### ISSUE TITLE
NativeScriptException: Cannot find runtime for instance=android.net.ConnectivityManager_NetworkCallback

### ISSUE THREAD

**Issue by felixkrautschuk** [NativeScript/NativeScript#10002]
### Issue Description

For some time now, I see some crash reports in the Google Play Console like this:

> Fatal Exception: com.tns.NativeScriptException: Cannot find runtime for instance=android.net.ConnectivityManager_NetworkCallback_vendor_38342_42_NetworkCallbackImpl@6a3a5a9
>   at com.tns.Runtime.callJSMethodImpl (Runtime.java:1181)
>   at com.tns.Runtime.callJSMethod (Runtime.java:1175)
>   at com.tns.Runtime.callJSMethod (Runtime.java:1153)
>   at com.tns.Runtime.callJSMethod (Runtime.java:1149)
>   at android.net.ConnectivityManager_NetworkCallback_vendor_38342_42_NetworkCallbackImpl.onAvailable
>   at android.net.ConnectivityManager$NetworkCallback.onAvailable (ConnectivityManager.java:3725)
>   at android.net.ConnectivityManager$NetworkCallback.onAvailable (ConnectivityManager.java:3707)
>   at android.net.ConnectivityManager$CallbackHandler.handleMessage (ConnectivityManager.java:4031)
>   at android.os.Handler.dispatchMessage (Handler.java:106)
>   at android.os.Looper.loopOnce (Looper.java:226)
>   at android.os.Looper.loop (Looper.java:313)
>   at android.os.HandlerThread.run (HandlerThread.java:67)

and this:

> Fatal Exception: com.tns.NativeScriptException: Cannot find runtime for instance=android.net.ConnectivityManager_NetworkCallback_vendor_38342_42_NetworkCallbackImpl@6a3a5a9
>   at com.tns.Runtime.callJSMethod (Runtime.java:1172)
>   at com.tns.Runtime.callJSMethod (Runtime.java:1153)
>   at com.tns.Runtime.callJSMethod (Runtime.java:1149)
>   at android.net.ConnectivityManager_NetworkCallback_vendor_38342_42_NetworkCallbackImpl.onCapabilitiesChanged
>   at android.net.ConnectivityManager$CallbackHandler.handleMessage (ConnectivityManager.java:4082)
>   at android.os.Handler.dispatchMessage (Handler.java:106)
>   at android.os.Looper.loopOnce (Looper.java:226)
>   at android.os.Looper.loop (Looper.java:313)
>   at android.os.HandlerThread.run (HandlerThread.java:67)

Those crashes seem to occur on different Android versions like 10, 11, 12, 12L.

### Reproduction

Unfortunately, I see those crash reports only in Google Play Console, and I have never experienced them myself.

This is what I am doing:

```
//app.js
var connectivityModule = require("@nativescript/core/connectivity");

applicationModule.on(applicationModule.launchEvent, function(args) {
    connectivityModule.startMonitoring(function(newConnectionType) {
        switch(newConnectionType) {
            case connectivityModule.connectionType.none:
                //inform user about no connection
                break;
            case connectivityModule.connectionType.mobile:
            case connectivityModule.connectionType.wifi:
            case connectivityModule.connectionType.ethernet:
                //hide no-connection-errors
                break;
        }

        previousConnectionType = newConnectionType;
    });
}

applicationModule.run({ moduleName: "app-root" });
```

### Environment

```yaml
OS: macOS 12.5.1
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Shell: /bin/zsh
node: 16.15.0
npm: 8.18.0
nativescript: 8.2.3

# android
java: 11.0.11
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 13.2.1/13C100
cocoapods: 1.11.3
python: 2.7.18
python3: 3.9.7
ruby: 2.7.4
platforms: 
  - DriverKit 21.2
  - iOS 15.2
  - macOS 12.1
  - tvOS 15.2
  - watchOS 8.3
```

### Dependencies

```json
"dependencies": {
  "@nativescript-community/ui-material-tabs": "^6.2.13",
  "@nativescript-community/ui-pager": "^13.0.33",
  "@nativescript-community/ui-pulltorefresh": "^2.5.1",
  "@nativescript/core": "^8.2.4",
  "@nativescript/firebase-analytics": "^1.2.2",
  "@nativescript/firebase-core": "^1.2.2",
  "@nativescript/firebase-crashlytics": "^1.2.2",
  "@nativescript/firebase-messaging": "^1.2.2",
  "@nativescript/iqkeyboardmanager": "^2.0.0",
  "@nstudio/nativescript-floatingactionbutton": "^3.0.4",
  "@nstudio/nativescript-loading-indicator": "^4.1.2",
  "@nstudio/nativescript-snackbar": "^2.1.0",
  "@triniwiz/nativescript-toasty": "^4.1.3",
  "ff-admob": "file:../plugins/ff-admob",
  "ff-ads-consent-sdk": "file:../plugins/ff-ads-consent-sdk",
  "ff-nativelib": "file:../plugins/ff-nativelib",
  "nativescript-permissions": "1.3.8",
  "nativescript-ui-listview": "^10.1.1",
  "nativescript-ui-sidedrawer": "^10.0.2",
  "url-parse": "^1.5.10"
},
"devDependencies": {
  "@nativescript/android": "8.2.4",
  "@nativescript/ios": "8.0.0",
  "@nativescript/types": "8.2.0",
  "@nativescript/webpack": "4.1.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by farfromrefug** [comment]
@felixkrautschuk i have seen that kind of report locally with webview. Seems to be that some class are still existing while the runtime/app has been closed. Never managed to really pinpoint this one

**Comment by felixkrautschuk** [comment]
@farfromrefug when having a look into the Firebase Console (Crashlytics), it looks like this crash is happening right after session start (or within the first 5 seconds of app usage).

The first appearance of this crash goes back one year ago when we started using @nativescript/android 7.0.1.

**Comment by felixkrautschuk** [comment]
@farfromrefug thanks for your hint. Indeed, we never call `stopMonitoring` at the moment.

The problem is that the NativeScript exitEvent is never called on Android side when "swiping" the app out of "recent apps" or when closing it using the device back button.

However, I cloud try starting the monitoring in resume event and stopping monitoring in suspended event.

**Comment by farfromrefug** [comment]
@felixkrautschuk swiping should not be an issue because the app is killed, so is the runtime. So everything starts clean

**Comment by felixkrautschuk** [comment]
After moving the _startMonitoring/stopMonitoring_ functionality to _resume/suspend_ event handlers, the number of crashes dropped drastically.
So I'm gonna close this for now.
