### ISSUE TITLE
ns resources generate icons dont work in Nativescript 8.3.1

### ISSUE THREAD

**Issue by vicmasa** [NativeScript/NativeScript#10003]
### Issue Description

Hi.
The command to generate the **icons** does not work, but the command to generate **splashes** does.
Note: In Windows PC.

**ITS OK:** ns resources generate splashes app/images/logos/logo.png
**DONT WORK:** ns resources generate icons app/images/logos/logo.png

```
{
  "name": "HelloWorld",
  "main": "app/app.js",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@nativescript/core": "~8.3.0",
    "@nativescript/theme": "~3.0.2"
  },
  "devDependencies": {
    "@nativescript/android": "8.3.1",
    "@nativescript/webpack": "~5.0.6",
    "eslint": "^8.21.0"
  }
}

```

### Reproduction

1. Create proyect.
2. Add Image
3. Run command generate icons

### Relevant log output (if applicable)

```shell
Generating icons ...
Icons generation completed.
```

### Environment

Android

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by CatchABus** [comment]
This is related to https://github.com/NativeScript/nativescript-cli/pull/5667

**Comment by CatchABus** [comment]
Closed via https://github.com/NativeScript/nativescript-cli/pull/5667
