### ISSUE TITLE
Crash on wake from hibernate on Android

### ISSUE THREAD

**Issue by emiloberg** [NativeScript/NativeScript#1003]
Hi,

This is a describing a problem when "resuming" the app from hibernate state. I guess there's a well defined word for this, but; Well the app has been started and then put in the background it goes in some kind of hibernate state after a while. By "resuming" I mean: when a user is clicking the app icon again which wakes it from hibernate.

When doing that, the app crashes ("App unexpectedly stopped"). Here's the crash log as seen in Google Play Developer Console: https://gist.github.com/emiloberg/81271ba2427278aa4262

Most likely, the crash is always there. However, it's a little hard to test because you have to let the device put the app in "hibernate mode" (can you force this anyway?), but 2 out of 2 times it crashes.

**More info:**

Crash is from an device with `Android 4.4`

The App if you want to see the source code: https://github.com/emiloberg/oppna-program-reklistan-app

```
▶ tns --version
1.4.2
```

**Comment by x4080** [comment]
Hi Emil, check out this link https://github.com/NativeScript/android-runtime/issues/241

**Comment by N3ll** [comment]
The discussion about this issue is moved to https://github.com/NativeScript/android-runtime/issues/241.
