### ISSUE TITLE
Allow FormattedString in Button

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#10043]
### Is your feature request related to a problem? Please describe.

Hi,

There is some limitation if we need to put an icon with text into a button, the font-familly of the `fa` class will prime and the text generated as below.

```xml

<Button text="{{ ic('fa-user') + ' ' + L('create_trip') }}" class="fa create-trip -outline -rounded-sm" style="height:50; border-color: blue;" />

```

![Sans titre](https://user-images.githubusercontent.com/18148534/192855801-a7698a92-3ed6-4ae0-a52e-cf470d5cfc3d.png)

To achieve a correct rendering I use a Label instead, but I should then work for the ripple and shadow...

### Describe the solution you'd like

It will be cool to have like this

```xml
<Button>
     <FormattedString>
         <span text="{{ 'fa-user' | fontawesome }}" class="fa" />
         <span text="Create new user" />
     </FormattedString>
</Button>
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by CatchABus** [comment]
@kefahB Afaik, this is already possible. I tested it in plain NativeScript and it works.

**Comment by rigor789** [comment]
As @CatchABus said, this is already possible:
```xml
<Button>
    <FormattedString>
        <span text="Hello" color="red" />
        <span text="World" />
    </FormattedString>
</Button>
```
![image](https://user-images.githubusercontent.com/879060/204239282-f286e7ea-a41a-4506-a499-99ca40ff0034.png)
