### ISSUE TITLE
Http.request - method POSt - headers:  { 'Authorization':'Bearer token' } is getting error: Unexpected token U in JSON position 0

### ISSUE THREAD

**Issue by ittrad-mobile-lab** [NativeScript/NativeScript#10074]
### Issue Description

When I do a HTTP request trying to add a custom header attribute I got the error:  Unexpected token U in JSON position 0
The problem is the space between Bearer and the token.

The question is how can I fix this issue?

### Reproduction

Try to add a header parameter/attribute like the one from example below to whatever HTTP request

The problem here is the space between Bearer and token 
which is getting the error: Unexpected token U in JSON position 0

```
Http.request({
      url: "URL",
      method: "POST",
      headers: { 'Authorization':'Bearer token' },
      content: httpBody.toString(),
    })
```

### Relevant log output (if applicable)

```shell
Unexpected token U in JSON position 0
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by CatchABus** [comment]
I don't think this is related to your header.
Try changing content value from `httpBody.toString()` to `JSON.stringify(httpBody)` and see how that goes.
