### ISSUE TITLE
Livesync with console.log

### ISSUE THREAD

**Issue by prijindal** [NativeScript/NativeScript#1009]
Currently you can't log anything with livesync
Any plans on upgrading livesync to show log output?

**Comment by x4080** [comment]
+1

**Comment by manijak** [comment]
+1

**Comment by N3ll** [comment]
This issue was moved to NativeScript/nativescript-cli#1130

**Comment by emiloberg** [comment]
Workaround in the meantime is to look at the actual log files. E.g.
```
tail -f ~/Library/Logs/CoreSimulator/<simulator-hash>/system.log
```

* iOS log can be found at `~/Library/Logs/CoreSimulator/<simulator-hash>/system.log`
* Android logs can be viewed by running `adb logcat`.  However, I highly recommend installing (pidcat)[https://github.com/JakeWharton/pidcat] which will let you view the logs for a specific application process (your app) as opposed to _all_ log statements the Android devices does.

**Comment by x4080** [comment]
The ios log can be opened with simulator menu debug log or something like that

**Comment by rclai** [comment]
@emiloberg I noticed this only works for the simulator, is there an equivalent tailing solution when running livesync on an iOS device with --watch?

**Comment by emiloberg** [comment]
@rclai You should always be able to grab it from XCode. Somewhere along the lines (going from memory here); Windows > Devices > {Select your tethered device} > Show log

**Comment by rclai** [comment]
I found the logs, but all I see are a bunch of Crash logs and nothing on the currently running app.

**Comment by ligaz** [comment]
Enjoy https://github.com/NativeScript/nativescript-cli/pull/1219

**Comment by rclai** [comment]
Yay! When's 1.5 scheduled to be released?

**Comment by valentinstoychev** [comment]
@rclai - 1.5 will be out next week.
