### ISSUE TITLE
Safari Extension within iOS

### ISSUE THREAD

**Issue by liamcharmer** [NativeScript/NativeScript#10095]
### Is your feature request related to a problem? Please describe.

I have prepared the iOS application with Nativescript, and then added in the Safari Extension doing the following:

![image](https://user-images.githubusercontent.com/10831349/202342485-fe36e4b2-8040-44a5-a2b8-c3fece0da91a.png)

![image](https://user-images.githubusercontent.com/10831349/202342498-a07a28e5-b5d1-433f-a84b-987ba9d09d2b.png)

![image](https://user-images.githubusercontent.com/10831349/202342521-2111914a-3d26-4ab5-b14e-87cd4278c8b3.png)

However, when I run the iOS app, it doesn't seem to show up in the Settings of iOS in safari extensions. (When doing this the normal way with a Safari Extension app works fine. 

Is this feature something that should be possible? I can't see why it shouldn't be possible..

React Native seems to have this module https://github.com/andrew-levy/react-native-safari-extension

### Describe alternatives you've considered

https://github.com/andrew-levy/react-native-safari-extension

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by shirakaba** [comment]
There's nothing NativeScript-specific that'll be obstructing this. NativeScript iOS apps are just Xcode projects with an iOS app target, so all the same rules apply to them. The Safari Extension target is largely independent of the app target.

An integration like React Native Safari Extension is not needed. It's a pretty cool project as it sets up a much better starter boilerplate than Xcode does, but it's all still stuff that you can set up yourself, in theory - my [LinguaBrowse](https://apps.apple.com/us/app/linguabrowse/id1281350165) app is a React Native iOS app with a Safari Extension added manually, for example.

All I can say is that, the development experience is dreadful and you will always have to try a bunch of different things before getting it working. As a sanity check, have you gone through these steps?

* https://developer.apple.com/documentation/safariservices/safari_web_extensions/running_your_safari_web_extension
* https://developer.apple.com/documentation/safariservices/safari_web_extensions/troubleshooting_your_safari_web_extension

I'll link to https://github.com/birchill/10ten-ja-reader as a working Safari Web Extension for another point of reference.
