### ISSUE TITLE
[RootLayout] TypeError: Cannot read property 'setOnTouchListener' of undefined

### ISSUE THREAD

**Issue by RGBvision** [NativeScript/NativeScript#10118]
### Issue Description

If two pages have a RootLayout element, then after backward navigation from the second page to the first page, an error will occur when trying to access the RootLayout (e.g. call `getRootLayout()`).
This is because RootLayout class called on the second page overwrites the global variable:
```
global.rootLayout = this;
```
So RootLayout of the first page "becomes" undefined.

Workaround (code for the first page):
```
export function navigatedTo(data: NavigatedData) {
  const page = <Page>data.object;
  if (data.isBackNavigation) {
    global.rootLayout = <RootLayout>page.getViewById('firstPageRootLayout');
  }
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by NathanWalker** [comment]
At the moment RootLayout is designed to be used once as the root element/component of entire app, hence it's name. There has been some discussion to potentially allow more than one but please only use one, and as the root node to entire app.
