### ISSUE TITLE
Modal presentation issue after pull request #10075

### ISSUE THREAD

**Issue by BozzaDaniel** [NativeScript/NativeScript#10115]
### Issue Description

Following the merging of the pull request of #10075 the content of a modal is missing until the animation completes, see attached video, if the modal contains a frame. If no frame is present the content is visible.

With a frame in the modal:

https://user-images.githubusercontent.com/15250117/204817823-b7d4a3bc-33fb-4fdf-a96b-29b7ddf9a012.mov

With no frame in the modal:

https://user-images.githubusercontent.com/15250117/204818099-aef0d2fc-bc86-4dc8-9e94-ce5ef6d6e6f1.mov

This happens because it's pushing the content of the frame only after transitionCoordinator completes it's animation.

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by PedroAnibarro1** [comment]
Hi!

I'm having a similar issue. 


https://user-images.githubusercontent.com/8890152/208448987-4d3bdf7b-c35d-4679-b3a6-19b0181fa569.MP4

**Comment by CatchABus** [comment]
@dgmachado I think that iOS #10075 patch needs a bit of tweaking.
It looks like there are modal animation problems.

**Comment by Woongsik** [comment]
Hi, I am suffering from this issue. Any updates for this?

**Comment by NathanWalker** [comment]
@Woongsik fix for this will go out with 8.4.3 shortly with ref'd PR.
