### ISSUE TITLE
@nativescript/core/utils/utils stopped working in 8.4

### ISSUE THREAD

**Issue by vicmasa** [NativeScript/NativeScript#10126]
### Issue Description

It is not possible to import utils, in version 8.4

### Reproduction

1. const utils = require('@nativescript/core/utils/utils')
2. function openUrl(){
        utils.openUrl('https://google.com')
}

### Relevant log output (if applicable)

```shell
Module not found: Error: Can't resolve '@nativescript/core/utils/utils' in '/Users/victor/invian/ns/invian/app/components/login'
resolve '@nativescript/core/utils/utils' in '/Users/victor/invian/ns/invian/app/components/login'
  Parsed request is a module
  using description file: /Users/victor/invian/ns/invian/package.json (relative path: ./app/components/login)
    resolve as module
      looking for modules in /Users/victor/invian/ns/invian/node_modules
        existing directory /Users/victor/invian/ns/invian/node_modules/@nativescript/core
          using description file: /Users/victor/invian/ns/invian/node_modules/@nativescript/core/package.json (relative path: .)
            using description file: /Users/victor/invian/ns/invian/node_modules/@nativescript/core/package.json (relative path: ./utils/utils)
              no extension
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils doesn't exist
              .ios.ts
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.ios.ts doesn't exist
              .ts
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.ts doesn't exist
              .ios.js
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.ios.js doesn't exist
              .js
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.js doesn't exist
              .ios.mjs
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.ios.mjs doesn't exist
              .mjs
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.mjs doesn't exist
              .ios.css
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.ios.css doesn't exist
              .css
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.css doesn't exist
              .ios.scss
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.ios.scss doesn't exist
              .scss
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.scss doesn't exist
              .ios.json
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.ios.json doesn't exist
              .json
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.json doesn't exist
              as directory
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils doesn't exist
      /Users/victor/invian/ns/invian/app/components/login/node_modules doesn't exist or is not a directory
      /Users/victor/invian/ns/invian/app/components/node_modules doesn't exist or is not a directory
      /Users/victor/invian/ns/invian/app/node_modules doesn't exist or is not a directory
      looking for modules in /Users/victor/invian/ns/invian/node_modules
        existing directory /Users/victor/invian/ns/invian/node_modules/@nativescript/core
          using description file: /Users/victor/invian/ns/invian/node_modules/@nativescript/core/package.json (relative path: .)
            using description file: /Users/victor/invian/ns/invian/node_modules/@nativescript/core/package.json (relative path: ./utils/utils)
              no extension
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils doesn't exist
              .ios.ts
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.ios.ts doesn't exist
              .ts
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.ts doesn't exist
              .ios.js
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.ios.js doesn't exist
              .js
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.js doesn't exist
              .ios.mjs
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.ios.mjs doesn't exist
              .mjs
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.mjs doesn't exist
              .ios.css
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.ios.css doesn't exist
              .css
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.css doesn't exist
              .ios.scss
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.ios.scss doesn't exist
              .scss
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.scss doesn't exist
              .ios.json
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.ios.json doesn't exist
              .json
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils.json doesn't exist
              as directory
                /Users/victor/invian/ns/invian/node_modules/@nativescript/core/utils/utils doesn't exist
      /Users/victor/invian/ns/node_modules doesn't exist or is not a directory
      /Users/victor/invian/node_modules doesn't exist or is not a directory
      /Users/victor/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
 @ ./app/ sync .(xml%7Cjs%7Cs?css)$ ./components/login/login.js
 @ ./node_modules/@nativescript/webpack/dist/stubs/virtual-entry-javascript.js 3:16-89

webpack 5.75.0 compiled with 2 errors and 6 warnings in 271 ms
Webpack compilation complete. Watching for file changes.
```

### Environment

{
  "name": "abc",
  "main": "app/app.js",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@nativescript/background-http": "^6.0.0",
    "@nativescript/camera": "^5.0.15",
    "@nativescript/core": "~8.4.0",
    "@nativescript/geolocation": "^8.1.0",
    "@nativescript/google-maps": "^1.4.9",
    "@nativescript/social-share": "^2.3.0",
    "@nativescript/theme": "~3.0.2",
    "@nativescript/ui-charts": "^0.2.4",
    "@nstudio/nativescript-exoplayer": "^6.0.1",
    "nativescript-sqlite": "^2.8.6",
    "nativescript-videoplayer": "^5.0.1"
  },
  "devDependencies": {
    "@nativescript/ios": "8.4.0",
    "@nativescript/webpack": "~5.0.12"
  }
}

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by NathanWalker** [comment]
Hi @vicmasa see the release notes at very bottom: https://github.com/NativeScript/NativeScript/releases/tag/8.4.0-core

**Comment by rajeshjadidminc** [comment]
const utils = require('@nativescript/core/utils/utils') this is resolved as per your previous comment but

Facing the below issue on migrating to 8.4 

Module not found: Error: Can't resolve '@nativescript/core/utils/utils' in '.../node_modules/@nota/nativescript-accessibility-ext/utils'
resolve '@nativescript/core/utils/utils' in '..../node_modules/@nota/nativescript-accessibility-ext/utils'
  Parsed request is a module
  using description file:...../node_modules/@nota/nativescript-accessibility-ext/package.json (relative path: ./utils)

**Comment by serrg1994** [comment]
Please check release notes for 8.4.0. There is described breaking changes about utils


utils/utils is just Utils

BEFORE
import { layout } from '@nativescript/core/utils/utils'
AFTER
import { Utils } from '@nativescript/core'

Utils.layout
This will affect some plugins. If you use a plugin that encounters this issue you can do the following:

Add a quick webpack alias to mitigate for now:
webpack.chainWebpack(config => {
    config.resolve.alias.set('@nativescript/core/utils/utils', '@nativescript/core/utils');
    config.resolve.alias.set('tns-core-modules/utils/utils', '@nativescript/core/utils');
    config.resolve.alias.set('tns-core-modules', '@nativescript/core');
Contribute a pull request to the plugin author.

**Comment by serrg1994** [comment]
@rajeshjadidminc also please let know if iOS app will not start lagging after upgrading to 8.4. As this pluggin is already part of core framework, in 8.4 there are some conflicts and for me it started lagging

**Comment by rajeshjadidminc** [comment]
I have updated as per the release notes but facing an issue due to @nota/nativescript-accessibility-ext/ they haven't update the file.

**Comment by serrg1994** [comment]
Can you please share webpack config file ?

**Comment by rajeshjadidminc** [comment]
const webpack = require("@nativescript/webpack");

module.exports = (env) => {
  webpack.init(env);

  // Learn how to customize:
  // https://docs.nativescript.org/webpack
  // alias tns-core-modules -> @nativescript/core
  webpack.chainWebpack((config) => {
    config.resolve.alias.set(
      "@nativescript/core/utils/utils",
      "@nativescript/core/utils"
    );
    config.resolve.alias.set(
      "tns-core-modules/utils/utils",
      "@nativescript/core/utils"
    );
    config.resolve.alias.set("tns-core-modules", "@nativescript/core");
  });
  return webpack.resolveConfig();
};

**Comment by serrg1994** [comment]
For what purposes are you using this plugin? Maybe you event do not need it as this plugin is part of core

**Comment by rajeshjadidminc** [comment]
Yes I know but this is due npm plugin **@nota/nativescript-accessibility-ext** issue they have replaced this but haven't published the new version

**Comment by serrg1994** [comment]
> const webpack = require("@nativescript/webpack");
> 
> module.exports = (env) => { webpack.init(env);
> 
> // Learn how to customize: // https://docs.nativescript.org/webpack // alias tns-core-modules -> @nativescript/core webpack.chainWebpack((config) => { config.resolve.alias.set( "@nativescript/core/utils/utils", "@nativescript/core/utils" ); config.resolve.alias.set( "tns-core-modules/utils/utils", "@nativescript/core/utils" ); config.resolve.alias.set("tns-core-modules", "@nativescript/core"); }); return webpack.resolveConfig(); };

Yes it's identical as in release notes. I don't use the same config as I in my project copied plugin to separate folder and changed pathes here. 

But for example for another plugin resolving aliases helped me

	webpack.chainWebpack(config => {
		config.resolve.alias.set("application", "@nativescript/core/application");
	})

**Comment by serrg1994** [comment]
@rajeshjadidminc Are you using this plugin for font scaling ?

**Comment by rajeshjadidminc** [comment]
I am using this for accessibility support.

**Comment by serrg1994** [comment]
> I am using this for accessibility support.

You don't need this plugin. Please refer to documentation https://docs.nativescript.org/interaction.html#accessibility-aka-a11y

@CatchABus please correct me if I'm wrong

**Comment by serrg1994** [comment]
> I am using this for accessibility support.

https://blog.nativescript.org/nativescript-8-announcement/#accessibility%3A-first-class-a11y

**Comment by rajeshjadidminc** [comment]
We have already used this plugin and its supporting since 2 years back, i need change whole code in my app.

**Comment by serrg1994** [comment]
> We have already used this plugin and its supporting since 2 years back, i need change whole code in my app.

Also please refer to this thread in discord https://discord.com/channels/603595811204366337/615931901756309514/threads/1048667697493319851

I'm also using this plugin and I cannot update to ns 8.4

**Comment by CatchABus** [comment]
> We have already used this plugin and its supporting since 2 years back, i need change whole code in my app.

Afaik, core has imported plugin itself so API shouldn't be different.
There is currently an issue with font scale due to missing sass files from plugin but I believe we'll take care of this soon.
