### ISSUE TITLE
TextField/TextView CSS color not applied to cursor

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#1012]

**Comment by sivsushruth** [comment]
How to make it work for android ?

**Comment by darmie** [comment]
This bug is on Android too.. how do I fix it?

**Comment by joshcomley** [comment]
@enchev do you have any solution for this on Android? I seem to be unable to change the cursor colour from ever being blue (at least via CSS). I can change the line colour as you recently implemented a solution for that using `border-color` :) But is it possible to change the cursor, also?
