### ISSUE TITLE
Error: Build input file cannot be found, when building NativeScript application with Xcode 14.1 using m1 mac

### ISSUE THREAD

**Issue by wontroba666** [NativeScript/NativeScript#10144]
### Issue Description

When building nativescript cross-platform application for ios, i get the following error.

Build input file cannot be found: 'xxx/platforms/ios/Build/Products/Debug-iphonesimulator/metadata-arm64.bin'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

### Reproduction

xcode 14.1
✔ Component nativescript has 8.4.0 version and is up to date.
✔ Component @nativescript/core has 8.4.1 version and is up to date.
✔ Component @nativescript/ios has 8.4.0 version and is up to date.

i would be very grateful for help and a way out of this

### Please accept these terms

- [x] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by dancosta-fed** [comment]
Hi ya,
Well, I've been facing this issue as well. I found a thread where one of the replies had the answer I was looking for. I'm not sure if this is going to help you. But it helped me:

```
1/ Change workspace setting > Build location > Custom & relative to workspace

2/ Go to "build phase" then "prebuild nativescript" then add the name of directory&file required in "output files" (for me /my_project/platforms/ios/build/..../arm64 etc...).
```

Here's the original, https://developer.apple.com/forums/thread/716483, from JulienGP.

**Comment by rigor789** [comment]
This should be fixed by https://github.com/NativeScript/ios/commit/3b1eafc4da502404ab8c50854016ff059ae8eff8

If you've recently updated the `@nativescript/ios` package, it's always a good idea to run `ns clean` to make sure the `platforms` folder is re-generated with the latest configuration from the runtime.

**Comment by donny08** [comment]
@rigor789 I followed your steps for nativescript/ios but still i am getting error as`Build input file cannot be found: 'xxx/platforms/ios/Build/Products/Debug-iphonesimulator/metadata-arm64.bin'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?`

**Comment by triniwiz** [comment]
@donny08 upgrade to a later or the latest version 8.6.x should resolve the issue.

**Comment by donny08** [comment]
@triniwiz 
Thanks, it worked.
