### ISSUE TITLE
Button wrapText property

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#1014]
https://gist.github.com/jbristowe/0d3ef7c9214e82487b52

**Comment by ligaz** [comment]
Will this work from CSS as well?

**Comment by toddanglin** [comment]
Wow! What speed. Looking forward to 1.5. :100:

**Comment by enchev** [comment]
@ligaz Unfortunately no. We've still not decided how to implement this properly since the property is available only on some of the components. We have other similar scenarios not implemented as well.

**Comment by enchev** [comment]
@ligaz I spoke to soon. Actually we have such properties (font-* for example) and we can implement wrapping as well. The question here however will be should we add [word-wrap](http://www.w3schools.com/cssref/css3_pr_word-wrap.asp) or [text-wrap](http://www.w3schools.com/cssref/css3_pr_text-wrap.asp)?

**Comment by ligaz** [comment]
I think `text-wrap` is deprecated.

**Comment by enchev** [comment]
Ok. Here is the issue: https://github.com/NativeScript/NativeScript/issues/1034

**Comment by ligaz** [comment]
:+1:

**Comment by enchev** [comment]
Hey folks,

It seems that `word-wrap` is not what we want. Our Button wrapText property will simply tell if the button title will wrap or not while with CSS `word-wrap` you can specify if you can break word when wrapping not switching on/off the wrap itself. There is better property for this in CSS: [white-space](http://www.w3schools.com/cssref/pr_text_white-space.asp).

What do you think? How we should implement properly wrap on/off with CSS?

Thanks!

**Comment by bundyo** [comment]
I think you can implement [white-space: **nowrap** and **normal**](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) in CSS, maybe with the difference that in NativeScript buttons the default value to be **nowrap** contrary to HTML which wraps everything by default. I wonder if you can also implement [default](http://hg.mozilla.org/mozilla-central/file/tip/layout/style/html.css) [stylesheets](http://trac.webkit.org/browser/trunk/Source/WebCore/css/html.css) and just place the default value of button wrapping there.

The [word-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/word-wrap) CSS property for HTML is to specify how exactly the text wraps but is not intended to stop it from wrapping.

**Comment by ligaz** [comment]
:+1: for default stylesheets.

**Comment by enchev** [comment]
Thanks @bundyo! In this case I will rename [this issue](https://github.com/NativeScript/NativeScript/issues/1034) to *Support CSS white-space: nowrap and normal*.
