### ISSUE TITLE
[IOS] Navigation transition freeze or break view

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#10149]
### Issue Description

Hi @NathanWalker,

I am experiencing a strange think with the navigation when I set transition, I didn't test all of them but for instance `slideRight` and `slideTop` causing problem.

- SlideRight freeze the navigation in some context 
- SlideTop break the view when navigate back only as in the image below, putting slideLeft resolve the issue !

<img src="https://user-images.githubusercontent.com/18148534/209918566-054cee85-0f55-42ed-b564-7dd21d9c61f4.png" width="300" />
<img src="https://user-images.githubusercontent.com/18148534/209918579-4b411f79-ada8-49b4-b4d7-9fd1eb4a7f21.png" width="300" />

I am using the latest version NS (8.4.2)

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by asharghi** [comment]
The bug has been narrowed down to this: https://discord.com/channels/603595811204366337/1041733427696771123/1050009146310791209  @edusperoni has to step in. I have created a demo for this bug: https://github.com/asharghi/NavigationTest

**Comment by kefahB** [comment]
@asharghi thanks for the information .. this channel is a private one ? can't access !

**Comment by asharghi** [comment]
> @asharghi thanks for the information .. this channel is a private one ? can't access !

It's in #general on the Discord server, you may have to log in. Good news is Nathan Walker said he will have a patch for this in 8.4.3 🎉

**Comment by kefahB** [comment]
I am logged in but cant access!

cool .. it is a must .. I have edited all navigation on my app without the transition to go prod. The navigation sims bizarre 😄
