### ISSUE TITLE
Adding Section and Index List in ListView

### ISSUE THREAD

**Issue by TobiasHennig** [NativeScript/NativeScript#1016]
I need to implement sections and and index list (a-z) in one of my ListViews like in this image:
![image](https://cloud.githubusercontent.com/assets/3656893/10880023/1aee2c6e-8158-11e5-9ae2-e544ba23f0e6.png)

Is this ...
    a.) possible with the current version of NativeScript?
    b.) possible with a bit "native hacking"?
    c.) a planned feature?

**Comment by manijak** [comment]
I believe this is available in the telerik-nativescript-ui package? The official Telerik ListView component.
https://www.nativescript.org/blog/telerik-ui-for-nativescript-preview-2-is-here-introducing-radlistview

**Comment by valentinstoychev** [comment]
Hi Tobias - @ginev can elaborate more here, but us manijak mentioned this is a planned feature for the RadListView as part of UI for NativeScript.

**Comment by ginev** [comment]
This feature will be supported out-of-the-box by RadListView for its official release.

**Comment by alexrainman** [comment]
I wonder why, if all this functionality is available on each platform: pulltorefresh, load more on demand, cell swipe actions, sections and index lost; why it needs to be included in a commercial product?

**Comment by TobiasHennig** [comment]
I basically agree with @alexrainman. Perhaps, there could be a free "lite" version with the standard function (like sections and index list)? The function "load more on demand" is already implemented with the "[loadMoreItems](https://docs.nativescript.org/ApiReference/ui/list-view/HOW-TO.html)" attribute.

**Comment by rajivnarayana** [comment]
You can use https://www.npmjs.com/package/nativescript-sectioned-list-view for showing section headers until then.

**Comment by blaur** [comment]
@manijak You mention that it will be apart of the ui package. Could you elaborate? I cannot get it to work.

**Comment by stefalda** [comment]
Hi, I couldn't find any mention of "sections" in the RadListView documentation... someone has some details about it? Thanks

**Comment by KoenPaas** [comment]
Any news regarding this topic?
