### ISSUE TITLE
Memory leak in Android on navigation

### ISSUE THREAD

**Issue by vallemar** [NativeScript/NativeScript#10166]
### Issue Description

I have created a new project using vue2 and when I browse I have memory leaks. It seems that the class of the leaks is FragmentClass. This is a screenshot from android studio, where you can see the forward and backward navigation leaks. I would understand that forward navigation detects it as a leak but backwards I think it should not be

![image](https://user-images.githubusercontent.com/15719383/211856864-4d8ea560-131e-4326-9f75-f410cf263331.png)

I have also used [LeakCanary ](https://square.github.io/leakcanary/getting_started/)to test and it seems that I have the same result. It also detects these leaks:

![photo_2023-01-11_17-14-17](https://user-images.githubusercontent.com/15719383/211858149-931121d7-f8b9-4c9c-8cea-86f77dc37860.jpg)

I have an android application that when it has been open for a long time it becomes very slow, totally different from when it only takes a few minutes. I don't know if it's because of this or because of other issues I've found here:
https://github.com/NativeScript/NativeScript/issues/9752

**Comment by edusperoni** [comment]
please add a `gc()` call either in a setInterval or after each navigation. Most of the times you get FragmentClass memory leaks they are related to timing issues (JS didn't gc it yet, so native thinks we're holding strong refs when it's going to be released in the next gc call).

The way android detects fragment class leaks is that it will wait some time after `onDestroy` is called and if the class is still in memory it shows as a leak.
