### ISSUE TITLE
BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

### ISSUE THREAD

**Issue by iamabs2001** [NativeScript/NativeScript#10174]
### Issue Description

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/abhijeetsharma/Documents/Abhijeet/hello-nativescript/platforms/tempPlugin/core/build.gradle' line: 183

* What went wrong:
A problem occurred evaluating root project 'core'.
> Could not open dsl generic class cache for script '/Users/abhijeetsharma/Documents/Abhijeet/hello-nativescript/App_Resources/Android/before-plugins.gradle' (/Users/abhijeetsharma/.gradle/caches/7.5/scripts/dryivtzqi4x0rfhi73c0kcgf2).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

### Reproduction

1. create tns app
2. tns run android
3. zulu 19 Java 
4. BUG!

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
The gradle plugin we are using (7.4, or 7.5 can't remember exactly) doesn't support java 19 yet. I believe 18 might work.

**Comment by aryzing** [comment]
When using the most recent versions of NativeScript as of today,

```
"@nativescript/core": "8.5.9",
"@nativescript/android": "8.5.3",
```

it seems that Gradle 7.5 is being used, since that's what appears in the logs when running `ns run android`,

```
...
Downloading https://services.gradle.org/distributions/gradle-7.5-bin.zip
```

As per the [Gradle compat table](https://docs.gradle.org/current/userguide/compatibility.html#java), this version of Gradle requires Java

**Comment by rigor789** [comment]
@aryzing good idea to reference that table in the setup docs. I would add that to the beta docs (that will soon replace our current docs): https://beta.docs.nativescript.org/setup/

The source for that is here: https://github.com/NativeScript/docs/tree/main/content/setup

The gradle version comes from the android runtime itself, I believe this one: https://github.com/NativeScript/android/blob/main/test-app/gradle/wrapper/gradle-wrapper.properties

Not sure if worth mentioning that, or just adding a table of runtime/gradle versions instead?

**Comment by aryzing** [comment]
> Not sure if worth mentioning that, or just adding a table of runtime/gradle versions instead?

Given the table, how would users know which version of Java to pick? Do most users know what version of Gradle they need to look for in the table? 

I dug it up from the logs after I saw the build errors, that's why I'm asking if there's a more straightforward way to inform users during the setup rather than expecting them to troubleshoot errors.

**Comment by rigor789** [comment]
@aryzing something like this maybe?

| `@nativescript/android` | Recommended Java version |
| ----------------------- | ------------------------ |
| v7.0.0 (Gradle, 7.4)    | 1.8 - 11.0               |
| v8.5.2 (Gradle, 7.5)    | 11.0 - 17.0              |

(note: just **example ranges/versions in this table**)
