### ISSUE TITLE
Barcode EAN13, CODE39, etc generator like JSBarcode

### ISSUE THREAD

**Issue by ittrad-mobile-lab** [NativeScript/NativeScript#10190]
### Is your feature request related to a problem? Please describe.

I'm really surprise not finding a plugin to generate (print to the client) all kind of barcodes (EAN13, CODE39, ITF, etc.)

### Describe the solution you'd like

I'd like to have a barcode generator plugin or an existing barcode scanner with a barcode show method incorporated to print to the client the scanned barcodes (all kind of barcodes)

### Anything else?

I tried to integrate the JSBarcode (https://www.npmjs.com/package/jsbarcode) 
on my nativescript-angular app but no success (see image below)

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/46108848/215619625-13c622e5-12d1-4718-ae98-ddc651748eb5.png">

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by vallemar** [comment]
This won't work, you are trying to use a native html library. You need to generate an image or svg from the barcode and then add it to the NS image or svg element. Also, the svg view does not exist in NS core. You need to use one of these plugins:
- https://github.com/nativescript-community/ui-canvas#nativescript-communityui-svg
- https://github.com/NativeScript/canvas

I also see that you are trying to create a div element in nativescript, this won't work either.

**Comment by triniwiz** [comment]
It’s possible it could work with the canvas but I’ll need to test/check which APIs are being called

**Comment by SmailHammour** [comment]
I was able to integrate JSBarcode into my project with something like this;

```
import {DOMImplementation, XMLSerializer} from 'xmldom';
import JsBarcode, {Options as jsBarcodeOptions} from 'jsbarcode';
...

const xmlSerializer = new XMLSerializer();
const document = new DOMImplementation().createDocument('http://www.w3.org/1999/xhtml', 'html', null);
const svgNode = document.createElementNS('http://www.w3.org/2000/svg', 'svg');

const options: jsBarcodeOptions = {
  xmlDocument: document,
  // ... other options
};

JsBarcode(svgNode, this.barcodeForm.get('barcode').value, options);

const value: string = xmlSerializer.serializeToString(svgNode); // this contains an SVG string
```

Hope this helps! Good luck!

**Comment by ittrad-mobile-lab** [comment]
> I was able to integrate JSBarcode into my project with something like this;
> 
> ```
> import {DOMImplementation, XMLSerializer} from 'xmldom';
> import JsBarcode, {Options as jsBarcodeOptions} from 'jsbarcode';
> import {Buffer} from 'buffer';
> ...
> 
> const xmlSerializer = new XMLSerializer();
> const document = new DOMImplementation().createDocument('http://www.w3.org/1999/xhtml', 'html', null);
> const svgNode = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
> 
> const options: jsBarcodeOptions = {
>   xmlDocument: document,
>   // ... other options
> };
> 
> JsBarcode(svgNode, this.barcodeForm.get('barcode').value, options);
> 
> const value: string = xmlSerializer.serializeToString(svgNode); // this contains an SVG string
> 
> const buff = Buffer.from(value.slice(1, -1), 'utf-8');
> const base64 = buff.toString('base64'); // convert to base64
> ```
> 
> Hope this helps! Good luck!

Thank you very much for your answer! 

And what should I do with the base64 value after that?

**Comment by SmailHammour** [comment]
> > I was able to integrate JSBarcode into my project with something like this;
> > ```
> > import {DOMImplementation, XMLSerializer} from 'xmldom';
> > import JsBarcode, {Options as jsBarcodeOptions} from 'jsbarcode';
> > import {Buffer} from 'buffer';
> > ...
> > 
> > const xmlSerializer = new XMLSerializer();
> > const document = new DOMImplementation().createDocument('http://www.w3.org/1999/xhtml', 'html', null);
> > const svgNode = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
> > 
> > const options: jsBarcodeOptions = {
> >   xmlDocument: document,
> >   // ... other options
> > };
> > 
> > JsBarcode(svgNode, this.barcodeForm.get('barcode').value, options);
> > 
> > const value: string = xmlSerializer.serializeToString(svgNode); // this contains an SVG string
> > 
> > const buff = Buffer.from(value.slice(1, -1), 'utf-8');
> > const base64 = buff.toString('base64'); // convert to base64
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope this helps! Good luck!
> 
> Thank you very much for your answer!
> 
> And what should I do with the base64 value after that?

You can generate an `ImageSource` from it. Whatever fits your need :-)

**Comment by ittrad-mobile-lab** [comment]
> nativescript-svg

SFSG :) 
Many thanks again.

Could you please add the tag you use?

 <SVGImage src="???" width="256" height="256"></SVGImage>
or
 <CanvasView width="100" height="100" (draw)="onDraw($event)"></CanvasView> 

?

**Comment by ittrad-mobile-lab** [comment]
GOTCHA!

Please find here (look for te coments): 
https://stackoverflow.com/questions/42113810/generate-barcode-in-angular-2-nativescript/75328965#75328965
my solution

THANK YOU ALL!

**Comment by ittrad-mobile-lab** [comment]
Please see the comments above to  get the solution
