### ISSUE TITLE
Support for WHATWG URL API 

### ISSUE THREAD

**Issue by darklight365** [NativeScript/NativeScript#10232]
### Is your feature request related to a problem? Please describe.

The URL API/constructor is not currently supported in core NativeScript.

### Describe the solution you'd like

Include a polyfill in NativeScript core so that it would be possible to make use of this standardized API: see https://developer.mozilla.org/en-US/docs/Web/API/URL/URL for reference

### Describe alternatives you've considered

Apply a local polyfill.

### Anything else?

Currently the following runtime error is encountered when attempting to use the URL constructor:
`const url = new URL("https://nativescript.org"); //ReferenceError: URL is not defined`

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by darklight365** [comment]
I'm aware that we could locally polyfill this (see considerations) within our app, but since this is a supported API across all common JavaScript implementations (see provided link) I think it would benefit NativeScript to provide the polyfill.

My reason for saying this is: as more pure JS libraries start to use this API those libraries will be unusable within a NativeScript app without people patching webpack (or their apps) with their own polyfills.

The provided library would not be a good fit for NativeScript since it uses the DOM to fill the gap to create a "valid" href link: see https://github.com/lifaon74/url-polyfill/blob/master/url-polyfill.js#L297

The polyfill mentioned within the referenced Mozilla Developer Docs would likely be a better fit: core-js

**Comment by prestopasto** [comment]
@rigor789 How does the NativeScript team feel about polyfilling something like this in core?  Would they be open to a PR?  Or is the recommended course for the end user to polyfill it themselves when needed?

**Comment by rigor789** [comment]
@prestopasto I'm for it personally, but we'll need to discuss on the next TSC meeting. Perhaps a good initial step would be to do the polyfill in a plugin that uses the webpack plugin api to automatically set things up (https://docs.nativescript.org/webpack.html#plugin-api) and if it's something we all agree should be in core, we'll have a clear path from the plugin to core.

**Comment by prestopasto** [comment]
@rigor789 Thank you for the feedback and direction!  I'm hoping to get some time to play with it soon.

**Comment by farfromrefug** [comment]
Personally I would not want that enabled by default. URL polyfills are pretty big and not that commonly use. Think an opt in option in our webpack setup would be best

**Comment by ray007** [comment]
Recent nativescript (version `8.8.x`) seems to have something native on `global.URL`, but it's buggy as hell.
Doesn't work with a present but undefined variable as 2nd parameter, adds query parameters to pathname on parsing, not sure what else goes wrong.

Could we please either get it fixed or get rid of it?

**Comment by rigor789** [comment]
@ray007 please open a new issue with an example, newer versions use ada for `URL` and it should be spec compliant. Also make sure you don't have an old polyfill replacing it.

**Comment by ray007** [comment]
My own polyfill works fine (and is not that large), so I'll just overwrite the native object.
I can live with buggy upstream URL.

**Comment by anonrig** [comment]
@ray007 I'm the author of Ada URL parser. Can you share a reproducible bug report? I'm more than happy to investigate.

**Comment by rigor789** [comment]
@ray007 we want to make sure it's working as expected, but as @anonrig said we need a reproducible example of an issue for it to be actionable on our side. 

"buggy as hell" isn't actionable I'm afraid.

**Comment by ray007** [comment]
I already mentioned 2 cases in my description, which should be very simple to verify:

1. try `new URL(absStringUrl, undefinedVar)` - does not create a valid `URL`
2. try parsing a complete url with pathname and query parameters, the `pathname` property of the url will contain the query (with `%3F` instead of `?`), and the `query` property will be empty.

**Comment by rigor789** [comment]
Thanks for test cases, we'll make sure these work as expected.

**Comment by rigor789** [comment]
@ray007 I fixed both of the issues, we'll have these in a release soon, thanks for pointing them out.

- https://github.com/NativeScript/ios/pull/263
- https://github.com/NativeScript/android/pull/1826
