### ISSUE TITLE
Intermittent Android Crashing Events

### ISSUE THREAD

**Issue by SeanKelly369** [NativeScript/NativeScript#10239]
### Issue Description

Using nativescript/core alpha, team members are reporting the following errors on Android 12 and 13 devices.  Both are a Samsung Galaxy, A90 and A13. ->

Error: java.lang.NoSuchMethodError: no non-static method "Lcom/telerik/android/primitives/widget/sidedrawer/RadSideDrawer;.setMainContent(Ljava/lang/String;)Ljava/io/File;"

Error: ClassNotFoundException when unmarshalling: androidx.core.widget.NestedScrollView$SavedState

Error: Unable to start activity ComponentInfo{com.$$.$$/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
Error: java.lang.NoSuchMethodError: no non-static method "Landroidx/appcompat/app/AppCompatActivity;.setContentView(Ljava/lang/String;)Ljava/io/File;

The onCreate failed occurs on an Android 9 moto g6 phone too.

Curiously, on a Realme GT Neo2, it has yet to crash at all when running on alpha

### Reproduction

NoSuchMethodError occurs when freshly install the app, delete the old version if it exists and open the app.  Twice when attempting to start the app will crash.  On the 3rd time opening it runs fine.

To trigger the other errors, start the app, let everything load and then force close.  Repeat these steps until the app crashes.  Another time the error occurs is when it is left idle and then restarted.  At times it crashes and attempts to restart, but gets stuck on the loading screen.

### Relevant log output (if applicable)

```shell
Error: java.lang.NoSuchMethodError: no non-static method "Lcom/telerik/android/primitives/widget/sidedrawer/RadSideDrawer;.setMainContent(Ljava/lang/String;)Ljava/io/File;"

Error: ClassNotFoundException when unmarshalling: androidx.core.widget.NestedScrollView$SavedState

Error: Unable to start activity ComponentInfo{com.$$.$$/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
Error: java.lang.NoSuchMethodError: no non-static method "Landroidx/appcompat/app/AppCompatActivity;.setContentView(Ljava/lang/String;)Ljava/io/File;
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by CatchABus** [comment]
About SavedState's `ClassNotFoundException`, it's fixed in core latest 8.4.8-next and 8.5.0 alpha so I suggest that you should try one of those versions or wait for official 8.5 release.

Regarding `NoSuchMethodError`, I've personally come across those too but haven't figured out when problem started and what's triggering it. If you provide me with more information we might be able to locate the problem.
For me, even 8.4 has that problem.

**Comment by SeanKelly369** [comment]
Thanks Dimitris-Rafail Katsampas,

These bugs are occurred on nativescript/core:alpha, which would be an alpha for 8.5.0, right?  I'll dig deeper.

NoSuchMethodError occurs right after the onCreate error.

**Comment by SeanKelly369** [comment]
@CatchABus the onCreate crash must be related to the `ClassNotFoundException` fix.  ScrollSavedState is null when first loading the app on some devices, perhaps?

**Comment by CatchABus** [comment]
> @CatchABus the onCreate crash must be related to the `ClassNotFoundException` fix. ScrollSavedState is null when first loading the app on some devices, perhaps?

I don't think this fix should cause such problems. Can you post full error stacktrace of that `onCreate` error?

**Comment by SeanKelly369** [comment]
I'm unable to run into a crash myself at any point, but others have.  I've post stacktraces over as soon as possible.  It may not be until Monday.

**Comment by CatchABus** [comment]
Regarding the `NoSuchMethodError` case, are you by any chance using a worker thread in your app?
I found this old case where developer faced the same problem: #9150
He explains how he solved it in the last post.

**Comment by SeanKelly369** [comment]
The sqlite software is using multithreading.  There is one file that appears to be using a webworker.  Thanks for your help.

**Comment by SeanKelly369** [comment]
2023-03-19T09:33:23.677Z; warning; Error; Could not load CSS from app.css: Error: require's first parameter should be string
2023-03-19T09:33:23.682Z; error; Error; Firebase Error: TypeError: Cannot read properties of undefined (reading 'setAttribute')
2023-03-19T09:33:23.805Z; log; Error; Error: ClassNotFoundException when unmarshalling: androidx.core.widget.NestedScrollView$SavedState
2023-03-19T09:33:23.806Z; error; Error; Firebase Error: TypeError: Cannot read properties of undefined (reading 'setAttribute')
2023-03-19T09:33:33.924Z; warning; Error; Could not load CSS from app.css: Error: require's first parameter should be string
2023-03-19T09:33:33.929Z; error; Error; Firebase Error: TypeError: Cannot read properties of undefined (reading 'setAttribute')
2023-03-19T09:33:34.101Z; log; Debug; applicationOn resumeEvent
2023-03-19T09:33:35.109Z; log; Debug; app.component connectivityService.isOnline switched to true
2023-03-19T09:33:35.113Z; log; Debug; app.component connectivityService.connectionType Mobile


Finally ran into a crash after leaving the app open in the background over night, the phone was on standby.  When turned on in the morning, the resumeEvent is occurring after the ClassNotFoundException occurs.  It's a rare edge case.  Ignore the CSS warning.

**Comment by SeanKelly369** [comment]
Stacktrace from one of the crashes ->

An uncaught Exception occurred on "main" thread. Unable to resume activity {com.app.place/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreateView failed Error: java.lang.NoSuchMethodError: no non-static method "Landroid/view/View;.setFocusable(Ljava/lang/String;)Ljava/io/File;"

StackTrace: java.lang.RuntimeException: Unable to resume activity {com.app.place/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreateView failed Error: java.lang.NoSuchMethodError: no non-static method "Landroid/view/View;.setFocusable(Ljava/lang/String;)Ljava/io/File;" at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4001) at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4033) at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1977) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:193) at android.app.ActivityThread.main(ActivityThread.java:6923) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870) Caused by: com.tns.NativeScriptException: Calling js method onCreateView failed Error: java.lang.NoSuchMethodError: no non-static method "Landroid/view/View;.setFocusable(Ljava/lang/String;)Ljava/io/File;" at com.tns.Runtime.callJSMethodNative(Native Method) at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302) at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188) at com.tns.Runtime.callJSMethod(Runtime.java:1175) at com.tns.Runtime.callJSMethod(Runtime.java:1153) at com.tns.Runtime.callJSMethod(Runtime.java:1149) at com.tns.FragmentClass.onCreateView(FragmentClass.java:55) at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104) at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524) at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261) at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899) at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817) at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760) at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:495) at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:312) at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1434) at android.app.Activity.performResume(Activity.java:7304) at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3993) ... 11 more Caused by: java.lang.NoSuchMethodError: no non-static method "Landroid/view/View;.setFocusable(Ljava/lang/String;)Ljava/io/File;" ... 29 more

**Comment by SeanKelly369** [comment]
The slower the device the app runs on, the greater the frequency of crashes.

**Comment by SeanKelly369** [comment]
Update:  It appears this is caused by a memory management issue.  There is a consistent crash after a number of force closes and restarts on devices.  The greater the available ram on the device, the greater number of restarts occur before a crash occurs.

**Comment by SeanKelly369** [comment]
Good news, the app does not crash when reactivated after being left idle when run on NativeScript/core 8.5.0-alpha-5 .

More good news, when force closing and restarting the app, by running gc(); in suspendEvent, there is no longer any crashing taking place - so far.

Therefore, I think it is safe to assume that not all objects and variables are being assigned for garbage collection automatically.  Without gc(), when restarting the app, it appears there is a build up of assigned to a memory location code or data, leading to an eventual crash.

**Comment by CatchABus** [comment]
> Good news, the app does not crash when reactivated after being left idle when run on NativeScript/core 8.5.0-alpha-5 .
> 
> More good news, when force closing and restarting the app, by running gc(); in suspendEvent, there is no longer any crashing taking place - so far.
> 
> Therefore, I think it is safe to assume that not all objects and variables are being assigned for garbage collection automatically. Without gc(), when restarting the app, it appears there is a build up of assigned to a memory location code or data, leading to an eventual crash.

Nice findings. This will help improving android runtime more in the future. 8.5 will come with more improvements and I think runtimes will keep getting better.

**Comment by SeanKelly369** [comment]
Unfortunately, it is still crashing occasionally in the same areas, but improving.

**Comment by SeanKelly369** [comment]
After installing nativescript/android 8.5.0-beta.2 , so far so good.  There has been no crashes yet to report.  It's running faster too.

**Comment by SeanKelly369** [comment]
One rare crash to report now, but things have improved

``Error: ClassNotFoundException when unmarshalling: androidx.core.widget.NestedScrollView$SavedState`` reported on Samsung Galaxy devices running on Android 12.

On Android 13, a couple of times it returned to the main page when opened after being left elsewhere in the app, but it didn't crash.

**Comment by CatchABus** [comment]
@SeanKelly369 Oh I see. Latest version of core 8.5 should get this fixed for you then. If you try it and errors stop, let us know so that we can close this.

**Comment by SeanKelly369** [comment]
I see where the code exists for this one at https://github.com/NativeScript/NativeScript/blob/main/packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/VerticalScrollView.java .  What can I do to pitch in and kill this bug?

**Comment by SeanKelly369** [comment]
So far, so good.  There has been no crashes to report.  If by Monday there are no crashes, I think this is good to close.

**Comment by SeanKelly369** [comment]
I can confirm that the app on Android is no longer crashing.  It was tested on a range of phones, from old phones run on Android 9 to phones running on Android 13.
