### ISSUE TITLE
Stop depending on globally installed Gradle

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/NativeScript#1024]
NativeScript can use Gradle wrapper and stop requiring the end users to download, install and setup exact versions of gradle on their machines.

 - [x] Android runtime: change the project template to include gradlew related files, created against the correct version of Gradle. Currently this is 2.8
 - [x] CLI: Change android build to use gradle wrapper from platforms/android
 - [x] Docs: Change system requirements, getting started, release notes and other relevant documentation.

**Comment by vchimev** [comment]
`spawn EACCES` error when trying to build - log: https://gist.github.com/vchimev/9ca40439a0c9c6a625c1
