### ISSUE TITLE
Box shadow does not respect the height in animations

### ISSUE THREAD

**Issue by vallemar** [NativeScript/NativeScript#10250]
### Issue Description

I have this problem, when I have a layout with box shadow and I animate the height with `.animate` the box-shadow does not respect the animated height, it has the final value of the height

https://user-images.githubusercontent.com/15719383/227615555-e24b74e6-1a73-4dff-a5ca-5ea3795e2d26.mov

I am using @farfromrefug  [fork](https://github.com/Akylas/NativeScript) and in his fork this does not happen, the box shadow grows with the height of the view. I only see this problem on @ns/core

This happens in the latest stable version 8.4.7 and I think also in alpha-6

Example: https://stackblitz.com/edit/nativescript-vue3-beta-2qnmtf?file=app%2Fapp.css,app%2Fcomponents%2FHome.vue

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by CatchABus** [comment]
Hello, thanks for the sample. Are you using Akylas fork? I think the major layout difference between that and original repo is this change: https://github.com/Akylas/NativeScript/commit/c50b4df83e59a23c1106d4138e7c20155aa1901a

Can you also try commenting out those changes and see how it goes?

**Comment by vallemar** [comment]
> 

Hi @CatchABus  I have not tried to remove this, but I am pretty sure that version 8.4.7 of @farfromrefug , which did not have these changes that you mention, worked without this error, I think this fix is ​​before this

**Comment by CatchABus** [comment]
> > 
> 
> Hi @CatchABus I have not tried to remove this, but I am pretty sure that version 8.4.7 of @farfromrefug , which did not have these changes that you mention, worked without this error, I think this fix is ​​before this

I see, thanks for clarification.
I think @farfromrefug was also doing some rework on animations and I wonder if this is related to getting this fixed.
