### ISSUE TITLE
Problem with RadSideDrawer and a nativescript project with nx

### ISSUE THREAD

**Issue by harikasin** [NativeScript/NativeScript#10266]
### Issue Description

I have a monorepo created with nx, first I created the web app and then a nativescript for android and ios devices. For the nativescript app when I try to add the sideDrawer component to have the navigation sidebar I get an error with the decorator "@ViewChild(RadSideDrawerComponent) public drawerComponent: RadSideDrawerComponent;".

If you change RadSideDrawerComponent to Label it can be seen that one of the problems resides in ViewChild.

I followed the nativescript guide to enter it correctly: https://v7.docs.nativescript.org/angular/ui/ng-components/ng-sidedrawer/getting-started.

I leave here a test project with the dependencies I have so you can check it out: https://github.com/harikasin/nx-angular-nativescript-sidedrawer

I have tried to follow https://github.com/ProgressNS/nativescript-ui-samples-angular/tree/master/sidedrawer/app example but I can't get it to work either.

### Reproduction

clone the repository and its submodule found at  https://github.com/harikasin/nx-angular-nativescript-sidedrawer

run "nx debug nativescript-movil:ios --verbose"

### Relevant log output (if applicable)

```shell
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn ns ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ns',
  path: 'ns',
  spawnargs: [ 'debug', 'ios', '--env.verbose', '--force' ]
}

Node.js v18.15.0
```

### Environment

```yaml
OS: macOS 13.3
CPU: (10) arm64 Apple M2 Pro
Shell: /bin/zsh
node: 18.15.0
npm: 9.5.0
nativescript: Not Found

# android
java: 11.0.17
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.2/14C18
cocoapods: 1.12.0
python: 2.7.18
python3: 3.9.0
ruby: 3.2.1
platforms: 
  - DriverKit 22.2
  - iOS 16.2
  - macOS 13.1
  - tvOS 16.1
  - watchOS 9.1
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "^15.0.0",
  "@angular/common": "^15.0.0",
  "@angular/compiler": "^15.0.0",
  "@angular/core": "^15.0.0",
  "@angular/forms": "^15.0.0",
  "@angular/platform-browser": "^15.0.0",
  "@angular/platform-browser-dynamic": "^15.0.0",
  "@angular/router": "^15.0.0",
  "@fortawesome/fontawesome-free": "^6.3.0",
  "@icon/open-iconic": "^1.1.1-alpha.3",
  "@nativescript/angular": "^15.0.0",
  "@nativescript/core": "~8.4.0",
  "@nativescript/firebase": "^11.1.2",
  "@nativescript/theme": "^3.0.2",
  "@nrwl/angular": "15.7.1",
  "bootstrap": "^5.2.3",
  "core-js": "^3.28.0",
  "nativescript-theme-core": "~1.0.4",
  "nativescript-ui-sidedrawer": "^15.2.0",
  "ngx-bootstrap": "^10.2.0",
  "rxjs": "~7.6.0",
  "tslib": "^2.3.0",
  "zone.js": "^0.12.0"
},
"devDependencies": {
  "@angular-devkit/build-angular": "^15.0.0",
  "@angular-devkit/core": "^15.1.6",
  "@angular-devkit/schematics": "^15.1.6",
  "@angular-eslint/eslint-plugin": "~15.0.0",
  "@angular-eslint/eslint-plugin-template": "~15.0.0",
  "@angular-eslint/template-parser": "~15.0.0",
  "@angular/cli": "~15.1.0",
  "@angular/compiler-cli": "^15.0.0",
  "@angular/language-service": "~15.1.0",
  "@angular/localize": "^15.1.5",
  "@nativescript/nx": "^4.2.0",
  "@nativescript/types": "~8.4.0",
  "@nativescript/webpack": "~5.0.0",
  "@ngtools/webpack": "^15.0.0",
  "@nrwl/cypress": "15.7.1",
  "@nrwl/eslint-plugin-nx": "15.7.1",
  "@nrwl/jest": "15.7.1",
  "@nrwl/linter": "15.7.1",
  "@nrwl/nx-cloud": "latest",
  "@nrwl/workspace": "15.7.1",
  "@schematics/angular": "^15.1.6",
  "@types/jest": "28.1.1",
  "@types/node": "^16.11.7",
  "@typescript-eslint/eslint-plugin": "^5.36.1",
  "@typescript-eslint/parser": "^5.36.1",
  "cypress": "^12.2.0",
  "eslint": "~8.15.0",
  "eslint-config-prettier": "8.1.0",
  "eslint-plugin-cypress": "^2.10.3",
  "jest": "28.1.1",
  "jest-environment-jsdom": "28.1.1",
  "jest-preset-angular": "~12.2.3",
  "nx": "15.7.1",
  "prettier": "^2.6.2",
  "sass": "^1.32.0",
  "ts-jest": "^28.0.5",
  "ts-node": "10.9.1",
  "typescript": "~4.8.2",
  "webpack": "^5.75.0"
}

**Comment by vallemar** [comment]
@harikasin try with this plugin https://github.com/nativescript-community/ui-drawer

**Comment by harikasin** [comment]
Yes, You can see the changes I made and reverted in the following commit following the plugin configuration you recommended @vallemar:

https://github.com/harikasin/nx-nativescript-movil/commit/3291dc1fb0ae33f1f02d28deb60b6ac738323192#diff-ad708251fe9410034b3e237034e20f2267068ca8e3a31d9d65a8bbff13deac44

**Comment by farfromrefug** [comment]
@harikasin still.not working? Feels like an issue with the build of the native part of the plugin

**Comment by NathanWalker** [comment]
Hi @harikasin is your latest all pushed up to the sample repo posted? If so, I'd be happy to look sometime this week.

**Comment by NathanWalker** [comment]
@harikasin I think it's just the run command you mentioned you were using:
> run "nx debug nativescript-movil:ios --verbose"

The proper run command would actually be this with v4 of @nativescript/nx - the `debug` shorthand will be supported in v5 but you can use this:
```
npx nx run nativescript-movil:ios  
```
Couple other small touchups I helped ya out with here:
https://github.com/harikasin/nx-angular-nativescript-sidedrawer/pull/1

There's several changes to the apps/nativescript-movil but seems the submodule doesn't take the commit changes?
Any particular reason that was pushed a submodule? I could include the changes if there was a way i could push on that.

**Comment by harikasin** [comment]
@NathanWalker I launched it with npx or nx and the error is still the same.

I uploaded it as a submodule because when I uploaded it from the parent project only the web part was uploaded and not the mobile part.

Entering your settings, updating dependencies and target, also still gives the same problem.

**Comment by harikasin** [comment]
oh it works! Thank you very much!! :) @NathanWalker
