### ISSUE TITLE
iOS 16.4 textChange behavior change

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/NativeScript#10267]
### Issue Description

iOS 16.4 textChange is called twice on input, and the first backspace in a TextField ignores the event as stated here:
https://github.com/NativeScript/NativeScript/issues/10249#issuecomment-1500974095

### Reproduction

Requires iOS 16.4 specifically - issue does not occur with 16.2.

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by NathanWalker** [comment]
@Salvetori appears iOS 16.4 is indeed ok too with latest 8.5 - if you find otherwise feel free to post further details...

https://user-images.githubusercontent.com/457187/231970871-18425554-4a9b-4403-b151-7b145fc35ead.mov

**Comment by dammynex** [comment]
https://user-images.githubusercontent.com/30000286/232069826-8c50cad3-b9e4-4b34-9a5f-b37e14f3d3eb.mov

The issue still persists and this is with v8.5

**Comment by serrg1994** [comment]
For me it only happens on emulator. Did you try to create Xcode project using SwiftUI for example and check if you have the same behavior?

**Comment by serrg1994** [comment]
> For me it only happens on emulator. @dammynex Did you try to create Xcode project using SwiftUI for example and check if you have the same behavior?

Ok. I created very simple SwiftUI application with text field and label. Cannot reproduce it

**Comment by NathanWalker** [comment]
@dammynex could you share a repo (either stackblitz or on GitHub) of exactly that setup you’re using in that video?

**Comment by dammynex** [comment]
Here's the link to the repo [](https://github.com/dammynex/testv3)

**Comment by NathanWalker** [comment]
Hi @dammynex thank you:
- Your lock file was still stuck on 8.4.0
- This PR adequately runs `ns clean` against and ensures package is using 8.5: https://github.com/dammynex/testv3/pull/1
- Runs good 👍 

https://user-images.githubusercontent.com/457187/232259568-2e882849-2f9f-4a3e-82c3-087072eb701d.mov

**Comment by mattNOTRS** [comment]
Hello, I am the same person as @Salvetori posting from a different account.
Here is a screen recording of a newly created NS Angular project running in an iOS 16.4 emulator
As you can see I am still getting the issue

https://user-images.githubusercontent.com/87208253/233187673-c100d07e-d60f-4a59-942b-c0a4828d5c6b.mov



Here is the repo: https://github.com/notrs/ios-ns-angular-test

I tried ns clean on my other private repo and that did not fix the issue, nor did I find evidence of a latent NS v8.4 record in the package-lock

Thank you for the help

**Comment by NathanWalker** [comment]
Hi @mattNOTRS cloned your repo and it's good there as well. Possible you have keyboard settings interfering?

https://user-images.githubusercontent.com/457187/233435459-7bf23313-8516-4ef3-b2e8-4e8f13bccb2a.mov

**Comment by dammynex** [comment]
Could it be an issue with the XCode simulator? It does not happen on device for me. But, even with v8.5 on the emulator, it still happens

**Comment by tylerablake** [comment]
@dammynex I'm also seeing the behavior only on simulator

**Comment by kryptus36** [comment]
I'm seeing this as well after switching from intel to M2. Could it be just an emulator issue on some platforms?

**Comment by NathanWalker** [comment]
I'm curious too - must be some other factor involved. I've tried multiple ways with different simulators and can confirm I don't experience it on 16.4 simulator even and I'm on M1 myself. Would be wild if it were M2 related only but anything could be possible. Would be curious if others experiencing same might share their dev machines details, for example I'm using:
`Apple M1 Max`

**Comment by dammynex** [comment]
I'm using intel

**Comment by tylerablake** [comment]
I’m using intel i9

**Comment by cjohn001** [comment]
Hello together,
I am also seeing this bug on my Mac M1, but just on iOS simulator. I assume this bug hre is the source of the problem I recently posted here:

https://github.com/NativeScript/angular/issues/110

**Comment by NathanWalker** [comment]
Is everyone experiencing the issue using Angular? Possible could be something there? I’ve verified on core only since this repo is often meant only for core alone.

**Comment by tylerablake** [comment]
@NathanWalker I'm using Angular

**Comment by cjohn001** [comment]
@NathanWalker , Angular +1 as you likely already have seen from my dependencies. Please consider, the bug report on the Angular gitrepo, which I wrote, mentions an issue with angular forms. I tried a textfield without using Angular forms and the issue also appears their. Hence, not an Angular Forms but an inheritted issue.
As mentioned, when setting a dummy function on the new valueFormatter I do not observe the bug anymore. Might be a hint to find the problem.

**Comment by subjekt-iv** [comment]
hey guys! I can't get through a strange text field behavior that may be related to this issue. The bug issue occurs on Android and ios simulators as well. When typing into a TextField (credentials in this case) both username and password text fields display correctly the characters but when I press the login button, which triggers the login request method, the last character of both the strings are truncated.

```
OS: macOS 13.0
CPU: (8) x64 Apple M2
Shell: /bin/bash
node: 14.18.0
npm: 6.14.15
nativescript: 8.5.3

# android
java: 11.0.15
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.3/14E222b
cocoapods: 1.12.0
python: 3.9.9
python3: 3.9.9
ruby: 2.7.8
platforms: 
  - DriverKit 22.4
  - iOS 16.4
  - macOS 13.3
  - tvOS 16.4
  - watchOS 9.4
 
"dependencies": {
  "@bradmartin/nativescript-urlhandler": "^2.0.1",
  "@nativescript/appversion": "^2.0.0",
  "@nativescript/background-http": "^6.0.0",
  "@nativescript/camera": "^5.0.15",
  "@nativescript/core": "~8.5.2",
  "@nativescript/datetimepicker": "^2.1.13",
  "@nativescript/email": "^2.0.5",
  "@nativescript/firebase-core": "^3.0.0",
  "@nativescript/firebase-messaging": "^3.0.0",
  "@nativescript/imagepicker": "^1.0.10",
  "@nativescript/iqkeyboardmanager": "^2.1.1",
  "@nativescript/theme": "^2.2.1",
  "@triniwiz/nativescript-socketio": "^4.0.3",
  "@triniwiz/nativescript-toasty": "^4.1.3",
  "@vue/devtools": "^5.3.3",
  "cocoapods": "^0.0.0",
  "moment": "^2.29.1",
  "n7-google-places-autocomplete": "^1.0.11",
  "nativescript-appversion": "^1.4.4",
  "nativescript-barcodescanner": "^4.1.2",
  "nativescript-clipboard": "^2.1.1",
  "nativescript-toasty": "^3.0.0-alpha.2",
  "nativescript-vue": "^2.9.3",
  "nativescript-vue-devtools": "^1.4.0",
  "nativescript-vue-shadow-ns-7": "^10.1.0",
  "vuex": "^3.3.0",
  "xcode": "^3.0.1"
},
"devDependencies": {
  "@babel/core": "^7.0.0",
  "@babel/preset-env": "^7.0.0",
  "@nativescript/android": "~8.5.0",
  "@nativescript/ios": "8.5.1",
  "@nativescript/types": "~8.5.0",
  "@nativescript/webpack": "~5.0.0",
  "@types/node": "^18.0.3",
  "babel-loader": "^8.1.0",
  "nativescript-vue-template-compiler": "^2.6.0",
  "prettier": "^2.8.7",
  "sass": "~1.49.9",
  "typescript": "~4.8.4",
  "vue-loader": "^15.9.1"
}
 ```

**Comment by Williams-Christopher** [comment]
I'm experiencing this exact issue on both the iOS simulator and physical device. Using a watcher to look at this it appears that initially the value of the underlying property is set correctly but there is an immediate update where the underlying property is mutated again:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/26190276/236698647-e762339d-7bdd-4a28-9094-367caf053e17.png">

Space and back space do not cause this double update behavior so if I enter a space then backspace, the value of the property is correct:
<img width="717" alt="image" src="https://user-images.githubusercontent.com/26190276/236699000-61d152bd-76af-44f1-a03a-958daa18fcd8.png">

This does not happen on the Android platform.

```yaml
OS: macOS 13.3.1
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Shell: /bin/zsh
node: 16.18.0
npm: 8.19.2
nativescript: 8.5.3

# android
java: 17.0.6
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.3/14E222b
cocoapods: 1.9.3
python: 3.7.3
python3: 3.9.6
ruby: 2.6.10
platforms: 
  - DriverKit 22.4
  - iOS 16.4
  - macOS 13.3
  - tvOS 16.4
  - watchOS 9.4
```

### Dependencies

```json
"dependencies": {
  "@angelengineering/filepicker": "^1.0.5",
  "@nativescript/background-http": "^6.0.0",
  "@nativescript/core": "~8.5.0",
  "@nativescript/imagepicker": "^2.0.0",
  "@nativescript/secure-storage": "^3.0.0",
  "@nstudio/nativescript-loading-indicator": "^4.1.2",
  "@vue/devtools": "^5.3.3",
  "nativescript-drop-down": "^6.0.0",
  "nativescript-iqkeyboardmanager": "^1.5.1",
  "nativescript-socketio": "^3.2.1",
  "nativescript-toasty": "^1.3.0",
  "nativescript-vue": "^2.0.0",
  "nativescript-vue-devtools": "^1.2.0",
  "vuex": "^3.1.2"
},
"devDependencies": {
  "@babel/core": "^7.8.3",
  "@babel/preset-env": "^7.8.3",
  "@nativescript/android": "8.5.0",
  "@nativescript/ios": "8.5.1",
  "@nativescript/types": "~8.5.0",
  "@nativescript/webpack": "~5.0.0",
  "@triniwiz/nativescript-socketio": "^5.0.1",
  "@triniwiz/nativescript-toasty": "^4.1.3",
  "@types/node": "^17.0.8",
  "babel-loader": "^8.0.2",
  "babel-traverse": "6.26.0",
  "babel-types": "6.26.0",
  "babylon": "6.18.0",
  "lazy": "1.0.11",
  "nativescript-vue-template-compiler": "^2.0.0",
  "sass": "~1.39.0",
  "typescript": "~4.3.5",
  "vue": "^2.6.11",
  "vue-loader": "^15.8.3"
}
```

**Comment by lekhmanrus** [comment]
Hi,
I'm experiencing the same issue on iOS simulator only (Nativescript Angular project). Real devices and Android Emulator - works fine.

**Comment by NathanWalker** [comment]
> 
> I am still seeing it with that version using iPhone 14 Pro simulator.
> 
> One side note: when I set the new [valueFormatter]="valueFormatter" to a function just returning the value than the bug does not appear anymore.
> 
> ```
> public valueFormatter = (value: string, useParens?: boolean) => {
> 		return value;
> 	};
> ```
> ```

Confirm that @cjohn001 workaround indeed works perfectly for this case. So far all we've been able to tell is that indeed is a iOS 16.4 simulator case and not universal - seems to happen to some (like my colleague Dave and I working on same project, doesn't happen to him, but was able to get it to occur to me only in the same sim on my machine). We'll report back here if we find anything else but for anyone experiencing similar in just that sim can do that harmless binding (perfectly fine).

**Comment by NathanWalker** [comment]
https://developer.apple.com/forums/thread/727715

**Comment by SeanKelly369** [comment]
It doesn't happen with TextView, which has similar code in the core/ui library.  Using TextView with some css to make it appear like a TextField can be used as workaround until a solution is found.  My inclination is, the bug may exist in a function in TextField that differs to TextView.

**Comment by JamesVal** [comment]
Just tacking on also ran into issue - and like the previous comment, TextView the input is fine but TextField we get the behavior where last character is removed

**Comment by NathanWalker** [comment]
We'll be investigating if the behavior is the same in iOS 17 and if so, we may place a conditional in the handling given the valueFormatter logic is simpler and may resolve it holistically for all - we just want to test this well to be certain.

**Comment by edusperoni** [comment]
I'll add to this:

The issue only seems to affect x86 builds, so if you're on x86 OR if your app is building for x86 simulator, then you'll experience the issue. Essentially affects all x86 macs. ARM (M1) macs can be affected if they use an .framework only built for x86, in which case Xcode might build the app for x86 simulator and run it through rosetta, which will make the issue happen.

Hopefully Apple fixes this on their end

**Comment by darklight365** [comment]
@NathanWalker - Using valueFormatter in this way will prevent users from updating text in the middle of a string (using delete key).  Another issue is that the current cursor position gets lost when delete is used in the middle of a string.  So I'm not sure the viability of including this within core.

**Comment by adamcikado** [comment]
This issue also happens when tapping on suggestion, e.g. you type `email` and then tap on suggestion `email@email.com` will result in `emailemail@email.com` value.

**Comment by ebalestrini** [comment]
Hi there I was wondering if there was any updates on this topic? It will be nice to get it to work on ios 16.4

**Comment by SeanKelly369** [comment]
@ebalestrini when using XCode 14.3 or higher, does the simulator drain your laptops's battery?

**Comment by ebalestrini** [comment]
@SeanKelly369 so far I have not noticed that.

**Comment by MrSnoozles** [comment]
@adamcikado We're seeing the `emailemail@domain.com` problem too. Not only on the simulator, but on live devices too.

I had opened an issue two years ago that got resolved, but since NS 8.5 it's back. Not sure if it's related to iOS 16.4, but since here people mostly talk about the emulator I think it might be two separate issues.
https://github.com/NativeScript/NativeScript/issues/9486

**Comment by timoschlueter** [comment]
I ran into this issue today on iOS 16.4. Is there any update on a fix yet?

**Comment by SeanKelly369** [comment]
Is the emulator hard on laptop battery?

**Comment by SeanKelly369** [comment]
https://developer.apple.com/forums/thread/727715  Read the last comment in the thread.

**Comment by artan-fetahaj** [comment]
@MrSnoozles Unfortunately we are facing the `emailemail@domain.com` issue as well. have you found a fix to this problem in the meantime?

**Comment by MrSnoozles** [comment]
Like I stated before, there are two separate issues, afaik both are still standing.

1) [this issue] the binding on textChange is wrong, this happens only simulator with iOS 16.4+ (happens on iOS 17.0 as well)

2) https://github.com/NativeScript/NativeScript/issues/9486 When clicking on the auto complete suggestion, the binding is wrong, leading to something like `emailemail@domain.com`. This appears to happen when `autocorrect="false"` is set.

**Comment by mrwrighty** [comment]
Just my take  on this.  Was previously running Monterey and Nativesccript 8.6.1. Built lots and lots of apps over the past few years. Just updated to Sonoma and Nativescript 8.6.5 in order to meet the new Xcode15 17.2 SDK requirements, thought this update would fix the issue with apps built in 8.6.1, but no, problem still exists. ns debug ios is Simulator problem is displayed. Open XCWorkspace and run in Xcode on Simulator (Arm64) and problem goes away. Makes designing, building and testing direct in Nativescript a nightmare. Code should compile OK in XCode and archive for TestFlight, but local testing with this issue is troublesome.

**Comment by SeanKelly369** [comment]
In XCode 15.3, running iOS 17.4 simulator for iPhone 15 this issue is no longer occurring.

**Comment by NathanWalker** [comment]
Confirmed here as well thanks @SeanKelly369 👌

**Comment by brianrclow** [comment]
We also just started getting reports of this issue iOS predictive text issue where the textfield starts with "email" then the user taps the predictive text of their email on the keyboard and the textfield updates visually but the actual form somehow sends ```emailemail@domain.com``` to the server. Xcode 15.2, iOS 17.2 simulator. Updating from Xcode 15.2 -> 15.3 to see if this resolves it.
