### ISSUE TITLE
Cache Module doesn't cache the image

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#10292]
### Issue Description

Hi @NathanWalker,

I was trying to use the Cache module (on simulator) the image is downloaded each time but not cached! it happen on both platforms.

I give a quick look into the code and seems to be correct!

I use latest version of NS 8.5.

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
Please include code or a reproducible sample for further investigations.

**Comment by kefahB** [comment]
Hi @rigor789 

I have this function :  the first time `cache.get(url)` should return null but the second time it should return the image cached. 

```ts

export function getImg(img: string): Promise<ImageSource> {
    return new Promise((resolve, reject) => {
        const cache = new Cache();
        let cachedImageSource: ImageSource;
        const url = "PATH_TO_REMOTE_IMAGE";

        const myImage = cache.get(url);
        console.log("GET IMG", url, myImage); 
 
        if (myImage) {
            console.log("img exist");
            cachedImageSource = new ImageSource(myImage);
            resolve(cachedImageSource)
        } else {
            console.log("img doesn't exist, request its download + put it in the cache");
            cache.push({
                key: url,
                url: url,
                completed: (image, key) => {
                    console.error("cache.push", image, key);
                    
                    if (url === key) {
                        cachedImageSource = new ImageSource(image);
                        cache.set(url, image)
                        resolve(cachedImageSource)
                    }
                }, 
                error: (key: string) => {
                    console.error("Error when cached img >> ", key);
                    reject(key)
                }
            })
            return cachedImageSource;
        }

        cache.disableDownload();
    });
}


```

**Comment by kefahB** [comment]
It doesn't change .. `cache.get()` still return null!

**Comment by kefahB** [comment]
this class should be a singleton!

**Comment by rigor789** [comment]
It doesn't need to be a singleton in core, you could technically maintain separate cache instances in your app.

Here's a working example:
```ts
import { ImageCache, ImageSource } from "@nativescript/core"

const cache = new ImageCache();
export function getImg(url: string): Promise<ImageSource> {
  return new Promise((resolve, reject) => {
    const cachedImage = cache.get(url);

    if (cachedImage) {
      console.log('Image found in cache, returning cached image');
      resolve(new ImageSource(cachedImage));
      return;
    }
    
    console.log('Image not in cache, fetching...');
    cache.push({
      key: url,
      url: url,
      completed(image, key) {
        console.log('cache.set', key, image);
        cache.set(key, image);
        resolve(new ImageSource(image));
      },
      error(key: string) {
        console.error('Failed to cache image', key);
        reject();
      },
    });
  });
}
```

**Comment by kefahB** [comment]
It dose work for you ?!! because for me no think changed!!

**Comment by kefahB** [comment]
@rigor789 

Oh I see the problem, the is a misunderstand between us :)

Once the app is launched the plugin effectively cache the image for a future use, but when we close the app it redownload the image and cache it again, that is my question!


The scenario should be:

- first app launch: No img in the cache -> it will download it then cache it
- now we close the app.
- second app launch: should find the image from the cache 

Now for every launch of the app it download the image, there is a way to cache the image for long time even if we close the app ?!

**Comment by NathanWalker** [comment]
Yes highly recommend this for that:
https://triniwiz.github.io/nativescript-plugins/api-reference/image-cache-it.html

**Comment by kefahB** [comment]
@NathanWalker @rigor789 Thank you all :)
