### ISSUE TITLE
ScrollView not working in a modal page in Android

### ISSUE THREAD

**Issue by N3ll** [NativeScript/NativeScript#1029]
When a ScrollView is placed inside a page, which is called through showModal(), the ScrollView is working only in iOS and not in Android.

**Comment by maknz** [comment]
We think we've stumbled upon this too, with a WebView in a modal not being scrollable (and thus won't move up automatically when you tap into fields like it would do normally. Not sure if it's a WebView problem or a modal problem.

**Comment by saulosda** [comment]
I solve with a workaroud like this:

if (platformModule.device.os === "Android") {
        var height = Math.floor(platformModule.screen.mainScreen.heightPixels /
            platformModule.screen.mainScreen.scale);
        page.content.height = height;
    }

Where 'page.content' is my ScrollView control.

**Comment by hshristov** [comment]
I'm unable to reproduce this with 1.5.
