### ISSUE TITLE
Stop NativeScript build if Webpack fails

### ISSUE THREAD

**Issue by insytes** [NativeScript/NativeScript#10314]
### Is your feature request related to a problem? Please describe.

I wish @nativescript/webpack would not discard errors from the configuration stage and instead halt the NativeScript build process.

I recently wrote a Webpack plugin to validate some env-vars that are required at runtime.

My attempts to raise an exception are visualised in the CLI however NativeScript proceeds with the build regardless.

### Describe the solution you'd like

It would be nice if NativeScript could propagate the raised exception for a better control flow when handling errors.

### Describe alternatives you've considered

Instead I find myself considering this _hacky_ workaround. The try/catch block is for illustrative purposes only.

```javascript
try {
  doSomethingThatMayThrow()
} catch (e) {
  process.exitCode = 1 // this feels wrong
  throw e // pointless anyway
}
```
### Anything else?

I believe this is the offending code. https://github.com/NativeScript/NativeScript/blob/6f87dbcd6cbd01d4c9a2e6252b128b9bfe0ab770/packages/webpack5/src/bin/index.ts#L78-L87
### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by NathanWalker** [comment]
Thanks for tracking this @insytes long time desire here; we’ll tackle this one likely for 9.0 but possibly sooner.
