### ISSUE TITLE
IOS only: Broken CSS classes when .ns-root is used. Core 8.5.4, 8.5.5, 8.5.6 (8.5.3 is working correctly)

### ISSUE THREAD

**Issue by cjohn001** [NativeScript/NativeScript#10318]
### Issue Description

Hello together,
I just played with the new core versions 8.5.4, 8.5.5 and 8.5.6. Seems that throughout my app on different elements the css classes are not correctly applied. 

The problem seems to be related to .ns-root not being correctly applied on initial app start. I for example have the following css class on a button.

```
.ns-root .icon-font-button {
	background-color: transparent;
	color: $info;
	border-width: 0;
	font-size: 24;
	box-shadow: none;
	border-color: transparent;
}
.ns-root .icon-font-button:active {
	background-color: transparent;
	color: $info;
	border-width: 0;
	font-size: 24;
	box-shadow: none;
	border-color: transparent;
}

.ns-root.ns-dark {
	.icon-font-button {
		background-color: green;
	}
	.icon-font-button:active {
		background-color: green;
	}
}
```

Interestingly, the button does not get the icon-font-button class applied when the app is started. However, when I switch to dark mode, the css class is applied as expected. When I than switch back to light mode, icon-font-button is applied as expected.

When I completely remove .ns-root on the css classes things are working on first app start as expected.

**Is this a breaking change in CSS I am observing? Should I now remove .ns-root from all classes, i.e. not used anymore?** Till 8.5.3 I required it in order to see dark/light mode changes to take effect as expected. Would be good to document the breaking change in the changelog than.

See example: https://github.com/NativeScript/NativeScript/issues/10318#issuecomment-1604440590

### Environment

```yaml
OS: macOS 13.4
CPU: (10) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 18.12.1
npm: 9.7.1
nativescript: 8.5.3

# android
java: 11.0.18
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.3.1/14E300c
cocoapods: 1.12.0
python: 3.11.2
python3: 3.11.2
ruby: 2.7.7
platforms: 
  - DriverKit 22.4
  - iOS 16.4
  - macOS 13.3
  - tvOS 16.4
  - watchOS 9.4
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "16.0.4",
  "@angular/common": "16.0.4",
  "@angular/compiler": "16.0.4",
  "@angular/core": "16.0.4",
  "@angular/forms": "16.0.4",
  "@angular/platform-browser": "16.0.4",
  "@angular/platform-browser-dynamic": "16.0.4",
  "@angular/router": "16.0.4",
  "@apollo/client": "3.7.15",
  "@mnd/external-web-view": "file:../mnd-plugins/dist/packages/external-web-view/mnd-external-web-view-1.0.1.tgz",
  "@nativescript/angular": "16.0.0",
  "@nativescript/core": "8.5.5",
  "@nativescript/iqkeyboardmanager": "2.1.1",
  "@nativescript/localize": "5.1.0",
  "@nativescript/mlkit-barcode-scanning": "2.0.0",
  "@nativescript/mlkit-core": "2.0.0",
  "@nativescript/secure-storage": "3.0.1",
  "@nativescript/theme": "3.0.2",
  "@nativescript/ui-charts": "0.2.4",
  "apollo-angular": "5.0.0",
  "apollo3-cache-persist": "0.14.1",
  "d3-ease": "3.0.1",
  "graphql": "16.6.0",
  "graphql-tag": "2.12.6",
  "intl": "1.2.5",
  "moment": "2.29.4",
  "nativescript-health-data": "file:../mnd-custom-plugins/nativescript-health-data/publish/package/nativescript-health-data-2.0.0.tgz",
  "nativescript-oauth2-ext": "file:../mnd-custom-plugins/nativescript-oauth2-ext/publish/package/nativescript-oauth2-ext-3.0.2.tgz",
  "nativescript-sqlite": "2.8.6",
  "nativescript-ui-calendar": "15.2.3",
  "nativescript-ui-gauge": "15.2.3",
  "rxjs": "7.8.1",
  "uuid": "9.0.0",
  "zone.js": "0.13.1"
},
"devDependencies": {
  "@angular-devkit/build-angular": "16.0.4",
  "@angular/compiler-cli": "16.0.4",
  "@graphql-codegen/cli": "4.0.1",
  "@graphql-codegen/fragment-matcher": "5.0.0",
  "@graphql-codegen/introspection": "4.0.0",
  "@graphql-codegen/typescript": "4.0.0",
  "@graphql-codegen/typescript-apollo-angular": "3.5.6",
  "@graphql-codegen/typescript-operations": "4.0.0",
  "@nativescript/android": "8.5.0",
  "@nativescript/ios": "8.5.2",
  "@nativescript/types": "8.5.0",
  "@nativescript/webpack": "5.0.15",
  "@ngtools/webpack": "16.0.4",
  "@types/d3-ease": "3.0.0",
  "@types/intl": "1.2.0",
  "@types/node": "20.3.1",
  "@types/uuid": "9.0.2",
  "keycloak-request-token": "0.1.0",
  "rimraf": "5.0.1",
  "sass": "1.63.4",
  "ts-node": "10.9.1",
  "typescript": "4.9.5"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
Would you be able to create a minimal reproduction of the issue in a new app, or on StackBlitz?

`.ns-root` is definitely not deprecated, and it should be getting applied correctly, ie. if the Traces are enabled, the correct classes are printed and applied:
https://stackblitz.com/edit/nativescript-stackblitz-templates-p8udgv?file=app%2Fapp.ts

```
Style: Setting root css classes: ns-root ns-android ns-phone ns-portrait ns-dark
Style: Applying root css class: a11y-fontscale-100. rootView css classes: ns-root ns-android ns-phone ns-portrait ns-dark a11y-fontscale-100
Style: Applying root css class: a11y-fontscale-m. rootView css classes: ns-root ns-android ns-phone ns-portrait ns-dark a11y-fontscale-100 a11y-fontscale-m
Style: Applying root css class: a11y-service-disabled. rootView css classes: ns-root ns-android ns-phone ns-portrait ns-dark a11y-fontscale-100 a11y-fontscale-m a11y-service-disabled
```

**Comment by cjohn001** [comment]
@rigor789: Was difficult to track the issue down, but I got a working example. It seems to be related to using a launchView.

In the attached example (zip file) in main.ts you can comment in/out the launch view in order to see the problem.

<img width="645" alt="Bildschirmfoto 2023-06-23 um 17 13 38" src="https://github.com/NativeScript/NativeScript/assets/43253483/cf0e8f01-b49c-4177-a5b6-8d4136d7ef56">

[nsroot.zip](https://github.com/NativeScript/NativeScript/files/11849825/nsroot.zip)

The working example without launch view should look like this, see bottom toolbar.


![Simulator Screenshot - iPhone 14 Pro - 2023-06-23 at 17 16 50](https://github.com/NativeScript/NativeScript/assets/43253483/d60262bd-ee05-4f19-a972-954820cb0951)


And when launch animation is enabled the bug appears and looks as follows:
![Simulator Screenshot - iPhone 14 Pro - 2023-06-23 at 17 14 20](https://github.com/NativeScript/NativeScript/assets/43253483/09d9f123-ab74-4014-afff-9f08ea2cf8cc)

**Comment by cjohn001** [comment]
@rigor789  and @NathanWalker: Thanks for the quick fix gentlemen!

**Comment by rigor789** [comment]
Excellent repro, helped spot the issue pretty quickly @cjohn001 👍
