### ISSUE TITLE
`Utils.dismissKeyboard()` does not work in android modals

### ISSUE THREAD

**Issue by vallemar** [NativeScript/NativeScript#10373]
### Issue Description

When you try to use `Utils.dismissKeyboard()` with focus on a modal view the keyboard does not close

### Reproduction

https://stackblitz.com/edit/nativescript-vue-nativescript-vue-fa2ksg?file=src%2Fcomponents%2FHome.vue,src%2Fcomponents%2FDetails.vue&title=NativeScript%20Starter%20Vue3%20Beta

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by farfromrefug** [comment]
Might have stumbled upon the same issue just yesterday. Are you trying to dismiss the keyboard while closing the modal ?

**Comment by vallemar** [comment]
@farfromrefug It happens when the modal is open and you try to close the keyboard while keeping the modal open. I have been debugging the code but I don't see anything strange, the code runs fine but the keyboard does not close

**Comment by CatchABus** [comment]
I think support for closing modal soft input is missing.
More specifically, core is missing handling here https://github.com/NativeScript/NativeScript/blob/a959a797df46d47ddf3bfa4514948a97f67758ef/packages/core/utils/android/index.ts#L60

One way to fix this is by retrieving modal window using `_dialogFragment` just like we do for certain properties in `Page` component: https://github.com/NativeScript/NativeScript/blob/main/packages/core/ui/page/index.android.ts#L69

**Comment by farfromrefug** [comment]
@vallemar what you can try to figure out the real issue is calling dismissSoftInput with the nativeView argument from your textfield. if it does work it is indeed because we dont get the right  windowToken for the current opened dialog.
