### ISSUE TITLE
Support for Bun package manager

### ISSUE THREAD

**Issue by mathletedev** [NativeScript/NativeScript#10397]
### Is your feature request related to a problem? Please describe.

The [Bun](https://github.com/oven-sh/bun) package manager is currently unsupported in the NativeScript CLI.

When running `ns package-manager set bun`, the following error is returned:
```
bun is not a valid package manager. Supported values are: npm, pnpm, yarn, yarn2.
```

### Describe the solution you'd like

It would be great if Bun could be included as a valid package manager. Perhaps a similar approach to the [NPM implementation](https://github.com/NativeScript/nativescript-cli/blob/main/lib/node-package-manager.ts) could be taken.

### Describe alternatives you've considered

1. Use `bun install` to manually install packages alongside NPM installations. However, this may run into problems with conflicting packages.
2. Don't use Bun. This isn't a problem, but there might be cases where Bun is a better option for a package manager than NPM or Yarn.

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by jasongitmail** [comment]
I created a PR to add Bun support at https://github.com/NativeScript/nativescript-cli/pull/5791
