### ISSUE TITLE
https://github.com/telerik/cli-table/tarball/v0.3.1.2 - nativescript 6.5 corrupted

### ISSUE THREAD

**Issue by leocrawf** [NativeScript/NativeScript#10394]
### Issue Description

When you run an install of nativescript 6.5 you get and error saying https://github.com/telerik/cli-table/tarball/v0.3.1.2 tarball is corrupted

### Reproduction

npm i -g nativescript@6.5

### Relevant log output (if applicable)

```shell
windows and linux
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
Use a more recent CLI version, should generally be backwards compatible with older projects.

Try `latest` or perhaps `6.8.1` where this was patched (~8 months ago).
