### ISSUE TITLE
Allow ListView init by directly specifying its items without template and collection

### ISSUE THREAD

**Issue by bundyo** [NativeScript/NativeScript#104]
Currently NativeScript ListView can be only initialized by specifying an itemTemplate and an items collection. However, sometimes the developer needs a ListView with several completely different items that wouldn't fit in an itemTemplate. The most often used scenarios of this are input forms or settings screens, which the native applications usually integrate in a ListView.

**Comment by enchev** [comment]
Duplicate to https://github.com/NativeScript/NativeScript/issues/262
