### ISSUE TITLE
Error when box-shadow is set no none

### ISSUE THREAD

**Issue by asharghi** [NativeScript/NativeScript#10403]
### Issue Description

After updating to core 8.6, I get this error. Seems to work with box-shadow: none anyway, but the error should be removed

```
CONSOLE ERROR: Error: Failed to apply property [box-shadow] with value [none] to Button(11). TypeError: Cannot read properties of null (reading 'values')
  JS:     at parseCSSShadow (file: app/webpack:/css-test/node_modules/@nativescript/core/ui/styling/css-shadow.js:58:0)
  JS:     at valueConverter (file: app/webpack:/css-test/node_modules/@nativescript/core/ui/styling/style-properties.js:1146:29)
  JS:     at Style.setCssValue [as css:box-shadow] (file: app/webpack:/css-test/node_modules/@nativescript/core/ui/core/properties/index.js:573:0)
  JS:     at CssState.setPropertyValues (file: app/webpack:/css-test/node_modules/@nativescript/core/ui/styling/style-scope.js:555:47)
  JS:     at file: app/webpack:/css-test/node_modules/@nativescript/core/ui/styling/style-scope.js:431:0
  JS:     at Button._batchUpdate (file: app/webpack:/css-test/node_modules/@nativescript/core/ui/core/view-base/index.js:361:0)
  JS:     at CssState.updateDynamicState (file: app/webpack:/css-test/node_modules/@nativescript/core/ui/styling/style-scope.js:429:0)
  JS:     at CssState.onLoaded (file: app/webpack:/css-test/node_modules/@nativescript/core/ui/styling/style-scope.js:399:0)
  JS:     at Button.onLoaded (file:///data/data/org.nativescript.csst...
```

### Reproduction

Add an element with box-shadow: none in css or inline style

### Environment

```
"dependencies": {
    "@nativescript/core": "~8.6.0",
    "@nativescript/theme": "~3.0.2",
    "nativescript-vue": "~2.9.3"
  },
  "devDependencies": {
    "@nativescript/android": "8.5.4",
    "@nativescript/webpack": "~5.0.18",
    "nativescript-vue-template-compiler": "~2.9.3"
  }
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by CatchABus** [comment]
> ### Issue Description
> After updating to core 8.6, I get this error. Seems to work with box-shadow: none anyway, but the error should be removed
> 
> ```
> CONSOLE ERROR: Error: Failed to apply property [box-shadow] with value [none] to Button(11). TypeError: Cannot read properties of null (reading 'values')
>   JS:     at parseCSSShadow (file: app/webpack:/css-test/node_modules/@nativescript/core/ui/styling/css-shadow.js:58:0)
>   JS:     at valueConverter (file: app/webpack:/css-test/node_modules/@nativescript/core/ui/styling/style-properties.js:1146:29)
>   JS:     at Style.setCssValue [as css:box-shadow] (file: app/webpack:/css-test/node_modules/@nativescript/core/ui/core/properties/index.js:573:0)
>   JS:     at CssState.setPropertyValues (file: app/webpack:/css-test/node_modules/@nativescript/core/ui/styling/style-scope.js:555:47)
>   JS:     at file: app/webpack:/css-test/node_modules/@nativescript/core/ui/styling/style-scope.js:431:0
>   JS:     at Button._batchUpdate (file: app/webpack:/css-test/node_modules/@nativescript/core/ui/core/view-base/index.js:361:0)
>   JS:     at CssState.updateDynamicState (file: app/webpack:/css-test/node_modules/@nativescript/core/ui/styling/style-scope.js:429:0)
>   JS:     at CssState.onLoaded (file: app/webpack:/css-test/node_modules/@nativescript/core/ui/styling/style-scope.js:399:0)
>   JS:     at Button.onLoaded (file:///data/data/org.nativescript.csst...
> ```
> 
> ### Reproduction
> Add an element with box-shadow: none in css or inline style
> 
> ### Relevant log output (if applicable)
> _No response_
> 
> ### Environment
> ```
> "dependencies": {
>     "@nativescript/core": "~8.6.0",
>     "@nativescript/theme": "~3.0.2",
>     "nativescript-vue": "~2.9.3"
>   },
>   "devDependencies": {
>     "@nativescript/android": "8.5.4",
>     "@nativescript/webpack": "~5.0.18",
>     "nativescript-vue-template-compiler": "~2.9.3"
>   }
> ```
> 
> ### Please accept these terms
> * [x]  I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
> * [x]  This is a bug report
> * [x]  I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

Did this value apply without problems in prior versions?

**Comment by NathanWalker** [comment]
Thanks @CatchABus yep see what it is, we'll include in a patch.

**Comment by Reached** [comment]
Has this fix been published? :)

**Comment by NathanWalker** [comment]
That sounds odd - your lock file reflects 8.6+?

**Comment by Reached** [comment]
Yes indeed.

From the lock file:
```
"dependencies": {
        "@nativescript-community/ui-material-bottom-navigation": "^7.2.7",
        "@nativescript/core": "^8.6.1",
```

I do a clean install with `ns clean` and then `ns run android --no-hmr`, but the result is the same :/

I worked around it by only using `box-shadow: none` for iOS.

**Comment by CatchABus** [comment]
I confirmed this. It seems latest fix does not help with box shadow as there are few cases in core that still rely on shadow being `null` to determine whether it should be drawn.
We should definitely revisit the problem.

**Comment by NathanWalker** [comment]
Lets reopen this and get a proper patch published, thanks for bringing this up.

**Comment by NathanWalker** [comment]
@asharghi @CatchABus I tried to repro this and see no errors?
```xml
<Button style="box-shadow: none" />

<Button boxShadow="none" />

<Button css="none" />

.none {
  box-shadow: none;
}
```

**Comment by CatchABus** [comment]
> @asharghi @CatchABus I tried to repro this and see no errors? All render properly and with no shadow.
> 
> ```
> <Button style="box-shadow: none" />
> 
> <Button boxShadow="none" />
> 
> <Button class="none" />
> 
> .none {
>   box-shadow: none;
> }
> ```

Shadow should actually throw on android specifically. On iOS, it will not throw any errors but will attempt to create CALayers for shadow while not needed instead.

I found few locations affected by `parseCSSShadow` changes:
https://github.com/NativeScript/NativeScript/blob/main/packages/core/ui/styling/style-properties.ts#L1243
https://github.com/NativeScript/NativeScript/blob/main/packages/core/ui/styling/background-common.ts#L314
https://github.com/NativeScript/NativeScript/blob/main/packages/core/ui/text-base/index.ios.ts#L418

These cases rely on box shadow or text shadow being null after parsing.

**Comment by NathanWalker** [comment]
Ok thanks that makes sense now. We'll fix android to be ignored as well in this case.
