### ISSUE TITLE
Tap event not fired after translate outside of the parent 

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#10430]
### Issue Description

hello guys, I have an issue with the tap event when an image is wrapped into a GridLayout and then the image is translated out of the grid layout:
- the expected behaviour is to be clickable even after translated outside of the grid
- the current behaviour is the tap event fired once the image is within the bounds of the grid!

### Reproduction

1. Keep the image inside of the Gridlayout 
2. Click on the red box to translate the box
3. Re-click on the translated box : the tap event will not be fired

A sample project here : https://stackblitz.com/edit/nativescript-stackblitz-templates-biqh4x?file=app%2Fmain-page.xml,app%2Fmain-page.ts,app%2Fcard%2Fcard-page.xml,app%2Fcard%2Fcard-page.ts

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by farfromrefug** [comment]
Are you saying ou expect a tap/gesture to happen when the view is outside its parent "frame" ? If so I think it is the expected behavior and I dont think we should change that. 
Plus your image view should not even be visible outside its parent frame (unless you disable clipping which won't change the gesture behavior)

**Comment by kefahB** [comment]
@farfromrefug look at this scenario (attached image) the player can select a card (pre-move) to be played automatically when is its turn. 
The selected card it is translated -80 dpi
The card can be deselected and translated back

now when translated -80 (outside of the gridLayout) the top part (from the blue line) isn’t clickable anymore to deselect the card.

can you explain please why we shouldn’t change this behavior ?  

![Uploading IMG_1778.jpeg…]()

**Comment by farfromrefug** [comment]
@kefahB because if I am correct It is platform specs(you should loom it up)) and it should be handled on your side. Simply make the red grid layout full height.

**Comment by kefahB** [comment]
You are right, I did read a bit about the problem an seems to be the case on both platforms.

Thanks dear :)
