### ISSUE TITLE
Scrollview does not fire scroll events when background color is set

### ISSUE THREAD

**Issue by JWiseCoder** [NativeScript/NativeScript#10431]
Referenced in #10368, scroll events in scroll views do not fire when that scroll view has a background set.  I was able to reproduce this using the following test code:

```
<ScrollView
    orientation="horizontal"
    style="background-color: black;"
    (scroll)="onScroll($event)"
>
    <StackLayout
        orientation="horizontal"
        [height]="200">
        <StackLayout width="100" backgroundColor="red"></StackLayout>
        <StackLayout width="100" backgroundColor="blue"></StackLayout>
        <StackLayout width="100" backgroundColor="green"></StackLayout>
        <StackLayout width="100" backgroundColor="yellow"></StackLayout>
    </StackLayout>
</ScrollView>
```

With the background color style in place, the scroll event does not fire.  If I remove it, the scroll event fires normally.

referenced in https://github.com/NativeScript/NativeScript/issues/10368#issuecomment-1795517802_

**Comment by CatchABus** [comment]
@JWiseCoder Can you try changes in #10432? I'm pretty sure they fix your problem.

**Comment by JWiseCoder** [comment]
@CatchABus Yes, that change fixes that issue.
