### ISSUE TITLE
TextField with [secure] string don't work on Android with core plugin 8.6.2

### ISSUE THREAD

**Issue by Dzenan-Fatkic** [NativeScript/NativeScript#10486]
### Issue Description

I have a TextField for a login and registration service in my Application. 
We are using the [secure] function from the TextField for the password input. 
In the version of @nativescript/core 8.6.2 occurs a bug for Android (API Range 26-34). When you change the [secure] vaule by runtime on android the input will not be visibile. 

The version 8.6.1 don't have this bug. 

### Reproduction

The source code of our company application is not public. But you can check this with a simple TextField using [secure]="BooleanVariable"  

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by CatchABus** [comment]
8.6.2 truly contains changes related to TextField but we'll need more information, like the previous and new boolean value or whether problem occurs both ways.
A stackblitz sample would also be helpful.

**Comment by ignacio68** [comment]
In version 8.6.5 the problem persists on Android. If you change 'secure' from true to false the text is not displayed. If the initial state is true and you change it to false, it works but changes the font type and the cursor moves to the beginning of the text.

**Comment by Bezlepkin** [comment]
The bug is reproduced exactly if you set: `keyboardType="number"`

**Comment by Bezlepkin** [comment]
If I comment out this line:
https://github.com/NativeScript/NativeScript/blob/main/packages/core/ui/text-field/index.android.ts#L115C45-L115C73If I everything works :)

**Comment by CatchABus** [comment]
> If I comment out this line: https://github.com/NativeScript/NativeScript/blob/main/packages/core/ui/text-field/index.android.ts#L115 everything works :)

This one is needed to fix another problem just as described in the comment. I'll try to reproduce it with your sample.
Worse case scenario, we'll revert the changes that affected this.

**Comment by CatchABus** [comment]
@Bezlepkin Can you try without a keyboard type?

**Comment by Bezlepkin** [comment]
> @Bezlepkin Can you try without a keyboard type?

Without specifying keyboardType, it works correctly
