### ISSUE TITLE
Event for start/end of an event

### ISSUE THREAD

**Issue by EnguGH** [NativeScript/NativeScript#1048]
Hi,

is it on the roadmap to implement the broadcast of events at the beginning / end of any gesture ?
Let's say I want to catch a pan : I'd like to know where exactly the initial tap happened. And I'd even more like to know when it ends so I can put all my elements back in place.

Thanks !

**Comment by N3ll** [comment]
If there is enough demand we will consider implementing a cross-platform abstraction of low level events like touchDown, touchUp, etc.
Until then you can use the native APIs and those low level events.

**Comment by EnguGH** [comment]
OK thanks !
I hadn't seen the native APIs things in the docs.

**Comment by x4080** [comment]
I think its important for the touch gesture detection in multi platform mode
