### ISSUE TITLE
Error reporting inside application

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#105]
There is a room for improvement in our error reporting workflow. Lets see how we can improve it. Here are several ideas that are floating around:
- Create a module that can overlay the app UI and show at runtime the console messages and various app metrics like:
   - memory usage
   - CPU usage
   - fps
   - network usage
- Create a special "error view" which is displayed when an unhandled exception occurs:
   - show all the details we know about the error
   - option to navigate to the actual source code where the error occured

**Comment by enchev** [comment]
This actually should be our App Inspector.
