### ISSUE TITLE
NS PREVIEW don't working properly

### ISSUE THREAD

**Issue by AAlex-11** [NativeScript/NativeScript#10503]
### Issue Description

emulator is working fine

![drawer-03312024_005420](https://github.com/NativeScript/NativeScript/assets/138773344/223cd5a4-393a-4ee3-a44b-0073e8cf25cb)

but NS Preview is not working
https://preview.nativescript.org/session/325b0c3571a30c5e2075c7acfd4e8dbf08735ad9d168d7669e0196ed3545ca6c

I use this project https://github.com/nativescript-community/ui-drawer

### Relevant log output (if applicable)

I see on phone white screen only, first screen working, but Drawer is nothing

![drawer-03312024_011649](https://github.com/NativeScript/NativeScript/assets/138773344/e41a9e6a-7d78-40ef-9750-11ef016b1858)

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by AAlex-11** [comment]
Thank you, Interesting... This means something going wrong in my side, most NativeScript project working fine in my phone with NS Preview, but this project - don't working. We will close this issue, but if other developers will send complains for NS Preview again and agian, maybe you would more carefully investigate this issue.

**Comment by rigor789** [comment]
@AAlex-11 can you tell me a few details:
- version of NativeScript Preview app
- android version of the device you are running on (and device type perhaps)
- version of the preview - cli (printed in the header when you run `ns preview`, ie. `{N} NativeScript Preview 2.0 [v1.0.13]`)

Also try `ns clean` and `ns preview` again, see if that makes a difference.

**Comment by AAlex-11** [comment]
Nativescript Preview 2.0.6 on phone
Device connected:    M2006C3LG [android: 2.0.6 (28)]
Phone type - Xaomi Redmi 9A
{N} NativeScript Preview 2.0 [v1.0.13]

However, My Application (if I copy APK to phone manually) working fine



![Office-04152024_221023](https://github.com/NativeScript/NativeScript/assets/138773344/d7eca6f2-dcf8-45a7-9b9c-473f00e7899a)

**Comment by AAlex-11** [comment]
package.json
{
  "name": "myvaultstart",
  "main": "./src/main.ts",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@angular/animations": "~16.2.0",
    "@angular/common": "~16.2.0",
    "@angular/compiler": "~16.2.0",
    "@angular/core": "~16.2.0",
    "@angular/forms": "~16.2.0",
    "@angular/platform-browser": "~16.2.0",
    "@angular/platform-browser-dynamic": "~16.2.0",
    "@angular/router": "~16.2.0",
    "@nativescript-community/arraybuffers": "^1.1.5",
    "@nativescript-community/ui-drawer": "^0.1.27",
    "@nativescript-community/ui-svg": "^0.1.33",
    "@nativescript/angular": "^16.0.0",
    "@nativescript/core": "~8.6.0",
    "@nativescript/secure-storage": "^3.0.3",
    "@nativescript/theme": "~3.0.2",
    "nativescript-clipboard": "^2.1.1",
    "platform": "^1.3.6",
    "rxjs": "~7.8.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~16.2.0",
    "@angular/compiler-cli": "~16.2.0",
    "@nativescript/android": "8.6.2",
    "@nativescript/preview-cli": "1.0.13",
    "@nativescript/types": "~8.6.0",
    "@nativescript/webpack": "~5.0.18",
    "@ngtools/webpack": "~16.2.0",
    "@types/platform": "^1.3.6",
    "typescript": "~5.1.6"
  },
  "readme": "MyVaultStart"
}

**Comment by rigor789** [comment]
That seems to be a different issue, a native package from one of the plugins (I presume `@nativescript/secure-storage` from the error) is not pre-installed in the Preview app, so that's normal:

![image](https://github.com/NativeScript/NativeScript/assets/879060/7ec1c9f8-c077-4871-a62a-543dfd7fdeab)
_from https://preview.nativescript.org/#faq_
