### ISSUE TITLE
Can not install NativeScript CLI on windows

### ISSUE THREAD

**Issue by nguyenbn7** [NativeScript/NativeScript#10547]
### Issue Description

I am following this [instruction](https://docs.nativescript.org/setup/windows) but stuck at **installing-the-nativescript-cli** , the installation failed as images bellow

![Capture](https://github.com/NativeScript/NativeScript/assets/148407637/3a2d1506-0f33-41ac-bd04-827c44f29bf1)

![image](https://github.com/NativeScript/NativeScript/assets/148407637/a24d4867-9238-4298-955e-63970d9c2c74)

![image](https://github.com/NativeScript/NativeScript/assets/148407637/f5d1ca77-4fd3-4a3c-9386-1ede435f804a)

I try to list global package in npm but it's empty

![image](https://github.com/NativeScript/NativeScript/assets/148407637/618bc25f-a9ae-45c6-bd57-4db9bab83a95)

I also use `npm install nativescript -g --force` but still failed

![image](https://github.com/NativeScript/NativeScript/assets/148407637/d835b1e1-df21-4c52-95fd-673f47042475)

![image](https://github.com/NativeScript/NativeScript/assets/148407637/7817abe7-1ce2-4e3d-b808-c1846ee91c6c)

![image](https://github.com/NativeScript/NativeScript/assets/148407637/fe62f860-7488-4bdf-9b87-8f07cd637451)

This time it show the package installed but can not use CLI.

![image](https://github.com/NativeScript/NativeScript/assets/148407637/eace64c0-3207-448f-ba6a-48fb613934c5)

Enviroment:

Windows 10 22H22 build 19045.4291
Node version: 22.1.0
NPM version: 10.7.0

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by RayLTCero** [comment]
@nguyenbn7, a workaround suggested by @rigor789 in this [issue](https://github.com/NativeScript/NativeScript/issues/10509) worked for me.
```
npm i -g npm@~10.3
npm i -g nativescript
```

**Comment by rigor789** [comment]
Please read the error message, it indicates the possible issue: network setup issue, either you are behind a proxy or you ran into an npm registry outage (in which case just try again).
