### ISSUE TITLE
NavigationButton does not show correct text when there are no action items

### ISSUE THREAD

**Issue by rclai** [NativeScript/NativeScript#1054]
```xml
<Page.actionBar>
    <ActionBar title="New Item">
      <NavigationButton text="Back"/>
    </ActionBar>
</Page.actionBar>
```

The back button keeps saying the title of the previous page instead of "Back"

However, if I do:

```xml
<Page.actionBar>
  <ActionBar title="Add New Device" icon="">
    <NavigationButton text="Back"/>
    <ActionBar.actionItems>
      <ActionItem text="Test" ios.position="left" />
    </ActionBar.actionItems>
  </ActionBar>
</Page.actionBar>
```

The back button will have the correct text, but the additional Test button will show.

**Comment by rclai** [comment]
Workaround is to do:

```xml
<Page.actionBar>
  <ActionBar title="Add New Device" icon="">
    <NavigationButton text="Back"/>
    <ActionBar.actionItems>
      <!-- this will not show -->
      <ActionItem />
    </ActionBar.actionItems>
  </ActionBar>
</Page.actionBar>
```

**Comment by N3ll** [comment]
Hey @rclai, I tested the code that you posted with {N} v.1.4.3 and the first code snippet :
```
<Page.actionBar>
    <ActionBar title="New Item">
      <NavigationButton text="Back"/>
    </ActionBar>
</Page.actionBar>
```
is working as expected. For the text of the button, I am getting the text, specified in the text attribute of the NavigationButton. Can you, please, check which version you are using?

**Comment by rclai** [comment]
I tested this on an iPod new generation using {N} 1.4.3 on the Telerik Platform.

**Comment by N3ll** [comment]
@rclai - I tried to reproduce it with iPod 7.1 through the Telerik Platform and I still could not reproduce it. What I used is just a Label that navigates to the next page.

main-page.xml
```
<Page>
    <ActionBar title="Prev Page"/>
	<Button text="Go to Next Page" tap="next"/>
</Page> 
```

main-page.js
```
var frameModel = require("ui/frame");

exports.next = function(args){
	frameModel.topmost().navigate("page");
}
```
page.xml
```
<Page>
<Page.actionBar>
    <ActionBar title="New Item">
      <NavigationButton text="back"/>
    </ActionBar>
</Page.actionBar>
</Page>
```

Can you paste the code of the page that you are navigating from, so we can check whether it influences the navigation in some way.

**Comment by pointdeveloper** [comment]
i am having the same issue as mentioned my tns version is 1.5.3..and i have tested with android 4.4 and 5.1

I am having the issue with android no text on button to tap on 

      <Page.actionBar>
        <ActionBar >
         <NavigationButton text="go back" />
        </ActionBar>
      </Page.actionBar>


i am navigating with the following code

     var frameModule =require("ui/frame");
      exports.nextview=function(){
	frameModule.topmost().navigate("views/second/second");
      }

the text "go back" does not show up so i did a work around like this
 
      <Page.actionBar>
        <ActionBar >
           <NavigationButton text="go back" android.iconVisibility="always" 
             android.systemIcon = "ic_menu_back" 
           tap="backCall"/>
        </ActionBar>
        </Page.actionBar>



and in the back call function

     var frameModule = require("ui/frame");
       function backCall() {
	    frameModule.topmost().goBack();;				
         }
        exports.backCall = backCall;

the arrow appears and i can navigate back.

Can you check this for android.

**Comment by N3ll** [comment]
@pointdeveloper, the behavior that you are describing is not expected to work in Android. You can only set an icon for the NavigationButton in Android. The workaround will not show the text, either.
