### ISSUE TITLE
Feature request: CarouselView (Android ViewPager / iOS UIPageViewController)

### ISSUE THREAD

**Issue by alexrainman** [NativeScript/NativeScript#1055]
CarouselView can be easily achieved matching Android ViewPager with iOS UIPageViewController.

Add UIPageControl in iOS for carousel dots and use this one to match it in android: https://github.com/JakeWharton/ViewPagerIndicator

Introduce methods to Add/Remove pages at runtime to make it dynamic.

**Comment by enchev** [comment]
Duplicate to https://github.com/NativeScript/NativeScript/issues/1055
