### ISSUE TITLE
ListView scroll position history

### ISSUE THREAD

**Issue by mcxolani** [NativeScript/NativeScript#1056]
Hi,

I am using a ListView and when i navigate to single item and come back to list page, it loses the scroll history and it starts from top.

I noticed that on TeleriNEXT sample app also running on my phone.

**Comment by mcxolani** [comment]
Ah ok its only on a tab view

**Comment by N3ll** [comment]
Hi @mcxolani  - can you, please, give us some more information about your scenario and post some code samples?

**Comment by bradmartin** [comment]
Ive experienced this today. So the main app view is a tabview page. One of the tabview.view is a master list with 'onItemTap' function that navigates to a new view, lets say framemodule.navigate(views/detail/detail) then when you navigate back to the view composed of the tabview the listview is scrolled to the top.

I have not tested anything but android 4.4.4 on a Samsung tab 3. Running nativescript 1.4

**Comment by mcxolani** [comment]
@N3ll just like how @bradmartin is explaining it. My app main feature is a timeline with wall posts, so you can feel my pain. Plus the other issue i don't know if it is possible to add a profile page with posts and user information on top, just like instagram or just a listview header. 

 <Page>
 <TabView>
   <TabView.items>
     <TabViewItem title="Wall">
       <TabViewItem.view>
          <ListView items="{{ myItems }}">
            <ListView.itemTemplate>
               <Label text="{{ title || 'Downloading...' }}" textWrap="true" class="title" />
            </ListView.itemTemplate>
         </ListView>
       </TabViewItem.view>
     </TabViewItem>
     <TabViewItem title="Profile">
       <TabViewItem.view>
         
          <ListView items="{{ myItems }}">
            <ListView.itemTemplate>
               <Label text="{{ title || 'Downloading...' }}" textWrap="true" class="title" />
            </ListView.itemTemplate>
         </ListView>
       </TabViewItem.view>
     </TabViewItem>
   </TabView.items>
 </TabView>
</Page>

**Comment by N3ll** [comment]
@mcxolani , @bradmartin  - a solution for keeping the scrolling is to use a the property [cachePagesOnNavigate](https://docs.nativescript.org/ApiReference/ui/frame/AndroidFrame.html) provided in the frame module. If you add the following code in your loaded function, for example, it should solved the problem:
```
if(platformModule.platformNames.android){
    	frameModule.topmost().android.cachePagesOnNavigate = true;
    }
```

**Comment by morilog** [comment]
I have same problem too, and i have been tried `cachePagesOnNavigate` but it's not work for me. :(

**Comment by cinder92** [comment]
same here any solution?

**Comment by jgraffite** [comment]
cachePagesOnNavigate works for me. Thks

**Comment by hurricaneditka16** [comment]
"Cannot set cachePagesOnNavigate if there are items in the back stack." using cachePagesOnNavigate as suggested for saving scroll position

**Comment by igorpetrov** [comment]
`cachePagesOnNavigate` not working. Any suggestions?

This behavior is absolute deal breaker for me. Long lists with infinity scroll is a core concept of my app.

**Comment by NickIliev** [comment]
Hey @igorpetrov you can use the view-model to "cache your index" and load it back when the users navigates back to the list-view. 

For example 

**_page.ts_**
```
export function onItemTap(args: RadListwModule.ListViewEventData) {
    var tappedItemIndex = args.itemIndex;

    // "cache" the tapped index
    roversViewModel.set("cachedIndex", tappedItemIndex);
    
    // go to details page
    frame.topmost().navigate("views/rovers/photo-details-page");
}

export function onListLoaded(args: RadListwModule.ListViewEventData) {
    list = <RadListwModule.RadListView>args.object;

    if (list.items) {
        // on list loaded scroll to the cached index
        list.scrollToIndex(roversViewModel.get("cachedIndex"));
    }

    list.refresh();
}
```

page.xml
```
<ListView items="{{ dataItems }}" loaded="onListLoaded" temTap="onItemTap">
```

Example implemented [here](https://github.com/NickIliev/NativeScript-Cosmos-Databank/blob/master/app/views/rovers/rover-photo-page.ts#L80-L106)

**Comment by igorpetrov** [comment]
@NickIliev thanks for solution. Scrolling to index not exactly accurate but at least it works.
