### ISSUE TITLE
Expose scroll event on ScrollView

### ISSUE THREAD

**Issue by hshristov** [NativeScript/NativeScript#1057]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/nativescript/KAJICjey2uk

**Comment by maknz** [comment]
:+1:

**Comment by bradmartin** [comment]
Curious, what will this achieve exactly? Better scroll event handling or will this patch something? Does the scrollview currently not have gesture capability?

**Comment by enchev** [comment]
Hey folks,

We've simply exposed the internal scroll event of the native component (UIScrollView and HorizontalScrollView/VerticalScrollView). You can check my pull request for more info.

Thanks
