### ISSUE TITLE
AbsoluteLayout does not cut borderRadius

### ISSUE THREAD

**Issue by qous** [NativeScript/NativeScript#10595]
### Is your feature request related to a problem? Please describe.

<template>
    <AbsoluteLayout
        width="300"
        height="300"
        backgroundColor="red"
        borderRadius="30"
        overflow="hidden"
    >
        <Label
            width="100%"
            height="100%"
            backgroundColor="rgba(0, 0, 0, 0.4)"
        ></Label>
    </AbsoluteLayout>    
</template>

the borderRadius of the child component is not clipped when using overflow: 'hidden'

I need to crop crop the borderRadius child element

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by CatchABus** [comment]
There is currently an android clipping limitation, resulting in what you experience (also, NativeScript uses `clipToBounds` on layouts instead of `overflow`).
You can apply border radius to the nested child as a workaround.

**Comment by qous** [comment]
> There is currently an android clipping limitation, resulting in what you experience (also, NativeScript supports `clipToBounds` on layouts instead of `overflow`). You can apply border radius to the nested child as a workaround for now.

I found a solution to the problem with android APIs
![solutionClipToBorderRadius](https://github.com/user-attachments/assets/41231646-94a0-41ae-8513-be5da3536030)
