### ISSUE TITLE
Android 14 emulator: App crashes with java.lang.SecurityException: "Writable dex file is not allowed."

### ISSUE THREAD

**Issue by Mahalakshmi274** [NativeScript/NativeScript#10590]
### Issue Description

Trying to run an application in an Android 14 emulator is resulting in a crash on launch with the following error:

`ERROR Error: java.lang.SecurityException: Writable dex file '/data/user/0/com.xxx.xxx/code_cache/secondary-dexes/android.view.View_AccessibilityDelegate_vendor_75312_28_TNSAccessibilityDelegateImpl.jar' is not allowed.`

**To Reproduce**

1. Run application using Android 14

**Expected behavior**
App not to crash

Stack traces
ERROR Error: java.lang.SecurityException: Writable dex file '/data/user/0/com.xxx.xxx/code_cache/secondary-dexes/android.view.View_AccessibilityDelegate_vendor_75312_28_TNSAccessibilityDelegateImpl.jar' is not allowed.

Device(s): Pixel devices and a few Samsung Devices
Android version or API level: Android 14 (API Level 34)

### Reproduction

1. Run application using Android 14

### Relevant log output (if applicable)

ERROR Error: java.lang.SecurityException: Writable dex file '/data/user/0/com.xxx.xxx/code_cache/secondary-dexes/android.view.View_AccessibilityDelegate_vendor_75312_28_TNSAccessibilityDelegateImpl.jar' is not allowed.

### Please accept these terms

- [x] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by RahulBhartiGoswami** [comment]
Looks like this is a known issue. I am also facing the same issue. I tried to update the nativescript/core library, adding  multiDexEnabled and enableDexingArtifactTransform flags but nothing helped.

**Comment by Mahalakshmi274** [comment]
This crash issue was resolved after updating Nativescript to the latest version and updating runtimes, core and webpack.
Thank you

**Comment by bhcuong2008** [comment]
I'm using Nativescript v6 for maintaining the old app, and when building for Android 14, I faced this bug. Pls help me how to set read permission for .jar file. 
I try to find out the fix in Nativescript 8 but could not figure out where to look at. In NS 8, I only see this line 137 in file `File dexDir = new File(rootDir, "code_cache/secondary-dexes");`

`System.err: Error: java.lang.SecurityException: Writable dex file code_cache/secondary-dexes/java.lang.Runnable-1726892219226-28.jar is not allowed.
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:674)
System.err:     at com.tns.Runtime.run(Runtime.java:666)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)`
