### ISSUE TITLE
Ability to disable back button navigation

### ISSUE THREAD

**Issue by ligaz** [NativeScript/NativeScript#106]
There are cases when I want to be able to disable the back button navigation on Android. It will be good if there is an out-of-the-box way to this .

**Comment by duongnhatduy** [comment]
+1, would be nice for ios too if we can disable back button.

**Comment by manijak** [comment]
+1 for iOS

**Comment by manijak** [comment]
This should also be included for iOS as well. There is no nice way to hide the back button except via code, and even then the behavior is weird. 
By using ```navigationItem.setHidesBackButtonAnimated(true, false);``` 
On page load the back button is visible for a while then just disappears. 

Would it be possible to navigate to a view without adding it to the backStack?

**Comment by N3ll** [comment]
@manijak, it is possible to navigate without adding th the backStack. You can check it here https://docs.nativescript.org/ApiReference/ui/frame/NavigationEntry.html.

**Comment by manijak** [comment]
@N3ll Thanks for the tip, but this is only for navigated pages/views? What about the main views, then ones that are displayed when the app starts, like the login-view? How do we remove that from the backstack?

**Comment by N3ll** [comment]
@manijak This will be possible in the coming version 1.4.0. Just stay tuned!

**Comment by N3ll** [comment]
@ligaz - the way to prevent back navigation is by using the activityBackPressed event. Then you can handle it by setting the cancel property of the AndroidActivityBackPressedEventData object to true. More information about it - [here] (https://docs.nativescript.org/ApiReference/application/AndroidActivityBackPressedEventData.html#object-applicationandroidactivitybackpressedeventdata).

**Comment by manijak** [comment]
Ok this is good for Android when pressing the back button on hardware.

But still we do not have a simple way to disable/hide the Back button on views. We have to write platform specific code in order to do that.

**Comment by hamorphis** [comment]
You can hide the back button like this:

``` XML
<Page xmlns="http://schemas.nativescript.org/tns.xsd">
  <Page.actionBar>
    <ActionBar>
      <NavigationButton visibility="collapsed"/>
    </ActionBar>
  </Page.actionBar>
  <StackLayout>
... content ...
  </StackLayout>
</Page>
```

Here you can learn more about how you can customize your action bar (navigation bar in iOS).

**Comment by poorcoder** [comment]
```
export function loaded(args) {
	page = <Page>args.object;
	if (page.ios) {
		topmost().ios.navBarVisibility = "always";
	}
}
```

**Comment by michaelsterpka** [comment]
For NativeScript Angular 2+

(In your component)
```
export class FooBarComponent {
  constructor(private page: Page){
    this.page.actionBarHidden = true;
  }
}
```
