### ISSUE TITLE
Adding an AVPlayer

### ISSUE THREAD

**Issue by rclai** [NativeScript/NativeScript#1066]
I'm trying to embed a video player on a page like this:
TNS .4.3 using Telerik platform

```xml
<Page ... loaded="onLoaded">
...
  <StackLayout id="video" height="200"></StackLayout>
...
</Page>
```
  
```js
exports.onLoaded = function() {
  page = args.object;
  
  var videoContainer = page.getViewById('video');
  
  var playerLayer = AVPlayerLayer.new();
  playerLayer.frame = videoContainer._nativeView.bounds;
  
  // This video is inside the App_Resources under iOS
  var videoUrl = NSBundle.mainBundle().URLForResourceWithExtension("my-video", "mp4");
  
  var player = AVPlayer.playerWithURL(videoUrl);
  player.actionAtItemEnd = AVPlayerActionAtItemEnd.AVPlayerActionAtItemEndNone;
  playerLayer.player = player;
  
  videoContainer._nativeView.layer.addSublayer(playerLayer);
  player.play();
}
```

For some reason, the video doesn't play, and there's just empty space. No errors are thrown either. What am I doing wrong?

**Comment by rclai** [comment]
Uhh it appears like the files in the App_Resources folder are inaccessible in the telerik platform perhaps in the new supported 1.4.3? I confirmed this by using an Image xml tag and used one of the stock images of a blank native app as the src="res://logo" and the image did not appear.

**Comment by manijak** [comment]
Hmm this looks interesting, I might try this in my app too see if it works (I am using CLI on OSX). I am in need of a video player for my app. 

Would be great if the team could create a cross-platform video-player component. Like this one:
https://www.fusetools.com/learn/fuse#-video-

**Comment by manijak** [comment]
Added this to the idea collection, so for those interested, vote :)
https://nativescript.ideas.aha.io/ideas/NS-I-78

**Comment by Mitko-Kerezov** [comment]
Hi @rclai 
I'm presuming you're having an issue with referencing and image with the Android platform. Please note that the Android App_Resources are specific for the different devices depending on the screen size. This said it may be that you've included your logo image in an inappropriate folder.

I've tried adding a logo.png in every subfolder of App_Resources/Android and was able to successfully display the image using ` <Image src="res://logo.png" stretch ="none" / > ` tag from the [getting started guide](https://docs.nativescript.org/ApiReference/ui/image/HOW-TO.html).

**Comment by rclai** [comment]
I'm trying to do this on an iPod and my logo was indeed in the App_Resources folder. Does the same rule apply regarding screen size?

**Comment by Mitko-Kerezov** [comment]
@rclai 
For iOS all the images are placed directly in the root of the App_Resources/iOS. I was able to display the image on an iPhone 5 with iOS 7.0 by placing it in said folder. Can you test with another device and see if it works?

**Comment by manijak** [comment]
Does the App_Resources folder behave similar towards videos as it does with images?

**Comment by rclai** [comment]
I will try with my co-worker's iPhone and see and will let you know.

**Comment by rclai** [comment]
@ivanbuhov, are you able to confirm whether my above code should work in getting a video to show up?

**Comment by bradmartin** [comment]
NPM: [https://www.npmjs.com/package/nativescript-videoplayer]( https://www.npmjs.com/package/nativescript-videoplayer)
Repo: [https://github.com/bradmartin/nativescript-videoplayer](https://github.com/bradmartin/nativescript-videoplayer)

iOS only plays local video files so if someone wants to contribute the capability to play remote video files on iOS, just make a PR and it might be good to raise the issue on the repo to help keep track as someone starts working on it.

**Comment by bradmartin** [comment]
iOS now handles remote video files. So the plugin should cover most use cases now and is planned to be verified on the Plugin Marketplace soon. #1515
