### ISSUE TITLE
CBCentralManager supported?

### ISSUE THREAD

**Issue by rclai** [NativeScript/NativeScript#1067]
I was wondering if iOS's `CBCentralManager` is supported? If so how is it supposed to be initialized?

I tried doing `CBCentralManager.initWithDelegate(this, null)`, where `this` is an instance of an `NSObject` being sub-classed in [this way](https://docs.nativescript.org/runtimes/ios/how-to/ObjC-Subclassing.html#calling-base-methods-Subclass), but it always keeps erroring saying that `initWithDelegate` is not a function.

I even tried doing `CBCentralManager.alloc().initWithDelegate(this, null)` and it still gives the same error.

I'm following [these docs](https://developer.apple.com/library/ios/documentation/CoreBluetooth/Reference/CBCentralManager_Class/index.html#//apple_ref/occ/instm/CBCentralManager/initWithDelegate:queue:) to try to replicate the initialization.

**Comment by ligaz** [comment]
Here is the declaration file for this class extracted from [here](https://raw.githubusercontent.com/NativeScript/NativeScript/master/ios.d.ts): 
```ts
declare class CBCentralManager extends NSObject {
	delegate: any;
	state: number;
	constructor(delegate: any, queue: NSObject);
	constructor(delegate: any, queue: NSObject, options: NSDictionary);
	constructor();
	initWithDelegateQueue(delegate: any, queue: NSObject): CBCentralManager;
	initWithDelegateQueueOptions(delegate: any, queue: NSObject, options: NSDictionary): CBCentralManager;
	retrievePeripherals(peripheralUUIDs: NSArray): void;
	retrievePeripheralsWithIdentifiers(identifiers: NSArray): NSArray;
	retrieveConnectedPeripherals(): void;
	retrieveConnectedPeripheralsWithServices(serviceUUIDs: NSArray): NSArray;
	scanForPeripheralsWithServicesOptions(serviceUUIDs: NSArray, options: NSDictionary): void;
	stopScan(): void;
	connectPeripheralOptions(peripheral: CBPeripheral, options: NSDictionary): void;
	cancelPeripheralConnection(peripheral: CBPeripheral): void;
	init(): CBCentralManager;
	static new(): CBCentralManager;
	static allocWithZone(zone: any): CBCentralManager;
	static alloc(): CBCentralManager;
	static extend(methods: any, exposedMethods?: {name?: string; protocols?: any[]; exposedMethods?: {[name: string]: string}}): any;
}
```

You can see that the correct signature is `initWithDelegateQueue` after `alloc`-ing it. You can also use the JavaScript constructor as well. 

More information about this [can be found](http://docs.nativescript.org/runtimes/ios/types/ObjC-Classes.html) in the iOS runtime docs.

**Comment by rclai** [comment]
Oh my goodness, thank you! I don't write in TS normally so it didn't occur to me that I could just look at the TS definition file.
