### ISSUE TITLE
Video Recording Support?

### ISSUE THREAD

**Issue by kn9ts** [NativeScript/NativeScript#108]
I've been able to add camera usage, which is also documented, but I do not see any way to be able to record a video or audio? Is this in the roadmap or already implemented but not documented.

**Comment by N3ll** [comment]
Hi @kn9ts,

There is no such feature, but you can follow-up and participate in the discussion about it here: https://github.com/NativeScript/NativeScript/issues/63.

**Comment by parliament718** [comment]
Looks like this was added 10 days ago. Yay https://github.com/triniwiz/nativescript-videorecorder
