### ISSUE TITLE
Example modal code breaks

### ISSUE THREAD

**Issue by rclai** [NativeScript/NativeScript#1084]
[This example code](https://docs.nativescript.org/ui-dialogs#page-as-custom-modal-dialog):

```js
var pages = require("ui/page");
var activityIndicator = require("ui/activity-indicator");

var p = new pages.Page();
var ai = new activityIndicator.ActivityIndicator();
ai.busy = true
p.content = ai;
p.showModal();

setTimeout(function () { p.closeModal(); }, 1000);
```

Even with no arguments passed into it, [this line of code](https://github.com/NativeScript/NativeScript/blob/481053e668e36c98d3f8c69217a23b5e84fbb27c/ui/page/page-common.ts#L204) is being hit, throwing an error.

**Comment by hshristov** [comment]
Hi @rclai,

there is no showModal method without arguments. It is like you have a page and on that page you call showModal('urlToModalPage') to show the specified page as modal.

See the docs:
https://docs.nativescript.org/ApiReference/ui/page/Page.html

**Comment by rclai** [comment]
Oh so [this example code](https://docs.nativescript.org/ui-dialogs#page-as-custom-modal-dialog) is wrong then.

**Comment by dragGH102** [comment]
@rclai The example is not about modals, but dialogs
