### ISSUE TITLE
Offline Database Example

### ISSUE THREAD

**Issue by LorenDorez** [NativeScript/NativeScript#1094]
This isnt an issue but more of a request for an Offline Database example. I know this can be done using Telerik's Everlive Backend Services but what if we already have a DB (MS SQL or MySQL) setup with an API that we can already leverage

**Comment by emiloberg** [comment]
By "offline database", do you mean a database on the device itself? If so, you probably want to take a look at the SQLite module: https://www.npmjs.com/package/nativescript-sqlite

If you mean a database available on the internet somewhere, that's just normal REST calls isn't it?

**Comment by LorenDorez** [comment]
Yes i mean on the device. For example, to be able to use it without the need for an internet connection to connect to a remote db

**Comment by luchillo17** [comment]
@emiloberg I've been researching about how persist data flows between `React Native` and `NativeScript`,
seems in `React Native` we can use `Realm` to persist `Redux` state, however in `NativeScript` with `NgRx/store` i've been unable to understand how to make it happen.

Before i jump head first into either `React Native` and `NativeScript` (i would like `NativeScript` better if i found a way to easily persist `NgRx/store` state for offline mode) do you know how would that work out?

**Comment by NathanaelA** [comment]
@luchillo17  - I can't answer specifically ngrx/store; but you can persist any data you want via several mechanisms.  I wrote both the ns-sqlite and ns-localstorage plugins, there is a firebase & couchbase  plugins and finally the framework has a built in appsettings .   You should be able use this https://www.npmjs.com/package/ngrx-store-localstorage and my localstorage plugin, or use the same idea that the plugin uses to store data however you want...

**Comment by luchillo17** [comment]
I see, so your plugin working like a polyfill for LocalStorage in NativeScript, while that one managing the @ngrx/store persistence to LocalStorage, i was about to just use React Native, but this changes everything. :smile:
