### ISSUE TITLE
Node modules missing when running 'tns platform add android'

### ISSUE THREAD

**Issue by arlowhite** [NativeScript/NativeScript#1095]
I installed node with nvm
Node v4.2.1
npm 3.3.12

Installed NativeScript with:
`npm install nativescript -g`

When I tried 'tns platform add android', I got errors for missing modules, starting with:
> Cannot find module 'child-process-close'

I had to install all of these modules for the command to finally work.
```
npm install -g child-process-close
npm install -g config-chain
npm install -g nopt
npm install -g umask
npm install -g npmlog
npm install -g uid-number
npm install -g abbrev
npm install -g npm-registry-client
npm install -g chownr
npm install -g npm-cache-filename
npm install -g write-file-atomic
npm install -g char-spinner
npm install -g read-package-json
npm install -g npm-package-arg
```

Does NativeScript need to list these as dependencies?

**Comment by N3ll** [comment]
This issue was moved to NativeScript/nativescript-cli#1181
