### ISSUE TITLE
[iOS] The background color of the ActionBar spans under the status bar

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#1097]
The background color of the ActionBar spans under the status bar on iOS. ~~It should spans only when *backgroundSpanUnderStatusBarProperty* property of the Page is set to *true*~~:  [example page] (https://github.com/NativeScript/NativeScript/blob/master/apps/ui-tests-app/action-bar/background.xml), related issue: https://github.com/NativeScript/NativeScript/issues/767.
![screen shot 2015-11-13 at 11 36 23 am](https://cloud.githubusercontent.com/assets/12251337/11142858/0b48d7ce-89f9-11e5-9273-cb9cabe31149.png)

**Comment by rclai** [comment]
This is not correct, `backgroundSpansUnderStatusBar` makes the __Page__ background span under the status bar NOT the __ActionBar__'s background color.

**Comment by vchimev** [comment]
@rclai, you are right - thanks for the correction. :)

**Comment by vchimev** [comment]
It turned out that this is not a bug - iOS 7 makes the status bar transparent, so background color of the action bar spans under it correctly.
