### ISSUE TITLE
how to create simple class in file *.ios.ts

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#1100]
Hello, I split my code between android and ios with .ios and .android extension, and I found something strange in *.ios.ts, sample class :

~~~~
in a file .ios.ts
export class aclass {
    constructor() {
        console.log("ok");
    }
}
~~~~

if I call new somemodule.aclass(); it will show error TypeError: undefined is not a constructor

but if I put the class in the .android.ts or in the caller's .ts it's working perfectly 

Is it in the *.ios.ts the class is an objectiveC class instead of javascript class ? because other class that extends objectiveC class works ok

**Comment by enchev** [comment]
Hey @x4080,

Can you post the transpiled JavaScript?

Thanks

**Comment by x4080** [comment]
Just regular class in js I think :

~~~~
var aclass = (function () {
    function aclass() {
        console.log("ok");
    }
    return aclass;
})();
exports.aclass = aclass;
~~~~

**Comment by enchev** [comment]
Please let us know if you find again something similar!

**Comment by x4080** [comment]
Sure sorry about that
