### ISSUE TITLE
Ability to specify an animation easing, i.e. curve in a platform-independent manner.

### ISSUE THREAD

**Issue by amjd** [NativeScript/NativeScript#1102]
It would be great if the platform-specific details could be abstracted in animation, so we could use the universal easing functions such as ease-in, ease-in-out, etc just by passing the name.

Is this possible at present? If not, please consider adding it in the next release.

**Comment by hamorphis** [comment]
Definitely a good idea. I will do some research for a possible API for this. Thank you for your suggestions.

**Comment by amjd** [comment]
Thanks for beginning the implementation. Any instructions on how to use it? :) Also, will this be a part of the 1.5 release?

**Comment by emiloberg** [comment]
@hamorphis Just out of curiosity, why are you save things like easing in in the `enums` file? I'm thinking that stuff like easing is never used anywhere else except when creating an animation and could therefor be placed in the `animation-common` file.

**Comment by hamorphis** [comment]
@emiloberg That is correct, but the same applies for all other enums. In the beginning of NativeScript we decided to stuff everyting in enums and we do it for consistency, even though I realize that this might have been a mistake :(

**Comment by amjd** [comment]
@hamorphis Is there a documentation page where we can learn how to use the new feature and which animation curves are supported?
