### ISSUE TITLE
Dynamic itemTemplate for Repeater

### ISSUE THREAD

**Issue by rclai** [NativeScript/NativeScript#1111]
Is it possible to do different `itemTemplate` per item on the `Repeater`?

**Comment by enchev** [comment]
You can have dynamic template content depending on some binding. For example:
```XML
<Repeater items="{{ someItems }}">
  <Repeater.itemsLayout>
    <WrapLayout  />
  </Repeater.itemsLayout>
  <Repeater.itemTemplate>
    <StackLayout>
      <Label visibility="{{ yourCondition ? 'visible' : 'collapsed' }}" />
      <Label visibility="{{ yourOtherCondition ? 'visible' : 'collapsed' }}" />
    </StackLayout>
  </Repeater.itemTemplate>
</Repeater>
```

**Comment by rclai** [comment]
Does this perform well? What if there many many different kinds?

**Comment by enchev** [comment]
This will perform in the same way as with normal template, still I suggest you if you want to show hundreds of items to use ListView because of the built-in UI virtualization.
