### ISSUE TITLE
iOS: action bar title issues

### ISSUE THREAD

**Issue by rclai** [NativeScript/NativeScript#1112]
```xml
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="onLoaded">
  <Page.actionBar>
    <ActionBar title="{{ customTitle }}" />
  </Page.actionBar>
  <StackLayout>
    <Label text="blah1" />
    <Label text="blah2" />
    <Label text="blah3" />
  </StackLayout>
</Page>
```

```js
var Observable = require('data/observable').Observable;
var viewModel = new Observable({ customTitle: 'hello??' });

exports.onLoaded = function(args) {
  args.object.bindingContext = viewModel;
};
```

This doesn't work.  This causes a freezing crash with a blank error.

However, if I change the action bar title to this:

```xml
<ActionBar title="{{ customTitle + 'awefawefawef' }}" />
```

This works. It will show `hello??awefawefawef`. So pretty much I have to workaround this freezing crash by doing `<ActionBar title="{{ customTitle + '' }}" />` to make it work.

In addition, when it DOES work, my stack layout (shown above) ends up getting overlapped by the action bar instead of going below the action bar.

This is {N} 1.4.3 in the browser-based Telerik Platform.

**Comment by hamorphis** [comment]
I will split the issue in two separate issues. Here is the other one: https://github.com/NativeScript/NativeScript/issues/1123

**Comment by hamorphis** [comment]
I reproduced the crash with with version 1.4.0 of the tns-core-modules. The app runs fine with our latest source from the `master` branch. I will now do a `git bisect` to find which commit fixes this issue.

**Comment by hamorphis** [comment]
Can you send some stack trace or other artifact describing the crash?

**Comment by rclai** [comment]
There is none because it just shows blank.

**Comment by hamorphis** [comment]
I have tried the code above with version 1.4.0 and our current release candidate for 1.5.0 and the ActionBar shows just fine. There is no crash. Unless I am able to reproduce this somehow, I don't know what I can do regarding this issue.

**Comment by N3ll** [comment]
@rclai - you can try to debug the code on your device. You can check the requirements [here](http://docs.telerik.com/platform/appbuilder/nativescript/debugging-your-code/debugging-on-device/prerequisites-for-debugging) and the procedure how to do it [here](http://docs.telerik.com/platform/appbuilder/nativescript/debugging-your-code/debugging-on-device/debug-on-ios-device). Another thing that might help is to check the [view logs](http://docs.telerik.com/platform/appbuilder/nativescript/debugging-your-code/view-logs).
