### ISSUE TITLE
Android ActionBar breaks when add styles.xml file

### ISSUE THREAD

**Issue by victorhugom** [NativeScript/NativeScript#1113]
I have a simple ActionBar and after I added a styles.xml file the app broke.

![screenshot_20151117-171040](https://cloud.githubusercontent.com/assets/146950/11221860/84444840-8d4e-11e5-9998-9d04d75e7dff.png)

Styles.xml
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <!-- inherit from the material theme -->
  <style name="AppBaseTheme" parent="Theme.AppCompat.Light">
        <item name="android:windowNoTitle">true</item>
        <!-- Main theme colors -->
        <!--   your app branding color for the app bar -->
        <item name="android:colorPrimary">#ff3100</item>
        <!--darker variant for the status bar and contextual app bars -->
        <item name="android:colorPrimaryDark">#d11f01</item>
        <!--theme UI controls like checkboxes and text fields -->
        <item name="android:colorAccent">#0065cf</item>
  </style>
</resources>
```

```
...
  <Page.actionBar>
    <actionBar title="{{ title }}"></actionBar>
  </Page.actionBar>
...
```

**Comment by vakrilov** [comment]
@victorhugom To shed som light on the matter. The property of the `Page` is called `actionBar` and the name of the class is `ActionBar` (capital "A"). So the right way to  use this is:
```
<Page>
  <Page.actionBar>
    <ActionBar title="Title">
      <ActionBar.actionItems>
        <ActionItem text="left"  ios.position="left"/>
      </ActionBar.actionItems>
    </ActionBar>
  </Page.actionBar>
  ...
</Page>
```
I hope that helps - you can find more examples in the [ActionBar - How To](http://docs.nativescript.org/ApiReference/ui/action-bar/HOW-TO). 
It is possible that there is a typo somewhere in the docs. If you think you found one please send us the exact location so that we can fix it.

**Comment by vakrilov** [comment]
@victorhugom By the way - about the `styles.xml` - it may be useful to take a look at the default styles.xml that are included in the project if you don't specify yours. You can find them [here](https://github.com/NativeScript/android-runtime/tree/master/build/project-template-gradle/src/main/res). You can see that the theme is based on `Theme.AppCompat.Light.NoActionBar`(which i think is similar to `Theme.AppCompat.Light` with `windowNoTitle`). So maybe you can avoid redefining `styles.xml` and only use the `colors.xml`.

**Comment by victorhugom** [comment]
Thanks @vakrilov, after I modify the `styles.xml` using the default file as base the bug stopped
