### ISSUE TITLE
How to debug layout?

### ISSUE THREAD

**Issue by tenorok** [NativeScript/NativeScript#1115]
Hello!

I'm reading documentation about debugging: https://docs.nativescript.org/runtimes/ios/debug/Debug

Thank you for debug opportunity it is very helpful!
But I don't understand how to debug layouts? Elements tab is empty.

**Comment by N3ll** [comment]
@tenorok - can you please paste the XML code which you are trying to debug, so we can get a better understanding of the problem.

**Comment by tenorok** [comment]
I work on OS X 10.10.5.

```
tns --version # → 1.4.3
```

Steps for reproducing:
```
tns create tns-example
cd tns-example/
tns platform add ios
tns debug ios --emulator --device "iPhone-6" --debug-brk
```

We will see:
![2015-11-19 14 10 54](https://cloud.githubusercontent.com/assets/1322855/11269370/9fc1a714-8ec7-11e5-9699-d3ac9edfbd72.png)

**Comment by N3ll** [comment]
Support for the visual tree will be provided in one of the next versions of {N}. You can follow and participate in the discussion https://github.com/NativeScript/NativeScript/issues/165.
