### ISSUE TITLE
xml-binding: Using ternary if with "greater than" operator yields error.

### ISSUE THREAD

**Issue by nedium** [NativeScript/NativeScript#1118]
Created a new project and changed the line displaying the xx taps left message markup to 
```xml
<Label text="{{ message }}" cssClass="{{ counter < 30 ? 'messageGreen' : 'message' }}" textWrap="true"/>
```
This works ok and changes cssClass to messageGreen when counter is less than 30.
But when i change the operator from less than to greater than as below
```xml
<Label text="{{ message }}" cssClass="{{ counter > 30 ? 'messageGreen' : 'message' }}" textWrap="true"/>
```
app throws an unhandled exception:
`
Error: XML parse error: close tagname
`

I can guess `>` is cought by the markup parser as close tag initiator but i think it should be omitted if its in double quotes.

As a workaround, i have created a function in viewmodel to return bool value if counter is greater than 30 or not.

**Comment by hamorphis** [comment]
When the sax parser encounters a `<` bracket, it immediately seeks the first occurrence of a `>` bracket to determine the boundaries of the tag. In your case it finds the `>` that is inside the attribute value. 

I am afraid that you will have to use and `&gt;` so the parser does not break. We use an **external** sax parser (with minimal modifications) and even though we can actually rewrite the parser to support the `>` bracket inside text, this will significantly slow it down and hurt performance. I know that it is not **mandatory** to escape the `>` bracket in XML, but w3.org recommends it anyway. Besides, w3.org states that you should always escape the `<` bracket inside text, even though our parser supports it.

http://www.w3.org/TR/2008/REC-xml-20081126/#syntax

> The ampersand character (&) and the left angle bracket (<) MUST NOT appear in their literal form, except when used as markup delimiters, or within a comment, a processing instruction, or a CDATA section. **If they are needed elsewhere, they MUST be escaped using either numeric character references or the strings `&amp;` and `&lt;` respectively**. The right angle bracket (>) **may** be represented using the string `&gt;`, and MUST, for compatibility, be escaped using either `&gt;` or a character reference when it appears in the string " ]]> " in content, when that string is not marking the end of a CDATA section.

**Comment by nedium** [comment]
Fair enough. I have already found a workaround for this. The reason of posting this issue was helping you and the community. 
There is no single word in documentation about this restriction, so please add a description about this case to related document. ie: (http://docs.nativescript.org/bindings#supported-expressions)

**Comment by hamorphis** [comment]
@nedium I will add this to the docs. Thanks.
