### ISSUE TITLE
Combing nativeScript with Swift and Java (ios and android native)

### ISSUE THREAD

**Issue by AlexDM0** [NativeScript/NativeScript#1121]
Hi all,

We have an application that currently uses c++ for a shared backend logic core of multiple apps. We want to modernize it and get rid of a lot of the current overhead. I was wondering if nativescript could work alongside a native implementation? We would have one module running javascript which should ideally be able to use some of our natively implemented methods. Is this feasible? I could not find anything in the issues or documentation about this..

Regards,

Alex

**Comment by x4080** [comment]
I think you can, just create libraries in native and call from ns

**Comment by PanayotCankov** [comment]
Hi,

You can consume native libraries from {N}. But exposing JavaScript defined classes for use in your Java and Objective-C is not that straight forward at the moment.

This is possible in theory but not documented or officially supported at all. It will involve a lot of extra effort to polish the path of integrating {N} in exiting apps. It will be put more stress on the cross platform modules to allow the common UI abstraction to be consumed by existing apps, while the runtimes are already forced to expose APIs to the native.

You can see for example one of our docs that never hit live playing with iOS Today Widgets:
https://github.com/NativeScript/ios-runtime-docs/blob/extensions-today-view/extensions/TodayExtension.md
It has the information (although terribly outdated) how you can add the native bits to a new (read existing) target, add the metadata, initialize the runtime, define some classes in JavaScript that register Objective-C classes with the iOS runtime (in that case the NSExtensionPrincipalClass). You can write header files to express the Objective-C classes implemented in JavaScript to allow existing Objective-C code to consume them.

In the long term you may consider the ios-runtime is doing with JavaScript something similar to what Swift is doing.

I am not so familiar with the android-runtime but there is a recent push to support all kind of services and activities. The JavaScript for android generates dex files either at compile or runtime so it shouldn't be that hard to expose the JavaScript defined classes for use from Java.

**Comment by AlexDM0** [comment]
Hi,

Thanks for your reply. We chose to go with the native JavaScriptCore and a C based JSengine for android. We don't need UI bindings, just cross platform logic. 

Regards
