### ISSUE TITLE
iOS: ActionBar covers the page.

### ISSUE THREAD

**Issue by hamorphis** [NativeScript/NativeScript#1123]
[Original issue](https://github.com/NativeScript/NativeScript/issues/1112) posted by @rclai

```xml
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="onLoaded">
  <Page.actionBar>
    <ActionBar title="{{ customTitle }}" />
  </Page.actionBar>
  <StackLayout>
    <Label text="blah1" />
    <Label text="blah2" />
    <Label text="blah3" />
  </StackLayout>
</Page>
```

```js
var Observable = require('data/observable').Observable;
var viewModel = new Observable({ customTitle: 'hello??' });

exports.onLoaded = function(args) {
  args.object.bindingContext = viewModel;
};
```

My stack layout (shown above) ends up getting overlapped by the action bar instead of going below the action bar.

This is {N} 1.4.3 in the browser-based Telerik Platform.

**Comment by rclai** [comment]
This is 1.6?

**Comment by hamorphis** [comment]
We have not debugged this issue yet. We don't know what is going on.

**Comment by rclai** [comment]
Oh ok.

**Comment by hamorphis** [comment]
We found the problem. As a quick workaround, can you please try to use the `navigatingTo` event instead of the `loaded` event to set the `bindingContext` of the page.

**Comment by vchimev** [comment]
This issue is not reproducible with 1.6.0 release candidates. To be reopened if needed.
