### ISSUE TITLE
Action bar doesn't display properly in Android 4.4

### ISSUE THREAD

**Issue by amjd** [NativeScript/NativeScript#1124]
The action bar looks like a native component when I test the app on Android 5, but on Android 4.4 it looks weird, the height and font-size are reduced, and a native-feeling (styled like other components of Android 4.4) action bar displays above the actual action bar. I tested this on two devices, a phone and a tablet, both had the same issue. I'll try adding a screenshot here later.

**Comment by N3ll** [comment]
@amjd - can you, please, provide code samples of the Action bar and state which version of {N} you are using, so we can get better understanding of the problem.

**Comment by amjd** [comment]
I'm using {N} 1.4.3.

This is the XML code for the Action bar:

```xml
  <Page.actionBar>
      <ActionBar title="SupportIT">
        <ActionBar.actionItems>
            <ActionItem text="Item 1" android.position="popup" />
            <ActionItem text="Item 2" android.position="popup" />
            <ActionItem text="Item 3" android.position="popup" />
            <ActionItem text="Logout" tap="logOut" android.position="popup" />
        </ActionBar.actionItems>
      </ActionBar>
  </Page.actionBar>
```

Also, on a related note, is it possible to change the color of the Action items icon?

**Comment by vakrilov** [comment]
@amjd We've tested your code with the 1.5 release and the action-bar is shown correctly. There are some differences in the styles - they come from the native android theme and are expected.

Here is how the app looks on our end:
Android 4.4:

![action-bar4 4](https://cloud.githubusercontent.com/assets/4092076/11531202/c6675e7c-9903-11e5-8e91-7763a9a09353.png)

Android 5.1:

![action-bar5](https://cloud.githubusercontent.com/assets/4092076/11531210/d7a011ac-9903-11e5-87d8-a4bb4645a73a.png)

**Comment by vakrilov** [comment]
About the color of the icons - you can images or resources as an icon so the color is up to you what images you will choose.
