### ISSUE TITLE
Changing ActionBar title after page is loaded does not show the ActionBar

### ISSUE THREAD

**Issue by hshristov** [NativeScript/NativeScript#1127]
Setup:
- Frame.ios.navBarVisibility is "auto" (which is the default value)
- ActionBar doesn't have items
- ActionBar title is set after page is loaded (e.g. try with setTimeout)

ActionBar is not shown but is should be.

**Comment by Jpaagt** [comment]
Is this really fixed or just forgotten? I tried setting the title in the XML template but it did not work, much less does it change when the binding is modified. I also tried setting in JS/TS asigning to the title property of the ActionBar and using set(propName, value) on the ActionBar but the title was not updated in the apps UI. The only thing that worked for me was calling the ActionBar's update() method after changing the title programatically.

**Comment by mhmo91** [comment]
Any updates here?
