### ISSUE TITLE
Why are iOS modal animations disabled by default? Can we pass an option to enable it?

### ISSUE THREAD

**Issue by rclai** [NativeScript/NativeScript#1129]
https://github.com/NativeScript/NativeScript/blob/fabe0baec564a4c3d9ee4e3bbfb201471c76641e/ui/page/page.ios.ts#L229

https://github.com/NativeScript/NativeScript/blob/fabe0baec564a4c3d9ee4e3bbfb201471c76641e/ui/page/page.ios.ts#L238

**Comment by enchev** [comment]
Will be animated in iOS 9 and above!

**Comment by toddanglin** [comment]
Shouldn't there be an overload for `showModal` that accepts a `NavigationEntry`?

This would allow you to control the modal animation and possibly use a page factory to generate the modal view page. Does this make sense? Or am I crazy? :)

**Comment by enchev** [comment]
Hey @toddanglin,

We believe that our modal pages should not be part of the navigation stack - you cannot navigate to a modal page.

**Comment by toddanglin** [comment]
That makes sense.

I was looking at it from the view of providing a way to specify the transitions (iOS/Android/Default) when showing a modal view, and possibly to provide the ability to dynamically generate a modal view (the `create` function). Is there a better/different way to do this with modals?
