### ISSUE TITLE
iOS build with 1.0 stuck

### ISSUE THREAD

**Issue by dbbk** [NativeScript/NativeScript#113]
Starting a new project from scratch, when I run

`tns run ios --emulator`

The build process gets stuck at this point:

`Generating metadata for i386:
./metadata-generation-build-step.sh: line 4: $BUILT_PRODUCTS_DIR/metadata-generation-stderr-$1.txt: ambiguous redirect`

Any help?

**Comment by dbbk** [comment]
Identified the issue, builds fail when any directory in the path contains a space.

**Comment by valentinstoychev** [comment]
Thank you for reporting this Ben - we are working on it. Please follow the ios-runtime issue for updates  nativescript/ios-runtime#106
