### ISSUE TITLE
Changing Image source URL causes "flickering" (iOS)

### ISSUE THREAD

**Issue by toddanglin** [NativeScript/NativeScript#1132]
I have an issue causing an image "flickering" problem (in iOS...haven't tested Android). The basic configuration is this:

1. A simple `Repeater` with a `StackLayout` rendering `Image` elements
2. `Repeater` is bound to an `ObservableArray`
3. `ObservableArray` has collection of remote/external image URL strings

In this scenario, the the image URLs are changing regularly (every 5 seconds), and the expectation is that the new image replaces the old image "instantly." Instead, there is a visible "flicker" as the new image is downloaded and replaces the old image. You can see the resulting effect in the GIF below.

![nativescript-images](https://cloud.githubusercontent.com/assets/647319/11321651/c390fd80-908d-11e5-85f9-bda8dff1fd82.gif)

I assume using the ImageSource object to pre-download the image and THEN set the Image source would solve the problem, BUT I'd prefer to continue to use the ObservableArray and XML binding.

```xml
   <Repeater items="{{ imageArray }}">
     <Repeater.itemsLayout>
        <StackLayout />
     </Repeater.itemsLayout>
     <Repeater.itemTemplate>      
        <Image src="{{ $value }}" />
     </Repeater.itemTemplate>
   </Repeater>
```
```javascript
//Snippet
imageArray: new observableArrayModule.ObservableArray([])
//Array contains remote/external URLs to PNG images
```

I know the `Image` internals already attempt to async download an image URL and create a new `ImageSource`, so not sure why there is a visual "flicker" or "lag" to see the new image replace the old image. Thoughts?

**Comment by hshristov** [comment]
@toddanglin I'm not sure what do you refer exactly - the time that it needs to render or maybe a flickering when new image changes an existing one (haven't tested your case).
The current state is that image is downloaded from the internet but it is decoded on the UI thread. So if you have large images it may take some time before they render.

We have plans on improving this by rendering images in different thread but it is not ready yet.
If that is not the case please share a sample where I can see the issue.

**Comment by toddanglin** [comment]
That's probably exactly what's happening (large images being decoded on UI thread). In my case, the images are coming from an IP camera, so they're probably 1280x720 (but being resized as thumbnails in the app).

I'll experiment with smaller images to confirm, but this is likely just a big +1 for background thread image decoding. :)

Thanks for the quick input.




On Sun, Nov 22, 2015 at 11:31 PM -0800, "Hristo Hristov" <notifications@github.com<mailto:notifications@github.com>> wrote:


@toddanglin<https://github.com/toddanglin> I'm not sure what do you refer exactly - the time that it needs to render or maybe a flickering when new image changes an existing one (haven't tested your case).
The current state is that image is downloaded from the internet but it is decoded on the UI thread. So if you have large images it may take some time before they render.

We have plans on improving this by rendering images in different thread but it is not ready yet.
If that is not the case please share a sample where I can see the issue.

-

**Comment by N3ll** [comment]
The discussion is moved to https://github.com/NativeScript/NativeScript/issues/151.
