### ISSUE TITLE
provide alternatives for element tags with periods

### ISSUE THREAD

**Issue by TMaYaD** [NativeScript/NativeScript#114]
Using jade to author xmls currently chokes on elements like ```ListView.itemTemplate``` which translates to ```<ListView cssClass="itemTemplate">``` currently.
providing alternatives to such items will allow the use of such templating languages.
CSS selectors also become ambiguous with periods.

ex: ListView_itemTemplate, itemTemplate, ListViewItemTemplate

**Comment by hdeshev** [comment]
Tags with periods seem problematic for HTML-based template engines (having some issues with them in the AngularJS renderer too). The good news here is that the Jade language is powerful enough and you can handle that case with a mixin.

This template:

```
mixin listViewTemplate
    <ListView.itemTemplate>
    block
    </ListView.itemTemplate>

ListView(items="{{todos}}", class="mylistview")
    +listViewTemplate
        Label(text="{{title}}")
```

Gets rendered as:

```xml
<ListView items="{{todos}}" class="mylistview">
    <ListView.itemTemplate>
        <Label text="{{title}}"></Label>
    </ListView.itemTemplate>
</ListView>
```

(indentation mine)

That said, it'd be very interesting if somebody packages up a Jade support plugin or library for NativeScript. Closing this issue for now.
