### ISSUE TITLE
iOS TabView Icon rendering mode set wrong

### ISSUE THREAD

**Issue by rclai** [NativeScript/NativeScript#1148]
`renderingMode` on `UIImage` is a read-only property: https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIImage_Class/#//apple_ref/occ/instp/UIImage/renderingMode

As a result of this the icon will always be gray on the tab view on iOS.

You guys are trying to set it here, but it doesn't work: https://github.com/NativeScript/NativeScript/blob/79f009fb383c5f933e62e1768d3930fd090371ac/ui/tab-view/tab-view.ios.ts#L246

The correct way is to use `imageWithRenderingMode`.

**Comment by N3ll** [comment]
@rclai : we tested your code and the result was - icons with their original colors. But the tabs did not change when you switch among them. The only way the user to know that a certain tab is chosen is by looking at the content inside the tabs, which is not very convenient. Is this what you were trying to achieve or are missing something?
