### ISSUE TITLE
Why don't you fix your website?

### ISSUE THREAD

**Issue by rubenstolk** [NativeScript/NativeScript#115]
The website has been having a SSL-issue since last couple of weeks...

![screen shot 2015-05-05 at 12 10 39](https://cloud.githubusercontent.com/assets/692644/7470755/f7294faa-f31f-11e4-8cb9-abc1d7d7179f.png)

**Comment by valentinstoychev** [comment]
Hmm - we believed we have fixed this issue last week. But lets investigate it again. Thanks for pointing it out!

**Comment by kaurag007ph** [comment]
I think since then Nativescript used .org instead of .com

**Comment by valentinstoychev** [comment]
This should be fixed now.
