### ISSUE TITLE
Error when navigate between tabs on TabView

### ISSUE THREAD

**Issue by victorhugom** [NativeScript/NativeScript#1150]
```
  <TabView selectedIndex="{{selected_tab}}">
    <TabView.items>
      <TabViewItem iconSource="res://home_w">
        <TabViewItem.view>
          <feed:feed/>
        </TabViewItem.view>
      </TabViewItem>
      <TabViewItem iconSource="res://map_w">
        <TabViewItem.view>
          <map:map/>
        </TabViewItem.view>
      </TabViewItem>
      <TabViewItem iconSource="res://bell_w">
        <TabViewItem.view>
          <notifications:notifications/>
        </TabViewItem.view>
      </TabViewItem>
      <TabViewItem iconSource="res://profile_w">
        <TabViewItem.view>
          <profile:profile/>
        </TabViewItem.view>
      </TabViewItem>
    </TabView.items>
  </TabView>
```

11-24 18:37:12.374  8832  8832 E art     : invalid stream - problem with parameter iterator in /data/user/0/org.nativescript.events/code_cache/secondary-dexes/android.support.v4.view.PagerAdapter_fternal_prepareExtend_l60_c37__PagerAdapterClass-1448397369872-1.jar for method java.lang.Object com.tns.gen.android.support.v4.view.PagerAdapter_fternal_prepareExtend_l60_c37__PagerAdapterClass.instantiateItem(android.view.ViewGroup, int)
11-24 18:37:12.401  8832  8832 E TNS.Native: Error: java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to org.nativescript.widgets.HorizontalScrollView$SavedState
11-24 18:37:12.401  8832  8832 E TNS.Native:     org.nativescript.widgets.VerticalScrollView.onRestoreInstanceState(VerticalScrollView.java:161)
11-24 18:37:12.401  8832  8832 E TNS.Native:     android.view.View.dispatchRestoreInstanceState(View.java:14746)
11-24 18:37:12.401  8832  8832 E TNS.Native:     android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3121)
11-24 18:37:12.401  8832  8832 E TNS.Native:     android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
11-24 18:37:12.402  8832  8832 E TNS.Native:     android.view.View.restoreHierarchyState(View.java:14724)
11-24 18:37:12.402  8832  8832 E TNS.Native:     com.tns.Platform.callJSMethodNative(Native Method)
11-24 18:37:12.402  8832  8832 E TNS.Native:     com.tns.Platform.dispatchCallJSMethodNative(Platform.java:821)
11-24 18:37:12.402  8832  8832 E TNS.Native:     com.tns.Platform.callJSMethod(Platform.java:708)
11-24 18:37:12.402  8832  8832 E TNS.Native:     com.tns.Platform.callJSMethod(Platform.java:687)
11-24 18:37:12.402  8832  8832 E TNS.Native:     com.tns.Platform.callJSMethod(Platform.java:677)
11-24 18:37:12.402  8832  8832 E TNS.Native:     com.tns.gen.android.support.v4.view.PagerAdapter_fternal_prepareExtend_l60_c37__PagerAdapterClass.instantiateItem(android.support.v4.view.PagerAdapter.java)
11-24 18:37:12.402  8832  8832 E TNS.Native:     android.support.v4.view.ViewPager.addNewItem(ViewPager.java:870)
11-24 18:37:12.402  8832  8832 E TNS.Native:     android.support.v4.view.ViewPager.populate(ViewPager.java:1054)
11-24 18:37:12.402  8832  8832 E TNS.Native:     android.support.v4.view.ViewPager.populate(ViewPager.java:952)
11-24 18:37:12.402  8832  8832 E TNS.Native:     android.support.v4.view.ViewPager$3.run(ViewPager.java:251)
11-24 18:37:12.402  8832  8832 E TNS.Native:     android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
11-24 18:37:12.402  8832  8832 E TNS.Native:     android.view.Choreographer.doCallbacks(Choreographer.java:670)
11-24 18:37:12.402  8832  8832 E TNS.Native:     android.view.Choreographer.doFrame(Choreographer.java:603)
11-24 18:37:12.402  8832  8832 E TNS.Native:     android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
11-24 18:37:12.402  8832  8832 E TNS.Native:     android.os.Handler.handleCallback(Handler.java:739)
11-24 18:37:12.403  8832  8832 E TNS.Native:     android.os.Handler.dispatchMessage(Handler.java:95)
11-24 18:37:12.403  8832  8832 E TNS.Native:     android.os.Looper.loop(Looper.java:148)
11-24 18:37:12.403  8832  8832 E TNS.Native:     android.app.ActivityThread.main(ActivityThread.java:5417)
11-24 18:37:12.403  8832  8832 E TNS.Native:     java.lang.reflect.Method.invoke(Native Method)
11-24 18:37:12.403  8832  8832 E TNS.Native:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-24 18:37:12.403  8832  8832 E TNS.Native:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-24 18:37:12.403  8832  8832 E TNS.Native: File: "/data/data/org.nativescript.events/files/app/tns_modules/ui/tab-view/tab-view.js, line: 49, column: 30
11-24 18:37:12.403  8832  8832 E TNS.Native: StackTrace:
11-24 18:37:12.403  8832  8832 E TNS.Native:    Frame: function:'PagerAdapterClass.instantiateItem', file:'/data/data/org.nativescript.events/files/app/tns_modules/ui/tab-view/tab-view.js', line: 49, column: 31
11-24 18:37:12.405  8832  8832 D AndroidRuntime: Shutting down VM

**Comment by N3ll** [comment]
@victorhugom : can you give us some more information about the version of {N} which you are using and on what device you are testing, so we can reproduce the error precisely?

**Comment by victorhugom** [comment]
@N3ll I'm using the  {N} 1.4.0 and to test I'm using a Nexus 6 with Android 6.0 and a Moto G 2014 with Android 4.4.3

**Comment by N3ll** [comment]
@victorhugom I used the same code and as yours, only I changed your custom components with Labels and your images with the icon images from the resources. I tested on Nexus 6 Genymotion emulator and I could not reproduce the error. What I suggest is to try to replace the custom components with Labels and see whether you will get the same error again.

**Comment by victorhugom** [comment]
@N3ll I tested, and found the issue, is with the [map component](https://github.com/dapriett/nativescript-google-maps-sdk), I use the same map in another view and there is no error, I'll try to find a solution. 
Thank you for the help

**Comment by dbenninger** [comment]
@victorhugom, I have the same issue with the map component. How did you solve this?
