### ISSUE TITLE
ActionBar styling in 1.5.0

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#1151]
Upgraded to 1.5.0 just now. Everything works fine except that all my ActionBars lost their styling. 
I had the ActionBar style changed in the main-view via code, overridden for ios: bar-style, bar-color, font-color and font-family. It was enough to set it once here, in the main-view, and it was applied to all views in the app.

Now after the upgrade to 1.5, the ios styling was only applied to the main view, and not the other views. After adding a global ActionBar { ... } css style the font-color and background-color are now OK.

But I still have to change the ios barStyle to UIBarStyle.UIBarStyleBlack via code. 

Same goes for font-family, has to be changed via code, does not change via css. And it is only changed in that view, and not across all views (like it did before).

Also, when changing the font-family via code, it only allows me to do so in the pageLoaded event. This gives a very ugly effect where you see that the font-family changes from default to custom while the page is loading. Tried doing the same in the navigatingTo event, but did not work. 

Any new tricks to get a diferent font in the ActionBar?

**Comment by tjvantoll** [comment]
I ran into the same problem. It’s awesome that you can set color and background color in CSS now, but the 1.5 code seems to wipe away any changes you manually make to the UINavigationBar, which I find to be a pretty common thing to need to do.

In my case I want to set the UINavigationBar’s `translucent` flag to `false` ([here’s my use case](https://github.com/NativeScript/sample-Groceries/issues/37)), and I end up with this, uh, interesting behavior.

![translucent](https://cloud.githubusercontent.com/assets/544280/11409957/7d669a8e-9391-11e5-91d2-83f15a9ea5da.gif)

**Comment by manijak** [comment]
@tjvantoll  Does the ```translucent``` flag realy work in {N}? I never got it to be true translucent.

It should behave as the first option here, but I've only seen the second one.
![Translucent navbar ios](http://i.stack.imgur.com/ZQzd3.png)

**Comment by vakrilov** [comment]
It seems that there are many issues at play here:

@manijak Indeed - for 1.5 we added support for `color`(basically font-color) and `background-color`. We don't set `font-family` explicitly, but we do set the `titleTextAttributes` property of the nav-bar so maybe that is what clears your style.
Can you please send us the exact code that you use to set the font-family so that we can confirm this.

One other thing you can try is to use the ActionBar's `titleView` property and put a `Label` as a title element. There you can use all the supported CSS properties to style it:
```
  <Page.actionBar>
    <ActionBar>
      <ActionBar.titleView>
        <Label text="Styled Label" style="font-size: 24; font-family: Times New Roman; color: green;" />
      </ActionBar.titleView>
    </ActionBar>
  </Page.actionBar>
```
This is not applicable for the action-items, because you cannot set a custom view inside an action-item.

**Comment by tjvantoll** [comment]
@manijak No I’ve never gotten the action bar to be truly translucent. I don’t know enough about iOS to know if that flag is working as expected or not though. Changing the display of an iOS UINavigationBar appears to be a jar full of spiders 🕷. I’d need more time to play with this to say anything definitive 😀

**Comment by manijak** [comment]
Please do something about the page-transitions when ```navbar.translucent``` is set to ```false```. It looks awful with the space between the actionbar and the new page. Look at the animation @tjvantoll posted!

This should be prioritized as it cannot be used in this state.

**Comment by speigg** [comment]
@manijak To make a translucent UINavigationController work, you need to do this in the pageLoaded callback:

```javascript
		page.ios.automaticallyAdjustsScrollViewInsets = true;
		page.backgroundSpanUnderStatusBar = true;
		page.actionBar.getMeasuredHeight = function() { return 0 };
		uiUtils.ios.getStatusBarHeight = function() { return 0 };
```

**Comment by manijak** [comment]
Thanks @speigg .
What does ```uiUtils``` in your example refer to?

**Comment by tjvantoll** [comment]
@manijak It refers to http://docs.nativescript.org/ApiReference/ui/utils/ios/README, or `var uiUtils = require("ui/utils");`

@speigg Thanks, but unfortunately this workaround doesn’t work for me. Making `getMeasuredHeight()` return `0` makes the content under the action bar appear underneath it, and I still see the awkward animation I showed in a previous comment. If you want to see the problem in action you can run [this sample](https://github.com/NativeScript/sample-Groceries), and add `navigationBar.translucent = false;` in [this file](https://github.com/NativeScript/sample-Groceries/blob/09b98ec3f03c477332efe7f91218a529ed73bb90/app/shared/utils/action-bar-util.js).

**Comment by skypanther** [comment]
I just completed the tutorial (nice, btw) and I see this color-swapping going on in the actionbar. Perhaps related?

![actionbar_colors](https://cloud.githubusercontent.com/assets/507996/12025078/02cbba5a-ad79-11e5-9919-2d2af5e12b4e.gif)

Per the tutorial, each screen has code like the following in its .js file:

```javascript
exports.loaded = function (args) {
	var page = args.object;
	if (page.ios) {
		var navigationBar = frameModule.topmost().ios.controller.navigationBar;
		navigationBar.barTintColor = UIColor.colorWithRedGreenBlueAlpha(0.011, 0.278, 0.576, 1);
		navigationBar.titleTextAttributes = new NSDictionary([UIColor.whiteColor()], [NSForegroundColorAttributeName]);
		navigationBar.barStyle = 1;
		navigationBar.tintColor = UIColor.whiteColor();
	}
	page.bindingContext = user;
};
```

Using tns version 1.5.2 installed from npm this morning.

**Comment by tjvantoll** [comment]
Hey @skypanther,

Thanks for reporting the issue in the tutorial.  What’s going on here is that, as of NativeScript 1.5, most of the code you include above can now be done in CSS rather than iOS-specific code. I have a [PR pending](https://github.com/NativeScript/docs/pull/208) to fix this issue in the guide, but it hasn’t been merged yet because of 🌲. That iOS-specific code block is now just

```js
if (page.ios) {
    var navigationBar = frameModule.topmost().ios.controller.navigationBar;
    navigationBar.barStyle = UIBarStyle.UIBarStyleBlack;
}
```

and

```css
ActionBar {
    color: white;
    background-color: #2E6DAD;
}
```

The problem this issue describes is that once you put this code in CSS, it becomes difficult/impossible to make other iOS-specific changes to the UINavigationBar. In my case, without being able to set the UINavigationBar’s `translucent` flag, I can’t get colors in Groceries to match up, so I end up with a color mismatch that my OCD brain can’t cope with.

![23a44c22-9390-11e5-894c-73ee7cef8d30](https://cloud.githubusercontent.com/assets/544280/12036410/bc097a12-ae13-11e5-91aa-0a0fdf421790.png)

**Comment by speigg** [comment]
@tjvantoll

> Making getMeasuredHeight() return 0 makes the content under the action bar appear underneath it

Yes, that's the whole point of a translucent navigation bar: the content is rendered full screen, top to bottom. If that makes content appear where it should not, then a scrollview is generally used with adjusted content insets (which can be adjusted automatically by the uiviewconroller's native functionality). This allows the content to scroll under the translucent navigation bar (or toolbar, or whatever).

**Comment by skypanther** [comment]
@tjvantoll Thanks. My thinking was that perhaps the flash-of-grey I was seeing, and the styling issues you were seeing were due to a similar underlying ActionBar issue. Admittedly, it was a stretch. I didn't mean to derail this thread.

**Comment by sitefinitysteve** [comment]
I have this issue loading a cocoapod, the navbar on the view that pops up is just stock grey, where it should be inheriting from what was set...

**Comment by pmz** [comment]
This issue is close but I have the same problem as @tjvantoll is describing. 
How an one make a navigationBar's translucent property to false without having this weird transition?
