### ISSUE TITLE
GcmListenerService.onMessageReceived

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#1153]
Hi i wondered if GcmListenerService cannot be used in native script since it is a service? 

And how about the iOS counterpart as well? 

Thanks

**Comment by ivanbuhov** [comment]
Yes, you can use it both from Andorid and iOS.
All you need to do is to create a plugin and include the [Google Cloud Messaging for Android Library](http://stackoverflow.com/a/12265851/3968054) in its `{plugin-path}/platforms/android/` and follow [these steps](https://developers.google.com/cloud-messaging/android/client). Bare in mind that GCM requres editing `AndroidManifest.xml` file which is a supported scenario by [NativeScript plugins](https://docs.nativescript.org/plugins). 
For iOS you can use Google Cloud Messaging for iOS. To include the library just add a `Podfile` with the following content:
```
pod 'Google/CloudMessaging'
```
in your `{plugin-path}/platforms/ios/` folder and follow [the instructions](https://developers.google.com/cloud-messaging/ios/client).

**Comment by x4080** [comment]
Oh wow. Thanks for the quick and precise answer
