### ISSUE TITLE
alert with null value is not displayed

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#1168]
var myObj = bull;
alert(myObj);///does nothing

It should display message with empty content or "null".

**Comment by jasssonpet** [comment]
Also, if you do `alert(this.counter)` in our "Hello World" template the app crashes:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UIAlertController must have a title, a message or an action to display'
```
