### ISSUE TITLE
SegmentedBarItem doesn't support iconfont codes like &#xf179;

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#1176]
This works 
SegmentedBarItem title="" class="icomoon" 
...but not 
SegmentedBarItem title="&#xf26e;" class="fontawesome" 
while
Label ios:text="&#xf26e" class="fontawesome" (sorry not sure how to get the code in there with the semicolon and have it not covert to the square :)
works

**Comment by amjd** [comment]
Not sure about the solution to your problem, but you can embed code in GitHub using backticks (`).
- For inline code, wrap the code in single backticks (`).
- For a block of code, wrap the code in triple backticks (```).

**Comment by enchev** [comment]
I've just tested this with our latest released and here is the result:
```XML
<Page>
  <StackLayout>
    <SegmentedBar selectedIndex="1" style="background-color: red; color: white;font-family: FontAwesome;" selectedBackgroundColor="green">
      <SegmentedBar.items>
        <SegmentedBarItem title="Item 1 &#xf179;" />
        <SegmentedBarItem title="Item 2 &#xf179;" />
        <SegmentedBarItem title="Item 3 &#xf179;" />
      </SegmentedBar.items>
    </SegmentedBar>
  </StackLayout>
</Page>
```

![android](https://cloud.githubusercontent.com/assets/5804953/11467042/3e029d78-974e-11e5-9be4-3e88ec96db30.png)
![ios](https://cloud.githubusercontent.com/assets/5804953/11467043/3e1d8796-974e-11e5-9014-5fc004096ca9.png)

**Comment by sitefinitysteve** [comment]
Ah, okay I was setting the style on the ActionBarITEM...not the parent.

Any chance this could be added to the how-to docs for the AB?

Very festive btw :)

**Comment by sitefinitysteve** [comment]
This borked?  In a hello world I see the icons on iOS, but nothing on Android (with your code).  In 2 seperate apps...

![image](https://cloud.githubusercontent.com/assets/1542376/11960308/1a584298-a8a0-11e5-8264-1e0133c9f209.png)

**Comment by sitefinitysteve** [comment]
Sample to save time: https://www.dropbox.com/s/5947m4pl8866mbx/hello-world-2.zip?dl=0

**Comment by sitefinitysteve** [comment]
Nope, keep it closed!

Problem was the ttf is "fontawesome"  but the family is (was) "FontAwesome".  Works like that on iOS, not the droid though.
