### ISSUE TITLE
Alert Dialog in SegmentedBar selectedIndexChanged event blocks navigation

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#1177]
- Create a start page with a button which navs to a child page
- On the child page put a segmented bar, with the selectedIndexChanged event, and in the event handler put a dialog alert

What happens is that when you click the button you see the dialog BEFORE the nav, when you click okay, you dont navigate at all.

Honestly it's annoying for this event to fire on view load...SO annoying.

**Comment by amjd** [comment]
I experienced something similar with the dropdown plugin. The change event fires every time the page is loaded, even if the dropdown value remains unchanged.

**Comment by sitefinitysteve** [comment]
I would rather see a loaded event and change event, change only fires on actual change and we don't have to worry about an undefined oldValue. 

... But blocking navigation needs fixing :)

**Comment by firescript** [comment]
Also blocks the UI in  "navigatingFrom" event on Page... simple alert prevents regular operation

**Comment by hamorphis** [comment]
@sitefinitysteve Can you please prepare a very small dummy sample project that reproduces the behavior and attach it here. I will take a look at what is going on. Thank you in advance.

**Comment by sitefinitysteve** [comment]
@hamorphis  "a very small dummy sample" ;) touche...

Sure here you go... based on blank hello world lots of wierdness
https://www.dropbox.com/s/z3jb2ousfcadzw0/blank-project.zip?dl=0

**Comment by hamorphis** [comment]
Thanks. I will look into it.

**Comment by hamorphis** [comment]
When you simply call alert("message"); the code on the following lines is executed immediately. The alert dialog returns a Promise. You should wait for this Promise to be fulfilled (i.e. the user clicked ok) and perform the navigation in the fulfilled callback. 

```
        alert("YOU SHALL NOT PASS").then(function(){
            viewModel.message = "Clicked, notice the header\actionbar appears too... and now the Navigate button does nothing as well";
            frameModule.topmost().navigate("child-page");
        });
```
