### ISSUE TITLE
Quick Question: custom view's property translate to a function callback 

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#1178]
Hi,

If I set a property observable of my custom view for example callback property, I get the value changes in
oncallbackPropertyChange using proxy.PropertyMetadata etc

And the value is a string, how do I convert the value to a real function call, for example like the nativescript view's "tap" property ? Looking for it on the source code and cannot find anything for it

Thanks

**Comment by enchev** [comment]
You can check [this code](https://github.com/NativeScript/NativeScript/blob/master/ui/core/bindable.ts#L588) for more info.

**Comment by x4080** [comment]
thanks for the tip

**Comment by x4080** [comment]
Hi enchev, follow up question : I can get the function if I'm using aproperty="{{afunction}}" , but I still cannot figure it out if I just wanna using aproperty="afunction", just like in tap="afunction", how can I access the "afunction" as a function instead of a string? Or is it just for built in events?

Thanks

**Comment by enchev** [comment]
You can execute functions as well - `{{ someFunction() }}`. Please check this article for more info:
http://docs.nativescript.org/bindings#using-expressions-for-bindings

**Comment by x4080** [comment]
I did calling the function but if for example i have property tapfunction="afunction" it cannot call the exported function with afunction() while in the tap="afunction" it can. Hope you get what i meant

While if i did tapfunction="{{afunction}}" i can call it if i do the bindingContext
