### ISSUE TITLE
Listview doesn't seem to clear\reset

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#1179]
Duplicate: #1235 

Okay so I have a listview, and in the changed event of the segbar I reload based on the selection... in the case of "Book" (see video) zero results are returned... but I can't seem to get that reflected in the listview.

I'm setting the observable arrays length back to 0 before I loop through the data with a forEach.

viewModel.resourceItems.length = 0;

http.getJSON(url).then(function (data) {
        data.Resources.forEach(function(item){
            viewModel.resourceItems.push(item);
        });
        
        pageSize++;
    }, function (e) {
        //ERROR
        console.log(e);
    });

http://www.screencast.com/t/Uz6P5SPZWvqN

**Comment by sitefinitysteve** [comment]
It gets weirder! :)
http://www.screencast.com/t/4tJ4i5y1xCUJ

**Comment by hshristov** [comment]
@sitefinitysteve Which version do you use?

**Comment by sitefinitysteve** [comment]
Atm I'm using the stock listview, just havent had time to move to TelerikUI yet... plan to, just no time atm.

**Comment by GitCharm** [comment]
I'm not sure if this is related, i've posted this issue on the Nativescript CLI github - Issue 1276:  https://github.com/NativeScript/nativescript-cli/issues/1276

Basically - when loading up a list (both my app and the Friends sample app), the database is being called 3 times, and the list has triple the records.  Is this happening for you @sitefinitysteve .  I've upgraded to {N}1.5.

Cheers
Janine

**Comment by hshristov** [comment]
@sitefinitysteve Could you please attach a project or snippet which reproduce this issue?

**Comment by sitefinitysteve** [comment]
...same project as the other issue
https://www.dropbox.com/s/ycsfxn1ezqadp5x/OutbreakHelp.zip?dl=0

Open the resources view and add a new "type" of "Books" as seen in the video.  I have it removed right now because there's no results, no point in showing it and this issue.

**Comment by hamorphis** [comment]
I will take a look...

**Comment by hamorphis** [comment]
I have found the problem and I am currently fixing it. Here is the issue that describes it: https://github.com/NativeScript/NativeScript/issues/1235

**Comment by hamorphis** [comment]
This pull request resolves the issue: https://github.com/NativeScript/NativeScript/pull/1236

**Comment by hamorphis** [comment]
Can you close this issue once you verify that setting length to zero works as expected.

**Comment by sitefinitysteve** [comment]
Sorry this all happened while i was asleep, thx for the fix!
