### ISSUE TITLE
iOS actionBarHidden="true" hides the actionbar AFTER the view is visible

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#1180]
...you see the actionbar in the view, then it animates itself out, looks really strange

http://www.screencast.com/t/T8THNfIdqrR4

**Comment by vakrilov** [comment]
@sitefinitysteve 
I was unable to reproduce the issue. Navigating to a page that has `actionBarHidden="true"` set in the XML does not show the nav-bar at all.
Can you please share more info about how are you setting the property. 

One thing that comes to my mind is that if you are binding the property and you set the `bindingContext` after the page is shown this may be that cause of the glitch.

**Comment by sitefinitysteve** [comment]
Just setting it in the XML

(Emulator)
https://jsbin.com/nukixe/edit?output


<Page xmlns="http://www.nativescript.org/tns.xsd" xmlns:widgets="widgets" loaded="pageLoaded" class="city-image" actionBarHidden="true">
 
    <ScrollView>
        <GridLayout rows="auto, *">
            <StackLayout class="padded-label-stack">
                <widgets:logo  />
            </StackLayout>
            <StackLayout row="1" class="buttonRow">
                <Button tap="onBlockLoad" text="{{ MenuKB }}" class="btn btn-primary" />
                <Button tap="onLoadResources" text="{{ MenuResources }}" class="btn btn-primary" />
                <Button tap="onLoadWebinars" text="{{ MenuWebinars }}" class="btn btn-primary" />
                <Button tap="onLoadNewsletters" text="{{ NewsletterTitle }}" class="btn btn-primary" />
                <Label tap="onChangeLanguage" text="{{ otherLanguage }}" class="languageButton" />
            </StackLayout>
        </GridLayout>
    </ScrollView> 
</Page>

exports.pageLoaded = function (args) {
    if (frame.topmost().ios) {
        frame.topmost().ios.navBarVisibility = "never";
    }
     
    var page = args.object;
     
    page.bindingContext = viewModel;
} 

So this page gets loaded after the splash screen which is just this

<Page xmlns="http://www.nativescript.org/tns.xsd" xmlns:widgets="widgets" loaded="pageLoaded" class="splash" actionBarHidden="true">
        <StackLayout id="logoPlaceHolder">
        </StackLayout>
</Page>



...incidentally as you can see in the app though, the image doesn't display on iOS, besides the point though.

**Comment by hshristov** [comment]
@sitefinitysteve Please use `actionBarHidden="true"` on the Page instance instead of navBarVisible.
The way you are doing it - in pageLoaded is too late. Page layout is already completed so animation starts with ActionBar visible.

**Comment by sitefinitysteve** [comment]
Sorry, I forgot the code markdown in the post... I just added the navBarVisibility there as a last resort because actionBarHidden alone didn't seem to work.

**Comment by hshristov** [comment]
@sitefinitysteve Could you send a project which reproduce this issue?

**Comment by sitefinitysteve** [comment]
https://www.dropbox.com/s/ycsfxn1ezqadp5x/OutbreakHelp.zip?dl=0

**Comment by hamorphis** [comment]
I will take a look...

**Comment by sitefinitysteve** [comment]
You know whats also wierd there on iOS...the splashscreen which loads first doesn't show on iOS where it's fine on android...no idea why it's just an image on a page, nothing else really.

**Comment by hamorphis** [comment]
Your spashscreen is not showing on iOS because there is no file called `splashscreen` inside the `App_Resources/iOS` folder.

**Comment by hamorphis** [comment]
I am currently investigating the issue with the navigation bar showing on the splash screen.

**Comment by hamorphis** [comment]
I spent several hours debugging your project. In the `pageLoaded` event handler of the splashscreen page, you call `helpers.platformInit` you set the navBarVisibility to `always`. The reason for this is beyond me.

Please, check the code you have written twice before opening a new issue.

**Comment by sitefinitysteve** [comment]
Okay I appreciate you digging into it.  The project was based (started) on a sample from somewhere or someone long ago I'm guessing back before the iOS actionbar was easily styleable\configurable is my guess.  I never added that myself...
