### ISSUE TITLE
Comparison operators in XML don't work

### ISSUE THREAD

**Issue by AllenMeex** [NativeScript/NativeScript#1181]
I want to set a Label's color automatically base on its value.like below:

The type of "score" is string. 

If I do it like this:

`<Label  text="{{ score }}" color="{{ scores&gt;0 ? '#FFFF0000' : '#FF00FF00' }}"  verticalAlignment="center" marginLeft="15" />
`
the text can not be shown.

like this:
`<Label  text="{{ score }}" color="{{ score>0 ? '#FFFF0000' : '#FF00FF00' }}"  verticalAlignment="center" marginLeft="15" />
`
App crashed: file:///app/tns_modules/ui/builder/builder.js:135:57: JS ERROR Error: XML parse error: close tagname

like this:
`<Label  text="{{ score }}" color="{{ +score&gt;0 ? '#FFFF0000' : '#FF00FF00' }}"  verticalAlignment="center" marginLeft="15" />
`
the text can not be shown.

this:
`
<Label  text="{{ score }}" color="{{ true ? '#FFFF0000' : '#FF00FF00' }}"  verticalAlignment="center" marginLeft="15" />
`
I can get a text with Red color.

How can I use the comparison operators in xml? Thx.

**Comment by enchev** [comment]
Hey @AllenMeex,

Such symbols are not allowed in XML - you can use &lt; and &gt; instead.

Thanks

**Comment by AllenMeex** [comment]
But if I use &gt; ,it still don't work,like this:

`color="{{ score &gt; 0 ? '#FFFF0000' : '#FF00FF00' }}"`

when score="1234", the text don't be shown.
if I need to convert the type of score from string to number, I should use it like this? "+score"
But 
`color="{{ +score&gt;0 ? '#FFFF0000' : '#FF00FF00' }}" `
still don't work

**Comment by vchimev** [comment]
Hi @AllenMeex,

I gave a try to your scenario with {N} 1.5.0 and it worked as expected. Here is my sample app: https://github.com/vchimev/gt-hello.

**Comment by AllenMeex** [comment]
Thanks @vchimev 

It's my mistake, It worked. :)
