### ISSUE TITLE
Karma + Babel won't run tests

### ISSUE THREAD

**Issue by stevetayloruk** [NativeScript/NativeScript#1182]
When using Babel/ES6 and unit tests (mocha or jasmine - tried both) I'm getting an error when the tests run.  The error i think is down to the the babel after-prepare as disabling this gets rid of the error but then the app doesn't run. I'm using "tns test ios --emulator" command.

The error I'm getting is: 

```
30 11 2015 11:46:42.230:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
30 11 2015 11:46:42.236:INFO [launcher]: Starting browser NativeScript Unit Test Runner
Successfully prepared plugin nativescript-unit-test-runner for ios.
Project successfully prepared
Executing after-prepare hook from /Users/stevetaylor/Projects/raise/raise-app/raise/hooks/after-prepare/nativescript-dev-babel.js
Cannot read property 'appDestinationDirectoryPath' of undefined
# test ios
```

and the tests do not run.

Any ideas?

Thanks

Steve

**Comment by N3ll** [comment]
This issue was moved to NativeScript/nativescript-cli#1286
