### ISSUE TITLE
onReceivedSslError is not exposed via the WebViewClientClass

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#1196]
On Android (not sure about iOS) You are missing the following class function.
```
WebViewClientClass.prototype.onReceivedSslError = function(webView, handler, error) {
       // Code should call a user callback obviously; and if that callback returns true you proceed
       // otherwise  you do cancel (the default)
      //  handler.cancel() or  handler.proceed();
};
```
And since WebViewClientClass is NOT exposed via an export; you can't monkey patch it in; leaving the worst possible choice of having to manually modify a runtime class.   :angry:

**Comment by N3ll** [comment]
This issue was moved to NativeScript/android-runtime#292

**Comment by NathanaelA** [comment]
@N3ll can you please re-open this one; this is the proper location for the bug.  This is NOT an android-runtime issue; this is a common-core issue.    The Common core ui/web-view/web-view.android.js is the location....

**Comment by N3ll** [comment]
@NathanaelA - sorry about that :) We will look into the problem.

**Comment by NathanaelA** [comment]
@N3ll not a problem.

**Comment by enchev** [comment]
Hey @NathanaelA,

Since we don't have similar event for iOS we will unable to expose cross-platform event. Maybe the best way in this case is to export the [WebViewClientClass](https://github.com/NativeScript/NativeScript/blob/master/ui/web-view/web-view.android.ts#L7)?

**Comment by NathanaelA** [comment]
I don't have any issues with that; monkey patching the class was my original intent until I discovered it couldn't be.  LOL.  

 Just as a thought; how hard would it be to find out how many of these "classes" their are and export them all.  I bet their are many other cases just like mine where you are extending an android class but only implementing a portion of it.   With giving us the developer the ability to extend it farther since it isn't being exported.

**Comment by enchev** [comment]
I've just made pull request - let me know if this will help you in your case. As for the other possible not exported classes we will review them and export if really needed.

**Comment by NathanaelA** [comment]
@enchev - Thanks for the fix.   As for the other reviewing the other classes; do you need a issue opened to start working through them.  Odds are pretty good that a large number of them are missing possible useful callbacks because Android is big on features and control.

**Comment by surdu** [comment]
This functionality seems not to be valid anymore as the [WebViewClientImpl](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/web-view/web-view.android.ts#L16) is not exported anymore.

Any idea how/if this can be achieved anymore ?
