### ISSUE TITLE
Correct image usage

### ISSUE THREAD

**Issue by edimoldovan** [NativeScript/NativeScript#120]
Hi,

I am trying to get an image locally into the app. like this:
`<Image stretch="fill" cssClass="logo" src=“logo.png" width="110" height="110”/>`
My problem is that I don’t know how to provide the url. There was a res folder used in a previous release, but images from that are not loaded anymore.

Thanks,
Eduárd

**Comment by edimoldovan** [comment]
Some extra information: if I use `res://Default.png` for the image src, it loads ok. If I put my own image there, it doesn’t work anymore.
Urls also work.

I have the same issue with iconSource for TabViewItem -- I don’t know how the correct url should be provided.

**Comment by alexziskind1** [comment]
I had the same problem.
When specifying the image src use ~/ before the path and file name UNDER the main app folder.
For example, if your image is in projectname/app/image.png 
use
<Image  src="~/image.png"  />

If your image is in a subfolder called "res", for example, like this: projectname/app/res/image.png
use
<Image  src="~/res/image.png"  />

**Comment by edimoldovan** [comment]
Very helpful, thx. Will try it tomorrow.
