### ISSUE TITLE
question: reload app programmatically like livesync?

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#1204]
is there an api or function to reload like livesync when .js is changed ? useful for development

**Comment by enchev** [comment]
You can call [reloadPage()](https://github.com/NativeScript/NativeScript/blob/master/ui/frame/frame-common.ts#L31) method of the Frame.

**Comment by x4080** [comment]
Thanks for the tip

**Comment by NathanaelA** [comment]
@x4080 just a word of warning, this function actually has the negative side effect of totally clearing your page history; so if you navigate from your main screen to a sub-screen and then run this function on the sub-screen, you will not be able to go back to the main screen using the back button...

**Comment by x4080** [comment]
Thanks for the tip

**Comment by x4080** [comment]
I tried it and its not cold boot the app like in livesync js changes, any other solution? 

Thanks

**Comment by NathanaelA** [comment]
Do you mean as in actually reload a new verison of the JavaScript?     If so then no, their is no built in way; my LiveEdit uses a special patch to do its magic, and Telerik takes the easy way currently and just reboots the app on any JS changes.

**Comment by x4080** [comment]
I think for restarting application, yes when i use your livesync it works nice, but i needed for ios too, oh well. but thanks anyway Nathan you are good help. and your new livesync is cool, ios version available too?

**Comment by NathanaelA** [comment]
Well, my LiveEdit stuff is just for Development; it uses undocumented calls into the V8 engine to do things that MIGHT crash your application.  (Odds are very low of a crash, but I need to stress this technique is NOT designed for running on a customers device).    Now if you need to just restart the whole app on Android; that is easy.    

As to iOS; nope -- I have not spent any time duplicating the functionality on iOS.  First reason was I haven't had the iOS code installed on my box; however I am in the process of downloading it now that I have fully update my machine to el capitan.

However, depending on what exactly you are trying to do their maybe a totally different way to do it with it being safe for your customers, on both iOS and Android.

**Comment by x4080** [comment]
Yes im only using the reload for development purposes

**Comment by NathanaelA** [comment]
If this is only for Dev purposes; why not just use my free liveedit plugin...

**Comment by x4080** [comment]
I will and thanks
