### ISSUE TITLE
iOS font issue with specific font

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#1208]
Ok, Valio has a blog post: that links to the font at http://zavoloklom.github.io/material-design-iconic-font/cheatsheet.html -- Several people were trying to get it to work on the forums on iOS and failing so I took a look into it.

 if you download the v2.2.0 (i.e. current version) of the font and attempt to use the ttf in iOS it fails to run on the iOS simulator under El Capitan (and latest XCode).  I haven't pulled a real device to see if it works or fails their also. 

It fails to resolve the font using the fontWithDescriptorSize, even though everything shows the font is installed and so it returns the helvetica font which of course gives you a nice broken unicode square.

Things I tried that WORKED:
1. By using UIFont.fontWithNameSize instead of UIFont.fontWithDescriptorSize; this works and resolved properly.  (Around line 27)
2. By eliminating the NSFontFaceAttribute in the descriptor on this font, in the case the font is just "Regular" don't add this key to the descriptor array. (Around Line 89)

Either one of those fixes it, but I'm not sure the ramifications of eliminating sending "Regular" on the rest of the fonts.   One possible deployable fix would be to add a check at line 28 and see if the font-family matches in the font that is returned; and if not then do a **this._uiFont = UIFont.fontWithNameSize(this.fontFamily, size);**

**Comment by x4080** [comment]
I too can confirn that using real device is a no go and using ios font change manually works.
