### ISSUE TITLE
Android build error: NativeScriptToolbarStyleBase not found

### ISSUE THREAD

**Issue by amjd** [NativeScript/NativeScript#1209]
In any new NativeScript project, I get this error while building:

```
REDACTED/platforms/android/src/main/res/values-v21/styles.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'NativeScriptToolbarStyleBase'.
```

This snippet of code in `platforms/android/src/main/res/values-v21/styles.xml` seems to be the culprit, after removing/commenting it the build goes through:
```xml
    <style name="NativeScriptToolbarStyle" parent="NativeScriptToolbarStyleBase">
        <item name="android:elevation">4dp</item>
    </style>
```

Is this a bug?
Also, is it safe to directly modify any file under platforms folder? What's the recommended way to do it (e.g. add permissions to AndroidManifest file)?

**Comment by N3ll** [comment]
@amjd - can you specify the version of NativeScript that you are using? And do you get this error when you create a new project and build it right after it has been created or you have a custom code written?
