### ISSUE TITLE
Conditionally displaying elements

### ISSUE THREAD

**Issue by RangerMauve** [NativeScript/NativeScript#121]
Is there a way to conditionally display or remove an element in a view?

**Comment by enchev** [comment]
You can hide/show conditionally elements [like this] (https://github.com/NativeScript/sample-TelerikNEXT/blob/master/app/main-page.xml#L70)

**Comment by RangerMauve** [comment]
The elements will still be in memory if they aren't visible, right?

**Comment by enchev** [comment]
Hey @RangerMauve,

Do you still need assistance with this? 

Maybe we can continue this thread in our google groups:
https://groups.google.com/forum/#!forum/nativescript

Thanks

**Comment by RangerMauve** [comment]
No, I think I'm good for now. I haven't gotten around to playing with this too much yet. But I'd still be interested to know about the implications on memory if something is marked as not visible.
