### ISSUE TITLE
greater than conditions not working in databinding

### ISSUE THREAD

**Issue by stevetayloruk** [NativeScript/NativeScript#1210]
Hi,

this works: 
```
<Label text="hello world" cssClass="right" visibility="{{ count === 1 ? 'visible' : 'collapsed' }}"/>
```
when the count is 1 but this doesn't compile on ios emulator: 

```
<Label text="hello world" cssClass="right" visibility="{{ count > 0 ? 'visible' : 'collapsed' }}"/>
```
thanks

Steve

**Comment by NathanaelA** [comment]
The Symbol < and > are not allowed inside XML.    You have to use &amp;lt; and &amp;gt;

**Comment by stevetayloruk** [comment]
Ha! Of course. Makes sense as I guess the XML is parsed at compile time and the JavaScript bindings at runtime.

thanks

**Comment by NathanaelA** [comment]
If it makes you feel any better; I've been doing this for months and I STILL want to but the < > inside the xml.   Then I hit my head when I realize why it is broken.   LOL
