### ISSUE TITLE
Create lower-case-dashed XSD definition

### ISSUE THREAD

**Issue by dokkis** [NativeScript/NativeScript#1212]
As documented here https://docs.nativescript.org/ui-with-xml it is possible using the Lower-case-dashed Component Declaration.

There should be another XSD definition for the components with this naming convention :)

I just discovered this project last week, I studied the documentation and saw a lot of videos and I think that is really good.

Thanks for your really good work ;)
For sure I'll try to experiment Nativescript in the next days.

Bye,
Antonio

**Comment by enchev** [comment]
Hey @dokkis,

It is already [part of our master](https://github.com/NativeScript/xsd-generator/commit/a24dbe5765180a747748028e4496ef6f83563931) and it will be released with our 1.5.1 release next week.
