### ISSUE TITLE
Populating list view calls Object.defineProperty 3 times {N} 1.5

### ISSUE THREAD

**Issue by ligaz** [NativeScript/NativeScript#1216]
_From @GitCharm on November 30, 2015 3:4_

I have this problem in my own project, and have also replicated in the Friends apps when populating the initial activies list.  

I have added an alert dialogue which displays 3 times when loading the activities in the Friends app:

```
 Object.defineProperty(ActivitiesViewModel.prototype, "activities", {
        get: function () {
            this.isLoading = true;
            var that = this;

            var expandExp = {
               "UserId":{
                  "ReturnAs":"User",
                  "TargetTypeName":"Users",
                  "Expand":{
                     "Picture":{
                        "TargetTypeName":"System.Files"
                     }
                  }
               },
               "Picture":{
                  "ReturnAs":"Picture",
                  "SingleField":"Uri",
                  "TargetTypeName":"System.Files"
               }
            };

            var data = EVERLIVE.data('Activities');
            var query = new Everlive.Query();
            query.orderDesc('CreatedAt');
            
            data.expand(expandExp).get(query)
            .then(function(data) {
                for(var i = 0; i < data.result.length; i++){
                    data.result[i].dateConverter = dateConverter;
                    var activityItem = new activityItemViewModel.ActivityItemViewModel(data.result[i]);

                    data.result[i] = activityItem;
                }

               alert('There are ' + data.result.length.toString() + ' activities: ' + JSON.stringify(data.result));
                that._activities.push(data.result); 

                that.isLoading = false;
            }, function(error) {
                that.isLoading = false;
                alert("Activities can't be retrieved");
            });      

            return this._activities;        
        },
            enumerable: true,
            configurable: true
    });
```

NOTE:  I have replicated this in CLI, Appbuilder CLI and also Windows Appbuilder.

_Copied from original issue: NativeScript/nativescript-cli#1276_

**Comment by ligaz** [comment]
_From @GitCharm on December 2, 2015 1:37_

Additionally - this means 3 calls to the backend database service, and also the number of records displayed is tripled.

**Comment by vakrilov** [comment]
@GitCharm
I would suggest that you implement an additional logic in your application that will prevent it form connecting to everlive every time the getter of the property is called.

One other thing that you can do (if you are not doing it already) is to use the [Observable](https://docs.nativescript.org/ApiReference/data/observable/HOW-TO.html) class. This way you can notify the binding when your data (activities) is loaded. You can also check out the (data binding article in the docs)[https://docs.nativescript.org/bindings] for more info on bindings and how they work.

**Comment by JanineGarrett** [comment]
Hi - thanks for your comments vakrilov - I have been using the Observable class, and have now wrapped the database calls in a check for IsLoading - which is working nicely :)

Cheers. J
