### ISSUE TITLE
AbsoluteLayout / popup and Tabview Control

### ISSUE THREAD

**Issue by stevetayloruk** [NativeScript/NativeScript#1222]
I'm trying to get a simple popup working with a TabView on the same view.  The behaviour is to click on the ActionBar to then select an option from a little context menu (a bit like a right click on windows or a tooltip - but a selection via a listview).

Initially, i tried a GridView Layout which worked to a degree but the popup menu would push the content of the tabview item down the screen - which i dont want. I want the popup to sit over the top of any other content (think zindex).

So i then tried AbsoluteLayout which allowed me to have the popup sit over the top of the content and not push it down. But now the TabView control isn't fixed to the bottom.  I've tried a number of combinations of different layouts such as stack, dock etc. but the combinations seem to break on at least one of the above.

Code:

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="pageInit" >
    <Page.actionBar>
        <ActionBar title="Feed">
            <ActionBar.titleView>
                <StackLayout orientation="vertical">
                    <StackLayout orientation="horizontal">
                        <Label text="Feed" />
                        <Label text="&#xf107;" cssClass="icon" tap="{{ toggleFeedStatusListView }}"/>
                    </StackLayout>
                    <Label text="{{ feedStatus }}" cssClass="tiny" id="feedStatusLabel" />
                </StackLayout>
            </ActionBar.titleView>
        </ActionBar>
    </Page.actionBar>

    <AbsoluteLayout>
        <StackLayout visibility="{{ feedStatusListViewVisible ? 'visible' : 'collapse' }}" left="160" top="160">
            <Label text="&#xf0de;" cssClass="icon" style="background-color: transparent; color: #fff; border-color: #fff; horizontal-align:center;"  />
            <StackLayout width="200" orientation="vertical" style="background-color: #fff; margin-top: -11;">
                <ListView items="{{ feedStatuses }}" rowHeight="20" height="40" itemTap="{{ changeFeedStatus }}">
                    <ListView.itemTemplate>
                        <Label text="{{ name }}" style=" horizontal-align:center; color:#171717; font-size: 10;"  />
                    </ListView.itemTemplate>
                </ListView>
            </StackLayout>
        </StackLayout>
    </AbsoluteLayout>

    <TabView id="tabView1">
        <TabView.items>
            <TabViewItem title="tab1">
                <TabViewItem.view>
                    <ScrollView>
                        <Label text="This is Label in Tab 1" />
                    </ScrollView>
                </TabViewItem.view>
            </TabViewItem>
            <TabViewItem title="tab2">
                <TabViewItem.view>
                    <Label text="This is Label in Tab 2" />
                </TabViewItem.view>
            </TabViewItem>
            <TabViewItem title="tab3">
                <TabViewItem.view>
                    <Label text="This is Label in Tab 3" />
                </TabViewItem.view>
            </TabViewItem>
            <TabViewItem title="tab4">
                <TabViewItem.view>
                    <Label text="This is Label in Tab 4" />
                </TabViewItem.view>
            </TabViewItem>
            <TabViewItem title="...">
                <TabViewItem.view>
                    <Label text="This is Label in Tab 5" />
                </TabViewItem.view>
            </TabViewItem>
        </TabView.items>
    </TabView>
</Page>
```

Many Thanks

Steve

**Comment by jlooper** [comment]
@stevetayloruk For popups, I ended up using a cocoapod and the NativeScript toast plugin. Could this be a strategy that might work for you?

https://github.com/jlooper/thisorthat-app (fancyAlert is the cocoapod integration)

**Comment by stevetayloruk** [comment]
Thanks Jen, I'll have a look - do it allow for listviews to be embedded?

I did look into the dialogs and page modal but they seemed too limited.

thanks

**Comment by jlooper** [comment]
Perhaps something like this for iOS https://cocoapods.org/pods/LGSemiModalNavController

I'm not sure about Android. Anyone? I think Toast won't work for you for big data-heavy modals. Perhaps @enchev could weigh in on the extensibility options for this plugin: http://plugins.telerik.com/nativescript/plugin/custom-ui-dialog

**Comment by stevetayloruk** [comment]
It's not data heavy only 2-4 items. Originally I used labels instead of list view but list view offers a bit more around selection. 

Thanks

**Comment by vakrilov** [comment]
@stevetayloruk 
It looks you are on almost there. A few tips:
*  `Page` should have only one content element.
*  You can use `GridLayout` as a container. If there are no rows and columns defined all views in the grid will be rendered on top each other - which is what you want
* For positioning - you can still use `AbsoluteLayout`

Here is how your page may look like:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="pageLoaded">
    <!-- ActionBar definition-->
    <GridLayout> 
        <TabView id="tabView1" horizontalAlignment="stretch">
            <!-- TabView definition goes here--> 
        </TabView>
    
        <AbsoluteLayout visibility="{{ popupVisible ? 'visible' : 'collapse' }}">
            <StackLayout left="160" top="160">
                <!-- Popup content ...--> 
            </StackLayout>
        </AbsoluteLayout>
    </GridLayout>
</Page>
```
I hope that is useful.

**Comment by stevetayloruk** [comment]
Perfect thanks! Works like a charm.

I had tried that but i defined the rows on the GridLayout which messed everything up.

**Comment by stevetayloruk** [comment]
Noticed a small issue with this. I cannot click on the tab items when the popup is visible. I first need to close the popup to be able to click and switch between the tabs.

**Comment by N3ll** [comment]
@stevetayloruk - the behavior that you are describing is expected. In the code, the AbsoluteLayout will appear on top of the TabView and will block the access to it.

**Comment by stevetayloruk** [comment]
@N3ll if you add a height and width to the absolutelayout then it allows you to tap on the tabview. But by adding these properties the layout position is messed up.

**Comment by stevetayloruk** [comment]
I've managed to get my desired result with a bit of messing around. I added a few properties to the absolutelayout.

```
<AbsoluteLayout verticalAlignment="top" horizontalAlignment="center" width="200" height="40">
```

**Comment by avmax** [comment]
@vakrilov Hello! I've tried almost same thing with putting AbsoluteLayout next to TabView. But I got a funny problem. While on iOS it worked as expected - in android I got stuck. Some how I got the following: it looks like that my absolute layout stays above the tabview but under the tabview content. Tabview content is just a StackLayout. Here is the image. 
![image](https://user-images.githubusercontent.com/16198161/27094249-25a2320a-5072-11e7-9d5d-58f85f406539.png)  Help please, what could go wrong ?

**Comment by avmax** [comment]
@vakrilov and I tried exactly what You've suggested - I got the same problem. In iOS my AbsoluteLayout is above TabView, but in Android my AbsoluteLayout is under TabView :(
