### ISSUE TITLE
Out of memory, Bitmap images on Android

### ISSUE THREAD

**Issue by duongnhatduy** [NativeScript/NativeScript#123]
Hi,

I'm trying to make something similar to sample-cuteness, loading a listview of images and save it by using image-cache. It works fine on iOS but crashes on android. 

I/dalvikvm-heap( 3757): Forcing collection of SoftReferences for 4506492-byte allocation
I/dalvikvm-heap( 3757): Clamp target GC heap from 33.083MB to 32.000MB
D/dalvikvm( 3757): GC_BEFORE_OOM freed 71K, 3% free 31709K/32680K, paused 6ms, total 6ms
E/dalvikvm-heap( 3757): Out of memory on a 4506492-byte allocation.
I/dalvikvm( 3757): "AsyncTask #2" prio=5 tid=13 RUNNABLE
I/dalvikvm( 3757):   | group="main" sCount=0 dsCount=0 obj=0xb323b7c0 self=0xb8540bc0
I/dalvikvm( 3757):   | sysTid=3775 nice=10 sched=3/0 cgrp=[fopen-error:2] handle=-1202450384
I/dalvikvm( 3757):   | state=R schedstat=( 0 0 0 ) utm=20 stm=20 core=0
I/dalvikvm( 3757):   at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
I/dalvikvm( 3757):   at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:500)
I/dalvikvm( 3757):   at com.tns.Async$Http$RequestResult.readResponseStream(Async.java:185)
I/dalvikvm( 3757):   at com.tns.Async$Http$HttpRequestTask.doInBackground(Async.java:264)
I/dalvikvm( 3757):   at com.tns.Async$Http$HttpRequestTask.doInBackground(Async.java:214)
I/dalvikvm( 3757):   at android.os.AsyncTask$2.call(AsyncTask.java:288)
I/dalvikvm( 3757):   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
I/dalvikvm( 3757):   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
I/dalvikvm( 3757):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
I/dalvikvm( 3757):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
I/dalvikvm( 3757):   at java.lang.Thread.run(Thread.java:841)
I/dalvikvm( 3757): 
D/skia    ( 3757): --- decoder->decode returned false

Thanks

**Comment by truongsinh** [comment]
+1

I'm reading this article btw http://developer.android.com/training/displaying-bitmaps/index.html

**Comment by enchev** [comment]
Hey folks, 

We rewrote our image-cache module for the latest release to avoid such problems. Are you using our official v1?

**Comment by duongnhatduy** [comment]
Yes, I'm using the official v1

**Comment by truongsinh** [comment]
@duongnhatduy it would help if you can post the commit of the submodule `tns_modules` you are using.

**Comment by duongnhatduy** [comment]
commit 2dd2bc0, tag v1.0.0

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#77
