### ISSUE TITLE
About Custom Component Like <mg-button></mg-button>

### ISSUE THREAD

**Issue by niluanxy** [NativeScript/NativeScript#1233]
Hi, thank you share this project!And now i have a question about how to create custom component.
For example,i want to create a button like component,and use it like
```JavaScript
<mg-button>Button Text</mg-button>
```
Or like create a slider like
```JavaScript
<mg-slider>
    <slider-item><img src="1.jpg"/></slider-item>
    <slider-item><img src="2.jpg"/></slider-item>
    <slider-item><img src="3.jpg"/></slider-item>
</mg-slider>
```
Anyone can show me a demo?

**Comment by enchev** [comment]
You can find more info here:
http://docs.nativescript.org/ui-with-xml#custom-components
