### ISSUE TITLE
What ide can I use in mac

### ISSUE THREAD

**Issue by lipangit** [NativeScript/NativeScript#1239]
I see many samples use visual studio and typescript, It must in windows.  
Can I use it in mac?

**Comment by jlooper** [comment]
Absolutely, many of us use a Mac with Sublime Text or Visual Studio Code.

**Comment by valentinstoychev** [comment]
@lipangit We will make a more tight integration with VS Code in the next month so I would recommend to use VS Code as a Mac and Windows client.
