### ISSUE TITLE
White text and icons on statusBar with hidden navigationBar

### ISSUE THREAD

**Issue by oscar-78** [NativeScript/NativeScript#1244]
When hiding the navigationBar and using a dark background I'm unable to get the text and icons of the statusBar in white color. What I'm trying:

```
var iosFrame = frameModule.topmost().ios;

if (iosFrame) {
    iosFrame.navBarVisibility = "never";

    var controller = iosFrame.controller;
    controller.view.window.backgroundColor = UIColor.colorwithRefGreenBlueAlpha(0.13, 0.16, 0.20, 1);
    controller.barStyle = 1;
}
```

**Comment by N3ll** [comment]
@oscar-78 - You will follow two steps to get white fonts on the dark background. You have to change the statusBatStyle to UIStatusBarStyleLightContent. You can do it by including the following line in your code.
```
UIApplication.sharedApplication().setStatusBarStyleAnimated(UIStatusBarStyle.UIStatusBarStyleLightContent,false);
```
You can find more information about the StatusBar [here](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/TransitionGuide/Bars.html). 

And the other thing is to change your Info.plist. There are two ways to do that:
- You can do that by directly modifying it in Xcode by adding a new line and set the **View controller-based status bar appearance** to  **NO**.

**or**

- You can go to YourProject/platforms/ios/YourProject/YourProject-Info.plist and include the lines in the **dict** tag section:
```
<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
```

**Comment by oscar-78** [comment]
@N3ll - Thank you for the steps provided. I've changed the statusBarStyle to UIStatusBarStyleLightContent in the code and added the **View controller-based status bar appearance** to the Info.plist and set it so **NO** as you mentioned, but now the status bar has disappeared.

Any idea what I'm missing?

**Comment by N3ll** [comment]
Do you keep the code where you set a dark background? I think that it is necessary to se a dark background, so the white color of the icons could be visible. The scenario I was testing, after I changed the Info.plist, was the following:
```
exports.onPageLoaded = function (args) {
    var iosFrame = frameModule.topmost().ios;
if (iosFrame) {
 UIApplication.sharedApplication().setStatusBarStyleAnimated(UIStatusBarStyle.UIStatusBarStyleLightContent,false);
    var controller = iosFrame.controller;
    controller.view.window.backgroundColor = UIColor.colorWithRedGreenBlueAlpha(0.13, 0.16, 0.20, 1);
}
};
```

**Comment by oscar-78** [comment]
I used the same code but it seems the option **Status bar is initially hidden** set to **YES** in Info.plist was causing the the status bar to disappear and also made the setStatusBarStyleAnimated not effective.

Changing the  **Status bar is initially hidden**  option to **NO** solved the problem for me. Thanks.
