### ISSUE TITLE
Locally store pictures when in offline mode and synchronize when in online mode again

### ISSUE THREAD

**Issue by oscar-78** [NativeScript/NativeScript#1245]
What is the best approach to detect when in offline mode (or 3G mode) and store pictures taken by camera locally and synchronize them when in online (WIFI) mode?

**Comment by N3ll** [comment]
@oscar-78 , what can give a good direction is the [connectivity module](https://docs.nativescript.org/ApiReference/connectivity/HOW-TO.html), with which you can check the connection type.
