### ISSUE TITLE
Enable Canvas API in NativeScript

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#125]
Enable the Canvas API in NativeScript so that existing data visualization frameworks written in JavaScript to be out of the box integrated inside NativeScript. For example - [charts.js](http://www.chartjs.org/).

Please [vote for this issue in our ideas portal](https://nativescript.ideas.aha.io/ideas/NS-I-22).

**Comment by ligaz** [comment]
Here is an iOS implementation that we can use as a reference: https://github.com/phoboslab/Ejecta

**Comment by luxueyan** [comment]
it will be cool if it can support canvas in nativescript!!

**Comment by atanasovg** [comment]
Rendering is one part of the task. Other parts are dimensions and user input responding. Enabling the drawing APIs of the HTML5 Canvas will not be enough to reuse existing Web Libraries in {N}. For example [here](https://github.com/nnnick/Chart.js/blob/master/Chart.js) you can see the usages of the `document` and `window` objects. So, this is connected to enabling some Web shims within {N} and will require more work than the drawing ONLY.

**Comment by bfattori** [comment]
If you're going to enable Canvas support, possibly it should be put into a WebGL 2D orthogonal context. That way, it'll be accelerated on both platforms. Additionally, it seems like Canvas API and WebGL should be polyfills to real GL/ES support. All of the browser capabilities should be polyfills on top of native implementations/plug-ins. That way, performance isn't lost to a bunch of translations in JavaScript.

Just my 2cents!

**Comment by sixman9** [comment]
Gents, I mention a [pre-existing Javascript-based WebGL function list][webgl.js@gh] (provided by Google's Closure compiler) @ [issue 289][webgl.js-289], hopefully, it should be possible to implement this 3D-Canvas API, against equivalent OpenGL ES functions, cross-platform, within NativeScript.

[webgl.js-289]: https://github.com/NativeScript/NativeScript/issues/289#issuecomment-138251892

[webgl.js@gh]: https://github.com/google/closure-compiler/blob/master/externs/browser/webgl.js

**Comment by enchev** [comment]
Hey folks,

Please use this repository to test and submit issues about our Canvas implementation:
https://github.com/NativeScript/nativescript-canvas

Thanks

**Comment by dev2tester1** [comment]
@enchev thank you for this

**Comment by lebeker** [comment]
@enchev , mentioned plugin is not supported anymore. am I missing something, maybe there is other way to perform simple drawing in Nativescript?

**Comment by Simone-cogno** [comment]
I'm also currently look for a way to do some very special drawing in Nativescript. Normally I did this with canvas on Android.
