### ISSUE TITLE
Two way Databinding in Custom Component via XML not working

### ISSUE THREAD

**Issue by shripal04** [NativeScript/NativeScript#1252]
I am trying to create a custom reusable component and want to have two way databinding of a component's property with the main page.

To illustrate the problem( or my misunderstanding) I have created a sample repository at https://github.com/shripal04/nativescript-component-databinding

I want to have two way data binding of `msg` with the `message` property of `GreetingsComponent`

`main-page.xml`
```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd"  
      xmlns:greetings="components/greetings"
      loaded="pageLoaded">
    <StackLayout>
         <greetings:GreetingsComponent message="{{msg}}" />
    </StackLayout>
</Page>
```

`main-page.ts`
```javascript
function pageLoaded(args) {
    var page = <Page>args.object;
    page.bindingContext = mainViewModel;
}
```

`main-view-model.ts`
```javascript
class MainViewModel extends Observable{
	
	_msg: string = 'Hello World';
	
	get msg(){
		console.log('getter called ', this._msg);
		return this._msg;
	}
	
	set msg(value: string){
		this._msg = value;
		this.notifyPropertyChange('msg', value);
	}
}

export var mainViewModel = new MainViewModel();
```

`greetings.ts`

```javascript
var messageProperty = new dependencyObservable.Property(
    "message",
    "GreetingsComponent",
    new proxy.PropertyMetadata("")
);
export class GreetingsComponent extends stackLayoutModule.StackLayout{
	
	static templateUrl: string = 'components/greetings.xml';
	
	static messageProperty = messageProperty;
	
	_message: string;
	
	constructor(){
		super();
		this.init();
	}
	
	get message(){
		return this._getValue(GreetingsComponent.messageProperty);	
	}
	
	set message(value: string){
		this._setValue(GreetingsComponent.messageProperty, value);
	}
	
	private attachView(){
		var xml = getFileContent(GreetingsComponent.templateUrl);
		var view = parse(xml);
		this.addChild(view);
	}
	
	private init(){
		this.bindingContext = this;
		this.attachView();
	}
}
```
`greetings.xml`

```xml
<StackLayout>
	<Label text="Message in greetings component : " />	
	<TextField text="{{message}}"></TextField>
	<Label text="{{message}}" />
</StackLayout>
```
When we do the databinding in XML as I shown above in `main-page.xml` file, it is not working. 

But, if I explicitly define twoway databinding by doing changes as shown below, it is working fine.

`main-page.xml`
```xml
<!-- Binding component property via code: working -->
<greetings:GreetingsComponent id="greetingsComponent" />
```
`main-page.ts`
```javascript
// binding message property
var greetingsComponent = <StackLayout>page.getViewById('greetingsComponent');
if(greetingsComponent){
	greetingsComponent.bind({
		sourceProperty: 'msg',
		targetProperty: 'message',
		twoWay: true
	}, mainViewModel);	
}
```

According to me, to keep the code clean, the databinding in xml should work properly.

Also, an insight of working of twoway databinding for custom component is appreciated.

**Comment by manijak** [comment]
+1
Wow, nice timing on this one. I was wondering the same :)
https://groups.google.com/forum/#!topic/nativescript/KxerscUIAPk

**Comment by nsndeck** [comment]
The problem comes from the fact that `binding` works with `bindingContext` which inherits via visual tree.
Changing `bindingContext` within `greetings.ts#init` method causes the example not working as expected. Unfortunately this action changes `bindingContext` of the entire GreetingsComponent. Therefore binding within main-page `message="{{msg}}"` cannot work, since in this moment bindingContext is the GreetingsComponent itself (which does not have `msg` property). This behavior could be fixed by alternating bindingContext of the inner StackLayout. This will preserve the original bindingContext for the entire component and binding within `main-page.xml` will work.

greetings.xml
```XML
<StackLayout id="greetingsRoot">
    <Label text="Message in greetings component : " />  
    <TextField text="{{message}}"></TextField>
    <Label text="{{message}}" />
</StackLayout>
```

greetings.ts
```Javascript
...
private init(){
        this.attachView();
        var rootPanel = this.getViewById("greetingsRoot");
        rootPanel.bindingContext = this;
    }
...
```

Same happens when binding is set manually, because you are specifying a correct source for the binding.

Let me know if there is something unclear.

**Comment by manijak** [comment]
When I try this in my code, I get "rootPanel" is undefined. I cannot seem to fetch any components from my xml in js by using this.getViewById()
