### ISSUE TITLE
can you make xml file changes trigger livesync's watch?

### ISSUE THREAD

**Issue by ogremagi88** [NativeScript/NativeScript#1253]
I am making changes to my xml file constantly.  However livesync doesn't restart/refresh the app.  I have to go to the js file, add a space somewhere and save the file to get livesync to pickup the changes.  This is really annoying.  Can you make it so that changes to the xml files also restart the app please?  Trying to build a UI with this workflow is quite painful.

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#1350
