### ISSUE TITLE
(ES2015/Babel compat) Deprecate application.mainModule

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/NativeScript#1255]
Problem: using a star import for the `application` module doesn't let you set the `mainModule` var

When you require the application module with a star import in Babel:

```ecmascript
import * as application from "application";
```

You get this `_interopRequireWildcard` helper function:

```
var application = _interopRequireWildcard(_application);

function _interopRequireWildcard(obj) { 
 if (obj && obj.__esModule) { 
  return obj; 
 } else { 
  var newObj = {}; 
  if (obj != null) { 
   for (var key in obj) { 
    if (Object.prototype.hasOwnProperty.call(obj, key)) 
     newObj[key] = obj[key]; 
   } 
  } 
  newObj.default = obj; 
  return newObj; 
 } 
}
```

The problem with that is it copies all exported attributes, which is fine when reading data, but doesn't work at all when writing (`application.mainModule = "main-page"`).

This module-global `mainModule` var has always been suspicious, and it would be way better if we move the main module config option to an `application.start` parameter. Probably the best way to do it would look like:

```
application.start({
    mainModule: "./main-page"
});
```

This isn't a breaking change and we can keep the old option working for some time, and fall back to it, if the app code doesn't provide the `application.start` parameter.

- [x] Add an optional `NavigationEntry` parameter to `application.start` 
- [x] Fall back to `application.mainModule` if no `NavigationEntry` provided
- [x] Update the new project templates.
- [x] Update the docs.

**Comment by hdeshev** [comment]
Another approach would be to pass a `NavigationEntry` to `application.start`:

```
application.start({
    moduleName: "./main-page"
});
```

We could probably use this to make Angular2 initialization simpler and have our `nativeScriptBootstrap` function set up a navigation entry and call `application.start` directly.

**Comment by hdeshev** [comment]
Ping @teobugslayer

**Comment by teobugslayer** [comment]
I think it is a good idea to ping the authors of https://www.npmjs.com/package/gulp-babel-nativescript once this change takes effect so that they can update their code as well.
