### ISSUE TITLE
Livesync both Android and iOS at the same time, only android updates

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#1258]
http://www.screencast.com/t/jIgl2WZ4

When I just had iOS going by itself it seemed fine, when I added android on a new terminal window to sync as well, it just doesn't update iOS, android syncs just fine.

So from the video:
tns livesync ios --emulator --watch
tns livesync android --watch    (<-- Geny emulator)

**Comment by N3ll** [comment]
This issue was moved to NativeScript/nativescript-cli#1354
