### ISSUE TITLE
Can't find variable: UIImageViewModeScaleAspect

### ISSUE THREAD

**Issue by oscar-78** [NativeScript/NativeScript#1259]
I'm trying to use the CocoaPod UIImageViewModeScaleAspect but I'm getting the message *Can't find variable: UIImageViewModeScaleAspect*

**Creating plugin**
* Created folder *nativescript-image-content-animation*
* Inside this folder I've created the file *package.json*
```
{
    "name": "nativescript-image-content-animation",
    "version": "1.0.0",
    "description": "This package installs an animation of a UIImageView between two contentModes",
    "main": "index.js",
    "nativescript": {
        "platforms": {
          "ios": "1.3.0"
      }
}
```
* Inside the same folder I've created a folder *platforms* and inside that folder a folder *ios*
* Inside the *ios* folder I've created a file *Podfile*
```
pod "UIImageViewModeScaleAspect"
```

**Using the plugin**
Within the project folder:
*tns plugin add ../nativescript-image-content-animation*

The NativeScript javascript code:
```
var myImage = UIImageViewModeScaleAspect.alloc().initWithFrame(CGRectMake(0, 100, 200, 100));
myImage.contentMode = UIViewContentModeScaleAspectFill;
myImage.image = UIImage.imageNamed("images/logo");
page.addSubView(myImage);
```
Running the app results in the JS ERROR *Can't find variable: UIImageViewModeScaleAspect*

**Comment by N3ll** [comment]
@oscar-78, we tested the code you provided and it is work as expected. I am using version 1.5.1 and I would advice you to upgrade to it as well.
There are a couple of things that I could suggest. You can check in the node_modules folder whether there is a folder with the name of the plugin. The other thing that you can try is to create the plugin all over again and share the log of the first build, when you add it to the project. Then when you share the log, we can check whether the plugin is built correctly.
There is one more thing I would like to point out. It is about the way you are trying to add a native view to the page. The proper way to do it is by using a [Placeholder](https://docs.nativescript.org/placeholder). There is no method addSubView, by which you can add the a subview to the page.

**Comment by oscar-78** [comment]
Updating to version 1.5.2 solved the issue for me. Also I've used the Placeholder to add the view and works as expected. Thank you.

**Comment by oscar-78** [comment]
I found another CocoaPod [FSImageViewer](https://github.com/x2on/FSImageViewer) which looks like a great image viewer. I installed it in a similar way as described above, but in stead of having a View I now have a ViewController.

To use the View I used the Placeholder, but how can I implement the ViewController.

```
var firstPhoto = FSBasicImage.alloc().initWithImageURLName("http://farm8.staticflickr.com/7319/9668947331_3112b1fcca_b.jpg", "Photo by Brian Adamson");
var secondPhoto = FSBasicImage.alloc().initWithImageURLName("http://farm9.staticflickr.com/8023/6971840814_68614eba26_b.jpg", "Photo by Ben Fredericson (http://farm9.staticflickr.com/8023/6971840814_68614eba26_b.jpg)");
var thirdPhoto = FSBasicImage.alloc().initWithImageURLName("http://farm5.staticflickr.com/4094/4888398067_36e695177a_o.jpg", "Photo by digital cat (https://www.flickr.com/photos/14646075@N03/4888398067)");

var failingPhoto = FSBasicImage.alloc().initWithImageURLName("http://example.com/1.jpg", "Failure image");

var photoSource = FSBasicImageSource.alloc().initWithImages([firstPhoto, secondPhoto, thirdPhoto, failingPhoto]);
var imageViewController = FSImageViewerViewController.alloc().initWithImageSource(photoSource);
```
So how would I use _imageViewController_?

**Comment by PanayotCankov** [comment]
That one is hard to implement. The Placeholder presents Android or iOS views. In iOS - UIView instances. You can check the code of the Frame and Page classes. The Frame creates a UINavigationViewController under the hood and the Page - a UIViewController. If you want to present the image viewer you will probably need a Page instance with custom UIViewController (the FSImageViewerViewController instance).

Currently I am not 100% sure if there is an easy way, I will check with the rest of the team at the start of Jan. I have managed to add the FSImageViewer to a NativeScript project and implement a Page here: [https://github.com/PanayotCankov/nativescript-ios-fsimageviewer](https://github.com/PanayotCankov/nativescript-ios-fsimageviewer) however it breaks somewhat assertions inside the FSImageViewer we will have to further research.

**Comment by oscar-78** [comment]
@PanayotCankov - Great that you're trying to make this Pod work. I'm going to dig into your code and see if I can use it in my app.

I was also trying to implement the FSImageViewer controller by looking at another example and I created a NativeScript module with this code:
```
module.exports = {
	view: function(images, imageIndex) {
		var basicImages = [];

		images.forEach(function (image) {
			var basicImage;
			if (image.imageSource) {
				if (image.imageSource instanceof UIImage) {
					if (image.name) {
						basicImage = FSBasicImage.alloc().initWithImageName(image.imageSource, image.name);
					} else {
						basicImage = FSBasicImage.alloc().initWithImage(image.imageSource);
					}
				} else {
					throw new Error("imageSource must be an instance of UIImage");
				}
			} else if (image.url) {
				if (image.name) {
					basicImage = FSBasicImage.alloc().initWithImageURLName(NSURL.URLWithString(image.url), image.name);
				} else {
					basicImage = FSBasicImage.alloc().initWithImageURL(NSURL.URLWithString(image.url));
				}
			}

			if (basicImage) {
				basicImages.push(basicImage);
			} else {
				throw new Error("Failed to add image");
			}
		});

		var basicImageSource = FSBasicImageSource.alloc().initWithImages(basicImages);
	    if (typeof imageIndex === "undefined") {
		    var imageViewController = FSImageViewerViewController.alloc().initWithImageSource(basicImageSource);
	    } else {
		    if (!isNaN(imageIndex)) {
		    	var imageViewController = FSImageViewerViewController.alloc().initWithImageSourceImageIndex(basicImageSource, imageIndex);
		    } else {
		    	throw new Error("imageIndex must be a number");	
		    }
		}

		UIApplication.sharedApplication().keyWindow.rootViewController.presentViewControllerAnimatedCompletion(imageViewController, true, null);
	}
}
```
Within NativeScript I can start the viewer by:
```
imageViewer.view([
	{ url: "http://farm8.staticflickr.com/7319/9668947331_3112b1fcca_b.jpg", name: "Photo by Brian Adamson" },
	{ url: "http://farm9.staticflickr.com/8023/6971840814_68614eba26_b.jpg", name: "Photo by Ben Fredericson (http://farm9.staticflickr.com/8023/6971840814_68614eba26_b.jpg)" },
	{ url: "http://farm5.staticflickr.com/4094/4888398067_36e695177a_o.jpg", name: "Photo by digital cat (https://www.flickr.com/photos/14646075@N03/4888398067)" }
], 1);
```
Not sure if this is the right way to implement this. I'm missing the titlebar and close button here, so still working on it.

**Comment by PanayotCankov** [comment]
I used the same aproach initially and display the controller on button tap. Then the navigation bar with a back button was visible but the app throw an error on back tap with "corrupted navigation stack". The NativeScript framework keeps a stack with its own navigatio entries and calling directly the native APIs seem to mess it up. Ultimately the {N} should allow UIViewControllers to be displayed similar to the approach with the placeholder used to display UIViews. We will investigate this further.

Have a great party tonight!

**Comment by oscar-78** [comment]
Hi - was wondering if there is any update in this issue.
