### ISSUE TITLE
Support 3D Touch as gesture

### ISSUE THREAD

**Issue by ligaz** [NativeScript/NativeScript#1260]
It will be good to add support for [3D Touch](https://developer.apple.com/ios/3d-touch/) available in newer iOS devices.

**Comment by x4080** [comment]
And Android equivalent as long press ala Instagram. Long press already available though?

**Comment by manoldonev** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Thank you!
