### ISSUE TITLE
Implement Icon Font support for ActionBarItems

### ISSUE THREAD

**Issue by firescript** [NativeScript/NativeScript#1267]
The icon font only loads in the actionBar.titleView, not actionItems.

```
        <ActionBar>
            <ActionBar.titleView>
                <Label text="&#xf117;" class="material-icon"/>
            </ActionBar.titleView>
            <ActionBar.actionItems>
                <ActionItem text="&#xf117;" class="material-icon" ios.position="right" tap="logout" style="font-family: Material-Design-Iconic-Font;"/>
            </ActionBar.actionItems>
        </ActionBar>
```

**Comment by sitefinitysteve** [comment]
Per this issue, unsupported\not implimented
https://github.com/NativeScript/NativeScript/issues/1166

Would love to see it, esp after this post says it's best prac
https://www.nativescript.org/blog/mobile-app-best-practices---use-font-instead-of-image-to-show-an-icon

**Comment by guillaume-roy** [comment]
+1 for this feature ! :)

**Comment by enchev** [comment]
Merged with https://github.com/NativeScript/NativeScript/issues/499
