### ISSUE TITLE
Variables not substituted in android plugin

### ISSUE THREAD

**Issue by rodenp** [NativeScript/NativeScript#1270]
I have a plugin that has the 2 variables below 

    "variables": {
      "FACEBOOK_APP_ID": {},
      "APP_NAME": {}
    }

I have tried 2 methods to get the facebook_app_id into the Android manifest:

1. A strings.xml in the res\values directory of the plugin: 

Here is my Android manifest:

<?xml version="1.0" encoding="UTF-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.INTERNET"/>
    <application>
        <meta-data
          android:name="com.facebook.sdk.ApplicationId"
          android:value="@string/facebook_app_id"
        />
        <activity android:name="com.facebook.FacebookActivity"
          android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
          android:theme="@android:style/Theme.Translucent.NoTitleBar"
          android:label="@string/app_name" />
    </application>
</manifest>

and strings.xml in the res\values directory

this works:

<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string name="facebook_app_id">593600500735750</string>
</resources>

but this doesn't:
 
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string name="facebook_app_id">{FACEBOOK_APP_ID}</string>
</resources>

2. Removing the need for the strings.xml and including the facebook_app_id variable in the Android manifest:

<?xml version="1.0" encoding="UTF-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.INTERNET"/>
    <application>
        <meta-data
          android:name="com.facebook.sdk.ApplicationId"
          android:value="{FACEBOOK_APP_ID}"/>
        <activity android:name="com.facebook.FacebookActivity"
          android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
          android:theme="@android:style/Theme.Translucent.NoTitleBar"
          android:label="@string/app_name" />
    </application>
</manifest>

running gives the following results:

/Users/osx/Development/nativescript/fbtest2/platforms/android/src/main/AndroidManifest.xml:20:3-64 Warning:
	Element uses-permission#android.permission.INTERNET at AndroidManifest.xml:20:3-64 duplicated with element declared at AndroidManifest.xml:8:3-64
/Users/osx/Development/nativescript/fbtest2/platforms/android/src/nativescript-facebook-sdk/AndroidManifest.xml:17:62-93 Error:
	Attribute meta-data#com.facebook.sdk.ApplicationId@value value=({FACEBOOK_APP_ID}) from AndroidManifest.xml:17:62-93
	is also present at AndroidManifest.xml:17:62-93 value=(593600500735750)
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:5:9-8:11 to override
:processNativescript-facebook-sdkDebugManifest FAILED

It looks like it manages to substitute the variable value correctly, however there are 2 versions of the meta data, which looks like the original version and the version with the substitution. 

I have noticed that i often get warnings saying there are duplicate entries in the manifest file after merging and normally these manage to not stop the build.

**Comment by rodenp** [comment]
Looks like some formatting got lost:

here are the 2 versions of the strings.xml in the res\values directory

this one works:

<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string name="facebook_app_id">593600500735750</string>
</resources>

this one doesn't

<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string name="facebook_app_id">{FACEBOOK_APP_ID}</string>
</resources>

**Comment by N3ll** [comment]
This issue was moved to NativeScript/android-runtime#310
