### ISSUE TITLE
CSS styling of custom components

### ISSUE THREAD

**Issue by N3ll** [NativeScript/NativeScript#1271]
Write article about how to use CSS with custom components. Or provide an easier solution for the Stylers.

**Comment by sitefinitysteve** [comment]
How to:
- check loaded css for a selector
- parse rules inside a match to act on them

So lets say i have a cocoapod item called SteveBar...its only loaded through code, no xml component.  I would like to support fontfamily, color, and padding in it.  So in the plugin I want an easy way to check for SteveBar in the css, and tweak the element based on the css.

**Comment by vakrilov** [comment]
This issue is no longer relevant. Stylers have been removed in NativeScript 3.0.
