### ISSUE TITLE
ActionBar disappears when app closes with back button

### ISSUE THREAD

**Issue by sect2k** [NativeScript/NativeScript#1275]
On Android 5.1.1 (Sony Xperia Z3C) when navigating back using the hardware back button all the way out of the app, when reopening ActionBar disappears.

At first I thought this might just be an issue with my app, but I just noticed this on the Examples NativeScript app as well.

**Comment by amjd** [comment]
I just tested this. It's happening on my app too.

**Comment by MehdiZonjy** [comment]
I just noticed this bug in my app as well. I tested it on android 6.0 and 4.4.4 and it is happening on both systems.
I thought something was wrong with my code, so i cloned the Sample-Tasks repository and the bug is there as well.

**Comment by MehdiZonjy** [comment]
i think i found a quick fix. in the onPageLoaded event I add this 
    page.actionBarHidden=false;
and it seems to keep the ActionBar visible even after the app was minimized. This is rather inconvenient as you have to add this line to every page you have. I hope this issue gets fixed in a future release.

**Comment by ahmadmarafa** [comment]
i have the same issue
