### ISSUE TITLE
TabView button icons (iOS)

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#1278]
I am creating a separate issue based my comments here: https://github.com/NativeScript/NativeScript/issues/1269
The original question was answered. 

@vakrilov , @maknz
From what I can see in ```tab-view.ios.js``` under tns_core_modules, line 218 is reason why tab-view icons look different in the latest release.

```javascript
...
var originalRenderedImage = is.ios.imageWithRenderingMode(UIImageRenderingMode.UIImageRenderingModeAlwaysOriginal);
...
```
The icon image rendering mode is set to ```AlwaysOriginal```. This means the icons will keep their original rendering, this is not default iOS behaviour, I think...

If I override this to ```AlwaysTemplate``` or  ```Automatic```, it will use the iOS color-templating on the tabBar icons. And you can define both text and icon color with the ```selectedColor``` property. 

Most of the time it is easier to use ```AlwaysTemplate``` since iOS takes care of the normal and selected color for each button, and you can use one icon for both states. 

But if we use ```AlwaysOriginal``` then we must provide both normal and selected icon-images, since they are not colored by iOS anymore. So we need to provide to version of each icon (one for each state). And from the looks of it, TabView in nativescript does not provide properites to add icons for both states.

**Comment by stevetayloruk** [comment]
+1

**Comment by manijak** [comment]
This should have been fixed/improved for 1.7.0.  Very annoying issue where we have to manually change ```tab-view.ios.js``` every time there is a release/update to the core-modules.

Please change the image render mode to Automatic and give us the ability to set color to both selected and non-selected buttons. And/Or the possibility to set normal and selected icons.

**Comment by hamorphis** [comment]
@manijak It's fixed. For simple stuff like this you can always change one two lines of code and then open a pull request.

**Comment by toddanglin** [comment]
@manijak Thanks again for raising this issue and providing the suggested solution! Everyone will now benefit in the 2.2 release.

**Comment by leocaseiro** [comment]
Perhaps, would be nice if we had the option to choose between `UIImageRenderingModeAlwaysOriginal` and `UIImageRenderingModeAutomatic`.
