### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by RWOverdijk** [NativeScript/NativeScript#128]
I was wondering if there's an official communications channel for nativescript. I'm aiming for the usual suspects (IRC or gitter).

I think this could be useful for the progress as well as the expansion of the NativeScript community.

**Comment by valentinstoychev** [comment]
You can reach us here, on [twitter](http://twitter.com/nativescript) or in our public [forums](https://groups.google.com/forum/#!forum/nativescript). If you want to reach out to the PM team please send me an email at valentin.stoychev@telerik.com.

Looking forward hearing from you!

**Comment by RWOverdijk** [comment]
Ha, sorry... I missed the README.

> IRC Chatroom - http://webchat.freenode.net/?channels=nativescript

**Comment by z3t0** [comment]
Hmm. The irc seems to be quite .. empty. Any chance of an official Gitter?

**Comment by valentinstoychev** [comment]
@z3t0 I know it is not RTC, but the best place to discuss is the public forum - https://groups.google.com/forum/#!forum/nativescript
