### ISSUE TITLE
text-transform breaks child colors

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#1280]
http://www.screencast.com/t/ywVfBrLx

So this works okay, text though isn't uppercase
```
<Label cssClass="logo-label" textWrap="false">
	<Label.formattedText>
		<FormattedString>
			<FormattedString.spans>
				<Span text="{{ BrandPrefix }}" fontAttributes="Bold" cssClass="prefix" />
				<Span text="{{ BrandPostfix }}" fontAttributes="Bold" foregroundColor="#bd5680" />
			</FormattedString.spans>
		</FormattedString>
	</Label.formattedText>
</Label>
```

So when I add in text-transform: uppercase it's now uppercase,  but I lose the purple on "Help"

**Comment by pointdeveloper** [comment]
yes text-transform does not work..but text-transform is not mentioned in the docs http://docs.nativescript.org/ui/styling so i guess it is not meant to work in the first place..kindly suggest any other way to transform the case of text...

**Comment by sitefinitysteve** [comment]
It might not be in the docs, but it is there... Just maybe borked which is why i opened the issue 

https://twitter.com/nativescript/status/677116835398053888

**Comment by pointdeveloper** [comment]
okay i found this in the docs http://docs.nativescript.org/ApiReference/ui/enums/TextTransform/README i have no idea how to implement this in the view

**Comment by sitefinitysteve** [comment]
Just add it in the css like you would in html

**Comment by pointdeveloper** [comment]
okay i found this in the docs http://docs.nativescript.org/ApiReference/ui/enums/TextTransform/README i have no idea how to implement this in the view

**Comment by pointdeveloper** [comment]
okay..i have another issue regarding this..i am loading a list from a http call and the list is loading fine and i can getting the desired text-transform, BUT i only see the text in the visible area as capitalized the rest of the text is not, so when i scroll down i see non-styled text

**Comment by sitefinitysteve** [comment]
I'm not using it on that context so i can't comment, but if you believe this to be a problem, open a new issue for it... Its not related to this one so it might get overlooked

**Comment by priyangamani** [comment]
Text Transform is not working in tns 3.0
