### ISSUE TITLE
Native properties are reset on orientation change

### ISSUE THREAD

**Issue by speigg** [NativeScript/NativeScript#1281]
I'm doing this when the page loads:

```typescript
function makePageTransparentIOS(page:pages.Page) {
	const pageView:UIViewController = page.ios;
	pageView.view.opaque = false;
	pageView.view.backgroundColor = UIColor.clearColor();
}

export function pageLoaded(args) {
    var page:pages.Page = args.object;
	if (page.ios) {
		makePageTransparentIOS(page)
	}
}
```

I tried using css, but apparently there isn't support for `rgba` values for `background-color` yet (opacity works, but I don't want to make the entire view + child views transparent, just it's background).

The problem is that the view's native properties (`opaque` and `backgroundColor`) are apparently being reset whenever the device orientation changes. I tried listening to the `orientationChange` event via the `application` api, but the native properties were still being reset after the orientation change. The workaround I finally worked out involves wrapping the `layout` function:

```typescript
export function pageLoaded(args) {
    var page:pages.Page = args.object;
	if (page.ios) {
		makePageTransparentIOS(page)
		const origLayout = page.layout;
		page.layout = function(...args) {
			origLayout.apply(page, args);
			makePageTransparentIOS(page);
		}
	}
}
```

Is this the intended workflow, or is there a bug?

**Comment by vakrilov** [comment]
Hi @speigg 
Indeed the `rgba` syntax is not yet supported in CSS, but you can set the color with hex in the following format `#AARRGGBB`. 
Here is an example of setting page background to semi-transparent red:

```
Page {
  background-color: #88FF0000;
}
```

**Comment by speigg** [comment]
Well, I can verify that using the `#AARRGGBB` format works, it's unfortunate that it's non-standard css though :\
