### ISSUE TITLE
Move between textfields with an on screen created button?

### ISSUE THREAD

**Issue by jphillips139** [NativeScript/NativeScript#1282]
is there any way to move to the next textfield or previous with a button you create on screen.
I have tried to make a couple functions of my own for this but i can't make any headway

**Comment by jphillips139** [comment]
function () {
    var pos, prev, next, setFocus;
   
    pos = 0;
    prev = document.getElementById('previous');
    next = document.getElementById('next');

    prev.onclick = function (e) {
        console.log('*');
        pos -= 1;
        setFocus();
    };
    
    next.onclick = function (e) {
        console.log('*');
        pos += 1;
        setFocus();
    };

    setFocus = function () {
        document.querySelector(
            'input[tabindex="' + pos +'"]'
        ).focus();
    };
})();


i was modeling my function off of this but im not sure what to use with the .focus and others?

**Comment by N3ll** [comment]
Hello @jphillips139 , NativeScript is not using the DOM, so you cannot use those methods. You can access a view by ID by using the **getViewById()** method. More about the architecture of a NativeScript application, can be found in the [docs](https://docs.nativescript.org/core-concepts/navigation.html). Below, you can see how you can switch the focus of two **TextField**s.

**main-page.xml**
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd">
  <StackLayout>
    <TextField id="first"/>
    <TextField id="second"/>
    <Button text="TAP" tap="changeFocus" />
  </StackLayout>
</Page>
```
**main-page.js**
```
var isTxt1Focused=true;
exports.changeFocus=function(args){
	var txt1 = args.object.page.getViewById("first");
	var txt2 = args.object.page.getViewById("second");
	if(isTxt1Focused){
		txt2.focus();
	}else{
		txt1.focus();
	}
	isTxt1Focused=!isTxt1Focused;
}
```

It might be useful for you check the [**Events** article](http://docs.nativescript.org/core-concepts/events) and [here](https://docs.nativescript.org/ApiReference/ui/core/view/View.html) you can check the **focus()** method.
