### ISSUE TITLE
Can't access args.object.page from ActionBar ActionItem tap event

### ISSUE THREAD

**Issue by maknz** [NativeScript/NativeScript#1283]
Normally when you have an onTap event on a page, you can access the page object using `args.object.page`. This is not possible when the tap handler is for an ActionItem in an ActionBar, where `page` does not exist on the `args.object`.

**Comment by vakrilov** [comment]
Hi @maknz 
The reason for this is that the ActionItem does not actually inherit form `View` and there is no `page` property. You can obtain a reference to the page by calling **`args.object.actionBar.page`**.

However it is reasonable that the `ActionItem` has property `page` for the sake of consistency.
