### ISSUE TITLE
WKWebView plugin to hook into webView

### ISSUE THREAD

**Issue by swlemp** [NativeScript/NativeScript#1287]
@tjvantoll "The web view module indeed uses UIWebView https://github.com/NativeScript/NativeScript/blob/e458a94191ea593e2a940c3610e7c9570aac1740/ui/web-view/web-view.ios.ts#L12 I don’t think there are any plans to switch to WKWebView at the moment. You’re welcome to file an issue. This would be a good candidate for a plugin"

I hear the hype about WKWebView and I'm sold, I am moving from cordova and it's such a bummer that there is no WKWebView :-(

**Comment by NathanaelA** [comment]
@vbresults The reason it uses UIWebView is because of compatibility.  WKWebView is iOS 8 and greater.  NativeScript supports iOS 7.    So unfortunately they have to program nativescript using what works on ALL the platforms.

**Comment by x4080** [comment]
Its time to move to ios 8 above?

**Comment by thepian** [comment]
Who cares about iOS 7 ?? People that also support IE 5 ?

**Comment by N3ll** [comment]
We are currently discussing the matter with the iOS 7 support. It will be stopped soon, so just stay tuned!

**Comment by x4080** [comment]
That is good news

**Comment by NathanaelA** [comment]
@N3ll you know rather than dropping ios 7 support; we could set it up so that it uses UIWebView on < 8 and WKWebView  >= 8.
The code just needs to detect which platform it is on, then create the proper WebView.  The app consuming the webview doesn't need to know about the underlying implementation.

**Comment by vbresults** [comment]
@NathanaelA I discovered in my Cordova project that WK on iOS 8 has the perplexing limitation of not being able to set a custom user agent.  WK.customUserAgent and updating NSUserDefaults do nothing.

Seems the iOS 9 implementation is more solid all around, maybe this was intentional.  @N3ll I second Nathan's idea with two changes -- WK default on iOS >= 9 and/or option to pick implementation.

**Comment by NathanaelA** [comment]
@vbresults Hmm, I wonder if this is something caused by cordova, or if this is something that is a bug in WKWebBrowser on iOS.

**Comment by NathanaelA** [comment]
@N3ll @hshristov If I updated the NativeScript core code to have the ability to use UIWebView <= 7 and WKWebVeiw => 8 would this be a patch that would be accepted; or would it be better for me to just create a WKWebView plugin?

**Comment by vbresults** [comment]
@NathanaelA It's definitely the WK in iOS 8.  I also confirmed by going to the iOS dev IRC and asking.

**Comment by PierBover** [comment]
So was WKWebView implemented in NativeScript?

Only 3% of iOS users are on iOS 7 or below. https://developer.apple.com/support/app-store/

**Comment by vbresults** [comment]
@PierBover It wasn't, but I have been able to implement it successfully in a private plugin (and unfortunately, for the time being it needs to remain private, but if that changes I'll post an update).

WKWebView should only be implemented for iOS 9 or newer.  The iOS 8 implementation is incomplete, many documented features simply don't work.  On iOS 9 it's perfect.

**Comment by PierBover** [comment]
> On iOS 9 it's perfect, zero problems.

[I beg to differ...](https://bugs.webkit.org/buglist.cgi?quicksearch=wkwebview&list_id=2149784) but the most annoying ones are [related to the file:// protocol](https://bugs.webkit.org/show_bug.cgi?id=154916).

**Comment by bnussey** [comment]
I am seeing memory leaks with UIWebView in our NativeScript project.. and a quick look on stackoverflow, looks like many others are experiencing this as well and recommend switching to WKWebView. Lets go to WKWebView!

**Comment by triniwiz** [comment]
We should get it after https://github.com/NativeScript/NativeScript/pull/5093

**Comment by davidsandoz** [comment]
It looks like this is done and included in NativeScript 3.4.0.

Shouldn't it be mentioned in the [CHANGELOG](https://github.com/NativeScript/NativeScript/blob/master/CHANGELOG.md)?

**Comment by m-abs** [comment]
@davidsandoz Yes, it should've been in the changelog.
It's a breaking change for us.
