### ISSUE TITLE
Rxjs 

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#1289]
Since ns compatible with angular 2. How about rxjs observables in ns? It will be awesome to have functional event programming

**Comment by jlooper** [comment]
Pinging @burkeholland on Rxjs :)

**Comment by hdeshev** [comment]
We will definitely support this for the Angular renderer and related components/directives.

RxJS observables are very different than the built-in NativeScript observables, and supporting those for the vanilla databound controls may be tricky. Anyway we may consider adding support, if there is enough interest in using RxJS sans Angular.
