### ISSUE TITLE
Change Android button background method

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/NativeScript#1296]
Change the button background styling from 

          setBackground()
to

         setBackgroundTintList()

           btn.setBackgroundTintList(android.content.res.ColorStateList.valueOf(tColor.android));

I've done this programatically by creating a new android.widget.Button() and found no issues.

If this is possible without collision in other areas it would give the buttons their material design ripple effect, whereas setBackground removes the ripple effect. Will this open other issues. I didn't want to make a PR without knowing if there would be other issues or conflicts.

**Comment by x4080** [comment]
Good idea

**Comment by vakrilov** [comment]
Nice one @bradmartin  - it is good to be able to change the color of the button without loosing the material design.

**Comment by enchev** [comment]
We can use simply:
```JavaScript
var nativeColor = v.style._getValue(style.backgroundColorProperty).android;
nativeView.getBackground().setColorFilter(nativeColor, android.graphics.PorterDuff.Mode.SRC_IN);
```
if only backgroundColor is set. In this way we can preserve other styles.

**Comment by talvasconcelos** [comment]
Hi @enchev i'm sorry, how do i implement that code you showed. I have this issue where the button background-color is used as a tint, or has transparency... i want to remove that.

i pasted that snippet in my app.js and it fails to compile saying "v" is not defined... i missed a require somewhere.

**Comment by spstratis** [comment]
@enchev  I have the same question as @talvasconcelos, what is the "v" object referencing here?

**Comment by bradmartin** [comment]
Think it's the view instance so the button. Not at computer to check the NativeScript view api but i think that's it

**Comment by spstratis** [comment]
@bradmartin Got it, that would make sense.

**Comment by spstratis** [comment]
In one of my views where I'm experiencing this problem I've tried the following:

```
exports.viewLoaded = function (args) {
    var page = args.object;
    var createBtn = page.getViewById('create-btn');
    var nativeColor = createBtn.style._getValue(style.backgroundColorProperty).android;    
    page.getBackground().setColorFilter(nativeColor, android.graphics.PorterDuff.Mode.SRC_IN);
    page.bindingContext = eulaViewModel;    
};
```

Yet when I load that view I get the following error:

> TypeError: Cannot read property 'id' of undefined
> File: "/data/data/org.nativescript.LibreLinkUp/files/app/tns_modules/ui/core/dependency-observable.js, line: 148, column: 50


Should I be referencing a different "view" when calling getBackground()? I have tried a couple different things but none of them are working out.

**Comment by calebeaires** [comment]
@enchev - Is this issue still on NativeScript team radar?

**Comment by enchev** [comment]
Hey @calebeaires,

This was fixed long time ago. Right now if you only want to set the color we will not override the default drawable.

**Comment by calebeaires** [comment]
Thanks for your help.

May you just me give some more info? If I choose to use ```border-width```, I will loose ripple effect on Android 4.2 to Android 4.4?

**Comment by enchev** [comment]
Yep, @bradmartin is correct. You can only set the color if you want to keep the original drawable.
