### ISSUE TITLE
Feature request: android's slide to delete

### ISSUE THREAD

**Issue by dragGH102** [NativeScript/NativeScript#1297]
In Nativescript's starter tutorial (http://docs.nativescript.org/start/getting-started) starting repository a "swipe to delete" feature is provided for iOS.

For Android a button-passed (tap on trash image to delete) is proposed.
However, as far as I know, slide to delete is now a recommended design pattern on Android too.

A native (Java) implementation with no minimum SDK level requirement is available at: https://github.com/JakeWharton/SwipeToDismissNOA/blob/master/src/com/example/android/swipedismiss/SwipeDismissTouchListener.java

Would it be possible to create a plugin (or a core module) to do it on Nativescript when deploying to Android?
Alternatively I can try to implement it myself, with some piece of advice on how-to (I'm a beginner in both Nativescript and Android native development)

**Comment by enchev** [comment]
This is already available https://github.com/NativeScript/NativeScript/issues/725
