### ISSUE TITLE
Calling focus() on a editable-text-base in Android will not automatically show the softInput

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#1299]
Currently calling `focus()` on a `TextField` in Android will focus and add the cursor, but will not show the soft input.

I've managed to get around this by using `toggleSoftInput` instead of `showSoftInput`.

This code will show the keyboard as intended:
```js
  var imm = utils.ad.getInputMethodManager();
  imm.toggleSoftInput(android.view.inputmethod.InputMethodManager.SHOW_IMPLICIT, 0);
``` 

However {N}s code inside utils does not show the input:

```js
 export function showSoftInput(nativeView: android.view.View): void {
        var imm = getInputMethodManager();
        if (imm && nativeView instanceof android.view.View) {
            imm.showSoftInput(nativeView, android.view.inputmethod.InputMethodManager.SHOW_IMPLICIT);
        }
    }
```

I have also tried using `imm.showSoftInput(nativeView, android.view.inputmethod.InputMethodManager.SHOW_IMPLICIT);` outside of this method, and still does not show the soft input.

**Comment by N3ll** [comment]
@lscown, on which device are you testing this code? What I tried and work for me (on Genymotion) was your second solution:
```
 imm.showSoftInput(nativeView, android.view.inputmethod.InputMethodManager.SHOW_IMPLICIT);
```

Here is the code that I was testing with:

**main-page.xml**
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd">
  <StackLayout>
    <TextField id="first"/>
    <TextField id="second"/>
    <Button text="TAP" tap="changeFocus" />
  </StackLayout>
</Page>
```

**main-page.js**
```
var device = require("platform").device;
var platformNames = require("platform").platformNames;
var utils = require("utils/utils");


var isTxt1Focused=true;
exports.changeFocus=function(args){
    var txt1 = args.object.page.getViewById("first");
    var txt2 = args.object.page.getViewById("second");
    if(isTxt1Focused){
        txt2.focus();
    }else{
        txt1.focus();
    }
    isTxt1Focused=!isTxt1Focused;

    if(device.os === platformNames.android){
    	var imm = utils.ad.getInputMethodManager();
  		imm.showSoftInput(args.object.android, android.view.inputmethod.InputMethodManager.SHOW_IMPLICIT);
    }
}
```

**Comment by dtopuzov** [comment]
I can confirm that keyboard is not available when focus some input field on default Android Emulator with Api17, however I'm not able to reproduce on Sony Experia with Api17 and Emulators with Api19 and above. Can you try on device or emulator with Api19+.
