### ISSUE TITLE
how to debug App?

### ISSUE THREAD

**Issue by bitcard** [NativeScript/NativeScript#13]
js can debug chrome or firebug or node-inspector, how to debug with NativeScript? thanks.

**Comment by bitcard** [comment]
I test the appbuilder, but print the follow error.
You are running an outdated version of the Telerik AppBuilder CLI. To run this command, you need to update to the latest version of the Telerik AppBuilder CLI. To update now, run 'npm update -g appbuilder'.

the latest version is 2.8.2-324.

**Comment by ligaz** [comment]
Hey @bitcard,

You can debug NativeScript apps with NativeScript CLI using the `tns debug` command. 

You can also debug with our AppBuilder tool chain. Its CLI current latest version is: 2.8.3-331 as stated on npmjs.org: https://www.npmjs.com/package/appbuilder. Have you tried to update it using `npm update -g appbuilder`?

**Comment by bitcard** [comment]
@ligaz thanks for your reply. yes, I have run the command "npm update -g appbuilder". but the result is same.
 
I also use "tns debug android --debug-brk or tns debug android --debug-brk --debuggerPort 12345", the App can be installed and run on the device, guide from https://github.com/NativeScript/nativescript-cli/wiki/Debug-command-specification.
"starts the app with ID com.example.MyApp with V8 debuggger enabled and waiting until debug client tools are connected", using what's dubug tools to connect?

**Comment by ligaz** [comment]
About the AppBuilder issue can you `npm cache clear` followed by `npm uninstall -g appbuilder` and then `npm install -g appbuilder` in an attempt to install the latest version?

Regarding the NativeScript CLI debugging I have recorded a [short video](http://screencast.com/t/Q1FcReCYrL9) that illustrates its basic usage. Hope you will find it useful.

**Comment by bitcard** [comment]
@ligaz thanks a lot, it's so great, NativeScript CLI also using node-inspector to debug app.
I will try appbuilder debug later.

**Comment by Sunify** [comment]
What about debug in iOS Simulator?

I try
````tns debug ios --debug-brk --emulator````

but get the error
````
Check dependencies
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 8.2'

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
Command xcodebuild failed with exit code 65
````

Dev account is required?

**Comment by PanayotCankov** [comment]
Up to v0.9.4 debugging in iOS was supported only for device connected through USB.
We have already implemented debugging on emulator, it is merged in the master:
[https://github.com/NativeScript/nativescript-cli/pull/339](https://github.com/NativeScript/nativescript-cli/pull/339)

**Comment by Sunify** [comment]
Thanks!

**Comment by rclai** [comment]
If I wanted to debug an iOS app, would it only work in a Mac?
