### ISSUE TITLE
Ability to block back button pressed

### ISSUE THREAD

**Issue by maknz** [NativeScript/NativeScript#1300]
It would be good if we could block the back button from being pressed (i.e. the hardware button). Our use case is that we want to throw a modal up for PIN entry, but don't want the user to be able to access the app before they verify their PIN. They can't close the modal without entering the PIN, but they can use the hardware back button (on Android) to get into the app.

**Comment by bradmartin** [comment]
If you need this before something is implemented, you should be able to hack something together using this android API: http://developer.android.com/intl/zh-tw/reference/android/view/KeyEvent.html#KEYCODE_ESCAPE  and from what I see you'll have to wire up the android.view.KeyEvent.Callback and handle the 'onKeyDown' method(keyCode, event)  and I think you could return false to prevent any action from happening.

**Comment by maknz** [comment]
We no longer need this, but I'll leave the issue open to be addressed (i.e. if {N} want to build it, or not).

**Comment by NathanaelA** [comment]
@maknz; what did you do to solve this?  I haven't looked into this; but I believe I may need something like this in the future.

**Comment by maknz** [comment]
To provide a bit of context, we were implementing PIN entry for our app. Rather than using a modal that pops over the current page and will close on correct pin (but the back button could be used to evade it easily), we just used a more bulletproof method of navigating to the pin entry screen (clearing history, not backstack visible).

So we didn't solve the problem (plus, blocking the back button is a bit shit anyway, right?), we just implemented our feature a little differently.

**Comment by vjoao** [comment]
Has anyone been able to do this?

**Comment by Milewski** [comment]
@vjoao i mananged to block back click with this

```
 if (application.android) {

            application.android.on(application.AndroidApplication.activityBackPressedEvent,
                function (args:application.AndroidActivityBackPressedEventData) {

                   if(......)
                      return true //can go back

                });
        }
```

**Comment by vjoao** [comment]
@Milewski 

Actually I'm using a pretty neat solution from @NathanaelA 's blog.

Thanks anyway.

**Comment by NathanaelA** [comment]
For a public service the blog in question is: http://fluentreports.com/blog/?p=261
It deals with the back button on Android and how to catch it, and the potential gotchas.
