### ISSUE TITLE
Modal caching problem in iOS

### ISSUE THREAD

**Issue by basumeet** [NativeScript/NativeScript#1301]
I am developing a cross-platform tablet app that requires a modal view . The modal works perfectly fine in android, but in iOS , there is a screen flicker when the modal is re-opened, the contents of the previous modal page are visible for some milliseconds, and are replaced by the new contents.
![modal-defect](https://cloud.githubusercontent.com/assets/16472210/12030130/c689479a-ae1f-11e5-9822-30f1b82a438d.gif)

The behavior is same for both bindingContext with template binding characters {{}} and changing the src for the modal image programatically.

**Comment by basumeet** [comment]
the behavior is same for emulator and device

**Comment by sitefinitysteve** [comment]
Is the image bound? ...Can you reset the src binding on close perhaps?

**Comment by basumeet** [comment]
@sitefinitysteve , Hi , yep it is bound, and resetting the source on modal close does not help, neither does setting a timeout to allow it to do so, nor does resetting it as the first thing on pageLoad, with reference to  the context, please refer https://plus.google.com/107683543476608830354/posts/iFqiKwoV1os

**Comment by enchev** [comment]
Closing as outdated.
