### ISSUE TITLE
Feature Request : Force orientation

### ISSUE THREAD

**Issue by basumeet** [NativeScript/NativeScript#1303]
It would be great to have the ability of forcing a page to be viewable in a particular orientation, irrespective of the orientation of the android or ios device. For example, it should be possible to play the video in landscape mode only, which could be achieved by locking the page in landscape orientation.

**Comment by NathanaelA** [comment]
On Android you can easily do this by changing the Android Manifest.  I believe on iOS you can change the project file to do the same thing.

**Comment by basumeet** [comment]
Hi Nathaniel, please correct me if I am wrong, I believe we cannot  force the orientation per activity basis on Android and per UIView basis on ios by changing manifest and info.plist. Last time I checked changing those files resulted in forcing orientation on whole app. I suspect that due to programmatic creation of activities/UIViews and deflating them at runtime internally, they can't be configured through manifest/info.plist files.

**Comment by NathanaelA** [comment]
@basumeet Ah, you are correct -- I misread what you were requesting.  You want to lock a single page to an orientation; not the entire app.  This feature is something that will have to be added to the page code for sure; you can't really change this easily after the fact on Android.

**Comment by basumeet** [comment]
https://www.npmjs.com/package/nativescript-screen-orientation

**Comment by SephReed** [comment]
The package linked above no longer works for ios

**Comment by NathanaelA** [comment]
@SephReed - This is a really old issue --  but my nativescript-orientation plugin has allowed you to enable/disable and/or force a orientation on-demand.   :grinning:
