### ISSUE TITLE
How to add .so in lib in Android?

### ISSUE THREAD

**Issue by basti-shi031** [NativeScript/NativeScript#1305]
I have read how to add .jar in [document](http://docs.nativescript.org/runtimes/android/external-libs/jars),but how to add .so file?

**Comment by N3ll** [comment]
@basti-shi031, you can get more information on the topic by checking this [GitHub sample project](https://github.com/NativeScript/sample-native-module), which describes how to add the .so file by using the **require** function. And the other thing that might be very useful is [this discussion](https://groups.google.com/forum/#!topic/nativescript/WPbP33Ks_tk) in the NativeScript Google group.
I hope this will help you!

**Comment by basti-shi031** [comment]
@N3ll thank you.
