### ISSUE TITLE
Not able to install NativeScript Correctly

### ISSUE THREAD

**Issue by lelong37** [NativeScript/NativeScript#1306]
printenv, shows I have all the paths and ANDROID_HOME, JAVA_HOME, etc... correctly set.

![image](https://cloud.githubusercontent.com/assets/4691404/12046791/883d3d64-ae85-11e5-8a12-0078044e61bd.png)

npm i nativescript -g, shows that I don't have ANDROID_HOME correctly set.

![image](https://cloud.githubusercontent.com/assets/4691404/12046803/df5904e8-ae85-11e5-9724-9af891472c81.png)

However even with previous errors when running "tns doctor", everything is fine, despite the errors from the install. Then running "tns platform add android" says ANDROID_HOME is not set, etc... Is this a bug? I imagine tns doctor should really tell you if you really do have everything configured for nativescript cli correctly...?

![image](https://cloud.githubusercontent.com/assets/4691404/12046850/b62ea112-ae86-11e5-8de1-10923db46037.png)

ANDROID_HOME directory is definitely set (see the printenv command screenshot) to the correct path, and I've installed everything for the Android SDK from API 22 -> 19 full install with Android Support Repository, Android Support Library, and Google Repository

![image](https://cloud.githubusercontent.com/assets/4691404/12046879/437e0382-ae87-11e5-984a-3b86e8cad8a3.png)

![image](https://cloud.githubusercontent.com/assets/4691404/12046883/4f213830-ae87-11e5-91ef-fa414c9f994e.png)

Please advise...

**Comment by lelong37** [comment]
For whatever reason if I create a project from scratch "tns create test-project" and rerun all the commands for adding platforms, everything works? So not sure if it's bug with groceries sample?

![image](https://cloud.githubusercontent.com/assets/4691404/12047110/fb7b1d0e-ae8b-11e5-83a3-b03523e7ef24.png)

**Comment by lelong37** [comment]
Confirmed potential bug: tns platform add android only throws exception when adding platform for groceries sample and not a brand new project from scratch.

![image](https://cloud.githubusercontent.com/assets/4691404/12047196/17a6edc2-ae8d-11e5-8c99-2a59f5aa606c.png)

**Comment by nsndeck** [comment]
Environment variables for an average `user` and `root` are quite different. Count you confirm that `ANDROID_HOME` variable is correctly set for `root`. Generally there is no need to install `nativescript` as `root`.

**Comment by lelong37** [comment]
Indeed they are, looks like my $PATH are the same but you right, ANDROID_HOME, etc. are there. I originally configured them in /lelong37/.zshrc. As you mentioned there isn't a need to run NS as root, however I would still like sudo and user to have the same env variables.

![image](https://cloud.githubusercontent.com/assets/4691404/12047975/24ea287a-ae9a-11e5-98f1-891f6a45e5f1.png)

**Comment by N3ll** [comment]
@lelong37, I believe the best thing to do is to refer your request to [http://www.linuxforums.org/](http://www.linuxforums.org/).

**Comment by zantinger** [comment]
Today I run in a similar issue. After install following the instruction, the tns doctor comand give me the same error as above.  I think, in my case, it was a problem with the admin user. He has a space in the name and also in the root folder. So I create a new user with admin rights in one word. I deinstall the android sdk and follow the instruction [here](http://docs.nativescript.org/start/quick-setup) again. Now when I run tns doctor I get no error.
