### ISSUE TITLE
Android : Set keyboardType/InputType to TYPE_NUMBER_FLAG_SIGNED from ListView's ItemTemplate

### ISSUE THREAD

**Issue by guillaume-roy** [NativeScript/NativeScript#1307]
Hello,

Inside a ListView's ItemTemplate i would like that a TextField accepts integers only.
And i would like to set that from XML.

Here is my piece of code :

```xml
<ListView items="{{items}}">
	<ListView.itemTemplate>
		<GridLayout rows="*,*">
			<Label text="{{name}}" />
			<StackLayout orientation="vertical">
				<StackLayout orientation="horizontal">
					<Label text="Blabla" class="secondary-text-color" />
					<TextField text="{{series}}" keyboardType="number" />
				</StackLayout>
			</StackLayout>
		</GridLayout>
	</ListView.itemTemplate>
</ListView>
```

Unfortunately in this configuration, decimal numbers are allowed. 
So, i tried to add :
* `android.inputType="TYPE_NUMBER_FLAG_SIGNED"`
* `android.inputType="4096"`
* `android.inputType="android.text.InputType.TYPE_NUMBER_FLAG_SIGNED"`

But in each case, it's not working.

How can i achieve that ?

Regards,
Guillaume

**Comment by guillaume-roy** [comment]
Hi,

No one have an idea about that ?

Regards

**Comment by bradmartin** [comment]
Currently the TextField on android is the native 'android.widget.EditText' so you can use the method below.
             
    setInputType(int type)

This is straight from memory so it might be a little off, but you need to get the element 'TextField' in your .js code. What I would do is:

    if (app.android) {
        var txtField = page.getViewById('textfieldNumber');
         txtField.setInputType(android.text.InputType.TYPE_NUMBER_FLAG_SIGNED);
    }

Again I haven't tried tis so it could need tweaking but from what I've read in the documentation http://developer.android.com/intl/zh-tw/reference/android/text/InputType.html#TYPE_MASK_FLAGS it is something like this. You could also get the element (textfield) a few other ways but this seemed fairly simple.

**Comment by N3ll** [comment]
@guillaume-roy , I tried @bradmartin's solution and it is working fine. I just wanted to add that you can also use the **loaded** event of the **TextField** and set the input type there.

**Comment by guillaume-roy** [comment]
Hi, thank you for your answers. I'll try it today.
