### ISSUE TITLE
Nativescript sandbox environment 

### ISSUE THREAD

**Issue by emmanuelbuah** [NativeScript/NativeScript#1308]
I just reviewed siphon https://getsiphon.com/ and their workflow certainly take something that looks complex and makes it amazingly easy. What makes siphon so easy to build react-native apps is their sandbox environment on their phone. Nativescript already has an great cli tool. Add a mobile sandbox environment up the simplicity of creating, prototyping and deploying an application.

**Comment by NathanaelA** [comment]
@emmanuelbuah - that is an interesting concept.  I believe the commercial Telerik side has the NativeScript app that works similarly for building and testing using their appbuilder without having the xcode or android tools installed.   .So they probably won't bring it to the free side.

However, once you add my liveedit plugin to a project; this system would be way slower for at least the entire development side of things..

**Comment by NathanaelA** [comment]
I should also add that their is some significant downsides to siphon; so much that you would want to once you have developed the app install xcode/android tools to build a release version of your app for you to distribute.

**Comment by ErjanGavalji** [comment]
@emmanuelbuah, I believe Siphon is a direct analogue to the [AppBuilder Command-Line Interface] (http://www.telerik.com/platform/appbuilder/command-line-interface) (as @NathanaelA perfectly pointed out).

What AppBuilder offers more to its customers is the ability to use the full capabilities of its IDE when needed as well as all the benefits of the surrounding platform - all available for turning on at the right time your business needs them.
Oh, and I almost forgot the best industry-wide support practices Telerik are famous with.

I hope this helps. Shall you have more questions regarding Telerik AppBuilder (or the Telerik Platform), please, do not hesitate to [contact me directly](https://twitter.com/erjitka).
