### ISSUE TITLE
.minWH600.<ext> only works for xml ?

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#1309]
Hi, I'm trying the responsive layout and its only works for xml ? Not for .js ?

Thanks

**Comment by enchev** [comment]
Indeed this will work for XML and CSS files only however you can specify `codeFile` for this page. For example:
```XML
<Page codeFile='~/some-js-file'>
...
</Page>
```

**Comment by x4080** [comment]
Oh cool, related question if you dont mind, it seems different in ios and android? In android it depends on the orientation and ios on the device resolution?
