### ISSUE TITLE
Images Android vs. IOS

### ISSUE THREAD

**Issue by lelong37** [NativeScript/NativeScript#1312]
For some reasons, images are loading in perfectly for Android and only sometimes if any on IOS, both are running the exact same code base (viewModels and views). At random they are loading and disappearing when you post right past where there suppose to be slowly. IOS behavior is consistent when running from tns emulator or directly running platform/ios folder from XCode.

Android | IOS
------------ | -------------
![image](https://cloud.githubusercontent.com/assets/4691404/12063832/3fbd4466-af7b-11e5-8e7e-1174655265bc.png) | ![image](https://cloud.githubusercontent.com/assets/4691404/12063951/04d00486-af7d-11e5-9132-562b658000f1.png)

* Android shows up just fine
* IOS usually shows nothing sometimes render images based on scrolling past where the image should load and then back up over it.

Implementation:

```js
var viewModel = new observable.Observable({
    myItems: new observableArray.ObservableArray([])
});

exports.pageLoaded = function pageLoaded(args) {
    var page = <page.Page>args.object;
    page.bindingContext = viewModel;


    http.getJSON("https://www.reddit.com/.json")
        .then(
        (result: any) => {
            console.log("json", JSON.stringify(result.data.children));

            result.data.children.map((x) => {
                x.data.thumbnail = x.data.thumbnail.replace("http://", "https://");

                (<any>viewModel).myItems.push(x.data);
            });
            // (<any>viewModel).myItems.push(result.data.children);
        },
        (error) => {
            console.log(error);
        });
    }
}
```

```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="pageLoaded">
    <Page.actionBar>
        <ActionBar title="Le's Reddit App">
            <ActionBar.actionItems>
                <ActionItem text="Next" tap="{{ nextPage }}" ios.position="right" />        
            </ActionBar.actionItems>
        </ActionBar>
    </Page.actionBar>
    <Image src="http://www.google.com/images/errors/logo_sm_2.png" stretch ="none" />
    <ListView id="myList" items="{{ myItems }}">
        <ListView.itemTemplate>
            <StackLayout>
            
                <Image src="{{ thumbnail }}" stretch="fill" />         
                <Label text="{{ title }}" textWrap="true" />
                    
            </StackLayout>
        </ListView.itemTemplate>        
    </ListView>                               
</Page>
```

**Comment by N3ll** [comment]
@lelong37, can you post which version of {N} you are using and what device exactly you are testing? I tried your code in iOS simulator and it is working the same way as in Android GenyMotion simulator.

**Comment by sitefinitysteve** [comment]
@lelong37 Dont want to put words in LongLes mouth but he updated this in Slack
" it’s working now, think i had to predefine the image size with css for ios"

**Comment by lelong37** [comment]
@N3ll, (thanks) @sitefinitysteve is correct, I'll go ahead and close this one out...

**Comment by hshristov** [comment]
@lelong37 @sitefinitysteve One subtle difference between Android and iOS ListView is that in iOS Image should have specific size or be loaded from resource otherwise loading image after Image element is shown does not refresh the ListView. This is platform limitation that we cannot fix.
