### ISSUE TITLE
Any processMessages type functionality

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#1315]
Ok, so I'm starting up my application and I'm doing a lots of file, database and raw data processing on startup and once it is all done I switch to the main screen from the startup progress screen.   However, even though I am updating the status label and progress bar; you do NOT see any of the changes because of course the main thread has been so busy doing all its work that it never actually had a chance to pass control back down to the android layer apparently to update the screen.  (I haven't tried this on iOS yet)    Since we don't have background thread ability yet; Is their any way I can force the android runtime to run and update the screen or do I have to split everything up into really small functions that I can then use setTimeout's so that their is a break between each one?

**Comment by x4080** [comment]
What if the background process using native android library?

**Comment by NathanaelA** [comment]
Actually, I might have to go that way in the future since it is so intensive.  But for the prototype I'd rather not write Java and ObjectiveC code if I don't have too.   :-)       

So in the meantime, in all my exploring I haven't seen anything like this; but there might be a feature somewhere deep in the Runtimes that will allow me to push out of the JS VM back into the Android NDK/Java level and get the screen updated...

**Comment by x4080** [comment]
Yea actually i suggested that sonehow there is 2nd javascript in the background it will be very helpful

**Comment by NathanaelA** [comment]
I'm pretty sure a feature to force the runtimes to update the screen (or actually suspend the JS runtimes and make the Android/iOS handle their message loops) is something that doesn't exist; but I figured it couldn't hurt to ask.  

@x4080 Having a background thread (which also would solve this, is bug report #85 ); as you can see  many people have commented on it.   I'm hoping that more people will +1 it so that it will become the top issue.  :grinning:

**Comment by x4080** [comment]
Actually i wrote the last comment there :)

**Comment by N3ll** [comment]
This issue was moved to NativeScript/android-runtime#324

**Comment by N3ll** [comment]
This issue was moved to NativeScript/ios-runtime#465
