### ISSUE TITLE
Can't set ActionItem font color

### ISSUE THREAD

**Issue by RusEu** [NativeScript/NativeScript#1316]
I have this actionbar and i want to change his background color and the font text color but the actionitem text color doesnt change.I tryed to set an class to the actionitem element but will no work.
```html
<ActionBar title="DROUPY" style="background-color:#000;color:#f8f8f8">
      <ActionBar.actionItems>
        <ActionItem text="BACK"  ios.position="left"/>
        <ActionItem text="SETTINGS" ios.position="right"/>
      </ActionBar.actionItems>
    </ActionBar>
```

**Comment by N3ll** [comment]
When you set the color property, in **iOS** it will affects the color of the title and the action items. In Android, the color property affects only the title text. However, you can set the default color of the text in the action items by adding an actionMenuTextColor item in the Android theme (inside App_Resources\Android\values\styles.xml).

**Comment by ajkula** [comment]
Hello enchev, could you be a bit more precise?
I believe it should be somehow similar and below : 
       ` 
    <style name="NativeScriptToolbarStyleBase" parent="Widget.AppCompat.Toolbar">
        <item name="android:background">@color/ns_primary</item>
        <item name="theme">@style/ThemeOverlay.AppCompat.ActionBar</item>
        <item name="popupTheme">@style/ThemeOverlay.AppCompat</item>

    </style>`

but then how ?

**Comment by Saadoosh8** [comment]
```
simply add the following line to your app/App_Resources/Android/values/styles.xml  file:

<item name="android:textColorSecondary">#fff</item>

or by refrencing a color in your colors.xml file as following:

<item name="android:textColorSecondary">@color/{YOUR_COLOR_NAME}</item>

-------------------------------------------------------------

 NOTE: add it inside the AppThemeBase, it will look like the code below:

   <style name="AppThemeBase" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="toolbarStyle">@style/NativeScriptToolbarStyle</item>
        <item name="colorPrimary">@color/ns_primary</item>
        <item name="colorPrimaryDark">@color/ns_primaryDark</item>
        <item name="colorAccent">@color/ns_accent</item>
        <item name="android:textColorSecondary">@color/{YOUR_COLOR_NAME}</item>
   </style>
```

**Comment by vtjon** [comment]
Sorry to reopen this but I'm having the same problem. actionMenuTextColor does not seem to work. If I set the secondary color, it works but then makes the clear button on my search bar the same color. Thoughts?

**Comment by spogulis** [comment]
Putting `<item name="android:actionMenuTextColor">#fff</item>` under `<style name="AppThemeBase" parent="Theme.AppCompat.Light.NoActionBar">` worked for me. Using {N} with Vue.
