### ISSUE TITLE
Issues w/ uiDebug on $ tns android run --emulator

### ISSUE THREAD

**Issue by DenverCoder-9** [NativeScript/NativeScript#1317]
I am trying to get the sample-Groceries app to run on my Macbook. I've followed all of the Installation instructions and have verified that TNS Doctor returns no issues, my Android SDK is installed, I've configured a virtual device, and setup the correct paths for ANDROID_HOME. but I still cannot successfully run an app. 

My issue seems to come back to a process called uiDebug, I'll get to about 80% and then it fails every single time. I'm not very familiar with Java, hence the reason I'm trying to use NativeScript so I don't have a clue how to fix it. 

Here is the output I see: 

```
:dexNativescript-telerik-uiDebug

Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:

Unknown source file : com.android.dex.DexException: Multiple dex files define LJsDebugRun;

Unknown source file : at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)

Unknown source file : at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)

Unknown source file : at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)

Unknown source file : at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)

Unknown source file : at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)

Unknown source file : at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)

Unknown source file : at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)

Unknown source file : at com.android.dx.command.dexer.Main.run(Main.java:246)

Unknown source file : at com.android.dx.command.dexer.Main.main(Main.java:215)

Unknown source file : at com.android.dx.command.Main.main(Main.java:106)



:dexNativescript-telerik-uiDebug FAILED



FAILURE: Build failed with an exception.



* What went wrong:

Execution failed for task ':dexNativescript-telerik-uiDebug'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

```

I am completely out of ideas so any help someone could offer would be greatly appreciated. 

I have done a little bit more digging and I can see in the merger.xml file the following info:

<dataSet config="nativescript-telerik-uiDebug"><source path="/Users/DenverCoder/Dev/nativescript/sample-Groceries/platforms/android/src/nativescript-telerik-uiDebug/assets"/></dataSet>

I attempted to checkout /Users/DenverCoder/Dev/nativescript/sample-Groceries/platforms/android/src/nativescript-telerik-uiDebug/assets and it does not exist.

I do not have this directory: nativescript-telerik-uiDebug so the assets directory is unavailable and I presume this is where my error begins...

**Comment by DenverCoder-9** [comment]
I have done a little bit more digging and I can see in the merger.xml file the following info:

```<dataSet config="nativescript-telerik-uiDebug"><source path="/Users/DenverCoder/Dev/nativescript/sample-Groceries/platforms/android/src/nativescript-telerik-uiDebug/assets"/></dataSet>```

I attempted to checkout /Users/DenverCoder/Dev/nativescript/sample-Groceries/platforms/android/src/nativescript-telerik-uiDebug/assets and it does not exist. 

I do not have this directory: nativescript-telerik-uiDebug so the assets directory is unavailable and I presume this is where my error begins...

**Comment by N3ll** [comment]
This issue was moved to NativeScript/nativescript-cli#1370
