### ISSUE TITLE
iOS on Navigate, UI visibility bindings are too slow

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#1318]
BASIC sample app...
https://www.dropbox.com/s/jnzrx3jlffclshq/slow-load.zip?dl=0

Seems fine on android, terrible on iPad, iPhone and simulator

So it's like on nav click it brings in all of the rendered UI elements, THEN the visibility bindings are applied for elements to hide or show.  So like as the "Page" moves in you just see everything before pageLoad runs (can see in the sample)

I have this basic idea all through my app and the end result is just sloppy looking, so so bad.  Not just things like showing a label if there's no listview items, but like toggle an actionbar icon.

**Comment by sitefinitysteve** [comment]
Will close, can get around by using navigatingTo... thanks @NathanaelA 

ALTHOUGH since it works just fine in pageLoaded on android, would be nice if iOS was the same

**Comment by kmuthukrishnan** [comment]
Hi @NathanaelA, " sitefinitysteve, Iam facing the same issue. Can you please give me a bit more detail on what you did to fix this.

**Comment by NickIliev** [comment]
@kmuthukrishnan you need to use the navigationTo event like this:
**_page.xml_**
`<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="onNavigatingTo">`

**_page.ts_**
```
export function onNavigatingTo(args) {
   // implement your visibility binding logic here so when the page navigates to the new one the binding is already set
]
```

There is a set of Page related events which you can use like
```
navigatedTo
navigatedFrom
navigatingTo
navigatingFrom
loaded
unloaded
```

More about the page events [here](http://docs.nativescript.org/api-reference/classes/_ui_page_.page.html)

**Comment by kmuthukrishnan** [comment]
Thanks @NickIliev. Just wanted to check if this approach will work in a angular 2 nativescript project?

**Comment by NickIliev** [comment]
@kmuthukrishnan yeah absolutely! 
In fact, there are many occasions where you will still work with the NativeScript events instead of the Angular lifecycles as the {N] events will assure that you are handling the logic working directly with the loaded native views at the right moment.

**Comment by kmuthukrishnan** [comment]
Hi, 
Thanks @NickIliev. If you could direct me to any sample project for NativeScript - Angular 2 where this is implemented it would be helpful.
