### ISSUE TITLE
Telerik UI free trial message with only RadSideDrawer

### ISSUE THREAD

**Issue by jaysson** [NativeScript/NativeScript#1319]
I read that RadSideDrawer is free. But I get trial alert like this:
<img width="639" alt="screen shot 2016-01-03 at 1 10 40 pm" src="https://cloud.githubusercontent.com/assets/1563862/12077789/b101d7fc-b21b-11e5-8e92-8b38d6fceb64.png">

I followed instructions at http://docs.telerik.com/devtools/nativescript-ui/Controls/SideDrawer/sidedrawer-getting-started

**Comment by Epotignano** [comment]
Urgent please! I have exactly the same problem!
+1

**Comment by karaahmed** [comment]
The NativeScript UI npm package updated with fix of this issue. 
Please, upgrade to the latest ver. 0.2.2.

**Comment by Epotignano** [comment]
Still I'm getting the same error even after update the library

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

2016-01-04 9:58 GMT-03:00 Bulent Karaahmed <notifications@github.com>:

**Comment by jaysson** [comment]
Works fine for me after the update.
