### ISSUE TITLE
How do I select a Listview item programmatically? 

### ISSUE THREAD

**Issue by stevetayloruk** [NativeScript/NativeScript#1327]
Hi,

I have a listview with bound items and I want to make the first one selected by default. Similar to a dropdown list in html where you have a selectedItem or selectedIndex property.  The listview doesn't seem to have such a property or method.

thanks

Steve

**Comment by N3ll** [comment]
Hi Steve, the selection is not supported currently. What you can do is to define a CSS class to define the style of the selected item. You can check this [gist](https://gist.github.com/N3ll/575d04fc16714e9e62d5) for inspiration. To achieve your scenario the only thing that you will have to add in the **main-view-model.js** is an **if statement**. In it the **isSelected** property of the first element will be set to true, thus the first element will be styled as selected.

**Comment by stevetayloruk** [comment]
Hi Neli,

Thanks, yes this is what I have already but seems a bit hacky. 

Steve
