### ISSUE TITLE
Adding own code in xcode

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#1331]
Hello, if I wanted to use objective C or swift, can I just add source in the xcode's project ? Or I have to use cocoapod ?

Thanks

**Comment by ivanbuhov** [comment]
Although it is technically possible to [embed Objective-C or Swift code directly in the Xcode project](https://github.com/NativeScript/sample-iOS-StaticLibs#user-content-consuming-objective-c-code-in-the-project) and consume it from JavaScript, it requres manual changes in `platforms/ios` folder, which is not recommended. The recommended approach is to wrap your source code in [NativeScript plugin](http://docs.nativescript.org/plugins/plugins). If you prefer not using CocoaPods you can add prebuilt library in the plugin. 
> Bare in mind that you can consume Swift APIs [only if they are exposed to Objective-C](https://github.com/NativeScript/ios-runtime/issues/257#issuecomment-133451921).

**Comment by x4080** [comment]
Thanks
