### ISSUE TITLE
Listview doesn't seem to measure properly with padding

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#1333]
https://groups.google.com/forum/#!topic/nativescript/s-eBakiLjqU

Just bind the listview to a few items with long titles, give the internal ListView.itemTemplate stacklayout some top\bottom padding.

Only fix I can see right now is to turn the listview into a repeater in a scrollview...

**Comment by enchev** [comment]
Hey @sitefinitysteve,

Do you still need help with this?

**Comment by sitefinitysteve** [comment]
Okay well... I mean the problem still exists TECHNICALLY... however @N3ll  gave me the fix.  So if the listview is not in a grid then it doesn't measure the padding when rendering the list items (like lets say there's only 5 items and the list doesnt occupy the entire screen).  However in that case the UI is super gimpy, so shouldn't be that way anyway.
