### ISSUE TITLE
animation scale with anchor

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#1334]
hello, can we specify anchor for scaling? now its the center I believe

**Comment by PanayotCankov** [comment]
There are two properties available currently in master:
https://github.com/NativeScript/NativeScript/blob/master/ui/core/view.d.ts#L265
https://github.com/NativeScript/NativeScript/blob/master/ui/core/view.d.ts#L270
I think these should be available with the latest version of the modules.

**Comment by x4080** [comment]
Cool
