### ISSUE TITLE
gridlayout like child but behave like absolutelayout

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#1336]
Gridlayout is best for auto sizing the view, but the downside is it anchored to the origin, if we want to move the view, it will go back as soon as layout refreshes, can we get the auto sizing and the custom location like absolutelayout? its very useful for animating the view, maybe absolutelayout with percentage size like in the one of the issue?

**Comment by hshristov** [comment]
Hi @x4080,
I'm not sure what do you mean by `it will go back as soon as layout refreshes`. Could you elaborate more?

Will `translateX` and `translateY` properties help?

**Comment by x4080** [comment]
Hi, for example I wanted to create full screen view that can be auto resize when rotate, but I want it to be starts at y position 100, If I use padding or margin it won't be full screen anymore since I want it to slide up like paralax effect :) I know specific thing .but it just example case 

So it will be cool if it can be like absolute layout but size can be 100%

**Comment by x4080** [comment]
Ok, now I know the problem is : 
- translateX is started at the view original position (not after a translateX position)
- the same is for view.animate translateX 
- Using the pan gesture to remember the latest position when using a variable, ex : currentX, have the problem with there's no "touchup" gesture to save the translateX position to currentX position

new question : can we get the "touchup" gesture after the pan gesture released ?

Sorry for the confusion, because at first I dont really know the problem that I have :)

**Comment by x4080** [comment]
Solve it, must use 1.5.1

**Comment by x4080** [comment]
Hi, I can pinpoint exactly what happened, if we move a view in a grid layout , then the device is rotated, it will back to the original position and any more move started from this position instead of from the original position

Movement means translate and animation. Only happens on ios. Android works great , that's what I confused about before

**Comment by x4080** [comment]
Oh and not sure within other layouts, only try it in grid layout
