### ISSUE TITLE
Ios and Android pageloaded

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#1337]
Ios goes to home screen, no pageloaded event fired . but Android does, can Android behave like ios ? I think it will load much faster when returning back to application

**Comment by enchev** [comment]
Can you post more info about your scenario? I've checked both Android and iOS and loaded event of the Page will be fired only when the page is loaded not when you press the HOME button of the device.

**Comment by enchev** [comment]
Ok. I see your point now after I've found your other issue:
https://github.com/NativeScript/NativeScript/issues/1295
You are right. Currently `loaded` and `unloaded` events are not fired correctly in iOS when the application enters to or resumes from background and we need to fix this. 

Can you post more info why however you do not want these to be fired? Do you have some long running code in the event handlers?

**Comment by x4080** [comment]
Sorry @enchev , I didnt know you move the question here, I kinda like the ios version of loaded and unloaded, because when destroy and recreating views after resuming app, it will add complexity with the native view changes and can be slower when we need to load something onloaded, but it will always called with this scenario

I think the best solution is if there is an optional destroy/recreate when app resume ? I think native app not destroy/recreate views ?

**Comment by NathanaelA** [comment]
@x4080 actually destroyed and recreated views is pretty standard for Android.  The os will decide depending on how much memory your phone has on if it will destroy a app going in the background.  On some phones with lots of memory the activity might not be destroyed when in the background.

Don't forget their the onnavigatedto event which should only be fired once; and you can load your data there...

**Comment by x4080** [comment]
Isnt it the view destroyed only when the memory is low? If we open app and go to home screen and go back shouldnt the view still there and not already recreated? 

And thanks for the event tip

**Comment by hshristov** [comment]
Hi @x4080,

Android recreates view when you navigate between them. We try to be as close to the platform as possible so when you navigate from page 1 to page 2, we destroy all native views (unless `topmostFrame().android.cachePagesOnNavigate = true`).

When application is suspended it may be stopped depending on the available memory like @NathanaelA said. So we destroy views only when Activity `onDestroy` event is fired or when we have navigation.

**Comment by x4080** [comment]
I think in Android, it always get called, if we open app, go to home, back again, pageloaded and unloaded is called
