### ISSUE TITLE
Question: How to set maxlength on textField?

### ISSUE THREAD

**Issue by gaurav-chandra** [NativeScript/NativeScript#1338]
How to set maxlength on textField?

android.widget.TextView has an xml declaration android:maxLength. How to convert this to XML UI of nativescript?

**Comment by gaurav-chandra** [comment]
Solved it after hitting my head on the keyboard and google
```
var phoneField = view.getViewById(page,'phoneField');
    var fArray = [];
    fArray[0] = new android.text.InputFilter.LengthFilter(10);
    phoneField.android.setFilters(fArray);
```

**Comment by PieterAelse** [comment]
And on iOS?..

**Comment by PetyaSotirova** [comment]
@PieterAelse take a look at this feature request https://github.com/NativeScript/NativeScript/issues/3614.
