### ISSUE TITLE
Activity indicator style

### ISSUE THREAD

**Issue by dkallkro** [NativeScript/NativeScript#1339]
Please allow setting the style and color of the Activity indicator style in the XML.

it is static now
this._ios = UIActivityIndicatorView.alloc().initWithActivityIndicatorStyle(UIActivityIndicatorViewStyle.UIActivityIndicatorViewStyleGrey);

We use "WhiteLarge" and have to remember to change when you update the controls

**Comment by enchev** [comment]
You can do this even now:
```XML
<Page style="background-color: red">
    <ActivityIndicator ios.activityIndicatorViewStyle="0" busy="true" />
</Page>
```

**Comment by nicolam1** [comment]
what are the possible values for the ios property?
