### ISSUE TITLE
In-call status bar is not handled appropriately (on iOS)

### ISSUE THREAD

**Issue by speigg** [NativeScript/NativeScript#1342]
Depending on whether the in-call status bar is triggered while is app is running, or if the app is launched while the in-call status bar is active, the page view is displayed incorrectly (with a gap) or the page view moves with a jarring movement when the in-cal status bar is activated, or both.

**Comment by hshristov** [comment]
Is this the same issue like that - https://github.com/NativeScript/NativeScript/issues/659

**Comment by speigg** [comment]
Ah, yes.
