### ISSUE TITLE
Button background color styling affects entire button style

### ISSUE THREAD

**Issue by andreyluiz** [NativeScript/NativeScript#1343]
I'm working around the tap button example, and something I noticed is when I set the background color of the button:

Before styling:
![Before](http://i.imgur.com/SFQZL1t.png)

After styling:
![After](http://i.imgur.com/dYfSrG6.png)

What happens is that the button loses all the styles. The ink on tap, the shadows, the border, everything. Is there a way to prevent this from happening? A way to just change the background color without losing the other styles?

Thank's.

**Comment by enchev** [comment]
duplicate to https://github.com/NativeScript/NativeScript/issues/1296

**Comment by andreyluiz** [comment]
:+1:
