### ISSUE TITLE
Android context issues

### ISSUE THREAD

**Issue by anarchicknight** [NativeScript/NativeScript#135]
The following lines worked with no issue a few releases ago (not sure exactly which version I was on at the time).

However, I have noticed that in the last couple of releases vibrator_service is always reported as null - any ideas?

var app = require("application");
var context = app.android.context;
var vibrator_service = context.getSystemService(context.VIBRATOR_SERVICE);

**Comment by anarchicknight** [comment]
resolved.

Had some contexts mixed up. Below works:

var app = require("application");
var context = android.content.Context;
var vibrator_service = app.android.context.getSystemService(context.VIBRATOR_SERVICE);

**Comment by priyangamani** [comment]
app.android.context is not working.How to refer the current Activity in javascript.(For Ex: MainActivity.this)
