### ISSUE TITLE
Change event on Switch

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#1353]
Can we please get a change event on Switch?

https://docs.nativescript.org/ApiReference/ui/switch/Switch

(...instead of needing to watch the model itself)

tap works, but an alert inside the tap event shows the binding hasn't changed yet, feel gimpy to set a timeout in there.

**Comment by enchev** [comment]
Hey @sitefinitysteve,

You can do this even now:
```XML
<Page>
  <Switch propertyChange="switchPropertyChange" />
</Page>
```

```TypeScript
import observable = require("data/observable");

export function switchPropertyChange(args: observable.PropertyChangeData) {
    if (args.propertyName === "checked") {
        // Your code goes here
    }
}
```

**Comment by sitefinitysteve** [comment]
Oh, is that this article?
http://docs.nativescript.org/core-concepts/events#propertychange-event

**Comment by enchev** [comment]
We do not have special article for UI components propertyChange event handling however I've added the same example in our docs:
https://github.com/NativeScript/docs/blob/production/ui/ui-with-xml.md#events

**Comment by sitefinitysteve** [comment]
That is EPIC!  This opens so many possibilities now, I have to go start refactoring some logic... 

Sidenote, Gestures and Events should be in the anchorlist there at the top... I'm also not sure the title or placement of it is the best spot.  "Events" isn't super clear what this is\does.  Can we make it more clear like Subscribing to Property changes in XML or something to that effect (and anchor list it).  I would also maybe put a link in Switch back to that as a footnote as I went to the switch docs first (Im sure most people would if they didn't know this was possible)

**Comment by IvRRimum** [comment]
How can pass my own arguments into ```switchPropertyChange()```?
