### ISSUE TITLE
Question: Why I'm only getting a white screen while the app is starting up?

### ISSUE THREAD

**Issue by gaurav-chandra** [NativeScript/NativeScript#1356]
Why I'm only getting a white screen while the app is starting up? When I click on launcher icon, I get a white screen for sometime and then my application shows.

**Comment by enchev** [comment]
Is this for Android or iOS? Or both?

**Comment by gaurav-chandra** [comment]
I develop for Android so I have checked it for Android only.

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#332
