### ISSUE TITLE
Iterate over array of arrays and create a Grid

### ISSUE THREAD

**Issue by andreyluiz** [NativeScript/NativeScript#1358]
How can I iterate over an array of arrays and create a structure with a Grid format?

For example, if I have:

```
[[1,2,3],[4,5,6],[7,8,9]]
```
Create a structure of buttons (probably with a GridLayout) like this:

```
1 2 3
4 5 6
7 8 9
```

I know it is possible by code. But is there a way to do this in xml?

Thank's.

**Comment by enchev** [comment]
Hey @andreyluiz,

You can do something similar to [Repeater and WrapLayout](https://docs.nativescript.org/ApiReference/ui/repeater/HOW-TO.html#repeater-with-wraplayout-inside-scrollview) however in this case your data should be flat: [1,2,3,4,5,6,7,8,9].

**Comment by andreyluiz** [comment]
Well, aparently this component solves my problem partially. Problem is that I need a perfect grid. And WrapLayout does not do this. Any idea if I can use Repeater with a grid layout?

**Comment by hshristov** [comment]
@andreyluiz You can use GridLayout but your items should have property which specify in which row/col item should be placed.

**Comment by andreyluiz** [comment]
That's exactly what I done. I have a perfect grid now. Thank's for the help @hshristov @enchev.
