### ISSUE TITLE
Cross platform animation-timing-function / easing

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#1363]
Consider the following articles about the CSS3 animation-timing-function:

 - [mozilla web css timing-function](https://developer.mozilla.org/en-US/docs/Web/CSS/timing-function)
 - [w3schools animation-timing-function](http://www.w3schools.com/cssref/css3_pr_animation-timing-function.asp)

Consider exposing cross platform abstraction for as much as possible from the CSS3 easing functions. The **linear**, **ease-in**, **ease-out**, **ease-in-out** should be easily achieved since they are defined as constants in iOS and there are corresponding [Accelerate/Decelerate/AccelerateDecelerate Interpolators](http://developer.android.com/reference/android/view/animation/BaseInterpolator.html) in android.

**besier-curve** for iOS have a reference in [CAMediaTimingFunction](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/CAMediaTimingFunction_class/#//apple_ref/occ/clm/CAMediaTimingFunction/functionWithControlPoints::::) but it is available in CoreAnimation API instead the UIKit we are using. It will require further investigation if we can use CA instead UI animations. For android [PathInterpolator](http://developer.android.com/reference/android/view/animation/PathInterpolator.html) with [Path](http://developer.android.com/reference/android/graphics/Path.html) and  the ["cubicTo"](http://developer.android.com/reference/android/graphics/Path.html#cubicTo(float, float, float, float, float, float)) API to draw the besier curve.

**steps** looks impossible for iOS, can be achieved with [PathInterpolator](http://developer.android.com/reference/android/view/animation/PathInterpolator.html) for android. Since it does not really look like a true animation I guess we can ignore it anyway.

**bounce/spring** are desirable but it seems some of them can be achieved only by using multiple keyframes with adequate besier timing functions in iOS.

**Comment by x4080** [comment]
I think we need bounce/spring animation in ios/android, in ios can we use :

```
animateWithDuration:delay:usingSpringWithDamping:initialSpringVelocity:options:animations:completion:
```

And I see @ the source code, ios animation keyframe option is not using the right option, maybe its not used like it intended to do ? The options should be :

```
Linear: makes the animation go from one point to the next, through each point in between.
Discrete: makes the animation leap directly from one point to the next. This option is presumably useful when you are specifying each frame in an animation
Paced: makes the animation "evenly paced", whatever that means. It seems to make it ignore either the start time or duration of the key frames, but not in a predictable way, so I'm not sure why you'd want to do that.
Cubic: uses the default Catmull-Rom spline (me neither) to interpolate between the keyframe values. Basically this smooths out any rough edges created by your key frame points.
Cubic paced: a cross between Cubic and Paced.
```

and not UIViewKeyframeAnimationOptionBeginFromCurrentState like in animation.ios.ts

But then again it still using setAnimationCurve and not from the above options

**Comment by PanayotCankov** [comment]
You are right.
I will check if the easing is applied at the moment.

We wouldn't use keyframe animations here, but we have problems with a particular case where an animation is applied and a view was moved from one point to another, but half way the animation, it is interrupted by a second animation that wants to move it to a third point. The `animateWithDuration:delay:options:animations:completion:` has the `EaseInOut, EaseIn, EaseOut, Linear` easing but when its `UIViewAnimationOptionBeginFromCurrentState` was set it couldn't handle well when 2 out of the three translation, rotation and scale were set. It looked like the transformation matrix was not properly decomposed when the second animation starts and the view jumps before the second animation. We may be forced to provide a `continue from current state` like option and switch between the 3 APIs based on this and the animation easing:
```
animateWithDuration:delay:options:animations:completion:
animateKeyframesWithDuration:delay:options:animations:completion:
animateWithDuration:delay:usingSpringWithDamping:initialSpringVelocity:options:animations:completion:
```
Or switch to CoreAnimation completely and animate the UIView's layer.

**Comment by x4080** [comment]
I see, is it related to using JavaScript instead of objective c? Or is it the bug in animation api?

**Comment by PanayotCankov** [comment]
The problems we had that made us use the keyframes API are reproducible in pure Objective-C app.

**Comment by x4080** [comment]
Oh wow, thats quite a bug for iOS

**Comment by PanayotCankov** [comment]
@tzraikov Did splendid job on this one. We now have support of besier and spring curves as well the animations can begin-from-current-state.

**Comment by x4080** [comment]
spring for both?

**Comment by PanayotCankov** [comment]
@x4080 I think in android he uses BounceInterpolator. You can check the PR, referred above. Feedback is welcomed. If you find problems please open a new issue. :)

**Comment by x4080** [comment]
Nice, since we in the topic, I found that if we move or animate view in ios then a rotation occurs, the view position is back to before move or animation. Which didn't happened in Android, will this fix this problem too?

**Comment by x4080** [comment]
I guess not, tried it in 1.6

**Comment by PanayotCankov** [comment]
@x4080 @tzraikov Is working on the animations. This may be fixed, but please open new issues when you find new problems. This issue is now closed.

**Comment by x4080** [comment]
Ok
