### ISSUE TITLE
GridLayout inside iOS ActionBar 

### ISSUE THREAD

**Issue by tiagordc** [NativeScript/NativeScript#1369]
Whenever I try to use a GridLayout inside the titleView of the ActionBar I get an error:
file:///app/tns_modules/ui/layouts/grid-layout/grid-layout.js:120:40: JS ERROR TypeError: undefined is not an object (evaluating 'this.helper.columns')

Any other layout will work fine

**Comment by vakrilov** [comment]
@tiagordc 
I tried, but could not reproduce the error. Here is the XML I tested width:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="pageLoaded">
    <Page.actionBar>
        <ActionBar title="test">
            <ActionBar.titleView>
                <GridLayout>
                    <Label text="Here be title!"/>
                </GridLayout>
            </ActionBar.titleView>
        </ActionBar>
    </Page.actionBar>
  <StackLayout>

  </StackLayout>
</Page>
```

Can you share XML of you page so that we can investigate.
