### ISSUE TITLE
ObservableArray.length is read-only

### ISSUE THREAD

**Issue by thokrae** [NativeScript/NativeScript#137]
It's a common practice to empty arrays in JavaScript by setting the length property of the array to zero.
This is not possible when using an array wrapped with ObservableArray in NativeScript because ObservableArray.length is a read-only property.

Maybe this is intended behavior but it might confuse some JavaScript developers.

```javascript
var observableArray = require("data/observable-array");

var tasks = new observableArray.ObservableArray([]);
tasks.push({ name: "foo" });
tasks.length = 0;
// tasks still contains one element at this point
```

**Comment by pitaj** [comment]
But you can just reinitialize the OA with an empty array to empty it, right?

However, this could be more computationally expensive. A simple `.empty()` method added to that class would be better.

**Comment by thokrae** [comment]
Yes, or you could do
```javascript
tasks.slice(0, tasks.length);
```

My point is that many JavaScript developers are used to setting the length to zero, so it would reduce confusion if ObservableArray would mimic this behavior.
But maybe my assumption that ObservableArray is supposed to behave like an ordinary array is wrong.
