### ISSUE TITLE
Clojurescript tanspiler

### ISSUE THREAD

**Issue by lxsameer** [NativeScript/NativeScript#1370]
Hi,
Is there any transpiler for clojurescript ? If no I like to write one,  I read about nativescript's transpilers and read typescript transpiler source code and i have several questions:

1) where should put the compiled source code ?
2) where can i find more info about transpilers ?
3) what hooks should I write in order to support cljs in nativescript?

Thanks

**Comment by enchev** [comment]
Hey @lxsameer,

We don't have yet clojurescript transpiler! You can check Less and Jave transpilers for more info:
https://github.com/NativeScript/nativescript-dev-less
https://github.com/NativeScript/nativescript-dev-jade

Both transpilers will place the new file next to the original file. You will need only [before-prepare hook](https://github.com/NativeScript/nativescript-dev-jade/blob/master/package.json#L11).

**Comment by lxsameer** [comment]
won't it be big ? I mean a compiled js file next to it's clojurescript file  ?  is it possible to force nativescript to use an other directory instead of `app` ? so we can hold clojurescripts inside app and the generated source tree in side a new directory and put that directory inside `.gitignore`

**Comment by NathanaelA** [comment]
The app folder is where the JS needs to be.  If you want to move the closure code into another folder that is fine; but NativeScript's primary folder is the app folder; and that is what is actually built into the app.    

Another example of a transpiler is the nativescript-dev-typescript also.   All three of them I believe use the nativescript-hook library which allows you to easily hook into the nativescript command.

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#1393
