### ISSUE TITLE
Firebase plugin Fail on IOS 9.2 ( XCode 7.2 )

### ISSUE THREAD

**Issue by wisonye** [NativeScript/NativeScript#1372]
Before I upgrade to IOS 9.2( XCode 7.2 ), everything is fine, but my Iphone upgrade to IOS9.2, then I also update to new XCode, after I upgraded, seems some plugins not work, for example "firebase", right now cannot run, the error looks like this:

```javascript
=== BUILD TARGET NativeScriptProject OF PROJECT NativeScriptProject WITH CONFIGURATION Debug ===

Check dependencies
CodeSign error: entitlements are required for product type 'Application' in SDK 'Simulator - iOS 9.2'. Your Xcode installation may be damaged.

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
Command xcodebuild failed with exit code 65
# run ios

```

If I remove the plugin it can open fine( but of course my app will crash when running the firebase part ):

```javascript
tns plugin remove nativescript-plugin-firebase
```

I've already modified the Pod file to use latest version of firebase( 2.5.0 ), still not work, any help on this :(

**Comment by enchev** [comment]
This issue was moved to EddyVerbruggen/nativescript-plugin-firebase#6
