### ISSUE TITLE
Use PubNub with NativeScript?

### ISSUE THREAD

**Issue by shantamg** [NativeScript/NativeScript#1375]
I followed [PubNub's instructions for node.js](https://github.com/pubnub/javascript/tree/master/node.js) and tried using it in my {N} project...

When trying to require pubnub, I get:

    Error: Failed to find module 'https' relative to 'file:///app/tns_modules/pubnub/node.js/pubnub.js'. Computed path: 'app/tns_modules/https.js'.

Any ideas, or is it way to ambitious to assume this could work?

**Comment by NathanaelA** [comment]
No https module.  You might be able to modify the pubnub code to use the NativeScript http module.   But their maybe other dependencies missing.

**Comment by shantamg** [comment]
Ah, I see. Thanks for the quick reply! I can probably do without https as you suggest.
The only other dependency is **crypto**. I can see that in #195 this is being requested... Do we know what the status of this is?

**Comment by NathanaelA** [comment]
Sorry, nobody has touched crypto yet.

**Comment by shantamg** [comment]
Ok, assuming I could bypass crypto, how would I reference the NativeScript http module? The pubnub file is in `node_modules/pubnub/node.js/pubnub.js`. Right now it's like this: `require('http')`, but is there a way to reference the NativeScript http module?

**Comment by NathanaelA** [comment]
Actually var http = require('http');  should be correct; however the http module in NS is  alot different than the HTTP module in node.  So you might have to write a wrapper of sorts; depending on what you need from http.

**Comment by shantamg** [comment]
[@antonybello](https://github.com/antonybello)'s [ns-chat](https://github.com/antonybello/ns-chat) app seems to work (though I need to test it more) but it looks like he has modified the pubnub.js file so it's not clear what is going on. Would be good to leave the pubnub.js file untouched and figure out a wrapper for it...
