### ISSUE TITLE
Android WebViewCoreThread

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#1376]
Hi, is ns in android using also this WebViewCoreThread? If not, we can use it to get another JavaScript thread?

**Comment by NathanaelA** [comment]
Wow, I LIKE it.   That is a really great idea!    Going to go try this right now....  :grinning:

**Comment by x4080** [comment]
i wait for your testing

**Comment by NathanaelA** [comment]
Tested on an Android 4.4 emulator and it appears like this idea will work great!  Brilliant idea!   And guess what; at least with android 4.4, we also get WebWorkers inside the WebView.  So I was running three threads.  :grinning:    The fullscreen WebView was having some issues on display while the main thread was busy in NS (which was expected); but it still updated.  It was running the non-visual code at full steam.  Now I haven't coded anything up but a simple test.  So to actually realize this idea; is going to require a bit of work to be able to setup the communication layer...   And of course you don't have access to the NS runtimes from inside WebView; so it is a limited JS environment.

**Comment by NathanaelA** [comment]
I had to go look up WW support; it looks like you have to have 4.4, webworkers weren't present in earlier versions.    But it does give us another thread.   This idea might also work for iOS, I bet there webview runs in its own thread also...

**Comment by NathanaelA** [comment]
Ok, who is up to help build a plugin for this.   I personally think we should use the WebWorker interface/model since their is lots of documentation and information on how it works for new developers and it best matches this model since the WebView thread will be a totally limited thread without any access to NativeScript other than via our communication channel.

**Comment by NathanaelA** [comment]
Hey NativeScript Android team ( @atanasovg @ErjanGavalji @Plamen5kov @slavchev @blagoev ), what is the current way to do annotations in JS code?   If you read the docs at
http://developer.android.com/reference/android/webkit/WebView.html#addJavascriptInterface%28java.lang.Object,%20java.lang.String%29
It states that for the AddJavaScriptInterface to be able to call functions from the JS bridge they need to be tagged with: @JavascriptInterface for API 17 and above...

**Comment by x4080** [comment]
@NathanaelA thanks for your testing. This will be good for ns fans like me. Hopefully ios can do the same thing and with wkwebview will run faster

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#335
