### ISSUE TITLE
Color in Page styles crashes app

### ISSUE THREAD

**Issue by stevetayloruk** [NativeScript/NativeScript#1382]
Hi,

Setting the color css property from within a Page element style on iOS crashes the app. Like so:

```
Page {
    color: white;
}
```

This would be useful to set a default text color across the app. I've had to revert to adding to a Label element.

Thanks

Steve

**Comment by enchev** [comment]
Hey @stevetayloruk,

I've just tried this and everything worked as expected on my end:

```XML
<Page style="background-color: blue;color: white">
    <Button text="Button" />
</Page>
``` 
![screen shot 2016-01-15 at 4 55 22 pm](https://cloud.githubusercontent.com/assets/5804953/12355990/e046bdf2-bba8-11e5-96c1-287df8352b1b.png)

**Comment by stevetayloruk** [comment]
I'm doing this within the app.css file. would that make a difference?  It crashes the emulator and on the device for me.

**Comment by stevetayloruk** [comment]
this is my style and as soon as i add in the color property either by name or hex it crashes.

```
Page {
    background-color: #2b282f;
    background-image: url('res://bg');
    background-size: cover;
    font-size: 20;
    font-family: "HelveticaNeue-Light";
}
```

**Comment by enchev** [comment]
I've just tried the same (except the background-image) and here is the result:
![screen shot 2016-01-18 at 9 56 20 am](https://cloud.githubusercontent.com/assets/5804953/12385962/d8ad63e8-bdc9-11e5-90fc-7128f989e113.png)

What is your {N} version? Can you send us your project to check locally what's going on?

**Comment by stevetayloruk** [comment]
updated to latest 1.5.2 and seems to be working now.

thanks
