### ISSUE TITLE
ObservableArray.push never responds

### ISSUE THREAD

**Issue by andreyluiz** [NativeScript/NativeScript#1384]
I have a view model which is an ObservableArray. I have a method called ```load``` that loads data and push it to the ObservableArray. The problem is that this push action never responds. Here's the example code with a few logs:

```
//...
var viewModel = new ObservableArray();

viewModel.load = function () {
    return fetch(config.fullUri('/updates'), {
      //...
    .then(function (updates) {
      console.log('Response!');
      console.log('Total updates: ' + updates.length);
      _(updates).each(function (update) {
        console.log('Current update: ' + update.title); <---------- It is the last log
        viewModel.push(update); <---------------------------------- It stops right here.
        console.log('Done.');
      });
      console.log('Done. Array has ' + viewModel.length + ' registers.');
    });
  };
```
The result of the logs is:
```
JS: Will load.
JS: Response!
JS: Total updates: 1
JS: Current update: My awesome update
```
The log with "Done" never prompts. I tried to debug and when I pass over the ```viewModel.push``` line, it breaks and never responds. There are no errors in the console nor errors in the application itself. The app just stay freeze (with an ActivityIndicator rotating) and nothing more. I can't imagine what is happening.

Any clues?

**Comment by enchev** [comment]
Can you try normal array in your case instead? Will it work?

**Comment by andreyluiz** [comment]
With array it works.

```
//...
.then(function (updates) {
  var simpleArray = [];
  console.log('Response!');
  console.log('Total updates: ' + updates.length);
  _(updates).each(function (update) {
    console.log('Current update: ' + update.title);
    simpleArray.push(update);
    console.log('Done.');
  });
  console.log('Done. Array has ' + simpleArray.length + ' registers.');
```
Result.
```
JS: Will load.
JS: Response!
JS: Total updates: 1
JS: Current update: Foto de uma xícara
JS: Done.
JS: Done. Array has 1 registers.
```

**Comment by andreyluiz** [comment]
I tested trying to push a single item, an entire array, with no success. The app still frozen in this particular line of code.

**Comment by andreyluiz** [comment]
Because my array is read only, I'm not using ObservableArray anymore, but just a simple array. It worked as expected.
