### ISSUE TITLE
Databinding <Button> background-color

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/NativeScript#1385]
Should setting **background-color** work with databinding? This does not work. 

      <Button text="Button" background-color="{{ vibrantRgb }}"  />
Yet, setting the **color** does work:  

      <Button text="Button" color="{{ vibrantRgb }}"  />

![backgroudn](https://cloud.githubusercontent.com/assets/6006148/12361642/fb33796c-bb84-11e5-8858-341692446839.PNG)

**Comment by advokata** [comment]
You can use class instead of inline element.

**Comment by bradmartin** [comment]
Yea, just curious if that was a bug since color works.

**Comment by enchev** [comment]
Hey folks,

background-color is actually the CSS way to set background color. The property in XML is backgroundColor of the style object:

```XML
<Button text="Button" style.backgroundColor="{{ vibrantRgb }}"  />
```
