### ISSUE TITLE
3rd party Native Android Widget missing titlebar

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#1387]
This is what the widget looks like on android
![image](https://cloud.githubusercontent.com/assets/1542376/12365135/dda03a04-bba0-11e5-89dc-9ab33fb516d4.png)

Here it is on iOS, you can see there's a Contact Us link at the top in the navbar there.
![image](https://cloud.githubusercontent.com/assets/1542376/12365152/087c78dc-bba1-11e5-8655-9c421a5e4ca5.png)

Zendesk support tells me (Quote)
"There seems to be a lack of an action bar when using Native Script. Is there a method or function you can use to display the toolbar? That's where the button would be expected."

So there's clearly no xml to define the bar, what am I to do?

**Comment by vakrilov** [comment]
@sitefinitysteve 
The default template for android uses `Toolbar` instead of `ActionBar` (as recommended by Google). Also the theme of the application inherits `Theme.AppCompat.Light.NoActionBar` for compatibility. 
That said can you please share what is you scenario and what 3rd party library aru you using.
You can create your own `contact us` button by defining `ActionItem` as shown [here](http://docs.nativescript.org/ui/action-bar#action-items).

**Comment by sitefinitysteve** [comment]
I can't make my own contact button, it's all inside their widget\view.  Like it's their component thats overlaying the screen :/

https://github.com/sitefinitysteve/nativescript-zendesk

steve@sitefinitysteve.com if you need some actual valid keys to run the plugin...

**Comment by vakrilov** [comment]
@sitefinitysteve 
I'm still not sure what the actual issue is. Can you define the "contact us" action-item as shown in the link above and show the overlay in the `tap` handler?

**Comment by sitefinitysteve** [comment]
Okay so their widget is self contained...my ns app is basically just a button that loads the above widget into view through the js.  The ios image above isnt my actionbar with a custom contactus link added...its literally all their cocoapod that animates into view overtop of what i have defined in ns.

Do you know what mean?  Even if i could have my own actionbar, i would need to manually wire up funtionality they have already created on android.

**Comment by vakrilov** [comment]
@sitefinitysteve 
From what i can see(pls correct me if I'm wrong) you show the zendesk activity [here](https://github.com/sitefinitysteve/nativescript-zendesk/blob/master/index.android.js#L35). What probably happens is that inherits the application theme which has no action-bar(`Theme.AppCompat.Light.NoActionBar`). As it is a separate activity - there should be a way to tell it to use another theme (for example `Theme.AppCompat.Light` - which should have the action bar).

**Comment by sitefinitysteve** [comment]
@vakrilov Yes, this is what I was thinking as well (after you mentioned it)... I'm only doing mobile through {N} so I don't have a lot of pure android experience outside of attempting plugins.

I will go back and ask zendesk

**Comment by sitefinitysteve** [comment]
@vakrilov That was it, set a custom theme for just that widget in the manifest brings it back

https://github.com/sitefinitysteve/nativescript-zendesk/blob/master/platforms/android/AndroidManifest.xml
