### ISSUE TITLE
Question: Are android xml layout attributes useable with nativescript xml layout?

### ISSUE THREAD

**Issue by gaurav-chandra** [NativeScript/NativeScript#1388]
Are android xml layout attributes useable with nativescript xml layout? Like 
```
Android:

<TextView android:maxLength="10"/>

Nativescript: 

<TextField maxLength="10" /> or <TextField android.maxLength="10" />
```
or it has to be done manually in code behind file?

**Comment by enchev** [comment]
Using android.some_property you can set properties however Android attributes cannot be set. For max length you can handle loaded event and call setMaxLength for example:
```XML
<TextView loaded="myTextViewLoaded" />
```
```JavaScript
exports.myTextViewLoaded = function(args){
  var tv = args.object;
  if(tv.android){
     tv.android.setMaxLength(10);
  }
}
```

**Comment by lakshaya22** [comment]
Where I have to keep this method. I have tried keeping it in my component class and outside too, but its not working. @enchev
