### ISSUE TITLE
Frame navigate, while android Activity is paused, crash

### ISSUE THREAD

**Issue by mike-ense** [NativeScript/NativeScript#1389]
##### Prio* Doing frameModule.topmost().navigate() when the app is not in the foreground crashes Java

The following page-1.js will crash Nativescript if you press the phone's "home" button as to switch activity away from the program within 5 seconds.

How can this be worked around?

var timerModule = require("timer");

exports.loaded = function(args) {
     timerModule.setTimeout(function () {
          frameModule.topmost().navigate({ create: function () {
     		return new pageModule.Page();
          }});
     },5000);
};

**Comment by NathanaelA** [comment]
This has been occurring since I believe day one.   

I've worked around it in by watching the application Pause/Resume events, and if the app is paused I store the navigation info; and once I resume I re-trigger it.

**Comment by mike-ense** [comment]
@NathanaelA , aha beautiful workaround - would you mind pasting code snippet for how to listen for that properly ?

E.g.  just in the style    listenforpause(function() { ... });   listenforresume(function() { .... }); , thanks

**Comment by NathanaelA** [comment]
The code is basically like this (I have it in a class):

```
var application = require('application');
var isSuspended = false, pendingNavigate = null;
application.on(application.suspendEvent, function () {
   isSuspended = true;
});

application.on(application.resumeEvent, function () {
   isSuspended = false;
  if (pendingNavigate) {
     myNavigate(pendingNavigate);
     pendingNavigate = null;
   }   
 });

function myNavigate(whereTo) {
   if (isSuspended) {
        pendingNavigate = whereTo;
   } else {
       frame.topmost().navigate(whereTo);
  }
}
```

**Comment by mike-ense** [comment]
@NathanaelA , is this watertight in your experience, no cornercases where it could crash or malfunction?  Looks good!

**Comment by NathanaelA** [comment]
Well, technically it might crash if you restore it and then like a second later suspend it.  It might crash if the timing is right for you to get the actual navigate code to be navigating while you suspend it..     I use this technique in my liveedit plugin to eliminate crashes on my apps while doing work on them and I haven't yet seen it cause a crash.  But then I'm not typically restore/suspend in the same second.

**Comment by mike-ense** [comment]
@NathanaelA , maybe that is a good reason to ask the Telerik guys to implement an actually solid solution to this problem? I mean, switching between pages is about as fundamental as a function can be come within {N}, so it's important that that Really Works - in particular when a crash means weird scary message to user PLUS shutdown of the app! (Even a 0.1% chance of your workaround above failing and instead leading to a crash, is unacceptable here.)   What do you think?

**Comment by mike-ense** [comment]
@vakrilov what do you say?  I.e. Nathanael suggested a way to mitigate frameModule.topmost().navigate() 's crash potential, but we're not sure his workaround is 100% solid - what about you have a look at this and provide some way that is guaranteed to always work as in safeguard {N} app from hard Java VM + app crashes in relation with frameModule.topmost().navigate() ? Thanks :)
