### ISSUE TITLE
How to maintain a viewModel through pages and again come back to it?

### ISSUE THREAD

**Issue by akkiittiwari** [NativeScript/NativeScript#1393]
Hey

I am trying to build a shopping cart through Nativescript. 
How can I maintain a cart viewModel so that I can store and update my cart constantly through all pages. 
Also, when I return back from a page with the back button, the pages appears fine but the functionality is disrupted. 

Also, how can I put a load more option in list page.

Hoping for some prompt solutions. 
Thanks

**Comment by bradmartin** [comment]
I believe you are going to need some local data storage. NativeScript provides the app_settings module and there is a SqlLite plugin. I would use app_settings and just JSON.stringify(dataObject) when you navigate away from the page and then JSON.parse(dataObject) when you go back to the page. 

Another approach, if not dealing with a deep navigational hierarchy, would be to show the secondary page as a modal

**Comment by akkiittiwari** [comment]
Thanks. Local storage solution with app_settings module worked. 

But still stuck with "load more" option.?

**Comment by akkiittiwari** [comment]
Done with that. 

Thanks a lot.
