### ISSUE TITLE
tap does not work when cssClass present on <Button>

### ISSUE THREAD

**Issue by rubenstolk** [NativeScript/NativeScript#14]
By simply adding any cssClass to a `<Button>`, the tap event is not fired anymore. This can be replicated by simply creating a new project and adding `cssClass="message"` to the `<Button>`. I can only confirm this for `iOS`.

**Comment by edimoldovan** [comment]
For better reproducibility I would add that it works like this:
`<Button cssClass="next" text="next" tap="{{ nextAction }}" />`

**Comment by vakrilov** [comment]
It's a known issue - declaring event binding does not work if it is not the last attribute in the xml element definition. Good news is that is already fixed - will be available with the next release.

**Comment by grouchycoterie** [comment]
You should add this to documentation of the tutorial. Ran into this problem there
<Button text="Sign up for Groceries" class="link" tap="register"/>

**Comment by vakrilov** [comment]
@grouchycoterie I think this was fixed long ago. If you managed to reproduce it - please reopen the issue and post some code so that we can investigate. It might be a regression.

**Comment by grouchycoterie** [comment]
Wow. I can't reproduce now. I thought all I did was move this around but I guess something else was going on.
