### ISSUE TITLE
Does the javascript run when the app is in the background?

### ISSUE THREAD

**Issue by shantamg** [NativeScript/NativeScript#1403]
On the emulators for ios and android, javascript does run when the app is in the background, but on my actual iPhone it seems to pause until the app is reopened at which time the script continues to run.

To produce the issue, I do this:

    var timer = require("timer");

    exports.loaded = function(args) {
      timer.setTimeout(function() {
        console.log('Hello!');
      }, 5000);
    };

As soon as the page loads, I hit the home button. 

In the ios emulator, after 5 seconds I see the log in the console.
On my physical iPhone the log never happens as long as the app is in the background but when I tap the icon of my app to bring it to the foreground, the log fires.

**Comment by hshristov** [comment]
This is controlled by the OS so there are multiple factors that could affect application lifetime. For example if your application is on the background and Android needs more memory it could kill it which will stop JS execution.

**Comment by shantamg** [comment]
I see, thanks.
My real use case is receiving push notifications. I am using PubNub, which I got to work beautifully while the app is running, but in order to get realtime messages when the app is in the background I suppose I do need to register with a push service.
