### ISSUE TITLE
Weird error(?) lines after left standing for a few minutes

### ISSUE THREAD

**Issue by prawnsalad** [NativeScript/NativeScript#1406]
I have a TCP client connection made by interfacing with the java classes directly on Android. With it connected and receiving data for 2-5 minutes the below lines start being thrown in the console (running via livesync). The app after around 10 seconds then crashes on the device.
~~~
01-20 02:59:58.240 26826 26826 W art     :   at com.tns.Platform.callJSMethodNative(Native method)
01-20 02:59:58.240 26826 26826 W art     :   at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:799)
01-20 02:59:58.240 26826 26826 W art     :   at com.tns.Platform.callJSMethod(Platform.java:700)
01-20 02:59:58.240 26826 26826 W art     :   at com.tns.Platform.callJSMethod(Platform.java:680)
01-20 02:59:58.240 26826 26826 W art     :   at com.tns.Platform.callJSMethod(Platform.java:670)
~~~

**Comment by enchev** [comment]
Can you post the full stack trace?

**Comment by prawnsalad** [comment]
That's literally all there is, repeated hundreds of times until it crashes...

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#336
