### ISSUE TITLE
List view not working on second tab of tab view

### ISSUE THREAD

**Issue by akkiittiwari** [NativeScript/NativeScript#1412]
Heyy.

I have implemented list view on one tab of the page and am trying to implement the same on the second tab, but the page comes out to be blank when loading data into viewmodel.
Is it compulsory to use promise to load data in the viewmodel or Can i use my own functions and callback?

**Comment by enchev** [comment]
To populate ListView you can assign `items` property no matter how and when your data are downloaded.
