### ISSUE TITLE
App hangs on data loading

### ISSUE THREAD

**Issue by akkiittiwari** [NativeScript/NativeScript#1413]
The app hangs as soon as i press load more button or whenever throughout the app it is loading data from the api. 
What can be an optimal solution to speed up and manage heavy data.

**Comment by enchev** [comment]
You can use the same approach as in our cuteness.io app:
https://github.com/NativeScript/NativeScript/blob/master/apps/cuteness.io/reddit-app-view-model.ts#L24-L51

**Comment by akkiittiwari** [comment]
Hey @enchev 

I am not able to figure out the solution as I am new to nativescript. can you please simplify and point out the exact solution.
