### ISSUE TITLE
Can't get cocoapods to run

### ISSUE THREAD

**Issue by stevetayloruk** [NativeScript/NativeScript#1420]
Hi,

I'm trying to get cocoapods to work but keep getting this error when doing a build:

```
Check dependencies
CodeSign error: entitlements are required for product type 'Application' in SDK 'Simulator - iOS 9.2'. Your Xcode installation may be damaged.

** BUILD FAILED **


The following build commands failed:
        Check dependencies
(1 failure)
Command xcodebuild failed with exit code 65
# build ios
```
I've tried many from this list without success: https://cocoapods.org/?q=on%3Aios%20segmented

Is it something I'm doing wrong?

Thanks

Steve

**Comment by fealebenpae** [comment]
Hi @stevetayloruk,

I had the same error on Xcode 7.2. I fixed it by downgrading to Xcode 7.1.

**Comment by stevetayloruk** [comment]
@fealebenpae do you have to reinstall to downgrade or it there an easier way?

thanks

**Comment by NathanaelA** [comment]
My understanding to downgrade you have to de-install then install xcode 7.1.   

No one has tried the 7.3 beta that I have seen, if you want to try it -- it would be interesting to see if the issue has been fixed in 7.3.

**Comment by stevetayloruk** [comment]
7.3 beta still doesn't work but i can confirm that 7.1.1 does.

thanks!

**Comment by stevetayloruk** [comment]
BTW, does anyone know why this is the case? It's far from convenient as my phone is 9.2 which isn't supported by 7.1 xcode.

**Comment by NathanaelA** [comment]
@stevetayloruk Why won't XCode 7.1 be able to compile something that works for 9.2?

You can probably actually close this issue as this issue belongs in the CLI; I opened a issue earlier today in the CLI repo on this.   https://github.com/NativeScript/nativescript-cli/issues/1428

**Comment by stevetayloruk** [comment]
I would have thought that too. I get this error:

```
Could not find Developer Disk Image
```

According to SO: http://stackoverflow.com/questions/30736932/xcode-error-could-not-find-developer-disk-image

```
I have experienced same issue

Could not find Developer Disk Image
My Xcode version was 7.0.1 and i updated my iPhone to version 9.2, then upon using Xcode i ran into this problem.

Solution is pretty simple just Download latest version of Xcode 7.2 which was released on 8 Dec, 2015 and install it. Everything works fine for you as it was before.
Note: Actual problem is your Xcode version is not compatible/outdated with version on your device.
```
