### ISSUE TITLE
Dynamic partial-view loads without CSS

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#1424]
I am loading a partial-view (js, css, xml) into another view, by using the following example:

```javascript 
var builder = require("ui/builder");
var myComponentInstance = builder.load({
        path: "~/xml-declaration/mymodulewithxml",
        name: "MyControl"
});
mylayout.addChild(myComponentInstance);
```
It loads just fine with all the data. But the CSS is not applied, what gives? The css file is the same name as the xml & js. It's just a few blocks, so I can move them to the main css-file, but still.

**Comment by enchev** [comment]
Please specify page in the options when loading:
```JavaScript
var myComponentInstance = builder.load({
        path: "~/xml-declaration/mymodulewithxml",
        name: "MyControl",
        page: referenceToYourPage
});
```

**Comment by manijak** [comment]
Well the thing is I am loading the module innside another partial-view. What is the easiest way to get the Page reference innside a non-page view?

**Comment by enchev** [comment]
if the page you want to add is the current app page your can get it using:
var frame = require("ui/frame");
....
var page = frame.topmost().currentPage;

**Comment by alexrainman** [comment]
@enchev which method is called on the view when it's loaded with builder? I want to hook an event to a button like this:

```
var view = <View>args.object;
var btn = <Button>view.getViewById("MyButton");
var observer = addpage.on(gestures.GestureTypes.tap, function (args: gestures.GestureEventData) {
    console.log("Tap");
});
```
I tried OnLoaded but is not called. Thx

**Comment by hshristov** [comment]
@alexrainman There is no event raised when view is created from builder. You should be able to use `loaded` event in order to attach handlers. It will raise later (not when builder is parsing the string) but it should be good enough.

**Comment by alexrainman** [comment]
@hshristov loaded is never called

**Comment by hshristov** [comment]
@alexrainman `loaded` will be called once you attach the view returned from `builder.load` to some parent view.

**Comment by alexrainman** [comment]
@enchev i am having the same issue. CSS not applied to view loaded with builder even specifying the page using frame.topmost().currentpage. Any ideas?

**Comment by emmanuel128** [comment]
@hshristov Can you tell me how to add tap events in buider.load?

**Comment by phattranky** [comment]
I got the same issue
