### ISSUE TITLE
Images have margin when added to Layout

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#1425]
When I add Image(s) to any Layout (tested on Stack and Grid), the images is added with margins on the left and right side (around 5 px on each side). Isn't it supposed to fill the width of the container and keep aspect? I tried also with stretch="AspectFill" same result. 

But as soon as I set a specific height to the image, the margins are gone.

**Comment by vchimev** [comment]
@manijak, is this on iOS, Android or both? Could you please elaborate a little bit more on how to reproduce this and also make sure there is no unexpected *css* applied?

Here is my page:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="pageLoaded">
  <StackLayout>
    <Image src="~/red.png" />
  </StackLayout>
</Page>
```
![screen shot 2016-02-01 at 4 31 16 pm](https://cloud.githubusercontent.com/assets/12251337/12719730/aebe6f0a-c8ff-11e5-91c3-6304a529a067.png)

**Comment by manijak** [comment]
It's true, it does not happen everywhere. I tried adding some other images to the same view & container, and they fit as they should. I think it's a resize/aspect issue with some images. 

The difference between images were the sizes. The images I have problems with are "banners" with a specific size of around: 994x172.

So there are no margins to be accurate, but there is some space on the left & right, so that the image does not fill the width.  

![apptest_imagew](https://cloud.githubusercontent.com/assets/3605066/12721966/c0708c6c-c902-11e5-8994-716993a08ac0.png)

**Comment by vchimev** [comment]
@manijak, I tried the following specific image sizes: 1000x200, 998x199. 996x198, 994x197, 992x196 and with some of them I reproduced the issue. It is both on Android and iOS.

**Comment by hamorphis** [comment]
Sample app: https://github.com/hamorphis/issue-1425

**Comment by hamorphis** [comment]
Android screenshot:
![android](https://cloud.githubusercontent.com/assets/1201857/16001767/ad2e7be2-315c-11e6-80ca-33323ba1a415.png)
