### ISSUE TITLE
Best practices of creating native code and passing parameters to ns, preferably async way

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#1427]
What is the best practices? It will solve thread problem by using native code

**Comment by enchev** [comment]
Hey @x4080,

Yep, if you need some async code you can simply create a plug-in with native part and later call desired plug-in method with desired parameters when needed. There is nothing special in this case and {N} will work exactly in the same way as with default platform async code, like [our http module](https://github.com/NativeScript/NativeScript/blob/master/http/http-request.ios.ts) for example.

**Comment by x4080** [comment]
Yes I thought so too, but its kinda confusing for the route to take, maybe there is some steps for Android and ios ?

Android using aar and ios using cocoapods?

**Comment by enchev** [comment]
Indeed the idea is to create a plugin with native part (aar for Android and cocoapod for iOS). Please check our documentation for plugins: http://docs.nativescript.org/plugins/plugins

**Comment by x4080** [comment]
Thanks for the pointers
