### ISSUE TITLE
How to create AppWidget using nativescript?

### ISSUE THREAD

**Issue by katturajam** [NativeScript/NativeScript#1431]
I need a help how to create a AppWidget using nativescript for Android & IOS.

**Comment by bigcrab1** [comment]
To the best of my knowledge AppWidgets are Android Only (iOS simply doesn't have an equivalent). 

I too would be interested in knowing if anyone has successfully created an AppWidget for Android using NativeScript however. I can't find any reference to it in the docs or in the roadmap...

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#356
