### ISSUE TITLE
Geolocation module problem with run app on Android 6 (Marshmallow)

### ISSUE THREAD

**Issue by aderbas** [NativeScript/NativeScript#1434]
I'm created a simple project using a sample for geolocation. Follow the tutorial but I am getting the following error: http://pastebin.com/WyqSaBUi

Added permission in AndroidManiest.xml
```
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
```
Do you need anything else?

**Comment by aderbas** [comment]
I found the possible problem, LocationClient is the new way of getting GPS. I teste on Android Lollipop and works fine, when I will test the Android Marshmallow the error occurs. I do not know if is a buggy of Android or NativeScript.

Android 6 show this error

```
JS: Error watch location: java.lang.SecurityException: "fused" location provider requires ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission.
JS:     android.os.Parcel.readException(Parcel.java:1599)
JS:     android.os.Parcel.readException(Parcel.java:1552)
JS:     android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:606)
JS:     android.location.LocationManager.requestLocationUpdates(LocationManager.java:880)
JS:     android.location.LocationManager.requestLocationUpdates(LocationManager.java:529)
JS:     com.tns.Platform.callJSMethodNative(Native Method)
JS:     com.tns.Platform.dispatchCallJSMethodNative(Platform.java:799)
JS:     com.tns.Platform.callJSMethod(Platform.java:700)
JS:     com.tns.Platform.callJSMethod(Platform.java:680)
JS:     com.tns.Platform.callJSMethod(Platform.java:670)
JS:     com.tns.gen.android.view.View_OnClickListener_ftns_modules_ui_button_button_l19_c42__.onClick(android.view.View$OnClickListener.java)
JS:     android.view.View.performClick(View.java:5201)
JS:     android.view.View$PerformClick.run(View.java:21163)
JS:     android.os.Handler.handleCallback(Handler.java:746)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:148)
JS:     android.app.ActivityThread.main(ActivityThread.java:5443)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by aderbas** [comment]
No one with this problem in Android Marshmallow? =/

**Comment by NathanaelA** [comment]
Android 6 requires the permissions to be granted a different way; you need to request the permission and check to see if you have it before you call the GPS.    Unfortunately, at this moment; I don't believe NativeScript actually supports getting the result back, so you can't actually solve it right now... 

  The NS code actually needs to support the:
**onRequestPermissionsResult** callback on the activity; this will need to be exposed I believe from the Android runtimes and then in the common core.

**Comment by aderbas** [comment]
I read has changed and needs to ask the user's permission. I'll see what can be done. Thanks for the tip.

**Comment by atanasovg** [comment]
@NathanaelA That is correct, we are already working on the integration of the https://github.com/NativeScript/android-runtime/issues/283 feature and once we complete this we will be able to change the base Activity type at Modules level.

@aderbas I've opened a [separate issue](https://github.com/NativeScript/NativeScript/issues/1451) on this - we will do our best to implement it for the 1.7 release - that is somewhere near May.

**Comment by aderbas** [comment]
Thanks @atanasovg

**Comment by ofirdagan** [comment]
+1

**Comment by frossi85** [comment]
+1

**Comment by chief10** [comment]
Was this issue fixed? I am getting the same errors as op.

**Comment by NathanaelA** [comment]
@chief10 - To my knowledge this is fixed.  I wrote a plugin called "nativescript-permissions" which works on all versions of android and allows you to request any permission your app needs and it has been working perfectly since v2.00.   You still have to have the permissions in the manifest AND if you are using Android 6, you have to ask the end user if they will grant the permission.   (Which is the part the ns-permissions plugin handles).    So if it is still failing on Android 6, it probably is because you haven't actually asked the user permission to use the permission, and you should check out my plugin for how to do it easily...
