### ISSUE TITLE
NSDate types need to be updated in ios.d.ts

### ISSUE THREAD

**Issue by speigg** [NativeScript/NativeScript#1436]
Due to auto-marshalling, many of the api's defined in `ios.d.ts` are now incorrectly declared as returning `NSDate` objects when they should instead be declared to return `Date` objects. I'm not sure if this is also needed the other way around (presumably apis that are declared as accepting `NSDate` objects should be changed to declare that they accept `Date` objects?).

**Comment by enchev** [comment]
This issue was moved to NativeScript/ios-runtime#496
