### ISSUE TITLE
Integrating with libraries that use JNI

### ISSUE THREAD

**Issue by RangerMauve** [NativeScript/NativeScript#144]
I'm very interested in getting this to somehow play with [WebRTC](http://www.webrtc.org/native-code/android), does NativeScript support using libraries on Android through JNI since AFAIK there is no pure Java implementation of a lot of libraries out there.

**Comment by slavchev** [comment]
The current metadata generator uses Java reflection so if WebRTC (or any other) library provides Java wrappers for the native code (e.g. `System.loadLibrary(...)` and `native` methods) then it should be possible to consume the library. I guess you should tweak a bit the build process to use `ndk-build` and/or update `Android.mk` file.

On the other hand, if you want to leverage C/C++ code without Java wrappers then we should come with different approach. We can use Clang to parse your header files and generate metadata. At present, we don't support this scenario but I encourage you and other interested to discuss it so we can get better understanding and prioritize the issue accordingly.

**Comment by RangerMauve** [comment]
as I understand it, this particular WebRTC library only provides the c/c++ wrappers and expects the user to use their own JNI wrappers if needed. That being said I doubt it'd take long at all to make wrappers since it's a small enough API. 

Also, I don't think that NativeScript should bother parsing headers or whatever else since wrapping over these libraries will not be needed very frequently and isn't too hard to do. I think that for the near future there are more interesting things to focus on.

Thanks for the help, I'll probably post here once I get time to play with this some more.

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#76
