### ISSUE TITLE
Import xml

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#1441]
Is it possible inside xml ala css import? It useful for breaking up xml and for platform dependent xml

**Comment by enchev** [comment]
Hey @x4080,

{N} will automatically resolve your XML files (and all other files as well) depending on various qualifiers:
https://docs.nativescript.org/core-concepts/navigation#supporting-multiple-screens

**Comment by x4080** [comment]
Ok solved for multiple screen. But no import like css then? For breaking up xml to different parts if the page view is too large without using component

**Comment by enchev** [comment]
You can use [custom components with XML in this case](http://docs.nativescript.org/ui/ui-with-xml). Look for "XML-Based Custom Component with a Code File"

**Comment by x4080** [comment]
Yes already read that.. Thanks anyway
