### ISSUE TITLE
Impossible to rotate 360degrees on iOS

### ISSUE THREAD

**Issue by DrCacho** [NativeScript/NativeScript#1443]
Hi!

Triying to use this sample code from https://docs.nativescript.org/ui/animation i can't get the animation work on IOS (it works ok on Android)

view.animate({
    rotate: 360,
    duration: 3000
});

But if i change it to 

view.animate({
    rotate: 180,
    duration: 3000
});

It works perfect. Any idea about why only works with 180 degrees? 

Regards

Cacho

**Comment by hamorphis** [comment]
Because for iOS 360 degrees is the same as 0 degreees. The rotation is done with an affine transform matrix and the matrix with 360 degrees rotation is the same as the one with no rotation at all, i.e. the identity matrix.

**Comment by DrCacho** [comment]
Hi, Thaks for your answer. I tried with 359, 350 and 340 degrees, but also not work.

**Comment by vchimev** [comment]
Fixed by https://github.com/NativeScript/NativeScript/pull/1472.
