### ISSUE TITLE
Available methods of a cocoapod

### ISSUE THREAD

**Issue by stevetayloruk** [NativeScript/NativeScript#1448]
Hi,

Question:

I'm using this cocoapod (https://github.com/HeshamMegid/HMSegmentedControl) and I'm trying to call this function from Nativescript but it says it's not available.

I'm trying to call this method:

```
- (void)setSelectedSegmentIndex:(NSUInteger)index animated:(BOOL)animated notify:(BOOL)notify 
```
like this:

```
const tabItems = ['tab1', 'tab2', 'tab3', 'tab4'];
const tabs = HMSegmentedControl.alloc().initWithSectionTitles(tabItems);
tabs.setSelectedSegmentIndex(index, true, true);
```

It's the last line I can't get to work. I can easily set properties like so:

```
tabs.selectedSegmentIndex = index
```
How do I go about trying to understand the Nativescript equivalent? Is there a way to see all exposed functions like a console.dump()?

I've read the marshalling section in the docs but i can get it to work.

Thanks

Steve

**Comment by NathanaelA** [comment]
I have a blog post on how to convert a third party module that also deals with naming: http://fluentreports.com/blog/?p=167
But in a nutshell the code should be:
```js
tabs.setSelectedSegmentIndexAnimatedNotify(index, true, true);
```

**Comment by stevetayloruk** [comment]
@NathanaelA thanks soooo much.  Great article, wish I knew about it before.

**Comment by stevetayloruk** [comment]
Spoke too soon..

There are 3 methods available as overloads and none seem to work:

```
- (void)setSelectedSegmentIndex:(NSInteger)index {
    [self setSelectedSegmentIndex:index animated:NO notify:NO];
}

- (void)setSelectedSegmentIndex:(NSUInteger)index animated:(BOOL)animated {
    [self setSelectedSegmentIndex:index animated:animated notify:NO];
}

- (void)setSelectedSegmentIndex:(NSUInteger)index animated:(BOOL)animated notify:(BOOL)notify {
```
Here is the cocoapod: (https://github.com/HeshamMegid/HMSegmentedControl)

**Comment by NathanaelA** [comment]
I have a theory; can you see if the non notify one works (i.e. the index/animated one): 
Which then would be called: [HMSC].setSelectedSegmentIndexAnimated(index, bool)

**Comment by stevetayloruk** [comment]
Yes! that seems to work.  Why is that? only one out of the 3 work??

**Comment by NathanaelA** [comment]
Unfortunately I have not delved really deep into the iOS metadata system, but my **theory** is that it uses the .h file to figure out how to generate the publicly accessible functions. The only function listed in the .h file is the one I asked you about.    The other two variations even though they are in the .m file; are not listed in the .h file, meaning they are private...   

Hey, @fealebenpae can you verify if my theory is correct, might help eliminate some confusions.

**Comment by stevetayloruk** [comment]
This makes perfect sense, and really I should have known this but it's been years since I last touched objective C.

thanks for you time.

**Comment by fealebenpae** [comment]
@NathanaelA: that's right, we generate the API metadata exclusively by parsing headers.

@stevetayloruk: in Objective-C method names contain the names of the parameters. The JavaScript name of an Objective-C method is really a concatenated list of all its parameters, like in [this example from our docs](http://docs.nativescript.org/runtimes/ios/types/ObjC-Classes.html#methods). But instead of mentally concatenating strings, [you can have the Objective-C metadata generator emit a set of TypeScript type declarations that describe the native APIs as exposed to JavaScript](http://docs.nativescript.org/runtimes/ios/how-to/Use-Native-Libraries#troubleshooting).

**Comment by stevetayloruk** [comment]
@fealebenpae the typescript declarations are what I was after. This is **extremely** helpful but knowing it parses the interface file also helps ;-).

thanks guys.

**Comment by NathanaelA** [comment]
@fealebenpae That is an awesome feature.  It didn't know it existed.  

:grinning: going to go play with a new toy...
