### ISSUE TITLE
Https Certificate cause error

### ISSUE THREAD

**Issue by wisonye** [NativeScript/NativeScript#1449]
Hi guys, I have a problem about fetch https, please take a look, should be a common situation but I didn't got answer from google :)

I have a SSL certificate which running on my public website( https is no problem ), then I'm build a NativeScript mobile app which need to access via "https" protocol, for coding( before publish to app store ), I have to use local Node.JS( express ) as a local web server( everybody do that, very common ), and the local web server( express ), I use my public website's SSL certificate, then the nativescript mobile app work fine when "fetch" use "http" protocol, but fail when use "https", error is :

```javascript
NSURLConnection/CFURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9843)
```

I know that I use a real certificate in a local server( 127.0.0.1 ) is not right, BUT for coding, I have to......, is any idea to "get round" it when coding on local web server ??? 

I checked solution in google, but usually need to add a delegate to "NSURLConnection", like this:
```javascript
http://stackoverflow.com/questions/23241872/nsurlconnection-cfurlconnection-http-load-failed-kcfstreamerrordomainssl-9813
```

But I cannot find any "NSURLConnection" in "fetch.js"( in NativeScript source code ), how to solve this ? Don't tell me that I'm the only one who met this issue :) Anyway, please help :)

**Comment by enchev** [comment]
Hey @wisonye,

Well, for the sake of testing you can modify your info.plist file as described in stackoverflow:
```XML
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

**Comment by wisonye** [comment]
@enchev Hi, actually I added this already, it ONLY WORKS on IOS9 :) Not works on IOS8 :)

**Comment by enchev** [comment]
Hey @wisonye,

In this case you can modify directly our code (for testing purposes only of course) here:
https://github.com/NativeScript/NativeScript/blob/master/http/http-request.ios.ts

We use however a bit different approach (not NSURLConnection).
