### ISSUE TITLE
Provide a way to get the app version

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/NativeScript#145]
I'm looking for a simple way to get the app's version, much like how the [Cordova app version plugin works](https://github.com/whiteoctober/cordova-plugin-app-version).

The iOS utils file has the major version, but it's [a bit hidden](https://github.com/NativeScript/NativeScript/blob/f0abe6639682ea4b771af14ddd7252aa3486764b/utils/utils.ios.ts#L79). Ideally this would be a part of the application module or something more global.

Thanks,
TJ

**Comment by valentinstoychev** [comment]
[Platform module](https://github.com/NativeScript/NativeScript/blob/f0abe6639682ea4b771af14ddd7252aa3486764b/platform/platform.ios.ts) is what you are looking for. No?

**Comment by tjvantoll** [comment]
Huh, indeed it is. Not sure how I missed that. Thanks!

**Comment by tjvantoll** [comment]
Actually my earlier comment was wrong, as was my link from earlier.

What I'm looking for is a way to get the app's version #, not the platform's. For example, given the [TelerikNEXT app](https://itunes.apple.com/us/app/teleriknext/id982525766?mt=8) I'd want a way to retrieve `"1.2"`.

My use case is analytics. Currently we have to [hardcode the app version when creating a `NativeScriptMonitor`](https://github.com/NativeScript/NativeScript-NEXT-Workshop/blob/e08957d44103ad56ac4e4258926cc468727c69b3/app/shared/analytics.js#L4), which is a maintenance nightmare.

**Comment by EddyVerbruggen** [comment]
Hi guys, a port of the Cordova AppVersion plugin TJ mentioned was on my hobbylist, so I decided to pick it up. [It's available on npm](https://www.npmjs.com/package/nativescript-appversion).

I verified that this plugin will report `1.2` when used with the TelerikNEXT app.

I was wondering one thing: intuitively I thought the `version` in `app/package.json` would propagate to `versionName` in `AndroidManifest.xml` and `CFBundleShortVersionString` in `*.plist` (much like Cordova does via `config.xml`). This is not the case. Is that something that's planned, or do users need to manually update those platform specific files?

**Comment by tjvantoll** [comment]
Wow @EddyVerbruggen, that's spectacular. Thanks for porting that so quickly!

And you have an excellent question. From the CLI I actually have no idea you you configure the version without manually changing the platform-specific files. I could see either `app/package.json` or a new property in `.tnsproject` making sense.

**Comment by valentinstoychev** [comment]
Hey @EddyVerbruggen - amazing! :) Are you interested to blog about these new modules on nativescript.org/blog? I can make you an author there. Let me know!

**Comment by valentinstoychev** [comment]
@tjvantoll this is definitely something that should be done. Can you please open an issue in the nativescript-cli repo. I think the best way to do it is to have a special section in the package.json file that decribes such types of properties. Based on this info the CLI can update the native packages.

**Comment by EddyVerbruggen** [comment]
@tjvantoll @valentinstoychev That would be a nice approach for specifying the version :+1: 

@valentinstoychev I'd be honoured to blog, PM me the details (eddyverbruggen at gmail) and I'll give it a shot.

**Comment by tjvantoll** [comment]
I created an issue on the CLI repo: https://github.com/NativeScript/nativescript-cli/issues/478.

@EddyVerbruggen's module solves my problem so I'm going to close this issue. We can continue the discussion of how this will work over in the CLI repo.
