### ISSUE TITLE
Button text difference

### ISSUE THREAD

**Issue by kiril-stanoev** [NativeScript/NativeScript#1450]
Hi,
I have a set of buttons whose text is bound.

`
<Button text="{{ first }}" tap="navigateToChord" class="first"/>
<Button text="{{ second }}" tap="navigateToChord" class="second"/>
<Button text="{{ third }}" tap="navigateToChord" class="third"/>
`
etc.

css is similar for all:
`.first {
	color: #0b61f7;
	font-size: 24;
	horizontal-align: center;
	width: 80;
	height: 80;
	margin-top: 5;
	margin-left: 5;
	margin-bottom: 5;
	margin-right: 5;
	border-color: lightgray;
	border-width: 1;
}`

The output is different on Android 6.0.1 and iOS 9.2.1. For some reason the Android device displays the button text capitalized. See the images below.

[Android](https://www.dropbox.com/s/8olxh17yqmtv4ti/nashville_android.png?dl=0)

[iOS](https://www.dropbox.com/s/in5erkbec2tcpil/nashville_ios.png?dl=0)

{N} version is 1.5.2

Let me know if you're aware of such issue.

-k

**Comment by bradmartin** [comment]
Hey @kiril-stanoev - on Android the default it to capitalize the text within buttons. So per the platform specs, I would leave it as is but you can change this behavior. I haven't done this, but I do know it's possible on Android to override the default behavior.

**Comment by kiril-stanoev** [comment]
Thanks,  I'll try that.

**Comment by kiril-stanoev** [comment]
Thanks,  I'll try that.
