### ISSUE TITLE
Listview's template, gridlayout not functioning properly

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#1454]
_From @x4080 on January 28, 2016 3:37_

If we have :

```
    <ListView rowHeight="100" id="listview">
      <ListView.itemTemplate>
        <GridLayout rows="50,50" backgroundColor="yellow">
          <Label text="sometext" horizontalAlignment="center" verticalAlignment="center" row="0" backgroundColor="blue"/>
          <Label text="sometext" horizontalAlignment="center" verticalAlignment="center" row="1" backgroundColor="green"/>
        </GridLayout>
      </ListView.itemTemplate>
    </ListView>

```

Both texts will be vertically and horizontally centered

Same result in iOS and Android

but if we do 

```
    <ListView rowHeight="100" id="listview">
      <ListView.itemTemplate>
        <GridLayout rows="*" backgroundColor="yellow">
          <Label text="sometext" horizontalAlignment="center" verticalAlignment="center" row="0" backgroundColor="blue"/>
        </GridLayout>
      </ListView.itemTemplate>
    </ListView>

```

In iOS, the text will not be vertically centered, but Android still vertically centered

Also I tried removing the rows="*" :

```
    <ListView rowHeight="100" id="listview">
      <ListView.itemTemplate>
        <GridLayout backgroundColor="yellow">
          <Label text="sometext" horizontalAlignment="center" verticalAlignment="center" row="0" backgroundColor="blue"/>
        </GridLayout>
      </ListView.itemTemplate>
    </ListView>
```

Android still works perfectly, iOS is still cannot vertically centered

Maybe alignment bug in iOS?

_Copied from original issue: NativeScript/nativescript-cli#1433_

**Comment by vchimev** [comment]
_From @x4080 on January 28, 2016 5:32_

Sorry post it in the wrong section, any help to move it?

**Comment by enchev** [comment]
Hey @x4080,

If you have just one child maybe you can simply place it as itemTemplate and it will work as expected.

**Comment by x4080** [comment]
thanks for the tip, is it gridlayout already? since i needed to auto resize

**Comment by enchev** [comment]
It is StackLayout actually and your case with vertical alignment will work as expected.

**Comment by tsonevn** [comment]
no longer reproducible with modules 4.1.
