### ISSUE TITLE
Generate alternative tns-core-modules.es6.d.ts to allow typescript targets: es6 and es2015

### ISSUE THREAD

**Issue by mkosieradzki** [NativeScript/NativeScript#1457]
Currently, when using references.d.ts with a /// reference to tns-core-modules.d.ts and in tsconfig.json target is set to es6 / es2015 there are multiple obvious name clashes due to partial es6 shimming implemented.

It would be very convenient for developers targeting es6 with typescript natively (and optionally using babel).To have an alternative tns-core-modules.es6.d.ts: which would look exactly as tns-core-modules.d.ts but will omit following es6 shims:

- es-collections.d.ts
- es6-promise.d.ts
- es6.d.ts
- weakmap.d.ts

If I understand correctly, it is also going to be default approach too when the full ES6 will be implemented.

**Comment by hdeshev** [comment]
That looks like a good idea.

We should also consider dropping our custom typings in favor of the [es6-shim](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/es6-shim/es6-shim.d.ts) ones. Some third party code and typings (Angular2 :stuck_out_tongue_winking_eye:) relies on types defined in there like `MapConstructor`, and it would be great if we can use the same typings.
