### ISSUE TITLE
Add TypeScript definitions for the fetch module

### ISSUE THREAD

**Issue by jgsacris** [NativeScript/NativeScript#1459]
As far as I can tell "fetch" is the only module of the tns-core-modules that is missing typescript type definitions. This is needed to port the Groceries tutorial example to TypeScript.

**Comment by enchev** [comment]
You can find TypeScript definitions here (fetch is part of the global context by default):
https://github.com/NativeScript/NativeScript/blob/master/declarations.d.ts#L3-L81
