### ISSUE TITLE
Support CSS for custom components

### ISSUE THREAD

**Issue by bundyo** [NativeScript/NativeScript#146]
Add support for CSS in custom components - they should load CSS files with the same name in their folders, but it the CSS rules should be scoped to only the component and shouldn't mess up the external page. Platform specific CSS would be nice too.

Currently the Page loads CSS in its folders, but the custom components lack a Page, thus I'm filing this issue.

**Comment by jjd314** [comment]
This works great if the component is used individually on a page, but the styles don't seem to apply if the component is used as an itemTemplate in a ListView.  If you could give me a pointer or two about where to begin looking, I'd be happy to contribute and try to fix this.

**Comment by mourahi** [comment]
hi, you can import your css file in "app.css" like that ;

@import url('~/path to your css file.css');
