### ISSUE TITLE
A suggestion about html tags

### ISSUE THREAD

**Issue by sheyooo** [NativeScript/NativeScript#1461]
pls if am wrong correct me: 
As we know native Script doesnt work with html tags. so to port existing apps we have to convert our html tags to some other things... so my suggestion is we should have a mapping system to convert these automatically... eg. a file called tags_map.js: 
`maps = {
 'p': 'Label',
 'div' : 'page',
}`
and so on

**Comment by enchev** [comment]
Hey @sheyooo,

I'm afraid that there is no direct conversion between HTML and iOS/Android layouts and components. NativeScript is just cross-platform wrap on native-platforms and while in some cases (like `<input type="button" />` can be converted to native button widget `android.widget.Button` and/or `UIButton`) in most cases such conversion may mislead you.
