### ISSUE TITLE
Http server?

### ISSUE THREAD

**Issue by nripendra** [NativeScript/NativeScript#1462]
Hi,

We are trying to build an ios app using nativescript. Our app requires a small light weight web server to be embedded within the app.

Is it possible with NativeScript? We are even fine if http server can be written in Objective-c, but we need a way to start server from js. Its even fine if we could use some objective-c class to create http server from within js.

Regards,
Nripendra

**Comment by fealebenpae** [comment]
Hi @nripendra,

You can use the excellent [GCDWebServer](https://cocoapods.org/pods/GCDWebServer) library on iOS. The easiest way is to integrate it is to [create a NativeScript plugin that wraps a CocoaPod](http://docs.nativescript.org/plugins/cocoapods).

**Comment by nripendra** [comment]
Thanks! looks like what I needed. Will check and ask more on this thread if necessary :)

**Comment by nripendra** [comment]
Hi,

Is there a way to do this without using cocoapod? Currently I'm hit by this issue NativeScript/nativescript-cli#1428, so until the fix is released cocoapod doesn't seem to be an option.


Regards,
Nripendra

**Comment by fealebenpae** [comment]
@nripendra: you can manually work around this issue by applying this patch: https://github.com/NativeScript/ios-runtime/pull/501 in your project's `platforms/ios/{app_name}/build.xcconfig` file.

**Comment by nripendra** [comment]
@fealebenpae 

Thanks! It started to build now. Now looks like I have one final question..

I'm writing following code to serve html, on top of default code generated by tns. Now, console log shows that server is getting the request, but the client never gets back response. I tried using both "fetch" as well as "openUrl", neither is getting response.

```js
var vmModule = require("./main-view-model");
var utils = require("utils/utils");
function pageLoaded(args) {
    var page = args.object;
    page.bindingContext = vmModule.mainViewModel;
    
    // Create server
    let webServer = GCDWebServer.alloc().init();

    console.log(webServer)
    webServer.addDefaultHandlerForMethodRequestClassAsyncProcessBlock("GET", GCDWebServerRequest, (request) => {
        console.log("got request");
        var response = GCDWebServerDataResponse.alloc().initWithHTML("<html><body><p>Hello World</p></body></html>");
        console.log("prepared response %o", response);
        return response;
    })

    webServer.startWithPortBonjourName(8080, "GCD Web Server");
    console.log("server started at :" + webServer.serverURL.toString());
    //fetch(webServer.serverURL.toString()).then(function(r) { console.log(r) }).catch(function(e){ console.log(e) });
    console.log("openning url")
    var opened = utils.openUrl(webServer.serverURL.toString());
    console.log("opened = " + opened);
}
exports.pageLoaded = pageLoaded;

```
In above code I get both "got request" and "prepared response" message in my console log, but the response is not received by the client.

Could you please point me to right direction? Once the browser is able to get response, my work can move forward. Stuck on this for almost a week.

**Comment by nripendra** [comment]
@fealebenpae 

I tried with [RoutingHTTPServer](https://cocoapods.org/?q=routinghttp), and it seems to work. Finally I can proceed with other works.

Thanks!

**Comment by c1ngular** [comment]
@nripendra, Can you share more about get this http sever done by using RoutingHTTPServer ? Is it running in a new thread ? I would be very appreciated if you can share your steps !

**Comment by nripendra** [comment]
@c1ngular,

Sorry, but I'm not working on that project anymore and as of now I don't have access to the code.

As far as I remember I just followed the document for integrating CocoaPods with nativescript - https://docs.nativescript.org/plugins/cocoapods. Was pretty straight forward just had to follow the instructions step by step.

For using the pods all you have to do is convert the Objective-C code to js code...

For example, this is the code in objective-c as given in the RoutingHTTPServer's read-me:
```Objective-c
http = [[RoutingHTTPServer alloc] init];
[http setPort:8000];
[http setDefaultHeader:@"Server" value:@"YourAwesomeApp/1.0"];

[http handleMethod:@"GET" withPath:@"/hello" block:^(RouteRequest *request, RouteResponse *response) {
    [response setHeader:@"Content-Type" value:@"text/plain"];
    [response respondWithString:@"Hello!"];
}];
```
A corresponding js would look something like this.
```js
var http = RoutingHTTPServer.alloc().init();
http.setPort(8000);
http.setDefaultHeaderValue("Server", "YourAwesomeApp/1.0");

http.handleMethodWithPath("GET", "/hello",  function(request, response) {
    response.setHeaderValue("Content-Type", "text/plain");
    response.respondWithString("Hello!");
});
```
More over where I had confusion with the method names, I could even inspect the method names of cocoapod in console while running the debugger.

Hope this helps.

**Comment by c1ngular** [comment]
@nripendra Thank you , I will give a go !

**Comment by mourice** [comment]
Any Update on GCDWebServer I also get both "got request" and "prepared response" message in my console log, but the response is not received by the client.

**Comment by mourice** [comment]
Any help on writing the below code in nativescript

```
[webServer addDefaultHandlerForMethod:@"GET"
                         requestClass:[GCDWebServerRequest class]
                    asyncProcessBlock:^(GCDWebServerRequest* request, GCDWebServerCompletionBlock completionBlock) {

  // Do some async operation like network access or file I/O (simulated here using dispatch_after())
  dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3 * NSEC_PER_SEC)), dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
    GCDWebServerDataResponse* response = [GCDWebServerDataResponse responseWithHTML:@"<html><body><p>Hello World</p></body></html>"];
    completionBlock(response);
  });

}];
```
