### ISSUE TITLE
TabView with 'More' option, adds its own navbar

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#1468]
When using a TabView with more than 5 items: the 'More' tab, when selected adds its own ActionBar. Looks weird when you have a view with its own ActionBar. 

Are we supposed to hide the original ActionBar when we select 'More' or is this a bug?

![tabview_actionbar](https://cloud.githubusercontent.com/assets/3605066/12729337/77202986-c926-11e5-8a0d-d2547a4532a7.png)

**Comment by hamorphis** [comment]
This is the default behavior of iOS. You can try the following:
```
if (tabView.ios){
    var uiTabBarController = tabView.ios;
    uiTabBarController.moreNavigationController.navigationBarHidden = true;
}
```

**Comment by maddy2get** [comment]
Hi there,

When I add the code above and go to Tab5, it's ActionBar is not shown but it shows actionbar with <More button.

How do I get the ActionBar related to Tab 5 and Tab 6 to display when I tap on them?

**Comment by NickIliev** [comment]
@maddy2get thanks for noticing this issue - I have logged it as a bug n a brand new issue so please track its developemnt [here](https://github.com/NativeScript/NativeScript/issues/3464)
