### ISSUE TITLE
Pass context to native iOS view controller

### ISSUE THREAD

**Issue by oscar-78** [NativeScript/NativeScript#1469]
How can I pass and retrieve context variables from a nativescript page to a native iOS page? To pass the context I'm using:

`frameModule.topmost().navigate({ moduleName: "views/photos-page", context: items, animated: false });`

Using [https://github.com/PanayotCankov/nativescript-ios-fsimageviewer](https://github.com/PanayotCankov/nativescript-ios-fsimageviewer) as base for the app.

In [https://github.com/PanayotCankov/nativescript-ios-fsimageviewer/blob/master/app/image-viewer-page.js](https://github.com/PanayotCankov/nativescript-ios-fsimageviewer/blob/master/app/image-viewer-page.js) I would like to init the images based on what I passed as context.

I tried overriding the `prepareForSegue` but no luck.

**Comment by PanayotCankov** [comment]
Hi,
The easy way would be to add listener for [`navigatingTo` JavaScript event on the Page instance here](https://github.com/PanayotCankov/nativescript-ios-fsimageviewer/blob/master/app/image-viewer-page.js#L47) where you can use the context [from the event args with a handler similar to this one](https://github.com/NativeScript/nativescript-marketplace-demo/blob/production/app/views/group-info-page.ts#L11). If you do this with lambda function in the constructor of the page you can use a `var that = this`-ish approach and access the page from `that` and the `imageViewController`.

**Comment by MartienB** [comment]
@PanayotCankov  Could you please elaborate a little bit more on your solution. I've tried to add an event listener on the Page instance:
```
pages.Page.call(this);
pages.Page.on("navigatedTo", function (eventData) {
                  console.log('navigatedTo');
                  });
```
but I get the following error:
`pages.Page.on is not a function.`

**Comment by NathanaelA** [comment]
@MartienB: 
1. in the new page.xml add \<Page **navigatedTo="myNavigatedTo"**/\>
2. In yournew  page.js add: 
```
exports.myNavigatedTo = function(args) {
  console.dump(args.context);
};
```
Which should print out "items" and what is in the items object.

**Comment by PanayotCankov** [comment]
[I was suggesting to add here:](https://github.com/PanayotCankov/nativescript-ios-fsimageviewer/blob/master/app/image-viewer-page.js#L47)
```
var ImageViewerPage = function() {
    pages.Page.call(this);
    // ...
    // Probably re-implement the initWithOwnerImageSource as initWithOwner
    var imageViewController = ImageViewerPageController.alloc().initWithOwnerImageSource(this, photoSource);
    this._ios = imageViewController;
    this.on("navigatingTo", function(args) {
        console.log("Context: " + args.context);
        // Make a photoSource out of the args.context
        imageViewController.imageSource = photoSource;
    });
} 
```

However @NathanaelA's suggestion is quite good. You can instead will add `navigatedTo` event [here](https://github.com/PanayotCankov/nativescript-ios-fsimageviewer/blob/master/app/photos-page.xml#L1) by adding `<ivp:ImageViewerPage xmlns:ivp="image-viewer-page" navigatedTo="myNavigatedTo">`, and his snippet in a new `photos-page.js` file near the existing .xml one:
```
exports.myNavigatedTo = function(args) {
    console.log("Context: " + args.context);
    // Make a photoSource out of the args.context
    args.object._ios.imageSource = photoSource;
});
```

`pages.Page` probably yelds the Page constructor function, you need the actual instance to add events to.

**Comment by MartienB** [comment]
@NathanaelA & @PanayotCankov thank you for your help. I successfully implemented a solution based on @PanayotCankov's approach!
