### ISSUE TITLE
No documentation for the SegmentedBar widget

### ISSUE THREAD

**Issue by nikolay-diyanov** [NativeScript/NativeScript#147]
There is no mention of the SegmentedBar widget here: http://docs.nativescript.org/ui-views.html There should be a section about it.

**Comment by Qandil** [comment]
Am not sure but are you looking for this ?

http://docs.nativescript.org/ApiReference/ui/segmented-bar/SegmentedBar.html

**Comment by enchev** [comment]
We've updated our docs with latest components:
https://github.com/NativeScript/docs/blob/master/ui-views.md#segmentedbar

**Comment by nikolay-diyanov** [comment]
Great, thanks!

**Comment by manijak** [comment]
Could someone please update the docs again for this module? The How-to doesn't look too good, and there aren't any examples on events (tap). 

https://github.com/NativeScript/docs/blob/master/ApiReference/ui/segmented-bar/HOW-TO.md

Thanks

**Comment by sitefinitysteve** [comment]
@manijak ...are there even events?  I feel like there should be, but the tasks sample seems to hook into property changed on the binding itself rather than the better (IMO) event trigger...?

**Comment by jlooper** [comment]
+1, I'm dealing with segmentedBar as well. XML sample would be good, as well as how to make things happen when you switch from one button to the other.
![qpu5pij6usd4u5tp5-r8uww25l9tqwp9f0xndsmqdng](https://cloud.githubusercontent.com/assets/1450004/9721382/8b9e97e0-5567-11e5-92ce-1d181288f7e2.png)

**Comment by sitefinitysteve** [comment]
@jlooper ...I feel like it's just...missing? TabView has it https://github.com/NativeScript/NativeScript/blob/master/ui/tab-view/tab-view-common.ts#L90

**Comment by manijak** [comment]
Yeah, it's not there.
I guess our Observable object needs to do the work for us. Bind a property on the selectedIndex of the segmentedbar to the observable, and listen to propertyChangeEvent. When the user taps the buttons, it will fire propertyChangeEvent on the obsevable, compare the property name, and there you go. 

That beeing said, I do agree that it should behave similar to TabView, just without the predefined views. Or at least not be "observable dependent" all the way.

**Comment by sitefinitysteve** [comment]
@manijak 
...what do we do here then, open a new issue?

**Comment by manijak** [comment]
I guess we should, this one is closed so I don't think any of the Telerik developers has seen our posts.

**Comment by sitefinitysteve** [comment]
@manijak Go for it, I'll support it :)
