### ISSUE TITLE
Update/Add documentation articles

### ISSUE THREAD

**Issue by hshristov** [NativeScript/NativeScript#1471]
In 1.6 release
- [x] Layouts article. (https://github.com/NativeScript/docs/issues/137) (https://github.com/NativeScript/docs/issues/124)
  (https://github.com/NativeScript/docs/issues/154) (https://github.com/NativeScript/docs/issues/7)
- [x] Styling the AppBar
- [x] Organize all of the getting started articles in one folder structure
- [x] Revise UI: The Basics article and move the advanced content in separate articles
- [x] contributing to cross-platform modules (from customer) 
- [x] Improve FAQ
- [x] Testing (http://blog.technokrat.nl/2015/10/13/writing-tests-for-nativescript-apps/)
- [x] Releasing to the App Store and Google Play (https://github.com/NativeScript/docs/issues/150)
- [x] How to work with custom components and the builder.

In 1.7
- [ ] Add an article about launch screens and icon.
- [x] Documentation about how to use icon font codes in a bound element(https://github.com/NativeScript/NativeScript/issues/1197)

In 1.8
- [ ] Handing and reporting unhandled JS and native exceptions
- [ ] Working with images (similar)
- [ ] Working Offline - working with connectivity module
- [ ] Global variables (https://github.com/NativeScript/docs/issues/141)

Next
- [ ] Working with local data
- [ ] Add link to all CLI commands in the documentation (https://www.npmjs.com/package/nativescript#quick-start)
- [ ] Localization
- [ ] Writing responsive views -  (use some content from here http://docs.nativescript.org/navigation#supporting-multiple-screens) 
- [ ] Theming
- [ ] Include the list of plugins http://plugins.telerik.com/ and  https://www.npmjs.com/search?q=nativescript+

**Comment by hamorphis** [comment]
https://github.com/NativeScript/docs/pull/249
