### ISSUE TITLE
Feature request: Audio!

### ISSUE THREAD

**Issue by benkaiser** [NativeScript/NativeScript#1475]
I would like to play music from the filesystem or from a URL. The Android MediaPlayer class does both of these.

I came looking for this when [nativescript-sound](https://www.npmjs.com/package/nativescript-sound) didn't quite cut it as it only played songs for 5 seconds.

**Comment by enchev** [comment]
Hey @benkaiser,

Maybe it will be better to [extend/fix the plug-in itself](https://github.com/jbristowe/nativescript-sound/issues). Hey @jbristowe what do you think?

**Comment by enchev** [comment]
You can use this plugin also: https://github.com/NathanWalker/nativescript-ezaudio

**Comment by benkaiser** [comment]
@enchev thanks for the suggestions. That framework looks like it binds to something specific to iOS?

But yes I think I'll give it a shot implementing it and the bindings for android, and let someone else add the iOS bindings.

**Comment by tinchou** [comment]
In HTML we have the simple `Audio` object to easily play some audio, and also `AudioContext` and friends for more complex scenarios.

Are there any plans to make them work natively?
