### ISSUE TITLE
Stuff about "frame.topmost().goBack()"

### ISSUE THREAD

**Issue by wisonye** [NativeScript/NativeScript#1477]
Actually I want to ask How to let "frame.topmost().goBack();" can have a animation( slide from right to left ) ? ? ?

**Comment by hamorphis** [comment]
With 1.6.0 we will release the Page Navigation Transitions feature: https://github.com/NativeScript/NativeScript/pull/1473

Simply do the following when navigating to a page:
```
frame.topmost().navigate({
    moduleName: "some-page",
    animated: true,
    navigationTransition: {
        transition: "slide"
    },
});
```

You will go to "some-page" with a slide transition. When you go back the reverse transition will be played. 

Here are the docs: https://github.com/NativeScript/docs/blob/production/core-concepts/navigation.md#navigation-transitions
