### ISSUE TITLE
Watch speed slow after install "nativescript-dev-typescript", any idea ? :)

### ISSUE THREAD

**Issue by wisonye** [NativeScript/NativeScript#1478]
Hello buddy, I use TypeScript to coding NativeScript project for a while, it is very great, but I'm not happy one thing: 

Before use TypeScript, the "livesync" command is very fast, hit save then you can see the CLI detect and refresh the mobile app in simulator, but AFTER I install "nativescript-dev-typescript", the "livesync" command is very slow than before!!!! When save a ts file, need to wait at least few seconds( sometime 5 seconds and more ) before you see the CLI start detect the file change and compile, and even sometime change XML, the CLI seems didn't know that( unless I write something in ts file and save ),  it's very Annoying, but nothing I can do, I take a look the file:

```javascript
https://github.com/NativeScript/nativescript-dev-typescript/blob/master/lib/watch.js
```

But seems nothing can change to improve the speed, any idea on this ? :)

**Comment by hdeshev** [comment]
I'm seeing this problem with plain `tsc watch` calls, for example [here](https://github.com/NativeScript/sample-ng-http/tree/master/web), and that's what the TypeScript plugin uses too.

I remember seeing it first after upgrading to TypeScript 1.7.5 first, and it could be related to Microsoft/TypeScript#6016, but I always thought it was a Linux-only issue (using mostly Linux myself).

You can try downgrading to TypeScript 1.7.3, and see if that makes things better.

**Comment by bradmartin** [comment]
What's your IDE? I use both VS Code and VS2015, VS Code is slow just like you said. However using VS2015, the typescript compiles really fast with LiveSync. Just my observations.

**Comment by wisonye** [comment]
@hdeshev @bradmartin Actually after I read a lot of "issue" and "release bug fix"( https://github.com/Microsoft/TypeScript/issues/6178 ), finally, I fount that 1.8.0 fixed this issue, what I did is that :

1) Go into my NativeScript project root folder, uninstall the "1.7.5"

```javascript
npm uninstall typescript
```

2) And then install the "1.8.0" and save to package.json

```javascript
npm install typescript@1.8.0 -s
```

Done, that's all, i try many times, perfect right now :)

**Comment by enchev** [comment]
Thanks for the info @wisonye! I'm closing this.
