### ISSUE TITLE
Rescale on Orientation Change

### ISSUE THREAD

**Issue by vbresults** [NativeScript/NativeScript#1480]
While testing, as I mentioned to @NathanaelA , I found the font size was too small in iPad portrait and too big on iPhone landscape, but the perfect size on iPad landscape and iPhone portrait.

In other words, the base unit of display (DIP, or whatever) is perfect on the standard orientation of each device, but when the orientation changes, the base unit does not rescale to the new orientation.

And so, we'd have to step into making several page XML's for each major device type on each platform.  This is overkill and a lot time and trouble could be saved by simply rescaling this base unit.

Is this technically possible?

**Comment by adisoftbn** [comment]
I need to scale the entire UI based on Width resolution. Did you succeed?

We want to code the entire UI for 320DPI and then dynamicaly scale everything to the device DPI, to make it look like it had 320DPI.

We work only on Portrait Mode.

**Comment by vbresults** [comment]
@adisoftbn I long abandoned designing the app this way and use percentage widths and gridlayout instead (which could largely work for you); it really only leaves out fonts from scaling.  I think @NathanaelA has an orientation plugin that works roughly the same as the one I wrote does; I wrote mine to scale the fonts and Nathan's could serve the same purpose for you
