### ISSUE TITLE
Nativescript AbsoluteLayout not refresh layout childs on device orientation change

### ISSUE THREAD

**Issue by baromir** [NativeScript/NativeScript#1482]
I am build a application that need put a transparent iOS status bar  and a map behind. to do this I am using a Nativescript AbsoluteLayout. Y add the view to the absolute layout and all working as expected the problems is when the device orientation change. the childs off the absolute layout not refresh their dimension.

init orientation:.
![screen shot 2016-02-01 at 8 08 54 am](https://cloud.githubusercontent.com/assets/12832002/12782396/14dc8ca0-ca49-11e5-887b-a6c905cd58a1.png)

after orientation change:
![screen shot 2016-02-01 at 8 10 56 am](https://cloud.githubusercontent.com/assets/12832002/12782409/2ae5fa5e-ca49-11e5-88c5-300c6acce869.png)

attached protect for test
[absLayoutTest.zip](https://github.com/NativeScript/NativeScript/files/115675/absLayoutTest.zip)

**Comment by PanayotCankov** [comment]
AbsoluteLayout does not apply any layouting at all. It just places its children at predefined positions with predefined sizes. You can try replacing the AbsoluteLayout with GridLayout. That layout will try to rearrange its children including when the orientation is changed. I am not sure how the Placeholder and the native view will react in your scenario but it does not work there are methods such as the [onLayout](https://github.com/NativeScript/NativeScript/blob/master/ui/core/view.d.ts#L379) that you can override to position the child native view based on the provided arguments.

Also if you are using an AboluteLayout just to move the content behind the status bar then a GridLayout should be able to move a little bit up by using a negative margin... this is somewhat hacky though.

In the long term we already have an `backgroundStretchUnderStatusBar` for iOS and we will consider adding somewhat mechanism to move the content under the status bar too.

**Comment by baromir** [comment]
Thanks for your answer, i have to change the margin from -20 to 0 in iphone 6 when orientation changes because  the status bar on landscape orientation it is hidden

**Comment by PanayotCankov** [comment]
I would suggest you check the API reference documentation about our application module. The "application" module exposes a cross platform orientation changed event.

Something like this should work:
``` JavaScript
var application = require("application");
application.on(application.orientationChangedEvent, function(args) {
    console.log(args.newValue);
});
```
