### ISSUE TITLE
Android 4.2 - Webview scroll explode

### ISSUE THREAD

**Issue by tolpit** [NativeScript/NativeScript#1484]
On **Android 4.2** when you scroll inside the Webview, the content scroll at differents speed, and some elements who are lower in the page pass in front of the content. The problem doesn't occur on the native browser for the same url. Or In upper Android version inside Webview.

Could the problem come from the website itself ?

**Comment by bradmartin** [comment]
What's the site address? It sounds like a parallax effect but strange it's not on all browsers. Have you tried it in a desktop browser (Chrome)?

**Comment by tolpit** [comment]
It's : http://www.unifrance.org
Yeah it's like some kind of parallax effect, but not wanted :)
Tested in some desktop and mobile browsers : no parallax problem.

**Comment by bradmartin** [comment]
@tolpit - Can you catch a few screens from your device running the site? I'd like to see what you are seeing, I might have an idea on a work around but not sure :)
