### ISSUE TITLE
Ability to define a custom view in ActionItem

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#1488]
Add ability for ActionItem to have a custom view associated with it, instead of using predefined icon/text. For example something like:
```XML
<ActionBar title="Something">
  <ActionBar.actionItems>
	<ActionItem ios.position="right" tap="doneTap">
		<ActionItem.actionView>
			<StackLayout>
				<Label text="Label1" backgroundColor="red"/>
				<Label text="Label2" backgroundColor="green"/>
			</StackLayout>
		</ActionItem.actionView>
	</ActionItem>
  </ActionBar.actionItems>
</ActionBar>
```
Implementation suggestion:
**For iOS** -  use ```- (id)initWithCustomView:(UIView *)customView``` of the UIBarButtonItem. The catch is that in order to be able to handle tap the custom view must be a button. So the custom view must be added as a sub view to a UIButton. And then the UIButton should be passed to the initWithCustomView method. 

**For Android** - use ```setActionView``` of MenuItem http://developer.android.com/reference/android/view/MenuItem.html#setActionView(android.view.View)

**Comment by enchev** [comment]
Hey @PeterStaev,

Great suggestion! If you have already something working you can submit pull request and we will gladly help with the implementation.

**Comment by PeterStaev** [comment]
@enchev  not exactly like this, but have made something similar in a custom actionbar implementation. So will see if to plug it in the {N} code.

**Comment by LeDinhsmarp** [comment]
I'm sorry but I quite don't get your solution. I'm quite new to NativeScript, do you have a simple sample app about ActionBar and ActionItem customization? I would appreciate really much.

**Comment by vchimev** [comment]
@LeDinhsmarp, you could find a sample page here: https://github.com/NativeScript/NativeScript/blob/master/apps/ui-tests-app/action-bar/action-view.xml.

**Comment by bfattori** [comment]
How about *without* having to use XML? I'm trying to approach the ActionBar programmatically, yet all examples start with XML.

**Comment by enchev** [comment]
Hey @bfattori,

You can create some View (for example Label) and assign in to ActionItem actionView property:
https://github.com/NativeScript/NativeScript/blob/master/ui/action-bar/action-bar.d.ts#L124

**Comment by sitefinitysteve** [comment]
I LOVE YOU GUYS

**Comment by vjoao** [comment]
I LOVE YOU GUYS [2]

**Comment by chief10** [comment]
Does this work with "android.position='popup' ?  For me, it is not working and places the inner items outside of the popup and into the action bar.

Here is the code for my action items -- the third one has the inner label:

```xml
 <ActionItem text="Change Layout" android.position="popup" (tap)="changeDisplayOfItems()"></ActionItem>
    <ActionItem text=" Sort by cost" android.position="popup" (tap)="sortItemsBy('size')"></ActionItem>
    <ActionItem android.position="popup" (tap)="addNewItem()">
      <Label text="Hi"></Label>
    </ActionItem>
    <ActionItem text="Account Info" (tap)="accountInfo()" android.position="popup"></ActionItem>
```

But this is what is happening:

![actionitem](https://cloud.githubusercontent.com/assets/2761499/18110830/8412dff4-6ecf-11e6-9469-cacaec12505d.png)
