### ISSUE TITLE
Animation broken in Android if used from onNavigatedTo (or earlier events)

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#1495]
If you attempt to use someElement.animate({opacity: x...}) on any element from the pageloaded or navigatedto event, the _createUI code may not have ran and so when it tries to manipulate the nativeView which is null which of course crashes it.

I think really the onNavigatedTo event should be fired after the page has actually been created; so that the elements exists as they should.

**Comment by hamorphis** [comment]
I tried the following with the modules from master and it works like a charm.
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatedTo="onNavigatedTo">
  <Label id="label" text="Animate me" style.backgroundColor="red"/>
</Page>
```
```
function onNavigatedTo(args) {
    var page = args.object;
    var label = page.getViewById("label");
    label.animate({ opacity: 0, duration: 5000 });
}
exports.onNavigatedTo = onNavigatedTo;
```

Here is my project: https://www.dropbox.com/s/nql8hqaavl5vxba/VSDevApp.zip?dl=0
