### ISSUE TITLE
meaning of , "No value for main"??

### ISSUE THREAD

**Issue by jjTudu** [NativeScript/NativeScript#1496]
whenever i add new package(Casperjs) through npm, and use require in view-model. i gets this error, if i comment it out, it runs perfectly. Do i have to use require elsewhere in app.js, or some other files
My System:windows 7
 and how to log error through --stacktrace??

**Comment by enchev** [comment]
Can you verify if this package is not node.js and/or web specific?

**Comment by jjTudu** [comment]
i found out, it is web specific, if i am not wrong

**Comment by jjTudu** [comment]
l was looking to scrap the dynamic webpage with it(ability to click a link), now i changed my approach, i thought it wil be better in Web Service Approach.

**Comment by slavchev** [comment]
@jjTudu 

I don't know if it is too late but our `require` logic has fallback to `index.js`. Probably it is good idea to check if this file exists.

**Comment by jjTudu** [comment]
yes index.js is present

**Comment by slavchev** [comment]
@jjTudu 

Recently other people reported the same problem. We haven't resolved it yet but we have some clues. In case you haven't found a workaround I would suggest to see my comment https://github.com/NativeScript/android-runtime/issues/355#issuecomment-183253640

The new runtime solved the issue and our tests pass but we still wait for confirmation from other people. I would love to hear your feedback in case you have time to try it.
