### ISSUE TITLE
Component life cycle

### ISSUE THREAD

**Issue by nripendra** [NativeScript/NativeScript#1497]
Hi,

Does the nativescript component have lifecycle events? For example in reactjs we have componentDidMount, componentDidUpdate etc. I think these would be valuable for someone wanting to create new components out of existing ones. 

Regards,
Nripendra

**Comment by hdeshev** [comment]
`View` subclasses have the [loaded/unloaded events](https://docs.nativescript.org/ApiReference/ui/core/view/View) which fire when you get attached to the visual tree. You can also detect changes to the component via [property change events](https://docs.nativescript.org/core-concepts/events#propertychange-event), and use the sophisticated [dependency property system](https://docs.nativescript.org/core-concepts/properties).

**Comment by nripendra** [comment]
Thanks!
