### ISSUE TITLE
Feature Request: Add addition Binding row number

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#1499]
If I create a listview.items = [1,3,5,7,9,11];  I would like to be able to print 
```
<ListView id="listview">
<StackLayout orientation="horizontal">
<Label text="{{$parent.index}}"/>
<Label text="="/>
<Label text={{$value}}/>
<ListView>
```
So it would print 0=1,1=3,2=5,3=7,4=9,5=11

What I want is the Index of the current array loop it is using.   The actual issue I'm trying to solve is putting buttons into a ListView does not send the realizedIndex to the button so you have no idea which button is being pressed.   It would be nice if I could just do \<Button realizedIndex="{{$parent.index}}"> and then I could easily access the realizedIndex like I would on a normal listview tap.

**Comment by PanayotCankov** [comment]
I don't know if this would help, but shouldn't the `args.object.bindingContext` in the tap handler be the data item for which the button is tapped, and work your way with it? In the case with the numbers, especially if there is a repeating one, it won't help much.

**Comment by enchev** [comment]
Hey @NathanaelA,

Actually $parent refers to parent bindingContext and we do not want to inject dynamically something additional like row number. If you want to get the row number you can easily use itemLoading event args.index.

**Comment by NathanaelA** [comment]
@PanayotCankov - Interesting, I didn't know the bindingContext at that point was the specific row... Very very nice!   Doesn't quite give me the dataset index; but it does give me a slightly better work around.

@enchev - That might work, but it also requires adding a more work;  I can do the same thing easier just iterating my data set and adding an index value.  The idea is to eliminate the "busy" work and have the framework provide a value it should already know as it is iterating through the dataset to display the items.   Using $parent.index was just an example; I don't care if it is __index or $data.index

If this isn't something that you guys want to add; that is perfectly fine.  It isn't critical; I already have a work around that I am using and a couple more if I need them.     But I figured I would make the request  as this seems like something that could benefit the framework.
