### ISSUE TITLE
Do typescript files need to be compiled to js before they work?

### ISSUE THREAD

**Issue by ritcoder** [NativeScript/NativeScript#15]
I'm following the getting started tutorial.
1. Created the project using tns and it runs fine on the android device
2. Opened the folder as a website in visual studio and added a few files (sighnpView.xml and signUpView.ts). The .ts files do not compile on save.
3. I run the project and the alert statement in the onLoad function does not fire.
4. I added a new file "signupView.js" and it works just fine.

Is nativescript supposed to compile the typescript files or I'll have to make sure the correct js files exist? Not sure if I should add a gulp task to do the compilation.

Thanks.

**Comment by soone** [comment]
I have the same trouble, how to use typescript to run app?

**Comment by fealebenpae** [comment]
Yes, you'll need to compile TypeScript to JavaScript manually or with a build step. NativeScript's support for TypeScript right now means that we support TypeScript constructs such as class inheritance when working with native Java or Objective-C classes, but the code has to be compiled to JavaScript before NativeScript can run it.
