### ISSUE TITLE
Listview item binding to observable

### ISSUE THREAD

**Issue by nripendra** [NativeScript/NativeScript#1500]
I'm binding a listview to an ObservableArray, and it is working great. Each item in observable array is also observable. When the viewmodel of individual item changes, the list item is not reflecting the change. What should be the solution?

**Comment by enchev** [comment]
Can you post more info how exactly this module is changed and what is not reflected?

**Comment by nripendra** [comment]
Let's say I have these class:

```ts
class Item : Observable{
   name: string;
   //...more code..
}
class Viewmodel {
   items: ObservableArray<Item> = new ObservableArray<Item>();
   constructor(){
       this.fetchData();
   }
   fetchData() {
      fetch(serviceUrl).then(response => {
          response.toJson().then(data => { this.items.push([...data]) });
      });
   }
}
```
Now, list is binding with items property of viewmodel:

```xml
<ListView id="mainListView" items="{{items}}" itemTap="onItemTapped">
  <ListView.itemTemplate>
    <Lable text={{name}} />
  </ListView.itemTemplate>
</ListView>
```
The list is binding, and I can see the list of item name, but when one of the item changes, then it is not reflected. 

But, if I add/remove item in the ObservableArray, then it seems to be reflecting. So basically change to array is getting observed, but changes to individual items are not.

One work-around I have figured out so far is to explicitly call mainList.refresh().

**Comment by enchev** [comment]
Can you post also how your Item class will notify when the property value is changed?

**Comment by nripendra** [comment]
Something like this:

```ts
export function onItemTapped(args) {
  var listItem = args.view;
  var bindingCtx = listItem.bindingContext;
  bindingCtx.name = "changed";
}
```

**Comment by enchev** [comment]
Hey @nripendra,

I'm asking about the code in your `Item` class which inherit from our `Observable` class. Can you post your `Item` class `name` property implementation and more specifically do you call `propertyChanged` and with what args in your property setter.

**Comment by nripendra** [comment]
Hi @enchev 

The `name` property is as shown above, there is no extra code involved. I'm exposing public property and getting/setting it.

Regards,
Nripendra

**Comment by enchev** [comment]
Hey @nripendra,

In this case I suggest you to check our [TelerikNEXT app](https://github.com/NativeScript/sample-TelerikNEXT/blob/master/app/app-view-model.ts#L278-L288) for example to know more about how to inherit from Observable, how to notify when your property value is changed, etc.
