### ISSUE TITLE
RadListView is choppy on iOS

### ISSUE THREAD

**Issue by Ivshti** [NativeScript/NativeScript#1504]
First of all, I don't know if this is the right repo, and second - there's no more technical detail/information about my issue that I can provide.

The issue is that the RadListView is noticeably choppy on iOS compared to Android when scrolling (kinetic scroll). This happens on emulator AND a real 5s device, with the Examples app (Item Layouts) and on emulator (iPhone 6s) and my own application.

The "choppyness" is essentially non-smooth scrolling - once the scrolling is started it slows down periodically a few times a second in a symmetrical (periodic) way.

**Comment by ginev** [comment]
Hello @Ivshti ,

We are aware of this behavior and are actively working on resolving the issue so stay tuned for updates.

When it comes to the UI suite, it is best to comment in the dedicated repo: https://github.com/telerik/nativescript-ui-samples/issues

Thanks!

**Comment by Ivshti** [comment]
@ginev thanks for the update

Primarily reason we use RadListView is because of the load on demand - to avoid memory issues on Android. Considering iOS is ran on powerful devices, can we use ListView with a Wrap/Grid layout template in place of the RadListView as a workaround?

**Comment by enchev** [comment]
This issue was moved to telerik/nativescript-ui-samples#58
