### ISSUE TITLE
Can only use PNG images on iOS

### ISSUE THREAD

**Issue by mmillican** [NativeScript/NativeScript#1505]
It appears that you can only use `.PNG` images in iOS and those image paths must end in `.png`.

For example, this URL does not work:
https://placeholdit.imgix.net/~text?txtsize=38&bg=ff0000&txt=400%C3%97200&w=400&h=200&fm.png

**Comment by manijak** [comment]
I use both gif, jpg and png in my app. work just fine. 

I see you are adding image via http/https. You can try and launch the app via xcode and see if there are any errors. In iOS 9.1 by default, it does not like loading images (or resources) externally, so you need to add explicit permissions in the .plist file for which domains to allow.

**Comment by enchev** [comment]
Hey @mmillican,

I've just tested this XML&
```XML
<Page>
  <StackLayout>
     <Image src="https://placeholdit.imgix.net/~text?txtsize=38&bg=ff0000&txt=400%C3%97200&w=400&h=200&fm.png"/>
  </StackLayout>
</Page>
```

and here is the result:
![screen shot 2016-02-08 at 4 37 53 pm](https://cloud.githubusercontent.com/assets/5804953/12888361/6575db20-ce82-11e5-8452-b19b3c4c684c.png)

**Comment by mmillican** [comment]
@manijak  interesting.  I tried JPGs locally in `App_Resources` with no luck.  I'll give it another shot.
@enchev I think it's the `.plist` issue described above perhaps.  Going to look into this more later today.
