### ISSUE TITLE
Switch status not taken into account in 'or' expression

### ISSUE THREAD

**Issue by dragGH102** [NativeScript/NativeScript#1507]
I tried to use || expressions to determine the isEnabled attribute of a Button based on page's context.

```
var pageData = new observableModule.Observable({
    ss: { // switchers status
        's1': false,
        's2': true,
        's3': false
    }
});

exports.loaded = function(eventData) {
    // binding context
    page = eventData.object;
    page.bindingContext = pageData;
};
```

```
    <StackLayout horizontalAlignment="center" width="400">
        <Switch checked="{{ ss.s1 }}" horizontalAlignment="center" />
      	<Switch checked="{{ ss.s2 }}" horizontalAlignment="center" />
      	<Switch checked="{{ ss.s3 }}" horizontalAlignment="center" />
      	<Button text="Click me" horizontalAlignment="center" isEnabled="{{ ss.s1 || ss.s2 || ss.s3 }}" />
    </StackLayout>
```

Even when all switched are off, the button is still enabled.

Sample project to reproduce the issue (tested on **Android**, {N} and Android runtime latest):

https://github.com/dragGH102/nativescript-sample-switch-button-binding

**Comment by enchev** [comment]
Your `s2` value is `true` and the expression will assign true for isEnabled.

**Comment by dragGH102** [comment]
@enchev yes, I know. I wanted just to provide an example. The point is: even if **all** the switches are off, the button **is** enabled

**Comment by NathanaelA** [comment]
@enchev -- I agree with @dragGH102, buttons don't seem to allow the isEnabled to be changed via declarative UI.  I saw the same thing occur in a ListView where even though the button should be disabled on startup (all values are null or false) all the buttons were still enabled.

**Comment by dragGH102** [comment]
@NathanaelA I think it would appropriate to turn it into a **bug** rather than a question

**Comment by NathanaelA** [comment]
@dragGH102 - I have no control over this or any other Telerik repo, I'm just another NativeScript user like you.

**Comment by dragGH102** [comment]
@NathanaelA ok, @enchev then :)
I thought you were somehow a contributor of the repo because I see you are very activate and hellful around

**Comment by enchev** [comment]
Hey folks,

Here is what I have for both iOS and Android with three false.
![android](https://cloud.githubusercontent.com/assets/5804953/12911548/f7dc932a-cf1b-11e5-8587-ad5b6c35a2aa.png)
![screen shot 2016-02-09 at 10 57 11 am](https://cloud.githubusercontent.com/assets/5804953/12911562/0ac70286-cf1c-11e5-8c6b-ac635568b511.png)

**Comment by dragGH102** [comment]
@enchev what if one or more are actually true?
what's your configuration?
because with latest {N} and Android runtime on Linux it doesn't work for me

**Comment by enchev** [comment]
If you return `true` from just one of the items no matter which you will have `true` as final expression. More info can be found for example here:
https://addyosmani.com/blog/exploring-javascripts-logical-or-operator/

**Comment by dragGH102** [comment]
@enchev logical operator in JS are pretty straightforward :-) in my environment it doesn't work. if you could provide your environment details as well as the precise modifications you did to have the button enabled/disabled would be nice
perhaps @NathanaelA you can give it a try?

**Comment by NathanaelA** [comment]
@enchev I just found out if the bound value is "undefined" it doesn't evaluate it as false...  :-(   

binding.someUndefinedValue = undefined;
\<Button isEnabled="{{someUndefinedValue}}" text="Hi" />

The button will still be enabled.   Not the expected behavior in my case; but explains why my buttons weren't disabling in my list view.   I was only expecting the button to be enabled if it == true.

**Comment by dragGH102** [comment]
@enchev @NathanaelA never mind.
Instead of 

```
var pageData = new observableModule.Observable({
    ss: { // switchers status
        's1': false,
        's2': true,
        's3': false
    }
});
```

I used s1,s2,s3 directly (not nested in ss) both in .ts and .xml and it worked like a charm. Not sure whether this is a bug or not

**Comment by dragGH102** [comment]
Sorry to reopen this but I noticed some strange behavior.
Still based on the previous example (modified a bit): https://github.com/dragGH102/nativescript-sample-switch-button-binding

I normally define page bindings by:

var pageData = new observableModule.Observable({// switchers status
    var1: 'value', // val1 of type string 
    var2: 12, // var 2 of type number
    var3: false // var 3 of type boolean
   etc.
});

whereas binding in code is {{ var1 }}, {{ var2 }} etc.

In my sample project (see above) I use
   's1': true, (with inverted commas)
  's2': false,
  etc.

What I don't understand is since it's an object we pass to Observable, **property names should be just propertyName **(without inverted comma). However it appears to work anyway (with or without inverted commas)

Just as a side note: in this specific example it doesn't work in either cases (I don't understand why) but in the app I'm developing it works exactly as described (with the same issue)

**Comment by nsndeck** [comment]
I've just made a pull request that upgrades the example to 1.7.1 version of NativeScript, also a small fix in code. Now example (according to me) works just fine.
