### ISSUE TITLE
Handling custom protocol scheme.

### ISSUE THREAD

**Issue by nripendra** [NativeScript/NativeScript#1513]
Hi,

I have registered a protocol scheme (CFBundleURLTypes) in my plist file. How do i handle incoming request in the app?

Regards,
Nripendra

**Comment by enchev** [comment]
You need to assign your own [custom delegate](https://github.com/NativeScript/NativeScript/blob/master/apps/tests/app/app.ts#L13-L26) for your app and provide openURL method. For example:
```JavaScript
class MyDelegate extends UIResponder implements UIApplicationDelegate {
    public static ObjCProtocols = [UIApplicationDelegate];

    applicationOpenURLSourceApplicationAnnotation(application: UIApplication, url: NSURL, sourceApplication: string, annotation: any): boolean {
        // Your code goes here
    }
}

application.ios.delegate = MyDelegate;
```

**Comment by nripendra** [comment]
@enchev 

Thanks!

**Comment by hypery2k** [comment]
I Currently working on a plugin for this: https://github.com/hypery2k/nativescript-urlhandler
