### ISSUE TITLE
TabView: "TypeError: this.page.frame._getNavBarVisible is not a function" when swiping left and then right

### ISSUE THREAD

**Issue by dragGH102** [NativeScript/NativeScript#1517]
I am using TabView component.
Apparently the issues I got is due to including pages inside tabItem content (xml includes)

I created a sample project to show the issue: https://github.com/dragGH102/nativescript-sample-tab-view

**How to reproduce**: swipe left-left (until third tab) and then right (tested on **Android**)

**Error stacktrace**:

```
com.tns.NativeScriptException: 
Calling js method instantiateItem failed

TypeError: this.page.frame._getNavBarVisible is not a function
File: "/data/data/org.nativescript.nativescriptsampletabview/files/app/tns_modules/ui/action-bar/action-bar.js, line: 124, column: 49

StackTrace: 
	Frame: function:'ActionBar.update', file:'/data/data/org.nativescript.nativescriptsampletabview/files/app/tns_modules/ui/action-bar/action-bar.js', line: 124, column: 50
	Frame: function:'ActionBar._createUI', file:'/data/data/org.nativescript.nativescriptsampletabview/files/app/tns_modules/ui/action-bar/action-bar.js', line: 118, column: 14
	Frame: function:'View._onContextChanged', file:'/data/data/org.nativescript.nativescriptsampletabview/files/app/tns_modules/ui/core/view.js', line: 202, column: 14
	Frame: function:'View._onAttached', file:'/data/data/org.nativescript.nativescriptsampletabview/files/app/tns_modules/ui/core/view.js', line: 160, column: 14
	Frame: function:'eachChild', file:'/data/data/org.nativescript.nativ
```

**Comment by enchev** [comment]
Hey @dragGH102,

Please use some layout as root for your custom components instead Page. You do not need also the StackLayout, TabView can be assigned directly as Page content.

**Comment by dragGH102** [comment]
@enchev thank you.
Apparently using a DockLayout/StackLayout directly instead of `<Page> + <Dock/StackLayout> `solved the issue.
Just for information: I'm using <Page> instead of a direct layout also for modals (showModal()).**is it appropriate (or better) to remove <Page> also for modals?**

Also, when defining the **binding context** (bindingContext) and using **getViewById**(<other_layout>, id), **do they still work with a non-page container?**

e.g. 

**includes/modal1/modal1.xml**

```
<Page loaded="loaded"> <!-- remove this -->
    <StackLayout id="modal-container">
        <Label id="my-id" text="{{ contextElement }}" />
    </StackLayout>
</Page> <!-- remove this -->
```

**includes/modal1/modal1.ts** (or the page included in TabView)

```
import ObservableEventData = require("data/observable");
import observableModule = require("data/observable");

import {getViewById} from "ui/core/view";

let includeContainer;

let pageData = new observableModule.Observable({
    contextElement: "123"
});

exports.loaded = function(eventData: ObservableEventData) {
    includeContainer = eventData.object;
    includeContainer.bindingContext = pageData;
    getViewById(includeContainer, "my-id").height = 80;
};
```

Apparently everything works but I want to make sure it's the right way to make it

Thank you

**Comment by enchev** [comment]
Hey @dragGH102, 

`getViewById()` should work normally without page. For modal pages you will still need Page tag however you can reuse content as custom components.

**Comment by cho-is** [comment]
I am experiencing the same error.
I am just trying to use Angular2 hello world example and from there implement TabView. 
```
import {Component} from "angular2/core";

import {StackLayout} from 'ui/layouts/stack-layout';
import {Label} from 'ui/label';
import {TabView, TabViewItem} from 'ui/tab-view';


@Component({
    selector: "my-app",
    template: `
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="pageLoaded">
  <TabView>
    <TabView.items>
      <TabViewItem title="First">
        <TabViewItem.view>
          <StackLayout class="tab-content">
            <Label text="First View" class="title"></Label>
            <Label text="This is the content of the first tab." textWrap="true"></Label>
          </StackLayout>
        </TabViewItem.view>
      </TabViewItem>
      <TabViewItem title="Second">
        <TabViewItem.view>
          <StackLayout class="tab-content">
            <Label text="Second View" class="title"></Label>
            <Label text="This is the content of the second tab." textWrap="true"></Label>
          </StackLayout>
        </TabViewItem.view>
      </TabViewItem>
    </TabView.items>
  </TabView>
</Page>
`,
})
export class AppComponent {
    public message: string = "Hello, Angular!";
}
```

Getting
`EXCEPTION: TypeError: this.page.frame._getNavBarVisible is not a function`

On a side note, I jumped from Ionic2 to NativeScript because of performance issues. I have being testing all of your app samples and they are slow on Nexus4. Is there something that I have to consider here?

**Comment by cho-is** [comment]
Digging a bit more, and testing same behaviour without Angular2, it works.

**Comment by jvzanatta** [comment]
+1

code
`<Page>
    <GridLayout rows="auto, *, auto">

        
        <ActionBar row="0" class="header" title="TCCTreino">
            <ActionItem ios.position="right">
                <Button class="actionbar-button" text="Settings"></Button>
            </ActionItem>
        </ActionBar>

        <GridLayout row="1" class="mid" columns="auto, *">
            <Image col="0" class="img-body" src="~/images/body.jpeg"></Image>
            <StackLayout col="1">
                <Label class="user-data" [text]="user.name"></Label>
                <Label class="user-data" [text]="user.email"></Label>
            </StackLayout>
        </GridLayout>

        <StackLayout row="2">
            <Button class="actionbar-button" text="Settings"></Button>
        </StackLayout>

    </GridLayout>
</Page>`

log

> JS: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
> JS: EXCEPTION: Error: Uncaught (in promise): TypeError: this.page.frame._getNavBarVisible is not a function
> JS: STACKTRACE:
> JS: Error: Uncaught (in promise): TypeError: this.page.frame._getNavBarVisible is not a function
> JS:     at resolvePromise (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:496:32)
> JS:     at /data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:473:14
> JS:     at ZoneDelegate.invoke (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:281:29)
> JS:     at Object.NgZoneImpl.inner.inner.fork.onInvoke (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:46:41)
> JS:     at ZoneDelegate.invoke (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:280:35)
> JS:     at Zone.run (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:174:44)
> JS:     at /data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:529:58
> JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:314:38)
> JS:     at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:37:41)
> JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.TCCTreino/files/app/tns_modules/zone.js/dist/zone-node.js:313:43)
> JS: Unhandled Promise rejection: this.page.frame._getNavBarVisible is not a function ; Zone: angular ; Task: Promise.then ; Value: TypeError: this.page.frame._getNavBarVisible is not a function
> JS: Error: Uncaught (in promise): TypeError: this.page.frame._getNavBarVisible is not a function
