### ISSUE TITLE
How to use SFSafariViewController?

### ISSUE THREAD

**Issue by nripendra** [NativeScript/NativeScript#1519]
Hi,

I just now found that ios 9 supports "SFSafariViewController". Is it possible to use it from nativescript? Please note that I'm not looking for webview, but safari view itself.

Regards,
Nripendra

**Comment by enchev** [comment]
Yep, you can however you need to import [SafariServices.framework](https://developer.apple.com/library/ios/documentation/SafariServices/Reference/SafariServicesFramework_Ref/). The best way in my opinion will be if you create [plugin](http://docs.nativescript.org/plugins/plugins) with native ios part similar to [our PushPlugin](https://github.com/NativeScript/push-plugin)

**Comment by nripendra** [comment]
@enchev 

Sorry to bother again.. Where to call "**presentViewController**" in context of a {N} app?

Regards,

**Comment by nripendra** [comment]
just figured out... this seems to be working. Interestingly I didn't have to do anything to import SafariServices.

```js
export function pageLoaded(args) {
    var page = args.object; 
    var url = NSURL.URLWithString("http://google.com"); 
    page.ios.presentViewControllerAnimatedCompletion(SFSafariViewController.alloc().initWithURL(url), true, null);
}
```
where pageLoaded is attached to page:

```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="pageLoaded"></Page>
```

**Comment by darkyen** [comment]
For anybody else looking https://github.com/bradmartin/nativescript-advanced-webview
