### ISSUE TITLE
Unable to start service. Result code is: 3892314239

### ISSUE THREAD

**Issue by iamlogiq** [NativeScript/NativeScript#152]
I am unable to run the command: tns run ios as I keep getting the above error. Please help! 

Status: CreatingStagingDirectory PercentComplete: 5
Status: ExtractingPackage PercentComplete: 15
Status: InspectingPackage PercentComplete: 20
Status: TakingInstallLock PercentComplete: 20
Status: PreflightingApplication PercentComplete: 30
Status: InstallingEmbeddedProfile PercentComplete: 30
Status: VerifyingApplication PercentComplete: 40
Status: CreatingContainer PercentComplete: 50
Status: InstallingApplication PercentComplete: 60
Status: PostflightingApplication PercentComplete: 70
Status: SandboxingApplication PercentComplete: 80
Status: GeneratingApplicationMap PercentComplete: 90
Status: Complete
Successfully deployed on device [set of numbers]
Unable to start service. Result code is: 3892314239

**Comment by teobugslayer** [comment]
Googling around, I found this thread: https://discussions.apple.com/thread/3390119?start=255&tstart=0 Note, 3892314239 is 0xE800007F in hex.

**Comment by teobugslayer** [comment]
Hello @iamlogiq,

Please open Xcode, go to Window -> Devices, click on your device, then click View device logs. This will show the real error happening on device which will allow us to troubleshoot the real problem.

**Comment by Fatme** [comment]
I suggest you to restart your device and try again. Sometimes there are issues with device's sockets and the restart may fix your issue.

**Comment by iamlogiq** [comment]
Thanks for the reply but none of the options worked :-/
@teobugslayer I did what you suggest and i don't see any logs. It says "No Device Logs". I'm running the default app that is generated with the 'tns create' command, didn't modify anything. I am able to access the app when I click "run" in excode or when I click on the app directly when I see it on my device but I can't seem to have 'tns run ios' to work. My certificates and provisioning are all correct. I dont know what's going on. Please help. 

@Fatme I tried restarting my computer and the device but I get the same error. Please help. 

Thanks

**Comment by Fatme** [comment]
Hi @iamlogiq,

Can you execute `tns run ios --log trace` command and send us the produced log?

**Comment by Fatme** [comment]
Also can you give us more information about your device?

**Comment by Fatme** [comment]
Another thing that you can try is to run `tns device run` command but you need to ensure that your application is deployed on device.

I'm looking forward to hearing the result.

**Comment by iamlogiq** [comment]
@Fatme 
Thanks for the reply. here is what I get when I run tns device run: 

Invalid application id: undefined. All available application ids are:
....

Here are the last few lines I get when I run tns run ios --log trace:

Results at 'nativescript.ipa'
Project successfully built
Using  nativescript.ipa
startLookingForDevices; platform is iOS
Found device with identifier '[my device]'
Found device with identifier '[my other device]'
Unable to start service. Result code is: 3892314239
List of registered commands: /?, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|ios, create, debug, debug|android, debug|ios, deploy, device, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|uninstall, emulate, emulate|android, emulate|ios, feature-usage-tracking, help, library, library|add, platform, platform|add, platform|remove, platform|update, prepare, run, run|android, run|ios
Reading help for command 'run|ios'. FileName is 'run-ios.md'.
# run ios

**Comment by Fatme** [comment]
Hi @iamlogiq,

From the log I can see that you have two connected devices. Unfortunately we have some issues when more than one device is connected. I suggest you to execute `tns run ios --device [device id]` or just to disconnect one of the devices.
I hope this will help you.

**Comment by iamlogiq** [comment]
@Fatme  Same error 

adding: Payload/oosynapsenativescript.app/PkgInfo	(in=8) (out=8) (stored 0%)
total bytes=9397605, compressed=3929784 -> 58% savings
]
Results at 'nativescript.ipa'
Project successfully built
Using  nativescript.ipa
Your application will be deployed only on the device specified by the provided index or identifier.
Unable to start service. Result code is: 3892314239
# run ios

**Comment by Fatme** [comment]
I'm sorry to hear that the error still happens. Can you try to execute `tns device run <your app identifier> --log trace`? You can get `app identifier` from `.tnsproject` file which is located in the root directory of your application.

**Comment by iamlogiq** [comment]
@Fatme It finally worked with tns device run org.nativescript.nativescript --log trace but I have a few questions. 

The id that I declared on my apple certificate is different than the one in .tnsproject The one I have with apple is com.mywebsite.myappname so could that be the reason for my earlier problems? When I try to change the id in .tnsproject to the one I have with apple then I get a new error: "Invalid application id". Ultimately when I deploy my app shouldn't I use my app id and not org.nativescript?

I also added a console.log message in the main page js file but I can see it in the console. Where can I see deguging messages?

Thanks

**Comment by iamlogiq** [comment]
@Fatme Actually it doesn't work unless the app is already on the device and when I try to modify the app and redeploy I don't see the changes.

**Comment by iamlogiq** [comment]
@Fatme Ok if figured it out! I deleted the /platform/ios folder, then changed the id in .tnsproject to the one i have set with apple and then did "tns platform add ios" and now it WORKS!!!!

My problem is that I created the ios folder before I changed the id. Thanks for the help!

**Comment by xho** [comment]
I am stuck with this error too.
`tns run ios` only works on iOS simulator but not on device.
Removing iOS platform and adding it back did not solve the issue.

If I run the product from xCode it works, the application is successfully installed on device and i get debug info in console. But when I execute CLI `tns tun ios` I get `Unable to start service com.apple.mobile.installation_proxy. Result code is: 3892314239`.

Last part of log trace is:
```
Project successfully built.
Installing...
Unable to start service com.apple.mobile.installation_proxy. Result code is: 3892314239
Error: Unable to start service com.apple.mobile.installation_proxy. Result code is: 3892314239
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:7:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:8:18)
    at Module._compile (module.js:570:32)
Analytics statuses: 
{ TrackFeatureUsage: 1, TrackExceptions: 1 }
Trying to track feature 'CLI' with value 'help'.
List of registered commands: /?, appstore, appstore|upload, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|ios, clean-app, clean-app|android, clean-app|ios, create, debug, debug|android, debug|ios, deploy, dev-generate-help, dev-generate-messages, dev-post-install, dev-preuninstall, dev-test, dev-test|android, dev-test|ios, device, devices, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, emulate, emulate|android, emulate|ios, error-reporting, help, info, init, install, livesync, platform, platform|add, platform|clean, platform|remove, platform|update, plugin, plugin|add, plugin|find, plugin|install, plugin|remove, plugin|search, plugin|update, post-install-cli, prepare, publish, publish|ios, run, run|android, run|ios, test, test|android, test|init, test|ios, update, usage-reporting
Reading help for command 'run|ios'. FileName is 'run-ios.md'.```

TNS version is 2.5.0.
Any suggestion?

**Comment by raefa** [comment]
I am not sure why this is marked as closed. I have to constantly restart my iPhone to get around this issue. It will work for a little while and then the error comes back. 

I used to get this one my old laptop and iPhone. I have recently updated both (fresh installs) and I still get the issue. I am now using 2.5 and same, same. This does not appear to be fixed.

It is frustrating to the point I will likely not start my next project on NativeScript@

**Comment by lidakis** [comment]
Yes same problem here:
Unable to start service com.apple.mobile.installation_proxy. Result code is: 3892314239...

Any workarounds yet ?

**Comment by toddanglin** [comment]
I encountered this error today, too (using v2.5.0).

The resolution for me simply required rebooting the target iPad (which had been connected to the Mac for a while). After that, the app successfully deployed without the 3892314239 error code.

The debugger still failed to attach, though (error code 3892314146). Tried changing USB ports and cables; no effect.

So...following the advice of @xho, I simply did a `tns build ios` and then re-ran `tns run ios` and the debugger launched/attached successfully.

Not sure what triggers this, but if you encounter these 3892314* errors, these steps seem to resolve:

- Reboot iOS device
- Rebuild app (`tns build ios`)
- Re-try run/deploy (`tns run ios`)

Hope that helps.

**Comment by xho** [comment]
Apparently also disabling wifi on the physical device solves the problem most of the times.
(I think that it could be related to the fact that the device is also available via wifi connection)

**Comment by InvSqr** [comment]
After struggling with this issue constantly, @xho's comment did the trick. I was always deleting platform and rebuilding but nothing worked until I switched wifi off. I'm guessing it has a persistent connection to the messages app on the mac and thus blocking the start of installation_proxy.

**Comment by Wittner** [comment]
What a pain. Same happening for me. My app uses the wifi connection to connect to an api so the wifi solution is not ideal. Did anyone at NativeScript address this?

**Comment by geoffbullen** [comment]
WIFI does the trick for me too, but yes kinda annoying..

**Comment by visikolkar** [comment]
Turning off WiFi fixed the issue. But why is this issue closed?
