### ISSUE TITLE
Disk caching for images

### ISSUE THREAD

**Issue by tilutza** [NativeScript/NativeScript#1522]
Hi,

The NativeScript library already has an in memory image cache. However, on large images this can easy run devices memory and will be good if a disk cache would be possible.

However, you can not use ListView with a Image set in it's itemTemplate because you will run out of memory quickly, and for this you need to do yourself the image downloading and setting to the cache.

Do you have planned add such a feature like https://github.com/square/picasso, in newer releases?

Thanks,

**Comment by NathanaelA** [comment]
I highly doubt they will bundle picasso into the runtime.  The object is for the core to be small.  Not everyone would use something like this.    However, I DO have code to allow you to use picasso as if it is built in to the library on Android.  If you are in need of this; send me an email and I'll send you the code.  However, it is not really setup to work on iOS   At some point in the future I'll probably release a complete plugin.  But at this point it is a simple library that only works on Android.

**Comment by PanayotCankov** [comment]
[We also have a fresco plugin in the marketplace app](https://github.com/NativeScript/nativescript-marketplace-demo/tree/production/deps). I am not sure that it will fit your needs but chances are once we have a decent iOS counterpart it will be released officially as a plugin.

**Comment by enchev** [comment]
Hey folks,

Indeed the recommended way will be to use plug-in for such cases.

Thanks
