### ISSUE TITLE
Label text="{{ anyField }}" should not print out "null" if the field is "null"

### ISSUE THREAD

**Issue by Daxito** [NativeScript/NativeScript#1524]
Label text="{{ anyField }}" should not print out "null" if the field is "null", I think this should be changed, otherwise we need to have a converter to every single field.

Let me know if I am missing something here.
Thanks

**Comment by Daxito** [comment]
This is still an issue for android, I still see "null" for TextField and TextViews.
I don't know how to reopen this issue, maybe I should create a new one.

**Comment by enchev** [comment]
Will be fixed immediately!
