### ISSUE TITLE
Unable to share data using application-settings and NSUserDefault to update Today'sExtension.

### ISSUE THREAD

**Issue by ravindraNS** [NativeScript/NativeScript#1525]
I want to update the label inside TodayExtension with the data which is saved to application-settings from app.js. I tried using this 
**var userDefaults = NSUserDefaults.standardUserDefaults().objectForKey("key");** (also with group capability) and this **var appSettings = require("application-settings"); var strShares = appSettings.getString("key", "Dummy String");** approach inside viewDidLoad() method. But still i am unable to get the data. 
Can anyone help me with this?

**Comment by PanayotCankov** [comment]
Hi,

I am so glad you've managed to setup a today extension using {N}.
As for the user defaults, according to this [blog post](http://tapadoo.com/2014/sharing-nsuserdefaults-between-your-app-and-a-today-extension-on-ios-8/), once you are done with grouping together the app and teh extension in the same group, you can access the user defaults by using:

``` Objective-C
[[NSUserDefaults alloc] initWithSuiteName:@"group.com.mycompany.myapp"]
```

Which in {N} gets:
``` JavaScript
var groupDefaults = NSUserDefaults.alloc().initWithSuiteName("group.com.mycompany.myapp");
var key = groupDefaults.objectForKey("key");
```
The group defaults will be shared the standardUserDefaults probably not. Could you give it a try?

**Comment by ravindraNS** [comment]
Hi @PanayotCankov,
thanks for the reply. I tried, but i am getting an empty value.

```
var groupDefaults = NSUserDefaults.alloc().initWithSuiteName("group.org.nativescript.MYTodayApp");
var key = groupDefaults.objectForKey("keyName");
	
        var button = UIButton.buttonWithType(UIButtonTypeSystem);
        button.frame = CGRectMake(0, 0, 200, 50);
        button.setTitleForState(key, UIControlStateNormal);
        this.view.addSubview(button);

```

**Comment by PanayotCankov** [comment]
Can you show me the code in the app (`app.js` in the application, and not in the extension) that saves the value?

**Comment by ravindraNS** [comment]
ya. here it is.
```
var application = require("application");
var appSettings = require("application-settings");
application.mainModule = "main-page";
application.cssFile = "./app.css";

/*  Saving the data to the application-settings  which will update the Widget*/
var data = {'keyName':'1000', 'keyName1':'3000', 'keyName2':'9999'};
function setMyStats(data){
   appSettings.setString('keyName', data.shares);
   appSettings.setString('keyName1', data.reactions);
   appSettings.setString('keyName2', data.clicks);
}
setMyStats(data);
application.start();
```

**Comment by PanayotCankov** [comment]
In the app.js you should use the same dictionary as per the extension. E.g.:
```
var groupDefaults = NSUserDefaults.alloc().initWithSuiteName("group.org.nativescript.MYTodayApp");
groupDefaults.setObjectForKey("keyName", "1000");
```
For numbers I think there is setIntegerForKey etc. you may consider. Application settings uses the standardUserDefaults that is not in the group.

**Comment by ravindraNS** [comment]
I tried your piece of code. Still i am not getting the value. 
i have changed the app.js to below code as suggested and tried to print the value...
```
var application = require("application");
var appSettings = require("application-settings");
application.mainModule = "main-page";
application.cssFile = "./app.css";

var groupDefaults = NSUserDefaults.alloc().initWithSuiteName("group.org.nativescript.MYTodayApp");
groupDefaults.setObjectForKey("shares", "1000");

console.log(groupDefaults.objectForKey("shares"));
application.start();
```
This is the console log result.
```
Starting iOS Simulator
Feb 10 20:34:56 --- last message repeated 1 time ---
Feb 10 20:34:56 GRG-iMac MYTodayApp[2397]: CONSOLE LOG file:///app/app.js:10:12: null
```

**Comment by PanayotCankov** [comment]
It works, you should just note that it is `setObjectForKey(object, key)` rather than `setObjectForKey(key, object)`. Objective-C has that funky naming that can be no that intuitive when mapped to JavaScript. Swap the places of "shares" and "1000".

**Comment by ravindraNS** [comment]
Great.. It works... Nice kick-start for the day... Thanks a lot...
