### ISSUE TITLE
Pixel perfect delimiters?

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#1532]
I have run into a couple cases where I want to create an item exactly 1 pixel high (primarily for borders).  Is their a way to tell the css/ns runtime that this is in pixels rather than dp.  

 Can we adopt the "px" designation to force pixels. This kinda goes along with the new % #412 but instead of a percentage of size; I want to be able to specify this is 5 pixels by 10 pixels no matter which device it is on.

**Comment by PanayotCankov** [comment]
Would you expect in such cases to avoid antialiasing and also have a layout rounding? Should 5.5 inch 4x HD still use 1 px or it could scale up as 2 or 3 as long as it is perfectly snapped to real device pixels and doesn't get fuzzy?

**Comment by NathanaelA** [comment]
I'm pretty sure I understand what you are asking, but I think in this case I would rather have 1px = 1px.  I want absolute pixel control in the case of borders.

**Comment by enchev** [comment]
Merged with https://github.com/NativeScript/NativeScript/issues/53
