### ISSUE TITLE
FileSystemAccess.fileExists returns true for directory as well

### ISSUE THREAD

**Issue by atanasovg** [NativeScript/NativeScript#1534]
Since in Java a `File` object represents both a directory and a file, we need to check not only for `exists` but for `isDirectory` as well:
https://github.com/NativeScript/NativeScript/blob/master/file-system/file-system-access.android.ts#L78

**Comment by enchev** [comment]
Hey folks,

It seems we were too fast! :)

`File.exists` will return true for folder in both iOS and Node.js as well. It seems that this is the expected behavior!

**Comment by cokobware** [comment]
Thanks for fixing this guys!

**Comment by lhitc** [comment]
This is completely contrary to virtually every other programming language or framework, not only Java or Node.js.
The various "exists" functions check for existance regardless of file type, and directories are just files of a special type. Typically you check that at the second stage.

So, this breaks intuitively expected behaviour and possibly also some already existing code out there.

Just my 5 cent.

**Comment by NathanaelA** [comment]
I happen to agree with @lhitc -- exists is one of those unique cases where most developers know that fs.exists = true for both folders and files.    Take this psuedo code for example:
if (!fs.exists('blah')) {
  var file = fs.create('blah');   // Fails here, but the assumption is that it shouldn't...
  file.write('wow');
}

**Comment by enchev** [comment]
Well, I was afraid of this. :) Possible option will be to restore the original behavior and provide additional optional parameter with `true` as default value:
```JavaScript
 export class File extends FileSystemEntity {
        static exists(path: string, includeFolder?: boolean): boolean;
}
```

In this case you will be able to set this to `false` if you want to check only for files not for folders. 
```JavaScript
var fileExists = fs.File.exists(path, false);
```
Hey @atanasovg, @cokobware, what do you think?

**Comment by lhitc** [comment]
If you want to implement both variants for convenience, it might be more consistent to have 3 different methods, like:
static exists(path: string): boolean; // classic behaviour
static isExistingRegularFile(path: string): boolean; // true if plain file
static isExistingFolder(path: string): boolean; // true if folder

**Comment by atanasovg** [comment]
@lhitc .NET for one will NOT return true for a directory: https://msdn.microsoft.com/en-us/library/system.io.file.exists(v=vs.110).aspx. But I guess our thinking is biased due to the fact that many of the core engineering team have extensive experience with .NET.

@enchev Given the default behavior on Node, iOS and Android is to return true for a simple `exists` check then any arbitrary parameters/methods added to the API seem artificial to me. If it is important for the user to check for a file explicitly he may do something like

```
if(File.exists(path) && !Folder.exists(path)) {
}
```

So, my vote goes for reverting the behavior to its previous state.

**Comment by enchev** [comment]
I'm fine for reverting as well. Hey @cokobware what do you think?

**Comment by lhitc** [comment]
@atanasovg Thanks for expanding my horizon. I admit I only checked with Java, PHP, Python, Ruby, Perl, classic C and a couple of web frameworks, which all seem to rely on the stat() system call.
So make that "a majority of programming languages and frameworks, especially in the context of web development" ;-)

**Comment by cokobware** [comment]
I suppose reverting is fine. Having said that, like most of the NS team, my
experience is with .NET too and I find this result surprising given my
experience. I guess it feels very *nixy, which is fine if that is what I
was expecting. It makes sense to revert if that's how Node.js does it.
Perhaps a compromise would be to enhance the documentation to point out the
actual behaviour?

**Comment by awebi** [comment]
So what is the solution to check if "isDirectory"?
