### ISSUE TITLE
Android: "no value for main" when some module's package.json does not have "main" field

### ISSUE THREAD

**Issue by Ivshti** [NativeScript/NativeScript#1537]
First of all, I don't know if NativeScript/NativeScript is the proper place for it or I should post that in the android runtime repo.

Anyway, when `require()`-ing a module that doesn't have a `main` field in it's `package.json`, I'm getting an error "No value for main" on top of the stack trace. 

Issues with this:
1. The error is cryptic, and if you just installed a dependancy with npm that has N number of sub-deps, it tough to trace which module it is
2. The error doesn't even say that it's about `package.json` and that it's `require()` related. Which makes it tough to understand in the first place
3. Node.js usually takes `index.js` as main file if no `main` is specified, and many modules in npm rely on that. I don't see a reason to go against this behaviour

**Comment by enchev** [comment]
Hey @Ivshti, thanks for the report! Is this only for android or you get the same for ios? @slavchev, @fealebenpae can you comment?

**Comment by atanasovg** [comment]
@Ivshti This is weird - if you take a look at the logic of main file resolution you will see that the behavior is exactly the same as you describe it:
https://github.com/NativeScript/android-runtime/blob/master/src/src/com/tns/Module.java#L159-L190

I just tested it on my side and everything is working as expected. Is there something specific with your project?

**Comment by slavchev** [comment]
@Ivshti 

I guess this is for the android runtime as you mention it explicitly. In our tests we load a lot modules without `package.json`. We also have a fallback to `index.js` if provided. I guess the confusion comes from the subtle difference between nodejs' `require` and the one we provide. A simple example should help to understand the issue.

**Comment by fealebenpae** [comment]
The iOS runtime always falls back to `index.js` if a `package.json` lacks a `main` field.

**Comment by enchev** [comment]
@slavchev we had similar issue several days ago https://github.com/NativeScript/NativeScript/issues/1496

**Comment by Ivshti** [comment]
@enchev @slavchev @atanasovg I can see the issue right away.

It does fallback if `package.json` is not found, **but my case is `package.json` being found, but not including `main`**. In which case your code will call `object.getString("main")` and therefore throw an exception.

The solution would be to catch that exception and THEN fallback to index.js. Or call some kind of a conditional ``getString`` which may return null - I don't understand `JSONObject` well enough to know.

**Comment by slavchev** [comment]
@Ivshti 

Is it possible to provide steps to reproduce? As far as I read the code that @atanasovg provided there is a check after https://github.com/NativeScript/android-runtime/blob/996b02ea19e6e04a5de46754eed69c9fd79d105d/src/src/com/tns/Module.java#L186-L190 that will be unconditionally executed after `if (packageFile.exists())` check. Anyway, a small repro will help us to fix the issue.

**Comment by Ivshti** [comment]
Ok, Do this example:
npm install equals
Then ``require("equals")`` in {N} project on Android.

Let me try to explain it again:
_case 1_: there's package.json and `main` prop in it
_case 2_: there's package.json and NO `main` prop in it
_case 3_: there's no package.json

Android case only handles _case 1_ and _case 3_. It does not handle _case 2_.

When I think about the code, it should absorb the JSON exception and go on to include index.js without throwing, so it should handle _case 2_, correct?

**Comment by slavchev** [comment]
@Ivshti 

I reproduced the issue. As I thought this is one of those subtle differences between nodejs and {N} `require`. We cannot find `jkroso-type.js` as it is a submodule of `equals` module and it is located in `equals/node_modules/jkroso-type` folder which we don't traverse.

See the very first line of `equals/index.js` file

```JavaScript
var type = require('jkroso-type')
```

While this is fine with nodejs in {N} runtime for Android it is not supported. As a temporary workaround I would suggest to edit this line as follows

```JavaScript
var type = require('./node_modules/jkroso-type')
```

Meanwhile, we will discuss whether we want to be 100% compliant with nodejs modules.

**Comment by Ivshti** [comment]
@slavchev I've just migrated to using lodash _.isEqual, but why would this happen? AFAIK submodule requiring is supported and it works on all the other modules. What's the exact difference - is it the depth of deps?

**Comment by slavchev** [comment]
@Ivshti Well, there is not a simple answer here. While `tns` makes it easy to import nodejs module, we are not 100% compliant with npm module model. Namely, we still don't support npm submodule organization (think of `node_modules` folders). Another difference is that we don't traverse the parent folder(s) as nodejs does.

>Also, why is the exception "No value for main"

Our bad. This is a typical example of wrong/misleading error message. We will try to come up with something better. Also, as any other open source project, we gladly accepts pull requests ;)

**Comment by Ivshti** [comment]
@slavchev I would fix it myself if I understood it remotely :) 

How do you not support submodule organization? How does everything work for me so far? I've installed like 6-7 modules that have sub-deps, and I think they in their turn have some sub-deps. 

Thanks for the information though, will keep in mind

**Comment by PanayotCankov** [comment]
@slavchev @atanasovg You can use this particular test that runs in iOS: https://github.com/NativeScript/common-runtime-tests-app/blob/master/Require/index.js#L101

**Comment by slavchev** [comment]
As far as I know we already share most of the `require` tests
https://github.com/NativeScript/android-runtime/tree/master/test-app/assets/app

**Comment by slavchev** [comment]
@Ivshti 

It might be a bug in the `tns` CLI. I ended up with a project structure where `node_modules` is not flattened.

**Comment by slavchev** [comment]
Just a quick update: I tested on a clean environment with the latest build from `master` I cannot reproduce the issue. I would suggest to build and try it or I can send you the binaries.

**Comment by Ivshti** [comment]
@slavchev I can make a sample project, but I think you're not reproducing it because it's as a dependancy of another module:
it goes like this:
node_modules/a/node_modules/equals 

I install module a with npm, then do ``tns run android`` and I encounter the error; If I remove usage of ``equals`` everything works fine

**Comment by atanasovg** [comment]
@Ivshti As @slavchev mentioned, recursive `node_modules` dependencies are not currently supported, mainly because of possible performance degrade during resolution.

**Comment by Ivshti** [comment]
@atanasovg I have many modules in my project which have recursive dependencies down to many levels (3-4). How do they work?
https://gist.github.com/Ivshti/d25ec7a9d75921d4d2a2
Just take a look at "stremio-addons/node_modules/dot-object". This is a module that I know for a fact that the project utilizes. And it has 2-3 levels of deps within it, which is already a dependency of a top-level module.

Perhaps there's flattening going on somewhere? And it didn't work in my case?

**Comment by slavchev** [comment]
@Ivshti 

We are not sure what is happening and we need your assistance. I uploaded a runtime build from `master` branch at [https://www.dropbox.com/s/froaud8whi11oc3/tns-android-1.6.0-2016.2.12.1.tgz?dl=0](https://www.dropbox.com/s/froaud8whi11oc3/tns-android-1.6.0-2016.2.12.1.tgz?dl=0)

```
tns create app1
cd app1
tns platform add android
cd..
tns create app2
cd app2
tns platform add android --frameworkPath <path-to>\tns-android-1.6.0-2016.2.12.1.tgz
// this migration step will not be needed for the next release
copy ..\app1\platforms\android\libs\widgets.jar platforms\android\libs
npm install equals
// edit your application to require equals module
tns run android
```

Please let us know if this works for you.

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#355
