### ISSUE TITLE
Drag&Drop support

### ISSUE THREAD

**Issue by cime** [NativeScript/NativeScript#1542]
Is there any plan to support crossplatform drag&drop for components like images/buttons?

Some html/js examples:
* [InteractJS](http://interactjs.io/)
* [Dragula](http://bevacqua.github.io/dragula/)

**Comment by enchev** [comment]
Hey @cime,

Our own @vakrilov made [very good demo](https://github.com/vakrilov/native-script-christmas-tree) with drag & drop.

**Comment by cime** [comment]
@enchev thank you, that's what is was looking for :+1:
