### ISSUE TITLE
Instructions to debug UnitTests

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#1548]
I love the unit testing framework... a lot :)

Issues though on failed tests, if these exist, it's I think just missing from the docs?
1) How to debug, if a test fails, how to we know the output?  Console.log doesn't seem to do anything on the test runs?
2) On release build, is the tests folder and karma stuff packaged as well, or stripped out?

**Comment by teobugslayer** [comment]
@sitefinitysteve,

1. The NativeScript CLI had issues forwarding the console.log output. We fixed these issues in the upcoming 1.6.0 release.
2. The test code is stripped out - see [here](https://github.com/NativeScript/nativescript-cli/blob/master/lib/services/platform-service.ts#L215)
