### ISSUE TITLE
Support for custom activities, e.g. FragmentActivity

### ISSUE THREAD

**Issue by ginev** [NativeScript/NativeScript#155]
The default _NativeScriptActivity_ inherits from _android.app.Activity_ which is limiting the available APIs for scenarios that use the support libraries. For instance, if we want to use an Android component in our NativeScript application that depends on _FragmentActivity.getSupportFragmentManager()_ - we won't be able to.

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#75
