### ISSUE TITLE
Improve setup scripts for 1.7

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/NativeScript#1556]
- [x] Focus the scripts to only install the native dependencies
 - [x] Change the documentation to describe installing the CLI and the platform SDK dependencies separately
 - [x] Improve the scripts with as much error handling as possible
 - [x] `tns doctor` to show the documentation when it detects that the environment is not configured correctly
 - [x] `tns doctor` should understand that error is in the environment and offer to run the setup scripts

**Comment by vchimev** [comment]
- [ ] After executing the setup script for OS X, installing node.js and NativeScript CLI, the `tns doctor` command reports a problem with CocoaPods:
```
setups-mbp:~ setup-script$ tns doctor
Verifying CocoaPods. This may take more than a minute, please be patient.
  ◠ Installing iOS runtime.tns-ios@1.6.0 ../../var/folders/10/g4345mgj5x72gxkj01l749yh0000gn/T/nativescript-check-cocoapods116125-5313-17hdosy/node_modules/tns-ios
  ◟ Verifying CocoaPods. This may take some time, please be patient.Creating shallow clone of spec repo `master` from `https://github.com/CocoaPods/Specs.git`
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.
  ◜ Verifying CocoaPods. This may take some time, please be patient..
WARNING: There was a problem with CocoaPods
```

**Comment by tjvantoll** [comment]
I think we need to be very careful that the CLI sets appropriate expectations about what the scripts do and how long they take—before the scripts run. I think the two things we risk here are:

- 1) Advanced users who get upset that a script is installing things on their machine that they don’t want. And...
- 2) An unexpectedly long install process that causes users to abandon the setup altogether.

I think we can avoid each of these with the appropriate prompts and wording though. I’m happy to update the Getting Started Guide with the necessary changes (and even videos) once this is ready.

**Comment by teobugslayer** [comment]
@vchimev - this is addressed by a change in the docs. It is an issue with CocoaPods and we cannot fix it.See https://github.com/NativeScript/docs/pull/257

**Comment by teobugslayer** [comment]
From @ErjanGavalji: 

I'd have a /y option too. It is horrible to start the installer, go to lunch and get back to only find your computer asking "and how about this nice option?"

Still, sudoer permissions can be asked in the very beginning of the script so that we achieve the /y option...
