### ISSUE TITLE
Android calling js method onCreateView failed TypeError: Cannot read property...

### ISSUE THREAD

**Issue by HunterTKingsley** [NativeScript/NativeScript#1558]
The following binding works in iOS but fails on Android, using exactly the same data set.

          <Label text="{{ jobItem.BasePartNum }}" />

Android throws the following: (See picture for full 'text')
com.tns.NativeScriptException:
Calling js method onCreateView failed

TypeError: Cannot read property 'BasePartNum' of undefined
File: "/data/data/com.telerik.NativeScript/Files/app/
tns_modules/ui/core/bindable.js, line: 192, column: 45
etc

And when I add an dialog.alert in iOS it works, but fails in Android. See the js below.

'use strict';
var isInit = true,
    navigationViewModel = require("../../navigation/navigation-view-model"),
    helpers = require('../../utils/widgets/helper'),
    gestures = require('ui/gestures'),
    dialogs = require("ui/dialogs"),
    viewModel = require('./opdtlView-view-model');
function pageLoaded(args) {
  var page = args.object;
  helpers.platformInit(page);
  viewModel.jobItem= navigationViewModel.jobItem;
  dialogs.alert(viewModel.jobItem["BasePartNum"]);
  page.bindingContext = viewModel;
  if (isInit) {
    isInit = false;
  }
}
exports.pageLoaded = pageLoaded;

![screenshot_2016-02-15-15-23-22](https://cloud.githubusercontent.com/assets/12221090/13060482/d1d3b990-d3ff-11e5-835e-309303284ecc.png)

**Comment by nsndeck** [comment]
I've tried to replicate this problem, unfortunately to no avail. I remember that we fix a similar issue lately. 
@HunterTKingsley Could you please provide me with a little bit more info about the version of `tns-core-modules` used in your code?

**Comment by HunterTKingsley** [comment]
NativeScript version is 1.5.2 according to properties of ShopScheduleIIB
HOWEVER package.json says 1.5.1 which I don't understand. I changed neither, started from empty NativeScript and built it only a week ago. If I need to alter something on account of this seeming mis-match, please provide detail instructions because I really don't want to re-construct this application for the 4th time. Ok?

TO REPLICATE ISSUE: If you build and run Android ShopScheduleIIB in my platform account then:
> Shop Schedule Login
> Login (don't change user/password) (Should take you back to the navigation page in a second or two, otherwise go back)
> ToDo (Should show you a list of 7 Jobs)
> Select DSS-1060 job

Blows up on Android. 
Works on iOS showing a long detail list of job attributes  for DSS-1060

package.json
{
    "name": "tns-template-screen-builder",
    "main": "app.js",
    "version": "1.5.1",
    "author": "Telerik <support@telerik.com>",
    "description": "Nativescript application template",
    "license": "BSD",
    "keywords": [
        "telerik",
        "mobile",
        "nativescript",
        "{N}",
        "tns",
        "appbuilder",
        "template"
    ],
    "repository": {
        "url": "https://github.com/NativeScript/NativeScript/commit/131208d58d73cd18423efe92ffa764db403896b6"
    }
}

**Comment by Mitko-Kerezov** [comment]
@HunterTKingsley I've logged https://github.com/NativeScript/NativeScript/issues/1618 illustrating the behavior you are experiencing.

Can you check and see if it addresses what you are talking about so we can close this issue and wait for [1618](https://github.com/NativeScript/NativeScript/issues/1618)'s resolution
