### ISSUE TITLE
Tracing for bindings

### ISSUE THREAD

**Issue by ligaz** [NativeScript/NativeScript#1560]
Currently it is not a trivial task to debug issues with data bindings. Debugging can be eased if we enable tracing via the trace module and add the necessary categories. The problem with this is that the output is too verbose because it outputs data for every single binding in the application.

Consider providing binding level tracing via XML, that will enable tracing only for the given specific binding.

Here is a snippet of one possible way to implement this:
```xml
 <Button text="Trace me" tap="{{ onTap, trace=true }}" />
```

**Comment by HunterTKingsley** [comment]
I couldn't agree more!  Have you seen the issue I logged yesterday where the binding fails in Android but works in iOS? I have NO clue as to how to debug! Any suggestions, I would be heartily grateful for!

https://github.com/NativeScript/NativeScript/issues/1558

**Comment by nsndeck** [comment]
For the time being we extend a little bit tracing module to print all errors (binding, css) to all trace writers (the default one is the console) no matter if tracing is enabled or not. This actually means that user will see (if there is an error) a message on console out-of-the-box.
