### ISSUE TITLE
Trace module does not report error upon invalid binding expression

### ISSUE THREAD

**Issue by Mitko-Kerezov** [NativeScript/NativeScript#1561]
Consider the following scenario:
In the code-behind:
```JavaScript
var trace = require("trace");
trace.setCategories(trace.categories.Binding + ',' + trace.categories.Error);
trace.enable();

function navigatingTo(args) {
    var page = args.object;
    page.bindingContext = {
        context: {
            a: 2,
            b: 3        
        }
    };
}
exports.navigatingTo = navigatingTo;
```

and in the view:
```xml
<Page navigatingTo="navigatingTo" >
	<Label text="{{ context. }}"/>
</Page>
```

This way the label, naturally, doesn't render. Now if I were to reference `context.a` or `context.b` then the label displays correctly.

However no error, warning or informational message is issued whatsoever in the console, despite the invalid binding expression.

**Comment by nsndeck** [comment]
Issue fixed with commit #1882, furthermore every error (including Binding errors) will be displayed on console (and all trace writers) no matter if trace module is enabled or not.
