### ISSUE TITLE
Can't find custom modules since v1.6

### ISSUE THREAD

**Issue by guillaume-roy** [NativeScript/NativeScript#1567]
Hi,

I've just created a new project based on v1.6.

I created a class Components which references all path.
I want to use it in app.ts but NS throw an error : 
![2016-02-17_17h42_43](https://cloud.githubusercontent.com/assets/2191489/13116852/dc87a1c2-d59d-11e5-8dbb-14b8f6533450.png)

* app.ts
```
import application = require("application");
import {Components} from "./utils/components";

application.start({
    moduleName: Components.Main
});
```

* utils/components.ts
```
export class Components {
    public static Main: string = "components/main/main";
}
```

And my main component is "components/main/main.xml"

* tns-android 1.6.0
* tns-core-modules 1.6.0
* Android SDK API 22&23 installed
* Windows 10

**Comment by NathanaelA** [comment]
Did you do a "tns install typescript" in your main project folder to get TypeScript installed so it can transpile the TS to JS?

**Comment by Daxito** [comment]
I wonder if this is also related to https://github.com/NativeScript/nativescript-cli/issues/1497  ??

**Comment by guillaume-roy** [comment]
@NathanaelA  : Yes because my .ts are transpiled into .js. I have a .tsconfig and :
```
"devDependencies": {
    "nativescript-dev-typescript": "^0.3.0",
    "typescript": "^1.7.5"
  }
```

@Daxito I follow the same instructions to upgrade NS

**Comment by NathanaelA** [comment]
@guillaume-roy I'm pretty sure this is a different issue.    Can you post the app.js & utils/components.js code it generated?

**Comment by guillaume-roy** [comment]
* app.js
```
var application = require("application");
var components_1 = require("./utils/components");
application.start({
    moduleName: components_1.Components.Main
});
```

* utils/components.js
```
var Components = (function () {
    function Components() {
    }
    Components.Main = "components/main/main";
    return Components;
})();
exports.Components = Components;
```

**Comment by NathanaelA** [comment]
Two shots that might work:
1In your app.ts; try 
import {Components} from "utils/components";
or 
import {Components} from "~/utils/components";

And see if either of those work...

**Comment by rosen-vladimirov** [comment]
I've just tried it on my side and it seems to work fine. I believe the problem is in:
```TypeScript
export class Components {
    public static Main: string = "components/main/main";
}
```
Based on the other information, I believe your components dir is under utils, not at the root of your project. Can you verify this path is correct as it is resolved in the app.ts in the root of your project. So in case I'm correct, you should change it to:
```TypeScript
export class Components {
    public static Main: string = "utils/components/main/main";
}
```

**Comment by guillaume-roy** [comment]
Thank you all for your help !

That's weird because this morning I reopen my code and Genymotion then I launch the app and eveything work perfectly.

I tried to remove the platform and re-add it, it works too.

I don't know what happened.
