### ISSUE TITLE
TextView text="{{ anyField }}" should not print out "null" if the field is "null"

### ISSUE THREAD

**Issue by Daxito** [NativeScript/NativeScript#1571]
TextView text="{{ anyField }}" should not print out "null" if the field is "null", I think this should be changed, otherwise we need to have a converter to every single field.

Let me know if I am missing something here.
Thanks

**Comment by enchev** [comment]
Hey @Daxito,

You reported this more than a week ago and the issue is already fixed in our 1.6 version:
https://github.com/NativeScript/NativeScript/issues/1524

**Comment by Daxito** [comment]
You fixed it for labels, I will try to create a sample app with the issue and attach it to the ticket.
Thanks!

**Comment by enchev** [comment]
I've reopened the origin issue!
