### ISSUE TITLE
Page.optionsMenu MenuItem icon property null reference

### ISSUE THREAD

**Issue by csell5** [NativeScript/NativeScript#158]
I see the MenuItem has a icon property but I can't seem to set it correctly.

I tried just passing it a reference to a png a few different ways but it doesn't seem to matter. https://github.com/NativeScript/NativeScript-NEXT-Workshop/blob/master/app/components/create-template/create-template.xml#L7

I still get the following error regardless.

/app/tns_modules/ui/frame/frame.js:160:91: JS ERROR TypeError: null is not an object (evaluating 'img.ios')
1   0xb8062 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x5d9b06 ffi_closure_SYSV_inner
3   0x5d9552 .LCFI7
4   0x123c96a -[UINavigationController _startCustomTransition:]
5   0x124a466 -[UINavigationController _startDeferredTransitionIfNeeded:]
6   0x124b0b2 -[UINavigationController __viewWillLayoutSubviews]
7   0x13bfd1c -[UILayoutContainerView layoutSubviews]
8   0x11467b1 -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
9   0x22a5771 -[NSObject performSelector:withObject:]
10  0x4a5b1cf -[CALayer layoutSublayers]
11  0x4a4f055 CA::Layer::layout_if_needed(CA::Transaction*)
12  0x4a4eeb0 CA::Layer::layout_and_display_if_needed(CA::Transaction*)
13  0x49ad1b6 CA::Context::commit_transaction(CA::Transaction*)
14  0x49ae58a CA::Transaction::commit()
15  0x4a746d9 +[CATransaction flush]
16  0x10b6c21 _UIApplicationHandleEventQueue
17  0x28fe98f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
18  0x28f449d __CFRunLoopDoSources0
19  0x28f39f8 __CFRunLoopRun
20  0x28f337b CFRunLoopRunSpecific
21  0x28f31ab CFRunLoopRunInMode
22  0x43772c1 GSEventRunModal
23  0x43770fe GSEventRun
24  0x10ba9b6 UIApplicationMain
25  0x5d946d .LCFI1
26  0x5d9a4f ffi_call
27  0xcc83e NativeScript::FFIFunctionCall::executeCall(JSC::ExecState*)
28  0x44856f JSC::LLInt::setUpCall(JSC::ExecState*, JSC::Instruction*, JSC::CodeSpecializationKind, JSC::JSValue, JSC::LLIntCallLinkInfo*)
29  0x444416 llint_slow_path_call
30  0x44e046 llint_entry
31  0x44e056 llint_entry

**Comment by froyke** [comment]
Reproducing here as well. 
tns version 1.0.1

However I do not get an error when using one of the provided icons (icon.png for example) - though they are not displayed correctly. Could it be some (undocumented) assumptions on the type of png ?

**Comment by froyke** [comment]
OK, identified the problem, but need help in solving it.
I have opened (in xcode) the created xcode project and found that the icons I have put in the App_Resource / iOS folder are not part of the xcode project (although they were copied to the output directory under platforms/ios/MYAPPResources/icons). I guess they are missing from the project.pbxproj file.
Only when I have added them manually in xcode - the app did not crash and I could see these nav menu icons..

**Comment by vchimev** [comment]
Not relevant anymore. Related to https://github.com/NativeScript/NativeScript/issues/304.

**Comment by vchimev** [comment]
Since [v.1.2.0.] (https://docs.nativescript.org/Changelogs/Cross-Platform%20Modules.html) ActionBar/NavigationBar is defined using the `page.actionBar` instead of `page.optionsMenu`. See an example [here] (https://docs.nativescript.org/ApiReference/ui/action-bar/HOW-TO.html).
