### ISSUE TITLE
Project does not build after upgrade to {N} 1.6.0

### ISSUE THREAD

**Issue by victorhugom** [NativeScript/NativeScript#1581]
Error:
```
malformed document. First element should be <plist>
# build ios
```

I did:

npm install -g nativescript
tns platform remove ios
tns platform add ios
npm install tns-core-modules@latest --save
tns build ios

And also tried:

remove folder: node_modules
remove folder: platform 

npm install -g nativescript
tns platform remove ios
tns platform add ios
npm install tns-core-modules@latest --save
tns build ios

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#1508
