### ISSUE TITLE
GridLayout: children are not stacking correctly when created programmatically

### ISSUE THREAD

**Issue by dragGH102** [NativeScript/NativeScript#1584]
Apparently it is possible to define a "z-index" (element order) for children in GridLayout (credit: @NathanaelA ) by:

```
<GridLayout rows="2" >
<Label row="0" text="Hi"/>
<Label row="1" text="Hello"/>
<Label row="0" text="       I'm stacked on the 'Hi'"/>
<Label row="1" text="             I'm stacked on the Hello"/>
</GridLayout>
```

**Issue**: when the elements are created programmatically **elements created first are not render on top of elements created later**.
In my specific case the first element is a **button with a background image** on top of which I want other elements to be rendered.

I created a sample project showing the issue: https://github.com/dragGH102/nativescript-sample-stacked-gridlayout (latest {N} version, tested on Android - upgraded to latest {N} just today).

**How to reproduce**: just launch the app in Android

The reason why I'm using a button with a background image is that I need the **image to be "tappable" and the tap event is not supported when the image is created programmatically** as I would do with a button by:

```
import buttonModule = require("ui/button");
// image is a button 
image.on (buttonModule.Button.tapEvent, ...
```

Any clue?
If there is a way to make a programmatically created image "tappable" without using a Button, I could try that.

**Comment by NathanaelA** [comment]
The tap event is supported fine, I took your sample app and change it to be basically this:
```
    var img = new imageModule.Image();
    img.src = "~/background_img.png";
    img.width = 100;
    img.height = 100;

    img.on('tap', function() {
        console.log("Img Tap");
    });
frameModule.topmost().getViewById("view-container").addChild(img);
```

I get "Img Tap" consoled out to my log when I click it fine...

**Comment by hshristov** [comment]
@dragGH102 Elements added first are behind elements added later in all layouts. So this is by design. If you need stack layout a better option is to use `<StackLayout>`. In case you need GridLayout please check documentation: https://docs.nativescript.org/ui/layout-containers#gridlayout

The correct usage is `rows="*, 80, auto"` e.g. you need to specify the height of the rows.

**Comment by dragGH102** [comment]
thanks @NathanaelA I'll try it out in a moment
@hshristov yes, StackLayout works fine, but elements are stacked "in 2D" (either horizontally or vertically), not on top of each other. am I wrong?

**Comment by dragGH102** [comment]
@NathanaelA I tried it out. apparently "tap" was what I was missing.
now it works. thanks!

**Comment by hshristov** [comment]
@dragGH102 - Yep, `StackLayout` stacks them either horizontally or vertically. I guess if you need them to overlap you could set some negative margin on the image or even use the `AbsoluteLayout`

**Comment by dragGH102** [comment]
@hshristov In the end GridLayout with all elements overlapped (same row/column) worked fine :-)
