### ISSUE TITLE
Button css color affects ActionSheet button color

### ISSUE THREAD

**Issue by EddyVerbruggen** [NativeScript/NativeScript#1586]
To prettify one of my plugin demo apps I'm setting this in `app.css`:

```css
button {
  color: #ffffff; /* this is the issue */
  background-color: #E0A458;
  ...
}
```

Somewhere else in the app I have an ActionSheet:
```js
  dialogs.action({
    message: "Your message",
    cancelButtonText: "Cancel text",
    actions: ['Action A', 'Action B']
  }).then(function (result) { ... }
```

On my iOS 9 device the button labels render with invisible text. Only when touched the label becomes visible (blue).

What I figured out after an hour of trial and error is that the css color definition of the button is used to set the color of the ActionSheet's button color. That was totally unexpected!

The code responsible [is here](https://github.com/NativeScript/NativeScript/blob/master/ui/dialogs/dialogs.ios.ts#L401).

I think at the very least this should be documented, but it would be great if you can explicitly set a color in the component itself. It's kinda cool that since iOS 8 you can set ActionSheet button colors, there is just no way to have decent control over it in {N} currently.

Once this was clear to me the fix was very simple, just not set the color on the `button` tag (this makes the ActionSheet buttons use the default blue color), but add a `.button` class and reference it from all buttons.

**Comment by vjoao** [comment]
Sorry to bother, but, as adding a class just works, isn't this issue a bit unnecessary? I mean, styles are just doing their job in this case.

**Comment by EddyVerbruggen** [comment]
They are not; I'm not trying to style an ActionSheet button with the `button` css selector, I'm trying to style `Button` tags in the `xml` definition (that's what you expect the css selector to target, right?).

IMHO it's a side-effect that it also styles the ActionSheet's so-called `tintColor` (which effectively is the button's text color). I'd love to be able to set different styles for different ActionSheet buttons, but that's unsupported if this was intended usage instead of a side-effect.

**Comment by vjoao** [comment]
I get your point and agree.

**Comment by enchev** [comment]
Hey folks,

In my opinion this is expected behavior. When you have type CSS selector we will try to style every instance in the app no matter if the component is declared in XML or instantiated programmatically including buttons, text-fields, etc. in dialog.

**Comment by EddyVerbruggen** [comment]
it's not intuitive. I'm also changing the background color of the button, but that doesn't affect the actionsheet button. Also on pre-ios8 the actionsheet button won't change. And you can't change the color of individual buttons this way.

**Comment by enchev** [comment]
Hey @myninka what do you think? Should global CSS styles affect our dialogs or not?

**Comment by myninka** [comment]
Hi all,
I also agree this is an expected behavior but we could think of a way of setting a specific style for the action sheet/other dialogs.

**Comment by enchev** [comment]
Yep, we can try to provide an option to disable this inheritance as a start. Hey @EddyVerbruggen, @vjoao what do you think? Something like:

```JavaScript
    export interface CancelableOptions {
        inheritGlobalStyles?: boolean;
    }
```
here: https://github.com/NativeScript/NativeScript/blob/master/ui/dialogs/dialogs.d.ts#L88-L93

**Comment by EddyVerbruggen** [comment]
Hey all, good discussion!

As most apps will probably change the default button style (colored background, light text color), and the starter template defines a `button` css class I'm afraid more folks will encounter this behavior

So to make it a bit more clear for the casual reader I'm attaching two screenshots. On the left the css `button class has  `color: #ffffff` and on the right no color is specified. With the latter the ActionSheet buttons will use the default color (blue):

![actionsheet](https://cloud.githubusercontent.com/assets/1426370/13178668/71bb86ae-d720-11e5-8a45-2022220444b5.png)

A way to suppress this behavior is nice, but adding it to the dialogs doc will go a long way too (at least that's where I looked when I thought my buttons were broken).

**Comment by enchev** [comment]
This should be revised with out upcoming default theme. I'm closing this for now.
