### ISSUE TITLE
Adding selectedColor does not affect tab text on android

### ISSUE THREAD

**Issue by mikeres0** [NativeScript/NativeScript#1591]
I have added in the `selectedColor` tag to a TabView in my app. On iOS everything is fine, however on android only the underline of the selected tab is coloured, not the text above which displays the name of the tabs.

`<TabView tabsBackgroundColor="#000165" selectedColor="#FFFFFF">`

**Comment by vjoao** [comment]
This is Android's expected behavior.

**Comment by enchev** [comment]
Hey @mikeres0,

Indeed we are trying to keep the default look feel and just colorize the component. In this case we use:
http://developer.android.com/reference/android/support/design/widget/TabLayout.html#setSelectedTabIndicatorColor(int)

There is no selected state for the tab titles.

**Comment by mikeres0** [comment]
Hello @enchev, 

I don't really see the point in this as you could potentially end up stuck when creating your own UI. I don't get why you'd allow part of a component to be coloured but not the other parts?

**Comment by enchev** [comment]
Hey @mikeres0,

We are just trying to style what's selectable. Unfortunately there is no native Android API for styling TabLayout items titles in normal and selected state.

**Comment by mikeres0** [comment]
@enchev thank you for your reply and explanation.
