### ISSUE TITLE
Unable to align icon from right to left for android

### ISSUE THREAD

**Issue by Daxito** [NativeScript/NativeScript#1595]
I can't align this "Back" icon for android , it keeps aligned to right, am I missing something? 
Any help is appreciated, this is my code and what I get 

`<page.actionBar>
		<action-bar title="Trucking Schedule" android.iconVisibility="never">
			<action-bar.actionItems>             
                <action-item tap="goBack"  android.systemIcon="ic_menu_back"  android.position="left" />
				<action-item tap="{{ anyCommand }}"  ios.systemIcon="13" android.systemIcon="ic_menu_refresh"  ios.position="right" />
			</action-bar.actionItems>
		</action-bar>
	</page.actionBar>`

![capture](https://cloud.githubusercontent.com/assets/16787057/13193077/961e8ba0-d738-11e5-9e77-1526638c667e.PNG)

**Comment by vjoao** [comment]
Buttons on the left are called NavigationButton. 
Try this:
```
<Page.actionBar>
    <ActionBar title="Navigation Button">
      <NavigationButton text="ios back" android.systemIcon = "ic_menu_back" tap="navTap"/>
    </ActionBar>
  </Page.actionBar>
```

**Comment by Daxito** [comment]
@vjoao, but I also need the "refresh" icon at the right, that combination is my problem right now, I know is so simple question but I just don't know the correct combination of buttons I guess.

**Comment by vjoao** [comment]
```
    <Page.actionBar>
         <ActionBar title="Native FAB" backgroundColor="#3F51B5" color="#fff">
             <NavigationButton text="ios back" android.systemIcon = "ic_menu_back" tap="navTap"/>
             <ActionBar.actionItems>
                <ActionItem ios.systemIcon="12" android.systemIcon = "ic_menu_search" />
                <ActionItem ios.systemIcon="15" android.systemIcon = "ic_menu_camera" />
                <ActionItem ios.systemIcon="16" android.systemIcon = "ic_menu_delete" />
            </ActionBar.actionItems>
         </ActionBar>
    </Page.actionBar>
```

**Comment by Daxito** [comment]
Thank you!
