### ISSUE TITLE
All the samples i build/install die with the same error

### ISSUE THREAD

**Issue by AdamGlass** [NativeScript/NativeScript#1597]
Groceries, Tasks, and the Nativescript-Marketplace all fail with
Unhandled Exception
java.lang.RuntimeExceptin: Unable to start activity....

This is not a good initial experience following the 'Getting Started' documentation.  Please advise.

**Comment by NathanaelA** [comment]
Can you put a bit more of the error?  
Does "tns doctor" report anything wrong?

**Comment by AdamGlass** [comment]
The android clipboard functionality isn't working so it's kinda manual.

This is from the Android Emulator on ubuntu 14.04.

Unhandled Exception
java.lang.RuntimeEception: Unable to start activity
ComponentInfo(org.nativescript.sampleTasks/com.tns.NativeScriptAcitvity):
com.tns.NaiveScriptException

TypeError: Cannot read property 'widgets' of undefined
File: /data/data/org.nativescript.sampleTasks/files/app/tns_modules/ui/frame/frame.js: line 327 column 39

Stacktrace: 
Frame: function NativeActivity.OnCreate', file:/data/data/org.nativescript.sampleTasks/files/app/tns_modules/ui/frame/frame.js, line 327 column 40

**Comment by AdamGlass** [comment]
tns doctor detects no issues

**Comment by bradmartin** [comment]
I would try `tns platform remove android` then add it back `tns platform add android`. Also, make sure you are on version *1.6.1* and you've installed the latest core modules into your app. If **widgets** is undefined (I've had this happen before) it's a config/build issue and doing what I said previously should fix the issue. It's likely an inconsistent version and/or setup in your project.

**Comment by enchev** [comment]
Hey @AdamGlass,

Do you still need help with this?

**Comment by AdamGlass** [comment]
i'll try today and see if that works.

**Comment by erkanarslan** [comment]
I have the same problem. Tried sample apps on different Android versions:

- 5.0.1 : app works
- 4.4.2 : not working
- 4.3.1 : not working
- 4.2.2 : not working
- 4.1.2 : not working

It seems that these sample apps are for Andorid 5+.

**Comment by bradmartin** [comment]
@erkanarslan - Nativescript currently doesn't run on Android 4.1 - [See here](https://docs.nativescript.org/) - I think in the next release in March (1.7) they've improved the runtime to work with lower Android versions but still some work to do on the core modules. As for the samples being 5+ only, I can run the Groceries sample app just fine on Android 4.4 and 5.1 so something might be wrong with your setup, just a guess.

**Comment by erkanarslan** [comment]
tns version is 1.6.1
Empty project uses tns modules 1.6.2
I have created an avd from Nexus 4 template. API level 19. I use intel x86 atom image for emulator
I have changed many parameters, but nothing has worked so far.

**Comment by bradmartin** [comment]
https://github.com/NativeScript/NativeScript/issues/1672 the solution from @rosen-vladimirov is what is the problem. As I suspected on another related issue thread you are on.
