### ISSUE TITLE
Ability to set binding context to prototypes

### ISSUE THREAD

**Issue by vjoao** [NativeScript/NativeScript#1598]
I don't know if I'm doing something wrong, but, when using TypeScript export class definition and defining public methods, shouldn't they be available to the bindingContext?

If I access `tap="tapAction"` it will work only if the `tapAction` is defined in the exports, not inside a exported class and defined as public. The generated code puts `tapAction` on the `Class.prototype.tapAction` and I have to access the method by putting `tap={{tapAction}}`. Is this the expected behavior?

**Comment by enchev** [comment]
Hey @vjoao,

Indeed this is the expected behavior. Please post your XML declaration and how you've set the bindingContext if you have some problem!

**Comment by vjoao** [comment]
It's not actually a problem. It's just uncomfortable to have it simply not working, even if you export the class and set the method as public in the view-model. I mean, writing tap="{{action}}" is ok. But the examples I see all use the exports directly and doing tap="action" is easier to follow as the page loaded="pageLoaded" is not using the curly braces. When I first started to use a view model for modularity, things like tap="action" simply didn't work (with no errors as well) and I was a little frustrated to say the least. 
I guess if this is the expected behavior, it should be documented somewhere (and if it is, sorry for not finding it).

**Comment by enchev** [comment]
Hey @vjoao,

When you declare the handler without curly brackets we will look for this function in the Page code file. For example:

### main-page.xml
```XML
<Page>
   <Button text="Click me!" tap="buttonTap" />
</Page>
``` 

### main-page.js
```JavaScript
exports.buttonTap = function(args){
   console.log("Button tap");
}
```
