### ISSUE TITLE
Force close on android - Lots of image loading on a list

### ISSUE THREAD

**Issue by vjoao** [NativeScript/NativeScript#1600]
I'm experiencing force closes when loading images on a list view. I'm loading reddit posts and populating the list. While scrolling the images load as usual, but randomly the app just crashes.

Fetch method:
```
 return fetch("https://www.reddit.com/r/pics.json?after=" + after).then((response)=> {
            return response.json();
        }).then((response)=>{
            response.data.children.forEach((item)=> {
                if(item.data.url.match(/.jpg/)) {
                    this.source.push(item);
                }
            });
            this.set("after", response.data.after);
        });
```

My list definition: 

```
<list-view loaded="{{listLoaded}}" row="1" items="{{source}}" itemTap="{{itemTap}}">
    <list-view.itemTemplate>
        <stack-layout>
            <label text="{{ data.title }}" textWrap="true" fontSize="12" margin="20" />
            <image src="{{data.url}}"/>
        </stack-layout>
    </list-view.itemTemplate>
</list-view>
```

And the error I'm getting on console as soon as the app crashes:
```
I/DEBUG   ( 2884):     #01  pc 0026db6f  /data/app-lib/org.nativescript.nsproject-1/libNativeScript.so (tns::MetadataNode::CreateJSWrapper(v8::Isolate*)+207)
I/DEBUG   ( 2884):          958ab7ec  97677b70  /data/app-lib/org.nativescript.nsproject-1/libNativeScript.so (tns::MetadataNode::CreateJSWrapper(v8::Isolate*)+208)
```

**Comment by enchev** [comment]
Hey @vjoao,

In my opinion this app run out of memory. Are the images too big? We have several apps with exactly this approach but we use thumbnails in ListView items:
https://github.com/NativeScript/NativeScript/blob/master/apps/cuteness.io/main-page.xml#L10
https://github.com/NativeScript/NativeScript/blob/master/apps/cuteness.io/reddit-item-view-model.ts#L45-L78

**Comment by NathanaelA** [comment]
@vjoao -- the solution to lots of images is using something like Picasso or something like the https://github.com/NativeScript/nativescript-fresco plugin.   These plugins will automatically cache the images and use only one or two image containers which eliminates the phones from running out of memory.

**Comment by vjoao** [comment]
It makes sense. Strange thing is even if I try it on Genymotion with 4GB of RAM it crashes in the same fashion. Does Android just kills apps that are consuming lots of memory (or this has something to do with video memory)?

**Comment by vjoao** [comment]
And isn't the ListView capable of doing garbage collection to free the images that are not visible? I also noted it crashes frequently when I scroll down fast (maybe its trying to load all images at once and there is some race condition somewhere?)
