### ISSUE TITLE
Add remaining properties to ui/core/view.View type definition

### ISSUE THREAD

**Issue by losttime** [NativeScript/NativeScript#1601]
There are quite a few functions missing from the type definition for `ui/core/view.View`. Those would be very helpful to those using TypeScript to write plugins that extend the `View` class.

Here's the documentation for `ui/core/view.View`: https://docs.nativescript.org/ApiReference/ui/core/view/View

Here's the type definition for `ui/core/view.View`: https://github.com/NativeScript/NativeScript/blob/master/ui/core/view.d.ts#L105

These are the functions I'm specifically interested in using:

```
_onDetached(force?: boolean): void;
_setCurrentMeasureSpecs(widthMeasureSpec: number, heightMeasureSpec: number): boolean;
```

but there are quite a few others that are missing as well:

```
_parentChanged( oldParent View )
_isInheritedChange() Boolean
_addViewToNativeVisualTree( view View, atIndex? Number ) Boolean
_removeViewFromNativeVisualTree( view View )
_eachChildView( callback Function... )
_onAttached( context Object )
_onContextChanged()
_onDetached( force? Boolean )
_createUI()
_shouldApplyStyleHandlers()
_checkMetadataOnPropertyChanged( metadata PropertyMetadata )
_updateLayout()
_setCurrentMeasureSpecs( widthMeasureSpec Number, heightMeasureSpec Number ) Boolean
_setCurrentLayoutBounds( left Number, top Number, right Number, bottom Number )
_getCurrentLayoutBounds() {}...
_goToVisualState( state String )
_setNativeViewFrame( nativeView Object, frame Object )
```

**Comment by PanayotCankov** [comment]
These methods are private. (starting with _) The reason they are not part of the public definition is we can not promise we won't change their behavior.

Perhaps we could rather elaborate on a `custom controls` feature and expose what is necessary for {N} control development?

**Comment by enchev** [comment]
Hey folks,

In my opinion we should expose some of them as `protected` to enable better custom components development. Hey @atanasovg, @hshristov what do you think?

**Comment by losttime** [comment]
@PanayotCankov It appears there are already some "private" methods (prefixed with an underscore) that are part of the definition file (and not using the `private` keyword). I wonder why some warrant inclusion while others don't?

**Comment by PanayotCankov** [comment]
@enchev  :+1: We should just carefully select which to expose. It would be nice to collect usecases (such as from @losttime ) and cover them in article (for example in the 'developing ui plugin').

@losttime The components frequently have different implementation for Android and iOS and so the .d.ts-es are written by hand, then the different implementations try to implement the promised public interface. Also there are scenarios where these methods should be used by child classes in the core framework but should not be available for public use (~ C# internal, or Java's default visibility ~  package-private). TS is really good addition to JS but it is also young and lacks some features. Have in mind that we also started {N} when TS was v 0.95 so there may be some legacy.

@losttime it would be really helpful if you could explain the potential use cases for the methods you need. We will probably open what is necessary anyway. However exposing these methods will open public surface that is good to have unit tests and documentation and will lock us to keep these methods to be backward compatible.

If these methods should be protected, shouldn't we remove the leading underscores?

**Comment by enchev** [comment]
Hey @losttime @PanayotCankov what's the status here?

**Comment by atanasovg** [comment]
@hshristov @PanayotCankov I think that these are already changed/exposed with modules 3.0+, could you please verify this and close the issue?

**Comment by PanayotCankov** [comment]
3.0 was focused at making it possible to develop JavaScript Views that wrap native Views. I think the property system now exposes API to handle update and propagate it to the native view, as well as there are public lifecycle events designed to handle the native view creation and management.

If there are APIs missing in 3.0+ we can discuss them in separate issues.
