### ISSUE TITLE
Problem depending on how observerables get initialized

### ISSUE THREAD

**Issue by nraboy** [NativeScript/NativeScript#1603]
Ran into what I can only assume to be a bug with observables.

Take the following example code:

```
var touchid = require("nativescript-touchid");
var observableModule = require("data/observable");

function pageLoaded(args) {
    var page = args.object;
    var data = new observableModule.Observable();
    data.authenticated = false;
    touchid.available().then(function(avail) {
        console.log("Available? " + avail);
        if(avail) {
            touchid.verifyFingerprint({
                message: 'Scan yer finger', // optional
                fallbackTitle: 'Enter PIN' // optional
            }).then(function() {
                console.log("Fingerprint was OK");
                data.authenticated = true;
                console.log(JSON.stringify(data));
            }, function(error) {
                console.log("Fingerprint NOT OK" + (error.code ? ". Code: " + error.code : ""));
            });
        }
    });
    page.bindingContext = data;
}

exports.pageLoaded = pageLoaded;
```

The `console.log(JSON.stringify(data));` prints `true` as it should after a successful authentication.  However, if I have the XML like this:

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="pageLoaded">
    <StackLayout>
        <Label text="{{authenticated}}" />
    </StackLayout>
</Page>
```

The value does not get updated.  I've noticed the same results when I do `data.set("authenticated", true/false)` as well.

When the observable changes in the 1st depth callback, the XML notices the change, just not the second depth.

There is a solution that does work.  If I initialize the observable like so:

```
var data = new observableModule.Observable({authenticated: false});
```

All works fine.

This raises my question, is the documentation flawed?  It has lead me to believe that all three methods should work.  If all three should work, then maybe it is a bug.

I'm using 1.6.x.

Let me know if you need more info.

**Comment by nsndeck** [comment]
I've just tested with a sample app and I can confirm that only 2 of 3 scenarios work perfectly (as expected).

Working scenarios:

```JAVASCRIPT
var data = new observableModule.Observable();
data.set("authenticated", true);
```
and the one mentioned by @nraboy 

```JAVASCRIPT
var data = new observableModule.Observable({"authenticated": false});
data.set("authenticated", true);
// or
data["authenticated"] = true; 
```

The reason for both scenarios working is that {N} when `Observable` class is created with `json object` {N} silently creates a property ES5 getter and setter for each member. Within property setter we include a logic that notifies all `propertyChange` listeners for the change. This logic is also included within `Observable.set` method. But when Observable instance is created with empty constructor neither setter or getter are created and notification cannot be raised.

@nraboy: Could you please point me to the documentation page which lead you to the wrong impression? Could you also double check the scenario with using `Observable.set` method (it should work)?
