### ISSUE TITLE
Allow changes to child properties to bubble up to the parents so the UI updates.

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#1604]
Binding example with kendo: 
http://dojo.telerik.com/OCUkA

So the root object is observable and all child properties are just automatically **awesome** as well.

So moving over to {N} I feel like we're behind a bit...

If I used that same example in {N} and bound a label to {{ name.first }} , then in code set viewModel.name.first = "Steve", the UI doesn't update.

I would like it to just work and not have to have a massive nested observable...I dont love having to keep moving properties onto the root object (ugly).

**Comment by sitefinitysteve** [comment]
I think this is the same as #1603 ...we submitted at the same time weirdly, I did search before posting I swear :)

**Comment by NathanaelA** [comment]
@sitefinitysteve I think he is describing a bug dealing with nested promises and observables.  Not nested properies in a observable.  So  I think these are separate.

**Comment by sitefinitysteve** [comment]
Why was this closed?  Is a non-issue?
