### ISSUE TITLE
Enable advanced gesture detection parameters when applied to a ScrollView (Feature request)

### ISSUE THREAD

**Issue by dragGH102** [NativeScript/NativeScript#1609]
I have a view which is spread over several screen (ScrollView - horizontal).
I need to implement a "swipe left to trigger some action (in this case .goBack() )". in a view which scrollable horizontally thanks to its container (a SrollView)

I initially considered watching for **swipe** event on main container (the ScrollView) but this would give me no way to know whether I'm on the first screen (before swiping right to show the rest of the horizontal scrollview) since no coordinates are available in eventData.

So, I switched to **pan** event which allows me to see deltaX coordinate: the issue is that **it doesn't matter where (horizontally) I'm in the scrollview, it will always start from 0**, and getting positive when sliding left.

So, my feature advice would be to **allow a view-related offset detection (rather than screen offset)** as they can be different when a ScrollView is horizontal. A similar reasoning can be done for vertically scrollable ScrollView (e.g. not my case, but it could be handy to have a pull-to-show-menu from top only if the view is actually at the top).

Of course I'm open to **some workaround / different approach** should it be complex to implement it in {N} APIs.

**Comment by vjoao** [comment]
+1

**Comment by PanayotCankov** [comment]
Can you use the [touch](https://docs.nativescript.org/ui/gestures#touch) gesture?

**Comment by dragGH102** [comment]
@PanayotCankov thank you. it sounds feasible. I will check it out
