### ISSUE TITLE
Need a javascript sandbox

### ISSUE THREAD

**Issue by tailsu** [NativeScript/NativeScript#161]
Browsers have iframes, node has contextify. A javascript unit test runner simply needs to have a sandboxing mechanism to work smoothly.

**Comment by fealebenpae** [comment]
How do you envision this in the context of NativeScript? Should the global object of the sandbox instance include the NativeScript APIs and `require`, or is a pristine global object enough? Would you need to intercept property definitions on the global object, or provide your own?

**Comment by N3ll** [comment]
This issue was moved to NativeScript/android-runtime#239
