### ISSUE TITLE
Livesync Not Copying SourceMaps

### ISSUE THREAD

**Issue by burkeholland** [NativeScript/NativeScript#1617]
It looks to me like in 1.6, `livesync` is not copying source maps over.

````
Unable to sync files. Error is: ENOENT: no such file or directory, stat '/Users/burkeholland/dev/burkeholland/nativescript-devdays/platforms/ios/nativescriptdevdays/app/models/Speaker.js.map'
````

Even though that file exists in my project, but it does not exist at the location specified in the error.

Note that this is resolved by adding `inlineSourceMaps: true` to the `tsconfig` file.

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#1531
