### ISSUE TITLE
XML Widget with Two-Way Binding

### ISSUE THREAD

**Issue by MarkPerryBV** [NativeScript/NativeScript#1620]
How can I get a custom widget defined in XML to work with a two way binding. I'd like to layout my widgets in XML rather than create them all using code.

```
//main.xml

<Page xmlns="http://schemas.nativescript.org/tns.xsd" 
    xmlns:myControls="customcontrols/greeter">
 <StackLayout>
  <Label text="{{msg}}" />
  <myControls:Greeter message="{{msg}}"/>
 </StackLayout>
</Page>

//Greeter.xml
<StackLayout id="greetingsRoot" loaded="loaded">
    <Label text="Message in greetings component : " />
    <TextField text="{{message}}"></TextField>
    <Label text="{{message}}" />
</StackLayout>

//Greeter.ts
var messageProperty = new dependencyObservable.Property(
    "message","Greeter",new proxy.PropertyMetadata("")
);

class Greeter extends stackLayoutModule.StackLayout{
	static messageProperty = messageProperty;
	get message(){
		return this._getValue(XmlGreeter.messageProperty);
	}
	set message(value: string){
		this._setValue(XmlGreeter.messageProperty, value);
	}
}

export function loaded(args){
  args.object.bindingContext = new Greeter();
}
```

Currently the label and textfield in the `greeter.xml` file do not get set with the value from the parent `main.xml` file.

**Comment by enchev** [comment]
Hey @MarkPerryBV,

I don't see where `loaded` handler is declared in your XML. Can you post more info?

**Comment by MarkPerryBV** [comment]
Greeter.xml line 1 `loaded="loaded"`

**Comment by enchev** [comment]
Sorry, I've missed this! Hey @nsndeck can you help here?

**Comment by MarkPerryBV** [comment]
I can make it work using a different technique referenced in this issue: https://github.com/NativeScript/NativeScript/issues/1252 but that involves loading the XML dynamically. Just before I create a load of widgets in this fashion I wanted to check there wasn't a better way of doing it.

**Comment by dragGH102** [comment]
same issue here +1

**Comment by BenElliottBV** [comment]
+1 here too please!

**Comment by ljx0517** [comment]
+1

**Comment by enchev** [comment]
Hey folks,

We've found what's going in in this case and I'll try to describe. 
It seems that you've mixed our custom control approaches and now you have both XML and JavaScript/TypeScript declarations which is not supported. We have only two ways to create/declare custom control:

- Declare everything in XML file. 
- Declare everything in code.

More info can be found here:
http://docs.nativescript.org/ui/ui-with-xml#custom-components

If you choose to use XML to declare the UI of your custom component you can work in similar way to Page. For example you can handle `loaded` event and attach some view-model to your control `bindingContext`.

```XML
<StackLayout loaded="loaded">
  <Label id="{{ message }}" />
</StackLayout>
```

```JavaScript
exports.loaded = function(args) {
   args.object.bindingContext = new YourViewModel();
}
```
No additional classes, inheritance in code from StackLayout, etc!

If you choose to use code-only approach you should remove your XML file, declare and export desired class in your TypeScript/JavaScript file and NativeScript will `require` and instantiate your class.

So when you declare your custom component namespace you have only two options:
`xmlns:myControl="myFolder/myCustomControl"`

- `myCustomControl` to be the name of XML file with code-behind
- `myCustomControl` to be exported class definition name from a TypeScript/JavaScript file 

Let me know if you have any questions!

**Comment by MarkPerryBV** [comment]
@enchev Does the XML with code-behind approach allow you to use two way attribute bindings?

e.g. `<myControls:Greeter message="{{msg}}"/>` 

If so how is this achieved?

**Comment by enchev** [comment]
Yep, you can use two way bindings in this case. Just handle loaded event and assign to the control bindingContext some view-model with such property. For example:

```JavaScript
class MyModel extends Observable {
  private _msg : string;
  get msg(){
        return this._msg;
    }
    set msg(value: string) {
        if(this._msg !== value) {
             this._msg = value;
             this.notify({ object: this, eventName: Observable.propertyChangeEvent, propertyName: "msg", value: value });
        }
    }
}

exports.loaded = function(args) {
   args.object.bindingContext = new MyModel();
}
```

**Comment by MarkPerryBV** [comment]
@enchev How does that get the value of `{{msg}}` from the `message` attribute in the parent XML file? I don't see how that works?

**Comment by enchev** [comment]
I see, I omitted the fact that you are referring to a custom property. In this case the XML approach will not work. You need to have a class that extends View and provide this additional property.

**Comment by MarkPerryBV** [comment]
@enchev So there is no way in the XML with code-behind file to get access to that custom property?

**Comment by enchev** [comment]
There is no way to define it actually since the property definition should be inside a class.

**Comment by MarkPerryBV** [comment]
@enchev So is the recommended way to create re-usable widgets to do so as "code only" components?

**Comment by enchev** [comment]
Well, if they have custom properties this is the only possible approach for now.

**Comment by MarkPerryBV** [comment]
@enchev Thank you very much for the clarification. I will continue to use the *code only* approach where I dynamically load an XML file as a View Child. Then I get the best of both for now.

**Comment by enchev** [comment]
I'm glad I helped! Should we close this issue?

**Comment by dsiddiqui** [comment]
For Future references, people who are struggling with the custom properties for custom controls, I have a written a blog here:
http://mobile.folio3.com/creating-custom-controls-in-nativescript/

**Comment by stefalda** [comment]
Someone from the NS team can tell if this is a planned feature or not? I think it would be nice addition to the framework...

I've added a request to the nativescript idea site:
https://nativescript.ideas.aha.io/ideas/NS-I-155
