### ISSUE TITLE
Android MediaRecorder.AudioSource = undefined

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/NativeScript#1622]
[MediaRecorder.AudioSource](http://developer.android.com/reference/android/media/MediaRecorder.AudioSource.html) - 

#### Android Sample:

        private void startRecording() {
        mRecorder = new MediaRecorder();
        mRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);
        mRecorder.setOutputFormat(MediaRecorder.OutputFormat.THREE_GPP);
        mRecorder.setOutputFile(mFileName);
        mRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB);

        try {
            mRecorder.prepare();
        } catch (IOException e) {
            Log.e(LOG_TAG, "prepare() failed");
        }

        mRecorder.start();
    }
`

#### NativeScript JS code:

        var MediaRecorder = android.media.MediaRecorder;
        var AudioSource = android.media.MediaRecorder.AudioSource;
        var OutputFormat = android.media.MediaRecorder.OutputFormat;
        var AudioEncoder = android.media.MediaRecorder.AudioEncoder;

       var recorder;

       function startAudio(args) {
          try {
              console.log('START AUDIO');
              recorder = new MediaRecorder();
              console.log('RECORDER: ' + recorder);

             // *** FAILS with AudioSource being undefined. **
             recorder.setAudioSource(AudioSource.MIC);
             recorder.setOutputFormat(OutputFormat.THREE_GPP);
             recorder.setOutputFile("bradTest");
             recorder.setAudioEncoder(AudioEncoder.AMR_NB);
             recorder.prepare();
             recorder.start();
           } catch (ex) {
              console.log(ex);
          }
     }
     exports.startAudio = startAudio;
`

**Comment by bradmartin** [comment]
Also I've added the RECORD_AUDIO permission so that's not the issue.

**Comment by enchev** [comment]
Hey @slavchev can you help here? It seems that [this class](http://developer.android.com/reference/android/media/MediaRecorder.AudioSource.html) is not exposed for some reason.

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#366
