### ISSUE TITLE
tns run android not working fine

### ISSUE THREAD

**Issue by SivaJonnala** [NativeScript/NativeScript#1623]
I am practicing the nativescript sample examples. While I doing I successfully run with the sample groceries app. And then I have restarted my computer. executing the file is not working. even tns build android also not working. 
I am using windows 7 Operating System.
I think problem is at setting the environmental variable is not set correctly. But it is having the environmental variable also.
I have attached my screen shots
![image](https://cloud.githubusercontent.com/assets/10843991/13277811/a1ef9476-daf1-11e5-88f2-9f08645c33dc.png)
![image](https://cloud.githubusercontent.com/assets/10843991/13277842/d4ae3ef8-daf1-11e5-8422-b41fe8bb5608.png)

please let me know the solution for this issue.

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#1536
