### ISSUE TITLE
VSCode debugging setting breakpoints

### ISSUE THREAD

**Issue by lelong37** [NativeScript/NativeScript#1626]
We are able to hit breakpoints only with keyword debugger; and not able to set breakpoints (F9) and hit them.

1. Hit
2. Not Hit

![image](https://cloud.githubusercontent.com/assets/4691404/13279272/23a597fa-da9c-11e5-8192-08cd2488fb49.png)

**Comment by lelong37** [comment]
Seems if we set the breakpoints before debugging (F5), they are not hit, however during the debugging session your are able to set them and get breakpoint hits.

Before

![image](https://cloud.githubusercontent.com/assets/4691404/13280165/fd5a0eb8-daa1-11e5-96dd-396c9123d422.png)

After

![image](https://cloud.githubusercontent.com/assets/4691404/13280225/4ec6381c-daa2-11e5-9bdd-1ed5b613e9bb.png)

**Comment by enchev** [comment]
Hey @ivanbuhov, @KristinaKoeva can you help here?
