### ISSUE TITLE
Nativescript layout overlaping videoview on 1.6 (was fine in 1.5)

### ISSUE THREAD

**Issue by Milewski** [NativeScript/NativeScript#1629]
when setting up and android/ios video player using native components and a {N} placeholder to pass the view.. the view gets on top of the video.. and all i can see/hear is the audio and see the controls...  if i am to remove all the layout within the placeholder it display fine... what`s going on?

**Comment by enchev** [comment]
Most probably you need to call setZOrderOnTop(true) for the video similar to this example:
http://stackoverflow.com/questions/19650483/video-is-not-showing-on-videoview-but-i-can-hear-its-sound
