### ISSUE TITLE
[iOS] Connectivity module getConnectionType() always returns "none" 

### ISSUE THREAD

**Issue by bfattori** [NativeScript/NativeScript#1634]
The connectivity module is always responding with zero when I check the connection type on the simulator. There are no errors, and I can still use the `fetch` module to get at my REST services. How do I simulate a network connection?

I'm running XCode 6.4 (7.2.1 wouldn't even start on my machine) and updated to `tns-core-modules` 1.5.2. *That* fixed the problem of `fetch` not getting anything, but `connectivity.getConnectionType()` is still returning zero.

Any ideas?

**Comment by dtopuzov** [comment]
Can you give us some more details:
- Simulator or real device
- iOS version

**Comment by bfattori** [comment]
Simulator
Version 8.4

**Comment by enchev** [comment]
Hey @bfattori @dtopuzov what's the status here?
