### ISSUE TITLE
NativeScript 1.6 Problem in "CLI", please take a look :)

### ISSUE THREAD

**Issue by wisonye** [NativeScript/NativeScript#1641]
1. For IOS, this command works fine in 1.5, AND it will start the IOS simulator IF it doesn't start,  after upgrade/re-install NativeScript 1.6, it fail:

```javascript
tns livesync ios --emulator --device "iPhone 5" --watch
```

So how I solve this currently is that, first, I do:
```javascript
tns run ios --emulator --device "iPhone 5" --watch
```

then after the IOS simulator comes up, I "Ctrl + C" to stop it and run ( remove the "--device" parameter )
```javascript
tns livesync ios --emulator --watch
```

I don't know why, but that "simple livesync" command was work fine for a long time in 1.5, or maybe I use wrong for a long time ? :)

2. For Android, this command was works fine in 1.5, but now, it broken:

```javascript
tns livesync android --emulator --avd "4.0_HDPI_5.1_API_22"
```

First time run it, it start the android AVD then exit( no mobile app run ) !!!!
Second time run it again, it start the mobile app, BUT CANNOT "livesync" anything, no matter I change what source file in my project !!!!!! :( I don't know what happen there....

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#1539
