### ISSUE TITLE
NativeScript 1.6 Problem 2, please take a look :)

### ISSUE THREAD

**Issue by wisonye** [NativeScript/NativeScript#1642]
In 1.5, for "get round" the splash screen( black screen, App Name, App Icon ) and network issue( e.g. "NSAppTransportSecurity" ) in IOS app, I can modify the "plist" file in XCode project:

```javascript
// "XXXX" is the project name
./platforms/ios/XXXX/XXXX-Info.plist
```

But 1.6, "run" and "livesync" will rebuild the plist file EVERY TIME, my modify gone, .....how to stop it re-write the file or where I can put the content I want to save in plist file ?????

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#1538
