### ISSUE TITLE
livesync with .css not able to sync and crashes

### ISSUE THREAD

**Issue by lelong37** [NativeScript/NativeScript#1643]
Team,

For some reason when making changes to e.g. home-view.ios.css livesync is not able to sync and getting this error.

![image](https://cloud.githubusercontent.com/assets/4691404/13309239/a86b237a-db40-11e5-810d-5a121f95eb47.png)

I've tried removing, re-adding the ios platform, tns build ios, and resyncing but issue is still remains. For now I just stop the livesync session, and restart it to get the new css changes.

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#1537
