### ISSUE TITLE
NativeScript1.6 can not get correct size of _nativeView.bounds.

### ISSUE THREAD

**Issue by zhousong3333** [NativeScript/NativeScript#1644]
`<Page ... loaded="onLoaded">
...
  <StackLayout id="video" height="200"></StackLayout>
...
</Page>`

`exports.onLoaded = function() {
  page = args.object;

  var videoContainer = page.getViewById('video');

  var playerLayer = AVPlayerLayer.new();
  playerLayer.frame = videoContainer._nativeView.bounds;
}`

>  videoContainer._nativeView.bounds is always  (0 0 , 0 0) in 1.6.  before in 1.5 it was normal.

**Comment by hshristov** [comment]
Hi @zhousong3333,

There is no `sizeChanged` event and in `loaded` layout is not completed so you cannot have the bounds of the view. The only workaround I can think of until we implement sizeChanged event is to get the bounds like you do it but wrap the code in `setTimeout` call. This will ensure that at least one layout pass is complete.
