### ISSUE TITLE
Flexbox Layout support

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#1650]
It will be very good if we have support for Flexbox Layout:
http://www.w3schools.com/css/css3_flexbox.asp
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by lawrencetaur** [comment]
+1

**Comment by emmanuelbuah** [comment]
+1

**Comment by fallen90** [comment]
+1 It would definitely help others in transitioning from web to nativescript.

**Comment by dreambo8563** [comment]
+1

**Comment by harry008** [comment]
Flexbox for android by google: https://github.com/google/flexbox-layout . How to integrate is with NativeScript application?

**Comment by enchev** [comment]
Hey @harry008,

You can create a plugin and add dependency in the `Include.gradle` file:
http://docs.nativescript.org/plugins/plugins#includegradle-specification

**Comment by alvirtuoso** [comment]
+1

**Comment by irthos** [comment]
+1 flex box is the present and future of view layouts.

**Comment by kazemihabib** [comment]
+1

**Comment by roblav96** [comment]
+1

**Comment by tomylee001001** [comment]
+1

**Comment by roblav96** [comment]
++1

**Comment by masix** [comment]
+1

**Comment by ShaneXie** [comment]
+1s

**Comment by roblav96** [comment]
+++1

**Comment by TanaseHagi** [comment]
++1

**Comment by hemedani** [comment]
with Flexbox we can easily create rtl version of project. (if whole module write with Flexbox).
It's really cool.
The react-native use Flexbox and also solve the many problem with that.

**Comment by valentinstoychev** [comment]
FlexBox layout is almost ready - very soon we will release a preview version.

**Comment by damianobarbati** [comment]
+1!

**Comment by vchimev** [comment]
Hi, All!

The first version of the flexbox support is already available in`@next` version of the `tns-core-modules` package and soon it will be released officially in `tns-core-modules@2.4.0`.

A quick reference could be found [here] (https://github.com/NativeScript/NativeScript/blob/master/tests/app/ui/layouts/flexbox-layout.md) as well as a few SDK examples [here] (https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/ui-category/layouts).

**Comment by vchimev** [comment]
In addition, Flexbox CSS support is added: issue https://github.com/NativeScript/NativeScript/issues/3044, pull request: https://github.com/NativeScript/NativeScript/pull/3051.

**Comment by wesamco** [comment]
Facebook has released Yoga, have you guys thought about leveraging it?

**Comment by valentinstoychev** [comment]
@wesamco we could. What benefits you see of Yoga compared to Flexbox?

**Comment by NathanaelA** [comment]
@valentinstoychev - It might be a piece that you wouldn't have to maintain, anything to reduce the surface area for the NativeScript engineers might be worth looking at.   Right now you have to maintain and enhance our own custom "flexbox" code, where if this was easily dropped into NS, then you have Facebook and Microsoft (&others) doing the flexbox maintenance for us.  :-D

**Comment by valentinstoychev** [comment]
@NathanaelA agree on that. But I'm more interested on the client perspective. What are teh benefits of the developer using it :). Reusing something from other company is a double sword knife - reuse vs control.

**Comment by wesamco** [comment]
[Yoga](https://github.com/facebook/yoga) is a cross-platform layout engine which implements Flexbox.
Facebook is using it for React Native flexbox support.
React Native & Nativescript are similar, both have kind of a mechanism to execute native code to change UI etc.. why not use this fast unmanaged cross-platform C library in the Nativescript runtime to add flexbox support.
according to [what I have read](https://facebook.github.io/yoga/) it has really good performance.
[Learn More About Yoga](https://facebook.github.io/yoga/docs/learn-more/)
[Yoga iOS example](https://github.com/facebook/yoga/tree/master/YogaKit/YogaKitSample)

**Comment by valentinstoychev** [comment]
Thanks @wesamco - we will definitely test the performance. Our implementation is also native. We are actually using the default flexbox layout implemented by Google.

**Comment by aleclarson** [comment]
@valentinstoychev What was the consensus on Yoga? And what's the "default flexbox layout" by Google?
