### ISSUE TITLE
Formatted text in a listview template loses font setting in iOS

### ISSUE THREAD

**Issue by sharesoft** [NativeScript/NativeScript#1651]
If a label in a listview template is bound to a viewmodel using its **formattedText** property (rather than the text property), the font-family setting appears to be lost in iOS when the listview is scrolled down and back up.
To demonstrate the problem, I’ve made some minor changes to the attached {N} Master Detail sample app. Three files are changed:

**Main-page.xml**
Changed bound property to formattedText...
`<Label formattedText="{{ title }}" class="listItem" />`

**App.css**
Added font-family rule...
```
.listItem {
    margin: 10;
    horizontal-align: center;
    color: #808080;
    font-size: 20;
    font-family:'HelveticaNeue-BoldItalic';
}
```

**Main-view-model.js**
I’ve added comments in the attached code sample to indicate the five lines of code added.

If you build the app, the listview is correctly displayed the first time with the list items displayed in the bold-italic font (see first PNG attachment). If you manually scroll the listview down to the last item and then back up, the first few items lose their font setting and are displayed in the default iOS font (see second PNG attachment). If you then scroll down to the bottom of the list a second time, you’ll see that the last few items have also now lost their font setting.

The same app works fine in Android. Note that I’ve created the app using AppBuilder and tested the app using the {N} iOS companion app. Because I’m using AppBuilder and there is no support for {N} 1.6 yet, I can only build/test the app using {N} 1.5.2.
[Modified_Master_Detail.zip](https://github.com/NativeScript/NativeScript/files/147046/Modified_Master_Detail.zip)
![img_1302](https://cloud.githubusercontent.com/assets/5300285/13328877/163d55d2-dbe9-11e5-806d-3a42e9497d12.PNG)
![img_1303](https://cloud.githubusercontent.com/assets/5300285/13328878/163e9f64-dbe9-11e5-93b5-2868857d64c6.PNG)

**Comment by NickIliev** [comment]
@sharesoft 
I ahve re-tested this issue with our latest release and it is no longer reproducible.
Feel free to re-open it if you encounter it again!
