### ISSUE TITLE
Setting visibility 'hidden' of actionbar item causes 'NSRangeException'

### ISSUE THREAD

**Issue by nripendra** [NativeScript/NativeScript#1654]
Setting visibility hidden on ActionItem causes app to crash with **NSRangeException**.
Below is the code for reference....

```ts
var icon1 = new ActionItem();
icon1.ios.systemIcon = 4;
icon1.ios.position = "right";
icon1.on("tap", (args) => {
  this.zone.run(() => {
    icon1.visibility = "hidden";
  });
});

var iconTools = new ActionItem();
iconTools.icon = "res://tool";
iconTools.ios.position = "right";
iconTools.on("tap", (args) => {
    this.zone.run(() => {
        this.basicSettings = !this.basicSettings;
    });
});

ActionBarUtil.addButton(icon1);
ActionBarUtil.addButton(iconTools);
ActionBarUtil.setTitle("myapp");
```
Following is the error I'm getting when tapping icon1.
```
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndex:]: index 2 beyond bounds [0 .. 1]'
	*** First throw call stack:
	(
		0   CoreFoundation                      0x03364a14 __exceptionPreprocess + 180
		1   libobjc.A.dylib                     0x02e25e02 objc_exception_throw + 50
		2   CoreFoundation                      0x0323ca4e -[__NSArrayI objectAtIndex:] + 206
		3   UIKit                               0x0168269c -[UINavigationBar _getTitleViewFrame:leftViewFrames:rightViewFrames:forItemAtIndex:returnedIdealWidthOfTextContent:availableLayoutWidthForTextContent:idealBackButtonWidth:] + 15460
		4   UIKit                               0x01685c87 -[UINavigationBar _getTitleViewFrame:leftViewFrames:rightViewFrames:forItemAtIndex:] + 1006
		5   UIKit                               0x01685ed2 -[UINavigationBar _getTitleViewFrame:leftViewFrames:rightViewFrames:] + 175
		6   UIKit                               0x0166f334 -[UINavigationBar _setLeftViews:rightViews:] + 2552
		7   UIKit                               0x01656967 -[UINavigationItem updateNavigationBarButtonsAnimated:] + 286
		8   UIKit                               0x016575cb -[UINavigationItem setObject:forLeftRightKeyPath:animated:] + 804
		9   UIKit                               0x016584ea -[UINavigationItem setRightBarButtonItems:animated:] + 114
		10  fsnsng                              0x007a3918 ffi_call_i386 + 24
	)
```

Basically `setRightBarButtonItems:animated` is throwing this exception, when the number of items is changed from its initial value. Setting visibility to hidden at time of adding to action bar doesn't have this problem. This problem occurs when visibility changes at runtime.

This same problem also seems to occur when adding actionitems after setting title.

This looks more like implementation detail of `setRightBarButtonItems:animated`, but it would be helpful if someone could suggest a workaround.

**Comment by nripendra** [comment]
one workaround is to clear all icons and text

```ts
icon1.ios.systemIcon = null;
icon1.icon = "";
icon1.text = "";
``` 

It is also interesting to note that changing icon1.ios.systemIcon doesn't reflect change in ui. Here is the workaround:

```ts
this.showplus = !this.showplus;
icon1.ios.systemIcon = this.showplus ? 0 : 4;
// HACK!! change to ios.systemIcon is not observed, hence actionbar is not redrawn. 
// Changing icon property causes the actionbar to re-rendered. 
// This hack works because when ios.systemIcon is present, the 'icon' property is ignored.

icon1.icon = "" + icon1.ios.systemIcon;//any new value that triggers change should do...
```

**Comment by hshristov** [comment]
There is no "hidden" value for Visibility enum. Its only - "visible" or "collapse".
https://github.com/NativeScript/NativeScript/blob/master/ui/enums/enums.ts

**Comment by nripendra** [comment]
@hshristov 

Yeah my bad, it should have been "collapse" instead of "hidden", probably hangover from css :)

But the problem is still the same even after replacing "hidden" with "collapse". As I mentioned above problem doesn't seem to be coming from nativescript, it is being thrown by `setRightBarButtonItems:animated`. Which means nativescript doesn't mind even if I use "hidden" to hide  element. But ios appbar doesn't seem to like changing number of buttons at runtime.
