### ISSUE TITLE
Weird whitish tint on ActionBar

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#1657]
Hi,

I've been struggling for a while to set the ActionBar background-color to the same as Page. For some reason, the same hex-color does not match between ActionBar and Page in the CSS. Here's what the CSS looks like:
```
Page {
  background-color: #30b773;
  color: #ffffff;
}
ActionBar {
  background-color: #30b773;
  color: #ffffff;
}
```

And this is the outcome:
![problem](https://cloud.githubusercontent.com/assets/2098838/13353463/de131f00-dc94-11e5-8591-abd197e53191.png)

Actually, there are 3 different background colors there (hard to see on some monitors):

- Status bar (carrier, clock, battery) is #4abd83
- Navigation/ActionBar is #46b97f
- Page background is #30b773

The only correct color is of course the Page background... Actually, the result I'm looking for is just a fullscreen view of a page, but keeping the status bar. I've read about Modals, but I'm not sure that is what I want here. Any suggestions?

How can I fix this? Appreciate any help. Thanks!

**Comment by mikeres0** [comment]
+1 this. This has annoyed me since the functionality was introduced to style the `ActionBar` component.

**Comment by burkeholland** [comment]
I think this is because the ActionBar on iOS has translucency by default. You have to turn that off. Check https://github.com/NativeScript/NativeScript/issues/1151

**Comment by NordlingArt** [comment]
@burkeholland The issue was never solved in there though.

**Comment by burkeholland** [comment]
Looks like it's not fixed in 1.6, but under consideration for 1.7.

**Comment by NordlingArt** [comment]
Ah, just noticed that. I guess I'll wait for the fix to come then.

**Comment by Cornishdan** [comment]
+1 on this too.  Still not fixed in 1.7.  I'm using Burke's nova theme (dark) and my actionbar just doesn't look right with my sidedrawer.  Setting translucency to false is not a workaround due to the weird animation it produces: https://github.com/NativeScript/NativeScript/issues/1151#issuecomment-159735337

Please fix.  Thanks

**Comment by einicher** [comment]
+1 
the suggested solution `frameModule.topmost().ios.controller.navigationBar.tanslucent = false;` is not working for me with 1.7. Maybe translucency should be disabled by default, since it shows a wrong color and is not really translucent at all.

**Comment by enchev** [comment]
Anyone having the same problem with latest (`2.1` or `@next`) versions?

**Comment by pmz** [comment]
This issue is marked as closed but I have the same problem.
How an one make a navigationBar's translucent property to false without having this weird transition?

**Comment by NickIliev** [comment]
Hello @pmz 

Thank you for reporting this issue - I have tested it on my side and indeed the problem with the transaction when the translucent is set to false is present in NativeScript 2.3.0.

You can track it [here](https://github.com/NativeScript/NativeScript/issues/2870)

As a solution you can do the follwing.
1.) Create your action bar
2.( Set the **translucent** to **false** as desired
```
frameModule.topmost().ios.controller.navigationBar.translucent = false;
```
3.) Finally when navigating to another page use animated: true with transition
example:
```
  frameModule.topmost().navigate({
    moduleName: "sub-page",
    animated: true,
    transition: {
      name: "curl" // iOS only transition
    }
  });
```

**Comment by einicher** [comment]
I do not understand, how does this help since the homescreen is showing up translucent before navigating anywhere.

**Comment by NickIliev** [comment]
@einicher the solution above is to get rid of the page transition bug which appeasrs duritg the transition from page A to page B - perhaps, you are observing different issue (if so you can describe it in a new issue in order to investigate)
