### ISSUE TITLE
Enums.js should be moved to root!

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#1658]
## Please, provide the details below:

 enums/enums.js does NOT belong in ui folder; it is used by things throughout the core modules.   In v2.0 (or when you introduce the other **breaking changes**); I recommend you move it to where it belongs in the root folder...
### Did you verify this is a real problem by searching

yes
### Which platform(s) does your issue occur on?

Both
### Please provide the following version numbers that your issue occurs with:

Core: 1.6.2 and prior
### Please tell us how to recreate the issue in as much detail as possible.

I should be doing 

```
var enums = require('enums');
```

not

```
var enums = require('ui/enums');
```

**Comment by bfattori** [comment]
+1

And add references from modules like `ActionBar` back to `enums` so we'll know what values to use where.

Thanks!

**Comment by gagandeepp** [comment]
IS this open?

**Comment by NathanaelA** [comment]
@gagandeepp - Yep, this is one that is open for anyone to change...

**Comment by nike47** [comment]
Can I work on this issue.

**Comment by NathanWalker** [comment]
Fixed
