### ISSUE TITLE
Loading local resources or files into a WebView

### ISSUE THREAD

**Issue by bfattori** [NativeScript/NativeScript#1659]
Is it possible to have the WebView itself load contents from the local filesystem? I'm storing the HTML in a sub-folder of `fs.knownFolders.documents()` that I create. The HTML loads properly, but what about CSS, scripts, and Images? I've tried using `~/web/css/form.css` within a &lt;link&gt; element:
```
<head>
   <link rel="stylesheet" href="~/web/css/form.css"/>
</head>
```
But the styles are never applied. I saw a previous issue that talked about setting the `baseURL` on Android. Is this because I'm loading the file from `documents()` and the CSS is in `currentApp()`?

I'm confused as to how to use the WebView to load all local HTML, CSS, scripts, and images. Especially since I have to download the HTML from a remote server and save it to `documents()`.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 1.6.1
- Cross-platform modules: ^1.6.2
- Runtime(s): 1.6.0 (iOS) 1.6.2 (Android)
- Plugin(s): nativescript-webview-interface 1.1.0

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
The context contains `category` (such as **General**) and `form` (such as **Testing**)
```
FormViewModel.prototype.showForm = function(evt) {
        this.context = evt.context;
        var documents = fs.knownFolders.documents().path;

        if (this.context) {
            this.webView.src = documents + "/forms/" + this.context.category + "/" + this.context.form.replace(/\s/g, "_") + ".html";
        }
    };
```
The &lt;head&gt; element looks like this:
```
<head>
   <title>Testing Form</title>
   <link href="~/modules/web/css/forms.css" rel="stylesheet">
   <script src="~/modules/web/scripts/formRunner.js"></script>
   <script src="~/modules/web/scripts/nativescript-webview-interface.js" type="application/javascript"></script>
</head>
```

**Comment by vbresults** [comment]
I may be wrong but I think you have to whitelist the schemes used to locally access files first.

**Comment by enchev** [comment]
Hey folks,

We've fixed several similar issues in the past:
https://github.com/NativeScript/NativeScript/issues/613
https://github.com/NativeScript/NativeScript/issues/963

Not sure however if `~` is supported at all.

**Comment by bfattori** [comment]
Will this work on iOS since the `currentApp()` folder is read-only? See, my situation is this:

The HTML forms, themselves, are downloaded from a remote server to the local device so it can operate on or off the network. This means, according to the documentation, that I have to write the files into the `documents()` folder. But when you set the `baseURL` property of the WebView, you're setting it to `currentApp()`. If there was a way to set that folder as the `baseURL` then I would think it would work for me. Maybe `~/some/folder/` would point to `currentApp()` and `~~/some/folder` would point to `documents()`?

**Comment by enchev** [comment]
Hey @bfattori,

Actually if you load html file the base url will be where the file is located:
https://github.com/NativeScript/NativeScript/blob/master/ui/web-view/web-view.ios.ts#L114
