### ISSUE TITLE
Feature request: automatically slide views when the keyboard shows

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/NativeScript#166]
See: https://twitter.com/kdawg02/status/598811302858006528, https://twitter.com/kdawg02/status/598811520915628032, and https://twitter.com/kdawg02/status/598811715862659072

The use case here is you have multiple text fields on one page and you want to provide an easy way for the user to move between them. There's an iOS library that does this sort of thing: https://github.com/hackiftekhar/IQKeyboardManager, so this might be as simple as showing how to use that library.

I've personally ran into this issue on my iOS apps, but I'm not sure what the situation is like on Android.

**Comment by kdawg1406** [comment]
For forms with multiple TextFields there are two considerations:
1.  Moving to the next field when the user presses Return on the Keyboard.
2.  If the field is gets covered when the keyboard displays, the form must be scrolled up.

I've had to do this in Unity3D and its a REAL PIA for Android.  Could be Unity's implementation.

IMO:  Solutions for these very common use cases needs to be part of NativeScript.  Without a native NativeScript solution, developers will need to dive into platform specific code on all platforms they are targeting. 

Providing this solution would raise the bar for NativeScript and it's simple cross-platform goals.  

Until this, I would not even attempt writing a cross-platform NativeScript application that had more than a few TextFields on a form. 

This issue could block adoption by other developers as well.

Thank you for your consideration of this important feature.

Karl

**Comment by hackiftekhar** [comment]
Being author of 'IQKeyboardManager', I would not suggest to use any `IQKeyboardManager` for any library or framework. `IQKeyboardManager` is designed for projects to help developers for their convenience, it's not designed for adding/shipping with SDK's because as @kdawg1406 said 'This issue could block adoption by other developers as well'.

Iftekhar

**Comment by N3ll** [comment]
Thanks to @tjvantoll now you can use this plug-in for that https://www.npmjs.com/package/nativescript-iqkeyboardmanager.

**Comment by hackiftekhar** [comment]
Great! Thanks @N3ll

**Comment by richdyang** [comment]
@kdawg1406 Do you have any difficulties when integrating NativeScript and Unity3D?

**Comment by alisomay** [comment]
It is a good question, would you share your experience integrating nativescript and unity?
