### ISSUE TITLE
Feature Request: Add css ability for other properties

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#1660]
### Did you verify this is a real problem by searching 
yes

### Tell us about the problem
I'd like to be able to do
```css
StackLayout {
  orientation: horizontal;
}
```

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
v1.6x (and before)

### Please tell us how to recreate the issue in as much detail as possible.
CSS does not appear to be able to set orientation on StackLayout.

Grid: Rows, Columns, row, column, colSpan, rowSpan would also be nice to be able to control in CSS

**Comment by enchev** [comment]
Hey @NathanaelA,

At the moment we are trying to avoid CSS properties that are supported only for specific components. For example you cannot set orientation for Button.

**Comment by NathanaelA** [comment]
Hey @enchev,

1. I realize the property is only used for some components; that doesn't stop its usefulness.  Right this minute instead of being able to control this via CSS, I have to create a function in the page it is on to handle this. ;-)

2. I realize orientation is not valid HTML CSS, but using it as a valid NS CSS should not matter.  As it is NS has several other CSS fields that aren't standard and that seems really silly to prefix a fully valid NS CSS value -- you really don't want to be constrained by HTML.  You need to do what is right for NS.

**Comment by enchev** [comment]
Hey @atanasovg, @hshristov, @ligaz, @tjvantoll what do you think? Should we:
1. Expose CSS properties that will work only on some of the elements similar to browsers
2. Expose custom CSS properties valid for NativeScript only with a `-ns-` prefix similar to other vendor prefixes: https://developer.mozilla.org/en-US/docs/Glossary/Vendor_Prefix

**Comment by atanasovg** [comment]
That's definitely an interesting discussion. As of now we **do** have properties that do not make sense for some views - for example `font-size` does not affect most of the views directly but rather the text-displaying ones. Still, if the property is inheritable - like the `font-size` one - then it is useful to apply it at root level and let interested descendants inherit and utilize the value. With that said:

- My vote goes for adding CSS properties regardless of whether they are applicable to each view type or not.
- IMO @NathanaelA has a point as to prefixing non-CSS standard properties with `-ns-`. Since {N} is the only CSS parsing engine such an additional separation seems artificial to me.

**Comment by tjvantoll** [comment]
Before I get into specifics about the syntax, I’ll start by agreeing with @NathanaelA that this is a very important use case that I’ve also wanted. @NathanaelA’s [orientation plugin](https://github.com/nathanaela/nativescript-orientation) for instance is slick, but I find that the biggest thing I want to change is the `orientation` of a `<StackLayout>`, or the `rows`/`columns` of a `<GridLayout>`, which currently you can’t do in CSS. Beyond orientation, this opens the door for things like media queries in the future. I’d love to be able to say, for instance, column B takes up 50% of the screen on phones, but 75% of the screen on tablets—and to do so in CSS.

> My vote goes for adding CSS properties regardless of whether they are applicable to each view type or not.

+1. The browser has set the precedent here. For example, the browser’s `list-style` property makes no sense outside of a `<ul>`; `table-layout` only applies to `<table>`s; etc.

> IMO @NathanaelA has a point as to prefixing non-CSS standard properties with -ns-. Since {N} is the only CSS parsing engine such an additional separation seems artificial to me.

I could go either way on this one. The semantics aren’t all that important to me as long as we provide something that allows me to accomplish the task. I will note, however, that we’re already broken this rule in a way—our `horizontal-align` property isn’t a thing in CSS 😀
