### ISSUE TITLE
Navigation transition direction not applying to ActionBar

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#1665]
I have applied a default transition of:

```
frameModule.Frame.defaultTransition = {
  name: "slide",
  duration: 300,
  curve: "easeIn"
};
```

As the documentation says, "slide" is the same as "slideLeft". It works as intended. But when I change it to "slideRight" on a button somewhere, only the Page will use the SlideRight. Not the ActionBar (the title that is). It is still locked to Slide/SlideLeft.

```
frameModule.topmost().navigate({
  moduleName: "views/settings/settings",
  transition: { name: "slideRight" },    // <-- This line
  backstackVisible: false,
  clearHistory: true
});
```

This is for version 1.6.1. Only tested on iOS so far.

**Comment by NordlingArt** [comment]
Figured I might need to show you the problem in action:


![jnlqbfu](https://cloud.githubusercontent.com/assets/2098838/13555491/23ff87c2-e3c2-11e5-8a46-86d588b29e8f.gif)

As you can see, a transition to the right will only do it to the content and not the Action Bar. Same goes for every transition effects - fade for instance. Is it only me or is this a global issue?

**Comment by tsonevn** [comment]
Hi @NordlingArt,
Thank you for reporting this issue. 
I was able to recreate the abnormality in a local project.
Unfortunately we confirm that this global issue for IOS projects.
We will do everything possible to solve the problem. 
Temporary solution can be to use the default transition.

**Comment by NordlingArt** [comment]
@tsonevn Thanks for checking. My project is far from being public, so I can definitely live with this until it is fixed 🙂

**Comment by hamorphis** [comment]
Unfortunately, we can only animate the two pages (i.e. two UIViewControllers) the one that is going out and the one that is coming in. I guess that you can use slide right for pages that do not have a navigation bar. Otherwise, use the slide left transition. We can't really affect the way iOS animates its navigation bar during a transition. I am sorry.

**Comment by NordlingArt** [comment]
@hamorphis Are you sure? Because if you check the direction of the view when going back in history ("< Back" button), the navigation bar uses the slide-right animation. See below:

![transitionissue](https://cloud.githubusercontent.com/assets/2098838/13927949/0f63d6be-ef94-11e5-9001-81dc3f47cbbf.gif)


As for slide up and down. I don't think the navigation bar should animate at all. Maybe just fading in/out.
