### ISSUE TITLE
Android-Tablet Crash (empty project)

### ISSUE THREAD

**Issue by seppel1992** [NativeScript/NativeScript#1669]
Hi,

I am not able to run my app on an Android-Tablet anymore and after spending some time, I noticed, that even a **new created app (empty project)** cannot be startet on Tablet devices, because of the following error:

> java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.TestTablet/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
> Calling js method onCreateView failed
> 
> Error: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
>     android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:986)
>     android.graphics.drawable.Drawable.createFromXml(Drawable.java:930)
>     android.content.res.Resources.loadDrawable(Resources.java:3436)
>     android.content.res.Resources.getDrawable(Resources.java:1917)
>     android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
>     android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:180)
>     android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:173)
>     android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
>     android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
>     android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
>     android.support.v7.widget.Toolbar.<init>(Toolbar.java:192)
>     java.lang.reflect.Constructor.constructNative(Native Method)
>     java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>     com.tns.Platform.createInstance(Platform.java:311)
>     com.tns.Platform.callJSMethodNative(Native Method)
>     com.tns.Platform.dispatchCallJSMethodNative(Platform.java:812)
>     com.tns.Platform.callJSMethod(Platform.java:711)
>     com.tns.Platform.callJSMethod(Platform.java:690)
>     com.tns.Platform.callJSMethod(Platform.java:680)
>     com.tns.gen.android.app.Fragment_ftns_modules_ui_frame_frame_l34_c42__.onCreateView(android.app.Fragment.java)
>     android.app.Fragment.performCreateView(Fragment.java:1700)
>     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
>     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
>     android.app.BackStackRecord.run(BackStackRecord.java:684)
>     android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
>     android.app.Activity.performStart(Activity.java:5460)
>     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)
>     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
>     android.app.ActivityThread.access$900(ActivityThread.java:175)
>     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
>     android.os.Handler.dispatchMessage(Handler.java:102)
>     android.os.Looper.loop(Looper.java:146)
>     android.app.ActivityThread.main(ActivityThread.java:5602)
>     java.lang.reflect.Method.invokeNative(Native Method)
>     java.lang.reflect.Method.invoke(Method.java:515)
>     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
>     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
>     dalvik.system.NativeStart.main(Native Method)
> File: "/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/action-bar/action-bar.js, line: 126, column: 24
> 
> StackTrace: 
> 	Frame: function:'ActionBar._createUI', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/action-bar/action-bar.js', line: 126, column: 25
> 	Frame: function:'View._onContextChanged', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/core/view.js', line: 206, column: 14
> 	Frame: function:'View._onAttached', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/core/view.js', line: 164, column: 14
> 	Frame: function:'eachChild', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/core/view.js', line: 169, column: 23
> 	Frame: function:'Page._eachChildView', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/page/page-common.js', line: 247, column: 9
> 	Frame: function:'View._onAttached', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/core/view.js', line: 175, column: 18
> 	Frame: function:'View._addViewCore', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/core/view.js', line: 144, column: 18
> 	Frame: function:'View._addView', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/core/view-common.js', line: 912, column: 14
> 	Frame: function:'onFragmentShown', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/frame/frame.js', line: 124, column: 11
> 	Frame: function:'android.app.Fragment.extend.onCreateView', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/frame/frame.js', line: 60, column: 17
> 
> 
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
> 	at android.app.ActivityThread.access$900(ActivityThread.java:175)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loop(Looper.java:146)
> 	at android.app.ActivityThread.main(ActivityThread.java:5602)
> 	at java.lang.reflect.Method.invokeNative(Native Method)
> 	at java.lang.reflect.Method.invoke(Method.java:515)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
> 	at dalvik.system.NativeStart.main(Native Method)
> Caused by: com.tns.NativeScriptException: 
> Calling js method onCreateView failed
> 
> Error: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
>     android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:986)
>     android.graphics.drawable.Drawable.createFromXml(Drawable.java:930)
>     android.content.res.Resources.loadDrawable(Resources.java:3436)
>     android.content.res.Resources.getDrawable(Resources.java:1917)
>     android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
>     android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:180)
>     android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:173)
>     android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
>     android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
>     android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
>     android.support.v7.widget.Toolbar.<init>(Toolbar.java:192)
>     java.lang.reflect.Constructor.constructNative(Native Method)
>     java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>     com.tns.Platform.createInstance(Platform.java:311)
>     com.tns.Platform.callJSMethodNative(Native Method)
>     com.tns.Platform.dispatchCallJSMethodNative(Platform.java:812)
>     com.tns.Platform.callJSMethod(Platform.java:711)
>     com.tns.Platform.callJSMethod(Platform.java:690)
>     com.tns.Platform.callJSMethod(Platform.java:680)
>     com.tns.gen.android.app.Fragment_ftns_modules_ui_frame_frame_l34_c42__.onCreateView(android.app.Fragment.java)
>     android.app.Fragment.performCreateView(Fragment.java:1700)
>     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
>     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
>     android.app.BackStackRecord.run(BackStackRecord.java:684)
>     android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
>     android.app.Activity.performStart(Activity.java:5460)
>     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)
>     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
>     android.app.ActivityThread.access$900(ActivityThread.java:175)
>     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
>     android.os.Handler.dispatchMessage(Handler.java:102)
>     android.os.Looper.loop(Looper.java:146)
>     android.app.ActivityThread.main(ActivityThread.java:5602)
>     java.lang.reflect.Method.invokeNative(Native Method)
>     java.lang.reflect.Method.invoke(Method.java:515)
>     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
>     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
>     dalvik.system.NativeStart.main(Native Method)
> File: "/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/action-bar/action-bar.js, line: 126, column: 24
> 
> StackTrace: 
> 	Frame: function:'ActionBar._createUI', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/action-bar/action-bar.js', line: 126, column: 25
> 	Frame: function:'View._onContextChanged', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/core/view.js', line: 206, column: 14
> 	Frame: function:'View._onAttached', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/core/view.js', line: 164, column: 14
> 	Frame: function:'eachChild', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/core/view.js', line: 169, column: 23
> 	Frame: function:'Page._eachChildView', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/page/page-common.js', line: 247, column: 9
> 	Frame: function:'View._onAttached', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/core/view.js', line: 175, column: 18
> 	Frame: function:'View._addViewCore', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/core/view.js', line: 144, column: 18
> 	Frame: function:'View._addView', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/core/view-common.js', line: 912, column: 14
> 	Frame: function:'onFragmentShown', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/frame/frame.js', line: 124, column: 11
> 	Frame: function:'android.app.Fragment.extend.onCreateView', file:'/data/data/org.nativescript.TestTablet/files/app/tns_modules/ui/frame/frame.js', line: 60, column: 17
> 
> 
> 	at com.tns.Platform.callJSMethodNative(Native Method)
> 	at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:812)
> 	at com.tns.Platform.callJSMethod(Platform.java:711)
> 	at com.tns.Platform.callJSMethod(Platform.java:690)
> 	at com.tns.Platform.callJSMethod(Platform.java:680)
> 	at com.tns.gen.android.app.Fragment_ftns_modules_ui_frame_frame_l34_c42__.onCreateView(android.app.Fragment.java)
> 	at android.app.Fragment.performCreateView(Fragment.java:1700)
> 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
> 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
> 	at android.app.BackStackRecord.run(BackStackRecord.java:684)
> 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
> 	at android.app.Activity.performStart(Activity.java:5460)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)
> 	... 11 more
> Caused by: java.lang.reflect.InvocationTargetException
> 	at java.lang.reflect.Constructor.constructNative(Native Method)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at com.tns.Platform.createInstance(Platform.java:311)
> 	... 24 more
> Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020016
> 	at android.content.res.Resources.loadDrawable(Resources.java:3440)
> 	at android.content.res.Resources.getDrawable(Resources.java:1917)
> 	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
> 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:180)
> 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:173)
> 	at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
> 	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
> 	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
> 	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:192)
> 	... 27 more
> 

I tested this on the following Tablet devices:
- Samsung Galaxy Tab 4 (Android 4.4.2) 
- ASUS MeMO Pad HD 7 (Android 4.2.2) 

When I run the app on Genymotion Tablet-Emulator, the app starts without problems. Unfortunately, I have no iPads available for testing. 

During the tests, I used the following configurations:
- NativeScript CLI version 1.6.1
- tns-core-modules version 1.6.2

I have the same problem using Telerik AppBuilder with the following configuration:
- NativeScript version 1.5.2
- tns-core-modules version 1.5.1

As I already mentioned in the beginning, this problem occurs completely independent from my own source code, because you should be able to reproduce this issue by creating a new project and running that on a Tablet device (Android).

Best regards,
Felix

**Comment by erkanarslan** [comment]
Have the same problem. Empty project does not work on Android 4.x but works on 5.x

**Comment by bradmartin** [comment]
I have not tested this out but I think your issue might be your need to update the Android Support library. Last week Google updated to 23.2 I believe. Update the support library and then try this again. This is just a hunch I have :+1:

**Comment by rosen-vladimirov** [comment]
@bradmartin  the issue is caused by the update. Check my comment [here](https://github.com/NativeScript/NativeScript/issues/1672) 
The workaround can be found [here](https://github.com/NativeScript/nativescript-cli/issues/1549)

**Comment by sitefinitysteve** [comment]
Will this be addressed in the next update so we wont need a workaround? (it's needing to modify a file in platforms that worries me)
