### ISSUE TITLE
Image tag in xml not Support 9 patch image

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#1670]
_From @ljx0517 on February 29, 2016 12:28_

does {n}  Support 9 patch image？

_Copied from original issue: NativeScript/android-runtime#370_

**Comment by PanayotCankov** [comment]
These images are frequently used in native development.
iOS has the built in utilities to achieve something similar to Android's 9 patch image:
[resizableImageWithCapInsets:resizingMode:](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIImage_Class/#//apple_ref/occ/instm/UIImage/resizableImageWithCapInsets:resizingMode:)
In Android there is the [Nine-patch drawables](http://developer.android.com/guide/topics/graphics/2d-graphics.html#nine-patch) and some [tooling](http://developer.android.com/tools/help/draw9patch.html) to support authoring such images.

We should verify if we can use `.9.png` images in Android out of the box, and it would be nice if Android `.9.png`-s can be used in iOS as well.

**Comment by vekexasia** [comment]
that would be good indeed.

**Comment by PanayotCankov** [comment]
Closing due to low demand
