### ISSUE TITLE
ListPicker: enable working with an array of objects

### ISSUE THREAD

**Issue by sebawita** [NativeScript/NativeScript#1677]
Currently the **ListPicker** can only display values from an array of strings, however it is not usable for an array of objects, like: 
`var items = [ {name: "Pizza", price: "8"},{name: "Hot Dog", price: "2"},{name: "Burger", price: "6"} ];.`
It would be good if there were properties like:
- **textField** - to define which field should be used to display
- **valueField** - to define which field should be used to return
- **selectedValue** or **selectedItem** - bindable property, that would contain the selected value (as defined by **valueField**)

These could be used like this:
```
    <ListPicker
        items="{{ items }}"
        textField="name"
        valueField="price"
        selectedValue="{{ itemPrice }}"
    ></ListPicker>
```

**Comment by enchev** [comment]
Hey @sebawita,

if you override toString() and use binding expressions you can something like this:

```XML
<Page loaded="pageLoaded">
  <StackLayout>
    <Label text="{{ items ? 'Selected item: ' + items[index].name : '' }}" />
    <ListPicker items="{{ items }}" selectedIndex="{{ index }}" />
  </StackLayout>
</Page>
```
```TypeScript
import observable = require("data/observable");
import pages = require("ui/page");

export function pageLoaded(args: observable.EventData) {
    let page = <pages.Page>args.object;

    let items = new Array<any>();
    for (let i = 0; i < 10; i++) {
        let name = `Name ${i}`;
        items.push({ id: i, name: name, toString: () => { return name; } });
    }

    page.bindingContext = { items: items, index: 2 };
}
```

Furthermore if your `bindingContext` is not anonymous but `Observable` the `Label` text will be updated when you raise change for `index` property.

**Comment by sitefinitysteve** [comment]
@sebawita I feel like we should re-open this, it's more than a valid scenario, very much a common one that should need less code than this?  I feel like we need this to be more dropdownlist\comboboxy with object support.

**Comment by x00** [comment]
he gave a perfectly good solution. 

You can define toString() to return a string.

**Comment by jonnysamps** [comment]
Using `toString` is not valid if already being used for serialization.  Seems like this should be reopened.

**Comment by sebawita** [comment]
To be honest this workaround feels a little bit hacky, as it requires extra code for something that should be rather simple.
Since UI for NativeScript is free now I moved on to using the [AutoComplete component](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/AutoCompleteTextView/autocomplete-getting-started#radautocompletetextview-getting-started). Or for building the screens where I expect users to enter a lot of data I use [DataForm](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/DataForm/dataform-overview). It just makes my app look and behave a lot better.

**Comment by pedromorgan** [comment]
Am I correct in understanding that I can't use `ListPicker` with an array of objects without the hack above ???

As @sebawita said.. ".. feels a little bit hacky, as it requires extra code for something that should be rather simple..."

**Comment by Topksk** [comment]
Hello !

Was this issue resolved?

**Comment by pedromorgan** [comment]
@Topksk use the RadListView instead (proprietary) http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/overview

**Comment by Topksk** [comment]
https://github.com/pedromorgan,
It is ListView
I needs ListPicker.

**Comment by WebDaMa** [comment]
There is a better way from the manual:
[https://docs.nativescript.org/api-reference/classes/_ui_list_picker_.listpicker#items](url)
Location Modal
```javascript
export class Location {
    id: string;
    code: string;
}
```
Constructor:
```javascript
import { Component, OnInit } from "@angular/core";
import { ListPicker } from "tns-core-modules/ui/list-picker";
import { Location } from "~/shared/models/location.model";
import { LocationService } from "~/shared/services/location.service";

@Component({
    selector: "Settings",
    moduleId: module.id,
    providers: [LocationService],
    templateUrl: "./settings.component.html"
})
export class SettingsComponent implements OnInit {
    locations: Array<Location> = [];
    items: object = {};
    location: Location;
    selectedIndex: number = 0;

    constructor(private locationService: LocationService) {
    }

    ngOnInit(): void {
        this.locationService.getLocationsAction()
            .subscribe(
                (result: Array<Location>) => {

                    this.locations = result;

                    /*THIS IS WHERE YOU CAN SET THE DISPLAYED TEXT*/
                    this.items = {
                        items: this.locations,
                        length: this.locations.length,
                        getItem(index) {
                            const item = this.items[index];
                            /*DO WHAT YOU WANT*/
                            return item.code;

                        }
                    };

                },
                (error) => {
                    console.dir(error);
                }
            );
    }

    selectedIndexChanged(args) {
        const picker = <ListPicker>args.object;
        console.log("picker selection: " + picker.selectedIndex);

        this.location = this.locations[picker.selectedIndex];
        console.log("item:");
        //ITEM STILL IS AN OBJECT
        console.dir(this.location);
    }

}
```
Template:
```html
<ListPicker [items]="items" [selectedIndex]="selectedIndex" (selectedIndexChange)="selectedIndexChanged($event)" class="p-15"></ListPicker>

**Comment by sebawita** [comment]
I've created a PR #6033 to take care of this.
At the moment this is for JS/TS only. Angular is coming next
