### ISSUE TITLE
Physical drag-to-page transition (need confirmation if possible yet or not)

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#1680]
As for the newly added NagivationTransitions, I thought that was the solution to this feature. But seems it is not.

What I would like to do is to physically be able to drag between pages, just like how it works on Snapchat or Tinder. As in, you don't need to push any button in the action bar to navigate between views.

If this doesn't exist, I would like to investigate the issue. However, I am not too used to NativeScript yet so I don't feel like I have the knowledge to actually do it (although I've done it in pure HTML/JS/CSS).

**Comment by bradmartin** [comment]
@NordlingArt - I haven't used Snapchat or Tinder apps (I know what they are :smile:) so I'm not sure what the interface is but I'm curious if the NativeScript `<TabView>` is what you are looking for. You can swipe between different pages/views.

**Comment by NordlingArt** [comment]
@bradmartin - My understanding is that you cannot swipe between the views in a <TabView>? I made a new page with this inside:

```
<TabView>
    <TabView.items>
      
      <TabViewItem title="Tab 1">
        <TabViewItem.view>
          <Label text="Label in Tab1" />
        </TabViewItem.view>
      </TabViewItem>
      
      <TabViewItem title="Tab 2">
        <TabViewItem.view>
          <Label text="Label in Tab2" />
        </TabViewItem.view>
      </TabViewItem>
      
    </TabView.items>
  </TabView>
```

I cannot swipe between the tabs (iOS). Also, I cannot have each tab as an external page within the "views" folder.

**Comment by bradmartin** [comment]
Oh yea iOS maybe doesn't work that way. Android you can swipe between the
pages. As for the views, I believe you can reference external xml files in
the TabView. There was an issue awhile back about this. Might be in the
docs now also. Pretty sure there was a decent solution :)

**Comment by NordlingArt** [comment]
@bradmartin - I'm gonna continue looking for a solution. [I just found this](https://github.com/goktugyil/EZSwipeController) (not NativeScript), but it shows exactly what I mean. Like some kind of sub view container.

**Comment by bradmartin** [comment]
If these are available as cocopoads you could easily integrate them into your NativeScript app. So it's possible to use with NativeScript but you have to make the "bridge" to use it. You could make a plugin or just keep it internal and use the code in your app.

**Comment by NordlingArt** [comment]
@bradmartin - First link is CocoaPods, yes. I have no idea how it works though. Might take a look at it soon, but currently I'm trying to create one from scratch. We'll see how that goes 😅
