### ISSUE TITLE
Documentation needed for XML User Interface Widgets

### ISSUE THREAD

**Issue by dskaggs** [NativeScript/NativeScript#1685]
There is nowhere on the documentation site that I have found that provides documentation on the user interface widgets. The documentation should include at a minimum for every XML element:

- Any required nesting (ie: this can only be inside an <xyz> element
- Complete list of attributes that can be used on the element (including OS-specific items)
- Whether attributes are required or optional
- List of acceptable values for each attribute (if applicable)
- List of and links to child elements that can/must be included

Using the ActionBar and ActionItem as an example, there are some examples in the How-To article (https://docs.nativescript.org/ApiReference/ui/action-bar/HOW-TO) and information about the programmatic API it exposes (https://docs.nativescript.org/ApiReference/ui/action-bar/ActionItem), but nowhere is there comprehensive documentation of the XML widget.

Continuing with the ActionItem example, I have the XSD plugged into WebStorm to get a measure of tag/node completion help. Even so, it does not include things like `ios.systemIcon` or even `tap`. I had to find out about those things from examples spread all over various blogs and examples (see attached screenshot). In order for developers to be the most productive (especially when they are just coming to NativeScript), *all* this information needs to be presented in a central, easy to use place.

![nativescript-webstorm](https://cloud.githubusercontent.com/assets/432500/13459392/3d0402a4-e041-11e5-90fc-00b29420438e.png)

**Comment by enchev** [comment]
This issue was moved to NativeScript/docs#255
