### ISSUE TITLE
Documentation of events and properties

### ISSUE THREAD

**Issue by bfattori** [NativeScript/NativeScript#1687]
Right now, the documentation includes a number of `on(event, handler, bind)` descriptions that would indicate that there are specific events, per component. However, they don't say what the event names are... A little digging in the code reveals them, but it would be nice if the documentation included those.

[Page Module](https://docs.nativescript.org/ApiReference/ui/page/Page.html)

Notice the parts that look like:
```
on( event , callback Function..., thisArg? Object )
Raised when navigation to the page has started.
event   <-- Assuming something should be shown here?
callback - Function(args NavigatedData)
thisArg - (optional) - Object
```

Then, I find it almost *impossible* to determine things like `ActionBarModule.ActionItem.visibility`... What is supposed to be set here? Is it `true` or `"true"`, maybe `visible` or `"visible"`? Can you add acceptable values for these fields? This is something that really hinders development when you have to try and try again until it works - guessing isn't very productive.

Great work, btw! I don't want to sound like I'm complaining. I'm just passing it along because I want to see {N} grow!

**Comment by NordlingArt** [comment]
Yes, I feel like some parts of the documentation are completely vague on how things work. I can't complain either though, we're all part of the contributing I think.

**Comment by bfattori** [comment]
I noticed the `enums` package which seems to fill in the gaps of what the values of properties accept. But more docs (or just mentioning the `enums` package) is the right thing to do.

**Comment by N3ll** [comment]
@bfattori -Great point! I think that this is already planned to be fixed. I just wanted to add in case you missed it that there is a repository for the documentation, which might be better for documentation contributions - https://github.com/NativeScript/docs/issues

**Comment by enchev** [comment]
This issue was moved to NativeScript/docs#258
