### ISSUE TITLE
marginLeft vs. translateX?

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#1696]
Performance-wise, which property of those two is the best to use for transitions? The reason why I ask is because when using the translate property, you the view that is out of frame, is non-clickable. However, if I instead use marginLeft, it will stay clickable.

Only tested on iOS.

EDIT: Now I just realized you cannot animate the margin property, so I'm forced to use translate. Is this even fixable?

I'll try be more specific: When using translate to pan something into view (coming from outside the view) makes that area non-clickable.

I do see the logic behind it though. The element that was translated into view is actually still at its "initial position", but appears visually where you set the translate value.

**Comment by hshristov** [comment]
Using `translateX` for animations the recommended approach. `marginLeft` will trigger layout pass which is heavy operation compared to hardware accelerate translate.
If you cannot click the item you could move it to the new location once animation completes (although my understanding is that hit testing should check the applied transformations).
