### ISSUE TITLE
Change the border-bottom color of a focused text-field

### ISSUE THREAD

**Issue by GerjanOnline** [NativeScript/NativeScript#1698]
### Tell us about the problem
Is it possible to change the border-bottom (line) color of a text-field? 

Screenshot:
![image](https://cloud.githubusercontent.com/assets/1153419/13534285/a617b958-e234-11e5-9225-477b31b0a006.png)

I want to change that blue color to green, how can I do this?

I've looked in http://developer.android.com/reference/android/widget/EditText.html and http://developer.android.com/reference/android/widget/TextView.html but can't find it.

I'm trying to access these properties/methods with:
```javascript
email = page.getViewById("email");

var Color = colorModule.Color;
var color = new Color("#19b0a7");

email.android.setTextColor(color.android);
email.android.setHintTextColor(color.android);
email.android.setHighlightColor(color.android);
// which method?

```

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 1.6.2
- Cross-platform modules: 1.6.2
- Runtime(s): 1.6.2

**Comment by bradmartin** [comment]
You can set this by setting the appropriate colors in your colors.xml file in the platform/Android resources. On phone now or I'd send you the snippet and some instructions. I forget if it's the *ns_accent* or *ns_primary dark* color that will be applied on lollipop devices.

**Comment by GerjanOnline** [comment]
Thanks @bradmartin 

It's `ns_accent` in `\platforms\android\src\main\res\values-v21\colors.xml`

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
	<color name="ns_accent">#3d5afe</color>
</resources>
```

But is there a way to do this in `\App_Resources\Android\values\strings.xml` or programmatically? I don't like changing files in de `\platforms\android` folder...

**Comment by mikeres0** [comment]
@GerjanOnline as of this moment in time there's no way to change this programmatically, it's all got to be done via this file: `\platforms\android\src\main\res\values-v21\colors.xml`

**Comment by sivsushruth** [comment]
What about pre lollipop ?

**Comment by sittingbool** [comment]
How to make this work with angular? Or is there any update on how to style this?

**Comment by lukeramsden** [comment]
Is it possible to change other colors (background, border etc) based on whether the text field is open? Like a pseudo selector?

**Comment by dvdbrk** [comment]
I'd like to know the same - can we use :focus or :active somehow in css?
