### ISSUE TITLE
HtmlView causes navigation events to not fire [iOS 8.4]

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#1699]
A very weird issue I came across, that is present on iOS 8.4, but not on iOS 9.2. 

I have a partial-view with the following content:
```xml
<StackLayout loaded="viewLoaded">
    <Image src="~/img/header.png"/>
    <ScrollView>
        <HtmlView html="{{ htmlString }}" />  
    </ScrollView>
</StackLayout>
```
The partial-view is a part of a main-view that consists of a TabView (each tab-item is a partial-view). 

When the app loads, everything looks fine, all views are populated, all seems right. But when I tap buttons, links, listview-items, nothing happens! No navigation or anything. I can only switch between tab-items. If I comment out the ```<HtmlView />```, everything works fine. I also didn't see this on iOS 9.2, only on 8.4. 

When I use the HtmlView in the partial-view I noticed this in the console:
````
myapp[78060]: +[CATransaction synchronize] called within transaction
myapp[78060]: Unbalanced calls to begin/end appearance transitions for <UIViewControllerImpl: 0x7dc58d30>.
```
CLI: 1.6.1
Cross-platform modules: 1.6.2
Runtime(s): ios 1.6.0, android 1.6.3

**Comment by enchev** [comment]
Hey @manijak do you still have the same problem?
