### ISSUE TITLE
HtmlView does not style on Android

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#1700]
On Android when using HtmlView and applying html via binding (or setting it via .js), the view has no styling even if the html content has it. It doesn't even fetch images in the <img src="" /> tag. 
On iOS it works normally, with the style & images applied. 

CLI: 1.6.1
Cross-platform modules: 1.6.2
Runtime(s): ios 1.6.0, android 1.6.3

**Comment by jalal** [comment]
I can confirm that this happens for me too.

**Comment by enchev** [comment]
Hey folks,

There are limitations for Android HtmlView: 
https://github.com/NativeScript/NativeScript/blob/master/ui/html-view/html-view.android.ts#L22
http://developer.android.com/reference/android/text/Html.html#fromHtml%28java.lang.String%29

Maybe if your scenarios is more complex you should use WebView instead.

**Comment by manijak** [comment]
I am just looking for a way to display rich-text content on a page that works cross-platform. Currently I'm receiving the content from a rest-service, part of it returns html. I don't think I can just inject html into a webView, has to be a path/url to a page?

**Comment by enchev** [comment]
WebView can consume both HTML and url/file:
https://github.com/NativeScript/NativeScript/blob/master/apps/tests/ui/web-view/web-view-tests.ts#L107-L148

**Comment by manijak** [comment]
Thanks @enchev, WebView works better than HtmlView. But there are still issues on Android using it:

- Does not apply font-family settings. I am using custom font in the app. Custom font is applied in iOS but not on Android

- Also only on Android; The app becomes VERY slow and laggy when using a view with WebView component! It stops when I navigate away from that view. Every time the WebView is shown, I get following errors in console:
```console
chromium: [ERROR:buffer_manager.cc(313)] [.Parent-Compositor-0xdf25d3f0]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
chromium: [ERROR:buffer_manager.cc(313)] [.Parent-Compositor-0xdf261c90]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
```

CLI: 1.7.0
Cross-platform modules: 1.7.0
Runtime(s): ios 1.6.0, android 1.7.0
