### ISSUE TITLE
Add support for data-* attributes to NativeScript XML

### ISSUE THREAD

**Issue by toddanglin** [NativeScript/NativeScript#1702]
For web developers, the most natural place to embed extra context for a UI element is in a custom data attribute ([spec](https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#embedding-custom-non-visible-data-with-the-data-attributes)). To further ease the transition to NativeScript (and reduce the learning curve), it would be great if NativeScript XML also supported data-* syntax.

**Example:**
_NativeScript XML_
`<label id="myLabel" text="{{ textValue }}" data-guid="{{ guid }}" data-ui-index="0" />`

_NativeScript JavaScript_
```
var myLabel = page.getViewById("myLabel");
...
myLabel.dataset.guid;
myLabel.dataset.uiIndex;
```

**Comment by NathanaelA** [comment]
@toddanglin not direct support for this yet, but this might help you out...
console.log(myLabel['data-guid'], myLabel['data-ui-index']) should print out your values...

**Comment by enchev** [comment]
Hey folks,

I believe that it will be better if we rely on Angular syntax. I'm closing this for now however we if you still believe that this is very important please write back.

**Comment by NathanaelA** [comment]
@enchev  -- What is the syntax for those who prefer to do plain straight NS code?

**Comment by jeremychone** [comment]
@enchev, I would agree with @NathanaelA, some of us like the Nativescript core XML and do not want/need the extra abstraction layer. Any plan to Nativescript XML, or new things get mostly added to the Angular XML side?
