### ISSUE TITLE
Please install Android target 17

### ISSUE THREAD

**Issue by danielb2** [NativeScript/NativeScript#171]
I get this error messages when trying to run  ` tns platform add android`

All I'm doing is following the steps here: http://docs.nativescript.org/hello-world/hello-world-ns-cli.html

However, those instructions mention nothing about targets. What is the correct solution? I ended up installing API 17 which appears to work. 

However, installation instructions here:  http://docs.nativescript.org/setup/ns-cli-setup/ns-setup-os-x.html

Say "Android SDK 19 or later"  ( and 17 is five versions behind )

Does the documentation need mention SDK 17 instead, or am I doing something wrong?

**Comment by teobugslayer** [comment]
Hello @danielb2,

please run

```bash
tns platform add android --log trace > trace.txt
```

and send us the trace.txt file.

There's code in [android project service](https://github.com/NativeScript/nativescript-cli/blob/master/lib/services/android-project-service.ts#L15) which should allow using of API level 19 but something prevents it from working properly.

**Comment by danielb2** [comment]
OK. Will try this. thank you

**Comment by danielb2** [comment]
I'm not sure closing this is a good idea. I didn't reproduce it mainly because I would have to install a bunch of stuff that took time to download and install to get things working. 

I was able to reproduce this problem on two separate computers.

**Comment by danielb2** [comment]
Did anyone at least attempt to reproduce this before closing?

**Comment by Nathanaela** [comment]
Actually, I saw the same issue on my VM creation.   I had to install both Android-17, & 21 -- 17 was required by the NativeScript common code (this repo).   21 If I recall correctly was required by the android-runtime.

**Comment by danielb2** [comment]
@enchev @teobugslayer
