### ISSUE TITLE
Allow debugging of typescript tns module source files 

### ISSUE THREAD

**Issue by blagoev** [NativeScript/NativeScript#1716]
As a TypeScript developer I want/prefer to see only TypeScript source code while debugging my {N} Typescript application. Provide a way to see the Typescript source code while debugging the {N} core modules.

Probably ship the Typescript source files for the {N} core modules as part of the tns-core-modules npm package.

**Comment by NathanaelA** [comment]
Only in _debug_ builds; I don't really want ANY TS code going with my release apps.  ;-D     

 I want my apps to be as small as possible; I don't really want TS adding another 2 megs to my download for no reason.

**Comment by blagoev** [comment]
TS files are filtered on prepare and never go to the app packge. Ts files are not needed in the debug or  in the release app packages. They are client side artifacts. ;)

**Comment by NathanaelA** [comment]
Ah, good.  Had me worried there.  :-)   If they are only on the dev machine, I am totally fine with that.

**Comment by enchev** [comment]
Already implemented
