### ISSUE TITLE
Capture back button

### ISSUE THREAD

**Issue by GerjanOnline** [NativeScript/NativeScript#1719]
### Tell us about the problem
I really would like to capture the Back button event for 2 reasons:

Current bad flow:
1. User starts app and is navigated to the login screen
2. User fills in username, password and presses "Login"
3. App shows an ActivityIndicator during the login process (can take a while)
4. User presses back because it takes too long (or he noticed that he mistyped something)
5. App closes without warning/confirmation => bad UX

Now i would like to do the following:
1. When the ActivityIndicator is active, and the user presses the back button, I want to close the ActivityIndicator and show the login screen again.
2. I would like to give a warning/confimation when a user presses the back button on the login screen, saying that this will close the app.

Is this possible? I have searched for it and saw some GitHub issues but none had concrete solutions.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 1.6.2
- Cross-platform modules: 1.6.2
- Runtime(s): 1.6.2

**Comment by Daxito** [comment]
+1
I would like to have a chance to cancel the event based on some rule.

**Comment by NathanaelA** [comment]
See: http://fluentreports.com/blog/?p=261
This issue can be closed.  :grinning:

**Comment by yuzhang666** [comment]
Can we cancel iOS back event as well in some way?

We have a form on one page, and we want to show an alert window for navigation confirmation, when the user clicks back or swipe left to right, just in case the user loses all the data.

**Comment by jdnichollsc** [comment]
@NathanaelA but what happen with iOS swipe back?

**Comment by NathanaelA** [comment]
This issue was about capturing the Back button on Android, not ios gestures, which my blog article shows how to do.   :grinning:   

If you are needing to capture the back swipe motion that is actually a different issue that should be created (might already exist).    

There is also an issue in the repo #583 (with even a PR #618, that was declined)  that dealt with cancelling the back system between pages.

**Comment by jdnichollsc** [comment]
Thanks @NathanaelA! 👍
