### ISSUE TITLE
Feature Request: Load local html files with <WebView>

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/NativeScript#172]
This came up via Twitter (see https://twitter.com/iamlogiq/status/599713464949612544) and it's something @csell5 needed for our JustMeme app.

Essentially it'd be nice if you could load a local html file with a `<WebView>` element, similarly to how you can load an image locally or via the network with `<Image>`.

Here's how @csell5 implemented the functionality for JustMeme: https://github.com/NativeScript/JustMeme/blob/7c7d704b61d944de43667d84e509e615e5083f01/src/views/releases/releases.js#L17-35

Let me know what you think.

Thanks,
TJ

**Comment by enchev** [comment]
Hey @tjvantoll,

Very good suggestion!

We can make for example *src* property similar to [Image src](https://github.com/NativeScript/NativeScript/blob/master/ui/image/image.d.ts#L36) and you will be able to set both url and HTML content again [similar to Image](https://github.com/NativeScript/NativeScript/blob/master/ui/image/image-common.ts#L18) where you can set url, path to local file or even image-source or image data. You will be able to bind it as well. 

Let me know what you think!

**Comment by tjvantoll** [comment]
Hey @enchev,

Yep that makes sense to me. Consistency is good :)

**Comment by enchev** [comment]
Implemented with #179.
