### ISSUE TITLE
Update observable arrays etc with module.exports

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#1731]
Basically I have a language switcher set up in the /shared folder, which looks kind of like this:

```
var appSettings = require("application-settings");
var observable = require("data/observable").Observable;

var language = new observable({
  strings: require("../shared/languages/" + appSettings.getString("app_language") + ".js")
});

module.exports = {
  strings: language.strings,
  init: function() {
    language.strings = require("../shared/languages/" + appSettings.getString("app_language") + ".js");
  }
};
```

This js file is called through every view with:

`var language = require("../shared/language");`

The idea is that whenever I change language inside the app, it will dynamically update all _bindingContext_ variables that is connected to this language file - instead of me having to restart the app for the change to take effect.

What I've tried is to select the language from a list, which then calls the function **language.init()** (as seen above). Problem is... If I console.dump **language.strings** inside this js file whenever the language has changed from within the app, I can see that the array has been updated to the new language. As intended. However, the **module.exports.strings** will not update even though it is pointing to the language variable that is an observable.

Is there another way to do this or am I just missing something?

**Comment by enchev** [comment]
Hey @NordlingArt,

Can you try to use Observable set method instead:

**Comment by NordlingArt** [comment]
@enchev - The set method does not fix the issue. I've come to realize that application-settings variables do not update until app restart. Is this true?
