### ISSUE TITLE
New ios animation in 1.6 : cannot use Debug-Slow Animation in emulator (question)

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#1733]
Hi, it seems like the new 1.6 animation is different somehow, and it cannot use Debug-Slow Animation in emulator, is this intended ?

Thanks

**Comment by tsonevn** [comment]
Hi @x4080, 
Can you tell us more about the diffrence in animation. It would help if you send us 
sample project to verify the problem with Debug-Slow Animation

**Comment by x4080** [comment]
It was integrated in my projetct but  basically any ios animation now cannot be slowed since 1.6

**Comment by tsonevn** [comment]
Hi @x4080,  
I would like to know, where did you test the project - on a device or simulator?

**Comment by x4080** [comment]
On simulator, there's an option in debug if I'm not wrong. It is not really critical just wondered come native iOS animation cannot be "slowed" by ios for debugging :)

1 possible answer maybe the new animation runs on JavaScript thread like react native ?

**Comment by tsonevn** [comment]
Hi @x4080,
That is right, the IOS simulator has a “Slow animations” debug option, you can toggle  it with Command+T. I've test this option in project from scratch and it is working for us. Try it ones again with Command+T and let me know whether this helps. If you still experience problems please send me an example.
