### ISSUE TITLE
Add text-transform property to Android

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/NativeScript#1734]
_From @donaldking on March 8, 2016 17:23_

Currently, on Android version 6.0+ button titles are all CAPS by default. setting css property:

``` .buttonClass { text-transform: none; }``` does nothing. 
You'd need to override this in code:
``` page.getViewById("buttonId").android.setTransformationMethod(null); ```

It would be more helpful if we could use css text-transform property for this.

Cheers

_Copied from original issue: NativeScript/nativescript-cli#1582_

**Comment by rosen-vladimirov** [comment]
_From @bradmartin on March 9, 2016 18:57_

This should be moved to the NativeScript repo.

Also, a temporary workaround is to set `textWrap` on the `<button>` and this will case your text as defined in the `text` property.

**Comment by rosen-vladimirov** [comment]
_From @bradmartin on March 9, 2016 19:6_

@TelerikAdminTeam - can someone move this to the main repo? So it doesn't get lost.

**Comment by enchev** [comment]
Hey folks,

We treat `text-transform: none` as default value similar to [CSS specification](http://www.w3schools.com/cssref/pr_text_text-transform.asp).

**Comment by bradmartin** [comment]
Oh yea @enchev - I guess I should have confirmed the reports of the issue first. The `text-transform` works fine on all android buttons for me. :+1:
