### ISSUE TITLE
Bad arguments passed to void org.nativescript.widgets.DockLayout.setStretchLastChild(boolean)

### ISSUE THREAD

**Issue by stavro** [NativeScript/NativeScript#1735]
First deployment of the sample app (https://github.com/NativeScript/sample-ng-todomvc) on my Nexus 6, Android 6.0.1 resulted in the following error:

```
bad arguments passed to void org.nativescript.widgets.DockLayout.setStretchLastChild(boolean) 
```

https://gist.github.com/stavro/ac1b46212846bd429192

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: `1.6.2`
- Cross-platform modules: `1.7.0-angular-0`
- Runtime(s): `tns-android`

**Comment by hdeshev** [comment]
Thanks for your report @stavro. It turned out to be a problem in the Angular renderer's `setProperty` implementation. I fixed it in master, and it should go live some time next week.
