### ISSUE TITLE
TypeError from fetch module due to no headers received

### ISSUE THREAD

**Issue by wubzz** [NativeScript/NativeScript#1737]
This is part bug report, and part question.

**Bug report**
I don't know if you would classify this as a bug, but when a request done via the `fetch` module returns no headers, it will throw an error here:

https://github.com/NativeScript/NativeScript/blob/master/xhr/xhr.ts#L119

Due to the returnvalue here:
https://github.com/NativeScript/NativeScript/blob/master/xhr/xhr.ts#L184
*(toLowerCase on null)*

Which eventually calls the `xhr.onerror` handler which is set to always throw:

```javascript
reject(new TypeError('Network request failed'))
```

Headers should be set, but when they're not, this is what happens. Which leads me to my question...

**Question**
I'm completely stumped by this and am by no means implying that this is caused by the fetch/xhr modules, but I'm completely lost on where to look right now. When my remote API endpoint returns with a `401 - Unathorized`, the xhr response does not pick up any response headers. If I return a 403 instead, response headers are present.

I've verified that it's not the API server doing something wrong, because the response headers are picked up by numerous other Clients such as Postman, Webbrowser, etc, when I return a `401`. Any ideas?

Running all this on Android.

```javascript

JS: Response {
JS:   "content": {
JS:    .......
JS:   },
JS:   "statusCode": 401,
JS:   "headers": {}
JS: }
```

````javascript

JS: Response {
JS:   "content": {
JS:    .......
JS:   },
JS:   "statusCode": 403,
JS:   "headers": {
JS:     "Date": "Thu, 10 Mar 2016 14:32:10 GMT",
JS:     "Content-Type": "application/json; charset=utf-8",
JS:     "Content-Length": "286",
JS:     "Keep-Alive": "timeout=15, max=100",
JS:     "Connection": "Keep-Alive",
JS:     "X-Android-Sent-Millis": "1457620330281",
JS:     "X-Android-Received-Millis": "1457620330364"
JS:   }
JS: }
```

**Comment by enchev** [comment]
Hey @wubzz,

The null ref exception was fixed immediately (check my pull request) and here is an example how to get the headers:

```JavaScript
    fetch("http://httpbin.org/status/401").then(function(r){
        console.log("STATUS: " + r.status);

        r.headers.forEach(function(key, value){
            console.log(key + ":" + value);
        });

        return r.text();
    }, function(e){
        console.log("ERROR: " + e)
    }).then(function(r){
        console.log("CONTENT: " + r)
    });
```

**Comment by wubzz** [comment]
@enchev Thanks!

Debugging this on my own by logging the output of the `xhr` module, I still find no explanation why the headers object was empty to begin with. It makes no sense at all. Even here:
https://github.com/NativeScript/NativeScript/blob/master/xhr/xhr.ts#L85
There are no headers set in the response. I got stuck after that and couldn't dig deeper (*http.request(..)*), so I'll just add this info here in case someone else has any idea.

**Comment by enchev** [comment]
Hey @wubzz,

After I've fixed the exception I was able to get headers using `http://httpbin.org/status/401` url from the echo service we use for testing.

**Comment by bismert** [comment]
I'm getting similar error when trying to make post request with fetch module
CLI error prints 
TypeError: Network request failed: unexpected expected token < in JSON at position 3
