### ISSUE TITLE
A very strange bug: when navigated another page, previous page content is still clickable

### ISSUE THREAD

**Issue by erkanarslan** [NativeScript/NativeScript#1741]
Entry point of my application is a login page that consists of two TextFields and one Button. After user login, app navigates to dashboard and dashboard content is shown. Login and dashboard pages are two different pages. However, I can still click the login button even though it is not in the dashboard page. I click an empty space in dashboard where the login button is placed in login page and it re-logins. Also, the TextFields are still selectable. I don't see them but I can click on them and select the text inside TextFields.

I couldn't find this problem on the internet. This problem exists on Android. I cannot test it in iOS, maybe same problem exists there too.

- CLI: 1.6.1
- Cross-platform modules: 1.6.2
- Runtime(s):"tns-android" : "1.6.3"

**Comment by Daxito** [comment]
I had this issue as well, and it is related to issue #1569, why? No idea but it also affects.

**Comment by NickIliev** [comment]
@erkanarslan , @Daxito 
Are you still reproducing this issue!?

**Comment by Daxito** [comment]
@NickIliev
This issue was fixed a while ago, probably by #1569
