### ISSUE TITLE
Modules support for older devices.

### ISSUE THREAD

**Issue by Plamen5kov** [NativeScript/NativeScript#1742]
Android Runtime is now compatible with Android API Level 10.
The next step is to be able to use the {N} modules with older devices.
Related: 
https://github.com/NativeScript/android-runtime/issues/198
https://github.com/NativeScript/android-runtime/issues/357

**Comment by vbresults** [comment]
@Plamen5kov Why was this closed?  It's not tagged or anything

**Comment by Plamen5kov** [comment]
@vbresults  I've mentioned the reason in the description. This issue was a duplicate.

**Comment by vbresults** [comment]
@Plamen5kov Ah I see
