### ISSUE TITLE
Hardware back button does not work as expected

### ISSUE THREAD

**Issue by erkanarslan** [NativeScript/NativeScript#1743]
In my app, login page is the entry point. User is navigated to dashboard after login. After that, if user navigates to another page (let say page B) and presses the back button of the device, he still sees the page B. If he presses the back button again, the dashboard page is shown for less than half a second. Then, he sees an empty page. At this point probably the user is on dashboard page but cannot see anything.

Problem occurs on Android. I don't know if it happens also in iOS.

- CLI: 1.6.1
- Cross-platform modules: 1.6.2
- Runtime(s): android : 1.6.3

**Comment by Daxito** [comment]
Also #1569 related issue :s

**Comment by enchev** [comment]
Hey @erkanarslan @Daxito do you still have the same problem?

**Comment by Daxito** [comment]
@enchev No issue anymore, it was fixed a while ago for me.
