### ISSUE TITLE
Keyboard hides when try to move from to next input field

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/NativeScript#1745]
### Tell us about the problem
Keyboard hides when user try to move from one input field to next one with "next" button on the keyboard. 

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
Found in {N} 1.7.0 RC, but also valid in {N} 1.6.0.

### Please tell us how to recreate the issue in as much detail as possible.
Get Xpencity or Friends sample apps and try to login with some user.
Enter name, hit next => keyboard is hidden.

**Comment by dtopuzov** [comment]
Related to https://github.com/NativeScript/sample-Friends/issues/23

**Comment by enchev** [comment]
Hey @dtopuzov what's the status of this?
