### ISSUE TITLE
Support smoother page transitions on Android (part of Material design)

### ISSUE THREAD

**Issue by GerjanOnline** [NativeScript/NativeScript#1748]
### Tell us about the problem

I really want to use the smoother page transitions (which was introduced with material design) but this does not work OOTB (I also can not get it to work manually but that's another problem)

The thing i really don't like is that when a page transition starts (so A => B), the underlying page (A) is becoming white (or is removed) which gives a poor effect imo (best noticable with a `slideLeft` transition). It would be nicer if they overlap together (hopefully this is the `windowAllowEnterTransitionOverlap` setting). 

What you need to do for this (according to me): put the following style in your `values-v21` folder

``` xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
<style name="AppTheme" parent="AppTheme.Base">
    <item name="android:windowContentTransitions">true</item>
    <item name="android:windowAllowEnterTransitionOverlap">true</item>
    <item name="android:windowAllowReturnTransitionOverlap">true</item>
</style>
</resources>
```

Can you guys make this work (so include it by default)?
### Which platform(s) does your issue occur on?

Android
### Please provide the following version numbers that your issue occurs with:
- CLI: 1.6.2
- Cross-platform modules: 1.6.2
- Runtime(s): tns-android 1.6.2
### Links

More info about this:
- http://antonioleiva.com/material-design-everywhere/
- http://developer.android.com/reference/android/view/Window.html#attr_android:windowAllowEnterTransitionOverlap
- http://willowtreeapps.com/blog/material-world-animating-l-shared-view-activity-animations/
- https://github.com/saulmm/Android-L-Preview-Concepts#activity-transitions
- http://tips.androidhive.info/2015/09/android-how-to-apply-material-design-theme/

**Comment by sitefinitysteve** [comment]
:+1:

**Comment by valentinstoychev** [comment]
@myninka can you please comment.

**Comment by hamorphis** [comment]
We have the overlap turned on. Check this out:

https://github.com/NativeScript/NativeScript/blob/master/ui/transition/transition.android.ts

```
newFragment.setAllowEnterTransitionOverlap(true);
        newFragment.setAllowReturnTransitionOverlap(true);
        if (currentFragment) {
            currentFragment.setAllowEnterTransitionOverlap(true);
            currentFragment.setAllowReturnTransitionOverlap(true);
        }
```

**Comment by hamorphis** [comment]
I will investigate this.

**Comment by dianikol** [comment]
It happened to me as well but with IOS too?  This is noticeable when i use the fade effect with 0 duration

So what is the actual workaround to this?

**Comment by MadhuSudhanBhaskar** [comment]
@hamorphis @enchev 
Hi can we expect this custom transitions also?

https://github.com/lgvalle/Material-Animations/

**Comment by hamorphis** [comment]
@MadhuSudhanBhaskar https://docs.nativescript.org/core-concepts/navigation#navigation-transitions

**Comment by MadhuSudhanBhaskar** [comment]
@hamorphis  I was looking for more of like this
https://github.com/lgvalle/Material-Animations/#2-shared-elements-between-activities
NS does support some transitions is what I know, I was looking for more like from the link here.

**Comment by hamorphis** [comment]
@MadhuSudhanBhaskar Currently we only support navigation transitions between pages (i.e. android fragments).

**Comment by MadhuSudhanBhaskar** [comment]
@hamorphis  Since its fragments 
http://www.androidauthority.com/using-shared-element-transitions-activities-fragments-631996/

Is it still something that we can achieve "Shared Elements with Fragments"  the above article says yes.

**Comment by hamorphis** [comment]
@MadhuSudhanBhaskar Unfortunately, we don't have shared element transitions implemented in NativeScript yet. This is why this issue exists.

**Comment by MadhuSudhanBhaskar** [comment]
@hamorphis So do we get to see it, some where in near future in that case?

**Comment by hamorphis** [comment]
@MadhuSudhanBhaskar I am not sure. It is quite complex feature to be honest.

**Comment by dianjuar** [comment]
The issue could not break apart? Maybe will be a start implementing just more page transitions for the moment.

**Comment by tsonevn** [comment]
Hi all,
I found that [another issue](https://github.com/NativeScript/NativeScript/issues/4464) with the similar problem is opened, which also is associated with PR.
I am closing this issue in favor of the another one, however, if you still thinking that the both issues described different problem, fill free to contact me and I will reopen it
