### ISSUE TITLE
Nativescript customer adoption

### ISSUE THREAD

**Issue by svc76** [NativeScript/NativeScript#1749]
Hey guys, not sure if this is a valid question to this forum. But i don't know where else to post this. Can someone tell me, what is the real customer adoption rate for NativeScript. Is there an app built using NativeScript, that's live on the market?

Appreciate taking time to look at this and respond.

Thx

**Comment by enchev** [comment]
Hey @svc76,

Please check this thread in our Google group:
https://groups.google.com/forum/#!topic/nativescript/L5ju0pl_se0

**Comment by svc76** [comment]
Thank you so much for prompt reply enchev. That's one more thing i like about this forum.
