### ISSUE TITLE
Laggy reversed page transition on Android

### ISSUE THREAD

**Issue by GerjanOnline** [NativeScript/NativeScript#1750]
### Tell us about the problem
On Android I am seeing a reproducible lag during the "reversed slide page transition" (so when you press the back button) 
Please see my gif:

![animation](https://cloud.githubusercontent.com/assets/1153419/13716874/04410f58-e7de-11e5-9ef3-85ba5f5f3dbd.gif)

Maybe it's not very clear (sorry for that) but when you look carefully you can see that at the end of the reversed animation there is a notable lag. Actually on my device _it's a lot worser_ than in this gif because of its framerate.

It's remarkable (or just not) that the lag is very good reproducible because it happens all the time and it's always around the same location/time.

For this issue I stripped a lot of code to make sure it is not an event handler or something. It also _seems_ that the lag in this demo app happens _later_ than in my real world app, so more near the end of the transition.

It really looks that there is something going on under the hood at that specific time.

### Which platform(s) does your issue occur on?
Android

I've tested this on:
- Genymotion emulator (nexus 6p)
- Genymotion emulator (samsung s6)
- Nexus 6P
- Galaxy A5 2016

### Please provide the following version numbers that your issue occurs with:
- CLI: 1.6.2
- Cross-platform modules: 1.6.2
- Runtime(s): 1.6.2

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

`login.xml`
```xml
<page xmlns="http://schemas.nativescript.org/tns.xsd">
  <page.actionBar>
    <action-bar title="Sign in" />
  </page.actionBar>
  <grid-layout rows="*, auto">
    <scroll-view row="0">
      <stack-layout >
        <grid-layout id="layout" row="0" rows="auto, auto" margin="0,30">
          <text-field marginTop="30" id="email" hint="Email Address" keyboardType="email"
            returnKeyType="next" returnPress="focusPassword" autocorrect="false" autocapitalizationType="none" row="0" />
          <text-field id="password" secure="true" hint="Password" returnKeyType="done" returnPress="signIn" row="1" />
        </grid-layout>
      </stack-layout>
    </scroll-view>
    <grid-layout row="1" rows="auto, auto, auto" margin="0,30" marginBottom="10">
      <button row="0" text="Sign in" id="sign-in-button" tap="signIn" class="mainbutton" />
      <button row="1" text="Sign up" id="sign-up-button" tap="register" margin="0" class="link" />
      <button row="2" text="Forgot password?" id="forgot-password-button" tap="forgotPassword" margin="0" class="link" />
    </grid-layout>
  </grid-layout>
</page>
```

`login.js`
```js
var frameModule = require("ui/frame");

exports.signIn = function() {
    frameModule.topmost().navigate({
        moduleName: "views/list/list",
        animated: true,
        transition: { name: "slide" }
    });
};

exports.register = function(args) {
    frameModule.topmost().navigate({
        moduleName: "views/register/register",
        animated: true,
        transition: { name: "slide" }
    });
}

exports.forgotPassword = function(args) {
    frameModule.topmost().navigate({
        moduleName: "views/password/password",
        animated: true,
        transition: { name: "slide" }
    });
}
```

`register.xml`
```xml
<page loaded="loaded" xmlns="http://schemas.nativescript.org/tns.xsd">
  <page.actionBar>
    <action-bar title="Reset Password" />
  </page.actionBar>
  <grid-layout rows="*, auto" style.backgroundColor="blue">
    <label text="password lost" />
  </grid-layout>
</page>
```

`register.js`
Nothing

`password.xml`
```xml
<page loaded="loaded" xmlns="http://schemas.nativescript.org/tns.xsd">
  <page.actionBar>
    <action-bar title="Reset Password" />
  </page.actionBar>
  <grid-layout rows="*, auto" style.backgroundColor="red">
    <label text="password lost" />
  </grid-layout>
</page>
```

`password.js`
Nothing

**Comment by GerjanOnline** [comment]
Maybe this issue can be combined with https://github.com/NativeScript/NativeScript/issues/1748

**Comment by tsonevn** [comment]
Hi @GerjanOnline, 
I've just tested given code in sample app. Actually I didn't see any lag in 
reverse page transition. The reason for that is not so smoothly transition through the pages.
I also think that this issue is related to #1748.
