### ISSUE TITLE
Android performance using gpu profiling 

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#1751]
Hi, when i was debugging performance on my device, i found something interesting, after touch up, the javascript thread is like "sleep" and woke up after touch down 

To replicate : 
1 app with listview with data
2 enable gpu profiling
3 scroll up and down just a little bit, the graph will eventually be low or 60fps
4 touch up
5 start no 3, the frame will drop significantly and goes up to 60 fps

And it even noticeable when starting app @first time

Thanks

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#380

**Comment by x4080** [comment]
Hi again, please take a look at this https://github.com/NativeScript/NativeScript/issues/1753

This is why I did the digging with the GPU profiling

**Comment by x4080** [comment]
And without any grid layout, when opening app, no lag happened at all

**Comment by enchev** [comment]
Hey @x4080,

We've made various performance optimizations recently and we are about to release our v2.2. Please check your
