### ISSUE TITLE
Support letter-spacing in CSS

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/NativeScript#1757]
Low priority, but I would like {N} to support the `letter-spacing` CSS property. At the moment I’m manually calling `setLetterSpacing()` on Android, and trying (and failing) to use this technique for iOS http://stackoverflow.com/questions/20580736/how-to-increase-the-character-spacing-in-uilabel.

And, just as an idea, this might be a good first issue for someone looking to contribute to {N}.

**Comment by tjvantoll** [comment]
Just fyi this is how I’m currently accomplishing this in Groceries: https://github.com/NativeScript/sample-Groceries/blob/be06c99c138ff0c214576ff71066be985955c967/app/views/login/login.js#L54-L68

**Comment by lawrencetaur** [comment]
Line-height would be a great addition as well. refer: #1664

**Comment by sitefinitysteve** [comment]
I would argue not low priority as these seemingly "fluffy" features all go towards making nice looking apps, and in this case groceries is a showcase app so it would go towards reducing the code complexity for a new user looking at it.

**Comment by vchimev** [comment]
There is an issue with the Label, TextField and TextView elements on iOS that *text-transform* does not apply when *letter-spacing* is set. For example:
```xml
<Label text="labelLabel" style="text-transform: uppercase; letter-spacing: 10;" />
<TextField text="textField" style="text-transform: uppercase; letter-spacing: 10;" />
<TextView text="textView" style="text-transform: uppercase; letter-spacing: 10;" />
```
It works as expected for Button.

**Comment by vchimev** [comment]
The letter-spacing property for Android is supported on API levels >= 21.

**Comment by hamorphis** [comment]
**Have in mind that letter spacing should be specified in EM units, not pixels!**

https://github.com/NativeScript/NativeScript/issues/2528

**Comment by priyangamani** [comment]
letter-spacing in CSS not supported ios..
