### ISSUE TITLE
Status bar text colour on iOS unable to be changed in 1.6

### ISSUE THREAD

**Issue by maknz** [NativeScript/NativeScript#1759]
In 1.5, we were able to set the following in our Info.plist file (committed in platforms/ios) to change the colour of the text of the status bar to white:

```
	<key>UIStatusBarStyle</key>
	<string>UIStatusBarStyleLightContent</string>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
```

This no longer seems to work in 1.6. I've verified the settings are making their way from our plist file in App_Resources/iOS into the Xcode project's one.

<img width="562" alt="screen shot 2016-03-15 at 1 45 11 pm" src="https://cloud.githubusercontent.com/assets/992356/13764446/38a2acd8-eab4-11e5-91a9-243b597bb5a1.png">

but alas the colour remains black.

![screen shot 2016-03-15 at 1 47 02 pm](https://cloud.githubusercontent.com/assets/992356/13764567/98bb7f68-eab5-11e5-8126-d52ecf925222.png)

- CLI: 1.6.2
- Cross-platform modules: 1.6.2
- Runtime(s): iOS 1.6.0, Android 1.6.3

**Comment by tsonevn** [comment]
Hi @maknz,
I reviewed your problem. The status bar style can be changed by changing the value of navigationBar.barStyle.
I give you an example code, how you can do this.
`if(page.ios){
        var controller = frameModule.topmost().ios.controller;
        var navigationBar = controller.navigationBar;
        navigationBar.barStyle=1;
  }`
You can also review the artical bellow:
http://developer.telerik.com/featured/customizing-ios-navigation-bar-status-bar-nativescript/
I hope this information would be useful. I will be glad to assist you further.*/
     if(page.ios){
        var controller = frameModule.topmost().ios.controller;
        var navigationBar = controller.navigationBar;
        navigationBar.barStyle=1;
     }

**Comment by maknz** [comment]
Hey, yeah we've been able to change the colour of it using that method (although via the appearance proxy, same effect). The only problem with that method is it doesn't kick in until the app has booted, so the status bar will have black text while the launch images are showing.

**Comment by tsonevn** [comment]
Hi @maknz,

Could you give us some code snippets or sample project to reproduce the issue?

**Comment by maknz** [comment]
Gah, okay, this was an issue introduced by some dodgy launch screens. After removing our launch screens and reinstating the defaults that the app template has, the above settings work and successfully make the text white.
