### ISSUE TITLE
Default design/theme for the cross-platform UI. A-la Bootstrap?

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#1763]
Lets think of creating a default design experience (maybe based on the Kendo Nova theme) with a set of CSS definitions that will give a default beautiful UX experience.

We can also think about bootstrap-like experience.

- [x] define design (@myninka)
- [x] define and implement CSS classes structure and impl.

**Comment by myninka** [comment]
It has to be super easy to apply the theme and to remove it for the pure native UI for different platforms.

**Comment by dragGH102** [comment]
+1

**Comment by valentinstoychev** [comment]
Hey @myninka do you want to share the designs here, so we can get a feedback from the community?

**Comment by leocaseiro** [comment]
This might help someone https://www.thepolyglotdeveloper.com/2016/07/give-nativescript-mobile-app-ionic-framework-theme/?utm_source=mobilewebweekly&utm_medium=email

**Comment by enchev** [comment]
Please report theme related issues here:
https://github.com/NativeScript/theme/issues
