### ISSUE TITLE
Cannot run your app in the native emulator.

### ISSUE THREAD

**Issue by mabelanski** [NativeScript/NativeScript#1765]
Hi

I have a problem with run emulator cmd :

C:\...NS>tns run android --emulator
Project successfully prepared

:config phase:  createDefaultIncludeFiles

:config phase:  createPluginsConfigFile

:config phase:  pluginExtend
        +applying configuration from: C:\..NS\pla
tforms\android\configurations\include.gradle

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
        +adding dependency: C:..NS\platforms\and
roid\libs\aar\widgets-release.aar
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:prepareComAndroidSupportAppcompatV72221Library UP-TO-DATE
:prepareComAndroidSupportSupportV42221Library UP-TO-DATE
:prepareWidgetsReleaseLibrary UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:cleanLocalAarFiles
:deleteJavaDir UP-TO-DATE
:ensureMetadataOutDir UP-TO-DATE
:collectAllJars
:isMetadataGenerationNecessary UP-TO-DATE
:buildMetadata UP-TO-DATE
:copyMetadata UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:compileDebugJavaWithJavac UP-TO-DATE
:compileDebugNdk UP-TO-DATE
:compileDebugSources UP-TO-DATE
:transformClassesWithDexForDebug UP-TO-DATE
:mergeDebugJniLibFolders UP-TO-DATE
:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:processDebugJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:validateDebugSigning
:packageDebug UP-TO-DATE
:zipalignDebug UP-TO-DATE
:assembleDebug UP-TO-DATE
:deleteExplodedAarFolder UP-TO-DATE
:buildapk UP-TO-DATE

BUILD SUCCESSFUL

Total time: 8.16 secs
Project successfully built.
Using  C:\...NS\platforms\android\build\outputs\ap
k\liveAppNS-debug.apk
Starting Android emulator with image Nexus_5_API_23_x86
Cannot run your app in the native emulator. Increase the timeout of the operatio
n with the --timeout option or try to restart your adb server with 'adb kill-ser
ver' command. Alternatively, run the Android Virtual Device manager and increase
 the allocated RAM for the virtual device.

tns doctor is ok 

Thanks

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#1609
