### ISSUE TITLE
Add Android bottom navigation to the core modules

### ISSUE THREAD

**Issue by myninka** [NativeScript/NativeScript#1766]
New in Material design guidelines:
https://www.google.com/design/spec/components/bottom-navigation.html

This is the direct alternative of the iOS tabbar with few differences.

**Comment by pap5508** [comment]
any alternate for bottom navigation for android devices. ?

**Comment by kazemihabib** [comment]
@pap5508 there is a plugin https://github.com/bradmartin/nativescript-bottomnavigation

**Comment by pap5508** [comment]
@kazemihabib thank you.. but I am looking for with Angular2

**Comment by NickIliev** [comment]
There is now a `BottomNavigaiton` and `Tabs` components (with NativeScript 6.x.x)
