### ISSUE TITLE
Radio Group using switch elements (event.preventDeafault())

### ISSUE THREAD

**Issue by nikolal** [NativeScript/NativeScript#1769]
I am trying to implement radio-group functionality using switch elements.

**JavaScript**

```
function loaded(args) {
  var page = args.object;

    var mySwitch1 = view.getViewById(page, "myId1"),
        mySwitch2 = view.getViewById(page, "myId2");

    function switchHandler(switch1, switch2){
        switch1.checked = true;
        switch2.checked = false;
    }

    mySwitch1.on("tap", function () {
          switchHandler(mySwitch1, mySwitch2);
    });
    mySwitch2.on("tap", function () {
          switchHandler(mySwitch2, mySwitch1);
    });
}
exports.loaded = loaded;
```

mySwitch1 has checked=true assigned in XML file so it is ON when I run the page.
The problem is:
If I tap on mySwitch1, it will turn OFF even though I am setting checked=true (I want to keep it on).

Is there any way to remove default behaviour of a switch element, something like event.preventDefault()???

The weird part is:
If I change the switchHandlercode:

```
 function switchHandler(switch1, switch2){
      switch1.checked = false;
      switch2.checked = false;
 }
```

Now the mySwitch1 stays on, even though I am assigning checked='false.
You are probably wondering why I just don't use this code, but the problem is that I need to use checked property for some other functionality.

My workaround is to assign correct value with** setTimeout** function. This way my switch stays on visually and I am getting the correct value after 300 ms.
There must be better way.

```
 function switchHandler(switch1, switch2){
    switch1.checked = false;
    switch2.checked = false;
    setTimeout(function(){ 
        switch1.checked = true;
    }, 300);
 }
```

**Comment by enchev** [comment]
Hey @nikolal,

Maybe the easiest way to achieve your goal will be to use binding expressions. For example:
```XML
<Page loaded="loaded">
  <StackLayout>
    <Switch id="Switch1" checked="{{ selected === 'Switch1' }}" tap="{{ tap }}" />
    <Switch id="Switch2" checked="{{ selected === 'Switch2' }}" tap="{{ tap }}" />
    <Switch id="Switch3" checked="{{ selected === 'Switch3' }}" tap="{{ tap }}" />
  </StackLayout>
</Page>
```

```JavaScript
var Observable = require("data/observable").Observable;

exports.loaded = function(args) {
    var obj = new Observable();
    obj.set("selected", "Switch1");
    obj.set("tap", function(args){
    setTimeout(function() {
            obj.set("selected", args.object.id);
        }, 100);
    });

    args.object.bindingContext = obj;
}
```

![radio](https://cloud.githubusercontent.com/assets/5804953/13873472/57f3aea0-ecfa-11e5-8c8a-281f776245e1.gif)
