### ISSUE TITLE
NavigationButton has no animate function

### ISSUE THREAD

**Issue by GerjanOnline** [NativeScript/NativeScript#1781]
### Tell us about the problem

I really would like to animate the NavigationButton but it seems this it not possible. All other elements have a `animate` function except `NavigationButton`

``` js
console.log("NavigationButton.animate: " + page.actionBar.navigationButton.animate); // gives undefined
```

I also tried it with:

``` js
  var animations = [
      { target: page.actionBar.navigationButton, opacity: 0, duration: 400, delay: 0 }
  ];

  var a = new animationModule.Animation(animations);
  a.play(); // will result in exception : TypeError: Cannot read property 'getAlpha' of undefined
```
### Which platform(s) does your issue occur on?

Android but probably also iOS
### Please provide the following version numbers that your issue occurs with:

1.7

**Comment by NickIliev** [comment]
Behind the navigation button on iOS stands native navigation button which comes with limited possibilities for animating. That said, the feature can't be implemented without breaking the design guidelines so I am closing this one.
