### ISSUE TITLE
ActionItem font is not displaying

### ISSUE THREAD

**Issue by triniwiz** [NativeScript/NativeScript#1783]
Since i noticed this https://github.com/NativeScript/NativeScript/issues/1267 i wanted to try it out
```xml
<ActionBar.actionItems>

				<!-- Chats -->
				<ActionItem class="material-icon" tap="addChat" text="&#xE0B7;" visibility="{{ selectedIndex,selectedIndex === 0 ? 'visible' : 'collapsed' }}" />
				<ActionItem class="material-icon" tap="searchChat" text="&#xE8B6;" visibility="{{ selectedIndex,selectedIndex === 0 ? 'visible' : 'collapsed' }}" />

				<!-- Contacts -->
				<ActionItem class="material-icon" tap="addContact" text="&#xE7FE;" visibility="{{ selectedIndex,selectedIndex === 1 ? 'visible' : 'collapsed' }}" />
				<ActionItem class="material-icon" tap="searchContact" text="&#xE8B6;" visibility="{{ selectedIndex,selectedIndex === 1 ? 'visible' : 'collapsed' }}" />


			</ActionBar.actionItems>
```

![actionitem](https://cloud.githubusercontent.com/assets/6695919/13835926/db8979f8-ebd2-11e5-8b04-c049bb93a0f2.png)

This appears on Android

CLI: 1.7.0
Cross-platform modules: 1.7.0
Runtime(s): 1.7.0

**Comment by NordlingArt** [comment]
It's the same on iOS. Currently we're not able to change font family on actionItems.

**Comment by tsonevn** [comment]
Hi @triniwiz, 
Unfortunately font-family is still not supported for ActionItem. Temporary solution can be found here #1166.
I hope this information helps.

**Comment by firescript** [comment]
Check my reply here:

https://github.com/NativeScript/NativeScript/issues/1166#issuecomment-198511286
