### ISSUE TITLE
tns-core-modules 1.7.0 in OnCreate not found Dex Class Loader?

### ISSUE THREAD

**Issue by katturajam** [NativeScript/NativeScript#1785]
Hi Team,
    We have imported around 16 plugins in our project. i tried in 1.7.0 . I have added two line in build.gradle. 

Its working in 1.6.2 but in 1.7.0 OnCreate function not found raised during runtime.

```
android {
	defaultConfig {
		//Multi Dex enable
		multiDexEnabled true
	}
}
dependencies {
           //added multi dex library
           compile 'com.android.support:multidex:1.0.1'
}
```
I found this link https://github.com/NativeScript/nativescript-cli/issues/1542  but there is no clarity where i can write onCreate in NativeScript Project.

Currently I am using Nativescritp Cli app structure in Netbeans IDE.

Let me know where i want to write onCreate function in NativeSript project using JS/TS.

[onCreate_Failed.txt](https://github.com/NativeScript/NativeScript/files/177570/onCreate_Failed.txt)

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#391
