### ISSUE TITLE
Binding problems with Repeater

### ISSUE THREAD

**Issue by humbss** [NativeScript/NativeScript#1790]
Hi, I'm using Repeater and a binding to a view model and it is working properly to invoke my view-model functions, the problem is that even able to invoke the functions variables are undefined. for example:

on my XML view I created the repeater below:

```
 <!--Breadcrumb -->
 <Repeater items="{{ bc }}">
            <Repeater.itemTemplate>
              <Label id="{{ id }}" tap="{{ $parents['Repeater'].loadparent }}" text="{{ name }}" /> 
            </Repeater.itemTemplate>
</Repeater>
```

in my view model I have 

nodes = new observableArrayModule.ObservableArray();

and the function _loadparent_ that simple executes pushes on my array _nodes_

`this.nodes.push(some_object);`

I tried to invoke the function outside the repeater without the $parents reference and it worked properly but when invokes inside repeter I get:

TypeError: Cannot read property 'push' of undefined

seems that everything on the view-model scope are not visible when called from my repeater via $parents. Is it ok? Could you guys help me?

Thank you

my package:

```
cat package.json 
{
	"nativescript": {
		"id": "xxxxxxxxxx",
		"tns-android": {
			"version": "1.6.3"
		}
	},
	"dependencies": {
		"nativescript-drop-down": "^1.2.3",
		"nativescript-floatingactionbutton": "^2.1.3",
		"nativescript-grid-view": "^1.3.2",
		"nativescript-telerik-ui": "^0.2.4",
		"tns-core-modules": "1.6.2"
	},
	"devDependencies": {
		"nativescript-dev-typescript": "^0.3.0",
		"typescript": "^1.8.7"
	}

```

**Comment by humbss** [comment]
I realized thru debug that the "this" reference was not pointing to the viewmodel but to the element that executed "tap" inside the repeater. So instead of this.myvariable I used myviewmodelinstance.myvariable and now I'm able to use them.

**Comment by ralphpig** [comment]
@humbss Do you know if "this" referencing the tapped elements context is the intended functionality?

**Comment by kritollm** [comment]
Had exactly the same problem, came to the same conclusion. It must be like that, context is this in view model methods. Then one may wonder why not just skip the class hysteria and make regular Object Literals and extend with a base object using Object.assign.
