### ISSUE TITLE
Cannot find module 'config-chain'

### ISSUE THREAD

**Issue by mehfuzh** [NativeScript/NativeScript#1798]
Upgrading from NativeScript 1.6.1 to 1.7.0 gives the following exception:

<img width="657" alt="unknown" src="https://cloud.githubusercontent.com/assets/141204/13884499/8477a684-eceb-11e5-91d6-7c937312305a.png">

Uninstalling and then reinstalling the nativescript modules solves it. 

```
npm  uninstall -g nativescript
npm install -g nativescript

```

**Comment by toddanglin** [comment]
I have hit this `config-chain` error upgrading from earlier versions of NativeScript, too. Uninstalling and reinstalling the nativescript npm package solved the problem in those cases, too.

This was also on a Mac. Haven't tried the upgrade on Windows.

FWIW, it seems this error is affecting other projects on upgrade. See these Ionic threads:
- https://forum.ionicframework.com/t/cannot-find-module-config-chain/37130/11
- https://github.com/driftyco/ionic-cli/issues/656

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#1630
