### ISSUE TITLE
`tns run android --emulator` not support android 5.0 AVD

### ISSUE THREAD

**Issue by Huntter** [NativeScript/NativeScript#18]
`tns run android --emulator` not support android 5.0 AVD
Get information
> Could not find an emulator image to run your project.

**Comment by teobugslayer** [comment]
Hello, could you please check that in Android SDK Manager you have installed one of "ARM EABI v7a System Image" or "Intel x86" images? We have a limitation in the beta that we are not supporting Google APIs images. Of course, pull requests adding the missing functionality are most welcome! You can look around https://github.com/telerik/mobile-cli-lib/blob/master/mobile/android/android-emulator-services.ts

**Comment by Huntter** [comment]
Yes, it works. thanks.
