### ISSUE TITLE
ListView with images crashes app when scrolling [Android]

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#1801]
I have a ListView with around 15 items (Images) loaded from service. When scrolling the list up & down several times (like 4-5 times moderate speed), the app can freeze and crash without any error in the console. This happens both in Genymotion and on real device. 

While testing I also noticed like the images were being loaded every time you scroll to them. Every time I scroll away from a row, and back again, it re-appears. 

All images are around 50kb and 540x340 in size. 
I also have a list with smaller images and the same thing happens. On iOS no issue. 

CLI: 1.7.0
Cross-platform modules: 1.7.0
Runtime(s): Android 1.7.0

**Comment by enchev** [comment]
Hey @manijak,

Have you tried to use image-cache similar to this app?
https://github.com/NativeScript/NativeScript/blob/master/apps/cuteness.io/reddit-app-view-model.ts#L18

**Comment by manijak** [comment]
I will try image-cache module. fresco looks also interesting, but is android only, I need something cross-platform.

**Comment by enchev** [comment]
Do you have the same problem in iOS? As far as I know something similar to iOS is https://github.com/rs/SDWebImage

**Comment by manijak** [comment]
I am not sure if the same problem is on iOS, I mean, it does not crash the app while scrolling the lists, like on Android, but it does crash the app randomly when opening views that contain ListView with images. Also without error...

**Comment by manijak** [comment]
UPDATE: After implementing image-cache in my app, the android app seems more responsive and without crashes!

**Comment by cinder92** [comment]
i have same issue here but with nativescript 2.0.0!! why i need to implement cache in my image while scrolling in listview?! :C

**Comment by ComputerTinker** [comment]
I'm having the same issue with Nativescript 2.1.0 on Android.  In my case, each of the rows is referencing the same remote server image (so you would think there would be some shared efficiency).  The app will load the first few list items, but then after scrolling down a few lines, it crashes very reliably.
