### ISSUE TITLE
Java proxy Is not Defined {N} 1.7

### ISSUE THREAD

**Issue by Milewski** [NativeScript/NativeScript#1803]
getting this error right after updating to 1.7 the app can not be launch

```
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Error calling module function 

ReferenceError: JavaProxy is not defined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'/data/data/com.app.cms.app/files/app/tns_modules/ui/frame/frame.js', line: 564, column: 9
	Frame: function:'', file:'/data/data/com.app.cms.app/files/app/tns_modules/ui/frame/frame.js', line: 567, column: 2
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/com.app.cms.app/files/app/tns_modules/application/application.js', line: 2, column: 13
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/com.app.cms.app/files/app/app.js', line: 2, column: 19


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
	at android.app.ActivityThread.-wrap1(ActivityThread.java)
	at android.app.ActivityThr
```

**Comment by NathanaelA** [comment]
You need to make sure you have TNS 1.7 Android runtimes installed.
**tns platform remove android**
then
**tns platform add android**
Then you should be able to see in your main package.json, both a tns-android: {version: "1.7.x"}

**Comment by Milewski** [comment]
@NathanaelA yeah worked for android... i am just wondering if i have to remove iOS and build again.. does it mean i will lose my .xcodeproject file?

**Comment by NathanaelA** [comment]
If you are upgrading to 1.7, then yep...  There are three things you need to upgrade at a minimum each version.   the NativeScript command line tools; the Common-Core-Modules, and the Runtimes.

**Comment by Milewski** [comment]
thats a problem as my app also has an iWatch Version build on top of the xcodeproject file.. so... my iWatch app will be wiped out.. any suggestion on how i could handle this next time?.

**Comment by gabrielbiga** [comment]
+1!
I'm having this problem as well just in Android... This decorator (JavaProxy) was added in https://github.com/NativeScript/NativeScript/pull/1668 pull request. 
Where is the implementation for JavaProxy? I'm running the 1.7 platform.

**Comment by gabrielbiga** [comment]
Guys, I solved the problem just updating my nativescript-cli...
 ```
sudo npm install -g nativescript
 ```
Don't forget to check the platform version and tns-core-modules if is in 1.7.0
The build was tested and working for OSX and Ubuntu.
