### ISSUE TITLE
Missing crash dialog on TNS 1.7.0

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#1804]
## Please, provide the details below:
When an application crashes on Android; it appears to freeze rather than "navigate" to the error screen and show the callback.

### Did you verify this is a real problem by searching?
Yes, and verified with a couple other people on the Slack

### Tell us about the problem
Missing Error screen and freezing app; I suspect they are related -- i.e. it is freezing when attempting to navigate.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
1.7 CLI
1.7 & Master (3/18) Runtime
1.7 Common modules

### Please tell us how to recreate the issue in as much detail as possible.
1. tns create testApp
2. Edit main-screen and add anywhere to the pageLoaded  "crashme();"  or edit the tap handler in the main-view-model() and add the crashme();  (i.e. a missing function call);
3. Start or click the app button.
4. See error in console, but app freezes and (might give a ANR dialog if you wait)

**Comment by dtopuzov** [comment]
If you build/run release configuration it is expected. This dialog is available only when you build/run in debug configuration. 

Please let us know if dialog is missing in debug.

**Comment by ngydat** [comment]
I kinda have the same issue. Before updating to {N} 1.7 my app was running fine but now whenever I type "tns livesync android" or "tns run android" I get a white screen and a few seconds later, I get this message "MyApp is not responding" and I have 2 buttons : "Wait" and "Close"

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#394
