### ISSUE TITLE
Fixed: SearchBar.textFieldHintColor not respected on iOS

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#1807]
As stated in the title, the textFieldHintColor property of SearchBar does not work when it's inside the ActionBar (tested in ActionBar.titleView). If I move the SearchBar outside the ActionBar tag, it works.

Tested on iOS only. As seen in the screenshot, the text color is gray, but should be white:

![image](https://cloud.githubusercontent.com/assets/2098838/13899023/1ee8568e-ede4-11e5-86be-0eec59aa42ad.png)

```
<Page.actionBar>
  <ActionBar title="{{ language.matches_title }}">
    <ActionBar.titleView>

      <AbsoluteLayout row="0" id="searchBar-container">
        <SearchBar top="0" id="searchBar" hint="{{ language.searchMatches }}" textFieldHintColor="#ffffff" textFieldBackgroundColor="#48af7a" width="{{ searchBarWidth }}" />
        <StackLayout top="0" class="border" width="{{ searchBarWidth }}" />
        <StackLayout top="43" class="border" width="{{ searchBarWidth }}" />
      </AbsoluteLayout>

    </ActionBar.titleView>
  </ActionBar>
</Page.actionBar>
```

**Comment by tsonevn** [comment]
Hi @NordlingArt,

Unfortunatly, I found that textFieldHintColor is not supported for ios apps
The code behind SearchBar textFieldHintColor property was create by  @NathanaelA. 
He can give further information on this issue.

**Comment by tsonevn** [comment]
Hi @NordlingArt , 
I apologize for the delay in replying. I made a little research and found that you can change `textFieldHintColor` manually in `iOS` by changing `UILabel` `textColor` property.
I am attaching an example, how you can do this:

main-page.xml
```
<Page navigatingTo="navigatingTo">
  <Page.actionBar>
    <ActionBar title="{{ language.matches_title }}">
      <ActionBar.titleView>
        <AbsoluteLayout row="0" id="searchBar-container">
          <SearchBar top="0" id="search" hint="test" textFieldHintColor="white" textFieldBackgroundColor="#48af7a" width="300" loaded="load"/>
      </AbsoluteLayout>
      </ActionBar.titleView>
    </ActionBar>
  </Page.actionBar>
</Page>
``` 
main-page.ts
```
import { EventData } from "data/observable"; 
import { Page } from "ui/page"; 
import {SearchBar} from "ui/search-bar"; 
import {Color} from "color"; 
import {Label} from "ui/label"; 

export function navigatingTo(args: EventData){

  var page:Page = <Page> args.object;
  if(page.ios){
    var search:SearchBar = <SearchBar> page.getViewById("search");
    var searchField = search.ios.valueForKey("searchField");
    var label = searchField.valueForKey("placeholderLabel");
    label.textColor = UIColor.yellowColor();
  }
}

```

I hope this is applicable for you.

**Comment by NordlingArt** [comment]
Hi @tsonevn,

No worries. I'll take a look at this. Thanks for hitting back to it!
