### ISSUE TITLE
Unable to show dialog from a modal page

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#1809]
Reporting from iOS. Calling this function from inside a modal page:

```
exports.selectPhoto = function() {
  dialogs.action({
    message: "Select new photo",
    cancelButtonText: "Cancel",
    actions: ["Take photo", "Select from Photos"]
  }).then(function (result) {
    console.log(result);
  });
};
```

Will give me the error:

> Warning: Attempt to present \<UIAlertController: 0x7cbd3a00> on \<UIViewControllerImpl: 0x7b7a88b0> whose view is not in the window hierarchy!

What is this, and how do I fix it?

Thanks in advance!

**Comment by tsonevn** [comment]
Hi @NordlingArt,

I reviewed this issue. Unfortunately I could not recreate the problem. 
Can you tell us more about the given error or sent us a simple project which shows the problem.

**Comment by yclau** [comment]
I meet this error too. In android , it work probably but in IOS , come out same error.

**Comment by tsonevn** [comment]
Hi @yclau, 
Could you give more details about the abnormality. Could you tell us more about the given error or sent us a simple project which shows the problem.

**Comment by yclau** [comment]
zzz zzzz has shared a?OneDrive?file with you. To view it, click the link below.


<https://onedrive.live.com/redir?resid=AB701A01965B0E3C!549&authkey=!AGolb1iVZauJz5U>
[https://r1.res.office365.com/owa/prem/images/dc-zip_20.png]<https://onedrive.live.com/redir?resid=AB701A01965B0E3C!549&authkey=!AGolb1iVZauJz5U>

Project.zip<https://onedrive.live.com/redir?resid=AB701A01965B0E3C!549&authkey=!AGolb1iVZauJz5U>




Hi,


Sorry for late reply, the attachment is my example project.

________________________________

**Comment by tsonevn** [comment]
Hi @yclau , 
Thank you for your sample project. 
I reviewed it and I confirm this is real issue. This problem is scheduled for fixing. 
I am attaching link to the project repository: 
https://github.com/tsonevn/iOSModalPageAlert.git

**Comment by nmandyam** [comment]
I am using 2.2.1, still have this problem. How come?

**Comment by dlucidone** [comment]
I'm having the same issue is there any fix for this?

**Comment by tsonevn** [comment]
Hi @dlucidone,
This issue has been fixed with NativeScript 3.0. For your convenience, I update the sample project [here](https://github.com/tsonevn/iOSModalPageAlert). You could clone it and test it on your side.

**Comment by BMwanza** [comment]
Hi, I've run into a similar problem on 4.1.1 I am trying to display a confirmation dialog from a modal, however, console error appears, the dialog just simply does not display.

**Comment by tsonevn** [comment]
Hi @BMwanza,
Can you provide more info about the error, which has appeared in the console? Also, send us a sample project, where the problem can be reproduced.

**Comment by t3hmrman** [comment]
Hey I just ran into this issue while trying to work with a different library but I think what I found applies here -- the issue might be [a limitation of iOS](https://github.com/NativeScript/NativeScript/issues/423) -- in my case I was trying to call `.scan` of the [nativescript-barcodescanner](https://github.com/EddyVerbruggen/nativescript-barcodescanner) project, but it will attempts to open a *new* modal, and at that point I had an modal *already open*.  The error I was seeing:

```
Warning: Attempt to present <QRCodeReaderViewController: 0x14fe80140> on <UINavigationControllerImpl: 0x15017b800> whose view is not in the window hierarchy!
```

For me, I fixed this by calling `this.$modal.close()` in the `ios` case inside the modal I had open, and refactored the rest of the code as necessary.

**Comment by webleaf** [comment]
Can someone check, does it works on iOS? I've seen message in one of the community chat, that someone can't open action dialog from modal in iOS (without any errors in console).
I don't have enviroment to check this. But I will need it in the near future.

**Comment by tsonevn** [comment]
Hi @webleaf,
I tested the scenario with the modal view and the dialogs with our https://github.com/NativeScript/nativescript-sdk-examples-js app and everything seems to work as expected on iOS

**Comment by ycherniavskyi** [comment]
I trap into this issue with NS 5.4. Yes, the structure of my layout is not trivial, but I think that *dialog* must work in any circumstances.

I extract my layout in [playground](https://play.nativescript.org/?template=play-tsc&id=bFb6p4).

As you could see from source code *dialog* operation depends on which view modal is opened. Unfortunately, in my case have access only to topmost frame.

**Comment by ycherniavskyi** [comment]
@tsonevn maybe it is better to open new issue?

**Comment by ycherniavskyi** [comment]
Ups, sorry for buzzing 😊.
Just found the solution - instead of `topmost().page.showModal` must be used `topmost().currentPage.showModal`, and everything works as expected!

**Comment by jelledijkstra97** [comment]
I have the issue on my Angular app. I'm opening a modal from my home page and on that modal I'm trying to open a confirm dialog, but that doesn't work. When first navigating away from the homepage, then returning back to the homepage and opening the modal + confirm, everything works as expected. The home page is lazily loaded.
