### ISSUE TITLE
Listview Items array, does the length has to be fixed?

### ISSUE THREAD

**Issue by JiaCui819** [NativeScript/NativeScript#181]
Scenario:
It's very similar to sample cuteness: https://github.com/NativeScript/sample-cuteness
I'm trying to create a listview with text buttons and switches in each row. I create virtual array with specific length, bind it to my listview items property. And I receive JSON with data, map and load it to the virtual array. In page xml, I code to add buttons and switched to listview template.

I kind have several issues here:
1. length of ListView is based on length of virtual array. so if my data is less than the length of virtual array, there would be blank rows at the end. What if my data exceeds the length, since I don't know how many records would be returned.
2. I guess, since I hard code the switches and buttons in the page xml ListView template. I get buttons in those 'blank' rows at the end.
3. this might be a JSON question, do i have to return a class from the server? Could I somehow return a string or int, and bind it to a textfield? I didn't figure out a way to read JSON {"JSONDataResult":"You requested product No.1234"} and bind it.

Any advice or ideas for these issues?
Thank you!

![img_5641](https://cloud.githubusercontent.com/assets/12416729/7690507/c82fd37c-fd79-11e4-82f5-3332d315d4b2.PNG)

main-page.xml
![page](https://cloud.githubusercontent.com/assets/12416729/7690633/f6a34170-fd7a-11e4-8189-a080b7d6b38a.jpg)

main-view-model.js
![view-model](https://cloud.githubusercontent.com/assets/12416729/7690640/00df3054-fd7b-11e4-8ed5-5756999f7941.jpg)

**Comment by enchev** [comment]
Straight onto your questions:
1) You can always extend the length when needed [similar to cuteness app](https://github.com/NativeScript/NativeScript/blob/master/apps/cuteness.io/main-page.ts#L33)
2) You can hide/show conditionally UI depending on your logic. We used [similar technique in our TelerikNEXT app](https://github.com/NativeScript/sample-TelerikNEXT/blob/master/app/main-page.xml#L90)
3) You can use primitive types as well. To refer the bindingContext in your temlate you can use $value
