### ISSUE TITLE
Android:Ripple effect lost for listview if background color set

### ISSUE THREAD

**Issue by Daxito** [NativeScript/NativeScript#1810]
### Did you verify this is a real problem by searching
Yes, and I did not find anything related to the list view (a button seems ok)

### Tell us about the problem
Having a list view, using itemTemplate with a grid, if I set a background color to the grid then the ripple effect is lost, this does not happen to buttons though (outside of list view btw), buttons keep the ripple effect even after changing background color, why is it that list view items loses it.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 1.7, 
- Cross-platform modules: 1.7
- Runtime(s): 1.7

### Please tell us how to recreate the issue in as much detail as possible.
Just run the attached sample app (does not include the platform folder btw), tap one item and there is no ripple effect, remove the background color and rerun it, the ripple effect is now back

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Here the sample app: 
[master-detail.zip](https://github.com/NativeScript/NativeScript/files/181165/master-detail.zip)

**Comment by NickIliev** [comment]
It's true that when background-color is set on the GridLayout inside the ListView.ItemTemplate the newly set color is overlapping the default android color including the ripple effect itself. This is a default behavior in Android as well. 
However there is an easy fix - remove the styling from your GridLayout and apply it to the ListView. Now you can have your desired background-color set and also the ripple effect is still here.
That won't work if you want your ListView items to be set in different colors - in that case you should right your own code-behind ripple effect!

**Comment by Daxito** [comment]
ok, well, then closing this issue, I will check your suggestion. thank you.

**Comment by nikoTM** [comment]
@NickIliev kind of related question: Is it possible to have `transparent` list items, but no ripple?
