### ISSUE TITLE
Element.Animate vs Animation.Animate differences

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#1811]
## Please, provide the details below:
If you use Element.Animate; you lose the ability to cancel the animation, because it returns a promise from the .play() event and not the animation object.

### Did you verify this is a real problem by searching
yes

### Tell us about the problem
No animation cancelling allowed on a Element.Animate

### Which platform(s) does your issue occur on?
All

### Please provide the following version numbers that your issue occurs with:
1.7

---

I have developed a very simple "patch" that will monkey patch the Promise returned by the Element.animate (and any .then's) to have a .cancel on it (i.e. to match the same name as the animation.cancel function).   This will then allow you to do:

```
var x = Element.animate({blah}).then(function() { more blah });
if (something_occured) x.cancel();
```

Is this something that would be acceptable to be put into core, if so I'll convert it from JS into TS and push a pull request.   But if you are opposed to something "monkey" patching the promise to add a cancel function, then I won't bother doing the translating back into TS, and just add it to my own little bag of tricks.

**Comment by hamorphis** [comment]
Go ahead and create a pull request with the new method. You can also add a test similar to `test_CancellingAnimation` located [here](https://github.com/NativeScript/NativeScript/blob/master/apps/tests/ui/animation/animation-tests.ts)

**Comment by NathanaelA** [comment]
@hamorphis Added pull request #1821 -- I really hate TS & v8 today.  Literally had JS working 100% in 5 minutes.   Took multiple hours to get TS and v8 to play nicely.   Oy, this turned into a fiasco time wise; but it is done w/ tests.
