### ISSUE TITLE
Add ability to set attributed text on Button

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#1813]
Currently we have this for labels. I think would be good to add this for Buttons as well. Will give user ability to add icon font and text inside buttons or add text with different styles inside the button.

**Comment by Daxito** [comment]
+1

**Comment by pierrediderot** [comment]
+1

**Comment by enchev** [comment]
Hey folks,

As far as I know you can use such styling even now:
```XML
<Page>
    <Button>
        <Button.formattedText>
            <FormattedString>
                <FormattedString.spans>
                    <Span text="&#xf17b;" fontFamily="FontAwesome" fontAttributes="Bold" foregroundColor="red" />
                    <Span text="My" fontAttributes="Bold" foregroundColor="#0000ff" />
                    <Span text="Button" fontAttributes="Italic" foregroundColor="#00ff00" />
                </FormattedString.spans>
            </FormattedString>
        </Button.formattedText>
    </Button>
</Page>
```

Or you have something else in mind?

**Comment by PeterStaev** [comment]
Hey @enchev , 

Yes, seems that was the problem on Android (I tried it on Android before). Once I removed the default android capitalization the button works as expected :+1:
