### ISSUE TITLE
all topmost().navigate instances stop working after Admob Interstitial close

### ISSUE THREAD

**Issue by calebeaires** [NativeScript/NativeScript#1820]
When Admob Interstitial is called and after user close the ad, all ```frameModule.topmost().navigate()``` stop working.

This problem occurs on [Nativescript blog implementation](https://www.nativescript.org/blog/details/monetize-your-nativescript-apps-with-admob-(part-2---android)) and nativescript-admob plugin too. from the blog content.

Example code I am using:
```
exports.buttonClicked = function(){
    frameModule.topmost().navigate({
        moduleName: "views/home",
        animated: true,
        transition: {
            name: "slideTop"
        }
    });
}
```
Platform: Android 5;
Nativescript: 1.7;

**Comment by NickIliev** [comment]
@calebeaires 
Yes indeed this is existing issue and the problem is scheduled for fixing. We think it was introduced with the #1647 PR. Thank you for noticing this problem - we will do our best to resolve it in a timely matter

**Comment by calebeaires** [comment]
Very thanks. 

Is there some workaround code to work with before you fix it?
