### ISSUE TITLE
NativeScript RequestPermission undefined

### ISSUE THREAD

**Issue by mabelanski** [NativeScript/NativeScript#1828]
How i can do for use android.support.v4.app.ActivityCompat.requestPermissions or android.app.Activity.requestPermissions ? 
Because it's always undefined 

I want to do this 

    var context = android.content.Context;
    var wifi_service = application.android.context.getSystemService(context.WIFI_SERVICE);

    wifi_service.setWifiEnabled(true);  
    var rs = wifi_service.startScan();

    console.log(android.support.v4.app.ActivityCompat.requestPermissions); // undefined
    console.log(android.support.v4.content.ContextCompat.requestPermissions); // undefined
    
    application.android.registerBroadcastReceiver(
      android.net.wifi.WifiManager.SCAN_RESULTS_AVAILABLE_ACTION,
      function onReceiveCallback(context, intent) {      
         var tp = wifi_service.getScanResults();
         console.log(tp); // empty []
         console.log(tp.size()); // 0
      });

but array tp is always empty and i thing that because i need the right permission, and on android 6 we need to ask it 

i also add on manifestfile :

    <uses-feature android:name="android.hardware.wifi" />
    <uses-feature android:name="android.hardware.location" android:required="false" />
    <uses-feature android:name="android.hardware.location.network" android:required="false" />
    <uses-feature android:name="android.hardware.location.gps" android:required="false" />

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission-sdk-23 android:name="android.permission.ACCESS_COARSE_LOCATION" />
    
also add on C:...\app\App_Resources\Android\app.gradle :

    dependencies {
        compile "com.android.support:support-v4:+"
        , compile "com.android.support:appcompat-v7:+"
    }

Thanks

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#399
