### ISSUE TITLE
`LayoutBase.clipToBounds=false` does not work on Android [CAN"T FIX]

### ISSUE THREAD

**Issue by hamorphis** [NativeScript/NativeScript#1829]
Add a child with negative margin to a layout. Part of the child should be rendered outside its parent layout and it is, but the part that is outside is clipped even if the layout's clipToBounds property is set to false.

**Comment by hamorphis** [comment]
Add a child with negative margin to a layout. Part of the child should be rendered outside its parent layout and it is, but the part that is outside is clipped even if the layout's clipToBounds property is set to false.

**Comment by Brainvise** [comment]
Any luck on this?

**Comment by hamorphis** [comment]
@Brainvise I am starting on it...

**Comment by hamorphis** [comment]
@Brainvise 

I spent two days researching this topic and I do not very good news. Android's clipping logic has nothing to do with iOS.

We can't implement this without calling setClipChildren(false) on every ancestor up in the visual tree, 
which will kill performance. It will also lead to unwanted side effects such as other totally unrelated 
views being affected by setting the parents' setClipChildren to false. The following article explains this in detail.
The problem in Android is that a ViewGroup either clips ALL of its children or it does not. Unlike iOS, the clipping 
cannot be controlled on a per view basis. So clipToBounds=false will have to be somehow achieved with stacking different
views on top of one another in an AbsoluteLayout or GridLayout. There is always a workaround when playing with layouts.

The following article explains the whole process in very great detail:
http://stackoverflow.com/questions/25044085/when-drawing-outside-the-view-clip-bounds-with-android-how-do-i-prevent-underli

**Comment by hamorphis** [comment]
So I guess we might even deprecate this property, since we can't implement it for Android in a sane way. Unless someone knows how.

**Comment by Brainvise** [comment]
@hamorphis I figured this might be the case. Luckily for me, I'm going about my project in a completely different way, so this doesn't affect me any more. But, I could see it causing others issues. Thanks for looking into it.
