### ISSUE TITLE
I am unable to update the tns

### ISSUE THREAD

**Issue by aderbas** [NativeScript/NativeScript#1850]
I do according to the documentation, my current version is 1.5.2, before update version continues 1.5.2. I'm restart the system but don't update. I'm use Linux Mint 17.2
```
$ sudo npm install nativescript -g
```
```
$ tns doctor
$ No issues were detected.
```
When installing it warns that ANDROID_HOME is not set, but if I try:
```
$ echo $ANDROID_HOME
/media/aderbal/DATA/android/Sdk/
```
During and at the end of the installation has no error message unless the notice of ANDROID_HOME. Any helpe?

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#1645
