### ISSUE TITLE
Fresh app works anywhere, except on Redmi 2 devices!

### ISSUE THREAD

**Issue by calebeaires** [NativeScript/NativeScript#1851]
Fresh Nativescript app (with no modification) stop working on Xiaomi Redimi 2 Prime smartphones. I have tested the same app on Sansung, Nexus, Genymotion and Android emulator. Everting goes well, except on Redimi 2. Here are the reporting log:

```
W/dalvikvm(24260):              in Lcom/tns/Platform;.callJSMethodNative:(ILjava/lang/String;IZ[Ljava/lang/Object;)Ljava/lang/Object; (CallVoidMethodA)
I/dalvikvm(24260):   at com.tns.Platform.callJSMethodNative(Native Method)
I/dalvikvm(24260):   at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:816)
I/dalvikvm(24260):   at com.tns.Platform.callJSMethod(Platform.java:715)
I/dalvikvm(24260):   at com.tns.Platform.callJSMethod(Platform.java:694)
I/dalvikvm(24260):   at com.tns.Platform.callJSMethod(Platform.java:684)
W/ErrorReport(  950): org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
W/ErrorReport(  950): 	at org.json.JSON.typeMismatch(JSON.java:111)
W/ErrorReport(  950): 	at org.json.JSONObject.<init>(JSONObject.java:159)
W/ErrorReport(  950): 	at org.json.JSONObject.<init>(JSONObject.java:172)
```

Redimi 2: Android 4.4
NativesScript 1.7.1

**Comment by enchev** [comment]
In my opinion JSON.parse() is failing since some service/server returned HTML (most probably server error) instead expected JSON.

**Comment by calebeaires** [comment]
Do you have some workaround to fix it?

**Comment by enchev** [comment]
Any more info what components are used or how to replicate this behavior will be helpful. Do you get this error in some of our default modules? Or this is somewhere else in your app?

**Comment by calebeaires** [comment]
This error get on a pure nativescript install.

1. ```tns create example```
2. ```tns platform add android```
3. ```tns run android```

This works on every device I have here (motorola, samsung, nexus), but when I run it on Redmi 2 Prime, from Xiaomi, the app stop working and it is closed.

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#404
