### ISSUE TITLE
ActionBar on Android has a thin bottom border since 1.6

### ISSUE THREAD

**Issue by maknz** [NativeScript/NativeScript#1858]
Since 1.6, the ActionBar on Android seems to have a thin bottom border being applied. Is there a property we can use to style this away? On 1.5 and below this worked, so I suspect something in 1.6 introduced this change. I thought it might be the same issue as the default Android button styles being used when no border property is set -- setting the border to the background colour doesn't help.

![screen shot 2016-03-29 at 11 50 57 am](https://cloud.githubusercontent.com/assets/992356/14092767/b55a301a-f5a5-11e5-8c67-cb9d231b1779.png)

The ActionBar is styled as such (in app.css):

```css
ActionBar {
  color: #FFFFFF;
  background-color: #6B2C81;
  border-width: 0.1;
  border-color: #6B2C81;
}
```

and it appears in the page:

```xml
  <Page.actionBar>
    <ActionBar title="">
      <ios>
        <NavigationButton />
      </ios>
    </ActionBar>
  </Page.actionBar>
```

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 1.7.0 (but 1.6 and up)
- Cross-platform modules: 1.7.0 (1.6 and up)
- Runtime(s): Android 1.7.1, iOS 1.7.0 (1.6 and up)

**Comment by tsonevn** [comment]
Hi @maknz,

I tried to recreate the abnormality in a local project, actually there is no thin bottom border.
Could you chack if there is other ActionBar border-color define. 
It would help if we could give me more info how to replicate this behavior.

![screenshot 4](https://cloud.githubusercontent.com/assets/17448734/14099801/508f3270-f591-11e5-9aa0-76eda7f68d19.png)
