### ISSUE TITLE
SegmentedBar selectedIndex binding does not work after setting new value

### ISSUE THREAD

**Issue by MiroValchev** [NativeScript/NativeScript#1863]
Really strange one (NativeScript 1.6, haven't tested yet on 1.7):

`<SegmentedBar selectedIndexChanged="{{ test1 }}" selectedIndex="{{ selectedDay.sex }}">
            <SegmentedBar.items>
                <SegmentedBarItem title="No" />
                <SegmentedBarItem title="Unprotected" />
                <SegmentedBarItem title="Protected" />
            </SegmentedBar.items>
        </SegmentedBar>`

The first time it works just fine. What I do is bind to the selected day from a calendar component.
//js1
console.log(day.sex);
this.set("selectedDay", day);

`public test1(args: any): void {
//js2
        console.log(args.newIndex + " - " + this.selectedDay.sex);        
    }`

JS1: 1
//tapping the different segmentBarItems
JS2: 1 - 1
JS2: 0 - 0
JS2: 2 - 2

Next I choose a new day.
JS1: 0
JS2: 0 - 0
JS2: 1 - 0
JS2: 2 - 0

As you can see selectedIndex binding is no longer updating the selectedDay.sex value.

**Comment by tsonevn** [comment]
Hi @MiroValchev,
I have recreated this issue,actually the event handler for SegmentedBar works correct in my local project. 
It would help if you could give me more info how to replicate this behavior or to send us sample project, which reproduce this problem.

**Comment by MiroValchev** [comment]
Hi @tsonevn,

Can you send me your local project, as it will be faster to modify it and send it back. miro@thecoolapps.com is my email, thanks!

**Comment by tsonevn** [comment]
Hi @MiroValchev,

You can review my simple project from link below:

https://github.com/tsonevn/segmented-Bar-Event-Handler.git

Let me know whether this helps or if I can assist you further.

**Comment by MiroValchev** [comment]
Let me upgrade to {N} 1.7 and will get back to you. Should find enough time to test it by Monday.

**Comment by MiroValchev** [comment]
@tsonevn please check this out https://github.com/MiroValchev/SegmentedBarIssue. It could be a binding issue, not sure. Anyway it's not working as expected.

Select another day and try to play with the segemented bar. Also, when selecting empty days with no event, the segmented bar binding is not working again. Could be a silly mistake on my side.

**Comment by tsonevn** [comment]
Hi @MiroValchev, 

I reviewed your code and found that problem is due to incorrect handling of property change event. 
I've made some changes. To address the problem, review the code below.

calendar.ts
```
import calendarModule = require("nativescript-telerik-ui-pro/calendar");
import {Observable, EventData} from "data/observable";
import {Log} from "../models/log";
import {Day} from "../models/day";
import moment = require("moment");
import frames = require ("ui/frame");

export class CalendarViewModel extends Observable {
    constructor() {
        super();                
    }

    public logs: Array<Log>;       
    public selectionMode: string;
    public events: Array<calendarModule.CalendarEvent>;            
    public selectedDay: Day;
    
    private _selectedIndex:number;    
    
    public loadCalendar(): void {
        this.set("selectionMode", calendarModule.CalendarSelectionMode.Single);
        this.setEvents();
        this.daySelected({ args: moment().startOf('day') });                    
    }    
    
    private setEvents(): void {        
        var events: Array<calendarModule.CalendarEvent> = [];

        var logs: Array<Log> = [];        
        for (var j = 0; j < 28; j++) {           
            if (Math.floor((Math.random() * 2) + 1) == 2) {
                logs.push(new Log(moment().startOf('day').subtract(j, 'days'), 2));
            }            
        }                
        this.logs = logs;

        for (var log of logs) {
            events.push(log.getEvent());
        }
                
        this.set("events", events);
    }
    
    public daySelected(args: any): void {        
        var date: moment.Moment = moment(args.date);                            
        var day: Day = new Day();
        day.date = date;
        
        var logs: Array<Log> = this.logs.filter(function(l) {
            return (l.isDateInLog(date));
        });

        day.sex = 0;
        logs.forEach(log => {
            day.sex = log.sex;
        });
        
        this.selectedDay = day;
        this.selectedIndex = day.sex;        
    }

    public sexSelected(args: any): void {        
        console.log("Args.newIndes: " + args.newIndex + " - selectedDay.sex: " + this.selectedDay.sex);
    }  
    
    public get selectedIndex():number{
        return this._selectedIndex;
    }  
    public set selectedIndex(arg:number){
        this._selectedIndex = arg;
        this.selectedDay.sex = this._selectedIndex;
        super.notify({ object: this, eventName: Observable.propertyChangeEvent, propertyName: "selectedIndex", value: arg });
    }      
}

export var vm: CalendarViewModel = new CalendarViewModel();
```

calendar.xml

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" 
      xmlns:rc="nativescript-telerik-ui-pro/calendar"
      xmlns:lv="nativescript-telerik-ui-pro/listview"
      loaded="pageLoaded"
      navigatingFrom="navigatingFrom">
  <GridLayout rows="auto, *, 200">    
      <rc:RadCalendar id="calendar"
                      row="1"      
                      eventSource="{{ events }}"                      
                      selectionMode="{{ selectionMode }}"
                      maxDate="{{ maxDate }}"
                      dateSelected="{{ daySelected }}"
                      dateDeselected="{{ dayDeselected }}"/>
      <StackLayout row="2">      
        <SegmentedBar selectedIndexChanged="{{ sexSelected }}" selectedIndex="{{ selectedIndex }}">
            <SegmentedBar.items>
                <SegmentedBarItem title="No" />
                <SegmentedBarItem title="Unprotected" />
                <SegmentedBarItem title="Protected" />
            </SegmentedBar.items>
        </SegmentedBar>            
      </StackLayout>
  </GridLayout>
</Page>
```
I hope this is applicable for you.
Kind regards

**Comment by MiroValchev** [comment]
Hi @tsonevn,

Why do I need a getter and setter for this? Since I do have selectedDay property in my observable view model, should there be a straightforward way for this binding to work:
<SegmentedBar selectedIndexChanged="{{ sexSelected }}" selectedIndex="{{ selectedDay.sex }}">
It's a nested property, but that should work?

Sorry for bugging you with those questions, just trying to figure this out :)

**Comment by tsonevn** [comment]
Hi @MiroValchev, 
There are two appropriate ways to make binding to works.
When you extend observable class you should use getter and setter for every property like this:
```
export class User extends Observable {
    private _email: string;
    private _password: string;
    private _age: number;

    constructor(email: string, password: string, age: number) {
        super();
        this._email = email;
        this._password = password;
        this._age = age;
    }

    public get email(): string {
        return this._email;
    }

    public set email(value: string) {
        this._email = value;
        super.notify({ object: this, eventName: Observable.propertyChangeEvent, propertyName: "email", value: value });
    }

    public get password(): string {
        return this._password;
    }

    public set password(value: string) {
        this._password = value;
        super.notify({ object: this, eventName: Observable.propertyChangeEvent, propertyName: "password", value: value });
    }

    public get age(): number {
        return this._age;
    }

    public set age(value: number) {
        this._age = value;
        super.notify({ object: this, eventName: Observable.propertyChangeEvent, propertyName: "age", value: value });
    }
}

```
or you can define new observable object and handle porperty change event like it is describe in the documentation

https://docs.nativescript.org/ApiReference/data/observable/HOW-TO.html

**Comment by MiroValchev** [comment]
Thanks for the clarification!
