### ISSUE TITLE
Variable WCSession not defined {N} 1.7.0

### ISSUE THREAD

**Issue by Milewski** [NativeScript/NativeScript#1866]
i'm trying to share data between iPhone and iWatch but i am not able to get [WCSession](https://developer.apple.com/library/ios/documentation/WatchConnectivity/Reference/WCSession_class/). it always returns me as null and crash whenever i try to access it..

here is the code i'm trying to execute:

```
if (!application.ios) return;

 if (WCSession.isSupported()) {
   var session = WCSession.defaultSession();
   session.delegate = this;
   session.activateSession();
}
```
Error
```
ReferenceError: Can't find variable: WCSession
```

Theoretically it should be a global object or as WCSession or NSObject.WCSession isn't it?

**Comment by enchev** [comment]
This issue was moved to NativeScript/ios-runtime#541
