### ISSUE TITLE
ActionBar icons (back, hamburger) are impossible to set on a exact margin from the left edge of the screen (e.g. 16)

### ISSUE THREAD

**Issue by myninka** [NativeScript/NativeScript#1870]

**Comment by gabitoesmiapodo** [comment]
This bug or glitch is still present as of version 3.2.

<img width="392" alt="screen shot 2017-09-22 at 11 49 25" src="https://user-images.githubusercontent.com/4015436/30750230-352acea8-9f8c-11e7-9bdc-67174d53a70a.png">

It may be an Android limitation? I'm not sure.

**Comment by tsonevn** [comment]
related to https://github.com/NativeScript/NativeScript/issues/6133
