### ISSUE TITLE
No platform.xx.css after creating Typescript template

### ISSUE THREAD

**Issue by dreambo8563** [NativeScript/NativeScript#1873]
## Please, provide the details below:
Create app with typescript template. I just follow the Getting started Guide with the template,
and I can not found the platform.ios.css and platform.android.css under app folder.

after reading how NS works on these platform.xx.css, I create these two css file by myself. suppose NS will move them into the platforms folder when app runs.

I add styles into to platform.android.css, it not woks. but works if I add styles into app.css

### Which platform(s) does your issue occur on?
I just test on android, no mac....

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)  1.7.1
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) -- 1.7.1
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project) "version": "1.7.1"

**Comment by tsonevn** [comment]
Thank you for your issue.
If you want to use platform specific css file, you should add `@import { url('~/platform.css') };` as the first line of your app's app.css file.
I hope this information helps. Please let me know if you are still having any problems

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#1659
