### ISSUE TITLE
[DESIGN] 'ui/dialogs' alert, confirm... background color and white text color...

### ISSUE THREAD

**Issue by myso-kr** [NativeScript/NativeScript#1876]
All messages will be displayed in the dialog output color to white.
Android is only solved by changing the AppTheme below.
iOS, I do not know what to do.

##### Problems
`<Style name = "AppThemeBase" parent = "Theme.AppCompat.Light.NoActionBar">`

##### Solves
`<Style name = "AppThemeBase" parent = "Theme.AppCompat.NoActionBar">`

**Comment by NickIliev** [comment]
Styling dialogs is discussed [**here #1586**](https://github.com/NativeScript/NativeScript/issues/1586) and yes  - changing the global themes in Androidis one way to set the background color - this is in fact a way to stay native. For IOS the native behaviour is that you cannot customize the appearance of alert views (source:[apple(https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/UIKitUICatalog/UIAlertView.html)

Applying a global CSS style **_color_** to **Label**, **TextView** and **Button** will also affect the style of dialogs.The discussion in the link above is explaining some of this behaviour.
Please let me know if you need more information / help on that matter.
