### ISSUE TITLE
Feature Request : can nativescript be used to develop android tv and apple tv apps?

### ISSUE THREAD

**Issue by bathejasumeet** [NativeScript/NativeScript#1880]
NativeScript already supports android and ios , just curious, can the same be used to develop apple tv and android tv apps?

**Comment by enchev** [comment]
Hey @bathejasumeet,

We've experimented last year with Apple TV:
https://www.nativescript.org/blog/details/running-the-nativescript-runtime-for-ios-on-apple-tv

**Comment by bufke** [comment]
Is Android TV supported (or planned)?

**Comment by rdlauer** [comment]
@bufke It's been a while, but FYI: https://www.nativescript.org/blog/building-an-android-tv-app-with-nativescript
