### ISSUE TITLE
DatePicker implement changed events

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#1884]
Feature request: Similar to other widgets, can we please add a changed event to the date picker?

https://github.com/NativeScript/NativeScript/blob/master/ui/date-picker/date-picker-common.ts

**Comment by enchev** [comment]
Hey @sitefinitysteve,

Can you provide more info about your scenario? 

Currently all DatePicker properties are dependency properties and you can monitor their changes if you bind your view-model to them.

**Comment by maddes** [comment]
I have a button that toggles the date-picker. On the button I need to show the current selection.

How do I do that? With a changed event would be so easy, I respond by updating the button's text property with a concatenation of the date picker selection... But...

I've got this:

```html
<Button col="0" (tap)="toggleControl('date')" text="{{ data.date.day }}/{{ data.date.month }}"></Button>
<DatePicker day="{{ data.date.day }}" month="{{ data.date.month }}" year="{{ data.date.year }}" *ngIf="control === 'date'"></DatePicker>
```

How do I get the selection change?

**Comment by maddes** [comment]
Using 
```html
<DatePicker [(day)]="data.date.day" ... >
```
triggers a `Expression has changed after it was checked. Previous value:
'24'. Current value: '[object Object]'.` when showing the picker.

(24 being the initial value I set on the controller's definition)

**Comment by maddes** [comment]
Very hacky solution:

```html
<DatePicker [(day)]="day" ... >
```

```ts
export class MyComponent {
  private _day = 24 // Initial value

  get day():any {
    return this._day
  }

  set day(event: any) {
    this._day = event.value
  }
}
```
The event object has: 
```js
{
        eventName: 'dayChange'
        propertyName: 'day'
        object: DatePicker(125)
        value: 27
}
```

This manual event handling should not be necessary…

**Comment by NickIliev** [comment]
There are `change` events that can be used for the exposed properties (day, month, year, date) - documentation article [here](https://docs.nativescript.org/ui/components/date-picker#events)
