### ISSUE TITLE
Debug mode stops code execution without breakpoints.

### ISSUE THREAD

**Issue by Premitium** [NativeScript/NativeScript#1885]
Hey I am running {N} 1.5.2 (I cannot update to a newer version because of a plugin that we are currently using) and whenever I start the app with tns debug android the node debugger runs in chrome and stops at different places where there are no breakpoints. It slows down everything! 

Anyone had the same issue?

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#415
