### ISSUE TITLE
SearchBar - textFieldHintColor doesn't apply on the search icon - Android

### ISSUE THREAD

**Issue by guillaume-roy** [NativeScript/NativeScript#1889]
In my application, i'm using a SearchBar component.
I want to set a dark background and so, a light text hint color.

But when i use the textFieldHintColor property. Only the hint text is setted and not the search icon.

* Here is my code : 

`<SearchBar hint="Hint Text" id="searchBar" textFieldHintColor="#FFFFFF" style="color:#FFFFFF;background-color: #795548;height:60" />`

* Here is the UI : 

![search-bar](https://cloud.githubusercontent.com/assets/2191489/14285801/275224be-fb4d-11e5-9c24-09494aa2a167.png)

* Informations : 

tns version : 1.7.1
tns-core-modules : 1.7.1
tns-android : 1.7.1

**Comment by tsonevn** [comment]
Hi @guillaume-roy, 

Thank you for your issue.
Unfortunately the searchbar icon is an image and its color can not be change. 
With textFieldHintColor property you can change only the hint text color.  
This is something android specific.
You create your own searchbar by using gridlayout. I am attaching sample code.
```
<GridLayout columns="*, 6*" rows="auto, *">
	<ContentView  style="background-color: #795548;"></ContentView>
    <Image src="~/res/icon" col="0"  row="0" style="color:#FFFFFF; background-color: #795548;height:20;"/>
	<TextField textFieldHintColor="white" hint="hint" col="1" textAlignment="left" row="0" style="color:#FFFFFF;background-color: #795548; border-color:#795548;height:60;width:100%;"/>
    <Image src="~/res/clearicon" col="1" row="0" style="height:60;" horizontalAlignment="right" tap="clear" id="imageClear"/>   
</GridLayout>
```
I hope this is applicable for you.
Kind regards

**Comment by guillaume-roy** [comment]
I'll try with that. Thanks
