### ISSUE TITLE
CSS processor should ignore px/em instead of ignoring the entire property

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/NativeScript#1890]
Currently if a property has a size with em/px, the value is ignored entirely. It would be great if just the em/px was ignored. For example: font-size: 42px would still be rendered in {N} as font-size: 42.

**Comment by rdlauer** [comment]
Looks like I gave a bad example, as this seems to be supported with font-size. In my case it was border-width and border-radius that weren't supported.

**Comment by enchev** [comment]
Merged with https://github.com/NativeScript/NativeScript/issues/53
