### ISSUE TITLE
Set Button color style is no working

### ISSUE THREAD

**Issue by xuezier** [NativeScript/NativeScript#1891]
Here is the main.xml Code:
`

    <x:StatusBar ios:barStyle="light" android:barStyle="#f05b72" />
    <StackLayout>
        <Image src="~/views/imageSource/login.png" />
        <Button tap="jump" text="mainButton" class="mainButton" id="mainButton">
        </Button>
    </StackLayout>

`

Here is the main.css Code:
` Button {
    margin-top: 50pt;
    height: 70px;
    background-color: #d71345;
    width: 85%;
    border-radius: 35;
    border-width: 0.1;
    color:#ffffff;
}`

but the Button text is not showing white.

**Comment by xuezier** [comment]
And fon-size,font-style both no working on Button

**Comment by xuezier** [comment]
@hdeshev

**Comment by xuezier** [comment]
no one can help me? it's seems to the theme causes the problem.
`android:theme="@style/AppTheme"`
Are there any other themes to choose from?

**Comment by NickIliev** [comment]
@xuezier  Indeed this is and active issue and currently **color **and **font-size** are not applying on **Button** in Android.
As a temp workaround you can set one of the following themes iin manifest.xml

`android:theme="@android:style/Theme.Holo"
android:theme="@android:style/Theme.Holo.Light"
android:theme="@android:style/Theme.Black"`

**Comment by NickIliev** [comment]
css **color **and **font-size** are not applying on **Button**

**Comment by xuezier** [comment]
Yes, I have tried to use those Themes,But it's causes another problem:
`
G:\NativeScript\sample-Groceries\platforms\android\build\intermediates\manifests\full\debug\AndroidManifest.xml:26:24-42 : AAPT: No resource found that matches the given name (at 'theme' with value '@style/Theme.Black').
`

**Comment by NickIliev** [comment]
@xuezier 
In your AndroidManifest.xml (App_Resources >> Android >> AndroidManifest.xml )
you should change the existing key android:theme to one of the selected themes like 
`android:theme="@android:style/Theme.Holo"`

by the way Theme.Holo is a theme that will bring you white color set for the buttons.(and darker background)

**Comment by xuezier** [comment]
@NickIliev 
```
android:theme="@android:style/Theme.Holo"
android:theme="@android:style/Theme.Holo.Light"
android:theme="@android:style/Theme.Black"
```
they are works,but the Action can not hide by
actionBarHidden="true"`

**Comment by xuezier** [comment]
Ok, I can use 
`android:theme="@android:style/Theme.Holo.NoActionBar"`
to hide the action bar.


The rest of the problem is How to hide status bar or change status bar background-color

**Comment by NickIliev** [comment]
To remove the action bar you can use the sub-theme .NoActionBar
for example : 
`android:theme="@android:style/Theme.Holo.NoActionBar" >`

**Comment by xuezier** [comment]
`android:Theme.Material.NoActionBar`
can use custom status bar

**Comment by NickIliev** [comment]
related to [#1902](https://github.com/NativeScript/NativeScript/issues/1902)

**Comment by simranraza** [comment]
var nativeButton = new android.widget.Button(args.context);
    nativeButton.setText("Test Button");
    nativeButton.setTextSize(42);
    nativeButton.setBackgroundColor(someColor)
    nativeButton.setTextColor(whiteColor);
    nativeButton.setWidth(10);

setWidth method for android button is not working, any solution for this?
