### ISSUE TITLE
Closing modal makes the parent's observableArray flicker

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#1892]
Only tested on iOS. If I have a list displayed from an observable array and open a modal within this view, the list will flicker when I close the modal.

Also noted, if you try to update this observable array within the modal and then close the modal, the array is not updated even though it "flickers". I thought the flicker was because of the view getting refreshed, but that is not the case.

**Comment by tsonevn** [comment]
Hi @NordlingArt,  
I was not able to recreate this issue in a local project. Could you give me more info about this issue.
It would help if we could give me a a sample project, which recreates the problem.
