### ISSUE TITLE
TabView selectedIndexChanged fires on load, before any other event

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#1898]
This is a tricky one. First I must say that this does not happen while running the app via: Simulator or  when connected to a device (iOS). I even ran the app to a device with the '--release' flag, still no issues, app runs normaly. 

But, when packaging the app and uploading it to iTunesConnect, and running it from TestFlight (internal), the app crashes on launch. By reading the logs, I found out that it has something to do with my main-view (it contains a TabView). 

After a bit of testing, I realised that the TabView event ```selectedIndexChanged``` fires (on its own?) before app is loaded/initialized. But you don't see it while in debug ("--release" flag not working?). 

I had some code innside that event that used some modules (google-analytics and some others), this made the app crash on load since it tried to run the code, before the modules where fully loaded. 

I do not understand why this event runs on load, it should not be fired on its own. (I checked the code I do not set the selectedIndex anywhere in code). 

At least make it run after the "page loaded" event... 

CLI: 1.7.1
Cross-platform modules: 1.7.1
Runtime(s): iOS 1.7.0, Android 1.7.0

**Comment by tsonevn** [comment]
Hi @manijak,
Could you verify , whether this  problem is reproducible  with latest CLI and modules? If this is still valid issue, it would help if you send us sample project, which could be debugged locally.

Regards,
@tsonevn

**Comment by Cateye82** [comment]
I think i have a similar problem:
https://stackoverflow.com/questions/43373272/nativescript-angular-tabview-binding
I tried it within the "onSelectedIndexChanged" Method using a timeout and it worked.
