### ISSUE TITLE
No suport for ubuntu touch

### ISSUE THREAD

**Issue by carakas** [NativeScript/NativeScript#19]
There is no support for ubuntu touch, should be possible I think

**Comment by pitaj** [comment]
This would be nice. Maybe if the devs created a guide or something for how to add platforms to the compatibility, people could do so themselves.

**Comment by dtopuzov** [comment]
Support for Ubuntu touch is still not planed, but if demand increases we will reconsider it.

**Comment by listepo** [comment]
+1
