### ISSUE TITLE
Css text properties not applying on Button when no other text-element is used in page

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#1902]
When trying to set **color** , **font-size** , **font-weight** and **font-style** on **Button** styles are not applied if no other text-based element is used (Label, TextField, ect.) in the current xml file. 
All other css-properties are working.

_Example:_

in app.css (or main-page.css)
```
Button {
    color:red; 
    font-style:italic;
    font-size: 50;
    font-weight: bold;
}
```

in main-page.xml
```
<!-- in this case Css works
<Page xmlns="http://schemas.nativescript.org/tns.xsd">
  <StackLayout>
    <Label text="Tap the button" />
    <Button text="TAP" tap="{{ onTap }}" />
  </StackLayout>
</Page>-->


<!-- here Css doesn't work
<Page xmlns="http://schemas.nativescript.org/tns.xsd">
  <StackLayout>
    <Button text="TAP" tap="{{ onTap }}" />
  </StackLayout>
</Page>-->

```

related to [#1891](https://github.com/NativeScript/NativeScript/issues/1891)

**Comment by hamorphis** [comment]
I will take a look....

**Comment by hamorphis** [comment]
If there is no TextBase on the Page, the TextBaseStyler.registerHandler method was never called because the file it is called from was never required.
