### ISSUE TITLE
Unable to navigate one page to another page while navigation get interrupted?

### ISSUE THREAD

**Issue by katturajam** [NativeScript/NativeScript#1907]
Unable to navigate one page to another while navigation get interrupted.

While navigating a page to another page phone get locked when get unlocked app is navigating to success. Here i am trying to call navigation block and I am getting message Navigation Scheduled. 

There is no option to clear navigationQueue when it get's interrupted.

**Comment by NickIliev** [comment]
Hello @katturajam 

We were unable to reproduce your case - can you please provide sample code that can reproduce this issue and also some more specifics about the used platform and used version of {N} and CLI.
Thanks in advance!

**Comment by faizmh** [comment]
after enabling the trace, we are getting "Navigation Scheduled". however the navaigation doesnt take place. This seem to happen in nexus,oneplusone. But work on samsung phones
