### ISSUE TITLE
TextWrap of button  will change the uppercase/lowercase of the text

### ISSUE THREAD

**Issue by dreambo8563** [NativeScript/NativeScript#1909]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

## Please, provide the details below:

if you assign textWrap to be true, the text will be lowercase.

### Which platform(s) does your issue occur on?
iOS/Android/Both

I just android

### Please tell us how to recreate the issue in as much detail as possible.

` <Button #btn (tap)="btnTap($event)" [text]="btnText" textWrap="true">test for wrap</Button>`

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

my dev envrionment is nativescript with angular2. 

I think, the prop textWrap shouldn't affect the format of the text

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-angular#223
