### ISSUE TITLE
Extend the set of support CSS properties in {N}

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#191]
Currently we have a limited set of [CSS style properties support](http://docs.nativescript.org/styling) and we are planning to extend the list of supported properties with our next releases.

Please comment below what additional properties you would like to see supported as part of {N}.

**Comment by vakrilov** [comment]
Properties related to backgrounds:
 * `background-position`
 * `background-repeat`

And some font properties:
 * `font-family`
 * `font-style`
 * `font-weight`

**Comment by bundyo** [comment]
These would be nice in no particular order:
* inherit/initial/default
* overflow/-x/-y
* box-shadow
* border (current XML element is rather strange, maybe the element can be automatically wrapped with it upon encounter of this property?)
* background-size
* left/right/top/bottom with width/height auto for absolute layouts? Width and height can't help much when the View changes its size.
* text-transform/text-decoration
* text-shadow
* transform?

Low priority, for bling mostly:
* [filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter)
* @supports() type of queries

**Comment by RangerMauve** [comment]
Would Flexbox ever be considered, maybe using Facebook's existing [css-layout](https://github.com/facebook/css-layout) code? As I understand it, however. The absolutely positioned css wasn't considered because it it'd require NativeScript to implement its own layout engine.

**Comment by emiloberg** [comment]
Not so much a property as a value: Sizes (width/height) as percentages

**Comment by jlooper** [comment]
I would really like to have background-image property options supported, especially  no-repeat and -x/-y. This is a showstopper for an app I'm working on now.

**Comment by bundyo** [comment]
Also, when adding support for background-position, please consider the little known right/bottom offset positioning, for instance:

    background-position: right 10px bottom 20px;

**Comment by emiloberg** [comment]
`font-weight` because currently the only way of setting font-weight is
```
        <Label>
            <Label.formattedText>
                <FormattedString>
                    <FormattedString.spans>
                        <Span text="My bold text" fontAttributes="Bold" />
                    </FormattedString.spans>
                </FormattedString>
            </Label.formattedText>
        </Label>
```

Or am I missing something?

**Comment by manijak** [comment]
What about state-selectors? To be able to style pressed or hover effects? 
```css
button:pressed{
  background-color:#FED700;
}
.mybutton:pressed{
  background-color:#FED700;
}
```

**Comment by alejonext** [comment]
@manijak seudo-class

**Comment by emiloberg** [comment]
I don't know if you've a plan set for solving animations. One way to do it would be to transpile the `transform` and `transition` properties into something the mobiles understand

**Comment by mdgiles** [comment]
Agree with @bundyo that having Border element as xml is strange. It also prohibits different styling for different sides of the border which are necessary eg: 
border-top-width, 
border-bottom-width

and so on for left and right, and other suffixes style and color.

**Comment by mdgiles** [comment]
+1 @emiloberg sizing (widths / heights) as percentages are needed.

**Comment by nemephx** [comment]
I need `font-family` and `font-weight` asap :)

**Comment by sharesoft** [comment]
It would be really useful to assign multiple styles to a single item (as you can when using CSS with browsers). In the example below, all of the CSS rules for style1 AND style2 would be merged and applied to the Label:

<Label text="{{ Message }}" cssClass="style1 style2" />

**Comment by sharesoft** [comment]
Oops, here's the example...
Label text="{{ Message }}" cssClass="style1 style2"

**Comment by sharesoft** [comment]
It would be useful if you could specify different border-radius values for each corner as you can with CSS in browsers. For example: corner-radius="3 0 0 3"

**Comment by EvanWieland** [comment]
<code>::before</code> and <code>:: after</code> are really useful.

**Comment by bradmartin** [comment]
fonts, borders, and psuedo selectors for buttons would be great. Currently, on Android there is no indication the button is 'active' or 'pressed'.

**Comment by vakrilov** [comment]
@manijak @bradmartin There is a separate issue(#50) about pseudo selectors.

**Comment by emmanuelbuah** [comment]
How about flexbox layout as layout engine?

**Comment by valentinstoychev** [comment]
@emmanuelbuah flexbox is definitely possible. Where do you see it adding more value compared with our current layout implentation?

**Comment by emmanuelbuah** [comment]
@valentinstoychev Its widely known/used since its part of the css 3 spec. It will make it easy for developers coming from the web tech to get up and running rather than learn a new layout engine. This by no means assert that the current layout engine is bad. I just think adaptation will be faster and easier for devs coming from js/web tech.

**Comment by toddanglin** [comment]
Is the CSS `content` property being evaluated, too?

Would be useful as a way to change text/font icons via CSS classes. Example:

`.myClass{
   content: '&#xf09f';
   color: #000;
}`

**Comment by t1amat9409** [comment]
@toddanglin 

Check this link

https://docs.nativescript.org/ui/icon-fonts

**Comment by bundyo** [comment]
The CSS content property is only valid for before/after pseudo elements and I'm not sure of the viability of pseudo-elements in NativeScript.

**Comment by toddanglin** [comment]
@bundyo That makes sense. I hadn't thought about the complexity of supporting the pseudo elements. Worth some extra thinking.

The scenario I was after was the ability to use CSS (only) to change icons in a button. Something like:

```
.btn { font-family: 'Ionicons'; }
.play { content: '\uf33b'; }
.pause { content: '\uf34b'; }

<button class="btn play" />
```
Using this approach, you could just add/remove CSS class to change icons. Absent this support, some JavaScript is required to manually change the "text" property of the button. I'm doing it today with converters, but CSS class would be more elegant/web familiar.

If pseudo elements cannot be supported in NativeScript, maybe this is an edge case that justifies allowing the `content` property in NativeScript to set an element's "text" property (if available)?

**Comment by michaelsterpka** [comment]
I know this is an older issue, but I would love to see :hover and button animation features if possible. Being able to use a similar css style like that of Angular4 would make my day!

**Comment by vakrilov** [comment]
Hi @michaelsterpka Can you please elaborate more on those features and properties and in what cases you would want to use them. For example - on a mobile device there is rarely a mouse pointer so `:hover` is hard to achieve.

**Comment by jamezilla0** [comment]
@vakrilov :hover = :tap in my opinion as when I set the :hover pseudo selector for web apps, it automagically gets converted to a tap trigger when viewing from mobile.

**Comment by toddanglin** [comment]
@dhoffens The most direct way to do that kind of formatting in {N} today is to use data binding "expressions" (or "converters" if you're using Angular). Here are some docs on the topic:

https://docs.nativescript.org/core-concepts/data-binding#using-expressions-for-bindings

If you're using Angular with {N}, follow this guidance instead:
https://docs.nativescript.org/core-concepts/angular-data-binding#data-converters

In both cases, these techniques let you modify the presentation of model without changing the actual values. Hope this helps.
