### ISSUE TITLE
TimePicker minHour, maxHour are throwing exception when hour is out of their range

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#1916]
When we have set minHour or/and maxHour and the user picks a hour smaller/larger then the pre-set limitations we are throwing an exception.

For example:
```
<TimePicker hour="5" minute="30" minHour="3" maxHour="7" />
```
This will create a time picker with all possible hours
and will throw exception when hour is smaller then 3 and larger then 7

> Error: Hour property value (02:00) is not valid. Min time: (03:00), max time: (07:59).

**Comment by niyazhussain** [comment]
I am facing the same issue in IOS, please tag me once fixed.

**Comment by Macarthurval** [comment]
Still the error in iOs when changing hour and falling out of the range by minutes gilt.

Example: 

max: 09:00
current: 08:30
move a hour forward: 09:30

It crash instead of autoadjust to 9:00.

**Comment by Dagrut** [comment]
Same error here...
Is there a workaround? I tried setting the value myself with hour/minute or with v-model after a change event, but nothing works :disappointed:
