### ISSUE TITLE
Modal fires closeCallback when Back Button is pressed

### ISSUE THREAD

**Issue by guillaume-roy** [NativeScript/NativeScript#1917]
* Description

When i open a modal page, if i press back button or i tap on the gray background, the modal is closed.
But it fires the `closeCallback` function and i loose my previous selection.

* Project : 
[modalIssue.zip](https://github.com/NativeScript/NativeScript/files/210431/modalIssue.zip)

* Steps to reproduce : 
  * Open modal page, select an item. it's saved in the main page => OK
  * Re-open the modal, the selection is keeped => OK
  * Close the modal by pressing back button or tap in gray background, the selection is lost => KO

It's really painful in the case of i would like to open the modal just to check my selection (if not displayed in the main page).

* Technical informations :
  * tns-core-modules 1.7.1
  * tns-android 1.7.1
  * Windows 10

Thanks :+1:

**Comment by vjoao** [comment]
Why can't you just put 

```
if(item)
    createViewModelModule.setSelectedItem(item);
```

on the modal close callback?

**Comment by guillaume-roy** [comment]
In this example, i'm ok with you, i could do that to solve the problem.

But in a real project, the fact that `item` is `null` or `undefined` is a valid return result which is different than just closing the modal.

**Comment by vjoao** [comment]
The callback is acting as it should, being called when the modal closes. You have to implement the logic behind the closing functionality.
