### ISSUE TITLE
can not run aap on device with android version 4.4

### ISSUE THREAD

**Issue by xuezier** [NativeScript/NativeScript#1918]
I have a mobile device with android version 5.1.1.
app works fine on this device.
but the app could not run on another device with android version 4.4.4.

![image](https://cloud.githubusercontent.com/assets/7692708/14394312/42315198-fdfe-11e5-9241-11b7ecb49159.png)
![image](https://cloud.githubusercontent.com/assets/7692708/14394332/4ddb1dd0-fdfe-11e5-9a38-58cad8f25259.png)
![image](https://cloud.githubusercontent.com/assets/7692708/14394339/55d4cfe0-fdfe-11e5-8b06-c6bff172f952.png)
![image](https://cloud.githubusercontent.com/assets/7692708/14394345/5a3df160-fdfe-11e5-93c9-3ec1b6e3c399.png)
![image](https://cloud.githubusercontent.com/assets/7692708/14394349/5d730b22-fdfe-11e5-888d-a68b99747e2e.png)

**Comment by xuezier** [comment]
@hdeshev do not support low android version?

**Comment by enchev** [comment]
Can you provide more info about your app?

**Comment by vjoao** [comment]
This is probably a `"res://"` type of error. Some resources are not available on older android versions causing this crash.

**Comment by NickIliev** [comment]
Hey @xuezier can you verify if chaning resources paths from `"res://icon"` to using a app folders like `"~/images/logo.png"` has solved this problem!?
