### ISSUE TITLE
How ignore invalid self-signed ssl certificate in nativescript

### ISSUE THREAD

**Issue by badlee** [NativeScript/NativeScript#1919]
HI,

I want send request to my https server (local network), but the request fails because the SSL certificate is self signed. How ignore invalid SSL certificate with nativescript?

```JS
{
    tns : "1.7.1",
    platform : "Android",
    tns-android : "1.7.1",
    tns-core-modules : "1.7.1"
}
```

**Comment by enchev** [comment]
Hey @badlee,

You can try [this approach](https://gist.github.com/aembleton/889392) - ping me if you need help translating the code to {N}!

**Comment by TeddyBo** [comment]
I've faced the same problem but I have no idea how to translate this solution to {N}. Any help?
Thanks

**Comment by badlee** [comment]
@TeddyBo [this approach](https://gist.github.com/aembleton/889392) has resolved my problem.

**Comment by bferreirainfo** [comment]
how can i implement the above approach? i cant understand where should i put this code, and where to call it...

**Comment by sm1ddy** [comment]
Can anyone please provide guidance for this in Nativescript?

It's not clear were the provided code snippet should be used.
