### ISSUE TITLE
After tns test init, Android fails compilation (gradlew exit code1), iOS (simulator) application killed (9)

### ISSUE THREAD

**Issue by dragGH102** [NativeScript/NativeScript#1920]
**Is this a real issue?**
While I didn't find the very same issue, I looked in SO, {N} repo as we well as related projects (cordova etc) and turns out that at least in the case of gradlew / aapt there are still many issues to be solved.

The issue (explained below) is resolved after uninstalling testing-related dependencies (I chose **MochaJS** as testing framework) by

> npm uninstall chai karma karma-chai karma-mocha karma-nativescript-launcher mocha nativescript-unit-test-runner

Unfortunately I can't provide the used code (for now) even it was just for testing, as it was part of private project. Should I be allowed to publish it later on I will.
I hope the following explanations help to figure out what's wrong.

**The issue**
The issue is that, after **tns test init** a number of dependencies and "sub-dependencies (nativescript-test-runner, karma, karma-chai, mocha, ...) are installed.

The error is explained in detail below.
Before reporting the error I updated to the latest version of Nativescript (both cli and runtime including remove/add platform android/ios). + installed/updated Google Repository, Android support library+repository, Android SDK Tools + Platform tools.
Android was tested on Linux (Debian 8), iOS in simulator (XCode 7.2 - Os X Yosemite .4).

**Android**
gradlew --> aapt to fail

```
com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'android-sdk-linux/build-tools/23.0.2/aapt'' finished with non-zero exit value 1
BUILD FAILED
Total time: 25.225 secs
Command %project_root%/platforms/android/gradlew failed with exit code 1

```
When I run **.../gradlew** manually it says "BUILD SUCCESSFUL" instead. However when I run **tns deploy android** it builds it over (shouldn't be done only by tns **build/run/livesync** ?) and same error pops up

Now, in the case of **Android** it seems aapt 23 is used even though I update sdk tools to 25 (but yes, platforms tools latest version is 23). Can this be the issue? if so, how to change default target sdk / aapt?

Furthermore I noticed that once the test dependencies are installed I get several messages (in yellow) during compilation, such as:

> The dependency located at %project_root%/node_modules/log4js/node_modules/readable-stream with version  1.0.33 will be replaced with dependency located at %project_root%/node_modules/readable-stream with version 2.0.6

It may also be interesting to notice that if I build the project without testing dependencies, then remove them and then run **tns livesync android --watch** (instead of tns run) the changes are synced with no compilation issue. However the issue comes back when building the project without livesync.

**iOS**

Compilation goes fine but then the application is killed by simulator with exit code 9 (apparently memory overflow).
As a last test I try to reinstall the test dependencies by

> npm install chai karma karma-chai karma-mocha karma-nativescript-launcher mocha nativescript-unit-test-runner

and on iOS (not Android) this apparently solved the issue.

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#1673
