### ISSUE TITLE
Updating an object within Observable Array will not update the UI until refreshing the whole list

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#1923]
I have a list of around 50 items within a ScrollView. There is a checkbox to the right which means whenever I tap the list item, it is supposed to update the corresponding checkbox. This works within the Observable Array, of course. But the UI will not see the change until I have done a refresh() of the Repeater view that holds the list of items. Since I have around 50 items, this means there is a 10 second delay each time I tap an item in order for the checkbox to appear checked.

Is there a way to update the Repeater in the UI, but only the actual element that is bound to the object's property within the Observable Array?

The Observable Array looks like this, with each item as an object:

```
var testList = new observableArray([
  {
    id: 1,
    title: "Test 1",
    checked: false
  },
  ...
]);
```

Upon tapping the item in the list, the "checked" property changes to **true**. The UI will however not update this unless I refresh the whole list (with a delay of 10 seconds due to excessive amount of items being reloaded):

`page.getViewById("testList-repeater").refresh();`

Is it possible to even fix this? The documentation says nothing about it except that pushing a new item will update the UI, which is not what I'm trying to achieve.

You can test it from this Git: https://github.com/NordlingArt/tns-testList

This has only been tested on iOS, but I assume it's a global issue for all platforms.

**Comment by vjoao** [comment]
Have you tried making each item Observable?

**Comment by NordlingArt** [comment]
@vjoao Interesting idea. How would I achieve that?

I supposed I can't do it this way:

```
var testList = new observableArray([
  new observable({
    id: 1,
    title: "Test 1",
    checked: false
  }),
  new observable({
    id: 2,
    title: "Test 3",
    checked: false
  }),
  ...
]);
```

**Comment by phattranky** [comment]
@NordlingArt  Thanks

It's working with me. BTW, i only got this issue on Android. iOS working well without do anything

**Comment by mutazmq** [comment]
When I make each item an observable, I'm not able to bind it anymore to my template elements. In this example, `item.title` is undefined. How can I bind the array items to my template elements when they are all observable?

```
        <ListView [items]="testList" class="list-group" *ngIf="testList">
            <ng-template let-item="item">
                <Label [text]="item.title"></Label>
```
