### ISSUE TITLE
appSettings.clear() not always clearing every property

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#1925]
There is something strange going on with my appSettings that makes it impossible for me to continue working on my project. I have around 6 appSettings properties:

- notFirstTime
- user_id
- user_email
- user_password
- user_displayname
- user_avatar

When they're all set, I try to clear them using `appSettings.clear()`. After I've done that, I `console.log()` every single one, but some properties (it's random with every try) are still there with their values.

I cannot reproduce this bug in a new project. I believe there is something weird going on with my project. Maybe because of the size of the project make things lag? FYI, this is on iOS.

I have a `frameModule.topmost().navigate()` right after `appSettings.clear()`:

```
appSettings.clear();
frameModule.topmost().navigate({moduleName: "views/main/main"});
```

 Could there be so that all properties in appSettings haven't been clear yet before it starts redirecting to the new view? If so, how can I prevent this from happening? Is it possible to attach a `then()` method after `appSettings.clear()` has finished?

EDIT: It seems like it "works" when I wrap the `navigate()` inside a `setTimeout()` with a delay by 2 seconds. 1 second seems to be too little. It definitely feels like `clear()` is slow to finish.

**Comment by enchev** [comment]
Hey @NordlingArt,

Here is what we do to clear all values:
https://github.com/NativeScript/NativeScript/blob/master/application-settings/application-settings.ios.ts#L64

You can try removing value by value using [this approach](http://stackoverflow.com/a/6797133/245513) in your case to see if it will work.

**Comment by NordlingArt** [comment]
@enchev Thanks for the links. Your second link I have no idea how to implement since it's not JS. Any guidelines to how I do this?

**Comment by enchev** [comment]
Porting ObjC to {N} JavaScript is very easy. For example:
```ObjC
    NSUserDefaults * defs = [NSUserDefaults standardUserDefaults];
    NSDictionary * dict = [defs dictionaryRepresentation];
    for (id key in dict) {
        [defs removeObjectForKey:key];
    }
    [defs synchronize];
```

```JavaScript
    let defs = NSUserDefaults.standardUserDefaults();
    let dict = defs.dictionaryRepresentation();
    for (let key of dict) {
        defs.removeObjectForKey(key);
    }
    defs.synchronize();
```

You can check also our docs for more info about the iOS runtime:
http://docs.nativescript.org/runtimes/ios/Overview

Right now we are using different approach for clear (check my first link) and I've suggested to check if the second approach (with the manual loop) will work in your case.

**Comment by NordlingArt** [comment]
Hi @enchev,

I've checked your alternative method and yes it might work. However, I have come to realize that there is a much deeper issue that I have. It is very random which keyss in appSettings that are being loaded during app launch.

Basically, this is what I am doing with my app's start page (main.js):

```
// Check whether "user_id" is set or not
if(!appSettings.hasKey("user_id")) { // If there is no key for "user_id", navigate to login view
  frameModule.topmost().navigate({
    moduleName: 'views/login/login',
    transition: { name: "fade" },
    clearHistory: true
  })
} else { // Otherwise, navigate to feed view
  frameModule.topmost().navigate({
    moduleName: 'views/feed/feed',
    transition: { name: "fade" },
    clearHistory: true
  });
}
```

Sometimes, "user_id" has not YET loaded (and of course various of other keys). This has mostly to do with the performance of the computer or device I'm testing at. For instance, if I have a Skype call on with screen sharing, my Mac is running more slowly and as a result I get this problem because the if statement is being called more or less at the same that the app settings keys are being loaded. Hence the script above sends me to the wrong view.

Now, is there anything I can do about that? Like I said, it would've been nice with a Promise method. Though I have not much experience with Promise, so I understand if that is not a possible solution.

**Comment by NordlingArt** [comment]
Closing this issue as I am opening up a new one with more relevant information: #2061
