### ISSUE TITLE
HtmlView displaying white URL's on android 4.2, 4.3, 4.4 and 6.0

### ISSUE THREAD

**Issue by Metalmate** [NativeScript/NativeScript#1926]
When using the HtmlView, all the links are displayed in white text-color. This is not a problem when using the WebView, or using the HtmlView on any version of iOS, or Android 5.1.1.

 I haven't tested this on android 5.0

Error occurs in: Android 4.2, 4.3, 4.4 and 6.0

Version of NativeScript CLI: 1.7.0

**Comment by tsonevn** [comment]
Hi @Metalmate , 
I tested this issue in a local project, however it seems that HtmlView links are not displayed in a white color in it. It would help if you could give me more info how to replicate this behavior or to send us sample project.

**Comment by Metalmate** [comment]
I came to the conclusion that we had the falowing line in our App_Resources/Android/values=v21/styles.xml: <item name="colorAccent">#FFF</item>

This changed the colors of the links in a HtmlView to white on the platforms specified above. Therefore I will close this "issue".
