### ISSUE TITLE
WebView does not load web pages on Api18

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#1928]
WebView does not load web page on Api18 until you tap on it.

Sample page:
```
<?xml version="1.0" encoding="UTF-8" ?>
<Page>
  <WebView margin="10" url="http://www.telerik.com/nativescript"/>
</Page>
```

This worked as expected for the last time in the CI on Mar 30, 2016 5:33 AM.
This issue appeared for the first time in the CI on Mar 31, 2016 7:47 PM.

**Comment by enchev** [comment]
Works with google so it must be something with the page itself:
```XML
<Page>
   <WebView src="http://www.google.com" />
</Page>
```
![untitled](https://cloud.githubusercontent.com/assets/5804953/14459511/00809450-00c1-11e6-8ede-cb2e9b20da88.png)

**Comment by enchev** [comment]
Here is actually what's causing this issue:
http://stackoverflow.com/questions/13500452/android-webview-renders-blank-white-view-doesnt-update-on-css-changes-or-html

The easiest workaround will be:
```XML
<Page>
  <WebView src="http://www.telerik.com/nativescript"/>
</Page>
```
```JavaScript
exports.loaded = function (args) {
    if (android.os.Build.VERSION.SDK_INT === 18) {
        args.object.android.setLayerType(android.view.View.LAYER_TYPE_SOFTWARE, null);
    }
}
```

Not sure if should put this

**Comment by enchev** [comment]
Ok. This is definitely related to #1899. I'm closing my pull request.
