### ISSUE TITLE
Feature Request: XML Import

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#1937]
### Did you verify this is a real problem by searching; 
Yes related would be the closed #1441 

### Tell us about the problem
I think having the ability to do 
\<TabView\>\<Import 'tab1.xml'/\>\</TabView\>\<TabView\>\<import 'tab2'xml'/\>\</TabView\>

Would be a useful feature.  We can do require in JS, and @ import in CSS to bring in code we need; but there is no real easy way to just import some xml into a part of the Declarative UI tree.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
Currently 1.7.x and below.

### Additional Notes
- Is this is something that would be considered for core, if so I might try and to do it.
- Is there any parsing of Declarative UI benchmarks available anywhere?

**Comment by vjoao** [comment]
+1

**Comment by enchev** [comment]
Hey folks,

You can do this even now with [XML based custom component](http://docs.nativescript.org/ui/ui-with-xml#custom-components): 
```XML
<Page xmlns:cc="some-component-folder-inside-app">
    <cc:SomeXMLFileNameWithoutExtension />
</Page>
```

**Comment by NathanaelA** [comment]
@enchev --- Awesome, I didn't realize that would work for a straight xml file to import into into the existing file.
