### ISSUE TITLE
UpdateTextTrigger not working

### ISSUE THREAD

**Issue by dreambo8563** [NativeScript/NativeScript#1938]
### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
updateTextTrigger didn't work for TextField

### Which platform(s) does your issue occur on?
iOS/Android/Both
Android

### Please tell us how to recreate the issue in as much detail as possible.
```xml
  <TextField  returnKeyType="done" updateTextTrigger="focusLost" hint="Email Address" id="email" text="{{ email }}" keyboardType="email" autocorrect="false" autocapitalizationType="none" />
```

No difference between focusLost and textChanged for `updateTextTrigger`

as I thought when I set it as "focusLost", the text won't update when typing. just display the text when lost the focus.

**Comment by tsonevn** [comment]
Hi @NordlingArt,
Thank you for reporting this issue. I've just tested given code snippet in sample app. 
Actually updateTextTrigger works correctly as it describe in the documentation,
When you use focuseLost, the text property wil be update when the widget loses focus and you use 
textChange, the text property will be update on every single character typed by the user. I am attaching sample code:

main-page.xml
```
<TextField  returnKeyType="next"  returnPress="focusPassword" hint="Email Address" id="email" text="{{ email }}" keyboardType="email" autocorrect="false" autocapitalizationType="none" />
   
<TextField  returnKeyType="done" updateTextTrigger="focusLost"  hint="pass" id="password" text="{{ password }}" keyboardType="password" autocorrect="false" autocapitalizationType="none" />
```
main-page.ts
```
import { Page } from "ui/page";
import {TextField} from "ui/text-field";
import   ENUMS = require ("ui/enums");
import {Observable} from "data/observable" 

var textFieldEmail:TextField;
export function loaded(args: EventData) {

    var page = <Page>args.object;
     var textFieldEmail:TextField = <TextField> page.getViewById("email");
     var textFieldPassword:TextField = <TextField> page.getViewById("password");
     
     textFieldEmail.updateTextTrigger= ENUMS.UpdateTextTrigger.textChanged;

    var observable = new Observable();

     observable.on(Observable.propertyChangeEvent, function (pcd) {
            console.log(pcd.eventName.toString());
            console.log("text property email "+textFieldEmail.text);
            console.log("text property password "+textFieldPassword.text)
           
         
    });
    page.bindingContext = observable;
}
```

I hope this information helps. I will be glad to assist you further.

**Comment by dreambo8563** [comment]
@tsonevn cool. thanks for your explanation, I misunderstand the doc. before I open the issue, I think the "won't update" means not to render the text on UI. Actually, it means update the value in your code
