### ISSUE TITLE
Navigation stops working after navigating with clearHistory and a transition

### ISSUE THREAD

**Issue by mobilemindtec** [NativeScript/NativeScript#1948]
Hi,

After navigate to page using clearHistory = true the navigation not work anymore. 

**Steps:**
1 - Open app
2 - Navigate to page two  using { clearHistory: false }
3 - Navigate to page one using { clearHistory: true }
4 - Navigate to page two again - navigaton not work anymore

I'm using last version android@next. This bug has been reported?

**Comment by tsonevn** [comment]
Hi @mobilemindtec, 
I tested this issue in a local project, however it seems that navigation works after clearing the history.
Could you test my project.
https://github.com/tsonevn/navigate_clearHistory-.git
I hope this information helps. I will be glad to assist you further.

**Comment by mobilemindtec** [comment]
Hi @tsonevn,

Your project worked, but I forgot a important detail.. I'm using transition.. change the page2 to:

```
export function back(){
    topmost().transition = { name: "fade" };
    topmost().navigate({
        moduleName:"main-page", 
        clearHistory:true
    })
}
```
so will stop work

**Comment by NickIliev** [comment]
The same issue was reproduced in Android API 19 (v.4.4.4)
Sample code to reproduce it : 
```
    var navigationEntry = {
        moduleName: "sub-page",
        context: context,
        clearHistory: true,
        transitioniOS: {
            name: "slideRight"
        },
        transitionAndroid: {
            name: "fade"
        }
    };
    
    topmost.navigate(navigationEntry);
```
