### ISSUE TITLE
Very low performances about navigation with clearHistory enabled on Android

### ISSUE THREAD

**Issue by guillaume-roy** [NativeScript/NativeScript#1952]
### Tell us about the problem

When i navigate from a view to another, it takes 2sec between the `frameModule.topmost().navigate()` and the `navigatedTo()` with the `clearHistory` enabled.
If i disable this feature, the navigation is immediate.

### Which platform(s) does your issue occur on?
Android 5.1

### Please provide the following version numbers that your issue occurs with:
- CLI: 1.7.1
- Cross-platform modules:1.7.1
- Runtime(s): tns-android 1.7.1

### Please tell us how to recreate the issue in as much detail as possible.

Create 2 views and navigate from one to another.
My source view is a form with about 10 fields.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Code used for raise navigation :

```
frameModule.topmost().navigate({
    animated: false,
    backstackVisible: false,
    clearHistory: true,
    moduleName: Views.main
});
```

**Comment by hshristov** [comment]
@guillaume-roy We did improve few things in the android-runtime as well as modules but they will be out in 2.0.0. So the easiest thing to try while waiting is to open `FragmenClass` and commend the utils.gc() call.

Let me know if this helps.

**Comment by guillaume-roy** [comment]
Thanks for this precision. 

Due to the fact that i have to publish my app in the PlayStore, i 'll wait the v2.0.0 stable release.
Do you have a releaseedate ?

**Comment by enchev** [comment]
Hey @guillaume-roy,

The release will be first week of may.

**Comment by guillaume-roy** [comment]
For now, i closed this issue.

When the v2.0.0 will be released, i'll re-try it and report here if it's ok or not.

**Comment by hshristov** [comment]
27 if all goes well.
