### ISSUE TITLE
Cannot change text color when value is true

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#1969]
I have an observable in which a certain property starts with `false` and turns into `true` from time to time.

```
var pageData = new observable({
  history = false,
  ...
});
```

pageData.history will change value during certain events in the view from `false` to `true`, and vice versa. In the XML I have a Label that should change text color depending on the value of `pageData.history`:

`<Label text="{{ pageData.history }}" color="{{ pageData.history ? '#000000' : '#cccccc' }}" />`

For some reason, the text will actively change depending on the value of `pageData.history`. However, the ternary inside the color property will not see this, thus keep having the same text color of `#000000`.

What is going on here?

**Comment by tsonevn** [comment]
Hi @NordlingArt , 
I tested given code snippet in sample app, however it seems that the property's value is changing correctly.
I am attaching link to the project repository:
https://github.com/tsonevn/BindingProperty_issue1969
It would help if you could give me more info how to reproduce this problem.

**Comment by NordlingArt** [comment]
@tsonevn - Found the issue. It works if you bind page.bindingContext directly to the observable, like you did:

`page.bindingContext = pageData;`

However, if I have multiple observables and other variables, I need to do it this way:

```
page.bindingContext = {
  pageData: pageData;
  ...
};
```

The UI can then only observe the text property and not color, and probably many other properties.

You can test it out from this branch: https://github.com/NordlingArt/tns-testList/tree/bindingProperty

**Comment by NordlingArt** [comment]
Update. I feel like the best way to do this is for me to reconsider my workflow and keep every variable that should be passed to `bindingContext`, inside the `pageData` variable instead. The way I do it now is not optimal, but I still think it should work considering that the text property does see change in the observable.

**Comment by tsonevn** [comment]
Hi @NordlingArt,
I confirm that this is a global issue. Temporary solution can be to set one more property to the observable array objects, which keeps class name value.

main-page.xml
```
<Page loaded="loaded">
  
  <GridLayout rows="*, auto, auto">
    
    <ScrollView row="0">
      <Repeater items="{{ testList }}" id="testList-repeater">
        <Repeater.itemsLayout>
          <StackLayout id="testList" />
        </Repeater.itemsLayout>
        <Repeater.itemTemplate>
          <GridLayout columns="*, 55" height="55" id="{{ id, 'id-' + id }}" tap="check">
            <Label col="0" text="{{ checked.valueChecked }}" />
            <StackLayout col="1" class="{{ className.name }}" />
          </GridLayout>
        </Repeater.itemTemplate>
      </Repeater>
    </ScrollView>
    
    <Button row="1" text="Push new item" tap="push" />
    <Button row="2" text="Refresh list" tap="refresh" />
    
  </GridLayout>
  
</Page>
```

main-page.js
```
var frameModule = require('ui/frame');
var observable = require("data/observable").Observable;
var observableArray = require("data/observable-array").ObservableArray;

var page;

var testList = new observableArray([
  {
    id: 1,
    title: "Test 1",
    checked:new observable({valueChecked: false}),
    className:new observable({name: "checkbox"})
  },
  {
    id: 2,
    title: "Test 2",
    checked:new observable({valueChecked: false}),
    className:new observable({name: "checkbox"})
  },
  {
    id: 3,
    title: "Test 3",
    checked:new observable({valueChecked: false}),
    className:new observable({name: "checkbox"})
  }
]);
 
exports.loaded = function(args) {
  page = args.object;
  
  page.bindingContext = {
    testList: testList
  };
};


exports.check = function(args) {
  var id = args.object.id.replace("id-", "");
  
  testList.forEach(function(value) {
    if(value.id == id) {
       if(value.checked.valueChecked == false){ 
         value.className.set("name", "checkbox-checked"); 
         value.checked.set("valueChecked", true);  
        }
        else {
          value.className.set("name", "checkbox"); 
          value.checked.set("valueChecked", false);
        } 
     }
  });
  
  console.dump(testList._array);
};

exports.push = function(args) {
  var lastinArray = testList.length - 1;
  var lastItem = testList.length;
  var newItem = {
    id: lastItem + 1,
    title: "Test " + (lastItem + 1),
    checked:new observable({valueChecked: false}),
    className:new observable({name: "checkbox"})
  };
  
  testList.forEach(function(value) {
    if(value.id == lastinArray) {
      testList.push(newItem);
    }
  });
  
  console.dump(testList._array);
};

exports.refresh = function(args) {
  page.getViewById("testList-repeater").refresh();
};
```
I am attaching your github link, which reproduced the problem. 

https://github.com/NordlingArt/tns-testList/tree/bindingProperty

**Comment by nsndeck** [comment]
@NordlingArt  I've checked your example and found a problem with your binding expression:

```XML
 <Label row="0" text="{{ pageData.history }}" color="{{ pageData.history ? '#73b94f' : '#e36262' }}" />
```
  
In general this expression will work for the first time and then on every change of the `pageData` property of the `Label.bindingContext`. The reason for this is that when only expression is passed for the binding declaration NativeScript internally uses bindingContext (or $value) as source property (which will be observed for changes). Therefore when you change `pageData` object there is no propertyChange listener attached and binding do not work correctly. Fortunately the fix is trivial and all you have to do is to set a proper `source property`. Your code should look like this:

```XML
 <Label row="0" text="{{ pageData.history }}" color="{{ pageData.history, pageData.history ? '#73b94f' : '#e36262' }}" />
```
As you can see I just added `pageData.history` as source property before binding expression.

**Comment by NordlingArt** [comment]
@nsndeck Oh... I got it. That is good to know. Though I started putting everything inside the pageData observable instead so that's the only thing bindingContext see. Anyhow, thanks for explaining!

**Comment by McDonal11** [comment]
@tsonevn Hi, Now I am facing the same issue. [Posted Question recently.](https://stackoverflow.com/questions/50577389/nativescript-listview-items-are-reusing-when-scrolling) I thought to do like that, by adding one more **key** as **Color** and changing respective index **Color** values. But, I am having only one doubt. I am getting datas from API. Each and every time, if I am facing same scenario, then do I have to add keys to that JSON?

**API:**
```
[
{
"name": "abc",
"age" : 12
},
{
"name": "qwe",
"age" : 15
},
]
```

**Customised API:**
```
[
{
"name": "abc",
"age" : 12,
"color" : black
},
{
"name": "qwe",
"age" : 15,
"color" : black
},
]
```

Is there any other way without customising api, we can achieve this ??
