### ISSUE TITLE
nativescript-geolocation 1.7.1 for ios is not compatible with the currently installed (1.7.0)

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#1987]
I am unable to to install nativescript-geolocation because of compatibility issues.

`tns --version` will show 1.7.1. tns-ios however is still 1.7.0. I tried upgrading using the instructions from https://docs.nativescript.org/releases/upgrade-instructions but to no avail.

**Comment by tsonevn** [comment]
Hi @NordlingArt, 
Thank you for reporting this issue,
Could you try to remove the platform using ```tns platform remove ios```, then upgrade tns modules - ```npm install tns-core-modules@latest --save``` and 
 then try to install the nativescript-geolocation modeule with the command ```tns plugin add nativescript-geolocation```.
I hope this information would be useful. If there is still a problem, I will be glad to assist you further.

**Comment by NordlingArt** [comment]
@tsonevn - Same thing unluckily. My package.json looks like this:

```
{
  ...
  "nativescript": {
    "id": "com.tradit.app",
    "tns-ios": {
      "version": "1.7.0"
    }
  },
  "dependencies": {
    "email-validator": "^1.0.4",
    "nativescript-geolocation": "0.0.9",
    "nativescript-screen-orientation": "^1.0.2",
    "tns-core-modules": "^1.7.1"
  }
}
```

`tns-ios` disappears when removing ios platform, as it should. I install tns-core-modules with your command and it appears as `"tns-core-modules": "^1.7.1"`. Also like it should. However, when adding ios platform back, it goes to 1.7.0. If I check the [iOS-runtime Git](https://github.com/NativeScript/ios-runtime), the latest version is in fact 1.7.0. But then why is android at 1.7.1? And why would nativescript-geolocation complain about the platform not being 1.7.1?

**Comment by tsonevn** [comment]
Hi @NordlingArt , 
I tried to recreate the abnormality, actually from the given package.json file content  it seems, that the plugin was successfully installed. However there is no reason for the conflict between `nativescript-geolocation` and `tns-ios version 1.7.0`.
It would help if you could give me more info about the given error.

**Comment by NordlingArt** [comment]
@tsonevn - I just realized now that the message that appears when I install nativescript-geolocation, is only a warning (First line, which is colorized in yellow):

```
nativescript-geolocation 1.7.1 for ios is not compatible with the currently installed framework version 1.7.0.
nativescript-geolocation@0.0.9 node_modules/nativescript-geolocation
Successfully installed plugin nativescript-geolocation.
```

I suppose it's an automatic message that displays. I should just ignore that for now.

Thanks for the help!
