### ISSUE TITLE
Error when invoking a method on Android due to changes in the Mapbox SDK

### ISSUE THREAD

**Issue by EddyVerbruggen** [NativeScript/NativeScript#1990]
Hi folks,

I was updating the [Mapbox plugin](https://github.com/EddyVerbruggen/nativescript-mapbox) for Android from [Mapbox GL](https://github.com/mapbox/mapbox-gl-native) 3.2.0 to 4.0.0 and may have found an issue in the metadata generator or Android runtime.

Mapbox has changed a lot of implementation details and I'm able to refactor the plugin accordingly except for one important item: `addMarkers` is broken because (I think) the NativeScript Android metadata generator chokes on the Java structure Mapbox now uses. Runtime error:

```
Error in mapbox.addMarkers: TypeError: markerOptions.title is not a function
```

In the 3.2.0 release the MapboxOptions class didn't extend anything and had [a method called `title`](https://github.com/mapbox/mapbox-gl-native/blob/fabc457adf04977bd73fd115b9e19383a89402f3/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerOptions.java#L109), but since 4.0.0 it extends BaseMarkerOptions and [`title` has moved over there](https://github.com/mapbox/mapbox-gl-native/blob/f3c64a4c95947768fd9a695744f9fe0965134c55/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerOptions.java#L32).

So in a regular Android app you should still be able to access the `title` method through the child class `MarkerOptions` but in a NativeScript app it seems to no longer be possible.

Not having Markers would be killing for this plugin so if we can't fix it here I'll contact Mapbox and ask them for a different class inheritance or method structure.. I would need to know what the exact cause is though, hence this issue.

### Reproduction:

- `git clone https://github.com/EddyVerbruggen/nativescript-mapbox-demo`
- `git clone -b mapbox-4.0.0 https://github.com/EddyVerbruggen/nativescript-mapbox` (to try the working old version just remove the `-b mapbox-4.0.0` stuff)
- `cd nativescript-mapbox-demo/Mapbox`
- run `tns install`
- In the demo app's package.json replace `"nativescript-mapbox": "1.1.2",` by `"nativescript-mapbox": "file:../../nativescript-mapbox",` so it refers to your locally cloned plugin
- In the demo app uncomment the line in `app/App_Resources/Android/AndroidManifest.xml` regarding `TelemetryServices`

Do a `tns run android`, browse to the second tab and press "show". That should draw a map.. if you now press "add markers" you'll see the error in the console.

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#424
