### ISSUE TITLE
Letter spacing is not working

### ISSUE THREAD

**Issue by karumurikiran** [NativeScript/NativeScript#1996]
I tried to give letter spacing, but it is not working.
Please see the below example,

.turbotext{
    color: white;
    text-align: center;
    letter-spacing: 5;
}

**Comment by enchev** [comment]
Can you provide more info about the platform, version of the platform, version of NativeScript and the type of component where this CSS is applied?

**Comment by karumurikiran** [comment]
Platform- Android,23
Version of the native script- tns 1.7.1
Component name- Label,button

**Comment by enchev** [comment]
I've just tested this and your are right! The issue however is already fixed and you can try our @next build like this in your app:
```
npm uninstall tns-core-modules
npm install tns-core-modules@next
tns run android
```
The official 2.0 release will be first week of may.

**Comment by karumurikiran** [comment]
Thank you for the reply.
It is working
