### ISSUE TITLE
Background Gradient

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#1997]
How to give Background Gradient in nativescript.

**Comment by NickIliev** [comment]
Hello @dhanalakshmitawwa 

For now background gradient in {N} can be achieved with native code implementation.
Good examples for both Android and iOS platforms are shown in this issue [#539] (https://github.com/NativeScript/NativeScript/issues/539) 
which is directly related to your problem

**Comment by NickIliev** [comment]
related to [#539](https://github.com/NativeScript/NativeScript/issues/539)
