### ISSUE TITLE
Support android hardware menu button

### ISSUE THREAD

**Issue by Metalmate** [NativeScript/NativeScript#2003]
Currently only the backButton is enabled. Add the menu button also.

Sample code for android:

@Override
public boolean onKeyDown(int keycode, KeyEvent e) {
    switch(keycode) {
        case KeyEvent.KEYCODE_MENU:
            doSomething();
            return true;
    }

```
return super.onKeyDown(keycode, e);
```

}

**Comment by manoldonev** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Thank you!
