### ISSUE TITLE
Can not require "node_modules" libs from files in /app sub-folders

### ISSUE THREAD

**Issue by hekigan** [NativeScript/NativeScript#2009]
### Which platform(s) does your issue occur on?
I only checked Android, I am not sure about iOS.
My OS is OSX 10.9.4
Using Typescript.

### Please provide the following version numbers that your issue occurs with:
**/package.json**
{
  "nativescript": {
    "id": "org.nativescript.myapp",
    "tns-android": {
      "version": "1.7.1"
    }
  },
  "dependencies": {
    "crypto-js": "^3.1.6",
    "lodash": "^4.0.1",
    "nativescript-telerik-ui": "^1.0.1",
    "tns-core-modules": "1.7.1"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "^0.3.0",
    "typescript": "^1.8.10"
  }
}

### Please tell us how to recreate the issue in as much detail as possible.
Basically, when I import **lodash** from a "/app/utils.ts" file, things work properly with a:

`export const _ = require("lodash");`

But, when writing the same thing in a sub-folder (ex: /app/models/my-model.ts), I can not load my lib.
I tried all combination of path (./, ./../, ../../, ../node_modules, etc...) to no avail.

So right now, I have to put all requires that are located in node_modules in a top file and then import that top file and import the exported variable which is not very clean and makes my structure awkward.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Just write the line below in an "/app" sub-folder's file (ex: /app/models/file.ts):

`const _ = require("lodash");`

**Comment by tsonevn** [comment]
Hi @hekigan , 
I reviewed your problem. The correct way to require a npm module in `NativeScript` project is like this: 
`var lodashModule = require("lodash");`. You can read more about the loading  `files` and `modules` in `NativeScript` project in our documentation: https://docs.nativescript.org/runtimes/require.html
I hope this info helps.

**Comment by hekigan** [comment]
Hi,

thank you for your answer.

Calling `var lodashModule = require("lodash");` instead of `const _ = require("lodash");` fix the issue.
But does that mean that even though I am using Typescript (or even just ES6), I can not use `const` or `let` instead of `var`? That's quite confusing.

Is there any plan on the roadmap to be able to use `import` for everything? It would make the use more consistent overall.

**Comment by tsonevn** [comment]
Hi @hekigan , 
At the moment  EcmaScript 6 is not supported in NativeScript. However soon in the next  NativeScript versions, the NS will be compatible with ES6, then it will be possible the use of `const` and `let`.
