### ISSUE TITLE
How to give the content in tabview

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#2011]
I tried this code in tabview but couldn't get the output.The following is the code and the output is the link below.

<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="onLoaded" navigatedTo="onNavigatedTo" >

    

       <Page.actionBar>
           <ActionBar title="stats" icon="">
           </ActionBar>
       </Page.actionBar>
       
        <TabView id="tabViewContainer">
            <TabView.items>
                <TabViewItem title="Tab 1">
                    <TabViewItem.view>
                        <Label text="This is Label in Tab 0" />
                        <Button text="sssssddds" tap="" />
                        
                        
                        
                    </TabViewItem.view>
                </TabViewItem>
                <TabViewItem title="Tab 2">
                    <TabViewItem.view>
                        <Label text="This is Label in Tab 2" />
                    </TabViewItem.view>
                </TabViewItem>
            </TabView.items>
        </TabView>
   
</Page>
![image](https://cloud.githubusercontent.com/assets/10844041/14731293/ab2d910c-086c-11e6-8334-e88da2d054aa.png)

**Comment by hshristov** [comment]
`TabViewItem.view` accepts single child. So you need to use some `Layout` like `StackLayout` or `GridLayout` to hold your widgets (e.g. `Label` & `Button`). Layouts are used for positioning widgets.

**Comment by dhanalakshmitawwa** [comment]
Thanks for reply
