### ISSUE TITLE
Cocoapod to NativeScript (question/issue)

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#2014]
I'm trying to create a custom camera view and I am using [LLSimpleCamera](https://cocoapods.org/pods/LLSimpleCamera) CocoaPod for this. The Pod is included in the project and seems to be working as it should. However, I am not so experienced with translating CocoaPod projects into JavaScript.

I am trying to translate this piece of code into JS:

```
CGRect screenRect = [[UIScreen mainScreen] bounds]; // I believe this one is not necessary since we can get the screen dimensions from the platformModule

self.camera = [[LLSimpleCamera alloc] init];
[self.camera attachToViewController:self withFrame:CGRectMake(0, 0, screenRect.size.width, screenRect.size.height)];
```
```
exports.cameraView = function(args) {
  var camera = LLSimpleCamera.alloc().init();
  camera.attachToViewController(this).withFrame(CGRectMake(0, 0, 300, 300));

  args.view = camera;
}
```

`attachToViewController()` does not exist if I console.dump `LLSimpleCamera`, and I am unsure if I even need it since I use `args.view = camera`? Also, `withFrame()` does not exist either, which I think is the real issue here for me.

Am I missing something? Thanks in advance.

**Comment by enchev** [comment]
The method name will be the original + all arguments names:
http://docs.nativescript.org/runtimes/ios/types/ObjC-Classes#methods

In your case:
```JavaScript
camera.attachToViewControllerWithFrame();
```

**Comment by NordlingArt** [comment]
@enchev - Thanks for the quick reply. That almost worked. I now get the error:

```
file:///app/tns_modules/ui/builder/builder.js:154:56: JS ERROR Error: Building UI from XML. @file:///app/main-page.xml:4:5
	 ↳Actual arguments count: "1". Expected: "2".
```

The XML looks like this:
```
<Page loaded="loaded">
  <StackLayout>
    <Placeholder creatingView="cameraView"/>
  </StackLayout>
</Page>
```
JS:
```
exports.cameraView = function(args) {
  var camera = LLSimpleCamera.alloc().init();
  camera.attachToViewControllerWithFrame(CGRectMake(0, 0, 300, 300));
  
  args.view = camera;
};
```

Anything missing?

**Comment by enchev** [comment]
Hey @NordlingArt,

I've checked [the method implementation](https://github.com/omergul123/LLSimpleCamera/blob/master/LLSimpleCamera/LLSimpleCamera.m#L155) and indeed you need to pass the `UIViewController` - you can get it from the current page:
```JavaScript
var frame = require("ui/frame");

exports.cameraView = function(args) {
  var camera = LLSimpleCamera.alloc().init();
  var viewController = frame.topmost().currentPage.ios;
  camera.attachToViewControllerWithFrame(viewController, CGRectMake(0, 0, 300, 300));

  args.view = camera;
};
```

**Comment by NordlingArt** [comment]
Hi @enchev,

`frame.topmost().currentPage` doesn't seem to exist:

```
tnscustomCamera[3137]: file:///app/tns_modules/ui/builder/builder.js:154:56: JS ERROR Error: Building UI from XML. @file:///app/main-page.xml:4:5
	 ↳undefined is not an object (evaluating 'frame.topmost().currentPage')
```

**Comment by enchev** [comment]
Hey @NordlingArt,

Sorry, you are right! Please use `args.object.page.ios` to get the view controller.

**Comment by NordlingArt** [comment]
Hi @enchev,

Just tried it. Now there's a blank page with nothing reported in the log. No crash though, that's one step forward! 😀  I don't know what to do now. I understand that the iPhone Simulator can't display the camera view. However, I've tested it on my iPhone 6 device and it's the same there. Would you mind taking a look at it? I'd really appreciate it. I'm posting the project Git and the CocoaPod below.

https://github.com/NordlingArt/tns-customCamera
https://github.com/NordlingArt/nativescript-custom-camera

(Note I've done a 3 second timeout on the script in case it can't read variables before `loaded`)

**Comment by NathanaelA** [comment]
@NordlingArt - just a simple question; any reason you are using the "loaded" event vs the navigated to event?   The navigatedTo event the page will be properly defined at that point, loaded the page is still being built so things aren't always set yet.   This might not solve your primary issue; but it would eliminate having to have a setTimeout of 3 seconds.  ;-)

**Comment by NordlingArt** [comment]
@NathanaelA Good question. Never thought about that. I should change it to navigatedTo. But like you said, it's not the primary issue 🙃

**Comment by patuku-roy** [comment]
Hi @NordlingArt do you have a plan to make this as an cross-platform plugin?

**Comment by NordlingArt** [comment]
@patuku-roy - Definitely a plan :) Not sure when though. Haven't looked into Android at all as of now. But in the near future hopefully!

**Comment by patuku-roy** [comment]
@NordlingArt I hope you have a strong motivation to do that :) ... can not wait ... great work anyway

**Comment by NickIliev** [comment]
Hey @NordlingArt it was quite a while I am closing this issue , but please let us know if you have created your plugin - it will be of great help for the whole NativeScript  community!
