### ISSUE TITLE
Setting bindingContext to primitive types throws

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#2016]
The following unit test throws that `new WeakRef` can not be called with non-object:
``` JavaScript
export var test_only_Bindable_BindingContext_Null_DoesNotThrow = function () {
        var options: bindable.BindingOptions = {
            sourceProperty: "a.b",
            targetProperty: "test"
        }
        var obj = new bindable.Bindable();
        obj.bind(options);
        obj.bindingContext = new observable.Observable({ a: "b" });
        obj.bindingContext = null;
}
```
It seems it tries to wrap the `"b"` string in WeakRef and fails. Setting bindingContext to null here:
https://github.com/NativeScript/nativescript-marketplace-demo/blob/production/app/examples/listview/selection/main-page.ts#L28
fails because `typeof null === 'object'` returns true and we try to wrap the `null` in `WeakRef`.

**Comment by nsndeck** [comment]
fixed with commit #2071
