### ISSUE TITLE
Can't exclude iPad from deployment devices

### ISSUE THREAD

**Issue by wapdtc** [NativeScript/NativeScript#2020]
I want to exclude iPad support when delivery to app store, but it failed. I did the following steps after googling:
add TARGETED_DEVICE_FAMILY=1 to build.xcconfig 
executing tns publish ios from command line .

But there is still an error when I try to upload my ipa to app store, the validation failed. It says:
ERROR ITMS-90475: "Invalid Bundle. iPad Multitasking support requires launch storyboard in bundle 'com.companyname.appname.'"
Any suggestion?

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#1714
