### ISSUE TITLE
Question:overidden func from swift is not called by original class

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#2021]
Hello, my problem :
- I create a class in swift for example 
```
public class SwiftClass:NSObject {
    public init() {
		dosomething()
	}
	
	public func dosomething() { // override this
        NSLog("dosomething parent should not called !")
    }	
	
}
```

And I override it in NS using 
```
var MySwiftClass = SwiftClass.extend({
	dosomething: function () {
                    console.log('Success with overriding function');
                }
});
```

Then I create the object (NS)
```
           newclass = new MySwiftClass();

```

The output is "dosomething parent should not called !" and not 'Success with overriding function'

But if I call using
```
newclass.dosomething();
```

The output is correct which is 'Success with overriding function'

So is the problem because of the swift, or I missing something for overriding method in class?

Thanks

**Comment by x4080** [comment]
Oh and it works if I inherit the class in Swift project BTW

**Comment by enchev** [comment]
This issue was moved to NativeScript/ios-runtime#553
