### ISSUE TITLE
Support px in css (strip it out)

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#2022]
It's a very common issue for people new to {N} (or even us seasoned webdevs) to accidentally add "px" to a css size, like 
``` css
.label {
    margin-top: 5px;
}
```
Now clearly {N} doesn't use pixels like this, but it would be great if the parser could just ignore the "px" and assume "5" in the above example instead of just not recognizing it as anything.

### Did you verify this is a real problem by searching 
Searched, didn't find anything, this came from a slack discussion 

### Which platform(s) does your issue occur on?
**Both**

![image](https://cloud.githubusercontent.com/assets/1542376/14762244/a6937062-0943-11e6-9674-39c4733ad53b.png)

**Comment by raefa** [comment]
Might this confuse people more? The values in CSS are actually dp not px. An alternate idea: show a warning in the logs when you build a project that has px in the CSS.

**Comment by sitefinitysteve** [comment]
We know they're device independant, the fix isn't to change that fact, it's to just prevent the constant "why isnt this working" question... a build warning can still be issued on top of this.  But it'd also allow people to take CSS libs they get from the web and drop it in and mostly just work, (instead of a find\replace on px)

**Comment by raefa** [comment]
@sitefinitysteve Good point re. CSS libs. I can see that being pretty cool. You could share CSS classes with your website too. I'd do that! :)

**Comment by enchev** [comment]
Merged with https://github.com/NativeScript/NativeScript/issues/53
