### ISSUE TITLE
Android: TabViewItem renders on 2 lines in certain conditions

### ISSUE THREAD

**Issue by rborn** [NativeScript/NativeScript#2023]
- CLI: 1.7.1
- Cross-platform modules: 1.7.1
- Runtime:1.7.1

In the case the tabs are only 4 the TabItemView is rendered on 2 lines:

~~~
<?xml version="1.0"?>
<Page xmlns="http://schemas.nativescript.org/tns.xsd">
		<TabView id="tabView" style="color:green;" selectedColor="green">
			<TabView.items>
				<TabViewItem title="Near">
					<TabViewItem.view>
						<Label id="mu" text="blah blahs"/>
					</TabViewItem.view>
				</TabViewItem>
				<TabViewItem id="districtsTab" title="Districts" >
					<TabViewItem.view>
						<Label id="mu" text="blah blahs"/>
					</TabViewItem.view>
				</TabViewItem>
				<TabViewItem title="As List">
					<TabViewItem.view>
						<Label text="blah blahs"/>
					</TabViewItem.view>
				</TabViewItem>
				<TabViewItem title="On Map">
					<TabViewItem.view>
						<Label id="mu" text="blah blahs"/>
					</TabViewItem.view>
				</TabViewItem>
			</TabView.items>
		</TabView>
</Page>
~~~
![screen shot 2016-04-23 at 20 48 53](https://cloud.githubusercontent.com/assets/406409/14763774/e5c1ad96-09a0-11e6-88f4-c735a4af3b4f.png)

If another tab is added, the TabView becomes "scrollable" and everything is rendered correctly.

**EDIT** This  seems to fix the issue, but it's actually cutting the text (final S is missing)
~~~
	var tabView = view.getViewById(page, "tabView");
	var tabTitle = tabView._getAndroidTabView().getTextViewForItemAt(1);
	tabTitle.setMaxLines(1);  //<= that's the (wrong) secret 😄 
~~~
![screen shot 2016-04-23 at 22 50 14](https://cloud.githubusercontent.com/assets/406409/14763922/dc2bc906-09a5-11e6-92a0-c2e9008df07d.png)

**Comment by NickIliev** [comment]
Confirmed under API23 
![confirmed](https://cloud.githubusercontent.com/assets/18008302/14775972/a8b16c8a-0acb-11e6-9140-61399ed96cd2.png)

**Comment by enchev** [comment]
Hey @rborn,

Unfortunately this is what will happen with every TextView in android if there is not enough space. According to [Material guidelines](https://www.google.com/design/spec/components/tabs.html#tabs-usage) all tab item titles should be with equal width equally distributes using the available space which will cause in some cases the annoying android wrapping "feature". 

Possible solution will be to truncate the text with ellipsis at the end however in this case you/we will loose the real wrapping with two separated words. 

Do you think if truncated text with ellipsis will work in your case? In this case you can simply do the following:

```XML
 <TabView loaded="pageLoaded">
...
```

```JavaScript
exports.pageLoaded = function(args) {
   var tabView = args.object;
   for(var i = 0; i < tabView.items.length; i++){
      tabView._tabLayout.getTextViewForItemAt(i).setHorizontallyScrolling(true);
   }
}
```

**Comment by rborn** [comment]
@enchev 
Thanks for the idea.

The issue is that the text is small enough to fit in 4 tabs
Maybe I will try to make the font 1px smaller.

I will test both solutions and let you know.

**Comment by sitefinitysteve** [comment]
Could we maybe have this as a toggleable option on the tabview?  For consistancy have it work like iOS for crossplatform purposes, but toggleable back to the 2-line via some XML attribute?

``` xml
<TabView uglifyTabs="true"
```
;)

**Comment by rborn** [comment]
`uglifyTabs` 😆

**Comment by rborn** [comment]
@enchev sorry for taking so long :( life is hectic 
So I tested your idea and the tabs get "shortened" indeed. I will try to either find different titles  or dig more when I'll have some more time. Thanks :)

![screen shot 2016-05-07 at 16 26 14](https://cloud.githubusercontent.com/assets/406409/15092654/785c6b3a-1470-11e6-8b21-51c89638b3a4.png)

**Comment by maddy2get** [comment]
This issue is happening to me as well. In emulator (5.1.1) it works fine as you can scroll the tabs horizontally but on Google Pixel XL (7.1.0) the tab titles are showing over two lines. How can I make the scroll like older versions?
