### ISSUE TITLE
Unable to set padding for TextView

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#2024]
Tested on iOS only. Padding for TextView will not apply. A very simple demonstration:

```
TextField, TextView {
  padding: 10;
}
```

```
<TextField text="TextField" />
<TextView text="TextView" />
```

Setting it via the XML view will not work either.

**Comment by tsonevn** [comment]
Hi @NordlingArt ,
Thank you for reporting this issue.

I tested given code snippet and found that textView padding property is not supported for iOS.
I confirm this is real issue. This problem will be scheduled for fixing. 
As a temporary solution you can set textView `textContainerInset property` in iOS. I am attaching a sample code:

main-page.xml
```
<Page loaded="load">
  <StackLayout>
    <Border borderRadius="10" borderWidth="1" borderColor="#FF0000">
      <TextField text="TextField" />
    </Border>
    <Border borderRadius="10" borderWidth="1" borderColor="#FF0000">
    <TextView text="TextView" id="textView" />
    </Border>
  </StackLayout>
</Page>
```

main-page.ts

```
import { EventData } from "data/observable";
import { Page } from "ui/page";
import {TextView} from "ui/text-view"

export function load(args:EventData){
    var page:Page = <Page> args.object;
    var tmpTextView= page.getViewById("textView");
    if(page.ios){
        var insets = UIEdgeInsetsMake(50, 50, 100, 100);
        tmpTextView.ios.textContainerInset =insets;
    }
}
```
I hope this is applicable for you.

**Comment by NordlingArt** [comment]
Hi @tsonevn,

Thanks for the workaround fix. I'll be using it in the meanwhile.
