### ISSUE TITLE
How to write the code for attached the image

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#2025]
![capture3](https://cloud.githubusercontent.com/assets/10844041/14774095/ae6b8a80-0acf-11e6-8143-9c69d8e5e505.PNG)

**Comment by NickIliev** [comment]
Hello @dhanalakshmitawwa 

You can attach image via **Image** tag and its **src** property
For example : 

the folloing code will look in **app/folder/** for **logo.png**
`<Image src="~/folder/logo.png" / >`

you can also use the following to look for images stored in the antive resources folders
(for example for Android its app/App_Resources/Android/drwable-xxxx/...)
 <Image src="res://icon" />
Here is a sample code with reproduces your scenario : 

main-page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <StackLayout class="stack">
    <!--native source for images-->
    <Image src="res://icon" stretch ="none" class="image" />
    <Label text="25789" class="counter"/>
    <Label text="views" class="views"/>
  </StackLayout>
</Page>
```

main-page.css
```
Page {
    background-color: black;
}

.stack {
    border-width:4;
    border-radius: 200;
    border-color: darkblue;
    height: 200;
    width: 200;
    background-color: darkgray;
}

.counter {
    font-size: 30;
    horizontal-align: center;
}

.views {
    font-size: 24;
    horizontal-align: center;
}

.image  {
    margin: 20;
    horizontal-align: center;
}

```

**Comment by dhanalakshmitawwa** [comment]
Thank you for reply
