### ISSUE TITLE
Are there any notes  or videos for using the components  in brief

### ISSUE THREAD

**Issue by karumurikiran** [NativeScript/NativeScript#2026]

**Comment by NickIliev** [comment]
@karumurikiran 

There are a lot of video tutorials posted by our community so you can explore them and find what your are looking for in specific [for example](https://www.google.bg/webhp?sourceid=chrome-instant&rlz=1C1NHXL_bgBG685BG685&ion=1&espv=2&ie=UTF-8#q=nativescript+video&tbm=vid)

Please note that the issue system is for tracking specific behaviours, possible features and potential bugs - for more basic question you can use our slack community chanel and stackoverflow support.
