### ISSUE TITLE
Unable to use Repeater inside TabView

### ISSUE THREAD

**Issue by Metalmate** [NativeScript/NativeScript#2027]
The sample code:

```xml
<TabView>
    <TabView.items>
        <Repeater items="{{ locations }}">
            <Repeater.itemsLayout>
                <StackLayout />
            </Repeater.itemsLayout>
            <Repeater.itemTemplate>
                <TabViewItem title="{{ city }}">
                    <TabViewItem.view>
                        <Label text="{{ address }}" />
                    </TabViewItem.view>
                </TabViewItem>
            </Repeater.itemTemplate>
        </Repeater>
    </TabView.items>
</TabView>
```

Causes the following error:

Error: View of TabViewItem at index 0 is undefined File: "/data/data/com.custom.id/files/app/tns_modules/ui/tab-view/tab-view.js", line : 218, column: 20

CLI: 1.7.0
Android 5.1

**Comment by ErjanGavalji** [comment]
@Metalmate, can you please, reformat the XML so that it gets readable in normal mode?

Thanks,
Erjan

**Comment by NickIliev** [comment]
Hello @Metalmate 

The error is invoked because of a missed `<TabViewItem.view>` tag
Your code should look like this : 
```
  <TabView>
      <TabView.items>
            <TabViewItem.view>
                   ....your repeater code here...
            </TabViewItem.view>
      </TabView.items>
  </TabView>
```

**Comment by Metalmate** [comment]
I want to create multiple tabs inside the TabView using the Repeater. So putting the Repeater inside the TabViewItem.view does not work for me.

**Comment by NickIliev** [comment]
Hey @Metalmate 

If i got it right your idea is to generate multiple tabs based on some dinamically loaded data (let say array of objects) and based on that array.lenght you want to generate multiple tabs.

Here is one way of doing it with some code-behind tab generation and a sample array.

in your page.ts 
```
import { EventData } from "data/observable";
import { ObservableArray } from 'data/observable-array';
import { Page } from "ui/page";

var tabViewModule = require("ui/tab-view");
var stackLayoutModule = require("ui/layouts/stack-layout");
var labelModule = require("ui/label");

var colors = new ObservableArray(["red", "green", "blue"]);

export function navigatingTo(args: EventData) {

    var page = <Page>args.object;
    page.bindingContext = colors;

    var tabView = new tabViewModule.TabView();

    var items = [];
    for (var index = 0; index < colors.length; index++) {
        var element = colors.getItem(index);

        var stackLayout = new stackLayoutModule.StackLayout();
        var label = new labelModule.Label();
        label.text = element;
        stackLayout.addChild(label);
        
        var tabEntry = {
            title: "Tab #" + index,
            view: stackLayout
        }
        items.push(tabEntry);
    }
    
    tabView.items = items;
    
    page.content = tabView;
}
```
Let me know if that solution worked for your project!

**Comment by Metalmate** [comment]
Hello @NickIliev ,

At this moment we currently use JavaScript to generate the dynamic content, however, this is quite slow. I hoped we could speed it up by using XML, therefore the Repeater-problem.

**Comment by Metalmate** [comment]
I don't see why this is closed, since I still can't use a Repeater to generate multiple tabs in XML and the error described above also is not solved yet.

**Comment by enchev** [comment]
The TabView is root level component and cannot be nested inside other components (for example Repeater). Repeater cannot be used to generate TabViewItem as well. The only way you can generate  TabViewItem dynamically is programmatically.

**Comment by Metalmate** [comment]
Ok, thanks for the explanation.
