### ISSUE TITLE
Is there a way to replace everything inside an observable without loosing the observable state?

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#2032]
Right now, if I have an observable object that is empty when initiating view, like so:

`var data = new observable();`

I want to fill the data with object keys out of an already existing object. Like this:

```
var object = { id: 1, title: "Test" };
data = object;

// data = { id: 1, title: "Test" };
```

The comment shows how the `data` variable becomes a non-observable object. What I want to do is filling `data` with the object so it becomes like this:

`data = new observable({ id: 1, title: "Test" });`

Is it an okay solution to just replace the empty observable with a new observable? Won't the bindingContext loose the observable state if I do this?

**Comment by NickIliev** [comment]
Hi @NordlingArt 

You can add new entities to your current model with **set**
For example : 
```
    var data = new Observable();

    var object = { id: 1, title: "Test" };
    
    data.set('myObject', object);
    
    var resultObject = data.get("myObject");
    console.log(resultObject.id); // 1
    console.log(resultObject.title); // test
```

Of course you can bind to those object directly like 
   `<Label text="{{ myObject.title }}" />`

I hope that will be helpful for your project - let me know if you need further assistance.

**Comment by NordlingArt** [comment]
Hi @NickIliev,

With `set()` I only add or edit a new key. Meaning I will have to do so for all keys inside the object in question.

What you're doing in your example, however, shows how to make a new variable called`resultObject` through `data.get("myObject")`. Question is, will `resultObject` be a new observable then?

**Comment by NickIliev** [comment]
Hey @NordlingArt 

The **resultObject** is not observable but just to represent the idea..  

Still instead of setting the keys one by one why don't you set the entire object..
You still wiil have access to your object key-value pairs and your data will be observable 
Like this : 

```
var data = new Observable();
var object = { id: 1, title: "Test" };
data.set('myObservableObject', object);

// binding in your xmlv via your obseervable object in data
<Label text="{{ myObservableObject.id }}" />
<Label text="{{ myObservableObject.title }}" />
```

Of course if you want to explicitly add each key as a new observable value for your data you can use the following syntax : 
```
var testObject = { id: 55, title: "my test object" };
var data = new Observable(testObject);

var object = { id: 1, title: "Test" };
data = new Observable(object); // this will override any previously passed data and testObject will no longer exist in your data

// binding in your xml
<Label text="{{ id }}" />  // 1
<Label text="{{ title }}" /> // Test
```
Keep in mind that this will override any previosly writen data in your observable variable **data** which will not be a problem if you are passing an emtpy observable (as shown in your example)
