### ISSUE TITLE
Angular + NativeScript + iOS = Signal 9 error

### ISSUE THREAD

**Issue by jlooper** [NativeScript/NativeScript#2041]
I upgraded to NativeScript 2.0 on my mac. All seemed fine.
My Xcode version is 7.3 (7D175).
I attempted to emulate the sample-Groceries on the angular-end branch after removing hooks, platforms, and doing an npm install to refresh the code. I also reinstalled tns-modules.

I get the following error after emulation using `tns emulate ios`:
Project successfully built.
Using  /Users/Looper/Documents/NativeScript/sample-Groceries/platforms/ios/build/emulator/sampleGroceries.app
Starting iOS Simulator
Apr 27 10:21:26 LOOPERMAC com.apple.CoreSimulator.SimDevice.41F94030-553A-48C8-9442-DB843CE80F4B.launchd_sim[33533] (UIKitApplication:org.nativescript.groceries[0xb959][35580]): Service exited due to signal: Killed: 9

TJ gets the same. Help please!

**Comment by enchev** [comment]
Hey @jlooper,

Can you try it again? @rosen-vladimirov what do you think? I had the same problem however with the second run everything worked as expected. I'm also using XCode 7.3.

**Comment by jlooper** [comment]
so I just downloaded a completely fresh .zip of sample-Groceries on the Angular-end branch and emulated, same issue. The app does build, however, so I can click on the installed icon and open the app. Is this just the workaround I should use?

**Comment by rosen-vladimirov** [comment]
ok, looks like the issue is caused by the simulator settings. Using **Simulator** -> Reset Content and Settings seems to help for anyone having this issue ;)

**Comment by jlooper** [comment]
I'm closing this as it only pertains to the angular version of {N}, moving my comments to the NativeScript/Angular repo. Thanks!
