### ISSUE TITLE
in Listview while scrolling and fast click on item unable to stop scroll, intead it will open a item?

### ISSUE THREAD

**Issue by katturajam** [NativeScript/NativeScript#2045]
http://stackoverflow.com/questions/36895287/in-listview-while-scrolling-and-fast-click-on-item-unable-to-stop-scroll-intead

**Comment by NickIliev** [comment]
Hi @katturajam 

I believe that what you are trying to achive is the default behaviour when your scroll a list of items within a ListView in iOS. For example you can try list-view demo below which demostrates how a scrolling list-view can be stoped with a fast tap without triggering the redirection to details-page (which are also present in the demo).
[https://github.com/NickIliev/NativeScript-demos/tree/master/cuteness.io](https://github.com/NickIliev/NativeScript-demos/tree/master/cuteness.io)

If however you are experiencing a different behaviour please post the platform & device versions on which you are testing your demo.
