### ISSUE TITLE
Converters are embedded in list of objects when bound to ListView - Part 2

### ISSUE THREAD

**Issue by guillaume-roy** [NativeScript/NativeScript#2046]
Please see #1910 

I've updated to version 2.0.0, the problem is still there.

- tns-core-modules 2.0.0
- tns-android 2.0.0
- Windows 10

**Comment by nsndeck** [comment]
@guillaume-roy  Yes, indeed the fix does not enter in 2.0 release. You can use `@next` version of ths-core-modules. Just call in your project dir:
```
tns plugin add tns-core-modules@next
```

**Comment by guillaume-roy** [comment]
With `"tns-core-modules": "^2.0.0-2016-04-28-2826"` the converters aren't in the object but the `$value` is still in.

**Comment by guillaume-roy** [comment]
The `"tns-core-modules": "^2.0.0-2016-05-03-2842"` contains the `$value` issue.

**Comment by nsndeck** [comment]
I've commit a new fix. This time a hope that this will be solved. Indeed version `2.0.0-2016-05-03-2842` does not include the fix but `@next` version which is something like `2856` does. So give it a try and let me know about the result.
Sorry for the inconvenience caused.

**Comment by guillaume-roy** [comment]
Now my project doesn't even build. I have this error message : 

> Processing node_modules failed. TypeError: Invalid Version: 2.0
> Sending exception report (press Ctrl+C to stop).....

I get back to `"tns-core-modules": "^2.0.0"`, delete my `node_modules` directory, `npm install` I still have the same build error.

**Comment by nsndeck** [comment]
I've managed to reproduce similar issue. The problem comes from the fact that anywhere (in some package.json) there is a reference to `2.0` version for `android` or `ios` platform instead of correct version `2.0.0`. My error was caused by `nativescript-geolocation` 0.0.10 plugin. I've just publish a new `0.0.11` version that fixes the problem.

**Comment by guillaume-roy** [comment]
Thanks for you answer. All issues are fixed :+1:
