### ISSUE TITLE
Message "Border is depricated" while this isn't true according to the documentation

### ISSUE THREAD

**Issue by Metalmate** [NativeScript/NativeScript#2047]
When using the Border-tag inside a view and you open that view in the app, you recieve the fallowing message:

CONSOLE LOG file :///app/tns_modules/globals/globals/js:122:20: Border is deprecated

But there is nothing to be found about the deprecation of the Border-tag in the documentation, see: https://docs.nativescript.org/ApiReference/ui/border/HOW-TO.html

CLI: 1.7.0

Android 5.1 & iOS 8.4

**Comment by NickIliev** [comment]
Hello @Metalmate 

Yes indeed Border is deprecated module. 
Thank you pointing out the need to fix the documentation article about it!

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/docs#333
