### ISSUE TITLE
[proposed] ui/builder's function load should accept attributes object

### ISSUE THREAD

**Issue by akagr** [NativeScript/NativeScript#2048]
This is when one is loading a component dynamically. In current state, if we want to set properties on the dynamically loaded component, we need to do something like this:

```javascript
const builder = require('ui/builder');

const staticLabel = builder.load({
    path: '~/components/staticLabel',
    name: 'staticLabel'
});

staticLabel.myProperty = 'hello';
```

I feel like we should be able to provide an `attributes` argument to `load` function, eliminating the need to set properties manually.

Proposed syntax:

```javascript
const builder = require('ui/builder');
const staticLabel = builder.load({
    path: '~/components/staticLabel',
    name: 'staticLabel',
    attributes: {
        myProperty: 'hello'
    }
});
```

The code is already present in `ui/builder` to support all this. Need to just add `attributes` as part of interface and send that instead of `undefined` to [`loadCustomComponent`](https://github.com/NativeScript/NativeScript/blob/master/ui/builder/builder.ts#L118) method.

Sending a PR in case this makes sense to whoever reads this.

**Comment by akagr** [comment]
This may be similar to #1758

**Comment by NickIliev** [comment]
duplicate to [#1758](https://github.com/NativeScript/NativeScript/issues/1758)
