### ISSUE TITLE
How to : ListView items drag and drop

### ISSUE THREAD

**Issue by Kyozatch** [NativeScript/NativeScript#205]
Hi,

I need to reorder my listview's items with a drag and drop on long-press event.
Is it currently possble with nativescript ?

**Comment by N3ll** [comment]
This will be available asTelerik UI components for NativeScript soon.

**Comment by perqa** [comment]
If a solution is available, please link to it. If not, the issue should remain open.

**Comment by speigg** [comment]
:+1:

**Comment by coorasse** [comment]
👍

**Comment by bsh314** [comment]
[Progress NativaScript Ui - ListView  - Reorder](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/item-reorder)
