### ISSUE TITLE
[v2.0.0] Cannot kill livesync process?

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#2054]
Using Mac OS X, I cannot kill the `tns livesync ios --watch --emulator` command with ctrl+c. Meaning I have to quit the Terminal and reset it.

Does anyone else have this issue? This did not happen prior 2.0.0.

**Comment by dtopuzov** [comment]
Already logged in CLI repo: https://github.com/NativeScript/nativescript-cli/issues/1725
Most likely it will be part of first hot fix release after 2.0.0
