### ISSUE TITLE
Issues with package.json dependencies in 2.0

### ISSUE THREAD

**Issue by mehfuzh** [NativeScript/NativeScript#2056]
tns build does not copy dependencies from `package.json` property.

I did the following:

```
git clone https://github.com/couchbaselabs/nativescript-couchbase.git

cd nativescript-couchbase/demo

tns platform add ios

tns plugin add ../

tns build ios 

```
It was not copying the plugin under `node_modules` folder. I therefore did the following:

`npm run instlall
`

This solved the issue for me.

However, didnt find any refenrence for it in `getting-started`: 
https://docs.nativescript.org/start/getting-started

**Comment by tsonevn** [comment]
Hi @mehfuzh ,

In our documentation is describe how to install standard npm plugins. For example if you try to install `nativescript-image-preview` with `tns plugin add nativescript-image-preview`, the plugin will be copied  to `node_module` folder. I saw that `nativescript-couchbase` is experimental and it has not yet been added to the NPM repository. Maybe this is the reason, why the folder is not copied to the `node_modules`.

I hope this helps.

**Comment by mehfuzh** [comment]
it is under npm here is the link:
https://www.npmjs.com/package/nativescript-couchbase

**Comment by tsonevn** [comment]
Hi @mehfuzh, 

I've tested your case one more time. The given steps are not going to work on NS 2.0.
Actually if you use `tns run ios --emulator` all the dependencies would be installed correctly. Another way to do that, after you clone the projects is to follow the steps below:
```
tns platform add ios

tns prepare ios

tns run ios --emulator
```
Indeed in `demo/package.json` `tns-core-modules` is `1.7.1`. This cuold bring some problems when you run the project. You could upgrade `tns-core-module` with `npm install tns-core-modules@latest --save`

Let me know whether this helps or if I can assist you further.
