### ISSUE TITLE
How to give the border shown in the image

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#2058]
![color](https://cloud.githubusercontent.com/assets/10844041/14953035/5774d312-1083-11e6-887b-189f5c9145ac.PNG)

**Comment by jjTudu** [comment]
` <GridLayout columns="*,*" >`
             `<ContentView col="0" row="0">`
             ` <Border borderRadius="0" borderWidth="1" borderColor="#FF0000">`
              `<Button text="Profile" tap="btnProfileClick"   width="100%" height="100%"/>`
              `</Border>`
              `</ContentView>`
             ` <ContentView col="1" row="0">`
             ` <Border borderRadius="0" borderWidth="1" borderColor="#FF0000">`
             ` <Button text="Setting" tap="btnSettingClick"   width="100%" height="100%"/>`
              `</Border>`
              `</ContentView>`
      `  </GridLayout>`

**Comment by NickIliev** [comment]
Hello @dhanalakshmitawwa 

Border element is one option but keep in mind that it is depricated.

The better solutiojn is to use CSS properties to apply border on your UI elements.
_For example:_

app.css
```
.bordered {
    border-width: 2; 
    border-color: #FF0000;
}
```

your-page.xml
```
<Page>
    <StackLayout class="bordered">
        <Label text="my label" />
    </StackLayout>
</Page>
```

Here is the article about styling with CSS and all the supported CSS properties in NativeScript
[https://docs.nativescript.org/ui/styling](https://docs.nativescript.org/ui/styling)
