### ISSUE TITLE
JS: Binding: Run-time error occured in file: undefined at line: undefined and column: undefined

### ISSUE THREAD

**Issue by Jpaagt** [NativeScript/NativeScript#2074]
With the release of version 2.0.0, I keep getting a lot of the following error messages in the console that are not very helpful:

`JS: Binding: Run-time error occured in file: undefined at line: undefined and column: undefined`

The application does not break and seems to work as expected, but the error messages are quite annoying, since there is not much information of what could be causing them. Would it be possible to improve the messages so that they are helpful at least?

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.0.0

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#443

**Comment by hshristov** [comment]
@Jpaagt Could you please attach a project which reproduce the issue?
