### ISSUE TITLE
2.0 Corrupted navigation stack

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#2076]
### Did you verify this is a real problem by searching 
Yes

### Tell us about the problem
When navigating from a promise I get frame-common.js:173:127: JS ERROR Error: Corrupted navigation stack

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.0
- Cross-platform modules: 2.0
- Runtime(s): 2.0
- Plugin(s): [nativescript-auth0](https://github.com/sitefinitysteve/nativescript-auth0)

### Please tell us how to recreate the issue in as much detail as possible.
Clone the plugin repo https://github.com/sitefinitysteve/nativescript-auth0, run the iOS demo... 
When it loads you should see the lock screen, login, then when the promise returns you should be navigated to the homepage (this was fine in 1.7).  2.0 though throws this and crashes the app.

file:///app/tns_modules/ui/frame/frame-common.js:173:127: JS ERROR Error: Corrupted navigation stack; page: Page(1)@file:///app/login.xml:1:1;; currentNavigationPage: Page(5)@file:///app/home.xml:1:1;
May  5 12:08:13 deli-pc4 com.apple.CoreSimulator.SimDevice.6BD92849-9D34-4142-8DA9-A65E9F54B736.launchd_sim[3205] (UIKitApplication:org.nativescript.demo[0xab0c][6221]): Service exited due to signal: Segmentation fault: 11

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Yep, all in the repo

**Comment by NickIliev** [comment]
Hi @sitefinitysteve 

The issue is confirmed - also confirmed that reverting back to 1.7.1 modules is fixing the corrupted navigation stack error.

After receiving the promise from **auth0.show()** navigation won't work 
even when it is only provided with a page name
```
    frameModule.topmost().navigate({
       moduleName: "home" 
    });
```
