### ISSUE TITLE
Remove nativescript from OSX

### ISSUE THREAD

**Issue by kristiyandobrev** [NativeScript/NativeScript#2087]
Hello ! 

How can I completely remove `nativescript` from my Mac ? I installed it using `npm`, then I tried to remove it with `sudo npm remove tns` and `sudo npm remove nativescript` but it's still around my Mac. Any ideas :) ?

**Comment by tsonevn** [comment]
Hi @kristiyandobrev, 
You could uninstall `NativeScript` by using `npm uninstall nativescript -g`
Regards,
@tsonevn

**Comment by kristiyandobrev** [comment]
Thank you @tsonevn , that worked 👍

**Comment by notflip** [comment]
Does it uninstall all the dependancies it installed using the Setup?

**Comment by tsonevn** [comment]
Hi @notflip,
The uninstall command will remove the specified package.
In this case, it will remove NativeScript CLI. More about the way NMP uninstall command cold be found [here](https://docs.npmjs.com/cli/uninstall).
