### ISSUE TITLE
actionBarHidden property does not work in nativescript 2.0 for modals

### ISSUE THREAD

**Issue by bathejasumeet** [NativeScript/NativeScript#2090]
`<Page shownModally="shownModally" actionBarHidden="true" loaded="pageLoaded" unloaded="modalUnloaded"  >`

does not seem to hide the modal in 2.0, worked perfectly in 1.7.1 , tested on android

**Comment by tsonevn** [comment]
Hi @bathejasumeet,

I reviewed your problem it seems that `actionBarHidden` works for me correctly. When I set `actionBarHidden` to true the `ActionBar` has been hided.

`actionBarHidden="true"`

![screenshot 6](https://cloud.githubusercontent.com/assets/17448734/15173993/0badafbc-1768-11e6-82e9-3c5049b13a93.png)


`actionBarHidden="false"`

![screenshot 7](https://cloud.githubusercontent.com/assets/17448734/15174000/11420ae0-1768-11e6-8fa4-141ff1536265.png)

Can you tell me more about the given abnormality or sent us a simple project which shows the problem.
