### ISSUE TITLE
[iOS] ActionBar background-color issue

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#2091]
I recently started testing my app on tablets, in order to create more tablet-specific views. I noticed this on iOS when using & simulating the app on "iPad 2" and "iPad Retina". It seems like the coloring either is not properly applied or the "translucent" flag is not being set. 

Color-code used: `#03396C`
I also use this in the main view: `frameModule.topmost().ios.controller.navigationBar.translucent = true;`

The result:
![](https://dl.dropboxusercontent.com/u/33168380/actionbar_ios_devices.png)

CLI: 2.0.0
Cross-platform modules: 2.0.0
Runtime(s): tns-ios: 2.0.0

**Comment by tsonevn** [comment]
Hi @manijak 
Thank you for you issue.

I was unable to reproduce this issue. Could you give me more specific example how to reproduce  this problem or to send me sample project. Actually `translucent` property should be set by default to `true`

 Regards,
@tsonevn

**Comment by manijak** [comment]
@tsonevn Sure thing, sample app added.

Added ActionBar background-color in the .css file. 

Then ran the following commands:
iPhone: `tns run ios --emulator --device 'iPhone 6' --sdk 9.3`
iPad 2: `tns run ios --emulator --device 'iPad 2' --sdk 9.3`

The color of the actionBar is like the images I posted above, not the same.

https://dl.dropboxusercontent.com/u/33168380/actionBarColor_sample.zip

**Comment by tsonevn** [comment]
Hi @manijak,

I reviewed your problem one more time. I confirm this is an real problem. Actually this issue is appearing, when you try to make custom title view instead of using the `ActionBar` title. I am attaching some code snippets, which are reproducing this abnormality.

main-page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <Page.actionBar>
     <ActionBar title="test" icon="" id="actionBar" class="actionBarClass">
         <StackLayout id="stack" orientation="horizontal"
      ios:horizontalAlignment="center"
      android:horizontalAlignment="left">
          <Image src="res://icon" class="action-image"></Image>
          <Label text="NativeScript"  class="action-label"></Label>
      </StackLayout>
     </ActionBar>
 </Page.actionBar>
</Page>

```
app.css
```
ActionBar{
    background-color:#03396C; 
}
```

Regards,
@tsonevn

**Comment by tzraikov** [comment]
@manijak Actually this is not an issue. Navigation bar appears and behaves in a different way on iPhone and on iPad. You can get exactly the same color only when translucency is disabled. Note also that colors may look different on simulator than a device.
