### ISSUE TITLE
declarations.*.d.ts files missing from published package

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#2095]
I'm just trying out the newly published platform declarations d.ts files. But using `tns-core-modules` and `tns-platform-declarations` packages I still face problems compiling correctly code that uses `interop` for iOS for example. From what I see that is defined in the `declarations.ios.d.ts` file which is missing from both packages. I guess that there will be problems when you use something specific from the android specific file as well. Thus I think those files should be published as part of either `tns-core-modules` or `tns-platform-declarations` packages

**Comment by PeterStaev** [comment]
Hey @tsonevn , 

Where were the declarations added? I've just downloaded from npm the platform declaration module and the core modules and they are still missing.

**Comment by tsonevn** [comment]
Hi @PeterStaev ,

You should have `tns-platform -declarations` folder inside the `node_modules` folder. There you could find `declarations.*.d.ts` files.


Regards,
@tsonevn

**Comment by PeterStaev** [comment]
Hey @tsonevn , this what i see:
![image](https://cloud.githubusercontent.com/assets/9464097/17508681/d6027be2-5e1e-11e6-9e4b-4be787bc01f9.png)

**Comment by tsonevn** [comment]
Hi @PeterStaev, 

Excuse me for misunderstanding your question,

Could you provide some more details about the missing `declarations.*.d.ts` files? I thought that you are looking for ios.d.ts and  android17.d.ts files, but maybe I am wrong.

Regards,
@tsonevn

**Comment by PeterStaev** [comment]
@tsonevn , I'm talking about these two files:
Android:
https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/declarations.android.d.ts

iOS:
https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/declarations.ios.d.ts

**Comment by PanayotCankov** [comment]
Hi,
iOS: https://github.com/NativeScript/NativeScript/blob/master/tns-platform-declarations/ios/interop.d.ts
Android: https://github.com/NativeScript/NativeScript/blob/master/tns-platform-declarations/android/declarations.d.ts
They are both referenced in the:
https://github.com/NativeScript/NativeScript/blob/master/tns-platform-declarations/ios.d.ts
and
https://github.com/NativeScript/NativeScript/blob/master/tns-platform-declarations/android.d.ts
Please if we are missing something open a new issue, this one is getting rather old.

**Comment by PeterStaev** [comment]
@PanayotCankov , agreed. With the 3.0 definitions I had no problems with the definitions so far!
