### ISSUE TITLE
Error in Android Emulator..

### ISSUE THREAD

**Issue by asadsahi** [NativeScript/NativeScript#2096]
Running "tns run android --emulator" command comes up with this error in android emulator.

![image](https://cloud.githubusercontent.com/assets/3470892/15213440/1d8c673c-183f-11e6-8caf-93f779a3a54f.png)

Any idea if I have missed anything?

Thanks

**Comment by tsonevn** [comment]
Hi @asadsahi,

Thank you for your question
In my opinion, there is problem with some of the modules. You could follow  those [upgrade instruction](http://docs.nativescript.org/releases/upgrade-instructions) from our documentation. 
Please let me know if you are still having any problems.

**Comment by asadsahi** [comment]
Thanks @tsonevn 

Now having this error:

![gihub](https://cloud.githubusercontent.com/assets/3470892/15243780/aca245b6-18f5-11e6-8647-03df044f07c1.png)

**Comment by tsonevn** [comment]
Hi @asadsahi,

Could you try to remove `platform` ones again with `tns platform remove android` and than to run `tns run android`.

Please, Let me know if this is applicable for you.
