### ISSUE TITLE
StackLayout + Label with horizontal-align renders differently on iOS and Android

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#2107]
Tested on iOS 9.3 and Android API 23
When we have **StackLayout** with **Label** as a child and we set horizontal-align:center the result is that the **Label position** renders differently on the different platforms. 
Code to reproduce the issue: 
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <StackLayout>
      <Label text="Label" fontSize="24"/> 
      <Button text="TAP" tap="" />
  </StackLayout>
</Page>
```

```
StackLayout {
    horizontal-align: center;
    width: 100%;
    height: 100%;
}
```
result
![screen shot 2016-05-13 at 3 46 07 pm](https://cloud.githubusercontent.com/assets/18008302/15248255/e4630824-1921-11e6-905f-cc25b2b6be25.png)

**Comment by Obsessive** [comment]
In android what is happening is that, you have set the width and height of stacklayout as 100% it covers the whole screen and the layout will be center horizontally but  the views inside it wont be horizontally center to get the text center you need to do this

`<Label text="Label" fontSize="24" class="textcenter"/> `

```
.textcenter{
  text-align: center;
}
```

**Comment by Obsessive** [comment]
![screenshot_2016-05-21-01-16-27 1](https://cloud.githubusercontent.com/assets/17127448/15440429/ffc02e7c-1ef2-11e6-8caa-a48d1101a166.png)

**Comment by Obsessive** [comment]
So I think ios is not rendering it correctly.

**Comment by Obsessive** [comment]
It feels that ios is wrapping the views.

```
width: 100%;
height: 100%;
```

is not applied to the stacklayout in ios.

**Comment by Obsessive** [comment]
Can you post the screenshot of ios version in which the stacklayout has some background other than white to check whether stacklayout is filling the entire screen or not.

**Comment by hamorphis** [comment]
Everything is working exactly the same on both platforms.

I removed all the CSS, colored all the elements and added small margins so you can better see what goes where. Here is what the following XML will produce on both platforms:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" style.backgroundColor="green">
  <StackLayout style.backgroundColor="yellow" margin="5">
      <Label text="Label" fontSize="24" style.backgroundColor="red" margin="5" style.textAlignment="center"/> 
      <Button text="TAP" style.backgroundColor="blue" margin="5"/>
  </StackLayout>
</Page>
```
![screen shot 2016-06-29 at 2 35 08 pm](https://cloud.githubusercontent.com/assets/1201857/16450702/21ec301c-3e07-11e6-8217-990cd085e35c.png)

**Comment by hamorphis** [comment]
Sample project: https://github.com/hamorphis/issue-2107

**Comment by hamorphis** [comment]
Everything is working correctly and in identical manner on both platforms so I will close this issue, since there is no issue at all.
