### ISSUE TITLE
using fontModule.ios.registerFont("some-font.ttf") will always log error

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#2109]
_From @NickIliev on May 13, 2016 13:35_

registering custom font for iOS is always logging error although it works
Here is the error
```
CONSOLE ERROR file:///app/tns_modules/trace/trace.js:160:30: Error: Error occur while registering font: The operation couldn’t be completed. (com.apple.CoreText.CTFontManagerErrorDomain error 105 - Could not register the CGFont '<CGFont (0x7b7d2650): Sansation-Light>')
May 13 16:26:29 mcsofniliev regFontsIos[25445]: 
```

Code to reproduce this behavior (tested with three different fonts in app/fonts folder - all are loaded successfully n the application but all three log this error)

app.ts
```
import application = require("application");
import fontModule = require("ui/styling/font");

if (application.ios) {
    fontModule.ios.registerFont("Sansation-Light.ttf");
    fontModule.ios.registerFont("Roboto-Regular.ttf");
    fontModule.ios.registerFont("Pacifico.ttf");
}
application.start({ moduleName: "main-page" });
```
All test fonts are located in **_app/fonts_**

_Copied from original issue: NativeScript/nativescript-cli#1759_

**Comment by NordlingArt** [comment]
I reported this a week ago: #2052. Doesn't seem like you need to include this line of code anymore because the font automatically gets included without.
