### ISSUE TITLE
Documentation: Add an article explaining how simple layouts are done for web devs

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#212]
I know we have [this article](http://docs.nativescript.org/layouts), but it doesn't show you how a basic layout is done and it is hard for web dev to get started with our layout system. We should start with simple scenarios and show the analogies.

**Comment by emiloberg** [comment]
The layout tutorial in the online AppBuilder is actually quite good - maybe reuse that?

**Comment by valentinstoychev** [comment]
Yes, definitely. We should also add content about how to convert HTML layout to {N}.

**Comment by jlooper** [comment]
I think it's quite tricky to move from a hybrid mobile 'mindset' to a {N} mindset, especially if you are creating an image-heavy app where you need content scaling to behave itself. I like the idea of showing use cases for each layout (why would you use a grid? a stack? why combine them? why use a wrap layout? who needs absolute?) and giving copy/pasteable code for each to onboard folks more easily.

**Comment by enchev** [comment]
This issue was moved to NativeScript/docs#124
