### ISSUE TITLE
The navigation bar duplicates when going to TabView's "More" tab

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#2121]
### Which platform(s) does your issue occur on?

iOS

### Please provide the following version numbers that your issue occurs with:

NativeScript 2.0.0

### Please tell us how to recreate the issue in as much detail as possible.

If you navigate from page A to page B which contains a TabView element with more items than it could show and go to the "More" tab, than the navigation bar duplicates.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Navigate to the following page:
https://github.com/NativeScript/NativeScript/blob/master/apps/ui-tests-app/css/tab-view-more.xml

![tabview](https://cloud.githubusercontent.com/assets/12251337/15295148/d559bd5a-1b97-11e6-8222-1dc67c60b088.png)

![tab-view](https://cloud.githubusercontent.com/assets/12251337/15295020/4e2e2cc6-1b97-11e6-8703-fb75dc42677d.png)

**Comment by hamorphis** [comment]
Sample project: https://github.com/hamorphis/issue-2121
