### ISSUE TITLE
How to set java version to 1.7

### ISSUE THREAD

**Issue by duongnhatduy** [NativeScript/NativeScript#213]
I run to this error when trying to import FacebookSDK to android platform. 

-compile:
    [javac] Compiling 151 source files to /Users/duyduong/Dev/tns/lib/Android/FacebookAndroidSDK/bin/classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] /Users/duyduong/Dev/tns/lib/Android/FacebookAndroidSDK/src/com/facebook/AccessToken.java:559: error: diamond operator is not supported in -source 1.5
    [javac]         ArrayList<String> permissionsList = new ArrayList<>();
    [javac]                                                           ^
    [javac]   (use -source 7 or higher to enable diamond operator)
    [javac] /Users/duyduong/Dev/tns/lib/Android/FacebookAndroidSDK/src/com/facebook/AccessTokenManager.java:224: error: diamond operator is not supported in -source 1.5
    [javac]         final Set<String> permissions = new HashSet<>();
    [javac]                                                     ^

The FacebookSDK version is 4.1.2.

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#74
