### ISSUE TITLE
HTTP Module Unicode issue

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#2130]
### Did you verify this is a real problem by searching 
Yes

### Tell us about the problem
HTTP module seems to be producing an error in NS 2.00 (might have been occurring at any point since 1.4 -- it worked fine in 1.40)

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
2.00 everything,  No plugins

### Please tell us how to recreate the issue in as much detail as possible.
Clone http://github.com/GettingStartedWithNativeScript/Chapter_4
Start the CrossCommunicator app on the android platform, and it should show an error...

The actual callstack error: 

> W/System.err( 1834): java.net.ProtocolException: Unexpected status line: 773}HTTP/1.1 200 OK
> W/System.err( 1834):    at com.android.okhttp.internal.http.RawHeaders.setStatusLine(RawHeaders.java:108)
> W/System.err( 1834):    at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
> W/System.err( 1834):    at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
> W/System.err( 1834):    at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java: 644)
> W/System.err( 1834):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
> W/System.err( 1834):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
> W/System.err( 1834):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:160)
> W/System.err( 1834):    at com.tns.Async$Http$RequestResult.getHeaders(Async.java:127)
> W/System.err( 1834):    at com.tns.Async$Http$HttpRequestTask.doInBackground(Async.java:314)
> W/System.err( 1834):    at com.tns.Async$Http$HttpRequestTask.doInBackground(Async.java:265)
> W/System.err( 1834):    at android.os.AsyncTask$2.call(AsyncTask.java:288)
> W/System.err( 1834):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> W/System.err( 1834):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> W/System.err( 1834):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
> W/System.err( 1834):    at java.lang.Thread.run(Thread.java:841)
> 
> 

The headers returned according to chrome (which has no issues) is:
> HTTP/1.1 200 OK
> Content-Length: 611
> Content-Type: text/plain
> Date: Wed, 18 May 2016 02:39:04 GMT
> Connection: keep-alive

The data returned is a properly formatted JSON text string.

--- 

After doing more testing -- the issue appears to be caused by unicode in the text stream.  The http component doesn't seem to able to handle unicode values.

**Comment by NickIliev** [comment]
Hi @NathanaelA 

I have tested the described scenario with NativeScript 2.0.0 but in my case the app is building with no build errors.
![untitled](https://cloud.githubusercontent.com/assets/18008302/15353042/b917ad56-1cef-11e6-8646-46cd6eaf265b.png)

Let me know if there is another specific step that I am missing - I have cloned the repository and started the application in **_crossCommunicator_** folder

**Comment by NathanaelA** [comment]
You must have missed the small update at the end.   The issue actually caused when their is unicode in the stream.  The HTTP module will throw that error when pulling any unicode text.  If you would like to see the issue, click settings in the app and switch the port to 3002 and then restart the application.    I have setup a server on *nativescript.rocks:3002* that returns unicode to the client in AJAX mode.   (My default server, I strip it out so that people can't break it, since I figured out what was causing the issue... ).  :)

**Comment by victorsosa** [comment]
Can you post the response header please?

**Comment by victorsosa** [comment]
Can you post the JSON response please?

**Comment by NathanaelA** [comment]
Hmm, this might not be fully(or at all) your problem.   When I was copying the response it appears the server is miscounting the size of the content being returned (because of the unicode); so the packet being sent is larger than the content-length is specifying; so then NS it complaining about the rest of the data coming over the wire I believe.

Chrome just shows the packet truncating the rest of the data after the content length.  Noticing the missing the trailing } was what finally gave it away...  

 However I'm not sure who should be responsible for the error.   Your http component is correct something is wrong; but should it listen to what the server said (i.e. 20 chars) and only return the first 20 chars and ignore the rest like browsers do; so that when I went to parse the data I would realize their was a data issue, or should the http component throw a weird error (like StatusLine error) when something is wrong?

**Comment by NathanaelA** [comment]
I can confirm that it is a malformed packet that is causing the issue.   I have updated the server code to use a different technique to get the full character count being passed onto the wire and now it fully works. 

---

  However, on a malformed packet (where the characters count is less than those on the wire) who should be responsible in this case?

Please feel free to close this issue if you feel the current error

> java.net.ProtocolException: Unexpected status line: 773}HTTP/1.1 200 OK

Is the proper way to proceed in a malformed packet.   I'll leave :3002 up with it producing a malformed packet in case you are going to pursue a better method of handling this error.

**Comment by NathanaelA** [comment]
Oh, and the direct url for the data is:
http://nativescript.rocks:3002/direct/get
   Basically the rest of the timestamp field and the final closing } is getting cut  and are being picked up by the http component as a new packet and then it is throwing the error..

**Comment by NickIliev** [comment]
@NathanaelA 

Ok I was **not** able to reproduce the error even when setting port 3002 thorught the app settings.
In fact at this very moment I got only response from http://nativescript.rocks/direct/get 
and i have zero response from http://nativescript.rocks:3002/direct/get
(tested w/Postman and w/CrossCommunicator app)

I am also not sure if error caused by malformed response packet should be handled by {N}
ping @enchev @PanayotCankov @hshristov - opinions?

**Comment by NathanaelA** [comment]
Ok, that is weird, I just clicked and tried this link: http://nativescript.rocks:3002/direct/get  (in the browser) and it returned the response properly.   (Well the broken response).
Tested in: Firefox & Chrome & crossCommunicator.     Do you have a firewall running that is blocking port 3002?

**Comment by enchev** [comment]
Hey @NathanaelA do you still have this issue?

**Comment by NathanaelA** [comment]
@enchev -- It seems like the http component is no longer crashing out!   So that is good news; and it is calling the onError routine properly!   But the request.status still = 200 (meaning success).      Not sure if you want this in another bug; or to track it here; or what...  In my opinion having the onerror called while leaving request.status=200 is more of a corner case; but not a big issue...

**Comment by enchev** [comment]
Hey @NathanaelA,

According to your original post Chrome will report exactly the same status (200).

**Comment by NathanaelA** [comment]
Agreed, but just because Chrome reports 200; doesn't mean that is the best way to do it.  Although 200 is actually coming from the server; so I would guess this is not your issue..  LOL closing...
