### ISSUE TITLE
How to give line height for paragraph in NS 

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#2131]

**Comment by NickIliev** [comment]
@dhanalakshmitawwa 

Line-height is currently not supported but is a feature request in NativeScript as discussed at issue  [#1664](https://github.com/NativeScript/NativeScript/issues/1664)
At this very moment the way to control your line height is to use the native APIs of iOS and Android.
At the above link there is also a sample code that can be used to achive control over line-height on Label element for Android and iOS.

**Comment by NickIliev** [comment]
@dhanalakshmitawwa 

Here is a sample code using the native APIs that worked out for my test application

```
function labelLineHeight(nsLabel) {

    if(application.ios){
        var label= nsLabel.ios;
        var attributedString;

        if(label.atributedText){
            attributedString = label.atributedText;
        }
        else{
            attributedString = NSMutableAttributedString.alloc().initWithString(label.text);
        }
        var paragraphStyle = NSMutableParagraphStyle.alloc().init();
        paragraphStyle.lineSpacing = 55;
        var range: NSRange = { location: 0, length: label.text.length };
        attributedString.addAttributeValueRange(NSParagraphStyleAttributeName, paragraphStyle, range);
        label.attributedText = attributedString;
    }
    if(application.android){
        var label = nsLabel.android;
        //Default spacing is 20% of text size
        //setLineSpacing(add,multiplyby);
        label.setLineSpacing(12, 1);
    }   
}
```

**Comment by enchev** [comment]
Merged with https://github.com/NativeScript/NativeScript/issues/1664

**Comment by dexter2019** [comment]
Hello @NickIliev  following your solution I just tried to add an image inside the textview using native NSAtrributedstring and NStextAttachment, getting some help from this article. [here](https://stackoverflow.com/questions/24010035/how-to-add-image-and-text-in-uitextview-in-ios)



However, I am unable to do it.  I am using nativescript-mediafilepicker library to add the image from the Photo library, then converting the PH image to UIImage using one its inbuilt method. But the textview is not getting updated with the image. However, I am being able to add more string through the NSattributedstring but not image. 

here's my code.

`
     
                   //creating and initilizing new NSMutableAttributedString
                       var attributedString = NSMutableAttributedString.alloc().initWithString(textview.ios.text);
                       textview.ios.attributedText = attributedString;

                      //value is an UIImage object what the convertPHImageToUIImage method returns
                       var image = value;

                      console.log(image);
                      //the above log prints<UIImage: 0x2817ac4d0> size {4032, 3024} orientation 0 scale 1.000000



                      let oldWidth = image.size.width;
                      // console.log(oldWidth);
                      let scaleFactor = oldWidth / (textview.ios.frame.size.width - 10);
                        //console.log(scaleFactor);
                      let orientation="up";

                        //create NStextAttachment

                       let textAttachment = NSTextAttachment.alloc().init();
                       //adding UIImage object to NSTextAttachment
                        textAttachment.image = UIImage.imageWithCGImageScaleOrientation(cgimage.CGImage ,scaleFactor , orientation)
                      // console.dir(textAttachment);

                       //creating a new NSAttributedString
                        let attrStringWithImage = NSAttributedString.alloc().init();
                        //console.dir(attrStringWithImage);
                        attrStringWithImage.attachment = textAttachment;
                        //console.dir(attrStringWithImage)

                       //appenind the NSAttributedString to the mutable string..
                        attributedString.appendAttributedString(attrStringWithImage);
                        //console.log(attributedString.containsAttachmentsInRange(textview.ios.selectedRange));
                        textview.ios.attributedText = attributedString;
                      
                         //textview.ios.textStorage.insertAttributedStringAtIndex(attrStringWithImage,textview.ios.selectedRange.location)
                        //this doesn't work either

`

would be great if anyone can help. I have been trying since long. I really need to do this :)
