### ISSUE TITLE
Add linear gradient color in NS for CSS background

### ISSUE THREAD

**Issue by karumurikiran** [NativeScript/NativeScript#2132]

**Comment by enchev** [comment]
Hey @karumurikiran,

I've [recently added](https://github.com/NativeScript/NativeScript/pull/2102) support for `clip-path` CSS property and I will extend this with `linear-gradient` as well!

Here is something for iOS already working:

```XML
 <Button text="rect" style="clip-path: linear-gradient(90deg, red, orange, yellow, green, blue, indigo, violet); border-width:2; border-color: blue; " />
```

![screen shot 2016-05-18 at 3 05 43 pm](https://cloud.githubusercontent.com/assets/5804953/15357860/12a5648e-1d0a-11e6-9f4c-75a6bab5fe5d.png)

**Comment by enchev** [comment]
Actually it will be better if we can specify `linear-gradient` as CSS `background`. In this case we will have both gradient and shape if needed.

**Comment by sitefinitysteve** [comment]
Lets get this bad-boy into the docs asap

**Comment by enchev** [comment]
Added: https://github.com/NativeScript/docs/commit/035751119eed1f5c8d02d7a24a8365e364765bf4

**Comment by NathanaelA** [comment]
@enchev; is **linear-gradient** actually supported; I'm not seeing any code for this in the tns-core-modules...

**Comment by enchev** [comment]
@NathanaelA Unfortunately still not. Not enough time to finish this.

**Comment by Robophil** [comment]
has this been added yet?

**Comment by OPADA-Eng** [comment]
Is it added or not ?

**Comment by toddanglin** [comment]
I suggest closing this issue and tracking further updates on support for CSS gradients in {N} here:
https://github.com/NativeScript/NativeScript/issues/539
