### ISSUE TITLE
Fetch Module not working since tns-core-modules 2.0.0

### ISSUE THREAD

**Issue by terreb** [NativeScript/NativeScript#2139]
I'm surprised this issue has not been created yet. After update tns-core-modules to 2.0.0 all fetch requests fail. This happens when debugging.

**Which platform(s) does your issue occur on**?
iOS

**Please provide the following version numbers that your issue occurs with**:
- CLI: 2.0.0
- Cross-platform modules: 2.0.0
- Runtime(s): 2.0.0
- Plugin(s): no

**Please tell us how to recreate the issue in as much detail as possible**.

$ tns create my-app-name --template tns-template-blank

then copy-paste the next in main-page.js:

```javascript
fetch("https://httpbin.org/get").then(function (r) {
    console.log('success', r)
}, function (e) {
    console.log('error', e)
});
```

$ tns debug ios --emulator

Now, see console messages.

**Comment by tsonevn** [comment]
Hi @terreb, 
Thank you for reporting this issue.
I tested the given code snippet and I could confirm that this is an real problem when you are using Fetch Module with  `tns debug ios --emulator` and `tns debug ios`. I am attaching my sample project:

https://github.com/tsonevn/FetchModule.git

As temporary decision if it is not necessary to debug your app, you could use `tns run ios --emulator`.

**Comment by terreb** [comment]
Hi @tsonevn,

Unfortunately, this is necessary, that's what I use 80% of time while developing and the app relies on https request to work. Probably this is different for other devs, I dunno...

So, please guys add a fix for this asap.

Thank you!

**Comment by tsonevn** [comment]
related to [#557](https://github.com/NativeScript/ios-runtime/issues/557)
