### ISSUE TITLE
fibers dependency issue

### ISSUE THREAD

**Issue by victorsosa** [NativeScript/NativeScript#2140]
### Did you verify this is a real problem by searching 
yes

### Tell us about the problem
Trying to run tns after been installed got this issue; the command is trying to get
v8-4.6/fibers.node but my system had installed **linux-x64-v8-3.14**/ and **linux-x64-v8-3.28**/ installed.

This seems to be a dependency issue.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
2.00 everything, No plugins

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```
[vns@localhost workspace]$ tns
/usr/lib/node_modules/nativescript/node_modules/fibers/fibers.js:16
	throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibers`?');
	^

Error: `/usr/lib/node_modules/nativescript/node_modules/fibers/bin/linux-x64-v8-4.6/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/usr/lib/node_modules/nativescript/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/lib/node_modules/nativescript/node_modules/fibers/future.js:2:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
[vns@localhost workspace]$ /usr/lib/node_modules/nativescript/node_modules/fibers/bin/linux-x64-v8-3.
linux-x64-v8-3.14/ linux-x64-v8-3.28/ 





```

**Comment by NickIliev** [comment]
Hello @victorsosa 

This error is caused when using Node.js version version  6.x.x.
At this moment version 6.x.x of node.js is not supported by many npm packets which is causing installing the dependencies to fail. 
For NativeScript at this moment the supported versions for Node.js are 0**.10.x, 0.12.x, 4.x, or 5.x stable official releases**

Related to [https://github.com/NativeScript/NativeScript/issues/2122](https://github.com/NativeScript/NativeScript/issues/2122)

**Comment by victorsosa** [comment]
Sorry but my nodejs version is v5.7.0

**Comment by NickIliev** [comment]
@victorsosa 
Can you try with another version of Node.js - I am using [this](https://github.com/coreybutler/nvm-windows) to switch version easily and the exact same error appear when switch on version ^6.X.X 
and in meanwhile when I switch to 4.4.0 or 5.9.0 I have no issues

**Comment by victorsosa** [comment]
@NickIliev Nop, I tried with 5.9.1 still getting the same issue and I am using Linux Fedora 23

**Comment by aderbas** [comment]
My Node version is v6.7.0 and get this error =/
I can not downgrade because of the angular-cli

**Comment by careuno** [comment]
Same issue with node 7.1.X, any solution?

**Comment by victorsosa** [comment]
I am using v5.9.1 and it is working fine now, with tns v2.2.1

**Comment by Splaktar** [comment]
Looks like this was fixed for Node 7.x in https://github.com/NativeScript/nativescript-cli/pull/2157. I'm still seeing the error with Node 6.7.0 though.

**Comment by NickIliev** [comment]
@Splaktar try updating to LTS version (6.9.2)

**Comment by bgdsh** [comment]
the same problem, even can not run `tns doctor`

**Comment by CristianHCol** [comment]
Change you version of node with nvm , i try in the v7.6.0 and doesnt work, but i change for v7.5.0 and work!

**Comment by lerv22** [comment]
I got the issue using Node.js 8.2.0
