### ISSUE TITLE
Side drawer position

### ISSUE THREAD

**Issue by Pip3r4o** [NativeScript/NativeScript#2141]
_From @eduardoturconi on May 18, 2016 19:16_

Hello.

I'm trying to use the RadSideDrawer from Telerik NativeScript UI, the code is almost exactly to the one provided in telerik docs.
But, when I set the property showOverNavigation to true, the layout becomes like this:
![screenshot_20160518-161113](https://cloud.githubusercontent.com/assets/4389868/15371815/b82e7892-1d13-11e6-9c31-62f1434efc18.png)

As you can see, the side drawer and status bar top are equal, and there's a strange margin with the same size than status bar's height on the bottom of the side drawer.
I'm using nativescript version 2.0

_Copied from original issue: NativeScript/android-runtime#458_

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-samples#90
