### ISSUE TITLE
How to downgrade nativescript version? 

### ISSUE THREAD

**Issue by yclau** [NativeScript/NativeScript#2150]
Hi,
After I update to new version 2.0 , it cause many issues in cocoapods especially MBProgressHUD using nativesceript-loading-indicator. How to downgrade native script version? this error when archive it

![screen shot 2016-05-20 at 10 45 49 am](https://cloud.githubusercontent.com/assets/4135524/15415818/0ad4701e-1e78-11e6-93f8-e6df27655578.png)

**Comment by NathanaelA** [comment]
See my blog article at: http://fluentreports.com/blog/?p=303

**Comment by anorthwolf** [comment]
thanks,  that's helpful.
