### ISSUE TITLE
Add z-index to the public API

### ISSUE THREAD

**Issue by zeroum** [NativeScript/NativeScript#2151]
The zIndex property only exists in https://github.com/NativeScript/NativeScript/blob/master/ui/styling/style.d.ts

but not in 
https://github.com/NativeScript/NativeScript/blob/master/ui/styling/styling.d.ts

where it could be found by the TypeScript compiler and tools.

Is it meant to be private API thing?

**Comment by NickIliev** [comment]
@zeroum 

Thank you for noticing this issue - indeed the zIndex should be exposed in both files.

**Comment by spstratis** [comment]
Is it planned to add z-index support to all API levels that are supported by Nativescript? For example API 19?

**Comment by NickIliev** [comment]
@spstratis for API levels below 21 you can use as a workaround an absolute layout and order your elements - the last one will be placed on top.
For example:
```
    <AbsoluteLayout>
        <GridLayout width="200" height="200" backgroundColor="red" id="mr-red"/>
        <GridLayout width="100" height="100" backgroundColor="green" id="mr-green"/>
        <GridLayout width="50" height="50" backgroundColor="blue" id="mr-blue"/>
    </AbsoluteLayout>
```

If you want to dynamically change the order of an element you can again use the native API method **bringToFront()**

**_For example:_**
in your page.xml (three blocks but the smallest (mr-blue) will be hidden behind the green one)
```
    <AbsoluteLayout>
        <GridLayout width="200" height="200" backgroundColor="red" id="mr-red"/>
        <GridLayout width="50" height="50" backgroundColor="blue" id="mr-blue"/>
        <GridLayout width="100" height="100" backgroundColor="green" id="mr-green"/>
    </AbsoluteLayout>
```

in your page.js
```
var blue = page.getViewById("mr-blue");
blue.android.bringToFront();
```

This will bring mr-blue to the front

**Comment by spstratis** [comment]
@NickIliev Thanks, I will try this out and see if it works. In my case everything is within a GridLayout.
