### ISSUE TITLE
android builds fail on nativescript 2.0 

### ISSUE THREAD

**Issue by Obsessive** [NativeScript/NativeScript#2157]
with the following error
:asbg:runAstParser
couldn't find logDirectory so it will be created in place:/Volumes/SERVER/root/repos/STS/App-Division/ocd-cheats/platforms/android/build-tools/android-static-binding-generator/ast-parser/logs/i.txt
ERROR WRITING TO LOG FILE DIRECTORY : /Volumes/SERVER/root/repos/STS/App-Division/ocd-cheats/platforms/android/build-tools/android-static-binding-generator/ast-parser/logs
:asbg:runAstParser FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Volumes/SERVER/root/repos/STS/App-Division/ocd-cheats/platforms/android/build-tools/android-static-binding-generator/build.gradle' line: 53

* What went wrong:
Execution failed for task ':asbg:runAstParser'.
> Process 'command 'node'' finished with non-zero exit value 255

Seems to be reproducible on OS X .

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.0.1
- Cross-platform modules: 2.0.1
- Runtime(s): 2.0.0
- Java 1.8.0_92
Tns doctor says,
Your components are up-to-date.

No issues were detected.

### Please tell us how to recreate the issue in as much detail as possible.
```
tns create projectname
tns platform add android
tns build android
```
(also tried with tns build android@next)

# Temporary fix
Temporary fix : replace the build.gradle file from previous version of nativescript (1.7.1) in /platform/android

**Comment by Pip3r4o** [comment]
This issue was moved to NativeScript/android-runtime#460
