### ISSUE TITLE
Reorganize open source samples.

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#216]
We have several samples in our organization, but some are done using AppBuilder, some are using the OSS version of the CLI. Currently these two environments are not compatible. 

We need to make sure that the samples are compatible with both AppBuilder and CLI. Until AB adopt the latest {N} version, one way to achieve this would be to add a script that will convert from CLI to AB project and vice-versa.

Also we need to make the following steps for each sample:
 - [x] create automated build for it
 - [x] list it on docs.nativescript.org with appropriate description
 - [x] list it on nativescript.org in the future samples page

For 1.5
 - [ ] make sure the latest techniques and best practices are implemented in the sample apps
 - [ ] optimize loading time.
 - [ ] make sure the Readme.md file has the correct structure and running instructions
 - [ ] add comments per issue request (#79)

For 1.6
 - [ ] make them work in AppBuilder
 - [ ] add open in AppBuilder image like in the Friends sample

The officially supported samples are:
 - [Tasks](http://github.com/nativescript/sample-Tasks) supported by {N} team,
 - [TelerikNext](http://github.com/nativescript/sample-TelerikNext) supported by {N} team,
 - [Expensity](http://github.com/nativescript/sample-Xpensity) supported by @kvelikov,
 - [Groceries](http://github.com/nativescript/sample-groceries) supported by @tjvantoll,  
 - [Friends](http://github.com/nativescript/sample-friends) supported by @tbozhikov.

**Comment by vchimev** [comment]
[TelerikNEXT] (https://github.com/nativescript/sample-TelerikNext) should be refactored to use the [Telerik UI for NativeScript] (https://www.npmjs.com/package/nativescript-telerik-ui) plugin.

**Comment by tjvantoll** [comment]
I'd add that the samples should support the latest versions of iOS and Android. I think? they all do, but it would be good to verify, especially as new versions of iOS and Android get released.
