### ISSUE TITLE
Textields inside modal

### ISSUE THREAD

**Issue by denkomanceski** [NativeScript/NativeScript#2164]
## Details:
TextFields inside Modals are being covered by the keyboard when they are focused. On normal page it works fine. I am setting the modal to fullscreen: true.

Is this a bug or using textfields inside modal is wrong ?

Thanks

**Comment by tsonevn** [comment]
Hi @denkomanceski , 

Thank you for your issue.
I tried to recreate the abnormality in a local project, however it seems that the keyboard do not cover the textfield.
Could you me infromation how to reproduce this issue. 
It would help if we could give me more info how to replicate this behavior.

**Comment by denkomanceski** [comment]
Did you try it on modal or on normal page ? I will give you more information soon

**Comment by denkomanceski** [comment]
Here is a video from the problem: https://www.dropbox.com/s/iyhcdl3jr7bn7vj/IMG_2939.MOV?dl=0
I also tried it on normal (non-modal) page and its working fine. 


Another problem which exists with the modals is the following (maybe new issue is needed):
 The angular router doesnt work on modals (its not loading the default route if the modal is parent of <page-router-outlet>)

**Comment by tsonevn** [comment]
Hi @denkomanceski, 

In my opinion this this normal behavior, when you use `modal view`. I found this `nativescript plugin` [nativescript-iqkeyboardmanager](https://www.npmjs.com/package/nativescript-iqkeyboardmanager), which  could be used for moving `TextField` above the keyboard. As a option you could replace model view with normal View and to use this plugin.

I hope this helps.
