### ISSUE TITLE
Angular 2 navigation transitions

### ISSUE THREAD

**Issue by denkomanceski** [NativeScript/NativeScript#2165]
How to use transitions in navigation while using angular2 and the router? Is it possible? If it is not is it possible to use ```frameModule.topmost().navigate``` inside angular ? Sometimes the pages need to be shown from the bottom like modals instead of normal pages and I cant find a way to achieve it using angular

Thanks

**Comment by vjoao** [comment]
Not possible yet there are some hacks you can do.

**Comment by denkomanceski** [comment]
I'd do hacks .. Could you show me how?
Thanks

**Comment by vjoao** [comment]
ping @tjvantoll

**Comment by tjvantoll** [comment]
Hey @denkomanceski, our navigation documentation with Angular 2 is up at http://docs.nativescript.org/angular/core-concepts/navigation-angular. There’s a feature request to allow things like transitions and such to be customized open at https://github.com/NativeScript/nativescript-angular/issues/202.

**Comment by tjvantoll** [comment]
Closing in favor of NativeScript/nativescript-angular#202.
