### ISSUE TITLE
Errors extending NativeScriptActivity on Android

### ISSUE THREAD

**Issue by chimon2000** [NativeScript/NativeScript#2166]
## Versions
tns: 2.0.1
tns-core-modules: 2.0.1
tns-android: 2.0.0

## Description
When attempting to extend NativeScriptActivity, I run into several issues:

````
var app = require("application");
var mainActivity = com.tns.NativeScriptActivity.extend({
    onCreate: function (savedState) {
        console.log('loaded');
        // call the base NativeScriptActivity.onCreate method
        // the "this" variable points to a NativeScriptActivity instance
        this.super.onCreate(savedState);

        // create a button and set it as the main content
        var button = new android.widget.Button(this);
        button.setText("Hello World");

        this.setContentView(button);
    }
});

var applicationInitObject = {
    getActivity: function (intent) {
        // this method is called whenever a new instance of NativeScriptActivity is about to be created
        return mainActivity;
    },
    onCreate: function () {
        // This is the first method called. Called from the android.app.Application.onCreate method.
    }
}

app.init(applicationInitObject);
````
I took the example from [here](https://docs.nativescript.org/runtimes/android/getting-started/hello-world), and I assume that the information is stale since it refers to bootstrap.js. Unfortunately, I can't find anymore documentation around the feature.

**Comment by chimon2000** [comment]
## Further Details

What I am actually trying to do is extend the NativeScriptActivity to add an event for user interaction that I can handle on the JS side. I reviewed the blog post about [SBG](https://www.nativescript.org/blog/static-binding-generator---what-is-it-good-for), but could not figure out how to override NativeScriptActivity in `MyActivity.js`. Doing the following
````
com.tns.NativeScriptActivity.extend({
    onCreate: function (bundle) {
        this.super.onCreate(bundle);
        console.log('overwrite');
    }
});
````
 results in no `MyActivity.java` file being generated, and I get an error when the app loads.

I also attempted the following
````
var frameModule = require("ui/frame");
var mainActivity = Object.assign({
    onUserInteraction: function(){
        console.log('user interaction');
    }
}, frameModule)

android.app.Activity.extend("com.tns.MyActivity", mainActivity);
````
which results in just a blank screen being displayed.

**Comment by vjoao** [comment]
Maybe new it?

```
var frameModule = require("ui/frame");
var mainActivity = Object.assign({
    onUserInteraction: function(){
        console.log('user interaction');
    }
}, frameModule)

android.app.Activity.extend("com.tns.MyActivity", **new mainActivity()**);
```

**Comment by chimon2000** [comment]
@vjoao I attempted that with just the default Activity `new com.tns.NativeScriptActivity()` with the same result.

I also tried removing the assign and just passing in mainActivity. In both cases `MyActivity.java` was not generated. 

It appears that only passing the object directly into the method yields the expected outcome (makes sense because it is static).

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#462
