### ISSUE TITLE
Install Plugin failed archive to ITunes

### ISSUE THREAD

**Issue by yclau** [NativeScript/NativeScript#2167]
Hi 

### Tell us about the problem
I trying using plugin nativescript-material-loading-indicator and nativescript-loading-indicator, When I try to archive and publish to ITunes,it show me error below. After I remove loading-indicator and nativescript-material-loading-indicator, it work fine. 

```
ld: warning: directory not found for option '-F/Users/bae-nb-050/Library/Developer/Xcode/DerivedData/SL-fbodsjqbjvdhcgeemiobyapkoekm/Build/Intermediates/ArchiveIntermediates/SL/BuildProductsPath/Release-iphoneos/MBProgressHUD'
    ld: framework not found MBProgressHUD
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.0.1
- Cross-platform modules: 2.0.0
- Runtime(s): 2.0.0
- Plugin(s): 
1) nativescript-material-loading-indicator : 1.0.0
2) nativescript-loading-indicator 2.0.1
-cocoapods : 1.0.0

**Comment by enchev** [comment]
This issue was moved to NativeScript/ios-runtime#567

**Comment by yclau** [comment]
Hi, 

any update? I got urgent deployment for IOS. 
isn't got other method to by pass this case ?

**Comment by Mia12344** [comment]
i have the same issue @yclau  are you able to fix this?
