### ISSUE TITLE
iOS navigation bug

### ISSUE THREAD

**Issue by denkomanceski** [NativeScript/NativeScript#2168]
There are two bugs involved here. 

The first one is when I start navigating back on iOS (slowly sliding left to right) the action bar is losing the styling (its going white with blue letters) and the components on the page are disappearing.

The second one which is worse is if you dont navigate back but stay on the page after you trigger the navigation transition (slide back to the same view instead of navigating back) the app crashes (before it crashes bug no.1 comes and the page is blank).

Here is a video: https://www.dropbox.com/s/tfz18kuhyottcuc/IMG_2936.MOV?dl=0
(First I show the first bug, than both together)

Is there any workaround that could help?

Edit: I tried with the ng-sample app (the NavigationTest, the one that is using page router and normal router) and the excatly same error happens. Here is the error also:

```
file:///app/tns_modules/rxjs/Subscriber.js:229:22: JS ERROR TypeError: undefined is not an object (evaluating 'state.isPageNavigation')
May 24 23:30:13 DenkoMBP com.apple.CoreSimulator.SimDevice.B0C93223-F914-47B3-97F0-E6B1D8739AE5.launchd_sim[11323] (UIKitApplication:org.nativescript.ngsample[0xfa7][11393]): Service exited due to signal: Segmentation fault: 11
```

Thanks

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#257
