### ISSUE TITLE
How to give spacing in text field

### ISSUE THREAD

**Issue by karumurikiran** [NativeScript/NativeScript#2169]
![capture](https://cloud.githubusercontent.com/assets/10797035/15529452/0a00932e-226b-11e6-9bd1-3ea70288677c.PNG)

Hi,
In the above image, you can see two images, in left side image there is spacing between the user symbol, name and tick mark. How to give spacing in text field. I  tried, but i could not get it as shown in right side.

**Comment by NickIliev** [comment]
Hi @karumurikiran 

You can use CSS-property **_padding_** to control the TextField.
For example:
```
TextField {
    padding-left: 30;
    padding-right: 10;
    padding-bottom: 20;
    padding-top: 20;
}
```

You can also use formattedStrings to further modify your TextField
For example:
```
    <TextField>
        <TextField.formattedText>
          <FormattedString>
            <FormattedString.spans>
              <Span text="    Left " fontAttributes="Italic" foregroundColor="red"/>
              <Span text="Middle" fontAttributes="Bold" foregroundColor="green"/>
              <Span text="   Right" fontAttributes="Normal" foregroundColor="blue"/>
            </FormattedString.spans>
          </FormattedString>
        </TextField.formattedText>
    </TextField>
```
