### ISSUE TITLE
Replacing Ant with Buck?

### ISSUE THREAD

**Issue by emiloberg** [NativeScript/NativeScript#217]
Hi,

Have you had any thought of replacing Ant with [Buck](http://buckbuild.com/) for building the Android App? It could do quite a lot to decrease build speeds.

**Comment by enchev** [comment]
Hi @emiloberg,

As far as we know they have some problems with Windows support:
https://buckbuild.com/concept/faq.html

**Comment by emiloberg** [comment]
Ah gotcha! And having two build systems up and running will break the sanity of even the healthiest.
