### ISSUE TITLE
iOS ActionBar changes styles on initiated navigation

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#2171]
From @denkomanceski on May 24, 2016 21:7

The first one is when I start navigating back on iOS (slowly sliding left to right) the action bar is losing the styling (its going white with blue letters) and the components on the page are disappearing.

Here is a video: https://www.dropbox.com/s/tfz18kuhyottcuc/IMG_2936.MOV?dl=0
(First I show the first bug, than both together)

From @NickIliev - the second bug is moved to nativescropt-angular [#257](https://github.com/NativeScript/nativescript-angular/issues/257)

**Comment by tzraikov** [comment]
@denkomanceski This behavior is expected because in iOS the navigation bar is a single object that is shared between pages. When navigating back it takes its style from the previous page. In this scenario this is the default white background.
