### ISSUE TITLE
iOS onSuspend + showModal() returning "Error: This value is not a native object"

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#2173]
Issue logged from **Allan Krayer** on 23-May-2016 1:34:11 PM (ticket)

When app is suspended with setting the currentPage to show modalPage the app is throwing an error onResume: 
```
JavaScript error:
file:///app/tns_modules/ui/page/page.js:279:98: JS ERROR Error: This value is not a native object.
```

code to reproduce the behavior:

**_app.ts_**
```
import application = require("application");
import frameModule = require("ui/frame");

application.onSuspend = function () {
    console.log("Application suspended.");
    var currentPage = frameModule.topmost().currentPage;
    currentPage.showModal("./login-page", true, function closeCallback() {
        console.log("modal page closed");
    }, true);
}

application.start({ moduleName: "main-page" });
```

Create simple _**main-page**_ and _**login-page**_ in your main app directory.

Tested under Android (working) and iOS 9.3 (crashing) - issue noticed since last update 2.0.1 (worked with earlier version)
edit. reproduced with version 2.0.0 as well!

client log file : 
[660fc0b7-e807-4772-879b-f460bfe172c8_Log.zip](https://github.com/NativeScript/NativeScript/files/281375/660fc0b7-e807-4772-879b-f460bfe172c8_Log.zip)

**Comment by hamorphis** [comment]
I created a sample app here: https://github.com/hamorphis/issue-2173

I tested with tns-core-modules and tns-ios from the master branches and everything works correctly.

**Comment by hamorphis** [comment]
This happens on iOS 9+ only.
