### ISSUE TITLE
How to wirte code for different screens

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#2175]
![potrait](https://cloud.githubusercontent.com/assets/10844041/15538196/57303802-2298-11e6-8247-4e8512b88bf9.PNG)
![landscape](https://cloud.githubusercontent.com/assets/10844041/15538199/5fcc476c-2298-11e6-951a-970cee613bd0.PNG)

Hi, 
How to write the code for the above attached images. When i see in Portrait , i can see two images. when i rotate the landscape, i can see only two images, but i want see automatic three to four images when it was seen in landscape format.Please give me an example for this .

One more thing when i rotate Portrait to landscape the screen must be automatically adjusted. For that give me an example.

How write code for different screens resolutions like
 ex.  mobile,tab,with different in sizes.

**Comment by tsonevn** [comment]
Hi @dhanalakshmitawwa, 

I have made a little research an dI would two articles about this topic.
The first article is about supporting multiple screen resolution in your native script App.
[Multiple Screen Resolutions](https://www.nativescript.org/blog/details/supporting-multiple-screen-resolutions-in-your-nativescript-app).
Second one is more about, how to build responsive UI in android: 
[Responsive UI](https://www.google.com/design/spec/layout/responsive-ui.html#).

Indeed you could read about  usage of our [User Interface Layouts](http://docs.nativescript.org/ui/layouts) in NativeScript documentation.

**Comment by NathanaelA** [comment]
@dhanalakshmitawwa - I wrote a plugin that might be able to help; nativescript-orientation; this allows you to have per-orientation css so that your screen can re-layout when the orientation changes.    This only solves one part of your question, the other links that tsonevn left are worth reading.

**Comment by smarza** [comment]
@tsonevn @NathanaelA, Do you know if Supporting Multiple Screens is working on Angular?

I reviewed the link you provided, but nothing is working for me.
Thanks.

**Comment by NickIliev** [comment]
@smarza at this very moment screen-size qualifiers are not supported in Angular based application. Discussion regarding that matter can be found [here](https://github.com/NativeScript/nativescript-angular/issues/404)

**Comment by smarza** [comment]
@NickIliev Thanks!
