### ISSUE TITLE
Image doesn't support redirects

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/NativeScript#2176]
_From @jrz on May 24, 2016 11:33_

If I set the source to http://graph.facebook.com/XXXXX/picture?type=large, no image shows up.

How should I support (max)redirects?

_Copied from original issue: NativeScript/nativescript-angular#253_

**Comment by hdeshev** [comment]
It looks like a bug in the Android HTTP client (works fine on iOS). I added a reproduction project here:

https://github.com/hdeshev/nativescript-image-redirect

**Comment by angeltsvetkov** [comment]
We faced this problem developing demo apps for [native script-facebook](https://github.com/NativeScript/nativescript-facebook). On iOS it works just fine but on Android it looks like the redirect from http://graph.facebook.com/XXXXX/picture?type=large to the exact image url is not executed.

**Comment by manoldonev** [comment]
Tested with `<Image src="https://graph.facebook.com/4/picture?width=200&height=200"></Image>` -- seems to be working fine with latest version.
