### ISSUE TITLE
Additional Intents Crashes app

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#218]
If I add an additional Intent to the AndroidManifest.xml; then when it is triggered; the code in **tns_module/ui/frrame/frame.android.js**  in the function  **AndroidFrame.prototype.onActivityRequested** is triggered which throws and error and crashes the app.    I tried several ways to see if I could make this work; but it appears it doesn't allow me to add any additional intents.

Is their any way to have additional Activities triggered and either go to the same screen or do a different screen?

**Comment by slavchev** [comment]
Hi @NathanaelA,

Is this issue still actual? If so, can you provide more details how to reproduce it?

**Comment by NathanaelA** [comment]
@slavchev -- Don't know.  Haven't tested it since back in may.  Was changes done that should fix this issue.

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#218
