### ISSUE TITLE
[Android] Modal view & HTML5 video issue

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#2180]
In my app I have a modal view, with a WebView for showing HTML5 video (youtube). The only issue I have with this (android only) is that when a user starts a video, and then closes the modal, the audio continues to play in the background. And it cannot be stopped, even if you go back to the modal. 

Is there a way to get around this? Stop the media playing?

CLI: 2.0.0
Cross-platform modules: 2.0.0
Runtime(s): Android 2.0.0

**Comment by tsonevn** [comment]
Hi @manijak, 
Tank you for reporting your issue.

I reviewed your case and found that behavior is related with `NativeScript 2.0.0`. you could upgrading the `NativeScript to 2.0.1`, where this abnormality has been fixed. 

[Upgrade Instructions](https://docs.nativescript.org/releases/upgrade-instructions)

I hope this is applicable for you.
Kind regards

**Comment by manijak** [comment]
Had no idea 2.0.1 was out! Will do, thanks :)

**Comment by manijak** [comment]
Looks like 2.0.1 did the trick, worked as it should via Genymotion. 

Thanks!
