### ISSUE TITLE
Feature Request: Focus / Blur events

### ISSUE THREAD

**Issue by speigg** [NativeScript/NativeScript#2181]
Pretty self-explanatory. It would be useful to have `focus` and `blur` events (to mirror the DOM terminology) that are raised for a textfield, searchbar, or any other controls that can gain or lose focus. Also would be good to have a way to determine if a view currently has focus or not, like a `hasFocus` property.

**Comment by NathanWalker** [comment]
Alongside this pseudo selectors would be needed for theme project:
```
TextField:focus {  color: blue; }
```
for example.

**Comment by dbenninger** [comment]
I can't believe there is no focus and blur event. 

Has someone found a workaround?

**Comment by atellmer** [comment]
You may emulate focus/blur event with tap event and other. It is temporary decision, but it is works fine

**Comment by EddyVerbruggen** [comment]
FYI: There is a `blur` event these days. I'm thinking of doing a PR for `focus` as well.

**Comment by EddyVerbruggen** [comment]
#4730 pending review 🤞

**Comment by nabil-mansouri** [comment]
This feature will be added in the next release? I find it really important

**Comment by EddyVerbruggen** [comment]
@nabil-mansouri The PR has been merged, so 3.2 it will be - and you can grab `tns-core-modules@next` right now if you can't wait! 😃
