### ISSUE TITLE
Error: Unable to create layer for StackLayout

### ISSUE THREAD

**Issue by Daxito** [NativeScript/NativeScript#2190]
### Did you verify this is a real problem by searching

Yes, nothing found
### Tell us about the problem

I am using Telerik Analytics and there is this Uncaught Error that is showing in our logs a bunch of times, I am not able to duplicate it since I am not sure how, all I can see is the log and I guess a user whose App keeps crashing.
### Which platform(s) does your issue occur on?

Android 
### Please provide the following version numbers that your issue occurs with:
- CLI: 2.0.1
- Cross-platform modules: 2.0.1
- Runtime(s): Android 2.0.0
- Plugin(s): `"lodash": "^4.12.0",
      "moment": "^2.13.0",
      "nativescript-appversion": "^1.2.0",
      "nativescript-dom": "^1.0.3",
      "nativescript-drawingpad": "^1.0.2",
      "nativescript-geolocation": "0.0.11",
      "nativescript-globalevents": "^1.1.0",
      "nativescript-iqkeyboardmanager": "^1.0.1",
      "nativescript-loading-indicator": "^2.0.1",
      "nativescript-master-technology": "^1.0.4",     
      "nativescript-screenshot": "0.0.2",
      "nativescript-snackbar": "^1.0.3",
      "nativescript-sqlite": "^1.0.8",
      "nativescript-telerik-analytics": "^1.0.0",
      "nativescript-telerik-ui-pro": "file:plugins/nativescript-ui-pro.tgz",
      "numeral": "^1.5.3",
      "pubsub-js": "^1.5.3",
      "string": "^3.3.1"`
### Please tell us how to recreate the issue in as much detail as possible.

I don't know how to duplicate this issue, seems like random for the end user, my hope is that by looking at the call stack and the error message you can tell what could be wrong.
### Is there code involved?

I have the call stack

```
{
  "nativeException": {

  },
  "stackTrace": "java.lang.IllegalStateException: Unable to create layer for StackLayout
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:143)
at android.os.Looper.loop(Looper.java:122)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
"
}

```

**Comment by Daxito** [comment]
This issue is not happening on all devices, I was able to duplicate it on a Samsung Galaxy S6, Android 6.

Basically what we are doing is that we are loading input fields dynamically (on the "fly"), these fields are just pieces of XML (A Grid with children) stored in a separate file (an XML file), then we load them and add them into a StackLayout as children on demand, we use "ui/builder" for this. The app crashes with this error when adding to this Parent StackLayout X amount of fields, if I reduce the number of fields then it won't crash, but it does not always crashes with the same number of fields added, sometimes it crashes with 10, sometime with 11, or 9....

**Comment by hamorphis** [comment]
Can you please attach a small dummy sample project that reproduces this exception. Thank you.

**Comment by Milewski** [comment]
i also have the same issue.. there are a lot of reports on crash on google play... my devices itself never get these crashes... but according with google crash reports.. those devices are having trouble:

LG G3 (g3), Galaxy S7 (herolte) 4, Galaxy Note4 (trhplte), Galaxy Note4 (trelte), Galaxy S6 (zerofltechn), Galaxy Note4 (tre3caltektt), Xperia Z (C6603)Galaxy Note5 (nobleltehk) 1, Galaxy S7 Edge (hero2lte).... and the list goes on.. pretty much all galaxy devices.... 

running from version 5 to 6.0

```
java.lang.IllegalStateException: Unable to create layer for StackLayout
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5272)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
```

**Comment by Daxito** [comment]
@hamorphis @Milewski 

I was able to duplicate the issue in the attached App, I tested it using a Galaxy S5 Android 6.0.1 and Android 5.0.
My test case is just a StackLayout, I dynamically load a bunch of external XML components into it as children of course, the StackLayout is bound to a property in order to change the back ground color, so it is bound to the className property.
 
Please follow these steps to make it crash:
1. Run the app
2. Tap on Load Components, if crash does not happen check the code and increase the chunk of Components to load, but again, I just use a Galaxy S5.

Please follow these steps to make it work!:
1. Remove the binding  className from the Parent StackLayout
2. Run the app
3. Tap on Load Components as many times as you want, no crashing!

So, it does not like it that the Parent has this simple binding, if the parent is bound to the VM then it would crash, very interesting!

Let me know if you need more info from me.
[DynamicLayoutApp.zip](https://github.com/NativeScript/NativeScript/files/309511/DynamicLayoutApp.zip)

**Comment by mattgalvin** [comment]
I've been troubleshooting the same issue on my Nativescript/Angular2 application. My app crashes consistently on a Galaxy S4, and a Galaxy S5, but does not crash on a Galaxy Tab4 or any emulators. Not sure if this is the same cause as what @Daxito is seeing but the crash is identical.

I've narrowed it down to the use of ScrollView with a dynamically sizing StackLayout inside of it. The kicker is that it only crashes if the content would cause scrolling to be needed. Assuming lengthy content, the first structure here crashes every time and the second one works every time. This is a huge pain that I don't currently have a solution to because with dynamically generated content, I don't know the height that is needed (which is kind of the point of needing to scroll a list!).

<ScrollView>
  <StackLayout>
    ... a bunch of content that exceeds visible screen size
  </StackLayout>
</ScrollView>

<ScrollView>
  <StackLayout height="3000">
    ... a bunch of content that exceeds visible screen size
  </StackLayout>
</ScrollView>

**Comment by mattgalvin** [comment]
A little more research.. It seems that the problem is the inner StackLayout being too large. When I tested again, setting a height of 3000 caused the crash but setting a height of 1000 worked.

**Comment by enchev** [comment]
Hey @mattgalvin do you still have the same issue? @hshristov do you know what can cause this?

**Comment by hshristov** [comment]
@enchev I have to double check it but it seems like Android limitation.

**Comment by mattgalvin** [comment]
I refactored my code to avoid the problem but it was easy to test. I'll dig up the test project I made when I'm back at a computer. At heart yes,  it's an android limitation due to the virtual screen size limitations. But the only Android devices that I've seen the problems on are Galaxy devices. Other devices must implement the virtual page differently because they don't exhibit the problem. 

Also, the ListView does not have the problem so it seems like there might be something different in how ScrollView handles things internally that maybe could be refactored?

**Comment by Daxito** [comment]
@enchev I removed the binding from my stack layout, I just found another way of doing what I was doing, but it is not like the issue is really gone, my sample app I attached should be an easy test though.

**Comment by tsonevn** [comment]
Hi all,
I tested @Daxito [project](https://github.com/NativeScript/NativeScript/issues/2190#issuecomment-225255455), with the latest modules 3.4 and android-runtime 3.4.1. However was unable to recreate the reported issue.
@Daxito @milewski @mattgalvin can you check on your side if you are still able to recreate the problem?

**Comment by mattgalvin** [comment]
@tsonevn Not easily, I haven't done work with this project/client in over a year! If you say it's resolved, I have no reason to doubt you.
