### ISSUE TITLE
How to represent different font colors for each word in a sentence under label element .

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#2193]
How to represent different font colors for each word in a sentence under label element .

**Comment by tsonevn** [comment]
Hi @dhanalakshmitawwa ,

In NativeScript there are two possible options to set different color for each word.
The first one is to use `Formatted String` and `Span module`

```
             <Label cssClass="info-orange">
                    <Label.formattedText>
                      <FormattedString>
                        <FormattedString.spans>
                          <Span  text="sample text" fontAttributes="Bold" foregroundColor="red"/>
                          <Span  text="sample text2" fontAttributes="Bold"  foregroundColor="green"/>
                        </FormattedString.spans>
                      </FormattedString>
                    </Label.formattedText>
                  </Label>
```

And the second one is more Android specific. You can use android `fromHtml` method to insert the text. I am attaching an example below:

**main-page.xml**

```
<Page xmlns="http://www.nativescript.org/tns.xsd" navigatedTo="onNavigatedTo" xmlns:app="./Share">
  <StackLayout verticalAlignment="center" horizontalAlignment="center">
      <Label text="sample textcolor" textWrap="true" id="label" />
      <TextField hint="words color" id='textfield' text="" />
  </StackLayout>
</Page>
```

**main-page.js**

```
var app = require('application');

function onNavigatedTo(args) {
    var page = args.object;
    var textField = page.getViewById('textfield');
    var label = page.getViewById('label');
    if (app.android) {
        var text = "<font color=#cc0029>First color</font> <font color=#ffcc00>Second Color</font>";
        textField.android.setText(android.text.Html.fromHtml(text));
        label.android.setText(android.text.Html.fromHtml(text));
    }
}
```

**Comment by dhanalakshmitawwa** [comment]
Thank You for reply

**Comment by haris008** [comment]
@tsonevn span code is not working for me.

**Comment by tsonevn** [comment]
Hi @haris008,
I tested the below-attached code on my side with latest CLI 2.5.4 and everything seems to work as expected both iOS and Android.
```
<Label cssClass="info-orange">
                    <Label.formattedText>
                      <FormattedString>
                        <FormattedString.spans>
                          <Span  text="sample text" fontAttributes="Bold" foregroundColor="red"/>
                          <Span  text="sample text2" fontAttributes="Bold"  foregroundColor="green"/>
                        </FormattedString.spans>
                      </FormattedString>
                    </Label.formattedText>
                  </Label>
```
If you still have an issue while using `FormattedString` provide some sample project, which could be debugged locally.

**Comment by haris008** [comment]
[Groceries.zip](https://github.com/NativeScript/NativeScript/files/933420/Groceries.zip)

Please found above zip folder of sample project. I am also running with latest CLI 2.5.4. Also attached below is error I get. and If I remove self closing from span, I get "  is not a valid View instance."



![simulator screen shot apr 19 2017 3 21 00 pm](https://cloud.githubusercontent.com/assets/3274960/25175432/28d99b18-2514-11e7-92de-a252c00c2d3b.png)

**Comment by tsonevn** [comment]
Hi @haris008,
This is related due to a syntax error in the HTML file. While using `FormattedString` in NativeScript angular 2 projects every `Span` should have an opening and closing tag as you could see in the Angular part if the documentation [here](http://docs.nativescript.org/angular/code-samples/ui/formatted-string.html).
For example:
```
<FormattedString>
        <Span text="Words " foregroundColor="#006600" ></Span>
        <Span text="with " foregroundColor="#990000" fontAttributes="Bold"></Span>
        <Span text="different " foregroundColor="#ffcc00"></Span>
        <Span text="color."></Span>
    </FormattedString>
```

**Comment by haris008** [comment]
Removing tag of   <Label.formattedText> works (y) .
with this tag, it gives error
