### ISSUE TITLE
Remove bootstrap.js

### ISSUE THREAD

**Issue by ErjanGavalji** [NativeScript/NativeScript#22]
The current logic of the runtimes for starting an application is searching for a bootstrap.js, that can have the starting code. Due to the possibility of having the main application code file specified by the package.json (searched by default), the bootstrap simply has a require("./") statement, which makes it useless.

Let's default to the package.json file.

How about falling back to app.js if package.json not found?

**Comment by teobugslayer** [comment]
In https://github.com/NativeScript/nativescript-cli/issues/362 we are discussing to make package.json *the* project file. If we go this route, it will be a required file and we can safely use it.

I am strongly in favor of removing bootstrap.js.

**Comment by ligaz** [comment]
:+1: Let's remove this `bootstrap.js` legacy :smile: It will be way much simpler.

**Comment by atanasovg** [comment]
As we discussed, we will add support for package.json, which will search for a main file to start. If no package.json exists (or no main key is declared), the fallback will search for bootstrap.js.

**Comment by RangerMauve** [comment]
Maybe look for `bootstrap.js` after `index.js`? Most JS devs that use CommonJS would anticipate that `index.js` would get loaded in absence of a `package.json` or `main` field, and the `bootstrap.js` lookup would be more of a legacy thing.
