### ISSUE TITLE
Feature request: sticky scroll view headers

### ISSUE THREAD

**Issue by dbbk** [NativeScript/NativeScript#220]
In several places in iOS, such as the App Store, scroll views can have 'sticky headers', that stay at the top of the viewport when you've reached the top, but scroll away as you scroll down. Video demonstrating this: http://cl.ly/b4g1

It would be great if we could specify subviews of a scrollview - or if not, a list view - to act as sticky headers.

**Comment by Nathanaela** [comment]
Why wouldn't you do:
\<stackedlayout>
  \<your sticky header>
  \<scrollview>\<content>\</scrollview>
\</stackedlayout>

**Comment by dbbk** [comment]
Because then the header would be in view at all times, I'm talking about a header that scrolls away with the scroll view, but never goes past beyond offset 0 vertically.

**Comment by Nathanaela** [comment]
Ah, I see what you are talking about.   Sorry was thinking the opposite, having a always fixed header..  

So why not do:
```
<scrollview>
  <stackedlayout>
     <your header>
     <listview or repeatable><content></listview or repeatable>
 </stackedlayout>
</scrollview>
```

It obviously won't be as nice as the ability to pull down and have a small animated gap appear between the header and content as shown in your video; but that should allow you to have a header and content.

**Comment by dbbk** [comment]
Yep, that's what I do now. I'm submitting a feature request to be able to do it the better way.

**Comment by enchev** [comment]
Closing in favor of https://github.com/NativeScript/NativeScript/issues/524
