### ISSUE TITLE
NativeScript-Telerik-UI : toggle definition outdated for sidedrawer

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/NativeScript#2203]
The toggle method on the *index.d.ts* file for the sidedrawer in the UI Pro and free versions needs to be updated to match the docs and the correct toggle function:

http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/SideDrawer/programmatic#the-showdrawer-closedrawer-and-toggledrawerstate-methods.

This is in the def file: 
`
/**
    * Toggles the current state of the SideDrawer instance.
    */
    public toggleDrawerOpenState(): void;
`

and it needs to be `toggleDrawerState()`

I couldn't find a repo for this, is it still private?

**Comment by Daxito** [comment]
@bradmartin
I think the repo is 
https://github.com/telerik/nativescript-ui-samples
I posted an issue with the side drawer the other day

**Comment by enchev** [comment]
This issue was moved to telerik/nativescript-ui-samples#96
