### ISSUE TITLE
[Android] App install fails from GooglePlay - "Error 505"

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#2204]
We recently launched our app on Google Play and are receiving reports that some users are not able to install the app from Google Play Store. When pressing Install, the app downloads, starts the install procedure, then stops with an error message: "Cannot be installed, error code -505". 

We've asked the users to restart phone, clear caches and remove old versions of the app. Still the issue remains. We've even heard that this happens to users who never had a version of the app installed before.

Reading on some sites, they recommend to factory reset the device before installing, but we cannot ask our users to do that! 

Does anyone know what this might be and if we can resolve it via an update? 

The app is built using version 2.0.0 of {N}.

**Comment by NathanaelA** [comment]
Are you using any google services by any chance.

**Comment by manijak** [comment]
We are using GoogleAnalytics and GCM

**Comment by NathanaelA** [comment]
Well, then I believe I might have some good news for you.   See this issue and how to solve it..
https://github.com/NativeScript/android-runtime/issues/454 -- I'm not 100% sure if this is the -505 error (not seeing anything for 505), but if you haven't fixed this manually yet -- it will have random install issues on devices.

**Comment by manijak** [comment]
Thanks Nathanael, I'll give it a go and report back!

**Comment by NickIliev** [comment]
@manijak can you tell us if the solution for [#454](https://github.com/NativeScript/android-runtime/issues/454) worked out for you!?

**Comment by manijak** [comment]
@NickIliev I will, as soon as we deploy new version and get feedback from the users.

**Comment by manijak** [comment]
@NickIliev, 
We published a new update yesterday with the fix from @NathanaelA. And the first feedbacks are very positive. The app installs fine on the affected devices! 

Created a  app.gradle and added the following:
```
android {  
  defaultConfig {  
    generatedDensities = []  
    applicationId = "my.package.name"
  }
}
```

Thanks again @NathanaelA!
