### ISSUE TITLE
iOS interactive transitions crash NativeScript apps

### ISSUE THREAD

**Issue by roosmaa** [NativeScript/NativeScript#2205]
NativeScript doesn't seem to handle interactive UINavigationController transitions correctly and results in a delayed crash of the app. This affects iOS apps only.

Steps to reproduce:
- Start the [grocery sample project](https://github.com/NativeScript/sample-Groceries) in iOS simulator
- Log in to get to the 2nd page of the app
- Invoke the built in iOS slide-from-left-side-to-get-back gesture (which triggers the interactive transition)
- Current page goes blank (shouldn't happen, fault 1)
- Change mind mid transition to stay on the same page (not complete the gesture)
- When navigating away from the blank page (pressing back) the app crashes (fault 2)

Gif demonstrating the issue & resulting crash: 
![iosnativescriptinteractivetransition](https://cloud.githubusercontent.com/assets/65596/15635920/5a300f60-25a3-11e6-8999-c3a9bfba789c.gif)

### Local environment

Freshly installed NativeScript environment:

```
$ tns --version
2.0.1
$ grep version node_modules/tns-core-modules/package.json
  "version": "2.0.0",
$ grep -EA 3 "tns-(ios|android)" package.json
		"tns-ios": {
			"version": "2.0.0"
		},
		"tns-android": {
			"version": "2.0.0"
		}
	},
```

**Comment by NickIliev** [comment]
Hello @roosmaa 

Thank you for reporting this behaviour.
This is issue is already is reported and we are working on solution.

Duplicate to [https://github.com/NativeScript/nativescript-angular/issues/257](https://github.com/NativeScript/nativescript-angular/issues/257)
