### ISSUE TITLE
CSS-Animation w/ iteration-count:infinite is never reset causing OutOfMemory error

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#2209]
Related to [https://github.com/NativeScript/NativeScript/issues/2195](https://github.com/NativeScript/NativeScript/issues/2195)

Any CSS-animation with animation-duration: inifinite will never be reset and will cause memory leak after navigating to another page.

Code to reproduce:
**_main-page.css_**
```
@keyframes zoominout {
    0%   { transform: scale(1,1); }
    50%  { transform: scale(1.2,1.2); }
    100% { transform: scale(1,1); }
}

.animate{
   animation-name: zoominout;
   animation-duration: 1s;
   animation-iteration-count: infinite;
}
```

**_main-page.xml_**
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <StackLayout>
    <Label text="Test infinite CSS-animation reset" class="title"/>
    <Button text="TAP" tap="onTap" />
    <Image src="res://icon" stretch="none" class="animate" />
    <Image src="res://icon" stretch="none" class="animate" />
    <Image src="res://icon" stretch="none" class="animate" />
  </StackLayout>
</Page>
```

**_main-page.ts_**
```
import { EventData } from "data/observable";
import { Page } from "ui/page";
import frameModule = require("ui/frame");

export function onTap(args:EventData) {
    frameModule.topmost().navigate("sub-page");
}
```

**_sub-page.xml_**
```
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="onLoaded" navigatedTo="onNavigatedTo">
    <StackLayout>
        <Label text="Sub page" textWrap="true" />
    </StackLayout>
</Page>
```

When you navigate from main-page to sub-page the CSS-animation is never reset.
After approx. minute-two the app is crashing by itself (tested on Geny with Android Device Monitor)

**Comment by mordeccai** [comment]
app still crashes. In NativeScript v 3.3.0

**Comment by mordeccai** [comment]
I had to comment the following code for it to stop the memory leak:
@keyframes blink {
    0% {
        opacity: 1;
    }
    25% { 
        opacity:0.5;
    }
    50% { 
        opacity:0;
    }
    75% { 
        opacity:0.5;
    }
    100% { 
        opacity:1;
    }
}

.in-page{
    animation-name: blink;
    animation-duration: 1;
    animation-timing-function: ease-in-out;
    animation-iteration-count: infinite;
}
