### ISSUE TITLE
[Android] Screen-size qualifier ignored?

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#2218]
I am trying to create some tablet-specific views in my app. I created a view with a qualifier like this: `main-view.minWH700.xml`

Now, this works just fine in iOS, it gets picked up iPad devices nicely. But on Android it is ignored. I am using Genymotion to test (Nexus 10 - 5.1.0 - 2560x1600). Still uses the normal view.

* CLI: 2.0.1
* Cross-platform modules: 2.0.1
* Runtime(s): Android 2.0.0

**Comment by tsonevn** [comment]
Thank you for reporting this issue.

I have created sample project however I was unable to reproduce your scenario. In my project the different XML files were loaded correctly on devices with different screen size.  Indeed I reproduced another problem with property binding when the app use  `main-view.minWH700.xml`. You can review my project here:[ScreenSizeQualifier](https://github.com/tsonevn/ScreenSizeQualifier.git).
It would help if you send us sample project, where your issue has been reproduced.

I hope this helps

**Comment by manijak** [comment]
Hmmm, ok. I did forget to mention that this is a partial view, referenced in a main-view and used innside a TabView-item.

**Comment by tsonevn** [comment]
Hi @manijak, 

I made a mistake in my project, actually there is no problem with the property binding. However I could not reproduce your issue. Could you send me a sample project, which recreates this behavior .

Regards,
@tsonevn

**Comment by manijak** [comment]
@tsonevn ,
I've managed to find out why it didn't work. Because the file was named `main-view.minWH760.xml`. Apperently it does not support that particular size (760) on Android. So, once I renamed it to `minWH700` or `minWH600`, it worked :)

Tested now both in iOS and Android and it works as it's supposed to. Can't remember why I choose 760 to start with, but it worked on iOS so I never changed it.
