### ISSUE TITLE
Fixed Layout

### ISSUE THREAD

**Issue by cinder92** [NativeScript/NativeScript#2224]
### Did you verify this is a real problem by searching 
yes, i don't found anything about this

### Tell us about the problem
with complex designs, it would be very nice that we can get something like `<FixedLayout bottom="0" width="100%" ccsClass="bottombar">`

and then have opacity between background` <StackLayout> `with Tabs component

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.01.
- Cross-platform modules: 2.0.1
- Runtime(s): 2.0.0

**Comment by NickIliev** [comment]
Hi @cinder92 

Fixed layout is hard thing to recreate in mobile development where the focus is responsive design and nowadays UX material design. Of course certain situations in comlpex design may require this behaviour and then you can implement it using native code.

Native code example (Android) for creating relative layout and fixing a textureView to its bottom
```
var myRelativeLayout = new android.widget.RelativeLayout(app.android.context);
var myTextureView = new android.view.TextureView(app.android.context);
var layoutParams = new android.widget.RelativeLayout.LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT); // or wrap_content
layoutParams.addRule(android.widget.RelativeLayout.ALIGN_PARENT_BOTTOM); // android:layout_alignParentBottom="true"
myRelativeLayout .addView(myTextureView , layoutParams);
```
And from this point you can create your custom view with [placeholder](https://docs.nativescript.org/ui/placeholder) and use it in NativeScript

**Comment by cinder92** [comment]
ok, thanks i will look into this

**Comment by alexrainman** [comment]
@NickIliev exactly what i was looking for 👍
