### ISSUE TITLE
[Bug] Placeholder creatingView fires multiple times

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#2228]
Only tested on iOS so far (ios-runtime 2.0.0). Adding a Placeholder `creatingView` will fire the function that it's attached to 6 times.

```
// main-page.xml
<Placeholder creatingView="creatingView" />

// main-page.js
var counter = 0;
exports.creatingView = function(args) {
  counter++;
  console.log(counter);
}
```

```
CONSOLE LOG file:///app/main-page.js:11:14: 1
CONSOLE LOG file:///app/main-page.js:11:14: 2
CONSOLE LOG file:///app/main-page.js:11:14: 3
CONSOLE LOG file:///app/main-page.js:11:14: 4
CONSOLE LOG file:///app/main-page.js:11:14: 5
CONSOLE LOG file:///app/main-page.js:11:14: 6
```

I can temporarily prevent this from happening using a `if/boolean` combination, but this shouldn't be happening at all. The above code sample is [available here](https://github.com/NordlingArt/tns-issue-creatingView).

**Comment by hshristov** [comment]
Actually this is by design. You need to set the `args.view` in `creatingView` function:
```
var nativeView = new UILabel();
nativeView.text = "Native";
args.view = nativeView;
```

**Comment by NordlingArt** [comment]
@hshristov

Why is this by design? I am unable to access `frameModule.topframe()` during the first iteration as it returns `undefined`, meaning I cannot reference to anything within the page. The rest will return actually return `topframe()`:

CONSOLE LOG file:///app/main-page.js:54:14: undefined
CONSOLE LOG file:///app/main-page.js:54:14: Frame(0)
CONSOLE LOG file:///app/main-page.js:54:14: Frame(0)
CONSOLE LOG file:///app/main-page.js:54:14: Frame(0)
CONSOLE LOG file:///app/main-page.js:54:14: Frame(0)
CONSOLE LOG file:///app/main-page.js:54:14: Frame(0)

**Comment by hshristov** [comment]
We raise it when .ios property is accessed. If you don't set the `args.view` then internally the component stays uninitialized. So next time some API (internal or external) access `.ios` this event is raised again. Why do you need `frameModule.topframe()`?

**Comment by NordlingArt** [comment]
Nevermind that. I realized I actually had no use for it. Thanks for the help!
