### ISSUE TITLE
Consider wrapping `observable.notify()` calls in `zonedCallback`

### ISSUE THREAD

**Issue by vakrilov** [NativeScript/NativeScript#2229]
Consider wrapping all listener calls made form `observable.notify()` in a the [`zonedCallback`](https://github.com/NativeScript/NativeScript/blob/dfaf481d6d2538372c13f9eab08d523cb5f6e9af/tns-core-modules/globals/globals.ts#L32-L43) function so that they trigger change detection in Angular2 applications. 
This however can read to performance issues. If it is slow - better look for a solution inside `nativescript-angular` project or leave the responsibility to the developer to take care of executing callbacks inside the NgZone.

**Comment by NathanWalker** [comment]
I like the thought of advocating plugin authors wrap their callbacks in the `zonedCallback` as mentioned.
Alternatively, wrapping `notify()` in `nativescript-angular` only seems to make sense as it would likely provide a better development experience so people aren't running into that often and not understanding why changes are not happening.
