### ISSUE TITLE
How to navigate the actual top frame within a sub frame?

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#2238]
I have a simple page that also has a `<Frame />` inside. How do I navigate the top frame that is hosting the sub frame?

Sample code:

```
/* main-page.xml
 =============================== */
<Page navigatedTo="navigatedTo">
  <Frame id="mainFrame"> // View: "views/sub-page" />
</Page>


/* sub-page.xml
 =============================== */
<Page navigatedTo="navigatedTo">
  <Button text="Navigate top frame" tap="topNav" />
</Page>


/* sub-page.js
 =============================== */
var frameModule = require("ui/frame");

var page;
exports.navigatingTo = function(args) {
  page = args.object;
  page.bindingContext = {};
};

exports.topNav = function(args) {
  frameModule.topmost().navigate({
    moduleName: "views/start"
    clearHistory: true
  });
};
```

`frameModule.topmost()` will not select the top frame, but the frame that the event was triggered within. Am I missing the point of `topmost()` and is there another to access the ACTUAL top most frame?

**Comment by hshristov** [comment]
`topmost()` returns the last frame on which navigate was called. So you have to use `stack` property defined in the frame module and get the first element of this array. Even then I'm not sure if nested navigation works as expected so you will probably hit some bugs. Why do you need nested frames?

**Comment by NickIliev** [comment]
@NordlingArt 

Instead of nested frames you can use loading of custom XML components for your app architecture.
For example:

**_main-page.xml_**
```
<Page xmlns:customControls="custom-components-folder">
  <customControls:my-component />
</Page>
```

_custom-components-folder_/**_my-component.xml_**
```
<StackLayout>
    <Label text="My custom component example" textWrap="true" />
</StackLayout>
```

More about this you can find here : [http://docs.nativescript.org/ui/ui-with-xml#custom-components](http://docs.nativescript.org/ui/ui-with-xml#custom-components)

And here: [http://blog.bradleygore.com/2016/03/12/custom-nativescript-components/](http://blog.bradleygore.com/2016/03/12/custom-nativescript-components/)

**Comment by NordlingArt** [comment]
@hshristov
Reason why I want nested frames is because I want to make a tabbed main view with sub views inside. TabView component does not do justice as I cannot style and manage the tab bar as I want.

@Nicklliev
this way I cannot load and unload the components (sub views) dynamically, right? I have to load every single sub view from start, meaning there will be memory issues if some views are bigger than others.

**Comment by NordlingArt** [comment]
I believe I managed to bypass the nested frame method, and instead creating a native UIView to the superview. Thus, the tab bar will never go away unless I say so myself by controlling the `hidden` property.

**Comment by tobydeh** [comment]
@NordlingArt Could you please post an example of your solution?
