### ISSUE TITLE
Make the file-system module run in a background thread [$300]

### ISSUE THREAD

**Issue by sebawita** [NativeScript/NativeScript#2239]
Calling file-sytem -> writeText is freezing the UI of my apps until the write process is complete. Even the ActivityIndicator freezes during that time.
This is a big issue when saving big chunks of data which can take between 10 to 60 seconds to write.

I have tested it on Android with NativeScript 2.0.1

To solve that it would be great if the write functionality could run in a background thread, just like it is done for the http module.

Here is the scenario where I need to save big chunks of data.
The app I am building uses Lokijs for Offline Storage mechanism, where I store 50k records from different tables. When I call save database, the LokiNativeScriptAdapter uses file-system module to save the data to a file, which takes up to 60 seconds.

**Comment by NordlingArt** [comment]
Question, is this the same thing as `imageSource.setNativeSource()` function? I am trying to make a photo library that creates a stack of photos from the iOS Photos library. Problem is that the app freezes until every photo has been rendered in the UI. If I only console.log each photo using the same procedure, the logs come out on by one as opposed to the UI that waits until every photo is loaded.

**Comment by farfromrefug** [comment]
I will bump that issue cause i feel it is kind of very big issue in Nativescript.
File are read in the main thread:
https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/file-system/file-system-access.android.ts#L241

Images are read on the main thread:
https://github.com/NativeScript/NativeScript/blob/05c2460fc4989dae4d7fa1ee52f6d54e0c3113f5/tns-core-modules/image-asset/image-asset.android.ts#L26

All that makes for a pretty bad navigation experience.
This all should be implemented in in the native lib.
