### ISSUE TITLE
Possible regex issue with CSS class names

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#2240]
_From @rdlauer on June 2, 2016 20:19_

It appears that there may be some confusion with CSS class names that contain other class names, leading to problems with the way styles are parsed. It appears to only be a problem on Android. For instance, [in this repo](https://github.com/rdlauer/nativescript-ionic), I have these classes: `.button, .button-assertive, and .button-assertive-outlined`.

For example, this button element doesn't load the `button-assertive class`: `<Button class="button button-assertive" text="assertive" />`

...but if you remove the `.button-assertive-outlined` class from the CSS file, it does work. Again, works on iOS, but this problem only comes up on Android.

cc @tjvantoll 

_Copied from original issue: NativeScript/nativescript-cli#1799_

**Comment by nsndeck** [comment]
Issue fixed with commit #2310.
