### ISSUE TITLE
unit testing with angular/core/testing

### ISSUE THREAD

**Issue by circy** [NativeScript/NativeScript#2246]
Hi Guys.
Is it possible to unit tests with the test lib to make of angular?
Or this is only possible in the browser?

for example:

```Typescript
import {
  it,
  describe,
  expect
} from '@angular/core/testing';

describe('App', () => {

  it('the first', () => {
    expect(true).toEqual(true);
  });

});
```

I use Native Script Version: 2.0.1
And I use Jasmine.

Many thanks.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#272
