### ISSUE TITLE
CodePush support to push code updates to NativeScript apps

### ISSUE THREAD

**Issue by cyparu** [NativeScript/NativeScript#2247]
Both [**Cordova**](http://microsoft.github.io/code-push/docs/cordova.html) and [**ReactNative**](http://microsoft.github.io/code-push/docs/react-native.html) supports [**CodePush**](http://microsoft.github.io/code-push/) for easy updates of the applications code & assets without a full reinstall of the app. 
It will be great to introduce CodePush support for NativeScript apps as well.

**Comment by NickIliev** [comment]
Duplicate to [https://github.com/NativeScript/NativeScript/issues/2092](https://github.com/NativeScript/NativeScript/issues/2092)
