### ISSUE TITLE
ItemTap doesn't work with mapView.

### ISSUE THREAD

**Issue by VsevolodAstanov** [NativeScript/NativeScript#2251]
Hello. I have an application with "nativescript-google-maps-sdk" plugin for displaying some maps (google maps) in the lite mode in the ListView.
I need to use the "itemTap" event for showing details about each list item.

When we using Button in the list item "ItemTap" event doesn't fire. I found the solution for Button.  Just use "args.object.android.setFocusable(false);". But it don't working for "mapView".

What is your the recomendation for it?

**Comment by NickIliev** [comment]
Hello @VsevolodAstanov 

Consider the following: **itemTap** is meant to be used for the list-item (not Button).
If you have introduced a logic for **itemTap** and then you want to have a button inside with another tap event it will again come to the question - which tap event will the user fire when clicking on the Button inside list-view-item !? (the Button tap or the itemTap) - maybe consider using clear UX with just one tap event for one logic container. Or nstead of list-view with item tapped you need  another solution - for example grid-layout where the elements in your cells will have extended structure (multiple buttons, e.g. ...).

This is the basic usage of list-view
```
<Page>
  <ListView items="{{ myItems }}" itemTap="listViewItemTap" />
</Page>
```
```
function listViewItemTap(args) {
  var itemIndex = args.index;
  // implement your itemTap logic
}
exports.listViewItemTap = listViewItemTap;
```

The same is valid when thinking od mapView from nativescript-google-maps-sdk.
Based on the API reference from the plugin we have the following:

> **_mapReady_**	                Called when Google Map is ready for use
> **_coordinateTapped_**	        Fires when coordinate is clicked on map
> **_markerSelect_**	                Fires whenever a marker is selected
> **_markerBeginDragging_**	Fires when a marker begins dragging
> **_markerDrag_**	                Fires repeatedly while a marker is being dragged
> **_markerEndDragging_**	        Fires when a marker ends dragging
> **_cameraChanged_**	        Fired on each camera change

If you have a list-view-item with _**itemTap**_ logic and inside you draw a map with **_coordinateTapped_** logic how will the user make the difference when he is tap-ing inside the map...

**Comment by VsevolodAstanov** [comment]
Button - it was just for example. I have no requirements to implement it.  It has the same behaviour like a mapView in my case.
I have a GridLayuot with map(lite mode - without tap events. Just to display several polylines)  

Here is example of my XML:
`<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="onTrainingLoaded" actionBarHidden="true" xmlns:maps="nativescript-google-maps-sdk">
	<ListView id="itemList" items="{{ trainings }}" itemTap="{{showDetails}}" cssClass="list-view">
		<ListView.itemTemplate>
			<GridLayout columns="*, auto" rows="auto, auto, auto, auto, auto">
				<maps:mapView liteMode="true" width="150" height="150" col="1" row="1" rowSpan="4" loaded="onMapLoaded" />
				<StackLayout col="0" row="0" colSpan="2" horizontalAlignment="right">
					<Label text="{{ trk.info.save_time }}" cssClass="task-save-time" />
				</StackLayout>
				<StackLayout col="0" row="1">
					<Label text="{{ trk.name }}" cssClass="task-name" />
				</StackLayout>
				<StackLayout col="0" row="2">
					<Label text="{{'Distance: ' + trk.info.distance }}" cssClass="task-distance" />
				</StackLayout>
				<StackLayout col="0" row="3">
					<Label text="{{'Time: ' + trk.info.time }}" cssClass="task-distance" />
				</StackLayout>
				<StackLayout col="0" row="4">
					<Label text="{{'Average speed: ' + trk.info.speedavg }}" cssClass="task-avgspeed" />
				</StackLayout>
			</GridLayout>
		</ListView.itemTemplate>
	</ListView>
</Page>`
No need to listen the mapView events, instead of mapReady.

**Comment by NickIliev** [comment]
@VsevolodAstanov 

I have tested your case and made only a small change
This line:
```
<maps:mapView liteMode="true"  loaded="onMapLoaded" />
```

Should be:
```
<maps:mapView liteMode="true"  mapReady="onMapLoaded" />
```

After that change everything seems to wrok as espected with this code
```
<ListView id="itemList" items="{{ trainings }}" tap="onItemTap" cssClass="list-view">
    <ListView.itemTemplate>
    
        <GridLayout columns="*, auto" rows="auto, auto, auto, auto, auto">
                <maps:mapView liteMode="true" width="150" height="150" col="1" row="1" rowSpan="4" mapReady="onMapReady" />
                <StackLayout col="0" row="0" colSpan="2" horizontalAlignment="right">
                    <Label text="{{ trk.info.save_time }}" cssClass="task-save-time" />         
                </StackLayout>
                <StackLayout col="0" row="1" >
                    <Label text="{{ trk.name }}" cssClass="task-name" />
                </StackLayout>
                <StackLayout col="0" row="2">
                    <Label text="{{'Distance: ' + trk.info.distance }}" cssClass="task-distance" />
                </StackLayout>
                <StackLayout col="0" row="3">
                    <Label text="{{'Time: ' + trk.info.time }}" cssClass="task-distance" />
                </StackLayout>
                <StackLayout col="0" row="4">
                    <Label text="{{'Average speed: ' + trk.info.speedavg }}" cssClass="task-avgspeed" />
            </StackLayout>
        </GridLayout>
        
    </ListView.itemTemplate>
</ListView>     
```           

I have also noticed that your itemTap function has a model binding 
`itemTap="{{showDetails}}"   `            
For executing the function in the code behind, the following syntax should be used in the XML - `tap="onTap"` and for the function from the bindingContext - `tap="{{ onTap }}"`.

**Comment by NickIliev** [comment]
@VladimirAmiorkov ok now with the informatiojn about args.index and your view-model I was able to reproduce your exact problem - please allow some more time for me to investigate further what is going on here and why args.index is undefined

**Comment by NickIliev** [comment]
@VladimirAmiorkov 

I have revised the above code using the NativeScript implementation and everything works as espected.

I suspect the native mdropid code is causing your trobules (args.object.android.setFocusable(false)) among with the usage of loaded="onMapLoaded" (if you want to create and use nativeView in NativeScript you can use [**placeholder** ](https://docs.nativescript.org/ui/placeholder) with **_creatingView_**)

However using **mapReady** with the plugin NativeScript functionalit also works fine so i recommend using this scenario.

**Comment by VsevolodAstanov** [comment]
hmm... **tap** event works ok. But I can't to get the args.index from it. Index is undefined =)

**Comment by NickIliev** [comment]
@VsevolodAstanov I had a mistakwe in the posted code

Change this
`tap="onItemTap" `

to this 
`itemTap="onItemTap" `

**Comment by VsevolodAstanov** [comment]
I'm sorry. It's not working.

XML:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="onTrainingLoaded" actionBarHidden="true" xmlns:maps="nativescript-google-maps-sdk">
	<ListView id="itemList" items="{{ trainings }}" itemTap="onItemTap" cssClass="list-view">
		<ListView.itemTemplate>
			<GridLayout columns="*, *, auto" rows="*, *, *, *, *">
				<maps:mapView liteMode="true" width="150" height="150" col="2" row="1" rowSpan="4" loaded="onMapLoaded" />
				<StackLayout col="1" row="0" colSpan="2" horizontalAlignment="right">
					<Label text="{{ trk.info.save_time }}" cssClass="task-save-time" />
				</StackLayout>
				<StackLayout col="0" row="0" horizontalAlignment="left" >
					<Label text="{{ trk.name }}" cssClass="task-name" />
				</StackLayout>
				<StackLayout col="0" row="1" colSpan="2">
					<Label text="{{ trk.info.time }}" cssClass="task-time" />
				</StackLayout>
				<StackLayout col="0" row="2" colSpan="2" rowSpan="2">
					<Label text="{{ trk.info.distance }}" cssClass="task-distance" />
				</StackLayout>
				<StackLayout col="0" row="4" cssClass="task-bottom-info">
					<Label text="Height" />
					<Label text="{{ 'Min: 243 m' }}" />
					<Label text="{{ 'Max: 333 m' }}" />
				</StackLayout>
				<StackLayout col="1" row="4" cssClass="task-bottom-info">
					<Label text="Speed" />
					<Label text="{{ 'Avg: 23.1 km/h' }}" />
					<Label text="{{ 'Max: 33.2 km/h' }}" />
				</StackLayout>
			</GridLayout>
		</ListView.itemTemplate>
	</ListView>
</Page>
```

JS:
```
var appSettings = require("application-settings");
var dialogs = require("ui/dialogs");
var vmModule = require("./trainings-view-model").TrainingsViewModel;
var MapService = require("../../services/map-service").MapService;

function onTrainingLoaded(args) {
    var page = args.object;
	page.bindingContext = vmModule;
}

function onMapReady(args) {
	args.object.android.setFocusable(false);
	var gMap = args.object.android.getMap();
	var UISettings = gMap.getUiSettings();

	/* Enable lite mode */
	UISettings.setMapToolbarEnabled(false);

	/* Add track */
	MapService.addTrackOnLiteMap(args);
}

function onItemTap(args) {
	console.log('test');
}

exports.onItemTap = onItemTap;
exports.onMapReady = onMapReady;
exports.onTrainingLoaded = onTrainingLoaded;
```

**Comment by NickIliev** [comment]
@VsevolodAstanov 

1.) in your XML file in your mapView tag you are still using 
```
loaded="onLoaded"
```
instead of 
```
mapReady="onMapReady"
```

2.) In your JavaScript file you are still trying your native Android code... in my opinion give a try at the NativeScript implementation of the plugin as the author is using it.

Here is also a [sample app](https://github.com/tsonevn/TabViewNativeScriptGoogleMaps) demonstrating usage of mapView

p.p. TypeScript is superset of JavaScript so basicly a code that wiorks in JS will work exactly the same in TS (but not the opposite - more about TypeScript [here](https://www.typescriptlang.org/docs/tutorial.html))

**Comment by VsevolodAstanov** [comment]
I have changes the laoded to mapReady and commented the native code. "itemTap" is not working.
XML:

**Comment by VsevolodAstanov** [comment]
I found a code string `this._android.onCreate(null);` in the map-view-android.js file.
After that the itemTap does not work.

**Comment by NickIliev** [comment]
@VsevolodAstanov 

It seems that the code indeed tends to work occasionly and occasionly not... I will investigate further and write back at you when I have more info about this scenario

**Comment by VsevolodAstanov** [comment]
Thank you.

**Comment by NickIliev** [comment]
@VsevolodAstanov 

Indeed mapView is setting the focus (no matter if in liteMode or not) and is preveting the itemTap event to fire. This is related to this issue [https://github.com/NativeScript/NativeScript/issues/594](https://github.com/NativeScript/NativeScript/issues/594) and is observed in Android [(http://stackoverflow.com/questions/6275183/android-listview-with-buttons-onitemclick-do-nothing)](http://stackoverflow.com/questions/6275183/android-listview-with-buttons-onitemclick-do-nothing)

Now we don't have button as the previous example for reproducing this bug but I guess in the logic of the plugin a certain element from the google map is getting the focus and from then the itemTap of list-view is not fired. This behaviour is coming from the native Android API so currently there is no fix for NativeScript.(setFocusable will work on Button and TextFiled but won't help on mapView)

As a workaround I can suggest to change the UI - what comes to mind are two solutions:

1.) In your list-view dont't use the plugin but a thumbnail with the selected region (passed in the code-behind) and then in the details-page use the full functionality of google-maps-sdk.This solution will also lower your app traffic (for example: yоu can cache the thumbs and re-use thumbs with ideantiacal regions)

2.) Do not use list-view - however this solution entirely depends on your business logic

**Comment by VsevolodAstanov** [comment]
Ok. thank you. It did not solve my problem. I will try to investigate it independently.
If I find a solution I will write about it =)

**Comment by VsevolodAstanov** [comment]
I have an idea for implement it with Button as background (Button in the AbsoluteLayout). Button id is index. It will works =)
