### ISSUE TITLE
Documentation ImageSource class

### ISSUE THREAD

**Issue by glueckandi** [NativeScript/NativeScript#2252]
Hi!

What is the min and max value for the quality parameter in the ImageSource class?

`toBase64String(format: string, quality?: number): string`

[https://docs.nativescript.org/api-reference/classes/_image_source_.imagesource.html#tobase64string](url)

**Comment by NickIliev** [comment]
Hi @glueckandi 

min = 0;
max = 100;

Default value is 100 (maximum quality)
The quality param is not mandatory so if you pass it like 
`seletedImgSource.toBaseString64("JPG") `
is the same like
`seletedImgSource.toBaseString64("JPG", 100); `

**Comment by glueckandi** [comment]
Perfect. Thanks.
