### ISSUE TITLE
How to give color for text field in NS

### ISSUE THREAD

**Issue by karumurikiran** [NativeScript/NativeScript#2254]
![capture](https://cloud.githubusercontent.com/assets/10797035/15821090/51e2cd66-2c0b-11e6-9874-a74737ef2ae3.PNG)

@NickIliev 

Thanks for the reply, but i want the the output as show in the above attached image.
The code what you have sent is went we type the text in the text field then the color of the letters changing, but i want went we write first the code then only i must get the text color same as shown in the image.

**Comment by tsonevn** [comment]
Hi @karumurikiran ,

You could set hint text color to your `TextField`. We do not have such NativeScript property, however you could use iOS and Android specific code. I am attaching sample code below.
main-page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" loaded="loaded" style="background-color: #0000ff;">
    <StackLayout>
    <TextField  hint="sample" text="{{  }}" id="textfield" style="color:white;"/>
    </StackLayout>
</Page>

```

main-page.js
```
var color_1 = require("color");

var page;
function navigatingTo(args) {
    page = args.object;
    var color = new color_1.Color("#CECECE");
    var textField = page.getViewById("textfield");
    if (page.android) {
        textField.android.setHintTextColor(android.graphics.Color.parseColor("#CECECE"));
    }
    else {
        var placeholder = textField.ios.valueForKey("placeholderLabel");
        placeholder.textColor = color.ios;
    }
}
exports.navigatingTo = navigatingTo;
```  

I hope this helps

**Comment by chrillewoodz** [comment]
@tsonevn How would you do this with angular?

**Comment by tsonevn** [comment]
Hi @chrillewoodz,
In this case, you could now use `placeholderColor` CSS property as you can see in the documentation [here](https://docs.nativescript.org/ui/styling#supported-css-properties).
for example:
```
<TextField hint="test"  style.placeholderColor="green"></TextField>
```
Please, for more `How to` questions use our [NativeScript forum](https://discourse.nativescript.org/).

**Comment by chrillewoodz** [comment]
@tsonevn Ok great. Yes I am doing that I just thought it was a valid thing to add to this issue, as a lot of us are using angular.
