### ISSUE TITLE
Custom ActionItem gets displaced in IOS

### ISSUE THREAD

**Issue by vakrilov** [NativeScript/NativeScript#2256]
### Tell us about the problem
Custom action item with `ios.postion="right"` moves to the left when text of the button inside is changed. The bug occurs only when the custom item inside the ActionItem has the same size after the change. If the size is changed it gets positioned correctly.

Here is a repo code:

XML:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <Page.actionBar>
    <ActionBar>
      <ActionItem ios.position="right" tap="change">
        <Button text="{{ text }}" backgroundColor="red"/>
      </ActionItem>
    </ActionBar>
  </Page.actionBar>
</Page>
```

TS:
```
import { EventData } from "data/observable";
import { Page } from "ui/page";
import { Observable } from "data/observable";

const context = new Observable();
const values = ["--i--", "-i---", "-i-"];
var count = 0;

// Event handler for Page "navigatingTo" event attached in main-page.xml
export function navigatingTo(args: EventData) {
    // Get the event sender
    var page = <Page>args.object;
    page.bindingContext = context;
    change();
}

// Event handler for Page "navigatingTo" event attached in main-page.xml
export function change() {
    context.set("text", values[count++ % 3]);
}
```

The issue is easily reproducible if icon font is used for the text of the button or if it has `width` set.

**Comment by NickIliev** [comment]
Is this related to [https://github.com/NativeScript/NativeScript/issues/2179](https://github.com/NativeScript/NativeScript/issues/2179) !? 
There is a client video in the link demostrating the custom action-item displacement onLoaded

**Comment by tskweres** [comment]
when using font icons in the actionbar and aligning using ios.position, i can confirm this is still an issue. Can we reopen? @tzraikov 

`<ActionItem ios.position="right" (tap)="goBack()">
      <Button #backicon text="&#xE87D;" class="material-icons backicon"
        style="font-size: 26; color: rgba(0,0,0,.2);
        background-color: transparent;
        width: 50px;
        text-align: right;">
      </Button>
    </ActionItem>`

**Comment by NickIliev** [comment]
Hello @tskweres 

I have re-rested this case with your code but was not able to reproduce the issue.
[Here you can find the sample projec](https://github.com/NickIliev/NativeScript-issues/tree/master/NativeScript-Angular/issue_2256_ng)t I have created for my test - can you tried on your side and let us know if it works as expected.  Also,  are you using tns-core-modules 2.3.0 for building your project!?

**Comment by tskweres** [comment]
@NickIliev bummer, it looks like it's a problem with Google Material Fonts specifically. If I just use regular text the animation is fine.

**Comment by tskweres** [comment]
Actually I take that back, the problem persists. Still trying to troubleshoot which style or setting is causing the issue

**Comment by tskweres** [comment]
@NickIliev try setting up two views with actionbars and iconsfonts in the header, and transitioning between them using slideLeft and slideRight.

My tns-core-modules are up to date and I'm seeing the issue with Google Material Fonts

any help much appreciated :/

**Comment by tskweres** [comment]
@NickIliev @tzraikov guys I have created a repo demonstrating the bug. If you navigate to the 'swipe' page, and then click over to settings or messages, you will see the font icons in the action bar snap into place awkwardly:

https://github.com/tskweres/tinder-clone

**Comment by NickIliev** [comment]
Hey @tskweres 
Can you add **_gitignore_** file as of this moment the project you have shared can not be cloned properly due to long paths.

**Comment by tskweres** [comment]
Sorry I'm not familiar with that issue or how to fix :/ Is it a windows problem related to this?

https://github.com/Strider-CD/strider/issues/446

**Comment by tskweres** [comment]
@NickIliev is it possible on your end to just download and unzip and run it? Are you using Windows?

**Comment by NickIliev** [comment]
Hey @tskweres 

We were able to reproduce this issue and it appears to be connected with the usage of IconFonts. At the moment the transaction is done they are not yet initialized and they have 0 initial sizes.. then after the initialization of the icons the size is updated which leads to the bug described. 
I am going to open a new issue to describe the specific problem (as it is different from the one resolved here) so you might want [to track this one here](https://github.com/NativeScript/NativeScript/issues/2941) for solutions and/or fix.
