### ISSUE TITLE
Unable to sync files. Error is: EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by georgeedwards** [NativeScript/NativeScript#2257]
### Tell us about the problem

When using livesync on windows, if you save files before the last compilation has completed then I get the error:

> Unable to sync files. Error is: EISDIR: illegal operation on a directory, read

It doesn't go away with subsequent file change events. However, killing and restarting the livesync works great. 

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
-CLI: 2.0.1
-Cross-platform modules: 2.0.1
-Runtime(s): 2.0.0 (android)

### Please tell us how to recreate the issue in as much detail as possible.

I am running Windows 10, then edit two files in the sample groceries, save the first one and then save the second one (very soon after), this creates it for me.

**Comment by tsonevn** [comment]
Hi @georgeedwards ,

Thank you for reporting your problem.
I reviewed your case however I was unable to reproduce the issue. Could you give me more info about this problem.
It would help if you could give me a a sample project, which recreates the problem.

Regards,
@tsonevn

**Comment by Metalmate** [comment]
Hello,

I can reproduce the error, but not the way you described. When livesync --watch is running and you create a new folder in the directory from where the command is running, a.k.a. you livesync a project, and somewhere in that project you create a new directory, this error shows up.

I guess you might have created a directory, or some other program did. Can you reproduce the problem and make sure no directory was created in the process?

CLI: 2.0
OS: Ubuntu 16.04
Android: 2.0.0

**Comment by tsonevn** [comment]
Hi @Metalmate,
Thank you for the reply

I confirm that this is an real issue for android projects, when you are using  `tns livesync android --emulator --watch` and make new folder in a project while livesync is running.

Regards,
@tsonevn

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-cli#1810
