### ISSUE TITLE
How to write code for border of the circle with different colors as shown in the image

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#2259]
![gradinent](https://cloud.githubusercontent.com/assets/10844041/15846049/e5157986-2c96-11e6-8d27-ec50c6c6bb17.PNG)

**Comment by NickIliev** [comment]
@dhanalakshmitawwa 

Creating gradient colors is currently not supported but is scheduled feature for future release.
You can see what our feature wil look like in this discussion here [https://github.com/NativeScript/NativeScript/issues/2132](https://github.com/NativeScript/NativeScript/issues/2132)

Meanwhile one way to achive taht is to use the solution in the duplicate issue here [https://github.com/NativeScript/NativeScript/issues/2249](https://github.com/NativeScript/NativeScript/issues/2249)
