### ISSUE TITLE
[Question] Are there any benefits of using the ActionBar over a self made one?

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#2273]
Reasion why I'm asking is because I feel like I am extremely limited of customizing the appearance of the ActionBar as compared to actually creating my own using the XML.

Are there any differences performance-wise?

**Comment by tsonevn** [comment]
Hi @NordlingArt,

Thank you for your question.

Our `ActionBar` is the same as `UINavicationBar` for `iOS` and `Toolbar` in `Android`.  Performance and benefits of the `Action Bar` are the same as in those Native components. `ActionBar` allow you to use same properties for both `Android` and `iOS`. However if you want to use some specific `iOS` or `Android` properties you could access them by using `actionbar.android` or `actionbar.ios`. In regards to that you could create custom view in the `ActionBar` as it is described in our documentation [displaying-custom-view](https://docs.nativescript.org/cookbook/ui/action-bar#displaying-custom-view-in-action-items).  If you could not style  `ActionBar` as you wish you could create `CustomView` as you suggest.


I hope this helps

**Comment by hshristov** [comment]
ActionBar for iOS is implemented by using UINavigationBar. In that sense when you make page navigation only the content of the page is loaded. UiNavigationBar is reused through pages. While this save memory and eventually improve performance it may not always suffice developer needs. So in some cases you will need custom action-bar :)

**Comment by NordlingArt** [comment]
@tsonevn, @hshristov - Thanks for the explanation! I'll stick with my custom navigation bar then :)
