### ISSUE TITLE
Let child view overflow AbsoluteLayout parent on Android

### ISSUE THREAD

**Issue by terreb** [NativeScript/NativeScript#2274]
### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.0.0
- Cross-platform modules: 2.0.0
- Runtime(s): tns-android 2.0.0

### Please tell us how to recreate the issue in as much detail as possible.
Please try to test the below markup on iOS and Android. You will notice that the child view overflows the parent on iOS, but not on Android. Expected behaviour: the child view should overflow the parent if the parent is AbsoluteLayout.

iOS:
<img width="241" alt="screen shot 2016-06-08 at 6 56 41 pm" src="https://cloud.githubusercontent.com/assets/6477282/15902986/d4c1abd0-2daa-11e6-8f34-58a23094648c.png">

Android:
<img width="272" alt="screen shot 2016-06-08 at 6 56 35 pm" src="https://cloud.githubusercontent.com/assets/6477282/15902990/de512810-2daa-11e6-97e0-33c4b29d2bf4.png">

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd" >
 <GridLayout>
    <AbsoluteLayout width="100" height="100" backgroundColor="green">
        <GridLayout width="100" height="100" backgroundColor="red" top="20" left="-20">
        </GridLayout>
    </AbsoluteLayout>
 </GridLayout>
</Page>
```

**Comment by tsonevn** [comment]
Hi @terreb , 
Thank your for your issue,
In my opinion this is normal behavior for Android. As a solution you could use second GridLayout in the AbsoluteLayout in your sample code and it will work in the same way for both Android and iOS. You could review the attached code below:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" >  
<StackLayout>
     <AbsoluteLayout row="0" col="0" width="200" height="200" backgroundColor="green">
        <GridLayout width="100" height="100" backgroundColor="red" top="0" left="20">
        </GridLayout>
        <GridLayout width="100" height="100" backgroundColor="blue" top="20" left="0">
        </GridLayout>
    </AbsoluteLayout>
 </StackLayout>
</Page>

```
I hope this helps.

**Comment by terreb** [comment]
Hi @tsonevn. Thank you for the reply. The thing is my example doesn't show the whole picture of what I'm trying to implement and your solution unfortunately doesn't help. In the real app I've got a view which is positioned over a scroller. This view is draggable and has a certain dimensions. When it's clicked a child view which is inside is shown. This child view has much bigger size and hidden by default. I don't won't to wrap those both views inside a bigger wrapper, since I need to keep an overall small size of the view in order when the user clicks outside the view he interacts with the scroller. But if I have a transparent wrapper it will intercepts the user clicks and I will need to bubble them somehow to the scroller. So, to keep things as simpler as possible I just need the same behaviour on Android as on iOS : when the child view is shown it overlaps the parent. Also, the view can be dragged over the screen when the child view is collapsed. To prevent moving the view outside of the screen and outside some other elements I make calculations again based on its dimensions. The dimensions of the child view can change dynamically.

I suggest you guys consider this behaviour for Android too. This will be helpful considering you added support for PhysicsJS and such stuff can be widely used in games for example when the user drags a view inside AbsoluteLayout.

Thanks.

**Comment by tsonevn** [comment]
Hi @terreb , 

Thank you for your answer.
Could your sent us some sample project, which we can use to review the behavior you needs. 
Regards

**Comment by tsonevn** [comment]
Hi @terreb ,

In regard to your feature request for supporting PhysicsJS I found that we already support this feature. You could use this NativeScript plugin [plugin](https://www.npmjs.com/package/nativescript-physics-js), which allows you to use the whole PhysicsJS functionality. In addition you also could review the demo in this GitHub here [here](https://github.com/vakrilov/nativescript-physics-js).

I hope this is applicable for you.

**Comment by terreb** [comment]
Hi @tsonevn thank you for you replies. I know you guys already support PhysicsJS. I follow your progress:) What I meant is that behaviour of the child in AbsoluteLayout that I suggested would be a good bonus to PhysicsJS that you are already support. Plus would be great to have css overflow property to control this even better: set child items or their parts hidden when they go outside parent like it's now on Android or make them visible like it's now on iOS.  The reason for this is that for now if we want to have dynamically dragged views the best place for them is inside AbsoluteLayout. We can use top and left properties to position them inside. Sometimes there are cases when we need those views to be positioned outside the parent (AbsoluteLayout) bounds and still be visible on the screen. I do realize that current behaviour is absolutely normal for Android, but would be great to make this more controllable by having css overflow property. Thanks.

**Comment by TheOriginalJosh** [comment]
I would like to second that I don't think a child view should overflow its parent. Allow a child to be visible outside of the parent seems counter-intuitive. 

That being consistent across both platforms would be best, is it possible this could be optional?

**Comment by tsonevn** [comment]
Hi @terreb,

Excuse me for the delay in replying and thank you for your suggestion for supporting css `overflow` property. In regard to that you could open new issue where you are describing your feature request for `overflow` support. Furthermore other people could vote for this feature in the new issue. 

Regards,
@tsonevn

**Comment by terreb** [comment]
Hi @tsonevn ok, thank you.

**Comment by carloscabral** [comment]
Any updates about this?

**Comment by tsonevn** [comment]
Hi @carloscabral 
The issue is related to a missing feature, which is logged [here](https://github.com/NativeScript/NativeScript/issues/2354).
You can also check the provided solution in [this comment](https://github.com/NativeScript/NativeScript/issues/2354#issuecomment-228085206) in the feature requests.

**Comment by BenDietze** [comment]
https://github.com/NativeScript/NativeScript/issues/2354#issuecomment-414930792

So its not available in _native_ - how should it become a _native_ feature?

**Comment by carloscabral** [comment]
Hi, @tsonevn. I tried the provided solution you've mentioned above but it doesn't work for me. However,  I've managed to get this working by using native Android code for this problem:

`if (app.android && platform.device.sdkVersion >= '21') {
       myView.android.setClipChildren(false)
 }`

It would be great to have this featured exposed as a CSS overflow property in the upcoming version of NativeScript.

Thank you for answering!

**Comment by BenDietze** [comment]
I am not sure, maybe i tried clipChildren and it doesn't work as aspected overall. Is longer time ago. But if it would do the trick it would be great

**Comment by carloscabral** [comment]
@BenDietze you have to put this method in the parent(s) of the object. It works like a charm for me now. iOS and Android sharing the same layout.

**Comment by BenDietze** [comment]
@carloscabral 💯 

Ah, ok, might be is **SDK >= 21** ? I remember when testing i had < 21 - but today - thats great news!

Thanks 👍

**Comment by mudlabs** [comment]
From my experiment the native android solution _( from @carloscabral )_ works, and needs to be applied to the target views grandparent.

Also RE original post, it's worth noting that if the parent view has a background the child will be clipped. This issue is resolved by the native solution though _(haven't checked iOS native solution)_.

**Comment by SephReed** [comment]
This would be a very helpful addition in order to keep the results of ios and android the same.  Either making apple clip by default, or android not.

**Comment by szhatef** [comment]
clipToBound works, but if it set as true, and parent has borderRadius, {N} neglect the space between parent and child!

https://github.com/NativeScript/NativeScript/issues/8929
