### ISSUE TITLE
Feature Request: Determine if build is Release or Debug at runtime

### ISSUE THREAD

**Issue by speigg** [NativeScript/NativeScript#2275]
Assuming this isn't possible yet since I can't find anything in the API that would allow me to do this. 

I'd like to be able to check, at runtime, whether the current build is a release build or a debug build. The reason for this feature request: I want to popup an alert dialog whenever there are any errors, but only for a debug build. That way I can easily be made aware of errors even when my app is not currently attached to a debugger.

**Comment by NathanaelA** [comment]
You can use my nativescript-master-technology plugin, it has methods to detect on android if it is released or debug build.  Unfortunately the same methods don't work on iOS; so it currently assumes that it is a debug build if it is on a emulator and a release build if it is on a real device.

**Comment by speigg** [comment]
Ah, thanks! Unfortunately I'm developing for iOS (for now).

**Comment by speigg** [comment]
@NathanaelA If I get around to it, I may send you a pull request which makes it work for iOS (assuming it's straightforward). Or I may just wait for someone else to do it :) 

I'll close this issue and keep your plugin in mind. 
Thanks.
