### ISSUE TITLE
Canvas & Bitmap class issue

### ISSUE THREAD

**Issue by Onkarn92** [NativeScript/NativeScript#2279]
tns version - 2.0.1
I am developing cross platform app and i want to use following classes in nativescript app for android build - 

android.graphics.Bitmap;
android.graphics.BitmapFactory;
android.graphics.Canvas;
android.graphics.Color;
android.graphics.Paint;
android.graphics.Rect;
android.graphics.RectF;
android.graphics.drawable.BitmapDrawable;
android.graphics.drawable.Drawable;

I need to create bitmap, put it in rectangle and draw bitmap using canvas class. But didn't find any documentation. Is there any way to use native classes in NativeScript applications? Please let me know.

**Comment by NickIliev** [comment]
Hello @Onkarn92 

You can use the native classes in NativeScript via [marshalling ](https://docs.nativescript.org/runtimes/android/marshalling/overview)(data conversion)

And to be more specific here is an direct link to the 
[Java-to-JavaScript convesrion articile](https://docs.nativescript.org/runtimes/android/marshalling/java-to-js) in our documenation.

Some marshalling examples:
```
var someBounds = new android.graphics.RectF(100, 100, 100, 100);

var myImageSource= imageSource.fromFileOrResource(icon);
var drawable = new android.graphics.drawable.BitmapDrawable(myImageSource.android);

var appContext = app.android.context; // where app is application module

// (example for: java static interface to javaScript )
var mOnImageAvailableListener = new android.media.ImageReader.OnImageAvailableListener({
    onImageAvailable: function (reader) {
    }
});  
```

**Comment by Onkarn92** [comment]
@NickIliev Really appreciate for your help, i will try marshaling technique. Please check following link, I want to achieve something like that - http://stackoverflow.com/questions/37724634/nativescript-bitmap-canvas
