### ISSUE TITLE
ListPicker for Android shows text after bound to an empty array.

### ISSUE THREAD

**Issue by hamorphis** [NativeScript/NativeScript#228]
If the ListPicker was originally bound to an array of strings and subsequently bound to an empty/null/undefined array, the last selected item could be still seen. The problem comes from the fact that the Android NumberPicker has no concept of zero items, i.e. it always has to have at least one item which is zero (minValue = value = maxValue = 0).

**Comment by valentinstoychev** [comment]
Maybe we can show "empty message" in this case?

**Comment by hamorphis** [comment]
We can show anything as long as the NumberPicker let's us do it :). It seems to cache something inside and I might resort to reflection in order to fight it! I am currently reading its source code to see what it does internally.
