### ISSUE TITLE
[Question] How to call SOAP web services 

### ISSUE THREAD

**Issue by Onkarn92** [NativeScript/NativeScript#2284]
**tns version - 2.0.1**
**Platform - android**

Hi, I want to use SOAP web services with SOAP request & response format in nativescript. In android there is soap library "**ksoap2-android**", but i didn't find any soap library in nativescript. I need to pass data in XML format. is there any plugin/library in nativescript for SOAP services?. I tried following code but didn't worked for me - 

```
 var xmlHttp = new XMLHttpRequest();
    xmlHttp.open('POST','http://MY_DOMAIN_ADDRESS/WebService.asmx',true);
    var soapRequest =  '<?xml version="1.0" encoding="utf-8"?>' +
                        '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"'+
  	                    '<soapenv:Header/>'+
                        '<soapenv:Body>'+
                            '<web:GetUserLoginForApp>'+                          
                                '<web:UserName>USERNAME</web:UserName>'+                         
                                '<web:Password>PASSWORD</web:Password>'+
                            '</web:GetUserLoginForApp>'+
                        '</soapenv:Body>'+
                        '</soapenv:Envelope>' ;

                         xmlHttp.onreadystatechange = function () {
                            if (xmlHttp.readyState == 4) {
                                if (xmlHttp.status == 200) {
                                    alert('done. use firebug/console to see network response');
                                }
                            }
                        }
       xmlHttp.setRequestHeader('Content-Type', 'text/xml');
            xmlHttp.send(soapRequest);
```

I did console.log, but output is null/UNKNOWN. I'm confused about the problem. Please help me :) Thanks

**Comment by NickIliev** [comment]
Hello @Onkarn92 

Do you have actual SOAP service from which you can receive a response!?
For example I have used this test service from w3schools
```
http://www.w3schools.com/webservices/tempconvert.asmx
```

And was able to receive a response with no problem.
For example in your code use this line:
```
xmlHttp.open('POST','http://www.w3schools.com/webservices/tempconvert.asmx',true);
```
and also log the response from the service
```
        if (xmlHttp.readyState == 4) {
            console.log(xmlHttp.responseText);
            // ... more code follows
```

Of course you will have to modify your soapRequest to actually convert from Fahrenheit (in your case you will have to pas your login service) but still you will receive a response with html page 404 which is valid response

**Comment by therevills** [comment]
Hi, I've managed to call my WS but I dont know how to parse the reponseText. Could you please show me an example on parsing? I've found that NS has an XML Parser (https://docs.nativescript.org/cookbook/xml-parser#xml-module) but having trouble using it with TypeScript...

**Comment by achernar9** [comment]
Is there anyone who has tried the examples with long soap responses? I tried these but response data is not healthy, for ex: response string has 3000 characters (approximately). but on NS, I ve 970 characters.  whats the reason? its about JS or NS? or what??
