### ISSUE TITLE
[Feedback] Could not run sample-Groceries-master

### ISSUE THREAD

**Issue by meow0703** [NativeScript/NativeScript#2289]
Debug log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'nativescript' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose install initial load of C:\Users\root\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\root\AppData\Roaming\npm\package.json
6 silly cache add args [ 'nativescript', null ]
7 verbose cache add spec nativescript
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'nativescript',
8 silly cache add   scope: null,
8 silly cache add   name: 'nativescript',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed nativescript@latest
10 verbose addNamed "latest" is being treated as a dist-tag for nativescript
11 info addNameTag [ 'nativescript', 'latest' ]
12 silly mapToRegistry name nativescript
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'nativescript',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'nativescript',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/nativescript
17 verbose addNameTag registry:https://registry.npmjs.org/nativescript not in flight; fetching
18 verbose request uri https://registry.npmjs.org/nativescript
19 verbose request no auth needed
20 info attempt registry request try #1 at 04:03:25
21 verbose request id 221ce93003d0bbd8
22 verbose etag "E4Y98DACHS21H5RMCYQIJEOGU"
23 http request GET https://registry.npmjs.org/nativescript
24 http 304 https://registry.npmjs.org/nativescript
25 verbose headers { date: 'Fri, 10 Jun 2016 21:03:26 GMT',
25 verbose headers   via: '1.1 varnish',
25 verbose headers   'cache-control': 'max-age=300',
25 verbose headers   etag: '"E4Y98DACHS21H5RMCYQIJEOGU"',
25 verbose headers   age: '162',
25 verbose headers   connection: 'keep-alive',
25 verbose headers   'x-served-by': 'cache-hkg6823-HKG',
25 verbose headers   'x-cache': 'HIT',
25 verbose headers   'x-cache-hits': '1',
25 verbose headers   'x-timer': 'S1465592606.050342,VS0,VE0',
25 verbose headers   vary: 'Accept-Encoding' }
26 silly get cb [ 304,
26 silly get   { date: 'Fri, 10 Jun 2016 21:03:26 GMT',
26 silly get     via: '1.1 varnish',
26 silly get     'cache-control': 'max-age=300',
26 silly get     etag: '"E4Y98DACHS21H5RMCYQIJEOGU"',
26 silly get     age: '162',
26 silly get     connection: 'keep-alive',
26 silly get     'x-served-by': 'cache-hkg6823-HKG',
26 silly get     'x-cache': 'HIT',
26 silly get     'x-cache-hits': '1',
26 silly get     'x-timer': 'S1465592606.050342,VS0,VE0',
26 silly get     vary: 'Accept-Encoding' } ]
27 verbose etag https://registry.npmjs.org/nativescript from cache
28 verbose get saving nativescript to C:\Users\root\AppData\Roaming\npm-cache\registry.npmjs.org\nativescript\.cache.json
29 verbose correctMkdir C:\Users\root\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
30 silly addNameTag next cb for nativescript with tag latest
31 silly addNamed nativescript@2.0.1
32 verbose addNamed "2.0.1" is a plain semver version for nativescript
33 silly cache afterAdd nativescript@2.0.1
34 verbose afterAdd C:\Users\root\AppData\Roaming\npm-cache\nativescript\2.0.1\package\package.json not in flight; writing
35 verbose correctMkdir C:\Users\root\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
36 verbose afterAdd C:\Users\root\AppData\Roaming\npm-cache\nativescript\2.0.1\package\package.json written
37 silly install resolved [ { name: 'nativescript',
37 silly install resolved     preferGlobal: true,
37 silly install resolved     version: '2.0.1',
37 silly install resolved     author: { name: 'Telerik', email: 'support@telerik.com' },
37 silly install resolved     description: 'Command-line interface for building NativeScript projects',
37 silly install resolved     bin:
37 silly install resolved      { tns: './bin/nativescript.js',
37 silly install resolved        nativescript: './bin/nativescript.js' },
37 silly install resolved     main: './lib/nativescript-cli.js',
37 silly install resolved     repository:
37 silly install resolved      { type: 'git',
37 silly install resolved        url: 'git+https://github.com/NativeScript/nativescript-cli.git' },
37 silly install resolved     keywords: [ 'nativescript', 'telerik', 'mobile' ],
37 silly install resolved     dependencies:
37 silly install resolved      { bluebird: '2.9.34',
37 silly install resolved        'bplist-parser': '0.1.0',
37 silly install resolved        broccoli: '0.16.4',
37 silly install resolved        'broccoli-funnel': '0.2.3',
37 silly install resolved        bufferpack: '0.0.6',
37 silly install resolved        bufferutil: 'https://github.com/telerik/bufferutil/tarball/v1.0.1.1',
37 silly install resolved        byline: '4.2.1',
37 silly install resolved        chalk: '1.1.0',
37 silly install resolved        'cli-table': 'https://github.com/telerik/cli-table/tarball/v0.3.1.2',
37 silly install resolved        clui: '0.3.1',
37 silly install resolved        colors: '1.1.2',
37 silly install resolved        esprima: '2.7.0',
37 silly install resolved        ffi: 'https://github.com/icenium/node-ffi/tarball/v2.0.0.1',
37 silly install resolved        fibers: 'https://github.com/icenium/node-fibers/tarball/v1.0.6.3',
37 silly install resolved        filesize: '3.1.2',
37 silly install resolved        gaze: '0.5.2',
37 silly install resolved        glob: '^7.0.3',
37 silly install resolved        'iconv-lite': '0.4.11',
37 silly install resolved        inquirer: '0.9.0',
37 silly install resolved        'ios-sim-portable': '~1.0.20',
37 silly install resolved        lockfile: '1.0.1',
37 silly install resolved        lodash: '3.10.0',
37 silly install resolved        log4js: '0.6.26',
37 silly install resolved        marked: '0.3.3',
37 silly install resolved        'marked-terminal': '1.5.0',
37 silly install resolved        minimatch: '2.0.10',
37 silly install resolved        mkdirp: '0.5.1',
37 silly install resolved        moment: '2.10.6',
37 silly install resolved        'mute-stream': '0.0.5',
37 silly install resolved        'node-inspector': 'https://github.com/NativeScript/node-inspector/tarball/v0.7.4.1',
37 silly install resolved        'node-uuid': '1.4.3',
37 silly install resolved        npm: '2.14.12',
37 silly install resolved        open: '0.0.5',
37 silly install resolved        osenv: '0.1.3',
37 silly install resolved        plist: '1.1.0',
37 silly install resolved        'plist-merge-patch': '0.0.9',
37 silly install resolved        plistlib: '0.2.1',
37 silly install resolved        'progress-stream': '1.1.1',
37 silly install resolved        'properties-parser': '0.2.3',
37 silly install resolved        ref: 'https://github.com/icenium/ref/tarball/v1.1.3.1',
37 silly install resolved        'ref-struct': 'https://github.com/telerik/ref-struct/tarball/v1.0.2.1',
37 silly install resolved        semver: '5.0.1',
37 silly install resolved        shelljs: '0.5.3',
37 silly install resolved        tabtab: 'https://github.com/Icenium/node-tabtab/tarball/master',
37 silly install resolved        temp: '0.8.3',
37 silly install resolved        'utf-8-validate': 'https://github.com/telerik/utf-8-validate/tarball/v1.0.1.1',
37 silly install resolved        winreg: '0.0.17',
37 silly install resolved        ws: '0.7.1',
37 silly install resolved        xcode: 'https://github.com/NativeScript/node-xcode/archive/1.4.0.tar.gz',
37 silly install resolved        xmldom: '0.1.21',
37 silly install resolved        xmlhttprequest: 'https://github.com/telerik/node-XMLHttpRequest/tarball/master',
37 silly install resolved        yargs: '3.15.0' },
37 silly install resolved     analyze: true,
37 silly install resolved     devDependencies:
37 silly install resolved      { chai: '1.8.x',
37 silly install resolved        grunt: '0.4.5',
37 silly install resolved        'grunt-contrib-clean': '0.6.0',
37 silly install resolved        'grunt-contrib-copy': '0.8.0',
37 silly install resolved        'grunt-contrib-watch': '0.6.1',
37 silly install resolved        'grunt-shell': '1.1.2',
37 silly install resolved        'grunt-ts': '4.2.0',
37 silly install resolved        'grunt-tslint': '3.0.1',
37 silly install resolved        istanbul: '0.3.19',
37 silly install resolved        mocha: '2.2.5',
37 silly install resolved        'mocha-fibers': 'https://github.com/Icenium/mocha-fibers/tarball/master',
37 silly install resolved        should: '7.0.2',
37 silly install resolved        tslint: '3.2.1',
37 silly install resolved        typescript: '1.7.5' },
37 silly install resolved     license: 'Apache-2.0',
37 silly install resolved     engines: { node: '>=0.10.40 <0.11.0 || >=0.12.7 <0.13.0 || >=4.2.1 <5.0.0 || >=5.1.0 <6.0.0' },
37 silly install resolved     scripts:
37 silly install resolved      { test: 'istanbul cover node_modules/mocha/bin/_mocha -- --ui mocha-fibers --recursive --reporter spec --require test/test-bootstrap.js --timeout 150000 test/ lib/common/test/unit-tests',
37 silly install resolved        postinstall: 'node postinstall.js',
37 silly install resolved        preuninstall: 'node preuninstall.js' },
37 silly install resolved     bugs: { url: 'https://github.com/NativeScript/nativescript-cli/issues' },
37 silly install resolved     homepage: 'https://github.com/NativeScript/nativescript-cli#readme',
37 silly install resolved     _id: 'nativescript@2.0.1',
37 silly install resolved     _shasum: '4834bcf936f9d63ea988054bd16380ceb648eae6',
37 silly install resolved     _resolved: 'https://registry.npmjs.org/nativescript/-/nativescript-2.0.1.tgz',
37 silly install resolved     _from: 'nativescript@latest',
37 silly install resolved     _npmVersion: '2.14.7',
37 silly install resolved     _nodeVersion: '4.2.2',
37 silly install resolved     _npmUser: { name: 'enchev', email: 'vladimir.enchev@gmail.com' },
37 silly install resolved     dist:
37 silly install resolved      { shasum: '4834bcf936f9d63ea988054bd16380ceb648eae6',
37 silly install resolved        tarball: 'https://registry.npmjs.org/nativescript/-/nativescript-2.0.1.tgz' },
37 silly install resolved     maintainers:
37 silly install resolved      [ [Object],
37 silly install resolved        [Object],
37 silly install resolved        [Object],
37 silly install resolved        [Object],
37 silly install resolved        [Object],
37 silly install resolved        [Object],
37 silly install resolved        [Object],
37 silly install resolved        [Object],
37 silly install resolved        [Object],
37 silly install resolved        [Object],
37 silly install resolved        [Object],
37 silly install resolved        [Object],
37 silly install resolved        [Object] ],
37 silly install resolved     _npmOperationalInternal:
37 silly install resolved      { host: 'packages-16-east.internal.npmjs.com',
37 silly install resolved        tmp: 'tmp/nativescript-2.0.1.tgz_1463659227678_0.3444894526619464' },
37 silly install resolved     directories: {},
37 silly install resolved     readme: 'ERROR: No README data found!' } ]
38 info install nativescript@2.0.1 into C:\Users\root\AppData\Roaming\npm
39 info installOne nativescript@2.0.1
40 verbose installOne of nativescript to C:\Users\root\AppData\Roaming\npm not in flight; installing
41 verbose correctMkdir C:\Users\root\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
42 verbose lock using C:\Users\root\AppData\Roaming\npm-cache\_locks\nativescript-f463a96406b0591b.lock for C:\Users\root\AppData\Roaming\npm\node_modules\nativescript
43 silly install write writing nativescript 2.0.1 to C:\Users\root\AppData\Roaming\npm\node_modules\nativescript
44 verbose unbuild node_modules\nativescript
45 info preuninstall nativescript@2.0.1
46 verbose unsafe-perm in lifecycle true
47 info uninstall nativescript@2.0.1
48 verbose unbuild rmStuff nativescript@2.0.1 from C:\Users\root\AppData\Roaming\npm\node_modules
49 silly gentlyRm C:\Users\root\AppData\Roaming\npm\tns.cmd is being gently removed
50 silly gentlyRm verifying C:\Users\root\AppData\Roaming\npm is an npm working directory
51 silly gentlyRm C:\Users\root\AppData\Roaming\npm\nativescript.cmd is being gently removed
52 silly gentlyRm verifying C:\Users\root\AppData\Roaming\npm is an npm working directory
53 silly gentlyRm containing path C:\Users\root\AppData\Roaming\npm is under npm's control, in C:\Users\root\AppData\Roaming\npm
54 silly gentlyRm deletion target C:\Users\root\AppData\Roaming\npm\tns.cmd is under C:\Users\root\AppData\Roaming\npm
55 verbose gentlyRm vacuuming from C:\Users\root\AppData\Roaming\npm\tns.cmd up to C:\Users\root\AppData\Roaming\npm
56 silly gentlyRm containing path C:\Users\root\AppData\Roaming\npm is under npm's control, in C:\Users\root\AppData\Roaming\npm
57 silly gentlyRm deletion target C:\Users\root\AppData\Roaming\npm\nativescript.cmd is under C:\Users\root\AppData\Roaming\npm
58 verbose gentlyRm vacuuming from C:\Users\root\AppData\Roaming\npm\nativescript.cmd up to C:\Users\root\AppData\Roaming\npm
59 silly vacuum-fs removing C:\Users\root\AppData\Roaming\npm\tns.cmd
60 silly vacuum-fs removing C:\Users\root\AppData\Roaming\npm\nativescript.cmd
61 silly vacuum-fs finished vacuuming up to C:\Users\root\AppData\Roaming\npm
62 silly gentlyRm C:\Users\root\AppData\Roaming\npm\tns is being gently removed
63 silly gentlyRm verifying C:\Users\root\AppData\Roaming\npm is an npm working directory
64 silly gentlyRm containing path C:\Users\root\AppData\Roaming\npm is under npm's control, in C:\Users\root\AppData\Roaming\npm
65 silly gentlyRm deletion target C:\Users\root\AppData\Roaming\npm\tns is under C:\Users\root\AppData\Roaming\npm
66 verbose gentlyRm vacuuming from C:\Users\root\AppData\Roaming\npm\tns up to C:\Users\root\AppData\Roaming\npm
67 silly vacuum-fs finished vacuuming up to C:\Users\root\AppData\Roaming\npm
68 silly gentlyRm C:\Users\root\AppData\Roaming\npm\nativescript is being gently removed
69 silly gentlyRm verifying C:\Users\root\AppData\Roaming\npm is an npm working directory
70 silly gentlyRm containing path C:\Users\root\AppData\Roaming\npm is under npm's control, in C:\Users\root\AppData\Roaming\npm
71 silly gentlyRm deletion target C:\Users\root\AppData\Roaming\npm\nativescript is under C:\Users\root\AppData\Roaming\npm
72 verbose gentlyRm vacuuming from C:\Users\root\AppData\Roaming\npm\nativescript up to C:\Users\root\AppData\Roaming\npm
73 silly vacuum-fs removing C:\Users\root\AppData\Roaming\npm\tns
74 silly vacuum-fs removing C:\Users\root\AppData\Roaming\npm\nativescript
75 silly vacuum-fs finished vacuuming up to C:\Users\root\AppData\Roaming\npm
76 silly vacuum-fs finished vacuuming up to C:\Users\root\AppData\Roaming\npm
77 info postuninstall nativescript@2.0.1
78 silly gentlyRm C:\Users\root\AppData\Roaming\npm\node_modules\nativescript is being purged from base C:\Users\root\AppData\Roaming\npm
79 verbose gentlyRm don't care about contents; nuking C:\Users\root\AppData\Roaming\npm\node_modules\nativescript
80 silly vacuum-fs purging C:\Users\root\AppData\Roaming\npm\node_modules\nativescript
81 verbose unlock done using C:\Users\root\AppData\Roaming\npm-cache\_locks\nativescript-f463a96406b0591b.lock for C:\Users\root\AppData\Roaming\npm\node_modules\nativescript
82 verbose stack Error: EBUSY: resource busy or locked, rmdir 'C:\Users\root\AppData\Roaming\npm\node_modules\nativescript'
82 verbose stack     at Error (native)
83 verbose cwd C:\Users\root\Downloads\sample-Groceries-master
84 error Windows_NT 10.0.10586
85 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "nativescript"
86 error node v4.4.4
87 error npm  v2.15.1
88 error path C:\Users\root\AppData\Roaming\npm\node_modules\nativescript
89 error code EBUSY
90 error errno -4082
91 error syscall rmdir
92 error EBUSY: resource busy or locked, rmdir 'C:\Users\root\AppData\Roaming\npm\node_modules\nativescript'
93 error If you need help, you may report this error at:
93 error     <https://github.com/npm/npm/issues>
94 verbose exit [ -4082, true ]
95 verbose unbuild node_modules\nativescript
96 info preuninstall nativescript@2.0.1
97 verbose unsafe-perm in lifecycle true
98 info uninstall nativescript@2.0.1
99 verbose unbuild rmStuff nativescript@2.0.1 from C:\Users\root\AppData\Roaming\npm\node_modules
100 silly gentlyRm C:\Users\root\AppData\Roaming\npm\tns.cmd is being gently removed
101 silly gentlyRm verifying C:\Users\root\AppData\Roaming\npm is an npm working directory
102 silly gentlyRm C:\Users\root\AppData\Roaming\npm\nativescript.cmd is being gently removed
103 silly gentlyRm verifying C:\Users\root\AppData\Roaming\npm is an npm working directory
104 silly gentlyRm containing path C:\Users\root\AppData\Roaming\npm is under npm's control, in C:\Users\root\AppData\Roaming\npm
105 silly gentlyRm deletion target C:\Users\root\AppData\Roaming\npm\tns.cmd is under C:\Users\root\AppData\Roaming\npm
106 verbose gentlyRm vacuuming from C:\Users\root\AppData\Roaming\npm\tns.cmd up to C:\Users\root\AppData\Roaming\npm
107 silly gentlyRm containing path C:\Users\root\AppData\Roaming\npm is under npm's control, in C:\Users\root\AppData\Roaming\npm
108 silly gentlyRm deletion target C:\Users\root\AppData\Roaming\npm\nativescript.cmd is under C:\Users\root\AppData\Roaming\npm
109 verbose gentlyRm vacuuming from C:\Users\root\AppData\Roaming\npm\nativescript.cmd up to C:\Users\root\AppData\Roaming\npm
110 silly gentlyRm C:\Users\root\AppData\Roaming\npm\tns is being gently removed
111 silly gentlyRm verifying C:\Users\root\AppData\Roaming\npm is an npm working directory
112 silly gentlyRm containing path C:\Users\root\AppData\Roaming\npm is under npm's control, in C:\Users\root\AppData\Roaming\npm
113 silly gentlyRm deletion target C:\Users\root\AppData\Roaming\npm\tns is under C:\Users\root\AppData\Roaming\npm
114 verbose gentlyRm vacuuming from C:\Users\root\AppData\Roaming\npm\tns up to C:\Users\root\AppData\Roaming\npm
115 silly gentlyRm C:\Users\root\AppData\Roaming\npm\nativescript is being gently removed
116 silly gentlyRm verifying C:\Users\root\AppData\Roaming\npm is an npm working directory
117 silly gentlyRm containing path C:\Users\root\AppData\Roaming\npm is under npm's control, in C:\Users\root\AppData\Roaming\npm
118 silly gentlyRm deletion target C:\Users\root\AppData\Roaming\npm\nativescript is under C:\Users\root\AppData\Roaming\npm
119 verbose gentlyRm vacuuming from C:\Users\root\AppData\Roaming\npm\nativescript up to C:\Users\root\AppData\Roaming\npm
120 info postuninstall nativescript@2.0.1
121 silly gentlyRm C:\Users\root\AppData\Roaming\npm\node_modules\nativescript is being purged from base C:\Users\root\AppData\Roaming\npm
122 verbose gentlyRm don't care about contents; nuking C:\Users\root\AppData\Roaming\npm\node_modules\nativescript
123 silly vacuum-fs purging C:\Users\root\AppData\Roaming\npm\node_modules\nativescript
124 error error rolling back Error: EBUSY: resource busy or locked, rmdir 'C:\Users\root\AppData\Roaming\npm\node_modules\nativescript'
124 error error rolling back     at Error (native)
124 error error rolling back  { [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\root\AppData\Roaming\npm\node_modules\nativescript']
124 error error rolling back   errno: -4082,
124 error error rolling back   code: 'EBUSY',
124 error error rolling back   syscall: 'rmdir',
124 error error rolling back   path: 'C:\\Users\\root\\AppData\\Roaming\\npm\\node_modules\\nativescript' }

**Comment by dtopuzov** [comment]
@meow0703 as first step, let's try to solve your issues with {N} installation. 
sample-Groceries can build if {N} is properly installed and setup.
