### ISSUE TITLE
Remove ActionItem icon border in Android

### ISSUE THREAD

**Issue by fmmsilva** [NativeScript/NativeScript#2292]
How do I remove the border from the icons used with ActionItem with Android, so they look more like Material Design?
![captura de tela 2016-06-11 as 12 50 15](https://cloud.githubusercontent.com/assets/2180350/15985959/1b662dde-2fd3-11e6-8775-d09806b55911.png)

I want to make the icons white and flat..

**Comment by NickIliev** [comment]
Hello @fmmsilva 

I am guessing you are using the built-in system icons like 
 ```
android.systemIcon = "ic_menu_search" 
 ```
This solution can not be styled however you can use a different aproach.
One solution is to use your own material-style icons lin your **_app/App_Resource/Android_** where you
should provide images for the different resolutions and then use the like this.
 ```              
<ActionItem icon="res://my_search_icon"  />
 ```

or create your own images folder and use its resource with its relative path
 ```            
<!-- for example this is image situated in app/images/search.png -->  
<ActionItem icon="~/images/search.png"  />
 ```

Another solution is to use Icon Fonts (like [IcoMoon](https://icomoon.io/) and [Font Awesome](http://fontawesome.io/)) for creating your icons. 

Example app demostrating Icon Fonts usage in NativeScript you can find [here](http://fontawesome.io/)
The documentatyion article about icon fonts : [https://docs.nativescript.org/angular/ui/icon-fonts](https://docs.nativescript.org/angular/ui/icon-fonts)

**Comment by fmmsilva** [comment]
Thank you!
