### ISSUE TITLE
[iOS] Cannot hide status bar

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#2294]
I am trying to hide the status bar on iOS, and it does not seem to work at all. I've also tried using the plugin from @PeterStaev. 

Info.plist
```xml
<key>UIStatusBarHidden</key>
<true/>
<key>UIViewControllerBasedStatusBarAppearance</key>
<false/>
```

main-view.js
```js

exports.loaded = function(args){
    page = args.object;
    page.bindingContext = pageData;

    UIApplication.sharedApplication().setStatusBarHiddenWithAnimation(true, UIStatusBarAnimation.UIStatusBarAnimationSlide);
}
```

iOS: 9.3
CLI & runtime: 2.0.1

**Comment by NordlingArt** [comment]
Don't think you need the first said key (`UIStatusBarHidden`) in the Info.plist. I don't have it and it works with only the second one. Have you tried removing it? Maybe it's a conflict between them.

**Comment by manijak** [comment]
Yeah I tried both, just added the UIStatusBarHidde to try that as well, but it did not work...

**Comment by manijak** [comment]
UPDATE: I remove the `UIStatusBarHidden`flag and RESTARTED the iOS emulator, now it works! :)
