### ISSUE TITLE
Can't build/run/anything

### ISSUE THREAD

**Issue by p4ulolol** [NativeScript/NativeScript#2297]
Hello,

I can't do anything with the CLI because my NPM is broken so it can't access the internet (EAI_AGAIN, I tried everything that is on Google), and every CLI command needs to download something (I don't know what) with NPM

For instance, if I type `tns run android`, I get this :

```
Copying template files...
Failed to retrieve data from npm. Please try again a little bit later.. Error: E
rror: getaddrinfo EAI_AGAIN registry.npmjs.eu:80
# run android
┌────────────────┬──────────────────────────────────────────────────────────┐
│ Usage          │ Synopsis                                                 │
│ Run on all     │ $ tns run android [--key-store-path <File Path> --key    │
│ connected      │ -store-password <Password> --key-store-alias <Name> -    │
│ devices and    │ -key-store-alias-password <Password>] [--release] [-     │
│ running        │ -justlaunch]                                             │
│ emulators      │                                                          │
│ Run on a       │ $ tns run android --device <Device ID> [--key-store-path │
│ selected       │ <File Path> --key-store-password <Password> --key-store  │
│ connected      │ -alias <Name> --key-store-alias-password <Password>] [-  │
│ device or      │ -release] [--justlaunch]                                 │
│ running        │                                                          │
│ emulator       │                                                          │
│ Start an       │ $ tns run android --emulator [<Emulator Options>] [--key │
│ emulator and   │ -store-path <File Path> --key-store-password <Password>  │
│ run the app    │ --key-store-alias <Name> --key-store-alias-password      │
│ inside it      │ <Password>] [--release] [--justlaunch]                   │
└────────────────┴──────────────────────────────────────────────────────────┘

Runs your project on a connected Android device or in a native Android emulator,
 if configured. This is shorthand for prepare, build and deploy. While your app
is running, prints the output from the application in the console.

### Options

    * --device - Specifies a connected device on which to run the app.
    * --emulator - If set, runs the app in a native emulator for the target plat
form, if configured. When set, you can also set any other valid combination of e
mulator options as listed by $ tns help emulate android.
    * --release - If set, produces a release build. Otherwise, produces a debug
build. When set, you must also specify the --key-store-* options.
    * --key-store-path - Specifies the file path to the keystore file (P12) whic
h you want to use to code sign your APK. You can use the --key-store-* options a
long with --release to produce a signed release build. You need to specify all -
-key-store-* options.
    * --key-store-password - Provides the password for the keystore file specifi
ed with --key-store-path. You can use the --key-store-* options along with --rel
ease to produce a signed release build. You need to specify all --key-store-* op
tions.
    * --key-store-alias - Provides the alias for the keystore file specified wit
h --key-store-path. You can use the --key-store-* options along with --release t
o produce a signed release build. You need to specify all --key-store-* options.

    * --key-store-alias-password - Provides the password for the alias specified
 with --key-store-alias-password. You can use the --key-store-* options along wi
th --release to produce a signed release build. You need to specify all --key-st
ore-* options.
    * --justlaunch - If set, does not print the application output in the consol
e.

### Attributes

    * <Device ID> is the index or name of the target device as listed by $ tns d
evice android
    * <Emulator Options> is any valid combination of options as listed by $ tns
help emulate android

Sending exception report (press Ctrl+C to stop).....
```
I installed tns-android with NPM with a local folder in my project but it still wants to install it...

**Comment by NickIliev** [comment]
Hello @p4ulolol 

When executing **tns run android** what is essentially going on is that your app is trying to retreive all the dependencies and dev-dependencies described in your **_package.json_** file and as those are npm dependencies it will fail if you don't have working node.js or don't have internet connection and your dependencies are not retreived from the source.
Keep in mind that every dependency in package.json may have additional own dependencies in its own package.json file.(For example your app has dependency on plugin-A, but plguin-A has dependencies on some other npm packets).

What version of **Node.js** are you using - consider using lastest stable release like **v4.4.5**
Also as suggested [here](https://github.com/npm/npm/issues/7348) this error is probably caused not by NPM but by a internet settings. Still this may be resolved when using a newer stable release of npm.

Also if you are using a proxy check your proxy setting and mkake4 sure you can reach [https://registry.npmjs.org](https://registry.npmjs.org)

**Comment by p4ulolol** [comment]
I'm currently running Node v5.5.0 and npm 3.3.12. I know I have proxy problems (but I have no proxy !), etc., I'm still looking for a way to solve it. Proof I can join https://registry.npmjs.org/ :
`{"db_name":"registry","doc_count":338899,"doc_del_count":356,"update_seq":2717965,"purge_seq":0,"compact_running":false,"disk_size":1553211515,"data_size":1287088580,"instance_start_time":"1465532520116000","disk_format_version":6,"committed_update_seq":2717965}`

I also tried to re-install npm but that doesn't work (I'm now on 3.5.0)

**Comment by NickIliev** [comment]
@p4ulolol  Some firewalls /anitvirus software can cause this behavour as well.

Try the following sollution:
Command to see your npm configuration settings
```
npm config list
```
or the full details with the key -l
```
npm config list -l
```

Additionally to set your npm registry explicitly use the following  
```
npm config set registry http://registry.npmjs.org/
```

**Comment by p4ulolol** [comment]
Hey, thanx, I don't know why, but I was using the npmjs.eu registry, which may no more work... I'm not sure (as I have other errors now) but I think you solved my biggest problem with NPM :)
