### ISSUE TITLE
Rotating the device makes ListView desappear (iOS)

### ISSUE THREAD

**Issue by jgamedev** [NativeScript/NativeScript#23]
While completing the in-browser AppBuilder tutorial and testing in both platforms, I noticed that in iOS the list  - or its contents -   desappears quite frequently when you rotate the device.

If you try to scroll, the list re-appears.

Tested on Ipod 5 running iOS 7.0.4

**Comment by ligaz** [comment]
This issue was moved to NativeScript/cross-platform-modules#233
