### ISSUE TITLE
Search in documentation leads to 404

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#230]
Search for "local settings" and click on the first link - it leads to 404. The link is http://docs.nativescript.org/ApiReference/local-settings/HOW-TO.html

Probably this is related to the fact that this module do not exist any more, but I can't be sure.

**Comment by ErjanGavalji** [comment]
Exactly.
The `local-settings` module got renamed to `application-settings` and the search engine has cached the old location for the search. It will get removed automatically on the next crawling step.

I'm closing the issue now. Let's reopen it if problem persists.
