### ISSUE TITLE
Error: Corrupted Navigation Stack

### ISSUE THREAD

**Issue by dohpaz42** [NativeScript/NativeScript#2303]
### Tell us about the problem
App crashes after navigating Back from a previously-navigated frame after using Frames.topmost().navigate().

### Which platform(s) does your issue occur on?
**iOS**

### Please provide the following version numbers that your issue occurs with:
- CLI: **2.0.1**
- Cross-platform modules: **2.0.1**
- Runtime(s): iOS **2.0.1**, andriod **2.0.0**
- Plugin(s): N/A

### Please tell us how to recreate the issue in as much detail as possible.
When navigating _Back_ after using `Frames.topmost().navigate()` the app crashes due to an exception thrown from line **174** in **frame-common.js**.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Reproducable using the following code:

    var Frames = require('ui/frame');

    exports.onLoaded = function(args) {
        Frames.topmost().navigate('views/main/main');
    }

**Comment by tsonevn** [comment]
Hi @dohpaz42,
Thank you reporting this issue.

I reviewed your issue while using `navigate` on  page `loaded`. However I think that this is normal behavior for iOS project. When you redirect to next page  on  page `loaded`, every time you to to go back to this page you will be redirect to `views/main/main`. This scenario would broke `navigation stack`.

If you want to change main page you could set  in `app.js` file new `moduleName` like that:
```
application.start({moduleName:"newMainPage"});
``` 
You could also review my sample project, where I am using code similar to your example.
[project](https://github.com/tsonevn/NavigationGoBack.git)

I hope this helps.

**Comment by dohpaz42** [comment]
My intent is to have a loading screen that would pull external data locally on the device. It would be like a splash screen, except that it would have a progress bar and show "Loading <component>..." so the user would get the idea of what is going on. After everything loads, it would then move the user automatically to the real main page. But, by default when using `navigate`, the navigation bar has a "Back" button. I want the "splash" screen to be there, but I don't want the user to be able to go back to it. I do understand that with some effort, the back button could be removed. I would probably go that route.

That being said, I understand what you're saying. But I would counter that while the situation might be unique, what is the right way to handle a situation where the user is directed to a new frame, but then decides to go back? Forgive me if I'm being naive; yesterday  was literally my first day with NativeScript, so I'm still learning.

**Comment by eduardoturconi** [comment]
And what about using `clearHistory` or `backstackVisible` properties in navigate?

**Comment by dohpaz42** [comment]
@eduardoturconi, I'm not sure that I follow what you mean by your question? Have I used them? No. I didn't know they existed until just now. Are you suggesting that I should use them to prevent the app crashing? If so, would you know of any example usages out there on the web?

**Comment by eduardoturconi** [comment]
@dohpaz42 you can use them to prevent users navigating back to the splash screen.
I think they'll have the same effect if used in the first navigation (not allowing navigating back to splash screen).
Try adding `clearHistory: true` or `backstackVisible: false` in NavigationEntry properties.

**Comment by dohpaz42** [comment]
@eduardoturconi Thank you, that seems to be a decent work-around to the problem. For posterity, and anybody else new to nativescript having this problem, here is the code I used:

    var frameModule = require('ui/frame');

    exports.onLoaded = function(args) {
        var navigationEntry = {
            moduleName:         'views/main/main',
            clearHistory:       true,
            backstackVisible:   false
        };

        frameModule.topmost().navigate(navigationEntry);
    }

**Comment by tsonevn** [comment]
Hi @dohpaz42,
The right way to prevent user of going back to previous page, as @eduardoturconi suggested, is to use `clearHistory: true` or `backstackVisible: false`. You could also use [Activity Indicator](https://docs.nativescript.org/cookbook/ui/activity-indicator), which  could be showing while your are loading the data of your app. I regard to that you could review our `Getting Started Guide` [here](http://docs.nativescript.org/tutorial/chapter-0), which could help you to understand how NativeScript works.

Let me know whether this helps
