### ISSUE TITLE
Refactor animations in order to decouple the animation logic from the View

### ISSUE THREAD

**Issue by tzraikov** [NativeScript/NativeScript#2316]
Currently the view contains methods such as _registerAnimation, _unregisterAnimation and _unregisterAllAnimations. We want the View to be independent from animations and those methods should be removed.

**Comment by atanasovg** [comment]
@vakrilov @hshristov @PanayotCankov Guys, could you please review and update the state of this issue? Is it still valid and do we consider doing this?
