### ISSUE TITLE
Image src binding not working in tns-core-modules 2.0.1

### ISSUE THREAD

**Issue by terreb** [NativeScript/NativeScript#2320]
### Tell us about the problem
When I bind an image source to src in xml the image doesn't show up if tns-core-modules 2.0.1 are installed. When I directly put the image source to xml it works. This issue doesn't occur when using tns-core-modules 1.7.1.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.0.0
- Cross-platform modules: 2.0.1
- Runtime(s): tns-ios: 2.0.0

### Please tell us how to recreate the issue in as much detail as possible.
Please see the code below.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

main-page.xml:

```xml
<page xmlns="http://schemas.nativescript.org/tns.xsd" >
      <stack-layout loaded="onLoaded">
        <image src="{{ img }}" id="logo" tap="fun" height="100" margin="20 0 0 0" />
        <label text="{{ myText }}" margin="20" horizontalAlignment="center" textWrap="true" />
      </stack-layout>
</page>
```

main-page.js:

```javascript
var observable = require('data/observable');
var vm = new observable.Observable({ myText: 'This is the home page', img: 'https://i.imgur.com/LY3cb3A.png' });

function onLoaded(args) {
    var view = args.object;
    view.bindingContext = vm;
}
exports.onLoaded = onLoaded
```

**Comment by tsonevn** [comment]
Hi @terreb,
Thank your for reporting your problem.
I tested your code in project from scratch, however I was unable to reproduce your issue. For your convenience I am attaching screenshot from my simulator.
![screen shot 2016-06-15 at 5 58 16 pm](https://cloud.githubusercontent.com/assets/17448734/16084786/aa16e9cc-3322-11e6-965e-f26f42d37526.png)
It would help if you could give me more info how to replicate this behavior or to send us sample project.

**Comment by terreb** [comment]
@tsonevn Please try in debug mode "tns debug ios --emulator". I've just tested with run command and it does work, but doesn't when debugging.

**Comment by tsonevn** [comment]
Hi @terreb ,
 I review your problem ones again and I think this is an issue related with sending HTTP request while debugging on iOS. I also think that this issue is related to [#557](https://github.com/NativeScript/ios-runtime/issues/557).

**Comment by terreb** [comment]
Hi @tsonevn that's what I think too:) Hope you guys fix that soon.

**Comment by tsonevn** [comment]
related to [#557](https://github.com/NativeScript/ios-runtime/issues/557)
