### ISSUE TITLE
Custom swift library with custom plugin Error

### ISSUE THREAD

**Issue by nor-bu** [NativeScript/NativeScript#2325]
I want create a custom plugin for Nativescript this plugin contains a custom shared universal framework written in Swift.

When i add my test framework to a test xcode project then it works fine. But when i add this framework to my nativescript test app and i call the library i get this error:

`File:///app/tns_modules/hello/index.js:8:15: ReferenceError: Metadata for "hello.Hello" found but symbol not available at runtime.`

I don't know what is the problem, pleas help me to understand this.

Here my repos for the test products:

[iOS Framework Github Repo](https://github.com/nor-bu/ios-framework-hello-world.git)

[Test App Github Repo](https://github.com/nor-bu/ns-hello-world-custom-plugin-library.git)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/ios-runtime#581

**Comment by roblav96** [comment]
@nor-bu @NickIliev Did anyone figure out why this is happening? I too would like to write my own custom plugins in Swift.
