### ISSUE TITLE
npm installs angular2-seed-advanced@0.0.0 instead of nativescript

### ISSUE THREAD

**Issue by betfun** [NativeScript/NativeScript#2332]
Hello,

I am trying to install NativeScript with npm

D:\Devs\euro2016app>npm install -g nativescript
C:\Users\XXX\AppData\Roaming\npm
`-- angular2-seed-advanced@0.0.0

As you can see it installs "angular2-seed-advanced"

So when I try to call tns I have an error. 

```
D:\Devs\euro2016app>tns
module.js:341
    throw err;
    ^

Error: Cannot find module 'C:\Users\XXX\AppData\Roaming\npm\node_modules\nativescript\bin\nativescript.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

There is no "node_modules\nativescript" folder.

my node and npm versions are:
```
D:\Devs\euro2016app>node -v
v5.11.1

D:\Devs\euro2016app>npm -v
3.8.6

```

Do you have an idea on what the issue is?
Thanks

**Comment by tsonevn** [comment]
Hi @betfun, 

In my opinion you could try those steps.
1. To run `npm uninstall nativescript -g`, which will remove nativescript . 
2.You could verify in `C:\Users\root\AppData\Roaming\npm\node_modules` folder, that there is no `nativescript` folder. 
3.Then try to run `npm install nativescript -g`


I hope this is applicable for you.

**Comment by betfun** [comment]
I had to do:

```
npm uninstall -g  "angular2-seed-advanced"

npm cache clean
```

and

`npm install -g nativescript
`
Now it works! Thanks
