### ISSUE TITLE
tns test <platform> include coverage?

### ISSUE THREAD

**Issue by georgeedwards** [NativeScript/NativeScript#2333]
## Feature Request:

Can the `tns test <platform>` command include coverage reporting as part of it's output? [Karma-Coverage](https://github.com/karma-runner/karma-coverage) seems to be quite a nice way of doing this. To add support for Typescript, adding in [remap-istanbul](https://github.com/SitePen/remap-istanbul) looks to be the most straight forward solution.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#1865
