### ISSUE TITLE
Add new Tab to TabView after loaded

### ISSUE THREAD

**Issue by nicHoch** [NativeScript/NativeScript#2337]
### Which platform(s) does your issue occur on?
only tested on Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.0.0
- Cross-platform modules: 2.0.1
- Runtime(s): "tns-android": {
			"version": "2.0.0"
		}

### Please tell us how to recreate the issue in as much detail as possible.

I have a TabView with some (3) tabs defined in XML and this is loaded fine. If i try to add a new tab after the TabView was loaded (lets say on user demand after pressing a button) with:

```
tv.items.push({
	title: "some title",
	view: new StackLayout()
});
```

I get the following error:
```
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 3, found: 4 Pager id: ffffffff Pager class: class android.support.v4.view.ViewPager Problematic adapter: class com.tns.gen.android.support.v4.view.PagerAdapter_frnal_ts_helpers_l47_c38__PagerAdapterClassInner
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1071)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
	at android.view.View.measure(View.java:16497)
	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:229)
	at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1059)
	at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:869)
	at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:279)
	at android.view.View.measure(View.java:16497)
	...
```

Is this a bug or how can i add a new tab dynamical?

**Comment by NickIliev** [comment]
Hello @nicHoch 

There are some limitations for using tab-view and one of them is that you can't initialize tabViewItem for XML-created tab-view and add it "on the fly". You can still overwrite your current page content in order to achive that however in my opinion its better to use anther component to achive that kind of UX as tab-view should provide the users with a steady navigation behaviour.

Still there are many scenarios and maybe something like this can help you out:
_**page.xml**_ (creating a page with 3 tabViewItems in the XML)
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="onLoaded">
    <TabView row="1" id="tabViewContainer">
        <TabView.items>
            <TabViewItem title="Tab 1">
                <TabViewItem.view>
                    <Label text="This is Tab 1" />
                </TabViewItem.view>
            </TabViewItem>
            <TabViewItem title="Tab 2">
                <TabViewItem.view>
                    <Label text="This is Tab 2" />
                </TabViewItem.view>
            </TabViewItem>
            <TabViewItem title="Tab 3">
                <TabViewItem.view>
                    <Label text="This is Tab 3" />
                </TabViewItem.view>
            </TabViewItem>
        </TabView.items>
    </TabView>
</Page>
```
_**page.js**_

```
"use strict";
var tabViewModule = require("ui/tab-view");
var colorModule = require("color");
var stackLayoutModule = require("ui/layouts/stack-layout");
var textViewModule = require("ui/text-view");

var page;

function onLoaded(args) {
    page = args.object;
    addTabViewItem();
}
exports.onLoaded = onLoaded;

function addTabViewItem() {
    var stackLayout = new stackLayoutModule.StackLayout();

    var textView1 = new textViewModule.TextView();
    textView1.editable = true;
    textView1.style.fontSize = 16;
    textView1.style.backgroundColor = new colorModule.Color("BlanchedAlmond");
    textView1.height = 150;
    textView1.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin maximus purus quis metus mattis euismod. Mauris ac purus commodo, sollicitudin tellus blandit, gravida turpis.";

    stackLayout.addChild(textView1);

    var tabViewItem = new tabViewModule.TabViewItem();
    tabViewItem.title = "Tab 4",
    tabViewItem.view = stackLayout;

    var tabView = page.getViewById("tabViewContainer");
    tabView.items.push(tabViewItem);

    page.content = tabView;
}
exports.addTabViewItem = addTabViewItem;
```

In this we have three XML created tabs and we are adding the forth one dinamically with "overwriting" the page content.

**Comment by nicHoch** [comment]
Hi @NickIliev 

thanks for your detailed answer. I will test it but might i ask first if i also can "overwrite" the content of the parent of the tabView because the tabview is not the only element on page.

Nicky

**Comment by NickIliev** [comment]
@nicHoch yes you can dinamically change **page.content** as you wish.
For example : 
```
var tabView = page.getViewById("tabViewContainer");
tabView.items.push(tabViewItem);

// the parent container for all (Tab-View, Buttons, Stacks. ect.) - can be different layout as well
var dockContainer = page.getViewById("myDockContainer");
dockContainer.addChild(tabView);
dockContainer.addChild(someOtherView);
dockContainer.addChild(anotherView);

page.content = dockContainer ;
```
You can also entirely create your page with code-behind - for similar example you can refer to this tab-view exmaple in our repository: [https://github.com/NativeScript/NativeScript/blob/master/apps/tab-view-demo/mainPage.ts](https://github.com/NativeScript/NativeScript/blob/master/apps/tab-view-demo/mainPage.ts)

**Comment by nicHoch** [comment]
@NickIliev 
thanks again. But still not sure if i got you right:
There are more than on element on the page and one is the TabView. In order to add the new tab with the override approach do i have to rebuild the entire page dynamically or could i update the content only of the parent of the TabView:

something like: 

```
var tabViewItem = new tabViewModule.TabViewItem();
tabViewItem.title = "Tab 4",
tabViewItem.view = stackLayout;

var tabView = page.getViewById("tabViewContainer");
tabView.items.push(tabViewItem);
    
//here not page but only parent
tabView.parent.content = tabView

```

**Comment by nicHoch** [comment]
Hi i tested a bit and the approach 

```
//here not page but only parent
tabView.parent.content = tabView
```

is not working. But it can be done with:

```
var tabView = page.getViewById("tabViewContainer");
var tabViewItem = new TabViewItem();
tabViewItem.title = "some";
tabViewItem.view = some_layout;

var oldParent : Layout = <Layout> tabView .parent;
oldParent.removeChild(tv);
tabView.items.push(tabViewItem);
oldParent.addChild(tabView );
```

I guess the performance of this workaround is not very good but at least I can add a new tab und update the page only partially.

**Comment by NickIliev** [comment]
@nicHoch you are absolutely right - you can use this approach however keep in mind that you should know what your tabView parent is as compoennt. The reason is as **_page_** component do have **_content_** property the same is not valid for most layouts.
For example StackLayout has addChild() method which accepts a view as arguments and has removeChildren() to reset all childrens of the layout.(the same applies for the other layouts)

Here is a demo that uses your technique to add a 4th tab via button and a StackLayout:
```
function addTabViewItem() {
    var stackLayout = new stackLayoutModule.StackLayout();
    var textView1 = new textViewModule.TextView();
    textView1.editable = true;
    textView1.style.fontSize = 16;
    textView1.style.backgroundColor = new colorModule.Color("BlanchedAlmond");
    textView1.height = 150;
    textView1.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin maximus purus quis metus mattis euismod. Mauris ac purus commodo, sollicitudin tellus blandit, gravida turpis.";
    stackLayout.addChild(textView1);
    var tabViewItem = new tabViewModule.TabViewItem();
    tabViewItem.title = "Tab 4",
        tabViewItem.view = stackLayout;
    var tabView = page.getViewById("tabViewContainer");
    tabView.items.push(tabViewItem);
    
    // via getViewById
    // var stack = page.getViewById("container");
    // stack.removeChildren();
    // stack.addChild(tabView);

    // or with parent
    var myStack = tabView.parent;
    myStack.removeChildren();
    myStack.addChild(tabView);
}
exports.addTabViewItem = addTabViewItem;
```

page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="onLoaded">
    <StackLayout id="container">
        <Button text="" tap="addTabViewItem" />
        <TabView id="tabViewContainer">
            <TabView.items>
                <TabViewItem title="Tab 1">
                    <TabViewItem.view>
                        <Label text="This is Tab 1" />
                    </TabViewItem.view>
                </TabViewItem>
                <TabViewItem title="Tab 2" visibility="{{ isItemVisible ? 'visible' : 'collapsed' }}">
                    <TabViewItem.view>
                        <Label text="This is Tab 2" />
                    </TabViewItem.view>
                </TabViewItem>
                <TabViewItem title="Tab 3">
                    <TabViewItem.view>
                        <Label text="This is Tab 3" />
                    </TabViewItem.view>
                </TabViewItem>
            </TabView.items>
        </TabView>
    </StackLayout>
</Page>
```

**Comment by amirhoseindgr** [comment]
How can i add image in this listView? 
here is my code


function onLoaded(args) {
    page = args.object;
    const appSettings = require("application-settings");
    appSettings.setString("InPage" , "Category");
    for(var loop=0 ; loop < listViewArray.length ; loop++)
    addTabViewItem(listViewArray._array[loop]);
}
exports.onLoaded = onLoaded;

function addTabViewItem(itemsContent) {
    var stackLayout = new stackLayoutModule.StackLayout();
    var tabView = page.getViewById("tabViewContainer");
    var tabViewItem = new tabViewModule.TabViewItem();
    console.dir(itemsContent);
    tabViewItem.title = itemsContent.type
    
    
    tabView.items.push(tabViewItem);
    tabViewItem.view = stackLayout;
    page.content = tabView;
    const listView = new listViewModule.ListView();
    listView.height = "100%";
    listView.className = "list-group";
    listView.items = listViewArray;
    listView.on(listViewModule.ListView.itemLoadingEvent, (args) => {
        if (!args.view) {
            args.view = new labelModule.Label();
            args.view.style.fontSize = 16;
            args.view.height = 150;
            args.view.className = "list-group-item pull-right";
            args.view.margin = "7";
        }
        (args.view).text = listViewArray.getItem(args.index).type;

    });
    stackLayout.addChild(listView);
}
exports.addTabViewItem = addTabViewItem;
