### ISSUE TITLE
TNS doctor redirects OSX user to download JRE instead of JDK

### ISSUE THREAD

**Issue by rbreaves** [NativeScript/NativeScript#2338]
### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS
### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
2.0.1
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
N/A
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
N/A
- Plugin(s): (look for the version number in the `package.json` file of your
project)
N/A

### Please tell us how to recreate the issue in as much detail as possible.
Install nativescript on OSX 10.11 and run tns doctor without java installed and then follow the More Info link when the download java prompt appears. Can you not have the prompt prompt for the JDK instead?

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
No.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#1863
