### ISSUE TITLE
DatePicker and TimePicker property bindings do not work in Android 5.x

### ISSUE THREAD

**Issue by hamorphis** [NativeScript/NativeScript#234]
DatePicker and TimePicker property bindings do not work in Android 5.x

**Comment by vakrilov** [comment]
DatePicker and TimePicker can configured to show in "spinner" mode by default trough theme. Add the following XML in the `App_Resources\Android\values-v21/styles.xml` file:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <style name="AppTheme" parent="android:Theme.Material.Light">
    <item name="android:datePickerStyle">@style/SpinnerDatePicker</item>
    <item name="android:timePickerStyle">@style/SpinnerTimePicker</item>
  </style>

  <style name="SpinnerDatePicker" parent="android:Widget.Material.Light.DatePicker">
    <item name="android:datePickerMode">spinner</item>
  </style>

  <style name="SpinnerTimePicker" parent="android:Widget.Material.Light.TimePicker">
    <item name="android:timePickerMode">spinner</item>
  </style>
</resources>
```

This should be added in the default template used when creating app with the NativeScript CLI.

**Comment by vakrilov** [comment]
Theme changed in default project template for android with [this commit](https://github.com/NativeScript/android-runtime/commit/5cdd431b5d5e941b6a19adc4ee7329fe27596c4b).
