### ISSUE TITLE
Typo on documentation of Telerik UI

### ISSUE THREAD

**Issue by vjoao** [NativeScript/NativeScript#2345]
## Please, provide the details below:

On http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/SideDrawer/callbacks there is a typo on

```
drawerOpening
drawerClosed
drawerClosing
drawerClosed
```

the second `drawerClosed` should be `drawerOpened`.

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-samples#97
