### ISSUE TITLE
Camera module: toBase64String(...) returns null

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/NativeScript#2353]
Hello,

I am testing on an iOS device and I am trying to convert the picture taken into a Base 64 string so I can submit it to the server for processing.  However the toBase64String() is returning null.  Here is my code:

```
cameraModule.takePicture().then(function (img) {
        try {
            var imageData = img.toBase64String('image/png');
            //  imageData is null //
           ...
        } catch (e) {
            alert(e);
        }         
    });
```

This code seems to work fine on Android.  

Am I doing anything wrong here?

Thank you.

**Comment by Daxito** [comment]
@dpdragnev 
I think is should be img.toBase64String(enums.ImageFormat.png, 100);

I am doing something similar and that works.

**Comment by NickIliev** [comment]
Hi @dpdragnev 

As @Daxito pointed out one way is to use the NativeScript enumerations module.
```
var enums = require("ui/enums");

img.toBase64String(enums.ImageFormat.png);
```

or to use directly the format with
```
img.toBase64String("png");
```

**Comment by dpdragnev** [comment]
Thank you @Daxito and @NickIliev.  I am testing it now.

**Comment by dpdragnev** [comment]
For some reason, I could not make it work with img.toBase64String("png"); but img.toBase64String("jpeg"); worked.

Thanks for the help.

**Comment by NickIliev** [comment]
@dpdragnev The Android camera is taking pictures in **jpeg** format by default so this is the expected format to convert. (however Screenshots for most Android deveices are in **png**)
