### ISSUE TITLE
Switch widget on Android 4.x not styled correctly

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/NativeScript#2358]
The `color` property is not correctly applied to `android.widget.Switch` on Android **4.x** (`background-color` is applied fine). To reproduce, you can look at [what we have discussed](https://github.com/rdlauer/nativescript-ionic/issues/1) on this separate issue and [clone the sample app](https://github.com/rdlauer/nativescript-ionic/) provided.

This is an issue with Android 4.x only, using {N} v2.0

**Comment by tsonevn** [comment]
In my opinion `switch module` `color` property works normally with NativeScript 2.0.1. In regard to that I am attaching my sample code. In addition I have tested my sample app in Android 4.4.4 API19.

**main-page.xml**

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd">
  <StackLayout>
  <scroll-view>
    <stack-layout>
        <stack-layout >
            <Switch checked="true" class="styleSwitch" />
            <Switch checked="true" class="styleSwitch2" />
            <Switch checked="true" class="styleSwitch3" />
        </stack-layout >
    </stack-layout>
   </scroll-view> 
  </StackLayout>
</Page>
```

**app.css**

```

.styleSwitch{
    color:red;
    background-color: green;
}

.styleSwitch2{
    color:blue;
    background-color: green;
}

.styleSwitch3{
    color:yellow;
}
```


![screenshot 11](https://cloud.githubusercontent.com/assets/17448734/16297501/c37e1760-3939-11e6-96dc-95a9a4ed981f.png)

**Comment by NordlingArt** [comment]
@tsonevn - The Switch module is acting a little strange on iOS (TNS 2.0.1). The shadow of the thumb is not there, so the off state makes the whole Switch practically invisible:

![image](https://cloud.githubusercontent.com/assets/2098838/16299894/0e75c6ca-393d-11e6-978f-e73cc358a5eb.png)


```
Switch {
  color: #ffffff;
  background-color: #3fbabf;
}
```

**Comment by tsonevn** [comment]
Hi @NordlingArt, 

I tested this scenario in a sample **Xcode** project and I think that this behavior is normal for **iOS** **Switch**, when you set `color` property  to  white.

**Comment by NordlingArt** [comment]
@tsonevn Okay, well the problem I'm having is that Switch color property is inherited from its ancestors. Say I set color on Page in the CSS, and nothing to Switch:

```
Page {
  color: #808080;
}
```

![image](https://cloud.githubusercontent.com/assets/2098838/16311184/cfeab306-396f-11e6-9f70-19d0cf2c93e1.png)

That's the outcome. Then how do I prevent the Switch to inherit a color property?

**Comment by tsonevn** [comment]
Hi @NordlingArt 
I reviewed this scenario, however I was unable to find a way to prevent Switch from the global styling. However as solution you could set `Switch` color property to something like `#F2F4F5` which is closer to white color and the switch can be seen when it is disable.


```
Switch {
  color:#F2F4F5;  
}


I hope this is applicable for you.
```
