### ISSUE TITLE
Question; Setting WebView cookies 

### ISSUE THREAD

**Issue by devna13** [NativeScript/NativeScript#2359]
Is it feasible to set WebView cookies in IOS/Android ?

**Comment by NickIliev** [comment]
Hello @devna13 

The way to use cookies is to implement the native API as there is no NativeScript implementation for using cookies.Nice example of setting cookies for Android with **_[CookieSyncManager](https://developer.android.com/reference/android/webkit/CookieSyncManager.html)_** is shown
in [issue #265](https://github.com/NativeScript/NativeScript/issues/265) (the post from 8th March from AntonioCuevaUrraco )

**Comment by devna13** [comment]
Thanks @NickIliev.
