### ISSUE TITLE
List of plugins

### ISSUE THREAD

**Issue by alejonext** [NativeScript/NativeScript#236]
Well, I think the best is to make a list of plugins. Since being built several, they are quite interesting. Here is my contribution

* [Admob](https://github.com/alejonext/NativeAdmob) - Admob for NativeScript
* [NativeLang](https://github.com/alejonext/NativeLang) - NativeScript for Internationalization
* [NativeNumber](https://github.com/alejonext/NativeNumber) - Java impletation

What have they done?

**Comment by RangerMauve** [comment]
I think it might be useful to have this in a Wiki page in the project so that people could easily contribute to the list.

**Comment by Nathanaela** [comment]
Agreed --- I have several of them in various stages of completion.

**Comment by alejonext** [comment]
@Nathanaela Publish it, to go by listing :D

**Comment by Nathanaela** [comment]
Actually I have published a couple of my repos already -- was busy today finishing up the IOS support for my SQLite library so I haven't had time to write up the docs and get the rest up yet.  But they should be up in the next day or so.

* [SQLite](https://github.com/Nathanaela/nativescript-sqlite) - SQLite support
* [Updater](https://github.com/Nathanaela/nativescript-updater) - Remote/Local update for apps.
* [Tracing](https://github.com/Nathanaela/nativescript-tracing) - Simple library for tracing all/some calls in classes (useful when class uses lots of callbacks).
* [compress](https://github.com/Nathanaela/nativescript-compress) - Simple de/compression library

Not a plugin per say; but NativeScript related: 
* [VM](https://github.com/Nathanaela/nativescript-vm) - A virtual Machine and/or vagrant script to install everything needed to develop and hack on NativeScript & NS apps.

**Comment by valentinstoychev** [comment]
Hey all - this is a wonderful, GREAT initiative! Let me shed some more light on what we are planning in this regard.

Please check - [http://plugins.telerik.com/](http://plugins.telerik.com/). There is currently a list of PhoneGap plugins, but as you can see we are starting to collect {N} plugins as well. We will open this plugins site once we have a plugins support. See #25. This site will be open for everyone. There will be a review process, just to make sure that the plugins are well documented and in a good shape.

This is how we plan to keep all the plugins in a good shape and in one centralized place.

**Comment by alejonext** [comment]
@valentinstoychev  Excellent! Sure, it's understandable that many think plugins are experimental.

**Comment by Nathanaela** [comment]
I just started a NativeScript community on Google+ https://plus.google.com/u/0/communities/117408587889337015711   -- I have a plugin Category if we want to start getting things put somewhere.    Otherwise I'm willing to start a repository where we can just fork and modify the repo and change the readme.md file...

**Comment by Nathanaela** [comment]
Here you go -- I dropped it into a repo; please fork to make any changes... https://github.com/Nathanaela/nativescript-plugins

**Comment by valentinstoychev** [comment]
This is great @Nathanaela - we are lucky to have you as part of {N}!

**Comment by PanayotCankov** [comment]
Since all nativescript plugins are supposed to be distributed through NPM and prefixed with "nativescript-" is such manually maintained list still necessary?

**Comment by enchev** [comment]
Yep, I'm closing this.
