### ISSUE TITLE
VSCode debugging for typescript

### ISSUE THREAD

**Issue by ryc16** [NativeScript/NativeScript#2360]
Need an advice for better debugging experience on VS Code. Here is my debugging experience.

1/ Currently, after a change made, I have to do "restart" debugging. Is there any way not to do "restart" after a change? Is there a livesync watch on debuging? If so, how to set it?
2/ I have never been able to do "attach to the device" even my emulator is running. So I have to do launch on device. I always got error "Connection timeout" from VSCode console. Any idea?

So it is not fun to debug as above both experience take long time. Any 

```
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.0.1           │ 2.0.1          │ Up to date    │
│ tns-core-modules │ 2.0.1           │ 2.0.1          │ Up to date    │
│ tns-android      │ 2.0.0           │ 2.0.0          │ Up to date    │

```

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-vscode-extension#51
