### ISSUE TITLE
Can't output size be decrease?

### ISSUE THREAD

**Issue by jjTudu** [NativeScript/NativeScript#2368]
If any config option can be provided in package.json, which can ignore few modules to load or build, like the functionality present in Grunt.
ignore{
['file.xx','file2.zz']
}
because like my stock/news app will never use the camera modules.

**Comment by triniwiz** [comment]
@jjTudu  you can check this out https://www.nativescript.org/blog/nativescript-android-application-package-size-revealed

**Comment by NickIliev** [comment]
Hi @jjTudu 

This topic is discussed at [#450](https://github.com/NativeScript/NativeScript/issues/450) and you can also find some useful suggestions for manual workflows to reduce your app size. I am closing this as duplicate but please feel free to join the discussion on that matter and track its development.

Additional information related to the issue you can find at [#1392](https://github.com/NativeScript/nativescript-cli/issues/1392)
