### ISSUE TITLE
Android: css style for elements inside a collapsed container 

### ISSUE THREAD

**Issue by devna13** [NativeScript/NativeScript#2375]
I have a textfields inside a StackLayout that is initially is collapsed and it becomes visible after few milliseconds, similar to [line 157](https://github.com/NativeScript/sample-Groceries/blob/08a145c43e698eb197e40d065d3a0ea261bd80cd/app/pages/login/login.component.ts)

and I have this global css style for text-fields 

TextField {
    border-width: 0.5;
    border-color: gray;
    border-radius: 4;
}

When I run in **android emulator** I get this error; -no error in IOS emulator-

JS: Style: Error setting property: borderRadius on TextField(145): TypeError: Cannot read property 'isEmpty' of undefined
JS: Style: Error setting property: borderRadius on TextField(145): TypeError: Cannot read property 'isEmpty' of undefined
JS: Style: Error setting property: borderRadius on TextField(147): TypeError: Cannot read property 'isEmpty' of undefined
JS: Style: Error setting property: borderRadius on TextField(147): TypeError: Cannot read property 'isEmpty' of undefined

and if I comment out the TextField CSS rule error goes away. 

Looks like a bug to me

**Comment by tsonevn** [comment]
Hi @devna13, 
I have tested the given scenario on a sample application and on our [sample-Groceries](https://github.com/NativeScript/sample-Groceries), however I was unable to reproduce you issue. I am attaching my sample code 

`app.css`
```
TextField {
border-width: 0.5;
border-color: gray;
border-radius: 4;
}
```
`app.component.ts`
```
import {Component} from "@angular/core";

@Component({
    selector: "my-app",
    template: `
<StackLayout>
    <TextField text="sample textfield"></TextField>

    <Label text="Tap the button" class="title"></Label>
    
    <Button text="TAP" (tap)="onTap()"></Button>

    <Label [text]="message" class="message" textWrap="true"></Label> </StackLayout> `,
})
export class AppComponent {
    public counter: number = 16;

    public get message(): string {
        if (this.counter > 0) {
            return this.counter + " taps left";
        } else {
            return "Hoorraaay! \nYou are ready to start building!";
        }
    }
    
    public onTap() {
        this.counter--;
    }
}

```

In regards to that I will appreciate if you provide sample application, which can be debugged locally. This will help me to provide better solution of your issue.

**Comment by devna13** [comment]
Hi @tsonevn,

I created a branch for you, and I got the error after adding styles to  the app.css:

clone: https://github.com/devna13/sample-Groceries.git
checkout ns-ng-android-2375 branch:

take a look at [app.css](https://github.com/devna13/sample-Groceries/blob/ns-ng-android-2375/app/app.css)

**Comment by tsonevn** [comment]
Hi @devna13,
Thank you for your answer.
I followed above described steps and tested your project on different  `android emulator` (API 18, API 21 and API23), actually I was unable to reproduce your problem again. This issue might be caused by an old NativeScript version, you could upgrade to latest official release following below described steps.

1.` npm uninstall -g nativescript`
2. `npm install -g nativescript` 
3. go in your project folder
4. delete the folders `platforms`, `node_modules`, `hooks`
5. run `tns run android`

Those steps are described also [here](https://docs.nativescript.org/releases/upgrade-instructions).

Let me know whether this helps or if I can assist you further.

**Comment by tsonevn** [comment]
Hi @devna13,

Do you still have problem with the styling?

Regards,
@tsonevn

**Comment by devna13** [comment]
not happening anymore, thanks @tsonevn
