### ISSUE TITLE
[Android] Issues with different API versions

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#2381]
My android app is having different issues on different API versions. 

**API 17**
App runs, but does not show the bottom layout of the view at all. Very weird. 
https://dl.dropboxusercontent.com/u/33168380/weather_API_17.png

**API 18-19**
App runs just fine, all views show and animations work. This is how the app is supposed to look.
https://dl.dropboxusercontent.com/u/33168380/weather_API_18-19.png

**API 21-22-23**
App runs, shows the bottom layout correctly on the first run. But when navigating to another view (settings) and back again to the main, a black box appears at the bottom. 
If I disable the page navigation animation, the black box is gone and the app works at it should. 
https://dl.dropboxusercontent.com/u/33168380/weather_API_21-22-23.png

Again, the iOS version works super smooth. 

I am working on getting the code deployed to github so you can test it. 

CLI: 2.0.1
Runtime: 2.0.0
Core modules: 2.0.1

**Comment by tsonevn** [comment]
Hi @manijak, 

Thank you for reporting those issues, however we will appreciate if you soon provide sample application, which can be debugged locally and help us to verify reported problems This will help us to provide better solution of your issue. 

Regard, 
@tsonevn

**Comment by tsonevn** [comment]
Hi @manijak,

Thank you for the project.
I was able to reproduce some of the above-described issues with `tns-core-modules` 2.0.1. However today I tested your project with new modules - 2.1 and it seems that now the application works on different API Levels without any problem. Could you try to run your app with the new modules, following the steps below?

1.  `tns plugin remove tns-core-modules`
2.  `tns platform remove android`
3.  `tns plugin add tns-core-modules@2.1.0`
4.  `tns run android`

The result:

`API 17`, `API 18-19`, `API 21-23`
![screenshot 13](https://cloud.githubusercontent.com/assets/17448734/16484940/cdfcfed2-3ec4-11e6-9a73-303a1201a284.png)
Let me know whether this helps or if I can assist you further.

**Comment by manijak** [comment]
Thanks @tsonevn,
I updated to 2.1.0 just now, removed and re-added both core-modules and the android platform. But now my app is stuck at the splash screen and never shows the main-view. no errors in the console. 

I tried all APIs and the result is the same.

**Comment by manijak** [comment]
Confirmed, after update the issues are gone! Thanks :)
