### ISSUE TITLE
entry.callback is not a function

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/NativeScript#2385]
Hello,

I recently started getting a strange error:  **entry.callback is not a function**.  The error is on line 155 in observable.js

The error appears randomly as I navigate through pages.  I have not been able to spot any pattern.  

Has anyone seen this error?

Thank you.

**Comment by tsonevn** [comment]
Hi @dpdragnev,

Thank you for reporting your problem,

I was unable to reproduce such a problem and In regards to that I  will appreciate if you could give me some more info about the issue, or to provide sample application, where the problem has been reproduced. This will help would help me to verify your problem

**Comment by dpdragnev** [comment]
Thank you @tsonevn.  I will try to isolate the problem and will post the actual code.  The problem is that I am also having trouble reproducing it consistently.  I suspect that it has something to do with an ajax calls I am making while navigating between pages.

**Comment by dpdragnev** [comment]
Bellow is the error message I get.  If you look at #3, it points to line 31 in onNavigatingTo.  The line in question is:

`model.set('customer', new Observable(JSON.parse(appSettings.getString('user'))));`

The error usually happens after I have updated the model.customer object and reinsert it in the appSettings from a different view.

I am setting the string as:

`appSettings.setString('user', JSON.stringify(c));`

What can be the problem here?  Do you see anything that I am doing wrong?

![errornav](https://cloud.githubusercontent.com/assets/11344576/16494598/bf39996c-3e9e-11e6-9d8e-a280d7ab5497.PNG)

**Comment by dpdragnev** [comment]
Ok, I got it to work.  Here is what the problem was:

On the first screen, I was creating an observable from the Json object saved in appSettings:

`model.set('customer', new Observable(JSON.parse(appSettings.getString('user'))));`

then I was making some changes and saving it back to the appSettings:

`appSettings.setString('user', JSON.stringify(c));`

The problem was that when the object was first converted into an observable, it added some additional properties to itself.  When I saved it back to the appSettings those properties went along as well.  When I visited the first View again where I get the object from appSettings and try to convert it to an observable, I would get the above error. 

To remedy this,  I created a custom replacer function that excluded all additional properties and use it when saving the object back to the appSettings:

`appSettings.setString('user', JSON.stringify(c, replacer));`

This kept the object clean and I did not run into this error again.  My concern is that if the Nativescript team changes the name of those internal properties, my code will fail and I will start seeing the error again.

Is there a better way to handle this?

Thank you.

**Comment by tsonevn** [comment]
Hi @dpdragnev, 

Using `appSettings.setString('user', JSON.stringify(c, replacer));` is possible solution in case you want to pass data between different pages. However you could use `context ` property while you are navigating to different page, to pass data. You could found example, how to do this in this [article](https://docs.nativescript.org/core-concepts/navigation#example-4--how-to-pass-content-between-different-pages).  In addition you could use global variable like the example [here](http://stackoverflow.com/questions/31502225/adding-a-global-variable-function-in-javascript-specifically-nativescript). 

I hope this is applicable for you.

**Comment by dpdragnev** [comment]
@tsonevn Thank you Nikolay.  Great suggestions.  I like the global variable approach.

Appreciate your help.
