### ISSUE TITLE
Create help application

### ISSUE THREAD

**Issue by hshristov** [NativeScript/NativeScript#2387]
Create sample application that should produce single markdown help page. The app should have subfolders with different pages for all our UI components. Something like:

**ActionBar (folder)**
- readme.md
- page.xml
- page.ts
- page.css

**GridLayout (folder)**
 - readme.md
 - page1.xml
 - page2.xml

On build generate one markdown by reading all inner **readme.md** files and insert all snippets defined in the pages. For example in the GridLayout/readme.md we may want to show several examples of different GridLayout configurations. Those snippets should be defined in page1.xml, page2.xml, etc.
The generated markdown should have sections so that hyperlinks can be create for every folder.

**Comment by PanayotCankov** [comment]
We have something similar for the `tests` already in place. You can take a look at the `Gruntfile.js` in the `articles` tasks how we exec:
```
node node_modules/markdown-snippet-injector/index.js --root=<%= localCfg.srcAppsTestsDir %> --docsroot=<%= localCfg.outArticlesDir %>
```
The tool extracts snippets and inject them in .md files (that's why they are first copied to the bin/dist).

**Comment by hamorphis** [comment]
https://github.com/NativeScript/NativeScript/pull/2401

**Comment by hamorphis** [comment]
[NativeScript SDK Examples](https://github.com/NativeScript/nativescript-sdk-examples)
