### ISSUE TITLE
CLI Livesync improvements

### ISSUE THREAD

**Issue by hshristov** [NativeScript/NativeScript#2388]
Tasks:
- [x] Enable debugging support - with `--watch`
- [ ] Improve the speed so that `livesync` happens in less than a second
- [ ] Profile & remove unnecessary steps in `livesync` command
- [ ] Rebuild project when needed - like AndroidManifest.xml is changed, Info.plist is changed, Image is added to XCAssets or android res folder or at least console log a message
- [x] Show unhandled error on device/simulator
- [x] `tns livesync` without `ios/android` should deploy on all devices/simulators/emulators

**Comment by atanasovg** [comment]
@rosen-vladimirov @hshristov @PanayotCankov @Plamen5kov Guys, could you please review this issue and update its state? I suggest that we close this issue and open new, more granular issues if needed.

**Comment by PanayotCankov** [comment]
I think these were implemented. If there are further problems lets log them in separate issues.

**Comment by rosen-vladimirov** [comment]
I confirm everything described in the issue is implemented in CLI.
