### ISSUE TITLE
Formatting Text Field

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/NativeScript#2393]
Hello,

Here is my scenario:  I have a form where the user enters their phone number.  The text field is bound to a view model and in some cases the phone is pre-populated.  This is a perfect scenario for a masked text field.  Unfortunately, the only module available ( https://github.com/bthurlow/nativescript-maskedinput ) does not support databinding (see http://stackoverflow.com/questions/38017201/nativescript-maskedinput-databinding and http://stackoverflow.com/questions/38081831/nativescript-observable-propertychangeevent?lq=1)

I tried handling  the propertyChange event, but this did not work either. (see http://stackoverflow.com/questions/38081831/nativescript-observable-propertychangeevent?lq=1)

The TextField does not have any key events that I can capture (at least I could not find any) so I can format it manually.

So, what are my options?  Do I have to write my own module handling the native iOS and Android controls to achieve this?  This is a pretty common scenario and I am very surprised that there is nothing available that helps in this case.  

Any suggestions are greatly appreciated.

Thank you.

**Comment by tsonevn** [comment]
Hi @dpdragnev,
Thank you for reporting this issue.
I review `nativescript-maskedinput` plugin and found that data binding and `propertyChangeEvent` works as expected for iOS. However  to make it work for Android you should set property change event to the MaskedInput. You could review the example below. 

**main-page.xml**
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:mi="nativescript-maskedinput" navigatingTo="navigatingTo">
  <StackLayout>
    <Label text="Tap the button" class="title"/>
    <mi:MaskedInput id="maskId" mask="1-999-999-9999? x999" hint="1-555-555-5555" textChange="onChange" placeholder="#"/>    
    <Button text="tapToView" tap="onTap" />
  </StackLayout>
</Page>
```
**main-page.js**
```
var observable_1 = require("data/observable"); var text_base_1 = require("ui/text-base"); 

var msTF;
var newObservable = new observable_1.Observable(); function navigatingTo(args) {
    var page = args.object;
    msTF = page.getViewById("maskId");

    msTF.on(text_base_1.TextBase.propertyChangeEvent, function (args) {
        console.log("data change");
        console.log(msTF.text);
    });
    page.bindingContext = newObservable; } 
exports.navigatingTo = navigatingTo;
```

In regard to your question you could specify the keyboardType for the `TextField`. you could review [this ](https://docs.nativescript.org/ui/keyboard) article.

I hope this helps

**Comment by dpdragnev** [comment]
@tsonevn: so in your experience, on iOS databinding with the masked input works as expected?  I could not get this to work.  I will start a new, clean solution and will test your suggestion there.

**Comment by dpdragnev** [comment]
So,  here is my sample project ( deriving from the Blank Javascript solution in Visual Studio ).  As you can see, I have a very simple view model and I am trying to bind the masked input to the phone property.  When I start the app, the masked input is empty.

In your message you say that databinding is working on iOS.  Am I doing anything wrong here?  It does not work for me.

**homeView.xml**
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:widgets="utils/widgets" xmlns:mi="nativescript-maskedinput" loaded="pageLoaded">
    <Page.actionBar>
        <widgets:action-bar />
    </Page.actionBar>

    <StackLayout>
      <mi:MaskedInput id="maskId" mask="999-999-9999" hint="555-555-5555" textChange="onChange" text="{{ phone }}" placeholder="#" />
    </StackLayout>
</Page>
```

**homeView.js**
```
'use strict';
var isInit = true,
    helpers = require('../../utils/widgets/helper'),
    navigationProperty = require('../../utils/widgets/navigation-property'),
    // additional requires
    viewModel = require('./homeView-view-model');
var Observable = require("data/observable").Observable;
var page;

// additional functions
function pageLoaded(args) {
    page = args.object;

    helpers.platformInit(page);
    page.bindingContext = viewModel;
    // additional pageLoaded

    if (isInit) {
        isInit = false;

        // additional pageInit
    }
}
function onChange(e) {
    
}
exports.pageLoaded = pageLoaded;
exports.onChange = onChange;
```


**view model**
```
'use strict';
var ViewModel,
    Observable = require('data/observable').Observable;
// additional requires

ViewModel = new Observable({

    pageTitle: 'Home View',
    // additional properties
    phone: '7023216548'
});

module.exports = ViewModel;```

**Comment by tsonevn** [comment]
Hi @dpdragnev,

To let DataBinding works for iOS, you should add **EventListener** to your **viewModel**, which will help you to handle property change event. In Addition you should also set to the binded `MaskedInput` `text` property empty string. I made some changes in your sample code, which you could review in the below attached code snippets.

**main-page.xml**
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:mi="nativescript-maskedinput" loaded="pageLoaded">

    <StackLayout>
      <mi:MaskedInput id="maskId" mask="999-999-9999" hint="702-321-6548" text="{{ phone }}" placeholder="#" />
    </StackLayout>
</Page>
```

**main-page.js**
```
var viewModel = require('./main-view-model’);

var ObservableModule = require("data/observable").Observable;

var page;

// additional functions
function pageLoaded(args) {
    page = args.object;

    viewModel.addEventListener(ObservableModule.propertyChangeEvent, function (pcd) {
        console.log(pcd.eventName.toString() + " " + pcd.propertyName.toString() + " " + pcd.value.toString());
    });

    page.bindingContext = viewModel;
    // additional pageLoaded

}

exports.pageLoaded = pageLoaded;
```

**main-view-model.js**
```
var ViewModel,
    Observable = require('data/observable').Observable;
// additional requires

ViewModel = new Observable({

    pageTitle: 'Home View',
    // additional properties
    phone: ''
});

module.exports = ViewModel;
```

Regards,
@tsonevn

**Comment by dpdragnev** [comment]
Thank you @tsonevn,  This works fine, but what about the case where the phone already has a value?  For example, when I am loading the page, I am pre-populating some of the fields with customer's existing information.  In this case the viewModel.phone will contain a value and the problem is that this value is not displayed in the masked input control.

Thank you.

**Comment by tsonevn** [comment]
Hi @dpdragnev, 

I have tested several options for above given scenario, however I was unable to find a temporary solution for  bind text property of MaskInput view and to set  existing value. In regard to that I found that you have been logged an [issue ](https://github.com/bthurlow/nativescript-maskedinput/issues/3) in the rope of this plugin. Possible solution you could be to use  TextField and its [keyboard ](https://docs.nativescript.org/ui/keyboard) type property.

I hope this helps.

**Comment by dpdragnev** [comment]
Thank you @tsonevn for your help.  While waiting for the module to be updated I am loading the value manually during the onLoaded event.  This is not exactly databinding since I have to get the textfield by id, but it does the job for now.

Thank you for you time and advise.

**Comment by lakshaya22** [comment]
Hello @dpdragnev @tsonevn , I want to use masked input library with angular 2 variant of the native script, I have added the masked input to my html and its working, the issue that is coming is tht i am not able to get the text that I have typed from the masked input in my typescript. Ngmodel is not working with it neither I am able to fetch the result by the id field.

**Comment by tsonevn** [comment]
Hi @lakshaya22,
You could try, for example, to handle `propertyChnaged` event for the `MaskedInput` on the component loaded event.
```
maskedinputloaded(args){
        var textinput = args.object;
        textinput.on("propertyChange", (args)=>{
            console.log(args.object.text)
        })
    }
```
Regard to that I found that this plugin has not been supported for [NativeScript Angular 2](https://github.com/bthurlow/nativescript-maskedinput/issues/2). In case you have issues with the plugin, please logged them in its GitHub [repository](https://github.com/bthurlow/nativescript-maskedinput/issues).

**Comment by lakshaya22** [comment]
Hello @tsonevn, can you please provide me the html and typescript code in detail, because this property change event I have tried and its not working. Thanks.

**Comment by dlucidone** [comment]
I managed to get it working with angular 2 check here - https://github.com/dlucidone/nativescript-maskedinput-example
