### ISSUE TITLE
Question: How can I use the code encryption?

### ISSUE THREAD

**Issue by gaurav-chandra** [NativeScript/NativeScript#2395]
As stated on the roadmap, 2.1 will have code encryption and security. I could not find any documentation as to how to enable it. Is it enabled by default or some config is required?

[https://www.nativescript.org/roadmap](Roadmap)

**Comment by NathanaelA** [comment]
Telerik has a plugin that they are working on, the last time I looked at it was fairly trivial to bypass on both platforms (and imho more security theater then useful).  I'm not sure when this plugin will be released as they just released the main 2.1 stuff today; so they are probably still cleaning up things and they need to verify it still works with the changes in 2.1.   But when it is released you will just simply install the plugin and the plugin will do the encryption on all release builds.    It will stop someone who has no knowledge of how to hack an app.

Disclaimer: I also have a app encryption service (http://appprotection.net) about to be launched (finishing the web service scripts hopefully this week)...  So I'm sure their is some bias in my viewpoint about the level of encryption. :grinning:   However, in all honesty I have broken all of them listed on my main appprotection.net page, the ratings of the security provided I gave them are accurate in my opinion for someone with a junior to medium level cracking ability.

**Comment by gaurav-chandra** [comment]
Awesome, looking forward to your service.

**Comment by tsonevn** [comment]
HI @gaurav-chandra,
Thank you for your interest in NativeScript.
Those encryption and security functionality would be provided from external plugin, which is still under development. You could follow our community channels: [slack](http://developer.telerik.com/wp-login.php?action=slack-invitation),[newsletter](https://www.nativescript.org/nativescript-newsletter) to find, when this plugin will be available.

**Comment by NickIliev** [comment]
Hey @gaurav-chandra it's been a while and I will close this issue as i saw you have some applicable solutions provided by our community members  - let us know if you need further assistance or information on that or other matter.
