### ISSUE TITLE
[iOS] AppStore deploy issue after update to 2.1.0

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#2397]
I am trying to publish a new version of my app to the AppStore. 
After upgrading to 2.1.0, I removed and re-added the ios-platform folder. Bumped the versions in my Info.plist file and done a full build. 

Opening XCode I can see the new versions applied. Archive validation is OK. But Archive upload is failing with the following error:

![XCode error](https://dl.dropboxusercontent.com/u/33168380/ios_archive.png)

**The keys are not missing in my Info.plist file, they are both there.** 

I have never seen this error before, especially when it's complaining about the keys innside "NativeScript.framework"? 

CLI: 2.1.0
Runtime: 2.1.0

Source available here: https://github.com/manijak/fancy-weather

**Comment by manijak** [comment]
I had to modify the `platforms/ios/Internal/NativeScript.framework/Info.plist` file manually prior to upload. Added both keys and a value. Upload successful.

**Comment by manijak** [comment]
Probably related to https://github.com/NativeScript/ios-runtime/pull/594

Closing

**Comment by devna13** [comment]
that file is not an xml file , This is what I get when I open it in text editor: 

bplist00�	

 !"#$&'()WDTXcodeYDTSDKNameZDTSDKBuild_CFBundleDevelopmentRegion_CFBundleVersion_BuildMachineOSBuild^DTPlatformName_CFBundlePackageType_CFBundleSupportedPlatforms_CFBundleInfoDictionaryVersion_CFBundleExecutableZDTCompiler_MinimumOSVersion_CFBundleIdentifier^UIDeviceFamily_DTPlatformVersion\DTXcodeBuild_CFBundleSignature_CSResourcesFileMapped_DTPlatformBuildT0731[iphoneos9.3V13E230WEnglishPU15F34XiphoneosTFMWK�XiPhoneOSS6.0\NativeScript_"com.apple.compilers.llvm.clang.1_0S8.0_org.nativescript.NativeScript�%S9.3V7D1014T????	3;EPl~�����)>Man���������������"&FHJNUZ*[

**Comment by devna13** [comment]
Hi @manijak

I'm getting same error  but When I open `platforms/ios/Internal/NativeScript.framework/Info.plist` in text editor this is what I get 
```
 
bplist00�	

 !"#$&'()WDTXcodeYDTSDKNameZDTSDKBuild_CFBundleDevelopmentRegion_CFBundleVersion_BuildMachineOSBuild^DTPlatformName_CFBundlePackageType_CFBundleSupportedPlatforms_CFBundleInfoDictionaryVersion_CFBundleExecutableZDTCompiler_MinimumOSVersion_CFBundleIdentifier^UIDeviceFamily_DTPlatformVersion\DTXcodeBuild_CFBundleSignature_CSResourcesFileMapped_DTPlatformBuildT0731[iphoneos9.3V13E230WEnglishPU15F34XiphoneosTFMWK�XiPhoneOSS6.0\NativeScript_"com.apple.compilers.llvm.clang.1_0S8.0_org.nativescript.NativeScript�%S9.3V7D1014T????	3;EPl~�����)>Man���������������"&FHJNUZ*[
```

any thoughts?

Thanks

**Comment by manijak** [comment]
Open with XCode ;-)

**Comment by devna13** [comment]
@manijak Thank you :)
and this is nativescript bundle version or can I put any number?

**Comment by manijak** [comment]
I added 2.1.0 in both keys

**Comment by Milewski** [comment]
worked for me..

actually **Bundle version** was already there but it was empty.. so i corrected it and also included **Bundle versions string, short**

**Comment by louislarry** [comment]
without XCode, use PbuddyList
```bash
/usr/libexec/PlistBuddy platforms/ios/internal/NativeScript.framework/Info.plist -c "Add :CFBundleShortVersionString string 1.0"
/usr/libexec/PlistBuddy platforms/ios/internal/NativeScript.framework/Info.plist -c "Set :CFBundleVersion 1.0"
```
