### ISSUE TITLE
Crypto module not supported ?

### ISSUE THREAD

**Issue by ignaciolarranaga** [NativeScript/NativeScript#2403]
Here it says the crypto module is supported: https://github.com/NativeScript/NativeScript/wiki/supported-npm-modules

But for example adding the aws-sdk (which requires crypto) produce an error?:

Jul  1 14:59:43 MacBook-Pro-de-Ignacio gyntoclient[85460]: file:///app/tns_modules/aws-sdk/lib/util.js:3:24: JS ERROR Error: **Could not find module 'crypto'**. Computed path '/Users/ignacio/Library/Developer/CoreSimulator/Devices/9664AAC3-BF9C-4721-890C-268893875DB9/data/Containers/Bundle/Application/17765363-57F3-43B9-84E9-A8F5D2EBFB62/gyntoclient.app/app/tns_modules/crypto'.
Jul  1 14:59:43 MacBook-Pro-de-Ignacio com.apple.CoreSimulator.SimDevice.9664AAC3-BF9C-4721-890C-268893875DB9.launchd_sim[63335] (UIKitApplication:org.nativescript.gynto[0xbef5][85460]): Service exited due to signal: Segmentation fault: 11

**Comment by tsonevn** [comment]
Hi @ignaciolarranaga,

Thank you for reporting your problem.

I have made a little research and found that you should use `npm install crypto`  to install the crypto plugin. I am attaching sample code snippet, how to require it in your project. 

main-page.ts
```
import { EventData } from "data/observable"; 
import { Page } from "ui/page";
var CryptoModule = require('crypto/md5');
export navigatingTo(args: EventData) {
    // Get the event sender
    var page = <Page>args.object;
    var tmpvar = CryptoModule.hex_md5('abc');

    console.log("crypto test - "+tmpvar);
}

```
main-page.js
```
var CryptoModule = require('crypto/md5');
function navigatingTo(args) {
    // Get the event sender
    var page = args.object;
    var tmpvar = CryptoModule.hex_md5('abc');
    console.log("crypto test - " + tmpvar);
}
exports.navigatingTo = navigatingTo;
```

I hope this helps

**Comment by vbudilov** [comment]
@tsonevn I think the question is in regards to aws-sdk not working since crypto cannot be found (which is a dependency). Have you tried using aws-sdk within nativescript?

**Comment by ignaciolarranaga** [comment]
@vbudilov just to comment, you are right, my ultimate intention was to upload files to S3 from the phone. I wasn't able to make the aws-sdk work on Nativescript so I did a workaround by implementing the upload manually (reproducing what the SDK actually does).
Here is the solution if you are interested: http://stackoverflow.com/questions/37581693/nativescript-background-http-file-uploading-to-s3/38174135#38174135

**Comment by vbudilov** [comment]
@ignaciolarranaga that's what I was afraid of. I'm still hoping there's a way to get this working on nativescript without signing the aws requests. Maybe I'll submit a nativescript issue/feature request and see where it takes me. Thanks!
