### ISSUE TITLE
Angular template is broken and updating to RC4 fixes it

### ISSUE THREAD

**Issue by tinchou** [NativeScript/NativeScript#2404]
Hi,

I just tried out the angular template (`tns create demo --ng`) and it's broken. It'll compile but then display an error message in the emulator.

I fixed it by manually updating to RC4:

```
  #...
  "dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/platform-server": "2.0.0-rc.4",
    "@angular/router": "3.0.0-beta.1",
    "@angular/router-deprecated": "2.0.0-rc.2",
    #...
```

**Comment by tsonevn** [comment]
Hi @tinchou,

I tested your scenario, however I was unable to reproduce such an issue. Could you try to upgrade to latest NS using the described steps [here](https://docs.nativescript.org/releases/upgrade-instructions) and then to create new sample project using `tns create demo --ng`.

Let me know whether this helps .

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#323

**Comment by tsonevn** [comment]
I moved this issue in [nativescript-angular](https://github.com/NativeScript/nativescript-angular) repo
