### ISSUE TITLE
Gestures no longer work as they did in the earlier versions

### ISSUE THREAD

**Issue by jalal** [NativeScript/NativeScript#2409]
The simplest way to reproduce this issue is to run vakrilov's demo and then update the libraries to the latest versions.
https://github.com/vakrilov/native-script-pan-scale-demo

This started happening on about the 28 June (when nativescript moved from 2.0.1 to 2.1.0)

Platforms: All
Operating systems: Ubuntu, MacOS

tns --version: 2.1.0
tns-core-modules: 2.1.0
tns-ios: 2.1.0
tns-android: 2.1.1

**Comment by NickIliev** [comment]
Hi @jalal I have tested the demo and it seems to work as expected in iOS however, I can confirm that in Android, there are unexpected glitches when gestures are triggered. 


@vakrilov reproduced with:
```
    "tns-android": {
      "version": "2.1.1"
    }

    "tns-core-modules": "2.1.0"

```

**Comment by vakrilov** [comment]
Hi @jalal,
I have updated the repo with the example and tested it on both Android and Ios. The apps seems to work as expected. 
Can you please try the new version and if there is still a problem - please share some more info so that we can investigate.

**Comment by jalal** [comment]
I can confirm that it now works correctly. What is changed? Or shall I look through the source :)

Using:
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 2.1.0           │ 2.1.0          │ Up to date  │
│ tns-core-modules │ 2.1.0           │ 2.1.0          │ Up to date  │
│ tns-android      │ 2.1.1           │ 2.1.1          │ Up to date  │
│ tns-ios          │ 2.1.0           │ 2.1.0          │ Up to date  │

**Comment by vakrilov** [comment]
The only significant change I did is [here](https://github.com/vakrilov/native-script-pan-scale-demo/blob/master/app/main-page.ts#L22-L25). The other changes are mostly typings because of the javascript->typescript migration.

**Comment by jalal** [comment]
I think I wasn't initialising the scaleX/Y coords...
