### ISSUE TITLE
Set base URL in WebView to be able to load resources

### ISSUE THREAD

**Issue by emiloberg** [NativeScript/NativeScript#241]
Hi,

What I'm trying to achieve here is to pre-save images in the App which are then displayed in the html in a WebView

You [recently](https://github.com/NativeScript/NativeScript/pull/179) added the ability to load local html files]/string with html in it in the Webview (yay!)

Looking at the code ([android](https://github.com/NativeScript/NativeScript/blob/master/ui/web-view/web-view.android.ts#L100)/[iOS](https://github.com/NativeScript/NativeScript/blob/master/ui/web-view/web-view.ios.ts#L108)) it looks like you're setting the baseURL to `null` (in the case of Android you probably have to change the `loadData` to [loadDataWithBaseURL](http://developer.android.com/reference/android/webkit/WebView.html#loadDataWithBaseURL) to be able to set BaseURL).

If I understand correctly, if this was set to a directory available to the app (`fs.knownFolders.documents()` ?) we would be able to load local resources from the HTML. E.g if we have `<img src="images/lolcat.png">` in our html that'd actually be loaded from our local resource.

I'd love to test this out but unfortunately my Objective C skills are atrocious.

#### Use case
I'm working on an ([open source app](https://github.com/emiloberg/oppna-program-reklistan-app)) which is a tool for doctors to help them prescribe medicine. There's a [web site](https://reklistan.vgregion.se/) today will all this information. Information on that site is displayed with a little help from a JSON object + Handlebars. To be able to update both the site and the mobile app at the same time I'm fetching both the JSON and the Handlebars templates in the App and are then displaying the content in a WebView. Somehow I need to be able to fetch the images and store them locally (for the app to be able to work offline) and then display the images in the WebView.

**Comment by enchev** [comment]
Implemented in https://github.com/NativeScript/NativeScript/pull/625
