### ISSUE TITLE
How to develop Notebook with secured data?

### ISSUE THREAD

**Issue by katturajam** [NativeScript/NativeScript#2410]
I would like to develop a secured encrypted data Notebook like `Manual Notebook`. 
With Password locking. 

![notebook](https://cloud.githubusercontent.com/assets/14198567/16549536/df26ad24-41bd-11e6-94bd-497d52ecf749.JPG)
Anybody have idea, Can you share me?

My Aim is to release `Ad free` NoteBook both Android & IOS or At least Android only

**Comment by NickIliev** [comment]
Hi @katturajam 

You question is more how-to related than a product issue and for this kind of questions you can find better support in [StackOverflow ](http://stackoverflow.com/questions/tagged/nativescript)and in [Google groups](https://groups.google.com/forum/#!forum/nativescript).

If you want to produce an encrypted notebook app with password authentication you should probably think about storing the user data in reliable backend service.(e.g. [Telerik Backend](http://docs.telerik.com/platform/backend-services/javascript/)) so the information will be stored and retrieved when needed from different devices and for the specific logged user. With Telerik Backend you can create [encrypted connection f](http://docs.telerik.com/platform/backend-services/javascript/security/introduction#connection-encryption)or further security. 
Your backend should provide you with the means of creating different notebook models (e.g. notebook, notebookPage, pageSection, dailyEntry, importatnNotes, etc.) and user models (admin, user, etc.)

At your application, you should probably create a login system that provides an easy and intuitive way for registering/login the user (e.g. [Auth0](https://www.npmjs.com/package/nativescript-auth0)) which then interacts with your userModel (that loads the user spefici data from your backend service) and provides nice UX and your business logic within the app (e.g. createNewPage(), deletePage(), createNewEntry(), deleteEntry(), markAsImporant(), share(), etc.)

As for the UI one possible idea is to create your notebook pages using [nativescript-sliides](https://www.npmjs.com/package/nativescript-slides). With this plugin you can slide your notebook pages and simulate the real experience.

All this is just hypothetical scenario - You can choose from many different approaches when creating your notebook. I recommend taking a lok at iur [sample-Groceries](https://github.com/NativeScript/sample-Groceries) repository where you can find both NativeScript Core and NativeScript+Angular implementations (at the respective branches). This app is pretty close to your idea  it is overall a checkbook for adding and removing items which is very close to a notebook functionality.
