### ISSUE TITLE
Page navigation transitions on Android

### ISSUE THREAD

**Issue by eduardoturconi** [NativeScript/NativeScript#2420]
Hello.

How can I keep the current frame fixed while animating the new frame over?
I tried creating a custom transition, and applying an animation that chances nothing (scale from 1 to 1, for example), but the current frame apparently is kept over the new frame until the transition finishes.

**Comment by NickIliev** [comment]
Hello @eduardoturconi 

Can you share with us sample project/code in order to reproduce your scenario.

**Comment by eduardoturconi** [comment]
Hi, 
I created a sample project in https://github.com/eduardoturconi/testapp

**Comment by NickIliev** [comment]
Hello @eduardoturconi 

Please excuse me for the late answer!
I have just seen your project (based on the sample demo from our documentation) 
and noticed that you don't have the **animated** property set (to **true**).

With this code, the animation is working as expected.
```
var frameModule = require("ui/frame");
var customTransitionModule = require("./custom-transition");

function onTap(args) {
    var customTransition = new customTransitionModule.CustomTransition(1000, "easeIn");
    var navigationEntry = {
        moduleName: "main-page",
        animated: true,
        transition: {instance: customTransition}
    };
    frameModule.topmost().navigate(navigationEntry);
}

exports.onTap = onTap;
```
