### ISSUE TITLE
Duplicate http cookie header in Android

### ISSUE THREAD

**Issue by devna13** [NativeScript/NativeScript#2421]
### Tell us about the problem
Cookie header gets added multiple times.

### Which platform(s) does your issue occur on?
only happens in Android. (tested same code in iOS )

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.1.0
- Cross-platform modules: 2.1.0
- Runtime(s): tns-android : 2.1.1

### Please tell us how to recreate the issue in as much detail as possible.

making http request cookie header gets added multiple times.

```
var http = require("http");
...
        return http.request({
            url: url,
            method: 'POST',
            headers: {
            "Cookie": "Bearer=XSTH4q...Je7",
            "Content-Type": "application/json;charset=UTF-8",
            "Cache-Control": "max-age=0",
            "Connection": "keep-alive"
        },
         content: postData,
        });

```

tns emulate android --geny="g1"

HTTP traffic in charles proxy: 

```
GET /api/account/userinfo HTTP/1.1
Cookie: Bearer=XSTH4q...Je7
Content-Type: application/json;charset=UTF-8
Cache-Control: max-age=0
Connection: keep-alive
User-Agent: Dalvik/2.1.0 (Linux; U; Android 6.0; g1 Build/MRA58K)
Host: xyz.com
Accept-Encoding: gzip
Cookie: Bearer=XSTH4q...Je7

```

it seems that android code automatically adds the last "Set-Cookie: " response header to next http request headers ?

**Comment by tsonevn** [comment]
Hi @devna13, 

Thank you for reporting this issue.

In my opinion the problem has been introduced in this [issue ](https://github.com/NativeScript/NativeScript/issues/2413) and been already fixed. In regard to that the solution will be available in next NativeScript release.

I hope this helps.

**Comment by NickIliev** [comment]
Closed as duplicate to [https://github.com/NativeScript/NativeScript/issues/2413](https://github.com/NativeScript/NativeScript/issues/2413)

**Comment by devna13** [comment]
Hi @tsonevn, any info on when is the next release?
