### ISSUE TITLE
App doesn't deploy on Android Emulator

### ISSUE THREAD

**Issue by renatograel14** [NativeScript/NativeScript#2425]
Hi, Folks!

I'm having an issue with nativescript emulator.

I already installed  the latest version of Android SDK. I can run an Android Instance with no problems. 

When I try 'tns run android --emulate' command it build perfectly the app, no errors, but the app doesn't start ): Using 'tns emulate android' I got this error (2nd image).

![image](https://cloud.githubusercontent.com/assets/5245008/16629955/8573eac6-438e-11e6-85fd-3298ba36a517.png)

![image](https://cloud.githubusercontent.com/assets/5245008/16630207/cc644b1e-438f-11e6-8df2-d610555c9276.png)

**Comment by tsonevn** [comment]
Hi @renatograel14, 

I have just tested test the both commands `tns run android --emulator` and `tns  emulate android` and was unable to reproduce any behavior. Could you give me more info about the given problem or to send me sample project, which could been debugged. As a possible solution you could try to delete `platforms/` and `node_modules/` folders from your project and to call `tns run android`. 

Regards,
@tsonevn

**Comment by tsonevn** [comment]
Hi @renatograel14 , 
Do you still have this problem?
Regards,
@tsonevn

**Comment by Anilinfo2015** [comment]
Yes this is true , i also face same error sometime and it work sometime. 
The issue generally faced on windows machine and during first time you run $tns run android,

Run the command again it work.

Some other people also facing same issue. 

1.[]( http://stackoverflow.com/questions/38411066/nativescript-built-but-not-being-installed-on-emulator)
