### ISSUE TITLE
(Android) Http module using HEAD method fails on large files

### ISSUE THREAD

**Issue by dfg-nota** [NativeScript/NativeScript#2426]
### Tell us about the problem
When you use http.request from Nativescript on Android using the HEAD method, it will fail on very large files, resulting in an OutOfMemoryError exception. This is because the http module tries to allocate a buffer the size of Content-Length, but it should not do so on a HEAD request.

### Which platform(s) does your issue occur on?
Android, have not tested iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.1.0
- Cross-platform modules: 2.1.0
- Runtime(s): Android: 2.1.1

### Please tell us how to recreate the issue in as much detail as possible.
using `http` module's request to make a HEAD request on a very large file will simply crash the app on Android. I dug deep to find the source of the bug and found out that [a buffer the size of the response's Content-Length header is created](https://github.com/NativeScript/tns-core-modules-widgets/blob/master/android/widgets/src/main/java/org/nativescript/widgets/Async.java#L177), even on a HEAD request, thus causing an OutOfMemoryError exception when the file requested has a size larger than the available RAM on the device.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```
http.request({
    method: 'HEAD',
    url: 'http://ipv4.download.thinkbroadband.com/1GB.zip'
});
```
Will crash the app on most devices & emulators in my experience

## Pull Request
I have created a PR to fix this issue on the tns-core-modules-widgets project:
https://github.com/NativeScript/tns-core-modules-widgets/pull/42

**Comment by NickIliev** [comment]
Hey @dfg-nota thank you for the PR - i am closing this issue as resolved via [https://github.com/NativeScript/tns-core-modules-widgets/pull/42](https://github.com/NativeScript/tns-core-modules-widgets/pull/42)

**Comment by dfg-nota** [comment]
:warning: Ping - The pull request is still open, and hasn't been resolved yet.
