### ISSUE TITLE
Activity indicator not showing after browser redirect.

### ISSUE THREAD

**Issue by Premitium** [NativeScript/NativeScript#2429]
The issue is that after redirecting back from the device browser and an async operation is still running the activity indicator is not showing anymore.

We are using Android with CLI - 2.1.0
tns-android: "version": "2.1.1"

How to recreate it:
After the user chooses to log in with Facebook, the app redirects to the device browser and an activity indicator shows. 
After successful login, the browser redirects back to the app. However, the activity indicator doesn't show even though we have hard coded the loading flag to true. 

Is there a way to show the indicator when redirected back?

**Comment by NickIliev** [comment]
Hi @Premitium 

Can you provide us with a sample code or even better sample project to reproduce your issue? 
Without a code base, it is hard to know your setup (for example are you opening a modal page to log to Facebook or using a plugin or something totally different)

**Comment by Premitium** [comment]
I did a test application and everything works fine. It is something on our side. Thanks!
