### ISSUE TITLE
Classes extending Observable don't have their properties observable as mentioned in the docs

### ISSUE THREAD

**Issue by victorhurdugaci** [NativeScript/NativeScript#2438]
According to example 5 (Typescript) from http://docs.nativescript.org/core-concepts/events#propertychange-event if a class extends Observable, then its properties it should be observable:

```Typescript
import observableModule = require("data/observable");

export class MyClass extends observableModule.Observable {
  private _myProperty:number;
  public get myProperty(): number {
    return this._myProperty;
  }

  public set myProperty(value: number) {
    this._myProperty = value;
  }
}
```

That doesn't work however:

```Typescript
var o = new MyClass();
o.on(Observable.propertyChangeEvent, d => {
    console.log(d);
})
o.myProperty = 5;
```

Looking through the `Observable` [code](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/data/observable/observable.ts#L54-L64), it's pretty obvious that this cannot work... If you invoke the constructor without manually specifying the properties, you end up with nothing observed.

If you pass the `json` object in the constructor, the code [here](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/data/observable/observable.ts#L67-L77) will overwrite the properties with its own implementation:

```Typescript
export class TestObservable extends Observable {
    private _myProperty: number;

    constructor()
    {
        super({
            'myProperty': 4
        });;
    }

    public get myProperty(): number {
        return this._myProperty;
    }

    public set myProperty(value: number) {
        console.log('Property changed code');
        
        this._myProperty = value;
    }
}
```

I believe that either the documentation is wrong or `Observable` does something that it shouldn't. 

My 2c on what the code should actually do:

1. If called without any arguments, Observable should index itself. That way a class extending it will work.
2. If there's already a property with a certain name, instead of replacing it's implementation, wrap it in your own call but still call the original implementation.

**Comment by tsonevn** [comment]
Hi @victorhurdugaci,
Thank you for reporting your problem,

I review the given code snippets, however I think that problem is due to incorrect  definition of your setter. The first mistake is that you should call super method without any parameters and the second think you should add in your code is notify listener, which will be firing propertyChangeEvent, when you set new value to your property. In regard to that you could review the example below.


`main-page.xml`

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <StackLayout>
    <Label text="Tap the button" class="title"/>
    <Label text="{{ myProperty }}" class="message" textWrap="true"/>
  </StackLayout>
</Page>
```

`main-page.ts`
```
import { EventData } from "data/observable"; import { Page } from "ui/page"; import { MyClass } from "./main-view-model"; import {setTimeout} from "timer"

// Event handler for Page "navigatingTo" event attached in main-page.xml export function navigatingTo(args: EventData) {
    // Get the event sender
    var page = <Page>args.object;
    var obs = new MyClass();


    obs.myProperty=2;
    setTimeout(function() {
        console.log("value change");
        obs.myProperty=4;
    }, 2000);

    page.bindingContext = obs;
}
```
`main-view-model.ts`

```
import {Observable} from "data/observable";

export class MyClass extends Observable {
  private _myProperty:number;
  constructor(){
      super();
  }

  public get myProperty(): number {
    return this._myProperty;
  }

  public set myProperty(value: number) {
    this._myProperty = value;
    super.notify({ object: this, eventName: Observable.propertyChangeEvent, propertyName: "myProperty", value: value });
  }
}
```

I could also review the discussion in [this](https://github.com/NativeScript/NativeScript/issues/1863) issue and the article [here](https://docs.nativescript.org/core-concepts/events#example-6-creating-a-custom-event)


I hope this helps
Regard,
@tsonevn

**Comment by victorhurdugaci** [comment]
Thanks for the reply @tsonevn. Makes sense that you have to call `notify` to do the actual notification.

Should this be a documentation bug instead? The first snippet I shared from the the official nativescript docs.

**Comment by tsonevn** [comment]
Hi @victorhurdugaci, 
Thank you for your reply.
The purpose  of the [Example 5](http://docs.nativescript.org/core-concepts/events#example-5-creating-a-custom-class-and-inheriting-observable-class) is to show how to extend ObservaleModule and to create needed getter and setter for the property. The example explains step by step how ObservableModule works. However we could add some examples how to use custom view model and notify listener in the future documentation updates.

Regards,
 @tsonevn
