### ISSUE TITLE
Resource generator for NativeScript

### ISSUE THREAD

**Issue by dimpu** [NativeScript/NativeScript#2442]
Is there any icons or splash screen generator for NativeScript. 

I'm looking for something as Ionic have.
http://blog.ionic.io/automating-icons-and-splash-screens/

**Comment by tsonevn** [comment]
There are several option to convert  images for ios and android , which you could use as a icons or splash screens.
The first option is to use [this ](http://nsimage.brosteins.com/) site, to convert your images in needed size.  
In regard to the question you could also use some of the image manipulation programs like GIMP, which is free open source program, or to use Photoshop to create the images for ios or android. You could review below attached tutorials, where has been shown how to create those images:
[Example](https://www.youtube.com/watch?v=COcp7t4dvgE&feature=youtu.be)

[GIMP](https://www.gimp.org/tutorials/Creating_Icons/)

[Example](http://graphicdesign.stackexchange.com/questions/15051/creating-graphics-for-android-ios-mobile-devices)

Another option is to use this sites icon_slayer or [http://ticons.fokkezb.nl/#result](http://ticons.fokkezb.nl/#result), which will auto  generate  icon for all ios and Android devices.

For further question you could use: [StackOverflow](http://stackoverflow.com/questions/tagged/nativescript)

I hope this helps

**Comment by dimpu** [comment]
Thanks a lot, @tsonevn.

But it would be great if we have some cli generator. With above options, we need to upload resource every time,  download the generated images and place them at proper positions.

For example for android even for a single image, we have uploaded and generate the resource and place them at folders. 
drawable-hdpi
drawable-ldpi
drawable-mdpi
drawable-nodpi
> Don't know about IOS

Instead of that, it would be so nice if we can have a cli just by running  a single command it will do all that stuff for us.

Please check the ionic cli for generating the resource. It's quite a smoot. All we have to do it provide PSD or AI or any Image. 

Another big advantage is our Resource source (PDS or AI) can be part of the source code. 

right?

**Comment by tsonevn** [comment]
Hi @dimpu,
you could open new issue tagged as feature request, where you are describing your idea, then the people could vote for it. If there is interest, the request could be reviewed and planned for some of the futher NativeScript versions
Regards,
@tsonevn

**Comment by dianjuar** [comment]
@dimpu Did you open the issue as @tsonevn suggest ?

**Comment by NathanaelA** [comment]
There are two places to create images via the web for NativeScript.

http://images.nativescript.rocks/
http://nsimage.brosteins.com/
