### ISSUE TITLE
Observable notification not updating UI when triggered from 'on' handler

### ISSUE THREAD

**Issue by victorhurdugaci** [NativeScript/NativeScript#2453]
Maybe I'm doing something totally wrong but I just can't figure it out why the example below doesn't work. Is this a bug?

1. `tns create Foo --ng`
2. `tns platform add android`
3. Replace `app.component.ts` with:

    ```typescript
    import {Component, ElementRef, ViewChild} from "@angular/core";
    import {Observable} from 'data/observable'
    import {StackLayout} from 'ui/layouts/stack-layout'
    import {Button} from 'ui/button'

    @Component({
        selector: "my-app",
        template:
        `<StackLayout #container>
            <Label [text]="model.count"></Label>
            <Button text="Button 1" (tap)="onTap()"></Button>
        </StackLayout>`,
    })
    export class AppComponent {
        public model = new Model();

        @ViewChild('container')
        private container: ElementRef;

        public ngOnInit() {
            var stack = <StackLayout>this.container.nativeElement;

            var button = new Button();
            button.text = "Button 2";
            button.on(Button.tapEvent, data => {
                this.ChangeModel();
            });

            stack.addChild(button);
        }

        public onTap() {
            this.ChangeModel();
        }

        private ChangeModel() {
            this.model.count++;
        }
    }

    class Model extends Observable {
        private _count: number = 0;

        get count() {
            return this._count;
        }
        set count(val: number) {
            console.log("Model updated");
            this._count = val;
            this.notifyPropertyChange('count', val);
        }
    }
    ```

4. Run
5. Tap *Button 1* and notice that the model (see the console log) and the label (see the UI) are updated
6. Tap *Button 2* and notice that the model is updated but the UI doesn't get the notification

CLI: 2.1.0
core modules: 2.1.0
tns-android: 2.1.1
OS: Win 10 x64
Emulator: Genymotion

**Comment by tsonevn** [comment]
Hi @victorhurdugaci,
Thank you for reporting this issue.

I confirm that this is a real problem in NativeScript Angular2 project, when you are adding a Button as a child to the Layout on ngOnInit. I will move this issue in our [nativescript-angular](https://github.com/NativeScript/nativescript-angular) repo.  

Regard,
@tsonevn

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#346
