### ISSUE TITLE
Debugging NativeScript in browser

### ISSUE THREAD

**Issue by Dharmoslap** [NativeScript/NativeScript#246]
The good thing about front-end web technologies is that there are a lots of people who know how to quickly debug them just in the browser using DOM inspector. What is the point about making mobile application with CSS, if I can't use the benefit of DOM inspector? Alright, I can just follow the docs + common sense and hope that everything will always just work, but there will be for sure situations where inspecting CSS might be really helpful. There are already toolkits out there (Cordova/Ionic), where you can run your mobile app directly in the browser and debug it from there.

So we need to be able to open NativeScript app in the browser and develop it from there, and then run it simulators. That would probably mean to use some CSS/JavaScript polyfills for native elements.

**Comment by Nathanaela** [comment]
Unfortunately, this is a lot easier said than done.    Technically it could be done so it would just be another platform -- but it would be a lot of work getting all the pieces and pollyfill's together working...

**Comment by valentinstoychev** [comment]
@Dharmoslap We are already working on a tool that will bring similar experience to what you described. We already have good progress, please follow this issue - #165 :/cc @fealebenpae, @KristinaKoeva
