### ISSUE TITLE
Enhancement: visibility="hidden"

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#2461]
### Tell us about the problem

I would like to be able to hide an item in the layout without affecting the layout sizing.
Using visibility="collapsed" removes the item for the layout; causing the entire layout to be resized/recalculated and moving all the existing items around the screen.    I want the layout to remain the same (i.e. the hidden item still takes up space).
### Which platform(s) does your issue occur on?

Both
### Please provide the following version numbers that your issue occurs with:

Still an issue in NS 2.1 
### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

``` js
<StackLayout>
  <StackLayout id="one"><Button text="One" tap="click"/><Button text="Two" tap="click"/></StackLayout>
  <StackLayout id="two"><Label text="Hi"></StackLayout>
</StackLayout>
```

If you do `var sl = page.getViewById('one'); sl.visibility="collapsed";` everything following the first StackLayout will shift up in the screen.   Not what I want.
If you do `var sl = page.getViewById('one'); sl.opacity=0;` the layout stays; but all the buttons (and other elements) are still fully active.   Not what I want.

What I need is:

``` js
Android: setVisibility(View.INVISIBLE); 
iOS.element.hidden = true; BUT the _isVisibleCache = true.   
```

So the code I expect to work would be:
`var sl = page.getViewById('one'); sl.visibility="hidden";`

**Comment by tsonevn** [comment]
Hi @NathanaelA , 

Thank you for reporting your issue, 
I reviewed your  problem  and found that you could use `opacity` property to make the `StackLayout` invisible and   `off` method to [remove tap Event listener ](https://docs.nativescript.org/core-concepts/events#example-3-removing-a-button-tap-event-listener) of your buttons. This solution will not affect layout sizing and will  allow you to remove all event listeners for the inner objects. Further more you could review  the attached example below.
main-page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="onLooaded">
  <StackLayout>
  	<StackLayout id="one”>
		<Button text="One" tap="click" />
		<Button text="Two”/>
	</StackLayout>
  	<StackLayout id="two”>	
		<Label text="Hi”/>
	</StackLayout>
  </StackLayout>
</Page>

```
main-page.js
```
var createViewModel = require("./main-view-model").createViewModel;
var buttonModule = require("ui/button"); var page; function onLooaded(args) {
    page = args.object;
}
exports.onLooaded = onLooaded;


function click(args){
    var sl = page.getViewById('one');    
    console.log("clicked");
    args.object.removeEventListener(buttonModule.Button.tapEvent);
    sl.opacity=0;
}

exports.click = click;

```

I hope this is applicable for you.
Regards,
@tsonevn

**Comment by NathanaelA** [comment]
@tsonevn - I appreciate your work on this; but this only solves a very minor part of the issue.   That an actual real "Hidden" support would allow.     I actually tried opacity in the first place as a simple hack which is why I know the buttons, any TextEdit, Switches, etc are all still fully active when Opacity is changed.   You would literally have to peruse every single item inside a "hidden" layout to disable them all and that leads to a lot of unneeded code.    In some cases if it is/contains a listView; it would be very difficult to automatically disable all control inside (without using my nativescript-dom plugin) as LV don't allow the built in getViewById to search for nested items inside a LV.  Using opacity is a hack, really doesn't solve the use case.

You don't need you to "solve" my issue; all I wanted to do was log a enhancement request to actually support "hidden" as a valid visibility option as I think it should be part of the core, there are a several use cases where "hidden" is a better option than "collapsed"

---

   I've actually solved it on my own projects by created a 60ish line plugin that monkeypatches the tns-core-modules to support "hidden" and all I have to do is do "require('nativescript-hidden') inside my app.js ;So I can now do:
`var sl = page.getViewById('one'); sl.visibility="hidden";`
and it works exactly as expected.  

I expect this plugin probably to work for a really long time in the future; because that part of the code in TNS rarely changes; but I honestly think it is something that would be better if it was core rather than a plugin...

**Comment by tsonevn** [comment]
Hi @NathanaelA,
Thank you for your quick reply,

You are right it would be difficult to disable all controls in case you are using `opacity` property to hide the layout. In regard to that you have mentioned that you have implemented such a functionality for the `visibility` property and I could suggest you to make new pull request to the modules repo  and this feature could be available in some of the next NativeScript versions.

Thank you in advance.
Regards,
@tsonevn

**Comment by irman** [comment]
Any news on this?

**Comment by hshristov** [comment]
on track for 3.0 release

**Comment by alexziskind1** [comment]
I recently saw that hidden is one of the options. Is this still a problem?

**Comment by hiperbou** [comment]
Not working for me with 3.3.1 and Android

**Comment by NickIliev** [comment]
`hidden` was added [as an option for the visibility property ](https://github.com/NativeScript/NativeScript/blob/05c2460fc4989dae4d7fa1ee52f6d54e0c3113f5/tns-core-modules/ui/styling/style-properties.ts#L1086-L1094)

Closing as resolved.
