### ISSUE TITLE
Allow usage of CSS files within node_modules

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/NativeScript#2462]
I would like to be to use the `@import` syntax in CSS files to import files that live within `node_modules`. This would allow NativeScript themes to be distributed via npm, whereas currently—as best I can tell—they cannot.

The syntax doesn’t really matter to me, but maybe something like:

``` css
@import { url('tns-theme-core/style.css') }
```

My vision is we’d have the ability to ship themes via npm, and potentially consume them both from Kendo UI apps and NativeScript apps.

Thanks. And if this functionality is already possible, consider this a documentation request 😄

**Comment by tsonevn** [comment]
Hi @tjvantoll, 

Thank you for your question.

This functionality is still not available. At the moment the only way is to import external `css` file, which lives in `app` folder as  it is described in the [documentation](https://docs.nativescript.org/ui/styling#import-external-css).  However I will log this as a feature request, which could be available in some of the next NativeScript versions.

Regards, 
@tsonevn

**Comment by NickIliev** [comment]
The feature is implemented and can be accessd via the following syntax (both TS or plain JS):

```JavaScript
@import '~nativescript-theme-core/css/core.light.css';
```

Closing as resovled
