### ISSUE TITLE
Where to find android system icons.

### ISSUE THREAD

**Issue by dimpu** [NativeScript/NativeScript#2463]
I'm trying to have android system icon in ActionBar

<ActionBar title="ActionBar Style">
  <NavigationButton text="Go Back" android.systemIcon="ic_menu_back"></NavigationButton>
  <ActionItem ios.systemIcon="2" android.systemIcon="ic_menu_edit" ios.position="right"></ActionItem>
</ActionBar>

Where can I find icon symbols?  For example `ìc_menu_back` is for back button similarly I want to have menu icon on my action bar.

Thanks in advance.

**Comment by NickIliev** [comment]
Hello @dimpu 

Those symbols are from the Android SDk drawable resources.
More info can be found at the following links:
[https://developer.android.com/reference/android/R.drawable.html](https://developer.android.com/reference/android/R.drawable.html)

and here
[https://developer.android.com/design/downloads/index.html](https://developer.android.com/design/downloads/index.html)

Respectively, you can use systemIcons in your ActionBarItem with the following syntax
```
<ActionBar title="Action Items">
  <ActionItem tap="onShare"
      ios.systemIcon="9" ios.position="left"
      android.systemIcon="ic_menu_share" android.position="actionBar"/>
  <ActionItem tap="onDelete"
      ios.systemIcon="16" ios.position="right"
      text="delete" android.position="popup"/>
</ActionBar>
```

**Comment by elvismercado** [comment]
@majorpaynegh i also want to know this

**Comment by majorpaynegh** [comment]
@NickIliev can i call the android system icon in css??

**Comment by sushant-j** [comment]
@NickIliev  - Any way to use System Icons outside ActionBar as @majorpaynegh asks above?
Couldn't find any resource if yes.

**Comment by kamok** [comment]
Is there any links where the entire album of icons is available? It seems like the links from nick are only text or for Angular Material.

Can we use Angular Material icons with `android.systemIcon`?

**Comment by dodongphure** [comment]
We can use android system icons with <Image> tag in angular version?

**Comment by mikhailshapiro** [comment]
Here is a gallery of the android system icons http://www.hellothupten.com/2013/06/25/436/
