### ISSUE TITLE
Question: How to popup a custom view or disable entire view? 

### ISSUE THREAD

**Issue by ryc16** [NativeScript/NativeScript#2464]
Hi, I want is to have a pop up where could add any control working like another page. ie. an input form with complex layout. I couldn't find helpful information from NS and internet. I assume there is no such control in NS. So I am trying work around it to simulate the behavior by creating a normal GridView or ScrollView follow by second AbsoluteLayout. Disable GridView/ScrollView with 0.5 opacity and show the AbsoluteLayout with a reduced side. However, doesn't seem work as expected, it does gray it entire view but not disable. I put isEnabled on GridView/ScrollView, all children are still enable. Although I could set isEnabled to individual control but too many to set and not really what I want. Set IsEnabled on ScrollView, but ScrollView is still able to scroll. 

My question here is what is the best way to have popup input form. If there is no popup control, will my workaround approach work? How could I disable entire view (not every single control)? For ScrollView, not allow to scroll once disabled. 

For example, 

```
<GridLayout>
<ScrollView isEnabled="false" opacity="0.5">
</ScrollView>
<AbsoluteLayout width="80%" height="80%" backgroundColor="white" opacity="1">
</AbsoluteLayout>
</GridLayout>
```

**Comment by NathanaelA** [comment]
Ray,

   You can use custom Dialogs, or even create a modal screen (showModal).    However if you still want to do your own custom layout that you are enabling; you can do something like:
(This is assuming your using the NativeScript-Dom plugin, otherwise you have to do a bit more work as the Dom plugin adds the classList ability, and getElement* ability to NS)
```
<GridLayout>
<ScrollView id="scrollView">
</ScrollView>
<AbsoluteLayout id="dialog" width="80%" height="80%" backgroundColor="white" >
</AbsoluteLayout>
</GridLayout>


.disabledOpacity {
  opacity: .5;
  isEnabled: false;
}

.disabledDialog {
  visibility: collapsed;
}

function showDialog(enabled) {
  // Get our Scroll View
  var sv = getElementById('scrollView');
  // Enabled or disable the opacity
  sv.classList.toggle('disabledOpacity', !enabled);

  // Enable or disable the controls inside the Scroller
  var textEdit = sv.getElementsByTagName('TextEdit');
  for (var i=0;i<textEdit.length;i++) { textEdit[i].isEnabled = !enabled; }
  var buttons = sv.getElementsByTagName('Button');
  for (var i=0;i<buttons.length;i++) { buttons[i].isEnabled = !enabled; }
  /* add any other edit controls */

  var dialog = getElementById('dialog');
  dialog.classList.toggle('disabledDialog', enabled);
 }

```

**Comment by NickIliev** [comment]
Hi @ryc16 

More about the **modal pages** mentioned by NathanaelA can be found here:
[https://docs.nativescript.org/core-concepts/navigation#modal-pages](https://docs.nativescript.org/core-concepts/navigation#modal-pages)

**Comment by ryc16** [comment]
@NathanaelA, thank for your suggestion. Will have a try.
@NickIliev, got exception before upgrade to tns 2.1.1. Just try it and it is what I need except one thing. When I tap on outside of modal, the modal got closing out. How to prevent this behavior? I prefer close the Modal by clicking ie a button in the Modal.

**Comment by NickIliev** [comment]
@ryc16 The first thing that comes to mind is to set your modal page with **fullscreen**  set to **true** .
(that said I should point out that in iOS the only possible behaviour is fullscreen = true)

**Comment by NickIliev** [comment]
@ryc16 with your modal page set to fullscreen you can then apply transparency to selected regions of your modal page and thus simulate that the page is not fullscreen.
However again due to some Apple restrictions setting transparency to modal page is not an easy thing to achieve in iOS. Solution to this problem can be found in [this discussion](https://github.com/NativeScript/NativeScript/issues/2086)
