### ISSUE TITLE
support for pouchdb and couchdb for nativescript apps

### ISSUE THREAD

**Issue by bsjaffer** [NativeScript/NativeScript#2466]
using pouchdb and couchdb to provide offline support for nativescript apps. A adapter which uses sqlite to store data offline.

**Comment by NickIliev** [comment]
Hello @bsjaffer 

There is already developed plugin for using CouchDB with NativeScript.
Link to the plugin repository can be found at the following link: [https://github.com/mehfuzh/couchbaselite-nativescript](https://github.com/mehfuzh/couchbaselite-nativescript)

Nice walkthrough article can be here : [http://blog.couchbase.com/2016/april/couchbase-mobile-in-a-cross-platform-telerik-nativescript-app](http://blog.couchbase.com/2016/april/couchbase-mobile-in-a-cross-platform-telerik-nativescript-app)

**Comment by bradmartin** [comment]
A plugin actually developed by Nic Raboy and others at Couchbase is here: https://github.com/couchbaselabs/nativescript-couchbase

**Comment by byteranger** [comment]
Pouch/CouchDB and Couchbase are completely different things.
