### ISSUE TITLE
Help with plugin development

### ISSUE THREAD

**Issue by alexrainman** [NativeScript/NativeScript#2476]
I am building a plugin and, in my plugin.android.ts i want to use the builder to load some component from xml, get _nativeView and add it to a ViewGroup but, .android and ._nativeView are always null.

How this can be achieved? I mean, get NativeView from {N} View at runtime and add it as a Child to another NativeView.

When the _nativeView is created?

**Comment by tsonevn** [comment]
Hi @alexrainman, 

I reviewed your problem and in regard to your question `android` property of the NativeScript layouts are available when the view has been initialized on the screen or have been created from the code behind manually. In addition you could review the article how to create [ui plugin](http://docs.nativescript.org/plugins/ui-plugin) in our documentation. 
I  found  also some useful stuffs in those articles: [creating-nativescript-plugins-in-typescript](http://developer.telerik.com/featured/creating-nativescript-plugins-in-typescript/) and [building-your-own-nativescript-modules-for-npm/](http://developer.telerik.com/featured/building-your-own-nativescript-modules-for-npm/) that might help you. 
You could use [this](https://github.com/bthurlow/nativescript-maskedinput) plugin as a sample.


Regards,
@tsonevn

**Comment by alexrainman** [comment]
@tsonevn thanks for the quick response. Actually, i dont have problem understanding the plugin architecture. My issue is getting _nativeView from {N} View. No matteer what i do, .android is always null.

```
instantiateItem : function (container, position)
{
    var view = builder.load({
        path: "~/Views",
        name: "myView"
    });
    viewPagerAdapter.addView(view.android);
    return view.android;
}
```

myView is an xml file that includes an StackLayout with 2 labels. Loading it with builder works as i can see it in debug mode but view.android is always null.

Same if i use:

```
var label = new Label();
label.android //null
```

Or any other widget. But if i do something like this:

```
instantiateItem : function (container, position)
{
    var label  = new android.widget.TextView(application.android.currentContext);
    label.setSingleLine(true);
    label.setEllipsize(android.text.TextUtils.TruncateAt.END);
    label.setText("Native");
    container.addView(label);
    return label;
},
```

It works. Any comments?

**Comment by alexrainman** [comment]
Also, i need to write plugin.android in JS because TypeScript cannot find android namespace, what im missing?

**Comment by alexrainman** [comment]
I was able to fix the namespace issue installing tns-platform-declarations package and adding this to references.d.ts
```
/// <reference path="./node_modules/tns-platform-declarations/ios.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/android17.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/org.nativescript.widgets.d.ts" />
```

But i still cannot get the nativeView at run time:

```
var button = new buttonModule.Button();
button.text = "Hello, world!";
container.addView(button.android); // .android is always null
```

Where container is a ViewPager instance.

**Comment by alexrainman** [comment]
```
Error: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
```

**Comment by tsonevn** [comment]
Hi @alexrainman ,
thank you for your explanation,
I reviewed your  problem to access `android` property of the view and found that the for Android the view should be first loaded on the visual UI tree and then  this property  will be available. In this case on after the view has been laoded `.android` will not be `null` For example:


`TypeScript`
```
function instantiateItem(container:StackLayout){
       let label = new Label();
       container.addChild(this.label);
       label.onLoaded=function() {
            console.log(this.android);
        }
}
```
As a solution you could use Android native code to create your views and to add them to the Page.

I hope this is applicable for you.
Regards,
@tsonevn

**Comment by alexrainman** [comment]
This is a huge {N} limitation. This property and .ios should be available at runtime without adding anything to the UI visual tree. Its basic functionality to get the NativeView from the View abstraction, dont you think? I cannot finish my plugin without this :(

**Comment by tsonevn** [comment]
Hi @alexrainman ,

This issue has not been related with NativeScript, actually it depends on Android. I suggest you to extend the view component you want to use (For example Label) and to rewrite  its `_createUI` method,   then you would be able to access the view, just after it is loaded on the UI visual tree and you will be allowed to make your changes. You could review the implementation of our [modules](https://github.com/NativeScript/NativeScript/tree/master/tns-core-modules) 

Regards,
@tsonevn

**Comment by alexrainman** [comment]
I believe you dont understand what i want to do.

I want to define a NS View in xml or code, then get its nativeView (.android and .ios) without the need of adding it to the UI visual tree and then add the nativeview to a native container view as a child.

Thats whay im saying its a huge limitation. How you do in the case of listview cells?

**Comment by tsonevn** [comment]
Hi @alexrainman ,
Thank you for your explanation.

To be able to get container android property you should also wait until the the container has been added to the UI tree.  You should wait for `onLoaded` event of the container or to rewrite `_createUI` method of the container you are setting as argument in your `plugin` method. In regard to that you could review, how has been implemented [Placeholder](https://github.com/NativeScript/NativeScript/tree/master/tns-core-modules/ui/placeholder) module, which gives you the functionality to add nativeView-s in `NativeScript UI`.

I hope this information will help you to solve your problem.

**Comment by alexrainman** [comment]
Guys, container is already a Native View, so it doeant have OnLoaded. As its a Android ViewPager, i will be adding and removing views from it at runtime, views that will come from NS xml, got it now?

I wont be adding native view to NS view, i will be getting native view from NS view and adding it to a native container.

**Comment by hshristov** [comment]
Hi @alexrainman 
What you want to do is possible at the moment - after you get the NS views from `builder.load` you have to call `._onAttached` method on the result of load method and pass the native activity as parameter so that our widgets could instantiate they native counterparts.
Keep in mind that if you don't add NS View inside NS parent - several things won't work - property inheritance, CSS applying, loaded & unloaded events, etc. If you are fine with this - you could use this approach. But if you want all the other benefits you will have to wrap the native viewGroup you want to use as parent to NS View (e.g. probably inherit from Layout or ContentView) and follow our approach to create custom UI view described here:
http://docs.nativescript.org/plugins/ui-plugin

You could check how we handle viewPager inside our TabView component:
https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/tab-view/tab-view.android.ts

**Comment by alexrainman** [comment]
._onAttached method cannot be found in View module :(

**Comment by hshristov** [comment]
@alexrainman It is there but the `_` shows that it is private method. Cast it to any to avoid TS check

**Comment by alexrainman** [comment]
@hshristov it works. Releasing a promised plugin soon :)

**Comment by alexrainman** [comment]
@hshristov question, i see a pattern in tab-view plugin:

```
var PagerAdapterClass;
function ensurePagerAdapterClass() {
    if (PagerAdapterClass) {
        return;
    }
...
```

And then you call ensurePagerAdapterClass before assigning the adapter to ViewPager. Is this a requirement?

**Comment by alexrainman** [comment]
@hshristov i am having the same problem but iOS. I am loading a view with build but .ios is null. What i need to call after loading a view with builder?

**Comment by alexrainman** [comment]
@hshristov i am developing the plugin right now and i have android version ready for release but i am facing issues on iOS. Can you take a look? Im sending you and invite to the private repo. Please take a look at thread we have been discussing in one open issue. using _onAttached in iOS doesn't have same result than Android. I am using UIPageViewController in iOS and assigning DataSource is not working so, i don't have Swiping behavior. I believe i am close but i need some help from core team. Once i get release one, this will be an open source project. Thanks.
