### ISSUE TITLE
Quick start application

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#248]
We need to create an application and publish it to the public app stores in order to show all the functionality that we have in NativeScript. Ideally we should also be able to load predefined sample applications (Tasks, Expensity, TelerikNEXT, etc).

It can be very similar to our other sample applications which we have for UI for iOS and UI for Android.

**Comment by PanayotCankov** [comment]
[We are not working on this, and the project has its own repo](https://github.com/NativeScript/nativescript-marketplace-demo)
It looks like it would be an ongoing process.
