### ISSUE TITLE
Provide better description for supported/unsupported CSS styles and syntax

### ISSUE THREAD

**Issue by BenevidesLecontes** [NativeScript/NativeScript#2480]
I'm like since 7 AM to 7PM, without eating and pulling my hair because of this LOL, would be nice if you implement a feature like this. Thanks

**Comment by NickIliev** [comment]
Hello @BenevidesLecontes 

NativeScript supports only a subset of CSS. 

The full list of supported CSS properties can be found at the following link:
[https://docs.nativescript.org/angular/ui/styling.html#supported-css-properties](https://docs.nativescript.org/angular/ui/styling.html#supported-css-properties)
You can also check the supported CSS selectors from this link:
[https://docs.nativescript.org/angular/ui/styling.html#supported-selectors](https://docs.nativescript.org/angular/ui/styling.html#supported-selectors)

[CSS Animations](https://docs.nativescript.org/angular/ui/animation-css.html) via keyframes are also supported

**Comment by BenevidesLecontes** [comment]
HI @NickIliev i saw all the guides but when use `padding:8 16;` the style won't apply
It only apply if i use `padding: 8 16 8 16;`

**Comment by NickIliev** [comment]
@BenevidesLecontes i see your point.. will move this issue to the documentation docs in order to provide better description of the supported syntax for each CSS property

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/docs#458
