### ISSUE TITLE
Is it possible to develope a cross-platform input method since nativescript is claiming to have access to all native APIs ?

### ISSUE THREAD

**Issue by c1ngular** [NativeScript/NativeScript#2481]
Any ideas?
or what am i missing ?

**Comment by NickIliev** [comment]
Hi @c1ngular 

Yes, you can implement cross-platform methods with accessing native APIs.
However to give you some valuable directions please provide more information on what you are trying to achieve and the code you are working with.

Meanwhile for better understanding on how to acces native APIs I recommned the follwing articles:
[Accessing native APIs with JavaScript](https://docs.nativescript.org/angular/core-concepts/accessing-native-apis-with-javascript.html)

[Java to javaScript marshalling](https://docs.nativescript.org/angular/runtimes/android/marshalling/java-to-js.html)

[Objective-C marshalling](https://docs.nativescript.org/angular/runtimes/ios/marshalling/Marshalling-Overview.html)

**Comment by c1ngular** [comment]
@NickIliev thank you for answering !  i was wondering , if nativescript alone(of course combine with necessary knowledge as well) is capable of developing an input method application? like  to make an input method for one specific minority language on smart phone platforms ! if possible, i should learn and dig deeper , if not , then let it is !

**Comment by NickIliev** [comment]
Hey @c1ngular virtually almost everything that is provided by the native APIs is applicable via the marshalling techniques used by NativeScript. At this very moment over [300 plugins in npm alone](https://www.npmjs.com/search?q=nativescript)  are developed by the community and most of them are cross-platform and all are using native APS, third-party libraries or both.

**Comment by c1ngular** [comment]
@NickIliev thanks ! i will start with something smaller and easier ! though i would love to see some of experienced developers to try this out ! it will be a very powerful demonstration of nativescript capability!  thanks again for your fast responses !
