### ISSUE TITLE
Cross-platform API for PhotoPicker

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#249]
Create cross-platform API for choosing an image from the device photo storage.

If you are interested in this feature please add comments below with specific requirements and [vote for this feature](https://nativescript.ideas.aha.io/ideas/NS-I-42) in our ideas portal.

**Comment by enchev** [comment]
Duplicate to https://github.com/NativeScript/NativeScript/issues/551

**Comment by bradmartin** [comment]
+1
