### ISSUE TITLE
Question: is this an okey way to...

### ISSUE THREAD

**Issue by IvRRimum** [NativeScript/NativeScript#2490]
Hello,

Recently started using nativescript with firebase. I want to redirect user to dashboard, if he is alredy logged in. Here is how i am doing it right now:

```
  2 import {Component} from "@angular/core";
  3 import {NS_ROUTER_DIRECTIVES} from "nativescript-angular/router";
  4 import firebase = require("nativescript-plugin-firebase");
  5 
  6 @Component({
  7   selector: "main",
  8   directives: [NS_ROUTER_DIRECTIVES],
  9   template: "<page-router-outlet></page-router-outlet>"
 10 })
 11 export class AppComponent {
 12 
 13   constructor(private _router: Router) {
 14     var thisAppComponent = this;
 15 
 16     firebase.getCurrentUser().then(function(data) {
 17       if(data.uid != "") {
 18         thisAppComponent._router.navigate(["/dashboard"])
 19       }
 20 
 21       console.log(data.uid);
 22     }, function(error) {
 23       console.log("userNotLoggedIn")
 24     });
 25 
 26   }
 27 }

```

I wanted to ask, is this okey way to do it ? What could be improved ?

**Comment by chillyprig** [comment]
I also face the same problem. I have changed line 4 to:

`var firebase = require("nativescript-plugin-firebase");`

But get this error instead:

```
Jul 25 02:59:31 Popeyes-MacBook-Pro KickoffToday[2067]: CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:310:18: Error in firebase.init: ReferenceError: Can't find variable: FIRApp
Jul 25 02:59:31 Popeyes-MacBook-Pro KickoffToday[2067]: CONSOLE LOG file:///app/main.js:12:16: firebase.init error: ReferenceError: Can't find variable: FIRApp
```

:(

**Comment by tsonevn** [comment]
Hi @IvRRimum,

You could review [this](http://plugins.telerik.com/nativescript/plugin/firebase) articles, where have been described how to use `nativescript-plugin-firebase`. Further more you could also review the demo app [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase-demo) .

I hope this is applicable for you.

**Comment by tsonevn** [comment]
You could also review this example [here](https://github.com/vakrilov/firegame/tree/master/app) . To run the examples you should use the described [setup](https://github.com/EddyVerbruggen/nativescript-plugin-firebase-demo) steps from the plugin demo .

**Comment by IvRRimum** [comment]
@tsonevn Well, i looked at the examples. And they are pretty similar to what i do..

```
@Injectable()
export class AuthGuard implements CanActivate {
  constructor(private router: Router, private store: Store<AppState>) { }

  canActivate() {
    let user;
    this.store.take(1).subscribe(s => user = s.auth.currentUser);

    if (user) {
      return true;
    } else {
      this.router.navigate(["/login"]);
      return false;
    }
  }
}
```
