### ISSUE TITLE
Excluding .ts and .scss files from the final package

### ISSUE THREAD

**Issue by devna13** [NativeScript/NativeScript#2491]
running `tns prepare ios` typescript and sass files will be copied to the `/platforms/ios/<appname>/app/ `directory which is the final package if I understand correctly?

Typescript is already been transpiled to .js and .ts files shouldn't be there.

**Comment by Anilinfo2015** [comment]
Same thing happen with android also.

platforms\android\src\main\assets\app

I can see all the .ts files in this folder. I don't think they should be their if they are using ECMAScript engines.

**Comment by enchev** [comment]
Actually TS files are there for debugging purposes, if you use however `--release` you will have app with .js files only.

**Comment by devna13** [comment]
Hi @enchev 

I'm following [Publishing for iOS blog](http://docs.nativescript.org/angular/publishing/publishing-ios-apps) and  I don't see any --release usage there.

Its using `tns prepare ios` command for publishing which doesn't remove .ts and .scss files.

Can you elaborate more on this?

Thanks
