### ISSUE TITLE
Changing the application name

### ISSUE THREAD

**Issue by BitsOnCoffee** [NativeScript/NativeScript#2499]
As I understood a final AndroidManifest.xml should be merged from _app/App_Resources/Android/AndroidManifest.xml_ and _AndroidManifest.xml_ within a _Platform_,

But when I change _application/android:label="MyName"_ rebuild and deploy, nothing is changed.

**Comment by Pip3r4o** [comment]
@BitsOnCoffee If you want to make changes that reflect on the final AndroidManifest you should edit the one in `app/App_Resources/Android`. The file you see in `platforms/android/src` is the resulting final merged AndroidManifest that will be uploaded to the device, but will most likely always be overwritten by the merge operation.

**Comment by BitsOnCoffee** [comment]
@Pip3r4o ok, so if I want to change the name of the app in the launcher, I should overwrite `app\App_Resources\Android\AndroidManifest.xml` like this?

`manifest -> application -> android:label="myName"`

Thanks

**Comment by Pip3r4o** [comment]
That should almost work, but not really. After some messing around I found out that changing the label alone was not enough. In addition to replacing application:android:label, I also had to declare use of xmlns:tools. The manifest looked something like this

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:tools="http://schemas.android.com/tools"
	package="__PACKAGE__"
	android:versionCode="1"
	android:versionName="1.0">

	<supports-screens
		android:smallScreens="true"
		android:normalScreens="true"
		android:largeScreens="true"
		android:xlargeScreens="true"/>

	<uses-sdk
		android:minSdkVersion="17"
		android:targetSdkVersion="__APILEVEL__"/>

	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.INTERNET"/>
	<uses-permission android:name="android.permission.RECORD_AUDIO"/>
	<application
		tools:replace="android:label"
		android:name="com.tns.NativeScriptApplication"
		android:allowBackup="true"
		android:icon="@drawable/icon"
		android:label="MyAwesome App Name"
		android:theme="@style/AppTheme" >
		<activity
                   android:label="MyAwesome App"> ... </activity>
		<activity android:name="com.tns.ErrorReportActivity"/>
	</application>
</manifest>
```

As that seemed like too much hassle to go through for something as simple as changing the application name, I found that replacing the root directory's name will have an immediate effect on the name!

**Comment by NickIliev** [comment]
Hi @BitsOnCoffee - I will close this issue as resolved.(currently with v.2.1.0 changing the root dir name is an applicable solution to change your app name seamlessly.) .Please let us know if you need further assistance on that matter.
