### ISSUE TITLE
Cross-platform API for Contacts picker

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#250]
Implement cross-platform API for picking contact info from the device contact storage.

Please [vote for this feature](https://nativescript.ideas.aha.io/ideas/NS-I-41) in our ideas portal.

**Comment by vzhen** [comment]
+111111111111111111111111111

**Comment by enchev** [comment]
We have this already as a separate module:
https://github.com/NativeScript/contacts

**Comment by khadorkin** [comment]
@enchev Hi! Unfortunately repo is not available :crying_cat_face:

**Comment by hgenru** [comment]
@enchev, we need contacts plugin :crying_cat_face:

**Comment by johnmurphy01** [comment]
+1

**Comment by sitefinitysteve** [comment]
Is this still not a thing?

**Comment by firescript** [comment]
It is now :) just built a plugin: https://www.npmjs.com/package/nativescript-contacts

**Comment by NathanaelA** [comment]
@firescript - We still need android; and @enchev what ever happened to your /contacts plugin, that repo is still unavailable.

**Comment by enchev** [comment]
Yep the repo is still unfinished and private. I've checked @firescript plugin and it seems that there is code for android.

**Comment by sitefinitysteve** [comment]
@enchev I added the android after he posted this.  While it does pick and return the object I have to admit Im unsure how to extract the data from the Contract or set the projections properly
