### ISSUE TITLE
Difference in styling custom plugin in android with pure {N} and Angular{N}

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#2502]
So a few weeks ago I implemented styling support for the Drop Down widget. Since I want every view that represents an item to look as the drop down I implemented this with copying the style properties from the drop down widget to the sub views representing each item in the popup: https://github.com/PeterStaev/NativeScript-Drop-Down/blob/master/drop-down.android.ts#L216

This works perfectly in pure {N}. But with Angular{N} there are couple of problems. Assuming I have:
```xml
<DropDown #dd class="test" [items]="items"></DropDown>
```
1. If I define the style with ID like:
```css
#dd { color: yellow; }
```
It does not work. If I move this style to the class `test` it works. 
2. The `backgroundColor` property is not applied at all (all others seem to be working fine)

Why are those differences and how can they be eliminated? Am I doing something wrong, or is there something special with styling with IDs and the background in Angular{N}?

**Comment by tsonevn** [comment]
Hi @PeterStaev ,
I have just tested your plugin in a local NativeScript Angular2 project and it works as expected. However to be able to set  style using `id` you should define it like in the pure NativeScritp.

`<DropDown id="dd" class="test" [items]="items"></DropDown>`. 

`#dd` will only make local variable in the angular template.
In regard your another problem, I was able to attached background color the `DropDown` , however it seems that you should add the same background color to the layout, which is shown  when you open the  menu with all items. 

Regards,
@tsonevn

**Comment by PeterStaev** [comment]
Hey @tsonevn , thanks for the explanation! But for the 2nd problem I do not have control over the popup as this is the native Spinner popup. So most places where people asked to change the background of the popup recommend returning a custom view and setting the background there (which is exactly what the current code does). Also note that like I explained in the OP the same code works fine in plain {N} and all the sub views have the correct background (you can check this in the sample app for the DropDown), so the problem is only in the Angular{N} implementation.

**Comment by tsonevn** [comment]
Hi @PeterStaev,
Excuse me for delay in replying.
I reviewed your plugin and found what is causing this problem with applying the background color on popup. The width of the labels you are adding in the StackLayout by default is not equal to the width of the parent layout. In regard to that one possible fix could be to add the width of the label to be 100% in `_getRealizedView` method.

```
    public _getRealizedView(convertView: android.view.View, realizedViewType: RealizedViewType): View {
        if (!convertView) {
            let view = new Label();
            let layout = new StackLayout();

            view.id = LABELVIEWID;
            view.width="100%";
            layout.addChild(view);

            return layout;
        }
        
        return this._realizedItems[realizedViewType][convertView.hashCode()];
    }
```
I  hope this is applicable for you.

**Comment by tsonevn** [comment]
Hi @PeterStaev, 
I found what is causing the problem with the background. In the default template in the `app.css`  has been set `horizontal-align:center;` to the Label and StackLayout and the background color has not been set to the whole popup menu. If you remove this
```
button, label, stack-layout {
    horizontal-align: center;    
}
```
 in your project, the background color should be applied normally. Could you verify if this will solve your problem.

Regards,
@tsonevn

**Comment by PeterStaev** [comment]
Hey @tsonevn , I do not have those styles in my app. Just make things clear:
1. DropDown sample app - https://github.com/PeterStaev/NativeScript-Drop-Down/tree/master/sample - pure {N} **IS** working
2. Angular sample app - https://github.com/PeterStaev/ng-test-bed - Angular + {N} is **NOT** working. 

Both are using the same styles and the same DropDown version.

**Comment by tsonevn** [comment]
Hi @PeterStaev,
Thank you for the sample project.
However it seems that your project works as expected, when I tested on an emulator and real device. Could you verify, whether you are using latest `CLI` and `modules`. It  would help if you could give me some more info, if I should do something specific  to reproduce the problem  instead only to clone your second repo and to run the project with `tns run android`. It  would help also if you could tell me which emulator or device you are using to test your app. For your convenience I am attaching screenshot of the emulator. 
![screenshot 19](https://cloud.githubusercontent.com/assets/17448734/17239570/b2ca5bb8-556d-11e6-8a50-faaf26a3a22c.png)

Regards,
@tsonevn

**Comment by PeterStaev** [comment]
Hey @tsonevn , really strange I just deleted the folder and recloned the repo and now it is working... It must have been some old left files (since the project was previously using Angular RC1). Much thanks for your time!
