### ISSUE TITLE
NativeScript post fetch with error Unexpected end of input

### ISSUE THREAD

**Issue by calebeaires** [NativeScript/NativeScript#2504]
I have tried to make and http post to an Laravel app with the built in NativeScript fetch module, but the post cant be completed. It returns this error Error occurred SyntaxError: Unexpected end of input

The code used is

        var data = {"codes":["7898422746759"],"id_store":1};

        fetchModule.fetch("http://example.com/get-barcode", {
            method: "POST",
            headers: {
                'Accept': 'application/json,text/plain, */*',
                'Content-Type': 'application/json;charset=UTF-8;'
            },
            body: JSON.stringify(data)
        }).then(r => {
            return r.json();
        }).then(function (r) {
            console.log("response");
            console.log(JSON.stringify(r));
        }, function (e) {
            console.log("Error occurred " + e);
        });
I have tried the same http post with the same "data object" on an simple angular application. Everything works as expected here, but not on NativeScript fetch.

AngularJS test:

       var data = {"codes":["7898422746759"],"id_store":1};

       $http.post('"http://example.com/get-barcode"', data)
            .success(function (res) {

               console.log(res)

            }).error(function (err) {

               console.log(err)

            });
Here, on an angular app, the http post don`t returns error. It works nicely.

NativeScript 2.1.1

**Comment by NickIliev** [comment]
Hey @calebeaires 

I have tested your POST url with Postman and it returns 404 error page.
As this is an html page starting with < respectivvly the error is 
`JS: Error occurred SyntaxError: Unexpected token <`

However if you test your post request with a working server everything works as expected.
For example change **http://example.com/get-barcode** with **https://httpbin.org/post**

**Comment by calebeaires** [comment]
The url I have put on the question above is just an "example" url to show how I am coding on the NativeScript app. But my real NS app do a post on a real PHP app, with a real URL. **AngularJS http-post module works fine, but NS fetch post module does not, event if it is the same url**

**Comment by NickIliev** [comment]
@calebeaires 
With your exact code and with the test server (httpbin) i am receiving the following response

```
JS: response
JS: {"args":{},"data":"{\"codes\":[\"7898422746759\"],\"id_store\":1}","files":{},"form":{},"headers":{"Accept":"application/json,text/plain, */*","Accept-Encod
ing":"gzip","Content-Length":"40","Content-Type":"application/json;charset=UTF-8;","Host":"httpbin.org","User-Agent":"Dalvik/2.1.0 (Linux; U; Android 6.0; Googl
e Nexus 5X - 6.0.0 - API 23 - 1080x1920 Build/MRA58K)"},"json":{"codes":["7898422746759"],"id_store":1},"origin":"82.103.64.88","url":"https://httpbin.org/post"
}
```

**Comment by NickIliev** [comment]
Hey @calebeaires were you able to resolve your issue?

**Comment by calebeaires** [comment]
Every many try, I figure out. The return from that php app was just an "string", so It was confusing me on the console log! We can close it.

**Comment by bismert** [comment]
I'm experiencing similar issue with CodeIgniter php framework
