### ISSUE TITLE
Install creates .bash_profile if it doesn't exist on Mac

### ISSUE THREAD

**Issue by psnider** [NativeScript/NativeScript#2506]
OS: Mac El Capitan 10.11.5
tns: v2.1.1
Cross-platform modules: v2.1.0

I just installed nativescript via ```npm install -g nativescript``` but ran into a set of odd problems, which seem to have been caused by the install script creating a .bash_profile, which resulted in my .profile being skipped.

I've used .profile on Mac because many programs assume .profile.

It also appears that both the android installation and the java installation (run under the control of the nativescript install) both use .profile as well, as these two lines were added to the end of my .profile:
```
export ANDROID_HOME=/usr/local/opt/android-sdk
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home
```

I was able to resolve my issues by adding the following to the top of my .bash_profile:
```
if [ -f /Users/peter/.profile ]; then
    source /Users/peter/.profile
fi
```

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-cli#1949
