### ISSUE TITLE
tns-android-metadata-generator not available.

### ISSUE THREAD

**Issue by extns** [NativeScript/NativeScript#2507]
npm install tns-android-metadata-generator

do not work. 

> 
> npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/tns-android-metadata-generator
> npm ERR! 404
> npm ERR! 404  'tns-android-metadata-generator' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 

currently there is no way to generate metadata for external java class. please help

**Comment by Pip3r4o** [comment]
@extns The `metadata generator` fires implicitly when building your application. That means that any plugins or java libraries you have included in your project will have metadata entries generated without needing to perform any additional manual steps.

**Comment by extns** [comment]
the metadata generator is from that page, likely most of the documenation need to be rewritten
https://docs.nativescript.org/runtimes/android/metadata/generator

i need to add android inapp billing library to my project, can't locate any plugins. (it is surprised that no plugin exist, no nativescript app with inapp billing exist?!)

search google how to include other android library, it show tns library add command, but this command no more exist in current version.

now i go through the plugin documentation, there is no plugin template to download. also existing plugins do not have such directory structure, really doubt if it will work.

the document of nativescript is really bad, lack of example and templates.

the  nativescript concept is good, but it lack of critical plugins

**Comment by Pip3r4o** [comment]
Hey, @extns, we strongly encourage the community to create plugins and wrappers around native libraries to help fellow {N} developers. Don't see a plugin for functionality that you need and think could help others? Be the first to make one!

If you wish to consume a library that is available in `bintray (jcenter, maven repository, etc.)` you simply have to add it as a dependency in `app/App_Resources/Android`

And thank you for pointing out the discrepancy on the metadata/generator page!

**Comment by extns** [comment]
I want to create a plugin for this, but it do not work, so i have to give up like many others and go back to phonegap.
