### ISSUE TITLE
app start before call service

### ISSUE THREAD

**Issue by yclau** [NativeScript/NativeScript#2515]
### Tell us about the problem
I trying get data from server before application start, and using data to determine which page going to. But app will start the default first then only can run call server. Isn't can I get data from server before app start first?

**Comment by NickIliev** [comment]
Hello @yclau 

You can fetch in the application Launch event.

For example:
in your **_app.js_**
```
"use strict";
var application = require("application");

application.on(application.launchEvent, function (args) {
    if (args.android) {
        // For Android applications, args.android is an android.content.Intent class.
        console.log("Launched Android application with the following intent: " + args.android + ".");
        receiveData();
    }
    else if (args.ios !== undefined) {
        // For iOS applications, args.ios is NSDictionary (launchOptions).
        console.log("Launched iOS application with options: " + args.ios);
        receiveData();
    }
});
application.start({ moduleName: "main-page" });

function receiveData() {
    fetch("https://httpbin.org/get").then(function (r) {
        // Argument (r) is Response!
        console.log("Received");
    }, function (e) {
        // Argument (e) is Error!
        console.log("Error!");
    });
}
```

More about application events can be found in[ this article](https://docs.nativescript.org/core-concepts/application-management)

More about fetch module can be found [here](https://docs.nativescript.org/cookbook/fetch)

**Comment by yclau** [comment]
many thanks for help , it work ~
