### ISSUE TITLE
access Segmentedbar selectedIndex

### ISSUE THREAD

**Issue by mragwa** [NativeScript/NativeScript#2519]
Dears, I'm using nativescript with angular2 and trying to use SegmentedBar it works fine with me but i need to trigger the selectedIndex my HTML :

`<SegmentedBar class="tabs" [items]="items" [(ngModel)]="selectedIndex" selectedBackgroundColor="#000" (selectedIndexChanged)="SegmentChanged(selectedIndex)"  #tabs></SegmentedBar>`
and my component is:

```
selectedIndex: number;
constructor( @Inject(Page) private _page: Page){
this.selectedIndex = 0;
}
public SegmentChanged(b) {
 console.log(b) // it gives me the old value not the current value
}
```
that code gives me the old selectIndex value not the active one. i'm also tried that code snippet:
[http://www.nativescriptsnacks.com/snippets/2016/06/22/angular-segmentedbar.html](http://www.nativescriptsnacks.com/snippets/2016/06/22/angular-segmentedbar.html)  but it doesn't work for me because :

`@ViewChild("tabs") tabs: ElementRef; // console.log(this.tabs); return undefined`
If any one can help or give me an working snippet. thank you.

**Comment by tsonevn** [comment]
Hi @mragwa,
In case you want to handle  selectedIndex change event of SegmentedBar you should add id `#sg` , which will make reference of the view in angular then you should add `sg.selectedIndex` instead `selectedIndex` as argument in your `SegmentChanged` method. For example  `SegmentChanged(sg.selectedIndex)`. This will allow you to get the correct  index. YOu could also review the attached example below.

`app.component.html`

```
<StackLayout>
    <SegmentedBar #tabs [items]="items" [selectedIndex]="index" (selectedIndexChanged)="SegmentChanged(tabs.selectedIndex)">
    </SegmentedBar>
</StackLayout>
```

`app.component.ts`

```
import {Component} from "@angular/core";
import {SegmentedBarItem} from "ui/segmented-bar";

@Component({
    selector: "my-app",
    templateUrl: "app.component.html",
})
export class AppComponent {

    public index: number;
    public items: Array<SegmentedBarItem>;
    constructor() {
        this.index=0;
        this.items=[];
        for(var i=0; i<4; i++){
            var segItem= new SegmentedBarItem();
            segItem.title="Title"+i;
            this.items.push(segItem);
        }



    }
  
    public SegmentChanged(value){
        console.log("selected index "+value)
    }
}

```


Regards,
@tsonevn

**Comment by mragwa** [comment]
thanks @tsonevn it works.
