### ISSUE TITLE
setActivityCallback is not found

### ISSUE THREAD

**Issue by kazemihabib** [NativeScript/NativeScript#2523]
setActivityCallbacks is not found in frame.d.ts when but in the source of nativescript in github I found it.

### Which platform(s) does your issue occur on?
linux

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.1.1

### Please tell us how to recreate the issue in as much detail as possible.
import {setActivityCallbacks ,AndroidActivityCallbacks} from "ui/frame";
or check the "ui/frame.d.ts" after create the project

**Comment by tsonevn** [comment]
Hi @kazemihabib,

Thank you for your issue.
However this info is not enough, your scenario to be reproduced. It would help if you could give us some more info about your problem. It would also help if you could give us sample project, where your case has been recreated.

Regards,
@tsonevn

**Comment by kazemihabib** [comment]
I want to use the custom activity I followed the tutorial : https://docs.nativescript.org/runtimes/android/advanced-topics/extend-application-activity

but the ts compilers throws this error:
`Module '"ui/frame"' has no exported member 'setActivityCallbacks'.at line 1 col 9 `  for 
`import {setActivityCallbacks,AndroidActivityCallbacks} from "ui/frame";` 

so I checked the file
 '/node_modules/tns-core-modules/ui/frame/frame.d.ts`

 and I found that it's not exported there so instead I used 
`let  uiFrame = require("ui/frame");`
`uiFrame.setActivityCallbacks(this);`

I just want to tell that it's not exported there and we can not use it in the way it's mentioned in documentation.

**Comment by tsonevn** [comment]
Hi @kazemihabib,

Thank you for your reply,

At the moment this method is set as private and for that reason it is not exported in the typescript definitions. We will be fixed this in some of the next NativeScript versions. In regard to that as temporary solution you could cast this method to any and you would be allowed to use it in your project. I logged new [issue ](https://github.com/NativeScript/NativeScript/issues/2526) about this problem. You could also review the attached code snippet, where have been shown how to use suggested workaround. 

```
import * as frame from "ui/frame";


@JavaProxy("org.myApp.MainActivity")
class Activity extends android.app.Activity {
   private _callbacks: frame.AndroidActivityCallbacks;

   protected onCreate(savedInstanceState: android.os.Bundle): void {
       if (!this._callbacks) {
           (<any>frame).setActivityCallbacks(this);
       }

       this._callbacks.onCreate(this, savedInstanceState, super.onCreate);
   }
   //....
}
```

I hope this is applicable for you.
