### ISSUE TITLE
Documentation on zone callbacks and triggering change detection on background operations

### ISSUE THREAD

**Issue by giovannicandido** [NativeScript/NativeScript#2524]
Hi,

The databind engine together with observables and background async process is a natural combination in the browser, but in mobile has specifics behaviors that make it difficult to grasp.

For example this question in stackoverflow: 

http://stackoverflow.com/questions/38525271/nativescript-binded-property-in-view-is-not-updated-when-the-model-is-set-in-p

Is related with a problem I'm current having.

First one simplified working example:

```
import {Observable, Subject} from 'rxjs';
export class AppComponent {
   message = new Subject<string>();
   public connect(){
        public connect() {
        let count = 0
        setInterval(() => {
            
            this.onStatusChange("yes " + count++)
                
        }, 1000)
    }

   public onStatusChange(message: string){
        console.log(message);
        this.status.next(message)
    }

   public sendMessage(){
   }
}
```

```
<StackLayout>
    <Button text="Connect" (tap)="connect()"></Button>
    <Button text="Send Message" (tap)="sendMessage()"></Button>
    <Label [text]="status | async" class="message" textWrap="true"></Label>
</StackLayout>
```

I'm using typescript with Angular2, but it should be reproduced in any combination.

Now to the problem. Let's change that code to a background code. I'm creating a plugin to abstract the ably.io pub/sub library, so the real code is more complex

But essentially we change to that:

```
import {Observable, Subject} from 'rxjs';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/do';
export class AppComponent {
   message = new Subject<string>();
   public connect(){
        public connect() {
        this.ably = new AblyRealtime(this.key)

        let channel = this.ably.channels.get(this.channelId)

        channel.subscribe()
            .map(m => m.data)
            .do((m) => console.log(m))
            .subscribe(m => this.onMessage(m))

        this.ably.connection.on().subscribe(c => this.onStatusChange(c.current))
    }

   public onStatusChange(message: string){
        console.log(message);
        this.status.next(message)
    }

   public sendMessage(){
   }
}
```

The behavior is 

1. The console.log message is displayed.
2. The message is not updated

Now click on sendMessage button which do nothing, but update the UI thread, and the message is displayed.

What I think is happening:

1. Ably library is running in background (obviously :-)
2. The observable is changed outside the context of the UIThread
3. Since angular databind do not trigger the change outside the UIThread the message is not updated
4. User interactive triggers the angular check cycle, which in turn, triggers the update

So, my reason tell's me that I need to update the UIThread. In android one way to do it is the `runOnUiThread(Runnable action)` Activity Method. I do not find a way to access the current activity on Nativescript, but I find that Nativescript already run on the context of the UIThread. So I'm confused.

I don't think it is a bug, should it be?
One way to clarify this, is with a documentation that explains this behavior and:

1. Explain the use of Observables and Promises with Nativescript
2. Explain what to do, to update the UIThread, if necessary
3. How the background http plugin works (https://plugins.telerik.com/nativescript/plugin/background-http). In particular how the events are updated in the UI `task.on("progress", logEvent);`
4. Explains how the angular http works (or the framework http)

I guess a documentation on that should benefit everyone 

Use cases:

* Progress bar
* Background tasks
* Publisher/Subscriber communication
* Mobile Push
* Any dynamic Async process (short or long running) that needs to update the UI using databind (or not)

Thank you.

**Comment by hdeshev** [comment]
@giovannicandido my guess here is that you are running into a zone issue. I'm not familiar with the Ably library, but it probably runs its event handlers outside of the Angular zone. That is fine most of the time, but it will not trigger a change detection run.

Try injecting a NgZone instance in your component and wrapping your event handler in a `zone.run(() => ...);` block as described in [this article](http://blog.thoughtram.io/angular/2016/02/01/zones-in-angular-2.html)

I agree that we should add a documentation article about that. I'll rename this issue.

**Comment by giovannicandido** [comment]
@hdeshev Nice article. Zone do the trick
