### ISSUE TITLE
Customizing TabView with logo & header color

### ISSUE THREAD

**Issue by hany-andriyanto** [NativeScript/NativeScript#2525]
Hallo,
I am new in NativeScript, my question is, I have following code below 
```<Page>
 <TabView style="background-color:black" selectedColor="#50B85D" marginTop="20">
   <TabView.items>
     <TabViewItem title="Tab1" backgroundColor="black">
       <TabViewItem.view>
          <Label text="Label in Tab1" />
       </TabViewItem.view>
     </TabViewItem>
     <TabViewItem title="Tab2">
       <TabViewItem.view>
          <Label text="History" />
       </TabViewItem.view>
     </TabViewItem>
   </TabView.items>
 </TabView>
</Page>
```
How to customize nativescript's tab-view to changing title app text with image logo, header color and mixing Uppercase & Lowercase (default: Uppercase) ?

Thank You..

**Comment by tsonevn** [comment]
Hi @hany-andriyanto ,

Cuold you provied some more info for your problem. However if  you to set custom title you could use in your app using [ActionBar](https://docs.nativescript.org/ui/action-bar#how-to-create-custom-title-view-instead-of-the-actionbar-title). You could review the attached sample code.
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">

<Page.actionBar>
    <ActionBar title="Title" icon="">
       <StackLayout orientation="horizontal"
        ios:horizontalAlignment="center"
        android:horizontalAlignment="left">
        <Label text="sample title" color="red" class="action-label"></Label>
      </StackLayout>
    </ActionBar>
</Page.actionBar>

</Page>
```

In case you want to set icons instead text in the `TabView` tabs you could review [this ](https://docs.nativescript.org/ui/icon-fonts) article, where have been described, how to use `Icon Fonts`. 
You could also use  [StackOverflow ](http://stackoverflow.com/questions/tagged/nativescript) for further questions
I hope this is applicable for you

**Comment by hany-andriyanto** [comment]
Thank you @tsoneven, ,my question have been answered,so i combine with Actionbar 

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
<Page.actionBar>
    <ActionBar title="Title" icon="">
       <StackLayout orientation="horizontal"
        ios:horizontalAlignment="center"
        android:horizontalAlignment="center">
        <Label text="sample title" color="red" class="action-label"></Label>
      </StackLayout>
    </ActionBar>
</Page.actionBar>
<TabView>
<TabView.items>
     <TabViewItem title="Tab 1" backgroundColor="black">
       <TabViewItem.view>
          <Label text="Label in Tab1" />
       </TabViewItem.view>
     </TabViewItem>
     <TabViewItem title="Tab2">
       <TabViewItem.view>
          <Label text="History" />
       </TabViewItem.view>
     </TabViewItem>
   </TabView.items>
   </TabView>
</Page>
```
But how to make text of TabView item from Uppercase like "TAB1" to "Tab1?"

**Comment by tsonevn** [comment]
Hi  @hany-andriyanto,
I am sorry for delay in reply.

At the moment to make titles with lower case letter you should use native code. You could review below attached example, where have been shown how to do that.

`main-page.xml`

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <StackLayout>
    <TabView id="tabViewContainer" loaded="onTabViewLoaded" >
        <TabView.items>
            <TabViewItem title="Tab 1">
                <TabViewItem.view>
                    <Label text="This is Label in Tab 1" />
                </TabViewItem.view>
            </TabViewItem>
            <TabViewItem title="Tab 2">
                <TabViewItem.view>
                    <Label text="This is Label in Tab 2" />
                </TabViewItem.view>
            </TabViewItem>
        </TabView.items>
    </TabView>
    
  </StackLayout>
</Page>
```

`main-page.ts`

```
import { EventData } from "data/observable";
import { Page } from "ui/page";
import { TabView } from "ui/tab-view";
import {isAndroid} from "platform"

var page:Page;

export function navigatingTo(args: EventData) {
    page = <Page>args.object;
}

export function onTabViewLoaded(){
    if(isAndroid){
        var tabview:TabView =<TabView> page.getViewById("tabViewContainer");
        var tab = (<any>tabview)._getAndroidTabView();
        
        for (var i = 0; i < tabview.items.length; i++) {
            tab.getTextViewForItemAt(i).setAllCaps(false);
        }
    }
}
```


In regard to that I have created new [feature request](https://github.com/NativeScript/NativeScript/issues/2551) and such a functionality could be available in some of the next NativaScript versions.


I hope that this workaround will help you.

**Comment by HeidiHansen** [comment]
How to do this in ObjC?  `displaysUppercaseTitles = NO;` doesn't work.

**Comment by Irvinhoe** [comment]
Hi, is there a workaround for this in regular html?

**Comment by tsonevn** [comment]
Hi @HeidiHansen,
I make a little research for iOS, however, at this time there is no way to setup programmatically the capitalization of the text. Bear in mind that if the title text is entered with all lowercase letters this capitalization will be transferred in the same way inside the application.

@Irvinhoe you could used the same approche for Android in NativeScript Anguler project as it is shown below. You could use tabview loaded event and to make the same changes for every tab.
