### ISSUE TITLE
To expose setActivityCallbacks method in `frame.d.ts`

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#2526]
`setActivityCallbacks` method has been added in private section and it is not exposed in `frame.d.ts`. 
This method has been used in one of our [examples](https://docs.nativescript.org/runtimes/android/advanced-topics/extend-application-activity#extending-activity) for using custom activity.

**Comment by sitefinitysteve** [comment]
Could maybe maybe just quickly export this dude for 2.3?

**Comment by sitefinitysteve** [comment]
Is this... live\working atm?  

Reference: https://github.com/sitefinitysteve/nativescript-auth0/blob/master/demo/app/activity.android.ts#L9

If I remove the "hack" in 2.4, I just get undefined errors...
