### ISSUE TITLE
does it support browseryfy.

### ISSUE THREAD

**Issue by frndxyz** [NativeScript/NativeScript#2529]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

**Comment by NickIliev** [comment]
Hey @frndxyz 

No official support but still you can check the following threads where usage of browserify in NativeScript is discussed

[https://github.com/NativeScript/nativescript-cli/issues/362#issuecomment-126611339](https://github.com/NativeScript/nativescript-cli/issues/362#issuecomment-126611339)

[https://github.com/NativeScript/NativeScript/issues/195#issuecomment-174353311](https://github.com/NativeScript/NativeScript/issues/195#issuecomment-174353311)
