### ISSUE TITLE
Theming support

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#253]
Implement support for themes - ability to stylize the UI to meet specific branding requirements and _not_ rely on the native look and feel.

*If you are interested in this feature __please add comments below__ with specific requirements and [vote for this feature](https://nativescript.ideas.aha.io/ideas/NS-I-39) in our ideas portal.*

**Comment by alejonext** [comment]
I was thinking that myself ... And if there is `.css`, you can build templates.

**Comment by dbbk** [comment]
I'm not quite sure how this differs from the existing CSS styling feature, can you expand?

**Comment by RangerMauve** [comment]
I second what @dbbk said. Isn't theming already done via custom CSS styles?

**Comment by valentinstoychev** [comment]
Sometimes CSS styling is not enough to achieve a certain look and feel. The scenario here is a company-branded application which "requires" the same look and feel on iOS and Android and *avoiding* the native-specific look and feel. This can be done in part with CSS, but the UI component templates needs to be updated to look and behave in the same way on both platforms.

Does this makes sense?

**Comment by alejonext** [comment]
It would be something like

* Themes ( native-specific ) 
* Custom ( `.css` )

Thus, it would be much better, and the number of files in css would be much lower.

**Comment by chadcampbell** [comment]
I also believe theming would be a valuable addition. Other frameworks provide themes that deliver apps that look the same whether they are running on Android or iOS. Sometimes developers need apps that are consistent with the operating system (which is what NativeScript does today). Other times, developers need to create apps that look/behave the same regardless of which operating system the app is running on (this would be achievable with themes).

**Comment by paranoid-android** [comment]
I would love to see [Material Design](https://github.com/NativeScript/NativeScript/issues/399) as a theme for NativeScript.

**Comment by amjd** [comment]
Any update on this? Is this planned for any future releases?

**Comment by enchev** [comment]
Closed in favor of: https://github.com/NativeScript/NativeScript/issues/1763
