### ISSUE TITLE
Full screen navigation

### ISSUE THREAD

**Issue by jorendemaeyer1996** [NativeScript/NativeScript#2532]
Is there a way to create a full screen navigation like [this](
https://codepen.io/PaulVanO/pen/XJYGNQ)?

**Comment by NickIliev** [comment]
Hello @jorendemaeyer1996 

Yes, this is a common case and you can refer to [this section of our documentation](https://docs.nativescript.org/ui/action-bar#creating-slidedrawer-button) for one possible solution.
You can also check [nativescript-telerik-ui ](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/SideDrawer/overview)side-drawer which can be combined with a drawer button.
