### ISSUE TITLE
Get started is unavailable

### ISSUE THREAD

**Issue by marciovicente** [NativeScript/NativeScript#2533]
Ok, I don't know exactly what's happening but when I click in `Get started` button, I have been redirected for a 404 page. Look the flow below:

![native-script](https://cloud.githubusercontent.com/assets/1021901/17259915/078a0758-55a4-11e6-9f72-017d43681c95.gif)

**Comment by traktraktrugui** [comment]
They were publishing a new version of documentation.

**Comment by tsonevn** [comment]
[Getting Started](http://docs.nativescript.org/angular/start/introduction.html)  project has been already available
