### ISSUE TITLE
where RouterExtensions?

### ISSUE THREAD

**Issue by peirancao** [NativeScript/NativeScript#2534]
https://docs.nativescript.org/angular/core-concepts/navigation-angular.html#navigation-options

**Comment by tsonevn** [comment]
Hi @peirancao, 

Could you provide some more info about your problem. It would also help if you could give me some sample project. 

Regards,
@tsonevn

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#381

**Comment by diegomelo182** [comment]
I'm found "RouterExtensions" on "nativescript-angular/router", look this code:

``` typescript
import {RouterExtensions} from "nativescript-angular/router";

export class YourComponent {
	public constructor (private routerExtensions: RouterExtensions) {
		this.page.actionBarHidden = true;
	}
}
```
