### ISSUE TITLE
file not found error!!!

### ISSUE THREAD

**Issue by peirancao** [NativeScript/NativeScript#2535]
```
  .
└── Ruiui
    ├── app
    │   └── components
    │   └── shared
    │   └──fonts
    ├──app.css
    ├──app.component.ts
    ├── node_modules
    │   └── tns-core-modules
    ├── package.json
    └── platforms
        ├── android
        └── ios
```

shared/tab-bar/tab-bar.component.ts
shared/tab-bar/tab-bar.component.html
```
import { Component } from '@angular/core';

@Component({
  selector: 'tab-bar',
  templateUrl : `tab-bar.component.html`
})

export class TabBarComponent {

  constructor() {

  }
}
```

`
error: File /data/data/org.nativescript.Ruirui/files/app/tab-bar.component.html does not exist. Resolved from: tab-bar.component.html.                                                           JS:     at FileSystemXHR.get (/data/data/org.nativescript.Ruirui/files/app/tns_modules/nativescript-angular/http/xhr.js:22:19)                                                                       JS:     at DirectiveNormalizer.normalizeTemplate (/data/data/org.nativescript.Ruirui/files/app/tns_modules/@angular/compiler/src/directive_normalizer.js:53:30)                                      JS:     at DirectiveNormalizer.normalizeDirective (/data/data/org.nativescript.Ruirui/files/app/tns_modules/@angular/compiler/src/directive_normalizer.js:26:21)                                     JS:     at /data/data/org.nativescript.Ruirui/files/app/tns_modules/@angular/compiler/src/runtime_compiler.js:65:147                                                                                 JS:     at Array.map (native)                                                                                                                                                                        JS:     at RuntimeCompiler._loadAndCompileComponent (/data/data/org.nativescript.Ruirui/files/app/tns_modules/@angular/compiler/src/runtime_compiler.js:65:89)                                       JS:     at /data/data/org.nativescript.Ruirui/files/app/tns_modules/@angular/compiler/src/runtime_compiler.js:88:35                                                                                  JS:     at Array.forEach (native)                                                                                                                                                                    JS:     at RuntimeCompiler._compileComponent (/data/data/org.nativescript.Ruirui/files/app/tns_modules/@angular/compiler/src/runtime_compiler.js:81:36)                                              JS:     at /data/data/org.nativescript.Ruirui/files/app/tns_modules/@angular/compiler/src/runtime_compiler.js:71:49
`

**Comment by triniwiz** [comment]
Try 
```
import { Component } from '@angular/core';

@Component({
moduleId: module.id,
  selector: 'tab-bar',
  templateUrl : `tab-bar.component.html`
})

export class TabBarComponent {

  constructor() {

  }
```

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#382
