### ISSUE TITLE
Issue with HTTP POST

### ISSUE THREAD

**Issue by zeeshanjan82** [NativeScript/NativeScript#2536]
I am working on building an mobile application using angular2-advanced-seed project which is using NativeScript and Angular2. I am using GennyMotion to test on an android device. I am also making use of the libraries like ngrx/store, ngrx/effects and angualr2 router.

I have implemented a simple login screen which takes in the username/password and then redirects users to the dashboard screen if the username/password is correct. This feature is working fine on the angualr2 web app but when I try to run it in the Android Emulator for NativeScript app I get the following error:

https://github.com/NathanWalker/angular2-seed-advanced/issues/185

**Comment by zeeshanjan82** [comment]
I am not sure if this is because my node.js backend service is running on differnet IP Address and the android app inside the Geny Emulator is running on different IP Address?

**Comment by triniwiz** [comment]
Since it is genymotion you are using set your server ip to `192.168.56.1` on your device

**Comment by NickIliev** [comment]
Hey @zeeshanjan82 

I saw you have opened[ the same issue ](https://github.com/NathanWalker/angular2-seed-advanced/issues/185)in the plugin's repository so I will close this one as a duplicate
There are also some possible solutions mentioned by the author of the plugin so you can check them out for your scenario.
