### ISSUE TITLE
Tag 2.1.0 release in github repository

### ISSUE THREAD

**Issue by mnahkies** [NativeScript/NativeScript#2537]
Could the commit that `tns-core-modules@2.1.0` was built from please be tagged and added to the list of github releases as the previous releases were?

Currently the closest thing I can find to a definite definition of where this release was built from is the release date, however multiple commits were made that date, many failing CI and so I have no idea where it was actually built from.

This is an issue as it make it difficult to identify what changes have been made since the last stable release, and to find a stable revision to test possible contributions on (if I run a build made from the current head of master I get many crashes that weren't present on 2.0.1 at least, that I assume are due to the in progress nature of the branch).

Ref:
https://github.com/NativeScript/NativeScript/tags
https://github.com/NativeScript/NativeScript/releases

**Comment by NickIliev** [comment]
Hey @mnahkies than you for reporting the issue - we will look into that! 
Meanwhile, you can check the latest release notes from [here](https://github.com/NativeScript/NativeScript/blob/master/CHANGELOG.md)

**Comment by NickIliev** [comment]
@mnahkies 
Tags and Release notes are now updated
[https://github.com/NativeScript/NativeScript/tags](https://github.com/NativeScript/NativeScript/tags)
[https://github.com/NativeScript/NativeScript/releases](https://github.com/NativeScript/NativeScript/releases)
