### ISSUE TITLE
Cannot target es2015/es6 to use async/await

### ISSUE THREAD

**Issue by alexrainman** [NativeScript/NativeScript#2541]
When i change target to es2015/es6 in tsconfig.json i get lot of errors

```
node_modules/typescript/lib/lib.es6.d.ts(1342,16): error TS2314: Generic type 'Promise<T, R>' requires 2 type argument(s)
```

I also tried this tutorial without luck: https://www.nativescript.org/blog/details/using-babel-in-nativescript-apps

Any ideas?

**Comment by hdeshev** [comment]
Hi @alexrainman,

This error is caused by a clash in the `es6-promise.d.ts` that NativeScript brings along and the TypeScript `lib.es6.d.ts` typings. We ship a separate ES6 typing that you need to reference in your `references.d.ts` -- `tns-core-modules.es6.d.ts`, and it should have be configured for ES6 builds.

Well, reality kicked in, and it seems we'd introduced public types that return promises, but are defined as using a promise-like interface type - `Thenable<T>`. You can work around that by aliasing the `Thenable<T>` type to `PromiseLike<T>`. The full `references.d.ts` file should now look like:

```TypeScript
/// <reference path="./node_modules/tns-core-modules/tns-core-modules.es6.d.ts" /> Needed for autocompletion and compilation.
declare type Thenable<T> = PromiseLike<T>;
```

Full demo project available [here](https://github.com/hdeshev/tns-ts-es2015-demo).

//cc @NickIliev

**Comment by alexrainman** [comment]
@hdeshev this is cool, but as i am developing a plugin, i need other lines in my references files

```
/// <reference path="./node_modules/tns-core-modules/tns-core-modules.es6.d.ts" /> Needed for autocompletion and compilation.
/// <reference path="./node_modules/tns-platform-declarations/ios.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/android17.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/org.nativescript.widgets.d.ts" />
declare type Thenable<T> = PromiseLike<T>;
```

The project compiles, but i get exception. First it was showing that (android) namespace cannot be found and now i get this

```
Error: Trying to link invalid 'this' to a Java object
```

Any ideas?

Something else, my plugin will need async/await from es6. Will this be available by default in {N} anytime soon?

Thanks

**Comment by hdeshev** [comment]
@alexrainman Your references.d.ts file looks OK. I can't say much about the `this` error without reproducing it on my end though. Do you have a project somewhere on github?

**Comment by alexrainman** [comment]
Will invite you to a private repository later on. Thanks

**Comment by enchev** [comment]
Hey @alexrainman @hdeshev is this still an issue?

**Comment by alexrainman** [comment]
@enchev yes it is. I will need to wait until async/await is supported by default in {N} without me needing to do some crazy configurations :)

I want to ship a plugin that everybody can install and use without conplications.

Thanks for the support.

**Comment by alexrainman** [comment]
When will * / yield be supported by default in N?

**Comment by alexrainman** [comment]
@enchev can anyone explain me whats the workflow to create UI plugins? I tried multiple times without luck, theres always something missing or no matching with the rest. I need to add declarations packages and that break the rest of the stuff. I also need the latest typescript support for async/await and it doesnt work neither. Help please.

**Comment by NickIliev** [comment]
Hey @alexrainman 

We have an article that covers the creation of UI Plugins in NativeScript.
You can find it at the following link: [https://docs.nativescript.org/plugins/ui-plugin](https://docs.nativescript.org/plugins/ui-plugin)

As for the adding of the declaration files - the workflow for tns-platform-declarations will change with 2.4.0 when you can use [this](https://github.com/NativeScript/NativeScript/tree/master/tns-platform-declarations) but as of this moment you can use the following workflow to enable the declarations files.

- in your package.json use the following version as a dependency
```    
"tns-platform-declarations": "2.2.0"
```

in your references.d.ts file add the following: 
```
/// <reference path="./node_modules/tns-platform-declarations/tns-core-modules/android17.d.ts" /> 
/// <reference path="./node_modules/tns-platform-declarations/tns-core-modules/ios.d.ts" /> 
/// <reference path="./node_modules/tns-platform-declarations/tns-core-modules/org.nativescript.widgets.d.ts" /> 

```

remove your node_modules and rebuild your project and your declarations will be enabled.

**Comment by NickIliev** [comment]
Update:
You can  also use the **next** tns-platform-declarations the following way:

in your **package json**
```
"tns-core-modules": "next",
"tns-platform-declarations": "next" // as this will be officialy applied in 2.4.0
```

**tsconfig.json**
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "lib": [
            "es2016"
        ]
    }
}
```

delete the current content of **references.d.ts** and lace the following
```
/// <reference path="./node_modules/tns-core-modules/tns-core-modules.es2016.d.ts" />

/// <reference path="./node_modules/tns-platform-declarations/ios.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/android.d.ts" />
```

**Comment by alexrainman** [comment]
@NickIliev the UI tutorial is clear for me, the problem was the declarations package version. Now im using 2.2.0 with latest typescript dev for async/await and everything works like a charm. Will be shipping a long awaited plugin soon. Thanks

**Comment by kt215** [comment]
With NativeScript 2.5.0, I can target es5 and use async-await.

The only issue I had was that `noEmitHelpers` compiler setting had to be `false`, otherwise I get one of these errors when I click a button that calls an async method:

  `
  W/System.err(23769): 	at com.tns.Runtime.callJSMethodNative(Native Method)
  `
or
  `
  __awaiter is not defined
  `
