### ISSUE TITLE
Intermittent java events on webview

### ISSUE THREAD

**Issue by davistan** [NativeScript/NativeScript#2542]
Platform: Android 5.0 (Asus Zenfone 2)
Nativescript:
* CLI: 2.1.1
* Core Modules: 2.1.0
* tns-android: 2.1.1

plugins:
* nativescript-telerik-ui: ^1.2.0
* nativescript-webview-interface: ^1.3.0

-----

Hi guys, I'm using [nativescript-webview-interface](https://github.com/shripalsoni04/nativescript-webview-interface) to integrate between webview javascript and NS.

Running on my device, the webview's emit is not triggered on NS's callback.

I've debug my app and [this function](https://github.com/shripalsoni04/nativescript-webview-interface/blob/master/index.android.js#L13) does not fires.

This is weird as the issue is intermittent, meaning that running the app 5 times, perhaps there's 1 time it will work as expected.

It feels like some race conditions (timing) that causes this.

A related to issue in https://github.com/shripalsoni04/nativescript-webview-interface/issues/4

**Comment by NickIliev** [comment]
This issue was moved to shripalsoni04/nativescript-webview-interface#5
