### ISSUE TITLE
Can't reassign back value when textchange event Textfield component

### ISSUE THREAD

**Issue by yclau** [NativeScript/NativeScript#2545]
## Please, provide the details below:
I trying doing textchange event in the textfield , it work using this link(http://stackoverflow.com/questions/30485879/basic-blur-event-in-a-telerik-nativescript-mobile-app) but after I using the value doing checking and set back the value , it doesn't work. 

### Which platform(s) does your issue occur on?
Both

**Comment by tsonevn** [comment]
Hi @yclau,

I review your scenario and  it looks that `proeprtyChange` event works as expected. However the given information is not enough to provide further help for your problem. It would help if you could give me  some more info for your issue or to provide sample project, which could be debug locally. You could also review the below attached sample project.


`main-page.xml`

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <StackLayout>
  <Label text="{{labeltext}}" textWrap="true" />
  
    <TextField id="tf" hint="Enter something" text="{{ text }}" />
  </StackLayout>
</Page>
```

`main-page.ts`
```
import { EventData } from "data/observable";
import { Page } from "ui/page";
import { HelloWorldModel } from "./main-view-model";
import {TextField} from "ui/text-field"
import {Observable, PropertyChangeData} from "data/observable"

var textField:TextField;
// Event handler for Page "navigatingTo" event attached in main-page.xml
export function navigatingTo(args: EventData) {
    // Get the event sender
    var page = <Page>args.object;
    textField = <TextField>page.getViewById("tf");
    var observable = new Observable();
    observable.set("text", "");
    observable.set("labeltext", "Sample label text")
    observable.on(Observable.propertyChangeEvent, function (event:PropertyChangeData) {
        console.log('The object changed!');
        console.log('Event:        ' + event.eventName);
        console.log('propertyName: ' + event.propertyName);
        console.log('New value:     ' + event.value);
        console.log('');
        observable.set("labeltext", event.value);



    });
    page.bindingContext =observable;
}
```


Regards,
@tsonevn

**Comment by yclau** [comment]
I trying using textField component to bind it. Same like below code.

```
export function navigatingTo(args: EventData) {
    // Get the event sender
    var page = <Page>args.object;
    textField = <TextField>page.getViewById("tf");
    var observable = new Observable();
    observable.set("text", "");
    observable.set("labeltext", "Sample label text")
    textField.on(Observable.propertyChangeEvent, function (event:PropertyChangeData) {
        textField.text = 0;
    });
    page.bindingContext =observable;
}
```

**Comment by NickIliev** [comment]
Hey @yclau 

What you are trying to do is in contradiction with itself... 
You are trying to reset the "text" property in the moment the "text" property is changed.
If this worked as expected the user won't be able to enter a new value for the textField as the value will be reset to "0" when propertyChangeEvent is raised (each time when users types new symbol). 

Also, it will cause a loop n which you are changing the text >> propertyChangeEvent is raised.. in which you are again changing the text >> propertyChangeEvent is raised in which you are again changing the text>> and on and on as your eventListener would trigger by itself.
... so this is why it won't work as you tried.

A better scenario is to have an independent control to reset the value which will be more user-friendly.
Something like a "X" or "Reset value" on which you can handle this and/or other elements to be reset.

**Comment by tsonevn** [comment]
Hi @yclau ,

I reviewed the given code, however it is not possible to update the TextField text property inside  the `on` method   in case the property of the TextField has been bind.  In regard to that you could use [nativescript-maskedinput](https://www.npmjs.com/package/nativescript-maskedinput) plugin to specify input format. This plugin would help you to validate the input and  set the formate  you want.

At this point, it would help, if you could  give me more info  about your scenario.

Regards.
@tsonevn
