### ISSUE TITLE
Question: How to detect if "onLaunch" event has already fired.

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#2548]
## Please, provide the details below:
Basically working on a plugin that can be put into the app.js before app start or much later in the application startup.  If it is put into the app.js; then I need to tie onto the application.onLaunch event.  However, if they put it later in the app; then it can run fine.    Is there some easy way to detect if the app is far enough booted that the launch event has already fired?

### Did you verify this is a real problem by searching 
yes

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
2.1

**Comment by markosko** [comment]
@NathanaelA 
more like workaround for android can be like this and something similar for ios can be done too

took from firebase source code
```javascript
plugin.newFunction = function (arg) {
  return new Promise(function (resolve, reject) {

    function _resolve() {
        /*code here for function to do*/
    };
    try {
      //if its after launchEvent
      if (appModule.android.foregroundActivity) {
        _resolve();
      } else {
        // if this is called before application.start() wait for the event to fire
        appModule.on(appModule.launchEvent, _resolve);      
      }
    } catch (ex) {
      console.log("Error: " + ex);
      reject(ex);
    }
  });
};
```

**Comment by NathanaelA** [comment]
@markosko - Thanks!    I was hoping I wouldn't have to resort to hacks.  ;-)      Yeah, I was checking a different value to see if it has booted; but that one actually might be better...

**Comment by markosko** [comment]
or u can use on launch event and exit for saving parameter maybe like init function :D so not sure which way is more hacky
```javascript
application.on(application.launchEvent,function(args){
    applicationSettings.setString("isLaunched","true")
});
application.on(application.exitEvent,function(args){
    //set as false or delete 
    applicationSettings.setString("isLaunched","false")
});
```
then u can use getString from application-settings and if true u can call without on launchEvent and if not then call on launch

**Comment by NathanaelA** [comment]
By the time *you* (the developer using my plugin) calls my plugin; the app might be launched already; which means that code won't work properly -- basically was trying to see if there was a easy supported way to detect if already launched so I can decide when to initialize the plugin.   It would be nice if there was a global property; `application.isLaunched()` or something like that to detect if the launch already happened.   But I can use a hack... ;-)
