### ISSUE TITLE
[iOS] How to import QuartzCore?

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#2550]
I am trying to natively add an UIView/UIImageView with a border. Apparently borders require QuartzCore or else the view renders blank.

Adding this to a UIImageView will render it blank:

```
imageView.layer.setBorderWidth(2.0);
imageView.layer.setBorderColor(UIColor.redColor());
```

And if I remove those lines, the UIImageView comes back. Probably due to QuartzCore not being imported as framework?

**Comment by tsonevn** [comment]
Hi @NordlingArt,
I reviewed your scenario, however in case you want to set border you could use borderWidth and borderColor properties of the NativeScript Image component. You could review the sample code below.
```
 <GridLayout rows="70" columns="70">
    <Image row="0" col="0"  borderColor="green" borderWidth="2"  src="~/file/icon-76.png" stretch ="none" />
  </GridLayout>
```
I regard to that it would help if you could give me some more info about problem.

Regards,
@tsonevn

**Comment by NordlingArt** [comment]
@tsonevn - I know about that already. Problem is that I am writing a native function that creates a view to the superview above all {N} elements. Therefore I need to do this natively.

**Comment by tsonevn** [comment]
Hi @NordlingArt 

In case you want to use native code to add border to the image you should use borderWidth and borderColor instead  `setBorderWidth` and  `setBorderColor`. You could review my  sample code below. 

`main-page.xml`

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" loaded="onPageLoaded">
  <GridLayout rows="100 70" columns="100">
    <Image id="sampleImage" width="90" loaded="imageloaded" row="0" col="0" src="~/file/icon-76.png" stretch ="none" />
    <TextField id="myTextField" hint="" text="sample text" row="1" col="0" />
    
  </GridLayout>
</Page>
```

`main-page.ts`

```
import { EventData } from "data/observable";
import { Page } from "ui/page";
import { HelloWorldModel } from "./main-view-model";
import { Image } from "ui/image";
import {isIOS} from "platform";
import {Color} from "color"

// Event handler for Page "navigatingTo" event attached in main-page.xml
var page:Page;

export function onPageLoaded(args: EventData){
page = <Page>args.object;


 if(isIOS){
    let myTextField = page.getViewById('myTextField');
    myTextField.ios.layer.masksToBounds = false;
    myTextField.ios.layer.shadowOpacity = 1.0;
    myTextField.ios.layer.shadowRadius = 0.0;
    myTextField.ios.layer.shadowColor = new Color('#000000').ios.CGColor;
    myTextField.ios.layer.shadowOffset = CGSizeMake(2.0, 2.0);
 }
    page.bindingContext = new HelloWorldModel();
}

export function imageloaded(args:EventData){
    console.log(args.object);
       //var tmpImage:Image =<Image> page.getViewById("sampleImage");
       let tmpImage:Image =<Image> args.object;
    var newColor = new Color("#ff0000");
    if(isIOS){
        console.log("inside the method");
        console.log(tmpImage.ios.layer.borderColor);
        //tmpImage.ios.clipsToBounds =true;
        tmpImage.ios.layer.borderWidth = 3.0;
        tmpImage.ios.layer.borderColor = new Color('#000000').ios.CGColor;
    }
```

In regard  to your second problem about the text-shadows, I found that possible solution has been given in this [issue](https://github.com/NativeScript/NativeScript/issues/550). You could review , the given example in the issue.


I hope this helps

**Comment by sitefinitysteve** [comment]
@NordlingArt Use tns debug to inspect the objects when you encounter stuff like this, the ObjC->Js isn't 1:1.  Like the code sample\docs say setBorderWidth but when you debug it's shortened to borderWidth in {N}

http://docs.nativescript.org/runtimes/ios/marshalling/Marshalling-Overview
