### ISSUE TITLE
Feature: TabView's Tab titles with lower case letters for Android

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#2551]
At the moment titles in the TabView's tab are always  uppercase and we do not have  property that could allow the letters to be lower case.
At the moment:
![screenshot 21](https://cloud.githubusercontent.com/assets/17448734/17435643/e6638e1a-5b1a-11e6-82ee-0c23b92da88d.png)

Possible workaround is to use native code and to set `setAllCaps` to false for every tab. I am attaching sample code, how to use this workaround.

`main-page.xml`

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <StackLayout>
    <TabView id="tabViewContainer" loaded="onTabViewLoaded" >
        <TabView.items>
            <TabViewItem title="Tab 1">
                <TabViewItem.view>
                    <Label text="This is Label in Tab 1" />
                </TabViewItem.view>
            </TabViewItem>
            <TabViewItem title="Tab 2">
                <TabViewItem.view>
                    <Label text="This is Label in Tab 2" />
                </TabViewItem.view>
            </TabViewItem>
        </TabView.items>
    </TabView>

  </StackLayout>
</Page>
```

`main-page.ts`

```
import { EventData } from "data/observable";
import { Page } from "ui/page";
import { TabView } from "ui/tab-view";
import {isAndroid} from "platform"

var page:Page;

export function navigatingTo(args: EventData) {
    page = <Page>args.object;
}

export function onTabViewLoaded(){
    if(isAndroid){
        var tabview:TabView =<TabView> page.getViewById("tabViewContainer");
        var tab = (<any>tabview)._getAndroidTabView();

        for (var i = 0; i < tabview.items.length; i++) {
            tab.getTextViewForItemAt(i).setAllCaps(false);
        }
    }
}
```

Result:
![screenshot 22](https://cloud.githubusercontent.com/assets/17448734/17435717/4a64b916-5b1b-11e6-9bdb-a64e9d1f5d5a.png)

**Comment by vjoao** [comment]
Just a reminder that caps are on par with the Material Design Specification. I'd like to have an option to disable them, though.

**Comment by MartoYankov** [comment]
It seems this was implemented a while ago in this PR https://github.com/NativeScript/NativeScript/pull/3891.

Basically, the `TabViewItem` has a property `textTransform` and a corresponding CSS rule `text-transform`  that do the trick. It's not the best solution, since this CSS rule is not inherited, but it works.

There is a proposed change in this issue https://github.com/NativeScript/NativeScript/issues/5803 to make `text-transform` inherited and introduce `tab-text-transform`.
