### ISSUE TITLE
Cannot read property 'getWidth' of null when saveToGallery=true

### ISSUE THREAD

**Issue by Daxito** [NativeScript/NativeScript#2553]
### Did you verify this is a real problem by searching
Yes, could not find an answer

### Tell us about the problem
I get an error when taking a picture and passing in the parameter saveToGallery = true
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=3453, result=-1, data=null} to activity {com.pantoninc.piV1/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onActivityResult failed

TypeError: Cannot read property 'getWidth' of null
File: "/data/data/com.pantoninc.piV1/files/app/tns_modules/camera/camera.js, line: 53, column: 90

StackTrace: 
Frame: function:'appModule_1.android.onActivityResult', file:'/data/data/com.pantoninc.piV1/files/app/tns_modules/camera/camera.js', line: 53, column: 91
Frame: function:'ActivityCallbacksImplementation.onActivityResult', file:'/data/data/com.pantoninc.piV1/files/app/tns_modules/ui/frame/frame.js', line: 769, column: 13
Frame: function:'NativeScriptActivity.onActivityResult', file:'/data/data/com.pantoninc.piV1/files/app/tns_modules/ui/frame/activity.js', line: 33, column: 25


at android.app.ActivityThread.deliverResults(ActivityThread.java:4920)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:4963)
at android.app.ActivityThread.access$1600(ActivityThread.java:221)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1848)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7224)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: com.tns.NativeScriptException: 
Calling js method onActivityResult failed

TypeError: Cannot read property 'getWidth' of null
File: "/data/data/com.pantoninc.piV1/files/app/tns_modules/camera/camera.js, line: 53, column: 90

StackTrace: 
Frame: function:'appModule_1.android.onActivityResult', file:'/data/data/com.pantoninc.piV1/files/app/tns_modules/camera/camera.js', line: 53, column: 91
Frame: function:'ActivityCallbacksImplementation.onActivityResult', file:'/data/data/com.pantoninc.piV1/files/app/tns_modules/ui/frame/frame.js', line: 769, column: 13
Frame: function:'NativeScriptActivity.onActivityResult', file:'/data/data/com.pantoninc.piV1/files/app/tns_modules/ui/frame/activity.js', line: 33, column: 25


at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
at com.tns.Runtime.callJSMethod(Runtime.java:712)
at com.tns.Runtime.callJSMethod(Runtime.java:693)
at com.tns.Runtime.callJSMethod(Runtime.java:683)
at com.tns.NativeScriptActivity.onActivityResult(NativeScriptActivity.java:69)
at android.app.Activity.dispatchActivityResult(Activity.java:7137)
at android.app.ActivityThread.deliverResults(ActivityThread.java:4916)
... 9 more`

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.1.1
- Cross-platform modules:2.1.0
- Runtime(s): 2.1.1
- Plugin(s): None

### Please tell us how to recreate the issue in as much detail as possible.
`cameraModule.takePicture({
            width: 400,
            height: 400,
            keepAspectRatio: true,
            saveToGallery: true
        })
```

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Just run the attached sample app, when taking a picture it will crash.

[cameraDemo.zip](https://github.com/NativeScript/NativeScript/files/404384/cameraDemo.zip)

**Comment by NickIliev** [comment]
Hello @Daxito 

I have tested your case it works as expected on Android devices.
This behaviour is only observed when you are testing the cameraModule on emulators.
As noticed in the documentation article about camera module:

>  By default NativeScript camera application uses a external files directory given by **Context.getExternalFilesDir(null)**

In fact when saveToGallery is set to true the camera module is using **getExternalStoragePublicDirectory** to store the taken photo.
Here is the doc article from Android for what this method really do

> Get a top-level shared/external storage directory for placing files of a particular type. This is where the user will typically place and manage their own files, so you should be careful about what you put here to ensure you don't erase their files or get in the way of their own organization.

So the reason your **saveToGallery : true** is throwing when tested on emulators is that you have some limitations when using camera module on emulators. Overall when working with camera prefer testing on devices.

**Comment by Daxito** [comment]
Interesting, but obviously I was testing on a real device, Samsung Galaxy S5 Android 6.0.1, I will take a look again maybe with a different device....

**Comment by NickIliev** [comment]
@m-abs does your app has the permissions set for read/write to external storage?
in app/App_Resources/**AndroidManifest.xml**
```
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

**Comment by NickIliev** [comment]
@Daxito 
I have created an emulator with SD-card and saveToGallery:true is working on it.
Try the following command to create emulator with SD card:
```
%ANDROID_HOME%\tools\android create avd -n Emulator-Api21-Default -t android-21 --abi default/x86 -c 12M -f
```
_64(for this emulator you will need to have Android 5.0.1 API21 installed - SDK and SystemImage x86, X86_64 Intel Atom)

**Comment by Daxito** [comment]
@NickIliev 
I was able to get rid of the error message by using the "permission plugin", my real device has the SD Card installed, It now takes the picture but I don't see it in the gallery, it says the output folder should be "/storage/emulated/0/Pictures/cameraPicture_090820169578.jpg" but when I search my phone and my SD Card I don't see it, no error at all, I just don't see the image from Gallery nor searching.

This is the simple code I use.

` var permissions = require("nativescript-permissions");            permissions.requestPermission([android.Manifest.permission.READ_EXTERNAL_STORAGE,
                android.Manifest.permission.WRITE_EXTERNAL_STORAGE], "In order to select or take pictures we need your permission")
                .then(function () {
                    console.log("Permissions granted");
                  
 cameraModule.takePicture({
                width: 400,
                height: 400,
                keepAspectRatio: true,
                saveToGallery: true
            }).then(picture => {
               console.log("check gallery");
            }, () => {
                  console.log("Error");
            });

                })
                .catch(function () {
                    console.log("Permissions denied");
                    reject();
                });
`

**Comment by NickIliev** [comment]
@Daxito the thing is that you can not write directly to Android "Gallery" - it will load your photos from Pictures folder after some time (I guess Android is refreshing Gallery on some interval that varies depending on the API level). Another applicable option is to force refresh the Gallery. However, this can be achieved with native code that varies for the different API levels. This is a know Android behaviour - check threads like[ this one](http://stackoverflow.com/questions/2170214/image-saved-to-sdcard-doesnt-appear-in-androids-gallery-app) for possible force refresh solutions.

**Comment by Daxito** [comment]
@NickIliev You are correct! it takes sometime for the pictures to be available in the Gallery, it works then ;-)

Thank you!
