### ISSUE TITLE
Normalize NPM packages

### ISSUE THREAD

**Issue by shlomiassaf** [NativeScript/NativeScript#2558]
Currently, the NativeScript NPM ecosystem is scattered with no convention guidelines.

NativeScript packages can come in flavours and can be easily categorised.
For example:  
- Plugins
- Adapters
- Adapter plugins
- Dev (Toolchain / build process hooks)

And more...

Here are some real world examples of packages:
- `nativescript-socketio` - Plugin
- `nativescript-angular` - Adapter
- `nativescript-ng2-magic` - Adapter plugin (angular)
- `nativescript-dev-sass` - Toolchain
- `nativescript-dev-typescript` - Toolchain

The list is long and growing...

I believe its important to organise most of the packages under a domain of some sort, similar to the way it is done by the Angular 2 team.

Some samples:

`@nativescript/core` ==> `nativescript`
`@nativescript/angular/core` ==> `nativescript-angular`
`@nativescript/angular/magic` ==> `nativescript-ng2-magic`
`@nativescript/dev/typescript` ==> `nativescript-dev-typescript`

Transition can be done in parallel where a new version is published into old and new name.

Of course other ways to categorise are welcome, this is just an idea.

For example, separate official telerik modules by having `@telerik/nativescript` or `@tns/core`

I think it will greatly help making some sense.

If top contributors such as @NathanWalker , @NathanaelA , @vakrilov , @triniwiz and many others will lead the way it will get adoption.

**Comment by triniwiz** [comment]
I love this idea :+1:  :+1:  don't forget @bradmartin

**Comment by NathanaelA** [comment]
It would be difficult to do this; as when you add name spaces you need someone to actually manage the actual name space and then to add people to it to be able to add new plugins.   So then you create an additional artificial wall to getting new plugins developed and released.   

For someone established like me; I'm sure Valio would add me to the name space easily; but then you get a new person like @mkloubert who came out of nowhere a couple months ago and is now the third top plugin developer (http://nativescript.rocks/authors.php) this would have been a barrier for him to even start.  I personally don't want to see another barrier in place for a new author, I want to eliminate barriers.   And then by what criteria does Telerik use to decide to add someone to the name spaces?

Which brings me to the third problem with this idea; security; unless Telerik is willing to spend $7 per plugin developer; there would be no security and I as a "bad" actor could make changes to every other developers plugin in this namespace and add malware or something else to it on a weekend and no one would probably notice until the next week...

Now my plugin site http://plugins.nativescript.rocks attempts to categorize the plugins, there is a section for tools, angular, interface, processing, it not perfect and there are a lot of features I'd love to see added, but at this point I'm not sure there is a better way to do it...

**Comment by shlomiassaf** [comment]
@NathanaelA I Agree, it's not straight forward.

Having a plugin repository is great but its not the whole solution.
One of the issues is import statements, I would like it to be organized.

Yes, not the end of the world, but important and will help new comers.

I see NativeScript as Node.JS for mobile and if NodeJS has NPM eventually NativeScript should have it as well... maybe its a possible solution, maybe not.

**Comment by atanasovg** [comment]
@shlomiassaf I am closing this issue in favor of a similar one with more votes in it: https://github.com/NativeScript/NativeScript/issues/4041
