### ISSUE TITLE
Localization and internationalization on xml file.

### ISSUE THREAD

**Issue by ryc16** [NativeScript/NativeScript#2566]
Hi, {N} supports Multiple Screens for Screen Size, Platform, & Orientation. Will {N} support xml as well?

For example, 
page.en.xml
page.en-US.xml

Currently, I use visibility on the same page.xml as solution.

**Comment by tsonevn** [comment]
Hi @ryc16 
similar issue allready exists - [https://github.com/NativeScript/NativeScript/issues/42](https://github.com/NativeScript/NativeScript/issues/42).

Regards,
@tsonevn
