### ISSUE TITLE
Returning certain values from native iOS code results in immediate crash

### ISSUE THREAD

**Issue by bnussey** [NativeScript/NativeScript#2568]
Since the latest NativeScript release (2.2.0) returning certain values from native iOS code results in a crash. I contribute to nativescript-videoplayer and since the new release, this line of code are resulting in an immediate crash:

```        
return this._player.currentTime().value
```
`this._player` is `AVPlayer`
`currentTime` relates to this method on the AVPlayer - https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVPlayer_Class/#//apple_ref/occ/instm/AVPlayer/currentTime
Full code can be reviewed here: https://github.com/bradmartin/nativescript-videoplayer/blob/master/videoplayer.ios.ts#L113

This is the crash message:

```
com.apple.CoreSimulator.SimDevice.7D812403-FB85-469B-9C88-1B286BC7DF9F.launchd_sim[11559] (UIKitApplication:com.stageme.app[0x6ba9][12379]): Service exited due to signal: Segmentation fault: 11
```

This was working absolutely fine before the upgrade.

In terms of doing some research about the error message, I found this: http://stackoverflow.com/a/23798704/3900606

**Comment by jasssonpet** [comment]
Hi @bnussey,
Thanks for reporting this bug. The problem seems to be related to how the iOS runtime handles struct marshalling on x86_64 architecture. The 2.2 NativeScript CLI now builds for this architecture by default.

In the meantime you can use a 32-bit simulator, like the iPhone 4s one. We'll provide a fix shortly.

**Comment by jasssonpet** [comment]
This issue was moved to NativeScript/ios-runtime#622
