### ISSUE TITLE
Feature request: Server-Sent Events API

### ISSUE THREAD

**Issue by terreb** [NativeScript/NativeScript#2572]
I didn't find whether it's planned to be supported in NativeScript.
https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

 Would be awesome to have this on board. I know there are some plugins for websockets, but HTTPS/2 + SSE sounds more promising.

**Comment by statiklabs** [comment]
I was trying to find information on using SSE with NativeScript and stumbled on this Github Issue. Is there currently no way to have SSE work with NativeScript?

**Comment by triniwiz** [comment]
@terreb  @statiklabs you can check out https://www.npmjs.com/package/nativescript-sse #IOS support coming soon :smile:

**Comment by triniwiz** [comment]
The plugin supports Android & IOS now :smile: so @tsonevn or @hshristov you can close this if you want

**Comment by terreb** [comment]
@triniwiz Unfortunately the plugin doesn't work, at least on iOS. The demo app crashes on connection closing and messages not coming.

**Comment by tsonevn** [comment]
Hi @terreb, 

In case there are issues related to the plugin you can open issue in the plugins [repo ](https://github.com/triniwiz/nativescript-sse/issues/3)
