### ISSUE TITLE
Css sync not working with livereload and groceries tutorial

### ISSUE THREAD

**Issue by vekexasia** [NativeScript/NativeScript#2573]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.
### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.2.0
- Cross-platform modules: android 2.1.1
- Runtime(s): "tns-android": {
      "version": "2.2.0"
    }
- Plugin(s): 
```json
{
    "@angular/common": "2.0.0-rc.3",
    "@angular/compiler": "2.0.0-rc.3",
    "@angular/core": "2.0.0-rc.3",
    "@angular/http": "2.0.0-rc.3",
    "@angular/platform-browser": "2.0.0-rc.3",
    "@angular/platform-browser-dynamic": "2.0.0-rc.3",
    "@angular/platform-server": "2.0.0-rc.3",
    "@angular/router": "3.0.0-alpha.7",
    "nativescript-angular": "0.2.0",
    "tns-core-modules": "2.1.0"
  }
```
### Please tell us how to recreate the issue in as much detail as possible.
I just started an emulator (PLAIN emulator not genymotion), followed the getting started groceries tutorial till Chapter `2.5 Global CSS`. When changing app.css Trying to apply a simple color to Button i see this in console

```
Executing before-prepare hook from /home/abaccega/tmp/nativescript/sample-Groceries/hooks/before-prepare/nativescript-dev-typescript.js
Project successfully prepared (android)
Transferring project files...
Successfully transferred app.css.
Applying changes...
Successfully synced application org.nativescript.groceries on device emulator-5554.
```

Unfortunately the changes are not there. If I restart the app within the emulator the css gets applied.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Just the tutorial till 2.5

**Comment by tsonevn** [comment]
HI @vekexasia,

I have noticed that you are using old modules and  new CLI. Could you try to upgrade `tns-core-modules` and `nativescript-angular` to latest available using the below described steps:

1. `tns plugin remove tns-core-modules`
2. `tns plugin add tns-core-modules@2.2.0`
3. `tns plugin remove nativescript-angular`
4. `tns plugin add nativescript-angular@0.3.0`

Then remove the platform using `tns platform remove android` and  run  `tns run android`.

I hope this will solve your problem.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#396
