### ISSUE TITLE
How do i create Such button? 

### ISSUE THREAD

**Issue by vekexasia** [NativeScript/NativeScript#2578]
How do I create such button @
![login-ticket](https://cloud.githubusercontent.com/assets/200523/17643613/a574e7ea-616f-11e6-876e-fd859c212eb9.png)

Please notice:

- icons are left aligned while text is centered
- text is in different font.

cc: @bradmartin

**Comment by NickIliev** [comment]
Hello @vekexasia,

You can achieve this with CSS using background-image for your icon.
For example something like this:

```

Button {
    width: 400;
    background-color: blue;
    color:white;
    font-family: sans-serif;
    font-size: 18;
    horizontal-align: center;
    text-align:center;

    background-image: url("res://icon");
    background-position: left;
    background-repeat: no-repeat;
    background-size: contain;
}
```
