### ISSUE TITLE
Error: CSS file found but no page specified

### ISSUE THREAD

**Issue by marciovicente** [NativeScript/NativeScript#2582]
Hey guys, I've started developing with NativeScript some days ago and today I got this error:
`CONSOLE ERROR file:///app/tns_modules/trace/trace.js:160:30: Error: CSS file found but no page specified. Please specify page in the options!`

Basically, I've these files:
```xml
<!-- pages/ProductList.xml  -->
<GridLayout xmlns:components="components" loaded="pageLoaded">
  <Label text="{{ title }}" />
  <ListView items="{{ productList }}" itemTap="onItemTap">
    <ListView.itemTemplate>
      <components:CartItem name="{{ name }}" value="{{ value }}" image="{{ image }}" />
    </ListView.itemTemplate>
  </ListView>
</GridLayout>
```

```xml
<!-- components/CartItem.xml -->
  <GridLayout columns="auto, *, auto" rows="auto, 25" class="Cart-wrapper" loaded="onPageLoaded"> 
    <Image src="{{ image }}" class="Cart-image" rowSpan="2" />
    <Label text="{{ name }}" class="Cart-text" textWrap="true" col="1" colSpan="2" />
    <Label text="{{ price }}" class="Cart-price" col="1" row="1" />
  </GridLayout>
```

```javascript
/* components/CartItem.js */
import { Observable } from 'data/observable';

exports.onPageLoaded = (args) => {
  const page = args.object;
  const { name, value, image } = page;
  let context = new Observable({ name, value, image });
  page.bindingContext = context;
}
```
```css
/* components/CartItem.css */
.CarItem { /* ... */ }
```
Anyone have any idea about this error and how could I fix this?

**Comment by NickIliev** [comment]
Hello @marciovicente 

Basically, your _CartItem.xml_ file is a custom component  inside the page _**ProductList.xml**_
Declare the styles for _.Cart-image_, _.Cart-text_ and ._Cart-price_ it in **_pages/ProductList.css_** file (as ProducutList is the page that handles your custom component, not the component itself).

Or you can declare the styles above in the global file **app.css** (respectively app.android.css and app.ios.css if you need platform-specific styles)

**Comment by marciovicente** [comment]
Thanks @NickIliev! I'll do this!

**Comment by igorpetrov** [comment]
@NickIliev Is obtained, it's possible to hook component's `.css` file if component loaded dynamically via `builder.load()` but impossible if component loaded in XML?
