### ISSUE TITLE
Missing TNSLabel in tns_core_modules/ui/label/label.ts

### ISSUE THREAD

**Issue by diestrin** [NativeScript/NativeScript#2583]
Error while running a fresh created project with `tns create my-angular-app --ng `
```
Aug 14 21:53:29 MacBook-Pro sampleGroceries[94568]: assertion failed: 15G31 12H141: libxpc.dylib + 59338 [AF8FA08F-353B-303B-A08E-AEBB3C60A640]: 0x7d
Aug 14 21:53:29 MacBook-Pro.local sampleGroceries[94568]: CONSOLE LOG file:///app/tns_modules/@angular/core/src/facade/lang.js:345:16: EXCEPTION: Error in ./AppComponent class AppComponent - inline template:0:0
Aug 14 21:53:29 MacBook-Pro.local sampleGroceries[94568]: CONSOLE LOG file:///app/tns_modules/@angular/core/src/facade/lang.js:345:16: ORIGINAL EXCEPTION: ReferenceError: Can't find variable: TNSLabel
Aug 14 21:53:29 MacBook-Pro.local sampleGroceries[94568]: CONSOLE LOG file:///app/tns_modules/@angular/core/src/facade/lang.js:345:16: ORIGINAL STACKTRACE:
Aug 14 21:53:29 MacBook-Pro.local sampleGroceries[94568]: CONSOLE LOG file:///app/tns_modules/@angular/core/src/facade/lang.js:345:16: Label@file:///app/tns_modules/ui/label/label.js:24:29
```
Looking a the code ([current snapshot](https://github.com/NativeScript/NativeScript/blob/15d891cc08023546546f4fa8f5dd28f7fd1f2204/tns-core-modules/ui/label/label.ios.ts)) I can see TNSLabel is being used but never imported.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.2.0
- Cross-platform modules: 2.2.0
- Runtime(s): 2.2.0
- Plugin(s): nativescript-angular@0.3.0

### Please tell us how to recreate the issue in as much detail as possible.
Just run the cloned project (after update the dependencies) with `tns run ios --emulator`

### Is there code involved?
No

**Comment by diestrin** [comment]
I was only able to run the project using tns-core-modules v2.0.1, neither 2.1.0 or 2.2.0 seems to be working.

**Comment by hshristov** [comment]
@diestrin With 2.1.0 we introduced TNSLabel control which is located inside tns-core-modules-widgets package. So you probably need to remove platforms and libs folders, then install tns-core-modules which will bring the widgets dependency.

**Comment by diestrin** [comment]
I actually deleted node_modules and platforms several times. I see the tns-core-modules-widgets being installed, but still get the error. And there's a really valid reason for that, go take a look at https://github.com/NativeScript/NativeScript/blob/15d891cc08023546546f4fa8f5dd28f7fd1f2204/tns-core-modules/ui/label/label.ios.ts and there's no import of TNSLabel at all!

**Comment by hshristov** [comment]
Check the package.json version of tns-core-modules package. It should be at least 2.1.0. Better if 2.2.0.
As for the no import of TNSLabel - this is by design. All native libraries are imported in the global context so no need of imports.
