### ISSUE TITLE
Use opacity to make background transparent but not the child element

### ISSUE THREAD

**Issue by ryc16** [NativeScript/NativeScript#2587]
I am trying to create action-bar shown below without using <ActionBar> as <ActionBar> seems more restriction. Anyway, I am expecting and looking for the action bar with opacity background only but not child element. I even tried to set opacity="1" but doesn't work. Is this a bug in {N}, or my usage is not correct. Please advice.

```
    <StackLayout backgroundColor="yellow" opacity="0.3" color="black">
      <GridLayout columns="auto, *, auto" opacity="1">
        <Label text="{{'fa-chevron-left' | fonticon}}" class="fa" opacity="1"/>
        <Label text="Detail" class="title" col="1" opacity="1"/>
        <Label text="{{'fa-pencil' | fonticon}}" class="fa" col="2" opacity="1" />
      </GridLayout>
    </StackLayout>
```

nativescript  = 2.2.0

**Comment by tsonevn** [comment]
Hi @ryc16,
This is normal behavior, while using `opacity` property for `ActionBar`. The children will be affected too.
As a solution for your scenario, you could  use color with alpha for ActionBar. You could review the attached sample code. You could also review the given suggestion for iOS in [this](https://github.com/NativeScript/NativeScript/issues/2192) issue.


main-page.xml

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="loadedEvent" backgroundSpanUnderStatusBar="true">
<Page.actionBar>
    <ActionBar icon="" id="actionbarid">
      <ActionBar.titleView>
        <StackLayout id="stacklayoutId"  id="stlayoutid" orientation="horizontal">
          <Button text="1st" />
          <Button  text="2nd" />
          <Button  text="3rd" />
        </StackLayout>
      </ActionBar.titleView>
  </ActionBar>
</Page.actionBar>
</Page>
```

main-page.ts

```
import { EventData } from "data/observable";
import { Page } from "ui/page";
import { isIOS, isAndroid } from "platform";
import { topmost } from "ui/frame";

// Event handler for Page "navigatingTo" event attached in main-page.xml
export function loadedEvent(args: EventData) {
    // Get the event sender
    var page = <Page>args.object;

     if (isIOS) {
        let navigationBar = topmost().ios.controller.navigationBar;
        navigationBar.translucent = true;
        navigationBar.backgroundColor = UIColor.colorWithRedGreenBlueAlpha(255, 0, 0, 0.9);
    }
}
```

app.css

```
Page{
background-color:"green";
}

ActionBar{
    background-color: rgba(255, 0, 0, 0.0);
}
```

I hope this is applicable for you.

**Comment by ryc16** [comment]
@tsonevn, thanks for your suggestion. What about android platform? Can your solution apply to non action bar element?

**Comment by tsonevn** [comment]
Hi @ryc16,
The given suggestion should be applicable  for non ActionBar Element. However it would help if you could give me some more info about the scenario you would like to use this feature.

Regards,
@tsonevn

**Comment by ryc16** [comment]
Hi @tsonevn, See example, screenshot the top bar started with full transparent (opacity = 0) but keep clear content (full opacity) . the top bar appears more and more solid background color (by increase opacity) while scrolling down. Let me know if this is clear. I think this is very common UX these days.

![68747470733a2f2f7777772e6e61746976657363726970742e6f72672f696d616765732f64656661756c742d736f757263652f64656661756c742d616c62756d2f73616d706c652d7461736b732d64657461696c732e706e67](https://cloud.githubusercontent.com/assets/5568006/17768084/172312d8-6565-11e6-88b2-92f3873a995b.png)

**Comment by tsonevn** [comment]
Hi @ryc16 ,

With the help of `nativescript-statusbar` plugin you could change the color of the statusBar.  You could set transparent  color using hex code for android instead using `opacity` property. You could  review the discussion in [this  ](http://stackoverflow.com/questions/15852122/hex-transparency-in-colors) thread, where have been described the possible values, which you could set as alpha in your color while using hex codes. In regard to that you could also review the attached sample code and  instruction .

to install the plugin run `tns plugin add nativescript-statusbar `

main-page.xml

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:x="nativescript-statusbar" loaded="loadedEvent" backgroundSpanUnderStatusBar="true">
<x:StatusBar ios:barStyle="light" android:barStyle="#40cb7820" />
<Page.actionBar>
    <ActionBar icon="" id="actionbarid">
      <ActionBar.titleView>
        <StackLayout id="stacklayoutId"  id="stlayoutid" orientation="horizontal">
          <Button text="1st" />
          <Button  text="2nd" />
          <Button  text="3rd" />
        </StackLayout>
      </ActionBar.titleView>
  </ActionBar>
</Page.actionBar>
</Page>
```


I hope this is applicable for you.

**Comment by ryc16** [comment]
@tsonevn, thanks for your information. the transparent color overcomes the issue. I only try on android. I am not sure yet on IOS. Hope it works. If you know the answer for IOS, kindly share it.

I hope {N} could fix or enhance the opacity as following:

If parent sets opacity but not children, it makes sense parent with all children use the same parent opacity. However, if children set opacity, all children should use it. I think it benefits on the animation.

**Comment by tsonevn** [comment]
Hi @ryc16 ,

you could  review [this ](http://docs.nativescript.org/ui/change-status-bar-style-ios) article, where have been described the possible ways to style the StatusBar in iOS.  In regard to this issue I will close it and you could open a new one, where you could describe your feature request for the opacity property. There the other people could vote for it and if there is an interest you could find it in some of the next NativeScript versions.

**Comment by dlucidone** [comment]
can anyone provide any sample code with android.Thanks

**Comment by tsonevn** [comment]
Hi @dlucidone,
You could use [nativescript-statusbar](https://www.npmjs.com/package/nativescript-statusbar) plugin, which provides a simple way to style StatusBar for Android and iOS.
Hope this helps.

**Comment by dlucidone** [comment]
@tsonevn Thanks for the help ! But how can I achieve same kind of transparency for any kind of custom view (Ex- transparency in alert box). I'm trying to create a view with same transparency with parent view as background. Any help?

**Comment by viniciodeltoro** [comment]
I have the same issue, I have a StackLayout parent element with a transparency (opacity) of 0.8, inside I have another StakLayout with opacity of 1 but this child element still looks transparent. Any ideas?
