### ISSUE TITLE
Content type with "+json" structured syntax suffix not parsed

### ISSUE THREAD

**Issue by acramatte** [NativeScript/NativeScript#2593]
Hi,

### Tell us about the problem
I am consuming a REST API that implements the [json-api spec](http://jsonapi.org/).
In this case, the Content-Type headers of the API responses are `application/vnd.api+json` [(see here)](http://jsonapi.org/format/#content-negotiation).
Because the XHR Nativescript implementation only JSON.parse content type `'application/json'` [(see here](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/xhr/xhr.ts#L135) and [here)](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/xhr/xhr.ts#L110) I then end up with some NSData object instead of the parsed response.

The quick fix for my case was to change the condition in the xhr.ts to also set the response type to "json" when the content type is `application/vnd.api+json`, something like this:

_tns-core-modules/xhr/xhr.js_
```javascript
...
if (contentType) {
    if (contentType.indexOf('application/json') >= 0 || contentType.indexOf('application/vnd.api+json') >= 0) {
        this.responseType = XMLHttpRequestResponseType.json;
    }
...
```

But as far as I understand, all media types that have the "+json" suffix should be able to be parsed as JSON so this quick fix definitely won't cover all cases.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.2.1
- Cross-platform modules: 2.3.0-2016-08-16-3908
- Runtime(s): 2.1.1

**Comment by enchev** [comment]
Maybe we can simplify it to:
```JavaScript
 if (contentType.indexOf('json') >= 0) {
        this.responseType = XMLHttpRequestResponseType.json;
 }
```

Hey @hdeshev what do you think?

**Comment by hdeshev** [comment]
Wow, I was completely unaware of the `+json` trend. It looks like there are a ton of JSON MIME types already: https://www.iana.org/assignments/media-types/media-types.xhtml. Also: http://stackoverflow.com/a/30740848

I would lean towards checking if the content type is `application/json` or has a `+json` suffix. We'd totally accept a PR that does so. :)

**Comment by acramatte** [comment]
Thanks for your inputs guys, submitted a PR implementing your suggestions.
