### ISSUE TITLE
Everlive - push.clearBadgeNumber issue

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/NativeScript#2594]
Hello,

I have an app for which I have enabled the push notifications.  To test, I sent 2 notifications using the Push Browser in the Telerik Platform site.  Everything worked well and now I have a badge that shows 2 on the application icon.

The problem is that I cannot clear this badge now.  After calling push.clearBadgeNumber, I can confirm that the badge is set to 0 by calling push.getRegistration() and examining the BadgeNumber, but the badge still remains on the application icon.

I even removed and reinstalled the app, but the badge remains.  I also restarted the device with no effect.

What do I need to do to clear it?

Thanks.

**Comment by NickIliev** [comment]
Hi @dpdragnev 

This is made by design - you need to clear the badges manually.
Here is a related thread with the same issue and a  solution;
[https://github.com/NativeScript/push-plugin/issues/31](https://github.com/NativeScript/push-plugin/issues/31)

**Comment by dpdragnev** [comment]
Thank you @NickIliev 

This worked.  I just wish things like this are better documented.   It would be nice to make a mention in the Everlive documentation (http://docs.telerik.com/platform/backend-services/javascript/apireference/JavascriptSDK/Push/push.clearBadgeNumber) that just clearing the badge number does not clear it on the device itself.

Appreciate your help.
