### ISSUE TITLE
Nested repeater when add many new rows crashed app

### ISSUE THREAD

**Issue by yclau** [NativeScript/NativeScript#2595]
## Tell us about the problem
Hi, I trying do a nested repeater binding 100 rows data with complicated interface, it take around 10 sec. So my solution separate binding, when i loop 100 new rows into child repeater and it will crashed the app.  Any idea?
  
### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.1.1
- Cross-platform modules: 2.2.0
- Runtime(s):  2.1.1 

 
[app.zip](https://github.com/NativeScript/NativeScript/files/421647/app.zip)

**Comment by enchev** [comment]
Hey @yclau,

The repeater is not virtualized like the ListView - you are running out of memory most probably. Maybe you can try RadListView:
http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/overview

**Comment by yclau** [comment]
I changed to RadListView and inner repeater, after when I scolling to another second area, it will like loading another repeater and reset my selected background button . If I scolling too fast, the app crashed.  Isn't can nested RadListView ?

**Comment by enchev** [comment]
Hey @yclau,

I've just checked the code of the SectionedListView and indeed this component is using virtualized native Android ListView. Why not use it?

**Comment by yclau** [comment]
I think SectionedListView  got android file or code but no support in android

![5ca550aebbb11391fde4bef7cb3942348da69c95cfa9fa6c23 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/4135524/17797180/845c3994-65f9-11e6-8a4d-2d735b2bf7db.jpg)

**Comment by yclau** [comment]
Hi @enchev , 
can I know Group Listview next new version got release ?

**Comment by ginev** [comment]
Hello @yclau,
Your current option is to create a flattened list of data items and visualize them in a regular LIstView using a condition in the ItemTemplate to differentiate between regular items and data groups. If a normal grouped data list looks like this:

Group 1.children:
-- Item 1
-- Item 2
-- Item 3
Group2.children:
-- Item 1
-- Item 2
......

The flattened list will be a simple array of data items and data groups looking like that:

Group 1
Item 1
Item 2
Item3
Group 2
Item 1
Item 2
....

So if you bind this simple array to a ListView instance you can put a property - `isGroup` - on your Group* and use it in your ItemTemplate to show an item that looks like a section header. For the rest of the items you can display a regular ItemTemplate.

I hope this helps.
