### ISSUE TITLE
Screen Size Qualifiers  not work  in tns Angular project, only work in js project.

### ISSUE THREAD

**Issue by Arthurisme** [NativeScript/NativeScript#2604]
I use following names as Screen Size Qualifiers, but none of any one is working in tns angular project:

page.minWH600.html
page.minWH600.css
page.minWH600.ts
page.land.css
page.land.html
page.port.css
page.port.html

So is it because Screen Size Qualifiers not support angular project yet?

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#404
