### ISSUE TITLE
Transformed text in Button - Text not colorable

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/NativeScript#2605]
_From @bastianjoel on August 18, 2016 17:19_

When I try this code
```
Button {
	text-transform: uppercase;
	color:#FFFFFF;
	background-color:#000000;
}
```
The text color inside the button is still blue instead of white. 
Without the text-transform it's white.

_Copied from original issue: NativeScript/ios-runtime#628_

**Comment by tsonevn** [comment]
The problem has been already introduced in   [#2601](https://github.com/NativeScript/NativeScript/issues/2601)
