### ISSUE TITLE
WebView crash when navigating back

### ISSUE THREAD

**Issue by hshristov** [NativeScript/NativeScript#261]
When navigating back from page that contains WebView to previous page that does not contain WebView an exception is thrown.

**Comment by emiloberg** [comment]
Hmm.. I'm doing this in an app without exceptions being thrown. Android/iOS?

**Comment by hshristov** [comment]
Hi @emiloberg,

which versions (of modules and runtimes) are you using?

**Comment by emiloberg** [comment]
Good question! Is there any way of getting the versions?

The modules was built from master on May 19, 16:08. The runtimes hasn't been updated manually so I'd guess it's 1.0.1?

**Comment by hshristov** [comment]
@emiloberg  tns --version will return the version of the CLI. CLI uses the latest official runtimes and modules which are version 1.0.0 as of now. If you are using custom build of the modules you can check the package.json

**Comment by emiloberg** [comment]
> ▶ tns --version
> 1.0.1

This has never been updated manually by me.

tns_modules/package.json
> "version": "1.0.0",

However, that version number has never been bumped. It's [currently also saying 1.0.0](https://github.com/NativeScript/NativeScript/blob/master/package.json). But I _have_ checked out and built the tns_modules as of commit 3b6a23b (to get access to the src property added in 1dc3de7 and the context binding bug fix in 3b6a23b).

The project is actually available here: https://github.com/emiloberg/oppna-program-reklistan-app

**Comment by dtopuzov** [comment]
@emiloberg can you please provide us a simple project where the problem is isolated (no external dependencies) or steps how to setup/build your project. 
We are not able to reproduce this issue with our [Gallery App application](https://github.com/NativeScript/NativeScript/tree/master/apps/gallery-app)
