### ISSUE TITLE
Push images to ListView asynchronously?

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#2612]
Found [this article](http://nuvious.com/Blog/2016/7/5/calling-dispatch_async-in-nativescript) specifically for iOS, but it's not as straight forward as it may seem.

Problem I'm having is that I am trying to load thumbnail images from the Photos Library from an iPhone or iPad. But if the device has too many photos, it could take up to a minute or even more for the ListView to visualize. It is pushing the images synchronously instead of one by one.

For iOS, how do I use `dispatch_async`? The found article above wasn't much of help.

**EDIT:** It seems like ListView does load asynchronously. I was using RadListView from the Telerik NativeScript UI. I am trying to load a ListView with horizontal scrolling but the normal ListView doesn't have that option. I thought RadListView was just a more advanced ListView?

**Comment by tsonevn** [comment]
Hi @NordlingArt,
NativeScript ListView do not support changing the scrolling orientation. In regard to that you could use [ScrollView ](https://bradmartin.net/2016/05/31/create-horizontal-scrolling-lists-in-nativescript-apps/) with horizontal orientation to display your data.  You could also use ImageCache module to get image source and to display it. Another option that you could use in your project is `nativescript-slides` plugin and to add the slides programmatical. You could find an example [here](https://github.com/TheOriginalJosh/nativescript-slides). 

I hope this is applicable for you.

**Comment by NordlingArt** [comment]
@tsonevn - Unfortunately either of those will make the app freeze when loading all the images. ListView is the only one that doesn't freeze. I figured I could make the script load for images per row, meaning every fourth image is asynchronous, more or less.
