### ISSUE TITLE
[question] embrace NativeScript without TypeScript skill ?

### ISSUE THREAD

**Issue by c1ngular** [NativeScript/NativeScript#2618]
Hi , everyone 
new to NativeScript, found it is fascinating ! though i am confused by knowing that TypeScript is the "first citizen"  in  NativeScript world ! but  i don't know anything about TypeScript , is this gonna be a problem to use NativeScript ? 

NO.1   how should i use plugins written by TypeScript  in JavaScript context ?

NO.2  can i just use plain JavaScript (ES6 support ? ) to write a plugin if necessary ?

thank you

**Comment by tsonevn** [comment]
Hi @c1ngular,

Thank you for your question.
In NativeScript you could use vanilla JavaScript as well as TypeScript as program language. With both options, you could use all features plugins build for the platform. In regard to that TypeScript has been integrated in NativeScript to help the programmer, who is coming from other strongly-typed language and would like to use IntelliSense  while writing their app. 

After you add plugin in your project `tns plugin add <plugin_name>` you should required it in your project to be able to use its functionality. You could review our [getting started](http://docs.nativescript.org/tutorial/chapter-0) project from the documentation.
About your second question, you could read more about NativeScript plugin [here](http://docs.nativescript.org/plugins/plugins#what-are-nativescript-plugins).

In case you have more questions you could use our [StackOverflow ](http://stackoverflow.com/questions/tagged/nativescript) or [Slack ](http://developer.telerik.com/wp-login.php?action=slack-invitation) canals, where you could also find help from our community .

I hope this information helps

**Comment by c1ngular** [comment]
@tsonevn 
Thank you, i will dig around .
