### ISSUE TITLE
after updating to tns-core-modules ^2.2.1 ui/image module stopped working

### ISSUE THREAD

**Issue by terhoraj** [NativeScript/NativeScript#2619]
I got this problem just when I really don't need this kind of stuff happening.

I'm getting: TypeError: this._goToVisualSate is not a function when navigatin to other view where I have:

var imageModule = require("ui/image");
var image = imageModule.Image();

commment out everything else and still this is happening. Worked without a problem before!

**Comment by tsonevn** [comment]
Hi @terhoraj,
Does this problem appear on new project or it is happening on existing one. You could try to remove the platform and to add it again via:

`tns platform remove <platform_name>`

`tns platform add <platform_name>`

In regard to that you should also remove and add again the `tns-core-modules`

`tns plugin remove tns-core-modules`

`tns plugin add tns-core-modules`

If the problem still exist after that, could you give us some more info about the problem or to give us sample project, which could be debugged locally.


Regards,
@tsonevn

**Comment by terhoraj** [comment]
Created new project (stock tns create projectname) I'm using viewmodel and here's my edited viewModel code. I got same error after running it with this clean new project. Here's my viewModel code:

`var __extends = (this && this.__extends) || function (d, b) {
        for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
        function __() {
            this.constructor = d;}
        __.prototype = b.prototype;
        d.prototype = new __();
    };

var observable = require("data/observable");
var imageModule = require("ui/image");
var image = imageModule.Image();


var QualityViewModel = (function (_super) {
    __extends(MainViewModel, _super);

    function MainViewModel() {
        _super.call(this);
        var _this = this;
    }


    return MainViewModel;
})();
exports.MainViewModel = MainViewModel;`

**Comment by terhoraj** [comment]
Same thing happens without viewModel


var imageModule = require("ui/image");
var image = imageModule.Image(); <--- after adding this

function navigatedTo(args) {
    var page = args.object;
}
exports.navigatedTo = navigatedTo;

**Comment by terhoraj** [comment]
For f* sake where is my NEW argument.
var image = new imageModule.Image(); worked of course..
