### ISSUE TITLE
DatePicker and TimePicker Styling is missing for Android

### ISSUE THREAD

**Issue by codingbandit** [NativeScript/NativeScript#2622]
I am needing to change the text color of a TimePicker control in my application. The color property isn't supported in Android.

Platform:
Android

- CLI: 2.2.1
- Cross-platform modules: 2.2.1
- tns-android : 2.2.0

**Comment by tsonevn** [comment]
related to  issue [#1903](https://github.com/NativeScript/NativeScript/issues/1903)
