### ISSUE TITLE
Feature request: Expansion files (main or patch obb) 

### ISSUE THREAD

**Issue by b3nnee** [NativeScript/NativeScript#2624]
I have an app for Android that requires 150MB+ video files, suitably the video files should be in obb files for upload to the Play Store as main/patch expansion files. I used to do this when I created Android apps using Android Studio (a tool I _abandoned_ long ago, after which I _abandoned_ Titanium for NativeScript!)

Support/tutorial for this in NativeScript would be great. 

_Sincere apologies if it exists, but I searched to no avail._

Edit: Just found this:
https://github.com/appcelerator-forks/_jasonkneen.TiExpansionFiles
Looking to see if one could get ideas from it.

**Comment by mn-martin** [comment]
👍  This really needs to be added.

**Comment by lukeramsden** [comment]
Its coming up on a year old now, and no discussion whatsoever? Does anyone know of ANY way of doing this? I can't release my app on Android without it.

**Comment by lukeramsden** [comment]
Bumping this, IMO it's a pretty important feature.

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/android-runtime #1400](https://github.com/NativeScript/android-runtime/issues/1400) via [**ZenHub**](https://www.zenhub.com/)
