### ISSUE TITLE
[TNS 2.2.1] [Android] Cannot emulate: "Execution failed for task ':asbg:runAstParser'"

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#2628]
Been trying to run the Android emulator for a while now but is constantly getting new error messages. I finally got rid of most of them, but this is the last one that I cannot resolve. I have googled this error and every issue that this has been reported on, has been resolved with no explanation or answer as to why it happens.

```
Waiting for emulator device initialization.....
Project successfully prepared (android)

:config phase:  createDefaultIncludeFiles
	+found plugins: tns-core-modules-widgets

:config phase:  createPluginsConfigFile
	 Creating product flavors include.gradle file in /Users/Filip/GitHub/NativeScript plugins/nativescript-na-camera/demo/platforms/android/configurations folder...

:config phase:  pluginExtend
	+applying configuration from: /Users/Filip/GitHub/NativeScript plugins/nativescript-na-camera/demo/platforms/android/configurations/include.gradle
	+applying configuration from: /Users/Filip/GitHub/NativeScript plugins/nativescript-na-camera/demo/platforms/android/configurations/tns-core-modules-widgets/include.gradle

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
	+adding dependency: /Users/Filip/GitHub/NativeScript plugins/nativescript-na-camera/demo/platforms/android/libs/aar/widgets-release.aar
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preF0DebugBuild UP-TO-DATE
:checkF0DebugManifest
:preF0ReleaseBuild UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2340Library UP-TO-DATE
:prepareComAndroidSupportAppcompatV72340Library UP-TO-DATE
:prepareComAndroidSupportSupportV42340Library UP-TO-DATE
:prepareComAndroidSupportSupportVectorDrawable2340Library UP-TO-DATE
:prepareNaCameraRuntimeUnspecifiedLibrary UP-TO-DATE
:prepareWidgetsReleaseLibrary UP-TO-DATE
:prepareF0DebugDependencies
:compileF0DebugAidl UP-TO-DATE
:compileF0DebugRenderscript UP-TO-DATE
:generateF0DebugBuildConfig UP-TO-DATE
:cleanLocalAarFiles
:ensureMetadataOutDir
:collectAllJars
:setProperties
:asbg:generateInterfaceNamesList
:asbg:runAstParser
inputDir: /Users/Filip/GitHub/NativeScript plugins/nativescript-na-camera/demo/platforms/android/src/main/assets/app
outFile: ../bindings.txt

/Users/Filip/GitHub/NativeScript plugins/nativescript-na-camera/demo/platforms/android/build-tools/android-static-binding-generator/parser/js_parser.js:93
	return new Promise(function (resolve, reject) {
            ^
ReferenceError: Promise is not defined
    at getFileAst (/Users/Filip/GitHub/NativeScript plugins/nativescript-na-camera/demo/platforms/android/build-tools/android-static-binding-generator/parser/js_parser.js:93:13)
    at Object.<anonymous> (/Users/Filip/GitHub/NativeScript plugins/nativescript-na-camera/demo/platforms/android/build-tools/android-static-binding-generator/parser/js_parser.js:81:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
:asbg:runAstParser FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Filip/GitHub/NativeScript plugins/nativescript-na-camera/demo/platforms/android/build-tools/android-static-binding-generator/build.gradle' line: 53

* What went wrong:
Execution failed for task ':asbg:runAstParser'.
> Process 'command 'node'' finished with non-zero exit value 8
```

This happens even on a clean git clone of Groceries. So it's nothing to do with my app itself.

**Comment by enchev** [comment]
Hey @Plamen5kov do you know what can cause this issue?

**Comment by Plamen5kov** [comment]
@NordlingArt you're probably using node `0.10.x`. Currently we support `0.12.x`, `4.x`, `6.x`. Try updating your node version.
There are no `Promise` in node `0.10.x` node version, hence the error you're getting.

**Comment by sacketty** [comment]
Hi guys,
I am facing the same issue event though I am running node v6.4.0.

My config:

- Mac OSX ElCapitan 10.11.4
- Node v6.4.0.
- latest android-sdk-macosx version
- tns --version 2.2.1

tns doctor result:
> Your components are up-to-date.

> No issues were detected.

tns create sampleApp:
> Project sampleApp was successfully created.

cd sampleApp; tns platform add android;
> ...
> Project successfully created.

tns prepare android
>...
>Project successfully prepared (android)
tns build android

> :config phase:  createDefaultIncludeFiles
	+found plugins: tns-core-modules-widgets
	 + creating include.gradle file for /Users/henrisack/workspace/Nativescript/sampleApp/platforms/android/configurations/tns-core-modules-widgets
Renaming plugin directory to flavor name: /Users/henrisack/workspace/Nativescript/sampleApp/platforms/android/src/tns-core-modules-widgets -> /Users/henrisack/workspace/Nativescript/sampleApp/platforms/android/src/F0

:config phase:  createPluginsConfigFile
	 Creating product flavors include.gradle file in /Users/henrisack/workspace/Nativescript/sampleApp/platforms/android/configurations folder...

:config phase:  pluginExtend
	+applying configuration from: /Users/henrisack/workspace/Nativescript/sampleApp/platforms/android/configurations/include.gradle
	+applying configuration from: /Users/henrisack/workspace/Nativescript/sampleApp/platforms/android/configurations/tns-core-modules-widgets/include.gradle

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
	+adding dependency: /Users/henrisack/workspace/Nativescript/sampleApp/platforms/android/libs/aar/widgets-release.aar
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preF0DebugBuild UP-TO-DATE
:checkF0DebugManifest
:preF0ReleaseBuild UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2340Library
:prepareComAndroidSupportAppcompatV72340Library
:prepareComAndroidSupportSupportV42340Library
:prepareComAndroidSupportSupportVectorDrawable2340Library
:prepareSampleAppRuntimeUnspecifiedLibrary
:prepareWidgetsReleaseLibrary
:prepareF0DebugDependencies
:compileF0DebugAidl
:compileF0DebugRenderscript
:generateF0DebugBuildConfig
:cleanLocalAarFiles
:ensureMetadataOutDir
:collectAllJars
:setProperties
:asbg:generateInterfaceNamesList
:asbg:runAstParser FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':asbg:runAstParser'.
> A problem occurred starting process 'command 'node''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Does anyone has any clue because I am now stuck with an actual project now

**Comment by Plamen5kov** [comment]
Hi @sacketty I couldn't reproduce the problem, so could you provide steps to reproduce. Does the problem happen with the default application, or just with the one you're currently working on?

**Comment by sacketty** [comment]
Hi @Plamen5kov , I thought the issue was with my project configuration.
So I created a vanilla new project ( tns create sampleApp ). But I could not build it.
As of now I can't event build the default application.

**Comment by sacketty** [comment]
This is kind of weird !
> cd samplApp; tns build android
result: 

> path.js:1144
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1144:25)
    at Function.Module._resolveLookupPaths (module.js:376:17)
    at Function.Module._resolveFilename (module.js:446:31)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/bin/nativescript.js:4:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
The I tried 

> tns run android
> Starting Android emulator with image Nexus_5_API_21_x86
Cannot run your app in the native emulator. Increase the timeout of the operation with the --timeout option or try to restart your adb server with 'adb kill-server' command. Alternatively, run the Android Virtual Device manager and increase the allocated RAM for the virtual device.
# run android
>....
Finally I tried : 
> tns build android
and now it builds perfectly !
>BUILD SUCCESSFUL

Total time: 1 mins 0.303 secs
Project successfully built.

I have absolutely no idea of what happened...

**Comment by Plamen5kov** [comment]
Hi @sacketty this looks like a nodejs issue. [Read more info on this matter](https://github.com/nodejs/node/issues/1184).

**Comment by sacketty** [comment]
Hi @Plamen5kov  thank you for your support 👍

**Comment by NordlingArt** [comment]
@Plamen5kov - Sounds plausible. But I am unable to update my Node v0.10.44. I download the 6.4.1 from the Node website and the installation runs successfully. Calling `node -v` will however still display `v0.10.44`.
