### ISSUE TITLE
Images brought in from internet disappear on scroll

### ISSUE THREAD

**Issue by chief10** [NativeScript/NativeScript#2629]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

## Please, provide the details below:
Images brought in that are not part of the app -- like from a url -- disappear momentarily when brought back into viewport from being scrolled off screen. [Gif example of the issue](http://imgur.com/a/JtBL6)

Code for an Image:     
`  <Image [src]="item.image_url" row="0" height="100%"></Image>`

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

[Gif example](http://imgur.com/a/JtBL6)

### Which platform(s) does your issue occur on?
Android. Have not tested on iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.2.0
- Cross-platform modules: 2.2.0

**My package.json**

```json
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.mymarket",
    "tns-android": {
      "version": "2.2.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/platform-server": "2.0.0-rc.4",
    "@angular/router": "3.0.0-beta.2",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "font-awesome": "^4.6.3",
    "nativescript-angular": "^0.3.0",
    "nativescript-geolocation": "0.0.12",
    "nativescript-permissions": "^1.2.0",
    "reflect-metadata": "^0.1.5",
    "tns-core-modules": "2.2.0"
  },
  "devDependencies": {
    "babel-traverse": "6.13.0",
    "babel-types": "6.13.0",
    "babylon": "6.8.4",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^1.8.10"
  }
```

### Please tell us how to recreate the issue in as much detail as possible.

1. Create a scrollable list view that includes multiple images. 
2. Scroll images off the screen.
3. Wait a moment.
4. Scroll back up the screen.
5. The image will be gone for about half a second before it reappears.

**Comment by enchev** [comment]
Hey @chief10,

You may need to use image caching similar to our example:
https://github.com/NativeScript/NativeScript/blob/master/apps/app/cuteness.io/reddit-item-view-model.ts#L45-L78

https://github.com/NativeScript/NativeScript/blob/master/apps/app/cuteness.io/main-page.xml#L10
