### ISSUE TITLE
Provide per page option for manipulating NavigationBar

### ISSUE THREAD

**Issue by hshristov** [NativeScript/NativeScript#263]
Page should have setting that specifies navigationBar visibility.

**Comment by hamorphis** [comment]
The new property is called Page.navigationBarHidden.

**Comment by vchimev** [comment]
Current state issues:
- iOS - when Page.navigationBarHidden = true the page is layouted as the navigation bar is hidden, but it is preset on the page and covers its content.
- Android - when Page.navigationBarHidden = true the page is layouted as expected, but going to another page where action bar should be present - it is not.

**Comment by vchimev** [comment]
The property is renamed to Page.actionBarHidden. Issues are fixed.
