### ISSUE TITLE
Enhancement: Automatically Transpile Module Typescript into Js

### ISSUE THREAD

**Issue by vbresults** [NativeScript/NativeScript#2631]
As it stands, modules in typescript don't get transpiled into js automatically -- the module has to be distributed with the js.  It would make things simpler, remove uneeded moving parts if automatic.

**Comment by m-abs** [comment]
We use the `nativescript-dev-typescript` for our project, it transpiles ts-files into js-files, but puts them in the same folder as the source ts-files, which I consider a mess in my filesystem.

**Comment by manoldonev** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Thank you!
