### ISSUE TITLE
Application-settings returning wrong values

### ISSUE THREAD

**Issue by RitvikMandyam** [NativeScript/NativeScript#2633]
Hi,
I've been searching StackOverflow and several GitHub issues to try and find a solution to this, but I've had no luck whatsoever.

Test platform: Android
CLI: 2.1.1
Cross-platform modules version: 2.3.0-2016-08-18-3928
Runtime (Android): 2.1.1
Plugins: {
     "crypto": "0.0.3",
     "nativescript-checkbox": "^1.1.3",
     "nativescript-statusbar": "^1.0.0",
     "nativescript-telerik-ui": "^1.1.1",
     "nativescript-toast": "^1.3.0",
     "tns-core-modules": "^2.3.0-2016-08-18-3928"
}

I've been using the application-settings module to save data, like an API Key, a local login PIN (salted), an email ID and suchlike. It's been working fine for a while, but all of a sudden, {N} has started putting values that I keyed into the app while testing it. I've been facing this issue since I built a signed APK of the app. I've gone through every line of code involved in the app and am absolutely positive I'm not setting values anywhere. The values it's giving me are the values I entered during the first test after building the APK. Unfortunately, I can't give you any code samples or tell you exactly how to recreate it on account of I haven't the slightest clue where the problem is coming from. Any help would be appreciated. Thanks.

**Comment by RitvikMandyam** [comment]
Update: it's only an issue on my Moto X Force running Android 6.0 and it gets fixed when I manually clear app data. It works fine on other devices.

**Comment by RitvikMandyam** [comment]
Still hoping for a fix to this, I'd really like to be able to test this on my phone.

**Comment by einicher** [comment]
I have this problem too, for a while I ignored it, but it gets really annoying now.
It does not matter if i delete all app data in the android application settings, completly remove the app and reinstall it, even if i do a applicationSettings.clear(); or applicationSettings.remove(); on all values, after the next install everything is suddenly there again.

This makes it impossbile for the customer to test the setup on phones which had earlyer versions of the app.

I am so glad someone else is having this issue, because i am loosing my mind on this right now.

Its also on Android 7.

Where do you actually store the data? i tried to delete my app data manually, but even that does not work.

**Comment by hchoriq** [comment]
I'm having issues when setting numbers with setNumber. eg. if I use appSettings.setNumber('id', 888888888); then appSettings.getNumber('id') right away, it returns the correct number. But if I use appSettings.getNumber('id') from another page, it returns a slightly different number. Very unstable and just renders nativescript quite unusable.

**Comment by einicher** [comment]
Cause of the problem in my case was android app backup.

**Comment by kurapikats** [comment]
I'm having the same issue.

```
let mobileNumber = 639082150652
applicationSettings.setNumber('memberMobile', mobileNumber)
console.log(mobileNumber)
console.log(applicationSettings.getNumber('memberMobile'))
// outputs
639082150652
639082168320
```
here's my NS version 
"nativescript-telerik-ui-pro": "^3.1.4",
"nativescript-theme-core": "~1.0.2",
"tns-core-modules": "~3.2.0"

running on windows 10 / genymotion android 6 and 7

**Comment by NickIliev** [comment]
@kurapikats  try setting the value as `string` while using `setString` instead using `setNumber`
