### ISSUE TITLE
Cannot even get native script running on Windows 

### ISSUE THREAD

**Issue by nigel-dewar** [NativeScript/NativeScript#2635]
Hi there,

The first time I tried to get nativescript running on windows, a month or so ago I got no-where. The second time I tried today on a different FRESH windows 7 machine, I still get nowhere.

There is something really broken with your setup/installation process.

I have done Everything correctly to my knowledge. I even have installed genymotion to try and get the nativescript to work and still no go.

With genymotion, I get this strange error whilst trying to run the emulator. 

C:\test\sample-Groceries>tns run android
Error: Command failed: C:\Users\s2980077\AppData\Local\Android\android-sdk\platf
orm-tools\adb devices
error: could not install *smartsocket* listener: cannot bind to 127.0.0.1:5037:
Only one usage of each socket address (protocol/network address/port) is normall
y permitted. (10048)
could not read ok from ADB Server
* failed to start daemon *
error: cannot connect to daemon
: Command failed: C:\Users\s2980077\AppData\Local\Android\android-sdk\platform-t
ools\adb devices

What is this all about. Should I not just be able to run tns and connect to genymotion?

what is this 'cannot install smartsocket' all about?

If you try with a fresh windows machine, and follow the installation instructions exactly, you will fail.

If you want, I can upload a step by step screen shotted document of how I followed your instructions exactly and still get no-where.

**Comment by vchimev** [comment]
Hi @nigel-dewar,

Could you please go to Genymotion > Settings > ADB tab > Check "Use custom Android SDK tools" and browse the path to your Android SDK [(an example)] (http://stackoverflow.com/questions/35959350/react-native-android-genymotion-adb-server-didnt-ack?answertab=votes#tab-top)?

**Comment by nigel-dewar** [comment]
Thank you very much this worked!!!

Can you please update the instructions to do this as I spent several hours banging my head against keyboard and wondering about my choice of career path.

Many thanks

Nigel D

**Comment by vchimev** [comment]
I'm glad this helped and will improve the article, @nigel-dewar.
