### ISSUE TITLE
App crashes after inactivity or multitasking

### ISSUE THREAD

**Issue by MomenYasser** [NativeScript/NativeScript#2636]
The App Crashes After Inactivity or multitasks and i don't know why !
i used android device monitor to know the reason and this is result 

`08-28 23:45:31.033: E/ActivityThread(8932): Performing stop of activity that is not resumed: {org.nativescript.playertns/com.tns.NativeScriptActivity}
08-28 23:45:31.033: E/ActivityThread(8932): java.lang.RuntimeException: Performing stop of activity that is not resumed: {org.nativescript.playertns/com.tns.NativeScriptActivity}
08-28 23:45:31.033: E/ActivityThread(8932):     at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3344)
08-28 23:45:31.033: E/ActivityThread(8932):     at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3425)
08-28 23:45:31.033: E/ActivityThread(8932):     at android.app.ActivityThread.access$1100(ActivityThread.java:151)
08-28 23:45:31.033: E/ActivityThread(8932):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
08-28 23:45:31.033: E/ActivityThread(8932):     at android.os.Handler.dispatchMessage(Handler.java:102)
08-28 23:45:31.033: E/ActivityThread(8932):     at android.os.Looper.loop(Looper.java:135)
08-28 23:45:31.033: E/ActivityThread(8932):     at android.app.ActivityThread.main(ActivityThread.java:5254)
08-28 23:45:31.033: E/ActivityThread(8932):     at java.lang.reflect.Method.invoke(Native Method)
08-28 23:45:31.033: E/ActivityThread(8932):     at java.lang.reflect.Method.invoke(Method.java:372)
08-28 23:45:31.033: E/ActivityThread(8932):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
08-28 23:45:31.033: E/ActivityThread(8932):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
08-28 23:47:04.375: E/MediaPlayer-JNI(8932): QCMediaPlayer mediaplayer NOT present
08-28 23:50:03.101: E/MediaPlayer-JNI(8932): QCMediaPlayer mediaplayer NOT present`

this before crashing 

`08-29 00:26:32.630: I/art(15607): Background sticky concurrent mark sweep GC freed 5511(111KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 23MB/23MB, paused 14.668ms total 72.804ms
08-29 00:26:32.630: I/art(15607): Background sticky concurrent mark sweep GC freed 5511(111KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 23MB/23MB, paused 14.668ms total 72.804ms
08-29 00:26:36.758: I/art(15607): Background partial concurrent mark sweep GC freed 11329(1435KB) AllocSpace objects, 1(255KB) LOS objects, 40% free, 21MB/36MB, paused 8.059ms total 130.466ms`

and this for emulator 

`08-28 21:53:19.029: I/ActivityManager(1525): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.nativescript.playertns/com.tns.NativeScriptActivity (has extras)} from uid 10014 on display 0
08-28 21:53:19.131: I/ActivityManager(1525): Start proc 2716:org.nativescript.playertns/u0a61 for activity org.nativescript.playertns/com.tns.NativeScriptActivity
08-28 21:53:19.950: E/AndroidRuntime(2716): Process: org.nativescript.playertns, PID: 2716
08-28 21:53:19.950: E/AndroidRuntime(2716): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.nativescript.playertns-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.playertns-1/lib/x86_64, /data/app/org.nativescript.playertns-1/base.apk!/lib/x86_64, /vendor/lib64, /system/lib64]]] couldn't find "libNativeScript.so"
08-28 21:53:19.950: E/AndroidRuntime(2716):     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:15)
08-28 21:53:19.961: W/ActivityManager(1525):   Force finishing activity org.nativescript.playertns/com.tns.NativeScriptActivity
08-28 21:53:20.271: I/WindowManager(1525): Screenshot max retries 4 of Token{f6a281f ActivityRecord{494efbe u0 org.nativescript.playertns/com.tns.NativeScriptActivity t34 f}} appWin=Window{682fc17 u0 Starting org.nativescript.playertns} drawState=1
08-28 21:53:20.774: W/ActivityManager(1525): Activity pause timeout for ActivityRecord{494efbe u0 org.nativescript.playertns/com.tns.NativeScriptActivity t34 f}
08-28 21:53:31.787: W/ActivityManager(1525): Activity destroy timeout for ActivityRecord{494efbe u0 org.nativescript.playertns/com.tns.NativeScriptActivity t34 f}`

-Platform: Android
- CLI: 2.1.1
- Cross-platform modules: 2.1.0
- Runtime(s): 2.1.1

**Comment by enchev** [comment]
Hey @slavchev do you know what can cause this error?

**Comment by roblav96** [comment]
@MomenYasser try updating your runtime to `v2.2.0`

**Comment by slavchev** [comment]
@roblav96 The device logcat doesn't reveal much. You can put `__enableVerboseLogging();` as a first line in your code to enable verbose logging.

As for the emulator logcat it clearly says it is `UnsatisfiedLinkError` because it is looking for `x86_64` architecture for which we currently don't provide a build. A common reason for this error is the presence of other native `*.so` libraries that are provided for this architecture. Try stripping them down to `x86`, `armeabi-v7a` and `arm64-v8a`. Using `x86` (not `x86_64`) emulator could also be an option.

**Comment by MomenYasser** [comment]
@slavchev First: Thanks about this (__enableVerboseLogging()) :+1: :smile: 

Second: i used it and the problem was in RadListView it logs infinity logs and use memory without any 
interactivity. now the ram usage for app is fixed at 80 mb and still increase when you navigate from 
component to another (i'm using angular). so i expect to solve that i need to close memory when leaving 
the route . Anyone know how can i clear it ???

Logs: her's the logs now from my console when app running :

`D/TNS.Native(14632): ObjectManager::GetJSInstanceInfo: called
D/TNS.Native(14632): ObjectManager::GetJSInstanceInfo: called
D/TNS.Native(14632): ObjectManager::GetJSInstanceInfo: called
D/TNS.Native(14632): ObjectManager::GetJSInstanceInfo: called
D/TNS.Native(14632): ObjectManager::GetJSInstanceInfo: called
D/TNS.Native(14632): ObjectManager::GetJSInstanceInfo: called
D/TNS.Native(14632): ObjectManager::GetJSInstanceInfo: called
D/TNS.Native(14632): ObjectManager::GetJSInstanceInfo: called
D/TNS.Native(14632): ObjectManager::GetJSInstanceInfo: called
D/TNS.Native(14632): ObjectManager::GetJSInstanceInfo: called
D/TNS.Native(14632): ObjectManager::GetJSInstanceInfo: called
D/TNS.Native(14632): ObjectManager::GetJSInstanceInfo: called
D/TNS.Native(14632): ObjectManager::GetJSInstanceInfo: called
D/TNS.Native(14632): ObjectManager::GetJSInstanceInfo: called
D/TNS.Java(14632): Platform.CallJSMethod: calling js method onTrimMemory with javaObjectID 4 type=com.tns.gen.android.content.ComponentCallbacks2
D/TNS.Native(14632): CallJSMethodNative called javaObjectID=4
D/TNS.Native(14632): CallJSMethodNative called jsObject=724579011
D/TNS.Java(14632): Platform.CallJSMethod: calling js method onDestroyView with javaObjectID 33 type=com.tns.FragmentClass
`

**Comment by slavchev** [comment]
@MomenYasser Glad to hear you solved `RadListView` issue. As for the navigation issue - I confirm we found a memory leak in [our navigation logic](https://github.com/NativeScript/NativeScript/blob/v2.1.0/tns-core-modules/ui/transition/transition.android.ts#L424-L466). 

Here is the [transpiled JavaScript code](https://gist.github.com/slavchev/09b002da392ae6de9e87644aa913f2a9). The main idea is to wrap the parameters (`fragment` and `nativeTransition`) into `WeakRef` objects. For the sake of simplicity I wrapped `fragment` only as the other parameter is not used in the code (I commented its usage).

Please review [my changes](https://gist.github.com/slavchev/eedb46cb065a465cc13bbbb64dd2142b) as I did them on the fly without testing.

ping @hshristov

**Comment by MomenYasser** [comment]
@slavchev Thanks a lot.
Actually i didn't resolve `RadListView` issue, I Changed it to `ListView` Because i can't know why `RadListView` log infinity logs and causes app crashing in first 2 mins from app starting. 
App now don't crash but still take Huge MBs from RAM. 
Let's say i have two routes X and Y . and X is the initial route
So, App will start with RAM Usage 85 MB. Now navigate to route Y and that number will increase to 
be 100 MB . Now back to route X it will be 120 and so on, This number will increase and increase
while navigation until app crashes.

I can't understand this behavior actually, My app is still small now but i it will became bigger and Complecated by the time, because of that i need to resolve that memory issue ASAP

What i am doing now is finding a way to clean all variables i am using in any component in
`ngOnDestroy` event. so any help will be appreciated :smile: .

Thanks

**Comment by MomenYasser** [comment]
@slavchev, So calling [Nativescript GC](https://docs.nativescript.org/api-reference/modules/_utils_utils_.html) Will stop improve memory management and stop memory leaks?? 
If that true where should i call it? Thanks :)

**Comment by slavchev** [comment]
@MomenYasser Calling `gc()` may help in some scenarios but it should be used with caution. I created a small [sample](https://github.com/slavchev/sample-gc-oom) that demonstrates the issue in details.

**Comment by MomenYasser** [comment]
@slavchev perfect :D
