### ISSUE TITLE
Extending SegmentedBar to remove borders

### ISSUE THREAD

**Issue by gsaadeh** [NativeScript/NativeScript#2640]
I have a requirement where I want to remove the borders from the SegmentedBar on iOS. I figured the best way to do this is by extending the existing SegmentedBar and overriding the insert tab method. In the insert tab event, I can set the background to a clear image and even remove the separators. 

In my components folder, I've created a custom plugin as follows:

.common file:

```
import * as app from 'application';
import * as dialogs from 'ui/dialogs';
import definition = require("ui/segmented-bar");

export class MSegmentedBar extends definition.SegmentedBar {
    constructor() {
        super();
        console.log('Plugin is working!!');
    }
}
```

.ios file:

```
import common = require("./msegmentedbar.common");

export class MSegmentedBar extends common.MSegmentedBar {
      constructor() {
        super();
      }
}
```

and then reference it in my view:

```
<Border xmlns:x="components/msegmentedbar/msegmentedbar">
        <GridLayout rows="auto, *">
            <x:MSegmentedBar id="group-bar">
                <SegmentedBar.items>
                    <SegmentedBarItem title="Now" selectedTextColor="#fff" borderColor="transparent" />
                    <SegmentedBarItem title="Today" selectedTextColor="#fff" />
                    <SegmentedBarItem title="Week" selectedTextColor="#fff" />
                    <SegmentedBarItem title="Month" selectedTextColor="#fff" />
                </SegmentedBar.items>
            </x:MSegmentedBar>
...
```

Because not all the delegates are exported, the app runs, shows the console.log messages but doesn't render the items. If I do any sort of binding on the selectedIndex, it throws an exception. 

Is it possible at all to make this work or should we wait till the team completely exposes all the delegates?
### Additional info

NativeScript: 2.2.1
tns-core-modues: 2.2.1
Platform: iOS

**Comment by enchev** [comment]
Hey @gsaadeh,

In my opinion you should extend first the native class (UISegmentedControl) and later use it in a JavaScript wrapper [simmilar to our SegmentedBar](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/segmented-bar/segmented-bar.ios.ts#L98). You can check various examples on how to remove UISegmentedBar borders: http://stackoverflow.com/questions/9314927/remove-uisegmentedcontrol-separators-completely-iphone

**Comment by gsaadeh** [comment]
Thanks @enchev. Your approach requires that I completely rewrite the SegmentedBar while I should be able to extend the one that you already have. Even without me adding any native code, I am not able to make the extended SegmentedBar work.

**Comment by zh-m** [comment]
The border of the SegmentedBar can be styled through CSS as easy as: 

`SegmentedBar {
    border-color: mediumspringgreen;
    border-width: 5;
    border-radius: 5;
    height: 75;
    color: deeppink;
}
`


The border between the items can be styled through the selectedBackgroundColor property of the SegmentedBar:

`<SegmentedBar selectedBackgroundColor="transparent">`

The result will be:
![segmentedbar](https://cloud.githubusercontent.com/assets/17438369/19559604/45142d08-96d9-11e6-825e-b98f11894bf2.png)
