### ISSUE TITLE
Nativescript Camera module problem

### ISSUE THREAD

**Issue by terhoraj** [NativeScript/NativeScript#2642]
After taking three images in a row I got this error. If I set image size big enough I get it at the first time.
I'm using Android with newest nativescript, tns-core-modules and tns-android components. 

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=3453, result=-1, data=null} to activity {APP_NAME/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onActivityResult failed

Error: java.lang.OutOfMemoryError: Failed to allocate a 38340876 byte allocation with 15125576 free bytes and 14MB until OOM
    dalvik.system.VMRuntime.newNonMovableArray(Native Method)
    android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
    android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:838)
    android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:814)
    android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:474)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:862)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:727)
    com.tns.Runtime.callJSMethod(Runtime.java:713)
    com.tns.Runtime.callJSMethod(Runtime.java:694)
    com.tns.Runtime.callJSMethod(Runtime.java:684)
    com.tns.NativeScriptActivity.onActivityResult(NativeScriptActivity.java:69)
    android.app.Activity.dispatchActivityResult(Activity.java:6441)
    android.app.ActivityThread.deliverResults(ActivityThread.java:4015)
    android.app.ActivityThread.handleSendResult(ActivityThread.java:4062)
    android.app.ActivityThread.access$1400(ActivityThread.java:177)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5930)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
File: "/data/data/APP_NAME/files/app/tns_modules/camera/camera.js, line: 48, column: 68

**Comment by tsonevn** [comment]
Hi @terhoraj,
Thank you for reporting this issue, however this problem has been already logged in another GitHub issue - [#2460](https://github.com/NativeScript/NativeScript/issues/2460);

Regards,
@tsonevn
