### ISSUE TITLE
Nativescript drawer does not render properly in iOS after device rotating

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/NativeScript#2646]
I have a NS app which uses a drawer (http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/SideDrawer/overview) as navigation.

One odd thing I noticed is that if I rotate the device landscape and then back to potrait, the drawer's main content gets cut to the point that was visible while the device was in landscape mode. This only happens in iOS. It seems that the drawer content does not redraw after rotating back to portrait. If I navigate to another view (where the drawer is loaded again) everything looks good.

Steps to reproduce:
1. load the view
2. open the drawer - everything looks good
3. close the drawer
4. rotate device in landscape
5. rotate back in portrait
6. open drawer - the content is cut up to the point equivalent of the width of the device (the portion that would be visible when the device is in landscape mode) 

Has anyone experienced this issue? Any ideas on how to solve it?

Related item:  http://stackoverflow.com/questions/39215252/nativescript-drawer-does-not-render-properly-in-ios-after-device-rotating

Thank you.

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-samples#120
