### ISSUE TITLE
Android Webview Cookie

### ISSUE THREAD

**Issue by duongnhatduy** [NativeScript/NativeScript#265]
I have a server that send my app a cookie for authenticated communication. It works well on ios but not android. I supposed cookie isn't implemented for android webview yet? If I want to make it myself how should I start?

**Comment by ErjanGavalji** [comment]
@duongnhatduy, there is no NativeScript-specific implementation of cookies in the WebView component. It is just a wrapper over the native android WebView.

The easiest way to check that is by building a pure android application and checking whether the authentication with your specific website would work...

**Comment by duongnhatduy** [comment]
Sorry, there was some misunderstanding from my side when I was trying to solve the problem. The actual problem I have is with http. In iOS, after I login, there will be a cookie set in the header whenever I make a request. In Android there isn't any. Here how I made it in pure android:
``` java
import com.loopj.android.http.AsyncHttpClient;
import com.loopj.android.http.AsyncHttpResponseHandler;
import com.loopj.android.http.PersistentCookieStore;

  if (ssCookieStore == null){
      ssCookieStore = new PersistentCookieStore(context);
  }
 AsyncHttpClient client = new AsyncHttpClient();
 client.setCookieStore(ssCookieStore);
```

In nativescript modules, the request is made from com.tns.Async.Http.MakeRequest. I wonder if it handles cookies.

**Comment by truongsinh** [comment]
It seems https://github.com/NativeScript/android-runtime/blob/master/src/src/com/tns/Async.java does not handle cookie at all!

**Comment by atanasovg** [comment]
Hey @truongsinh, thanks for submitting this issue. I was wondering - should we support persistent cookie store or the default in-memory store that is valid until the application's VM is live and running (that is, the process spawned for the application is live)? The in-memory solution is as simple as:

```java
CookieManager cookieManager = new CookieManager();
CookieHandler.setDefault(cookieManager);
```

What do you think?

**Comment by AntonioCuevaUrraco** [comment]
This solution seams to work

```ts
export function pageNavigatedTo(args: EventData) {
    // Get the event sender
    var page: Page = <any>args.object;
    var source = new Observable();
    context = page.navigationContext;
    var url = "url";
    
    //For android we have to insert the cookie manually
 
        //Create a cookie string
        var cookieString = "yourCookieName" + "=" + "yourCookieValue" + "; domain=" + "yourDomain";

        //Set the cookie for the webview
        var cookieSyncManager = android.webkit.CookieSyncManager.createInstance(androidContext);
        var cookieManager = android.webkit.CookieManager.getInstance();
        cookieManager.setAcceptCookie(true);
        cookieManager.removeSessionCookie();
        cookieManager.setCookie(""yourDomain", cookieString);
        cookieSyncManager.sync();
      //console.log("the is in?" + cookieManager.hasCookies())
   
    source.set("url", url);
    page.bindingContext = source;
}
```

**Comment by devna13** [comment]
Is there any example of setting webview cookie in IOS?

**Comment by mourice** [comment]
`if (android.os.Build.VERSION.SDK_INT >= 21) {
				android.webkit.CookieManager.getInstance().setAcceptThirdPartyCookies(webview, true);

			}`
not working getting the following error

Failed resolving method setAcceptThirdPartyCookies on class com.android.webview.chromium.CookieManagerAdapter

**Comment by ergoTech** [comment]
> ```
> if (android.os.Build.VERSION.SDK_INT >= 21) {  		     
> 
> android.webkit.CookieManager.getInstance().setAcceptThirdPartyCookies(webview, true);
> }
> ```
> not working getting the following error
> 
> Failed resolving method setAcceptThirdPartyCookies on class com.android.webview.chromium.CookieManagerAdapter

thnx, work for me
