### ISSUE TITLE
Calling native methods in NativeScript with multiple arguments

### ISSUE THREAD

**Issue by mdanishs** [NativeScript/NativeScript#2653]
I am trying to implement a plugin in NativeScript which uses a [pod](https://github.com/scalessec/Toast) and pod has the following methods.
```
// basic usage
[self.view makeToast:@"This is a piece of toast."];

// toast with a specific duration and position
[self.view makeToast:@"This is a piece of toast with a specific duration and position." 
            duration:3.0
            position:CSToastPositionTop];
```
the basic usage works fine like this:
`frameModule.topmost().ios.controller.view.makeToast("sometext");`

but when i try to send multiple parameters for specific duration and position

`frameModule.topmost().ios.controller.view.makeToast(toastObject.text, 5.0, CSToastPositionTop);`

I get this exception in console

> Actual arguments count: "3". Expected: "1". 

How do we send multiple parameters in to call native functions?

**Comment by m-abs** [comment]
It has to do with the way {N} maps to native function in Objective-c:

I think this is what you need:
https://docs.nativescript.org/runtimes/ios/marshalling/Marshalling-Overview.html#objective-c-selectors

It might help you to generate typescript type definitions for your module
```bash
TNS_TYPESCRIPT_DECLARATIONS_PATH="${pwd}/typings" tns build ios
```
from: https://docs.nativescript.org/runtimes/ios/how-to/Use-Native-Libraries

**Comment by mdanishs** [comment]
@m-abs i went through the links, I get marshalling a bit, but it is for data types, and the second link doesn't give examples, I am using the cocoapods technique. My pods are working fine and methods with only one argument are working fine as well. What I am not getting is to call native methods with more than one argument.

**Comment by mdanishs** [comment]
@m-abs just tried `TNS_TYPESCRIPT_DECLARATIONS_PATH="${pwd}/typings" tns build ios` to see the exposed API I get it now. Thanks a lot.
