### ISSUE TITLE
TextField Line Color

### ISSUE THREAD

**Issue by triniwiz** [NativeScript/NativeScript#2656]
![](https://cloud.githubusercontent.com/assets/6695919/17902733/76c626e2-6936-11e6-8369-dd18f35f6c43.png)

At the moment the only way to style it is by adding the native styles on android it would be great tohave this as a css prop

```xml
<style name="Theme.App.Base" parent="Theme.AppCompat.Light.DarkActionBar">
    <item name="colorControlNormal">#c5c5c5</item>
    <item name="colorControlActivated">@color/accent</item>
    <item name="colorControlHighlight">@color/accent</item>
</style>
```

**Comment by tsonevn** [comment]
Hi @triniwiz,
Thank you for your issue. I found that similar issue - [#859](https://github.com/NativeScript/NativeScript/issues/859) exist and this feature soon will be available.

Regards,
@tsonevn

**Comment by NathanaelA** [comment]
@tsonevn Actually these two issues are different, #859 refers to having per-side borders on fields; this is talking the line color on the Text Entry.  On Android there is a line under each entry field...

**Comment by triniwiz** [comment]
@tsonevn as @NathanaelA metioned this issue is completely different

**Comment by enchev** [comment]
Hey folks,

I've just made background-color to control this for Android TextField:
```CSS
.myTextField {
    color: red;
    background-color: green;
}
```
![image](https://cloud.githubusercontent.com/assets/5804953/19520844/46f3fa78-961a-11e6-9270-b0df3318a75c.png)

What do you think?

**Comment by tjvantoll** [comment]
@enchev Personally I would expect `background-color` to change the whole background of the TextField, because that’s how it works on the web—see https://jsfiddle.net/oh1hueau/, for example.

As a web developer I would want to do `TextField { border-width: 0 0 1 0; border-color: green; }`, because that’s how I’d accomplish this on the web, but I’m not sure how possible that is to make work on both Android and iOS. As a fallback I’d prefer some made up property like `--android-line-color`, so `TextField { --android-line-color: green; }`.

**Comment by enchev** [comment]
Thanks @tjvantoll! I'll try to implement it as close as possible to web.

**Comment by magar91** [comment]
Hello I am trying to do this in some of my app's textfields is there a css prop? if there is which is it?

**Comment by cgebe** [comment]
Hey guys, how can i change the `focused` color? `--android-line-color` does only control the non focused color.

**Comment by erkanarslan** [comment]
Setting border width to 0 does nothing. It is not working.

**Comment by RoyiNamir** [comment]
@enchev Where can we see how to do it ? Do i still need background color prop for this ? Or do i need to use it with border as @tjvantoll suggested...?

**Comment by waszqba** [comment]
Bump, how can we change the underline property?
