### ISSUE TITLE
installing latest version of tns-core-modules

### ISSUE THREAD

**Issue by Robophil** [NativeScript/NativeScript#2659]
Hi,

Am building a plugin and using ui/date-picker as a guide line, and i noticed
`require("utils/utils").Owned` doesn't exist. So i dived into the source i.e `"utils/utils"` and i find out it does there. But when installing from npm i get "tns-core-modules@2.2.0" and whats currently here is `@2.3.0`.

i went as far as checking the version on npm, `["1.2.0","1.3.0","1.4.0","1.5.0","1.5.1","1.5.2","1.6.0-angular-0","1.6.0-angular-1","1.6.0-angular-2","1.6.0-angular-3","1.6.0-angular-4","1.6.0-angular-5","1.6.0","1.6.1-angular-0","1.6.2","1.7.0-angular-0","1.6.2-css-animations-0","1.7.0","1.7.1","2.0.0-angular-0","2.0.0-angular-1","2.0.0-angular-2","2.0.0-angular-3","2.0.0-angular-4","2.0.0-2016-04-14-2615","2.0.0-2016-04-14-2618","2.0.0-2016-04-14-2623","2.0.0-2016-04-15-2640","2.0.0-2016-04-15-2649","2.0.0-2016-04-15-2652","2.0.0-2016-04-15-2661","2.0.0-2016-04-18-2668","2.0.0-2016-04-18-2680","2.0.0-2016-04-18-2683","2.0.0-2016-04-18-2684","2.0.0-2016-04-19-2701","2.0.0-2016-04-19-2702","2.0.0-2016-04-19-2716","2.0.0-2016-04-20-2718","2.0.0-2016-04-20-2720","2.0.0-2016-04-20-2725","2.0.0-2016-04-20-2726","2.0.0-2016-04-21-2739","2.0.0-2016-04-21-2745","2.0.0-2016-04-21-2746","2.0.0-2016-04-22-2757","2.0.0-2016-04-22-2762","2.0.0-2016-04-22-2766","2.0.0-angular-5","2.0.0-2016-04-25-2775","2.0.0-2016-04-25-2786","2.0.0-angular-6","2.0.0-2016-04-26-2803","2.0.0-2016-04-26-2805","2.0.0","2.0.0-2016-04-27-2813","2.0.0-2016-04-27-2818","2.0.0-2016-04-28-2821","2.0.0-2016-04-28-2826","2.0.0-2016-05-03-2842","2.0.0-2016-05-03-2849","2.0.0-2016-05-03-2856","2.0.0-2016-05-05-2863","2.0.0-2016-05-05-2882","2.0.0-2016-05-09-2892","2.0.0-2016-05-09-2893","2.0.0-2016-05-09-2894","2.0.0-2016-05-09-2899","2.0.0-2016-05-09-2900","2.0.0-2016-05-09-2901","2.0.0-2016-05-09-2902","2.0.0-2016-05-09-2903","2.0.0-2016-05-16-2974","2.0.0-angular-7","2.0.0-2016-05-17-2998","2.0.0-2016-05-17-3001","2.0.0-2016-05-17-3002","2.0.0-2016-05-17-3013","2.0.0-2016-05-17-3015","2.1.0-2016-05-18-3030","2.1.0-2016-05-18-3039","2.1.0-2016-05-19-3044","2.1.0-2016-05-19-3043","2.1.0-2016-05-19-3045","2.1.0-2016-05-19-3046","2.1.0-2016-05-19-3047","2.1.0-2016-05-19-3048","2.1.0-2016-05-19-3052","2.0.1","2.1.0-2016-05-19-3062","2.1.0-2016-05-20-3066","2.1.0-2016-05-20-3077","2.1.0-2016-05-20-3087","2.1.0-2016-05-20-3092","2.1.0-2016-05-25-3107","2.1.0-2016-05-25-3114","2.1.0-2016-05-26-3142","2.1.0-2016-05-27-3156","2.1.0-2016-05-27-3161","2.1.0-2016-06-03-3268","2.1.0-2016-06-03-3271","2.1.0-2016-06-03-3278","2.1.0-2016-06-03-3281","2.1.0-2016-06-07-3314","2.1.0-2016-06-07-3316","2.1.0-2016-06-08-3329","2.1.0-2016-06-08-3339","2.1.0-2016-06-08-3352","2.1.0-2016-06-13-3392","2.1.0-2016-06-13-3395","2.1.0-2016-06-13-3400","2.1.0-2016-06-13-3403","2.1.0-2016-06-14-3425","2.1.0-2016-06-14-3438","2.1.0-2016-06-14-3443","2.1.0-2016-06-15-3470","2.1.0-2016-06-16-3480","2.1.0-2016-06-16-3484","2.1.0-2016-06-16-3487","2.1.0-2016-06-16-3490","2.1.0-2016-06-17-3493","2.1.0-2016-06-17-3496","2.1.0-2016-06-17-3500","2.1.0-2016-06-17-3501","2.1.0-2016-06-17-3502","2.1.0-2016-06-17-3507","2.1.0-2016-06-20-3509","2.1.0-2016-06-20-3527","2.1.0-2016-06-20-3531","2.1.0-2016-06-21-3532","2.1.0-2016-06-21-3533","2.1.0-2016-06-21-3537","2.1.0-2016-06-22-3542","2.1.0-2016-06-22-3546","2.1.0-2016-06-24-3567","2.1.0-2016-06-24-3569","2.1.0-2016-06-24-3572","2.1.0-2016-06-29-3601","2.1.0","2.2.0-2016-07-05-3640","2.2.0-2016-07-06-3646","2.2.0-2016-07-06-3649","2.2.0-2016-07-08-3660","2.2.0-2016-07-08-3665","2.2.0-2016-07-11-3667","2.2.0-2016-07-12-3682","2.2.0-2016-07-13-3685","2.2.0-2016-07-13-3686","2.2.0-2016-07-14-3692","2.2.0-2016-07-18-3700","2.2.0-2016-07-18-3724","2.2.0-2016-07-18-3725","2.2.0-2016-07-19-3737","2.2.0-2016-07-19-3743","2.2.0-2016-07-19-3744","2.2.0-2016-07-19-3745","2.2.0-2016-07-20-3750","2.2.0-2016-07-20-3751","2.2.0-2016-07-20-3754","2.2.0-2016-07-20-3760","2.2.0-2016-07-21-3777","2.2.0-2016-07-21-3778","2.2.0-2016-07-22-3795","2.2.0-2016-07-22-3796","2.2.0-2016-07-25-3800","2.2.0-2016-07-25-3805","2.2.0-2016-07-25-3807","2.2.0-2016-07-26-3815","2.2.0-2016-07-26-3822","2.2.0-2016-07-27-3824","2.2.0-2016-07-27-3831","2.2.0-2016-07-27-3834","2.2.0-2016-07-28-3835","2.2.0-2016-07-28-3839","2.2.0-2016-07-29-3845","2.2.0-2016-07-29-3847","2.2.0-2016-07-29-3849","2.2.0-2016-08-01-3858","2.2.0-2016-08-01-3859","2.2.0-2016-08-01-3862","2.2.0-2016-08-02-3872","2.2.0-2016-08-03-3874","2.2.0-2016-08-03-3877","2.2.0-2016-08-05-3881","2.2.0-2016-08-07-3885","2.3.0-2016-08-09-3890","2.2.0","2.3.0-2016-08-11-3894","2.3.0-2016-08-11-3895","2.3.0-2016-08-12-3900","2.3.0-2016-08-15-3905","2.3.0-2016-08-16-3908","2.3.0-2016-08-16-3911","2.3.0-2016-08-17-3919","2.3.0-2016-08-17-3922","2.3.0-2016-08-18-3927","2.3.0-2016-08-18-3928","2.2.1","2.3.0-2016-08-23-3955","2.3.0-2016-08-23-3958","2.3.0-2016-08-25-3961","2.3.0-2016-08-29-3967","2.3.0-2016-08-29-3966","2.3.0-2016-08-30-3994","2.3.0-2016-08-30-3997","2.3.0-2016-08-30-3998","2.3.0-2016-08-31-4000","2.3.0-2016-08-31-4003","2.3.0-2016-08-31-4006","2.3.0-2016-09-01-4009","2.3.0-2016-09-01-4010","2.3.0-2016-09-01-4013"]` and i installed the latest which is `2.3.0-2016-09-01-4013` but it doesn't reflect the changes on `"utils/utils"` on this repo. 

Am adding a listener so i need the `Owned` of `utils/utils`. Any way around this?

**Comment by tsonevn** [comment]
Hi @Robophil ,

Thank you for reporting your problem.
The latest official version of tns-core-modules is 2.2.0 and this version will be installed, when you install NativeScript with `npm install -g NativeScript`. In case you want to use next NativeScript version, which is still under development, you could follow the below described steps:

1. `npm uninstall -g nativescript`
2. `npm install -g nativescript@2.3.0-2016-09-01-6572`

In case you will use existing project you should also remove and add tns-core-modules.
3. `tns plugin remove tns-core-modules`
4. `tns plugin add tns-core-modules@next`

In regard to your question could you give us more info about your problem?

Regards,
@tsonevn

**Comment by Robophil** [comment]
Thanks for your response @tsonevn . Am building a plugin for number picker in typescript and am actively following your source. Its been nice so far :100:  . I found out most of the goodies i find on your source is not available on my locally installed version. Like `styler` from `("ui/styling/style")` and `("utils/utils").Owned` when using weakRef with listeners on android. Which throws error on vscode.

is the latest version stable enough to use?

**Comment by tsonevn** [comment]
Hi @Robophil,
I am glad to hear that you have solved your problem.

At the moment latest NativeScript version is 2.2.0, which is stable to be used.   2.3.0 is our next version that will be officially released next week and then  you will be able to upgrade your projects to the latest NativeScript.

In case you have other problem related with NativeScript you could open new Issue in GitHub or to use our StackOverflow channel [here](http://stackoverflow.com/questions/tagged/nativescript).


Regards,
@tsonevn

**Comment by Robophil** [comment]
Thanks. Looking forward to this. I've wrapped up my work on the number-picker. here [number-picker](https://github.com/Robophil/nativescript-numberpicker). Looking forward to getting this update.

**Comment by sagar1911** [comment]
Hi @tsonevn sir,
I have updated to 3.3 but got some errors, So now I want to restore the previous version(i.e 3.2). How can I do that ??

**Comment by tsonevn** [comment]
Hi @sagar1911,
Could you give us some more info about the problem s, which you re facing after the upgrade to NativeScript  3.3?
