### ISSUE TITLE
Styling ActionBar in css file carries over to other view

### ISSUE THREAD

**Issue by firescript** [NativeScript/NativeScript#2661]
### Tell us about the problem

When you style ActionBar in a views css, it carries those ActionBar properties over to the next view you navigate to. 
### Which platform(s) does your issue occur on?

iOS not sure about android
### Please provide the following version numbers that your issue occurs with:
- CLI: 2.2.1
### Please tell us how to recreate the issue in as much detail as possible.

use this project:

[actionbarbug.zip](https://github.com/NativeScript/NativeScript/files/450026/actionbarbug.zip)

**Comment by tsonevn** [comment]
Hi @firescript,
Thank you for reporting this issue.
I reviewed the given project and confirm that this is a real issue, when you set ActionBar style in the view css file.  This issue has been reproducible only for iOS.

**Comment by leocaseiro** [comment]
I confirm this issue

**Comment by DomGaud** [comment]
I too confirm this issue

**Comment by hamorphis** [comment]
I tried to reproduce this, but it seems to be working properly with the master branch of the modules. I added a UI test to verify this: https://github.com/NativeScript/NativeScript/blob/master/apps/app/ui-tests-app/issues/issue-2661.xml

**Comment by hamorphis** [comment]
It appears that this bug has been fixed with the following pull request: https://github.com/NativeScript/NativeScript/pull/2994

**Comment by firescript** [comment]
Thanks!
