### ISSUE TITLE
Image preview does not work on iOS

### ISSUE THREAD

**Issue by pawelangelow** [NativeScript/NativeScript#2666]
I've checked known issues, but the one that match most is already closed, so I'm opening new one.

I've created [ScreenBuilder application](https://www.dropbox.com/s/ae7g6facxzay1zm/NSImages.zip?dl=0) for displaying images. In simulator works fine, deployed on Android works fine, deployed on iOS works, except in List View of the app.

In the code, there is helper to resolve the link of the image, so the link is correct.

To the core of the problem:
In file **app/masterDetailView/masterDetailView.xml** there is 
`<Image src="{{ imageImg }}" row="1" col="1" stretch="aspectFit" cssClass="image-field alignment-left" />`
The image binding is made through helper for resolving hyperlink. That can not be the problem, because it works deployed on android and it works in **app/masterDetailView/detailsView/itemDetails.xml** (the binding has different name, but it uses the same helper). The helper itself doesn't make requests, it just transforms dataId to hyperlink. Here is the code:

> function processImage(img, dbConfiguration) {
>     function isAbsolute(img) {
>         if (img && (img.slice(0, 5) === 'http:' || img.slice(0, 6) === 'https:' || img.slice(0, 2) === '//' || img.slice(0, 5) === 'data:')) {
>             return true;
>         }
>         return false;
>     }
>     if (!img) {
>         var empty1x1png = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVQI12NgYAAAAAMAASDVlMcAAAAASUVORK5CYII=';
>         img = 'data:image/png;base64,' + empty1x1png;
>     } else if (!isAbsolute(img)) {
>         var setup = dbConfiguration || {};
>         img = setup.scheme + ':' + setup.url + setup.appId + '/Files/' + img + '/Download';
>     }
>     return img;
> }

In this example of application, the data provider is Backend services.

[The problem](https://drive.google.com/file/d/0B2vtpUNpEkJTZXY3WTFobXczaTg/view?usp=sharing)
[In different view, it works](https://drive.google.com/open?id=0B2vtpUNpEkJTRXpRdnJwWHV2SEE)

**Comment by enchev** [comment]
Hey @pawelangelow,

Are you loading these images via http? In latest iOS http is forbidden by default:
http://stackoverflow.com/questions/30731785/how-do-i-load-an-http-url-with-app-transport-security-enabled-in-ios-9

**Comment by pawelangelow** [comment]
Hi, @enchev !

If that was the case, I think images in Details View of the app should not appear too, but they do. In both views, images are resolved by the same method.

**Comment by tsonevn** [comment]
Hi @pawelangelow,

Using [ImageCache](https://docs.nativescript.org/cookbook/ui/image-cache) module for loading Images in the ListView should resolve this problem. I am attaching [sample project](https://github.com/tsonevn/ListViewImageCache.git), where has been used ListView with ImageCache, based on [this](http://pstaev.blogspot.bg/2016/04/using-nativescripts-imagecache-to-cache.html) article.

Regards,
@tsonevn
