### ISSUE TITLE
Cannot edit width of Repeater

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#2667]
**Platform:** iOS
**TNS:** 2.2.1

Am trying to make a slider using `Repeater` to push slide views. Everything works when not using a `Repeater`. But when I do use it, the `Repeater` cannot change its width at all. Its width seems to be locked to the screen width.

**XML**
```
1  <AbsoluteLayout id="photos-slideShow" class="slide-show">
2    <ScrollView orientation="horizontal" class="photos">
3      <StackLayout orientation="horizontal" class="slide-container" width="{{ photosInfo.count, cameraView_height * (photosInfo.count + 2) }}">
4        <Repeater items="{{ photosInfo.photos }}" width="300">
5          <Repeater.itemsLayout>
6            <StackLayout orientation="horizontal" class="slide-wrapper" id="photos-wrapper" />
7           </Repeater.itemsLayout>
8           <Repeater.itemTemplate>
9             <Image src="{{ $value }}" stretch="aspectFill" class="photo" />
10          </Repeater.itemTemplate>
11         </Repeater>
12       </StackLayout>
13     </ScrollView>
14   </AbsoluteLayout>
```

Line 3 is a `StackLayout` with a width of the screen times amount of photos (this works). At line 4 you can see that I've set the width to 300. Screen width is 375 (iPhone 6), and the `Repeater` width doesn't change at all (is still 375).

**Comment by tsonevn** [comment]
Hi @NordlingArt, 

thank you for reporting this issue,
I have tested the given code and set StackLayout width to be fixed to 1000 and the repeater width has been set to 300 as it is set in the xml code. In regard to the topic you could use [nativescript-slides](https://www.npmjs.com/package/nativescript-slides), which provides this functionality. In case the plugin is not applicable for you, could you give as some more info or to send us sample project which could be debug locally.

**Comment by NordlingArt** [comment]
@tsonevn - I have used [nativescript-slides](https://www.npmjs.com/package/nativescript-slides) before but wasn't satisfied with its performance as it does not utilize the `pagingEnabled` in a `UIScrollView` for iOS which I think is the perfect way of making a slider (as that is its function). I've been trying to make my own plugin using this method but am struggling with the `Repeater` width.

Anyhow, I seem to have fixed the issue by removing the wrapping `.slide-container`, as that container should obviously be the `itemsLayout`.
