### ISSUE TITLE
Calling dialogsModule.alert inside a custom modal page

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/NativeScript#2675]
_From @roblav96 on September 3, 2016 4:18_

Currently it is not possible to call `modalModule.alert` while a custom modal page is open.

Error:
```
Sep  3 00:12:21 Robs-MBP client[17765]: Warning: Attempt to present <UIAlertController: 0x7ff2e60c89a0> on <UIViewControllerImpl: 0x7ff2e378dda0> whose view is not in the window hierarchy!
```
I'm not sure if this a bug or an iOS limitation, but I thought I'd post an issue just in case.

Thank you!

_Copied from original issue: NativeScript/ios-runtime#636_

**Comment by enchev** [comment]
Hey @roblav96,

I've just tried this and everything worked as expected. Here is my code:

```XML
<Page>
    <Button text="Tap to show modal page" tap="buttonTap" />
</Page>
```

```JavaScript
var Page = require("ui/page").Page;
var Button = require("ui/button").Button;

exports.buttonTap = function (args) {
    var btn = new Button();
    btn.text = "Tap to show alert"
    btn.on("tap", function() {
        alert("Hi!");
    });

    var page = new Page();
    page.content = btn;
    page.showModal()
}
```

**Comment by roblav96** [comment]
@enchev I'm saying, after you've called `page.showModal`, try calling `modalModule.alert` inside modal code while it's open.

**Comment by enchev** [comment]
Hey @roblav96,

My code will open modal page with a button which will open alert while the modal page is open.

**Comment by roblav96** [comment]
@enchev Might be an angular thing. I'll test it again.

**Comment by NathanWalker** [comment]
I have also seen this with NativeScript+Angular (aka, Angular Native)....

Using 2.0 final Angular with `next`, so latest `nativescript-angular` and latest `2.3.0`.

**Comment by erkanarslan** [comment]
I have this problem too. You can show an alert dialog before or after opening a modal but you cannot show it while modal is open.

@enchev  Can you re-open this issue?

**Comment by romandragan** [comment]
The same for me
