### ISSUE TITLE
Page Global Event Touch Not Working !

### ISSUE THREAD

**Issue by MomenYasser** [NativeScript/NativeScript#2676]
Hi,

I need to listen to any touch event on my app to detect inactive user within specific time and log him out.
I'm using page.on event touch to detect it but it not logging anything.
`this.page.on(GestureTypes.touch, (args) => {
    console.log("Touch: x: " + args.getX() + " y: " + args.getY());
});`

│ nativescript           │ 2.2.1           │ 2.2.1          │ Up to date    │
│ tns-core-modules │ 2.2.1           │ 2.2.1          │ Up to date    │
│ tns-android           │ 2.2.0           │ 2.2.0          │ Up to date    |

**Comment by tsonevn** [comment]
Hi @MomenYasser ,
I reviewed your case and found that touch gesture works as expected when you attached it to the page. Could you review the attached code snippets. In case you still have a problem could you give me some more info about your app or if you could send me sample project, which could be debugged locally.


main-page.xml

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <StackLayout backgroundColor="green">
    <Label text="Tap the button" class="title"/>
    <Button text="TAP" tap="{{ onTap }}" />
    <Label text="{{ message }}" class="message" textWrap="true"/>
  </StackLayout>
</Page>
```

main-page.ts

```
import { EventData } from "data/observable";
import { Page } from "ui/page";
import { HelloWorldModel } from "./main-view-model";
import { GestureTypes, GestureEventData } from "ui/gestures";

// Event handler for Page "navigatingTo" event attached in main-page.xml
export function navigatingTo(args: EventData) {
    // Get the event sender
    var page = <Page>args.object;
    var i=0;
    page.on("touch", function (args: GestureEventData) {
        console.log("Tap "+i);
        i++;
    });
    page.bindingContext = new HelloWorldModel();
}
```

main-page.js

```
var main_view_model_1 = require("./main-view-model");
// Event handler for Page "navigatingTo" event attached in main-page.xml
function navigatingTo(args) {
    // Get the event sender
    var page = args.object;
    var i = 0;
    page.on("touch", function (args) {
        console.log("Tap " + i);
        i++;
    });
    page.bindingContext = new main_view_model_1.HelloWorldModel();
}
exports.navigatingTo = navigatingTo;
```

Regards,
@tsonevn

**Comment by MomenYasser** [comment]
Hi @tsonevn ,

Actually i'm attaching the touch event to page but still not working .
see the component
`// Nativescript Core
import { EventData } from "data/observable";
import { Page } from 'ui/page';
import { GestureTypes, GestureEventData, TouchGestureEventData } from "ui/gestures";
import * as platform from 'platform';
import * as db from 'application-settings';
import * as HTTP from 'http';

// Angular
import {
  Component,
  OnInit,
  OnDestroy,
  ViewChild,
  ElementRef,
} from '@angular/core';

// plugins
import * as $q from 'q';
import * as sideDrawerModule from "nativescript-telerik-ui/sidedrawer";
import { RadSideDrawerComponent, SideDrawerType } from "nativescript-telerik-ui/sidedrawer/angular";

// Local
import * as endpoints from './../../../endpoints.js';
import * as env from './../../../env.js';
import { Methods } from './../../providers/methods';

// Screens
import { Home } from './home';

// Ui
import { Header } from './ui/header';
import { Loading } from './ui/loading';
import { Sidedrawer } from './ui/sidedrawer';


@Component({
  selector: "dashboard",
  directives: [
    // Screens
    Home,

    // Ui
    Header,
    Loading,
    Sidedrawer
  ],
  providers: [
    Methods,
  ],
  template: `
  <RadSideDrawer #drawer drawerLocation="Right" [transition]="sideDrawerTransition" (loaded)="loaded(e)">
    <StackLayout tkDrawerContent backgroundColor="#FFF">

      
      <Sidedrawer
        #Sidedrawer
        (sidedrawer)="closeSidebar()"
        [user]="user">
      </Sidedrawer>

    </StackLayout>
    <StackLayout tkMainContent backgroundColor="#E0E0E0">

      
      <StackLayout
        *ngIf="!user || showView === 'collapse'"
        orientation="vertical"
        height="100%"
        width="100%">
          <StackLayout horizontalAlignment="center" orientation="horizontal" height="100%">
            <StackLayout *ngIf="loading" verticalAlignment="center">
              <ActivityIndicator
                busy="true"
                width="80"
                height="80">
              </ActivityIndicator>
              <Label marginTop="20" text="Please wait. We are loading your activities now."></Label>
            </StackLayout>
            <StackLayout *ngIf="!loading && errorMessage" verticalAlignment="center">
              <Label [text]="errorMessage" fontSize="25"></Label>
              <Button marginTop="20" padding="25" text="Try again" (tap)="methods.reload()"></Button>
            </StackLayout>
          </StackLayout>
      </StackLayout>

      <AbsoluteLayout [visibility]="showView" backgroundColor="#F3F3F3" width="100%" height="100%">
        
        <TabView cssClass="tabsWrapper" [(ngModel)]="tabSelectedIndex" height="100%" width="100%">
          
          <StackLayout *tabItem="{title: 'Home'}" [paddingTop]="80-48">

            <Home
              #Home
              *ngIf="user"
              [token]="token"
              [userId]="user?.id"
              (done)="cardsBoxDone()"
              (networkError)="networkError()"
              (serverError)="serverError()">
            </Home>

          </StackLayout>
          
        </TabView>
        

        
        <Header
          #Header
          (navigator)="navigateTo(index)"
          (sidedrawer)="openSidebar()"
          [selected]="0"
          [user]="user">
        </Header>

        
        <Loading #Loading></Loading>
      </AbsoluteLayout>

    </StackLayout>
  </RadSideDrawer>
  `,
  styles: [`

    .dashboardWrapper {
      background-color: #E0E0E0;
    }

    .tabsWrapper {
      width: 100%;
    }

    .tabContent {
      padding: 20;
    }

    .overlayWrapper {
      z-index: 52;
      opacity: 0;
    }

    .sidebarWrapper {
      z-index: 53;
      padding: 20;
      transform: translate(250, 0);
    }


    `]
})

export class DashboardComponent implements OnInit, OnDestroy {
  // User module
  public user;
  public token;

  // Loading
  public loading;

  // Platform
  public screen;

  // Config
  public showView;

  // Sidebar
  private drawer: SideDrawerType;
  public sideDrawerTransition: sideDrawerModule.DrawerTransitionBase;
  @ViewChild(RadSideDrawerComponent) public drawerComponent: RadSideDrawerComponent;

  // Errors
  public errorMessage;

  // View
  public tabSelectedIndex;

  // Routes
  @ViewChild('Home') home: Home;
  @ViewChild('drawer') drawerElm: ElementRef;

  // UI
  @ViewChild('Header') header: Header;
  @ViewChild('Sidedrawer') sidedrawer: Sidedrawer;
  @ViewChild('Loading') loadingScreen: Loading;

  constructor(
    private page: Page,
    private methods: Methods
  ){
    // --- Default Values ---

    // User Module
    this.user = false;
    this.token = db.getString('token');
    // Loading
    this.loading = true;

    // Platform
    this.screen = platform.screen;

    // Config
    page.actionBarHidden = true;
    this.showView = 'collapse';
  }

  loaded(args: EventData) {
    // Get the event sender
    var page = <Page>args.object;
    var i=0;
    page.on("touch", function (args: GestureEventData) {
        console.log("Tap "+i);
        i++;
    });
}

  ngOnInit() {
    // Customize Back Button (you can use promise .then(() => {}))
    this.methods.preventBackButton();

    // HTTP Initialization Request
    // (fetch user data then fetch activities data)
    HTTP
    .request({
      url: env.player.host + env.player.port + endpoints.player.auth,
      method: "GET",
      headers: { 'token': this.token },
      timeout: 5000
    })
    .then((response) => {
      this.methods.validateHttpResponse(response)
      .then((response) => {
        // inject user data
        this.user = response.content.toJSON().data;

      }, (response) => {
        this.networkError();
      })
    }, () => {
      this.networkError();
    })
  }

  ngOnDestroy() {
    // gc();
  }

  ngAfterViewInit() {
    // Sidebar Drawer
    this.drawer = this.drawerComponent.sideDrawer;
    /* Animation types :
     * ----------------
     * FadeTransition()
     * PushTransition()
     * RevealTransition()
     * ScaleDownPusherTransition()
     * ScaleUpTransition()
     */
    this.sideDrawerTransition = new sideDrawerModule.PushTransition();
  }


  cardsBoxDone() {
    setTimeout(() => {
      // Kill Loading
      this.loading = false;
      // Show View
      this.showView = 'visible';
    })
  }

  // Sidebar
  openSidebar() {
    this.drawer.showDrawer();
  }

  closeSidebar() {
    // Defined Defer
    let $d = $q.defer();

    this.drawer.closeDrawer();

    setTimeout(() => {
      // Run Action
      $d.resolve();
    }, 400);

    // Return Promise
    return $d.promise;
  }
  // Request Error
  serverError() {
    // Defined Defer
    let $d = $q.defer();

    // Close any Loading
    this.loadingScreen.hide();

    // Alert The Error
    alert('Server error (fetching user data). Please try again');

    // Run Action after alert
    $d.resolve();

    // Return Promise
    return $d.promise;
  }

  networkError() {
    // Kill Loading
    this.loading = false;
    // Update Message
    this.errorMessage = 'Error with your internet connection. Please try again';
  }

  navigateTo(id){
    this.tabSelectedIndex = id-1;
  }

}
`

**Comment by MomenYasser** [comment]
@tsonevn ,
I found the reason ... the all elements over the page is preventing touch event to page .. if i removed all elements in screen it works fine :(

**Comment by tsonevn** [comment]
Hi @MomenYasser,

I review your scenario ones again and found that this is something expected for Android in case you have attached another event in the inner Layouts in your project. 

For your case you could use `Application Events` and to handle, for example,  the `exit event`, when the  application is about to exit and then to log out the user in your application . 

You could read more about  [Application Events](https://docs.nativescript.org/core-concepts/application-lifecycle#use-application-events) in the documentation.

I hope this is applicable for you

**Comment by csi-stasik** [comment]
@tsonevn It would be great to have such of feature (like global touch or handle any user interaction). I have the following scenario:

My app never go to sleep so after x seconds I want to dim the brightness and on touch restore the previous intensity.
