### ISSUE TITLE
Create plugin from c++ library (.so + .h files)

### ISSUE THREAD

**Issue by pinderko** [NativeScript/NativeScript#2680]
Hello,

I need comunicate with some device and distributor of these device gave me a library for linux (x86 or arm11). I don't know, how create plugin for nativescript app, where I need call functions from library. 

I found tutorial to create plugins, which I also tried it and it works, but it was only jar file or java files. 

http://developer.telerik.com/featured/using-native-libraries-in-nativescript/

Now, I have some .so file and headers which are probably written on c++. I don't any idea, how to call some functions, from header files. I also got some demo application, but it was made for windows as desktop.

I paste here some part of heade file.

```
#ifndef EFox_DLL_H
#define EFox_DLL_H

#include "OS_Spec.h"

#if defined _WIN32 || defined __MINGW32__ || defined _WINDOWS || defined MINGW
	#if defined EFoxProg_NO_EXPORT_API
		#define EFox_DLL_API
	#elif defined EFox_Export_Functions
		#define EFox_DLL_API __declspec(dllexport)
		#undef AFX_DATA
		#define AFX_DATA AFX_EXT_DATA
	#else
		#define EFox_DLL_API __declspec(dllimport)
	#endif
#else  // #if defined _WIN32 || defined __MINGW32__ || defined _WINDOWS || defined MINGW
	#define EFox_DLL_API
#endif // #if defined _WIN32 || defined __MINGW32__ || defined _WINDOWS || defined MINGW

// maximal count of connected fiscal printers
#define MAX_FP_COUNT 16

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// This methods are exported from the CommFP.dll

#ifndef DISABLE_USB_CONNECTION

//return value is handle to connected fiscal printer
//to get connection error code use "GetLastComError(0)"
//zero means not connected
EFox_DLL_API int WINAPI ConnectUSB(int f_nPortNum);

#ifdef NAMED_PORTS
//return value is handle to connected fiscal printer
//to get connection error code use "GetLastComError(0)"
//zero means not connected
EFox_DLL_API int WINAPI ConnectUSBName(LPCSTR f_pcPortName);
#endif //#ifdef NAMED_PORTS
```

And I also paste my try of plugin

```
var application = require("application");
 
module.exports = {
    cUSB: function(port){
        var nh = ConnectUSB(port);
        if(nh == 0){
            alert(ProcessError(GetLastComError(0)));
        }else{
            alert('connected');
        }
    }

};
```

I will be very thankful, If I'll get some useful information about my issue. Thanks.

**Comment by slavchev** [comment]
Hi @pinderko 

I can explain the C++ libraries support in NativeScript Runtime for Android (regarding the iOS bridge you can create Objective-C wrappers and use them from Xcode).

Firstly, let me say that the support for C++ libraries is in very early stage and so far it is not backed with real-world scenarios. With that said, let's see what your options are:
* Write Java wrappers with `native` methods that call the C/C++ library
* Use clang/llvm to parse the header files
* Create native module and then `require` it from JavaScript

In first two scenarios the goal is to generate `*.java` (or `*.class`) files so we can read the metadata (think reflection) which will make the APIs visible from JavaScript. Currently, we have no tools that you can use to automate the process.

I guess you may find the last option the most easiest way to go. You can find a sample project at [NativeScript/sample-native-module](https://github.com/NativeScript/sample-native-module).
