### ISSUE TITLE
On Android soft menu hiding app content

### ISSUE THREAD

**Issue by hypery2k** [NativeScript/NativeScript#2683]
I'm currently having issues in my app an android device with soft menu keys. It's hiding the bottom content. I didn't found anything in the documentation. 

How can I handle this?

**Comment by tsonevn** [comment]
Hi @hypery2k ,
Thank you for reporting your issue. 
I have made a little research and found that possible solution of your problem could be to use full-screen layouts on Android in your NativeScript App. How to do this you could find in [this](https://bradmartin.net/2016/03/10/fullscreen-and-navigation-bar-color-in-a-nativescript-android-app/) article. In the article has been also shown how to style Navigation Bar in Android.

I hope this will be applicable for your project.

**Comment by hypery2k** [comment]
yes it works, but a little bit weird to use fullscreen then ;)

**Comment by tsonevn** [comment]
related to issue [#2691](https://github.com/NativeScript/NativeScript/issues/2691)
