### ISSUE TITLE
I got nothing in grid layout 

### ISSUE THREAD

**Issue by 1392324000** [NativeScript/NativeScript#2684]
table.xml
```xml
<Page loaded="loaded">
    <GridLayout id="table" rows="*,*,*,*,*,*" columns="*,*,*,*,*,*,*">        
    </GridLayout>
</Page>
```

table.js
```javascript
var LabelModule = require("ui/label");
function loaded(args) {
    page = args.object;
    var gridLayout = page.getViewById("table");
    
    for (var j = 0; j < 6; j++) {
        for (var k; k < 7; k++) { 
            var grid = new LabelModule.Label;
            gridLayout.addChild(grid);
            grid.text = j + "," + k;
            gridLayout.setRow(grid, j);
            gridLayout.setColumn(grid, k);

        }
    }
}
exports.loaded = loaded;
```

In the Js file ,everything in for loop seems not working ,is there something wrong?

**Comment by NordlingArt** [comment]
It appears that the ’addChild()’ function has been renamed to ’insertChild()’ instead. So try that.

**Comment by 1392324000** [comment]
@NordlingArt  
I changed addChild() to insertChild(),I got nothing too.
And in the first "for loop" it can alert anything,but alert function seems no use  in the second .

**Comment by NordlingArt** [comment]
@1392324000 - In the second for loop you haven't declared a starting index to variable `k`. Now it says `var k;`, should be `var k = 0;`.

**Comment by 1392324000** [comment]
@NordlingArt oh, k! it's a big mistake . Haha~~
After fixing it , a err report tellme "gridLayout.setColumn is not a function" ,and "gridLayout.setRow is not a function" ,too.

**Comment by hshristov** [comment]
setRow, setColumn are static functions (e.g. on the type GridLayout) not a instant functions.

**Comment by atanasovg** [comment]
@1392324000 This line:
```
var grid = new LabelModule.Label;
```

Should be
```
var grid = new LabelModule.Label();
```

**Comment by 1392324000** [comment]
@NordlingArt @atanasovg @hshristov 
thank you guys . I got it. :-)

![screenshot_2016-09-07-16-37-13](https://cloud.githubusercontent.com/assets/4407761/18305323/9c378fe4-7519-11e6-9596-738fe8c71a90.jpeg)
