### ISSUE TITLE
[iOS] LiveSync suddenly stopped working ("Unable to kill the application")

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#2690]
LiveSync (TNS 2.2.1) worked well earlier today. Went for a walk outside, came back and it now throws me this error:

```
Project successfully prepared (ios)
Transferring project files...
Successfully transferred all files.
Applying changes...
Transferring project files...
Successfully transferred all files.
Applying changes...
Successfully synced application org.nativescript.naSlideShow on device 7C3FA351-6853-469E-B51C-05098DFB430F.
Unable to kill the application.
```

It does launch the app but the terminal process closes after the error, so I cannot check any further logs. I have tried doing `tns platform remove ios` but still the same. I even tried "Reset Content and Settings..." in the iOS Simulator.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-cli#2043
