### ISSUE TITLE
software navigation buttons hiding app content

### ISSUE THREAD

**Issue by Plamen5kov** [NativeScript/NativeScript#2691]
_From @hypery2k on September 7, 2016 11:57_

I'm currently having issues in my app an android device with software navigation buttons  on the bottom.

It's hiding the bottom content. I didn't found anything in the documentation.

How can I handle this, see also https://github.com/NativeScript/NativeScript/issues/2683

_Copied from original issue: NativeScript/android-runtime#549_

**Comment by hypery2k** [comment]
the [fullscreen solution](https://bradmartin.net/2016/03/10/fullscreen-and-navigation-bar-color-in-a-nativescript-android-app/) works for now, but I don't like the workaround. Any suggestions?

**Comment by bradmartin** [comment]
Do you have screenshots and can you share your code? The navigation bar shouldn't be obstructing anything unless your layout is larger than the device screen height.

**Comment by tsonevn** [comment]
@hypery2k 

You could review the attached example, where has been shown how to hide the  software navigation buttons. However when a tap event has been triggered on the screen the navigation buttons will be shown again. To solve that you could set `gesture` to the Page and for example on `doubleTap` you could hide it again, Another option is to use setTimeInterval, which to hide the buttons. In regard to that could you provide more info about your project.


main-page.xml

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" loaded="pageloaded">
  <StackLayout>
    <Label text="Tap the button" class="title"/>
    <Button text="TAP" tap="{{ onTap }}" />
    <Label text="{{ message }}" class="message" textWrap="true"/>
  </StackLayout>
</Page>
```

main-page.ts

```
import { EventData } from "data/observable";
import { Page } from "ui/page";
import { HelloWorldModel } from "./main-view-model";
import {isAndroid} from "platform";
var app = require("application");
import { GestureTypes, GestureEventData } from "ui/gestures";
import {setInterval} from "timer"

// Event handler for Page "navigatingTo" event attached in main-page.xml
export function pageloaded(args: EventData) {
    // Get the event sender
    var page = <Page>args.object;

    hideMenu();
    page.on("doubleTap", function (args: GestureEventData) {
        hideMenu();
    });
    // setInterval(function(){
    //     hideMenu();
    // }, 10);
    // page.bindingContext = new HelloWorldModel();
}

function hideMenu(){
    if(isAndroid){
        var window = app.android.startActivity.getWindow();
        window.setStatusBarColor(0x000000);
 
        var decorView = window.getDecorView();
        let View = android.view.View;
        decorView.setSystemUiVisibility(
            View.SYSTEM_UI_FLAG_LAYOUT_STABLE
            | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
            | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION);
    }
}
```

I hope this helps

**Comment by hypery2k** [comment]
I will take a look on monday at customers side

**Comment by tsonevn** [comment]
Hi @hypery2k ,

Does the given suggestion solve your problem?

Regards,
@tsonevn

**Comment by hypery2k** [comment]
yes that's working for us. Thanks for your support
