### ISSUE TITLE
Js binding

### ISSUE THREAD

**Issue by locomain** [NativeScript/NativeScript#2692]
Binding does not work as stated in example http://docs.nativescript.org/tutorial/chapter-3

**Comment by tsonevn** [comment]
Hi @locomain,
I have tested data binding and the given example in the chapter and It looks that the binding works as expected. Could you give us some more info about the problem or to provide a sample project, where problem has been reproduced.


Sample code:

main-page.xml

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <StackLayout backgroundColor="green" >
   
    <Label text="{{email}}" textWrap="true" />
    <Label text="{{password}}" textWrap="true" />
    
    
  </StackLayout>
</Page>
```

main-page.js
```
var Observable = require("data/observable").Observable;
var user = new Observable({
    email: "user@domain.com",
    password: "password"
});
// Event handler for Page "navigatingTo" event attached in main-page.xml
function navigatingTo(args) {
    // Get the event sender
    var page = args.object;
    page.bindingContext = user;
}
exports.navigatingTo = navigatingTo;
```


Regards,
@tsonevn

**Comment by locomain** [comment]
Hi, i think there was a error in my own environment thnx for your reply
