### ISSUE TITLE
Cannot add platform to project

### ISSUE THREAD

**Issue by TheLox95** [NativeScript/NativeScript#2694]
## Problem
I have troubles running the `tns platform add android` command.
`Failed to retrieve data from npm. Please try again a little bit later.. Error: Error: shasum check failed for C:\Users\Leonardo\AppData\Local\Temp\npm-5404-6ee83dd8\registry.npmjs.org\tns-android\-\tns-android-2.2.0.tgz
Expected: 089ca9e45e42f39e760deff372a10afc21df1043
Actual:   48c6eda4b8a6b075a2b9f8a2eb59acd98dd57822
From:     https://registry.npmjs.org/tns-android/-/tns-android-2.2.0.tgz
`

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.2.1
- Cross-platform modules:   `2.2.1`
- Runtime(s): There is not any of these properties
- Plugin(s): `"dependencies": {
    "tns-core-modules": "2.2.1"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "^0.3.0",
    "typescript": "^1.8.10"
  }
`

## Question
I just want to know if there is some error with my configuration or if it is an error with the server. Yesterday I update Nativescript so I do not know what is wrong.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-cli#2047
