### ISSUE TITLE
http module does not support *sending* multiple headers with same name

### ISSUE THREAD

**Issue by vbresults** [NativeScript/NativeScript#2701]
This is identical to #1695, except that this is in regards to sending headers instead of receiving.

Ping @enchev

**Comment by NickIliev** [comment]
Hello @vbresults 

Indeed, duplicated headers are not allowed in the **_http_** and **_fetch_** modules at this very moment so I am logging this as a bug. Meanwhile, can you please provide some more information about the scenario where you would need to send multiple headers with the same name.

Some servers can handle multiple header values separated by comma, so if it is applicable in your scenario you can use something like this:
,
`        headers: { "headerA": "value-111, value222" },`

**Comment by vbresults** [comment]
Hello @NickIliev 

Scenario is replaying cookies from another source i.e. a webview javascript call to `document.cookie`.

**Comment by NickIliev** [comment]
ping @hdeshev

**Comment by hamorphis** [comment]
@vbresults This will not be very easy. Here is the native API's that we use for setting the headers:

https://developer.android.com/reference/java/net/URLConnection.html#addRequestProperty(java.lang.String,%20java.lang.String)

https://developer.apple.com/reference/foundation/nsmutableurlrequest/1408793-setvalue

Both of them are key-value-ish and do not allow having the same key multiple times.
