### ISSUE TITLE
Getting an Error with Connectivity.getConnectionType() method

### ISSUE THREAD

**Issue by JaganJonnala** [NativeScript/NativeScript#2704]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

**Comment by JaganJonnala** [comment]
by displaying connectivity.getConnectionType it showing like function getConnectionType() {
 //etc...
//todo.
}
but running that method it shows error

**Comment by JaganJonnala** [comment]
![image](https://cloud.githubusercontent.com/assets/10844009/18435926/6904413c-7913-11e6-927c-8da82ed0ef3d.png)

**Comment by JaganJonnala** [comment]
![image](https://cloud.githubusercontent.com/assets/10844009/18435959/8b270740-7913-11e6-8efd-5750840b4642.png)

**Comment by tsonevn** [comment]
Hi @JaganJonnala,
I reviewed your issue and found that this issue has been related to issue [#1033](https://github.com/NativeScript/NativeScript/issues/1033) and has been caused due to not having permissions to get  network status. To fix this error you should add in `app/App_Resources/Android/AndroidManifest.xml` following permission `<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>`
For your convenience I am also attaching sample project, where has been used `ConnectivityModule`.


main-page.xml

```
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="onLoaded" navigatedTo="onNavigatedTo" navigatingTo="navigatingTo">
  <StackLayout>
    <Label text="Test connectionType" class="title"/>
  </StackLayout>
</Page>
```

main-page.ts

```
import { EventData } from "data/observable";
import { Page } from "ui/page";
import { HelloWorldModel } from "./main-view-model";
import {connectionType, getConnectionType, startMonitoring} from "connectivity"

// Event handler for Page "navigatingTo" event attached in main-page.xml
export function navigatingTo(args: EventData) {
    // Get the event sender
    var page = <Page>args.object;

    page.bindingContext = new HelloWorldModel();
}


export function onNavigatedTo(args:EventData){
    getConnectivity();  
}

function getConnectivity()
{
    startMonitoring(function(newConnectionType: number)
    {
        switch (newConnectionType) {
        case connectionType.none:
            console.log("Connection type changed to none.");
            break;
        case connectionType.wifi:
            console.log("Connection type changed to WiFi.");
            break;
        case connectionType.mobile:
            console.log("Connection type changed to mobile.");
            break;
    }
    })
}
```

main-page.js

```
var main_view_model_1 = require("./main-view-model");
var connectivity_1 = require("connectivity");
// Event handler for Page "navigatingTo" event attached in main-page.xml
function navigatingTo(args) {
    // Get the event sender
    var page = args.object;
    page.bindingContext = new main_view_model_1.HelloWorldModel();
}
exports.navigatingTo = navigatingTo;
function onNavigatedTo(args) {
    getConnectivity();
}
exports.onNavigatedTo = onNavigatedTo;
function getConnectivity() {
    connectivity_1.startMonitoring(function (newConnectionType) {
        switch (newConnectionType) {
            case connectivity_1.connectionType.none:
                console.log("Connection type changed to none.");
                break;
            case connectivity_1.connectionType.wifi:
                console.log("Connection type changed to WiFi.");
                break;
            case connectivity_1.connectionType.mobile:
                console.log("Connection type changed to mobile.");
                break;
        }
    });
}
```
