### ISSUE TITLE
Blog is broken

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/NativeScript#2705]
I know this is probably not the place to report issues with the website but I wasn't sure how else to get in touch. 

Currently all blog articles are throwing an exception.

Eg.

https://www.nativescript.org/blog/announcing-nativescript-code-samples

**Comment by 3rror404** [comment]
It appears to have been fixed.

**Comment by valentinstoychev** [comment]
Thanks for reporting it! It was during our migration to the new website :).
