### ISSUE TITLE
Accessing iOS Pedometer

### ISSUE THREAD

**Issue by marciovicente** [NativeScript/NativeScript#2706]
Hey guys, I'm trying to access the Pedometer ([CMPedometer](https://developer.apple.com/reference/coremotion/cmpedometer)) data from a iOS (real device). 
Basically this is the simple code:

```javascript
  var pedometer = new CMPedometer();
  if(CMPedometer.isStepCountingAvailable()){
      pedometer.queryPedometerData(/*...*/);
  }
```
I've read the CMPedometer documentation but the only method available is `stopPedometerUpdates`. All other methods are undefined (like `queryPedometerData`).

Does anyone have an idea about this?

**Comment by PanayotCankov** [comment]
The method queryPedometerData(from:to:withHandler:)  maybe is mapped as queryPedometerDataFromToWithHandler(....) As a general rule of thumb, read the Objective-C version of the APIs and use the JavaScriptCore convention for name mapping.

**Comment by NickIliev** [comment]
Hey @marciovicente 

If you create your project with TypeScript (`tns create my-app-name --template tsc`) ,then you can install the [tns-platform-declarations](http://stackoverflow.com/questions/37523071/how-can-i-access-native-api-in-nativescript-when-i-use-typescript/37524018#37524018) and you will have IntelliSense in VSCode for all the mapped methods from Objective-C (for iOS) and Java (for Android)

**Comment by marciovicente** [comment]
Nice tips!!! Thanks a lot @NickIliev @PanayotCankov

**Comment by PanayotCankov** [comment]
You can also use this for reference:
https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ios/objc-i386/objc!CoreMotion.d.ts#L309
