### ISSUE TITLE
Label should scale to accommodate content

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/NativeScript#2709]
Hi guys,

I have a GridLayout similar to the below:

```
<GridLayout class="row1" row="1" columns="*, auto, auto, auto, auto, auto, *">
    <Image col="1" src="~/images/clock.png" />
    <Label col="2" id="startTime" text="{{ journey.StartTime_Formatted }}"  tap="onTimeTap" />
    <Label col="3" text="to"  />
    <Image col="4" src="~/images/clock.png" />
    <Label col="5" id="endTime" text="{{ journey.EndTime_Formatted }}" tap="onTimeTap" />
</GridLayout>
```

The two labels at col 2 and col 5 use two-way binding to display a string. 

After updating the model, if the new value is longer than the original, the label doesn't stretch to accommodate the new value. Instead it is cut off and the ellipses is displayed.

Initial value (9:53): 

![label-width](https://cloud.githubusercontent.com/assets/1102402/18472005/97e7daa6-79ac-11e6-926d-e3d625713c29.jpg)

After updating model (10:53):

![label-width2](https://cloud.githubusercontent.com/assets/1102402/18472063/032bd722-79ad-11e6-9f45-c3706439dc31.jpg)

I would expect the label / column to adjust it's width to accommodate the value if there is room in the layout to do so.

Is this by design? Or a bug? 

```
┌──────────────────┬─────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 2.2.1           │ 2.2.1          │ Up to date       │
│ tns-core-modules │ 2.1.0           │ 2.2.1          │ Update available │
│ tns-android      │ 2.2.0           │ 2.2.0          │ Up to date       │
│ tns-ios          │ 2.2.1           │ 2.2.1          │ Up to date       │
└──────────────────┴─────────────────┴────────────────┴──────────────────┘
```

(I'm using core modules 2.1.0 due to https://github.com/NativeScript/NativeScript/issues/2682)

**Comment by NickIliev** [comment]
Hello @3rror404 

I can not reproduce your exact scenario without your code base, but perhaps you can try turning of textWrap for your label.
e.g.
```        
<Label text="" textWrap="false" />
```

**Comment by 3rror404** [comment]
Hi @NickIliev,

I can reproduce with the following reduced example:

Frontend:

```
<GridLayout class="row1" row="1" columns="*, auto, auto, auto, auto, auto, *">
    <Image col="1" src="~/images/clock.png" />
    <Label col="2" id="startTime" text="{{ StartTime_Formatted }}"  tap="onTimeTap" />
    <Label col="3" text="to"  />
    <Image col="4" src="~/images/clock.png" />
    <Label col="5" id="endTime" text="{{ EndTime_Formatted }}" tap="onTimeTap" />
</GridLayout>
```

Codebehind:

```
var Observable = require("data/observable").Observable;

var timeModel = new Observable();
timeModel.StartTime_Formatted = '9:53';
timeModel.EndTime_Formatted = '9:53';

function loaded(args) {
    page = args.object;
    page.bindingContext = timeModel;
}

function onTimeTap(args) {
    timeModel.set('EndTime_Formatted', '10:53');
}
```

There is no CSS file.

I've only tested on Android.

**Comment by NickIliev** [comment]
Hey @3rror404 

I have tested your code and with textWrap="true" (for the EndTime) it works as expected (my bad for the previous answer.. by default textWrap is false so you should set it to true). 
Here is the working code which I have tested on my side.

page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="loaded">
  <GridLayout class="row1" row="1" columns="*, auto, auto, auto, auto, auto, *">
      <Image col="1" src="~/images/clock.png" />
      <Label col="2" id="startTime" text="{{ StartTime_Formatted }}"  tap="onTimeTap" />
      <Label col="3" text="to"  />
      <Image col="4" src="~/images/clock.png" />
      <Label col="5" id="endTime" text="{{ EndTime_Formatted }}" tap="onTimeTap" textWrap="true" />
  </GridLayout>
</Page>
```

page.ts
```
import { EventData } from "data/observable";
import { Page } from "ui/page";

var Observable = require("data/observable").Observable;

var timeModel = new Observable();
timeModel.StartTime_Formatted = '9:53';
timeModel.EndTime_Formatted = '9:53';

export function loaded(args: EventData) {
    var page = <Page>args.object;
    page.bindingContext = timeModel;
}

export function onTimeTap(args: EventData) {
    timeModel.set('EndTime_Formatted', '10:53');
}
```

**Comment by 3rror404** [comment]
Thanks @NickIliev. `textWrap="true"` works.

So is this by design? Or a bug? `textWrap="true"` doesn't seem like an particularly intuitive attribute to have to use to force the desired behaviour.

**Comment by NickIliev** [comment]
@3rror404 

We have tested the same scenario in Android (HorizontalScrollView with TextView - both with match_parent and the tv with singleLine="true" and it appears to be a by design as the exact same behavior was reproduced in the native environment.

**Comment by 3rror404** [comment]
OK that's cool. Thanks for looking in to it. And thanks for the solution.
