### ISSUE TITLE
View.getMeasuredWidth/Height() too slow (or too fast?) to measure during loaded state

### ISSUE THREAD

**Issue by NordlingDev** [NativeScript/NativeScript#2710]
**Platform:** iOS
**TNS:** 2.2.1

There are way too many times I have to wrap this code in a `setTimeout()` during a loaded state, by a 0 to 1 second delay. Shouldn't a loaded state of a view already have its dimensions measured?

Depending on how many stuff that's going on, I have to do this workaround:

**XML**

``` xml
<Page navigatedTo="navigatedTo">
  <GridLayout rows="*" columns="*">
    <StackLayout row="0 loaded="loaded_StackLayout">
      ...
    </StackLayout>
  </GridLayout>
  ...
</Page>
```

**JS**

``` js
exports.loaded_StackLayout = function(args) {
  var view = args.object;

  // Sometimes returns 0
  console.log(view.getMeasuredWidth());

  // Will most likely return the actual size, but is not an ideal solution
  setTimeout(function() {
    console.log(view.getMeasuredWidth());
  }, 100);
};
```

Any better way of measuring a width or height of a view that hasn't been set via CSS or XML?

**Comment by hshristov** [comment]
@NordlingArt What scenario you want to accomplish so that you need the measuredWidth/Height?

**Comment by NordlingArt** [comment]
@hshristov - In short, I am more or less trying to modify a view from the XML so that it has childrens with specific dimensions relative to its parent.

**Comment by triniwiz** [comment]
You can bind to the `layoutChanged` event introduced in `4.1.0` to accomplish this
