### ISSUE TITLE
Android Navigation Bar blocking bottom child DockLayout

### ISSUE THREAD

**Issue by colinskow** [NativeScript/NativeScript#2713]
I have a page with an ActionBar at the top, then a DockLayout with navigation buttons on the bottom and then content stretched to fill the page on top. On Android devices without a system navigation bar there is no problem. On devices with a system navigation bar it blocks the bottom child of the DockLayout.

I know there is a [workaround](https://bradmartin.net/2016/03/10/fullscreen-and-navigation-bar-color-in-a-nativescript-android-app/) to detect the navigation bar height and set padding manually, but I feel this is something NativeScript should take care of automatically. (Since there are few use cases where developers will actually want the Android navigation bar blocking their UI.)

![screenshot_2016-09-14-03-07-20](https://cloud.githubusercontent.com/assets/5303269/18488103/d977413c-79ac-11e6-8058-94ad27977e26.png)

**Comment by NathanaelA** [comment]
Are you using any plugins?  Or any to mess with the action bar?

**Comment by colinskow** [comment]
I copied the same HTML/CSS into a new project and couldn't duplicate the issue. I later figured out I was using the [translucent status bar code](https://docs.nativescript.org/angular/tutorial/ng-chapter-6.html#63-customizing-the-status-bar) from the tutorial, which was causing the issue.

I simply commented out the hide navigation flag and this resolves the problem. The bottom dock is now correctly above the navigation.

```js
if (application.android) {
    application.android.onActivityStarted = function() {
      if (application.android && platform.device.sdkVersion >= "21") {
        var View = android.view.View;
        var window = application.android.startActivity.getWindow();
        window.setStatusBarColor(0x000000);

        var decorView = window.getDecorView();
        decorView.setSystemUiVisibility(
          View.SYSTEM_UI_FLAG_LAYOUT_STABLE
          // | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
          | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
          | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);
      }
    }
  }
```
