### ISSUE TITLE
Changing native views (customizing in XCode) - how does it affect nativescript view layer

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/NativeScript#272]
If a developer customizes a native view that was compiled from nativescript, how does that translate back to nativescript view xml? Or would any/all customizations be overwritten on the next nativescript compile?

Just curious here if any thinking around that.

**Comment by enchev** [comment]
Hey @NathanWalker,

Sorry for this very long delay - it seems that somehow we've missed your post.

If you are using our CLI every time you build the project the changes made in any XML within platforms/ios folder will be overridden. If you want to change something please do it in the file located in app/ folder. More info can be found here:
https://github.com/NativeScript/nativescript-cli#create-project

HTH
