### ISSUE TITLE
Error when trying to run app - Expected "/*", "//" or "{" but "<" found

### ISSUE THREAD

**Issue by firescript** [NativeScript/NativeScript#2725]
CLI: 2.3
iOS 10
Xcode 8

So for some reason when i tns run ios or anything i have to tns platform remove ios then tns platform add ios before it works again. on a fresh platform add it launches the app, but lets say i ctrl+z to exit then run again i get this error
```
Expected "/*", "//" or "{" but "<" found.
```
if i make a change with tns livesync ios --watch i get this error:
```
10:57:02 AM - Compilation complete. Watching for file changes.
Executing before-prepare hook from /Users/ryanlebel/Apps/TeamReps/hooks/before-prepare/nativescript-dev-typescript.js
Unable to sync files. Error is: Expected "/*", "//" or "{" but "<" found.
```

**Comment by firescript** [comment]
This is what fixed it for me: https://github.com/NativeScript/NativeScript/issues/2703#issuecomment-247430766

**Comment by mattwilson1024** [comment]
What fixed it for me was updating cocoapods as follows:

`sudo gem install cocoapods --pre`
`tns platform remove ios`
`tns platform add ios`
`tns build ios`

This took me from v1.0.1 to v.1.2.0.beta.1 of cocoapods (`pod --version`).
