### ISSUE TITLE
Passing the arguments to a nested component

### ISSUE THREAD

**Issue by okmttdhr** [NativeScript/NativeScript#2728]
### Did you verify this is a real problem by searching 

I found there issues, but it's not the same situation, I think.
http://stackoverflow.com/questions/37313514/native-script-how-to-pass-object-from-page-to-custom-component-with-data-bindin
https://github.com/NativeScript/NativeScript/issues/2153

### Please provide the following version numbers that your issue occurs with:
- iOS emulator
- tns: 2.2.1
- node_modules/tns-core-modules/package.json: 2.4.0-2016-09-02-4021
- tns-ios: 2.2.1

### Please tell us how to recreate the issue in as much detail as possible.

Hi, I'm trying to pass the arguments to a nested NativeScript component, but it doesn't work. First, I'm loading `component-one` here in `main-page.xml`.

```xml
// main-page.xml
    <Page
      xmlns="http://schemas.nativescript.org/tns.xsd"
      xmlns:component-one="components/component-one">
        <StackLayout>
          <component-one:component-one />
        </StackLayout>
    </Page>
```

And then, passing the arguments to `component-two` from `component-one`.

```xml
// component-one.xml
    <StackLayout
      loaded="onLoad"
      xmlns:component-two="components/component-two">
      <component-two:component-two name="John" color="{{ colorMain }}" />
    </StackLayout>
```

```ts
// component-one.ts
    export const onLoad = (args) => {
      const container = args.object;
      const viewModel = new Observable();
      viewModel.set("colorMain", "#ffffff"); // I want to change the color from component-one
      container.bindingContext = viewModel;
    };
```

Here is `component-two`, but `color` became `undefined` (No problem for `name` ). I don't know why and how can I solve this??

```xml
// component-two.xml
    <Label
      loaded="onLoad"
      text="{{ name }}"
      color="{{ color }}"></Label>
```

```ts
// component-two.ts
    export const onLoad = (args) => {
      const container = args.object;
      const viewModel = new Observable();
      viewModel.set("name", container.name);
      viewModel.set("color", container.color);
      container.bindingContext = viewModel;
    };
```

I'll appreciate your help..

**Comment by NickIliev** [comment]
Hey @okmttdhr

The reason this is not working is because you should make your binding in the main-page which is the container for all of your nested components. Your app lifecycle will load all the nested components, then its parents and finally the main-page. At this point the binding will be triggered by the Observable.

Here is an example of your scenario with the two level nested components and with a working binding model in the main-page.

**_main-page.xml_**
```
    <Page xmlns="http://schemas.nativescript.org/tns.xsd"
               xmlns:componentOne="component/component-one"
               loaded="onPageLoaded">
        <StackLayout>
          <componentOne:component-one />
        </StackLayout>
    </Page>

```

**_main-page.ts_**
```
import { EventData, Observable } from 'data/observable';
import { Page } from 'ui/page';

export function onPageLoaded(args: EventData) {

  let page = <Page>args.object;

  let vm = new Observable();
  vm.set("color", "red");
  vm.set("name", "Anakin");

  page.bindingContext = vm;
}
```

**_component/component-one/component-one.xml_**
```
<StackLayout xmlns:componentTwo="component/component-two">
    <componentTwo:component-two />
</StackLayout>
```
**_component/component-two/component-two.xml_**
```
<Label text="{{ name }}" color="{{ color }}" />
```

**Comment by okmttdhr** [comment]
@\NickIliev You mean that I could make my binding in the container and couldn't separately in my components. Thank you so much!!
