### ISSUE TITLE
Feature Request: CSS or XML StatusBar support

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#2736]
I have yet to have an app where it wasn't a problem dealing with the status bar... changing the background or text color, transparent, maybe white text, whatever it is, it's always a headache.

Always gotta remember how to do things on iOS or Android, or use a plugin and hope it works, would be nice to have it core "just working"... 

Request: Allow us to modify the statusbar in CSS, or at the very least XML on the page node please :)

**Comment by zh-m** [comment]
Related to [CSS support for styling status bar  ](https://github.com/NativeScript/NativeScript/pull/3156) and [backgroundColor added in ActionBarStyler](https://github.com/NativeScript/NativeScript/pull/3469)
