### ISSUE TITLE
Feature Request: Improved ActionBar CSS Support

### ISSUE THREAD

**Issue by firescript** [NativeScript/NativeScript#2740]
In order to take out the action bar shadow you must use js, here is the code to do it.

```
    if (page.ios) {
        navigationBar.shadowImage = new UIImage();
        navigationBar.setBackgroundImageForBarMetrics(new UIImage(), UIBarMetrics.UIBarMetricsDefault)
    }   
```

I think it would make sense to make use of the border css property to over ride that. Setting `border: 0;` on an ActionBar, should remove that naturally. 

The other thing is I cant seem to set the actionbar to transparent/transulcent? `background-color:transparent;` or `background-color: rgba(0,0,0,.8)` would make sense, in combination with the removal of the shadow on the action bar, it would give me a clean, transparent/transulcent actionbar.

**Comment by sitefinitysteve** [comment]
+1 for "transparent"

**Comment by wnas** [comment]
+1 for border 0 in css.

**Comment by pmz** [comment]
+1. This is bugging me :)

**Comment by EddyVerbruggen** [comment]
Please join the discussion at #3900, thanks!

**Comment by vakrilov** [comment]
@EddyVerbruggen Thanks for the great PR - it is merged now.
@SvetoslavTsenov Can you please add this scenario in the e2e tests for the action-bar.

**Comment by SvetoslavTsenov** [comment]
A test is already included but I found an issue on iOS. When we update the flat prop. from code behind it doesn't update the UI.
Here is the sample page that we use:
https://github.com/NativeScript/NativeScript/blob/master/apps/app/ui-tests-app/action-bar/flat.ts
Please have in mind that so far for Android is it working perfectly fine.
