### ISSUE TITLE
Android: getMeasuredWidth and getMeasuredHeight return wrong measurements when the _nativeView is set

### ISSUE THREAD

**Issue by kvelikov** [NativeScript/NativeScript#2746]
The getMeasuredWidth and getMeasuredHeight methods return wrong measurements in android when the _nativeView is set. This can cause trouble when implementing custom Layout.

**Comment by rrcoolp** [comment]
That's right - I have the same problem....

My APP returns correct value in IOS....but on Android see the details for device below...

AMAZON FIRE HD:

Width of the Screen returned by NPM MODULE: nativescript-swiss-army-knife/nativescript-swiss-army-knife - is 533.33 where as the function for a FULL WIDTH element is returning: 740....The correct value is actually less than 533.333 (as I have some padding on that element)....

**Comment by tsonevn** [comment]
The issue seems to be fixed with the upcoming modules version 4.0.
