### ISSUE TITLE
[FEATURE] onNewIntent event listener

### ISSUE THREAD

**Issue by petekanev** [NativeScript/NativeScript#2747]
_From @roblav96 on September 17, 2016 1:59_

I'm not too sure how hard it would be to implement, but having a `onNewIntent` event would be awesome.

I'm trying to make a custom url plugin but in order for it to work properly I need to set `android:launchMode="singleTask"` on the `com.tns.NativeScriptActivity` in `AndroidManifest.xml` because if I don't, then the intent launches a whole new instance of my app on top of the already existing one.

I tried this with every android event available:

``` typescript
application.android.on(application.AndroidApplication.activityResumedEvent, function(args: application.AndroidActivityEventData) {
    global.tnsconsole.info('application.AndroidApplication.activityResumedEvent >')
    let intent: android.content.Intent = args.activity.getIntent()
    global.tnsconsole.log('intent.getData()', intent.getData())
    global.tnsconsole.log('intent.getDataString()', intent.getDataString())
    global.tnsconsole.log('intent.getScheme()', intent.getScheme())
    global.tnsconsole.log('intent.getExtras()', intent.getExtras())
})
```

and they all come up empty.

According to [EddyVerbruggen/Custom-URL-scheme](https://github.com/EddyVerbruggen/Custom-URL-scheme/blob/master/src/android/nl/xservices/plugins/LaunchMyApp.java#L73), he calls `onNewIntent` which is exactely what I'm looking to do. I also tried making my custom activity and overwriting the event, but it doesn't exist in `ui/frame/AndroidActivityCallbacks`.

This addition would be greatly appreciated!

_Copied from original issue: NativeScript/android-runtime#558_

**Comment by roblav96** [comment]
## This is how you do it:
```typescript
import * as application from "application"
import * as frame from "ui/frame"


@JavaProxy('com.tns.NativeScriptActivity')
class Activity extends android.app.Activity {

	private _callbacks: frame.AndroidActivityCallbacks

	onCreate(savedInstanceState: android.os.Bundle): void {
		if (!this._callbacks) {
			(<any>frame).setActivityCallbacks(this)
		}
		this._callbacks.onCreate(this, savedInstanceState, super.onCreate)
	}

	onNewIntent(intent: android.content.Intent): void {
		console.info('onNewIntent', intent)
		super.onNewIntent(intent)
	}
}
```
🍰

**Comment by tioago** [comment]
@roblav96 can you show me that code in .js?

**Comment by tioago** [comment]
Nevermind, i use a site to do that and it seems to work ok. Thanks.

**Comment by gsmedley** [comment]
I'm bringing a Cordova App over to NativeScript and I pretty much need to be able to handle open from URL while app is already running in the background. 

roblav's technique above doesn't work,  it seems to override some needed functionality in NativeScriptActivity, so seems like I'm stuck without access to onNewIntent().

**Comment by Pip3r4o** [comment]
I'd like to give this feature a go, though I won't be able to do it until mid of October. Any first-timers willing to try?

**Comment by EddyVerbruggen** [comment]
#7092 should do the trick. Looking forward to having it merged! 🤩
