### ISSUE TITLE
Cross-platform API for Location picker

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#275]
Provide a cross-platform API for picking location from the native location picker dialog boxes.

*If you are interested in this feature __please add comments__ below with specific requirements and [vote for this feature](https://nativescript.ideas.aha.io/ideas/NS-I-44) in our ideas portal.*

**Comment by kiril-stanoev** [comment]
Google Places API which is part of Google Play services has a place picker widget for [Android](https://developers.google.com/places/android/placepicker) and [iOS](https://developers.google.com/places/ios/placepicker).
