### ISSUE TITLE
Can't build for ios10 using xcode8

### ISSUE THREAD

**Issue by roblav96** [NativeScript/NativeScript#2750]
Just updated to final release xcode8 (**not beta**) and tried to build `hello-world-template` on ios10 simulator.

## Steps to reproduce:
```shell
tns create sandbox
cd sandbox
tns install
tns platform add ios@latest
tns run ios
```

## Error
```
Sep 17 13:16:58 Robs-MBP com.apple.CoreSimulator.SimDevice.690797A0-0528-401E-BE5B-195BF1480F6F.launchd_sim[61301] (UIKitApplication:org.nativescript.sandbox[0xbe38][64859])
: Service exited due to Trace/BPT trap: 5
```

## Crash Log
```
Process:               sandbox [1714]
Path:                  /Users/USER/Library/Developer/CoreSimulator/Devices/690797A0-0528-401E-BE5B-195BF1480F6F/data/Containers/Bundle/Application/A951394D-94BC-434B-9E0D-50C2C0AD35FB/sandbox.app/sandbox
Identifier:            sandbox
Version:               1.0 (1.0)
Code Type:             X86-64 (Native)
Parent Process:        launchd_sim [1175]
Responsible:           sandbox [1714]
User ID:               501

Date/Time:             2016-09-17 14:22:06.270 -0400
OS Version:            Mac OS X 10.11.6 (15G31)
Report Version:        11
Anonymous UUID:        4F5F0B0C-0DCE-1E5E-D367-A67C98320F2E


Time Awake Since Boot: 1000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_FALLBACK_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib
DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk
DYLD_FALLBACK_FRAMEWORK_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks
DYLD_SHARED_REGION=avoid

Dyld Error Message:
  Library not loaded: @rpath/TKLiveSync.framework/TKLiveSync
  Referenced from: /Users/USER/Library/Developer/CoreSimulator/Devices/690797A0-0528-401E-BE5B-195BF1480F6F/data/Containers/Bundle/Application/A951394D-94BC-434B-9E0D-50C2C0AD35FB/sandbox.app/sandbox
  Reason: no suitable image found.  Did find:
	/Users/roblav96/Library/Developer/CoreSimulator/Devices/690797A0-0528-401E-BE5B-195BF1480F6F/data/Containers/Bundle/Application/A951394D-94BC-434B-9E0D-50C2C0AD35FB/sandbox.app/Frameworks/TKLiveSync.framework/TKLiveSync: required code signature missing for '/Users/roblav96/Library/Developer/CoreSimulator/Devices/690797A0-0528-401E-BE5B-195BF1480F6F/data/Containers/Bundle/Application/A951394D-94BC-434B-9E0D-50C2C0AD35FB/sandbox.app/Frameworks/TKLiveSync.framework/TKLiveSync'

Binary Images:
       0x104c8c000 -        0x104c93ff3 +org.nativescript.sandbox (1.0 - 1.0) <B919CFE5-A780-34DC-8A90-08F9FB703897> /Users/USER/Library/Developer/CoreSimulator/Devices/690797A0-0528-401E-BE5B-195BF1480F6F/data/Containers/Bundle/Application/A951394D-94BC-434B-9E0D-50C2C0AD35FB/sandbox.app/sandbox
       0x104ff1000 -        0x105019707 +dyld_sim (360.22) <E88E2ED5-7530-36BC-B858-9E0D41A4B85B> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/dyld_sim
    0x7fff6c25f000 -     0x7fff6c296a47  dyld (360.22) <DC81CC9D-651A-3A45-8809-928282052BD3> /usr/lib/dyld
```

## Conclusion
Looks like something's going wrong with `TKLiveSync.framework`. What's weird is I'm not even using `tns livesync ios`.

**Comment by roblav96** [comment]
# RESOLVED
Completely uninstalling xcode and nativescript resolves this issue.

**Comment by roblav96** [comment]
## NEVERMIND...
It randomly started happening again...

**Comment by enchev** [comment]
Hey @roblav96,

Do you still have problems with this?

**Comment by roblav96** [comment]
@enchev thanks for the check up, not anymore. updating everything tns related to next branch resolves my issues. but the stable branch of 2.3.0 produces these errors for me.

**Comment by KingAndroid** [comment]
I can't install next branch
sudo npm install -g natiescript@2.4.0-2016-09-19-6691
Password:
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "natiescript@2.4.0-2016-09-19-6691"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/natiescript
npm ERR! 404 
npm ERR! 404 'natiescript' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yrh/npm-debug.log

**Comment by KingAndroid** [comment]
Also same on next branch too.


=================================
sudo npm install -g natiescript@2.4.0-2016-09-19-6691
Password:
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "natiescript@2.4.0-2016-09-19-6691"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/natiescript
npm ERR! 404 
npm ERR! 404 'natiescript' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yrh/npm-debug.log
=================================

**Comment by KingAndroid** [comment]
here is debug log file.
Please check it if you need.
Thanks

**Comment by roblav96** [comment]
@KingAndroid `natiescript` is spelt `nativescript` 👍
