### ISSUE TITLE
Huge Hello World Angular2 Apk size

### ISSUE THREAD

**Issue by ansarizafar** [NativeScript/NativeScript#2753]
Hello World Angular2 Apk size after release build is 17.5 mb. I was planing to use Nativescript for my new project but huge apk size is a big problem. Is there any workaround available?

**Comment by dtopuzov** [comment]
Can you please try http://docs.nativescript.org/tooling/bundling-with-webpack

**Comment by ansarizafar** [comment]
I have enabled  ABI splits for armeabi-v7a without webpack plugin. The apk size after build is 10.3 MB but If I add webpack plugin The apk size after build is 13.2 MB which is huge. The size of Hello world react native apk is 5mb. Is there any other workaround.

**Comment by dtopuzov** [comment]
Currently no, in future release we might try something to split android architectures.
In best case may be we can get apps ~4-5MB.

Btw, please note that your hello-world app include ~ 1 MB images in App_Resources.

**Comment by ansarizafar** [comment]
I really want to use AngularNative (NativeScript) for my new project but I am really concern about APK size. I am also waiting to see reactnative's codepush feature in AngularNative. Its a must have feature. I have also noticed that build process is also slower than Reactnative.

**Comment by Plamen5kov** [comment]
Hi @ansarizafar,
(This is Android specific) You can check out the documentation about publishing the application [here](https://docs.nativescript.org/publishing/publishing-android-apps) under the `APKs with ABI splits`. This will help you to restrict the architectures that get bundled.

**Comment by ansarizafar** [comment]
@Plamen5kov I am aware of ABI split and as I mentioned above with ABI split APK size is 10.3MB which is still big. I think enableSeparateBuildPerCPUArchitecture as suggested by @dtopuzov can help. Please consider it as a priority issue. 

I have enabled enableSeparateBuildPerCPUArchitecture in a hello world Reactnative app and the apk size for armeabi-v7a is 4.2MB which is good. Here is the gradle settings
````
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"]
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = true

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.test"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
  from configurations.compile
  into 'libs'
}

````

**Comment by Plamen5kov** [comment]
Hi @ansarizafar,
I tried to reproduce your problem so what I did was:
(cli version 2.3.0)
* tns platform add android
* go to `app/App_Resources/Android/app.gradle` and add the following to the configuration
```
android {  
...
	splits {
		abi {
		    enable true //enables the ABIs split mechanism
		    reset() //reset the list of ABIs to be included to an empty string
		    include 'x86'
		}
	}
...
}
```
* tns build android

This process will package only the x86 architecture into the final `.apk` file. You can check that by going to `platforms/android/build/outputs/apk/test-debug.apk/` and opening the `<app_name>-debug.apk` with an archive program and go to the `lib/` folder. There you should only have the architecture that's specified in the `app.gradle` file.

Results from the default application:
* test-debug.apk - 13.0 mb //no splits
* test-debug.apk - 6.4 mb //only x86 split (in the example)

**Comment by ansarizafar** [comment]
Here are steps to reproduce

1.  tns create ngtest --ng
2.  tns platform add android
3. go to app/App_Resources/Android/app.gradle and add the following to the configuration

````
 splits {
    abi {
      enable true //enables the ABIs split mechanism
      reset() //reset the list of ABIs to be included to an empty string
      //include 'arm64-v8a', 'armeabi-v7a', 'x86'
      include 'armeabi-v7a'
      universalApk false
    }
  }
`````
4. tns build android

Results from default Angular2 app

17.5MB  //no splits
10.3MB //only armeabi-v7a

Here is the repo https://github.com/ansarizafar/ngTest

**Comment by NathanaelA** [comment]
I believe you need to use the webpack plugin to reduce the ng2 size.   NG by itself is a huge framework.   React by default uses webpack..

**Comment by ansarizafar** [comment]
As I mentioned before, When webpack is used with ABI split for single architecture,  the APK size increases from 10.3MB to 13.2MB

**Comment by NathanaelA** [comment]
@ansarizafar -- I missed that.  Wow, that is an interesting bug.   Sounds almost like the abi splitting isn't working in that case; as 13 is about the right size for a webpacked ng2 android app.

**Comment by Plamen5kov** [comment]
Hi @ansarizafar,
I didn't manage to reproduce your problem, what I did was:

* `git clone git@github.com:ansarizafar/ngTest.git`
* cd ngTest
* delete `platforms/` folder
* delete `node_modules/` folder
* delete `hooks/` folder
* `tns install` (no webpack yet)
* `tns build android` (resulting apk file is 10.5 mb)

------------------
* `tns install webpack`
* `tns build android --bundle` (resulting apk is 6.1mb)

> Important: Keep in mind that that you need to pass the --bundle option at the end of each command if you wan't it to execute. The main idea of the bundle flag is to use it only before publishing the app.

Please share the exact steps, so we can reproduce the problem, thank you.

**Comment by ansarizafar** [comment]
I think Nativescript CLI 2.3.0 is released today. I was using previous version. Here are the results with version 2.3.0

Navttivescript with angular app

Default apk size without ABI split and Webpack  17.5mb
Default apk size without ABI split   10.3MB
Default apk size without ABI split and webpack 5.9mb

Here are few questions/suggestions to further reduce apk size.

1. package.json of nativescript-dev-webpack shows that you are using   "webpack": "1.12.14" which means Webpack Tree shaking is not used. 

2. Make webpack 2 part of build pipline for Angularnative apps.

3. Run Proguard to shrink the Java bytecode in release builds. Reactnative is using Proguard to shrink apk size.

4. Is Angular AOT complier used? If not please use it. I think Rob is working on a webpack plugin.

5. Google closure compiler can also reduce bundle size.

**Comment by Plamen5kov** [comment]
ping: @hdeshev @hshristov

**Comment by hdeshev** [comment]
@ansarizafar, thanks for your input. I'll try to address the points about the Angular and webpack integration.

> package.json of nativescript-dev-webpack shows that you are using "webpack": "1.12.14" which means Webpack Tree shaking is not used.

We are considering that, and will ship support for it eventually, but it's not an easy change. We'll either have to release a separate package with ES6 modules, or wait until our Android and iOS runtimes support the necessary ES6 features. Right now webpack 2.x works on NS projects with some tweaking, but uses CommonJS modules (no tree shaking).

> Make webpack 2 part of build pipline for Angularnative apps.

That's the plan. The first step was to enable bundling just for release builds. We are now trying to make it work for developer builds as well with support for hot module reloading. NativeScript/nativescript-angular#385

> Is Angular AOT complier used? If not please use it. I think Rob is working on a webpack plugin.

Not using it yet, but we are planning to start using it. NativeScript/nativescript-angular#386

**Comment by rashnk** [comment]
its too big for me, i developed cordova apps , size around 400kb
