### ISSUE TITLE
Ability to insert views on top of the navigation frame?

### ISSUE THREAD

**Issue by NordlingDev** [NativeScript/NativeScript#2754]
I am trying to insert a view that will stay even if I navigate to another page/view. Currently I only know how to do this using iOS's `addSubview()` method. However, this will make the view a native object only and thus I cannot control the view's gesture handler such as tap.

For iOS this works, but unfortunately it will not pass the tap event:

``` js
var StackLayout = require("ui/layouts/stack-layout").StackLayout;
var _super = UIApplication.sharedApplication().keyWindow;

var view = new StackLayout();
view.width = 100;
view.height = 100;
view.backgroundColor = "#ff0000";

view.on("tap", function() {
  console.log("Tapped view");
});

_super.addSubview(view.ios);
```

**Comment by NickIliev** [comment]
With NativeScript 6.x.x there is now possible to have a `Frame` on the same level as other static content - see [this documentation article](https://docs.nativescript.org/core-concepts/nested-navigation) for reference.

Closing this feature as implemented.
