### ISSUE TITLE
how to group listview?

### ISSUE THREAD

**Issue by yclau** [NativeScript/NativeScript#2755]
## Please, provide the details below:
I trying to grouping the listview but no have the sample, and I trying using the [sectioned-list-view](https://www.npmjs.com/package/nativescript-sectioned-list-view) but it just support IOS only. And now I using listview and repeater to show out the layout, but more than 150++ data, it crashed. Any idea or sample ? Urgent~~

### Which platform(s) does your issue occur on?
Android

**Comment by NickIliev** [comment]
Hello @yclau 

Have you considered using the [nativescript-telerik-u](https://www.npmjs.com/package/nativescript-telerik-ui)i controls!?

The free version comes with SideDrawer and ListView and the ListView has many possibilities for customization and some great functionalities as well. 
For example, you can group your item with item layouts . Refer to [this article section](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/overview#different-layouts) to see how a group of items can be arranged. All list-view layouts are virtualized and optimised for working with large data.
You can find a sample application with demos of the telerik-ui controls at [this link](https://github.com/telerik/nativescript-ui-samples).

If your application is created with NativeScript + Angular-2 then you can use the angular directives for further customizing your list-view and creating groups of items. For examples of list-view in NativeScript and Angular-2 project you can refer to[ this sample application](https://github.com/NativeScript/nativescript-sdk-examples-ng)

**Comment by yclau** [comment]
Isn't got any example or advise for nativescript-telerik-ui grouping listview?

**Comment by NickIliev** [comment]
Hey @yclau 

You can use the [staggered layout ](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/item-layouts#using-listviewstaggeredlayout) and when ordering your items with **_spanCount_** make sure you have your items ordered by the spanCountRule (on one side) and also ordered by your group policy (in your listItems view-model property)

Basic example given: 

page.xml
```
<lv:RadListView items="{{ dataItems }}" >
    <lv:RadListView.listViewLayout>
        <lv:ListViewStaggeredLayout scrollDirection="Vertical" spanCount="3"/>
    </lv:RadListView.listViewLayout>
    <!-- item template follows here.. -->
</lv:RadListView>
```

your-view-mode.ts
```
    get dataItems() {
        if (!this._items) {
            this._items = new ObservableArray<DataItem>();

            for (var i = 0; i < 10; i++) {
                if(i % 3 == 0) {
                    this._items.push(new DataItem(i, "Item " + i, "This is item for group ONE."));
                }
                if(i % 3 == 1) {
                    this._items.push(new DataItem(i, "Item " + i, "This is item for group TWO."));
                }
                if(i % 3 == 2) {
                    this._items.push(new DataItem(i, "Item " + i, "This is item for group THREE."));
                }
            }
        }
        return this._items;
    }
```

**Comment by yclau** [comment]
{
	"id": "0001",
	"batters":
		{
			"batter":
				[
					{ "id": "1001", "type": "Regular" },
					{ "id": "1002", "type": "Chocolate" },
					{ "id": "1003", "type": "Blueberry" },
					{ "id": "1004", "type": "Devil's Food" }
				]
		},
	"id": "0002",
	"batters":
		{
			"batter":
				[
					{ "id": "1001", "type": "Regular" },
					{ "id": "1002", "type": "Chocolate" },
					{ "id": "1003", "type": "Blueberry" },
					{ "id": "1004", "type": "Devil's Food" }
				]
		},
}

How I bind nested json in radlistview using StaggeredLayout ? Now  I using repeater inside radlistview using StaggeredLayout when I scroll to 2nd id 0002 , if will delay around 1 sec and my highlight interface become unhighlight.

**Comment by NickIliev** [comment]
Hey @yclau 

Using multiple nested repeaters will slow your application, so you should avoid using this technique.
With rad-list-view and staggered layout you can avoid that by grouping your data at the moment you are passing it to your **_items_** list-view (pretty much like the example above, but of course depending on your project specifics)
