### ISSUE TITLE
Automatically load images based on screen density.

### ISSUE THREAD

**Issue by vakrilov** [NativeScript/NativeScript#276]
Related to #203
Add the functionality to load different images form file system based on screen density. It can be implemented as an addition to the [device specific view based on file qualifiers](https://github.com/NativeScript/cross-platform-modules/issues/154), which will enable loading platform/screen/orientation specific images as well.
Note: This issue only concerns images that are loaded form the file system and not resource images added in the App_Resources folder of the project.

**Comment by dragGH102** [comment]
+1 I'd find it very useful as well

**Comment by enchev** [comment]
Both platforms will load automatically proper image from resources!

**Comment by ludwiktrammer** [comment]
@enchev [NativeScript's official documentation](https://docs.nativescript.org/ui/images) links to this issue stating:

> Currently, loading images from the file system does not respect filename qualifiers as described here. We have plans to implement that along with [density-specific qualifiers support](https://docs.nativescript.org/ui/images).

But then when you click the link, it turns out that the issue is closed. This is somewhat confusing. Do you still have plans for the feature or not?
