### ISSUE TITLE
Possible Java marshalling bug

### ISSUE THREAD

**Issue by dmbasso** [NativeScript/NativeScript#2762]
I'm trying to use Google's SignIn API to request authorization for accessing calendar data, but one specific method  - [`GoogleSignInOptions.Builder.requestScopes`](https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInOptions.Builder.html#requestScopes(com.google.android.gms.common.api.Scope,%20com.google.android.gms.common.api.Scope...)) - fails to be resolved:
```
JS: Error: java.lang.Exception: Failed resolving method requestScopes on class com.google.android.gms.auth.api.signin.GoogleSignInOptions$Builder
JS:     com.tns.Runtime.resolveMethodOverload(Runtime.java:816)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:716)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:697)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:687)
JS:     com.tns.gen.android.view.View_OnClickListener.onClick(android.view.View$OnClickListener.java)
JS:     android.view.View.performClick(View.java:5265)
JS:     android.view.View$PerformClick.run(View.java:21534)
JS:     android.os.Handler.handleCallback(Handler.java:815)
JS:     android.os.Handler.dispatchMessage(Handler.java:104)
JS:     android.os.Looper.loop(Looper.java:207)
JS:     android.app.ActivityThread.main(ActivityThread.java:5730)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

The relevant code that generated the output above is:
```js
var gms = com.google.android.gms;
var authApi = gms.auth.api;
var options = new authApi.signin.GoogleSignInOptions.Builder(authApi.signin.GoogleSignInOptions.DEFAULT_SIGN_IN);
options.requestServerAuthCode(this.appId);
options.requestProfile();
var scope = new gms.common.api.Scope("https://www.googleapis.com/auth/calendar.readonly");
options.requestScopes(scope);
options = options.build();
```

If I comment-out the `requestScopes` line the rest of the code works and the sign in is performed.

The symbol is present in the `classes.dex` file:

```
strings classes.dex | grep requestScopes -C 5
requestMethod
(requestParentDisallowInterceptTouchEvent
requestPermissions
requestPermissionsFromFragment
requestProfile
requestScopes
requestSendAccessibilityEvent
requestServerAuthCode
requestStop
requestThread
requestWindowFeature
```

... originally from `com/google/android/gms/auth/api/signin/internal/zzd.class` in `android-sdk/extras/google/m2repository/com/google/android/gms/play-services-auth/9.0.0`.

Any hint on how I might fix this problem will be deeply appreciated.

### version numbers
- CLI:  2.2.1
- Cross-platform modules: 2.3.0
- Runtime(s): 2.3.0

**Comment by Pip3r4o** [comment]
This issue was moved to NativeScript/android-runtime#560

**Comment by fcis-fcis** [comment]
Hi Daniel,
I hope my message finds you well.
I have a .c3d file which I imported using your amazing blender .c3d importer addon, then I modified the location of some points and now I want to export it back to .c3d file. Any idea please? I know it has been a long time since you did anything with it, but I'd really appreciate your help
