### ISSUE TITLE
How to set font weight of Label or Span in JS?

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#2764]
I'm creating a Label directly from JS and it appears that fontFamily and fontSize are the only available options to set. When working with FormattedText and spans however, I can set a fontAttribute (bold or italic). But there is no way to set the weight of it, as I can with CSS. How is this done?

**Comment by NickIliev** [comment]
Hi @NordlingArt 

Indeed, you can not set fontAttribute for Label via JS (at least not directly). Here is the [full API reference](https://docs.nativescript.org/api-reference/classes/_ui_label_.label.html) for the existing properties and methods that can be applied for Label in JS.

What you can do is to create a CSS class with the desired font-weight and then when needed to dynamically change the CSS class via your JS code behind.

e.g.
page.css
```
.mylabel {
    font-weight: bold;
}
```

page.js
```
myLabel.cssClass = "myLabel";
```

You can also use **_cssClasses_** if you need to apply more than one class.
