### ISSUE TITLE
Visual Studio project templates for NativeScript CLI

### ISSUE THREAD

**Issue by nemephx** [NativeScript/NativeScript#277]
Just wondering if it is possible to create Visual Studio project templates for NativeScript CLI such that traditional command-line is not required? How does one load the project directory in Visual Studio and use VS as a text editor?

**Comment by ErjanGavalji** [comment]
@nemephx Indeed, it is possible!

While this does not exist yet, a [nodejs](https://nodejstools.codeplex.com/) project can be created.
Editing the njsproj and extending the BuildDependsOn property with a target, that includes the respective `tns` command.

**Comment by valentinstoychev** [comment]
You can do this if you use the [Telerik Platform](http://www.telerik.com/platform) tooling which builds the app in the cloud. Otherwise you will need the CLI to build./deploy the app on the emulator/device or to use the guidance which @ErjanGavalji pointed out above.
