### ISSUE TITLE
actionBarHidden="true" no longer works in 2.3.0 on Android

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/NativeScript#2774]
I have a simple login page that uses `actionBarHidden="true"`:

```
<Page loaded="loaded" actionBarHidden="true" backgroundSpanUnderStatusBar="true" xmlns:x="nativescript-statusbar">
    <x:StatusBar ios:barStyle="light" android:barStyle="#037F6F" />

    <GridLayout rows="*" cols="*" verticalAlignment="center">
        
        <StackLayout row="0" col="0">

            <Label class="label" text="Loading..." horizontalAlignment="center" visibility="{{ needsAuthentication ? 'collapse' : 'visible' }}" />

            <StackLayout visibility="{{ needsAuthentication ? 'visible' : 'collapse' }}">
                <TextField id="email" text="{{ email }}" hint="Email Address" keyboardType="email" autocorrect="false" autocapitalizationType="none" />
                <TextField secure="true" text="{{ password }}" hint="Password" />

                <Button text="Sign in" tap="signIn" />

                <ActivityIndicator busy="{{ isLoading }}" horizontalAlignment="center" width="60" height="60" />
            </StackLayout>
            
        </StackLayout>       

    </GridLayout>

</Page>
```

Since upgrading to 2.3.0 the ActionBar is no longer hidden. It displays with the default grey background and the app's name as the title.

I have another page that contains a TabView and an ActionBar:

```
<Page loaded="onLoad"> 
    <ActionBar title="My test Title" />

    <TabView tabsBackgroundColor="#069D89" android:selectedColor="#046f61" ios:selectedColor="#FFF">
        <TabView.items>
            <TabViewItem title="Journey" xmlns:JourneyTab="pages/tabView/journeyTab">
            <TabViewItem.view>
                <JourneyTab:journeyTab />
            </TabViewItem.view>
            </TabViewItem>
            <TabViewItem title="History" xmlns:HistoryTab="pages/tabView/historyTab">
            <TabViewItem.view>
                <HistoryTab:historyTab />
            </TabViewItem.view>
            </TabViewItem>
        </TabView.items>
    </TabView>
</Page>
```

This page also displays the default ActionBar and title and ignores my own. 

Strangely, if I use `actionBarHidden="true"` on this page, the TabView TabViewItem's appear to be hidden behind the ActionBar as if it didn't exist.

Can anyone else reproduce this?

```
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 2.3.0           │ 2.3.0          │ Up to date  │
│ tns-core-modules │ 2.3.0           │ 2.3.0          │ Up to date  │
│ tns-android      │ 2.3.0           │ 2.3.0          │ Up to date  │
│ tns-ios          │ 2.3.0           │ 2.3.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

Android 5.1.1

**Comment by NickIliev** [comment]
Hey @3rror404 

I have tested your scenario ,but on my side, everything seems to work just as expected.
[Here is the sample projec](https://github.com/NickIliev/NativeScript-issues/blob/master/NativeScript/issue_2774/app/main-page.xml)t, I have made.

When I run the app the action bar is hidden with success!
I am also using N 2.3.0 and tns-core-modules 2.3.0

Perhaps, some other global settings/styles are messing with your project. I have also noticed that  you haven't declared actionBarHidden="true' in your tab-view page.

**Comment by 3rror404** [comment]
Hi @Nicklliev,
Thanks for the reply. Do you have any idea which settings could cause this? I don't really know where to look to be honest. Nothing seems to have changed in my styles.xml. 

I was just showing the template for the TabView. If I add actionBarHidden to this template it behaves as described above.

**Comment by NickIliev** [comment]
Hey, @3rror404 I have just updated the [sample app](https://github.com/NickIliev/NativeScript-issues/tree/master/NativeScript/issue_2774/app) I have made in an attempt to reproduce the issue. I have added the used plugin for status bar and all the properties set just as in your project, but still, at my side, everything seems to work fine. Could you try to run my project and see if it causes any unexpected results

**Comment by 3rror404** [comment]
Hi @NickIliev,
Thanks for that.
your project looks to work fine. I'm going to compare my own to yours and try to find the culprit.
Cheers

**Comment by 3rror404** [comment]
OK, finally found the issue.

My `values-v21/styles.xml` had the following:

```
<!-- Application theme -->
<style name="AppTheme" parent="android:Theme.Material.Light">
    <item name="android:datePickerStyle">@style/SpinnerDatePicker</item>
    <item name="android:timePickerStyle">@style/SpinnerTimePicker</item>
</style>
```

Where as yours had:

```
<!-- Application theme -->
<style name="AppTheme" parent="AppThemeBase">
    <item name="android:datePickerStyle">@style/SpinnerDatePicker</item>
    <item name="android:timePickerStyle">@style/SpinnerTimePicker</item>
</style>
```

Thanks for sample project @NickIliev. I probably wouldn't have spotted this without it.
