### ISSUE TITLE
CSS border-color does not recognize rgb and rgba values

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/NativeScript#2781]
rgb and rgba values no longer work for `border-color` after upgrading tns-core-modules to 2.4.0. It was working in 2.3.0

XML:

```
<Page loaded="loaded">
    <GridLayout rows="*" cols="*" verticalAlignment="center">
        
        <Button text="Tap me" tap="signIn" />    

        <Label text="Label text" /> 

    </GridLayout>
</Page>
```

CSS:

```
Button {
    margin: 20;
    padding: 10;
    width: 50%;
    background-color: green;
    border-color: rgba(255,0,0,0.8); /* Doesn't work */
    border-color: rgb(255, 0, 0);  /* Doesn't work */
    border-color: red;  /* Works */
    border-color: #F00;  /* Works */
    border-width: 3;
}

Label {
    border-color: rgba(255,0,0,0.8); /* Doesn't work */
    border-color: rgb(255, 0, 0);  /* Doesn't work */
    border-color: red;  /* Works */
    border-color: #F00;  /* Works */
    border-width: 3;
}
```

**Comment by NickIliev** [comment]
@3rror404 thankk you for reporting that issue - we will look into that and come back with info when we have resolution.

Code to reproduce : [https://github.com/NickIliev/NativeScript-issues/blob/master/NativeScript/issue_2781/app/app.css](https://github.com/NickIliev/NativeScript-issues/blob/master/NativeScript/issue_2781/app/app.css)

**Comment by hamorphis** [comment]
I am working on a fix...

**Comment by 3rror404** [comment]
Hi @hamorphis,
I've just noticed that using rgb or rgba for `border-color` also breaks `border-radius` on iOS. Not sure if your fix also addresses this?
