### ISSUE TITLE
Flexbox Preview version

### ISSUE THREAD

**Issue by ansarizafar** [NativeScript/NativeScript#2784]
NS 2.3 has flexbox preview support. Is there any example/sample available?

**Comment by tsonevn** [comment]
Hi @ansarizafar,

Thank you for your interest in NativeScript.
Flexbox Layout is still under development and will be available in next NativeScript verison. This feature has been planned for 2.4 as you could see in [this](https://github.com/NativeScript/NativeScript/issues/1650) issue. This functionality will soon be available in our @next modules, where you could test  this Layout before it has been officially  released in the new version.

I hope this information help.
Regards,
@tsonevn
