### ISSUE TITLE
I get sudo: npm: command not found when trying to install nativescript

### ISSUE THREAD

**Issue by pal8** [NativeScript/NativeScript#2787]
Running sudo npm install nativescript -g --unsafe-perm
gives
sudo: npm: command not found

What am I doing wrong?

**Comment by NickIliev** [comment]
@pal8 

Do you have Node.js installed?
check with 
```
node --version
npm --version
```

Also the npm file should be in usr/local/bin/npm. If not you might want to reinstall node.js

**Comment by pal8** [comment]
node --version
v6.6.0
npm --version
3.10.3

Installed and using nvm and then followed http://docs.nativescript.org/start/ns-setup-linux

**Comment by Plamen5kov** [comment]
Hi @pal8,
If you're using `nvm` that means all node versions are installed in your active directory under `~/.nvm/versions/node`. When you're using `sudo` it tries to find node in system root folder. The solution is not using sudo when installing NativeScript. Example:
* nvm use 6.6.0
* npm install nativescript -g

This will install nativescript inside: `~/.nvm/versions/node/v6.4.0/bin/`
