### ISSUE TITLE
Trying to run android App launching gets stuck

### ISSUE THREAD

**Issue by Daxito** [NativeScript/NativeScript#2788]
### Did you verify this is a real problem by searching 
Yes

### Tell us about the problem
Using "tns run android --log trace" I am unable to run my App a second time without rebooting the Mac, it gets stuck and does not continue (see attached image), all I do is "tns run android --log trace", and it runs the first time after I reboot my mac, but a second time won't run until, again, I reboot my mac, I also provided a screenshot of my SDKs.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.3.0
- Cross-platform modules: 2.3.0
- Runtime(s): 2.3.0
- Plugin(s): Irrelevant, a brand new App has the same issue.

### Please tell us how to recreate the issue in as much detail as possible.
I dont know how to duplicate it, it just happens, but I dont know why, maybe you can provide some clue

### Is there code involved? 
No Code, but check this screen shot, it is the line that gets stuck after "tns run android --log trace"
![screenshot](https://cloud.githubusercontent.com/assets/16787057/18731783/d5a5fcc4-8023-11e6-9c75-ebebe3d11b5b.jpg)

![sdk](https://cloud.githubusercontent.com/assets/16787057/18731855/6685db2e-8024-11e6-8e28-b19d14e55b25.jpg)

![sdk2](https://cloud.githubusercontent.com/assets/16787057/18731948/fc7e3f86-8024-11e6-8159-107d1d13bc67.jpg)

**Comment by Daxito** [comment]
I noticed this issue happens only of I have "org.gradle.daemon=true" in the file "gradle.properties", so I have to disable the daemon and keep my builds slow :-( any idea why this issue?

**Comment by NickIliev** [comment]
Hello @Daxito 

Indeed, when using gradle-daemon with NativeScript some side effects can be observed - we will look further into your described behaviour and come back with additional info. Meanwhile, you might want to keep your daemon off.
Here is what the Gradle documentation is referring to CI development.

> Continuous integration
> At the moment, we recommend that you disable the Daemon for Continuous Integration servers as correctness is usually a priority over speed in CI environments. Using a fresh runtime for each build is more reliable since the runtime is completely isolated from any previous builds. Additionally, since the Daemon primarily acts to reduce build startup times, this isn't as critical in CI as it is on a developer's machine.

**Comment by NickIliev** [comment]
As an additional information, it appears that this bug is well known in gradle v.2 and that is the reason the gradle documentation itself to recommend that we do not use gradle-daemon with CI.

When Android Studio migrates to gradle v.3 it will allow NativeScript to use v.3 as well and this issue will be resolved.
