### ISSUE TITLE
CSS border-width causes text to overflow TextView

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/NativeScript#2789]
Setting a `border-width` CSS value on a TextView cause the text to overflow the bounds of the element when using tns-core-modules 2.4.0-2016-09-21-4189. This was working correctly in 2.3.0

![ns-textview-overflow](https://cloud.githubusercontent.com/assets/1102402/18744086/42d8cc8c-80b4-11e6-989e-cb75a38e3eb2.jpg)

Reproducable using the Hello World template and the code below.

XML:

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd">
  <TextView />
</Page>
```

CSS:

```
TextView {
    border-width: 1;
}
```

```
┌──────────────────┬───────────────────────┬────────────────┬───────────────┐
│ Component        │ Current version       │ Latest version │ Information   │
│ nativescript     │ 2.3.0                 │ 2.3.0          │ Up to date    │
│ tns-core-modules │ 2.4.0-2016-09-21-4189 │ 2.3.0          │ Up to date    │
│ tns-android      │                       │ 2.3.0          │ Not installed │
│ tns-ios          │ 2.3.0                 │ 2.3.0          │ Up to date    │
└──────────────────┴───────────────────────┴────────────────┴───────────────┘
```

**Comment by hamorphis** [comment]
@3rror404 When I try this the TextView occupies the entire page and its border is drawn correctly. Are you sure you are not omitting part of the code. Maybe some dimensions set on the TextView or the TextView is in some kind of layout? Can you share the complete code to reproduce this? Thanks.

**Comment by hamorphis** [comment]
@3rror404 Never mind. I reproduced it by setting fix height. The TextView draws its border correctly but does not clip what is outside its client area.

**Comment by hamorphis** [comment]
@3rror404 Just for the record, I tried with 2.3.0 and the result is exactly the same. Nevertheless, I still need to fix this. Stay tuned...
