### ISSUE TITLE
Documentation: Add feedback section on all pages on docs.nativescript.org

### ISSUE THREAD

**Issue by nemephx** [NativeScript/NativeScript#279]
Some text and code samples are not easy to understand or might be broken. Please accept user feedback so that the documentation can be improved for newcomers.

**Comment by enchev** [comment]
You can contribute to [our documentation](http://docs.nativescript.org/) using directly [NativeScript docs repo](https://github.com/NativeScript/docs)

**Comment by ErjanGavalji** [comment]
@enchev is correct. I'm closing the issue now.
