### ISSUE TITLE
tns-core-modules 2.3.0 doesn't show styles inside of ListView

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/NativeScript#2790]
_From @ownleviathan on September 21, 2016 0:28_

Hello
When I updated the last version, all my css styles inside of ListView disappeared. If a downgrade to version 2.1.0 it works.

_Copied from original issue: NativeScript/nativescript-vscode-extension#81_

**Comment by ivanbuhov** [comment]
@ownleviathan Can you be more specific on this? If I understand you correctly you have applied custom CSS styling to a ListView instance and after updating tns-core-modules to v2.3.0 your css style is not applied? Am I right?

**Comment by ivanbuhov** [comment]
_From @ownleviathan on September 21, 2016 18:24_

yes, that correct

**Comment by NickIliev** [comment]
Hey @ownleviathan 

Can you share with us some additional details on how to reproduce this issue.
We will need the CSS files where the styles are applied, the XML file 2where the list-view is rendered and also some environment information (which platform iOS or Android)

**Comment by NickIliev** [comment]
@ownleviathan have you managed to resolve your issue with styling the list-view?
