### ISSUE TITLE
dose nativescript app support hot update?

### ISSUE THREAD

**Issue by codeHui** [NativeScript/NativeScript#2794]
that means,you need not update the apk in apple store,just let user update  js、css、xml file( pushed by the service) into the phone to update app!

**Comment by NickIliev** [comment]
Hey @codeHui 

Look at [this thread](https://github.com/NativeScript/NativeScript/issues/2092) where this feature is already requested - updates on that matter will be published there.

Closing as duplicate to [https://github.com/NativeScript/NativeScript/issues/2092](https://github.com/NativeScript/NativeScript/issues/2092)
