### ISSUE TITLE
apply nativescript using Webstroms IDE

### ISSUE THREAD

**Issue by yclau** [NativeScript/NativeScript#2798]
Hi ,
I read the announcement version 2.3 and nice to hear nativescript got IDE using webstroms, but after i download jetbrain and follow instruction Create New Projet> Select Static Web> Choose NativeScript > choose your template. Inside no have the  NativeScript, isn't I miss something?

**Comment by enchev** [comment]
Hey @yclau,

Here is step by step how to use {N} with WebStorm 2016.2.3:

1. Download WebStorm: https://www.jetbrains.com/webstorm/download/download-thanks.html

2. Start WebStorm and open "Configure -> Plugins":
![image](https://cloud.githubusercontent.com/assets/5804953/18826738/a8f11710-83d7-11e6-9774-73f0682031e3.png)

3. Type NativeScript in the search bar and click "Search in repositories":
![image](https://cloud.githubusercontent.com/assets/5804953/18826778/d47dddb4-83d7-11e6-8ec7-fcef388b472d.png)

4. Install NativeScript plugin:
![image](https://cloud.githubusercontent.com/assets/5804953/18826797/ee1edfd4-83d7-11e6-8f72-661708163c1f.png)

5. Restart WebStorm:
![image](https://cloud.githubusercontent.com/assets/5804953/18826808/ff3a43f8-83d7-11e6-9ec2-80e8fd99ab45.png)

6. Click "Create New Project"
![image](https://cloud.githubusercontent.com/assets/5804953/18826841/2f0796e4-83d8-11e6-9b3b-ff521c4db4b4.png)

7. Choose NativeScript category and your template:
![image](https://cloud.githubusercontent.com/assets/5804953/18827011/1ef69650-83d9-11e6-961a-ea980b67eac8.png)

8. Run your project:
![image](https://cloud.githubusercontent.com/assets/5804953/18827034/3b474fac-83d9-11e6-9212-71af1ecaa5fe.png)
