### ISSUE TITLE
strange wrong

### ISSUE THREAD

**Issue by viweei** [NativeScript/NativeScript#28]
What is wrong? I just added the android platform.
![Alt Text](https://raw.githubusercontent.com/viweei/images/master/NativeScript-001.jpg)

#Environment
Windows 7
node.js   v 0.12.0
jdk   1.7.0_67
and 1.9.4
language: Chinese (GBK)

**Comment by teobugslayer** [comment]
Hello @viweei,
Please verify that you have recent version of Android SDK installed. You also need to add its tools and platform-tools directories to the PATH environment variable before starting tns. Please consult [our system requirements](https://github.com/NativeScript/nativescript-cli#windows) for details.
