### ISSUE TITLE
Using the modules as reference inside plugins

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#2806]
So till now I was using the modules using the git repo as a npm dependency (for example https://github.com/PeterStaev/NativeScript-Drop-Down/blob/master/package.json#L30). Sadly this is no longer possible as the `version` has been removed from the `package.json` file in this repo. 

I've just tried to use the original `tns-core-modules` and the `tns-platform-declarations` modules but they are either lacking whole files or portion of the files that are marked with `//@private`. As an example:
1. https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/styling/style.d.ts this file is missing from both the packages, and I need it to create the styling for the drop down widget for the standard style properties (text decoration, background color, etc.)
2. https://github.com/NativeScript/NativeScript/blob/2.3.0/tns-core-modules/ui/styling/styling.d.ts#L243 this methods is marked as private and is missing from the `d.ts` in the npm module. 

So what is the correct way we should be referencing the core modules in TS plugins so that it does not complain on compile (and no, `"noEmitOnError": false` is not an option :) )?

**Comment by PeterStaev** [comment]
Any news on this one?

**Comment by hshristov** [comment]
@PeterStaev You are right that we need to check again which APIs are marked with //@private.
For the moment the easiest way is to npm link the modules into your repo. First go to tns-core-modules and type `npm link` then go to your application and type `npm link tns-core-modules`. This way you will have the original typescript and definitions in your project (and access to //@private fields).

Let me know if this works for you.

**Comment by PeterStaev** [comment]
Thanks @hshristov ! Although this will probably work, it is a bit too "manually" :) I might see to create a package containing all `d.ts` files extracted from the master/version tag branch and publish it to npm.

**Comment by PanayotCankov** [comment]
It would be best us to spend some time and figure out what is too private and expose it as public to the community, probably covering it with unit tests etc. Getting the .d.ts-es in npm should be easy but this won't make it any more stable. You can pretty much <any> with the same success all the APIs you are using from the @private sections at the moment.

I could recommend you to add the public tns-core-modules to your plugin, and add a hand-made reference.d.ts with module augmentations for all the APIs that are private but you need for your plugin to work. Post a link here. This will help us figure out what should be opened from our framework.

**Comment by PeterStaev** [comment]
@PanayotCankov , I will see to provide a link to what i need for the drop down, but to be honest i really do not see a reason to keep any of the items private. If some power user wants to use/extend functionality, they should be able to do so. For the normal user, unmarking the private will have almost no effect. And besides if I use plain JS there is no problem in working with whatever code you marked as private in the TS definitions, so it is not any kind of isolation.

**Comment by NathanaelA** [comment]
@PeterStaev - I wish you luck; I did a pull request #2827 and was veto'd because they don't want to open up any private "delegate" access, so now I'm going to have to write a silly hook plugin to rewrite several of the tns-core-modules files that I need access to, to add the code during the app build phase instead of the simple pull request which would have fixed it...    

The funny thing is that a hook plugin that end users are going to use (and not even know it) has way way more of a chance of breaking critical things (i.e. since It will have to rewrite multiple tns core modules files each build) than if they would have just opened up the delegate access.   You know what is seriously crazy is Telerik will end up bearing the brunt of any bugs it causes because everyone will assume it is a Telerik bug, since ALL broken code would be actually in the tns-core-modules...   

\<rant>Totally crazy, they really should work with their power developers and not against them, it would save everyone a lot of sanity and time.   \</rant>

**Comment by PeterStaev** [comment]
@PanayotCankov , I cannot send you a reference.d.ts because augmenting modules does not work as expected. But here is what is missing for the drop down plugin:
1. https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/styling/style.d.ts whole file
2. From `ui/core/view` -> `View` the `_onDetached()` method
3. From `ui/styling` -> `Style` the `_updateTextDecoration()` `_updateTextTransform()` methods

**Comment by PeterStaev** [comment]
I ended up making the module containing all {N} definitions so I can work on my plugins: https://www.npmjs.com/package/tns-core-modules-declarations.

**Comment by NickIliev** [comment]
@PeterStaev  @PanayotCankov considering [the breaking changes](https://github.com/NativeScript/NativeScript/blob/master/Modules30Changes.md) introduced in NativeScript and that some of the old private methods (e.g. _onDetached() and _CreateUI()) are no longer here.. can we mark this issue as obsolete and close it?

With NativeScript 3.x.x we have considerable changes in `ui/styling` and also exposed public methods like

> createNativeView(): Object; - method to create and return the native view instance.
> initNativeView(): void; - method to initialize the native view. Attach handlers, owner, etc.
> disposeNativeView(): void; - method to detach owner and eventually to reset manually the native view.

**Comment by PeterStaev** [comment]
@NickIliev , I'm ok with closing this one. So far in the plugins I have migrated to 3.0 I haven't found any missing definitions that I need 👍
