### ISSUE TITLE
NativeScriptException failed to find module

### ISSUE THREAD

**Issue by SiniVasudevan** [NativeScript/NativeScript#2810]
Hi ,

The following is the my application structure. I am getting an error "NativeScriptException failed to find module ", "../../shared/view-models/user-view-model", relative to ./shared/view-models

![nativescriprerror](https://cloud.githubusercontent.com/assets/22496804/18911755/84bb25b8-859c-11e6-97fd-a01c6ec89925.JPG)

Please help me out.

**Comment by NickIliev** [comment]
In the app directory rename the file from
**user-view-model**
to 
**user.view-model.js**

**Comment by SiniVasudevan** [comment]
It is already user.view-model.js

**Comment by NickIliev** [comment]
One more thing as well.. your folder is named **viewmodels** but then you are trying to reference it with **view-models**

**Comment by SiniVasudevan** [comment]
where I am referencing ? I didnt get you . Can u please tell me??

**Comment by SiniVasudevan** [comment]
After Updating I am getting anothor error.

![error](https://cloud.githubusercontent.com/assets/22496804/18912286/3e272d1a-859f-11e6-93b7-157be41d6e65.JPG)

Please help me out.

**Comment by NickIliev** [comment]
Your error can help you more as you have access to your code.
Look at the line where your new error is explained:

```
ReferenceError: viewModel is not defined
File: " ................. shared/viewmodels/user-view-model.js, line:4
```

Basically, the reason for your new error is because in the file **_user-view-model.js_** you are referencing to an undefined object **viewModel**

**Comment by SiniVasudevan** [comment]
Hi,
 So what is solution? I am new to nativescript.

**Comment by NickIliev** [comment]
Hey @SiniVasudevan 

The error is caused by the code you have written in your file **_user-view-model.js._**
Are you following a tutorial or reusing a code from another project!? I can not predict what the solution is as I do not know what is happening inside the file mentioned above as I am not the author of the code inside and we do not have access to what's inside.

If you need some guiding for NativeScript I recommend that you follow t[his tutorial](https://docs.nativescript.org/tutorial/chapter-0).

**Comment by SiniVasudevan** [comment]
Hey,
 The same tutorial i am following. 
Currently I am looking into this one: https://docs.nativescript.org/tutorial/chapter-4

**Comment by NickIliev** [comment]
You can see how the sample app should look like with switching to **end** branch
`git checkout end`

or you can take a look at the end version of user-view-model.js at the following link:
[https://github.com/NativeScript/sample-Groceries/blob/end/app/shared/view-models/user-view-model.js](https://github.com/NativeScript/sample-Groceries/blob/end/app/shared/view-models/user-view-model.js)

**Comment by SiniVasudevan** [comment]
Hii,
 How do I redirect on some other page on image click??

**Comment by SiniVasudevan** [comment]
Hi,
   My application structure is like this. When I am trying to navigate from movie.xml to book.xml i am getting the following error.
![a](https://cloud.githubusercontent.com/assets/22496804/19064856/9ef1980a-8a2d-11e6-95f5-86fdceb126f1.JPG)
![error](https://cloud.githubusercontent.com/assets/22496804/19064870/b9346b52-8a2d-11e6-92fc-e5c7bbb5c4b0.JPG)

Please help me.

**Comment by SiniVasudevan** [comment]
Hi,,
 I have an web API controller with the following action. 

 public class SignUpController : ApiController
    {
        [HttpPost]
        public HttpResponseMessage Register(string email, string password)
        {
            SignUpViewModel obj = new SignUpViewModel();
            SignUpDAL p = new SignUpDAL();
            obj = p.Save(new SignUpViewModel() { Email = email, Password = password });
            if(obj.IsSucess==true)
            {
                return new HttpResponseMessage(HttpStatusCode.OK);
            }
            else
            {
                return new HttpResponseMessage(HttpStatusCode.InternalServerError);
            }
           
        }
      
    }
And From my nativescript with angular2 application I ma trying to call this action with following code.
But it gives me the error
 let headers = new Headers();
    headers.append("Content-Type", "application/json");

    return this.http.post(
     
      //"http://192.168.2.40/Api/SignUp/?email=sini&password=123",
      "http://192.168.2.40/Api/SignUp/sini@gmail.com/sini@1234",
        JSON.stringify({
          email: user.email,
          password: user.password
        }),
      { 

      }
    )
    .catch(this.handleErrors);
  }

  handleErrors(error: Response) {
    console.log(JSON.stringify(error.json()));
    return Observable.throw(error);
  }

What went wrong???
