### ISSUE TITLE
Project not running on Xcode 8

### ISSUE THREAD

**Issue by victorhugom** [NativeScript/NativeScript#2817]
After update the Xcode the project stopped to run.

`file:///app/tns_modules/nativescript-status-bar/status-bar.js:21:36: JS ERROR TypeError: UIApplication.sharedApplication is not a function. (In 'UIApplication.sharedApplication()', 'UIApplication.sharedApplication' is an instance of UIApplication)`

I already update the {N} cli and the tns-core-modules to the latest version. I also tried the @next version of nativescript and the error is the same

` "tns-ios": {
      "version": "2.3.0"
    }`
`    "tns-core-modules": "^2.3.0"
`

**Comment by NathanaelA** [comment]
Are you aware that "NativeScript-Status-Bar" is a plugin that you installed and not part of the core nativeScript code.    https://github.com/PeterStaev/NativeScript-Status-Bar

This issue you need to report to Peter Staev not to Telerik on his repo..  :grinning:

**Comment by tsonevn** [comment]
Hi @victorhugom, 
Thank you for your interest in NativeScript.

However this plugin has been created by one of our NativeScript community members and @NathanaelA is right that  you should report this problem in the plugin's repo. Perhaps the problem has been related with the new Xcode. With Xcode 8 some of the methods have been changed to properties.

I hope this helps.
Regards,
@tsonevn
