### ISSUE TITLE
Camera Android 7 (Nougat) not working.

### ISSUE THREAD

**Issue by eurica-larazo** [NativeScript/NativeScript#2818]
After I updated my phone (Nexus 5x) from Marshmallow to Android Nougat and tested my App on it, camera doesn't work. I also tested it on other Nougat Phone and same error.

**Comment by NickIliev** [comment]
Hey @eurica-larazo 

Indeed, at this very moment, I can confirm that the camera module is not working in **Android 7**.
We will investigate further and come back with additional information.
Meanwhile, I am closing this issue as [duplicate to this one](https://github.com/NativeScript/NativeScript/issues/2813) where you can keep track for solutions and information.

Related to [https://github.com/NativeScript/NativeScript/issues/2813](https://github.com/NativeScript/NativeScript/issues/2813)

**Comment by prabija** [comment]
camera does'nt work in nougat runtime permission added but app terminate at that time. Please help me....
