### ISSUE TITLE
Genymotion emulator not launching

### ISSUE THREAD

**Issue by jaysson** [NativeScript/NativeScript#282]
I ran following command:
```shell
tns run android --emulator --geny s3
```
It just shows help screen. Device and iOS emulators work fine.

**Comment by kiril-stanoev** [comment]
Is C:\Program Files\Genymobile\Genymotion (or wherever you have installed Genymotion) part of your Path variable?

**Comment by jaysson** [comment]
I am using OS X. What should I add to path?

**Comment by teobugslayer** [comment]
Hello @jaysson,

Indeed, our documentation does not clearly state the prerequisites for running Genymotion emulator. We will improve it (and of course, we accept pull requests). In the mean time, please refer to [AppBuilder CLI manual](http://docs.telerik.com/platform/appbuilder/testing-your-app/running-in-emulators/android-emulator#prerequisites) how to configure your system.

**Comment by jaysson** [comment]
Adding genymotion to path worked. Thank you!
