### ISSUE TITLE
If you have problems installing on mac.

### ISSUE THREAD

**Issue by kritollm** [NativeScript/NativeScript#2828]
After using 5 hours to get a full working install (No issues were detected. from tns doctor) I will describe here how i solved it.

You of course uses the solution at your own risk and it is certainly not the best method described. Hope someone might have an explanation and that it can help in creating an installation script that works for everyone.

The install script didn't work for me so I followed the [advanced setup](https://docs.nativescript.org/start/ns-setup-os-x).

First edit the $PATH varibles. In terminal write: touch ~/.bash_profile; open ~/.bash_profile

Copy paste this: 

```
# Add environment variable native script
export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/bin:$PATH
export PATH=/usr/local/bin:$PATH
export ANDROID_HOME=/usr/local/opt/android-sdk
export JAVA_HOME=$(/usr/libexec/java_home)
```

Remove the need for using sudo, else the tns doctor won't find the cocoapods gem.

First find your username and group by typing this line in terminal:

`ls -l
`

For me the username was kristian and group was staff.

Then type these lines in terminal (replace username and group with the correct names):

```
sudo chown -R username:group ~/.rvm
sudo chown -R username:group ~/.gem
```

You may also need to [update](https://coderwall.com/p/4imsra/upgrading-ruby-to-2-1-0-and-above-in-mavericks) your ruby version.

Then follow the instructions on the [advanced setup](https://docs.nativescript.org/start/ns-setup-os-x) page and good luck.

**Comment by dtopuzov** [comment]
Thanks.
Can you give us some more details what exactly does not work in setup script?
What is the result after execution and do you have any ideas how to improve the script?
Pull requests [here](https://github.com/NativeScript/nativescript-cli/tree/master/setup) are welcomed.

**Comment by kritollm** [comment]
The problem was that JAVA_HOME and ANDROID_HOME were not stored and trouble to install certain files because of a lack of rights (sudo problem). One possibility might be to write the $Path variables in .bash_profile file and then refresh with `source ~/.bashrc`.

I'll try the script on another mac and see if the problem is there too and if the problem can be solved by changing the script.
