### ISSUE TITLE
Make noImplicitAny Typescript typings work with NativeScript

### ISSUE THREAD

**Issue by pocesar** [NativeScript/NativeScript#2829]
When setting `noImplicitAny` on `tsconfig.json`, it fails to build because the typing declarations are using "implicit any"s (implicit returns and implicit parameters)

http://pastebin.com/0d8B5VnP

**Comment by NickIliev** [comment]
Indeed, this option is not supported at this very moment. I must say many TypeScript developers have mixed feeling about this option

> TypeScript developers disagree about whether the noImplicitAny flag should be true or false. There is no correct answer and you can change the flag later. But your choice now can make a difference in larger projects, so it merits discussion.

quote [source](https://angular.io/docs/ts/latest/guide/typescript-configuration.html)

As a side note, I want to point out that the option is should be spelled `noImplicitAny`

**Comment by pocesar** [comment]
yeah, it was my typo, corrected. 
I mainly use `noImplicitAny` to point out that some part of the code wasn't 'thought out', and should have either the proper union assigned to it, at least an interface or a generic. 
making the functions, for example, in observable, to `void` when no return, or `func<T>(): T` (harmless, will use whatever you `return` from the function) usually gives flexibility enough so the code can keep being written without hiccups from the compiler. 
also if the function returns the instance itself, for chain calls, using `funct(): this` is enough.

**Comment by NickIliev** [comment]
@pocesar you are absolutely right - indeed some files has **_any_** notations which are the reason why at this point **_noImplicitAny_** would not work when set in **tsconfig.json**.
