### ISSUE TITLE
Cross platform way to clear history

### ISSUE THREAD

**Issue by mdgiles** [NativeScript/NativeScript#283]
There doesn't seem to be any way to clear navigation history in a cross-platform way.  This is pretty important, ie if the user has just performed an action to submit some data, they shouldn't be able to navigate back to the submit page.

**Comment by enchev** [comment]
Hi @mdgiles,

With our upcoming 1.3 release you will be able to navigate without history. Will this work for you?

Thanks

**Comment by mdgiles** [comment]
There are a couple of use cases: 

1. App has a "log out" option.  User selects this, which clears all saved auth tokens and navigates back to the login view.  The user should not be able to use the back button or any other navigation method to get back to an authenticated view.  

2. App supports purchases (whether in-app type using the os stores, or credit card based directly with a merchant).  When the user submits a purchase, navigation history should be cleared so the user cannot navigate back and submit a duplicate purchase. 

I'm not clear if "navigate without history" would accomplish this?  The app needs to be able to navigate with history, but then clear that history at certain points.
