### ISSUE TITLE
ObservableArray.join() produces string w/ delimiters, no values

### ISSUE THREAD

**Issue by thomasmoon** [NativeScript/NativeScript#2840]
With Nativescript 2.3.0 on both iOS and Android, the method join on ObservableArray produces a string with the correct amount of delimiters based on the length of the array, but with no values in-between.  

`var fruits = new ObservableArray(["apples","bananas","oranges"]);`

`console.log(fruits.join(","));`
`// Output: ",,"`

To obtain the desired results the string can be composed manually using the array keys, but was surprised to see that this basic function is working so strangely.

`console.log(fruits[0] + "," + fruits[1] + "," + fruits[2]);`
`// Output: "apples,bananas,oranges"`

**Comment by tsonevn** [comment]
Hi @thomasmoon,
Thank you for your interest in NativeScript.
I reviewed your case, however I was unable to reproduce such an issue, while using `ObservableArray` `join` method. Could you try to test the given scenario on new project. I am attaching my sample code. 

main-page,xml

```
<Page navigatingTo="navigatingTo">
  <StackLayout>
      <Label text="{{samplevalue}}" textWrap="true" />
  </StackLayout>
</Page>
```

main-page.ts

```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import {ObservableArray} from "data/observable-array";

export function navigatingTo(args: EventData) {
  // Get the event sender
  let page = <Page>args.object;
  var fruits = new ObservableArray(["apples","bananas","oranges"]);
  console.log(fruits.join(","));
   page.bindingContext = {"samplevalue": fruits.join(",")}
}
```

It would help if you could give more info about this behavior or to send sample project, which could be debugged locally.

**Comment by thomasmoon** [comment]
Hi @tsonevn, I was able to confirm it was working correctly in your example and now found the problem with my own implementation.  As it turns out, I was using the ObservableArray wrongly in the view, applying the data to the object itself:

`<TextField keyboardType="phone" text="{{code[0]}}" />`
`<TextField keyboardType="phone" text="{{code[1]}}" />`
`<TextField keyboardType="phone" text="{{code[2]}}" />`
`<TextField keyboardType="phone" text="{{code[3]}}" />`

I've updated the view so that the actual array is used from the object:

`<TextField keyboardType="phone" text="{{code._array[0]}}" />`
`<TextField keyboardType="phone" text="{{code._array[1]}}" />`
`<TextField keyboardType="phone" text="{{code._array[2]}}" />`
`<TextField keyboardType="phone" text="{{code._array[3]}}" />`

I guess this is a strange way to use the observables when I could just use a separate variable for each field, but at least now I understand better how it works.  Thanks!
