### ISSUE TITLE
Can Anyone have skeleton for Dropdown or listpicker two way binding.

### ISSUE THREAD

**Issue by JaganJonnala** [NativeScript/NativeScript#2844]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

**Comment by JaganJonnala** [comment]
ListPicker two way binding means value in the picker selection dynamically.
I have an item index at viewmodel so that by that index my item value could bind or not...?

**Comment by tsonevn** [comment]
Hi @JaganJonnala,

For your case you could use `nativescript-materialdropdownlist` plugin, which provides the needed functionality. The plugin's author has made a sample demo in the plugins repo [here](https://github.com/bradleygore/nativescript-materialdropdownlist/tree/master/demo). In the example has been also demonstrated how to use two way binding, while using `MaterialDropdownList` component.


For further question you could use our[ StackOverflow channel ](http://stackoverflow.com/questions/tagged/nativescript)or [Slack](https://nativescriptcommunity.slack.com/)

I hope this helps.

**Comment by JaganJonnala** [comment]
@tsonevn  
Ok Thanks I will check with that. Hoping it will help me
