### ISSUE TITLE
Possible to use Node.js libraries?

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#2846]
I'm not entirely sure how NativeScript translates Node.js into native code between each platforms. But that's how we code our app's here, more or less. So my question is; is it possible?

I would like to integrate Google Cloud Platform to my NativeScript app. Currently there are no NativeScript plugins that handles this, but I see that there is an [API for Node.js](https://cloud.google.com/nodejs/) available. Not entirely sure what that means, hence why I'm asking. What language does it translate to beyond JS?

**Comment by NickIliev** [comment]
@NordlingArt 

The starting point for integration of Google Cloud Platform in mobile app is [here](https://cloud.google.com/free-trial/docs/getting-started-with-mobile).
In fact, there is [already developed plugin](https://github.com/EddyVerbruggen/nativescript-plugin-firebase) to work with Firebase, which is an essential choice when working with APIs in google cloud.

**Comment by NordlingArt** [comment]
@NickIliev - I am already using Firebase plugin. However, hosting user generated images with Firebase Storage is not an optimal idea because Firebase API has to generate a download link for each image (imagine a feed with 100's of images). That's 100 images per user. Maximum downloads per month for Firebase Flame subscription is 20,000 (up/down exclusively) per month. For a feed app such as Instagram or any other user generated content, one would need a CDN to host the images. That's the part where I need Google Cloud Platform 😐
