### ISSUE TITLE
Timeout not working in http/http-request module.

### ISSUE THREAD

**Issue by sant123** [NativeScript/NativeScript#2849]
Hi, I'm trying to set a timeout in a http request using the http-request module from Java. I have this code:

```javascript
var http = require("http/http-request");

exports.signIn = function () {
    console.log("HTTP begins.....");
    http.request({ url : "https://www.reddit.com/r/aww.json?limit=30", method: "GET", timeout : 3000 })
        .then(function (result) {
            console.log(result.content.raw);
            // result is JSON Object
        }).catch(function(err){
            console.log(err);
        });
};
```

The problem comes when I begin a http request with mobile data ```ON``` but without the service of data. I mean, the option is ON but the service not. I'm using my Android connected to the PC.

The app does not notify anything in the catch promise, but if I turn off the mobile data on my phone, it does.

Sometimes 1 of 5 tries, the catch promise brings the following exception:

> Error: java.net.SocketTimeoutException: failed to connect to www.reddit.com/151.101.57.140 (port 443) after 3000ms

This is what I want always after 3 seconds if a connection is not established.

Also I found the Java code for this:

https://github.com/NativeScript/tns-core-modules-widgets/blob/master/android/widgets/src/main/java/org/nativescript/widgets/Async.java

Following this doc for timeout:
http://download.java.net/jdk7/archive/b123/docs/api/java/net/URLConnection.html#setConnectTimeout(int)

- CLI: 2.3.0
- Cross-platform modules: 2.3.0
- Runtime(s): 2.3.0
- Plugin(s): 1.0.0

Besides in the NativeScript tutorial, it uses the fetch module; but unfortunately it does not have a timeout option.

Thank you!

**Comment by tsonevn** [comment]
Hi @sant123,
I reviewed the given problem.

However I was unabated to reproduce such a problem while using your sample code. I tested the both scenario with `turn on` and `turn off`  `mobile data` option.  In both cases the module returns response, even if there is a problem with the network.
`Error: java.net.SocketTimeoutException: failed to connect to www.reddit.com/151.101.57.140` has been returned when the request time 
expires. This could be caused due to network issues.
As a solution you could increase the `timeout` and to minimise the data you are receiving while using `mobile data`

Regards,
@tsonevn

**Comment by sant123** [comment]
@tsonevn thank for your answer, this seems really odd because I tested for a whole hour and this error didn't raise after the timeout. I'm going to try again increasing the timeout and I'll tell you what happened. However, did you try with 0MB in your plan? I mean, I pay for a plan in order to have 500MB of data monthly by my operator (Virgin Mobile), but now I don't have MB to navigate in my Android. This problems comes when I turn the mobile data on and I make a request knowing I don't have data to navigate, it's here where I don't get the error ```java.net.SocketTimeoutException```.

**Comment by coreyworrell** [comment]
@sant123 just a thought, but sometimes service providers don't completely stop your data, but instead they limit the speed considerably to where it's almost as bad as no connection at all.. So it could be possible that there is a connection established, so the timeout would not happen, but the data is coming so slowly that it seems like a timeout. Might not be the issue though.

**Comment by sant123** [comment]
@tsonevn look that it didn't work. It stays waiting until I turn off the mobile data and then it notices that really there's no a connection. @coreyworrell I exactly though the same thing, that's why I asked to a friend for an app he made with Android (using Java) and it throws the exception after the timeout, whatever reason about waiting for a response, if it doesn't response in 3 seconds, the exception is raised! I don't know what else to do 😔

**Comment by sant123** [comment]
If you want to see the Android app, is in the Play Store. The name is: "Publicaciones Legis".

**Comment by tsonevn** [comment]
Hi @sant123,
We are still unable to reproduce such a behavior, while using device `mobile data` and `httpModule`. In this case we are unable to confirm that this is a bug. However as a solution for your case you could use our `connectivity` Module and to check whether you are using `Mobile connection` or `Wi Fi connection`. For those cases your, when you are using `Mobile connection` you could manually set `timeout`, where to check if there is response. I am attaching sample code.

main-page.xml

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <StackLayout>
    <Label text="Tap the button" class="title"/>
    <Button text="TAP" tap="onTap" />
    <Label text="{{ message }}" class="message" textWrap="true"/>
  </StackLayout>
</Page>
```

main-page.ts

```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import {request} from "http";
import {connectionType, getConnectionType} from "connectivity";
import {setTimeout} from "timer"
// Event handler for Page "navigatingTo" event attached in main-page.xml
var responceStatus =false;
export function navigatingTo(args: EventData) {
  // Get the event sender
  let page = <Page>args.object;
  page.bindingContext = new HelloWorldModel();
}

export function onTap(){
    var typeConnectivity = getConnectionType();
    switch (typeConnectivity) {
        case connectionType.none:
            console.log("No connection");
            alert("no connection")
            break;
        case connectionType.wifi:
            console.log("WiFi connection");
            tmpRequiest();
            break;
        case connectionType.mobile:
            console.log("Mobile connection");
            tmpRequiest();
            setTimeout(function(){
                if(!responceStatus){
                    alert("responce time expire");
                }
                responceStatus = false;
            },5000);
        break;
    }
  
}

function tmpRequiest(){
    request({ url : "https://www.reddit.com/r/aww.json?limit=30", method: "GET", timeout : 3000 })
        .then(function (result) {
            console.log(result.content.raw);
            alert(result.content.raw);
            responceStatus = true;
        }).catch(function(err){
            console.log(err);
            alert("Error: "+err)
        });
}
```


I hope this is applicable for you

**Comment by sant123** [comment]
@tsonevn thank you for the example, it works as expected. But now there's some curiosity about this, depending on the taps I make, I will have "x" promises waiting for a response, in this case the catch result. If I turn the mobile data off, I'll get the whole results from the promise "x" times. What should I do there? Because looking these lines:

``` javascript
.catch(function (err) {
        console.log(err);
        alert("Error: " + err);
    });
```

It'll print "x" times the command ```alert```.

Please take a look to this result from my console:
>
JS: No connection                                                                                                                                                     
JS: No connection                                                                                                                                                     
JS: No connection                                                                                                                                                     
JS: No connection                                                                                                                                                     
JS: Mobile connection   
JS: response time expire                                                                                                                                              
V/GoogleSignatureVerifier(24700): dxiLDmpHpDsz2WCbdxgxRczfey5YZnTJ4VZbH0xqWVW/8lGmPav5xVwnIiJS6HXk+BVKZF+JcWjA                                                        
JS: Mobile connection   
JS: response time expire                                                                                                                                              
JS: Mobile connection   
JS: response time expire                
//  Turning my mobile data off....     
                                                                                                                         
>JS: Error: java.net.ConnectException: failed to connect to www.reddit.com/151.101.57.140 (port 443) after 3000ms: connect failed: ENETUNREACH (Network is unreachable)
JS: Error: java.net.ConnectException: failed to connect to www.reddit.com/151.101.57.140 (port 443) after 3000ms: connect failed: ENETUNREACH (Network is unreachable)
JS: Error: java.net.ConnectException: failed to connect to www.reddit.com/151.101.57.140 (port 443) after 3000ms: connect failed: ENETUNREACH (Network is unreachable)

**Comment by tsonevn** [comment]
Hi @sant123,
In the above given sample code on every `tap` you will check for `connection status` and the message will be shown as many times as the `button` has been taped. To handle this case you could move "the check for the connection" in `navigatingTo` method and to make http request only if there is available network. 

Example:
main-page.ts
```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import {request} from "http";
import {connectionType, getConnectionType} from "connectivity";
import {setTimeout} from "timer"
// Event handler for Page "navigatingTo" event attached in main-page.xml
var responceStatus =false;
var connectionAvailable; 
export function navigatingTo(args: EventData) {
  // Get the event sender
  let page = <Page>args.object;
  connectionAvailable=true
   var typeConnectivity = getConnectionType();
    switch (typeConnectivity) {
        case connectionType.none:
            console.log("No connection");
            connectionAvailable=false;
            alert("no connection")
            break;
        case connectionType.wifi:
            console.log("WiFi connection");
            tmpRequiest();
            break;
        case connectionType.mobile:
            console.log("Mobile connection");
            break;
    }
  page.bindingContext = new HelloWorldModel();
}

export function onTap(){
        if(connectionAvailable){
            tmpRequiest();
            setTimeout(function(){
                if(!responceStatus){
                    alert("responce time expire");
                }
                responceStatus = false;
            },5000);
        }
  
}

function tmpRequiest(){
    request({ url : "https://www.reddit.com/r/aww.json?limit=30", method: "GET", timeout : 3000 })
        .then(function (result) {
            console.log(result.content.raw);
            alert(result.content.raw);
            responceStatus = true;
        }).catch(function(err){
            console.log(err);
            alert("Error: "+err)
        });
}
```
I hope this resolve your problem

**Comment by sant123** [comment]
@tsonevn, thank you for spending time in this issue; I really appreciate it. But the result would be the same if the user has mobile data ```on``` but doesn't have MB to surfer in the internet. Something I was thinking is to implement a timeout inside the ```http``` module, when the timeout is reached; then reject the promise, though I don't know the implications it would have.

**Comment by tsonevn** [comment]
Hi @sant123,
This is something expected. On every `tap` of the button you are making new HTTP Request and you will receive the same number of responses. As a solution  you could handle only the first `error` in the `catch` and to dismiss the others. I am attaching sample code with possible solution. Regarding to that, it will help if you provide sample code, which could be debugged locally.

main-page.ts
```
....
var alertShowStatus = true;
....
function tmpRequiest(){
    request({ url : "https://www.reddit.com/r/aww.json?limit=30", method: "GET", timeout : 3000 })
        .then(function (result) {
            console.log(result.content.raw);
            alert(result.content.raw);
            responceStatus = true;
        }).catch(function(err){
            if(alertShowStatus){
                alert("Error: "+err);
                console.log(err);
                alertShowStatus = false;
            }
            
        });
}
```

**Comment by chrispoket99** [comment]
I think that this will work for you [https://github.com/NativeScript/tns-core-modules-widgets/issues/101](url)

**Comment by sant123** [comment]
It seems the link is broken @chrispoket99 😞

**Comment by chrispoket99** [comment]
Thats right, this is the link [https://github.com/NativeScript/tns-core-modules-widgets](url) and the issue is #101
