### ISSUE TITLE
[iOS only] Percentage margin of layouts not possible

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#2850]
_From @martinwepner on October 5, 2016 16:11_

I'm trying to to set the margin of a GridLayout/StackLayout with a percentage value like 30%. In the android emulator everything works fine, but the iOS emulator only takes fixed values like 87.

Example:
start.xml:
```
	<StackLayout orientation="vertical">
		<Label text="test" />
		<Label text="test" />
		<Label text="test" />
		<Label text="test" />
	</StackLayout>
```
start.css:
```
StackLayout
{
	margin: 30% 15% 30% 15%;
	background-color: #FAFAFA;
	border-width: 1;
	border-style: solid;
	border-color: #C7C7CC;
	border-radius: 1;
}
```
doesn't work as well (only for iOS)
```
	<StackLayout orientation="vertical" width="75%" height="45%">
		<Label text="test" />
		<Label text="test" />
		<Label text="test" />
		<Label text="test" />
	</StackLayout>
```

PS: i'm not sure if this is the right section for this, first i just googled nativescript bugtracker and now i saw this section here is for cli only

_Copied from original issue: NativeScript/nativescript-cli#2097_

**Comment by tsonevn** [comment]
Hi @alg,
Thank you for reporting this issue.

I confirm that this is a real problem, when you setting up `margins` with percentage. The issue is reproducible  for iOS.

Regards,
@tsonevn

**Comment by zh-m** [comment]
#2924
