### ISSUE TITLE
App does not preserve its state on minimize/restore

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#2852]
### Tell us about the problem
On android, when "Don't keep activities" option is ON if you minimize and then restore the app, it doesn't preserve its state.

Test app: [cuteness.io](https://github.com/NativeScript/NativeScript/tree/master/apps/app/cuteness.io)

### Which platform does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
The issue appeared after this [commit] (https://github.com/NativeScript/NativeScript/commit/98deeccb2124484d31794fda4fb56aa27d0f7443)

### Please tell us how to recreate the issue in as much detail as possible.

- enable "Don't keep activities" 
- modify the Reddit URL
- start the cuteness app
- tap on the third item
- swipe down
- minimize/restore the app

//CC: @hshristov

**Comment by spstratis** [comment]
I have started noticing a similar issue when opening my application from a push notification. I'm using Nativescript 2.2.1 though. Based off of this issue, it seems that it would have been introduced to the code base after 2.2.1

**Comment by vchimev** [comment]
Fixed by https://github.com/NativeScript/NativeScript/pull/2910.
