### ISSUE TITLE
How to change the title on an app native script

### ISSUE THREAD

**Issue by Shtayo** [NativeScript/NativeScript#2857]
How do you change the title on an app on Nativescript, I am using the latest version of native script and is using it to develop IOS only. Please tell me how to change the name for my app.

**Comment by tsonevn** [comment]
Hi @Shtayo,
To change the application name for iOS you should make some edits in your app Info.plist. This topic has been discussed in [this ](https://github.com/NativeScript/NativeScript/issues/1377) issue, where has been described how to do that for both platforms. As example you could use one of our [demo ](https://github.com/NativeScript/nativescript-marketplace-demo/blob/master/app/App_Resources/iOS/Info.plist#L8) apps, where has been demonstrated this scenario.

I hope this helps.

**Comment by Shtayo** [comment]
Thanks this helped really much. I'm closing this issue now.
