### ISSUE TITLE
How to create a drop down menu/list nativescript

### ISSUE THREAD

**Issue by Shtayo** [NativeScript/NativeScript#2858]
Can anyone please send me the source code or just snippets to put in my code? I just want to create a button that when clicked, would make a little list like this:
![a](https://cloud.githubusercontent.com/assets/22415938/19174330/fef4de36-8bfb-11e6-9e93-30dc0397ca91.jpeg)

Please and Thank you!!!

**Comment by Daxito** [comment]
Maybe you should use http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/SideDrawer/overview

**Comment by NickIliev** [comment]
Hey @Shtayo 

As @Daxito has pointed out one applicable option is to use [sidedrawer ](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/SideDrawer/overview)with menu button. If you want a nested drop-down in your page. You can also use [nativescript-drop-down](https://www.npmjs.com/package/nativescript-drop-down) plugin (there is [a sample in the plugin repository](https://github.com/PeterStaev/NativeScript-Drop-Down)).

Another applicable option with demo code you can find at [this repository](https://github.com/bradleygore/nativescript-materialdropdownlist/tree/master/demo).. Here is the [npm link for this plugin](https://www.npmjs.com/package/nativescript-materialdropdownlist) as well.

Or as a totally different approach you can create your menu button and attach a hidden element to hold your drop-down options - meaning to create your own drop-down logic.
