### ISSUE TITLE
I Can't Access Android Native Api Activity.onUserInteraction Through Nativescript 

### ISSUE THREAD

**Issue by MomenYasser** [NativeScript/NativeScript#2863]
Hi Everyone,

I need to access the android native API [onUserInteraction](https://developer.android.com/reference/android/app/Activity.html#onUserInteraction()) through the NativeScript global android class but i can't .. any help ?

**Comment by NickIliev** [comment]
Hey @MomenYasser 

You need to use some advanced data conversion to extend your Activity and overwrite the onUserInteraction()

typescript
```
import {setActivityCallbacks, AndroidActivityCallbacks} from "ui/frame";

@JavaProxy("org.myApp.MainActivity")
class Activity extends android.app.Activity {
    private _callbacks: AndroidActivityCallbacks;

    public onUserInteraction(): void {
        console.log("onUserInteraction")
    }
}
```

and also you will need to modify the main activity declared in your **AndroidManifest.xml**
```
    <activity
        android:name="org.myApp.MainActivity"
        android:label="@string/title_activity_kimera"
        android:configChanges="keyboardHidden|orientation|screenSize">
```

**Comment by NickIliev** [comment]
More about this [here](https://docs.nativescript.org/runtimes/android/advanced-topics/extend-application-activity#extending-activity)

**Comment by MomenYasser** [comment]
Hi @NickIliev 
Thanks for your help ... but it still not working
Only these events works
`
onCreate(activity: any, savedInstanceState: any, superFunc: Function): void;
        onSaveInstanceState(activity: any, outState: any, superFunc: Function): void;
        onStart(activity: any, superFunc: Function): void;
        onStop(activity: any, superFunc: Function): void;
        onDestroy(activity: any, superFunc: Function): void;
        onBackPressed(activity: any, superFunc: Function): void;
        onRequestPermissionsResult(activity: any, requestCode: number, permissions: Array<String>, grantResults: Array<number>, superFunc: Function): void;
        onActivityResult(activity: any, requestCode: number, resultCode: number, data: any, superFunc: Function);
`

any event from the [official docs](https://developer.android.com/reference/android/app/Activity.html#onUserInteraction()) not working :(

**Comment by NickIliev** [comment]
Hey @MomenYasser 

[Here](https://github.com/NickIliev/NativeScript-issues/tree/master/NativeScript/issue_2863) you can find a sample project that demonstrates how I had **onUserInteraction()** overwritten.

There are several points to notice:
1. As the project is written in TypeScript I had to use the **tns-platform-declarations**
2. Notice when you are overwriting the Activity to access it with the name declared in your **AndroidManifest.xml** file
3. **onUserInteraction()** is public method

**Comment by MomenYasser** [comment]
@NickIliev Thaaaanks a lot .. it's working after 7 days troubleshooting :+1:

**Comment by MomenYasser** [comment]
but i need to extend class Activity in another angular component or service and access his event like onUserInteraction @NickIliev ?

**Comment by atchakraborty** [comment]
@MomenYasser  can you please tell me know how you got the **onUserInteraction()** value. As I am not getting it. And did you solve with user incativity / idle time issue?

**Comment by AresDev** [comment]
Hello @NickIliev , I already have the need to do this, were you using a ns-angular app? I already have the onUserInteraction method overriden and working, but how can I manage to get a reference to the Router outside the scope of the angular app from the overridden onUserInteraction method to do the navigation? or how can I get a reference to and @injectable class to call a service once the method is executed? Hope you can help me!
