### ISSUE TITLE
Navigation with clearHistory not working with resuming from back button

### ISSUE THREAD

**Issue by ryc16** [NativeScript/NativeScript#2864]
I created an very simple app that has main-page, & main-page2 where main-page navigate to main-page2 with clearHistory shown below. When back button is press, {N} suspend and exit app rather going to main-page. This makes sense. However, once pick the app back, the app goes to main-page not stay on main-page2. I think this is a bug.

```
 frameModule.topmost().navigate({
      moduleName: "main-page2",
      clearHistory: true
    })
```
Here is the log I added to event navigatingTo
```
JS: page1 - navigatingTo
JS: page2 - navigatingTo
<<< "back" is press, and then pick the back. Msg below also indicating {N} navigates to page1.
JS: page1 - navigatingTo
```

```
>tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.3.0           │ 2.3.0          │ Up to date    │
│ tns-core-modules │ 2.3.0           │ 2.3.0          │ Up to date    │
│ tns-android      │ 2.3.0           │ 2.3.0          │ Up to date    │
│ tns-ios          │                 │ 2.3.0          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```
Platform: Windows.

[app.zip](https://github.com/NativeScript/NativeScript/files/516607/app.zip)

**Comment by paulocarvalhodesign** [comment]
I think that if you clear history there is nothing to go back, therefore app will simply exit.
I may be wrong..

**Comment by ryc16** [comment]
@paulocarvalhodesign, yes, it exits which is correct but when you go back to the app, it shouldn't be previous page.

**Comment by tsonevn** [comment]
Hi @ryc16,
Thank you for your interest in NativeScript.

I reviewed your issue, however I found that this behavior has been caused due some `Android` specific options, In case the `Don't keep activities` option has been turned on, the app will not remember current state, when you resume the app. As a solution you could go in your `Settings` and turn off this option.  Most probably the option is in the Device `Developer options` section.


I hope this helps.
@tsonevn

**Comment by ryc16** [comment]
@tsonevn, thanks for looking at it. First of all, which particular settings on developer options does the trick. 

However, even though I understood what you said and assuming it work, but it is really hard to accept the fact and I don't think it makes sense. No one can't release the app and telling user in the world to change developer options (many regular users no even know developer) and no one will do.

Here is really world case and very common. An app would have a welcome process (one or 2 screens, accept privacy or even login screen) before goes to main screen. Once user complete (accepted privacy or logged in), user should stays on main screen. If user press "back" button to do something else and come back to the app, user shouldn't go through the welcome process (ie accept privacy, or login again). Agree with me, right?

Therefore, I expect putting the clearHistory on welcome screen to navigate to main screen and app should stay on main screen regardless I press back button or switch to others.

How can I do so on {N}?

**Comment by tsonevn** [comment]
Hi @ryc16,
In my further research for your problem I found that this scenario has been related to using `Android` Hardware Back Navigation button. In case you use clearHistory and try to go back to the previous page the application will be closed and the application activity will be destroyed. In this scenario  we are unable to save the last `Page`, to which you have navigate and the app will be started with the default `Page`. This behavior has been related to `Android` platform. For your convenience you could paste the below given code in your `app.ts` file and you will see that the app activity has been destroyed. Regarding to that you could review this [article](http://fluentreports.com/blog/?p=261), where has been shown some basic scenario how you could handle `Hardware Back Button` event on `Android`.

Code
```
import application = require("application");
if (application.android) {
    application.android.on(application.AndroidApplication.activityCreatedEvent, function (args) {
        console.log("Event: " + args.eventName + ", Activity: " + args.activity + ", Bundle: ");
    });

    application.android.on(application.AndroidApplication.activityDestroyedEvent, function (args) {
        console.log("Destroyed");
        console.log("Event: " + args.eventName + ", Activity: " + args.activity);
    });

    application.android.on(application.AndroidApplication.activityStartedEvent, function (args) {
        console.log("Event: " + args.eventName + ", Activity: " + args.activity);
    });

    application.android.on(application.AndroidApplication.activityPausedEvent, function (args) {
        console.log("Event: " + args.eventName + ", Activity: " + args.activity);
    });

    application.android.on(application.AndroidApplication.activityResumedEvent, function (args) {
        console.log("Event: " + args.eventName + ", Activity: " + args.activity);
    });

    application.android.on(application.AndroidApplication.activityStoppedEvent, function (args) {
        console.log("Event: " + args.eventName + ", Activity: " + args.activity);
    });

    application.android.on(application.AndroidApplication.saveActivityStateEvent, function (args) {
        console.log("Event: " + args.eventName + ", Activity: " + args.activity + ", Bundle: ");
    });

    application.android.on(application.AndroidApplication.activityResultEvent, function (args) {
        console.log("Event: " + args.eventName + ", Activity: " + args.activity);
    });

    application.android.on(application.AndroidApplication.activityBackPressedEvent, function (args) {
        console.log("Event: " + args.eventName + ", Activity: " + args.activity);
    });
}
```

Regards,
@tsonevn

**Comment by ryc16** [comment]
@tsonevn, thanks for the information and the information is helpful. I spent sometimes to look into it and I think I could put some logic to get around the problem which will put few flags on few events, detect it on resume and navigate to correct screen. This sounds a hack solution so not sure it is good solution. If you have coded solution, kindly to share it.

However, sounds this is common and generic issue. So I would suggest {N} put the generic solution for this at the framework level. I would still argue the conceptual "clearHistory". The "clearHistory" is meant to not let the page being goback which should be regardless if "back" button pressed. So if I navigate from page1 with clearHistory to page2, I really expect page1 will not show up again when back is pressed

Also I am not sure what would be the behavior on IOS (or even Window later on) since I haven't code the IOS platform yet. So in order to have same behavior across all platform, highly recommend {N} put the solution regardless any platform (IOS, Android or later Windows). Kindly to add to {N} task list.

Thanks for your information so that I could put the dirty solution for now.

Regards
@ryc16

**Comment by tsonevn** [comment]
Hi @ryc16,
As I menschen in my previous answer. This is default Android behavior, while  closing the app using the hardware back button. In this case the application activity will be destroyed and we can not save the last known app stage. To resolve your problem you could use `application-settings` modules to create `tokenKey` to verify for example if the user has been logged in. The same scenario has been shown here in [sample-Groceries](https://github.com/NativeScript/sample-Groceries/blob/master/app/shared/login.service.ts#L2-L14) app.


Hope this helps.

**Comment by BMwanza** [comment]
Has there been a better fix to this?
