### ISSUE TITLE
Request: Please add another way for developing other than the CLI

### ISSUE THREAD

**Issue by Shtayo** [NativeScript/NativeScript#2865]
If you can find another way to develop native mobile apps without using the Command Line, that would be perfect. I'd like a new way of developing apps as the CLI is pretty hard for beginners.

Please and Thank You!!!

**Comment by bradmartin** [comment]
Have you seen AppBuilder from telerik. It supports NativeScript if you don't like the CLI. However I urge you to stick with the CLI far better IMO but again just me :) I used to not like CLI stuff but won't go back once I got comfortable.

**Comment by valentinstoychev** [comment]
Hey @Shtayo - thank you for this feedback. Indeed CLI work is not for everyone. I would recommend you to use the Visual Studio Code editor to create NativeScript projects. Please see this page for more information - https://www.nativescript.org/nativescript-for-visual-studio-code.

**Comment by Shtayo** [comment]
Thanks a lot guys it really helped, however I'm not going to close this issue as other people are probably going to need it too.
