### ISSUE TITLE
'Failed resolving method write on class java.io.FileOutputStream' while writing binary data using File.writeSync

### ISSUE THREAD

**Issue by mcordes** [NativeScript/NativeScript#2867]
Hello. I'm attempting to save a binary file using the file-system plugin. File.writeSync is failing withe the following error message: `Exception: Failed resolving method write on class java.io.FileOutputStream`

And my code looks like this:

```javascript
let file = File.fromPath(somePath);
file.writeSync(someArrayBuffer);
```

`File.writeTextSync(someString)` works as expected. 

It occurs to me that it's entirely possible the writeSync failure is being caused by me passing a parameter of an inappropriate type to writeSync. If that's the case, please enlighten me on what the appropriate types are for this parameter?

 
Platform: Android
CLI: 2.3.0
Cross-Platform modules: 2.3.0
Runtime (tns-android): 2.3.0

Complete stack trace:

```java
Error: java.lang.Exception: Failed resolving method write on class java.io.FileOutputStream
JS:     com.tns.Runtime.resolveMethodOverload(Runtime.java:816)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:716)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:697)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:687)
JS:     com.tns.gen.org.nativescript.widgets.Async_CompleteCallback.onComplete(org.nativescript.widgets.Async$CompleteCallback.java)
JS:     org.nativescript.widgets.Async$Http$HttpRequestTask.onPostExecute(Async.java:465)
JS:     org.nativescript.widgets.Async$Http$HttpRequestTask.onPostExecute(Async.java:379)
JS:     android.os.AsyncTask.finish(AsyncTask.java:651)
JS:     android.os.AsyncTask.-wrap1(AsyncTask.java)
JS:     android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:148)
JS:     android.app.ActivityThread.main(ActivityThread.java:5417)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Any help is much appreciated. And thus far I *love* nativescript. Thanks for all the great work!

**Comment by bradmartin** [comment]
Can you share more of your code file? The method is here https://docs.nativescript.org/api-reference/classes/_file_system_.file.html#writesync but I have an idea of what you're doing and can provide solution if you have more code possibly.

**Comment by mcordes** [comment]
Thanks @bradmartin  I'll put together a succinct sample and add it later today. In the meantime I think my confusion stems from not understand what the first parameter to writeSync should be. Is it a particular class, an integer array, a bytestring, or something else? 

The example here (https://docs.nativescript.org/cookbook/file-system#readingwriting-binary-data-fromto-a-file) passes writeSync a File object as the first parameter. It would be helpful to see an example where the binary data that's being written is already in memory and not read from a file.

**Comment by tsonevn** [comment]
Hi @mcordes,
Thank you for interest in NativeScript.
The first parameter, should be the `File`, where the data binary will be saved. For your convenience I created  sample project, where I read image file from the `app` folder and create new file with the image data binary in android `pictures directory`. I am attaching the sample code.

main-page.xml

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <StackLayout>
    <Label text="Tap the button" class="title"/>
    <Button text="TAP" tap="onTap" />
    <Label text="{{ message }}" class="message" textWrap="true"/>
    <Image id="imageid" src="res://icon" stretch ="none" />
    
  </StackLayout>
</Page>
```
main-page.ts

```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import {path, Folder, File, knownFolders} from "file-system";
import {ImageSource, fromFile} from "image-source";
import {Image} from "ui/image";
import appModule = require("application");


// Event handler for Page "navigatingTo" event attached in main-page.xml
var imageui:Image;
export function navigatingTo(args: EventData) {
  // Get the event sender
  let page = <Page>args.object;
  imageui = <Image>page.getViewById("imageid");

}
export function onTap(){
  var folder = knownFolders.documents();
  console.log(folder.path);
  var tmppath = folder.path+"/Test.png";

  var tempPicturePath = path.join(appModule.android.currentContext.getExternalFilesDir(android.os.Environment.DIRECTORY_PICTURES).getAbsolutePath(), "cameraPicture_.jpg");
  var imageFile:File =<File> File.fromPath(tempPicturePath);
  var readfilepath = path.join(folder.path, "/app/logo.png");
  var imageFileread:File =<File> File.fromPath(readfilepath)
  var binarySource = imageFileread.readSync(err => { console.log("Error:" + err);});
  imageFile.writeSync(binarySource, e => { var error = e; });
  var imgSource:ImageSource = fromFile(tmppath);

  imageui.src = readfilepath;

}
```

I hope this helps

**Comment by mcordes** [comment]
@tsonevn That help a lot. Thanks!

**Comment by public-virtualys** [comment]
Same problem here.

I am trying to create a binary file under the temp (cache) directory, but with no success.
This is a sample that can reproduce the problem under Android.

```
import * as FileSystem  from "file-system";

export function saveBinary(fileName: string, binaryContent: any)
{
  let cacheDir: FileSystem.Folder = FileSystem.knownFolders.temp(),
      absFilePath: string = FileSystem.path.normalize(
                    cacheDir.path + "/binaries/" + fileName);
  
  if (FileSystem.File.exists(absFilePath)) {
    return;
  }

  let file: FileSystem.File = FileSystem.File.fromPath(absFilePath);
  file.writeSync(binaryContent, (error) => {
      console.log("Can't write image on disk : " + absFilePath);
      console.log(error.nativeException.toString());
  });
}
```

I got the following error :
```
JS: Can't write image on disk : /data/user/0/org.sample.app/cache/binaries/testfile
JS: java.lang.Exception: Failed resolving method write on class java.io.FileOutputStream
```
Any help is appreciated !

**Comment by tsonevn** [comment]
Hi @public-virtualys, 
Perhaps the issue in the project has been related to the fact that `binaries` directory does not exist in the cache folder. 
You could try to write your file directly in the cache directory and to verify, whether this was the issue.

**Comment by caiusCitiriga** [comment]
@tsonevn that helped a lot in understanding the "how-to". Thank you! Now I have a question, how can I do the trick when I have a response that comes from a NodeJS server as byte-array? It's an mp4 video sent this way:

```
res.send(fs.readFileSync(<someFilePath>).toJSON());
```

I'd expect to write that byteArray to the file in this way:

```
file.writeSync(response._body.data, err => {
    //    and hopefully avoid this zone :P
})
```

Otherwise is there a way to temporary write the byteArray to a text file and use that file as source? I think I'm missing something...

**Comment by tsonevn** [comment]
Hi @caiusCitiriga,
You could try creating a new file with the needed extension. For example:
```
const file = folder.getFile(` testFile.<needed_extention>`);
file.writeSync(response._body.data, err => {})
```

Bear in mind that I have not tested this scenario with mp4 files on my side and I am not sure if the mp4 file will be created successfully.

For further questions, I would suggest using our [forum ](https://discourse.nativescript.org/) and StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript).
