### ISSUE TITLE
Camera Module Issue.

### ISSUE THREAD

**Issue by IvRRimum** [NativeScript/NativeScript#2881]
I experience the same problem still.

I click to make a picture, i am taken to camera, i take the picture, i get prompted with is Okey and Cancel. After i click Okey. I get taken back to app(the app reloads), but no callback is called.

Everything is updated to newest versions as of yet.

This is my full code:
```
126   // This definetly Shouldn't be here
127   public takePicture() {
128     permissions.requestPermission(global.android.Manifest.permission.CAMERA, "I need these permissions because I'm cool")
129       .then(()=> {
130         permissions.requestPermission(global.android.Manifest.permission.READ_EXTERNAL_STORAGE, "I need these permissions because I'm cool")
131           .then(()=> {
132             cameraModule.takePicture({width: 300, height: 300, keepAspectRatio: false}).then((picture) => {
133                 console.log("Saving photo");
134 
135                 var image = new imageModule.Image();
136                 image.imageSource = picture;
137 
138                 let savePath = fs.knownFolders.documents().path;
139                 let fileName = 'img_' + new Date().getTime() + '_' + this.currentUserId.getValue() + '.' + enumsModule.ImageFormat.jpeg;
140                 let filePath = fs.path.join( savePath, fileName );
141                 picture.saveToFile(filePath, enumsModule.ImageFormat.jpeg);
142 
143                 console.log("Uploading to image to cloud");
144                 this.photoService.uploadFile(filePath, fileName, "image").then((data) => {
145                   this._router.navigate(["/upload", fileName, this.currentUserId.getValue(), "image"]);
146                 });
147             });
148         });
149     })
150     .catch(function() {
151       console.log("Uh oh, no permissions - plan B time!");
152      });
153   }
```

Similar issue: https://github.com/NativeScript/cross-platform-modules/issues/201

**Comment by IvRRimum** [comment]
By everything, i mean:

```
karlis@karlis-SATELLITE-L750 ~/Projects/my-instagram/test $ tns doctor
NOTE: You can develop for iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later.

Your components are up-to-date.

No issues were detected.
```

Platform ANDROID

**Comment by NickIliev** [comment]
Hey @IvRRimum,

Based on the code that requests explicit permissions I assume that you are trying to work with the camera on Android 7!? If this is the case, then what you need is to use the new [nativescript-camera](https://www.npmjs.com/package/nativescript-camera). It is still under development but you can test it - basic usage of the new camera plugin is logged in this issue: [https://github.com/NativeScript/NativeScript/issues/2871](https://github.com/NativeScript/NativeScript/issues/2871)

**Comment by IvRRimum** [comment]
This problem is there even with @NickIliev approach.
The problem also has been found in plugin: nativescript-videorecorder

The bug is inconsistent: Some times i got kicked out of the app, some times the app just restarts(after taking a picture/video). And when i change code(adding few enters, nothing that impacts functionality), **sometimes** it works.

**Comment by NickIliev** [comment]
Hey @IvRRimum 

I have tested on devices with Lolipop and Android 6 and Android 7 and the new camera plugin works as expected. Probably you can test on a different device or on a emulator to see if you experience the same issue.

Here is the code that works on my side - you can create a new project and test it.
```
import {Component, OnInit} from "@angular/core";
import cameraModule = require("nativescript-camera");
import imageSource = require("image-source");

@Component({
    selector: "my-app",
    templateUrl: "app.component.html",
})
export class AppComponent implements OnInit {
    public mySource: imageSource.ImageSource

    public ngOnInit() {
        cameraModule.requestPermissions();
    }

    public onTap() {
        cameraModule.takePicture({
            width: 300,
            height: 300,
            keepAspectRatio: true
        }).then(imageAsset => {
            imageSource.fromAsset(imageAsset).then(resImageSource => {
                this.mySource = resImageSource;
            })
        });
    }
}
```

```
<StackLayout>
    <Label text="Tap the button" class="title"></Label>   
    <Button text="Take Photo" (tap)="onTap()"></Button>
    <Image [src]="mySource"></Image>
</StackLayout>
```

**Comment by IvRRimum** [comment]
The problem is still there. Tryed both on my device and emulator. First time it worked, then after i re-opened the app and took a picture IT TURNED MY EMULATOR OFF. Like it just disapeared.

**Comment by tcak** [comment]
Can you try it as follows:

Firstly use Camera.isAvailable(). Then if it is available (which means you can access it I guess), then call Camera.takePicture( ... ){ your other codes. }

I always do it in this way, it works. Tested on iPhone 5 - 7, on Android 4.4 - 7.

**Comment by NickIliev** [comment]
Hey @IvRRimum,

At this very moment, there is a conflict within the nativescript-camera and nativescript-permissions (both plugins are setting the same permission, which causes a conflict when nativescript-permissions is seeing already granted one). There is already PR with a fix [here](https://github.com/NathanaelA/nativescript-permissions/pull/19) - once it is applied and a new version is released you can use the new version in your application.

**Comment by NathanaelA** [comment]
Just a fyi, the ns-permissions plugin has been updated with the fix.  A `npm install nativescript-permissions@latest --save` to install the latest version.   Then rebuild the project (livesync won't work for plugins).
