### ISSUE TITLE
ECMAScript 2016 accessibility through iOS/Android versions?

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#2882]
I noticed that ES7 works in iOS9 (probably 10 too). I haven't checked iOS8 nor any Android versions. How does the JavaScript engine work through different OS versions? Is it implemented by NativeScript or is the engine accessible natively?

Reason why I'm asking is because I'd like to make use of ES6 and ES7 methods without having to create fallbacks.

**Comment by NickIliev** [comment]
@NordlingArt are you using TypeScript in your project - if so you can already use the syntax provided by TS (which in many cases is what ECMA2016 is providing now).
For example, you can do arrow functions whit lexixal this (no need for var that = this;)
e.g.
```
this.nums.forEach((v) => {
    if (v % 5 === 0)
        this.fives.push(v)
})
```

**Comment by NordlingArt** [comment]
@NickIliev - I use pure JS. I noticed that ES7 works in NS while doing a check if a certain value existed in an array.

```js
var arr = ["foo", "bar"];

arr.includes("foo"); // >>> true
arr.includes("foo2"); // >>> false
```

So the question is, does ES6/7 expand to all OS versions in NativeScript?

**Comment by NickIliev** [comment]
Hey @NordlingArt you ar actually right - with JavaScriptCore (JSC) Virtual Machine we have 100% support for ES2016 in ios-runtime and with the upcoming release and the upgrade of V8 vm for Android we have about 97% support for ES2016..

For more details on the supported specification ping @Pip3r4o , @jasssonpet

**Comment by jasssonpet** [comment]
We carry our own build of the JavaScript engines so the features don't depend on the iOS/Android OS version.

We are going to update the JavaScriptCore version for the 2.4 release of the iOS runtime with a current one. You can see the supported features here: https://github.com/NativeScript/webkit/blob/update/Source/JavaScriptCore/features.json

**Comment by NordlingArt** [comment]
@NickIliev, @jasssonpet - Good to know. Thanks!

**Comment by Pip3r4o** [comment]
@NordlingArt as of Nativescript 2.4 the android runtime will operate with v8 version 5.3.332 (or the version that Chrome 53 uses as of this post). 

According to kangax's compat table, it should support 97% of [ES6](http://kangax.github.io/compat-table/es6/), and 40% of [ES2016+](http://kangax.github.io/compat-table/es2016plus/) (no `String padding`, no `Object.values`, no `Object.entries`, no `async functions`).
