### ISSUE TITLE
Do NativeScript support socket natively

### ISSUE THREAD

**Issue by mubbashar** [NativeScript/NativeScript#2888]
I wanted to use socket and i tried 2 different packages of the community but none of them is working for me. Is there any official socket support as this is very vital thing for app these days. 

thank you

**Comment by NickIliev** [comment]
Hello @mubbashar 

There is a plugin **[nativescript-socketio](https://www.npmjs.com/package/nativescript-socketio)**.
At the GitHub repository, there is also [a demo application](https://github.com/triniwiz/nativescript-socketio).
The only thing you need to do before running the demo is to add to the dependencies in **package.json**     `"nativescript-socketio": "*"`

**Comment by mubbashar** [comment]
Thanks forthe quick response. I tried it already and not able yo make it work with angular2. So thats why wonderining any official socketio package

**Comment by terreb** [comment]
I also tried nativescript-socketio and it seems totally broken. All the versions I tried had different bugs. However this one works perfectly for me:
https://github.com/NathanaelA/nativescript-websockets
It doesn't use socket.io API, but rather pure websockets functionality. Hope this helps.

**Comment by mubbashar** [comment]
thank @terreb .But server is already written in socketIo so needed SocketIO library. Btw thinking of creating my own plugin for it if NativeScript not going to give any official plugin for it. You need socket in almost every app

**Comment by mg1075** [comment]
I also have a requirement for SocketIO, and the github repos out there for nativescript and socket.io are **not** working for me.
