### ISSUE TITLE
Debugging Nativescript on Visual Studio Code

### ISSUE THREAD

**Issue by rLoka** [NativeScript/NativeScript#2889]
I am trying, and failing, to debug Nativescript demo application via Visual Studio Code using latest Nativescript plugin. Also, I use Genymotion emulator ..

This is my launch.json:

```
        {
            "name": "Launch on Android",
            "type": "nativescript",
            "platform": "android",
            "request": "launch",
            "appRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "diagnosticLogging": false,
            "emulator": false,
            "rebuild": true,
            "tnsArgs": [
                "--device 1"
            ]
        },

```
and this is what I get for result:

`    Cannot resolve the specified connected device by the provided index or identifier. To list currently connected devices and verify that the specified index or identifier exists, run 'tns device'.`

Running tns device from terminal:

    ```
┌───┬─────────────┬──────────┬─────────────────────┬──────────┬───────────┐
    │ # │ Device Name │ Platform │ Device Identifier   │ Type     │ Status    │
    │ 1 │ vbox86p     │ Android  │ 192.168.56.101:5555 │ Emulator │ Connected │
    └───┴─────────────┴──────────┴─────────────────────┴──────────┴───────────┘
```

So far I tried the following:

 - Reinstalling VSC Nativescript plugin
 - Building latest Nativescript plugin from git repo
 - Launching via --geny 'Custom Phone'
 - Killing ADB server

However, I can run or livesync application normally via terminal, but the same doesn't work in Visual Studio Code.

**Comment by tsonevn** [comment]
Hi @rLoka, 
I reviewed this issue, however I was unable to reproduce issues while using  Visual Studio Code `debug` option. Could you try to [setup](https://github.com/NativeScript/docs/blob/master/tooling/android-virtual-devices.md) AVD Emulator and delete `.vscode` folder from your project. Then try to launch an application with the [debugger](https://docs.nativescript.org/tooling/visual-studio-code-extension#debugging) again.

I hope this help

**Comment by rLoka** [comment]
Hey @tsonevn,
thanks for responding. That is exactly what I did last night, and it worked like a charm. Looks like there is a problem with geny after all. I 'll stick to the official AVD from now on.
