### ISSUE TITLE
nativescript installation overwrites .bash_profile if activating bash autocompletion.

### ISSUE THREAD

**Issue by adlh** [NativeScript/NativeScript#2890]
I noticed this because after installing nativescript my aliases stopped working on tmux. 

After a bit of looking around, I noticed, that the 3 lines here:

    ###-tns-completion-start-###
    if [ -f /home/andrea/.tnsrc ]; then 
        source /home/andrea/.tnsrc  
    fi 
    ###-tns-completion-end-###

... were correctly appended to .bashrc at the end of the file, But on my .bash_profile (which only had a line sourcing my .bashrc) the old content was gone, and having only the tns-completion block now.
Because tmux uses .bash_profile, then that was the reason my .bashrc wasn't being sourced anymore on tmux windows.  

So I'm almost sure, the problem was caused by the installation script from nativescript, even though I didn't found on the github source where the install process lives. So I couldn't verify this.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#2124
