### ISSUE TITLE
Error: Cannot convert object to Landroid/graphics/Bitmap;

### ISSUE THREAD

**Issue by ryc16** [NativeScript/NativeScript#2895]
I think it was used to work on early {N} version with below xml where img is ImageSource but in {N} 2.3.0, I got binding error with "Error: Cannot convert object to Landroid/graphics/Bitmap; "

            <Image src="{{ img }}" class="avatar"/>

**Comment by NickIliev** [comment]
Hi @ryc16 ,

you can bind image-source in NativeScript 2.3.0

For example the code below creates miage source fromUrl and binds it to your image src property as expected.
```
  imageSource.fromUrl("http://sample.li/boat.jpg")
      .then(res => {
      vm.set("img", res);
  }).catch(err => {
      console.log(err.stack);
  })
```

**Comment by hshristov** [comment]
@ryc16 Setting `src` property to imageSource instance is also supported. If there is problem please provide sample project

**Comment by narayananl23** [comment]
I see that error. here is the example. Any idea what is wrong ?

xml
`<Image src="{{ myImage }}"  row="7"></Image>`

view-model
```
    var image = new imageModule.Image();
        image.src = "https://placehold.it/150x150";
    viewModel.myImage = image;
```

Error 
JS: Binding: Binding error while setting property src of Image(18)@file:///app/pages/mypage/mypage.xml:37:11;
: Error: Cannot convert object to Landroid/graphics/Bitmap; at index 0
