### ISSUE TITLE
Nativescript Tabview TabItem Title Width Size  partial solution for Android

### ISSUE THREAD

**Issue by arslanutku** [NativeScript/NativeScript#2897]
```
var application = require("application");
function pageLoaded(args) 
{
	var page = args.object;
	//tabViewID Change your tabview id.
	var tabView = page.getViewById("tabViewID");
	if(application.android)
		{

			//getViewForItemAt(3) at 3 ->item index. Your change item index.
			//0.3 Your change for item title text width
			tabView._getAndroidTabView().getViewForItemAt(3).getLayoutParams().weight =0.3;
		}

}
exports.pageLoaded = pageLoaded;
```

**Comment by NickIliev** [comment]
Hello @arslanutku ,

You can not change the style of tabViewItem title. Via NativeScript you can control [selectedColor for your Tabs](http://docs.nativescript.org/api-reference/classes/_ui_tab_view_.tabview.html) (for Android it will change the underline for the selected tabs)
You can also control the content of your tabs via selectedIndex property.
Some advanced techniques for working with tab-view can be fount [at this blog post](https://www.nativescript.org/blog/guest-post-getting-cozy-with-nativescript's-tabview).

**Comment by arslanutku** [comment]
Hello @NickIliev 

This is my solution. I wrote this for looking solution.
![tabitemtitlewidth](https://cloud.githubusercontent.com/assets/22832525/19382358/83df93c2-9208-11e6-981e-bf056a13d6d2.png)
