### ISSUE TITLE
Latest master cli and tns-core-modules:  Failed resolving method refresh on class org.nativescript.widgets.BorderDrawable

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/NativeScript#2903]
## To repro:

1) Clone repo and install:

```
git clone https://github.com/NathanWalker/ShoutOutPlay.git
cd ShoutOutPlay
npm i
```

2) Answer Firebase postinstall questions as follows:
<img width="608" alt="screen shot 2016-10-15 at 9 03 33 am" src="https://cloud.githubusercontent.com/assets/457187/19413436/b508f194-92e1-11e6-9c73-506c7ef625d1.png">

3) Move the files here: https://github.com/NathanWalker/ShoutOutPlay/tree/development/platforms/android to the root of `platforms` folder, then:

```
tns platform add android
```

Then drag/drop them back into `platforms/android` folder replacing `build.gradle`.

4) Then start up a GenyMotion emulator using at least v 6.0.0 w/ API 23, then:

```
tns run android
```

> An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to resume activity {com.wwwalkerrun.ShoutOutPlay/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreateView failed

> Error: java.lang.Exception: Failed resolving method refresh on class org.nativescript.widgets.BorderDrawable
    com.tns.Runtime.resolveMethodOverload(Runtime.java:971)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1010)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:895)
    com.tns.Runtime.callJSMethod(Runtime.java:883)
    com.tns.Runtime.callJSMethod(Runtime.java:867)
    com.tns.Runtime.callJSMethod(Runtime.java:859)
    com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
    android.app.Fragment.performCreateView(Fragment.java:2352)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
    android.a

/cc @vakrilov @bradmartin

**Comment by aboalwi** [comment]
I have this issue too.. i'm pulling my hair out right now.. half way to full baldness.

**Comment by NickIliev** [comment]
Hey @aboalwi , @NathanWalker 

I think your issue is related to [this one here](https://github.com/NativeScript/NativeScript/issues/2772). Try syncing the **_tns-core-modules_** and **_tns-core-modules-widgets_** and let me  know if that worked out for your cases.
