### ISSUE TITLE
ts to es6 to es5

### ISSUE THREAD

**Issue by Robophil** [NativeScript/NativeScript#2905]
Hi,
Am writing my code in typescript and targeting es6. I did the following.

``` bash
    tns install typescript && tns install babel
```

my package.json contains this

``` json
"babel": {
    "presets": [
      "es2015"
    ]
}
```

I don't get to see any es5 code in my .js file. or is the output sent somewhere else? when i run

``` bash
   tns prepare android
```

how does babel handle the conversion to es5??

**Comment by NickIliev** [comment]
Using Babel should make no differences when transpiling your files.
Here is [the article section](https://docs.nativescript.org/tooling/transpilers#installing-babel) on how Babel transpiler works in NativeScript

> Run the following command to install Babel support into your project:
> 
> ``` tns install babel ```
> The above command installs the Babel compiler and the nativescript-dev-babel npm module as a dev dependencies. The latter installs a prepare hook into your project, that transpiles your JavaScript files with Babel during build and when live-syncing.

**Comment by hdeshev** [comment]
I have an old demo that might help here: https://github.com/hdeshev/tns-ts-es2015-demo

**Comment by Robophil** [comment]
Thanks for the demo @hdeshev. I have something similar setup also but i'll give it a try again.
