### ISSUE TITLE
File upload issue on nativescript web-view kCFErrorDomainCFNetwork - iOS

### ISSUE THREAD

**Issue by jeyachanthuruj** [NativeScript/NativeScript#2908]
Hi Guys,

I'm facing a issue when i upload image on iOS. I'm using webView to upload image to server (REST-API). In our api we can't upload image as base64, thats why i used webview to convert base64 to Blob. I'm using nativescript-imagepicker to pick images.

**This is works fine on Android**

### Console log

> : [] __nw_connection_get_connected_socket_block_invoke 8 Connection has no connected handler
>  PAC stream failed with
> : [] nw_proxy_resolver_create_parsed_array PAC evaluation error: kCFErrorDomainCFNetwork: 2
> : [] __nw_connection_get_connected_socket_block_invoke 10 Connection has no connected handler
> : PAC stream failed with
> : [] nw_proxy_resolver_create_parsed_array PAC evaluation error: kCFErrorDomainCFNetwork: 2
> : CONSOLE ERROR file:///app/tns_modules/trace/trace.js:160:30: Binding: Binding error while setting property selectedIndex of DropDown(316)@file:///app/views/lodging/create/lodging-reservations.xml:30:17;: TypeError: undefined is not an object (evaluating 'this._array[index].displayMember')
> : [Generic] Creating an image format with an unknown type is an error
> : CONSOLE LOG file:///app/views/lodging/create/lodging-photo-view-model.js:137:28: [object Object]
> : [] __nw_connection_get_connected_socket_block_invoke 18 Connection has no connected handler
> : PAC stream failed with
> : [] nw_proxy_resolver_create_parsed_array PAC evaluation error: kCFErrorDomainCFNetwork: 2
> Oct 17 01:15:29 --- last message repeated 2 times ---
> Oct 17 01:15:29 MacBook-Pro com.apple.CoreSimulator.SimDevice.BF5311BD-42C8-4F22-98E5-8EB9EEB72577.launchd_sim[11765] (UIKitApplication:com.nativescript.arvixstay[0xd62d][12475]): Service exited due to Segmentation fault: 11

### Envirnment
- OS: MacOS Sierra 10.12
- CLI:  2.3.0
- Cross-platform modules: 2.3.0
- Runtime(s): tns-ios 2.3.0
- Plugin(s): 

>    "currency-formatter": "^1.0.2",
>     "dateformat": "^1.0.12",
>     "nativescript-checkbox": "^1.1.6",
>     "nativescript-drop-down": "^1.3.3",
>     "nativescript-imagepicker": "0.0.6",
>     "nativescript-loading-indicator": "^2.0.1",
>     "nativescript-master-technology": "^1.0.7",
>     "nativescript-pulltorefresh": "^1.1.7",
>     "nativescript-statusbar": "^1.0.0",
>     "nativescript-toolbox": "^1.38.0",
>     "nativescript-webview-interface": "^1.3.1",
>     "tns-core-modules": "^2.3.0",
>     "tns-ios": "^2.2.1"

I really don't have idea to how to recreate this issue. But If you need i can share my code (BitBucket or zip)

*NOTE: I have searched everywhere and couldn't get any answer that's why i post here. I'm not sure this is NativeScript issue or not. If this not related to here, Please remove this*

[video of emulator and console](https://drive.google.com/file/d/0ByY8vhkIp-iQNFlZZ2lwT21VeG8/view?usp=sharing)

**Comment by tsonevn** [comment]
Hi @jeyachanthuruj,
Thank you for reporting your issue, Unfortunately the given information is not enough to be able to reproduce your problem. It would help if you could provide sample project or to give more info, how to reproduce this behavior. In the meantime  I found some options, which could help you to resolve the problem. The first one is to remove `https:// ` from the host String. Another point is if there are issues with the Server DNS and  VPN server does not push DNS. [here ](https://groups.google.com/forum/#!topic/tunnelblick-discuss/pZw-BNGMEzo) you can find possible solution.

I look forward of hearing from you.

**Comment by jeyachanthuruj** [comment]
@tsonevn I'm closing this issue because, I create a new project and copy my old files to that, It's works fine. 

Thank you for your support.
