### ISSUE TITLE
CSS scale breaks background properties on iOS

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/NativeScript#2911]
Applying a scale transform to a button on iOS breaks `background-repeat` and `background-position` on iOS.

Using template-hello-world as a base.

main-page.xml

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="onNavigatingTo">
  
  <StackLayout>
      <Button class="btn" />
      <Button class="btn btn-scaled" />
  </StackLayout>
 
</Page>
```

app.css

```
.btn {
    background-color: orange;
    background-image: url("res://play");
    background-position: center;
    background-repeat: no-repeat;
}

.btn-scaled {
    transform: scale(0.5, 0.5);
}
```

Tested with tns-core-modules 2.3.0 and 2.4.0-2016-10-10-4344

![background-issue](https://cloud.githubusercontent.com/assets/1102402/19433435/9231c4f2-9458-11e6-9d40-fc60b2eeae4a.jpg)

**Comment by 3rror404** [comment]
Can anyone think of a workaround for this until a fix is released? I need to show my app to the client.

**Comment by NickIliev** [comment]
Hey @3rror404 
We will update the info here once an official fix is applied. Meanwhile, to resolve your issue, perhaps you can avoid using the transform scale for your button and instead use another technique to resize the button. For example, you can use dummy grid-layout with columns="* , 2*, *" where you button is placed within the 2* col. Or you can hardcore the button width based on it parent view using percentage!?

**Comment by 3rror404** [comment]
I got this working by wrapping the button in a StackLayout and scaling this instead. The inner button seems to be unaffected by the above bug in this situation.
