### ISSUE TITLE
Error: more than one library with package name 'com.telerik.android.data'

### ISSUE THREAD

**Issue by nmandyam** [NativeScript/NativeScript#2913]
App all working OK till recently. But, after upgrading on Windows 10 to NativeScript 2.3.0, I get this error on "build android" or "run android". Specifically:

**:processF0F1F2F3DebugResources FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':processF0F1F2F3DebugResources'.
> Error: more than one library with package name 'com.telerik.android.data'**

Any ideas on how to fix this?
Also, now unable to go back to 2.2.1 because that build assumes fibers is 1.0.13, when fibers has moved to 1.0.16. And building fibers 1.0.13 fails. But that's another story.

**Comment by Pip3r4o** [comment]
Hey @nmandyam 
Have you tried completely removing the platforms directory, as well as node_modules, and doing a `tns install`?

Additionally, if the above doesn't resolve your issue, could you paste the contents of your `package.json` or list all installed project dependencies?

**Comment by nmandyam** [comment]
I blew away the node_modules directory, then ran tns install. Now, when I run tns run android, I get this message (below). Will paste package.json after the message.
------------------------------------------------------
module.js:471
    throw err;
    ^

Error: Cannot find module 'babel-runtime/core-js/object/get-own-property-symbols'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\Dropbox (Daksh)\dftly\source-code\v4sm_public\node_modules\babel-traverse\lib\index.js:6:3
0)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
:asbg:runAstParser FAILED

FAILURE: Build failed with an exception.

* Where:
Build file 'F:\dropbox\dftly\source-code\v4sm_public\platforms\android\build-tools\android-static-binding-generator\buil
d.gradle' line: 56

* What went wrong:
Execution failed for task ':asbg:runAstParser'.
> Process 'command 'cmd'' finished with non-zero exit value 1
------------------------------------------------------
package.json:
---------------
{
  "description": "V4SM Public",
  "license": "UNLICENSED",
  "repository": {
    "type": "git",
    "url": "v4sm-public"
  },
  "nativescript": {
    "id": "com.dftly.v4sm_public",
    "tns-android": {
      "version": "2.3.0"
    }
  },
  "dependencies": {
    "crypto": "0.0.3",
    "moment": "^2.14.1",
    "nativescript-awesome-loaders": "^1.2.1",
    "nativescript-checkbox": "^1.1.3",
    "nativescript-statusbar": "^1.0.0",
    "nativescript-telerik-ui": "^1.1.1",
    "nativescript-timedatepicker": "^0.2.2",
    "nativescript-toast": "^1.3.0",
    "tns-core-modules": "^2.3.0-2016-08-18-3928"
  },
  "devDependencies": {
    "babel-traverse": "6.13.0",
    "babel-types": "6.13.0",
    "babylon": "6.9.0",
    "lazy": "1.0.11"
  },
  "name": "v4sm_public",
  "version": "1.4.0",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": ""
}
{
  "description": "V4SM Public",
  "license": "UNLICENSED",
  "repository": {
    "type": "git",
    "url": "v4sm-public"
  },
  "nativescript": {
    "id": "com.dftly.v4sm_public",
    "tns-android": {
      "version": "2.3.0"
    }
  },
  "dependencies": {
    "crypto": "0.0.3",
    "moment": "^2.14.1",
    "nativescript-awesome-loaders": "^1.2.1",
    "nativescript-checkbox": "^1.1.3",
    "nativescript-statusbar": "^1.0.0",
    "nativescript-telerik-ui": "^1.1.1",
    "nativescript-timedatepicker": "^0.2.2",
    "nativescript-toast": "^1.3.0",
    "tns-core-modules": "^2.3.0-2016-08-18-3928"
  },
  "devDependencies": {
    "babel-traverse": "6.13.0",
    "babel-types": "6.13.0",
    "babylon": "6.9.0",
    "lazy": "1.0.11"
  },
  "name": "v4sm_public",
  "version": "1.4.0",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": ""
}
------------------------------------------------------------------

Do let me know what else I can do to fix this. Thanks!

**Comment by nmandyam** [comment]
I deleted the platforms directories, then ran npm install (not tns install - that did not help, as I said in the my earlier message), then npm cache clean, then tns add platform. All OK now, thanks.
