### ISSUE TITLE
Serious issue of inconsistent content by deploying apk

### ISSUE THREAD

**Issue by ryc16** [NativeScript/NativeScript#2918]
### Tell us about the problem
I recently started to build a debug apk for easy of deploying various devices for testing (which also similar production deployment) but I encountered very strange behavior. Apk got deployed but content sometimes show updated and sometimes not. Also same apk deploy to 2 devices but one shows correctly but another devices shown incorrectly. This could be easy to tell looking at UI already. The problem happen randomly so very painful. I wish more people try this way and see if more people got the same problem.

Steps:
#1. build apk by "tns build android".
#2. copy the xxx_debug.apk from platforms\android\build\outputs\apk to my share place.
#3. I installed the apk to 2 devices. note: both devices had early version installed.

From app info, both devices got the same, in term of content, they look different see the attachment for 2 devices.

Device1: content not updated look like old UI.
[hw.zip](https://github.com/NativeScript/NativeScript/files/535713/hw.zip)

Device2: content did updated show correctly
[note2.zip](https://github.com/NativeScript/NativeScript/files/535715/note2.zip)

On device 1, Also try clean cache, clean data on the device, uninstall package from device package manager, then install apk from my share place. Still had same problem - correct app version but incorrect content.

Any idea? How can I further troubleshoot? How could I know what content I am running on? 

I am a bit worry what happen if this is on production environment, Would user will face this problem? If so, user wouldn't know about it. So this is very critical issue.

### Which platform(s) does your issue occur on?
Only tried on Android not IOS

### Please provide the following version numbers that your issue occurs with:
```
>tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.3.0           │ 2.3.0          │ Up to date    │
│ tns-core-modules │ 2.3.0           │ 2.3.0          │ Up to date    │
│ tns-android      │ 2.3.0           │ 2.3.0          │ Up to date    │
│ tns-ios          │                 │ 2.3.0          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```

**Comment by ryc16** [comment]
In order to get the content up to date, I have to plug my device to my computer and use tns command. 

tns livesync android --watch

Afterwards, everything works as expect.

Again, I am worry what would be happend if app is in production and install from ie google play store. Would this happen?

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#591
