### ISSUE TITLE
Application specific event IOS UIResponder,UIApplicationDelegate 

### ISSUE THREAD

**Issue by mubbashar** [NativeScript/NativeScript#2922]
Hi all,

## Please, provide the details below:

I am following this tutorial.
https://docs.nativescript.org/angular/core-concepts/application-lifecycle.html#use-application-events

and try to add a delege in main.ts

```
import * as application from 'application';
if (application.ios) {
    class MyDelegate extends UIResponder implements UIApplicationDelegate {
        public static ObjCProtocols = [UIApplicationDelegate];

        applicationDidFinishLaunchingWithOptions(application:UIApplication, launchOptions:NSDictionary):boolean {
            console.log("applicationWillFinishLaunchingWithOptions: " + launchOptions)

            return true;
        }

        applicationDidBecomeActive(application:UIApplication):void {
            console.log("applicationDidBecomeActive: " + application)
        }
    }
    application.ios.delegate = MyDelegate;
}
```

### Tell us about the problem

```
Found peer TypeScript 1.8.10
app/main.ts(10,30): error TS2304: Cannot find name 'UIResponder'.

app/main.ts(10,53): error TS2304: Cannot find name 'UIApplicationDelegate'.

app/main.ts(11,40): error TS2304: Cannot find name 'UIApplicationDelegate'.

app/main.ts(13,62): error TS2304: Cannot find name 'UIApplication'.
app/main.ts(13,91): error TS2304: Cannot find name 'NSDictionary'.
app/main.ts(19,48): error TS2304: Cannot find name 'UIApplication'.

```
### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.3.0
- Cross-platform modules: 2.3.0
- Runtime(s): 2.3.0
- Plugin(s): 

"@angular/common": "~2.0.2",
    "@angular/compiler": "~2.0.2",
    "@angular/core": "~2.0.2",
    "@angular/forms": "~2.0.2",
    "@angular/http": "~2.0.2",
    "@angular/platform-browser": "~2.0.2",
    "@angular/platform-browser-dynamic": "~2.0.2",
    "@angular/router": "~3.0.2",
    "email-validator": "1.0.4",
    "everlive-sdk": "1.7.1",
    "nativescript-angular": "~1.0.2",
    "nativescript-background-fetch": "^1.0.2",
    "nativescript-background-geolocation-lt": "^1.2.3",
    "nativescript-geolocation": "0.0.13",
    "nativescript-google-maps-sdk": "^1.3.14",
    "nativescript-iqkeyboardmanager": "1.0.1",
    "nativescript-social-share": "1.3.1",
    "nativescript-unit-test-runner": "^0.3.3",
    "nativescript-fonticon": "^1.1.0",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "^2.3.0"

**Comment by mubbashar** [comment]
http://stackoverflow.com/questions/37523071/how-can-i-access-native-api-in-nativescript-when-i-use-typescript

it is explained here to install

`npm i tns-platform-declarations`

and then 

```
/// <reference path="./node_modules/tns-platform-declarations/tns-core-modules/ios/ios.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/tns-core-modules/android17.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/tns-core-modules/org.nativescript.widgets.d.ts" />

```

add these in your references.d.ts file

after doing this i got these error

```
Executing before-prepare hook from /Users/Mubi/htdocs/metrotracker/application/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 1.8.10
node_modules/tns-platform-declarations/tns-core-modules/ios/objc-i386/objc!CoreAudio.d.ts(7,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'AudioBuffer' must be of type '{ new (): AudioBuffer; prototype: AudioBuffer; }', but here has type 'StructType<AudioBuffer>'.

node_modules/tns-platform-declarations/tns-core-modules/ios/objc-i386/objc!UIKit.d.ts(4940,15): error TS2300: Duplicate identifier 'UIEvent'.

node_modules/tns-platform-declarations/tns-core-modules/ios/objc-i386/objc!UIKit.d.ts(4940,15): error TS2417: Class static side 'typeof UIEvent' incorrectly extends base class static side 'typeof NSObject'.
  Types of property 'alloc' are incompatible.
    Type '() => UIEvent' is not assignable to type '() => NSObject'.
      Type 'UIEvent' is not assignable to type 'NSObject'.
        Property 'accessibilityActivationPoint' is missing in type 'UIEvent'.

node_modules/typescript/lib/lib.d.ts(14781,11): error TS2300: Duplicate identifier 'UIEvent'.
node_modules/typescript/lib/lib.d.ts(14787,13): error TS2300: Duplicate identifier 'UIEvent'.

TypeScript compiler failed with exit code 1

```

**Comment by NickIliev** [comment]
Hey @mubbashar you are on the right way - you really need tns-platform-declarations but as of version  2.3.0 there is a structural change in the way they are referenced in your **reference.d.ts** and in your **tsconfig.json** files.
You can read in details about the latest requirements when using [tns-platform-declarations in this section](https://github.com/NativeScript/NativeScript/tree/master/tns-platform-declarations).

Shortly you with the latest version you will need to cnahge your reference.d.ts  like this
(delete the all the previous content and replatce with the following)
```
/// <reference path="./node_modules/tns-core-modules/tns-core-modules.es2016.d.ts" />

/// <reference path="./node_modules/tns-platform-declarations/ios.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/android.d.ts" />
```

Also important is to modify your **tsconfig.json** (the file on the root level) like this

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "lib": [
            "es2016"
        ]
    }
}
```

**Comment by mubbashar** [comment]
trying to install tns-platform-declarations 2.4.0 and getting this error. It is updated on npm ?
```
 No compatible version found: tns-platform-declarations@^2.4.0
npm ERR! Valid install targets:
npm ERR! 2.4.0-2016-09-28-1, 2.3.0, 2.2.0, 2.0.0, 1.7.1
npm ERR! 

```

**Comment by NickIliev** [comment]
the current latest version is 2.3.0 .. you can use tns-platform-declarations@next to install the nightly build

**Comment by mubbashar** [comment]
the path are different in 2.3

**Comment by mubbashar** [comment]
there is no such file tns-core-modules.es2016.d.ts in tns-core-modules 2.3

**Comment by NickIliev** [comment]
You are absolutely right!
Use this in your package.json untile the next release is official. (among with the changes ins references.d.ts and tsconfig.json)

```
    "tns-core-modules": "next",
    "tns-platform-declarations": "next"
```
