### ISSUE TITLE
Cannot get nativeView from N view (iOS)

### ISSUE THREAD

**Issue by alexrainman** [NativeScript/NativeScript#2928]
I am loading a {N} view from a file using Loader:

```
var view = builder.load({
    path: "~/Views/Slides",
    name: "slider-view"
});
```

Then i need to convert this view to UIView to add it programmatically to another UIView:

```
var obj = <any>view;
obj._onAttached();
viewController.view = obj.ios;
```

Doing some debugging i can see that obj._subViews contains the {N} UI elements but i get a white screen.

It seems obj.ios, obj._view and obj._nativeView are null at this point.

Any ideas?

I am using the same in Android and it works with the difference that in android i am passing context to _onAttached.

```
obj._onAttached(application.android.currentContext);
container.addView(obj.android);
```

In this case obj.android contains the native view.

Thanks.

**Comment by alexrainman** [comment]
?

**Comment by alexrainman** [comment]
@hshristov i have beeb digging in {N} source but i cannot find anything that tells me how to get UIView from {N} view :(

**Comment by hshristov** [comment]
You need to call `_addView` if you want to add a View to existing View. `_onAttached` will be called from `_addView`. `.android` will be set after `_addView` is executed. `.ios.` should be populated immediately after `builder.load` completes (because we don't need context in order to create iOS UI components like in android).

I have some problems locally so @tzraikov will help you out.

**Comment by tzraikov** [comment]
Hey @alexrainman, I checked your code. Like @hshristov said you can't set the view property of an `UIView` object directly. You should call the `addView` method instead. Here is the code:

<pre>
        var viewController = new ViewContainer();
        viewController.tag = position;
        var iosView = <UIView>obj._view;
        viewController.view.addSubview(iosView);
</pre>

Note that at this point the `ViewController` isn't initialized and its size will be **0,0**. You can set the correct size when handling the `setViewControllersDirectionAnimatedCompletion` callback:

<pre>
this._ios.setViewControllersDirectionAnimatedCompletion(<any>[firstViewController], direction, true, (arg1) => {
        firstViewController.view.subviews[0].frame = firstViewController.view.frame;
        firstViewController.view.subviews[0].backgroundColor = new colorModule.Color("yellow").ios;
});
</pre>

**Comment by alexrainman** [comment]
@tzraikov this doesn't works. I xamarin i had to use viewController.view = obj._view if not i get weird behavior like this:

<img width="374" alt="screen shot 2016-10-21 at 8 19 26 am" src="https://cloud.githubusercontent.com/assets/3793554/19599590/14b8f880-9767-11e6-97fe-52aaff391343.png">

As you can see, i still get a blank screen. It seems you have a core problem here. Child elements doesn't requestLayout().

**Comment by alexrainman** [comment]
@tzraikov i tried everything, no luck :(

```
this._ios.setViewControllersDirectionAnimatedCompletion (<any>[firstViewController], direction, false, (arg1) => {
    firstViewController.view.subviews[0].frame = firstViewController.view.frame;
    firstViewController.view.subviews[0].backgroundColor = new colorModule.Color("yellow").ios;
    firstViewController.view.subviews[0].setNeedsLayout();
    firstViewController.view.subviews[0].layoutIfNeeded();
    firstViewController.view.subviews[0].setNeedsDisplay();
});
```

**Comment by alexrainman** [comment]
@tzraikov the white space at the bottom is the UIPageControl, as i'm implementing the delegate, it shows automatically. I have to add some code to make it transparent or not visible.

**Comment by alexrainman** [comment]
@tzraikov also, when you swipe you don't call this._ios.setViewControllersDirectionAnimatedCompletion by yourself, it's handled by UIPageViewController, so you cannot use the callback. Somehow the frame needs to be set in createViewController.

**Comment by tzraikov** [comment]
Although possible, replacing the default view of a ViewController by using the view setter is not recommended. You should add child views instead. 
In this case firstViewController.view.subviews[0] is the view we just added as a child view of viewController.view. It has no child views, that is why calling setNeedsLayout has no effect. Note that in native iOS applications there are no layouts and the parent view is responsible for positioning its child views.
Could you describe in detail what you want to achieve. This will help me to give you more adequate suggestions.

**Comment by alexrainman** [comment]
@tzraikov i know that firstViewController.view.subviews[0] i just added. That view is the ios representation of a {N} view that i just loaded with builder and it contains elements (2 labels and a button), but it seems loading them with builder doesn't call requestLayout() so, the are basically invisible.

**Comment by alexrainman** [comment]
@tzraikov i also tried declaring height and width of {N} view i am loading with no luck. Still getting a blank page :(

This is what i have in the xml i am loading with builder:

```
<StackLayout loaded="onLoaded" horizontalAlignment="center" padding="12">
    <Label text="{{ first }}"/> 
    <Label text="{{ last }}"/>
    <Button text="Remove me" tap="buttonTap"/> 
</StackLayout>
```

**Comment by alexrainman** [comment]
@tzraikov using Reveal (amazing tool) i was able to take a look at the DOM and i can confirm that the loaded view is added and the elements are there but they don't have frame/bounds. Take a look at this screenshots, something is failing at core level.

<img width="1438" alt="screen shot 2016-10-23 at 12 02 49 pm" src="https://cloud.githubusercontent.com/assets/3793554/19627971/3aaf12c8-9919-11e6-803a-58d1f25b3232.png">

<img width="1440" alt="screen shot 2016-10-23 at 12 03 13 pm" src="https://cloud.githubusercontent.com/assets/3793554/19627972/3f46ef36-9919-11e6-8d8b-4dc5ee9c0ae0.png">

<img width="1440" alt="screen shot 2016-10-23 at 12 03 32 pm" src="https://cloud.githubusercontent.com/assets/3793554/19627973/4489f8c6-9919-11e6-89c5-5d999c3c34e4.png">

<img width="1440" alt="screen shot 2016-10-23 at 12 03 52 pm" src="https://cloud.githubusercontent.com/assets/3793554/19627974/48cd4aaa-9919-11e6-9704-4d259a8d7de9.png">

**Comment by alexrainman** [comment]
@tzraikov this tool is amazing, i changed the button W and H and pum, it shows in the screen. Somehow requestLayout() is not being called down to all the children in the DOM when you load a view with builder in iOS

<img width="375" alt="screen shot 2016-10-23 at 12 13 24 pm" src="https://cloud.githubusercontent.com/assets/3793554/19628011/2a3a7eb8-991a-11e6-8abf-cf8ac8995696.png">

**Comment by alexrainman** [comment]
@tzraikov i also found that the first time i add the view, bindings doesn't work, but once i i start moving back and fort in the carousel, the show up :(

**Comment by tzraikov** [comment]
@alexrainman Thank you for those details. I understand now the issue. In this scenario you should call layout methods explicitly. It is not necessary to do this when handling the `setViewControllerAnimatedCompletion` handler. You can do it by overriding `viewDidLoad` and `viewDidLayoutSubviews` methods of `ViewController` class. Here is the code:

<pre>
export class ViewContainer extends UIViewController
{
    public tag: number;
    public owner: any;

    public viewDidLoad(): void {
        super.viewDidLoad();
        if (this.owner) {
            this.owner.onLoaded();
        }
    }

    public viewDidLayoutSubviews(): void {
        if (this.owner) {
            var width = this.view.frame.size.width;
            var height = this.view.frame.size.height;
            this.owner.measure(width, height);
            this.owner.layout(0, 0, width, height);
            this.owner._updateLayout();
        }
    }
}
</pre>

You can set the owner property when creating the `viewController` instance:

<pre>
var viewController = new ViewContainer();
viewController.tag = position;
viewController.view = <UIView>obj._view;
viewController.owner = view;
</pre>

**Comment by 3rror404** [comment]
Hey @alexrainman, what software are you using to inspect the ui in those screenshots?

**Comment by tzraikov** [comment]
@3rror404 You can use the build-in functionality of Xcode for this.
[Examining the View Hierarchy](https://developer.apple.com/library/content/documentation/ToolsLanguages/Conceptual/Xcode_Overview/ExaminingtheViewHierarchy.html)

**Comment by alexrainman** [comment]
@3rror404 i am using Reveal :)

**Comment by alexrainman** [comment]
@tzraikov i will try this and let you know. Thanks

**Comment by alexrainman** [comment]
@tzraikov we have {N} carousel-view :)

**Comment by tzraikov** [comment]
👍

**Comment by alexrainman** [comment]
@hshristov @tzraikov thanks for your support.
