### ISSUE TITLE
no docs / info on how to debug NativeScript with Visual Studio Android emulator 

### ISSUE THREAD

**Issue by born2net** [NativeScript/NativeScript#2929]
no docs / info on how to debug NativeScript with Visual Studio Android Sim

How to debug NativeScript with Visual Studio Android Simulator? I have the extensions installed and I looked at launch.json but could not find any docs on how to attach my Visual Studio emulator for Android 
to Visual Code editor?

ref: 
http://stackoverflow.com/questions/40137293/how-to-debug-nativescript-with-visual-studio-android-simulator

![capture](https://cloud.githubusercontent.com/assets/5090936/19529265/061de5c6-95e4-11e6-91b8-d3586913ae7a.PNG)

thanks,

Sean.

**Comment by Pip3r4o** [comment]
@born2net as with most Visual Studio Code extensions that come with a debug configuration, so does the NativeScript extension. You go to the debug view, and click the cogwheel icon with the little red exclamation mark, you will be prompted to choose a debug configuration for Node.js, NativeScript Extension, or another language/extension. You simply pick NativeScript and the project will be configured for you with a `launch.json`. Now you simply need to press the `play` button (green arrow pointing to the right) and you are good to go. 

Same answer posted on SO -> http://stackoverflow.com/a/40138854/6408287

**Comment by born2net** [comment]
tx for the help, closing!!!
