### ISSUE TITLE
Google Maps Not painting on Android for Angular 2 build

### ISSUE THREAD

**Issue by codyboaz** [NativeScript/NativeScript#2938]
I am trying to use the google maps api for an Angular 2 build. It us up and running yet it wont paint the map for Android. It works flawlessly for IOS yet android it builds without error, just wont paint the map. Has anyone else had this issue? Any Idea why this might be?

**Comment by tsonevn** [comment]
Hi @codyboaz,
Thank you for your interest in NativeScript.
Could you give us some more info about the plugin that you are using in your app. There are two `nativescript-maps` or `nativescript-google-maps-sdk`, which provides same functionality.   It will also help if you can provide more info about your case or to provide sample project, which could be debugged locally.

Regards,
@tsonevn

**Comment by codyboaz** [comment]
Hey @tsonevn 
I am using nativescript-google-maps-sdk. I figured out the issue. I had to remove then re add my android platform. Also I had to change my layout to:

<AbsoluteLayout width="100%" height="100%">
    <GridLayout width="100%" height="100%">
        <MapView></MapView>
    </GridLayout>
</AbsoluteLayout>

Thanks for the response.
