### ISSUE TITLE
Using IconFonts in ActionBar + navigation leeds to displaced icons

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#2941]
Related to [this comment](https://github.com/NativeScript/NativeScript/issues/2256#issuecomment-254712715)

Code to reproduce [here ](https://github.com/tskweres/tinder-clone)

Description: 
- Create two pages with ActionBarItem that are using **IconFonts**
- Navigate from pageA to pageB with action-bar set

```
<ActionItem ios.position="right" (tap)="goBack()"> 
    <Button #backicon text="&#xE87D;" class="material-icons backicon"></Button> 
</ActionItem>
```

result: Icon is loaded at one place at the initial moment - then the icon is displaced by x (where x is the icon size)

**Comment by tskweres** [comment]
temporarily I just had the action items for 400ms after the page transition until I can safely show, but eagerly awaiting this :)

**Comment by tskweres** [comment]
Is there an alternative to font icons in the actionbar? raw images?

**Comment by NickIliev** [comment]
@tskweres 

Yeas - you can use images to customize both your ActionBar title and ActionBar items.
Example for customizing the title can be found [here](https://docs.nativescript.org/ui/action-bar#using-a-custom-title-view).

And [at this section ](https://docs.nativescript.org/ui/action-bar#action-items)you can see how to customize your action-bar items and use system icons

**Comment by tskweres** [comment]
@NickIliev yeah I'm interested in using custom icons not the system icons. I think what I'll do is pop open photoshop and save the font icons as images for now and see what happens :/
