### ISSUE TITLE
Please make a better dev flow in Windows, gotta kill the tab 100's of times...

### ISSUE THREAD

**Issue by born2net** [NativeScript/NativeScript#2943]
Hi Guys,
so I am developing using the command:

```
tns debug android --device 169.254.138.177:5555 --debug-brk --watch
```

the problem is that on every change I save I have to kill the chrome tab that opens up (which I dont need as I debug in visual code)
second issue is that I have to reconnect debugger in visual code... again hundreds of times.

Is there anyway we can:
1. not open a tab in browser on ever save / change when debug?
2. have visual code auto-retry and connect on save to debugger?

That would save me a ton of time developing and will make the workflow MUCH better

Regards,

Sean

**Comment by tsonevn** [comment]
Hi @born2net,
Thank you for reporting those problems.

At the moment our VS Code extension do not support Sync with Watch. There is an issue, which has been already logged [here ](https://github.com/NativeScript/nativescript-vscode-extension/issues/78), where you could track its progress.
Regarding to your first problem I confirm that this a real problem, while using `tns debug android --watch` and on every change in the new tap in the browser will be open. We will investigate this problem and verify how it could be fix. You could follow the progress here.


Hope this helps

**Comment by tsonevn** [comment]
Enabled with https://github.com/NativeScript/nativescript-vscode-extension/pull/96
