### ISSUE TITLE
White background for a split second

### ISSUE THREAD

**Issue by dianikol** [NativeScript/NativeScript#2944]
Hey guys!

A strange thing I noticed while building my first app.

When I add a background color on a page , let's say the first page of the app, for a split second the background color is white (the default i guess) and then it gets the color I specified in my css file. 

If I navigate using the fade transition the same thing happens.

Any ideas? 

I'm using CLi 2.3.0 with no extra plugins 
tns-ios: 2.3.0
tns-android: 2.3.0

Thank you

**Comment by paulocarvalhodesign** [comment]
You can style that defining background for the activity on the theme using the xml values on Android.

**Comment by NickIliev** [comment]
@dianikol 

Indeed, the situation you are describing is observed during the page transitions in Android.
The issue [is related to this one](https://github.com/NativeScript/NativeScript/issues/1748) and is logged as the feature.
I am closing this one as duplicate - please keep track on the original feature issue for information.

**Comment by greenstevester** [comment]
@dianikol - I am seeing the same issue, did you ever find a workaround?

**Comment by dianjuar** [comment]
The same problem over here.

I'm using CLi 3.0.1
tns-android: 3.0.0
