### ISSUE TITLE
Changing applicationId in package.json doesnt affect the build

### ISSUE THREAD

**Issue by Legited** [NativeScript/NativeScript#2945]
Hi,

Running NS 2.3.0 on Android, changed the "nativescript id" in package.json, but still get default Application ID. Final AndroidManifest.xml will still contain `package="org.nativescript.xxx"`

For now changed it manually in App_Resources/Android/app.gradle

**Comment by Pip3r4o** [comment]
Duplicate of https://github.com/NativeScript/nativescript-cli/issues/2089. Follow the progress of the issue resolution there.
