### ISSUE TITLE
How can I get tap event when I set textfield is not editable?

### ISSUE THREAD

**Issue by liuhanlcj** [NativeScript/NativeScript#2962]
### Tell us about the problem
I want to have a not editable textfield to display some string, and I want to it can deal tap action so I can do some thing when player click this textfield. I write code like this
```
<TextField hint="like" text="{{interests}}" autocorrect="false" autocapitalizationType="none" editable="false" tap="onTapInterests" />

function onTapInterests() {
    console.log("onTapInterests");
}
exports.onTapInterests = onTapInterests;
```
But I can not see output log.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.3.0
- Cross-platform modules: "version": "2.3.0"
- Runtime(s): "version": "2.3.0"
- Plugin(s): 
"email-validator": "1.0.4",
 "nativescript-checkbox": "1.1.6",
 "nativescript-drop-down": "^1.3.3",
 "tns-core-modules": "2.3.0"
"babel-traverse": "6.16.0",
"babel-types": "6.16.0",
"babylon": "6.13.0",
"lazy": "1.0.11"

**Comment by NickIliev** [comment]
I guess you have managed to get the solution so I am posting info for any future community member : Working as expected : sample code [here](https://github.com/NickIliev/NativeScript-issues/tree/master/NativeScript/issue_2962)

**Comment by rafaelcmrj** [comment]
It works only for Android. iOS doesn't listen to (tap) events when editable = false.

**Comment by princy05** [comment]
I am also facing the same issue. My textfield ui component with editable set as false is not working for tap event
