### ISSUE TITLE
Unable to debug using Remote Chromium Javascript Debugger for Eclipse

### ISSUE THREAD

**Issue by iguissouma** [NativeScript/NativeScript#2964]
I'm following this steps in this [link](https://docs.nativescript.org/runtimes/android/debug/debug-eclipse) on how to debug a nativescript app on android using Remote Chromium Javascript Debugger for Eclipse.

I installed eclipse and the plugin as mentioned on the tutorial.

I run the application on my android using this command:
`tns debug android --device 1 --debug-brk --no-client`
`# NativeScript Debugger started #`

`tns debug android --get-port`
`device: G5AxFG0xxxxSNM debug port: 40000`

`adb forward --list`
`G5AxFG0xxxxSNM  tcp:40000 localabstract:org.nativescript.tools-debug`

I tried to run the following remote debug configuration:

![debug-eclipse](https://cloud.githubusercontent.com/assets/9085108/19716070/e605f3e8-9b59-11e6-9c09-fade13f257fa.png)

I got this error:
![debug error](https://cloud.githubusercontent.com/assets/9085108/19716173/9378340a-9b5a-11e6-8d54-5e39dd3d7ca0.png)

I'm using the following version:
Chromium plugin for eclipse:
Chromium JavaScript Remote Debugger 0.3.8.201210040400  
Eclipse:
Eclipse IDE for Java Developers 4.4.1.20140925-1820 
tns:
2.3.0

Can you please verify if it's still possible to debug android app using Eclipse?

**Comment by blagoev** [comment]
Yeah that eclipse plugin is very outdated and is not working. We will be needing to update our documentation on that article. Consider using Visual Studio Code to debug {N} apps

**Comment by iguissouma** [comment]
I'm aware of the debug feature in vscode, I was investigating if we can use Chromium remote debugguer of eclipse or webstorm to debug a nativescript app.
What changes made to nativescript that broke debug with eclipse?

**Comment by blagoev** [comment]
I guess V8 updates. But that time out error is like that for quite some time. Not sure what have changed on the client side. Never tried webstorm for that.

**Comment by denofevil** [comment]
@blagoev the problem is that there's no V8-Version field in your debugger protocol output, which is expected by WebStorm (and probably Eclipse). We'll try to workaround that on our side, but I'm not sure what's the reason to remove it? E.g. Electron provides that field and attach works fine

**Comment by atanasovg** [comment]
Hey @denofevil, thanks for your observations! We are currently after enabling Chrome DevTools integration and I guess there will be some changes in our protocol with regards to that effort. In the mean time, if this missing V8-Version field is the issue could you please directly make a PR to the Android Runtime repo and we will make sure to accept it?

**Comment by denofevil** [comment]
@atanasovg, thank you, we were able to workaround it on our side, but I think having this field would be better as we won't have to make assumptions about Node version. I'll take a look at it a little bit later

**Comment by blagoev** [comment]
@denofevil 
Currently we are using the old v8 API to work with the debugger. The {N} runtime just redirects messages back and forth between the client and the debugger back end. When we switch to the v8-inspector debugger then I guess these fields will come in as expected. Also there is work on the v8 side to move away from the newer JS debugger and to have native debugger. So this field is in big move right now

So write us anything you want us to help you with on this issue. 
P.S. The v8-inspector bits will be present in v8 5.5 in late December.

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#639
