### ISSUE TITLE
Enhancement:  Global Events 

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#2966]
## Please, provide the details below:

I developed the global events plugin, I would like to see if we can merge this into core with an additional change.   I have found I am in need to create an addition event that fires when ever a view component is created.    

The global events plugin currently works very well as a plugin, and I have no issues leaving the majority of it as a plugin.   However to make the the View component fire a global "onCreated" event, would actually require patching the actual view to fire the event in its constructor.    This requires a change to the actual tns core file; and not something I can just monkey-patch in via a plugin.

I am willing to create the entire PR; but I am not going to waste everyone's time if this is something that you won't add to core and becomes better suited to be another patch that justifies my proposed TCP project.
### Which platform(s) does your issue occur on?

Both

**Comment by hshristov** [comment]
HI @NathanaelA,

In order to accept pull request it have to add concrete benefit (like feature implementation or bug fix). to everyone. In this case I would really love if you could share more details about the scenario that you want to implement. Sharing current implementation will also help understand the use case.

**Comment by NathanaelA** [comment]
Well the first thing to understand is what the global events does;
Well the current global events published these events:

    Page.navigatingToEvent
    Page.navigatedToEvent
    Page.navigatingFromEvent
    Page.navigatedFromEvent
    Page.shownModallyEvent
    Page.showingModallyEvent
    View.loadedEvent
    View.unloadedEvent

These events are global, in that I can do 
    var View = require('...view').View;
   View.on('loadedEvent', function(me) {  /* do something with this view */ });

So now any View (and all View descendants) that is "loaded" in the future will trigger that event handler.   This has come in very handy with several of my plugins use this plugin as a dependency.   

So based on this description I assume you understand what I mean by these are **global** event handlers; they are set once, and anytime they would be fired for a individual control, my handler is also called.

---

Now going forward I have need to have an added event 

    View.onCreated

This would allow me to tie into each control as it is created before anything else occurs; I have need of this in a couple plugins.

1. the first being my scaling font utility; the ability for me to get access to the controls as they are created would allow me to have per-page settings instead of the font scaling right now is totally global, either on or off.    I would like to add per-page, and angular support.  
2. The second is my international lang support plugin.|
3. It simplifies code in two other plugins and allows them to work in angular.

   However the key is that the View **constructor** has to call the event with the newly created object, so it isn't something I can monkey patch...

**Comment by andreasotto** [comment]
+1

**Comment by bradmartin** [comment]
+1

**Comment by NathanWalker** [comment]
+1

**Comment by sitefinitysteve** [comment]
I see this as only being beneficial... 
![image](https://cloud.githubusercontent.com/assets/1542376/19831603/1514f77c-9ddc-11e6-871b-935b5f6c1f0b.png)

please

**Comment by bradmartin** [comment]
Speaking of which what are the negatives of doing this?

**Comment by NathanaelA** [comment]
@bradmartin - There are two potential negative:

1. Since this is an event on the view component, this event is fired on every component that is created, Page, Button, Label, etc.    This will add extra micro-seconds to the component creation.   However, since they added ZonedCallback to tons of areas for NG support, my proposed patch should be way less intrusive and less costly (app time/memory wise)  than that crazyness.

2. This adds more code to the core framework, more code means more places for bugs and more code to maintain by the framework team.  Sometimes you have to decide what is worth bringing in and what is worth leaving out.

However the good news if the core team decides not to support it in the framework; I have come up with two ways to do it myself.   


1.  My [TNS-Core-Patcher plugin](https://github.com/NathanaelA/nativescript-dev-tnscorepatcher) idea, this would definitely add a :+1: for doing the TCP plugin, it always better to patch before than at runtime, however the second way.

2. Monkey patch the constructor at runtime ->
```
  var View = require('ui/view').View;

  var newClass = new Function("console.log('new code'); " + View.toString().substring(12) + "; console.log(`more new code`);") ;
  for (var key in oldClass.prototype) { if oldClass.hasOwnProperty(key) newClass.prototype[key] = oldClass.prototype[key]; }
  View = newClass;
```

**Comment by rigor789** [comment]
Implemented in https://github.com/NativeScript/NativeScript/pull/8830
