### ISSUE TITLE
Livesync doesn't work for TS files (Android)

### ISSUE THREAD

**Issue by bm-software** [NativeScript/NativeScript#2972]
### Tell us about the problem
Livesync feature doesn't working anymore for `ts` files. Works fine only for `css` and `html` files.

**Moreover, also running the build command followed by run command my changes to ts files are not deployed to the emulator.**

**NOTE**: I've tried to run livesync with `--log trace` option and when I change a ts file the CLI log the following lines:

    Shasum of file C:\Code\NativeScriptsProjects\SOSNumbers\app\pages\tabs\tabs.component.ts is f9e0fbd5f5c8cd4e0859ba8c3ade2704caf69ec0
    Adding C:\Code\NativeScriptsProjects\SOSNumbers\app\pages\tabs\tabs.component.ts file with f9e0fbd5f5c8cd4e0859ba8c3ade2704caf69ec0 hash.
    Syncing filePath C:\Code\NativeScriptsProjects\SOSNumbers\app\pages\tabs\tabs.component.ts, mappedFilePath is C:\Code\NativeScriptsProjects\SOSNumbers\platforms\android\src\main\assets\app\pages\tabs\tabs.component.ts
    Syncing C:\Code\NativeScriptsProjects\SOSNumbers\platforms\android\src\main\assets\app\pages\tabs\tabs.component.ts

Seems that livesync gets stuck on syncing.

### Which platform(s) does your issue occur on?
Android (not tested on iOS yet)

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.3.0
- Cross-platform modules: 2.3.0
- Runtime(s): tns-android: 2.3.0
- Plugin(s): 

    "nativescript-cardview": "^1.2.0",
    "nativescript-dom": "^1.0.7",
    "nativescript-floatingactionbutton": "^2.2.5",
    "nativescript-geolocation": "0.0.13",
    "nativescript-google-maps-sdk": "^1.3.14",
    "nativescript-material-icons": "^1.0.1",
    "nativescript-ng2-fonticon": "^1.2.6",
    "nativescript-phone": "^1.2.2",
    "nativescript-snackbar": "^1.1.4",
    "nativescript-social-share": "^1.3.1",
    "nativescript-sqlite": "^1.1.2",
    "nativescript-telerik-ui": "^1.4.1",
    "nativescript-theme-core": "^0.1.3",
    "tns-platform-declarations": "^2.3.0"

### Please tell us how to recreate the issue in as much detail as possible.
Execute `tns livesync android --emulator --watch` command from command prompt

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#2167
