### ISSUE TITLE
Documentation: add an article how to run unit tests and how to write a functional test.

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#298]
Often is the question how to setup testing environment and it will be good if we have articles about this in the docs.

**Comment by emiloberg** [comment]
@ligaz [just wrote](https://twitter.com/ligaz/status/607451819359354881):
> We are currently prototyping some ideas for unit testing. We will post a GitHub issue with our findings in the coming weeks.

**Comment by ligaz** [comment]
I don't want to spoil the surprise so I will just give this hint: https://github.com/NativeScript/karma-nativescript-launcher/blob/master/concept.md :smiley_cat:

**Comment by enchev** [comment]
This issue was moved to NativeScript/docs#123

**Comment by fritzvd** [comment]
I just wrote this in lieu of something better:
http://blog.technokrat.nl/2015/10/13/writing-tests-for-nativescript-apps/
