### ISSUE TITLE
Data Binding to Observable not working.

### ISSUE THREAD

**Issue by Arman8852** [NativeScript/NativeScript#2983]
I am using tns version 2.3.0 for Android.I have a problem with my fetch response.I am trying to attach response data to a Observable.But I have failed to do so.I have received the reponse data and now I am trying to attach it to the Observable inside a function.But it's not working.I have added my Viewmodel and Controller JS.Please Check and kindly give a response.

```
var fetchModule = require("fetch");
var Observable = require("data/observable").Observable;
var ObservableArray = require("data/observable-array").ObservableArray;
var pageData = require("data/observable").Observable;

var data;
var priceFromResponse;

function ModelViewModel() {

  var viewmodel = new Observable();
  var Viewmodel = new Observable();
  viewmodel.get = function (model) {

    data = model;

  }

  var viewModel = new ObservableArray();
  viewModel.load = function () {
    fetch("http://10.0.2.2:8000/get_model", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        brand: data,
      })
    }).then(r => { return r.json(); }).then(function (data) {

      for (var i = 0; i < data.length; i++) {
        viewModel.push({
          model: data[i].product,
        });
      };
      price = data[0].value;
      return price;
    }).then(getPrice)
  }
  viewModel.empty = function () {
    while (viewModel.length) {
      viewModel.pop();
    }
  };

  function getPrice(price) {
    Viewmodel.set("price", price);
  }
  return [viewModel, viewmodel, Viewmodel];
}
module.exports = ModelViewModel;
```
[tns.txt](https://github.com/NativeScript/NativeScript/files/559951/tns.txt)

```
var ModelViewModel = require("../../shared/model_view_model");
var modelList = new ModelViewModel();
var view = require("ui/core/view");
var observableModule = require("data/observable");

var Observable = require("data/observable").Observable;
var list;
var text;

var Data = new observableModule.fromObject({
  modelList: modelList[0],
  price: modelList[2].price

 );

exports.loaded = function (args) {
  page = args.object;
  page.bindingContext = Data;

  modelList[0].empty();
  modelList[0].load();

};

exports.value = function (args) {
  console.log(text);
}

```
[tns2.txt](https://github.com/NativeScript/NativeScript/files/559954/tns2.txt)

**Comment by NickIliev** [comment]
Hey @Arman8852 

There are several points you should reconsider in your model structure.
Once, you have created multiple Observables inside the model - why is that needed in the first place.
Take, as example, the view-model from the  basic app created with `tns create myApp`

```
function createViewModel() {
    var viewModel = new Observable();
    viewModel.counter = 42;
    viewModel.message = getMessage(viewModel.counter);

    viewModel.onTap = function() {
        this.counter--;
        this.set("message", getMessage(this.counter));
    }

    return viewModel;
}
```

You do not need to create several Observable objects inside you view model class. Once created you can attach your methods and properties to it as shown for **_onTap_**  function and for **_counter_** and **_message_** properties (or in your case and array of items)

Then your code also contains several variables with a different casing of the word view model which makes it harder to read and follow. Reading your code you can create your ObservableArray that can be a property of your view model.

For example: 
```
viewmodel.items = new ObservableArray();

// and then in your fetch response you can se the ObservableArray like this:
this.items.push(itemToPush);
```

**Comment by Arman8852** [comment]
Sir problem is I have to populate a listview and level from  response.If I try to push level data in Observable array.It's not working.So,I have created another observable.What I want to say,can my Observable array contain two different data for Level and list view?

**Comment by NickIliev** [comment]
Hey @Arman8852 

In an observable array you can push any kind of data and it will be structured just as in any other array.
You can either flatten your data if you want the array to contains everything (not very proper case when youare going to use it to populate lists) or you can create different properties in your view-model and populate them when the data is fetched.
In order to help you out can you provide sample data you are receiving from the HTTP response.
From what I've understood you are receiving data that is containing a key which you want to use on one level and then you are also receiving an array of items you want to populate in list-view....

For example something like : 
```

{
    "id": 102605,
    "img_src": "http://mars.jpl.nasa.gov/msl-raw-images/proj/msl/redops/ods/surface/sol/00945/opgs/edr/fcam/FLB_481377766EDR_F0451108FHAZ00323M_.JPG",
    "earth_date": "2015-04-03",
    "cameras": [
        {
        "name": "FHAZ",
        "full_name": "Front Hazard Avoidance Camera"
        },
        {
        "name": "NAVCAM",
        "full_name": "Navigation Camera"
        },
        {
        "name": "MAST",
        "full_name": "Mast Camera"
        },
        {
        "name": "CHEMCAM",
        "full_name": "Chemistry and Camera Complex"
        },
        {
        "name": "MAHLI",
        "full_name": "Mars Hand Lens Imager"
        },
        {
        "name": "MARDI",
        "full_name": "Mars Descent Imager"
        },
        {
        "name": "RHAZ",
        "full_name": "Rear Hazard Avoidance Camera"
        }]
}
```
In the received data above you have an object that have several keys on one level (**_id_**, **_img_src_**, **_earth_date_** and **_cameras_**)
The cameras key is array of objects that you can populate in your list-view while the level keys can be used as appropriate in other levels.

Now when receiving the data you can check if the key is your array of items and push it to the items property which will be used for your list-view. Then you can check if the key is the level data and push it to a "level" data property.

e.g.

 ```
    if (key === "id") {
        console.log("id: " + element);
        _this.id = element;
        _this.notifyPropertyChange("id", element);
    }
     if (key === "cameras") {
           // push your cameras to your items array
     }                         
```

Full examples on how to bind complex API responses can be found in this sample app 
[here](https://github.com/NickIliev/NativeScript-Cosmos-Databank/blob/master/app/models/asteroid/asteroid-view-model.js) and [here](https://github.com/NickIliev/NativeScript-Cosmos-Databank/tree/master/app/models/rovers)

**Comment by Arman8852** [comment]
Sir,first,thank you for helping me.You have got my point.My response is like this-
`[{"id":1,"product":"350V4X-S023BD","price":52000,"brand_id":3,"created_at":"2016-10-18 09:42:26","updated_at":"2016-10-18 09:42:26","value":"12000tk"}],{"id":2,"product":"NP360V4X-K023BD","price":34500,"brand_id":4,"created_at":"2016-10-18 09:44:54","updated_at":"2016-10-18 09:44:54"}]`
This is my response.I am trying to create a Listview using the `"product"` from response and a level using the `response[0].value or `Value from the first item of the response array or `Value` from the response.Notice,value is present only in the first item of response array. 

Controller.js(model.js):
```
var ModelViewModel = require("../../shared/model_view_model");
var modelList = new ModelViewModel();
var observableModule = require("data/observable");
var Data = new observableModule.fromObject({
 
    modelList: modelList[0],
	 price :modelList[0].price
	
});  

```
view(model.xml):
```
<Page loaded="loaded">
    <GridLayout>

	 <Label text="{{ price }}"  horizontalAlignment="left" verticalAlignment="center"/>

                <ListView items="{{ modelList }}" >

            <ListView.itemTemplate>

 <Label text="{{ model }}"  horizontalAlignment="left" verticalAlignment="center" tap="display"  />
	
</ListView.itemTemplate>
        
</ListView>
		
</GridLayout>

</Page>
```
If I take the example of the response you have given,then I am trying to populate a Listview using the `camera` array and create a level by using `id` or `img_src` or `earth_date`.

**Comment by NickIliev** [comment]
I can not really reproduce your final goal as the JSON you have sent us is not a valid one as a structure.
Still ,you need to map your data to the properties that you want to populate.

```
.then(r => { return r.json(); }).then(function (data) { 
   console.log(data); // first good practice -- check the format your data is received.
   
  // now map the data in the proper format that you want to handle
  // push the array of models in your items array property
  // push the price in your price property
  // as here you have JSON you can get them by their key e.g. if (key === "id")
}
```
However, you should handle your data based on the JSON structure that you are receiving.

If you follow the example app shown above you can also create an object with the properties you want and use this object as your dataItem property.

As this is not an observable data related issue but a parsing data one I am closing this one here - please contact me in your StackOverflow thread if you need further assistance,

**Comment by Arman8852** [comment]
Thank You sir.Could you please share your Stackoverflow Id?Then I can reach out to you in case of any problem.One last thing,can I bind data for both Listview and Level?

**Comment by NickIliev** [comment]
[http://stackoverflow.com/users/4936697/nick-iliev](http://stackoverflow.com/users/4936697/nick-iliev)

**Comment by Arman8852** [comment]
Mr NickIliev,are you there? I need your help.
