### ISSUE TITLE
Showcase app task is not available in google playstore

### ISSUE THREAD

**Issue by gokulkrishh** [NativeScript/NativeScript#3]
I tried to download showcase task app from google play store. It seems the link is broken https://play.google.com/store/apps/details?id=com.telerik.Tasks

**Comment by valentinstoychev** [comment]
Thank you for reporting this. The app will be back on the marketplace soon. We found some issues that needs polish on our end.

**Comment by gatkinsNZ** [comment]
Still no app available.
