### ISSUE TITLE
Found peer TypeScript 2.0.3 Error: read ECONNRESET     at exports._errnoException (util.js:1008:11)     at TCP.onread (net.js:563:26)

### ISSUE THREAD

**Issue by HiskDeathnote** [NativeScript/NativeScript#3004]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

**Comment by HiskDeathnote** [comment]
Found peer TypeScript 2.0.3
Error: read ECONNRESET
    at exports._errnoException (util.js:1008:11)
    at TCP.onread (net.js:563:26)
keeps showing up everytime I execute tns run android or tns run android --emulator. Help

**Comment by tsonevn** [comment]
Hi @HiskDeathnote,
Thank you for reporting this issue.
However the given information is not enough to diagnose your problem. Could you provide sample code that is causing this strange behavior  and to run `tns run android --log trace`, which will generate more details error log. It will also help if you could share more info about your environment: `Node`, `CLI`, `tns_core_modules` versions. In the mean time you could check the NativeScript version you have installed and check your project `package.json`, whether you are using `tns-core-modules` version 2.3.0. 

Hope this helps.

**Comment by HiskDeathnote** [comment]
Hello, 
I am using the latest version of tns-core-modules and nodejs. tns doctor shows no errors and tns run android --log trace shows
Socket {
  connecting: false,
  _hadError: false,
  _handle:
   Pipe {
     bytesRead: 0,
     _externalStream: {},
     fd: -1,
     writeQueueSize: 0,
     owner: [Circular],
     onread: [Function: onread],
     reading: true },
  _parent: null,
  _host: null,
  _readableState:
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: true,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  domain: null,
  _events:
   { end: { [Function: g] listener: [Function: onend] },
     finish: [Function: onSocketFinish],
     _socketEnd: [Function: onSocketEnd],
     close: [Function] },
  _eventsCount: 4,
  _maxListeners: undefined,
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     decodeStrings: false,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     bufferedRequestCount: 0,
     corkedRequestsFree: CorkedRequest { next: null, entry: null, finish: [Function] } },
  writable: false,
  allowHalfOpen: false,
  destroyed: false,
  _bytesDispatched: 0,
  _sockname: null,
  _writev: null,
  _pendingData: null,
  _pendingEncoding: '',
  server: null,
  _server: null }
                                                                                                       Exec npm -v
 stdout: 3.10.3

 stderr:
spawn: java "-version"
Exec node-gyp -v
 stdout:
 stderr: 'node-gyp' is not recognized as an internal or external command,
operable program or batch file.

Exec "C:\Users\Hisk\AppData\Local\Android\android-sdk\platform-tools\adb" version
 stdout: Android Debug Bridge version 1.0.36
Revision 84e3321d5db3-android

 stderr:
spawn: C:\Users\Hisk\AppData\Local\Android\android-sdk\tools\android.bat "-h"
Result when throw error is false:
{ stdout: '\n       Usage:\n       android [global options] action [action options]\n       Global options:\n  -s --silent     : Silent mode, shows errors only.\n  -v --verbose    : Verbose mode, shows errors, warnings and all messages.\n     --clear-cache: Clear the SDK Manager repository manifest cache.\n  -h --help       : Help on a specific command.\n\n                                                                    Valid\n                                                                    actions\n                                                                    are\n                                                                    composed\n                                                                    of a verb\n                                                                    and an\n                                                                    optional\n                                                                    direct\n                                                                    object:\n-    sdk              : Displays the SDK Manager window.\n-    avd              : Displays the AVD Manager window.\n-   list              : Lists existing targets or virtual devices.\n-   list avd          : Lists existing Android Virtual Devices.\n-   list target       : Lists existing targets.\n-   list device       : Lists existing devices.\n-   list sdk          : Lists remote SDK repository.\n- create avd          : Creates a new Android Virtual Device.\n-   move avd          : Moves or renames an Android Virtual Device.\n- delete avd          : Deletes an Android Virtual Device.\n- update avd          : Updates an Android Virtual Device to match the folders\n                        of a new SDK.\n- create project      : Creates a new Android project.\n- update project      : Updates an Android project (must already have an\n                        AndroidManifest.xml).\n- create test-project : Creates a new Android project for a test package.\n- update test-project : Updates the Android project for a test package (must\n                        already have an AndroidManifest.xml).\n- create lib-project  : Creates a new Android library project.\n- update lib-project  : Updates an Android library project (must already have\n                        an AndroidManifest.xml).\n- create uitest-project: Creates a new UI test project.\n- update adb          : Updates adb to support the USB devices declared in the\n                        SDK add-ons.\n- update sdk          : Updates the SDK by suggesting new platforms to install\n                        if available.\n',
  stderr: '',
  exitCode: 0 }
Exec mono --version
 stdout:
 stderr: 'mono' is not recognized as an internal or external command,
operable program or batch file.

Exec git --version
 stdout: git version 2.8.2.windows.1

 stderr:
Exec gradle -v
 stdout:
 stderr: 'gradle' is not recognized as an internal or external command,
operable program or batch file.

Exec "C:\Program Files\Java\jdk1.8.0_102\bin\javac" -version
 stdout:
 stderr: javac 1.8.0_102

System information:
{ procInfo: 'nativescript/2.3.0',
  platform: 'win32',
  os: 'Windows 10 Pro 6.3.14393',
  shell: 'C:\\WINDOWS\\system32\\cmd.exe',
  dotNetVer: '4.6.01586',
  procArch: 'x64',
  nodeVer: 'v6.3.0',
  npmVer: '3.10.3',
  javaVer: '1.8.0',
  nodeGypVer: null,
  xcodeVer: null,
  xcodeprojGemLocation: null,
  itunesInstalled: true,
  cocoapodVer: null,
  adbVer: 'Android Debug Bridge version 1.0.36',
  androidInstalled: true,
  monoVer: null,
  gitVer: '2.8.2.windows.1',
  gradleVer: null,
  javacVersion: '1.8.0_102' }
Starting watch on killswitch C:\Users\Hisk\AppData\Local\Temp\Hisk\KillSwitches\cli
Analytics statuses:
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track feature 'CLI' with value 'run'.
AnalyticsInstallationID: 90ad88c3-48e2-483d-b4a2-2e37ecb431d5
monitor not started
monitor not started
monitor not started
monitor has started, connecting to http://5752dabccfc54c4ab82aea9626b7338e.monitor-eqatec.com/json.ashx

My apologies if the code is disorganized.

**Comment by tsonevn** [comment]
Hi @HiskDeathnote,
Thank you for your additional info. 
We will investigate further this problem and will research what is causing this strange  behavior. Regarding to that, we will write you back as soon as we have more info about your problem.
Regards,
@tonevn

**Comment by tsonevn** [comment]
Hi @HiskDeathnote,
Excuse me for the delay in replying.

Last week we released new **NativeScirpt** versions - 2.4. Could you try to upgrade to latest **NativeScript** by following the instruction [here](http://docs.nativescript.org/releases/upgrade-instructions) and verify, whether you will have the same problem.

Regards,
@tsonevn

**Comment by HiskDeathnote** [comment]
Hello again,
Thank you very much for your support, Native Script is working correctly
now.
Sincerely,
Hiskias Dingeto
