### ISSUE TITLE
define specific deploy environment variables

### ISSUE THREAD

**Issue by TeddyBo** [NativeScript/NativeScript#3012]
In my project I want to have some environment dependent variables, for example different urls to web services for development and production.
Is there any way to define such values in some `.json` config file or elsewhere and then somehow tell `tns` what environment we are building for?

**Comment by tsonevn** [comment]
Hi @TeddyBo,
Thank you for reporting this issue.
I research your case and found that for your scenario you could use for Android `isDebuggableApp` method, which will return `true` if the app is in Debug mode and `false` if it is in `production`. Unfortunately for iOS there is not easy way to check the app mode. As a workaround you could create your own `JSON` file where to define  the app mode. For further help for the workaround you could review the example below. Regarding to that the `iOS` option could be used also for `Android`

`app/config.json`

```
{
    "isDebug":true
}
```

`main-page.ts`

```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import {isAndroid, isIOS} from "platform";
import {knownFolders, File} from "file-system";

import app = require("application");
declare var com:any;
// Event handler for Page "navigatingTo" event attached in main-page.xml
export function navigatingTo(args: EventData) {
  // Get the event sender
  let page = <Page>args.object;
  if(isAndroid){
    var context = app.android.context;
    var util = com.tns.Util;
    if(util.isDebuggableApp(context)){
      console.log("in debug mode");
    }
    
  }
  if(isIOS){
    var documents = knownFolders.currentApp();
    var jsonFile:File =<File> documents.getFile('config.json');
    var jsonData;
    jsonFile.readText()
    .then(function (content) {
        try {
              jsonData = JSON.parse(content);
              if(jsonData["isDebug"]){
                console.log("in debug mode");
              };
            } 
        catch (err) {
            throw new Error('Could not parse JSON file');
        }
    }, function (error) {
        throw new Error('Could not read JSON file');
    });
  }
  
  page.bindingContext = new HelloWorldModel();
}
```

Hope this helps

**Comment by TeddyBo** [comment]
Hi @tsonevn,

thanks for your reply.
Unfortunately this workaround is not exactly what I'm looking for.
It would be great to have some kind of environment variables like `debug`, `stage` and `prod` and refer them in code:
`if (env.stage) { ... }`
and then set it when `tns` is run:
`tns build android --env stage`

Or at least add the possibility to pass custom attributes to `tns` and access them from code.

**Comment by NathanaelA** [comment]
@TeddyBo - You should be able to use the NS-hooks project to do this.   I know I used it for my AppProtection.net project to be able to detect if I was building for Release or Debug, and then change the execution of code based on that information.

**Comment by stvnmntjy** [comment]
New to `tns` and I would love to see this, as well.

I was told in the `tns` Slack channel that [this](https://github.com/NativeScript/nativescript-cli/blob/2074526e14891b8cc4088fedfb127b723c5182aa/extending-cli.md) (at the time of this post, the latest) is the relevant documentation for hooking into the build **but that it was "old."** Is there other documentation?

Just for testing forensically, I added many `/before-*` and `/after-*` (including `/before-watch`, `/after-watch` and `/watch`) directories under `/hooks`, with this simple node script in each:

```js
module.exports = function ($logger, $projectData, $usbLiveSyncService, hookArgs) {
    "use strict";
    console.log('*** in <the_name_of_the_hook_directory_here> ***');
    return new Promise(function (resolve, reject) {
        resolve();
    });
};
```

I ran them against:

```sh
tns livesync ios --emulator --watch
```

Most hooks did not run. Only (and in this order) ran:

* `before-prepare`
* `after-prepare`
* `before-livesync` (but not `after-livesync`)

... and **none of them reran on source code changes**.

Ideally, with respect to this issue, it would nice if the `tns` API provided access to environment variables. Something like:

```ts
import { vars } from "some_tns_environment_lib";
...
```

... something akin to `process.env.<SOME_VAR>` in node.

As these are strings, the idea is to allow for string substitution in the source code prior to being natively compiled -- if that's possible with `tns` (again, I'm new). So, no platform-specific compilation needed. Just string substitution/interpolation prior to the "build" phase.

Short of that/in the meantime, if someone has a gist or snippet of code out there that works as suggested by @NathanaelA, please share.

Btw, using `nativescript-cli@2.4.2` and a project created by it.

**Comment by markosko** [comment]
Somewhat close to issue and for now it's choosing files based on debug/release  build type but shouldn't be problem set that to env parameter or at worst reading it from package.json from root folder of app
https://www.npmjs.com/package/nativescript-hook-debug-production

**Comment by Cayan** [comment]
I think this relates to: https://github.com/NativeScript/android-runtime/issues/527

**Comment by rhrn** [comment]
Simple set release info to json file
https://github.com/rhrn/nativescript-10hook-release-info

**Comment by martin-mitro** [comment]
Hi, if anyone is still interested, I wrote a blog how to set variables for different environments using CLI hooks. Have a look here: https://blog.davincisoftware.sk/building-a-mobile-nativescript-app

**Comment by Dashue** [comment]
This really needs to become easier than having to write your custom hooks

**Comment by manojdcoder** [comment]
Must be easier with [webpack](https://github.com/NativeScript/nativescript-dev-webpack/issues/160#issuecomment-304092952)

**Comment by urvishagile** [comment]
Hello All 
In my project i want to use environment variable in swift 4.0 and its working fine when we debug through Xcode but i did not get the environment variable value when we open the app without debug mode.
Can you please help us.

Thanks

**Comment by urvishagile** [comment]
Hello All 
In my project i want to use environment variable in swift 4.0 and its working fine when we debug through Xcode but i did not get the environment variable value when we open the app without debug mode.
Can you please help us.

Thanks

**Comment by mjrichards91** [comment]
@manojdcoder Definitely easier with webpack. I used a [different approach](https://github.com/NativeScript/nativescript-dev-webpack/issues/304) using webpack.

**Comment by IRCraziestTaxi** [comment]
It still is not easier to use environments for NativeScript? Very hard to believe. I am using NativeScript with Angular and was disappointed to find out that using `environment.*.ts` as you can in Angular is super complicated to do. I am even fine with not doing it the "Angular way", but it is hard to believe it is not easier than custom hooks, etc.

**Comment by redmagic** [comment]
```
            new webpack.NormalModuleReplacementPlugin(/environment$/, function(resource) {
                resource.request = resource.request.replace(/environment$/, `environment.${env.environment || ''}`);
            }),
```

**Comment by mrpaaske** [comment]
@redmagic could you add some more info to your answer to make it a complete example?

**Comment by AnthonyLenglet** [comment]
> It still is not easier to use environments for NativeScript? Very hard to believe. I am using NativeScript with Angular and was disappointed to find out that using `environment.*.ts` as you can in Angular is super complicated to do. I am even fine with not doing it the "Angular way", but it is hard to believe it is not easier than custom hooks, etc.

This one surprised us too, it could be useful is the `release` flag switched to environment.prod.ts if there was one

**Comment by AnthonyLenglet** [comment]
as an update to this, since NS 7 no longer shows the webpack.config.js to us, the answer is no longer viable

this is what we were using, if there is a way to directly extend the webpack config, that would be the best case scenario, if not, we can probably switch this to a hook then ?

```typescript
new webpack.NormalModuleReplacementPlugin(
  /environment$/,
  function (resource) {
    if (env.environment) {
      resource.request = resource.request.replace(
        /environment$/,
        `environment.${env.environment}`,
      );
    }
  },
),
```

**Comment by rigor789** [comment]
There are multiple ways to support this:
- Via DotEnv files: https://docs.nativescript.org/webpack.html#using-env-files
- Via resolve aliases, for example (pseudo code example):
```js
webpack.chainWebpack(config => {
  config.resolve.alias.set('environment', `environment.${env.environment}`);
})
```

There are likely many other ways to do this, but the above options are generally preferred.
