### ISSUE TITLE
Help with error making a plugin that calls an activity with fragment.

### ISSUE THREAD

**Issue by AresDev** [NativeScript/NativeScript#3017]
I've created a Native Library(aar) from Android Studio, then a NativeScript plugin to navigate an activity inside it, everything works fine, it shows the MainActivity of the Library, but when I navigate from this activity to another that has a fragment, it shows me this error inside the app:

Unhandler Exception java.lang.NoClassDefFoundError: com.xxxx.nameofmypackage.CameraFragment ...

This is how I'm calling the fragment(this fragment is in the same package as the activity) inside my activity:

protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_record);
        if (null == savedInstanceState) {
            getFragmentManager().beginTransaction()
                    .replace(R.id.container, com.nameofmypackage.CameraFragment.newInstance())
                    .commit();
        }
    }

What am I missing? Hope you guys can help me!

**Comment by Pip3r4o** [comment]
This issue was moved to NativeScript/android-runtime#611
