### ISSUE TITLE
Combine .js files

### ISSUE THREAD

**Issue by Alphapage** [NativeScript/NativeScript#302]
Hello,

I tried to combine all .js files to a single bundle.js using this app demo which contains no .xml:
https://github.com/NativeScript/NativeScript/tree/master/apps/absolute-layout-demo

I tried browserify, webpack without success, only gluejs is able to combine to a single app.js, but the debugger crashes each time.
Is it possible to bundle Nativescript app easily ? I tried with only my files and with tns_modules too without success.

Thanks in advance for your help.

**Comment by teobugslayer** [comment]
Related to https://github.com/NativeScript/nativescript-cli/issues/489
