### ISSUE TITLE
The Angular2 sample project doesn't run on Android emulator, runs on iOS simulator

### ISSUE THREAD

**Issue by pritambarhate** [NativeScript/NativeScript#3024]
### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:

CLI: 2.3.0
tns-ios: 2.3.0
tns-android: 2.3.0

### Please tell us how to recreate the issue in as much detail as possible.

I cloned the project from repo. Switched to "angular-start" branch. Added iOS and Android platforms. First started iOS simulator and ran the project on it. It ran successfully. Then started the Android emulator. And tried to run the project using:

`tns run android --emulator`

It prints the following lines:

> Project successfully built
> The system failed to delete the package for an unspecified reason.
> Successfully deployed on device with identifier 'emulator-5554'

But the app doesn't start on the emulator. I looked through the apps on the emulator, the "Groceries" app is not present on it.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

This is same sample code from the example repo, without any change: https://github.com/NativeScript/sample-Groceries.git

**Comment by michelkal** [comment]
I had similar issue. I had to manually start the emulator then run `tns run android` however when I quit with Crtl+C (Command+C) then run `tns livesync android` the app crashes.

**Comment by NickIliev** [comment]
Hey @pritambarhate 

I have tested the angular-start branch on my side with the exact same command and CLI/runtime versions and everything worked as expected.

In your case it seems that the application was successfully built and deployed and still to make sure that you have connected device you can run the following command
```
tns device
```

This should list all connected devices with their current status (e.g.: connected or unreachable)


Moving this to the sample-Grocceries repo

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/sample-Groceries#175
