### ISSUE TITLE
I want to use DotsPageIndicator for android

### ISSUE THREAD

**Issue by alexrainman** [NativeScript/NativeScript#3026]
I want to use DotsPageIndicator for android

https://android.googlesource.com/platform/packages/apps/Settings/+/085028d/src/com/android/settings/widget/DotsPageIndicator.java

Translate it to TS can be tricky.

Any help?

**Comment by Pip3r4o** [comment]
@manijak has done something similar already with PageIndicatorView in his https://github.com/manijak/nativescript-carousel plugin
