### ISSUE TITLE
[Question] Is it possible to observe a CSS or XML property?

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#3029]
I am trying to update a native sublayer view's size whenever a, for instance View.height, is changed. Somehow I need to observe this property (and CSS property) and do something when this gets changed. Is this possible? Specifically this is for iOS, but I wouldn't mind a solution for both.

Thanks!

**Comment by NordlingArt** [comment]
I noticed that View.prototype.onLayout is called whenever the view frame changes. I'll be using this! Or is there a more correct way?

**Comment by enchev** [comment]
Hey @hshristov can you help here?

**Comment by NickIliev** [comment]
Hey, @NordlingArt have you managed to resolve this issue? I will close it due to inactivity, but please let me know if you need further assistance on that one and also please provide some concept code snippet to ease the investigation process.
