### ISSUE TITLE
Selecting an item in ListView remove all background of its children

### ISSUE THREAD

**Issue by duongnhatduy** [NativeScript/NativeScript#303]
![snip20150609_1](https://cloud.githubusercontent.com/assets/6529267/8077912/559a342e-0f62-11e5-9349-5c81a0cf4788.png)
![snip20150609_2](https://cloud.githubusercontent.com/assets/6529267/8077911/559800f0-0f62-11e5-98f8-edfabf511cf1.png)

As you can see in the attachment, when I click on an item, its background and the children's background  all turn gray. Is there anyway to fix this?

**Comment by nsndeck** [comment]
Duplicated with issue #455.
