### ISSUE TITLE
Missing android.Manifest from the typings

### ISSUE THREAD

**Issue by pocesar** [NativeScript/NativeScript#3032]
Although I created the issue in https://github.com/NathanaelA/nativescript-permissions/issues/22, it seems a problem with NS generated typings

### Which platform(s) does your issue occur on?
Android / Typescript

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.3.0
- Cross-platform modules: 2.3.0
- Runtime(s): 2.3.0

### Please tell us how to recreate the issue in as much detail as possible.

`android` declaration on `android17.d.ts` in `tns-platform-declarations` is missing the `android.Manifest` namespaces (and everything else inside it, like `android.Manifest.permission`). 

I think `tns-platform-declarations` should come with `tns-core-modules` if you are using Typescript, by default.  There are no docs stating that `tns-platform-declarations` should be installed and the proper files that should be manually set inside `references.d.ts`

Workaround was to set manually: 

```ts
/// <reference path="./node_modules/tns-core-modules/tns-core-modules.d.ts" /> Needed for autocompletion and compilation.

/// <reference path="./node_modules/tns-platform-declarations/tns-core-modules/android17.d.ts" /> Android
/// <reference path="./node_modules/tns-platform-declarations/tns-core-modules/org.nativescript.widgets.d.ts" />

declare module android {
  export module Manifest {
    export var permission: any
  }
}
```

**Comment by NickIliev** [comment]
Hey @pocesar there is a [README in the tns-platform-declarations source](https://github.com/NativeScript/NativeScript/blob/master/tns-platform-declarations/README.md).
Note that the this readme applies for the modules and declarations in master so you should either install it with @next or wait for the next release.

As all plugins it will require to install it via npm with
`npm i tns-platform-declarations`

Closing this as duplicate to [https://github.com/NativeScript/NativeScript/issues/3033](https://github.com/NativeScript/NativeScript/issues/3033)
