### ISSUE TITLE
Enable WebPack by default in Release mode

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#3039]
WebPack reduces the size of the app and also the loading time. There is not reason why not enable it by default for release mode.

For 2.4
 - enable it for iOS apps

For 2.5
 - enable it for Android apps together with the V8 snapshots

**Comment by anuragd7** [comment]
Hi
Without webpack the startup time of nativescript angular apps is too long going upto 35 seconds on some devices. We need better support for webpack to produce production apps.

**Comment by TheLarkInn** [comment]
Hi!!! Sean Larkin from [webpack](https://GitHub.com/webpack).

Is this something specific I can advise on? (DLL? ETC?)

**Comment by anuragd7** [comment]
Hi Sean!
Thanks for writing. I have a nativescript angular app that is pretty much ready for release, however I am facing one big issue - The startup time for the app is just too long, as much as 35 seconds on some android devices and 15 seconds or so on newer devices. I implemented lazyloading of routes but it had negligible impact on the startup time.

I take it that one important way to bring down that startup time is to use webpack, however after spending hours and hours on trying to use the nativescript-dev-webpack plugin I just cant get it to work for my project!!

I have posted the details of the issue in the [nativescript-dev-webpack repo here.](https://github.com/NativeScript/nativescript-dev-webpack/issues/274)  

Do let me know if you need any more information. Would be great to get any advice on how I can fix this. Thanks again.

**Comment by NickIliev** [comment]
Webpack is now enabled by default for both release and debug modes.
