### ISSUE TITLE
CSS import does't work.

### ISSUE THREAD

**Issue by montella1507** [NativeScript/NativeScript#3041]
Hello,

nothing is working>

`@import { url('res://foo.css') }
@import { url('~/foo.css') }`

with file /app/foo.css
or.. 
`@import url("~/foo.css");`

with file 
/app/foo.android.css

I have it as the first line.

**Comment by devna13** [comment]
I'm using sass and imports works

  "devDependencies": {

    "nativescript-dev-sass": "^0.1.0",

  }

 @import "./_common.scss";

**Comment by montella1507** [comment]
Well i would try it, but the main idea was to split code for each platform ->  foo.android.css and foo.ios.css  (import url("~/foo.css")) 

http://docs.nativescript.org/angular/tutorial/ng-chapter-2#25-global-css

**Comment by wnas** [comment]
In my opinion this is what you do in the TypeScript

```
styleUrls: ['./foo.common.css',
                './foo.component.css']
```

where you provide a `foo.component.ios.css` and a `foo.component.android.css`. So I won't do it in the css import...

**Comment by NickIliev** [comment]
Hey @montella1507 

Here is a [working exampl](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/app.css#L1)e on how to use import in NativeScript application.
```
@import '~/css/core.light.css';
```
Meanwhile, notice the platform specific CSS files in the folder [css](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/css)

**Comment by montella1507** [comment]
@NickIliev  

Hello, thank you for your answer!

So the platform specific styles (or all files?)   must be in a subfolder to works correctly? 

So there is a mistake in the official documentation then.

**Comment by NickIliev** [comment]
@montella1507 no need to explicitly set subfolder.
What i meant is that you can use platform specific files like
```
core.light.android.css
core.light.ios.css
``

and then import the base name without the platform part like 
``
@import '~/css/core.light.css';
// or
@import url('~/css/core.light.css');
``

Indeed the syntax is the documenation has intrudoced some additional brackets which is non-working variant. Thank you for reporting that docs bug! We have already fixed the articles with[ this PR](https://github.com/NativeScript/docs/pull/557#pullrequestreview-7621438).

**Comment by cielocoderep** [comment]
im having this problem, im actually following the grocery tutorial, https://docs.nativescript.org/tutorial/chapter-2, importing css to app.css, it doesnt do anything. All styles on the imported css doesnt take effect.
