### ISSUE TITLE
Question:  how can i convert {N} File object to javascript File or Blob. And upload XMLHttpRequest

### ISSUE THREAD

**Issue by matart15** [NativeScript/NativeScript#3043]
I tried to upload files with `background-http` plugin. I managed to upload single file in every request. But my backend wants one POST request which contains video and image together. 

Turns out I don’t have privilege to fix backend. zipping files into one requires backend fix as well.

I tried using `XMLHttpRequest` with in background via `nativescript-batch` plugin. background part and sending POST request parts work. code is here
```
private postFileUpload(url, fileName: string, localPath: string) {
    let date = moment().utc();

    let xhr = new XMLHttpRequest();
    xhr.open("POST", url);
    // xhr.setRequestHeader("Content-Type", "multipart/form-data");

    let file = fs.File.fromPath(localPath);

    var formData = new FormData();
    //let payload = file.readSync(error => console.log(error));
    // This fails because file is not recognized as file so added as toString()
    formData.append("post_image", file, fileName);  // file or payload
    formData.append("title", "asdfasdfasdf");

    console.log(JSON.stringify(xhr), url);
    xhr.onload = () => {
      console.log("Response Text", xhr.responseText);
      console.log("XHR: ", JSON.stringify(xhr));
      if (xhr.status === 200) {
        console.log('Uploaded!');
      }
    };
    xhr.onprogress = () => {
      console.log("Progress!");
    }
    xhr.onerror = (error) => {
      console.log("Could not upload file: " + error);
    };

    xhr.send(formData);
  }
```

problem is in backend post_image is string.
```
"post_image":"[object Object]","title":”asdfasdfasdf”
```

how can i convert {N} File objeect to javascript File or Blob

**Comment by NickIliev** [comment]
Hey, @matart15 I think you can take a look at this comment [here](http://stackoverflow.com/a/6212497/4936697). As you do not have access to the backend what you need to do is not to provide stringified JSON but a plain object.

**Comment by matart15** [comment]
Thank you. I will try that

**Comment by giscafer** [comment]
how to get SelectedAsset (select image) localPath?
