### ISSUE TITLE
CFBundleIdentifier Collision publishing ios

### ISSUE THREAD

**Issue by NNieto** [NativeScript/NativeScript#3046]
ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'org.nativescript.TNSWidgets' under the iOS application 'Wos.app'."

**Comment by NickIliev** [comment]
Hey @NNieto 

The system error you are receiving suggests that your project has a duplicate identifier with the shown value in your platforms folder. However, the reason for that to happen is unknown without some more information. The best case scenario is if you can provide your application in order to test it locally and research what is causing your application to refer to TNSWidgets twice.
If, that is not a possible solution, you can provide us with your application environment in order to recreate a similar application at our side. For that we will need the following:

- node.js version
- xCode version
- OS version
- NativeScript CLI version
- tns-core-modules version
and your whole package.json (from the root directory) to recreate an app will your exact same dependencies.

**Comment by NNieto** [comment]
Thanks for reply, my information is:
Node JS: 6.5.0
xCode: 8.1
OS version: OSX El Capitan 10.11.6
Nativescript CLI version: 2.3.0
tns-core-modules version: 2.3.0

I include in the podfile the FBSDKShareKit too
package.json:
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.highlevel.wos",
    "tns-android": {
      "version": "2.3.0"
    },
    "tns-ios": {
      "version": "2.3.0"
    }
  },
  "dependencies": {
    "nativescript-effects": "^0.3.0",
    "nativescript-image-cache-it": "^1.5.1",
    "nativescript-insomnia": "^1.2.0",
    "nativescript-loading-indicator": "^2.1.0",
    "nativescript-platform-css": "^1.0.1",
    "nativescript-plugin-firebase": "^3.6.2",
    "nativescript-screen-orientation": "^1.0.2",
    "nativescript-slides": "^2.1.4",
    "nativescript-sound": "^1.0.4",
    "nativescript-videoplayer": "^1.0.3",
    "nativescript-web-image-cache": "^2.0.1",
    "tns-core-modules": "^2.3.0"
  },
  "devDependencies": {
    "babel-traverse": "6.14.0",
    "babel-types": "6.14.0",
    "babylon": "6.9.1",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^1.8.10"
  }
}

**Comment by NNieto** [comment]
ERROR ITMS-90680: "The binary you uploaded was invalid." Also I get this error too, and another related with the architecture but I fixed using a script, maybe this is important to say. Thanks

**Comment by NickIliev** [comment]
Hey @NNieto 
Are you using `[tns publish](http://docs.nativescript.org/publishing/publishing-ios-apps) `command to generate your package?

**Comment by NNieto** [comment]
Yes @Nicklliev, I am using the two commands and get the same result.

`tns publish ios` 
`tns publish ios AppleAccount ApplePass`

**Comment by NickIliev** [comment]
Hey @NNieto 

We've investigated the problem and it seems that the reason to have a duplicate identifier of kind TNSWidgest is caused by the plugin **nativescript-slides**.
The plugin is referring in its [package.json](https://github.com/TheOriginalJosh/nativescript-slides/blob/master/package.json#L77) devDependency to tns-core-modules: next and in the same time referring to 2.3.0 for nativeScript so this is the reason both versions are used by the plugin (from where duplicate files are produced in your build files). 

I have logged this problem at [the plugin repository](https://github.com/TheOriginalJosh/nativescript-slides/issues/81) and the best solution is the author of the plugin to fix it and publish a new version in npm.

Another possible and fastest solution is to fix the plugin locally at your side and use it to build your application. To do that follow these steps:
- Fork the plugin repo.
- fix the package.json [so that this line ](https://github.com/TheOriginalJosh/nativescript-slides/blob/master/package.json#L77)should be either pointing to 2.3.0 or not exists at all
- run `npm pack` to create your local version of the plugin in the tgz file
- in your application run
```
tns plugin remove nativescript-slides
tns plugin add path-to-tgz-file
```
- run the publish command again (with deleted platforms folder)
```
tns publish ios AppleUser ApplePass
```

The third variant for a solution - wait for our next release where similar inconveniences with npm 3.x should be fixed. The next release is expected within few days.

**Comment by NNieto** [comment]
Great!!, Thank you so much @NickIliev, I will try to fix the problem locally.

**Comment by NNieto** [comment]
@NickIliev it works!!! Thanks, I will close the issue

**Comment by 3rror404** [comment]
Hi @NickIliev, I seem to be experiencing the same issue.

I've checked all of the plugins that I'm using and the only one that references a `next` build is `tns-core-modules` ([here](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/package.json#L27)).

Have you any idea what might be causing this?

Thanks

```
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 2.4.2           │ 2.4.2          │ Up to date  │
│ tns-core-modules │ 2.4.3           │ 2.4.3          │ Up to date  │
│ tns-android      │ 2.4.1           │ 2.4.1          │ Up to date  │
│ tns-ios          │ 2.4.0           │ 2.4.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

```
{
  "description": "*****",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "*****",
  "repository": {
    "type": "git",
    "url": "*****"
  },
  "nativescript": {
    "id": "*****",
    "tns-android": {
      "version": "2.4.1"
    },
    "tns-ios": {
      "version": "2.4.0"
    }
  },
  "dependencies": {
    "html-entities": "^1.2.0",
    "moment": "^2.14.1",
    "nativescript-background-fetch": "^1.0.3",
    "nativescript-background-geolocation-lt": "^1.3.3",
    "nativescript-background-http": "^2.4.0",
    "nativescript-camera": "0.0.8",
    "nativescript-fonticon": "^1.1.1",
    "nativescript-google-maps-sdk": "^1.4.2",
    "nativescript-iqkeyboardmanager": "^1.0.1",
    "nativescript-pulltorefresh": "^1.1.9",
    "nativescript-statusbar": "^1.0.0",
    "tns-core-modules": "^2.4.3",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "babel-traverse": "6.16.0",
    "babel-types": "6.16.0",
    "babylon": "6.11.4",
    "filewalker": "0.1.2",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.0",
    "typescript": "^2.0.3"
  }
}
```

**Comment by NickIliev** [comment]
Hey, @3rror404  I will try to reproduce your issue with the provided package.json but first I've noticed that you have referenced a file that is from the master branch of tns-core-modules and the same file in the release branch is referencing not next but the version as expected.
[Here](https://github.com/NativeScript/NativeScript/blob/release/tns-core-modules/package.json#L27) is the link to the same line in the release branch

Are you sure you have published your application with the official latest version of tns-core-modules and not with the **_next_**

**Comment by 3rror404** [comment]
Whoops, yes that was a mistake. I am actually using the release branch. I just linked to the wrong one above. 

Thanks for taking a look.

**Comment by NickIliev** [comment]
HeyB @3rror404 on second thought which error you are hitting!?
Is it ERROR ITMS-90680 or ERROR ITMS-90685 (as the previous use has mentioned both errors in the issue).
Also, how are you publishing you app (via Xcode or via `tns publish` command) ?

**Comment by 3rror404** [comment]
I'm using xcode. I have been having lots of issue building for release (https://github.com/NativeScript/nativescript-cli/issues/2339#issuecomment-268209258). I've finally got an archive to build but I get both of the errors mentioned as well as some others. I'm in the middle of updating xcode from 8.2 to 8.2.1 ("installing - less than a minute" for 45 minutes!) so I can't check the exact errors at the moment.

**Comment by NickIliev** [comment]
@3rror404 from the list of errors I am guessing that in fact some of your plugins are duplicating the TNSWidgets and you are hitting the same error as NNileto had. It might be the background-http plugin in which I saw a dependency to tns-core-modules: next and at the same time using CLI 2.4.0 but to be sure what exactly is causing the CFBundleIdentifier collision (and most likely the linked errors 90680 and other errors). To do that generate your release build and see if you have doubled **_org.nativescript.TNSWidgets_** generated.

As a possible solution for these errors try the following steps:

- clone the repo of [nativescript-background-http plugin](https://github.com/NativeScript/nativescript-background-http/) (or the plugin that is generating the doubled identifier if it is not this one)
- open package.json of the plugin 
- change [these two lines](https://github.com/NativeScript/nativescript-background-http/blob/master/nativescript-background-http/package.json#L26-L29) so they are not requiring next but the latest version 
- remove platforms folder and node_modules
- run `npm install` and `tsc` 
- and finally `npm pack`

Now you will have generated tgz file for the plugin. 
**Or alternativel**y you can try my generated tgz from [here](https://drive.google.com/open?id=0B05aPIW_j-XFU3FnbXFzeUJTUnM)
 - In your project reference the file as dependency in your package.json
"nativescript-background-http": "file:./nativescript-background-http-2.4.0.tgz",
- remove platforms folder and then run `tns publish ios` (you w8ill be prompted for your AppleId and Apple pass)

**Comment by 3rror404** [comment]
That looks to have worked. Thanks for your help @NickIliev !

**Comment by mounirka** [comment]
Hi @NickIliev i have the same problem ERROR ITMS-90685. I don't know which package cause the collision. My system informations are the same of NNieto.
My package.json is this:
```
{
  "description": "Application",
  "readme": "Application",
  "nativescript": {
    "id": "org.nativescript.application",
    "tns-android": {
      "version": "2.4.1"
    },
    "tns-ios": {
      "version": "2.3.0"
    }
  },
  "dependencies": {
    "nativescript-facebook-login": "^0.2.0",
    "nativescript-geolocation": "0.0.15",
    "nativescript-imagecropper": "0.0.7",
    "nativescript-imagepicker": "^2.4.1",
    "nativescript-loading-indicator": "^2.2.1",
    "nativescript-pulltorefresh": "^1.1.8",
    "nativescript-toast": "^1.4.0",
    "tns-core-modules": "^2.4.2"
  },
  "devDependencies": {
    "babel-traverse": "6.18.0",
    "babel-types": "6.18.0",
    "babylon": "6.13.1",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^2.0.9"
  }
}
```
Thank you so much for your help.

**Comment by NNieto** [comment]
@mounirka the problem is the tns-platform declarations, using next, it duplicates the TNSWidgets, follow the steps posted by @NickIliev the problem is solved, I did it for two libraries that have the same problem.

**Comment by mounirka** [comment]
Now it gives me this exact two problems:

- CFBundleIdintifier Collision. There is more than one bundle with the CFBundleIdentifier value 'Telerik.TelerikAppFeedback' under the ios application 'Application.app'
- CFBundleIdintifier Collision. There is more than one bundle with the CFBundleIdentifier value 'Telerik.TelerikUI' under the ios application 'Application.app'

I can't find the telerikAppFeedback in my project, neither the TelerikUI.
Can someone help? Thank you
