### ISSUE TITLE
AWS SDK support on NativeScript

### ISSUE THREAD

**Issue by vbudilov** [NativeScript/NativeScript#3048]
Hello!

I've tried using the aws-sdk npm package in NativeScript and running into a dependency issue - it's failing at crypto. 

Are there any plans to support it? I'm using Ionic2 for this particular reason, but hopefully there's a way to get around these issues. AWS is huge, and not being able to use it's javascript library "out of the box" (without creating my own client and signing every request) is a huge stumbling block for quite a few of us. 

Thanks in advance!
Vladimir

**Comment by dexterque** [comment]
:hamster:

**Comment by NickIliev** [comment]
Hey @vbudilov 

As of this very moment, NativeScript does not support the **crypto** module.
Working on a polyfill for the crypto is scheduled as a feature but is not a priority right now. You can track[ this issue](https://github.com/NativeScript/NativeScript/issues/195) for comments on that matter.

You can also try a different approach and instead rely on **crypto** you can see where the module is used and substitute its use with **crypto-js** which is supported in NativeScript environment (as suggested [here](http://stackoverflow.com/a/36836890/4936697))

Or, in the corner case where you need to upload files to S3, you can try[ this manual solution](http://stackoverflow.com/questions/37581693/nativescript-background-http-file-uploading-to-s3/38174135#38174135) suggested by @ignaciolarranaga

**Comment by vbudilov** [comment]
Hi @NickIliev , 

Thanks for getting back to me. Unfortunately that's not really an option -- rewriting all of the apis (not just S3) is just too time consuming, and "recompiling" the aws javascript sdk is way too much effort, since code changes happen almost weekly. 

Also, the referenced issue has a "Crypto would be great!" comment, that was upvoted 11 times  ;)

I guess I'll have to write the AWS logic on the backend for now. 

Thanks again -- NativeScript is a really cool framework.

**Comment by simplicii** [comment]
+1
