### ISSUE TITLE
Improve android layout performance by reducing marshalling calls

### ISSUE THREAD

**Issue by hshristov** [NativeScript/NativeScript#305]
Rewrite android layouts in Java so that transition between Java and JavaScript are not needed for layout. This will increase application performance by reducing marshaling.

**Comment by RangerMauve** [comment]
Will it still be possible to implement a UI with Nativescript with pure JS when this feature is implemented?

**Comment by valentinstoychev** [comment]
Yes - this will be a transparent change, no API will be touched, just the implementation below will be changed.

**Comment by RangerMauve** [comment]
Cool. Thanks for the clarification.

**Comment by hshristov** [comment]
@RangerMauve What do you mean with - "Will it still be possible to implement a UI..."?

**Comment by RangerMauve** [comment]
Like, if it will be possible to use the native APIs for building up the UI rather than the ViewModel abstraction you guys have made.

**Comment by hshristov** [comment]
Yes you will be able to use native APIs to build UI. Even better when our layouts are implemented as native library you will be able to use them directly.

**Comment by RangerMauve** [comment]
Awesome, can't wait to see what it looks like. :D
