### ISSUE TITLE
NSLayoutConstraint with VisualFormat not working

### ISSUE THREAD

**Issue by alexrainman** [NativeScript/NativeScript#3052]
Trying to add a UIPageControl programmatically with this code:

```
var viewsDictionary = NSDictionary.dictionaryWithObjectForKey(this._pageControl, "pageControl");

this._ios.addConstraints(NSLayoutConstraint.constraintsWithVisualFormatOptionsMetricsViews("H:|[pageControl]|", NSLayoutFormatOptions.NSLayoutFormatAlignAllCenterX, <any>[], viewsDictionary));

this._ios.addConstraints(NSLayoutConstraint.constraintsWithVisualFormatOptionsMetricsViews("V:[pageControl]|", 0, <any>[], viewsDictionary));
```

But the UIPageControl doesn't goes to bottom as expected, instead is at the top half hidden behind navigation bar.

Any ideas?

**Comment by alexrainman** [comment]
I need this or any other way to apply constraints to a view so i can keep it at the bottom but resizable when screen rotates.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/ios-runtime#694
