### ISSUE TITLE
ListView, SegmentedBar separatorColor - allow adjustment via CSS

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/NativeScript#3056]
Allow `separator-color: #3489db;` to be set via CSS for `ListView`, `SegmentedBar`, etc.

Need styler added --
https://github.com/NativeScript/NativeScript/blob/4b94fe8c631617bf3f056eddbff4871a23a16678/tns-core-modules/ui/list-view/list-view.ios.ts#L195-L209

/cc @bradmartin @tjvantoll

**Comment by bradmartin** [comment]
Would be great to see all view components with specific properties for styling to be set in CSS. I've tried `separatorColor` for the listview with no luck, and `selectedBackgroundColor` for the segmented bar. I believe the TabView specific properties worked at one time, TJ enlightened me months ago so maybe it's broken right now. I've only tested on 2.3.

**Comment by zh-m** [comment]
Hi @NathanWalker, @bradmartin, 

Setting separtorColor of ListView in CSS will be available with the merge of the PR of [separatorColor property of ListView can be set in CSS](https://github.com/NativeScript/NativeScript/pull/3233)

**Comment by shiv19** [comment]
@bradmartin, separatorColor on listView is now working. I think this issue can be closed.

**Comment by NickIliev** [comment]
Closing as implemented
