### ISSUE TITLE
iOS10 Speech Recognition

### ISSUE THREAD

**Issue by gsaadeh** [NativeScript/NativeScript#3065]
I've been trying to implement an iOS10 Speech Recognition demo app following the sample code [here](https://github.com/shu223/iOS-10-Sampler/blob/master/iOS-10-Sampler/Samples/SpeechRecognitionViewController.swift) but I was unsuccessful. 

The following code is throwing an exception:

```    
let speechRecognizer = new SFSpeechRecognizer();
....
let recognitionRequest = new SFSpeechAudioBufferRecognitionRequest();
....
let recognitionTask = speechRecognizer.recognitionTask(recognitionRequest, function(result, error) {
        let isFinal = false;

        if (result) {
            model.set('speechText', result.bestTranscription.formattedString);
            isFinal = result ? result.isFinal : false;
        }

        if (error || isFinal) {
            audioEngine.stop();
            inputNode.removeTap(0);

            recognitionRequest = null;
            recognitionTask = null;

            model.set('recordButtonEnabled', true);
        }
```
And the exception is:

speechRecognizer.recognitionTask is not a function. (In 'speechRecognizer.recognitionTask', 'speech Recognizer.recognitionTask' is undefined)

### Which platform(s) does your issue occur on?
Tested on both iOS 10.0 and 10.1 (simulator and device)

### More Info:
- CLI: 2.3.0
- Cross-platform modules: ^2.5.0-2016-11-02-4652
- Runtime(s): 2.3.0

What am I missing?

**Comment by NickIliev** [comment]
You are using next modules with latest CLI and runtimes. Try updating all.

```
npm uninstall nativescript -g
npm install nativescript@next -g

cd myApp
npm install tns-core-modules@next
tns platform add ios@next
tns run ios
```

**Comment by NickIliev** [comment]
Hey @gsaadeh were you able to resolve your issue with the suggested steps!?
Please let us know if you need further assistance on that matter!

**Comment by gsaadeh** [comment]
Hi @NickIliev, sorry for the late response but I am not sure why I didn't get notifications for this thread. I tried installing the next modules and I am still seeing the same error. Previously I had attempted to use the Objective C api and It didn't seem to work either. I will test it some more today and let you know if I get any luck.

<img width="640" alt="screen shot 2016-11-18 at 1 32 02 am" src="https://cloud.githubusercontent.com/assets/3935786/20425302/e53351a4-ad2e-11e6-9e3d-7f3b66a4dbdc.png">

**Comment by NickIliev** [comment]
Use the [Objective-C API](https://developer.apple.com/reference/speech/sfspeechrecognizer?language=objc) and s a reference on how to initialize you can see the typescript declarations [here](https://github.com/NativeScript/NativeScript/blob/master/tns-platform-declarations/ios/objc-i386/objc!Speech.d.ts) using [the rules](http://uatdocs.nativescript.org/runtimes/ios/getting-started/HelloWorld) in the iOS runtime references

**Comment by gsaadeh** [comment]
Awesome thanks @NickIliev, I will try it and report back to you. Cheers

**Comment by gsaadeh** [comment]
I was able to get past the error by using the latest version of `tns modules` and replacing the swift code with objective C. I am now getting an error with `audioEngine.start()` function. I will report as soon as I find what the solution is. 

Thanks for your help @NickIliev

**Comment by NickIliev** [comment]
Hey @gsaadeh I will close this issue as resolved but let me know if you need further assistance.
