### ISSUE TITLE
Sample project with webpack does not work

### ISSUE THREAD

**Issue by ignaciolarranaga** [NativeScript/NativeScript#3066]
### Tell us about the problem
A sample app with webpack does not work:
```
Nov 10 19:31:10 MacBook-Pro-de-Ignacio Sample[6126]: assertion failed: 16B2555 13B143: libxpc.dylib + 58126 [0F47719F-3076-3664-A64B-CEB6901B254D]: 0x7d
Nov 10 19:31:10 MacBook-Pro-de-Ignacio Sample[6126]: 1   0x10f4ee379 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
Nov 10 19:31:10 MacBook-Pro-de-Ignacio Sample[6126]: 2   0x10fb5b51e ffi_closure_unix64_inner
Nov 10 19:31:10 MacBook-Pro-de-Ignacio Sample[6126]: 3   0x10fb5bed2 ffi_closure_unix64
Nov 10 19:31:10 MacBook-Pro-de-Ignacio Sample[6126]: 4   0x110476013 -[UIViewController view]
Nov 10 19:31:10 MacBook-Pro-de-Ignacio Sample[6126]: 5   0x11034f51c -[UIWindow addRootViewControllerViewIfPossible]
Nov 10 19:31:10 MacBook-Pro-de-Ignacio Sample[6126]: 6   0x11034fc05 -[UIWindow _setHidden:forced:]
Nov 10 19:31:10 MacBook-Pro-de-Ignacio Sample[6126]: 7   0x1103614a5 -[UIWindow makeKeyAndVisible]
Nov 10 19:31:10 MacBook-Pro-de-Ignacio Sample[6126]: 8   0x10fb5bd2d ffi_call_unix64
Nov 10 19:31:10 MacBook-Pro-de-Ignacio Sample[6126]: 9   0x11cfb15d0
Nov 10 19:31:10 MacBook-Pro-de-Ignacio Sample[6126]: file:///app/main-view-model.js:1:95: JS ERROR Error: Could not find module 'data/observable'. Computed path '/Users/ignacio/Library/Developer/CoreSimulator/Devices/00A4117D-42D7-4D34-A741-4D4FAA4286CD/data/Containers/Bundle/Application/17E2A240-931E-44D3-B1B1-16642BB7EDA3/Sample.app/app/tns_modules/data/observable'.
Nov 10 19:31:10 MacBook-Pro-de-Ignacio com.apple.CoreSimulator.SimDevice.00A4117D-42D7-4D34-A741-4D4FAA4286CD.launchd_sim[1769] (UIKitApplication:org.nativescript.Sample[0x21fb][6126]): Service exited due to signal: Segmentation fault: 11
```

### Which platform(s) does your issue occur on?
Verified on iOS emulator

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.3.0
- Cross-platform modules: 2.3.0
- Runtime(s): tns-ios 2.3.0
- Plugin(s): none

### Please tell us how to recreate the issue in as much detail as possible.
Just create a sample project and try to run it with WebPack:
```
tns create Sample
cd Sample
tns install webpack
tns run ios --bundle
```

**Comment by NathanaelA** [comment]
Check out https://github.com/NativeScript/NativeScript-dev-webpack and the issues there.  There are a LOT of issues with WebPack right now.

**Comment by ignaciolarranaga** [comment]
Thanks @NathanaelA, I'm actually using it on the Angular projects (because the size if not of a single project is too high), but just found this when trying to fix the https://github.com/NativeScript/nativescript-imagepicker at least to work on the angular projects with webpack. I'll replace the xml views with JS implementations through createPage, I think it might work.

**Comment by NathanaelA** [comment]
@ignaciolarranaga -- I was trying All the issues for WebPack are over in that repo.   I've listed several myself and they have to do with both Angular and non-Angular projects.   Some of those issues have fixes you can use...  :grinning:    And you don't have to replace the view; you just have to register the view.

**Comment by ignaciolarranaga** [comment]
@NathanaelA I did register the view for example with this code:

if (global.TNS_WEBPACK) {
    require("globals");
    global.registerModule("tns_modules/nativescript-imagepicker/images", () => require("./images.ios.js"));
}

But this only register the JS, it does not work because the frame-common#pageFromBuilder() does not recognized it (it means, it found the JS but can not create the view),
I even tried to register the xml and place it on the webpack file, with no luck, but I was using the last released version. It might be something new with the dev code of  https://github.com/NativeScript/NativeScript-dev-webpack ?

**Comment by NathanaelA** [comment]
Try:

```
if (global.TNS_WEBPACK) {
    global.registerModule("nativescript-imagepicker/images", () => require("nativescript-imagepicker/images"));
}
```

**Comment by ignaciolarranaga** [comment]
I'm afraid the same that before: `Error: Failed to load Page from entry.moduleName: tns_modules/nativescript-imagepicker/albums`

I guess the problem is that the tns_modules are cleared and there is no place where to find albums.xml, I'm trying with 2.3.0 by the way (is there some difference in 2.4.0?, I tried compiling the release branch, but problems with dependencies :()

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-dev-webpack#29
