### ISSUE TITLE
CSS Border Shorthand Property

### ISSUE THREAD

**Issue by hamorphis** [NativeScript/NativeScript#3068]
```
Label 
{
    border: 5px solid red;
}
```
- The `px` can be omitted from the first value, since currently only pixels are supported.
- Currently only `solid` borders are supported. The second value will be ignored until support for non-solid borders is introduced.

**Comment by tillsanders** [comment]
Hey, out of curiosity: why has this never been implemented? Is this a won't-fix? 🤔
