### ISSUE TITLE
Can't run build apk in an external emulator. Displaying the error code:

### ISSUE THREAD

**Issue by HiskDeathnote** [NativeScript/NativeScript#3076]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

**Comment by HiskDeathnote** [comment]
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to resume activity {org.nativescript.Kelal/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreateView failed

TypeError: Cannot read property 'LayoutParams' of undefined
File: "/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/view.js, line: 507, column: 68

StackTrace: 
	Frame: function:'ViewStyler.setNativeLayoutParamsProperty', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/view.js', line: 507, column: 69
	Frame: function:'StylePropertyChangedHandler.applyProperty', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/styling/style.js', line: 1326, column: 14
	Frame: function:'Style._applyStyleProperty', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/styling/style.js', line: 1086, column: 25
	Frame: function:'Style._applyProperty', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/styling/style.js', line: 1049, column: 14
	Frame: function:'Style._onPropertyChanged', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/styling/style.js', line: 1030, column: 14
	Frame: function:'DependencyObservable._setValueInternal', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/dependency-observable.js', line: 307, column: 18
	Frame: function:'DependencyObservable._setValue', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/dependency-observable.js', line: 133, column: 14
	Frame: function:'onLayoutParamsChanged', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/styling/style.js', line: 130, column: 11
	Frame: function:'DependencyObservable._onPropertyChanged', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/dependency-observable.js', line: 213, column: 13
	Frame: function:'Style._onPropertyChanged', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/styling/style.js', line: 1028, column: 45
	Frame: function:'DependencyObservable._setValueInternal', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/dependency-observable.js', line: 307, column: 18
	Frame: function:'DependencyObservable._setValue', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/dependency-observable.js', line: 133, column: 14
	Frame: function:'set', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/styling/style.js', line: 856, column: 18
	Frame: function:'set', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/view-common.js', line: 527, column: 42
	Frame: function:'Page._addViewToNativeVisualTree', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/page/page.js', line: 102, column: 41
	Frame: function:'eachChild', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/view.js', line: 160, column: 61
	Frame: function:'Page._eachChildView', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/page/page-common.js', line: 286, column: 9
	Frame: function:'View._onAttached', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/view.js', line: 165, column: 18
	Frame: function:'View._addViewCore', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/view.js', line: 126, column: 18
	Frame: function:'View._addView', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/view-common.js', line: 1163, column: 14
	Frame: function:'onFragmentShown', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/frame/frame.js', line: 40, column: 11
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/frame/frame.js', line: 612, column: 13
	Frame: function:'FragmentClass.onCreateView', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/frame/fragment.js', line: 23, column: 38


	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2788)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2817)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
	at android.app.ActivityThread.access$800(ActivityThread.java:135)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5021)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreateView failed

TypeError: Cannot read property 'LayoutParams' of undefined
File: "/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/view.js, line: 507, column: 68

StackTrace: 
	Frame: function:'ViewStyler.setNativeLayoutParamsProperty', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/view.js', line: 507, column: 69
	Frame: function:'StylePropertyChangedHandler.applyProperty', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/styling/style.js', line: 1326, column: 14
	Frame: function:'Style._applyStyleProperty', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/styling/style.js', line: 1086, column: 25
	Frame: function:'Style._applyProperty', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/styling/style.js', line: 1049, column: 14
	Frame: function:'Style._onPropertyChanged', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/styling/style.js', line: 1030, column: 14
	Frame: function:'DependencyObservable._setValueInternal', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/dependency-observable.js', line: 307, column: 18
	Frame: function:'DependencyObservable._setValue', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/dependency-observable.js', line: 133, column: 14
	Frame: function:'onLayoutParamsChanged', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/styling/style.js', line: 130, column: 11
	Frame: function:'DependencyObservable._onPropertyChanged', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/dependency-observable.js', line: 213, column: 13
	Frame: function:'Style._onPropertyChanged', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/styling/style.js', line: 1028, column: 45
	Frame: function:'DependencyObservable._setValueInternal', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/dependency-observable.js', line: 307, column: 18
	Frame: function:'DependencyObservable._setValue', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/dependency-observable.js', line: 133, column: 14
	Frame: function:'set', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/styling/style.js', line: 856, column: 18
	Frame: function:'set', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/view-common.js', line: 527, column: 42
	Frame: function:'Page._addViewToNativeVisualTree', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/page/page.js', line: 102, column: 41
	Frame: function:'eachChild', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/view.js', line: 160, column: 61
	Frame: function:'Page._eachChildView', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/page/page-common.js', line: 286, column: 9
	Frame: function:'View._onAttached', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/view.js', line: 165, column: 18
	Frame: function:'View._addViewCore', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/view.js', line: 126, column: 18
	Frame: function:'View._addView', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/core/view-common.js', line: 1163, column: 14
	Frame: function:'onFragmentShown', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/frame/frame.js', line: 40, column: 11
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/frame/frame.js', line: 612, column: 13
	Frame: function:'FragmentClass.onCreateView', file:'/data/data/org.nativescript.Kelal/files/app/tns_modules/ui/frame/fragment.js', line: 23, column: 38


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
	at com.tns.Runtime.callJSMethod(Runtime.java:895)
	at com.tns.Runtime.callJSMethod(Runtime.java:879)
	at com.tns.Runtime.callJSMethod(Runtime.java:871)
	at com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
	at android.app.Fragment.performCreateView(Fragment.java:1700)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
	at android.app.BackStackRecord.run(BackStackRecord.java:684)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
	at android.app.Activity.performResume(Activity.java:5321)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2778)
	... 12 more

**Comment by Pip3r4o** [comment]
@HiskDeathnote We'd be grateful if you could provide all the requested information.

What is the NativeScript package version (CLI)? 
tns-core-modules version? 
What about the tns-core-modules-widgets?

You could try removing the `node_modules` and `platforms/android` dirs, and installing the latest modules and platform, see if that can help you move on

Also, the problem does not appear to be the external emulator. As a matter of fact, it should not matter whether you deploy the APK on a physical device, or an emulator, be it on your machine or someone else's.
