### ISSUE TITLE
Unable to use $parents property in xml loaded with builder

### ISSUE THREAD

**Issue by alexrainman** [NativeScript/NativeScript#3077]
I am loading a view with builder, getting the native representation and adding it to a native view programmatically (Android ViewPager and iOS UIPageViewController) but this doesn't work:

```
<Label text="{{ $parents['CarouselView'].position, $parents['CarouselView'].position }}" />
```

Any ideas?

**Comment by NickIliev** [comment]
Hey @alexrainman I have tested the parent binding for components loaded via builder and it works as expected on my side. 
[Here is the sample application](https://github.com/NickIliev/NativeScript-issues/tree/master/NativeScript/issue_3077) I have created to test this case.

**Comment by alexrainman** [comment]
@NickIliev this works but what i am doing is different as i am loading a component, getting its native instance and adding it to a native view, as a view in Android ViewPager, as a view in UIViewController added to UIPageViewController in iOS.

Android ViewPager Adapter:

```
instantiateItem (container: android.view.ViewGroup, position: number)
{
    var item = this._owner.itemsSource.getItem(position);
    var view = this._owner.templateSelector.OnSelectTemplate(position, item);
    var obj = <any>view;
    obj._onAttached(application.android.currentContext);
    container.addView(obj.android);
    obj.onLoaded();
    return obj.android;
}
```

iOS UIPageViewController DataSource:

```
public createViewController(position: number) : UIViewController 
{
    var item = this.itemsSource.getItem(position);
    var view = this.templateSelector.OnSelectTemplate(position, item);
    var obj = <any>view;
    var viewController = new ViewContainer();
    viewController.view = obj._view;
    obj.onLoaded();
    return viewController;
}
```

Any ideas?

**Comment by NickIliev** [comment]
Hey @alexrainman 

I think the issue here is again related to the usage of _onAttached which leads to not receiving the child context. Apply [the fix for your other thread](https://github.com/NativeScript/NativeScript/issues/3054#issuecomment-262458425) with _AddView and let me know if you can access the parent's context.

**Comment by alexrainman** [comment]
@NickIliev the fix in the other thread works for CSS but $parents still not working 👍

**Comment by NickIliev** [comment]
Hey @alexrainman 

I have tested your **demo** application from the Carousel view and at my side, it works as expected with parents binding. Here is the modification i have made to test the $parents binding.

At your slider-view.xml added label with $parents binding like this:
```
<StackLayout loaded="onLoaded" horizontalAlignment="center" padding="12" backgroundColor="blue" tap="stackTap">
    <Label text="{{ first }}" cssClass="label" tap="labelTap"/> 
    <Label text="{{ last }}"/>
    <Button text="Remove me" tap="buttonTap"/> 
    <Label text="{{ $parents['CarouselView'].position, $parents['CarouselView'].position }}" />
</StackLayout>
```

at your ViewModels/main-view-model.ts added the position property

```
    ....
    public _position: string;

    constructor() {
        super();

        // Initialize default values.

        this.templateSelector = new MyTemplateSelector();

        var person = new Person();
        person.first = "Alexander";
        person.last = "Reyes";

        var items = [ person, person, person, person, person ];
        this.itemsSource = new observableArrayModule.ObservableArray<Person>(items);

        this._position = "ala bala";
    }

    
    get position(): string {
        return this._position;
    }

    set position(value: string) {
        if (this._position !== value) {
        this._position = value;
        this.notifyPropertyChange('position', value)
        }
    }

   ....
```

Nothing more was added - the label is successfully retrieving the position value.

![parents](https://cloud.githubusercontent.com/assets/18008302/20598382/b216b414-b251-11e6-8125-0ea3e44b2c73.png)

**Comment by alexrainman** [comment]
Yes, but this access to the CarouselView binding context properties, not the view properties itself.

**Comment by alexrainman** [comment]
I understand now what $parents is for. Thanks
