### ISSUE TITLE
Is there any plan to support vue2

### ISSUE THREAD

**Issue by yayanyang** [NativeScript/NativeScript#3083]

**Comment by NickIliev** [comment]
Hey @yayanyang 

NativeScript is open source project and there are multiple requests to support many different and interesting libraries and technologies. However, the development team has priorities which are followed and one of the priorities is to deliver the most wanted features.
In order one feature to be considered most-wanted, you can vote for it - for example [here is the voting for vue.js](https://nativescript.ideas.aha.io/ideas/NS-I-94).
You can also upvote this feature request [here](https://github.com/NativeScript/NativeScript/issues/2437).

I would also recommend joining our slack channels where the community is discussing various topics including the development of new plugins.

Closing this issue as duplicate to [https://github.com/NativeScript/NativeScript/issues/2437](https://github.com/NativeScript/NativeScript/issues/2437)
