### ISSUE TITLE
Support lower-case-dashed component declaration in the XML

### ISSUE THREAD

**Issue by ligaz** [NativeScript/NativeScript#309]
For developers coming from a web developer perspective (HTML) it would be good to support XML declarations that are using lower-case-dashed syntax (aka kebap-case). Here is an example:
```xml
<page>
  <scroll-view>
    <stack-layout>
      <label cssClass="title" text="Layouts" />
      <stack-layout>
        <button tag="layouts/stack-layout" text="StackLayout" tap="itemTap" />
...
```

Possible technical implementations:

1. Split by Capital case. Ex:
`Button` - `button`
`MyButton` - `my-button`
`MySuperButton` - `my-supper-button`

2. Add a decorator to the component class. Ex:
```ts
@Component({tagName: 'button'})
export class Button extends view.View implements definition.Button {
```

**Comment by tjvantoll** [comment]
+1 This has always bothered me but I never thought to log it.

**Comment by RangerMauve** [comment]
This would make the different UI elements feel more like web components, and maybe in the future could be used to actually use web components.
