### ISSUE TITLE
Https module support

### ISSUE THREAD

**Issue by garciaguillermoa** [NativeScript/NativeScript#3094]
Hi, I am working on an application that requires https requests with an attached certificate and key in order to authenticate against a proxy. I haven't been able to achieve this as the modules that I have tried with (request, node-rest-client) depend on https module. My questions are:
Does NativeScript support https module?
Is there another alternative?

In case it helps, here is a code sample:
```js
var https = require("https");

var options = {
  host: 'www.sample.com',
  port: 443,
  path: '/api/v1.0/sample/endpoint',
  method: 'GET',
  headers: {
    accept: 'application/json'
  },
  key: certificateKey,
  cert: certificateFile
};

var req = https.request(options, function(res) {
  res.on('data', function(d) {

  });
  res.on('error', function(e) {

  });
});
req.end();
```

The **certificateKey** and **certificateFile** would contain the respective data.

Thanks

**Comment by tsonevn** [comment]
Hi @garciaguillermoa,
Thank you for your interest in NativeScript.
Using [HTTP Module](https://docs.nativescript.org/cookbook/http) also supports https request. For iOS this is default setting as it is described in this [article ](https://techcrunch.com/2016/06/14/apple-will-require-https-connections-for-ios-apps-by-the-end-of-2016/) . It would also help if you could provide more detailed description about the wanted feature. Regarding to that you could also make your own plugin, which provides specific functionality for your needs. More about creating NativeScript plugin you, could find here-> [http://docs.nativescript.org/plugins/plugins](http://docs.nativescript.org/plugins/plugins) and [http://developer.telerik.com/featured/building-your-own-nativescript-modules-for-npm/](http://developer.telerik.com/featured/building-your-own-nativescript-modules-for-npm/).

Regards,
@tsonevn

**Comment by garciaguillermoa** [comment]
Hi @tsonevn,
Thanks for your reply.
I have been able to make https requests using the http module, but I haven't been able to attach the certificate and the key as I would do it using the https module (see my sample code in the first comment).
Basically, what I need is the support of the https module in NativeScript in order to achieve that.
I will look into creating my own plugin and I hope I can solve the problem.

Thanks for your time.
Regards, Guillermo.

**Comment by triniwiz** [comment]
@garciaguillermoa you can check out https://github.com/gethuman/nativescript-https

**Comment by garciaguillermoa** [comment]
Thanks @triniwiz! Right now I am working on a different project, but as soon as I can, I will get back to this. It looks like that library will solve my problem.
