### ISSUE TITLE
[Bug] *ngFor in span/formattedString

### ISSUE THREAD

**Issue by mikraus94** [NativeScript/NativeScript#3099]
Hi,

I'm trying to make *ngFor for span but without success.

It stacks texts under selfs

`<Label *ngFor="let span of spans>
<FormattedString>
<Span [text]="span.text" [fontAttributes]="span.att"></Span>
</FormattedString>
</Label>`

It doesn't work for

`<Label>
<FormattedString *ngFor="let span of spans>
<Span [text]="span.text" [fontAttributes]="span.att"></Span>
</FormattedString>
</Label>`

or

`<Label>
<FormattedString>
<Span *ngFor="let span of spans [text]="span.text" [fontAttributes]="span.att"></Span>
</FormattedString>
</Label>`

It shows only first object from spans array.

Can you help me or this is bug?

Thank you

**Comment by jlooper** [comment]
Did you see that you have a typo that may be impacting the layout? </FormattedString>

**Comment by mikraus94** [comment]
It's only typo in my text If you mean </FromattedString>

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#537
