### ISSUE TITLE
Cleanup `tns run ios --emulator` output

### ISSUE THREAD

**Issue by vjeux** [NativeScript/NativeScript#31]
Since the entire project is written in JS, there isn't a big need for displaying all the xctools build logs. It is super spammy and doesn't add any value for the end user. Would be nice removing it.

Example: https://gist.github.com/vjeux/3a87e04b90f62f43501b (846 lines)

**Comment by teobugslayer** [comment]
This issue was moved to NativeScript/nativescript-cli#410
