### ISSUE TITLE
Close dialogs/modal on older android closes nativescript app

### ISSUE THREAD

**Issue by m-abs** [NativeScript/NativeScript#3102]
### Tell us about the problem
Closing dialogs or modal-views on Android 4.2.2 exits the app.

### Which platform(s) does your issue occur on?
Android 4.2.2 (API 17)

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.0-2016-11-09-7088
- Cross-platform modules: 2.3.0
- Runtime(s): tns-android: 2.5.0-next-2016-11-11-1390

### Please tell us how to recreate the issue in as much detail as possible.
It's pretty simple to reproduce:
* Setup a android emulator with Android 4.2.2/API-17 (Google APIs Intel x86)
* Checkout the nativescript source code
* Run the demo app under `apps`
* Open any dialog or modal-view
* Close it again.
* App have now closed

It doesn't happen on Android 4.4/API-19

**Comment by tsonevn** [comment]
Hi @m-abs,
Thank you for reporting this problem.
I reviewed the given scenario and confirm that this is a real problem while using dialogs. I was able to reproduce this issue only on **Android** with **API level 17**. This strange behavior could be reproduced with `2.3` and `@next` modules. I am also attaching a link to a [sample project](https://github.com/tsonevn/dialogs_issue3102).


Regards,
@tsonevn

**Comment by tsonevn** [comment]
Hi @m-abs,

In my further research I found that the problem has been reproduced on x86 Android Emulators, however the most of the devices with `Android API level 17` have been `ARM` based. Regarding to that could you verify, whether this  behavior will be reproduced on `ARM` Android Emulator. 

Please let me know, whether you have still have this problem.

**Comment by m-abs** [comment]
Hi @tsonevn,

Running on an ARM based emulator the problem doesn't happen.
So it'll only minor issue that makes testing difficult for us.

**Comment by NickIliev** [comment]
@m-abs this one should be now fixed with @next (2.5.0 which is expected officially to be released within few days)
