### ISSUE TITLE
How to use scrollview in tabview , (this is the example i tried, but it is not working).Please Let me know the solution.

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#3107]
<TabView>

				<StackLayout *tabItem="{title: 'All Orders'}">

					<ScrollView>
						<GridLayout rows="auto " columns="auto,25,auto,*" class="p-10 m-5" (tap)="gotoOrderDetails()">
							<StackLayout row="0" col="0" verticalAlignment="center" class="t-15 color">
								<Label text="Order No " textWrap="true"></Label>
								<Label text="Order Date" textWrap="true"></Label>
								<Label text="Order Status" textWrap="true"></Label>
							</StackLayout>
							<StackLayout row="0" col="1" verticalAlignment="center" horizontalAlignment="right" class="t-15 color">
								<Label text=":" textWrap="true"></Label>
								<Label text=":" textWrap="true"></Label>
								<Label text=":" textWrap="true"></Label>
							</StackLayout>

							<StackLayout row="0" col="2" class="t-15 color" verticalAlignment="center">
								<Label text=" 12345678923456745" textWrap="true"></Label>
								<Label text=" 12-10-2016" textWrap="true"></Label>
								<Label text=" Verified" textWrap="true"></Label>

							</StackLayout>
							<StackLayout row="0" col="3" horizontalAlignment="right" verticalAlignment="center">
								<Label text="&#xf105;" textWrap="true" class="example rightArrow"></Label>
							</StackLayout>

						</GridLayout>
						<StackLayout class="hr-light"></StackLayout>
						<GridLayout rows="auto " columns="auto,25,auto,*" class="p-10 m-5" (tap)="gotoOrderDetails()">
							<StackLayout row="0" col="0" verticalAlignment="center" class="t-15 color">
								<Label text="Order No " textWrap="true"></Label>
								<Label text="Order Date" textWrap="true"></Label>
								<Label text="Order Status" textWrap="true"></Label>
							</StackLayout>
							<StackLayout row="0" col="1" verticalAlignment="center" horizontalAlignment="right" class="t-15 color">
								<Label text=":" textWrap="true"></Label>
								<Label text=":" textWrap="true"></Label>
								<Label text=":" textWrap="true"></Label>
							</StackLayout>

							<StackLayout row="0" col="2" class="t-15 color" verticalAlignment="center">
								<Label text=" 12345678923456745" textWrap="true"></Label>
								<Label text=" 12-10-2016" textWrap="true"></Label>
								<Label text=" Delivered" textWrap="true"></Label>

							</StackLayout>
							<StackLayout row="0" col="3" horizontalAlignment="right" verticalAlignment="center">
								<Label text="&#xf105;" textWrap="true" class="example rightArrow"></Label>
							</StackLayout>

						</GridLayout>
						<StackLayout class="hr-light"></StackLayout>

					</ScrollView>
				</StackLayout>

				<StackLayout *tabItem="{title: 'Delivery Orders'}">
					<GridLayout rows="auto " columns="auto,25,auto,*" class="p-10 m-5" (tap)="gotoOrderDetails()">
						<StackLayout row="0" col="0" verticalAlignment="center" class="t-15 color">
							<Label text="Order No " textWrap="true"></Label>
							<Label text="Order Date" textWrap="true"></Label>
							<Label text="Order Status" textWrap="true"></Label>
						</StackLayout>
						<StackLayout row="0" col="1" verticalAlignment="center" horizontalAlignment="right" class="t-15 color">
							<Label text=":" textWrap="true"></Label>
							<Label text=":" textWrap="true"></Label>
							<Label text=":" textWrap="true"></Label>
						</StackLayout>

						<StackLayout row="0" col="2" class="t-15 color" verticalAlignment="center">
							<Label text=" 12345678923456745" textWrap="true"></Label>
							<Label text=" 12-10-2016" textWrap="true"></Label>
							<Label text=" Delivered" textWrap="true"></Label>

						</StackLayout>
						<StackLayout row="0" col="3" horizontalAlignment="right" verticalAlignment="center">
							<Label text="&#xf105;" textWrap="true" class="example rightArrow"></Label>
						</StackLayout>

					</GridLayout>
					<StackLayout class="hr-light"></StackLayout>
					<GridLayout rows="auto " columns="auto,25,auto,*" class="p-10 m-5" (tap)="gotoOrderDetails()">
						<StackLayout row="0" col="0" verticalAlignment="center" class="t-15 color">
							<Label text="Order No " textWrap="true"></Label>
							<Label text="Order Date" textWrap="true"></Label>
							<Label text="Order Status" textWrap="true"></Label>
						</StackLayout>
						<StackLayout row="0" col="1" verticalAlignment="center" horizontalAlignment="right" class="t-15 color">
							<Label text=":" textWrap="true"></Label>
							<Label text=":" textWrap="true"></Label>
							<Label text=":" textWrap="true"></Label>
						</StackLayout>

						<StackLayout row="0" col="2" class="t-15 color" verticalAlignment="center">
							<Label text=" 12345678923456745" textWrap="true"></Label>
							<Label text=" 12-10-2016" textWrap="true"></Label>
							<Label text=" Delivered" textWrap="true"></Label>

						</StackLayout>
						<StackLayout row="0" col="3" horizontalAlignment="right" verticalAlignment="center">
							<Label text="&#xf105;" textWrap="true" class="example rightArrow"></Label>
						</StackLayout>

					</GridLayout>
					<StackLayout class="hr-light"></StackLayout>
				</StackLayout>
				<StackLayout *tabItem="{title: 'Cancelled Orders'}">
					<GridLayout rows="auto " columns="auto,25,auto,*" class="p-10 m-5" (tap)="gotoOrderDetails()">
						<StackLayout row="0" col="0" verticalAlignment="center" class="t-15 color">
							<Label text="Order No " textWrap="true"></Label>
							<Label text="Order Date" textWrap="true"></Label>
							<Label text="Order Status" textWrap="true"></Label>
						</StackLayout>
						<StackLayout row="0" col="1" verticalAlignment="center" horizontalAlignment="right" class="t-15 color">
							<Label text=":" textWrap="true"></Label>
							<Label text=":" textWrap="true"></Label>
							<Label text=":" textWrap="true"></Label>
						</StackLayout>

						<StackLayout row="0" col="2" class="t-15 color" verticalAlignment="center">
							<Label text=" 12345678923456745" textWrap="true"></Label>
							<Label text=" 12-10-2016" textWrap="true"></Label>
							<Label text=" Cancelled" textWrap="true"></Label>

						</StackLayout>
						<StackLayout row="0" col="3" horizontalAlignment="right" verticalAlignment="center">
							<Label text="&#xf105;" textWrap="true" class="example rightArrow"></Label>
						</StackLayout>

					</GridLayout>
					<StackLayout class="hr-light"></StackLayout>
					<GridLayout rows="auto " columns="auto,25,auto,*" class="p-10 m-5" (tap)="gotoOrderDetails()">
						<StackLayout row="0" col="0" verticalAlignment="center" class="t-15 color">
							<Label text="Order No " textWrap="true"></Label>
							<Label text="Order Date" textWrap="true"></Label>
							<Label text="Order Status" textWrap="true"></Label>
						</StackLayout>
						<StackLayout row="0" col="1" verticalAlignment="center" horizontalAlignment="right" class="t-15 color">
							<Label text=":" textWrap="true"></Label>
							<Label text=":" textWrap="true"></Label>
							<Label text=":" textWrap="true"></Label>
						</StackLayout>

						<StackLayout row="0" col="2" class="t-15 color" verticalAlignment="center">
							<Label text=" 12345678923456745" textWrap="true"></Label>
							<Label text=" 12-10-2016" textWrap="true"></Label>
							<Label text=" Cancelled" textWrap="true"></Label>

						</StackLayout>
						<StackLayout row="0" col="3" horizontalAlignment="right" verticalAlignment="center">
							<Label text="&#xf105;" textWrap="true" class="example rightArrow"></Label>
						</StackLayout>

					</GridLayout>

				</StackLayout>

			</TabView>

**Comment by tsonevn** [comment]
Hi @dhanalakshmitawwa,
I reviewed your case and found that the problem appears only on the first tab of the `TabView` component. To be displayed properly the content you should have one main container, for example `StackLayout`, which to include all other components, which you would like to display in this `tab`. 
The code for your first tab should look like the example below.
```
<StackLayout *tabItem="{title: 'All Orders'}">

				<ScrollView>
                   <StackLayout>
					<GridLayout rows="auto " columns="auto,25,auto,*" class="p-10 m-5" (tap)="gotoOrderDetails()">
						<StackLayout row="0" col="0" verticalAlignment="center" class="t-15 color">
							<Label text="Order No " textWrap="true"></Label>
							<Label text="Order Date" textWrap="true"></Label>
							<Label text="Order Status" textWrap="true"></Label>
						</StackLayout>
						<StackLayout row="0" col="1" verticalAlignment="center" horizontalAlignment="right" class="t-15 color">
							<Label text=":" textWrap="true"></Label>
							<Label text=":" textWrap="true"></Label>
							<Label text=":" textWrap="true"></Label>
						</StackLayout>


						<StackLayout row="0" col="2" class="t-15 color" verticalAlignment="center">
							<Label text=" 12345678923456745" textWrap="true"></Label>
							<Label text=" 12-10-2016" textWrap="true"></Label>
							<Label text=" Verified" textWrap="true"></Label>

						</StackLayout>
						<StackLayout row="0" col="3" horizontalAlignment="right" verticalAlignment="center">
							<Label text="&#xf105;" textWrap="true" class="example rightArrow"></Label>
						</StackLayout>

					</GridLayout>
					<StackLayout class="hr-light"></StackLayout>
					<GridLayout rows="auto " columns="auto,25,auto,*" class="p-10 m-5" (tap)="gotoOrderDetails()">
						<StackLayout row="0" col="0" verticalAlignment="center" class="t-15 color">
							<Label text="Order No " textWrap="true"></Label>
							<Label text="Order Date" textWrap="true"></Label>
							<Label text="Order Status" textWrap="true"></Label>
						</StackLayout>
						<StackLayout row="0" col="1" verticalAlignment="center" horizontalAlignment="right" class="t-15 color">
							<Label text=":" textWrap="true"></Label>
							<Label text=":" textWrap="true"></Label>
							<Label text=":" textWrap="true"></Label>
						</StackLayout>


						<StackLayout row="0" col="2" class="t-15 color" verticalAlignment="center">
							<Label text=" 12345678923456745" textWrap="true"></Label>
							<Label text=" 12-10-2016" textWrap="true"></Label>
							<Label text=" Delivered" textWrap="true"></Label>

						</StackLayout>
						<StackLayout row="0" col="3" horizontalAlignment="right" verticalAlignment="center">
							<Label text="&#xf105;" textWrap="true" class="example rightArrow"></Label>
						</StackLayout>

					</GridLayout>
					<StackLayout class="hr-light"></StackLayout>
                </StackLayout>
				</ScrollView>
                             
			</StackLayout>
```

For further help you could also use the examples in [this ](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/ui-category/tab-view/basic-tab-view/basic-tab-view.component.html) sample app. Regarding to the issue, for further question you could also use [StackOverflow](http://stackoverflow.com/questions/tagged/nativescript) .

Hope this helps.

**Comment by dhanalakshmitawwa** [comment]
Thank you for reply
