### ISSUE TITLE
Colors issues {N} 2.4

### ISSUE THREAD

**Issue by pgrzeszczak** [NativeScript/NativeScript#3113]
Hi, I have 2 problems after update app to {N} 2.4 (Android 7.0, Angular2)

1. I can't set transparent border to button. When I try to set `border-color: rgba(0, 0, 0, 0);` it appeared as black border, but when I try `border-color: rgba(0, 0, 0, 0.1);` it works fine
2. I can't set background color to white on custom dialog. When I try to set `this.page.backgroundColor = new Color('rgb(255,255,255)');` or just `'white'`, dialog appears without any background (transparent). Also without setting any custom background, it appears as transparent. But when I try `this.page.backgroundColor = new Color('rgb(250,250,250)');`, it works.

**Comment by kwong93** [comment]
I also have a problem with background color on modals in Android. All modals shown using `showModal` have transparent backgrounds after upgrading to 2.4. Previously it was white. Now I can barely see text input for text fields. Did a `tns create` for a fresh test app and same issue.

**Comment by hamorphis** [comment]
I will investigate this issue.

**Comment by hamorphis** [comment]
I've opened a new issue for the background of the dialogs: https://github.com/NativeScript/NativeScript/issues/3129

**Comment by hamorphis** [comment]
Fixed the background issue as well.
