### ISSUE TITLE
Why N2.4 generated ios package file is so big?

### ISSUE THREAD

**Issue by jiafuzhang** [NativeScript/NativeScript#3114]
Today I have installed the latest version 2.4
And from the command line to create a default project, added the ios and android platform support
Very glad app to apply successfully generated, and to be able to run on ios and android emulator
Thank you for your great engineer's hard work
But I find that the generated ios package is very big, in the case of I did not add any code about **50M** or so
Don't know this is a problem, but I hope the generated ios app package can try a little bit small.
China's relevant information is less, hope to get your help.
Thank you!

**Comment by enchev** [comment]
Can you post your package.json content?
