### ISSUE TITLE
Feature : Ability to  change font size in List Picker

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#3115]

**Comment by tsonevn** [comment]
Hi @dhanalakshmitawwa,
Thank you for reporting this issue.

Such a functionality for changing the `fontSize` of the `ListPicker` items has not been supported in NativeScript.  We will research, whether this is possible to be supported for both `iOS` and `Android` platforms and will provide additional information about this feature.

Regards,
@tsonevn

**Comment by dhanalakshmitawwa** [comment]
Thank you for reply

**Comment by harrinsonmb** [comment]
+1

**Comment by tsonevn** [comment]
Duplicated with https://github.com/NativeScript/NativeScript/issues/3863
