### ISSUE TITLE
Feature: New Dialog-Prompt-Input-Type for E-Mails

### ISSUE THREAD

**Issue by Taremeh** [NativeScript/NativeScript#3118]
It would be great if the `ui/dialog prompt ` would offer an `inputType` for E-Mails (so the keyboard would display the "@" directly). Currently available are only plain `text` and `password`.

https://github.com/NativeScript/nativescript/blob/bc3910f/tns-core-modules/ui/dialogs/dialogs.d.ts#L49

**Comment by EddyVerbruggen** [comment]
I like the idea. See #3905 👍

**Comment by Taremeh** [comment]
Thx @EddyVerbruggen ! 😄
