### ISSUE TITLE
Add an article explaining how to work with images

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#312]
We have support for loading images based on the density and OS, but we are lacking and article for this.

**Comment by mdgiles** [comment]
This issue https://github.com/NativeScript/NativeScript/issues/276 seems to indicate the opposite - that you do not yet have support for loading images based on density and OS.  It is also my experience that the xcode project has to be manually modified for this to work on iOS, even for app_resources.

**Comment by valentinstoychev** [comment]
@mdgiles the issue you refer to describes a custom mechanism for loading images based on density. We have the default one working - e.g. by placing images in App_Resources folder.

**Comment by mdgiles** [comment]
So if I use a resource prefix in my xml, eg src="res://ic_menu"/, and then in app_resources/ios I have files named ic_menu.png, ic_menu@2x.png and ic_menu@3x.png, it should load those properly?  That is not my experience.  It does work for android, with the drawable* folders.

**Comment by mdgiles** [comment]
Sorry, extra / got in there, src="res://ic_menu"

**Comment by vakrilov** [comment]
@mdgiles - you are correct - there is a [known issue in the nativescritp-cli](https://github.com/NativeScript/nativescript-cli/issues/520). Currently you will have to manually add the images to the xCode project to make thi work.

**Comment by dtopuzov** [comment]
Article published to NativeScript site: http://uatdocs.nativescript.org/ui-images

**Comment by tjvantoll** [comment]
For anyone that stumbles upon this we have an implementation of this in [our Groceries sample](https://github.com/NativeScript/sample-Groceries) and have an explanation of what's going on in our [WIP quick-start guide](http://nativescript.github.io/quick-start/#chapter2.4).

**Comment by alexziskind1** [comment]
For those interested, the finished quick start guide is here: http://docs.nativescript.org/start/getting-started#images
