### ISSUE TITLE
Can't access native element of ActionItem

### ISSUE THREAD

**Issue by EricRobertBrewer** [NativeScript/NativeScript#3120]
### Tell us about the problem

<img width="402" alt="screen shot 2016-11-18 at 1 46 58 pm" src="https://cloud.githubusercontent.com/assets/1558524/20447781/9763089a-ad95-11e6-9b8f-2f52ae659697.png">

<img width="296" alt="screen shot 2016-11-18 at 12 01 50 pm" src="https://cloud.githubusercontent.com/assets/1558524/20447727/4de3a882-ad95-11e6-8f19-ecde78468475.png">

**All I *really* want to do is disable/enable ActionItem,** like so:

    import {ActionItem} from "ui/action-bar";
    ...
    setEnabled(actionItem: ActionItem, isEnabled: boolean) {
        if (actionItem.ios) {
            actionItem.ios.isEnabled = isEnabled;
        } else if (actionItem.android) {
            actionItem.android.setEnabled(isEnabled);
        }
    }

I was hoping to be able to gain access to the underlying native element of `ActionItem`, one of either `UIBarButtonItem` on iOS or `android.view.MenuItem` on Android. But this code gives us two errors:

`[ts] Property 'isEnabled' does not exist on type 'IOSActionItemSettings'.`
`[ts] Property 'setEnabled' does not exist on type 'AndroidActionItemSettings'.`

These errors occur despite the [`isEnabled` property of `UIBarItem`](https://developer.apple.com/reference/uikit/uibaritem/1616418-isenabled) on iOS and the [`setEnabled(boolean)` method of `android.view.MenuItem`](https://developer.android.com/reference/android/view/MenuItem.html#setEnabled(boolean)).

I was expecting this code to perform like [this section](http://docs.nativescript.org/angular/tutorial/ng-chapter-6) of the tutorial for [iOS](http://docs.nativescript.org/angular/tutorial/ng-chapter-6#61-accessing-ios-apis) and [Android](http://docs.nativescript.org/angular/tutorial/ng-chapter-6#62-accessing-android-apis), but it doesn't.

Digging deeper, we see that neither [ActionBar](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/action-bar/action-bar.d.ts#L36-L39) nor [ActionItem](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/action-bar/action-bar.d.ts#L158-L166) make native element access available, as does, for example, [TextField](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/text-field/text-field.d.ts#L13-L21). ***Why not?***

I would rather not use `*ngIf` to *hide* the action item completely [as is described here](http://docs.nativescript.org/angular/ui/action-bar#hiding-action-items).

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.3.0
- Cross-platform modules: 2.4.0
- Runtime(s): 2.3.0
- angular/core: 2.1.2
- nativescript-angular: 1.1.2
- typescript: ^2.0.10

### Please tell us how to recreate the issue in as much detail as possible.
Using code below, app doesn't compile.

Change line 20 of code below to:

        setEnabled(actionItem: any, isEnabled: boolean) {

to compile, but tapping action bar item on Android results in a crash.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
app/app.component.html:

    <ActionBar title="ActionItem">
        <ActionItem #saveActionItem (tap)="onSaveTapped($event)"
        ios.systemIcon="3" ios.position="right"
        android.systemIcon="ic_menu_save" android.position="actionBarIfRoom"></ActionItem>
    </ActionBar>
    <StackLayout>
    </StackLayout>

app/app.component.ts:

    import {Component, ViewChild, ElementRef} from "@angular/core";
    import {ActionItem} from "ui/action-bar";

    @Component({
        selector: "my-app",
        templateUrl: "app.component.html",
    })
    export class AppComponent {

        @ViewChild("saveActionItem") saveActionItem: ElementRef;

        onSaveTapped(event) {
            // simulate save to server
            this.setEnabled(<ActionItem>this.saveActionItem.nativeElement, false);
            setTimeout(() => {
                this.setEnabled(<ActionItem>this.saveActionItem.nativeElement, true);
            }, 500);
        }

        setEnabled(actionItem: ActionItem, isEnabled: boolean) {
            if (actionItem.ios) {
                actionItem.ios.isEnabled = isEnabled;
            } else if (actionItem.android) {
                actionItem.android.setEnabled(isEnabled);
            }
        }
    }

**Comment by NickIliev** [comment]
Hey @EricRobertBrewer 

The thing is that when you say [actionItem.ios](http://docs.nativescript.org/api-reference/classes/_ui_action_bar_.actionitem.html#ios) or [actionItem.android](http://docs.nativescript.org/api-reference/classes/_ui_action_bar_.actionitem.html#android) you are getting access to the [specific options for the acti9on items](http://docs.nativescript.org/api-reference/interfaces/_ui_action_bar_.iosactionitemsettings.html). These are nativeScript exposed properties and they are **position** and **systemIcon**

One applicable option if you do not wish to use angular directives to control your UI you can create a custom layout for you action item and apply your logic for it. 

For example:
```
  <ActionItem #saveActionItem>
    <StackLayout >
        <Label text="Custom item" color="#8C489F"></Label>
    </StackLayout>
  </ActionItem>
```

From this point you can access the custom view with **[actionView](http://docs.nativescript.org/api-reference/classes/_ui_action_bar_.actionitem.html#actionview)**
```
actionItem.actionView.android.setEnabled(isEnabled);
```
