### ISSUE TITLE
Label textWrap - provide CSS property

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/NativeScript#3123]
It only makes sense to make `textWrap` a CSS property much like `verticalAlignment`/`horizontalAlignment` can be set with `vertical-align`/`horizontal-align`.

I would recommend `text-wrap`.

**Comment by NickIliev** [comment]
By CSS specifications the property is called **word-wrap** - Perhaps, should follow these in order to make NatieScript more understandable for web-developers!? (although that would raise questions about textWrap and word-wrap name inconsistency)

**Comment by 3rror404** [comment]
Actually I think the CSS property that would be closest to this would be `white-space: normal` (multiline) and `white-space: nowrap` (single line).

Here is an example: https://jsfiddle.net/0913ar4b/

`word-wrap` defines with how individual words should be handled if they are too long to fit on a single line - rather than how a whole block of text is handled.

**Comment by enchev** [comment]
Hey folks,

We support already white-space:
https://github.com/NativeScript/NativeScript/blob/master/apps/app/ui-tests-app/css/white-space.xml

**Comment by shyandsy** [comment]
@enchev 

still not working on tns 2.5.2
```
.whiteSpace {
  white-space: normal; /* default value */
}
```

```
<label text="{{team}}" class="whiteSpace" width="100%" height="auto" horizontalAlignment="left"/>
```

**Comment by frapaa** [comment]
seems to work for 4.2.1, maybe earlier as well.

**Comment by jarrodwhitley** [comment]
> Hey folks,
> 
> We support already white-space: https://github.com/NativeScript/NativeScript/blob/master/apps/app/ui-tests-app/css/white-space.xml
> 
> @NathanWalker will this work for you?

Old link is dead. Long live the new link https://docs.nativescript.org/ui-and-styling.html#label
