### ISSUE TITLE
Issue creating native views within plugin

### ISSUE THREAD

**Issue by dapriett** [NativeScript/NativeScript#3127]
Hello,

I'm having some issues trying to add a custom infoWindow within the nativescript-google-maps-sdk plugin: https://github.com/dapriett/nativescript-google-maps-sdk/issues/77

I'm basically trying to implement this for Android: https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.InfoWindowAdapter
and this for iOS: https://developers.google.com/maps/documentation/ios-sdk/reference/protocol_g_m_s_map_view_delegate-p#ab83c3dab588f06e6227794740782bf55

They should return a native view for the supplied marker.  Here is what I started to implement:

map-view-common:[_getMarkerInfoWindowContent](https://github.com/dapriett/nativescript-google-maps-sdk/blob/custom_info_window/map-view-common.ts#L93)
map-view.android:[InfoWindowAdapter. getInfoContents](https://github.com/dapriett/nativescript-google-maps-sdk/blob/custom_info_window/map-view.android.ts#L342)
map-view.ios:[MapViewDelegateImpl.mapViewMarkerInfoContents](https://github.com/dapriett/nativescript-google-maps-sdk/blob/custom_info_window/map-view.ios.ts#L130)

When I run my demo app (https://github.com/dapriett/nativescript-google-maps-sdk/blob/custom_info_window/demo/app/main-page.js#L93), Android seems to work, although images are not loading.  As for iOS, nothing seems to appear at all - InfoWindow comes up blank.  

What modifications would you suggest?

iOS - Empty Info Window:
![image](https://cloud.githubusercontent.com/assets/4422908/20470246/ab277ab0-af74-11e6-8af4-189584f44f94.png)

Android - Working, but Blank Image 
![image](https://cloud.githubusercontent.com/assets/4422908/20470264/cef63e40-af74-11e6-90ae-070834f8454f.png)

Thanks!

**Comment by Yamilquery** [comment]
Nobody knows? Nobody knew :(

**Comment by NickIliev** [comment]
Closing as resolved (see [this thread](https://github.com/dapriett/nativescript-google-maps-sdk/issues/77#issuecomment-333014619))
