### ISSUE TITLE
android vs android.Manifest.permission

### ISSUE THREAD

**Issue by snekbaev** [NativeScript/NativeScript#3128]
Hi,

I had a 2.3 NG2+TS project. To work with permissions, say ```android.Manifest.permission.SEND_SMS``` I had to ```declare var android : any;```. Upgraded to 2.4, noticed that if I remove that declaration then I get quite rich intellisense in vscode. However, when done so TS complains that ```Manifest``` is not defined in the provided global ```android``` variable. To make it happy I have to resort back to the aforementioned ```android:any``` and basically lose intellisense.

What is the suggested workaround to keep both parties happy?

**Comment by Pip3r4o** [comment]
Hey @snekbaev, with 2.4 there's an experimental feature in the android domain that will generate typings (.Manifest included) for your needs. To try out run any `tns build/run android` command with the `--androidTypings` flag. That should also eliminate the need to use tns-platform-declarations, and even replace it.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#635

**Comment by snekbaev** [comment]
Hi,

will give it a try soon, thank you!
