### ISSUE TITLE
Ripple effect lost on Segmented-Bar with selectedBackgroundColor

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/NativeScript#3137]
NS 2.4 all
Using `selectedBackgroundColor` will lose the ripple effect. Tested on Android 6.0
This issue with the button fix many versions ago might help in fixing. https://github.com/NativeScript/NativeScript/issues/1296

CC: @enchev - you might remember this better than anyone 😄 

### Good
``` xml
<SegmentedBar>
            <SegmentedBar.items>
                <SegmentedBarItem title="Yesterday" />
                <SegmentedBarItem title="Today" />
                <SegmentedBarItem title="Tomorrow" />
            </SegmentedBar.items>
        </SegmentedBar>
```

### Broken
``` xml
 <SegmentedBar selectedBackgroundColor="red">
            <SegmentedBar.items>
                <SegmentedBarItem title="Yesterday" />
                <SegmentedBarItem title="Today" />
                <SegmentedBarItem title="Tomorrow" />
            </SegmentedBar.items>
        </SegmentedBar>
```

![segbarbug](https://cloud.githubusercontent.com/assets/6006148/20497907/9921cf06-aff0-11e6-85ac-28833748ba65.gif)

**Comment by bradmartin** [comment]
I'll update the .gif later, gotta downgrade licecap on mac 😞

**Comment by bradmartin** [comment]
![segbarbug](https://cloud.githubusercontent.com/assets/6006148/20498395/aa4e8dda-aff2-11e6-91f9-5b4ff5f3a7d5.gif)

**Comment by enchev** [comment]
Thanks @bradmartin! We will fix this immediately!
