### ISSUE TITLE
WebView with dom as src does not render when within Stacked or Absolute Layout

### ISSUE THREAD

**Issue by zackarychapple** [NativeScript/NativeScript#3138]
### Which platform(s) does your issue occur on?
iOS
### Please provide the following version numbers that your issue occurs with:
- CLI: 2.4.0 + --ng flag
- Runtime(s): "tns-ios"2.4.0

### Please tell us how to recreate the issue in as much detail as possible.
Tried the following combinations to get WebView to render. 
app.component.html
```
<StackLayout>
    <StackLayout class="nav">
        <Button text="Login"
                [nsRouterLink]="['/login']"></Button>
        <Button text="flashcards"
                [nsRouterLink]="['/flashcards']"></Button>
        <Button text="Second"
                [nsRouterLink]="['/flashcard/1']"></Button>
    </StackLayout>

    <router-outlet></router-outlet>
</StackLayout>
```

Where `router-outlet` puts out 
`<WebView [src]="'<div>here</div>'"></WebView>`

Tried with AbsoluteLayout as well.  I know it's not the webview configuration itself because when I put the webview element itself in my app.component.html it renders as expected.  It seems putting WebView in any layout breaks the render of WebView.

**Comment by tsonevn** [comment]
Hi @zackarychapple,

While using `StackLayout` and `AbsoluteLayout ` Layouts, you should specify the height of the inner component in iOS. Then  child components will be displayed properly. Another option is to use `GridLayout`. 
**Example**

```
<StackLayout class="p-20">
    <WebView height="100" [src]="'<div>here</div>'"></WebView>
</StackLayout>
```
Please let me know, whether this helps or if I could assist you further.

**Comment by zackarychapple** [comment]
@tsonevn thank you very much. Very helpful.  It also seems that even with height it will shrink to the content.  For example I set it to `1200` and even though the content was only around `500` the `WebView` did not have a lot of extra white space.  Is this expected?  Not complaining just surprised.
