### ISSUE TITLE
MAC Installation Problem 

### ISSUE THREAD

**Issue by stefanovay73** [NativeScript/NativeScript#3145]
Hi,I'm trying to install NativeScript on my MAC 10.11 but something is wrong.
On step 3 "Step 3: Install iOS and Android requirements" when I run "ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)" the script ask me if the XCode is installed. I answer yes but it do not find the XCode. 
I installed Latest XCode and latest XCode Command Line. What can I check?? 
Thanks in advance

**Comment by stefanovay73** [comment]
Hi,I'm trying to install NativeScript on my MAC 10.11 but something is wrong. On step 3 "Step 3: Install iOS and Android requirements" when I run "ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)" the script ask me if the XCode is installed. I answer yes but it do not find the XCode. I installed Latest XCode and latest XCode Command Line. What can I check?? Thanks in advance

**Comment by dtopuzov** [comment]
Is your Xcode installation with default name (Xcode.app)? 
Can you paste the output of "xcodebuild -version"?

**Comment by stefanovay73** [comment]
Now I not have the possibility to check. This evening I will do.
Anyway I tried to install the 8.1 and the 8.2 Beta 2
Thanks

**Comment by stefanovay73** [comment]
I re-installed Xcode previous version 7.3 and all works now.
But it is better use the last one or it is the same??
Thanks

**Comment by tsonevn** [comment]
Hi @stefanovay73,
Thank you for writing us back.
NativeScript should work with Xcode 8.1 as well as Xcode 7.3. Regarding to that, could you give us some more info about the problem you have, while using Xcode 8.1 . Where did you test your app: on real device or only on emulator? To be able to deploy your app with 8.1 on real device, you should first add your `Team_ID` in `app/App_Resources/iOS/build.xcconfig` file in your project.

**Comment by stefanovay73** [comment]
The problem was on installation part.
On Step 3 the script asked me if I had XCode installed, I answered yes and the result was XCode not found.
After I installed XCode 7.3 and all works fine.
I had no time to test my app becaus the system not worked.
Now it is ok.
Thanks again
