### ISSUE TITLE
ERROR ITMS-90680 When deploying on applestore

### ISSUE THREAD

**Issue by shinzao** [NativeScript/NativeScript#3146]
Hi,

I'm trying to deploy my app on the applestore, but everytime
<img width="697" alt="capture d ecran 2016-11-22 a 12 11 20" src="https://cloud.githubusercontent.com/assets/12793476/20522062/829e52fe-b0ae-11e6-8a14-1a20b8e046dd.png">
 I've tried, I get this error : 
ERROR: ERROR ITMS-90680: "The binary you uploaded was invalid."

I have tried the following ways : 
- Directly on Xcode (Archives control)
- From the CLI with the commands : 
    - tns publish ios

I get the same error.

Any idea ?

Thanks in advance

**Comment by NickIliev** [comment]
Hey @shinzao 

Can you share with us as much information as possible regarding your app setup.
We will need your package.json content as a starting point and even better provide us with the following

- **node.js** version
- **xCode** version
- OS version
- **NativeScript CLI** version
- **tns-core-modules** version and your whole **package.json** (from the root directory) to recreate an app will your exact same dependencies.

**Comment by shinzao** [comment]
Hey @NickIliev , thanks for you answer.

I've tried with : 
`tns publish ios YourAppleAccount YourApplePass`
and I get the same error.

This is my package.json : 
`
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "SARCInfo",
    "tns-ios": {
      "version": "2.4.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@angular/router": "3.0.0",
    "nativescript-angular": "^1.0.0",
    "nativescript-geolocation": "0.0.12",
    "nativescript-gradient": "^1.0.0",
    "nativescript-intl": "0.0.4",
    "nativescript-plugin-firebase": "^3.6.3",
    "nativescript-slides": "^2.1.5",
    "nativescript-telerik-ui": "^1.4.0",
    "reflect-metadata": "^0.1.8",
    "tns-core-modules": "^2.3.0"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^1.8.10",
    "zone.js": "^0.6.21"
  }
}
`

node.js version : v5.9.0
xCode version: v8.1
OS : OS X El Capitan v10.11.6
NativeScript CLI version : 2.4.0 
TNS version : 2.4.0

I forgot to say but it's my first time I try to post an app.

Thanks in advance

**Comment by NickIliev** [comment]
Hey @shinzao I've noticed that your issue is pretty similar [to this one](https://github.com/NativeScript/NativeScript/issues/3046#issuecomment-259716219).
You are already using the newest version of nativescript-slides where the fix should be updated but still... can you try the given workaround at your side. You can also check the other plugins in use for the same patterns (whether they have a reference in their root package.json file to tns-core-modules) and respectively either sync the used versions or remove it from their package.json and rebuild the plugin as shown in the link above.

**Comment by shinzao** [comment]
Hey @NickIliev, thanks for the answer.

I don't need nativescript-slides on my app. I've tried to remove the plugin with : 
`tns plugin remove nativescript-slides`

But I still have 2 errors : 
<img width="561" alt="capture d ecran 2016-11-22 a 18 40 54" src="https://cloud.githubusercontent.com/assets/12793476/20538683/874de97e-b0f2-11e6-8462-7b7529adad88.png">

Thanks in advance

**Comment by shinzao** [comment]
I have found my error. 
I had 2 directories lib (with TNSWidgets) in my repository.

Thanks !
