### ISSUE TITLE
[feature request] Java typecasting in NativeScript

### ISSUE THREAD

**Issue by pstueven** [NativeScript/NativeScript#3148]
The following is a code snippet from com.google.android.gms.nearby.nessages.internal.zzs.class's subscribe method.

`final zzrr var4 = ((zzr)var1.zza(hg)).zza(var1, var2);`

I could not find how to cast in NativeScript.
Is it possible to implement this feature, if it isn't yet?

**Comment by Pip3r4o** [comment]
Hey @pstueven, there are several technical limitations that stop us from realizing what you are requesting, as Java and JavaScript are not as similar as they seem at first sight. Casting in Java is used to instruct the compiler that you know better what the object is, that is unnecessary in JavaScript, and if done, would probably add unneeded overhead in the JavaScript execution. 

Method/Constructor resolution is done implicitly in the Android Runtime, and casting to certain types should not be concern.

**Comment by pstueven** [comment]
Hi @Pip3r4o ,
thanks for your reply!
I understand why it is not possible.
But still, it would be nice to have.
Because of [this](https://github.com/NativeScript/android-runtime/issues/636#issuecomment-261978876) issue, I tried to remake the subscribe method using {N}, but therefore I would need methods from zzr, that var1(GoogleApiClient) does not have.
So I will have to find another workaround.

**Comment by Pip3r4o** [comment]
@pstueven the aforementioned issue is being looked at, I'll let you know when we figure out why the crashes are occurring
