### ISSUE TITLE
Cohabitation of ng2 webapp with NativeScript app

### ISSUE THREAD

**Issue by zackarychapple** [NativeScript/NativeScript#3151]
### Tell us about the problem
I have an `angular-cli` generated angular2 app and its structure differs from the `tns` generated structure.  I have been trying to figure out how can I change where tns looks for the main.ts to bootstrap the application. The goal is to have the web and native app living in the same repo and control switching between them via which `main.ts` is bootstrapped. 

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.4.0 with `--ng` flag

**Comment by bradmartin** [comment]
@zackarychapple - does this seed project help any? https://github.com/NathanWalker/angular-seed-advanced there is another seed too, just don't recall the repo right now.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#552
