### ISSUE TITLE
[question] how to access local file[file://] from webview ? 

### ISSUE THREAD

**Issue by c1ngular** [NativeScript/NativeScript#3155]
**my scenario is :**

my app is mainly a webview , it loads a web page (.html file) and bunch of other files [images,js,audio,json] locally ,  it runs pretty well under node.js environment, but not on Nativescript app due to the webview[browser] restrictions . it prevents me from opening/readding local files [config files], so my app became useless in this case .  by searching around the internet , i came up with 2 possible solutions:

**1. build a http server inside the app** , this approach seems a bit of a long shot !

**2. i found that on android platform** , it has APIs such as setAllowContentAccess, setAllowFileAccess, setAllowFileAccessFromFileURLs , these methods seems relevant to this problem , **but i do not know how to use it from Nativescript side** , **on iOS platform ,i found no similar APIs to this problem** . overall,  it seems solution 2 is the easier one for me , but i got no clue **how to make this work on both platforms** .

any idea or advise would be really appreciated !

Best

**Comment by c1ngular** [comment]
**in case anyone is facing the same situation :**
on android platform , WebView.android.getSettings().setAllow... methods work ! [ i am testing on android 6.0 real device ], no progress made so far on iOS platform though !

**Comment by NickIliev** [comment]
@c1ngular 

It is not a trivial job to do even in native iOS for UIWebView.
This example shows [how to use local files with UIWebView](http://stackoverflow.com/a/5573155/4936697) and still even this implementation will not work as expected on all iOS versions.

**Comment by c1ngular** [comment]
@NickIliev thank you for helping me out , any suggestions for my option 1 [ a static web server inside the app ] ?

**Comment by NickIliev** [comment]
@c1ngular take a look [at this discussion](https://github.com/NativeScript/NativeScript/issues/1462). Creating your own plugin is the way to go.

**Comment by Alpha1001** [comment]
@c1ngular  @NickIliev Have you come up with a solution for this problems . I am trying to load a read file from a webview and push data into it through my nativescript app. But upon reading i found out that if i read from the webview , the file in the project is read whereas if i write in the file via the .ts code , it reads and update a file in file///data/data/0.nativescript........ 

Any help please?
