### ISSUE TITLE
[Question/Request] View to XML string? Opposite of builder.parse()

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#3162]
I would like to print a stringified View. I can do it the other way around, from string to View object with `builder.parse()`. But I need to do the opposite. Is this possible?

Would be great if this was a possibility:

```js
var builder = require("ui/builder");
var Label = require("ui/label").Label;

var labelView = new Label();
labelView.text = "Test";

var labelViewString = builder.stringify(labelView); // >>> <Label text="Test" />
```

**Comment by tsonevn** [comment]
Hi @NordlingArt,

At the moment NativeScript do not support such a functionality. Could you provide some more details about the need of such a functionality and for the cases,  which it will be applicable.

Regards,
@tsonevn

**Comment by NordlingArt** [comment]
@tsonevn Well, I am creating a plugin that makes use of [RadListView](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/overview) and RadListView.itemTemplate only works with strings. A user should be able to create the itemTemplate from code-behind and assign it, while the plugin converts it to a string.
