### ISSUE TITLE
Issue with WHxxx calculations on android / wrong files loaded.

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#3163]
## Please, provide the details below:

Ok, here is the scenario; 
Android 4.4.4, using a Device with the size 1024x600.  So In portrait mode the app starts up fine as a "tablet" sized device.  However if the app was switched to Landscape (still thinks it is a tablet) and will continue to use the MW600 files for the rest of the session.    However, if you exit the app in Landscape and restart the application; the application is Width is calculated as 1024, but the Height is now calculated as 552.   So this now causes the wrong files to be loaded.  It no longer things it is a tablet device.

Maybe I am thinking wrong, but the calculations needs to be using the raw values of the device not the values minus action/tool bars.

### Which platform(s) does your issue occur on?
Android ( iOS might have a similar issue, but 1024x768 - size is still above the 600 )

### Please provide the following version numbers that your issue occurs with:
2.4.x

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

- Create a demo app 
- Make sure Action bar is enabled.
- Create a `main-page.css`, add `Page { background-color: red; }`
- Create a `main-page.minWH600.css` add `Page { background-color: green; }`
- Consider adding to the tap event out put of the current width/height.

Run the app on a emulator with the dimensions of 1024x600.  (This is what a Amazon Fire is).
Start it up; you should get a green page.  Change orientation.  Quit the app.  Start the app up again, you will get the red page.

**Comment by NathanaelA** [comment]
To fix (api 17+) In the platforms.android file you can replace the existing code in the `MainScreen.metrics` property
```this._metrics = utils.ad.getApplicationContext().getResources().getDisplayMetrics();```
with this
```
this._metrics = new android.util.DisplayMetrics();
utils.ad.getApplicationContext().getSystemService(android.content.Context.WINDOW_SERVICE).getDefaultDisplay().getRealMetrics(this._metrics);
```

**Comment by NickIliev** [comment]
Hey @NathanaelA 

I have tested your issue ([here is the sample app](https://github.com/NickIliev/NativeScript-issues/tree/master/NativeScript/issue_3163) and I've used Android 4.4.4 Samsung GalaxyS4 emulator with a predefined screen size of 1024 x 768 (had to use Geny to create this specific emulator as I have not found a similar image for the 'state' AVD). However, I was **not** able to reproduce your results (with or without the modifications in platform.android.js the final results were the same in both cases).

Can you please share with us what system image you have used for the testing!?

**Comment by NathanaelA** [comment]
I cloned the Galaxy s5 emulator 4.4.4 - API 19, renamed it "Amazon Fire 4.4.4".  Then went into Settings and changed its screen size to Predefined 600x1024x160dpi 
![image](https://cloud.githubusercontent.com/assets/850871/20603268/5cd5c1dc-b226-11e6-8e47-c48d579cb654.png)
Hmm, looking at those settings **"Show Android Nav Bar"** might be the cause as those are on a real fire and so this emulator image works pretty darn close to a real fire;...

**Comment by NathanaelA** [comment]
Using your app you linked to above here is what I see:
![rotateissue](https://cloud.githubusercontent.com/assets/850871/20604761/b1b022cc-b22d-11e6-9124-6dc172292175.gif)

Actually now that I'm messing with it -- I'm pretty sure the "Show Android Nav Bar" is the key; I thought it was the header on top; but the Nav Bar eats screen real-estate.     If I use my code I copied in above, everything works as I would expect it too.  (Both orientations will be green).

**Comment by NickIliev** [comment]
@NathanaelA  I can confirm that mine emulator was created without the check for "Show Android Navigation Bar" and after I turned that option on I have reproduced your case, so I also think it is more likely a Genymotion related problem than a real issue. I personally prefer testing on AVDs with HAXM, as they are much more reliable, although lacking some of the option available in Genymotion.

**Comment by NathanaelA** [comment]
I actually have a fire; I'll test this tomorrow on a real device and see if the issue occurs on a real device.  
If you have an AVD, can you create it as a 600x1024 w/ the Nav Bar; do you see the same issue on an AVD image?

**Comment by NathanaelA** [comment]
I tested it on a Amazon Fire, it acts the exact same way Geny does.  If I start the app up in Port mode, I get green screens.  If I start it up in Land mode, I get red screens.    The Fire uses a Soft Nav Bar...

**Comment by vakrilov** [comment]
Hey @NathanaelA - good catch.
Indeed using the `WINDOW_SERVICE` method seems to return more consistent results and I believe this is the metrics we should use in the `platforms` module.

Can you do a PR with the fix?

**Comment by NathanaelA** [comment]
@vakrilov - Done.
