### ISSUE TITLE
Publish NativeScript JavaScript modules as npm packages

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#317]
Now that we have support for the npm packaging manager lets make our own modules to be as part of npmjs so that we can ease the update and discovery process. Modules which have dependency on the native project configuration should be separated as plugins.

**Comment by RangerMauve** [comment]
To be honest, first class NPM support is the only thing stopping me from using NativeScript for big apps right now. So the sooner this is implemented the better, I'd say. :D

**Comment by ligaz** [comment]
The initial thinking is that we can use the nativescript scope on npm to hold all NativeScript core modules. This means that the following require will be used:
```js
var geolocation = require('@nativescript/geolocation');
```
Having this in a separate scope (namespace) will allow us to support Node.js modules with same name as existing NativeScript modules.

**Comment by Nathanaela** [comment]
why not just leave it as is?
```
var geolocation = require('geolocation'); 
```
and then if there is not a node_modules/geolocation folder then require checks in the node_modules/nativescript/geolocation folder...

Nathanael A.

**Comment by ligaz** [comment]
Yes, this fallback will be provided so that current modules can load in the future without introducing breaking change. 

However the open question is which module should we load if there is `node_modules/http` and `node_modules/@nativescript/http`?

**Comment by Nathanaela** [comment]
Excellent Question:

I tend to think that  ```node_modules/http``` would be the one.   And I would use ```require('nativescript/http')``` to get the nativescript version.   Not sure their needed to be a '@'  
Or are you saying the folder itself on the harddrive with be ```node_modules/@nativescript/...```

**Comment by ligaz** [comment]
The `@` comes from the scoping in npm. You can find more information [here](https://docs.npmjs.com/misc/scope).

**Comment by Nathanaela** [comment]
Awesome.   I hadn't read about scoped packages, yet.   I see they were recently added.    That is pretty sweet.   Any idea when this will be usable in NativeScript?   The upgrade from to 1.1.0 is not exactly "clean" -- this would really make life a LOT simpler.  :grinning:

**Comment by ligaz** [comment]
We will gradually migrate all currently bundled core `tns_modules` into scoped packages between 1.1 and 1.2. The end goal is that at 1.2 timeframe the process will be streamlined and everything will be in npm. 

Regarding the current upgrade procedure the "process" is like this:
```sh
$ tns platform update ios
$ rsync -a node_modules/tns-core/ app/tns_modules
$ rm -rf node_modules/tns-core/
```

**Comment by dtopuzov** [comment]
{N} CLI will be able to consume modules as npm packages with 1.3.0. Modules will be published on each release.

**Comment by RangerMauve** [comment]
Awesome!
