### ISSUE TITLE
setup native script via terminal

### ISSUE THREAD

**Issue by MMAANNSS** [NativeScript/NativeScript#3176]
Hello every body , i have an issue while setup of nativescript when i run this command 
npm install -g nativescript
![screenshot from 2016-11-26 03-58-14](https://cloud.githubusercontent.com/assets/19964514/20639511/2912ebd2-b3ce-11e6-839f-2e0e58da9389.png)

**Comment by MMAANNSS** [comment]
could any one please help me out ?

**Comment by kazemihabib** [comment]
can you install other packages?

**Comment by MMAANNSS** [comment]
first at all i setuped npm and nodejs and used them in angular2 and typescript but they didn't work for nativescript i don't know the reason ?
kazemihabib

**Comment by enchev** [comment]
Hey @MMAANNSS,

Please upgrade your node to the current LTS version (6.9.1).

**Comment by NickIliev** [comment]
Hey @MMAANNSS have you managed to resolve this issue after updating to the latest stable Node.js ?!
