### ISSUE TITLE
Bug: Cannot read property 'LayoutParams' of undefined (ui/core/views.js)

### ISSUE THREAD

**Issue by Taremeh** [NativeScript/NativeScript#3177]
Hi!
I upgraded from NS 2.3 to the new **2.4.0** (I installed the new version, removed and added **Android** platform again, also I installed the core-modules a second time to version 2.4.0). But I still get the following error:

```
11-26 13:44:04.585  3526  3526 W System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
11-26 13:44:04.585  3526  3526 W System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
11-26 13:44:04.585  3526  3526 W System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
11-26 13:44:04.585  3526  3526 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:716)
11-26 13:44:04.585  3526  3526 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:697)
11-26 13:44:04.586  3526  3526 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:687)
```

The application actually starts (the Nativescript Launch Screen shows up correctly), but then the application crashes (=> screenshot).

Nativescript wants to load my LoginComponent, which uses <View> from "ui/core/view". And there the error happens (for more information have a look at the screenshot):
`TypeError: Cannot read property 'LayoutParams' of undefined` 

Here the screenshot after the app crashes:

https://cloud.githubusercontent.com/assets/1512652/20640619/67d09d8c-b3e3-11e6-8425-d14539b6aaab.png

**Comment by Pip3r4o** [comment]
Hey @Taremeh, please delete your `node_modules` dir, also do `tns platform remove android` followed by `tns platform add android`, and then `tns plugin add tns-core-modules`

**Comment by Taremeh** [comment]
Thanks @Pip3r4o !
I deleted and installed the platform, as well as Nativescript itself and the tns-core-modules a couple of times and it works now! Don't know where the error came from, but thanks to a clean reinstallation, everything works fine again. 😄
