### ISSUE TITLE
[iOS] imageSource.toBase64String() returns null if UIImage is CIImage-based

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#3179]
**Platform:** iOS
**TNS:** 2.4.0

The following code example will explain the issue:

```js
var inputImage = image.ios; // The UIImage, which initially is CGImage-based

var base64_1 = imageSource.fromNativeSource(inputImage).toBase64String("png");
console.log(base64_1); // This will return a valid base64 string of the image

if(inputImage.CGImage) {
  // Convert from CGImage to CIImage
  inputImage = CIImage.imageWithCGImage(inputImage.CGImage);
} else {
  // Refer to CIImage
  inputImage = inputImage.CIImage;
}

var newImage = UIImage.imageWithCIImage(inputImage);
var base64_2 = imageSource.fromNativeSource(newImage).toBase64String("png");
console.log(base64_2); // Returns null (because it's now a CIImage)
```

My use case is that I'm create an image processing function and images become a CIImage afterwards.

**Comment by NordlingArt** [comment]
Found a workaround (or actual solution?), which is to convert the CIImage back to CGImage after the processing is done.

**Comment by NickIliev** [comment]
@NordlingArt 

The thing is that **fromNativeSource(source)** is expecting **UIImage** and you are creating **CIImage** with `CIImage.imageWithCGImage(inputImage.CGImage)`. So the workaround you found is indeed applicable.
