### ISSUE TITLE
Android ListView performance when row class is assigned

### ISSUE THREAD

**Issue by snekbaev** [NativeScript/NativeScript#3180]
Hi,

Android, Nexus 5 with Marshmallow, NS 2.4.0. TS + NG. Plugins:
```
"nativescript-angular": "1.1.3",
"nativescript-direct-sms-send": "file:..\\nativescript_modules\\direct-sms-send",
"nativescript-messenger": "^1.2.0",
"nativescript-permissions": "^1.2.1",
"nativescript-ripple": "^1.0.1", 
```

I'm rendering a listview, content is quite simple, images used are either A.png or B.png from the resources, each image size is around 2.7KB. Items count is around 50 elements for now. I wanted to set different background for even rows and followed the official guide:

```
<ListView [items]="listItems" rowHeight="60" visibility="{{ !isLoading ? 'visible' : 'collapsed' }}">
    <template let-item="item" let-i="index" let-odd="odd" let-even="even">
        <StackLayout [class.odd]="odd" [class.even]="even">
            <Image [src]="item.image"></Image>
            <Label [text]='item.date' textWrap="true"></Label>
        </StackLayout>
    </template>
</ListView>
```
styles:
```
.odd {
}

.even {
    background-color: #FDFDFD;
}
```
however when I scroll the list fast I notice lags or even hiccups, doesn't feel very smooth. When I navigate away from the view and come back, performance is a bit better, but aforementioned issues remain. I tried to improve it by assigning the class directly:

```
<ListView [items]="listItems" rowHeight="60" visibility="{{ !isLoading ? 'visible' : 'collapsed' }}">
    <template let-item="item">
        <StackLayout [class]="item.listClass">    
            <Image [src]="item.image"></Image>
            <Label [text]='item.date' textWrap="true"></Label>
        </StackLayout>
    </template>
</ListView>
```

feels a bit better, but still... The only way I managed to get the best and smoothest experience was to give up any class assignments and just do:

```
<ListView [items]="listItems" rowHeight="60" visibility="{{ !isLoading ? 'visible' : 'collapsed' }}">
    <template let-item="item">
        <StackLayout> 
            <Image [src]="item.image"></Image>
            <Label [text]='item.date' textWrap="true"></Label>
        </StackLayout>
    </template>
</ListView>
```

Thank you!

P.S.: tried to assign the row height (rowHeight) via CSS, but seems that it is not supported yet, so inlined

**Comment by tsonevn** [comment]
Hi @snekbaev,
Thank you for reporting this issue,

I reviewed the problem, however this behavior could be related with the loadeing the image in the ListView item instead of a problem with applying the style. Regarding to that for better performance and to prevent from some further problems with loading the images in `Android`, you could use [nativescript-fresco](https://github.com/NativeScript/nativescript-fresco) plugin. For further help you could also review the example [here](https://github.com/telerik/nativescript-ui-samples-angular/blob/900d0259a3d4eb15c404c9555bde28de3241741d/sdkAngular/app/listview/item-layouts/listview-item-layouts-grid.component.android.html#L5).

Hope this helps,

**Comment by snekbaev** [comment]
As far as I remember before posting I tried commenting out the image output, issue remained. Moreover, yesterday I generated ~1000 dummy items (image+text) and list scrolling was (and still is) smooth without styles :)

Btw, I read in some NS issue that 2.4.0 was supposed to make the fresco plugin unnecessary by providing better image handling or...?

**Comment by tsonevn** [comment]
Hi @snekbaev,

With `NativeScript 2.4` we have some performance improvements and better image handling for Android. Regarding to the issue, I followed the above-given steps, however I was unable to reproduce this behavior in my local project. I tested the app on Nexus 6 real device. It would help if you could give us sample project, which will help us to investigate further this problem.

Regards,
@tsonevn

**Comment by snekbaev** [comment]
Hi,

there you go: https://drive.google.com/open?id=0B_AKy2bw0LtuVjlpWTA5U3hzSEE

So basically you need ```app.component.html```.

For the ultimate experience you need:
```
<template let-item="item">
```
for way less awesomeness you want:
```
<template let-item="item" let-odd="odd" let-even="even">
```

Try comparing both: scroll fast, scroll again and again while list is already scrolling, do the instant opposite scrolling while list is still scrolling etc. Watch the side scroll position indicator, how it moves. Without classes it is just outstanding and very responsive, however, when classes are used scroll indicator visibly moves less smooth, sometimes jumps a bit, occasionally scrolling freezes and in a couple of seconds ListView tries to catch-up with the gestures it has missed.

Thank you!

**Comment by snekbaev** [comment]
Probably not a fair comparison: I replicated the sample app in Xamarin Android. Setting the background color does not affect the ListView's performance:

```
var lvSmsHistory = FindViewById<ListView>(Resource.Id.lvSmsHistory);

            var data = new List<HistoryListItem>( 200 );

            for (var i = 0; i < 200; i++)
            {
                var imageToSet = i % 2 == 0 ? Resource.Drawable.list_unlocked_red : Resource.Drawable.list_locked_green;
                data.Add( new HistoryListItem { Image = imageToSet, Date = DateTime.UtcNow.ToString("H:mm:ss dddd, MMMM d yyyy", CultureInfo.InvariantCulture ) } );
            }
            
            lvSmsHistory.Adapter = new HistoryListAdapter(this, data);
```

Adapter:

```
internal sealed class HistoryListAdapter : BaseAdapter<HistoryListItem>
    {
        private readonly Activity _context;
        private readonly List<HistoryListItem> _items;
        private static readonly Color AlternativeColor = Color.ParseColor("#FAFAFA"); // pull that from resources!

        public HistoryListAdapter( [NotNull] Activity context, [NotNull] List<HistoryListItem> items )
        {
            _items = items;
            _context = context;
        }

        public override int Count => _items.Count;
        public override HistoryListItem this[ int position ] => _items[ position ];

        public override long GetItemId( int position )
        {
            return position;
        }

        public override View GetView( int position, View convertView, ViewGroup parent )
        {
            var item = _items[ position ];
            
            var view = _context.LayoutInflater.Inflate( Resource.Layout.HistoryListViewRow, parent, false );

            view.FindViewById<TextView>( Resource.Id.HistoryListViewRowText).Text = item.Date;
            view.FindViewById<ImageView>( Resource.Id.HistoryListViewRowImage).SetImageResource( item.Image );

            if (position % 2 == 0)
            {
                view.SetBackgroundColor(AlternativeColor);
            }

            return view;
        }
    }
```

History layout that contains the ListView:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/history_layout"
    android:orientation="vertical"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent">
  <android.support.v7.widget.Toolbar xmlns:app="http://schemas.android.com/apk/res-auto"
       android:id="@+id/toolbar"
       android:layout_width="match_parent"
       android:layout_height="wrap_content"
       android:minHeight="?attr/actionBarSize"
       android:background="?attr/colorPrimary"
       android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
       app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />
  <ListView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/lvSmsHistory" />
</LinearLayout>
```

Row layout:
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="horizontal"
    android:layout_width="fill_parent"
    android:layout_height="60dp">

  <ImageView
        android:id="@+id/HistoryListViewRowImage"
        android:layout_width="wrap_content"
        android:layout_height="28dp"
        android:layout_gravity="center"
        android:src="@drawable/icon"/>
  <TextView
          android:id="@+id/HistoryListViewRowText"
          android:layout_width="wrap_content"
          android:layout_height="match_parent"
          android:gravity="center"
          android:textSize="16dp"/>
</LinearLayout>
```

**Comment by tsonevn** [comment]
Hi @snekbaev,
Thank you for your feedback and for the  given suggestion.

We will research this problem further and will verify, what is causing this memory leak while using ListView in NativeScript Angular 2 project. You could keep track this issue for further info related with this problem.

Regards,
@tsonevn

**Comment by snekbaev** [comment]
@tsonevn please keep in mind that my previous comment is related to **Xamarin Android** where I basically replicated the behavior I was trying to achieve with NS and it shows that setting the background color doesn't not affect the performance like it does with NS.

**Comment by vakrilov** [comment]
Hey @snekbaev. The glitch when scrolling is most probably caused by a GC pass triggering to collect the object that is created when setting the background.

The good news is that there is way to further optimize the list view in you scenario. We have recently released support for different templates in ListView(NativeScript/nativescript-angular#527). Using this feature will help this case as the odd and even templates will be kept in separate "buckets" and reused with their background already set. So, it will spare the need to reset the background for each item. 

You can check [this gist](https://gist.github.com/vakrilov/4b098aab4cf766f4f92996e070adf493) to see how the templates work in you example.
_Note: I have bumped the versions of `@angular` and `nativescript-angular` packages_

**Comment by snekbaev** [comment]
Hi @vakrilov. Is this supposed to work in 2.4? I do get the output, but alternative class is not applied:

```
.odd {
    background-color: #FF0000;
}
.even {
    background-color: #CCCCCC;
}
```

```
 <ListView [items]="listItems" rowHeight="60" [itemTemplateSelector]="templateSelector">
        <!--<template let-item="item">-->
        <!--<template let-item="item" let-odd="odd" let-even="even">-->
                <!--<StackLayout [class.odd]="odd" [class.even]="even">
                    <Image [src]="item.image"></Image>
                    <Label [text]='item.date' textWrap="true" style="padding-left:10;"></Label>
                </StackLayout>
        </template>-->

         <template nsTemplateKey="odd" let-item="item">
            <StackLayout class="odd">
                <Image [src]="item.image"></Image>
                <Label [text]='item.date' textWrap="false" style="padding-left:10;"></Label>
            </StackLayout>
        </template>

        <template nsTemplateKey="even" let-item="item">
            <StackLayout class="even">
                <Image [src]="item.image"></Image>
                <Label [text]='item.date' textWrap="false" style="padding-left:10;"></Label>
            </StackLayout>
        </template>
    </ListView>
```

```
public templateSelector = (item: any, index: number, items: any) => {
        console.log((index % 2) ? "odd" : "even");
        return (index % 2) ? "odd" : "even";
    }
```

and the output is:
```
JS: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
JS: even
JS: even
JS: even
JS: even
JS: odd
JS: odd
JS: odd
JS: odd
JS: even
JS: even
JS: even
JS: even
JS: odd
JS: odd
JS: odd
JS: odd
JS: even
JS: even
JS: even
JS: even
JS: odd
JS: odd
JS: odd
JS: odd
JS: even
JS: even
JS: even
JS: even
JS: odd
JS: odd
JS: odd
JS: odd
JS: even
JS: even
JS: even
JS: even
JS: even
JS: odd
JS: even
JS: odd
JS: even
JS: odd
JS: even
JS: odd
JS: even
```

I get all rows in red (.odd). Also regarding versions update - it seems like we are using the same versions of ```@angular``` and ```nativescript-angular```, right?

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.ListViewIssue",
    "tns-android": {
      "version": "2.4.1"
    }
  },
  "dependencies": {
    "@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/core": "2.1.2",
    "@angular/forms": "2.1.2",
    "@angular/http": "2.1.2",
    "@angular/platform-browser": "2.1.2",
    "@angular/platform-browser-dynamic": "2.1.2",
    "@angular/router": "3.1.2",
    "nativescript-angular": "1.1.3",
    "nativescript-theme-core": "^0.2.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "2.4.0"
  },
  "devDependencies": {
    "babel-traverse": "6.19.0",
    "babel-types": "6.19.0",
    "babylon": "6.14.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^2.0.10",
    "zone.js": "~0.6.21"
  }
}
```

Thank you!

**Comment by vakrilov** [comment]
Ops, my mistake! The right versions are:
 - `2.2.1` for `@angular` (except for the router which is `3.2.1`)
 - `1.2.0` for `nativescript-angular`

I have also updated the snippet.

**Comment by snekbaev** [comment]
Updating the packages to these versions helped, thank you!
