### ISSUE TITLE
Data bind on navigation

### ISSUE THREAD

**Issue by snekbaev** [NativeScript/NativeScript#3182]
Android, Nexus 5 with Marshmallow, NS 2.4.0. TS + NG. Plugins:
```
"nativescript-angular": "1.1.3",
"nativescript-direct-sms-send": "file:..\\nativescript_modules\\direct-sms-send",
"nativescript-messenger": "^1.2.0",
"nativescript-permissions": "^1.2.1",
"nativescript-ripple": "^1.0.1", 
```

While continuing my journey with NS and I'm working on my first app. App is very simple and meant for personal use, it is my playground and I'm trying to get as best performance as possible. Current question is related to loading the data on navigation. I have "home" and "history" views. "Home" view has a link that takes user to the "history" view, which lists user smses: small image (set of 2) and the formatted date. Initially I used the ListView and NG's DatePipe and formatted the value in the markup. Tested the transition and noticed a bit of a delay before "history" view pops up, also ListView scrolling wasn't smooth enough. Then I decided to remove the DatePipe from the markup and rather apply it in the component directly to the data before assigning to the items property, so that ListView will render only simple text output, that made the scrolling super smooth. However, navigation lag was still there: a noticeable delay when I tap the "go to history" button. I traced it to the DatePipe's transform function.

Eventually what I wanted is to preprocess the data as much as possible beforehand and not do that on the main thread. So my next solution was to use a worker which does the heavy lifting now (via momentjs). Now navigation is instantaneous```*``` and "history" view immediately loads with a activity indicator and then data comes. This way app feels way more responsive.

Thus, the question: is my understanding correct that when any data preprocessing is needed, even for simple cases like formatting the date basically I have to do that via workers to get the best UX, what eventually means that I probably should start doing nearly all my data binding via workers.

```*```when app is newly started and first ever navigation is done - there is a small initial delay, **usually** doesn't happen when doing back-forward after that.

Thank you!

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#566

**Comment by nsndeck** [comment]
Hi @snekbaev,

Could you please send me a small sample project which I can debug on my end? Generally date pipe should not impact performance so bad.
Thank you in advance.

**Comment by snekbaev** [comment]
Hi @nsndeck, I replied in https://github.com/NativeScript/nativescript-angular/issues/566, let's continue there as this one is closed. Thank you!
