### ISSUE TITLE
Disable input controls while processing data.

### ISSUE THREAD

**Issue by TeddyBo** [NativeScript/NativeScript#3184]
### Tell us about the problem
I need to disable all TextFields and Button on a page while processing a data.
I've been trying to implement the following approach: [StackOverflow: How to add an activity-indicator on a page level?](http://stackoverflow.com/questions/39124433/how-to-add-an-activity-indicator-on-a-page-level), but all controls have still remained clickable and editable even having a `StackLayout` on top of them.
So is it possible to disables all input without specifying IsEnabled property on each one? 

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.4.0
- Cross-platform modules: 2.4.0
- Runtime(s): 2.4.1
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```
<GridLayout>
    <StackLayout>
        <StackLayout>
            <TextField hint="Username" [(ngModel)]="username"></TextField>
            <TextField hint="Password" [(ngModel)]="password"></TextField>
        </StackLayout>
        <Button text="Login" (tap)="login()"></Button>
    </StackLayout>
    <StackLayout verticalAlignment="stretch" horizontalAlignment="stretch" backgroundColor="gray" opacity="0.4">
    </StackLayout>
    <ActivityIndicator busy="true"></ActivityIndicator>
</GridLayout>
```

**Comment by NathanaelA** [comment]
You probably need to set the tap event on the stacklayout so it catches the tap event.   However things like this is not a bug; so it doesn't belong here in the github issues -- this is something that should be posted on StackOverflow in the future as I (& others) can give you better techniques that might be better than rendering another layer that isn't needed.

**Comment by TeddyBo** [comment]
Thank for our reply, I've got it. It would be get to know about another way how to achieve the same goal.
