### ISSUE TITLE
Tried this code but couldn't get the output 

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#3185]
```
<Image src="~/images/medzysettingbg.png" height="90" width="90" class="img-rounded"></Image>
<Image src="~/images/medzysettingbg.png" height="90" width="90" class="img-circle m-t-20"></Image>

```
[images](https://cloud.githubusercontent.com/assets/10844041/20658402/88f0cc28-b562-11e6-8a25-c3b4c24fde24.PNG)

Please send the code.

**Comment by NickIliev** [comment]
Hey @dhanalakshmitawwa 

Thank you for your interest in NativeScript.
This repository is for logging and resolving issues - the better place for common UI and UX techniques would be [stackoverflow](http://stackoverflow.com/questions/tagged/nativescript) .

Also, from your post it is not quite clear what problem you are trying to solve.
If you need to load images in vertical alignment you can use several different approaches.
For example, you can wrap them in StackLayout.
```
<StackLayout>
    <Image src="~/images/medzysettingbg.png" height="90" width="90" class="img-rounded"></Image>
    <Image src="~/images/medzysettingbg.png" height="90" width="90" class="img-circle m-t-20"></Image>
</StackLayout>
```
And apply the desired aligment via CSS.

**Comment by dhanalakshmitawwa** [comment]
Thank you for reply

**Comment by dhanalakshmitawwa** [comment]
I want image in circular form, and rounded

**Comment by NickIliev** [comment]
You need to apply border-radius equal to half of the side of you square image.

`<Image src="res://icon" height="100" width="100" borderRadius="50"></Image>`
