### ISSUE TITLE
Question: Telerik NativeScript

### ISSUE THREAD

**Issue by boustanihani** [NativeScript/NativeScript#319]
Just wondering, is this the official repo for the Telerik NativeScript: http://www.telerik.com/nativescript ??

I mean is this another product or just the repo for the one mentioned above? If not, how do the two relate to one another ??

**Comment by Nathanaela** [comment]
Yes, this is one of the repo's for Telerik's NativeScript.   This one handles the abstraction layer/common controls.

Their are a couple of them; docs, runtimes, meta-genarators.

**Comment by boustanihani** [comment]
THANKS
