### ISSUE TITLE
Unable to save image in custom component [android]

### ISSUE THREAD

**Issue by ullalaaron** [NativeScript/NativeScript#3190]
This is a real problem.
Here is the SO topic.
http://stackoverflow.com/questions/40827064/nativescript-how-to-save-image-to-file-in-custom-component

### Tell us about the problem
If I declare an Image tag in a custom component, the Image itself is defined but Image.imageSource is undefined, making it impossible, for example, to save the current image.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.4.0
- Cross-platform modules: 2.4.0
- Runtime(s): 2.4.0
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
Please check the above mentioned SO post :)
Thank you!

**Comment by NickIliev** [comment]
@ullalaaron 

I have answered in the SO thread - [direct link](http://stackoverflow.com/a/40866347/4936697).
