### ISSUE TITLE
Question: PropertyChange textfield fire on auto-complete?

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/NativeScript#3192]
- NS 2.4 all
- Only tested on Android as that's what the clients are mostly using when they report the issue.

In an app I use the `propertyChange` event on a text field to handle validation. 

```typescript

  // Email validation
        this.emailTextField.on("propertyChange", ((args: PropertyChangeData) => {
            if (this.emailTextField.text === '') {
                this.emailErrorMsg = 'Email is required.';
                this.emailContainer.classList.add('text-warning');
            } else {
                let isValid = emailValidator.validate(this.emailTextField.text);
                if (isValid === false || !isValid) {
                    this.emailErrorMsg = 'Email is invalid.';
                    this.emailContainer.classList.add('text-warning');
                } else {
                    this.emailErrorMsg = '';
                    this.emailContainer.classList.remove('text-warning');
                }
            }
        }))
```

The code works fine when the user keys in using the soft keyboard. What I didn't expect or test was users using auto-complete on their phones for their emails. So I've had numerous emails from users come in saying they can't sign in because it says invalid email because they've used the auto-complete email and not keyed in the value. I'm going to change the process in my app to not fire until a sign in attempt but the question is: is this a bug or expected behavior for `propertyChange` on the textfield?

**Comment by tsonevn** [comment]
Hi @bradmartin,
Thank you for reporting this issue.
We reviewed this scenario, however could you try to set `updateTextTrigger="focusLost"` to the TextField, which will trigger property change when the value has been set. This should work for the case, when autocompletion has been used. Could you verify if this will work for you or if we could assist further.

Hope this helps.

**Comment by bradmartin** [comment]
Hi @tsonevn with that property set the `propertyChangeEvent` only fires when leaving the textfield and not on keystrokes so then the above code I have that was checking the email string on every key stroke no longer executes until `focusLost`. Something doesn't seem right here 😕  any other thoughts? I'm currently taking a different approach to validating the email but I like the original approach I had here ^^^ but the auto-complete emails from users proved to me I was wrong 😄

**Comment by tsonevn** [comment]
Hi @bradmartin,
Could you send us sample code, where the problem could be reproduced. I am attaching the sample code, which I am using for testing. When I enter some text in the field, while using autocompletion, the correct value will be returned. 


main-page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
    <StackLayout class="p-20">
       <TextField hint="Field 1" updateTextTrigger="focusLost" id="tx" />
       <TextField hint="Field 2"  />
    </StackLayout>
</Page>
```

main-page.ts
```
import { EventData, PropertyChangeData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import {Observable} from "data/observable";
import {TextField} from "ui/text-field";

export function navigatingTo(args: EventData) {
    /*
    This gets a reference this page's <Page> UI component. You can
    view the API reference of the Page to see what's available at
    https://docs.nativescript.org/api-reference/classes/_ui_page_.page.html
    */
    let page = <Page>args.object;
    var textfield:TextField = <TextField>page.getViewById("tx");
    textfield.on("propertyChange", ((args: PropertyChangeData) => {
        var tField:TextField = <TextField>args.object;
        console.log(tField.text);
    }));
}
```

Thank you in advance for your cooperation
