### ISSUE TITLE
Camera on modals not work on iOS

### ISSUE THREAD

**Issue by ganeshhfs** [NativeScript/NativeScript#3195]
Hi,
I am using native script in one of the my application. I am using  page.showModal () in one of the screen in  application. In that screen i use camera to take the picture of something and use in application but it is not working at all on iOS, it won't allow two modals I think and the camera counts as one. The camera on modal is working fine on android device.  The camera is one type of modal and that why it not work on modal upon modal or it may  modal upon modal not working on in general.

can any one provide the solution for that? or shared any sample application solution on it.

**Comment by tsonevn** [comment]
Hi @ganeshhfs,
Thank you for reporting this issue,

I reviewed this scenario and was able to reproduce this behavior, when your try to open the camera via modal page on `iOS`.  We will research further this problem and will provide solution. I am also attaching sample [project](https://github.com/tsonevn/modalPageCamera_issue3195), where this behavior could be reproduced.

Regards,
@tsonevn

**Comment by tsonevn** [comment]
Hi @ganeshhfs,

In my further research I found  that this behavior is platform-specific and it is not related with NativeScript. For your scenario you could close the `ModalPage`, before you are opening the camera on iOS.  This will prevent from this problem and will allow you to use the camera. For your help I also upgrade my [sample project](https://github.com/tsonevn/modalPageCamera_issue3195), where has been show this case.

Hope this helps.

**Comment by isaacfi** [comment]
This is still an issue, you explained a workaround, but this has not to be closed.
