### ISSUE TITLE
Style or css of Dialog  button in nativescript core

### ISSUE THREAD

**Issue by ganeshhfs** [NativeScript/NativeScript#3198]
Hi,

 I am using dialog in my application as following way-

var dialogs = require("ui/dialogs");
dialogs.confirm({
  title: "Your title",
  message: "Your message",
  okButtonText: "Your button text",
  cancelButtonText: "Cancel text",
}).then(function (result) {}); 

In my application problem is that OK and Cancel button are invisible. So I need to use style or css for that.I want style this button with different style or css.
How can i style the buttons on dialogs? 

can any one have solution for that .Please shared sample application or solution for it 

Thanks and Regards 
Ganesh Madane

**Comment by NickIliev** [comment]
Hello @ganeshhfs 

At this very moment, you can apply only text color for your dialog.
To achieve that use CSS property **color** for element **Button**

e.g.
**_page.css_**
Button {
    color: red;
}

Now all button in your page.xml will be with red text color including the dialogs that are triggered from that page.

However, if you want to create fully customizable dialog, you can use [modal pages](https://docs.nativescript.org/core-concepts/navigation#modal-pages) which allow you to fully customize your layout.

**Comment by NickIliev** [comment]
Hey @ganeshhfs we are currently working on this feature - you can track it [here](https://github.com/NativeScript/NativeScript/issues/3220)
