### ISSUE TITLE
Instant reload?

### ISSUE THREAD

**Issue by vjeux** [NativeScript/NativeScript#32]
The big feature of the web and JavaScript is that refreshing after a code change is extremely fast. I was surprised that you still had to compile using xcode after every single change, basically negating the big developer velocity aspect of the web. Are you planning to support this?

**Comment by enchev** [comment]
Hi @vjeux!

We have already [LiveSync working for our companion app](http://docs.telerik.com/platform/appbuilder/nativescript/running-your-app/livesync-app) and we plan to add it for regular applications as well.

**Comment by thomasloh** [comment]
any news on this feature for nativescript CLI?

**Comment by Nathanaela** [comment]
@enchev  I think the question is when will the tns command support livesync to the companion app?    Is this something being worked on by a developer right now (if not, is their any docs on how I can communicate the changes to the NativeScript app?)

**Comment by csell5** [comment]
FWIW I've been using nodemon on the cli. Just make sure you're not watching the platform folder. Mine looks something like:

nodemon --exec "tns emulate ios --device=iPhone-6-Plus"  -e css,xml,js

**Comment by RangerMauve** [comment]
Posting to get notifications on developments. :3

**Comment by valentinstoychev** [comment]
Hey all I'm pleased to let you now that now as part of the 1.2 release we have the ```livesync``` command enabled. Enjoy it!

**Comment by Nathanaela** [comment]
Lol, I totally forgot I commented on this thread so long ago.   For those interested in a really fast LiveSync system; check out the plugin nativescript-livesync that I wrote way back in v1.00 and am still maintaining.   it only works on Android, but it is LIVE sync.
