### ISSUE TITLE
How to write the code for this page

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#3200]
![coupons](https://cloud.githubusercontent.com/assets/10844041/20712518/5616f74c-b66a-11e6-8cd5-a5d95053b5c8.PNG)

**Comment by tsonevn** [comment]
Hi @dhanalakshmitawwa,
Thank you for your interest in NativeScript,
Please report only real issues here and use [StackOverflow ](http://stackoverflow.com/questions/tagged/nativescript) or Slack for general questions. You could join the NativeScript Community on Slack, by using the registration form in our [web site ](https://www.nativescript.org/).
Regards,
@tsonevn

**Comment by dhanalakshmitawwa** [comment]
Thank you for reply
