### ISSUE TITLE
request for socket.io demo app

### ISSUE THREAD

**Issue by mg1075** [NativeScript/NativeScript#3204]
On the Resources page of the nativescript website, there is a link to a tutorial for using socket.io:
- https://www.nativescript.org/resources

The external link was for this tutorial: "Creating a realtime chat app with Socket.io and NativeScript".

- https://fitcom.co/2016/04/17/creating-realtime-chat-app-socket-io-nativescript/

The link returns a **404**.

There are two small github repos for dealing with socket.io and nativescript, yet the documentation is not that detailed, and apparently I am not the only one who has had trouble trying to get them to run on my local.

- https://github.com/triniwiz/nativescript-socketio
- https://github.com/naderio/nativescript-socket.io

What would be nice is if the nativescript team created a demo app of working with socket.io throughout an app, and with streaming data examples (not just "chat" type examples). A simple `http` service is insufficient for certain categories of apps.

**Comment by triniwiz** [comment]
@mg1075 atm my time is very limited so any plugins if needed will get love on the weekends and about the 404 i'll work on that
