### ISSUE TITLE
Why tns-core-modules duplicates node.d.ts, es2015 and es2016 typings?

### ISSUE THREAD

**Issue by pocesar** [NativeScript/NativeScript#3205]
### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.0-2016-11-28-7246
- Cross-platform modules: 2.5.0-2016-11-29-4890
- Runtime(s): 2.5.0-next-2016-11-28-1432
- Plugin(s): 
```
    "nativescript-barcodescanner": "^2.1.5",
    "nativescript-geolocation": "^0.0.15",
    "nativescript-loading-indicator": "^2.2.1",
    "nativescript-permissions": "^1.2.1",
    "nativescript-theme-core": "^1.0.1",
    "nativescript-unit-test-runner": "^0.3.4",
    "tns-core-modules": "^2.5.0-2016-11-29-4890",
    "tns-core-modules-widgets": "^2.5.0-2016-11-21-158"
```

### Please tell us how to recreate the issue in as much detail as possible.

When adding typings using `npm install @types/some-types`, usually `@types` will add `@types/node` as a dependency, and everything breaks, because `tns-core-modules` have it's own typings for things that Typescript already provides though either `lib.d.ts`, `es6.d.ts`, like WeakMap, WeakSet, Promise and other declarations, for es2015 and es2016. 

Is there any good reason why `tns-core-modules` is trying to give their own duplicated definitions for things that already exists and are well tested by Microsoft themselves in their "std" libs?

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

The minimum reproducible code is doing a "npm install @types/node", and the build fails. 

```
node_modules/@types/node/index.d.ts(38,11): error TS2300: Duplicate identifier 'MapConstructor'.

node_modules/@types/node/index.d.ts(40,11): error TS2300: Duplicate identifier 'SetConstructor'.
node_modules/@types/node/index.d.ts(49,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'global' must be of type 'any', but here has type 'Global'.
node_modules/@types/node/index.d.ts(73,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NativeScriptRequire', but here has type 'NodeRequire'.
node_modules/@types/node/index.d.ts(85,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'module' must be of type 'NativeScriptModule', but here has type 'NodeModule'.
node_modules/@types/node/index.d.ts(3966,5): error TS2309: An export assignment cannot be used in a module with other exported elements.
node_modules/tns-core-modules/es-collections.d.ts(30,14): error TS2300: Duplicate identifier 'MapConstructor'.
node_modules/tns-core-modules/es-collections.d.ts(31,14): error TS2300: Duplicate identifier 'SetConstructor'.
```

**Comment by PanayotCankov** [comment]
In your reference.d.ts can you try to point the `tns-core-modules.es2016.d.ts` or `tns-core-modules.base.d.ts` instead of `tns-core-modules.d.ts`?

**Comment by bufke** [comment]
I'm curious if there is a solution to this. I tried changing reference.d.ts but I just get different typescript errors. 

tns-core-modules.base.d.ts

```
node_modules/tns-core-modules/declarations.d.ts(102,22): error TS2304: Cannot find name 'NativeScriptRequire'.
node_modules/tns-core-modules/declarations.d.ts(122,18): error TS2300: Duplicate identifier 'log'.
node_modules/tns-core-modules/declarations.d.ts(162,21): error TS2304: Cannot find name 'NativeScriptModule'.
```

I'm trying to use some shared code from a web app that contains a lot of ES6. Targeting ES6 in tsconfig.json breaks a lot of stuff. I can use core-js or node type definitions but then I get these errors. I've seen some code in the angular 2 seed just assigning Object as any but that would really ugly up a external code base.
