### ISSUE TITLE
How can we know the difference between the image src  & image res ? in output

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#3207]
<Image src="~/images/lemons.png" ></Image>

			<Image src="res://lemons"  style="margin-top:20;"></Image>

I couldn't find any difference between those two images.

**Comment by tsonevn** [comment]
Hi @dhanalakshmitawwa,
Thank you for the question.

Loading image from the resources, while using `res://` prefix allows you to load the best image for the current device screen density. 
Another way to load image is from  local file system using `~/` prefix before the image name, however in this case images from the file system does not respect filename qualifiers.
You could read more about those two ways to load image in the application [here ](https://docs.nativescript.org/ui/images#load-images-from-a-resource) in the docs.

Hope this information helps.

**Comment by dhanalakshmitawwa** [comment]
Thank you for reply
