### ISSUE TITLE
how to exit app when crash ?

### ISSUE THREAD

**Issue by Leo-lay** [NativeScript/NativeScript#3208]
Hi, i'm a new nativescripter,I want to do something when my app crashes, the android app will display an incorrect page when it crashes, and I want to use **android.os.Process.killProcess (android.os.Process.myPid ());** to kill the android process, but this does not work, how should I do not show this error page?
`
application.on(application.uncaughtErrorEvent, args => {
            let android = args.android;
            if (android) {
                console.log('uncaughtErrorEvent android=>');
                console.log('uncaughtErrorEvent args android=>', android);
                android.os.Process.killProcess(android.os.Process.myPid());
            } else {
                console.log('uncaughtErrorEvent ios=>');
                console.log('uncaughtErrorEvent args ios=>', args.ios);
            }
        });
`
tns --version
2.4.0

**Comment by Pip3r4o** [comment]
Hey @Leo-lay what you see is not an incorrect page but in fact an activity that shows you the stack trace from an exception that was caused during app execution, and a logcat report. If you wish to close the activity, you simply need to press the Home or Back button, and we will kill the process for you. 

The activity is excluded from release builds (packages you upload to the playstore) so you don't need to take extra steps to remove it, or attempt to not display it.

**Comment by Leo-lay** [comment]
@Pip3r4o  Thank you for your replay，
yeah，it's appear debug ，But in the release version will appear a crash dialog, my idea is to kill the app process so there will be no pop-up box, so I want to do is when the app crash when directly exit.

**Comment by Pip3r4o** [comment]
@Leo-lay as I mentioned earlier, the crash screen will not appear in release builds, it is excluded altogether from the final package.

**Comment by Leo-lay** [comment]
@Pip3r4o  yeah， I know what you mean, my idea is that when the app crashes, do not appear **app has stopped** such a dialog，
eg.
![screenshot_20161130-231139](https://cloud.githubusercontent.com/assets/8528051/20757735/753afaf4-b752-11e6-8826-5a3a7b3b73fa.png)

**Comment by Pip3r4o** [comment]
@Leo-lay that is part of the Android Platform implementation (the [ActivityManager](https://android.googlesource.com/platform/frameworks/base/+/android-5.0.0_r2/services/core/java/com/android/server/am/ActivityManagerService.java)) and cannot be suppressed, or disabled for the end user.

**Comment by Leo-lay** [comment]
@Pip3r4o  all right，thx。
