### ISSUE TITLE
Deep linking

### ISSUE THREAD

**Issue by dbbk** [NativeScript/NativeScript#321]
Somewhat related to the forthcoming push notifications support, we need the ability to match URLs to states in our application to enable 'deep linking', so when you enter the app from a notification or from another app, the NativeScript app can interpret the URL path and take the user to the content they are trying to navigate to. This will get particularly greater focus with the release of iOS 9, as deep links are indexed within Spotlight search.

**Comment by ErjanGavalji** [comment]
@dbbk, deep linking will indeed be a really good addition to iOS.

To be honest, we haven't researched nor planned it yet.

It seems a good candidate for a NativeScript plugin, as it would need changes in the xcproj file (where the capabilities get stored).

@hshristov @ligaz @enchev, @teobugslayer, other opinions?

**Comment by dbbk** [comment]
The actual deep linking itself is super simple to implement, it's just the implementation of an actual router to parse the URL and push a navigation entry that would be the challenge. I understand Angular 2 is being integrated with NativeScript, do you know if that will include their component router?

**Comment by AresDev** [comment]
Any progress about this feature?

**Comment by tsonevn** [comment]
Hi @dbbk,

This feature seems to be an ideal candidate for a separate plugin.  An appropriate solution for iOS could be found [here ](https://github.com/NativeScript/NativeScript/issues/3632#issuecomment-279642394) in this issue.

Let me know, whether this helps.
