### ISSUE TITLE
Segmentedbar crash using a number as title - 2.4.0 android

### ISSUE THREAD

**Issue by FmarquezM** [NativeScript/NativeScript#3210]
In android, If you use a number as title in a segmentedbar item the app crash.
Not tested in iOS.

![image](https://cloud.githubusercontent.com/assets/18644204/20748196/86435fcc-b6ed-11e6-86ac-c7f3eb5b9128.png)

```
<SegmentedBar>
        <SegmentedBar.items>
            <SegmentedBarItem title="1" />
            <SegmentedBarItem title="2" />
        </SegmentedBar.items>
</SegmentedBar>
```

Perhaps this isn't the right way but i solved it with this little "hack" in this file.

> /YOUR_APP_FOLDER/platforms/android/src/main/assets/app/tns_modules/ui/segmented-bar/segmented-bar.js

In line 141 replace "||" with "+".

`tab.setIndicator(tabItem.title || ""); --> tab.setIndicator(tabItem.title + "");`

**Comment by NickIliev** [comment]
Hello @FmarquezM

Thanks for reporting this issue - I have tested it and can confirm that it is reproducible under Android and iOS.

Code to reproduce this issue [here](https://github.com/NickIliev/NativeScript-issues/tree/master/NativeScript/issue_3210)

**Comment by FmarquezM** [comment]
Happy to can help in some way.

Thanks a lot for your work, i'm really enjoying Nativescript !!
