### ISSUE TITLE
Masonry / Pinterest style list view

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/NativeScript#3222]
This is either a question or a feature request depending on the answer.

Is there a built in method using any of the available layouts that can produce a multi-column scrollable list with items of uneven height?

In the web world this layout is often know as a "masonry" layout after a popular [javascript plugin](http://masonry.desandro.com/) that produces layouts similar to the [Pinterest](https://pinterest.com/) feed.

I am required to produce a layout similar to this:

![masonry-grid](https://cloud.githubusercontent.com/assets/1102402/20799013/c5385142-b7d8-11e6-9df6-b0fd542d4d11.png)

The items need to be bindable and will have variable dimensions based on their content. In an ideal world it would work in a similar way to ListView with reusable items to conserve memory.

Is this possible with NativeScript?

Thanks

**Comment by tsonevn** [comment]
Hi @3rror404,
Thank you for your question. 

For your case you could use `nativescript-telerik-ui` plugin and its `RadListView` component. In this ListView you could set `ListViewStaggeredLayout` layout, which will provide the the needed order of the items, For more info you could review the plugins [documentation](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/item-layouts#using-listviewstaggeredlayout) or to review the sample project [here](https://github.com/telerik/nativescript-ui-samples/tree/release/sdk/app/listview/item-layouts).

Hope this helps.

**Comment by 3rror404** [comment]
Oh wow! That it is exactly what I was looking for. Thanks @tsonevn
