### ISSUE TITLE
any working code for fil upload typescript/ javascript

### ISSUE THREAD

**Issue by tzraikov** [NativeScript/NativeScript#3223]
from @swinn77:

any working code for fil upload typescript/ javascript, all samples on git i tried, but failed to understand where these files uploaded. i tried replicateing working html javascript php code but still not succeeded.

Moved from:
https://github.com/NativeScript/nativescript-cli/issues/2264

**Comment by tsonevn** [comment]
Hi @swinn77,
Thank you for your interest in NativeScript.

For your scenario you could use `nativescript-background-http ` plugin, which provides needed functionality. For further help you could review the following sample apps. [sample-ImageUpload](https://github.com/NativeScript/sample-ImageUpload/blob/master/app/main-page.js) and [SimpleBackgroundHttp](https://github.com/NativeScript/nativescript-background-http/tree/master/examples/SimpleBackgroundHttp). To be able to build the second project, you should first  open its `package.json` file and to change  `nativescript-background-http `  version to `*` -> `"nativescript-background-http": "*"`.

Let me know, whether this helps or if I could assist you further.
