### ISSUE TITLE
Update (or ideally automate) the listing of supported npm modules

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/NativeScript#3224]
The listing of [supported npm modules](https://github.com/NativeScript/NativeScript/wiki/supported-npm-modules) was last updated 1.5 years ago. It would be great to get this updated or magically auto-generated from npm if at all possible. It's a resource I use and send to people regularly when talking about library re-use.

**Comment by tsonevn** [comment]
Hi @rdlauer,

This list of [supported-npm-modules](https://github.com/NativeScript/NativeScript/wiki/supported-npm-modules) has been manually updated and include npm plugins, which has been manually tested in NativeScript. Unfortunately this process could not be automated at the moment. Regarding to that, if you have found another plugin, which could be used with NativeScript, we could include it to the available ones.

Regards,
@tsonevn
