### ISSUE TITLE
[iOS] Synchronous loading of background-images

### ISSUE THREAD

**Issue by bnussey** [NativeScript/NativeScript#3225]
I am experiencing very slow performance when using lots of background images on iOS and according to the debugger it looks like these are all being loaded synchronously. All the HTTP requests complete before the view initialises. From my understanding by default all images in NativeScript should be loaded asynchronously. 

Works as expected on Android.

Are you able to provide some clarification on this?

Thanks

**Comment by enchev** [comment]
Hey @bnussey,

Not sure what's causing the issue at your side however the code for downloading images is asynchronous for sure:
https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/http/http-request.ios.ts
