### ISSUE TITLE
How to insert images in different mobile screens

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#3227]
can I know the path.

**Comment by NickIliev** [comment]
You can use the native resources under app/App_Resources to store images with different resolution.
More about this: option [here (for Android)](http://uatdocs.nativescript.org/publishing/creating-launch-screens-android) and [here (for iOS)](http://uatdocs.nativescript.org/publishing/creating-launch-screens-ios).

You can also create pages with screen size qualifiers which will be loaded depending on the screen resolution. More about this [here](http://uatdocs.nativescript.org/ui/supporting-multiple-screens)

**Comment by dhanalakshmitawwa** [comment]
Thank you for reply
