### ISSUE TITLE
CSS class applied to child element does not override class applied to parent element

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/NativeScript#3234]
I have a CSS selector with a class + element applied to a parent layout. However, I'm not able to override the styles applied there in any child element. For example:

```
<StackLayout class="blue">
    <Label text="Example Text" class="red" />
</StackLayout>
```

```
.blue label {color: blue}
.red {color: red}
```
The text will always be blue, while I would expect to be able to override the color with the class applied directly to the label element.

**Comment by realtebo** [comment]
Try with a more specific CSS selector. For example:

    .blue Label.red {color :red} 

Because `.blue Label` is more specific than `.red` and so the more specific wins.
_This is my idea_

**Comment by rdlauer** [comment]
+1 that does work, thanks!
