### ISSUE TITLE
How to write this code for this image.

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#3240]
![first](https://cloud.githubusercontent.com/assets/10844041/20876479/65daca82-bae8-11e6-8f84-c4f72059c4da.PNG)

I tried this code 

		<AbsoluteLayout>
				<Label text="&#xf00c;" textWrap="true" left="85" top="10" horizontalAlignment="center" class="example checkIcon"></Label>
				<AbsoluteLayout class="Delivered">

					<GridLayout rows="*,*,*,*,  " columns="*,*,*" style="background-color:#f6f7f8; width:350;" class="m-15 p-10 ">

						<Label text="Delivered" textWrap="true" row="1" col="1"></Label>

					</GridLayout>
				</AbsoluteLayout>
			</AbsoluteLayout>

**Comment by NickIliev** [comment]
Hey @dhanalakshmitawwa 

I recommend using SO preferable for UI related cases.

AbsoluteLayout supports properties top and left for its childrend so one possible approach would be somthing like this:

```
<AbsoluteLayout>
    <GridLayout top="50" backgroundColor="red" width="350" height="350">
        <Label text="Delivered" textWrap="true" row="1" col="1"></Label>
    </GridLayout>
    <Image src="res://icon" width="80" height="80" left="85" top="10"></Image>
</AbsoluteLayout>
```

**Comment by dhanalakshmitawwa** [comment]
Thank you for reply
