### ISSUE TITLE
Plugin fixes for 2.5.0

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#3241]
* https://github.com/NativeScript/nativescript-imagepicker/issues/50
* https://github.com/NativeScript/nativescript-background-http/issues/43
* https://github.com/NativeScript/nativescript-background-http/issues/26
* https://github.com/NativeScript/nativescript-camera/issues/18
* https://github.com/NativeScript/nativescript-geolocation/issues/40
* https://github.com/NativeScript/nativescript-geolocation/issues/39

**Comment by Daxito** [comment]
After trying to use "tns publish ios", I got these errors, any idea?

Package Summary:
 
1 package(s) were not uploaded because they had problems:
	/var/folders/s3/w6wtrhjs4954xv7xsgyddngw0000gq/T/itms-11705-34224-xnk9fm/mybundle.itmsp - Error Messages:
		ERROR ITMS-90680: "The binary you uploaded was invalid."
		ERROR ITMS-90087: "Unsupported Architectures. The executable for ABCApp.app/app/tns_modules/nativescript-background-http/node_modules/tns-core-modules/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework contains unsupported architectures '[x86_64, i386]'."
		ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'org.nativescript.TNSWidgets' under the iOS application 'ABCApp.app'."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'ABCApp.app/app/tns_modules/nativescript-background-http/node_modules/tns-core-modules/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/TNSWidgets' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."
Command /Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/bin/iTMSTransporter failed with exit code 1
