### ISSUE TITLE
Is there a CSS support for border-style: dashed

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#3246]
![orders](https://cloud.githubusercontent.com/assets/10844041/20919263/e89682b2-bbc0-11e6-8a44-60f608bd95f7.PNG)

I tried this code 
```
<GridLayout rows="*,*,*" columns="*,*" class="firstRow p-20">
    <Label text="Upload Prescription" textWrap="true" row="0" colSpan="2" horizontalAlignment="center" class="m-b-20"></Label>
    <Label text="&#xf093;" textWrap="true" row="2" col="0" horizontalAlignment="center" class="example m-t-20 t-30" ></Label>
    <Label text="&#xf030;" textWrap="true" row="2" col="1" horizontalAlignment="center" class="example m-t-20 t-30" ></Label>
</GridLayout>

.firstRow{
    border-width: 1;
    border-color: #ababab;
    border-style: dashed;
}

```

**Comment by NickIliev** [comment]
Hey @dhanalakshmitawwa 

NativeScript supports a subset of CSS. That said some of the CSS used in web is not applicable.
As of this moment, the border in NativeScript does not support _border-style_ property.

These are the supported border properties in NativeScript 
```

CSS Property	JavaScript        Property Description
border-color	borderColor	Sets a border color to the matched view’s.
border-width	borderWidth	Sets a border width to the matched view’s.
border-radius	borderRadius	Sets a border radius to the matched view’s.
```

Full list of supported properties can be found [here](http://docs.nativescript.org/ui/styling#supported-css-properties)

**Comment by dhanalakshmitawwa** [comment]
Thank you for reply

**Comment by venu2017** [comment]
Hi,
I have written temporary solution for dahsed line in my NS project, which is as follows:

XML code:

<Label  [text]="dashedLine" textWrap="false" marginTop="30%"  id="dashedLine" class="dashed-line" paddingTop="20" paddingBottom="10"></Label> 

Code behind:

for (var i = 0; i < platformModule.screen.mainScreen.widthPixels; i++) {
			this.dashedLine += '-';
		}
		this.dashedLine = this.dashedLine.split('').splice(20, this.dashedLine.length - 20).join(' ');
