### ISSUE TITLE
code for the tabview as shown in image

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#3247]
![image](https://cloud.githubusercontent.com/assets/10844041/20922251/80c548dc-bbcd-11e6-9832-3e8368109904.png)

**Comment by NickIliev** [comment]
Hey @dhanalakshmitawwa

I would recommend posting similar questions in [StackOverflow](http://stackoverflow.com/questions/tagged/nativescript) or similar channels.

For your scenario, using [tab-view](http://docs.nativescript.org/cookbook/ui/tab-view) along with[ list-view](http://docs.nativescript.org/cookbook/ui/list-view) will do the trick

**Comment by dhanalakshmitawwa** [comment]
thank you for reply
