### ISSUE TITLE
tns prepare android Bus error: 10  and 

### ISSUE THREAD

**Issue by YouYII** [NativeScript/NativeScript#3252]
**Android app can not run properly.**

**tns_modules only a small amount of the module.**
> $ ls platforms/android/src/main/assets/app/tns_modules/
> common                   core                     http                     platform-browser-dynamic
> compiler                 forms                    platform-browser         router

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.4.1
- Cross-platform modules: 2.4.0 and 2.4.1
- Runtime(s): tns-android

### Please tell us how to recreate the issue in as much detail as possible.
After install  [firebase](https://github.com/EddyVerbruggen/nativescript-plugin-firebase)  , can not run project on android ,then uninstall this plugin.

May be related to the issue : https://github.com/NativeScript/nativescript-cli/issues/637

**Comment by YouYII** [comment]
I encountered this problem again

> $ ls platforms/android/src/main/assets/app/tns_modules/
> common                   core                     http                     platform-browser-dynamic
> compiler                 forms                    platform-browser         router

Run android project
> An uncaught Exception occurred on "main" thread.
> java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
> 
> Error calling module function 
> 
> Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular/platform", relative to: app/tns_modules/
    > com.tns.Module.resolvePathHelper(Module.java:159)
    > com.tns.Module.resolvePath(Module.java:60)
    > com.tns.Runtime.runModule(Native Method)
    > com.tns.Runtime.runModule(Runtime.java:514)
    > com.tns.Runtime.run(Runtime.java:509)
    > com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    > android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
    > android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
    > android.app.ActivityThread.access$1500(ActivityThread.java:144)
    > android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
    > android.os.Handler.dispatchMessage(Handler.java:102)


I tried the following command
> $ rm -rf node_modules && rm -rf platform 
> $ tns prepare android
> Copying template files...
> Project successfully created.
> Executing before-prepare hook from /Users/zy/Workspaces/EasyReader/hooks/before-prepare/nativescript-dev-android-snapshot.js
> Executing before-prepare hook from /Users/zy/Workspaces/EasyReader/hooks/before-prepare/nativescript-dev-sass.js
> Executing before-prepare hook from /Users/zy/Workspaces/EasyReader/hooks/before-prepare/nativescript-dev-typescript.js
> Found peer TypeScript 2.1.1
> Bus error: 10
> $ tns run android

But wrong again.This problem has been bothering me for two days...

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#2326
