### ISSUE TITLE
tns livesync ios --watch --emulator doesn't watch html or sass changes, only ts

### ISSUE THREAD

**Issue by tskweres** [NativeScript/NativeScript#3256]
When I run tns livesync ios --watch --emulator, the project only compiles and relaunches on ts changes, not sass or html files. 

**I see in the console:**

Executing before-prepare hook from /Users/tskweres/Dev/MyApp/hooks/before-prepare/nativescript-dev-android-snapshot.js
Executing before-prepare hook from /Users/tskweres/Dev/MyApp/hooks/before-prepare/nativescript-dev-sass.js
Executing before-prepare hook from /Users/tskweres/Dev/MyApp/hooks/before-prepare/nativescript-dev-typescript.js
Project successfully prepared (ios)
Executing after-prepare hook from /Users/tskweres/Dev/MyApp/hooks/after-prepare/nativescript-dev-android-snapshot.js
Executing after-prepare hook from /Users/tskweres/Dev/MyApp/hooks/after-prepare/nativescript-dev-sass.js
Transferring project files...
Successfully transferred all files.
Applying changes...
Successfully synced application org.nativescript.MyApp on device DB835084-D28C-4974-95D1-119D23761C75.

But no relaunch.

**I'm running nativescript 2.4**

**package.json:**

{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.MyApp",
    "tns-ios": {
      "version": "2.4.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/core": "2.1.2",
    "@angular/forms": "2.1.2",
    "@angular/http": "2.1.2",
    "@angular/platform-browser": "2.1.2",
    "@angular/platform-browser-dynamic": "2.1.2",
    "@angular/router": "3.1.2",
    "nativescript-angular": "1.1.3",
    "nativescript-slides": "^2.2.4",
    "nativescript-theme-core": "^0.2.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "^2.5.0-2016-11-21-4821"
  },
  "devDependencies": {
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-sass": "^0.4.1",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^2.0.10",
    "zone.js": "~0.6.21"
  }
}

**Simulator:**
Version 10.0 (SimulatorApp-700.14)

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-cli#2325
