### ISSUE TITLE
how to handle android back  key down ?

### ISSUE THREAD

**Issue by Leo-lay** [NativeScript/NativeScript#3259]
Hi,guys.
  I want to listen to the android return button, in my app home page, press the back button when I want to do some operations, and then exit the app。
  then,how can i handle the key down event?

**Comment by terhoraj** [comment]
var applicationModule = require("application");
var AndroidApplication = applicationModule.android;
var activity = AndroidApplication.foregroundActivity;

On for example navigatedTo function:
`activity = AndroidApplication.foregroundActivity;
activity.onBackPressed = function () {
        /* Do something */
};`

**Comment by tsonevn** [comment]
Hi @Leo-lay,

You could review the article [here](http://fluentreports.com/blog/?p=261) , where has been shown, how to capture back Button for Android in NativeScript application. In the article has been given examples for this case.

Hope this helps

**Comment by bhargavakrishna** [comment]
thanks..
