### ISSUE TITLE
getting payments using PayPal

### ISSUE THREAD

**Issue by sulhome** [NativeScript/NativeScript#3267]
I am trying to build a phone app and I am considering NativeScript however I am unable to find plugins for taking payments using paypal on Android and ios. There is [one](https://www.npmjs.com/package/nativescript-paypal) unoffical plugin that works only on Android. For such important functionality I wonder if there is an official plugin from NativeScript and if not what are my options? 

thank you

**Comment by NickIliev** [comment]
Hey @sulhome there is no official plugin developed for Paypal payments, however as NativeScript is open source product a lot of the plugins are developed by the community (including the one you have come across which provide the Android implementation).
If that plugin does not suites your needs then one possible option is[ to create your own plugin](http://docs.nativescript.org/plugins/plugins) using the [Paypal SDKs](https://developer.paypal.com/docs/classic/mobile/gs_MPL/).

There is also [a plugin for in-app purchases](https://www.npmjs.com/package/nativescript-purchase) that supports both iOS and Android

**Comment by NickIliev** [comment]
@sulhome 

Even easier scenario is to use [PaypalMPL CocoaPod](https://cocoapods.org/pods/PayPalMPL) which you can include in your NativeScript project and then you will have access to the native API. More about this option [here](http://docs.nativescript.org/plugins/cocoapods)

**Comment by sulhome** [comment]
@NickIliev thank you for your help

**Comment by NickIliev** [comment]
For anyone interested in Paypal payments - there are two community driven plugins

https://market.nativescript.org/plugins/nativescript-paypal-checkout

https://market.nativescript.org/plugins/nativescript-paypal
