### ISSUE TITLE
Android - View flickering before animations start

### ISSUE THREAD

**Issue by bnussey** [NativeScript/NativeScript#3269]
I'm experiencing issues with animations and views that directly inherit from Android views, for example `nativescript-videoplayer` (https://github.com/bradmartin/nativescript-videoplayer/blob/master/videoplayer.android.ts). What happens is just before the animation is about to start, the view flickers and disappears a second. It re-appears as the animation begins. The odd thing is that the animation is not to this view, but another on the page.

This occurs in some scenarios on the emulator and in all cases on a device.

I've investigated and made sure its not CPU related.

Is there something that needs to be applied to these views that is needed before/after animations to ensure they do not disappear momentarily? I've explored a few topics on stackoverflow and apparently this is a known issue.

I've also looked at https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/animation/animation.android.ts but can't see anything specific here.

Any ideas?

**Comment by tsonevn** [comment]
Hi @bnussey,

I tested the given scenario with the `nativescript-viedoplayer` and indeed there is a problem, when you try to animate this component on Android. However in my opinion, this has been related with some limitations of the Android `VideoView` component. [Here ](http://blog.brightinventions.pl/frame-video-view/) I found an article, where has been described, how to avoid flickering and black screen issues, while using `VideoView`. 

One possible workaround is to use some placeholder with the same `backgroundColor` or `Image` as this on the video and to show and hide it during the animation. Another suggestion from the articles is to use `TextureView` for the plugin, which  provides a lot better performance than `VideoView`. I am attaching sample code, where has been shown one possible workaround. It is not the best approach , however it will working suggestion .


main-page.xml
```
<Page 
  xmlns="http://schemas.nativescript.org/tns.xsd" 
  xmlns:Video="nativescript-videoplayer" loaded="pageLoaded">
  <ActionBar title="Native Video" />
      <StackLayout>
          <Button text="Animation" tap="animate" />
          <Label text="Label On Top of Video View" color="#fff" horizontalAlignment="center" />
          <GridLayout id="grid" backgroundColor="green">
              <ContentView row="0" col="0" id="idContentView" height="180" backgroundColor="black"></ContentView>
              <Video:Video  row="0" col="0" id="nativeVideoPlayer" controls="true" finished="{{ videoFinished }}" loop="true" autoplay="false" height="280" src="~/videos/big_buck_bunny.mp4" />
          </GridLayout>
       </StackLayout>
</Page>
```
main-page.ts
```
import { Page } from 'ui/page';
import { EventData } from 'data/observable';
import { HelloWorldModel } from './main-view-model';
import { isAndroid, device } from "platform";
import { Color } from "color";
import { topmost } from "ui/frame";
var app = require("application");
import { Video } from 'nativescript-videoplayer';
import {AnimationCurve} from "ui/enums";
import {StackLayout} from "ui/layouts/stack-layout";
import {ContentView} from "ui/content-view"
let page;

export function pageLoaded(args: EventData) {
    page = <Page>args.object;
    
    page.bindingContext = new HelloWorldModel(page);
    
    if (isAndroid && device.sdkVersion >= "21") {
        let window = app.android.startActivity.getWindow();
        window.setStatusBarColor(new Color("#d32f2f").android);
        
    }
    var view:ContentView = <ContentView> page.getViewById("idContentView");
    view.visibility="collapsed";

}

export function animate(){
    var videoplayer:Video = <Video>page.getViewById("nativeVideoPlayer");
    var view:ContentView = <ContentView> page.getViewById("idContentView");
    if(isAndroid){
        view.visibility="visible";
        videoplayer.visibility="collapsed";

        setTimeout(function(){
            view.animate({
                translate: { x: 0, y: 100 },
                duration: 1000,
                curve: AnimationCurve.cubicBezier(0.1, 0.1, 0.1, 1)
            }).then(function(){
                view.visibility="collapsed";
                videoplayer.translateY=100;
                videoplayer.visibility="visible";
                videoplayer.play();
            });
        }, 2000)
    }
    else{
        setTimeout(function(){
            videoplayer.animate({
                translate: { x: 0, y: 100 },
                duration: 1000,
                curve: AnimationCurve.cubicBezier(0.1, 0.1, 0.1, 1)
            }).then(function(){
                view.visibility="collapsed";
                videoplayer.translateY=100;
                videoplayer.visibility="visible";
                videoplayer.play();
            });
        });
    
    }
}
```

Hope this helps

**Comment by bnussey** [comment]
Hey @tsonevn can't thank you enough for the detailed response. This is some excellent information that will be very helpful.

The only consideration that I wanted to highlight was that this issue occurs even when not animating the videoview itself, it occurs when animating anything else on the page.. Do you think that changes things at all?

**Comment by bnussey** [comment]
Ok further testing and you're absolutely right, we're going to move to a `TextureView`
