### ISSUE TITLE
itemTap support for Repeater

### ISSUE THREAD

**Issue by oscar-78** [NativeScript/NativeScript#327]
Just as in the ListView would it be possible to have itemTap support for the Repeater?.

**Comment by enchev** [comment]
You can assign tap gesture for the component defined in itemTemplate. For example:
```XML
 <Page>
<ScrollView>
   <Repeater items="{{ myItems }}">
     <Repeater.itemsLayout>
        <WrapLayout />
     </Repeater.itemsLayout>
     <Repeater.itemTemplate>
        <Label text="{{ name }}" margin="10" tap="myTapFunction" />
     </Repeater.itemTemplate>
   </Repeater>
  </ScrollView>
 </Page>
```
```JavaScript
var view = require("ui/core/view");
function pageLoaded(args) {
    var page = args.object;
    page.bindingContext = { myItems: [{ name: "Name1" }, { name: "Name2" }, { name: "Name3" }] };
}
exports.pageLoaded = pageLoaded;

function myTapFunction(args) {
    //
}
exports.myTapFunction = myTapFunction;
```

**Comment by oscar-78** [comment]
But how would I then know which item was tapped?

**Comment by enchev** [comment]
@oscar-78 Can you post more info why you need this index? You can access the data-item (bindingContext) to bind properties, event or gesture handlers, etc.

**Comment by oscar-78** [comment]
I needed an ID to repopulate the Repeater with other items.

But as you mentioned as well I solved it by binding the properties to the component in the itemTemplate and accessing this using the `args.view` in the tap event handler.

Thanks.

**Comment by hekigan** [comment]
I would like to re-open this issue.

My project involve having a gallery-type of layout (grid) and I need to do a multi-selection on tap (to select which items to do a batch action on).

Typically the source is an ObservableArray.
Using data-item is a no go for me as I do not have IDs for my items. I just want to rely on the ObservableArray's index.

Given that the repeater's source is the ObservableArray and that with the ListView it's possible to access the index, why is not the same with the Repeater element?

Any simple way out to solve this issue?

**Comment by leocaseiro** [comment]
Thanks @oscar-78, I took a while to make it work, so here we go:

```javascript
exports.onTap = function(args) {
    var item = args.view.bindingContext;
    console.log('item.id', item.get('id'));
};
```
