### ISSUE TITLE
Animation set promise resolves before animation is complete

### ISSUE THREAD

**Issue by gla5001** [NativeScript/NativeScript#3271]
If creating an animation set and playing sequentially, promise resolves before animation is complete

Trying to write a simple app in iOS (for now) to see how this works out.
Using version 2.4.1 and Angular2

I am creating an array of images to place in an AbsoluteLayout container. I would like these images to slide in one at a time. I loop over and as I am creating the images i also create an animationSet. Once the loop is finished, i play the animations sequentially the promise resolves before the animation has completes. I would expect the promise to resolve AFTER ALL animations have completed, but this is not the case. I need to do stuff after the animation set has completed. I am doing something like

```
let absoluteArea = <AbsoluteLayout>this.page.getViewById('absoluteArea'),
       animationSet = [];

        for (let i = 0; i < 100; i++) {
            let newImage = new Image();
            newImage.style.backgroundImage = some.jpg;
            newImage.width = width;
            newImage.height = height;

            AbsoluteLayout.setLeft(newImage, leftPosition);
            AbsoluteLayout.setTop(newImage, centerTopPosition);

            animationSet.push({target: newImage, translate: {x: tranlatedLeftPosition, y: 0}, duration: 75 });

            absoluteArea.addChild(newImage);
        }

        animationAction = new Animation(animationSet, true);
        animationAction.play()
            .then(() => {
                console.log('DONE');
            })
            .catch((err) => {
                console.log('Animation set error', err);
            });
```

The console log 'DONE' will get logged long before the animation completes.

**Comment by tsonevn** [comment]
Hi @gla5001,
Thank you for contacting us.

I reviewed your case and confirm that the `Promise` will be fired at the end of the first `Animation` and `DONE` will be logged earlier. We will research further this behavior and will check if it is possible to be fixed in some of the future `NativeScript` versions. In the meantime, you could use `setTimeout` with the `duration` and number of the `items` in the array or to run animation for every view as it has been shown [here](https://docs.nativescript.org/ui/animation-css.html#access-css-animations-from-code). I am also attaching sample code for my first suggestion.

main-page.xml

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
    <AbsoluteLayout id="absid">
    </AbsoluteLayout>
</Page>
```

main-page.ts

```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import {AbsoluteLayout} from "ui/layouts/absolute-layout";
import {Image} from "ui/image"
import {AnimationCurve} from "ui/enums";
import {Animation, AnimationDefinition} from "ui/animation";
import {KeyframeAnimation} from "ui/animation/keyframe-animation";
import {Label} from "ui/label"

export function navigatingTo(args: EventData) {

    let page = <Page>args.object;
    var animationSet:Array<AnimationDefinition> = [];
    var absoluteArea:AbsoluteLayout =<AbsoluteLayout> page.getViewById("absid");
    var centerTopPosition = 10;

        for (let i = 0; i < 7; i++) {
            let newImage = new Image();
            newImage.style.backgroundImage = "~/images/icon.png";
            newImage.width = 70;
            newImage.height = 70;

            AbsoluteLayout.setLeft(newImage, 150);
            AbsoluteLayout.setTop(newImage, centerTopPosition);
            
             animationSet.push({target: newImage, translate: {x: 100, y: 0}, duration: 75 });

            absoluteArea.addChild(newImage);
            centerTopPosition=centerTopPosition+70;
        }

       var  animationAction = new Animation(animationSet, true);


        setTimeout(function() {
            animationAction.play()
                    .then(() => {
                        setTimeout(function() {
                            console.log('DONE');
                        }, 75*7);
                        

                    })
                    .catch((err) => {
                        console.log('Animation set error', err);
                    });
        }, 2000);
}
```


Hope this helps.

**Comment by gla5001** [comment]
@tsonevn This helps for the time being. Thanks!

**Comment by prolink007** [comment]
Status of this bug? I am seeing the same issue.

**Comment by tsonevn** [comment]
Hi @prolink007, 
This issue is still under review, we will review what is causing this problem after the 3.1 release, however, I could not commit to the exact date, when this will be fixed.

**Comment by tsonevn** [comment]
no longer reproducible with modules 4.1.
