### ISSUE TITLE
Button background has a transparency effect

### ISSUE THREAD

**Issue by rwngallego** [NativeScript/NativeScript#3272]
When I try to set the background color of a button it's having a transparency effect and the color is not the real one, it's faded. However when I press and hold the button the color is displayed as it should. It's creating misleading button colors in all over the project. How can I remove that transparency?

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.4.1
- Cross-platform modules: 
    "@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/core": "2.1.2",
    "@angular/forms": "2.1.2",
    "@angular/http": "2.1.2",
    "@angular/platform-browser": "2.1.2",
    "@angular/platform-browser-dynamic": "2.1.2",
    "@angular/router": "3.1.2",
    "nativescript-angular": "1.1.2",
    "nativescript-telerik-ui": "^1.5.1",
    "nativescript-theme-core": "^0.1.3",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "^2.4.1"
- Runtime(s): 2.4.1
- Plugin(s): none

### Please tell us how to recreate the issue in as much detail as possible.
````
In the HTML:
<Button text="OPEN DRAWER" (tap)=openDrawer()></Button>

In the CSS:
Button{
    background-color: red;
}
````
Normal button:
![button_normal](https://cloud.githubusercontent.com/assets/691521/21071269/a3d6fdcc-be69-11e6-9eb4-48b886d49d81.png)

Pressed and held:
![button_hold](https://cloud.githubusercontent.com/assets/691521/21071270/aa353166-be69-11e6-8f40-3eabdaf91a7b.png)

**Comment by tsonevn** [comment]
Hi @rwngallego,
Thank you for your interest in NativeScript.
I tested your scenario and on my side everything seems to work as expected and the `Button` `background-color` has been applied as expected. This behavior could be related with some another style set in your project CSS file. it would help if you could give us some more info about the problem or if you could send us sample project, which could be debugged locally. 

Thank you for your cooperation in advance.
Regards,
@tsonevn

**Comment by dhanalakshmitawwa** [comment]
Hi @rwngallego  , 

In css place border-radius - 1;
.Button{
    background-color: red;
    border-radius: 1;
    margin: 10
}

**Comment by rwngallego** [comment]
@dhanalakshmitawwa Yes, using border-radius: 1 did the trick. However if this is going to be the desired behavior we should need to add this to the docs in the Button section.

**Comment by danielgek** [comment]
@tsonevn @dhanalakshmitawwa i don't like that much of the `border-radius: 1;` because on more recent versions of android this makes the button loose the ripple effect

**Comment by tsonevn** [comment]
Hi @danielgek,
For the ripple effect you could use `nativescript-ripple` plugin and for further help you could review the demo app [here](https://github.com/bradmartin/nativescript-ripple).

Hope this helps.

**Comment by danielgek** [comment]
@tsonevn i do know that plugin, but it would be nice if {N} handle it out of the box xD i'm not complaining, it's just an opinion ;)

**Comment by leonardocaldas** [comment]
Any news on this bug?

**Comment by tsonevn** [comment]
the issue with the `background-color` is not reproducible with modules 4.1
