### ISSUE TITLE
Having issue pushing app to ios app store

### ISSUE THREAD

**Issue by codyboaz** [NativeScript/NativeScript#3275]
Hey can anyone please help me with this issue?

I have been able to push my app to the app store once but now am having issues.

I am getting this response from the itunes team

Invalid Bundle - Ensure that app executables and bundled frameworks use consistent architectures
Once these issues have been corrected, you can then redeliver the corrected binary.

I have added the nativescript-estimote-sdk and NativeScript WebSockets plugin.

Any advice would be greatly appreciated.

**Comment by tsonevn** [comment]
Hi @codyboaz,
Thank you for your interest in NativeScript. 

Could you give us some more info about the steps, you are following to  publish the app. In the mean time could you try to build in release mode using `tns publish ios` command as it is described in the documentation [here](http://docs.nativescript.org/publishing/publishing-ios-apps#builds).


Hope this helps.

**Comment by NickIliev** [comment]
@codyboaz please post your **package.json** content

**Comment by NickIliev** [comment]
Hey @codyboaz haven't heard from you for a while... have you managed to resolve your issue!?
