### ISSUE TITLE
Enhancement: Namespace Imports

### ISSUE THREAD

**Issue by vbresults** [NativeScript/NativeScript#3276]
This is a namespace play on #2986, so `xmlns:` attributes do a `global.loadModule` instead of trying to load a file.  Without this, you can't plug modules like Telerik UI when using webpack.

Considering that webpack is slated to be enabled by default in 2.5, this is critical.  If you point me to the right place I will make a PR -- I can't figure out where the actual include for `xml.ts`.

Ping @hdeshev @enchev

**Comment by enchev** [comment]
Hey @vbresults,

You can find the code here:
https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/builder/component-builder.ts#L54-L69

**Comment by vbresults** [comment]
@enchev Looks like it already does what's needed, it just falls back to the file version if the module isn't registered; closing (:
