### ISSUE TITLE
send push notification to subscribers of a topic

### ISSUE THREAD

**Issue by macnux** [NativeScript/NativeScript#3277]
just i want to know if nativescript capable of send push notification to subscribers of a topic
i checked this plugin but i found nothing related to what i need
[push-plugin](https://github.com/NativeScript/push-plugin)

just asking if nativescirpt supports send push notification to subscribers of a topic

thanks in advance.

**Comment by NickIliev** [comment]
Hello @macnux

NativeScript has no problem to support PN to subscribers of topics - the thing is that the plugin you have mentioned has not implemented this feature at this moment. A request for enhancement has been logged [here](https://github.com/NativeScript/push-plugin/issues/28). A [similar thread](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/164) is opened in nativescript-plugin-firebase where this is also logged as a feature. 

At this moment what you can do is to create your own implementation of one of those plugins and implement the topic feature or create a PR with the implementation code and be a part of the contributors for the plugin. You can also upvote this issue [here ](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/81)and get in touch with the author for possible ideas/workarounds.

**Comment by macnux** [comment]
Hello @NickIliev 
i think that nativescript and its plugins still in early product that i cannot rely on  and i have to use native languages (java - swift)

thanks for reply @NickIliev

**Comment by NickIliev** [comment]
@macnux You can use the native APIs (both iOS and Android) in NativeScript. Android article on the matter [here](http://docs.nativescript.org/runtimes/android/marshalling/java-to-js).
