### ISSUE TITLE
ListView disappear 

### ISSUE THREAD

**Issue by CodeXtinction** [NativeScript/NativeScript#3278]
hello, i have a issue with physical back button, when i select an element from the list to navigate to another view and then press back button the list disappears, the list loads on  ngOnInit and i get  an object from sqlite, but when the list view loads with back button it seems the object does not exist ,any idea why this happen?

Android
Nativescript + Angular 2 

![](http://k60.kn3.net/F/D/9/E/C/6/B35.png)

![](http://k60.kn3.net/8/D/C/E/5/C/47F.png)

**Comment by tsonevn** [comment]
Hi @CodeXtinction,
Thank you for contacting us, 

I reviewed your case, however was unable to reproduce such a problem. Could you send us some more info about your environment(`CLI`, `tns-core-modules`, `node versions`) and your problem. It would help also, if you could send us sample project, which could be debugged locally. For your convenience I am attaching [link ](https://github.com/tsonevn/NGRouterSample) to a sample project.

Hope this helps

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#587
