### ISSUE TITLE
Failed to find module: "platform", relative to: /app/tns_modules/

### ISSUE THREAD

**Issue by v-r-sankar** [NativeScript/NativeScript#3281]
I am trying to run my first native script app, but facing the problem 
Failed to find module: "platform", relative to: /app/tns_modules/

The problem is reported  here https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/224
but no solutions. I've attached screenshot there.

output of tns info attached.

![image](https://cloud.githubusercontent.com/assets/3470205/21093514/3aeeec3c-c078-11e6-9fbf-6e8895c90874.png)

**Comment by valentinstoychev** [comment]
Thank you for your report. Are you following the Groceries getting started article? Or you are adding the firebase plugin manually in a separate app?

**Comment by v-r-sankar** [comment]
I was just following groceries article, not using any firebase plugin. I dint realize at first that the issue was reported in firebase plugin. So I added the issue here.

**Comment by valentinstoychev** [comment]
Thanks @v-r-sankar. We are looking into this.

**Comment by v-r-sankar** [comment]
I removed the platforms folder and started android emulator externally.. After adding platform back, it worked fine..
