### ISSUE TITLE
can u give me the css code for tabview  to get screen like below 

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#3288]
![image](https://cloud.githubusercontent.com/assets/10844041/21136371/6ce80574-c14b-11e6-9f95-0499074aa842.png)

**Comment by tsonevn** [comment]
Hi @dhanalakshmitawwa,
For styling your `TabView` you could use the properties described in the comment of [this ](https://github.com/NativeScript/NativeScript/issues/2738#issuecomment-255745605) issue. For the main view you could use `GridLayout` and to specify the `borderWidth`, `borderColor` and `borderRadius` properties.
Please report only real issues here and use [StackOverflow ](http://stackoverflow.com/questions/tagged/nativescript)or Slack for general questions. You could join the NativeScript Community on Slack, by using the registration form in our[ web site](https://www.nativescript.org/) .
Regards,
@tsonevn

**Comment by dhanalakshmitawwa** [comment]
Thank you for reply
