### ISSUE TITLE
Change the way platform specific css works

### ISSUE THREAD

**Issue by mdgiles** [NativeScript/NativeScript#329]
I know that you can have app.ios.css and app.android.css.  I think that these should be used to add to or override classes already defined in app.css, rather than both being complete replacements for app.css, since a large proportion of styling is common to both platforms.

**Comment by hshristov** [comment]
Hi @mdgiles,

It is our build process that overwrite app.css based on the platform you are building/preparing. But you should be able to use @import in the css file.
