### ISSUE TITLE
iOS http-request

### ISSUE THREAD

**Issue by rLoka** [NativeScript/NativeScript#3292]
When running on iOS, I get the following message:

`Error {message: "The resource could not be loaded because the App T…y policy requires the use of a secure connection.", line: 40, column: 37, sourceURL: "file:///app/tns_modules/http/http-request.js", stack: "file:///app/tns_modules/http/http-request.js:40:37…e]`

It seems that this is linked with Apple security policies:
http://stackoverflow.com/questions/32631184/the-resource-could-not-be-loaded-because-the-app-transport-security-policy-requi

**Comment by tsonevn** [comment]
Hi @rLoka,
The `http` request has been forbidden by default. To be able to make such a request you could include the following lines in your `<project_name>/app/iOS/Info.plist ` file, which will allow this functionality. 
```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```
For further instructions you could review this [thread](http://stackoverflow.com/questions/30731785/how-do-i-load-an-http-url-with-app-transport-security-enabled-in-ios-9) in StackOverflow.


Hope this helps.

**Comment by divyachandana** [comment]
@tsonevn Thanks alot my issue fixed
