### ISSUE TITLE
App closing after click in OK on dialog

### ISSUE THREAD

**Issue by betosalvador** [NativeScript/NativeScript#3293]
Hello.

I just create a new app, using tns 2.4.1 and add the code bellow to the default onTap() method.
alert("Click!"); 

But, after I click on "OK", the app is closed.

I run on Androids 4.1.3 and 4.4.4.,

Is this a normal behavior on dialogs?

Thanks in advance!

**Comment by betosalvador** [comment]
I'm closing this issue, because for some reason, after I closed and open, and rebuild everything, the app is not closing after click on Ok anymore

**Comment by betosalvador** [comment]
Hello.

I'm having the same problem again, but this time only happens on android 4.2.2.

I'm testing using a simulator of Galaxy Note 2.

Is anyone having this problem too?

Thanks in advance.

**Comment by NickIliev** [comment]
Hi @betosalvador 

I have tested the described scenario on Android API19 (4.4.4) and on API17(4.2.2) but was not able to reproduce this issue. [Here](https://github.com/NickIliev/NativeScript-issues/tree/master/NativeScript/issue_3293) you can find the test project I 've made (perhaps you can try it at your side). Please share more detailed code to help us investigate and eventually reproduce the potential problem.

**Comment by betosalvador** [comment]
Hi @NickIliev .

Thanks for response,

I just don't know what can be happening.

I downloaded your code and build it to android and I got the same problem on android 4.2.2.

My TNS version is 2.4.1.

You're using this version for local testing?

Thanks in advance

**Comment by NickIliev** [comment]
tested with 2.4.2 and with @next (2.5.0-next-2016-12-14-1505). 
Perhaps you can try installing our latest or next release
```
npm uninstall -g nativescript
npm install -g nativescript@next  // or just nativescript for 2.4.2
```
You mentioned you are using an emulator for Samsung Galaxy. Have you tried on a different emulator (same API level)? Also in case you are using Genymotion - can you try on AVD created emulator as well?

**Comment by betosalvador** [comment]
Hello @NickIliev .

I will do the tests suggested by you.

Thank you very much for your attention.
