### ISSUE TITLE
Rotate does not work as CSS property in Android

### ISSUE THREAD

**Issue by bnussey** [NativeScript/NativeScript#3294]
On iOS, this works but on Android it does not, have to manually rotate.

```
.rotate90 {
    rotate: 90;
}
```

**Comment by tsonevn** [comment]
Hi @bnussey,
I was able to reproduce this behavior, while using Image and setting `rotate` property to the component via CSS. This problem has been reproduced only on Android. In the meantime you could set this property inline in the XML, which will work as expected on both iOS and Android. I am attaching also sample code, which I used for testing.

`main-page.xml`
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
    <StackLayout class="p-20" >
        <Image class="rotate90" width="70" height="70" src="res://icon" stretch ="none" />       
    </StackLayout>
</Page>
```

`app.css`

```
.rotate90 {
    rotate: 90;
}
```

Regards,
@tsonevn

**Comment by bnussey** [comment]
Hey @tsonevn yep no problems thanks for that. Will do in line as a temporary fix.

**Comment by tsonevn** [comment]
the issue is no longer reproducible with modules 4.1
