### ISSUE TITLE
issue in the docs (fix inside)

### ISSUE THREAD

**Issue by SamuelGRwebfab** [NativeScript/NativeScript#3307]
I noticed this page of the docs is incorrect https://docs.nativescript.org/angular/cookbook/tab-view-ng.html#binding-two-way-tabview-selectedindex

using `[(ngModel)]="tabSelectedIndex"` throws an error and crashes the app, what needs to be done is this `[selectedIndex]="tabSelectedIndex"`

just a small change, didn't notice anything else wrong.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/docs#630
