### ISSUE TITLE
Navigate inside modal?

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#3308]
**Platform:** iOS
**TNS:** 2.4.0

Is it possible to navigate inside a modal somehow? Neither `frame.navigate()` or `page.showModal()` does the job as far as I'm concerned.

Thanks in advance!

**Comment by NickIliev** [comment]
You can't navigate inside a modal page but you can navigate to other page after the closeCallback is called.
Think of the modal page as an extension of the current page you have triggered it.
For example if you have page-A which open modal-A then you can not trigger loaded or navigatedTo callbacks for you modal as there are already triggered from page-A.
So you onlyoption is to navigate with the closeCallback.

Note that if you use topmost() withi your modal page it will be triggered but only after the close call back is called. For example:

```
<Button text="go to third page" tap="onSetReturnPage" />
<Button text="onCloseModal" tap="onCloseModal" />

export function onSetReturnPage() {
    // this will navigate as expected but will be visible only after the modal is closed with closeCallback
    topmost().navigate({
        moduleName: "third-page",
    });
}

export function onCloseModal() {
    closeCallback();
}
```

Of course, as a solution you can use tab-view and simulate navigation with showing the selected tabs. Or following that thought you can create segmented-bar with hiding block for content and again "simulate" navigation.

**Comment by NordlingArt** [comment]
@NickIliev - I understand. Thanks! I just made a work-around like you explained 🙂
