### ISSUE TITLE
TabViewItem Title cannot be bound to model

### ISSUE THREAD

**Issue by stonecourier** [NativeScript/NativeScript#331]
Cannot bind to model, does not reflect changes on the screen if you change it programatically.

http://docs.nativescript.org/ApiReference/ui/tab-view/TabViewItem.html

Ideally want it bound to model, so I can do localization like all other views.

**Comment by enchev** [comment]
At the moment data binding will work only for components inherited from View and part of the visual tree. SegmentedBarItem, TabViewItem and other similar are represented as simple JSON name/value storage, they are not part of the visual tree and that is why cannot be bound. Possible way to achieve your goal is to create view-model and bind all items:
```XML
<Page loaded="MyPageLoaded">
  <TabView items="{{ items }}" />
</Page>
```
```JavaScript
function MyPageLoaded(args) {
    var page = args.object;
    var lbl1 = new label.Label();
    lbl1.text = "Label1";
    var lbl2 = new label.Label();
    lbl2.text = "Label2";
    page.bindingContext = { items: [{ title: "Tab 1", view: lbl1 }, { title: "Tab 2", view: lbl2 }] };
}
exports.MyPageLoaded = MyPageLoaded;
```

**Comment by hamorphis** [comment]
https://github.com/NativeScript/NativeScript/issues/541
