### ISSUE TITLE
How to navigate from a webview to nativeapp with some data?

### ISSUE THREAD

**Issue by narender56** [NativeScript/NativeScript#3311]
I have a requirement that i want to navigate from webview to native app, like i have users on map,when i click on a particular user , i have to redirect him to his page with his details.Please can anyone tell me some suggestions.

**Comment by tsonevn** [comment]
Hi @narender56, 
Thank you for your interest in NativeScript.
To be able to open native app from NativeScript application, you could use `openUrl` method from `utils/utils`. For iOS you should also register `<native_app_name>://` in your project `app/App_Resources/iOS/Info.plist`. To do that you should add the following code in `Info.plist`.
```
<key>LSApplicationQueriesSchemes</key>
    <array>
        <string><native_app_name></string>
    </array>
```
I am attaching sample code, where has been shown, how to use `openUrl` method. For further help you could also review [this ](http://stackoverflow.com/questions/38964197/nativescript-launch-another-app-from-nativescript-app) thread in StackOverflow.

main-page.html
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
    <StackLayout class="p-20">
        <Button text="Open app" tap="onTap" class="btn btn-primary btn-active"/>
    </StackLayout>
</Page>
```
main-page.ts
```

 ```import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import {openUrl} from "utils/utils"

export function navigatingTo(args: EventData) {
    let page = <Page>args.object;

    page.bindingContext = new HelloWorldModel();
}
export function onTap(){
    openUrl('waze://?ll=37.44469,-122.15971&z=10');
}
```
About the the communication between the WebView and the Application you could review the article [here](http://shripalsoni.com/blog/nativescript-webview-native-bi-directional-communication/).

Hope this information helps.

**Comment by narender56** [comment]
Hi @tsonevn,

Thanks for the reply, bidirectional example helped me to resolve the issue but i came across a new issue : 

I'm trying to emit an event from webview and catching it in native end and trying to navigate to other native screen(webview --> native screen ).Here we are able navigate first time properly but when we come back on webview and navigate again to the same screen,this time it's navigating twice to the same screen and it keeps incrementing with every iteration.

For Example : If we come back 5th time to webview and try to navigate the same screen so its getting navigated to the same screen 5 times consecutively.

**Comment by tsonevn** [comment]
Hi @narender56,

Thank you for writing us back.

I tested your case, however was unable to reproduce this behavior with navigation. It could be related with the time, when you are making the navigation. 
Could you share some code with us? It will help if you could provide some sample code, which could be debugged locally? 

Regards,
@tsonevn

**Comment by narender56** [comment]
Thanks @tsonevn ,

I resolved it by making some count checks.Its working fine now.
thanks a lot for your help :)

**Comment by NumEmboy** [comment]
Hi @narender56, 

I also encounter the same issue regarding the repeated navigation. How did you manage to resolved it by making some count checks? Thanks in advanced.

**Comment by NumEmboy** [comment]
@narender56 I resolve the issue by also performing some count checks. Thanks a lot for the idea.
