### ISSUE TITLE
Listpickers inside tabviews reset when navigating tabs

### ISSUE THREAD

**Issue by stonecourier** [NativeScript/NativeScript#332]
When you have a listpicker bound to a model, and the list picker is inside a tabview, when you navigate from one tab to another, the listpicker resets (but the model is not affected, the value bound to the selectedindex still remembers what it was). (Experienced this on Android)

**Comment by hshristov** [comment]
@stonecourier which version are you using?

**Comment by stonecourier** [comment]
I was using a Samsung Galaxy Note 4 with android 4.4. But I upgraded the operating system to 5.01 yesterday and the problem no longer occurs.

Nativescript version 1.1
