### ISSUE TITLE
webView.request.URL is undefined for trace and make iOS crash

### ISSUE THREAD

**Issue by AntonioCuevaUrraco** [NativeScript/NativeScript#3328]
```
trace.write("UIWebViewDelegateClass.webViewDidStartLoad(" + webView.request.URL + ")", trace.categories.Debug);
```

### Which platform(s) does your issue occur on?
IOS

### Please provide the following version numbers that your issue occurs with:
This is related only to tns-core-modules: The version affected is 2.2.1 but it doesn't seams to be fixed on the latest tns-core

### Please tell us how to recreate the issue in as much detail as possible.
   I have no idea how to reproduce the issue because is coming form our app on the store. I can not know what the end user is clicking. Just make sure that  webView.request is something before trying to access URL

    "2": "TypeError: null is not an object (evaluating 'webView.request.URL') ",
    "3": "",
    "4": " stackTrace:",
    "5": " webViewDidStartLoad@file:///app/tns_modules/ui/web-view/web-view.js:44:88",
    "6": "UIApplicationMain@[native code]",
    "7": "start@file:///app/tns_modules/application/application.js:233:26",
    "8": "anonymous@file:///app/app.js:154:18",
    "9": "evaluate@[native code]",
    "10": "moduleEvaluation@[native code]",
    "11": "[native code]",
    "12": "promiseReactionJob@[native code]"

**Comment by davecoffin** [comment]
Submitted a PR for a fix for this: https://github.com/NativeScript/NativeScript/pull/4830

**Comment by hshristov** [comment]
@AntonioCuevaUrraco @davecoffin Could you share steps to reproduce the crash so that we can add unit-test?

**Comment by davecoffin** [comment]
Its sort of hard to reproduce, it happens with certain URLs and I'm not sure why. But my fix just in #4830 just brings it in line with how its handled in webViewDidFailLoadWithError further down in the file, it appeared to just be an oversight.

**Comment by hshristov** [comment]
Can you share the URL that you manage to reproduce it?

**Comment by davecoffin** [comment]
Well thats just the thing, that function is being invoked with no URL, thats why its crashing:
https://cl.ly/nBaL
https://cl.ly/nCXz
