### ISSUE TITLE
Provide Browser Polyfills

### ISSUE THREAD

**Issue by opiepj** [NativeScript/NativeScript#3335]
Is there a polyfill for NativeScript (tns-core-modules) for browsers?

If I have an app that needs to deploy to web and mobile, how would I go about that without having two separate code bases?

**Comment by NickIliev** [comment]
Hi @opiepj 

You can take a look at [angular-seed-advanced](https://github.com/NathanWalker/angular-seed-advanced).


> Considering Angular 2 for a large project? Do you need i18n support? Enhanced testing support? Oh and building for multiple platforms too? Web, native Mobile (Android/iOS), and even Desktop (Mac, Windows and Linux)?

**Comment by opiepj** [comment]
The problem is that they move t
