### ISSUE TITLE
Applicatoin crash on Genymotion

### ISSUE THREAD

**Issue by vadag** [NativeScript/NativeScript#3344]
Hello!

### Tell us about the problem
When I do 'tns run android' on genymotion emultator, the app crashes, but runs well on ARM-based AVD and real device.

### Which platform(s) does your issue occur on?
Abdroid

### Please provide the following version numbers that your issue occurs with:
NativeScript: 2.5.0-2016-12-20-7489 (the same was with 2.4.2, updated just to see if the problem will go away with new development version)
tns-core-modules: 2.4.3
tns-android: 2.4.1

### Please tell us how to recreate the issue in as much detail as possible.
I'm using Windows 7 64bit on AMD CPU, Genymotion 2.8.1 with just created empty 6.0.0 - API23 device, VirtualBox 5.0.30, node v6.9.2, npm 3.10.9, Android Studio (with SDKs and tools) was recently updated.

What I did:
1. install nativescript-cli: npm install nativescript
2. create project: tns create simple && cd simple
3. npm install, tns platform add android
4. start genymotion virtual machine (have tried 4.4.4, 5.1.0, 6.0.0)
4. tns run android (or emulate - result the same) and got message "Unfortunately, <app> has stopped".

When I run the same empty new project on real ARM device or ARM AVD - all is fine. As well as in the Nox Player. Can't check on x86 AVD because of host AMD CPU.  

Have tried React Native on the same Geny Virtual Device - everything worked as expected. Cordova apps working too (checked this on new Ionic2 project). 

Attached log files (with __enableVerboseLogging() ) and screenshot of the error.

[full_log.txt](https://github.com/NativeScript/NativeScript/files/667679/full_log.txt)
[logcat.txt](https://github.com/NativeScript/NativeScript/files/667680/logcat.txt)
![device-2016-12-22-100635](https://cloud.githubusercontent.com/assets/3302725/21410808/43917666-c82f-11e6-9302-d5f58a04f281.png)

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

The only change made in the template project - added __enableVerboseLogging();

**Comment by tsonevn** [comment]
Hi @vadag,
Thank you for reporting your problem.

You could try to delete the app from the emulator and to restart the `genymotion` virtual machine. then try to build the app again. This problem could also be caused due to  not enough space on the emulator or if there are not network available. 

However in my further research I found in this [thread ](http://stackoverflow.com/questions/32455645/unfortunately-myapp-has-stopped-no-error-logs-in-logcat#32455752) that `Unfortunately, has stopped` error is common exception , while deploying the app on Android emulator and the solution could be to restart the machine and to test on different emulator.

Let me know, whether this helps.

**Comment by vadag** [comment]
Sorry for taking so long to answer!
Actually, i completely reinstalled SDK, native script client, node_modules and platform (in project folder). Created completely new genymotion machine. But the problem still remains. 
Can't see nothing about RegEx in logs...

**Comment by NickIliev** [comment]
Hey @vadag perhaps, you can try [creating an AVD ](https://docs.nativescript.org/tooling/android-virtual-devices) - if you install HAXM and enable it then the AVDs are much faster and reliable then the Genymotion emulators.

**Comment by vadag** [comment]
Hello @NickIliev! Thanks for suggesting, but unfortunately my PC is AMD based so I can't install HAXM and AVDs without it is very slooow (surely you're aware of it). Currently I'm playing with Nox, everything work fine so far, but it based on 4.4.2 version of Android.

**Comment by mamarilmanson** [comment]
@vadag ~ Can you please teach me how to use Nox App Player? I type `tns device` but it just says "Cannot find connected devices. Reconnect any connected devices, verify that your system recognizes them, and run this command again."

Please help...

**Comment by vadag** [comment]
@mamarilmanson - just try to type "adb connect 127.0.0.1:62001" in terminal and after that tns (as well as adb) should see your device.

**Comment by mamarilmanson** [comment]
Thanks... :D

**Comment by danielmachado1980** [comment]
The same problem here, I have used Nox Player too, the problem is the Geny, any solution?

**Comment by tsonevn** [comment]
Hi @danielmachado1980 
I would suggest trying to create an AVD emulator while following the guidelines [here](https://developer.android.com/studio/run/managing-avds.html). As @NickIliev already mentioned 
> if you install HAXM and enable it then the AVDs are much faster and reliable then the Genymotion emulators.

**Comment by danielmachado1980** [comment]
Thx @tsonevn but I suffer too much with AMD processors limitations, the AVDs run slowly.

**Comment by pauloantonelli** [comment]
i have the same problem and try many solotions but i still stuck!
anyone found any solution of this problem?
