### ISSUE TITLE
isUserInteractionEnabled="false" doesn't work after an app is re-opened 

### ISSUE THREAD

**Issue by TeddyBo** [NativeScript/NativeScript#3345]
Setting the property `isUserInteractionEnabled="false"` for `Button`/`TextField`/`TextView` etc works fine till the application is not switched (or even just Overview button is clicked). After the user comes back to the application this property still remains equal to "false" but the view for which it is specified becomes editable.

### Which platform(s) does your issue occur on?
Android 6, did not check iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.4.0
- Cross-platform modules: 2.4.1
- Runtime(s): 2.4.1

### Please tell us how to recreate the issue in as much detail as possible.
Run an application, press Overview button (third one) and choose the application again

**Comment by tsonevn** [comment]
Hi @TeddyBo,
Thank you for reporting this issue.
I reviewed this case and confirm that this is real problem on Android. When you suspend the app and open it again `isUserInteractionEnabled="false"` will not be applied the the components. I am also attaching sample code, whether the problem could be reproduced.

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
    <StackLayout class="p-20">
        <Label  text="Tap the button" class="h1 text-center"/>
        <Button isUserInteractionEnabled="false" text="TAP" tap="{{ onTap }}" class="btn btn-primary btn-active"/>
        <Label text="{{ message }}" class="h2 text-center" textWrap="true"/>
        <TextField isUserInteractionEnabled="false" hint="" text="Sample text" />
        <TextView isUserInteractionEnabled="false" hint="" text="Sample textview" editable="true" /> 
    </StackLayout>
</Page>

```
As a temporary solution for `TextField ` and `TextView`, you could use `editable` property and to set it to `false` . Example:

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
    <StackLayout class="p-20">
        <TextView text="TextView" editable="false" />
        <TextField  text="TextField" editable="false" />            
    </StackLayout>
</Page>
```

Hope this helps.

**Comment by sivsushruth** [comment]
It also fails if you go back to a page

**Comment by tsonevn** [comment]
the issue is no longer reproducible with modules 4.1
