### ISSUE TITLE
Support UglifyJS

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/NativeScript#3347]
Our CSS implementation relies on discovering classes by name. That breaks when using UglifyJS:

- [x] Fix class name discovery
- [x] Generate UglifyJS mangle exclusion lists for public controls.

**Comment by hdeshev** [comment]
Steps to reproduce:

1. npm install --save-dev nativescript-dev-webpack
2. npm run start-android-bundle --uglify
3. Styles not applied properly. The app looks ugly.

**Comment by NathanaelA** [comment]
This has been an issue that has been around for a while; I reported it almost two years ago.  ;-)

I just looked at your patch; how is that going to help when it is uglified; the CSS is still going to Reference "Page" or "VideoPlayer".    Or is there another patch you didn't reference in this pull request somewhere else that automatically builds an exclusion list for all the _plugins_ and the tns core modules?

**Comment by URvesh109** [comment]
npm run start-android-bundle --uglify

ERROR in bundle.js from UglifyJs
Unexpected token: punc ()) [bundle.js:6432,16]

**Comment by CoericK** [comment]
Im having the same issue after upgrading to angular 5 and webpack 0.9.0, the docs says i can run tns build ios --env.uglify but im getting the error unexpected token: punc())....

**Comment by dtopuzov** [comment]
Hi @CoericK 

Can you reproduce the issue with new hello-world angular app?
Can you also post your package.json?
