### ISSUE TITLE
Image Upload using AWS in nativescript.

### ISSUE THREAD

**Issue by narender56** [NativeScript/NativeScript#3352]
Hello everyone,

Can anybody please help me to upload image in AWS using nativescript ?. I have tried nativescript-aws plugin but it didn't worked for me.

Thanks in  advance.

**Comment by NickIliev** [comment]
@narender56 can you shows us what you have tried so far and what is your stopper!?
Uploading a file to amazon S3 is discussed [here](http://stackoverflow.com/a/37593437/4936697) and also I noticed that nativescript-aws uses the same API as [aws-sdk](https://www.npmjs.com/package/aws-sdk) so you should be able to use almost all if the functionalities listed [here](https://github.com/aws/aws-sdk-js)
