### ISSUE TITLE
"getDrawable()" and "getBitmap()" no longer working for Android

### ISSUE THREAD

**Issue by jiwonyune** [NativeScript/NativeScript#3355]
Hi,

After taking a photo with camera, I want to do some image processing. In order to do that, I need to access its bitmap. For previous versions of tns, "getDrawable()" and "getBitmap()" used to work, but I get error as follows:

```
JS: imageAsset.android: /storage/emulated/0/Android/data/org.nativescript.SRMeter/files/NSIMG_20161225_191319.jpg
JS: imageAsset.android.getDrawable is not a function
```

And this is the code (NS with NG2):

```
camera.takePicture({).
    then((imageAsset) => {
        console.log("Result is an image asset instance");
        var image = new Image();
        image.src = imageAsset;

        console.log("imageAsset.android: " + imageAsset.android);
        console.log("imageAsset.android.getBitmap(): " + imageAsset.android.getDrawable()); // ERROR!
    }).catch((err) => {
        console.log("Error -> " + err.message);
    });
```

Can anyone help me fix this problem? Thanks a lot in advance.

Info:
```
tns --version 2.4.0
tns-android 2.4.2
tns-core-modules 2.4.0

```

**Comment by Pip3r4o** [comment]
@jiwonyune hey, I don't know what dictated the changes to the imageAsset, but as a temporary work-around you could wrap the path manually in a drawable/bitmap and operate on it.

```javascript
var imagePath = imageAsset.android;
var imageAndroidDrawable = android.graphics.drawable.Drawable.createFromPath(imagePath);

// or

var imagePath = ...;
var imageAndroidBitmap = android.graphics.BitmapFactory.decodeFile(imagePath);
```

**Comment by jiwonyune** [comment]
@Pip3r4o thanks for the reply.

By the way, by importing the image like as follows also helped solving the problem:

`let image: Image = this.ImageRef.nativeElement;`

I'll close this issue.
