### ISSUE TITLE
How to Ignore invalid SLL(SSLHandleException) 

### ISSUE THREAD

**Issue by bferreirainfo** [NativeScript/NativeScript#3356]
Hi,  

I need to access an API that i cant control the certificate, in this case the certificate is invalid and need that the nativescript ignore this and do the request anyway, how can i achieve that?

**Comment by NickIliev** [comment]
Hi @bferreirainfo 

Can you provide more information about your issue? 
- on what platform you are experiencing the SSLHandleException? (Android, iOS or both)
- post the error log
- post a code snippet or a sample project that can recreate the situation

You can see this discussion [here ](https://github.com/NativeScript/NativeScript/issues/1919) for a similar issue.

**Comment by NickIliev** [comment]
Hey @bferreirainfo thre is also a plugin developed by a community member which is handling SSL - perhaps you can try it for your case.
Here is the plugin repo : [https://github.com/gethuman/nativescript-https](https://github.com/gethuman/nativescript-https)
