### ISSUE TITLE
Switch button is not working in sideDrawer - nativeScript

### ISSUE THREAD

**Issue by narender56** [NativeScript/NativeScript#3358]
Hello everyone,

I'm using two sideDrawers in same screen. One from Left and one from bottom.
On left sideDrawer switch button is working properly.
but on bottom sideDrawer no toggle happens when click on switch button. 

Pls help.

Thanks in advance.

**Comment by NickIliev** [comment]
Hey @narender56 

Thank you for your interest in NativeScript!
Please consider providing a code snippet or a sample project with what you have done so far - this way it would be much easier for you to get answers and solutions and to investigate the reasons behind your problem. Apart from the code part do not forget to provide essential information as on what platform you are experiencing this issue (iOS and/or Android)
Closing this issue as your question is more UI related then real issue so I would recommend posting it in the [StackOverflow ](http://stackoverflow.com/questions/tagged/nativescript)channel or another similar community group. This
