### ISSUE TITLE
Android:processing node_modules failed.

### ISSUE THREAD

**Issue by vzJosip** [NativeScript/NativeScript#3359]
After upgrading to SSD and installing new Windows on my machine following error keeps poping up while trying to build project for deployment on android. Same project was working on the HDD just two days ago!

"Processing node_modules failed. Error: spawn ENAMETOOLONG"

error pops up after these two lines in terminal:
Executing before-prepare hook from C:\OET\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.1.4

I'm running: tns --version -> 2.4.2.
tns-core-modules -> version -> 2.4.4
tns-android -> 2.3.0

Can anyone help me with resolving this problem!

**Comment by NickIliev** [comment]
Hello @vzJosip 

This is Windows related error caused by file paths longer than 254 characters. To resolve that try to delete your **_node_modules_** and **_platforms_** folders and rebuild your project. I would also recommend installing the latest android runtime as well.

```
rm -rf node_modules
tns platform remove android
tns platform add android
tns build android
```
