### ISSUE TITLE
ENV Variable to Disable Email Prompts for Telerik UI

### ISSUE THREAD

**Issue by vbresults** [NativeScript/NativeScript#3360]
For those of us building many apps in a CI environment, please add a variable that we can prepend to npm install so that there is no opt in/email prompt.  It is causing my builds to hang.

Tried using `npm install telerik-nativescript-ui --ignore-scripts` but at random this seems to be ignored by the `npm install` that follows it, and we can't `--ignore scripts` on the latter.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#2384
