### ISSUE TITLE
[Feature] Google Drive API

### ISSUE THREAD

**Issue by michaellee8** [NativeScript/NativeScript#3380]
Feature Requests:
Is it possible for us to get a Google Drive plugin?

**Comment by NickIliev** [comment]
@michaellee8 if you need a storage solution perhaps you can use the firebase plugin and its functionality to storage to upload and download files. More information about the plugin [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/STORAGE.md) and about fFrebase [here](https://console.firebase.google.com)

If you want to create a feature request you can do it in our aha ideas site [here](https://nativescript.ideas.aha.io/). This way the idea can be upvoted and discussed within the community and the best/most popular ideas are getting implemented.
