### ISSUE TITLE
Service exited due to signal: Terminated: 15

### ISSUE THREAD

**Issue by davidxiao** [NativeScript/NativeScript#3386]
First time tried to play NS with the Groceries example, and found the below errors on command terminal, angular 2 version,

Dec 31 23:04:42 192-168-1-111 com.apple.CoreSimulator.SimDevice.2A834640-8AAC-456C-AB46-E8630E262BB9.launchd_sim[15636] (UIKitApplication:org.nativescript.groceries[0x83c8][16315]): Service exited due to signal: Terminated: 15

$ tns --version
2.4.2

### Please tell us how to recreate the issue in as much detail as possible.
it happens after edit the source code, seems related to sync compiled file as similar to https://github.com/NativeScript/nativescript-angular/issues/101
but it doesn't help by following advice there.

**Comment by tsonevn** [comment]
Hi @davidxiao,

I reviewed your problem and found that this problem could be related with some of the `before-prepare` hooks. To solve this behavior you could try to follow the below described steps.

1. delete `node_modules`, `platforms`, `hooks`, `lib`  folders. 
2.  run `tns install`
3. `tns run ios`
4. `tns livesync ios --watch`

If this does not help, could you provide some more info about your problem and full log with the error from the console.

Regards,
@tsonevn

**Comment by bnussey** [comment]
Hi @tsonevn I am continuing to get this even after doing the above steps on 3.0.0 .. any ideas?

**Comment by tsonevn** [comment]
Hi @bnussey,
First of all at this time you should use `tns run ios`, while building the project, which will start automatically to live sync all files.

Could you verify, whether the below-attached steps will resolve your issue:
1. delete `node_modules`, `platforms` folders.
2. clear the cache with `npm cache clear`
3. `tns run ios`
if you still have the same problem, please provide some more info about the problem.
