### ISSUE TITLE
Problem with TelerikUI and TelerikAppFeedback compiling IOS

### ISSUE THREAD

**Issue by mounirka** [NativeScript/NativeScript#3387]
Hi guys, i made an app that's working good on android, and also on IOS when i'm doing the tns deploy ios command. But when i try to upload the .ipa to the store with Xcode, during the validations process it says that i have 2 errors that involves the TelerikUI and the TelerikAppFeedback components.
Those are the errors:

- CFBundleIdintifier Collision. There is more than one bundle with the CFBundleIdentifier value 'Telerik.TelerikAppFeedback' under the ios application 'Application.app'
- CFBundleIdintifier Collision. There is more than one bundle with the CFBundleIdentifier value 'Telerik.TelerikUI' under the ios application 'Application.app'

I'm using:
MacOSX: El Captain 10.11.6
Xcode: 8.2
Nativescript CLI version: 2.3.0
tns-core-modules version: 2.3.0

And this is my package.json
```
{
  "description": "Application",
  "readme": "Application",
  "nativescript": {
    "id": "org.nativescript.application",
    "tns-android": {
      "version": "2.4.1"
    },
    "tns-ios": {
      "version": "2.3.0"
    }
  },
  "dependencies": {
    "nativescript-facebook-login": "^0.2.0",
    "nativescript-geolocation": "0.0.15",
    "nativescript-imagecropper": "0.0.7",
    "nativescript-imagepicker": "^2.4.1",
    "nativescript-loading-indicator": "^2.2.1",
    "nativescript-pulltorefresh": "^1.1.8",
    "nativescript-toast": "^1.4.0",
    "tns-core-modules": "^2.4.2"
  },
  "devDependencies": {
    "babel-traverse": "6.18.0",
    "babel-types": "6.18.0",
    "babylon": "6.13.1",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^2.0.9"
  }
}
```
Thank you so much

**Comment by NickIliev** [comment]
Hi @mounirka 

I've noticed that you are using previous versions of NativeScript CLI and iOS runtime while using the latest tns-core-modules. Try to update both your NativeScript and iOS runtimes by executing the following commands.

```
npm uninstall -g nativescript
npm install -g nativescript
tns platform remove ios
tns platform add ios
```

Also take a look at [this thread](https://github.com/NativeScript/NativeScript/issues/3046) where a similar issue with duplicate identifiers is discussed and a solution is provided.

**Comment by NickIliev** [comment]
@mounirka I notice that the plugin **nativescript-imagepicker** is depending on **nativescript-telerik-ui** plugin. This is the reason for your duplicating instances of **CFBundleIdintifier** regarding TelerikUI.

However, I have created new project with the exact same dependencies as your in **package.json** but using tns-ios : { "version" : "2.4.0" } and NativeScript 2.4.2 and in the fi8nal result I had only one appearance of both TelerikUI and TelerikAppFeedback. Let me know if updating your NativeScript CLI and runtime has resolved this issue for you.

**Comment by mounirka** [comment]
Hi @NickIliev thank you for your reply. I solved it 2 days ago by changing the CFBundleIdentifier of the two bundles and it worked.
Regarding the update of nativescript i will try tomorrow, thank you again.

**Comment by mounirka** [comment]
Hi @NickIliev unfortunately the trick of forking the plugin and changing the package.json it didn't work for me becuase it keeps telling me: couldn't find the module nativescript-imagepicker
I don't know what to do, if i use the plugin from github i can't validate the app for ios because the binary was invalid, and if i fork and edit the package it can't even find the module.

Please i need your help, thank you

**Comment by mounirka** [comment]
After a long night i managed to get it to work.
I used the official nativescript-imagepicker plugin, but before adding it i added to my project the nativescript-telerik-ui plugin.
Now everything seems to work, i'm waiting for the ios review.
