### ISSUE TITLE
XCode Deploying Issue

### ISSUE THREAD

**Issue by eurica-larazo** [NativeScript/NativeScript#3388]
Im using XCode to deploy my app and when I tried to build it this errors are showing.

```
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

XCode 8.1
Node v7.3.0
tns --version 2.4.2
Pod 1.1.1

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.appname",
    "tns-ios": {
      "version": "2.4.0"
    },
    "tns-android": {
      "version": "2.3.0"
    }
  },
  "dependencies": {
    "moment": "^2.15.2",
    "nativescript-cache": "^1.0.0",
    "nativescript-drop-down": "^1.3.3",
    "nativescript-floatingactionbutton": "^2.2.4",
    "nativescript-imagecropper": "0.0.7",
    "nativescript-imagepicker": "^2.3.1",
    "nativescript-iqkeyboardmanager": "^1.0.1",
    "nativescript-loading-indicator": "^2.1.0",
    "nativescript-statusbar": "^1.0.0",
    "nativescript-webview-interface": "^1.3.0",
    "tns-core-modules": "^2.2.1"
  },
  "devDependencies": {
    "babel-traverse": "6.14.0",
    "babel-types": "6.14.0",
    "babylon": "6.9.1",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.0",
    "typescript": "^1.8.10"
  }
}
```

**Comment by tsonevn** [comment]
Hi @eurica-larazo,

This problem could be related with an issue while installing some of the pods, while deploying your app from XCode. Could you try to deploy your app using `tns run ios` command and to verify, whether you will have the same problem.  If this does not help you could install the pods manually using the below-given instruction.

1. `cd platforms/ios` 
2. run `pod install`
3. go to the main project directory and run `tns run ios`

I  notice that your are using old modules. You could  upgrade them to latest version, while using `tns update`. More about the command and upgrade instruction could be find in the docs [here](http://docs.nativescript.org/releases/upgrade-instructions#upgrading-the-application).

Hope this helps.
Regards,
@tsonevn

**Comment by eurica-larazo** [comment]
Thanks for the quick reply. I did the update and also do the `post install` and this is the result.

```
emma-pro:ios eurica$ pod install
Analyzing dependencies
Downloading dependencies
Using IQKeyboardManager (4.0.8)
Using MBProgressHUD (1.0.0)
Using MNFloatingActionButton (0.1.5)
Using TMCache (2.1.0)
Using TOCropViewController (1.3.3)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 5 dependencies from the Podfile and 5 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `vinbuddies` to `Pods/Target Support Files/Pods-vinbuddies/Pods-vinbuddies.debug.xcconfig` or include the `Pods/Target Support Files/Pods-vinbuddies/Pods-vinbuddies.debug.xcconfig` in your build configuration (`vinbuddies/build-debug.xcconfig`).

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `vinbuddies` to `Pods/Target Support Files/Pods-vinbuddies/Pods-vinbuddies.release.xcconfig` or include the `Pods/Target Support Files/Pods-vinbuddies/Pods-vinbuddies.release.xcconfig` in your build configuration (`vinbuddies/build-release.xcconfig`).
```

But still doesn't work. When im building it on XCode there is no problem but when I try to Archive it, the error will show.

**Comment by tsonevn** [comment]
Hi @eurica-larazo,

For publishing the app in App Store you could use `tns publish ios` command. First you could delete `platforms`, `node_modules` and `hooks` folders and to run `tns publish ios` command. The command will prompt for your `Apple ID` and `Password` for authentication with iTunes Connect and then produce a release build and proceed to upload it to iTunes Connect. For more info you could review the [documentation](http://docs.nativescript.org/publishing/publishing-ios-apps#builds) and instructions, how to publish app. 

Hope this will resolve your problem.
Regards,
@tsonevn

**Comment by eurica-larazo** [comment]
Thanks @tsonevn, but why do you think this is happening? I already uploaded versions of my app in that way but that error never occur. This is the first time I encountered this error.

**Comment by tsonevn** [comment]
Hi @eurica-larazo,

This notification could be shown due to adding some explicit dependency on the Pods, however this is only a warning and should not prevent you of publishing your application on the App Store. You should be able to publish your app while using our publish command `tns publish ios` or while using XCode. If there is a problem with publishing the application will be rejected and with specific error.


Regards,
@tsonevn

**Comment by mounirka** [comment]
Hi @eurica-larazo i saw that you used the imagepicker plugin in your project, i had your same error on xcode and for me the problem was related to the imagepicker plugin.
I solved it by doing:
```
tns plugin remove nativescript-imagepicker
tns plugin add nativescript-telerik-ui
tns plugin add nativescript-imagepicker
tns prepare ios
```

Hope that this works for you too, bye.

**Comment by eurica-larazo** [comment]
Thanks @mounirka, It's working that way but I already submitted the App few days ago. I just submitted it using `Nativescript CLI`. So guess I can close this now. 
Thanks guys.
