### ISSUE TITLE
Pass data nativescript to webview, when we use url for loading webview

### ISSUE THREAD

**Issue by narender56** [NativeScript/NativeScript#3394]
Hello folks,

Wish you a happy new year to all, 

I have a scenario where I've to send user id and receiver id to a web-view but i'm using "src" as a http link(a page which is in server    http://139.123.0.0:7777/index.html ). can anyone please help.

(user id & receiver id)  --------------------  >(web-view)
NativeScript ------------------------->  http://139.123.0.0:7777/index.html

**Comment by NickIliev** [comment]
Hello @narender56 

You can access native methods like discussed [here](https://github.com/NativeScript/NativeScript/issues/915#issuecomment-147370848) or use a plugin for bi-directional communication like [nativescript-webview-interface](https://www.npmjs.com/package/nativescript-webview-interface)

**Comment by narender56** [comment]
Hey @NickIliev Thanks for your reply, i've gone through  this before, it helped me for the issue, this time i want to pass data to server url,does this transfer data to server through that events which are in that example???

**Comment by NickIliev** [comment]
@narender56 can you elaborate more perhaps with a code sample of yours.

**Comment by narender56** [comment]
@NickIliev , For example when user enter a message and submit it ,then i have to  emit a socket from nativescript socket and i have to listen that socket event on node js server which is in linode server. So my doubt is how to configure this nativescript socket to node socket.io? i have done it in html using socket.io script file. Here  nativescript socket io looking for some configuration.can you please help me to connect both sockets.

**Comment by NickIliev** [comment]
Hey @narender56 have you tried [this plugin](https://www.npmjs.com/package/nativescript-socketio) ?
