### ISSUE TITLE
http.getFile how to handle error responses

### ISSUE THREAD

**Issue by NaokiDaxima** [NativeScript/NativeScript#3397]
I am using the http.getFile function to download files from an api. I am having a issue where files are still created, even though the url returns errors ( ex. If session is expired) . After some research it appears the getFile will always create a new file. Can you catch the response status before the http.getFile creates the file?

In the example below I was tying to use the File.exists, but it always returns true.
```
return http.getFile(fullUrl, filePath)
.then(function(r){

    // Test - Check if file Exists
    console.log("Check File Exist: " + fs.File.exists(filePath));
}, function(error) {
});
```

**Comment by NickIliev** [comment]
Hello @NaokiDaxima 

You can use the extended syntax for http request instead of getFile and privide logic for the different server statuses that you will receive. 
For example:

```
http.request({ url: "https://httpbin.org/image/png", method: "GET" })
    .then(function (response) {
        // Argument (response) is HttpResponse!
        var statusCode = response.statusCode;
        console.log("statusCode: " + statusCode);

        if (statusCode >= 200 && statusCode <= 400) {
            response.content.toImage().then(function (res) {
                console.log(res);
            });
        }
    }).catch(function (err) {
        console.log(err);
    });
```

**Comment by NaokiDaxima** [comment]
Hi @NickIliev . Thanks! I have updated my code using the http.request instead, and everything is working correctly. I also made a small update and used the `response.content.toFile(filePath);` to save the file.
