### ISSUE TITLE
Cant create release apk native script

### ISSUE THREAD

**Issue by roeiedri** [NativeScript/NativeScript#3399]
hey guys this is my first time and I really need help
I want to publish an app through google developer console and when I'm trying to upload the name-debug.apk it says that from security reasons I need to disable debugging in the apk
when I run tns build android --release with all the key-store attributes it just prints the explanation for all of the attributes, but there is no release apk in platform/android/build/outputs/apk
Its driving me crazy, what to do?! 
thank you

**Comment by roeiedri** [comment]
also whenever I try to run for example with tns run android it shoes a red error saying
Command D:\Code\NativeScript\byebell\platforms\android\gradlew.bat failed with exit code 1

**Comment by tsonevn** [comment]
Hi @roeiedri,

Could you try to delete `platforms`, `node_modules`, `hooks` folders and to clear npm cache using `npm cache clear`. Then try to again to build for release using 
`tns build android --release --key-store-path <path-to-your-keystore> --key-store-password <your-key-store-password> --key-store-alias <your-alias-name> --key-store-alias-password <your-alias-password>` as it has been described in the [documentation](https://docs.nativescript.org/publishing/publishing-android-apps). After that check if there has been created `<app_name>-release.apk` in `<app_name>/platforms/android/build/outputs/apk/` folder.


Let me know, whether this helps.

**Comment by roeiedri** [comment]
@tsonevn thank you so much for answering
after I deleted the files and cache, I committed the build command... the problem is that the files are still deleted, so I cant search for an apk, there is no platforms folder
should I run `tns run android` ?
hope its nothing serious

**Comment by roeiedri** [comment]
@tsonevn I meant `tns add platform`

**Comment by tsonevn** [comment]
Hi @roeiedri 

The `build` command will first call `tns platform add android`. Regarding to that, you do not have to run it manually. I would also like to know, whether you have problems with run your project with `tns run android`. It would help if you could give us some more info about your environment (CLI, node, modules versions, etc.).

Regards,
@tsonevn

**Comment by roeiedri** [comment]
@tsonevn I'm not sure how to get the node, module version etc... the cli version is 2.4.2

**Comment by roeiedri** [comment]
@tsonevn I run the build command and it shows me this 
`# build android
┌─────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Usage   │ Synopsis                                                                                             │
│ General │ $ tns build android [--compileSdk <API Level>] [--key-store-path <File Path> --key-store-password    │
│         │ <Password> --key-store-alias <Name> --key-store-alias-password <Password>] [--release] [--static     │
│         │ -bindings] [--copy-to <File Path>]                                                                   │
└─────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────┘

Builds the project for Android and produces an APK that you can manually deploy on device or in the native emulator.

### Options

    * --compileSdk - Sets the Android SDK that will be used to build the project.
    * --release - If set, produces a release build. Otherwise, produces a debug build. When set, you must also specify the --key-store-* options.
    * --key-store-path - Specifies the file path to the keystore file (P12) which you want to use to code sign your APK. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --key-store-password - Provides the password for the keystore file specified with --key-store-path. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --key-store-alias - Provides the alias for the keystore file specified with --key-store-path. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --key-store-alias-password - Provides the password for the alias specified with --key-store-alias-password. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --copy-to - Specifies the file path where the built .apk will be copied. If it points to a non-existent directory, it will be created. If the specified value is directory, the original file name will be used.

### Attributes
<API Level> is a valid Android API level. For example: 22, 23.`
nothing have been created, including the platforms folder

**Comment by tsonevn** [comment]
Hi @roeiedri, 

This notification shows you the command with the needed setting to be able to build APK file for release. 
The command is as follow 

`tns build android --release --key-store-path <path-to-your-keystore> --key-store-password <your-key-store-password> --key-store-alias <your-alias-name> --key-store-alias-password <your-alias-password>`, 

where you should replace `<path-to-your-keystore>`, `<your-key-store-password>` , `<your-alias-name>` and `<your-alias-password>` with your own data. 

Could you also check, whether you have valid `.keystore` file and if not to create new one, while following instructions [here](https://developer.android.com/studio/publish/app-signing.html) and [here](https://coderwall.com/p/r09hoq/android-generate-release-debug-keystores) .

Regards,
@tsonevn

**Comment by roeiedri** [comment]
@tsonevn 
I created a new keystore using the instructions in the links you sent, I did as I needed but still when I run `tns build android` it prints what I've sent earlier, and nothing happens
when I run `tns run android` it prints
`Copying template files...
Project successfully created.
Starting Android emulator with image Nexus4
Error: getaddrinfo ENOENT undefined:5554
    at Object.exports._errnoException (util.js:1026:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
Sending exception report (press Ctrl+C to stop)...`

**Comment by roeiedri** [comment]
@tsonevn 
I run `tns run android` again and....
`-
> nativescript-dev-android-snapshot@0.0.5 postinstall D:\Code\NativeScript\tanahone\node_modules\nativescript-dev-android-snapshot
> node postinstall.js

nativescript-statusbar@1.0.0 node_modules\nativescript-statusbar

email-validator@1.0.7 node_modules\email-validator

babylon@6.14.1 node_modules\babylon

lazy@1.0.11 node_modules\lazy

nativescript-dev-android-snapshot@0.0.5 node_modules\nativescript-dev-android-snapshot
├── semver@5.3.0
├── adm-zip@0.4.7
├── shelljs@0.6.1
└── nativescript-hook@0.2.1 (mkdirp@0.5.1, glob@6.0.4)

nativescript-theme-core@0.2.6 node_modules\nativescript-theme-core

tns-core-modules@2.4.4 node_modules\tns-core-modules
└── tns-core-modules-widgets@2.4.0

babel-traverse@6.21.0 node_modules\babel-traverse
├── babel-messages@6.8.0
├── globals@9.14.0
├── debug@2.6.0 (ms@0.7.2)
├── invariant@2.2.2 (loose-envify@1.3.0)
├── babel-code-frame@6.20.0 (js-tokens@2.0.0, esutils@2.0.2, chalk@1.1.3)
├── lodash@4.17.4
└── babel-runtime@6.20.0 (regenerator-runtime@0.10.1, core-js@2.4.1)

babel-types@6.21.0 node_modules\babel-types
├── to-fast-properties@1.0.2
├── esutils@2.0.2
├── lodash@4.17.4
└── babel-runtime@6.20.0 (regenerator-runtime@0.10.1, core-js@2.4.1)
Executing before-prepare hook from D:\Code\NativeScript\tanahone\hooks\before-prepare\nativescript-dev-android-snapshot.js

:config phase:  createDefaultIncludeFiles

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
        +adding dependency: D:\Code\NativeScript\tanahone\platforms\android\libs\aar\widgets-release.aar
Incremental java compilation is an incubating feature.
:asbg:clean UP-TO-DATE
:deleteMetadata
:deleteFlavors
:clean

BUILD SUCCESSFUL

Total time: 56.9 secs
Successfully prepared plugin nativescript-statusbar for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared (android)
Executing after-prepare hook from D:\Code\NativeScript\tanahone\hooks\after-prepare\nativescript-dev-android-snapshot.js

:config phase:  createDefaultIncludeFiles
        +found plugins: tns-core-modules-widgets
         + creating include.gradle file for D:\Code\NativeScript\tanahone\platforms\android\configurations\tns-core-modules-widgets
Renaming plugin directory to flavor name: D:\Code\NativeScript\tanahone\platforms\android\src\tns-core-modules-widgets -> D:\Code\NativeScript\tanahone\platforms\android\src\F0

:config phase:  createPluginsConfigFile
         Creating product flavors include.gradle file in D:\Code\NativeScript\tanahone\platforms\android/configurations folder...

:config phase:  pluginExtend
        +applying configuration from: D:\Code\NativeScript\tanahone\platforms\android\configurations\include.gradle
        +applying configuration from: D:\Code\NativeScript\tanahone\platforms\android\configurations\tns-core-modules-widgets\include.gradle

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
        +adding dependency: D:\Code\NativeScript\tanahone\platforms\android\libs\aar\widgets-release.aar
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preF0DebugBuild UP-TO-DATE
:checkF0DebugManifest
:preF0ReleaseBuild UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2501Library
:prepareComAndroidSupportAppcompatV72501Library
:prepareComAndroidSupportDesign2501Library
:prepareComAndroidSupportRecyclerviewV72501Library
:prepareComAndroidSupportSupportCompat2501Library
:prepareComAndroidSupportSupportCoreUi2501Library
:prepareComAndroidSupportSupportCoreUtils2501Library
:prepareComAndroidSupportSupportFragment2501Library
:prepareComAndroidSupportSupportMediaCompat2501Library
:prepareComAndroidSupportSupportV42501Library
:prepareComAndroidSupportSupportVectorDrawable2501Library
:prepareComAndroidSupportTransition2501Library
:prepareTanahoneRuntimeUnspecifiedLibrary
:prepareWidgetsReleaseLibrary
:prepareF0DebugDependencies
:compileF0DebugAidl
:compileF0DebugRenderscript
:generateF0DebugBuildConfig
:cleanLocalAarFiles
:ensureMetadataOutDir
:collectAllJars
:setProperties
:generateTypescriptDefinitions SKIPPED
:copyTypings SKIPPED
:asbg:generateInterfaceNamesList
:asbg:traverseJsFiles
:asbg:runAstParser
Running full build
finished with reading lines with js files
:asbg:generateBindings
:mergeF0DebugShaders
:compileF0DebugShaders
:generateF0DebugAssets
:mergeF0DebugAssets
:generateF0DebugResValues
:generateF0DebugResources
:mergeF0DebugResources
[drawable-hdpi-v4/bavlim2] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\bavlim2.jpg    [drawable-hdpi-v4/bavlim2] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\bavlim2.png: Error: Duplicate resources
[drawable-hdpi-v4/table1] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\table1.jpg [drawable-hdpi-v4/table1] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\table1.png: Error: Duplicate resources
[drawable-hdpi-v4/mizrim1] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\mizrim1.jpg    [drawable-hdpi-v4/mizrim1] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\mizrim1.png: Error: Duplicate resources
[drawable-hdpi-v4/mizrim2] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\mizrim2.JPG    [drawable-hdpi-v4/mizrim2] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\mizrim2.png: Error: Duplicate resources
[drawable-hdpi-v4/bavlim] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\bavlim.jpg [drawable-hdpi-v4/bavlim] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\bavlim.png: Error: Duplicate resources
:mergeF0DebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeF0DebugResources'.
> [drawable-hdpi-v4/bavlim2] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\bavlim2.jpg  [drawable-hdpi-v4/bavlim2] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\bavlim2.png: Error: Duplicate resources
[drawable-hdpi-v4/table1] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\table1.jpg [drawable-hdpi-v4/table1] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\table1.png: Error: Duplicate resources
[drawable-hdpi-v4/mizrim1] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\mizrim1.jpg    [drawable-hdpi-v4/mizrim1] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\mizrim1.png: Error: Duplicate resources
[drawable-hdpi-v4/mizrim2] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\mizrim2.JPG    [drawable-hdpi-v4/mizrim2] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\mizrim2.png: Error: Duplicate resources
[drawable-hdpi-v4/bavlim] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\bavlim.jpg [drawable-hdpi-v4/bavlim] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\bavlim.png: Error: Duplicate resources

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 26.108 secs
Command D:\Code\NativeScript\tanahone\platforms\android\gradlew.bat failed with exit code 1
# run android
┌────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────┐
│ Usage                  │ Synopsis                                                                              │
│ Run on all connected   │ $ tns run android [--key-store-path <File Path> --key-store-password <Password> --key │
│ devices and running    │ -store-alias <Name> --key-store-alias-password <Password>] [--release] [--justlaunch] │
│ emulators              │                                                                                       │
│ Run on a selected      │ $ tns run android --device <Device ID> [--key-store-path <File Path> --key-store      │
│ connected device or    │ -password <Password> --key-store-alias <Name> --key-store-alias-password <Password>]  │
│ running emulator       │ [--release] [--justlaunch]                                                            │
│ Start an emulator and  │ $ tns run android --emulator [<Emulator Options>] [--key-store-path <File Path> --key │
│ run the app inside it  │ -store-password <Password> --key-store-alias <Name> --key-store-alias-password        │
│                        │ <Password>] [--release] [--justlaunch]                                                │
└────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────┘

Runs your project on a connected Android device or in a native Android emulator, if configured. This is shorthand for prepare, build and deploy. While your app is running, prints the output from the application in the console.

### Options

    * --watch - If set, when you save changes to the project, changes are automatically synchronized to the connected device.
    * --device - Specifies a connected device on which to run the app.
    * --emulator - If set, runs the app in a native emulator for the target platform, if configured. When set, you can also set any other valid combination of emulator options as listed by $ tns help emulate android.
    * --release - If set, produces a release build. Otherwise, produces a debug build. When set, you must also specify the --key-store-* options.
    * --key-store-path - Specifies the file path to the keystore file (P12) which you want to use to code sign your APK. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --key-store-password - Provides the password for the keystore file specified with --key-store-path. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --key-store-alias - Provides the alias for the keystore file specified with --key-store-path. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --key-store-alias-password - Provides the password for the alias specified with --key-store-alias-password. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --justlaunch - If set, does not print the application output in the console.

### Attributes

    * <Device ID> is the index or name of the target device as listed by $ tns device android
    * <Emulator Options> is any valid combination of options as listed by $ tns help emulate android

Sending exception report (press Ctrl+C to stop)...............................................`

**Comment by tsonevn** [comment]
Hi @roeiedri, 
This error could be related with some problem with copying the second time the `App_Resources` folder, while running `tns run android`

Please try to delete `platforms`, `node_modules` and `hooks` folders. Then run `tns run android`. if the app has been deployed on the device as expected, delete again `platforms` folder and build for release `tns build android --release ...`.  

If the problem still exists, send us your project `package.json` file. The node version could be found by running `node --version` in the console and the CLI version, while using `tns --version`

**Comment by roeiedri** [comment]
node version : v6.9.1
CLI    version : 2.4.2

**Comment by roeiedri** [comment]
@tsonevn 
`>tns run android
Copying template files...
Project successfully created.
|
> nativescript-dev-android-snapshot@0.0.5 postinstall D:\Code\NativeScript\tanahone\node_modules\nativescript-dev-android-snapshot
> node postinstall.js

nativescript-statusbar@1.0.0 node_modules\nativescript-statusbar

email-validator@1.0.7 node_modules\email-validator

babylon@6.14.1 node_modules\babylon

lazy@1.0.11 node_modules\lazy

nativescript-dev-android-snapshot@0.0.5 node_modules\nativescript-dev-android-snapshot
├── semver@5.3.0
├── adm-zip@0.4.7
├── shelljs@0.6.1
└── nativescript-hook@0.2.1 (mkdirp@0.5.1, glob@6.0.4)

nativescript-theme-core@0.2.6 node_modules\nativescript-theme-core

tns-core-modules@2.4.4 node_modules\tns-core-modules
└── tns-core-modules-widgets@2.4.0

babel-traverse@6.21.0 node_modules\babel-traverse
├── babel-messages@6.8.0
├── globals@9.14.0
├── debug@2.6.0 (ms@0.7.2)
├── invariant@2.2.2 (loose-envify@1.3.0)
├── babel-code-frame@6.20.0 (js-tokens@2.0.0, esutils@2.0.2, chalk@1.1.3)
├── lodash@4.17.4
└── babel-runtime@6.20.0 (regenerator-runtime@0.10.1, core-js@2.4.1)

babel-types@6.21.0 node_modules\babel-types
├── to-fast-properties@1.0.2
├── esutils@2.0.2
├── lodash@4.17.4
└── babel-runtime@6.20.0 (regenerator-runtime@0.10.1, core-js@2.4.1)
Executing before-prepare hook from D:\Code\NativeScript\tanahone\hooks\before-prepare\nativescript-dev-android-snapshot.js

:config phase:  createDefaultIncludeFiles

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
        +adding dependency: D:\Code\NativeScript\tanahone\platforms\android\libs\aar\widgets-release.aar
Incremental java compilation is an incubating feature.
:asbg:clean UP-TO-DATE
:deleteMetadata
:deleteFlavors
:clean

BUILD SUCCESSFUL

Total time: 14.971 secs
Successfully prepared plugin nativescript-statusbar for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared (android)
Executing after-prepare hook from D:\Code\NativeScript\tanahone\hooks\after-prepare\nativescript-dev-android-snapshot.js

:config phase:  createDefaultIncludeFiles
        +found plugins: tns-core-modules-widgets
         + creating include.gradle file for D:\Code\NativeScript\tanahone\platforms\android\configurations\tns-core-modules-widgets
Renaming plugin directory to flavor name: D:\Code\NativeScript\tanahone\platforms\android\src\tns-core-modules-widgets -> D:\Code\NativeScript\tanahone\platforms\android\src\F0

:config phase:  createPluginsConfigFile
         Creating product flavors include.gradle file in D:\Code\NativeScript\tanahone\platforms\android/configurations folder...

:config phase:  pluginExtend
        +applying configuration from: D:\Code\NativeScript\tanahone\platforms\android\configurations\include.gradle
        +applying configuration from: D:\Code\NativeScript\tanahone\platforms\android\configurations\tns-core-modules-widgets\include.gradle

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
        +adding dependency: D:\Code\NativeScript\tanahone\platforms\android\libs\aar\widgets-release.aar
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preF0DebugBuild UP-TO-DATE
:checkF0DebugManifest
:preF0ReleaseBuild UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2501Library
:prepareComAndroidSupportAppcompatV72501Library
:prepareComAndroidSupportDesign2501Library
:prepareComAndroidSupportRecyclerviewV72501Library
:prepareComAndroidSupportSupportCompat2501Library
:prepareComAndroidSupportSupportCoreUi2501Library
:prepareComAndroidSupportSupportCoreUtils2501Library
:prepareComAndroidSupportSupportFragment2501Library
:prepareComAndroidSupportSupportMediaCompat2501Library
:prepareComAndroidSupportSupportV42501Library
:prepareComAndroidSupportSupportVectorDrawable2501Library
:prepareComAndroidSupportTransition2501Library
:prepareTanahoneRuntimeUnspecifiedLibrary
:prepareWidgetsReleaseLibrary
:prepareF0DebugDependencies
:compileF0DebugAidl
:compileF0DebugRenderscript
:generateF0DebugBuildConfig
:cleanLocalAarFiles
:ensureMetadataOutDir
:collectAllJars
:setProperties
:generateTypescriptDefinitions SKIPPED
:copyTypings SKIPPED
:asbg:generateInterfaceNamesList
:asbg:traverseJsFiles
:asbg:runAstParser
Running full build
finished with reading lines with js files
:asbg:generateBindings
:mergeF0DebugShaders
:compileF0DebugShaders
:generateF0DebugAssets
:mergeF0DebugAssets
:generateF0DebugResValues
:generateF0DebugResources
:mergeF0DebugResources
[drawable-hdpi-v4/bavlim2] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\bavlim2.jpg    [drawable-hdpi-v4/bavlim2] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\bavlim2.png: Error: Duplicate resources
[drawable-hdpi-v4/table1] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\table1.jpg [drawable-hdpi-v4/table1] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\table1.png: Error: Duplicate resources
[drawable-hdpi-v4/mizrim1] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\mizrim1.jpg    [drawable-hdpi-v4/mizrim1] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\mizrim1.png: Error: Duplicate resources
[drawable-hdpi-v4/mizrim2] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\mizrim2.JPG    [drawable-hdpi-v4/mizrim2] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\mizrim2.png: Error: Duplicate resources
[drawable-hdpi-v4/bavlim] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\bavlim.jpg [drawable-hdpi-v4/bavlim] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\bavlim.png: Error: Duplicate resources
:mergeF0DebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeF0DebugResources'.
> [drawable-hdpi-v4/bavlim2] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\bavlim2.jpg  [drawable-hdpi-v4/bavlim2] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\bavlim2.png: Error: Duplicate resources
[drawable-hdpi-v4/table1] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\table1.jpg [drawable-hdpi-v4/table1] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\table1.png: Error: Duplicate resources
[drawable-hdpi-v4/mizrim1] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\mizrim1.jpg    [drawable-hdpi-v4/mizrim1] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\mizrim1.png: Error: Duplicate resources
[drawable-hdpi-v4/mizrim2] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\mizrim2.JPG    [drawable-hdpi-v4/mizrim2] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\mizrim2.png: Error: Duplicate resources
[drawable-hdpi-v4/bavlim] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\bavlim.jpg [drawable-hdpi-v4/bavlim] D:\Code\NativeScript\tanahone\platforms\android\src\main\res\drawable-hdpi\bavlim.png: Error: Duplicate resources

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 55.357 secs
Command D:\Code\NativeScript\tanahone\platforms\android\gradlew.bat failed with exit code 1
# run android
┌────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────┐
│ Usage                  │ Synopsis                                                                              │
│ Run on all connected   │ $ tns run android [--key-store-path <File Path> --key-store-password <Password> --key │
│ devices and running    │ -store-alias <Name> --key-store-alias-password <Password>] [--release] [--justlaunch] │
│ emulators              │                                                                                       │
│ Run on a selected      │ $ tns run android --device <Device ID> [--key-store-path <File Path> --key-store      │
│ connected device or    │ -password <Password> --key-store-alias <Name> --key-store-alias-password <Password>]  │
│ running emulator       │ [--release] [--justlaunch]                                                            │
│ Start an emulator and  │ $ tns run android --emulator [<Emulator Options>] [--key-store-path <File Path> --key │
│ run the app inside it  │ -store-password <Password> --key-store-alias <Name> --key-store-alias-password        │
│                        │ <Password>] [--release] [--justlaunch]                                                │
└────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────┘

Runs your project on a connected Android device or in a native Android emulator, if configured. This is shorthand for prepare, build and deploy. While your app is running, prints the output from the application in the console.

### Options

    * --watch - If set, when you save changes to the project, changes are automatically synchronized to the connected device.
    * --device - Specifies a connected device on which to run the app.
    * --emulator - If set, runs the app in a native emulator for the target platform, if configured. When set, you can also set any other valid combination of emulator options as listed by $ tns help emulate android.
    * --release - If set, produces a release build. Otherwise, produces a debug build. When set, you must also specify the --key-store-* options.
    * --key-store-path - Specifies the file path to the keystore file (P12) which you want to use to code sign your APK. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --key-store-password - Provides the password for the keystore file specified with --key-store-path. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --key-store-alias - Provides the alias for the keystore file specified with --key-store-path. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --key-store-alias-password - Provides the password for the alias specified with --key-store-alias-password. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --justlaunch - If set, does not print the application output in the console.

### Attributes

    * <Device ID> is the index or name of the target device as listed by $ tns device android
    * <Emulator Options> is any valid combination of options as listed by $ tns help emulate android

Sending exception report (press Ctrl+C to stop).....`





The package.json file: 
`{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.tanahone",
    "tns-android": {
      "version": "2.4.1"
    }
  },
  "dependencies": {
    "email-validator": "^1.0.7",
    "nativescript-statusbar": "^1.0.0",
    "nativescript-theme-core": "^0.2.1",
    "tns-core-modules": "2.4.4"
  },
  "devDependencies": {
    "babel-traverse": "6.21.0",
    "babel-types": "6.21.0",
    "babylon": "6.14.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*"
  }
}`

**Comment by roeiedri** [comment]
it worked at the beginning, but since three days ago it is not working @tsonevn 
thank you

**Comment by roeiedri** [comment]
@tsonevn 
Very sorry for being annoying but I need to solve this problem until this sunday :/
still, thank you very much for your time

**Comment by NathanaelA** [comment]
@roeiedri - The issue you need to fix is that "duplicate resources" -- that is what is stopping you.  There are a couple ways this can happen, but here is the typically way to fix it.

1. Solving it typically is fairly simple.  Just do a search in your folder for "bavlim2.*" (and the other files it is complaining about) and see if you have multiple copies of it, and then deleted the extra copies.  Don't worry about any copies in the "platforms" folder, this will be reset by step 2.
2. Reset the Android platform (i.e. `tns platform remove android` then `tns platform add android`)

**Comment by roeiedri** [comment]
@NathanaelA I do have couple of images with the same name but different extension names, this is a problem?

**Comment by roeiedri** [comment]
@NathanaelA Do I need to put for instance the bavlim2 img in every drawable folder?

**Comment by roeiedri** [comment]
@NathanaelA  I didn't read the log message carefully, dump act

**Comment by roeiedri** [comment]
@tsonevn @NathanaelA 
I cant believe its working! 
the app runs and with images and so on but still there is the build problem,
whenever i run the `tns build android --release ....`
this happens:

`# build android
┌─────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Usage   │ Synopsis                                                                                             │
│ General │ $ tns build android [--compileSdk <API Level>] [--key-store-path <File Path> --key-store-password    │
│         │ <Password> --key-store-alias <Name> --key-store-alias-password <Password>] [--release] [--static     │
│         │ -bindings] [--copy-to <File Path>]                                                                   │
└─────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────┘

Builds the project for Android and produces an APK that you can manually deploy on device or in the native emulator.

### Options

    * --compileSdk - Sets the Android SDK that will be used to build the project.
    * --release - If set, produces a release build. Otherwise, produces a debug build. When set, you must also specify the --key-store-* options.
    * --key-store-path - Specifies the file path to the keystore file (P12) which you want to use to code sign your APK. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --key-store-password - Provides the password for the keystore file specified with --key-store-path. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --key-store-alias - Provides the alias for the keystore file specified with --key-store-path. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --key-store-alias-password - Provides the password for the alias specified with --key-store-alias-password. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --copy-to - Specifies the file path where the built .apk will be copied. If it points to a non-existent directory, it will be created. If the specified value is directory, the original file name will be used.

### Attributes
<API Level> is a valid Android API level. For example: 22, 23.
`

**Comment by roeiedri** [comment]
@tsonevn @NathanaelA no release apk is created

**Comment by roeiedri** [comment]
@tsonevn is there a problem with the package.json file? what can I do?

**Comment by roeiedri** [comment]
Does someone have an answer?

**Comment by roeiedri** [comment]
@tsonevn @NathanaelA okay I did  it!!!!!!!!!!!!!!!!!!!!!!! its working!!!!!!!!!!!!
let me tell you what happened:
as I was still trying to solve this annoying problem, I needed to go out to somewhere, 
at my home, I'm using a laptop that connected to a big screen, usb port and more.
i disconnected my laptop and got out, on my way in the car i connected onlyyy the external flash drive in which i have the project.
i connected the laptop to a wifi using hot spot in my phone, and as i said i couldn't believe it... i just worked!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! thank you very much for your time,
i guess it was either a problem with the keystore file or either it has something to do with the connected deviced at my home cause i got plenty of them

**Comment by aduwillie** [comment]
I think I am facing the same issue. I've tried creating the release build both in Windows and Linux but i only get the instructions instead of the actually build. I need to get a release build for my app as soon as possible too.

**Comment by Euniceswit** [comment]
Hi,

Please tns build is not generating an apk. Please what should I do?

**Comment by NickIliev** [comment]
@Euniceswit please provide as much details as possible regarding your specific problem. 
- Which command you ar using (are you building for release with `tns` or bundling with WebPack)
- Are there generated files in **_platforms/android/build_**

**Comment by Euniceswit** [comment]
@NickIliev thanks for your quick response.

Am not building for release, I just want to run the app on my android phone.
There are generated files in my platforms/android/build folder, however no apk was in this folder:C:\NODEJSCODES\getStatus\platforms\android\build\outputs\apk. Just this file .nsbuildinfo is in there.

Kindly help.

**Comment by NickIliev** [comment]
@Euniceswit try deleting the platform folder and re-building the project
```
rm -rf platforms
tns build android
```
Can you verify that the command is executed successfully and ending with similar lines
```
BUILD SUCCESSFUL

Total time: 5.852 secs
Project successfully built.
```

**Comment by jasonComing** [comment]
I had the same problem.  It was because I had a space in my key store path.  It's must be breaking the tns parser.  Problem solved after renaming the folder name to remove the space!

Also, you can use --log trace to get more information about the build process.  It's helpful sometimes.
