### ISSUE TITLE
Where does console.log go?

### ISSUE THREAD

**Issue by vjeux** [NativeScript/NativeScript#34]
In many places in the docs you use console.log but I can't find where the output goes. It isn't in the terminal after I type `tns run ios --emulator`, nor in the simulator.

**Comment by teobugslayer** [comment]
Hello @vjeux, we just merged a code change to show these by default - see https://github.com/telerik/mobile-cli-lib/pull/250 . This will be available in our next public release.

**Comment by vjeux** [comment]
Great thanks!
