### ISSUE TITLE
How to check internet connectivity status in nativescript?

### ISSUE THREAD

**Issue by narender56** [NativeScript/NativeScript#3403]
Hi every one,

I have to check whether the user having internet or not, so i've used connectivity module but am getting a gigantic error,which is tied below. I think it's asking some permissions but that are also configured in Androidmanifest.xml file.but wondering why is throwing?? and It is working in ios but not in android.

(https://cloud.githubusercontent.com/assets/8955270/21639917/ba1c74d4-d298-11e6-886e-66d8bbdaf68b.png)

**Comment by NickIliev** [comment]
Hello @narender56 

The error you are seeing is as you stated because of missing permissions in your **_AndroidManifest.xml_** file. Keep in mind that any changes made in AndroidMManifest.xml will require a full rebuild of your application (**livesync** won't apply changes outside **_app_** folder).

[This is the necessary permission ](https://github.com/NickIliev/NativeScript-issues/blob/master/NativeScript/issue_3403/app/App_Resources/Android/AndroidManifest.xml#L20)
located in **_app/App_Resources/AndroidManifest.xml_**. After saved changes rebuild your app with `tns run android` or `tns build android`.

Test application with working connectivity module  [here](https://github.com/NickIliev/NativeScript-issues/tree/master/NativeScript/issue_3403) - you can check it on your side and let us know if everything worked out for you.

**Comment by narender56** [comment]
hey @NickIliev , here i'm directly getting permission denied.How to alert the user for taking the permissions.

var permissions = require("nativescript-permissions")
var connectivity = require("connectivity");
//var connectionType = connectivity.getConnectionType();

permissions.requestPermission(android.Manifest.permission.ACCESS_NETWORK_STATE, "I need these permissions because I'm cool")
            .then(() => {
                console.log("Permission Granted!");
               
                switch (connectivity.getConnectionType()) {
                    case connectivity.connectionType.none:
                        this.connectWith = "None";
                        console.log("none");
                        break;
                    case connectivity.connectionType.wifi:
                        this.connectWith = "Wi-Fi";
                        console.log("wifi");
                        break;
                    case connectivity.connectionType.mobile:
                        this.connectWith = "Mobile";
                        console.log("mobile");
                        break;
                    default:
                        break;
                }
            })
            .catch(() => {
                console.log("Permission Denied!");
            });  

output : permission denied

**Comment by NickIliev** [comment]
@narender56  have you added the permission in your **AndroidManifest.xml** file prior to building your application!? 

Apart from that [here is an example](https://github.com/NickIliev/NativeScript-Cosmos-Databank/blob/master/app/views/drawer-page.ts) on how to grant permissions using the nativescript-permissions plugin - in this example I have asked for permission on navigatedTo page event. Note that you will still have to explicitly set the list of wanted permission in your [AndroidManifest.xml](https://github.com/NickIliev/NativeScript-Cosmos-Databank/blob/master/app/App_Resources/Android/AndroidManifest.xml#L17-L21)

**Comment by narender56** [comment]
@NickIliev thanks for your help. It's working now.

**Comment by slasho** [comment]
but this only show the type of connection, but if you have for example, wifi with no internet it says wifi, but doesnt say if you have internet or not... is there something to check internet??

**Comment by JorgeHawkins** [comment]
I want to know if I have access to Internet, not if I have my wireless board turned on or off.

**Comment by fhackenb** [comment]
@NickIliev I have the same need as @JorgeHawkins  and @slasho. I need to know if there's internet connection or not - being connected to a wifi network that doesn't have internet for instance should tell me there's no internet

**Comment by Omi231** [comment]
@JorgeHawkins @fhackenb you guys found any solution?

**Comment by NickIliev** [comment]
@fhackenb @Omi231 @slasho the connectivity module in NativeScript is using the native APIs and is working just as it would work in native Android or iOS (for example [here is the Android implementation](https://github.com/NativeScript/NativeScript/blob/f1bef481e69eb378facc4daa0ac3f8281210832b/tns-core-modules/connectivity/connectivity.android.ts) which is using the native `getActiveNetworkInfo` method).

So if that said even[ the native Android developers are facing the same scenario](https://stackoverflow.com/questions/9570237/android-check-internet-connection) where the connectivity module is assuming that there is a connection (and there might be one even if it is very slow and practically there is almost no internet connection). In similar cases and an additional check is required and, for example, you could implement kind of manual ping.  There are multiple suggestions provided in t[the very same thread](https://stackoverflow.com/questions/9570237/android-check-internet-connection), but as far as I saw none of them is actually covering all scenarios that can occur.


All of the above considered, if anyone has a good and bullet-proof solution for real Internet check, we are open for PRs and contributions.
