### ISSUE TITLE
Xcode archive problem

### ISSUE THREAD

**Issue by kwong93** [NativeScript/NativeScript#3410]
### Tell us about the problem
When I try to archive app on Xcode, it gives me this error:

```
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: tns --version gives me 2.4.0
- Cross-platform modules: 2.4.0

```
{
  "nativescript": {
    "id": "...",
    "name": "...",
    "tns-android": {
      "version": "2.4.1"
    },
    "tns-ios": {
      "version": "2.4.0"
    }
  },
  "dependencies": {
    "lodash": "^4.16.6",
    "moment": "^2.16.0",
    "nativescript-angular": "^1.1.2",
    "nativescript-appversion": "^1.3.1",
    "nativescript-background-http": "2.4.0",
    "nativescript-checkbox": "^1.1.6",
    "nativescript-dom": "^1.0.7",
    "nativescript-fresco": "^1.0.13",
    "nativescript-geolocation": "0.0.14",
    "nativescript-globalevents": "^1.1.1",
    "nativescript-imagepicker": "2.3.1",
    "nativescript-loading-indicator": "^2.2.1",
    "nativescript-master-technology": "^1.0.8",
    "nativescript-orientation": "^1.0.5",
    "nativescript-permissions": "^1.1.1",
    "nativescript-photoviewer": "file:plugins/nativescript-photoviewer-full-screen.tgz",
    "nativescript-pulltorefresh": "^1.1.8",
    "nativescript-push-notifications": "0.0.17",
    "nativescript-screen-orientation": "^1.0.2",
    "nativescript-snackbar": "^1.0.3",
    "nativescript-telerik-ui-pro": "file:plugins/nativescript-ui-pro1.5.1.tgz",
    "nativescript-websockets": "^1.3.0",
    "numeral": "^1.5.3",
    "pubsub-js": "^1.5.3",
    "string": "^3.3.1",
    "tns-core-modules": "^2.4.1",
    "typescript": "^1.8.10",
    "url-parse": "^1.1.1"
  },
  "devDependencies": {
    "babel-traverse": "6.15.0",
    "babel-types": "6.15.0",
    "babylon": "6.9.2",
    "lazy": "1.0.11"
  }
}
```
### Please tell us how to recreate the issue in as much detail as possible.
I did tns platform clean ios, tns prepare ios, open .xcworkspace file in Xcode, select generic ios device and go to Product > Archive.

There is also a warning that appears before the error:

`build-release.xcconfig line 2: Unable to find included file "../plugins-release.xcconfig"`

I see a `plugins-debug.xcconfig` under platforms/ios, but not `plugins-release.xcconfig`. Looking at the `plugins-debug.xcconfig` file, the `PODS_ROOT` is set to `${SRCROOT}/Pods` . I'm guessing since the release version of this xcconfig is not generated it couldn't get the `PODS_ROOT` and gives the error.

My Xcode version is 8.2.1 (8C1002)

My pod version is 1.1.1

Mac is Sierra 10.12.1

**Comment by tsonevn** [comment]
Hi @kwong93,
Thank you for reporting this issue.
I reviewed your casa and found that you should call `pod install`, before publishing the app using Xcode. You could follow the below-described steps.

1. `cd platforms/ios`
2. `run pod install`

 You could also publish your app while using our publish command `tns publish ios`. The command will prompt for your `Apple ID` and `Password` for authentication with iTunes Connect and then produce a release build and proceed to upload it to iTunes Connect. 

Hope this helps.

duplicated with issue #3388

**Comment by Daxito** [comment]
executing "tns prepare ios --release" before archiving fixed this issue.

**Comment by pandeyshivang** [comment]
run pod update instead of pod install beacuse pod install check only existing pod and pod update reinstall all pods.
