### ISSUE TITLE
View fragments

### ISSUE THREAD

**Issue by bfattori** [NativeScript/NativeScript#342]
How difficult is it to implement view fragments? For example, say I have a grid layout:
```
<Page>
   <GridLayout rows="60,*,30" columns="*">
      <Label text="Hello" row="0"/>
      <Image src="~/foo.png" row="1"/>
      <Label text="World" row="2"/>
   </GridLayout>
</Page>
```
Now say I want the Image to be swapped out, but keep the rest of the existing view. I would think that from code this wouldn't be too difficult, but it would be nice to be able to swap that `Image` by giving it some identifier, then in code being able to swap that:
```
<!-- Main page in file "main-page.xml" -->
<Page>
   <GridLayout rows="60,*,30" columns="*">
      <Label text="Hello" row="0" id="header"/>
      <Image src="~/foo.png" row="1" id="content"/>
      <Label text="World" row="2" id="footer"/>
   </GridLayout>
</Page>


<!-- Fragment in file "fragments/new-view.xml" -->
<Fragment id="new-view">
   <Image src="~/bar.png"/>
</Fragment>
```
Then in code do something like:
```
var frag = page.loadFragment('~/fragments/new-view');
page.setContent('content', frag);
```
So it would swap just that one part of the view so I don't have to recreate the entire view for every page. Possibly also loading a JavaScript fragment called "new-view.js" which would be accessible from the same context as the Page.

Thoughts?

**Comment by RangerMauve** [comment]
Rather than fragments, I think what you might find useful is the [custom components](https://docs.nativescript.org/ui-with-xml#custom-components) feature. You can also set the src of the image dynamically if you use bindings inside the ViewModel fro the component.

**Comment by bfattori** [comment]
Possibly, I will have to look into that a bit more.

**Comment by bfattori** [comment]
Yep. Just what I needed. Closing.
