### ISSUE TITLE
Activity Indicator does not work inside ListView Template.

### ISSUE THREAD

**Issue by davecoffin** [NativeScript/NativeScript#3420]
Activity Indicators simply dont show in a list view. If you put one in, it takes up the space it should, but the indicator does not show.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.4.2
- Cross-platform modules: 2.4.4
- Runtime(s): 2.4.0

code:
```
<ListView items="{{ timeline }}" height="100%" style.padding="0" style.backgroundColor="red">
    <ListView.itemTemplate>
        <Image src="res://foodicon" height="40" />
    </ListView.itemTemplate>
</ListView>

```
produces this:
<img width="459" alt="screenshot 2017-01-05 13 34 10" src="https://cloud.githubusercontent.com/assets/1245462/21692755/55941634-d34c-11e6-81d0-d6a0e5ed486d.png">

```
<ListView items="{{ timeline }}" height="100%" style.padding="0" style.backgroundColor="red">
    <ListView.itemTemplate>
        <ActivityIndicator busy="true" color="red" width="40" height="40" />
    </ListView.itemTemplate>
</ListView>

```
produces this:
<img width="459" alt="screenshot 2017-01-05 13 33 54" src="https://cloud.githubusercontent.com/assets/1245462/21692735/3c5157cc-d34c-11e6-9885-8ba002e0625c.png">

**Comment by tsonevn** [comment]
Hi @davecoffin,
Thank you for reporting this issue.

I reviewed your code, however was unable to reproduce this behavior, while following he above given instructions. I am also attaching my sample code and screenshot from the simulator. In my opinion, this could be related with some style properties in your css file. You could also try to set `GridLayout` for main container for your  `ListView`. It would help if you could provide demo, where the problem could be debugged locally.

main-page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">

    <GridLayout rows="" columns="">
        <ListView items="{{ source }}"  style.padding="0" style.backgroundColor="red">
            <ListView.itemTemplate>
                <ActivityIndicator busy="true" color="red" width="40" height="40" />
            </ListView.itemTemplate>
        </ListView>    
    </GridLayout>
</Page>
```

main-page.ts
```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';

export function navigatingTo(args: EventData) {

    let page = <Page>args.object;
    var array=[{title:"title1"}, {title:"title2"}, {title:"title3"}, {title:"title4"}, {title:"title5"}, {title:"title6"}];

    page.bindingContext = {source:array};
}
```

![screen shot 2017-01-06 at 8 54 37 am](https://cloud.githubusercontent.com/assets/17448734/21710085/fc074674-d3ee-11e6-82b2-a1865c90546a.png)

Hope this help

**Comment by lfabreges** [comment]
I encountered the same issue using the latest version of NativeScript. `ListView` on iOS is using `dequeueReusableCellWithIdentifier` in `tableViewCellForRowAtIndexPath`, thus, `ActivityIndicator` is instantiated only one time and then reused.

I think the problem is that `ActivityIndicator` call `startAnimating` in `onBusyPropertyChanged`. When reusing the instance, `onBusyPropertyChanged` isn't triggered if the reused instance had already the `busy` property set to true.

Can we reopen this issue ?

**Comment by lfabreges** [comment]
As a workaround, you can listen to the `itemLoading` event, get the `ActivityIndicator` view, and then start the animation with :
```ts
const activityIndicator = <ActivityIndicator>args.view;
activityIndicator.busy = !activityIndicator.busy;
activityIndicator.busy = !activityIndicator.busy;
```

**Comment by tsonevn** [comment]
Hi @lfabreges,

I reviewed this case again, however, I am still unable to reproduce this behavior.
Regard to that, could you provide sample project, which could be debugged locally?

Regards,
@tsonevn

**Comment by ycherniavskyi** [comment]
@tsonevn the issue simple reproduced by adding more items to `ListView` and then just scroll it - [demo playground](https://play.nativescript.org/?template=play-tsc&id=FtF9KZ).

@lfabreges your solution works - thanks.
