### ISSUE TITLE
Cant load an image from res folder

### ISSUE THREAD

**Issue by roeiedri** [NativeScript/NativeScript#3421]
hey guys,
I'm trying to insert an img... `<Image src="res://download.jpg"/>`
i moved to image to the res folder and i did as i should, when i run the app there is a warning saying that the image doesn't exist or not found, also tried writing in the xml with the full address 
what can i do?
thanks

**Comment by tsonevn** [comment]
Hi @roeiedri,
Thank you for your interest in NativeScript.

When you try to load image from resources you should set the image name without the extension. For example `<Image src="res://download"/>`.  Then the image should be shown. Important step is to add the needed images in the right folder in App_Resources for both iOS and Android. 
For further help you could follow the [article ](https://docs.nativescript.org/ui/images#load-images-from-a-resource) in the docs. You could also use [NativeScript Image Builder](http://nsimage.nativescript.rocks/Home/UploadImage) for converting your image to the correct resolution.

Regards,
@tsonevn

**Comment by roeiedri** [comment]
@tsonevn thank you it worked
another problem that was related is that i had two photos with the same name, the extension name wasn't the same, `png ` and `jpg` but apparently it doesn't matter, what matters is the name itself
