### ISSUE TITLE
Strange ActionBar Animation

### ISSUE THREAD

**Issue by josempbrites** [NativeScript/NativeScript#3424]
Hi guys,

### Tell us about the problem
I'm building a simple application with a listview and a details view when I tap an item. However in, iOS I'm getting a strange flick of the action bar when navigating to the details view. Does anyone know why this occurs ? Older projects work as they should.
This gif shows whats happening:

![actionbar](https://cloud.githubusercontent.com/assets/9122756/21713394/bbe188ae-d3f1-11e6-99c2-71b0afd8aa1c.gif)

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.4.2
- Cross-platform modules: 2.4.4
- Runtime(s): iOS - 2.4.0; Android - 2.4.1

### Please tell us how to recreate the issue in as much detail as possible.

Creating a listview with item tap to details view. Action bar displays a strange animation, even when it is not styled.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

main-view.xml

```
    <StackLayout> 
        <ListView items="{{ myItems }}">
            <ListView.itemTemplate>
                <StackLayout orientation="horizontal" tap="itemTap">
                    <Label cssClass="id" text="{{ ID }}" />    
                    <Label cssClass="title" text="{{ Title }}" />    
                </StackLayout>
            </ListView.itemTemplate> 
         </ListView> 
    </StackLayout>
```

main-view.js
```

function itemTap (args) {
    frameModule.topmost().navigate({
        moduleName: 'details',
        context: args.view.bindingContext,
        animated: true,
        transition: {
            name: "slide",
            duration: 300,
            curve: "easeIn"
    }
    });
}
```

details.js

```
function pageLoaded(args){
    var page = args.object;
    page.bindingContext = page.navigationContext;

}

exports.pageLoaded = pageLoaded;
```

**Comment by tsonevn** [comment]
Hi @josempbrites,

I reviewed your case and found that this behavior with the transition could be related with the fact that you have missed to add `ActionBar` component in your `details.xml` file. When you use ActionBar in your project , you should add it on the other pages too. Then the transition should have the work as expected. For your convenience I am attaching sample code.

main-page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
 <Page.actionBar>
     <ActionBar title="Title"  icon="">
         <NavigationButton text="Back" icon="" tap="" />
         <ActionBar.actionItems>
             <ActionItem icon="" text="Left" tap="" ios.position="left" />
             <ActionItem icon="" text="Right" tap="" ios.position="right" />
         </ActionBar.actionItems>
     </ActionBar>
 </Page.actionBar>
 <StackLayout> 
        <ListView items="{{ myItems }}">
            <ListView.itemTemplate>
                <StackLayout orientation="horizontal" tap="itemTap">
                    <Label cssClass="id" text="{{ ID }}" />    
                    <Label cssClass="title" text="{{ Title }}" />    
                </StackLayout>
            </ListView.itemTemplate> 
         </ListView> 
    </StackLayout>
</Page>
```
main-page.ts
```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import { isIOS } from "platform";
import {topmost} from "ui/frame"

export function navigatingTo(args: EventData) {
    let page = <Page>args.object;
    
    var array = [{ID:"id1", Title:"title1"}, {ID:"id2", Title:"title2"}, {ID:"id3", Title:"title3"}];
    page.bindingContext = {myItems:array};
}


export function itemTap (args) {
    topmost().navigate({
        moduleName: 'details',
        context: args.view.bindingContext,
        animated: true,
        transition: {
            name: "slide",
            duration: 300,
            curve: "easeIn"
    }
    });
}
```
details.xml
```
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="onLoaded" navigatedTo="onNavigatedTo">
     <Page.actionBar>
        <ActionBar title="Title2" ></ActionBar>
    </Page.actionBar>
    <StackLayout>
        <Label text="details page" textWrap="true" />
    </StackLayout>
</Page>
```

app.css
```
ActionBar{
    background-color: green;
}
```

Let me know whether this helps or if I could assist you further.

**Comment by josempbrites** [comment]
Hi @tsonevn, thank you for your quick answer. I already have an action bar on the details view. The code is similar, but my issue still persists. I'll try to create a new project with your code only, maybe the problem is with my view model.

**Comment by josempbrites** [comment]
Ok, the problem was with the action items. They must match on both action-bars, at least in number.
