### ISSUE TITLE
How to get index from repeater in nativescript?

### ISSUE THREAD

**Issue by narender56** [NativeScript/NativeScript#3426]
Hello, 

Can anyone please tell me that how to get index from nativescript repeater.

       <Repeater items={{myItems}}>
               <repeater.itemTemplate>
                         <Label text={{$value}} />
               </repeater.itemTemplate>
       </Repeater> 

Thanks in advance.

**Comment by NickIliev** [comment]
Hey @narender56 

You can assign unique id for your context items and access it via the bindingContext and the tapEvent for the selected item.

e.g.
Typescript
```
import { EventData, Observable } from 'data/observable';
import { Page } from 'ui/page';

let vm = new Observable();

export function navigatingTo(args: EventData) {
    let page = <Page>args.object;
    vm.set("myItems", [{ color: "red", id: 1 }, { color: "blue", id: 2 }, { color: "green", id: 3 }]);

    page.bindingContext = vm;
}

export function onTap(args) {
    var item = args.view.bindingContext;
    console.log('item.id', item.id);
};
```

XML
```
<Repeater id="rp" items="{{ myItems }}">
    <Repeater.itemTemplate>
        <StackLayout tap="onTap" >
            <Label text="{{ color }}" />
        </StackLayout>
    </Repeater.itemTemplate>
</Repeater>
```

**Comment by narender56** [comment]
thanks @NickIliev , it worked for me.

**Comment by majorpaynegh** [comment]
`<Repeater items="{{ nowshowing }}" id="repeater" itemTap="repeatertap" >
                <Repeater.itemsLayout>
                <StackLayout orientation="horizontal" tap="onTap">
                </StackLayout>                    
                </Repeater.itemsLayout>
                <Repeater.itemTemplate>
                <GridLayout rows="auto,*,*" columns="104,*" >
                    <Image src="{{ image_url }}" stretch ="fill" row="0" colSpan="2" tap="" />
                    <Label text="{{ title }}" id="{{ $value.title }}" textWrap="true" class="lblTitle" row="1" col="0" />                                                  
                    </GridLayout>
                </Repeater.itemTemplate>
            </Repeater>`

Thant is my XML
can you help me with with JS code to get the tapped gridlayout's corresponding name?

**Comment by sagar1911** [comment]
Hi @NickIliev ,
When user clicks on an item in repeater I want only that item to be highlighted and other items should be in non-selective mode. How can i do that ?
