### ISSUE TITLE
How to change the visual style and add icons to Dialog (actions)?

### ISSUE THREAD

**Issue by betosalvador** [NativeScript/NativeScript#3436]
Hello everyone.

How do I change the background color, text color and add icons to each action item on my Dialog-Actions?

Is there anyway?

Thanks in advance,

**Comment by mounirka** [comment]
You can create a custom dialog using modal pages.

**Comment by betosalvador** [comment]
Hi @mounirka , thanks for response.

But the modal pages hides the content of the current page. It's seems like a new page.

I would like to keep the current page visible below, like dialog does. :(

**Comment by NickIliev** [comment]
Hey @betosalvador 

As @mounirka  pointed out you can use modal page to create your customised dialogues pages.
However keep in mind that for iOS the modal pages can be **fullscreen only** (while for Android you can also control their size and make them look like dialogues). You can see [this solution here ](https://github.com/NativeScript/nativescript/issues/2086#issuecomment-221956483) on how to create translucent modal page including a custom native solution [for iOS](https://github.com/NativeScript/nativescript/issues/2086#issuecomment-221956483)

**Comment by betosalvador** [comment]
Thanks @NickIliev for response.

Today I will try this.

:) +1:
