### ISSUE TITLE
 Android: Cannot read property 'loadImage' of undefined

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#3441]
_From @iridiumsoft on January 6, 2017 21:48_

In my App i'm loading images from Amazon S3 and images folder. Everything going well in iOS but Android giving the very strange error. if i comment off all of Image tags it works fine. So I'm sure its something wrong with image loader. I'm using Native Script **Version: 2.4.0**
Here is the error message

```
JS: EXCEPTION: Cannot read property 'loadImage' of undefined
JS: ORIGINAL STACKTRACE:
JS: TypeError: Cannot read property 'loadImage' of undefined
JS:     at Image._createImageSourceFromSrc (/data/data/org.sujag.district/files/app/tns_modules/ui/image/image.js:142:29)
JS:     at Image._createUI (/data/data/org.sujag.district/files/app/tns_modules/ui/image/image.js:94:14)
JS:     at Image.View._onContextChanged (/data/data/org.sujag.district/files/app/tns_modules/ui/core/view.js:202:14)
JS:     at Image.View._onAttached (/data/data/org.sujag.district/files/app/tns_modules/ui/core/view.js:153:14)
JS:     at eachChild (/data/data/org.sujag.district/files/app/tns_modules/ui/core/view.js:158:23)
JS:     at StackLayout.LayoutBase._eachChildView (/data/data/org.sujag.district/files/app/tns_modules/ui/layouts/layout-base-common.js:144:22)
JS:     at StackLayout.View._onAttached (/data/data/org.sujag.district/files/app/tns_modules/ui/core/view.js:165:18)
JS:     at FlexboxLayout.View._addViewCore (/data/data/org.sujag.district/files/app/tns_modules/ui/core/view.js:126:18)
JS:     at FlexboxLayout.View._addView (/data/data/org.sujag.district/files/app/tns_modules/ui/core/view-common.js:1164:14)
JS:     at FlexboxLayout.LayoutBase.insertChild (/data/data/org.sujag.district/files/app/tns_modules/ui/layouts/layout-base-common.js:53:14)
JS: EXCEPTION: Cannot read property 'v' of null

```

_Copied from original issue: NativeScript/nativescript-cli#2390_

**Comment by NickIliev** [comment]
Hi @iridiumsoft,

Can you provide us with a snippet or a sample application that can reproduce this issue?

**Comment by iridiumsoft** [comment]
Hi @NickIliev I could not fixed this issue but i created a new app and moved my original code to there and get that working. I really did know 100% what was the issue but i think i tried to change application id in Manifest.xml file manually and some other settings, may be that was the reason, but i don't know.

**Comment by NickIliev** [comment]
@iridiumsoft nice to hear you have resolved this case.

Apart from the issue f you want to change your package id you should do it via your root package.json file.Once the ide is changed you should remove platforms folder and rebuild your application.
e.g.
```
  "nativescript": {
    "id": "org.nativescript.myNewIssueName", // change this
    "tns-android": {
      "version": "2.4.1"
    }
  },
```

**Comment by iridiumsoft** [comment]
Thanks, it works :)
