### ISSUE TITLE
Cannot display app

### ISSUE THREAD

**Issue by roeiedri** [NativeScript/NativeScript#3443]
hey guys,
I created an drawer template application and copied into the home.xml other file... that ive created before
whenever I run the app, the build successful but when displaying this shows up
`Successfully transferred all files.
Applying changes...
Successfully synced application org.nativescript.tanahbakal on device emulator-5554.
01-09 09:33:56.544  4575  4575 W System.err:    at com.tns.Runtime.callJSMethodNative(Native Method)
01-09 09:33:56.544  4575  4575 W System.err:    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
01-09 09:33:56.544  4575  4575 W System.err:    at com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
01-09 09:33:56.544  4575  4575 W System.err:    at com.tns.Runtime.callJSMethod(Runtime.java:895)
01-09 09:33:56.544  4575  4575 W System.err:    at com.tns.Runtime.callJSMethod(Runtime.java:879)
01-09 09:33:56.544  4575  4575 W System.err:    at com.tns.Runtime.callJSMethod(Runtime.java:871)`

the home.js file
```
var BasePage = require("../../shared/BasePage");
var frameModule = require("ui/frame");
var topmost = frameModule.topmost();
var HomePage = function() {};
HomePage.prototype = new BasePage();
HomePage.prototype.constructor = HomePage;

// Place any code you want to run when the home page loads here.
HomePage.prototype.contentLoaded = function() {}


module.exports = new HomePage();
```
what can I do?
thanks

**Comment by tsonevn** [comment]
Hi @roeiedri, 

Thank you for reporting your problem.

Could you give us some more info about your case? It would help if you could give us the code from `home.xml`, which leads to this problem. You could also build your project with `tns run <platform_name> --log trace` and to send us the full log from the console.

Regards,
@tsonevn
