### ISSUE TITLE
Dialog modal show back button after modal close in IOS

### ISSUE THREAD

**Issue by kentplaza** [NativeScript/NativeScript#3445]
In IOS, a caller page was was hide thr back button  using code as below:

```
if (app.ios) {
		var controller = frameModule.topmost().ios.controller;
		var navigationItem = controller.visibleViewController.navigationItem;
		navigationItem.setHidesBackButtonAnimated(true, false);
}

then I call for a modal form as below: 
page.showModal(modalPageModule, context, function closeCallback(username, password) {
    //do something
}, true);

```
The modal form closed but the back back appear again.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: **2.4.1**
- Cross-platform modules: **2.4.2**
- Runtime(s): **tns-android 2.4.1, tns-ios 2.4.0**
- Plugin(s): **"tns-core-modules": "^2.4.2"**

Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

**Comment by NickIliev** [comment]
Hello @kentplaza 

Perhaps redefining `clearHistory: false` from your initial page will do the job for you.
Example [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_3445/modalViewListView) (navigate to Page Two >> open modal / close modal >> navigation Button does not appear as I have set clearHistory: false [here](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/NativeScript/issue_3445/modalViewListView/app/main-page.ts#L19))
