### ISSUE TITLE
Nativescript app error with google maps.

### ISSUE THREAD

**Issue by AntonisHopkins** [NativeScript/NativeScript#3451]
Hello, I use in my app the plugins, geolocation and google-maps-sdk and when I try to redirect to the maps page which will show the location of the user this kind of error appears: Error:Building UI from xml @file........./maps/maps:xml:2:3
>invalid nodeName
File:/data/data/......./tns_modules/ui/builder/builder.js line 170 column 16.
the code of xml is this : 

 <Page 
    xmlns="http://www.nativescript.org/tns.xsd"
    xmlns:maps="nativescript-google-maps-sdk"
    navigatingTo="onNavigatingTo">
  <StackLayout>
    <maps:mapView latitude="{{ PosX }}"
                  longitude="{{ PosY }}"
                  zoom="15"
                  mapReady="mapIsReady"
    /> </StackLayout></Page>

**Comment by tsonevn** [comment]
Hi @AntonisHopkins,

I have tested `nativescript-google-maps-sdk` plugin in sample project and it seems to work as expected. You could review the sample project [here](https://github.com/tsonevn/TabViewNativeScriptGoogleMaps). It would help if you could provide some more info about the problem , or to give us sample project, which could be debugged locally. 

In the meantime you could also check, whether you have added in `app/App_Resources/Android/values/nativescript_google_maps_api.xml` file your `API_KEY` as it has been shown below.

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="nativescript_google_maps_api_key">API_KEY</string>
</resources>
```

Hope this helps

**Comment by AntonisHopkins** [comment]
I am using the app in my Elephone p8000 Android 5.1 in google the api key it is saying enabled. But a friend of me with  different api key in different device the same code said it works... Is it possible that my device create this bug??

**Comment by tsonevn** [comment]
Hi @AntonisHopkins, 
Could you check, whether you will have the same problem, while using the [sample project ](https://github.com/tsonevn/TabViewNativeScriptGoogleMaps) and build it in your device. 

If you still have the same behavior you could try to setup Android emulator with `Google Play Services` and to check, whether this issue has been related with the device or it is problem in the project.

You could follow the instructions in the attached links, where has been described, how to set `Google Play Service` and `Android Emulator`, which is needed for using `nativescirpt-google-maps-sdk` in your project.

[https://developers.google.com/android/guides/setup](https://developers.google.com/android/guides/setup)


[http://stackoverflow.com/questions/22141043/google-play-services-missing-in-emulator-android-4-4-2](http://stackoverflow.com/questions/22141043/google-play-services-missing-in-emulator-android-4-4-2)


Regards,
@tsonevn

**Comment by AntonisHopkins** [comment]
Okay let me explain you what I noticed. I copied the code and follow the steps :https://www.npmjs.com/package/nativescript-google-maps-sdk.Same error . I tried your sample in the same device and with mine and yours api key and it worked fine with both. When I try to run my app it shows me this and then continues the build: C:\Users\Antony\Desktop\Talos\app\views\maps\maps.xml has syntax errors.
error
element parse error: Error: invalid tagName:Page 
@#[line:11,col:2]
error
element parse error: Error: attribute equal must after attrName
@#[line:16,col:5]
fatalError
end tag name: Page is not match the current start tagName:undefined
@#[line:22,col:16]

**Comment by tsonevn** [comment]
Hi @AntonisHopkins,

Perhaps the problem has been related due to broken XML code.
However to be able to investigate further this issue, you can share the full code from your `maps.xml` file. 
It would also help if you send us your project, which will help us to give you more detailed solution for this behavior.
Thank you in advance for your cooperation.

Regards,
@tsonevn

**Comment by AntonisHopkins** [comment]
Here is the code , the code in comment is the same code with the link I posted in the previous comment. Both codes has the same xml errors. Another thing is your sample use http://schema.nativescript.org/tns.xsd. I did changed it but there are 2 more xml errors..
<Page xmlns="http://nativescript.org/tns.xsd" xmlns:maps="nativescript-google-maps-sdk" navigatingTo="onNavigatingTo" >
  <GridLayout >
    <maps:mapView
    	latitude= "{{ PosX }}"
        longitude= "{{ PosY }}"
        zoom= "{{ zoom }}"
        mapReady= "mapIsReady" />
  </GridLayout>
</Page>

**Comment by AntonisHopkins** [comment]
Js code for the first xml code : 
var Observable = require("data/observable").Observable;
var GeoLocation = require("nativescript-geolocation");
var mapsModule = require("nativescript-google-maps-sdk");
var Color = require("color").Color;
var CurrentPage;

// Define GPS's Class
var GPSData = new Observable({
    PosX : "40.7696886",
    PosY : "23.5531552",
    zoom: 15
});

// Unit Functions
function onNavigatingTo(args) {
    CurrentPage = args.object;
    CurrentPage.bindingContext = GPSData;
    enableLocation();
}
exports.onNavigatingTo = onNavigatingTo;

function enableLocation(args) {
    do {
        GeoLocation.enableLocationRequest();
    } while (!GeoLocation.isEnabled())
    trackLocation();
}
exports.enableLocation = enableLocation;

function trackLocation() {
  watchId = GeoLocation.watchLocation(
    function (loc) {
        if (loc) {
            console.log("Received location: " + loc.latitude + " " + loc.longitude);
            GPSData.PosX = loc.latitude;
            GPSData.PosY = loc.longitude;
        }
    },
    function(e){
        console.log("Error: " + e.message);
    },
    {
      desiredAccuracy: 3,
      updateDistance: 10,
      minimumUpdateTime : 1000 * 20
    }
  );
}
exports.trackLocation = trackLocation;

function mapIsReady(args) {
    showLocation(args);
    showRadius(args);
    generateQuest(args);
}
exports.mapIsReady = mapIsReady;

function showLocation(args) {
  var mapView = args.object;
  console.log("Setting a marker...");
  var marker = new mapsModule.Marker();
  marker.position = mapsModule.Position.positionFromLatLng(GPSData.PosX,GPSData.PosY);
  marker.title = "Me";
  marker.userData = {index: 1};
  mapView.addMarker(marker);
}

function showRadius(args) {
  var mapView = args.object;

  var circle = new mapsModule.Circle();
  circle.center = mapsModule.Position.positionFromLatLng(GPSData.PosX, GPSData.PosY);
  circle.visible = true;
  circle.radius = 100;
  circle.fillColor = new Color('#99ff8800');
  circle.strokeColor = new Color('#99ff0000');
  circle.strokeWidth = 2;
  mapView.addCircle(circle);
}

function generateQuest(args) {
  var mapView = args.object;
  var marker = new mapsModule.Marker();
  marker.position = mapsModule.Position.positionFromLatLng(GPSData.PosX + 0.001,GPSData.PosY + 0.001);
  marker.title = "Quest";
  marker.userData = {index: 2};
  mapView.addMarker(marker);
}

**Comment by AntonisHopkins** [comment]
problem solved. This code: do {
GeoLocation.enableLocationRequest();
} while (!GeoLocation.isEnabled())
trackLocation();
}
Has bug, endless pop-ups System UI,  a friend of mine (who wrote this part of code) said me.
