### ISSUE TITLE
the way to mock api in tests

### ISSUE THREAD

**Issue by syncro** [NativeScript/NativeScript#3453]
Hi

I want to test service layer using api mocks but when I try to use nock library running tests returns the following exception: 

	Error: com.tns.NativeScriptException: Failed to find module: "nock", relative to: /app/tns_modules/

trying some other libraries (e.g. json-mock) dives to "unable to find 'tty' node module" errors. Is there any way to easily stub responses for NS http client or an universal way can be used with unit tests ?

**Comment by NickIliev** [comment]
@syncro  Perhaps something like [this ](https://github.com/NativeScript/nativescript-angular/blob/master/tests/app/tests/mocks/ns-file-system.mock.ts) can help you with the mocking!?
