### ISSUE TITLE
Android webview enable Cookies not working

### ISSUE THREAD

**Issue by mourice** [NativeScript/NativeScript#3456]
setAcceptThirdPartyCookies on the webview for android is not working

```
if (android.os.Build.VERSION.SDK_INT >= 21) {  		     

android.webkit.CookieManager.getInstance().setAcceptThirdPartyCookies(webview, true);
}
```
getting the following error

Failed resolving method setAcceptThirdPartyCookies on class com.android.webview.chromium.CookieManagerAdapter

I am Using:
- CLI: 2.4.2
- Cross-platform modules: 
"ios": "2.3.0",
"android": "2.3.0"
"version": "2.4.3"
- Runtime(s): "tns-android": {
      "version": "2.4.1"
    }

**Comment by mourice** [comment]
Got it working with following code

if (android.os.Build.VERSION.SDK_INT >= 21) {
				android.webkit.CookieManager.getInstance().setAcceptThirdPartyCookies(**webview.android**, true);
			}

**Comment by AresDev** [comment]
Does someone know how to apply this exactly setting in iOS? I have a Salesforce cookie integration that works ok on Android with this setting but In don't know how to make this on iOS
