### ISSUE TITLE
Unable to access a specific android library

### ISSUE THREAD

**Issue by mn-martin** [NativeScript/NativeScript#3461]
It seems to be impossible accessing the library nanohttpd from within a NativScript project.
Maybe this is some issue with the marshalling that's going on somehow for this library or something like this?

See detailed information and troubleshooting here:
http://forum.nativescript.org/t/nativescript-android-plugin-nanohttpd/136

**Comment by markosko** [comment]
Problem is that it was obfuscated with ProGuard to access library you need to use `fi.iki.elonen` package name so `fi.iki.elonen.NanoHTTPD`

**Comment by mn-martin** [comment]
Thank you markosko, will close this now :-)
