### ISSUE TITLE
How to use angular 2 File ?

### ISSUE THREAD

**Issue by Leo-lay** [NativeScript/NativeScript#3463]
I would like to use angular 2 way to upload pictures, but I found File is not available，appear **cannot find name 'File'**, I would like to know how to use the File ？

![image](https://cloud.githubusercontent.com/assets/8528051/21841203/38aa1666-d81c-11e6-8374-f8d029ce6a29.png)

**Comment by NickIliev** [comment]
Hi @Leo-lay 

In NativeScript [File ](http://docs.nativescript.org/api-reference/classes/_file_system_.file.html)is implemented as part of the [file system module](http://docs.nativescript.org/api-reference/modules/_file_system_.html).
To use it you have to import it in your code behind file.
e.g.
```
import * as fs from "file-system';

var documents = fs.knownFolders.documents();
var path = fs.path.join(documents.path, "FileFromPath.txt");
var file = fs.File.fromPath(path);

// Writing text to the file.
file.writeText("Something")
    .then(function () {
        // Succeeded writing to the file.
    }, function (error) {
        // Failed to write to the file.
    });
```

More examples on how to use file-system in Angular application can be found [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/file-system)

**Comment by Leo-lay** [comment]
@NickIliev  thank you for your help ~

**Comment by AbdallahBedir** [comment]
how to open file dialog to upload an image using angular ?

**Comment by Srij07** [comment]
@NickIliev I am new in Angular. While trying to apply the above code, I am getting an error.
![Capture](https://user-images.githubusercontent.com/50131768/56944285-70705600-6b40-11e9-8b2b-3e8f1c015bac.JPG)

What can I do to resolve it.
