### ISSUE TITLE
HtmlView -> Images are not loading on Android

### ISSUE THREAD

**Issue by iridiumsoft** [NativeScript/NativeScript#3472]
Hi,
I'm using HtmlView to load my content which i get from my web service. Everything looks good except two things on Android.
1)  It doesn't show images in HtmlView, shows small boxes instead
2) I'm adding custom css with style tags to html content and then passing to Htmlview but it shows as string instead of applying styles

Here is how I'm using HtmlView
`<HtmlView html="{{post.content}}" class="text"></HtmlView>`
See attached screenshot for its preview, there you will see small colored box which supposed to be full width image, and you will also see some css showing as string.
https://www.dropbox.com/s/p953p5n51i7bn8a/Screenshot%202017-01-12%2004.02.26.png?dl=0

I'm using NativeScript 2.4.0.

Quick Response would be really great!

**Comment by tsonevn** [comment]
Hi @iridiumsoft,

`HtmlView` in NativeScript has been designed to display pure html code. Loading an image in HtmlView is not supported in NativeScript. 

However if you want interaction or some more specific functionality, it would be better if you use `WebView` module. There you will be able to display image and to apply appropriate style.

More info about this component could be found in the [documentation](https://docs.nativescript.org/cookbook/ui/web-view).

Hope this helps.

**Comment by markosole** [comment]
Hi @tsonevn  I am looking for solution to handle url-s inside `html="{{post.content}}"` 
URL handle works in HtmlView and URL opens in default browser. I would like to have same functionality on WebView because HtmlView does not show images (same as for @iridiumsoft ). I spent 5-6 days in looking for solution. I'm using pure NativeStript with JS, not NG or TS. Any ideas are welcome. Thanks

**Comment by tsonevn** [comment]
Hi @iridiumsoft,
In your case, you can use [nativescript-webview-interface](https://www.npmjs.com/package/nativescript-webview-interface) plugin for creating bi-directional communication between WebView and Android/iOS. With the plugin's help, you can handle some predefined events in the NativeScript app and to open the needed URL via [openUrl](https://docs.nativescript.org/api-reference/modules/_utils_utils_#openurl) method.

**Comment by markosole** [comment]
Hi @tsonevn I have tried this plugin but getting error on page load. I have added this to my js:
`var webViewInterfaceModule = require('nativescript-webview-interface');
var oWebViewInterface;
 
function pageLoaded(args){
    page = args.object;
    setupWebViewInterface(page) 
}
 
// Initializes plugin with a webView
function setupWebViewInterface(page){
    var webView = page.getViewById('webView');
    oWebViewInterface = new webViewInterfaceModule.WebViewInterface(webView, 'http://google.com');
}`

Error is present until I comment out this line: 
`oWebViewInterface = new webViewInterfaceModule.WebViewInterface(webView, 'http://google.com');`

Error is: 
Cannot read property 'isLoaded' of undefinded
file: .../tns_modules/tns-core-modules/ui/gestures/gestures.js, line: 228, column: 40

StackTrace:
function: 'WebViewInterface._initWebView',
nativescript-webview-interface/intex.js', line: 48, column: 25

I would like to have: `<web-view id="webView" src="http://google.com"></web-view> ` and when ever I click on any URL on loaded page, to open it in default browser. I did not figure out how to set it with this plugin/module.

**Comment by tsonevn** [comment]
Hi @markosole,
I tested the `nativescript-webview-interface` plugin in a sample project, and it was working as expected. You can review the attached project. 
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2188029/Archive.zip)

Also, bear in mind that you should import `nativescript-webview-interface` lib in the page, which you will load in the WebView. Then you should use the `emit` method in the web page source to notify the NativeScript app for the specific event. You can check the code snippet [here](https://github.com/shripalsoni04/nativescript-webview-interface-demo/blob/master/app/www/index.js#L49).
