### ISSUE TITLE
ListPicker selectedIndex not working

### ISSUE THREAD

**Issue by svengraziani** [NativeScript/NativeScript#3476]
CLI: 2.4.1, Android

Hi, pre-selecting an Index inside the ListPicker does not work, nor when using ngModel. The ListPicker always starts at Element/Index 0.

**Comment by svengraziani** [comment]
Adding a Timeout before setting the initial index value fixes this issue.

**Comment by tsonevn** [comment]
Hi @svengraziani, 
I have tested your scenario on my side in a sample project, while using `ListPicker` component in NativeScript Angular 2 project and Data Binding `selectedIndex` property seems to work as expected. 

You could use `ListPicker` loaded event and when it has been fired to set the index of the selected item. I am attaching sample code related with the issue.

`HTML`

```
<GridLayout rows="auto, auto" sdkExampleTitle sdkToggleNavButton>
        <!-- >> using-selected-index-html -->
        <StackLayout row="0">
                <Label class="h3 p-15 text-left" text="Use the slider to change ListPicker's selectedIndex" textWrap="true"></Label>
                <Slider class="slider" #sl [minValue]="0" [maxValue]="pokemons.length - 1" [(ngModel)]="index"></Slider>
        </StackLayout>
        <ListPicker class="p-15" #picker row="1" class="picker" (loaded)="lploaded()" [items]="pokemons" [selectedIndex]="index" (selectedIndexChange)="selectedIndexChanged(picker)">
        </ListPicker>
        <!-- << using-selected-index-html -->
</GridLayout>

```

`TypeScript`

```
import { Component } from "@angular/core";

let pokemonList = ["Bulbasaur", "Parasect", "Venonat", "Venomoth", "Diglett",
"Dugtrio", "Meowth", "Persian", "Psyduck", "Arcanine", "Poliwrath", "Machoke"];

@Component({
    moduleId: module.id,
    templateUrl: "./using-selected-index.component.html"
})
export class UsingSelectedIndexExampleComponent {
    public pokemons: Array<string>;
    public index: number;

    constructor() {
        this.pokemons = [];

        for (let i = 0; i < pokemonList.length; i++) {
            this.pokemons.push(pokemonList[i]);
        }
        //this.index=3;
    }
    ngAfterViewInit(){
        
    }
    public selectedIndexChanged(picker) {
        console.log("picker selection: " + picker.selectedIndex);
    }
    lploaded(){
           this.index=3; 
    }
}
```

For further help, you could also review the sample project [here](https://github.com/NativeScript/nativescript-sdk-examples-ng).

If you still have problem, while using the component. please provide some sample code or project, which could be debugged locally. 

Regards,
@tsonevn

**Comment by svengraziani** [comment]
Thank you so much,  the "ListPicker loaded event" did the trick.
Regards,
Sven
