### ISSUE TITLE
https module is missing

### ISSUE THREAD

**Issue by scottmeng** [NativeScript/NativeScript#348]
Hi I have tried to `require("https")` but it seems the module cannot be found

**Comment by RangerMauve** [comment]
The only modules that are supported are the ones in folders in the root of this repo. As a note, the API isn't node compatible in terms that the standard Node modules are not implemented, and it doesn't seem like they will be any time soon.

**Comment by ligaz** [comment]
Hey @scottmeng,

Can you share more details why you need the `https` module? Do you want to host a web server locally on the device? 

We do have an `http` module that should be sufficient for all your client needs.

**Comment by scottmeng** [comment]
@RangerMauve I see thanks for the information

**Comment by scottmeng** [comment]
@ligaz No I was just trying it out. I thought NativeScript is node compatible. Will close this issue.

**Comment by scottmeng** [comment]
@ligaz BTW I am wondering if we could do https requests now with NativeScript?

**Comment by valentinstoychev** [comment]
@scottmeng Yes - you *can* use "https" requests with {N}. Ping us if you hit an issue.
