### ISSUE TITLE
ListView line separators are with shorter width than the listview items 

### ISSUE THREAD

**Issue by SvetoslavTsenov** [NativeScript/NativeScript#3480]
![image](https://cloud.githubusercontent.com/assets/3598759/21896035/8aa808fc-d8ed-11e6-91b8-7a1134f12b39.png)

**Comment by 3rror404** [comment]
I _think_ this is the default behaviour for the iOS table view. Though yours looks more exaggerated than usual.

You can remove the default inset like this:

```
var listViewModule = require("ui/list-view");

if (Platform.isIOS) {
    var listView = page.getViewById('listView');

    listView.on(listViewModule.ListView.itemLoadingEvent, function (args) {
        args.ios.separatorInset = UIEdgeInsetsZero;
    });
}
```

**Comment by atanasovg** [comment]
@SvetoslavTsenov Is this issue still present? It seems more like a bug to me?

**Comment by SvetoslavTsenov** [comment]
Hey, @atanasovg
@hshristov and I have discussed this issue and he has convinced me that this is the default behaviour of iOS. Anyway, I will double check it and write back with more details.

**Comment by NickIliev** [comment]
For anyone interested in overwriting the native behavior and applying full length separators for iPad this can be achieved the following way:

```
onListLoaded(args) {
    var list = <ListView>args.object;
    list.ios.cellLayoutMarginsFollowReadableWidth = false;
}
```

**Comment by b02505048** [comment]
@NickIliev  I tried the solution you provided but no luck.. any other solution?

**Comment by janossuta** [comment]
hi @b02505048 

I don't know if you are still looking for an answer for your question but this is what I've found:

    <ListView class="list-group" [items]="countries" (itemTap)="onItemTap($event)"   
        separatorColor="transparent">
        <ng-template let-country="item">
            <StackLayout>
                <FlexboxLayout flexDirection="row" class="list-group-item">
                    <Image [src]="country.imageSrc" class="thumb img-circle"></Image>
                    <Label [text]="country.name" class="list-group-item-heading"
                        verticalAlignment="center" style="width: 60%"></Label>
                </FlexboxLayout>
                <StackLayout class="hr-light"></StackLayout>
            </StackLayout>
        </ng-template>
    </ListView>

You can set  **separatorColor="transparent"**  and then add a  **<StackLayout class="hr-light"></StackLayout>** control to display a horizontal line or just add a border to the bottom element in your template
