### ISSUE TITLE
nativescript-loading-indicator is not working in ios.

### ISSUE THREAD

**Issue by narender56** [NativeScript/NativeScript#3482]
Hi everyone,

I'm using nativescript-loading-indicator plugin for loader,it's working fine for android but in ios is not. It's looking some value for "mode". Can anyone please tell me what value will there for this "mode" in ios?

ios: {
details: "Additional detail note!",
square: false,
margin: 10,
dimBackground: true,
color: "#4B9ED6",
mode: // see iOS specific options below
}

**Comment by tsonevn** [comment]
Hi @narender56 ,

I tested the plugin's [demo ](https://github.com/NathanWalker/nativescript-loading-indicator/tree/master/demo) on my side and it seems to work as expected on iOS. 

Regarding to the `mode` option, you should choose one of the available options [here](https://github.com/NathanWalker/nativescript-loading-indicator#ios-specific). For further info you could review the plugins `README` file in Github.

If you have further issues with the plugin, please log them in the plugin's repo. For general questions you could use StackOverflow.

Regards,
@tsonevn

**Comment by narender56** [comment]
Hey @tsonevn , thanks a lot, it's working fine now.
