### ISSUE TITLE
Feature Request: XML conditional tag

### ISSUE THREAD

**Issue by vbresults** [NativeScript/NativeScript#3483]
It would be great if we could evaluate conditions and group on them, in a standardized way.

Introducing `<if>`

Before:
```xml
<ios>
```

After:
```xml
<if is="{{ ios }}">
```

Thoughts @NathanaelA @enchev ?

**Comment by NathanaelA** [comment]
I think I'm against both items.    I don't think it offers enough to make the added complexity that it would add to the building system. 

I personally just Dynamically Load in the extra pieces I need if there is a `if` type decision; this eliminates the time parsing code that won't be used initially.   Parsing is very costly in all reality; and the simpler your layouts can be; the faster it switches screens.   So adding more parsing does not seem like a good idea to me.

Btw; the `<Repeater>` control is actually identical to the `FOR`, not a `<ListView>`.

**Comment by vbresults** [comment]
@NathanaelA Looks like `<Repeater>` does the job for `<for>`, updating OP

**Comment by enchev** [comment]
Hey @vbresults,

If you write Angular {N} apps you can use [ngif ](https://angular.io/docs/ts/latest/api/common/index/NgIf-directive.html) and [ngfor](https://angular.io/docs/ts/latest/api/common/index/NgFor-directive.html)

**Comment by vbresults** [comment]
@enchev I don't use Angular

**Comment by enchev** [comment]
You can use also `visibility` property:
```XML
 <GridLayout visibility="{{ YourCondition ? 'visible' : 'collapsed' }}">
```
The binding will react immediately on property change and will update your layout while if we implement this at parsing stage you need to reload the page to re-run the parsing in order to execute your condition.

**Comment by vbresults** [comment]
I've been using the property that way, but syntactically it didn't feel right, that said I can see how much complexity it would add under the hood so closing this.
