### ISSUE TITLE
Provide Core NativeScript Modules for the New Android Design Support Library

### ISSUE THREAD

**Issue by FlipOneDev** [NativeScript/NativeScript#349]
Is this possible for the next update of NativeScript? Recent announcement of the Android Design Support Library here: http://android-developers.blogspot.com/2015/05/android-design-support-library.html

**Comment by valentinstoychev** [comment]
Hey @FlipOneDev - you should be able to consume the UI components directly, without us doing anything. Just add the library in the project. You can see how you can add such 3rd party libraries in [this article](http://docs.nativescript.org/runtimes/android/external-libs/jars).

Please let us know if you need further assistance.
