### ISSUE TITLE
Android: #1559 Regression - Image rotation from camera

### ISSUE THREAD

**Issue by zweimal** [NativeScript/NativeScript#3499]
Regression of issue #1559 "Image rotation from camera".
Tested on a Samsung Galaxy S3 (GT-I9300) with CyanogenMod 13 (Android 6.0.1) last SNAPSHOT (13.0.20161220)

Fix: Re-apply #1635 "fixed image rotation"

Thanks

**Comment by tsonevn** [comment]
Hi @zweimal,

I think that this issue is similar to the [other one](https://github.com/NativeScript/nativescript-camera/issues/24), which has been reported in the `nativescirpt-camera` repo.
Could you comment in the other issue?

Regards,
@tsonevn

**Comment by zweimal** [comment]
I will. Thanks for your quick answer
