### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by basarat** [NativeScript/NativeScript#350]
Requested here http://stackoverflow.com/questions/30970414/how-to-use-typescript-in-nativescript

I just downloaded https://github.com/NativeScript/NativeScript/releases/tag/v1.1.0 (https://github.com/NativeScript/NativeScript/releases/download/v1.1.0/nativescript-1.1.0.tgz) but don't see a `.d.ts` in the contents. 

Is it even provided / supported?

**Comment by hdeshev** [comment]
The definitions are shipped in a separate archive, usually called `tns-definitions-*.tgz`. You can find them linked in the [releases page](https://github.com/NativeScript/NativeScript/releases).

We are also [working](https://github.com/NativeScript/nativescript-cli/issues/493) on better TypeScript support in the NativeScript command-line tool. Until that ships, people can also use [this TypeScript sample project](https://github.com/hdeshev/nativescript-ts-hello) and its `grunt-ts`-based workflow  :wink: to quickly get an app running.

**Comment by basarat** [comment]
Thanks! I've updated my answer on SO. :rose:

**Comment by izackhub** [comment]
HI @basarat and @hdeshev is this still valid for the latest nativescript. I think it's 3.2. Or how might that be achieved in the latest version?
