### ISSUE TITLE
camera take pickture not stored on phone

### ISSUE THREAD

**Issue by Leo-lay** [NativeScript/NativeScript#3504]
Hi, i use the camera plugin and take pickture,and set the options **saveToGallery:true**  but i don't see the photo in the album.

ios:10.0.2(14A456)
nativescript:2.4.0

follow is my code 

```
onTakePhoto() {
        let options = {
            width: 600,
            height: 800,
            keepAspectRatio: false,
            saveToGallery: true
        };
        camera.takePicture(options).then(
            imageAsset => {
                console.log('imageAsset takePicture=>', imageAsset);
                // let source = imageSource.fromAsset(imageAsset);
                // this.saveFile(source);
                // this.makeImageFile(imageAsset);
                this.imageTaken = imageAsset;
                this.photoList.push(this.imageTaken);
                console.log('Size: ' + imageAsset.options.width + 'x' + imageAsset.options.height);
                // this.selections.push(imageAsset);
                console.log('imageAsset=>', JSON.stringify(imageAsset));
                this.photoList.forEach((item) => {
                    console.log('this.photoList=>', JSON.stringify(item));
                    console.log('length', this.photoList.length);
                });

            }).catch(error => {
                console.log('take photo error=>', error.message);
            });
    }
```

**Comment by tsonevn** [comment]
Hi @Leo-lay,

I have tested `nativescript-camera` plugin with [this ](https://github.com/NativeScript/nativescript-camera/tree/master/examples/CameraTest) sample project on `iOS` and it seems to work as expected. 
Could you verify, whether you will have the same problem, while using the sample project [here](https://github.com/NativeScript/nativescript-camera/tree/master/examples/CameraTest).
It will help if you could provide sample project, which could be debugged locally?

Regards,
@tsonevn

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-camera#25
