### ISSUE TITLE
How to add vibrate animation to the text field?

### ISSUE THREAD

**Issue by narender56** [NativeScript/NativeScript#3507]
Hi all,

I have a query ,when user remains some field empty in a form, i have to vibrate that filed. do we have these feature in nativescript ? Thanks in advance.

**Comment by tsonevn** [comment]
Hi @narender56, 

For your case you could use chaining animations, which should allow you to create such an animation.
For example you could create set of several  `translate` animations.
Example:

```
view.animate({ translate: { x: 0, y: 10 } })
    .then(() => view.animate({ translate: { x: 0, y: 0 } }))
    .then(() => view.animate({ translate: { x: 0, y: -10 } }))
    .then(() => view.animate({ translate: { x: 0, y: 0 } }))
    .then(() => view.animate({ translate: { x: 0, y: 10 } }))
    .then(() => view.animate({ translate: { x: 0, y: 0 } }))
    .then(() => view.animate({ translate: { x: 0, y: -10 } }))
    .then(() => view.animate({ translate: { x: 0, y: 0 } }))  
    .then(() => {
    console.log("Animation finished");
  })
    .catch((e) => {
    console.log(e.message);
  });
```

More about NativeScript animations could be found [here](https://docs.nativescript.org/ui/animation-code.html).
If this does not work for you, it would help if you could provide some more info about your case and needed animation.

**Comment by narender56** [comment]
thanks @tsonevn ,awesome it working. But it is moving very slowly,how to make it vibrate faster?

**Comment by tsonevn** [comment]
Hi @narender56,

You can setup several properties to the animations. In your case you could setup the `duration` of every animation. For more info and samples, you could review [this ](https://docs.nativescript.org/cookbook/ui/animation#animating-properties) section in the documentation.

**Comment by narender56** [comment]
thanks @tsonevn
