### ISSUE TITLE
Polyfills to enable browser-based libraries to work in {N} project

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#351]
Lets collect common [polyfills](https://remysharp.com/2010/10/08/what-is-a-polyfill) that need to be implemented in NativeScript in order to support browser-based libraries.

We already have support for [XHR](https://github.com/NativeScript/NativeScript/blob/9a8fdbc6f593e27216f6968a2fa77ba1771aebad/http/http.ts#L35), which enables libraries that work with cloud data to work out of the box in NativeScript, but what would be other polyfills that we can add to NativeScript?

A good starting point will be an example of a browser library that you want to run inside NativeScript app.

**Comment by RangerMauve** [comment]
Websockets are probably the biggest, followed by canvas. Maybe the [notifications api](http://www.html5rocks.com/en/tutorials/notifications/quick/)

**Comment by bfattori** [comment]
WebSockets, WebGL, Canvas, and something for audio is on my immediate list.

**Comment by emiloberg** [comment]
WebSockets indeed! For all thing realtime.

**Comment by bfattori** [comment]
I have a _near complete_ WebSocket plugin... But, as I'm not an iOS developer, I could only get the Android side working. I grabbed **java_websockets** (android) and **JetFire** (iOS) to be the implementations since I've used the Android one before and JetFire was recommended. I should have a browser-esque WebSocket implementation any day now.

**Comment by bfattori** [comment]
I now have the iOS side working, but as yet not fully tested.

**Comment by valentinstoychev** [comment]
Hey @bfattori is the plugin available on Github or somewhere else to check it out? 

We are planning to open a *verified* plugins marketplace in August and if you are interested you can publish it there. I can provide you with more information in case you are interested.

**Comment by bfattori** [comment]
Unfortunately, no. I wrote the code for my company. I'm trying to get them
to open source it, but I've been told it probably won't happen. I'll keep
pushing though. It's now working on both iOS and Android, so I'd love for
others to be able to use it.

Are the plugins meant to be free (open source) or pay-for, or either?

Thanks,
Brett

**Comment by valentinstoychev** [comment]
They can free or paid and there is no need for them to be open sourced. They can be licensed with any license - proprietary included. cc:/ @kiril-stanoev

**Comment by Nathanaela** [comment]
@valentinstoychev - I have an android version that I will be releasing in a couple days.   Looking at the IOS side right now.    ;-)

**Comment by emmanuelbuah** [comment]
@bfattori  Tell your company they are using nativescript for free. If they can't contribute a plugin in return then ....they aren't being fair and should be ashamed. 
@Nathanaela Thanks for all your hard work. Per https://github.com/NativeScript/NativeScript/issues/167, i have just been swamped to work on this. The community will be grateful for your contribution. If you have a repro, kindly share it with @valentinstoychev and the community. Thanks.

**Comment by Nathanaela** [comment]
Fully functional websockets for iOS and android are finally released.  http://fluentreports.com/blog/?p=95 for more details.

**Comment by emmanuelbuah** [comment]
@Nathanaela Thanks for the hard work. Will check it out.

**Comment by emmanuelbuah** [comment]
@valentinstoychev How about flexbox layout as layout engine?

**Comment by hshristov** [comment]
HI @emmanuelbuah,

Are there any particular problem you are facing with our current layout support? Is it hard to understand and/use? Any scenario that you cannot cover with it?
It will be of great help if we identify current issues that people are struggling with.

**Comment by dbbk** [comment]
@hshristov I think the current Layout engine is fine, but it's very specific to NativeScript. One of the big benefits of the platform is skills reuse - allowing web developers to come over to building native mobile apps. Being able to use (a subset) of CSS is a great start, but if the CSS support expanded to supporting layout structures like grid/flexbox, it'd be even easier for developers to adopt the platform.

**Comment by emmanuelbuah** [comment]
Per my answer at https://github.com/NativeScript/NativeScript/issues/191#issuecomment-138198221

Its widely known/used since its part of the css 3 spec. It will make it easy for developers coming from the web tech to get up and running rather than learn a new layout engine. This by no means assert that the current layout engine is bad. I just think adaptation will be faster and easier for devs coming from js/web tech.

@hshristov spot on

**Comment by hshristov** [comment]
What bugs me in the flexbox layout is that it is supposed to be used without changing the html. I'm by no means html, css expert - quite the opposite so please correct me if I'm wrong. You just mark one element as flexbox container and that's it. But in the native platforms (like Android and WU) elements cannot be added everywhere. Only ViewGroup (in Android) can have children.

So it will not be possible to specify the layout using only CSS. One should have something like FlexboxLayout element somewhere in the XML.

Doesn't this defeat the purpose of flexbox?

**Comment by valentinstoychev** [comment]
I agree with most that flexbox is very well suited for NativeScript. The most important part is that it is known and will not require additional learning. I'm also sure that the current layout implementation in NativeScript is much more powerful and enables many scenarios.

With that said - I think that the core team behind the project can focus on bringing additional features and other core capabilities to the product and the flexbox layout will be a very good task for the community to work on. It can be easily distributed as a plugin via npm and anyone will be able to easily consume it.

If someone decides to put some development cycles into this I'm sure @hshristov  will help you out with any questions during the development.

**Comment by enchev** [comment]
I've created separate issue for flexbox https://github.com/NativeScript/NativeScript/issues/1650

**Comment by enchev** [comment]
I'm closing this since it is too general.
