### ISSUE TITLE
More than 1 view added to Page works on Android, not on iOS

### ISSUE THREAD

**Issue by bradleygore** [NativeScript/NativeScript#3518]
I've written a plugin that makes use of an AbsoluteLayout being programmatically add to the Page for the purpose of making a material-inspired dropdown list. It was built testing against Android, as I had no Mac at that time, and then once I got a Mac I found that it does not work on iOS.

I've opened [this issue](https://github.com/bradleygore/nativescript-materialdropdownlist/issues/4) in my repo, however I think that there may be some improvement to how this is handled in NativeScript. 

The root issue is that the `Page` entity is derived from `ContentView` and is set up to only have 1 `content` View (I didn't realize this when first building the plugin :p ). That being said, it seems like it should be doable to allow an arbitrary number of AbsoluteLayout elements to be a child of a Page - for purposes such as this, or other use cases. So, that's what I'd like to request - if it's at all possible. Otherwise, it may be beneficial to note this in the `Page` documentation that this is possible on Android, just not iOS.

### Verification
I read through the source code once I realized it didn't work on iOS and found this limitation of the Page. I've linked to the appropriate source code files in the open issue in my repo.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.4.2
- Cross-platform modules: 2.4.4
- Runtime(s): iOS: 2.4.0    android: 2.4.1

### Please tell us how to recreate the issue in as much detail as possible.
Clone the repo for my plugin and run the demo. You can use npm scripts from the root of the project: `npm run demo.[ios|android]`. Notice that it renders the additional view onto the Page in Android, but not in iOS. I've used debug tools to verify that It does successfully add the AbsoluteLayout view and calculate placement for the subsequent ListView for the dropdown list, but it doesn't appear on the page (maybe renders outside the already existing layout within the page or something?).

**Comment by manoldonev** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Thank you!
