### ISSUE TITLE
filter listview

### ISSUE THREAD

**Issue by ginger89** [NativeScript/NativeScript#3519]
hi . i have one problem . i use item tap in the list view. i add search bar to filter mylist . the problem is when i search,its work but when i tap to the item its read main item index,not item that i select . please help me. huhu

**Comment by NickIliev** [comment]
Hey, @ginger89 the issues of NativeScript are meant for logging and resolving potential bugs and features. For more how-to related questions I recommend using the SO community channel [here](http://stackoverflow.com/questions/tagged/nativescript). Also provide a code snippet or sample project of what you have achieved so far in order for your question to be reproduced as easy as possible from other users.

**Comment by pedromorgan** [comment]
So I have the same problem and consider this a bug.. or missing something

the itemTapEvent event returns the `ListViewEventData` 
https://docs.telerik.com/devtools/nativescript-ui/api/classes/radlistview.html#itemtapevent

https://docs.telerik.com/devtools/nativescript-ui/api/classes/listvieweventdata.html
which has an index (am not using grouping)
and the index is kinda incorrect when filtered

The filtered list has say 5 items visible, from around 500+
- index 3 is assumed tapped
- getting data from lisview with  `listView.getItemAtIndex(args.index)` return data from source array, not the filtered list
- getting data from the model presents the same data
- the index being returned should point somehow to the filtered data
```ts
export function onListViewItemTap(args){
    console.log("index=" + args.index);
    // get data item from listview #BUG#
    var recList = listView.getItemAtIndex(args.index);
    console.log(recList.company)

    // get data item from model
    var recModel = accountsModel.items.getItem(args.index);
    console.log(recModel.company)
}
```

**Comment by pedromorgan** [comment]
However the "itemSelected" event returns correct index
