### ISSUE TITLE
Extending modules with ES6?

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#3523]
I cannot seem to extend a module the right way using ES6. Say if I want to extend an Observable, the typeName should become the one that the new class name was assigned. But the typeName becomes blank:

```js
var Observable = require("data/observable").Observable;

var Test = class Test extends Observable {
  constructor() {
    super();
    this.foo = "bar";
    this.bar = true;
  }
};

var testInstance = new Test();
console.log(testInstance.typeName); // Returns a blank string
```

Is it not possible to extend modules this way yet or have I missed a step somewhere?

**Comment by NickIliev** [comment]
@NordlingArt 

Your code would work if written in TypeScript. Here is a [sample project](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/NativeScript/issue_3523_tsc/app/main-page.ts) that demonstrates it. The good thing about the TS projects is that it auto-transpile your code to JS so you can see the actual output written in JS ;)

Here is the code in JavaScript needed to extend an Observable

```
function navigatingTo(args) {
    var testInstance = new Test();
    console.log(testInstance.typeName); // prints Test
}
exports.navigatingTo = navigatingTo;

var observable_1 = require("data/observable");

var Test = (function (_super) {
    __extends(Test, _super);
    function Test() {
        var _this = _super.call(this) || this;
        _this.foo = "bar";
        _this.bar = true;
        return _this;
    }
    return Test;
}(observable_1.Observable));
```

**Comment by NordlingArt** [comment]
@ - Ah, I see. So oblygt in TS it works. The sample you provided is how I do it currently. Just hoped it would work with ES6 in plain JS 🙂
