### ISSUE TITLE
How to refresh webview using nativescript-pulltorefresh module?

### ISSUE THREAD

**Issue by narender56** [NativeScript/NativeScript#3525]
Hi everyone ,

I have scenario, where i have to refresh the data and map in a webview for certain period of time. I'm able to get the data dynamically using setInterval but i have to update data on webview map without reloading the map. Can anyone please suggest any ideas? thanks in advance.

**Comment by vjoao** [comment]
@narender56 Please leave general questions to StackOverflow or even better the NativeScript Slack channel.

**Comment by narender56** [comment]
Hey @vjoao , i'm not finding any helpful there,that's y i've raised issue here
