### ISSUE TITLE
Create class to manipulate my view

### ISSUE THREAD

**Issue by mobilemindtec** [NativeScript/NativeScript#3527]
Hi,

I'm trying create a class to manipulate my view events. 

```
// coffescript
class ActivityView
	# on load event
	onLoaded: (args) ->
		@page = args.object	
		@viewModel = new ActivityViewModel() 
                @page.bindingContext = @viewModel

       onTap: (args) ->
               # @viewModel is null here

module.exports = ActivityView
// or 
module.exports = new ActivityView()
```

but this not work.. How I can do this?

**Comment by NickIliev** [comment]
@mobilemindtec 

In NativeScript the technique used to convert data from Java to JavaScript is called marshalling.
More about how to handle data conversion can be found in [this documentation section](https://docs.nativescript.org/angular/runtimes/android/overview.html).

Useful information  can be found [here ](https://docs.nativescript.org/angular/runtimes/android/marshalling/java-to-js.html)and [here](https://docs.nativescript.org/angular/code-samples/ui/web-view.html)
