### ISSUE TITLE
Issue with routing on android activity resumed [NS + NG]

### ISSUE THREAD

**Issue by echap** [NativeScript/NativeScript#3532]
Hi there, I'm facing a new issue that may be related to the nativescript activity resuming.

###What I want :
Someone receives a notification through FCM. *On click on the notification, the app is launched* : I want to reroute my user depending on a parameter that is contained on my notification.

In app.component.ts :

```
//Does the same thing in the constructor
ngOnInit() {
application.android.onActivityResumed = (activity) => {
      if(activity.getIntent() && activity.getIntent().getExtras() && activity.getIntent().getExtras().getString("required_route")){
          let required_route = activity.getIntent().getExtras().getString("required_route");
          console.log("I am routing now");
          this._routerExtensions.navigate([required_route]);
      }
    };
}
```

###What I have :
The app is launched well, the `I am routing now` is on my log, but I don't get re-routed.
This is not an issue with my variable `required_route` which is correct & tested.

More surprising, after the  `I am routing now`, I get another log `Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.` which is basically the first log I usually have on app launch.

### Note :
The process works if I do this : 
```
application.android.onActivityResumed = (activity) => {
      this._routerExtensions.navigate(["my_route"]);
    };
```
(with usual resume, not from notification click).

Do you have a hint ?

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#647
