### ISSUE TITLE
how to convert a specific view into an image ?

### ISSUE THREAD

**Issue by c1ngular** [NativeScript/NativeScript#3540]
Hi, i have been watching Nativescript on Github for a while , it is a wonderful project ! good work !
i am wondering , is it possible to convert a view into an image ? if possible , how ?  i want to convert a specific view (not the screen , a listview , but some items are off-screen, but i need it all) into an image  and send the image to social networks ?

**Comment by bradmartin** [comment]
If it's possible with native apps then you bet it's possible with nativescript :) there are very few limitations between full native and nativescript by now. Anyway to your question, on Android it's fairly simple. I am on phone or I'd convert this for you but in this SO post it's shown how to take a native view and output and image. http://stackoverflow.com/a/3527902/1893557 very little code to do it on Android.

**Comment by c1ngular** [comment]
@bradmartin, thank you !

**Comment by bradmartin** [comment]
Here is a rough attempt with that approach, not tested so not sure if all the pieces work but hopefully gives you a head start 😄 

### XML
```xml
<StackLayout id="makeImage">
    <Button text="Hi" />
</StackLayout
```

### JS
```js
var ViewModule = require("ui/core/view");

const CompressFormat = android.graphics.Bitmap.CompressFormat;
const FileOutputStream= java.io.FileOutputStream;

/// run the following during some event, a button tap to make the image or whatever

let makeImage = ViewModule.getViewById("makeImage"); /// the stacklayout ^^^
makeImage.android.setDrawingCacheEnabled(true);
var myBitmap = makeImage.getDrawingCache();
myBitmap.compress(CompressFormat.PNG, 95, new FileOutputStream("filePathToSomewhere");
```

That is a rough conversion, I have not tested and the FileOutputStream you could likely use the NativeScript `file-system` module to save the image using a different approach.

**Comment by c1ngular** [comment]
@bradmartin，really appreciated ! By the way, you have a wonderful blog !
