### ISSUE TITLE
Code is not running after http request in view model

### ISSUE THREAD

**Issue by Brutia** [NativeScript/NativeScript#3542]
I have this view model

        
     export class CommandeViewModel extends Observable {

        constructor() {
              super();
              this.isLoading = true;
              this.apiService = new ApiService();

             this.listeInfo = new observableArray.ObservableArray();
     
            this.apiService.getInfo().then(
            function (data) {
                
                this.listeInfo.push({ title: "test", message: "test" });
                console.log("Not reached");
     
            },
            function (e) {
                alert("impossible de récupérer les infos de la liste");
            }
        );

I would like to fill listeInfo with data but there is an issue, the code is not runned after the http request.

Here is the code of ApiService:

    import http = require("http");

    export default class ApiService {

      public url: string;
      constructor() {//public http: Http
        this.url = "http://url/api/";

    }

   

    getInfo() {
        return http.getJSON(this.url + 'getInfo');

    }

    }
  
here is my nativescript version:

`All NativeScript components versions information

│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.4.2           │ 2.4.2          │ Up to date    │
│ tns-core-modules │ 2.4.4           │ 2.4.4          │ Up to date    │
│ tns-android      │ 2.4.1           │ 2.4.1          │ Up to date    │
│ tns-ios          │                 │ 2.4.0          │ Not installed │`

Can anyone help me?

**Comment by tsonevn** [comment]
Hi @Brutia,

Thank you for reporting your problem,

I reviewed the case and found that the problem could be related with missed `getter` for the  `listeInfo ` property in `CommandeViewModel `.

While extending Observable modules, you should also define getter and setter for the properties in the ViewModel. In your case, you could define 
```
get listeInfo():any{
        return this._listeInfo;
    }
```
which returns the array.
For further help I am attaching example related to the above-given code. 
main-page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">

    <GridLayout>
        <ListView items="{{ listeInfo }}"  loaded="onLoaded" itemLoading="onItemLoading" itemTap="onItemTap">
            <ListView.itemTemplate>
                <StackLayout>
                    <Label text="{{name}}" textWrap="true" />
                    
                </StackLayout>
            </ListView.itemTemplate>
        </ListView>
    </GridLayout>
</Page>
```
main-page.ts
```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { CommandeViewModel } from './main-view-model';

export function navigatingTo(args: EventData) {

    let page = <Page>args.object;

    page.bindingContext = new CommandeViewModel();
}
```
main-view-model.ts
```
import {Observable} from 'data/observable';
import {ObservableArray} from "data/observable-array"
import {ApiService} from "./apiService"

 export class CommandeViewModel extends Observable {
    private apiService;
    public _listeInfo:ObservableArray<any>;
    constructor() {
          super();
          this.apiService = new ApiService();

         this._listeInfo = new ObservableArray();
 
        this.apiService.getInfo().then(
            (data) => {
                data.args.name.forEach(element=>{
                    this._listeInfo.push({name:element});
                })
                console.log("Not reached");
    
            },
            (e) => {
                alert("impossible de récupérer les infos de la liste");
            }
        )
    }
    get listeInfo():any{
        return this._listeInfo;
    }

 
```
apiService.ts
```
import http = require("http");

export class ApiService {

  public url: string;
  constructor() {//public http: Http
    this.url = "https://httpbin.org/get?name=name&message=ms1&name=name2&message=ms2&name=name3&message=ms3";

}



getInfo() {
    return http.getJSON(this.url + 'getInfo');

}

}
```
For further help, you could also review the comment on [this ](https://github.com/NativeScript/NativeScript/issues/1863#issuecomment-208861894) issue.

**Comment by Brutia** [comment]
It works well.

Thanks a lot!
