### ISSUE TITLE
TextField Editable=false, textWrap="true" not working?

### ISSUE THREAD

**Issue by dlucidone** [NativeScript/NativeScript#3545]

**Comment by NickIliev** [comment]
Hey, @dlucidone  I have tested text-field with both options (Editable=false, textWrap="true" ) and it works as expected on my side. [Here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_3545) you can find a sample test application that demonstrates the behaviour.

Please provide additional information for that issue - including code snippet demonstrating the probnlem and the platform on which it occurs and also the model of the device/emulator you are using.

**Comment by dlucidone** [comment]
Hey, @NickIliev  thanks for the quick response 
Here's my code snippet I'm Using

#### TS Code
`public longName="This is a Very Long String so its text should be wraped to new line but this is not happening"`

#### HTML Code
`<TextField hint="Select Lead" [(ngModel)]="longName" textWrap = "true" editable= "false" ></TextField>`

I'm building application for android on OSX
`Android version : 2.4.1`
`tns-core-modules : 2.4.0`
`nativescript-angular: 1.1.3`

![screen shot 2017-01-31 at 6 01 52 pm](https://cloud.githubusercontent.com/assets/9256365/22464975/75778ee8-e7df-11e6-90a6-a45b6a3596fe.png)


Thanks

**Comment by NickIliev** [comment]
@dlucidone 

Instead of _TextField_ use **TextView**
e.g.
```
<TextView [(ngModel)]="longName"  editable="false" textWrap="true"></TextView>
```

**Comment by dlucidone** [comment]
@NickIliev  Tried stil not working.
Suppose If i have to make it editable based on some input and not editable for some with text wrap property being true in all cases is it possible. Thanks

**Comment by ChirantanPatel** [comment]
@NickIliev thanks i also faceing same issue and solve it.

**Comment by brianha** [comment]
Remember that it is "editable" and not Editable".... that helped me.

**Comment by kumaratc** [comment]
thanks helped me.
