### ISSUE TITLE
Why doesn't ListView inherit from ScrollView?

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#3546]
I only have experience with iOS development. But why doesn't ListView have properties such as `scrollableHeight` and `scrollableWidth`? Or events such as `scroll`?

In iOS (at least), UITableView is a subclass of UIScrollView which both provide the same native properties. Is it just a matter of consistency between iOS and Android, or is there a better explanation to why I cannot observe a ListView's scrolling position?

**Comment by NickIliev** [comment]
The list-view module is using [android.widget.ListView](https://developer.android.com/reference/android/widget/ListView.html) for its Android implementation while behind ScrollView lies [android.widget.HorizontalScrolView](https://developer.android.com/reference/android/widget/HorizontalScrollView.html) (or vertical) so basically we have two different native controls with different implementations. Comparing to HorizontalScrollView, the ListView for Android presets much more functionality for listing data and also has specific optimisations so this is the logical choice to implement in nativeScript as well.

If you need a custom scroll for your list-view under Android then you can access the native methods

e.g.
```

var list = page.getViewById("myList");
list.android.smoothScrollByOffset(10);
// or
list.android.smoothScrollToPosition(10);
```

API references [here](https://developer.android.com/reference/android/widget/ListView.html#smoothScrollByOffset(int)) and [here](https://developer.android.com/reference/android/widget/ListView.html#smoothScrollToPosition(int))

**Comment by NordlingArt** [comment]
@NickIliev - I was never asking for an Android solution, but more specifically for iOS 😛  Problem is that I want to create a custom scroll indicator for ListView, but since I cannot observe the scrolling event (as with a ScrollView), it's impossible to do so.

**Comment by NickIliev** [comment]
@NordlingArt my bad - somehow I was under the impression that we are talking about Android.

Behind ListView in iOS stands an implementation of [UITableView](https://developer.apple.com/reference/uikit/uitableview) (subclass of [UIScrollView](https://developer.apple.com/reference/uikit/uiscrollview)). .You can use [estimatedRowHeight](https://developer.apple.com/reference/uikit/uitableview/1614925-estimatedrowheight) and similar native properties like:
```

public onListLoaded(args) {
   var list = args.object;
   console.log(list);
   console.log(list.ios.estimatedRowHeight);
}
```
Now to set the offset in UIScrollView in native project you acn use [contentOffset](https://developer.apple.com/reference/uikit/uiscrollview/1619404-contentoffset).
So to create a method like **_scroll_** (scrollToOffset) with native code you can do the following:

```
console.log(list.ios.contentOffset.y) // initial y content
var point = CGMake(0, 200); // set CGPoint with x and y
list.ios.setContentOffsetAnimated(point, false);

console.log(list.ios.contentOffset.y) // y is now updated
```
