### ISSUE TITLE
Closing modal dialog causes ns-ng app to crash on older Android versions (API 17 or 19)

### ISSUE THREAD

**Issue by honrust** [NativeScript/NativeScript#3547]
Android API < 20 only.

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.4.2
- Cross-platform modules: 2.4.4
- Runtime(s): tns-android: 2.4.1, tns-ios: 2.4.0

### Please tell us how to recreate the issue in as much detail as possible.
Run the sdk-examples-ng app on Android API 17. Open the modal dialog page, open dialog, and close it using the submit button. App crashes.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
App crashes on this line:
https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/modal-page/sample-modal-page-module-example/modal-view.ts#L29

(see also https://github.com/NativeScript/nativescript-sdk-examples-ng/issues/154 which I opened for the same issue)

**Comment by tsonevn** [comment]
Hi @honrust ,

This behavior with could be reproduced on some `Android` ARM emulator with API level lower the 20 . 
However, this problem has been related only with `Android` emulators and modal dialogs should be working as expected on a real device.

Regard to that could you provide some more info about the emulator, which you are using for testing. The best solution is to use a real device for testing.

Regards,
@tsonevn

**Comment by honrust** [comment]
Thanks for the reply! I was testing on Nexus 4.2.2, API 17 using Genymotion on my macBook.  I'll try testing on a real device as soon as I get my hands on one!

**Comment by NickIliev** [comment]
@honrust we haven't heard from you for a while - closing this one due to inactivity but please fell free to comment and add information regarding your case.

**Comment by honrust** [comment]
Oh please don't close. I'll be looking into the info this week.

**Comment by tsonevn** [comment]
Hi @honrust,
We have not heard from you for a while. Do you have the same issue on a real device?

**Comment by honrust** [comment]
Hi, thanks for getting back to this issue. We recently upgraded to NS 2.5. The problem seems gone now. Issue can be closed.
