### ISSUE TITLE
Nativescript geolocation is not working in Android

### ISSUE THREAD

**Issue by narender56** [NativeScript/NativeScript#3548]
Hello everyone,

I've used nativescript-geoloaction module for getting coords of a user, it's working in ios perfectly but in android it's not. Please can anyone suggest any idea to get coords in android or is there any other module to do?

**Comment by tsonevn** [comment]
Hi @narender56,
I reviewed your case, however, was unable to reproduce problems while using `nativescript-geolocation` plugin. For your convenience, I am attaching a link to the plugin's demo.

Regard to the topic, your problem could be related with an update time of the location. You could manage this time while setting up `minimumUpdateTime` property. For example:
```
export function buttonStartTap(agrs: EventData) {
    watchId = geolocation.watchLocation(
        function (loc) {
            if (loc) {
                model.locations.push(loc);
            }
        },
        function (e) {
            console.log("Error: " + e.message);
        },
        { desiredAccuracy: Accuracy.high, updateDistance: 0.1, minimumUpdateTime: 10 });
}
```

It would help if you could provide some more info and sample project, which could be debugged locally.
