### ISSUE TITLE
iOS css styles are not working on xml

### ISSUE THREAD

**Issue by terhoraj** [NativeScript/NativeScript#3549]
cssClasses which work and android does not work on iOS even when iOS css is loaded at app.js properly. Only inline css works which makes development sluggish and hard.

Using ns 2.4.2 ios 2.4.0 so all the latest stuff

**Comment by tsonevn** [comment]
Hi @terhoraj,
Could you provide some more info about the problem? 
It would help if you could give us some more info about your environment(`CLI` `node` versions). Could you also provide some code snippets or sample project, which could be debugged locally?

Thank you in advance for your cooperation.

**Comment by tsonevn** [comment]
Hi @terhoraj,
You could try to upgrade to latest NativeScirpt 2.5.0 and to verify, whether you will have the same behavior. Instructions, how to do that could be found [here](http://docs.nativescript.org/releases/upgrade-instructions).
To upgrade the dependencies for your project, you could use `tns update` command. 

Before rebuilding your app you should also remove `platforms`, `node_modules` and `hooks` folders from your project and to clear npm cache while using `npm cache clear`.
