### ISSUE TITLE
NativeScript Video Player is not working

### ISSUE THREAD

**Issue by narender56** [NativeScript/NativeScript#3551]
Hello everyone,

I have to stream a video lively, so i have used the nativescript-videoplayer module, but i've clone the project and  initiated tns run, but it throwing following error.Can anyone please tell me how to resolve the error?

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.demo/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: Building UI from XML. @file:///app/main-page.xml:16:9
 > Module '/data/data/org.nativescript.demo/files/app/nativescript-videoplayer' not found for element 'nativescript-videoplayer:Video'.
   > com.tns.NativeScriptException: Failed to find module with absolute path: "/data/data/org.nativescript.demo/files/app/nativescript-videoplayer".
      com.tns.Module.resolvePathHelper(Module.java:220)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:862)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:727)
    com.tns.Runtime.callJSMethod(Runtime.java:713)
    com.tns.Runtime.callJSMethod(Runtime.java:694)
    com.tns.Runtime.callJSMethod(Runtime.java:684)
    com.tns.NativeScriptActivity.onCreate(NativeScriptActivi

**Comment by tsonevn** [comment]
Hi @narender56,
I just tested `nativescript-videoplayer` [demo](https://github.com/bradmartin/nativescript-videoplayer/tree/master/demo) with latest NativeScirpt 2.5 and the plugin seems to work as expected on both Android and iOS.
You could try to update your NativeScript , while following the instructions [here](http://docs.nativescript.org/releases/upgrade-instructions#upgrading-the-nativescript-tools) and to upgrade the demo app dependencies in its `package.json` file.

```
{
  "nativescript": {
    "id": "org.nativescript.demo",
    "tns-ios": {
      "version": "2.5.0"
    },
    "tns-android": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "nativescript-videoplayer": "*",
    "tns-core-modules": "^2.5.0"
  },
  "devDependencies": {
    "babel-traverse": "6.8.0",
    "babel-types": "6.8.1",
    "babylon": "6.8.0",
    "filewalker": "0.1.2",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^1.8.10"
  }
}

```

Hope this helps.

**Comment by bradmartin** [comment]
I'm guessing one of two things caused your issue.
1. https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/
2. You didn't add the xmlns to the page (plain nativescript) or registerElement() with angular.

As for streaming I've never tried that with the plugin, it's using native default video controls and I'm not sure how good they are with streaming.

**Comment by NickIliev** [comment]
This issue was moved to bradmartin/nativescript-videoplayer#55
