### ISSUE TITLE
Heap snapshot package version mismatch

### ISSUE THREAD

**Issue by dxshindeo** [NativeScript/NativeScript#3555]
Updated nativescript to:
nativescript-cli: 2.5.0
tns-core-modules: 2.5.0
nativescript-angular-snapshot: 1.4.0-5.5.372.32

When building android release mode, I am getting warning:

> Required heap snapshot package is not installed. Installing "nativescript-angular-snapshot@latest-1.3.0-5.5.372.32".
> Could not find package "nativescript-angular-snapshot@latest-1.3.0-5.5.372.32" in the registry.
> Build will now continue without using heap snapshots ...

... which results in slower and +7mb larger app.

**Comment by vchimev** [comment]
Hey @dxshindeo,

could you please update to `nativescript-angular@1.4.0` as well?

**Comment by dxshindeo** [comment]
Forgot to mention it, it is at 1.4.0 already.

**Comment by vchimev** [comment]
@dxshindeo, could you please share your `package.json` file?

**Comment by dxshindeo** [comment]
```
..
  "nativescript": {
    "id": "com.test.test",
    "tns-android": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.4.5",
    "@angular/compiler": "2.4.5",
    "@angular/core": "2.4.5",
    "@angular/forms": "2.4.5",
    "@angular/http": "2.4.5",
    "@angular/platform-browser": "2.4.5",
    "@angular/platform-browser-dynamic": "2.4.5",
    "@angular/router": "3.4.5",
    "nativescript-angular": "1.4.0",
    "nativescript-angular-snapshot": "1.4.0-5.5.372.32",
    "nativescript-geolocation": "0.0.18",
    "nativescript-gif": "^1.0.8",
    "nativescript-google-maps-sdk": "^1.4.3",
    "nativescript-platform-css": "^1.4.0",
    "nativescript-vibrate": "^1.1.2",
    "reflect-metadata": "^0.1.9",
    "rxjs": "5.1.0",
    "tns-core-modules": "2.5.0",
    "tns-platform-declarations": "^2.4.4"
  },
  "devDependencies": {
    "babel-traverse": "6.22.1",
    "babel-types": "6.22.0",
    "babylon": "6.15.0",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.3.6",
    "typescript": "^2.1.5",
    "zone.js": "^0.7.6"
  }
..
```

**Comment by vchimev** [comment]
Thanks, @dxshindeo! I didn't manage to reproduce it.

My guess is that the `nativescript-dev-android-snapshot` plugin gets confused for the version of `nativescript-angular`. However, I'd suggest to delete the *node_modules* and *platforms* and rebuild again android for release.

**Comment by dxshindeo** [comment]
I think I had not deleted _hooks_ folder, now it compiles correctly with the appropriate snapshot, thank you :)
