### ISSUE TITLE
ListView triggering tap event unexpectedly after scrolling

### ISSUE THREAD

**Issue by tones411** [NativeScript/NativeScript#3559]
## Please, provide the details below:
I have a concern about the ListView. I created the starter app using `tns create "TestAppNG" --ng`. I run it in iOS and I see the ListView. If I scroll the list about a centimeter, and then let up with my finger, it triggers a tap on the row my finger was on. That felt strange to me. I didn't expect it to actually tap the row, since I scrolled slightly. To confirm my suspicion, I opened the iOS Settings app, scrolled that list just slightly and then let up. As expected it did not trigger a tap on the row my finger was on.

### Which platform(s) does your issue occur on?
iOS (I haven't tried it on Android)

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.0
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): tns-ios 2.5.0

**Comment by tsonevn** [comment]
Hi @tones411,
Thank you for interest in NativeScript Angular 2.

I reviewed your case and found that this issue has been related to `nsRouterLink` directive and the fact that has been attached to the Label, which contains the `item.name`. In this case the navigation will be start and if you scroll about a centimeter.

We will research this problem and will verify, whether this is something related with NativeScirpt.

Regard to that, the best way to handle the selected ListView item is to use `itemTap` method, which will be fired just after selected some row in the component. I am providing an example.

`HTML`

```
<StackLayout class="page">
    <ListView [items]="items" class="list-group" (itemTap)="onItemTap($event)">
        <template let-item="item">
            <Label  [text]="item.name"
                class="list-group-item"></Label>
        </template>
    </ListView>
</StackLayout>
```

`TypeScript`
```
export class ItemsComponent implements OnInit {
    items: Item[];

    ......
    onItemTap(args:ItemEventData){
        alert(args.index);
    }
}
```

For further help, you could also review the sample app [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/ui-category/listview/creating-listview).

Hope this helps.

**Comment by tsonevn** [comment]
Fixed with PR[#45](https://github.com/NativeScript/template-hello-world-ng/pull/45)

**Comment by JoHuang** [comment]
I tried this https://github.com/NativeScript/nativescript-sdk-examples-ng
and the list view tap behavior is the same.
Is that the same issue?

**Comment by tsonevn** [comment]
Hi @JoHuang,
We will verify whether this is the same behavior with `nativescritp-sdk-examples-ng` and if so we will make the needed changes in it.

**Comment by JoHuang** [comment]
hi @tsonevn 

I checked the code, and I'm sure that it's the same behaviour and the solution of hello world project works, too.

However, the solution,using the javascript code to route instead of **nsRouterLink**, means you have to change every component.ts file in the example project (so many).
I have no time to make a pull request for you, sorry.

Jo
