### ISSUE TITLE
Webview loadFinishedEvent does not get triggered in NativeScript 2.4

### ISSUE THREAD

**Issue by sudhanshu-15** [NativeScript/NativeScript#3564]
Hello, I am using webview in my code, where I have to monitor for the LoadEventData constantly till the correct value is obtained. My code runs perfectly fine on NativeScript 2.3 but after updating to 2.4 the code stoped working. It seems the loadFinishedEvent is not getting triggered. For now I have downgraded to NativeScript 2.3 but I can explore more and send some code if people think this could be a bug with NativeScript 2.4
This is the call that I am making:

`webView.on(webViewModule.WebView.loadFinishedEvent, function(args: webViewModule.LoadEventData)`

**Comment by tsonevn** [comment]
Hi @sudhanshu-15,

I tested your case with latest NativeScirpt 2.5, however, was unable to reproduce the problem with WebView loadFinishEvent. 
You could upgrade to latest NS while following the instructions here and to verify, whether you will have the same problem.

I am also attaching sample code:

main-page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page">

    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>
    
    <GridLayout rows="100 *" columns="*">
        <Button row="0" col="0" text="Change WebSite" tap="onChange" />
    
        <WebView row="1" col="0" src="{{someurl}}" loaded="webviewLoad"/>
        
    </GridLayout>
</Page>

```
main-page.ts
```
import { EventData, Observable } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import {WebView, LoadEventData} from "ui/web-view";

var tmpObservable:Observable;
export function navigatingTo(args: EventData) {

    let page = <Page>args.object;
    
    tmpObservable = new Observable();
    tmpObservable.set("someurl", "https://www.google.com")

    page.bindingContext = tmpObservable;
}

export function webviewLoad(args){
    var webView=args.object;
    webView.on(WebView.loadFinishedEvent, function (args: LoadEventData) {

        let message;
        if (!args.error) {
            message = "WebView finished loading " + args.url;
        }
        else {
            message = "Error loading " + args.url + ": " + args.error;
        }
        alert(message);
    });
}

export function onChange(){
    tmpObservable.set("someurl", "https://plus.google.com/communities/117408587889337015711")
}
```

if this does not resolve your problem, please could you send us some more code snippets or sample project, where the problem could be debugged locally.

**Comment by sudhanshu-15** [comment]
@tsonevn Thanks for looking into this, I upgraded to 2.5.0 and the code seems to working fine. Thanks a lot.
