### ISSUE TITLE
ActionBar transparent background crahses on android  with NS 2.5.0

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#3565]
_From @ullalaaron on February 2, 2017 15:24_

Setting 
```
ActionBar{
         background-color : transparent;
}
```
makes the Android app crash.

_Copied from original issue: NativeScript/nativescript-cli#2479_

**Comment by NickIliev** [comment]
Reproduced with [this test app ](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_3565)

@ullalaaron as a workaround to achieving transparent background you can use **rgba** and control your alpha channel 

e.g.
```
ActionBar{
         background-color : rgba(200, 54, 54, 0.5); 
}
```

**Comment by NathanaelA** [comment]
@ullalaaron - I mentioned this on my blog; http://fluentreports.com/blog/?p=479   -- it isn't just `transparent`; it is ALL named colors.   You need to use `#00000000` or the `rgba(r,g,b,a)` for any colors on the actionbar.

**Comment by vakrilov** [comment]
Managed to reproduce it with `transparent` and fix is on the way.
However, other named color(ex. `red`, `green`, etc.) worked as expected. @NathanaelA can you give more information about which colors caused a crash on your end?

**Comment by NathanaelA** [comment]
To my knowledge any color name will do it.   But it was _random_ according to @triniwiz   He was also using Angular2; but I wouldn't think that should matter...
