### ISSUE TITLE
How to extend nativescript application further in Android Studio with Java Code and Activity?

### ISSUE THREAD

**Issue by dlucidone** [NativeScript/NativeScript#3566]
I'm building a android app and now i'm stuck as i have to use a android library. I have created a separate project in Android studio and completed my functionality. Now i have to merge these two components.How can I do that? Thanks

**Comment by tsonevn** [comment]
Hi @dlucidone,
Thank you for your interest in NativeScirpt.

In your case, you could create your own custom plugin, which implements needed functionality from your native project and allows you to use it in your `NativeScirpt` app. 
For your help, I am attaching several articles, which could help to understand how to create `NativeScirpt`  plugin.

* https://docs.nativescript.org/plugins/plugins
* http://blog.bradleygore.com/2016/04/18/my-first-nativescript-plugin/
* http://fluentreports.com/blog/?p=167
* http://developer.telerik.com/featured/creating-nativescript-plugins-in-typescript/
* http://developer.telerik.com/featured/write-nativescript-plugins-theyre-easier-cordova-plugins/

Hope this helps.

**Comment by dlucidone** [comment]
@tsonevn thank You so much for the quick reply.

I found this [(https://github.com/enchev/android-ng2-tns)] for extending my application. Hope it will Work for me. Please close the Issue in case i need help i'll ask to reopen it.

**Comment by dlucidone** [comment]
Hey @tsonevn , I merged the two applications and I'm using the below code to switch activity from android to nativescript.

        public void openNativeScriptActivity() {
        com.tns.Runtime runtime = com.tns.RuntimeHelper.initRuntime(MainActivity.this.getApplication());
        if(runtime != null) {
            runtime.run();

            android.content.Intent intent = new android.content.Intent(MainActivity.this,   MyCustomNativeScriptActivity.class);
            intent.setAction(android.content.Intent.ACTION_DEFAULT);
            startActivity(intent);
        }
    }


Now I want to call some activity defined in android from nativescript. How can i do that.Thanks

**Comment by dlucidone** [comment]
@tsonevn Any Help on the above I'm stuck on this thing. Thanks

**Comment by tsonevn** [comment]
Hi @dlucidone,
Thank you for writing us back.
Could you provide some more info about your case and what you are trying to achieve?
Regard to your last comment I understand that you would like to extend existing native app while using `NativeScript`.
If this is your case, you could review [this ](http://docs.nativescript.org/angular/integration-with-existing-ios-and-android-apps/extend-existing-android-app-with-ns-angular2.html)article, where this scenario has been described.

Regards,
@tsonevn

**Comment by dlucidone** [comment]
@tsonevn Yess, with the above method i have merged the applications but now what i'm trying to do is -
![screen shot 2017 02 06 at 7 50 48 pm](https://cloud.githubusercontent.com/assets/9256365/22652153/5a7a438a-ecab-11e6-93e0-a694bb7abe80.png)


call addEvent activity described in java from nativescript app.component. Thanks
