### ISSUE TITLE
Nativescript 2.5.0 can't synchronize changes into device, ENOENT and EACCES errors

### ISSUE THREAD

**Issue by S4M37** [NativeScript/NativeScript#3569]
I'm using NativeScript 2.5.0 with Angular2, using android platform with building tool 25.0.2, I'm testing on a device, and `tns doctor` no issues are found. So my problem is when running 'tns run android' the app is launched but no changes are applied, here is the log

> Project successfully prepared (android)
Transferring project files...
Unable to sync files. Error is: ENOENT: no such file or directory, stat 'C:\Users\S4M37\Desktop\CrossPlatform\project\platforms\android\src\main\assets\app\modules\feed\item\feed.item.css___jb_tm
p___'
02-03 15:16:18.512  5693  5693 W System.err: remove failed: EACCES (Permission denied) : /data/local/tmp/org.nativescript.project/sync/tns_modules/rxjs/src/MiscJSDoc.ts
02-03 15:16:18.532  5335  5335 E audit   : type=1400 msg=audit(1486131378.512:526786): avc:  denied  { unlink } for  pid=5693 comm="tivescript.project" name="MiscJSDoc.ts" dev="dm-1" ino=335142 s
context=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=file permissive=0
02-03 15:16:18.562  5693  5693 W System.err: remove failed: EACCES (Permission denied) : /data/local/tmp/org.nativescript.project/sync/tns_modules/rxjs/src/observable/dom/MiscJSDoc.ts
02-03 15:16:18.582  5335  5335 E audit   : type=1400 msg=audit(1486131378.562:526982): avc:  denied  { unlink } for  pid=5693 comm="tivescript.project" name="MiscJSDoc.ts" dev="dm-1" ino=335340 s
context=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=file permissive=0
JS: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
02-03 15:16:22.322  5693  5693 W ExifInterface:         at com.tns.Runtime.callJSMethodNative(Native Method)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#2485
