### ISSUE TITLE
(iOS) Mis-rotated camera when started from a horizontally-rotated view

### ISSUE THREAD

**Issue by ErjanGavalji** [NativeScript/NativeScript#357]
In iOS 8.x, when the button, starting the camera app gets tapped from a horizontally-rotated device, the camera is rotated too. Thus, moving the device up and down, the image moves right and left and vice-versa.

[Here is a project](https://github.com/ErjanGavalji/nativescript-horizontal-camera-error), created with NativeScript 1.1.0, demonstrating the problem. Just `tns platform add ios` and `tns run ios` it, then rotate the device horizontally and press the button to get the unexpected experience.

**Comment by hamorphis** [comment]
http://stackoverflow.com/questions/14618546/force-landscape-orientation-in-uiimagepickercontroller/16346664#16346664

As per the [UIImagePickerController Class Reference][1]

> **Important**: The `UIImagePickerController` class supports portrait mode only. This class is intended to be used as-is and does not support subclassing. The view hierarchy for this class is private and must not be modified, with one exception. You can assign a custom view to the [cameraOverlayView][2] property and use that view to present additional information or manage the interactions between the camera interface and your code.

So it looks like forcing landscape mode is unsupported and discouraged, unless you do so by replacing the default controls with a custom `cameraOverlayView`.

  [1]: http://developer.apple.com/library/ios/documentation/uikit/reference/UIImagePickerController_Class/UIImagePickerController/UIImagePickerController.html#//apple_ref/doc/uid/TP40007070-CH3-DontLinkElementID_1
  [2]: http://developer.apple.com/library/ios/documentation/uikit/reference/UIImagePickerController_Class/UIImagePickerController/UIImagePickerController.html#//apple_ref/occ/instp/UIImagePickerController/cameraOverlayView

**Comment by hamorphis** [comment]
We can not inherit from the UIImagePickerController and hack it since Apple might reject the app. Do so at your own risk.

**Comment by ErjanGavalji** [comment]
Well, some things in life aren't pleasing :)

![](http://24.media.tumblr.com/0e28faae2ce73796864a1720eecac5cc/tumblr_mn3pogYBV61rzxujso1_500.gif)
