### ISSUE TITLE
Debug on device does not sync file changes

### ISSUE THREAD

**Issue by bnussey** [NativeScript/NativeScript#3575]
When using debug mode on device (works as expected on emulator), it does not sync new files with the following error message:

`Unable to sync files. Error is: Unable to kill the application.`

This results in having to re-run the debug command
Here's full logs:

```
Executing before-prepare hook from /Users/blake/Documents/ns/app/hooks/before-prepare/nativescript-dev-typescript.js
Preparing project...
Project successfully prepared (iOS)
Executing after-prepare hook from /Users/blake/Documents/ns/app/hooks/after-prepare/nativescript-unit-test-runner.js
Transferring project files...
Successfully transferred asset-manager.models.js.
Successfully synced application com.stageme.app on device 1a33b375679bbb440fb6dbfcad31ea28bb1ed8af.

Frontend socket closed!
Unable to sync files. Error is: Unable to kill the application.
```

**Comment by mounirka** [comment]
Hi @bnussey are you using the command tns run android ?

**Comment by tsonevn** [comment]
Hi @bnussey,

I reviewed your case, however, was unable to reproduce such a problem. Regard to that, could you provide some more info about your problem and exact steps, which you are following?
I tested your case `tns run <platform_name>`, which will automatically start livesync and it seems to work as expected.

Regards,
@tsonevn

**Comment by bnussey** [comment]
Hey all,

Sorry, left that key bit of information out. The command I use is tns run debug ios

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#2500
