### ISSUE TITLE
DEPLOYMENT_TARGET_CLANG_FLAG_NAME PreBuild Issues building on OSX 10.11.6

### ISSUE THREAD

**Issue by nickp60** [NativeScript/NativeScript#3577]
### Tell us about the problem
Hi!  I am having trouble building a ios project. I have made the test app with `tns create`, built successfully for android, and keep getting an error on `tns build ios`. The error seems to occur when the metadata checking python script is looking for DEPLOYMENT_TARGET_CLANG_FLAG_NAME in the environment and not finding it.  The variable is not set during the initial shell script.

Any advice would be useful!  I have seen these errors posted elsewhere on the web, but not in relation to NativeScript.  This is my first time trying to develop for iOS , so there could be something simple I am missing.  Thanks in advance!

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.0
- cocoapods-1.2.0
- Runtime(s): tns-ios 2.5.0
- xcode 6.4
- xcodeproj-1.4.2
- xcproj-0.2.1

### Please tell us how to recreate the issue in as much detail as possible.
`tns create test`
`tns build android` (works as expected)
`tns build ios`

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Here is the log:

me$ tns build ios

$ tns build ios
Skipping prepare.
Building project...
Build settings from command line:
    ARCHS = i386 x86_64
    CODE_SIGN_IDENTITY = 
    CONFIGURATION_BUILD_DIR = /Users/ me/test/platforms/ios/build/emulator
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphonesimulator8.4
    SHARED_PRECOMPS_DIR = /Users/ me/test/platforms/ios/build/sharedpch
    VALID_ARCHS = i386 x86_64

=== BUILD TARGET test OF PROJECT test WITH CONFIGURATION Debug ===

Check dependencies

PhaseScriptExecution NativeScript\ PreBuild build/test.build/Debug-iphonesimulator/test.build/Script-C97FD7AC1ADE5369004DB2A4.sh
    cd /Users/ me/test/platforms/ios
    export ACTION=build
    export AD_HOC_CODE_SIGNING_ALLOWED=NO
    export ALTERNATE_GROUP=staff
    export ALTERNATE_MODE=u+w,go-w,a+rX
    export ALTERNATE_OWNER= me
    export ALWAYS_SEARCH_USER_PATHS=NO
    export ALWAYS_USE_SEPARATE_HEADERMAPS=YES
    export APPLE_INTERNAL_DEVELOPER_DIR=/AppleInternal/Developer
    export APPLE_INTERNAL_DIR=/AppleInternal
    export APPLE_INTERNAL_DOCUMENTATION_DIR=/AppleInternal/Documentation
    export APPLE_INTERNAL_LIBRARY_DIR=/AppleInternal/Library
    export APPLE_INTERNAL_TOOLS=/AppleInternal/Developer/Tools
    export APPLICATION_EXTENSION_API_ONLY=NO
    export APPLY_RULES_IN_COPY_FILES=NO
    export ARCHS="i386 x86_64"
    export ARCHS_STANDARD="i386 x86_64"
    export ARCHS_STANDARD_32_64_BIT="i386 x86_64"
    export ARCHS_STANDARD_32_BIT=i386
    export ARCHS_STANDARD_64_BIT=x86_64
    export ARCHS_STANDARD_INCLUDING_64_BIT="i386 x86_64"
    export ASSETCATALOG_COMPILER_APPICON_NAME=AppIcon
    export ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME=LaunchImage
    export AVAILABLE_PLATFORMS="iphonesimulator macosx iphoneos"
    export BUILD_COMPONENTS="headers build"
    export BUILD_DIR=/Users/ me/test/platforms/ios/build
    export BUILD_ROOT=/Users/ me/test/platforms/ios/build
    export BUILD_STYLE=
    export BUILD_VARIANTS=normal
    export BUILT_PRODUCTS_DIR=/Users/ me/test/platforms/ios/build/emulator
    export CACHE_ROOT=/var/folders/hd/0_5q8vyd0nz1p0bg88vs1xlm0000gn/C/com.apple.DeveloperTools/6.4-6E35b/Xcode
    export CCHROOT=/var/folders/hd/0_5q8vyd0nz1p0bg88vs1xlm0000gn/C/com.apple.DeveloperTools/6.4-6E35b/Xcode
    export CHMOD=/bin/chmod
    export CHOWN=/usr/sbin/chown
    export CLANG_CXX_LANGUAGE_STANDARD=gnu++0x
    export CLANG_CXX_LIBRARY=libc++
    export CLANG_ENABLE_MODULES=NO
    export CLANG_ENABLE_OBJC_ARC=YES
    export CLANG_MODULES_AUTOLINK=NO
    export CLANG_MODULES_BUILD_SESSION_FILE=/var/folders/hd/0_5q8vyd0nz1p0bg88vs1xlm0000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation
    export CLANG_WARN_BOOL_CONVERSION=YES
    export CLANG_WARN_CONSTANT_CONVERSION=YES
    export CLANG_WARN_DIRECT_OBJC_ISA_USAGE=YES_ERROR
    export CLANG_WARN_EMPTY_BODY=YES
    export CLANG_WARN_ENUM_CONVERSION=YES
    export CLANG_WARN_INT_CONVERSION=YES
    export CLANG_WARN_OBJC_ROOT_CLASS=YES_ERROR
    export CLANG_WARN__DUPLICATE_METHOD_MATCH=YES
    export CLASS_FILE_DIR=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build/JavaClasses
    export CLEAN_PRECOMPS=YES
    export CLONE_HEADERS=NO
    export CODESIGNING_FOLDER_PATH=/Users/ me/test/platforms/ios/build/emulator/test.app
    export CODE_SIGNING_ALLOWED=NO
    export CODE_SIGN_CONTEXT_CLASS=XCiPhoneSimulatorCodeSignContext
    export COLOR_DIAGNOSTICS=YES
    export COMBINE_HIDPI_IMAGES=NO
    export COMMAND_MODE=legacy
    export COMPOSITE_SDK_DIRS=/var/folders/hd/0_5q8vyd0nz1p0bg88vs1xlm0000gn/C/com.apple.DeveloperTools/6.4-6E35b/Xcode/CompositeSDKs
    export COMPRESS_PNG_FILES=YES
    export CONFIGURATION=Debug
    export CONFIGURATION_BUILD_DIR=/Users/ me/test/platforms/ios/build/emulator
    export CONFIGURATION_TEMP_DIR=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator
    export CONTENTS_FOLDER_PATH=test.app
    export COPYING_PRESERVES_HFS_DATA=NO
    export COPY_PHASE_STRIP=NO
    export COPY_RESOURCES_FROM_STATIC_FRAMEWORKS=YES
    export CP=/bin/cp
    export CREATE_INFOPLIST_SECTION_IN_BINARY=NO
    export CURRENT_ARCH=x86_64
    export CURRENT_VARIANT=normal
    export DEAD_CODE_STRIPPING=NO
    export DEBUGGING_SYMBOLS=YES
    export DEBUG_INFORMATION_FORMAT=dwarf-with-dsym
    export DEFAULT_COMPILER=com.apple.compilers.llvm.clang.1_0
    export DEFAULT_KEXT_INSTALL_PATH=/System/Library/Extensions
    export DEFINES_MODULE=NO
    export DEPLOYMENT_LOCATION=NO
    export DEPLOYMENT_POSTPROCESSING=NO
    export DERIVED_FILES_DIR=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build/DerivedSources
    export DERIVED_FILE_DIR=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build/DerivedSources
    export DERIVED_SOURCES_DIR=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build/DerivedSources
    export DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
    export DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export DEVELOPER_FRAMEWORKS_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
    export DEVELOPER_FRAMEWORKS_DIR_QUOTED=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
    export DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Library
    export DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
    export DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Tools
    export DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
    export DEVELOPMENT_LANGUAGE=English
    export DOCUMENTATION_FOLDER_PATH=test.app/English.lproj/Documentation
    export DO_HEADER_SCANNING_IN_JAM=NO
    export DSTROOT=/tmp/test.dst
    export DT_TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
    export DWARF_DSYM_FILE_NAME=test.app.dSYM
    export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT=NO
    export DWARF_DSYM_FOLDER_PATH=/Users/ me/test/platforms/ios/build/emulator
    export EFFECTIVE_PLATFORM_NAME=-iphonesimulator
    export EMBEDDED_CONTENT_CONTAINS_SWIFT=NO
    export ENABLE_BITCODE=NO
    export ENABLE_HEADER_DEPENDENCIES=YES
    export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS=".DS_Store .svn .git .hg CVS"
    export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES="*.nib *.lproj *.framework *.gch (*) .DS_Store CVS .svn .git .hg *.xcodeproj *.xcode *.pbproj *.pbxproj"
    export EXECUTABLES_FOLDER_PATH=test.app/Executables
    export EXECUTABLE_FOLDER_PATH=test.app
    export EXECUTABLE_NAME=test
    export EXECUTABLE_PATH=test.app/test
    export EXPANDED_CODE_SIGN_IDENTITY=
    export EXPANDED_CODE_SIGN_IDENTITY_NAME=
    export EXPANDED_PROVISIONING_PROFILE=
    export FILE_LIST=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build/Objects/LinkFileList
    export FIXED_FILES_DIR=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build/FixedFiles
    export FRAMEWORKS_FOLDER_PATH=test.app/Frameworks
    export FRAMEWORK_FLAG_PREFIX=-framework
    export FRAMEWORK_SEARCH_PATHS="/Users/ me/test/platforms/ios/build/emulator /Users/ me/test/platforms/ios/internal/ ../../lib/iOS"
    export FRAMEWORK_VERSION=A
    export FULL_PRODUCT_NAME=test.app
    export GCC3_VERSION=3.3
    export GCC_C_LANGUAGE_STANDARD=gnu99
    export GCC_DYNAMIC_NO_PIC=NO
    export GCC_INLINES_ARE_PRIVATE_EXTERN=YES
    export GCC_OBJC_LEGACY_DISPATCH=YES
    export GCC_OPTIMIZATION_LEVEL=0
    export GCC_PFE_FILE_C_DIALECTS="c objective-c c++ objective-c++"
    export GCC_PRECOMPILE_PREFIX_HEADER=YES
    export GCC_PREFIX_HEADER=test/test-Prefix.pch
    export GCC_PREPROCESSOR_DEFINITIONS=" DEBUG=1"
    export GCC_SYMBOLS_PRIVATE_EXTERN=NO
    export GCC_TREAT_WARNINGS_AS_ERRORS=NO
    export GCC_VERSION=com.apple.compilers.llvm.clang.1_0
    export GCC_VERSION_IDENTIFIER=com_apple_compilers_llvm_clang_1_0
    export GCC_WARN_64_TO_32_BIT_CONVERSION=YES
    export GCC_WARN_ABOUT_RETURN_TYPE=YES_ERROR
    export GCC_WARN_UNDECLARED_SELECTOR=YES
    export GCC_WARN_UNINITIALIZED_AUTOS=YES
    export GCC_WARN_UNUSED_FUNCTION=YES
    export GCC_WARN_UNUSED_VARIABLE=YES
    export GENERATE_MASTER_OBJECT_FILE=NO
    export GENERATE_PKGINFO_FILE=YES
    export GENERATE_PROFILING_CODE=NO
    export GID=20
    export GROUP=staff
    export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT=YES
    export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES=YES
    export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS=YES
    export HEADERMAP_INCLUDES_PROJECT_HEADERS=YES
    export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES=YES
    export HEADERMAP_USES_VFS=NO
    export HEADER_SEARCH_PATHS="/Users/ me/test/platforms/ios/build/emulator/include  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include \"/Users/ me/test/platforms/ios/internal\""
    export ICONV=/usr/bin/iconv
    export INFOPLIST_EXPAND_BUILD_SETTINGS=YES
    export INFOPLIST_FILE=/Users/ me/test/platforms/ios/test/test-Info.plist
    export INFOPLIST_OUTPUT_FORMAT=binary
    export INFOPLIST_PATH=test.app/Info.plist
    export INFOPLIST_PREPROCESS=NO
    export INFOSTRINGS_PATH=test.app/English.lproj/InfoPlist.strings
    export INSTALL_DIR=/tmp/test.dst/Applications
    export INSTALL_GROUP=staff
    export INSTALL_MODE_FLAG=u+w,go-w,a+rX
    export INSTALL_OWNER= me
    export INSTALL_PATH=/Applications
    export INSTALL_ROOT=/tmp/test.dst
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export JAVAC_DEFAULT_FLAGS="-J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8"
    export JAVA_APP_STUB=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
    export JAVA_ARCHIVE_CLASSES=YES
    export JAVA_ARCHIVE_TYPE=JAR
    export JAVA_COMPILER=/usr/bin/javac
    export JAVA_FOLDER_PATH=test.app/Java
    export JAVA_FRAMEWORK_RESOURCES_DIRS=Resources
    export JAVA_JAR_FLAGS=cv
    export JAVA_SOURCE_SUBDIR=.
    export JAVA_USE_DEPENDENCIES=YES
    export JAVA_ZIP_FLAGS=-urg
    export JIKES_DEFAULT_FLAGS="+E +OLDCSO"
    export KEEP_PRIVATE_EXTERNS=NO
    export LD_DEPENDENCY_INFO_FILE=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build/Objects-normal/x86_64/test_dependency_info.dat
    export LD_GENERATE_MAP_FILE=NO
    export LD_MAP_FILE_PATH=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build/test-LinkMap-normal-x86_64.txt
    export LD_NO_PIE=NO
    export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER=YES
    export LD_RUNPATH_SEARCH_PATHS=" @executable_path/Frameworks"
    export LEGACY_DEVELOPER_DIR=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
    export LEX=lex
    export LIBRARY_FLAG_NOSPACE=YES
    export LIBRARY_FLAG_PREFIX=-l
    export LIBRARY_KEXT_INSTALL_PATH=/Library/Extensions
    export LIBRARY_SEARCH_PATHS="/Users/ me/test/platforms/ios/build/emulator "
    export LINKER_DISPLAYS_MANGLED_NAMES=NO
    export LINK_FILE_LIST_normal_i386=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build/Objects-normal/i386/test.LinkFileList
    export LINK_FILE_LIST_normal_x86_64=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build/Objects-normal/x86_64/test.LinkFileList
    export LINK_WITH_STANDARD_LIBRARIES=YES
    export LOCALIZED_RESOURCES_FOLDER_PATH=test.app/English.lproj
    export LOCAL_ADMIN_APPS_DIR=/Applications/Utilities
    export LOCAL_APPS_DIR=/Applications
    export LOCAL_DEVELOPER_DIR=/Library/Developer
    export LOCAL_LIBRARY_DIR=/Library
    export MACH_O_TYPE=mh_execute
    export MAC_OS_X_PRODUCT_BUILD_VERSION=15G31
    export MAC_OS_X_VERSION_ACTUAL=101106
    export MAC_OS_X_VERSION_MAJOR=101100
    export MAC_OS_X_VERSION_MINOR=1106
    export NATIVE_ARCH=i386
    export NATIVE_ARCH_32_BIT=i386
    export NATIVE_ARCH_64_BIT=x86_64
    export NATIVE_ARCH_ACTUAL=x86_64
    export NO_COMMON=YES
    export OBJC_ABI_VERSION=2
    export OBJECT_FILE_DIR=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build/Objects
    export OBJECT_FILE_DIR_normal=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build/Objects-normal
    export OBJROOT=/Users/ me/test/platforms/ios/build
    export ONLY_ACTIVE_ARCH=NO
    export OPTIMIZATION_LEVEL=0
    export OS=MACOS
    export OSAC=/usr/bin/osacompile
    export OTHER_LDFLAGS=" -ObjC -sectcreate __DATA __TNSMetadata \"/Users/ me/test/platforms/ios/build/emulator/metadata-x86_64.bin\" -framework NativeScript -F\"/Users/ me/test/platforms/ios/internal\" -licucore -lz -lc++ -framework Foundation -framework UIKit -framework CoreGraphics -framework MobileCoreServices -framework Security"
    export PACKAGE_TYPE=com.apple.package-type.wrapper.application
    export PASCAL_STRINGS=YES
    export PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Tools:/Users/ me/.rvm/gems/ruby-2.3.0/bin:/Users/ me/.rvm/gems/ruby-2.3.0@global/bin:/Users/ me/.rvm/rubies/ruby-2.3.0/bin:/Users/ me/riboseedVE/riboSeedbin/sratoolkit.2.8.1-mac64/bin:/Users/ me/riboseedVE/riboSeedbin/bwa-0.7.12:/Users/ me/riboseedVE/riboSeedbin/barrnap-0.7/bin:/Users/ me/riboseedVE/riboSeedbin/samtools-1.3.1:/Users/ me/riboseedVE/riboSeedbin/quast-4.4:/Users/ me/riboseedVE/riboSeedbin/SPAdes-3.9.1-Darwin/bin:/Users/ me/riboSeedVE/riboSeedbin/sratoolkit.2.8.1-mac64/bin:/Users/ me/riboSeedVE/riboSeedbin/bwa-0.7.12:/Users/ me/riboSeedVE/riboSeedbin/barrnap-0.7/bin:/Users/ me/riboSeedVE/riboSeedbin/samtools-1.3.1:/Users/ me/riboSeedVE/riboSeedbin/quast-4.4:/Users/ me/riboSeedVE/riboSeedbin/SPAdes-3.9.1-Darwin/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/local/ncbi/blast/bin:/Library/TeX/texbin:/Users/ me/.rvm/bin"
    export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES="/usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms"
    export PBDEVELOPMENTPLIST_PATH=test.app/pbdevelopment.plist
    export PFE_FILE_C_DIALECTS=objective-c
    export PKGINFO_FILE_PATH=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build/PkgInfo
    export PKGINFO_PATH=test.app/PkgInfo
    export PLATFORM_DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications
    export PLATFORM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin
    export PLATFORM_DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer/Library
    export PLATFORM_DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs
    export PLATFORM_DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Tools
    export PLATFORM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr
    export PLATFORM_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
    export PLATFORM_NAME=iphonesimulator
    export PLATFORM_PREFERRED_ARCH=i386
    export PLATFORM_PRODUCT_BUILD_VERSION=12H141
    export PLATFORM_VERSION_AVAILABILITY_H_FORMAT=80400
    export PLIST_FILE_OUTPUT_FORMAT=binary
    export PLUGINS_FOLDER_PATH=test.app/PlugIns
    export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR=YES
    export PRECOMP_DESTINATION_DIR=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build/PrefixHeaders
    export PRESERVE_DEAD_CODE_INITS_AND_TERMS=NO
    export PRIVATE_HEADERS_FOLDER_PATH=test.app/PrivateHeaders
    export PRODUCT_MODULE_NAME=test
    export PRODUCT_NAME=test
    export PRODUCT_SETTINGS_PATH=/Users/ me/test/platforms/ios/test/test-Info.plist
    export PRODUCT_TYPE=com.apple.product-type.application
    export PROFILING_CODE=NO
    export PROJECT=test
    export PROJECT_DERIVED_FILE_DIR=/Users/ me/test/platforms/ios/build/test.build/DerivedSources
    export PROJECT_DIR=/Users/ me/test/platforms/ios
    export PROJECT_FILE_PATH=/Users/ me/test/platforms/ios/test.xcodeproj
    export PROJECT_NAME=test
    export PROJECT_TEMP_DIR=/Users/ me/test/platforms/ios/build/test.build
    export PROJECT_TEMP_ROOT=/Users/ me/test/platforms/ios/build
    export PUBLIC_HEADERS_FOLDER_PATH=test.app/Headers
    export RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS=YES
    export REMOVE_CVS_FROM_RESOURCES=YES
    export REMOVE_GIT_FROM_RESOURCES=YES
    export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES=YES
    export REMOVE_HG_FROM_RESOURCES=YES
    export REMOVE_SVN_FROM_RESOURCES=YES
    export REZ_COLLECTOR_DIR=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build/ResourceManagerResources
    export REZ_OBJECTS_DIR=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build/ResourceManagerResources/Objects
    export REZ_SEARCH_PATHS="/Users/ me/test/platforms/ios/build/emulator "
    export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES=NO
    export SCRIPTS_FOLDER_PATH=test.app/Scripts
    export SCRIPT_INPUT_FILE_COUNT=0
    export SCRIPT_OUTPUT_FILE_COUNT=0
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk
    export SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk
    export SDK_NAME=iphonesimulator8.4
    export SDK_PRODUCT_BUILD_VERSION=12H141
    export SED=/usr/bin/sed
    export SEPARATE_STRIP=NO
    export SEPARATE_SYMBOL_EDIT=NO
    export SET_DIR_MODE_OWNER_GROUP=YES
    export SET_FILE_MODE_OWNER_GROUP=NO
    export SHALLOW_BUNDLE=YES
    export SHARED_DERIVED_FILE_DIR=/Users/ me/test/platforms/ios/build/emulator/DerivedSources
    export SHARED_FRAMEWORKS_FOLDER_PATH=test.app/SharedFrameworks
    export SHARED_PRECOMPS_DIR=/Users/ me/test/platforms/ios/build/sharedpch
    export SHARED_SUPPORT_FOLDER_PATH=test.app/SharedSupport
    export SKIP_INSTALL=NO
    export SOURCE_ROOT=/Users/ me/test/platforms/ios
    export SRCROOT=/Users/ me/test/platforms/ios
    export STRINGS_FILE_OUTPUT_ENCODING=binary
    export STRIP_INSTALLED_PRODUCT=YES
    export STRIP_STYLE=all
    export SUPPORTED_DEVICE_FAMILIES="1 2"
    export SUPPORTED_PLATFORMS="iphonesimulator iphoneos"
    export SYMROOT=/Users/ me/test/platforms/ios/build
    export SYSTEM_ADMIN_APPS_DIR=/Applications/Utilities
    export SYSTEM_APPS_DIR=/Applications
    export SYSTEM_CORE_SERVICES_DIR=/System/Library/CoreServices
    export SYSTEM_DEMOS_DIR=/Applications/Extras
    export SYSTEM_DEVELOPER_APPS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
    export SYSTEM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
    export SYSTEM_DEVELOPER_DEMOS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples"
    export SYSTEM_DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export SYSTEM_DEVELOPER_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library"
    export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools"
    export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Java Tools"
    export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Performance Tools"
    export SYSTEM_DEVELOPER_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes"
    export SYSTEM_DEVELOPER_TOOLS=/Applications/Xcode.app/Contents/Developer/Tools
    export SYSTEM_DEVELOPER_TOOLS_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools"
    export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools"
    export SYSTEM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
    export SYSTEM_DEVELOPER_UTILITIES_DIR=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
    export SYSTEM_DOCUMENTATION_DIR=/Library/Documentation
    export SYSTEM_KEXT_INSTALL_PATH=/System/Library/Extensions
    export SYSTEM_LIBRARY_DIR=/System/Library
    export TARGETED_DEVICE_FAMILY=1,2
    export TARGETNAME=test
    export TARGET_BUILD_DIR=/Users/ me/test/platforms/ios/build/emulator
    export TARGET_NAME=test
    export TARGET_TEMP_DIR=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build
    export TEMP_DIR=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build
    export TEMP_FILES_DIR=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build
    export TEMP_FILE_DIR=/Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build
    export TEMP_ROOT=/Users/ me/test/platforms/ios/build
    export TOOLCHAINS=com.apple.dt.toolchain.XcodeDefault
    export TREAT_MISSING_BASELINES_AS_TEST_FAILURES=NO
    export UID=501
    export UNLOCALIZED_RESOURCES_FOLDER_PATH=test.app
    export UNSTRIPPED_PRODUCT=NO
    export USER= me
    export USER_APPS_DIR=/Users/ me/Applications
    export USER_LIBRARY_DIR=/Users/ me/Library
    export USE_DYNAMIC_NO_PIC=YES
    export USE_HEADERMAP=YES
    export USE_HEADER_SYMLINKS=NO
    export VALIDATE_PRODUCT=NO
    export VALID_ARCHS="i386 x86_64"
    export VERBOSE_PBXCP=NO
    export VERSIONPLIST_PATH=test.app/version.plist
    export VERSION_INFO_BUILDER= me
    export VERSION_INFO_FILE=test_vers.c
    export VERSION_INFO_STRING="\"@(#)PROGRAM:test  PROJECT:test-\""
    export WRAPPER_EXTENSION=app
    export WRAPPER_NAME=test.app
    export WRAPPER_SUFFIX=.app
    export XCODE_APP_SUPPORT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Xcode
    export XCODE_PRODUCT_BUILD_VERSION=6E35b
    export XCODE_VERSION_ACTUAL=0640
    export XCODE_VERSION_MAJOR=0600
    export XCODE_VERSION_MINOR=0640
    export XPCSERVICES_FOLDER_PATH=test.app/XPCServices
    export YACC=yacc
    export arch=x86_64
    export diagnostic_message_length=80
    export variant=normal
    /bin/sh -c /Users/ me/test/platforms/ios/build/test.build/Debug-iphonesimulator/test.build/Script-C97FD7AC1ADE5369004DB2A4.sh
~/test/platforms/ios/internal/metadata-generator/bin ~/test/platforms/ios
Python version: 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
Traceback (most recent call last):
  File "./build-step-metadata-generator.py", line 35, in <module>
    deployment_target_flag_name = env("DEPLOYMENT_TARGET_CLANG_FLAG_NAME")
  File "./build-step-metadata-generator.py", line 12, in env
    return os.environ[env_name]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'DEPLOYMENT_TARGET_CLANG_FLAG_NAME'
Command /bin/sh failed with exit code 1

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution NativeScript\ PreBuild build/test.build/Debug-iphonesimulator/test.build/Script-C97FD7AC1ADE5369004DB2A4.sh
(1 failure)
Command xcodebuild failed with exit code 65
# build ios

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/ios-runtime#723
