### ISSUE TITLE
Android application slow start

### ISSUE THREAD

**Issue by mounirka** [NativeScript/NativeScript#3579]
Hi guys, after updating all my components to the 2.5.0 version, i re-compiled my application, and i noticed that with 2.5.0 version the app is slower than the previous version when it's launched.
I mean when you open it and the splashscreen appears, it take longer than before (3/4 seconds more) to open the app.

How can i solve this? Thank you.

**Comment by dxshindeo** [comment]
I am seeing the same issue, but for my phone it was ~2 second longer increase. I am trying to implement AoT in my app, so that it starts super fast. I suggest you try it too (http://docs.nativescript.org/angular/tooling/bundling-with-webpack.html).

**Comment by Pip3r4o** [comment]
@mounirka are you building in release? It is possible that the snapshot plugin is outdated to work with the previous v8 engine in the previous android runtime (2.4). At this point you can delete `node_modules` and `platforms`, 
`npm remove nativescript-angular-snapshot --save` or `npm remove tns-core-modules-snapshot --save` if you are not using angular in your project
`npm install nativescript-dev-android-snapshot --save-dev`
`tns platform add android`

**Comment by NickIliev** [comment]
@mounirka  can you share more information about your application e.g. your package.json content and if it is Angular based or NativeScript core.

**Comment by mounirka** [comment]
Hi guys, unfortunately i stopped working on the nativescript version of my app an i switched to a native version

**Comment by NickIliev** [comment]
Hey @mounirka sorry to hear that - still if you have time pelase llet us know on what app yu were experiencing those delay and with what environment settings (Angular vs core app, versions of Node.js, NativeScript CLI, runtimes, modules and eventually your app's package.json content)
