### ISSUE TITLE
Workers do not work in AoT compilated apps

### ISSUE THREAD

**Issue by dxshindeo** [NativeScript/NativeScript#3581]
Steps to reproduce:
1. Create a blank project: `tns create test --ng`
2. Install webpack for AoT support: `npm install --save-dev nativescript-dev-webpack`
3. Create a blank `sockets.js` file next to `app.component.ts`
4. In `app.component.ts` add this line calling a new thread: `var sockets_worker = new Worker('sockets');`

It compiles successfully, but when I open the app, it crashes and I get an error:
```
Failed to find module: "sockets"
```
That path worked fine in non-AoT version.
Perhaps, problem lies that this sockets.js file does not get copied/compiled into the project? Because now, when I implemented AoT, no .js file is being generated next to their respective .ts files. I guess that is the idea, because they were not used at all there. And since the sockets.js file is not a ts file, it might not get copied. 

Would like to get a fix on this asap, since it blocks production.

**Comment by Pip3r4o** [comment]
Hey @dxshindeo could you try passing a relative path to the `sockets` module, like so: `new Worker('./sockets')`? It appears like you are trying to require a global `sockets` module, while you are saying you want to load a local script.

More info: https://nodejs.org/api/modules.html#modules_file_modules

**Comment by dxshindeo** [comment]
2 things fixed this:
1. Yes, changing path to `./sockets` helped.
2. First point was not enough, my hunch was right, I had to add `{ from: "**/*.js" },` in `webpack,common.js` as described in here http://docs.nativescript.org/angular/tooling/bundling-with-webpack.html :

> If you need other files bundled with your app, find the CopyWebPackPlugin configuration in webpack.common.js, and add a new config

**Comment by dxshindeo** [comment]
Eh, unfortunately, getting rid of the error does not make the worker work. The post gets sent, but nothing gets received in the worker.

```
// app.component.ts
import { Component } from "@angular/core";
var sockets_worker = new Worker('./sockets');
@Component({
    selector: "ns-app",
    templateUrl: "app.component.html",
})
export class AppComponent {
	ngAfterViewInit() {

		console.log("poke sockets");
		sockets_worker.postMessage("test message");

		sockets_worker.onmessage = function(msg) {
			console.log("Received: ", msg);
		}
	}
}
```
```

// sockets.js
require('globals'); // necessary to bootstrap tns modules on the new thread

onmessage = function(msg) {
    console.log(JSON.stringify(msg.data, null, 4));

	postMessage("test back at ya");
}
```

**Comment by Pip3r4o** [comment]
@dxshindeo try logging something in the global scope of the `sockets.js` to verify that it is (not) being loaded. I'd also add error handlers (at least on the worker object) to see whether an error is thrown.

**Comment by dxshindeo** [comment]
JS: An unhandled error occurred in worker: undefined, line: 1 :
JS: Uncaught Error: com.tns.NativeScriptException: Failed to find module: "globals", relative to: app/tns_modules/

**Comment by dxshindeo** [comment]
I just checked my non AoT version app, this folder exists `platforms/android/src/main/assets/app/tns_modules`, but in AoT version, this folder does not exist.

**Comment by hdeshev** [comment]
It seems workers need extra care when working with webpack. Webpack-ed apps do not have a `tns_modules` folder as everything is bundled in 1-2 big JS files. We have several options here:

* Make your "worker" module not use any of the `tns-core-modules` code and just copy it to the target dir (using the webpack copy plugin) like you did above.
* Tweak the CommonsChunkPlugin by adding an entry for your "worker" module. That will probably require a "loader" module that requires the vendor chunk before the worker one. I am thinking about something like the auto-generated `starter.js`

The latter approach sounds both cumbersome and risky. We probably don't want to bundle the entire UI framework in a non-UI module just to be able to use a `console.log` statement. The best solution would probably be to use a separate entry point in the webpack config for the "worker" module, and include (duplicate) all referenced non-UI modules like `console`, `filesystem`, etc.

**Comment by dxshindeo** [comment]
Yeah I went with the first option, since the only tns module I was using there was to access the application data on phone. Thanks for the help!
