### ISSUE TITLE
IOS TextView hint din't display numeric

### ISSUE THREAD

**Issue by michaelchan1992** [NativeScript/NativeScript#3584]
I'm trying to set hint for TextView for numeric hint = "0.01" but it doesn't display anything. I tried to use alphabet hint = "abc" but it seem working fine.

xml:
< TextView  hint="0.00" />

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.0
- Cross-platform modules: 2.4.4
- Runtime(s): tns-android 2.4.1, tns-ios 2.4.0
- Plugin(s): "tns-core-modules": "^2.4.4"

**Comment by NickIliev** [comment]
Reproduced under iOS with tns-core-modules 2.5.0.

The issue appeared only when the digit is **0** or **0.00**;
Works as expected with any other digit and string.

Possible reason for this issue [here](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/text-view/text-view.ios.ts#L125)

@michaelchan1992  as a temporary workaround open your **_node_modules/tns-core-modules/ui/text-view/text-view.ios.js_** and modify [this line](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/text-view/text-view.ios.ts#L115) to this

```
        if (hint.toString() && !text) {
```

**Comment by michaelchan1992** [comment]
Thank for the solution, it work as expected.

**Comment by SvetoslavTsenov** [comment]
Tested with 3.0.0
