### ISSUE TITLE
Lazy Loading with service provider is not working?

### ISSUE THREAD

**Issue by dlucidone** [NativeScript/NativeScript#3586]
I'm trying lazy loading to improve the performance of app - 
My configs are -

`"tns-android": {
      "version": "2.6.0-next-2017-01-24-1639"
    }`
`"tns-core-modules": "2.4.0"`

I'm not able to call service and having issue with two way binding with ngModel.Thanks

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#658
