### ISSUE TITLE
iOS FormattedString issue

### ISSUE THREAD

**Issue by shivapersad** [NativeScript/NativeScript#3588]
I followed a post provided by a user in the Nativescript Slack Channel to create a button with an icon and text. Link to post here: http://forum.nativescript.org/t/create-multi-line-button-with-text-and-icon/162/8

After following the instructions in the post I was able to produce the button on the screen but the text color is blue. I want the text to be white. I have modified the CSS of the button to change the text color to white with "color: white" but this has not helped.

<img width="119" alt="ios_bluetext_button" src="https://cloud.githubusercontent.com/assets/17012660/22650653/8a153eec-ec56-11e6-8009-3dd6196a415a.png">

The code included in the post works fine with Android and the color of the text is white as intended from the CSS but it appears this does not work with iOS. Please assist in how I can change the text color of the button to white and if this can be addressed in a future release of Nativescript. I look forward to anyone's assistance. Thanks.

**Comment by tsonevn** [comment]
Hi @shivapersad ,
You should use `foregroundColor` property in case you would like to change the text color inside the `Span` component. For more info, you could also review the api-reference [here](https://docs.nativescript.org/api-reference/classes/_text_span_.span.html).

**Comment by shivapersad** [comment]
Thank you. This worked to resolve my issue.
