### ISSUE TITLE
calling Android intent activity from Nativescript component class?

### ISSUE THREAD

**Issue by dlucidone** [NativeScript/NativeScript#3589]
I'm trying to do something like this-
![screen shot 2017 02 06 at 7 50 48 pm](https://cloud.githubusercontent.com/assets/9256365/22651316/a8397fc6-eca8-11e6-9207-5930a6e56d62.png)

NativeScript activity is called as below -

     public void openNativeScriptActivity() {
        com.tns.Runtime runtime = com.tns.RuntimeHelper.initRuntime(MainActivity.this.getApplication());
        if(runtime != null) {
            runtime.run();

            android.content.Intent intent = new android.content.Intent(MainActivity.this, MyCustomNativeScriptActivity.class);
            intent.setAction(android.content.Intent.ACTION_DEFAULT);
            startActivity(intent);
        }
    }

Now I want my app to come back to android by calling add event activity defined in Java. Any help ! Thanks!

**Comment by dlucidone** [comment]
I'm juss stuck on this. Is there any way out from this. Thanks

**Comment by dlucidone** [comment]
Hey  @tjvantoll @hdeshev @alg @ligaz @jbristowe  can you help me figuring out how this can be achieved. Thanks

**Comment by tsonevn** [comment]
Hi @dlucidone ,

This behavior seems no to be a bug and it is not related to NativeScript modules. In my opinion, this discussion could continue in [StackOverflow](http://stackoverflow.com/questions/tagged/nativescript), where more people could take part in it and give you suggestions for your issue.

Regards,
@tsonevn

**Comment by dlucidone** [comment]
I have asked for this in nativescript slack account and nativescript forum still not able to resolve this.

**Comment by tsonevn** [comment]
Hi @dlucidone,
Could you send me the thread in NativeScript forums, where you are reporting your issue?

**Comment by dlucidone** [comment]
Here is the link - 
   https://discourse.nativescript.org/t/switch-to-another-android-activity-ontap/367
