### ISSUE TITLE
The binary you uploaded was invalid.

### ISSUE THREAD

**Issue by maniacube** [NativeScript/NativeScript#3591]
Hi,

### Tell us about the problem
We are facing the below issue when we upload the app store ipa file through test flight. We are able to generate ad-hoc ipa and development ipa files for testing in real devices. It is working fine.  We are getting below issues if we use nativescript-imagepicker and nativescript-background-http frameworks. If we didn't use those two frameworks, we can upload app store ipa file through test flight. we are almost on the edge of the development. we have to post our ipa file in to app store. Kindly please update us regarding this.

### Which platform(s) does your issue occur on?
iOS

Issues:-
----------------

ERROR ITMS-90680: "The binary you uploaded was invalid."

ERROR ITMS-90087: "Unsupported Architectures. The executable for RoomReview.app/app/tns_modules/nativescript-imagepicker/node_modules/nativescript-telerik-ui/platforms/ios/TelerikAppFeedback.framework contains unsupported architectures '[x86_64, i386]'."

ERROR ITMS-90087: "Unsupported Architectures. The executable for RoomReview.app/app/tns_modules/nativescript-imagepicker/node_modules/nativescript-telerik-ui/platforms/ios/TelerikUI.framework contains unsupported architectures '[x86_64, i386]'."

ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'Telerik.TelerikAppFeedback' under the iOS application 'RoomReview.app'."

ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'Telerik.TelerikUI' under the iOS application 'RoomReview.app'."

ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'RoomReview.app/app/tns_modules/nativescript-imagepicker/node_modules/nativescript-telerik-ui/platforms/ios/TelerikAppFeedback.framework/TelerikAppFeedback' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."

ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'RoomReview.app/app/tns_modules/nativescript-imagepicker/node_modules/nativescript-telerik-ui/platforms/ios/TelerikUI.framework/TelerikUI' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."

ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."

WARNING ITMS-90080: "The executable 'Payload/RoomReview.app/app/tns_modules/nativescript-imagepicker/node_modules/nativescript-telerik-ui/platforms/ios/TelerikAppFeedback.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library."

**Comment by Daxito** [comment]
I know this one! @NathanaelA Suggestion, you just **delete** the node_modules folder under the nativescript-imagepicker and nativescript-background-http , clean everything just in case and try again.

**Comment by NickIliev** [comment]
@maniacube have you build your application for release. To do that the command is

```
tns build ios --release --for-device
```

Moe info about the build command (and any other command) can be seen via
```
tns build ios --help
```

If this does not resolve your case, please verify that you have gone through the steps described in [publishing for iOS](https://docs.nativescript.org/publishing/publishing-ios-apps) and also send us your **package.json** file.

**Comment by maniacube** [comment]
@Daxito i have followed your instruction, but i am getting run time error like "TNSLabel is not found". After deleting node_modules folder under the nativescript-imagepicker and nativescript-background-http, i have done complete clean of the project. After that when try to run the app, we are getting mentioned run time error in the initial screen itself. But we can able to upload app store ipa through test flight(First Issue resolved). Please get back to me with proper solution.

**Comment by maniacube** [comment]
@NickIliev we are generating ipa file through XCode. we are not generating through command line prompt or terminal. Can you please provide your detail suggestion. Also find the below package.json file.

Package.Json:-
---------------------

{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.RoomReview",
    "tns-ios": {
      "version": "2.4.0"
    },
    "tns-android": {
      "version": "2.4.1"
    }
  },
  "dependencies": {
    "nativescript-background-http": "file:../../nativescript-background-http",
    "nativescript-checkbox": "^1.1.6",
    "nativescript-facebook-login": "^0.2.0",
    "nativescript-geolocation": "0.0.17",
    "nativescript-grid-view": "^1.4.0",
    "nativescript-imagepicker": "file:../../nativescript-imagepicker",
    "nativescript-iqkeyboardmanager": "^1.0.0",
    "nativescript-loading-indicator": "^2.2.1",
    "nativescript-localstorage": "^1.1.0",
    "nativescript-openurl": "^1.0.2",
    "nativescript-permissions": "^1.2.1",
    "nativescript-social-share": "file:../../nativescript-social-share",
    "nativescript-statusbar": "^1.0.0",
    "nativescript-theme-core": "^0.2.1",
    "tns-core-modules": "^2.4.4"
  },
  "devDependencies": {
    "babel-traverse": "6.19.0",
    "babel-types": "6.19.0",
    "babylon": "6.14.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*"
  }
}

**Comment by Daxito** [comment]
@maniacube Well, I just deleted the node_modules folder from the nativescript-background-http and NOT  from the image-picker (I also have both installed on the same App), and then I run the command suggested by @NickIliev 

tns build ios --release 

Go to Xcode, and try to publish...

**Comment by maniacube** [comment]
@Daxito Thanks for your reply. We don't have "node-modules" folder in "nativescript-background-http" framework. Please check this url for your reference "https://github.com/NativeScript/nativescript-background-http/tree/master/nativescript-background-http". Also we have tried "tns build ios --release" comment in terminal. And then we tried to publish the app from XCode. it doesn't resolve this issue. I would like to inform you one more thing, we are facing this issue only on "nativescript-imagepicker" not on "nativescript-background-http" framework. we have  "node-modules" folder only in "nativescript-imagepicker". So Kindly please update us regarding this issue.

**Comment by NickIliev** [comment]
@maniacube are the dependencies referred to local files customised anyhow!? If not can you try to use and publish with the official npm packages. 

I've also noticed that you are using 2.4.0 instead of the latest version 2.5.0 (for runtimes, and tns-core-modules) - if there is not specific reason for using the older versions perhaps you can try to update your project and NativeScritp and rebuild your project using the latest.

**Comment by NickIliev** [comment]
@maniacube you can open your bundle file in XCode and following the "Quick Fix" guide from[ this post](https://medium.com/@getsigneasy/error-cfbundleidentifier-collision-ios-8627d3325413#.476txmryu). You can also check your "Frameworks" folder (when opened via XCode) to verify that you do not have duplicated frameworks with identical BundleIdentifiers. 

When rebuilding your app, make sure you have deleted **node_modules** and **platforms** folder and also try to build your application with dependencies that are not referred from local paths.

**Comment by Daxito** [comment]
@maniacube 
To be honest I am getting rid of the image-picker and replacing it with 
http://plugins.nativescript.org/plugin/nativescript-telegram-image-picker and https://github.com/zhangao0086/DKImagePickerController
So I am not using it anymore, I just had the issue with the nativescript-background-http, 
follow @NickIliev  suggestions.

**Comment by maniacube** [comment]
@NickIliev and @Daxito 
After updating nativescript 2.5.0, this issue gets resolved. Thank you so much for you guys support.
