### ISSUE TITLE
GIFs not working in AoT compilated apps

### ISSUE THREAD

**Issue by dxshindeo** [NativeScript/NativeScript#3592]
Compiled an app with AoT support, got everything up n running, except my loading gif. Used this library: https://github.com/bradmartin/nativescript-gif
The Gif itself is stored locally in random folder (it did not like to be stored in App_Resources) and executed as follows: `<Gif src="~/resources/images/ripple.gif"></Gif>`
Error code:
```
JS: EXCEPTION: Uncaught (in promise): Error: pl.droidsonroids.gif.GifIOException: GifError 101: Failed to open given input
JS:     pl.droidsonroids.gif.GifInfoHandle.openFile(Native Method)
JS:     pl.droidsonroids.gif.GifInfoHandle.<init>(GifInfoHandle.java:51)
JS:     pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:125)
```

**Comment by bradmartin** [comment]
Is this gif actually in that file path? Resources/images?

**Comment by bradmartin** [comment]
And just confirming it worked without aot ?

**Comment by dxshindeo** [comment]
Yes, it worked without AoT, and thanks for pointing out the obvious - had to add the .gif file format in webpacker copy thingy: `{ from: "**/*.gif" },`. Now it's working as it should :)
