### ISSUE TITLE
Unable to install nativescript. npm error

### ISSUE THREAD

**Issue by smithamalur** [NativeScript/NativeScript#3593]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "nativescript"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code EACCES
npm ERR! errno EACCES
npm ERR! syscall connect

npm ERR! Error: connect EACCES 151.101.128.162:443
npm ERR!     at Object.exports._errnoException (util.js:1022:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:1045:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
npm ERR!  { Error: connect EACCES 151.101.128.162:443
npm ERR!     at Object.exports._errnoException (util.js:1022:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:1045:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
npm ERR!   code: 'EACCES',
npm ERR!   errno: 'EACCES',
npm ERR!   syscall: 'connect',
npm ERR!   address: '151.101.128.162',
npm ERR!   port: 443 }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

**Comment by tsonevn** [comment]
HI @smithamalur,

In your case, you could try to disable temporary Windows Defender and if you have an anti-virus program.
Then try to install again `nativescript` with `npm install nativescript -g`. 
When the installation complete you can enable again the defender and anti-virus.

Let me know, whether this helps.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#2499
