### ISSUE TITLE
Groceries example of NativeScript tutorial - Failed “tns run ios” command

### ISSUE THREAD

**Issue by drdavidtaylor** [NativeScript/NativeScript#3594]
Dear, Community of NativeScript!

I'm starting to learn NativeScript with NativeScript TypeScript and Angular getting started guide.
- I cloned the repository from: https://github.com/NativeScript/sample-Groceries.git 
- My branch is master
- I opened the project with IntelliJ IDEA
- tns run ios
it should be successfull ... but i got this: _UIImage.tns_safeImageNamed is not a function_

> CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:344:22: Error: Uncaught (in promise): Error: Error in login/login.component.html:10:4 caused by: UIImage.tns_safeImageNamed is not a function. (In 'UIImage.tns_safeImageNamed(name)', 'UIImage.tns_safeImageNamed' is undefined)

I tried on MacOS Sierra (10.12.3) with IntelliJ IDEA.
Python version 2.7.10 
Xcode 8.2.1
ruby-2.3.3
npm 4.0.5
bower 1.8.0
CLI:  2.4.2

package.json:

> tns-core-modules 2.5.0
>     "tns-ios": version": "2.5.0" 
>   "dependencies": {
>     "@angular/common": "2.4.3",
>     "@angular/compiler": "2.4.3",
>     "@angular/core": "2.4.3",
>     "@angular/forms": "2.4.3",
>     "@angular/http": "2.4.3",
>     "@angular/platform-browser": "2.4.3",
>     "@angular/platform-browser-dynamic": "2.4.3",
>     "@angular/router": "3.4.3",
>     "nativescript-angular": "1.4.0",
>     "nativescript-theme-core": "^1.0.2",
>     "reflect-metadata": "~0.1.8",
>     "rxjs": "~5.0.1",
>     "tns-core-modules": "2.5.0"
>   },
>   "devDependencies": {
>     "nativescript-dev-android-snapshot": "^0.*.*",
>     "nativescript-dev-typescript": "^0.3.5",
>     "sass": "^0.5.0",
>     "typescript": "~2.1.0",
>     "zone.js": "~0.7.2"
>   }
> 

![screen shot 2017-02-06 at 22 27 00](https://cloud.githubusercontent.com/assets/25477200/22669562/731845d0-ecc5-11e6-874e-9d3a7d634be2.png)

Could you give me any advice please? I tried everything ... I think.

Best regards,
David

**Comment by tsonevn** [comment]
Hi @drdavidtaylor,
I tested your case, however, was unable to reproduce problems with building `sample-Groceries` with latest NativeScript 2.5
Could you update your node to [latest LTS version](https://nodejs.org/en/) `6.9.5` and your `NativeScirpt` to 2.5, while following the instructions [here](http://docs.nativescript.org/releases/upgrade-instructions)?
Then clone again [sample-Groceries](https://github.com/NativeScript/sample-Groceries.git) and try to build it with `tns run ios` command.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/sample-Groceries#218
