### ISSUE TITLE
[Feature] add outline to label and button text

### ISSUE THREAD

**Issue by kazemihabib** [NativeScript/NativeScript#3597]
### Tell us about the problem

Currently there is no way to add `outline` for texts in nativescript.
but we need that in cases the color of `Label` ( or `Button` with transparent background) and parent  are same so if we don't add an outline to text of button and label the element will be invisible.

I found that for android this can be done using `shadaw for Label` and `stroke for button`.

It would be really good if we had CSS property to set outline of text.

**Comment by NordlingArt** [comment]
I actually tried to do this yesterday with native code but couldn't solve it. However, in OS you can at least create a shadow effect using this:

```js
var Color = require("color").Color;

function textShadow(view, hex, props = {}) {
  var defaults = {
    alpha: 1,
    x: 0, y: 0,
    radius: 1,
  };
  for(var key in defaults) if(!props.hasOwnProperty(key)) props[key] = defaults[key];
  
  if(view.ios) {
    nativeView = view.ios;
    nativeView.layer.masksToBounds = false;
    nativeView.layer.shadowOpacity = props.alpha;
    nativeView.layer.shadowRadius = props.radius;
    nativeView.layer.shadowColor = new Color(hex).ios.CGColor;
    nativeView.layer.shadowOffset = CGSizeMake(props.x, props.y);
  }
};
```

This won't create a perfect outline though because you cannot control the intensity. What I tried to do after some googling was this:

```js
function textOutline(view, color = "#ff0000", width = -1.0) {
  color = new Color(color);
  width = parseFloat(width);
  
  if(view.ios) {
    let nativeView = view.ios;
    let attributes = NSDictionary.dictionaryWithDictionary({
      NSStrokeColorAttributeName: color.ios,
      NSForegroundColorAttributeName: view.color.ios,
      NSStrokeWidthAttributeName: width
    });
    let attributedString = NSAttributedString.alloc().initWithStringAttributes(view.text || "", attributes);
    nativeView.attributedText = attributedString;
  }
}
```

But it doesn't work. It should, but nothing happens.

**Comment by tsonevn** [comment]
Hi @kazemihabib,

This issue could be related to [#550](https://github.com/NativeScript/NativeScript/issues/550), where has been logged a feature request for implementing shadow CSS property for the components. Could you verify the attached issue and to vote for it if this is your case?

Regards,
@tsonevn

**Comment by kazemihabib** [comment]
Hi, @tsonevn 

that issue is about box-shadaw but my requested feature is text-shadaw.
this page shows the difference  http://www.w3schools.com/css/css3_shadows.asp .

**Comment by NordlingArt** [comment]
@tsonevn - box-shadow and text-shadow are different things. Also, what's being requested here is an outline feature. Think "Stroke" in Photoshop compared to "Outer shadow" or "Outer glow". So it's not the same request as #550.

**Comment by Cayan** [comment]
Any update on this?

**Comment by tsonevn** [comment]
Hi @Cayan,
This feature is still under review and I could not commit to the exact time when this functionality will be included in NativeScript.
Regarding that, any PR will be highly appreciated and if all the test pass, it will be included in the modules. For further info review [this article](https://www.nativescript.org/contribute).

**Comment by irthos** [comment]
+1 text-shadow / stroke feature

**Comment by shabib3** [comment]
+1 text-shadow

**Comment by elalienx** [comment]
Yes, please add the text-shadow property.

**Comment by gabrielsmelo** [comment]
Please, add text-shadow property!! <3

**Comment by tanekim77** [comment]
I need text-shadow property so bad

**Comment by frabanca** [comment]
+1!!!

**Comment by Omi231** [comment]
+1

**Comment by Omi231** [comment]
I can't believe a modern framework doesn't have this feature. Its one of the very basic things in terms of UI.

**Comment by Macarthurval** [comment]
I've found a way to stroke easily a label text:

    function textLoaded(args) {

        var attributes = {
            NSStrokeColor: UIColor.blackColor,
            NSColor: UIColor.whiteColor,
            NSStrokeWidth: 2
        };

        var attributedString = NSAttributedString.alloc().initWithStringAttributes( args.object.text, attributes );

        args.object.ios.attributedText = attributedString;
        
    }

**Comment by NathanWalker** [comment]
The stated spec https://www.codesdope.com/blog/article/adding-outline-to-text-using-css/ will be supported in next minor release.
