### ISSUE TITLE
Button tap action not firing under GridLayout

### ISSUE THREAD

**Issue by damjankuznar** [NativeScript/NativeScript#36]
I'm trying to setup a simple UI using the GridLayout and I came across something odd (the whole project is based on HelloWorld example).  In some setups the Button is not firing the tap action.
For instance, the following setup is working correctly, i.e. the tapAction function is called.
```
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
  <GridLayout rows="auto, auto, *" columns="*">
    <Label text="Tap the button" cssClass="title" row="1"/>
    <Button text="TAP" tap="{{ tapAction }}" />
    <Label text="{{ message }}" cssClass="message" textWrap="true" row="2"/>
  </GridLayout>
</Page>
```

However, if I add the `row="0"` attribute to the Button, the tapAction function is not being called. Same goes for setting any other row value.
```
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
  <GridLayout rows="auto, auto, *" columns="*">
    <Label text="Tap the button" cssClass="title" row="1"/>
    <Button text="TAP" tap="{{ tapAction }}" row="0"/>
    <Label text="{{ message }}" cssClass="message" textWrap="true" row="2"/>
  </GridLayout>
</Page>
```

Is this a bug or am I doing something wrong?

**Comment by damjankuznar** [comment]
I've been playing around some more and the tap action works if the `row` attribute is the first one defined in the Button element, i.e.
```
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
  <GridLayout rows="auto, auto, *" columns="*">
    <Label text="Tap the button" cssClass="title" row="0"/>
    <Button row="1" text="TAP" tap="{{ tapAction }}" />
    <Label text="{{ message }}" cssClass="message" textWrap="true" row="2"/>
  </GridLayout>
</Page>
```

**Comment by ligaz** [comment]
This issue was moved to NativeScript/cross-platform-modules#269
