### ISSUE TITLE
sample code to implement NativeScript Class in TypeScript with self delegate

### ISSUE THREAD

**Issue by xmlking** [NativeScript/NativeScript#3603]
I am new to NativeScript,  looking for sample code to implement NativeScript Class in TypeScript with self delegate?

here are more details : 
http://stackoverflow.com/questions/41991160/how-to-implement-nativescript-class-in-typescript-with-self-delegate

want to simplify my code my eliminating additional delegate class by directly implementing delegate methods in the main class that supposed to have a delegate. 
Thanks

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/ios-runtime#725
