### ISSUE TITLE
CSS - letter-spacing in "Page" selector

### ISSUE THREAD

**Issue by philippsander** [NativeScript/NativeScript#3606]
```
Page {
  font-family: monospace;
  letter-spacing: 30;
}
```

the font-family is working and the letter-spacing is ignored.

**Comment by NickIliev** [comment]
Hey, @philippsander on what device/platform you are testing? 

Notice that the CSS property [letter-spacing](https://docs.nativescript.org/ui/styling#supported-css-properties) would work only on Android API21+ ([source](https://docs.nativescript.org/ui/styling#supported-css-properties))

**Comment by philippsander** [comment]
I'm on the latest Android (25?)

**Comment by hshristov** [comment]
Hi @philippsander,

`letter-spacing` is supported on iOS too. According to CSS spec this is inherited property but we didn't registered it like inherited. So for the time it will only work if you set it on concrete elements (like Button, Label, TextField, etc.).

I will mark this as a bug and we will change the implementation to make it inherited property as the spec say. 

Thanks for reporting it.

**Comment by NickIliev** [comment]
reproducible with modules30

**Comment by tsonevn** [comment]
reproducible with 4.1
