### ISSUE TITLE
Feature: CodePush support

### ISSUE THREAD

**Issue by biapar** [NativeScript/NativeScript#3611]
Hi,

Do Nativescript support Microsoft CodePush? 
If no it will be a good thing if you add the support -:)

**Comment by NickIliev** [comment]
Hey @biapar indeed supporting CodePush is an interesting feature and it is [already logged as possible future implementation](https://github.com/Microsoft/code-push/issues/247). Upvote here and iff you have any code concepts or implementations you can also join the community and provide it as this is an open source project.

Closing as duplicate to [https://github.com/Microsoft/code-push/issues/247](https://github.com/Microsoft/code-push/issues/247)
