### ISSUE TITLE
NativeScript 2.5 - CLI - tns run makes device hang and app keeps failing to launch - iOS

### ISSUE THREAD

**Issue by sudhanshu-15** [NativeScript/NativeScript#3615]
tns run on the NativeScript 2.5.0 makes the testing device (IPhone) hang, and also after 2-3 runs the command is aborted abruptly. The only solution to get the device back functioning again is to remove the USB cable and plug back in (once the device got stuck in loop of lock screen). Some times tns run says `Unable to kill the application.`

![image](https://cloud.githubusercontent.com/assets/883233/22753836/83da43ea-ee0b-11e6-9c1b-8b7c8b021754.png)

On other instances it fails after `Installing...`

![image](https://cloud.githubusercontent.com/assets/883233/22754039/2703f71e-ee0c-11e6-8fce-eafa8f2d44a9.png)

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-cli#2514
