### ISSUE TITLE
CFBundleVersion is not correctly set on the project

### ISSUE THREAD

**Issue by ignaciolarranaga** [NativeScript/NativeScript#3621]
### Tell us about the problem
Seems CFBundleVersion is not correctly transferred to the generated project. The value I set on app/App_Resources/iOS/Info.plist is ignored or some problem occurs in the middle 

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.0
- Cross-platform modules: 2.5.0
- Runtime(s): 2.5.0
- Plugin(s): N/A

### Please tell us how to recreate the issue in as much detail as possible.
Not sure what is really affecting the thing, here is the log after removing the platform completely: 
[log.txt](https://github.com/NativeScript/NativeScript/files/763792/log.txt)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#2523
