### ISSUE TITLE
Invalid image path on Image uploading in real device.

### ISSUE THREAD

**Issue by maniacube** [NativeScript/NativeScript#3626]
Hi,

Tell us about the problem:-
------------------------------
We are trying to upload the selected gallery images by using "nativescript-background-http" framework. It is working fine in iOS simulator. But when we try it in real device, we are getting error message saying that "Invalid image path". We are getting image object for selected image using getImage() method. When we try to bind this image object to ui image control, it is binding selected image perfectly. But when we try to log the image object, the console is printing empty object. Also we just tried to convert image object to base64string, but it is returning with null value. So please help us to achieve this task. 

Which platform(s) does your issue occur on?:-
------------------------------------------------
iOS and Android.

**Comment by tsonevn** [comment]
Hi @maniacube,
Could you provide some more info about the issue? It would help if you could provide some code snippets, which could be used to reproduce this behavior. 
Regard to that topic, in case you are using `nativescript-imagepicker` plugin, perhaps you should save the imagesource in a temporary file. Then you should be able to access the fileUri.

Sample code:

```
assest.getImage().then(function(imagesource){
                    let folder = fs.knownFolders.documents();
                    let path = fs.path.join(folder.path, "Test"+counter+".png");
                    let saved = imagesource.saveToFile(path, "png");
                    
                    if(saved){
                       //use new image path
                    }
                    counter++;
                })
```
Hope this helps
