### ISSUE TITLE
How I can handle deep links on nativescript on iOS?

### ISSUE THREAD

**Issue by NNieto** [NativeScript/NativeScript#3627]
I tried overriding a method on appDelegate but it is not working

**Comment by NickIliev** [comment]
Hey @NNieto there is a blog post aboout deep linking on iOS posted [here](https://www.nativescript.org/blog/deep-linking-your-nativescripts-apps-with-ios-9-user-activity-and-core-spotlight-apis). The blog post explains some native techniques as this is not supported out-of-the-box but it sis also logged as possible feature [here](https://github.com/NativeScript/NativeScript/issues/321)

Closing as duplicate to [https://github.com/NativeScript/NativeScript/issues/321](https://github.com/NativeScript/NativeScript/issues/321)

**Comment by NNieto** [comment]
Thanks @NickIliev
