### ISSUE TITLE
NativeScript - Dynamically changing background image of a page

### ISSUE THREAD

**Issue by sudhanshu-15** [NativeScript/NativeScript#3630]
Is there a way to change the background image of a page in NativeScript dynamically? For example I want to have a set of images which should be displayed as the background image but only one image at a time and depending on the location or some other parameter. 
I know in native android one can use `layout.invalidate()` to redraw the layout, but is there a similar feature available on NativeScript?

**Comment by NickIliev** [comment]
Hey @sudhanshu-15 
To keep the issues strictly for logging and resolving bug and features please post similar UI related question in the community channels as stackoverflow.

Regarding your question - I think [nativescript-themes](https://github.com/NathanaelA/nativescript-themes) plugin can do the trick for you. It can change CSS runtime and via CSS you can set your background-image selector. Note that to use this plugin you have to uninstall nativescript-theme-core.

**Comment by sudhanshu-15** [comment]
@NickIliev Thanks a lot for the answer, I will keep this in mind for future posts.
