### ISSUE TITLE
npm install -g nativescript on Windows 10 fails

### ISSUE THREAD

**Issue by justechn** [NativeScript/NativeScript#3631]
I am trying to follow the Windows install steps outlined here http://docs.nativescript.org/angular/start/ns-setup-win. However on step 7 it says to run `npm i -g nativescript` but I get an error
```
npm install -g nativescript

> angular-seed-advanced@0.0.0 preinstall C:\Users\ryan\AppData\Roaming\npm\node_modules\.staging\angular-seed-advanced-2ef5f751
> mkdirp app

'mkdirp' is not recognized as an internal or external command,
operable program or batch file.
```

I am unable to proceed forward

**Comment by vjoao** [comment]
Can you please try `npm i -g mkdirp` before running the NS command?

**Comment by justechn** [comment]
That worked.

Thanks

**Comment by vjoao** [comment]
Actually this should be included as a pre-step on the NS installation script itself, or just be added as a dependency (a forgotten `--save` perhaps)

**Comment by vjoao** [comment]
ping @atanasovg

**Comment by tieuquy1995** [comment]
you should learn how to create folder in windows again. Pay attention
mkdir app. Take carefully

**Comment by justechn** [comment]
Thank you for that very helpful comment. I appreciate the effort and thought you put into it. Keep up the good work.
