### ISSUE TITLE
With Webpack and AOT my css for pages break?

### ISSUE THREAD

**Issue by dlucidone** [NativeScript/NativeScript#3638]
With using webpack and AOT compilation my Action bar is touching the status bar when i make my application bundle and other pages container are overflowing too. with the normal app compilation its working as desired.

My package.json is like - 

    "dependencies": {
    "@angular/common": "2.4.5",
    "@angular/compiler": "2.4.5",
    "@angular/core": "2.4.5",
    "@angular/forms": "2.4.5",
    "@angular/http": "2.4.5",
    "@angular/platform-browser": "2.4.5",
    "@angular/platform-browser-dynamic": "2.4.5",
    "@angular/router": "3.4.5",
    "email-validator": "1.0.4",
    "nativescript-angular": "1.4.0",
    "nativescript-calendar": "^1.2.0",
    "nativescript-camera": "0.0.8",
    "nativescript-cardview": "^1.2.1",
    "nativescript-checkbox": "^1.2.3",
    "nativescript-drop-down": "^1.5.1",
    "nativescript-fancyalert": "^1.1.2",
    "nativescript-floatingactionbutton": "^2.2.7",
    "nativescript-imagepicker": "^2.4.1",
    "nativescript-iqkeyboardmanager": "1.0.1",
    "nativescript-loading-indicator": "^2.2.2",
    "nativescript-progressbar": "^1.0.2",
    "nativescript-social-share": "~1.3.2",
    "nativescript-theme-core": "^1.0.2",
    "nativescript-unit-test-runner": "^0.3.3",
    "reflect-metadata": "^0.1.8",
    "rxjs": "~5.0.1",
    "tns-core-modules": "^2.5.0"
     },
    "devDependencies": {
    "@angular/compiler-cli": "2.4.5",
    "babel-traverse": "6.8.0",
    "babel-types": "6.8.1",
    "babylon": "6.8.0",
    "codelyzer": "2.0.0-beta.4",
    "copy-webpack-plugin": "~3.0.1",
    "extract-text-webpack-plugin": "~2.0.0-beta.4",
    "filewalker": "0.1.2",
    "jasmine-core": "^2.4.1",
    "karma": "^1.2.0",
    "karma-jasmine": "^1.0.2",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "nativescript-dev-webpack": "^0.3.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~1.6.0",
    "tslint": "^4.0.0",
    "typescript": "^2.1.0",
    "webpack-sources": "~0.1.3",
    "zone.js": "~0.7.2",
    "nativescript-css-loader": "~0.26.0",
    "htmlparser2": "^3.9.2",
    "webpack": "2.2.0",
    "@ngtools/webpack": "1.2.4"
    }

**Comment by dlucidone** [comment]
I'm getting something like this when bundling - 

    `WARNING in ../~/resolve-url-loader!../~/nativescript-css-loader!../~/nativescript-dev- 
    webpack/platform-css-loader.js!./app.css
      resolve-url-loader cannot operate: CSS error`

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#669
