### ISSUE TITLE
Update on Webview documentation needed

### ISSUE THREAD

**Issue by AndersGerner** [NativeScript/NativeScript#3639]
Hello NativeScript team.

I'm in the middel of creating an app with a webview and found your documentation here: https://docs.nativescript.org/cookbook/ui/web-view

I did not see a "Improve this article" on that page, so this is why I'm writing to you here.

I would like to suggest an improve in regards to the headlines. It says "Using WebView" on all 3 code examples, but it should be something like:
Using Webview with remote URL
Using Webview with local file
Using Webvies with raw HTML

This might make it easier for people to find the correct sample they need. 

Have a great day :)

//Anders Gerner

**Comment by NickIliev** [comment]
Hey @AndersGerner thnak you for you suggestions - as NativeScript is an open source project you can also join the contributors and improve our documentation with PRs in [https://github.com/NativeScript/docs](https://github.com/NativeScript/docs) - All pull request should be made against our master branch and once approved by other team members will be merged and published in the live documentation

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/docs#677
