### ISSUE TITLE
Ability to use built-in system icons on ActionBarItems.

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/NativeScript#364]
The `<MenuIcon>` has an `icon` attribute, but it seems to require you to use an image that your provide in your app.

Is there any built-in way we can leverage the icons built into the OS? For instance [`UIBarButtonSystemItem`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIBarButtonItem_Class/#//apple_ref/c/tdef/UIBarButtonSystemItem) on iOS.

On two different apps now I've wanted to add a share icon to the nav bar, and there doesn't seem to be an easy way to do this at the moment. Ideally {N} would give me some way to use `UIBarButtonSystemItemAction` on iOS, and [Android's version](https://lh5.googleusercontent.com/zaiERj4Vx7nNWc3KiG5BtWWBdoJtxPCx-jMswHHaogADauuypJCOxMktFUBcmAnYjDCB_HOws5F_oH8cbcP3TJLvQrK7zlIgtbAPH6nPhvKp03dgACjnddVFm1jVtrDGPA) on Android.

Thanks.

**Comment by tjvantoll** [comment]
In the meantime, if someone could help me figure out how to make an existing `<ActionItem>` use a built in iOS icon you would make my day. The iOS APIs don't seem to have a way to change an existing button's icon.

**Comment by hamorphis** [comment]
```
    <ActionBar title="Title">
      <ActionBar.actionItems>
        <ActionItem tap="searchTap" ios.Position="left" ios.systemIcon="12" android.systemIcon="ic_menu_search"/>
        <ActionItem tap="cameraTap" ios.Position="right" ios.systemIcon="15" android.systemIcon="ic_menu_camera"/>
        <ActionItem tap="trashTap" ios.Position="right" ios.systemIcon="16" android.systemIcon="ic_menu_delete"/>
      </ActionBar.actionItems>
    </ActionBar>

```
