### ISSUE TITLE
ios  UINavigationController interactivePopGestureRecognizer 

### ISSUE THREAD

**Issue by Leo-lay** [NativeScript/NativeScript#3640]
Hi ,
 i have a case ,that i jump to **home page (A)** from **login page(B)**,in A page i  want disable right swipe  back to **B page**. i google some information i found the ios disable swipe back was used **interactivePopGestureRecognizer**  so ,in my app i set 
```
this.routerExtensions.frame.ios.controller.interactivePopGestureRecognizer.enabled = false;
```
but it didn;t work for me , so is there any other way resolve it ?

thank you .

**Comment by tsonevn** [comment]
Hi @Leo-lay,
For this case, you could use NativeScript `RouterExtensions` and to setup `clearHistory` property to false. This will disable the swipe back for iOS. For Example:
```
export class ItemsComponent implements OnInit {
    items: Item[];

    constructor(private itemService: ItemService, private routerExtensions:RouterExtensions) { }

    ngOnInit(): void {
        this.items = this.itemService.getItems();
    }

    onItemTap(args:ItemEventData){
         let itemID = this.items[args.index].id;
         this.routerExtensions.navigate(['/item', itemID], { clearHistory: true } )
     }
}
```
More about this could be found [here](https://docs.nativescript.org/angular/core-concepts/angular-navigation.html#clearing-page-navigation-history)

**Comment by Leo-lay** [comment]
Hi @tsonevn   it works . thank you so much ~
