### ISSUE TITLE
Loading Indicator Not Working

### ISSUE THREAD

**Issue by maniacube** [NativeScript/NativeScript#3648]
Tell us about the problem:-
-------------------------------
Hi,
"nativescript-loading-indicator" is not working after installing "nativescript-admob". I am not getting any errors but loading indicator is not showing. If i uninstalled the  "nativescript-admob", indicator is working perfect. Please help us to resolve it.

**Comment by tsonevn** [comment]
Hi @maniacube,

I tested the both plugins on my side and this behavior seems to be reproduced only on iOS.
As you have mentioned, this issue has been related to `nativescript-loading-indicator`.
In that case, you could contract with the plugin authors and to open a new issue in its repository [here](https://github.com/NathanWalker/nativescript-loading-indicator/issues).

Regards,
@tsonevn
