### ISSUE TITLE
Android File System Access

### ISSUE THREAD

**Issue by z3t0** [NativeScript/NativeScript#365]
What does the built in file system for Nativescript allow us to do? As I understand it only allows us to access private files which are pertinent and private to the app? Is there any way to access external storage using the file-system api?

**Comment by nsndeck** [comment]
Built-in file access does not grant access to some directories or files. It is just a module that simplifies a little bit working with files and directories. If your application has permissions to write or read something stored on the external storage then you could use file-system api. I don't know if that will help, but there is an example (from camera module) how to use external storage.

`var appModule = require("application");
var tempPicturePath = fileSystem.path.join(appModule.android.currentContext.getExternalFilesDir(null).getAbsolutePath(), "cameraPicture_" + dateStamp + ".jpg");
var nativeFile = new java.io.File(tempPicturePath);
var tempPictureUri = android.net.Uri.fromFile(nativeFile);
takePictureIntent.putExtra(android.provider.MediaStore.EXTRA_OUTPUT, tempPictureUri);`
