### ISSUE TITLE
Button text disappears with "swipe left" gesture in iOS

### ISSUE THREAD

**Issue by shivapersad** [NativeScript/NativeScript#3654]
I am running an iOS version of my app with a Button that is displaying text using the FontAwesome icon pack in Span tags nested in FormattedString tags i.e.
<FormattedString>
  <Span>[content]</Span>
</FormattedString>

I noticed that when I swipe left to return to the previous page the icon and text from the Button disappears. I can still interact with the buttons even though the text has disappeared but this is a major User Experience concern. I have attached a GIF of the issue. Any assistance is appreciated in resolving this issue.

![fontawesome issue](https://cloud.githubusercontent.com/assets/17012660/23081696/575d109a-f52c-11e6-98c6-677f7b40a710.gif)

**Comment by tsonevn** [comment]
Hi @shivapersad,
Thank you for interest in NativeScript.
I tested your scenario on my side, however, was unable to reproduce this behavior.
For your convenience I am attaching sample project. 
Could you review it and make the needed changes, which will allow us to reproduce the issue. 
[Archive.zip](https://github.com/NativeScript/NativeScript/files/786826/Archive.zip)
![screencast 2017-02-20 at 9 52 59 am]
I am also attaching gif from the simulator, which I use for testing.
(https://cloud.githubusercontent.com/assets/17448734/23116410/10966d5e-f753-11e6-9567-b7d5c870f693.gif)

**Comment by shivapersad** [comment]
Hi @tsonevn. I've attached my modified code as well a GIF of the issue occurring. It happens when you swipe left very quickly.
[Archive 2.zip](https://github.com/NativeScript/NativeScript/files/787751/Archive.2.zip)
![fontawesome issue 2](https://cloud.githubusercontent.com/assets/17012660/23129321/91647ffc-f758-11e6-9dd6-750702ad664a.gif)

**Comment by shivapersad** [comment]
@tsonevn @SvetoslavTsenov Any feedback on this issue? Were you able to reproduce it?

**Comment by alixandru** [comment]
I've run into a similar issue but in my case the `bindingContext` of the page was overwritten when navigating back. Maybe it's the same issue in your situation (if the buttons captions are taken from the page context).
