### ISSUE TITLE
NativeScript Angular project folder structure customization 

### ISSUE THREAD

**Issue by xmlking** [NativeScript/NativeScript#3658]
I would like to organize my  NativeScript Angular project code base like this:
```
src/
    main.ts
    main.aot.ts
    main.scss
    app/
         app.module.ts
         app.component.ts
         app.scss
e2e/
test/
package.json  
```
will it be possible to inform `tns` about my new structure? i.e., externally specifying all cli settings in /`.nativescript-cli.json`  
why do I need to have an extra `package.json` in `app` folder. I already have one in project root directory. Can `tns` use the  `package.json` in the project root directory?

**Comment by NickIliev** [comment]
@xmlking the role of the nested **package.json** the file is to allow p[roject templates to be created and published in npm. Like this one [here](https://www.npmjs.com/package/tns-template-hello-world-ng) published with the code from [this repository](https://github.com/NativeScript/template-hello-world-ng).

That said you can create your template following this structure and enable it with the following command:
```
tns create myApp --template <path-to-template>
```

where the path to the template can be a local path, a path to GitHub repository or a predefined official template.

More on templates and how to create your custom one can be found [here](https://www.tjvantoll.com/2016/02/22/creating-nativescript-templates/)

**Comment by xmlking** [comment]
@NickIliev thanks for information on `--template`. I definitely has use for it.
My issues is:
1. With `nativescript-dev-webpack` , every time we run `npm install` it is overwriting my local `webpack.common.js` which has my customizations for my directory structure. (distributive 👎 )
2. Even though I manage moving `/app` to `/src/app` for webpack, `tns` still expects `/app/App_Resources` 
My suggestion is, instead of each tool expecting source directory structure in certain way, all tools (webpack, scss, tns, and 3rd party hooks etc.,)  can share user preference settings via `.nativescript-cli.json` similar to `angular-cli`

**Comment by dolanmiu** [comment]
I would like this feature too so its closer to how angular cli does it. 

And it would be nice if the transpiled `.js` files were in a `dist` folder rather than scattered throughout the project.
