### ISSUE TITLE
remove button shadow in android api > 21

### ISSUE THREAD

**Issue by kazemihabib** [NativeScript/NativeScript#3660]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Tell us about the problem
There is a button Shadow in android > 21 that currrently there is no way to remove it with css in nativescript.
This shadow shows it self specially when button is white.

### Which platform(s) does your issue occur on?
Android

### Please tell us how to recreate the issue in as much detail as possible.
Create a Button there there is shadow around it, make it white

###Solution:
This shadaw is removable with `setStateListAnimator(null);` 
I tested  `btn.android.setStateListAnimator(null); ` and worked.

![photo_2017-02-19_21-12-17](https://cloud.githubusercontent.com/assets/10830552/23104709/55de6ef4-f6e8-11e6-8090-6408517713e5.jpg)

the left button has the problem and the right one I fixed it with setStateListAnimator .

**Comment by tsonevn** [comment]
Hi @kazemihabib,
Could you provide some sample code snippets or sample project, where the problem could be debugged locally? I have tested this case on my side while using NativeScript CLI and modules version 2.5.1, however, I was unable to reproduce the issue. I am attaching sample code.

main-page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page">

    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>

    <StackLayout class="p-20">
        <Label text="Tap the button" class="h1 text-center"/>
        <Button text="TAP" tap="{{ onTap }}" class="btnstyle"/>
        <Label text="{{ message }}" class="h2 text-center" textWrap="true"/>
    </StackLayout>
</Page>
```

app.css
```
.btnstyle {
    background-color: transparent;
}
@import 'nativescript-theme-core/css/core.light.css';
```

Regards,
@tsonevn

**Comment by kazemihabib** [comment]
HI, @tsonevn 

I tested your sample and here is the result:

![screenshot from 2017-02-20 21-24-25](https://cloud.githubusercontent.com/assets/10830552/23136651/01df559a-f7b3-11e6-931c-2c2b8c29e699.png)

as you see there is a shadow for the button.
This shadow added after  android 5.

**Comment by tsonevn** [comment]
Hi @kazemihabib,
I investigate this case further and it seems to be something expected in NativeScirpt for Android. While setting backgrounsColor to `transparent` we will change the tint color of the component. In this case, this shadow will be shown the API levels > 21. 
This shadow could be removed by setting `borderWidth` and `borderColor` for the `Button`. For example:

main-page.xml

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page">

    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>

    <StackLayout class="p-20">
        <Label text="Tap the button" class="h1 text-center"/>
        <Button text="TAP" tap="{{ onTap }}" class="btnstyle"/>
        <Label text="{{ message }}" class="h2 text-center" textWrap="true"/>
    </StackLayout>
</Page>

```

app.css

```
.btnstyle {
    background-color: transparent;
    border-color: transparent;
    border-width: 1;
}
@import 'nativescript-theme-core/css/core.light.css';
```

Could you verify, whether this will work for you?

**Comment by kazemihabib** [comment]
@tsonevn 
thanks it worked.
I already tried with `border-width:0` and it didn't work.but now I understand I should use with `border-width:1`.

**Comment by Jaishankarb** [comment]
But the native touch ripple effect gets lost on android if we use this

**Comment by tsonevn** [comment]
In your case after the button border color to transparent will remove the ripple effect option, however, you could still use [nativescript-ripple ](https://www.npmjs.com/package/nativescript-ripple), which will allow you to use this functionality

**Comment by bhavincb** [comment]
use below code to remove shadow and still keep ripple effect.
```
Button{
    z-index:0;
}
```

**Comment by tillsanders** [comment]
`border-color` / `border-width` didn't work for me. Maybe, things changed. Instead, I came up with a clever little Vue.js directive to remove the shadow, whilst keeping the ripple effect. This works quite well. It was only afterwards, that I discovered @bhavincb's solution works, too, and with much less code 🤦‍♂ I will leave my directive here anyway – maybe it will still be useful to someone, someday 😅🤷‍♂ 

```javascript
import { isAndroid } from 'tns-core-modules/platform';

export default {
  inserted(element) {
    if (isAndroid) {
      element.nativeView.on('loaded', () => {
        element.nativeView.android.setOutlineProvider(null);
      });
    }
  },
  updated(element) {
    if (isAndroid) {
      element.nativeView.android.setOutlineProvider(null);
    }
  },
};
```

**Comment by edusperoni** [comment]
@tillsanders please refer to the android-elevation and android-dynamic-elevation-offset properties since NS 5.3: https://docs.nativescript.org/ui/styling#nativescript-specific-css-properties

**Comment by codealvarez** [comment]
> use below code to remove shadow and still keep ripple effect.
> 
> ```
> Button{
>     z-index:0;
> }
> ```

It works! Nice thanks!

**Comment by Komar12124** [comment]
`z-index: 0`
Bad idea. Coz on few tablet ur text of button would be "transparent".
So, following the [docs](https://docs.nativescript.org/ui/styling#nativescript-specific-css-properties-Using) for removing shadow u should use 

`
.btn-no-elevation {
    android-elevation: 0;
}
`

**Comment by Jaroslav84** [comment]
> `z-index: 0`
> Bad idea. Coz on few tablet ur text of button would be "transparent".
> So, following the [docs](https://docs.nativescript.org/ui/styling#nativescript-specific-css-properties-Using) for removing shadow u should use
> 
> `.btn-no-elevation { android-elevation: 0; }`

This solution still has shadow effects ON button press 🥺

**Comment by edusperoni** [comment]
@Jaroslav84 you can also do:

`android-dynamic-elevation-offset: 0;`
