### ISSUE TITLE
Android GPU overdraw showing 4x Rendering throughout my application

### ISSUE THREAD

**Issue by dlucidone** [NativeScript/NativeScript#3665]
I'm doing GPU overdraw to check the rendering of each element in my app but what i'm all seeing is 4x rendering (dark red). Is something I'm doing wrong.

**Comment by NickIliev** [comment]
@dlucidone 

When using GPU overdraw color debugging, keep in mind that these are only recommendations and not mandatory requirements from Android. It is indeed a good practice to avoid redrawing multiple times on single selection from your app, but in real life scenarios, this is not always possible. In fact, even the "Developer options" menu from settings on Android is always in full dark red which shows that even the native OS solution can not always keep the UI so simple.

The easiest way to avoid becoming "red" (in Android GPU overdraw) is to avoid nesting multiple layouts and keep your UI as simple and as flat as possible. For example(assuming we are GPU overdraw debugging [this app](https://play.google.com/store/apps/details?id=org.nativescript.curiosity&ah=JzMiTK6i7_W0DjmFnEL4ORKdB3w&hl=eng#details-reviews)), take a look at [the XML of this page here](https://github.com/NickIliev/NativeScript-Cosmos-Databank/blob/master/app/views/asteroid/asteroid-details-page.xml). Following [the color scheme](https://developer.android.com/studio/profile/dev-options-overdraw.html)  you will notice that

- the outer FlexBox layout is in blue (Overdrawn 1 time)
- the nested GridLayouts are in green (Overdrawn 2 times)
- the Labels inside these grids are in pink (Overdrawn 3times)
- everything that goes deeper then the Labels will be in red (3+ times)

However, this is not always possible especially when you have complex templates or UI elements like card-views, side-drawers, etc. [This page](https://github.com/NickIliev/NativeScript-Cosmos-Databank/blob/master/app/views/drawer-page.xml) is demonstration that you can not always follow the recommendations for GPU rendering but in the same time it should not concern you if you do not have performance issues.
