### ISSUE TITLE
Not Getting Local Notification Sound On "nativescript-local-notifications"

### ISSUE THREAD

**Issue by maniacube** [NativeScript/NativeScript#3678]
Hi,

Problem:-
-----------------
When we set some custom audio sound file to "nativescript-local-notifications", we are not getting local notification sound. If we didnt set any custom audio sound file, we are getting default notification sound. Please help us to resolve this.

Platform:-
-------------
iOS

**Comment by NickIliev** [comment]
@maniacube please post your issue in the repository of the plugin you are using where the author and the community members which have already used it can provide you with proper instructions. The repository of this plugin can be found [here](https://github.com/eddyverbruggen/nativescript-local-notifications)

It is always a good practice to provide a sample app or code snippet of what you have achieved so far and highlight the places where you are experiencing the issue.

**Comment by NickIliev** [comment]
@maniacube a quick glance at the original repository shows that a community member already has [a solution](https://github.com/EddyVerbruggen/nativescript-local-notifications/issues/3) provided in a forked repo. More [here](https://github.com/Obsessive/nativescript-custom-local-notifications)
