### ISSUE TITLE
[Screen Builder] Model is not updated when an observable object property is used in two text fields

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#368]
In brief:
An observable object property is used in two text field elements. Modifying one of the text fields does not always update the model.
In the case of Screen Builder the text field is the password of a sign in and register form, which are part of an authentication component.

1. Create new native SB app with BS sample data project.
2. Add authentication form, add it to the navigation and apply the change.
3. Deploy the app on iOS device.
4. Open the app on the device and go to the authentication form.
5. Redirect to the register form, fill in the email and password and submit the form.
6. Go again to the authentication, switch to the sign in form and submit it.
7. Go again to the authentication switch to the register form, delete the password and change the email. Submit the form.

Expected: error for missing password appears.
Actual: the form is submitted without password.

**Comment by nsndeck** [comment]
Fixed with #383.

**Comment by vchimev** [comment]
The issue was caused by secure text field in ios. Tested with https://github.com/NativeScript/NativeScript/commit/542704cd7818b99e4ddc799e76170ba4534025d5.
