### ISSUE TITLE
Provide a way to control cachePolicy for NSURLRequest

### ISSUE THREAD

**Issue by toddanglin** [NativeScript/NativeScript#3681]
I ran in to a weird problem in an iOS app I'm developing ({N} 2.5.1, iOS 9+). After running for a few days on an iPad (device is always on), the iPad said it was running out of space, and my app had swelled to use over 8GB of disk space!

I downloaded the Container using Xcode to inspect, and the "problem" turned-out to be this folder:
`AppData > Library > Caches > [my app identifier] > fsCachedData`

Upon closer inspection, the folder was full of iOS auto-cached responses to `fetch` requests my app had executed.

Critical to this problem and scenario, my app makes a new `fetch` request EVERY SECOND to get updated JSON responses. So this `fsCachedData` folder had over 200k entries at 36KB a pop. 😳 And it seems iOS won't auto-clear the `fsCachedData` folder if your app is running, which is problem when the scenario is an app that's always on. **In NativeScript, we need a way to disable this iOS caching behavior.**

Looking around for answers, it seems this can be solved by controlling the iOS cache policy for `NSURLRequest` (which NativeScript does not seem to do in the core `http` module). Here is a good discussion of the general iOS `fsCachedData` problem and some solutions:
http://stackoverflow.com/questions/405151/is-it-possible-to-prevent-an-nsurlrequest-from-caching-data-or-remove-cached-dat

I'm not an iOS expert, so I may be missing some nuance to the problem here. Based on what I've seen, though, I think the iOS implementation for the {N} `http` module (on which `xhr` and `fetch` modules are built) should either:

1. Set a default cache size limit to proactively prevent runaway fsCacheData folder size
2. Provide additional method options to allow developers to optionally set this caching policy
3. Something else?

For now, I will try to monkey patch the `http` module and see if I can solve my immediate problem. Let me know something here is unclear.

**Comment by toddanglin** [comment]
To expand on this issue (after more debugging)...

The problem is pronounced when querying URLs on a regular interval with "cache busting" parameters (like a random number in the query parameters). When cache busting URLs are used, a new entry is created is the `fsCacheData` folder for every query response. If cache busting URLs are _not_ used, the same entry gets overwritten, avoiding the problem of a constantly growing cache (assuming you are not querying thousands of unique URLs).

So as a "work around," don't use cache busting URLs. :)

To be honest, I'm not 100% cache busting URLs are needed in a {N} app. I'm used to doing it on the web, but maybe it's overkill in {N}?

**Comment by toddanglin** [comment]
Is there any reason `NSURLCache` is not available in the global scope during the `onLaunch` event?

![image](https://cloud.githubusercontent.com/assets/647319/23245541/e5436d94-f952-11e6-8f95-c54e6041ae1b.png)

I would have expected to find that class in the global scope (https://developer.apple.com/reference/foundation/nsurlcache). I was trying to implement a "brute force" work around to effectively disable the URL cache on app launch:

```
if (app.ios) {
        // Disable URL cache
        let cachePolicy = NSURLCache.alloc().initWithMemoryCapacity(0, 0, "nsurlcache");
        NSURLCache.setSharedURLCache(cachePolicy);
}
```

But, obviously, without access to the `NSURLCache` class, this approach won't work. Any ideas? I'm I headed down the wrong path? :)

**Comment by tsonevn** [comment]
Hi @toddanglin, 
I tested this case on my side on real iOS device, however, was unable to reproduce this behavior.
Regarding your last comment, you could add to the project `tns-platform-declarations` -> `npm install tns-platform-declarations --save` and to follow the setup instructions [here](https://www.npmjs.com/package/tns-platform-declarations).

Then you should be able to use `NSURLCache` on the loaded event. I am also attaching sample code related to the above-given snippet, which should allow you to disable `URL cache`.

```
import {isIOS} from "platform"

if (isIOS) {
           let cachePolicy = NSURLCache.alloc().initWithMemoryCapacityDiskCapacityDiskPath(0, 0,"nsurlcache")
           NSURLCache.sharedURLCache=cachePolicy;
       }
```

**Comment by toddanglin** [comment]
Here is a sample project that demonstrates the problem on iOS:
https://github.com/toddanglin/ns-urlcache-demo

Key to trigger this behavior, I think, is that the response size has to be large enough for iOS to decide it needs to be cached in `fsCacheData`. If you run this project, use Xcode to extract the "Container" from the device after the app has run for 30 to 60 seconds (giving it time to re-run the query a number of times). Then, you should see the expanding number of entries in `AppData > Library > Caches > [app identifier] > fsCachedData`.

I will attempt to apply your suggested `NSURLCache` solution to this demo and see if it "brute force" solves the problem. Ideally, a permanent solution would allow developers to choose a URL caching policy on a per request basis.

**Comment by toddanglin** [comment]
It looks like the NSURLCache approach works for completely disabling the fsCacheData caching on iOS. Here is a branch that demonstrates that solution:
https://github.com/toddanglin/ns-urlcache-demo/tree/cachehack

**Comment by tsonevn** [comment]
Hi @toddanglin,
I have tested your case while using the given sample project, however, I am still unable to reproduce the same behavior. This could be related to an issue with the device or in case there is not enough free memory on it
Regarding that, do you have any further suggestions about this issue and how we could reproduce it?
If this issue has been related only to iOS and the given workaround resolved the issue, we could close this issue and reopen it if someone else hits it

Regards,
@tsonevn

**Comment by toddanglin** [comment]
Odd. Not sure how else to test it. Locally tested on several iPads and consistently hit the issue.

Regardless, the workaround does work so I think it's okay to close this. If others hit this in the future, we may want to provide an easier way to expose the iOS cache policy settings.
