### ISSUE TITLE
loaded event not fired for a custom component in android

### ISSUE THREAD

**Issue by Liooo** [NativeScript/NativeScript#3691]
`loaded` event isn't fired when it's in a custom component. Here's the minimum code to reproduce.

app/main-page.xml
```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd" class="page" xmlns:assignments="assignments">
  <assignments:assignment-list />
</Page>
```

app/assignments/assignment-list.xml
```xml
<Label text="hello" loaded="onLoad"></Label>
```

app/assignments/assignment-list.ts
```ts
export function onLoad(args){
  console.log("loaded!!") 
}
```

when running this code in iOS, it shows the message "loaded!!", but in android it doesn't.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.0
- Cross-platform modules: 2.5.1
- Runtime(s):     ios: 2.5.0, androd: 2.5.0

package.json
```json
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.CascoMobile",
    "tns-ios": {
      "version": "2.5.0"
    },
    "tns-android": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "nativescript-theme-core": "~1.0.2",
    "tns-core-modules": "2.5.1"
  },
  "devDependencies": {
    "babel-traverse": "6.23.1",
    "babel-types": "6.23.0",
    "babylon": "6.15.0",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.3.5",
    "typescript": "~2.1.0"
  }
}
```

**Comment by tsonevn** [comment]
Hi @Liooo, 
I tested your case on my side, however, the `loaded` event of the `Label` inside the custom component seems to be fired as expected on Android. For you convenience, which I am attaching the project, I have used for testing and screenshot from the emulator.

It would help if you could provide sample project, which could be debugged locally. I also noticed that you are using an old `CLI` with new `Modules`. Could you upgrade to `NativeScript CLI` to version `2.5.1`, while following the instructions [here](http://docs.nativescript.org/releases/upgrade-instructions) and to verify, whether you will have the same behavior?
![screen shot 2017-02-23 at 11 33 29 am](https://cloud.githubusercontent.com/assets/17448734/23253479/6003511a-f9bd-11e6-8db5-15be9d4018b8.png)
[Archive.zip](https://github.com/NativeScript/NativeScript/files/796086/Archive.zip)

**Comment by Liooo** [comment]
@tsonevn

As you told me I updated cli's version and re-added android platform, then it worked with the same code! Thanks so much for the quick response!
