### ISSUE TITLE
[Proposal] Comply with sem-ver specification (semantic versioning).

### ISSUE THREAD

**Issue by Plamen5kov** [NativeScript/NativeScript#3698]
See more information about [semantic versioning](http://semver.org/).

How does it apply for npm? [Read more](https://docs.npmjs.com/getting-started/semantic-versioning)?

_[Why we might not want to adopt sem-ver](https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e)?_
Much is said on the topic of "Is sem-ver helping?", but my opinion is largely summarized by the comment of @krainboltgreene. Did you break the public API - yes/no there's no gray area there. And currently by not complying with sem-ver we have more problems (project migrations), so my vote goes towards adopting it. Furthermore we distribute large portion of the packages as npm modules.

_What problem does it solve?_
In short: It helps us with project update transitions.

_Some arguments and critical points to discuss:_
Currently we don't follow sem-ver specification, and we had a couple of complaints from users, expecting no breaking changes, because of the versioning of the packages, which implies developers expect us to keep sem-ver specification. 
Is sem-ver a cure for all? Certainly not, but it will help us a lot based on the current expected behavior and user concerns.
There is an argument of automatic updates and them leading to unexpected behavior. This happens only if you've used something different than an exact version (>=, ~ ...), so there's room left for decision on what to do and how the updates should happen. If a package is critical, then an app developer might consider using an exact version of a package.

>Recommending you read all the provided information before commenting.

**Comment by vakrilov** [comment]
Great suggestion! 

We are indeed moving in the direction of complying with sem-ver spec (that is why we Release v3.0 with breaking changes).

It is our intention to minimize breaking changes and make the upgrade process for developers seamless.
