### ISSUE TITLE
Image Path Not Found. Native Exception Error Nativescript Android

### ISSUE THREAD

**Issue by maniacube** [NativeScript/NativeScript#3699]
### Tell us about the problem

When we are uploading images using "nativescript-imagepicker" & "nativescript-background-http", selecting images from gallery and binding to imageView control and then uploading is working fine in iOS but we are getting native exception error  in android. We are done it with the following code.

selected.getImage().then(function(imagesource){
                    let folder = fsModule.knownFolders.documents();
                    let path = fsModule.path.join(folder.path, "Test"+new Date().getTime()+".png");
                    let saved = imagesource.saveToFile(path, "png");

                    if(saved){
                       console.log("New image path:"+path);
                       let newPath="file://"+path;
                    }
                });

Please help us to resolve it. Thanks.

### Platform(s)
Android

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-imagepicker#74
