### ISSUE TITLE
css 3 and animations

### ISSUE THREAD

**Issue by erny100** [NativeScript/NativeScript#37]
hi

have you any plan to implement some css3 features like ?
Gradients - Rounded Corners - Shadow Effects

how implement animation to move element into widget ? 

thanks

E

**Comment by valentinstoychev** [comment]
Please [vote for this feature](https://nativescript.ideas.aha.io/ideas/NS-I-27) in our ideas portal.

**Comment by valentinstoychev** [comment]
@erny100 Animations support is in our roadmap. We are also investigating if we should use the Angular 2.0 format for describing the animations.

**Comment by valentinstoychev** [comment]
Please see #255 and #201
