### ISSUE TITLE
Android: any view below full-screen ListView

### ISSUE THREAD

**Issue by mikalai-sauchanka** [NativeScript/NativeScript#370]
Hey there.
Initially I needed a footer for a ListView to display progress when loading new items, but haven't found a way how to add it.
More general question - Is it possible to create a layout with button/label or anything below a list view which occupies full screen? Or may be there's any good workaround for to display a progress at the very bottom?
Thank you!

**Comment by enchev** [comment]
Here is an example:
<GridLayout rows="*,auto">
  <ListView />
  <Button row="1" />
</GridLayout>

**Comment by mikalai-sauchanka** [comment]
Thanks, but the button is always visible. I need it at the end of scrollable area :)
I tried StackLayout, the button isn't rendered

**Comment by enchev** [comment]
In this case maybe you need itemTemplate with some logic to display special item content for the last item. For example:
```XML
<ListView>
  <ListView.itemTemplate>
     <StackLayout>
        <Label visibility="{isLastItem? 'visible' : 'collapsed'}" />
        <Button visibility="{!isLastItem? 'visible' : 'collapsed'}" />
     </StackLayout>
  </ListView.itemTemplate>
</ListView>
```

You need to have this property (isLastItem) in your item model.

**Comment by mikalai-sauchanka** [comment]
Looks like a hacky workaround :) And every item will contain that button, which costs performance. Both IOS and Android supports a footer for ListView, but it's not implemented in the base ListView component.
Moreover it's not possible to add this footer (at least for Android, because it should be added before setting the adapter).
Anyway, I wonder if it's planned to add support of footers, because it's commonly used feature to display progress when you've scrolled down to the bottom of the list and new items are being fetched.

**Comment by enchev** [comment]
Closing in favor of https://github.com/NativeScript/NativeScript/issues/524
