### ISSUE TITLE
Application page transition takes time if the page has a lots of html content.

### ISSUE THREAD

**Issue by lakshaya22** [NativeScript/NativeScript#3706]
### Tell us about the problem
I have a screen that has lots of data to be shown in different format, so has many Stack layout and Grid layout. The time taken to open this page is at least 4 second, which is huge.

Which platform(s) does your issue occur on?
Android

**Comment by Pip3r4o** [comment]
Hey @lakshaya22 please provide proper code samples so that we may be able to help you.

Also, I'd recommend that you avoid nesting too many layouts as that can impose a big performance hit.
https://developer.android.com/training/improving-layouts/optimizing-layout.html

**Comment by tsonevn** [comment]
closed due to inactivity
