### ISSUE TITLE
Listview delete element issue.

### ISSUE THREAD

**Issue by abdumama** [NativeScript/NativeScript#3709]
Hi to all,
I'm using Nativescript (angular2 / typescript) to create a mobile application, and I have found a problem when I use the ListView widget.

![listview](https://cloud.githubusercontent.com/assets/22960356/23331669/9da49a0c-fb6a-11e6-82db-6d72d88d4ab1.jpg)

I have an ObservableArray with the data, and I'm trying to remove the first element of the list with an animation:

`viewElement.animate({
translate: { x: 200, y: 0 },
duration: 500
}).then(() => {
this.requestPreviewList.splice(this.requestPreviewList.indexOf(request), 1);
});`

The removal is carried out correctly, but as you can see from the pictures the second list item inheritance the animation properties.

![listview_err](https://cloud.githubusercontent.com/assets/22960356/23331716/855fd2f8-fb6b-11e6-85ba-5ed54071ab6d.jpg)

**UPDATE:**

Here you can download a simple project where you can reproduce the issue.
[ListViewBug.zip](https://github.com/NativeScript/NativeScript/files/801400/ListViewBug.zip)

**Version:**
- CLI: 2.5.0
- Cross-platform modules: 2.5.0
- Runtime(s): 2.5.0 [Android]

**Comment by abdumama** [comment]
For now I have found a workaround:

`viewElement.animate({ translate: { x: 200, y: 0 }, duration: 500 }).then(() => { `
      `this.requestPreviewList.splice(this.requestPreviewList.indexOf(request), 1); `
						`viewElement.translateX = 0;`
`});`

After the remove of the element I use the .translateX property.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#683
