### ISSUE TITLE
Change Switch textOn and textOff 

### ISSUE THREAD

**Issue by dzfweb** [NativeScript/NativeScript#3710]
My app is required for old devices (SKD 4.4.4) and there is an old switch ui element.

I need to change the text options "On" and "Off"

I've tried using the following codes after page load:

`@ViewChild("sw1") switch: ElementRef;`

```
(<Switch>this.switch.nativeElement).set("textOn", "Sim");
(<Switch>this.switch.nativeElement).set("textOn", "Não");
```

```
this.switch.nativeElement.setTextOn("Sim");
this.switch.nativeElement.setTextOff("Não");
```

```
 this.switch.nativeElement.textOn = "Sim";
 this.switch.nativeElement.textOff = "Não";
```

Is there any way to change it values?

![screenshot_59](https://cloud.githubusercontent.com/assets/10212321/23333003/77ee59f4-fb62-11e6-8da5-758b6334e9a9.png)

**Comment by tsonevn** [comment]
Hi @dzfweb, 
To change Switch `textOn` and `textOff`, you should use `setTextOff` and `setTextOn` methods. You could review the below attached example.

NativeScirpt Core

XML
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page">
    <StackLayout class="p-20">
        <Label text="Tap the button" class="h1 text-center"/>
        <Switch loaded="swloaded" checked="true" />
        
    </StackLayout>
</Page>

```
TypeScript
```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import {Switch} from "ui/switch"
export function navigatingTo(args: EventData) {

    let page = <Page>args.object;

    page.bindingContext = new HelloWorldModel();
}
export function swloaded(args){
    var switchv:Switch= <Switch>args.object;
    switchv.android.setTextOff("Sim");
    switchv.android.setTextOn("Não");
}
```



NativeScirpt Angular 2

HTML
```
<StackLayout>
    <Label text="Switch test" textWrap="true"></Label>
    <Switch (loaded)="swloaded($event)" checked="true" class="switch"></Switch>
</StackLayout>
```
TypeScript
```
import { Component } from "@angular/core";
import {Switch} from "ui/switch";

@Component({
    selector: "ns-app",
    templateUrl: "app.component.html",
})
export class AppComponent { 

    swloaded(args){
        var switchv:Switch= <Switch>args.object;
        switchv.android.setTextOff("Sim");
        switchv.android.setTextOn("Não");
    }
}

```

Hope this helps

**Comment by dzfweb** [comment]
Thank you for the support, it's working.

**Comment by 1392324000** [comment]
@tsonevn 
In commonJs
`        //already required Switch component
        var choose = new Switch(); 
        choose.android.setTextOff("off");
        choose.android.setTextOn("on");
`
I got exception of "cannot read property 'setTextOff' of undefined"

**Comment by tsonevn** [comment]
@1392324000,
Perhaps the problem has been related to the early access the android property of the component.
Try to setup `TextOff` and `TextOn` on component `loadedEvent`. For example:
```
 var choose = new Switch(); 
   choose.on(Switch.loadedEvent, (args)=>{
       choose.android.setTextOff("off");
   choose.android.setTextOn("on");
   })
```

**Comment by 1392324000** [comment]
@tsonevn 
with your code,it reports no error again.
But,the switch button's sign dosn't changed either.
If the button's text is forced to cover by local language variable package in native level?
Anyway,thanks,man!
