### ISSUE TITLE
"ERROR ReferenceError: Can't find variable: TKSideDrawerDelegate" after 2.5 upgrade

### ISSUE THREAD

**Issue by alexziskind1** [NativeScript/NativeScript#3713]
_From @alexziskind1 on February 6, 2017 2:3_

Existing project throws seg fault 11 when trying to run on iOS emulator after upgrade to 2.5. 
Running commands: 
```tns livesync ios --emulator --watch``` OR ```tns run ios```

 Running on MacOS Siera 10.12.3

When reinstalling nativescript 2.4.2, the project works again.

_Copied from original issue: NativeScript/nativescript-cli#2490_

**Comment by alexziskind1** [comment]
Yesterday this was working with CLI 2.4.2, today trying to run it again and getting this error:

```
file:///app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js:320:67: JS ERROR ReferenceError: Can't find variable: TKSideDrawerDelegate
Feb  7 13:15:07 AlexMBP com.apple.CoreSimulator.SimDevice.7EF5EC7B-FB52-49AF-B710-2077B6F98F98.launchd_sim[28697] (UIKitApplication:org.nativescript.rpspt[0xd635][29224]): Service exited due to Segmentation fault: 11
```

**Comment by alexziskind1** [comment]
_From @roofi07 on February 8, 2017 0:20_

This is very strange, I still have the same error. Look at here: https://github.com/telerik/nativescript-ui-samples/issues/141

**Comment by alexziskind1** [comment]
Saw that issue and tried the suggestions listed, but no luck.

**Comment by alexziskind1** [comment]
_From @soeyanmin on February 8, 2017 10:5_

Me too, until now having the same error. Looks like no one can help out

**Comment by alexziskind1** [comment]
_From @Plamen5kov on February 8, 2017 13:11_

Please provide steps to reproduce.

**Comment by alexziskind1** [comment]
_From @RamyaMenon on February 9, 2017 12:21_

I am also facing the same issue.

**Comment by alexziskind1** [comment]
I've had to make some modifications and currently not getting this error (because of another error), so if anyone on this thread can reproduce this and post the steps, that would be great!

**Comment by alexziskind1** [comment]
_From @soeyanmin on February 9, 2017 13:36_

Hi Plamen5kov,

Below is the error that i got. And CLI version information.
Thanks 

> ndefined:21:51:

 JS ERROR TypeError: NSFileManager.defaultManager is not a function. (In 'NSFileManager.defaultManager()', 'NSFileManager.defaultManager' is undefined)
1   0x102c2b7b9 -[TNSRuntime executeModule:]
2   0x10298496a main
Feb  9 21:30:16 Soes-MacBook-Pro nativescriptappmaster[823]: 3   0x1084a768d start
Feb  9 21:30:16 Soes-MacBook-Pro nativescriptappmaster[823]: 4   0x1
Feb  9 21:30:16 Soes-MacBook-Pro com.apple.CoreSimulator.SimDevice.DA92A58D-E3CA-4A99-A0A2-EBC773C4C963.launchd_sim[714] (UIKitApplication:org.nativescript.mapApp[0x4b00][823]): Service exited due to Segmentation fault: 11

> 

"nativescript-telerik-ui": "^1.6.0",
"tns-core-modules": "^2.6.0-2017-02-03-5543"

──────────────────┬─────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 2.4.2           │ 2.5.0          │ Update available │
│ tns-core-modules │ 1.4.0           │ 2.5.0          │ Update available │
│ tns-android      │ 1.4.0           │ 2.5.0          │ Update available │
│ tns-ios          │ 1.4.1           │ 2.5.0          │ Update available │
└──────────────────┴─────────────────┴────────────────┴──────────────────┘

**Comment by alexziskind1** [comment]
Hi @soeyanmin . It looks like this is a different error than the one in the title. Can you reproduce the one about the TKSideDrawerDelegate?

**Comment by alexziskind1** [comment]
_From @RamyaMenon on February 9, 2017 13:55_

I thought I've done something wrong. That why it did not work. Then, I tried to create a new project as per the reference. But it is also showing same error.
(Ref git url https://github.com/shripalsoni04/nativescript-angular-drawer-template)

**Error Log**
Feb  9 15:37:04 Ramyas-MBP drawer[8147]: 1   0x1086b333c -[TNSRuntime executeModule:referredBy:]

Feb  9 15:37:04 Ramyas-MBP drawer[8147]: 2   0x1082553b9 main

Feb  9 15:37:04 Ramyas-MBP drawer[8147]: 3   0x10ca1568d start

Feb  9 15:37:04 Ramyas-MBP drawer[8147]: file:///app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js:369:67: JS ERROR ReferenceError: Can't find variable: TKSideDrawerDelegate

Feb  9 15:37:04 Ramyas-MBP com.apple.CoreSimulator.SimDevice.20CC84A5-C166-49C9-9177-6DD222F01D26.launchd_sim[7447] (UIKitApplication:org.nativescript.drawer[0x1db8][8147]): Service exited due to Segmentation fault: 11

Feb  9 15:38:34 Ramyas-MBP routined[7454]: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104

All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 2.4.2           │ 2.5.0          │ Update available │
│ tns-core-modules │ 2.4.4           │ 2.5.0          │ Update available │
│ tns-android      │                 │ 2.5.0          │ Not installed    │
│ tns-ios          │ 2.5.0           │ 2.5.0          │ Up to date       │
└──────────────────┴─────────────────┴────────────────┴──────────────────┘

**Comment by alexziskind1** [comment]
_From @Plamen5kov on February 9, 2017 14:29_

@alexziskind1 @RamyaMenon 
```
file:///app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js:320:67: JS ERROR ReferenceError: Can't find variable: TKSideDrawerDelegate
Feb  7 13:15:07 AlexMBP com.apple.CoreSimulator.SimDevice.7EF5EC7B-FB52-49AF-B710-2077B6F98F98.launchd_sim[28697] (UIKitApplication:org.nativescript.rpspt[0xd635][29224]): Service exited due to Segmentation fault: 11
```
This is a javascript error. Please either open an issue in [here](https://github.com/NativeScript/nativescript/issues) or move this issue there.

**Comment by alexziskind1** [comment]
How would I move the issue there and keep all the history?

**Comment by alexziskind1** [comment]
_From @Plamen5kov on February 10, 2017 7:45_

@alexziskind1  https://github-issue-mover.appspot.com/

**Comment by alexziskind1** [comment]
_From @elvismercado on February 27, 2017 10:36_

This is closed? What was the fix?

**Comment by alexziskind1** [comment]
_From @RamyaMenon on February 27, 2017 10:51_

Once I had updated the nativescript and tns-core-modules to 2.5.0, ,then it started to working for me. Also, I have removed platforms and added it again.

**Comment by alexziskind1** [comment]
_From @Plamen5kov on February 27, 2017 12:51_

@elvismercado I asked for this issue to be moved. Please read the comments for more information.

**Comment by NickIliev** [comment]
Hey, @elvismercado has the solution provided by @RamyaMenon  working out for you?
One crucial moment is that you will have to delete the previously installed app (for iOS) from your device/emulator as discussed [here](https://github.com/telerik/nativescript-ui-samples/issues/141#issuecomment-265055393)

**Comment by elvismercado** [comment]
@NickIliev Yes downgrading to v2.5.0 allowed me to keep working on my project. In my case i had to have tns-core-modules and nativescript-cli @2.5.0

**Comment by NickIliev** [comment]
@elvismercado glad to hear that you were able to resolve this issue. 

Closing as duplicate to [https://github.com/telerik/nativescript-ui-samples/issues/141](https://github.com/telerik/nativescript-ui-samples/issues/141#issuecomment-265055393)
