### ISSUE TITLE
[Android] changing the `isUserInteractionEnabled` value from false to true will remove tap event for some of the components

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#3714]
When you set `isUserInteractionEnabled` to `false` and again change it to `true`, the `tap` event for the `Label` and for the `Layout`s will stop working.
This behavior has been reproduced only for Android

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.2
- Cross-platform modules: 2.5.1
- Runtime(s): 2.5.0

[Archive.zip](https://github.com/NativeScript/NativeScript/files/803975/Archive.zip)

**Comment by Ericky14** [comment]
Is this going to be fixed?

**Comment by tsonevn** [comment]
Hi @Ericky14,
This issue seems to be fixed in latest NativeScript 3.4. For your convenience, I am attaching a sample project.


[Archive.zip](https://github.com/NativeScript/NativeScript/files/1836380/Archive.zip)
