### ISSUE TITLE
Simple location app doesn't perform until real gps apps are also running

### ISSUE THREAD

**Issue by getsetbro** [NativeScript/NativeScript#372]
My [simple gps location app](https://github.com/getsetbro/nativescriptapp), straight from the documentation LocationManager example, doesn't work well when tested on 3 different android phones. Please try for yourself.

Properties like altitude, speed, and direction are not displayed. It performs best if it has data, wifi, and gps. Worse if it has wifi and gps. Worst if it has just gps.

However if an app like [GPS Status](https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2) or Google Maps is also running, then it responds well and is useable. Those other apps are unlocking something that the TNS location module isn't.

**Comment by slavchev** [comment]
I managed to reproduce the described behavior though I am not sure if that is your case. I pulled your repo and indeed I reproduced the issue. Then I checked my phone location settings and saw that the current (probably the default) location mode is set to `Battery saving`. Once I set it to `High accuracy` your code starts working as expected.

As far as your observation about Google Maps. My guess is that Google Maps changes the current location mode to `High accuracy` and thus your app works as expected.

**Comment by getsetbro** [comment]
My phones are already in high accuracy mode. 2 of them do not have sim
cards or data plans so they are not getting data that way. The phone with a
data plan does better then ones without.
FYI Google maps doesn't work on a device without a data plan.
If they are connected to WiFi they can do okay but once I leave the WiFi
area their GPS info pauses. That is until I launched an app like GPS status
or take a picture (with positioning info for photos turned on). Then the
{N} app will gather GPS info again.

Please try taking your device out of the WiFi area. And pausing your data
service. The info that seems the hardest for {N} to get is altitude.

I think I'll need to display a status of if it has a lock on any
satellites. Not sure if I need to hard code satellite into.

**Comment by getsetbro** [comment]
A (stackoverflow answer](http://stackoverflow.com/a/31162769/1072149) has helped tremendously.

Steps are:
1 - Import enums in your main-page.js:
```
var enums = require('ui/enums');
```
2 - Add an object as the third parameter to the startLocationMonitoring call, here:
```
{desiredAccuracy: enums.Accuracy.high}
```
But it seems like [the docs said](https://github.com/NativeScript/docs/blob/master/ApiReference/location/Options.md#object-locationoptions) HIGH was the default, and even if it isn't [the docs showed](https://github.com/NativeScript/docs/blob/master/location.md#getting-a-location) I could set it like this:
```
var locationOptions = {desiredAccuracy: 3}
```

**Comment by emiloberg** [comment]
Just for reference: Where they're doing `var locationOptions = {desiredAccuracy: 3}` and then setting locationOptions as the third argument to `startLocationMonitoring`, it is essentially the same thing as setting it to the "enum" value (which resolves to `3`).

**Comment by getsetbro** [comment]
What is the desiredAccuracy value that will set accuracy to high?
Zero?

**Comment by slavchev** [comment]
Here is how Android defines `ACCURACY_xxx` constants

https://android.googlesource.com/platform/frameworks/base.git/+/master/location/java/android/location/Criteria.java#60

You are looking for this one

```Java
public static final int ACCURACY_HIGH = 3;
```

**Comment by emiloberg** [comment]
High is 3. See [enums declaration](https://github.com/NativeScript/NativeScript/blob/master/ui/enums/enums.ts#L71-L74).

And currently it seems like 3 is the only valid value of the desiredAccuracy. [This line of code](https://github.com/NativeScript/NativeScript/blob/master/location/location.android.ts#L144) says:

> If the `desiredAccuracy` equals `enums.Accuracy.high` (which is `3`) then set the accuracy to `ACCURACY_FINE` (which is the highest of all accuracies) if *anything* else than 3, then just set accuracy to `ACCURACY_COARSE`.

So either you set that value to 3 and get fine accuracy, or you don't set it at all and get coarse accuracy, there's no other values available (as of now).

**Comment by emiloberg** [comment]
@slavchev You're right, but in practice that value is not being marshaled directly to the underlying Java, it  get evaluated by the Javascript:

    criteria.setAccuracy((this.desiredAccuracy === enums.Accuracy.high) ? android.location.Criteria.ACCURACY_FINE : android.location.Criteria.ACCURACY_COARSE);

https://github.com/NativeScript/NativeScript/blob/master/location/location.android.ts#L144

**Comment by getsetbro** [comment]
This api docs states:
"Specifies desired accuracy in meters."
https://github.com/NativeScript/docs/blob/master/ApiReference/location/Options.md

**Comment by emiloberg** [comment]
Yeah, that seems wrong @getsetbro, or am I the one reading it wrong @slavchev ?

**Comment by slavchev** [comment]
It seems the documentation is wrong. Reopen the issue.

**Comment by getsetbro** [comment]
This issue? Does it appear as closed for you?

**Comment by getsetbro** [comment]
Here is a pull request for the doc change: https://github.com/NativeScript/docs/pull/110
