### ISSUE TITLE
Our .bundle file is not copied to the xcodeproj (iOS)

### ISSUE THREAD

**Issue by dennis-montana** [NativeScript/NativeScript#3723]
We've created a plugin which has a .bundle file in the plugin's `platforms/ios` folder which is not copied to the xcodeproj after building for iOS.
If we drag the file to the xcodeproj after building, the app runs perfectly.

Our plugin to reproduce the issue can be found here:
https://github.com/Essent/nativescript-live-engage
To run use:
```sh
npm run setup
npm run demo.ios
```

**Comment by NickIliev** [comment]
Hey @dennis-montana 

At this very moment, NativeScript does not support working out-of-the-box with bundle files. However,  you can try this approach and inject the bundle to your native project as suggested [here](http://stackoverflow.com/questions/41589178/how-to-add-bundle-file-to-a-nativescript-plugin).

Another option is to create Podfile from the framework, bundle, and momd files and use the Pod in your plugin. as described [here](http://docs.nativescript.org/angular/plugins/cocoapods.html)

**Comment by dennis-montana** [comment]
Hi @NickIliev,

Thank you for your reply! We'll try using a hook to edit our xcodeproj file.

For others running into this issue: 
We've just found a similar solution in the [Fabric plugin](https://github.com/hypery2k/nativescript-fabric), they edit the xcodeproj using [Node XCode](https://github.com/alunny/node-xcode) in their [after prepare script](https://github.com/hypery2k/nativescript-fabric/blob/master/lib/after-prepare.js).

**Comment by spike1292** [comment]
we created a hook to copy the bundle file and add it to the xcode project, see https://github.com/Essent/nativescript-live-engage/pull/6
