### ISSUE TITLE
How to set background color of tab-view?

### ISSUE THREAD

**Issue by SumanSingh4** [NativeScript/NativeScript#3724]
I want to change color of tab-item background. I have applied css also but not successful.

Any help?

![add services](https://cloud.githubusercontent.com/assets/25900614/23460266/7bbff0c4-feaa-11e6-8535-d683059b7b04.png)

just like this

**Comment by NickIliev** [comment]
Use [**_tabBackgroundColor_** ](http://docs.nativescript.org/api-reference/classes/_ui_tab_view_.tabview.html#tabbackgroundcolor) to set the primary color of your tabs and use **_[tabTextColor](http://docs.nativescript.org/api-reference/classes/_ui_tab_view_.tabview.html#tabtextcolor)_** to set the primary text color of your tabs.

There are also selectedTabTextColor to set the text color of the selected tab.

**Comment by SumanSingh4** [comment]
I got it.

Thanxx

**Comment by carrbrpoa** [comment]
Hey @SumanSingh4, how did you do that fancy tab pointer below the tab? :)

**Comment by iamabs2001** [comment]
no gradient background ? i have a gradient actionbar!
