### ISSUE TITLE
How do I Bind Json response returned from a web service to Listview on Nativescript-angular 2 ?

### ISSUE THREAD

**Issue by smithamalur** [NativeScript/NativeScript#3726]
I have the JSON response returned from the WebAPI as
 `[
  {
    "requestedon": "2/28/2017 5:48:52 PM",
    "requestid": 25494,
    "requestno": "#25494",
    "requesttype": "Revision"
  },
  {
    "requestedon": "2/28/2017 5:14:41 PM",
    "requestid": 25491,
    "requestno": "#25491",
    "requesttype": "Revision"
  },
  {
    "requestedon": "2/24/2017 4:41:18 PM",
    "requestid": 25439,
    "requestno": "#25439",
    "requesttype": "Revision"
  },
  {
    "requestedon": "2/23/2017 10:15:05 AM",
    "requestid": 23804,
    "requestno": "#23804",
    "requesttype": "Revision"
  },
  {
    "requestedon": "2/22/2017 2:47:44 PM",
    "requestid": 23797,
    "requestno": "#23797",
    "requesttype": "Revision"
  }
]`

How do I parse each Item and render them on a Listview  ?

**Comment by tsonevn** [comment]
Hi @smithamalur,
You should bind `ListView` source to an array, where you could push the needed data from the response.
For further help, you could review the attached example or the sample project [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/release/app/http/http-get).
For further `How to` questions please use our `StackOverflow` thread [here](http://stackoverflow.com/questions/tagged/nativescript).
[Archive.zip](https://github.com/NativeScript/NativeScript/files/812924/Archive.zip)

**Comment by smithamalur** [comment]
Thank you @tsonevn
