### ISSUE TITLE
Add sibling  and indirect adjacent combinators for CSS rules

### ISSUE THREAD

**Issue by SBats** [NativeScript/NativeScript#3727]
Hi,
after looking trough issue https://github.com/NativeScript/NativeScript/issues/98, I though multiple combinators were implemented but with some test and a look at the [`css-selector.ts`](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/styling/css-selector.ts#L235) file, it seems to me that only the direct child (`>`) combinator is supported at the moment.
I would like to have your opinion on the addition of the sibling (`+`) and the indirect adjacent (`~`) combinators.

I would be willing to try adding it myself, even though I'm not really familiar with the code base yet. Do you see any counter-indication for this feature or pitfalls I should know about?

Thanks for your time and this project!

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.1
- Cross-platform modules: 2.5.0 for project dev and 3.0.0 for source crawling
- Runtime(s): 2.5.0
- Plugin(s): -

**Comment by NickIliev** [comment]
Hey, @SBats thank you for your interest ni NativeScript and for the suggested feature!
As an open source product, you can indeed join the contributors and add the feature via PR.
The first step is to[ sign the CLA](https://docs.google.com/forms/d/e/1FAIpQLSeq92C84Cv-lHO09DimJVgJOjLVEbUfGIUhHNPdbozPobaWZA/viewform) but before all, I would recommend going through the detailed contributing guide can be found [here](https://github.com/NativeScript/NativeScript/blob/master/.github/CONTRIBUTING.md) - let us know if you need any assistance on that matter!!

**Comment by SBats** [comment]
I've started working on it. You can find it on this PR (https://github.com/NativeScript/NativeScript/pull/4002).
Please, when you find time, let me know what you think of this first (incomplete) attempt.

**Comment by atanasovg** [comment]
@PanayotCankov @SBats Guys, do you think we can close this issue as complete? Looking at this merged PR: https://github.com/NativeScript/NativeScript/pull/4146
