### ISSUE TITLE
ID's for UI Automation Tests on Dynamic Objects

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#3729]
_From @kseeman on March 1, 2017 18:21_

Here’s what I have for the GitHub issue:

I'm trying to create UI automation tests and I'm running into an issue with setting the automationText attribute to a static value on an object such as a label or a button where the text is dynamic. By setting the automationText to a unique value it makes it easier to create UI automation tests, but it causes an adverse side effect of forcing the Talk Back feature to speak the wrong value. If you set the value of a Label dynamically based on the result of an API call, you obviously want Talk Back to read the value of the label. Take this code for example:

<Label automationText=”Welcome Message” [text]=”welcomeMessage”></Label>

Talk Back will read “Welcome Message” out loud, opposed to whatever the variable “welcomeMessage” is set to (and is shown on the screen). To provide a better accessibility experience, UI Automation is made more difficult.

I'm new to UI automation for mobile apps but in previous projects for native applications each object was able to be given a specific ID that is separate from what Talk Back uses. This allowed us to create unique IDs for all the objects and made creating UI automation tests much simpler. In native apps, when an ID was set and you used Android's UIAutomatorViewer to view the objects, the resource-id was set like: <packageName>:id/<id>. For example "com.company.application:id/etFirstName." This allowed for tools like Xamarin.uitests and Appium to have visible IDs' that are separate from what the Talk Back uses.

Is this something that can be added or changed to solve this issue? If not, what are some other approaches that I can do to handle situations like these?

Thank you.

_Copied from original issue: NativeScript/nativescript-cli#2582_

**Comment by NickIliev** [comment]
_From @coltcook on March 1, 2017 19:1_

+1

We also have this issue--we have to decide between good accessibility practices and writing non-brittle UI Automation Tests...

**Comment by SvetoslavTsenov** [comment]
As an automation engineer, I agree that this is the most convenient way to access UI elements but unfortunately, the android platform doesn't support anything else than [setContentDescription method](https://developer.android.com/reference/android/view/View.html#setContentDescription%28java.lang.CharSequence%29) and it is not possible so far to implement such functionality for android.
On the other hand, you can take a look at our repository with [functional tests](https://github.com/NativeScript/functional-tests) and our [functional-test-core](https://github.com/NativeScript/functional-tests-core) framework based on [appium](http://appium.io/) for some ideas. Of course, any feedback will be appreciated.
