### ISSUE TITLE
Building a time table / complex view

### ISSUE THREAD

**Issue by MidiDEVS** [NativeScript/NativeScript#3732]
# Building a time table view with {nativescript}

## this issue is not intended to rate { N }, but to give room for criticism at our approach, since this was our first production journey with { N }. Also, our problems come with a structure, so i choose to wrap them in one issue.

Hello everyone!

We have a { N } project, in wich we've build a time table. Also, We tried to get as much info and best practises for our implementation, and kinda achieved what we wanted, but the result's performance is wanting.

## The Problem (Week - View/Page)
---
It's context: all events for every day of a week. Device orientation determines which of two available representaions is shown.

#### 1. Portrait orientation

In portrait, the view is a simple list, which has items for every day of a week. Every day-item has it's own list again, which shows all events occuring in that day. Day-Items also are collapsables, so when tapping on an item, it would shrink or expand.

#### 2. Landscape orientation

In landscape, the view is a time table.
Every row represents a day while the row's items are representing events for that day, again. 
How ever, a big difference, and probably the bottleneck/problem is that those items need to be in an absolute layout context. 

The absolute positioning is mandatory, since an event item would need to be at the right distance to the left, to represent its start-time via positioning.

Furthermore, tapping on an event-item in landscape orientation would expand the row to double height and show a detailed version of that event's item. This would be usefull for very short events, since you would need extra space to read the event's details.

## Our approach
---
We thought that with potentially longer lists and certainty that all lists allways have at least one item to show, runtime-reusement f nodes/elements would be a good thing for performance.

Also, as we tried to style available list components (ListView, RadListView, Repeater ... ect.) we found that we could not style them as needed (Absolute positioning especially).

So we took the *ng-for structural directive, since we are building our app with nativescript-angular.

## The result
---
We where able to achieve nearly everything we wanted, with drawbacks. Also, data is loaded nicely fast, but rendering is a mess when it comes to the problematic view at hand.

### Issues and cuts we had to make.

1. For Landscape we wanted to allow vertical scrolling, since showing 7 day-rows means, that their items could not be that tall. But a 'sticky-header' for this view should show a hour-metric bar, that is in precise scale with all event's width and positioning.
    * But since the day rows would need to be inside a container that has a hour-metrics line that is allways shown, we could not find a way to implement a layout structure that allows vertical and horizontal scrolling.

2. A really convienient and intuitive thing was ofcourse, that when navigating to the landscape time-table, the view would automatically scroll to the current hour.
    * But we have not found any API that gives us state or functionality to implement a solution for this.

3. Performance is wanting. We assume that our complex layout structure is the reason for this, as hinted at [an issue, that describes a simmilar problem](https://github.com/NativeScript/NativeScript/issues/3706).
    * This structure was implemented with list-best-practises in mind. In other words: because we did not want to make a seperate view that would get the same data again, and hydrate additional lists.
    * We thought having user-interaction state for one use-case in one component, would keep the responsibility for this abstraction at one place and would spare building another module as a mediator for two views.

If you have { N } know-how, ideas or critic for us, let me know!

Thanks!

**Comment by NickIliev** [comment]
Hey @MidiDEVS 

As far as I understand you have a complex HTML layout in which you are using a lot of Angular structural directives (e.g.,.*ngFor and perhaps *ngIf). Now I see that you have chosen those so you could have more control over styling but keep in mind that structural directives may cause a big performance drawback in complex layouts. In fact for repeating scenarios (e.g. week layouts, day layouts, etc.) I would recommend choosing ListView as it is virtualized m and its cells are recycled. In big structure, this control will have a significant advantage compared to elements repeated with *ngFor. A great blog post on that matter can be found [here](https://medium.com/@alexander.vakrilov/faster-nativescript-listview-with-multiple-item-templates-8f903a32e48f#.i7forqd9p)
Of course, here the question is what you can not style/position when using ListView - can you please provide real code sample depicting the situation

**Comment by NickIliev** [comment]
@MidiDEVS haven't heard from you for a while - closing this one due to inactivity.
