### ISSUE TITLE
Using angular2-mqtt

### ISSUE THREAD

**Issue by CelebratedPooper** [NativeScript/NativeScript#3736]
I want to use the [angular2-mqtt](https://www.npmjs.com/package/angular2-mqtt) in my app. I have an angular2-app which works fine and tried to port this to android.

The build works but when I start the app it throws an uncought exception. This is the output:

> An uncaught Exception occurred on "main" thread.
> java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:
> 
> Error calling module function
> 
> Error calling module function
> 
> Error calling module function
> 
> Error calling module function
> 
> ReferenceError: window is not defined
> File: "/data/data/org.nativescript.WeatherView/files/app/tns_modules/ng2-mqtt/mqttws31.js, line: 2143, column: 3
> 
> StackTrace:
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/tns_modules/ng2-mqtt/mqttws31.js', line: 2143, column: 4
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/mqtt-weather/mqtt-weather.component.js', line: 3, column: 18
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/app.module.js', line: 5, column: 32
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/main.js', line: 4, column: 20
> Frame: function:'require', file:'', line: 1, column: 266
> 
> 
> ReferenceError: window is not defined
> File: "<unknown>, line: 1, column: 265
> 
> StackTrace:
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/tns_modules/ng2-mqtt/mqttws31.js', line: 2143, column: 4
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/mqtt-weather/mqtt-weather.component.js', line: 3, column: 18
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/app.module.js', line: 5, column: 32
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/main.js', line: 4, column: 20
> Frame: function:'require', file:'', line: 1, column: 266
> 
> 
> ReferenceError: window is not defined
> File: "<unknown>, line: 1, column: 265
> 
> StackTrace:
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/tns_modules/ng2-mqtt/mqttws31.js', line: 2143, column: 4
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/mqtt-weather/mqtt-weather.component.js', line: 3, column: 18
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/app.module.js', line: 5, column: 32
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/main.js', line: 4, column: 20
> Frame: function:'require', file:'', line: 1, column: 266
> 
> 
> ReferenceError: window is not defined
> File: "<unknown>, line: 1, column: 265
> 
> StackTrace:
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/tns_modules/ng2-mqtt/mqttws31.js', line: 2143, column: 4
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/mqtt-weather/mqtt-weather.component.js', line: 3, column: 18
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/app.module.js', line: 5, column: 32
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/main.js', line: 4, column: 20
> Frame: function:'require', file:'', line: 1, column: 266
> 
> 
> ReferenceError: window is not defined
> File: "<unknown>, line: 1, column: 265
> 
> StackTrace:
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/tns_modules/ng2-mqtt/mqttws31.js', line: 2143, column: 4
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/mqtt-weather/mqtt-weather.component.js', line: 3, column: 18
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/app.module.js', line: 5, column: 32
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/main.js', line: 4, column: 20
> Frame: function:'require', file:'', line: 1, column: 266
> 
> 
> at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
> at android.app.ActivityThread.-wrap1(ActivityThread.java)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:148)
> at android.app.ActivityThread.main(ActivityThread.java:5417)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
> Caused by: com.tns.NativeScriptException:
> 
> Error calling module function
> 
> Error calling module function
> 
> Error calling module function
> 
> Error calling module function
> 
> ReferenceError: window is not defined
> File: "/data/data/org.nativescript.WeatherView/files/app/tns_modules/ng2-mqtt/mqttws31.js, line: 2143, column: 3
> 
> StackTrace:
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/tns_modules/ng2-mqtt/mqttws31.js', line: 2143, column: 4
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/mqtt-weather/mqtt-weather.component.js', line: 3, column: 18
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/app.module.js', line: 5, column: 32
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/main.js', line: 4, column: 20
> Frame: function:'require', file:'', line: 1, column: 266
> 
> 
> ReferenceError: window is not defined
> File: "<unknown>, line: 1, column: 265
> 
> StackTrace:
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/tns_modules/ng2-mqtt/mqttws31.js', line: 2143, column: 4
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/mqtt-weather/mqtt-weather.component.js', line: 3, column: 18
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/app.module.js', line: 5, column: 32
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/main.js', line: 4, column: 20
> Frame: function:'require', file:'', line: 1, column: 266
> 
> 
> ReferenceError: window is not defined
> File: "<unknown>, line: 1, column: 265
> 
> StackTrace:
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/tns_modules/ng2-mqtt/mqttws31.js', line: 2143, column: 4
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/mqtt-weather/mqtt-weather.component.js', line: 3, column: 18
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/app.module.js', line: 5, column: 32
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/main.js', line: 4, column: 20
> Frame: function:'require', file:'', line: 1, column: 266
> 
> 
> ReferenceError: window is not defined
> File: "<unknown>, line: 1, column: 265
> 
> StackTrace:
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/tns_modules/ng2-mqtt/mqttws31.js', line: 2143, column: 4
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/mqtt-weather/mqtt-weather.component.js', line: 3, column: 18
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/app.module.js', line: 5, column: 32
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/main.js', line: 4, column: 20
> Frame: function:'require', file:'', line: 1, column: 266
> 
> 
> ReferenceError: window is not defined
> File: "<unknown>, line: 1, column: 265
> 
> StackTrace:
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/tns_modules/ng2-mqtt/mqttws31.js', line: 2143, column: 4
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/mqtt-weather/mqtt-weather.component.js', line: 3, column: 18
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/app.module.js', line: 5, column: 32
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.WeatherView/files/app/main.js', line: 4, column: 20
> Frame: function:'require', file:'', line: 1, column: 266
> 
> 
> at com.tns.Runtime.runModule(Native Method)
> at com.tns.Runtime.runModule(Runtime.java:514)
> at com.tns.Runtime.run(Runtime.java:509)
> at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
> at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
> at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
> ... 8 more

**Comment by bradmartin** [comment]
Can't use a browser lib in nativescript directly. There is no window or DOM. Hence why the error about window is thrown

**Comment by tsonevn** [comment]
Hi @CelebratedPooper,
I have to agree with @bradmartin. You are not able to use DOM related plugins.
I found that there is another plugin called `nativescript-mqtt`, which provides the mqtt support for NativeScript. Could you verify, whether this plugin is applicable for you?
