### ISSUE TITLE
tab not working in nativescript

### ISSUE THREAD

**Issue by BhuvaneswariVajravel** [NativeScript/NativeScript#3739]
this is my ts file

```
import { Component, OnInit } from "@angular/core";

import { Item } from "./item";
import { ItemService } from "./item.service";

@Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
   
})
export class ItemsComponent implements OnInit {

    items: Item[];

    constructor(private itemService: ItemService) { }

    ngOnInit(): void {
        this.items = this.itemService.getItems();
    }
	toggleDisplay() {
    alert("Hello");
    console.log("hello");
  }
}
```

=================================================

and this is my html file
```
<ActionBar title="My App" class="action-bar">
</ActionBar>
<StackLayout class="page">
   <Button text="clicking" (tab)="toggleDisplay()"></Button>
     <ListView [items]="items" class="list-group">
          <template let-item="item">
            <Label  [text]="item.name"
                class="list-group-item"></Label>
        </template>
    </ListView>
</StackLayout>

```

here i cant see any alert or console when i click button?

what 's problem here anyone know?

**Comment by NickIliev** [comment]
Hey @BhuvaneswariVajravel please post similar question in the community channels like [stackoverflow](http://stackoverflow.com/questions/tagged/nativescript) where there is greater chance to receive fast and adequate answer as you will face the experience of the whole community.

Meanwhile, make sure that you have included your **AlertDialogComponent** in the respective module.ts file as done [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/release/app/ui-category/dialogs/dialogs-examples.module.ts#L55). In the example shown the app has multiple module.ts files but if you are not using lazy loading you probably have one main on the root level where you should import the used component as shown [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/release/app/ui-category/dialogs/dialogs-examples.module.ts#L1-L10) and use it as a declaration in your ngModule directive as shown [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/release/app/ui-category/dialogs/dialogs-examples.module.ts#L52-L60)

Overall you can use those examples as a reference to check what is different from your code compared to the alert exmaple [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/release/app/ui-category/dialogs/alert-dialog)

**Comment by BhuvaneswariVajravel** [comment]
Thanks for ur concern @NickIliev .
sry for wasting ur time  i did very small mistake.
here i used (tab) instead of (tap).

but my problem is i need to toggle the content when click the button 

do u know how is this .
