### ISSUE TITLE
how to use custom pipe on nativescript angular

### ISSUE THREAD

**Issue by harriscreativity** [NativeScript/NativeScript#3742]
i am having problem to use my pipe on  listView any help please

**Comment by tsonevn** [comment]
Hi @harriscreativity,
You could review the sample project [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/d2c54685f9c38873d00996968b7acdf55f872495/app/color/creating-colors/creating-colors.component.ts#L7-L19), where has been shown, how to create and use custom pipes in NativeScirpt Angular 2 project.

For further questions please use our [StackOverflow thread](http://stackoverflow.com/questions/tagged/nativescript).
