### ISSUE TITLE
How can I limit ngFor repeat to 10 items in Angular 2?

### ISSUE THREAD

**Issue by harriscreativity** [NativeScript/NativeScript#3743]
<template *ngFor="let item of items; let i=index" >  <ion-slide *ngIf="i<5" >   <img [src]="item.ItemPic">  </ion-slide> </template>

how can i use this example on ListView

**Comment by NickIliev** [comment]
Hey @harriscreativity please post similar logic based and UI related questions in our community channels like [StackOverflow questions](http://stackoverflow.com/questions/tagged/nativescript) for NativeScript and [nativescript forum](https://discourse.nativescript.org/)

hint: If you are creating Angular-2 based application you have multiple options. From using code-behind logic to initialize exact number of items, to using [custom Angular directives](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/release/app/ui-category/ng-directives)
