### ISSUE TITLE
IOS: gestures are not passing through an element

### ISSUE THREAD

**Issue by dxshindeo** [NativeScript/NativeScript#3751]
Let's say I have the following code:

```
<StackLayout id="wrapper" style="width: 100%; height: 100%">
   <StackLayout id="click-me" (tap)="i_do_something()">
      <Label text="test"></Label>
   </StackLayout>
</StackLayout>
```

The idea is that I have a full page view which is tap-throughable, but the children inside it are not. This works fine in android, but not in IOS. 
In IOS I can tap the `click-me` element and get console.log, but the `wrapper` element itself is not letting taps through (I have a gmaps under it, that's why I need to pass through gestures).

If I set `isUserInteractionEnabled="false"` to `wrapper` element, then yeey, gestures pass through, *but* now gestures pass through its children as well, in this case, `click-me` element - I can't tap on it anymore. I also tried to set `isUserInteractionEnabled="true"` to this child, but still no taps received. It's like parents setting overrides childrens.

Can anyone help with this? Kind of blocking all development on IOS with such a silly thing.

**Comment by NickIliev** [comment]
Hey @dxshindeo indeed the event propagation in iOS is different from the implementation in Android.
This topic is often discussed and there are several related closed issues in this repository. You can take a look at this discussion [here](https://github.com/NativeScript/NativeScript/issues/3006) and see if the solution provided is applicable for your case.

Basically, you can try to turn off the event handler when needed like this:

**page.xml**
```
<StackLayout id="wrapper" tap="onParentTap" style="width: 100%; height: 100%" backgroundColor="green">
    <StackLayout id="click-me" tap="onChildTap" width="200" height="300" backgroundColor="red"  >
        <Label text="test"></Label>
    </StackLayout>
</StackLayout>
```

**page.ts**
```
export function onParentTap(args: EventData) {
  console.log("onParentTap");
}

export function onChildTap(args) {
  console.log("onChildTap");
  var parent = args.object.parent;
  parent.off("tap"); // same valid for touch and other gestures
}
```

The above example is for non-Angular application but the same principle can be applied in and Angular based project.

**Comment by dxshindeo** [comment]
Thank you for the info.
I guess I wasn't quite accurate enough:

```
<AbsoluteLayout style="width: 100%; height: 100%;">

	<!-- gmaps element -->
	<MapView style="width: 100%; height: 100%;"></MapView>

	<DockLayout style="width: 100%; height: 100%;">
		<StackLayout dock="bottom" class="dynamic-content-holder" style="width: 100%;" (tap)="myTap()">
			<Label text="Click me and I'll do magic!"></Label>
		</StackLayout>
	</DockLayout>

</AbsoluteLayout>
```
As a base layout I am using `AbsoluteLayout`, so I can show another layouts/elements on top of gmaps. Then I am showing dynamic content (with clickable buttons in it) at the bottom of the screen. To do that, I have to make a `DockLayout` in full screen height and then dock="bottom" the immediate child/content holder.

And here lies the problem - now the `DockLayout` is on top of gmaps, and no gesture cab get through this `DockLayout`.

'parent.off("tap");' - it only removes the listener, it still does not let taps pass through to element **underneath** it.

**Comment by dxshindeo** [comment]
A minor workaround to this specific "putting content at the bottom of the screen and don't block whole screen" case would be if it was possible to set `bottom="0"` to this dock layout. Unfortunately, `AbsoluteLayout` only allows positioning elements with `top` and `left`, so it might good to implement positioning with "bottom" and "right" as well.

**Comment by NickIliev** [comment]
@dxshindeo following your line of thoughts for using the AbsoluteLayout .**top** and **left** you can get the dimensions of your AbsoluteLayout (used as a main container) and calculate where you want your DockLayout placed using the **top**. To achieve that you can use **getMeasuredHeight()** method available for each view. 

e.g.
```
<AbsoluteLayout id="ab" style="width: 100%; height: 100%;">
	<!-- gmaps element -->
	<MapView style="width: 100%; height: 100%;"></MapView>

	<DockLayout top="{{ abMeuseredHeight }}" style="width: 100%; height: 100%;">
		<StackLayout dock="bottom" class="dynamic-content-holder" style="width: 100%;" backgroundColor="blue" tap="onDockTap">
			<Label text="Click me and I'll do magic!"></Label>
		</StackLayout>
        </DockLayout>

</AbsoluteLayout>
```

and in your code behind you can get the actual height of the absolute layout (which will be different for each device) and set it with small setTimeout (to ensure that all the layouts are rendered as only then you will get a value from this method)
```
export function onLoaded(args: EventData) {
    let page = <Page>args.object;

    var ab = <AbsoluteLayout>page.getViewById("ab");

    setTimeout(function() {
      console.log(ab.getMeasuredHeight());

      abMeuseredHeight = (ab.getMeasuredHeight()/5) * 4; // 80% of the AbsoluteLayout height
      vm.set("abMeuseredHeight", abMeuseredHeight);

      page.bindingContext = vm;
    }, 300);

}
```

This way you don't need to worry about event propagation and can use both events from MapView and from your DockLayout. test project available [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_3751)

**Comment by dxshindeo** [comment]
Thank you for snippets.

The `top` property won't work here, because `DockLayout` child (`class="dynamic-content-holder"`) is going to grow "downwards" - it will never grow upwards past the `top` value, because that's where `DockLayout` has set its living quarters. Meaning, if I want to display content at bottom, I would need to give my `DockLayout` a static, predefined height or I read its height every time a content has changed in its' child - `class="dynamic-content-holder"`. And then, when I have its height, I would adjust the `DockLayout` position. 

That is very .. well I can't find a word to describe it :D
It's a workaround, not a fix.

**Comment by NickIliev** [comment]
@dxshindeo yeah indeed this is a workaround for this specific case. Will close this as I think we resolved the main problem but if you want to log the **bottom** functionality of **_AbsoluteLayout_** as a possible feature request please open a new issue where the request will be on its own apart from the discussion here.
