### ISSUE TITLE
Official templates not working with {N} 2.5.2

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/NativeScript#3760]
I can't run any of the official non-typescript templates ([found here](https://www.tjvantoll.com/2016/02/22/creating-nativescript-templates/)) since updating NativeScript to 2.5.2.

```
$ tns create my-app-name --template tns-template-blank
$ cd my-app-name
$ tns run ios
```

The above fails with the following:

```
Copying template files...
  ◝ Installing tns-iosInstalling  tns-ios         <= This looks strange
/Users/daniel_rochelle/Documents/git repositorys/my-app-name
└── tns-ios@2.5.0 

  ◡ Installing tns-ios        <= Should this be repeated here?
Project successfully created.
Preparing project...
We have failed to check if we need to add a compatability LaunchScreen.xib due to: Error: ENOENT: no such file or directory, open '/Users/daniel_rochelle/Documents/git repositorys/my-app-name/app/App_Resources/iOS/Info.plist'
ENOENT: no such file or directory, scandir '/Users/daniel_rochelle/Documents/git repositorys/my-app-name/platforms/ios/myappname/Resources'
# run ios
```

Indeed neither the `App_Resources` or the `Resources` folder have been created.

All of the non-typescript templates fail similarly.

I tested the `tns-template-hello-world-ts` typescript template and it _did_ work. Just seems to be the plain JS ones that aren't.

MacOS: 10.12.3
XCode: 8.2.1

```
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.5.2           │ 2.5.2          │ Up to date    │
│ tns-core-modules │ 2.5.1           │ 2.5.1          │ Up to date    │
│ tns-android      │                 │ 2.5.0          │ Not installed │
│ tns-ios          │ 2.5.0           │ 2.5.0          │ Up to date    │
└──────────────────┴─────────────────┴────────────────┴───────────────┘ 
```

**Comment by dtopuzov** [comment]
This templates is depreciated and not supported. Will unpublish from npm.

**Comment by 3rror404** [comment]
Hi @dtopuzov,

so what is the new alternative to the templates? I found this article in the docs https://github.com/NativeScript/NativeScript/wiki/Using-the-%60tns-create%60-command

But using `tns create MyApp` uses the hello world template. How do we create an empty app like `tns-template-blank` used to do?
