### ISSUE TITLE
toggle individual listview content in nativescript with angular

### ISSUE THREAD

**Issue by BhuvaneswariVajravel** [NativeScript/NativeScript#3761]
hi i need to toggle individual content in listview when the respective  button is clicked in nativescript angular,
i added bellow my code. if anyone know please answer me. thanks in advance

   

     import { Component, OnInit } from "@angular/core";
    
    import { Item } from "./item";
    import { ItemService } from "./item.service";
    
    @Component({
        selector: "ns-items",
        moduleId: module.id,
        templateUrl: "./items.component.html",
    })
    export class ItemsComponent implements OnInit {
        items: Item[];
    	isList = true;
    	
        toggle(){
            this.isList = !this.isList;
      
     }
    
        constructor(private itemService: ItemService) { }
    
        ngOnInit(): void {
            this.items = this.itemService.getItems();
        }
    	
    }

and here my items.component.html

    <ActionBar title="My App" class="action-bar">
    </ActionBar>
    <StackLayout class="page">
       
        
         <ListView [items]="items" class="list-group">
          <template let-item="item">
    	 <GridLayout columns="auto,auto" width="210" height="210"  >
                <Label  [text]="item.name"  col="0"
                    class="list-group-item" visibility="{{isList ? 'visible' : 'collapse'}}"></Label>
    				<Button [text]="isList ? 'hide' : 'Show'"  col="1" (tap)="toggle()"></Button>
    				
    		   </GridLayout>
            </template>
    	 
        </ListView>
       
    
    </StackLayout>

here problem is when i click the button all the labels are toggle. so i need to generate the variable dynamically. i m very beginner so anyone can help me? 
thank in advance.

**Comment by tsonevn** [comment]
Hi @BhuvaneswariVajravel ,
For your case, you could set a unique id for the `Buttons` and the `Label`. then you should be able to get the needed `Label` by using `getViewById` method and to set up its visibility property. You could review the attached sample project.
app.component.html
```
tsonevn [5:46 PM] 
<GridLayout >
       <ListView class="list-group" [items]="listitems" separatorColor="white">
           <template let-item="item">
               <GridLayout backgroundColor="red" rows="*" columns="* * *">
                   <Label col="0" [text]="item.item1" class="list-group-item-heading"></Label>
                   <Label col="1" [text]="item.item2" class="list-group-item-heading" ></Label>
                   <Label col="2" [text]="item.item3" class="list-group-item-heading"></Label>
               </GridLayout>
           </template>
       </ListView>
   </GridLayout>
```
app.component.ts
```
import { Component } from "@angular/core";
import {Button} from "ui/button";
import {Label} from "ui/label";
import {Page} from "ui/page"

@Component({
   selector: "ns-app",
   templateUrl: "app.component.html",
})
export class AppComponent {
   items:Array<any>=[];
   constructor(private page:Page){
       this.items.push({name:"name1", labelid:"id1", buttonid:"1"});
       this.items.push({name:"name2", labelid:"id2", buttonid:"2"});
       this.items.push({name:"name3", labelid:"id3", buttonid:"3"});
   }
   toggle(args){
       var crButton:Button = <Button>args.object;
       var btnID = crButton.get("id");
       var crLabel:Label = <Label>this.page.getViewById("id"+btnID);
       crLabel.visibility="collapse";

   }
}
```

For further `How to` questions, please use our [StackOverflow thread.](http://stackoverflow.com/questions/tagged/nativescript)

**Comment by BhuvaneswariVajravel** [comment]
thank u very much @tsonevn 
i am very beginner can you please explain the

 toggle(args){
       var crButton:Button = <Button>args.object;
       var btnID = crButton.get("id");
       var crLabel:Label = <Label>this.page.getViewById("id"+btnID);
       crLabel.visibility="collapse";

   }


and here  args came from where and cant understand full function.
i already post this issue in stackoverflow.
