### ISSUE TITLE
ANDROID: TextView and cursor position change event like onSelectionChanged

### ISSUE THREAD

**Issue by daniel-idf** [NativeScript/NativeScript#3765]
I have a "custom" component -> extending TextView - but i need the "onSelectionChanged" method, to check the text at the current position. I cannot use the "onTouch" event because this event is triggered before the native android component return the right "spans" at the current position.

see: [https://discourse.nativescript.org/t/textview-and-cursor-position-change-event-like-onselectionchanged/356](https://discourse.nativescript.org/t/textview-and-cursor-position-change-event-like-onselectionchanged/356)

could you override the "onSelectionChanged" method or change the following line in "editable-text-base.android.js" (line 19 - version 2.5.0)...

_this._android = new android.widget.EditText(this._context);_
**example: this._android = new android.inputmethodservice.ExtractEditText(this._context);**

... or provide a method to change the android.widget component in custom components like the following example:

`EditableTextBase.prototype._createUI = function () {
this.android = this.createNativeUIElement();
...
}`
`
EditableTextBase.prototype._createNativeUIElement = function() {
return new android.widget.EditText(this._context);
}`

please.

**Comment by tsonevn** [comment]
Hi @daniel-idf,
 for your case, you could use TextField `updateTextTrigger` property at to set it to `textChanged`. Then you should be able to use TextFiled `propertyChangeEvent`, which will be fired on every new input in the Field.
For example:

main-page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
    <StackLayout class="p-20">
       <TextField hint="Field 1" updateTextTrigger="textChanged" id="tx" />
       <TextField hint="Field 2"  />
    </StackLayout>
</Page>
```
main-page.ts
```
import { EventData, PropertyChangeData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import {Observable} from "data/observable";
import {TextField} from "ui/text-field";

export function navigatingTo(args: EventData) {
    /*
    This gets a reference this page's <Page> UI component. You can
    view the API reference of the Page to see what's available at
    https://docs.nativescript.org/api-reference/classes/_ui_page_.page.html
    */
    let page = <Page>args.object;
    var textfield:TextField = <TextField>page.getViewById("tx");
    textfield.on("propertyChange", ((args: PropertyChangeData) => {
        var tField:TextField = <TextField>args.object;
        console.log(tField.text);
    }));
}
```

Could you verify, whether this is applicable for your case?

**Comment by daniel-idf** [comment]
Hi @tsonevn,

thank you for your answer, but i would like to catch the event "onSelectionChanged", not "characterChange" (

> The text property will be udpaded on every single character typed by the user.

). I am using an extended version of TextView (**EditText**) and now i would like to check the spannable object ("Text") at the current position for existing spans (getSpans). Now there is the problem: if i am using the "onTouch" event - "getSpans" provides the spans from the previous position. To get the spans at the current position i have to use the "onSelectionChanged" method.

I need an option to check the text/spannable object if the cursor position changed.

**Comment by tsonevn** [comment]
Hi @daniel-idf,
To extend android EditableText component and to overwrite the needed methods, you could use `.extend` method. 
How to extend android native classes in NativeScript could be also found in the attached articles from the documentation.
https://docs.nativescript.org/runtimes/android/generator/extend-class-interface
https://docs.nativescript.org/runtimes/android/generator/how-extend-works.html
For your help, I am also attaching sample project, where has been demonstrated, how to use `.extend` method.

main-page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page">

    <Placeholder creatingView="creatingView"/>
</Page>
```
main-page.ts
```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
declare var android:any; 
export function navigatingTo(args: EventData) {
    
    let page = <Page>args.object;

    page.bindingContext = new HelloWorldModel();
}

import placeholder = require("ui/placeholder");

export function creatingView(args: placeholder.CreateViewEventData) {
    var ExtendedEditableText = android.widget.EditText.extend({
        onTouch: function(view, event){
            console.log("on touch");
        },
        onSelectionChanged: function(start, end){
            console.log("onSelectionChanged");
            console.log("start "+start, "end ", end);

        }  
    })
    var nativeView =new ExtendedEditableText(args.context)
    nativeView.setSingleLine(true);
    nativeView.setEllipsize(android.text.TextUtils.TruncateAt.END);
    nativeView.setText("Native");
    args.view = nativeView;
}
```
main-page.js
```
var main_view_model_1 = require("./main-view-model");
function navigatingTo(args) {

    var page = args.object;
    page.bindingContext = new main_view_model_1.HelloWorldModel();
}
exports.navigatingTo = navigatingTo;
function creatingView(args) {
    var ExtendedEditableText = android.widget.EditText.extend({
        onTouch: function (view, event) {
            console.log("on touch");
        },
        onSelectionChanged: function (start, end) {
            console.log("onSelectionChanged");
            console.log("start " + start, "end ", end);
        }
    });
    var nativeView = new ExtendedEditableText(args.context);
    nativeView.setSingleLine(true);
    nativeView.setEllipsize(android.text.TextUtils.TruncateAt.END);
    nativeView.setText("Native");
    args.view = nativeView;
}
exports.creatingView = creatingView;
```

Hope this helps
