### ISSUE TITLE
Unable to display list and table in HtmlView in Android and table in iOS

### ISSUE THREAD

**Issue by sudhanshu-15** [NativeScript/NativeScript#3766]
I am trying to add a HtmlView in my app, the html will contain list(ordered or unordered) and will also contain a table. The HtmlView is unable to render list and table in Android, whereas on iOS it is able to render the list but not able to render the table. 
Is there a way I could get this working?
I don't want to go WebView route because it doesn't integrate well with my implementation and I have tried it already.
It will be really helpful if someone could point me to the right 

![screenshot_20170309-164151](https://cloud.githubusercontent.com/assets/883233/23772079/a9a0d682-04e7-11e7-8cca-0b8b29589112.png)
![img_0014](https://cloud.githubusercontent.com/assets/883233/23772083/abca8b42-04e7-11e7-8b85-fa1818d34c4e.PNG)

**Comment by tsonevn** [comment]
Hi @sudhanshu-15,
I reviewed your case, however, it seems to be a limitation of Android and the fact that not all HTML tags have been supported. 
In Nativescript we are using Android TextView's `fromHtml` method while implementing our HtmlView.
For your convenience, you could review this thread in StackOverflow and the attached article.
http://stackoverflow.com/questions/3150400/html-list-tag-not-working-in-android-textview-what-can-i-do
https://commonsware.com/blog/Android/2010/05/26/html-tags-supported-by-textview.html
At this point the way to workaround this behavior is to use WebView.

Regarding the second issue with displaying table in ios HtmlView, could you provide some sample HTML code, which you are trying to display in the View?

Regards,
@tsonevn

**Comment by sudhanshu-15** [comment]
Thank you for your response and sharing the knowledge about Android textview.
Here is the sample HTML I am using:

```
<html>

<body>
    <p>Dear Sudhanshu Siddh,</p>
    <p>Congratulations on your admission to IUPUI. We are excited about your future arrival on campus!</p>
    <p>Your next step is to complete the SEVIS Transfer-In Request e-form that will allow us to prepare your immigration documentation. This is an electronic form, which is&nbsp;located on the \"Complete Your Application\" tab in iStart:&nbsp;https://www.iu.edu.
        <em>Log into iStart through Limited Services for Students &amp; Scholars. You will need your <strong><span style=\"font-family: \'Verdana\',\'sans-serif\';\">University ID: 1111111</span></strong>&nbsp;and iStart Limited Access&nbsp;<strong><span style=\"font-family: \'Verdana\',\'sans-serif\';\">PIN: 1234.</span></strong></em>&nbsp;&nbsp;</p>
    <ul>
        <li>Please carefully enter the name and email address of your International Student Advisor. This is the person at your current US school who works with your I-20.</li>
        <li>Once you complete and submit this SEVIS Transfer-In Request e-form, the form will automatically be sent to your International Student Advisor via email at the address you provided.</li>
        <li>Your International Student Advisor will then complete the second part of the SEVIS Transfer-In Request e-form.</li>
        <li>Your SEVIS record will be released to IUPUI.</li>
    </ul>
    <p>Please let us know if you have any questions about the SEVIS Transfer-In Request e-form or the transfer process. You can contact us at&nbsp;mail@mail.edu.</p>
    <table>
        <tr>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Age</th>
        </tr>
        <tr>
            <td>Jill</td>
            <td>Smith</td>
            <td>50</td>
        </tr>
        <tr>
            <td>Eve</td>
            <td>Jackson</td>
            <td>94</td>
        </tr>
    </table>
</body>

</html>
```

**Comment by sudhanshu-15** [comment]
Here is what I found on the HtmlView, it is able to render tables but the view is not scrollable and hence is truncated. I am trying to find a way to make the htmlview scrollable. Will update if I find something useful. If you happen to have some suggestion please let me know. Thank you for the help.

**Comment by sudhanshu-15** [comment]
I added the HtmlView inside a ScrollView and that did the trick. Thank you for all the help.

**Comment by Reier360** [comment]
@sudhanshu-15 Hi, did you manage to get table tags to work?

**Comment by sudhanshu-15** [comment]
@Reier360 I was able to get the table tags work but we finally resolved to using webview instead.
