### ISSUE TITLE
http module failure in Android

### ISSUE THREAD

**Issue by bfattori** [NativeScript/NativeScript#377]
I'm getting an NPE when I try to call a server with the http module. I'm pretty sure this is the exception being thrown:
```
W/System.err( 9165): java.lang.NullPointerException
W/System.err( 9165):    at com.tns.Async$Http$RequestResult.getHeaders(Async.java:106)
W/System.err( 9165):    at com.tns.Async$Http$HttpRequestTask.doInBackground(Async.java:263)
W/System.err( 9165):    at com.tns.Async$Http$HttpRequestTask.doInBackground(Async.java:214)
W/System.err( 9165):    at android.os.AsyncTask$2.call(AsyncTask.java:287)
W/System.err( 9165):    at java.util.concurrent.FutureTask.run(FutureTask.java:234)
W/System.err( 9165):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
W/System.err( 9165):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
W/System.err( 9165):    at java.lang.Thread.run(Thread.java:856)
```

**Comment by atanasovg** [comment]
Could you please share the URL of the request so that I may debug the issue locally? I took a quick look at the code and couldn't find an obvious reason for this exception.

**Comment by bfattori** [comment]
The issue is that the connection receives no response from the server. The request is sent, and the server accepts the request but generates no response. What appears to be happening (I'm not debugging the actual Android runtime, so I don't know _for sure_) is that the connection eventually times out, but no error is returned - it just **fails silently**.

When I corrected the server and made it send the response, things started working as expected. So, here are 3 suggestions:

1) Implement a timeout of some large amount, like 300 seconds (5 minutes) even when the user leaves the timeout at zero. Instead, implement a constant like `NO_TIMEOUT` which will explicitly _not set a timeout_.

2)  When the connection receives no response, reject the request in the `http` module. As it stands, this does not appear to happen. This error can be forwarded to the `onerror` callback for `XMLHttpRequest`, which leads me to my final point...

3) Add an `onerror` handler to `XMLHttpRequest`. You have `onreadystatechange` but nothing to handle an error situation.

**Comment by bfattori** [comment]
I see in the 1.2.0 codebase you've added the `onerror` event.

**Comment by bfattori** [comment]
It was an ExpressJS server at localhost, port 80. It was set up to respond
to certain routes, none of which are important. However, if the server
never sent a response (accepted the request, generated no response) there
was no error reported on Android. The request would eventually timeout or
fail, but there was no way to catch the error in NativeScript's http object.

On Wed, Jul 22, 2015 at 10:07 AM, Nedyalko Nikolov <notifications@github.com
