### ISSUE TITLE
iOS Slide page transition causes "snap" behaviour

### ISSUE THREAD

**Issue by josempbrites** [NativeScript/NativeScript#3775]
Hi guys,

### Tell us about the problem
Since the latest update I'm having an issue when I set actionBar `navigationBar.translucent = false;` and remove the border. Is was working fine before, but now the page navigation and transitions are making a strange snap animation, as if, when the view loads it starts behind the actionbar.

Any ideas on what's going on? Can you test this?

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.2
- Cross-platform modules: 2.5.1
- Runtime(s): iOS 2.5.0

### Please tell us how to recreate the issue in as much detail as possible.
Adding the code bellow to a pageLoad event. It only happens when navigating to a details view for example.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```   
if (platform.isIOS) {
        var navigationBar = frameModule.topmost().ios.controller.navigationBar;
        navigationBar.barStyle = 1;
        navigationBar.translucent = false;
        navigationBar.setBackgroundImageForBarMetrics(UIImage.new(), UIBarMetrics.Default);
        navigationBar.shadowImage = UIImage.new();   
       }
```

**Comment by NickIliev** [comment]
@josempbrites  can you elaborate a bit more? 
I've tested the described scenario with [this sample project](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_3775) but was not able to reproduce a "snap" behavior.

Please share with us a sample code that reproduces this case or provide more details on what transactions you are using, is your page using ActionBar and all that could help us investigate further.

**Comment by josempbrites** [comment]
@NickIliev Thank you for your time. I've figured out what was the issue based on your sample project. The problem was not related with the ActionBar, but with the transition. I'm using a slide transition (not the flip transition you used). 

You can try and change the transition to slide, to see what was my problem. 

I've removed the transition and now the navigation behaves as it should. The slide transition would come in handy in some cases though.

**Comment by NickIliev** [comment]
@josempbrites thank you for the follow-up! I was able to reproduce the issue using slide transition.
Indeed in iOS, there is a strange overlapping during the animation. Logged this one as a bug.

Steps to reproduce: 
- use [this test project](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_3775)
- navigate from **_main page_** to **_sub page_** with slide transition - there is an overlapping in the top part of the screen around the ActionBar (the actual bug)
- navigate back with another transition (e.g. flip) - everything works as expected

**Comment by NickIliev** [comment]
Similar behaviour reported [here](https://github.com/NativeScript/NativeScript/issues/3906)

**Comment by uzarsalan** [comment]
Hi! i have the same problem with TNS v3.2.0. Is anybody has this bug?

**Comment by 7ammer** [comment]
This seems similar to what is described? https://github.com/nativescript-vue/nativescript-vue/issues/200
