### ISSUE TITLE
http module SLOW on Android

### ISSUE THREAD

**Issue by bfattori** [NativeScript/NativeScript#378]
I am having issues with the `http` module. A simple http request is sent, _and returned_ from the server in < 5ms. But the response in NativeScript `http` module doesn't show up for about 1 minute.

I'm running this on the emulator, using 10.0.2.2 to access my local machine's loopback (where the server is located). As I said, the app sends the request, the server sends the response, then the  runtime takes forever to return the response to my application.

**Comment by emiloberg** [comment]
Is the http request in a chain of promises?

I've noticed that sometimes it takes {N} a long time to kick of the next function after one promise resolves.  Adding a few console.logs at the start/end of each function shows that it just holds between two promises. I've spent quite long time to figure out when and why this happens by I have _no_ idea. The way I "solved" is was to make the promise chain smaller and, I kid you not, reordered some of promises.

If you're doing your http request with promises, try removing all other promises but the http one and see if that "solves" it...

**Comment by bfattori** [comment]
The server was not responding, so the request was timing out after about 3 minutes but returning no error. see #377 for more info.

**Comment by vforv** [comment]
Hello,

I am using Nativescript with Angular 
And Angular HttpClient but requests are slow sometime in localhost it take few seconds to finish request here is my code:

```
public getMenu(code: string) {
    alert('menu');
    return this.http.get(`${environment.emenuApi}/menu/list/${code}`) //TODO: ${qrCode}
      .pipe(
        tap((data) => {
          alert(data)
        }),
        map((data: any) => data.result)
      );
  }
```

I put alert to see how much time it lags...
