### ISSUE TITLE
[Feature Request] Support multiple item templates within Repeater

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/NativeScript#3781]
As far as I can tell, we can not use templates within the Repeater control.

In an ideal world this would work exactly like the [`ListView` `itemTemplateSelector`](https://docs.nativescript.org/cookbook/ui/list-view#define-multiple-item-templates-and-an-item-template-selector-in-xml).

```
<Repeater items="{{ items }}" itemTemplateSelector="SOME EXPRESSION">
  <Repeater.itemTemplates>
  
    <template key="template-one">
      <!-- LAYOUT 1 -->
    </template>
    
    <template key="template-two">
      <!-- LAYOUT 2 -->
    </template>
    
  </Repeater.itemTemplates>
</Repeater>
```

**Comment by NickIliev** [comment]
Hey @3rror404, as this functionality is already available for ListView, isn't that option applicable for you?

**Comment by 3rror404** [comment]
Hi @Nicklliev,
Yes and no. There are some issues with the list view that don't exist with the repeater. 
It's not possible to set the listview's height to automatically fit its items. This can be especially difficult when each time is of different height. 
The list view also has a built in scrolling behaviour, tap highlighting, cell dividers, all of which are not desired sometime. 

Having a basic repeater with a more complex templating system would make life easier for me.

**Comment by OPADA-Eng** [comment]
any news for this feature ?

**Comment by DimitrisRK** [comment]
It would be great if this feature got implemented. It's solving so many problems.
