### ISSUE TITLE
Disable App Idle State

### ISSUE THREAD

**Issue by maniacube** [NativeScript/NativeScript#3788]
Hi,

If app goes to background state, after some time app will reach the idle state. How to stop the app that reaches idle state and remains in the background state. Please help us to achieve this.

Thanks & Regards,
Mani

**Comment by tsonevn** [comment]
Hi @maniacube, 
Could you provide some more info about your case and what you are trying to achieve? 

In the meantime, you could review [nativescript-idle](https://www.npmjs.com/package/nativescript-idle) plugin and verify, whether it is applicable for your scenario. This plugin allows you to post a callback to be executed when the application is in an idle state.

Regards,
@tsonevn

**Comment by tsonevn** [comment]
Hi @maniacube 
In our further research, we found a simple way to prevent an Android application from reaching the idle state. You could have a video playing on the page and the device won't go to sleep. 

More about this solution you can find [here](http://stackoverflow.com/questions/33933555/prevent-android-chrome-from-going-idle-auto-locking-sleeping-phone).

However, as you can see in the attached thread from StackOverflow, disabling the App Idle State is not recommended.
