### ISSUE TITLE
Firebase plugin

### ISSUE THREAD

**Issue by nikolay-diyanov** [NativeScript/NativeScript#379]
A Firebase plugin would be a great addition to the Marketplace as developers would have subscriptions to different cloud backend providers and Firebase would be one of them.

*If you are interested in this feature please __add comments below__ with specific requirements and [vote for this feature](https://nativescript.ideas.aha.io/ideas/NS-I-48) in our ideas portal.*

**Comment by jbristowe** [comment]
Can you elaborate on your requirements? [Firebase has a JavaScript API.](https://www.firebase.com/docs/web/api/) Am I missing something?

**Comment by nikolay-diyanov** [comment]
It seems like this JavaScript API is browser dependant and {N} does not work with such APIs.

**Comment by N3ll** [comment]
You can read more about the topic in the NativeScript google group here: https://groups.google.com/forum/#!topic/nativescript/yyd52uU15YU.

**Comment by valentinstoychev** [comment]
The plugin is now available! 
https://plugins.telerik.com/nativescript/plugin/firebase
