### ISSUE TITLE
The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by initialcatalog** [NativeScript/NativeScript#3797]
Hi,

I use telerik guage in  first page.
When I switch to another page from this page by pressing "backspace" key, I see this error message: 

`java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.`

Could you help me please?

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#128
