### ISSUE TITLE
Error with "tns run ios --emulator" on mac os 10.10.2

### ISSUE THREAD

**Issue by n0n0n0** [NativeScript/NativeScript#38]
When I run command "tns run ios --emulator" from demo project directory, ios simulator running but has not demo application inside. Its just iPhone/iPad desktop inside with Safari icon on bottom screen, and its also has second screen with 2 icons of my xcode project. So in mac terminal i got this error after waiting about minute:

Starting iOS Simulator (after this message simulator starts and nothing happend more about 1.5 minute, and after i got this -> )

Session started with error  Error Domain=DTiPhoneSimulatorErrorDomain Code=2 "Timed out waiting for device boot" UserInfo=0x100b9b190 {NSLocalizedDescription=Timed out waiting for device boot}

**Comment by n0n0n0** [comment]
I have Xcode 6.2, OS X 10.10.2

**Comment by Fatme** [comment]
Hi @n0n0n0,

Can I ask you to open .xcodeproject file - it is located in `platforms/ios/` directory and try to run the project in simulator from xcode? 
I also want to ask you to execute ` $ tns run ios --emulator --log trace ` and sends us the output.

**Comment by n0n0n0** [comment]
I just open xcodeproject file from `platforms/ios/` as you said, and successfully run it from XCode. Seems app works fine inside simulator. But if I try `tns run ios --emulator` its still dosent work, just run emulator but not start app inside.

Here is trace log:
[gist](https://gist.github.com/n0n0n0/a852dd0a918bae3dc15b)

**Comment by jkaan** [comment]
I'm having the same problem. Is this issue still being worked on ?

**Comment by jlooper** [comment]
+1 I have the same issue, could we reopen this? Why was it closed without comment @enchev -  maybe it's been resolved elsewhere?

**Comment by jlooper** [comment]
I was able to resolve the issue by checking permissions and making sure I was able to run the app without running it as root.

**Comment by rikbru** [comment]
I reckon a lot of people on OSX might run into this. Seems like it's indeed related to installing nativescript as root, running "sudo npm install nativescript -g" instead of "npm install nativescript -g"

It will cause the permissions to be messed up for the project. I got a black screen when starting the emulator using "sudo tns run ios --emulator" while I could get the xcode project to run from the project's /ios folder.

You can fix it by making npm work without root (sudo), explained here: http://www.johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/

What I did was remove nativescript, clean npm cache, chown the node_modules folder like in the article's comment section above, reinstall without sudo. All seems to work now..

**Comment by cinder92** [comment]
i'm receiving same error after tns create command, here y copy and paste

`Command failed: /bin/sh -c ruby -e "require 'xcodeproj'; Xcodeproj::Config.new('/Users/dantecervantes/Documents/nativescript/diocesis/platforms/ios/plugins-debug.xcconfig').merge(Xcodeproj::Config.new('/Users/dantecervantes/Documents/nativescript/diocesis/app/App_Resources/iOS/build.xcconfig')).save_as(Pathname.new('/Users/dantecervantes/Documents/nativescript/diocesis/platforms/ios/plugins-debug.xcconfig'))"
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- xcodeproj (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'`

this is the command that i'm using  `sudo tns livesync ios --emulator --watch`, if i delete `sudo` i receive an error for permissions.

is this issue still open?

thanks!

**Comment by bernhardwaidacher** [comment]
@cinder92 I'm having the same issue. Did you find a solution?
