### ISSUE TITLE
XML Schema

### ISSUE THREAD

**Issue by ayongw** [NativeScript/NativeScript#380]
The default layout file is like below. But I can not found the schema file in the location. Is the locaton changed or something else?
My NativeScript version is 1.1.1
```xml
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
  <StackLayout>
    <Label text="Tap the button" cssClass="title"/>
    <Button text="TAP" tap="{{ tapAction }}" />
    <Label text="{{ message }}" cssClass="message" textWrap="true"/>
  </StackLayout>
</Page>
```

**Comment by enchev** [comment]
We are working on this: https://github.com/NativeScript/NativeScript/issues/169!
