### ISSUE TITLE
Incorrect returned value fs.knownFolders.currentApp() in IOS

### ISSUE THREAD

**Issue by nakedcity** [NativeScript/NativeScript#3805]
tns-cli version: 2.5.2
tns-android: 2.5.0
tns-ios: 2.5.0

Details: 
fs.knownFolders.currentApp().path returns / which is not the current path where the app is in the ios device while in android works just fine.

**Code to reproduce and test**

`console.log('CSS exists:', fs.File.exists(fs.path.join(fs.knownFolders.currentApp().path, 'app.css')))`

In IOS is false while in android returns the correct result true

**Comment by tsonevn** [comment]
Hi @nakedcity,
Thank you for reporting this issue, 
I reviewed that case, however, was unable to reproduce this behavior on my side.
I tested `currentApp()` method on ios real device and everything seems to work as expected and the correct path to be returned.
For your convenience, I am attaching a sample code and screenshot.
main-page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page">

    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>

    <StackLayout class="p-20">
        <Label text="Tap the button" class="h1 text-center"/>
        <Button text="TAP" tap="onTap" class="btn btn-primary btn-active"/>
        <Label text="{{ message }}" class="h2 text-center" textWrap="true"/>
    </StackLayout>
</Page>

```
main-page.ts
```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import {knownFolders, path, File} from "file-system"


export function navigatingTo(args: EventData) {
 
    let page = <Page>args.object;
 
    page.bindingContext = new HelloWorldModel();
}

export function onTap(){
    console.log("show current folder path");
    var crpath = knownFolders.currentApp().path;
    console.log(crpath, 'app.css'); 
    var filePath = path.join(crpath, "app.css");
    var exists = File.exists(filePath);
    console.log("exists: "+exists);
    alert("Current folder path: "+crpath);

}
```
![img_0005](https://cloud.githubusercontent.com/assets/17448734/23985826/cfacee32-0a29-11e7-9767-872e3e2a7e55.jpg)

Regarding that, could you provide some more info about the iOS device, you are using? It would also help if you could send us sample project, which could be debugged locally

**Comment by nakedcity** [comment]
All ios emulators and devices I connected have the same faulty behaviour. 

![screen shot 2017-03-16 at 14 26 47](https://cloud.githubusercontent.com/assets/4519631/23998234/c0cda00c-0a54-11e7-9ff4-9817e6ad1927.png)

![screen shot 2017-03-16 at 14 28 05](https://cloud.githubusercontent.com/assets/4519631/23998257/cfcfdbec-0a54-11e7-83c6-dbd2f2f5dd1b.png)

**Comment by nakedcity** [comment]
Found the error __dirname was overwritten by webpack see https://github.com/webpack/webpack/issues/1599

**Comment by tsonevn** [comment]
Hi @nakedcity,
Could you verify, whether you will have the same problem while using the latest version of `nativescript-dev-webpack` plugin? 
For further help, you could use the instructions [here](https://docs.nativescript.org/tooling/bundling-with-webpack#installation-and-configuration).

**Comment by nakedcity** [comment]
Sorry I dont use the nativescript webpack plugin I wrote my own
