### ISSUE TITLE
Android: permissions using camera

### ISSUE THREAD

**Issue by dxshindeo** [NativeScript/NativeScript#3806]
The logic for requiring camera permissions is not correct, in `nativescript-camera` plugin.

```
exports.requestPermissions = function () {
    if (android.support.v4.content.ContextCompat.checkSelfPermission(applicationModule.android.currentContext, android.Manifest.permission.WRITE_EXTERNAL_STORAGE) != android.content.pm.PackageManager.PERMISSION_GRANTED) {
        android.support.v4.app.ActivityCompat.requestPermissions(applicationModule.android.currentContext, [android.Manifest.permission.CAMERA, android.Manifest.permission.WRITE_EXTERNAL_STORAGE], REQUEST_REQUIRED_PERMISSIONS);
    }
};
```

The check happens against `WRITE_EXTERNAL_STORAGE`, so if I have the permission to WRITE already, the check thinks I also have permission to CAMERA, which I don't, because it was never checked against.

**Comment by NickIliev** [comment]
resolved with the following PR [https://github.com/NativeScript/nativescript-camera/pull/33/files](https://github.com/NativeScript/nativescript-camera/pull/33/files)
