### ISSUE TITLE
Feature - nativescript specific entry point in package.json

### ISSUE THREAD

**Issue by gngeorgiev** [NativeScript/NativeScript#3808]
Hey guys,

Different module loaders and frameworks recognize specific fields in the package.json of installed packages as an entry point e.g.

* Node.js - main
* Browserify - browser
* Rollup - rollup
* Rect Native - react-native

Since in Everlive we are looking to create platform specific bundles we could really use such a feature in NativeScript.

Regards.

**Comment by yyosifov** [comment]
Issue moved to [NativeScript/nativescript-cli #2627](https://github.com/NativeScript/nativescript-cli/issues/2627) via [**ZenHub**](https://www.zenhub.com/)
