### ISSUE TITLE
iOS combination error between cocoapod and framework.bundle 

### ISSUE THREAD

**Issue by code0wl** [NativeScript/NativeScript#3809]
Currently having an issue when using cocoapods in combination with a framework bundle in unison.
I am trying to load two different types of frameworks into our a project. One is a pod using CocoaPod and the other is being manually added the resource folder.

Once the manual copy framework is integrated into the project. I can no longer run the framework/library that is included using CocoaPods. I get a reference error saying that the runtime objects for the cocoapod framework do not exist.

in this case the error message is:
> Xcode stdout
```bash
The bundle “PersistenceTesting” couldn’t be loaded because its executable couldn’t be located.
```

> bash debug stdout
```bash
com.apple.CoreSimulator.SimDevice.93AAB200-A581-4BE4-BEC0-4360B1FA74FB.launchd_sim[95792] (UIKitApplication:org.nativescript.frameworkissuedemo[0x93fc][73825]): Service exited due to Segmentation fault: 11
```

Demo repo => https://github.com/code0wl/nativescript-framework-issue-demo

Combining these two frameworks together in Native for iOS seem to work fine. But using NativeScript I get the above mentioned error. Is there a step I am missing in the demo repo?

**Comment by code0wl** [comment]
Definitely open for any input at the moment. Has anyone had any success with a similar issue?

**Comment by ivanbuhov** [comment]
This issue was moved to NativeScript/ios-runtime#737
