### ISSUE TITLE
Loaded event of Page is not raised at proper time

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#381]
The child elements are not being instantiated yet. Consider the following code snippet
```
function pageLoaded(args) {
    var page = args.object;
    // rootView is a StackPanel inside the Page, declared in XML
    var rootView = view.getViewById(page, "root");
    var nativeView = rootView.nativeView; // this is undefined
}
```

**Comment by hshristov** [comment]
You could switch from page loaded event to page navigatedTo.

**Comment by valentinstoychev** [comment]
Is this a workaround or the *proper way* to implement it?

**Comment by hamorphis** [comment]
Is it possible that this is caused because an underscore is missing before nativeView?
