### ISSUE TITLE
Make imageSource work in AOT workers

### ISSUE THREAD

**Issue by dxshindeo** [NativeScript/NativeScript#3811]
So in AOT applications we cannot reference ANY plugin, which is a giant drawback (discussed here: https://github.com/NativeScript/NativeScript/issues/3581).

> The best solution would probably be to use a separate entry point in the webpack config for the "worker" module, and include (duplicate) all referenced non-UI modules like console, filesystem, etc.

I am not really getting the quoted part - what exactly do I need to add to my webpack config, in order for `var imageSource = require("image-source");` to be accessible in worker?
I can't process images on UI thread, a single image blocks it for like ~5s, so I have to do it on worker thread.

**Comment by NickIliev** [comment]
Ping @hdeshev

**Comment by m-abs** [comment]
Did you find a solution to this?

**Comment by dxshindeo** [comment]
Nope.

**Comment by m-abs** [comment]
Maybe you could use the vendor.ts file?

If you export `image-source` from `app/vendor`, you should be able to import it in your worker-script from `app/vendor`

**Comment by NickIliev** [comment]
@dxshindeo to prevent large images blocking the UI thread you can use `loadMode` set to `async`.
I have just written an article (PR for revision [here](https://github.com/NativeScript/docs/pull/776)) explaining how to improve the performance when working with large images) and will go live pretty soon. With this solution, you don't have to use workers for ImageSource.

e.g.
```
<Image src="{{ largeImage }}" loadMode="async">
```

**Comment by dxshindeo** [comment]
> I can't process images on UI thread

By process I meant convert them to base64, because I am going to send the image to the server. The conversion itself is the blocking aspect, therefore `loadMode="async"` won't help here.
