### ISSUE TITLE
Why to use NativeScript color module?

### ISSUE THREAD

**Issue by bini7a** [NativeScript/NativeScript#3823]
Hi, I'm confused why do we need to use color module instead of using simply the css color values? Using a module is an extra load to the app. But there might good reason for it.

**Comment by bradmartin** [comment]
You typically don't need it unless you need to use colors valid for Android and iOS methods. It's just part of the core, and used in lots of places to make sure your css colors are valid when they're being translated into color values for Android and iOS. There is a method `isValid()` that determines if a string is valid so the calls to native APIs don't throw exceptions which again your css needs to be valid for a hex to actually use it's native value for the platform APIs. Hope that makes sense :)

**Comment by bini7a** [comment]
This means all css color values are not valid for Android and iOS? Only color values that are defined in color module are valid for Android and iOS?
Thanks for your reply.

**Comment by bradmartin** [comment]
No. But let's say you use 'red' as your css color. Well to be used with
native APIs on Android you need to convert that string into a valid hex
color so the color module handles that for you among other things. So it's
an important piece for nativescript to provide css as the connecting piece
to native styling methods on Android and iOS. Since css isn't a real thing
on native platforms :)

**Comment by bini7a** [comment]
So, if I use hex value then I don't need use color module. Right?

**Comment by NordlingArt** [comment]
@bini7a - Different use cases may be:

```js
const Color = require("color").Color;
const Label = require("ui/label").Label;

const labelView = new Label();

// When working with NativeScript view modules, a simple hex string is enough
labelView.color = "#ff0000";

// For native views, you may to use the Color module
labelView.ios.textColor = new Color("#ff0000").ios;
```
