### ISSUE TITLE
Fetch does not support the full spec in nativescript

### ISSUE THREAD

**Issue by morsdyce** [NativeScript/NativeScript#3824]
### Tell us about the problem
Fetch does not support the full WHATWG fetch spec.
For example if you want to clone a request or a response it's not possible because the clone method is unavailable.

In the fetch module you specify:
"Implementation of fetch API. Modified version of https://github.com/github/fetch."

Is there a specific reason why the full implementation was not used? I've overridden the fetch implementation locally using this polyfill and it worked perfectly as it uses the underlying XMLHttpRequest api which is working in nativescript so there is no reason i can think of to think why the official polyfill can't be used here.

I'm willing to submit a PR unless there is a specific reason why you implemented it this way.

### Which platform(s) does your issue occur on?
Both (did not explicitly check on android but via reading the fetch implementation in the code base).

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.2
- Cross-platform modules: 2.5.1
- Runtime(s): tns-ios 2.5.0
- Plugin(s): "nativescript-websockets": "^1.3.1"

### Please tell us how to recreate the issue in as much detail as possible.
Create a Request object and then execute clone method on that object.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```js
var request = new Request('https://www.google.com');
request.clone(); // clone is not a function
```

**Comment by bradmartin** [comment]
I'm not from the team but I bet they'll love a PR to improve it. I also can't see a reason why not, only thing I can think of was to provide the functionality and not spend the time implementing everything (dev, test, etc). You'll prob hear from the team on Monday :)

**Comment by m-abs** [comment]
It would be great to have full support of fetch.
But it's not just `clone` that's missing, binary calls are also missing see: #570

I'm also not on the team, but I'm also sure they'd love to approve a PR on this.

The README.md on `fetch` says it's a modified version, but not what those modifications are, but it could be these lines: https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/fetch/fetch.js#L4-L11

**Comment by NickIliev** [comment]
Hey, @morsdyce we greatly appreciate any features that will improve NativeScript functionality.
I am login this one as a feature request but keep in mind that NativeScript is an open source project you can also participate and become one of the contributors (for example by extending the fetch module). Anyone who wants to contribute is welcome - [here you can find the contributors guide](https://www.nativescript.org/contribute)

[The original source code for the fetch module is here](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/fetch/fetch.js) and can guide you on how to extend the implementation.

**Comment by ilyagelman** [comment]
@NickIliev These two issues look quite different to me. Although they are related to the same problem (not supporting the full spec), it doesn't mean those can't be tackled separately.

It might be too much work for one person to contribute the full support for the spec, but if issues like that would be separated, it seems more welcoming to fix all of them step by step.

**Comment by tjvantoll** [comment]
@ilyagelman Would you mind creating a new issue specially for the inability to clone `Request` objects in NativeScript? The more specific issue will be more actionable for us, and you should be able to copy/paste most of the description you used when creating this issue.
