### ISSUE TITLE
Apple Store reject app~how to delete 'Automatic App Updates' reference ?

### ISSUE THREAD

**Issue by Leo-lay** [NativeScript/NativeScript#3827]
Hi,
  App was Apple off the shelf, told me inside with some **hot repair, update the framework,** but I did not use these procedures inside, I found in http://www.telerik.com/platform#deploy there are automatic repair The framework, I would like to know if there is any way to remove this.

- Cross-platform modules: 2.5.1
- Runtime(s): tns-ios 2.5.0

Does anyone have the same confusion with me？
Thanks & Regards~

**Comment by tsonevn** [comment]
Hi @Leo-lay.
Thank you for contacting us.

We reviewed your case, however, the given information is not enough, to investigate your issue and provide a solution for it.
It would help if you could give us some more info about the way, you publish your app. Do you use NativeScript CLI and its `tns publish ios` command, Xcode or you are publishing with Telerik Platform?

Please also send us your project `package.json` file with the plugins that has been used in the project and the content of `Info.plist` file located in `app/App_Resources/iOS` folder.

**Comment by Leo-lay** [comment]
Hi @tsonevn .
Thank you for your reply.

Last time i used  `tns publish ios ` command to push app to apple store.

follow is my  [package.json](https://gist.github.com/Leo-lay/2baa1c7de0490d38affd638308bbbdf5) &  [info.list](https://gist.github.com/Leo-lay/49c9d632381875139a8d9826d8dddb9d)

Please let me know if you need more information

Thanks & Regards.

**Comment by tsonevn** [comment]
Hi @Leo-lay, 
We have tested this behavior while using the attached Info.plist and `package.json` files and was able to publish an app while using `tns publish ios` command.

Regarding that could you provide some more info about your Xcode version and info, whether you have made some extra changes in the `Info.plist`, before publishing the app.

In the meantime, you could also verify, whether the app has been signed with the correct certificate while opening the project with Xcode.
![image](https://cloud.githubusercontent.com/assets/17448734/24208383/2d8612e8-0f2c-11e7-80c3-c95334c0ff01.gif)
