### ISSUE TITLE
[iOS] Crashes on Device, runs flawlessly on Emulator

### ISSUE THREAD

**Issue by premjg** [NativeScript/NativeScript#3828]
### Tell us about the problem
My app runs fine without any errors on different emulator devices (6, 7plus) but fails to start on my real device. It installs fine without errors and crashes instantly. Occasionally, it starts for a few seconds and crashes by itself.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.2
- Cross-platform modules: 2.5.0
- Runtime(s): 2.5.0
- Plugin(s): 

```
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/router": "3.4.3",
    "angular2-uuid": "^1.1.1",
    "moment": "^2.17.1",
    "nativescript-angular": "1.4.0",
    "nativescript-barcodescanner": "^2.4.0",
    "nativescript-numeric-keyboard": "^2.1.1",
    "nativescript-plugin-firebase": "^3.10.2",
    "nativescript-pulltorefresh": "^1.1.10",
    "nativescript-theme-core": "~1.0.2",
    "ramda": "^0.23.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.0.1",
    "tns-core-modules": "2.5.0"
```
### Please tell us how to recreate the issue in as much detail as possible.
Not sure

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Here's a gist of the crash log I recovered from the device.
https://gist.github.com/premjg/3e16a058f3bd63abaf7cbef174cd530a

**Comment by NordlingArt** [comment]
If you open the iOS project inside XCode, you can run the build to your real device from there and log the error of the crash.

**Comment by premjg** [comment]
@NordlingArt Doing it now.

**Comment by tsonevn** [comment]
Hi @premjg, 
In the description above you have mentioned that you are using NativeScript CLI 2.5.2 with old iOS Runtime.
Could you change `tns-ios` to `2.5.0` in your project `package.json` file? You should also delete `platforms` and `node_modules` folders, before rebuilding the app with `tns run ios`.

Please let me know, whether this helps.

**Comment by premjg** [comment]
@tsonevn - sorry my bad. It was `2.5.0` - updated my original comment.

**Comment by tsonevn** [comment]
Hi @premjg,
 The cause of the large backtrace in the crash log could be related to Observable that was being subscribed to on some of the pages and has not been unsubscribed.
In regard to the problem, this issue could be caused due to an issue with app signing. 

Could you delete `platforms` folder and the app from the device and to try again to build with `tns run ios` command by selecting the correct certificates for this device.

**Comment by premjg** [comment]
@tsonevn No luck unfortunately 😞 
(by deleting the platforms dir)

I'm going to turn off all observables and see if that works.

**Comment by premjg** [comment]
I can confirm that there are no `Observables` anywhere.

**Comment by tsonevn** [comment]
Hi @premjg,
Could you verify whether the device has been added to correct provisioning profile?
You could also open your project `<project_name>.xcworkspace` file from `<app_name>/platforms/ios` folder  with Xcode to uncheck `Automatically manage signing` to manually to select the `Team`. Then build again with XCode.
![image](https://cloud.githubusercontent.com/assets/17448734/24149960/02ec1c24-0e4d-11e7-8a27-ab63c613a07a.gif)
