### ISSUE TITLE
How to make an NS project multi-faceted (being able to build it for Apps and Web)

### ISSUE THREAD

**Issue by vbudilov** [NativeScript/NativeScript#3849]
Hello!

I'm trying to figure out the best way to build my Angular2 project into an NS app and a website. Have you looked at this? Do you have any best-practices that I can follow? This shouldn't be hard since I can create the view for each facet (app vs web), but I need to understand what else I need to worry about (the obvious is browser-specific libraries). 

Any help is appreciated!

Thanks,
Vladimir

**Comment by bradmartin** [comment]
Here is a great starting point https://github.com/NathanWalker/angular-seed-advanced @nathanwalker can provide more info on it. The forums and the nativescript slack channel have many devs actively using the seed project and can help answer questions also on sharing your code base.

**Comment by vbudilov** [comment]
Thanks, let me take a look.
