### ISSUE TITLE
Make "_nativeView" property public

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#385]
Often is the case when working directly with native APIs to need a reference to the native View, so lets make the ```nativeView``` property the official way to access this

**Comment by atanasovg** [comment]
The **public** means to access the native implementation are the `android` and `ios` properties respectively. They bring more context as the name hints which platform each property is valid for and when to use it. So, my vote goes for not changing the current implementation (if `_nativeView` is so desperately needed it is still accessible - this is JS after all).

**Comment by valentinstoychev** [comment]
Yes, but the ios and android properties are not officialy designed to return the native "view". In some cases they return other objects. This is the reason to ask for an officially supported way to get the native view. By making it officialy the way - we need eto document it and to rename it from ```_nativeView``` to ```nativeView```.

Makes sense?

And BTW I'm open for other suggestions what would be the best way to implement this, but it is a requirement in many cases when you are dealing with plugins and need to use/extend native UI APIs.

**Comment by atanasovg** [comment]
Let's see which are the cases - these are also designed on purpose. To use OS-specific APIs you know what the underlying android property returns. E.g. the Frame.android property. It is of type [AndroidFrame](http://docs.nativescript.org/ApiReference/ui/frame/AndroidFrame) and has all the frame-specific properties available for Android. What would the `nativeView` be here - is it the root `ViewGroup` or is it the `Activity`? Say you want to modify the viewgroup, you will have to write something like:

```
var androidFrame = frame.android;
androidFrame.viewGroup.<someMethod>;
```
This way we have the typed information as well - we know the exact type of the native widget - it is ViewGroup and we know which methods are available on it.

What is the actual scenario you hit that made you open this issue?

**Comment by valentinstoychev** [comment]
Hey @atanasovg, this solution was actualy proposed by @hshristov, As I said earlier - I need to know what is the official and recomended way of getting the native view. If this is it - I'm fine, but according to Ico this is not the case, so I guess you should discuss the technicalities.

As for the API I'm trying to implement - here it is - [https://developer.android.com/reference/android/support/design/widget/Snackbar.html#make(android.view.View, int, int)](https://developer.android.com/reference/android/support/design/widget/Snackbar.html#make(android.view.View, int, int))

```
public static Snackbar make (View view, int resId, int duration)
```

**Comment by hshristov** [comment]
We agreed that .android should be used.
