### ISSUE TITLE
Datepicker hide the year select option

### ISSUE THREAD

**Issue by giscafer** [NativeScript/NativeScript#3853]
Datepicker hide year select 

how to  hide the year option for the DatePicker?

**Comment by tsonevn** [comment]
Hi @giscafer,
The NativeScript DatePicker is a common abstraction over iOS `UIDatePicker` and Android's `android.widget.DatePicker`. Regarding that, there are some limitations that prevent us from styling the component and from hiding some of the components items (For example to hide the year).
This is something that does not depends on NativeScript and you could review the available DatePicker modes for [iOS ](https://developer.apple.com/reference/uikit/uidatepickermode) and [Android](https://developer.android.com/reference/android/widget/DatePicker.html#attr_android:datePickerMode).

In case you would like to change the mode for iOS, you could access the native property `datePickerMode` and to set up the new value.

For example:
XML
```
<GridLayout rows="" columns="">
        <DatePicker loaded="dploaded" day="12" month="12" year="2016"></DatePicker>
        
    </GridLayout>
```

TypeScript
```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import {DatePicker} from "ui/date-picker";
import {isIOS} from "platform"


export function dploaded(args){
    var datepicker:DatePicker = <DatePicker>args.object;
    if(isIOS){
        console.log("datepicker loaded");
        console.log(datepicker.ios);
// 0 -for time mode
// 1 -for date mode
// 2 -for dateAndTime mode
// 3 -for countDownTimer mode
        datepicker.ios.datePickerMode=2 
        console.log(datepicker.ios.datePickerMode);
    }
}
```
For Andorid there onl;y two options `calendar` and `spinner` modes.
To set one of them you should open `app/App_Resources/Android/values-v21/styles.xml` file and to change the default `datePickerMode` from `spinner` to `calendar`. For example 
```
<style name="SpinnerDatePicker" parent="android:Widget.Material.Light.DatePicker">
        <item name="android:datePickerMode">spinner</item>
    </style>
```
Bear in mind that this two options for Android has been available for Api level 21 or higher.

Hope this helps.

**Comment by giscafer** [comment]
@tsonevn thks a lot

**Comment by RoyiNamir** [comment]
@giscafer How did you do that in Android ?
