### ISSUE TITLE
ActionBar style doesn't work with classes only

### ISSUE THREAD

**Issue by Cayan** [NativeScript/NativeScript#3854]
### Which platform(s) does your issue occur on?
Detected on Android.

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.2
- Cross-platform modules: 2.5.2
- Runtime(s): android -> 2.5.0; ios -> 2.5.0
- Plugin(s): 
```
  "dependencies": {
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/router": "3.4.3",
    "@ngrx/core": "^1.2.0",
    "@ngrx/store": "^2.2.1",
    "email-validator": "1.0.4",
    "faker": "^3.1.0",
    "moment": "^2.17.1",
    "nativescript-angular": "1.4.0",
    "nativescript-angular-snapshot": "1.4.0-5.5.372.32-1",
    "nativescript-camera": "0.0.8",
    "nativescript-cardview": "^1.3.1",
    "nativescript-checkbox": "^1.2.6",
    "nativescript-fancyalert": "^1.1.2",
    "nativescript-geolocation": "0.0.17",
    "nativescript-image-cache-media": "^1.0.5",
    "nativescript-imagecropper": "0.0.7",
    "nativescript-imagepicker": "^2.4.1",
    "nativescript-loading-indicator": "^2.2.2",
    "nativescript-permissions": "^1.2.2",
    "nativescript-slides": "^2.2.8",
    "nativescript-socketio": "^2.2.9",
    "nativescript-vibrate": "^1.1.2",
    "redux": "^3.6.0",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.0.3",
    "tns-core-modules": "^2.5.1"
  },
  "devDependencies": {
    "babel-traverse": "6.21.0",
    "babel-types": "6.21.0",
    "babylon": "6.15.0",
    "filewalker": "0.1.2",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "0.0.6",
    "nativescript-dev-typescript": "^0.3.5",
    "tslint": "^4.3.1",
    "tslint-eslint-rules": "^3.2.3",
    "tslint-microsoft-contrib": "^4.0.0",
    "typescript": "2.2.0",
    "zone.js": "0.7.2"
  }
```

### Please tell us how to recreate the issue in as much detail as possible.
If you just add a class to an action bar, the style will not be applied. But once you style the ActionBar itself the classes start working.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```
ActionBar {
    color: #FFFFFF;
    background-color: #323232;
}

.action-bar-margin {
    padding-top: 30;
}
```

```
<ActionBar title="Test" class="action-bar-margin"></ActionBar>
```

**Comment by tsonevn** [comment]
Hi @Cayan, 
Thank you for contacting us.
I reviewed that case, however, was unable to reproduce the described scenario on my side.
For your convenience, I am attaching screenshots from the simulators. 
![screen shot 2017-03-23 at 9 40 58 am](https://cloud.githubusercontent.com/assets/17448734/24237119/aa0d64f2-0fad-11e7-99ae-01064cfd1ee2.png)
![screen shot 2017-03-23 at 9 42 28 am](https://cloud.githubusercontent.com/assets/17448734/24237120/aa0dc12c-0fad-11e7-86b1-a735133aed27.png)
I am also attaching a sample project. Could you make the needed changes, which will allow us to reproduce that issue?
[Archive.zip](https://github.com/NativeScript/NativeScript/files/863948/Archive.zip)
