### ISSUE TITLE
Change of color theme doesnt work 

### ISSUE THREAD

**Issue by montella1507** [NativeScript/NativeScript#3855]
http://docs.nativescript.org/angular/tutorial/ng-chapter-1

i Did exactly the same  what is mentioned in the tutorial, but the theme is not changed., I have installed node_modules correctly and there are CSS files.

Everytime when i want to START with NativeScript and give it a chance i got nervous in first step, when importing of CSS doesnt work :-(

**Comment by tsonevn** [comment]
Hi @montella1507,
Thank you for your interest in NativeScript.

I reviewed your case, however, was unable to reproduce any issues with changing the theme of the app.
Could you verify, whether you have attached the `action-bar` class to the ActionBar component, which is important for the `nativescript-theme-core plugin` to apply the needed style?

`<ActionBar title="My App" class="action-bar"></ActionBar>`

Let me know, whether this helps or if I could assist you further

**Comment by montella1507** [comment]
Im blind, thank you.
