### ISSUE TITLE
Android: updateTextTrigger="focusLost" when new string is empty

### ISSUE THREAD

**Issue by DickSmith** [NativeScript/NativeScript#3860]
On Android, `updateTextTrigger="focusLost"` does not function correctly when a field is updated to an empty string.

On iOS, it behaves as expected.

### Using the following Angular 2 Component:
```
import { Component, ElementRef, ViewChild } from '@angular/core';
import { TextField } from 'ui/text-field';

@Component({
               moduleId:    module.id,
               selector:    'app-textfield',
               template: `<StackLayout>
                            <TextField #textField
                                       hint="Field to check"
                                       updateTextTrigger="focusLost"></TextField>
                            <TextField hint="Refocus field"></TextField>
                            <Button text="Check"
                                    (tap)="checkValue()"></Button>
                            <Label text="value:({{ value }})"></Label>
                          </StackLayout>`
           })
export class LogInChoiceComponent {
    @ViewChild('textField') public elementRef: ElementRef;

    value: string;

    checkValue() {
       this.value = (this.elementRef.nativeElement as TextField).text;
    }

}
```

1. Enter any text in the first field
2. Refocus to the second field
3. Press "Check" button (*value:(...)* label updates correctly)
4. Clear text from first field
5. Refocus to second field
6. Press "Check" button

## Result:
*value:(...)* is same as first press

## Expected Result:
Label should be *value:()*. This is how it correctly behaves on iOS.

## Cause:
**tns-core-modules/ui/editable-text-base/editable-text-base.android.ts**
```
75: if (owner._dirtyTextAccumulator) {
76:     textProperty.nativeValueChange(owner, owner._dirtyTextAccumulator);
77:     owner._dirtyTextAccumulator = undefined;
78: }
```
This means that the condition evaluates to false if the string is empty and that the text value of the field is not updated on `focusLost`.

Instead it should be:
```
75: if (owner._dirtyTextAccumulator || owner._dirtyTextAccumulator === "") {
76:     textProperty.nativeValueChange(owner, owner._dirtyTextAccumulator);
77:     owner._dirtyTextAccumulator = undefined;
78: }
```

## Configuration
- CLI: 2.5.3
- Cross-platform modules: 2.5.2

**Comment by vakrilov** [comment]
Hey @DickSmith! Thanks for the PR. I have a small suggestion about it and we can merge it and resolve this issue.
