### ISSUE TITLE
How to make the TabView rendering at top of the page in IOS?

### ISSUE THREAD

**Issue by giscafer** [NativeScript/NativeScript#3862]
How to make the TabView rendering at **top** of the page in IOS?

**Comment by PetyaSotirova** [comment]
Hi @giscafer ,
As we want to keep the native behavior on both platforms, currently tabs are shown on top in Android apps and at the bottom in iOS apps and there's no way to change that. We've received several similar questions so I logged it a feature request for future consideration in https://github.com/NativeScript/NativeScript/issues/3871. 

Meanwhile, you could mimic the desired result by using [SegmentedBar](https://docs.nativescript.org/cookbook/ui/segmented-bar).

**Comment by snq** [comment]
With the latest version though, it is possible to position the tabs at the bottom on Android:

`androidTabsPosition="bottom"`

**Comment by IAMtheIAM** [comment]
What about setting iOS to `top`?
