### ISSUE TITLE
Curious space with ListView in a TabView in More section

### ISSUE THREAD

**Issue by adappter** [NativeScript/NativeScript#3865]
Hello,

I have currently a little problem and couldn't find any solutions.

I have a TabView with 8 items. In iOS you will have a "more" button to see the other items of a tabview.
I choose an item with listview inside, which are in "more". When the view is showing you will have a gap between the listview and actionbar. If I look at this listview when it's not in "more", everything is fine.

![img_2934](https://cloud.githubusercontent.com/assets/20188615/24291330/d011925a-1088-11e7-815a-0216abade683.PNG)

Maybe there is on with the same problem or have any solution.

tab-bar.html
```
<TabView #tabView>

    <StackLayout *tabItem="{title: 'Karte', iconSource: 'res://Map'}">
        <map></map>
    </StackLayout>

    <StackLayout *tabItem="{title: 'Route', iconSource: 'res://Route'}">
        <route></route>
    </StackLayout>

    <StackLayout *tabItem="{title: 'Hinzufügen', iconSource: 'res://Add'}">
        <Label text="Hinzufügen"></Label>
    </StackLayout>

    <StackLayout *tabItem="{title: 'Facebook', iconSource: 'res://Facebook'}">
        <Label text="Facebook"></Label>
    </StackLayout>

    <StackLayout *tabItem="{title: 'News', iconSource: 'res://News'}">
        <news></news>
    </StackLayout>

    <StackLayout *tabItem="{title: 'Forum', iconSource: 'res://Forum'}">
        <GridLayout>
            <WebView src="https://google.de"> </WebView>
        </GridLayout>
    </StackLayout>

    <StackLayout *tabItem="{title: 'Bußgeldrechner', iconSource: 'res://Calculator'}">
        <GridLayout>
            <WebView src="https://bussgeldrechner.expert/bussgeldbescheid-pruefen"> </WebView>
        </GridLayout>
    </StackLayout>

    <StackLayout *tabItem="{title: 'Einstellungen', iconSource: 'res://Settings'}">
        <Label text="Facebook"></Label>
    </StackLayout>

</TabView>
```

news.html
```
<GridLayout>
    <ListView [items]="newsArray" class="list-group" (itemTap)="onItemTap($event)">
        <template let-item="item">
            <StackLayout>
                <Label [text]="item.title" class="title small-spacing"></Label>
                <Label [text]="item.text" class="text small-spacing"></Label>
            </StackLayout>
        </template>
    </ListView>
</GridLayout>
```

**Comment by NickIliev** [comment]
@adappter thanks for posting this one - I can confirm that this issue is reproducible with the described settings. Test project to demonstrate the issue can be found [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_3865)
Reproducible only in iOS.

Steps to reproduce:
- open the application
- tap on "more" (tab-view items)
- tap on "news" (this is the tap with list-view)
- a blank space will be rendered on initial load within the ActionBar and the ListView. After some interaction with the list the space is removed.

**Comment by NickIliev** [comment]
Reproducible with tns-core-modules and nativescript-angular official and `next`

Updated test application demonstrating the issue can be found [here](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/NativeScript/issue-3865)

**Comment by tsonevn** [comment]
The issue is no longer reproducible with the latest official tns-core-modules `4.1.1` and `nativescript-angular` `6.0.6`.
