### ISSUE TITLE
How to keep different size images, in flexbox layout. All must be same size in flexbox layout

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#3866]
When i  was trying to insert different size images in flexbox layout .
It is showing in different sizes as shown in the image below
![flexboxlayout](https://cloud.githubusercontent.com/assets/10844041/24291583/9587e3ba-10af-11e7-8d18-8ed9ad43fb9e.PNG)

This is the code written 

	<FlexboxLayout class="p-5 firstRow m-y-10" alignContent="flex-start" height="115">
					<Image src="~/images_Test/lillys.jpg" class="chickenImg m-r-5"></Image>
					<FlexboxLayout flexDirection="column" style="width:60%;">
						<FlexboxLayout flexDirection="row" flexWrap="wrap" alignItems="flex-start">
							<Label text="Chicken  without skin " textWrap="true" class="subCategoryName"></Label>
							<Label text="250GRMS" textWrap="true" flexWrapBefore="true" class="chickenAmount"></Label>
							<Label text="&#xf156;" textWrap="true" class=" example rupeeIcon"></Label>
							<Label text="30 " textWrap="true" class="chickenAmount"></Label>
							<Label text="-" textWrap="true" flexWrapBefore="true" class="subtractIcon"></Label>
							<Label text="height :145" textWrap="true" class="ChickenQuantity"></Label>
							<Label text="+" textWrap="true" class="addIcon"></Label>
						</FlexboxLayout>
					</FlexboxLayout>
				</FlexboxLayout>

				<FlexboxLayout class="p-5 firstRow m-y-10" alignContent="flex-start" height="115">
					<Image src="~/images_Test/pink.jpg" style="height:90;" class="chickenImg m-r-5"></Image>

					<FlexboxLayout flexDirection="column" style="width:60%;">
						<FlexboxLayout flexDirection="row" flexWrap="wrap" alignItems="flex-start">
							<Label text="Chicken  without skin " textWrap="true" class="subCategoryName"></Label>
							<Label text="250GRMS" textWrap="true" flexWrapBefore="true" class="chickenAmount"></Label>
							<Label text="&#xf156;" textWrap="true" class=" example rupeeIcon"></Label>
							<Label text="30 " textWrap="true" class="chickenAmount"></Label>
							<Label text="-" textWrap="true" flexWrapBefore="true" class="subtractIcon"></Label>
							<Label text="height :145" textWrap="true" class="ChickenQuantity"></Label>
							<Label text="+" textWrap="true" class="addIcon"></Label>

						</FlexboxLayout>
					</FlexboxLayout>
				</FlexboxLayout>

				<FlexboxLayout class="p-5 firstRow m-y-10" alignContent="flex-start" height="115">
					<Image src="~/images_Test/rose.jpg" class="chickenImg m-r-5"></Image>

					<FlexboxLayout flexDirection="column" style="width:60%;">
						<FlexboxLayout flexDirection="row" flexWrap="wrap" alignItems="flex-start">
							<Label text="Chicken  without skin " textWrap="true" class="subCategoryName"></Label>
							<Label text="250GRMS" textWrap="true" flexWrapBefore="true" class="chickenAmount"></Label>
							<Label text="&#xf156;" textWrap="true" class=" example rupeeIcon"></Label>
							<Label text="30 " textWrap="true" class="chickenAmount"></Label>
							<Label text="-" textWrap="true" flexWrapBefore="true" class="subtractIcon"></Label>
							<Label text="height :145" textWrap="true" class="ChickenQuantity"></Label>
							<Label text="+" textWrap="true" class="addIcon"></Label>

						</FlexboxLayout>
					</FlexboxLayout>
				</FlexboxLayout>

The output of the code as shown in above image.

But I want all the images height and width must be same in flexbox layout, i want code for that flexbox layout

**Comment by PanayotCankov** [comment]
The images default stretch mode is aspect fit, try setting it to "aspectFill": `<Image stretch="aspectFill" src="..." />`

**Comment by dhanalakshmitawwa** [comment]
Thank you for the reply.
