### ISSUE TITLE
iOS: HttpContent.toFile() does not save if the file does not exist

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#3870]
With this code:
```ts
const response = await http.request({
    url: "https://raw.githubusercontent.com/NativeScript/NativeScript/master/apps/tests/logo.png",
    method: "GET",
});
const filePath = fs.path.join(fs.knownFolders.temp().path, "test", "logo.png");
const file = response.content.toFile(filePath);
console.log("FILE LENGTH: " + file.readSync().length);
```
The file length that gets logged is 0. 

While the following code:
```ts
const response = await http.request({
    url: "https://raw.githubusercontent.com/NativeScript/NativeScript/master/apps/tests/logo.png",
    method: "GET",
});
const file = fs.knownFolders.temp().getFolder("test1").getFile("logo.png");
response.content.toFile(file.path);
console.log("FILE LENGTH: " + file.readSync().length);
```
Works ok and the file length is non-zero. 

I would expect when the file does not exists the method to automatically create the file and write the contents to the file.

**Comment by gezn** [comment]
I was looking to work on this, but I couldn't find the guide for contributing, the web page points to https://github.com/NativeScript/NativeScript/blob/master/.github/CONTRIBUTING.md
that is an 404 link

**Comment by gezn** [comment]
@radeva  I have a question, should this be implemented on Android also. or is restricted to be implemented on ios platform

**Comment by radeva** [comment]
Hi @gezn , I see you already did a PR, so I suppose your questions are not relevant anymore. The team will review the PR and get back if there are any comments.

**Comment by NickIliev** [comment]
Resolved via https://github.com/NativeScript/NativeScript/pull/6451
