### ISSUE TITLE
Can't load a local HTML file with querystring via WebView.src (WebView.url works but is removed)

### ISSUE THREAD

**Issue by EddyVerbruggen** [NativeScript/NativeScript#3872]
As noted [here](https://github.com/NativeScript/NativeScript/pull/3843#issuecomment-289091626) I'd like to request to not remove the `WebView.url` property as it's the only way to currently load a local HTML file with query parameters.

Passing `~/file.html` to `WebView.src` works, but `~/file.html?foo=bar` loads a blank page because it can't find the local file. `WebView.url` works perfectly for that case.

`WebView.src` can be altered to make it load the file successfully, but still I see no way in the current implementation to pass querystring params to the file. I really need a way to access those params in the loaded HTML file.

**Comment by NickIliev** [comment]
Related to [this fix](https://github.com/NativeScript/NativeScript/pull/3843#issuecomment-289091626).
Should we provide a way to pass query params via **src** or roll-back the **url**  property?

Ping @vakrilov , @hshristov ^^^

**Comment by speigg** [comment]
IMO, I think we should keep both properties:

`src` should be the url that was explicitly set on the webview (and triggers a load)
`url` should be only a getter that always provides the current url (automatically updated on redirects, navigation, etc)
