### ISSUE TITLE
ListView - itemTap event not being called on inserted items

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/NativeScript#3873]
Have a list-view that's driven by an ObservableArray - and I initialize with a few items. I'm using ListView.itemTemplates.

On the itemTap event, I insert some more items (in the middle and of a different template type than above) and displays fine on the screen.

But when I tap on these newly inserted items, the itemTap event is not being called.

More info. My definition is similar to below

`<ListView.itemTemplates>
  <template key="A">
  </template>
  <template key="B">
  </template>
</ListView.itemTemplates>
`
I've got a list of A and insert B. Taps on B are not being registered.

If I have a list of A and insert A - taps are registered.

Latest NS + core and on Android.

More info
----
If there's a Button element in template B - then taps on the item itself is not registered.

**Comment by NickIliev** [comment]
Hey, @erjdriver I am guessing here as I don't have your actual implementation to work with but perhaps how are you adding new items to your ObservableArray is the key to your issue?

[Here ](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_3873)you can find a very basic application which I've used to test the changing of items when using itemTemplates and it works as expected on my side.

**Comment by erjdriver** [comment]
I think you missed the last line of my updated post.

If the inserted item contains a Button element - the tap doesn't work.

My project is {N} w/o Angular but I think it might apply to w/ Angular also.

Thanks.

**Comment by NickIliev** [comment]
@erjdriver I see your point now.

I can suggest an easy workaround - just wrap the template where the buttons are inserted in parent layout and create a tap event for the parent layout. This hack will allow you to work with multiple nested tap events but now you will have to manually take care of things like tapped item index

e.g.
```
<template key="red">
     <StackLayout orientation="horizontal" tap="onStackTap">
           <Label text="{{ $value }}" textWrap="true" style.backgroundColor="red"/>
           <Button text="tap me" tap="onButtonTap" />
     </StackLayout>
</template>
```

```
export function onStackTap(args: EventData) {
    console.log("onStackTap fired");

    var stack = <StackLayout>args.object;
    var listview = <ListView>stack.parent;

    console.log(stack)
    console.log(stack.bindingContext)
} 

```

Now **_onStackTap_** will work as a tap triggered for the whole cell and **_onButtonTap_** will be triggered only when the user taps the button.

Updated test project [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_3873)

**Comment by erjdriver** [comment]
Thank you - that works.

But I do think it's a bug and should be fixed. This solution might break in 3.0.

Let me know if you want me to mark this closed or not.

Thanks again.

p.s. for others, if trying to get the item-index, I did:

this._listItemArray.indexOf(stack.bindingContext)

where _listItemArray is the ObservableArray data-model behind the ListView.

**Comment by NickIliev** [comment]
Hey, @erjdriver this can not be handled by NativeScript as it is a common scenario in Android. (e.g. [here](http://stackoverflow.com/questions/6275183/android-listview-with-buttons-onitemclick-do-nothing))

For example in Android when an AdapterView contains clickable views such as buttons, the listener registered to the clickable view will take over the click event disallowing onItemClick on AdapterView to fire. So this is the reason the same happens in NativeScript (for Android) - we are reusing the native behavior.

**Comment by erjdriver** [comment]
No worries.

The solution you provided works.

Also as for the ripple effect - i was able to give a visual feedback to the user by - adding the following code to the onItemTap callback.

savedColor = args.view.style.backgroundColor;

args.view.style.backgroundColor = "red";    // pseudo-code

setTimeout( function()
{
  args.view.style.backgroundColor = savedColor;
}, 400 );

Not ripple, but gives a good visual feedback.

**Comment by freddiandrew** [comment]
@NickIliev  
```
export function onStackTap(args: EventData) {
    console.log("onStackTap fired");

    var stack = <StackLayout>args.object;
    var listview = <ListView>stack.parent;

    console.log(stack)
    console.log(stack.bindingContext)
} 

```
how to do it in {N} angular ways? please guide,
thank you

**Comment by NickIliev** [comment]
@freddiandrew in Angular you context is per component and the main approach is to use DI and services. [Here is the article] an(https://docs.nativescript.org/core-concepts/data-binding) about data binding syntax in NativeScript + Angular.  For a better understanding of the Angular application structure, I would suggest giving a try to the application tutorial in [the Playground] (https://play.nativescript.org/) (Gettings Started >> Build a Full App)

Overall instaed of searching for `bindingContext` of specific layout/page,. you would be working with the Angular Component which can expose public/private properties and methods and receive data via dependency injection of services.

**Comment by freddiandrew** [comment]
```
<ListView #list class="list-group" [items]="_products" (itemTap)="onNavigationItemTap($event)" >
            <ng-template let-item="item">
                <GridLayout columns="80,*,90" class="list-group-item">
                    <Image col="0" [src]="item.thumb" class="imglist" (tap)="goDetail(item.id)" ></Image>
                    <StackLayout col="1" class="proddesc">
                        <Label [text]="item.name" class="prod-title"></Label>
                        <Label [text]="item.description"></Label>
                    </StackLayout>
                    <StackLayout col="2">
                        <Button android:focusable="false" class="btn btn-primary btn-rounded-lg" (tap)="buy(item.id)" 
                         text="GET" loaded="btnLoaded($event)"></Button>
                        <Label text="T-Mart purcase" class="footnote"></Label>
                    </StackLayout>
                </GridLayout>
            </ng-template>
        </ListView>
```
i try to use itemTap but not fired,
if i use tap  got fired but args.index will undefined

any solution for this in {N} angular? 
thank you
