### ISSUE TITLE
Error: more than one library with package name 'com.telerik.android.data'

### ISSUE THREAD

**Issue by ryanzaatari** [NativeScript/NativeScript#3875]
## What went wrong:
Execution failed for task ':processF0F1F2DebugResources'.
> Error: more than one library with package name 'com.telerik.android.data'
Command /Users/ryanzaatari/Documents/Development/NativeScript/nativescript/MFTime/platforms/android/gradlew failed with exit code 1
I'm using both nativescript-ui, free and pro in this project. someone ([here](https://github.com/NativeScript/nativescript-imagepicker/issues/68)) mentioned that after removing the pro module the project worked on Android, but I don't want to do that. (didn't test it either)
[tns_build_android_traceLog.txt](https://github.com/NativeScript/NativeScript/files/870680/tns_build_android_traceLog.txt)
OS: Mac OS Sierra
### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.2
- Cross-platform modules: 2.3.0
- Runtime(s): 2.5.0
- package.json: `{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.MFTime",
    "tns-ios": {
      "version": "2.5.0"
    },
    "tns-android": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "nativescript-intl": "0.0.10",
    "nativescript-sqlite": "^1.1.2",
    "nativescript-statusbar": "^1.0.0",
    "nativescript-telerik-ui": "1.4.1",
    "nativescript-telerik-ui-pro": "file:///Users/ryanzaatari/Documents/Development/NativeScript/nativescript-ui-pro.tgz",
    "nativescript-theme-core": "^1.0.3",
    "tns-core-modules": "2.3.0"
  },
  "devDependencies": {
    "babel-traverse": "6.23.1",
    "babel-types": "6.23.0",
    "babylon": "6.16.1",
    "lazy": "1.0.11"
  }
}
`

**Comment by ryanzaatari** [comment]
Following part of what's mention [here](https://github.com/NativeScript/nativescript-imagepicker/issues/50) solved my issue.

- I deleted the `nativescript-telerik-ui` folder in `node_modules`

- Removed ios and android platforms `tns platform remove [platform]`

- Added ios and android platforms `tns platform add [platform]`

- In my xml views, i replaced `nativescript-telerik-ui` with `nativescript-telerik-ui-pro`

- Built both platforms using `tns build [platform]`

**Comment by Pip3r4o** [comment]
@ryanzaatari make sure you remove the `nativescript-telerik-ui` package from your dependencies as well. The next time you do `npm install` you will be faced with the same issue.

`npm remove nativescript-telerik-ui --save`

**Comment by ryanzaatari** [comment]
Thank you @Pip3r4o, I did forget to do that.
