### ISSUE TITLE
iOS App installing Error

### ISSUE THREAD

**Issue by pap5508** [NativeScript/NativeScript#3876]
Package.json
` "tns-ios": {
      "version": "3.0.0-2017-3-14-1"
    }`

`Installing...
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Multiple errors were thrown:
Error Command failed: xcrun simctl install 25AE79E9-26AF-4A22-B744-6490423422BA /Users/admin/Documents/Development Begis/Hieber/platforms/ios/build/emulator/Hieber.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.`

**Comment by NickIliev** [comment]
@pap5508 can you provide more information on how you are reproducing this error.
(full package.json and also the commands used to run your application)

I was not able to reproduce this behavior:
- `tns create myApp --tsc`
- `rm -rf platforms`
- `rm -rf node_modules`
- `tns platform add ios@next`

Following the above steps, I was able to successfully create and execute my project.

**Comment by pap5508** [comment]
@NickIliev : thats works..!!
Thank you..!!
