### ISSUE TITLE
[Android] App back to splash screen when the camera returns

### ISSUE THREAD

**Issue by dzfweb** [NativeScript/NativeScript#3879]
I have an app with nativescript + angular that closes when i call camera's api, returning to splash screen.. I think it's because of the low memory of the dispositive, because only occur on old devices. Is there a way to force the app still open on first stage, even when opening other app (in my case, camera) ?

**Comment by tsonevn** [comment]
Hi @dzfweb, 
I tested your case while using [CameraTestAngular](https://github.com/NativeScript/nativescript-camera/tree/master/examples/CameraTestAngular) plugin, however, was unable to reproduce the same behavior.
Regarding that could you provide some further info, about the device or emulator API Level? Could you also provide some sample project, which could be debugged locally?

**Comment by dzfweb** [comment]
For reproduce the scenario, i used android 4.4.4, open some android apps on the dispositive, and then back to the app and open the camera. When the camera returns, in some case android close the app and it will open again from the begin (splash screen).

is there a way to use the camera without close the app, to evict it scenario, or other solution?

**Comment by tsonevn** [comment]
Hi @dzfweb,
I tested this case on a device with Android 4.4.4, however, was unable to reproduce this behavior on my side. I am using [CameraTest](https://github.com/NativeScript/nativescript-camera/tree/master/examples/CameraTest) app for testing.
You could review the steps that I follow:
1. deploy `CameraTest` app on the device with `tns run android`.
2. open another android app on the device.
3, return back to the NativeSciprt app and open the camera by tapping on `Take Picture` button.
4. take a new picture and we will be returned to the app, without restarting the whole application.

It would help if you could provide sample project and steps, which could help us to debug this scenario.

**Comment by dzfweb** [comment]
I understand you, the fact only occurs on Samsung J1, and is not ever, just sometimes.
I have it problem in other project developed in Xamarin, and i solved by reducing the quality of the camera photo, and it sizes, but i 'm not getting in NativeScript 'cause other bug (https://github.com/NativeScript/nativescript-camera/issues/35)

**Comment by tsonevn** [comment]
Hi @dzfweb,
Let's move this issue in the `nativescript-camera` repository and keep the discussion there. 
Regarding the issue [#35](https://github.com/NativeScript/nativescript-camera/issues/35). The reported problem seems to affect only the save option on some Android device. You should be able to change the sizes of the image(width and height).

Could you try to setup image size in takePicture method and to verify, whether this resolve the issue with app restart. For Example:
`takePicture({width: 100, height: 100, keepAspectRatio: false, saveToGallery: saveToGallery})`

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-camera#36
