### ISSUE TITLE
Camera still saving image to gallery even when setted to dont save

### ISSUE THREAD

**Issue by dzfweb** [NativeScript/NativeScript#3883]
Apparently CameraOptions is not working correctly.
Camera still saving image to gallery even when setted to dont save. 
The width and height is not working as configured too.

My code:
```
takePhoto(args) {
        let options = { width: 300, height: 300, keepAspectRatio: false, saveToGallery: false };
        let imageView = args.object.page.getViewById('image');
        camera.takePicture(options).
        then((imageAsset ) => {
            let source = new ImageSourceModule.ImageSource();
            source.fromAsset(imageAsset).then((source) => {
                console.log(`Size: ${source.width}x${source.height}`);
            });
            this.checkout.photo = source.toBase64String('png');
            imageView.src = imageAsset;
        }).catch((err) => {
            console.log('Error -> ' + err.message);
        });
    }
```

**Comment by tsonevn** [comment]
This could be related to issue [#25](https://github.com/NativeScript/nativescript-camera/issues/25) and the fact that you should request permissions for the phone gallery.

You could try to call `nativescript-camera` plugin `requestPermissions();` method before taking a picture, which will set up the needed permissions and will allow cameraOptions to be changed.

Hope this helps.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-camera#35
