### ISSUE TITLE
Creating a Button with no border or shadow

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/NativeScript#3884]
I've got a NS app (w/o Angular) and trying to create a Button with no border or shadow - basically transparent.

I created a project `tns create myApp --template tsc` and then modified the "tap" button with css class definitions of 

"btn btn-active"
"btn btn-primary btn-active"
"" (no class)

But can't get the border and shadow to disappear.

This is using the latest NS software + Android + Android emulator (dev on Windows 10).

**Comment by tsonevn** [comment]
Hi @erjdriver,
To remove the shadow of the button on Android you should set some `borderWidth` and to setup `borderColor` to `transparent` for  the component as it has been shown in the example below:

XML
```
<StackLayout class="p-20">
        <Label text="Tap the button" class="h1 text-center"/>
        <Button text="TAP" tap="{{ onTap }}" class="btn btn-active"/>
        <Label text="{{ message }}" class="h2 text-center" textWrap="true"/>
    </StackLayout>
```
CSS
```
.btn{
    border-color: transparent;
    border-width: 1;
}
```

**Comment by erjdriver** [comment]
Genius!

case closed.

**Comment by Jaishankarb** [comment]
Still, the native touch effect gets lost on android

**Comment by proximilis** [comment]
.btn:active {
background-color: [your-color] ;
}
something like that ?

**Comment by surdu** [comment]
@tsonevn Without `border-width: 1;` it doesn't work... That makes no sense ...
