### ISSUE TITLE
error TS2339: Property 'type' does not exist on type 'Object'.

### ISSUE THREAD

**Issue by himanshu331** [NativeScript/NativeScript#3886]
```
serviceArray: Array<Object> = [];
var offerValue = {
                "id": this.offerData.id,
                "type": true
}
this.serviceArray.push(offerValue);

this.serviceArray[index].type
```
I dont know what its means. My app is running but getting errors while running time. Any idea??

**Comment by NickIliev** [comment]
You should either create your offerValue TS class or use the JavaScript syntax to access your property e.g.
```
this.serviceArray[index]["type"]
```

More details on this TypeScript related issue can be found [here](http://stackoverflow.com/questions/38324949/error-ts2339-property-x-does-not-exist-on-type-y)
