### ISSUE TITLE
Memory leak when dealing with images. iOS

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/NativeScript#3887]
I display two images on the page. When either is tapped, two new images are loaded. I've tried binding the `src` properties to an observable and updating this. I've also tried removing the `Image` elements and entirely replacing them. Both of these lead to high memory usage and crashes. It looks like the old images are never removed from memory.

Here is part of the code using binding. Memory usage jumps by ~30mb each time these images are loaded - even though the images themselves are only 87kb. 

```
function loadQuestionImages(question) {
    // ## Load both images before binding to ensure
    // ## both display at same time.

    var loadedImages = 0;
    var imageSRC_1;
    var imageSRC_2;

    imageSourceModule.fromUrl('https://placehold.it/2000x2000')
        .then(function (res) {
            loadedImages = loadedImages + 1;
            imageSRC_1 = res;

            if (loadedImages == 2) {
                imagesLoaded();
            }
        }, function (error) {
            //console.log("Error loading image: " + error);
        });

    imageSourceModule.fromUrl('https://placehold.it/2000x2000')
        .then(function (res) {
            loadedImages = loadedImages + 1;
            imageSRC_2 = res;

            if (loadedImages == 2) {
                imagesLoaded();
            }
        }, function (error) {
            //console.log("Error loading image: " + error);
        });

    function imagesLoaded() {
        pageData.set('imageSRC_1', imageSRC_1);
        pageData.set('imageSRC_2', imageSRC_2);

        animateInImages();
    }
}
```

There is also a project here that replaces the image elements https://github.com/3rror404/ImageMemoryTest. This performs exactly the same as the code above.

Am I doing something wrong here? 

Thanks

**Comment by NickIliev** [comment]
Hey @3rror404 thank you for reporting this one - indeed the memory consumption is rising and sometimes the app is crashing or freezing due to out of memory before the cache is cleared. We will look into this. Meanwhile, you can use [nativescript-web-image-cache ](https://www.npmjs.com/package/nativescript-web-image-cache)to load your online images.
With this plugin the memory consumption is normal but if needed you can force clean the cache as well.

e.g. (based on your test application)
**_main-page.js_**
```
var imageCacheModule = require("nativescript-web-image-cache");


function loadQuestionImages() {
    var imageSRC_1 = 'https://placehold.it/2000x2000';
    var imageSRC_2 = 'https://placehold.it/2000x2000';

    imagesLoaded();

    function imagesLoaded() {
        var image1_orig = page.getViewById('question-1-image');
        var image2_orig = page.getViewById('question-2-image');

        image1_orig.src = imageSRC_1;
        image2_orig.src = imageSRC_2;

        animateInImages();
    }
}
```
**_main-page.xml_**
```
 <Page loaded="onLoaded" navigatedTo="onNavigatedTo" actionBarHidden="true" xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:IC="nativescript-web-image-cache">
    <GridLayout id="questions-wrap" row="0" rows="50*, 50*">     
        <GridLayout id="image1_wrap" class="question" tap="tapQuestion" row="0" rows="*" columns="*">
            <IC:WebImage id="question-1-image" stretch="aspectFill" ></IC:WebImage> 
        </GridLayout>
        <GridLayout id="image2_wrap" class="question" tap="tapQuestion" row="1" rows="*" columns="*">
            <IC:WebImage id="question-2-image" stretch="aspectFill" ></IC:WebImage> 
        </GridLayout>
    </GridLayout>
</Page>
```

App to reproduce this issue [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_3887/ImageMemoryTest)

Steps to reproduce:
- start the application for iOS
- start **Instruments** and track the memory usage for `ImageMemoryTest` app
- tap on the image (this will load new iage from provided URL) - result the cache will not be cleaned which will lead to Out of Memory. Using nativescript-web-image-cache will resolve this issue)

**Comment by 3rror404** [comment]
Thanks @NickIliev,

I've just tested on Android and the same memory issue exists.

Using the image-cache plugin does seem to work but I can't now use the technique above to ensure both images are loaded before displaying. I don't suppose you have any ideas about this issue I've just opened? https://github.com/VideoSpike/nativescript-web-image-cache/issues/24

**Comment by NickIliev** [comment]
@3rror404 for your scenario you can use <Image> and manually trigger the garbage collector before loading the new images.
Here is how to do it in iOS:
```
function loadQuestionImages(question) {
      if (app.ios) {
           global.__collect(); 
      }

      // the loading of the new images follows here
}
```

You can also trigger GC for Android - look here for [more details](https://github.com/NativeScript/NativeScript/issues/3901#issuecomment-290433850)

**Comment by 3rror404** [comment]
That works great. Thanks for the help.

**Comment by NickIliev** [comment]
@3rror404 use this only as a last resort and where needed as it might lead to side effects (mainly with page transitions) and is not the recommended way to handle memory usage in iOS app (that is the reason the method is private). Meanwhile, we will investigate the reasons for this and post additional info here.

**Comment by 3rror404** [comment]
Ok cool.

The idea of this app is for the user to choose an image quickly so I'm switching images a lot. Maybe  30-40 times in 10-20 seconds or less dependant on network speed.
Could triggering the GC in rapid succession cause any problems? 
Would it be better to trigger the GC every few image changes rather than every time? 
What side effects might this cause?

**Comment by NickIliev** [comment]
One of the thing that might happen is to clear reference to objects that are still needed (for example object needed for navigation). .I can not answer your question directly - it is best to test the scenario when you are using the GC and then navigation to another page and back - and if there is no low performance in the page transitions then you should be ok.

**Comment by tsonevn** [comment]
Hi @3rror404,
We tested the provided project in your [very first comment](https://github.com/NativeScript/NativeScript/issues/3887#issue-217526824), and we are not able to recreate this issue while using latest tns-core-modules and tns-ios (3.4.1).
If you still facing the issue, please provide steps for reproducing, and I will reopen the issue.
