### ISSUE TITLE
Add dynamic Widget/Component creation

### ISSUE THREAD

**Issue by patrickseda** [NativeScript/NativeScript#389]
### What’s the problem?
The current UI definition paradigm requires us to know exactly which UI elements are needed before a `Page` creation. This is often ***not*** the case for larger apps. Although data binding handles dynamic UI updating nicely for tabular data and other small items, it is not the right solution for large dynamically generated UI compositions.

### What do we have now?
The existing capabilities of {N} ***do*** allow for us to specify isolated groupings of UI components (*or widgets*) referenced into the XML of the parent `Page`.
```
// Define our Widget in file "xml-declaration/widget1".
<StackLayout id="stackLayout" >
    <Label id="label1" text="Label1" />
    <Button id="button1" text="Button1" /> 
</StackLayout>
```
```
// Embed our custom Widget into our Page.
<Page xmlns:widgets="xml-declaration/widget1">
     <widgets:Widget1 />
</Page>
```

### What do we need?
We need a dynamic widget builder, providing full control over ***when*** a custom widget gets created.

Ideally we’d expect its usage and API to be simple, perhaps something like:
*(using the widget XML declared above)*
```
var widget1 = viewBuilder.build({ name: ‘xml-declaration/widget1’ });
someView.addChild(widget1);
```

Currently we ***do*** have the ability to dynamically create `Page` views/controllers from an XML file.
This is done via the `Frame` class using the static method `resolvePageFromEntry()`:
```
var widget1 = frameCommon.resolvePageFromEntry({ moduleName: 'xml-declaration/widget1' });
someView.addChild(widget1);
```
where the XML would be declared something like:
```
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded" >
    <StackLayout id="stackLayout" >
        <Label id="label1" text="Label1" />
        <Button id="button1" text="Button1" /> 
    </StackLayout>
</Page>
```
Note that the widget must be wrapped in a `Page` element or this will ***not work***!
But making every widget a `Page` would incur excessive overhead, and quite frankly you could create some nonsensical compositions, like a `Page` with a `StackedLayout` parent.

This is not the right solution.

### Technical considerations
The main *benefit* of having a `Page` as our root in a widget is contains the internal method `addCssFile()` which applies styling during the `resolvePageFromEntry()` call, where the css file name is dynamically determined from the target module name.

The main *drawback* of having a `Page` root is that it knows about app Navigation, which a small widget absolutely should ***not***. This abstraction is wrong for our widgets.

Currently the visible UI elements have different direct parent classes: `TextBase`, `Layout`, `ContentView`, and `View`. So introducing a generic builder which handles the automatic styling (like the `Page` does now) would mean they would all have to have a common base having the `addCssFile()` styling capability. Perhaps this could be retrofitted up into the shared-common base class `View`? Or perhaps some other class abstraction in between would be more correct.

Then using the same builder call proposed before, we would be handed the correct (and stylized) widget, regardless of the outer container type specified in the XML:
```
var widget1 = viewBuilder.build({ name: ‘xml-declaration/widget1’ });
someView.addChild(widget1);
```

**Comment by enchev** [comment]
I've just extended UI builder with [new load method](https://github.com/NativeScript/NativeScript/blob/custom-component-load/ui/builder/builder.d.ts#L6) and now you can do the following:

##### Load pure JavaScript component (*require() the specified path and look for specified component name in the require() exports*):
```JavaScript
var myComponentInstance = builder.load({
        path: "~/xml-declaration/mymodule",
        name: "MyControl"
});
```
or
##### Load XML file with JavaScript code-behind (*Load the specified XML file name in the  specified path. JavaScript file with the same name will be required() and served as code-behind of the XML.*):
```JavaScript
var myComponentInstance = builder.load({
        path: "~/xml-declaration/mymodulewithxml",
        name: "MyControl"
});
```
What do you think? Will this work for you?

We need a bit more extra research about CSS support for dynamically loaded components. Stay tuned!

**Comment by patrickseda** [comment]
Very awesome, thanks!
The XML version will be immeasurably useful
