### ISSUE TITLE
Image view not loading images

### ISSUE THREAD

**Issue by praven07** [NativeScript/NativeScript#3890]
I tried to use the image view and It would not load some images over http.

This one works
`<Image  src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_120x44dp.png"></Image>`

But this one does not work.
`<Image src="http://civilizedcavemancooking.com/wp-content/uploads/2015/01/Paleo-Chicken-Soup.jpg"></Image>`

**Comment by tsonevn** [comment]
Hi @praven07, 
Can you provide more info about the platform, where you have this issue?
Regard that by default iOS is not allowing requests via HTTP but only via HTTPS. To allow this option you could add `NSAllowsArbitraryLoads` key to `true` in your `Info.plist` file.
```
<key>NSAppTransportSecurity</key>
<dict>
  <!--Include to allow all connections (DANGER)-->
  <key>NSAllowsArbitraryLoads</key>
      <true/>
</dict>
```

**Comment by NickIliev** [comment]
@praven07 sample project demonstrating the load of the exact same image can be found [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_3890) (along with the solution provided by @tsonevn for NSAllowsArbitaryLoads in info.plist file)

**Comment by praven07** [comment]
Thanks! I got it working!
