### ISSUE TITLE
Scroll to anchor point

### ISSUE THREAD

**Issue by lukeramsden** [NativeScript/NativeScript#3895]
Is it possible to scroll to an anchor point in a scroll view?
Like on the web?

**Comment by EddyVerbruggen** [comment]
You can scroll to an index (row number). But this is better asked at the forum / SO.

**Comment by lukeramsden** [comment]
@EddyVerbruggen how do I find a row number though? Currently, I have a StackLayout inside a ScrollView, so how do I find where to scroll through? Also, will ask questions on the forum in future, thanks for the advice.

**Comment by EddyVerbruggen** [comment]
@lukeramsden Depends a bit on your usecase. I'll give an example for NativeScript with Angular.

Suppose you have this listView: `<ListView #myListView [items]="listItems"` and want to scoll to the an item at a specific index, then do this in your component:

```js
@ViewChild("myListView") myListView: ElementRef;

scrollToIndex(index: number): void {
  let myListViewElement = <ListView>this.myListView.nativeElement;
  myListViewElement.scrollToIndex(index);
}
```

A more real world example would be matching against some value of an item in the list and scroll that item into view:

```js
scrollToItem(theValueImLookingFor: any): void {
  let myListViewElement = <ListView>this.myListView.nativeElement;
  this.listItems.forEach((item: Item, index: number) => {
    if (item.someValue === theValueImLookingFor) {
      myListViewElement.scrollToIndex(index);
      return;
    }
  }
}
```

**Comment by NickIliev** [comment]
@lukeramsden you can also use [scrollToVerticalOffset ](http://docs.nativescript.org/api-reference/classes/_ui_scroll_view_.scrollview.html#scrolltoverticaloffset)and [scrollToHorizontalOffset ](http://docs.nativescript.org/api-reference/classes/_ui_scroll_view_.scrollview.html#scrolltohorizontaloffset)but you will need to know the value needed to scroll.

Example sis given [here](https://github.com/NativeScript/nativescript-angular/issues/623#issuecomment-271511626)
