### ISSUE TITLE
iOS http-request header User-Agent always reports iOS 6

### ISSUE THREAD

**Issue by EddyVerbruggen** [NativeScript/NativeScript#3898]
Hi,

I was looking at Analytics reports today and found that all my users have iOS 6 installed. Even if that's not a supported version of my app 🤔 😁

Turns out the header is hardcoded [here](https://github.com/NativeScript/NativeScript/blob/29e07dd027aff343d64138290c1825769846f6d5/tns-core-modules/http/http-request/http-request.ios.ts#L24).

I'd like to send a PR to change this to a dynamic string, based on the actual version the user's device is running.

**Comment by vchimev** [comment]
Thanks a lot, @EddyVerbruggen!
