### ISSUE TITLE
Runtime error when using require("net"); Mac OS/xcode

### ISSUE THREAD

**Issue by n0n0n0** [NativeScript/NativeScript#39]
When I try use node module "net" in main-page.js like this
`var net = require("net");`
I get runtime error. As I wrote in issues here I still cant run app with `tns run ios --emulator` but i can run it in xcode from xcodeproject file in `platforms/ios`. So I see this error only in debug mode in xcode (while app in emulator show me start screen with "NativeScreen" icon). In xcode debug screen with assembler-like view i see this:
`Thread 1: EXC_BAD_ACCESS (code=1, address=0xbbadveef)`
When I delete statement 'var net = require("net");` app works fine.
So whats wrong here?

**Comment by fealebenpae** [comment]
Hi @n0n0n0,

Is there any chance the `require("net")` call is before `require("application")`?

**Comment by fealebenpae** [comment]
Hi @n0n0n0,

NativeScript doesn't ship a `net` module. Is it perhaps one you've added yourself? The output in the Xcode debugger window should hold more details to what the actual cause of the error is, please check that and paste it here so we can take a look.

**Comment by n0n0n0** [comment]
As I said statement `require("net")` palced in main-page.js from standart demo app (by tns create <app>) so i think it called after `require("application")`

I thought `net` module is built-in in node? If NS not supported it how i can make tcp connect to some host and port?

**Comment by n0n0n0** [comment]
I just found error in Xcode (i have old small monitor on mac). Here it is
`undefined:76:153: JS ERROR Error: Failed to find module 'net' relative to '/app/main-page.js'.`

**Comment by n0n0n0** [comment]
I have tried `npm install net` and `npm install -g net` but still dosent work, so I would convert my first question to "does NS support standart node.js modules (that install by `npm install module`?"

**Comment by fealebenpae** [comment]
`net` is a built-in module in Node.js. NativeScript has its own set of [built-in modules](https://github.com/NativeScript/cross-platform-modules). We would like to eventually be fully node-compatible, as mentioned by @ligaz [here](https://github.com/NativeScript/NativeScript/issues/35), but we're not there yet.

Even though there isn't a cross-platform socket API right now, you can use native APIs such as [CFStream](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/NetworkingTopics/Articles/UsingSocketsandSocketStreams.html) on iOS or [Socket](http://developer.android.com/reference/java/net/Socket.html) on Android in your JavaScript code.

**Comment by n0n0n0** [comment]
Ok, thank you @fealebenpae.
