### ISSUE TITLE
Document: Please add articles and simple examples about  multi-thread execution Model and cross-bridge callback mechanism

### ISSUE THREAD

**Issue by yytony** [NativeScript/NativeScript#390]
HI, I am a newbie for nativescript , and just looking for and evaluating some cross-platform mobile development solutions that is not base on web  engine , like titanium, nativescript ,react native ...etc but not cordova like .   Please add articles( or information) and simple examples about  multi-thread execution model and about cross-bridge reverse callback mechanism (actively calling from androi/ios to javascript). It is important to develop  fine quality applications. Thanks !

**Comment by yytony** [comment]
I have searched some web pages by google, and they indicated that V8 engine is not thread safe. So, When I fork a new thread by calling android thread class api from Nativescript, is it safe ?

**Comment by enchev** [comment]
Hi @yytony,

Please check our docs on how both runtimes for iOS and Android works:
http://docs.nativescript.org/runtimes/android/overview
http://docs.nativescript.org/runtimes/ios/Overview

You can ask also any question on our google group:
https://groups.google.com/forum/#!forum/nativescript

Thanks
