### ISSUE TITLE
Cannot run app created with NativeScript 3.0 RC

### ISSUE THREAD

**Issue by julitogtu** [NativeScript/NativeScript#3903]
Hi, today I updated NativeScript to version 3.0 RC to try the it, I already created a new application in my windows laptop and add support for android according to the post https://www.nativescript.org/blog/nativescript-3.0-release-candidate-available-today, but I cannot run my app, when I run `tns run android` I get the following error (I ever use genymotion):

> Command failed: C:\Program Files (x86)\Android\android-sdk\platform-tools\adb devices
> error: could not install *smartsocket* listener: cannot bind to 127.0.0.1:5037: Only one usage of each socket address (protocol/network address/port) is normally permitted. (10048)
> could not read ok from ADB Server
> * failed to start daemon *
> error: cannot connect to daemon_

I'm running cmder with admin.

Also, if a run `tns devices` nativescript cannot find my emulator:

> 
> Connected devices & emulators
> Searching for devices...
> Cannot find connected devices. Reconnect any connected devices, verify that your system recognizes them, and run this command again.

### Platform info:
- CLI: 3.0.0-rc.1
- OS: Windows 10 Pro x64

### Steps:
- Update to version 3.0
- `tns create DemoNgV3RC --template tns-template-hello-world-ng@rc`
- `tns platform add android@r`
- No code changes, try to run and get the error.

### Update:
- I did the same process in MAC and all is fine

**Comment by dtopuzov** [comment]
Hi @julitogtu 

From what I see it looks Android Tools issue (adb), can you reproduce the issue with latest official version of {N}?

**Comment by tsonevn** [comment]
Hi @julitogtu,
Could you provide also some info about the device or emulator, which you are using for testing?
Also, do you use Genymotions or default [AVD emulator](https://docs.nativescript.org/tooling/android-virtual-devices)?

**Comment by julitogtu** [comment]
Hi @tsonevn I'm using genymotion v 2.8.1,

**Comment by dtopuzov** [comment]
@julitogtu did you try the things listed here: 
https://github.com/NativeScript/NativeScript/issues/3903#issuecomment-290313821

**Comment by julitogtu** [comment]
@dtopuzov not yet, I tried it tonight and send us and update, sorry for the delay

**Comment by NickIliev** [comment]
@julitogtu closing this one due to inactivity but please let us know if you need further assistance on this one

**Comment by julitogtu** [comment]
Hi @NickIliev sorry for the delay, I come back to nativescript 2.5 and all work fine, so reinstalled all, genymotion, node, nativescript 3.0 and now its working fine, maybe an update issue in windows? I did the same steps in MAC and I did not problems, thanks

**Comment by demym** [comment]
Hi, I have too problems on 3.0.

How can I cleanly go back to 2.5 ? I've tried several commands (npm I -g nativescript@2.5.0 n others), but I have no been able to reissue my working 2.5 environment.. thanks I advance

**Comment by NathanaelA** [comment]
@demym - See my blog http://fluentreports.com/blog/?p=509

**Comment by ShonChuang** [comment]
I have too problems on CLI 3.0 and on MAC.

**Comment by dtopuzov** [comment]
Hi @ShonChuang 

What are your problems?
If you think that those problems are valid issues, please log them and add more info - description, steps to reproduce, versions of {N} components (CLI, modules, platforms).

**Comment by julitogtu** [comment]
Hi @ShonChuang , when I updated to {N} version 3 I had issues with emulators, but after update xcode and reinstall {N} all is work fine.
