### ISSUE TITLE
SegmenterBar on Android color incorrect

### ISSUE THREAD

**Issue by rowdyrabouw** [NativeScript/NativeScript#3904]
I have weird behaviour for the segmented bar.

On the home page and detailpage the segmented bars are exactly the same, but on home it's blue underlined (default Android) and on the detail page it's green as it should be.

When you return from the detail page to home, it is suddenly green (as it is supposed to)!

Any ideas what's going on here?

Project + animated GIF is on :
https://github.com/rowdyrabouw/-N-SegmentedBar

**Comment by tsonevn** [comment]
Hi @rowdyrabouw,
I tested your project, however its seems that this behavior has been related to using an old `nativescript-angular`. I created new project with `tns create sample --ng` and tested the below-attached code and the `selectedBackgroundColor` seems to be applied as expected.

HTML
```
<ActionBar title="My App" class="action-bar">
</ActionBar>
<StackLayout class="page">
    <SegmentedBar borderColor="#8AC215" selectedBackgroundColor="#8AC215" [items]="sgbaritems" >
    </SegmentedBar>
</StackLayout>
```
TypeScript
```
import { Component, OnInit } from "@angular/core";

import { Item } from "./item";
import { ItemService } from "./item.service";

@Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
})
export class ItemsComponent {
    items: Item[];
    sgbaritems=[{title: 'Ingredients'}, {title: 'Tools'}, {title: 'Procedure'}]

    
}
```

You could also update your existing project `package.json` by following the attached sample.
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.ngsample",
    "tns-android": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/animations": "4.0.0",
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/router": "4.0.0",
    "nativescript-angular": "1.5.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "2.5.2",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.23.1",
    "babel-types": "6.23.0",
    "babylon": "6.16.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.3.5",
    "typescript": "~2.1.0"
  }
}
```
Bear in mind that you should delete  `platforms` and `node_modules` folders before rebuilding with `tns run android`.
Could you also provide some more info about your environment(CLI, node versions).

**Comment by rowdyrabouw** [comment]
Yes, in the sample project it's working now with nativescript-angular 1.5.0.

I'm currently upgrading my real project to Angular 4 and the latest nativescript packages to see if it's working there too. Running in some problems there now.

To be continued ... :-)

**Comment by NickIliev** [comment]
Hey @rowdyrabouw closing this one due to inactivity but let us know if you need further assistance.
