### ISSUE TITLE
Stopping Tranisiton when change View in TabView

### ISSUE THREAD

**Issue by adappter** [NativeScript/NativeScript#3906]
Hello,

I'm using a TabView in my NativeScript porject. In iOS there is a transition bug when changing to a view.

Herer is a screencast: https://www.dropbox.com/s/p4frjnwnbtw49m2/Bildschirmaufnahme.mov?dl=0

I think the problem is, that NativeScript doesn't use a TabBarController  because the navigtion bar seems not to be a part of the TabBarController like I know from the native Storyboard, because the push segue doesn't look like this.

**Comment by NickIliev** [comment]
Hey @adappter can you provide a code sample to reproduce this issue so we can investigate it locally?

**Comment by adappter** [comment]
ok, sorry for duplicate :)
