### ISSUE TITLE
Webpack Issues n3.0

### ISSUE THREAD

**Issue by URvesh109** [NativeScript/NativeScript#3909]
Hello, Nativescript Team,

I have created app, but it size is too big and loading time is upto 8sec approx, so i decided to use webpack and aot. When i use fresh template of hello world-ng@rc, and  npm run start-android-bundle
showing errors.

ERROR in ../~/nativescript-angular/directives/action-bar.ngfactory.ts
Module not found: Error: Can't resolve '../../../@angular/core' in '/home/urvesh/Miscellaneous/Nativescript/projects/Nat3/node_modules/nativescript-angular/directives'
 @ ../~/nativescript-angular/directives/action-bar.ngfactory.ts 9:14-47
 @ ./item/items.component.ngfactory.ts
 @ ./app.module.ngfactory.ts
 @ ./main.aot.ts

ERROR in ../~/nativescript-angular/directives/list-view-comp.ngfactory.ts
Module not found: Error: Can't resolve '../../../@angular/core' in '/home/urvesh/Miscellaneous/Nativescript/projects/Nat3/node_modules/nativescript-angular/directives'
 @ ../~/nativescript-angular/directives/list-view-comp.ngfactory.ts 9:14-47
 @ ./item/items.component.ngfactory.ts
 @ ./app.module.ngfactory.ts
 @ ./main.aot.ts

**Comment by sis0k0** [comment]
Hello @URvesh109,

You'll need to manually update the version of the `@angular/compiler-cli` to 4.0.0 to make it compatible with the other angular packages. Let us know if solves the problem.

**Comment by URvesh109** [comment]
Hello Ma'am,

this is my package.json file

{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.WebPack",
    "tns-android": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/animations": "4.0.0",
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/router": "4.0.0",
    "nativescript-angular": "1.5.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "2.5.2",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~2.4.3",
    "@ngtools/webpack": "1.2.10",
    "babel-traverse": "6.23.1",
    "babel-types": "6.23.0",
    "babylon": "6.16.1",
    "copy-webpack-plugin": "~3.0.1",
    "extract-text-webpack-plugin": "~2.0.0-beta.4",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.3.5",
    "nativescript-dev-webpack": "^0.3.6",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~1.6.0",
    "typescript": "~2.1.0",
    "webpack": "2.2.0",
    "webpack-sources": "~0.1.3"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --start-app",
    "start-ios-bundle": "npm run ns-bundle --ios --start-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}
will this dependencies it is not working.


But with this package.json it is working

{
    "description": "NativeScript Application",
    "license": "SEE LICENSE IN <your-license-filename>",
    "readme": "NativeScript Application",
    "repository": "<fill-your-repository-here>",
    "nativescript": {
        "id": "org.nativescript.Parlour",
        "tns-android": {
            "version": "2.5.0"
        }
    },
    "dependencies": {
        "@angular/common": "2.4.3",
        "@angular/compiler": "2.4.3",
        "@angular/core": "2.4.3",
        "@angular/forms": "2.4.3",
        "@angular/http": "2.4.3",
        "@angular/platform-browser": "2.4.3",
        "@angular/platform-browser-dynamic": "2.4.3",
        "@angular/router": "3.4.3",
        "nativescript-angular": "1.4.0",
        "nativescript-exit": "^1.0.0",
        "nativescript-theme-core": "~1.0.2",
        "nativescript-toast": "^1.4.5",
        "reflect-metadata": "~0.1.8",
        "rxjs": "~5.0.1",
        "tns-core-modules": "2.5.2"
    },
    "devDependencies": {
        "@angular/compiler-cli": "~2.4.3",
        "@ngtools/webpack": "1.2.10",
        "babel-traverse": "6.23.1",
        "babel-types": "6.23.0",
        "babylon": "6.16.1",
        "copy-webpack-plugin": "~3.0.1",
        "extract-text-webpack-plugin": "~2.0.0-beta.4",
        "lazy": "1.0.11",
        "nativescript-css-loader": "~0.26.0",
        "nativescript-dev-android-snapshot": "^0.*.*",
        "nativescript-dev-typescript": "~0.3.5",
        "nativescript-dev-webpack": "^0.3.6",
        "raw-loader": "~0.5.1",
        "resolve-url-loader": "~1.6.0",
        "typescript": "~2.1.0",
        "webpack": "2.2.0",
        "webpack-sources": "~0.1.3",
        "zone.js": "~0.7.2"
    },
    "scripts": {
        "ns-bundle": "ns-bundle",
        "start-android-bundle": "npm run ns-bundle --android --start-app",
        "start-ios-bundle": "npm run ns-bundle --ios --start-app",
        "build-android-bundle": "npm run ns-bundle --android --build-app",
        "build-ios-bundle": "npm run ns-bundle --ios --build-app"
    }
}


Can we use webpack with nativescript 3.0 and angular 4

**Comment by sis0k0** [comment]
Yup, just the update the first devDependency (@angular/compiler-cli) to 4.0.0 :)

**Comment by URvesh109** [comment]
Thks Ma'am
