### ISSUE TITLE
iOS: icloud option not available to upload files [PDf amd Word ]from IOS Devices

### ISSUE THREAD

**Issue by pap5508** [NativeScript/NativeScript#3917]
Hello Nativescript,
In my Application I need to share document using icloud. I searched a lot but No where find out the option for icloud access using nativescript.

Please guide me for accessing Document from icloud.There is no Options to upload document from icloud.

How can I open icloud and select document and share it..?

**Comment by NickIliev** [comment]
Hey @pap5508 can you clarify what is preventing you from working with files from iCloud? Perhaps you can share a code base of what you have tried so far.
Meanwhile, to access files from iCloud you should first save them locally and then you can upload and share them or execute other operations as your app logic requires. Details about how to achieve this can be found in [this thread](https://github.com/NativeScript/nativescript-imagepicker/issues/67#issuecomment-276662830).

**Comment by pap5508** [comment]
@NickIliev : firstly thank you for the quick response.. the method you refereed me I have already implemented for the Image Pick and capture photo. but My question is how can I attach PDF and WORD files from the icloud..??

Do I need to give specific permission for that..?

**Comment by pap5508** [comment]
@NickIliev : I would like to attach PDF and Word File from iCloud. Do we have any sample for that to access iCloud from device and select PDF file and Upload it.._??

**Comment by NickIliev** [comment]
@pap5508 indeed there is no out-of-the-box way to handle files from iCloud in NativeScript (except for images where nativescript-imagepicker is providing built-in access to the gallery). In this case you can implement a native solution  Take a look at [this answer](http://stackoverflow.com/a/32229311/4936697) on how to enable iCloud in your info.plist and also on [this thread](http://stackoverflow.com/a/26791231/4936697) to see a native implementation for downloading a file from iCloud. Once downloaded you and save to a temp folder and proceed with your further logic using the temp file saved.

To implement the Objective-C code in NativeScript you will need to do data conversion - see [this article ](http://docs.nativescript.org/runtimes/ios/marshalling/Marshalling-Overview)for details on the syntax needed to convert the iOS API

**Comment by pap5508** [comment]
@NickIliev : 
I did research a lot and found out package for Document Picker... need your view that does this solve my Problem.?

https://www.npmjs.com/package/react-native-document-picker
