### ISSUE TITLE
[3.0 RC] - Spawn EPERM

### ISSUE THREAD

**Issue by Cae2** [NativeScript/NativeScript#3918]
Hello guys,

I'm testing the RC and everything went fine in my home computer yesterday, yay!

but today in my company notebook I followed the exact same guide, and cannot build or run my application, it gives the error:

![1](https://cloud.githubusercontent.com/assets/24416663/24554849/66f5898e-1605-11e7-8aed-ab0dda69dae4.jpg)

(in appbuilder there is a --verbose/--debug option to show more details, didnt find something like that in tns to provide you more details..)

**Comment by NickIliev** [comment]
Hey @Cae2 can you give more details on your configuration (OS, Node versions, npm version). 
Also, run `tns doctor` to verify that you have a proper installation of NativeScript.

The error is related to locked folders/files and the absence of permissions to unlock them.
Can you try `npm cache clean` and the steps mentioned [here](https://github.com/NativeScript/nativescript-cli/issues/1029#issuecomment-146758169)

**Comment by Cae2** [comment]
@NickIliev ohh nice, thanks for the tips! setting the debug to true more info comes out (after npm cache clean)

![2](https://cloud.githubusercontent.com/assets/24416663/24556637/6d69f51a-160b-11e7-8308-2c2df0b04266.jpg)

the tns doctor says that no issues were detected, just did some upgrade (from node v6.9.5 to v6.10.1, npm was already on v3.10.10. Im using W10 OS), deleted the nativescript global directory to reinstall from fresh, but still with the same error.

trying to figure out what kind of permission could it be...  (Im sending the "--log trace > out.txt"  of tns platform add android@rc and tns build android)

[tns_android_build_out.txt](https://github.com/NativeScript/NativeScript/files/886154/tns_android_build_out.txt)

[platform_add_android.txt](https://github.com/NativeScript/NativeScript/files/886155/platform_add_android.txt)
