### ISSUE TITLE
issue implementing an interface

### ISSUE THREAD

**Issue by kesienajoel** [NativeScript/NativeScript#3920]
please i need help implementing the java code in nativescript.

```
public abstract interface IpayResultDelegate {
         public abstract void onPaymentSucceeded(String TransId, String RefNo, String Amount, String Remark, String AuthCode);
         public abstract void onPaymentFailed(String TransId, String RefNo, String Amount, String Remark, String ErrDesc);
         public abstract void onPaymentCanceled(String TransId, String RefNo, String Amount, String Remark, String ErrDesc);
         public abstract void onRequeryResult(String MerchantCode, String RefNo,
String Amount, String Result); 
}
```

**Comment by kesienajoel** [comment]
thank you. i will check it out

**Comment by kesienajoel** [comment]
i get this error when i follow the implementation from the article

java.lang.NullPointerException: Attempt to invoke direct method 'java.lang.Object com.tns.Runtime.callJSMethodImpl(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[])' on a null object reference

**Comment by tsonevn** [comment]
Hi @kesienajoel, 
Could you provide some sample project or at least sample code, which could be debugged locally? It would also help if you could also send us the full log from the console with the error.
