### ISSUE TITLE
issue with 3.0 and nativescript-camera plugin

### ISSUE THREAD

**Issue by SD-Lab** [NativeScript/NativeScript#3921]
Hello,

I'm testing the new 3.0 version for 3 days an I am facing a camera plugin issue: when I add the nativescript-camera plugin (just run "tns plugin add nativescript-camera", not even use it) the application crashes (no other change, no error message).

but if I restart from scratch it works:
```
- tns create MyApp --template tns-template-hello-world-ng@rc
- tns plugin add nativescript-camera
- tns run android
```

I don't know how solving this. Is someone facing the same issue ?

**Comment by Daxito** [comment]
Can leave a comment how you fixed this issue if any? I dont have it, but just for the record ;-)

**Comment by pap5508** [comment]
@Daxito : First include`"nativescript-camera": "0.0.8", in Package.json`
Initialize in your component with `import {takePicture} from "nativescript-camera";`
and to open Camera Module. you can call method... TakePicture.. 
`cameraModule.takePicture({ width: 200, height: 200, keepAspectRatio: true}).then(picture => {
          
          //  Handle ImageSource here....
     
        });`
