### ISSUE TITLE
Event handler: entry.callback is not a function

### ISSUE THREAD

**Issue by khcr** [NativeScript/NativeScript#3922]
Android
CLI: 2.5.2
Cross-platform modules: 2.5.1
Runtime: 2.5.0

Hi,
I'm trying to create an infinite feed (facebook-like). I add a scroll event, which loads new posts when the user scrolls to the bottom of the page. While the posts are loading, I delete the event handler and once the posts are ready, I add the scroll event again. However, this last step raises an exception.
```
> An uncaught Exception occurred on "main" thread.
> com.tns.NativeScriptException: 
> Calling js method onScrollChanged failed
> 
> TypeError: entry.callback is not a function
> File: "file:///data/data/org.jstech.rjApp/files/app/tns_modules/tns-core-modules/data/observable/observable.js, line: 149, column: 22
> 
> StackTrace: 
> 	Frame: function:'Observable.notify', file:'file:///data/data/org.jstech.rjApp/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 149, column: 23
> 	Frame: function:'ScrollView._onScrollChanged', file:'file:///data/data/org.jstech.rjApp/files/app/tns_modules/tns-core-modules/ui/scroll-view/scroll-view.js', line: 132, column: 22
> 	Frame: function:'onScrollChanged', file:'file:///data/data/org.jstech.rjApp/files/app/tns_modules/tns-core-modules/ui/scroll-view/scroll-view.js', line: 121, column: 27
> 
> 	at com.tns.Runtime.callJSMethodNative(Native Method)
> 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
> 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
> 	at com.tns.Runtime.callJSMethod(Runtime.java:1047)
> 	at com.tns.Runtime.callJSMethod(Runtime.java:1028)
> 	at com.tns.Runtime.callJSMethod(Runtime.java:1018)
> 	at com.tns.gen.android.view.ViewTreeObserver_OnScrollChangedListener.onScrollChanged(android.view.ViewTreeObserver$OnScrollChangedListener.java)
> 	at android.view.ViewTreeObserver.dispatchOnScrollChanged(ViewTreeObserver.java:1016)
> 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2687)
> 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
> 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
> 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
> 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
> 	at android.view.Choreographer.doFrame(Choreographer.java:621)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
> 	at android.os.Handler.handleCallback(Handler.java:751)
> 	at android.os.Handler.dispatchMessage(Handler.java:95)
> 	at android.os.Looper.loop(Looper.java:154)
> 	at android.app.ActivityThread.main(ActivityThread.java:6119)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
> 
```
Here is the code for my feed view:

```
var scrollEvent = require("ui/scroll-view").ScrollView.scrollEvent;

var PostList = new Post.List()

var page, postsView;

var pageData = new observableModule.fromObject({
    posts: PostList
});

exports.loaded = function(args) {
  page = args.object;
  page.bindingContext = pageData;

  PostList.empty();
  PostList.load();

  postsView = page.getViewById("posts");
  postsView.addEventListener(scrollEvent, loadMore);
};

var loadMore = function(e) {
  if((e.object.scrollableHeight - 20) <= e.scrollY) {
    postsView.removeEventListener(scrollEvent);
    PostList.load().then(function() {
      postsView.addEventListener(scrollEvent, loadMore);
    });
  }
}

```

Thanks for your help !

**Comment by tsonevn** [comment]
Hi @khcr,
For your case on `removeEventListener` method, you should also specify the callback method, which will be removed. For example:
```
var loadMore = function(e) {
  if((e.object.scrollableHeight - 20) <= e.scrollY) {
    postsView.removeEventListener(scrollEvent, loadMore);
    PostList.load().then(function() {
      postsView.addEventListener(scrollEvent, loadMore);
    });
  }
}
```

This should remove the event properly and will allow you to attach a new one, when the new item has been added to the list.

Regarding the topic, you for your case you could also use `nativescript-telerik-ui` `RadListView` component and its `Load on demand` functionality, which will help you to created the infinity feed in your app. For further help, you could review the [documentation ](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/load-on-demand) and the sample project [here](https://github.com/telerik/nativescript-ui-samples/tree/release/sdk/app/listview/load-on-demand).

Hope this helps.

**Comment by khcr** [comment]
Thanks for your reply. I tried your solution, but unfortunately the problem is still there. 
```RadListView``` seems a pretty good option if we don't find the cause of the bug.

**Comment by tsonevn** [comment]
Hi @khcr 

Could you send us sample project, where the issue could be reproduced on our side? This will help us to provide some further suggestions about the cause of the problem.

**Comment by NickIliev** [comment]
@khor you can use [this test application](https://github.com/NativeScript/NativeScript/blob/master/apps/app/cuteness.io/reddit-app-view-model.ts) as a reference where the requested functionality (loadOnDemand) is implemented using ListView module.

As this is related to a common functionality and not to an issue or a bug please post similar questions to our community channels (as SO or [forum.nativescript.org](https://discourse.nativescript.org)) where your question will have more visibility and the information will be discussed and shared with other community members.
