### ISSUE TITLE
PackageApplication not available anymore after Xcode update to Version 8.3

### ISSUE THREAD

**Issue by u-r-b-a-n-y** [NativeScript/NativeScript#3923]
I am getting this error when I run "**tns run ios**" after updating to Xcode 8.3 today.

> ** BUILD SUCCEEDED **
> xcrun: error: unable to find utility "PackageApplication", not a developer tool or in PATH
> Command xcrun failed with exit code 72

### Which platform(s) does your issue occur on?
iOS (macOS Sierra 10.12.4)

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.3

**Comment by Yamilquery** [comment]
I have the same error...

[https%3A%2F%2Fgithub.com%2FNativeScript%2Fnativescript-cli%2Fissues%2F2668&usg=AFQjCNEllFrkTOsRVsGa70wMB7KzdpIr6g&sig2=5BDbE-cVUK4apvC3rDGOoQ&bvm=bv.151325232,d.amc](url)

**Comment by dtopuzov** [comment]
Already reported in CLI repository: https://github.com/NativeScript/nativescript-cli/issues/2668
I hope we will have a fix in several days.
