### ISSUE TITLE
iOS: attr.isEnabled not working

### ISSUE THREAD

**Issue by dxshindeo** [NativeScript/NativeScript#3936]
The following is correctly disabled in android, but can still be tapped in iOS, when it shouldn't:
```
<StackLayout [attr.isEnabled]="false" (tap)="globalsService.menuService.selectImages()" ></StackLayout>
```

NS CLI: 2.5.3
Tested on real iPhone 5.

**Comment by vakrilov** [comment]
If you want to disable the tap event - use the [`isUserInteractionEnabled`](http://docs.nativescript.org/api-reference/classes/_ui_core_view_.view.html#isuserinteractionenabled) property.
```
<StackLayout class="page" [attr.isUserInteractionEnabled]="val" (tap)="tap()"></StackLayout>
```

**Comment by dxshindeo** [comment]
Ah, forgot about that one, thanks, it does disable it :)
