### ISSUE TITLE
Nativescript-camera not working with Nativescript 3.0

### ISSUE THREAD

**Issue by SD-Lab** [NativeScript/NativeScript#3939]
Nativescript-camera not working with Nativescript 3.0

**Problem:**
The plugin nativescript-camera doesn't seem to work with Nativescript 3.0. 
The code never executes what is inside the "then" of Camera.takePicture() when we install a nativescript 3.0 project.
It does work however when we install a nativescript 2.5.2 project. (see below)

Platform: Android

Versions: 
tns-core-modules: rc,
nativescript-camera 0.0.8

**Recreating the issue:**
Create the project and install the plugin: 
```
    tns create MyApp --template tns-template-hello-world-ng@rc
    npm install
    tns plugin add nativescript-camera
```

Put this code into app.component.ts:
```
import { Component, OnInit } from "@angular/core";
import * as Camera from 'nativescript-camera';
@Component({
    selector: "ns-app",
    templateUrl: "app.component.html",
})
export class AppComponent implements OnInit { 
    ngOnInit() {
        Camera.requestPermissions();
        console.log("Before taking picture");
        Camera.takePicture()   
            .then((imageAsset) => {
                console.log("Result is an image asset instance");
            }).catch((err) => {
                console.log("Error -> " + err.message);
            });
    }
}
```

The problem is "Result is an image asset instance" is never displayed, even after taking the picture.
When we create a project in nativescript version 2.5.2, "Result is an image asset instance" is displayed after taking the picture. 

**Installing the 2.5.2 nativescript project - working**

Versions: 
tns-core-modules: ^2.5.2,
nativescript-camera 0.0.8

The project is created with the following commands:
```
tns create HelloWorld --template nativescript-template-ng-tutorial
npm install
tns plugin add nativescript-camera
```

app.component.ts code in 2.5.2 nativescript project:
```
import { Component, OnInit } from "@angular/core";
import * as Camera from 'nativescript-camera';
@Component({
  selector: "my-app",
  template: `
    <ActionBar title="My App"></ActionBar>
    <!-- Your UI components go here -->
  `
})
export class AppComponent implements OnInit {
  
  ngOnInit() {
      Camera.requestPermissions();
      console.log("Before taking picture");
      Camera.takePicture()   
          .then((imageAsset) => {
              console.log("Result is an image asset instance");
          }).catch((err) => {
              console.log("Error -> " + err.message);
          });
  }
}
```

**Comment by NickIliev** [comment]
Hey, @SD-Lab 

Indeed the current latest versions of the plugin (0.0.8) are not compatible with NativeScript 3.0.0-rc1.
We are working on the official version compatible with the release candidate, meanwhile, you can already find a working one in [this branch](https://github.com/NativeScript/nativescript-camera/tree/hdeshev/modules-3.0). It is not officially published, but you can clone the repo and create an npm pack from that branch.
e.g
```
git clone git@github.com:NativeScript/nativescript-camera.git
git checkout hdeshev/modules-3.0
cd src
tsc
npm pack
```
then take the generated tgz file and use it as a plugin for your 3.0-rc1 project
```
tns plugin add <path-to-the-generated-tgz>
```

[Here ](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_3939)you can find test application using this workflow.

**Comment by NickIliev** [comment]
Even the more convenient way to create your local buld using the RC (or other versions) is the following:

 - Clone the repo
- Run the create script in the root of the repo:
./create.sh
- This will create a nativescript-camera-*.tgz file (* stands for version) within ./dist folder.

Based on the README of the plugin [here](https://github.com/NativeScript/nativescript-camera)
