### ISSUE TITLE
How to fit a image in Absolute Layout

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#3943]
How to fit a image in Absolute Layout, what ever the image size be it must be fitted in to the specified height and width.
![category](https://cloud.githubusercontent.com/assets/10844041/24697884/674610ba-1a0c-11e7-8a6a-e0a2769889d0.PNG)

			<StackLayout orientation="horizontal">

					<AbsoluteLayout class="firstRow " height="160" width="47%">
						<AbsoluteLayout>
							<Image src="~/images_Test/Chicken with skin.jpg" ></Image>
						</AbsoluteLayout>
						<Label text="  Country Chicken" textWrap="true" class="categoryNames  text-center  bgCategory"></Label>
					</AbsoluteLayout>
					<AbsoluteLayout class="firstRow " height="160" width="47%">
						<AbsoluteLayout>
							<Image  src="~/images_Test/lillys.jpg" ></Image>
						</AbsoluteLayout>
						<Label text="  Country Chicken" textWrap="true" class="categoryNames  text-center  bgCategory"></Label>

					</AbsoluteLayout>
				</StackLayout>

This is the code for above image for the first row

**Comment by pap5508** [comment]
Just add this..
`stretch="aspectFit" `

Hope this helps..

**Comment by BenGermany** [comment]
You can find the available stretch modes here:

http://docs.nativescript.org/api-reference/modules/_ui_enums_.stretch.html

**Comment by dhanalakshmitawwa** [comment]
Thank you , for reply

**Comment by dhanalakshmitawwa** [comment]
Thank you, for reply

**Comment by dhanalakshmitawwa** [comment]
I can add the stretch="aspectfit" , but not fitted any image

**Comment by BenGermany** [comment]
It's aspectFit, not aspectfit?

**Comment by dhanalakshmitawwa** [comment]
<StackLayout orientation="horizontal">

					<AbsoluteLayout class="firstRow " height="160" width="47%">
						<AbsoluteLayout>
							<Image stretch="aspectFit" src="~/images_Test/Chicken with skin.jpg" class="chickenImg"></Image>
						</AbsoluteLayout>
						<Label text="  Country Chicken" textWrap="true" class="categoryNames  text-center  bgCategory"></Label>
					</AbsoluteLayout>
					<AbsoluteLayout class="firstRow " height="160" width="47%">
						<AbsoluteLayout>
							<Image src="~/images_Test/lillys.jpg" stretch="aspectFit" class="chickenImg"></Image>
						</AbsoluteLayout>
						<Label text="  Country Chicken" textWrap="true" class="categoryNames  text-center  bgCategory"></Label>

					</AbsoluteLayout>
				</StackLayout>
I tried it , but i could not get the output

**Comment by BenGermany** [comment]
This should be aspectFill - i posted the modes before... Please look at.

**Comment by NickIliev** [comment]
Hey @dhanalakshmitawwa question related to UI and UX are better suited in some of the community channels like StackOverflow or forum.nativescript.org. Please keep the issues in this repository for reporting problems, bugs and features.
