### ISSUE TITLE
Adding script to build phase

### ISSUE THREAD

**Issue by patrickpereira** [NativeScript/NativeScript#3944]
Hi Nativescript,

Is it possible to add a script to build phases without using xcode? If so, how?

Best regards
Patrick

**Comment by NickIliev** [comment]
Yes, it is possible with the help of **hooks**.
To create a **hooks** you will need a folder with the same name (**hooks**) at your root level.
The nativeScript CLI will automatically execute the scripts but they have to follow a naming convention from which it depends on when the scripts will be executed.

[Here ](https://github.com/NativeScript/nativescript-cli/blob/25b68253de48f1994ab1644b8fbb0bcbfa48a68f/extending-cli.md)you can find an article that covers the usage of hooks in NativeScript.
