### ISSUE TITLE
how to view image like this?

### ISSUE THREAD

**Issue by sydeEvans** [NativeScript/NativeScript#3945]
like is in wechat?
![img_2285](https://cloud.githubusercontent.com/assets/15522856/24700353/7efc4fae-1a29-11e7-80c5-2e690c42c276.PNG)

**Comment by BenGermany** [comment]
There is some logic to build this, you can try to find a plugin that fits your needs... I thought there would be something out there like a carousel or so

**Comment by tsonevn** [comment]
Hi @sydeEvans,

In your case, you could use [nativescript-carousel](https://www.npmjs.com/package/nativescript-carousel) plugin. Sample project could be found [here](https://github.com/manijak/nativescript-carousel/tree/master/demo).

Please for more `How To` questions use our StackOverflow thread [here](http://stackoverflow.com/questions/tagged/nativescript).

**Comment by sydeEvans** [comment]
Thanks for the answer~ 
@tsonevn but I need a plugin like nativescript-photoviewer 
but  nativescript-photoviewer seems like work worry in Xcode build

<img width="1391" alt="dingtalk20170405191016" src="https://cloud.githubusercontent.com/assets/15522856/24702960/afabae38-1a33-11e7-8ccb-d54cb0a81f3e.png">

**Comment by tsonevn** [comment]
Hi @sydeEvans,
I have tested this plugin on my side while using clear NativeScript project and everything seems to work as expected. You could review the attached sample project.

If you have some further issues with the plugin, you could log them in the plugins repository [here](https://github.com/manijak/nativescript-photoviewer/issues).
[Archive.zip](https://github.com/NativeScript/NativeScript/files/899751/Archive.zip)
