### ISSUE TITLE
Feature: Page onRendered 

### ISSUE THREAD

**Issue by BenGermany** [NativeScript/NativeScript#3946]
Actually there is no possibility to get a callback when the Ui is rendered. Actually, we can catch the following states of a Page:

navigatingTo, loaded, navigatedTo. 

On all this states there is no guaranteed UI Layout, so every coder must use a timeout or interval and try to find this happening. 

Like for getMeasuredHeight() / Width / Position... 

Overall, the performance of nativescript apps could be better (or less laggy), if there is a clean state after rendering.

So if a Page is initially rendered (only the XML!) i want a callback like "onRendered".

After this, there might be updates or animations which should trigger it too, but only if this is done (not while - this could be "onRendering" for consistency.)

To check for the rendered elements, there could be the infos in the args-object. 

Are there any possibilities to get this into the core?

**Comment by tsonevn** [comment]
Hi @BenGermany,
If I understand you correctly, you would like to handle the moment, when some component has been rendered on the screen and when this happens to attach an animation to it.

If this is the case you could use component `loaded` event. When the event has been fired, you could access the component and to make the needed changes. For example:

XML
```
<Button loaded="btLoaded" text="Sample button" tap="" />
```
TypeScript
```
import {Button} from "ui/button"
export function btLoaded(args){
    var button:Button = <Button>args.object;
// make the needed changes.
}
```

Let me know, whether this helps.

**Comment by BenGermany** [comment]
Hi @tsonevn,

this would be unbelievable - i just want to get a callback when a component was rendered to get the rendered size without using timeouts or intervals.

I tried lastly on Page and asked some people, but found only help in using timeouts - but this is not the clean code I want to have. 

I will try this in the evening - if this is the callback where I got correct measurements for height in width or location etc. (not only zero because the measures comes before rendering) nativescript seems to be the widely really best framework i have ever used. If not, i will have an idea for improvement ;-) 

Many thanks, 
I will answer my posts for others if this is the clean solution.

**Comment by BenGermany** [comment]
... height AND width ... ;-) please do not get confused

**Comment by BenGermany** [comment]
Hi @tsonevn,

yes, your last words are the issue/feature i asked - everything everytimes returns zero (0) and i have to do a timeout or interval to get correct measurement like height: 200 or width: 127 or whatever. Same on LocationInWindow, getActualSize, ... and so on. Nothing returns anything else than zero or objects with values = zero.

THX

**Comment by bozhidarc** [comment]
+1

**Comment by john-landgrave** [comment]
I'm encountering a similar issue here, but the use-case is a little different. We are trying to apply a gradient to text/icons by calling into the native platforms to do their native gradient stuff. This is working, but with the timeout and no good "force redraw" methodology (at least on Android) I'm in a bind.

Gradients coordinates are apparently from the top left of the screen, not the top left of the control, so I need to get the coordinates of the control in order to properly scale the gradient. I need some sort of event that would allow me to `getLocationInWindow()` as well as `measureText()` and `getMeasuredHeight()`, any thoughts there? This request seems like what I would need.

**Comment by BenDietze** [comment]
Any progress here?

So, when using a timeout to await the moment the ui is completely build and ready for measuring - is it already guaranteed, if we use a zero-seconds-timeout or should it be some milliseconds, because xml/ui isnt completely rendered when {N} runs the .js file?

**Comment by tsonevn** [comment]
Hi all,
With the latest NativeScript, you can use the new `layoutChanged ` event. For example: 
```XML
<Page xmlns="http://schemas.nativescript.org/tns.xsd">
    <StackLayout layoutChanged="onLayoutChanged" class="p-20">
        <!-- ......  -->
    </StackLayout>
</Page>
 ```
```TypeScript
import {StackLayout} from "ui/layouts/stack-layout";
 export function onLayoutChanged(args){
    let layout:StackLayout = <StackLayout>args.object;
    console.log("StackLayout - actual width: "+layout.getActualSize().width);
    console.log("StackLayout - actual height: "+layout.getActualSize().height);
}
```
```JavaScript
function onLayoutChanged(args) {
    var layout = args.object;
    console.log("StackLayout - actual width: " + layout.getActualSize().width);
    console.log("StackLayout - actual height: " + layout.getActualSize().height);
}
exports.onLayoutChanged = onLayoutChanged;
```

**Comment by BenDietze** [comment]
Thanks @tsonevn 

So, this is now the overall feature for all things hanging on correct measuring:

- when a page / element is initially first time drawn
- on every redraw of an element / page

and there is no need anymore for setTimeout() to get complete drawn UI?

**Comment by NickIliev** [comment]
Closing as the provided implementation of ``layoutChanged event is in compliance with this feature request.
