### ISSUE TITLE
Image not showing up on radsidedrawer V 2.5.3

### ISSUE THREAD

**Issue by SamBaqai94** [NativeScript/NativeScript#3949]
hey,
I am creating my app on NativeScript. Firstly, its wonderful, thank you for making this. I am having one issue and that is image not showing up in sidedrawer header
here is my code:

```
<sd:RadSideDrawer.drawerContent>
             <StackLayout class="sidedrawer-left">
                 <StackLayout class="sidedrawer-header">
                     <Label text="Hello Kobe!" class="sidedrawer-header-brand"/>
                     <Image src="res://logo" stretch="none" />
                 </StackLayout>
```

**Comment by tsonevn** [comment]
Hi @SamBaqai94,
Thank you for contacting us.
I have tested your case on my side, however, I was unable to reproduce this case on my side.
Could you provide some more info about the problem and the platform, where you experience this issue?

It would also help if you could send us sample project, which could be debugged locally.

In the meantime could you also verify that you have set the images in the correct folder in the App_Resources for both iOS and Android. Further info about the loading images from resources and the right image place could be found [here](https://docs.nativescript.org/ui/images#load-images-from-a-resource).
