### ISSUE TITLE
any plugin for aws.s3?

### ISSUE THREAD

**Issue by SumanSingh4** [NativeScript/NativeScript#3952]
I want to save data at AWS.S3. But I didn't find any plugin.I have used nativescript-aws. But it didn't work.  

Can any have any suggestions?? Please I need it urgently.

Thanks

**Comment by tsonevn** [comment]
Hi @SumanSingh4, 
In your case, you could use [nativescript-aws](https://www.npmjs.com/package/nativescript-aws) plugin, which exposes AWS SDK.
For further help and guidelines, how to use it in a NativeScirpt project, you could review the plugins repository [here](https://github.com/EddyVerbruggen/nativescript-aws). You could also review the demo app [here](https://github.com/EddyVerbruggen/nativescript-aws/tree/master/demo).

**Comment by SumanSingh4** [comment]
Hi @tsonevn I have try these many time currently again trying this but I am getting error.

In app.component.ts file 
import * as AWS from "nativescript-aws";
import { Credentials } from "nativescript-aws";
constructor() {
        // set connection to AWS
        AWS.config.update({
            region: 'eu-west-1',
            credentials: new AWS.CognitoIdentityCredentials({
                IdentityPoolId: ..........
            })
        });
}

in home.component.ts
import * as AWS from "nativescript-aws";

let s3 = new AWS.S3();
 let params = {
            Bucket: ".......",
            Key: '..........',
            Body: ........
};

        s3.upload(params, (err, result) => {
            if (!err) {
               //work
            } else {
                console.log(err);
            }
        });


I am getting error : CredentialsError: Missing credentials in config


Any help??

**Comment by tsonevn** [comment]
Hi @SumanSingh4,
Excuse me for my misunderstanding.
I notice that `nativescript-aws` plugin has been deprecated in favor of `nativescript-nodeify`, which should be used for Amazon Web Services in your app.
You could review the [demo](https://github.com/EddyVerbruggen/nativescript-nodeify) app and test it with your credentials.

**Comment by SumanSingh4** [comment]
Hi @tsonevn I have tried it. But not successful. Getting some errors while running.

failed to find "aws" module exception is showing.

I have few doubts.
do i have to separately install asw-sdk through npm?

**Comment by tsonevn** [comment]
Hi @SumanSingh4,
As it is described in the `nativescript-nodeif` plugins README, you should install one of the both npm plugins `aws-sdk` or `amazon-cognito-identity-js` for using Amazon Web Services.

Make sure also that you are using the latest version of NativeScript 2.5.4.
In the meantime, you could also try to remove `node_modules`, `platforms` and `hooks` folders and to rebuild again with `tns run <platform_name>`.

I noticed that you have logged an issue in the `nativescript-nodeif` plugins repo [here](https://github.com/EddyVerbruggen/nativescript-nodeify/issues/12). Let's keep the discussion in the other issue.
