### ISSUE TITLE
[Bug] fromAsset method will create an imageSource with wrong dimensions. 

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#3955]
This issue could be reproduced easily while using a `nativescript-camera` plugin and try to get the `imageSource` from the newly create `imageAsset`.

For example, if we have an asset with dimensions:
 width 2700 and height 2700, 
the image source will always be created with 
width 612 and height 816.

This issue is reproducible only on Android.
I am also attaching sample project, where this behavior could be reproduced.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/904752/Archive.zip)

**Comment by ju4nj3** [comment]
+1

Any solution, please?

**Comment by p-3** [comment]
+1

**Comment by gle6as** [comment]
On iOS too

**Comment by tsonevn** [comment]
The issue is no longer reproduced with the latest version of the nativescript-camera plugin `4.0.2` and tns-core-modules `4.1`. The case is tested with the [nativescript-camera demo](https://github.com/NativeScript/nativescript-camera/blob/master/demo).
