### ISSUE TITLE
Q: NativeScript - AirWatch - Get info from plist

### ISSUE THREAD

**Issue by AndersGerner** [NativeScript/NativeScript#3956]
I have a NativeScript app which is placed in an AirWatch custom App Store.

I have read (http://stackoverflow.com/questions/33400087/retrieving-username-through-mdm-by-configuring-enterprise-app-preferences-airwa) that you can get AirWatch configuration values by adding a dict to the info.plist

As in the example on stackoverflow - How would you in NativeScript retrive this kind of plist information? It seems that it needs to be in a separate Root.plist file

AirWatch info:
My Configuration key is "initial" and its a "string".

Thanks for any help on this :)

Working function to get version number:
```
function getAppInfo(key) {
  return new Promise(function(resolve, reject) {
    try {
      var mainBundle = utils.ios.getter(NSBundle, NSBundle.mainBundle);
      resolve(mainBundle.infoDictionary.objectForKey(key));
    } catch (ex) {
      console.log("Error in reading key: " + key + " : " + ex);
      reject(ex);
    }
  });
};

getAppInfo("CFBundleShortVersionString").then(function(data){
	console.log("Version:",data);
});
```

**Comment by NickIliev** [comment]
Hey @AndersGerner 

As far as I understood from [here](http://developer.air-watch.com/ios/airwatch-ios-sdk-setup-native/) all configuration settings are added to the main info.plist file. If that is the case you can simply reuse your **getAppInfo** method passing the key name (as the info.plist will be merged with the new values added by AirWatch)

**Comment by AndersGerner** [comment]
Hey @NickIliev 

Thanks for your reply! 

Just one question:

When a part of the plist XML looks like this:

```
<dict>
    <key>PreferenceSpecifiers</key>
    <array>
        <dict>
            <key>Key</key>
            <string>com.apple.configuration.managed</string>
            <key>DefaultValue</key>
            <dict>
                <key>initial</key>
                <string>ANONYMOUS</string>
            </dict>
        </dict>
    </array>
</dict>
```

What should I then parse to my getAppInfo ?
I have tried:
```
getAppInfo("com.apple.configuration.managed").then(function(data){
	console.log("initials:",data);
});
getAppInfo("initial").then(function(data){
	console.log("initials2:",data);
});
```

They are both "null".. I guess they should be "ANONYMOUS" when I'm testing locally :)

**Comment by NickIliev** [comment]
@AndersGerner your dictionary key is named **PreferenceSpecifiers** so you should grab it with 
```
getAppInfo("PreferenceSpecifiers").then(function(data){
	console.log(data);
});
```

Now if the value of your key is not string, but array with dictionary like the one in your example e.g.
```
<dict>
    <key>PreferenceSpecifiers</key>
    <array>
        <dict>
            <key>Key</key>
            <string>com.apple.configuration.managed</string>
            <key>DefaultValue</key>
            <dict>
                <key>initial</key>
                <string>ANONYMOUS</string>
            </dict>
        </dict>
    </array>
</dict>
```

Then keep in mind that the returned values are not marshaled so you will have to use the native iOS API to parse te result so in the example above to print the value of the key with name **MyValue** it will happen like this
```
getAppInfo("PreferenceSpecifiers").then(function(data) { 
    console.log(data.objectAtIndex(0).objectForKey["DefaultValue"].objectForKey["initial"].toString());
}
```
