### ISSUE TITLE
Nativescript tns create testapp --ng create the app but tns run android is not working

### ISSUE THREAD

**Issue by abhisekgithub** [NativeScript/NativeScript#3964]
I have created the nativescript app with tns version 2.3.0
as `tns create myapp --ng`
then I tried to execute the command
`tns run android` and the below error show

```
D:\androidproject\NativeScript\MyNextGreatApp>tns run android
Executing before-prepare hook from D:\androidproject\NativeScript\MyNextGreatApp
\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.2.2
node_modules/tns-core-modules/declarations.d.ts(3,15): error TS2300: Duplicate i
dentifier 'Request'.

node_modules/tns-core-modules/declarations.d.ts(17,5): error TS2403: Subsequent
variable declarations must have the same type.  Variable 'headers' must be of ty
pe 'any', but here has type 'string[] | Headers | { [index: string]: string; }'.


node_modules/tns-core-modules/declarations.d.ts(19,5): error TS2403: Subsequent
variable declarations must have the same type.  Variable 'mode' must be of type
'string', but here has type 'RequestMode'.
node_modules/tns-core-modules/declarations.d.ts(20,5): error TS2403: Subsequent
variable declarations must have the same type.  Variable 'credentials' must be o
f type 'string', but here has type 'RequestCredentials'.
node_modules/tns-core-modules/declarations.d.ts(21,5): error TS2403: Subsequent
variable declarations must have the same type.  Variable 'cache' must be of type
 'string', but here has type 'RequestCache'.

node_modules/tns-core-modules/declarations.d.ts(36,15): error TS2300: Duplicate
identifier 'Headers'.
node_modules/tns-core-modules/declarations.d.ts(46,5): error TS2687: All declara
tions of 'bodyUsed' must have identical modifiers.
node_modules/tns-core-modules/declarations.d.ts(56,15): error TS2300: Duplicate
identifier 'Response'.

node_modules/tns-core-modules/declarations.d.ts(72,5): error TS2687: All declara
tions of 'status' must have identical modifiers.
node_modules/tns-core-modules/declarations.d.ts(73,5): error TS2687: All declara
tions of 'statusText' must have identical modifiers.
node_modules/tns-core-modules/declarations.d.ts(74,5): error TS2403: Subsequent
variable declarations must have the same type.  Variable 'headers' must be of ty
pe 'any', but here has type 'HeaderInit'.
node_modules/tns-core-modules/declarations.d.ts(74,5): error TS2687: All declara
tions of 'headers' must have identical modifiers.

node_modules/tns-core-modules/declarations.d.ts(78,14): error TS2300: Duplicate
identifier 'BodyInit'.
node_modules/tns-core-modules/declarations.d.ts(79,14): error TS2300: Duplicate
identifier 'RequestInfo'.

node_modules/typescript/lib/lib.d.ts(5327,5): error TS2687: All declarations of
'status' must have identical modifiers.

node_modules/typescript/lib/lib.d.ts(5328,5): error TS2687: All declarations of
'statusText' must have identical modifiers.
node_modules/typescript/lib/lib.d.ts(5329,5): error TS2687: All declarations of
'headers' must have identical modifiers.
node_modules/typescript/lib/lib.d.ts(11168,11): error TS2300: Duplicate identifi
er 'Headers'.
node_modules/typescript/lib/lib.d.ts(11177,13): error TS2300: Duplicate identifi
er 'Headers'.
node_modules/typescript/lib/lib.d.ts(13566,11): error TS2300: Duplicate identifi
er 'Request'.
node_modules/typescript/lib/lib.d.ts(13583,13): error TS2300: Duplicate identifi
er 'Request'.
node_modules/typescript/lib/lib.d.ts(13588,11): error TS2300: Duplicate identifi
er 'Response'.
node_modules/typescript/lib/lib.d.ts(13599,13): error TS2300: Duplicate identifi
er 'Response'.
node_modules/typescript/lib/lib.d.ts(17714,14): error TS2687: All declarations o
f 'bodyUsed' must have identical modifiers.
node_modules/typescript/lib/lib.d.ts(19121,6): error TS2300: Duplicate identifie
r 'BodyInit'.
node_modules/typescript/lib/lib.d.ts(19152,6): error TS2300: Duplicate identifie
r 'RequestInfo'.

TypeScript compiler failed with exit code 1
Sending exception report (press Ctrl+C to stop).....
```

**Comment by Cae2** [comment]
I dont think that tns 2.3.0 is compatible with typescript 2.2.2, arent you using tns@rc?

post your package.json please

**Comment by tsonevn** [comment]
Hi @abhisekgithub, 
@Cae2  is right the NativeScript  version 2.3.0 is not compatible with TypeScript 2.2.2. This TypeScript version will be supported with the [upcoming release 3.0.](https://www.nativescript.org/blog/nativescript-3.0-release-candidate-available-today)
In the meantime, you could [upgrade to the latest official version 2.5.4](https://docs.nativescript.org/releases/upgrade-instructions) and to downgrade the typescript version to 2.1.5.
Then you should be able to create and build a new project while following the below-attached steps.

**Comment by harriscreativity** [comment]
g3r7ev2
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at org.gradle.wrapper.Install.unzip(Install.java:215)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:75)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessMana
ger.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Processing node_modules failed. Error: Command ./gradlew failed with exit code 1

this is what i am getting as an error on android

**Comment by tsonevn** [comment]
Hi @abhisekgithub,
Could you delete `platforms` and `node_modules` folders from the app and try to rebuild it with `tns run android`? If this does not help, can you give us the exact steps you are following, while creating a new project?
It would also help if you can give us info about the NativeScript version, you are using: `2.5` or if you are using our Release Candidate.

**Comment by vjoao** [comment]
I have Typescript 2.2.2 installed and I'm using TNS@2.5.4 with angular just fine.
