### ISSUE TITLE
Google Sign In throwing error response 

### ISSUE THREAD

**Issue by maniacube** [NativeScript/NativeScript#3968]
Hi,

I am using "nativescript-social-login" plugin for google sign in, everything works on iOS but not on Android. No errors or anything just throwing following response.

"{"provider":"google","code":1}"

Please help us to resolve it.

**Comment by NickIliev** [comment]
Hey @maniacube as nativescript-social-plugin is a plugin developed by a community member and not the nativeScript team please post your issue n [the repository of the plugin](https://github.com/mkloubert/nativescript-social-login) (where you could receive the best guidence)
