### ISSUE TITLE
Feature request: text-stroke property and/or text-shadow

### ISSUE THREAD

**Issue by ickata** [NativeScript/NativeScript#3972]
Hi {N} team,

I wonder if it is technically possible on both platforms and have you got any plans implementing `text-stroke`, and/or `text-shadow` CSS properties? The `text-shadow` is a valid CSS property. `text-stroke` as well, however some vendors support it with prefix (e.g. `-webkit-text-stroke`). 

I need to add outline to text. Semantically `text-stroke` is what I need, but `text-shadow` also does the job when used like this `text-shadow: 0 0 red`.

I'll be happy to know if there is some workaround in tns 2.5 to achieve this.

Thanks!

**Comment by NordlingArt** [comment]
I explained a possible [workaround here](https://github.com/NativeScript/NativeScript/issues/3597#issuecomment-278889890) for iOS. However, it somewhat doesn't render the outline even though it should.

**Comment by tsonevn** [comment]
Hi @ickata,
A similar issue for `text-shadow` support has been logged [here](https://github.com/NativeScript/NativeScript/issues/3597). Please if you have some further suggestions comment on the other issue.

**Comment by AdityaChoudhary** [comment]
+1

**Comment by NathanWalker** [comment]
Reopening - we will be supporting this in the next minor release of core.
