### ISSUE TITLE
Passing Params in ios

### ISSUE THREAD

**Issue by harriscreativity** [NativeScript/NativeScript#3974]
there is some delay and sometimes it is taking so long to go to the itemdetailcomponent when u run the app on ios emulators please fix

**Comment by tsonevn** [comment]
Hi @harriscreativity,
Could you provide some more info about your case and the issue which you are facing with?
It would also help if you could give us some more info about your environment(`CLI`, `tns-core-modules` versions) and sample project, which could be debugged locally.
