### ISSUE TITLE
Dynamic SegmentedBar is it possible?

### ISSUE THREAD

**Issue by bachras** [NativeScript/NativeScript#3976]
Hi all, 

I am using code from here (https://github.com/NativeScript/NativeScript/issues/2519  and http://www.nativescriptsnacks.com/snippets/2016/06/22/angular-segmentedbar.html) and everything works fine. I would like to implement segmentedBar based on the data I retrieve from server. I tried to implement that in constructor, but by the time response from server comes i have an error : selectedIndex should be between [0,-1].  I am relatively new to nativescript and angular 2, so any help would be highly appreciated. Thanks

**Comment by tsonevn** [comment]
Hi @bachras,
In your case,  SegmentedBar is not the applicable component. The items of the component should be available in the execution of the constructor or on ngOnInit. 
In this scenario, if you will display a few items you could use ngFor directive as it has been shown in [this](http://stackoverflow.com/questions/40667899/nativescript-angular-how-to-pass-a-button-view-as-a-parameter-in-tap-event/40671850#40671850) thread in StackOverflow.

For further `How to` questions you can use our NativeScript [forum](https://discourse.nativescript.org/).

**Comment by bachras** [comment]
Thank you for prompt reply @tsonevn. I will try do that.
