### ISSUE TITLE
Open DatePicker / TimePicker dynamically

### ISSUE THREAD

**Issue by longpham91** [NativeScript/NativeScript#398]
I'm just wondering if it'd be easy to add something like this to NativeScript, so that a DatePicker can be easily initialized and opened by an event, i.e. a button tap.

**Comment by enchev** [comment]
You can place desired picker in modal page and show the page when needed [using showModal()](https://github.com/NativeScript/NativeScript/blob/master/apps/modal-views-demo/main-page.ts#L15)

**Comment by longpham91** [comment]
Thanks. That was useful!

**Comment by EricRobertBrewer** [comment]
Above link moved to [modal-view](https://github.com/NativeScript/NativeScript/blob/master/apps/app/ui-tests-app/modal-view/modal-view.ts).
