### ISSUE TITLE
Tab View

### ISSUE THREAD

**Issue by praven07** [NativeScript/NativeScript#3985]
I used the nativescript tabview snippet that comes for visual studio code. And it produced this snippet.

```
<TabView #tabView>
  <TabViewItem title="Tab 1">
    <Label text="This is Label in Tab 1"></Label>
  </TabViewItem>
  <TabViewItem title="Tab 2">
    <Label text="This is Label in Tab 2"></Label>
  </TabViewItem>
</TabView>
```

It does not display the tab view properly.
Here is the screen shot.
![screen shot 2017-04-12 at 5 29 46 pm](https://cloud.githubusercontent.com/assets/2223191/24982175/b022fe08-1fa5-11e7-9592-877297d4a2f7.png)

**Comment by tsonevn** [comment]
Hi @praven07,
Could you provide some more info about the case and whether you are using a NativeScript Angular template or pure NativeScript TypeScript one?
In the NativeScript Angular 2 project, the syntax for defining TabView is different. 
For example:
```
<TabView>
    <StackLayout *tabItem="{title: 'Profile', iconSource: '~/icon.png'}" >
        <ListView [items]="items">
            <template let-item="item">
                <Label [text]="item.itemDesc"></Label>
            </template>
        </ListView>
    </StackLayout>
    <StackLayout *tabItem="{title: 'Stats'}">
        <Label text="Second tab item"></Label>
    </StackLayout>
    <StackLayout *tabItem="{title: 'Settings'}">
        <Label text="Third tab item"></Label>
    </StackLayout>
</TabView>
```
Also you could review the docs [here](https://docs.nativescript.org/cookbook/tab-view-ng).
