### ISSUE TITLE
Q: How to reload a webview?

### ISSUE THREAD

**Issue by AndersGerner** [NativeScript/NativeScript#3986]
Hello NativeScript guys :)

I have tried for days to get my webview to reload the current page, but nothing seems to be working.

I'm bulding my app based on this github project: https://github.com/shripalsoni04/nativescript-webview-interface

I have setup the webview with this local file: ~/www/index.html

I have tried:
* `webview.reload()` (Nothing works)
* `webview.src = "<h1>LOADING</h1>"; webview.src = "~/www/index.html"` (This can work on emulator, not device)
* `webviewinterface.destroy(); webviewinterface = new webviewinterface(webview,"~/www/index.html")` (Working on emulator, not device)

Can anybody help me?

**Comment by tsonevn** [comment]
Hi @AndersGerner,
Thank you for contacting us. 
I tested your case on my side, however, was unable to reproduce issues with reloading the WebView content.
For your convenience, I created two sample projects. In the first one, I have used pure NativeScript WebView and there I just replace the source of the component and everything seems to be reloaded properly.
[pure_webview_test.zip](https://github.com/NativeScript/NativeScript/files/918819/pure_webview_test.zip)

On the second one, I used `nativescript-webview-interface`.
[nativescript-webview-interface_test.zip](https://github.com/NativeScript/NativeScript/files/918820/nativescript-webview-interface_test.zip)

Could you review the both apps and make the needed changes, which will allow us to recreate the problem?
It would also help if you could provide some more info about your environment(CLI, modules versions) and info about the device, which you are using for testing.

**Comment by AndersGerner** [comment]
Thank you so much @tsonevn ! I'll have a look at it and get back to you.

**Comment by AndersGerner** [comment]
@tsonevn I have looked at you code. 
It seems that the code only updates the src on the webview. 

I can also get the webview to have a src and then change it to another. But I need it to reload the current page its on. I'm running a SingePageApplication in the webview, and it needs to be reloaded .

So the src of my webview is ~/www/index.html and it just needs to reload that page, just like location.reload would do in a browser.

I'm sorry if I have misunderstood something from you reply/code, but then please explain. :)

**Comment by tsonevn** [comment]
Hi @AndersGerner,
Excuse me for the misunderstanding. 
Indeed at the moment `WebView`  `reload` will not reload current page, while loading the component source from local `HTML` file. 

We will research what is causing this issue and will provide the appropriate fix.
For your convenience, I am attaching sample app, where this behavior could be reproduced.
[webview_reload_issue.zip](https://github.com/NativeScript/NativeScript/files/919920/webview_reload_issue.zip)

**Comment by AndersGerner** [comment]
@tsonevn Thank you very much! Your help is really appriciated.

I don't mean to sound like a jerk, but do you have any kind of ETA on this? I'm just curious if there are a lot other issues to be resolved before mine :)

**Comment by AndersGerner** [comment]
@tsonevn Any news? :)

**Comment by tsonevn** [comment]
Hi @AndersGerner, 
I will research, whether there is a possible workaround for this case. I will write you back as soon as I have some additional info about this.

**Comment by mn-martin** [comment]
This works great for me: 

```ts
function reloadWebview(page: Page, webview: WebView): void {
    if (isString(webview.url) && webview.url.length > 0) {
        webview.reload();
    } else {
        // webview.reload() wouldn't do the trick because the url is lost
        // due to an error that occurred on the initial load
        webview.stopLoading();
        webview.url = page.navigationContext.url;
    }
}
```

**Comment by tsonevn** [comment]
Hi @AndersGerner,
I tested the suggested workaround from @mn-martin  and it seems to work as expected. 

For you convenience, I am also attaching sample project with the workaround:
[Archive.zip](https://github.com/NativeScript/NativeScript/files/958617/Archive.zip)
