### ISSUE TITLE
Research on the use of Google's Material Design library in NativeScript

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#399]
Recently Google released their Design Support library which brings several components that implement the Material Design guidelines. We should decide whether we will base our Android implementation on this library or if it will be optional how it will be consumed - e.g. how the NativeScript default TabBar component in Android will get the "Material design" look and feel.

**Comment by valentinstoychev** [comment]
Based on my conversation with our designer @NinaZayakova we should make the Material design look and feel by default in NativeScript.

**Comment by RangerMauve** [comment]
Would that look and feel extend to iOS apps?

**Comment by bfattori** [comment]
I'm thinking not... unless someone wants to implement it.

**Comment by alejonext** [comment]
+1

**Comment by valentinstoychev** [comment]
@RangerMauve - nope, it is not for iOS. It is only about making the default look and feel of the Android app UI to be by the material design guidelines.

**Comment by sitefinitysteve** [comment]
+1 for Material default

**Comment by paranoid-android** [comment]
+1 for Material Design

I would LOVE to see Material Design as a [theme](https://github.com/NativeScript/NativeScript/issues/253) if not the default look of NativeScript apps.

**Comment by bradmartin** [comment]
Huge +1 for this. Will give android nativescript apps a huge bonus for keeping up to the default platform specs.

**Comment by lscown** [comment]
We'd love to see this, as it'd save us a lot of time. :+1:

**Comment by fela98** [comment]
Would LOVE to see this :+1:

**Comment by shripal04** [comment]
:+1:  for default material design look and feel for android.

**Comment by prijindal** [comment]
:+1: for this

**Comment by atanasovg** [comment]
Since 1.3 this is already available. It still requires a manual step but it can be easily implemented:

1. Go to `platforms/android` folder
2. Modify the `build.gradle` script and add the following line (after line 126):

    ``` 
    compile 'com.android.support:design:$suppotVer'
    ``` 

For 1.4 we will try to figure out a smarter way to do this. NativeScript/android-runtime#223.

**Comment by toddanglin** [comment]
Can you provide a simple example of how you'd use the Material Design widgets after making this change to the `build.gradle` file?

Will built-in NativeScript widgets like the ActionBar automatically use Material Design if this reference is present?

**Comment by bradmartin** [comment]
Yes I need some info on how to include this. I made the cradle change but
don't think anything material is done by default. Maybe a styles change for
theme is needed..

**Comment by bradmartin** [comment]
@toddanglin - doing what @atanasovg suggested in the gradle file does include the support library to use some components of material design. Adding this, I believe, causes some issues with styling. I think this is due to {N} abstracting a lot of styling internally for the nativescript widgets. So you might need to start working with styles.xml and colors.xml in your resources/value folders to get the native look.

At any rate adding that in and running the app on a 5.0 device I see several material design effects take place.

**Comment by x4080** [comment]
Already included in 1.4?

**Comment by prijindal** [comment]
How do we use the solution provided by @atanasovg .
Can anyone give an example by using some material design component

**Comment by bradmartin** [comment]
Some components should adapt, I believe. I added the gradle step and the
tabs component has the sliding bar for the selected tab which I believe is
the material design style. Someone else can chime in with more
understanding but that's what I've found

**Comment by amjd** [comment]
Is this included in 1.4? If yes, any information on how to use it?

**Comment by benjick** [comment]
Anything new on this? On the fence if I should use nativescript or not

**Comment by atanasovg** [comment]
A quick clarification - there are two aspects of the Material Look-and-feel:

- The [Material Theme](http://developer.android.com/training/material/theme.html)
- The [Google's Design Support Library](http://android-developers.blogspot.bg/2015/05/android-design-support-library.html)

The first one is a set of styles, applicable to all Android components when running on Android 5.0+. And the default {N} application project template will use the Material Theme when running on API level 21+.

The second one is a collection of widgets, implemented with the Material Design in mind, which complement the Material paradigm in Android. These are components still to enable in the {N} modules.

**Comment by valentinstoychev** [comment]
And just to note that while the components from the Design library are not part of the {N} modules you can still use them by adding the Design library as a 3rd party reference to your NativeScript project. I know for example that @bradmartin is using the SnackBar UI component from the Design library. This is probably a good call for a blog post.

**Comment by bradmartin** [comment]
@valentinstoychev - just did this http://bradmartin.net/2015/12/08/how-to-use-material-design-snackbar-in-a-nativescript-app/ for the snackbar. It could be improved. Feel free to check it out. If you do a post, maybe you could tackle the Palette() and Palette.Builder() stuff. I haven't circled back to that just yet but would be great to have.

**Comment by bradmartin** [comment]
Anyone needing the FAB button: http://bradmartin.net/2015/12/23/how-to-use-material-design-fab-floating-action-button-in-a-nativescript-app/

**Comment by bradmartin** [comment]
This is the CardView component. 

https://www.npmjs.com/package/nativescript-cardview

I also have worked on FAB button and Snackbar plugins and have wrote a blog post on using the Palette class in Android apps. The team has fixed the button ripple effect by changing the background color method used on buttons and it should be in 1.6 so lollipop devices will retain their ripple effect when you color the background of a button. Not sure if they changed other components or not.

**Comment by x4080** [comment]
Good job Brad

**Comment by vjoao** [comment]
+1 on Material default.

**Comment by laguiz** [comment]
+1  for this. Would give a big boost to Android.

**Comment by toddanglin** [comment]
What's the state of Material Design in NativeScript now that this is closed?

**Comment by enchev** [comment]
We are now able to use Material Design in NativeScript which was not possible at the time when the issue was logged. We have several blogs and components from the community and I believe that we no longer need to "research" anything. :)

**Comment by thinkblue36** [comment]
+1

**Comment by prijindal** [comment]
I think we can do this by using individual widgets/components in our script.
But there are not much tutorials/resources on how to do that.
Only one that i see are some of the tutorials provided by @bradmartin.
And by reading his tutorial it seems it is possible to use material design in nativescript but it just needs to be documented correctly

**Comment by bradmartin** [comment]
Most of the components are already plugins. There are just a few things
lacking from the MD spec with NativeScript but overall you can have a great
material design NativeScript app.

**Comment by prijindal** [comment]
Can we have a list of these components?

**Comment by cecilphillip** [comment]
Looks like good is creating a common set of material components for android, ios and the web https://github.com/material-components

**Comment by valentinstoychev** [comment]
I'm sure these will make an easy and great nativescript plugin!

**Comment by geminiyellow** [comment]
is there some news in here?

anybody can tell me how to apply something like https://github.com/material-components to nativescript ?

**Comment by samrantmedia** [comment]
1. Download nativescript sidekick 1.0. 
2. Create new project
3. click 'plugins'
4. in 'Available', search for 'Material'. 
5. click the one you are interested in and select 'Open link' next to homepage to see more information
6. if it is alright, click 'Install'.
