### ISSUE TITLE
iOS: How to Implement uidocumentmenuviewcontroller ios

### ISSUE THREAD

**Issue by pap5508** [NativeScript/NativeScript#3990]
How can I implement uidocumentmenuviewcontroller ???
![d4z66](https://cloud.githubusercontent.com/assets/8488715/25005009/600d0adc-2057-11e7-9976-d65c98a4eb92.png)

**Comment by NickIliev** [comment]
Please address similar questions in the community channels like [forum.nativescript.org](https://discourse.nativescript.org/) so we can keep this repository strictly for issues, bug and feature related threads.
