### ISSUE TITLE
http module timeout doesn't work on Android

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/NativeScript#3991]
The below code works perfectly on iOS but fails on Android. No matter what `timeout` is passed to the http module, the value seems to be ignored.

If there is no network connection (airplane mode for example) then the error callback is fired immediately but on a slow connection it is not. The actual time taken for the request to timeout seems to be completely random. On a real device the callback runs after ~20 seconds. In the emulator it runs after ~2 minutes.

    var httpModule = require("http");

    httpModule.request({
        url: "https://httpbin.org/get",
        method: "GET",
        timeout: 1000
    }).then(function (response) {
        console.log('Network reachable!');
        var statusCode = response.statusCode; 
    }, function (e) {
        console.log('Network unreachable!');
    });

I'm testing this using the Android emulator and Apple's Network Link Conditioner. On a real device I'm testing by connecting to an iOS device hot spot and using the iOS version of Network Link Conditioner.

```
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 2.5.4           │ 2.5.4          │ Up to date  │
│ tns-core-modules │ 2.5.2           │ 2.5.2          │ Up to date  │
│ tns-android      │ 2.5.0           │ 2.5.0          │ Up to date  │
│ tns-ios          │ 2.5.0           │ 2.5.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

**Comment by tsonevn** [comment]
Hi @3rror404,
Thank you for reporting this issue.
I reviewed that case and was able to reproduce this behavior while using our official modules ` 2.5.4` and `@rc`. We will research this problem and will provide the needed fix. For further info, you could keep track on the issue.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/928855/Archive.zip)

For your convenience, I am also attaching sample project, where the issue could be reproduced.

**Comment by 3rror404** [comment]
Thanks @tsonevn.

I know very little Java, but perhaps this is related: http://stackoverflow.com/a/6830053/746736

**Comment by 3rror404** [comment]
This is actual proving to be a bit of a problem for me. If anyone has any ideas on how to patch core-modules-widgets before an official fix is released I'd really appreciate some help.

Adding `connection.setReadTimeout(options.timeout);` at line 418 of Async.java works for the first one or two times `httpModule.request()` is used but then doesn't after.

**Comment by 3rror404** [comment]
I think there are a couple of issues here. 

In Async.java `connection.setConnectTimeout(options.timeout)` is used but `setReadTimeout` also needs to be used otherwise a slow connection will not timeout in the provided `timeout`.

This works _sometimes_. The reason it fails other times seems to be that a DNS lookup is done before the `HttpURLConnection` is triggered. This throws a `java.net.UnknownHostException` after ~20 seconds. I'm not sure why this happens on occasion and not every time.

I tried to do something with `InetAddress.getByName(url).isReachable(options.timeout)` before opening the `HttpURLConnection` connection  but this always throws a `java.net.UnknownHostException` even when connected to a network.

Here is my modified Async.java https://gist.github.com/3rror404/8a81a24980ca186686729725315b54f4

**Comment by tsonevn** [comment]
Hi @3rror404,
Regarding the first question, you could build locally `tns-core-modules-widgets` on your side by using the `build` shell script, which will generate `tgz` file in the `dist` folder. You could also review the instructions [here](https://github.com/NativeScript/tns-core-modules-widgets).

In case you have some appropriate solution for this scenario you could create your pull request in `tns-core-modules-widgets` repository. We will review it and will merge it if all test passed.

**Comment by 3rror404** [comment]
Just wondering if anyone has had chance to look into this yet? This issue is holding up my release and I'm not able to find a solution myself.

**Comment by tsonevn** [comment]
Hi @3rror404,
I have just tested this case with HTTP module `timeout` option with @rc CLI and Modules and Runtime on Android device and it seems to work.
If you set small timeframe, for example, 100 milliseconds, you will see that the request will be dismissed and the callback method for `Network unreachable` will be fired. 
You could download the attached sample app and tested on your side by using [@rc CLI](https://www.nativescript.org/blog/nativescript-3.0-release-candidate-available-today).

[Archive.zip](https://github.com/NativeScript/NativeScript/files/954708/Archive.zip)

**Comment by carrbrpoa** [comment]
Is it possible to call `InetAddress.getByName(url).isReachable(options.timeout)` from NativeScript, or is it "ported" yet?
