### ISSUE TITLE
search name list character by character

### ISSUE THREAD

**Issue by SumanSingh4** [NativeScript/NativeScript#3993]
Hi

I want to search array list of users name, character by character like if I type A then it must shotlist the array having name started with A or a or so on......

I other language we use "A%". I have try these but not working.

Please can any one explain how to do these with small demo.

Thanks

**Comment by NordlingArt** [comment]
You can do it this way:

```js
const users = [
  { id: 1, name: "John" },
  { id: 2, name: "Johnny" },
  { id: 3, name: "Timmy" }
];

const searchQueryString = "J";

function searchUser(queryString) {
  // Make the query string case-insensitive
  queryString = queryString.toLowerCase();  

  return users.filter(user => {
    // Make user's name case-insensitive
    const name = user.name.toLowerCase();
    
    // Will return true or false depending if the query string matches the user's name
    return name.indexOf(queryString) >= 0;
  });
}
```

**Comment by tsonevn** [comment]
Hi @SumanSingh4 
Thank you for your interest in NativeScript,
For your case, you could use the given @NordlingArt solution, which will allow you to filter the array while comparing every character in the names.

Please for further `How to questions` use our NativeScirpt forum [here](https://discourse.nativescript.org/).
