### ISSUE TITLE
library "exports" don't work as expected.

### ISSUE THREAD

**Issue by Nathanaela** [NativeScript/NativeScript#40]
If I create a file "mymodule.js"
```
var someFunction = function() { console.log("MyModule"); }
exports = someFunction;
```

// In another file
```
var someFunction = require('mymodule')
var a = new someFunction();
```
This will crash on "new someFunction" as it throws an error "TypeError: object is not a function"

This does work in node.js and allows simpler modules...

**Comment by slavchev** [comment]
Hi,

the actual code in `mymodule.js` should be

```JavaScript
var someFunction = function() { console.log("MyModule"); }
module.exports = someFunction
```

**Comment by Nathanaela** [comment]
Interesting -- all the sample & real code you guys wrote just use "exports".   For example; I downloaded nativescript-phone as a sample; and also looked at the built in code under the tns_modules; and they all use:   
```javascript
exports.name = name;
```

For nativescript; what is the difference between:
   module.exports vs exports

**Comment by Nathanaela** [comment]
I can confirm this does fix it.     Using "module.exports" works as expected.  Using just plain "exports" does not.    

Is their any documentation detailing the differences between these two methods as "exports" is what is used everywhere in the tns_modules; other samples, and even the "new" application template uses "exports" which is why I assumed "exports" was .the proper method.

**Comment by slavchev** [comment]
The current module implementation is based mostly on CommonJS specification. We also adopted some things like `__dirname` and `__filename` from Node.js.

http://wiki.commonjs.org/wiki/Modules/1.1
https://nodejs.org/api/modules.html

**Comment by Nathanaela** [comment]
Wow, now I feel stupid.  ;-)       I've been developing on Node for ages --  and I never knew about the "exports" variables.   Thanks for the pointer; the node docs have been very informative.    And know I understand why, so thanks again!
