### ISSUE TITLE
android-sdk not installed

### ISSUE THREAD

**Issue by wolfgangmeyers** [NativeScript/NativeScript#4000]
I ran the mac setup script for android/ios deps from http://docs.nativescript.org/start/quick-setup:
`ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)"`
Ran into this problem when running the script:

```
Error: No available formula with the name "android-sdk"
It was migrated from homebrew/core to caskroom/cask.
You can access it again by running:
  brew tap caskroom/cask
WARNING: Android SDK not installed
checking for android... no
```

**Comment by dtopuzov** [comment]
It is known (issue)[https://github.com/NativeScript/nativescript-cli/issues/2125] that we will fix in next days.
