### ISSUE TITLE
add AWS Support

### ISSUE THREAD

**Issue by simplicii** [NativeScript/NativeScript#4005]
Nativescript and Amazon MobileHub is a DreamTeam, but unfortunately there is not Nativescript SDK from Amazon and [](https://github.com/EddyVerbruggen/nativescript-nodeify) doeas not work for me with Android 4, node 7.9 npm 4.5.

It would be amazing if you can add support for Amazon AWS. 
Although it would be another selling point for NativeScript.

**Comment by bradmartin** [comment]
Should be possible with some work outlined here: https://github.com/EddyVerbruggen/nativescript-nodeify/blob/master/README.md#aws-sdk-or-amazon-cognito-identity-js-which-includes-aws-sdk

**Comment by simplicii** [comment]
Yes, but very unstable. With nativescript-nodeify I have to delete the node_modules folder several times a day because it messes up something in there. Also this is a project backed by one (1) man. If he looses interest everyone using it is left alone.

It would be good if Nativscript (Telerik) would support nativescript-nodeify.

Actually it would be best if Amazon itself would provide a Nativescript-SDK, but this is maybe too much of a wish.

**Comment by bradmartin** [comment]
Understandable :)

The most likely option is to consume the SDK yourself in your app. Then you
don't depend on anyone. I've never checked does Amazon provide native sdks?
If so do you have the links? Thanks

**Comment by simplicii** [comment]
Ok, finally I can connect. If there is a build error "nativescript-nodeify" will create an "Cannot find module 'file-system/file-system-access'", then you need to delete the whole node_modules folder.

https://www.npmjs.com/package/aws-api-gateway-client

https://www.npmjs.com/package/aws-sdk
and amazon-cognito-identity-js

**Comment by tsonevn** [comment]
Hi @simplicii,
I am glad to hear that you have resolved the problem and that you was able to connect to the Amazon service.
Regarding the topic, if the available plugins are not applicable, you could use the available [native SDK](https://aws.amazon.com/mobile/sdk/) provided from Amazon as @bradmartin  suggested and implement the needed functionality while using it.
Something more, you could create your own plugin. For further info, you could review the below-attached articles.

https://docs.nativescript.org/plugins/plugins
http://developer.telerik.com/featured/write-nativescript-plugins-theyre-easier-cordova-plugins/
http://developer.telerik.com/featured/creating-nativescript-plugins-in-typescript/
http://fluentreports.com/blog/?p=167
