### ISSUE TITLE
NS 3.0: ngOnInit() <component>.android is undefined.

### ISSUE THREAD

**Issue by Abdumama** [NativeScript/NativeScript#4006]
**### Tell us about the problem**
I'm trying to access at the native API of the **TextField** component in the **ngOnInit** method but _**.android**_ returns _**undefined**_.

**### Which platform(s) does your issue occur on?**
Android

**### Please provide the following version numbers that your issue occurs with:**
- CLI: 3.0.0-rc.1
- Cross-platform modules: 3.0.0-rc.2

**### Please tell us how to recreate the issue in as much detail as possible.**

**test.component.html**
`<TextField #username id="username"></TextField>`

**test.component.ts**
```
@ViewChild("username") usernameTextField: TextField;

ngOnInit() {
	console.log(this.usernameTextField.android); // undefined
	console.log(this.page.getViewById("username").android); // underfined
}
```

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#757
