### ISSUE TITLE
Q: How would you rewrite this Obj-C to {N} ?

### ISSUE THREAD

**Issue by AndersGerner** [NativeScript/NativeScript#4011]
This it not an issue but a request for help :)

How would you rewrite this Obj-C code to {N} ?

```
-(NSString*)getUserFullName;{
    NSString * kConfigurationKey = @"com.apple.configuration.managed";
    NSDictionary *mdmConfig = [[NSUserDefaults standardUserDefaults] dictionaryForKey:kConfigurationKey];
    NSString *temp = mdmConfig[@"userFullName"];
   
    if (temp && [temp isKindOfClass:[NSString class]])
    {
        return temp;
    } else {
        return @"";
    }
   
}
```

My first version is:

```
try {
	let kConfigurationKey = "com.apple.configuration.managed";
	let defs = NSUserDefaults.standardUserDefaults();
	let mdmConfig = defs.dictionaryForKey(kConfigurationKey);
    	return mdmConfig["userName"];
}catch(err) {
    	console.dir(err)
}
```

I can't test this more than twice, so that's why I ask for help, instead of just debugging my way through it :)

**Comment by NordlingArt** [comment]
That's pretty much how I would do it :)

**Comment by AndersGerner** [comment]
@NordlingArt Got this:

`TypeError: NSUserDefaults.standardUserDefaults is not a function. (In 'NSUserDefaults.standardUserDefaults()', 'NSUserDefaults.standardUserDefaults' is an instance of NSUserDefaults)`

Tried to change defs. 
`let defs = NSUserDefaults.standardUserDefaults();`

and got: `TypeError: null is not an object (evaluating 'mdmConfig["userName"]')`

This could be because the data is not present in my current version, but I just need to be sure, so I hope get it to work the first time :)

**Comment by NordlingArt** [comment]
@AndersGerner - As of iOS10, a lot of native method became instances instead, as the error states. Remove the function call of `standardUserDefaults()` so it becomes:

`let defs = NSUserDefaults.standardUserDefaults`

**Comment by AndersGerner** [comment]
@NordlingArt Oh, sorry, that was what i meant in the last comment.

I changed it to:
`let defs = NSUserDefaults.standardUserDefaults;`

and then got this error: `TypeError: null is not an object (evaluating 'mdmConfig["userName"]')`

Do you know how I should "query" it? I have assumed its an array :)

Do you know on any data which is always being stored in "standardUserDefaults" ? Then I can test it with that data :)

**Comment by NordlingArt** [comment]
@AndersGerner - Ah, I see! I believe the AppSettings module utilises `NSUserDefault` in a [different way](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/application-settings/application-settings.ios.ts). Perhaps this will make it return an array instead of `null`.

```js
const utils = require("utils/utils");
let defs = utils.ios.getter(NSUserDefaults, NSUserDefaults.standardUserDefaults);
```

**Comment by AndersGerner** [comment]
@NordlingArt Like this? :)

```JS
let defs = utils.ios.getter(NSUserDefaults, NSUserDefaults.standardUserDefaults);
let kConfigurationKey = "com.apple.configuration.managed";
let mdmConfig = defs.dictionaryForKey(kConfigurationKey);
userInfo["userName"] = mdmConfig["userName"];
```

**Comment by AndersGerner** [comment]
Solved here: https://discourse.nativescript.org/t/converting-obj-c-code-to-n/1071/8
