### ISSUE TITLE
[TNS 3.0 RC] Unable to disable layout view's clipToBounds

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#4016]
**Platform:** iOS
**TNS:** 3.0 RC

I am unable to disable `clipToBounds` on a view:

```js
const GridLayout = require("ui/layouts/grid-layout").GridLayout;
const StackLayout = require("ui/layouts/stack-layout").StackLayout;
const view = new GridLayout();
const subView = new Label();

subView.text = "foo";
subView.translateY = -50;
view.addChild(subView);

view.clipToBounds = false;

// Let's make sure the native property is set to false as well.
if(view.ios) {
  view.ios.clipsToBounds = false;
}
```

The `subView` is still clipping out of bounds.

**Comment by tsonevn** [comment]
Hi @NordlingArt,
I tested this scenario on my side and everything seems to work as expected. 
For your convenience, I am attaching sample project and screenshot from the Simulator.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/932598/Archive.zip)
![screen shot 2017-04-19 at 11 08 07 am](https://cloud.githubusercontent.com/assets/17448734/25169793/047843c8-24f1-11e7-9d9a-d5b38f74adcf.png)

If you still have a problem, please provide sample project, which could be debugged locally.

**Comment by NordlingArt** [comment]
@NickIliev - Seems to work yes. I think this was somehow related to #4046 which also froze a property. I'll re-open this issue if it occurs again. Thank you for looking into this!
