### ISSUE TITLE
Typescript compiler fails in new project from template

### ISSUE THREAD

**Issue by DanielKucal** [NativeScript/NativeScript#4023]
I'm trying to integrate nativescript with my Angular project since a week and I face a lot of issues, but this one seems just ridiculous.

## Please, provide the details below:
I can't run `tns run ios` from **brand new project from template**! I guess it's partially related to typescript/nativescript behavior looking for files in parent directory - how can I turn it off as a temporary workaround?
Here is short recording: https://youtu.be/WLlvz-F2NDg
Commands executed:
```
tns create brand-new-app --template ng
cd brand-new-app
tns run ios
```

### Tell us about the problem
After adding 
```
        "lib": [
          "es6",
          "dom",
          "es2015.iterable"
        ]
```
and excluding `../node_modules` in `tsconfig.json` I still get following errors: 

```
Found peer TypeScript 2.1.6
node_modules/nativescript-angular/platform-providers.d.ts(1,23): error TS2307: Cannot find module 'ui/frame'.

node_modules/nativescript-angular/platform-providers.d.ts(2,22): error TS2307: Cannot find module 'ui/page'.

node_modules/nativescript-angular/platform-providers.d.ts(4,24): error TS2307: Cannot find module 'platform'.
node_modules/nativescript-angular/router.d.ts(3,23): error TS2307: Cannot find module 'ui/frame'.

node_modules/nativescript-angular/router/ns-location-strategy.d.ts(2,45): error TS2307: Cannot find module 'ui/frame'.

node_modules/nativescript-angular/router/page-router-outlet.d.ts(3,24): error TS2307: Cannot find module 'platform'.

node_modules/nativescript-angular/router/page-router-outlet.d.ts(4,23): error TS2307: Cannot find module 'ui/frame'.

node_modules/nativescript-angular/router/router-extensions.d.ts(3,23): error TS2307: Cannot find module 'ui/frame'.
```

### Which platform(s) does your issue occur on? 
Both, before compilation time

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) 2.5.4
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) 2.5.2
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project) 2.5.0
- Plugin(s): (look for the version number in the `package.json` file of your
project) from template

### Please tell us how to recreate the issue in as much detail as possible.
Look above...

Thanks in advance!

**Comment by tsonevn** [comment]
Hi @DanielKucal,
Thank you for your interest in NativeScript.
I review your scenario and try to reproduce this case on my side while following the above-given instructions, however, I am still unable to recreate the same problem.
Regarding that could you send us the `package.json` file and `tsconfig.json` from your newly created project, which could help us to investigate further this issue.

Thank you in advance for your cooperation.

**Comment by DanielKucal** [comment]
Hi @tsonevn, as you can see on the video I didn't make any changes to the files from [nativescript Hello World Angular template](https://github.com/NativeScript/template-hello-world-ng). The clue is I created the project under other project using nativescript (at least I haven't removed all files or settings). I guess compiler is trying to find top-level project although it exists in current directory.

**Comment by tsonevn** [comment]
Hi @DanielKucal,
If I understand you correctly this scenario happens when you nest NativeScript Angular 2  Project inside another one.
If this is the case, building the nested project with `tns run ios` will lead to the above-mentioned error, however, this specific scenario has not been supported from NativeScirpt. Regarding that, I would suggest separating the both projects in different directories, which will prevent from this build errors.
Please let me know if I could assist you further.

**Comment by DanielKucal** [comment]
I just want to know if there is any workaround for this. I tried excluding "..", "../node_modules", "./.." etc in tsconfig.json but nothing made it work. I don't nest the projects in real-life scanario, just tried to test something and was unable to...

**Comment by tsonevn** [comment]
Hi @DanielKucal,
Thank you for writing us back,
I reviewed this case ones again, however, at this moment I was unable to find a possible workaround that could resolve this conflict in the modules.
Regarding the issue as it is something that you will not use in real-life scenario, could you give us some more info about the case and what you are trying to test?

**Comment by DanielKucal** [comment]
Just debugging, I want to prototype nativescript app for an existing project and run into several issues and nativescript errors don't provide much details. To give an example take a look at #4040
