### ISSUE TITLE
Does device Farm supports testing of NativeScript application

### ISSUE THREAD

**Issue by nsnarvekar** [NativeScript/NativeScript#4024]
Hi,

I am developing NativeScript application and writing unit test cases in Jasmine/Karma. 

Does device Farm supports testing of NativeScript application. If yes then what framework should I use to write the automation test cases.

**Comment by dtopuzov** [comment]
Hi @nsnarvekar 

{N} generates native mobile app, so you should be able to use any device farm that supports testing native mobile apps.

Re testing framework you can use: This is specific for each device farm, so you should check documentation of device farms.

Just looking at [Amazon device cloud](https://docs.aws.amazon.com/devicefarm/latest/developerguide/welcome.html) and it looks they do not support JS testing frameworks, so ou should write your tests using Appium with Java or Python.

**Comment by Cayan** [comment]
I have used AWS Device Farm before with a nativescript app with fuzz and explore tests.

I wonder with there is a way to work with AWS Device Farm and https://github.com/NativeScript/nativescript-dev-appium

**Comment by dtopuzov** [comment]
I think no, it looks AWS Device Farm dos not support testing based on JS ecosystem at all.
https://saucelabs.com support JS based testing with Appium. 
Sauce Labs are great, but their offering is mostly for Android Emulator and iOS Simulator clouds.
Recently (Sauce Labs acquired TestObject )[https://saucelabs.com/news/sauce-labs-acquires-testobject-to-expand-real-device-mobile-app-testing-platform] so I expect they will also have strong device cloud story soon.
