### ISSUE TITLE
[TNS 3.0 RC] Unable to run on iOS device

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#4025]
**Platform:** iOS
**TNS:** 3.0 RC

Runs fine on emulator with `tns run ios --emulator`. But when trying to run on iPhone device through the command `tns run ios --device [identifier]`, I get the error:

`JS ERROR Error: A Frame must be used to navigate to a Page.`

I can build and install the application to the device as I normally would, but unable to debug with livesync using the `run` command.

**Comment by dtopuzov** [comment]
Hi @NordlingArt 

It is issue that we fixed after we released rc, so it will be fine in final version of {N} 3.0.0.

As temporary workaround you can use this:
```
tns platform remove ios
npm cache clean
tns platform add ios@next
```

**Comment by NordlingArt** [comment]
@dtopuzov - Ah, great. Thanks!

**Comment by vchimev** [comment]
The fix has been included in *tns-ios@3.0.0-rc.2* which is available in npm behind the `rc` tag.

**Comment by NordlingArt** [comment]
@vchimev - How do I get that version? Whenever I run `tns platform add ios` and removing the old, I still get `tns-ios@3.0.0-rc.1-2017-3-28-2`. My dependencies says:

```json
"dependencies": {
  "nativescript-theme-core": "~1.0.2",
  "tns-core-modules": "^3.0.0-rc.2"
}
```

**Comment by dtopuzov** [comment]
May be you should clean you npm cache.

```
tns platform remove ios
npm cache clean
tns platform add ios@rc
```

**Comment by NordlingArt** [comment]
@dtopuzov - God, I missed that part. Sorry, it works now! Thank you both :)
