### ISSUE TITLE
[TNS 3.0 RC] getMeasuredWidth and getMeasuredHeight methods now return device pixels

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#4026]
What's the deal with the methods such as `getMeasuredWidth` and `getMeasuredHeight` returning device pixels? As opposed to 2.5.x (and before), they returned device independent pixels. Now I have to check for every line I've used these two methods on, and wrap them with:

```js
const utils = require("utils/utils/");
const view = [some view];

const width = utils.layout.toDeviceIndependentPixels(view.getMeasuredWidth());
const height = utils.layout.toDeviceIndependentPixels(view.getMeasuredHeight());
```

If this is intentional, can't there be an argument inside these methods that is either `true` or `false` whether to return device pixels or DIPs? Like:

`view.getMeasuredWidth(true)` returns device pixels
`view.getMeasuredWidth()` returns device independent pixels, as before

**Comment by hshristov** [comment]
@NordlingArt I assume you are referring to iOS because in 2.5 these methods return device pixels for android. Are you writing custom layout? Why do you need measuredWidth?

Here is more information why we change that:
https://github.com/NativeScript/NativeScript/issues/4017#issuecomment-295635040

**Comment by NordlingArt** [comment]
@hshristov - Yes, iOS. I assumed there would be no difference between platforms. Anyhow, thanks for the explanation. I'll have to create a global function that shortens `utils.layout.toDeviceIndependentPixels` then. Thank you!

**Comment by hshristov** [comment]
@NordlingArt Could you share why do you need to convert from px to dip?

**Comment by NordlingArt** [comment]
Because working with dip allows me to measure dimensions more easily with Photoshop aside. Having to work with device pixels requires me to constantly take the device's pixel density into account. Also, when working in native code, a value of 1 means 1 dip. So if I were to measure a view's dimension with native code, it would return dip values while {N} wouldn't.

**Comment by hshristov** [comment]
@NordlingArt We do the following - all properties are in dip. All numbers inside measure/layout pass - are in px.

**Comment by NordlingArt** [comment]
@hshristov - Alright, fair enough. I'll have to re-adapt then 🙂

**Comment by PanayotCankov** [comment]
This is somewhat related:
https://github.com/Microsoft/TypeScript/issues/202
It would let us type create dip and px types and indicate the expected units in place of such methods.

**Comment by toddanglin** [comment]
I find myself (and others) running-in to this a lot with TNS 3 (also on iOS), especially if upgrading pre-3.0 code. It's particularly tricky when, as @NordlingArt highlights, you have JavaScript interacting with native CocoaPod APIs to set layout dimensions.

Were there any objections or obstacles to implementing @NordlingArt's API suggestion? Provide an "overload" for `getMeasuredWidth` to allow developers to explicitly request device independent pixels again? Something like:

`view.getMeasuredWidth()` returns device pixels
`view.getMeasuredWidth(true)` returns device independent pixels, as before

Seems like a nice compromise.
