### ISSUE TITLE
"invalid animation curve" exception for a CSS animation - NativeScript 3 RC

### ISSUE THREAD

**Issue by ludwiktrammer** [NativeScript/NativeScript#4027]
### Tell us about the problem
I have a CSS animation in my project - it worked perfectly well in NativeScript 2. After I upgraded the project to NativeScript 3 I get the following exception instead:

```
Error: invalid animation curve: android.path.view.animation.PathInterpolator@58ff198
File "file:///data/data/.../files/app/tns_modules/tns-core-modules/ui/animation/animation.js, line 71, column 16
```

The exact class name in the exception seem to differ depending on the `animation-timing-function` setting, but the only timing function that seem to be working properly and doesn't end up in an exception is `animation-timing-function: linear`.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
3.0.0-rc.1

- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
3.0.0-rc.2

- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
3.0.0-rc.1

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

This code ends up with an exception:

```
@keyframes arrow-bottom {
  0% { transform: translate(0, 50); }
  100% { transform: translate(0, 0); }
}

.coachmarks-arrow-bottom {
  animation-duration: 2.5s;
  animation-iteration-count: infinite;
  animation-timing-function: ease-in-out;
  animation-name: arrow-bottom;
}
```

If you replace `animation-timing-function: ease-in-out;` with `animation-timing-function: linear` everything starts to work as expected.

**Comment by tsonevn** [comment]
Hi @ludwiktrammer,
Thank you for reporting this issue.
I was able to reproduce this case on Android while setting up `animation-timing-function` to `ease-in-out` in the CSS animation for the component. 
This issue is reproducible while using `@rc` `CLI` and `modules`. I am attaching sample project, which could be used for debugging.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/946300/Archive.zip)

**Comment by PanayotCankov** [comment]
It works against the master branch.
