### ISSUE TITLE
iOS : iCloud Document Export Import

### ISSUE THREAD

**Issue by pap5508** [NativeScript/NativeScript#4029]
I have tried a lot in order to implement import document from cloud storage platform in iOS.

How can I implement this three steps and any demo available.?

/* 1. Create Array that contains the list of Installed application */
/*2. Show Dialog to User for select App */
/*3. Select and Upload file*/

```
class DocumentPickerDelegate extends NSObject implements UIDocumentMenuDelegate {
    private _owner: WeakRef<DocumentPicker>;
    public static ObjCProtocols = [UIDocumentMenuDelegate];
    public static initWithOwner(owner: WeakRef<DocumentPicker>): DocumentPickerDelegate {
        let delegate = <DocumentPickerDelegate>DocumentPickerDelegate.new();
        delegate._owner = owner;
        return delegate;
    }
    public documentMenuDidPickDocumentPicker(documentMenu, documentPicker) {
        console.log("this method called");
        this._owner.get().addFiles(documentMenu);
    }
}
```

```
declare var UIDocumentMenuViewController;
export class DocumentPicker {
    private documentPicker: any;
    constructor() {
        this.documentPicker = UIDocumentMenuViewController.alloc().init();
        let importMenu =UIDocumentMenuViewController.alloc().initWithDocumentTypesInMode(kUTTypeText,UIDocumentPickerMode.Import);
        importMenu.delegate = DocumentPickerDelegate.initWithOwner(new WeakRef(this));
        this.documentPicker.modalPresentationStyle = UIModalPresentationStyle.Popover;
        rootVC().presentViewControllerAnimatedCompletion(importMenu, true, null);
    }
    public addFiles(files) {
        console.log(files);
    }
}
const rootVC = function () {
    let appWindow = UIApplication.sharedApplication.keyWindow;
    return appWindow.rootViewController;
}
```

Does anyone have idea that how can i implement select file from cloud platform in iOS and share in my App ?
Also Give me suggestion and link for reference.

Thanks in advance.

**Comment by NathanWalker** [comment]
@pap5508 Please consider posting this question in the forums:
https://discourse.nativescript.org/
I can continue assisting there - curious though the above looks pretty decent - I imagine you need a property key in your Info.plist file for iCloud document access?

**Comment by MilosStanic** [comment]
We just had a discussion about this on discourse and we have a working solution here https://discourse.nativescript.org/t/import-file-from-icloud/2883/8

**Comment by sunny18pectio** [comment]
> We just had a discussion about this on discourse and we have a working solution here https://discourse.nativescript.org/t/import-file-from-icloud/2883/8

I used the code exactly in the discussion but for some reason this delegate does not get called every-time.
documentPickerDidPickDocumentAtURL

Some time I get the file in the delegate method and some time not.

Can you please suggest how to fix

**Comment by sunny18pectio** [comment]
`import { Injectable } from '@angular/core';
import * as utils from 'utils/utils';
import { ios as iosApp } from 'application';
import { Observable } from 'rxjs/Observable';
import { BehaviorSubject } from 'rxjs/BehaviorSubject';

@Injectable({
  providedIn: 'root'
})
export class DocumentPickerService {
  private documentPicker: UIDocumentPickerViewController;

    cancelledPicking = new Observable<boolean>();
    private _cancelledPicking = new BehaviorSubject<boolean>(null);
    pickedFile = new Observable<string>();
    private _pickedFile  = new BehaviorSubject<string>(null);

    private dataStore: {
        cancelledPicking: boolean,
        pickedFile: string
    };

    constructor() {
        this.dataStore = {
            cancelledPicking: null,
            pickedFile: null
        };

        this.cancelledPicking = this._cancelledPicking.asObservable();
        this.pickedFile = this._pickedFile.asObservable();
    }

    show(vc: UIViewController) {
        // show the picker
        const documentTypes = utils.ios.collections.jsArrayToNSArray([kUTTypeImage, kUTTypePDF]);
        // tslint:disable-next-line:max-line-length
        this.documentPicker = UIDocumentPickerViewController.alloc().initWithDocumentTypesInMode(documentTypes, UIDocumentPickerMode.Import);
        this.documentPicker.delegate = DocumentPickerDelegate.initWithOwner(new WeakRef(this));

        vc.presentViewControllerAnimatedCompletion(this.documentPicker, true, null);
    }

    setCancelled(cancelled: boolean) {
        this.dataStore.cancelledPicking = cancelled;
        this._cancelledPicking.next((<any>Object).assign({}, this.dataStore).cancelledPicking);
        console.log(' setCancelled ------>');
    }

    setFilePicked(fileUrl: NSURL) {
        this.dataStore.pickedFile = fileUrl.path;
        this._pickedFile.next((<any>Object).assign({}, this.dataStore).pickedFile);
        console.log(' setFilePickedfileUrl ------>', fileUrl);
    }
}


class DocumentPickerDelegate extends NSObject implements UIDocumentPickerDelegate {
  public static ObjCProtocols = [UIDocumentPickerDelegate];
  private owner: WeakRef<DocumentPickerService>;

  static initWithOwner(owner: WeakRef<DocumentPickerService>): DocumentPickerDelegate {
      const delegate = <DocumentPickerDelegate>DocumentPickerDelegate.new();
      delegate.owner = owner;

      return delegate;
  }

  documentPickerDidPickDocumentsAtURLs(controller: UIDocumentPickerViewController, urls: NSArray<NSURL> | NSURL[]) {
    console.log('documentPickerDidPickDocumentsAtURLs ----');
  }

  documentPickerDidPickDocumentAtURL(controller: UIDocumentPickerViewController, url: NSURL) {
      console.log('documentPickerDidPickDocumentAtURL');
      this.owner.get().setFilePicked(url);
  }
  documentPickerWasCancelled?(controller: UIDocumentPickerViewController) {
      console.log('documentPickerWasCancelled');
      this.owner.get().setCancelled(true);
  }
}
`
documentPickerDidPickDocumentsAtURLs
documentPickerDidPickDocumentAtURL
documentPickerWasCancelled

After selecting file (pdf) some time the delegate method gets called but not every time.

**Comment by NickIliev** [comment]
@sunny18pectio  regarding `some time the delegate method gets called but not every time.` it seems like the delegate method might be collected by GC (similar to this issue [here](https://github.com/NativeScript/nativescript-imagepicker/issues/251)). 


Can you [try the solution](https://github.com/NativeScript/nativescript-imagepicker/blob/master/src/imagepicker.ios.ts#L128-L144) that was used in the nativescript-imagepicker where the delegate instance is attached to the global object during its creation

**Comment by marcuschoong** [comment]
@sunny18pectio I got "NSObject is not defined" when I running in android platform for your sample. did the code running well on android ?

**Comment by NickIliev** [comment]
@marcuschoong this is iOS specific code (e.g. [NSObject ](https://developer.apple.com/documentation/objectivec/nsobject?language=objc)is from the Objective-C iOS runtime ) so create an iOS specific file (e.g. my-delegate.ios.ts) and this way the code won't be executed on Android. When assigning the delegate you can wrape the execution as well.

e.g. something like
```TS
if (isIOS) {
   // execute the iOS specific code here
}
```

**Comment by marcuschoong** [comment]
@NickIliev I'm new to the Nativescript. possible you can show the example for create this DocumentPickerService and how to retrieve this service? it will be much appreciated.

**Comment by Rajdeo-Das** [comment]
> @NickIliev @sunny18pectio I'm new to the Nativescript. possible you can show the example for create this DocumentPickerService and how to retrieve this service? it will be much appreciated.

I have not tried this on android yet.

**Comment by sunny18pectio** [comment]
> @NickIliev @sunny18pectio I'm new to the Nativescript. possible you can show the example for create this DocumentPickerService and how to retrieve this service? it will be much appreciated.

I have not tried this on android yet.
