### ISSUE TITLE
Nativescript File Picker?

### ISSUE THREAD

**Issue by tsebvaan** [NativeScript/NativeScript#4032]
Hi there, I want to implement in my app that can upload file(any extension) but I'm having a problem with this file picker. I've read the docs about file system but it only gets the app's document & cache(correct me if I'm wrong). I also read about this plugin -> https://www.npmjs.com/package/nativescript-file-picker , but there's no implementation for nativescript+angular. 

This is what i want in my app, the native file picker opened by Facebook App:
![11](https://cloud.githubusercontent.com/assets/23137338/25243497/c756d06e-262f-11e7-9af4-237ad07ca3e6.png)
![12](https://cloud.githubusercontent.com/assets/23137338/25243503/c8e2922e-262f-11e7-8222-a513b2fe7aa0.png)

**Comment by tsonevn** [comment]
Hi @tsebvaan,
I tested this plugin on my side and found that it is working as expected on both pure `NativeScirpt` and `NativeScirpt Angular 2` project. You could verify whether you have applied all needed setting described in the plugins [ReadMe](https://www.npmjs.com/package/nativescript-file-picker).
For your convenience, I am attaching a sample project. 

Bear in mind that this plugin is created by one of our community members and is not officially supported by NativeScript team. Regarding that, if you have some further issues with this plugin please contact the [author](https://github.com/kazemihabib/). For some other `How to ` question you could use [NativeScript forums](https://discourse.nativescript.org/).

[Archive.zip](https://github.com/NativeScript/NativeScript/files/947016/Archive.zip)

**Comment by tsebvaan** [comment]
Thank you, got it now working. There was no code for opening the file-picker in the plugin's documentation thats why I thought it's not yet implemented.

**Comment by tmandekic** [comment]
NativeScript-file-picker does not work with NativeScript 3.0. To make it work with NativeScript 3.0, I have applied following changes (after adding the plugin to the project (after "tns plugin add nativescript-file-picker"):

1) apply changes as per @tsonevn in the comment above

2) make sure all files in node-modules/nativescript-file-picker/ directory have been updated as per: https://github.com/NativeScript/NativeScript/wiki/Migrating-Plugins-to-NativeScript-3.0

3) in tns-core-modules/application/application.android.js, ln 183 ( onActivityResumed), add:
            androidApp.currentContext = activity;

4) in 
node_modules/nativescript-file-picker/file-picker.android.js, line 25, change following line from: appModule.android.onActivityResult = function (requestCode, resultCode, data) {, 
to:
            appModule.android.foregroundActivity.onActivityResult = function (requestCode, resultCode, data) {

5) tns platform clean android
6) tns run android

**Comment by sayeed360** [comment]
@tmandekic can you please elaborate #2 point above?

**Comment by saikksub** [comment]
@tsonevn I am trying to use this `Nativescript-file-picker` using VueJs. I am getting following error after selecting multiple files:

```
System.err: android.os.FileUriExposedException: file:///storage/emulated/0/DCIM/Facebook/FB_IMG_1540947660290.jpg exposed beyond app through ClipData.Item.getUri()
```

After doing some research, I found this: [android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed](https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed)

How to resolve this?

**Comment by tsonevn** [comment]
Hi @saikksub,
For issues related to `Nativescript-file-picker`, please contact the plugin's author.
