### ISSUE TITLE
[TNS 3.0 RC] Placeholder not firing creatingView (iOS)

### ISSUE THREAD

**Issue by toddanglin** [NativeScript/NativeScript#4043]
**Problem:**
With NativeScript 3.0, when using a simple `Placeholder` element, the `creatingView` event is not firing

**Steps to reproduce:**

1. Create a new project with the default template. 
2. Add a placeholder to the XML view (`<Placeholder creatingView="creatingView" />`)
3. Create an event handler (`export function creatingView(args) { console.log("Here"); }`)
4. Run the app and you should see that creatingView code does not get executed

**Environment:**

- NativeScript 3.0.0-rc.2, tns-core-modules@3.0.0-2017-04-19
- Tested on iOS

Verified that this setup _does_ work as expected in {N} 2.4. So something changed between 2.4 and 3.0 that is breaking the way Placeholder works.

**Comment by toddanglin** [comment]
With some further testing, I can confirm that this issue is specific to iOS. Occurs on both simulator and device.

Android behaves as expected.

**Comment by toddanglin** [comment]
Digging-in to the codebase, for some reason the iOS implementation is different than Androids. BUT, if I add the code from the Android `Placeholder` implementation to iOS, everything works again:

```typescript
public createNativeView() {
  let args = <CreateViewEventData>{ eventName: Placeholder.creatingViewEvent, object: this, view: undefined, context: this._context };
  this.notify(args);
  return <ios.view.View>args.view;
}
```

Any reason the iOS implementation is different? If not, changing the iOS implementation to the above seems to resolve the issue.

**Comment by NickIliev** [comment]
Hey @toddanglin confirming that this one is reproducible with NativeScript 3.0.0-rc2 on iOS
Sample application to demonstrate the issue can be located [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4043)

**Comment by hshristov** [comment]
Hi @toddanglin 
Thanks for reporting this issue and providing a solution. There is a PR that makes both implementations the same.
