### ISSUE TITLE
The Launch Screen has a quality loss when the release version it's generated (android)

### ISSUE THREAD

**Issue by locolauty97** [NativeScript/NativeScript#4044]
When I'm in debug mode the quality of the launch screen image is alright, but when I make the release version, I don't know why the launch screen appears like rounded and with a very poor quality.
There is some way to build the release version without zipping or rezising the images or assets? Thanks

**Comment by tsonevn** [comment]
Hi @locolauty97,
I tested your case with our [template-hello-world](https://github.com/NativeScript/template-hello-world). 
I build the sample app for release with `tns build android --release --key-store-path <path-to-your-keystore> --key-store-password <your-key-store-password> --key-store-alias <your-alias-name> --key-store-alias-password <your-alias-password> ` and after I install it on a device the the launch screen seems to be shown as expected without an issues.

It would help if you could provide sample project, which could be debugged locally.

In the meantime, you could review if you have set up images for all needed densities in your app as it is described [here](https://docs.nativescript.org/publishing/creating-launch-screens-android#application-resources-used-for-launch-screen-creation).

**Comment by locolauty97** [comment]
Hi @tsonevn, yes I have set up all the images for all densities, so I don't think that was the problem. 
Anyway to get by the problem momentarily I solved with, in some way, a hacky manner. I built the project as in debug mode but set up the signing key for debug mode in the build.gradle file and set the android:debuggable property to false in androidManifest.xml

That way when I run `tns build android` I have a releaseable apk file that doesn't have that problem with the images.
Maybe i should `zipalign` the file later.

Thanks for the response!

**Comment by tsonevn** [comment]
Hi @locolauty97,
I am glad to hear that you resolved your problem.
Regarding that, It would help if you could send us some sample images, which could help us to investigate further this case and if it is a real issue to provide needed fix.

Also, could you provide some more info about your environment (NativeScript CLI, `tns-core-modules` `node` versions)?

Regards,
@tsonevn
