### ISSUE TITLE
[question/feature request] List of sass variables that you can override

### ISSUE THREAD

**Issue by chrillewoodz** [NativeScript/NativeScript#4047]
I've tried to search for an answer to this but I cannot find it.

Basically if you install the sass plugin, you get this line in the `_app-common.scss` file:

`// Customize any of the theme’s variables here, for instance $btn-color: red;`

Is there a list of which variables you can override? The docs doesn't seem to contain them. Exposing these variables would make it very easy to create a custom look for your app.

**Comment by danielgek** [comment]
@chrillewoodz you can take a look at [_variables.scss](https://github.com/NativeScript/theme/blob/master/app/scss/_variables.scss)

**Comment by chrillewoodz** [comment]
@danielgek Thank you :)
