### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by praven07** [NativeScript/NativeScript#4049]
I started getting this error log. I don't use any http request of any sort. Is there any reason why I would get this. 

<img width="646" alt="screen shot 2017-04-22 at 11 22 09 am" src="https://cloud.githubusercontent.com/assets/2223191/25306195/24c8619e-274e-11e7-8427-b541115ff5e6.png">

**Comment by tsonevn** [comment]
Hi @praven07,
Thank you for reporting this issue.
I reviewed your case, however, the given information is not enough to be able to investigate further this problem.
It would help if you provide info about your environment (CLI, node_modules, node versions) and sample project, which could be debugged locally or at least some steps.
You could also verify, whether this error is related to some of the plugins, which is used in the application.

**Comment by tsonevn** [comment]
Hi @praven07,
Something more that could be related to this issue is in case you are loading an image from URL.
Passing in URLs with spaces could lead to the `unsupported URL` error. 
if this is the case you replace the empty spaces with `%20`, which will solve the issue.
