### ISSUE TITLE
iOS - navigating with flipRight/Left transition - freezes the new page.

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/NativeScript#4052]
_From @erjdriver on April 22, 2017 13:6_

If I navigate to a new page with flipLeft/Right - it freezes the new page. 

This is on iOS version - Android works fine. This has been a problem for quite a bit.

ns 2.5.3
core 2.5.2
ios 2.5

Here's my code:

`

        var page_def =
        {
            moduleName: "my-page"),
            animated: true,
            clearHistory: true,
            transition:
            {
                name: "flipLeft",
                duration: 400,
                curve: "easeOut"
            }
        };

        frameModule.topmost().navigate( page_def );

`

_Copied from original issue: NativeScript/nativescript-cli#2731_

**Comment by NickIliev** [comment]
Hey @erjdriver , I've tested the described scenario but at my side everything works as expected and the transitions are executing with no problems. Can you please give additional information on what iOS device / emulator you are testing?

[I've used this application ](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4052 (with the code you provided))and test it with iOS 10.2 and iOS 9.2.

**Comment by erjdriver** [comment]
This is on emulator version 10.

I haven't tried it yet on a device itself...because I need it to work on the emulator. But I suppose I can try it on a device.

The transition works - but the issue is the destination page freezes after the transition.

I thought it might be the destination page and tried another page that works - and that froze also.

Tried a few different combinations for clearHistory, duration etc and they all froze.

Right now I've set it to slideLeft and it works fine.

Since the app just freezes, I can't look at a crash log or something.

**Comment by NickIliev** [comment]
@erjdriver can you test with the sample application I've created - I have made a button that navigates back and the app does not freeze at my side, so perhaps it is something specific within your code. The best scenario is to create a test applicait9on that reproduces this behavior and attach it here as an archive or as a GitHub link.

**Comment by erjdriver** [comment]
I did some more testing.

I'm using Telerik RadSideDrawer - the problem occurs when that function is called on a menu selection from the side-drawer.

I called the same function (that navigates with a page flip transition) from a button event callback and the page didn't freeze.


Again this is on the ios simulator version 10.

**Comment by NickIliev** [comment]
Hey, @erjdriver  As this issue is probably related to more complex scenario (page transitions + RadSideDrawer) it will be great to provide us with a sample application that can reproduce the problem on our side.
