### ISSUE TITLE
Cannot read property 'setSelection' of undefined

### ISSUE THREAD

**Issue by mayureshjadhav** [NativeScript/NativeScript#4054]
Hello Guys,

Unexpected issue I am receiving at my login component. The scenario is 
1. Open the app
2. Enter the login credential
3. Do some stuffs
4. Close the app
5. It shows main page (not login page because I had stored some values in local storage and I am checking that for not allowing user to re-enter their credentials again)
6. Do some stuffs
7. Click on log out button
8. It shows blank page instead of showing login page

If I Open the app and enter the login credentials and do immediate logout it shows me the login page but in above scenario it is not showing it. 

When I debug more on it I found bellow message

 Error: Error in pages/login/login.component.html:5:16 caused by: Cannot read property 'setSelection' of undefined

I don't know why?

I found this issue while testing on Android device

The App I am developing using NS 2.5

**Comment by tsonevn** [comment]
Hi @mayureshjadhav,
Thank you for your interest in NativeScript.
I reviewed the case, however, was unable to reproduce the case on my side. I exact steps that I follow are:
1. `git clone https://github.com/NativeScript/sample-Groceries/`
2. `tns run android` 
3. login in the app
4. add new item in the app list
5. close the app
6. open the app and log out
After that, I was returned successfully to the login screen.
![screenshot 37](https://cloud.githubusercontent.com/assets/17448734/25332648/e727055e-28ef-11e7-8df3-47d9af0b8d1f.png)

Regarding that, could you provide some more info about the problem and about the device that has been used and its API level. 
Let me know if I am missing something in the steps.
