### ISSUE TITLE
iOS ListView displays more entries than there is with separators.

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/NativeScript#4060]
I've got a ListView with no entries - and ListView displays a bunch of separators - when it really should be a blank page.

Sometimes, I've got 1 entry and it'll display that entry + a few more separators.

This issue is in iOS version only.

I looked in Stackoverflow and seems like a known issue.

Can anything be done - or disable separators and use a LABEL of height 1.

**Comment by NickIliev** [comment]
@erjdriver 

Indeed this is known behavior for ListView in iOS and this is as implemented by the native design (e.g. the same issues can are discussed by native iOS devs [here](http://stackoverflow.com/questions/4213197/how-to-hide-empty-rows-in-a-uitableview-and-change-the-height-of-the-uitableview)). 

To overcome this you can control your ListView and ListView item heights with **height** and **rowHeight** properties and then change the height whn needed (when more items are loaded). 
e.g.
```
<ListView id="myList" height='100' rowHeight="100">
```

And later when you load additional items then you can dynamically change the height ofn your ListView.
e.g.
```
var myList = page.getViewById("myList");

// add more items 

myList.height = 500;
myList.refresh()
```

You can also control the separator color from your CSS.
```
ListView {
    separator-color: white
}
```

**Comment by erjdriver** [comment]
That's going to to be difficult - because you now also have to know the available height right? Or is myList.height the absolute/virtual height of the listview and not the scrollview.

Anyway, this is especially a non-starter with me because my row heights are variable.

I was thinking of disabling separator and then add a extra LABEL with height 1 to my list-item - that should work right?
