### ISSUE TITLE
NativeScript debugging with BigNox player emulator

### ISSUE THREAD

**Issue by Fabiyo-90** [NativeScript/NativeScript#4064]
Hello Community, I have BigNox player, an android emulator and I need to use it for debugging my nativescript application, I need your help for connecting nativescript to BigNox player.... 
Please i need a solution !

**Comment by NickIliev** [comment]
Hello @Fabiyo-90 and thank you for your interest in NativeScript!

Yes, you can use BigNox player to debug your NativeScrtip applications. 
To do that you need to enable the developer mode on your Nox player and then make ADB recognize the emulator. Achieve that by following the steps in [this great guide ](https://www.bignox.com/blog/how-to-connect-android-studio-with-nox-app-player-for-android-development-and-debug/). Keep in mind that the path in the last 6th step might differ. For me, under Windows 10, it was **_C:\Program Files (x86)\Nox\bin_**

Once all above is done verify taht NativeScrtip CLI is reciognizing your Nox player (which should be started)
```
tns devices
```

it should print something like this:
```
C:\Program Files (x86)\Nox\bin>tns devices

Connected devices & emulators
Searching for devices...
iTunes is not installed. Install it on your system and run this command again.
┌───┬──────────────────────┬──────────┬───────────────────┬──────────┬───────────┐
│ # │ Device Name          │ Platform │ Device Identifier │ Type     │ Status    │
│ 1 │ cancro               │ Android  │ 127.0.0.1:62001   │ Device   │ Connected │
│ 2 │ sdk_google_phone_x86 │ Android  │ emulator-5554     │ Emulator │ Connected │
└───┴──────────────────────┴──────────┴───────────────────┴──────────┴───────────┘
```

In the case above the device called **cancro** is the Nox player.

So now we can simply run our application with **tns run** command
```
tns run android --device 1
```

**Comment by Fabiyo-90** [comment]
it's not working ! I have the result when i write nox_adb.exe connect 127.0.0.1:62001

\Users\fabiyo\AppData\Roaming\Nox\bin>nox_adb.exe connect 127.0.0.1:62001
already connected to 127.0.0.1:62001

and tns device print as result

E:\PROJECT_NODE\NativeScript\mobileJs>tns device
iTunes is not installed. Install it on your system and run this command again.
Cannot find connected devices. Reconnect any connected devices, verify that your system recognizes them, and run this command again.

**Comment by Fabiyo-90** [comment]
I don't understand, and please forgive me cause I am a french man and my english is not so good; and there isn't a french community of nativescript; I live in DR Congo

**Comment by NickIliev** [comment]
@Fabiyo-90 based on the log from **tns devices** it seems that you either have not connected the device or more likely the device (the Nox player) has not been enabled for USB dubbing as shown in[ step 5](https://www.bignox.com/blog/how-to-connect-android-studio-with-nox-app-player-for-android-development-and-debug/). Verify that  your player is up and running and that you have followed all the steps to enable the USB debugging just like it would be done on a real Android device.

If the **ADB** is not recognizing your NOX player then it would be recognized by tns as well. You can try to kill the ADB server and then try to reconnect your devices to see if ADB and tns are seeing the NOX player./
```
adb kill-server
adb devices 
```

**adb devices** should print the exact same list of connected devices as **tns devices**

**Comment by Fabiyo-90** [comment]
It is still not working
I do and thr result is 
C:\Users\fabiyo\AppData\Roaming\Nox\bin>nox_adb.exe connect 127.0.0.1:62001
adb server is out of date.  killing...
* daemon started successfully *
connected to 127.0.0.1:62001

and tns device is 
E:\PROJECT_NODE\NativeScript\mobileJs>tns device
iTunes is not installed. Install it on your system and run this command again.
Cannot find connected devices. Reconnect any connected devices, verify that your system recognizes them, and run this command again.

**Comment by Fabiyo-90** [comment]
Please may you make a video via youtube

**Comment by NickIliev** [comment]
@Fabiyo-90 your issue is related to your **adb** and not to your NOX player or NativeScript CLI (tns).
No point of showing you how this is working on my PC because you need to solve your adb issue which is not reproducible here.

Try executing 
```
adb devices
```
and you should see the same warning ("adb server is out of date.killing ...")

This is probably caused either by an older version of adb or because you have multiple instances no your machine and you are not using the right one.
I would recommend checking out the solutions suggested [here](http://stackoverflow.com/questions/5092542/adb-server-is-out-of-date) or [here](http://stackoverflow.com/questions/36731277/adb-server-is-out-of-date-killing)

There is a very accurate explanation, and solution posted [here](http://visualgdb.com/adbfix/). However, I have not tested them on my side and can not guarantee that it is a safe one so use it with caution.

**Comment by Fabiyo-90** [comment]
I am using windows 10; 64x and see the result ! 

C:\Users\fabiyo\AppData\Roaming\Nox\bin>nox_adb.exe connect 127.0.0.1:62001
adb server is out of date.  killing...
* daemon started successfully *
connected to 127.0.0.1:62001

C:\Android-sdk\platform-tools>adb.exe devices
List of devices attached
adb server version (31) doesn't match this client (39); killing...
* daemon started successfully *

C:\Android-sdk\platform-tools>adb.exe devices
List of devices attached

**Comment by NickIliev** [comment]
This line is the reason for your issue - see the links I've posted above to resolve it.

```
adb server version (31) doesn't match this client (39); killing...
```

**Comment by Fabiyo-90** [comment]
I had installed genymotion and is working goodly but with BigNox isn't working

**Comment by NickIliev** [comment]
@Fabiyo-90 indeed GenyMotion is an option but in my opinion, the best option is the Android sirtual devices (a.k.a. AVD).
If you are interested in how to create AVDs you can take a look at [this article](https://docs.nativescript.org/angular/tooling/android-virtual-devices.html) where it is explained how to create different Android virtual devices with enabled HAXM.

**Comment by Fabiyo-90** [comment]
Thank you for your advices

**Comment by Tomdoff** [comment]
I'm coming into the same issue at the moment. Android studio detects my nox emulator, and if I type 
`adb devices` then I see my emulator listed, but when I run `tns devices` I don't get the emulator coming up.

**Comment by sirius2013** [comment]
@Fabiyo-90 
I got same issue like you. did you get success to run nox for app?
