### ISSUE TITLE
platform-specific .ts WebStorm resolution

### ISSUE THREAD

**Issue by vbresults** [NativeScript/NativeScript#4066]
What ways are there to have WebStorm pick up my .ios.ts and .android.ts files instead of marking them as non-existent when I include them using the platform-agnostic path?

**Comment by PanayotCankov** [comment]
In the modules we usually have a .d.ts which is resolved and describes the common API provided by the two platform specific files. E.g:
```
index.d.ts // This gets picked as types by tsc when the module is required
index.android.ts // Android spec.
index.ios.ts // iOS spec.
```
