### ISSUE TITLE
NS 2.5.4 debug run problems

### ISSUE THREAD

**Issue by terhoraj** [NativeScript/NativeScript#4068]
Am I the only one who's experiencing LOTS of issues while running "tns run android" or "tns livesync android --watch" <-- deprecated.. commands. Sometimes update goes in well but app may "restart" itself multiple times and then start with changes. Most of the time changes are not included but app still starts. Even more annoying is that sometimes it just reverts my changes and starts an app with old state where I don't have all my code included.

So my work around is to remove app and remove platform and build again which takes tons of time. It also looks to do build multiple times hanging my computer.

These issues were not there in earlier versions like 2.4.. so it's a kinda step backwards for me.

This happens with emulator as well as physical device.

I'm using Javascript with my project.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#2742
