### ISSUE TITLE
Catch TypeErrors

### ISSUE THREAD

**Issue by johnnyzen** [NativeScript/NativeScript#4069]
Hi all

Using: Angular / Typescript
Version 2.5.4
TS: 2.1.6
Android and iOS

When a TypeError occurs, the app is left in a inconstant/unstable state.

Example: EXCEPTION: Cannot read property 'length' of undefined
Expected Outcome: Catch this error globally and exit the app or create a log
What happens: The app is still useable, but renders it completly unstable.

There appears no way to catch these errors globally and either close the app or conduct a log report.

I have tried application.uncaughtErrorEvent but this seems to ignore the TypeErrors.

If this is not possible, can we consider this?

Best

**Comment by tsonevn** [comment]
Hi @johnnyzen,
Thank you for writing us
In regard to the issue, you are facing, could you provide some more info about the problem and when it appears.  It would help if you could provide some sample project.

Something you could suggest doing for this case is to use use the NativeScirpt trace modules, which will help you to receive some information about your application at runtime.
More information how to use it could be found [here](https://www.nativescript.org/blog/tracing-nativescript-applications). 
Also, you could review the sample app [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/release/app/trace), where is shown how to use it in NativeScritp Angular 2 application.

**Comment by NickIliev** [comment]
Hey @johnnyzen we haven't heard from you for a while - will close this due to inactivity but do let us know if you need assistance.
