### ISSUE TITLE
Tab View

### ISSUE THREAD

**Issue by praven07** [NativeScript/NativeScript#4076]
I'm using this line inside a tab view. 
`<StackLayout *tabItem="{title: homeTab}"></StackLayout>`

`public homeTab = 'Home';`
and assigning the variable in angular typescript. But when I change the variable later on to say 'Hello'. It does not seem to change the tab title. Shouldn't it be dynamic.

**Comment by NickIliev** [comment]
@praven07 you need to bind and change the whole tabItem object - simply changing a key from your bound object won't work.

An example is given [here](https://github.com/NativeScript/NativeScript/issues/3911#issuecomment-291459437) so I am closing this as a duplicate.
