### ISSUE TITLE
NavigationButton and ActionItem icon colors are different on iOS

### ISSUE THREAD

**Issue by racekarl** [NativeScript/NativeScript#4079]
### Did you verify this is a real problem
- Yes, searched and read all open "color" issues here as well as extensive Google searches

### Tell us about the problem
If I set the icon property of a Navigation button and an ActionItem in the same ActionBar to the same resource (PNG) the colors are not the same.  The ActionItem (and the text of the ActionBar itself) are a lighter color.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
Native script 2.5.2

### Please tell us how to recreate the issue in as much detail as possible.
1. Add a set of scaled PNG images representing an icon to the resources folder 
2. Add an action bar to a page
3. Add a NavigationButton to the action bar and set icon="res://iconfromstep1"
4. Add an ActionItem to the action bar and set icon="res://iconfromstep1"
5. Run the app in the iOS emulator and see the colors of the two icons are not the same (see attached screen shots)

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
From the component.html:
```
    <ActionBar title="Download Project">
        <NavigationButton icon="res://settings"></NavigationButton>
        <ActionItem icon="res://settings"></ActionItem>
    </ActionBar>
```
I also set the action bar to translucent = false in the component.ts:
```
constructor(private routerExtenions: RouterExtensions, private page: Page) {
    frameModule.topmost().ios.controller.navigationBar.translucent = false;
   }
```
NavigationButton on left, ActionItem on right.  Both point to the same res:// image.  The NavigationButton is visibly darker:
<img width="131" alt="screen shot 2017-04-28 at 11 33 35 am" src="https://cloud.githubusercontent.com/assets/12420066/25536416/bf8eb12e-2c08-11e7-9ea6-a4da74bb7fda.png">

The issue is more easily seen when the background color of the ActionBar is set to be the same as the color of the PNG, which makes the ActionItem disappear, while the NavigationButton remains visible:
<img width="164" alt="screen shot 2017-04-28 at 11 33 07 am" src="https://cloud.githubusercontent.com/assets/12420066/25536417/bf8f1510-2c08-11e7-9cde-5c0473784f21.png">

**Comment by NickIliev** [comment]
@racekarl what is happening, here is that by default in iOS the ActionItems are colored with a UIColor set with property tintColor and by default, this is the iOS blue color (#007AFF or simply calling self.tintColor on any native view in iOS). By chance, in your case, the color of the icon is pretty close to the one with the applied tintColor which is causing this case.
To resolve this one you have two options - either change the default tintColor for your ios navigationController OR use custom action item and provide your icon as an image.

Here is how to achieve both solutions:
**_Solution with creating custom ActionItem_**
```
    <ActionBar title="icon test">
        <NavigationButton icon="res://icon"></NavigationButton>
        <ActionItem ios.position="right">
            <StackLayout>
                <Image src="res://icon" stretch="none" />
            </StackLayout>
        </ActionItem>
    </ActionBar>
```

**_Solution with accessing the native tintColor of the navigationController in iOS_**
```
import { Color } from "color"

export function onLoaded(args: EventData) {
    let page = <Page>args.object;

    topmost().ios.navBarVisibility = "always";

    var controller = topmost().ios.controller;

    controller.navigationBar.tintColor = new Color("red").ios; // you can also set color with hex but apply the native iOS value with .ios
    controller.navigationBarHIdden = false;
}
```
