### ISSUE TITLE
ScrollView does not scroll

### ISSUE THREAD

**Issue by vakrilov** [NativeScript/NativeScript#408]
Here is a repro page:
```xml
<Page>
	<StackLayout>
	  <ScrollView>
	     <StackLayout>
	         <Label text="START" />
	         <Label height="1000" backgroundColor="red"/>
	         <Label text="END" />
	     </StackLayout>
	  </ScrollView>
	</StackLayout>
</Page>
```
Looks like the issue occurs when the ScrollView is measured s AT_MOST height measure spec. I'm looking at you [MEASURED_STATE_TOO_SMALL](https://github.com/NativeScript/NativeScript/blob/master/ui/core/view.android.ts#L308)

**Comment by cime** [comment]
Anything new on this one? I need ScrollView for my app because I have few large forms that needs scrolling functionality.

**Comment by enchev** [comment]
This issue is already fixed and will be part of our upcoming 1.3 release.

**Comment by danicomas** [comment]
The same issue @cime @enchev we need to wait for.

**Comment by enchev** [comment]
The release will be next week.

**Comment by danicomas** [comment]
@enchev Doesn't it appear in changelog? https://github.com/NativeScript/NativeScript/blob/master/CHANGELOG.md

**Comment by enchev** [comment]
Our mistake! We missed three issues - log will be updated immediately!

**Comment by danicomas** [comment]
Thanks @enchev

**Comment by danicomas** [comment]
@enchev I have done this:

npm remove nativescript -g
npm install nativescript -g

and I have added to my current project a page with this:
https://docs.nativescript.org/ApiReference/ui/scroll-view/HOW-TO.html

And it doesn't work.

**Comment by vakrilov** [comment]
@danicomas You can try to upgrade you rpoject following the instructions [here](http://docs.nativescript.org/upgrade-instructions#upgrade-instructions)

**Comment by danicomas** [comment]
@vakrilov @enchev tns platform update ios makes me override the xcode project then I lose all my manually libraries added. Mmmm... I think that is not a good solution. What do you think?

**Comment by fealebenpae** [comment]
Hi @danicomas - I feel your updating pain. We're working on making platform updates a lot easier starting with the upcoming 1.4 release of the iOS runtime. That is to say, projects created with 1.4 will have an automatic upgrade path to newer versions of the runtime.

Until then, [here are the changes we've made to the template project file between the 1.2.2 and 1.3.0 releases](http://pastebin.com/9dKheU0d). You can apply them to your project file manually.

**Comment by x4080** [comment]
Is the issue been fixed?
I tried the sample above, "END" text still dont show, (I install fresh 1.3 version). If I have to change it manually, what file to fix ? tq

**Comment by hshristov** [comment]
Hi @x4080 
This issue is fixed in 1.3.0

In order to see the "END" text - you have to scroll.

**Comment by x4080** [comment]
You're right, my mistake, I put it after absolutelayout not directly inside page, I'll try to investigate further (and I did scroll) 
:-)

**Comment by x4080** [comment]
Ok after some investigation, I set the absolutelayout height to deviceHeight = platformModule.screen.mainScreen.heightPixels / platformModule.screen.mainScreen.scale;

I forgot to decrease 25 which is the statusbar dp height (hope helps someone too)

Sorry guys for the false alarm
