### ISSUE TITLE
Running any combination of 'tns run android' always shows a options list

### ISSUE THREAD

**Issue by caiusCitiriga** [NativeScript/NativeScript#4082]
Hi everybody! I'm trying to run nativescript on Windows, because on this machine I've got more RAM. After following the guide for the installation and managed to solve each problem posted by <code>tns doctor</code>, I decided to try to follow the Nativescript + Angular guide to build an Angular project.

Things went bad when I've tryied to launch <code>tns run android</code>

### Any combination of this command brings me to the following screen:

![capture](https://cloud.githubusercontent.com/assets/12595721/25568620/f7af587e-2e06-11e7-944c-aa4ab50c1db7.PNG)

<code>tns run android</code>
<code>tns run android --device 1</code>
<code>tns run android --device <device-identifier></code>
<code>tns run android --emulate</code>

<b>None of this worked.</b> The strange fact is that it's not throwing any error, besides the message saying that the <code>tns-android@2.5.0</code> already installed.

I'm trying to run this on android platform, and for now I'm doing it on my macbook attaching my phisical device and running <code>tns run android --device 1</code>, of course it's less RAM consuming but I'd really love to run it on my Windows workstation too.

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.4
- Cross-platform modules: ^2.5.2
- Runtime(s): <code>tns-android: ^2.5.0</code>
- Plugin(s): ???

### Please tell us how to recreate the issue in as much detail as possible.
As simple as possible, It's a fresh install of the nativescript package. Globally with npm. Then I went through the automated script for the android tools installation. After that I've managed to run <code>tns doctor</code> and solve each issue.

Created an avd:
![capture](https://cloud.githubusercontent.com/assets/12595721/25568685/8cc52b68-2e08-11e7-894c-2df680a47a5f.PNG)

I've then tryied to run the <code>tns run android [any combo of options]</code> in both ways:
* with the emulator shutted off
* with the emulator running

<b>If it can help I'm using HAXM</b>

As said before I've also tryied to run the application with my phisical device attached by passing the ID of the device (retrieved by running <code>tns device list</code>) or the device identifier, but none worked.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
There's no code involved, just created the Angular project using the template command:
<code>tns create HelloWorld --template nativescript-template-ng-tutorial</code>

Then cd into it and tryied to run it.

**Comment by sis0k0** [comment]
Hey @caiusCitiriga,

You need to open your `package.json` and remove the `tns-android` from dependencies.
See [this](https://github.com/NativeScript/nativescript-cli/issues/2487) thread if you are interested why this happens.
Note: the issue is resolved in NativeScript 3.0.

**Comment by NickIliev** [comment]
@caiusCitiriga the solution provided by sis0k0 should handle your case, but please let me know if you need further assistance!

Closing as duplicate to [https://github.com/NativeScript/nativescript-cli/issues/2487](https://github.com/NativeScript/nativescript-cli/issues/2487)

**Comment by caiusCitiriga** [comment]
@sis0k0, @NickIliev,
Thank you guys! It worked like a charm!
