### ISSUE TITLE
Support for modules that depend on Android AppCompat libraries

### ISSUE THREAD

**Issue by vakrilov** [NativeScript/NativeScript#409]
The issue is related to #304 - the action bar implementation can benefit from using AppCompat libraries (more specifically [v7](https://developer.android.com/tools/support-library/features.html#v7)). 
To use the appcomat libraries one should typically: 

 - [x] Add a reference to the app compact library. Probably the best place to do that is in the NativeScript CLI. Note that some of the libraries(e.x. v7) are not just a jar file - but a project with resources.
 - [x] Modify the styles.xml files to change the app theme to derive from one of the AppComat themes(e.x. `Theme.AppCompat.Light`).

 - [ ] Create an activity that derives form [AppCompatActivity](https://developer.android.com/reference/android/support/v7/app/AppCompatActivity.html). This feature will be enabled trough the android-runtime in future.

**Comment by alejonext** [comment]
+1 Styles.xml

**Comment by alejonext** [comment]
Why close?

**Comment by vakrilov** [comment]
@alejonext I closed the issue as it will be included in the upcoming 1.3 release. There you will have access to the AppComapt lib by default and also the theme of the application is changed to the AppCompat theme.

**Comment by alejonext** [comment]
ok!

**Comment by WinMinTun** [comment]
@vakrilov I m writing a NS plugin that will use an android plugin, and I need to pass the native plugin the instance of `AppCompatActivity`. `application.android.currentContext` doesn't work, so pls help.
