### ISSUE TITLE
My ActivityIndicator freezes on android

### ISSUE THREAD

**Issue by mobilemindtec** [NativeScript/NativeScript#4091]
Hi guys,

It's normal ActivityIndicator  freeze on android?  If I start my ActivityIndicator and process any thing in background, as a read database or a loop  that work a little more time the ActivityIndicator freezes. 

Another case is the google maps manipulation. When I need add many markers on map the ActivityIndicator freezes. It's been a while since I've had this problem. Is there any workaround without having to put this "slow code" in a native plugin? It's a little complicated export all app map logic to native plugin. In this case, I need get same database infos, manipulate and test if will appear at map. 

Thanks!

**Comment by NickIliev** [comment]
Hey, @mobilemindtec can you provide us with a basic example/code sample demonstrating the "freeze" case?

**Comment by mobilemindtec** [comment]
Hi @NickIliev,

Yes, you can test using this:

xml
```
    <GridLayout>
        <StackLayout class="p-20">
            <Button text="Work without timeout" tap="onTapWithoutTimeout" class="btn btn-primary btn-active"/>
            <Button text="Work with timeout" tap="onTapWithTimeout" class="btn btn-primary btn-active"/>
        </StackLayout>
        <ActivityIndicator busy="{{ busy }}" />
    </GridLayout>
```
js 
```
exports.onTapWithoutTimeout = function(){

    viewModel.set('busy', true)
    for(var i= 0; i < 50000; i++){
        console.log("step " + i)
    }
    viewModel.set('busy', false)

}

exports.onTapWithTimeout = function(){

    viewModel.set('busy', true)

    setTimeout(function(){
        for(var i= 0; i < 50000; i++){
            console.log("step " + i)
        }
        viewModel.set('busy', false)
    }, 300)

}
```
`onTapWithoutTimeout` does not show ActivityIndicator
`onTapWithTimeout` show ActivityIndicator but freezes

Thanks!

**Comment by NickIliev** [comment]
@mobilemindtec thank you very much for providing test snippet!
Indeed I can confirm that this is happening with nativeScript 2.5.x but the good news taht this is already fixed with RC versions (upcoming 3.0.0). Sample project used to test this one with tns-core-modules@3.0.0-rc.2 can be found [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4091)

**Comment by mobilemindtec** [comment]
Hi @NickIliev,

Very nice, I'll test!

**Comment by mobilemindtec** [comment]
Hi @NickIliev,

This not work anymore? I make the same test and ActivityIndicator freezes.

```
"tns-android": {
  "version": "3.2.0"
}
"tns-core-modules": "~3.2.0"
```

**Comment by ScriptiZer** [comment]
i have the same issue using 3.2.0

**Comment by manoldonev** [comment]
@ScriptiZer Could you elaborate? Triggering the activity indicator for asynchronous operation (with `setTimeout(...)`) works without freezing with tns-core-modules@3.2.0 as well as latest tns-core-modules@3.4.1 in our local tests.

**Comment by mobilemindtec** [comment]
Hi @manoldonev ,

In both cases activity indicator freezes, using `setTimeout` to start my task or to trigger activity indicator. I tested using last version 3.4.3

My example:

```
    <GridLayout>
        <ActivityIndicator busy="{{ busy }}" />
        <Button text="Go!!" tap="onGo" style='width: 200; height: 44'/>
    </GridLayout>
```
```
exports.onGo = () => {

    viewModel.set('busy', true)

    setTimeout(function(){
        for (var i = 0; i <= 100000; i++) {
            console.log("item " + i)
        }
        viewModel.set('busy', false)
    }, 100)

}
```

https://github.com/mobilemindtec/temp-files/blob/master/app-indicator-freezes.tar.gz

**Comment by manoldonev** [comment]
Hey @mobilemindtec @ScriptiZer -- I was able to reproduce the described behavior on a physical device (it is not reproducible on emulator). The freeze in this scenario is actually expected (with or without setTimeout) as you are trying to execute a long-running operation (the array traversal in this example) synchronously on the UI thread thus blocking it for any other operations (the activity indicator and everything else).

You can explore your options with [background](https://www.nativescript.org/blog/using-workers-in-nativescript-to-execute-javascript-on-background-threads) [workers](https://docs.nativescript.org/core-concepts/multithreading-model) for non-UI work, or try to extract your logic in native plugins to keep the UI thread responsive.

**Comment by mobilemindtec** [comment]
Ok @manoldonev , thanks!
