### ISSUE TITLE
Odd Android <Label /> bug causing "Calling js method onCreateView failed"

### ISSUE THREAD

**Issue by davecoffin** [NativeScript/NativeScript#4092]
When trying to display a label on Android, the app crashes. I am aware that this is obviously related to my environment and other factors, but I need some advice on how to track down the source of this issue. Here is a video displaying the problem: https://cl.ly/kGWW

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
```
┌───────────────┬───────────────┬───────────────┬─────────────┐
│ Component     │ Current       │ Latest        │ Information │
│               │ version       │ version       │             │
│ nativescript  │ 2.5.4         │ 2.5.4         │ Up to date  │
│ tns-core      │ 2.5.2         │ 2.5.2         │ Up to date  │
│ -modules      │               │               │             │
│ tns-android   │ 2.5.0         │ 2.5.0         │ Up to date  │
│ tns-ios       │ 2.5.0         │ 2.5.0         │ Up to date  │
└───────────────┴───────────────┴───────────────┴─────────────┘
```

The XML that is causing this is:
```
<StackLayout xmlns:PullRefresh="nativescript-pulltorefresh" loaded="loaded" xmlns:IC="nativescript-web-image-cache">
    <GridLayout>
        <Label col="2" text="Hello." />
        <PullRefresh:PullToRefresh refresh="refreshShifts" height="100%">
            <ScrollView height="100%">
                <StackLayout orientation="vertical">
                    <StackLayout class="shifts_header">
                        <GridLayout columns="*, 50, 250, 50, *">
                            <Label col="2" text="Hello." />
                        </GridLayout>
                    </StackLayout>
                </StackLayout>
            </ScrollView>
        </PullRefresh:PullToRefresh>
    </GridLayout>
</StackLayout>
```

The presence of the Label is causing the issue. If I change that to a Button, it displays fine. If I move it outside of the PullRefresh, it works. 

The truncated error log is:

```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to resume activity {com.cubbynotes.pocketnanny/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreateView failed

Error: java.lang.NullPointerException
    android.widget.TextView.setTextColor(TextView.java:3260)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
    com.tns.Runtime.callJSMethod(Runtime.java:1047)
    com.tns.Runtime.callJSMethod(Runtime.java:1028)
    com.tns.Runtime.callJSMethod(Runtime.java:1018)
    com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
    android.app.Fragment.performCreateView(Fragment.java:2352)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
    android.app.BackStackRecord.run(BackStackRecord.java:815)
    android.app.Fra
```

**Comment by bradmartin** [comment]
I've recreated the crash from @davecoffin sample repo https://github.com/davecoffin/PullToRefresh-Android-Bug

- If you set the color on the `Label` in the *main-page.xml* and run the app it will run successfully. You can then remove the hard coded `color` property on the label and livesync will keep running the app. However, if you go make a change in the .js that refreshes the application it will crash with the `NullPointerException`

**Comment by tsonevn** [comment]
Hi @davecoffin @bradmartin.
Thank you for the sample project
I tested this case on my side with the official module version 2.5.2 and with modules 3.0. However, this issue seems to be reproduced with both. 
In my opinion, this is related to the `nativescript-pulltorefresh` plugin and the fact that we are trying to set an undefined color to the Label component. We could keep the discussion in the plugin's repository [here](https://github.com/bradmartin/nativescript-pulltorefresh/issues/24).
As a temporary solution, you could set up color property for the Label as @bradmartin suggested, which will allow you to use this plugin.

**Comment by aleksander351** [comment]
I have the same error message `System.err: Calling js method onCreateView failed` after adding  `RadSideDrawer` component to my Angular/NativeScript project.
