### ISSUE TITLE
IOS: CXCallObserverDelegate: callChanged not triggering

### ISSUE THREAD

**Issue by Timothylawler** [NativeScript/NativeScript#4099]
tns --version : 2.5.4
tns-ios: 3.0.0-rc.2

I'm using the CXCallObserver to listen for incoming/outgoing/ongoing calls on a IOS device (currently testing on a Iphone 6s version 10.2.1) and set up my delegate and observer like this: 

	module.exports = {
		phoneDelegate: NSObject.extend({
			initWithResolveReject: function(resolve, reject){
				var self = this.super.init();
				if(self){
					this.resolve = resolve;
					this.reject = reject;
				}
				return self;
			},

			callObserverCallChanged: function(observer, call){
				console.log("This log is not triggering");
				if(call.hasEnded){
					//  call has ended
					this.resolve({phoneState: "ended"});
				}
				if(call.isOutgoing && !call.hasConnected){
					//  Dialing out
					this.resolve({phoneState: "outgoing call"});
				}
				if(!call.isOutgoing && !call.hasConnected && !call.hasEnded){
					//  Call is incoming
					this.resolve({phoneState: "incoming call"});
				}
				if(call.hasConnected && !call.hasEnded){
					//  Call is ongoing
					this.resolve({phoneState: "ongoing call"});
				}
			}
		}, {
			protocols: [CXCallObserverDelegate]
		}),

		registerListener: function(){
			return new Promise((resolve, reject) => {
				try{
					this.callObserver = new CXCallObserver();

					let myCallDelegate = this.phoneDelegate.alloc().initWithResolveReject(resolve, reject);
					this.callObserver.setDelegateQueue(myCallDelegate, null);
					console.log("phone listener registered");
				} catch(error) {
					reject({error: error});
				}
			})
		}
	}

Where the delegate with the method [callObserverCallChanged](https://developer.apple.com/reference/callkit/cxcallobserverdelegate/1649009-callobserver?language=objc) is registered in the function "registerListener" using [CXCallObserver.setDelegate:queue](https://developer.apple.com/reference/callkit/cxcallobserver/1648998-setdelegate?language=objc)

The delegate is registered without any error since the last console log is executed inside the try.

The problem is: the method "callObserverCallChanged" is never executed. It does not matter if calls are incoming, outgoing or on going.

**Comment by tsonevn** [comment]
Hi @Timothylawler,
Thank you for contacting us and for the sample code.

We reviewed the attached code, however, we were enabled to find something that could lead to this behavior.
Regarding that, it would help if you could provide sample project, which demonstrates, what is expected as a final result and will also help us to debug it on our side. Then we will be able to provide some solution.

**Comment by Timothylawler** [comment]
Hi @tsonevn 
I have put up a github repo here: [repo](https://github.com/Timothylawler/sampleAppForCXCallObserver) with a very minimal application to demonstrate the behaviour.

Installation and steps to reproduce, this I have my self followed and verified that it reproduces the problem:

1. git clone https://github.com/Timothylawler/sampleAppForCXCallObserver.git
2. cd sampleAppForCXCallObserver
3. tns platform add ios
4. yarn install (I used yarn)
5. tns prepare ios
6. enter xcode, add development team and launch the application through xcode targeting an Iphone6s ios version 10.2.1
7. When the application starts it should log "registering phone listener" and "phone listener registered"
8. Call the device from another device.

Expected result after step 8: 
I am expecting log messages saying (in order of appearence):"This log is not triggering", "Gotten new phone state!", "incoming call"

Observed result after step 8: 
Nothing more than the two first log messages from step 7.


In the code at app/app.component.ts I am requiring app/native-module/phone-listener as phoneListener and call in onNgInit, phoneListener.registerListener

**Comment by Timothylawler** [comment]
The CXCallObserver+CXCallObserverDelegate works on native ios (Swift) and in react native (bridging Swift) so I know that there is nothing wrong with that.

**Comment by tsonevn** [comment]
Hi @Timothylawler,
Thank you for the attached sample project.
We reviewed it and found that this issue has been related to the fact that `myCallDelegate` property will be destroyed before firing `callObserverCallChanged` event. 
To resolve this case you could assign the property to `this`, which will allow firing the event properly and you will be able to handle incoming and outgoing calls.
For example:
index.ios.js
```


	module.exports = {
		phoneDelegate: NSObject.extend({
			initWithResolveReject: function(resolve, reject){
				var self = this.super.init();
				if(self){
					this.resolve = resolve;
					this.reject = reject;
				}
				return self;
			},

			callObserverCallChanged: function(observer, call){
				console.log("This log is not triggering");
				if(call.hasEnded){
					//  call has ended
					console.log("ended");
				}
				if(call.isOutgoing && !call.hasConnected){
					//  Dialing out
					console.log("outgoing call");
				}
				if(!call.isOutgoing && !call.hasConnected && !call.hasEnded){
					//  Call is incoming
					console.log("Call is incoming");
				}
				if(call.hasConnected && !call.hasEnded){
					//  Call is ongoing
					console.log( "ongoing call");
				}
			}
		}, {
			protocols: [CXCallObserverDelegate]
		}),

		registerListener: function(){
			return new Promise((resolve, reject) => {
				try{
					this.callObserver = new CXCallObserver();

					this.myCallDelegate = this.phoneDelegate.alloc().initWithResolveReject(resolve, reject);
					this.callObserver.setDelegateQueue(this.myCallDelegate, null);
					console.log("phone listener registered");
				} catch(error) {
					reject({error: error});
				}
			})
		}
	}
```

**Comment by Timothylawler** [comment]
@tsonevn 
Well this is embarrassing... Thank you for your time and the solution. It works like a charm as it should. I wonder what went through my head when the only thing i did not assign the class was the delegate. Have a great day @tsonevn!
