### ISSUE TITLE
Binding converter inconsistently called with different objects 

### ISSUE THREAD

**Issue by csell5** [NativeScript/NativeScript#410]
@tjvantoll  and I have been working through Binding Converters and trying to put something in place for an app. We're seeing some inconsistent behavior with what the runtime and what it passes into the converter and how many times it's actually called.

It appears when the converter is called it sometimes gets passed the observable rather than the object in that observable. Mind you, we're doing this in a ListView. 

In a list of ~150 items it seems to happen a handful of times but only initially. Now we we're always passed the object expected for ever record so the times when the converter passed the observable was in fact extra calls that we weren't expecting.

* View: https://github.com/tjvantoll/summer-of-nativescript/blob/master/august/DemoCode/app/Views/DataBinding/DataBinding.xml#L9
* Converter: https://github.com/tjvantoll/summer-of-nativescript/blob/master/august/DemoCode/app/Views/DataBinding/DataBinding.js#L39-L53
* Demo app: Demo app: https://github.com/tjvantoll/summer-of-nativescript/tree/master/august/DemoCode

**Comment by nsndeck** [comment]
The issue will be fixed for almost all scenarios using ios 8+. However for ios 7 converter will be called 2 times for a row (due to some initial measure), but at least will be called with the correct "bindingContext".
