### ISSUE TITLE
Problem with plugin upgrade - nativescript-videoplayer / nativescript-exoplayer

### ISSUE THREAD

**Issue by bnussey** [NativeScript/NativeScript#4104]
### Tell us about the problem
I'm a contributor on `nativescript-videoplayer` and `nativescript-exoplayer` (a fork from `nativescript-videoplayer`) and am attempting to update them to 3.0. 

You can review my 3.0 branch here -- https://github.com/NathanaelA/nativescript-exoplayer/tree/3.0-update

I've completed updating videoplayer-common.ts to conform to new standards but am having issues with replacing `onSetNativeValue` in PropertyMetaData. As I understand it, this has transitioned to `setNative`. Ultimately I am trying to trigger a callback in the videoplayer.ios.ts when the videoSource property is changed.

Existing line:

`// (<proxy.PropertyMetadata>common.Video.videoSourceProperty.metadata).onSetNativeValue = onVideoSourcePropertyChanged;`

New line:

```
    [videoSourceProperty.setNative](value: AVPlayerItem) {
        console.log("value", value);
    }
```

However this doesn't seem to be triggered when the videoSource is updated. This is changed here: https://github.com/NathanaelA/nativescript-exoplayer/blob/3.0-update/videoplayer-common.ts#L28 and is a result of https://github.com/NathanaelA/nativescript-exoplayer/blob/3.0-update/video-source/video-source.ios.ts

Would appreciate guidance here.

**Comment by PeterStaev** [comment]
@bnussey , I suspect the problem is that because the type for that property is a complex object the default `equalityComparer` of `===` fails to detect a new object is being set and does not trigger the native value. set. Can you try to define a custom `equalityComparer` for the `videoSource` property and see if that will help?

**Comment by bnussey** [comment]
Hey @PeterStaev that doesn't seem to have any impact.. have I missed something else?

**Comment by PeterStaev** [comment]
@bnussey , sadly no other ideas :( The `videoSource` property is a bit of a special case as seems the `VideoSource` object also has `android` and `ios` properties for the native values. So not sure how the new properties should work in this case...

**Comment by bnussey** [comment]
Hey @PeterStaev i can't seem to even get it working for standard string properties.. no callback to the specific platform files.. so perhaps there is some other issue that I've missed?

**Comment by PeterStaev** [comment]
Strange, simple properties are working fine. One other thing I spot is this line: https://github.com/NathanaelA/nativescript-exoplayer/blob/3.0-update/videoplayer.ios.ts#L15 this is no longer needed as it is handled by the line above it `export * from ....`

**Comment by bnussey** [comment]
Hey @PeterStaev thanks for your reply. Will give that a shot. So simple properties are working fine for you?

**Comment by PeterStaev** [comment]
Yes, I've had no problems with the DropDown and GridView widgets.

**Comment by bnussey** [comment]
Fixed and released.
