### ISSUE TITLE
TabView with icons only

### ISSUE THREAD

**Issue by henrychavez** [NativeScript/NativeScript#4105]
**IOS only**

When we try to use the TabView with icons only, the icon it's not centered.

With this code in the TabView class and TabViewItem the icons will be centered if the title it's not present of course:

`tabBarItem.imageInsets = UIEdgeInsetsMake(6, 0, -6, 0);`

please consider this to have a better TabView for iOS. I try to find another solution but it's difficult create a new TabView to only add this line of code and have a better UI.

**Comment by tsonevn** [comment]
Hi @henrychavez,
Thank you for reporting this issue.
I review that case, however, at this time there is not an easy way to centered the image for the TabView item for iOS.
Regarding that, we will research further how it could be done and you could keep track on the issue for some further info.

**Comment by henrychavez** [comment]
Hi @tsonevn ,
Thanks for answer me quickly.

I used the code that I wrote before to center the icon in the TabViewItem but in the version 2.5.2 and works fine.

I modified the code for tab-view.ios.ts in _update() function for TabViewItem class and _addTabs() function for TabView class.
```
var tabBarItem = UITabBarItem.alloc().initWithTitleImageTag((this.title || ""), icon,
                                                            this._parent.items.indexOf(this));
if (!icon) {
  if (types.isFunction((<any>tabBarItem).setTitlePositionAdjustment)) {
    (<any>tabBarItem).setTitlePositionAdjustment({ horizontal: 0, vertical: -20 });
  }
  else {
    tabBarItem.titlePositionAdjustment = { horizontal: 0, vertical: -20 };
  }
}
else  {
  tabBarItem.imageInsets = UIEdgeInsetsMake(6, 0, -6, 0);
}
```

I reviewed the code for the 3.0.0 version and maybe the best way to implement this is with a function: 

```
function updateIconPosition(tabBarItem: UITabBarItem) {
    tabBarItem.imageInsets = UIEdgeInsetsMake(6, 0, -6, 0);
}
```

then can be called in the _update() function for TabViewItem class and setViewControllers() function for TabView class.

```
const tabBarItem = UITabBarItem.alloc().initWithTitleImageTag((item.title || ""), icon, i);
if (!icon) {
  updateItemTitlePosition(tabBarItem);
}
else {
  updateIconPosition(tabBarItem);
}
```

Sorry if my english it's not the best :D

**Comment by tsonevn** [comment]
Hi @henrychavez,
I reviewed the given code sample and indeed setting up new `UIEdgeInsets`  in setViewControllers in `tab-view.ios.js` file will solve this case.

Regarding that, you could create your own pull request in `tns-core-modules`, which implements this functionality. Something that I could suggest is to check if there is a title available for the `Tab` and if not then set up the new `UIEdgrInsets`. For example:
```
  TabView.prototype.setViewControllers = function (items) {
        var length = items ? items.length : 0;
        if (length === 0) {
            this._ios.viewControllers = null;
            return;
        }
        var controllers = NSMutableArray.alloc().initWithCapacity(length);
        var states = getTitleAttributesForStates(this);
        for (var i = 0; i < length; i++) {
            var item = items[i];
            var newController = void 0;
            if (item.view.ios instanceof UIViewController) {
                newController = item.view.ios;
            }
            else {
                newController = UIViewController.new();
                newController.view.addSubview(item.view.ios);
            }
            item.setViewController(newController);
            var icon = this._getIcon(item.iconSource);
            var tabBarItem = UITabBarItem.alloc().initWithTitleImageTag((item.title || ""), icon, i);
            if (!icon) {
                updateItemTitlePosition(tabBarItem);
            }
            else if(!item.title){
               tabBarItem.imageInsets = UIEdgeInsetsMake(6, 0, -6, 0);
             }
            applyStatesToItem(tabBarItem, states);
            newController.tabBarItem = tabBarItem;
            controllers.addObject(newController);
        }
        this._ios.viewControllers = controllers;
        this._ios.customizableViewControllers = null;
        this._ios.moreNavigationController.delegate = this._moreNavigationControllerDelegate;
    };
```
For further help about the pull request, you could review our [contribute article](https://www.nativescript.org/contribute)

**Comment by henrychavez** [comment]
@tsonevn 
Great! I'll do it tonight.

Thanks.

**Comment by SvetoslavTsenov** [comment]
Hey @henrychavez I just merged your pull request, so the feature will be available with tns-core-modules@next
