### ISSUE TITLE
Can not find modules 

### ISSUE THREAD

**Issue by pap5508** [NativeScript/NativeScript#4106]
`app/app.component.ts(3,60): error TS2307: Cannot find module 'application-settings'.

app/app.component.ts(8,27): error TS2307: Cannot find module 'platform'.
app/chat/addContactToGrp.component.ts(2,22): error TS2307: Cannot find module 'ui/page'.
app/chat/addContactToGrp.component.ts(7,33): error TS2307: Cannot find module 'data/observable-array'.
app/chat/addContactToGrp.component.ts(9,51): error TS2307: Cannot find module 'connectivity'.
app/chat/editChatContact.component.ts(2,23): error TS2307: Cannot find module 'color'.
app/chat/editChatContact.component.ts(3,51): error TS2307: Cannot find module 'connectivity'.
app/chat/editChatContact.component.ts(4,27): error TS2307: Cannot find module 'ui/animation'.
app/chat/editChatContact.component.ts(5,22): error TS2307: Cannot find module 'ui/core/view'.
app/chat/editChatContact.component.ts(6,24): error TS2307: Cannot find module 'ui/dialogs'.
app/chat/editChatContact.component.ts(7,22): error TS2307: Cannot find module 'ui/page'.
app/chat/editChatContact.component.ts(8,27): error TS2307: Cannot find module 'ui/text-field'.
app/chat/editChatContact.component.ts(12,49): error TS2307: Cannot find module 'application-settings'.
app/chat/editGroupChat.component.ts(3,22): error TS2307: Cannot find module 'ui/page'.
app/chat/editGroupChat.component.ts(4,32): error TS2307: Cannot find module 'ui/dialogs'.
app/chat/editGroupChat.component.ts(8,23): error TS2307: Cannot find module 'color'.
app/chat/editGroupChat.component.ts(9,22): error TS2307: Cannot find module 'ui/core/view'.
app/chat/editGroupChat.component.ts(10,22): error TS2307: Cannot find module 'application'.
app/chat/editGroupChat.component.ts(11,27): error TS2307: Cannot find module 'platform'.
app/chat/editGroupChat.component.ts(12,23): error TS2307: Cannot find module 'platform'.
app/chat/editGroupChat.component.ts(13,51): error TS2307: Cannot find module 'connectivity'.
app/chat/editGroupChat.component.ts(16,33): error TS2307: Cannot find module 'data/observable-array'.
app/chat/editGroupChat.component.ts(17,27): error TS2307: Cannot find module 'application-settings'.
app/chat/groupChatDetail.component.ts(3,22): error TS2307: Cannot find module 'ui/page'.
app/chat/groupChatDetail.component.ts(4,32): error TS2307: Cannot find module 'ui/dialogs'.
app/chat/groupChatDetail.component.ts(9,51): error TS2307: Cannot find module 'connectivity'.
app/chat/groupChatDetail.component.ts(10,23): error TS2307: Cannot find module 'color'.
app/chat/groupChatDetail.component.ts(13,26): error TS2307: Cannot find module 'ui/list-view'.
app/chat/groupChatDetail.component.ts(14,26): error TS2307: Cannot find module 'ui/text-view'.
app/chat/groupChatDetail.component.ts(15,22): error TS2307: Cannot find module 'ui/core/view'.
app/chat/groupChatDetail.component.ts(16,22): error TS2307: Cannot find module 'application'.
app/chat/groupChatDetail.component.ts(17,33): error TS2307: Cannot find module 'data/observable-array'.
app/chat/groupChatDetail.component.ts(18,27): error TS2307: Cannot find module 'platform'.
app/chat/groupChatDetail.component.ts(19,23): error TS2307: Cannot find module 'platform'.
app/chat/groupChatDetail.component.ts(20,38): error TS2307: Cannot find module 'application-settings'.
app/chat/groupChatDetail.component.ts(23,29): error TS2307: Cannot find module 'image-source'.
app/chat/groupChatDetail.component.ts(24,36): error TS2307: Cannot find module 'file-system'.
app/chat/groupChatDetail.component.ts(25,21): error TS2307: Cannot find module 'file-system'.
app/chat/groupChatDetail.component.ts(26,24): error TS2307: Cannot find module 'ui/enums'.
app/chat/groupChatDetail.component.ts(27,29): error TS2307: Cannot find module 'utils/utils'.
app/chat/groupChatDetail.component.ts(30,24): error TS2307: Cannot find module 'utils/utils'.
app/chat/groupChatDetail.component.ts(651,19): error TS2304: Cannot find name 'GamepadButton'.
app/chat/imageViewer.component.ts(3,22): error TS2307: Cannot find module 'ui/page'.
app/chat/imageViewer.component.ts(4,32): error TS2307: Cannot find module 'ui/dialogs'.
app/chat/imageViewer.component.ts(9,51): error TS2307: Cannot find module 'connectivity'.
app/chat/imageViewer.component.ts(10,23): error TS2307: Cannot find module 'color'.
app/chat/imageViewer.component.ts(12,33): error TS2307: Cannot find module 'data/observable-array'.
app/chat/imageViewer.component.ts(13,22): error TS2307: Cannot find module 'application'.
app/chat/imageViewer.component.ts(14,27): error TS2307: Cannot find module 'platform'.
app/chat/imageViewer.component.ts(15,23): error TS2307: Cannot find module 'platform'.
app/chat/imageViewer.component.ts(17,27): error TS2307: Cannot find module 'data/observable'.
app/chat/imageViewer.component.ts(18,45): error TS2307: Cannot find module 'ui/scroll-view'.
app/chat/imageViewer.component.ts(19,39): error TS2307: Cannot find module 'image-source'.
app/chat/imageViewer.component.ts(20,28): error TS2307: Cannot find module 'data/observable'.
app/chat/imageViewer.component.ts(21,36): error TS2307: Cannot find module 'image-source'.
app/chat/imageViewer.component.ts(22,36): error TS2307: Cannot find module 'file-system'.
app/chat/imageViewer.component.ts(23,21): error TS2307: Cannot find module 'file-system'.
app/chat/imageViewer.component.ts(24,24): error TS2307: Cannot find module 'ui/enums'.
app/chat/imageViewer.component.ts(26,29): error TS2307: Cannot find module 'utils/utils'.
app/chat/previewImage.component.ts(3,22): error TS2307: Cannot find module 'ui/page'.
app/chat/previewImage.component.ts(4,32): error TS2307: Cannot find module 'ui/dialogs'.
app/chat/previewImage.component.ts(9,51): error TS2307: Cannot find module 'connectivity'.
app/chat/previewImage.component.ts(10,23): error TS2307: Cannot find module 'color'.
app/chat/previewImage.component.ts(14,26): error TS2307: Cannot find module 'ui/list-view'.
app/chat/previewImage.component.ts(15,26): error TS2307: Cannot find module 'ui/text-view'.
app/chat/previewImage.component.ts(16,22): error TS2307: Cannot find module 'ui/core/view'.
app/chat/previewImage.component.ts(17,22): error TS2307: Cannot find module 'application'.
app/chat/previewImage.component.ts(18,27): error TS2307: Cannot find module 'platform'.
app/chat/previewImage.component.ts(19,23): error TS2307: Cannot find module 'platform'.
app/chat/previewImage.component.ts(21,23): error TS2307: Cannot find module 'ui/image'.
app/chat/previewImage.component.ts(22,39): error TS2307: Cannot find module 'image-source'.
app/chat/previewImage.component.ts(23,33): error TS2307: Cannot find module 'data/observable-array'.
app/chat/previewImage.component.ts(24,28): error TS2307: Cannot find module 'data/observable'.
app/chat/previewImage.component.ts(25,36): error TS2307: Cannot find module 'image-source'.
app/chat/previewImage.component.ts(29,60): error TS2307: Cannot find module 'application-settings'.
app/chat/previewImage.component.ts(30,30): error TS2307: Cannot find module 'ui/gestures'.
app/chat/previewImage.component.ts(31,27): error TS2307: Cannot find module 'ui/animation'.
app/chat/previewImage.component.ts(32,36): error TS2307: Cannot find module 'file-system'.
app/chat/previewImage.component.ts(33,21): error TS2307: Cannot find module 'file-system'.
app/chat/previewImage.component.ts(34,24): error TS2307: Cannot find module 'ui/enums'.
app/chat/previewImageGrp.component.ts(3,22): error TS2307: Cannot find module 'ui/page'.
app/chat/previewImageGrp.component.ts(4,32): error TS2307: Cannot find module 'ui/dialogs'.
app/chat/previewImageGrp.component.ts(9,51): error TS2307: Cannot find module 'connectivity'.
app/chat/previewImageGrp.component.ts(10,23): error TS2307: Cannot find module 'color'.
app/chat/previewImageGrp.component.ts(14,26): error TS2307: Cannot find module 'ui/list-view'.
app/chat/previewImageGrp.component.ts(15,26): error TS2307: Cannot find module 'ui/text-view'.
app/chat/previewImageGrp.component.ts(16,22): error TS2307: Cannot find module 'ui/core/view'.
app/chat/previewImageGrp.component.ts(17,22): error TS2307: Cannot find module 'application'.
app/chat/previewImageGrp.component.ts(18,27): error TS2307: Cannot find module 'platform'.
app/chat/previewImageGrp.component.ts(19,23): error TS2307: Cannot find module 'platform'.

Executing before-prepare hook from /Users/admin/Desktop/Project1/hooks/before-prepare/nativescript-plugin-firebase.js
Preparing project...

Could not find folder: /Users/admin/Desktop/Project1/platforms/ios/Hieber/app/tns_modules/tns-core-modules
`

I have just updated my package.json file
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.project.app",
    "tns-ios": {
      "version": "3.0.0"
    }
  },
  "dependencies": {
    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/router": "~4.0.0",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "email-validator": "^1.0.7",
    "latest-version": "^3.1.0",
    "moment": "^2.18.1",
    "nativescript-angular": "^3.0.0",
    "nativescript-background-http": "2.5.1",
    "nativescript-camera": "3.0.0",
    "nativescript-couchbase": "^1.0.17",
    "nativescript-imagepicker": "^2.5.1",
    "nativescript-iqkeyboardmanager": "^1.0.1",
    "nativescript-pdf-view": "^1.2.1",
    "nativescript-plugin-firebase": "3.11.0",
    "nativescript-sqlite": "^1.1.3",
    "nativescript-theme-core": "~1.0.3",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.2.0",
    "tns-core-modules": "^3.0.0",
    "tns-platform-declarations": "^2.4.4"
  },
  "devDependencies": {
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.3.5",
    "typescript": "~2.2.0",
    "zone.js": "^0.8.2"
  }
}
```

and tsconfig.json 
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": false,
        "lib": [
            "es2016"
        ]
    },
    "exclude": [
        "node_modules",
        "platforms",
        "**/*.aot.ts",
        "typingz-i386",
        "typingz-x86_64"
    ]
}
```

**Comment by pap5508** [comment]
Project successfully prepared (ios)
Executing after-prepare hook from /Users/admin/Desktop/Begis/hieberapp/hooks/after-prepare/firebase-build-gradle.js
Configure firebase
Executing after-prepare hook from /Users/admin/Desktop/Begis/hieberapp/hooks/after-prepare/firebase-copy-google-services.js
Executing after-prepare hook from /Users/admin/Desktop/Begis/hieberapp/hooks/after-prepare/nativescript-dev-android-snapshot.js
Executing after-prepare hook from /Users/admin/Desktop/Begis/hieberapp/hooks/after-prepare/nativescript-plugin-firebase.js
TypeError: Cannot read property 'stopExecution' of undefined
    at maybePromise.then (/usr/local/lib/node_modules/nativescript/lib/common/services/hooks-service.js:110:52)

**Comment by vakrilov** [comment]
Hi,
You will probably have to update your `tsconfig` file as described [here](https://github.com/NativeScript/NativeScript/blob/v3.0.0/Modules30Changes.md#typescript).
Also you can check the [release notes](http://docs.nativescript.org/releases/Cross-Platform%20Modules) so that you know which of the other changes might affect your project

**Comment by pap5508** [comment]
@vakrilov  : I have implemented those changes but still getting error 
`file:///app/tns_modules/nativescript-angular/view-util.js:7:35: JS ERROR Error: Could not find module 'ui/builder/special-properties'. Computed path '/Users/admin/Library/Developer/CoreSimulator/Devices/0C8655B0-E129-4D98-B0E2-77410AFDD463/data/Containers/Bundle/Application/6DB1E78B-FE27-4121-BAE5-3FCA11B9443D/test.app/app/tns_modules/ui/builder/special-properties'.
May  4 12:21:10 win-0ld4psbiajp com.apple.CoreSimulator.SimDevice.0C8655B0-E129-4D98-B0E2-77410AFDD463.launchd_sim[438] (UIKitApplication:com.test.app[0xe270][476][55919]): Service exited due to Segmentation fault: 11
`


Please guide me to solve this error

**Comment by NickIliev** [comment]
@pap5508 Apart from the changes needed to be made in your **tsconfig.json** you will also need to verify that each of the plugins used has a released compatible version with nativeScript 3.0.0
At first glance, I saw that you are using **nativescript-background-http** and **nativescript-imagepicke**r with versions 2.5.1. Both plugins are already migrated to be compatible with NativeScript 3.0.0 and **their 3.0.0 versions will be published any time now**.

Basicaly your package.json and tsconfig.json should look like this (without the third partu plugins)

package.json
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.project.app",
    "tns-ios": {
      "version": "3.0.0"
    },
    "tns-android": {
      "version": "3.0.0"
    }
  },
  "dependencies": {
    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/router": "~4.0.0",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "email-validator": "^1.0.7",
    "latest-version": "^3.1.0",
    "moment": "^2.18.1",
    "nativescript-angular": "^3.0.0",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.10",
    "rxjs": "5.2.0",
    "tns-core-modules": "^3.0.0",
    "tns-platform-declarations": "^3.0.0"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.4.2",
    "typescript": "~2.3.2",
    "zone.js": "^0.8.2"
  }
}
```

If you are using **tns-platform-declarations** 3.0.0 you will also need to modify your references.d.ts file to contain **only** the following
```
/// <reference path="./node_modules/tns-platform-declarations/android.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/ios.d.ts" />
```

and finally the **tsconfig.json**
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": false,
        "lib": [
            "es6",
            "dom"
        ],
        "baseUrl": ".",
        "paths": {
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms",
        "**/*.aot.ts",
        "typingz-i386",
        "typingz-x86_64"
    ]
}
```

After this is done I would recommend to add each plugin (assuming it is using the latest published version explicitly compatible with NativeScript 3.0.0) and rebuild your app.

**Comment by pap5508** [comment]
@NickIliev : Resolved all the error except one Error for angular router 
Application install successfully but After splash screen pop up only white screen on Device
![simulator screen shot 5 may 2017 10 10 56](https://cloud.githubusercontent.com/assets/8488715/25738030/2cc1a004-317b-11e7-9445-d814ab509700.png)

and throws following error on console

CONSOLE LOG file:///app/app.component.js:70:24: firebase.init done
CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1091:24: ERROR Error: Uncaught (in promise): Error: Invalid value: text
	file:///app/tns_modules/tns-core-modules/ui/core/properties/properties.js:935:28 [angular]
	set@file:///app/tns_modules/tns-core-modules/ui/core/properties/properties.js:57:50 [angular]
	setPropertyInternal@file:///app/tns_modules/nativescript-angular/view-util.js:196:17 [angular]
	setProperty@file:///app/tns_modules/nativescript-angular/view-util.js:155:37 [angular]
	setAttribute@file:///app/tns_modules/nativescript-angular/renderer.js:126:41 [angular]
	setAttribute@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:13218:35 [angular]
	createElement@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:9341:34 [angular]
	createViewNodes@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:11963:57 [angular]
	callViewAction@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:12381:28 [angular]
	execComponentViewsAction@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:12320:27 [angular]
	createViewNodes@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:12032:29 [angular]
	createRootView@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:11910:20 [angular]
	callWithDebugContext@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:13048:47 [angular]
	create@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:9831:60 [angular]
	createComponent@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:10033:68 [angular]
	activateOnGoForward@file:///app/tns_modules/nativescript-angular/router/page-router-outlet.js:153:70 [angular]
	activateWith@file:///app/tns_modules/nativescript-angular/router/page-router-outlet.js:139:37 [angular]
	placeComponentIntoOutlet@file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4516:28 [angular]
	activateRoutes@file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4497:50 [angular]
	file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4433:72 [angular]
	forEach@[native code] [angular]
	activateChildRoutes@file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4433:36 [angular]
	activate@file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4407:33 [angular]
	file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4024:30 [angular]
	file:///app/tns_modules/rxjs/Observable.js:110:25 [angular]
	__tryOrSetError@file:///app/tns_modules/rxjs/Subscriber.js:245:20 [angular]
	next@file:///app/tns_modules/rxjs/Subscriber.js:187:42 [angular]
	_next@file:///app/tns_modules/rxjs/Subscriber.js:125:30 [angular]
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23 [angular]
	_next@file:///app/tns_modules/rxjs/operator/map.js:83:30 [angular]
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23 [angular]
	notifyNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:143:34 [angular]
	_next@file:///app/tns_modules/rxjs/InnerSubscriber.js:23:31 [angular]
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23 [angular]
	_next@file:///app/tns_modules/rxjs/operator/map.js:83:30 [angular]
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23 [angular]
	_subscribe@file:///app/tns_modules/rxjs/observable/ScalarObservable.js:49:28 [angular]
	_trySubscribe@file:///app/tns_modules/rxjs/Observable.js:57:35 [angular]
	subscribe@file:///app/tns_modules/rxjs/Observable.js:45:40 [angular]
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26 [angular]
	_innerSub@file:///app/tns_modules/rxjs/operator/mergeMap.js:130:55 [angular]
	_tryNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:127:23 [angular]
	_next@file:///app/tns_modules/rxjs/operator/mergeMap.js:110:26 [angular]
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23 [angular]
	notifyNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:143:34 [angular]
	_next@file:///app/tns_modules/rxjs/InnerSubscriber.js:23:31 [angular]
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23 [angular]
	_next@file:///app/tns_modules/rxjs/operator/map.js:83:30 [angular]
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23 [angular]
	_complete@file:///app/tns_modules/rxjs/operator/reduce.js:119:34 [angular]
	complete@file:///app/tns_modules/rxjs/Subscriber.js:114:27 [angular]
	_complete@file:///app/tns_modules/rxjs/operator/mergeMap.js:135:38 [angular]
	complete@file:///app/tns_modules/rxjs/Subscriber.js:114:27 [angular]
	_subscribe@file:///app/tns_modules/rxjs/observable/ArrayObservable.js:116:32 [angular]
	_trySubscribe@file:///app/tns_modules/rxjs/Observable.js:57:35 [angular]
	subscribe@file:///app/tns_modules/rxjs/Observable.js:45:40 [angular]
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26 [angular]
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26 [angular]
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26 [angular]
	_innerSub@file:///app/tns_modules/rxjs/operator/mergeMap.js:130:55 [angular]
	_tryNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:127:23 [angular]
	_next@file:///app/tns_modules/rxjs/operator/mergeMap.js:110:26 [angular]
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23 [angular]
	notifyNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:143:34 [angular]
	_next@file:///app/tns_modules/rxjs/InnerSubscriber.js:23:31 [angular]
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23 [angular]
	_next@file:///app/tns_modules/rxjs/operator/map.js:83:30 [angular]
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23 [angular]
	notifyNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:143:34 [angular]
	_next@file:///app/tns_modules/rxjs/InnerSubscriber.js:23:31 [angular]
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23 [angular]
	notifyComplete@file:///app/tns_modules/rxjs/operator/every.js:53:30 [angular]
	_complete@file:///app/tns_modules/rxjs/operator/every.js:70:28 [angular]
	complete@file:///app/tns_modules/rxjs/Subscriber.js:114:27 [angular]
	_complete@file:///app/tns_modules/rxjs/operator/mergeMap.js:135:38 [angular]
	complete@file:///app/tns_modules/rxjs/Subscriber.js:114:27 [angular]
	_subscribe@file:///app/tns_modules/rxjs/observable/ArrayObservable.js:116:32 [angular]
	_trySubscribe@file:///app/tns_modules/rxjs/Observable.js:57:35 [angular]
	subscribe@file:///app/tns_modules/rxjs/Observable.js:45:40 [angular]
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26 [angular]
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26 [angular]
	_innerSub@file:///app/tns_modules/rxjs/operator/mergeMap.js:130:55 [angular]
	_tryNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:127:23 [angular]
	_next@file:///app/tns_modules/rxjs/operator/mergeMap.js:110:26 [angular]
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23 [angular]
	notifyComplete@file:///app/tns_modules/rxjs/operator/every.js:53:30 [angular]
	_complete@file:///app/tns_modules/rxjs/operator/every.js:70:28 [angular]
	complete@file:///app/tns_modules/rxjs/Subscriber.js:114:27 [angular]
	_complete@file:///app/tns_modules/rxjs/operator/mergeMap.js:135:38 [angular]
	complete@file:///app/tns_modules/rxjs/Subscriber.js:114:27 [angular]
	_subscribe@file:///app/tns_modules/rxjs/observable/ArrayObservable.js:116:32 [angular]
	_trySubscribe@file:///app/tns_modules/rxjs/Observable.js:57:35 [angular]
	subscribe@file:///app/tns_modules/rxjs/Observable.js:45:40 [angular]
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26 [angular]
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26 [angular]
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26 [angular]
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26 [angular]
	_innerSub@file:///app/tns_modules/rxjs/operator/mergeMap.js:130:55 [angular]
	_tryNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:127:23 [angular]
	_next@file:///app/tns_modules/rxjs/operator/mergeMap.js:110:26 [angular]
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23 [angular]
	_next@file:///app/tns_modules/rxjs/operator/map.js:83:30 [angular]
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23 [angular]

**Comment by NickIliev** [comment]
@pap5508 in your archive the **package.json** and the other files included at root level are missing - can you please provide them so we can investigate your case just as it is happening in your environment

**Comment by pap5508** [comment]
@NickIliev : Please find root level Files


[Archive.zip](https://github.com/NativeScript/NativeScript/files/978715/Archive.zip)

**Comment by alaska321** [comment]
You have set keyboardtype="text" somewhere in your templates.
Available values are here.
http://docs.nativescript.org/api-reference/modules/_ui_enums_.keyboardtype.html

**Comment by NickIliev** [comment]
@alaska is right - there are few places where keyboard type is set to text.
Here is the list of available types:
```
export type KeyboardType = "datetime" | "phone" | "number" | "url" | "email";
```

The only difference is tnat in NativeScript 2.5.x setting invalid keyboard type was not causing your application to throw (but to use the default **string**) while with NativeScript 3.x.x we have now validations and any invalid type values will throw

**Comment by pap5508** [comment]
@alaska321 @NickIliev  : thanks a lot now app working fine..!! all changes implemented
