### ISSUE TITLE
WebView doesn't load

### ISSUE THREAD

**Issue by buu700** [NativeScript/NativeScript#4107]
I've tried several variants of the following in an iOS 10.2 simulator on OS X El Capitan with NativeScript 3.0.0:

```
const webView = new WebView();
webView.on(WebView.loadStartedEvent, () => console.log('balls'));
webView.src = '<html></html>';
```

The rest of my application continues to load as expected with no crashing or anything, but the console log never fires.

**Comment by vakrilov** [comment]
I think this event will only fire if you set the `src` to a URL. 
Did the same code work with NativeScript 2.5.x?

**Comment by buu700** [comment]
Ah, got it, thanks. If that is the case, https://docs.nativescript.org/cookbook/ui/web-view may need to be updated. I've only tried with 3.0.0, so not sure about 2.5.

Would a file:// URL trigger that event? /file.html had the same effect. (I didn't properly test with remote URLs because with http:// I got an error that I needed to update some configuration file and with https:// I got some dylib stack trace that might've just been an issue with my machine.)

**Comment by NickIliev** [comment]
Hey, @buu700, I have tested your case at my side and it works as expected (the loaded event is triggered with both URL and HTML code). The only difference is that I am adding the WebView to the layout.
e.g.
```
const webView = new WebView();
webView.on(WebView.loadStartedEvent, () => console.log('===== TEST TEST TEST ====='));
webView.src = '<html></html>'; // works also with "~/index.html" or with "https://docs.nativescript.org"

page.content = webView; // now that the web-view is part of the layout the loaded event will be triggered
```

Test application can be found [here](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/NativeScript/issue_4107/app/main-page.ts#L17-L26)

**Comment by buu700** [comment]
Ah, I see, thanks! It wasn't clear from the documentation that the webview actually needed to be added to the page before it would load.
