### ISSUE TITLE
App crash Invalid color

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/NativeScript#4108]
_From @naturalfreak on May 3, 2017 15:31_

I'm using nativescript 3.0.
tns version 3.0 ( android )

> An uncaught Exception occurred on "main" thread.
> com.tns.NativeScriptException: 
> Calling js method getView failed
> 
> Error: Invalid color: 
> File: "file:///data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js, line: 13025, column: 8
> 
> StackTrace: 
> 	Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 993, column: 33
> 	Frame: function:'Color', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/color/color-common.js', line: 24, column: 27
> 	Frame: function:'Color', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/color/color.js', line: 6, column: 42
> 	Frame: function:'valueConverter', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/styling/style-properties.js', line: 817, column: 176
> 	Frame: function:'', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 627, column: 32
> 	Frame: function:'ViewUtil.setStyle', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/nativescript-angular/view-util.js', line: 254, column: 31
> 	Frame: function:'NativeScriptRenderer.setStyle', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/nativescript-angular/renderer.js', line: 145, column: 23
> 	Frame: function:'DebugRenderer2.setStyle', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 13237, column: 23
> 	Frame: function:'setElementStyle', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 9520, column: 18
> 	Frame: function:'checkAndUpdateElementValue', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 9449, column: 13
> 	Frame: function:'checkAndUpdateElementInline', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 9390, column: 24
> 	Frame: function:'checkAndUpdateNodeInline', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 12084, column: 23
> 	Frame: function:'checkAndUpdateNode', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 12059, column: 16
> 	Frame: function:'debugCheckAndUpdateNode', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 12688, column: 59
> 	Frame: function:'debugCheckRenderNodeFn', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 12667, column: 13
> 	Frame: function:'', file:'', line: 1147, column: 5
> 	Frame: function:'debugUpdateRenderer', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 12652, column: 21
> 	Frame: function:'checkAndUpdateView', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 12031, column: 14
> 	Frame: function:'callViewAction', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 12341, column: 17
> 	Frame: function:'execEmbeddedViewsAction', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 12313, column: 17
> 	Frame: function:'checkAndUpdateView', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 12027, column: 5
> 	Frame: function:'callWithDebugContext', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 13014, column: 42
> 	Frame: function:'debugCheckAndUpdateView', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 12554, column: 12
> 	Frame: function:'ViewRef_.detectChanges', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 10123, column: 63
> 	Frame: function:'ListViewComponent.detectChangesOnChild', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/nativescript-angular/directives/list-view-comp.js', line: 132, column: 17
> 	Frame: function:'ListViewComponent.onItemLoading', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/nativescript-angular/directives/list-view-comp.js', line: 118, column: 14
> 	Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 100, column: 32
> 	Frame: function:'ListViewAdapter.getView', file:'file:///data/data/org.nativescript.groceries/files/app/tns_modules/tns-core-modules/ui/list-view/list-view.js', line: 233, column: 24
> 
> 
> 	at com.tns.Runtime.callJSMethodNative(Native Method)
> 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
> 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
> 	at com.tns.Runtime.callJSMethod(Runtime.java:1047)
> 	at com.tns.Runtime.callJSMethod(Runtime.java:1028)
> 	at com.tns.Runtime.callJSMethod(Runtime.java:1018)
> 	at com.tns.gen.android.widget.BaseAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.getView(android.widget.BaseAdapter.java)
> 	at android.widget.AbsListView.obtainView(AbsListView.java:2346)
> 	at android.widget.ListView.makeAndAddView(ListView.java:1876)
> 	at android.widget.ListView.fillDown(ListView.java:702)
> 	at android.widget.ListView.fillFromTop(ListView.java:763)
> 	at android.widget.ListView.layoutChildren(ListView.java:1671)
> 	at android.widget.AbsListView.onLayout(AbsListView.java:2148)
> 	at android.view.View.layout(View.java:16692)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5445)
> 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
> 	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
> 	at android.view.View.layout(View.java:16692)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5445)
> 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
> 	at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:169)
> 	at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:123)
> 	at android.view.View.layout(View.java:16692)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5445)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
> 	at android.view.View.layout(View.java:16692)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5445)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
> 	at android.view.View.layout(View.java:16692)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5445)
> 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
> 	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
> 	at android.view.View.layout(View.java:16692)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5445)
> 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
> 	at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
> 	at android.view.View.layout(View.java:16692)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5445)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
> 	at android.view.View.layout(View.java:16692)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5445)
> 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
> 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
> 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
> 	at android.view.View.layout(View.java:16692)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5445)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
> 	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2684)
> 	at android.view.View.layout(View.java:16692)
> 	at android.view.ViewGroup.layout(ViewGroup.java:5445)
> 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2178)
> 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1938)
> 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1114)
> 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6068)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
> 	at android.view.Choreographer.doFrame(Choreographer.java:606)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
> 	at android.os.Handler.handleCallback(Handler.java:739)
> 	at android.os.Handler.dispatchMessage(Handler.java:95)
> 	at android.os.Looper.loop(Looper.java:148)
> 	at android.app.ActivityThread.main(ActivityThread.java:5539)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
> 

My package.json

```
"dependencies": {
    "@angular/animations": "^4.1.0",
    "@angular/common": "4.1.0",
    "@angular/compiler": "4.1.0",
    "@angular/core": "4.1.0",
    "@angular/forms": "4.1.0",
    "@angular/http": "4.1.0",
    "@angular/platform-browser": "4.1.0",
    "@angular/platform-browser-dynamic": "4.1.0",
    "@angular/router": "4.1.0",
    "nativescript-angular": "3.0.0",
    "nativescript-camera": "3.0.0",
    "nativescript-fresco": "^3.0.2",
    "nativescript-geolocation": "3.0.0",
    "nativescript-imagepicker": "./packages/nativescript-imagepicker-3.0.0.tgz",
    "nativescript-iqkeyboardmanager": "1.0.1",
    "nativescript-telerik-ui-pro": "rc",
    "reflect-metadata": "^0.1.8",
    "rxjs": "~5.1.0",
    "tns-core-modules": "^3.0.0"
  },
  "devDependencies": {
    "@angular/compiler-cli": "4.1.0",
    "@ngtools/webpack": "1.2.10",
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "codelyzer": "3.0.1",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~2.1.0",
    "filewalker": "0.1.3",
    "htmlparser2": "^3.9.2",
    "jasmine-core": "^2.5.2",
    "karma": "^1.6.0",
    "karma-jasmine": "^1.1.0",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.1",
    "nativescript-dev-android-snapshot": "0.0.8",
    "nativescript-dev-typescript": "^0.4.2",
    "nativescript-dev-webpack": "^0.4.0",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.0.2",
    "tslint": "^5.1.0",
    "typescript": "~2.3.2",
    "webpack": "2.4.1",
    "webpack-sources": "~0.2.3",
    "zone.js": "~0.8.4"
  }
```

_Copied from original issue: NativeScript/nativescript-cli#2762_

**Comment by sis0k0** [comment]
Hey there!

As the the error log states, there's a problem with a color you are using. Can you send your `app.css` and the other stylesheets you are using?

**Comment by naturalfreak** [comment]
Problem is solved.
After upgrate to tns version 3.0  empty color stops working
[style.color]="boolean ? 'red' : ''" 

> <Label text="Text
>            [style.color]="boolean ? 'red' : ''"
>             (tap)="onFollow(index)">
> </Label>
