### ISSUE TITLE
Setting invalid value for css properties causes app to crash

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#411]
The issue exists for the following properties:
- android: color, background-color, border-color, border-width, border-radius, font, font-style, font-weight, text-align, min-width, min-height, visibility and opacity.
- iOS: border-width, border-radius, font, font-style, font-weight, text-align, min-width, min-height, visibility and opacity.

**Comment by yyosifov** [comment]
:+1 just hit it with border-radius
