### ISSUE TITLE
After Upgrading Nativescript 3.0.0

### ISSUE THREAD

**Issue by gauravbabu74** [NativeScript/NativeScript#4112]
Found peer TypeScript 2.2.0
node_modules/nativescript-telerik-ui/listview/index.d.ts(302,56): error TS2339: Property 'Bindable' does not exist on type 'typeof "
C:/Users/gaurav.babu/Desktop/BizNative/May/4-5-17/BizCase/node_modules/tns-core-modules/u...'.

node_modules/tns-core-modules/tns-core-modules.d.ts(17,27): error TS2304: Cannot find name 'Headers'.

node_modules/tns-core-modules/tns-core-modules.d.ts(19,44): error TS2304: Cannot find name 'RequestInit'.

node_modules/tns-core-modules/tns-core-modules.d.ts(19,66): error TS2304: Cannot find name 'Response'.

**Comment by NickIliev** [comment]
@gauravbabu74 which version of nativescript-telerik-ui plugin is used in your project?
You will need to use the latest version  2.0.0 which is compatible with NativeScript 3.0.0.

**Comment by gauravbabu74** [comment]
After use nativescript-telerik-ui 2.0.0 :-----


Found peer TypeScript 2.2.0
node_modules/tns-core-modules/tns-core-modules.d.ts(17,27): error TS2304: Cannot find name 'Headers'.

node_modules/tns-core-modules/tns-core-modules.d.ts(19,44): error TS2304: Cannot find name 'RequestInit'.

node_modules/tns-core-modules/tns-core-modules.d.ts(19,66): error TS2304: Cannot find name 'Response'.

TypeScript compiler failed with exit code 1

**Comment by gauravbabu74** [comment]
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.Biz2Case",
    "tns-android": {
      "version": "3.0.0"
    }
  },
  "dependencies": {
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/platform-browser-dynamic": "~4.1.0",
    "@angular/router": "~4.1.0",
    "nativescript-angular": "internal-preview",
    "nativescript-background-http": "^2.4.2",
    "nativescript-bottombar": "^1.1.3",
    "nativescript-drop-down": "1.5.1",
    "nativescript-exit": "^1.0.0",
    "nativescript-imagepicker": "2.4.1",
    "nativescript-loading-indicator-new": "^2.1.0",
    "nativescript-telerik-ui": "2.0.0",
    "nativescript-textinputlayout": "^0.1.5",
    "nativescript-theme-core": "1.0.4",
    "nativescript-toast": "1.4.5",
    "nativescript-toolbox": "^1.47.0",
    "nativescript-vibrate": "^1.1.2",
    "nativescript-xmlobjects": "1.1.4",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.3.1",
    "tns-core-modules": "^3.0.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.4.2",
    "typescript": "2.2.0"
  }
}
##################################################################
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "lib": [
            "es2015.iterable",
            "es6",
            "dom"
        ],
        "baseUrl": ".",
        "paths": {
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms",
        "**/*.aot.ts"
    ]
}

**Comment by NickIliev** [comment]
At first glance, you will need to bump your typescript version to 2.3.x and nativescript-angular version to 3.0.0 (instead of "internal-preview"). You must do that also for all the plugins assuring that they have released a compatible 3.0.0 version. For example, as of today nativescript-imagepicker and nativescript-background-http plugins have released versions 3.0.0 which are the ones compatible with nativeScript 3.0.0.

Here is how I have modified your package.json so i can build a new project with its content

```
  "dependencies": {
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/platform-browser-dynamic": "~4.1.0",
    "@angular/router": "~4.1.0",
    "nativescript-angular": "3.0.0",
    "nativescript-background-http": "3.0.0",
    "nativescript-bottombar": "2.0.1",
    "nativescript-drop-down": "3.0.0",
    "nativescript-exit": "^1.0.0",
    "nativescript-imagepicker": "3.0.0",
    "nativescript-loading-indicator-new": "^2.1.0",
    "nativescript-telerik-ui": "2.0.1",
    "nativescript-textinputlayout": "^0.1.5",
    "nativescript-theme-core": "1.0.4",
    "nativescript-toast": "1.4.5",
    "nativescript-toolbox": "^1.49.2",
    "nativescript-vibrate": "^1.1.2",
    "nativescript-xmlobjects": "1.1.4",
    "reflect-metadata": "^0.1.10",
    "rxjs": "5.3.1",
    "tns-core-modules": "^3.0.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.4.2",
    "typescript": "2.3.2"
  }
```

The test app using this package.json can be found [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4112)

**Comment by gauravbabu74** [comment]
**Thanks for Quick Support.**

Finally I have done apk build successfully. But with "TextInputLayout" plugin It is showing errors.

Please check my two files.

Main.ts:----
########################

import * as application from "tns-core-modules/application";
import * as frame from 'ui/frame';

import { platformNativeScriptDynamic } from "nativescript-angular/platform";

import { AppModule } from "./modules/app.module";
import { registerElement } from "nativescript-angular/element-registry";
registerElement("DropDown", () => require("nativescript-drop-down/drop-down").DropDown);
registerElement("TextInputLayout", () => require("nativescript-textinputlayout").TextInputLayout);

platformNativeScriptDynamic().bootstrapModule(AppModule);


########################
Login.component.html:- 

#######################

<ActionBar title="">
    
</ActionBar>
<ScrollView class="loginstack" orientation="vertical" verticalAlignment="center" id="login">
    <StackLayout>
        <StackLayout style="padding-left:20;padding-right:20;">
            <Image src="res://black_logo" [stretch]="imageType" horizontalAlignment="center" style="margin-left:30;margin-right:30;margin-bottom:30;"></Image>
            <TextInputLayout hint="Email Address" hintAnimationEnabled="true" errorEnabled="false" ineHeight="0">
                <TextField #uname [(ngModel)]="username" keyboardType="email" autocorrect="false" autocapitalizationType="none"></TextField>
            </TextInputLayout>
            <TextInputLayout hint="Password" hintAnimationEnabled="true" errorEnabled="false">
                <TextField #password [(ngModel)]="pass" secure="true"></TextField>
            </TextInputLayout>
            <Button text="Login" (tap)="validateUser()" backgroundColor="#64980D" color="#ffffff" style="margin-top:10;margin-bottom:30;"></Button>
            <Label class="forgot-password-label" text="Forgot password?" (tap)="forgotPass()" horizontalAlignment="center"></Label>
        </StackLayout>
        <StackLayout orientation="vertical" horizontalAlignment="center" verticalAlignment="bottom" style="margin-top:20;">
            <GridLayout row="0" columns="*, auto" style="padding-left:15;padding-right:15;height:50;">
                <Label class="bold-font" text="Privacy Policy" col="0"></Label>
                <Label class="bold-font" text="Terms & Conditions" col="1"></Label> </GridLayout>
        </StackLayout>
    </StackLayout>
</ScrollView>

#######################
Errors:- 

 TypeError: Could not load view for: TextInputLayout.Error: com.tns.NativeScriptException: Failed to find module: "ui/core/proxy", rel
ative to: app/tns_modules/ 




And during build process command " tns debug android" I am getting following errors. but it is not interrupting  in building process.

##########################

05-05 11:33:08.910  7436  7436 W System.err: remove failed: EACCES (Permission denied) : /data/local/tmp/org.nativescript.Biz2Case/sync/t
ns_modules/rxjs/src/MiscJSDoc.ts
05-05 11:33:08.940  4420  4420 E audit   : type=1400 msg=audit(1493964188.910:84626): avc:  denied  { unlink } for  pid=7436 comm="script
.Biz2Case" name="MiscJSDoc.ts" dev="dm-0" ino=71503 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass
=file permissive=0
05-05 11:33:08.990  7436  7436 W System.err: remove failed: EACCES (Permission denied) : /data/local/tmp/org.nativescript.Biz2Case/sync/t
ns_modules/rxjs/src/observable/dom/MiscJSDoc.ts
05-05 11:33:09.020  4420  4420 E audit   : type=1400 msg=audit(1493964188.990:84819): avc:  denied  { unlink } for  pid=7436 comm="script
.Biz2Case" name="MiscJSDoc.ts" dev="dm-0" ino=133284 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:shell_data_file:s0 tclas
s=file permissive=0

**Comment by NickIliev** [comment]
Hey, @gauravbabu74  glad to hear that you were able to build your project! The exception you're receiving is indicating that the plugin **nativescript-textinputlayout** is not migrated for usage with NativeScript **3.x.x**. As of version 3.x.x NativeScript is introducing some [breaking changes](https://github.com/NativeScript/NativeScript/blob/master/Modules30Changes.md) all plugins that are relating on "ui/core/proxy" as in the case of **nativescript-textinputlayout** needs to be updated to be compatible with NativeScript 3.x.x. 
I have logged this as [an issue in the plugin's repository](https://github.com/bradleygore/nativescript-textinputlayout/issues/6) so please track the plugin for new version compatible with N 3.x.x.

**Comment by irums** [comment]
I installled nativescript 3.0, i create a sample project and tried to build. i got the following error.

![capture](https://cloud.githubusercontent.com/assets/15905631/25744043/07ff5406-3198-11e7-890f-201633c8463a.PNG)

**Comment by NickIliev** [comment]
Hey @irums can you please provide as much as possible details on the exact steps you have taken. 
e.g which command have you executed before receiving this errro?
