### ISSUE TITLE
Expected "// !$*UTF8*$!" but "<" found.

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/NativeScript#4115]
I'm still using N 2.5.4 as I don't have time to upgrade to version 3 yet.

After I removed the iOS platform and re-added I noticed that the platform had been upgraded to 3.0.0.  After removing the platform again and reinstalling the 2.5.0 version with `tns platform add ios@2.5.0` I can no longer run my project.

```
Project successfully prepared (ios)
Searching for devices...
Building project...
Expected "// !$*UTF8*$!" but "<" found.
# run ios
```

I've tried numerous things including removing iOS and installing the 3.0.0 version. Removing the hooks, node_modules and platforms folders all with the same result.

Any ideas?

```
┌──────────────────┬─────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 2.5.4           │ 3.0.0          │ Update available │
│ tns-core-modules │ 2.5.2           │ 3.0.0          │ Update available │
│ tns-android      │ 3.0.0           │ 3.0.0          │ Up to date       │
│ tns-ios          │ 2.5.0           │ 3.0.0          │ Update available │
└──────────────────┴─────────────────┴────────────────┴──────────────────┘
```

**Comment by tsonevn** [comment]
Hi @3rror404 ,
Thank you for reporting this issue.

I tested it on my side and I have to confirm that this is a real issue, while using an old CLI.
If we have an old project, using runtime 2.5.0 and build with `tns run <platform_name>` tns-ios` and `tns -android` will be automatically updated to version 3.0.

Workaround:
1. `tns platform remove <platform_name>`
2. `tns platform add <platform_name>`
3. `tns prepare <platform_name>`
4. `tns run <platform_name>`

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-cli#2782
