### ISSUE TITLE
Command xcodebuild failed with exit code 65

### ISSUE THREAD

**Issue by SandipFichadiya** [NativeScript/NativeScript#4122]
### Tell us about the problem
when I am trying to run the application on device I am getting following error in console.
```

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution NativeScript\ PostBuild /Users/myUser/Library/Developer/Xcode/DerivedData/MobileApp-afveghqmtvrxlqajajgokgnxuoke/Build/Intermediates/MobileApp.build/Debug-iphoneos/MobileApp.build/Script-CD3EAD351B05FF060042DBFC.sh
(1 failure)
Command xcodebuild failed with exit code 65
```

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI:2.5.0
- Cross-platform modules:2.5.2
- Runtime(s): "tns-ios": {  "version": "2.5.0"    }

**Comment by dtopuzov** [comment]
@SandipFichadiya Can you give us some more details:
- What app you build, is it hello-world template?
- What is the version of your Xcode?
- Are you able to run on iOS Simulator?
- Did you set correctly your iOS signing certificates?
- Please post package.json of your app

**Comment by SandipFichadiya** [comment]
- I had created an app using a simple TypeScript and Angular template.
- Xcode version 8.2.1
- App is neither running on device nor on simulator.
- Yes signing certificates had been set correctly.

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.demoProject",
    "tns-ios": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.0.0",
    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/router": "~4.0.0",
    "nativescript-angular": "~1.5.1",
    "nativescript-myplugindemo": "file:///Users/myUser/Desktop/DemoPlugin",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "2.5.2",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.3.5",
    "typescript": "~2.1.0"
  }
}
```

**Comment by dtopuzov** [comment]
@SandipFichadiya Can you please post or attach console logs from simulator/device.

**Comment by NickIliev** [comment]
Hey, @SandipFichadiya were you able to resolve this issue?

In your package.json you have referenced a plugin from a local directory - can yu verify that the plugin exists in that specific directory (`Users/myUser/Desktop/DemoPlugin`)

**Comment by jibon57** [comment]
@NickIliev, I am facing similar problem that I have described here: https://github.com/NativeScript/nativescript-cli/issues/2858 
Any suggestion please?

**Comment by 99hats** [comment]
`tns update`

Worked for me, YMMV.

**Comment by snq** [comment]
`tns build ios --clean` solved the issue for me
