### ISSUE TITLE
ATOB() and BTOA() methods not working

### ISSUE THREAD

**Issue by mast3rd3mon** [NativeScript/NativeScript#4126]
I'm running 2.5 nativescript with 2.4 angular. I'm building on android, i haven't tested ios.

In a pure js or angular2 app, `atob()` and `btoa()` work as expected. However, within an angular 2 nativescript app, those methods appear to somewhat pause the code but throw no errors at all.

Is this a known issue? Is there a fix?

**Comment by NickIliev** [comment]
NativeScript works with the native mobile APIs and not with the DOM and those methods require a Window object which is simply non-existent in both Android and iOS. You can use Angular in NativeScript but not the DOM related properties and methods.

**Comment by mast3rd3mon** [comment]
Then why do the methods get accepted and compiled if they cant be used? If they aren't available then they shouldn't appear

**Comment by mast3rd3mon** [comment]
How am i able to achieve what I'm after then?

**Comment by NickIliev** [comment]
@mast3rd3mon perhaps you can use custom implementation like [this one](http://www.webtoolkit.info/javascript-base64.html#.WQxrZNryj8s)

**Comment by mast3rd3mon** [comment]
that requires non npm plugins, ideally i want to do it in nativescript

**Comment by NickIliev** [comment]
@mast3rd3mon there are native methods that can handle taht for you in few lines of code.
Example  given by @triniwiz  [here](https://discourse.nativescript.org/t/how-to-base64-encode-a-string-in-nativescript/345)

```
Android
const text = new java.lang.String("Yolo 10000");
const data = text.getBytes("UTF-8");
const base64 = android.util.Base64.encodeToString(data, android.util.Base64);

IOS
const text = NSString.stringWithString("Yolo 10000");
const data = text.dataUsingEncoding(NSUTF8StringEncoding);
const base64 = data.base64EncodedStringWithOptions(0);
```

**Comment by mast3rd3mon** [comment]
i just tried the first way you recommended, the same thing happens as using the atob/btoa methods

**Comment by mast3rd3mon** [comment]
as for the native way, 1, thats encoding but im after decoding 2, `[ts] Cannot find name 'java'`

**Comment by triniwiz** [comment]
you can install the platform declarations then add the android typings to your ref or add the following `declare const java:any`

**Comment by mast3rd3mon** [comment]
forgot about that, ill give it a try

**Comment by mast3rd3mon** [comment]
nope, still freezes when decoding

**Comment by triniwiz** [comment]
Try decoding using a worker to take the load of the main thread

**Comment by mast3rd3mon** [comment]
i can leave it for 10+ minutes and still nothing

**Comment by NickIliev** [comment]
@mast3rd3mon [here](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/NativeScript/issue_4126_tsc/app/main-page.ts#L18-L33) you can find a basic example for encode and decode methods using the native Android API. Still, as @triniwiz mentioned if you want to operate with large files the best solution is to do that with workers in the background so that your UI thread won't freeze.

**Comment by mast3rd3mon** [comment]
the ui doesnt freeze, the code behind does, as for workers, im still yet to be told how

**Comment by NickIliev** [comment]
@mast3rd3mon [here](http://uatdocs.nativescript.org/core-concepts/multithreading-model#multithreading-model) you can find information on how to implement workers in NativeScript

**Comment by mast3rd3mon** [comment]
why is this closed? its not resolved

**Comment by NickIliev** [comment]
@mast3rd3mon I think we answered the main question (why ATOB and BTOA methods are not working). We have also provided suggestions on how to encode/decode a string using the Native APIs and in addition to work with rather large files, we suggested to use workers so that the heavy-duty operation won't be on your UI thread but in will be made in the background.

Even with [the example](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/NativeScript/issue_4126_tsc/app/main-page.ts#L18-L33) I have provided it would be expected your whole app to freeze if you are working with rather large files on the UI thread (this is why we suggested using workers) so I have closed this one as it is not a bug but more of a conceptual question.

If you think that this is related to a bug, please provide a sample project which can reproduce the issue.

**Comment by mast3rd3mon** [comment]
my UI doesn't freeze, its the code behind because those methods don't work

**Comment by mast3rd3mon** [comment]
I've just tried your way again and this is what happens
![image](https://cloud.githubusercontent.com/assets/24700106/25803382/7632443a-33ee-11e7-89b3-0aa1c839e64f.png)

**Comment by mast3rd3mon** [comment]
i would like to reopen this issue until a correct solution is presented as the one given doesnt work

**Comment by NickIliev** [comment]
Hey, @mast3rd3mon there is no issue that we can specify as a bug or non-expected NativeScript behavior based on our discussion. As discussed before both methods (**atob**() and **btoa**()) are using browser specifics which are not present in iOS or in Android. So what you need is to either [create a polyfill](https://github.com/hdeshev/nativescript-ntlm-demo/blob/master/app/base64.js) for these methods or [use the Native APIs.](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/NativeScript/issue_4126_tsc/app/main-page.ts#L18-L33). Both solutions are tested and are working as expected.

The last screenshot suggests that the error you are receiving is not in the example app (as there were no document paths used at all) but in your own application logic and is probably related to invalid document path which has nothing to do with this discussion so far.

**Comment by mast3rd3mon** [comment]
the native methods return horrible looking string type values, as for the screenshot, i tried to open the file by going in to file manager

**Comment by dlucidone** [comment]
@NickIliev the example doesnt have methods for ios ?

**Comment by mast3rd3mon** [comment]
@dlucidone theres a way to write it in native android and native ios, i never got round to adding the ios way but i couldnt find any other solution to this

**Comment by dlucidone** [comment]
@mast3rd3mon Android one works perfectly! but i need for iOS. So if there any one can help me in that.

**Comment by mast3rd3mon** [comment]
@dlucidone i ended up googling around until i found the native ios example, cant remember the links anymore, sorry

**Comment by dlucidone** [comment]
@NickIliev @triniwiz can you shed some light here?

**Comment by NickIliev** [comment]
@dlucidone in the very same thread there is an iOS example ([here](https://github.com/NativeScript/NativeScript/issues/4126#issuecomment-299455410)) - isn't this native solution working out for you?

**Comment by dlucidone** [comment]
@NickIliev Its working and its for encoding to base64. I need base64 to string decode function -  
Someone shared on slack channel but i dont know how to marshal this -

`NSData *decodedData = [[NSData alloc] initWithBase64EncodedString:base64String options:0];
NSString *decodedString = [[NSString alloc] initWithData:decodedData encoding:NSUTF8StringEncoding];
NSLog(@"Decode String Value: %@", decodedString); `

**Comment by triniwiz** [comment]
**Android**
```
const text = new java.lang.String(“Yolo 10000”);
const data = text.getBytes(“UTF-8”);
const base64 = android.util.Base64.encodeToString(data,android.util.Base64.DEFAULT);
android.util.Base64.decode(text, android.util.Base64.DEFAULT);
```
**IOS**
```
const decodedData = NSData.alloc().initWithBase64EncodedStringOptions(base64String,0);
const decodedString = NSString.alloc().initWithDataEncoding(decodedData,NSUTF8StringEncoding);
```


@dlucidone  ☝️

**Comment by dlucidone** [comment]
@triniwiz Thanks a lot

**Comment by dlucidone** [comment]
I created a Gist for this conversion methods  -https://gist.github.com/dlucidone/95264cf6cd216225224b2d72e7e27399

**Comment by kumaran-dena** [comment]
@NickIliev,
 As mentioned in this [comment](https://github.com/NativeScript/NativeScript/issues/4126#issuecomment-299804120) , the link you shared about on how to implement workers in NativeScript is broken.



Its showing site cannot be reached,
http://uatdocs.nativescript.org/core-concepts/multithreading-model#multithreading-model

Can you please share the latest link?

**Comment by jdnichollsc** [comment]
or using **base-64** and **utf8** npm packages:
```
import * as base64 from 'base-64';
import * as utf8 from 'utf8';

global['btoa'] = (str) => {
    var bytes = utf8.encode(str);
    return base64.encode(bytes);
};
global['atob'] = (encoded) => {
    return base64.decode(encoded);
};
```

**Comment by jdnichollsc** [comment]
Perfect, we can generate PDFs with {N}! 👍  https://play.nativescript.org/?template=play-ng&id=OGrw9s&v=13
