### ISSUE TITLE
Error with plugin

### ISSUE THREAD

**Issue by praven07** [NativeScript/NativeScript#4130]
Hi, I'm using nativescript angular. When ever I install a plugin from the nativescript plugins and I hit the 'tns run ios --watch' cmd. It gets stuck on this line.

<img width="646" alt="screen shot 2017-05-06 at 12 24 56 am" src="https://cloud.githubusercontent.com/assets/2223191/25770136/14752cc8-31f3-11e7-921d-9823e83eebe1.png">

**Comment by tsonevn** [comment]
Hi @praven07,
Thank you for contacting us.
Could you provide more info about your environment(CLI, tns-core-modules, node versions)? It would help if you could provide some more info about the problem. you could also send us sample project, which could be debugged locally.

Meanwhile, you could also verify, whether you will have the same problem with newly created project.
1. `tns create sample --ng`
2. `cd sample `
3. `tns run android`

**Comment by NickIliev** [comment]
@praven07 as you are stuck on the CocoaPods setup verify that you have installed CocoaPods on your Mac.
```
pod --version
```

you can install CocoaPods with
```
sudo gem install cocoapods
```

and then
```
pod setup
```

**Comment by praven07** [comment]
I updated to 3.0 and there was no issue. Thanks.
