### ISSUE TITLE
Unable to start service com.apple.mobile.installation_proxy. Result code is: 3892314239

### ISSUE THREAD

**Issue by SandipFichadiya** [NativeScript/NativeScript#4131]
### Tell us about the problem
I am running my nativescript application on iPhone6SPlus device. App is not running and shows following error.

```
** ARCHIVE SUCCEEDED **

2017-05-06 15:10:29.786 xcodebuild[14520:96785] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/_s/6l5z2bd97lv0wl9ztv1dmfph0000gn/T/demoProject_2017-05-06_15-10-29.784.xcdistributionlogs'.
1.2.840.113635.100.1.61
Exported demoProject.xcarchive to: /Users/myUser/Desktop/demoProject/platforms/ios/build/device
** EXPORT SUCCEEDED **

Project successfully built.
Installing...
Unable to start service com.apple.mobile.installation_proxy. Result code is: 3892314239
```

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.0
- Cross-platform modules: 2.5.2
- Runtime(s): 2.5.2

**Comment by elvismercado** [comment]
I'm having this trouble too. Have you found out why this happened?

**Comment by NickIliev** [comment]
@SandipFichadiya , @elvismercado try to reset your platforms folder and rebuild your application. The cause of this error code is discussed [here](https://github.com/NativeScript/NativeScript/issues/152) and this is one of the possible solutions. If you are still running into this error please provide a sample app that can reproduce it so we can investigate further or use the instructions in thenlink3ed issue to get additional error logs..

**Comment by elvismercado** [comment]
@NickIliev thnx. Most of the time `tns run <platform> --clean` will help

**Comment by JijeshP** [comment]
@NickIliev this issue is still there.. the problem is WiFi debugging is not working. if you disable WIFI it works.. how to make Wifi work  ? 

`Could not start service com.apple.mobile.installation_proxy.`

**Comment by dtopuzov** [comment]
Hi @JijeshP 

Debug and livesync via wifi are not supported at the moment. 
If you need it you can log issue in nativescript-cli repo.
