### ISSUE TITLE
ng-template ngFor not repeating within layouts

### ISSUE THREAD

**Issue by x00** [NativeScript/NativeScript#4133]
Android / Nativescript 3.0

            <StackLayout>
                <ng-template ngFor let-index [ngForOf]="[1,2,3,4]">
                <Label [text]="'This is Label' + index"></Label>
                </ng-template>
            </StackLayout>

yield only `This is Label 1`, where as 

            <StackLayout>
                <Label text="This is Label 1"></Label>
                <Label text="This is Label 2"></Label>
                <Label text="This is Label 3"></Label>
                <Label text="This is Label 4"></Label>
            </StackLayout>

should have the same result. 

this is true is grid wrap and other layouts. 

It is also true if you use the depreciated template. It was working prior to update.

**Comment by x00** [comment]
<StackLayout>
                <Label [text]="'This is Label' + index" *ngFor="let index of [1,2,3,4]"></Label>
            </StackLayout>

works correctly but does help if you need a template.

**Comment by x00** [comment]
I can confirm thsi with  fresh app

**Comment by tsonevn** [comment]
Hi @x00,
Thank you for reporting this issue.
I tested the above-mentioned scenario and unfortunately have to confirm that this is a real issue for both iOS and Android while using `ng-template` in NativeScript Angular 2 project.
I am attaching sample project, where this could be reproduced. 

[Archive.zip](https://github.com/NativeScript/NativeScript/files/986668/Archive.zip)

In the meantime, you could use `StackLayout` as a template and attach to it `ngFor` directive. For example:
```
 <StackLayout>
        <StackLayout height="50" *ngFor="let index of [1,2,3,4]">
            <Label [text]="'This is Label' + index" ></Label>
        </StackLayout>
</StackLayout>
```

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#789
