### ISSUE TITLE
Invalid Revision:26.0.0

### ISSUE THREAD

**Issue by jeneiro** [NativeScript/NativeScript#4140]
please can anyone help with this issue. i am using a 32 bit windows system with 4gig ram and i am new to natives
![error](https://cloud.githubusercontent.com/assets/28535480/25807201/e73cf4f4-33fd-11e7-860b-38251e29e7a4.jpg)
cript

**Comment by dtopuzov** [comment]
Hi @jeneiro,

It looks the problem is caused by having android build-tools 26.0.0-preview installed on your system.
Can you uninstall them, add latest official version (25.*) and try again?

**Comment by NickIliev** [comment]
@jeneiro we haven't heard from your for a while - have you managed to resolve your issue with the solution suggested by @dtopuzov?

**Comment by jeneiro** [comment]
@dtopuzov thank you. your suggestion actually worked, you're a life saver. @NickIliev Sorry about that, my issue has been taken care of.
