### ISSUE TITLE
consider updating the "NativeScript Advanced Setup: macOS" section of the official document

### ISSUE THREAD

**Issue by c1ngular** [NativeScript/NativeScript#4145]
since there have been major changes of Android SDK Tools , the current steps/tutorials may not set Android SDK environments properly ! 

e.g.  "brew cask install android-sdk" , now installs Android SDK Tools 25.2.3 by default , and sdk installation location is different , and "android update sdk --filter tools,platform-tools,android-25,build-tools-25.0.2,extra-android-m2repository,extra-google-m2repository,extra-android-support --all --no-ui " is no longer working !

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/docs#768
