### ISSUE TITLE
ERROR SyntaxError: JSON Parse error: Unexpected EOF

### ISSUE THREAD

**Issue by pap5508** [NativeScript/NativeScript#4148]
I am getting Unexpected EOF file after Successfully launching on Emulator.

Due to this Error I am not able to translate Home screen but Expect that Each screen translate works.

Problem: First time logged in app Translation works but If I force close application and re-run it translation not working..

```
CONSOLE LOG file:///app/tns_modules/@angular/core/./bundles/core.umd.js:3032:20: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
CONSOLE LOG file:///app/app.component.ts:null:null: firebase.init done
CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1091:24: ERROR SyntaxError: JSON Parse error: Unexpected EOF
```

Running on Xcode getting following Error
```
CONSOLE LOG file:///app/app.component.js:59:24: firebase.init done
2017-05-09 10:21:12.263593+0200 Hieber[508:84865] CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1091:24: ERROR Error: Failed to create file at path '/var/containers/Bundle/Application/6E5AC3EB-13A5-42C1-B479-EE3E2C7F0758/Hieber.app/app/i18n/de-DE.json'

CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1091:24: ERROR Error: Failed to create file at path '/var/containers/Bundle/Application/6E5AC3EB-13A5-42C1-B479-EE3E2C7F0758/Hieber.app/app/i18n/de-DE.json'
```

**Comment by NickIliev** [comment]
Hey @pap5508 I suspect that your issue is closely related to[ this one](https://github.com/NativeScript/nativescript-dev-webpack/issues/42#issuecomment-269297910)
If you are using `ng2-translate`, can you please try the solution provided in the linked issue?

**Comment by pap5508** [comment]
@NickIliev : Already tried that but nothing works.. Preparing demo for you so that you can test it..

**Comment by pap5508** [comment]
@NickIliev : tried that too but nothing works. Preparing demo for you so that you can test it.
I'm using @ngx-translate/core

**Comment by NickIliev** [comment]
Hey @pap5508 yes sending demo project would be great - remove node_modules and platforms and you should be able to attach it here as an archive.

**Comment by NickIliev** [comment]
@pap5508 you can also try [this](https://www.thepolyglotdeveloper.com/2017/01/internationalization-nativescript-mobile-app-angular/) for translation in your app.
