### ISSUE TITLE
Console.dump is not a function!

### ISSUE THREAD

**Issue by ryanzaatari** [NativeScript/NativeScript#4153]
I created a new project that crashes upon a console.dump statement, console.log and console.dir both work just fine, here's the log:

> 1   0x1022f071b NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*,
> void**, void*)
> 2   0x1029c515e ffi_closure_unix64_inner
> 3   0x1029c5a92 ffi_closure_unix64
> 4   0x1036fc07f -[UIViewController __viewWillAppear:]
> 5   0x103736fb8 -[UINavigationController _startTransition:fromViewController:toViewController:]
> 6   0x103737ef9 -[UINavigationController _startDeferredTransitionIfNeeded:]
> 7   0x103738fdb -[UINavigationController __viewWillLayoutSubviews]
> 8   0x10392fdd7 -[UILayoutContainerView layoutSubviews]
> 9   0x103618ab8 -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
> 10  0x108333bf8 -[CALayer layoutSublayers]
> 11  0x108327440 CA::Layer::layout_if_needed(CA::Transaction*)
> 12  0x1083272be CA::Layer::layout_and_display_if_needed(CA::Transaction*)
> 13  0x1082b5318 CA::Context::commit_transaction(CA::Transaction*)
> 14  0x1082e23ff CA::Transaction::commit()
> 15  0x1082e2d6f CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
> 16  0x106766267 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
> 17  0x1067661d7 __CFRunLoopDoObservers
> 18  0x10674a8a6 CFRunLoopRunSpecific
> 19  0x10354daea -[UIApplication _run]
> 20  0x103553c68 UIApplicationMain
> 21  0x1029c58ed ffi_call_unix64
> 22  0x11edaef70
> file:///app/pages/home/home.js:13:15: JS ERROR TypeError: console.dump is not a function. (In 'console.dump(repItems)',
> 'console.dump' is undefined)
> 

Package.json:

> {

> 
>   "description": "NativeScript Application",
>   "license": "SEE LICENSE IN <your-license-filename>",
>   "readme": "NativeScript Application",
>   "repository": "<fill-your-repository-here>",
>   "nativescript": {
>     "id": "org.nativescript.MakhzoumiFoundation",
>     "tns-ios": {
>       "version": "3.0.0"
>     },
>     "tns-android": {
>       "version": "3.0.0"
>     }
>   },
>   "dependencies": {
>     "nativescript-intl": "^3.0.0",
>     "nativescript-statusbar": "^1.0.0",
>     "nativescript-telerik-ui":"^2.0.0",
>     "nativescript-telerik-ui-pro": "file:///Users/ryanzaatari/Documents/Development/NativeScript/nativescript-ui-pro.tgz",
>     "nativescript-theme-core": "^1.0.4",
>     "tns-core-modules": "^3.0.0"
>   },
>   "devDependencies": {
>     "babel-traverse": "6.24.1",
>     "babel-types": "6.24.1",
>     "babylon": "6.17.0",
>     "lazy": "1.0.11"
>   }
> }

Note: I have another project with tns version 2.5.0 having console.dump running with no issues.
Appreciate any help!

**Comment by tsonevn** [comment]
Hi @ryanzaatari,
`console.dump`  has been deprecated from NativeScript 3.0 in favor of  `console.dir`.
In your case, you could replace `console.dump` with `console.dir`.

**Comment by NickIliev** [comment]
@ryanzaatari  for list of the breaking changes in NativeScript 3.0.0 look [here](https://github.com/NativeScript/NativeScript/blob/master/Modules30Changes.md)

**Comment by ryanzaatari** [comment]
@tsonevn, @NickIliev I see, thanks for the info, however console.dir shows [object Object] for a Json object, how to check the object tree just like console.dump used to ?

**Comment by tsonevn** [comment]
Hi @ryanzaatari,
We have already logged the issue `[object Object]`, while using `console.dir`. You could keep track on this issue [here](https://github.com/NativeScript/NativeScript/issues/3973).
Meanwhile, you could use `console.log(JSON.stringify(<parametar_name>))`, which should help you for this case.

**Comment by ryanzaatari** [comment]
Thanks @tsonevn, that was really helpful.
I think I'll downgrade to 2.5.0 `tns update 2.5.0` as I had other issues when passing an object as a parameter in observable constructor, it's just not worth it moving to 3.0 yet
Hopefully downgrading won't turn out to be a nightmare.

**Comment by tsonevn** [comment]
Hi @ryanzaatari,
From NativeScript 3.0 passing an object as a parameter in observable constructor has been deprecated.
You should use `fromObject` method, which will create an Observable object. For Example:

```
import { EventData, Observable, fromObject } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';


export function navigatingTo(args: EventData) {

    let page = <Page>args.object;

    var tmpObservable= fromObject({"test":"test", "test1":"test1"});
 
    page.bindingContext = tmpObservable;
}
```
