### ISSUE TITLE
RSA Encryption Module for NativeScript.

### ISSUE THREAD

**Issue by deepak4u2006** [NativeScript/NativeScript#4156]
As per the discussion on the StackOverflow and with @NickIliev, I propose for a dedicated module for Encryption in NativeScript. 
As mostly all modern apps use encryption in their apps, so this is really a great and important feature to have.

**Comment by vbresults** [comment]
jsrsassign works great for me.

**Comment by PeterStaev** [comment]
What would be the benefit/difference between this plugin and using the crypto-js module from NPM. Last time I checked crypto-js has been working just fine in NativeScript.

**Comment by deepak4u2006** [comment]
Hi @PeterStaev, Sorry I didn't fully understood your point. 
I am very new to this community so pls Correct me If I am wrong, I think Crypto-JS don't have RSA Module.
Also having a own module Security would add some more Stars to it.

**Comment by NickIliev** [comment]
As the solution provided by @vbresults appears to be applicable I think we can close this feature request and use [jsrsassign](https://www.npmjs.com/package/jsrsasign) cryptographic library as @deepak4u2006 has done in the comment above.
