### ISSUE TITLE
GestureTypes error

### ISSUE THREAD

**Issue by ownleviathan** [NativeScript/NativeScript#4165]
Hello

After update to version 3.0.0, appears this error to me:

app/pages/home/home.ts(78,19): error TS2345: Argument of type 'GestureTypes' is not assignable to parameter of type 'string'.

And this is the code for that error:
```
import { GestureTypes, SwipeGestureEventData } from "ui/gestures";

let tl = page.getViewById("_top_layer");
        if (tl)
            tl.on(**GestureTypes.swipe**, this.onSwipe);

        if (page.android) {
           let gridViewkpiCards = page.getViewById("_gridViewkpiCards");
             if (gridViewkpiCards)
                 gridViewkpiCards.on(**GestureTypes.swipe**, this.onSwipe);
        }
```

I read the NativeScript v3.0 Breaking Changes but is not mentioning anything about this.
What have I to do? 

Thanks

**Comment by tsonevn** [comment]
Hi @ownleviathan,
I tested the above-described scenario on my side, however, everything seems to work as expected and the project is built, without the TypeScript errors.
Regarding that, could you give us some more info about your project and to send us the project `package.json` file.
You could also review the attached sample app and to verify if I am missing something, which is needed for reproducing the problem.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/995134/Archive.zip)

**Comment by ownleviathan** [comment]
Hi.
this is my package.json

{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.cisco.mbr",
    "tns-ios": {
      "version": "2.5.0"
    },
    "tns-android": {
      "version": "3.0.0"
    }
  },
  "dependencies": {
    "@angular/common": "^4.1.1",
    "@angular/compiler": "^4.1.1",
    "@angular/core": "^4.1.1",
    "@angular/forms": "^4.1.1",
    "@angular/http": "^4.1.1",
    "@angular/platform-browser": "^4.1.1",
    "@angular/router": "^4.1.1",
    "base-64": "^0.1.0",
    "nativescript-angular": "^3.0.0",
    "nativescript-cardview": "^2.0.0-rc.0",
    "nativescript-collapsing-header": "2.0.0",
    "nativescript-exit": "^1.0.0",
    "nativescript-fingerprint-auth": "4.0.0",
    "nativescript-floatingactionbutton": "3.0.0",
    "nativescript-grid-view": "3.0.0",
    "nativescript-intl": "3.0.0",
    "nativescript-loading-indicator": "2.3.2",
    "nativescript-master-technology": "^1.1.0",
    "nativescript-oauth": "file:../nativescript-oauth",
    "nativescript-statusbar": "1.0.0",
    "nativescript-telerik-ui": "2.0.1",
    "rxjs": "^5.4.0",
    "tns-core-modules": "^3.0.0",
    "utf8": "^2.1.2",
    "zone.js": "^0.8.10"
  },
  "devDependencies": {
    "babel-traverse": "^6.22.1",
    "babel-types": "^6.22.0",
    "babylon": "^6.15.0",
    "filewalker": "^0.1.3",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.4.4",
    "tns-platform-declarations": "^3.0.0",
    "typescript": "^2.3.2"
  }
}


I still have the same problem!!

Thanks

**Comment by NickIliev** [comment]
@ownleviathan we were not able to reproduce your issue even with the exact same dependency versions as in your package.json file. However as a workaround, provide directly the string for your event listener.
e.g.
```
tl.on("swipe", this.onSwipe)
```
