### ISSUE TITLE
Got issue with Nativescript-Couchbase while upgrade to Nativescript 3.0

### ISSUE THREAD

**Issue by phattranky** [NativeScript/NativeScript#4169]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Did you verify this is a real problem by searching [StackOverflow]
Almost same issue here
https://github.com/couchbaselabs/nativescript-couchbase/issues/27

### Tell us about the problem
Got the error message on iOS: Metdata for "CouchbaseLite.CBLManager" found but symbol not available at runtime

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI:  3.0.0
- Cross-platform modules: 3.0.0
- Runtime(s): 3.0.0
- Plugin(s):
```
    "@angular/common": "^4.1.2",
    "@angular/compiler": "^4.1.2",
    "@angular/core": "^4.1.2",
    "@angular/forms": "^4.1.2",
    "@angular/http": "^4.1.2",
    "@angular/platform-browser": "^4.1.2",
    "@angular/platform-browser-dynamic": "^4.1.2",
    "@angular/router": "^4.1.2",
    "@ngrx/core": "^1.2.0",
    "@ngrx/store": "^2.2.1",
    "base-64": "^0.1.0",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "nativescript-angular": "^3.0.0",
    "nativescript-camera": "^3.0.0",
    "nativescript-cardview": "^2.0.0-rc.0",
    "nativescript-carousel": "^2.4.2",
    "nativescript-couchbase": "^1.0.18",
    "nativescript-dev-sass": "^1.1.1",
    "nativescript-drop-down": "^3.0.0",
    "nativescript-iqkeyboardmanager": "^1.0.1",
    "nativescript-loading-indicator": "^2.3.2",
    "nativescript-mapbox": "^3.0.0",
    "nativescript-ripple": "^1.1.0",
    "nativescript-slides": "^2.2.8",
    "nativescript-status-bar": "^1.1.1",
    "nativescript-stringformat": "^2.3.4",
    "nativescript-telerik-ui-pro": "^2.0.1",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-timedatepicker": "^1.2.0",
    "nativescript-unit-test-runner": "^0.3.4",
    "nativescript-zendesk-with-chat": "0.0.2",
    "ng2-translate": "^5.0.0",
    "reflect-metadata": "~0.1.10",
    "rxjs": "^5.4.0",
    "tns-core-modules": "^3.0.0",
    "utf8": "^2.1.2",
    "zone.js": "^0.8.10"
    "@types/jasmine": "^2.5.47",
    "babel-traverse": "6.23.1",
    "babel-types": "6.23.0",
    "babylon": "6.15.0",
    "codelyzer": "^2.0.0-beta.4",
    "filewalker": "0.1.3",
    "jasmine-core": "^2.5.2",
    "karma": "^1.6.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.1.0",
    "karma-nativescript-launcher": "^0.4.0",
    "karma-typescript": "^3.0.1",
    "karma-typescript-preprocessor": "^0.3.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.4.4",
    "tslint": "^4.0.0",
    "typescript": "2.2.1",
    "zone.js": "~0.8.2"
```

### Please tell us how to recreate the issue in as much detail as possible.
after create new couchbase database and create view on constructor

```
     this.database = new Couchbase("database_name");
      this.database.createView("database_view_name", "1", function(document, emitter) {
          emitter.emit(document._id, document);
      });
```

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```
import { Injectable } from "@angular/core";
import { Couchbase } from "nativescript-couchbase";


@Injectable()
export class ABCService {

  public database: Couchbase;

  constructor(private http: Http, private dataProvider:Data) {
      this.database = new Couchbase("database_name");
      this.database.createView("database_view", "1", function(document, emitter) {
          emitter.emit(document._id, document);
      });
  }
}

```

### Screenshots:

![screen shot 2017-05-12 at 3 18 25 pm](https://cloud.githubusercontent.com/assets/6443154/25989665/3bc8fa5a-3727-11e7-91b9-3e0cc76d32bd.png)
![screen shot 2017-05-12 at 3 25 05 pm](https://cloud.githubusercontent.com/assets/6443154/25989666/3bdec6fa-3727-11e7-8a2b-7340b17ba639.png)

### Notes:

It's working well on NativeScript 2.5.4. I have called *tns plugin update* to make sure all of my plugin version is lasted.

**Comment by NickIliev** [comment]
Hey @phattranky the nativescript-couchbase is migrated to 3.0.0 and tested so I guess your problem is related of version mismtaching in your package.json.

I have tested the described scenario in [this test application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4169) and on my side, everything works as expected. The difference is that NativeScript 3.0.0 works with @angular 4.1.x and nativescript-angular 3.0.0 which are not updated with tns update. See [this](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/NativeScript/issue_4169/package.json) as a reference

**Comment by NickIliev** [comment]
This issue was moved to couchbaselabs/nativescript-couchbase#59

**Comment by phattranky** [comment]
@NickIliev Thanks for quick response, i will recheck later
