### ISSUE TITLE
RadioGroup Error after upgrading to NS-3

### ISSUE THREAD

**Issue by shaikhspear16** [NativeScript/NativeScript#4179]
> Could not load view for: RadioGroup.Error: com.tns.NativeScriptException: Failed to find module: "ui/core/proxy", relative to: app/tns_modues/

After upgrading to NS 3, I get the error above using RadioGroup
https://www.npmjs.com/package/nativescript-radiobutton

I also tries utilizing the native control 
https://developer.android.com/guide/topics/ui/controls/radiobutton.html

Gives me the exact same error.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.0
- Cross-platform modules: 3.0.0
- Runtime(s): "tns-android": { "version": "3.0.0" }
- Plugin(s):  "nativescript-radiobutton": "^0.1.0",

### Please tell us how to recreate the issue in as much detail as possible.
Create new Nativescript project. Add the radiobutton plugin.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```

 <RadioGroup [(value)]="dataBoundVariable">
        <RadioButton text="Selection 1"></RadioButton>
        <RadioButton text="Selection 2"></RadioButton>
        <RadioButton text="Selection 3"></RadioButton>
    </RadioGroup>
```

**Comment by NickIliev** [comment]
Hey, @shaikhspear16 as there was a number of [breaking changes in NativeScript 3.0.0](https://github.com/NativeScript/NativeScript/blob/master/Modules30Changes.md) all of the plugins that are using changed modules like "ui/core/proxy" should be migrated for compatibility with NativeScript 3.0.0. As of this moment, the plugin nativescript-radiobutton is compatible with NativeScript 2.5.x and below.

**Comment by NickIliev** [comment]
This issue was moved to Tunaweza/nativescript-radiobutton#4
