### ISSUE TITLE
Application resume event

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/NativeScript#4181]
_From @pitAlex on May 12, 2017 13:38_

Hello,

I've been experimenting with the ios plaform in nativescript and I noticed that the application.resumeEvent is fired whenever application gains focus, not when it came in foreground.
This is how I noticed the behavior:
Add the following code in your app startup script (main.js) :
```
import * as application from "application";
....
class MyDelegate extends UIResponder implements UIApplicationDelegate {
    public static ObjCProtocols = [UIApplicationDelegate];


    applicationWillEnterForeground(application: UIApplication): void {
        console.log("resumed");
    }
}
application.ios.delegate = MyDelegate;

application.on(application.suspendEvent, (args) => {
        console.log("suspended");
});
application.on(application.resumeEvent, (args) => {
        console.log("focused");
});
...
```
After app start simply open the notification bar from the top and then close it. The app will fire "focused" event. However put the app in background then bring it back again and you will see "resumed" + "focused" fired.

Is this behavior intentional? If so then what is the event that is hooked to the "applicationWillEnterForeground" method?

_Copied from original issue: NativeScript/ios-runtime#763_

**Comment by ivanbuhov** [comment]
Hi @pitAlex 
`application.resume` [is triggered](https://github.com/NativeScript/NativeScript/blob/86b9be340a6bd06f4c145e0a99b73d1d205f0ac6/tns-core-modules/application/application.ios.ts#L141) on `didBecomeActive` iOS event and this behavior is intentional.

If you want to subscribe to iOS event which is not exposed by the `application` module you can still get the application delegate and inject your own event handler:

```
var appDelegateProto = Object.getPrototypeOf(application.ios.delegate);
appDelegateProto.applicationWillEnterForeground = function(application) {
    console.log("applicationWillEnterForeground");
}
```

**Comment by ivanbuhov** [comment]
_From @pitAlex on May 12, 2017 16:30_

Hmm, if its intentional and application.resumeEvent should be a cross platform event, then the ios behavior is inconsistent with the android behavior. On android application.resumeEvent is fired when application is brought in foreground, not when becoming focused.

**Comment by NickIliev** [comment]
Hey @pitAlex thanks for your considerations

> **_applicationWillEnterForeground_**: is called:
> 
> - before **_applicationDidBecomeActive_**:
> - when the application is re-launched
> 
> **_applicationDidBecomeActive_**: is called:
> 
> - on first launch after **_application:didFinishLaunchingWithOptions_**:
> - after **_applicationWillEnterForeground_**
> - after **_application:handleOpenURL_**
> - after **_applicationWillResignActive_**

That said, we can see that **_applicationDidBecomeActive_** is called every time after **_applicationWillEnterForeground_** but also covers some case which can also be considered app resuming (e.g. when the user ignores a phone call and goes back to the app) so in my opinion the current implementation is covering all the common cases plus some additional ones. Of course, as @ivanbuhov  pointed out you can implement your own application delegate to use **_applicationWillEnterForeground_**
