### ISSUE TITLE
Toast module

### ISSUE THREAD

**Issue by cime** [NativeScript/NativeScript#419]
It would be nice to have a cross-platform module for [toast messages](http://developer.android.com/guide/topics/ui/notifiers/toasts.html). 

Here is my implementation - [toast.ts](https://gist.github.com/cime/7ed0596e5fe6eb764fb7)

The problem with my implementation is that on iOS the "toast" is a blocking modal dialog, which blocks user interaction for the time it's shown.

**Comment by valentinstoychev** [comment]
Thanks @cime! We are planning toasts with this issue #401 . Lets move the conversation there.
