### ISSUE TITLE
Webview, Adding Navigation "bar"

### ISSUE THREAD

**Issue by ryanzaatari** [NativeScript/NativeScript#4193]
I couldn't find webview's api list, I need to have the "back", "Refresh", and "forward" functionality.
it would be great if you redirect me to an example or just a link to the API list.

**Comment by tsonevn** [comment]
Hi @ryanzaatari,
For your case, you could create custom navigation bar by using `GridLayout`. For example:
```
    <GridLayout rows="auto *" columns="* * *">
        <Button col="0" text="Back" tap="gobackbuton" />
        <Button col="1" text="Refresh" tap="gorefreshbuton" />
        <Button col="2" text="Forward" tap="goforwardbuton" />
        <WebView col="0" colSpan="3" row="1" src="someUrl | pathToLocalFile | htmlString" />
    </GridLayout>
```
When some of the buttons are tapped, you could call the appropriate WebView method:
* [goback](http://docs.nativescript.org/api-reference/classes/_ui_transition_.webview.html#goback)
* [goforward](http://docs.nativescript.org/api-reference/classes/_ui_transition_.webview.html#goforward)
* [reload](http://docs.nativescript.org/api-reference/classes/_ui_transition_.webview.html#reload)

For further `How to` questions, you could use NativeScript Forum [here](https://discourse.nativescript.org/)

**Comment by ryanzaatari** [comment]
Thank you @tsonevn, I'v adopted what you suggested.

**Comment by Xsmael** [comment]
goback
goforward
reload

links are broken :/
