### ISSUE TITLE
Tutorial: data binding not working properly

### ISSUE THREAD

**Issue by peresbruno** [NativeScript/NativeScript#4199]
Hello.

I'm start learning NativeScript. Currently I'm following the Tutorial from the Getting Started Guide. Everything was going well but in [Chapter 3: Adding a View Model][2] the data binding don't works as expected. In this section the chapter 3 says:

> Because JavaScript sets the view model's `email` to "user@domain.com",
> and because you bound the email address text field to that property
> using `<TextField text="{{ email }}">`, **when you run this app you'll see
> "user@domain.com" appear on the front end.**

But this don't occurs... When I ran the app the Email Address and Password fields remain with placeholder (see image below). After I start typing the data binding works fine.

![screenshot_20170515-235114](https://cloud.githubusercontent.com/assets/1018182/26087918/3d5433b2-39ca-11e7-9e0c-a11013b5390b.png)

My login.xml:

    <Page loaded="loaded">
        <StackLayout orientation="vertical">
    		<Image src="res://logo" stretch="none" horizontalAlignment="center" />
    		<TextField id="email" text="{{ email }}" hint="Email Address" keyboardType="email" autocorrect="false" autocapitalizationType="none" />
    		<TextField secure="true" text="{{ password }}" hint="Password" />
    		<Button text="Sign in" tap="signIn" />
    		<Button text="Sign up for Groceries" class="link" tap="register" />
    </StackLayout>
</Page>

My login.js:

    var frameModule = require("ui/frame");
    var Observable = require("data/observable").Observable;
    
    var user = new Observable({
        email: "user@domain.com",
        password: "password"
    });
    
    exports.loaded = function(args) {
        page = args.object;
        page.bindingContext = user;
    };
    
    exports.signIn = function() {
    	console.log(user.email);
    };
    
    exports.register = function() {
        var topmost = frameModule.topmost();
        topmost.navigate("views/register/register");
    };

This is a problem with the tutorial or I'm making a mess?

Thanks!

  [2]: http://docs.nativescript.org/tutorial/chapter-3#34-adding-a-view-model

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/sample-Groceries#250
