### ISSUE TITLE
Create Documentation Docset compatible w/ Dash for offline access

### ISSUE THREAD

**Issue by sfeather** [NativeScript/NativeScript#420]
See https://kapeli.com/docsets for reference

**Comment by moll** [comment]
:+1:

**Comment by sfeather** [comment]
@valentinstoychev are ya'll using anything to auto-generate the current docs from source/etc at the moment? Thinking this would be best if automated, and easier to implement that automation before the framework grows too large.

**Comment by valentinstoychev** [comment]
@sfeather Yes, we have the documentation in markdown format here - https://github.com/NativeScript/docs. The we have a build system that is using jekyll to generate the HTML pages. @ErjanGavalji can tell you more details if needed.

**Comment by sfeather** [comment]
doh! Thanks @valentinstoychev, how I walked right past that and missed the md files I have no idea.

**Comment by enchev** [comment]
This issue was moved to NativeScript/docs#120
