### ISSUE TITLE
ObservableModule fromObject and getter not working as expected

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#4203]
When using the **[fromObject](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/data/observable/observable.ts#L183-L196)** method the observable values are mapped. however, the [getter](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/data/observable/observable.ts#L183-L196) accesses the value directly (no mapping) which leads to unexpected behavior.

cc @hshristov 

Example application [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/test/dynTab) and more specifically [this line of code](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/test/dynTab/app/categories-root/categories-root.js#L66). (setting goes well then the app uses the getter and fails with **undefined**)

Temporary solution: Changing [this line ](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/data/observable/observable.ts#L40) to:
```
return this._map[name];
```

reported via t.1109124

**Comment by torvicv** [comment]
How can I adding that line commented above in observable.d.ts?

**Comment by torvicv** [comment]
I have this problem in my app.
