### ISSUE TITLE
Page.showModal seems completely broken in IOS

### ISSUE THREAD

**Issue by stonecourier** [NativeScript/NativeScript#421]
I have been using showModal pages extensively to enable simple choice screens.

Unfortunately, they do not seem to work at all on IOS. Debugging using CLI returns no errors or exceptions on IOS, but the pages do not seem to initialize correctly (ie elements not bound, styles not set).

Tested on IOS emulator, various screen resolutions and actual device.

Raised trouble ticket 952281 with telerik and included a link to my project there (didn't want this publicly available).

This is how they look on android.

![popup1](https://cloud.githubusercontent.com/assets/2016796/8636645/adcb5652-28b0-11e5-9be5-b3c7903b8da2.png)
![popup2](https://cloud.githubusercontent.com/assets/2016796/8636647/af756ba0-28b0-11e5-801b-23902d815e8f.png)
![popup3](https://cloud.githubusercontent.com/assets/2016796/8636646/ae183c56-28b0-11e5-8180-9bc2a83482b7.png)
![popup4](https://cloud.githubusercontent.com/assets/2016796/8636648/b4ea907e-28b0-11e5-8866-3d6cdae64d76.png)

**Comment by hamorphis** [comment]
I will investigate this.

**Comment by hamorphis** [comment]
I managed to reproduce it. I am now debugging it to find out why the layout and css do not work as expected. Stay tuned...

**Comment by hamorphis** [comment]
I am currently working on a fix for this issue. If all goes well, it should be working for our 1.2.0 release later this month.

**Comment by stonecourier** [comment]
Thanks
