### ISSUE TITLE
How to use two searchbar not working

### ISSUE THREAD

**Issue by harriscreativity** [NativeScript/NativeScript#4217]
i am trying to use two searchbar one is working and the other isnt but when i use input field it is working 
```
<SearchBar borderColor="#009366" backgroundColor="#e12b28" textFieldBackgroundColor="white" row="0" #whatitem hint="Search for Video via Company name"
                (clear)="onClear()" [text]="searchPhrase" (textChange)="searchWhat(whatitem.text)"></SearchBar>
<SearchBar borderColor="#009366" backgroundColor="#e12b28" textFieldBackgroundColor="white" hint="Search for Video via Company name"
                 [text]="term" #location (textChange)="searchFn(location.text)"></SearchBar>
```

**Comment by tsonevn** [comment]
Hi @harriscreativity,
I tested this scenario on my side, however, was unable to reproduce this an issue, while using multiple SearchBars in a single Page.
For your convenience, I am attaching a sample project. You could review it and make the needed changes, which will help us to reproduce the problem.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1007913/Archive.zip)

**Comment by harriscreativity** [comment]
Thanks
