### ISSUE TITLE
"globals" changes in v3.0.0 ?

### ISSUE THREAD

**Issue by rborn** [NativeScript/NativeScript#4222]
Hi,

I have a user that reports he cannot use `global.L()` anymore since the update - https://github.com/rborn/nativescript-i18n/issues/57
I didn't change any behaviour related to the global scope in the plugin when I updated it for 3.0.0.

Could anyone give us some ideas?
Thank you.

PS (I'm not good with typescript 😞)

**Comment by tsonevn** [comment]
Hi @rborn,
Thank you for writing us this issue.
From NativeScirpt 3.0 `global` module is typified. In this case, such methods like `L()` , which do not exist in `global` will break the typescript compilation. 
In your scenario, you could cast `global` to any, which will allow you to use the needed methods in NativeScript Typescript application.
For example:
```
declare var global:any;
```

**Comment by Buuhuu** [comment]
Or even better create a lib.d.ts file like 

```
declare namespace NodeJS {
    interface Global {
        process: any; // tslint:disable-line
    }
}
```

we used that for using redux

**Comment by rborn** [comment]
@Buuhuu @tsonevn  thank you, should I do this in the plugin or each project needs this?

**Comment by Buuhuu** [comment]
This extends the typing of the current project (similar to how the typescript typing libs work) so it has to be done in each project.

**Comment by rborn** [comment]
@Buuhuu thank you

**Comment by shyandsy** [comment]
@Buuhuu 
could u show more detail?
i created lib.d.ts with same content as u provided in my project(based on typescript), my code still not working.

i have some code like following based on nativescript 2.5.*
```
global.xxx = function()
{
    .........................
} 
```

the error message is: app/app.ts(450,8): error TS2339: Property 'xxx' does not exist on type 'Global'.

**Comment by bearoutthere** [comment]
@Buuhuu   same question as @shyandsy.  How to setup the lib.d.ts properly to avoid declaring global as any in every file.  Thanks in advance.
