### ISSUE TITLE
Showing a modal page from another modal page results in error on iOS.

### ISSUE THREAD

**Issue by hamorphis** [NativeScript/NativeScript#423]
Warning: Attempt to present UIViewControllerImpl 1 on UIViewControllerImpl 2 whose view is not in the window hierarchy!

**Comment by stonecourier** [comment]
I had a similar problem with this on Android. My "fix" was to ensure the popup passed the root page reference to the new popup, not use the modal page's page instance. This seemed to work fine from then on.

**Comment by hamorphis** [comment]
In fact, this is a limitation of the iOS. The developer will have to make sure that he has dismissed one modal page before showing another one. The master page on which you call .showModal has to be visible when you call it. In order to be visible in iOS, you would have to close the previous modal page with the supplied closeCallback. Since we can't really fix anything in our code, I am going to close this issue.

**Comment by hvadotnarola** [comment]
@stonecourier how did you passed root page reference to second modal ? I have same issue. Parent page opens modal page and from that modal page opens a small dialog.
