### ISSUE TITLE
How to change Home Page nativescript?

### ISSUE THREAD

**Issue by elpin1988** [NativeScript/NativeScript#4231]

**Comment by Jonatthu** [comment]
@elpin1988 Can you provide a better description of what you want to do?

Example NS VERSION, and the goal or specs, that question is not clear

**Comment by elpin1988** [comment]
I have a page default, but i want to introduce a page before, for example a login page, else i need change the home page a login page.

**Comment by tsonevn** [comment]
Hi @elpin1988,
To change the default page, which to be loaded in the application you should change the name of the module in `app.ts` file:
```
import "./bundle-config";
import * as app from 'application';

app.start({ moduleName: 'main-page' });
```
For more info about Application Architecture review the article  [here](http://docs.nativescript.org/core-concepts/navigation#set-home-page) 

For further `How to` questions please use our NativeScript forum [here](https://discourse.nativescript.org/).

**Comment by elpin1988** [comment]
my app.ts, but doesn´t show the login page first

import "./bundle-config";
import * as app from 'application';

app.start({ moduleName: 'login' });

**Comment by tsonevn** [comment]
Hi @elpin1988,
Could you provide some sample project, which could be debugged locally? 
Then I will be able to verify, whether there is an issue with the platform or it is something related to the project.

Thank you in advance for your cooperation.

**Comment by phantoxe** [comment]
I have the same issue. Can u help me?

In my app folder i just have app.module.ts    and    app.component.ts    and     main.ts

:-(

I need create a LOGIN PAGE first... :-(

**Comment by tsonevn** [comment]
Hi @phantoxe,
You could review [this article](https://docs.nativescript.org/core-concepts/angular-navigation), where it is described, how the use the router in NativeScript Angular application. For any further questions,  I would suggest using [NativeScript Forum](https://discourse.nativescript.org/).
