### ISSUE TITLE
Preloading modules are freezing the UI

### ISSUE THREAD

**Issue by codeback** [NativeScript/NativeScript#4232]
We are using "lazy-loaded modules" to improve the app booting. When we tap on a "lazy-loaded module", it takes a few seconds to load (and the UI is frozen). So that, we have decided to use "Preloaded module strategy":
```
NativeScriptRouterModule.forRoot(<any>NSRoutes, {preloadingStrategy: PreloadModules})
```
The problem now is that while the user is navigating the app gets frozen.

In summary, now we get the "freezing moment" while the user is navigating the page instead of when the users tap the route of the lazy-loaded module :(.

I think a possible solution would be to make this preloading process occur in a separate thread like Nativescript does when requesting images.

**Comment by sis0k0** [comment]
This issue was moved to NativeScript/nativescript-angular#809
