### ISSUE TITLE
image-source saveToFile does not work - related to issue 4237

### ISSUE THREAD

**Issue by xanZ08** [NativeScript/NativeScript#4242]
Please help me save a image taken from camera to file.
I need the filename and filepath, so I can take next action to it.
Saving to gallery will not help me, as I do not have the file name. Below is the code. and the error is 
JS: TypeError: img.saveToFile is not a function
I am running tns 3.0.1
Help please.

var cameraModule = require("nativescript-camera");
var fs = require('file-system');
var imageSource = require("image-source");
var enumsModule  = require('ui/enums');
var imageModule = require("ui/image");
var format = enumsModule.ImageFormat.jpeg
console.log(JSON.stringify(imageSource));
exports.takepic=function(){
    console.log('take pic');
    cameraModule.requestPermissions()
cameraModule.takePicture({
    width: 300,
    height: 300,
    keepAspectRatio: true
}).then(function (imageAsset) {
    console.log("Image taken!");
    console.log(JSON.stringify(img));
   
     try{
    var img=imageSource.fromAsset(imageAsset);     
         console.log(JSON.stringify(img));
    var folder = fs.knownFolders.documents().path;
    console.log('folder - ', folder); // => object
    var fileName = 'img_' + new Date().getTime() + '.' + format
    var path = fs.path.join(folder, fileName);
    console.log('path - ', path); // => correct path
    
   
    img.saveToFile(path, format); // ### Execution stops here.
    console.log('saved - ', saved); 
    console.log('saved - ');
    }
    catch(e){
        console.log(e);
    }

    var imgLocal = imageSource.fromFile(path);

    pageData.camera.set("cameraImage", img);
});
}

**Comment by tsonevn** [comment]
Hi @xanZ08,
I reviewed your code and found that the issue, which you are facing is related to the fact that you have missed creating a new ImageSource instance, before calling `fromAsset` method. In your case to avoid the above-mentioned error you could include the following line:
```
var  img= new imageSourceModule.ImageSource();
```
For further help you could also review the attached sample application:
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1018120/Archive.zip)

**Comment by xanZ08** [comment]
Thank you.
I think this needs to be updated in the documents.
https://docs.nativescript.org/cookbook/image-source

**Comment by tsonevn** [comment]
PR: [#4265](https://github.com/NativeScript/NativeScript/pull/4265)
