### ISSUE TITLE
Issue with plugins and Cocoapods

### ISSUE THREAD

**Issue by dogabudak** [NativeScript/NativeScript#4243]
I am keeping getting this error when I try to run my Applications . I deleted and re-installed plugins nothing has changed. 
`<A Plug-in> has Podfile and you don't have Cocoapods installed or it is not configured correctly. Please verify Cocoapods can work on your machine.
`
pod --version
1.2.1
tns --version
3.0.1

**Comment by tsonevn** [comment]
Hi @dogabudak.
 I' ve tried to reproduce your case on my side, however, everything seems to work as expected while using a plugin with a pod. 
For testing this case with `nativescript-iqkeyboardmanager` plugin, while using latest cocoapods `1.2.1` and CLI `3,0,1`.
Regarding that, it would help if you could provide some more info about the problem. It would help also if you could send us a sample project or at least the `package.json` file.

**Comment by dtopuzov** [comment]
Hi @dogabudak 

Can you please run `pod setup` and retry?

**Comment by joseph-montanez** [comment]
I had the issue and its due to RVM:

```
Josephs-Mac-mini:MyApp josephmontanez$ gem list --local | grep cocoapods
cocoapods (1.3.1, 1.2.0, 0.39.0)
cocoapods-core (1.3.1, 1.2.0, 0.39.0)
cocoapods-deintegrate (1.0.1)
cocoapods-downloader (1.1.3, 0.9.3)
cocoapods-plugins (1.0.0, 0.4.2)
cocoapods-search (1.0.0, 0.1.0)
cocoapods-stats (1.0.0, 0.6.2)
cocoapods-trunk (1.3.0, 1.1.2, 0.6.4)
cocoapods-try (1.1.0, 0.5.1)
motion-cocoapods (1.8.1, 1.7.8, 1.7.5)
```

As you can see I had multiple versions of the gems and my RVM was set to Ruby-2.2:

```
Josephs-Mac-mini:MyApp josephmontanez$ rvm list

rvm rubies

=> ruby-2.2.0 [ x86_64 ]
   * ruby-2.4.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```

So I ended up removing cocoapods from my Ruby 2.2 instance:

```
gem uninstall --force cocoapods
gem uninstall --force cocoapods-core
gem uninstall --force cocoapods-deintegrate
gem uninstall --force cocoapods-downloader
gem uninstall --force cocoapods-plugins
gem uninstall --force cocoapods-search
gem uninstall --force cocoapods-stats
gem uninstall --force cocoapods-trunk
gem uninstall --force cocoapods-try
```

I then switched to my Ruby-2.4 instance:

`rvm use ruby-2.4.0`

`gem uninstall --force cocoapods`

> Remove executables:
>         pod, sandbox-pod
> 
> in addition to the gem? [Yn]  Y
> Removing pod
> Removing sandbox-pod
> Successfully uninstalled cocoapods-1.2.0

Then removed the rest of the gems:


```
gem uninstall --force cocoapods-core
gem uninstall --force cocoapods-deintegrate
gem uninstall --force cocoapods-downloader
gem uninstall --force cocoapods-plugins
gem uninstall --force cocoapods-search
gem uninstall --force cocoapods-stats
gem uninstall --force cocoapods-trunk
gem uninstall --force cocoapods-try
```

And reinstalled cocoapods:

`sudo gem install cocoapods`

And I was all set. You might need to add / remove the plugin, again. I nuked the iOS platform all together just to make sure.
