### ISSUE TITLE
tabview image navigation in nativescript angular app

### ISSUE THREAD

**Issue by nelsonwilliam11** [NativeScript/NativeScript#4246]
am trying to tab one an image on the tabview  stacklayout then it navigate me to another file(page)
thanks

**Comment by tsonevn** [comment]
Hi @nelsonwilliam11,
Thank you for contacting us.
For your case, you could set tap event to the Image component as it is shown in the example below and to navigate to next page while using RouterExtention. More about the router and how to use it could be found [here](http://docs.nativescript.org/angular/core-concepts/angular-navigation.html#clearing-page-navigation-history).

HTML
```
<ActionBar title="My App" class="action-bar">
</ActionBar>
<StackLayout class="page">
   <Image width="30" height="30" (tap)="test()" src="~/icon.png"></Image>
</StackLayout>
```
TypeScript 
```
import { Component, OnInit } from "@angular/core";


@Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
})
export class ItemsComponent implements OnInit {

    constructor() { }

    ngOnInit(): void {
    }

    test(){
        console.log("image tap")
    }
}
```

**Comment by nelsonwilliam11** [comment]
<StackLayout *tabItem="{title: '', iconSource:'res://aaa'}">
              </StackLayout>

**Comment by nelsonwilliam11** [comment]
<StackLayout *tabItem="{title: '', iconSource:'res://aaa'}">

              </StackLayout>

**Comment by nelsonwilliam11** [comment]
thats how my tabview looks like i want to tab on the iconsource and it navigates me to another file
