### ISSUE TITLE
OptionsMenu MenuItem icon not showing

### ISSUE THREAD

**Issue by duongnhatduy** [NativeScript/NativeScript#425]
Hi,

I have tried different values for "icon" property of MenuItem but cannot get the icon to display.
I tried with &lt;MenuItem icon="~/res/image.png" /&gt;. It doesn't show for both iOS and Android.
I also tried using App_Resources images like &lt;MenuItem icon="icon.png" /&gt;. It shows incorrectly for iOS and nothing for Android

**Comment by vakrilov** [comment]
@duongnhatduy We are close to releasing the next version of the {N} modules(1.2.0) and we have significant changes in the action-bar API. You can check [here](https://github.com/NativeScript/NativeScript/blob/master/apps/action-bar-demo/pages/action-items-icon.xml) how action bar items will be defined with the new release. So, my suggestion is to try the new approach when the release is out as there are changes in the image loading logic too.
