### ISSUE TITLE
Span renders line break as zero

### ISSUE THREAD

**Issue by triniwiz** [NativeScript/NativeScript#4251]
In 2.5.x i used the following to get a simple icon above some text design 

```html
<Button [nsRouterLinkActiveOptions]="{exact:true }" [nsRouterLinkActive]="['active']" [nsRouterLink]="item.menuLink" textWrap="true">
        <FormattedString>
            <Span [icon]="item.icon" [fontSize]="item.size ? item.size : '14'" fontFamily="icons"></Span>
            <Span [text]="item.label ? '\n\n' : ''"></Span>
            <Span class="menu-text" [text]="item.label"></Span>
        </FormattedString>
    </Button>
```
result

<img width="60" alt="screen shot 2017-05-01 at 11 41 03 am" src="https://cloud.githubusercontent.com/assets/6695919/26306010/ac002b1e-3ebf-11e7-87cb-875f1874fc3a.png">

In 3.0.x it results in the following

<img width="40" alt="screen shot 2017-05-19 at 10 16 49 pm" src="https://cloud.githubusercontent.com/assets/6695919/26306049/dd865ea6-3ebf-11e7-9a06-b567cfc9b177.png">

tns 3.0.1
tns-ios 3.0.0
core-modules: 3.0.0  and next

**Comment by tsonevn** [comment]
Hi @triniwiz,
Thank you for reporting this issue,
I tested this case on my side and indeed this is a real issue in NativeScirpt Angular 2 application. This problem is not reproducible in while using a pure NativeScirpt app.
As a workaround, you could use the below-attached code, where the check, if there is text available, is made on the second span.
Example:
```
<StackLayout class="page">
    <GridLayout rows="" columns="">
        <Button  textWrap="true">
            <FormattedString>
                <Span fontFamily="FontAwesome" [text]="title" fontSize="14" ></Span>
                <Span class="menu-text" [text]="label ? '\n\n'+label : ''"></Span>
            </FormattedString>
        </Button>
    </GridLayout>
</StackLayout>
```

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#813
