### ISSUE TITLE
HTTP Patch not working on Android API level 18

### ISSUE THREAD

**Issue by ludcila** [NativeScript/NativeScript#4252]
### Tell us about the problem
I get a "Response with status: 200  for URL: null" right away when I issue an HTTP PATCH request on Android API 18, although it works fine on API 23, 24 and 25.  Other methods also work fine.

### Which platform(s) does your issue occur on?
Tested on Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.1
- Cross-platform modules: 3.0.0 / 2.5.2
- Runtime(s): 3.0.0 / 2.5.0

### Please tell us how to recreate the issue in as much detail as possible.

I created a blank project using an Angular template, and I am making http requests in the ngOnInit function of AppComponent.

This is my `package.json` file.  

Your help is appreciated.  Please let me know if you need more information.

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.testpatch",
    "tns-android": {
      "version": "3.0.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/router": "~4.1.0",
    "nativescript-angular": "~3.0.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "~3.0.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.4.0",
    "typescript": "~2.2.1"
  }
}
```

Thanks!
Lucía

**Comment by NickIliev** [comment]
@ludcila this is a limitation of the lower API levels in Android as discussed [here](https://stackoverflow.com/questions/25163131/httpurlconnection-invalid-http-method-patch) and in other multiple threads. HTTP Patch request is supported only by the newer API levels. Meanwhile, you can try the workaround provided by the Android users by overwriting the method in the headers. However, keep in mind that this won't work with every server as some servers are not allowing method overwriting.

example for overwriting the POST with PATCH method via headers
```
http.request({
            url: "https://some-server.com/patch",
            method: "POST",
            headers: { 
                "X-HTTP-Method-Override": "PATCH",
                "Content-Type": "application/json"
            },
            content: JSON.stringify({ MyVariableOne: "ValueOne", MyVariableTwo: "ValueTwo" })
        }).then (() => {
        })
```

If that works you might also want to overwrite only for the lower API levels.
```
android.os.Build.VERSION.SDK_INT <= android.os.Build.VERSION_CODES.KITKAT
```

**Comment by ludcila** [comment]
Ok, I will try that.  Thanks a lot for your help @NickIliev :)
