### ISSUE TITLE
Setting fontSize to multiple spans crashes app

### ISSUE THREAD

**Issue by triniwiz** [NativeScript/NativeScript#4253]
If i set the fontSize to more than one span the app will crash

```css
.h3{
font-size:32;
}

```
```html
<Label>
        <FormattedString>
            <Span class="h3 accent" [icon]="icon" fontFamily="icons"></Span>
            <Span class="h3 title" [text]="' ' + title + '  '"></Span>
            <Span class="subtitle" [text]="subtitle"></Span>
    </FormattedString>
    </Label>
```

or if i try 

```html
    <Label class="h3">
        <FormattedString>
            <Span class="accent" [loopIcon]="icon" fontFamily="loop-icons"></Span>
            <Span class="title" [text]="' ' + title + '  '"></Span>
            <Span class="subtitle" [text]="subtitle"></Span>
    </FormattedString>
    </Label>
```

tns 3.0.1
tns-ios 3.0.0
core-modules: 3.0.0 and next

**Comment by NickIliev** [comment]
@triniwiz I have tested your case using [this test application ](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4253)but was not able to reproduce.

Basically using this to set the FormattedString
```
    <Label>
        <FormattedString>
            <Span class="h1" text="h1 "></Span>
            <Span class="h2" text="h2 "></Span>
            <Span class="h3" text="h3 "></Span>
            <Span class="head" text="head "></Span>
            <Span class="h3 label" text="label "></Span>

            <Span class="bigger-head fa" text="&#xf019; "></Span>

            <Span class="title" [text]="bindedText"></Span>
        </FormattedString>
    </Label>
```

and this in my app.css
```
.head{
    font-size:32;
}
.bigger-head{
    font-size:48;
}
.fa {
    font-family: "FontAwesome"
}
@import 'nativescript-theme-core/css/core.light.css';
```

However, I do suspect that you issue might be [related to this one](https://github.com/NativeScript/NativeScript/issues/4230). I saw that you are using FontFamily and setting some icon font - can you clarify what that font is and how are you setting it in your fonts folder.

I have used [FontAwesome](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4253/app/fonts) in my test application and was able to [set in on a Span using the text property](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/NativeScript/issue_4253/app/item/items.component.html#L12)

**Comment by NickIliev** [comment]
@triniwiz we've noticed that you have custom properties **icon** and **loopIcon** probably made via Angular directives - perhaps the code behind is also related to your issue.

**Comment by triniwiz** [comment]
Using a timeout fixed the issue for now
