### ISSUE TITLE
Calling a method in Parent class from Child Class when Navigating Back.

### ISSUE THREAD

**Issue by deepak4u2006** [NativeScript/NativeScript#4254]
I have implemented a custom BottomSheet in Nativescript + Angular, I am Navigating a page using Transaition: slideTop.
```
changePocket() 
{
        console.log("Inside The delegate class");
        this.data.storage = [];
        this.routerExtensions.navigate(["vdlist-modal"], {
            animated: true,
            transition: {
                name: "slideTop",
                curve: "easeOut"
            }
        });
    }
```

While closing the Bottomsheet, I need to get a callback or some event to be called in the Class presenting it.
For closing the Botomsheet I am using the 
```
this.routerExtensions.backToPreviousPage();
```

**Comment by NickIliev** [comment]
Hey, @deepak4u2006 this repository is mainly for logging and discussing issues, bugs, and features.
For application logic and structure related questions I would recommend using the public community channels such as [forum.nativescript.org](forum.nativescript.org) and SO.

Suggestions: In NativeScript we have modal pages which are using close callbacks - look for example [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/modal-page/sample-modal-page-module-example).

Or in Angular, you can pass parameters when navigating using [ActivatedRoute](https://angular.io/docs/ts/latest/api/router/index/ActivatedRoute-interface.html)
Documentation section [here](http://docs.nativescript.org/angular/core-concepts/angular-navigation.html#passing-parameter)

**Comment by deepak4u2006** [comment]
Hi @NickIliev Sorry for the behaviour, I assure this won't be repeated next time.
Thanks for the suggestions!!
