### ISSUE TITLE
ListPicker style not applied

### ISSUE THREAD

**Issue by tigrenok00** [NativeScript/NativeScript#4259]
Hi,
I'm using ListPicker with Angular, and it seems like it doesn't repsect css class or style.font-size properties, is there an issue with this?
Thanks!

**Comment by NickIliev** [comment]
Hey, @tigrenok00 the only supported properties for [ListPicker ](http://docs.nativescript.org/api-reference/classes/_ui_list_picker_.listpicker.html)are **color** and **backgroundColor**,
The option to change font related propeties is loged as a feature [here](https://github.com/NativeScript/NativeScript/issues/3863).

Closing as related to [https://github.com/NativeScript/NativeScript/issues/3863](https://github.com/NativeScript/NativeScript/issues/3863)
