### ISSUE TITLE
[iOS] Unloaded event of any element positioned in ListView ItemTemplate does not rise

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#426]
The issue is present on iOS and expected to reproduce on Android, but there it works somehow.

For example:
```xml
<Page>
  <ListView loaded="onListViewLoaded">
    <ListView.itemTemplate>
      <Label unloaded="onLabelUnloaded" minHeight="250" />
    </ListView.itemTemplate>
  </ListView>
</Page>
```

```typescript
export function onListViewLoaded(args) {
    args.object.items = [1];
}

export function onLabelUnloaded(args) {
    console.log("Label unloaded.");
}
```

**Comment by hamorphis** [comment]
Unfortunately, I was unable to create an automated unit test for testing such irregular behavior. I added a new sample app called list-view-demo which is a playground for testing the loaded/unloaded events.

**Comment by hamorphis** [comment]
I will undo the changes for performance reasons.

**Comment by hamorphis** [comment]
https://github.com/NativeScript/NativeScript/pull/531
