### ISSUE TITLE
navigation with tabview iconSource nativescript ng

### ISSUE THREAD

**Issue by nelsonwilliam11** [NativeScript/NativeScript#4262]
```
 <StackLayout *tabItem="{title: '', iconSource:'res://aaa'}">

              </StackLayout>
```
thats one of my tabview stacklayouts they are four what i want is when i tap the iconSource(image) it navigates me to another file(page) for example Instgram status bar you tap on profile it takes u to your profile page and so on
am trying to implement Instgram's secnario

**Comment by tsonevn** [comment]
Hi @nelsonwilliam11,
If I understand you correctly, you want to handle the tap event to specific Tab of the control and to navigate to the specific page.  

For this scenario I could suggest using SegmentedBar, where you could handle the tap on specific item and to create your custom functionality. On Item tap you could navigate to the the needed page. For example:

HTML
```
<SegmentedBar [items]="myItems" selectedIndex="0" (selectedIndexChange)="onSelectedIndexChange($event)" class="m-5"></SegmentedBar>
```

TypeScript 
```
public onSelectedIndexChange(args) {
        let segmetedBar = <SegmentedBar>args.object;
        this.prop = "Item" + (segmetedBar.selectedIndex + 1);
    }
```

For further help you could review the sample app [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/ui-category/segmented-bar).
