### ISSUE TITLE
sample project won't build on Android

### ISSUE THREAD

**Issue by c1ngular** [NativeScript/NativeScript#4268]
i use "tns create sample" to successfully created a project , when i tried to run it on Android , it fails to build , says :
```
> Executing before-prepare hook from /Users/c1ngular/Projects/TNSProject/sample/hooks/before-prepare/nativescript-dev-android-snapshot.js
Preparing project...

:config phase:  createDefaultIncludeFiles

:config phase:  addAarDependencies
        +adding dependency: /Users/c1ngular/Projects/TNSProject/sample/platforms/android/libs/aar/widgets-release.aar
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'sample'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.774 secs
Processing node_modules failed. Error: Command ./gradlew failed with exit code 1
```

it works fine on iOS emulator !
Java version "1.8.0_121"
TNS:  3.0.1
Android SDK Build Tools : 25.0.2
Android SDK Platform-Tools :25.0.6

thanks !

**Comment by NickIliev** [comment]
@c1ngular can you provide the detailed error log with
```
tns run android --log trace > log.txt
```

**Comment by c1ngular** [comment]
@NickIliev 

--- log trace ---

Loading extensions.
execFile: /usr/local/share/android-sdk/platform-tools/adb "help"
Exec uname -a 
 stdout: Darwin was-MacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
 
 stderr: 
Exec npm -v 
 stdout: 4.6.1
 
 stderr: 
spawn: java "-version"
Exec node-gyp -v 
 stdout:  
 stderr: /bin/sh: node-gyp: command not found

Exec xcodebuild -version 
 stdout: Xcode 8.3.2
Build version 8E2002
 
 stderr: 
Exec gem which xcodeproj 
 stdout: /Users/c1ngular/.rvm/gems/ruby-2.2.5/gems/xcodeproj-1.4.4/lib/xcodeproj.rb
 
 stderr: 
Exec pod --version 
 stdout: 1.2.1
 
 stderr: 
Exec '/usr/local/share/android-sdk/platform-tools/adb' version 
 stdout: Android Debug Bridge version 1.0.39
Revision 3db08f2c6889-android
Installed as /usr/local/share/android-sdk/platform-tools/adb
 
 stderr: 
spawn: /usr/local/share/android-sdk/emulator/emulator "-help"
Result when throw error is false:
{ stdout: 'Android Emulator usage: emulator [options] [-qemu args]\n  options:\n    -list-avds                     list available AVDs\n    -sysdir <dir>                  search for system disk images in <dir>\n    -system <file>                 read initial system image from <file>\n    -writable-system               make system image writable after \'adb remount\'\n    -datadir <dir>                 write user data into <dir>\n    -kernel <file>                 use specific emulated kernel\n    -ramdisk <file>                ramdisk image (default <system>/ramdisk.img\n    -image <file>                  obsolete, use -system <file> instead\n    -initdata <file>               same as \'-init-data <file>\'\n    -data <file>                   data image (default <datadir>/userdata-qemu.img\n    -partition-size <size>         system/data partition size in MBs\n    -cache <file>                  cache partition image (default is temporary file)\n    -cache-size <size>             cache partition size in MBs\n    -no-cache                      disable the cache partition\n    -nocache                       same as -no-cache\n    -sdcard <file>                 SD card image (default <datadir>/sdcard.img\n    -snapstorage <file>            file that contains all state snapshots (default <datadir>/snapshots.img)\n    -no-snapstorage                do not mount a snapshot storage file (this disables all snapshot functionality)\n    -snapshot <name>               name of snapshot within storage file for auto-start and auto-save (default \'default-boot\')\n    -no-snapshot                   perform a full boot and do not do not auto-save, but qemu vmload and vmsave operate on snapstorage\n    -no-snapshot-save              do not auto-save to snapshot on exit: abandon changed state\n    -no-snapshot-load              do not auto-start from snapshot: perform a full boot\n    -snapshot-list                 show a list of available snapshots\n    -no-snapshot-update-time       do not do try to correct snapshot time on restore\n    -wipe-data                     reset the user data image (copy it from initdata)\n    -avd <name>                    use a specific android virtual device\n    -skindir <dir>                 search skins in <dir> (default <system>/skins)\n    -skin <name>                   select a given skin\n    -no-skin                       deprecated: create an AVD with no skin instead\n    -noskin                        same as -no-skin\n    -memory <size>                 physical RAM size in MBs\n    -cores <number>                Set number of CPU cores to emulator\n    -accel <mode>                  Configure emulation acceleration\n    -no-accel                      Same as \'-accel off\'\n    -ranchu                        Use new emulator backend instead of the classic one\n    -engine <engine>               Select engine. auto|classic|qemu2\n    -netspeed <speed>              maximum network download/upload speeds\n    -netdelay <delay>              network latency emulation\n    -netfast                       disable network shaping\n    -code-profile <name>           enable code profiling\n    -show-kernel                   display kernel messages\n    -shell                         enable root shell on current terminal\n    -no-jni                        disable JNI checks in the Dalvik runtime\n    -nojni                         same as -no-jni\n    -logcat <tags>                 enable logcat output with given tags\n    -no-audio                      disable audio support\n    -noaudio                       same as -no-audio\n    -audio <backend>               use specific audio backend\n    -radio <device>                redirect radio modem interface to character device\n    -port <port>                   TCP port that will be used for the console\n    -ports <consoleport>,<adbport> TCP ports used for the console and adb bridge\n    -onion <image>                 use overlay PNG image over screen\n    -onion-alpha <%age>            specify onion-skin translucency\n    -onion-rotation 0|1|2|3        specify onion-skin rotation\n    -dpi-device <dpi>              specify device\'s resolution in dpi (default 165)\n    -scale <scale>                 scale emulator window (deprecated)\n    -http-proxy <proxy>            make TCP connections through a HTTP/HTTPS proxy\n    -timezone <timezone>           use this timezone instead of the host\'s default\n    -dns-server <servers>          use this DNS server(s) in the emulated system\n    -cpu-delay <cpudelay>          throttle CPU emulation\n    -no-boot-anim                  disable animation for faster boot\n    -no-window                     disable graphical window display\n    -version                       display emulator version number\n    -report-console <socket>       report console port to remote socket\n    -gps <device>                  redirect NMEA GPS to character device\n    -shell-serial <device>         specific character device for root shell\n    -tcpdump <file>                capture network packets to file\n    -bootchart <timeout>           enable bootcharting\n    -charmap <file>                use specific key character map\n    -prop <name>=<value>           set system property on boot\n    -shared-net-id <number>        join the shared network, using IP address 10.1.2.<number>\n    -nand-limits <nlimits>         enforce NAND/Flash read/write thresholds\n    -gpu <mode>                    set hardware OpenGLES emulation mode\n    -camera-back <mode>            set emulation mode for a camera facing back\n    -camera-front <mode>           set emulation mode for a camera facing front\n    -webcam-list                   lists web cameras available for emulation\n    -screen <mode>                 set emulated screen mode\n    -force-32bit                   always use 32-bit emulator\n    -selinux <disabled|permissive> Set SELinux to either disabled or permissive mode\n    -unix-pipe <path>              Add <path> to the list of allowed Unix pipes\n    -fixed-scale                   Use fixed 1:1 scale for the initial emulator window.\n    -wait-for-debugger             Pause on launch and wait for a debugger process to attach before resuming\n    -skip-adb-auth                 Skip adb authentication dialogue\n\n     -qemu args...                 pass arguments to qemu\n     -qemu -h                      display qemu help\n\n     -verbose                      same as \'-debug-init\'\n     -debug <tags>                 enable/disable debug messages\n     -debug-<tag>                  enable specific debug messages\n     -debug-no-<tag>               disable specific debug messages\n\n     -help                         print this help\n     -help-<option>                print option-specific help\n\n     -help-disk-images             about disk images\n     -help-debug-tags              debug tags for -debug <tags>\n     -help-char-devices            character <device> specification\n     -help-environment             environment variables\n     -help-virtual-device          virtual device management\n     -help-sdk-images              about disk images when using the SDK\n     -help-build-images            about disk images when building Android\n     -help-all                     prints all help content\n\n',
  stderr: '',
  exitCode: 0 }
The result of checking is Android Emulator installed is:
- stdout: Android Emulator usage: emulator [options] [-qemu args]
  options:
    -list-avds                     list available AVDs
    -sysdir <dir>                  search for system disk images in <dir>
    -system <file>                 read initial system image from <file>
    -writable-system               make system image writable after 'adb remount'
    -datadir <dir>                 write user data into <dir>
    -kernel <file>                 use specific emulated kernel
    -ramdisk <file>                ramdisk image (default <system>/ramdisk.img
    -image <file>                  obsolete, use -system <file> instead
    -initdata <file>               same as '-init-data <file>'
    -data <file>                   data image (default <datadir>/userdata-qemu.img
    -partition-size <size>         system/data partition size in MBs
    -cache <file>                  cache partition image (default is temporary file)
    -cache-size <size>             cache partition size in MBs
    -no-cache                      disable the cache partition
    -nocache                       same as -no-cache
    -sdcard <file>                 SD card image (default <datadir>/sdcard.img
    -snapstorage <file>            file that contains all state snapshots (default <datadir>/snapshots.img)
    -no-snapstorage                do not mount a snapshot storage file (this disables all snapshot functionality)
    -snapshot <name>               name of snapshot within storage file for auto-start and auto-save (default 'default-boot')
    -no-snapshot                   perform a full boot and do not do not auto-save, but qemu vmload and vmsave operate on snapstorage
    -no-snapshot-save              do not auto-save to snapshot on exit: abandon changed state
    -no-snapshot-load              do not auto-start from snapshot: perform a full boot
    -snapshot-list                 show a list of available snapshots
    -no-snapshot-update-time       do not do try to correct snapshot time on restore
    -wipe-data                     reset the user data image (copy it from initdata)
    -avd <name>                    use a specific android virtual device
    -skindir <dir>                 search skins in <dir> (default <system>/skins)
    -skin <name>                   select a given skin
    -no-skin                       deprecated: create an AVD with no skin instead
    -noskin                        same as -no-skin
    -memory <size>                 physical RAM size in MBs
    -cores <number>                Set number of CPU cores to emulator
    -accel <mode>                  Configure emulation acceleration
    -no-accel                      Same as '-accel off'
    -ranchu                        Use new emulator backend instead of the classic one
    -engine <engine>               Select engine. auto|classic|qemu2
    -netspeed <speed>              maximum network download/upload speeds
    -netdelay <delay>              network latency emulation
    -netfast                       disable network shaping
    -code-profile <name>           enable code profiling
    -show-kernel                   display kernel messages
    -shell                         enable root shell on current terminal
    -no-jni                        disable JNI checks in the Dalvik runtime
    -nojni                         same as -no-jni
    -logcat <tags>                 enable logcat output with given tags
    -no-audio                      disable audio support
    -noaudio                       same as -no-audio
    -audio <backend>               use specific audio backend
    -radio <device>                redirect radio modem interface to character device
    -port <port>                   TCP port that will be used for the console
    -ports <consoleport>,<adbport> TCP ports used for the console and adb bridge
    -onion <image>                 use overlay PNG image over screen
    -onion-alpha <%age>            specify onion-skin translucency
    -onion-rotation 0|1|2|3        specify onion-skin rotation
    -dpi-device <dpi>              specify device's resolution in dpi (default 165)
    -scale <scale>                 scale emulator window (deprecated)
    -http-proxy <proxy>            make TCP connections through a HTTP/HTTPS proxy
    -timezone <timezone>           use this timezone instead of the host's default
    -dns-server <servers>          use this DNS server(s) in the emulated system
    -cpu-delay <cpudelay>          throttle CPU emulation
    -no-boot-anim                  disable animation for faster boot
    -no-window                     disable graphical window display
    -version                       display emulator version number
    -report-console <socket>       report console port to remote socket
    -gps <device>                  redirect NMEA GPS to character device
    -shell-serial <device>         specific character device for root shell
    -tcpdump <file>                capture network packets to file
    -bootchart <timeout>           enable bootcharting
    -charmap <file>                use specific key character map
    -prop <name>=<value>           set system property on boot
    -shared-net-id <number>        join the shared network, using IP address 10.1.2.<number>
    -nand-limits <nlimits>         enforce NAND/Flash read/write thresholds
    -gpu <mode>                    set hardware OpenGLES emulation mode
    -camera-back <mode>            set emulation mode for a camera facing back
    -camera-front <mode>           set emulation mode for a camera facing front
    -webcam-list                   lists web cameras available for emulation
    -screen <mode>                 set emulated screen mode
    -force-32bit                   always use 32-bit emulator
    -selinux <disabled|permissive> Set SELinux to either disabled or permissive mode
    -unix-pipe <path>              Add <path> to the list of allowed Unix pipes
    -fixed-scale                   Use fixed 1:1 scale for the initial emulator window.
    -wait-for-debugger             Pause on launch and wait for a debugger process to attach before resuming
    -skip-adb-auth                 Skip adb authentication dialogue

     -qemu args...                 pass arguments to qemu
     -qemu -h                      display qemu help

     -verbose                      same as '-debug-init'
     -debug <tags>                 enable/disable debug messages
     -debug-<tag>                  enable specific debug messages
     -debug-no-<tag>               disable specific debug messages

     -help                         print this help
     -help-<option>                print option-specific help

     -help-disk-images             about disk images
     -help-debug-tags              debug tags for -debug <tags>
     -help-char-devices            character <device> specification
     -help-environment             environment variables
     -help-virtual-device          virtual device management
     -help-sdk-images              about disk images when using the SDK
     -help-build-images            about disk images when building Android
     -help-all                     prints all help content


- stderr: 
Exec mono --version 
 stdout:  
 stderr: /bin/sh: mono: command not found

Exec git --version 
 stdout: git version 2.11.0 (Apple Git-81)
 
 stderr: 
Exec gradle -v 
 stdout:  
 stderr: /bin/sh: gradle: command not found

Exec "/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/javac" -version 
 stdout:  
 stderr: javac 1.8.0_121

System information:
{ procInfo: 'nativescript/3.0.1',
  platform: 'darwin',
  os: 'Darwin was-MacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64\n',
  shell: '/bin/bash',
  dotNetVer: null,
  procArch: 'x64',
  nodeVer: 'v7.10.0',
  npmVer: '4.6.1',
  javaVer: '1.8.0',
  nodeGypVer: null,
  xcodeVer: 'Xcode 8.3.2\nBuild version 8E2002\n',
  xcodeprojGemLocation: '/Users/c1ngular/.rvm/gems/ruby-2.2.5/gems/xcodeproj-1.4.4/lib/xcodeproj.rb\n',
  itunesInstalled: true,
  cocoapodVer: '1.2.1',
  adbVer: 'Android Debug Bridge version 1.0.39',
  emulatorInstalled: true,
  monoVer: null,
  gitVer: '2.11.0 (Apple Git-81)',
  gradleVer: null,
  javacVersion: '1.8.0_121' }
Looking for project in '/Users/c1ngular/Projects/TNSProject/sample'
Project directory is '/Users/c1ngular/Projects/TNSProject/sample'.
Validate options for platform: Android
Initializing analytics statuses.
Analytics statuses: 
{ TrackFeatureUsage: 1, TrackExceptions: 1 }
Trying to track feature 'Non-interactive' with value 'run|android'.
Analytics statuses: 
{ TrackFeatureUsage: 1, TrackExceptions: 1 }
Trying to track feature 'Working with project type' with value 'Pure JavaScript'.
Changes info in prepare platform: ProjectChangesInfo {
  appFilesChanged: true,
  appResourcesChanged: true,
  modulesChanged: true,
  configChanged: true }
Project dir from hooksArgs is: /Users/c1ngular/Projects/TNSProject/sample.
Hooks directories: [ '/usr/local/lib/node_modules/nativescript/lib/hooks',
  '/usr/local/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/c1ngular/Projects/TNSProject/sample/hooks' ]
BeforeHookName for command prepare is before-prepare
Executing before-prepare hook from /Users/c1ngular/Projects/TNSProject/sample/hooks/before-prepare/nativescript-dev-android-snapshot.js
Executing before-prepare hook at location /Users/c1ngular/Projects/TNSProject/sample/hooks/before-prepare/nativescript-dev-android-snapshot.js in-process
Validating before-prepare arguments.
Hook completed
Preparing project...
spawn: node "/Users/c1ngular/Projects/TNSProject/sample/platforms/android/build-tools/check-v8-dependants.js" "[{"name":"nativescript-theme-core","directory":"/Users/c1ngular/Projects/TNSProject/sample/node_modules/nativescript-theme-core","depth":0,"nativescript":{"platforms":{"ios":"2.4.0","android":"2.4.0"}}},{"name":"tns-core-modules","directory":"/Users/c1ngular/Projects/TNSProject/sample/node_modules/tns-core-modules","depth":0,"nativescript":{"platforms":{"ios":"2.1.1","android":"2.1.1"}}},{"name":"tns-core-modules-widgets","directory":"/Users/c1ngular/Projects/TNSProject/sample/node_modules/tns-core-modules-widgets","depth":0,"nativescript":{"platforms":{"ios":"2.0.0","android":"2.0.0"}}}]" "/Users/c1ngular/Projects/TNSProject/sample/platforms"
Installed Android Targets are:  [ 'android-25' ]
Directories found in /usr/local/share/android-sdk/build-tools are 25.0.2
Versions found in /usr/local/share/android-sdk/build-tools are 25.0.2
Selected version is:  25.0.2
Selected targetSdk is: 25
Directories found in /usr/local/share/android-sdk/extras/android/m2repository/com/android/support/appcompat-v7 are 18.0.0, 19.0.0, 19.0.1, 19.1.0, 20.0.0, 21.0.0, 21.0.2, 21.0.3, 22.0.0, 22.1.0, 22.1.1, 22.2.0, 22.2.1, 23.0.0, 23.0.1, 23.1.0, 23.1.1, 23.2.0, 23.2.1, 23.3.0, 23.4.0, 24.0.0, 24.0.0-alpha1, 24.0.0-alpha2, 24.0.0-beta1, 24.1.0, 24.1.1, 24.2.0, 24.2.1, 25.0.0, 25.0.1, 25.1.0, 25.1.1, 25.2.0, 25.3.0, 25.3.1, 26.0.0-alpha1, maven-metadata.xml, maven-metadata.xml.md5, maven-metadata.xml.sha1
Versions found in /usr/local/share/android-sdk/extras/android/m2repository/com/android/support/appcompat-v7 are 18.0.0, 19.0.0, 19.0.1, 19.1.0, 20.0.0, 21.0.0, 21.0.2, 21.0.3, 22.0.0, 22.1.0, 22.1.1, 22.2.0, 22.2.1, 23.0.0, 23.0.1, 23.1.0, 23.1.1, 23.2.0, 23.2.1, 23.3.0, 23.4.0, 24.0.0, 24.0.0, 24.0.0, 24.0.0, 24.1.0, 24.1.1, 24.2.0, 24.2.1, 25.0.0, 25.0.1, 25.1.0, 25.1.1, 25.2.0, 25.3.0, 25.3.1, 26.0.0
Selected version is:  25.3.1
Selected AppCompat version is: 25.3.1
spawn: ./gradlew "clean" "-PcompileSdk=android-25" "-PtargetSdk=__APILEVEL__" "-PbuildToolsVersion=25.0.2" "-PsupportVersion=25.3.1" "-PgenerateTypings=false"

:config phase:  createDefaultIncludeFiles

:config phase:  addAarDependencies
	+adding dependency: /Users/c1ngular/Projects/TNSProject/sample/platforms/android/libs/aar/widgets-release.aar
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.

BUILD FAILED

Total time: 1.452 secs
Error: Command ./gradlew failed with exit code 1
    at ChildProcess.childProcess.on (/usr/local/lib/node_modules/nativescript/lib/common/child-process.js:112:36)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Processing node_modules failed. Error: Command ./gradlew failed with exit code 1

**Comment by NickIliev** [comment]
@c1ngular can you try resetting the newly created project and rebuild it again (remove **platforms** folder and execute `tns run adnroid` again)

**Comment by c1ngular** [comment]
@NickIliev already did that several times , no avail

**Comment by NickIliev** [comment]
@c1ngular the downloaded gradle versions in your dists folder should not matter (I have more than two downloaded versions) but you can still delete gradle-3.3-bin and try to rebuild. However,

Node.js 7.10.0 which is not the official LTS version but more like the beta version with all latest implementations. I would recommend using the LTS versions (6.10.3) but you should also be able to work with 7.10.0 (Current).

Another thing you can try is to update your Build tools to 25.0.3 (again 25.0.2 should be perfectly fine in the common case).

You can also try to build an already existing project like[ this one](https://github.com/NativeScript/nativescript-sdk-examples-ng) just to see if that results in the same case.

**Comment by NickIliev** [comment]
@c1ngular were you able to resolve your issue?

**Comment by c1ngular** [comment]
@NickIliev nope , tried to completely reinstall all needed components according to the {N} documents, same problem here ~

**Comment by NickIliev** [comment]
@c1ngular can you try to build and run some existing project for example [this one](https://github.com/NativeScript/nativescript-sdk-examples-ng) and send us the log trace
```
tns run android --log trace > log.txt
```

This will generate a file called log.txt in your root project directory (wait for the entire build and run process to pass as it won't show you the process in your terminal)

**Comment by c1ngular** [comment]
@NickIliev log trace of building this project:  https://github.com/NativeScript/nativescript-sdk-examples-ng
[log.txt](https://github.com/NativeScript/NativeScript/files/1046417/log.txt)

**Comment by NickIliev** [comment]
related to [https://github.com/NativeScript/nativescript-cli/pull/2837](https://github.com/NativeScript/nativescript-cli/pull/2837)

**Comment by NickIliev** [comment]
@c1ngular thank you for the log file. 

Based on the log the most probable cause for your issue is related to the SDK version installed on your machine. The log indicates that the __APILEVEL__ is not set with existing numeric version which may be caused by two reasons: either you have installed not supported SDK versions (e.g. installed SDK 26 preview version only) or there is no SDK version installed/set at all.

As a possible workaround, I would suggest installing SDK versions 25 and 23 and then trying to rebuild your project.
![sdkversions](https://cloud.githubusercontent.com/assets/18008302/26781581/f3b9073a-49f7-11e7-9a0a-310a5efe2df7.png)

**Comment by c1ngular** [comment]
@NickIliev thanks for helping ,  i have got SDK versions 25 and 23 installed , confirmed no white spaces in my path, still not working ~ 
it used to work for me , until i did some update/reinstall of components[softwares], maybe forced tns building process to terminate once or twice  ,  it is just broken for me , ever since ~  no matter how many times i freshly reinstall all need components[softwares], it is just not working for me anymore ~

i attached my example project(default hello world project), with android platform included , and a log.txt file as well , please take a look ! 

thanks again

**Comment by c1ngular** [comment]
@NickIliev  never mind , i formatted HD and reinstalled system , it is working now !
thanks again !

**Comment by c1ngular** [comment]
@NickIliev it happens again ,  i can ONLY build android project ONCE !

i have formatted HD and reinstalled OS **yesterday** , then i installed everything we need for nativescript cli , then i created the helloworld project , it builds and runs on my android device successfully .

**today** ,  i have tried to create and build a new project , but it failed to build android , then i went to the helloworld project i have created and builded successfully from yesterday , removed android platform , and tried to build and run it again , it fails too ~

still the same error message as before 
`:config phase:  addAarDependencies
        +adding dependency: /Users/s1ngular/Projects/TNS/ripple/platforms/android/libs/aar/widgets-release.aar
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'ripplewallet'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 53.588 secs
Processing node_modules failed. Error: Command ./gradlew failed with exit code 1`

**Comment by c1ngular** [comment]
@NickIliev  details of my dev environment : 
OS : Sierra 10.12.5
Node: v6.10.3
Java: 1.8.0_131
NPM : 5.0.3
Nativescript:3.0.3
Gradle: 3.3
Android SDK Platform: 25/23/22/21/19 [api level]
Android SDK Build Tools: 25.0.2, 26.0.0
Android SDK Platform Tools: 26.0.0
Android SDK Tool :26.0.2

**Comment by NickIliev** [comment]
@c1ngular I am suspecting the usage  of  `Android SDK Build Tools: 25.0.2, 26.0.0`
