### ISSUE TITLE
To create new views from a template "tns view add myNewView".

### ISSUE THREAD

**Issue by getsetbro** [NativeScript/NativeScript#427]
Id like to create new views from a template "tns view add myNewView".

**Comment by valentinstoychev** [comment]
I like the idea a lot - we can even have predefined page templates to choose from like
 - login screen
 - listview
 - about page
- more ...
and also to allow for custom creation of templates for specific use cases.

**Comment by getsetbro** [comment]
Another choice could be JS or TypeScript.

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#905
