### ISSUE TITLE
how to compress images  before upload in NS

### ISSUE THREAD

**Issue by giscafer** [NativeScript/NativeScript#4271]
the photo is more than 4M，i want to compress before upload，how to do?

**Comment by giscafer** [comment]
compress the ImageAsset or the ImageSource

**Comment by NickIliev** [comment]
Can you clarify what you mean with "before uploading in NS"?
If you are creating large images on the user device (e.g. using Camera) then you can control the size of the image. Or you can send the image as a base64 string. If you want to control the image size on download (e.g. when using some online API and the `src` property) then you can downsample the images with using decodeWidth and decodeHeight for Android (article [here](http://docs.nativescript.org/angular/ui/images-optimisations.html)).

As a side note, I would suggest to post similar questions in the community channels like [forum.nativescript.org](https://discourse.nativescript.org/) and SO where you can receive faster answers from the community members and in the same time we can keep this repo clean for issues, bugs and feature related threads.

**Comment by giscafer** [comment]
i select the photo form the album，the photo is more then 3M。i use the nativescript-background-http upload， it's slowly。so i want to compress the selected photos

**Comment by NickIliev** [comment]
@giscafer you can use the converting to base64 technique decided in the linked issue via ImageSource module and the method **_toBase64String_**

e.g.based on [this sample application](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/NativeScript/issue_4271/app/main-page.ts#L11-L14)
```
import { fromFileOrResource } from "image-source";

let img = fromFileOrResource("~/images/cosmos.jpg");
let baseString = img.toBase64String("jpeg");

console.log(baseString);
```

Currently, there are no compression plugins for NativeScript, but I would also recommend joining and posting your question in the community channels and especially the [forum.nativescript.org](https://discourse.nativescript.org/) where the communiti is very active and other possible solutions can be provided.

**Comment by himank1991** [comment]
did you guess got any plugin to compress image in nativescript angular ?

**Comment by pospospos2007** [comment]
no,it's so sad I have to say

**Comment by NickIliev** [comment]
@himank1991 @pospospos2007 the method `toBase64String` also has a quality parameter which can be used to compress large images. See[ this thread](https://discourse.nativescript.org/t/compressing-images-and-other-files-before-uploading-to-the-server/2888/2) for details.

**Comment by timleland** [comment]
Here is another [example on how to compress images](https://timleland.com/compress-and-upload-image-using-nativescript/)

**Comment by Rajdeo-Das** [comment]
`opneImagePicker() {
    var context = imagepicker.create({
      mode: "single"
    });

    context
      .authorize()
      .then(function () {
        return context.present();
      })
      .then((selection) => {
        console.log("Selection done:");

        ImageSourceModule.ImageSource.fromAsset(selection[0]).then((image: ImageSource) => {
          image = image.resize(100). // This does the compression and reduce the size.
          var b64 = image.toBase64String('jpeg', 0.5);   // This does not work always for me.

          const fileSize = b64.replace(/\=/g, '').length * 0.75;

          console.log("base64 ---------> ", b64)
          console.log('fileSize----------->', fileSize);
          if (fileSize >= 1000000) {
            console.log('File bigger then 1MB !', 'error')
            return;
          }

          const folder = knownFolders.currentApp().path;
          const fileName = "profile.jpeg";
          const fPath = path.join(folder, fileName);
          const saved = image.saveToFile(
            fPath,
            "jpeg",
            0.5
          );

          if (saved) {
            console.log('fPath----------->', fPath);
            this.profileService.updateUserProfileImage(fPath, this.userId);
          }
        });
      }).catch(function (e) {
        console.log(e);
      });

  }`
