### ISSUE TITLE
SearchBar is not displayed - Android API 24 

### ISSUE THREAD

**Issue by ADjenkov** [NativeScript/NativeScript#4272]
`<SearchBar>` Is not showing at all on Android >= 7.0 . I've tested on Emulator with 7.0 API 24, 7.1.1 API 25 and on a device with 7.0. I'll log an issue, but I'm writing you here because I'm pretty sure that this problem was occuring on my phone some months ago with {N} 2.5 + Android 7.0 .

Working as expected on lower Android versions.
PS: Testing with SearchBar inside the page not in the ActionBar

**Comment by NickIliev** [comment]
@ADjenkov please share the code that you are using for the XML page.

I have tested the SearchBar in both API25 and API24 and it works as expected on my side.[ Here is the used test application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4272).

![screen shot 2017-05-29 at 9 35 20 am](https://cloud.githubusercontent.com/assets/18008302/26538912/312d91a4-4452-11e7-8416-8e387be0212b.png)

**Comment by ADjenkov** [comment]
@NickIliev  After some more testing I've noticed that the <SearchBar> control does not init with default sizes. What I mean is that if the control is inside layout with `auto` size for example:

`<GridLayout rows="auto, *">
    <SearchBar row="0" id="searchBar" hint="Search" text="" clear="onClear"></SearchBar>
    <Label row="1" text="Test"></Label>
</GridLayout>`

The SearchBar is not displayed -> only the Label is visible. If i change the grid to `<GridLayout rows="*, *">` or hardcode a `height=50` on the `SearchBar` then it is visible.
Sorry for the initial misleading info, but I think that this is a problem too  because the `SearchBar` control is behaving differently from the other controls

**Comment by NickIliev** [comment]
@ADjenkov you are right - some of the controls like **ListView** needs to be initialized with size or the parents in which they are nested needs to have a size so they can be rendered as expected. These limitations are coming from the native design of the controls that lies behind ListView.

However, this should not be the case for **SearchBar** - I have modified [my application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4272) using your snippet you provided and the SearchBar is still visible for iOS (10.2) and Android (API25).

**Comment by ADjenkov** [comment]
@NickIliev  I've just tested again. It is ok on Android 6.0 API 23, but not visible in Android 7.0 API 24

![image](https://cloud.githubusercontent.com/assets/5860190/26548104/1bd9748e-447b-11e7-879c-a4e5587e9e88.png)
[search-bar-test-tsc.zip](https://github.com/NativeScript/NativeScript/files/1035691/search-bar-test-tsc.zip)

**Comment by NickIliev** [comment]
@ADjenkov I can confirm that indeed the SearchBar is not showing on API-24 if some size is not explicitly set (either for its container or for the SearchBar itself). Working as expected on API25 and all API levels before API23  We will need some additional time to investigate if this is not a specific behavior of [android.wdiget.SearchView ](https://developer.android.com/reference/android/widget/SearchView.html)for API-24 and will get bac at you on this issue.

App demonstrating the issue (only on API 24) [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4272).

**Comment by ADjenkov** [comment]
@NickIliev Thanks! Yes, I've already hardcoded id for my scenario.

Again, thanks for your time!

**Comment by ADjenkov** [comment]
Btw , on my phone Sony Xperia Compact with Android 7.0.0 I'm not able to display it with even when I'm setting hardcoded sizes (`height="50"`)

**Comment by SvetoslavTsenov** [comment]
The fix is already available in tns-core-modules@next and will also be released with tns-core-modules@3.1.0
