### ISSUE TITLE
ListView itemTap handler doesn't cleanup with livesync

### ISSUE THREAD

**Issue by jrz** [NativeScript/NativeScript#4277]
I have a ListView with items. the (itemTap)="tapInListView(args)"

```
tapInListView(args: ItemEventData) {
    var itemIndex = args.index;
    console.log(`Itemindex = ${itemIndex}`);
}
```

Everytime livesync syncs, I get one more console log. This is fixed when stopping the application / tns run.

If I change the log line into: `test = ${itemIndex}`, all lines will show "test". 
So it seems that the function gets refreshed, but the ListView has multiple handlers (same function).

**Comment by NickIliev** [comment]
@jrz Using NativeScript 3.0.1 and [this sample applicaiton](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4277) everything seems to work as expected with ListView and live-syncing.

One small note - the only difference in your code sample in the test applicaiton I am using is the way I am passing the event object. To capture the event object (in Angular apps), pass `$event` as a parameter in the event callback from the template:

```
(itemTap)="tapInListView($event)"
```

**Comment by jrz** [comment]
Interestingly, I cannot reproduce in both the testcase and my other project.
Please keep it open while I'm searching for it

**Comment by NickIliev** [comment]
@jiz no problem at all - let me know if there is a stable workflow to reproduce the case.

**Comment by NickIliev** [comment]
@jrz any updates on your test case project?
