### ISSUE TITLE
TextField: autocorrect doesn't work properly.

### ISSUE THREAD

**Issue by Abdumama** [NativeScript/NativeScript#4278]
### Tell us about the problem
If you use the property **_autocorrect_** to **_false_** in the widget **TextField** the autocorrection layout is always showed.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.0
- Cross-platform modules: 3.0.0

### Please tell us how to recreate the issue in as much detail as possible.
`<TextField hint="Test" autocorrect=false></TextField>`

or

`<TextField hint="Test" autocorrect="false"></TextField>`

**Comment by tsonevn** [comment]
Hi @Abdumama,
Thank you for reporting this issue.
I tested this scenario on my side and indeed at the moment setting autocorrect to false will not change the layout of the TextField Keyboard for Android. 
For further info about the problem and possible fix, you could keep track on the issue.
In the meantime, as a workaround, you could setup Input type on the component loaded event, which will change the layout as expected.
XML
```
 <TextField hint="test autocorrect" loaded="loadedtf" text="{{  }}" />
```

TypeScript
```
export function loadedtf(args){
    var tf:TextField = <TextField>args.object;
    if(isAndroid){
        tf.android.setInputType(524288);
    }
    
}
```

Bear in mind that `524288` is the value of `TYPE_TEXT_FLAG_NO_SUGGESTIONS`, more about the other options could be found [here](https://developer.android.com/reference/android/text/InputType.html#TYPE_TEXT_FLAG_NO_SUGGESTIONS).

**Comment by tsonevn** [comment]
Hi @Abdumama,
I discussed this issue with the NativeScript developer's team and we conclude that in this issue we are talking about a different feature.
The idea of the autocorrect is to underline the wrong word. Changing the layout of the keyboard depends on the `suggestion` functionality.
On that matter, the given above suggestion is the way that you could change the keyboard style in the needed way.
```
export function loadedtf(args){
    var tf:TextField = <TextField>args.object;
    if(isAndroid){
        tf.android.setInputType(tf.android.getInputType()|524288);
        console.dir(tf.android.getInputType());
    }
    
}
```

**Comment by Abdumama** [comment]
Ok, thanks.

**Comment by RoyiNamir** [comment]
@tsonevn  Why `<TextField>args.object;` and not `<TextField>args.view;`  ? Is there a difference ?

**Comment by tsonevn** [comment]
Hi @RoyiNamir,
[By design](https://docs.nativescript.org/api-reference/interfaces/_data_observable_.eventdata), the `object` property will return an instance to the element loaded event which you are listening. There is no `view` property returned from the loaded event. If you try using something like `<TextField>args.view`, the returned value will be undefined.

**Comment by RoyiNamir** [comment]
@tsonevn Hi.
So I guess I don't know the difference between those two : 

```
  onDoubleTap(args: GestureEventData) {
        console.log("DoubleTap!");
        console.log("Object that triggered the event: " + args.object); <---- ???
        console.log("View that triggered the event: " + args.view);
        console.log("Event name: " + args.eventName);
```
