### ISSUE TITLE
On iOS changing .css makes emulator app unresponsive

### ISSUE THREAD

**Issue by RobertGardner** [NativeScript/NativeScript#4280]
If I 'tns run ios' on Mac 10.12.5 with XCode 8.3.2 and change only a .css file, then the app in the emulator becomes unresponsive. I have to exit the app (using cmd-shift-H twice) and relaunch it. If I change a .ts or .html file then the app in the emulator relaunches and all is well.

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.1
- Cross-platform modules: 3.0.0
- Runtime(s): tns-ios
- Plugin(s): "nativescript-plugin-firebase": "^3.11.4" (though this doesn't seem relevant to this issue)

**Comment by tsonevn** [comment]
Hi @RobertGardner,

I reviewed this scenario, however, the livesync seems to work as expected while using the latest NativeScirpt. The steps that I follow are:
1. `tns create testApp --tsc`
2. `tns run testApp `
3. remove all styling setting in `app.css` and add following line:
```
Label{
color:green;
}
```
It would help if you provide some more info about the template, which is used and about the device or emulator.
In the meantime, you could verify, whether this issue will be reproduced on a clear project or it is something related to the existing one.

**Comment by dtopuzov** [comment]
Hi @RobertGardner I can confirm that we had such an issue, but it should be resolved if you update both CLI and tns-core-modules.

Latest CLI: 3.0.3
Latest Modules: 3.0.1

**Comment by RobertGardner** [comment]
Upgrading to 3.0.3 and 3.0.1 fixed this. Thank you!
