### ISSUE TITLE
font-weight property not working

### ISSUE THREAD

**Issue by Jonatthu** [NativeScript/NativeScript#4282]
font-weight property is not working, only tested on nativescript 3.0.1 and iOS,
I'm using it within angular if that helps

**Comment by tsonevn** [comment]
Hi @Jonatthu,
I tested this case on my side, however, was unable to reproduce an issue, while using `font-weight` CSS property. 
Could you review the attached project and make the needed changes, which will allow us to recreate the problem?
Also, it would help if you could provide some more info about your environment(CLI, node, tns-core-modules versions).

![screen shot 2017-05-29 at 9 44 05 am](https://cloud.githubusercontent.com/assets/17448734/26539116/6bacc57e-4453-11e7-9acc-ee40936773cf.png)
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1035020/Archive.zip)

**Comment by Jonatthu** [comment]
I just ran your example project and is working

but mine not

this is my package.json
```

{
  "name": "TyFitt",
  "version": "1.0.0",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "hagele.jonatthu.test",
    "tns-android": {
      "version": "3.0.0"
    },
    "tns-ios": {
      "version": "3.0.0"
    }
  },
  "dependencies": {
    "@angular/common": "^4.1.3",
    "@angular/compiler": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/forms": "^4.1.3",
    "@angular/http": "^4.1.3",
    "@angular/platform-browser": "^4.1.3",
    "@angular/platform-browser-dynamic": "^4.1.3",
    "@angular/router": "^4.1.3",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "nativescript-angular": "^3.0.0",
    "nativescript-carousel": "^2.4.2",
    "nativescript-ngx-fonticon": "^2.2.0",
    "nativescript-theme-core": "^1.0.4",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.4.0",
    "tns-core-modules": "^3.0.1",
    "zone.js": "^0.8.11"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^4.1.3",
    "@types/lodash": "^4.14.64",
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "^0.26.1",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-sass": "^1.1.1",
    "nativescript-dev-typescript": "^0.4.0",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.0.2",
    "tns-platform-declarations": "^3.0.1",
    "typescript": "~2.2.1"
  }
}

```

**Comment by tsonevn** [comment]
Hi @Jonatthu,
Thank you for attaching the `package.json` file.
I reviewed that case while using NativeScirpt Angular 2 template, however, `font-weight` property seems to work as expected as well as in pure NativeScirpt project.

I am attaching again my sample project. Regarding that, it would help if you could give us sample project or at least some code snippet, which will help me to recreate the problem.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1037679/Archive.zip)

**Comment by Jonatthu** [comment]
Was an user issue (by me) sorry about that, seems like when you have a global class with font-weight normal this can not be overridden, maybe we can add support  for !important declaration in CSS, but this is closed.

Thanks @tsonevn
