### ISSUE TITLE
WebView - a broken link referenced to the API 

### ISSUE THREAD

**Issue by eladcandroid** [NativeScript/NativeScript#4284]
Here: https://docs.nativescript.org/angular/code-samples/ui/web-view.html

When clicking on "WebView Class" to show the API reference for the control, the link is broken.

**Comment by tsonevn** [comment]
Hi @eladcandroid,
Thank you for reporting this issue, 
We will research, what is causing this problem and will fix it.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/docs#789
