### ISSUE TITLE
Create a project with template (Typescript + Angular) without .js files

### ISSUE THREAD

**Issue by gtzinos** [NativeScript/NativeScript#4285]
Hello,
I am starting to learning your great framework. I created my first app with --ng (Angular, typescript template) but when i executed tns debug android it created for me and files .js (like main.js and more). Why am i need them ? Is it possible to have a more clear project (just angular and typescript as the official angular) ?

**Comment by tsonevn** [comment]
HI @gtzinos,
Thank you for your interest in NativeScript.
Regarding the question, generating JavaScript files is something expected. This is the way that TypeScript works. All `.ts` files will be transpiled to its corresponding `.js` file. TypeScript just gives you some extras, like IntelliSense. you could read more about it [here](http://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html).


About the other question, you could review this thread [here](https://stackoverflow.com/questions/12678716/transforming-typescript-into-javascript), where has been shown, how to hide JavaScrip files, while using VSCode.

For more `Question`, please use our NativeScript forum [here](https://discourse.nativescript.org/).

**Comment by gtzinos** [comment]
Sorry but i have another question, i use typescript for a year, i know that it generates these files, but it generates them compiled, in your framework i just have the code as i did it but translated to javascript (without compile).

**Comment by tsonevn** [comment]
Hi @gtzinos,
Excuse me for the misunderstanding,
This is something expected and the NativeScirpt will generate the typescript files compiled inside the project. This is the way, how the framework works.
Let me know if I could assist you further
