### ISSUE TITLE
Margin value with TextWrap overlapping problem

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#4287]
When using textWrap on a longer text that will wrap on several lines the margins are not properly calculated for iOS. Works as expected on Android.

Test application [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4287)

e.g. textWrap for long text with margin-bottom: 60 (this)
```
<Button text="This a test of a wrapping button [CENTER]" textWrap="true" style="text-align:center;width:100;margin-bottom:20;" />
<Button text="This a test of a wrapping button [RIGHT]" textWrap="true" style="text-align:right;width:100;margin-bottom:20;" />
<Button text="This a test of a wrapping button [LEFT]" textWrap="true" style="text-align:left;width:100;margin-bottom:20;" />
<Button text="&#xf8ff; This a test of a wrapping button [CENTER ICON]" textWrap="true" style="text-align:center;width:100;margin-bottom:20;" />
```

The same wth larger margin will look ok (if the margin is big enough to handle the wrapping of the ling text)
e.g. example looks as expected with larger margin
```
<Button text="This a test of a wrapping button [CENTER]" textWrap="true" style="text-align:center;width:100;margin-bottom:60;" />
<Button text="This a test of a wrapping button [RIGHT]" textWrap="true" style="text-align:right;width:100;margin-bottom:60;" />
<Button text="This a test of a wrapping button [LEFT]" textWrap="true" style="text-align:left;width:100;margin-bottom:60;" />
<Button text="&#xf8ff; This a test of a wrapping button [CENTER ICON]" textWrap="true" style="text-align:center;width:100;margin-bottom:60;" />
```

Related to [https://github.com/NativeScript/NativeScript/issues/4266#issuecomment-304355063](https://github.com/NativeScript/NativeScript/issues/4266#issuecomment-304355063)

**Comment by SvetoslavTsenov** [comment]
The fix is already available in tns-core-modules@next.
