### ISSUE TITLE
[Build] Error : Execution failed for task ‘:mergeF0F1DebugResources

### ISSUE THREAD

**Issue by sujanmah062** [NativeScript/NativeScript#4289]
Hi, all

i using nativescript version "3.0.1" with angular . i had change image on "drawable" file. I get error while run "tns run android".

> Error: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException:
> :mergeF0F1DebugResources FAILED
> 
> FAILURE: Build failed with an exception.
> 
> What went wrong:
> Execution failed for task ':mergeF0F1DebugResources'.
> 
> Error: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException:
> Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by NickIliev** [comment]
@sujanmah062 to resolve this reset your **platforms** folders and rebuild the project.
```
tns platform remove android
tns platform add android
tns run android
```
