### ISSUE TITLE
Problem with the Listview items height on android devices under android 7

### ISSUE THREAD

**Issue by vegeorgi** [NativeScript/NativeScript#4294]
Hi,

I noticed something with ListView items height on android devices under android 7. On initial load the height is not set properly. After redirect, it is fixed.  - [video](https://www.screencast.com/t/Jga74sqQCDY)

The app that i`m testing is angular app with Light theme.
I`m testing with Google nexus 6 - 6.0.0 - API 23 - it is broken, but on Google nexus 5x - 7.1.0 - API 25, it is OK

**Comment by tsonevn** [comment]
Hi @vegeorgi,
I tested this case on my side, while following the given description, however, was unable to reproduce this problem. 
I am attaching the sample project, which I used for testing. Could you review it and verify, if I am missing something? It would also help if you could provide some info about NativeScript version, that it is used.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1041342/Archive.zip)
![screencast 2017-05-31 at 2 41 57 pm](https://cloud.githubusercontent.com/assets/17448734/26630638/456c8020-4610-11e7-8144-ddcbf3de3a8d.gif)

**Comment by tsonevn** [comment]
Hi @vegeorgi,
I was able to reproduce this behavior on my side with the applying height for the ListView items, Indeed this issue is a valid problem only for Android API level 23. I am attaching the project.

In the meantime, you could setup specific height for the main container inside the ListView template. for example:
```
<StackLayout class="sidedrawer sidedrawer-left">
    <GridLayout class="sidedrawer-content">
        <ListView [items]="items" >
            <ng-template let-item="item" let-i="index" let-odd="odd" let-even="even">
                <GridLayout  backgroundColor="red" rows="100" columns="auto, *"
                    class="sidedrawer-list-item" >
                    <Label row="0" col="0" [text]="item.title" class=" p-l-15 p-r-5"></Label>
                    <Label row="0" col="1" [text]="item.title" textWrap="true"></Label>
                </GridLayout>
            </ng-template>
        </ListView>
    </GridLayout>
</StackLayout>

```
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1044028/Archive.zip)

**Comment by vegeorgi** [comment]
Hi @tsonevn,

I tried the solution that you provide. It looks like it fixes the problem :) It will be nice if it is not necessary to set item height, but for now it is ok :)

Thank you for you help

**Comment by tsonevn** [comment]
The issue is no longer reproducible with NativeScript 4.1.
