### ISSUE TITLE
android.webkit.WebChromeClient.extend

### ISSUE THREAD

**Issue by Tyre88** [NativeScript/NativeScript#4297]
Hello, i am trying to extend the WebChromeClient and override the function: onShowFileChooser but i am getting this error when i build the project:

> \platforms\android\src\main\java\com\tns\gen\android\webkit\WebChromeClient_fPage_Main_main_page_l182_c72__.java:3: error: '{'
>  expected

> \platforms\android\src\main\java\com\tns\gen\android\webkit\WebChromeClient_fPage_Main_main_page_l182_c72__.java:4: error: <id
> entifier> expected
>         public WebChromeClient_fPage_Main_main.page_l182_c72__(){

this is how i am doing it: 

```
ngAfterViewInit() {
let myWebChromeClient = android.webkit.WebChromeClient.extend({
                    onShowFileChooser: function () {
                        alert("Test");
                        return true;
                    }
                });
this.wv.android.setWebChromeClient(new myWebChromeClient());
}
```

But if i comment out the code and do platform remove and then add again and do tns run android it works and then when the live sync is active i activate the code again then the code works. So when i am debugging the app i can get the code to run but i can't build the app with the code active and that means i can't publish the app with the code active.

-This is for the android platform.

**Comment by NickIliev** [comment]
@Tyre88 to resolve this issue extend your web view using the NativeScript event and not the ngAfterInit lifecycle from Angular. You can use **loaded** event for your web view like this:
```
onWebViewLoaded(args) {
    var webview = args.object;
    let myWebChromeClient = android.webkit.WebChromeClient.extend({
                                onShowFileChooser: function () {
                                    alert("Test");
                                    return true;
                                }
                            });
    webview.android.setWebChromeClient(myWebChromeClient);
}
```

and in your HTML file
```
<WebView (loaded)="onWebViewLoaded($event)"></WebView>
```

**Comment by Tyre88** [comment]
Hello, 

After moving the code to the Loaded event it still doesn't work, i am getting this error: 

> \platforms\android\src\main\java\com\tns\gen\android\webkit\WebChromeClient_fPage_Main_main_page_l181_c64__.java:3: error: '{' expected
> public class WebChromeClient_fPage_Main_main.page_l181_c64__ extends android.webkit.WebChromeClient implements com.tns.NativeScriptHashCodeProvider {

> \platforms\android\src\main\java\com\tns\gen\android\webkit\WebChromeClient_fPage_Main_main_page_l181_c64__.java:4: error: <identifier> expected
>         public WebChromeClient_fPage_Main_main.page_l181_c64__(){
>                                                               ^
> 2 errors


> * What went wrong:
> Execution failed for task ':compileF0F1F2DebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.


TNS version: 3.0.0

**Comment by NickIliev** [comment]
@Tyre88 I was able to reproduce and the issue is related to creating an anonymous class in an Angular application which might le4ad to conflict (as in your case) To resolve this case, either assign your own custom name for the extended class or use [this solution](https://github.com/NativeScript/NativeScript/issues/4166#issuecomment-302065956) (**recommended approach**)

Here is how to assisgn your own name to the extended class:

```
let myWebChromeClient = android.webkit.WebChromeClient.extend("a.b.testClassName", {
    onShowFileChooser: () => {
        console.log("Test");
    }
});
```

**Comment by Tyre88** [comment]
Thanks this worked great!

**Comment by mahavirvataliya** [comment]
How can I set path in that for return after choosing file
