### ISSUE TITLE
App chashed when conect/disconect a bluetooth barcode scanner on android

### ISSUE THREAD

**Issue by leoelcoder** [NativeScript/NativeScript#4298]
Hey everyone!! 
I'm using a bluetooh barcode scanner in my android app 
but I'm getting the following exception:

**Error: could not find a page for fragment1[0]**

This happend when turn on/turn off the barcode scanner
after navigate to other view and set `clearHistory: true` in the`navigationEntry`

When turn on /turn off the barcode scanner and the barcode scanner connect or disconect to the phone,  the `launchEvent` and `resumeEvent` were called also `suspendEvent`

is this a bug?
is there a way to detect when a bluetooth device is connected?

##### tns info
nativescript   2.5.3 
tns-core-modules │ 2.5.2 
tns-android      │ 3.0.1

**Comment by NickIliev** [comment]
@leoelcoder are you using a plugin or code of yours to work with the Bluetooth scanner? 
Please provide sample project or snippet that demonstrates and fully reproduces your issue.

**Comment by leoelcoder** [comment]
@NickIliev No, I'm not using any plugin or code,  the android device detects the scanner as keyboard. if I scan a codebar, and my app has a TextField active, automatically fills the TextField

**Comment by NickIliev** [comment]
@leoelcoder try using [this plugin](https://www.npmjs.com/package/nativescript-barcodescanner) to resolve your issue.

**Comment by NathanaelA** [comment]
@NickIliev - I think you misunderstand what his problem is.   He doesn't need a barcode scanner plugin, what he wants to know is why a **physical** device (which acts like a physical keyboard) connected to the Android will cause NativeScript to crash.  Adding the NS-BarCode plugin won't help since the NS-BarCode plugin is for using the camera to read barcodes.

**Comment by NickIliev** [comment]
@NathanaelA tThank you for the clarification! 
@leoelcoder we will try our best to test this behavior with a real barcode device and I will post back here when I have more conclusive results.

**Comment by leoelcoder** [comment]
Thanks! and I'll be waiting for your results.

**Comment by NickIliev** [comment]
@leoelcoder can you clarify what is the specific physical device you are using.

**Comment by leoelcoder** [comment]
@NickIliev I'm using a generic scanner like [this one ](https://uedata.amazon.com/Hundred-Eighty%C2%AE-Handheld-Bluetooth-Wireless/dp/B00MQN65GM ). Let me check if exists an user guide or technical manual. if I success I'll notify you
