### ISSUE TITLE
app.platform.css should compliment app.css and not replace it

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#43]
_From @MiroValchev on April 23, 2015 14:8_

From my tests, if platform specific versions of app.css are added, the original file is completely ignored. Shouldn't they just compliment it by overriding some styles?

_Copied from original issue: NativeScript/cross-platform-modules#314_

**Comment by enchev** [comment]
_From @sfeather on April 23, 2015 19:40_

Agreed, @MiroValchev . The two should be merged with platform specific styles being added to (and overwriting conflicting) app level styles.  This merging needs to take place at the property level.

app.css
```
Button {
  font-size: 16;
  color: black;
}
```

app.android.css
```
Button {
  font-size: 20;
  horizontal-align: center;
}
```

The resultant style applied should be:
```
Button {
  font-size: 20;
  horizontal-align: center;
  color: black;
}
```

**Comment by enchev** [comment]
Hey folks,

You are right. Currently our CLI will remove "platform" part from the file name and will replace app.css if any. We plan to support [CSS import](https://developer.mozilla.org/en/docs/Web/CSS/@import) for common and platform specific declarations.

**Comment by bundyo** [comment]
In my opinion @import will help, but app.css and platform CSS merger is logically expected and should be supported in addition to @import.

**Comment by bundyo** [comment]
Closing #116 as duplicate. Discussion should continue here.

**Comment by Klors** [comment]
I would have said that either replacement of the file or merger of the content could be logically expected and that documentation would ultimately decide what I expect.

However, of the two options, it's immediately obvious what would happen with a replace. Whereas there are many subtleties that could happen during a merger that would potentially need some extra declaration syntax to control. This in my opinion makes merger the less desirable choice.

CSS already cascades for its merge, that should be the preferred method and import should help enough with that.

**Comment by bundyo** [comment]
By merger I meant common app.css gets concatenated with the platform CSS, with the common one being first. No extra declaration of any kind needed.

**Comment by Klors** [comment]
Concatenation would certainly be as predictable.

I think @import gives you more control and anyone coming from Cordova/PhoneGap would be expecting the files to be replaced?

**Comment by RangerMauve** [comment]
The JS doesn't behave like concatenation, though, does it? I'm pretty sure if you wan to reuse some code between platforms you have to `require()` the JS code that's shared. This would be paralleled better by the `@import` calls in CSS.

**Comment by enchev** [comment]
Hey folks,

We believe that using @import is much better and predictable and I'm closing this.

Thanks

**Comment by davehibshman** [comment]
Can someone show an example of using @import on app.css files?  I would think my platform specific app.ios|android.css would import general app.css, but I suspect due to renaming it would just end up including itself.
