### ISSUE TITLE
Getting an error after installing nativescript using windows msi

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#4301]
tns create testapp --ng

Unexpected token   in JSON at position 0
Failed to display command help SyntaxError: Unexpected token   in JSON at positi
on 0
    at Object.parse (native)
    at FileSystem.readJson (C:\Users\Dhana\AppData\Roaming\npm\node_modules\nati
vescript\lib\common\file-system.js:167:25)
    at UserSettingsService.<anonymous> (C:\Users\Dhana\AppData\Roaming\npm\node_
modules\nativescript\lib\common\services\user-settings-service.js:55:50)
    at next (native)
    at C:\Users\Dhana\AppData\Roaming\npm\node_modules\nativescript\lib\common\s
ervices\user-settings-service.js:7:65
    at __awaiter (C:\Users\Dhana\AppData\Roaming\npm\node_modules\nativescript\l
ib\common\services\user-settings-service.js:3:12)
    at UserSettingsService.loadUserSettingsFile (C:\Users\Dhana\AppData\Roaming\
npm\node_modules\nativescript\lib\common\services\user-settings-service.js:50:16
)
    at UserSettingsService.<anonymous> (C:\Users\Dhana\AppData\Roaming\npm\node_
modules\nativescript\lib\common\services\user-settings-service.js:19:24)
    at next (native)
    at C:\Users\Dhana\AppData\Roaming\npm\node_modules\nativescript\lib\common\s
ervices\user-settings-service.js:7:65

**Comment by NickIliev** [comment]
@dhanalakshmitawwacan you please  try the solution suggested [here](https://github.com/NativeScript/nativescript-cli/issues/2321#issuecomment-303760229)

Closing as duplicate to [https://github.com/NativeScript/nativescript-cli/issues/2321#issuecomment-303760229](https://github.com/NativeScript/nativescript-cli/issues/2321#issuecomment-303760229)

**Comment by dhanalakshmitawwa** [comment]
Thank you for reply

**Comment by NickIliev** [comment]
@dhanalakshmitawwa no problem - let me know if you have resolved your issue

**Comment by dhanalakshmitawwa** [comment]
Thank you, the problem has been rectified.

**Comment by ChirantanPatel** [comment]
thank you very much @dhanalakshmitawwa  .
I also geting same here and solve it.
