### ISSUE TITLE
Component output in Nativescript without Angular

### ISSUE THREAD

**Issue by thanhphongdo** [NativeScript/NativeScript#4304]
Hi. I use nativescript without Angular. In my project, I custom a component and I want to binding event to parent page to change parent model same as output in Angular. I can access to bindingContext in parent page and change data model but it not binding in UI.

**Comment by NickIliev** [comment]
@thanhphongdo please post-structural type question in the community channels like [forum.nativescript.org](https://discourse.nativescript.org/) or SO, so we can keep the repo for posting issues, bugs, and feature requests.

As a side note, the passing of a context within the modal page and its parent is documented [here](https://docs.nativescript.org/core-concepts/navigation#example-14--receive-data-from-the-modal-page) but if your scenario is different please provide a code snippet or sample app demonstrating what you have done so far.
