### ISSUE TITLE
tns run ios fails in a real device

### ISSUE THREAD

**Issue by Juanjofp** [NativeScript/NativeScript#4306]
Hi,

I can run my app on my ios simulator but when i try to run on a ios device it fails whe run:

tns run ios --release

CompileAssetCatalog build/device/gamificationmobile.app gamificationmobile/Resources/Assets.xcassets
    cd /Users/juanjo/Projects/GamificationPlatform/gamification-mobile/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/juanjo/.nvm/versions/node/v6.9.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/juanjo/Library/Android/sdk/tools:/Users/juanjo/Library/Android/sdk/platform-tools:/Users/juanjo/.rvm/bin"
    /Applications/Xcode.app/Contents/Developer/usr/bin/actool --output-format human-readable-text --notices --warnings --export-dependency-info /Users/juanjo/Library/Developer/Xcode/DerivedData/gamificationmobile-cnalxyszbwthfmgmmxseyyanpdhp/Build/Intermediates/gamificationmobile.build/Release-iphoneos/gamificationmobile.build/assetcatalog_dependencies --output-partial-info-plist /Users/juanjo/Library/Developer/Xcode/DerivedData/gamificationmobile-cnalxyszbwthfmgmmxseyyanpdhp/Build/Intermediates/gamificationmobile.build/Release-iphoneos/gamificationmobile.build/assetcatalog_generated_info.plist --app-icon AppIcon --launch-image LaunchImage --compress-pngs --enable-on-demand-resources YES --sticker-pack-identifier-prefix .sticker-pack. --target-device iphone --target-device ipad --minimum-deployment-target 8.0 --platform iphoneos --product-type com.apple.product-type.application --compile /Users/juanjo/Projects/GamificationPlatform/gamification-mobile/platforms/ios/build/device/gamificationmobile.app /Users/juanjo/Projects/GamificationPlatform/gamification-mobile/platforms/ios/gamificationmobile/Resources/Assets.xcassets

** BUILD FAILED **

The following build commands failed:
	CpResource gamificationmobile/app build/device/gamificationmobile.app/app
(1 failure)
Multiple errors were thrown:
Command xcodebuild failed with exit code 65

And when I run:
tns run ios

2017-06-02 15:34:53.466 xcodebuild[69222:1203210] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/sl/ys83fx1s2wq4263h8h8wd6qm0000gn/T/gamificationmobile_2017-06-02_15-34-53.465.xcdistributionlogs'.
1.2.840.113635.100.1.61
2017-06-02 15:34:55.447 xcodebuild[69222:1203210] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-12153/DVTFoundation/DeveloperStructure/DVTPlatformFamily.m:192
Details:  Error Domain=DVTFoundationErrorDomain Code=-1 "Couldn't determine platform family for Bolts." UserInfo={NSFilePath=/Users/juanjo/Projects/GamificationPlatform/gamification-mobile/platforms/ios/build/archive/gamificationmobile.xcarchive/Products/Applications/gamificationmobile.app/app/tns_modules/nativescript-facebook-login/Demo/demo/platforms/ios/build/device/Bolts.framework.dSYM/Contents/Resources/DWARF/Bolts, NSLocalizedDescription=Couldn't determine platform family for Bolts., NSLocalizedRecoverySuggestion=None of the available platform families (iOS, macOS, tvOS, and watchOS) matched an LC_VERSION_MIN load command.}
Object:   <NSBundle>
Method:   +dvt_platformFamilyForBundleAtPath:error:
Thread:   <NSThread: 0x7fde7e415b30>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2017-06-02 15:34:55.447 xcodebuild[69222:1203210] [MT] IDEDistribution: Step failed: <IDEDistributionSummaryStep: 0x7fde85d3bf90>: Error Domain=DVTFoundationNSBundleAdditionsErrorDomain Code=1 "Couldn't find platform family in Info.plist CFBundleSupportedPlatforms or Mach-O LC_VERSION_MIN for Bolts" UserInfo={NSLocalizedDescription=Couldn't find platform family in Info.plist CFBundleSupportedPlatforms or Mach-O LC_VERSION_MIN for Bolts}
error: exportArchive: Couldn't find platform family in Info.plist CFBundleSupportedPlatforms or Mach-O LC_VERSION_MIN for Bolts

Error Domain=DVTFoundationNSBundleAdditionsErrorDomain Code=1 "Couldn't find platform family in Info.plist CFBundleSupportedPlatforms or Mach-O LC_VERSION_MIN for Bolts" UserInfo={NSLocalizedDescription=Couldn't find platform family in Info.plist CFBundleSupportedPlatforms or Mach-O LC_VERSION_MIN for Bolts}

** EXPORT FAILED **

Multiple errors were thrown:
Command xcodebuild failed with exit code 70

I'm using tns 3.0.1 and xcode 8.3.2

I appreciate any help!

Thanks in advance!

**Comment by dtopuzov** [comment]
Hi @Juanjofp 

This log looks stage:
```
UserInfo={NSFilePath=/Users/juanjo/Projects/GamificationPlatform/gamification-mobile/platforms/ios/build/archive/gamificationmobile.xcarchive/Products/Applications/gamificationmobile.app/app/tns_modules/nativescript-facebook-login/Demo/demo/platforms/ios/build/device/Bolts.framework.dSYM/Contents/Resources/DWARF/Bolts, NSLocalizedDescription=Couldn't determine platform family for Bolts., 
```

From what I see you use `nativescript-facebook-login` plugin and the demo app of the plugin gets inside your app, which is a problem for sure. Most likely the same problem cause Xcode build fail you encounter.

Can you please post package.json of you application?

**Comment by dtopuzov** [comment]
Update:

Latest version of `nativescript-facebook-login` package in npm include demo inside the plugin.
May be we should contact @AntonioCuevaUrraco and let him know.

**Comment by AntonioCuevaUrraco** [comment]
Thanks guys, should be fix on 1.0.1

**Comment by NickIliev** [comment]
@Juanjofp version 1.0.1 of [nativescript-facebook-login](https://www.npmjs.com/package/nativescript-facebook-login) is now live - please let us know is updating the plugin version and rebuild your application has resolved the issue for you.

**Comment by Juanjofp** [comment]
@NickIliev @AntonioCuevaUrraco 
Thank you very much, I'll try it right now.

**Comment by Juanjofp** [comment]
That was the problem, once updated to version 1.0.1 of the plugin everything works correctly. Many thanks to all @dtopuzov @AntonioCuevaUrraco @NickIliev
