### ISSUE TITLE
TNS Device command fails to find phone

### ISSUE THREAD

**Issue by mast3rd3mon** [NativeScript/NativeScript#4307]
### Tell us about the problem
I've recently got myself an android phone, it runs android 7.0. I have enabled developer options and followed 3 guides to do so to make sure I'm not missing anything. Despite this, `tns device` still fails to find my phone. This is the case on 2 pc's both running windows 8 both with Nativescript installed.

### Which platform(s) does your issue occur on?
Android

I am unable to find any solution to this. I may have missed something in the developer options but I'm not sure.

### UPDATE
I've just tried with an android 6.0 device and the same occurs, file explorer see's the phone but `tns device` doesn't seem to be able to find the phone

**Comment by sudhanshu-15** [comment]
Can you check if USB debugging is enabled in the developer options?
![screenshot_20170602-131042](https://cloud.githubusercontent.com/assets/883233/26736884/dcdf7972-4795-11e7-93f5-4046cb9015a6.png)

**Comment by mast3rd3mon** [comment]
Yep, its enabled on both devices

**Comment by dtopuzov** [comment]
Hi @mast3rd3mon

Can you verify Android tools can find the device:
Windows: `%ANDROID_HOME%\platform-tools\adb devices`
macOS or Linux: `$ANDROID_HOME\platform-tools\adb devices`

**Comment by mast3rd3mon** [comment]
`%ANDROID_HOME%\platform-tools\adb devices` cant find the device, however, if i plug in a phone i use to use for developing it can, both phones run android 7.0, both dev unlocked and both with usb debugging

**Comment by dtopuzov** [comment]
If `adb` can't find your phone or show it as unauthorized then the problem is with Android tooling itself.
For some Android devices you need to install drivers to get them working with `adb`.
Please search for Android USB drivers for your phone.

**Comment by mast3rd3mon** [comment]
Why do i not have this issue with one phone but i do with others though? i never installed drivers for the phone that works currently?

**Comment by mast3rd3mon** [comment]
More so, i have just installed the driver for my phone from the manufacturers website and the problem persists.

**Comment by mast3rd3mon** [comment]
So installing the `Android Composite ADB Interface' seemed to do the trick for one phone but thats the phone im gonna be using
