### ISSUE TITLE
Unable to build and deploy app to iTunes: Unable to connect to iTunes Connect

### ISSUE THREAD

**Issue by briandilley** [NativeScript/NativeScript#4310]
`    /usr/bin/touch -c /Users/distiller/Library/Developer/Xcode/DerivedData/quickridensmobile-bnzhogcsicpkjudhwfepmetihxvs/Build/Intermediates/ArchiveIntermediates/quickridensmobile/BuildProductsPath/Release-iphoneos/quickridensmobile.app.dSYM

** ARCHIVE SUCCEEDED **

Archive at: /Users/distiller/quickride-ns-mobile/platforms/ios/build/archive/quickridensmobile.xcarchive
2017-06-03 15:36:48.606 xcodebuild[17633:31256] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/jm/fw86rxds0xn69sk40d18y69m0000gp/T/quickridensmobile_2017-06-03_15-36-48.605.xcdistributionlogs'.
Exported quickridensmobile.xcarchive to: /Users/distiller/quickride-ns-mobile/platforms/ios/build/archive
** EXPORT SUCCEEDED **

Export at: /Users/distiller/quickride-ns-mobile/platforms/ios/build/archive/quickridensmobile.ipa
Unable to connect to iTunes Connect
An error occurred while processing the json request. (1268)`

**Comment by dtopuzov** [comment]
This issue was moved to NativeScript/nativescript-cli#2874
