### ISSUE TITLE
tns run Relaunches app every time I make a css change

### ISSUE THREAD

**Issue by thomaspaniagua** [NativeScript/NativeScript#4312]
Hey, I'm using Nativescript CLI 3.0.3

I recall in previous versions of Nativescript, when running the app on a device with livesync, the app would only completely relaunch when a change in the logic (Typescript or Javascript) was made, but when css or HTML was changed there would be a hot reload without the app closing and reopening. That is not the case anymore as the app relaunches whenever I make changes in CSS and HTML instead of Hot Reloading, how can I fix this?

**Comment by mast3rd3mon** [comment]
As far as i know, this is supposed to happen, the app reloads on change of js, ts, html and css.

**Comment by dtopuzov** [comment]
Hi @thomaspaniagua what kind of app you develop - Angular or vanilla JS/TS?
