### ISSUE TITLE
TextView Support For maxLines and minLines

### ISSUE THREAD

**Issue by Ericky14** [NativeScript/NativeScript#4315]
Does TextView have support for ```minLines``` and ```maxLines``` attributes? This would be a really useful feature for multi-line text.

**Comment by NickIliev** [comment]
Hey @Ericky14 you can implement your own logic for creating maxLines / minLines rules for your TextView.
nativeScript allows you to work directly with the native APIs (Android and iOS) so you can extend the logic just as you would do in a native project. 
Behind TextView stands [android.widget.EditText](https://developer.android.com/reference/android/widget/EditText.html) for Android and [UITextView ](https://developer.apple.com/documentation/uikit/uitextview) for iOS so tayht said we ca use some antive techniques to limit the number of lines.
e.g.
```
let tv = <TextView>page.getViewById("tv");
tv.text = "sample text";

if (isAndroid) {
    let tvAndriod = tv.android;
    tvAndriod.inputType = "text";
    tvAndriod.maxLines = "3";
} else if (isIOS) {
    tv.ios.textContainer.maximumNumberOfLines = 3;
    tv.ios.textContainer.lineBreakMode = NSLineBreakByTruncatingTail;
}

tv.on("textChange", () => {
    if (isAndroid) {
        if (tv.android.getLayout().getLineCount() > 3) {
            tv.android.getText().delete(tv.android.getText().length() - 1, tv.android.getText().length());
        }
    }
})
```
Demonstration project can be found [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4315).

Thank you for your feature request - as a side note, I want to mention that NativeScript is open-source and everyone can become a contributor to the project. If you are interested in this option and you have a tested solution you can go through our contributing guide [here](https://www.nativescript.org/contribute).

**Comment by bhavincb** [comment]
hey @NickIliev ,i would like to implement this to nativescript. but i have some doubts. where can i address them?

**Comment by NickIliev** [comment]
@bhavincb[ this is what you need to create a PR](https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#pr) - there is also a code [convention guide](https://github.com/NativeScript/NativeScript/blob/master/CodingConvention.md) included and [development workflow](https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md). Create your PR with the codebase and test and the PR will be reviewed and if needed there will be requests for changes.

Of course, the best practice would be to discuss the possible code feature or changes here in this very same issue.

**Comment by bhavincb** [comment]
@NickIliev, i want to add `maxLines` for android we can directly implement it in `TextBase` because it uses `android.widget.TextView`. but for ios TextBase uses `UITextField | UITextView | UILabel | UIButton` out of which `UITextField` doesn't support more than one line.
so my issue is where to write logic. is there any common approach available. or should i implement it in  `TextView, Label and Button` separately.

**Comment by LeoDupont** [comment]
@bhavincb, @NickIliev, do you have any news about this feature?

**Comment by bhavincb** [comment]
@LeoDupont  for now you can use workaround provided by Nichlliev.

**Comment by virtualbjorn** [comment]
Is there any workaround for having a scrollable textview after a certain number of lines?
I implemented @NickIliev workaround and it no longer accepts any input after reaching the maximum number of lines.

And right now, max-height is not yet implemented.
