### ISSUE TITLE
Question: Is there a downside of omitting Page.actionBar, ActionBar.actionItems and ActionItem.actionView?

### ISSUE THREAD

**Issue by sserdyuk** [NativeScript/NativeScript#4324]
It seems that the schema demands all these extra elements in the XML, but the views work fine without them. Needless to say, I prefer terse code, and 8 lines is better than 13. Is there any downside in omitting these elements altogether?

```
<Page class="page">
  <Page.actionBar>
    <ActionBar class="action-bar" title="My App">
      <ActionBar.actionItems>
        <ActionItem>
          <ActionItem.actionView>
            <Button text="Action" class="action-item"></Button>
          </ActionItem.actionView>
        </ActionItem>
      </ActionBar.actionItems>
    </ActionBar>
  </Page.actionBar>
</Page>
```
```
<Page class="page">
    <ActionBar class="action-bar" title="My App">
        <ActionItem>
            <Button text="Action" class="action-item"></Button>
        </ActionItem>
    </ActionBar>
</Page>
```

**Comment by hshristov** [comment]
@sserdyuk Nope, no downside. Exactly the opposite - less XML to parse

**Comment by sserdyuk** [comment]
@hshristov Why are they in the scheme then, if you don't mind me asking?

**Comment by hshristov** [comment]
@sserdyuk When we created the syntax initially this was the only way to set them. Later we added an option to skip the extra elements (more concise syntax) but miss to update the scheme.
