### ISSUE TITLE
[ios] Application crash if a button uses formatted text, custom font and isEnabled is changed

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#4332]
I have a button with formatted text and two spans, one of which uses font awesome. The buttons `isEnabled` property is bound to a model property. Once the bound value is changed from `true`  to `false` the application crashes with a `EXC_BAD_ACCESS` error. See attached sample. 
[demo-button.zip](https://github.com/NativeScript/NativeScript/files/1058257/demo-button.zip)

**Comment by NickIliev** [comment]
@PeterStaev thank you for reporting this one - I can confirm that indeed this is a bug as reported [here](https://github.com/NativeScript/NativeScript/issues/4230).

Closing as duplicate to [https://github.com/NativeScript/NativeScript/issues/4230](https://github.com/NativeScript/NativeScript/issues/4230)
