### ISSUE TITLE
How to monitor physical return key on Android?

### ISSUE THREAD

**Issue by giscafer** [NativeScript/NativeScript#4337]
on Android platform, there is a physical return button on the phone，the user is loving to use the physical return button not the app back button in the page，but something do special on app back button，not just go back the page. So ,how to monitor physical return key on Android? It's there any way to add a key listener?

![back button](https://user-images.githubusercontent.com/8676711/26915657-8b255188-4c59-11e7-9eb3-76f175e66687.png)

### Which platform(s) does your issue occur on?
Android

**Comment by NickIliev** [comment]
Using the backPressedEvent in Android
```
    application.android.on(application.AndroidApplication.activityBackPressedEvent, function (args) {
        console.log("Event: " + args.eventName + ", Activity: " + args.activity);
        // Set args.cancel = true to cancel back navigation and do something custom.
    });
```

More about application events can be found [here](http://docs.nativescript.org/core-concepts/application-lifecycle#android-activity-events-Example)

**Comment by giscafer** [comment]
@NickIliev thks
