### ISSUE TITLE
RowHeight of ListView is not working

### ISSUE THREAD

**Issue by SvetoslavTsenov** [NativeScript/NativeScript#4340]
Reproducible with tns-core-modules@3.1.0 for Android
Row height of list view item is not respected.
Steps to reproduce:
```
        <ListView items="{{ source }}" rowHeight="100">
            <ListView.itemTemplate>
                <Label text="{{ $value }}" />
            </ListView.itemTemplate>
        </ListView>
```

**Comment by tsonevn** [comment]
The problem is no longer reproducible with NativeScript 4.1. 
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2236000/Archive.zip)
