### ISSUE TITLE
Issue: Unable to change the fontWeight for both iOS and Android.

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#4342]
When you try to setup fontWeight, the text style will no be changed. This problem is reproducible on both iOS and Android. Only `bold` font weight will be applied. Attaching sample project, where the issue could be debugged.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.5 and 3.0.3
- Cross-platform modules: 2.5.2, 3.0.1
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1061310/Archive.zip)

t,1113363

**Comment by ishitatsuyuki** [comment]
@vakrilov can you provide some progress on this? Has the root cause been determined?

**Comment by vakrilov** [comment]
Hi, we are currently testing a fix proposed by #4436

**Comment by vchimev** [comment]
A compatible fix with *2.5* version has been released as **tns-core-modules@2.5.3**.
For *3.\** version, the fix is already available in **tns-core-modules@next** and is going to be released officially in *3.1.1* or *3.2.0*.
