### ISSUE TITLE
How to control the screen brightness?

### ISSUE THREAD

**Issue by kentplaza** [NativeScript/NativeScript#4347]
Is there any way to control the brightness? either with plugin or tns-core-module?

**Comment by NickIliev** [comment]
@kentplaza there is no built-in functionality in the modules that allows you to control the screen brightness and I was not able to find such in existing plugin. However, one of the best sides to NativeScript is that you can virtually do anything that the native API allows you to do.

For example, in Android you can do the following to dim your the screen of your current activity:
```
import { android as androidApp } from "application";

var params = androidApp.foregroundActivity.getWindow().getAttributes();
params.screenBrightness = 50; // range from 0 - 255 as per docs
androidApp.foregroundActivity.getWindow().setAttributes(params);
androidApp.foregroundActivity.getWindow().addFlags(android.view.WindowManager.LayoutParams.FLAGS_CHANGED);
```

The scenario above is pretty basic but following this logic, you can implement your own brightness control (multiple suggestions for Android [here](https://stackoverflow.com/questions/18312609/change-the-system-brightness-programmatically) and for iOS [here](https://stackoverflow.com/a/3779721/4936697)).

**Comment by priyangamani** [comment]
Is there anyother way to control the screen brightness of the device?

**Comment by NickIliev** [comment]
@priyangamani the example above is just one of the many options I have came across during my search on how to control the screen brightness in Android. Every native solution can be implemented in NativeScript - for more example look for threads like [this one](https://stackoverflow.com/questions/18312609/change-the-system-brightness-programmatically)

**Comment by chansc2016** [comment]
Hi, I had tried the following method for the ios but it seem doesn't work. Is there something i miss?

javascript:
if (app.ios) {
	var screen = utils.ios.getter(UIScreen, UIScreen.mainScreen);
	screen.brightness = 0.0; //float between 0.0 and 1.0.
}

**Comment by priyangamani** [comment]
How to retrieve current system Screen brightness value in nativescript?
