### ISSUE TITLE
tns build/run android works only once after installation 

### ISSUE THREAD

**Issue by c1ngular** [NativeScript/NativeScript#4353]
i have formatted HD and reinstalled OS **yesterday** , then i installed everything we need for nativescript cli according to {N} document, created the default helloworld project , it builds and runs on my android device successfully , so i thought this is working ~

**today** , i have tried to create and build a new project , but it failed to build android , then i went to the helloworld project i have created and builded successfully from yesterday , removed android platform , and tried to build and run it again , it fails too ~

**dev environment**
OS : Sierra 10.12.5
Node: v6.10.3
Java: 1.8.0_131
NPM : 5.0.3
Nativescript:3.0.3
Gradle: 3.3
Android SDK Platform: 25/23/22/21/19 [api level]
Android SDK Build Tools: 25.0.2, 26.0.0
Android SDK Platform Tools: 26.0.0
Android SDK Tool :26.0.2

**trace log attached** 
[log.txt](https://github.com/NativeScript/NativeScript/files/1065934/log.txt)

as @NickIliev directed:
tried "tns build android --sdk 23" , still not working , trace log shows, 
APILEVEL is still not set ~

**Comment by dtopuzov** [comment]
Hi @c1ngular,

We have some issues with npm5 and still do not support it.
Since several days `brew install node@6` will install `npm5` on your machine.
You can still use `brew install node@6`, but after it is complete you should downgrade to `npm4` with this command:
`npm i -g -f npm@4`

Once you have `npm4` please cleanup you project (or even better - create new one) and try again.

How to cleanup the project:
```
rm -rf <your-project>\platforms
rm -rf <your-project>\node_modules
rm -rf <your-project>\hooks
Remove `package-lock.json` files if such are available (this is something new introduced with `npm5`)
```

Notes:
`node6` officially brings `npm4`, not sure why brew installations get `npm5`.
`node8` officially brings `npm5` and we should add support for both `node8` and `npm5` (Most likely we will ship it with `nativescript@3.2.0` version).

**Comment by c1ngular** [comment]
@dtopuzov  thanks for helping , tried as you told , downgraded to npm 4.6.1, created a new helloworld project , still got the same error  ~ i have been troubled by this problem for 2 weeks , starts from here [](https://github.com/NativeScript/NativeScript/issues/4268), it is very frustrating 

i attached trace log for this time as well : 
[log.txt](https://github.com/NativeScript/NativeScript/files/1066469/log.txt)

**Comment by Pip3r4o** [comment]
@c1ngular There really isn't anything that I can identify as problematic when looking at all the logs you've shared, and I've been keeping up to date with the posts and comments. 

I'd ask that you try deleting the gradle wrapper and cache `.gradle` from your user directory, then create a project and try building it, while also allowing the wrapper to download anew.  Just throwing some ideas out there as I can't think of anything else that could be causing the errors.

**Comment by c1ngular** [comment]
@Pip3r4o it was my first guess that something might be wrong with gradle ,  I have had deleted the whole gradle folder, and made  build process downloading it fresh several times,  still  didn't work,  what makes me most curious is that, why I could successfully  build once  even I was using npm 5  shipped with node@6 by home brew~

**Comment by c1ngular** [comment]
@Pip3r4o  i guess , it might be caused by that  java 8 is not fully compatible with  Mac OS Sierra (v 10.12) , i have found lots similar complaining [null pointer exception] about this combination on internet by plenty of users  , i will try to downgrade my Mac OS to an older version (EI Capitan) in a couple of days, and see what happens ! or what would you suggest ?

**Comment by Pip3r4o** [comment]
@c1ngular some of the CI build machines that NativeScript is tested on are upgraded to Sierra, so that may not be it.

**Comment by c1ngular** [comment]
@Pip3r4o it is working now , in latest Mac OS version (10.12.5) , i installed everything i need as i did in previous attempts , except this time i left out Android studio ~ too tired to bother thinking why ,i will leave it to you experts for that if it interests you, thanks a lot for your time !
