### ISSUE TITLE
Question: how to use Android styles to amend default Android look?

### ISSUE THREAD

**Issue by sserdyuk** [NativeScript/NativeScript#4355]
I would like to amend the look of some UI components beyond of what available through CSS in NS. The native approach to it is to define a custom style and use it with the native component. Is there a way to specify my custom styles in the styles.xml file so it is automatically used by NS. 

For example, I find that default thumb size on material design slider is too small for my needs, based on the suggestion from [stackoverflow](https://stackoverflow.com/a/3187898), I can use drawable resource to replace the default thumb. I am trying to find a way to do it with configuration files rather than writing lots of platform code.

Thank you.

**Comment by tsonevn** [comment]
Hi @sserdyuk,
Indeed you could specify custom styles inside the App_Resources/Android/values/styles.xml file, which will be applied globally for the whole project. For example, specific style is defined for the DatePicker and TimePicker for API level higher than 21 inside our HelloWorld template.
app/App_Resources/Android/values-v21/style.xml
```
<?xml version="1.0" encoding="utf-8"?>
<resources>

    <!-- Application theme -->
    <style name="AppTheme" parent="AppThemeBase">
        <item name="android:datePickerStyle">@style/SpinnerDatePicker</item>
        <item name="android:timePickerStyle">@style/SpinnerTimePicker</item>
    </style>

    <!-- Default style for DatePicker - in spinner mode -->
    <style name="SpinnerDatePicker" parent="android:Widget.Material.Light.DatePicker">
        <item name="android:datePickerMode">spinner</item>
    </style>

    <!-- Default style for TimePicker - in spinner mode -->
    <style name="SpinnerTimePicker" parent="android:Widget.Material.Light.TimePicker">
        <item name="android:timePickerMode">spinner</item>
    </style>

    <style name="NativeScriptToolbarStyle" parent="NativeScriptToolbarStyleBase">
        <item name="android:elevation">4dp</item>
    </style>    
</resources>
```
However changing the thumb of the slider is related to defining custom drawable and changing the existing one, which could lead to build-time issues, while applying the custom drawable. 
Regarding that, my suggestion is to change the thumb from code behind on slider loaded event:
Example:
XML
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page">

    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>

    <StackLayout class="p-20">
        <Label text="Tap the button" class="h1 text-center"/>
        <Button text="TAP" tap="{{ onTap }}" class="btn btn-primary btn-active"/>
        <Label text="{{ message }}" class="h2 text-center" textWrap="true"/>
        <Slider loaded="slloaded"  minValue="0" maxValue="100" value="{{  }}" />
        
    </StackLayout>
</Page>
```
TypeScript
```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import {Slider} from "ui/slider"
import {Color} from "color"
declare var android:any
// Event handler for Page "navigatingTo" event attached in main-page.xml
export function navigatingTo(args: EventData) {

    let page = <Page>args.object;
    

    page.bindingContext = new HelloWorldModel();
}

export function slloaded(args){
    var sliderobj:Slider = <Slider>args.object;
    var newcolor = new Color("red");
    var thumb = new android.graphics.drawable.ShapeDrawable( new android.graphics.drawable.shapes.RectShape() );
    thumb.getPaint().setColor( newcolor.android );
    thumb.setIntrinsicHeight( 80 );
    thumb.setIntrinsicWidth( 30 );
    sliderobj.android.setThumb( thumb );
}
```

**Comment by sserdyuk** [comment]
@tsonevn Thank you for posting the examples. For the record, here's what I used in production:

```
import { screen } from "tns-core-modules/platform";
import { Slider } from "ui/slider";

    slloaded(args) {
        if (args.object.android) {
            const slider = <Slider>args.object,
                size = 30,
                scale = screen.mainScreen.scale,
                scaledSize = size* scale,
                thumb = new android.graphics.drawable.ShapeDrawable(new android.graphics.drawable.shapes.OvalShape());

            thumb.getPaint().setColor(slider.style.color.android);
            thumb.setIntrinsicHeight(scaledSize);
            thumb.setIntrinsicWidth(scaledSize);
            slider.android.setThumb(thumb);
        }
    }

```

**Comment by sserdyuk** [comment]
@tsonevn Actually, live is more complicated than that. The slider can be enabled and disabled at runtime, and the thumb needs to be updated. Is listening on the Slider.propertyChangeEvent the best way to do that? 

```
    ...
            this.on(Slider.propertyChangeEvent, (data: PropertyChangeData) => {
                if (data.propertyName == 'isEnabled') {
                    this.updateThumb();
                }
            });
    ...

```

**Comment by tsonevn** [comment]
Hi @sserdyuk,
It depends on the logic of the application, In case you want to disable the Slider after the value is changed, you could change the thumb style on `propertyChangeEvent` as you have mentioned above.

**Comment by sserdyuk** [comment]
@tsonevn Let me as a better question. If I am doing a custom component and can override methods,etc, is using the propertyChangeEvent listener to react on isEnabled attribute change the best way?

**Comment by tsonevn** [comment]
Hi @sserdyuk,
If you need to apply some extra customizations on the component at the startup of the application, the best time is to do them on component `loadedEvent`. For some further changes, depending some property changes, you could use `propertyChangeEvent`
