### ISSUE TITLE
How do I get pictures from my phone's album?

### ISSUE THREAD

**Issue by xiaochong44** [NativeScript/NativeScript#4356]
How do I get pictures from my phone's album?. Compatible with Android and IOS.

**Comment by NickIliev** [comment]
@xiaochong44 you can use[ nativescript-imagepicker](https://www.npmjs.com/package/nativescript-imagepicker) plugin.

Please note that this repository is for logging features, bugs, and issues. For the how-to related question, I would recommend using the community channels such as [https://discourse.nativescript.org/](https://discourse.nativescript.org/) and SO.

**Comment by xiaochong44** [comment]
@NickIliev 
Sorry,
I can't find the answer, so please ask here.
I'm using ImagePicker now, but in different Android phones, it's UI is different, and the difference is great, so I guess there's no way to get all the pictures, custom UI,
