### ISSUE TITLE
[NS 3.0] iOS TextView Caret Color is always system blue

### ISSUE THREAD

**Issue by dturing** [NativeScript/NativeScript#4357]
The Caret (blinking cursor line) in TextViews is always blue on iOS. It should be a separate CSS property, or be the same as the text color.

This had been tackled with #1013 a long time ago, but seems to have regressed?

Setting .tintColor as well as .textColor in [Line 198 of text-field.ios.ts](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/text-field/text-field.ios.ts#L198) (as seen in the commented-out line 195) seems to fix this.

**Comment by dturing** [comment]
(similar for [TextView](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/text-view/text-view.ios.ts#L146)

**Comment by tsonevn** [comment]
Hi @dturing 
Indeed there is a regression from NativeScirpt 2.5 and in this time changing the value of the color property will not change the cursor color. I am attaching a sample project, where this behavior could be reproduced.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1068178/Archive.zip)

However, in the meantime, you could change the tintColor on TextView and TextField loaded event, which will also apply the color to the cursor

XML
```
 <TextField loaded="loadedtf" hint="TextField test" color="red" text="{{  }}" />


```
TypeScript
```
export function loadedtf(args){
    var newcolor = new Color("red")
    args.object.ios.tintColor=newcolor.ios;
}
```

**Comment by vakrilov** [comment]
Hey @dturing - Thanks for the great PR!

When trying it out I noticed that the `tintColor` property wasn't reset to its original color. I did the fix and reopened anther PR based on your commit - #4549 
I'm closing this one in favour of the new one.
