### ISSUE TITLE
two webviews in tab view does not work 

### ISSUE THREAD

**Issue by c1ngular** [NativeScript/NativeScript#4365]
i have 2 webviews each loading 1 local html file in tabview , found that only the first webview in first tab item works/shows properly , the second does not show/work , unless i change the second webview's src to a remote web url .  this happened on iOS emulator , not sure about real device or Android platform ! {N} 3.0.3

```        
       <TabViewItem title="t1" iconSource="res://icons/bar">
        <TabViewItem.view>
            <GridLayout columns="*" rows="*">
                    <WebView id="priceView" src="~/charts/a.html" loadFinished="priceViewLoaded"/>
            </GridLayout>        
        </TabViewItem.view>
        </TabViewItem>
        <TabViewItem title="t2" iconSource="res://icons/amount">
        <TabViewItem.view>
            <GridLayout columns="*" rows="*">
                    <WebView  id="volumeView" src="~/charts/b.html" />
            </GridLayout>
        </TabViewItem.view>
        </TabViewItem>
```

**Comment by tsonevn** [comment]
Hi @c1ngular 

I tested this scenario with using the WebView inside the TabView and loading a local HTML file, however, I am unable to reproduce an issue with loading those files. For your convenience I am attaching sample project, could you review it and make the needed changes, which will allow us to reproduce this case on our side.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1070566/Archive.zip)
![screencast 2017-06-13 at 10 03 37 am](https://user-images.githubusercontent.com/17448734/27070088-20e8866c-5020-11e7-9b2d-6b7b4293346d.gif)

**Comment by c1ngular** [comment]
@tsonevn thanks , it is working ~ please close this issue !
