### ISSUE TITLE
Error installing the docs while cli-install on MacOSX (Maybe Linux too)

### ISSUE THREAD

**Issue by sittingbool** [NativeScript/NativeScript#4367]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

MacOSX 10.12.5

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

sudo npm install -g nativescript

### Please tell us how to recreate the issue in as much detail as possible.

1. Install nativescript cli on MacOSX
2. wait

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Output is:

EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nativescript/docs/html'

I guess its because the directory docs in /usr/local/lib/node_modules/nativescript/ is under my personal user but the installer ties as root (which is confusing but Apple changed some permission features in OSX 10.12).

The install process seams to run until the end though. But its confusing for some people.

**Comment by sittingbool** [comment]
Btw: if i create the directory myself I will still get the error and its gone again afterwards.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#2885
