### ISSUE TITLE
Throwing errors does no good...

### ISSUE THREAD

**Issue by bfattori** [NativeScript/NativeScript#437]
For those that like to throw errors, but hate that they are caught in the promises or lost entirely, I threw together this very simple helper:
```Javascript
var TraceableException = function(msg) {
    Error.call(this, msg);

    console.error('[TraceableException] %s', msg);
    console.trace();
};

TraceableException.prototype = Object.create(Error.prototype);
TraceableException.prototype.constructor = TraceableException;

global.TraceableException = TraceableException;
```
Load that in your `app.js` file and it will be on `global` scope so you can just call:
```Javascript

if (doSomething() === "failure") {
   throw new TraceableException("A failure occurred calling doSomething()");
}
```
You can catch that error if you want, let it get caught up in the promise and handle it there, but the benefit is that an error will be logged to the `console` and a stack trace will be produced (including the trace from JavaScript).

**Comment by N3ll** [comment]
@bfattori , it will helpful if you could make this as a plug-in.
