### ISSUE TITLE
Using the SFsafariviewcontroller delegate 

### ISSUE THREAD

**Issue by itsjtwright** [NativeScript/NativeScript#4373]
In native script there is a delegate system for UIApplication event hooks that allow you to see when the app is opened, or when the app is closed or suspended ect. There is another delegate system that I cannot find a way to use and that is the SFsafariviewcontroller delegate, a setup that allows you to hook into events like load finished for the view controller as well as hooking into the done button. Here is a link to the apple docs on this delegate, https://developer.apple.com/documentation/safariservices/sfsafariviewcontrollerdelegate Is there any way to do something like this in nativescript?
```
class MyDelegate extends NSObject implements SFSafariViewControllerDelegate {
   public static ObjCProtocols = [SFSafariViewControllerDelegate];
    safariViewControllerDidFinish() {
        console.log('did finish');
}
```
or is the SFsafariviewcontroller delegate not apart of native script at this time?

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/ios-runtime#772
