### ISSUE TITLE
Individual Border Radius

### ISSUE THREAD

**Issue by Ericky14** [NativeScript/NativeScript#4377]
I know this has already been asked as an issue and the issue was closed, but I have to ask again since there was no solution.

Is there a work-around to getting individual border-radius such as borderTopLeftRadius and so on? Will this feature ever be implemented?

I was not able to use clip-path to achieve the desired results.

**Comment by NickIliev** [comment]
@Ericky14 this feature is logged [here](https://github.com/NativeScript/NativeScript/issues/77) however at this time the NativeScript modules team is not prioritizing this feature as we are concentrated on performance improvements, webpack, Angular-2 and bug fixing. 
I have marked the feature with "up-for-grabs" so everyone who is interested and has a possible solution can [become a NativeScript contributor](https://www.nativescript.org/contribute).

Closing as duplicate to [https://github.com/NativeScript/NativeScript/issues/77](https://github.com/NativeScript/NativeScript/issues/77)
