### ISSUE TITLE
Trying to link invalid 'this' to a Java object, undefined

### ISSUE THREAD

**Issue by paldepind** [NativeScript/NativeScript#4378]
How does one debug errors of the type `Trying to link invalid 'this' to a Java object, undefined`?

I get the error by creating a new project with `tns create --tsc` and then importing the library [Jabz](https://github.com/funkia/jabz) into the project. I can import other modules without problems so I assume there's something specific to Jabz that causes the issue. But, I don't have any ideas about what that might be since the error message isn't very helpful.

Even though the error shows on the phone the library does seem to be imported correctly. I can use its functions and log their result.

```ts
import { isEmpty } from "@funkia/jabz";
console.log(isEmpty([]));
console.log(isEmpty([12]));
```

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.3
- Cross-platform modules: 3.0.1
- Runtime(s): 3.0.1

**Comment by NickIliev** [comment]
@paldepind not recognizing the entry point might be the reason for the library not to be imported as expected. To use the library I have cloned the [master branch from the author's repository](https://github.com/funkia/jabz) and done the following changes

- in tsconfig.json changed the target to es5 and removed all es2015 libs
- changed the entry point (**main**) and the module file (**module**) in the plugin's package.sjon to `src/index.js` 
- transpiled with `tsc` the plugin (some errors still needs attention in the Monad part of the plugin)
- executed `npm pack` to generate [new tgz](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/test/jabz)

All this done the plugin can now be imported as expected in NativeScript applications.
[Demonstation project here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/test/jabz) (I had to change [this ](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/test/jabz)to false to skip the Monad part errors). In the sample project you can find the generated *.tgz file.

**Comment by paldepind** [comment]
@NickIliev 

Thanks a lot for your answer. I greatly appreciate it.

I can confirm that the changes you made fixes the issue. I'm however quite confused about why that is. I'm a contributor to the library so I can make the necessary changes. Are all the changes you specified required? I'm not too happy about all of them.

> in tsconfig.json changed the target to es5 and removed all es2015 libs

In `tsconfig-release.json` (which is the config that compiles into the `/dist` directory) the target is set to es5. I cannot simply remove all the es2015 libs as the code actually uses the typings that are found in those.

> changed the entry point (main) and the module file (module) in the plugin's package.sjon to src/index.js

I don't think `main` and `module` can point to the same file. The former should point to a file in commonjs module format and the later to one in ES2015 module format. I don't understand why the current values of those would be a problem.

> transpiled with tsc the plugin (some errors still needs attention in the Monad part of the plugin)

I don't get any errors when I compile with `npm run build`. I think those happens because of the removed es2015 libs.

Let me add that using Jabz normally does not give any problems. I've used it both in Node, with Webpack and with Rollup without issues.

**Comment by NickIliev** [comment]
@paldepind, to be honest, I was not quite sure about **main** & **module** entries but I had to change them as in the master branch of the repository I've cloned there was no **dist** folder at all. Regarding the changed target to es5 - I've made for compatibility this as in NativeScript the target is es5a so all the javaScript will be in ES5 format by default - I had no idea that.`tsconfig-release.json` is targeting es5 so I guess taht is not a problem also.

**Comment by paldepind** [comment]
@NickIliev 

Thanks again for your answer. The command `npm run build` creates the `dist` directory. The `dist` directory contains transpiled ES5 files in the commonjs module format. The current value of `main` is `dist/index.js` and that correctly points to a file that is present in the current package on npm. Changing it shouldn's be necessary.

To me, it seems like the setup in Jabz should be fine. Also, note that even though the error occurs the library does seem to be imported correctly. I.e. the imported functions works as they should. I've forked your repository and added a project where [you can see this](https://github.com/paldepind/NativeScript-Issues-2017/tree/master/test/jabz2). When I run `tns run android` in the project the following is logged:

```
JS: true
JS: false
```

That is coming from [these lines](https://github.com/paldepind/NativeScript-Issues-2017/blob/master/test/jabz2/app/app.ts#L11). So despite the error Jabz actually seems to be imported correctly.

Since I've used Jabz without problems elsewhere I'm wondering if this is a bug in NativeScript.

**Comment by paldepind** [comment]
@NickIliev Did you find the time to look at the repository I linked? I still think that this looks like a bug in NativeScript. I'd be very interested to hear what you think. We are considering using NativeScript for a project but this issue is causing a bit of worry.
