### ISSUE TITLE
Timers are not standard

### ISSUE THREAD

**Issue by WebReflection** [NativeScript/NativeScript#4384]
`tns --version` 3.0.3 tested on android emulator platform version 25 and device with API 7.x

[Timers](https://www.w3.org/TR/2011/WD-html5-20110525/timers.html#timers) are a very well spec'd primitive, universally compatible with every platform but IE < 10 ... please don't be IE < 10 :smile: 

```js
setTimeout(console.log, 2000, 'hello', 'world');
```

The expected output is the equivalent of executing `console.log('hello', 'world')` after 2 seconds.

Instead, NativeScript runtime does not pass arguments along.

I have no idea how much code out there give this for granted, since it works literally everywhere like this, but it broke anyway already few scripts of mine.

Please consider fixing this or report this upstream if it's a nashorn issue (I'm really new to TS I'v eno idea what's exactly behind as JS core but so far it looks most of it just works out of the box, kudos that!)

Thank you and Best Regards

**Comment by tsonevn** [comment]
Hi @WebReflection,
Thank you for the suggestion. this could be a useful feature for the Timers in NativeScript. 
We will investigate, how it could be integrated into NativeScirpt. You could keep track on the issue for further info.

Something more, you could also make your own PR to `tns-core-modules`, which implements this functionality, we will review it and if all test passed, we will include it. For further info review [this article.](https://www.nativescript.org/contribute)

**Comment by WebReflection** [comment]
The [PR is up and running](https://github.com/NativeScript/NativeScript/pull/4389). The code is self explanatory and it should just work but if you can tell me where to find/write tests for the extra `...args` I'll try to write some.

**Comment by atanasovg** [comment]
Closed with https://github.com/NativeScript/NativeScript/pull/4389
