### ISSUE TITLE
End-to-End Testing

### ISSUE THREAD

**Issue by paranoid-android** [NativeScript/NativeScript#439]
I was trying to identify if there was a way to write end-to-end tests using NativeScript. With Ionic, I was able to successfully write some end-to-end tests with Jasmine. I would love to be able to do this with NativeScript. 

Is there a way to do end-to-end tests with NativeScript? Are there plans to include this?

**Comment by valentinstoychev** [comment]
Yes, you can write functional tests with any framework that supports native app. We use [Appium](http://appium.io/) internally and it works great for us.

As for unit tests - we are working on a complete solution, please see [here](https://github.com/NativeScript/karma-nativescript-launcher/blob/master/concept.md)
