### ISSUE TITLE
Styling SearchBar on android gives error: cannot read property 'android' of undefined, undefined

### ISSUE THREAD

**Issue by sridharmane** [NativeScript/NativeScript#4397]
### Tell us about the problem

Styling SearchBar on android gives error: 

```
cannot read property 'android' of undefined, undefined
```
I Don't see any errors in the console. 

<img width="414" alt="screen shot 2017-06-15 at 1 15 44 pm" src="https://user-images.githubusercontent.com/1156113/27193607-725e32d6-51cd-11e7-81f1-4c45419b4269.png">

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.3
- Cross-platform modules: tns-core-modules@~3.0.0
- Runtime(s):  
"tns-android": {
      "version": "3.0.0"
    },
    "tns-ios": {
      "version": "3.0.1"
    }
- Plugin(s): 
    "nativescript-appversion": "^1.4.1",
    "nativescript-plugin-firebase": "^3.12.0",

### Please tell us how to recreate the issue in as much detail as possible.
Add a SeachBar in the android app and style it using css.

**Comment by sserdyuk** [comment]
@sridharmane Could you post the code and XML?

**Comment by tsonevn** [comment]
Hi @sridharmane,
As @sserdyuk mentioned, it would help if you could provide the code from the XML, which you are using.
Also, it would help if you send us the CSS, which styles the SearchBar

**Comment by sridharmane** [comment]
The XML :
```
<SearchBar row="0" col="0" id="searchBar" hint="Search Name" [(ngModel)]="filters.name" (submit)="applyFilters($event)" (textChange)="applyFilters($event)"
        (loaded)="onSearchBarLoaded($event)" (clear)="applyFilters($event)" height="50"></SearchBar>
```
SCSS
```
SearchBar {
    background-color:$primary;
}
```

I was getting this error if I use the above styles as a common style for both ios and android. I moved the style such that it applies only to iOS and everything works. 

So basically, adding the ```backgroun-color``` style to ```SearchBar``` on android gives this error.

**Comment by NickIliev** [comment]
@sridharmane we [tried to reproduce](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4396) the error but to no avail. Let us know if you have a test project that can stably reproduce this issue and I will reopen this case immediatly.
