### ISSUE TITLE
Circle element using border

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#44]
_From @MiroValchev on April 23, 2015 14:6_

I wanted to show user's avatar in circle. To do this I tried using image nested in border.
1. I succeeded creating the circle, but the nested image was showing outside the boundaries of the border. Is this the desired behavior for border?
2. If you don't set a color for border, an exception is thrown. In the above example I want to use the border just for the rounded shape so a transparent default color sounds legit?

_Copied from original issue: NativeScript/cross-platform-modules#313_

**Comment by enchev** [comment]
Hey @MiroValchev! Can you post the code of your border and the exception related to color? Generally our Border class do no have any color by default.

**Comment by enchev** [comment]
_From @MiroValchev on April 24, 2015 8:45_

Hey @enchev 
This works just, except that it does not cut the image in a circle as expected.
```
<Border cssClass="user-picture" cornerRadius="100" borderColor="grey" borderWidth="3">
                  <Image cssClass="user-picture" src="{{ PictureUrl }}" stretch="aspectFill" />
</Border>
```
This one throws exception. I have just removed the borderColor. 
```
<Border cssClass="user-picture" cornerRadius="100" borderWidth="3">
                  <Image cssClass="user-picture" src="{{ PictureUrl }}" stretch="aspectFill" />
</Border>
```

[JS      ] Application error: Error; The application crashed because of an uncaught exception. You can look at "stackTrace" or "nativeException" for more detailed information about the exception.; com.tns.NativeScriptException: 
[JS      ] Calling js method onCreateView failed
[JS      ] 
[JS      ] TypeError: Cannot read property 'android' of undefined
[JS      ] File: "ui/border, line: 18, column: 55
[JS      ] 
[JS      ] StackTrace: 
[JS      ] 	Frame: function:'onCornerRadiusPropertyChanged', file:'ui/border', line: 18, column: 56
[JS      ] 	Frame: function:'ProxyObject._trySetNativeValue', file:'ui/core/proxy', line: 86, column: 27
[JS      ] 	Frame: function:'eachPropertyCallback', file:'ui/core/proxy', line: 65, column: 18
[JS      ] 	Frame: function:'DependencyObservable._eachSetProperty', file:'ui/core/dependency-observable', line: 359, column: 22
[JS      ] 	Frame: function:'ProxyObject._syncNativeProperties', file:'ui/core/proxy', line: 68, column: 14
[JS      ] 	Frame: function:'View._syncNativeProperties', file:'ui/core/view-common', line: 770, column: 48
[JS      ] 	Frame: function:'View._onContextChanged', file:'ui/core/view', line: 140, column: 14
[JS      ] 	Frame: function:'View._onAttached', file:'ui/core/view', line: 95, column: 14
[JS      ] 	Frame: function:'eachChild', file:'ui/core/view', line: 100, column: 23
[JS      ] 	Frame: function:'Layout._eachChildView', file:'ui/layouts/layout', line: 50, column: 22
[JS      ] 	Frame: function:'View._onAttached', file:'ui/core/view', line: 106, column: 18
[JS      ] 	Frame: function:'eachChild', file:'ui/core/view', line: 100, column: 23
[JS      ] 	Frame: function:'Layout._eachChildView', file:'ui/layouts/layout', line: 50, column: 22
[JS      ] 	Frame: function:'View._onAttached', file:'ui/core/view', line: 106, column: 18
[JS      ] 	Frame: function:'eachChild', file:'ui/core/view', line: 100, column: 23
[JS      ] 	Frame: function:'TabView._eachChildView', file:'ui/tab-view/tab-view-common', line: 151, column: 26
[JS      ] 	Frame: function:'View._onAttached', file:'ui/core/view', line: 106, column: 18
[JS      ] 	Frame: function:'TabView._onAttached', file:'ui/tab-view', line: 196, column: 38
[JS      ] 	Frame: function:'eachChild', file:'ui/core/view', line: 100, column: 23
[JS      ] 	Frame: function:'Layout._eachChildView', file:'ui/layouts/layout', line: 50, column: 22
[JS      ] 	Frame: function:'View._onAttached', file:'ui/core/view', line: 106, column: 18
[JS      ] 	Frame: function:'eachChild', file:'ui/core/view', line: 100, column: 23
[JS      ] 	Frame: function:'ContentView._eachChildView', file:'ui/content-view', line: 51, column: 13
[JS      ] 	Frame: function:'View._onAttached', file:'ui/core/view', line: 106, column: 18
[JS      ] 	Frame: function:'View._addViewCore', file:'ui/core/view', line: 75, column: 18
[JS      ] 	Frame: function:'View._addView', file:'ui/core/view-common', line: 705, column: 14
[JS      ] 	Frame: function:'onFragmentShown', file:'ui/frame', line: 153, column: 11
[JS      ] 	Frame: function:'PageFragmentBody.onCreateView', file:'ui/frame', line: 46, column: 13
[JS      ]

**Comment by truongsinh** [comment]
+1

**Comment by enchev** [comment]
Hey folks,

I've just [merged in master](https://github.com/NativeScript/NativeScript/pull/320) support for borders for any component. Here is an example with Button:
```XML
<Page>
    <Button text="Button" style="width:200;height:200;border-width:1;border-color:red;border-radius:100;background-color:green" />
</Page>
```

**Comment by duongnhatduy** [comment]
Hey, I tried this on Image but it doesn't work

**Comment by eugeneniemand** [comment]
I also experienced this problem while trying the tab-view example as specified in the docs. Can te docs be updated with a warning or is there an ETA on a fix for this?

**Comment by viniciodeltoro** [comment]
I'm trying to put an image inside a StackLayout that has round borders looking as a circle. But I have the same issue as everyone else, the image gets displayed outside the circle. This is my code:

```
<StackLayout class="avatar">
  <StackLayout class="circle-wrapper">
    <Image [src]="item.user.avatar"></Image>
  </StackLayout>
</StackLayout>
```

CSS:
```
.avatar{
  background-color: #ffffff;
  width:50;
  height: 50;
  margin-right: 15;
}

.circle-wrapper{
  background-color: #666666;
  border-radius: 100;
  width: 100%;
  height: 100%
}
```

I also tried using clip-path instead of border-radius but I get the same result. Any suggestions?

Thank you

**Comment by jovanymezura** [comment]
Hello @viniciodeltoro try whit this .circle-wrapper{
 background-color: #666666;
border-radius: 30;
border-width:20;
border-color:any;
width:100px;
height:100px;
}

**Comment by BenGermany** [comment]
Hey folks, 

why you don't use borderRadius directly on Image Tag?

**Comment by viniciodeltoro** [comment]
Hey @BenGermany that's what I end up doing and now it works on Android but not on iOS. So I guess I will have to create a piece of code for Android and another one for iOS.

Thanks for the help guys.
