### ISSUE TITLE
Using greater than (>) comparison operator in binding expression causes XML parse error

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#440]
For example:
```xml
<Label text="{{ var1 > var2 }}" />
```
Output:
tns_module/ui/builder/builder.js:139:157 JS ERROR Error: XML parse error: close tagname

**Comment by hamorphis** [comment]
&gt; should be used.

**Comment by hamorphis** [comment]
&.g.t.;

**Comment by emiloberg** [comment]
Just a note: Other XML based languages (such as freemarker) solves this by enclosing the statement within parenthesis, .e.g `<Label text="{{ (var1 > var2) }}" />`

**Comment by hgenru** [comment]
this bug is fixed?
