### ISSUE TITLE
Installation failed when install globally with Yarn under Node JS 8

### ISSUE THREAD

**Issue by hantsy** [NativeScript/NativeScript#4401]
I tried to install NativeScript via Yarn, but failed due to incompatible module with Node 8.1.2.

```
error ios-sim-portable@3.0.0: The engine "node" is incompatible with this module. Expected version ">=4.2.1 <5.0.0 || >=5.1.0 <8.0.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

BTW, installation via NPM is successfully.

**Comment by dtopuzov** [comment]
Hi @hantsy 

Currently we do not support `node8`, `npm5` and `yarn`, but we have plans to enable them.

Closing this issue in favor of 
https://github.com/NativeScript/nativescript-cli/issues/2873
https://github.com/NativeScript/nativescript-cli/issues/2737

**Comment by hantsy** [comment]
@dtopuzov  Thanks for ur clarification.
