### ISSUE TITLE
SegmentedBar doesn't render initial state properly on iOS

### ISSUE THREAD

**Issue by sserdyuk** [NativeScript/NativeScript#4410]
SegmentedBar doesn't show any of the tabs lit even if selectedIndex property is set. This is specific to iOS, the Android is behaving as expected.

The workaround I found is to set selectedIndex to a wild number at first (as commented out in the code below), and then to the correct one. This helps, but is very inconvenient if the number is set through binding.

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="onLoad" class="page">
    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>
    <StackLayout class="p-20">
        <SegmentedBar id="bar">
            <SegmentedBarItem title="Item 1" />
            <SegmentedBarItem title="Item 2" />
            <SegmentedBarItem title="Item 3" />
        </SegmentedBar>
        <StackLayout class="m-20">
            <Button text="Set 0" tap="setselectedIndex0" />
            <Button text="Set 1" tap="setselectedIndex1" />
        </StackLayout>
    </StackLayout>
</Page>
```

```
import { SegmentedBar } from 'ui/segmented-bar';
import { EventData } from 'data/observable';
import { Page } from 'ui/page';

let page: Page, bar: SegmentedBar;

export function onLoad(args: EventData) {
    page = <Page>args.object;
    bar = <SegmentedBar>page.getViewById("bar");
    // bar.selectedIndex = 99;
    bar.selectedIndex = 0
}

export function setselectedIndex0(){
    bar.selectedIndex = 0
}
export function setselectedIndex1(){
    bar.selectedIndex = 1
}
```

```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 3.0.3           │ 3.0.3          │ Up to date    │
│ tns-core-modules │ 3.0.1           │ 3.0.1          │ Up to date    │
│ tns-android      │                 │ 3.0.1          │ Not installed │
│ tns-ios          │ 3.0.1           │ 3.0.1          │ Up to date    │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```

![simulator screen shot jun 16 2017 7 28 34 pm](https://user-images.githubusercontent.com/395998/27247795-ffbe514a-52c9-11e7-8583-28de527d36c9.png)

**Comment by tsonevn** [comment]
Hi @sserdyuk,
Thank you for reporting this issue.
After I tested it on my side I have to confirm that this is a real problem for iOS and the style for the selected tab will not be applied. You could keep track on the issue for further info.

**Comment by tsonevn** [comment]
Hi @sserdyuk,
This issue is fixed with  @next modules. You could test it on your side while adding those modules.
Steps:
1. `tns plugin remove tns-core-modules`
2. `tns plugin add tns-core-modules@next`
3. remove `platforms` and `node_modules` folders

**Comment by sserdyuk** [comment]
@tsoenv great! Is it going to make into 3.1?

**Comment by tsonevn** [comment]
@sserdyuk 
yes, this fix is already added for upcoming release
