### ISSUE TITLE
getMeasuredWidth/height always return 0 on Android

### ISSUE THREAD

**Issue by c1ngular** [NativeScript/NativeScript#4413]
i have tried to call these functions in different page/view events , always get zero on Android , iOS emulator seems working as expected .
Any ideas, thanks !

**Comment by thomaspaniagua** [comment]
I seem to be having trouble with the same thing at the moment. I did discover that if I call this within a tap event (or any other event seconds after app launch like a setTimeout for that matter) that it will return an actual number. After some research it seems like a parent's loaded function is called before its children are initiated which leads to the 0 when called then. Try waiting a few seconds through a setTimeout or a tap and see what happens.

**Comment by c1ngular** [comment]
@thomaspaniagua thanks for helping , i can't wait few seconds or a tap event to happen for my purpose , i need this on my home page to dynamically add views accordingly , thanks any way !

**Comment by sserdyuk** [comment]
You are checking too early. You have to wait at least on "load" event to fire. See #4329.

**Comment by c1ngular** [comment]
@sserdyuk  I tried that , except the setTimeout part , I am wondering, how do we know how long to wait on different devices ?  Thanks for your help !

**Comment by sserdyuk** [comment]
If you need to measure a specific component, hook into "loaded" event for the component specifically, not the page itself. See the example in #4329.

**Comment by thomaspaniagua** [comment]
@sserdyuk, even if the code is attached to the loaded event, it will have the same outcome (on iOS).

**Comment by sserdyuk** [comment]
I suggest that you post your source code here so that Telerik team can help you.

**Comment by NickIliev** [comment]
@thomaspaniagua you question is about Android and wrapping some layouts in minimal setTimeout (e.g. 100 milliseconds) will do the trick. However your last comment is mentioning iOS - are you having issues getting the measures on iOS as well?

Please share the XML layout you are trying to measure so we can investigate further.

**Comment by aMarCruz** [comment]
@sserdyuk , @NickIliev ,
@c1ngular is right, 100ms are not enough, the Samsung FrandPrime needs 200ms to detect the measurements.
