### ISSUE TITLE
Style error after upgrading to NS 3

### ISSUE THREAD

**Issue by Cayan** [NativeScript/NativeScript#4415]
## Please, provide the details below:
I was finally able to migrate to NS 3 yey! While I was navigating in some pages I noticed an error, it took me a while to figure it out.

The log is:
`JS: ERROR Error: Uncaught (in promise): TypeError: androidView.background.newDrawable is not a function
JS: TypeError: androidView.background.newDrawable is not a function
JS:     at Object.onBackgroundOrBorderPropertyChanged (file:///data/data/org.nativescript.meupatrocinio/files/app/tns_modules/tns-core-modules/ui/styling/background.js:67:83)
JS:     at Label.View.(anonymous function) (file:///data/data/org.nativescript.meupatrocinio/files/app/tns_modules/tns-core-modules/ui/core/view/view.js:382:29)
JS:     at Object.initNativeView (file:///data/data/org.nativescript.meupatrocinio/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js:818:37)
JS:     at Label.ViewBase._setupUI (file:///data/data/org.nativescript.meupatrocinio/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:542:30)
JS:     at file:///data/data/org.nativescript.meupatrocinio/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:546:19
JS:     at StackLayout.LayoutBaseCommon.eachChildView (file:///data/data/org.nativescript.meupatrocinio/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:26)
JS:     at StackLayout.ViewCommon.eachChild (file:///data/data/org.nativescript.meupatrocinio/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js:690:14)
JS:     at StackLayout.ViewBase._setupUI (file:///data/data/org.nativescript.meupatrocinio/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:545:14)
JS:     at file:///data/data/org.nativescript.meupatrocinio/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:546:19
JS:     at ProxyViewContainer.LayoutBaseCommon.eachChildView (file:///data/data/org.nativescript.meupatrocinio/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:26)
JS:     at ProxyViewContainer.ViewCommon.eachChild (file:///data/data/org.nativescript.meupatrocinio/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js:690:14)
JS:     at ProxyViewContainer.ViewBase._setupUI (file:///data/data/org.nativescript.meupatrocinio/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:545:14)
JS:     at FlexboxLayout.ViewBase._addViewCore (file:///data/data/org.nativescript.meupatrocinio/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:438:18)
JS:     at FlexboxLayout.ViewBase._addView (file:///data/data/org.nativescript.meupatrocinio/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:419:14)
JS:     at FlexboxLayout.LayoutBaseCommon.insertChild (file:///data/data/org.nativescript.meupatrocinio/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:49:14)
`

I had a CSS class with:
`.introduction-text {
    font-size: 14;
    height: 110;
    text-align: center;
    text-indent: 5;
    width: 100%;
    border-width: 0;
    background: transparent;
    margin-top: 15;
}`

The border-width is alone with no other border related argument. Removing that line fixed it for me.

I'm reporting this because I think there should be a better way to report this instead of those fatal errors.

### Which platform(s) does your issue occur on?
Tested on Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.3
- Cross-platform modules: ^3.0.1
- Runtime(s): 3.0.1

**Comment by NickIliev** [comment]
@Cayan thank you for reporting this issue.
Confirming that setting border-width: 0 and background: transparent would crash your application with:
```
androidView.background.newDrawable is not a function, undefined
```
Test project can be found [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4415)
