### ISSUE TITLE
Search Bar don't have textChange event 

### ISSUE THREAD

**Issue by LeCaoPhuc** [NativeScript/NativeScript#4417]
Hi all,
I am creating a search bar but I don't find **textChange** event in tns-core-modules/ui/search-bar. It have only submit and clear event for android and ios. Howerver, I can see a event   "QueryTextListenerImpl.prototype.onQueryTextChange" in search-bar.android.js file and "UISearchBarDelegateImpl.prototype.searchBarTextDidChange" search-bar.ios.js.

To Solve, I added a some code in search-bar-common.js and search-bar.d.ts.
In search-bar-common.js add `SearchBarBase.textChange = "textChange";` under`SearchBarBase.clearEvent = "clear";`
In search-bar.d.ts add  ` public static textChange: string;` and
 `on(event: "textChange", callback: (args: EventData) => void, thisArg?: any);` 

After, I call event with .ts file :
` var searchBarModule = require('ui/search-bar');`
`export function loadSearchBar(args)
    { 
        var textField = args.object;
         textField.on(searchBarModule.SearchBar.textChange, function(args) {
             console.log("Searchbar event");
       }
    }`
In .xml file : 
`<SearchBar hint="Search hint" textFieldHintColor="#ccc" 
                           loaded="loadSearchBar"></SearchBar>`
And It worked.
I think development department can implement in library to easy for use.
Thanks !

**Comment by tsonevn** [comment]
Hi @LeCaoPhuc,
Thank you for your suggestion.
I reviewed your case and found that you could trigger the text change, without the needed to make any changes inside the NativeScript modules.
At the moment you could handle the change as defining as first argument the event name as string value inside the `on` method. For example.
```
export function searchbarLoaded(args){
var search:SearchBar = <SearchBar>args.object;
search.on("textChange", function(args){
    console.log("text changed");
    console.log((<any>args).value)
})
}
```

**Comment by LeCaoPhuc** [comment]
Hi @tsonevn, Thank you very much for a help and example. It worked with me...Have nice day.

**Comment by RoyiNamir** [comment]
@tsonevn  where is the documentation for `textChange` ? 

the only thing I've found is 
https://docs.nativescript.org/api-reference/modules/_ui_enums_.updatetexttrigger#textchanged

But that's not the same event name

**Comment by VeeK727** [comment]
Hi @tsonevn , can you explain your code? What is the `searchbarLoaded` function?
