### ISSUE TITLE
Debugger.js exception for HTTP requests with no Content-Type

### ISSUE THREAD

**Issue by milannankov** [NativeScript/NativeScript#4419]
Hello,

I am getting an error in debugger.js when debugging my app. The app sends HTTP requests some of which happen to have no "Content-Type". This seems to be causing the error.

Error: Error while parsing debug 'response' object. mimeType: string value expected.

Debugger.ts contains the following code:
`let mimeType: string = <string>headers["Content-Type"] || <string>headers["content-type"];`

So there will be no mimeType for requests with no "Content-Type". Locally I have temporarily fixed the problem by providing an empty string if no "Content-Type" is specified.

`let mimeType: string = <string>headers["Content-Type"] || <string>headers["content-type"] || '';`

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.3
- Cross-platform modules: 3.1.0-2017-06-16-6999 or 3.0.1

- Runtime(s): 3.0.1

### Please tell us how to recreate the issue in as much detail as possible.
1. Unzip the sample 
2. Run the http server - node .\server\index.js
3. Add Android platform to the app - HelloWorld
4. Update main-page.js to hit the correct URL
5. Run the app in debug mode using VS Code
6. Click the button

[bug-http.zip](https://github.com/NativeScript/NativeScript/files/1084306/bug-http.zip)

**Comment by NickIliev** [comment]
The issue is only reproducible when using local node server (as in the posted example above).

**Comment by R4ZuL** [comment]
+1

I am using ASP.NET Core Web API services for my backend. The application crashs if one of my services returns a http status code that doesn't include content for example 404 - Not Found

**Comment by joshcomley** [comment]
I have the same issue, with the same environment except in my case it's a missing mime type that's causing it to crash

**Comment by joshcomley** [comment]
Hacky fix for now, I just modified line 15 of debugger.js in my `node_modules` to:

        var mimeType = headers["Content-Type"] || headers["content-type"] || "text/plain";
