### ISSUE TITLE
ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'Telerik.TelerikAppFeedback'

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/NativeScript#4423]
Hello,

I am trying to upload an app to iTunesConnect and I am getting the following errors:
**ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'Telerik.TelerikAppFeedback' under the iOS application myapp.app**

**ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'Telerik.TelerikUI' under the iOS application myapp.app**

Here is my package.json

```{
  "name": "myapp",
  "version": "1.0.0",
  "description": "Mobile Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "Mobile Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.company.myapp",
    "tns-ios": {
      "version": "3.0.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/router": "~4.1.0",
    "@progress/nativescript-telerik-ui-pro": "^2.0.1",
    "moment": "^2.18.1",
    "nativescript-angular": "~3.0.0",
    "nativescript-appversion": "^1.4.1",
    "nativescript-drop-down": "^3.0.2",
    "nativescript-loading-indicator": "^2.3.2",
    "nativescript-local-notifications": "^1.2.1",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-toast": "^1.4.5",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "~3.0.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "~0.4.0",
    "typescript": "~2.2.1"
  }
}```

Any idea of what could be causing this and how to resolve it?

Thank you.

**Comment by tsonevn** [comment]
Hi @dpdragnev,
I was able to reproduce this error while using the dependencies from the attached `package.json` file. 
However, we will need some more time to verify what is causing this error and will write you back as soon as we have some solution or any further info.

**Comment by dpdragnev** [comment]
Thank you @tsonevn,

I upgraded NS to version 3.1.0 and now I am able to publish via tns publish ios.  Perhaps the latest version of NS fixed it?

**Comment by tsonevn** [comment]
Hi @dpdragnev,
I am glad to hear that you were able to solve this problem.
Indeed this problem could be reproduced with current CLI version. In the upcoming one, several issues with the iOS publish command has been fixed and for now you could use the @next version.

**Comment by clayellis** [comment]
@tsonevn Did you ever figure out what was causing the issue? What changed in the CLI versions around the publish command that resolved the issue?
