### ISSUE TITLE
Slider[Android] set value to zero and maxValue breaks the progress of the slider  

### ISSUE THREAD

**Issue by SvetoslavTsenov** [NativeScript/NativeScript#4424]
Steps to reproduce
```
	<Slider minValue="0" maxValue="10" value="0" />
```
Also reproducible with animations-demos tests
https://github.com/NativeScript/animation-demo/blob/master/app/css-animations/settings/page.xml

![image](https://user-images.githubusercontent.com/3598759/27322676-aa1c6ca0-55a7-11e7-9f5d-36c8d490215e.png)

**Comment by vchimev** [comment]
https://github.com/NativeScript/NativeScript/commit/4f76fab4ae1e7bed75d20ce6248a8cebb35b07c8
