### ISSUE TITLE
how to access specific list item view without using itemTap event ?

### ISSUE THREAD

**Issue by c1ngular** [NativeScript/NativeScript#4425]
i have a observable array binded to a listview, **this listview will not use the itemTap event** , since tap event will do nothing at all in my scenario , so my problem is : 

i want to  change/animate particular list **item view** from code as my binded observable array item changes, but i found nothing from listview API document which might achieve such a functionality , only way to access/change a specific list item view is by listening to itemTap event , i wonder is there any alternative would make this work ? 

another problem is that i found i can not have access to the  index of my observable array from list view template , i have tried {{ $index }}, {{ index }}, nothing works ~

i know this is not a good place to ask questions , but i have tried slack/forum/stackoverflow , found nothing ~

thanks

**Comment by tsonevn** [comment]
Hi @c1ngular 
You could setup the tap event for the layout which is used in your `ListView.itemTemplate` and on callback method to access its `object` property . For example:
```
<ListView.itemTemplate>
               <StackLayout tap="onTap">
                   <Label text="{{title}}" textWrap="true" />
                   
               </StackLayout>
</ListView.itemTemplate>
```
```
export function onTap(args){
     //args.object
}
```

However, the best solution to access the items view and to apply the needed animation on  `itemTap` event.
XML
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page">

    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>

   <GridLayout rows="" columns="">
       <ListView items="{{ source }}"  loaded="onLoaded" itemLoading="onItemLoading" itemTap="onItemTap">
           <ListView.itemTemplate>
               <StackLayout>
                   <Label text="{{title}}" textWrap="true" />
                   
               </StackLayout>
           </ListView.itemTemplate>
       </ListView>
   </GridLayout>
</Page>
```
TypeScript 
```
import { EventData } from 'data/observable';
import {ObservableArray} from "data/observable-array"
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';

// Event handler for Page "navigatingTo" event attached in main-page.xml
export function navigatingTo(args: EventData) {

    let page = <Page>args.object;

    var array=new ObservableArray();
    array.push({title:"title1"});
    array.push({title:"title2"});
    array.push({title:"title3"});
    array.push({title:"title4"});
    array.push({title:"title5"});
    page.bindingContext = {source:array}
}

export function onItemTap(args){
    console.log("item tap");
    console.log(args.view);

}
```

**Comment by c1ngular** [comment]
@tsonevn  thanks , i may have not made my point clear , what i am looking for is , to access list's item view without user interaction (tap event ) !
how about accessing observable array 's index from list view template , i have tried {{ $index }} , it is not working ~

**Comment by tsonevn** [comment]
Hi @c1ngular,
Excuse me for my misunderstanding,
For this scenario, you could setup unique id for every item of the ListView and by using the `Page` `getViewById()` method,  to get the needed view, without the user interaction. For example:
XML
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page">

    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>

   <GridLayout rows="" columns="">
       <ListView items="{{ source }}"  loaded="onLoaded" itemLoading="onItemLoading" itemTap="onItemTap">
           <ListView.itemTemplate>
               <StackLayout id="{{'item'+index}}">
                   <Label  text="{{title}}" textWrap="true" />
                   
               </StackLayout>
           </ListView.itemTemplate>
       </ListView>
   </GridLayout>
</Page>

```

TypeScript 
```
import { EventData } from 'data/observable';
import {ObservableArray} from "data/observable-array"
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import {ListView} from "ui/list-view"

// Event handler for Page "navigatingTo" event attached in main-page.xml
export function navigatingTo(args: EventData) {

    let page = <Page>args.object;
    
    
    var array=new ObservableArray();
    array.push({index:1, title:"title1"});
    array.push({index:2, title:"title2"});
    array.push({index:3, title:"title3"});
    array.push({index:4, title:"title4"});
    array.push({index:5, title:"title5"});
    page.bindingContext = {source:array}
}
```

In the time when you need the view, you could use the following code:
```
var view = page.getViewById("item1");
```

**Comment by c1ngular** [comment]
@tsonevn  thanks , i tried this trick, thought there may be better/correct way of accessing array index from list view template !

**Comment by tsonevn** [comment]
Hi @c1ngular,

This is the possible way to get the View in the pure NativeScript project at this time.

Let me know, whether this is applicable for you or is I could assist you further

**Comment by kglowacki** [comment]
this is really awkward... any plans to fix this (by exposing $index property) ?
