### ISSUE TITLE
Document how to call function in viewmodel from XML

### ISSUE THREAD

**Issue by lukeramsden** [NativeScript/NativeScript#4431]
Not sure if it's documented anywhere, but if it is it should be more prominent, is that if you want to call a function that's in a view model:

`view-model.ts`
```typescript
import { Observable, EventData } from 'data/observable'
import { GestureEventData } from 'ui/gestures'

export class FinanceCalculatorModel extends Observable {

  private _selectedUnit: number;

  constructor() {
    super();

    // Initialize default values.
    this._selectedUnit = 0;
  }

  get selectedUnit(): number {
    return this._selectedUnit;
  }

  set selectedUnit(value: number) {
    if (this._selectedUnit !== value) {
      this._selectedUnit = value;
      this.notifyPropertyChange('selectedUnit', value)
    }
  }

  public tapUnit(args: GestureEventData) {
    const value: number = args.object['unit']
    if (this._selectedUnit !== value) {
      this._selectedUnit = value;
      this.notifyPropertyChange('selectedUnit', value)
    }
  }
}
```
You have to bind it in XML like this:
```xml
<GridLayout rows="4*, *" unit="0" tap="{{tapUnit}}" class="multi-select-square multi-select-square-big"  id="{{ selectedUnit == 0 ? 'selected' : '' }}">
```

with the `{{}}`

Took me quite a bit of debugging to figure this out, so this is just to help people with the same issue.

**Comment by tsonevn** [comment]
Hi @lukeramsden,
Similar information already exists in the [data-binding article](http://docs.nativescript.org/core-concepts/data-binding#binding-to-an-event-in-xml), where it is described how to bind to a specific event in XML.

**Comment by lukeramsden** [comment]
Ahh ok, I couldn't find anything on Google so hopefully this issue will start coming up.
