### ISSUE TITLE
[NS 3.0] iOS TextView hint issue

### ISSUE THREAD

**Issue by davorpeic** [NativeScript/NativeScript#4433]
When using hint on TextView, iOs gives an color issue:

`CONSOLE ERROR [native code]: ERROR TypeError: UIColor.blackColor.colorWithAlphaComponent is not a function. (In ‘UIColor.blackColor.colorWithAlphaComponent(0.22)‘, ‘UIColor
.blackColor.colorWithAlphaComponent’ is undefined)`

template
```
<TextView #TV1  formControlName=“text” hint=“you message” [(ngModel)]=“entry.text”></TextView>
```

I traced issue to https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/text-view/text-view.ios.ts#L130 It looks like that TextView doesn't have default `color` assigned because once I put `color="black"` in the tag, then it works.

In this comments it says something about Xcode changing some methods to properties, so I think that the source needs some backward compatibility fixes? https://github.com/NativeScript/NativeScript/issues/2839#issuecomment-251385801

Thanks

**Comment by tsonevn** [comment]
Hi @davorpeic,
I tested your case with latest NativeScript 3.0 and setting up `hint` to the TextView seems to work as expected on my side. For your convenience, I am attaching a sample project. you could review it and make the needed changes, which will allow us to reproduce this behavior.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1090528/Archive.zip)
![screen shot 2017-06-21 at 9 40 12 am](https://user-images.githubusercontent.com/17448734/27370709-7443d1a8-5666-11e7-96c9-59ff9c765fdc.png)

It will also help if you provide some info for the device, which you are using for testing.

**Comment by davorpeic** [comment]
Hi @tsonevn 

thank you very much for test project. I run it on my machine (Xcode 8.3, iOS 10.3) and I can see fine the hint, and I also run it on our other machine where we have older version and where we actually got the error (Xcode 7.3, iOS 9) and I can there is still issue with that. The app doesn't crash but the textview is not visible.

```
CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1091:24: ERROR Error: Uncaught (in promise): TypeError: UIColor.bl
ackColor.colorWithAlphaComponent is not a function. (In 'UIColor.blackColor.colorWithAlphaComponent(0.22)', 'UIColor.blackColor.colorWithAlp
haComponent' is undefined)
        _refreshColor@file:///app/tns_modules/tns-core-modules/ui/text-view/text-view.js:104:87
        showHint@file:///app/tns_modules/tns-core-modules/ui/text-view/text-view.js:120:27
        _refreshHintState@file:///app/tns_modules/tns-core-modules/ui/text-view/text-view.js:86:26
        file:///app/tns_modules/tns-core-modules/ui/text-view/text-view.js:139:31
```

And here is how it is seen in both versions

![glass_and_iphone_6_ _ios_10_3__14e269_](https://user-images.githubusercontent.com/694091/27390861-ffa39340-5667-11e7-85db-b842712640fb.jpg)

Hope it helps debug it, we just updated to latest NS+angular.
davor

**Comment by tsonevn** [comment]
Hi @davorpeic,
the above-mentioned error has been related to the fact that from Xcode 8.* some of the methods in the iOS SDK now are properties and this is the reason for the problem.
In regard to that, this does not depend on NativeScript and to be able to build project for iOS 9 or higher you should use Xcode 8.  
for further info, you could review [this article](http://fluentreports.com/blog/?p=401).

**Comment by davorpeic** [comment]
HEy @tsonevn 
thanks for that, updating to xcode 8 actually fixed the issue :) thanks!
