### ISSUE TITLE
Close button is not visible in action dialogue on iPad

### ISSUE THREAD

**Issue by SvetoslavTsenov** [NativeScript/NativeScript#4435]
Close button of a dialogue is not visible on iPad
Reproducible with this code 

on simulator iOS 10
![dialogs_21_actionclose_test_svetli_delete_actual](https://user-images.githubusercontent.com/3598759/27375488-0b4de00a-5678-11e7-884a-550e924c2da2.png)

on iPad2 iOS 10

![](http://nsbuild01.telerik.com:8080/build/view/Stable/view/32.%20Tests%20iOS/job/integration-tests-stable-uitests-ios-10-ipad2/269/artifact/target/surefire-reports/screenshots/dialogs_21_actionClose_fail.png)

**Comment by manoldonev** [comment]
Closing this as duplicate of https://github.com/NativeScript/NativeScript/issues/5894
