### ISSUE TITLE
GridLayout not rendered in RadListView.headerItemTemplate

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#4442]
The GridLayout does not render properly when in GridLayout not rendered in RadListView.headerItemTemplate/footerItemTemplate.

Works as expected with `tns-core-modules@3.1.0-2017-06-06-6819`.
Does not work with `tns-core-modules@3.1.0-2017-06-08-6858` - commit https://github.com/NativeScript/NativeScript/commit/014e7a8e0ffaeefd5e0c29f0bfa64459f7547681.

CC: @miroslavaivanova

# Example:

https://github.com/telerik/NativeScriptUITestApp/blob/master/NativeScriptUITests/app/listview/header-footer/header-footer.xml

# Expected:
![listviewheaderfooter_02_item_selection_expected](https://user-images.githubusercontent.com/12251337/27433881-2a2f14d4-575f-11e7-85b0-57a8c54d812a.png)

# Actual:
![listviewheaderfooter_02_item_selection_actual](https://user-images.githubusercontent.com/12251337/27433871-221b465a-575f-11e7-96c3-3f8d179354c9.png)

# Diff:
![listviewheaderfooter_02_item_selection_diff](https://user-images.githubusercontent.com/12251337/27433877-2839d56a-575f-11e7-9665-429298e2684a.png)

**Comment by ginev** [comment]
This results in another issue which is observable in the SDK samples of NativeScript UI: when navigating to an example of a given control and going back the examples list is shuffled.

**Comment by vchimev** [comment]
Both issues have been handled in the `nativescript-ui` plugin.
