### ISSUE TITLE
Can't load local files in a WebView on iOS devices

### ISSUE THREAD

**Issue by EddyVerbruggen** [NativeScript/NativeScript#4443]
I hear you think: "not this one again!?". Bear with me.

### Tell us about the problem
Loading a local file like `<WebView src="~/webview-content.html"/>` fails when doing `tns run ios` on an *iOS device*. A simulator is fine, as well as Android.

The problem is the space in the calculated path to the file: `/var/mobile/Containers/Data/Application/C015FB8D-32BA-43FF-A518-DDA6B5A4F5EA/Library/Application Support/LiveSync/app/path-to-webview-content.html`, the space at `Application Support` breaks loading the content. Replacing it with `%20` fixes it.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.3
- Cross-platform modules: 3.0.1
- Runtime(s): tns-ios 3.0.1
- Plugin(s): n/a

### Please tell us how to recreate the issue in as much detail as possible.
Created a [minimal demo app](https://github.com/EddyVerbruggen/nativescript-webview-ios-local-file-issue/tree/master) with instructions.

### Fix
Submitted #4444

### Temporary workaround
Until the PR is merged and released you can load content like this (Angular-TypeScript example, but it the same idea for any stack):

```html
<WebView [src]="webViewSRC"></WebView>
```

```typescript
import * as fs from "tns-core-modules/file-system";

public webViewSRC: string = encodeURI(`${fs.knownFolders.currentApp().path}/path-to-webview-content.html`);
```

Once the issue is fixed you can replace that with:

```typescript
public webViewSRC: string = '~/path-to-webview-content.html';
```

**Comment by tsonevn** [comment]
Hi @EddyVerbruggen,
Thank you logging this issue and for the PR.
Indeed this is a real problem while loading a local file in WebView on iOS device.

**Comment by LSmint** [comment]
After added the fix, the problem still exist in the ios device when perform 'tns run ios'. But, the problem not exist if run from xcode project

**Comment by tsonevn** [comment]
Hi @LSmint,
Could you provide sample project, which demonstrates the issue and could be used for debugging?

**Comment by LSmint** [comment]
Hi @tsonevn,

Thank for your reply. I got the solution by removing the encodeURI then it works fine in mobile device!
