### ISSUE TITLE
Sass in NativeScript with angular for Component specific .scss

### ISSUE THREAD

**Issue by umeshrs** [NativeScript/NativeScript#4448]
I am trying to use nativescript-dev-sass plugin and it successfully creates ".css" files from within the app folder only (NOT Subfolders) in my project (app.scss -> app.css). But I want to use component specific css file. That is, inside "app" folder I have component folder "login" and it contains login.scss. (app -> login -> login.scss). login.css is not getting creating from login.scss.

Is it not possible to use it like this ? Should I add all my css into "app" folder and set the path to css right in all the components that I create ? Please help.

**Comment by NickIliev** [comment]
@umeshrs you should be able to use subfolders with nativescript-dev-sass. For reference, you can see how it is made in [this template](https://github.com/NativeScript/template-drawer-navigation-ng/tree/master/shared/my-drawer)

**Comment by umeshrs** [comment]
Thank you @NickIliev. It works for me now.
