### ISSUE TITLE
human-to human notifications

### ISSUE THREAD

**Issue by nelsonwilliam11** [NativeScript/NativeScript#4452]
am building Nativescript Angular app and looking for a way to implement users interaction notifications 
as in when someone start to follow you or a comment on a post etc 

need help ASAP thanks

**Comment by NickIliev** [comment]
@nelsonwilliam11 Please post a how-to related question in our community channels like [discourse.nativescript.org](https://discourse.nativescript.org/) or SO so we can keep the repo clean for logging issues, bugs and feature requests only.
