### ISSUE TITLE
htmlView font size

### ISSUE THREAD

**Issue by glorindel** [NativeScript/NativeScript#4455]
Is it possible to change font size in htmlView? because it isnt work in android for me, i can change font size but not size

I am using nativescript angular 3.0

**Comment by NickIliev** [comment]
@glorindel to modify any styles of your htmlView you will need to set them internally in the HTML view e.g. just like you would do in a plain HTML
```
'<span><font color="#ff0000">Test</font></span>';
```

Please post a how-to related question in our community channels like [discourse.nativescript.org](https://discourse.nativescript.org/) or SO so we can keep the repo clean for logging issues, bugs and feature requests only.

**Comment by Vo0Do0** [comment]
Hi @NickIliev,

I couldn't able to change the font size of the content inside htmlview in android. Here is my code snippet.
```
<HtmlView html="<span style='font-size: 15px;'><b><font color='blue' face='lato'>{{item.text}}
</font></b></span>" class="m-y-5" row="0" col="1" colSpan="2" isUserInteractionEnabled=false </HtmlView>
```
And if I change it to this:
```
<HtmlView html="<span><b><font size='10' color='blue' face='lato'>{{item.text}}
</font></b></span>" class="m-y-5" row="0" col="1" colSpan="2" isUserInteractionEnabled=false </HtmlView>
``` 
It doesn't work either.

Please help !

**Comment by Vo0Do0** [comment]
Hi @glorindel,

Can you tell me that how did you solve this?

Thanks,
