### ISSUE TITLE
XHR: 'Set-Cookie' vs 'set-cookie'

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [NativeScript/NativeScript#4456]
Hi there, in the latest `tns-core-modules` I noticed something very peculiar.
tns-core-modules/xhr/xhr.ts line 203, `set-cookie` and `set-cookie2` are excluded from the answer of `getAllResponseHeaders()`. Why these cookies are excluded, and `Set-Cookie` is not? And no, you should not exclude these cookies, because we can make our own cookie-jar entirely in App. Maybe the right way is only to exclude cookies that are marked as `HttpOnly`.

Regards,
Dragomir

**Comment by NickIliev** [comment]
@Dragomir-Ivanov indeed the support for cookies in XHR module is discussed here and is maerked as up-for-grabs which in the context of an open-source product like NativeScript means that we will greatly appreciate and welcome all [contributors](https://www.nativescript.org/contribute). Our priorities for the upcoming releases are not focused on the XHR module so the feature is still open for development and improvements.

Closing as related to [https://github.com/NativeScript/NativeScript/issues/2424](https://github.com/NativeScript/NativeScript/issues/2424)
