### ISSUE TITLE
Missing Feature appendFile on file-system

### ISSUE THREAD

**Issue by DrMabuse23** [NativeScript/NativeScript#4462]
Hello I am new to the Nativescript community and i have to say many thanks for this great Product. I miss the feature in the file system appendFile. I think it would be very helpful and a lot faster than file to read  and write.
Something like [android FileWriter](https://developer.android.com/reference/java/io/FileWriter.html#FileWriter) boolean append
maybe ios ?
[filehandle](https://developer.apple.com/documentation/foundation/filehandle/1416892-init)
sorry ios i cant handle the docs ..
Can this be done ?
Many Thanks

**Comment by NickIliev** [comment]
Hello @DrMabuse23 and thank you for your interest in NativeScript.

We have [file-system](https://docs.nativescript.org/cookbook/file-system) module which allows you to create and read from files and folders, work with paths and work with content data. There are very good example demonstrated [here ](https://docs.nativescript.org/cookbook/file-system#file-system)(NativeScript core) and [here ](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/file-system)(nativeScript Angular).

Indeed there is no append boolean flag, however, you can append any data to your file using[ the respective exposed methods](https://docs.nativescript.org/api-reference/classes/_file_system_.file.html).

Of course, if you think that this is a good candidate for a feature, we will be more than happy to accept contributors (as NativeScript is an open-source product everyone can [become a contributor](https://www.nativescript.org/contribute)).

**Comment by EddyVerbruggen** [comment]
@DrMabuse23 If you need to read/write text only, you can try something similar to [this](https://github.com/EddyVerbruggen/nativescript-node/blob/dc93ab48a84c410bc8d6f46527fb171799f8bfeb/fs.js#L233-L254).
