### ISSUE TITLE
To create a file and write the contents in it locally using angular2

### ISSUE THREAD

**Issue by kalai4013** [NativeScript/NativeScript#4465]
Hi,

I need to log the entries of the user in a .txt file and save it in my local system through angular2.
I have tried using fs module, but it doesn't workout. So can anyone help me with any example to create and write file thru angular2 in my local? Please help. Thanks in advance.

**My Code:**
import * as fs from "file-system';
var documents = fs.knownFolders.documents();
var path = fs.path.join(documents.path, "FileFromPath.txt");
var file = fs.File.fromPath(path);
file.writeText("Something")
    .then(function () {
        // Succeeded writing to the file.
    }, function (error) {
        // Failed to write to the file.
    });

**Error I received in browser(Chrome):**
ERROR TypeError: Cannot read property 'documents' of undefined
    at NewBoxComponent.webpackJsonp.../../../../../src/app/scan/new-box/new-box.component.ts.NewBoxComponent.writeFile (new-box.component.ts:623)
    at Object.eval [as handleEvent] (NewBoxComponent.html:72)
    at handleEvent (core.es5.js:12076)
    at callWithDebugContext (core.es5.js:13535)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:13123)
    at dispatchEvent (core.es5.js:8688)
    at core.es5.js:9299
    at HTMLDivElement.<anonymous> (platform-browser.es5.js:2668)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424)
    at Object.onInvokeTask (core.es5.js:3924)

**package.json**
 "devDependencies": {
    "@angular/cli": "^1.1.1",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "2.5.45",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3",
    "fs-extra":"2.1.2"
  }

**Comment by DrMabuse23** [comment]
Hey i can show how i read my local files :
```js
import { Observer } from 'rxjs/Observer';
import 'rxjs/Rx';
import * as fs from "file-system";
import { Http } from '@angular/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { knownFolders, File, Folder } from "file-system";

let documents = knownFolders.currentApp();
// const de_DE = require('./../../assets/i18n/de-DE');
// const en_IN = require('./../../assets/i18n/en-IN');


class FileReader {
  public static readJSON(folder: string, file: string, language: string): Observable<{data: any, language: string}> {
    
    if (!Folder.exists(documents.path + '/' + folder)) {
      return Observable.throw(`Folder not exist ${documents.path + '/' + folder}`);
    }
    const _folder = documents.getFolder(folder);
    
    if (!File.exists(documents.path + '/' + folder + '/' + file)) {
      return Observable.throw(`File not exist ${_folder.path}`);
    }
    let jsonFile = _folder.getFile(file); 
    return Observable.fromPromise(jsonFile.readText())
      .map((content) => {
        return {data: JSON.parse(content), language: language};
      });
  }
}

@Injectable()
export class I18nProvider {
  public assetPath = 'assets/i18n';
  public activeLanguage: string = 'de-DE';
  public dict: { [key: string]: { [key: string]: string } } = {

  };
  public defaultLanguages = ['en-IN', 'de-DE'];

  constructor(public http: Http) {
    this.loadDict().subscribe(() => console.log(this.dict));
  }

  loadDict() {
    const source = Observable
      .from(this.defaultLanguages)
      .concatMap((language) => FileReader.readJSON(`${this.assetPath}`,`${language}.json`, language));

    return source
      .map((data) => {
        if (!this.dict) {
          this.dict = {
            [data.language]: data.data
          }
        } else  {
          this.dict[data.language] = data.data;
        }
        console.dir(this.dict[data.language]);
      })
      .do(() => console.log('dict', this.dict));
  }

  changeActiveLanguage(langKey) {
    if (this.defaultLanguages.indexOf(langKey) === -1) {
      throw Error(`key is not available please choose one of ${this.defaultLanguages.toString()}`);
    }
    this.activeLanguage = langKey;
  }
}

```
maybe its usefull for you

**Comment by kalai4013** [comment]
Thanks. But, Getting below error while compiling.
Line of Code: 
let jsonFile = _folder.getFile(file); 
    return Observable.fromPromise(jsonFile.readText())
      .map((content) => {
        return {data: JSON.parse(**content**), language: language};
      });

ERROR in D:/Angular4.2/RDSApp/src/app/scan/new-box/new-box.component.ts (50,34):
 Argument of type '{}' is not assignable to parameter of type 'string'.

**Comment by NickIliev** [comment]
@kalai4013 the error indicates that you need to change the Type from object to string for that argument that you have on that specific line.

Apart from the solution provided by @DrMabuse23, you should be also able to use file-system with no hassle (for example as shown [here](https://github.com/NativeScript/NativeScript/issues/3463#issuecomment-271816990)) or [here(Angular)](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/file-system/create/create.component.ts#L22-L40)

Please post a similar how-to related question in our community channels so we can keep the repository strictly for login issues, bugs, and feature requests.
