### ISSUE TITLE
TNS 3.1 android Navigation Error

### ISSUE THREAD

**Issue by harriscreativity** [NativeScript/NativeScript#4475]
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property '0' of undefined
JS: TypeError: Cannot read property '0' of undefined
JS:     at new HomeComponent (file:///data/data/org.nativescript.sadcdirectory/files/app/pages/home/home.component.js:19:39)
JS:     at createClass (file:///data/data/org.nativescript.sadcdirectory/files/app/tns_modules/@angular/core/bundles/core.umd.js:10905:26)
JS:     at createDirectiveInstance (file:///data/data/org.nativescript.sadcdirectory/files/app/tns_modules/@angular/core/bundles/core.umd.
js:10730:37)
JS:     at createViewNodes (file:///data/data/org.nativescript.sadcdirectory/files/app/tns_modules/@angular/core/bundles/core.umd.js:12093
:49)
JS:     at createRootView (file:///data/data/org.nativescript.sadcdirectory/files/app/tns_modules/@angular/core/bundles/core.umd.js:11998:
5)
JS:     at callWithDebugContext (file:///data/data/org.nativescript.sadcdirectory/files/app/tns_modules/@angular/core/bundles/core.umd.js:
13213:42)
JS:     at Object.debugCreateRootView [as createRootView] (file:///data/data/org.nativescript.sadcdirectory/files/app/tns_modules/@angular
/core/bundles/core.umd.js:12673:12)
JS:     at ComponentFactory_.create (file:///data/data/org.nativescript.sadcdirectory/files/app/tns_modules/@angular/core/bundles/core.umd
.js:9919:46)
JS:     at ComponentFactoryBoundToModule.create (file:///data/data/org.nativescript.sadcdirectory/files/app/tns_modules/@angular/core/bund
les/core.umd.js:3455:29)
JS:     at ViewContainerRef_.createComponent (file:///data/data/org.nativescript.sadcdirectory/files/app/tns_modules/@angular/core/bundles
/core.umd.js:10121:62)
JS:     at DetachedLoader.loadWithFactory (file:///data/data/org.nativescript.sadcdirectory/files/app/tns_modules/nativescript-angular/com
mon/detached-loader.js:38:34)
JS:     at PageRouterOutlet.activateOnGoForward (file:///data/data/org.nativescript.sadcdirectory/files/app/tns_modules/nativescript-angul
ar/router/page-router-outlet.js:168:60)
JS:     at PageRouterOutlet.activateWith (file:///data/data/org.nativescript.sadcdirectory/files/app/tns_modules/nativescript-angular/rout
er/page-router-outlet.js:140:18)
JS:     at ActivateRoutes.placeComponentIntoOutlet (file:///data/data/org.nativescript.sadcdirectory/files/app/tns_modules/@angular/router
/bundles/router.umd.js:4526:16)
JS:     at ActivateRoutes.activateRoutes (file:///data/data/org.nativescript.sadcdirectory/files/app/tns_modules/@angular/router/bundles/r
outer.umd.js:4507:26)

**Comment by NickIliev** [comment]
@harriscreativity please provide as much as possible information on how to reproduce this error.

**Comment by harriscreativity** [comment]
What do  u mean

**Comment by NickIliev** [comment]
@harriscreativity 
Simply posting the error log is not enough. In order to investigate potential issue we need the actual code that caused the error log including both the code-behind file and the layout files. We also need the `package.json` content so we can reproduce the case using the exact same versioning as in your project.
The basic rule of thumbs when posting new issue is as follows:


> ### Tell us about the problem
> Please, ensure your title is less than 63 characters long and starts with a capital
> letter.
> ### Which platform(s) does your issue occur on?
> iOS/Android/Both
> 
> ### Please provide the following version numbers that your issue occurs with:
> - CLI: (run `tns --version` to fetch it)
> - Cross-platform modules: (check the 'version' attribute in the
> `node_modules/tns-core-modules/package.json` file in your project)
> - Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
> `package.json` file of your project)
> - Plugin(s): (look for the version number in the `package.json` file of your
> project)
> 
> ### Please tell us how to recreate the issue in as much detail as possible.
> 
> ### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
>
