### ISSUE TITLE
Chrome Developer Tools - Modal View Tree

### ISSUE THREAD

**Issue by jericdeleon** [NativeScript/NativeScript#4480]
Just upgraded to 3.1, congratulations on the great work guys!  💯 
Tried the debug feature and I can view the page markup nicely :)

But do you guys know if it's possible to inspect the view tree of a Modal, shown through ModalDialogService.showModal() (and how)?

**Comment by vakrilov** [comment]
Currently, modals will not be visible in the devtools.
It is something we should implement additionally.

**Comment by jericdeleon** [comment]
Closing due to age / not working with Nativescript recently.
