### ISSUE TITLE
Command gradlew.bat

### ISSUE THREAD

**Issue by ALoubna** [NativeScript/NativeScript#4487]
while I'm executing my Android app I get this Error on the CLI "Unable to apply changes on device: emulator-555. Error is:Command gradlew.bat failed with exit code 1".
if anyone can help,please.

**Comment by dtopuzov** [comment]
Hi @ALoubna 

Can you please provide:
- exact steps to reproduce
- OS type and version
- npm and node versions
- CLI version
- package.json of your application

Can you reproduce the issue with hello-world project?

**Comment by NickIliev** [comment]
@ALoubna we haven't heard from you for a while - were you able to resolve your issue?
If not please provide the information requested in the post above so we could test it at our side
