### ISSUE TITLE
Allow the modules to consume iOS images with app thinning

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#449]
[iOS 9 app thinning allows images to be ordered in asset catalogs](https://developer.apple.com/library/prerelease/watchos/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html). Then when the app is submitted on the AppStore, the store will apply app thinning and will deliver only the images relevant for the client's device.

For example you can create a catalog with an image, and add one high resolution for tablets and one with small resolution for phones. The App used to bundle and deliver both images to phones and tablets, but now it will strip the phone image when it delivers the app for a tablet and the vice-versa.

Make sure the modules can work with such images.

**Comment by fealebenpae** [comment]
This can work with all kinds of assets as well, so potentially .xml layouts and .css styles might also benefit from participating in slicing.

**Comment by PanayotCankov** [comment]
:+1: @fealebenpae

**Comment by enchev** [comment]
This is already supported by the modules (App_Resources).
