### ISSUE TITLE
Memory Leak on iOS since tns-ios 3.0.0

### ISSUE THREAD

**Issue by EddyVerbruggen** [NativeScript/NativeScript#4490]
### Tell us about the problem
The image below is [this app](https://github.com/EddyVerbruggen/nativescript-ios-out-of-memory) (shown on the left) going back and forth between a homepage and a page with a listview. Back-navigation doesn't clear the memory of the listview (inspecting the heap it mostly looks like retained labels, but I find it very hard to interpret):

<img width="1333" alt="172loops" src="https://user-images.githubusercontent.com/1426370/27773016-a3cc3c64-5f6f-11e7-84cc-86e2ae3190b2.png">

Note this is a screenshot of the app after going back and forth exactly 172 times (as shown in the app's screenshot), and the blue graph on the right is Xcode reporting the heap size over time. As you can see it's growing with every visit of the listview.

### Q. Dude, this is artificial!
A. While this may seem very artificial, I actually created this app to demonstrate a problem I saw in a real app. The app crashes after about 20 minutes of usage on an iPad Air (1GB RAM). It has lots more graphics and styling than this demo, so I had to add a lot of labels and automated navigation to reach the same level of memory pressure my app has. The problem with both apps is exactly the same: **memory is retained. Forever. Until the app crashes.**

### Which platform(s) does your issue occur on?
iOS (didn't check Android)

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.1.0
- Cross-platform modules: 3.1.0
- Runtime(s): tns-ios 3.0.0 and 3.1.0 (same issue)
- Plugin(s): n/a

### Please tell us how to recreate the issue in as much detail as possible.
Follow the instruction in the ["Fully automated {N} Out Of Memory Crash App"](https://github.com/EddyVerbruggen/nativescript-ios-out-of-memory). It's based on [this template](https://github.com/NativeScript/template-hello-world-ng).

I hope this app will help in identifying and verifying possible solutions. I've tried a few my own, but there are a few internal classes in the runtime I can't inspect so my hands are a bit tied in this case.

Thanks for any feedback you have in advance,
Eddy

**Comment by EddyVerbruggen** [comment]
I just tested [the demo app](https://github.com/EddyVerbruggen/nativescript-ios-out-of-memory) with [this `tns-ios` line](https://github.com/EddyVerbruggen/nativescript-ios-out-of-memory/blob/5152633ec4bf7087b210454d79f1ffc11bca1216/package.json#L9) changed to 2.5.0 and that produced a nice flat memory graph - so the issue was introduced with 3.x

Here's 2.5.0 after 100 loops and GC (tns-ios 3.0.0 and 3.1.0 consume 430 MB after GC):

<img width="1336" alt="screen shot 2017-07-04 at 15 18 53" src="https://user-images.githubusercontent.com/1426370/27831705-2239701e-60cc-11e7-80d0-a1a0095514db.png">

**Comment by pawel-filuciak** [comment]
I am facing very the same problem as described above.
Target milestone is 3.2 which is planned for August - too long for me, is it possible to fix it before, I see it as a high priority bug.
Is downgrade to 2.5.x recommended workaround?
Any other suggestions?

**Comment by PanayotCankov** [comment]
It is easily reproduced with this project:
https://github.com/EddyVerbruggen/nativescript-ios-out-of-memory

You can track leaked native objects following:

Start the debugging in Xcode and transfer to instruments, in “All Heap & Anonymous VM” at the bottom there is a “Mark Generation” you can click it, then “Loop 10x” then click “Collect Garbage” then again “Mark Generation” this leaves about 15Mb growth in gen2. 7MiB CFString (immutable) and & 7MiB in malloc_zone_malloc that is in UINavigationBar popNavigationItem then CALayer setAffineTransform.

**Comment by PanayotCankov** [comment]
> Just to add: I'm receiving more and more crash reports from beta testers through TestFlight. Until now it only happens on older devices with 1 GB RAM (iPad 3 for instance). Perhaps only once on an iPhone 7, but the TestFlight crash reports are often pretty useless.
This particular app is meant to be used and depends on going back and forth between (long) lists a lot so it's quite sensitive to this issue.

Eddy,

**Comment by sean-perkins** [comment]
Any update on this issue? We are also running into a similar issue with our production app using NativeScript. Our app will continue to allocate memory; starting at ~150mb to well over 500mb within minutes of navigating throughout the application.

**Comment by patrickpereira** [comment]
+1

**Comment by NickIliev** [comment]
+1 from [https://github.com/NativeScript/NativeScript/issues/4700](https://github.com/NativeScript/NativeScript/issues/4700) and from t1125793

**Comment by triniwiz** [comment]
+1

**Comment by zf8848** [comment]
+1

**Comment by ivanbuhov** [comment]
I found a memory leak in the iOS Runtime introduced in 3.0. [This PR](https://github.com/NativeScript/ios-runtime/pull/790) fixes the leak and makes the Xcode memory debugger to print no errors in a blank application.

However, some leaks are still reported in the Leak tool in instruments. After inspecting the call stack when the leaked memory is allocated, it seems that the Xcode Instruments consider the memory allocated [here](https://github.com/NativeScript/ios-runtime/blob/master/src/NativeScript/Calling/FFICall.cpp#L34) and [here](https://github.com/NativeScript/ios-runtime/blob/master/src/NativeScript/Calling/FFICall.cpp#L50) as leaked. Actually, this memory is owned by the `FFICall` instance and is [deallocated in its destructor](https://github.com/NativeScript/ios-runtime/blob/master/src/NativeScript/Calling/FFICall.cpp#L69-L70). However, most of the `FFICall` objects are never destructed (which is expected and desired behavior) and the memory is never deallocated (which is expected, too). It seems that this makes the Instruments to treat the memory as leaked, even it is not.

Initially, I thought that the usage of `new` is what makes the Instruments tools to treat the memory as leaked, but even after refactoring the code to avoid the usage of `new` operator and replacing it with `unique_ptr` and `std::vector` objects saved as an instance variable (following the [RAII technique](http://en.cppreference.com/w/cpp/language/raii)), the allocations are still treated as memory leaks, even if they are not.

P.S.: I haven't investigated the `tns-core-modules` and [the example app](https://github.com/EddyVerbruggen/nativescript-ios-out-of-memory) for existing memory leaks in their codebase. My main focused was the iOS Runtime.

**Comment by EddyVerbruggen** [comment]
@ivanbuhov That's great news! I will be more than happy to run the example app (and my real app which suffers from this issue) with your PR included. Is there a way for me to "easily" grab a patched version?

**Comment by hshristov** [comment]
@EddyVerbruggen just install `tns platform add ios@next` or use `next` without @ in the package.json

**Comment by EddyVerbruggen** [comment]
@ivanbuhov Tears of joy in my eyes - this seems to fix it indeed! Will update this comment in a few minutes when my complete testrun (before and after upgrading tns-ios) is finished.

**Comment by triniwiz** [comment]
Great news 😃

**Comment by NathanWalker** [comment]
This is awesome :tada:

**Comment by reposooo** [comment]
Should be reopened in {N}-angular 5.0.0 
we have blocker 
a lot of memory leaks on ios that cause crash, i have run "Loop 10x" once on device (iPhone 7 Plus)
![image](https://user-images.githubusercontent.com/2729175/48919260-b7c42d80-eea2-11e8-9672-6fa64ca5be1d.png)
