### ISSUE TITLE
How to obfuscated asset folder in android apk using nativescript (platforms/android/asset )

### ISSUE THREAD

**Issue by priyangamani** [NativeScript/NativeScript#4492]
progaurd does not obfusticate the asset folder. I have a .apk file of my application created using nativescript. I want to know how to prevent my code being seen by anyone who gets my apk so that a person can use it but not be able to see the code. Due to client specific requirements It is not distributed via website or playstore etc. But since the app is in nativescript of the code is in xml and js which I can see just by opening the apk file.

**Comment by NickIliev** [comment]
@priyangamani you can use [WebPack with uglify](https://docs.nativescript.org/best-practices/bundling-with-webpack#advanced-optimizations)

**Comment by NathanaelA** [comment]
@priyangamani  - https://AppProtection.net

**Comment by priyangamani** [comment]
**This was my error(By using Nativescript-AppProtection)**

D:\Sample\platforms\android\src\main\java\com\tns\RuntimeHe
lper.java:57: error: package com.tns.app_protection does not exist
com.tns.app_protection.AppProtection.setKey("qyUMQZhu43KByppjVJFJyRxVG+PZaRAHId2
+mczHiwo=");
^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:compileF0F1F2F3F4F5F6F7F8F9F10F11F12F13F14F15F16ReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

    What went wrong:
    Execution failed for task ':compileF0F1F2F3F4F5F6F7F8F9F10F11F12F13F14F15F16Rele
    aseJavaWithJavac'.

    Compilation failed; see the compiler error output for details.

    Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug
    option to get more log output.

BUILD FAILED
