### ISSUE TITLE
Custom fonts acting weird on iOS with 2.5.3

### ISSUE THREAD

**Issue by spike1292** [NativeScript/NativeScript#4497]
Hi Guys, 

After this weekend our custom fonts are acting weird on iOS. After some investigation we found out that there is a new tns-core-modules version 2.5.3. 
In our `package.json` we have `"tns-core-modules": "~2.5.2"` and because of the tilde it was updated automatically to 2.5.3. This release broke our application and we spend a lot of time to figure out what went wrong. 

I'm curious what was changed and why version 2.5.3 broke our application. 
But I could not find an issue, pull request, changelog or git tag related to 2.5.3 except for this branch https://github.com/NativeScript/NativeScript/commits/font-weight-fixes-2.5
So I'm left with two questions:
- What changed in 2.5.3 ?
- Why is this release not documented?

Kind regards,
Henk Bakker

**Comment by spike1292** [comment]
Here are some screenshots which demonstrate the problem:
Correct font: 
![iphone6_10 3](https://user-images.githubusercontent.com/288597/27826430-3eeeaf26-60b3-11e7-96c5-7ea763cec6e8.png)
After 2.5.3 upgrade:
![iphone](https://user-images.githubusercontent.com/288597/27826429-3ecc5a20-60b3-11e7-9c50-90414f866ad9.png)

**Comment by NickIliev** [comment]
@spike1292 do you have any CSS styles applied to your custom font like font-weight?
Is the custom font available for test (if so please share its name with us so we can test on our side)

**Comment by NickIliev** [comment]
@spike1292 with NativeScript 2.5.3 we have introduced [this fix](https://github.com/NativeScript/NativeScript/issues/4342) - we 've just updated the release notes via [this PR](https://github.com/NativeScript/NativeScript/pull/4509). 
However, I am still trying to reproduce the issue you are experiencing so any additional information would be useful (e.g. the used font and any CSS styles applied to it)

**Comment by spike1292** [comment]
@NickIliev tnx for the feedback! I have created an example repo https://github.com/Essent/font-issue-2.5.3.
While working on this example and looking into to the mentioned issue I think I found a solution: adding `font-weight: 800` to css. 
This was functionality which would not work before, as mentioned in the issue. So we never added it any where in our application.

**Comment by NickIliev** [comment]
@spike1292 indeed this was the main reason to introduce the fix so that `font-weight` property can work on iOS - is this acceptible for your application (meaning not causing any side effects when `font-weight` is applied)?
