### ISSUE TITLE
'Property<T, U>' has no properties in common with type 'TypedPropertyDescriptor<U>

### ISSUE THREAD

**Issue by Robophil** [NativeScript/NativeScript#4498]
Hi guys,

when trying to compile my typescript file, I get to see this error.
```bash
node_modules/tns-core-modules/ui/core/properties/properties.d.ts(48,14): error TS2559: Type 'Property<T, U>' has no properties
in common with type 'TypedPropertyDescriptor<U>'.
```

following through on this error, and implementing one of the method decleared in this interface `TypedPropertyDescriptor<U>` in `Property<T, U>` the error goes away and I'm able to compile successfully.

```typescript
interface TypedPropertyDescriptor<T> {
    enumerable?: boolean;
    configurable?: boolean;
    writable?: boolean;
    value?: T;
    get?: () => T;
    set?: (value: T) => void;
}
```

```typescript
export class Property<T extends ViewBase, U> implements TypedPropertyDescriptor<U> {
    constructor(options: PropertyOptions<T, U>);

    public readonly getDefault: symbol;
    public readonly setNative: symbol;
    public readonly defaultValue: U;
    public register(cls: { prototype: T }): void;
    public nativeValueChange(T, U): void;
    public isSet(instance: T): boolean;
}
```

Can this be fixed, i'll rather not have to do this (edit) in my `node_modules/tns-core-modules/ui/core/properties/properties.d.ts` file.

**Comment by NickIliev** [comment]
The error you are hitting is most likely caused by a mismatch of your TypeScript version and the version of a package like `rxjs`. If you are using TypeScript 2.4.1 you might try to downgrade to 2.4.0 or 2.3.4. More information [here](https://github.com/Microsoft/TypeScript/issues/16593) and [here](https://stackoverflow.com/a/44858294/4936697).

Once you downgrade the version of your TypeScript, remove `node_modules` and rebuild your project. Let me know if that resolved your issue.

**Comment by Robophil** [comment]
Thanks @NickIliev, i'll give it a try

**Comment by sugendran** [comment]
BTW, setting the compiler option `noStrictGenericChecks` in your tsconfig.json will let it compile.

**Comment by jarrodchesney** [comment]
@sugendran  Setting noStrictGenericChecks didn't work for me. I've checked it, and checked it, and it doesn't work.

```
{
    "strictNullChecks": true,
    "allowUnreachableCode": true,
    "compilerOptions": {
        "declaration": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "noStrictGenericChecks": true,
        "noEmitOnError": true,
        "moduleResolution": "node",
        "baseUrl": ".",
        "module": "commonjs",
        "target": "es5",
        "typeRoots": [
            "./node_modules/@types"
        ],
        "types": [
            "moment"
        ],
        "lib": [
            "es6",
            "dom",
            "es2015.iterable"
        ],
        "paths": {
            "~/*": [
                "./app/*"
            ],
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms",
        "**/main.aot.ts"
    ]
}
```

**Comment by jarrodchesney** [comment]
I worked around the problem by installing typescript 2.3.4 as mentioned above, but i needed to use "2.3.4" not ~ or ^

`npm install --saveDev typescript@2.3.4`

The project then built with this typescript

**Comment by DCleymans** [comment]
I have the same error. The noStrictGenericChecks flag does not solve the problem.

tns info:

    ┌──────────────────┬─────────────────┬────────────────┬───────────────┐
    │ Component        │ Current version │ Latest version │ Information   │
    │ nativescript     │ 3.1.3           │ 3.1.3          │ Up to date    │
    │ tns-core-modules │ 3.1.0           │ 3.1.0          │ Up to date    │
    │ tns-android      │                 │ 3.1.1          │ Not installed │
    │ tns-ios          │ 3.1.0           │ 3.1.0          │ Up to date    │
    └──────────────────┴─────────────────┴────────────────┴───────────────┘

npm list typescript:

    typescript@2.4.1

npm list tns-core-modules:

    tns-core-modules@3.1.0

I want to use typescript 2.4.x for the string enumerations.

**Comment by adamauckland** [comment]
@DCleymans did you ever resolve this? I've got the same problem, I need TypeScript 2.4 for string enums but it breaks tns-core-modules and tns-platform-declarations.

**Comment by bmargevicius** [comment]
adding  "skipLibCheck": true, to tsconfig helped me get it to build.

 "compilerOptions": {      
        "skipLibCheck": true,

**Comment by musasesay** [comment]
[ts] Type 'typeof HomePage' has no properties in common with type 'Component'.
(property) Menu.homePage: Component

![Uploading image.png…]()

**Comment by musasesay** [comment]
| constructor(public navCtrl: NavController, public navParams: NavParams) {
-- | --
  | this.homePage = HomePage
  | this.categories=[];
