### ISSUE TITLE
'background-image' property options

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#45]
_From @MiroValchev on April 23, 2015 14:1_

We need to be able to set options to the css 'background-image' property - for example no-repeat.

_Copied from original issue: NativeScript/cross-platform-modules#312_

**Comment by enchev** [comment]
We plan to add support for [background-repeat](http://www.w3schools.com/cssref/pr_background-repeat.asp)

**Comment by bundyo** [comment]
I wonder if data-URI support is also possible/planned?

**Comment by enchev** [comment]
Hey @bundyo,

We already support[ url | local_file_path for this](https://github.com/NativeScript/sample-TelerikNEXT/blob/master/app/app.android.css#L61)

@MiroValchev  I'm closing this issue. Please use #191 instead.

**Comment by bundyo** [comment]
I know that :) I was asking about [data-URIs](https://developer.mozilla.org/en-US/docs/Web/HTTP/data_URIs).

**Comment by enchev** [comment]
https://github.com/NativeScript/NativeScript/commit/949b3195605dbc93287fee46a066bdc058c93b2d
