### ISSUE TITLE
APK file size 

### ISSUE THREAD

**Issue by ZeroHackeR** [NativeScript/NativeScript#450]
Dear all,

We are researching to use NativeScript for our next production apps.
However, we noticed that the APK file size is quite huge for a small project like default hello-world.
6.41 MB for such small project is considerable large.

I'd love to know why is so large as my understanding was there were no wrappers and js were directly complied to native code?

Is this because of all modules (used/unused) were included?
If so, is there any option to remove unused modules while compiling to make the file size smaller?

**Comment by valentinstoychev** [comment]
Hello @ZeroHackeR, 6.4 Mb is the apk size for both platforms. If the APK size is a concern for you - you can [upload separate apk packages](http://developer.android.com/google/play/publishing/multiple-apks.html) and the app size will be around 3-4Mb.

The main thing to note here is that as the projects get bigger the app size will depend only on what resources *you* are adding to the app. The number of native APIs will *not* affect the APK size.

*What APK size you would consider to be OK for your needs?*

Please also note that the JS code is **not** compiled to native code. It is being executed at runtime by the JS VM. The UI of the application however is being done with the native UI elements, so only the business logic is interpreted at runtime.

To learn more about how NativeScript works please read [this blog post](http://developer.telerik.com/featured/nativescript-works/).

**Comment by ZeroHackeR** [comment]
Thanks Valentin!

You meant both ARM and x86 versions were included?

3.4mb is better than 6.8mb. But, the default hello-world example does not
contain any resources. It has just a couple of small JS files. So that
reason, 3.4 mb is still big.

So, nativescript added some kind of overhead?

Again, yesterday I also tested the nativescript and I found it difficult to
work with compare to xamarin or android studio. We would need drag and drop
UI designer or at least some ways to preview the UI without compiling the
app every time. Again, debugging is not so easy. A missing image made my
app crashed at launch. And there were no proper error message or might be I
didnt know where to read.

As a developer, I was so excited and thought I could just switch to
nativescript. But, I think, at this very moment, I felt like... its not
there yet. Or, am I missing something?

**Comment by valentinstoychev** [comment]
Thank you for taking time to send your feedback! NativeScript is still new and such feedback helps a ton!

Please see my replies below. Please try with these instructions and let me know again if you hit another issue. BTW - **I will be useful for us if you elaborate more on the app size concerns**. What is the reason to ask for smaller package size? Do you have a particular requirement?

Re: *You meant both ARM and x86 versions were included?*
Yes - both ARM and x86 versions are included.

Re: *So, nativescript added some kind of overhead?*
Yes. We need to ship our framework as part of the APK package. These 3.4Mb is the size of the runtime + some small assets that we are shipping as part of the package. This includes the V8 engine and our implementation on top of it. You can't go smaller than this size at the moment.

Re: *We would need drag and drop
UI designer or at least some ways to preview the UI without compiling the
app every time*
With the release next week we are adding the LiveSync capability which will allow you to sync only the changed files without the need to recompile. The issue for this is [here](https://github.com/NativeScript/nativescript-cli/issues/523) and you will be able to use it next week. This will wastly improve the development experience.
Also as part of our paid tooling in [Telerik Platform](www.telerik.com/platform) you can find a designer for NativeScript called Screen Builder. It is still in its infancy but it will mature in the following months.

Re: *Again, debugging is not so easy.*
Have you tried using the debugging tools? You will need to run the application with the ```tns debug``` [command](http://docs.nativescript.org/runtimes/android/debug/debug-cli) to make sure that you will hit breakpoints and to show the debugger when an exception is raised.

Greetings!

**Comment by ZeroHackeR** [comment]
Hi again Valentine,

I'm glad that my feedback helps
Thanks for your answers. They cleared a lot of my doubts. :) 

The App size does concern me, because I'm from a country (Myanmar) where the internet speed is not so reliable and every Mb counts for us. But, I think, less than 5Mb overhead should be fine. 

Screen Builder is awesome. But, again, I think, Screen Builder should also be open-sourced or free to attract more developers towards NativeScript. Now, hand-coding XML is like "we went backwards 20 years". Not so productive. 

For most of our server side projects, we already moved to NodeJS from PHP and ASP.net. I'm hoping to do the same with NatvieScript for App development. 

I will try NatvieScript again this weekends and I'll feedback you again! 

have a great weekends!

**Comment by valentinstoychev** [comment]
Thanks @ZeroHackeR for sharing the additional details. Please let us know how we can help you further, we are eager to see you writing NativeScript code and we are here to help! :)

**Comment by rizkyramadhan** [comment]
How do i separate ARM & x86 build ?

**Comment by adalbertojoco** [comment]
This app oversize broke my heart, my app needs to be update once/twice a month in +18.000 installs, my app size now with JQM is less than 1MB. But unfortunatelly JQM is dying and I need look another option out there. I will try NS again if the others FWs are this big.

**Comment by NathanaelA** [comment]
@adalbertojoco -- You do realize that if the update is just to the JS code; you can either write your own update code plugin; or use an existing plugin that will do it.   The plugin I have written allows you to update the code at any point and the download size is only a couple KB of space.   Only the initial install that has all the compiled run-times needs to be large.  ;-D

**Comment by adalbertojoco** [comment]
I need update data (bus schedule), but nice know about your plugin. If I can update data NS is the clear choice, I love it.

**Comment by NathanaelA** [comment]
If all you are doing is updating data; you can just use an HTTP call to your own server and pull down the latest schedules without having to update your app.

**Comment by adalbertojoco** [comment]
My app is offline, generally the users do update at home/public wifi, another kind of cell phone connection in Brazil are terrible at this time.

**Comment by NathanaelA** [comment]
I figured it was offline; what I'm saying is that when the user connects to the wifi the update is just a simple data update from your server.  The amount of data transferred should be minimal and then stored on the phone.   This is way better than making them update the app from the app store.  The data transfer should only be a couple kb of data...

**Comment by adalbertojoco** [comment]
I will research/try this approach once again, no lucky so far, isn't easily available like it sounds like.

**Comment by NathanaelA** [comment]
The http & fetch modules are built into NativeScript. 
http://docs.nativescript.org/ApiReference/fetch/HOW-TO
So all you need to do is something like:
'''
fetch(someSiteUrl).then(function(data) { // do something with the data });
'''
It is pretty simple.

**Comment by adalbertojoco** [comment]
Thank you NathanaelA, I will follow your advices about update and stick with NS, the love is back to my heart :)

**Comment by calebeaires** [comment]
Someone discover how to separate ARM & x86 build so the NativeScript APK goes smaller?

**Comment by NathanaelA** [comment]
Actually their is a couple way to do it.   But none of them are automated at this point.  
See: https://github.com/NativeScript/nativescript-cli/issues/1392 for the bug that is now tracking this feature request.   The APK size has actually grown another third in v1.6, as now THREE runtimes are included instead of just two.

**Comment by PanayotCankov** [comment]
We had an issue in the "Examples NativeScript". The fresco plugin we use had 64 bit binaries while the runtime did no. We had to remove the 64 bit slice of fresco and it appeared the easiest way was to actually get the APK, open with zip, delete the unwanted .so files, delete the META-INF, then save the zip, align and resign. The so created APK indicated that there are no 64 bit binaries when uploaded in the Play Store. So it should be possible to manually create 3 versions (with the same versionName but sequential versionCodes) and upload all 3 at the Play Store. When downloaded on a device the Play Store will pick the right one for your device.

It is similar to the [steps here](http://stackoverflow.com/questions/7119839/re-sign-an-android-apk) but also the unwanted archs were deleted.

On the other hand when we added 64bit build of the runtime, the app is about 44MB, 3/4 of it are images.

**Comment by cho-is** [comment]
I am afraid that the hello-world is now 12.3MB

**Comment by alvirtuoso** [comment]
Does that mean If I were to install the hello-world app in my phone, it will be 12.3MM download & install?

**Comment by lawrencetaur** [comment]
Suggestion: allow us to build without a certain runtime if we do not want to support x86. 

Example: tns build android --x86=off 

inspired by https://easyengine.io/docs/commands/site/create/

**Comment by alexrainman** [comment]
Well, I'm just trying to release Android today and I'm getting a 155 MB app size with this command

```
tns build android --release --key-store-path <path-to-your-keystore> --key-store-password <your-key-store-password> --key-store-alias <your-alias-name> --key-store-alias-password <your-alias-password>
```

**Comment by valentinstoychev** [comment]
Is this the size of the apk? What are the biggest artefacts in the package? This is not normal.

**Comment by alexrainman** [comment]
Nothing there. Just creating apk that contains one page and "under dev" MobileIron plugin that has small aar that is only a few KB.

**Comment by alexrainman** [comment]
Even debug mode is 155 MB.

**Comment by alexrainman** [comment]
This is how my package looks like

```
{
  "nativescript": {
    "id": "org.nativescript.demo",
    "tns-ios": {
      "version": "2.3.0"
    },
    "tns-android": {
      "version": "2.4.1"
    }
  },
  "dependencies": {
    "nativescript-nsappconnect": "file:..",
    "nativescript-unit-test-runner": "^0.3.0",
    "tns-core-modules": "^2.3.0"
  },
  "devDependencies": {
    "babel-traverse": "6.12.0",
    "babel-types": "6.11.1",
    "babylon": "6.8.4",
    "filewalker": "0.1.2",
    "jasmine-core": "^2.5.2",
    "karma": "^1.3.0",
    "karma-jasmine": "^1.0.2",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^2.0.7"
  }
}
```

**Comment by alexrainman** [comment]
I found the problem. The plugin seed was copying a TEMP folder and it was included in the app build 👍

**Comment by upender-devulapally** [comment]
@alexrainman I am also facing the same issue with app size, can you please let me know which plugin it is ?how do you  resolve it?.. still I didn't get 
|| The plugin seed was copying a TEMP folder

**Comment by farsix** [comment]
@upender-devulapally every apk is a zip file rename it to *.zip and then extract to a folder, you can check what is included in your app that is not necessary. but if you really care about app size you can check ionic framework however it has its own dis-adventuresses like performance and none really native consept
