### ISSUE TITLE
Investigate the memory leak eddy reported

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#4505]
It is easily reproduced with this project:
https://github.com/EddyVerbruggen/nativescript-ios-out-of-memory

You can track leaked native objects following:

Start the debugging in Xcode and transfer to instruments, in “All Heap & Anonymous VM” at the bottom there is a “Mark Generation” you can click it, then “Loop 10x” then click “Collect Garbage” then again “Mark Generation” this leaves about 15Mb growth in gen2. 7MiB CFString (immutable) and & 7MiB in malloc_zone_malloc that is in UINavigationBar popNavigationItem then CALayer setAffineTransform.

**Comment by NickIliev** [comment]
related to [https://github.com/NativeScript/NativeScript/issues/4490](https://github.com/NativeScript/NativeScript/issues/4490)

**Comment by EddyVerbruggen** [comment]
Just to add: I'm receiving more and more crash reports from beta testers through TestFlight. Until now it only happens on older devices with 1 GB RAM (iPad 3 for instance). Perhaps only once on an iPhone 7, but the TestFlight crash reports are often pretty useless.

This particular app is meant to be used and depends on going back and forth between (long) lists a lot so it's quite sensitive to this issue.

**Comment by PanayotCankov** [comment]
I am closing this one and moving the comments to the #4490
