### ISSUE TITLE
Improve the Network Stack

### ISSUE THREAD

**Issue by chadcampbell** [NativeScript/NativeScript#451]
It would be valuable if there was a way to know more about the device's network status. For example, it would be nice if the there was a way to:

* Determine if a network is available (whether you can connect or not)
* Detect when there has been a change in the network that the device is connected to.

**Comment by kiril-stanoev** [comment]
This will make a great plugin! +1

**Comment by hamorphis** [comment]
I am currently working on these...

**Comment by hamorphis** [comment]
It's ready: https://github.com/NativeScript/NativeScript/tree/master/connectivity

**Comment by hamorphis** [comment]
Sample App: https://github.com/NativeScript/NativeScript/tree/master/apps/connectivity-demo

**Comment by chadcampbell** [comment]
@hamorphis 

Thank you for tackling this. I reviewed the code and the sample app. From what I could tell, you added
```
connectivity.connectionType.none
connectivity.connectionType.wifi
connectivity.connectionType.mobile
```
This is a great start to the connectivity module. However, it only tells the type of connection. From what I can tell, a developer still has challenges to determine if they can actually connect to the internet. I think it would be helpful if the connectivity module included:

`isAvailable` - This true/false property would signal if a network connection is reachable. This property does not inform the developer if they are actually connected to the internet or not. Rather, if they can hit a network point (like a router).

`isWebAvailable` - This true/false property would signal whether the app can actually reach the internet or not.

`changed` - This event would fire when the IP Address that is being used changes. This would be useful for scenarios where app users are moving while using an app.

These are probably nice-to-haves at this point. I just wanted to get them down while I was thinking about them. Still, thanks for adding the connectivity module!
