### ISSUE TITLE
Text/xml content type not treated as text on iOS

### ISSUE THREAD

**Issue by swishstache** [NativeScript/NativeScript#4514]
**Issue**
On iOS, when a http response is of the content type "text/xml", the result of the http.post method is a string representation of NSData rather than XML. On Android, the result is the expected XML of the response.

**Impact**
Response bodies cannot be parsed as XML.

**Recreate**
Using a url that responds with a content type of "text/xml", submit a request.

_Example code_
```
loginUser(): RxObservable<Response> {
    return http.post(url, body, options)
        .timeout(100000, new Error('Connection Timeout'))
        .map(res => res);
}
let res = loginEfxUser();
let result = res.text();
```
"result" is now a string representation of NSData (such as "<33336563 39643830 2d353236 642d3465 36322d38 6435652d 32393637 37663538 36303330>") rather than XML.

We've worked around this by changing "tns-core-modules/xhr/xhr.js" so that http/XMLHttpRequest.textTypes includes "text/xml" and tar-zip'ing the package locally.

This issue appears to have been similar: https://github.com/NativeScript/nativescript-angular/issues/352

- CLI: "tns --version" => 2.5.2
- module: tns-core-modules@2.5.1
- Runtime: "tns-ios": { "version": "3.1.0" }
- Plugins
  "dependencies": {
    "@angular/common": "2.3.1",
    "@angular/compiler": "2.3.1",
    "@angular/core": "2.3.1",
    "@angular/forms": "2.3.1",
    "@angular/http": "2.3.1",
    "@angular/platform-browser": "2.3.1",
    "@angular/platform-browser-dynamic": "2.3.1",
    "@angular/router": "3.3.1",
    "events": "^1.1.1",
    "nativescript-adobe-marketing-cloud": "file:local_node_modules/nativescript-adobe-marketing-cloud-1.3.1.tgz",
    "nativescript-angular": "1.3.0",
    "nativescript-appversion": "~1.4.1",
    "nativescript-fingerprint-auth": "^4.0.0",
    "nativescript-loading-indicator": "^2.2.2",
    "nativescript-ngx-fonticon": "^2.1.2",
    "nativescript-secure-storage": "^2.1.0",
    "nativescript-telerik-ui": "1.5.1",
    "nativescript-theme-core": "1.0.2",
    "nativescript-unit-test-runner": "^0.3.4",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.0.0-rc.4",
    "timers": "^0.1.1",
    "tns-core-modules": "file:local_node_modules/tns-core-modules-2.5.1.tgz",
    "tns-platform-declarations": "^2.5.2",
    "xml2js": "^0.4.17"
  },
  "devDependencies": {
    "@types/xml2js": "^0.0.33",
    "@types/jasmine": "^2.5.47",
    "babel-traverse": "6.8.0",
    "babel-types": "6.8.1",
    "babylon": "6.8.0",
    "codelyzer": "0.0.28",
    "jasmine-core": "^2.5.2",
    "karma": "^1.6.0",
    "karma-jasmine": "^1.1.0",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "0.4.2",
    "nativescript-dev-typescript": "0.3.2",
    "tslint": "3.14.0",
    "typescript": "2.0.10",
    "zone.js": "0.7.2"
  },

**Comment by vakrilov** [comment]
Hi @swishstache,
I checked the [code](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/xhr/xhr.ts#L131-L135) and it looks like `XMLHttpRequest.textTypes` already includes "application/xml". It is also in the code base of the [`2.5.1` version](https://github.com/NativeScript/NativeScript/blob/v2.5.1/tns-core-modules/xhr/xhr.ts#L131-L135) which you are using.

Can you please provide some more information:
1. Are there any other changes you made in the code to work-around the issue?
2. Is the issue reproducible in  the current official version (`3.1.0`).
3. Have you can considered opening a Pull Request with your changes?

You can also consider migrating your project to the latest official version. Most of the bug-fixes we do are shipped in a minor/patch version of the current official version. We currently don't have planned release for another `2.5.x` version.

**Comment by swishstache** [comment]
My apologies, I meant "text/xml". I've updated my original text.

Our application is currently using a SOAP 1.1 API. Per https://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Toc478383526

> HTTP applications MUST use the media type "text/xml" according to RFC 2376 [3] when including SOAP entity bodies in HTTP messages.

It's critical that we get this fixed. We do plan to upgrade to 3.0 but that will require other changes as well. 

I see 2.5.3 was recently released -- is that the last 2.5.x release we can expect? If not, how can I commit to the 2.5.x line of code? If so, I'll create a pull request for master.

**Comment by vakrilov** [comment]
We are currently not planning of releasing another `2.5.x` release.

My suggestion in this case: 
1. We would appreciate your PR. We will merge it in master, which mean it will be available in `next` builds and it will be there waiting for you when you decide to migrate your project to latest (I'm guessing the `2.5.x` -> `3.x.x` migration is what might require some effort. Switching minor release after that shouldn't require changes in the app).
2. If the we decide to release another `2.5.x` version we can cherrypick your changes there. 
3. You can get the code of the `2.5.3` release from the [`v 2.5.3`](https://github.com/NativeScript/NativeScript/tree/v2.5.3) - you can fork and experiment with it as you like, but we generally accept PRs only for the `master` branch.

**Comment by swishstache** [comment]
I've created a PR and signed the CLA. https://github.com/NativeScript/NativeScript/pull/4531#issuecomment-313691043

Thanks for the clarification on 2.5.x releases.
