### ISSUE TITLE
Image Border Radius 

### ISSUE THREAD

**Issue by jogboms** [NativeScript/NativeScript#4521]
Running on Android v7. Using TNS `3.1.1`

``` html
<Image src="res://image" width="50" borderRadius="100"></Image>
<Image src="res://image" width="50" borderRadius="100"></Image>
```
doesn't seem to apply border radius to any of the images.

**Comment by NickIliev** [comment]
@jogboms I have tested the scenario you described and everything seems to works as expected on my side on Android API25 and API23. [Here is the test project](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4521) I've used 

```

<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page">
    <StackLayout class="p-20">
        <Image src="res://logo" width="150" borderRadius="100"></Image>
        <Image src="res://logo" width="50" borderRadius="100"></Image>

        <Image src="res://icon" width="150" borderRadius="100"></Image>
        <Image src="res://icon" width="50" borderRadius="100"></Image>
    </StackLayout>
</Page>

```

And this is the result
![borderradius](https://user-images.githubusercontent.com/18008302/27957140-a115537a-6325-11e7-87a6-04c782dc8e7a.png)

**Comment by jogboms** [comment]
#540
