### ISSUE TITLE
Allow toggling of scrollbar indicators on ScrollView

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#4522]
Feature request: Scrollbar indicators exist in a ScrollView widget by default, would be handy to be able to configure in the XML.

**Comment by sitefinitysteve** [comment]
I have the PR for this pending, the docs said to create an issue... doesnt need up-for-grabs I dont think

**Comment by shiv19** [comment]
How to toggle scrollbar indicators?

**Comment by sitefinitysteve** [comment]
Should be scrollBarIndicatorVisible="false"

**Comment by shiv19** [comment]
Thanks @sitefinitysteve
