### ISSUE TITLE
Multithreading Worker not working

### ISSUE THREAD

**Issue by GrEg00z** [NativeScript/NativeScript#4524]
While using the same than [https://docs.nativescript.org/angular/core-concepts/multithreading-model.html](url)

Then it not working at all : using `postMessage(...` do nothing.

Both "postMessage" and "onmessage" doesn't seems to throw any error.

Here my config :
 - nativescript     │ 3.0.0 
 - tns-core-modules │ 3.0.1
 - tns-android      │ 3.0.1

**Comment by tsonevn** [comment]
Hi @GrEg00z,
I reviewed your case and tested the reported issue with `postMessage` and `onmessage` with latest NativeScript 3.1.2, however, the described method for using workers seems to work as expected.
For testing, I used [demo-workers](https://github.com/NativeScript/demo-workers) project. To be able to build it with latest NativeScirpt, you should first run `tns update` command, which will upgrade all needed dependencies.

Before building the above-attached sample project, upgrade to latest NativeScript, while using `npm install NativeScript --g` command

Moreover, it would help if you provide some more info about your case and what is the expected result. It would also help if you send us sample project, which could be debugged locally

**Comment by GrEg00z** [comment]
Ok I am using Nativescript with Angular, so the demo-worker projet was not good for me.
So I found this project : [here](https://github.com/kazemihabib/ns-angular-worker-demo)

And now I can make it work by following ns-angular-worker-demo code.

Thanks for your good orientation 👍
