### ISSUE TITLE
tns run android

### ISSUE THREAD

**Issue by baguosiji** [NativeScript/NativeScript#4525]
tns run android when transferring project files stuck still, when I run tns platform remove android run again has been stuck in a searing device.I am sure that the device exists.Why is this?

**Comment by dtopuzov** [comment]
Hi @baguosiji 

Please add:
- OS Type and version
- `node` and `npm` versions
- CLI version
- Steps to reproduce the problem 
- Post package.json of you project

**Comment by baguosiji** [comment]
Hi@dtopuzov Thank you very much for your reply
When I platform remove android, there is no problem to run, but when I run again after modify the content, will stay on the Transferring project files, or Refreshing application when I press Ctrl + c, can run normally. 
npm version 3.10.10;
node version v6.10.2;
win10；
This is my package.json
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.longteng",
    "tns-ios": {
      "version": "3.0.1"
    },
    "tns-android": {
      "version": "3.0.1"
    }
  },
  "dependencies": {
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/platform-server": "^4.0.0",
    "@angular/router": "4.0.0",
    "df-tns-ng-instruments": "git+https://git@code.aliyun.com/defangCoLtd/df-tns-ng-instruments.git#45b5e1566ca16707b3eb84d8322cd289a7e74fcd",
    "nativescript-angular": "^3.0.0",
    "nativescript-angular-snapshot": "^1.5.2-5.5.372.32",
    "nativescript-background-http": "^3.0.0",
    "nativescript-camera": "^3.0.0",
    "nativescript-code-push": "^1.0.1",
    "nativescript-geolocation": "^3.0.0",
    "nativescript-imagepicker": "^3.0.0",
    "nativescript-ng2-slides": "github:tjzfg/nativescript-ng2-slides",
    "nativescript-permissions": "^1.2.3",
    "nativescript-phone": "^1.3.0",
    "nativescript-pulltorefresh": "^2.0.0-rc.1",
    "nativescript-social-share": "^1.3.2",
    "nativescript-telerik-ui": "^2.0.1",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "3.0.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "4.0.0",
    "@ngtools/webpack": "1.2.10",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~2.1.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "0.0.9",
    "nativescript-dev-typescript": "^0.4.2",
    "nativescript-dev-webpack": "^0.4.2",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.0.2",
    "typescript": "2.3.4",
    "webpack": "~2.3.3",
    "webpack-sources": "~0.2.3",
    "zone.js": "~0.7.2"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --start-app",
    "start-ios-bundle": "npm run ns-bundle --ios --start-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}

**Comment by tsonevn** [comment]
Hi @baguosiji,
Could you upgrade to latest NativeScript 3.1.2, while using `npm install nativescirpt --g` command and to verify, whether you will have the same issue?

Also to be able to use latest `tns-core-modules` and `nativescript-angular`, you should also change their versions as follow `3.1.0` for both of them. As an example, you could use the attached sample package.json file.

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.issue4525"
  },
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/router": "~4.1.0",
    "nativescript-angular": "~3.1.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "~3.1.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "~0.5.0",
    "typescript": "~2.2.1"
  }
}

```

Please let me know, whether this helps or if I could assist you further

**Comment by NickIliev** [comment]
@baguosiji let us know if you need further assistance on this one - closing the issue due to inactivity.
