### ISSUE TITLE
Dynamically loaded custom component fail to restore previous state after app suspended/resumed on Android

### ISSUE THREAD

**Issue by c1ngular** [NativeScript/NativeScript#4526]
i have a custom menu in my app , each time user click one of the menu items , it dynamically loads a custom component (xml based), and add to a pre-defined gridlayout ( just a place holder), it is working good , soon i found each time i bring my app  from background  to foreground mode , the dynamically loaded components are just gone(my gridlayout is just blank) , app failed to restore its state as before suspended , the app went back to the state of initial start where no custom components were loaded, is the the normal/default behavior of android system ?  

i watched the suspend / resume event of the app , when app suspended , custom component's unloaded event fired , when app resumed , no custom component's loaded event fired at all !

if this is the default behavior (android device) , is there any work around ? 
i am just experimenting , so really got not much "code" involved , i just copied some code snippets from official document examples , and put it together !

thanks

**Comment by NickIliev** [comment]
Hello @c1ngular 

We will need the actual code used to create and add your dynamically loaded components so we could investigate your case. Meanwhile, I have created [this basic test application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4526) that loads a custom component dynamically using the `ui/builder` module and the custom component is loaded as expected when the application goes from background to foreground - perhaps you can use this application to demonstrate your specific structure.

**Comment by c1ngular** [comment]
@NickIliev [https://github.com/c1ngular/nscomponentissue](https://github.com/c1ngular/nscomponentissue) i just uploaded my whole experimenting project folder ,  please check , each time app brought back from background mode , it always show the initial/first loaded component instead of the one we left it before app suspended ~ thanks

**Comment by NickIliev** [comment]
@c1ngular thank you for the provided project.
Based on your code-behind I've noticed that the method responsible for loading the custom components is triggered in the `loaded` callback of your Page. The loaded event will be called each time your apps resumes and as you are providing a default parameter (called "mate") it will overwrite the current state.

To overcome this simply move the initialization of your custom components from `onPageLoaded` to `onNavigatingTo`

e.g. based on main-page.ts
```
function onNavigatingTo(args) {
    page = args.object;

    loadComponent('mate'); // now the methodwon't be executed when the app resumes

}
```

**Comment by c1ngular** [comment]
@NickIliev thank you,  I Will try as you told,  very helpful and informative !

**Comment by NickIliev** [comment]
@c1ngular Closing this - do let me know if that resolved the issue for you and I will reopen if you need further assistance.
