### ISSUE TITLE
Support older Android versions 

### ISSUE THREAD

**Issue by thstarshine** [NativeScript/NativeScript#453]
According to this:

http://www.telerik.com/support/whats-new/nativescript

> Later releases will support older Android version - our target is Android 2.3 as well as latest API levels.

Is this in schedule?

**Comment by atanasovg** [comment]
There is no particular technical complication to support older Android versions. However, the cross-platform modules use quite some APIs available in API level 17+, that's why we initially opted on this version as the minimum. We will need to figure out how to handle different API versions at modules level first. We already have our discussions on this matter internally and we will soon open a separate issue that summarizes our thoughts on versioning as a whole.

**Comment by thstarshine** [comment]
Thanks. That would be great!

**Comment by jmatsushita** [comment]
Hi there, targeting older Android versions is important for our project. It would be great to get a sense of where this would fit in your roadmap (1.6? 1.7? 2.0?) so we can choose between Cordova and {N}.

Thanks for your help!

**Comment by jmatsushita** [comment]
Hi @atanasovg, 

Would you mind helping me understand what it would take to support API level < 17? Are you saying that some of the NativeScript modules wouldn't be happy with using the android support libraries for backward compatibility? 

Would it be helpful to try to fork and compile android-runtime with [all](https://github.com/NativeScript/android-runtime/search?utf8=%E2%9C%93&q=minSdkVersion) ```minSdkVersion``` set to ```14``` (like it is for ```binding-generator```? 

Then probably introducing a minSdkVersion in the ```AndroidToolsInfo``` and in the [android-project-service](https://github.com/NativeScript/nativescript-cli/blob/f465f8400b7034056f4150b29367127e9ce9282b/lib/services/android-project-service.ts#L205-L210) ? 

Whatever errors would show up running something like ```tns run android --mindSdk=16``` would be the todo list to support older versions? Let me know if I'm missing something big or I'll give it a shot!

**Comment by slavchev** [comment]
Hi @jmatsushita 

>Would you mind helping me understand what it would take to support API level < 17? 

When it comes to the NativeScript runtime for Android we can easily go back to API level 15 (see https://github.com/NativeScript/android-runtime/issues/198 for more details). However, there are good chances that we can support API level 10 as well. I have to check that but my preliminary tests showed that most of the runtime components are supported in API level 10.

>Are you saying that some of the NativeScript modules wouldn't be happy with using the android support libraries for backward compatibility?

Currently, there are parts of the module functionality that are not designed with Android Support Library in mind. With that said, there is always room for improvement. It is an iterative process and I won't be surprised if future versions of NativeScript modules support API level 10.

>Would it be helpful to try to fork and compile android-runtime with all minSdkVersion set to 14 (like it is for binding-generator?

At the moment this approach is unlikely to work. There is some application specific code in the {N} runtime that relies on API level 17. The good news is that I already created a prototype that shows how to move this logic from the runtime to the application template. Once we refactor this part of the project it will be possible to downgrade to API level 10.

Finally, I would like to suggest to keep this issue closed and move any further conversations to the [android-runtime](https://github.com/NativeScript/android-runtime) project site.

**Comment by saravanacs** [comment]
I have one doubts, below android 5.1 version support printer in {N} ?
