### ISSUE TITLE
[Angular] Slider with two-way binding remains stuck after first usage

### ISSUE THREAD

**Issue by manoldonev** [NativeScript/NativeScript#4530]
### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.1.2
- Cross-platform modules: 3.1.0
- Runtime(s): 3.1.0

### Please tell us how to recreate the issue in as much detail as possible.
Slider with two-way ngModel binding remains stuck after first usage. No errors are thrown but you cannot move the slider in either direction anymore. If you navigate away from the page and return back to it, the control is again operational on first usage, then remains stuck. This works correctly on Android.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
The issue is reproducible with any of the sliders in the Angular sdk examples that use two-way data binding [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/ui-category/slider/slider-access-value-code). You just need to update the tns-core-modules version in the app package.json to "~3.1.0".

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#887
