### ISSUE TITLE
[FormattedString]  [Angular]The text in the FormattedString lose its color after redirection

### ISSUE THREAD

**Issue by vegeorgi** [NativeScript/NativeScript#4532]
### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:

- CLI: 3.1.2
- Cross-platform modules: 3.1.0
- Runtime(s): 3.1.0

### Please tell us how to recreate the issue in as much detail as possible.

Have an app with a list view. Each item has a FormattedString section with icons (font icon - font awesome) and text. The icons has to be a different color from the text. After navigation to the detail page and return back, the icon color has changed to the same color as the text - [video](https://www.screencast.com/t/la6HKVWua)

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

The code can be seen [here](https://github.com/NativeScript/template-master-detail-ng/blob/vegeorgi/style-fixes/cars/car-list.component.html)

**Comment by tsonevn** [comment]
The issue seems to be fixed with the latest tns-core-modules - `4.1.1` and nativescript-angular - `6.0.6`.
