### ISSUE TITLE
isUserInteractionEnabled= true is not working after the http post 

### ISSUE THREAD

**Issue by Jaishankarb** [NativeScript/NativeScript#4540]
is isUserInteractionEnabled is not enabling after the http post  response 

//typescript
```
 public signInInteraction: boolean = true;

 this._loginService.loginUser(JSON.stringify(this.loginUser))
        .subscribe((data) => {          
          this.signInInteraction = true;
          this.navHome();
        },
        (error) => {        
          console.log(this.password)
          this.signInInteraction = true;
          this.isLoginApi = true;
        });
```
//html
```
 <Button id="btnSubmit" text="Sign in" [isUserInteractionEnabled]="signInInteraction" class="Loginsubmit" autocapitalizationType="none" (tap)="Login()"></Button>
```

**Comment by tsonevn** [comment]
Hi @Jaishankarb 
I reviewed this case and have to confirm that this is a real issue. I was able to reproduce it in NativeScript Angular 2 project only on Android.
I am attaching sample project, which could be used for debugging.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1141038/Archive.zip)

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#890
