### ISSUE TITLE
Need to use XCode to build ONCE before doing tns run ios with a real device

### ISSUE THREAD

**Issue by kamok** [NativeScript/NativeScript#4545]
### Please, ensure your title is less than 63 characters long and starts with a capitalletter.
I've been using Ionic Framework. Just dabbling in NS, with the Groceries project as a starter. I am not able to use `tns run ios` on the get go. `tns run android` works fine with livereload.

I have added my device to the apple id (I already deployed and tested 2 Ionic apps, so I know it works). I needed to open the xcodeproject file inside of `platforms/ios`, select build target to my device and build there.

Afterwards, I can exit the entire thing out of XCode, and use the cli to do `tns run ios`. This needs to be addressed as you will be turning away prospective users on such a basic functionality. I replicated this with 2 other members on my team. (More like I couldn't build and ask them how they got it to work via `tns run ios`)

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) `3.1.2`
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.Groceries",
    "tns-ios": {
      "version": "3.1.0"
    },
    "tns-android": {
      "version": "3.1.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.0.0",
    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/router": "~4.0.0",
    "nativescript-angular": "~3.0.0",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "~3.0.0",
    "zone.js": "0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.25.0",
    "babel-types": "6.25.0",
    "babylon": "6.17.4",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.4.0",
    "typescript": "~2.2.1"
  }
}
```

### Please tell us how to recreate the issue in as much detail as possible.
I already told you. 

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
No.

**Comment by tsonevn** [comment]
Hi @kamok,
First of all, thank you for your interest in NativeScript.
Regarding the problem, could you give us some more info and whether there is specific error thrown in the console when you are building the project with `tns run ios`. Something more you could build the project with `tns run ios --log trace` and to send us the full log from the terminal.

In the meantime, you could also try to build the project while specifying the provisioning profile -> `tns run ios --provision <uuid-or-name>`. For more info about the provisioning option review this comment [here](https://github.com/NativeScript/NativeScript/issues/3125#issuecomment-296212439).
