### ISSUE TITLE
Why is there a white screen for a second after splash screen in iOS?

### ISSUE THREAD

**Issue by thomaspaniagua** [NativeScript/NativeScript#4546]
This doesn't seem to happen in the simulator I use, but when I test on a real device (iOS 10.3, NS 3.0) my app's first screen takes a little while to render and is completely blank at first. What can I do to solve this issue and keep the splash screen up until the screen is fully rendered?

As far as I know this doesn't happen in Android, but I've only used an Android emulator to test.

**Comment by tsonevn** [comment]
Hi @thomaspaniagua,
Could you provide some more info about your project and whether you are using NativeScript Angular 2 or NativeScript TyperScript template? 
We have the similar [issue ](https://github.com/NativeScript/nativescript-angular/issues/829)logged for NativeScript Angular 2, which is already fixed for the upcoming release.

**Comment by thomaspaniagua** [comment]
@tsonevn Can confirm it's Nativescript Angular 2

**Comment by tsonevn** [comment]
Hi @thomaspaniagua,
Thank you for the additional info. In this case, I am closing this issue in favor of the [other one,](https://github.com/NativeScript/nativescript-angular/issues/829) which reports this problem.
