### ISSUE TITLE
ListView item removes backgroundColor when pressed

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#455]
I have a Page with a ListView and itemTemplate. The template contains a GridLayout (one row, one column) with Image and overlapping text (title). The overlapping text is contained innside a StackLayout and has a certian background-color applied. 

When tapping on the ListView item, the background-color I set, is gone, and replaced by nothing (transparent), the text is still there. 
If I press another item in the list, the previous item gets its bg-color back, and the newly pressed item looses its bg-color. 

I also tested by removing the image from the template and only leaving StackLayout and labels. By tapping the item, the bg-color becomes grey.  

I could not find a way to remove the pressed-color on the listview item. 

Either way, tapping listview item should not remove any style set on elements innside the template.

**Comment by hamorphis** [comment]
Can you attach or somehow share a small sample project that reproduces this behavior. Thanks in advance.

**Comment by manijak** [comment]
No problem, download link included. Should mention that I use 1.1.0 with iOS. 

Run it as is, to see how it behaves in full. Then you can comment out the <Image src> tag to see what happens in the background. I think it just overrides all background colors when tapped.

[Download listview-glitch](https://dl.dropboxusercontent.com/u/33168380/listview-glitch.zip)

**Comment by nsndeck** [comment]
Unfortunately this is the default behavior of the iOS native control (UITableView). It changes the background of controls when selected. An easy way to solve the issue is to set **selectionStyle** for every cell to `UITableViewCellSelectionStyleNone`. It will disable all background changes to list view item on selection. This can be done with the help of **itemLoading** event of the NativeScript ListView control. Your code should look like the following:

``` XML
<ListView itemLoading="listViewItemLoading" ../>
```
``` JavaScript
function listViewItemLoading(args) {
    var cell = args.ios;
    cell.selectionStyle = UITableViewCellSelectionStyle.UITableViewCellSelectionStyleNone;
}
exports.listViewItemLoading = listViewItemLoading;
```

**Comment by manijak** [comment]
Great stuff. Your example works perfectly! Just what I needed. I really did not like the default behaviour, especially when it removes all bg-color on other elements. 

Thanks a log for looking into this. Could this become a xml property in the future?

**Comment by nsndeck** [comment]
Since this is a platform (ios) specific property we do not plan to provide a `xml` way to set it. Also there is another problem - this property should be set to **ListView.item** (cell) and we do not have access to item via xml.

**Comment by manijak** [comment]
Ok no problem. Your solution works anyways. Thanks again.

**Comment by uzarsalan** [comment]
It doesn't work right now, on my app's first screen. As i think Nativescript overrides this property with it's own. I asked for solution for the same problem here https://github.com/NativeScript/NativeScript/issues/4805#issuecomment-329979771
but i can't apply it for ListView. Can anybody help me? I'm js junior.

**Comment by rsaf** [comment]
Can this solution work for Angular as well? It seems not to be working. @nsndeck

**Comment by FranciZ** [comment]
@rsaf You can listen for these events in the component. [This is the event you want](https://docs.nativescript.org/api-reference/classes/_ui_list_view_.listview#itemloadingevent) and below is example code for this working.

```typescript
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core'
import { isIOS } from 'tns-core-modules/platform';

// Declare the var so typescript doesn't complain
declare var UITableViewCellSelectionStyle;

@Component({
  moduleId: module.id,
  selector: 'ns-list-view-example',
  templateUrl: './list-view-example.component.html',
  styleUrls: ['./list-view-example.component.css']
})
export class ListViewExampleComponent implements OnInit {

  @ViewChild('listView') listView: ElementRef;

  constructor() {
  }

  ngOnInit() {

    this.listView.nativeElement.addEventListener('itemLoading', ( args ) => {
      
      // check that platform is iOS
      if ( isIOS ) {
        const cell = args.ios;
        cell.selectionStyle = UITableViewCellSelectionStyle.UITableViewCellSelectionStyleNone;
      }
      
    });

  }

}
```

**Comment by CoreyCole** [comment]
@FranciZ I can't seem to get that code working. I'm getting the error:
```
[native code]: ERROR TypeError: undefined is not an object (evaluating 'this.listView.nativeElement')
```
I've also tried changing your code to use a capital letter `L` like it is in my XML `<ListView>`
```
@ViewChild('ListView') listView: ElementRef;
```

**Comment by allnash** [comment]
^^ That works on latest native script.

**Comment by paxperscientiam** [comment]
Combining @nsndeck's answer and @CoreyCole , here's for typescript (no angular)

```xml
<ListView itemLoading="listViewItemLoading" ... />
```

```typescript
declare var UITableViewCellSelectionStyle

export function listViewItemLoading(args) {
    const cell = args.ios
    cell.selectionStyle = UITableViewCellSelectionStyle.UITableViewCellSelectionStyleNone
}
```

**Comment by lblase** [comment]
I'm Workting with Angular + Nativescprit, How to do that with Andorid?
