### ISSUE TITLE
Application drains battery when in background on Android

### ISSUE THREAD

**Issue by ickata** [NativeScript/NativeScript#4557]
Hi,

I observe huge battery consumption on Android devices when the app is started and is running in background mode. Battery just goes down in a couple of hours. As soon as I kill the app, battery starts exhausting normally.

Can you please advise me is there a quick & easy way to detect what exactly is draining the battery?

## Environment
- CLI: 2.5.4
- Cross-platform modules: 2.5.2
- Runtime(s): 2.5.0
- Plugin(s): 

```
┌──────────────────────────────────┬─────────┐
│ Plugin                           │ Version │
│ async                            │ 2.1.4   │
│ nativescript-drop-down           │ 1.5.1   │
│ nativescript-geolocation         │ 0.0.18  │
│ nativescript-google-maps-sdk     │ 1.4.3   │
│ nativescript-ios-uuid            │ 1.0.0   │
│ nativescript-iqkeyboardmanager   │ 1.0.1   │
│ nativescript-local-notifications │ 1.2.1   │
│ nativescript-phone               │ 1.3.0   │
│ nativescript-push-notifications  │ 0.1.2   │
│ nativescript-theme-core          │ 0.2.1   │
│ tns-core-modules                 │ 2.5.2   │
└──────────────────────────────────┴─────────┘
```

**Comment by tsonevn** [comment]
Hi @ickata,
Could you give us some more info about your project? It would help if you could provide some sample, which will allow us to debug this case and to verify, whether this battery consumption is related directly with NativeScirpt.

Also, could you check, if there is some process, which is running on background and could lead to this problem? I notice that you are using `nativescript-geolocation` plugin and which might lead to bigger consumption if you are checking for the location when the app is in the background.

In the meantime, you could also verify, whether you will have the same problem while using latest NativeScript 3.1.0

**Comment by ickata** [comment]
Hi Nikolay,

Thanks for the directions. I managed to locate the cause of this – it's a permission called `WAKE_LOCK` set by the [push plugin](https://github.com/NativeScript/push-plugin#android-1). I am 100% sure that this is causing the huge battery consumption because I was able to disable it on older Android version (4.2) and left the app running in background the whole night. In the morning, battery was almost untouched.

Please advise how should I proceed. Should I move this issue to the [push plugin issues](https://github.com/NativeScript/push-plugin/issues)? Unfortunately application does not work well w/o this permission – push notifications are received, but it seems that they cannot be handled correctly.

**Comment by tsonevn** [comment]
Hi @ickata,
Thank you for the further information,
Indeed if this problem is related to the permission which is needed by this plugin, the best place for this issue is on the plugin's [repository](https://github.com/NativeScript/push-plugin/issues), where you could describe this scenario.

**Comment by ickata** [comment]
Thanks, moved this to NativeScript/push-plugin#135

**Comment by ickata** [comment]
BTW, does someone support the push-plugin repo? No answer for 2 days...
