### ISSUE TITLE
App freezes using the AppStore Profile on navigating to screen which has keyboard event i.e. taking value from user.

### ISSUE THREAD

**Issue by macin40** [NativeScript/NativeScript#4558]
`    @ViewChild("inputValue") inputValue: ElementRef;
    

      ngAfterViewInit() {
        console.log("ngAfterViewInit");
        if (isIOS) {
            this.inputValue.nativeElement.ios.keyboardType = UIKeyboardType.DecimalPad;
            this.inputValue.nativeElement.focus();
        }
    }`
I want to use decimal keypad in iOS and open keypad on nativating to that page.
The app freezes wherever the screen has keyboard events.

**Comment by tsonevn** [comment]
Hi @macin40,
I tested your scenario and the provided sample code, however changing the keyboard type on iOS work as expected. I tested changing the keyboard type on `ngAfterViewInit` and on `loadedEvent`.
For your convenience, I am attaching sample project, you could review it and make the needed changes, which will allow us to reproduce the problem.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/1152238/Archive.zip)

**Comment by macin40** [comment]
@tsonevn I figured out the mistake ,function was called in wrong life cycle method.Thanks for help
