### ISSUE TITLE
nativescript-imagecropper in NativeScript 3.0

### ISSUE THREAD

**Issue by SandipFichadiya** [NativeScript/NativeScript#4565]
Hi,
nativescript-imagecropper Plugin is not working in Nativescript 3.0.3 Version.
It gives me undefined error in catch clause.
Is there another way to implement nativescript-imagecropper Plugin for Nativescript 3.0.3 Version?

**Comment by tsonevn** [comment]
Hi @SandipFichadiya,
At this time this is the only plugin, which provides functionality for cropping an image. 
Regarding that, the nativescript-imagecropper is created by one of the community members and is not officially supported by NativeScript team. I found that you have already opened an [issue ](https://github.com/bthurlow/nativescript-imagecropper/issues/14) in the plugins repository and you could keep track on it for further info.

**Comment by shiv19** [comment]
I've added support for NativeScript 3.3 for image cropper plugin, please try it out :)
