### ISSUE TITLE
Unable to route on particular page with parameters. 

### ISSUE THREAD

**Issue by macin40** [NativeScript/NativeScript#4566]
`    
  this._routerExtensions.navigate([AppConstant.MY_PAGE, this.selectedSize + '+' + sizeType]);
`
I am sending the params in concatenated form and splitting them by delimiter  '+' on other controller.
This is working fine in debug mode but not working in release mode.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#902
