### ISSUE TITLE
How to run app in release mode in IOS

### ISSUE THREAD

**Issue by macin40** [NativeScript/NativeScript#4567]
how to run app using release mode and distribution certificate and app store profile?

**Comment by tsonevn** [comment]
Hi @macin40,
To be able to run your application on a device, you should firstly generate the ipa file, which will be used for installing the project. Instruction how to prepare your project for release and how to sign it could be found [here](https://docs.nativescript.org/publishing/publishing-ios-apps#overview). The second step is to install the api file. For more info review [this ](http://techapple.net/2015/01/4-waysmethods-install-ipa-file-app-iphone-ipad-ipod-online-offline-methods/) article, where are described several options s, how it could be done.
For further how to questions please use [NativeScript forum](https://discourse.nativescript.org/).
