### ISSUE TITLE
TypeErrors aren't caught by application

### ISSUE THREAD

**Issue by NordlingDev** [NativeScript/NativeScript#4568]
**Platform:** iOS
**TNS:** 3.1.0

It's been like this since 2.5 (or maybe even earlier) for me. My {N} applications do not catch any TypeErrors.

Say I make this typing error:

```js
  function test() {
    this.options = { foo: false };
    this.optoins.foo = true;
  }
```

In the function I mistype `this.options` as `this.optoins`. But the terminal doesn't log the error unless I wrap the code in a try/catch. Developing an application without TypeError logging by default slows down the development process A LOT. How can I fix this?

I know there is an event inside the `application` module called `uncaughtErrorEvent`, but this is about a TypeErrorEvent, which doesn't seem to exist.

Thanks in advance!

**Comment by NordlingArt** [comment]
@Nicklliev - I wouldn't count it as a question, more like a bug or similar issue. Can it be related to the simulator, and not the NS CLI?

**Comment by NickIliev** [comment]
@NordlingArt I have tested this scenario with [this test application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4568).
At my side, the error immediately throws with
```
TypeError: Cannot set property "foo" of undefined
```

It should be enough indication but still, I am logging this one as a `feature` request and with `up-for-grabs`

**Comment by NordlingArt** [comment]
@NickIliev - Were you trying this with iOS or Android? And on what OS? It's definitely enough with an error like you get, however, I don't even get that. Nothing is logged to the terminal so I have no idea where an error is located when I have tons of code in a larger app.

**Comment by CoreyCole** [comment]
I'm also running into a TypeError and it is not caught by `applicationOn(uncaughtErrorEvent)`. I trigger it by adding a `(tap)="functionName"` where `functionName` is not defined. I get error:
```
ERROR TypeError: _co.functionName is not a function
```
I was hoping stuff like this would be caught by `applicationOn(uncaughtErrorEvent)`.

**Comment by NickIliev** [comment]
Type errors are now caught by uncaughtErrorEvent on both iOS and Android

```
file:///app/home/home-page.js:10:9: JS ERROR TypeError: undefined is not an object (evaluating 'this.options = { foo: false }')
```
