### ISSUE TITLE
Button touch feedback delay

### ISSUE THREAD

**Issue by praven07** [NativeScript/NativeScript#4571]
Button inside a scroll view has a delay in the touch feedback. for ex:

`<StackLayout>
     <Button text="Click Me"></Button>
</StackLayout>`

This Works fine.

`<ScrollView>
      <StackLayout>
          <Button text="Click Me"></Button>
      </StackLayout>
</ScrollView>`

This gets a delay in the touch feedback. After I touch it, it takes like few milliseconds for it to get the touch fade feedback.

**Comment by NickIliev** [comment]
Hi @praven07 

I am guessing that by fade effect you are talking about the ripple effect that the native Android has for its buttons. If that is the case keep in mind that this effect is triggered by the tap event and not the touch. If you have both events to your button the touch event will be triggered first and only then the tap event will be executed and the ripple will be visualized on the tap event.

Demo application demonstrating the behavior can be found [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4571)

**Comment by praven07** [comment]
No this is in iOS. I did add the tap event on the button  and it still has the delay on the tap feedback.

**Comment by praven07** [comment]
you can recreate the issue with the default project on "tns create sample --ng"

The screenshot of the code used.
![screen shot 2017-07-19 at 1 06 01 pm](https://user-images.githubusercontent.com/2223191/28382277-357df9c0-6c83-11e7-8bfc-4b28d787b965.png)

When you run the on iOS. And when you click on the button it will have a slight delay on the tap feedback. But once you remove the scroll view surrounding the stacklayout it works perfectly fine.

**Comment by FranciZ** [comment]
@praven07 Did you maybe figure anything out? Seeing the same issue on my end. Thanks!
