### ISSUE TITLE
Google Maps - Waypoints and Direction 

### ISSUE THREAD

**Issue by umeshrs** [NativeScript/NativeScript#4577]
Is it possible to render directions using waypoints like here - https://developers.google.com/maps/documentation/javascript/examples/directions-waypoints

Is there any plugin to do this or any pointers in this direction will be helpful. 

nativescript-google-maps-sdk doesn't support this I think and nativescript-directions just has directions from point a to b, does not support many points.

**Comment by tsonevn** [comment]
Hi @umeshrs,
At this time there is no plugin which provides support for `waypoints` in google maps for NativeScript application. However, you could implement it while using native code. Here you will find an [article](https://developer.dji.com/mobile-sdk/documentation/android-tutorials/GSDemo-Google-Map.html), how it could be done on android 

I also found that in the `nativescript-directions` plugin repository, there is a request for a support of similar functionality. You could vote for it and if there is interest the plugin author could implement it.

Also for a further question please use NativeScirpt [forums](https://discourse.nativescript.org/).

**Comment by EddyVerbruggen** [comment]
Regarding the nativescript-directions plugin that was mentioned above, it now supports waypoints. See [this example](https://github.com/EddyVerbruggen/nativescript-directions/blob/d360d145ddcd3a2d82ad651bf8aefc10e9b01bcf/demo/app/main-view-model.ts#L34-L54).
