### ISSUE TITLE
Connectivity's startMonitoring behaviour is different between platforms

### ISSUE THREAD

**Issue by surdu** [NativeScript/NativeScript#4579]
When I use `connectivity.startMonitoring` on Android it implicitly triggers the callback with the current state of the connectivity when I call `startMonitoring`.

On iOS, it will trigger the callback only when the connectivity changes.

I like the Android behaviour, but that being said iOS sounds more like how it should work.

Anyhow, shouldn't the behaviour be the same in between the two platforms ?

PS: both scenarios are tested on real devices, not simulators.

```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.1.2           │ 3.1.2          │ Up to date  │
│ tns-core-modules │ 3.1.0           │ 3.1.0          │ Up to date  │
│ tns-android      │ 3.1.1           │ 3.1.1          │ Up to date  │
│ tns-ios          │ 3.1.0           │ 3.1.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

**Comment by NathanaelA** [comment]
For whoever does this - probably be simplest is to make iOS equivalent to Android; just call the callback in the `startMontitoring` if it is iOS and then both platforms would match.

**Comment by vakrilov** [comment]
Agree with @NathanaelA 
I can see there is already a PR implementing the same (fire event on `startMonitoring()`) for IOS. Let's work on getting that merged.
