### ISSUE TITLE
Create an article describing how to access a valid Android Context

### ISSUE THREAD

**Issue by atanasovg** [NativeScript/NativeScript#458]
People are starting to experiment with native APIs within the modules. Since some Android APIs require a valid `android.content.Context` instance, we need to add a help article describing the `Context` instances available at modules level:

* The `application.android.context` property
* The `View.android.getContext` method
* The Placeholder's `CreateViewEventData.context` property
* The `View._context` property - although it is private(internal) this property is sometimes useful.

We need to also describe (or link to external resources) the differences between the `Application` and `Activity` contexts.

**Comment by enchev** [comment]
This issue was moved to NativeScript/docs#240
