### ISSUE TITLE
line-height

### ISSUE THREAD

**Issue by marcelbraun1985** [NativeScript/NativeScript#4581]
Hi,

how can i use css like property "line-height"? The lines are realy close.

Thanks
Marcel

**Comment by NickIliev** [comment]
There is a lineHeight property implemented for controls like TextField.

[https://docs.nativescript.org/api-reference/classes/_ui_text_field_.textfield#lineheight](https://docs.nativescript.org/api-reference/classes/_ui_text_field_.textfield#lineheight)
