### ISSUE TITLE
[ios] Label with formatted text and theme classes crashes

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#4582]
The following snippet crashes on iOS 3.1.0 but was working in 3.0:
```xml
    <Label row="1" colSpan="2" class="h2 p-t-15">
        <Label.formattedText>
            <FormattedString>
                <FormattedString.spans>
                    <Span class="fa" text="&#xf1b3;"/>
                    <Span text=" Workload"/>
                </FormattedString.spans>
            </FormattedString>
        </Label.formattedText>
    </Label>
```
If i remove the `h2` class it works as expected. Attaching demo project to simulate the problem. 
[label-styles.zip](https://github.com/NativeScript/NativeScript/files/1165534/label-styles.zip)

**Comment by tsonevn** [comment]
Hi @PeterStaev,
Thank you for the sample project.
I reviewed it and was also able to reproduce this issue on my side. We will research what is causing this issue and will provide the needed fix.

For further info you could keep track on the issue.

**Comment by hshristov** [comment]
@PeterStaev @tsonevn I cannot reproduce it with master branch.
Could you guys check it too and close if it is fixed?

**Comment by tsonevn** [comment]
@hshristov 
Indeed this problem is no longer reproducible with `@next` modules.

**Comment by PeterStaev** [comment]
@hshristov 
I also confirm that this is fixed in `@next`
