### ISSUE TITLE
Issues with extended Page component and CSS file

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#4590]
**Platform:** iOS 10.2
**TNS:** 3.1.0

If I use an extended `Page` component in an XML file (say test.xml), it will not recognize the corresponding CSS file (test.css) which is in the same directory. This means nothing that's inside the CSS file is being applied to the `Page`.

Question is, is the `Page` module non-extendable?

**Comment by tsonevn** [comment]
Hi @NordlingArt,
Indeed you could extend the Page component. Similar extending has been also used in the nativescript-ui-sample app, which could be found [here](https://github.com/telerik/nativescript-ui-samples/blob/release/sdk/app/navigation/example-page.ts).

Regarding that, it would help if you could provide sample project, which could demonstrate your case and also could be debugged locally.
