### ISSUE TITLE
[Feature] Helper to dismiss keyboard

### ISSUE THREAD

**Issue by vcooley** [NativeScript/NativeScript#4594]
Currently, as far as I can tell, you have to have a reference to a TextField or similar in order to call the `dismissSoftInput` method. This feels hacky when, for instance, you want to dismiss the keyboard when a certain action is taken by a user in order to show more of the screen. 

This is the only way that I know of to dismiss the keyboard, whether or not the field is focused:
```
const field = <TextField>this.page.getViewById('first-name');
field.dismissSoftInput();
```

I don't think that this code clearly expresses the intent of the developer, and could be more concise with something such as:
```
this.page.dismissSoftInput();
``` 

If something similar to this approach is already possible, please let me know.

**Comment by bradmartin** [comment]
I'd kill for something on iOS like this. On android it's a simple call to close it and I use it in every app I do. Outlined it here: https://bradmartin.net/2016/10/21/dismiss-the-android-softkeyboard-programmatically-in-a-nativescript-app/ I mainly use this on a button tap when a form is completed. Sometimes the `done` returnType doesn't close the keyboard so I just go with this approach. Now that I've gotten more into iOS I've been experiencing how much a nightmare it is to get the iOS keyboard to close consistently. The returnKeyType `next` works most of the time but I think on TextView's it doesn't close the keyboard and adds a line break (seems reasonable I suppose). So if there is a simple global iOS way to close the keyboard that would be awesome. If so, it seems like a great method for `utils` or the `page`.

**Comment by vcooley** [comment]
To expand on this, I have actually found that it is an extra line of code on iOS. The field must be focused before dismissing the keyboard. So let's say there are multiple fields on a screen and you want to dismiss the keyboard no matter which is focused. The above code will work if the field with `id="first-name"` is focused, but assuming a different field is focused (for instance a field with id='last-name'), you need the following code:

```
const field = <TextField>this.page.getViewById('first-name');
field.focus();
field.dismissSoftInput();
```

**Comment by bhavincb** [comment]
if nativescript can provide extra event binding support like 'focus' and 'blur' than it will be great to have it.

**Comment by manojdcoder** [comment]
It must be already possible with Android.

```
import * as utils from "tns-core-modules/utils/utils";
utils.ad.dismissSoftInput();
```

Just needs equivalent on iOS.

**Comment by bradmartin** [comment]
@manojdcoder 
```typescript
 UIApplication.sharedApplication.sendActionToFromForEvent(
      "resignFirstResponder",
      null,
      null,
      null
    );
```

This works on iOS without reference to a textfield.

**Comment by manojdcoder** [comment]
Thanks, though I had been using

```
utils.ios
            .getter(UIApplication, UIApplication.sharedApplication)
            .keyWindow
            .endEditing(true);
```

Do you think `resignFirstResponder` could be better?

**Comment by bradmartin** [comment]
Not entirely sure, after the few years in the mobile space I've still never had time to learn a lot of iOS 😄

**Comment by bradmartin** [comment]
@tsonevn - do you know if the above approach would work on iOS? Without any negative impact? 

I've just added [this](https://github.com/TheOriginalJosh/nativescript-swiss-army-knife/blob/master/src/nativescript-swiss-army-knife.ts#L232) to the Swiss-Army-Knife plugin and it has worked on the few tests I've ran.

**Comment by bearoutthere** [comment]
After looking at several threads on this topic here's what i came up with, which is shorter than all other examples i've seen.  

`export const hideKeyboard = () => {
    // hide soft keyboard on Android
    if (ios) {
        ios.nativeApp.sendActionToFromForEvent('resignFirstResponder, null, null, null');
    } else {
        nsutils.ad.dismissSoftInput();
    }
};`

**Comment by darylteo** [comment]
@bearoutthere  thank you so much for that code for ios! 

Just want to note that there is a typo, which took me awhile to figure out. The single quote is in the wrong place. Don't copy and paste without reading, folks!

```ts
import * as nsutils from 'tns-core-modules/utils/utils';
import { ios } from 'tns-core-modules/application';

export const hideKeyboard = () => {
    if (ios) {
        ios.nativeApp.sendActionToFromForEvent('resignFirstResponder', null, null, null);
    } else {
        nsutils.ad.dismissSoftInput();
    }
};
```

**Comment by vallemar** [comment]
New on NS7, 8...
```
import { isIOS } from "@nativescript/core/platform";
import * as utils from "@nativescript/core/utils/utils";
import * as app from "@nativescript/core/application";

export const hideKeyboard = () => {
  if (isIOS) {
    app.ios.nativeApp.sendActionToFromForEvent(
      "resignFirstResponder",
      null,
      null,
      null
    );
  } else {
    utils.ad.dismissSoftInput();
  }
};

```

**Comment by ittrad-mobile-lab** [comment]
> New on NS7, 8...
> 
> ```ts
> import { isIOS } from "@nativescript/core/platform";
> import * as utils from "@nativescript/core/utils/utils";
> import * as app from "@nativescript/core/application";
> 
> export const hideKeyboard = () => {
>   if (isIOS) {
>     app.ios.nativeApp.sendActionToFromForEvent(
>       "resignFirstResponder",
>       null,
>       null,
>       null
>     );
>   } else {
>     utils.ad.dismissSoftInput();
>   }
> };
> ```
Could you please let me know where should I place this code on my nativescript (NS7+) angular app?
Many thanks.

**Comment by vallemar** [comment]
Added in nativescript/core 8.4.0 the`dismissKeyboard` method to close the keyboard (https://github.com/NativeScript/NativeScript/releases/tag/8.4.0-core) Now you can do 
```ts
import { Utils } from "@nativescript/core";

Utils.dismissKeyboard( )
```
 
and the keyboard will close.

@ittrad-mobile-lab This depends on where you want to close the keyboard. Call the method when you want to close the keyboard

**Comment by ittrad-mobile-lab** [comment]
> ```ts
> dismissKeyboard
> ```

Well apparently the method dismissKeyboard is not yet on 8.4.0( I've, update to the version 8.4.0 then cleanup - ns clean -then installed npm i +ns build android, etc)
<img width="420" alt="dismiss-keyboardon84" src="https://user-images.githubusercontent.com/46108848/212074653-81a61667-2cd8-47dc-a1c5-66190490f54e.png">

**Comment by vallemar** [comment]
@ittrad-mobile-lab you need update dependency in your project: `@nativescript/core`

**Comment by ittrad-mobile-lab** [comment]
> @ittrad-mobile-lab you need update dependency in your project: `@nativescript/core`

You mean....???
This is what I have now
"dependencies": {
    "@angular/animations": "~13.1.1",
    "@angular/common": "~13.1.1",
    "@angular/compiler": "~13.1.1",
    **"@angular/core": "~13.1.1",**

**Comment by bradmartin** [comment]
@ittrad-mobile-lab  yes, in your package.json you should also have `"@nativescript/core": ..."` so be sure it is set to `8.4.0` and also be sure you do `ns clean` in the root of your project to delete node_modules and the npm lock file or you'll end up installing the old versions in your lock file (assuming you haven't disabled lock files on your system).
