### ISSUE TITLE
Border-radius not working for FlexboxLayout

### ISSUE THREAD

**Issue by vijaykumarbollavaram** [NativeScript/NativeScript#4596]
I am setting border radius for top-left ...etc not working

**Comment by vijaykumarbollavaram** [comment]
+ Overflow  also not working  in nativescrtipt

**Comment by PanayotCankov** [comment]
The CSS spec is not completely implemented.
Could you list what you expect to use with the flex box?

**Comment by PanayotCankov** [comment]
#4573
