### ISSUE TITLE
Android GC MarkReachableObjects is slow

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#4597]
#### Issues related/affected:
 - https://github.com/NativeScript/NativeScript/issues/3901

#### Existing NativeScript Articles:
 - https://iobservable.net/blog/2014/06/07/synchronizing-gc-in-java-and-v8/
 - https://docs.nativescript.org/runtimes/android/advanced-topics/memory-management

#### WIP High Level Overview Here:
 - https://panayotcankov.github.io/nativescript-3.2.0-memory-management/

#### Reference And Memory API
Java references: [java.lang.ref](http://docs.oracle.com/javase/6/docs/api/java/lang/ref/package-summary.html).

Cleaning up after dead Java objects can be done by subclassing WeakReference and waiting for dead objects in a separate Thread.

V8's Persistant SetWeak is used to get called when a JS is about to be collected:
http://bespin.cz/~ondras/html/classv8_1_1PersistentBase.html#aaf342ece1a4ba926ba62e8d6af7be777
Potentially the JS object can be retained again.

We can subscribe for V8 GC prologue and epilogue.

**Comment by PanayotCankov** [comment]
Working on a prototype that acts as follows:

 - When a Java instance marshalled to a JavaScript type, the Java and JavaScript instances are bound,
    - Add finaliser to the JavaScript instance
    - Add a strong reference to the Java instance (this will not let it be garbage collected)

 - When the JavaScript instance's finaliser is called (the JavaScript instance is not reachable)
    - Make the reference to the Java instance weak (this will let it be garbage collected by Java GC)
    - Check the weak reference to the Java instance, if the Java instance is still alive, don't let the JavaScript instance be collected

This approach can lead to instances being collected but doesn't involve long blocks on the main thread.

Further try to remove any calls to GC APIs.
 - Add methods to manually disconnect a JavaScript and Java instance (make the Java reference weak) to allow big resources to be disposed more quickly.
 - For instances created from the Java, we may need API to mark the JavaScript instance as strong.
 - Check where these are used and try to limit manual GC control:
    - gcThrottleTime
    - memoryCheckInterval
    - freeMemoryRatio

**Comment by PanayotCankov** [comment]
There are WIP in this android-runtime branch: https://github.com/NativeScript/android-runtime/tree/marking-mode-none
It allows the `app/package.json` to switch the marking mode:
```
{
  "android": {
    "markingMode": "none"
  }
}
```
This disables the MarkReachableObjects completely and switches to a different memory management model.

When JavaScript and Java instances are associated, the runtime holds strong reference to the Java object. The JavaScript object is added a finaliser, that is triggered on GC that will otherwise collect the JavaScript instance, when it is called the Java reference is changed to weak ref. The JavaScript object is revived, and the runtime keeps reviving the JavaScript instance until the Java instance is collected by Java GC. After that the JavaScript instance is let to be collected by V8 GC.

**Comment by NathanaelA** [comment]
I just saw this comment; are you aware that using Java finalizers are a major issue in Java/Android.  Not only cause performance issues during allocation, (like 500 times slower and cause other perf issues during its life) but in addition they will cost an additional generation of GC for them to all hang around and will cause performance and memory issues during finalization as the finalization thread is serial and if even one finalizer goes haywire (or slow to run) everything else will never be released as the finalizer will hold the memory of the entire object until it can run.   Finalizers are NOT recommended for any usage by anyone at Google, PhatomReferences are a much better way to handle GC linkage.

**Comment by PanayotCankov** [comment]
@NathanaelA,
These are in the V8, not the Java. The implementation in the V8 is much different. On the other side the current runtime implementation installs them anyway, so it won't get any slower. We are actively looking for other solutions.
