### ISSUE TITLE
Where should I find a DateTimePicker

### ISSUE THREAD

**Issue by vinhtiensinh** [NativeScript/NativeScript#4601]
Hi Guys,
Sorry for posting here, it is not really an issue but rather a question..
I've been searching for quite awhile a way to have a datetime picker widget that is similar to the Calendar app on ios but I couldn't find it.

I found this https://www.npmjs.com/package/nativescript-timedatepicker

However the way it slide up from the bottom is not consistent with my app. Is there a way to have datetimepicker that is similar to the one in calendar app

Thanks

**Comment by tsonevn** [comment]
Hi @vinhtiensinh,
At this time the [nativescript-timedatepicker](https://www.npmjs.com/package/nativescript-timedatepicker) is the only available option, which provides similar functionality.
I do not know the exact case, however, I could also suggest using  [Calendar](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/Calendar/overview) component provided by [nativescript-telerik-ui-pro](https://www.npmjs.com/package/nativescript-telerik-ui-pro) plugin.

For any further question, please use our NativeScirpt [forum](https://discourse.nativescript.org/).
