### ISSUE TITLE
Issue with setting up the vertical-align via CSS 

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#4602]
The issue is reproducible when we try to so setup the `vertical-align` for a component inside the ActionBar. For example:
xml
```
<Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        <ActionItem 
            tap="onEditButtonTap" 
            ios.position="right"
            android.position="right">
            <Label  text="Edit" class="action-item"/>
        </ActionItem> 

        </ActionBar>
    </Page.actionBar>
```
CSS
```
.action-item {
    height: 100%;
    vertical-align: center;
} 

```
 Setting it inline in the XML `<Label verticalAlignment="center" text="Edit" class="action-item"/>`  will work, the problem exists only while using CSS class.
Attaching a project, where the problem could be reproduced.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1176863/Archive.zip)

**Comment by jdnichollsc** [comment]
I have the same issue but using icons with resources
```
<ActionBar title="Catalog">
    <ActionItem class="navButton" icon="res://menu" ios.position="left"></ActionItem>
    <SearchBar hint="Search in catalog"></SearchBar>
    <ActionItem class="navButton" icon="res://scan" ios.position="right"></ActionItem>
</ActionBar>
```
<img width="401" alt="captura de pantalla 2017-11-03 a la s 1 50 14 a m" src="https://user-images.githubusercontent.com/2154886/32362707-6140bc14-c039-11e7-8f7e-a3778c62c7e7.png">


Thanks in advance

**Comment by tsonevn** [comment]
After a discussion with the core modules team, we considered that the right approach for setting up the vertical alignment would be to create a custom view with some of the available layouts and then to set up the needed components inside of it. 

In this case, the `verticalAlignment` will be set up correctly via XML code or CSS file.
