### ISSUE TITLE
ECONNRESET when running tns test ios/android

### ISSUE THREAD

**Issue by chris-shepperd** [NativeScript/NativeScript#4604]
I can't test using tns on ios or android.  I continue to get a ECONNRESET error.  I've tried upgrading NativeScript, node, npm all with same results.  I searched for every possible reason for ECONNRESET while running tests and no suggestions have helped...  Below is what I have:

[~/code/learning/nativescript] $ tns create econnreset
Installing  tns-template-hello-world
+ tns-template-hello-world@3.1.0
added 2 packages in 1.157s
Installing  tns-core-modules
+ tns-core-modules@3.1.0
added 2 packages in 2.876s
up to date in 0.131s
Project econnreset was successfully created.

[~/code/learning/nativescript] $ cd econnreset/
[~/code/learning/nativescript/econnreset] $ tns test init
? Select testing framework: jasmine

> fsevents@1.1.2 install /Users/a606521/code/learning/nativescript/econnreset/node_modules/fsevents
> node install

[fsevents] Success: "/Users/a606521/code/learning/nativescript/econnreset/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node" is installed via remote
+ karma@1.7.0
added 297 packages in 34.762s
npm WARN karma-jasmine@1.1.0 requires a peer of jasmine-core@* but none was installed.

+ karma-jasmine@1.1.0
added 1 package in 2.236s
+ jasmine-core@2.6.4
added 1 package in 2.209s
+ karma@1.7.0
updated 1 package in 8.63s
+ karma-nativescript-launcher@0.4.0
added 2 packages in 2.599s

> nativescript-unit-test-runner@0.3.4 postinstall /Users/a606521/code/learning/nativescript/econnreset/node_modules/nativescript-unit-test-runner
> node postinstall.js

+ nativescript-unit-test-runner@0.3.4
added 1 package in 2.224s
Successfully installed plugin nativescript-unit-test-runner.

Example test file created in app/tests/
Run your tests using the "$ tns test <platform>" command.
[~/code/learning/nativescript/econnreset] $ tns test ios
Searching for devices...
26 07 2017 12:58:02.587:WARN [karma]: No captured browser, open http://localhost:9876/
26 07 2017 12:58:02.599:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
26 07 2017 12:58:02.599:INFO [launcher]: Launching browser ios with unlimited concurrency
26 07 2017 12:58:02.607:INFO [launcher]: Starting browser NativeScript Unit Test Runner
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
[~/code/learning/nativescript/econnreset] $ tns test android
Searching for devices...
Starting Android emulator with image Nexus_5X_API_24
Waiting for emulator device initialization...
26 07 2017 12:58:44.456:WARN [karma]: No captured browser, open http://localhost:9876/
26 07 2017 12:58:44.466:WARN [karma]: Port 9876 in use
26 07 2017 12:58:44.467:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9877/
26 07 2017 12:58:44.467:INFO [launcher]: Launching browser android with unlimited concurrency
26 07 2017 12:58:44.483:INFO [launcher]: Starting browser NativeScript Unit Test Runner
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
[~/code/learning/nativescript/econnreset] $ tns --version
3.1.3
[~/code/learning/nativescript/econnreset] $ node --version
v7.10.0
[~/code/learning/nativescript/econnreset] $ npm --version
5.3.0
[~/code/learning/nativescript/econnreset] $ cat package.json
{
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": {
		"id": "org.nativescript.econnreset"
	},
	"dependencies": {
		"nativescript-theme-core": "~1.0.2",
		"nativescript-unit-test-runner": "^0.3.4",
		"tns-core-modules": "3.1.0"
	},
	"devDependencies": {
		"jasmine-core": "^2.6.4",
		"karma": "^1.7.0",
		"karma-jasmine": "^1.1.0",
		"karma-nativescript-launcher": "^0.4.0"
	}
}

**Comment by dtopuzov** [comment]
This issue was moved to NativeScript/nativescript-cli#3024
