### ISSUE TITLE
fontFamily attribute not working in formatted string with binding expression

### ISSUE THREAD

**Issue by clzola** [NativeScript/NativeScript#4608]
I have this XML:

    <Label tap="onWorkingHoursDailyViewClick">
        <Label.formattedText>
            <FormattedString>
                <FormattedString.spans>
                    <Span fontSize="16" text="{{working_hours.status}}" color="{{working_hours.statusColor}}" style="font-weight: bold;"></Span>
                    <Span fontSize="16" text="{{working_hours.statusText}}"></Span>
                
                    
                    <Span text="&#xf230;" fontFamily="FontAwesome"></Span>

                    
                    <Span fontFamily="FontAwesome" text="{{working_hours.isDailyVisibleSign}}"></Span>
                </FormattedString.spans>
            </FormattedString>
        </Label.formattedText>
    </Label>

and I have this code behind:

    export function onNavigateTo(args) {
        // ...
        viewModel.set("working_hours", fromObject({
            status: "Open",
            statusColor: "green",
            statusText: " - Closes at 23:00h",
            isDailyVisible: false,
            isDailyVisibleSign: "&#xf106;"
        }));
        //...
        page.bindingContext = viewModel;
    }
    export function onWorkingHoursDailyViewClick() {
        let workingHours:Observable = <Observable>viewModel.get("working_hours");
        if(workingHours.get("isDailyVisible")) {
            workingHours.set("isDailyVisibleSign", " &#xf106; ");
            workingHours.set("isDailyVisible", false);
        }
        else { 
            workingHours.set("isDailyVisibleSign", " &#xf107; ");
            workingHours.set("isDailyVisible", true);
        }
    }

It prints  "&#xf106" or "&#xf107" (with semi-colon) instead of font awesome icons... But it works if I do not use binding...

**Comment by tsonevn** [comment]
HI @clzola,
Thank you for the attached code snippet,
While using Icon font and changing the icons code from code behind, you should use the String.fromCharCode converter, which will generate a one-letter string from the character.  For more info, you could review [this ](https://docs.nativescript.org/ui/icon-fonts) part of the documentation. also for further help, I am attaching a sample project.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/1197367/Archive.zip)

**Comment by tsonevn** [comment]
Hi @clzola,
Were you able to resolve your case or you still have a problem with using Icon fonts in your project?

**Comment by clzola** [comment]
Yeah, I have resolved the way you said
