### ISSUE TITLE
Create an article describing how to create custom UI plugin

### ISSUE THREAD

**Issue by atanasovg** [NativeScript/NativeScript#461]
With the availability of the {N} [Plugins](https://docs.nativescript.org/plugins), it is now much easier custom UI modules to be created. We need to explain the preferred approach to be followed. The article may consist of the following paragraphs (or these may form separate articles):

- [x] Plugin structure
    - [x] Definition file
    - [x] Common file
    - [x] Platform-specific files
- [x] {N} Visual Tree Lifecycle
    - [x] Android
    - [x] iOS
- [x] Creating the native UI
- [x] Adding CSS(styling) support
- [x] Creating bindable properties
- [x] Raising events

**Comment by jadsonlourenco** [comment]
I saw in another blog article that we can use "native" libraries, third, we will use a library like this in a plugin: https://github.com/okmr-d/DOFavoriteButton ? How? How expose the bindable properties and events to my "view-model" on {N}?

This article will be great to see too. Thank you.

**Comment by atanasovg** [comment]
The article is already available in the [docs](https://github.com/NativeScript/docs/blob/master/ui-plugin.md) repo. Closing the issue.
