### ISSUE TITLE
Executing local tns build for ios with valid provision failed

### ISSUE THREAD

**Issue by ndinev** [NativeScript/NativeScript#4612]
tns version is 3.1.3

Create project 
Try to build it using : tns build ios --provision [valid_provision_file]
Error is: ENOENT: no such file or directory, scandir '/Users/xxxxxx/Library/MobileDevice/Provisoning Profiles'

**Comment by dtopuzov** [comment]
This issue was moved to NativeScript/nativescript-cli#3029
