### ISSUE TITLE
Webview reloads when coming back on the page

### ISSUE THREAD

**Issue by surdu** [NativeScript/NativeScript#4615]
I have a NativeScript Page (i.e. main page) that contains an WebView and means to navigate to another NativeScript Page (i.e. about page).

If I got to the about page, and then come back to the main page, on android only, the webview on the main page will reload with the initial URL.

The fact that on iOS it works as expected leads me to believe it's a bug.

I have this problem on two different applications that I'm working on now, and I also [found another guy on StackOverflow](https://stackoverflow.com/questions/44509915/nativescript-webview-prevent-reload-when-navigating-back-on-android) with the same issue. If it is needed, I will also write a small example app that will illustrate the issue.

I'm using {N} with vanilla JS.

```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 3.1.2           │ 3.1.3          │ Update available │
│ tns-core-modules │ 3.1.0           │ 3.1.0          │ Up to date       │
│ tns-android      │ 3.1.1           │ 3.1.1          │ Up to date       │
│ tns-ios          │ 3.1.0           │ 3.1.0          │ Up to date       │
└──────────────────┴─────────────────┴────────────────┴──────────────────┘



```

**Comment by tsonevn** [comment]
Hi @surdu,
I research this issue and it seems that this is something specific to the Android platform. I found [this ](https://stackoverflow.com/questions/15782166/android-webview-prevent-reload-when-go-back-to-the-app) thread in StackOverflow where it is suggested to set `android:launchMode="singleInstance"` in your `androidmanifest.xml`, which will prevent reloading the WebView page.

**Comment by surdu** [comment]
Nope, that doesn't solve this problem. 😢 

Also, the problem described in that SO question is not reproducible on my apps. In my case, I don't leave the app, just move to another screen (I don't think it's even another activity ?)

**Comment by tsonevn** [comment]
Hi @surdu,
I reviewed further this case and was able to reproduce similar scenario and found that this happens in the cases when you setup the URL for the `WebView` on `navigatingTo` event.
In this case, the URL will be reset every time when you navigating back from the previous page. 

To resolve this you could setup the URL to the Observable outside the event, which will prevent resetting the page. For example:
```
import { EventData, Observable } from 'data/observable';
import { Page } from 'ui/page';
import {topmost} from "ui/frame"
import { HelloWorldModel } from './main-view-model';
var tmpObservable= new Observable();
tmpObservable.set("wurl", "https://google.com");
// Event handler for Page "navigatingTo" event attached in main-page.xml
export function navigatingTo(args: EventData) {

    let page = <Page>args.object;
    console.log("navigating to ")

    page.bindingContext = tmpObservable;
}
export function loadPage(){
    tmpObservable.set("wurl", "https://docs.nativescript.org");
}

export function onTap(){
    topmost().navigate("page2")
}
```
I am also attaching a sample project.

If your scenario is different please provide a sample project.

**Comment by tsonevn** [comment]
Hi @surdu,
Were you able to resolve your case with my latest suggestion?

**Comment by surdu** [comment]
@tsonevn Sorry, managed now to squeeze some time to do it.

In you code, you can change:
`
<WebView height="200" src="{{wurl}}" />
`
into:
`
<WebView height="200" src="https://docs.nativescript.org" />
`

and the problem is still reproducible. Now the src is constant.

**Comment by tsonevn** [comment]
Hi @surdu,
Thank you for your further investigation.
Indeed while setting the value for the src property inline in the XML the WebView page will be reloaded every time, when you navigate back to the previous page. This is caused due to fact that the native WebView will be destroyed and recreated every time when you navigate to the page with WebView.

However, this behavior has been fixed in @next modules and you could test it on your side while following the described steps:

`tns plugin remove tns-core-modules`

`tns plugin add  tns-core-modules@next`

also before rebuild delete `node_modules` and `platforms` folders

**Comment by surdu** [comment]
@tsonevn 

```
$ tns plugin add tns-core-modules@next
[...]

npm WARN nativescript-geolocation@3.0.0 requires a peer of tns-core-modules@^3.0.0 ||
 ^3.0.0-rc.1 || >=3.0.0-2017 but none was installed.

Command npm install tns-core-modules@next --save failed with exit code 1
```

I included that warning, but I don't believe that's the issue, as I get that warning also for tns-core-modules 3.1 and it works just fine.

Any idea how can I make the `tns plugin add` command more verbose in order to see what the problem might be ?

**Comment by hshristov** [comment]
@surdu 
I think you can use `npm i tns-core-modules@next --save` instead of `tns plugin add`.

**Comment by surdu** [comment]
Works! Thanks a lot !

**Comment by abbas5454** [comment]
hiii @tsonevn and @surdu, i have the same problem but i i am using react native webview..
can you tell me how to solve this problem in react native webview

**Comment by surdu** [comment]
@abbas5454 This should have been already fixed. The only thing I did then was update `tns-core-modules@next`, but the fix should be live now in the latest NativeScript version.

**Comment by tsonevn** [comment]
Hi @abbas5454,
If you are facing an issue, while using `nativescript-advanced-webview` plugin, I would suggest contacting [the authors](https://github.com/bradmartin/nativescript-advanced-webview)
