### ISSUE TITLE
WebView not working when there is StackLayout on the page in iOS

### ISSUE THREAD

**Issue by vtrifonov** [NativeScript/NativeScript#4617]
I have some problems using WebView in iOS. It turns out that if there's StackLayout on the page the WebView is not working, it works on Android however. To isolate the issue I've created a new application with the following template:
`tns create layout --tsc`

I'm using the currently latest version of the **tns** -  _3.1.2_

Here's the changed code of the main-page.xml:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page" actionBarHidden="true" backgroundColor="green">
    <WebView src="https://www.google.com" />
    <StackLayout></StackLayout>
</Page>
```

Here's the result:
![Screenshot](http://i.imgur.com/HBacbZ2.png)

**Comment by runbb** [comment]
try 
```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page" actionBarHidden="true" backgroundColor="green">
    <StackLayout>
        <WebView src="https://www.google.com" />
    </StackLayout>
</Page>
```

**Comment by hshristov** [comment]
@vtrifonov `Page` can have only 1 child. So adding `StackLayout` removes the `WebView`.

**Comment by vtrifonov** [comment]
@runbb did you try this?

Here's the result with the following snippet:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page" actionBarHidden="true" backgroundColor="green">
    <StackLayout>
        <WebView src="https://www.google.com" />
    </StackLayout>
</Page>
```

![Screenshot](http://i.imgur.com/MPGUyJT.png)

I've tried several configurations, with GridLayout, with StackLayout, with the WebView inside the layout and outside the layout. All the configurations work on Android and none of them having StackLayout work on iOS!

As I see it having more than one child is another problem as I think it should have the same behaviour on iOS and Android as well - either throwing an error or not working on both platforms.

**Comment by tsonevn** [comment]
Hi @vtrifonov,
While using GridLayout for the parent of the WebView, the component will be shown properly and the page will be loaded. Could you verify again this problem on your side? I am attaching the sample project, which I used for testing? Could you also verify, whether I am missing something in the project?
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1187560/Archive.zip)
![screen shot 2017-07-31 at 3 47 33 pm](https://user-images.githubusercontent.com/17448734/28778374-a088857c-7607-11e7-9fbb-c19fd9a81b62.png)

**Comment by vtrifonov** [comment]
Hi @tsonevn,
It works with GridLayout but doesn't work with StackLayout, is it something expected? As it works on Android?

**Comment by tsonevn** [comment]
Hi @vtrifonov,
In case you need to use StackLayout, you need to specify the height on the inner components, otherwise, the child component will not be sized correctly. This is behavior valid only on iOS.

**Comment by vtrifonov** [comment]
I see, that makes sense, but I didn't found that information in the documentation however. 
Thanks!
