### ISSUE TITLE
Expose list item index to be accesseable in xml

### ISSUE THREAD

**Issue by terreb** [NativeScript/NativeScript#4622]
This is not an issue but rather a proposal. Sometimes there is a case when we need to apply different classes for the first/last list item or even or odd items in XML. I know this can be done in the code behind or by having index or id set explicitly for each ObservableArray item, but it would be great to have access to item index already by default, since this is something of very common  usage for many apps. It can be something like $value._index or whatever.

**Comment by terreb** [comment]
Ok, I found what I needed. The item index is already exposed and can be accessed as $parent.$index in XML. However this is not documented and would be nice to have this still documented. The issue can be closed.

**Comment by terreb** [comment]
For people struggling to achieve the same I will leave this xml snippet hoping it will help to understand how this works:

```xml  
      <ListView items="{{ items }}">
            <ListView.itemTemplate>
                <GridLayout columns="* auto" class="{{ $parents['ListView'].items, $parents['ListView'].items.length !== $parent.$index+1 ? 'list-item' : 'list-item last-list-item' }}">
                    <Label text="{{ title || 'Loading...' }}" col="0"/>
                    <Label text="&#xf105;" col="2" class="icon list-expand-icon"/>
                </GridLayout>
            </ListView.itemTemplate>
        </ListView>
```

Please note the items should be accessed in this particular case as $parents['ListView'].items and not $parent.items which didn't work for me (though I might be doing something wrong).

**Comment by terreb** [comment]
Ok, actually the code above not working properly since I removed something from it which seems the trick for $parent.$index to be exposed inside list items. The key is to add itemTemplateSelector="$index" first. So, the working code would be:

```xml  
      <ListView items="{{ items }}" itemTemplateSelector="$index">
            <ListView.itemTemplate>
                <GridLayout columns="* auto" class="{{ $parents['ListView'].items, $parents['ListView'].items.length !== $parent.$index+1 ? 'list-item' : 'list-item last-list-item' }}">
                    <Label text="{{ title || 'Loading...' }}" col="0"/>
                    <Label text="&#xf105;" col="2" class="icon list-expand-icon"/>
                </GridLayout>
            </ListView.itemTemplate>
        </ListView>
```

**Comment by terreb** [comment]
The above is actually look bad and thus I still ask for $parent.$index to be accessible inside list items without  having to add itemTemplateSelector="$index" to the list view.

**Comment by terreb** [comment]
Hmm, class="{{ $parents['ListView'].items, $parents['ListView'].items.length !== $parent.$index+1 ? 'list-item' : 'list-item last-list-item' }}" doesn't trigger the last-list-item class to be added to the last item, however 

```xml
<Label text="{{ $parents['ListView'].items, $parents['ListView'].items.length !== $parent.$index+1 ? 'list-item' : 'list-item last-list-item' }}"  />
```

...does correctly set text "list-item last-list-item" only to the last item.

Could you guys explain please why it's not working in class but working in label text?

**Comment by tsonevn** [comment]
Hi @terreb, 
Could you send us a sample project, where your case could be tested on our side locally? It would help us verify your exact case.

**Comment by tsonevn** [comment]
Hi @terreb,
thank you for the attached example.
I tested it on my side and indeed the `$index` will return the correct index of the items and it could be used for applying an extra styling to the items.

**Comment by terreb** [comment]
@tsonevn, yep, but only if itemTemplateSelector="$index" is added to ListView. Without that $index won't be exposed in list view item.

**Comment by tsonevn** [comment]
Hi @terreb,
While declaring `$index` property in side the `itemTemplateSelector` you will have access to the context of the current item. In this case, the index of the item will be assigned to the `$index` and you will have the ability to use it in the itemTemplate.

**Comment by terreb** [comment]
@tsonevn, thank you, I've got it!

**Comment by terreb** [comment]
I guess the issue can be closed.
