### ISSUE TITLE
Can't build with aot when i am using lazy loading

### ISSUE THREAD

**Issue by gtzinos** [NativeScript/NativeScript#4630]
Hi,
I followed this guide (http://docs.nativescript.org/angular/best-practices/bundling-with-webpack.html#introducing-webpack) on this project (https://github.com/sis0k0/lazyNinjas) which you present the lazy loading in a nativescript app but i am getting the following error message:

ERROR in Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'routes'. Consider exporting the symbol (position 5:7 in the original .ts file), resolving symbol routing in /my-path/app/app-routing.ts, resolving symbol AppModule in /my-path/lazyNinjas/app/app.module.ts, resolving symbol AppModule in /my-path/lazyNinjas/app/app.module.ts

Steps to reproduce:

git clone https://github.com/sis0k0/lazyNinjas
npm install
npm install --save-dev nativescript-dev-webpack
npm install
npm run start-android-bundle

**Comment by tsonevn** [comment]
Hi @gtzinos,
Thank you for pointing this case, 
The above-mentioned project is not configurated to use webpack technique. We will upgrade the project and will provide the needed changes, however, I could not commit to the exact time when this will be ready.

Regarding the problem, to be able to use the lazy loading with webpack we need to setup the correct the path  for the `loadChildren` component. We should setup the relative path to the module and the after the `#` we need to set the name of the exported module. For example:
```
// ex. app.routes.ts
{
       path: "ninjas",
       loadChildren: "./ninjas/ninjas.module#NinjasModule",
}
```

At that, we should also to provide the module loader in the root NgModule, which will load the needed modules. 
```
// app.module.ts
import { NgModuleFactoryLoader } from "@angular/core";
import { NSModuleFactoryLoader } from "nativescript-angular/router";

@NgModule({
    providers: [
        { provide: NgModuleFactoryLoader, useClass: NSModuleFactoryLoader }
    ]
...
})
export class AppModule { }
```
Also, you could review the sample project [here](https://github.com/NativeScript/nativescript-sdk-examples-ng), where is demonstrated, how to use the both lazy loading and webpack in the same app
Hope this helps.

**Comment by gtzinos** [comment]
Thank you very much. Now it works. The above project is using older packages versions but the lazy loading it works for me.

**Comment by tsonevn** [comment]
duplicated with [#4639](https://github.com/NativeScript/NativeScript/issues/4639)

**Comment by gtzinos** [comment]
@tsonevn  you closed both of them.
