### ISSUE TITLE
Nativescript-core: How to remove default styles(like padding, margin) of Page tag in XML

### ISSUE THREAD

**Issue by sagar1911** [NativeScript/NativeScript#4631]
I have tried
Page {
padding:0;
margin:0;
}

but didn’t work.

Any solution ??

Thanks…

**Comment by tsonevn** [comment]
Hi @sagar1911,


Could you provide some more info about your case and info about the issue, which you have? 
Bear in mind that together with the default templates in NativeScript, `nativescript-theme-core` plugin is added as a dependency. The theme provides some basic styling and perhaps it could add some styling by default. To remove the theme you could open your project app.css file and remove the following line `@import 'nativescript-theme-core/css/core.light.css';`

**Comment by sagar1911** [comment]
Hi @tsonevn ,

Thank you for responding. I have removed the theme but nothing happening.

here is my code

xml code
<FlexboxLayout justifyContent="space-between" class="footer-buttons">
            <Button text="Reset" class="button reset-button"/>
            <Button text="Submit" class="button submit-button" />
</FlexboxLayout>

css code
.footer-buttons {
    width: 100%;
}
.button{
    width: 50%;
    padding: 28 77;
    font-size: 15;
    text-transform: none;
    color: #ffffff;
}
.reset-button {
    background-color: #06333e;
}
.submit-button {
    background-color: #e84f39;
}

So,
The case is i want 'reset-button' to stretch completely to the left and 'submit-button' to completely to the right while they are adjacent to each other.

Thank You.

**Comment by tsonevn** [comment]
Hi @sagar1911,
I investigate further your case and I it seems that those default margins to buttons are coming from the [Android theme](https://stackoverflow.com/questions/38175142/remove-margin-from-android-buttons).
Regarding that, I could suggest setting a negative number for the button margin, which will stretch the component completely to the left and to the right. For example:

```
.footer-buttons {
width: 100%;
}
.button{
width: 50%;
margin: -5;
padding: 28 77;
font-size: 15;
text-transform: none;
color: #ffffff;
}
.reset-button {
background-color: #06333e;
}
.submit-button {
background-color: #e84f39;
}
```

**Comment by sagar1911** [comment]
Hi Nikolay Tsonev

Thank you Problem solved. 😀

Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com

**Comment by sagar1911** [comment]
I want to fix a button at the bottom and i dont want it to change its
position while scrolling(like we do it in html using position:fixed).
can we do that in nativescript-core ?


Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com

**Comment by tsonevn** [comment]
Hi @sagar1911,
You could use AbsoluteLayout, where you could also specify the exact position of the element while setting up top and left position of the component. more info and example could be found [here](https://docs.nativescript.org/ui/layout-containers#absolutelayout) .

**Comment by sagar1911** [comment]
Hi,

.footer-buttons {
width: 100%;
}
.button{
width: 50%;
padding: 28 77;
font-size: 15;
text-transform: none;
color: #ffffff;

}
.reset-button {
background-color: #06333e;
}
.submit-button {
background-color: #e84f39;
}

for the above problem

.footer-buttons {
width: 100%;
}
.button{
width: 50%;
margin: -5;
padding: 28 77;

border-width: 0.01; ---------------------- this worked fine

font-size: 15; text-transform: none; color: #ffffff; } .reset-button {
background-color: #06333e; } .submit-button { background-color: #e84f39; }


Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com

**Comment by sagar1911** [comment]
Hi,
When user clicks on an item in repeater I want only that item to be
highlighted and other items should be in non-selective mode. How can i do
that ?

Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com

**Comment by sagar1911** [comment]
can I get a solution from you for this ..??
https://discourse.nativescript.org/t/ui-floating-button-in-nativescript-core/2211/10

Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com

**Comment by tsonevn** [comment]
Hi @sagar1911,
Did you add the needed namespace inside the XML, which is needed while using the `nativescript-floatingactionbutton` plugin, For example:
```
xmlns:FAB="nativescript-floatingactionbutton"
```
For further help, you could also review the plugin's [demo ](https://github.com/bradmartin/nativescript-floatingactionbutton/blob/master/demo/app/main-page.xml#L2) app.
If the problem still exists, please provide a sample app, which I could debug locally.

**Comment by sagar1911** [comment]
Hi Nikolay,
Thanks for the response but I have implemented it without plugin :)

Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com

**Comment by tsonevn** [comment]
Hi @sagar1911,
If I understand you correctly you were able to resolve your problem, while using your custom implementation.
Is this correct or you still have a problem?

**Comment by sagar1911** [comment]
No sir, I don't have any problem now . :)
Thank you

Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com
