### ISSUE TITLE
Is it possible for app user to select location using google maps in nativescript ?? Developer should get that location for further processing ..

### ISSUE THREAD

**Issue by sagar1911** [NativeScript/NativeScript#4632]

**Comment by tsonevn** [comment]
Hi @sagar1911,
Thank you for your interest in NativeScirpt. 
First of all, I would like to notify you that the `nativescript-googlemaps` has been deprecated in favor of `nativescript-google-maps-sdk`. After a little research, I found that in the plugin there is coordinateTapped method, which could be used for your case. As it is described [here](https://github.com/dapriett/nativescript-google-maps-sdk) in the plugin's repo, the event will be fired when a coordinate is clicked on the map. Also, you could verify the demo [app](https://github.com/dapriett/nativescript-google-maps-sdk/tree/master/demo).

For further questions, please use the NativeScritp forum [here](https://discourse.nativescript.org/).

**Comment by sagar1911** [comment]
Thank You @tsonevn for the resources .
