### ISSUE TITLE
Local dependency brakes build

### ISSUE THREAD

**Issue by surdu** [NativeScript/NativeScript#4634]
After upgrading nativescript to 3.1.3 I have the following error in my project when I try to build:

```
Unable to apply changes on device: <device-id>. Error is: cp: cannot create directory 
'/Users/<user>/work/<project>/platforms/android/src/main/assets/app/tns_modules': No such 
file or directory.
```

Did a little investigation and realized the problem is a local dependency in my package JSON:

```
nativescript-local-notifications": "file:../nativescript-local-notifications"
```

Taking this out make the app build again.

The weird part is that's not the only local dependency in my project, I have another that doesn't brakes the build. 

I can confirm the problem is only in 3.1.3 because I reverted back to 3.1.2 (twice) and the problem is not reproducible using that version.

For context, here is the full dependencies entry:

```
  "dependencies": {
    "moment": "^2.18.1",
    "nativescript-activity-detection": "file:../nativescript-activity-detection",
    "nativescript-android-utils": "^1.0.2",
    "nativescript-geolocation": "^3.0.0",
    "nativescript-local-notifications": "file:../nativescript-local-notifications",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-webview-interface": "^1.4.1",
    "tns-core-modules": "^3.1.0"
  }
```

**Comment by tsonevn** [comment]
Hi @surdu,
I tested your case on my side while using latest NativeScript CLI and local tgz file for the plugin, however, I was unable to reproduce this scenario. I am attaching my sample project together with the plugin. 
Could you provide some info about the Android device, which you are using for testing? Also, could you check if in the main app folder of the project there is tns_modules folder? If so this could be the reason for this problem and you should delete it. Then you will be able to build the project successfully.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1190333/Archive.zip)

**Comment by dtopuzov** [comment]
This issue was moved to NativeScript/nativescript-cli#3028
