### ISSUE TITLE
[Android] TabView title is wrapped in two rows

### ISSUE THREAD

**Issue by vegeorgi** [NativeScript/NativeScript#4637]
### Tell us about the problem

I have an app with 5 tab items - [link ](https://github.com/NativeScript/template-tab-navigation-ng)
When opened the app on an emulator which is api 23 or above, some of the items fall down on two rows. - [screen shot](https://www.screencast.com/t/ELj2W0WSd). If i add a couple more items, e.g the count of the items is 9, the item's  text is rendered fine, on a single line. 

### Which platform(s) does your issue occur on?

Android

### Please provide the following version numbers that your issue occurs with:

[package.json](https://github.com/NativeScript/template-tab-navigation-ng/blob/master/package.json)

### Please tell us how to recreate the issue in as much detail as possible.

link to the app - [here](https://github.com/NativeScript/template-tab-navigation-ng)

**Comment by vakrilov** [comment]
I think wrapping the tab title on two lines is acceptable according to the [material design guide](https://material.io/guidelines/components/tabs.html#tabs-content). Also the suggestions is to have all tabs with equal width.

Can you please elaborate more on what do you expect to happen in different cases.

To clarify a little bit more: currently the implementation of the tab has [some constants](https://github.com/NativeScript/tns-core-modules-widgets/blob/master/android/widgets/src/main/java/org/nativescript/widgets/TabLayout.java#L223-L257) (including text max width) that we took from the material design guide. There is also an option that we can expose that will allow variable-tab-widths, although I would advise agains it as it doe not comply with the material design guidelines.

**Comment by prestopasto** [comment]
The material design guide says that fixed tabs have equal widths, but also that scrollable tabs can have longer tab labels, and presumably not be constrained to equal widths.

I'm in a similar situation to @vegeorgi where 2 of my 4 tab labels are being wrapped/truncated while being only slightly longer than the others. 

I would agree that for very long labels there is a need to wrap or '...', but for labels that are slightly too long it creates a very unprofessional look to have a single word split on two lines.  I don't know where to draw the line on what gets split and what doesn't, so exposing an option and leaving it up to the developer to asses their situation might be for the best.

**Comment by tsonevn** [comment]
Changing the label of the issue to feature request. We will need to introduce some new functionality, which allows control of the width for every TabViewItem, which will also allow properly sizing the width for the label.

**Comment by dbay920** [comment]
Please view [screenshot](https://www.primary-health.net/review/screenshot_1-24.png) to see my dilemma. I don't see how this can be considered acceptable, please address this issue.

**Comment by manojdcoder** [comment]
If anyone looking for a workaround, [here you go](https://play.nativescript.org/?template=play-ng&id=8rie9E&v=2).

**Comment by prestopasto** [comment]
@manojdcoder That workaround worked great for me until recently.  Maybe around the 4.0 or 4.1 update... Not exactly sure when.

It works the first time the TabView is loaded, but if I navigate away and then back when it runs again the tabCount is zero and my tabs are back to equal width.  Anyone else seeing that behavior?

**Comment by manojdcoder** [comment]
@Aceman18 Adding a 100ms timeout in loaded event seems to fix the issue, I will let you guys know if I find time to debug this further.

**Comment by Aceman18** [comment]
@manojdcoder Ok thank you that should work.

**Comment by NickIliev** [comment]
Closing this one as the behavior is what is expected when following the Material guidelines and at the same time we have[ an applicable solution provided by @manojdcoder](https://github.com/NativeScript/NativeScript/issues/4637#issuecomment-360229194)
