### ISSUE TITLE
github.com/Update lazy-loading + AoT compilation demo project and blog post

### ISSUE THREAD

**Issue by gtzinos** [NativeScript/NativeScript#4639]
Its better to create a new project or to update your existing one, with latest packages versions, in order to present us best practises for aot compilation with lazy loading. It will helps developers to understand how can they make their app faster. At this time i am trying to fix the boot time (8-11 seconds) and the app size (35mb) when i am using both of lazy loading and aot. Maybe i do something wrong but how do i know it when i can't find something up to date to read it ?

**Comment by sis0k0** [comment]
@gtzinos 
Thanks for the feedback! We'll definitely to update the existing [demo project](github.com/sis0k0/lazyNinjas) and the corresponding [blog post](https://www.nativescript.org/blog/optimizing-app-loading-time-with-angular-2-lazy-loading) in the next few days.

**Comment by gtzinos** [comment]
This is great, thank you very much.

**Comment by sis0k0** [comment]
The article and the demo app are updated now.
https://www.nativescript.org/blog/optimizing-app-loading-time-with-angular-2-lazy-loading
github.com/sis0k0/lazyNinjas
