### ISSUE TITLE
How to give different colors for actions in one page in mobile android

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#4643]
![actionitem icon color](https://user-images.githubusercontent.com/10844041/28862407-9c8b51e4-7782-11e7-9546-7aac97bf31ea.PNG)

1.Action Item
2. Drop down as shown in the figure

how to give different colors for action Item Icon and drop down Icon

**Comment by tsonevn** [comment]
Hi @dhanalakshmitawwa,
Similar topic has been discussed [here ](https://github.com/NativeScript/nativescript-angular/issues/299#) on this issue. You could review this [comment ](https://github.com/NativeScript/nativescript-angular/issues/299#issuecomment-227159368)and the suggestion described in it.

For further questions please use NatuiveScript [forum](https://discourse.nativescript.org/)

**Comment by dhanalakshmitawwa** [comment]
Thank you for reply
