### ISSUE TITLE
Can we use an image in place of dragger in nativescript-core slider. ?

### ISSUE THREAD

**Issue by sagar1911** [NativeScript/NativeScript#4645]

**Comment by tsonevn** [comment]
Hi @sagar1911,
Thank you for contacting us,
regarding your question, the slider component does not support a change of the thumb image. Something that I could suggest to access the native instance of the object while using its android and ios property and to follow the suggestion in those StackOverflow threads. [Android](https://stackoverflow.com/a/9732840/6133327), [iOS](https://stackoverflow.com/a/7371872/6133327)

For example:
```
<Slider loaded="slloaded" />
```

```
export function slloaded(args){
var slider:Slider = <Slider>args.object;
//slider.ios
//slider.android
}
```

For further questions, please use our NativeScript forum [here](https://discourse.nativescript.org/).

**Comment by sagar1911** [comment]
Yay, Thanks a lot sir

Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com
