### ISSUE TITLE
While I am using .svg images I am getting error as 'BUILD FAILED'. is nativescript don't have support for .svg files or any alternative we have for using the same ??

### ISSUE THREAD

**Issue by sagar1911** [NativeScript/NativeScript#4649]

**Comment by tsonevn** [comment]
Hi @sagar1911,
The Image component does not support SVG format, however, for this case, you could use nativescript-SVG plugin, which provides this functionality. 
Bear in mind that the latest version is not published correctly from the auhor and to be able to use it I created a custom tgz file, which could be used in your project.  To install the tgz file you could use `tgz plugin add <tgz_path>` For further info how to use it,  you could use the examples from the plugins [repository](https://github.com/peoplewareDo/nativescript-svg). Something more, to be able to use the attached file you need to remove the zip extension from the app name
[nativescript-svg-1.3.4.tgz.zip](https://github.com/NativeScript/NativeScript/files/1196790/nativescript-svg-1.3.4.tgz.zip)

**Comment by sagar1911** [comment]
Thanks. I will try

Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com

**Comment by daulet2030** [comment]
I think you ment `tns plugin add <tgz_path>`. I installed your plugin, but svg is not displayed on android (dont know about iOS), I am using nativescript.svg located in demo-angular\app\images folder

**Comment by throwingdarts** [comment]
Have you tried a webview?

https://docs.nativescript.org/ui/ns-ui-widgets/web-view#source-load
