### ISSUE TITLE
WrappedValue not working 

### ISSUE THREAD

**Issue by rhanb** [NativeScript/NativeScript#4651]
Hi,

While I was coding [this plugin](https://github.com/rhanb/nativescript-fancy-calendar), I wanted to be able to have two "BIG" properties rather than a ton of "SMALL" properties.
Here is an example of one of those "BIG" property:

```typescript
class Settings {
            displayMode: DISPLAY_MODE.MONTH, 
            scrollOrientation: SCROLL_ORIENTATION.HORIZONTAL,
            selectionMode: SELECTION_MODE.MULTIPLE,
            firstWeekday: 3, // SUN: O, MON: 1, TUES: 2 etc..
            maximumDate: nextMonth, // Can't go further than this date
            minimumDate: lastMonth // can't go earlier than this date
};

export const settingsProperty = new Property<CalendarBase, Settings>({
    name: "settings"
});
settingsProperty.register(CalendarBase);
```

Unfortunately when a changement is made on one of the "BIG" property for example:

`this.settings.displayMode = DISPLAY_MODE.WEEK`

The callback `[settingsProperty.setNative](newSettings: Settings)` is not triggered since by default property change will not be fired for a same object. 

So I'm trying to use [WrappedValue](http://docs.nativescript.org/api-reference/classes/_data_observable_.wrappedvalue.html) class to avoid that.
My best attempt for now was to change the `Property` type to `WrappedValue` instead of `Settings` like this:

```typescript
export const settingsProperty = new Property<CalendarBase, WrappedValue>({
    name: "settings"
});
settingsProperty.register(CalendarBase);
```
And then initialise the property like this:

```typescript
let settings = <Settings>{
            displayMode: DISPLAY_MODE.MONTH,
            selectionMode: SELECTION_MODE.SINGLE,
            scrollOrientation: SCROLL_ORIENTATION.HORIZONTAL,
            firstWeekday: 3,
            minimumDate: undefined,
            maximumDate: undefined
};
this.settings = WrappedValue.wrap(settings);
```
But still doesn't work..

Hope I'm clear and somebody will be able to help me!

Cheers from France 😄

**Comment by hshristov** [comment]
Hi @rhanb,

You shouldn't change the type of your property to `WrappedValue`. It should be of type `Settings`.
Changing it should be done in the following way:
```
var currentSettings = calendar.settings;
currentSettings.firstWeek = 4;
calendar.settings = WrappedValue.wrap(currentSettings);
```

**Comment by rhanb** [comment]
hi @hshristov ,

Thanks for you answer. 
Ok so I see how `WrappedValue` works now. Since I want to make a plugin, I don't want the consumer to have to wrap the value each time he changes it. 
So, is there a solution to do that? I've looked into the API to find out about `WrappedValue` but maybe it"s not what I should use. 

To resume what I would like to do, here is an example (on the consumer side) in Angular: 

### app.component.ts
```typescript
imports here ...
register element here ... 

@Component({
    selector: "ns-app",
    templateUrl: "app.component.html",
})
export class AppComponent {

    public settings: Settings;

    public calendarLoaded(event) {
        this.settings = <Settings>{
            displayMode: DISPLAY_MODE.MONTH,
            selectionMode: SELECTION_MODE.SINGLE,
            scrollOrientation: SCROLL_ORIENTATION.HORIZONTAL,
            firstWeekday: 3
        };
    }
}
```
### app.component.html
```xml
 <Calendar backgroundColor="#686B74" row="0" [settings]="settings"(loaded)="calendarLoaded($event)">
    </Calendar>
```
Now let's assume that the consumer wants to let his users to change the displayMode on the fly. So he implements the following function in his component:

```typescript
public changeDisplayMode() {
    this.settings.displayMode = this.settings.displayMode === DISPLAY_MODE.MONTH ? DISPLAY_MODE.WEEK : DISPLAY_MODE.MONTH;
}
```
Since `settings` is a property on the `Calendar` `View`, when the consumer changes its value it should trigger `[settingsProperty.setNative]`. 

But it does not, to trigger `[settingsProperty.setNative]` the consumer has to recreate an object with a new ref and then affect its property through this new object. like this:

```typescript
this.settings = <Settings>{
        displayMode: displayModeValue,
        scrollOrientation: this.settings.scrollOrientation,
        selectionMode: this.settings.selectionMode,
        firstWeekday: this.settings.firstWeekday,
        maximumDate: this.settings.maximumDate,
        minimumDate: this.settings.minimumDate
}
```

That's why I go the idea to use `WrappedValue` to avoid that. 
I also got the idea to make the class `Settings extends Observable` and then keep a `WeakRef` of the `Calendar` instance and then `notify` the `Calendar` instance when one of the attributes of `Settings` changes (that means that i'll have to set listeners on the `Calendar` class).

I Hope I'm clear 😄

**Comment by hshristov** [comment]
Hi @rhanb,

One option is to use the `WrappedValue` like shown above. This way a user won't need to recreate the whole `Settings` object but only change a value and the set it like this:
```
this.settings.displayMode = this.settings.displayMode === DISPLAY_MODE.MONTH ? DISPLAY_MODE.WEEK : DISPLAY_MODE.MONTH;
this.settings = WrappedValue.wrap(this.settings)
```

The other option is to make `Settings` type extends `Observable` then attach listener for `propertyChange` event on that observable (and detach it in the `valueChange` handler of Settings property. Then in the `valueChange` handler you could check if there is `nativeView` field and if there is you can call the `[settingsProperty.setNative]` like any other methods (e.g. `this[settingsProperty.setNative] = newValue`). 
It is a little bit manually but it should work.

**Comment by rhanb** [comment]
Hi @hshristov ,

I was on the good path apparently, that's cool! I will try to implement the second option, your tips are really useful! 

Thanks you very much for your help and your time 😄 
Cheers
