### ISSUE TITLE
How to change selected tab  borderBottomColor. I alreay tried with this property but unable to get the result. It always showing "blue" colored bottom border.

### ISSUE THREAD

**Issue by vijaykumarbollavaram** [NativeScript/NativeScript#4653]

**Comment by tsonevn** [comment]
Hi @vijaykumarbollavaram, 
To change the bottom border color of the tab on Android you could use [androidSelectedTabHighlightColor](http://docs.nativescript.org/api-reference/classes/_ui_tab_view_.tabview.html#androidselectedtabhighlightcolor).
