### ISSUE TITLE
How to get the value entered in a textfield directly ? without using viewmodel ??

### ISSUE THREAD

**Issue by sagar1911** [NativeScript/NativeScript#4654]

**Comment by tsonevn** [comment]
Hi @sagar1911,
For your case, you could review the below-attached articles, where it is described, how to use data-binding in NativeScript.
[NativeScript TypeScript](https://docs.nativescript.org/core-concepts/data-binding)
[NativeScript Angular](https://docs.nativescript.org/core-concepts/angular-data-binding)
Please for any others "How to question" use our NativeScript [forum](https://discourse.nativescript.org/).

**Comment by sagar1911** [comment]
Hi Nikolay Tsonev,

Sorry for disturbing you but Im in little hurry. So, my question is by
mentioning "res://image" will it load image for both android and ios from
their respective platforms ?

Thank You


Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com

**Comment by tsonevn** [comment]
Hi @sagar1911,
Indeed it will load the image for both platforms, however, make sure that the needed image is added in the App_Resources folder for both of them as it is described [here ](https://docs.nativescript.org/ui/images#load-images-from-a-resource) in the documentation.

**Comment by sagar1911** [comment]
Yes. we got to know that thanks a lot

Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com

**Comment by sagar1911** [comment]
Is it possible to add a floating button in nativescript apps ? the button
should be fixed(at bottom, top or anywhere) all the time even the user
scrolling the app page. ?

**Comment by tsonevn** [comment]
You could use [nativescript-floatingactionbutton](https://github.com/bradmartin/nativescript-floatingactionbutton) plugin, which provides this functionality.

For any further questions please use our NativeScript forum [here](https://discourse.nativescript.org/).
