### ISSUE TITLE
Execution failed for task ':asbg:runAstParser', when running in Android studio

### ISSUE THREAD

**Issue by goforu** [NativeScript/NativeScript#4659]

**Comment by goforu** [comment]
I can run "tns run android" directly and it complies without problems. But when I import my project to Android Studio, gradle is not working properly. Check out the [detail](https://stackoverflow.com/questions/45530185/how-to-debug-nativescript-java-code-in-android-studio)

**Comment by goforu** [comment]
package.json:
`{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.WeiYi",
    "tns-android": {
      "version": "3.1.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/router": "~4.1.0",
    "nativescript-angular": "~3.1.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "~3.1.0",
    "ts-md5": "^1.2.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.25.0",
    "babel-types": "6.25.0",
    "babylon": "6.17.4",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.5.0",
    "tns-platform-declarations": "^3.1.0",
    "typescript": "~2.2.1"
  }
}
`

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#816
