### ISSUE TITLE
NativeScript node modules require fails if "main" is not present

### ISSUE THREAD

**Issue by NekR** [NativeScript/NativeScript#466]
See this module: https://github.com/sindresorhus/object-assign
It does not have "main" entry in package.json but it works fine with npm and node. However, when trying to use it with NativeScript, it says: ``module "object-assign" is not found``. Adding "main" field to ``object-assign``s package.json fixes problem.

Spent some time to figure out what is going on :-)

**Comment by arthurvr** [comment]
Kindof a duplicate issue. From https://github.com/NativeScript/NativeScript/issues/25:

> The JavaScript module loading will use the same technique we are currently using in the runtimes when a module is required. If a JavaScript file is specified in the package.json's main key we will load that otherwise we will look for index.js file in the root.

**Comment by NekR** [comment]
I thought that Plugins are shipped already so it's probably post that issue bug.

**Comment by enchev** [comment]
Hey folks,

I've just tested this and everything worked as expected in both iOS and Android. Can you check if you are using our latest release?

Thanks

**Comment by NekR** [comment]
@enchev I had that issue with {N} 1.1. I am currently not able to test it with 1.2, but if it works then great. Thanks!
