### ISSUE TITLE
cachePagesOnNavigate doesn't work properly on Android 7.1

### ISSUE THREAD

**Issue by MIYankov** [NativeScript/NativeScript#4660]
### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.1.3
- Cross-platform modules: 3.1.0
- Runtime(s): 3.1.1

### Please tell us how to recreate the issue in as much detail as possible.

Run the following command. It will create a project that reproduces the problem. The problem is best observed when you have 3 consecutive navigations liek master->detail->edit:

```tns create master-detail-ts-page-cache --template https://github.com/NativeScript/template-master-detail-ts#myankov/android-page-cache```

It has topmost().android.cachePagesOnNavigate = true; on the first page - /cars/cars-list-page.ts

Reproduces on Android 7.1 (emulator too). On Android 6 it works fine. Steps:
1. Select a car.
2. Tap Edit in the top right corner.
3. Tap Cancel or the hardware back button.
4. Tap Edit again - nothing happens. The page is frozen. It seems it lost context?

Fun fact: If you tap the Edit button several times and then the hardware back button several times, some navigations execute in quick succession. Eventually there is an error "corrupted navigation stack".

**Comment by tsonevn** [comment]
@hshristov

**Comment by hshristov** [comment]
@MIYankov @tsonevn 
I have checked in a lot of changes in the master branch. I tried to reproduce the issue but I can't with master. Could you also verify that everything is ok on your end?

**Comment by MIYankov** [comment]
@hshristov I can confirm that the bug is fixed with @next. However, for some reason the RadListView component from UI for NativeScript doesn't work with these changes.

**Comment by SvetoslavTsenov** [comment]
Hi @MIYankov, 
This should be resolved automatically with next official version of RadListView.
