### ISSUE TITLE
TimePicker – `minuteInterval` property does not apply on iOS

### ISSUE THREAD

**Issue by ickata** [NativeScript/NativeScript#4662]
Hi,

After upgrading {N} from 2.5.4 to 3.1.3 I am not able to set `minuteInterval` property to a `TimePicker` instance anymore. Reproduces on iOS only. Works fine on Android. 

My code:

```
<TimePicker android:scaleY="0.7" hour="{{ hour }}" minute="{{ minute }}" loaded="onTimePickerLoad" verticalAlignment="center" horizontalAlignment="center" colSpan="2" row="8" visibility="{{ !is_loading ? 'visible' : 'collapsed' }}"/>
```

```
   onTimePickerLoad : function ( args ) {
      args.object.minuteInterval = 5;
   },
```

TNS version 3.1.3
tns-core-modules: 3.1.0
tns-ios: 3.1.0
tns-android: 3.1.1

**Comment by NickIliev** [comment]
Confirming this as unexpected behavior on iOS.
Steps to reproduce - run [this application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4662). On iOS the time interval is not applied while on Android the interval is applied on user interaction.

**Comment by gregersen79** [comment]
Experiencing the same issue on {N} 3.2.0. Any updates on when this issue will be fixed. Or perhaps a workaround?

**Comment by Macarthurval** [comment]
Very simple workaround here:

`if( timePicker.ios ) timePicker.ios.minuteInterval = 15;`

**Comment by tsonevn** [comment]
This issue is also reproduced on Android while using NativeScript 3.3.0.
