### ISSUE TITLE
There is no guide to create avd on linux

### ISSUE THREAD

**Issue by erkanarslan** [NativeScript/NativeScript#4673]
Nativescript installation guide asks users to install "sdk tools only" option for android sdk installation. However, when creating an avd, guide uses Android Studio. We need a guide to create an avd without Android Studio.

**Comment by NickIliev** [comment]
@erkanarslan you can install Android Studio for Linux official download links [here](https://developer.android.com/studio/index.html#downloads) and use the AVD to create your emulator using the GUI. just as described in [the documentation article](http://docs.nativescript.org/tooling/android-virtual-devices)

Another option is to download the needed system images (emulators) and start them through command line - more info on that [here](https://developer.android.com/studio/run/emulator-commandline.html)

**Comment by erkanarslan** [comment]
Then, documentation should be updated. Because developers who follow the documentation first install sdk only tools, then android studio. Developers should directly install Android Studio.
