### ISSUE TITLE
ListView w/"itemTemplates" (multiple templates) cannot be used with TabView

### ISSUE THREAD

**Issue by jgraffite** [NativeScript/NativeScript#4678]
In Nativescript 3.0, I cannot use two or more ListView with itemTemplates together in the same page. They are not displayed and when I try to access one through by id with Javascript, I get a undefined element even it exists on xml page

**Comment by NickIliev** [comment]
@jgraffite using [this sample application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4678) I was able to successfully create and use two list views with `ItemTemplates`

Check the4 events responsible for the items binding and if the event where you are trying to get the ID is included in your XML file.

**Comment by jgraffite** [comment]
Ok. I will test it. But try to test it inside a tabview

**Comment by NickIliev** [comment]
@jgraffite I can confirm that indeed when ListView with multiple templates is nested within TabView it is not rendered (nor the TabView). Loggin this as a bug.

Steps to reproduce - nest a ListView with multiple ItemTemplates within TabView 
or use [this test project](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4678).

Reproducible with `tns-core-modules 3.1.0` on iOs and Android.

**Comment by hshristov** [comment]
This is fixed with 3.2
