### ISSUE TITLE
wrong js path after generate binding using webpack

### ISSUE THREAD

**Issue by tjzfg** [NativeScript/NativeScript#4683]
I write a JAVA extended class in my js file as below
```
import {globalConfig} from "df-tns-ng-instruments/global";

declare let android;
export declare let com:any;
let WXAPI;
let WXAPPID:string="wx9b42099451b15345";
@JavaProxy("org.nativescript.ydzp.wxapi.WXPayEntryActivity")
@Interfaces([com.tencent.mm.opensdk.openapi.IWXAPIEventHandler])
export class TenpayAndroid extends android.app.Activity{
    public onCreate(savedInstanceState) {
        super.onCreate(savedInstanceState);
        WXAPI = com.tencent.mm.opensdk.openapi.WXAPIFactory.createWXAPI(this, WXAPPID);
        WXAPI.handleIntent(this.getIntent(), this);
    }

    protected  onNewIntent(intent) {
        super.onNewIntent(intent);
        this.setIntent(intent);
        WXAPI.handleIntent(intent, this);
    }

    public onReq(req){

    }

    public onResp(resp) {
      globalConfig.message.next(resp.errCode==0?"success":"fail");
      //console.log(resp.errCode);
      this.finish();
    }
}
```
after webpack,I got a Java class in 'platform/android/src/main/package' as below
```
package org.nativescript.ydzp.wxapi;

@com.tns.JavaScriptImplementation(javaScriptFile = "./tenpay/tenpay.js")
public class WXPayEntryActivity extends android.app.Activity implements com.tns.NativeScriptHashCodeProvider, com.tencent.mm.opensdk.openapi.IWXAPIEventHandler {
	public WXPayEntryActivity(){
		super();
		com.tns.Runtime.initInstance(this);
	}

	protected void onCreate(android.os.Bundle param_0)  {
		java.lang.Object[] args = new java.lang.Object[1];
		args[0] = param_0;
		com.tns.Runtime.callJSMethod(this, "onCreate", void.class, args);
	}

	public void onCreate(android.os.Bundle param_0, android.os.PersistableBundle param_1)  {
		java.lang.Object[] args = new java.lang.Object[2];
		args[0] = param_0;
		args[1] = param_1;
		com.tns.Runtime.callJSMethod(this, "onCreate", void.class, args);
	}

	protected void onNewIntent(android.content.Intent param_0)  {
		java.lang.Object[] args = new java.lang.Object[1];
		args[0] = param_0;
		com.tns.Runtime.callJSMethod(this, "onNewIntent", void.class, args);
	}

	public void onReq(com.tencent.mm.opensdk.modelbase.BaseReq param_0)  {
		java.lang.Object[] args = new java.lang.Object[1];
		args[0] = param_0;
		com.tns.Runtime.callJSMethod(this, "onReq", void.class, args);
	}

	public void onResp(com.tencent.mm.opensdk.modelbase.BaseResp param_0)  {
		java.lang.Object[] args = new java.lang.Object[1];
		args[0] = param_0;
		com.tns.Runtime.callJSMethod(this, "onResp", void.class, args);
	}

	public boolean equals__super(java.lang.Object other) {
		return super.equals(other);
	}

	public int hashCode__super() {
		return super.hashCode();
	}

}
```
I wonder whether the js path should be "bundle.js",because when my app invoke this java class,it reported a issue of 'can not find tenpay.js relate to app'.Thanks for any help,best regards!

**Comment by tsonevn** [comment]
Hi @tjzfg 

Thank you for contacting us.
We reviewed your case, however, it would help if you could provide some detailed explanation and steps, which will allow us to reproduce this scenario. It would help also if you could provide a sample project, which could be debugged locally.  

Bear in mind that the classes with custom names have not been removed in the intermediate rebuilds of the app. If you need to make the clean build you could try to remove the `platforms` folder and to verify, whether you will have the same problem.

**Comment by tjzfg** [comment]
Thanks for response.
I put the JAVA dependency which includes the implemented interface:"com.tencent.mm.opensdk.openapi.IWXAPIEventHandler" in my nativescript plugin project.In my tns+ng2 app project,I add the ts file named "tenpay/tenpay.android.ts" .As the above,that is the result.
I have another ts file in the same plugin which had js file path as "bundle.js" after webpack,the difference between these two may help:
1. another ts file is located to the plugin project where  its gradle dependency is located,but this one is seperated.
2. another ts file is annotated only by "@JavaProxy" and is not implements interfaces.
3. another ts file is invoked in app project's other ts file.Differently,this one is extends a android Activity invoked by intent,so there is not invoke by other ts files.
These code is designed to invoke a Chinese special pay way named Wechat.For now,I have change the webpack.config.js to package a additional tenpay.js.It works ,but has some abnormal states.
I will try to make a sample project to reproduce this scenario,it maybe resolve this issue.
Thanks again,best regards

**Comment by tjzfg** [comment]
@tsonevn Hi,tsonevn,I am sure that the problem still exists after I removed the whole android platform directory and webpack again.
Another to be mentioned,when webpack myapp,the 3rd line of tenpay.android.ts
```
export declare let com:any;
```  
will report a issue,so I add 'export' before this line.On the contrary,when I run 'tns run android',I must remove 'export' in the same position to avoid a new issue.does this matter?
Thanks for any advice ,best regards!

**Comment by tjzfg** [comment]
the problem when webpack app without 'export' in 3rd line of tenpay.android.ts 
```
ERROR in Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'com'. Consider exporting the symbol (position 5:13 in the original .ts file), resolving symbol TenpayAndroid in /home/defangit/code/ydzp/app/tenpay/tenpay.android.ts
```

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-dev-webpack#277
