### ISSUE TITLE
How to get elements by className in nativescript?

### ISSUE THREAD

**Issue by vijaykumarbollavaram** [NativeScript/NativeScript#4688]
Hi I am new to nativescript. I want to get elements by className same as Id.`getViewById("name");`. Is this possible with className whicj also support in ios also.

**Comment by tsonevn** [comment]
Hi @vijaykumarbollavaram,
At this time the only available way to get the element, while using some of its attributes is by `id`.  the is the official way which is integrated into tns-core-modules
I do not know what is the exact case, however, you could review the [nativescript-dom](https://github.com/nathanaela/nativescript-dom) plugin which seems to provide the needed functionality.
