### ISSUE TITLE
ActionItem with *ngIf throws an error when it's removed

### ISSUE THREAD

**Issue by madakk** [NativeScript/NativeScript#4691]
Looks like this is happening because ActionItems.removeItems calls _removeView directly: https://github.com/NativeScript/NativeScript/blob/12020bd8bbdb8d87f9100d713590d0db982b7661/tns-core-modules/ui/action-bar/action-bar-common.ts#L190

But the nativescript angular handler has already removed the view (due to the same *ngIf directive) causing the error.

I believe this can be fixed by simply checking that the item's parent is actually the actionBar before attempting to remove it.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#942
