### ISSUE TITLE
 create a plugin for ios by using static libraries error 

### ISSUE THREAD

**Issue by priyangamani** [NativeScript/NativeScript#4696]
I created a plugin by using static libraries such as .a and .h files.
I  implemented the plugin in js like this..
var payment = require("nativescript-payment");
Error while trying to run the project in nativescript...
file:///app/main-page.js:2:22: JS ERROR Error: Could not find module 'nativescript-payment'. Computed path '/Users/macadmin/Library/Developer/CoreSimulator/Devices/D960679B-D897-4EFE-92EB-FF24CEAE4EC8/data/Containers/Bundle/Application/E7E61E37-41B7-44D1-8CBF-8F3C75E2780D/HelloWorld.app/app/tns_modules/nativescript-payment'.
Aug 15 11:36:56 Intellects-MBP com.apple.CoreSimulator.SimDevice.D960679B-D897-4EFE-92EB-FF24CEAE4EC8.launchd_sim[3935] (UIKitApplication:org.nativescript.HelloWorld[0x6ed2][4029]): Service exited due to signal: Segmentation fault: 11

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/ios-runtime#786
