### ISSUE TITLE
System UI has stopped message when I call camera.getPermissions on button tap

### ISSUE THREAD

**Issue by mutazmq** [NativeScript/NativeScript#4697]
I'm developing an Android app and this is the tap listener for my button.

```
(tap)=getPermissions(args) {
camera.requestPermissions();
}
```
Every time I click on the button, I get an error message "System UI has stopped" on Android emulator!

- CLI: 3.1.3
- Cross-platform modules: 3.1.1
- Runtime: Android
- package.json:

```
"nativescript": {
    "id": "org.nativescript.sampleApp",
    "tns-android": {
      "version": "3.1.1"
    },
    "tns-ios": {
      "version": "3.1.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/router": "~4.1.0",
    "font-awesome": "^4.7.0",
    "nativescript-angular": "~3.1.0",
    "nativescript-camera": "^3.0.1",
    "nativescript-couchbase": "^1.0.18",
    "nativescript-ngx-fonticon": "^2.2.3",
    "nativescript-telerik-ui": "^3.0.4",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^5.4.2",
    "tns-core-modules": "^3.1.1",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.25.0",
    "babel-types": "6.25.0",
    "babylon": "6.17.4",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.5.0",
    "typescript": "~2.2.1"
  }
```

![image](https://user-images.githubusercontent.com/34026/29304038-f0622b84-81a1-11e7-85a5-1bef2b934b6e.png)

**Comment by NickIliev** [comment]
@mutazmq I have created[ this demonstration application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4697) and on my side it works as expected when we require camera permissions.

Here is the actual code used:

component file
```
import { Component } from "@angular/core";
import { requestPermissions } from "nativescript-camera";

@Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
})
export class ItemsComponent {

    getPermissions() {
        requestPermissions();
    }
}
```
and in the HTML file
```
<Button text="Get Camera Permissions" (tap)="getPermissions()"></Button>
```

**Comment by mutazmq** [comment]
Thanks @NickIliev, I just used your code as is and got the same error! Can you please help me troubleshoot what is going wrong? Any logs or anywhere I can find a traceback?

**Comment by NickIliev** [comment]
@mutazmq please let me know on what device/emulator you are experiencing this error? (API level)

**Comment by mutazmq** [comment]
@NickIliev it is Android Emulator API 26. Thanks

**Comment by NickIliev** [comment]
@mutazmq I've just finished testing on API-26 emulator but still the error is not reproducible on my side. Try to remove the app from the emulator, wipe all data and then redeploy the application again.

![screen shot 2017-08-15 at 3 27 45 pm](https://user-images.githubusercontent.com/18008302/29315946-8c64cbdc-81ce-11e7-829c-a1e2d552883c.png)

**Comment by mutazmq** [comment]
@NickIliev I removed the app and cleaned all data. Still the same issue :(
I also created a new app with these steps exactly:
```
tns create HelloWorld --template nativescript-template-ng-tutorial
cd HelloWorld/
tns plugin install nativescript-camera
tns run android
```

And the `app.component.ts` code is

```
import { Component } from "@angular/core";
import * as camera from "nativescript-camera"; 

@Component({
  selector: "my-app",
  template: `
  <ActionBar title="My App" class="action-bar"></ActionBar>
  <Button text="Get Camera Permissions" (tap)="getPermissions()"></Button>
  `
})
export class AppComponent {
  // Your TypeScript logic goes here
  getPermissions() {
    camera.requestPermissions();
}
}

```
And still same issue with the fresh app!
How can I debug this problem? Any log I can send to you?

<img src="https://user-images.githubusercontent.com/34026/29317931-339bdd86-81df-11e7-9881-065a90e7c55f.png" width="300">

**Comment by NickIliev** [comment]
The error "System UI has stopped" might indicate that the issue is related to the AVD itself and not to NativeScript. Perhaps you can try some of the solutions provided [here](https://stackoverflow.com/a/16402304/4936697)

**Comment by mutazmq** [comment]
Thanks for sharing it. I found this post earlier, but my `hw.mainKeys` is already set to `yes`.
Strange I'm getting this error only when I request the camera permissions. I will try to remove the AVD and reinstall it again.

**Comment by mutazmq** [comment]
@NickIliev I used a different AVD and it works fine. Seems that AVD specifically has an issue. Thank you

**Comment by eddi333** [comment]
I found an app which solves this problem. You can download it from the play store. Here is the link: https://play.google.com/store/apps/details?id=com.millionairesapp.system.ui

Best Regards,
Eddi
