### ISSUE TITLE
Nativescript - Keep keyboard open when TextField returned on Android

### ISSUE THREAD

**Issue by TareqAteik** [NativeScript/NativeScript#4698]
How can I keep the keyboard open after the user taps on the "Return" key on the soft keyboard? I'm calling the focus method on "returnPress" event, which works fine on IOS but not on android:

```
text() {
    let textFieldElement = <TextField>this.textField.nativeElement;
    textFieldElement.focus();
}
```

Note: this is also posted on [StackOverflow](https://stackoverflow.com/questions/45677875/nativescript-keep-keyboard-open-when-textfield-returned-on-android)

**Comment by NickIliev** [comment]
@TareqAteik try to wrap the focus method in small timeout - most of the times the keyboard focus would be invoked only after the whole UI is loaded.

e.g.
```
text() {
    let textFieldElement = <TextField>this.textField.nativeElement;
    setTimeout(function() {
        textFieldElement.focus();
    }, 300);
}
```

**Comment by TareqAteik** [comment]
Thanks, but this wont work, it will hide the keyboard and shows it back again

**Comment by TareqAteik** [comment]
Okay, turns out I have to override "onEditorAction" method in the "EditorActionListener"...
