### ISSUE TITLE
slider ui component 

### ISSUE THREAD

**Issue by rehamalisalehhosni** [NativeScript/NativeScript#4699]
slider ui component not dragged inside scrollview
```
  <ScrollView>
    <StackLayout class="searchContent" >
      
        <Slider row="1" col="1" value="{{startingPrice.value}}"  minValue="0" maxValue="8000000" class="slider" ></Slider>
        
</StackLayout>
</ScrollView>

```

**Comment by NickIliev** [comment]
@rehamalisalehhosni using your code snippet I've created [this demo app ](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4699_tsc)and both sliders are working as expected inside the scroll view. You an use the project to test at your side and let us know if you can reproduce the issue by changing any related code inside.

If you are still experiencing troubles with your sliders please clarify on what platform you are testing and on what API level(Android). Also providing a project that fully reproduces the issue would be of great help.

**Comment by rehamalisalehhosni** [comment]
issue still exsist 
this code inside RadSideDrawer   like this `
<Page
  loaded="loaded"
  xmlns="http://www.nativescript.org/tns.xsd"
  xmlns:lv="nativescript-telerik-ui/listview"
  xmlns:sidemenu="components/sidemenu"
  xmlns:searchproject="components/searchproject"
  navigatedTo="pageMainNavigated"
  xmlns:dd="nativescript-drop-down"
  xmlns:drawer="nativescript-telerik-ui/sidedrawer"
  xmlns:IC="nativescript-web-image-cache"
  >
  <ActionBar  >
    <GridLayout columns="auto,*,auto" rows="*"
      horizontalAlignment="left" verticalAlignment="center" >
      <StackLayout orientation="horizontal"  horizontalAlignment="left"  col="0" row="0"   Tap="onLeftLocationTap"  class="nav">
        <Image src="~/images/back.png"  height="22" verticalAlignment="center" />
        <Label text="&#xf0c9;"   class="fa baricon" verticalAlignment="center" ></Label>
      </StackLayout>
      <dd:DropDown items="{{ locationSearchBar }}"  col="1" row="0" class="fa actionselect" hint="Area Of Interest &#xf124;" selectedIndex="{{ selectedIndex }}"
        opened="dropDownOpened"  selectedIndexChanged="dropDownSelectedIndexChangedSearch"  verticalAlignment="center" >
      </dd:DropDown>
      <Image src="~/images/search-ico.png"  height="25" width="25" col="2" row="0" Tap="onRightLocationTap" class="bariconsearch" verticalAlignment="center"/>
    </GridLayout>
  </ActionBar>
  <drawer:RadSideDrawer id="ffSideDrawer" drawerTransition="PushTransition" >
    <drawer:RadSideDrawer.mainContent>
      <GridLayout>
        <lv:RadListView
          id="listview"
          swipeActions="true"
          row="1"
          items="{{ listProject }}"
          selectionBehavior="None"
          itemTap="onItemClick"
          itemSwipeProgressEnded="onSwipeCellFinished"
          itemSwipeProgressStarted="onSwipeCellStarted"
          itemSwipeProgressChanged="onSwipeCellProgressChanged"
          >
          <lv:RadListView.listViewLayout>
            <lv:ListViewLinearLayout scrollDirection="Vertical"   />
          </lv:RadListView.listViewLayout>
          <lv:RadListView.itemTemplate>
            <GridLayout  rows="*"  columns="*"  class="listProject  ">
            <IC:WebImage  placeholder="~/images/loader.gif"  col="0" row="0" class="{{borderlocation.value}}" backgroundColor="#fff" verticalAlignment="center"  width="100%" height="100%" stretch="aspectFill"  src="{{ 'https://newhomes.com.eg/New2017/public_html/en-us/Newhomes/Upload_Newhomes_Entity_Db_Project_ImgBig_'+ imgBig }}"></IC:WebImage>
            
              <GridLayout rows="auto,auto,auto" columns="*,*" class="im dista" verticalAlignment="bottom" >
                <StackLayout col="0"  row="0" colSpan="2">
                  <IC:WebImage     horizontalAlignment="left"  stretch="aspectFit"  height="50"  width="50" src=" {{ 'https://newhomes.com.eg/New2017/public_html/en-us/Newhomes/Upload_Newhomes_Entity_Db_Project_ImgLogo_'+ imgLogo }}" class="logoview" row="1" col="0"  />
                </StackLayout>
                <Label text="{{ name }}" class="tit " col="0" row="1"/>
                <Label text="{{'District :' + locationName }}" class="tit" col="0" row="2" />
                <Label text="Starting Price :"  class="rightpos linehight" col="1" row="1" />
                <Label text="{{ startingPrice  + ' '+ startingPriceType }}" class="rightpos" col="1" row="2" />
              </GridLayout>
            </GridLayout>
          </lv:RadListView.itemTemplate>
          <lv:RadListView.itemSwipeTemplate >

            <GridLayout columns="5*,*, auto"  backgroundColor="White" >
              <GridLayout columns="*,10,*" id="mark-view" col="0" style="background-color: #E5E5E5;" padding="5">
                <StackLayout col="2" verticalAlignment="center">
                  <Label text="Down Payment" class="smallfont"/>
                  <Label text="{{downPayment}}" class="bigfont"/>
                  <Label text="installments Years" class="smallfont" />
                  <Label text="{{installmentsYears}}" class="bigfont" />
                  <Label text="Delivery Date"  class="smallfont"/>
                  <Label text="{{deliveryDate}}" class="bigfont" />
                </StackLayout>
                <StackLayout col="1"></StackLayout>
                <StackLayout col="0" verticalAlignment="center" >
                  <Repeater items="{{ units }}">
                    <Repeater.itemTemplate>
                      <Label text="{{ $value }}" class="unit"/>
                    </Repeater.itemTemplate>
                  </Repeater>
                </StackLayout>
              </GridLayout>
              <GridLayout   rows="*" id="delete-view" col="2" Tap="onRightSwipeClick" style="background-color: #F9AD33;text-align:center"  orientation="horizontal" padding="25">
                <Image src="{{fav.value}}" stretch="aspectFit" width="30"  verticalAlignment="center" srtyle="vertical-align: stretch" horizontalAlignment="center"  />
              </GridLayout>
            </GridLayout>
          </lv:RadListView.itemSwipeTemplate>
        </lv:RadListView>
        <AbsoluteLayout background-color="red">
          <StackLayout  orientation="horizontal" verticalAlign="bottom" class="position" >
            <Label text="Map" Tap="goToMap" verticalAlign="bottom"/>
            <Image src="~/images/64@2x.png"  Tap="getNearestLocations" verticalAlign="bottom"/>
          </StackLayout>
        </AbsoluteLayout>
      </GridLayout>
    </drawer:RadSideDrawer.mainContent>
    <drawer:RadSideDrawer.drawerContent>
   <ScrollView>
        <StackLayout class="searchContent" backgroundColor="gray" height="1500">
            <Label text="Search Filteration" class="search_title" />
            <TextField text="{{searchKey" hint="Search Keyword" class="keyword" color="#fff" />
            <Label text="Projects Starting Price" class="search_title" />

            <Slider minValue="0" maxValue="800" value="100" class="slider"></Slider>

            <GridLayout rows="auto" columns="*, *" class="textslider">
                <Label row="0" col="0" text="startingPrice.value" class="label1">
                </Label>
                <Label row="0" col="1" text="maxPrice.value" class="label2">
                </Label>
            </GridLayout>

            <label class="hr" />
            <Label text="Area From (Sqm)" class="search_title" />

            <Slider minValue="0" maxValue="1000" value="50" valueChange="onSecondSliderChange($event)" class="slider" ></Slider>

            <GridLayout rows="auto" columns="*, *" class="textslider">
                <Label row="0" col="0" text="areafrom.value" class="label1">
                </Label>
                <Label row="0" col="1" text="areato.value" class="label2">
                </Label>
            </GridLayout>

            <label class="hr" />
            <Label text="Project Include" class="search_title" />
            <Label text="Project Facilities" class="search_title" />
            <label class="hr" />
            <label height="100" />
        </StackLayout>
    </ScrollView>
    </drawer:RadSideDrawer.drawerContent>
  </drawer:RadSideDrawer>
</Page>

**Comment by NickIliev** [comment]
@rehamalisalehhosni  I have revised [my demo application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4699_tsc) to use RadSideradwer and ScrollView in which the sliders are nested and everything works as expected on both iOS and Android.

**Comment by rehamalisalehhosni** [comment]
https://github.com/rehamalisalehhosni/sliderComponent
this is issue
