### ISSUE TITLE
Add QR and Barcode scanner in real time, no after photo

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#47]
_From @DevManny on April 20, 2015 6:17_

I'd like to add the option to read "QR Code" and "barcode" in real time, not process photo after its capture.

_Copied from original issue: NativeScript/cross-platform-modules#291_

**Comment by PanayotCankov** [comment]
[Zebra crossing](https://github.com/zxing/zxing):
 - [iOS CocoaPod](https://cocoapods.org/pods/ZXingObjC)
 - [Android - it is originally written in Java so there are some jars](http://repo1.maven.org/maven2/com/google/zxing/)

It should be somewhat easy to create a plugin with cross platform JavaScript API based on these dependencies.

**Comment by fealebenpae** [comment]
You don't need XZing on iOS, you can use [`AVCaptureMetadataOutput`](https://developer.apple.com/library/prerelease/ios/documentation/AVFoundation/Reference/AVCaptureMetadataOutput/index.html#//apple_ref/occ/cl/AVCaptureMetadataOutput).

**Comment by enchev** [comment]
Please use our verified plugin:
http://plugins.telerik.com/nativescript/plugin/barcodescanner
