### ISSUE TITLE
How to open video in youtube app with given url?

### ISSUE THREAD

**Issue by vijaykumarbollavaram** [NativeScript/NativeScript#4702]
Hi. I am new to nativescript.

I have youtube url "KhzGSHNhnbI". I want to open this in youtube app(if youtube app is installed in phone) or in browser(if youtube app not installed in phone). 

Can anyone suggest me how to solve this or suggest any third party plugins.

**Comment by NickIliev** [comment]
@vijaykumarbollavaram 

You can use [nativescript-youtube-parser ](https://www.npmjs.com/package/nativescript-youtube-parser) and get a video link taht can be opened in the native video player

**Comment by vijaykumarbollavaram** [comment]
@NickIliev  I dont want to play video in app. When i tap it must open in youtube app.

**Comment by NickIliev** [comment]
@vijaykumarbollavaram you can use [openUrl](https://docs.nativescript.org/api-reference/modules/_utils_utils_.html#openurl) method to open another application (e.g. [here](https://stackoverflow.com/a/39005809/4936697))

**Comment by vijaykumarbollavaram** [comment]
What is the syntax for opening in youtube application.
`utils.ipenUrl("youtube://..");`
Is it works
