### ISSUE TITLE
nativescript carousel view is throwing an error when refering from XML

### ISSUE THREAD

**Issue by venkatTammareddy** [NativeScript/NativeScript#4704]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

**Comment by venkatTammareddy** [comment]
![screenshot_20170816-153103](https://user-images.githubusercontent.com/10940775/29358945-8625b9da-829a-11e7-825b-c3e72cd41031.png)

**Comment by venkatTammareddy** [comment]
Can anyone help me out to fix the above issue?

**Comment by NickIliev** [comment]
Hey @venkatTammareddy this repository is for logging issues, bugs and feature relate to NativeScript modules (tns-core-modules ) and NativeScript base functionality.

Please log issue related to third-party plugins in the plugin's repository.

Regarding your issue - make sure you have added the name space to your XML file
```
xmlns:controls="nativescript-carousel-view"
```

And follow the instructions in [the plugin's README](https://github.com/alexrainman/nativescript-carousel-view/blob/master/README.md)

Closing as duplicate to [https://github.com/alexrainman/nativescript-carousel-view/issues/19](https://github.com/alexrainman/nativescript-carousel-view/issues/19)

**Comment by venkatTammareddy** [comment]
@NickIliev Sorry for posting this question here. I got it and thanks for the reply.
