### ISSUE TITLE
NativeScript pinchMove gesture event

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/NativeScript#4711]
Is there any `pinchMove` gesture event? It's needed for something like instagram zoom. I couldn't find anything in the docs. 

I tried `args.getFocusX()`, but it gives focused finger's location.

**Comment by NickIliev** [comment]
@vahidvdn you can refer to the API reference for the [PinchGestureEventData](https://docs.nativescript.org/api-reference/interfaces/_ui_gestures_.pinchgestureeventdata.html).

Here is the full list of properties and methods you can access:

TypeScript example
```
export function onPinch(args: PinchGestureEventData) {

    console.log(args.android)
    console.log(args.ios)

    console.log(args.eventName)
    console.log(args.object)
    console.log(args.scale)
    console.log(args.state)
    console.log(args.type)
    console.log(args.view)

    console.log(args.getFocusX())
    console.log(args.getFocusY())
}
```

Demonstration application can be found [here](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/NativeScript/issue_4711/app/main-page.ts#L14-L28)

**Comment by vahidvdn** [comment]
@NickIliev Thanks. But which one is related to pinch moving? I want to implement something like Instagram zoom, that user can be able to pinch to zoom and the drag his fingers to move the image. Any idea?

**Comment by vahidvdn** [comment]
@NickIliev I tested these properties, but none of them answers my question. The nearest one is `getFocusX()` and `getFocusY()` methods, but they are related to focused finger, not pinch moving event.
