### ISSUE TITLE
UI: floating action button

### ISSUE THREAD

**Issue by sagar1911** [NativeScript/NativeScript#4712]
Hi,
While I am using FAB as mentioned here https://github.com/bradmartin/nativescript-floatingactionbutton
I am getting the below error. Can anyone explain me why the error is coming !!

![screenshot_1503035088](https://user-images.githubusercontent.com/30491548/29446371-7ce43ee4-8409-11e7-9512-425d8b9a415d.png)

XML Code

`<Page xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:FAB="nativescript-floatingactionbutton" loaded="pageLoaded">
<StackLayout>
<FAB:fab tap="fabTap"
row="1"
icon="res://logo"
rippleColor="#f1f1f1"
class="fab-button" />
</StackLayout>
</Page>`

CSS Code

.fab-button {
height: 70;
width: 70;
margin: 15;
background-color: #ff4081;
vertical-align: bottom;
}

package.json

{
“description”: “NativeScript Application”,
“license”: "SEE LICENSE IN ",
“readme”: “NativeScript Application”,
“repository”: “”,
“nativescript”: {
“id”: “org.nativescript.src”,
“tns-ios”: {
“version”: “3.1.0”
},
“tns-android”: {
“version”: “3.1.1”
}
},
“dependencies”: {
“nativescript-carousel”: “^3.1.0”,
“nativescript-drop-down”: “^3.1.1”,
“nativescript-floatingactionbutton”: “^3.0.1”,
“nativescript-geolocation”: “^3.0.1”,
“nativescript-materialdropdownlist”: “^1.0.15”,
“nativescript-phone”: “^1.3.1”,
“nativescript-social-share”: “^1.4.0”,
“nativescript-theme-core”: “~1.0.2”,
“tns-core-modules”: “^3.2.0-2017-7-20-1”,
“tns-i18n”: “0.0.9”
},
“devDependencies”: {
“babel-traverse”: “6.4.5”,
“babel-types”: “6.4.5”,
“babylon”: “6.4.5”,
“lazy”: “1.0.11”
}
}

Thanks.

**Comment by NickIliev** [comment]
@sagar1911 the issue might be related to [this](https://github.com/bradmartin/nativescript-floatingactionbutton/issues/57#issuecomment-322013795) - check your CSS styles and remove backgrond-color for the floating button.

Apart from that, I have created this test application (without setting background-color) and it works as expected on my side. Perhaps you can test with on your environment and let us know if you are still receiving this error.

**Comment by sagar1911** [comment]
Thanks a lot sir. It worked

Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com

**Comment by sagar1911** [comment]
problem solved but when I am trying to put the FAB code in another page it
is giving me the same error. What might be the problem ??

Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com

**Comment by sagar1911** [comment]
Okay okay I did one mistake now its working without errors.

Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com
