### ISSUE TITLE
Behaviour of In-line styling of the Items of the List view is inconsistent. 

### ISSUE THREAD

**Issue by karthikvdhanya** [NativeScript/NativeScript#4717]
I am trying to apply style for the child item of a Listview through codebehind( .js) file. Styling is inconsistent with the items. 
Inside the Itemtemplete of Listview , for a Lable , i am trying to style its background in code-behind(,js) file. I am using loaded method of the element Label .For the first 5 to 6 items, color of the Label  is displying as expected. But as i scroll down its not coming as expected.

XML file 

`<ListView items="{{ taskList }}" id="taskList">`
`            <ListView.itemTemplate>`
`                <StackLayout orientation="vertical" style="padding: 5">`
`                 <GridLayout class="topBlock" rows="*,*" columns="2*,*">`
`                    <Label class="companyName" text="{{ name }}" col="0"/>`
`                    <Label text="{{ status }}" col="1" loaded="statusCss" />`
`                </GridLayout>`
`            </StackLayout>`
`        </ListView.itemTemplate> `
` </ListView>`

Codebehind(.js) file

`exports.statusCss= function(args){`
`    var label1 = args.object;`
`    if(label1.text === "Follow Up"){`
`        label1.className = "statusFallowUp"`
`    }else if(label1.text === "Interested"){`
`        label1.className = "statusInterested"`   
`    }else if(label1.text === "Converted"){`
`         label1.className = "statusConverted" `
`    }else {`
`         label1.className = "statusNotConverted"` 
`    }`
`}`

First few items(Right top corner of each item - notice the background color of "interested")
![screenshot_1503128682](https://user-images.githubusercontent.com/31185299/29496274-e68c4dd4-85ec-11e7-9324-4e71a868ed90.png)

As scroll down(Right top corner of each item - notice the background color of "interested")
![screenshot_1503128690](https://user-images.githubusercontent.com/31185299/29496275-f078b17a-85ec-11e7-8069-87e48fc17fb8.png)

CLI : 3.0.1
tns-core-modules version: 3.0.1
Platform : Android
TNS Version : 3.0.1

**Comment by NickIliev** [comment]
The ListView is using recycling of the items for better overall performance (so that we don't have to load all the items initially but only the visible ones + one on the top and one on the bottom). 

> UI Virtualization — Views are created only for the items that are currently visible. Fewer elements in memory => less memory footprint.
> View Recycling — Whenever an item scrolls out of the view port, the view that was rendering it is not destroyed. It is put in a pool of recycled views and reused when a new item scrolls into view.

Great blog post on that matter can be found [here](https://medium.com/@alexander.vakrilov/faster-nativescript-listview-with-multiple-item-templates-8f903a32e48f).

That said, when we need to create list items with different styles we should use [item templates](https://docs.nativescript.org/cookbook/ui/list-view#define-multiple-item-templates-and-an-item-template-selector-in-xml)

**Comment by karthikvdhanya** [comment]
Thanks for the answer  and for the nice links about Listview 👍
