### ISSUE TITLE
Instead of reset CSS - reapply the new properties and reset the old ones

### ISSUE THREAD

**Issue by hshristov** [NativeScript/NativeScript#4721]
Profile and optimize how we set/reset CSS properties. There is an option to skip some properties reset because the new CSS will set them again.

**Comment by NathanaelA** [comment]
@hshristov - I noticed this issue in Angular, it sets/clears a ng-dirty class name, which causes several properties to be cleared and reset.  This is seen clearly on the Android slider, the code clears and sets the background multiple times per second if you are doing anything that triggers a ng-dirty class to be added/removed.
