### ISSUE TITLE
Show image as circle with any resolution.

### ISSUE THREAD

**Issue by vijaykumarbollavaram** [NativeScript/NativeScript#4722]
Hi Iam new to nativescript development. While doing project I met an issue as an images as rectangle resolution. When apply 
`
width:100;
height:100;
border-radius:50%;
`
Is is not showing as a circle but it showing as elipse. Is there any way to achive my goal.

**Comment by tsonevn** [comment]
Hi @vijaykumarbollavaram,
 I reviewed your case and tested the scenario with the borderRadius, however, the radius seems to be applied properly on the image. For your convenience, I am attaching sample project and a ScreenShot from the simulator. 
Make sure that you have set the correct width and height to the image, which corresponds to the image size.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1238729/Archive.zip)
![screen shot 2017-08-21 at 3 08 20 pm](https://user-images.githubusercontent.com/17448734/29518613-b2f1bfd6-8682-11e7-883e-bb00ca840775.png)

**Comment by rdlauer** [comment]
To anyone still having this issue, I found that setting `stretch="none"` on the `<Image>` (instead of `aspectFill` or `aspectStretch`) solved the problem.
