### ISSUE TITLE
Nativescript roadmap

### ISSUE THREAD

**Issue by gtzinos** [NativeScript/NativeScript#4727]
Hello guys,

Your job is great, i see to much libraries to use for whatever i need but i think its better to focus to help developers to fix critical issues on your cross platform components. In my case, i have an app and i am following one of your tutorial for aot (https://github.com/sis0k0/lazyNinjas). I created the app and i successfully run it on android devices. After a week i decided to run it on ios and now i realized that 70% of my job can't run there (e.g aot, lazy loading, issues with some layouts). Why to use angular template without the aot, lazy loading and guards ?

**Comment by sean-perkins** [comment]
We have AOT and Lazy Loading working on iOS with our seed: https://github.com/TeamMaestro/angular-native-seed. 

A lot of the libraries you see, are created by the community. Although NativeScript does have several libraries, focusing on performance on the framework should be a crucial focus. 

And without code or an example project, there is very little anyone can do to help you on your issue. 

I would suggest following the issue template: https://github.com/NativeScript/NativeScript/blob/master/.github/ISSUE_TEMPLATE.md to receive better help on your problem. 

Common problems with webpack/AOT not working, is how you request assets and build out your components.

**Comment by NickIliev** [comment]
With the latest NativeScript, we can use Angular applications with lazy loading, guards, AOT, uglify, snapshots and Webpack.
