### ISSUE TITLE
Overlap one layout with other

### ISSUE THREAD

**Issue by vijaykumarbollavaram** [NativeScript/NativeScript#4732]
Hi. Iam developing one application. I have menu layout and decription layout. I need menu layout should present on description layout.

![capture](https://user-images.githubusercontent.com/25168085/29561438-3ec8531e-86ea-11e7-87e1-689f6153d578.PNG)

Is this possible in nativescript.

**Comment by 3rror404** [comment]
If you wrap your layouts in a `GridLayout` and give them the same `row` number they will be positioned one on top of the other.

```
<GridLayout rows="*">
    <StackLayout row="0">
        <!-- Your BACKGROUND layout -->
    </StackLayout>
    <StackLayout row="0">
        <!-- Your FOREROUND layout -->
    </StackLayout>
</GridLayout>
```

**Comment by vijaykumarbollavaram** [comment]
@3rror404  Thanks. It is working

**Comment by vijaykumarbollavaram** [comment]
@3rror404 But When I use Layout with `rows="*"` second layout overlaping first layout.

```
<GridLayout rows="*">
    <StackLayout row="0">
        <!-- Your BACKGROUND layout -->
    </StackLayout>
    <StackLayout row="0" class="second>
        <!-- Your FOREROUND layout -->
    </StackLayout>
</GridLayout>
```
**second** layout overlaiping **first** layout. So my first layout scrollable content not scrolling.

**Comment by tsonevn** [comment]
Hi @vijaykumarbollavaram,
The scrollable layout should be added in the latest position. For example:
```
<GridLayout rows="*">
    <StackLayout row="0">
        <!-- Your BACKGROUND layout -->
    </StackLayout>
    <StackLayout row="0" class="second>
        <!-- Scrollable layout -->
    </StackLayout>
</GridLayout>
```
Otherwise, the scroll will be blocked from the other layouts. 
However, It would help if you could provide some detailed information about the case and what is the expected final result.

**Comment by vijaykumarbollavaram** [comment]
Hi @tsonevn . I already mention in theimage attached. I have hambergur menu bar and content wrapper.
When I use layout mentioned, hamberger menu wrapper occupying total height of screen, so i unable to scroll content.

**Comment by tsonevn** [comment]
Hi @vijaykumarbollavaram,
Did you try my last suggestion, to put the scrollable content in the latest position in the parents GridLayout.
Also, it would help if you provide sample project, which could be debugged locally. This will help to provide a correct solution.
