### ISSUE TITLE
Image upload in nativescript-core

### ISSUE THREAD

**Issue by sagar1911** [NativeScript/NativeScript#4734]
Hi All,
How can I navigate a user to his gallery when he clicks on something(to upload photos).??

**Comment by tsonevn** [comment]
Hi @sagar1911 ,
You could use [nativescript-imagepicker](https://github.com/NativeScript/nativescript-imagepicker), plugin to open the photo gallery and to allow the user to chose the needed picture.
You could also review the sample app [here](https://github.com/NativeScript/sample-ImageUpload).

For further question please use [NativeScript forum](https://discourse.nativescript.org/).

**Comment by sagar1911** [comment]
thanks @tsonevn ,

**Comment by sagar1911** [comment]
Hi Sir,
Please consider this as urjent. I am loading my items into view using a
repeater.
I would like to apply click event on them.If i click on an item I want to
apply styles to only that item.
My question is how to differentiate between clicked, non-clicked items.
Please reply

Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com
