### ISSUE TITLE
Problem in BrainTree Drop In SDK for Android

### ISSUE THREAD

**Issue by jibon57** [NativeScript/NativeScript#4736]
Hello,

I was trying with BrainTree Drop In SDK for android like this:

```
let activity = app.android.foregroundActivity;
let dropInRequest = new com.braintreepayments.api.dropin.DropInRequest();
dropInRequest.clientToken(token) // I got the token from server
app.android.foregroundActivity.startActivityForResult(dropInRequest.getIntent(activity), '4949');
```
But I am getting following error:
```
JS: ERROR TypeError: dropInRequest.clientToken is not a function
JS: ERROR CONTEXT [object Object]
```
But I am following: 

https://github.com/braintree/braintree-android-drop-in/blob/master/Demo/src/main/java/com/braintreepayments/demo/MainActivity.java#L118

That functions are exist in documentation:

http://static.javadoc.io/com.braintreepayments.api/drop-in/3.0.8/com/braintreepayments/api/dropin/DropInRequest.html#clientToken-java.lang.String-
http://static.javadoc.io/com.braintreepayments.api/drop-in/3.0.8/com/braintreepayments/api/dropin/DropInRequest.html#getIntent-android.content.Context-

When I tried to get the methods like:

```
let dropInRequest = new com.braintreepayments.api.dropin.DropInRequest();
console.dir(dropInRequest);
```
```
Output:
JS: === dump(): dumping members ===
JS: {}
JS: === dump(): dumping function and properties names ===
JS: <init>()
JS: amount()
JS: androidPayAllowedCountriesForShipping()
JS: clone()
JS: equals()
JS: finalize()
JS: getClass()
JS: hashCode()
JS: notify()
JS: notifyAll()
JS: toString()
JS: wait()
JS: === dump(): finished ===
JS: ERROR TypeError: dropInRequest.clientToken is not a function
JS: ERROR CONTEXT [object Object]
```
I am trying with Angular:
```
tns --version
3.1.3

"tns-android": {
      "version": "3.1.1"
    }
```
In where I am doing wrong? Please give me suggestion. Thanks in advance.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#831
