### ISSUE TITLE
TextField secure="true" and keyboardType="number" input not secure, and keyboard is default

### ISSUE THREAD

**Issue by ibenzyk** [NativeScript/NativeScript#4738]
When set Text field TextField secure="true" and keyboardType="number" input not secure, and keyboard is default
`<TextField  row="0" col="2" hint="CVV" class="input input-border" secure="true"  keyboardType="number" maxLength="3"></TextField>`
![screenshot](https://user-images.githubusercontent.com/9117979/29605268-86a988a0-87ea-11e7-8805-5b8ec72d2775.png)

**Comment by NickIliev** [comment]
@ibenzyk I have created [this test application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4738) based on your snippet and it works as expected on several Android emulators (tested on API24 as yours, API26).

If possible please test with our test application and also let me know if you have sample project or way taht can reproduce the issue (and let us know the device/emulator used for tests)

**Comment by jogboms** [comment]
I noticed this too on one of my pages i am developing i was hoping it was something i did wrong and would go back to fixing it.

**Comment by ibenzyk** [comment]
@NickIliev thanks for fast response. I've installed your example so 
1) keyborad displays as numeric - so probably  the issue in my project setting or something
2) but field still not secure
![issue4738](https://user-images.githubusercontent.com/9117979/29609494-ad5050b2-87f7-11e7-9f23-1817fd5f6eb8.png)

**Comment by NickIliev** [comment]
@ibenzyk I see the issue now - indeed the input is not secured when using keyboard type ( not working on Android - works as expected on iOS).
Once again thank you for clarifying the issue for me and excuse me for any inconvenience caused.

I am logging this one as a bug for Android - stay tuned for possible workarounds and also any related fixes will be posted and linked in this issue.

**Comment by EddyVerbruggen** [comment]
Ran into this as well. Looks like before #4467 the secure property setter [did honor the setting of `keyboardType`](https://github.com/NativeScript/NativeScript/pull/4467/files#diff-d9d6832f9cd4926581a4fb9dae6e82f0L22).

**Comment by cgebe** [comment]
I have the same issue. However when i add the `secure` attribute to the textfield, the `keyboardType` changes back to normal in addition to not being secure...

**Comment by sserdyuk** [comment]
Setting secure and numeric keyboard type results in plain unsecure text keyboard shown because TYPE_NUMBER_VARIATION_PASSWORD actually belongs to TYPE_CLASS_NUMBER, so the correct implementation should be:

`/tns-core-modules/ui/text-field/text-field.android.ts`

```
if (this.keyboardType === "number") {
   inputType = android.text.InputType.TYPE_CLASS_NUMBER | android.text.InputType.TYPE_NUMBER_VARIATION_PASSWORD;
} else {
   inputType = android.text.InputType.TYPE_CLASS_TEXT | android.text.InputType.TYPE_TEXT_VARIATION_PASSWORD;
}
```

**Comment by vchimev** [comment]
Thank you for the suggested fix, @sserdyuk! Thank you for the discussion, Guys!
Feel free to open pull requests with such fixes following our [contribution](https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md) guide.

**Comment by deepak4u2006** [comment]
Hi @vchimev is this issue closed in the latest version of Nativescript?

**Comment by vchimev** [comment]
Hi @deepak4u2006,

the fix is available in the `next` version of *tns-core-modules* and is going to take part of version **3.4.0** expected in a few weeks.

**Comment by vforv** [comment]
On IOS is problem not display numbers keyboard it is possible to enter text as well.
