### ISSUE TITLE
Angular http put request with attached file without nativescript-background-http

### ISSUE THREAD

**Issue by shabib3** [NativeScript/NativeScript#4739]
There is a way to attach file (in my case image) in a PUT http request with a simple http request and not using the nativescript-background-http plugin?

I need it to upload image to aws s3.
I can do it very simply with postman put request - just attach image and select the 'binary' option the 'body' tab.

Thanks a lot :)

**Comment by tsonevn** [comment]
For using `Amazon Web Services` in your NativeScript application and to be able to make a request to this service you could use [nativescript-nodeify](https://github.com/EddyVerbruggen/nativescript-nodeify/blob/master/README.md#aws-sdk-or-amazon-cognito-identity-js-which-includes-aws-sdk) plugin, which will allow you using the `aws-sdk` or `amazon-cognito-identity-js`. 

For further instruction, you could review the ReadMe file in this [repository](https://github.com/EddyVerbruggen/nativescript-nodeify/blob/master/README.md#aws-sdk-or-amazon-cognito-identity-js-which-includes-aws-sdk).
