### ISSUE TITLE
Documentation for NativeScript UI Components 

### ISSUE THREAD

**Issue by rumysharma** [NativeScript/NativeScript#4747]
I have just strated building apps in NativeScript. Its very easy to understand all the details provided on the websites. 

I am facing issues while creating a new layout with the NativeScript components and attributes.

I dont know which element to use while creating a layout, I saw many examples and have a understanding of basic layout. For example "page" tag and "StackLayout" tag. But still there is lot of tags in NativeScript.  

http://docs.nativescript.org/ui/components

In the above link I have read all the components. For example if I need to add paragraph what tag I have to use ?

Is there any breif link about the components and attributes for NativeScript?

**Comment by tsonevn** [comment]
Hi @rumysharma,
First of all, thank you for your interest in NativeScript.
Indeed all available components are described in the [http://docs.nativescript.org/ui/components](http://docs.nativescript.org/ui/components) as you have mentioned in your comment.

An example, how to use them could be found in the [cookbook](http://docs.nativescript.org/cookbook/ui/text-field) section of the docs. there you will also found a sample code snippets.
For further info about the available properties for specific element could be used [api-reference](https://docs.nativescript.org/api-reference/) part of docs. In the left side, you will find the components and while selecting them it will be shown the full list of their properties.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/docs#884

**Comment by rumysharma** [comment]
@tsonevn  Thanks for the Quick reply!

Well all the components are well defined in that section. Just a quick query, How can we found all the attributes for a particular tag or component. For example I recently used "Textview" and later I have found its attributes like "hint, text, editable etc. 

Really Appreciate you help!

**Comment by tsonevn** [comment]
Hi @rumysharma,
If we take for example `TextView` component when you open the [api-reference](https://docs.nativescript.org/api-reference) you could select the `"ui/tab-view"` field on the left side. Then in the newly opened window, you will see the link with name `TabView`. When you open [it you will](https://docs.nativescript.org/api-reference/classes/_ui_text_view_.textview.html) see all properties which are available for the component.
