### ISSUE TITLE
[iOS] XML + JS: Switch incorrectly states the status (Checked) in a 'Tap' Event.

### ISSUE THREAD

**Issue by GuneshRaj** [NativeScript/NativeScript#4758]
### Tell us about the problem
The Control 'Switch' does not state the correct status during a Tap event. The behaviour is unpredictable and sometimes provide the inverse result of the Switch state.
The success rate to get the right status is around 60% in my manual test for both cold start and hot reload.

Yes, I understand that Observables or Bindings are the way to go but I find this behaviour quite unpredictable & needs to be addressed.

### Which platform(s) does your issue occur on?
iOS Emulator and IOS Device.

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.1.3
- Cross-platform modules: Core Control

### Please tell us how to recreate the issue in as much detail as possible.
Create a basic Hello World Project without any plugins.
Assuming theres 2 files, index.xml and index.js for code behind.

Add the code below & start the emulator.

`tns run ios --emulator
`
### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Code:

XML:
```
    <Switch dock="right" id="switch1" tap="switchPropertyChange" checked="false"/>
```

JS:
```
    exports.switchPropertyChange = function(args) {
    console.log("switchPropertyChange : " + Date.now());
    var page = args.object.page;
    var switch1 = view.getViewById(page, "switch1");
    console.log("Switch Status : " + switch1.checked);
    }
```

**Comment by tsonevn** [comment]
Hi @GuneshRaj,
Thank you for contacting us.

Regarding your case, to be able to handle the value change of the Switch component, you should use `checkedChange` event instead of using tap. To do that you should use `on` method in the component loaded event, as it is shown in the attached code.
XML
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page">

    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>

    <StackLayout class="p-20">
        <Label text="Switch test" class="h1 text-center"/>
        <Switch loaded="swloaded" checked="false"/>
    </StackLayout>
</Page>
```
TypeScript
```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import {Switch} from "ui/switch"

// Event handler for Page "navigatingTo" event attached in main-page.xml
export function navigatingTo(args: EventData) {

    let page = <Page>args.object;
    page.bindingContext = new HelloWorldModel();
}
export function swloaded(args){
    var switchcomp:Switch = <Switch> args.object;
    switchcomp.on("checkedChange", function(arg){
        console.log("value "+args.object.checked
    );
    })
}
```
