### ISSUE TITLE
Error when running app on Android emulator/device

### ISSUE THREAD

**Issue by dgmaar** [NativeScript/NativeScript#4766]
### Did you verify this is a real problem by searching 
yes
### Tell us about the problem
Error when running my app on Android emulator and device, not always appears
![screenshot_1503967980](https://user-images.githubusercontent.com/24962518/29798450-37a890dc-8c1a-11e7-93d8-63dc1e8418fd.png)

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:

 nativescript     │ 3.1.3           │ 3.1.3        
 tns-core-modules │ 3.1.1           │ 3.1.1 
 tns-android      │ 3.1.1           │ 3.1.1  
 tns-ios          │ 3.1.0           │ 3.1.0

**Comment by tsonevn** [comment]
Hi @dgmaar,
Could you provide some more info about the steps, which are used, while you are building the application?
It would help if you provide an info about the Emulators API level. Also, please, send us the full log from the console, when the error appears.

In the meantime, you could delete `node_modules`, `platforms`, `hooks` folders, clear npm cache with `npm cache clean` and rebuild the app `tns run android`

**Comment by dgmaar** [comment]
I'm attaching some log files
[Log.zip](https://github.com/NativeScript/NativeScript/files/1260929/Log.zip)

I've tested my app on Android device 7.0 Nougat and emulator with Android 6.0, in both I get same error

**Comment by tsonevn** [comment]
Hi @dgmaar,

Thank you for the attached log.
In my further investigation, I found that this error could be related to the fact that in the project app.ts file is called the `MajorVersion` property, which is valid only for iOS platform. Calling this property on Android will lead to an issue with the application build. If this is the case you could check for the platform type while using the `platforms` module as it is shown in the attached code.
```
import {isIOS} from "platform";
if(isIOS){
    // platform specific code here
}
```
If the problem still exists, please send us a sample project, which could be debugged locally.
