### ISSUE TITLE
How to implement menu tooltip in NS-core

### ISSUE THREAD

**Issue by sagar1911** [NativeScript/NativeScript#4769]
Hi,
I would like to implement menu tool tip in nativescript. How can I do that ? Im using list view to load the items. Any suggestions ?? The tooltip should look similar to the image attached below .
![screenshot 1](https://user-images.githubusercontent.com/30491548/29816197-d4d7786c-8cd0-11e7-8617-a9606f5c7c3d.png)

Thank You.

**Comment by tsonevn** [comment]
HI @sagar1911,
You could verify whether [nativescript-tooltip](https://github.com/triniwiz/nativescript-tooltip) is applicable for your scenario.

Please for any further `How to ` questions use NativeScript [forum](https://discourse.nativescript.org/).

**Comment by sagar1911** [comment]
Thanks,
But in nativescript forum I am not getting response quick enough.
thats why I am posting my questions in gitbub.

Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com

**Comment by tsonevn** [comment]
Hi @sagar1911 

The main purpose of this repository is for Bug reporting. Regarding that, you could also use the NativeScript StackOverflow thread [here](https://stackoverflow.com/questions/tagged/nativescript), where you could also post your questions

**Comment by sagar1911** [comment]
Okay sir.

Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com

**Comment by sagar1911** [comment]
Sir,
Is it possible to display superscript(for date formats) in nativescript, I
used <sup></sup> but it is not rendering in the view.
Example: August 25th

Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com
