### ISSUE TITLE
ui slider 

### ISSUE THREAD

**Issue by rehamalisalehhosni** [NativeScript/NativeScript#4773]
slider not dragged inside scrollView  and sidemenu
android 
https://github.com/rehamalisalehhosni/sliderComponent
this is issue

**Comment by tsonevn** [comment]
Hi @rehamalisalehhosni,
Thank you for your sample app.
I reviewed it and found that in the app are used an old version of `tns-core-modules` and `nativescript-telerik-ui`, which could lead to this error.

Bear in mind that the latest official version of the modules is `3.0.1` and `nativescript-telerik-ui` - 3.0.4.
Regarding that, I create a new sample project, where is used Slider inside the SideDrawer menu and the event of the slider is executed properly. For your convenience, I am attaching GIF file and the sample project.
![screencast 2017-08-30 at 11 33 40 am](https://user-images.githubusercontent.com/17448734/29863484-84775312-8d78-11e7-9d15-a4b949196ab2.gif)
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1262893/Archive.zip)

**Comment by rehamalisalehhosni** [comment]
thanks
