### ISSUE TITLE
propertyChange not work in ListPicker on NS 3.0.0 

### ISSUE THREAD

**Issue by Mflm** [NativeScript/NativeScript#4781]
### Tell us about the problem
I updated Nativescript 3.0.0, and found that the "propertyChange" event on ListPicker nor works. I'm using NativeScript with vanilla

Has changed the way to call the events?

thanks
### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
3.0.0
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
│ Component │ Current version │ Latest version │ Information │
│ nativescript │ 3.0.0 │ 3.0.0 │ Up to date │
│ tns-core-modules │ 3.0.0 │ 3.0.0 │ Up to date │
│ tns-android │ 3.0.0 │ 3.0.0 │ Up to date │
│ tns-ios │ 3.0.0 │ 3.0.0 │ Up to date │
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
EXAMPLE:

XML
```
<ListPicker id="pokemonPicker" items="{{ pokemon }}" >
    </ListPicker>
```
JS
```
var Observable = require("data/observable").Observable;
var pageData = new Observable({
pokemon: ["Bulbasaur", "Charmander", "Squirtle"]
});

exports.pageLoaded = function(args) {
var page = args.object;
page.bindingContext = pageData;

page.getViewById("pokemonPicker").addEventListener(
Observable.propertyChangeEvent, function(e) {
  if (e.propertyName == "selectedIndex") {
    console.log("You selected: " + pageData.pokemon[e.value]);
  }
}
);
};
```

**Comment by Mflm** [comment]
I know Nativescript update the way to call events,  with a Textfield this works:

<TextField id="email" />

page.getViewById("email").on("textChange", function(args){
    console.log("text changed");
})

But I need the event of listpicker, in the documentation I can't find it.

**Comment by tsonevn** [comment]
Hi @Mflm, 
To be able to handle `selectedIndex` change, while using `on` method,  the first argument should be `selectedIndexChange` and the callback method will be fired properly. For example:
XML
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page">

    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>

    <GridLayout rows="" columns="">
        <ListPicker loaded="lvloaded" id="pokemonPicker" items="{{ pokemon }}" ></ListPicker>
    </GridLayout>
</Page>

```
TypeScript
```
import { EventData, Observable } from 'data/observable';
import { Page } from 'ui/page';
import { ListPicker } from "ui/list-picker"
import { HelloWorldModel } from './main-view-model';

// Event handler for Page "navigatingTo" event attached in main-page.xml
export function navigatingTo(args: EventData) {

    let page = <Page>args.object;
    var tmpobservable = new Observable();
    tmpobservable.set("pokemon", ["Bulbasaur", "Charmander", "Squirtle"]);

    tmpobservable
    page.bindingContext = tmpobservable;
}

export function lvloaded(args){
    var picker:ListPicker = <ListPicker>args.object;
    picker.on("selectedIndexChange", function (arg){
        console.dir((<any>arg.object).selectedIndex);
    })

}
```
Generally, while attaching for some property change event with using `on` method the first parameter should be a construction from the property name + "Change" word at the end.

**Comment by Mflm** [comment]
Hi @tsonevn and thanks for your response

this works:
`page.getViewById("pokemonPicker").on("selectedIndexChange", function (arg){
    console.log("-- "+arg.object.selectedIndex);
    })`

I can the ability to get the Index of the ListPicker, but before I got the name only with nameFunction.value or `arg.object.value` but this return the index.

The solution is get the index in the array:

` console.log("-- "+items[arg.object.selectedIndex]);`

Or exists a way to get directly the name of the item? 

Thanks

**Comment by Mflm** [comment]
Hi @tsonevn 

yes this works:

`page.getViewById("pokemonPicker").on("selectedIndexChange", function (arg){
    console.log("-- "+arg.object.selectedIndex);
    })`

and if I need to get the name is=

` console.log("-- "+items[arg.object.selectedIndex]);`

Thanks
