### ISSUE TITLE
Examples of setTimeout use-cases in NativeScript

### ISSUE THREAD

**Issue by sean-perkins** [NativeScript/NativeScript#4782]
Per a conversation between the developer experts, @hshristov has asked us to log instances of having to use `setTimeout` inside our NativeScript applications.

These are the following scenarios I have encountered.

1. Pull to refresh (RadListView)
When leveraging the pull-to-refresh feature, our application clears state (RxJS) and reloads data off the server. If the request time is under a second, the UI has no time to cleanly animate the activity indicator for the ListView.

Example code:
```
onPullToRefreshList(args: ListViewEventData): void {
    const listView: RadListView = args.object;
    this.isLoading$
        .subscribe((done) => {
            if (done) {
                setTimeout(() => {
                    listView.notifyPullToRefreshFinished();
                }, 1000);
            }
        });
    this.searchList(this.search);
}
```

2. Complex UI layouts
If your application has a lot of containers and UI to render on the view, it will drastically decrease overall performance of your application. This is most noticeable when trying to navigate between routes in a nativescript-angular application. I am unsure why, but an assumption is the router change has to wait for the UI to finish rendering on the main thread, prior to actually changing the route. To solve this problem, we wrap complex views in a `*ngIf` boolean check, leveraging `setTimeout`. 

Example code:
```
this.renderView = false;
this.renderViewTimeout = setTimeout(() => {
    this.renderView = true;
}, 350);
```

```
<GridLayout>
   <StackLayout *ngIf="renderView">
       <!-- complex layout with iteration over large lists, etc. -->
   </StackLayout>
</GridLayout>
```

3. Changing the source of a `WebView` dynamically. 
When changing the source of the web view, it takes several seconds for the change to occur and the page to re-render. To get around this, we call the `reload()` function in a timeout. 

Example code:
```
@ViewChild('loginWebView') webView: ElementRef;

...

this.setWebViewSrc();
setTimeout(() => {
    this.webView.nativeElement.reload();
}, 500);

...

private setWebViewSrc() {
    this.webView.nativeElement.src = `https://${this.config.ENVIRONMENT.LOGIN}?no-op`;
}
```

4. Debouncing Textfield typing
If you have any UI interactions tied to the `textChange` emission of the `TextField` component, the UI will lock up/by laggy for the user. To get around this, we bind to the `textChange` event and only emit after a specific duration has occurred since the last key press. We also tie the same resolution for the challenge of the second (2) bullet item. 

Example code:
```
@Output() onSearch: EventEmitter<any> = new EventEmitter();
private debounceTime = 1000;
private debounceTimeout: any;
...

onKeyUp(searchPhrase: string): void {
    this.isSearching = Boolean(searchPhrase);
    clearTimeout(this.debounceTimeout);
    this.debounceTimeout = setTimeout(() => {
        this.debounceTimeout = null;
        this.onSearch.emit(searchPhrase);
        this.renderView = false;
        this.renderViewTimeout = setTimeout(() => {
            this.renderView = true;
        }, 1000);
    }, this.debounceTime);
}
```

```
<TextField (textChange)="onKeyUp($event?.value)"></TextField>
```

**Comment by NathanaelA** [comment]
1. If you need access to the nativeView object or any real layout information it may not be created until the rendering has occurred, in this case to get access to the value as soon as possible you have to use a setTimeout.

2. If you are doing long work on the main thread (better use case in some cases might be a background thread, but a background NS thread is pretty heavy in memory usage).   So one way I can do this is:
var x.doWork().then(doAnimation).then(DoMoreWork).then(doAnimations)....
DoWork, DoMoreWork are functions that have some work to do in them.     DoAnimation looks like this:

```
function doAnimation(): Promise<any> {
        return new Promise<any>((resolve) => {
            setTimeout(resolve, 0);
        });
}
```
This works and allows the UI to update in between chunks of work being done, and then continues on doing more work.  ;-)

3. Many many plugins use setTimeout in them to deal with weirdness in when rendering occurs verses when data shows up.  No specific use case; but I can point you to the entire list if you need it.

**Comment by bradmartin** [comment]
https://github.com/telerik/nativescript-ui-feedback/issues/570#issuecomment-373039895 - related to RLV observableArray and specific to iOS.
