### ISSUE TITLE
Integrate bucklescript in nativescript workflow

### ISSUE THREAD

**Issue by kliron** [NativeScript/NativeScript#4786]
Thank you for your wonderful work with NativeScript. I am wondering if anyone has considered adding support for Bucklescript in the build process. Bucklescript  has matured a lot and seems to  build a strong momentum. I believe it would add a lot of value for developers that would like the option to use OCaml/ReasonML and could integrate nicely with Typescript.

I have just started with Nativescript and know too little of its internals. Would using nativescript-hook be the way to add the bucklescript compiler in the workflow?

**Comment by vakrilov** [comment]
Hey @kliron,
NativeScript executes JS at runtime, so you can use any compiler in your workflow as long as it outputs javascript.
If you are willing to start working on Bucklescript plugin for NativeScript - you can check how the [nativescript-dev-typescript](nativescript-dev-typescript) is made - it uses a hook to compile the typescript to javascript.
