### ISSUE TITLE
“npm ls -g --depth=0” show error

### ISSUE THREAD

**Issue by terrilltang** [NativeScript/NativeScript#4791]
version info:
os: macOS 10.12.6
node: v8.4.0
npm: 5.4.0
nativescript :3.1.3
======================
after run commend 'npm ls -g --depth=0' show some error;

`/usr/local/lib
├── @angular/cli@1.3.2
├── asar@0.13.0
├── nativescript@3.1.3
└── npm@5.4.0

npm ERR! error in /usr/local/lib/node_modules/nativescript/node_modules/cli-table: Invalid version: "https://github.com/telerik/cli-table/tarball/v0.3.1.2"
npm ERR! invalid: cli-table /usr/local/lib/node_modules/nativescript/node_modules/cli-table
npm ERR! error in /usr/local/lib/node_modules/nativescript/node_modules/tabtab: Invalid version: "https://github.com/Icenium/node-tabtab/tarball/master"
npm ERR! invalid: tabtab /usr/local/lib/node_modules/nativescript/node_modules/tabtab
npm ERR! error in /usr/local/lib/node_modules/nativescript/node_modules/xcode: Invalid version: "https://github.com/NativeScript/node-xcode/archive/1.4.0.tar.gz"
npm ERR! invalid: xcode /usr/local/lib/node_modules/nativescript/node_modules/xcode
npm ERR! error in /usr/local/lib/node_modules/nativescript/node_modules/xmlhttprequest: Invalid version: "https://github.com/telerik/node-XMLHttpRequest/tarball/master"
npm ERR! invalid: xmlhttprequest /usr/local/lib/node_modules/nativescript/node_modules/xmlhttprequest
npm ERR! error in /usr/local/lib/node_modules/nativescript/node_modules/zipstream: Invalid version: "https://github.com/Icenium/node-zipstream/tarball/master"
npm ERR! invalid: zipstream /usr/local/lib/node_modules/nativescript/node_modules/zipstream
npm ERR! missing: node-uuid@1.4.7, required by ios-device-lib@0.4.8
npm ERR! error in /usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/bplist-parser: Invalid version: "https://github.com/telerik/node-bplist-parser/tarball/master"
npm ERR! invalid: bplist-parser /usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/node_modules/bplist-parser
npm ERR! missing: cli-table@^0.3.1, required by marked-terminal@2.0.0`

**Comment by tsonevn** [comment]
Hi @terrilltang,
I research this error and found that this is something related to npm and the fact that the newer versions will warn you if it finds packages installed under a `node_modules` directory which is not explicitly listed in the package.json file. Regarding that, this is not something related to NativeScript platform and it seems to be the way how npm works.
This behavior is discussed in the thread [here](https://groups.google.com/forum/#!topic/node-red/lTEqGo-0UWU).

Hope this information helps.

**Comment by terrilltang** [comment]
@tsonevn 
thank you!!
I understand this error message now，this issue will be closed.:)
