### ISSUE TITLE
Not loading app.js as default

### ISSUE THREAD

**Issue by sagar1911** [NativeScript/NativeScript#4798]
Hi All,

Even though I am defining the entry page in app.js some other page is loading and not applying the changes. What might be the problem ??
I am not getting any error also.

**Comment by tsonevn** [comment]
Hi @sagar1911,
The given information is not enough to investigate your case, Please provide some more info about your case. It would also help if you give us some sample project or at least code snippets, which are related to the issue.

**Comment by sagar1911** [comment]
Thanks for the reply.
I have shifted the project to another directory and it worked fine.

Rodda SagarUX Engineer
M +91 9502315034
E sagar@divami.com

**Comment by tsonevn** [comment]
Hi @sagar1911 
I am assuming that you were able to fix the problem in your application. In this case, I am closing this issue. In case the problem appears again, please provide a sample project, which could be debugged locally and I will reopen the issue.
