### ISSUE TITLE
Segmentbar for main bottom navigation in android with icon

### ISSUE THREAD

**Issue by rumysharma** [NativeScript/NativeScript#4800]
Hello Team,

I have done lot of R & D to create a main navigation for android app. 

As we already know tab view is rendering on top in Android and bottom in IOS. Now I have to create a bottom navigation for android.

I have found from some examples that for android we can use Segmentbar to create a custom navigation at the bottom.

Can anyone please help me out with a detailed example of Segmentbar to create a Navigation at the bottom. 

or if there is any other way to create the same then please let me know.

**Comment by NickIliev** [comment]
hello @rumysharma and thank you for your interest in NativeScript!

Please notice that the issues in this repository is for loggin bug, issues and feature related cases.
For how-to related questions please post in one of the community channels where you will find large support from the community (e.g. like [discourse.nativescript.org](https://discourse.nativescript.org/))

Meanwhile, you can also check some custom made pplugins taht have already handled this case
- [nativescript-bottombar](https://www.npmjs.com/package/nativescript-bottombar)
- [nativescript-toolbar](https://www.npmjs.com/package/nativescript-toolbar)
