### ISSUE TITLE
How to put popup menu icon in ios

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#4802]
With  below code i get the popup menu icon in android but won't get same icon in ios.
<ActionItem ios.position="right" android.position="popup"></ActionItem>
How to achieve this in both in ios and android?

**Comment by NickIliev** [comment]
hello @dhanalakshmitawwa and thank you for your interest in NativeScript!

Please notice that the issues in this repository are for logging bug, issues, and feature related cases.
For how-to related questions, please post in one of the community channels where you will find large support from the community (e.g., like [discourse.nativescript.org](https://discourse.nativescript.org/))
