### ISSUE TITLE
Change the view when data in array which is inside of object of an array

### ISSUE THREAD

**Issue by saikumar-madana** [NativeScript/NativeScript#4803]
I am changing data in array which is in object of an array. When I change the data in inside array, how to reflect it in view?

I have data something like:

```
//initially declared array like this
var pageData = new observableModule.fromObject({
    data: new ObservableArray([])
});

//this is data declared with observable array above. And Iam changing data in items array
 [
     {
         "id": 93,
         "items": [ 1, 2, 3 ]
      }
]

//refreshing view like this
page.getViewById("OHrepeater").bindingContext = pageData;
```

when I delete an item, data in items array is changing but view is not getting reflected.

Please help me solve this.
Thank you..

**Comment by NickIliev** [comment]
@saikumar-madana your `items` array is not observable and won't trigger property change detection when a new element is pushed.
With the code above only a change in the `data` array will trigger property change detection. Either provide observable `items` array and bind directly to it or directly change the elements of your `data`.

You can use [fromObjectRecursive](http://docs.nativescript.org/api-reference/modules/_data_observable_.html#fromobjectrecursive) method, **but** it will create observable for each nested object **excluding arrays and function**. So once again either flatten the input data and provide observable `items` or directly change the element of your observable array in your case
```
{
     "id": 93,
     "items": [ 1, 2, 3 ]
}
```

Please notice that the repository is for loggin issues,bugs and feature request.
For how-to related questions please post in one of the community channels like [discourse.nativescript.org](https://discourse.nativescript.org/) or SO.
