### ISSUE TITLE
Support padding on TextField and Button elements

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/NativeScript#481]
A common requirement in mobile UIs is the need for a gap between button/textfield text and its border, for example:

![03 signup](https://cloud.githubusercontent.com/assets/544280/8876146/d1e18fb8-31eb-11e5-9d60-9cc2b4f15a70.png)

Before {N} 1.2, border was a UI element, and you could create this spacing using `margin` on the `<TextField>`. Now that border is done in CSS (which is awesome btw), there's no way to create this spacing anymore, so you end up with a UI that looks like this:

![screen shot 2015-07-24 at 10 06 51 am](https://cloud.githubusercontent.com/assets/544280/8876184/22725ade-31ec-11e5-9ff7-d19309ed0071.png)

As a web developer I would expect to have the ability to apply padding to control this spacing. Is this something {N} can support?

Thanks.

**Comment by vakrilov** [comment]
@tjvantoll Until we add support for TextView padding - you can wrap the text view in another layout(e.x. GridLayout) - then set the border on the grid an use its padding (or the text vew's margin).

**Comment by PanayotCankov** [comment]
This makes the TextField smaller and harder to tap to focus it. I think the Padding for TextFields and Buttons is important.

**Comment by hamorphis** [comment]
https://github.com/NativeScript/NativeScript/pull/559
