### ISSUE TITLE
[iOS] Disabled label remains actionable on iOS

### ISSUE THREAD

**Issue by manoldonev** [NativeScript/NativeScript#4811]
### Tell us about the problem
Label element with `isEnabled` property set to `false` remains actionable on iOS i.e. its `tap` handler is executed on tap action. The problem is present in both Angular and VanillaJS flavors. Note that styling is correctly applied for disabled labels e.g. if you have specified `disabled` pseudo class, it gets applied as expected (see code below).
This works correctly on Android (`tap` handler not executed). 

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.2.0
- Cross-platform modules: 3.1.1
- Runtime(s): 3.2.0

### Please tell us how to recreate the issue in as much detail as possible.
See code below

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
``` css
.myclass {
    color: greenyellow;
}
.myclass:disabled {
    color: red;
}
```
``` html
<Label text="Disabled Label" class="myclass" isEnabled="false" (tap)="onTap()"></Label>
```
``` ts
    onTap(): void {
        console.log("TAP");
    }
```

**Comment by sserdyuk** [comment]
@manoldonev IsEnabled only affects the looks http://docs.nativescript.org/api-reference/classes/_ui_label_.label.html#isenabled. You should also set isUserInteractionEnabled to block the interaction http://docs.nativescript.org/api-reference/classes/_ui_label_.label.html#isuserinteractionenabled

**Comment by manoldonev** [comment]
Thanks @sserdyuk, the isUserInteractionEnabled solved my problem!
