### ISSUE TITLE
Replacements and styling for Android/iOS components in NativeScript

### ISSUE THREAD

**Issue by truewt** [NativeScript/NativeScript#4812]
Hello,

I'm new to NativeScript and I already created a basic application which works pretty well. I'm using NativeScript with Angular (+ SASS with NativeScript Theme Light), and I created project with NativeScript Sidekick. So far I got through almost everything I had to implement, but there are few things I can't solve on my own, since I can't figure out where to look for solution. In order to resolve those things I'm writing here because I think it's the most appropriate place to ask questions which may also help others which have just started using NativeScript as I am.

Basically I have four problems which I would like to resolve on the easiest way (I'm beginner, so I may not understand something advanced) ...

- The main problem is with SearchBar which I'm using for searching around 100 items in a list. I can't style it in the way, that it would use colors from my variables file (which comes by default named `_app-variables.scss` in app directory). Along that I would also like to remove padding on left and right. I am attaching image so that you will understand what I mean:
![search_bar_no_design](https://user-images.githubusercontent.com/29984705/30174421-55f27e8e-93fb-11e7-96ba-0acae1d540dd.jpeg)
So the cursor which is blue should probably be in the same color as the ActionBar. Also the padding doesn't get removed even if I style it with `padding: 0;` or I add `p-0`. SearchBar is positioned inside classic StackLayout and that's the code I use for it:

```
<StackLayout>
        <SearchBar row="0"
                   [hint]="'search_text' | translate"
                   (loaded)="onLoaded($event)"
                   (textChange)="onTextChange($event)"
                   (clear)="onClear()"
                   class="items-search">
        </SearchBar>
        ...
</StackLayout>
```

- The second problem is connected with styling a ListView item tap. So basically I added some styling to item, which consists of background, padding, inner background and border-radius (look at the top item on the picture below). With that I have override default styling, so there is no material tap on Android anymore. Instead of that I want to change inner background to some other color, to show user a response on his tap. Is there any selector as `:hover`, `:focus`, ... for HTML, like `:tap`? If there is one, is the usage same as `:hover` or it does differ?
![list_item_tap](https://user-images.githubusercontent.com/29984705/30175126-be9baa3a-93fd-11e7-8f50-7b756a6b1532.jpeg)

- The third problem I have is with showing the options like in Cell Broadcast settings or Settings of Gmail app on Android. I want the same (or at least similar) functionality, so that options are tappable and once one of them is tapped, there is a menu which shows additional options. I already did something similar with ListView and then styled both title and chosen option, so that it looks like it's a real setting. However, I can't find comparable option as the dialog for choosing options. Here is a screenshot of settings which describe a bit better what I actually want to achieve:
![main_menu_list_options](https://user-images.githubusercontent.com/29984705/30175579-4bca135a-93ff-11e7-9087-dd468050f3eb.jpeg)

- The fourth problem is with dialogs. I want to add custom about dialog where I would also include an icon of app, some text and Close button. I tried using ModalDialog, but I don't know how to style it, so that it would look like the material dialog on Android. I suppose I have to create custom plugin which would support that. Am I right? If true, is there any guide or could you please write some steps how to do that (if there will be some example code, I would be very happy)? Othervise, what would be the way to achieve that?
![style_about_dialog](https://user-images.githubusercontent.com/29984705/30176112-8eb7c458-9401-11e7-8789-d62c089b8850.jpeg)

If I was unclear at any point and you have a question, please write it down and I will try to answer as soon as possible. I will be very grateful for any information you will provide.

Thank you very much in advance!

**Comment by NickIliev** [comment]
@truewt this repository is f logging issues, bugs, and feature request. Please post a how-to related question in the community channels like [https://discourse.nativescript.org/](https://discourse.nativescript.org/)  where you will receive fast support from other community members.


Notes:  when overriding the Button default styles the material ripple effect is gone. You can implement your own using either the h9ighlighted CSS pseudo selector or using nativescript-ripple plugin.

Regarding the third question, you could use modal pages to create entirely custom dialogs. You can use [nativescript-checkbox](https://www.npmjs.com/package/nativescript-checkbox) to create radio button

Regarding the fourth question - if you need to create your own plugin I would recommend going through the Plugins section in [docs.nativescript.org](http://docs.nativescript.org). We have recently released several detailed articles covering the creation of NativeScript plugins workflow (e.g. [building a plugin](http://docs.nativescript.org/angular/plugins/building-plugins.html) article).

Once again please use the community channels for all how-to related question so we could keep this repository for solving problems related to the framework.
