### ISSUE TITLE
Last child property in nativescript.

### ISSUE THREAD

**Issue by vijaykumarbollavaram** [NativeScript/NativeScript#4817]
I am creating a hybrid app upsing nativescrip. I have one problem, when I repeat the template using `repeater` and applied borders to that repeater layout. I want to remove border properties to last element. Is this possible with nativescript, as in HTML `last-child: ` property

**Comment by NickIliev** [comment]
@vijaykumarbollavaram  NativeScript supports only a subset of CSS properties and does not support pseudo selector last-child. Full list of supported CSS properties can be found [here](http://docs.nativescript.org/angular/ui/styling.html#supported-css-properties)
