### ISSUE TITLE
ServiceStack

### ISSUE THREAD

**Issue by Ox90** [NativeScript/NativeScript#4823]
Hi, someone can provide me a help to integrate ServiceStack (JsonServiceClient)?

https://servicestack.net/
http://docs.servicestack.net/typescript-add-servicestack-reference#typescript-serviceclient

Thanks

**Comment by NickIliev** [comment]
@Ox90 this repository is for logging issue, bugs and feature requests.

Please post how-0to related questions in the community channels like[https://discourse.nativescript.org/]( https://discourse.nativescript.org/)
