### ISSUE TITLE
IOS - AVCaptureVideoDataOutputSampleBufferDelegate randomly stops calling callback function

### ISSUE THREAD

**Issue by thomaspaniagua** [NativeScript/NativeScript#4824]
So I'm trying to have some OpenCV code running in an iOS Nativescript App. I have a camera wrapper with a callback that runs a UIImage from the phone camera through my opencv algorithm. So I have a Placeholder in my nativescript UI that I assign to a UIImageView and then pass it to the start function in my Obj-C code. My problem is that the delegate that updates the image stops being called after around 30 seconds, which doesn't happen when I use this code outside of Nativescript. What would be causing the delegate to not be called anymore? 

https://pastebin.com/quXE1smV

This is not a memory leak, I checked in the Xcode debugger and this code just plain stops running.
I'm using NS 3.0 and TNS IOS 3.1

Something to note is that if I reinitialize the above class and call the start function again in nativescript after it stops, it starts updating frames again for a longer time every time it restarts.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/ios-runtime#797
