### ISSUE TITLE
actionbar How can the page cover actionbar?

### ISSUE THREAD

**Issue by baguosiji** [NativeScript/NativeScript#4826]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Tell us about the problem
I want to implement a slip style like this, but I don't know how to block actionbar. How can I block actionbar?
![image](https://user-images.githubusercontent.com/27269213/30260924-a88f3de0-96fc-11e7-9273-25d509c0d850.png)

### Which platform(s) does your issue occur on?
android

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

**Comment by NickIliev** [comment]
@baguosiji  Based on the screenshot provided it seems taht you are using side drawer. If you are using RadSideDrawer then you can use [showOverNavigation ](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/SideDrawer/show-over-navi-bar)boolean property for your drawer.

Please, notice that this repository is for logging issues, bugs, and feature requests. For how-to related question, I would recommend using one of the community channels like [discourse.nativescript.org](https://discourse.nativescript.org/)
