### ISSUE TITLE
NativeScript.h file not found

### ISSUE THREAD

**Issue by NikitaKurdin** [NativeScript/NativeScript#4827]
Hello.
I have a problem when trying to build an app "NativeScript.h file not found"
Here is a screenshot https://yadi.sk/i/2TtHaJmX3Megu8

**Comment by NickIliev** [comment]
@NikitaKurdin can you clarify the steps taken to build the application (the used `tns` commands) and also which file are you opening in your XCode - is this the generated IPA file after `tns build ios`

**Comment by Yevart** [comment]
@NickIliev, hello! @NikitaKurdin and I work on this project. I am answering your question.
At project folder I implement `tns platform add ios` and get result `Project successfully created.`. Then I move to ./platform/ios and implement `tns run ios` and get `** BUILD SUCCEEDED **`. Then I see splash screen and after it app terminates. In terminal there is log:

> Project successfully built.
> Installing...
> Successfully installed on device with identifier '641253A3-1CA9-42C8-9BB2-F9A98B19FA39'.
> Successfully transferred all files.
> Refreshing application...
> Successfully synced application org.nativescript.HramApp on device 641253A3-1CA9-42C8-9BB2-F9A98B19FA39.
> objc[1311]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x1228e7cc0) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x1226fe6f0). One of the two will be used. Which one is undefined.
> CONSOLE LOG file:///app/views/calendar/calendar.js:72:24: ReferenceError: Can't find variable: sqlite3_open_v2
> CONSOLE LOG file:///app/views/calendar/calendar.js:90:16: Calendar Page is loaded
> 1   0x10cd5fe3b NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
> 2   0x10d4032be ffi_closure_unix64_inner
> 3   0x10d403c02 ffi_closure_unix64
> 4   0x10e1293c3 -[UIViewController __viewWillAppear:]
> 5   0x10e162b51 -[UINavigationController _startTransition:fromViewController:toViewController:]
> 6   0x10e163a03 -[UINavigationController _startDeferredTransitionIfNeeded:]
> 7   0x10e164b41 -[UINavigationController __viewWillLayoutSubviews]
> 8   0x10e35660c -[UILayoutContainerView layoutSubviews]
> 9   0x10e04355b -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
> 10  0x112d4e904 -[CALayer layoutSublayers]
> 11  0x112d42526 CA::Layer::layout_if_needed(CA::Transaction*)
> 12  0x112d423a0 CA::Layer::layout_and_display_if_needed(CA::Transaction*)
> 13  0x112cd1e92 CA::Context::commit_transaction(CA::Transaction*)
> 14  0x112cfe130 CA::Transaction::commit()
> 15  0x112cfeb37 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
> 16  0x1115b4717 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
> 17  0x1115b4687 __CFRunLoopDoObservers
> 18  0x111599038 CFRunLoopRunSpecific
> 19  0x10df7a08f -[UIApplication _run]
> 20  0x10df80134 UIApplicationMain
> 21  0x10d403a5d ffi_call_unix64
> 22  0x11c6172c0
> file:///app/tns_modules/tns-core-modules/ui/action-bar/action-bar.js:188:72: JS ERROR Error: Error loading icon from res://ic_menu
> Sep 18 12:33:22 macmini com.apple.CoreSimulator.SimDevice.641253A3-1CA9-42C8-9BB2-F9A98B19FA39.launchd_sim[1052] (UIKitApplication:org.nativescript.HramApp[0xfc68][1074][1311]): Service exited due to Segmentation fault: 11
> 

I am going to write one more post concerned XCODE error.

**Comment by Yevart** [comment]
I open ./platforms/ios/HramApp.xcodeproj in XCODE (8.3.3). Then run Product/Run. Now there is no error from the first post (I don`t now the reason). But result is the same – app terminates after splash screen with such an error – https://yadi.sk/i/YoOIT0-83MyhGG

**Comment by tsonevn** [comment]
Hi @Yevart,
Regarding your lates posts I found that this error could be related to an missing resource in the application. Could you verify, whether `ic_menu` image, exists in `App_Resources/ios folder` and if not  to add it in the ios resource folder.

Then delete `platforms` folder and rebuild the app with `tns run ios` command.

In case similer resource is not used in your app generally, could you provide sample project, which could be debugged locally?

**Comment by Yevart** [comment]
Now everything is ok! Nick, thank you!
