### ISSUE TITLE
GridLayout Rows Overlapping

### ISSUE THREAD

**Issue by guinness74** [NativeScript/NativeScript#483]
I'm new to NativeScript and I'm trying to create my first app. I created the following use interface, and it doesn't looks as expected.

```
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="onPageLoaded">
    <GridLayout columns="auto, *" rows="auto, *">
        <Image row="0" col="0" colSpan="2" src="{{ imageUrl }}" /> 
        
        <Label row="1" col="0" text="row1-col0" cssClass="" />
        <Label row="1" col="1" text="{{ value1 }}" cssClass="" />

        <Label row="2" col="0" text="row2-col0" cssClass="" />
        <Label row="2" col="1" text="{{ value2 }}" cssClass="" />

        <Label row="3" col="0" text="row3-col0" cssClass="" />
        <Label row="3" col="1" text="{{ value3 }}" cssClass="" />

        <Label row="4" col="0" text="row4-col0" cssClass="" />
        <Label row="4" col="1" text="{{ value4 }}" cssClass="" />
    </GridLayout>
</Page>
```

The image appears at the top of the screen as it should, but then all the labels appear in the row underneath it, stacked on top of each other.

Also, I couldn't find where `<GridLayout>` `columns`  or `rows` are documented, so I suspect that might be an issue, because the rest seems OK to me.

What am I doing wrong? Any help would be appreciated. Thank you!

**Comment by guinness74** [comment]
Found this link, which led me to clear up my issue: http://developer.telerik.com/featured/demystifying-nativescript-layouts/.

**Comment by jlooper** [comment]
Glad this article helped you. What was the fix?
