### ISSUE TITLE
Label in FlexboxLayout isn't sized correctly on iOS

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/NativeScript#4834]
Bit of a strange one.

```
<FlexboxLayout class="">
    <Image src="https://placehold.it/40x40" />
    <Label textWrap="true" text="a b c d e f g h i j k l m n o p q r s t u v w x" />
</FlexboxLayout>

<FlexboxLayout class="">
    <Image src="https://placehold.it/40x40" />
    <Label textWrap="true" text="a b c d e f g h i j k l m n o p q r s t u v w x y z 1" />
</FlexboxLayout>
```

The markup above produces this layout on iOS:

![simulator-screen-shot-12-sep-2017 -17 42 11](https://user-images.githubusercontent.com/1102402/30338670-4963f124-97e4-11e7-8e8d-db3ebd95cfaf.jpg)

As you can see the first Label is cut off after "v". Add a couple more characters to the string and the Label wraps properly and the full string is displayed.

This was in the iPhone 7 simulator. Other screen sizes will work/break with different string lengths.

I have a demo project here showing the issue: https://github.com/3rror404/ns-flexbox-issue

```
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.2.0           │ 3.2.0          │ Up to date  │
│ tns-core-modules │ 3.2.0           │ 3.2.0          │ Up to date  │
│ tns-android      │ 3.2.0           │ 3.2.0          │ Up to date  │
│ tns-ios          │ 3.2.0           │ 3.2.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

**Comment by tsonevn** [comment]
Hi @3rror404,
Thank you for the sample project.
I reviewed this case on my side and indeed there is a problem with the setting the correct dimensions for the Flexbox Layout, I was able to reproduce this case on iPhone 7 simulator as well as on Android device. We will investigate further this case and will provide additional info on it. The attached sample project is also tested with @next modules. 
In the meantime, I would suggest using GridLayout as the main container. For example:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="onNavigatingTo" class="page">

    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>

    <GridLayout rows="100 100" class="p-20">

        <FlexboxLayout rpw="0" class="">
            <Image src="https://placehold.it/40x40" />
            <Label textWrap="true" text="a b c d e f g h i j k l m n o p q r s t u v w x" />
        </FlexboxLayout>

        <FlexboxLayout row="1" class="">
            <Image src="https://placehold.it/40x40" />
            <Label textWrap="true" text="a b c d e f g h i j k l m n o p q r s t u v w x y z 1" />
        </FlexboxLayout>

    </GridLayout>
</Page>

```

**Comment by erkanarslan** [comment]
This seems like not working again on Nativescript 4.2
