### ISSUE TITLE
Console.log has no output on terminal

### ISSUE THREAD

**Issue by bigradish** [NativeScript/NativeScript#4835]
When I follow the steps in the "Debugging apps" section of your tutorial https://docs.nativescript.org/tutorial/chapter-1 , both console.log and console.dir have no output on the terminal.

More info:
1. development machine: Windows 10 64bit
2. target platform: android
3. cli version: 3.2.0
4. Cross-platform modules: 3.1.1
5. Runtime: 3.2.0
6. Plugin: no plugin used, just the HelloWorld project in the tutorial.

Thank you.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3118
