### ISSUE TITLE
Webview doesnt open geolocalization prompt to validate permissions

### ISSUE THREAD

**Issue by CristianHCol** [NativeScript/NativeScript#4837]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

## Please, provide the details below:
I'm trying to load a web app made in angularjs, deployed in a web server, the webpage access to te geolocalization through html5 geolcalization api (navigator.geolocalization), when i load the app in a webview the app cant open the prompt modal to allow the access to obtain the geolocalization, however the map is open and i can navigate through it. i was researching about webview geolocalization  permission in Nativescript but i cant found something that it help.

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both
The op
BOTH

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

Tns --version 2.5.0
tns core module 3.2.0
   "tns-android": {
      "version": "3.1.1"
    },
    "tns-ios": {
      "version": "3.1.0"
    }

And
### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
i allow the permissions in manifest 
	<uses-permission android:name="android.permission.INTERNET"/>
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

and info.plist

**Comment by NickIliev** [comment]
@CristianHCol  to set geolocation permission you can use the native approaches. 
For example, you can try the solution in [this thread
](https://stackoverflow.com/a/5423026/4936697)


```
onWebViewLoaded(args) {
    var webview = args.object;
    if (isAndroid) {
        var androidWegView = webview.android; // native Android web view
    } else if (isIOS) {
        var iosWebView= webview.ios; // native iOS web view
    }

}
```

However, instigating and providing help without a code base is very hard. Please post how-to related question in the community channels (like [https://discourse.nativescript.org/](https://discourse.nativescript.org/)) where you could find help from other community members
