### ISSUE TITLE
Set Page Transition Duration/Curve via the XML File

### ISSUE THREAD

**Issue by Fabrianne** [NativeScript/NativeScript#4839]
Hi, first time posting here,

I would like to know if there's a way to set the page transition duration/curve via the XML file
in the doc I could set it using the RouterExtensions class like so:
```
flipToNextPage() {
    this.routerExtensions.navigate(["/main"], {
        transition: {
            name: "flip",
            duration: 2000,
            curve: "linear"
        }
    });
}
```
but what if I want to set it directly without using routerExtensions like:

Button pageTransition="slideLeft" pageTransitionDuration="2000" pageTransitionCurve="easeIn Button

**Comment by NickIliev** [comment]
@Fabrianne  you can use nsRouterLink as shown in [this article section](http://docs.nativescript.org/angular/core-concepts/angular-navigation.html#specifying-page-transitions)

For example
```
<Button text="flip to next" [nsRouterLink]="['/main']" pageTransition="flip"></Button>
<Button text="no transition" [nsRouterLink]="['/main']" pageTransition="none"></Button>
```

**Comment by Fabrianne** [comment]
Thanks @NickIliev,

Also, is there a way to change the default transition timing/curve directly like:

`<Button text="no transition" [nsRouterLink]="['/main']" pageTransition="none" pageTransitionDuration="2000" pageTransitionCurve="easeInOut"></Button>`

or Nativescript currently supports setting the pageTransition="transition_name" directly as of now?

**Comment by tsonevn** [comment]
Hi @Fabrianne,
To change the default transition for the page transision, you could use frame module and its topmost method. To do that you could make this change in `app.component,ts` file. For example:

```
import { Component } from "@angular/core";
import {topmost} from "ui/frame";

@Component({
    selector: "ns-app",
    templateUrl: "app.component.html",
})

export class AppComponent { 
    constructor(){
        topmost().transition = { name: "flip" };
    }
}

```

More about changing the dafault transition could be found [here](http://docs.nativescript.org/core-concepts/navigation#example-10--set-up-a-transition-property-on-page-navigation).
