### ISSUE TITLE
.Section-banner in the site covered by #MainNav and .Section

### ISSUE THREAD

**Issue by TemplarRei** [NativeScript/NativeScript#484]
At resolutions with height below 900 px the Get Started and View in GitHub buttons of the section banner are partially covered by the main nav (not only visually, but functionally - at 1366x768 with bookmark toolbar it's impossible to click the lower half of the buttons).
The social media buttons below are completely covered and can't be clicked. Tested on latest versions of FF and Chrome (screens below).
I think the problem is with the secrion-banner height (100 vh or the entire height of the screen). Adding a min-height value should fix the functionality, even if it makes it a bit uglier.

![ns-issue-chrome](https://cloud.githubusercontent.com/assets/10461026/8888560/8ca1585a-32ba-11e5-8bf1-00ecc7d63ce7.png)
![ns-issue-ff](https://cloud.githubusercontent.com/assets/10461026/8888559/8c9c81c2-32ba-11e5-96d6-6763cd8c98ba.png)

**Comment by valentinstoychev** [comment]
Thank you for reporting this! It should be fixed now.

**Comment by TemplarRei** [comment]
Yup :) Glad to help!

2015-07-28 10:13 GMT+03:00 Valentin Stoychev <notifications@github.com>:
