### ISSUE TITLE
In NS 3.x is Javascript async/await supported

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/NativeScript#4846]
In NS 3.x is Javascript async/await supported - used to work in NS 2.x.

In code, I've got something like:

`private async onTapBounce( )
{
   //await my_func();
}
`
Looking at the JS code

`   ToyModel.prototype._onTapBounce = function (label) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                return [2 /*return*/];
            });
        });
    };`

I'm getting undefined ____awaiter at runtime.

**Comment by tsonevn** [comment]
Hi @erjdriver,
Thank you for contacting us.

About your request, I make a little research and found that async/await should be supported in NativeScript.  For further help and more info how to use it, you could review the article [here](https://www.nativescript.org/blog/use-async-await-with-typescript-in-nativescript-today).

Another option to be able to use async/await is to open your project `tsconfig.json` file and to set `noEmitHelpers ` to `false`.

Hope this helps.

**Comment by erjdriver** [comment]
Thank you - it does.
