### ISSUE TITLE
How can I add some offset between spans in a FormattedString?

### ISSUE THREAD

**Issue by vegeorgi** [NativeScript/NativeScript#4849]
### Tell us about the problem
Hi,

I`m trying to add some offset between two spans in a FormattedString, but this is something that I could managed to do only adding some spaces into one of the spans. I searched the  [API](https://docs.nativescript.org/api-reference/classes/_text_span_.span.html), but I did not find anything I could use

Is this the only way to achieve it? 

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
tns --version - 3.2.1

### Please tell us how to recreate the issue in as much detail as possible.
[Repo](https://github.com/NativeScript/template-master-detail-kinvey/blob/master/cars/cars-list-page.xml#L43)

**Comment by tsonevn** [comment]
The FormattedString does not support offset between spans. The styling for the FormattedString layout is not controlled by the modules, which interfere with implementing this functionality
