### ISSUE TITLE
Bug in GridLayout xml processing

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/NativeScript#4850]
I've got the following snippet of xml page definition

`<GridLayout columns="12,32,40,*,auto" rows="auto">
    <Label row="0" col="0" colspan="5"/>
 </GridLayout>`

I snipped out some irrelevant code.

The label width is being set to 12 - when in actually since this label spans 5 columns - it should be the sum of all the columns.

Used to work as expected in NS 2.x but not in NS 3.2

**Comment by tsonevn** [comment]
Hi @erjdriver,
Thank you for writing us.
I reviewed your case and found that the problem is related to a mistake in the property name. The name of the property should be written as follow `colSpan` and the Label will be displayed with full width.
```
<GridLayout columns="12,32,40,*,auto" rows="auto"> 
   <Label row="0" col="0" colSpan="5"/> 
</GridLayout>
```

**Comment by erjdriver** [comment]
Thanks - that was it.
