### ISSUE TITLE
Can we integrate nativescript fragment with native fragment?

### ISSUE THREAD

**Issue by chancyWu** [NativeScript/NativeScript#4856]
We are planning to integrate nativescript with our existing android app. I know we can start one nativescript activity with nativescript fragment to show. Just wonder whether we could call nativescript fragment directly from android activity or nativescript fragment work with normal android fragment? Looks cannot, because i try to call the nativescript fragment from android activity. the app will crash due to missing _frameId in  `var frameId = fragment.getArguments().getInt(FRAMEID);` (ui/frame/frame.js 581)

**Comment by hshristov** [comment]
@chancyWu haven't planned using directly fragments. It may work but you will have to call directly JS from Java. And you will probably need to pass a `android.os.Bundle`.
My recommendation is to use `NativeScriptActivity`

**Comment by chancyWu** [comment]
@hshristov I see. Thanks for your update.
