### ISSUE TITLE
Make Sidemenu / Sidedrawer a module

### ISSUE THREAD

**Issue by paranoid-android** [NativeScript/NativeScript#486]
The sidemenu is a valuable and common UI element used in apps. It is more commonly referred to as the "[hamburger](https://en.wikipedia.org/wiki/Hamburger_button)" menu. When a user clicks the "hamburger" button, a sidemenu appears. Sometimes this menu appears on top of the existing UI, other times, the menu pushes the existing content to the left-or-right when revealed.

A functioning sidemenu is currently available in the [TelerikNEXT](https://github.com/NativeScript/sample-TelerikNEXT) sample app as the [sidedrawer](https://github.com/NativeScript/sample-TelerikNEXT/tree/master/app/TelerikUI/sidedrawer). It would be great if this component was included as a baked-in module.

**Comment by manijak** [comment]
:+1:  This is a must. Hope to see such a module in 1.2.0 

The sidedrawer in the TelerikNEXT example is not good enogh. In this example all views are included in the same page where the sidedrawer is (similar to TabView). This results in very messy markup, especially when your app has over 10 different views/pages, and most of them fetch external data on load (slows down the app untill the loading is finished for all views).

I do see a "ui/side-out" module in the master branch, but it's been here for over 5 months and no progress has been made (not released).

**Comment by valentinstoychev** [comment]
Hey @manijak i'm happy to let you know that sidemenu is part of the official 1.2.1 release due next week.

**Comment by ginev** [comment]
Hi there @manijak,

Could you please elaborate a bit further on how would you expect to have a side-drawer behave in contrast to what you are pointing out as a weak point of the existing one? Currently, the existing side-drawer exposes the *mainContent* and *drawerContent* properties which are used to define what's inside the sliding pane and the main pane of the component. What are the alternative options you would like to have available?

Thanks!

**Comment by manijak** [comment]
Hi @ginev, I'd be happy to :)  
I do admit that I was a bit harsh on my previous post. A module like the one in the TelerikNEXT is not bad, at all, and would work nice in smaller apps. 

But in my case, the app I am designing, has over 10-12 different views, and reads a lot of external data. So I would not perfer to load all of that when the app launches. 

But. I did find an example not that long ago, that had a great idea for a side-menu, but for some reason it did not work well on my app (perhaps the code is outdated), also crashed a few times. But the idea is still good. 

It's a module that you add like any other. In it's attributes you define the names of a main-page and a menu-page.  This is the starting point of the app. When loaded, it loads the main-page as the main view, and when calling the menuTriggerAction event, it slides in the view defined in the menu-page attribute. 

Found it here: http://nuvious.com/Blog/2015/5/30/its-finally-here-nativescript-animated-side-menu
Git: https://github.com/alexziskind1/nativescript-animated-menu-demoapp

Too bad it didn't work on my end, the layout of the pages was messed up. And the type of animation (slide out & zoom inn\out) didn't feel very native. Plus it crashed if the main-page had a tabView in it. 

Hope this helps.

**Comment by valentinstoychev** [comment]
I think we need to clear the concept. If side drawer is an APP level menu, then it doesn't makes sense to declare its content on page level. 

The thing is that it is *page-level* component. And this is how it should be, because the design patters dictate that you will have pages with side bar or without sidebar and also for different pages you may want to have different side bar components.

To make life simpler for you, you can start using custom XML components, to declare the UI and then just reuse them in the side drawer context. You will not need to declare all the UI in a single page.

Does this makes sense?

**Comment by manijak** [comment]
Yes, that does make sense :)  My head was wrapped around the tought of having one static menu for all pages. But yeah, creating a custom component for the common parts of the menu would help. 
As you said this gives you the flexibility of having different menus or none on some pages.

Glad we had this disscussion :) Makes me think in a different way than before.
