### ISSUE TITLE
Notification 'App' [Android]

### ISSUE THREAD

**Issue by fabioloreggian** [NativeScript/NativeScript#4860]
Hi there

I have been searching around the web, and I haven't come across anything substantial.

Firstly let me describe the 'component' that I am looking, when opening Google Maps you get a sticky notification 'app' when you pull down the notification bar [android]. Likewise when you start Google Music and you 'close' the app there is a notification 'app' that stays where you can control the music etc.

So hopefully you know what I am looking for, is there any implementation of this functionality within NativeScript, or will it be a feature?

If not can someone please direct me to some resources for android that I can have a look at. Thank you for all your awesome work.

**Comment by fabioloreggian** [comment]
Not sure how to add the question label to this issue

**Comment by tsonevn** [comment]
Hi @fabioloreggian,
First of all, thank you for your interest in NativeScript.

I reviewed your question, however, I am not sure that I understand it correctly. In case you are looking for a way to show notifications when the app is not running, you could use `nativescript-local-notifications` [plugin](https://github.com/EddyVerbruggen/nativescript-local-notifications), which provides similar functionality.

In addition, I would suggest using [NativeScript forum](https://discourse.nativescript.org/) or [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) for any further questions. The main purpose of this repository is feature requests and bug reporting.
