### ISSUE TITLE
Application LAUNCH EVENT behavior [android]

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/NativeScript#4863]
When an app starts for the first time - it executes app.ts - gets to the end and
app.start() is called and then the LAUNCH-EVENT.

Within the app I navigate to other pages. 

And then go to the Android Home page (my app gets suspended).

I then click on the app icon again:
  - the app is brought to the front
  - the app.start() at the end of app.ts is NOT called (ok with that)
  - but the LAUNCH EVENT is called and that seems to call the same page that I called app.start() during the true app start.
  - then the resume event is called.

In the above case the app is being brought to the foreground - just going thru a suspend/resume state - my belief is that the LAUNCH EVENT should not be called.

It also screws up the navigation history if the hardware back button is pressed - it looks like the second LAUNCH created a new start page at the end of the old history.

So in the second app icon click - I just want to resume on the page that I left off on - not the first start page.

I understand that in some cases - it will be a true app start - like a cold start.

My question is: is there a way to short circuit the second app LAUNCH EVENT and continue where you left off.

Thank you - I appreciate all the help!

**Comment by tsonevn** [comment]
Hi @erjdriver,
This behavior seems to be Android related and it is not something specific for NativeScript. When you start an android application while clicking on the icon, Android will start a new Activity on top of the old one as it is described [here](https://stackoverflow.com/a/21407931/6133327). In this case, the launch event will be fired again.

Regarding that, something that I could suggest to set up `android:launchMode="singleTop"` option in your project `AndroidManifest.xml` file, as it is described [here ](https://stackoverflow.com/questions/16126511/app-completely-restarting-when-launched-by-icon-press-in-launcher) in this StackOverflow thread.

**Comment by erjdriver** [comment]
Thank you - I'll look into that.
