### ISSUE TITLE
MAC OS install link problem

### ISSUE THREAD

**Issue by robcaa** [NativeScript/NativeScript#4865]
When I Install iOS and Android requirements,
the doc (https://docs.nativescript.org/start/quick-setup) say's: 
>copy and paste the script below into your terminal and press Enter
`ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)"`

Te requested URL returned error: 404 Not Found
Check the link: https://www.nativescript.org/setup/mac

Platform: IOS

What is the correct link?

**Comment by tsonevn** [comment]
duplicated with [issue915](https://github.com/NativeScript/docs/issues/915)
