### ISSUE TITLE
TabView tab bar font size can't increase or decrease

### ISSUE THREAD

**Issue by ghost** [NativeScript/NativeScript#4869]
Hi!
I use latest NativeScriptAngular version
I can't increase and decrease tabItem 'Scanner' and 'Termékeim' font Size
The color change is ok but I can't find how can I css change size?
Can U help me?

```
TabView {
  selected-tab-text-color: $theme-primary-color;
  border-bottom-color: $theme-primary-color;
  android-selected-tab-highlight-color: $theme-primary-color;
}
<TabView #tabview
                 (selectedIndexChanged)="tabIndexChanged($event)">
            <StackLayout *tabItem="{title: 'Scanner'}">
                ...
            </StackLayout>
            <StackLayout *tabItem="{title: 'Termékeim'}">
                ...
            </StackLayout>
        </TabView>
```

**Comment by tsonevn** [comment]
Hi @bumbella,
I reviewed your scenario, however, at the moment there is no functionality, which allows changing the tab's title `fontSize`. Regarding that, I will mark this as a feature request. 
```
TabView {
  selected-tab-text-color: $theme-primary-color;
  border-bottom-color: $theme-primary-color;
  android-selected-tab-highlight-color: $theme-primary-color;
font-size:30;
}
```
As a temporary solution, you could set a fontSize for the whole TabView , which will affect the tabs titles and the child component inside the TabView in Android. Keep in mind that this solution will not work for iOS.

**Comment by Rjgoolsby** [comment]
To expand on this, I'm running to this issue. Also. A work around is to do what @tsonevn said but also set the css for the tab view. This is what I did 
```
TabView {
    selected-tab-text-color: #C86B27;
    android-selected-tab-highlight-color: #C86B27;
    background-color: $accent-light;
    font-size: 20;
}
Page{
    font-size:12;
}
```

**Comment by MartoYankov** [comment]
There is a way to do this for some time now. See https://github.com/NativeScript/NativeScript/pull/5752.

Basically the `TabView` has a new property `tabTextFontSize` and corresponding CSS rule `tab-text-font-size` which affects only the tab title text.

```
<Page>
  <TabView tabTextFontSize="8">
    <TabView.items>
      <TabViewItem title="First">
        <TabViewItem.view>
          <GridLayout>
            <Label text="First View" verticalAlignment="center" horizontalAlignment="center"/>
          </GridLayout>
        </TabViewItem.view>
      </TabViewItem>
      <TabViewItem title="Second">
        <TabViewItem.view>
          <GridLayout>
            <Label text="Second View" verticalAlignment="center" horizontalAlignment="center"/>
          </GridLayout>
        </TabViewItem.view>
      </TabViewItem>
    </TabView.items>
  </TabView>
</Page>
```

**Comment by tofikabdullayev** [comment]
tabTextFontSize="8" doesn't work

**Comment by jokkopp** [comment]
try this in css file
```
TabView {
	tab-text-font-size: 15
} 
```
