### ISSUE TITLE
ListPicker showing up all the content

### ISSUE THREAD

**Issue by jay3dec** [NativeScript/NativeScript#487]
I'm assuming the listpicker to work like a dropdown. But the content of the list picker is all on the form. Here is my xml code,

```xml
<Page loaded="pageLoaded" background-color="blue">
    
        <StackLayout orientation="vertical">
            <ListPicker items="{{names}}">
            </ListPicker>
        </StackLayout>

</Page>
```

And here is the output view of how it looks ,
![untitled](https://cloud.githubusercontent.com/assets/2197531/8891474/32344104-3349-11e5-95e5-172fd8aa2477.jpg)
 The content of the listpicker is two elements and it showing both of them unlike a drop down.

**Comment by enchev** [comment]
The ListPicker is actually NumberPicker wrapper in Android. Here is more info about this widget:
http://developer.android.com/reference/android/widget/NumberPicker.html

Maybe for your case you should use ListView instead.
