### ISSUE TITLE
App is building when I change css or js.

### ISSUE THREAD

**Issue by vijaykumarbollavaram** [NativeScript/NativeScript#4870]
I am new to nativescript. I am creating an hybrid aplication using nativescript. When I change js file or css file entire app is building. Is there an issue

**Comment by tsonevn** [comment]
Hi @vijaykumarbollavaram,
First of all, thank you for your interest in NativeScript,
Regarding your question, generally in case, you make some changes in the js file, the entire project will be rebuilt. If you make changes in the CSS files the application will be restarted and only the styling will be applied again.

For further questions, you could also use [NativeScript forum](https://discourse.nativescript.org/) and [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript).
