### ISSUE TITLE
Device specific styles for ios iphone 6 .!!

### ISSUE THREAD

**Issue by sagar1911** [NativeScript/NativeScript#4877]
Hi all,

I would like to write separate styles for iphone 6 and higher. how can I do that in vanilla NS ???
I tried 
page.ios.minW1080.css 
but didn't work. any suggestion ??

**Comment by NickIliev** [comment]
@sagar1911 does not support CSS qualifiers files. Instead, you can create different classes and load them in the respective XML files.
For iPhone 6 you do not need screen qualifier so `page.ios.xml` will do the job.
From this point, you can load your style for iOS (e.g. `my-ios.style`) in `page.ios.xml` and do the same for the Android styles.

**Comment by sagar1911** [comment]
Hi @NickIliev ,
Thanks for the response.
I have tried 'page.ios.minW326.css' and it worked for me.

**Comment by leocrawf** [comment]
Hi @NickIliev,

Can you share how that file may be added to the xml file? I know it is a really noob question.

**Comment by leocrawf** [comment]
Hi,

I think this doc gives that answer: https://docs.nativescript.org/ui/styling#applying-css-styles
