### ISSUE TITLE
Warning: byline dependency deprecated

### ISSUE THREAD

**Issue by itsashis4u** [NativeScript/NativeScript#488]
While installing using `npm` :
`npm WARN deprecated byline@4.1.1: critical bug fixed in v4.2.0`

**Comment by teobugslayer** [comment]
Hello @itsashis4u,

We have updated our dependencies. This change is actually quite big and can introduce many regressions throughout the entire {N} CLI. That's why we need some more time for testing it and will release it with {N} 1.3.

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#705
