### ISSUE TITLE
Error on "brew cask install android-sdk"

### ISSUE THREAD

**Issue by jblancas-git** [NativeScript/NativeScript#4880]
**This is mi config:**
➜  ~ brew config
HOMEBREW_VERSION: 1.3.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 05bb3532fc3f0d723a8e8af1605c3f8080051e78
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a46a83b94bd4c99bc38750ef42c2ba1e9ea5482d
Core tap last commit: 88 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 9.0 build 900
Git: 2.13.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 9
macOS: 10.12.6-x86_64
Xcode: 9.0
CLT: 9.0.0.0.1.1504363082
X11: N/A
➜  ~

### About the problem when execute the installation
➜  ~ brew cask install android-sdk --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
We will install android-sdk-tools, platform-tools, and build-tools for you.
You can control android sdk packages via the sdkmanager command.
You may want to add to your profile:
  'export ANDROID_SDK_ROOT=/usr/local/share/android-sdk'

This operation may take up to 10 minutes depending on your internet connection.
Please, be patient.

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://dl.google.com/android/repository/sdk-tools-darwin-3859397.zip
Already downloaded: /Users/julio/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip
==> Downloaded to -> /Users/julio/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip
==> Verifying download
==> Determining which verifications to run for Cask android-sdk
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask android-sdk
==> SHA256 checksums match
==> Installing Cask android-sdk
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/julio/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Using container class Hbc::Container::Zip for /Users/julio/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip
==> Executing: ["/usr/bin/ditto", "-x", "-k", "--", "/Users/julio/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip", "/var/folders/gl/wxtc06yn30j2nj8tg9vsvlwc0000gn/T/d20170923-36069-1jypk59"]
==> Creating metadata directory /usr/local/Caskroom/android-sdk/.metadata/3859397,26.0.1/20170923183553.504.
==> Creating metadata subdirectory /usr/local/Caskroom/android-sdk/.metadata/3859397,26.0.1/20170923183553.504/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask android-sdk
==> 47 artifact/s defined
preflight (Preflight Block)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/aapt (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/aapt2 (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/aarch64-linux-android-ld (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/aidl (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/arm-linux-androideabi-ld (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/bcc_compat (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/dexdump (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/dx (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/i686-linux-android-ld (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/llvm-rs-cc (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/mainDexClasses (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/mipsel-linux-android-ld (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/split-select (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/x86_64-linux-android-ld (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/zipalign (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/bin64/e2fsck (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/bin64/fsck.ext4 (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/bin64/mkfs.ext4 (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/bin64/resize2fs (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/bin64/tune2fs (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/emulator (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/emulator-check (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/emulator64-arm (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/emulator64-crash-service (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/emulator64-mips (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/emulator64-x86 (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/mksdcard (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/platform-tools/adb (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/platform-tools/dmtracedump (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/platform-tools/etc1tool (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/platform-tools/fastboot (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/platform-tools/hprof-conv (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/platform-tools/systrace/systrace.py (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/android (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/archquery (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/avdmanager (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/jobb (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/lint (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/monkeyrunner (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/screenshot2 (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/sdkmanager (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/uiautomatorviewer (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/mksdcard (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/monitor (Binary)
postflight (Postflight Block)
uninstall_postflight (Postflight Block)
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/sdkmanager", "tools", "platform-tools", "build-tools;26.0.1"]
==> Exception in thread "main" 
==> java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
==> 	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
==> 	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
==> 	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
==> 	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:117)
==> 	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:93)
==> Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
==> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
==> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
==> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
==> 	... 5 more
==> Purging files for version 3859397,26.0.1 of Cask android-sdk
Error: Command failed to execute!

**==> Failed command:
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/sdkmanager tools platform-tools build-tools;26.0.1**

==> Standard Output of failed command:

==> Standard Error of failed command:
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:117)
	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:93)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 5 more

==> Exit status of failed command:
#<Process::Status: pid 36194 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:65:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/base.rb:14:in `system_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:68:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:44:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:44:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:28:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:191:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'

### Which platform(s) does your issue occur on?
MAC Os Sierra 10.12.6

How can I do to fix this?  Thank you very much!.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3130
