### ISSUE TITLE
Thread support: Approx how will it be designed&implemented, as it looks now?

### ISSUE THREAD

**Issue by mike-ense** [NativeScript/NativeScript#4885]
Hi!

I guess it's worthwhile for all us who use Nativescript to get a rough idea about how you intend to implement multithreading.

Probably Windows support is a way higher priority than multithreading, but, it would be great to learn to know your general ideas, so that any code I/others write for Nativescript, can be designed to fit the threading model that you are thinking about, maybe that can save us Nativescript app developers some effort later.

Thanks!

**Comment by NickIliev** [comment]
@mike-ense the multithreading model is already part of NativeScript and can be achieved by using **workers**. The full documentation article can be found [here](http://docs.nativescript.org/core-concepts/multithreading-model).

[Here ](https://www.nativescript.org/blog/using-workers-in-nativescript-to-execute-javascript-on-background-threads)you can find a great blog post about how to use workers to execute tasks in the background.
