### ISSUE TITLE
App freeze after use router.back()

### ISSUE THREAD

**Issue by cmargulhano** [NativeScript/NativeScript#4886]
I used this to change page:

this.router.navigate(['XXX'], { transition: {name: "slideLeft"}});

in a < page-router-outlet > template HTML.

App freeze after use: this.router.back()

After remove transition, everything works again;

Platforms: iOS/Android/Both
- CLI: 3.2.1
- Cross-platform modules: 3.2.0
- Runtime(s): 3.2.0
- Plugin(s): 3.2.0

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#1007
