### ISSUE TITLE
Additional Page Events - Feature Request

### ISSUE THREAD

**Issue by glen-stephens** [NativeScript/NativeScript#4887]
Would love to see additional page events.  There currently is no differentiation between when a page is being instantiated or navigated to for the first time vs. when you are going to it in a cached state using the ActionBar Back navigation.  It would be helpful if there was an event for when the page is being created and a separate call for when the page is already in memory and just being navigated to.

**Comment by NickIliev** [comment]
@glen-stephens you can achieve that with a boolean flag to check if the page has been already visited (e.g. in `navigatedTo`, `loaded` or `navigatingTo` events). Then you can save/restore the state using application-settings.
