### ISSUE TITLE
Improve the console module

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#49]
_From @atanasovg on April 14, 2015 10:32_

The current console implementation uses the built-in `console` object for iOS and our custom JavaScript implementation for Android. This custom implementation is not behaving like the Web one and works for primitive types only (and plain Objects, without circular references). We may take a look at how [Node.js](https://github.com/joyent/node/blob/master/lib/console.js) have implemented it.

_Copied from original issue: NativeScript/cross-platform-modules#281_

**Comment by nsndeck** [comment]
Android console improved by adding "%j" format option which stands for "JSON.stringify". This format option will print the entire js object. Usage example:
var button = new buttonModule.Button();
console.log("%j", button);

Result will be same as:

console.dump(button);

For objects that have circular references all circular references will appear similar to "CR: value.toString()".

Closed with commit #297.
