### ISSUE TITLE
Style individual items inside action bar of a page

### ISSUE THREAD

**Issue by thomaszang** [NativeScript/NativeScript#4912]
Hi,

Does NativeScript support the ability to style individual items inside action bar of any page? if no, is there a plan for it?

**Comment by tsonevn** [comment]
Hi @thomaszang,
In case you need to setup specific styling to the ActionBar, you could display custom view inside the ActionItems. For more info, you could review the documentation [here](http://docs.nativescript.org/cookbook/ui/action-bar#displaying-custom-view-in-action-items).
Another option would be to modify your styles/theme xml files to set the action items to white for the default theme (this one requires some android work)
