### ISSUE TITLE
Need Help setting up the bundle-config file for a webpack build

### ISSUE THREAD

**Issue by shiv19** [NativeScript/NativeScript#4914]
I have tried to setup the bundle-config file for a webpack build. 
But it fails to find nativescript-theme-core every time, when I run `npm run start-android-bundle`

Can someone point me in the right direction to use webpack?

Here are the files. [files.zip](https://github.com/NativeScript/NativeScript/files/1355583/files.zip)

Files included:
bundle-config.js
report/stats.json
report/report.html
vendor.js
app.scss
app.css
webpack.config.js

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-dev-webpack#283
