### ISSUE TITLE
CSS placeholder-color for TextView is not applied when hint is updated

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#4915]
Issue: setting `placeholder-color` is applied successfully on initial load. But when the `hint` value is updated dynamically via binding the `placeholder-color` is reset to the default one and the CSS value is not applied on iOS (works as expected on Android).

Steps to reproduce:
- use [this test application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4458_new) or follow these steps

- set the placeholder-color via CSS
```
.form-input {
    color: red;
    placeholder-color: blue;
}
```

- the hint is dynamically changed
```
<Button text="change hint" tap="onChangeHint" />
<!-- dynamically chaning the binded value will not apply the placeholder-color on iOS (works on Android) -->
<TextField class="form-input" hint="{{ hint }}" autocapitalizationType="none" autocorrect="false" keyboardType="email" returnKeyType="next">
</TextField>
```
- in the code behind change the hint value dynamically
```
export function onChangeHint() {
    vm.set("hint", "NEW HINT VALUE");
}
```

Result: on iOS after the `hint` value is changed, the placeholder-color is lost.

Related to [https://github.com/NativeScript/NativeScript/issues/4458](https://github.com/NativeScript/NativeScript/issues/4458)

**Comment by crowmagnumb** [comment]
Yup, this is still an issue. My placeholder-color css on TextView does not show up until I have focused and then un-focused on the TextView. Seems to work fine in TextField however.

**Comment by rigor789** [comment]
This seems to be fixed, cannot reproduce.
