### ISSUE TITLE
Using Alamofire Swift Library in Nativescript plugin

### ISSUE THREAD

**Issue by tigerdi** [NativeScript/NativeScript#4923]
I am trying to use the Alamofire Http Networking library for my Nativescript (+ Angular) iOS app:
https://alamofire.github.io/Alamofire/

I have tried wrapping it in a Nativescript plugin, and the structure is very simple:
```
nativescript-alamofire /
    package.json   
    platforms /
        ios /
            Podfile
```
The Podfile contains: 

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

pod 'Alamofire', '~> 4.5'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

```

When I install the plugin from a local folder, it all seems ok. I then remove any existing iOS platform and build from scratch. I can see that the Alamofire pod is downloaded into the iOS platform folder. So now it seems I have all the files downloaded. 

My question is how to import the Alamofire module? Say on my login page, I try this:

`import {Alamofire} from "nativescript-alamofire"`

It says an error saying the module cannot be found. Is this because I need to have an index.ts file at the root of my plugin which exposes the iOS library? 

Eventually, I just want to be able to do a simple request such as this:

```
Alamofire.request("https://httpbin.org/get").responseJSON { response in
    // code
}
```

I know I will have to use Marshalling to convert it into typescript, which Im sure is another thing I will have trouble with. Any help you can give me would be most appreciated.

**Comment by ivanbuhov** [comment]
@tigerdi You can only call APIs from JavaScript that are visible to the Objective-C runtime. This include all Objective-C APIs and only the subset of all Swift APIs that are exposed to Objective-C. So, to use a Swift API (class/function/method etc.) from NativeScript, first make sure that it can be used from Objective-C code. For more information which Swfit APIs can be exposed to Objective-C, see [here](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html#//apple_ref/doc/uid/TP40014216-CH4-ID53).

After that you can use the API without importing any modules. All classes should be exposed directly on the global object:
```
SomeClassFromAlamofire.someMethod();
```
