### ISSUE TITLE
TabView memory leaks using iconSource

### ISSUE THREAD

**Issue by Tompote** [NativeScript/NativeScript#4924]
### Tell us about the problem
Setting iconSource in *tabItem causes memory leaks.

### Which platform(s) does your issue occur on?
Android (did not test on iPhone)

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.2.1
- Cross-platform modules: 3.2.0
- Runtime(s): 3.2.0

### Please tell us how to recreate the issue in as much detail as possible.
Create a TabView with angular (didn't test without it) following [https://docs.nativescript.org/cookbook/tab-view-ng](url), be sure to set the iconSource property inside the tabItem. Navigate back and forth to this component will eventually throw OutOfMemoryException.

I guess it's related to #2571. Maybe the fix was ok for regular Image but not for iconSource inside tabItem.

**Comment by Tompote** [comment]
After further investigation I found that it comes from this file:
https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/tab-view/tab-view.android.ts
(line 167)

**Comment by NickIliev** [comment]
@Tompote I have tried to reproduce the out of memory exception using [this test application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4924) but to no avail. 

Can you please share sample project that can stably reproduce the issue or provide any further information on how to modify [the test project](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4924) so we could hit the error.

**Comment by Tompote** [comment]
Check out this [https://github.com/Tompote/NativeScript_issue_4924](sample project) to see the error more easily. I just added a home component with a button to navigate to your items page.
After I navigate to item I can click back and then go to items again, but after the ninth attempts I run into OutOfMermoryException.
I'm sorry I don't know how to perform real memory testing (with actual values) but I guess the bigger the iconSource is, the faster memory runs out.

I'm pretty sure it's due to the line I posted above, because drawable Bitmap are not release properly in JS context. I really think it's the same error as #2571 that has been fixed for classic Image.

**Comment by NickIliev** [comment]
@Tompote confirming this as a bug as it really appears that navigation back and forward to tab-view is causing a memory leak (when the TabView has iconSource added). Test project to reproduce can be found [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4924) or use the one provided in the thread above.

As a workaround to this issue you can use significantly smaller images for your tab items and for Android, you can create properly resized resource images for the different devices screens. For example, even [this background logo](https://github.com/NativeScript/template-hello-world-ng/blob/master/App_Resources/Android/drawable-mdpi/logo.png) image is only 15K (compared to over 200K for the apple used in your demo). This would not solve the memory leak but will "spare" some devices with lower memory and would prevent throwing the out of memory exception after few navigations.

**Comment by Tompote** [comment]
@NickIliev Thanks for your answer. Can we hope for a fix in the next release ? It's quite a huge problem for our project because we will navigate to this component really often, we can't let memory leaks grow and slow down our application until it throws OOM, even if I use 10 times smaller images.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#1044
