### ISSUE TITLE
iOS 8.1 issue - Can't find variable: UIFontWeightRegular

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#4927]
Application crashes out at startup with:
`file:///app/tns_modules/tns-core-modules/ui/styling/font.js:76:39: JS ERROR ReferenceError: Can't find variable: UIFontWeightRegular`

**Update**: According to the DOCS and MetaData, the UIFontWeightRegular (and siblings) are iOS 8.2 additions; hence the reason why it is crashing in 8.1...   If NS is no longer compatible with 8.1, it might be worth documenting somewhere what versions it is compatible with.   I checked both the iOS and this repo and main doc site and didn't see anything saying versions of iOS supported.

Steps tested:
- Down graded to 3.11 TNS core modules
- Recreated app from scratch. (i.e. another tns create...)
- I attached a debugger to the app and broke just before the line it crashes on, and UIFont is defined, but UIFontWidth* are not a valid references.   
- I built the metadata; and it shows it in the meta data for UIKit.yaml.
- I switched to a iOS 11 simulator and it worked!   

### Did you verify this is a real problem by searching
Yes

### Which platform(s) does your issue occur on?
Anything less than iOS 8.2 apparently

### Please provide the following version numbers that your issue occurs with:
- CLI: tns 3.2.1
- Cross-platform modules: 3.2.0 & 3.1.1
- Runtime(s): 3.2.0
- Plugin(s): None extra

### Please tell us how to recreate the issue in as much detail as possible.
tns create testApp
tns platform add ios
tns run ios

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
No additional code, just running a brand new unmodified application on the iOS 8.1 simulator crashes.

**Comment by vakrilov** [comment]
You are correct - we have added some fonts related code that depends on IOS 8.2+ in the `tns-core-modules` (note: the IOS runtime is still compatible with the IOS 8.1, but the code of the modules is not).

The marketshare of all 8.x devices is currently <2% and most of them are updated to `8.4`, and this is the reason that we didn't plan a hot-fix with a work-around code for <8.2 IOS versions.

About the docs - thanks for pointing that out. @NickIliev and @tsonevn - do you think you can update the appropriate articles?

**Comment by NathanaelA** [comment]
Am I correct that this a 3.0 Font change, so technically if someone needed < 8.2 compatibility they could use TNS-Core-Modules 2.5 correct?

I really think the versions should be listed somewhere easily found on the docs site and in the main repo readme.   It wasn't until I traced down the UIFontWeight* back to Apples docs and read the meta data that it finally understood it was by _design_ broken with 8.1...

**Comment by NickIliev** [comment]
Closing this one as the official support4ed version of iOS is now 9.0
