### ISSUE TITLE
Does NativeScript work with ThreeJS?

### ISSUE THREAD

**Issue by cmayankc** [NativeScript/NativeScript#4928]
We are currently planning to create a game app which uses ThreeJS as the rendering engine. I searched and could not find any plugin that integrates ThreeJS with NativeScript.

I just want to know if ThreeJS code will render properly if used with NativeScript and Angular2.

If now, are there any plans for this?

**Comment by NickIliev** [comment]
@cmayankc the short answer is no - the ThreeJS library will not work out-of-the-box in NativeScript (as it depends on some DOM related dependencies + some OpenGL WebGL features that are not currently supported directly in NativeScript). More detailed info [here](https://github.com/NativeScript/NativeScript/issues/289)

**Comment by kasra0** [comment]
Hello,
I would like to know if there is any news about the OpenGL WebGL support in NativeScript ?
I use threejs as the 3D rendering engine for some parts of my application.

Thanks

**Comment by fei4xu** [comment]
you can check out https://github.com/pmccloghrylaing/nativescript-webgl
