### ISSUE TITLE
NativeScript drawer not working : " showDrawer() is not a function"

### ISSUE THREAD

**Issue by moda20** [NativeScript/NativeScript#4932]
Hey, is it me or the official documentation at docs.telerik.com about the drawer is not right ?

I tried that in my app and it didn't work. 
Here is the code i wrotein the ts file.
```
    toggleDrawer(){
        console.log("RRRR");
       let X = <RadSideDrawer>( frame.topmost().getViewById("drawer"));
        /*console.log(sideDrawer.toggleDrawerState())*/
        /*sideDrawer.toggleDrawerState()*/
        X.showDrawer();
    } 
```

and the XML content 
```
    <drawer:rad-side-drawer id="drawer">
        <drawer:rad-side-drawer.mainContent>

            <grid-layout>
                <slides>
                    <slide class="slide-1">
                        <StackLayout>
                            <GridLayout rows="60" columns="*, *, *" >
                                <Button class="btn btn-primary" col="2" text="Button" (tap)="rr()"></Button>
                            </GridLayout>
                        </StackLayout>
                        <Label text="This is Panel 1"></Label>
                    </slide>
                </slides>
            </grid-layout>

        </drawer:rad-side-drawer.mainContent>
        <drawer:rad-side-drawer.drawerContent>

        </drawer:rad-side-drawer.drawerContent>
    </drawer:rad-side-drawer>
```

Note i use the nativescript plugin slides, which should not by any means have any problems with the drawer.
so when i try to show the drawer like the docs says i get this error
`JS: ERROR TypeError: X.showDrawer is not a function
JS: ERROR CONTEXT [object Object]
`
any ideas if this is a bug or outdated docs ?

**Comment by NickIliev** [comment]
Hey, @moda20 as discussed in [the previous issue](https://github.com/NativeScript/nativescript-angular/issues/1032) both `showDrawer` and `closeDrawer` methods will work only if you have a valid reference to the drawer component. Make sure that you are getting the reference before trying to access drawer specific methods.

Another thing that I have noticed in your code is that it is not clear where the method `toggleDrawer` is used. Make sure that when you make a call to this method you have a valid drawer reference with `let X = <RadSideDrawer>( frame.topmost().getViewById("drawer"));`

Please, once again notice that this repository is for logging issues, bugs and features related to tns-core-modules and the nativescript-angular repository is for logging issues, bugs and features related to nativescript-angular plugin. For how-to related question post in the community channels like [https://discourse.nativescript.org/](https://discourse.nativescript.org/) and bugs related to nativescript-pro-ui plugin use the [nativescript-ui-feedback repository](https://github.com/telerik/nativescript-ui-feedback/issues)

**Comment by NickIliev** [comment]
If you are still experiencing troubles debugging the execution of toggleDrawer method please send me a sample project as an archive or GitHub link (no node_modules and platforms folders are needed)
