### ISSUE TITLE
Navigation scroll to matched element in list items when tap

### ISSUE THREAD

**Issue by vijaykumarbollavaram** [NativeScript/NativeScript#4935]
Hi I Am new to native script. While learning native script I faced a problem that, I have a-z letters and list items side by side. When I tap any item in (a-z), list view must move to matched first letter in list items. Same as contact filter using alphabets. Is there any solution for this.

**Comment by NickIliev** [comment]
@vijaykumarbollavaram this repository is for logging issues. bugs and features related to NativeScript.
For how-to related question please post in one of the community channels like SO or [discourse.nativescript.org](https://discourse.nativescript.org/).

Regarding your question: you can use [scrollToIndex ](https://docs.nativescript.org/api-reference/classes/_ui_list_view_.listview.html#scrolltoindex) method to manually scroll to desired list-view item. That said you can implement the feature by check the selected alphabet letter and from that point scroll to the first item in your list view while checking the index item in your sorted source array.

**Comment by vijaykumarbollavaram** [comment]
@NickIliev  Sorry for that. Next time onwards I will post  inn community channel And thanks for answer
