### ISSUE TITLE
Nativescript - list-picker error (iOS only)

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/NativeScript#4942]
I have a vanilla nativescript app with NS version 2.5.0 and tns-core-modules version 2.5.0. In it I am using a list picker in a modal page to display a list of items. Here is how I call the modal:

```
var ctx = {
        items: model.states,
        value: model.State
    };
    page.showModal('./modals/ddl', ctx, function (value) {
        model.set('State', value);
    });
```

Then in the modal page (in onShownModally), I initialize the list items as:
```
page = args.object;

    var ctx = args.context;

    model.set('selectedIndex', 0); //the default
    //console.log('incoming value: ' + ctx.value);
    var itm = [];
    for (var i = 0; i < ctx.items.length; i++) {
        itm.push(ctx.items[i].name);
        if (ctx.value && ctx.value == ctx.items[i].value) {
            model.set('selectedIndex', i);
        }
    }

    model.set('items', itm);
    model.set('objects', ctx.items); 
    model.set('value', ctx.value);

    closeCallback = args.closeCallback;
    page.bindingContext = model;
```

Here is the markup:

```
<ListPicker id="picker" items="{{ items }}" selectedIndex="{{ selectedIndex }}" 
                    verticalAlignment="center" horizontalAlignment="center" padding="10" />
```

Everything works well and the page and the list load properly displaying the list of states, except that sometimes, when I am scrolling up and down the list the app crashes and I get the error display in the image below. This error happens only on iOS, I was never able to reproduce it on android. The problem is that it happens intermittently and I cannot figure out where the problem is.

![20171011_132116](https://user-images.githubusercontent.com/11344576/31509064-f824a14c-af34-11e7-8214-f895f2a0a4b9.jpg)

Any ideas are highly appreciated. Before you suggest it, currently, I cannot upgrade the project to a newer version of NS.

Thank you.

**Comment by tsonevn** [comment]
Hi @dpdragnev,
I tested the described scenario while using the attached code snippet with tns-core-modules 3.2 and 2.5.3, however, was unable to recreate the similar problem. It would help if you could provide sample project, which could be debugged locally on our side or review the attached project and make the needed changes. 

Also, it would help if you could provide some detailed description on the steps, which you used while building the application.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1382354/Archive.zip)

**Comment by dpdragnev** [comment]
Thank you Nikolay,

I am not sure what really happened, but I am testing on another device now and everything is working fine.  It could be something with my test device.

Thank you for your help.
