### ISSUE TITLE
Crash on android

### ISSUE THREAD

**Issue by angelscat** [NativeScript/NativeScript#4943]
My app crashes frequently. This is the error on console. Can anyone help me, Thanks!

---------

chromium: [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
10-13 10:53:28.094  4391  4391 I cr_BrowserStartup: Initializing chromium process, singleProcess=true
10-13 10:53:28.183  4391  4391 I cr_DRP  : No DRP key due to exception:java.lang.ClassNotFoundException: com.android.webview.chromium.Drp
10-13 10:53:41.896  4502  4391 F google-breakpad: M D8AE9000 008EB000 03207000 BCB99A3173DFB4D88935B0CB4A7CA9D80 libwebviewchromium.so
10-13 10:53:41.896  4502  4391 F google-breakpad: M DF6FD000 00000000 00002000 5A18791166F2CB7437D154194C316B9A0 libwebviewchromium_loader.so
10-13 10:53:41.900  4502  4391 F google-breakpad: M EF249000 00000000 00003000 D7E60E0E7B6968707EE4E54A309DC7240 libwebviewchromium_plat_support.so

**Comment by tsonevn** [comment]
Hi @angelscat,
Thank you for reporting this issue,
I reviewed your case, however, was unable to recreate a problem, which could lead to the above-given error. It could be related to some specifics on the project or some of the NativeScript plugins, which are used.
Regarding that, It would help if you could provide us some more info about your environment (CLI, node, npm, tns-core-modules) and info about the device or simulator, which is used for testing.

Also providing a sample project or at least some sample code will be really helpful.

**Comment by NickIliev** [comment]
@angelscat are you experiencing this error on real device - if it only appears on emulator it might be related to some limitation for the Android WebView working with some emulators as discussed [here](https://stackoverflow.com/a/35360605/4936697)

**Comment by angelscat** [comment]
@tsonevn @NickIliev 
Thank you for helping me!
I updated to the newest version(CLI, tns-core-modules), and the app don't crash now.
