### ISSUE TITLE
Protocol buffers and gomobile integration

### ISSUE THREAD

**Issue by gedw99** [NativeScript/NativeScript#4944]
Just raising this too see if I am reinventing the wheel.

I am writing a NS plugin with golang and gomobile.

For the IO layer I am planning to use protocol buffers for speed and codegen reasons.

Has anyone gotten this far yet ?
This is a non GUI plugin.

Thanks in advance !!

**Comment by Pip3r4o** [comment]
Hey @gedw99 you might have better luck asking this on the NativeScript forums - https://discourse.nativescript.org/

Github issues here are mostly used to track issues and feature requests

**Comment by gedw99** [comment]
Will do. thansk @Pip3r4o 

Closing this...
