### ISSUE TITLE
Multiple paths for nativescript module resolution, e.g. typescript paths

### ISSUE THREAD

**Issue by flosn** [NativeScript/NativeScript#4946]
Is it possible to define multiple pathes the nativescript module resolver looks for when resolving absolute imports? 

E.g. in typescript this is possible by configuring the `compilerOptions.paths`:
`"paths": {
      "*": [
        "app/devices/nativescript/*",
        "app/*"
      ]
 }`

In webpack you can pass an array to `resolve.modules` what tells webpack where to look for imports.

**Comment by NickIliev** [comment]
@flosn[ look here](https://github.com/NativeScript/nativescript-cli/issues/3138#issuecomment-332794626) for more information on that matter.

Closing as duplicate to [https://github.com/NativeScript/nativescript-cli/issues/3138#issuecomment-332794626](https://github.com/NativeScript/nativescript-cli/issues/3138#issuecomment-332794626)
