### ISSUE TITLE
Issue with installing NativeScript while using npm 4.0.2

### ISSUE THREAD

**Issue by Eddie541** [NativeScript/NativeScript#4948]
When performing npm i nativescript –g on Windows I get the following errors:

Cannot read property 'assert-plus' of undefined
And 
Cannot read property 'minimist' of undefined

My npm-debug.log file is here:
https://gist.github.com/Eddie541/8a54f37e044578032fb76b90c34a4c8e

My environment:

Windows 7 SP1
Node v6.11.2
npm 4.0.2
java SDK version "1.8.0_144"
Android Studio installed
Android SDK  android-26
Android platform / build tools 26.0.2
JAVA_HOME and ANDROID_HOME environment variables set

The following issue is the same as mine however it is for Mac and the solution was to upgrade the version of Homebrew; Chocolatey is currently not an option for me.

https://github.com/NativeScript/NativeScript/issues/4682

I am able to npm install other packages without issue.

Thanks,
PWE

**Comment by tsonevn** [comment]
Hi @Eddie541,
Thank you for contacting us,
Could you try clearing npm cache with `npm cache clear` and then install NativeScript again with `npm install nativescript --g`? 
If this those not resolve the issue, please downgrade to npm version 3.10.10 and check if the problem still persists.

Let me know, whether some of the above-given suggestions help.

**Comment by Eddie541** [comment]
Thanks Nikolay,
I had tried cache clear without success but downgrading to 3.10.10 has allowed a successful install.
All good
Thanks again.
E

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-cli#3160
