### ISSUE TITLE
import short xml code to new page xml

### ISSUE THREAD

**Issue by Hesamp** [NativeScript/NativeScript#4953]
HI 
i need to repeat a short xml code in app 
But I do not want to repeat the code every time
I want to create a sample.xml file once, 
I just need to be read every time I need that part.
Like importing in css language

**Comment by tsonevn** [comment]
Hi @Hesamp,
In this scenario, you could use the Repeater component or a ListView, depending on your project specifics. You could find an example about the repeater [here ](https://docs.nativescript.org/cookbook/ui/repeater) and about ListView [here](https://docs.nativescript.org/cookbook/ui/list-view).

For any further questions use the NativeScript forum [here](https://discourse.nativescript.org/).
