### ISSUE TITLE
Lack of fields in package.json of tns core module - utils

### ISSUE THREAD

**Issue by bigradish** [NativeScript/NativeScript#4956]
The  package.json of the "utils" tns core module is as follows:

{
	"nativescript": {}
}

When importing or requiring the utils module, it fails, for the package.json lacks name, main, types fields.
I've not checked all other modules, and don't know if other modules also have this issue. Please check thoroughly. Thank you.

More info:

- CLI: 3.2.1
- Cross-platform modules: 3.2.0
- Runtime(s): 3.2.0
- Plugin(s): no plugin used

**Comment by tsonevn** [comment]
Hi @bigradish,

Could you provide some more info about the issue and the way, which you create your project?
I tested the creation of a project with our default templates while using the commands as follow
`tns create testProject1` ->NativeScirpt JavaScript project
`tns create testProject2 --tsc` ->NativeScript TypeScript project
`tns create testProject3 --ng` -> NativeScript Angular project
, however, was unable to recreate an issue which affects the project package.json file.

**Comment by tsonevn** [comment]
Hi @bigradish,
Thank you for reporting this,
We verified this case and indeed inside the utils module the package.json do not contain info about the name main and types. However, this is something expected and the reason for this limited info is that the utils folder contains several modules such as `utils` `debug` `lazy` and we could not provide singe name for all.

Regarding the problem, we were unable to recreate an issue with the import or require for the utils. 
```
import { openUrl } from "tns-core-modules/utils/utils"
```
Could you provide some more info about the problem and the way you import it?

**Comment by bigradish** [comment]
Hi @tsonevn ,
Thank you for your kind reply.
I use
`import * as utils from "utils";`
Yes, as you say, the folder contains other modules, and `import * as utils from "utils/utils";` should be used.
I think maybe you can consider to merge the 3 modules into one or use the structure like "ui" folder to put each module into its own sub folder. But this may break many existing code.
One other thing: there is a utils module in the "ui" folder, which only has utils.ios.js file and has no utils.android.js file. Maybe you can add an empty utils.android.js file, and move the utils module in the ui folder to the utils folder.
Thank you very much.

**Comment by vakrilov** [comment]
@bigradish About the different modules inside "utils" - you are correct. It contains a bunch of different modules and you cannot use `import * as utils from "utils";` to get them all at once. It is usually not needed though (you usually just need `utils/utils`) and introducing breaking changes does not seem reasonable tradeoff.

About the `utils.android.js` - you are correct. In fact this seems a good way to start in case you want to get involved in the project. You can check out our [contribution guide](https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md) to see how to do that.

**Comment by surdu** [comment]
@vakrilov So.... just add an empty `utils.android.js` inside `ui` folder? Because moving `utils.*.ts` from `ui` to `utils` sounds like a braking change also.

**Comment by NathanWalker** [comment]
n/a
