### ISSUE TITLE
ScreenMetrics Properties Clarification

### ISSUE THREAD

**Issue by paranoid-android** [NativeScript/NativeScript#496]
I have been reviewing the [platform.ScreenMetrics](http://docs.nativescript.org/apireference/platform/screenmetrics.html) properties. With iOS 9 and Android supporting multiple windows, can someone please clarify what the width, height, and scale properties reflect? Are these values the width, height, and scale of the app's window? Or are these values the width, height, and scale of the screen?

Thanks!

**Comment by enchev** [comment]
All screen metrics properties are in device independent pixels.
