### ISSUE TITLE
Android: ListView Adapter wrongly implements stable ids

### ISSUE THREAD

**Issue by Buuhuu** [NativeScript/NativeScript#4962]
The Adapter implementation on top of `BaseAdapter` of the ListView wrongly implements the stable ids, it supposes to provide from its data source.

According to [BaseAdapter#hasStableIds()](https://developer.android.com/reference/android/widget/BaseAdapter.html#hasStableIds()) with hasStableIds() returning true "the same id always refers to the same object".  In the implementation of [list-view.android.ts](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/list-view/list-view.android.ts#L226) the id used is the index of the item in the array.

That means changing the underlaying data, by reordering, filtering or entirely reloading will break the named above contract.

For us that causes [app crashes because the cached views of the adapter are out of sync](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/list-view/list-view.android.ts#L262) with realizedItems and realizedTemplates. But it can also cause behaviour that is similar to "the list view doesn't properly update". Unfortunately it is hard to reproduce.

I want to propose an enhancement to the android list-view implementation that allows to delegate calculating the id from the item itself to the listview's container/consumer (similar to the templateSelector), with a default implementation being compatible to the current version.

This applies to 3.1, and from what I can see in the code, to 3.2 as well.

**Comment by tsonevn** [comment]
Hi @Buuhuu,
Thank you for contacting us.
I think that this topic has been already discussed [here ](https://github.com/NativeScript/NativeScript/issues/4724) in this issue. Regarding that, we have logged new feature request #4729  for exposing a function that gets a unique ID for the items on ListView.

**Comment by Buuhuu** [comment]
Well spotted. I did not found that - thanks. I'm going to provide a proposal for that as we have to fix that against 3.1 in our project.
