### ISSUE TITLE
Setting CSS background-image property to none

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/NativeScript#4965]
This is in latest NS 3.2.

When I set the CSS background-image property to 'none' - get the following error:

`Error in downloadBitmap - java.net.MalformedURLException: Protocol not found: none`

It looks like it's trying to download a file named 'none' instead of ignoring it.

I need this functionality because I'm using SASS and sometimes the value of the property is a valid url/file and sometimes it's none.

**Comment by erjdriver** [comment]
Setting property value to **null** does the trick.

Again under SASS.

**Comment by liuchuancong** [comment]
JS: Error in downloadBitmap - java.net.MalformedURLException: no protocol: url(https://cdn.pixabay.com/photo/2018/01/12/10/19/fantasy-3077928_960_720.jpg)

in my code 
<StackLayout class="boday-bg-image" [ngStyle]="{'backgroundImage': ahImage}" orientation="vertical">
imageAlUrl = "https://cdn.pixabay.com/photo/2018/01/12/10/19/fantasy-3077928_960_720.jpg";
ngOnInit() {
        this.ahImage = `url(${this.imageAlUrl})`;
}
when i use Ngstyle it throw this err
somebody said add http:// but i do

**Comment by liuchuancong** [comment]
@erjdriver
