### ISSUE TITLE
PropertyChangeEvent doesn't work for the Switch component.

### ISSUE THREAD

**Issue by Abdumama** [NativeScript/NativeScript#4970]
### Tell us about the problem
I'm using Nativescript with Typescript and I noticed that the event **propertyChange** doesn't work with the **Switch** component

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.2.1

### Please tell us how to recreate the issue in as much detail as possible.

**main.xml**

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <StackLayout>
    <Switch propertyChange="onCheckChange"/>
  </StackLayout>
</Page>

```

**main.ts**:

```
export function onCheckChange(args: PropertyChangeData) {
    console.log("I'm in!");
}
```

When I click on the switch component the method **onCheckChange** doesn't write nothing in the console..

**Comment by NickIliev** [comment]
@Abdumama you can not use propertyChange via XML and in NativeScript 3.x.x the `change` event is named by concatenating the property name + the word `Change`. For example, for Switch to observe the `checked` property you will need the `checkedChange` event handler. This was a breaking change introduced in NativeScript 3.x.x - more detailed info can be found [here](https://github.com/NativeScript/NativeScript/blob/master/Modules30Changes.md#events-raised-when-property-value-change)


TypeScript example
```
export function onSwitchLoaded(args) {
    let sw = <Switch>args.object;
    sw.on("checkedChange", (args) => {
        console.log("checkedChange");
        console.log(sw.checked);
    })
}
```
And in the XML file
```
<Switch checked="true" loaded="onSwitchLoaded"/>
```

Full demonstration of the above technique can be found [here](https://github.com/NickIliev/NS-Issues/tree/master/NativeScript/issue_4970)
