### ISSUE TITLE
Archive IOS tester app version

### ISSUE THREAD

**Issue by mobilemindtec** [NativeScript/NativeScript#4971]
Hi,

I'm trying archive a IOS app to my tester using Xcode, but this error is returned:

```
Diff: /Podfile.lock: No such file or directory
Diff: /Manifest.lock: No such file or directory
The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

I can archive my app using `tns` command? Or else, how fix this error? I found other issues with this question but all, apparently, without solution.

Thanks!

**Comment by NickIliev** [comment]
@mobilemindtec Can you try the solutions provided [here](https://github.com/NativeScript/NativeScript/issues/3410)

**Comment by mobilemindtec** [comment]
Hi @NickIliev,

Work now.. I did test yesterday using this issue and not work, but now its working. Thanks!
