### ISSUE TITLE
how to use platform custom view in nativescript

### ISSUE THREAD

**Issue by zhyilong** [NativeScript/NativeScript#4972]
# **1.I really want to be able to provide a demo that uses a custom control on the platform；
**2.I want to know how to use iOS push, without third party push (for example: google-firebase)；**

thanks!**

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there.

**Comment by tsonevn** [comment]
Hi @zhyilong,
Thank you for your interest in NativeScript.
Regarding your first question, If I understand you correctly, You would like to separate the UI views by platform. If this is the case, you could review the article [here](https://developer.telerik.com/products/nativescript/platform-specific-development-nativescript/), where this approach is described.  
In case you need to firebase push-notification functionality, you could use [nativescript-plugin-firebase,](https://github.com/EddyVerbruggen/nativescript-plugin-firebase) which provides a common abstraction for the firebase Native APIs and its functionality. 

For further questions, please use NativeScirpt [forum](https://discourse.nativescript.org/) or [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript).

**Comment by zhyilong** [comment]
hi，how can I create a bottom tabview?

发自我的 iPhone

**Comment by tsonevn** [comment]
Hi @zhyilong,
Setting up the bottom TabView in Android is not supported. In your case, you could use SegmentedBar, where you could set up the position of the tabs. For more info, you could review [this ](https://www.telerik.com/forums/bottom-menu-bar-for-android-and-ios#0WNrf7L290WgTrvO8WXZcg) thread.

For further questions please use our NativeScript [forum](https://discourse.nativescript.org/).

**Comment by zhyilong** [comment]
hi，can support ES6 ? Thank you 

发自我的 iPhone
