### ISSUE TITLE
Getting Index of RadListView

### ISSUE THREAD

**Issue by markomiljkovic** [NativeScript/NativeScript#4973]
## Please, provide the details below:
Ok, sorry for bothering but I have a samll problem...
 I have a  RadListView and I want to show index of element in my xml
Here is a piece of code, so how can I do this

NOTE:  Im using vanilla JS not angular 

 <lv:RadListView>
<lv:RadListView.itemTemplate>
Label text="Index of element" />
</<lv:RadListView.itemTemplate>
 </lv:RadListView>

### Which platform(s) does your issue occur on?
Android

**Comment by NickIliev** [comment]
@markomiljkovic You can use binding and set the index of the item while using the index from your source array.

Or you can use [`itemLoading` event](http://docs.telerik.com/devtools/nativescript-ui/api/classes/radlistview.html#itemloadingevent), get the current index via [`args.index` ](http://docs.telerik.com/devtools/nativescript-ui/api/classes/listvieweventdata.html#index)and again show it in your UI using binding.

Note that this repository is for logging issue, bugs, and features related to NativeScript modules.
For how-to related question regarding nativescript-pr-ui use either the nativescript-ui-feedback repository or one of the community channels like discourse.nativescript.org or SO.
