### ISSUE TITLE
Binding visiblity in XML

### ISSUE THREAD

**Issue by markomiljkovic** [NativeScript/NativeScript#4974]
### Tell us about the problem
Hello guys I have a newbiew question Im trying to created button like accordian,
when clicking on it is should toggle visibility of the content bellow
Here is my Code:
```
Button text=“click” tap=“openAccordian”>
StackLayout visibility="{{ toggle ? ‘visible’ : ‘collapse’ }}">
/StackLayout>

var toggle = true;
exports.openAccordian = function(){
console.log(“Opening accordian”);
var tr = pageData.get(‘toggle’);
pageData.set(‘toggle’,!tr);
}
```
But seems like the expression in StackLayout is not working at all ???
NOTE:
I want to do this in plain Javascript Im not using Angular
### Which platform(s) does your issue occur on?
iOS/Android/Both

```
### Please provide the following version numbers that your issue occurs with:
- CLI: 3.2.1
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json`
"dependencies": {
    "moment": "^2.19.1",
    "nativescript-drop-down": "^3.1.3",
    "nativescript-pro-ui": "^3.1.4",
    "nativescript-theme-core": "~1.0.4",
    "tns-core-modules": "3.2.0"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.5.1",
    "typescript": "^2.5.3"
  }
```

**Comment by NickIliev** [comment]
@markomiljkovic thank you for your interest in NativeScript.
please notice that this repository is for logging issues, bugs, and feature requests.
For how-to related questions, please use the community support channels like discourse.nativescript.org or SO.

Regarding your question:
I have created [this test project](https://github.com/NickIliev/NS-Issues/tree/master/NativeScript/issue_4974) demonstrating toggling the visibility for StackLayout.
However, keep in mind that you might need to provide a `toggle` property for your item model if you are trying to change the visibility of an item inside a ListView or RadListView. If this is the case see [this comment ](https://github.com/NativeScript/NativeScript/issues/4469#issuecomment-334079192)for instructions on how to handle it.

**Comment by markomiljkovic** [comment]
Hi thankx for replying in sucha short time,
I downloaded your sources but it is not working can you test again your example???

**Comment by NickIliev** [comment]
@markomiljkovic let me know on what platform (iOS or Android) and on what device you are testing?

**Comment by markomiljkovic** [comment]
Im testing on Linux mint Debian , platform is Android

**Comment by markomiljkovic** [comment]
tns version 3.2.1

**Comment by NickIliev** [comment]
@markomiljkovic yes the test applicaiton works on m side on both iOS and Android (tested on API19, API23 and API26) - here is a [demonstration video ](https://drive.google.com/open?id=0B05aPIW_j-XFUzhTU2xLYXJmWE0)

**Comment by neddinn** [comment]
I'm having a similar issue. I upgraded my tns-core-modules to latest (3.2.0), tns-ios , and also switched from nativescript-teleric-ui to nativescript-pro-ui, and now I noticed that the condition in a ternary operator isn't  updating the UI after it changes. E.g I have 
   ```<Label text="{{condition ? 'Yes': 'No'}}" textWrap="true"></Label>```  &
```<Label text="{{condition}}" textWrap="true"></Label>```
When the condition becomes true, the second label text shows `true`, but the first label still shows `No`

**Comment by NickIliev** [comment]
@neddinn please if possible provide a full demo project demonstrating the issue

**Comment by neddinn** [comment]
I figured out the problem. This happens when using `observableModule.fromObject` or passing an object to the observable constructor.

**Comment by NickIliev** [comment]
@neddinn keep in mind that passing an object to the observable constructor is no longer supported in NativeScript 3.x.x. use `forObject` or `fromObjectRecursive` to create an Observable from object.

**Comment by markomiljkovic** [comment]
Yes seems that was the problem with, thanx guys
awesome support here :)
