### ISSUE TITLE
webpack error 

### ISSUE THREAD

**Issue by behi1ty** [NativeScript/NativeScript#4975]
ERROR in Error encountered resolving symbol values statically. Could not resolve tns-core-modules/ui/frame relative to D:/Project/node_modules/nativescript-angular/router.d.ts., resolving symbol NativeScriptRouterModule in D:/Project/node_modules/nativescript-angular/router.d.ts, resolving symbol NativeScriptRouterModule in D:/Proje
ct/node_modules/nativescript-angular/router.d.ts

"dependencies": {
    "@angular/animations": "~4.2.0",
    "@angular/common": "~4.2.0",
    "@angular/compiler": "~4.2.0",
    "@angular/core": "~4.2.0",
    "@angular/forms": "~4.2.0",
    "@angular/http": "~4.2.0",
    "@angular/platform-browser": "~4.2.0",
    "@angular/router": "~4.2.0",
    "class-validator": "^0.7.2",
    "nativescript-angular": "~4.2.0",
    "nativescript-bcryptjs": "^1.0.1",
    "nativescript-camera": "^3.1.2",
    "nativescript-cardview": "^2.0.3",
    "nativescript-drop-down": "^3.1.3",
    "nativescript-fancyalert": "^1.1.2",
    "nativescript-imagepicker": "^3.0.7",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-onesignal": "^1.0.7",
    "nativescript-permissions": "^1.2.3",
    "nativescript-phone": "^1.3.1",
    "nativescript-pulltorefresh": "^2.0.2",
    "nativescript-telerik-ui": "^3.1.4",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.2",
    "tns-core-modules": "^3.2.0",
    "tns-platform-declarations": "^3.2.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.2.0",
    "@ngtools/webpack": "~1.6.0",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "^0.5.1",
    "nativescript-dev-webpack": "^0.8.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "typescript": "^2.5.3",
    "webpack": "~3.2.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install"
  }

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-dev-webpack#300
