### ISSUE TITLE
Icons are not showing correctly in Android ActionBar

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#498]
If I set an icon for an actionBarItem it'll appear (with a keen eye) very tiny (approx 2px x 2px).

```xml
<Page.actionBar>
    <ActionBar title="Title">
      <ActionBar.actionItems>
        <ActionItem tap="rightTap" icon="~/res/ic_search_white.png" ios.position="right" android.position="left"/>
        <ActionItem text="pop" ios.position="right" android.position="popup"/>
      </ActionBar.actionItems>
    </ActionBar>
</Page.actionBar>
```

However, the same icon will appear in iOS just fine:

![screen shot 2015-07-28 at 2 18 10 pm](https://cloud.githubusercontent.com/assets/5018471/8922150/80f14558-3533-11e5-872b-2e4b2816b0bd.png)

**Comment by vakrilov** [comment]
Images are rendered according to their size in physical pixels and may appear very small on devices with high DPI. 
The best approach would be to have the images as resources in `App_Resources/Android/drawable-XXX` folders for Android. 
Note, if you don't want to change the icon in iOS you can use different icons for both platforms:
```
<ActionItem tap="rightTap" 
    ios:icon="~/res/ic_search_white.png" 
    android:icon="res://ic_search_white" 
    ios.position="right" android.position="left"/>
```

**Comment by lscown** [comment]
Ah, great - thanks :-)

**Comment by ddimitrov899** [comment]
Use the NavigationButton as a side-drawer button in Android because ActionItems are shown on the right side of the ActionBar

`<NavigationButton ios:visibility="collapsed"  android:icon="res://ic_search_white"  ></NavigationButton>`

**Comment by ibnYusrat** [comment]
> Use the NavigationButton as a side-drawer button in Android because ActionItems are shown on the right side of the ActionBar
> 
> `<NavigationButton ios:visibility="collapsed" android:icon="res://ic_search_white" ></NavigationButton>`

I think font icon cannot be used in NavigationButton
