### ISSUE TITLE
TextField focus is not showing numeric keyboard

### ISSUE THREAD

**Issue by brunaaanayara** [NativeScript/NativeScript#4984]
```
let focusTextField: TextField = <TextField>this.page.getViewById("test");
if (focusTextField) {
    focusTextField.focus();
}
```
When I try to use that my textfield get focus but the numeric keyboard is not showing. I need to tap on textfield and after that the numeric keyboard appears.

I need the numeric keyboard appear when the textfield get focus and not only when I tap on textfield.
What can I do to solve that?

**Comment by tsonevn** [comment]
HI @brunaaanayara,
I tested the described scenario on my side, however, was unable to recreate an issue with the keyboard type and TextField. For your convenience, I am attaching GIF file from the simulators and sample project. Please review it and make the needed changes, which will allow us to recreate the problem. 
![screencast 2017-10-26 at 10 15 52 am](https://user-images.githubusercontent.com/17448734/32040021-fe535780-ba37-11e7-9583-a27fe7917ff8.gif)
![screencast 2017-10-26 at 10 19 13 am](https://user-images.githubusercontent.com/17448734/32040022-fe6f05fc-ba37-11e7-937a-86f315d31e4c.gif)
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1417330/Archive.zip)

Also, it would help if you could provide some more info about your environment(CLI modules node versions).

**Comment by brunaaanayara** [comment]
I was able to recreate the same issue in this project
[keyboardTest.zip](https://github.com/NativeScript/NativeScript/files/1418051/keyboardTest.zip)

**Comment by NickIliev** [comment]
@brunaaanayara This is a timing issue as the modal page is not fully initialized when calling the focus method. To resolve the issue we can wrap the focus in a minor `setTimeout`

```
let focusTextField: TextField = <TextField>this.page.getViewById("test");
if (focusTextField) {
    setTimeout(function() {
        focusTextField.focus();
    }, 100);
}
```
