### ISSUE TITLE
tns 3.2.0 ios publish error on Xcode

### ISSUE THREAD

**Issue by harriscreativity** [NativeScript/NativeScript#4989]
(null): Linker command failed with exit code 1 (use -v to see invocation)

**Comment by harriscreativity** [comment]
Ld /Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/IntermediateBuildFilesPath/yellowcoza.build/Release-iphoneos/yellowcoza.build/Objects-normal/arm64/yellowcoza normal arm64
    cd "/Users/dotcomholding/Desktop/Mobile Apps/NATIVESCRIPT/YELLOW.CO.ZA/yellow.co.za/platforms/ios"
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk -L/Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos -F/Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos -F/Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos/FLAnimatedImage -F/Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos/GTMSessionFetcher -F/Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos/GoogleToolboxForMac -F/Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos/MBProgressHUD -F/Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos/NYTPhotoViewer -F/Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos/SCLAlertView-Objective-C -F/Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos/leveldb-library -F/Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos/nanopb -F/Users/dotcomholding/Desktop/Mobile\ Apps/NATIVESCRIPT/YELLOW.CO.ZA/yellow.co.za/platforms/ios/Pods/FirebaseAnalytics/Frameworks -F/Users/dotcomholding/Desktop/Mobile\ Apps/NATIVESCRIPT/YELLOW.CO.ZA/yellow.co.za/platforms/ios/Pods/FirebaseAuth/Frameworks -F/Users/dotcomholding/Desktop/Mobile\ Apps/NATIVESCRIPT/YELLOW.CO.ZA/yellow.co.za/platforms/ios/Pods/FirebaseCore/Frameworks -F/Users/dotcomholding/Desktop/Mobile\ Apps/NATIVESCRIPT/YELLOW.CO.ZA/yellow.co.za/platforms/ios/Pods/FirebaseDatabase/Frameworks -F/Users/dotcomholding/Desktop/Mobile\ Apps/NATIVESCRIPT/YELLOW.CO.ZA/yellow.co.za/platforms/ios/Pods/FirebaseInstanceID/Frameworks -F/Users/dotcomholding/Desktop/Mobile\ Apps/NATIVESCRIPT/YELLOW.CO.ZA/yellow.co.za/platforms/ios/Pods/FirebaseStorage/Frameworks -F/Users/dotcomholding/Desktop/Mobile\ Apps/NATIVESCRIPT/YELLOW.CO.ZA/yellow.co.za/platforms/ios/internal -F/Users/dotcomholding/Desktop/Mobile\ Apps/NATIVESCRIPT/YELLOW.CO.ZA/yellow.co.za/platforms/ios/../../node_modules/nativescript-telerik-ui/platforms/ios -F/Users/dotcomholding/Desktop/Mobile\ Apps/NATIVESCRIPT/YELLOW.CO.ZA/yellow.co.za/platforms/ios/../../node_modules/nativescript-pro-ui/platforms/ios -F/Users/dotcomholding/Desktop/Mobile\ Apps/NATIVESCRIPT/YELLOW.CO.ZA/yellow.co.za/platforms/ios/../../node_modules/tns-core-modules-widgets/platforms/ios -filelist /Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/IntermediateBuildFilesPath/yellowcoza.build/Release-iphoneos/yellowcoza.build/Objects-normal/arm64/yellowcoza.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/IntermediateBuildFilesPath/yellowcoza.build/Release-iphoneos/yellowcoza.build/Objects-normal/arm64/yellowcoza_lto.o -fobjc-arc -fobjc-link-runtime -ObjC -lc++ -licucore -lsqlite3 -lz -framework CFNetwork -framework FLAnimatedImage -framework FirebaseAnalytics -framework FirebaseAuth -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseDatabase -framework FirebaseInstanceID -framework FirebaseNanoPB -framework FirebaseStorage -framework GTMSessionFetcher -framework GoogleToolboxForMac -framework MBProgressHUD -framework MobileCoreServices -framework NYTPhotoViewer -framework SCLAlertView_Objective_C -framework Security -framework StoreKit -framework SystemConfiguration -framework leveldb -framework nanopb -ObjC -sectcreate __DATA __TNSMetadata /Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos/metadata-arm64.bin -framework NativeScript -F/Users/dotcomholding/Desktop/Mobile\ Apps/NATIVESCRIPT/YELLOW.CO.ZA/yellow.co.za/platforms/ios/internal -licucore -lz -lc++ -framework Foundation -framework UIKit -framework CoreGraphics -framework MobileCoreServices -framework Security -framework TelerikUI -framework TelerikAppFeedback -framework TelerikUI -framework TNSWidgets -framework Pods_yellowcoza -Xlinker -dependency_info -Xlinker /Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/IntermediateBuildFilesPath/yellowcoza.build/Release-iphoneos/yellowcoza.build/Objects-normal/arm64/yellowcoza_dependency_info.dat -o /Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/IntermediateBuildFilesPath/yellowcoza.build/Release-iphoneos/yellowcoza.build/Objects-normal/arm64/yellowcoza

ld: warning: directory not found for option '-F/Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos/FLAnimatedImage'
ld: warning: directory not found for option '-F/Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos/GTMSessionFetcher'
ld: warning: directory not found for option '-F/Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos/GoogleToolboxForMac'
ld: warning: directory not found for option '-F/Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos/MBProgressHUD'
ld: warning: directory not found for option '-F/Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos/NYTPhotoViewer'
ld: warning: directory not found for option '-F/Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos/SCLAlertView-Objective-C'
ld: warning: directory not found for option '-F/Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos/leveldb-library'
ld: warning: directory not found for option '-F/Users/dotcomholding/Library/Developer/Xcode/DerivedData/yellowcoza-dnqugmvlycvbrqgixmbmwstwpgpy/Build/Intermediates/ArchiveIntermediates/yellowcoza/BuildProductsPath/Release-iphoneos/nanopb'
ld: framework not found FLAnimatedImage
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3181
