### ISSUE TITLE
Ability to style the ActionBar 

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#499]
I've noticed that there isn't a way to style the Navigation/Action bar through the new implementation. Is there a work around?

Would be great if you could apply a background-color, color etc to the ActionBar and it's items.

**Comment by vakrilov** [comment]
List of suggested properties:
- [ ] `color`
- [ ] `background-color`
- [ ] `font-size`
- [ ] `font-family`

**Comment by manijak** [comment]
Would be great if the font-family applies to both Title and the Buttons in the actionBar. 

I tried overriding font-family via code for iOS, but it only changed it for title, and not the buttons, any way around this?

**Comment by lscown** [comment]
It would be great be able to change the height of the actionBar as well, so you have the option of putting a second tier of text. 

Another great thing to be able to do is alter the opacity.

**Comment by bradmartin** [comment]
+1 any update on this?

**Comment by hshristov** [comment]
Hi guys,

this item didn't make it for 1.4.0 but we will raise its priority for the next release.

**Comment by vchimev** [comment]
From https://github.com/NativeScript/NativeScript/issues/767 - the following styling options will be released in {N} 1.5:

**ActionBar**
* `color` (CSS) - the title font color.
* `background-color` (CSS) - background color of the ActionBar/NavigationBar.

**Comment by MarkPerryBV** [comment]
Any chance we can get a logo into the action bar please?

**Comment by lhitc** [comment]
@MarkPerryBV You can for example set an icon on the left side ("navigation button"):
```javascript
	page.actionBar.navigationButton = new actionBarModule.NavigationButton();
	page.actionBar.navigationButton.icon = "res://your_icon";
```
or you can add an ActionItem with an icon attribute/properte if you need the icon on a different place

Works at least on Android.

I didn't try the possibilities of ActionBar.titleView as described here:
https://docs.nativescript.org/ApiReference/ui/action-bar/HOW-TO#setting-custom-title-view
but this may also provide what you want to achieve.

**Comment by MarkPerryBV** [comment]
@lhitc We are already using the `page.actionBar.navigationButton.icon` to host a burger menu icon to open the SideMenu from Telerik. Ideally I would like to also add our App Logo into the heading.

**Comment by lhitc** [comment]
@MarkPerryBV Just played around with it, consider this:

```xml
  <Page.actionBar>
    <ActionBar>
      <ActionBar.titleView>
        <StackLayout orientation="horizontal">
          <Label text="AppName" />
          <Image src="res://app_icon" />
        </StackLayout>
      </ActionBar.titleView>
    </ActionBar>
  </Page.actionBar>
```

**Comment by manijak** [comment]
Any updated on this?!  Still not able to change font-family on ActionBar & items ?

**Comment by vakrilov** [comment]
It will probably won't get into the 1.6 milestone - it got pushed down by other issues.

**Comment by lecungdinh1702** [comment]
I just found a way to change the color of the navigation button programmatically in Android. It's been a headache problem for me because the customers would like to customize their own color for some UI components. I have tried using back arrow in FontAwesome so that I can change its color programmatically but it doesn't work. However this way might be helpful if you need to change navigation button's color.

In the xml: 
```html
<ActionBar title="{{ title }}" android.iconVisibility="never">
      <NavigationButton  android.systemIcon="ic_menu_back" text="Back" tap="navTap"/>
 </ActionBar>
```
In the script:
```js
var page: Page = <any>args.object;
page.actionBar._toolbar.getNavigationIcon().setColorFilter(android.graphics.Color.parseColor("#ed5d40"), android.graphics.PorterDuff.Mode.SRC_ATOP);
```
Hope this could help. Still waiting for the font support for ActionBar and items.

**Comment by vakrilov** [comment]
Some progress here.
It turned out that it is very hard to customize the default look of the action items once they are created in Android. However, with PR #1554 (thanks @PeterStaev) we will have the ability to set custom views inside ActionItems, so that you can style them in any - including setting font properties.
I'm closing this issue for now.

**Comment by bhavincb** [comment]
hii @vakrilov ,
css color and backkground clolor doesn't apply on NavigationButton.
here is playground link [https://play.nativescript.org/?template=play-ng&id=FpaWzb&v=26](url)
i had checked on Android.

**Comment by vakrilov** [comment]
Hey @bhavincb 
This issue is quite old and has to much legacy. Do you mind opening a separate issue on styling the navigation button?
