### ISSUE TITLE
Span not setting color correctly (iOS)

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/NativeScript#4992]
I create a FormattingString and push a Span object into it.

For the Span object, I set the "color" and "text" property.

And I then assign it to a Label object.

This Label object also has a CSS class set which sets the "color" property also.

The bug is that the "color" property that I set int the Span - does NOT override the value set in CSS class.

It works correctly in the Android version - but not in the iOS version.

```
var formattedString = new fmtStrModule.FormattedString();

var span : spanModule.Span = new spanModule.Span();
span.text ="test";
span.color = new colorModule.Color("red");
formattedString.spans.push(span);

label.formattedText = formattedString;
```

label object is set to a CSS class that sets it's color property.

In the iOS version - I get the color of the CSS class.

I think the proper color should be the one that's set in the Span object.

**Comment by tsonevn** [comment]
Hi @erjdriver,
Thank you for reporting this issue,
Indeed this is a real problem for iOS. For your convenience, I am attaching sample project, which could be used for debugging.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1421049/Archive.zip)
![screen shot 2017-10-27 at 9 58 29 am](https://user-images.githubusercontent.com/17448734/32091695-ebf5e1e0-bafd-11e7-9b63-77c3b5cff3ef.png)

**Comment by erjdriver** [comment]
Thank you.

This happened with 3.3 release.

**Comment by StevenLJackson1** [comment]
I'm seeing a similar issue in Android with {N} version 3.3.0 and Android platform version "3.4.0-2017-10-31-1" using TypeScript and Angular.  Would that be the same issue as reported here, or should I open a different issue?

**Comment by tsonevn** [comment]
Hi @StevenLJackson1,
In case you reproduce the exact same issue, you could leave your comment here on this issue. 
Also, it would help if you provide sample code, which could be used for reproducing the issue.

Thank you in advance for your cooperation.

**Comment by erjdriver** [comment]
Is there a solution for this at this time??

Maybe tns-core-modules@next or do I have to wait for the next release.

Thanks for the correct format for `FormattedString` in xml - but I'm more interested in the `FormattedString` in code.

**Comment by erjdriver** [comment]
Any solution to this - where the Formatted text in code doesn't work (ios).

Thanks.

**Comment by erjdriver** [comment]
When will this bug be fixed!

I got a workaround from issue #7081 - but it's a slow workaround.

I've got a page with a lot of formatted text labels and it increases the rendering time quite a bit.

This was tagged as a bug Oct 2017 - and still not fixed.

**Comment by erjdriver** [comment]
Looks like this is fixed on both ios.
