### ISSUE TITLE
ScrollView base: Adding listener when you are supposed to remove it

### ISSUE THREAD

**Issue by alg** [NativeScript/NativeScript#4993]
Have a look here:

https://github.com/NativeScript/NativeScript/blob/b192abf4f2f9fd92c68988d07f9621be8fa980b7/tns-core-modules/ui/scroll-view/scroll-view-common.ts#L23-L24

Is it really correct that you add listener when you are supposed to remove it?

**Comment by NickIliev** [comment]
@alg Nice catch! The issue will be resolved via [this PR](https://github.com/NativeScript/NativeScript/pull/4994)
