### ISSUE TITLE
Observable Array with ListView delete all itens just erase few itens

### ISSUE THREAD

**Issue by evnds** [NativeScript/NativeScript#4995]
I'm build a app that create a listview, and to do it i use Observable Array. I'm basic desenvelop, and don't know exaclty what's is the issue, but Observable Array appear work on async mode;

## Minimal code to reproduce it:
file: main.js

```
// Include Observable Array
var ConstObsArray = require("data/observable-array");
// Create an object;
var ObsArray = new ConstObsArray.ObservableArray();

// Exclude few itens
function remove_all_one(){
   var i;
   for(i = 0; i < ObsArray.length; i++) ObsArray.pop();
   alert('Done! All itens are removed.'); // haha don't lie to me
}

// Exclude all itens (not a good solution if async)
function remove_all_two(){
   while(ObsArray.length > 0) ObsArray.pop();
   alert('Done! All itens are removed.'); // great!
}

// 
function onInit(args){
    var p  = args.object;
   p.bindingContext = {myItens: ObsArray};
   // Add some itens
   ObsArray.push({"id":"1","title":"title 1","description":"description 1"});
   ObsArray.push({"id":"2","title":"title 2","description":"description 2"});
   ObsArray.push({"id":"3","title":"title 3","description":"description 3"});
   ObsArray.push({"id":"4","title":"title 4","description":"description 4"});
   ObsArray.push({"id":"5","title":"title 5","description":"description 5"});
   ObsArray.push({"id":"6","title":"title 6","description":"description 6"});
   ObsArray.push({"id":"7","title":"title 7","description":"description 7"});
   ObsArray.push({"id":"8","title":"title 8","description":"description 8"});
   ObsArray.push({"id":"9","title":"title 9","description":"description 9"});
   ObsArray.push({"id":"10","title":"title 10","description":"description 10"});
   ObsArray.push({"id":"11","title":"title 11","description":"description 11"});
   ObsArray.push({"id":"12","title":"title 12","description":"description 12"});
   ObsArray.push({"id":"13","title":"title 13","description":"description 13"});
   ObsArray.push({"id":"14","title":"title 14","description":"description 14"});
   ObsArray.push({"id":"15","title":"title 15","description":"description 15"});
   ObsArray.push({"id":"16","title":"title 16","description":"description 16"});
}

exports.OnBtn1 = remove_all_one;
exports.OnBtn2 = remove_all_two;
exports.OnLoaded =  onInit;
```

file: main.xml
```
<Page loaded="OnLoaded">

	<ActionBar title="Teste" >
	  <ActionItem tap="OnBtn1" text="For" android.position="actionBar" />
	  <ActionItem tap="OnBtn2" text="While" android.position="actionBar" />
   </ActionBar>

   <StackLayout>
		<ListView items="{{ myItens }}">
        <ListView.itemTemplate>
            <StackLayout>
			<Label text="{{ 'ID: ' + id }}" class="text-primary" textWrap="true" />
			<Label text="{{ 'Title: ' + title }}" class="text-primary" textWrap="true" />
			<Label text="{{ 'Description: ' + description }}" class="text-primary" textWrap="true" />
		</StackLayout>
        </ListView.itemTemplate>
		</ListView>
	</StackLayout>
 
</Page>
```
Initial data:
![capture _2017-10-27-10-30-10](https://user-images.githubusercontent.com/18752435/32106822-901c6660-bb0b-11e7-824f-7b2022623243.png)
Erase with For:
![capture _2017-10-27-10-30-19](https://user-images.githubusercontent.com/18752435/32106825-9184701a-bb0b-11e7-9c6d-b16ce9dc6eec.png)
Erase with While:
![capture _2017-10-27-10-30-28](https://user-images.githubusercontent.com/18752435/32106826-91c4fb12-bb0b-11e7-9fce-6f9e90f16803.png)

## Enjoying this topic
How i can search in a ObservableArray using indexOf in a specified column like id?

## Possible solution:
include a function "removeAll" on (https://github.com/NativeScript/NativeScript/blob/5e0de0a8b84d81b52510fd979d920ae8d51956c4/tns-core-modules/data/observable-array/observable-array.ts); ?

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
TNS Version 3! (hahaha 3.2.1)

**Comment by tsonevn** [comment]
Hi @evnds,
Thank you for reporting this issue, 
I tested your case and found that this is something expected while using for loop and checks for the `ObsArray.length` in the scope of the loop.
In every loop's iteration,  you will compare `i` with the new array length, which will lead to removing only the half the elements. 
Something that I would suggest is to use `while` and to execute it while the array is not empty. For Example:
```
while(ObsArray.length){
ObsArray.pop();
}
```
For any further questions, you could use our[ NativeScript forums](https://discourse.nativescript.org/).
