### ISSUE TITLE
console.dir works the same as log 

### ISSUE THREAD

**Issue by Andy-ZYA** [NativeScript/NativeScript#4997]
I am following the [official tutorial](https://docs.nativescript.org/angular/tutorial/ng-chapter-1) and after I change console.log to console.dir, the terminal shows the same thing.

`CONSOLE LOG file:///app/app.component.js:6:20: [object Object]
CONSOLE LOG file:///app/tns_modules/@angular/core/./bundles/core.umd.js:2957:20: Angu`

How should I fix this problem?

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3186
