### ISSUE TITLE
Might be an error on official tutorial Chapter 3

### ISSUE THREAD

**Issue by Andy-ZYA** [NativeScript/NativeScript#4998]
I am following [Chapter 3](https://docs.nativescript.org/angular/tutorial/ng-chapter-3) and I believe that there is a problem with the templateUrl

`import { Component } from "@angular/core";`
`import { User } from "./shared/user/user";`
`@Component({`
`  selector: "my-app",`
`  moduleId: module.id,`
`  templateUrl: "./login.html",`
`  styleUrls: ["./login-common.css", "./login.css"]`
`})`

For me, `templateUrl: "./pages/login/login.html"` works, instead of the one currently on the website.

**Comment by joshuaharrison** [comment]
indeed, most of the urls from this chapter are incorrect

**Comment by NickIliev** [comment]
@Andy-ZYA are you sure you have included `moduleId: module.id,` (this directive is allowing you to use relative paths instead of absolute ones)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/sample-Groceries#278
