### ISSUE TITLE
Detected problems with app native libraries

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [NativeScript/NativeScript#4999]
Hello, strange popup message:

### Tell us about the problem
Detected problems with app native libraries
(please consult log for details)
libavcodec.so: text relocations
etc...

### Which platform(s) does your issue occur on?
Android-X86_64 7.1.2 VM VirtualBox
Android-X86_64 6.0 VM Qemu
Gnu/linux x86_64 host machine
![2017_10_28_14 11 1509189103s_screen](https://user-images.githubusercontent.com/9258443/32133942-c05dda04-bbea-11e7-9f69-f4999c2101d3.png)

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
3.2.1
tns-template-master-detail-kinvey-ng without any changes

there are no any errors in logs.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/template-master-detail-kinvey-ng#44
