### ISSUE TITLE
tns platform add ios doesn't work

### ISSUE THREAD

**Issue by bellu** [NativeScript/NativeScript#5]
I'm trying to add iOS platform to my project, but without success.
I have no problem using the command "tns platform add android" in the terminal, but when i try to add iOS platform, it returns this error:

ENOENT, open '/Users/myuserfolder/.npm/tns-ios/0.9.1/package/package.json'

PS: I'm using a Mac.

**Comment by ligaz** [comment]
It looks like the iOS runtime package (tns-ios) has not been installed correctly (this happens the first time when you issue `tns platform add ios`, the package is quite large and there might have been some connectivity issues). Can you share the output that you get if you `npm install -g tns-ios`?

**Comment by bitcard** [comment]
same issue, sudo chmod 777 /Users/myuserfolder/.npm/tns-ios/0.9.1/package/package.json, it's ok.

**Comment by bellu** [comment]
I've install a new version of Xcode Command Line Tools and this fix my problem.

**Comment by PedroAnibarro1** [comment]
I did have the same problem ENOENT, open '/Users/myuserfolder/.npm/tns-ios/0.9.1/package/package.json'..... I fixed by using npm install -g tns-ios. Now when I try to add the platform of iOS a new message appear. 

ENOENT, rename '/Users/username/Desktop/demo/platforms/ios/__PROJECT_NAME__/__PROJECT_NAME__-Info.plist'

any fix or idea?

**Comment by bitcard** [comment]
It seems access file fail, try sudo chmod 777 filename.

**Comment by PedroAnibarro1** [comment]
it didn't work... I tried to change permission to every file with not success. I don't know what more I can do

**Comment by lexrus** [comment]
Same issue.

**Comment by chrene** [comment]
Got it to work with the following command: 
`tns platform add ios --frameworkPath /usr/local/lib/node_modules/tns-ios`

Seems to be an issue where it can't find the `node_modules`. However don't hang me up on that.

**Comment by rajivnarayana** [comment]
I see a '/Users/myuserfolder/.npm/tns-ios/0.9.1/package.tgz' and that it was unable to extract properly. I backed up existing '/Users/myuserfolder/.npm/tns-ios/0.9.1/package' and extracted '/Users/myuserfolder/.npm/tns-ios/0.9.1/package.tgz' manually. Everything works and runs now.
