### ISSUE TITLE
Free Webinar for NativeScript 1.2

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#500]
Hello everyone,

we are hosting a free webinar on what's new in our latest NativeScript 1.2 release. The webinar will be held on August, 4th. Please register here - https://www.nativescript.org/webinars. If you can't attend sign-in anyway - we will send you the recording later.

**Comment by ligaz** [comment]
Here is the recording of the webinar: https://www.youtube.com/watch?v=binVpBThb0A
