### ISSUE TITLE
form validation

### ISSUE THREAD

**Issue by praven07** [NativeScript/NativeScript#5001]
I'm trying to use the ng form validation. I have attached an gif of the app. if you look at it the ng-untouched changes to ng-touched. As soon as I touch it the first time. But in default angular2 the ng-untouched changes to ng-touched when it has been visited. It changes after it has blurred out. You can see the differences in the screenshoots below.

On nativescript.
![untitled](https://user-images.githubusercontent.com/2223191/32137700-c0e72980-bbea-11e7-9a69-a0a7d9388438.gif)

On Angular2
![untitled 1](https://user-images.githubusercontent.com/2223191/32137741-47c5aaf8-bbeb-11e7-80a7-4f0e5b28a911.gif)

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1063
