### ISSUE TITLE
Error when trying to run the tutorial project on the android virtual device.

### ISSUE THREAD

**Issue by SantiValdez** [NativeScript/NativeScript#5003]
tns version 3.3.0
Windows 10
tns doctor reporting zero problems

I searched similar issues but could not find a solution. Ive tried deleting the project and removing/adding back the android platform but nothing has worked thus far:

```
Searching for devices...
Preparing project...
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared (Android)
Building project...
Gradle build...
         + creating include.gradle for plugin C:\Users\SantiValdez\Desktop\#WEB DEV\Nativescript\test\node_modules\tns-core-modules-widgets
         + applying plugin configuration from C:\Users\SantiValdez\Desktop\#WEB DEV\Nativescript\test\platforms\android\build\configurations\tns-core-modules-widgets\include.gradle
         + applying user-defined configuration from C:\Users\SantiValdez\Desktop\#WEB DEV\Nativescript\test\app\App_Resources\Android\app.gradle
         + adding nativescript runtime package dependency: nativescript-optimized
         + adding aar plugin dependency: C:\Users\SantiValdez\Desktop\#WEB DEV\Nativescript\test\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
Exception in thread "main" java.net.MalformedURLException: no !/ in spec
        at java.net.URL.<init>(URL.java:627)
        at java.net.URL.<init>(URL.java:490)
        at java.net.URL.<init>(URL.java:439)
        at com.ig.GetInterfaceNames.getClassLoader(GetInterfaceNames.java:94)
        at com.ig.GetInterfaceNames.generateInterfaceNames(GetInterfaceNames.java:51)
        at com.ig.GetInterfaceNames.main(GetInterfaceNames.java:35)
Caused by: java.lang.NullPointerException: no !/ in spec
        at sun.net.www.protocol.jar.Handler.parseAbsoluteSpec(Handler.java:171)
        at sun.net.www.protocol.jar.Handler.parseURL(Handler.java:151)
        at java.net.URL.<init>(URL.java:622)
        ... 5 more

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\SantiValdez\Desktop\#WEB DEV\Nativescript\test\platforms\android\build-tools\android-static-binding-generator\build.gradle' line: 67

* What went wrong:
Execution failed for task ':asbg:generateInterfaceNamesList'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_152\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.
```

I have noticed that android studio creates the virtual device files in a different folder than the one the ANDROID_HOME variable points to, I've no idea why but as a bandaid solution I just move the AVD files to the correct folder and it starts up fine.

**Comment by tsonevn** [comment]
Hi @SantiValdez,
Indeed this error could be related to a wrong path for the ANDOIRD_HOME variable, which could lead to an issue with the project build.
If I understand you correctly, you were able to resolve the issue and now the project has been built properly.
Let me know if I could assist you further.
Le mt ho

**Comment by SantiValdez** [comment]
@tsonevn 

Sorry, I made this confusing without noticing. What I was able to fix was the android emulator. Before, it didnt start because when I downloaded an image to emulate it would put the files in a different directory, so I can manually make it work by cutting and pasting the files from "C:/users/<user>/.android/avd" <-- where the avd manager THINKS the filñes should go, to "C:/android/.android/avd" <-- where I actually set the ANDROID_HOME variable.

The build still fails though, I have no clue why it does, but it might be related to what is happening with the emulator. It seems as though some configuration is wrong inside android studio that tells the avd manager (and who knows what else) the wrong directory to do stuff in.

**Comment by tsonevn** [comment]
Hi @SantiValdez;,
Could you give us the exact steps, which you used while building the project. Also, It would help if you could build the project with `tns run android --log trace` and send us the full log from the console, info about your environment(node, npm version) and the package.json file of the project.

Please while opening a new issue, follow the template and provide the requested info. This helps us in the problem investigation.

**Comment by SantiValdez** [comment]
@tsonevn 

Initially I had several issues so I completely removed nativescript and Android Studio + sdk. Then:
*installed Android Studio and set up ANDROID_HOME to "C:/android/.android/" (and did the same to ANDROID_SDK_HOME, just in case),
*installed nativescript with no issues reported by tns doctor.
*downloaded a system image in the AVD manager
*had an error on the emulator start-up saying it couldnt find the files
*found out android studio was putting these files somewhere else, so I copy-pasted them in the right place, which made the emulator start correctly
*run "tns run android" with emulator going, and the build fails with the error that made me start this issue.

**log trace** : https://pastebin.com/7GXFZUV9  (some lines from the beginning of the log are missing, log is so big it exceeds the max size of powershell. You can still see the error near the end though)
**node version**: v6.11.3
**npm version**: 5.5.1
**package.json**: (its the helloworld project from the tutorial)

```
{
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": {
		"id": "org.nativescript.test",
		"tns-android": {
			"version": "3.3.0"
		}
	},
	"dependencies": {
		"nativescript-theme-core": "~1.0.2",
		"tns-core-modules": "~3.3.0"
	},
	"devDependencies": {
		"babel-traverse": "6.4.5",
		"babel-types": "6.4.5",
		"babylon": "6.4.5",
		"lazy": "1.0.11"
	}
}


```

**Comment by Plamen5kov** [comment]
Hi, @SantiValdez moving the .avd fils is not a recommended approach since it's error-prone. Please consider setting up your environment using the NativeScript setup scripts [here](https://docs.nativescript.org/start/quick-setup#windows) and follow the given instructions for setting up the environment.
