### ISSUE TITLE
Font awesome icon not working on Action Items

### ISSUE THREAD

**Issue by markomiljkovic** [NativeScript/NativeScript#5006]
### Tell us about the problem
Im trying to add FontAwesome Icon to Icon Item but it only displays Black Box
```
    <ActionBar class="action-bar" backgroundColor='red'>               
        <Label class="action-bar-title" text="Home"></Label>

           <ActionBar.actionItems>                
                <ActionItem tap="mainpage">
                    <ActionItem.actionView>
                       <Label text="&#xf044;" cssClass="font-awesome-icon" tap="Post" />
                    </ActionItem.actionView>
                </ActionItem> 
                <ActionItem icon="res://menu"
                    tap="onDrawerButtonTap"
                    ios.position="right">
                </ActionItem>               
            </ActionBar.actionItems>    
    </ActionBar>
```

And in CSS I add Class like this
```
.font-awesome-icon {
    font-family: FontAwesome, fontawesome-webfont;
}
```

### Which platform(s) does your issue occur on?
Android

**Comment by markomiljkovic** [comment]
ok I managed to display Icon but then the ripple effect is lost when tapping on Icon.

**Comment by NickIliev** [comment]
@markomiljkovic losing the ripple effect is expected when any kind of custom styling is applied (in native Andriod the ripple effect is applied via background drawable). So if you want to have both custom styling and ripple effect you should implement it manually (e.g.using [nativescript-ripple](https://github.com/bradmartin/nativescript-ripple))

**Comment by TheOnlyMatt** [comment]
How did you do to get this working on Action Items ?
I always got a question mark

```
<ActionItem (tap)="addToCalendar()"
                 ios.position="right"
                class="fa-icon"
                style="font-family: FontAwesome;"
                ios:text="&#xf230;">
</ActionItem>
```
In app.css :
`.fa-icon{font-family:'FontAwesome', fontawesome-webfont}`
I have fontawesome-webfont.eot/ttf and FontAwesome.ttf/otf in my fonts folder

**Comment by markomiljkovic** [comment]
I defined in app.css 
like this 
.fa{
    font-family: FontAwesome, fontawesome-webfont;
}
also in app I created folder fonts and put in there 
fontawesome-webfont.ttf
fontawesome-webfont.woff
files

**Comment by TheOnlyMatt** [comment]
Looks like I have the same thing there ... I have the class defined in app.css, and the fonts in the app/fonts folder

**Comment by markomiljkovic** [comment]
You can share here github link to your project, so we can see.
