### ISSUE TITLE
Error: Response not found for requestId = 0 happen in version 3.3

### ISSUE THREAD

**Issue by yclau** [NativeScript/NativeScript#5009]
## Please, provide the details below:
After update new version 3.3, my project http show out error :
System.err: com.tns.NativeScriptException: 
System.err: Calling js method onComplete failed
System.err: Error: Response not found for requestId = 0
System.err: File: "file:///data/data/org.nativescript.dealer/files/app/tns_modules/tns-core-modules/debugger/debugger.js, line: 71, column: 27
System.err: StackTrace: 
System.err: 	Frame: function:'responseReceived', file:'file:///data/data/org.nativescript.dealer/files/app/tns_modules/tns-core-modules/debugger/debugger.js', line: 71, column: 28
System.err: 	Frame: function:'onRequestComplete', file:'file:///data/data/org.nativescript.dealer/files/app/tns_modules/tns-core-modules/http/http-request/http-request.js', line: 60, column: 33
System.err: 	Frame: function:'onComplete', file:'file:///data/data/org.nativescript.dealer/files/app/tns_modules/tns-core-modules/http/http-request/http-request.js', line: 37, column: 13
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)

System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err: 	at com.tns.gen.org.nativescript.widgets.Async_CompleteCallback.onComplete(Async_CompleteCallback.java:12)
System.err: 	at org.nativescript.widgets.Async$Http$HttpRequestTask.onPostExecute(Async.java:585)
System.err: 	at org.nativescript.widgets.Async$Http$1$1.run(Async.java:486)
System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:224)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5526)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
ActivityManager: Process org.nativescript.dealer (pid 5743) has died

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.3
- Cross-platform modules: 3.3
- Runtime(s): 3.3

### Please tell us how to recreate the issue in as much detail as possible.
I can run smooth in 3.2 version, after update new version and come out this kind of error.  Below is my http code

```
var http = require("http");
http.request({ 
                url:config.login,
                method: "POST",  
                headers: { "Content-Type": "application/x-www-form-urlencoded" },
                timeout:3000,
                content: 'grant_type=password&username='+username + '&password=' + password
            }).then(function (response) { 
                console.log(JSON.stringify(response));
                resolve(response.content.toJSON());  
            }, function (e) {
                console.log(JSON.stringify(e));
                resolve(null);
            }).catch(function() {
                resolve(null);
            });

```

**Comment by NickIliev** [comment]
Hello, @yclau thank you for reporting this issue. We have logged this one as a bug [here](https://github.com/NativeScript/nativescript-cli/issues/3187).

Closing this issue as a duplicate to [https://github.com/NativeScript/nativescript-cli/issues/3187](https://github.com/NativeScript/nativescript-cli/issues/3187) - please keep track on the linked issue for updates n that matter.
