### ISSUE TITLE
getting frameload interupted issue while redirecting to app from redirect url in ios

### ISSUE THREAD

**Issue by chauhan-saurabh** [NativeScript/NativeScript#5013]
![screen shot 2017-10-31 at 8 45 15 pm](https://user-images.githubusercontent.com/31333681/32230457-35a7a37c-be79-11e7-9e9e-a58ff5dc885d.png)

**Comment by tsonevn** [comment]
Hi @chauhan-saurabh,
If I understand you correctly, you are using `openUrl` method provided by `utils` module to open web page in the mobile browser. I tested this case on my side, however, was unable to recreate the problem.  
Regarding that It would help if you could provide some more info about your environment(CLI, tns-core-modules, node, npm versions) and sample project, which could be used for debugging or to review the attached one and to make the needed changes. 
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1433431/Archive.zip)

**Comment by chauhan-saurabh** [comment]
@tsonevn i am using WebView from ui/web-view providing you webview code and package.json info

// webview component
`import { Component, OnInit, ViewChild, ElementRef } from "@angular/core";
import {Router} from "@angular/router";
import { Observable } from 'tns-core-modules/data/observable';
import { WebView, LoadEventData } from "ui/web-view";

@Component({
    selector: "Auth",
    moduleId: module.id,
    styleUrls: ['auth.css'],
    templateUrl: "./auth.component.html"
})
export class AuthComponent extends Observable implements OnInit  {
    public webViewSrc: string = "https://appDomain.auth.us-east-1.amazoncognito.com/login?response_type=token&client_id=CLIENTID&redirect_uri=myapp://callback";

  
    @ViewChild("myWebView") webViewRef: ElementRef;
    
    ngOnInit(): void {
        let webview: WebView = this.webViewRef.nativeElement;
        
        webview.on(WebView.loadFinishedEvent, (args: LoadEventData) => {
            let message;

            if (!args.error) {
                message = "WebView finished loading of " + args.url;
            } else {
                message = "Error loading " + args.url + ": " + args.error;
            }
            alert(message);
            console.log("Message from webview -------> ", message);            
        });
        
    }

    
}`


//package.json

`{
  "description": "Shyft",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.shyft",
    "tns-ios": {
      "version": "3.4.0-2017-10-26-1"
    },
    "tns-android": {
      "version": "3.4.0-2017-10-31-1"
    }
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "4.2.5",
    "@angular/common": "4.2.5",
    "@angular/compiler": "4.2.5",
    "@angular/core": "4.2.5",
    "@angular/forms": "4.2.5",
    "@angular/http": "4.2.5",
    "@angular/platform-browser": "4.2.5",
    "@angular/router": "4.2.5",
    "@klouddms/futuredms-shyft-api-client": "^0.2.1",
    "nativescript-accordion": "^5.0.2",
    "nativescript-advanced-webview": "^1.2.0",
    "nativescript-angular": "4.2.0",
    "nativescript-autocomplete": "^1.0.0",
    "nativescript-braintree": "^1.0.8",
    "nativescript-camera": "^3.0.2",
    "nativescript-chatview": "^1.0.3",
    "nativescript-checkbox": "^2.1.11",
    "nativescript-dialog": "^0.1.0",
    "nativescript-directions": "^1.1.0",
    "nativescript-drop-down": "^3.1.1",
    "nativescript-geolocation": "^3.0.1",
    "nativescript-google-places": "0.0.3",
    "nativescript-mapbox": "^3.1.2",
    "nativescript-pro-ui": "^3.1.4",
    "nativescript-theme-core": "1.0.4",
    "nativescript-urlhandler": "^1.2.1",
    "node-googleplaces": "^0.1.2",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.3",
    "tns-core-modules": "^3.4.0-2017-10-31-2",
    "zone.js": "0.8.16"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "codelyzer": "3.1.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "1.3.0",
    "nativescript-dev-typescript": "0.5.0",
    "node-sass": "4.5.3",
    "tslint": "5.6.0",
    "typescript": "2.4.2"
  }
}`

**Comment by tsonevn** [comment]
Hi @chauhan-saurabh,
Thank you for the attached sample project.
I tested your case on my side and was able to recreate the `too many HTTP redirects` error on iOS, while using WebView component and load a site, which makes more than 15 redirects, while loading the page. For testing, I use the below-attached project and the following URL.
`https://httpbin.org/relative-redirect/20`

In my research, I found that the same behavior is also reproducible for native iOS  WebView and is something that does not depends on NativeScritp abstraction od the component. I also found that this error could be caused by a server configuration error that causes the web page to redirect to itself. For more info, you could review [this](https://stackoverflow.com/questions/38702529/how-to-handle-too-many-http-redirects-error
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1434387/Archive.zip)
) thread in StackOverflow.

**Comment by chauhan-saurabh** [comment]
hi @tsonevn ,
thank you for the response.
i am stuck in this issue. So, can you please help me in signin from awscognito.

**Comment by tsonevn** [comment]
Hi @chauhan-saurabh,
You could try [nativescript-aws-cognito](https://www.npmjs.com/package/nativescript-aws-cognito) plugin, which provides support for AWS Cognito services in NativeScript.

**Comment by chauhan-saurabh** [comment]
Hi @tsonevn ,
Thanks for the plugin nativescript-aws-cognito, can you please provide a sample to implement signin from awscognito.

**Comment by tsonevn** [comment]
Hi @chauhan-saurabh,
Thank you for writing us back.
 `nativescript-aws-cognito` is not officially supported by NativeScript team and the best solution is to contact the plugin's author as you did in the issue [here](https://github.com/aliyksel/nativescript-aws-cognito/issues/1), and to report the problems, which you are facing.
