### ISSUE TITLE
NativeScript cli error when tns run ios or any command related to IOS platform

### ISSUE THREAD

**Issue by fawzywassel** [NativeScript/NativeScript#5015]
cli error =>
NativeScript can only run in Xcode version 6.0 or greater

**Comment by NathanaelA** [comment]
@fawzywassel -- Do you have XCode 8 or 9 installed?   
See: https://docs.nativescript.org/start/quick-setup

**Comment by fawzywassel** [comment]
yes i have XCode 9 , and i follow this steps and all is installed perfect

**Comment by fawzywassel** [comment]
![screen shot 2017-10-31 at 9 34 42 pm](https://user-images.githubusercontent.com/8037526/32245112-647676e2-be83-11e7-954b-f0bbd834bc3a.png)

**Comment by fawzywassel** [comment]
![screen shot 2017-10-31 at 9 36 47 pm](https://user-images.githubusercontent.com/8037526/32245189-a4544834-be83-11e7-979f-245a32027173.png)
this is my xcode version

**Comment by NathanaelA** [comment]
A couple things you can try:
1. what does `xcodebuild -version` say?
2. what does `c++ --version` say?
3. What does `tns doctor` say?

**Comment by fawzywassel** [comment]
`xcodebuild -version`
Xcode 9.0
Build version 9A235
`c++ --version`
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
`tns doctor`
Your components are up-to-date: 
nativescript,tns-core-modules,tns-android,tns-ios

**Comment by NathanaelA** [comment]
@fawzywassel - Everything looks correct based on that.   So when you do a 
- `tns create name` 
- `cd name`
- `tns platform add ios`
- `tns build ios` 

You get that error, correct? , this is from a brand new project correct?

**Comment by fawzywassel** [comment]
yes

**Comment by NathanaelA** [comment]
Can you do a `tns info`?

**Comment by fawzywassel** [comment]
![screen shot 2017-10-31 at 10 55 20 pm](https://user-images.githubusercontent.com/8037526/32248528-a00e46fc-be8e-11e7-994e-abd0344d5607.png)

**Comment by fawzywassel** [comment]
this issue happen when i trying to add/remove/build/prepare ios

**Comment by NathanaelA** [comment]
@tsonevn - Any ideas?    This also probably needs to be moved to the CLI repo...

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-cli#3189
