### ISSUE TITLE
Listening to events being generated when raising/showing alerts

### ISSUE THREAD

**Issue by blaur** [NativeScript/NativeScript#5016]
Hi guys,

My application is listening to some notifications from firebase and whenever a notification is received it will result in an alert dialog. All this works perfectly fine.

My expectation would be that you from any given page can listen to an alert being shown and then react accordingly. For instance, I'm wanting to perform certain actions when the alert is shown.

Is there any way that I can listen to these events on the current page, or maybe on the frame or topmost frame? I'm not seeing any shownModally, showingModally or navigatingFrom events.

Thanks in advance.

**Comment by NickIliev** [comment]
Hello @blaur and thank you for your interest in NativeScript.

Behind dialog module stand [AlertDialog ](https://developer.android.com/reference/android/app/AlertDialog.html)for Android and [UIAlertView ](https://developer.apple.com/documentation/uikit/uialertview?language=objc)for iOS. These are not modal pages but special dialog classes that handle immediate user interaction. On Android, you can set 'cancelable' to allow the user to close the dialog without interaction with it while on iOS the UIAlertView will block any interaction with the view behind until interaction with the shown dialog. That said we are sticking with the native implementations and recommendations on how a user should interact with a dialog.

However, you can still take some actions by implementing your custom logic when the Firebase notification is received (as this is the moment the alert is raised).
