### ISSUE TITLE
Prevent WebView from loading specific URL

### ISSUE THREAD

**Issue by surdu** [NativeScript/NativeScript#5021]
Looking into the source code for both [iOS](https://github.com/NativeScript/NativeScript/blob/2e09d3714a0e8c79992c32baea2462e7dbbd0219/tns-core-modules/ui/web-view/web-view.ios.ts#L47) and [Android](https://github.com/NativeScript/NativeScript/blob/2e09d3714a0e8c79992c32baea2462e7dbbd0219/tns-core-modules/ui/web-view/web-view.android.ts#L27), it looks there is no way to prevent a WebView from loading a specific URL.

Am I missing something?

If not, we need this functionality and most probably we'll implement it in a fork of {N} and create a PR if this is something anybody else would need.

**Comment by tsonevn** [comment]
Hi @surdu,
In your case, you could use `loadStartedEvent ` to validate the url and if needed to stop page loading while using [stopLoading()](https://github.com/NativeScript/NativeScript/blob/2e09d3714a0e8c79992c32baea2462e7dbbd0219/tns-core-modules/ui/web-view/web-view-common.ts#L44) method. For example:

```
    webview.on(WebView.loadStartedEvent, (args: LoadEventData)=>{
        if(args.url === "url"){
            (<WebView>args.object).stopLoading();
        }
    })
```
Let me know if this helps in your case.

**Comment by surdu** [comment]
@tsonevn Ha! Yes, it does the trick! I didn't think of that :)

Thanks!

**Comment by LSmint** [comment]
The stopLoading seems sometimes not working for Android platform, sometimes it still loading and redirect to the specific url

**Comment by tsonevn** [comment]
Hi @LSmint,
Can you provide sample project, which could be used for debugging?

**Comment by LSmint** [comment]
Hi @tsonevn 

You can git clone from https://github.com/LSmint/webviewurltest.git

I have included a sample URL loaded in the web view inside the app.component.ts file. I would like to make sure that specific URL start with "tcl::" will be stopped loading during the loadStartedEvent is called. But when i try to click the image inside the web view, it still continue call loadFinishedEvent and show error net::ERR_UNKNOWN_URL_SCHEME(-10) after webview loaded. This issue only happens in Android platform, iOS works fine.

**Comment by Bidou44** [comment]
I can confirm the problem, the provide solution is not working (also on iOS)
