### ISSUE TITLE
Some question about tab-view

### ISSUE THREAD

**Issue by SkyGrass** [NativeScript/NativeScript#5023]
hey, i am very interested in NativeScript . i think it will have a better furture.
 but , now ,i have some questions .
first  question, when i try to use tab-view tag , i add  'selectIndexChanged' to the tag  and i export it in .js file . and i print the args in the function .
but ,is seems that print is not work , sometime . i tap second tab , the message is show . but i tap the first tab ,no message show! i am so confused....

**Comment by tsonevn** [comment]
Hi @SkyGrass,
First of all, thank you for your interest in NativeScript.
I tested the selectedIndexChnage event on my side and everything with its execution seems to work as expected.
For your convenience, I am attaching GIF files from both simulators and the code, which I used.

XML
```
<GridLayout rows="" columns="">
    <TabView selectedIndexChanged="onSelectedIndexChanged" id="tabViewContainer">
        <TabView.items>
            <TabViewItem title="Tab 1">
                <TabViewItem.view>
                    <Label text="This is Label in Tab 1" />
                </TabViewItem.view>
            </TabViewItem>
            <TabViewItem title="Tab 2">
                <TabViewItem.view>
                    <Label text="This is Label in Tab 2" />
                </TabViewItem.view>
            </TabViewItem>
        </TabView.items>
    </TabView>
    
</GridLayout>
```
JavaScript
```
function onSelectedIndexChanged(args) {
    console.log("onSelectedIndexChanged");
    console.log("newIndex " + args.newIndex);
    console.log("eventName " + args.eventName);
    console.log("oldIndex " + args.oldIndex);
}
exports.onSelectedIndexChanged = onSelectedIndexChanged;
```
To be able to investigate further the issue, please provide some more info about your environment(CLI node, npm modules versions) and sample project, which could be used for debugging.

Also, while logging a new issue, please use the provided template and provide the requested info.
![screencast 2017-11-02 at 9 00 58 am](https://user-images.githubusercontent.com/17448734/32313965-1639a52c-bfae-11e7-96cf-a3fc8f5bd9ab.gif)
![screencast 2017-11-02 at 9 02 01 am](https://user-images.githubusercontent.com/17448734/32313966-1659e7e2-bfae-11e7-8310-7a53211c082b.gif)

**Comment by SkyGrass** [comment]
it is work !!!!  
i just restart the simulator, and it is work !!!
