### ISSUE TITLE
Webpack for development

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#5024]
There PRs in the CLI and the nativescript-dev-webpack:
 - CLI: https://github.com/NativeScript/nativescript-cli/pull/3116
 - Webpack: https://github.com/NativeScript/nativescript-dev-webpack/pull/299
The implementation splits the "prepare" step into "prepare js" and "prepare native" and allows release builds using the CLI and web pack like `tns run ios --bundle --release`.

We basically want to extend this and have it for development builds. We need fast incremental web pack builds.

Problems:
 - [x] Switching on/off snapshot may leave artefacts in platforms/..../app that should be cleaned
 - [x] These take a lot of time:
    - Webpack Bundle Analyzer saved stats file to ./report/stats.json
    - Webpack Bundle Analyzer saved report to ./report/report.html

TODO:
- [x] Show messages in TS and SASS plugins when they skip due to --bundle option.
- [ ] Show messages in Webpack plugin when rejecting the --env.snapshot option with reasons. Moved to https://github.com/NativeScript/nativescript-dev-webpack/issues/441
- [x] Devise strategy how to handle --bundle option without webpack plugin installed. Currently, build hangs without message.

Resources:
https://github.com/angular/angular/tree/master/packages/compiler-cli
https://github.com/angular/angular/pull/18818

**Comment by PanayotCankov** [comment]
```
time ./node_modules/.bin/ngc -p tsconfig.aot.json
```
With `tns-platform-declarations`:
```
real	0m29.511s
user	0m30.300s
sys	0m1.217s
```
Without `tns-platform-declarations`:
```
real	0m12.892s
user	0m13.971s
sys	0m0.700s
```

**Comment by MartoYankov** [comment]
DLL plugins:
https://robertknight.github.io/posts/webpack-dll-plugins/
https://webpack.js.org/plugins/dll-plugin/

Example for Angular with AOT and DLL and lots more:
https://github.com/qdouble/angular-webpack2-starter/blob/master/webpack.config.ts

**Comment by PanayotCankov** [comment]
It looks like compiling without the code generation (AoT) in web pack makes somewhere a web pack context (https://webpack.github.io/docs/context.html) that recursively includes all *.module.ts files generated by the angular compiler. [However our loader tries to load using require here](https://github.com/NativeScript/nativescript-angular/blob/9d92f686cad45f6e95ae0e8873aa09822e0eb27c/nativescript-angular/router/ns-module-factory-loader.ts#L42), we should probably check how to import the modules from the context for the "no-aot in web" story to work.

**Comment by sis0k0** [comment]
We'll target Angular 5 and the new [AngularCompilerPlugin](https://github.com/angular/angular-cli/tree/master/packages/%40ngtools/webpack) for webpack.

**Comment by sis0k0** [comment]
For incremental builds, we can use https://github.com/webpack-contrib/cache-loader

**Comment by PanayotCankov** [comment]
To use skipCodeGeneration: true, we will have to deal with module.id being a number instead of string in web packed modules. This seems to be solvable by using __filename (which web pack seems to replace with path relative to app) and then deal with the calculation of absolute path [here](https://github.com/NativeScript/nativescript-angular/blob/65359fa61b25320072a4e4ec2e19da8c7baa1e0b/nativescript-angular/router/ns-module-factory-loader.ts#L50)

**Comment by PanayotCankov** [comment]
Ok, so for development we will be targeting Angular 5 with the AngularCompilerPlugin and there are some changes that should happen, here is a list of some issues and how we are about to address them:

1. [This NSModuleFactoryLoader doesn't work](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/75769f44e1d93596fd3b098b8223f8133eb7f9c3/app/app.module.ts#L34), We merged a "System.import" in the tns-core-modules though, so [SystemJsNgModuleLoader does work now](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/4a9d175d3b98041ca4ebe0bbbc7970cf035d1459/app/app.module.ts#L49), it should be properly tested and replace our implementation.
2. AngularCompilerPlugin now does a TypeScript build in web pack and fails to figure our .android.css, .ios.html etc. resources, [we will extend it and use private API](https://github.com/NativeScript/nativescript-dev-webpack/blob/4616b12a27de398fcb37d0e52136958113a38084/plugins/NativeScriptAngularCompilerPlugin.ts#L34) to implement the resource resolution, also wrap its FS. This may be unstable! May brake with a patch! However we already talked about this with the angular team and are confident that we will eventually agree on a stable solution using only public APIs in the near future.
3. The web pack config will change drastically but update scripts will be provided and the [web pack config will probably look similar to this](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/4a9d175d3b98041ca4ebe0bbbc7970cf035d1459/webpack.config.js#L234)

**Comment by sis0k0** [comment]
I'm not sure if we should provide update scripts. I think we should document the changes in the webpack configuration and release v1.0, because:
1. The webpack configs will be changed a lot.
2. The workflow will be pretty different, too - using the {N} CLI instead of npm scripts.
3. We discussed that we can turn the snapshot plugin to a loader - that will also affect the webpack configuration. (maybe this can be done later)
