### ISSUE TITLE
ActionBar not showing with lazy loading (Angular)

### ISSUE THREAD

**Issue by JohanBeumer** [NativeScript/NativeScript#5025]
Probably this issue is a duplicate of https://github.com/NativeScript/nativescript-angular/issues/662, but I didn't find an answer in there and the issue is closed.

### Which platform(s) does your issue occur on?
Android (can't verify iOS)

I have a sample project at https://bitbucket.org/JohanBe/nativescript-actionbar

Be aware, the app has 2 routes, both to the same component so they can't be active at the same time.
If the app starts with navigating to the HomeComponent, the actionbar shows the title which in set in home.componet.ts.

If you change the routing to navigate to the lazy loaded HomeComponent, the actionbar doesn't show the title of home.component.ts. Instead it shows the name of the app.

Is there a simple way to solve this?

Issue 662 points to example app nativescript-sdk-examples-ng. However there is a lot of overhead in that app. Is the solution of that project the only way to go?

**Comment by NickIliev** [comment]
@JohanBeumer in each lazily loaded module, we need to import `NativeScriptCommonModule` which will take care of some basic NativeScript functionalities including the rendering of your ActionBar

**_home.module.ts_**
```
import { NativeScriptCommonModule } from "nativescript-angular/common";

@NgModule({
    imports: [
        NativeScriptCommonModule, // RIGHT HERE
        NativeScriptRouterModule.forChild(routes)
    ]
})
```

**Comment by JohanBeumer** [comment]
@NickIliev thnx for the quick response! It's the solution to my problem. 

Now I know what to look for I see many entries on Google about it.
Thnx again!
