### ISSUE TITLE
Nativescript toogling visiblity of LIstItems

### ISSUE THREAD

**Issue by markomiljkovic** [NativeScript/NativeScript#5030]
### Tell us about the problem
Hello guys I have just I quick noob question
I want to toggle Visibility of a ListItem to Make like a accordion,
NOTE: I dont want to use plugin 

Here is my LIstView Im using RadListView

```
 <lv:RadListView id="ticketsList" items="{{ tickets }}">
                        <lv:RadListView.itemTemplate>
                            <GridLayout class="card-layout" rows="*,*" columns="*,*" tap="**showHide**">
                                <Label row="0" col="0" class="ticket-date" text="{{ date }}" />
                                <Button col="1" rowSpan="2" class="play-ticket" 
                                    text="{{ '&#xf04b; ' + 'Play' }}"></Button>
                                <StackLayout row="2" id="accordion">
                                    <Label class="h2" text="Hello user" />
                                </StackLayout>        
                            </GridLayout>
 </lv:RadListView.itemTemplate>
```

and here is my Js file thats Loaded

```
function showHide(args){
	var layout = args.object.getViewById("accordion");
	if(layout.visibility==='visible'){
		layout.visibility = 'collapsed';
	}else{
		layout.visibility = 'visible';
	}
}
```

Here is My Question I have succeded in toggling each List Item visibilty and my code is working
but is the code in showHide method OK? does it influence the performance and is there some other better solution.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.3.0

**Comment by tsonevn** [comment]
Hi @markomiljkovic,
Thank you for your interest in NativeScript.
Regarding your question, using visibility property to toggle the visibility of the item's child element should not influence the performance of the application.
Something that I notice in the sample code is that you are using the same id for all elements. Keep in mind that the id attribute for the element should be unique. In case you need to access some of the child elements I would suggest using the getChildAt method. For example:
```
function showHide(args){
    var mainContainer:GridLayout = (<GridLayout>args.object)
    var layout = mainContainer.getChildAt(2);

	if(layout.visibility==='visible'){
		layout.visibility = 'collapse';
	}else{
		layout.visibility = 'visible';
	}
}
```
I also notice that you are using old CLI and I would recommend upgrading to latest available NativeScript 3.3.0.
For further questions, please use our NativeScript [forum ](https://discourse.nativescript.org/)or [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript).
