### ISSUE TITLE
Using NSURLSession with authentication

### ISSUE THREAD

**Issue by tigerdi** [NativeScript/NativeScript#5032]
In my ongoing quest to enable NTLM authentication with my {N} + Angular iOS app, I have now moved on from trying to use libraries, and trying to use just native code.

I know all the latest iOS networking libraries are based around the NSURLSession class, and so after studying Apple's documentation, I feel like I am pretty close. 

I will go through my code step by step:

```
var URL = NSURL.URLWithString([HTTPS URL]);
var configuration = NSURLSessionConfiguration.defaultSessionConfiguration;
var session = NSURLSession.sessionWithConfiguration(configuration);
```
Here I am creating a new NSURLSession with the default configuration

```
var task = session.dataTaskWithURLCompletionHandler(URL, function (data, response, error) {
    if (error) {
        console.log('Error: ' + error);
    } else {
        console.log('Success: ' + response);
        console.log('Data: ' + data);
    }
})
task.resume()
```
Now I have just created a Task which should just give me the contents of the URL. When this runs, I want the following method to be triggered:

```
// Initialising a challenge variable to go into the method's parameter. Not sure if this is right
var challenge:NSURLAuthenticationChallenge

// Cant seem to get to this method - I know I am not calling it right           
session.delegate.URLSessionDidReceiveChallengeCompletionHandler(session, challenge, function completion(disposition, credential){
    if (challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodNTLM) { 
        
        // Create credentials to be passed into completionHandler    
        var cred:NSURLCredential = NSURLCredential.credentialWithUserPasswordPersistence('[DOMAIN\\USERNAME]', '[PASSWORD]', NSURLCredentialPersistence.ForSession);                    
        
        // Call completion handler with credentials    
        completion(NSURLSessionAuthChallengeDisposition.UseCredential, cred);
    }            
    else if (challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust) {
        
        // Call completion handler with default handling. ServerTrust sometimes is sent first, then NTLM
        completion(NSURLSessionAuthChallengeDisposition.PerformDefaultHandling, null);
    }
    else {
        // Cancel authentication challenge
        completion(NSURLSessionAuthChallengeDisposition.CancelAuthenticationChallenge, null);
     }
}) 
```

The main problem here is that the `URLSessionDidReceiveChallengeCompletionHandler` method is not being called. I feel like it is not correct trying to set this method using `session.delegate`, but it was the only way to get it to not show an error. Incidentally, `session.delegate` logs as being null - but not sure how to set the delegate when creating the NSURLSession, and don't think I should have to. 

The logs show this error:
`CONSOLE ERROR [native code]: ERROR TypeError: null is not an object (evaluating 'session.delegate.URLSessionDidReceiveChallengeCompletionHandler')`

I also feel like I shouldnt be having to create a `NSURLAuthenticationChallenge` variable just to pass into the method.

Hope that all makes sense, and any help you can give would be most appreciated. Thanks

**Comment by NickIliev** [comment]
Hi @tigerdi 

Regarding your issue - take a look on how to implement a delegate method as shown in [this documentation article](https://docs.nativescript.org/runtimes/ios/how-to/objc-subclassing#calling-base-methods-Protocol). 

Please notice that this issue is for logging bugs, features, and issues related to NativeScript modules.
Please post how-to related questions in the community channels like slack, SO or [discourse.nativescript.org](https://discourse.nativescript.org/)

**Comment by tigerdi** [comment]
Thanks @NickIliev 
However when I try this, it doesn't give me an option to 'extend'. The error is: 
`Property 'extend' does not exist on type 'typeof UIResponder'`
I am using typescript if that is an issue.
