### ISSUE TITLE
Binding and Navigating in Modal page

### ISSUE THREAD

**Issue by markomiljkovic** [NativeScript/NativeScript#5041]
### Tell us about the problem

Hello guys, I know this isnt the right place to ask a question but I asked on forums and no one is answering :(

I have a page where user can choose date 
```
  <StackLayout >
         <TextField class="input" editable="false"
                    text="{{ userDate  }}
                    tap="onBirthDateTap" hint="Enter a birth date..." />                
  </StackLayout>

```
and event on tap ,It opens new Modal page and passes data to it

```
exports.onBirthDateTap = function(args) {
    var modalPageModule = "views/selectDate-page";
    var context = { date : args.object.bindingContext   };

    var fullscreen = true;
    page.showModal(modalPageModule, context, function closeCallback(birthDate) {
    }, fullscreen);
};
```

now How can I in my SelectDate-page (modal page), display that date in datepicker and bind to it like this ?????

<Page shownModally="onShownModally" loaded="loaded">
    <StackLayout>
        <DatePicker date="{{ date }}" />
    </StackLayout>
</Page>

Here is my current code in SelectDate-page.js but I cannot seem to get how to bind to view 
```
var model = "";
module.exports = {
    loaded: loaded,
    onShownModally :onShownModally
};

function loaded(args){
        console.log("DATA IN LAODED");
        console.dir(args.context); // display null

}


function onShownModally(args) {
    model  = args.context;  // display date, but how do I bind it to bindingContext and display it in xml
    closeCallback = args.closeCallback;
}

```

but on tap I want to Open Modal page and bind data from userDate and display it in that modal page

Similar code to mine is in this repository

https://github.com/mikebranstein/TheNativeScriptBook/tree/master/Chapter12/PetScrapbook

### Which platform(s) does your issue occur on?
iOS/Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.2.0

**Comment by tsonevn** [comment]
Hi @markomiljkovic,
 In your case, you could set up the binding context in the page loaded event inside the `SelectDate-page.js` file. For example:

`SelectDate-page.js`


```
var model = "";
var observableModule = require("data/observable");
module.exports = {
    loaded: loaded,
    onShownModally :onShownModally
};

function loaded(args){
        var page = args.object;

    model = new observableModule.fromObject(args.context);
    page.bindingContext = model;

}


function onShownModally(args) {
    model  = args.context;  // display date, but how do I bind it to bindingContext and display it in xml
    closeCallback = args.closeCallback;
}
```



This should set up the context of the modal page while using the received data from the main page.
For further questions, you could also use [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript).

**Comment by markomiljkovic** [comment]
Yes I see but args.context inside loaded function return null,
and inside onShownModally return passed context ???

**Comment by markomiljkovic** [comment]
Nevermind seem like I solved it I moved everything you written inside onShownModally method and now its working.
