### ISSUE TITLE
returnKeyType got broken in 3.3 on Android

### ISSUE THREAD

**Issue by sserdyuk** [NativeScript/NativeScript#5050]
@tsonevn 

#4859 broke it. I've commented out two lines added in that commit and everything started working. 

`returnKeyType="next"` is no longer moves to the next input.

**Comment by sserdyuk** [comment]
Ahh. Found it already reported. #5033 #5047

**Comment by TheOnlyMatt** [comment]
Hi ! 
I have took a look at the issues you referenced but didn't find how to make it work again, did you found a way to solve this ?
