### ISSUE TITLE
Parents binding in ListView item templates is not working until ListView is refreshed.

### ISSUE THREAD

**Issue by HunterJS-bit** [NativeScript/NativeScript#5054]
### Tell us about the problem

Hello guys I have a quick question I searched forums but couldnt find answer
How can I display my observable in parents if I have 2 or 3 of them
like this:

`<Button text="{{ $parents['RadListView'].name + " "+ "$parents['RadListView'].surname" ]] }}" />`

This above doesnt works or only gives me one item but what if I want two of them or tree displayed ????

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.2.0

**Comment by NickIliev** [comment]
@markomiljkovic 

There are a number of syntax errors in the your Button XML line.
You have double quotes for your second binding and also some closing brackets at the end that are not needed. 

Here is the refactored code that will work
```
<Button text="{{ $parents['RadListView'].name + '  '+ $parents['RadListView'].surname }}" />
```

Demo application demonstrating the above syntax can be found [here](https://github.com/NickIliev/NS-Issues/tree/master/NativeScript/issue_5054).

Meanwhile, it appears that you might have to [manually refresh the list ](https://github.com/NickIliev/NS-Issues/blob/master/NativeScript/issue_5054/app/main-page.ts#L18-L20)view to update all parents binding in the item templates.

Logging this one as a bug - steps to reproduce use the linked application and
[remove the manual refresh of the list](https://github.com/NickIliev/NS-Issues/blob/master/NativeScript/issue_5054/app/main-page.ts#L18-L20). As a result, the binding will appear only for the few first items or only after the list is scrolled.

**Comment by markomiljkovic** [comment]
thank you very much its working :)

**Comment by NickIliev** [comment]
Reproducible with tns-core-modules@next

**Comment by NathanWalker** [comment]
Released with https://github.com/NativeScript/NativeScript/releases/tag/6.5.9 now
