### ISSUE TITLE
This issue has nothing to do with technology, just a question.

### ISSUE THREAD

**Issue by SkyGrass** [NativeScript/NativeScript#5058]
This issue has nothing to do with technology, just a question.
Hello, thanks for your development team and NativeScript !!
I am a developer from Mainland China. I am very interested in NativeScript. I also know that many people are also very interested in NativeScript.
However, when we visited your company's website, it was very slow ... especially the marketplace.
So I ask, do you consider setting up a well-visited mirror server for users in mainland China?
If you have such a plan, I really thank you very much.

**Comment by NickIliev** [comment]
Hey, @SkyGrass thank you for your interest in NativeScript!

We are currently not planning setting up a mirror server in mainland China.
However, you just need a good connection to NPM to work with NativeScript.
If you have troubles reaching the documentation site then you can create your own [local docs build ](https://github.com/NativeScript/docs#local-setup)but use VirtualBox and Vagrant and access the whole documentation locally. 

Closing this issue as the rep9ository is for logging issues, bugs and features related to NativeScript modules.
