### ISSUE TITLE
Groceries APK size for the groceries demo app?

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/NativeScript#5061]
I'm new to NS so I don't have the proportion of file size app from NS output.

For the groceries app - I've installed webpack and used uglify and release switches : 

    npm run build-android-bundle --uglify  --release 

But after that - I've seen the output file : 

 ![image|510x174](https://discourse-cdn-sjc1.com/standard3/uploads/nativescript/original/2X/7/7f4db3a0a59c1e0d3495715b91fb9f9308a0500d.png)

**Question:**

* It has the `-debug` postfix . Why is that? I executed it with `--release` 
* Does 16 mb  is a reasonable apk size for the groceries app demo ? 

**webpack.config.js** : http://jsbin.com/vivukecuce/edit?html,output
**package.json** : http://jsbin.com/jucapahumi/edit?html,output

**Comment by NickIliev** [comment]
@RoyiNamir the thing is that Android won't build for release unless you pass the release arguments as well.

For example:
```

npm run build-android-bundle -- --release --for-device --key-store-path <path-to-key-file> --key-store-password <pass> --key-store-alias <alias> --key-store-alias-password <alias-pass>
```

If the arguments are not passed the `--release` flag will be ignored and a debug APK is created.

Regadring the release APK size you can see this thread [here](https://discourse.nativescript.org/t/how-to-decrease-app-size-and-release-it-using-webpack-and-nativescript/798)
