### ISSUE TITLE
Run tns doctor waiting too long

### ISSUE THREAD

**Issue by tolerious** [NativeScript/NativeScript#5062]
After I  run `tns doctor`  I got this,
<img width="1420" alt="2017-11-11 8 19 10" src="https://user-images.githubusercontent.com/2922120/32689345-c5a5529c-c71d-11e7-84a4-1f47cd17dc03.png">
and I have waited for a long time.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3215
