### ISSUE TITLE
Install libs linux

### ISSUE THREAD

**Issue by madsongr** [NativeScript/NativeScript#5068]
I don't know how to install these libs in linux manjaro (arch linux based).

`sudo apt-get install lib32z1 lib32ncurses5 libbz2-1.0:i386 libstdc++6:i386
`
Can someone help me?

**Comment by tsonevn** [comment]
Hi @madsongr 
For your case, you could review the solution provides in [this ](https://askubuntu.com/a/637121) forum thread. 
Please for any further questions, which are not related to the NativeScript use [Stackoverflow](https://stackoverflow.com/questions/tagged/nativescript)

**Comment by madsongr** [comment]
What do you mean when you say "which are not related to the NativeScript"? These libs are described to be installed for Nativescript to work properly.

**Comment by tsonevn** [comment]
Hi @madsongr,
Those libraries are not directly related to the NativeScirpt as a product. The mentioned packages in the documentation are needed while installing the Android SDK and some other dependancies which are needed. In the documentation is shown one of the possible ways to install them, however, depending on the Linux distribution the command could be different.

Regarding that, my previous comment. Does the suggested solution in [this thread](https://askubuntu.com/questions/637113/unable-to-locate-package-lib32bz2-1-0/637121#637121) resolve the issue? It would help if you provide some more info about the used Linux distribution.

**Comment by madsongr** [comment]
That thread commands correspond to Ubuntu and its derivatives releases and the libs come from theirs repositories. I can install and work with NS CLI but when I try to install Sidekick it misses those libs or similars.

**Comment by tsonevn** [comment]
Hi @madsongr,
Excuse me for the delay in reply,
If I understand you correctly, you are able to create and build NativeScript project, while using  NS CLI and the issue with those libraries is reproducible only when the Sidekick is used. 
If this is the case I will recommend opening new issue in the [sidekick-feedback repository](https://github.com/NativeScript/sidekick-feedback/issues), which is the right place for problems related to the Sidekick.
Also there you could provide the more detailed info in the newly created issue about the problem and if there is an error, while it is installed.

**Comment by sis0k0** [comment]
It's also reproducible if you try to build with snapshot.
@madsongr, for installing 32bit packages on Arch linux, you need to enable the [multilib](https://wiki.archlinux.org/index.php/multilib) repo.

**Comment by madsongr** [comment]
@sis0k0 I did it too (multilib). But don't worry anymore. I removed that linux distro. Thanks for your attention.
