### ISSUE TITLE
Latest Xcode requires "ios-marketing" App Icon

### ISSUE THREAD

**Issue by abhayastudios** [NativeScript/NativeScript#5072]
### Tell us about the problem
Latest Xcode requires a new `ios-marketing` App Icon to be included in the bundle (builds are now rejected without). See Apple's comments:

> Missing App Store Icon - iOS Apps must include a 1024x1024px App Store Icon in PNG format. Without providing the icon in the Asset Catalog or via iTunes Connect, apps cannot be submitted for App Review or Beta App Review. Refer to https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/ for more information.

I think it would be a good idea to include this icon in the default project and to add something like the entry below to `/app/App_Resources/iOS/Assets.xcassets/AppIcon.appiconset/Contents.json`:

```
    {
      "size" : "1024x1024",
      "idiom" : "ios-marketing",
      "filename" : "iTunesArtwork@2x.png",
      "scale" : "1x"
    }
```

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
Latest Xcode - I have version 9.1 (9B55)

**Comment by shiv19** [comment]
Thank you @abhayastudios <3

**Comment by takahser** [comment]
I came here because I got a related error message, when building my nativescript app using `tns publish ios`:

`WARN: WARNING ITMS-90704: "Missing App Store Icon. iOS Apps must include a 1024x1024px App Store Icon in PNG format. Without providing the icon in the Asset Catalog or via iTunes Connect, apps cannot be submitted for App Review or Beta App Review. Refer to https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/ for more information."`

Until this is fixed, how can I manually add the image?

**Comment by abhayastudios** [comment]
@takahser you can just create an icon of 1024x1024 pixels and save it as  `/app/App_Resources/iOS/Assets.xcassets/AppIcon.appiconset/iTunesArtwork@2x.png` (or use a [generator](http://images.nativescript.rocks/) that generates all the icons for you). Also add the entry to the `Contents.json` as described above.

**Comment by shiv19** [comment]
and just for icon sake, you can use nsimage.brosteins.com

**Comment by takahser** [comment]
thanks for your replies @abhayastudios and @shiv19 

actually I got it to work after including the itunes artwork logos (512 and 1024) in the config file **AppIcon.appiconset/Contents.json**:

```
{
  "images": [
    {
      "size" : "512x512",
      "idiom" : "ios-marketing",
      "filename" : "iTunesArtwork.png",
      "scale" : "1x"
    },
    {
      "size" : "1024x1024",
      "idiom" : "ios-marketing",
      "filename" : "iTunesArtwork@2x.png",
      "scale" : "2x"
    }]
}
```

**Comment by pentool** [comment]
But when I build with the default {N} configuration (eg having the 1024x1024 marketing icons included in the bundle and also having and entry for it in the Contents.json file), during a release build, it will generate a warning that `/Resources/Assets.xcassets:./AppIcon.appiconset/[][ios-marketing][][][][1x][2d][icon-1024.png]: warning: The app icon set "AppIcon" has an unassigned child.`

Will this warning trigger a rejection?

**Comment by shiv19** [comment]
No it won't trigger a rejection

**Comment by abhayastudios** [comment]
From what I can see the latest default project now contains a `icon-1024.png` file and a corresponding entry in `Contents.json`. Closing.

**Comment by qtb000** [comment]
You may need add assets.car file witch is required by ios 11 and you can create it with xcode or online tool http://www.applicationloader.net/appuploader/icontool.php

put assets.car file as asset file or image file .

**Comment by Sam-Davis** [comment]
I'm still getting this issue after adding the 512 and 1024 logos with metadata as specified by @takahser I started this project in late 2018. I can't see any documentation for help on how to include this particular image.
