### ISSUE TITLE
ScrollView dose not scroll

### ISSUE THREAD

**Issue by zhyilong** [NativeScript/NativeScript#5076]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

package.json
{
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": {
		"id": "org.nativescript.Over002",
		"tns-android": {
			"version": "3.3.0"
		}
	},
	"dependencies": {
		"nativescript-theme-core": "~1.0.2",
		"tns-core-modules": "~3.3.0"
	},
	"devDependencies": {
		"babel-traverse": "6.4.5",
		"babel-types": "6.4.5",
		"babylon": "6.4.5",
		"lazy": "1.0.11"
	}
}

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

<Page xmlns="http://schemas.nativescript.org/tns.xsd"
    navigatingTo="navigatingTo"
    loaded="didLoaded"  class="page">

    <ScrollView id="scroll" orientation="vertical" isEnabled="true" width="100%" height="100%" backgroundColor="green">
        <AbsoluteLayout width="100%" height="8000" backgroundColor="gray">
        </AbsoluteLayout>
    </ScrollView>

</Page>

add this page to other page, scroll can not scroll?

**Comment by NickIliev** [comment]
@zhyilong I've created [this test project](https://github.com/NickIliev/NS-Issues/tree/master/NativeScript/issue_5076) and the scroll view is working as expected on Android and on iOS.

**Comment by zhyilong** [comment]
thank you！

I have another question, how to ask 2 rows label showing ellipsis when no enough to show text

发自我的 iPhone

**Comment by NickIliev** [comment]
@zhyilong you can use `textWrap` set `false` however this would work only for single row content.

**Comment by cremfert** [comment]
I had the same issue that scrolling was not possible even with a scroll view and ```adjustResize```. What did the trick for me was to disable the translucent status bar as described here: 

https://discourse.nativescript.org/t/keyboard-covers-the-layout-and-windowsoftinputmode-set-to-adjustresize-doesnt-help-when-you-have-translucent-status-bar/4150

It can be done in the ```values/styles.xml``` and ```values-21/styles.xml``` in the ```App_Resources/Android``` folder.
I just post it here as some others might find it helpful!

**Comment by canelacho** [comment]
I had a similar issue but I solved reducing the % of height, in the scrollview I was setting height="100%", so I tried 90% and it work, then I was testing until get the right number, it was 98%.

**Comment by heese** [comment]
The plugin https://github.com/tjvantoll/nativescript-IQKeyboardManager does a good job fixing these issues.
