### ISSUE TITLE
ActionItem: add a badge

### ISSUE THREAD

**Issue by relvis** [NativeScript/NativeScript#5077]
Is there a way to add a badge to an ActionItem in the action-bar? or it's a feature that needs to be added?

Thanks!

**Comment by NickIliev** [comment]
@relvis 

The ActionItem can be customized by using your own layouts.
e.g.
An ActionItem can be easily customized by placing whichever element you need directly inside.
```
<ActionItem>
    <Label class="m-5" text="Custom item" color="#8C489F"></Label>
</ActionItem>
```

This said you can create your action item while using your own implementation for badge functionality or plugin like[ this one](https://www.npmjs.com/package/nativescript-badge-button)
