### ISSUE TITLE
Create verified plugin for downloading large files (iOS and Android)

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#5079]
Create a verified plugin that handles downloading of large files for both iOS and Android.
Very good plugin handling the Android part can be found [here](https://www.npmjs.com/package/nativescript-downloadmanager)

Related to [https://github.com/NativeScript/NativeScript/issues/3314/](https://github.com/NativeScript/NativeScript/issues/3314/)

**Comment by bradmartin** [comment]
@NickIliev - https://github.com/triniwiz/nativescript-downloader looks close to what is needed/asked

**Comment by triniwiz** [comment]
You can close this now @NickIliev  😁
