### ISSUE TITLE
iOS Page lack of a background screws the page transitions

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#508]
Since there is no background, only the page's content and a shadow is visible during transition. Setting a white background on the Page fixes the behavior presenting a better eye candy. Consider putting background on the iOS Pages by default.

Complaints:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/nativescript/g2bYxSgV2nQ/N-dxpPRrEgAJ

**Comment by rclai** [comment]
Is there any way to get rid of that shadow during transition? My page uses a background image and that shadow is still visible during transitions.

**Comment by hshristov** [comment]
@rclai Could you share a screencast so that we are on the same page?
