### ISSUE TITLE
getting error during ios build 

### ISSUE THREAD

**Issue by chauhan-saurabh** [NativeScript/NativeScript#5092]
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
2017-11-23 14:32:28.757914+0530 shyft[73337:2537215] 1   0x10df86ac8 -[TNSRuntime executeModule:referredBy:]
1   0x10df86ac8 -[TNSRuntime executeModule:referredBy:]
2017-11-23 14:32:28.787256+0530 shyft[73337:2537215] 2   0x109af8e51 main
2   0x109af8e51 main
2017-11-23 14:32:28.787435+0530 shyft[73337:2537215] 3   0x1112fcd81 start
3   0x1112fcd81 start
2017-11-23 14:32:28.787566+0530 shyft[73337:2537215] 4   0x1
4   0x1
JavaScript stack trace:
1   @[native code]
JavaScript error:
2017-11-23 14:32:28.787994+0530 shyft[73337:2537215] [native code]: JS ERROR NSErrorWrapper: The data couldn’t be read because it isn’t in the correct format.

[native code]: JS ERROR NSErrorWrapper: The data couldn’t be read because it isn’t in the correct format.

**Comment by tsonevn** [comment]
Hi @chauhan-saurabh,
Thank you for contacting us.
We reviewed your case, however, the given information is not enough to investigate the problem. Regarding that , please provides a sample project, which could be debugged locally and the full log from the console. It would also help if you give us more info about your environment(CLI, modules. node, npm and Xcode versions).
The problem could be related to using invalid value for a property, which is accessed from code behind.

**Comment by chauhan-saurabh** [comment]
Hi @tsonevn,

here is my package.json
`{
  "description": "Shyft",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.shyft",
    "tns-ios": {
      "version": "3.4.0-2017-11-9-1"
    },
    "tns-android": {
      "version": "3.4.0-2017-11-13-2"
    }
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "4.2.5",
    "@angular/common": "4.2.5",
    "@angular/compiler": "4.2.5",
    "@angular/core": "4.2.5",
    "@angular/forms": "4.2.5",
    "@angular/http": "4.2.5",
    "@angular/platform-browser": "4.2.5",
    "@angular/router": "4.2.5",
    "@klouddms/futuredms-shyft-api-client": "^0.2.9",
    "angular2-uuid": "^1.1.1",
    "jwt-decode": "^2.2.0",
    "moment": "^2.19.2",
    "nativescript-accordion": "^5.0.2",
    "nativescript-advanced-webview": "^1.2.0",
    "nativescript-angular": "4.2",
    "nativescript-autocomplete": "^1.0.0",
    "nativescript-braintree": "^1.0.8",
    "nativescript-camera": "^3.0.2",
    "nativescript-chatview": "^1.0.3",
    "nativescript-checkbox": "^2.1.11",
    "nativescript-dialog": "^0.1.0",
    "nativescript-directions": "^1.1.0",
    "nativescript-drop-down": "^3.1.1",
    "nativescript-geolocation": "^3.0.1",
    "nativescript-google-places": "0.0.3",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-mapbox": "^3.1.2",
    "nativescript-pro-ui": "^3.1.4",
    "nativescript-theme-core": "1.0.4",
    "nativescript-urlhandler": "^1.2.1",
    "node-googleplaces": "^0.1.2",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.3",
    "tns-core-modules": "^3.4.0-2017-11-17-1",
    "zone.js": "0.8.16"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "codelyzer": "3.1.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "1.3.0",
    "nativescript-dev-typescript": "0.5.0",
    "node-sass": "4.5.3",
    "tslint": "5.6.0",
    "typescript": "2.4.2"
  }
}
`

**Comment by tsonevn** [comment]
Hi @chauhan-saurabh,
 I reviewed your package.json file and found that you are using @next modules and runtime. I would suggest changing the versions to the latest official one, which at this time is 3.3. You could also follow the below-attached steps.
1. check the NativeScript version , which you are using with `tns --version`. If the version is different from `3.3.1` run `npm install nativescript --g`, which will install the latest official version.
2. change `tns-core-modules` version to `3.3.0`
3. delete project `node_modules` folder
4. remove ios  and android platform with
`tns platform remove android`
`tns platform remove ios`

5. add platforms again 
`tns platform add android`
`tns platform add ios`

After making those changes, try rebuilding the project with `tns run <platform name>`.
Regarding that, It would help if you could provide at least some code snippets, which you think are related to the problem. This will help in our further investigation.

**Comment by chauhan-saurabh** [comment]
Hi @tsonevn ,
 thanks for your response will make a try and then inform you back

**Comment by chauhan-saurabh** [comment]
Hi @tsonevn , 
its not working for me

**Comment by tsonevn** [comment]
Hi @chauhan-saurabh,
We researched this problem, however, the returned error is too generic, which makes the investigation hard.
Regarding that, It would help if you could send us the project or sample one, which could be used for debugging. In case you do not want to share it here in this Github issue, you could send it to us in a private message in our community slack Chenal - https://nativescriptcommunity.slack.com/ .

**Comment by chauhan-saurabh** [comment]
Hey @tsonevn,
thanks for your help issue is resolved by making new project and adding my all components to that project.
