### ISSUE TITLE
Voip

### ISSUE THREAD

**Issue by behi1ty** [NativeScript/NativeScript#5094]
Hi,
Is it possible to use voip?
Is there a way to use this lazy technology?

**Comment by tsonevn** [comment]
Hi @behi1ty,
If I understand you correctly you would like to create NativeScrtip VOIP calling app. If this is correct I would suggest reviewing [nativescript-sinch](https://github.com/triniwiz/nativescript-sinch) plugin which is created by one of our community members, This plugin supports only Android platform at this time and uses Sinch services to allow making VOIP calling and messaging. 
You could also review the bellow attached articles and to verify how the sinch SDK is used in a native project and to create your own plugin while using [nativescript-plugin-seed](https://github.com/NativeScript/nativescript-plugin-seed) as starting point.
https://www.sinch.com/tutorials/android-app-to-app-voip-tutorial/
https://github.com/sinch/ios-app-to-phone-tutorial
https://docs.nativescript.org/plugins/building-plugins

If the case is different, please provide some more info about the problem.

**Comment by behi1ty** [comment]
Hi @tsonevn 
Thanks for your answer, I want to use my own server, but the plugin you introduced should surely use my server.

**Comment by tsonevn** [comment]
Hi @behi1ty,
 I case you will use your own server, you could create your own plugin with the needed functionality as I suggested in my previous comment and to use the above-attached articles and sample only for a guideline. 
Regards,
@tsonevn
