### ISSUE TITLE
Feature request: Pull-to-refresh ListView

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#51]
_From @truongsinh on April 9, 2015 18:31_

I'm trying to implement "pull-to-refresh" myself with native iOS UIRefreshControl, however, I could not `addTargetActionForControlEvents`, the app crashes with segfault every time i pull
```typescript

class RefreshHandlerImpl extends NSObject {
	static new(): RefreshHandlerImpl {
		return <RefreshHandlerImpl>super.new();
	}

	private _owner: UIRefreshControl;

	public initWithOwner(owner: UIRefreshControl): RefreshHandlerImpl {
		this._owner = owner;
		return this;
	}

	public "myRefresh" (sender: UIRefreshControl) {
		//console.log("refresh")
		//this._owner._emit(eventReload);


	public static ObjCExposedMethods = {
		'myRefresh': { returns: interop.types.void, params: [UIRefreshControl] }
	};
}


// Event handler for Page "loaded" event attached in main-page.xml
export function pageLoaded(args: EventData) {
	var page: Page = <any>args.object;
	var postListView: ListView = view.getViewById(page, "PostListView");


	var refreshControl = new UIRefreshControl();
	var rHandler = RefreshHandlerImpl.new().initWithOwner(refreshControl);
	refreshControl.addTargetActionForControlEvents(rHandler, "myRefresh", UIControlEvents.UIControlEventValueChanged)
	postListView.ios.addSubview(refreshControl);


	page.bindingContext = mainViewModel;
}

```

_Copied from original issue: NativeScript/cross-platform-modules#278_

**Comment by enchev** [comment]
_From @hshristov on April 13, 2015 7:41_

Hi truongsinh,
Could you try to remove the "" around myRefresh method? e.g.

public myRefresh (sender: UIRefreshControl) {
...
}

**Comment by enchev** [comment]
_From @truongsinh on April 13, 2015 18:38_

@hshristov I tried that before. The only reason I used "" is to have "myRefresh:" instead of "myRefresh". However, I believe when transpiling to ES5, it's the same!

**Comment by enchev** [comment]
_From @truongsinh on April 13, 2015 18:40_

Take a look at http://docs.nativescript.org/runtimes/ios/how-to/ObjC-Subclassing, search for
```typescript
// A native class with the name "JSObject" will be registered, so it should be unique
class JSObject extends NSObject implements NSCoding {
    public encodeWithCoder(aCoder) { /* ... */ }

    public initWithCoder(aDecoder) { /* ... */ }

    public "selectorWithX:andY:"(x, y) { /* ... */ }

    // An array of protocols to be implemented by the native class
    public static ObjCProtocols = [ NSCoding ];

    // A selector will be exposed so it can be called from native.
    public static ObjCExposedMethods = {
        "selectorWithX:andY:": { returns: interop.types.void, params: [ interop.types.id, interop.types.id ] }
    };
}
```

**Comment by enchev** [comment]
_From @hshristov on April 14, 2015 6:43_

@truongsinh There are a lot of examples in the cross platform modules were we expose methods that are called from ObjC. Please take a look at Button.ios.ts.

https://github.com/NativeScript/cross-platform-modules/blob/master/ui/button/button.ios.ts

**Comment by enchev** [comment]
_From @truongsinh on April 14, 2015 6:48_

Thanks. I tried to imitate those examples, but always got `Segmentation Fault: 11`. Do you think it is because of something wrong with my script (i.e. if I write NativeScript correctly it will work), or with the logic itself (i.e. if I write that logic in ObjC, I still have `Segmentation Fault: 11`)?

**Comment by enchev** [comment]
_From @PanayotCankov on April 17, 2015 11:40_

**addTargetActionForControlEvents** keeps internally a weak reference, when the GC collects the rHandler the native object used as target is gone, its deallocated, calls to its methods result in seg fault. etc. Would you try keeping the rHandler in a var in the module, that would keep it alive.

E.g. move the "var rHandler" outside the pageLoaded function, or even export it on the module?

**Comment by enchev** [comment]
_From @truongsinh on April 17, 2015 17:22_

I will try in a moment!

**Comment by enchev** [comment]
_From @truongsinh on April 17, 2015 17:41_

@PanayotCankov yes it works, thank you very much! I'll keep this issue open and try to make a PR for this feature, as I believe it is quite popular!

**Comment by enchev** [comment]
Will be available as a plug-in when  http://plugins.telerik.com/ is ready.

**Comment by danicomas** [comment]
Roadmap @enchev?

**Comment by enchev** [comment]
My suggestion actually was to @truongsinh was to create plugin instead this pull request. In this way we will not break the current ListView.

**Comment by valentinstoychev** [comment]
@danicomas Pull to refresh will be available later this month for the Telerik ListView, part of the [Telerik UI for NativeScript](https://www.npmjs.com/package/nativescript-telerik-ui). @ginev can share more.

**Comment by danicomas** [comment]
@valentinstoychev and we will be able to use it in other page without ListView?

**Comment by valentinstoychev** [comment]
@danicomas not in this first version. But I love the idea! We should be able to easily implement it. Do you want to open a separate issue for this so that it doesn't get lost?

**Comment by danicomas** [comment]
@valentinstoychev issue created
