### ISSUE TITLE
Android Facebook Sdk

### ISSUE THREAD

**Issue by AntonioCuevaUrraco** [NativeScript/NativeScript#510]
Hello everyone I am trying to get the facebook login for Android working and this is my progress so far

I managed to build the sdk and access it from nativescript.
Also I can open for login and receive the data from facebook.
but it is crashing when the facebook activity reply back with the data.

Here It crash:

    mCallbackManager.onActivityResult(requestCode, resultCode, data);

And this is the implementation I did of the interface FacebookCallback

      loginManager.registerCallback(mCallbackManager, new com.facebook.FacebookCallback({
         
          onSucces: function() {
            console.log("Print this");

          }
          onCancel: function() {
            console.log("Cancel was press");

           }
           onError: function(e) {
           console.log("errore " + e);
       }

          }));

The cancel is working but the onSucces is generating "abstract method not implemented"

And this is the full implementation code

     if (args.android) {

    //fb initialization
    com.facebook.FacebookSdk.sdkInitialize(application.android.context.getApplicationContext());
   
    //fb objects
    var mCallbackManager = com.facebook.CallbackManager.Factory.create();

    var loginManager: com.facebook.login.LoginManager = com.facebook.login.LoginManager.getInstance(); 
    

    //Implementing the callback Interface
     var callback = new com.facebook.FacebookCallback({
          
           onSucces: function(result) {
             console.log("Print this");

              console.log("Result3 " +result);
           }
           onCancel: function() {
             console.log("Cancel23");

           }
           onError: function(e) {
         console.log("errore " + e);
       } 

           });
       
       var act: android.app.Activity = application.android.startActivity;
        
       //Overriding Activity onActivityResult method to send it to the callbackManager
        act.onActivityResult = (requestCode: number, resultCode: number, data: android.content.Intent) => {
        mCallbackManager.onActivityResult(requestCode, resultCode, data);
        }
        com.facebook.login.LoginManager.getInstance().logInWithPublishPermissions(act,        java.util.Arrays.asList(["publish_actions"]));
      }

**Comment by slavchev** [comment]
Before we investigate the issue can you check if it works when the method is named `onSuccess` (my guess it that you made a typo `onSucces`)

**Comment by AntonioCuevaUrraco** [comment]
You are right :-D  it was a typo. Now I get the access token with no problem. 
We are thinking to create a nativescript module to provide the facebook login since we have it working for iOS and Android, Is someone already working on that?

**Comment by slavchev** [comment]
Glad to help :)

The idea for facebook module is great! I have no idea as to whether someone is already working on such module. As a matter of fact our team don't have much experience with open source projects and guiding the community. So, please let us know if you have any suggestions. Maybe you can take a look at this page https://github.com/NativeScript/NativeScript/issues/236 and decide if it works for you and the others.

**Comment by valentinstoychev** [comment]
Hey @AntonioCuevaUrraco - this is a great initiative and as @slavchev said - please feel free to ask as any questions on the implementation. If you want to find fellow developers you can ask on the [forum](https://groups.google.com/forum/#!forum/nativescript) or in the [G+ community page](https://plus.google.com/communities/117408587889337015711).

@Nathanaela - are you interested to work on this with @AntonioCuevaUrraco?

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#174
