### ISSUE TITLE
Change TabViewItem title size

### ISSUE THREAD

**Issue by mobilemindtec** [NativeScript/NativeScript#5104]
Hi,

How can I change TabViewItem title size in IOS? On android the title is good, but on IOS the title is very small.

IOS Screen

![screen shot 2017-11-27 at 19 17 59-partt](https://user-images.githubusercontent.com/8561714/33374726-66569268-d4ee-11e7-9bba-7fa25e226358.png)

Android Screen

![screenshot_20171129-101810](https://user-images.githubusercontent.com/8561714/33374878-10d636b2-d4ef-11e7-9d19-fae23f2ab057.png)

**Comment by tsonevn** [comment]
Hi @mobilemindtec 
This issue seems to be duplicated with #1269. Please leave your comment on the other issue.
