### ISSUE TITLE
Nativescript - error: Unable to apply changes on device: 192.168.56.101:5555. Error is: Command gradle w.bat failed with exit code 1.

### ISSUE THREAD

**Issue by irvanap1111** [NativeScript/NativeScript#5106]
I followed the steps on
https://docs.nativescript.org/tutorial/chapter-1#11-install-nativescript-and-configure-your-environment
But the error as in the picture. How to solve it?

`tns create HelloWorld --template nativescript-template-tutorial`
`cd HelloWorld`
`tns run android`

I have tried
`tns platform remove android `
And
`tns platform add android`
but still failed.

![Nativescript Error 1](https://user-images.githubusercontent.com/16983323/33416014-ee47f32c-d5cc-11e7-900e-d6741247fbf9.PNG)
![Nativescript Error 2](https://user-images.githubusercontent.com/16983323/33416097-5db987ca-d5cd-11e7-9906-eb9725005bf4.PNG)

**Comment by tsonevn** [comment]
Hi @irvanap1111,
Thank you for contacting us.
We reviewed your case and the returned error seems to be related to an issue with the local configurations of the machine. Regarding that, I would suggest reviewing the article [here ](http://www.tomsguide.com/faq/id-1761312/fix-create-java-virtual-machine-issue.html) and to test the provided solution on your side.

Let me know whether this help or if I could assist you further.

**Comment by irvanap1111** [comment]
@tsonevn Thank you for the reply. I have tried to follow the steps in the article, but failed.

![hps fra2](https://user-images.githubusercontent.com/16983323/33418725-d2a13b76-d5d9-11e7-9071-5994efdd144b.PNG)

**Comment by Pip3r4o** [comment]
@irvanap1111 please refer to the following response in the nativescript android runtime repository - https://github.com/NativeScript/android-runtime/issues/758#issuecomment-300128238. In short - make sure you have installed the 64bit distribution of Java (Oracle JDK)

**Comment by irvanap1111** [comment]
This works
Oh he does not have any offline nativescript documentation like at https://devdocs.io/offline ? Because such documentation is very helpful.
Thanks @tsonevn and @Pip3r4o
