### ISSUE TITLE
Is it possible to use the Angular 5 WebApp source within the NativeScript WebView?

### ISSUE THREAD

**Issue by Kampii** [NativeScript/NativeScript#5107]
I am reaching out to the NativeScript experts with a hope that there is a way to solve this challenge, this is not a bug, rather an architectural/ technology/ compatibility puzzle.

For the last couple of weeks we have been trying to come up with an architecture that would allow us to build a regular Angular WebApp that saves data to MySQL and be able to pull it in NativeScript and hook up the **WebView** with SQLite which would then sync with the MySQL. In other words, our goal is to have a single Angular code base and be able to build a native mobile app with a WebView which communicates with SQLite. I want to emphasize that the WebView of the native app communicates with the local SQLite DB. This will allow the WebView to work offline. We brainstormed and came up with two approaches.

With the Approach 1 we would build the regular Angular WebApp which directly communicates with MySQL - no problems here. The question is if it's possible to put the Angular WebApp source code into www folder of the NS App and somehow built together with the NS code? We were not able to find any library that would do that. There is a plugin that allows the WebView to communicate with the SQLite, so that part is not the problem. We are stuck at figuring out how to run the Angular WebApp source code into NS WebView. 

![image](https://user-images.githubusercontent.com/725316/33416250-7087551c-d550-11e7-9565-c2c5573c199c.png)

In the Approach 2 we were thinking about some separate NS code that would communicate with the SQLite, and we would put this code into the Angular WebApp so that the WebApp could communicate with the NS App. THEN, the NS App would have some kind of interface that would get calls from Angular WebApp dist build. How do we let the Angular WebApp know what NS functions we have? Like in Java, can we create an interface like thing which would be used by the Angular WebApp and after it is compiled, the compiled code could be used with NS WebView to access the native functionalities like sqlite database, etc?

![image](https://user-images.githubusercontent.com/725316/33416498-bb23da90-d551-11e7-93dd-361a1eebc9b2.png)

I posted this question because we are running out of options. Both of the approaches above are concepts, but we have not been able to get it working. We would highly appreciate any feedback, idea, google keyword etc.

**Comment by kurapikats** [comment]
This can be done with meteorjs + angular + apollo

**Comment by Kampii** [comment]
Thank you @kurapikats for the keywords, but we have picked the NativeScript as our partner. Thank you!

**Comment by Kampii** [comment]
Thank you @NickIliev!
