### ISSUE TITLE
card emulation

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#5109]
_From @Nurgunkalol on November 30, 2017 10:0_

is any plugin for https://developer.android.com/guide/topics/connectivity/nfc/hce.html ?
thx for advance.

_Copied from original issue: NativeScript/nativescript-angular#1104_

**Comment by tsonevn** [comment]
Hi @Nurgunkalol,
I have researched your case and found that there is a plugin, which provides support for `NFC Tag Reading` called nativescript-nfc. Regarding that, you could review the plugins [repository ](https://github.com/EddyVerbruggen/nativescript-nfc) and verify, if it is applicable to your case.

**Comment by Nurgunkalol** [comment]
Hi @tsonevn 
I founded this plugin before, but it works as scanner, im looking for card emulation inside application

**Comment by tsonevn** [comment]
Hi @Nurgunkalol,
I research this case, however, I was unable to find another plugin, which provides the functionality that you need. Regarding that, I would suggest creating your own plugin. You could review [this article](https://docs.nativescript.org/plugins/building-plugins) from our documentation and as starting point to use native [nativescript-plugin-seed](https://github.com/NativeScript/nativescript-plugin-seed)

**Comment by vakrilov** [comment]
Closing this one, as ti looks like something that will be done in a plugin instead in the core-modules.

For future readers: https://market.nativescript.org/ would be a good place to check if such plugin already exists.
