### ISSUE TITLE
Style of progress bar

### ISSUE THREAD

**Issue by Judyzhudi** [NativeScript/NativeScript#511]
Hi Everyone,

I am dealing with the progress bar. I follow the example on the documentation. It the documentation only shows how to change the value.
http://docs.nativescript.org/ApiReference/ui/progress/HOW-TO.html
However, I want to change the colour of the bar tint and make the bar wider. I try with cssClass in xml file. It does't work.

**Comment by BasyaLipman** [comment]
This helped: https://stackoverflow.com/a/46567698/6743682
