### ISSUE TITLE
Fix scaling of background images on iOS

### ISSUE THREAD

**Issue by dbenninger** [NativeScript/NativeScript#5112]
### Tell us about the problem
I have noticed that background images are blurred on iOS as soon as I scale it using the background-size css attribute. I have already located the issue in background.ios.ts. A PR is following soon..

### Which platform(s) does your issue occur on?
iOS only

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.3.0
- Cross-platform modules: 3.3.0
- Runtime(s): 3.3.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Use a hand-drawn image or an image with small text
2. Scale it using background-size
3. It looks blurred on iOS, but fine on Android

**Comment by tsonevn** [comment]
Hi @dbenninger,
Thank you for reporting this issue. I tested this case and indeed the background images will be blurred for iOS. I am attaching sample project, where the problem could be reproduced. I will look forward to the PR.

Thank you in advance for your cooperation
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1520780/Archive.zip)

**Comment by dbenninger** [comment]
Here is the PR: https://github.com/NativeScript/NativeScript/pull/5113

**Comment by tsonevn** [comment]
@vakrilov
