### ISSUE TITLE
remove file 

### ISSUE THREAD

**Issue by rehamalisalehhosni** [NativeScript/NativeScript#5122]
please iwant remove this files
https://github.com/NativeScript/NativeScript/files/1225336/listview.txt

**Comment by NickIliev** [comment]
@rehamalisalehhosni files attached via GitHub can't be deleted by GitHub users. Still, as a creator of the issue, you can remove the link to the file by editing the issue post. See [this thread](https://stackoverflow.com/a/33215776/4936697) for details regarding the above

**Comment by rehamalisalehhosni** [comment]
thank you
