### ISSUE TITLE
Nativescript - How to hide a menu under the bottom? [question] 

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/NativeScript#5123]
I have these two images where one is on top of the other : (twitter image and black image):

[![enter image description here][1]][1]

The black image should be hidden  at bottom - and when a user clicks the twitter page - ***the black menu should slide-in from bottom***.

The black image is in the middle (on top of the other image) since the outside Gridview doesn't have any rows  - so everything is placed as a z-index stack: 

    <GridLayout   columns="*"  >
     <GridLayout slide-out>
            <Image src="~/images/page.png"    ></Image>
        </GridLayout>
    
        <StackLayout slide-in class="slide b" height="300" >
            <Image   src="~/images/replies.png" "></Image>
        </StackLayout>
    </GridLayout>

But the Black image ( which held by Stacklayout) should be hidden at the bottom like this : 

[![------------------][2]][2]

**What have I tried so far ?** 

As you see there is a directive on the Stacklayout (named `slide-in`) : 

So I set its `marginBottom` on startup  : 

     constructor(el: ElementRef) {
            this.element.nativeElement.marginBottom = 0;
        }

But the Stacklayout stays the same  ( in the middle)/

If I set 

     this.element.nativeElement.marginBottom = -screen.mainScreen.heightDIPs;

It shows : 

[![enter image description here][3]][3]

But it should be completly hidden at bottom

**Question:**

How can I hide it at the bottom ? 

  [1]: https://i.stack.imgur.com/tpnJZ.png
  [2]: https://i.stack.imgur.com/voEIP.png
  [3]: https://i.stack.imgur.com/50Rh4.png

**Comment by tsonevn** [comment]
Hi @RoyiNamir,
I this case you could use `visibility` property, which will allow you to hide the needed component. For example:
```
<GridLayout   columns="*"  >
 <GridLayout slide-out>
        <Image src="~/images/page.png"    ></Image>
    </GridLayout>

    <StackLayout  [visibility]="isItemVisible ? 'visible' : 'collapsed'" class="slide b" height="300" >
        <Image   src="~/images/replies.png" "></Image>
    </StackLayout>
</GridLayout>
```

Another option could be to use NativeScript [translate animations ](https://docs.nativescript.org/ui/animation-code) on element loaded event. I am attaching a sample project.

For further questions please use our NativeScript [forum](https://discourse.nativescript.org/) or [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript).
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1526145/Archive.zip)

**Comment by RoyiNamir** [comment]
@tsonevn  I must say the I see you post a lot or answering via project. This is not obvious .
I would like to thank you for your extra effort.
