### ISSUE TITLE
tns-core-modules text-transform conversion

### ISSUE THREAD

**Issue by woozie** [NativeScript/NativeScript#5125]
Hellow

https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/text-base/text-base.android.ts#L327

if you have object like

`[{
id: 1
}, {
id: 2
}]
`

and code in repeater

`<Label class="label" text="{{ id }}"/>`

and style 

`label {
text-tranform: uppercase;
}`

so error occurs

TypeError: text.toUpperCase is not a function

for me fails only Android 7. iOS - ok

Solution: In future release add String(text).toUpperCase or check if input value numeric do nothing

**Comment by tsonevn** [comment]
Hi @woozie,
Thank you for contacting us,
I tested the described scenario while using the latest NativeScript CLI 3.3.1, `tns-core-modules` -  `3.3.0` and typescript `2.4.2` on Android

 simulator API level 24, however, was unable to recreate this error.
For your convenience, I am attaching sample project and screenshot from the console.
It would help if you could also give us some more info about your environment(CLI, node, npm modules, typescript versions)
 
![screen shot 2017-12-04 at 9 14 27 am](https://user-images.githubusercontent.com/17448734/33540659-c66da4a4-d8d4-11e7-929d-194225fc07c7.png)
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1526016/Archive.zip)

**Comment by woozie** [comment]
try text-transform, not tranform

Eugenes-MacBook-Pro:Archive coba$ tns --version
3.3.0

tns-core-modules 3.3.0

![screen shot 2017-12-05 at 00 53 37](https://user-images.githubusercontent.com/3217527/33580713-ecfd2c3e-d956-11e7-828e-5a67aa7189db.png)

**Comment by tsonevn** [comment]
Hi @woozie,
Excuse me for the mistake.
I fix the sample project and indeed this is a real issue. Regarding that, I updated the project in my previous comment. Regarding that please keep track on the issue for further info.
