### ISSUE TITLE
Nativescript move element by 50% and not by 100%?

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/NativeScript#5127]
I have a simple demo project where : 

    <GridLayout>
    
        <StackLayout #myStack1 width="100" height="100" translateX="-50" backgroundColor="red" id="bbb">
        </StackLayout>
    
        <StackLayout #myStack2 width="100" height="100" translateX="50" backgroundColor="green" id="ccc">
        </StackLayout>
    </GridLayout>

[![enter image description here][1]][1]

Notice that `width` and `height` are `100`.

Now let's add `marginTop` to the `green` layout : 

    @ViewChild("myStack2") private myStack2: ElementRef;
    ngOnInit(): void {
        this.myStack2.nativeElement.marginTop =100;
      }

But look what happened : 

[![enter image description here][2]][2]

It moved by `50%` of `100` ( box dimensions are 100) . Why is that ? 

**Question:**

Why did that happen and how can I fix my code to actually marginTop `100` ?

I'm not after  `translateY=100` ( which does show it as expected - I;m after the reason and solution for `marginTop`).
    

  [1]: https://i.stack.imgur.com/veZoD.png
  [2]: https://i.stack.imgur.com/k3kiv.png

**Comment by NickIliev** [comment]
@RoyiNamir 

Apart from [the solution](https://stackoverflow.com/questions/47633023/nativescript-move-element-by-50-and-not-by-100) with `verticalAlignment` set to `top` (which is not applicable in your case as you are seeking horizontally centered items) you can use the same approach with `verticalAlignment` set to `center` for both items but then once again the content will be "stretched" and you will need to apply `marginBottom` for the first box and `marginTop` for the second one.

For example:
```
<StackLayout orientation="horizontal" backgroundColor="gray">
    <StackLayout col="0" verticalAlignment="center" marginBottom="100" width="100" height="100" backgroundColor="red">
    </StackLayout>

    <StackLayout col="1" verticalAlignment="center" marginTop="100" width="100" height="100" backgroundColor="green">
    </StackLayout>
</StackLayout>
```

Or using GridLayout (with set columns)
```
<GridLayout columns="auto auto" backgroundColor="blue">
    <StackLayout col="0" verticalAlignment="center" marginBottom="100" width="100" height="100" backgroundColor="red">
    </StackLayout>

    <StackLayout col="1" verticalAlignment="center" marginTop="100" width="100" height="100" backgroundColor="green">
    </StackLayout>
</GridLayout>
```

A third option is to set the height of your parent layout and again use `verticalAlignment` set to `top`. Then you can position the parent layout to be vertically centered relatively to the main page layout.

```
<!--center the GridLayout to be vertically aligned in the center of the wanted layout -->
<!-- Note that we are setting the height of the rows to 200 -->
<GridLayout rows="200" columns="auto auto" backgroundColor="yellow">
    <StackLayout col="0" verticalAlignment="top" width="100" height="100" backgroundColor="red">
    </StackLayout>

    <StackLayout col="1" verticalAlignment="top" width="100" height="100" marginTop="100" backgroundColor="green">
    </StackLayout>
</GridLayout>
```

Demo application demonstrating the above approached can be found [here](https://github.com/NickIliev/NS-Issues/tree/master/NativeScript/issue_5127)

**Comment by RoyiNamir** [comment]
I appreciate it a lot Nick. no words to thank.

**However** - I think that there is a four solution. ( please confirm)

Since no  alignment is specified : 

**Had alignement been specified** ( `left` for example) then axis would be : 

 ```
+----------------------+
|   
| 0 1 2 3 4 5 6 7 8 9 10   
|                                      
|                                      
+----------------------+
 ```
But since i'm not specifying it so `"0"` is in the middle : 


 ```
+----------------------+
|   
|----------- 0----5---10 
|                                      
|                                      
+----------------------+
 ```
But now - density is double.
And that's why  when I do : 

        this.myStack2.nativeElement.marginTop = 100*2 ;

With my original markup : 

```
<GridLayout   borderColor="red" borderWidth="2"  >
    <StackLayout      width="100" height="100"  translateX="-50" backgroundColor="red" id="bbb">

    </StackLayout>

     <StackLayout    #myStack2 width="100" height="100" translateX="50" backgroundColor="green" id="ccc">
    </StackLayout>
</GridLayout>
```


Result : 

![image](https://user-images.githubusercontent.com/2842123/33559669-33ed5614-d916-11e7-9c65-8dad998e551e.png)

 am I right ? ( or am I talking rubbish ..?).

**Comment by NickIliev** [comment]
@RoyiNamir yep that viable solution but might be hard to implement if you have more complex layout structure with multiple elements and margins. - in fact, I am not so sure what would happen if you decide to mix a layout with set alignment and this approach so I would prefer to set `verticalAlignment` and `horizontalAlignment` and then use the more simple math for all nested and root layouts.
