### ISSUE TITLE
Webpack as hooks v0.9.0

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#5129]
Webpack for development will be delayed as the Angular 5 introduced some necessary changes. We adopted the new AngularCompilerPlugin for webpack. CLI hooks are now merged and CLI commands such as `tns run ios --bundle` can be used instead of the current npm scripts.

Well done, this is the TODO list before the release party:

## For the 3.4 Release
 1. [x] (@PanayotCankov) Fix the hello world templates!
 2. [x] (@PanayotCankov) tns-core-modules merge .scss support
 2. [x] (@PanayotCankov) Bump nativescript-dev-webpack the version to 0.9.0
 3. [x] (@PanayotCankov) Merge the PR.
 4. Double build? Running consecutive commands should run:
 - `tns run android --bundle`
 - `tns run android --bundle --env.snapshot`
 - `tns run android`  
  We should:
 - [x] (@dtopuzov @vchimev @SvetoslavTsenov) Test for such issues
 - [x] (@Mitko-Kerezov) Isolate repros, and consider fixes or just "clean platforms" as workaround
 5. [x] (@Mitko-Kerezov) Update the webpack repo documentation, change the npm scripts readmes with the tns --bundle.
 6. [x] (@Mitko-Kerezov) Update the npm scripts to fail with exit code 1, log the dependencies and the new commands.
 7. [x] (@Mitko-Kerezov) Update the CLI command line help
 8. [x] (@NickIliev @tsonevn) Update the documentation article
 9. [x] (@Mitko-Kerezov) nativescript-dev-sass|less|typescript print `executing hook`, with --bundle notify it is suppressed
 10. [x] (@Mitko-Kerezov) What if --bundle is passed but no bundler is installed, print a message. @vchimev to add a test
 11. [x] (@MartoYankov) Fix the templates, `styleUrls: ["./items.component.scss"]` now works, fix templates.
 12. [x] (@PanayotCankov) nativescript-angular livesync .scss is instead the .css when not bundled
 14. [x] (@PanayotCankov) AoT doesn't work with the lazy loaded modules, mind `--env.aot` in tests
 15. [x] (@PanayotCankov) iOS LaunchScreen doesn't work with webpack
 16. [x] (@PanayotCankov) vendor.js for JavaScript projects has TypeScript content, @vchimev to enable tests on CI when fixed
 16. [x] (@PanayotCankov) main.aot.ts is not part of the compilation as it is not included in `tsconfig.json`, @vchimev to enable tests on CI when fixed
 17. [x] (@PanayotCankov) Update/Test groceries  
      https://github.com/NativeScript/sample-Groceries/tree/angular5
 18. [x] (@PanayotCankov) app.css to be able to load .less, .sass, .scss
   21. [x] (@PanayotCankov) Whit this version `moduleId: module.id` must become `moduleId: __filename`, check if this can be handled with a webpack plugin.
 22. [x] (@PanayotCankov) Figure out why ./ in loadChildren stopped working. (it turns out it is relative to app/ and never actually worked as relative to the module it is written in) 
 23. [x] @PanayotCankov to update https://github.com/NativeScript/template-hello-world-ng/blob/master/main.aot.ts#L4

## Nice to have post-release
 19. [x] (@PanayotCankov) Try to remove the tsconfig.aot.json and use a single tsconfig.json, provide a app.module.ngfactory.d.ts
21. [x] [Tried - didn't work] In Angular the app.css is loaded using the tns-core-modules logic, while component css-es are handled by angular and the angular compiler, this introduces two different paths with different set of loaders in the webpack config, let's try to unify them, for example require the app.css in app component/module with global scope.
20. [ ] (@PanayotCankov) Move the bundle-config from the template-hello-world to the webpack
22. [x] Clean up unused loaders (classes) from nativescript-dev-webpack (platform-css-loader, tns-aot-loader etc.) Moved to https://github.com/NativeScript/nativescript-dev-webpack/issues/442

**Comment by vchimev** [comment]
The compatibility between packages with the next official release:
```
nativescript@3.4.0 - CLI
tns-android@3.4.0
tns-core-modules@3.4.0
tns-template-hello-world@3.4.0
tns-template-hello-world-ts@3.4.0
tns-template-hello-world-ng@3.4.0
nativescript-angular@5.0.0
nativescript-dev-typescript@0.6.0
nativescript-dev-webpack@0.9.0
```

**Comment by PanayotCankov** [comment]
- [ ] Add the sass-loader and node-sass when adding nativescript-dev-webpack

**Comment by PanayotCankov** [comment]
- [ ] Make https://github.com/telerik/nativescript-ui-samples-angular/blob/vlaeva/webpacknext/sdkAngular/webpack.config.js work with --bundle --env.aot --env.snapshot --env.uglify

**Comment by elvismercado** [comment]
Hey @PanayotCankov . I am experiencing an issue when using that combination of flags: 
`--bundle --env.aot --env.snapshot --env.uglify`
Are you experiencing the same problem?

![screen shot 2018-01-02 at 10 26 46](https://user-images.githubusercontent.com/3658208/34481036-b768361a-efa7-11e7-8da9-7f87c9d2d889.png)

**Comment by NickIliev** [comment]
@elvismercado please open a separate issue describing in details the case along with providing sample code or project which can reproduce the case.

**Comment by ADjenkov** [comment]
Fail to bundle with file names `kinvey-nativescript-sdk.android.min.js/kinvey-nativescript-sdk.ios.min`
