### ISSUE TITLE
Nativescript UI chart: resize problem (android)

### ISSUE THREAD

**Issue by attdona** [NativeScript/NativeScript#5132]
### Description

Three is a resize problem with a chart component inserted into a content area of a drawer based app.

At app start all is ok:

<img src="https://user-images.githubusercontent.com/943963/33602251-01d75190-d9af-11e7-949d-9c0f85ff40f8.png" width="300" height="600" />

After an app resume or a click on Home drawer menu item the chart is nor rendere correctly:

<img src="https://user-images.githubusercontent.com/943963/33602653-4483ccde-d9b0-11e7-8b10-30f00d59dea5.png" width="300" height="600" />

### Which platform(s) does your issue occur on?
Android (IOS not tested)

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.3.0
- Cross-platform modules: 3.3.0
- Runtime(s): 3.3.1
- Plugin(s): nativescript-pro-ui 3.2.0

### How to recreate the issue

The RadSideDrawer.mainContent:

```
     <nsDrawer:RadSideDrawer.mainContent>
            
            <GridLayout columns="*" rows="auto, *" class="page-content">
                <Label row="0" col="0" class="center" text="Online Users"/>
                <chart:RadCartesianChart row="1" col="0" height="1000" class="graph" id="cartesianChart">
                    <chart:RadCartesianChart.series>
                        <chart:BarSeries items="{{ categoricalSource }}" categoryProperty="Day" valueProperty="Amount">

                            <chart:BarSeries.horizontalAxis>
                                <chart:CategoricalAxis/>
                            </chart:BarSeries.horizontalAxis>
                            <chart:BarSeries.verticalAxis>
                                <chart:LinearAxis majorStep="5" labelFormat="%.0f"/>
                            </chart:BarSeries.verticalAxis>
                        </chart:BarSeries>
                    </chart:RadCartesianChart.series>
                </chart:RadCartesianChart>
            </GridLayout>
        </nsDrawer:RadSideDrawer.mainContent>

```

The nativescript demo project that shows the problem:

[demo.tar.gz](https://github.com/NativeScript/NativeScript/files/1530779/demo.tar.gz)

Greetings
Attilio

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#434
