### ISSUE TITLE
scrollToIndex Method on Android

### ISSUE THREAD

**Issue by horeyes** [NativeScript/NativeScript#5135]
Hello, 

Method: scrollToIndex on android.

### Tell us about the problem
I'm trying to use the scrollToIndex method, but even though I'm calling the method on AfterViewInit it doesn't work on Android; while on IOS it does.

In this case I'm setting the scrollToIndex position to 8.

### Which platform(s) does your issue occur on?
Android

### Please tell us how to recreate the issue in as much detail as possible.
Run the app on an IOS device and the scrollToIndex position will be 8.
Hence we get the expected behavior. 

However,
Run the app on an Android device and the scrollToIndex postion will remain at zero.
Thus, not giving the expected behavior. 

Link to playground: https://play.nativescript.org/?template=play-ng&id=THPmPi&v=3

Thanks in advanced

**Comment by tsonevn** [comment]
Hi @horeyes,
You could use the loaded event and navigate to the needed index, when it is fired. For example:
```
<RadListView #dateListView (loaded)="loadedEvent($event)" [items]="getDay">
	<ng-template tkListItemTemplate let-item="item">
		<StackLayout>
			<Label id="date-day" [text]="item" textWrap="true"></Label>
		</StackLayout>
	</ng-template>
	<ListViewLinearLayout tkListViewLayout scrollDirection="Horizontal"></ListViewLinearLayout>
</RadListView>
```
```
public loadedEvent(args){
// scroll to index
}
```
Also you could review this issue, where it is [mentioned the new ](https://github.com/telerik/nativescript-ui-feedback/issues/329)`dataPopulated` event, which will be available in the upcomming release of UI for NativeScript. This event could be used for those scenario, when you need to scroll to specific index.

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#437
