### ISSUE TITLE
Change the outDir of the transpiled code

### ISSUE THREAD

**Issue by GeorgeKnap** [NativeScript/NativeScript#5139]
### Tell us about the problem
I would like to ask for reopening  #4842 . `tsconfig.json`'s `outDir` property should be allowed to change transpiled code directory together with setting the new `main.js` path in `app/package.json`.

Recommended solution was to _hide_ the files in VS Code. I believe that hides the problem, not solve it.
Polluting codebase with compiled files is always wrong.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.3.1
- Cross-platform modules: 3.3.0
- Runtime(s): 3.3.1
- Plugin(s): 3.3.0

**edit**
it actually does work only if I put the `outDir` path inside `app` folder. That ease the pain but it's not 100% flexible.

**Comment by tsonevn** [comment]
Hi @GeorgeKnap,
I will reopen the old issue, in regard to that, let's keep the discussion there. Also, it would help if you could provide some more info about the need for a similar feature and what would be the benefits. 
Ther also the other users could leave their opinion and if there is an interest the developers' team will discuss what would be the options for introducing a similar feature.

Best regards @tsonevn

**Comment by GeorgeKnap** [comment]
- not everyone is using VS code or any editor with the ability to hide transpiled files
- Some version control systems might try to add transpiled files into version control each time the files are generated. Separate dist folder can be easily put into version control system's ignore list.
- Image you'd like to `.zip` you project for any reason. There is no need to include any unnecessary files which would increase the `.zip` file size.

Ideally I would like to set the `outDir` under root folder where also node_modules are.

**Comment by tsonevn** [comment]
Hi @GeorgeKnap,
Could you comment in the other issue, which is already opened?
