### ISSUE TITLE
Include and maintain Code Editors IDE plugins repositories  

### ISSUE THREAD

**Issue by darkyelox** [NativeScript/NativeScript#5141]
This issue does not refer to any version of NativeScript or platform, it's a suggestion for to maintain also a repository of plugins for VSCode as you maintain a repository for TNS plugins from Github, because there are too few plugins that do well the work, or simply are abandoned by their developers (worrying); Maybe you can create their own plugins also, maybe not only for VSCode maybe for Android Studio (as i see in the roadmap you plan to allow nativescript development using Android Studio) i guess this issue is useful for you, if not, i don't care if you close it

**Comment by NickIliev** [comment]
@darkyelox thank you for your interest in NativeScript and for the suggestions made. 
We are constantly working on improving the user experience with our framework and one of our latest initiatives is the [NativeScript marketplace](https://market.nativescript.org/). This is the place where our plugins team is adding **verified** plugins and templates. More information about the marketplace can be found [here](https://github.com/NativeScript/marketplace-feedback/blob/master/docs/verified-plugins.md)

As NativeScript is an open source project I am also marking your request as a feature. Anyone interested can contribute and be a part of this initiative for creating VSCode (and/or other IDEs) repository for NativeScript extensions.

**Comment by vakrilov** [comment]
Closing this one, as it is not really actionable in the scope of this repo.
