### ISSUE TITLE
Binding Multiple expressions

### ISSUE THREAD

**Issue by LorenDorez** [NativeScript/NativeScript#5144]
Is there a way to do bind using multiple expressions?

the docs show this as an example

```
<Page>
    <StackLayout>
        <TextField text="{{ testDate, testDate | dateConverter('DD.MM.YYYY') }}" />
    </StackLayout>
</Page>
```

if i wanted to add some text before the binding like 'Date: ' how would this be done? I tried to no avail

```
<Page>
    <StackLayout>
        <TextField text="{{ testDate, 'Date: ' + (testDate | dateConverter('DD.MM.YYYY')) }}" />
    </StackLayout>
</Page>
```

**Comment by tsonevn** [comment]
Hi @LorenDorez,
In your case, you could use the FormattedString functionality, which is described in the [documentation](https://docs.nativescript.org/cookbook/formatted-string-ng).
you could define two Spans one for the static text and another for the data, which will be changed. For example:
```
<Label.formattedText>
                <FormattedString>
                    <FormattedString.spans>
                        <Span text="Date: " fontWeight="Bold"></Span>
                        <Span text="{{'Date:' + testDate, testDate | dateConverter('DD.MM.YYYY') }}"></Span>
                    </FormattedString.spans>
                </FormattedString>
            </Label.formattedText>
        </Label>
```
