### ISSUE TITLE
NativeScript's Intellisense (Android) - is not showing some methods?

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/NativeScript#5146]
Using WebStorm, I have a `Progress` element : 

    <Progress  id="prgressid" ></Progress>

I want to increase its height. It can be done via `scaleY=".."` attribute or [**via native code**][1] : 

    mProgressBar.setScaleY(3);

I've decided to do it via code but the intellisene shows me : 

[![enter image description here][2]][2]

[Another try without `.android.`](https://i.stack.imgur.com/J62o8.png)

 

It doesn't have the `setScaleY` method.   
(*if I try to use `setScale` method - it fails at runtime - But if I try `setScaleY` - it does work.*)

**Question:** 

Why isn't the method shown ? And what should I see in order to see all accessible methods ?

`tns info` : 

[![enter image description here][4]][4]

 [Sdk manager](https://i.stack.imgur.com/KzGJO.png)

  [1]: https://stackoverflow.com/a/27301074/859154
  [2]: https://i.stack.imgur.com/aTUVj.png
  [3]: https://i.stack.imgur.com/J62o8.png
  [4]: https://i.stack.imgur.com/yzZnd.png

**Comment by tsonevn** [comment]
Hi @RoyiNamir,
Thank you for contacting us.
I reviewed the [API reference](https://docs.nativescript.org/api-reference/classes/_ui_progress_.progress)  for the Progress component and found that similar method as `setScale` do not exist at this time. 
In case you need to change the height of the component from code behind, you could access and change the value of the height property. For example:
```
progress.height
```

**Comment by RoyiNamir** [comment]
@tsonevn 

Ok. BTW ...` (...).android.setScaleY(3)` did work. I was just wondering about the intellisense. Thank you. ( like always).
