### ISSUE TITLE
[Question] [Android] Can't extend an abstract class notificationListenerService inside my ts file ?

### ISSUE THREAD

**Issue by batout** [NativeScript/NativeScript#5149]
I working on an application that should read all the mobile notifications on get posted,
I've tried to extend the NotificationListenerService and override the onNotificationPosted method put nothing happens when the mobile receives a notification.

    `android.service["notification"]["NotificationListenerService"].extend({
        onNotificationPosted : function(sbn) {
            this.super.onNotificationPosted(sbn);
            console.log("got it");
            console.log(sbn.getNotification().tickerText);
        },
        onCreate: function() {
            this.super.onCreated();
            console.log("Created");
        })`

is any tutorial to extend an abstract class?

**Comment by jogboms** [comment]
@batout see an example [here](https://github.com/NativeScript/nativescript-geolocation/blob/master/demo/app/background-service.ts)

**Comment by tsonevn** [comment]
Hi @batout,
Did you resolve your case with the extending the `notificationListenerService ` while following the provided link by @jogboms
