### ISSUE TITLE
CSS Style Property "z-index"

### ISSUE THREAD

**Issue by bfattori** [NativeScript/NativeScript#515]
I know that `z-index` is a web specific property, but I was thinking today about using an `AbsoluteLayout` to handle the positioning of elements in a view. One of the things that I'm thinking could potentially be a problem is z-indexing. Defining the items in source-order will probably function as a stop-gap, but I was wondering if I were to position a floating element higher in the order, and then a background element lower down in the order, would it overlap the floating element?

I haven't tried this myself - just thinking out loud.

**Comment by rclai** [comment]
I'm trying to create a dropdown menu in iOS by using an `AbsoluteLayout` and using the animation framework to make it show, however, I cannot get it to show up in front of everything. How do I make it go in front of things?

**Comment by stevetayloruk** [comment]
+1

**Comment by hshristov** [comment]
I think z-index could be added but it won't help with dropdown menu. You can implement it now using AbsoluteLayout added as a last child in the root view. Then change its visibility.

**Comment by stevetayloruk** [comment]
@rclai please see here: #1222

**Comment by patrickseda** [comment]
+1 ... Having z-index is **critical** for more advanced UI. Most "business" apps won't ever need it, but when you get into dynamically-generated or gesture-based controls, it is a _must have_.

**Comment by terreb** [comment]
z-index doesn't work in 2.0.0. Please try this xml:

`<Page xmlns="http://schemas.nativescript.org/tns.xsd" >
    <AbsoluteLayout>
      <GridLayout zIndex="99" height="100" width="100" backgroundColor="red"></GridLayout>
      <GridLayout zIndex="1" height="200" width="200" backgroundColor="green"></GridLayout>
    </AbsoluteLayout>
</Page>`

The red rectangle should be on top, but it's hidden behind the green one or am I doing something wrong?

**Comment by FireSt-dead** [comment]
This works in 2.2.0 with angular 0.3.0:
```
<Image class="asignee" *ngFor="let assignee of issue.assignees; let i = index" [index]="i" [src]="assignee.avatar_url" [style.zIndex]="-i"></Image>
```

**Comment by prolink007** [comment]
I am still not able to get this to work. Why is this issue closed?

**Comment by sittingbool** [comment]
I agree, where is the problem in that?

**Comment by mudlabs** [comment]
At current zIndex appears to be constrained to its parent container. Not the page.

```xml
<!-- Just Ignoring that the desired layout can be achieved by other means.  -->
<Page>
    <Label id="topZ" text="Be on top" />
    <AbsoluteLayout>
        <Label text="Middle is best" />
        <Label id="bottomZ" text="Be on bottom" />
    </AbsoluteLayout>
</Page>
```
```css
/*
Also assume other styles have been added to push the AbsoluteLayout Labels 
beyond there container. Overlapping the #topZ Label.
*/
#topZ { z-index: 1; }
#bottomZ { z-index: 0; }
```
The z-index applied to `#topZ` has no impact on its rendering relative to the other Labels. So it will still appear below both other Labels

I think zIndex should be treated at the page/global level. This would make it easer to have more complex pages where items overlap.

`{N} 3.4.1`

**Comment by tdrdimov** [comment]
Changing the order of the elements inside the StackLayout tag fixed things for me. No need of z-index at that point!
