### ISSUE TITLE
HtmlView css - background cover not working

### ISSUE THREAD

**Issue by TimHawkHodg** [NativeScript/NativeScript#5159]
## Please, provide the details below:

I am using an HtmlView in my app and would like to enable a background-color that spans the entire screen. However upon rendering on an iOS device, it only is the background-color for it's child elements.

[Here is a link to how the background is rendering.](https://s3.amazonaws.com/stretchflex-templates/606518AB-A625-4186-A516-8A6D53D76817.png)

[This is how the code renders in a browser](http://scratchpad.io/damaging-hands-6366)

Yes I have searched both SO and git for an answer to this problem to no avail.

### Which platform(s) does your issue occur on?
iOS (Have not tried Android)

### Please provide the following version numbers that your issue occurs with:
    "nativescript-angular": "^3.1.2",
    "tns-core-modules": "^3.3.0",
    CLI: 3.4.0-2017

### Please tell us how to recreate the issue in as much detail as possible.

[Follow this approach to making an html view.](https://docs.nativescript.org/angular/code-samples/ui/htmlview)

Then add the markup below to this.htmlString:

```
<style>
        .full-back {
            background-color: #95a5b8;
            background-repeat: no-repeat;
            background-size: cover;
        }
        .hero {
            background-size: cover;
            color: #fff;
            height: 27.34375vw;
            max-height: 350px;
            position: relative;
        }
</style>
<div class="full-back">
      <div class="hero">
            <div>
                 <h1>Privacy Policy</h1>
             </div>
       </div>
</div>
```

**Comment by tsonevn** [comment]
Hi @TimHawkHodg,
The HtmlView component provides some limited support for the content styling, which also is related to your case.  The height property will not be set up and the background-color will be applied only on the to the text
Regarding that, I would recommend using [WebView ](https://docs.nativescript.org/angular/code-samples/ui/web-view#web-view-html) component, which will render all of the needed HTML content and its styling.

**Comment by TimHawkHodg** [comment]
@tsonevn I appreciate the support. We have explored the web view and concluded that it was not an option in our use case.

Is it possible to do a hybrid XML and HTML view?

<ScrollView orientation="vertical">
    <StackLayout orientation="vertical" height="200">
            <Label text="Privacy Policy" class="background-full"></Label>
     </StackLayout>
    <HtmlView [html]="htmlString"></HtmlView>
</ScrollView>

My stack layout and label does not render in this scenario.

**Comment by tsonevn** [comment]
HI @TimHawkHodg,
In case you need to show multiple elements inside a ScrollView you need to setup the HtmlView and the ScackLayout inside another Layout(StackLayout GridLayout). For Example:
```
<ScrollView orientation="vertical">
<StackLayout>
    <StackLayout orientation="vertical" height="200">
            <Label text="Privacy Policy" class="background-full"></Label>
     </StackLayout>
    <HtmlView [html]="htmlString"></HtmlView>
</StackLayout>
</ScrollView>
```
