### ISSUE TITLE
Ability to manipulate the Android and iOS status bar

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#516]
Right now the status bar inherits the colour from it's ActionBar/NavigationBar. This is not so great when you have a hidden ActionBar.

It would be great to be able to hide the status bar or add custom colours to it. 

CSS property suggestions:
* color
* background-color

**Comment by lscown** [comment]
Would be great to have the status bar transparent as well. This goes for both iOS and Android (I believe the Android one overlays the background content.) #601

**Comment by enchev** [comment]
Merged with https://github.com/NativeScript/NativeScript/issues/601
