### ISSUE TITLE
Bug  : Incorrect `///<reference` path values 

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/NativeScript#5160]
When doing `tns create MyApp --ng` , 

project is created with 

![image](https://user-images.githubusercontent.com/2842123/33852566-b47c38c4-dec3-11e7-89b9-41af00c134c0.png)

And that file contains : 

```
/// <reference path="./node_modules/tns-platform-declarations/ios.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/android.d.ts" />
```

Now this is incorrect value.
becuase triple slash starting with `./` are relative and there is no such files there. ( io.d.ts etc...)

this is causing problems like the one I've asked aboutr  :

https://stackoverflow.com/questions/47757276/reference-path-to-node-modules-is-not-found

**Comment by NickIliev** [comment]
@RoyiNamir thank you for reporting this issue - to temporary resolve the issue remove the `references.d.ts` file from your `node_modules/tns-core-modules` folder.

Logging this one as a bug. Steps to reproduce:
- create sample application
- in tns-core-modules there is a references.d.ts file causing some IDEs to fail with TS error
```
TS6053: File 'c:/NS/pre-dev/NS-developmentGroceriesV2/node_modules/tns-core-modules/node_modules/tns-platform-declarations/android.d.t.s' not found
```

**Comment by RoyiNamir** [comment]
@NickIliev Oh my god. I thought it was a problem on my side. I've spent 3 hours on this :-)
Good thing to know that my environment was ok. ( some suggested me to switch to vscode ) hahaha

**Comment by NickIliev** [comment]
@RoyiNamir indeed the thing is the WebStorm is making its checks which are leading to the TS error.
In VSCode this error is not reproducible because the IDE is not making custom check but respecting the project's `tsconfig.json` file where the `node_modules` folder is excluded from TypeScript transpilation.

I have no idea why WebStorm is not respecting this option so switching to VSCiode is indeed an option ;)

**Comment by RoyiNamir** [comment]
@NickIliev But this value  : `<reference path="./node_modules/tns-platform-declarations/ios.d.ts" />` is **wrong**.

So transpilling or not - there is no way to resolve that relative path ( unless it's on the root). Right ?

**Comment by NickIliev** [comment]
@RoyiNamir you are right, and **this is still a bug** (the `references.d.ts` file should not be located in `tns-core-modules`). 

Just pointing out that this won't be a stopper if your `tsconfig.json` is respected by the IDE (the difference between VSCode and WebStorm) and you have the following in this file:
```
"exclude": [
    "node_modules",
    "platforms",
    "**/*.aot.ts"
]
```

As the file (`node_modules/tns-core-modules/references.d.ts`) is actually never used the error is only observed during the TypeScript transpilation and won't lead to runtime errors.So in your case WebStorm is causing the buuild time error as it is not repscting the above option in `<project-name>/tsconfig.json`

**Comment by RoyiNamir** [comment]
I think that there is another related bug : 

When I installed both tns-platforms and declerations : NONE of the installations added those two lines (which is mandatory) : 

https://i.imgur.com/WLr4QjJ.jpg
![image](https://user-images.githubusercontent.com/2842123/33872164-6348cd86-df1e-11e7-9f0d-d02582ea1f3d.png)

Only the first line was there. 

What i'm trying to say is that when installing declarations - the file should be added with those two lines.
That's all.

**Comment by RoyiNamir** [comment]
OOPS I accidently closed this .

How can I reopen it ? sorry about that.

**Comment by RoyiNamir** [comment]
@NickIliev @tsonevn Updating : it's not a Webstrom Bug.

I've asked here : 
https://youtrack.jetbrains.com/issue/WEB-30225

It all begins becuase the root `referenes.d.ts` links to `tns-core-modules`  where there is seeks for future references inside the file and there it sees this invalid relative path.

**Comment by NickIliev** [comment]
@RoyiNamir that said you can safely remove the root references.d.ts link to tns-core-modules as it is not needed.

**Comment by RoyiNamir** [comment]
@NickIliev  If I remove this root file , then I don't have definitions  and it fails to compile : 

![image](https://user-images.githubusercontent.com/2842123/33888602-3c6125b4-df56-11e7-8680-9927a60a381d.png)

**Comment by RoyiNamir** [comment]
Update : 

[After reading this thread](https://stackoverflow.com/a/40861142/859154) I've added to the TS.config file : 
```
 "files": [

    "./node_modules/tns-platform-declarations/android.d.ts",
    "./node_modules/tns-platform-declarations/ios.d.ts"
  ]
```

and removed  `references.d.ts` from root. 
It all works. ( I know it's the same)

But please tell me i'm not insane -  NS's third party librarys which needs NSObject/android - must have definitions and they will have it from those 2 files.

Am I right ?

**Comment by NickIliev** [comment]
@RoyiNamir all plugins are transpiled from TS to JS, then NPM packed, and the install files are pure JavaScript. So you do not need tns-platform-declarations (the declaration files are needed only for TypeScript transpilation of TS files to JS files). So if you are using tns-platform-declarations in development use the workflow described [here](https://www.npmjs.com/package/tns-platform-declarations), and you are good to go. 

Do not forget to always install tns-platform-declarations as **devDependency** as you do not need this enormously big files in your project (once again they are only needed in development to transpile TS to JS).

e.g.
```
tns create myAngularApp --ng
npm i tns-platform-declarations --save-dev
```
- then create 'references.d.ts' located in in `myAngularApp/references.d.ts` and add the following
```
/// <reference path="./node_modules/tns-platform-declarations/ios.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/android.d.ts"
```

Many authors of plugins are using TypeScript as the development language, and they need `references.d.ts` during the development process of the plugin (or even if you use JavaScript the declaration file will still bring IntelliSense) but after the plugin is ready the TypeScript files are transpiled to JavaScript (using `tsc`) and then the *.tgz file is created with `npm pack`. The TypeScript files should be excluded from the NPM (example how this is done [here](https://github.com/NativeScript/nativescript-camera/blob/master/src/.npmignore)), and the source of the plugin, in the end, will contain only JavaScript files.

**Comment by RoyiNamir** [comment]
@NickIliev  To tell you the truth , I read 200 times this thread here. (I'm not that new to ts).
But when I created a simple new ng project demo with the instructions you gave me (including adding the references.d.ts to the root) - evrything works. **BUT** When I navigate to a spcific folder ( and only this folder) - it tries to find `android` and it doesn't know it ALTHOUGH I put the root references.d.ts


I'm attaching a sample project.

https://ufile.io/e6fvm
(i'm using `tns run android`)


If you navigate to that folder and open that file - you'll see the error. ( which shouldnt be happening since there are d.ts files at root).

![image](https://user-images.githubusercontent.com/2842123/33901851-c99f712c-df7b-11e7-8cde-c45a5807ed98.png)

**Comment by NickIliev** [comment]
@RoyiNamir this is simply a design fault by the author of the wrapped plugin ([@spartadigital/nativescript-permissions](https://www.npmjs.com/package/@spartadigital/nativescript-permissions)). In comparison using the [nativescript-permissions](https://github.com/NathanaelA/nativescript-permissions) by @NathanaelA does not have such issue.

You can easily resolve this issue by correcting the path of the reference for the plugin as follows:

**_node_modules/@spartadigital/nativescript-permissions/references.d.ts_**
```
/// <reference path="../../tns-platform-declarations/ios.d.ts" />
/// <reference path="../../tns-platform-declarations/android.d.ts" />
```

However, keep in mind that this would require that your project has installed tns-platform-declarations (which you have already added as a devDependency).

**Comment by RoyiNamir** [comment]
@NickIliev @tsonevn  I don't know how to reach you but I think I created a useful feature where you can add to NSNG.

Regarding finding a solution for `setTimeout`  , or in other words : "_how to get rid of setTimeout for view to be ready for measure_"  

**problem** is shown here : https://play.nativescript.org/?template=play-ng&id=rf8Aok (edited)

**Solution(!) is shown here.** ( notice the times) https://play.nativescript.org/?template=play-ng&id=uJnwGx&v=2
