### ISSUE TITLE
Validate form with javascript

### ISSUE THREAD

**Issue by wuilmerj24** [NativeScript/NativeScript#5162]
How can I validate the form for login with the fields of mail and password

**Comment by tsonevn** [comment]
Hi @wuilmerj24,
In your case, you could use `nativescript-pro-ui` plugin and its RadDataForm control.
More about it could be found here in the plugin's [documentation](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/DataForm/dataform-overview).
