### ISSUE TITLE
[iOS] Missing ARKit properties

### ISSUE THREAD

**Issue by andreacappadona17** [NativeScript/NativeScript#5164]
I'm trying ARKit combined with Vision in a NativeScript app, but when I try to access some properties like `transform` from [ARCamera](https://developer.apple.com/documentation/arkit/arcamera).

Looking through the docs, I found out that 

>The following members can not be accessed from JavaScript:
>
> * Unions
> * Variadic Objective-C methods, function pointers, blocks
> * Structs with constant size array members
> * Vectors
> * Inline functions
> *  int64_t, uint64_t outside the [-2^53, 2^53] range
> *  long double, int128_t, uint128_t

Is there no way to bypass this limitation? Am I doing something wrong?

Thanks

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/ios-runtime#836
