### ISSUE TITLE
Loaded event before ngOnInit

### ISSUE THREAD

**Issue by bori87** [NativeScript/NativeScript#5166]
When i'm navigating from page A to page B then going back to page A i'm reciving errors. I noticed that Loaded event from the view is firing before ngOnInit.  

![err1](https://user-images.githubusercontent.com/29092029/33903175-c24b8202-df77-11e7-8672-555cadec8b49.png)

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1123
