### ISSUE TITLE
TimerPicker keeps showing all minutes in Android

### ISSUE THREAD

**Issue by Macarthurval** [NativeScript/NativeScript#5167]
### Tell us about the problem
The timePicker minuteInterval property doesn't work properly on Android, the timePicker keeps showing all minutes, although the spinner jumps to the correct interval minute when spin move it.

`timePicker.minuteInterval = 15`

<img width="432" alt="captura de pantalla 2017-12-12 a la s 19 07 17" src="https://user-images.githubusercontent.com/30457050/33915164-dea2b98c-df6f-11e7-9620-b58bebefa1bd.png">

And another issue, I cannot access to `timePicker.android`, it returns `undefined`.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.3.0
- Cross-platform modules: 3.3.0
- Runtime(s):
  ios: 3.2.0
  android: 3.3.1
- Plugin(s): 
"base-64": "^0.1.0",
    "crypto-js": "^3.1.9-1",
    "email-validator": "^1.1.1",
    "nativescript-background-http": "^3.1.0",
    "nativescript-barcodescanner": "^2.7.1",
    "nativescript-camera": "^3.1.3",
    "nativescript-custom-entitlements": "^0.2.0",
    "nativescript-drop-down": "^3.2.0",
    "nativescript-email": "^1.5.1",
    "nativescript-facebook": "^2.0.1",
    "nativescript-geolocation": "^3.0.1",
    "nativescript-google-maps-sdk": "^2.4.0",
    "nativescript-gradient": "^2.0.1",
    "nativescript-imagepicker": "^4.0.1",
    "nativescript-ios-uuid": "^1.0.0",
    "nativescript-iqkeyboardmanager": "^1.1.0",
    "nativescript-phone": "^1.3.1",
    "nativescript-pro-ui": "^3.1.4",
    "nativescript-pulltorefresh": "^2.0.2",
    "nativescript-push-notifications": "^0.1.4",
    "nativescript-slides": "^2.2.12",
    "nativescript-socket.io": "^0.9.0",
    "nativescript-sound": "^1.0.4",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-web-image-cache": "^4.2.2",
    "tns-core-modules": "^3.3.0",
    "utf8": "^2.1.2"

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

XML
`<TimePicker id="time-picker" class="picker"/>`

JS
```
timePicker = page.getViewById("time-picker");
timePicker.minuteInterval = 15;
```

**Comment by tsonevn** [comment]
Hi @Macarthurval,
Thank you for reporting this issue. I tested it on my side and need this seems to a valid issue for Android. However, at this time there is no easy way, which could help to workaround this issue.
Regarding that similar issue is already logged [here](https://github.com/NativeScript/NativeScript/issues/4662). Let's keep the conversation in the old one. 
About the accessing the native part of the TimePicker, you could access it on the component loaded event. For example:
XML
```
<TimePicker loaded="tploaded"  hour="9" minute="35"  id="time-picker" class="picker"/>
```
TypeScript

```
import { EventData } from 'data/observable';
import { Page } from 'ui/page';
import { HelloWorldModel } from './main-view-model';
import {TimePicker} from "ui/time-picker"
import {isIOS} from "platform"
// Event handler for Page "navigatingTo" event attached in main-page.xml
export function navigatingTo(args: EventData) {

    let page = <Page>args.object;
    

    page.bindingContext = new HelloWorldModel();
}

export function tploaded(args){
var tm:TimePicker = <TimePicker>args.object;
console.log(tm.android)
}
```
