### ISSUE TITLE
Javascript textField

### ISSUE THREAD

**Issue by wuilmerj24** [NativeScript/NativeScript#5168]
How to change the border color of a textField from javascript

**Comment by NickIliev** [comment]
@wuilmerj24 

Use `borderWidth` and `borderColor` properties.

e.g.
```
function onNavigatingTo(args) {
    var page = args.object;

    var tf = page.getViewById("tf");

    tf.borderWidth = 3;
    tf.borderColor = "red";
}
```

Demo **NativeScript Playground** project demonstrating the above can be found [here](https://play.nativescript.org/?template=play-js&id=RzKj0o)

**Comment by wuilmerj24** [comment]
can a modal be closed from the page where the modal opens?
