### ISSUE TITLE
1.2.1 upgrade causes file enum error on iOS

### ISSUE THREAD

**Issue by maknz** [NativeScript/NativeScript#517]
After upgrading our project from 1.1 to 1.2.1, our iOS builds broke with the following error. Android is fine.

```
/app/tns_modules/file-system/file-system.js:314:24: JS ERROR Error: Failed to enum files for folder '/Users/user/Library/Developer/CoreSimulator/Devices/blah/data/Containers/Bundle/Application/blah/mobile.app/app/views/main/': Error: Actual arguments count: "1". Expected: "2". 
1   0x1040d22ae NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x1046818e9 ffi_closure_unix64_inner
3   0x1046846de ffi_closure_unix64
4   0x1053b53ce -[UIViewController view]
5   0x1052d0289 -[UIWindow addRootViewControllerViewIfPossible]
6   0x1052d064f -[UIWindow _setHidden:forced:]
7   0x1052dcde1 -[UIWindow makeKeyAndVisible]
8   0x10468455c ffi_call_unix64
9   0x7fff5bb5ff80
(lldb)
```

Our app.js looks like:

```
var application = require("application");
application.mainModule = "views/main/main";
application.cssFile = "./app.css";
application.start();
```

And folder structure:

![screen shot 2015-07-30 at 12 49 39 pm](https://cloud.githubusercontent.com/assets/992356/8973522/adc48108-36b9-11e5-8dd9-96a94e5baeb1.png)

We build our project by opening our `.xcworkspace` in Xcode, running `tns prepare ios` and pressing play in Xcode, as we need Cocoapods as part of the build process, as discussed [here](https://docs.nativescript.org/runtimes/ios/native-libs/CocoaPods). This was of course working fine in 1.1.

To upgrade to 1.2, we upgraded the `nativescript` global node package, `tns platform update ios` and `tns platform update android`, and dumped the new `tns_modules` folder in.

**Comment by maknz** [comment]
I noticed that the `tns_modules` folder went walkabout, so I figured that user error was the cause here... except, the crash still persists on iOS, despite a fresh `tns prepare ios`.

**Comment by paranoid-android** [comment]
I'm experiencing the same issue. I have not figured out how to work around it. @maknz have you had any luck?

**Comment by maknz** [comment]
No, unfortunately. But glad to hear it's not just us (and our DIY build process).

**Comment by Nathanaela** [comment]
One thing I have had to do a couple times (I mess around a lot with custom components).    Is reinstall the Ios or android platforms.    Not sure if you are aware but the xcode project file gets replaced when you upgrade.   This might be causing you issues.

One thing you can try is; rename your platform/ios folder to platform/ios_old
then do a "tns platform add ios"
Then copy the pieces (i.e.. the cocoapods) to your new ios folder; and re-install them in your project file and see if that fixes your issue.  If it does, then nuke your old ios_old folder as you don't need it any more.

**Comment by maknz** [comment]
A fresh `tns platform add ios` and reinstalling Pods seems to have fixed it, the app now starts up. It would be good to find out what caused this.

**Comment by maknz** [comment]
Okay, so Git indicates the following files ended up with changes after the platform re-add:

```
modified:   platforms/ios/metadataGenerator/bin/metadata-generation-build-step.sh
modified:   platforms/ios/metadataGenerator/bin/objc-metadata-generator
modified:   platforms/ios/mobile.xcodeproj/project.pbxproj
modified:   platforms/ios/mobile/TNSDebugging.h
modified:   platforms/ios/mobile/main.m
```

TNSDebugging.h and main.m have significant changes. Perhaps these need to get fixed up when a platform update is done?

**Comment by enchev** [comment]
This issue was moved to NativeScript/ios-runtime#253
