### ISSUE TITLE
keyboard event textField javascript

### ISSUE THREAD

**Issue by wuilmerj24** [NativeScript/NativeScript#5170]
add keyboard event in  textfield

**Comment by tsonevn** [comment]
Hi @wuilmerj24,
You could set up the event via the UI while providing the event name and the name of the callback method. 
```
<TextField autocorrect="false" text="test" tap="testTap" />
```

JavaScript
```
exports.testTap= function (){
console.log("test tap event")
}
```
For further "How to" question, please use our [forum ](https://discourse.nativescript.org/) channel or [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript). This repository should be used only for bug reporting and feature requests.
