### ISSUE TITLE
App crashes only on iOS 9 when changing Tabs using *ngIf and binding to SelectedIndex

### ISSUE THREAD

**Issue by smartsanja2013** [NativeScript/NativeScript#5178]
### Which platform(s) does your issue occur on?
iOS (only on ios 9.x)

### Please provide the following version numbers that your issue occurs with:
tns version 3.3.1
package.json version 3.3.0
ios version on package.json 3.0.0

### Please tell us how to recreate the issue in as much detail as possible.
I have tab bar app.
There are 3 tabs
I am changing the action bar buttons based on the current selected tab index.
App crashes **only on iOS 9.x** (both simulator and real device) due to **array out of bound index error.**
Crash happens when selecting the tabs (eg: tap on 2nd tab and then try to select 1st tab, app crash)
Please see the code snippets and xCode error bellow

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Tabs.component.html
```
<ActionBar [title]="title" class="action-bar" actionBarHidden="false" backgroundColor="#f33" >
    <NavigationButton visibility="collapsed"></NavigationButton>
    <ActionItem *ngIf="tabIndex!=1" (tap)="searchBtnTapped()" android.systemIcon="ic_menu_search" ios.systemIcon="12" ios.position="right"></ActionItem>
    <ActionItem *ngIf="tabIndex==2" (tap)="plusBtnTapped()" android.systemIcon="ic_input_add" ios.systemIcon="4" ios.position="right"></ActionItem>
    <ActionItem *ngIf="tabIndex==1" (tap)="deleteBtnTapped()" ios.systemIcon="16" android.systemIcon="ic_delete" ios.position="right"></ActionItem>
    <ActionItem (tap)="userBtnTapped()" android.systemIcon="ic_input_add" ios.systemIcon="4" ios.position="left"></ActionItem>
</ActionBar>

```

Tabs.component.ts

```
onSelectedIndexChanged(args: SelectedIndexChangedEventData) {
        const tabView = <TabView>args.object;
        const selectedTabViewItem = tabView.items[args.newIndex];

        this.title = selectedTabViewItem.title;
        this.tabIndex = tabView.selectedIndex;
    }
```

Xcode error
<img width="858" alt="screen shot 2017-12-16 at 10 34 16 am" src="https://user-images.githubusercontent.com/12458727/34066900-6a79e9aa-e252-11e7-87d0-9ca561202bfb.png">

**Comment by NickIliev** [comment]
@smartsanja2013 confirming this as a bug on iOS 9.x.

As a temporary workaround, we can use **visibility** instead of an Angular structural directive.

For example:
```
<ActionBar title="My Title" class="action-bar" actionBarHidden="false" backgroundColor="#f33" >
    <NavigationButton visibility="collapsed"></NavigationButton>
    <ActionItem [visibility]="tabIndex!=1 ? 'visible' : 'collapsed'" ios.systemIcon="12" ios.position="right"></ActionItem>
    <ActionItem [visibility]="tabIndex==2 ? 'visible' : 'collapsed'" ios.systemIcon="4" ios.position="right"></ActionItem>
    <ActionItem [visibility]="tabIndex==1 ? 'visible' : 'collapsed'" ios.systemIcon="16" ios.position="right"></ActionItem>
    <ActionItem ios.systemIcon="4" ios.position="left"></ActionItem>
</ActionBar>
```

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#1126
