### ISSUE TITLE
TypeScript compiler failed with exit code 1

### ISSUE THREAD

**Issue by KayUOM** [NativeScript/NativeScript#5179]
When i run the application it crashes with the following error code:

> tns run android
> Searching for devices...
> Starting Android emulator with image Pixel_API_26
> Waiting for emulator device initialization.....
> Skipping prepare.
> Building project...
> Gradle build...
>          + applying user-defined configuration from /var/www/mobile/app/App_Resources/Android/app.gradle
>          + creating include.gradle for plugin /var/www/mobile/node_modules/tns-core-modules-widgets
>          + applying plugin configuration from /var/www/mobile/platforms/android/build/configurations/tns-core-modules-widgets/include.gradle
>          + adding nativescript runtime package dependency: nativescript-optimized
>          + adding aar plugin dependency: /var/www/mobile/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar
> Running full build
> Project successfully built.
> Installing...
> Successfully installed on device with identifier 'emulator-5554'.
> Successfully transferred all files.
> Refreshing application...
> Successfully synced application org.nativescript.mobile on device emulator-5554.
> Executing before-watch hook from /var/www/mobile/hooks/before-watch/nativescript-dev-typescript.js
> Found peer TypeScript 2.4.2
> ActivityManager: Start proc 3442:org.nativescript.mobile/u0a85 for activity org.nativescript.mobile/com.tns.NativeScriptActivity
> fs.js:1376
>     throw error;
>     ^
> 
> Error: watch /var/www/mobile ENOSPC
>     at _errnoException (util.js:1024:11)
>     at FSWatcher.start (fs.js:1374:19)
>     at Object.fs.watch (fs.js:1400:11)
>     at Object.watchDirectory (/var/www/mobile/node_modules/typescript/lib/tsc.js:2394:32)
>     at Object.executeCommandLine (/var/www/mobile/node_modules/typescript/lib/tsc.js:58090:43)
>     at Object.<anonymous> (/var/www/mobile/node_modules/typescript/lib/tsc.js:58450:4)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)
> 
> TypeScript compiler failed with exit code 1
> 

1. tns create myapp --ng
2. tns run android

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
-node: v8.9.3
-npm: 5.5.1
- CLI: 3.3.1

┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 3.3.1           │ 3.3.1          │ Up to date    │
│ tns-core-modules │ 3.3.0           │ 3.3.0          │ Up to date    │
│ tns-android      │ 3.3.1           │ 3.3.1          │ Up to date    │
│ tns-ios          │                 │ 3.3.0          │ Not installed │

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.mobile",
    "tns-android": {
      "version": "3.3.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.4.1",
    "@angular/common": "~4.4.1",
    "@angular/compiler": "~4.4.1",
    "@angular/core": "~4.4.1",
    "@angular/forms": "~4.4.1",
    "@angular/http": "~4.4.1",
    "@angular/platform-browser": "~4.4.1",
    "@angular/router": "~4.4.1",
    "nativescript-angular": "~4.4.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.2",
    "tns-core-modules": "^3.3.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.5.0",
    "typescript": "~2.4.2"
  }
}

```

**Comment by tsonevn** [comment]
Hi @KayUOM,
Thank you for contacting us. 
I review your case, however, was unable to recreate the same problem while using the provided steps. 
Regarding that provided log I found that an `ENOSPC` error is thrown, which means that there is no space on the drive. You could try to free some space on the emulator and to try again deploying the app.
For further info about the problem and possible solutions, you could also review[ this thread ](https://stackoverflow.com/questions/22475849/node-js-error-enospc) in StackOverflow. 

Let me know if I could assists you further.

**Comment by KayUOM** [comment]
The solution provided in the stackoverflow thread fixed my problem.
