### ISSUE TITLE
Add support for platform specific css rules for multiple platforms in the same file

### ISSUE THREAD

**Issue by erkanarslan** [NativeScript/NativeScript#5180]
This is a feature request.

In current situation, we need to create a css file for common rules and 2 files for android and iOS specific rules even if it is just a few lines. Also if you create a platform specific css file you have to create another file for other platform even if you put nothing in it, otherwise angular or file import codes will complain about the missing file.

To solve this problem, allow us to define platform specific css rules in the same file. Maybe we can use media queries for this. For example, when developing for web, you can define different css rules based on screen resolution and whether it is for screen or print. For Nativescript, we can check the platform in media queries.

**Comment by tsonevn** [comment]
Hi @erkanarslan,
Thank you for contacting us.

If I understand you correctly you would like  NativeScript to support for [CSS media queries](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Media_queries) in the CSS.
If this is correct, we have already similar issue logged here. Regarding that, you could vote for this feature on the other issue and we could close this one. 

Let me know if the case is different and I will reopen this issue.

**Comment by erkanarslan** [comment]
@tsonevn If you are talking about issue #64, that is not what I am requesting. In that issue, media queries are requested for different device resolutions. Here I want it for applying different styles to android and ios devices. Example:

````
@media (platform : android) {
    Label { text-align : left; } 
}
````

**Comment by tsonevn** [comment]
Hi @erkanarslan,
Excuse me I missed to attached the issue in my previous comment.
Indeed I was toking about issue #64. The issue describes the support of the @media rule in its general use case, however, you could add your case as a comment in the old issue, while providing the same example.
It would be better to keep the this feature request in one issue.

**Comment by NathanaelA** [comment]
@erkanarslan - My `Nativescript-Platform-css` does this:
```
.android LABEL { text-align: left; }
```

https://plugins.nativescript.rocks/plugin/nativescript-platform-css
