### ISSUE TITLE
WebView is still alive after page leave on iOS

### ISSUE THREAD

**Issue by gerfigna** [NativeScript/NativeScript#5189]
### Which platform(s) does your issue occur on?
iOS

### version numbers
- CLI:  3.3.1
- Cross-platform modules: 3.1.1
- Runtime(s): "tns-ios": "3.3.0"
- Plugin(s): none

### Please tell us how to recreate the issue in as much detail as possible.
Each time I navigate and go back from a page containing a WebView, it's created a new instance of it that is never destroyed

![screenshot](https://user-images.githubusercontent.com/2639926/34164282-6ef48718-e4d9-11e7-9eb8-6bfa044e7e3c.png)

### Code involved

**main-page.xml**
```
<Page loaded="pageLoaded">
  <ActionBar title="My App" class="action-bar"></ActionBar>
  <!-- Your UI components go here -->
  <Button text="Navigate to webview page" tap="tap" />
</Page>
```

**main-page.js:**
```javascript
var frameModule = require("ui/frame");

exports.tap = function() {
    var topmost = frameModule.topmost();
    topmost.navigate("views/webview/webview");
};
```
**app/views/webview/webview.xml**
```
<Page>
    <StackLayout orientation="vertical">
        <WebView id="webview" width="100%" height="100%" src="https://google.com"/>
    </StackLayout>
</Page>

```

I have created a repo with the code involved:
https://github.com/gerfigna/NativeHelloWorld

**Comment by tsonevn** [comment]
Hi @gerfigna,
Thank you for contacting us,
I tested your scenario, indeed on every navigation to the page, a new WebView instance will be created, which is expected. While navigating back the old instance will not be deallocated immediately. Those instances will be destroyed after a while automatically, when this memory is marked that could be cleaned up.
However, if you have a problem, which you think that could be caused by the above-mentioned case, please provide some more info.

**Comment by gerfigna** [comment]
Thanks @tsonevn ! In my real scenario, the webview loads a canvas with high resource consumption. When i have more than 2 webviews loaded, i get a very low performance level in the active webview.

Is there any way to destroy or unload it where te page is unloaded ?
 i.e. navigatedFrom, navigatedTo

**Comment by tsonevn** [comment]
Hi @gerfigna,
Thank you for the provided info about your case.
In the upcoming release, we have made some changes to the WebView component. Regarding that I would suggest to test our @next modules and to verify, whether you will have the same problem with the performance.  You could follow the below-attached steps:
1. `tns plugin remove tns-core-modules`;
2. `tns plugin add tns-core-modules@next`
3. remove the platform with `tns platform remove ios`;
4. `tns run ios`

If you still facing issues while using the next module, you could try to save an instance of the page, which contains the WebView and used it while navigating to it. In this case, the page and the WebView will be created on the first navigation. For this scenario, you could review the below-attached sample project.

> NB: the second approach is not very recommended, because the page will be kept alive in the whole time while the application is running and will be destroyed only when the application is closed.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/1575525/Archive.zip)

**Comment by gerfigna** [comment]
I have fixed the performance issue by loading a empty html document before leaving page

**Comment by tsonevn** [comment]
Hi @gerfigna,
I am glad to hear that you were able to resolve your issue. 

Let me know if I could assist you further.
