### ISSUE TITLE
'android' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by jjk3** [NativeScript/NativeScript#519]
when attempting

    tns platform add android

Command failed: C:\Windows\system32\cmd.exe /s /c "android list targets" 'android' is not recognized as an internal or external command,

**Comment by thstarshine** [comment]
Did you install Android SDK and set the PATH correctly?
You can follow the steps described here: 
http://docs.nativescript.org/setup/ns-cli-setup/ns-setup-win.html
