### ISSUE TITLE
If you delete the whole css data or the css file itself the changes are not going to be applied to the app

### ISSUE THREAD

**Issue by vhristov5555** [NativeScript/NativeScript#5196]
1. Create project
2. Open the app.css
3. Delete the whole data or delete the app.css
4. Save
Actual: The APP won't be refreshed with the changes
Expected: The APP to be refreshed with the changes
Comment: Test with js project. Also happens in Angular if you have only app.css

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-cli#3351
