### ISSUE TITLE
ES6 and ES7 features without babel transpiling?

### ISSUE THREAD

**Issue by mercmobily** [NativeScript/NativeScript#5199]
I just have a quick question, and I couldn't find it addressed anywhere.
I would love to use Javascript ES6 and ES7 syntax (especially async/await, my new best friends) without transpiling. Is that even an option? And _should_ it be an option?

It all depends on the sub-question: what Javascript engine does NativeScript effectively use, on Android and MacOs? Is it taken from the device itself? (in which case transpiling IS the only option...) Or is it provided by Native Script itself?

Thanks for listening...!

**Comment by NickIliev** [comment]
@mercmobily you can use async/await with TypeScript which will transpile the to ES5 (blog post [here](https://www.nativescript.org/blog/use-async-await-with-typescript-in-nativescript-today)). Currently, ES6 is not supported by both iOS and Android runtimes ([here](https://github.com/NativeScript/ios-runtime/issues/818#issuecomment-346065077)).

The topic has been discussed over the time ni  several issues - look [here ](https://github.com/NativeScript/NativeScript/issues/2882#issuecomment-253516404)and [here ](https://discourse.nativescript.org/t/ecmascript-6-es6-importing-problems/2927/20)for more details

SOlution for using async/await in NativeScript by using[ this community plugin](https://www.npmjs.com/package/nativescript-tslib)

**Comment by AshleyCao** [comment]
@NickIliev Hey, we are using typescript 2.6.2. Quote your saying 

> You can use TypeScript as from version 2.x.x TS is supporting await/async syntax and the code with being transpiled to ES5 which is the target for a NativeScript application. 

Our project is IOS based but it seems it doesn't like async function. It works fine on Android. 

Will it be something to do with the ts setting? 

Here is tsconfig.ts:
`{
    "compilerOptions": {
        "module": "commonjs",
        "target": "esnext",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "lib": [
            "es6",
            "dom"
        ],
        "baseUrl": ".",
        "paths": {
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
}`

If we changed target to es 5, async function works but some other functions don't perform as expected.
