### ISSUE TITLE
CSS bug: short form of "transform: translate" is incorrectly applied

### ISSUE THREAD

**Issue by sserdyuk** [NativeScript/NativeScript#5202]
According [mozilla](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translate), short notation `translate(-50)` can be used, and should applied as `translate(-50, 0)`. NS incorrectly interprets it as `translate(-50, -50)`.

I came across this issue due to how webpack and uglifier now rewrite CSS rules to shortest possible form, and it causes UI to break.

See related [webpack ticket](https://github.com/NativeScript/nativescript-dev-webpack/issues/377). 

```
$ tns create cssTranslateTest --tsc
$ cd cssTranslateTest/
$ echo 'button.btn {transform: translate(-50);}' >> app/app.css
$ tns run android
```
![image](https://user-images.githubusercontent.com/395998/34305947-a975b6fa-e70e-11e7-83b4-6fa6b1771d5a.png)

**Comment by NickIliev** [comment]
Confirming this one as a bug - the short property for `translate` is not rendering the recommended result 
Also related to [https://github.com/NativeScript/nativescript-dev-webpack/issues/377](https://github.com/NativeScript/nativescript-dev-webpack/issues/377)
