### ISSUE TITLE
error in tns doctor Android SDK 22

### ISSUE THREAD

**Issue by ZainAli1839** [NativeScript/NativeScript#5205]
E:\nativscript>tns doctor
NOTE: You can develop for iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later.

You need to have Android SDK 22 or later and the latest Android Support Repository installed on your system.
Run $ %ANDROID_HOME%\tools\android to manage the Android Support Repository.

Error executing command 'javac'. Make sure you have installed The Java Development Kit (JDK) and set JAVA_HOME environment variable.
You will not be able to build your projects for Android.
To be able to build for Android, verify that you have installed The Java Development Kit (JDK) and configured it according to system requirements as
 described in http://docs.nativescript.org/setup/ns-cli-setup/ns-setup-win.html#system-requirements

There seem to be issues with your configuration.
? Do you want to visit the official documentation? (Y/n)

**Comment by NickIliev** [comment]
@ZainAli1839 make sure that you have installed Java JDK 8 and have your `JAVA_HOME` environment variable set on your OS. Also, make sure that you have installed Android SDK and Android Support Repository as sugge4sted in the error log. If you have multiple Android SDK installations this might cause an issue - check if this is the case and leave only one SDK (if using Android Studio make sure that the SDK used by the IDE is the one set as `ANDROID_HOME`)

Closing this as the information from the error log is not enough to reproduce an issue.
