### ISSUE TITLE
Tab to only call ngOnInit when selected and not earlier?

### ISSUE THREAD

**Issue by TinusJ** [NativeScript/NativeScript#5209]
Hi,

i am trying to use ngOninit with a tabview, but on the tab component (Map) the ngOnInit gets called before the tab was even selected, Is this a bug or how could i work arround this?

TabView HTML

    <ActionBar class="action-bar">
    <Label class="action-bar-title fa" [text]="getTitle()"></Label>
</ActionBar>
    <TabView (selectedIndexChanged)="onSelectedIndexChanged($event)" class="fa" style="font-size: 25;">

    <StackLayout *tabItem="{title: '&#xf073;'}">
        <Event></Event>
    </StackLayout>
    <StackLayout *tabItem="{title: '&#xf000;'}">
        <Special></Special>
    </StackLayout>
    <StackLayout *tabItem="{title: '&#xf1ad;'}">
        <Bar></Bar>
    </StackLayout>
    <StackLayout *tabItem="{title: '&#xf279;'}">
        <Map></Map>
    </StackLayout>
</TabView>

Event will be the first Tab to open

TabView TS

  onSelectedIndexChanged(args: SelectedIndexChangedEventData) {
        const tabView = <TabView>args.object;
        const selectedTabViewItem = tabView.items[args.newIndex];

        this.title = selectedTabViewItem.title;
        this._selectedTab = args.newIndex;
    }

With the basics from the demo

Map TS

    ngOnInit(): void {
        geolocation.isEnabled().then(function (isEnabled) {
            if (!isEnabled) {
                geolocation.enableLocationRequest().then(function () {
                }, function (e) {
                    console.log("Error: " + (e.message || e));
                });
            }
        }, function (e) {
            console.log("Error: " + (e.message || e));
        });
    }

With the basics

When the app opens on the Event Tab the map already calls oninit asking for location

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-angular #1141](https://github.com/NativeScript/nativescript-angular/issues/1141) via [**ZenHub**](https://www.zenhub.com/)
