### ISSUE TITLE
Error executing command 'javac'. Make sure you have installed The Java Development Kit (JDK) and set JAVA_HOME environment variable.

### ISSUE THREAD

**Issue by moorthi07** [NativeScript/NativeScript#5210]
**My Environment**
Win 10
NS: 3.1.1 / 3.4.0
Android Studio (ADK) <---------- 'ANDROID_HOME'
JDK 1.8, 1.9

**Error when you try android** 
c:\MyNSApp>**tns platform add android**   or **tns run android**
Error executing command 'javac'. Make sure you have installed The Java Development Kit (JDK) and set JAVA_HOME environment variable.

 The issue could be finding 'Android_home' . 

Here are the steps I tried:
1. Without using Chocolatey.
- **Already installed ANDROID STUDIO** AND I don't want to install another version of Android SDK. So, I set ANDROID_HOME to 'Android_studio\android\sdk'
**But Android Studio uses embeded open JDK now** - So, I had to install JDK separately. I installed latest version 9.0.1. Set JAVA_HOME to JDK path.

But **javac works in command prompt**, but doesn't work with tns run android.

2. With Chocolatey.
Using **tns doctor** , chose to install JDK only. It installed JDK 1.8 and set JAVA_HOME and javac command works from cmd pompt. But didn't work with 'tns run android'

Updated NS to 3.4 and tried again, for the last two days, its still not working. I'll keep you posted. 
I'd appreciate if you could show me the way through this 'startup- up" mess. thanks.

**Comment by tsonevn** [comment]
Hi @moorthi07,
Could you ensure that the JAVA_HOME variable is set up properly by executing `ECHO %JAVA_HOME%` in the command prompt(CMD)?  If JAVA_HOME is not set up properly, you could follow the instructions from this [site](https://www.howtogeek.com/51807/how-to-create-and-use-global-system-environment-variables/) , where it is described another option for setting up global system variables.
Also, you could verify if the latest installed version of the java is 1.8 or if it still pointing to the new one via `javac -version`

**Comment by moorthi07** [comment]
Here are the versions I have ,
\MyNSApp>javac -version
javac 1.8.0_152
MyNSApp>echo %java_home%
"C:\Program Files\Java\jdk1.8.0_152"
And ....
\MyNSApp>tns run android
Error executing command 'javac'. Make sure you have installed The Java Development Kit (JDK) and set JAVA_HOME environment variable.

**Comment by moorthi07** [comment]
OK.  Here is how it works. 
Current NativeScript commands  (at least tns run android) married to jdk1.8.0_152. 
So, if you have any environment path (in windows 10) set for jdk1.9 or  anything else, NativeScript doesn't get the right JAVA_HOME as it directly looking for this folder: C:\Program Files\Java\jdk1.8.0_152

NativeScript commands do not recognize temporary path settings like using of the 'SET JAVA_HOME=jdk/path' commands .
