### ISSUE TITLE
Compile error in build.gradle

### ISSUE THREAD

**Issue by randy-johnson** [NativeScript/NativeScript#5213]
### Tell us about the problem
After upgrading to Nativescript 3.4 I am getting a compile error in build.gradle:

```
dependencies {
        classpath "com.google.gms:google-services:3.1.1"
		classpath "com.android.tools.build:gradle:2.3.3'
       classpath "com.google.gms:google-services:3.0.0"
     }
```

Notice the single quote on the middle line.

Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 3.4.0           │ 3.4.0          │ Up to date    │
│ tns-core-modules │ 3.4.0           │ 3.4.0          │ Up to date    │
│ tns-android      │ 3.4.0           │ 3.4.0          │ Up to date    │
│ tns-ios          │                 │ 3.4.0          │ Not installed │

When I fix the error I get another error when I try to do another tns run andriod

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'myappname'.
> Configuration with name 'compile' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Which I think may be related to the first error because I didn't have any problems on the previous version.

I have tried removing and adding the platform multiple times as well as deleting node_modules.

Any ideas on what is happening?

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#906
