### ISSUE TITLE
TypeScript compiler failed with exit code 3221225477

### ISSUE THREAD

**Issue by ZainAli1839** [NativeScript/NativeScript#5215]
>tns build android
Executing before-prepare hook from E:\firstType\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.4.2
TypeScript compiler failed with exit code 3221225477

**Comment by NickIliev** [comment]
@ZainAli1839  please provide all the additional info required to investigate the issue

> 
> ### Please provide the following version numbers that your issue occurs with:
> - CLI: (run `tns --version` to fetch it)
> - Cross-platform modules: (check the 'version' attribute in the
> `node_modules/tns-core-modules/package.json` file in your project)
> - Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
> `package.json` file of your project)
> - Plugin(s): (look for the version number in the `package.json` file of your
> project)
> 
> ### Please tell us how to recreate the issue in as much detail as possible.
> The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 
> 
> ### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
> 
>
