### ISSUE TITLE
viewModel not working inside BroadCastReceive for the first time

### ISSUE THREAD

**Issue by radhe12** [NativeScript/NativeScript#5216]
I am not able to access viewModel in onReceiveCallBack() of app.js when I login or installed app for the first time. If I rerun my app it is working perfectly.
for more info and source code please review this - https://discourse.nativescript.org/t/viewmodel-null-inside-broadcastreceive-for-the-first-time/3795

Platform: Android
CLI: 3.2.1
Cross - Platform Modele: "name": "tns-core-modules",
  "nativescript": {
    "platforms": {
      "ios": "3.0.0",
      "android": "3.0.0"
    }

**Comment by NickIliev** [comment]
Hello @radhe12 and thank you for your interest in NativeScript.

Please notice that this repository is for logging issues, bugs and features related to NativeScript modules.
For how-to related questions please use the community channels like the NativeScript forum or SO.

Regarding your question: Based on your code snippet the initial setup of `scanType` property ( `dockReceive.set("scanType","ScanPackingSlip");` ) is done when the `dockreceive` page is loaded (which is after the app.js execution so it is expected that on first run the scanType getter in app.js would not return any value)

Closing as duplicate to [https://discourse.nativescript.org/t/viewmodel-null-inside-broadcastreceive-for-the-first-time/3795](https://discourse.nativescript.org/t/viewmodel-null-inside-broadcastreceive-for-the-first-time/3795)
