### ISSUE TITLE
AM/PM buttons in ClockTimePicker style Timepicker not working

### ISSUE THREAD

**Issue by shabib3** [NativeScript/NativeScript#5217]
It seems like when I use the ClockTimePicker style for TimePicker, the AM/PM buttons not working at all.

For instance: If you set the TimePicker at the begging in time that is AM (like 02:00), it always stay in AM, even if I put in on PM. and the same thing on the opposite (PM).

Thanks a lot :)

**Comment by tsonevn** [comment]
Hi @shabib3,
Thank you for contacting us,
If I understand you correctly you are changing the style of the TimePicker from spinner to clock in the App_Resources/Android/values-v21/styles.xml files and while changing the values for the hour property the AM/PM field does not change its value.

I tested this case, however, I was unable to recreate this behavior on my side. For your convenience I am attaching a sample project. Please review the project and make the needed changes, which will allow us to recreate this issue.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1596943/Archive.zip)

**Comment by jogboms** [comment]
@tsonevn i experienced the same thing #1030

**Comment by tsonevn** [comment]
Hi @jogboms,
Could you provide sample project or make the needed changes in the attached one in my previous comment, which will allow us to recreate this behavior?

**Comment by jogboms** [comment]
Mixed up the references here is it.
https://github.com/NativeScript/nativescript-angular/issues/1030

**Comment by tsonevn** [comment]
Hi @jogboms,
I tested the scenario with the timeChange event handling and indeed the event will not be fired while changing the TimePicker value manually via the UI on Android API level 21 and 22.  I was able to recreate this behavior also on a non-Angular project. For your convenience, I am attaching sample project, which could be used for debugging.

@shabib3 could you confirm if you are facing the same problem or the case is different on your side.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/1600054/Archive.zip)

**Comment by NickIliev** [comment]
Closing as related to [https://github.com/NativeScript/nativescript-angular/issues/1030](https://github.com/NativeScript/nativescript-angular/issues/1030)
