### ISSUE TITLE
Confirm dialog does not show up after a custom dialog 

### ISSUE THREAD

**Issue by fourctv** [NativeScript/NativeScript#5218]
I’m opening a custom dialog and after that dialog closes I need to show a Confirm dialog.
The Confirm dialog does not show up, if called from within the .then() of a custom dialog.

I’ve set up a playground to show the problem: https://play.nativescript.org/?template=play-ng&id=tlRK9w1

There are 2 buttons on the home screen:

- the first one shows a sample confirm and an alert after confirm is closed
- the second shows a custom dialog to select names from a list, and after a selection it calls the same confirm

You can see that in the first case confirm+alert does work, but in the second case the confirm fails to show up, although the same function is called on both cases and the log shows that.

I’ve tried to add a timeout before calling the confirm function, from the custom dialog, but that did not help.

### Which platform(s) does your issue occur on?
tested on iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.0
- Cross-platform modules: 3.4.0
- Runtime(s): 3.1.0

**Comment by tsonevn** [comment]
Hi @fourctv,
Thank you for contacting us.
I reviewed the attached link, however in the project I was unable to find, where a modal page is used. Could you review again the project and to provide a link to the correct one.
I the meantime something that could be related to this behavior. In case you are opening the alert or the confirm in the very beginning of the statement, the modal page is still closing, the alert might not be opened. In this case, I would suggest to try using a timeout and to verify, if you will have the same problem. For example:
```
getEndDate() {
        this.createModelView().then(result => {
            setTimeout(() => {
                alert("test");
            }, 1000);
           
        }).catch(error => this.handleError(error));
    }
```

**Comment by fourctv** [comment]
@tsonevn yes, adding a large enough timeout does work. 600 was the minimum amount.

But that is not exactly a solution, right?

Unfortunately the playground expired and is not there anymore. I'll try to recreate it.

FYI, if you put out a Confirm and embed an Alert, it works fine. The problem is occurs only when you have a Custom Dialog, and want to do a Confirm when the custom dialog closes. A pretty common situation I presume.

**Comment by tsonevn** [comment]
Hi @fourctv,
Thank you for writing us back, 
We reviewed the case with playground link, however, those links do not have an expiration time. It might be a temporary issue with the playground.
Indeed it would help if you could recreate this behavior again in a sample project and to send us again the link.

**Comment by fourctv** [comment]
Here is a playground link that reproduces the problem reported:
https://play.nativescript.org/?template=play-ng&id=6Xs5rO

**Comment by EmilStoychev** [comment]
@fourctv just FYI the old Playground session hasn't expired – the link that you pasted contains "1" at the end which was probably added by mistake upon copy/paste. The correct link is https://play.nativescript.org/?template=play-ng&id=tlRK9w

**Comment by fourctv** [comment]
humm... then the Share button is buggy, because that's what I did... hit Share and paste into the message :-(

**Comment by tsonevn** [comment]
Hi @fourctv,
Thank you for the attaching the new link. In your case, you could also show the confirm and the alert before calling the modal page callback method. For example:
home.modal.ts
```
import { Component, Input, ViewChild } from '@angular/core';
import { ModalDialogParams } from 'nativescript-angular/modal-dialog';
import * as dialog  from "ui/dialogs"

@Component({
    moduleId: module.id,
    selector: 'home-modal',
    templateUrl: 'home.modal.html'
})

export class HomeModal {


    public selectorList: Array<string> = ['Item 1', 'Item 2', 'Item 3', 'foo', 'bar'];


    constructor(private params: ModalDialogParams) {
    }



    public selectItem(index) {
        dialog.confirm("Confirm selection: ").then(res => {
            dialog.alert('confirm result:' + res).then(alres => { 
                this.params.closeCallback(this.selectorList[index]);
            });
        });
    }

    public close() {
        this.params.closeCallback('none');
    }

}
```
In this case, there will be no needs to use a timeout.

**Comment by fourctv** [comment]
@tsonevn but with your change you're not showing the custom dialog! All you're showing is a confirm and alert. That works, I know.

The problem is only with the custom dialog. The custom dialog Promise is completed before {N} finishes cleaning up its stuff, thus the need for a bit of a delay before one can use any other `ui/dialog` function.

**Comment by tsonevn** [comment]
Hi @fourctv,
Excuse me for the delay in reply.
The above code snippet is showing another approach, where the idea is to show the confirm, before the close callback method of the custom dialog(modal page). I am not sure that this meets the needs of your application, however, it shows another case, how to show the confirm, without a timeout.

Also, I would like to mention that some changes have been made to the modal page in the next NativeScript version, which improves its functionality.

**Comment by bryce-marshall** [comment]
I encountered a similar problem when wanting to display an alert following a Google sign-in error. I found that a "delay" was not necessary, but certainly that the Promise returned by the initial modal dialog did need to complete before a new dialog (the alert) could be opened. The workaround is to wrap the Promise returned by the modal dialog in containing promise that queues itself for completion after the modal has completed. Note that no client code should have access to the inner promise, because any chained handlers could break the workaround. The following snippets represent my solution applied to your example:

function safeDialog(inner: Promise<any>): Promise<void> {
    return new Promise((resolve, reject) => {
        inner
            .then((r) => {
                setTimeout(() => { resolve(r); });
            })
            .catch((e) => {
                setTimeout(() => { reject(e); });
            });
    });
}

function showCustom(): void {
    const options: ModalDialogOptions = {
        viewContainerRef: this.viewref,
        fullscreen: false,
        context: {}
    };

    safeDialog(this.modalService.showModal(ModalComponent, options))
        .then((select: string) => {
            console.log('selected:' + select);
            this.onButtonTap;
        });
}
