### ISSUE TITLE
Release apk but show bash: !@: event not found

### ISSUE THREAD

**Issue by yclau** [NativeScript/NativeScript#5223]
i trying to build release version apk in mac but terminal show "bash: !@: event not found" , i follow step by step using this [https://www.nativescript.org/blog/steps-to-publish-your-nativescript-app-to-the-app-stores](url). I try using tns build android , it complete build. what is the problem ?

**Comment by tsonevn** [comment]
Hi @yclau,
Thank you for contacting us.
I reviewed the attached article and follow the described steps for an android release build, however, was unable to recreate the described issue.

I steps the I used are as follow:
1. `tns create test`
2. `cd test`
3. `tns build android --release --key-store-path <path-to-your-keystore> --key-store-password <your-key-store-password> --key-store-alias <your-alias-name> --key-store-alias-password <your-alias-password>`

However, the given information is not enough to investigate further the case. Regarding that could you provide some more info about your environment(CLI, modules, runtime versions, OS). Also, it would help if you provide the exact steps, which you used while building the application for release and the full log from the console, while the error is thrown.

**Comment by yclau** [comment]
this is my package.json 

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.merchant",
    "tns-android": {
      "version": "3.4.0"
    }
  },
  "dependencies": {
    "nativescript-background-http": "^3.1.0",
    "nativescript-camera": "^3.2.1",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-imagepicker": "^4.0.1",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-permissions": "^1.2.3",
    "nativescript-phone": "^1.3.1",
    "nativescript-plugin-firebase": "^5.0.5",
    "nativescript-pro-ui": "^3.3.0",
    "nativescript-slideshow-busy-indicator": "^3.0.1",
    "nativescript-theme-core": "^1.0.4",
    "tns-core-modules": "^3.4.0"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.0.1",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "^0.9.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "webpack": "~3.8.1",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  }
}
```
my os is macOS High Sierra Version 10.12.2

i just follow step build out jks file and follow this command.

`tns build android --release --key-store-path <path-to-your-keystore> --key-store-password <your-key-store-password> --key-store-alias <your-alias-name> --key-store-alias-password <your-alias-password>
`

**Comment by yclau** [comment]
I find out the problem, cannot put symbol into <your-alias-password> , I test in abcd1234 it work !! , before that i use Abcd1234!@

**Comment by tsonevn** [comment]
Hi @yclau,
I am glad to hear that you have resolved your case. Indeed there are [some symbols](https://www.mtu.edu/umc/services/digital/writing/characters-avoid/) that should be avoided in the application name.
Best Regards
