### ISSUE TITLE
CSS property values non-complying with CSS3 specification

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/NativeScript#5224]
List of CSS property values that are not applied correctly in {N}:

backgroundPosition with percent/number: https://github.com/NativeScript/NativeScript/issues/4201
short form of "transform: translate": https://github.com/NativeScript/NativeScript/issues/5202

**Comment by vakrilov** [comment]
This seems like a good place to start for anyone that wants to contribute to the framework (thus the [`good first issue`](https://github.com/NativeScript/NativeScript/labels/good%20first%20issue) label):
Here are some for folks that might want to get involved:
 - Read the [contributing guide](https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md).
 - Here is a [useful documentation article on properties in NativeScript](https://docs.nativescript.org/core-concepts/properties)
 - Most of the CSS properties are defined in the [style-properties.ts](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/styling/style-properties.ts) -  this might be a good place to start exploring the codebase.

**Comment by chrisdemars** [comment]
Has this been touched yet @vakrilov? I can take it if not.

**Comment by vchimev** [comment]
Hey @chrisdemars,

This issue hasn’t been worked on - feel free to go ahead and take it.

Let us know if you have questions.

Thanks.

**Comment by chrisdemars** [comment]
Sounds good, thanks!

**Comment by janoshrubos** [comment]
Closing this issue since the implementations are merged to master. 
If these errors are still relevant, feel free to open a new issue!
