### ISSUE TITLE
How to get the orientation of the device camera for android using the android native method "getWindowManager().getDefaultDisplay().getRotation();"

### ISSUE THREAD

**Issue by shibobrota** [NativeScript/NativeScript#5226]
I want to get the orientation of device camera using native method "context.getWindowManager().getDefaultDisplay().getRotation()"
how to do it ???

**Comment by NickIliev** [comment]
@shibobrota getWindowManager is a method from [android.app.Activity](https://developer.android.com/reference/android/app/Activity.html) but you can obtain WindowManager using getSystemService

TypeScript example
```TypeScript
import * as applicationfrom "application";

let appContext = <android.content.Context>application.android.context;
let windowManager = appContext.getSystemService(android.content.Context.WINDOW_SERVICE);
let rotation = windowManager.getDefaultDisplay().getRotation();

console.log(rotation); // returns int (e.g. 0 or 1)
```

Or you can use one of the [orientationChangedEvent](https://docs.nativescript.org/api-reference/modules/_application_#orientationchangedevent)
```TypeScript
import * as application from "application";

application.on(application.orientationChangedEvent, (args) => {
    console.log("orientationChangedEvent");
    console.log(args.newValue); // landscape or portrait
});
```

Or you can use the already creted plugins like [nativescript-orientation](https://www.npmjs.com/package/nativescript-orientation) or [nativescript-screen-orientation](https://www.npmjs.com/package/nativescript-screen-orientation)

**Comment by shibobrota** [comment]
Hey @NickIliev, Thank you.
This code is working fine and I'm getting the desired result as well.
but I've converted it to **JS** like this 
`var rotation = app.android.context.getSystemService(android.content.Context.WINDOW_SERVICE).getDefaultDisplay().getRotation();`
