### ISSUE TITLE
ScrollView scrollableHeight

### ISSUE THREAD

**Issue by sharesoft** [NativeScript/NativeScript#523]
When populating a ScrollView from code, the value of the ScrollView’s scrollableHeight property appears to be calculated asynchronously. This makes it difficult to use the scrollToVerticalOffset() method reliably as it will fail if invoked before the scrollableHeight property is actually available.

It would be useful if an event could be triggered once the scrollableHeight value had been calculated. Or perhaps making the scrollableHeight property observable might be another option?
I’ve included more information on this issue in a forum post at…
https://groups.google.com/forum/?hl=en#!topic/nativescript/2ddhqjpMzrE

**Comment by enchev** [comment]
We've just replied to your post, let's continue our conversation in our forums.
