### ISSUE TITLE
How to add native android dependencies in nativescript app

### ISSUE THREAD

**Issue by shibobrota** [NativeScript/NativeScript#5230]
I want to add native dependency " CameraKit-Android" in my app and I want to use it in js.
If I'm trying to add `compile 'com.wonderkiln:camerakit:0.13.1` in
 ```
dependencies {
	compile "com.wonderkiln:camerakit:0.13.1"
}
```
 in app.gradle, then the gradle build is failing.
Also, tell how to use the xml implementation
 ```
<com.wonderkiln.camerakit.CameraView
    android:id="@+id/camera"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:adjustViewBounds="true" />
```
Please suggest how to include native dependency and use it in js.

**Comment by NickIliev** [comment]
@shibobrota 
The best case would be to create your own plugin using [the recommended plugin structure](https://docs.nativescript.org/plugins/building-plugins).
Article about creating custom UI plugins can be found [here](https://docs.nativescript.org/plugins/ui-plugin-custom)
More about creating Android plugins [here](https://docs.nativescript.org/runtimes/android/plugins/plugins)
