### ISSUE TITLE
imageSource saving and loading from file issues

### ISSUE THREAD

**Issue by shabib3** [NativeScript/NativeScript#5233]
Hi! :)

I am creating a service that will allow me to cache images into the file system for better performance, and I am meeting couple issues here.

first of all, this is the code of the service:
```
import { Injectable } from '@angular/core';
import * as imageSource from "tns-core-modules/image-source";
import * as fs from "tns-core-modules/file-system";


@Injectable()
export class ImageCacheService {
    private folder: fs.Folder = fs.Folder.fromPath(fs.path.join(fs.knownFolders.documents().path, "Cached_Images"));
    
    constructor() {
        console.log("folderPath ->", this.folder.path)
    }

    public getImage(key: string): imageSource.ImageSource {
        const filePath = fs.path.join(this.folder.path, `${key}.jpg`);
        return imageSource.fromFile(filePath);
    }

    public setImage(key: string, image: imageSource.ImageSource): boolean {
        const path = fs.path.join(this.folder.path, `${key}.jpg`);
        return image.saveToFile(path, "jpg");
    }

    public removeImage(key: string): Promise<any> {
        const file = this.folder.getFile(`${key}.jpg`);
        return file.remove();
    }
}
```

Loading code part of the component that use the service:
```
...
...
const image: imageModule.Image = this.myImageRef.nativeElement;
const profilePictureUrl = "https://www.blog.google/static/blog/images/google-200x200.7714256da16f.png";
const key = "googleLogo";

const cachedImageSource = this._imageCacheService.getImage(key);
if (!cachedImageSource) {
    imageSourceModule.fromUrl(profilePictureUrl).then(imgSrc => {
        console.log("cached img -> ", key);
        image.imageSource = imgSrc;
        this._imageCacheService.setImage(key, imgSrc);
    });
} else {
     image.imageSource = cachedImageSource;
}
...
...
```

Now it seems that it save it correctly...but I am fail to load the imageSource.
So few question (test it on android):
1. I see that the command `fs.knownFolders.documents()` bring me this -> `/data/user/0/com.myApp.app/files` - there is a way to look at it in the file explorer? it seems like it hidden but when I expose the hidden file there are not in the folder so I am not sure that the folder I am looking into is the right folder(when I use the 'file explorer' app I navigate to `/Android/data/com.myApp.app` and there are not `files` folder in there)
2. When I get into the `getImage` function in looks like the file is exist (checked it with `fs.File.exists(filePath);`) and it seems to load something but there is nothing showing on the image element.

Thank you very much! :)

**Comment by tsonevn** [comment]
Hi @shabib3,
I tested your scenario while using some part of the attached code snippets while using the [nativescript-sdk-examples-ng](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/http/http-get) I make the following  changes in the files:
http-get.service.ts
```
// >> http-get-service
import { Injectable } from "@angular/core";
import { Observable as RxObservable } from "rxjs/Observable";
import { HttpClient, HttpHeaders, HttpResponse } from "@angular/common/http";
import "rxjs/add/operator/map";
import "rxjs/add/operator/do";

import * as imageSource from "tns-core-modules/image-source";
import * as fs from "tns-core-modules/file-system";

@Injectable()
export class MyHttpGetService {
    private serverUrl = "https://httpbin.org/get";
    private folder: fs.Folder = fs.Folder.fromPath(fs.path.join(fs.knownFolders.documents().path, "Cached_Images"));

    constructor(private http: HttpClient) { 
        console.log("folderPath ->", this.folder.path)
    }


    public getImage(key: string): imageSource.ImageSource {
        
        console.log("getImage");
        let result;
        if(fs.File.exists(this.folder.path+"/"+key+`.jpg`)){
            const filePath = fs.path.join(this.folder.path, key+`.jpg`);
            
            result = imageSource.fromFile(filePath);
        }
        
        return result;
    }

    public setImage(key: string, image: imageSource.ImageSource): boolean {
        console.log("setImage");
        const path = fs.path.join(this.folder.path, key+`.jpg`);
        return image.saveToFile(path, "jpg");
    }

    public removeImage(key: string): Promise<any> {
        alert("remove image");
        console.log("removeImage");
        const file = this.folder.getFile(`${key}.jpg`);
        return file.remove();
    }
}
// << http-get-service

```
http-get.component.ts
```
// >> http-get-component
import { Component, OnInit } from "@angular/core";
import { MyHttpGetService } from "./http-get.services";
import * as imageSourceModule from "tns-core-modules/image-source";
@Component({
    moduleId: module.id,
    templateUrl: "./http-get.component.html",
    providers: [MyHttpGetService]
})
export class HttpGetComponent implements OnInit {
    public host: string;
    public userAgent: string;
    public origin: string;
    public url: string;
    public test;
    constructor(private myService: MyHttpGetService) { }

    ngOnInit() {
        
    }

    onTap(){
        const profilePictureUrl = "https://www.blog.google/static/blog/images/google-200x200.7714256da16f.png";
        const key = "googleLogo";

        const cachedImageSource = this.myService.getImage(key);
        if (!cachedImageSource) {
            alert("image is not cached");
            imageSourceModule.fromUrl(profilePictureUrl).then(imgSrc => {
                console.log("cached img -> ", key);
                // image.imageSource = imgSrc;
                this.myService.setImage(key, imgSrc);
                console.log("image source")
                console.log(imgSrc)
                this.test=imgSrc;
            });
        } else {
            alert("imaged is cached")
            this.test = cachedImageSource;
        }
    }

    removeImage(){
        const key = "googleLogo";
        this.myService.removeImage(key);
    }
    
}
// << http-get-component

```
http-get.component.html
```
<ScrollView sdkExampleTitle sdkToggleNavButton>
    <GridLayout rows="auto, auto, auto" columns="*">
        <Button text="show Image" row="0"  (tap)="onTap()"></Button>
        <Button text="remove Image" row="1" (tap)="removeImage()"></Button>
        
        <Image row="2" [src]="test"></Image>
        
    </GridLayout>
</ScrollView>
```
In my code, the difference is that I bind the src property to the image. For your convenience, I am attaching images, which demonstrates the behavior of the code on the first navigation to the page and on the second. You could see that on the second navigation after a tap on `show Image` we will go in the `else` state and the second alert will be shown.


![image1](https://user-images.githubusercontent.com/17448734/34667379-70301ad2-f471-11e7-8405-c06a0e0830c8.png)
![image2](https://user-images.githubusercontent.com/17448734/34667380-704ae182-f471-11e7-8ddd-a79ad419e361.png)


If the issue still persists, please provide sample project, which could be debugged locally and more info about your environment(CLI, modules, runtime versions.)

**Comment by shabib3** [comment]
So actually it works for me.
Somehow when published this issue something went wrong...
But I'll take the bind thing from your sample to my code! :)

For my other question:
There is a way to see the actual saved files in the android explorer? What is the path to `/data/user/0/com.myApp.app/files` (`fs.knownFolders.documents()`)?
and another question, Can I save files to the root folder of the device?

**Comment by tsonevn** [comment]
Hi @shabib3,
You could check if the folder contains files while using `getEntities` method. The method will return a Promise with an array with all entities. To verify if the folder is empty you could check the length of the entities array. For further help, you could review the example [here](https://docs.nativescript.org/cookbook/file-system#getting-folder-contents).

Regarding your second question. On the devices, which are using latest Android you will not have access to the `root` directory.   I would suggest saving the needed images in the `sdcard` folder.
For example: `var documents = fsModule.Folder.fromPath("/sdcard");`

**Comment by shabib3** [comment]
Thanks a lot!
