### ISSUE TITLE
ListView static headers & footers, grouping and unbound mode support

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#524]
I think this is a good use-case, for the following features:
 - Support unbound mode in ListView #262
 - Enable grouping on ListView #259
 - Allow ListView init by directly specifying its items without template and collection #104

Our "Expensity" application has the following design for iOS:

![08 1 login](https://cloud.githubusercontent.com/assets/5919275/8981536/d57f4e6e-36c1-11e5-96a4-6166c3b4b284.png)

Which in iOS can easily be created using Xcode's IB with UITableView that has `Content` of `Static Cells`. The following is a screenshot of an attempt to recreate the above design in Xcode with static cells:

![login](https://cloud.githubusercontent.com/assets/5919275/8981694/1847d33c-36c3-11e5-84b0-afc57881dc7f.png)

I would expect something like the following code, to be able to recreate what is possible with Xcode's storyboards:
``` XML
<Page xmlns="http://www.nativescript.org/tns.xsd" 
      loaded="pageLoaded"
      navigatedTo="navigatedTo">
  <Page.actionBar>
    <ActionBar title="Xpensity">
      <ActionBar.actionItems>
        <ActionItem text="Sign up" tap="signup" ios.position="right" android.position="actionBar" />
      </ActionBar.actionItems>
    </ActionBar>
  </Page.actionBar>

  <ListView>
    <ListViewSection>
      <ListViewCell>
        <TextField hint="username" text="{{ username }}" />
      </ListViewCell>
      <ListViewCell>
        <TextField hint="password" text="{{ password }}" secure="true" />
      </ListViewCell>
    </ListViewSection>
    <ListViewSection>
      <ListViewCell>
        <Button text="Login" tap="login" />
      </ListViewCell>
    </ListViewSection>
    <!-- list-view footer -->
    <Button text="Forgotten password?" tap="resetpass" />
  </ListView>
</Page>
```

Currently the effect is achieved with a bunch of Border-s and CSS.

**Comment by PanayotCankov** [comment]
Btw, the `ActionBar` works like a charm.

**Comment by enchev** [comment]
As far as I know this is planned in UI for NativeScript, right @ginev? :)

**Comment by ginev** [comment]
Hey guys,

Sorry for the delay but I inexplicably missed that one.

We're currently working on a ListView component which will be released for 1.3.

It will support all common native features of the iOS and Andorid components including:
- sorting
- grouping
- filtering
- static header/footer
- swipe to refresh (a.k.a. pull-to-refresh)

Since **unbound mode** is something that does not come out of the box in the native components, we will have to implement it at NativeScript level. This will happen presumably after the implementation of the currently supported features.

**Comment by getsetbro** [comment]
Can we get the floating headers?:
![gif](http://i.imgur.com/8n5vKwU.gif)

**Comment by scorpnode** [comment]
So has this feature been implemented?

**Comment by ginev** [comment]
@scorpnode 
Static header and footer support is already implemented and will be available in the upcoming release. Grouping, filtering and sorting have all been postponed but are on the TODO list - probably for May-June timeframe.

**Comment by scorpnode** [comment]
Thanks I will await this

**Comment by patuku-roy** [comment]
Ho @ginev , can you define when the upcoming release? Is it 1.8 or maybe on 1.7 minor release?

**Comment by AntonioCuevaUrraco** [comment]
hi @ginev was the sticky header released on NS 2.0 I can not find the reference to the code

**Comment by seppel1992** [comment]
@ginev 
are there any updates regarding grouping / filtering in a NativeScript ListView (or RadListView in Telerik UI for NativeScript) ?

**Comment by ginev** [comment]
Hello @AntonioCuevaUrraco, @seppel1992: Sticky headers work in context with data groups. The implementation of grouping/filtering/sorting was delayed and the current version of RadListView does not support these features. They are on the roadmap though and will be implemented in the upcoming months.

**Comment by AntonioCuevaUrraco** [comment]
Sorry @ginev but I still can not find a way to make a listview to include an item on the top different to the rest of the template.
The only way I got is to bind on the xml to the model a property to hide the header part on the rest of the items like this
```
visibility="{{ isHeader ? 'visible' : 'collapsed' }}" 
````
And of course that idea was literally killing the performance of the listview

Is there some example/test/Api documentation that you could point?

**Comment by ginev** [comment]
I am sorry @AntonioCuevaUrraco, I forgot to paste the link to the docs article related to Header and Footer: http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/header-footer

Does this not work for you?

**Comment by AntonioCuevaUrraco** [comment]
Yes, thank you @ginev now is all clear. I was looking on NS ListView not on the RadListView.
I will check  between migrating to RadListView on our app or filling the missing headers/footers with a plugin.

**Comment by leocaseiro** [comment]
Hi @ginev, I was able to implement the listViewHeader, however it's not sticky. Is there any example with Angular?

The one I'm following is https://github.com/telerik/nativescript-ui-samples-angular/tree/release/sdkAngular/app/listview/header-footer.

Also I'd like to have more than a header. What I want to achieve is very similar the image from @getsetbro [here](https://github.com/NativeScript/NativeScript/issues/524#issuecomment-158139569)

Thanks

**Comment by ginev** [comment]
Hello @leocaseiro,
Sticky headers are currently not supported in RadListView but we have them in mind. The second scenario is most probably a grouped data set visualized in the List control with sections with headers and sub-items. This is also not available out of the box. You can mimic this behavior though by creating a flattened data list consisting of group items and data items and use the 'itemLoading' event to provide custom look-and-feel . More info about the item-loading event here:

http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/How-To/item-customization

**Comment by stefalda** [comment]
Hi, any news about the "sticky-headers", AKA"sections", implementation for the ListView or RadListView?

**Comment by svzi** [comment]
I would be very interested in this feature as well.

**Comment by dlucidone** [comment]
Any Updates on this i'm not abe to find any reference on this.Thanks

**Comment by ginev** [comment]
@dlucidone, @svzi we have logged this as a TODO issue in our public NS UI related repository: github.com/telerik/nativescript-ui-feedback. Please make sure to post any comments and track its status there.

**Comment by rajasekarsp** [comment]
Any update on listview unbound mode support?

**Comment by sean-perkins** [comment]
For reference on those that find this issue from Google and want floating headers.

I was able to accomplish this in my own application. 

![Image](https://i.gyazo.com/e6422b7d753c9d4affa8ed96283e6651.gif)

Was accomplished with the RadListView, an external label outside of the List and registering to the scroll event to calculate offset position. This was then used to detect which group was entering/leaving the viewport.

**Comment by stefalda** [comment]
Have you got some code to share? It would be great to wrap it in a sort of plugin...

**Comment by leocaseiro** [comment]
here's an extension that works with iOS only for ListView. https://github.com/rajivnarayana/nativescript-sectioned-list-view

**Comment by empresarrollo** [comment]
@sean-perkins do you have any code example uploaded?

**Comment by sean-perkins** [comment]
It's available in this repository: https://github.com/sean-perkins/nativescript-petfinder/blob/master/app/pet/components/breed-dialog/breed-dialog.component.ts @empresarrollo
