### ISSUE TITLE
Defining an object in the .js file of a custom component creates a single object instance for all the usages of that component in the XML file

### ISSUE THREAD

**Issue by rolaru** [NativeScript/NativeScript#5241]
nav-item.js:

    var frameModule = require('ui/frame');

    var NavItem = {
        onLoad: function (args) {
        NavItem.instance = args.object;  // I save the instance in the NavItem object 
      },

      navigate: function (args) {
          var navItem = NavItem.instance;
          console.log(navItem.to);
          console.log(args.object.to);
          frameModule.topmost().navigate('pages/' + navItem.to + '/' + navItem.to);
      }
    };

nav-item.xml:

`<Button id="nav-item-button" loaded="onLoad" tap="navigate" />`

side-menu.xml:

    <StackLayout class="main-menu-content"
             xmlns:NavItem="shared/components/nav-item">
      <NavItem:nav-item class="main-menu-button" text="Cazinouri din apropiere" to="nearby-casinos" />
      <NavItem:nav-item class="main-menu-button" text="Quiz-uri" to="quizzes" />
      <NavItem:nav-item class="main-menu-button" text="Map quest" to="map-quest" />
      <NavItem:nav-item class="main-menu-button" text="Setări" to="settings" />
      <NavItem:nav-item class="main-menu-button" text="Promoții" to="promotions" />
    </StackLayout>

What the console displays after tapping the "nearby-casinos" button:

JS: promotions
JS: nearby-casinos

So, I expect `navItem.to` to be the same as `args.object.to` in the navigate function but it seems that a single instance of the NavItem object is created for all "NavItem:nav-item" in the menu and each calls the `onLoad()` function which overwrites the `NavItem.instance` property. Is this the intended behaviour?

**Comment by tsonevn** [comment]
Hi @rolaru,
First of all, thank you for your interest in NativeScript.
I reviewed your case and if I understand you correctly the NavItem in `nav-item.js` file is a global variable, where the value for the NavItem will be set on every firing of the button loaded event.
In this case, the NavItem will be overwritten with every execution of the loaded event and will point every time to the last button. In this case, we could not be sure that the value for the custom defined properties such as `to` will also be overwritten.

Regarding that, I would suggest using `args.object` when you need to take the instance of the button, which is the appropriate way in your case.
Also keep in mind that every component should have unique id, however you set up the same for every button -> `<Button id="nav-item-button" loaded="onLoad" tap="navigate" />`, which could lead to an issue, if you try to get some of the components by its id. 
For your convenience, I am attaching a sample project. if you still think that there is a real issue, please review it and make the needed changes, which will allow us to debug it on our side.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1611748/Archive.zip)

**Comment by rolaru** [comment]
Hi @tsonevn ,

Thank you very much for the quick reply. That's greatly appreciated!

So, mostly yes, that's the case: the `NavItem.instance` property gets overwritten with each `onLoad` call (executed on the loaded event). I know about the `args.object` solution, but I found the fact that you only have one `NavItem` object instance for all `<NavItem:nav-item />` to be unnatural.

I thought a separate instance of `NavItem` is created for each of the `<NavItem:nav-item />`  elements. 

When setting `xmlns:NavItem="shared/components/nav-item"` does NS require the `nav-item.js` file only once?
And with each  `<NavItem:nav-item />`  declaration, does NS use the same code from `nav-item.js`?
If that's the case than this is an important thing to put in the official documentation I think.

I thought that for each `<NavItem:nav-item />`  declaration a separate module with it's own `NavItem` object is created. That's how I considered it to be normal: each instance of  `<NavItem:nav-item />`  with it's own JS code.

And regarding the `<Button id="nav-item-button" />`, I had no issues with selecting the corresponding button. That works fine.

Thanks once again @tsonevn ! Can't wait for your answer.

**Comment by tsonevn** [comment]
Hi @rolaru,
I research again your case and confirm that the namespace, which is declared in the XML `xmlns:NavItem="shared/components/nav-item"` will be required ones and  `nav-item` files will be reused while creating the objects from your custom component `<NavItem:nav-item />`.

Something more, for each custom component there will be defined separated callback methods for the event. for example, the `loaded` and `tap` event will have there own instance of the callbacks of every new component. However `NavItem` global object will be defined ones while the file is required.  

About the Button, I  just wanted to let you know that the recommended way is to use unique id for every new component

**Comment by rolaru** [comment]
Ok, that's really good to know. So the correct way to write code for different instances of `<NavItem:nav-item />` is to use the `args.object` property. I understand now.

Thanks again @tsonevn ! I think this can be closed.
