### ISSUE TITLE
App is crashing if I am using Android soft back button

### ISSUE THREAD

**Issue by nmongiya** [NativeScript/NativeScript#5242]
### Tell us about the problem
When I am using android back button to navigate back to screen , it is crashing with the following error in console
01-08 16:15:19.920 11863 11863 F zygote  : java_vm_ext.cc:504]     from java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[])
01-08 16:15:19.920 11863 11863 F zygote  : java_vm_ext.cc:504]   at com.tns.Runtime.callJSMethodNative(Native method)
01-08 16:15:19.920 11863 11863 F zygote  : java_vm_ext.cc:504]   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
01-08 16:15:19.920 11863 11863 F zygote  : java_vm_ext.cc:504]   at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
01-08 16:15:19.920 11863 11863 F zygote  : java_vm_ext.cc:504]   at com.tns.Runtime.callJSMethod(Runtime.java:953)
01-08 16:15:19.920 11863 11863 F zygote  : java_vm_ext.cc:504]   at com.tns.Runtime.callJSMethod(Runtime.java:937)
01-08 16:15:19.920 11863 11863 F zygote  : java_vm_ext.cc:504]   at com.tns.Runtime.callJSMethod(Runtime.java:929)
01-08 16:15:20.013 11863 11863 F zygote  : runtime.cc:492]   at com.tns.Runtime.callJSMethodNative(Native method)
01-08 16:15:20.013 11863 11863 F zygote  : runtime.cc:492]   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
01-08 16:15:20.013 11863 11863 F zygote  : runtime.cc:492]   at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
01-08 16:15:20.013 11863 11863 F zygote  : runtime.cc:492]   at com.tns.Runtime.callJSMethod(Runtime.java:953)
01-08 16:15:20.013 11863 11863 F zygote  : runtime.cc:492]   at com.tns.Runtime.callJSMethod(Runtime.java:937)
01-08 16:15:20.013 11863 11863 F zygote  : runtime.cc:492]   at com.tns.Runtime.callJSMethod(Runtime.java:929)
01-08 16:15:20.014 11863 11863 F zygote  : runtime.cc:492]   at com.tns.Runtime.callJSMethodNative(Native method)
01-08 16:15:20.014 11863 11863 F zygote  : runtime.cc:492]   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
01-08 16:15:20.014 11863 11863 F zygote  : runtime.cc:492]   at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
01-08 16:15:20.014 11863 11863 F zygote  : runtime.cc:492]   at com.tns.Runtime.callJSMethod(Runtime.java:953)
01-08 16:15:20.014 11863 11863 F zygote  : runtime.cc:492]   at com.tns.Runtime.callJSMethod(Runtime.java:937)
01-08 16:15:20.014 11863 11863 F zygote  : runtime.cc:492]   at com.tns.Runtime.callJSMethod(Runtime.java:929)
01-08 16:15:20.059 11863 11863 F zygote  : runtime.cc:500]     from java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[])
01-08 16:15:20.060 11863 11863 F zygote  : runtime.cc:500]   at com.tns.Runtime.callJSMethodNative(Native method)
01-08 16:15:20.060 11863 11863 F zygote  : runtime.cc:500]   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)   com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
01-08 16:15:20.060 11863 11863 F zygote  : runtime.cc:500]   at com.tns.Runtime.callJSMethod(Runtime.java:953)
com.tns.Runtime.callJSMethodImpl(Runtime.java:966)              com.tns.Runtime.callJSMethod(Runtime.java:937)
01-08 16:15:20.060 11863 11863 F zygote  : runtime.cc:500]   at com.tns.Runtime.callJSMethod(Runtime.java:929)
com.tns.Runtime.callJSMethod(Runtime.java:953)                  3) has died: fore TOP
01-08 16:15:20.060 11863 11863 F zygote  : runtime.cc:500]   at com.tns.Runtime.callJSMethod(Runtime.java:937)
01-08 16:15:20.060 11863 11863 F zygote  : runtime.cc:500]   at com.tns.Runtime.callJSMethod(Runtime.java:929)
ActivityManager: Process org.nativescript.FreshTracker (pid 11863) has died: fore TOP
ActivityManager: setHasOverlayUi called on unknown pid: 11863

### Which platform(s) does your issue occur on?
Android
 "tns-android": {
      "version": "3.2.0"
    }
angular 4.4.5
"nativescript-angular": "~4.4.1",

**Comment by nmongiya** [comment]
I think I found the reason, I am using MapView from 'nativescript-google-maps-sdk'. When I have disabled it from html and I am successfully able to redirect to that page in android back button. That seems some problem with MapView.

**Comment by NickIliev** [comment]
Closing as related to [https://github.com/dapriett/nativescript-google-maps-sdk](https://github.com/dapriett/nativescript-google-maps-sdk)
