### ISSUE TITLE
Want help to access webview document height and cookies

### ISSUE THREAD

**Issue by dhananjaykumar880** [NativeScript/NativeScript#5243]
Hello Everyone,

you guys are doing the very good job, I am creating a simple application by using nativescript and I am new on nativescript as well as native platforms.

I want to access webview document height and cookies of loaded URL.
I found a library that is named as 'nativescript-webview-interface' but after 3.4.0 update it is not working. And the repository is also inactive for a long time.

I had verified almost all StackOverflow related to nativescript and webview
the platform should be both

-cli: 3.4.0
-cross-platform: 3.4.0
runtime: 3.4.0

Please help me to access webview cookies and document height.
Once again cheers for fabulous work.

**Comment by NickIliev** [comment]
@dhananjaykumar880 there is an [upcoming fix ](https://github.com/NativeScript/android-runtime/pull/918)in android-runtime that is about to be patched which will resolve the issue for plugins like nativescript-webview-interface not being built.
Stay tuned for versions 3.4.1 of `tns-android` and you will be able to use nativescript-webview-interface.

Regarding getting the height of your webview - you can use the approach shown [here](https://github.com/NativeScript/NativeScript/issues/224#issuecomment-352378697)

**Comment by dhananjaykumar880** [comment]
@NickIliev thanks for your reply.

But I need it for ios too as currently, I am working on ios.
and you have suggested a stack for height but it will work when interface library will work.
I don't know when will a new version release of tns-android and tns-ios?
