### ISSUE TITLE
JS ERROR Error: Value is not a class

### ISSUE THREAD

**Issue by govi2010** [NativeScript/NativeScript#5245]
Hello everyone, 

I am facing the issue of IOS platform. 

Following is my code. 

```declare class GGLContext {
  static sharedInstance(): any;
};

declare class GIDSignIn {
  static sharedInstance(): any;
};
export class MyDelegate extends UIResponder implements UIApplicationDelegate {
  public static ObjCProtocols = [UIApplicationDelegate];

  applicationDidFinishLaunchingWithOptions(application: UIApplication, launchOptions: any): boolean {
    let gglDelegate = false;
    console.log(JSON.stringify(launchOptions));
    console.log('2');
    try {
      const errorRef = new interop.Reference();
      GGLContext.sharedInstance().configureWithError(errorRef);

      const signIn = GIDSignIn.sharedInstance();
      gglDelegate = true;
    } catch (error) {
      console.log(error);
    }
    return gglDelegate || true;
  }

  applicationOpenURLSourceApplicationAnnotation(application, url, sourceApplication, annotation) {
    console.log('3');
    const gglDelegate = GIDSignIn.sharedInstance().handleURLSourceApplicationAnnotation(url, sourceApplication, annotation); // google login delegate

    return true || gglDelegate;
  }
}```


in Main.ts

```
if (application.ios) {
  application.ios.delegate = MyDelegate;
}```

But i am getting following error. 
I am trying to use `nativescript-social-login` plugin. 

![image](https://user-images.githubusercontent.com/8776031/34678572-873223cc-f4b9-11e7-9bb6-47fe1eae6232.png)

**Comment by jogboms** [comment]
@govi2010 where exactly is line 235:87?

**Comment by govi2010** [comment]
I fixed it by converting my code to ES5 instead of ES6 or ES2015.

**Comment by govi2010** [comment]
You can read here. https://github.com/NativeScript/ios-runtime/issues/818

**Comment by tsonevn** [comment]
Hi @govi2010,
We tested the [demo application](https://github.com/mkloubert/nativescript-social-login/tree/master/demo) provided in the plugin's repository, however, was unable to recreate the same problem. This prevents us from checking if there is a real issue in NativeScirpt or if it related to the plugin.
Regarding that, it would help if you provide more info about your environment(CLI, modules, runtime versions) as well as a sample project, which could be used for debugging.

it would help if you use our template while logging an issue in the future, where is described the needed info, which is needed while investigating a problem.

**Comment by govi2010** [comment]
@tsonevn 
I have anulgar 5 +nativescript project.

I had following Tsconfig.json

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2015",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noEmitHelpers": true,
    "noEmitOnError": true,
    "lib": [
      "es6",
      "dom",
      "es2015.iterable"
    ],
    "baseUrl": ".",
    "paths": {
      "~/*": [
        "app/*"
      ],
      "*": [
        "./node_modules/tns-core-modules/*",
        "./node_modules/*"
      ]
    }
  },
  "exclude": [
    "e2e",
    "node_modules",
    "platforms"
  ]
}
```

I was getting error. 

Then i change my tsconfig to 

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noEmitHelpers": true,
    "noEmitOnError": true,
    "lib": [
      "es6",
      "dom",
      "es2015.iterable"
    ],
    "baseUrl": ".",
    "paths": {
      "~/*": [
        "app/*"
      ],
      "*": [
        "./node_modules/tns-core-modules/*",
        "./node_modules/*"
      ]
    }
  },
  "exclude": [
    "e2e",
    "node_modules",
    "platforms"
  ]
}
```

So now my compiler conver my TS file to Es5 instead of ES2015(ES6)

**Comment by NickIliev** [comment]
Closing as related to [https://github.com/NativeScript/ios-runtime/issues/818](https://github.com/NativeScript/ios-runtime/issues/818)

**Comment by tsonevn** [comment]
Hi @govi2010,

Thank you for the provided solution.

As you already mentioned this problem is logged in issue [#818](https://github.com/NativeScript/ios-runtime/issues/818).  Regarding the fact that this seems to be an iOS runtime problem I would suggest closing this one in favor of the issue in the ios-runtime repository.
