### ISSUE TITLE
http request timeout not working

### ISSUE THREAD

**Issue by terreb** [NativeScript/NativeScript#5247]
### Tell us about the problem
Http request timeout stopped working. Worked fine before 3.3.0.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.3.0
- Cross-platform modules: 3.3.0
- Runtime(s): 3.3.0 (both)

**Comment by NickIliev** [comment]
Hey @terreb can you give more details on how the `timeout` is failing and perhaps provide demo project demonstrating the issue. I have used [this Playground test project ](https://play.nativescript.org/?template=play-tsc&id=0IsMbY)and the timeout option is respected on my side using the `httpbin` test server

**Comment by terreb** [comment]
Hey @NickIliev, sorry for the delay. Yes you're right it works in the playground and in my app too. I had this issue 2 days ago, but now I can not reproduce it. Might be an iOS simulator glitch. Thank you for your time and playground test.
