### ISSUE TITLE
There's a console.log in web-view.ios.ts

### ISSUE THREAD

**Issue by hettiger** [NativeScript/NativeScript#5248]
https://github.com/NativeScript/NativeScript/blob/02dba02e8bd35a270d6e2a8e4db0a18ec89c5615/tns-core-modules/ui/web-view/web-view.ios.ts#L60

This console.log keeps logging null into the console. I think it should be removed.

**Comment by EddyVerbruggen** [comment]
@triniwiz Has already done that in PR #5200.

**Comment by EddyVerbruggen** [comment]
Didn't mean to close btw, please reopen if appropriate.

**Comment by hettiger** [comment]
I have subscribed to the PR, if it won't get merged I'll reopen. Thank you @EddyVerbruggen
