### ISSUE TITLE
Better XML declaration error reporting for non-existing attribute

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#525]
This does not warn nor works:
``` XML
<Border row="1" bakcgroundColor="#FFFFFF">
```
The correct attribute is `backgroundColor`, but the misspelled works flawlessly except it is not applying any background.

**Comment by enchev** [comment]
We left this intentionally because of easy expandos support.

**Comment by PanayotCankov** [comment]
An existing app working with 1.0.0 broke when migrated to 1.2.0 due to the following event:
``` XML
<TabView id="TabView" selectedItemChanged="selectedItemChanged">
```

being changed to:
``` XML
<TabView id="TabView" selectedIndexChanged="selectedIndexChanged">
```

Once again without any warnings.

Can we have somewhat convention for the expandos that will allow us to detect them when used. Similar to the XAML's dot in "owner.attachedProperty", or HTML's "must-have-slash" convention for custom html elements.

**Comment by PanayotCankov** [comment]
`verticalAlignemnt`

**Comment by enchev** [comment]
Implemented in http://docs.nativescript.org/core-concepts/transpilers#installing-xml-validation-against-xsd-schema
