### ISSUE TITLE
Error Platforms IOS

### ISSUE THREAD

**Issue by srcarmi** [NativeScript/NativeScript#5250]
tns run ios --emulator

# file:///app/tns_modules//./bundles/core.umd.js:1091:24: ERROR Error: Uncaught(in promise): ReferenceError: Can't find variable: android

**Comment by tsonevn** [comment]
Hi @srcarmi,
Please provide more info about the problem and your environment(CLI, node, npm, tns-core-modules versions). Also, it would help if you send us sample project, which could be debugged locally.

**Comment by tsonevn** [comment]
duplicated with https://github.com/NativeScript/sample-Groceries/issues/288
