### ISSUE TITLE
ios app is crashing on launch with tns-ios "version": "3.4.0"

### ISSUE THREAD

**Issue by nmongiya** [NativeScript/NativeScript#5256]
```
here is my package.json
"nativescript": {
    "id": "org.fcs.FreshTracker",
    "tns-android": {
      "version": "3.4.0"
    },
    "tns-ios": {
      "version": "3.4.0"
    }
  },
  "dependencies": {
    "@angular/common": "~5.0.0",
    "@angular/compiler": "~5.0.0",
    "@angular/core": "~5.0.0",
    "@angular/forms": "~5.0.0",
    "@angular/http": "~5.0.0",
    "@angular/platform-browser": "~5.0.0",
    "@angular/platform-browser-dynamic": "~5.0.0",
    "@angular/router": "~5.0.0",
    "nativescript-angular": "5.0.0",
    "nativescript-camera": "^3.2.1",
    "nativescript-cardview": "^2.0.4",
    "nativescript-css-loader": "^0.26.1",
    "nativescript-drawingpad": "^2.1.1",
    "nativescript-geolocation": "^4.2.2",
    "nativescript-google-maps-sdk": "^2.4.3",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-pro-ui": "next",
    "nativescript-social-share": "^1.5.0",
    "nativescript-statusbar": "^3.0.1",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^5.5.0",
    "tns-core-modules": "3.4.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~5.0.0",
    "@ngtools/webpack": "~1.8.2",
    "@types/jasmine": "^2.8.3",
    "@types/node": "^7.0.5",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "0.6.0",
    "nativescript-dev-webpack": "^0.9.0",
    "nativescript-worker-loader": "~0.8.1",
    "node-sass": "^4.7.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "^6.0.6",
    "tns-platform-declarations": "3.4.0",
    "typescript": "~2.4.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  },
  "scripts": {
    "update-ns-webpack": "update-ns-webpack",
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install"
  }
```

**Comment by nmongiya** [comment]
i am trying on ios11.2

**Comment by nmongiya** [comment]
I tried 
tns debug ios
tns run ios -- bundle
tns run ios as well, result is the same
`Project successfully built.
Installing...
Successfully installed on device with identifier '83388787-BAC0-40AF-B45C-CD0397EA0C08'.
Successfully transferred all files.
Refreshing application...
Successfully synced application org.fcs.FreshTracker on device 83388787-BAC0-40AF-B45C-CD0397EA0C08.
Executing before-watch hook from /---/Mobile/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 2.4.2
17:02:32 - Compilation complete. Watching for file changes.`

**Comment by tsonevn** [comment]
Hi @nmongiya,
I notice that you are using @next version for `nativescript-pro-ui`. I would suggest replacing the `next` version with the latest official one `3.3.0`. For example:
`"nativescript-pro-ui": "3.3.0",`

Then remove the platform with `tns platform remove ios` command. Delete `node_modules` and `hooks` folders and rebuild the application with `tns run ios`.

If the problem persists, please send us the project, which will help us to investigate the case.

**Comment by nmongiya** [comment]
@tsonevn I think the problem lies with web-view in latest release.
I have uninstalled everything and made a fresh start.
npm install -g nativescript
tns create HelloWorld --template nativescript-template-ng-tutorial
in my app.component.html I am using as webview 
`<GridLayout rows="75 250 50" sdkExampleTitle sdkToggleNavButton>
    <GridLayout row="0" rows="*" columns="50 *" class="form">
        <Button class="btn btn-primary btn-active icon" row="0" col="0" text="&#xea44;" (tap)="goBack()"></Button>
        <TextField #urlField row="0" col="1" hint="Enter URL" [text]="webViewSrc" returnKeyType="done" (returnPress)="submit(urlField.text)"
            autocorrect="false" verticalAlignment="center" class="input input-border m-t-0" autocapitalizationType="none"></TextField>
    </GridLayout>
    <WebView row="1" #myWebView [src]="webViewSrc"></WebView>
    <Label row="2" #labelResult></Label>
</GridLayout>`
and in my .ts public webViewSrc: string = 'http://www.freshcomputers.com.au/' ;
that is not working. 
I tried with many other urls and some of them are working(e.g. http://google.com, hello.com) and some of them are not, they are just a blank white page
and in console it is showing file:///app/tns_modules/tns-core-modules/ui/web-view/web-view.js:59:28: null

**Comment by nmongiya** [comment]
Thank You @tsonevn , you can close the issue now. Cheers !!
