### ISSUE TITLE
Android: Custom SDK integration

### ISSUE THREAD

**Issue by MherX** [NativeScript/NativeScript#5260]
Hi all!

I'm new to this topic so please forgive me and help ))
I wrote a small app which communicates with my API, but now we have to integrirovanii third-party SDK but unfortunately I don't know how to do it, pozhaluista prompt where it is possible about atmo to poistat where you can see examples and how to do it better. 
Here is the link for SDK http://www.generalscan.com/en-us/gs-sdk-en.php

Тhank you in Advance.

**Comment by tsonevn** [comment]
Hi @MherX,
First of all, thank you for your interest in NativeScript.
in your case, you could create a custom NativeScript plugin, which implements the needed functionality form your SDK. 
More about this topic you could find in the below-attached links from NativeScript docs.
https://docs.nativescript.org/plugins/building-plugins
https://docs.nativescript.org/runtimes/android/plugins/plugins
Also as starting point, you could use our [nativescript-plugin-seed](https://github.com/NativeScript/nativescript-plugin-seed)

Hope this helps

**Comment by MherX** [comment]
Hi @tapcore Thank you very much for the help!
I understood about how and what to do if you I still haven't shut until you understand.
Thank you for the work done and for a good product!!!
