### ISSUE TITLE
get system time both ios and android

### ISSUE THREAD

**Issue by peppeg85** [NativeScript/NativeScript#5264]
hello everyone, how can i take the system time in nativescript both on ios and android? is there some documentation? tank you

**Comment by EddyVerbruggen** [comment]
Wouldn't that simply be `new Date()`?

**Comment by tsonevn** [comment]
Hi @peppeg85,
Could you provide some more info about your case and if the provided solution from @EddyVerbruggen  is applicable to your scenario?

**Comment by peppeg85** [comment]
hi, thanks for the answers, i still don't try the solution provided from @EddyVerbruggeni I need to take the system time (hour:minutes:sec) and send to an arduino by bluetooth LE that will update an RTC to have it always with the right time. 
moreover i need to create a scheduler like the android alarm clock to set the times and days of the device to be on and off. 
thanks for the support
