### ISSUE TITLE
Android app failing to re-install

### ISSUE THREAD

**Issue by lin-brian-l** [NativeScript/NativeScript#5267]
The app installs on my phone as expected when using "tns run android", but after uninstalling the app from my phone, "tns run android" does not reinstall the app. Instead, I get a long list of text with the following error message (the app was named "testing4"): 

ActivityManager: Force stopping org.nativescript.testing4 appid=10247 user=-1: installPackageLI
ActivityManager: Skipping broadcast of Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:org.nativescript.testing4 flg=0x4000010 (has extras) }: user 10 is stopped
ActivityManager: Skipping broadcast of Intent { act=android.intent.action.PACKAGE_ADDED dat=package:org.nativescript.testing4 flg=0x4000010 (has extras) }: user 10 is stopped
ActivityManager: Skipping broadcast of Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:org.nativescript.testing4 flg=0x4000010 (has extras) }: user 10 is stopped
ActivityManager: Skipping broadcast of Intent { act=android.intent.action.MY_PACKAGE_REPLACED flg=0x4000010 pkg=org.nativescript.testing4 (has extras) }: user 10 is stopped
ActivityManager: Force stopping org.nativescript.testing4 appid=10247 user=0: from pid 4726
System.err: android.content.pm.PackageManager$NameNotFoundException: org.nativescript.testing4
System.err: 	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:373)
System.err: 	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:355)
System.err: 	at com.android.server.am.ActivityManagerService.dumpUids(ActivityManagerService.java:15465)
System.err: 	at com.android.server.am.ActivityManagerService.dumpProcessesLocked(ActivityManagerService.java:15571)
System.err: 	at com.android.server.am.ActivityManagerService.dump(ActivityManagerService.java:15279)
System.err: 	at android.os.Binder.doDump(Binder.java:512)
System.err: 	at android.os.Binder.dump(Binder.java:502)
System.err: 	at android.os.Binder.onTransact(Binder.java:452)
System.err: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4256)
System.err: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2935)
System.err: 	at android.os.Binder.execTransact(Binder.java:674)
System.err: android.content.pm.PackageManager$NameNotFoundException: org.nativescript.testing4
System.err: 	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:373)
System.err: 	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:355)
System.err: 	at com.android.server.am.ActivityManagerService.dumpUids(ActivityManagerService.java:15465)
System.err: 	at com.android.server.am.ActivityManagerService.dumpProcessesLocked(ActivityManagerService.java:15577)
System.err: 	at com.android.server.am.ActivityManagerService.dump(ActivityManagerService.java:15279)
System.err: 	at android.os.Binder.doDump(Binder.java:512)
System.err: 	at android.os.Binder.dump(Binder.java:502)
System.err: 	at android.os.Binder.onTransact(Binder.java:452)
System.err: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4256)
System.err: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2935)
System.err: 	at android.os.Binder.execTransact(Binder.java:674)

My CLI version is 3.3.1. I ran into this problem with an app that I am developing and reproduced it by creating new projects Angular2 with the default "Hello World" template, so the repo "testing4" is just the default template. It seems as though the problem would be resolved by copy+pasting the code in my current project into a new project, but is there anything else I can do?

**Comment by tsonevn** [comment]
Hi @lin-brian-l,
First of all thank you for your interest in NativeScript .
Could you provide some sample project, where the problem could be reproduced and also could be used for debugging? It would also help if you provide more info about your device or simulator, which you used for testing.
In the meantime I would suggest installing the latest version of NativeScript 3.4 -> `npm install  nativescript --g`. Then try to create a new project -> `tns create testProject --ng` and build it with `tns run android`.

**Comment by lin-brian-l** [comment]
Hi @tsonevn, thanks for your response.

I've provided a sample project [here](https://github.com/lin-brian-l/testing4); it's the default "hello world" template that's used when generating a new NativeScript project with Angular. I haven't tested whether reinstalling after an uninstall will work on an emulator, but I am using a Google Pixel. 

I've been able to continue on my project by creating a new project directory, but I am wary about updating to NativeScript 3.4 since I don't want to potentially introduce any bugs and thereby don't know if my issue would be fixed by updating. Is it possible to have different versions of NativeScript for different directories?

**Comment by tsonevn** [comment]
Hi @lin-brian-l,
Thank you for the sample project.
I tested it on my side, however, the application seems to be build and deployed properly while using NativeScript 3.4 as well as the old version 3.3.
Something that you could try is to check if there is an alive adb process, which could block the app deployment and kill [adb if is need](https://stackoverflow.com/a/29826345/6133327). You could also to clear up the cache with `npm  clear cache.`

 To be sure that everything is up to date you could delete all data associated with the application on the device ->`adb shell pm clear com.yourapp.package` and to start the app deploying from a clear state.

**Comment by lin-brian-l** [comment]
Hi @tsonevn, thanks for the tips. I tried deleting the adb process and clearing the npm cahce, but neither of those solutions worked. However, I have continued my project in a new directory and it seems that my issue of re-installing an app after deleting it cannot be replicated; I appreciate the help, but it seems like this should be discontinued unless others experience this problem.
