### ISSUE TITLE
tap event at transparent part in modal page 

### ISSUE THREAD

**Issue by yclau** [NativeScript/NativeScript#5269]
## Please, provide the details below:
I trying use modal page shown invitation form but i getting a problem , how I can close modal page when click transparent part? I try add tap event in Page , but no have effect. 

xml
```
<Page 
    xmlns="http://schemas.nativescript.org/tns.xsd" shownModally="onShownModally" backgroundColor="transparent" tap="onCancel">
    <GridLayout rows="auto,auto, auto " columns="*" horizontalAlignment="center" verticalAlignment="center" backgroundColor="#ffffff" margin="20">
        <StackLayout class="primary-background-color" horizontalAlignment="stretch">
            <Label margin="10" color="#ffffff" text="Invite a friend to JOD" horizontalAlignment="center" class="h4"/>
        </StackLayout>
        <StackLayout horizontalAlignment="stretch" row="1">
            <Label text="Enter your friend's details:" padding="10"/>
            <GridLayout columns="*,*">
                <TextField hint="First Name" padding="10"/>
                <TextField hint="Last Name" col="1" padding="10"/>
            </GridLayout>
            <TextField hint="Email Address" padding="10"/>
        </StackLayout>
        <Button row="2" text="Invite" tap="onOk" color="#ffffff" backgroundColor="#159200" height="60"/>
    </GridLayout>
</Page>
```

JS
```
var context,closeCallback,page;  

exports.onShownModally = function(args) { 
    page = args.object; 
    context = args.context;
    closeCallback = args.closeCallback; 
}
 
exports.onCancel = function(args){
    closeCallback(); 
}

exports.onInvite = function(args){ 
     closeCallback(); 
}
```

**Comment by tsonevn** [comment]
Hi @yclau,
Thank you for the providing the sample code.
If I understand your case correctly, you are looking for a way to close the modal page, when it is tap out of the TextFields or Button.
I tested the code snippet in sample project while using NativeScirpt 3.4 and the tap event on the Page seems to work as expected on Android.
However on iOS you the event will not be consumed by the TextField, which is iOS specific behavior, and the modal page will be closed on every tap. To solve this you could set a flag property, which could be used to stop the execution of the page `closeCallback`
 method while the TextField is tapped.
For your convenience, I am attaching a sample project. Please review it and verify if it is applicable to your scenario.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/1631519/Archive.zip)
