### ISSUE TITLE
Feature Request - Web Audio API implementation

### ISSUE THREAD

**Issue by jamesharvey2** [NativeScript/NativeScript#5270]
Hello NativeScript,

Would you please implement complete Web Audio API to NativeScript? 

Web Audio API is already a very complete audio solution which has all necessary features for any audio app development. 
Right now, it's only possible to use it on WebView layer on native apps. Cordova for instance can use this but I would like to be able to use it on NativeScript.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API

https://www.html5rocks.com/en/tutorials/webaudio/intro/

Please make this work on NativeScript then I will be developing apps on NativeScript for a long time.

Thanks,

**Comment by NickIliev** [comment]
@jamesharvey2 in NativeScript you can access the native WebView for both Android and iOS platforms and implement the functi9onallity that is supported by the native controls.

TypeScript example:

```TypeScript
let webview = <WebView>page.getViewById("myWebView");
let androidNativeWebView = webview.android;
```

From this point, you have the native layer and can do what the native Android developers can do

**Comment by jamesharvey2** [comment]
Hi, thanks for your response. 
I know I can use WebView in NativeScript. However I'm not sure what you mean by these. 
Do you mean I will be able to build native UI while using web audio API? 
That's my goal... I want build native UI which can use web audio api.

**Comment by NickIliev** [comment]
@jamesharvey2 if there is a native way to implement Web Audio API than you should be able to do it via NativeScript by accessing the native APIs. Or if there is a wrapper library in Android than you can create a NativeScript plugin.

**Comment by jamesharvey2** [comment]
Thanks Nicklliev, I will look into it. 
I'm curious if I can get audio output of web audio api connected  to native android audio output. 
On the other hand, it would be great if NativeScript ships with web audio capability. Web audio already has everything for audio. It has delays, reverb, convolution reverb, oscillators, distortion, etc.

**Comment by rickdps** [comment]
Hi jamesharvey2. Have you got any solution for this. I am having the same problem. Maybe we can work together to come up with this plug in.

**Comment by stdangerous** [comment]
Any word from NativeScript on this? I also need the features provided by Web Audio API for a project.

**Comment by triniwiz** [comment]
The news is a bit late but there is a new plugin for this [@nativescript/audio-context](https://github.com/NativeScript/canvas/tree/master/packages/audio-context). Do give it a try and report any issues. 

Thank you
