### ISSUE TITLE
Burger menu doesn't work on http://docs.telerik.com/devtools/nativescript-ui

### ISSUE THREAD

**Issue by bearoutthere** [NativeScript/NativeScript#5275]
On my multi-screen setup i keep the documentation site on the side 23" monitors that are in portrait orientation. At that width the left navigation panel collapses into the hamburger menu.  Unfortunately when clicking on that menu nothing happens. I have to keep resizing the browser window in order to navigate. I've tried in Chrome and FF on Ubuntu 17.04.  It's broken in both browsers.  Not a big deal, but it's inconvenient and doesn't look good for the brand.
Just thought you'd want to know.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/docs#1043
