### ISSUE TITLE
Question about plugin

### ISSUE THREAD

**Issue by mobilemindtec** [NativeScript/NativeScript#5276]
Hi,

How can I create a Composite Component plugin that use another ui plugin? For example, my plugin need of `nativescript-grid-view` to create my ui view. My xml plugin looks like then:

```
<GridLayout  xmlns="http://schemas.nativescript.org/tns.xsd"  xmlns:gv="nativescript-grid-view">

</GridLayout> 
```

But when I use the plugin, this error is showed:

```
System.err: Error: Building UI from XML. @file:///app/main-page.xml:32:9
System.err:  > Module '/data/data/org.nativescript.demo/files/app/tns_modules/nativescript-calendar-inline' not found for element 'nativescript-calendar-inline:Calendar'.
System.err:    > Building UI from XML. @file:///app/tns_modules/nativescript-calendar-inline/calendar.xml:13:3
System.err:    > Module '/data/data/org.nativescript.demo/files/app/nativescript-grid-view' not found for element 'nativescript-grid-view:GridView'.
System.err:    > com.tns.NativeScriptException: Failed to find module: "/data/data/org.nativescript.demo/files/app/nativescript-grid-view", relative to: app//
```

Thanks!

**Comment by NickIliev** [comment]
@mobilemindtec depending on a third-party plugin to create another plugin might not be a good idea (any changes in the plugin might break your implementation and you might need to re-write the logic).

However, this is doable by using the wanted plugin as a dependency and then reusing the needed logic.
Real-life example can be found in nativescript-imagepicker reusing nativewscript-pro-ui (`RadListView` in specific), Here is [the dependency](https://github.com/NativeScript/nativescript-imagepicker/blob/master/src/package.json#L53)  and here is [the actual implementation reusing the RadListView](https://github.com/NativeScript/nativescript-imagepicker/blob/c98cb2f46e34e2ac1555559b2ffc4b0af3bc8471/src/images.ios.ts#L36-L82).
