### ISSUE TITLE
Switch: Not able to listen for checkedChange event from XML

### ISSUE THREAD

**Issue by manojdcoder** [NativeScript/NativeScript#5279]
### Tell us about the problem
When `checkedChange` event is added via XML it doesn't fire at all (binding event / adding one via JS still works).

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.1
- Cross-platform modules: 3.4.0
- Runtime(s): 3.4.1

### Please tell us how to recreate the issue in as much detail as possible.
https://play.nativescript.org/?template=play-js&id=a7hjAi

**Comment by tsonevn** [comment]
Hi @manojdcoder,
After the changes in 3.0 the `propertyChange` was deprecated and the appropriate way at this time to handle the checked change event is to register a listener from code behind. For example, you could register a new listener on Switch loaded event:
XML
```
<StackLayout class="p-20">
    <Switch loaded="swloaded"  />
    
    </StackLayout>
```
TypeScript
```
export function swloaded(args){
    var swichcomp = <Switch>args.object;
    swichcomp.on("checkedChange", (args:EventData)=>{
        console.log("checkedChange");
        console.log((<Switch>args.object).checked)
    })
}
```
Also, I found that this topic has been discussed in [this](https://github.com/NativeScript/NativeScript/issues/3971) issue.  I will suggest keeping the conversation on the other issue, where you could also leave your comment.

**Comment by manojdcoder** [comment]
I noticed that issue already but I was assuming only the high level`propertyChange` event was not possible but specific property change events like `textChange` on TextField / `checkedChange` on Switch may be possible. But I understood now, thanks for the clarification @tsonevn.
