### ISSUE TITLE
Build errors after removing plugin

### ISSUE THREAD

**Issue by MisterMunchkin** [NativeScript/NativeScript#5282]
## Please, provide the details below:
Hi, I wanted to remove a plugin called nativescript-accordion because I don't need it anymore then once I ran the build it gave me this error:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Android\Nativescript\Unwind\platforms\android\app\build.gradle' line: 234

* What went wrong:
A problem occurred evaluating project ':app'.
> C:\Android\Nativescript\Unwind\node_modules\nativescript-accordion\package.json (The system cannot find the path specified)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Unable to apply changes on device: G9AXGY09D701H9J. Error is: Command gradlew.bat failed with exit code 1.Executing after-watch hook from C:\Android\Nativescript\Unwind\hooks\after-watch\nativescript-dev-sass.js

### Which platform(s) does your issue occur on?
iOS/Android/Both
This happens on android, haven't tested it out on iOS yet

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.1
- Cross-platform modules: 3.4.0
- Runtime(s): tns-android: 3.4.1
                      tns-ios: 3.4.1

**Comment by tsonevn** [comment]
Hi @MisterMunchkin,
Thank you for contacting us.
From the provided info I would suggest verifying if you have removed the whole code related to the `nativescript-accordion` plugin in your project. Also remove the platforms via `tns platform remove android` and `tns platform remove ios` commands. Delete `node_modules` and `hooks` folders and try to rebuild the application with `tns run <platform_name>`.

If the problem persists, please provide more info about the issue. It would help if you could send us the project, which will allow us to debugged it locally and to verify, what is causing the issue.

**Comment by MisterMunchkin** [comment]
Hi, sorry for not replying sooner. I've been really busy working on my
thesis. Thank you for your response and I will try the suggestions you have
given me.
