### ISSUE TITLE
rxjs/Observable notification receive multiple times

### ISSUE THREAD

**Issue by smartsanja2013** [NativeScript/NativeScript#5283]
I am using rxjs/Observable to notify selected tabIndex to other components. 
In tab component
````
onSelectedIndexChanged(args: SelectedIndexChangedEventData) {
        const tabView = <TabView>args.object;
        this.tabIndex = tabView.selectedIndex;
        let message = {
            "tabIndex" : this.tabIndex,
        };
        this.notifyService.send(JSON.stringify(message));
    }
````

In other component constructor
```
// check the notify from tab component
       this.notifyService.get().subscribe(result =>{
           let message = JSON.parse(result);
           if(message["tabIndex"]=="1"){
           this.doSomething();     
          }
       });
```
notify service

```
import { Injectable } from "@angular/core";
import { Observable } from "rxjs/Observable";
import { Subject } from "rxjs/Subject";

@Injectable()
export class NotifyService{

    private subject = new Subject<any>();

    send(message: any) {
        this.subject.next(message);
    }

    get(): Observable<any> {
        return this.subject.asObservable();
    }
}
```

Problem is, notification receive multiple times. Any way to remove the notification observer after 1st time received?

**Comment by NickIliev** [comment]
@smartsanja2013 perhaps you can call `unsubscribe` when needed  as discussed [here](https://stackoverflow.com/a/37338340/4936697).

Note that this repository is for logging issues, bugs, and features related to NativeScript modules. For how-to related questions please use the community channels like [https://discourse.nativescript.org/](https://discourse.nativescript.org/), [SO ](https://stackoverflow.com/questions/tagged/nativescript)or the [NativeScript community channel.](https://nativescriptcommunity.slack.com/messages/general)
