### ISSUE TITLE
TextField underline color

### ISSUE THREAD

**Issue by bori87** [NativeScript/NativeScript#5286]
Is there way to style with css TextField underline color, underline color when focused and cursor color?
![textfield](https://user-images.githubusercontent.com/29092029/35064579-dd84cabe-fbca-11e7-9533-7f7207b97083.png)

**Comment by tsonevn** [comment]
Hi @bori87,
You could setup bottom border to the TextField and to set the needed color to it. For example:
XML
```
<StackLayout class="p-20">
        <TextField class="tfstyle" hint="" text="{{  }}" />
        
    </StackLayout>
```

TypeScript 
```
.tfstyle{
    border-bottom-width: 1;
    border-color:red; 
}
```
For further question please use our [forum](https://discourse.nativescript.org/) or [StackOverflow thread.](https://stackoverflow.com/questions/tagged/nativescript)

**Comment by bori87** [comment]
I know this but i dont know how to change textField focused state bottom border with css. Also i would like to know how to change CURSOR color in textField.
