### ISSUE TITLE
Changing ActionBar options icon color.

### ISSUE THREAD

**Issue by bori87** [NativeScript/NativeScript#5289]
Is there way to change options icon color? I added colorControlNormal to AppThemeBase but it also affecting other elements like TextField underline color.

```xml
    <style name="AppThemeBase" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="toolbarStyle">@style/NativeScriptToolbarStyle</item>
        <item name="colorPrimary">@color/ns_primary</item>
        <item name="colorPrimaryDark">@color/ns_primaryDark</item>
        <item name="colorAccent">@color/ns_accent</item>

<!--- new color -->
        <item name="colorControlNormal">#fff</item>
    </style>

```
![options](https://user-images.githubusercontent.com/29092029/35090051-df58978a-fc38-11e7-9f24-e4007e65fa4b.png)

**Comment by NickIliev** [comment]
@bori87 modifying the colorControlNormal is the way to change the options color.
However, as noticed this would also apply the theme to other controls as well so you would need to overwrite the colors.

For TextField there is a workaround by using `blur` and `focus` event to apply bottomBorder and this way overwrite the default underline color while in the same time preserve the changing of the colors while the field is in focus.

e.g.
```XML
<TextField hint="Some textfield" 
    borderBottomWidth="1" 
    borderColor="{{ myTFUnderlineColor }}" 
    blur="onBlur" 
    focus="onFocus" />
```

and then in the code behind change the colors via view-model and the `focus` and `blur` events
```TypeScript
export function onFocus(args) {
    console.log("onFocus")


    if (vm.get("myTFUnderlineColor") === "red") {
        vm.set("myTFUnderlineColor", "blue");
    } else {
        vm.set("myTFUnderlineColor", "red");
    }
}

export function onBlur(args) {
    console.log("onBlur")

    if (vm.get("myTFUnderlineColor ") === "red") {
        vm.set("myTFUnderlineColor", "blue");
    } else {
        vm.set("myTFUnderlineColor", "red");
    }
}
```

Demonstration of the above code can be found [here](https://github.com/NickIliev/NS-Issues-2018/tree/master/NativeScript/issue_5289)
