### ISSUE TITLE
NativeScript Throwing Error Response with status: 200 for URL: null when passing search and filter value as an Object instead of string

### ISSUE THREAD

**Issue by san18793** [NativeScript/NativeScript#5290]
I am using Angular4 with TypeScript version 2.2.2

My web app is running fine when I call JSON with Filters but my NativeScript app fails when I call the Filter Values as an Object but works fine when I call filter values as a string.

Error Response with status: 200 for URL: null

THIS WORKS 
https://domainname.com/api/v1/searchevents?token=057001a78b8a7e5f38aaf8a682c05c414de4eb20&filter=text&search=upcoming

If the filter value and search value is STRING it works whereas if they are objects as below, it does not work

THIS DOES NOT WORK 

https://api.domainname.com/api/v1/searchevents?token=057001a78b8a7e5f38aaf8a682c05c414de4eb20&filter={"limit":"12","skip":"0"}&search={"search":"","latitude":"","longitude":"","categories":"","address":"","type":"upcoming"}
----------------------------------------------
The Code I used is below

getData(serverUrl, type, skip_limit) {

    console.log(serverUrl);
    let headers = this.createRequestHeader();
    let token_value = localStorage.getItem('access_token')

    let url;
    var filter;

    filter = '{"limit":"10","skip":"0"}'
    url = this.apiUrl + serverUrl + '?token=' + token_value + '&filter=' + filter
    return this.http.get(url, { headers: headers })
        .map(res => res.json());
}
The URL as formed above for the API is fine and works fine. Yet the error comes Error Response with status: 200 for URL: null

CAN ANYONE HELP ME SOLVE THIS?

**Comment by NickIliev** [comment]
@san18793  please keep this repository for logging issues, bugs and features related to NativeScript modules.

For how-to related questions please use the community channels like [https://discourse.nativescript.org/](https://discourse.nativescript.org/), [SO ](https://stackoverflow.com/questions/tagged/nativescript)or NativeScript community slack channel

Regarding your question - take a look at the request headers you are passing. Also notice that the link you have posted is not working .

**Comment by san18793** [comment]
Got the solution: All you have to do is encode the Filter and Search Parameters if it is an Object or Array using Typescript encodeURI()

var filter = '{"limit":"12","skip":"0"}'

var search = '{"search":"","latitude":"","longitude":"","categories":"","address":"","type":"upcoming"}'

var encoded_filter = encodeURI(filter);

var encoded_search = encodeURI(search);

url = this.apiUrl+serverUrl+'?token='+token_value+'&filter='+encoded_filter+'&search='+encoded_search
