### ISSUE TITLE
ListPicker: How to get the selected index value & event name in js.

### ISSUE THREAD

**Issue by priyangamani** [NativeScript/NativeScript#5292]
1.SelectedIndexChanged function is not working.How to get the index value as per the list item click.
2.Is there any way to  remove the  divider line in listPicker.(I tried textdecoration:none style but it doesn't work.) 
<ListPicker id="listPicker" verticalAlignment="center"  horizontalAlignment="center"  items="{{items}}" selectedIndex="0" selectedIndexChange="selectedIndexChanged"></ListPicker>

**Comment by tsonevn** [comment]
Hi @priyangamani,
Thank you for contacting us.
To be able to handle `SelectedIndexChange` event you should define a listener via the code behind. similar topic has been described [here](https://github.com/NativeScript/NativeScript/issues/3971). For your convenience I am attaching sample project:

About the second question at this time the separator of the Items in ListPicker cannot be styled. Regarding that, you could log a new feature request for implementing such a functionality.

Hope this helps.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1642646/Archive.zip)
