### ISSUE TITLE
iOS Upload App Failed 

### ISSUE THREAD

**Issue by pap5508** [NativeScript/NativeScript#5294]
I am trying to upload app to App store in iOS. I am getting following error after succesfully archive project and Export IPA file 

I am getting this error only when trying to upload to app store. 

![screen shot 2018-01-18 at 14 16 39](https://user-images.githubusercontent.com/8488715/35099975-524c970c-fc5a-11e7-9982-9650e41c55c0.png)

Thank you..

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3326
