### ISSUE TITLE
ListPicker visibility is not working.

### ISSUE THREAD

**Issue by priyangamani** [NativeScript/NativeScript#5297]
I tried to set the visibility in Listpicker but it's not working in both android and ios.

```
<ListPicker id="listPicker" loaded="selectedIndexChanged" row="0" style="color:#081D2D;"  items="{{items}}" selectedIndex="{{selectedIndex}}" visibility="{{ screen=='close'  ? 'collapsed' : 'visible' }}"></ListPicker>
```

//Js
 pageData.set("screen", "close");
  page.bindingContext = pageData;

**Comment by tsonevn** [comment]
Hi @priyangamani,

We reviewed your case, however, we were unable to recreate similar issue as the reported one while using NativeScript 3.4. For your convenience, I am attaching sample project and GIF files for both Android and iOS, which demonstrates how the project works. 
 
Please review the project and make the needed changes, which will allow us to recreate the issue. Also provide info about your environment(CLI, runtime versions)
![screencast 2018-01-19 at 11 27 05 am](https://user-images.githubusercontent.com/17448734/35144203-86010148-fd0c-11e7-9aeb-816ab15f5635.gif)
![screencast 2018-01-19 at 11 29 52 am](https://user-images.githubusercontent.com/17448734/35144204-8623c0b6-fd0c-11e7-8c4e-6ac06a7b3b4a.gif)

[Archive.zip](https://github.com/NativeScript/NativeScript/files/1645936/Archive.zip)
