### ISSUE TITLE
Modal Dialog on IOS - Transparency issue

### ISSUE THREAD

**Issue by shabib3** [NativeScript/NativeScript#5306]
Hi,

Trying to create non-fullscreen modal dialog on IOS, and without success.
I've notice that I cannot create a fullscreen modal dialog on IOS [here](https://docs.nativescript.org/core-concepts/navigation#modal-pages).

But after some search I saw [this solution](https://github.com/NativeScript/nativescript/issues/2086#issuecomment-221956483) do the job but I kind of don't get how to fully implement this solution.

There is a chance for getting help here about this thing? :)

Thanks a lot!

**Comment by shabib3** [comment]
@mobilemindtec @NickIliev

**Comment by jogboms** [comment]
@shabib3 "By design on iPhone, a modal page appears only in fullscreen."
Qouted from the docs.

**Comment by shabib3** [comment]
@jogboms - I know this is why I mention that I saw that and also saw that there is workaround that I don't get how to implement it

**Comment by mobilemindtec** [comment]
Hi @shabib3,

I was able to create a transparent dialog for IOS by making a change in the module `page.ios.js`.

http://4minds.com.br/blog/NativeScript-transparent-modal

On module `page.ios.js`  function `_showNativeModalView`, change:

```
_super.prototype._raiseShowingModallyEvent.call(this);
parent.ios.presentViewControllerAnimatedCompletion(this._ios, utils.ios.MajorVersion >= 7, null);
var transitionCoordinator = parent.ios.transitionCoordinator();
if (transitionCoordinator) {
    UIViewControllerTransitionCoordinator.prototype.animateAlongsideTransitionCompletion.call(transitionCoordinator, null, function () { return _this._raiseShownModallyEvent(); });
}
else {
    this._raiseShownModallyEvent();
}
```

To

```
_super.prototype._raiseShowingModallyEvent.call(this);

var that = this
this._ios.providesPresentationContextTransitionStyle = true;
this._ios.definesPresentationContext = true;
this._ios.modalPresentationStyle = UIModalPresentationOverFullScreen;
this._ios.view.backgroundColor = UIColor.clearColor(); // can be with 'alpha'

parent.ios.presentViewControllerAnimatedCompletion(this._ios, utils.ios.MajorVersion >= 8, function(){
    that._ios.modalPresentationStyle     = UIModalPresentationCurrentContext;
    that._raiseShownModallyEvent(parent, context, closeCallback)            
});
```

I hope it helped you!

**Comment by shabib3** [comment]
Hi @mobilemindtec - Thanks for the comment! :)

I tried it just now and it right me in the console the following error:
```
CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1389:24: ERROR Error: Uncaught (in promise): TypeError: UIColor.clearColor is not a function. (In 'UIColor.clearColor()', 'UIColor.clearColor' is an instance of UIColor)
```

any idea?

**Comment by mobilemindtec** [comment]
Ok, this code é a little old... to get IOS color use:

```
var clearColor = utils.ios.getter(UIColor, UIColor.clearColor)
```

Here's how to call the `utils` module, which should already be present in the `page.ios.js` module and correct the name.

**Comment by shabib3** [comment]
@mobilemindtec 
Ok so,

Now it looks like this:
```
var uiUtils = require("../../ui/utils");
var utils_1 = require("../../utils/utils");
var getter = utils_1.ios.getter;
...
...
...
_super.prototype._raiseShowingModallyEvent.call(this);

var that = this
this._ios.providesPresentationContextTransitionStyle = true;
this._ios.definesPresentationContext = true;
this._ios.modalPresentationStyle = UIModalPresentationOverFullScreen;
this._ios.view.backgroundColor = getter(UIColor, UIColor.clearColor) // can be with 'alpha'

parent.ios.presentViewControllerAnimatedCompletion(this._ios, uiUtils.ios.MajorVersion >= 8, function () {
    that._ios.modalPresentationStyle = UIModalPresentationCurrentContext;
    that._raiseShownModallyEvent(parent, context, closeCallback)
});
```

take a look on those following change I did from the first code sample that you've send:
`this._ios.view.backgroundColor = UIColor.clearColor(); // can be with 'alpha'`
became:
`this._ios.view.backgroundColor = getter(UIColor, UIColor.clearColor) // can be with 'alpha'`
and
`parent.ios.presentViewControllerAnimatedCompletion(this._ios, utils.ios.MajorVersion >= 8,`
became:
`parent.ios.presentViewControllerAnimatedCompletion(this._ios, uiUtils.ios.MajorVersion >= 8, `

Notice that:
`utils.ios.getter` is now `getter`
and 
`utils` is now `uiUtils`

because this is how I think that it is declared in the `page.ios.js` (attached the declare code in the beginning of the sample) - correct me if I wrong.

Now, It doesn't throw any error, but it doesn't seems to work.

Just so you know, I call the open modal dialog method exactly like in android:
```
let options: ModalDialogOptions = {
    viewContainerRef: params.vcRef,
    context: {
        title: params.title,
        actionsData: params.actionsData
    },
    fullscreen: false
};
return this._modalService.showModal(ActionPickerModalDialogComponent, options);
```

Thanks a lot! :)

**Comment by shabib3** [comment]
@mobilemindtec - sorry! works just awesome! thanks a lot :)

**Comment by tsonevn** [comment]
duplicated with [#2086](https://github.com/NativeScript/nativescript/issues/2086)
