### ISSUE TITLE
application.android.foregroundActivity is undefined

### ISSUE THREAD

**Issue by Pip3r4o** [NativeScript/NativeScript#5307]
_From @debevv on January 20, 2018 18:25_

### Tell us about the problem
I really don't know if this is intended behaviour, but on both my application and a fresh javascript template the `foregroundActivity` member of `application.android` is always undefined. I noticed it because
this breaks [nativescript-plugin-google-places](https://github.com/tylergrinn/nativescript-plugin-google-places).

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.1
- Cross-platform modules: 3.4.0
- Runtime(s): 3.4.1
- Plugin(s):
```
         "moment": "^2.19.3",
	"nativescript-facebook": "^2.1.0",
	"nativescript-plugin-google-places": "^1.4.1",
	"nativescript-pro-ui": "^3.3.0",
	"nativescript-theme-core": "^1.0.4",
	"tns-core-modules": "^3.4.0"
```
I'm testing the app inside an Android Oreo emulator.

### Please tell us how to recreate the issue in as much detail as possible.
- Create a new project (`tns create Test')
- `console.log(application.android.foregroundActivity)` in `app/main-page.js` prints `undefined`

_Copied from original issue: NativeScript/android-runtime#927_

**Comment by NickIliev** [comment]
@debevv the template application is hooked on the `navigatingTo` lifecycle event.
To get a reference to the `foregroundActivity` you will need `navigatedTo` event to be fired

For example:
```
var application = require("application");

function onNavigatingTo(args) {
    console.log("============= onNavigatingTo =============");
    console.log("foregroundActivity: " + application.android.foregroundActivity); // undefined in navigatingTo
    console.log("startActivity: " + application.android.startActivity);
}
exports.onNavigatingTo = onNavigatingTo;

function onLoaded(args) {
    console.log("============= onLoaded =============");
    console.log("foregroundActivity: " + application.android.foregroundActivity); // undefined in loaded
    console.log("startActivity: " + application.android.startActivity);
}
exports.onLoaded = onLoaded;

function onNavigatedTo(args) {
    console.log("============= onNavigatedTo =============");
    console.log("foregroundActivity: " + application.android.foregroundActivity); // HERE
    console.log("startActivity: " + application.android.startActivity);
}
exports.onNavigatedTo = onNavigatedTo;
```

Demonstration application can be found [here](https://github.com/NickIliev/NS-Issues-2018/tree/master/NativeScript/issue_5307)

**Comment by NickIliev** [comment]
Logged [an issue in the plugin's repository ](https://github.com/tylergrinn/nativescript-plugin-google-places/issues/4)- closing this as related.

**Comment by NickIliev** [comment]
As 'startActivity' is [marked as deprecated in the source-code](https://github.com/NativeScript/NativeScript/blob/87703ce3eaae86f9ec4eada49f63536790af9f7b/tns-core-modules/application/application.d.ts#L378-L380) and with NativeScript 3.4.x we have introduced a change in the lifecycles that supports 'foregroundActivity' I am reopening this issue

**Comment by debevv** [comment]
I think this isn't necessarily a problem, as long it's made clear in the documentation that this member wil be usable only after the 'navigatedTo' event (my application is hooked to the 'onLoaded' one and it's not working)

**Comment by EddyVerbruggen** [comment]
@debevv For plugins it's a problem as they can't hook into the `navigatedTo` event.

**Comment by NickIliev** [comment]
@EddyVerbruggen the foregroundActivity is present in `navigatedTo` (not not in `loaded`)

Ok after looking at [Android activity lifecycles](https://developer.android.com/guide/components/activities/activity-lifecycle.html) we can consider setting the `foregroundActivity` to be set in [onActivityCreated event](https://github.com/NativeScript/NativeScript/blob/87703ce3eaae86f9ec4eada49f63536790af9f7b/tns-core-modules/application/application.android.ts#L222) . As the `lifecycleCallbacks` are attached to the native app runtime. This would also mean that even if we have two activities (e.g. one for the splash screen and one for the main app)  the `lifecycleCallbacks` are attached to the native app and the `foregroundActivity` value will be updated as expected.

ping @vchimev

**Comment by vchimev** [comment]
TODO:
- set `foregroundActivity` on onCreate(), onStart(), onResume() events
- delete `startActivity`

**Comment by EddyVerbruggen** [comment]
@NickIliev @vchimev Those changes would be very useful, thank you!

**Comment by vchimev** [comment]
Hello All,

After additional consideration, we suggest unmarking `startActivity` as deprecated; `foregroundActivity`remains unchanged - it is available on `application.resumeEvent`.

**Comment by EddyVerbruggen** [comment]
That's perfectly fine with me as well.
