### ISSUE TITLE
GridLayout performance

### ISSUE THREAD

**Issue by b4rtt** [NativeScript/NativeScript#5312]
Hi,

I found a little problem with grid layout.
I have not so big dataset and it's rendering very slow. When I try to scroll trough the page it's very laggy. 

This is how my page looks. There is not too much nodes I think.

https://youtu.be/IC_EU81hqCw

`<ActionBar class="action-bar" title="Tabuľka" flat="true">
    <NavigationButton text=""></NavigationButton>
</ActionBar>
<GridLayout rows="*, auto" class="page page-content">
    <StackLayout row="0" orientation="vertical">
        <AbsoluteLayout class="modal" *ngIf="show_modal==true">
            <StackLayout class="modal-inner">
                <GridLayout rows="*" class="box">
                    <StackLayout orientation="vertical">
                        <StackLayout class="modal-heading">
                            <FlexboxLayout flexDirection="row">
                                <Label text="Vyber sezónu:" class="modal-heading-text" flexGrow="1"></Label>
                                <StackLayout class="modal-heading-ico" (tap)="hide_modal()">
                                    <Image src="~/assets/menu_icons/cross.png"></Image>
                                </StackLayout>
                            </FlexboxLayout>
                        </StackLayout>

                        <ScrollView orientation="vertical">

                            <StackLayout class="seasons-list">

                                <StackLayout class="season-item">
                                    <FlexboxLayout flexDirection="row">
                                        <Label flexGrow="1" class="season-item-text" text="2010/2011"></Label>
                                    </FlexboxLayout>
                                </StackLayout>

                                <StackLayout class="season-item">
                                    <FlexboxLayout flexDirection="row">
                                        <Label flexGrow="1" class="season-item-text" text="2010/2011"></Label>
                                    </FlexboxLayout>
                                </StackLayout>

                                <StackLayout class="season-item">
                                    <FlexboxLayout flexDirection="row">
                                        <Label flexGrow="1" class="season-item-text" text="2010/2011"></Label>
                                    </FlexboxLayout>
                                </StackLayout>

                                <StackLayout class="season-item">
                                    <FlexboxLayout flexDirection="row">
                                        <Label flexGrow="1" class="season-item-text" text="2010/2011"></Label>
                                    </FlexboxLayout>
                                </StackLayout>

                                <StackLayout class="season-item">
                                    <FlexboxLayout flexDirection="row">
                                        <Label flexGrow="1" class="season-item-text" text="2010/2011"></Label>
                                    </FlexboxLayout>
                                </StackLayout>

                                <StackLayout class="season-item">
                                    <FlexboxLayout flexDirection="row">
                                        <Label flexGrow="1" class="season-item-text" text="2010/2011"></Label>
                                    </FlexboxLayout>
                                </StackLayout>

                                <StackLayout class="season-item">
                                    <FlexboxLayout flexDirection="row">
                                        <Label flexGrow="1" class="season-item-text" text="2010/2011"></Label>
                                    </FlexboxLayout>
                                </StackLayout>

                                <StackLayout class="season-item">
                                    <FlexboxLayout flexDirection="row">
                                        <Label flexGrow="1" class="season-item-text" text="2010/2011"></Label>
                                    </FlexboxLayout>
                                </StackLayout>

                                <StackLayout class="season-item">
                                    <FlexboxLayout flexDirection="row">
                                        <Label flexGrow="1" class="season-item-text" text="2010/2011"></Label>
                                    </FlexboxLayout>
                                </StackLayout>

                                <StackLayout class="season-item">
                                    <FlexboxLayout flexDirection="row">
                                        <Label flexGrow="1" class="season-item-text" text="2010/2011"></Label>
                                    </FlexboxLayout>
                                </StackLayout>

                                <StackLayout class="season-item">
                                    <FlexboxLayout flexDirection="row">
                                        <Label flexGrow="1" class="season-item-text" text="2010/2011"></Label>
                                    </FlexboxLayout>
                                </StackLayout>

                                <StackLayout class="season-item">
                                    <FlexboxLayout flexDirection="row">
                                        <Label flexGrow="1" class="season-item-text" text="2010/2011"></Label>
                                    </FlexboxLayout>
                                </StackLayout>

                            </StackLayout>

                        </ScrollView>

                    </StackLayout>
                </GridLayout>
            </StackLayout>
        </AbsoluteLayout>

        <StackLayout *ngIf="show_modal==false">
            <ScrollView orientation="vertical">
                <StackLayout class="page-standings">

                    <StackLayout class="heading-with-selects">
                        <StackLayout class="page-heading">
                            <Label text="Fortuna liga 2017 / 18" class="page-heading-text"></Label>
                        </StackLayout>
                        <StackLayout class="page-heading-selects">
                            <FlexboxLayout flexDirection="row">
                                <StackLayout class="select-box" flexGrow="1" (tap)="show_modal_box()">
                                    <Label text="Fortuna liga"></Label>
                                </StackLayout>
                                <StackLayout class="divider"></StackLayout>
                                <StackLayout class="select-box" flexGrow="1">
                                    <Label text="Sezóna 2017 / 18"></Label>
                                </StackLayout>
                            </FlexboxLayout>
                        </StackLayout>
                    </StackLayout>

                    <StackLayout class="page-inner">

                        <GridLayout columns="auto, *, auto, auto, auto, auto, auto, auto" rows="*, *, *, *, *, *, *, *, *, *, *, *, *" class="table table-standings">

                            <StackLayout row="0" col="0" class="th #">
                                <Label text="P" textWrap="true"></Label>
                            </StackLayout>
                            <StackLayout row="0" col="1" class="th team">
                                <Label text="Tím" textWrap="true"></Label>
                            </StackLayout>
                            <StackLayout row="0" col="2" class="th Z">
                                <Label text="Z" textWrap="true"></Label>
                            </StackLayout>
                            <StackLayout row="0" col="3" class="th V">
                                <Label text="V" textWrap="true"></Label>
                            </StackLayout>
                            <StackLayout row="0" col="4" class="th R">
                                <Label text="R" textWrap="true"></Label>
                            </StackLayout>
                            <StackLayout row="0" col="5" class="th P">
                                <Label text="P" textWrap="true"></Label>
                            </StackLayout>
                            <StackLayout row="0" col="6" class="th S">
                                <Label text="S" textWrap="true"></Label>
                            </StackLayout>
                            <StackLayout row="0" col="7" class="th B">
                                <Label text="B" textWrap="true"></Label>
                            </StackLayout>

                            <template *ngFor="let standing of standings">
                                <StackLayout row="{{standing}}" col="0" class="td #">
                                    <Label text="{{standing}}." textWrap="true"></Label>
                                </StackLayout>
                                <StackLayout row="{{standing}}" col="1" class="td team">
                                    <Image src="~/assets/teams/spa.png" height="15" class="logo"></Image>
                                    <Label text="ŠK Slovan" textWrap="true"></Label>
                                </StackLayout>
                                <StackLayout row="{{standing}}" col="2" class="td Z">
                                    <Label text="3" textWrap="true"></Label>
                                </StackLayout>
                                <StackLayout row="{{standing}}" col="3" class="td V">
                                    <Label text="3" textWrap="true"></Label>
                                </StackLayout>
                                <StackLayout row="{{standing}}" col="4" class="td R">
                                    <Label text="3" textWrap="true"></Label>
                                </StackLayout>
                                <StackLayout row="{{standing}}" col="5" class="td P">
                                    <Label text="3" textWrap="true"></Label>
                                </StackLayout>
                                <StackLayout row="{{standing}}" col="6" class="td S">
                                    <Label text="34:43" textWrap="true"></Label>
                                </StackLayout>
                                <StackLayout row="{{standing}}" col="7" class="td B">
                                    <Label text="3" textWrap="true"></Label>
                                </StackLayout>
                            </template>

                        </GridLayout>

                    </StackLayout>

                </StackLayout>
            </ScrollView>
        </StackLayout>

    </StackLayout>
    <Tabs></Tabs>
</GridLayout>
`

**Comment by EddyVerbruggen** [comment]
You have incredibly deep view nesting which is very likely the reason for the sluggish performance. Native layouts should be as shallow (less nesting is better) as possible.

For example, this:

```html
<StackLayout row="0" col="3" class="th V">
  <Label text="V" textWrap="true"></Label>
</StackLayout>
```

Can be replaced by this:

```html
<Label row="0" col="3" class="th V" text="V" textWrap="true"></Label>
```

**Comment by NickIliev** [comment]
@b4rtt apart from the excessive level of nesting you can try to use `ListView` or `RadLisView` instead of `*ngFor` (the native controls are coming with virtualization and recycling while the structural directive is not)

**Comment by b4rtt** [comment]
@NickIliev @EddyVerbruggen 
But I think that ListView doesn't help because I need same width columns across all rows. I need something like classic HTML Table.
