### ISSUE TITLE
Webview detect document height

### ISSUE THREAD

**Issue by b4rtt** [NativeScript/NativeScript#5324]
Hello,

I am kinda confused about combination of native elements with webview.

My task is create article detail page.
And it should look like example picture.

![snimek obrazovky 2018-01-24 v 14 06 35](https://user-images.githubusercontent.com/4247839/35343743-ab9ec868-012b-11e8-9d3a-8b5d4b34def5.jpg)

Problem you can see on this video. You will see, that using this looks pretty bad. 
https://youtu.be/4kuLXHnB1Bc

There is playground example: https://play.nativescript.org/?template=play-ng&id=QUj1f0

Problem is scrolling in webview. Solution could be WebView which has the same height as website content, but on each page content should have different sizes.

I found some simple solution for React Native. Is some way how to simple do it in NativeScript?
https://flexwork.io/blog/webview-height-html-content-react-native/

I really don't know how to solve it most elegant way.

Thanks for any suggestion

**Comment by NickIliev** [comment]
@b4rtt there are couple approaches that can be used. For example, you can scroll only the WebView content and "dock" the native elements as done [here](https://play.nativescript.org/?template=play-ng&id=QUj1f0&v=2) or directly use a DockLayout as done [here](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/apod/apod.component.html#L16-L18). 

You can dock and "push" the native elements (top or bottom) using parallax effect ([here](http://www.nativescriptsnacks.com/)) or you can only scroll the webview content and push the native elements with `translateY`.


Notice that the repository is for logging issues, bugs and features related to NativeScript.
For how-to related questions please use the community channels like [the NativeScript forum](https://discourse.nativescript.org/), [SO ](https://stackoverflow.com/questions/tagged/nativescript)or [NativeScript community slack](https://nativescriptcommunity.slack.com/messages/general) where the community can provide you will guidelines.
