### ISSUE TITLE
TNS fails to build when watchkit extension is present.

### ISSUE THREAD

**Issue by spbond** [NativeScript/NativeScript#5328]
### Tell us about the problem
I added a watchkit extension to my NativeScript app through Xcode, and ever since I get the following error:

"target specifies product type 'com.apple.product-type.watchkit2-extension', but there's no such product type for the 'iphoneos' platform"

I have been building building my project through Xcode, but I would like to debug the javascript portions of my code.  Would it be possible to support building applications which have manually added watchkit extensions?

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.0
- Cross-platform modules: 3.4.0
- Runtime(s): tns-ios 3.4.0
- Plugin(s): ?

### Please tell us how to recreate the issue in as much detail as possible.
Create a nativescript app. 
Open it in Xcode and add a watchkit extension.
Try to build with "tns build ios"

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3336
