### ISSUE TITLE
Custom Observable objects

### ISSUE THREAD

**Issue by moll** [NativeScript/NativeScript#533]
Hey,

I notice the bindings code does explicit `instanceof `checks for Observables. I'd like to use my own implementation to re-use existing code. It's not a problem to decorate them with an equivalent interface, but the `instanceof` checks forbid them from working.

**Comment by enchev** [comment]
If you inherit from our Observable instanceof checks will pass normally.

**Comment by moll** [comment]
I won't be inheriting from that, that's the point. ;-)

**Comment by enchev** [comment]
We are not sure how we can enable custom observables since we will not know the API. Can you share more info about your idea?

**Comment by ligaz** [comment]
We can introduce a TypeScript interface for Observable and refactor our code to use it instead. This way we can have the structural (duck) typing of TypeScript help us accommodate external observables as long as they comply to the contract we expose.

**Comment by enchev** [comment]
Yep we can do that, thanks @ligaz! @moll will this work for you?

**Comment by moll** [comment]
Absolutely. I personally use the other common style of `change` and `change:nameOfProperty` events with `value` as the first argument to the callback, but anything you pick I can interface to. That version does seem a little more succinct — skips the redundant `eventName` and `object` properties that are on NativeScript's `EventData`.

Speaking of events, I've got a lean prototype-friendly event/pubsub library that supports currying extra arguments beyond `thisArg` (https://github.com/moll/js-concert#extra-arguments) named [Concert.js](https://github.com/moll/js-concert). Perhaps it comes handy if you don't want to reimplement things. If need be, I can throw TypeScript definitions at it as well.

**Comment by ligaz** [comment]
The `EventData` property names are derived from the [`Object.observe()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/observe) in order for us to better align with the spec (at least from naming perspective). 

I like you minimalistic events lib. I even send you a pull request with a small typo in the read me :smile:

**Comment by moll** [comment]
Ah, fair enough on `Object.observe`.

Thanks @ Concert.js. I'll be waiting for your PR. :)
I'm most proud of its prototype support. Saves everyone from thousands and thousands of `this.on(...)` calls in constructors. :)

**Comment by hamorphis** [comment]
I’m closing this issue because it has been inactive for almost an year.
