### ISSUE TITLE
Content Property for XML declarations

### ISSUE THREAD

**Issue by ligaz** [NativeScript/NativeScript#534]
In order to simplify the XML declaration it might be a good idea to introduce the concept of Content Property. Here is an example:
```xml
  <Page.actionBar>
    <ActionBar>
      <ActionBar.actionItems>
        <ActionItem text="{{ resources.signUp }}" tap="signUpMenuItemTap" android.position="actionBar" />
      </ActionBar.actionItems>
    </ActionBar>
  </Page.actionBar>
```
can be simplified to just:
```xml
  <Page.actionBar>
    <ActionBar>
      <ActionItem text="{{ resources.signUp }}" tap="signUpMenuItemTap" android.position="actionBar" />
    </ActionBar>
  </Page.actionBar>
```
The idea is to annotate somehow the respective UI component so that the XML parser can figure out which should be the Content property and set the property value based on the XML element's content. 

A possible way to do this is to use decorators on the UI components.

**Comment by enchev** [comment]
Merged with this: https://github.com/NativeScript/NativeScript/issues/597
