### ISSUE TITLE
fetch OutOfMemory

### ISSUE THREAD

**Issue by LorenDorez** [NativeScript/NativeScript#5343]
When using the Fetch module i get a response from an API an call the response.json(). All works find until 1 API call where i return a very large result in which the android app crashes saying outofmemory.

is there another effective way to get this json response?

**Comment by tsonevn** [comment]
HI @LorenDorez,
I tested your case with the fetch module while using latest NativeScript modules 3.4.0, however, was unable to recreate a similar issue.

Regarding that, it would help if you provide some info about your environment(CLI, tns -core-modules, runtime versions). 

For your convenience I am attaching sample project, please review it and make the needed changes, which will allow us to recreate this case.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1672576/Archive.zip)

**Comment by LorenDorez** [comment]
Hi @tsonevn ,

Im new to {N} hre is the info you requested below. Also i switch the fetch to a normal HTTP Post and it works. Im pulling about 60,000 nested json records back on this API call.

CLI: 3.4.1
Core Modules: 
`{
  "_from": "tns-core-modules",
  "_id": "tns-core-modules@3.4.0",
  "_inBundle": false,
  "_integrity": "sha1-PEDdPpXGwzs/73rU7nTaqEOpKhE=",
  "_location": "/tns-core-modules",
  "_phantomChildren": {},
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "tns-core-modules",
    "name": "tns-core-modules",
    "escapedName": "tns-core-modules",
    "rawSpec": "",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/tns-core-modules/-/tns-core-modules-3.4.0.tgz",
  "_shasum": "3c40dd3e95c6c33b3fef7ad4ee74daa843a92a11",
  "_spec": "tns-core-modules",
  "_where": "F:\\GLSS\\Clients\\Oversii\\MobileApps\\NativeScript\\Patrolman Mobile App",
  "bundleDependencies": false,
  "dependencies": {
    "tns-core-modules-widgets": "3.4.0"
  },
  "deprecated": false,
  "description": "Telerik NativeScript Core Modules",
  "devDependencies": {
    "@types/node": "~7.0.5",
    "tns-platform-declarations": "*"
  },
  "files": [
    "**/*.d.ts",
    "**/*.js",
    "**/package.json",
    "!android17.d.ts",
    "!ios.d.ts",
    "!bin/",
    "!apps/",
    "!build/",
    "!node-tests/",
    "!declarations.android.d.ts",
    "!declarations.ios.d.ts",
    "!gruntfile.js",
    "!org.nativescript.widgets.d.ts"
  ],
  "homepage": "https://www.nativescript.org",
  "license": "Apache-2.0",
  "name": "tns-core-modules",
  "nativescript": {
    "platforms": {
      "ios": "3.0.0",
      "android": "3.0.0"
    }
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/NativeScript/NativeScript/commit/40868ae54b12b1e244a9cf93e3cc116f062eae86"
  },
  "snapshot": {
    "android": {
      "tns-java-classes": {
        "modules": [
          "ui/frame/activity",
          "ui/frame/fragment"
        ]
      }
    }
  },
  "typings": "tns-core-modules.d.ts",
  "version": "3.4.0"
}
`

RunTimes: 
```
"tns-ios": {
      "version": "3.4.1"
    },
    "tns-android": {
      "version": "3.4.1-2018-01-25-01"
    }
```

**Comment by tsonevn** [comment]
Hi @LorenDorez,
I research your case further, however, was unable to find out a way to reproduce this scenario.
Something that I would suggest is using the [nativescript-downloadmanager](https://www.npmjs.com/package/nativescript-downloadmanager) plugin, which will allow you to download files with a large size for Android.

**Comment by tsonevn** [comment]
Hi @LorenDorez,
Were you able to solve the OutOfMemory issue, while using the nativescript-downloadmanager plugin?

**Comment by LorenDorez** [comment]
@tsonevn I look at this but it only states it support android. I do need support for iOS. I tried nativescript-downloader but it keeps giving me and other errors and wont load

**Comment by LorenDorez** [comment]
@tsonevn the plugin `nativescript-downloader` for file downloads. But i have a FETCH to my api that return 75MB and im getting an Out Of Memory occasionally

Is there a better way to handle large API responses?

**Comment by tsonevn** [comment]
Hi @LorenDorez,
Excuse me for the delay in reply.
At this time the `nativescript-downloader` is the only available way for downloading and accessing large files in a NativeScript application for Android. 
We have a feature request for enabling a download option in a [nativescript-background-http](https://github.com/NativeScript/nativescript-background-http/issues/2), however, I can not commit to the exact time when it will be available.
