### ISSUE TITLE
Data binding, can't bind property with name contains dots

### ISSUE THREAD

**Issue by im4LF** [NativeScript/NativeScript#5347]
Example of my data source:
```js
var items = [{
    title : 'Some title of 0',
    'attr.name1' : 10,
    'attr.name2' : 20
},{
}]
```

My template:
```html
<ListView items="{{ tasks }}">
    <ListView.itemTemplate>
        <StackLayout class="p15">
            <Label text="{{ title }}" class="title" />
            <!-- generate Binding error -->
            <Label text="{{ $value['attr.name1'] }}" />
            <!-- valid access -->
            <Label text="{{ ( $value['attr.name1'] ) }}" />
        </StackLayout>
    </ListView.itemTemplate>
</ListView>
```

So [the getProperties function](https://github.com/NativeScript/NativeScript/blob/43fbabb5e9d383244ce5fa9926ad6b45de5e8c68/tns-core-modules/ui/core/bindable/bindable.ts#L29) can't understand attribute name with `dots`.

Data binding in that cases only possible as expression `{{ ( $value['prop.with.dots'] ) }}`.
Perhaps you should fix parser and documentation.

`
$ tns --version
3.4.1
`

**Comment by NickIliev** [comment]
@im4LF indeed naming with dots is supported only via expression. 
Moving the article to documentation so that we can improve the data binding article by adding a section describing how to use property names that contain dots.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/docs#1054
