### ISSUE TITLE
OK - Cancel buttons are on the wrong sides in a "confirm" dialog

### ISSUE THREAD

**Issue by pentool** [NativeScript/NativeScript#5349]
## Please, provide the details below:
Correct me if I'm wrong, but when you bring up a confirm dialog in iOS, the positive action button is on the left, and the negative action is on the right.

For a simple example, try to delete an app from your iOS device. You don't have to actually delete it, just start the process, eg:
1. Tap and hold an app icon until they start to wiggle.
2. Press the little delete icon.
3. You will get a confirm dialog asking if you want to delete the app: Delete/Cancel.

The positive action (to execute) is on the left: Delete
And the negative/cancel action on the right: Cancel

However, in {N} Dialog.confirm, it's the other way around. Example:

```
Dialogs.confirm({
    title: "Which side I am on?",
    message: "Are you sure you are on the correct side?",
    okButtonText: "Yes",
    cancelButtonText: "Cancel"
})
.then((result) => {...})
```

The "Yes" button will be on the right, and "Cancel" is on the left. The "result" in the `then` clause will return `true` for tapping "Yes" and `false` for "Cancel".

Technically, I could reverse the buttons (okButtonText: Cancel, cancelButtonText: Yes) and check the `result` to be false for "Yes", but that's just weird code.

And while we are on the topic, the positive action buttons are usually bolded (even in a simple alert dialog). But {N} doesn't seem to bold them.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.1

### Please tell us how to recreate the issue in as much detail as possible.
Playground: https://play.nativescript.org/?template=play-js&id=EY6Quj

```
Dialogs.confirm({
    title: "Which side I am on?",
    message: "Are you sure you are on the correct side?",
    okButtonText: "Yes",
    cancelButtonText: "Cancel"
})
.then((result) => {...})
```

**Comment by tsonevn** [comment]
HI @pentool,
We researched this case and it seems that this is the standard behavior on iOS and the Cancel button will be shown on the left side, while it is used UIAlertViewContorller. In NativeScript has been used the standard way for displaying UIAlert. 
For further info, you could also review this [article](https://learnappmaking.com/uialertcontroller-alerts-swift-how-to/), where is demostrated, how the Alert is displayed in a pure iOS application and what is the default layout structure.

Hope this helps.

**Comment by pentool** [comment]
Thanks for checking on this @tsonevn! I also found in Apple's HIG that:

_"Place buttons where people expect them. In general, buttons people are most likely to tap should be on the right. Cancel buttons should always be on the left."_
(URL: https://developer.apple.com/ios/human-interface-guidelines/views/alerts/)

I guess there are no hard rules. The "most likely" button should be on the right. I guess that's good enough for me :-)
