### ISSUE TITLE
Is there any plugin to embed Instagram, Facebook & Twitter to a WebView?.

### ISSUE THREAD

**Issue by reilue** [NativeScript/NativeScript#5357]
Hi guys!.

I'm building an app to display (embedding content using WebView) Facebook, Twitter, Instagram.

Twitter made this super easy to embbed.

But when related to Facebook and Instagram, things gets clumsy.

So is there any plugin to fulfill such thing?.

Have a nice day!.

**Comment by tsonevn** [comment]
Hi @reilue,
Could you describe more detailed about your problem and what is the expected final result in the project?

I made a little research and found that you could use [nativescript-twitter](https://www.npmjs.com/package/nativescript-twitter) and [nativescript-facebook](https://www.npmjs.com/package/nativescript-facebook), which allows using the facebook and twitter SDKs in NativeScript, however at this time I was unable to find a similar solution for Instagram.

**Comment by reilue** [comment]
Hi @tsonevn 
Such plugins is for authenticantion, which is awesome but not what i require right now.

Something like this.

![timeline](https://user-images.githubusercontent.com/12874996/35624560-b6d5bae0-0665-11e8-84bb-fc55c86cd80d.PNG)

I could embedded twitter within the app (no-plugin added), but is there any plugin for instagram or facebook to embed their timeline respectively?.

**Comment by tsonevn** [comment]
Hi @reilue,
Thank you for the provided info,
Regarding Facebook
As I suggest in the previous comment, you could use [nativescript-facebook](https://www.npmjs.com/package/nativescript-facebook) plugin and implement the needed functionality with its help.

Regarding Instagram

I researched the case and found [this article ](https://www.instagram.com/developer/embedding/) from the Instagram documentation that might help for embedding it while using WebView.

> Keep in mind that I have not tested the scenario with Instagram embedding and I can not confirm that it will work.

**Comment by gustavost26** [comment]
> Hi @tsonevn
> Such plugins is for authenticantion, which is awesome but not what i require right now.
> 
> Something like this.
> 
> ![timeline](https://user-images.githubusercontent.com/12874996/35624560-b6d5bae0-0665-11e8-84bb-fc55c86cd80d.PNG)
> 
> I could embedded twitter within the app (no-plugin added), but is there any plugin for instagram or facebook to embed their timeline respectively?.

Eulier, do you have any nativescript-twitter functional project to make available for study?
