### ISSUE TITLE
NativeScript CLI hangs on ADB “help”

### ISSUE THREAD

**Issue by BeMor81** [NativeScript/NativeScript#5359]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

When running various TNS commands such as

tns create my-app-name --template tns-template-blank-ng

or

tns doctor

using the --log trace switch it appears that the command hangs at the following line

execFile: D:\AndroidSDK\platform-tools\adb "help"

That is the correct path for ADB and I've tried resetting the ADB server as well as restarting my machine. ANDROID_HOME is also set to D:\AndroidSDK.

### Which platform(s) does your issue occur on?
Android only

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) 3.4.1
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) Attempting to create a new app so N/A
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project) Attempting to create a new app so N/A
- Plugin(s): (look for the version number in the `package.json` file of your
project) Attempting to create a new app so N/A

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

Launch command prompt with admin rights. After navigating to desired folder using CD then run tns create my-app-name --template tns-template-blank-ng

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
 No code

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3344
