### ISSUE TITLE
Aurelia support for nativescript apps

### ISSUE THREAD

**Issue by kkganesan** [NativeScript/NativeScript#536]
Aurelia framework, http://aurelia.io

**Comment by enchev** [comment]
Hey,

As far as we know this framework can work only in the browser. You can check the [main JavaScript for more info](https://github.com/aurelia/framework/blob/master/src/aurelia.js).

**Comment by kkganesan** [comment]
Thanks @enchev, confirmed here https://twitter.com/EisenbergEffect/status/628175434459541504

**Comment by Lichtjaeger** [comment]
[Looks like this has changed.](http://blog.aurelia.io/2016/11/04/introducing-aurelia-ux/#hostsplatformsanddesignlanguages) Target for mobile is Cordova but it would be nice to see NativeScript support too.

Please reopen.

**Comment by valentinstoychev** [comment]
Thanks @Lichtjaeger! The core team can help with any guidance if there is someone interested in working on this. Most of the hard work is already done during our integration with Angular 2, so integrating Aurelia should not be very difficult atm.

**Comment by Kukks** [comment]
@enchev I'm up to joining this initiative if you're willing to point us in the right direction :)

**Comment by peacechen** [comment]
Aurelia support would be a game changer for us to adopt NativeScript.  Currently using React Native which is pretty good, but the codebase doesn't readily run on web browsers.

**Comment by arjendeblok** [comment]
I like this one too. What needs to be solved first is that Aurelia can also data-bind with nativescript templates (in XML) instead of HTML views.  That will be the most work.

**Comment by bigopon** [comment]
Aurelia can now run on Node, if some1 could pursue this target from that base, it would be awesome.

**Comment by arjendeblok** [comment]
@bigopon where did you find that base? Still templates in Aurelia are HTML templates and not XML. Or can NativeScript also handle HTML views with native controls?

**Comment by bigopon** [comment]
It's [here, (pal - nodejs)](https://github.com/aurelia/pal-nodejs). The implementation is based on jsdom.

**Comment by Lichtjaeger** [comment]
Any WIP?

**Comment by PisaJan** [comment]
I would really love to use Aurelia with NativeScript, considering results of State of JS (https://2018.stateofjs.com/front-end-frameworks/other-libraries/) it seems like step forward :)

**Comment by weoreference** [comment]
Hello, is anyone interested in this? Really looking forward to any tips !

**Comment by rigor789** [comment]
Closing this as not officially planned. If the community decides to work on an integration (via for example [DOMiNATIVE](https://github.com/SudoMaker/dominative) or based on one of the other integrations) please reach out on our Discord (https://nativescript.org/discord) with any questions!
