### ISSUE TITLE
Send data to app (local)

### ISSUE THREAD

**Issue by hypery2k** [NativeScript/NativeScript#5360]
Is it possible when running app locally to push data to it via websocket or similar?
Locally means: Connected smartphone via USB and deployed app via "tns run ..." there ;)

**Comment by NickIliev** [comment]
@hypery2k take a look at [this blog post about using web sockets in NativeScript](https://www.thepolyglotdeveloper.com/2017/01/communicate-with-websockets-in-a-nativescript-angular-application/).

Note that the repository is for logging issues, bugs and features related to NativeScript.
For how-to related questions please use the community channels like [the NativeScript forum](https://discourse.nativescript.org/), [SO ](https://stackoverflow.com/questions/tagged/nativescript)or [NativeScript community slack](https://nativescriptcommunity.slack.com/messages/general)
