### ISSUE TITLE
Wrapping events in Observable.fromEvent causes issues 

### ISSUE THREAD

**Issue by nikoTM** [NativeScript/NativeScript#5369]
### Tell us about the problem

Wrapping `touch` events with `Rx.Observable` causes unexpected side effects on both platforms. While the desired functionality is possible to implement via `on` and `off` methods of `View`, wrapping the same events with `Rx.Observable` shouldn't be causing these issues.

Manifestation:
    IOS: Button is not being released in the view.
    Both platforms: `btnHoldEvent$` is called only 1 time. It never gets to that point again.

The idea was to implement `hold` event that fires each second when holding down. Desired outcome is implemented with `on` and `off` methods, and is commented.
Web equivalent of the intended usage of `rxjs` is here: https://codepen.io/anon/pen/gvamLv 

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.1
- Cross-platform modules: 3.4.0
- Runtime(s): 3.4.1.
- Plugin(s): -

### Please tell us how to recreate the issue in as much detail as possible.
https://play.nativescript.org/?template=play-ng&id=7Or8oa&v=2

Click on the button

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#1182
