### ISSUE TITLE
SearchBar component inside ActionBar causes layout to improperly render on iOS

### ISSUE THREAD

**Issue by noumaans** [NativeScript/NativeScript#5371]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
When using SearchBar inside an ActionBar text gets rendered incorrectly on initial view. When user taps inside the SearchBar, enters text and clears the SearchBar text is rendered correctly at that point.

### Which platform(s) does your issue occur on?
iOS/Android/Both
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)
Playground link provided to show issue

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 
https://play.nativescript.org/?template=play-ng&id=52EfVM&v=3

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
You can also remove m-t-24 from Line 15 of home.component.html to see how Help Text gets chopped off.

**Comment by tsonevn** [comment]
Hi @noumaans,
Thank you for reporting this bug.
I tested the sample project on my side, and I have to confirm that this is a real issue on iOS.
I am attaching an image, which demonstrates the case.
![iostest](https://user-images.githubusercontent.com/17448734/35719864-fb45359a-07f3-11e8-8801-dfd33d915a27.png)

For further info please keep track on the issue.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1183
