### ISSUE TITLE
SegmentedBar font-awesome icons not rendering correctly.

### ISSUE THREAD

**Issue by Meyer-dev** [NativeScript/NativeScript#5373]
### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

I have tried using fontawesome icons in my segmentedbar. Fontawesome is installed correctly and working throughout the app except here.When i run the code the other styling that i have applied (the color) works but it just displays the unicode characters instead of the respective icons in the segmentedbar.

### Which platform(s) does your issue occur on?
Android

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

My markup:
Html: 
<SegmentedBar row="1" col="0"  [items]="segmentedBarItems" [(ngModel)]="selectedBarIndex" (selectedIndexChange)="onSelectedIndexChange($event)" class="m-5" style="font-family: 'FontAwesome'; color: #84C7C2;" selectedBackgroundColor="#84C7C2"></SegmentedBar>

TS:
private getSegmentedBarItems = () => {
        let segmentedBarItem1 = new SegmentedBarItem();
        segmentedBarItem1.title = "&#xf0c0;";
        let segmentedBarItem2 = new SegmentedBarItem();
        segmentedBarItem2.title = "&#xf07a;";
        let segmentedBarItem3 = new SegmentedBarItem();
        segmentedBarItem3.title = "&#xf07a;";
        return [segmentedBarItem1, segmentedBarItem2, segmentedBarItem3];
    }
    segmentedBarItems: Array<SegmentedBarItem> = this.getSegmentedBarItems();
    selectedBarIndex: number = 0;

**Comment by tsonevn** [comment]
Hi @Meyer-dev,
Thank you for contacting us,
When you creating the SegmentedBarItems from code behind and need to use icon font you should generate the displayed title while using `fromCharCode` generator, which will create a one-letter string from the character code. For example:
```
private getSegmentedBarItems = () => {
        let segmentedBarItem1 = new SegmentedBarItem();
        segmentedBarItem1.title = String.fromCharCode(0xf2b9);
        let segmentedBarItem2 = new SegmentedBarItem();
        segmentedBarItem2.title = String.fromCharCode(0xf2b9);
        let segmentedBarItem3 = new SegmentedBarItem();
        segmentedBarItem3.title = String.fromCharCode(0xf2b9);
        return [segmentedBarItem1, segmentedBarItem2, segmentedBarItem3];
    }

```

**Comment by Meyer-dev** [comment]
Hi

Thanks a lot for the help.was looking for ages on the net.Can i enlarge
them by increasing font-size?If so would i just add Style="font-size:'16''
in the segmented bar tab ?
Also,has Nativescript found a way to style (re-colour) a selected
textfield(the bottom line that lights up?)

Regards
Meyer

**Comment by tsonevn** [comment]
HI @Meyer-dev,
For changing the font size of the SegmentedBar, you could use the following piece of code:
`style.fontSize="24"`->
` <SegmentedBar row="1" col="0" style.fontSize="24" >...</SegmentedBar>`
Regarding the bottom TextField border, you could review the discussion in this thread.

For further question, please use our [forum](https://discourse.nativescript.org/). The repository is used only for features request and bug reporting.
