### ISSUE TITLE
Question: .ipa Installs

### ISSUE THREAD

**Issue by LorenDorez** [NativeScript/NativeScript#5375]
I have a questions.

Is there a way to directly install the .ipa file on an iOS device? Im coming from the Telerik Platform where it just gave me a URL to i could give to my AdHoc tester to go to and it prompted the install.

I upload the .ipa file to my webserver and provided them a link but it just downloads the .ipa file into the "my files" on the iOS device and never installs

**Comment by NickIliev** [comment]
@LorenDorez with NativeScript CLI the command `run` will deploy and start the application on your connected device or simulator (keep in mind that if you want to deploy on real device you will have to provide the development certificate)
```
tns run ios
```

If you want to directly install the generated IPA file in `<project>/platforms/ios/build/device` folder you can use one of the methods used by native iOS developers (e.g. [here](https://mobikul.com/install-ipa-file-iphone-device/)).
