### ISSUE TITLE
searchbar example from docs not work?

### ISSUE THREAD

**Issue by mauriciosouza** [NativeScript/NativeScript#5376]
https://docs.nativescript.org/cookbook/ui/search-bar
```
<SearchBar id="searchBar" hint="Search" text="" clear="onClear" submit="onSubmit" />
```
Events "onClear" and "onSubmit" they are not called inside <nsDrawer:RadSideDrawer.mainContent>
```
function onSubmit(args){
    const searchbar = args.object;
    console.log("Search submit result: "+searchbar.text);
}
function onClear(args){
    console.log("clear search-bar text");
}
exports.onClear = onClear;
exports.onSubmit = onSubmit;
```

**Comment by NickIliev** [comment]
@mauriciosouza the example works as expected on my side (tested on both iOS and Android)
[Here is a sample Playground demo ](https://play.nativescript.org/?template=play-js&id=TJBhzg)demonstrating the above code. 
Or if you prefer [a demo JS application](https://github.com/NickIliev/NS-Issues-2018/tree/master/NativeScript/issue_5376_js) and [a demo TS application](https://github.com/NickIliev/NS-Issues-2018/tree/master/NativeScript/issue_5367).

Let me know if you need further assistance of if your project have some specifics that can help us reproduce the issue.

**Comment by mauriciosouza** [comment]
follows example, onsubmit is working, but not onclear.
https://play.nativescript.org/?template=play-js&id=YSbDY9

**Comment by NickIliev** [comment]
@mauriciosouza the thing is that your HTML layouts are not properly set which causes this strange behavior.
In `GridLayout` when no `rows` and `columns` are set by default only one element will be visualized.
However, you have a GridLayout in which there are three nested elements. 
Introducing a proper layout structure is making the clear event to fire as expected - demo [here](https://play.nativescript.org/?template=play-js&id=YSbDY9&v=2)

**Comment by mauriciosouza** [comment]
Perfect, thanks for the support.
