### ISSUE TITLE
stdout maxbuffer exceeded

### ISSUE THREAD

**Issue by iamajaymakwana** [NativeScript/NativeScript#538]
I am new in android application development. So have started learning the Nativescript development.
After configured the environment for running the application when I have created the hello-world application and tried to run the application on my physical device, it shows me the error "stdout maxbuffer exceeded".
Below are the system and configuration I am using.
Windows 7 32 bit
Samsung Note 3 Neo

Please help me for this issue.

**Comment by dtopuzov** [comment]
@iamajaymakwana, please provide some logs and steps to reproduce.
If you use LiveSync it might be related to https://github.com/NativeScript/nativescript-cli/issues/730

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#172
