### ISSUE TITLE
Modal dialog doesn't open from event listener on element

### ISSUE THREAD

**Issue by shabib3** [NativeScript/NativeScript#5381]
on android modal dialog doesn't open right if it comes from a listening on any kind of `GestureTypes`.

example: 
```
public userLoaded(member: User, args) {
        args.object.on(GestureTypes.longPress, () => {
            this.openUserLongPressMenu(member); // should open simple modal page
        });
    }
``` 

thanks :)

**Comment by tsonevn** [comment]
Hi @shabib3,
I tested the scenario with opening modal page while using gesture, however, was unable to recreate an issue. For your convenience, I am attaching sample project and GIF files, which demonstrated the case.
Please review the project and make the needed changes, which will allow us to recreate the problem. 
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1694222/Archive.zip)
![screencast 2018-02-05 at 9 40 21 am](https://user-images.githubusercontent.com/17448734/35793107-f0661268-0a58-11e8-9c15-5ffceb26e145.gif)
![screencast 2018-02-05 at 9 37 06 am](https://user-images.githubusercontent.com/17448734/35793108-f08ac022-0a58-11e8-9b50-caa296ccecf3.gif)

**Comment by shabib3** [comment]
Hi @tsonevn ,

was able to reproduce it on a playground sample -> https://play.nativescript.org/?template=play-ng&id=UswQN7

**Comment by shabib3** [comment]
For the next to come:

With the help of @tsonevn I understand that there is 2 ways to solve it:
1. The right way:
add `longPress` hook to the HTML -> `<Label (longPress)="myFunction()"></Label>`

2. To run the event listener callback inside a `ngZone.run` function:
```
public labelLoaded(args) {
    console.log("add gesture- label: " + NgZone.isInAngularZone());
    args.object.on(GestureTypes.longPress, () => {
        this.zone.run(() => this.openLongPressMenu());
    });
}
```
