### ISSUE TITLE
TypeScript compiler failed with exit code 3221225477

### ISSUE THREAD

**Issue by DeepakArora76** [NativeScript/NativeScript#5382]
Steps:
1. tns create HelloWorld --template nativescript-template-ng-tutorial
2. tns run android

Searching for devices...
Executing before-liveSync hook from C:\Users\Finn.no\Documents\ExperimentNativeScript\HelloWorld\hooks\before-liveSync\nativescript-angular-sync.js
Executing before-prepare hook from C:\Users\Finn.no\Documents\ExperimentNativeScript\HelloWorld\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.6.2
**Unable to apply changes on device: emulator-5554. Error is: TypeScript compiler failed with exit code 3221225477.**
Executing after-watch hook from C:\Users\Finn.no\Documents\ExperimentNativeScript\HelloWorld\hooks\after-watch\nativescript-dev-typescript.js

**tns info**
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬──────────
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 3.4.2           │ 3.4.2          │ Up to date    │
│ tns-core-modules │ 3.4.0           │ 3.4.0          │ Up to date    │
│ tns-android      │ 3.4.1           │ 3.4.1          │ Up to date    │
│ tns-ios          │                 │ 3.4.1          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴──────────

**tns doctor**
NOTE: You can develop for iOS only on Mac OS X systems.
To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later.

Your components are up-to-date:
nativescript,tns-core-modules,tns-android,tns-ios

No issues were detected.

**Comment by DeepakArora76** [comment]
Appreciate your help on this.

**Comment by tsonevn** [comment]
Hi @DeepakArora76,
Thank you for contacting us.

I tested your scenario while using the above-provided steps, however, was unable to recreate this issue.
Regarding could you check which TypeScript version you have installed on your machine-> `tsc --version`. This issue could happen if you were using TypeScript version different from the one, which is set up in the project: `2.6.2.`

**Comment by DeepakArora76** [comment]
Hi,

Thanks for your reply. The installed version of TypeScript matches to 2.6.2. This version of TypeScript is installed under the project-folder/node_modules/typescript. 

The version of TypeScript installed at Global level is 2.7.1.

**Still same error.** 

It would have been nicer if error logs on console indicated the reason for failure. The error exit code 3221225477 to be is little help.

Please consider improving this.

Please let me know if you need more inputs/info.

**Comment by DeepakArora76** [comment]
My google search shows that there are many bugs which are pretty similar to this. I think we should have better error reporting.

**Comment by DeepakArora76** [comment]
I update the packages to the latest version using the following commands
1. npm install -g npm-check-updates
2. ncu -u
3. npm install 

Even after updating local TypeScript version to 2.7.1, I still continue to see the problem.

[NativeScriptCli] execute: tns --analyticsClient VSCode --version
[NSDebugAdapter] Using tns CLI v3.4.2 on path 'tns'
[NSDebugAdapter] Running tns command...
[NativeScriptCli] execute: tns --analyticsClient VSCode debug android --no-client --watch 
[NSDebugAdapter] Watching the tns CLI output to receive a connection token
Searching for devices...

Starting Android emulator with image Pixel_2_API_27

Waiting for emulator device initialization...


Executing before-liveSync hook from c:\Users\Finn.no\Documents\ExperimentNativeScript\HelloWorldTest\hooks\before-liveSync\nativescript-angular-sync.js

Executing before-prepare hook from c:\Users\Finn.no\Documents\ExperimentNativeScript\HelloWorldTest\hooks\before-prepare\nativescript-dev-typescript.js

Found peer TypeScript 2.7.1

Unable to apply changes on device: emulator-5554. Error is: TypeScript compiler failed with exit code 3221225477.

Executing after-watch hook from c:\Users\Finn.no\Documents\ExperimentNativeScript\HelloWorldTest\hooks\after-watch\nativescript-dev-typescript.js

[NSDebugAdapter] The tns command finished its execution with code 0.

**Comment by DeepakArora76** [comment]
Package.json looks like:

{
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": {
		"id": "org.nativescript.HelloWorldTest",
		"tns-android": {
			"version": "3.4.1"
		}
	},
	"dependencies": {
		"@angular/animations": "~5.2.0",
		"@angular/common": "~5.2.0",
		"@angular/compiler": "~5.2.0",
		"@angular/core": "~5.2.0",
		"@angular/forms": "~5.2.0",
		"@angular/http": "~5.2.0",
		"@angular/platform-browser": "~5.2.0",
		"@angular/platform-browser-dynamic": "~5.2.0",
		"@angular/router": "~5.2.0",
		"nativescript-angular": "~5.2.0",
		"nativescript-theme-core": "~1.0.4",
		"reflect-metadata": "~0.1.8",
		"rxjs": "~5.5.2",
		"tns-core-modules": "~3.4.0",
		"zone.js": "~0.8.18"
	},
	"devDependencies": {
		"babel-traverse": "6.26.0",
		"babel-types": "6.26.0",
		"babylon": "6.18.0",
		"lazy": "1.0.11",
		"nativescript-dev-typescript": "~0.6.0",
		"typescript": "~2.7.1"
	}
}

**Comment by DeepakArora76** [comment]
Here are the package files.
[package.json.txt](https://github.com/NativeScript/NativeScript/files/1697033/package.json.txt)
[package-lock.json.txt](https://github.com/NativeScript/NativeScript/files/1697035/package-lock.json.txt)
[tsconfig.json.txt](https://github.com/NativeScript/NativeScript/files/1697036/tsconfig.json.txt)

**Comment by DeepakArora76** [comment]
On a fresh project folder, I get something 

"
[NativeScriptCli] execute: tns --analyticsClient VSCode --version
[NSDebugAdapter] Using tns CLI v3.4.2 on path 'tns'
[NSDebugAdapter] Running tns command...
[NativeScriptCli] execute: tns --analyticsClient VSCode debug android --no-client --watch 
[NSDebugAdapter] Watching the tns CLI output to receive a connection token
Searching for devices...

Executing before-liveSync hook from c:\Users\Finn.no\Documents\ExperimentNativeScript\blank\hooks\before-liveSync\nativescript-angular-sync.js

Copying template files...

Installing tns-android

Installing  tns-android

+ tns-android@3.4.1
added 1 package in 11.532s

+ babel-traverse@6.4.5
added 17 packages in 20.24s

+ babel-types@6.4.5
added 1 package, removed 1 package and updated 1 package in 12.861s

+ babylon@6.4.5
updated 1 package in 10.555s

+ lazy@1.0.11
added 1 package in 12.199s

Project successfully created.

Executing before-prepare hook from c:\Users\Finn.no\Documents\ExperimentNativeScript\blank\hooks\before-prepare\nativescript-dev-typescript.js

Found peer TypeScript 2.6.2

Unable to apply changes on device: emulator-5554. Error is: TypeScript compiler failed with exit code 3221225477.

Executing after-watch hook from c:\Users\Finn.no\Documents\ExperimentNativeScript\blank\hooks\after-watch\nativescript-dev-typescript.js

[NSDebugAdapter] The tns command finished its execution with code 0.
"

**Comment by DeepakArora76** [comment]
I am clueless why this problem persists. 

I am pretty tired after many attempts.

**Comment by DeepakArora76** [comment]
**Error code 3221225477(0xC0000005) -1073741819**: Access violation. Indicates that the executed program has terminated abnormally or crashed.

**Comment by tsonevn** [comment]
Hi @DeepakArora76 ,
We tried to recreate the scenario whit not applying the changes on Android emulator, however, we are still unable to reproduce it.
I would suggest to follow below-described steps and to send us the full log from the console:
1. create a new sample project `tns create HelloWorld --template nativescript-template-ng-tutorial`
2. run `npm install`
3. prepare the project with log trace->`tns prepare android --log trace`

Then send us the full log from the console.

**Comment by DeepakArora76** [comment]
Many many thanks for your valuable support. You made my day :)

The logs from the command **tns prepare android --log trace** gave me an insight what is needed to resolve the problem.

I installed **node-gyp**, **gradle** and **mono**, and adjusted the environment variables. I believe this was one among the various reasons behind the problem.

Also, I upgraded my node using NVM to v9.5.0.

With these changes in-place, I managed to have the emulator running with my very first app using NativeScript framework

Here is the log for your ref [log.txt](https://github.com/NativeScript/NativeScript/files/1700669/log.txt)

**Comment by DeepakArora76** [comment]
Many many thanks for your valuable support. You made by day :)

The logs from the command **tns prepare android --log trace** gave me an insight what is need to resolve the problem.

I installed **node-gyp**, **gradle** and **mono**, and adjusted the environment variable

[log.txt](https://github.com/NativeScript/NativeScript/files/1700669/log.txt)

**Comment by richard457** [comment]
@DeepakArora76 how did you install mono, is gradle needed if you arleady have android studio or we need to install it in npm way? please help me.

**Comment by DeepakArora76** [comment]
Please sure that the environment variables related to` node-gyp`, `gradle `and `mono `are there.

In my case, I installed `gradle `additionally in-spite of the fact that Androids comes equipped with it.

Mono can be downloaded from the http://www.mono-project.com/download/stable/
