### ISSUE TITLE
Q: RFC#8252 OAuth2 for Native Apps support

### ISSUE THREAD

**Issue by Peperud** [NativeScript/NativeScript#5394]
I realize that this question might not belong here. If that is the case, please point me to the right place. 

Last year IETF officially came out with a best practices recommendation on implementing [OAuth 2.0 for native apps.](https://tools.ietf.org/html/rfc8252)
The gist of it is that the apps should not drive a WebView and instead must use the system browser. 
There are [AppAuth-iOS](https://github.com/openid/AppAuth-iOS) and [AppAuth-Android](https://github.com/openid/AppAuth-Android) open source projects. 
There's also [AppAuthJS](https://github.com/openid/AppAuth-JS), however it seems to be Node/Desktop bound.

Are there any plans for NativeScript - AppAuth integration? 

Generally speaking -  solid OAuth2/OpenIdConnect support would be quite welcome in corporate environments.

**Comment by NickIliev** [comment]
@Peperud there is[ this plugin](https://www.npmjs.com/package/nativescript-oauth) which uses OAuth2.

**Comment by Peperud** [comment]
@NickIliev that plugin does drive a web view (I'm guessing that's why it doesn't work with Google, since [Google no longer allows it](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html)) and have a rather narrow list of supported providers. 
IMO the right solution should work with any provider that supports OAuth2/OpenIdConnect specs. 
More like what [this React-Native project](https://github.com/FormidableLabs/react-native-app-auth) is aiming for.

**Comment by NickIliev** [comment]
@Peperud logging this one as a feature request and perhaps the community will come up with a plugin that enables AppAuth. As NativeScript is an open source project anyone interested can become a contributor and implement this as [a plugin](https://docs.nativescript.org/plugins/building-plugins).

**Comment by NickIliev** [comment]
@Peperud as of this moment you can use [NativeScript Sidekick ](https://docs.nativescript.org/sidekick/intro/introduction)to create kidney auth template and choose from different authentication providers including Auth2 with [Kinvey](https://www.npmjs.com/package/kinvey-nativescript-sdk).

You can install NativeScript Sidekick, and create new. Enterprise Auth template to test the Auth2 functionality provided by Kinvey.

Closing the issue as resolved as **kinvey-nativescript-sdk** plugin is proving this functionality

**Comment by Peperud** [comment]
@NickIliev thanks, I saw that. Doesn't work for me because of [this bug](https://github.com/NativeScript/sidekick-feedback/issues/131), but it sounds good.

**Comment by adityamenonsrijan** [comment]
I'm sorry - I fail to understand how this can be closed as "resolved" - when the only way to provide the feature OP is asking for, which is based on Open Standards, in this Open Source project - is with a proprietary backend provider? Could you please clarify?
