### ISSUE TITLE
IOS Action-bar border not visible

### ISSUE THREAD

**Issue by markomiljkovic** [NativeScript/NativeScript#5395]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes

### Tell us about the problem
Hello guys, I have folowing code
```
<ActionBar class=" border-top"  title="" loaded="loaded" >
    <NavigationButton ></NavigationButton>
    <ActionBar.actionItems  >
        <ActionItem ios.position="right" >
            <ActionItem.actionView>
                <AbsoluteLayout >
                <Label text="&#xf145;" class="action-item gray" />
                </AbsoluteLayout>
            </ActionItem.actionView>
        </ActionItem>
        <ActionItem ios.position="right" >
            <ActionItem.actionView>
                <AbsoluteLayout  class="{{ selectedPage ==='contacts' ? 'higlight-menu-item':'' }}">
                    <Label text="&#xf0c0;" class="action-item gray" />
                </AbsoluteLayout>
            </ActionItem.actionView>
        </ActionItem>
    </ActionBar.actionItems>
</ActionBar>
```
and in my app.css 
```
.border-top {
  border-top-color:#ec295f;
    border-top-width:2;
}

```
But it is not applying border to Actionbar, on ANDROID this works fine, but on IOS it is not working.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.3

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there.

**Comment by NickIliev** [comment]
@markomiljkovic indeed there are some limitations when working with the NavigationController in iOS (the native iOS control behind ActionBar) and there is no out-of-the-box solution for changing its border color.

To modify the border of the iOS NavigationController you can try [this solution](https://github.com/NativeScript/NativeScript/issues/2470#issuecomment-233555881) (but instaed of removing applying new border). Take a look [at this native solution](https://stackoverflow.com/a/6818324/4936697) as well.

**Comment by markomiljkovic** [comment]
Here is a solution I wrote, if someone needs it.
```
var colorModule = require("color");
var red = new colorModule.Color("#ec295f");


if (frameModule.topmost().ios) {
        let controller = frameModule.topmost().ios.controller;
        let navBar = controller.navigationBar;
        let border = new UIView(CGRectMake(0, 1, navBar.frame.size.width, 2));
        border.backgroundColor = UIColor(red.ios);
        border.opaque = true;
        navBar.addSubview(border);
    }
```
