### ISSUE TITLE
 how to call a function inside the xml in nativescript + javascript

### ISSUE THREAD

**Issue by mauriciosouza** [NativeScript/NativeScript#5397]
how to call a function inside the xml in nativescript + javascript. This example not work.
`<Span text="{{ calculateValue(Value) }}"/>`

**Comment by NickIliev** [comment]
@mauriciosouza you can directly call the function by name.
For example:
```
<Button text="TAP" tap="{{ onTap }}"  />
```
and in the view model
```
  viewModel.onTap = function () {
    this.counter--;
    this.set("message", getMessage(this.counter));
  }
```
Full demo [here](https://play.nativescript.org/?template=play-js&id=lhw8PV).

If your scenario requires working with additional arguments you can pass them as expando object.
Refer to [this thread for details on how to achieve that](https://github.com/NativeScript/NativeScript/issues/2143#issuecomment-220263783)

**Comment by mauriciosouza** [comment]
In the event ontap I can use, I would call a function in a span text when I already have a value in the variable "value"

**Comment by webleaf** [comment]
@NickIliev same question. Your example is about binding to tap event, but question was about calling function with params within `text` property.
In my case i'm trying to call `$parents['Page'].someFunc(itemProp)` and nothing happens.
How do that?
```
<Repeater items="{{ myItems }}">
    <Repeater.itemTemplate>
        <Label text="{{ $parents['Page'].someFunc(itemProp) }}"/>
    </Repeater.itemTemplate>
</Repeater>
```

**Comment by NickIliev** [comment]
@webleaf you can't. Use the view model to extract the function return value and pass it via an observable property.
