### ISSUE TITLE
Execution failed for task ':asbg:generateBindings'.

### ISSUE THREAD

**Issue by mouhsine123** [NativeScript/NativeScript#5399]
## Details:
i have tried bundling my app with webpack, but i am getting the following error. I tried removing android platform and readd it to the project but in vain. I tried deleting my .gradle folder in /home/user, this also did not work. i also tried deleting node_modules and reinstall, but its still giving me the error

![image](https://user-images.githubusercontent.com/11781298/35959837-ae795904-0cc0-11e8-8357-f8e69836e7c9.png)

### Problem
when i do ```tns run android``` its ok. But when i do ```tns run android --bundle``` i get the error

### Platform
Android

### Version numbers:
- CLI: 3.2.1
- Cross-platform modules: 3.4.0
- Runtime(s): 3.2.0

Here is what my package.json ressembles
![image](https://user-images.githubusercontent.com/11781298/35960061-a3bb787a-0cc1-11e8-81ae-681be9dee4e6.png)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-dev-webpack#435
