### ISSUE TITLE
API Notifications

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#54]
_From @ligaz on April 4, 2015 19:31_

_From @unlight on January 20, 2015 15:55_

Not sure, that is right place for issue.
But I found nothing about notifications [ApiReference][1].
Will it be available in future version of NativeScript?

[1]: https://github.com/NativeScript/docs/tree/master/ApiReference

_Copied from original issue: NativeScript/nativescript-cli#192_

_Copied from original issue: NativeScript/cross-platform-modules#260_

**Comment by enchev** [comment]
_From @ligaz on April 4, 2015 19:31_

Hi unlight,

Can you please elaborate what kind of Notification API you are expecting? I guess you are talking about Push Notifications and Local Notifications.

**Comment by enchev** [comment]
_From @ligaz on April 4, 2015 19:31_

_From @unlight on March 6, 2015 15:50_

I mean something like this
![example](http://www.vogella.com/tutorials/AndroidNotifications/images/xnotification10.png.pagespeed.ic.fmc6zyoaDS.png)
http://www.vogella.com/tutorials/AndroidNotifications/article.html

**Comment by bradmartin** [comment]
Any update? I'm in a dilemma of Nativescript (performance of native controls) or continuing with Phonegap purely because of the notifications. Can't really have a very successful app without being able to use local notifications to inform the user of events.

**Comment by valentinstoychev** [comment]
Hey @bradmartin we are working on the push notifications and they will be available at the end of July.

**Comment by danicomas** [comment]
@valentinstoychev @vakrilov news about that? We will need Push and local Notifications :S

**Comment by valentinstoychev** [comment]
@danicomas push notifications are available -please see here - https://www.npmjs.com/package/nativescript-push-notifications

Local notifications are still in the backlog though. Please let me know on your app scenario via email (valentin.stoychev@telerik.com) to see how we can enable it.

**Comment by N3ll** [comment]
The discussion about the local notifications could be followed here https://github.com/NativeScript/NativeScript/issues/401.
