### ISSUE TITLE
RadDataForm fires form validate events before any user input

### ISSUE THREAD

**Issue by bearoutthere** [NativeScript/NativeScript#5402]
### Did you verify this is a real problem by searching the [NativeScript Forum

yes

### Tell us about the problem
When initializing a RadDataForm containing properties that have valuesProviders with the array of key / value pairs in order to show labels in the list picker while saving ids to the db the forms propertyValidate and propertyValidated events are triggered, which they shouldn't since the user did not provide any input and nothing needs to be validated.  

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)  3.3.1
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)  tns-android 3.3.1
- Plugin(s): (look for the version number in the `package.json` file of your
project)
    "nativescript-plugin-firebase": "^5.1.1",
    "nativescript-pro-ui": "3.2.0",
    "nativescript-theme-core": "1.0.4",
    "tns-core-modules": "3.4.0"

### Please tell us how to recreate the issue in as much detail as possible.
RadDataForm includes a field with a values provider bound to an observable property on the model.  The model loads the list from the db.  
```
<df:EntityProperty name="province" displayName="Province" index="13" required="true"  valuesProvider="{{ provinces }}" >
                        <df:EntityProperty.editor>
                            <df:PropertyEditor type="Picker" />
                        </df:EntityProperty.editor>
                    </df:EntityProperty>
```

The list contains key value pairs and only the key is stored in the forms source object.

```
this.province = [
        { key: "0", label: "" },
        { key: "2", label: "Province 1" },
        { key: "4", label: "Province 2" },
        { key: "1", label: "Province 3" },
        { key: "5", label: "Province 3" } 
...
    ];
```  
When the form loads initially the entityProperty.source["province"] is 1 but the editor shows "Province 3" as it should.
However during the initial load the propertyValidate and propertyValidated events are triggered, which they shouldn't since no user input was received so there's nothing to validate.

After the form is loaded and a user actually makes a different selection from the list the debugger shows that args.entityProperty.value === null, which is also not an expected behavior since the correct value is shown in the editor.  
There's something wrong with how the form is handling propertyProviders.

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#520
