### ISSUE TITLE
Revise frame access API in the context of {N} 4.0

### ISSUE THREAD

**Issue by manoldonev** [NativeScript/NativeScript#5407]
### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- Cross-platform modules: 4.0.0

frame.topmost() API is the most obvious "static" API to access navigation frame that is very popular among customers. The fact that it just works (until now) is related to {N} apps mostly having a single internally created frame up to {N} 4.0. With {N} 4.0 we expose the ability to the developer to create multiple frames in different scenarios and there are scenarios where frame.topmost() is not really applicable. Generally frame.topmost() returns the last frame that performed navigation but that is not entirely obvious either from its name, or from the documentation -- with {N} 4.0 the following scenario will be possible that renders frame.topmost() meaningless:

- Root tabview with two tab items
- Each tab item contains frame as a root element (with defaultPage property set to module name)

When you load the app:
- First tab item is processed thus its frame is processed and navigation occurs to the page set as frame.defaultPage (implicitly this adds frame1 to the top of the frame stack)
- Second tab item is processed (nevertheless it is not visible) thus its frame is processed and its navigation entry is added to the navigation queue (but at the same time this implicitly adds frame2 to the top of the frame stack)

So if while playing with the visible first tab, you try to reference its frame via frame.topmost() you will actually get a reference to the invisible frame from the second tab.

Consider:
- Updating frame.topmost() documentation to explain that it returns the frame that performed navigation last
- Extend frame access API besides frame.topmost() to support scenarios like the one above (possible use frame.id and provide API for the user to lookup frames by id)
- Do we need the frame stack at all? Is it a stack or something else?

**Comment by MartoYankov** [comment]
@manoldonev 
Note: The frame.topmost() API returns the last navigated Frame instance that hasn't been already in the stack. This means that if you have 2 Frames and navigate in this order, Frame1 then Frame2 then again Frame1, the frame.topmost() API will return Frame2.
