### ISSUE TITLE
[TabView] Wrong navigation events fired when switching tab items with frames inside

### ISSUE THREAD

**Issue by manoldonev** [NativeScript/NativeScript#5412]
### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.1
- Cross-platform modules: 4.0.0

### Please tell us how to recreate the issue in as much detail as possible.
Wrong navigation events fired when switching tab items with frames inside.

1. Define tabview with two tab items (each tab item contains frame with page inside).
2. [Correct] On initial load page.onNavigatingTo/onNavigatedTo fired for first tab page.
3. [Correct] On switching to second tab page.onNavigatingTo/onNavigatedTo fired for second tab page.
4. [Not correct] On switching back to first tab page.onNavigatedFrom/onNavigatedTo fired for first tab page (no events should be fired as there is no actual navigation?)

**Comment by MartoYankov** [comment]
This should be fixed with https://github.com/NativeScript/NativeScript/pull/5468 .
