### ISSUE TITLE
AVCaptureDeviceInput with wrong definition

### ISSUE THREAD

**Issue by dartmann** [NativeScript/NativeScript#5414]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes, nothing helpful found.

### Tell us about the problem
The `AVCaptureDeviceInput` class has a wrong method definition for `deviceInputWithDeviceError`.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.1
- Cross-platform modules: 3.4.0
- Runtime(s): 3.4.0
- Plugin(s): 

### Please tell us how to recreate the issue in as much detail as possible.
While trying to implement a barcode scanning logic in my {N} plugin I stumbled across the `deviceInputWithDeviceError` method of the `AVCaptureDeviceInput` class. Given the method name, I thought that it should take two parameters: the device and an error reference. But with the current definition it only takes the device. 

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
The nativescript method definition:
```javascript
static deviceInputWithDeviceError(device: AVCaptureDevice): AVCaptureDeviceInput;
```
The Objective-C method definition (taken from the Apple docs):
```objectivec
+ (instancetype)deviceInputWithDevice:(AVCaptureDevice *)device 
                                error:(NSError * _Nullable *)outError;
```

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/ios-runtime#879
