### ISSUE TITLE
Tabview not rendering as intented

### ISSUE THREAD

**Issue by Meyer-dev** [NativeScript/NativeScript#5416]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

When increasing the tabview title font size the tabview extends past the width of the page .Is there a way to style the tabview as to reduce the margin between tabview  item icons as well as to allow the title text to extend wider than the width of the Icon.The margin between the respective icons and title text is also to small.The youtube app with bottom tab nav has the same style as i want to achieve.

### Which platform(s) does your issue occur on? 
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there.

**Comment by tsonevn** [comment]
HI @Meyer-dev.
Thank you for contacting us.
However, the provided info is not enough for investigating the problem. Please follow the template and provide the required information. Also, it will help if you send us sample project, which demonstrates the issue and could be debugged locally.

**Comment by Meyer-dev** [comment]
Hi Nikolay,thanks for the speedy response.I'm unsure how else i can explain
my troubles in more detail.I will attach two screen shots.One is the design
I'm trying to achieve(the one with product pics) and the other is what I've
been able to do.I require help regarding the styling of the tabview at the
top.I want to enlarge the text and create a margin between the text and
icons,without the tabview extending out of the page.I haven't been able to
locate such documentation on the internet.Your help is always greatly
appreciated.

HTML

<GridLayout visibility="{{ visibility1 ? 'visible' : 'collapsed' }}"
backgroundColor="white" class="fa">
<TabView selectedIndex="0" (selectedIndexChange)="onIndexChanged($event)"
sdkExampleTitle sdkToggleNavButton width=100% class="intabbtn
font-weight-bold">
<StackLayout *tabItem="{title: 'Groceries', iconSource:'res://groceries'}">
<label text="products will be displayed here" class="fa"></label>
</StackLayout>
<StackLayout *tabItem="{title: 'Recipes', iconSource:'res://recipe'}">
</StackLayout>
<StackLayout *tabItem="{title: 'Household', iconSource:'res://household'}">
</StackLayout>
<StackLayout *tabItem="{title: 'Health & Beauty',
iconSource:'res://healthnbeauty'}">
</StackLayout>
<StackLayout *tabItem="{title: 'Electricity',
iconSource:'res://electricity'}" class="fa">
<StackLayout class="m-l-30 m-r-30 m-t-30 m-b-20">
<Label text="Meter Number" style="font-size:'28'" class="h3 p-5"></Label>
<TextField [(ngModel)]="textFieldValue" style="font-size:'22'" hint="E.g
04076554165" keyboardType="phone" ></TextField>
<Label text="Amount" style="font-size:'28'" class="m-t-25 h3 p-5"></Label>
<StackLayout orientation="horizontal">
<Label text="R" style="font-size:'28'" class="m-r-10 h3 p-5"></Label>
<TextField [(ngModel)]="OwnValue" style="font-size:'22'" hint="E.g 50"
keyboardType="phone"></TextField>
</StackLayout>
</StackLayout>
<StackLayout class="m-t-30 bottombuttons">
<Button text="Request" class="btn-outline btn-rounded-lg font-weight-normal"
style="font-family: 'FontAwesome';font-size:'18'" width="150" (tap)=
"onButtonTap()"></Button>
</StackLayout>
</StackLayout>
</TabView>
</GridLayout>

css:

.intabbtn {
font-size: 6;
font-family: "WorkSans-Medium";
tab-text-color:$text-color;
android-selected-tab-highlight-color: #C2C4C6;
}

**Comment by tsonevn** [comment]
HI @Meyer-dev,
Which text you are trying to enlarge. The one inside the TabView item or the title of the items? Also for which platform you are building your project iOS, Android or for both?
I look forward to the sample screenshots, which demonstrates the case.

**Comment by Meyer-dev** [comment]
The title of the items without the tabview extending out of the page. I
attached the screenshots as attachments in the previous email. Did you
receive them?

**Comment by Meyer-dev** [comment]
Building for android

**Comment by tsonevn** [comment]
Hi @Meyer-dev,
For now, I could not see any images, which are attached to the issue. Could you check if you have uploaded them correctly?

**Comment by Meyer-dev** [comment]
I will attach again in this email.Thanks again for all the help :) the one
without the products is where i currently am regarding the design.

**Comment by tsonevn** [comment]
Hi @Meyer-dev,
Please attach the images via the web browser. The pictures which you are trying to add to the issue via email are still not available.

**Comment by Meyer-dev** [comment]
![screenshot_20180106-204507](https://user-images.githubusercontent.com/31076768/36200503-978f87da-1185-11e8-8fbc-6af02ec7f5b9.png)
![screenshot_20180206-090158](https://user-images.githubusercontent.com/31076768/36200517-a4832712-1185-11e8-93b3-2824130dcde4.png)

**Comment by Meyer-dev** [comment]
the top design is what i'm trying to achieve :)

**Comment by Meyer-dev** [comment]
i have attached the pics to the issue on github :)

**Comment by tsonevn** [comment]
Hi @Meyer-dev,
Thank you for the images.
To change the font-Size of the TabView Item titles, you could setup the fontSize property for the entire TabView and then to specify it for the internal content of the tab. For example:
HTML
```
<GridLayout  backgroundColor="white" class="fa">
    <TabView  class="tabviewstyle">
        <StackLayout class="layoutstyle" *tabItem="{title: 'Groceries', iconSource:'res://icon'}">
            <label text="products will be displayed here" class="fa"></label>
        </StackLayout>
       ........
        </StackLayout>
    </TabView>
</GridLayout>
```
CSS
```
.tabviewstyle {
    font-size: 15;
    font-family: "WorkSans-Medium";
    tab-text-color:green;
    android-selected-tab-highlight-color: #C2C4C6;
}
.layoutstyle{
    font-size: 10;
}
```
Also there is no functionality, which provides a way to control the margin between the TabItem title or icon. In case you would like to have some extra control on the Tabs styling, you could create custom TabView via GridLayout. For example:
```
<GridLayout rows="*, *" columns="*, *, *">
    <Label row="0" col="0" text="Tab1" textWrap="true"></Label>
    <Image row="1" col="0" src=""></Image>
    
    <Label row="0" col="1" text="Tab1" textWrap="true"></Label>
    <Image row="1" col="1" src=""></Image>

    <Label row="0" col="2" text="Tab1" textWrap="true"></Label>
    <Image row="1" col="2" src=""></Image>
    
</GridLayout>
```
Keep in mind that in this scenario you should manually control the visibility of the Layouts, where you will display the content. This could be done with the help of[ visibility property.](https://docs.nativescript.org/api-reference/classes/_ui_layouts_stack_layout_.stacklayout#visibility)

**Comment by Meyer-dev** [comment]
Hi .Thanks for the help.I have decided to create a custom Tabview as to
have more control over the styling.I have implemented the above code but
require some assistance regarding the visibility.The tabview is already
nested within a segmented bar.What will my TS file now have to look like?

html:

<SegmentedBar row="1" col="0" style.fontSize="26" [items]=
"segmentedBarItems" [(ngModel)]="selectedBarIndex" (selectedIndexChange)=
"onSelectedIndexChange($event)" class="m-5" style="font-family:
'FontAwesome'; color: #84C7C2;" selectedBackgroundColor="#84C7C2"></
SegmentedBar>
<GridLayout visibility="{{ visibility1 ? 'visible' : 'collapsed' }}"
backgroundColor="white" class="fa">
<GridLayout rows="*, *" columns="*, *, *, *, *">

<Image row="0" col="0" src="res://groceries" height="50"></Image>
<Label row="1" col="0" text="Groceries" textWrap="true" class="text-center
fa"></Label>
<Image row="0" col="1" src="res://recipe" height="50"></Image>
<Label row="1" col="1" text="Recipes" textWrap="true" class="text-center fa"
></Label>
<Image row="0" col="2" src="res://household" height="50"></Image>
<Label row="1" col="2" text="Household" textWrap="true" class="text-center
fa"></Label>
<Image row="0" col="3" src="res://healthnbeauty" height="50"></Image>
<Label row="1" col="3" text="Health & Beauty" textWrap="true"
class="text-center
fa"></Label>
<Image row="0" col="4" src="res://electricity" height="50"></Image>
<Label row="1" col="4" text="Electricity" textWrap="true" class="text-center
fa"></Label>
</GridLayout>
</GridLayout>

TS:

public items: Array<SegmentedBarItem>;
public selectedIndex = 0;
public visibility1 = true;
public visibility2 = false;
public visibility3 = false;

public onSelectedIndexChange(args) {
let segmetedBar = <SegmentedBar>args.object;
this.selectedIndex = segmetedBar.selectedIndex;
switch (this.selectedIndex) {
case 0:
this.visibility1 = true;
this.visibility2 = false;
this.visibility3 = false;
break;
case 1:
this.visibility1 = false;
this.visibility2 = true;
this.visibility3 = false;
break;
case 2:
this.visibility1 = false;
this.visibility2 = false;
this.visibility3 = true;
break;
default:
break;
}
}

**Comment by tsonevn** [comment]
Hi @Meyer-dev,
I reviewed your sample code and made some changes.
HTML
```
<GridLayout rows="auto, *" columns="*, *, *, *, *">
    <StackLayout (tap)="onTab('0')" row="0" col="0">
        <Image row="0" col="0" src="res://icon" height="50"></Image>
        <Label row="1" col="0" text="Groceries" textWrap="true" class="text-center
fa"></Label>
    </StackLayout>
    <StackLayout (tap)="onTab('1')" row="0" col="1">
        <Image row="0" col="1" src="res://icon" height="50"></Image>
        <Label row="1" col="1" text="Recipes" textWrap="true" class="text-center fa"></Label>
    </StackLayout>
    <StackLayout (tap)="onTab('2')" row="0" col="2">
        <Image row="0" col="2" src="res://icon" height="50"></Image>
        <Label row="1" col="2" text="Household" textWrap="true" class="text-center
    fa"></Label>
    </StackLayout>
    <StackLayout (tap)="onTab('3')" row="0" col="3">
        <Image row="0" col="3" src="res://icon" height="50"></Image>
        <Label row="1" col="3" text="Health & Beauty" textWrap="true" class="text-center
fa"></Label>
    </StackLayout>
    <StackLayout (tap)="onTab('4')" row="0" col="4">
        <Image row="0" col="4" src="res://icon" height="50"></Image>
        <Label row="1" col="4" text="Electricity" textWrap="true" class="text-center
fa"></Label>
    </StackLayout>
    <StackLayout backgroundColor="blue" [visibility]="visibility1 ? 'visible' : 'collapsed'" row="1" col="0" colSpan="5">
        <Label text="Tab 1" textWrap="true"></Label>
    </StackLayout>
    <StackLayout backgroundColor="yellow" [visibility]="visibility2 ? 'visible' : 'collapsed'" row="1" col="0" colSpan="5">
        <Label text="Tab 2" textWrap="true"></Label>
    </StackLayout>
    <StackLayout backgroundColor="green" [visibility]="visibility3 ? 'visible' : 'collapsed'" row="1" col="0" colSpan="5">
        <Label text="Tab 3" textWrap="true"></Label>
    </StackLayout>
    <StackLayout backgroundColor="red" [visibility]="visibility4 ? 'visible' : 'collapsed'" row="1" col="0" colSpan="5">
        <Label text="Tab 4" textWrap="true"></Label>
    </StackLayout>
    <StackLayout backgroundColor="orange" [visibility]="visibility5 ? 'visible' : 'collapsed'" row="1" col="0" colSpan="5">
        <Label text="Tab 5" textWrap="true"></Label>
    </StackLayout>


</GridLayout>
```
TypeScript
```
import { Component, OnInit } from "@angular/core";
import { SegmentedBarItem, SegmentedBar } from "ui/segmented-bar"
import { Item } from "./item";
import { ItemService } from "./item.service";

@Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
})
export class ItemsComponent {
    public items: Array<SegmentedBarItem>;
    public selectedIndex = 0;
    public visibility1 = true;
    public visibility2 = false;
    public visibility3 = false;
    public visibility4 = false;
    public visibility5 = false;

    public onTab(args) {
        this.selectedIndex = parseInt(args);
        switch (this.selectedIndex) {
            case 0:
                this.visibility1 = true;
                this.visibility2 = false;
                this.visibility3 = false;
                this.visibility4 = false;
                this.visibility5 = false;
                break;
            case 1:
                this.visibility1 = false;
                this.visibility2 = true;
                this.visibility3 = false;
                this.visibility4 = false;
                this.visibility5 = false;
                break;
            case 2:
                this.visibility1 = false;
                this.visibility2 = false;
                this.visibility3 = true;
                this.visibility4 = false;
                this.visibility5 = false;
                break;
            case 3:
                this.visibility1 = false;
                this.visibility2 = false;
                this.visibility3 = false;
                this.visibility4 = true;
                this.visibility5 = false;
                break;
            case 4:
                this.visibility1 = false;
                this.visibility2 = false;
                this.visibility3 = false;
                this.visibility4 = false;
                this.visibility5 = true;
                break;
            default:
                break;
        }
    }
}
```
In the sample code, I am using GridLayout with two rows on the first one I set the Layout responsible for the Tab buttons and on the second one the Layouts, where the page content will be displayed

**Comment by Meyer-dev** [comment]
Thanks for the help Nikolay. I have adapted my html to the code you
provided.I am however getting a typescript error.I think this may be
because of the visibility logic.My app uses the segmented bar to create 3
views of which one needs to feature the tabview with 5 possible views.I
will attach the code below as it stands.

HTML:

<GridLayout rows="*, auto" columns="*" tkMainContent >
<SegmentedBar row="1" col="0" style.fontSize="26" [items]=
"segmentedBarItems" [(ngModel)]="selectedBarIndex" (selectedIndexChange)=
"onSelectedIndexChange($event)" class="m-5" style="font-family:
'FontAwesome'; color: #84C7C2;" selectedBackgroundColor="#84C7C2"></
SegmentedBar>
<GridLayout visibility="{{ visibility1 ? 'visible' : 'collapsed' }}"
backgroundColor="white" class="fa">
<GridLayout rows="auto, *" columns="*, *, *, *, *">
<StackLayout (tap)="onTab('0')" row="0" col="0">
<Image row="0" col="0" src="res://icon" height="50"></Image>
<Label row="1" col="0" text="Groceries" textWrap="true" class="text-center
fa"></Label>
</StackLayout>
<StackLayout (tap)="onTab('1')" row="0" col="1">
<Image row="0" col="1" src="res://icon" height="50"></Image>
<Label row="1" col="1" text="Recipes" textWrap="true" class="text-center fa"
></Label>
</StackLayout>
<StackLayout (tap)="onTab('2')" row="0" col="2">
<Image row="0" col="2" src="res://icon" height="50"></Image>
<Label row="1" col="2" text="Household" textWrap="true" class="text-center
fa"></Label>
</StackLayout>
<StackLayout (tap)="onTab('3')" row="0" col="3">
<Image row="0" col="3" src="res://icon" height="50"></Image>
<Label row="1" col="3" text="Health & Beauty" textWrap="true"
class="text-center
fa"></Label>
</StackLayout>
<StackLayout (tap)="onTab('4')" row="0" col="4">
<Image row="0" col="4" src="res://icon" height="50"></Image>
<Label row="1" col="4" text="Electricity" textWrap="true" class="text-center
fa"></Label>
</StackLayout>
<StackLayout backgroundColor="blue" [visibility]="visibility1 ? 'visible' :
'collapsed'" row="1" col="0" colSpan="5">
<Label text="Tab 1" textWrap="true"></Label>
</StackLayout>
<StackLayout backgroundColor="yellow" [visibility]="visibility2 ? 'visible'
: 'collapsed'" row="1" col="0" colSpan="5">
<Label text="Tab 2" textWrap="true"></Label>
</StackLayout>
<StackLayout backgroundColor="green" [visibility]="visibility3 ? 'visible'
: 'collapsed'" row="1" col="0" colSpan="5">
<Label text="Tab 3" textWrap="true"></Label>
</StackLayout>
<StackLayout backgroundColor="red" [visibility]="visibility4 ? 'visible' :
'collapsed'" row="1" col="0" colSpan="5">
<Label text="Tab 4" textWrap="true"></Label>
</StackLayout>
<StackLayout backgroundColor="orange" [visibility]="visibility5 ? 'visible'
: 'collapsed'" row="1" col="0" colSpan="5">
<Label text="Tab 5" textWrap="true"></Label>
</StackLayout>
</GridLayout>
</GridLayout>
<GridLayout rows="*" visibility="{{ visibility2 ? 'visible' : 'collapsed'
}}" backgroundColor="white" class="fa">
<Label [text]="'CART'" class="m-5 h3 p-5 text-center" ></Label>
<StackLayout class="centeredlowered">
<StackLayout orientation="horizontal">
<Label text="Number of items :"></Label>
<Label text="5"></Label>
</StackLayout>
<StackLayout orientation="horizontal">
<Label class="text-center" text="Total Price (Inc. VAT) :"></Label>
<Label text="R 240"></Label>
</StackLayout>
</StackLayout>
<StackLayout orientation="horizontal" class="bottombuttons">
<Button class="btn-outline btn-rounded-lg m-r-10 m-b-5" text="Save Cart" (
tap)="onButtonTap()" width="110"></Button>
<Button class="btn-outline btn-rounded-lg m-l-10 m-b-5" text="Clear Cart" (
tap)="onButtonTap()" width="110"></Button>
</StackLayout>
</GridLayout>
<GridLayout rows="*" visibility="{{ visibility3 ? 'visible' : 'collapsed'
}}" backgroundColor="white" class="fa">
<Label [text]="'CHECKOUT'" class="m-5 h3 p-5 text-center"></Label>
</GridLayout>
</GridLayout>
</RadSideDrawer>

**Comment by Meyer-dev** [comment]
When using your typescript logic provided above it doesnt seem to work for
this case.This is my Typescript logic as it stands :

import { DrawerTransitionBase, SlideInOnTopTransition } from
"nativescript-pro-ui/sidedrawer";
import { Component, ViewChild, OnInit, AfterViewInit, ChangeDetectorRef }
from "@angular/core";
import { Page } from "ui/page";
import { ActionItem } from "ui/action-bar";
import { Observable } from "data/observable";
import { RadSideDrawerComponent, SideDrawerType } from
"nativescript-pro-ui/sidedrawer/angular";
import { RadSideDrawer } from 'nativescript-pro-ui/sidedrawer';
import { TabView, SelectedIndexChangedEventData, TabViewItem } from
"ui/tab-view";
import { SegmentedBar, SegmentedBarItem } from "ui/segmented-bar";
import { StackLayout } from "ui/layouts/stack-layout";
import { Item } from "./item";
import { ItemService } from "./item.service";



@Component({
selector: "Home",
moduleId: module.id,
templateUrl: "./home.component.html",
})
export class HomeComponent implements OnInit {
/* ***********************************************************
* Use the @ViewChild decorator to get a reference to the drawer component.
* It is used in the "onDrawerButtonTap" function below to manipulate the
drawer.
*************************************************************/
@ViewChild("drawer") drawerComponent: RadSideDrawerComponent;

private _sideDrawerTransition: DrawerTransitionBase;

/* ***********************************************************
* Use the sideDrawerTransition property to change the open/close animation
of the drawer.
*************************************************************/
ngOnInit(): void {
this._sideDrawerTransition = new SlideInOnTopTransition();
}

private getSegmentedBarItems = () => {
let segmentedBarItem1 = new SegmentedBarItem();
segmentedBarItem1.title = String.fromCharCode(0xf1e5);
let segmentedBarItem2 = new SegmentedBarItem();
segmentedBarItem2.title = String.fromCharCode(0xf07a);
let segmentedBarItem3 = new SegmentedBarItem();
segmentedBarItem3.title = String.fromCharCode(0xf064);
return [segmentedBarItem1, segmentedBarItem2, segmentedBarItem3];
}
segmentedBarItems: Array<SegmentedBarItem> = this.getSegmentedBarItems();
selectedBarIndex: number = 0;

constructor() {
}

public items: Array<SegmentedBarItem>;
public selectedIndex = 0;
public visibility1 = true;
public visibility2 = false;
public visibility3 = false;

public onSelectedIndexChange(args) {
let segmetedBar = <SegmentedBar>args.object;
this.selectedIndex = segmetedBar.selectedIndex;
switch (this.selectedIndex) {
case 0:
this.visibility1 = true;
this.visibility2 = false;
this.visibility3 = false;
break;
case 1:
this.visibility1 = false;
this.visibility2 = true;
this.visibility3 = false;
break;
case 2:
this.visibility1 = false;
this.visibility2 = false;
this.visibility3 = true;
break;
default:
break;
}
}

public onTab(args) {
this.selectedIndex = parseInt(args);
switch (this.selectedIndex) {
case 0:
this.visibility1 = true;
this.visibility2 = false;
this.visibility3 = false;
this.visibility4 = false;
this.visibility5 = false;
break;
case 1:
this.visibility1 = false;
this.visibility2 = true;
this.visibility3 = false;
this.visibility4 = false;
this.visibility5 = false;
break;
case 2:
this.visibility1 = false;
this.visibility2 = false;
this.visibility3 = true;
this.visibility4 = false;
this.visibility5 = false;
break;
case 3:
this.visibility1 = false;
this.visibility2 = false;
this.visibility3 = false;
this.visibility4 = true;
this.visibility5 = false;
break;
case 4:
this.visibility1 = false;
this.visibility2 = false;
this.visibility3 = false;
this.visibility4 = false;
this.visibility5 = true;
break;
default:
break;
}
}

get sideDrawerTransition(): DrawerTransitionBase {
return this._sideDrawerTransition;
}

/* ***********************************************************
* According to guidelines, if you have a drawer on your page, you should
always
* have a button that opens it. Use the showDrawer() function to open the
app drawer section.
*************************************************************/
onDrawerButtonTap(): void {
this.drawerComponent.sideDrawer.showDrawer();
}
}

I do however think im missing some logic regarding the navigation of the
Tabview...

**Comment by tsonevn** [comment]
Hi @Meyer-dev 
Please provide sample project, which demonstrates the issue, which you are facing.
