### ISSUE TITLE
How to Get Image Path from ImageAsset?

### ISSUE THREAD

**Issue by shibobrota** [NativeScript/NativeScript#5419]
Let's say we have a path of an image like "**/storage/emulated/0/Camera/IMG_1234_1234.jpg**"
And we have created an Image Asset with that path like 
```
import * as imageAssetModule from "tns-core-modules/image-asset/image-asset";
let picturePath = "/storage/emulated/0/Camera/IMG_1234_1234.jpg";
let asset = new imageAssetModule.ImageAsset(picturePath);
```
Now how to get the path from **asset** ??

**Comment by NickIliev** [comment]
@shibobrota although you can get the path of your ImageAsset you should consider that some native assets are stored in read-only folders and you won't be able to modify the asset. For example, when selecting an image with image picker from iOS gallery the returned imageAsset.ios is not a path but `PHAsset` (demonstrated [here](https://github.com/NativeScript/sample-ImageUpload/blob/master/app/main-page.js#L110-L115)).

So the safe thing to do is to store the received ImageAsset as ImageSource in a local path and work with that ImageSource.

Apart from that you can get the path with the following:
```
let asset = new imageAssetModule.ImageAsset(picturePath);
if (app.android) {
    console.log(asset.android)
} else if (app.ios) {
    console.log(asset.ios);
}

``
