### ISSUE TITLE
ListView IOS rendering bug

### ISSUE THREAD

**Issue by shabib3** [NativeScript/NativeScript#5421]
@NickIliev - I don't know if it is a new issue or the same as I opened 3 weeks ago (https://github.com/NativeScript/NativeScript/issues/5326)

I have this weird rendering bug in IOS - I have a chat that when you click a chat message you should see who watch the message already and the time that the message sent.

this is the video that shows the issue -> https://youtu.be/Zw3r2_xF_bg

the issue here is that when I click the message it show some change on the already painted elements (the chat message change his color) - but don't show the new elements that should be shown.
The only way to get those elements visible is to scroll until you can't see the message and then when you scroll down the elements are visible.

also, in the end of the video you can see that when I scrolled a lot up and fast the profile picture changed to every one of the senders to actually the same picture.

*** Note: the error that you can see on the VSCode isn't related to this issue.

**Comment by tsonevn** [comment]
HI @shabib3,
Thank you for the provided video
We reviewed the video; however, we are not able to see clear enough, what is the thrown error.
Please send us the error which is shown in the console as well as the latest version of your project or sample one, which could be used for debugging.



Thank you in advance for your cooperation.

**Comment by shabib3** [comment]
Hi @NickIliev - np!

like I said the error you see on the video has no related to this issue...

Here is a weird way to show the problem lol, I created a [Playground Sample](https://play.nativescript.org/?template=play-ng&id=PIwWsV).

`About the text content rendering issue on message click`:
Just click on the messages and see the issue (Note: on first click it looks like it is working so investigate this issue after the second click).

`About the picture rendering issue on fast scroll`:
I cannot reproduce it here because it seems to related to a resource picture...If you can add to the sample a resource picture and change let say all `Dave` `pic` property to it, then you would be able to reproduce it (You will understand why I wrote `Dave` when you will see the data I put on the sample lol :) )


If you need any help to understand the sample pls contact me! :)

**Comment by shabib3** [comment]
@tsonevn 

also I saw this [comment](https://github.com/NativeScript/nativescript-angular/issues/377#issuecomment-365700055), which actually solve to first rendering issue on message click...
so I don't know if it is the right solution to the issue, but I am going to use it until it will be fixed...

but the issue of the resource images rendering issue is still happening

**Comment by tsonevn** [comment]
The issue was related to the custom logic used for caching and loading the images in the ListView.
