### ISSUE TITLE
Detect App inactivity/idle timeout in NativeScript

### ISSUE THREAD

**Issue by atchakraborty** [NativeScript/NativeScript#5423]
I need to detect user's inactivity time in NativeScript app. I tried with few plugins (like ng-idle) but they are not compatible with NativeScript. I also tried to to emit application level event (in page router outlet) but it is not working either. Any help will be appreciated.

Infact I tried to extend activity, onPause, onResume everything is calling except **onUserInteraction**

`public onUserInteraction(): void {
        console.log("onUserInteraction overwritten from app.ts"); // OVERWRITTEN BEHAVIOUR
    }`

This piece of code never getting called.

Yes I have declared `@JavaProxy('com.tns.NativeScriptActivity')` and I have used **tns-platform-declarations** as well.

Please let me know what else to do?

**Comment by tsonevn** [comment]
HI @atchakraborty,
In your case, you could try using the [nativescript-idle](https://www.npmjs.com/package/nativescript-idle) plugin and check if it will work for your project.

**Comment by atchakraborty** [comment]
@tsonevn already used but its not giving me any option to check user interactivity or idle time. The only function is there for long waiting task. any other help?

**Comment by NickIliev** [comment]
@atchakraborty the repository is for logging issues, bugs and features related to NativeScript.
For how-to related questions please use the community channels like [the NativeScript forum](https://discourse.nativescript.org/), [SO ](https://stackoverflow.com/questions/tagged/nativescript)or [NativeScript community slack](https://nativescriptcommunity.slack.com/messages/general)

I have updated my sample with overwritten `onUserInteraction` method - the updated example can be found [here](https://github.com/NickIliev/NS-Issues-2018/tree/master/NativeScript/issue_5423).
The demo is very basic - keep in mind that you would like to extend the activity in a separate file and provide your own activity name (more details [here](https://docs.nativescript.org/angular/runtimes/android/advanced-topics/extend-application-activity)).
Instruction regarding the demo can be found [here](https://github.com/NativeScript/NativeScript/issues/2863#issuecomment-253174682)

Closing as duplicate to [https://stackoverflow.com/questions/48788676/detect-app-inactivity-idle-timeout-in-nativescript](https://stackoverflow.com/questions/48788676/detect-app-inactivity-idle-timeout-in-nativescript)

**Comment by nikoTM** [comment]
@NickIliev After extending this the application like that other event callbacks stopped firing within the app:

```
    app.on(app.suspendEvent, () => {
      console.log('suspended');
    });

    app.on(app.resumeEvent, () => {
      console.log('resumed');
    });
```

Those callbacks never log. Is that expected behavior? If not, how can I fix it? Also, is it possible to somehow expose `onUserInteraction` events to be used within the app through the same event system as in `app.on('userInteraction'...` ? Currently to get hold of that event I need to create an observable outside of Angular app, create and push that event through that observable to get hold of it within ng app. This  feels like a bad solution to me. Thanks.
