### ISSUE TITLE
iOS Instruments indicating a lot of leaks using the app created from the basic template

### ISSUE THREAD

**Issue by pentool** [NativeScript/NativeScript#5424]
## Please, provide the details below:
Hello, I have noticed a lot of leaks and memory issues in my app, so I have decided to try using iOS Instruments on the basic {N} app created from the default template to see what results I get.

The app is created using `tns create hello-world` cmd using the default template. I have put the same description in the video comments as below (https://www.youtube.com/watch?v=ceRLmqjesiw):

The {N} app created from the default template has the following UI items on the screen:
- label with text "Tap the button"
- a blue button with title "TAP"
- A label below the blue button, indicating the number of taps left.

(You can create the basic app by doing "tns create hello-world".)

1. Around 10 second, I tap on the window in an empty area. I do not tap on any UI elements. At that point the memory shoots up to about 200KB and I get 6,233 new leaks.

2. Right around the 30 second mark, I start tapping (and keep tapping) on the empty area of the window. While I do not get any leaks, the memory is going up every time I tap.

3. I start tapping on the blue button around the 1:10 mark. Notice the memory shoots up (blue areas) and I start getting leaks.

During the time I was tapping on an empty area of the window, while the memory was keep going up, there was no leak. Once I started tapping on the button (to count down), not only the memory started going up, but also got leaks - as indicated by the red marks every 10 or so seconds.

It is indicated that there are a few HUNDRED (!!!) new leaks at each red mark.

### Which platform(s) does your issue occur on?
iOS (not tested on Android)

### Please provide the following version numbers that your issue occurs with:
iOS 9.3.5
Xcode 8.2.1
TNS 3.4.2

### Please tell us how to recreate the issue in as much detail as possible.
1. Create the basic Hello World app using `tns create hello-world`.
2. Profile the memory of the app using iOS Instruments.

Link to video: https://www.youtube.com/watch?v=ceRLmqjesiw

**Comment by NickIliev** [comment]
@pentool thank you for your interest in NativeScript and for contacting us about the reports from `Instruments`. The topic was discussed [here ](https://github.com/NativeScript/NativeScript/issues/4490#issuecomment-324893202).

Notice the following exaplined by @ivanbuhov 

> the leaked memory is allocated, it seems that the Xcode Instruments consider the memory allocated here and here as leaked. Actually, this memory is owned by the FFICall instance and is deallocated in its destructor. However, most of the FFICall objects are never destructed (which is expected and desired behavior) and the memory is never deallocated (which is expected, too). It seems that this makes the Instruments to treat the memory as leaked, even if actually it is not.
> 
> Initially, I thought that the usage of new is what makes the Instruments tools to treat the memory as leaked, but even after refactoring the code to avoid the usage of new operator and replacing it with unique_ptr and std::vector objects saved as an instance variable (following the RAII technique), the allocations are still treated as memory leaks.


Closing as duplicate to [https://github.com/NativeScript/NativeScript/issues/4490#issuecomment-324893202](https://github.com/NativeScript/NativeScript/issues/4490#issuecomment-324893202)
