### ISSUE TITLE
Reponse type of 'blob' not supported on HttpClient

### ISSUE THREAD

**Issue by BeMor81** [NativeScript/NativeScript#5427]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
Reponse type of 'blob' not supported on HttpClient
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both
Tested just on Android

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) 3.4.2
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project) 3.4.0
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Getting the following error when running the following service below.

import { Injectable } from "@angular/core";
import { HttpParams, HttpClient, HttpHeaders, HttpResponse, HttpClientJsonpModule  } from "@angular/common/http";
import { Observable } from "rxjs/Observable";
import "rxjs/add/operator/map";

import { Config } from "../config";

@Injectable()
export class ImageLoaderService {
  constructor(private http: HttpClient) {}

  loadImage(imgUrl) {
    this.http.get(
      imgUrl, { responseType: 'blob' }
    ).subscribe();
  }
}

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1202
