### ISSUE TITLE
Feature request: Carthage support for iOS

### ISSUE THREAD

**Issue by Andrea65** [NativeScript/NativeScript#5429]
Would it be possible to support Carthage libraries besides Cocoapod?
I'm developping a plugin that uses a third party library supplied only in carthage/framework.

**Comment by tsonevn** [comment]
Hi @Andrea65,
Thank you for your suggestion.
Regarding that, we do not have plans for providing support for Carthage libraries in ios runtime.
However, we will log this issue as a feature request, and if there is interest, we will research how we could provide support for this lib in NativeScript.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/ios-runtime#882
