### ISSUE TITLE
Allow different ActionBar-s to be specified for different TabViewItems in a TabView app

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#543]
We have an application that uses a TabView for navigation, but also uses an ActionBar with different titles and ActionItems in the various TabViewItems. Currently this is handled in JavaScript code, it would be nice if this can be declaratively expressed in the UI XML.

**Comment by bradmartin** [comment]
+1

**Comment by N3ll** [comment]
Do you have any ideas how it might look like in XML?

**Comment by PanayotCankov** [comment]
``` XML
<Page>
  <TabBar>
    <TabBarItem>
      <TabBarItem.actionBar>
        <ActionBar title="page1" />
      </TabBarItem.actionBar>
    </TabBarItem>
    <TabBarItem>
      <TabBarItem.actionBar>
        <ActionBar title="page2" />
      </TabBarItem.actionBar>
    </TabBarItem>
  </TabBar>
</Page>
```

**Comment by hshristov** [comment]
Or even better if we have source property on TabBarItem where you specify path to xml page.

**Comment by bradmartin** [comment]
Yes @hshristov. That would help clean up a tabview source a lot.

**Comment by stevetayloruk** [comment]
+1

**Comment by maddy2get** [comment]
+1

**Comment by maddy2get** [comment]
Is there any alternative way of achieving this functionality at this stage?
