### ISSUE TITLE
nativescript angular generated *.js files could be moved to a "dist" folder to keep code clean

### ISSUE THREAD

**Issue by Abderrahmane-H** [NativeScript/NativeScript#5432]
### Tell us about the problem
when working with nativescript angular, and try to run "tns run android/ios" some js files are generated, those files could be generated in a dist folder instead of generating them in the same folder that contains the typescript source. 

![capture](https://user-images.githubusercontent.com/22124417/36356365-e9899178-14e8-11e8-82b6-154ba41aa941.PNG)

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.2

**Comment by tsonevn** [comment]
duplicated with #4842
