### ISSUE TITLE
Setting rowHeight property results in doubled row height on iOS

### ISSUE THREAD

**Issue by gummibjorn** [NativeScript/NativeScript#5441]
### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.2
- Cross-platform modules: 3.4.0
- Runtime iOS: 3.4.1
- iOS: 11.0 

### Please tell us how to recreate the issue in as much detail as possible.

* `tns create HelloWorld --template nativescript-template-ng-tutorial`
* create a listView and set rowHeight

```
import { Component } from "@angular/core";

@Component({
  selector: "my-app",
  template: `
    <ListView [items]="[1, 2]" rowHeight="40">
        <ng-template>
            <Label style.height="40" text="Label" style.background-color="#bbbbbb"></Label>
        </ng-template>
    </ListView>
  `
})
export class AppComponent {
  // Your TypeScript logic goes here
}
```

![image](https://user-images.githubusercontent.com/11292339/36415430-276854a0-1626-11e8-8e49-b89b2dbb90ec.png)

As you can see is the row height actually twice as high as expected. I also did not manage to fill the complete row with content. `style.height=100%` only fills half the row as well.

**Comment by NickIliev** [comment]
@gummibjorn thanks for reporting this issue - I can confirm that indeed this is unexpected behavior on iOS and marking this issue as a bug.

Steps to reproduce:
- use [this demo PlayGround](https://play.nativescript.org/?template=play-ng&id=jTSVNs)
- or [use this demo app](https://github.com/NickIliev/NS-Issues-2018/tree/master/NativeScript/issue_5441) (with **next** version)

Result: the `rowHeight` is adding extras space for each cell on iOS (works as expected on Android)

**Comment by NickIliev** [comment]
Reproducible with `tns-core-modules@4.0.0`

Example
```XML
<GridLayout rows="*" columns="*" backgroundColor="blue">
    <ListView items="[1, 2, 3, 5, 8, 13, 21, 34]"  rowHeight="40">
        <ListView.itemTemplate>
            <StackLayout>
                <Label text="Some Label" textWrap="true" height="40" backgroundColor="green" />
            </StackLayout>
        </ListView.itemTemplate>
    </ListView>
</GridLayout>
```

will produce the following on Android
![screen shot 2018-04-16 at 2 09 45 pm](https://user-images.githubusercontent.com/18008302/38805821-ec1fda00-417f-11e8-9277-b458445d834f.png)

while on iOS there will be additional space applied
![screen shot 2018-04-16 at 2 10 01 pm](https://user-images.githubusercontent.com/18008302/38805839-fefeaa48-417f-11e8-8624-80a4a46d2a89.png)

Test application [here](https://github.com/NickIliev/NS-Issues-2018/tree/master/NativeScript/issue_5441_tsc).
