### ISSUE TITLE
Feature Request: Hot Reload

### ISSUE THREAD

**Issue by bnussey** [NativeScript/NativeScript#5447]
Currently styling and polishing NativeScript UI is incredibly inefficient due to the full app reload necessary for any change. This has added many hours, days, weeks to our NativeScript project and we consider this a significant deterrent in using NativeScript for any new projects.

Both React Native and Flutter have solved this through their hot reload capabilities which preserves state and sees a refresh within milliseconds. 

Is this feature coming to NativeScript soon? 

![Flutter Hot Reload](https://user-images.githubusercontent.com/7215297/36455982-848edbdc-1657-11e8-824f-cba86a520d0d.gif)

![React Native Hot Reload](https://user-images.githubusercontent.com/7215297/36456045-c689acb0-1657-11e8-95ce-dc7484c85ef4.gif)

**Comment by cloudcover** [comment]
+1

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3384
