### ISSUE TITLE
Support ~ path syntax in require

### ISSUE THREAD

**Issue by slavchev** [NativeScript/NativeScript#545]
Support ~ path syntax in `require`. For example

```JavaScript
var mymodule = require('~/path1/path2/mymodule');
```

See:
* https://github.com/NativeScript/android-runtime/issues/177
* https://github.com/NativeScript/ios-runtime/pull/254

**Comment by jasssonpet** [comment]
What do you think of:

```javascript
var mymodule = global.require('./path1/path2/mymodule');
```

as an alternative?

**Comment by fealebenpae** [comment]
Or there's always `require.main.require('./my-top-level-module')` which I think is the node.js way to do it. It isn't implemented either but seems more logical to me than some string convention.

**Comment by atanasovg** [comment]
The string convention seems easier to use to me and is tied with less implicit logic underneath. Additionally, we may provide a property at the `file-system` module that returns the app root. This will enable a more verbose way to do something like:

```javascript
var fs = require("file-system");
var appRoot = fs.path.appRoot;
var myModulePath = fs.path.join(appRoot, "my-module");
var myModule = require(myModulePath);
```

**Comment by norfas** [comment]
Tilde (require('~/path1/path2/mymodule')) is more logical and clean approach to my taste.
It is also consistent with xml layout, e.g.:
<Image src="~/res/ctlArrangements1.png"/>

**Comment by fealebenpae** [comment]
@atanasovg: I would advise against tightly coupling the application assets, including any JavaScript files, to a filesystem idiom. Whether we load assets from a filesystem or something like `android.res.AssetManager` or `NSAssetData` is an implementation detail, and as we transition towards ES6 modules this rule should hold even more so.

In general I am against this change. I would much rather we reverted to simpler times when absolute paths passed to `require` resolved to the `app` folder in the application package, which would in turn obviate the need for the tilde character entirely.

**Comment by dspells** [comment]
I tend to agree agree with fealeaenpae.

If the concept of a "root" path is in the system then you should be able to use '/' as the first character to resolve to root.

var mymodule = require('/path1/path2/mymodule');

This is consistent with both the web definition of the "root"

http://www.motive.co.nz/glossary/linking.php?ref

and linux/unix
