### ISSUE TITLE
Launch Screen for IOS 

### ISSUE THREAD

**Issue by markomiljkovic** [NativeScript/NativeScript#5450]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes searched forum and . stackoverflow

### Tell us about the problem
Hello guys I have used website:
http://images.nativescript.rocks/
to generate NS Launch Image for my app
but when I put them in AppResources nothing changes ???

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.1

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there.

**Comment by tsonevn** [comment]
Hi @markomiljkovic,
Please provide sample project, which could be used for debugging and demonstrates the issue, which you are facing.

**Comment by EddyVerbruggen** [comment]
Just sharing my experience with launchscreens: once you think you've done everything right, make sure to reboot the device. Somehow the old screens remain cached..

**Comment by markomiljkovic** [comment]
I have upload sample app here, when I run my app for launch screen displays white background insted of my image in app resources
[My repository](https://github.com/markomiljkovic/NS-test)
Also Im testing this on IPhone 8 on Simulator IOS 11.2

**Comment by markomiljkovic** [comment]
Angular groceries app is loading launch screens just fine, but as soon I add my own I just see white screen.

**Comment by markomiljkovic** [comment]
Anybody ???

**Comment by markomiljkovic** [comment]
Solved it, you can close the issue :)

**Comment by markomiljkovic** [comment]
NEvermin, solved it closing issue :)

**Comment by Qanah** [comment]
@markomiljkovic i have same issue how can i fix it
