### ISSUE TITLE
Image orientation issue

### ISSUE THREAD

**Issue by han41858** [NativeScript/NativeScript#5454]
Tested in Android.
I took a photo in portrait mode, and create `<Image>` in 3 methods.

1. use `src` directly
file path is set in `<Image src="">`

2. use `fromFile()`
imageSource is set using `fromFile()` in component

3. use `fromFile()` & `fromBase64()`
get image with `fromFile()` and convert it using `toBase64String()`
and `imageSource` is set using `<Image [src]="base64Src">`

I expected all picture are shown in portrait mode, but only 2. case is ok.
Images are not rotating properly in 1, 3 cases.

![image](https://user-images.githubusercontent.com/15343639/36545416-2c785082-182c-11e8-8739-5986a6e3be8e.png)

when I checked image-source.android.js code,
setting rotation angle is invoked only in `loadFromFile()`

How can I get orientation info using `fromBase64()`?
I want to get orientation info in any file of cloud.

I attached my test project.

I'll wait for your reply.
thanks!!

[picture-rotation.zip](https://github.com/NativeScript/NativeScript/files/1748382/picture-rotation.zip)

**Comment by NickIliev** [comment]
@han41858 I can confirm that indeed the original rotation angle is not respected if the JPEG has a rotation set in its `ExifInterface`. This issue will be fixed when [this PR](https://github.com/NativeScript/NativeScript/pull/5110/files#diff-3ee24d371f8f1043555c731e0b683405R75) is merged and is planned to be published with NativeScript 4.0.0.

Meanwhile, you can get the orientation info only from the native image asset (for JPEGs with ExifData)
```
const ei = new android.media.ExifInterface(filename); // filename is the path to the native Android asset
const orientation = ei.getAttributeInt(android.media.ExifInterface.TAG_ORIENTATION, android.media.ExifInterface.ORIENTATION_NORMAL);

```
