### ISSUE TITLE
Jpeg malformed issue

### ISSUE THREAD

**Issue by han41858** [NativeScript/NativeScript#5455]
Tested in Android.

I read a image file using `fromFile()` & invoke `toBase64String('jpeg')` to get Exif in a photo.

in the jpeg spec, jpeg file start with `FF D8 FF` in hex.

and my image file starts with `FF D8 FF` in hex & just in jpeg spec.
![image](https://user-images.githubusercontent.com/15343639/36547312-ef27d57c-1830-11e8-8255-d4c8b84ff726.png)

but `toBase64String('jpeg')` **DECODED by base64** string is not starts with this order.
it's `0xFD 0xFD 0xFD`
I decoded base64 string with `android.util.Base64.decode()`.

anyway, <Image> using `fromBase64()` is ok, haha...

Is is ok case?

I attached test project.
[jpeg-malformed.zip](https://github.com/NativeScript/NativeScript/files/1748491/jpeg-malformed.zip)

I'll wait your reply.
thanks!!

**Comment by NickIliev** [comment]
@han41858 Perpahsp related to [this](https://stackoverflow.com/a/28460422)

**Comment by han41858** [comment]
@NickIliev I read that article, but it have been done in my code.

line 34~35
<pre>
const decodedJavaObj = android.util.Base64.decode(base64Str, android.util.Base64.NO_WRAP);
const decodedStrObj : any = new java.lang.String(decodedJavaObj);</pre>

`new String()` you talked is `new java.lang.String()` in my code.

Did I do something wrong?

**Comment by NickIliev** [comment]
@han41858 [this is the actual implementation ](https://github.com/NativeScript/NativeScript/blob/a94ec9946f3f80129ccf7690173d2dfb32882ec9/tns-core-modules/image-source/image-source.android.ts#L163-L179)of tobase64String for Android (in NativeScript) - what I am seeing is that we are exposing a quality property which might be causing the difference in the starting bytes (the default value is 100 when the arguments i emitted).

Still, you can use entirely native approach to [encode/decode to Base64](https://developer.android.com/reference/android/util/Base64.html) and skip the usage of the method if that raises any concerns.
