### ISSUE TITLE
Sample-Groceries project - not able to debug in andoid

### ISSUE THREAD

**Issue by velchev** [NativeScript/NativeScript#5457]
Hello, 
I am new to Nativescript development, and especially configurations. Trying to see how can I debug sample project. I have modified it a little bit before - added qr reader plugin and one to display qr codes. Everything works fine for ios. As debugging is not available for ios I configured android environment. Got an error about .gradlew. Please see the whole log trace attached. Thanks for the help... I am really stack with that tried everything that was looking like a solution online.
[log-trace.txt](https://github.com/NativeScript/NativeScript/files/1750889/log-trace.txt)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/sample-Groceries#297
