### ISSUE TITLE
gradle: how to setup correctly the searched location for platform custom files

### ISSUE THREAD

**Issue by attdona** [NativeScript/NativeScript#5462]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

Yes

### Which platform(s) does your issue occur on?

Android

### Version numbers that the issue occurs with:
- CLI: 3.4.2
- Cross-platform modules: 3.4.1
- Runtime(s): 3.4.1
- Plugin(s): NA

### How to recreate the issue in as much detail as possible.

I have a custom android file located at `app/App_Resources/Android/google_services.json` and I expect that it is copied in the right place of build output dir.  

`tns build android` give instead this error:

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':app:processDebugGoogleServices'.
    > File google-services.json is missing. The Google Services Plugin cannot function without it. 
      Searched Location: 
      /home/adona/dev/mammuth/okkio/platforms/android/app/src/nullnull/debug/google-services.json
      /home/adona/dev/mammuth/okkio/platforms/android/app/src/debug/nullnull/google-services.json
      /home/adona/dev/mammuth/okkio/platforms/android/app/src/nullnull/google-services.json
      /home/adona/dev/mammuth/okkio/platforms/android/app/src/debug/google-services.json
      /home/adona/dev/mammuth/okkio/platforms/android/app/src/nullnullDebug/google-services.json
      /home/adona/dev/mammuth/okkio/platforms/android/app/google-services.json

I can confirm that  `google-services.json` is copied into `platforms/android/app/src/main/res/google-services.json`.

This directory is not in the list of searched directory of the task `:app:processDebugGoogleServices`.

Observing the `nullnull` string into the search dirs above I suspect that I missing to configure some options.

There is a way to fix that?

My setup:

app/App_Resources/Android/app.gradle:

    dependencies {
	   compile 'com.google.firebase:firebase-core:11.8.0'
	   compile 'com.google.firebase:firebase-messaging:11.8.0'
	   compile "com.google.android.gms:play-services-base:11.8.0"
	}

	android {  
	  defaultConfig {  
	    generatedDensities = []
	    applicationId = "io.musa"  
	  }  
	  aaptOptions {  
	    additionalParameters "--no-version-vectors"  
	  }  
	} 

	apply plugin: 'com.google.gms.google-services'

platforms/android/build.gradle:

    buildscript {

        repositories {
            google()
            jcenter()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:2.3.3'
            classpath 'com.google.gms:google-services:3.2.0' // google-services plugin
        }
    }

    allprojects {
        repositories {
            google()
            jcenter()
            maven {
                url "https://maven.google.com" // Google's Maven repository
            }
        }
    }

    task clean(type: Delete) {
        delete rootProject.buildDir
    }

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#956
