### ISSUE TITLE
binding property wont update if setting to null or undefined

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/NativeScript#5467]
Kind of self explained.

I have a custom component on top of a textfield.
I use bind to bind the ```text``` property of my custom component to the ```text property of the textfield:
```
this.textField.bind(
            {
                sourceProperty: "text",
                targetProperty: "text",
                twoWay: true
            },
            this
        );
```
Now if i do ``` mytextcomp.text = null``` the textfield value is not cleared. Same thing with ``` mytextcomp.text =''```
null value should be accepted i think.

I am still investigating where it comes from.

**Comment by NickIliev** [comment]
@farfromrefug  this should work as you would expect -[ example here](https://github.com/NickIliev/NS-Issues-2018/tree/master/NativeScript/issue_5467).

**Comment by farfromrefug** [comment]
@NickIliev first thanks for the fast answer!

The code is on github
https://github.com/Akylas/cea.logistic
[this](https://github.com/Akylas/cea.logistic/blob/master/app/shared/ctextfield.ts) is the failing component

Now if you run the app, fill the "receiving_clerk" filed and click the "signature" button, the "receiving_clerk" field should get cleared as i do ```this.receiving_clerk = null;```
But it doesn't 
Right now i am debugging in ```Binding``` (nativecsript core) to see what's happening.
I see that it goes into ```onSourcePropertyChanged``` but nothing after.
Still working on it

**Comment by farfromrefug** [comment]
@NickIliev maybe you can help me a bit in debugging this.
When i use a tns textfield, if i do ```mytextfield.text = 'toto'``` what method is actually called on the ```TextField``` component? 
I thought it was [textProperty.setNative](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/text-base/text-base.android.ts#L104) but apparently not. that method seems only be to called when building from xml file. And i don't see the setter ... So i don't know where the ```TextField``` component actually updates it's nativeView text.

**Comment by NickIliev** [comment]
@farfromrefug as far as I understood you are extending the `nativescript-textinputlayout` plugin in your custom textfiled implementation in `shared/ctextfiled.ts` .. however, I am not able to run your project due to multiple failures like 
```
Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. 
```
The TS transpilation also fails on my side.

As your issue seems to be related to a specifics in the custom implementation I am closing this issue but please do let know if you can provide stable build to debug (contact me here or at the community slack channel: username **niliev**)
