### ISSUE TITLE
TabView contents are incorrectly sized on iPhone X

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/NativeScript#5470]
Platform: iOS
Device: iPhone X
N: 3.4.2

When using a `GridLayout` within a `TabView` dimensions seem to be incorrectly calculated when using `*` sizing. Switching tabs will correct the dimensions.

Given the below example, the green `StackLayout` will be positioned partially behind the `TabView` tabs as shown in the attached screen shots. After switching to tab 2 and back to tab 1 the layout will be rendered correctly. It seems like the bottom safe areas are not taken in to account when the view is first rendered. 

```
    <TabView id="tabView">
        <TabView.items>
            <TabViewItem title="Tab 1">
                <TabViewItem.view>

                    <GridLayout rows="*, auto">
                        <StackLayout row="0" backgroundColor="lightblue" />
                        <StackLayout row="1" backgroundColor="green" height="50" />
                    </GridLayout>
                    
                </TabViewItem.view>
            </TabViewItem>
            <TabViewItem title="Tab 2">
                <TabViewItem.view>
                    
                    <StackLayout>
                        <Label text="Tab 2" />
                    </StackLayout>

                </TabViewItem.view>
            </TabViewItem>
        </TabView.items>
    </TabView>
```

![iphonex-tabview](https://user-images.githubusercontent.com/1102402/36687997-086fc5ae-1b23-11e8-8ec0-23724fe0363d.png)

It's easy enough to fix some other safe-area related issues using code similar to the below but I have no idea how to go about solving this one.

```
    if (application.ios && application.ios.window.safeAreaInsets) {
        const bottomSafeArea: number = application.ios.window.safeAreaInsets.bottom;

        if (bottomSafeArea > 0) {
            application.addCss(`
                .safeareas-bottom { padding-bottom: ${bottomSafeArea} !important }
            `);
        }
    }
```

Adding extra padding works for the initial rendering but then the layout is wrong after switching tabs.

Are iPhone X and safe-areas officially supported yet? I've come across pull request https://github.com/NativeScript/NativeScript/pull/4893 which mentions safe-area support but I see no mention of this in the docs.

Sample project can be found here https://github.com/3rror404/IphoneXTest

**Comment by NickIliev** [comment]
@3rror404 thank you for the detailed description and for logging this issue!
I can confirm that indeed some layouts are not correctly sized on iPhoneX (safe area) with tns-core-modules 3.4.1.

The good news is that this issue is already fixed and the fix will be included in our next official release.
Meanwhile, for testing purposes, you can try the **next** with `npm i tns-core-modules@next --save`

Demo application testing the above snippet with next can be found [here](https://github.com/NickIliev/NS-Issues-2018/tree/master/NativeScript/issue_5470)

**Comment by NickIliev** [comment]
@3rror404 you should be able to migrate to **next** without much hassle - let me know if you need assistance at any point (you can find me at community slack - username **niliev**). 

The **next** release is under development and there is no migration guide at this point as the release is not in final stage. Once we are close to official release we will, of course, publish the changelog and related documents (and if needed a migration guide),
