### ISSUE TITLE
Can't rely on ObservableArray.length in a boolean expression

### ISSUE THREAD

**Issue by jorotenev** [NativeScript/NativeScript#5476]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
yes
### Tell us about the problem
I use the `.length` of an ObservableArray in an expression in XML like this
`<Button text="should disappear" tap="tapped" visibility="{{items.length === 0 ? 'visible' : 'collapse' }}"></Button>`
Even after adding items to the array, the visibility is still `visible`.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.0
- Cross-platform modules: 3.4.0
- Runtime(s): 3.4.0
- Plugin(s):    
```  "dependencies": {
    "font-awesome": "^4.7.0",
    "moment": "^2.18.1",
    "nativescript-localize": "^2.2.1",
    "nativescript-plugin-firebase": "^5.1.7",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-autocomplete": "^3.5.0",
    "nativescript-ui-calendar": "^3.5.0",
    "nativescript-ui-chart": "^3.5.0",
    "nativescript-ui-dataform": "^3.5.0",
    "nativescript-ui-gauge": "^3.5.0",
    "nativescript-ui-listview": "^3.5.0",
    "nativescript-ui-sidedrawer": "^3.5.0",
    "nativescript-unit-test-runner": "^0.3.4",
    "tns-core-modules": "^3.4.0",
    "tv4": "1.3.0",
    "underscore": "^1.8.3"
  },
  "devDependencies": {
    "@types/jasmine": "^2.6.2",
    "babel-traverse": "6.25.0",
    "babel-types": "6.25.0",
    "babylon": "6.17.4",
    "jasmine-core": "^2.9.0",
    "karma": "^2.0.0",
    "karma-jasmine": "^1.1.1",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.6.0",
    "typescript": "~2.6.2"
  }
}
```

### Please tell us how to recreate the issue in as much detail as possible.
Open the app from the linked repo and press the button. The `Label` will update with the correct value of `.length`, but the Button will still be visible.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
https://github.com/jorotenev/ns-data-binding-issue (based on `NativeScript/template-hello-world-ts`)

**Comment by NickIliev** [comment]
The `length` property is not an observable - the Array and its elements are the observables but not their attributes. This has an easy workaround - just introduce an observable property of type number that uses the items.lenght as a value.

**Comment by jorotenev** [comment]
Thanks for the response
From those two issues
https://github.com/NativeScript/nativescript-angular/issues/499
https://github.com/NativeScript/NativeScript/issues/1506
I was left with the impression that I can bind on the `.length`.

**Comment by terreb** [comment]
This is obviously a bug with ObservableArray length and boolean expressions in xml. Steps to reproduce:
1. Set an empty ObservableArray items
2. In xml <Label text="{{ items, items.length }}" /> shows 0 
3. Another label <Label text="{{ items, items.length == 0 }}" /> shows "true". All is good at this point.
3. Now add an item to array <Label text="{{ items, items.length }}" /> shows 1 - this means binding works.
4. The other label <Label text="{{ items, items.length == 0 }}" /> shows still "true", but should show "false".

**Comment by jorotenev** [comment]
@terreb this is exactly what I do in the sample repo at the end of the first post here

**Comment by kryptus36** [comment]
@NickIliev I think you should reconsider this bug. As @terreb points out, there is inconsistent behavior as outputting the length in the template binds as expected, but using it as a boolean fails. It confused me for a long time before finding this.
