### ISSUE TITLE
ActionBar title not visible when using a custom actionView

### ISSUE THREAD

**Issue by felix-idf** [NativeScript/NativeScript#5478]
### Did you verify this is a real problem by searching the [NativeScript Forum]
_Yes_, I created a thread in the [NativeScript Forum](https://discourse.nativescript.org/t/actionbar-title-not-visible-when-using-a-custom-actionview/4702) and I am thankful for the suggestions, but they could not solve the problem, so I want to share an official issue here. Maybe this is a real issue and there might be no workarounds.

### Tell us about the problem
The details are described in the [NativeScript Forum](https://discourse.nativescript.org/t/actionbar-title-not-visible-when-using-a-custom-actionview/4702), so please have a look at this thread for more information and the screenshots.

### Which platform(s) does your issue occur on?
iOS & Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.2
- Cross-platform modules: 3.4.0
- Runtime(s): 3.4.1

### Please tell us how to recreate the issue in as much detail as possible.
The code snippets are provided in the forum post as well.

Thank you in advance and best regards,
felix

**Comment by felix-idf** [comment]
I noticed, that I used a wrong syntax for defining the custom actionitem, that caused the issue of not showing the title.
Now I am having trouble in correctly positioning the SearchBar within the ActionBar, but that's a different thing, so I am closing this for now.

**Comment by aleksander351** [comment]
@felix-idf How did you implement your ActionBar?
Mine is:
 `

    <ActionBar [title]="title">
          <NavigationButton class="navigation-button" ios:visibility="collapsed" icon="res://menu" 
             (tap)="toggle()"></NavigationButton>                    
          <ActionItem icon="res://menu" android:visibility="collapsed" (tap)="toggle()" ios.position="left">
          </ActionItem>
          <GridLayout width="80" height="36" android.position="right" ios.position="right" horizontalAlignment="right">
                <app-upload [folder]="currentFolder" (updateView)="updateList($event)"></app-upload>
          </GridLayout>
    </ActionBar>
`
