### ISSUE TITLE
Expose public API controlling whether a Page should be added to the navigation backstack or not

### ISSUE THREAD

**Issue by atanasovg** [NativeScript/NativeScript#548]
It is a common use case to have some initial (and probably not only) page that the user should NOT be able to navigate back to - for example a LoginPage. Or an Authentication page. We should enable an API that allows for a page to be explicitly excluded from the back navigation. See [this thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/nativescript/eEDQJ4VinZw) for more information.

As a proposal, we may add an additional parameter to the [NavigationEntry API](https://github.com/NativeScript/NativeScript/blob/master/ui/frame/frame.d.ts#L127-L147) called `backstackVisible` (or alike).

**Comment by maknz** [comment]
:+1: for sure. I assume we can clear he backstack by wiping that collection manually, but being able to exclude a page from being pushed there in the first place would be helpful.

**Comment by lscown** [comment]
This'll be one of the options for people wanting to disable back-button navigation in android: #106

**Comment by manijak** [comment]
:+1:  Yes, please. This would solve the "disable back-button" issue on iOS as well.

**Comment by PanayotCankov** [comment]
Once done, we can update the samples like this: https://github.com/NativeScript/sample-Xpensity/blob/master/app/utils/navigation.ts#L9

**Comment by TobiasHennig** [comment]
:+1:

**Comment by maknz** [comment]
Additionally, a way to clear the backstack would be good also. For example, if you've currently got a few pages on the back-stack and use say, the new sidedrawer component to change sections, we'd want a fresh navigation stack, which could be achieved by wiping the backstack, and then navigating without adding to the backstack.

**Comment by jkappel71** [comment]
Yes Please.. I am in need of this currently ;)

**Comment by tjvantoll** [comment]
Is this API available?

The new commit seems to be in 1.3, but if I try using the code below I'm still able to navigate back on both iOS and Android.

```js
frameModule.topmost().navigate({
    moduleName: "path/to/my/view",
    backstackVisible: false
});
```

**Comment by mikebranstein** [comment]
In reference to @tjvantoll above, I don't believe this API works as intended. Tested 1.4.0, the code below still allows me to navigate backwards.

```javascript
frameModule.topmost().navigate({
    moduleName: "path/to/my/view",
    backstackVisible: false
});
```

**Comment by lscown** [comment]
`backstackVisible` doesn't add the navigated-to page to the backstack, but the backstack will still contain your previous entries. What you want to be using is `clearHistory`
```js
frameModule.topmost().navigate({
    moduleName: "path/to/my/view",
    clearHistory: true
});
```
