### ISSUE TITLE
Keyboard management - KeyboardAvoidingView

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [NativeScript/NativeScript#5480]
Does nativescript have something like react KeyboardAvoidingView?

I would love to see this.

And if there is, please link me something about it.

About:
https://facebook.github.io/react-native/docs/keyboardavoidingview.html

**Comment by tsonevn** [comment]
HI @diego-lipinski-de-castro,
Thank you for contacting us.
If I understand you correctly you looking for a way to adjust the position of the TextField based on the position of the keyboard.
Regarding that, you could use the [nativescript-iqkeyboardmanager](https://www.npmjs.com/package/nativescript-iqkeyboardmanager) plugin.

For any further questions please use our [forum ](https://discourse.nativescript.org/) or StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript).

**Comment by diego-lipinski-de-castro** [comment]
I like that, is there anything for Android? It could be related to this https://github.com/NativeScript/NativeScript/issues/5088 but i couldnt find any docs on it.

And yes "If I understand you correctly you looking for a way to adjust the position of the TextField based on the position of the keyboard." This is what I want

**Comment by tsonevn** [comment]
HI @diego-lipinski-de-castro,
This functionality should work out of the box in Android. The TextField position will be adjusted automatically after opening the keyboard. I am attaching example and GIF file which demonstrates the behaviour.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/1774126/Archive.zip)
![screencast 2018-03-02 at 9 50 39 am](https://user-images.githubusercontent.com/17448734/36888696-4f1e79e4-1dff-11e8-9555-63804e6ef0b8.gif)

**Comment by diego-lipinski-de-castro** [comment]
Oh nice, didnt saw that, thanks
