### ISSUE TITLE
Display weather icon

### ISSUE THREAD

**Issue by ngunhaSO** [NativeScript/NativeScript#5482]
### Tell us about the problem
Weather Icon does not display

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.2
- Cross-platform modules: ^3.4.0
- Runtime(s): tns-ios: 3.4.1
- Plugin(s): 
nativescript-angular: 4.2.0
angular/core: 4.2.5

### Please tell us how to recreate the issue in as much detail as possible.
I am creating a weather app where i need to show the icon accordingly. The Icon is downloaded from here: https://erikflowers.github.io/weather-icons/
After I downloaded the icon, i renamed and placed the css file under: app/assets/weathericons.css. I put the ttf file under: app/fonts/weathericons.ttf
In my css file for the component, i defined the rule for the font family like this: 
```
.wi {
    font-family: 'weathericons';
    font-size: 100px;
    text-align: center;
    color: green;
}
```

My template is like this:
```
<StackLayout class="weather_cardview">
    <Label [text]="icon" class="wi"></Label>
    <Label [text]="temperature" class="temperature"></Label>
    <Label [text]="weather" class="weather" textWrap="true"></Label>
</StackLayout>
```

I defined the icon code like this:
```
static WEATHER_ICONS = {
        day: {
            'clear': 0xf00d,
            'clouds': 0xf002,
            'drizzle': 0xf009,
            'rain': 0xf008,
            'thunderstorm': 0x010,
            'snow': 0xf00a,
            'mist': 0xf0b6
          },
          night: {
            'clear': 0xf02e,
            'clouds': 0xf086,
            'drizzle': 0xf029,
            'rain': 0xf028,
            'thunderstorm': 0xf02d,
            'snow': 0xf02a,
            'mist': 0xf04a
          },
          neutral: {
            'temperature': 0xf055,
            'wind': 0xf050,
            'cloud': 0xf041,
            'pressure': 0xf079,
            'humidity': 0xf07a,
            'rain': 0xf019,
            'sunrise': 0xf046,
            'sunset': 0xf052
          }
    }
```

To decode, i do:
`var iconToBeDisplayed = Config.WEATHER_ICONS[this.timeOfDay][this.weather];
this.icon = String.fromCharCode(iconToBeDisplayed);`

However, the app keeps displaying a big question mark instead of an actual icon. Everything works fine if i use font-awesome tff though

**Comment by tsonevn** [comment]
Hi @ngunhaSO,
Thank you for contacting us,
Based on the [documentation ](https://docs.nativescript.org/ui/icon-fonts#using-icon-fonts-in-nativescript)
> Remember: Android needs the actual filename (without extension) whereas iOS needs the font name. To be cross-platform-ready, you can provide both.

Regarding that, you should set the actual Font Family name in the CSS class for iOS. You could check it while double tapping on the ttf file. It will be open a window, where you could see the name. In your case, it is `Weather Icons`.
![screen shot 2018-03-01 at 9 01 52 am](https://user-images.githubusercontent.com/17448734/36831298-e3af03b0-1d2f-11e8-924a-b0843f6fe7a1.png)

Try changing the font family as it is shown below and verify if you will be able to reproduce the problem.
```
.wi {
    font-family: 'Weather Icons';
    font-size: 100px;
    text-align: center;
    color: green;
}
``` 
If the issue persists, please send us a sample project, which could be used for debugging.

**Comment by ngunhaSO** [comment]
Ahh, changing to use the font name works for iOS. Thanks!
