### ISSUE TITLE
Slow startup even with webpack

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/NativeScript#5483]
Hey. Of course there are some issues for this topic, but still annoying me. NativeScript is really slow on startup even with optimizations. With this command:

```
tns run android --bundle --env.uglify --env.aot --env.snapshot
```

It takes about 5 or 6 seconds on each startup. Any idea?

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-dev-webpack#451
