### ISSUE TITLE
Hello darkness my old friend, got exit code 65 again... (Firebase IOS)

### ISSUE THREAD

**Issue by ogmedia** [NativeScript/NativeScript#5485]
I've searched through the issues here, and it seems exit code 65 is common among builds. However, I've been unable to find a resolution for this particular case:

I am trying to run `tns build ios` and get code 65:
`platforms/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/FBSDKApplicationDelegate.m:58:3: error: unknown type name 'SFAuthenticationSession'
  SFAuthenticationSession *_authenticationSession NS_AVAILABLE_IOS(11_0);`
`platforms/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/FBSDKApplicationDelegate.m:173:20: error: unrecognized platform name iOS
    if (@available(iOS 11.0, *)) {`
I am trying to run this on the iPhone simulator, so I am fairly sure that I don't need the Apple Team ID in the xcode build conf. I had it working previously, but after adding and removing some plugins something seems to have gone awry.

I've tried `tns platform remove`, along with `rm -rf node_modules hooks platforms`, and also even tried updating the Pods via `pod repo update`.

Anyone run into this issue with Firebase?

- CLI: 3.4.2
- Cross-platform modules: 3.4.1
- Runtime(s): ios (3.4.1)
- Plugin(s): nativescript-plugin-firebase (5.1.7):
- NPM: 5.7.1
- Nodejs: 6.11.1

**Comment by ogmedia** [comment]
I should add, removing the nativescript-plugin-firebase DOES resolve this issue. However, that's not ideal.

**Comment by EddyVerbruggen** [comment]
Bump Xcode to version 9 and you're good.

**Comment by ogmedia** [comment]
Thanks @EddyVerbruggen - updated to Xcode 9 and seems to have resolved the issue!
