### ISSUE TITLE
Newline, line separation overrides

### ISSUE THREAD

**Issue by waszqba** [NativeScript/NativeScript#5486]
## Please, provide the details below:
There seems to be a problem with keeping line endings intact when running CLI. At first, when I generated project, git client prompted me to enable changing CRLF line separators apparently set by CLI to LF ones. I've changed every file to LF ending, but the CLI after each digestion of those files reverts line breaks to CRLF and that messes with my git. Is there, by any chance, a way to configure it?

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes, and I have found no topic on this.

### Which platform(s) does your issue occur on?
macOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.2
- Cross-platform modules: 3.4.1
- Runtime(s): 3.4.1 for both iOS and Android

### Please tell us how to recreate the issue in as much detail as possible.
Just change line endings in any file to LF and then run either tns run <platform> or tns debug <platform>. That's what I worked with

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3412
