### ISSUE TITLE
[ui/image] [fresco] aspectFit value not working dynamically?

### ISSUE THREAD

**Issue by kamlekar** [NativeScript/NativeScript#5492]
Hi,

I am capturing an image using nativescript-na-camera in portrait mode and displaying the image in a square by creating Image element dynamically using ui/image(for iOS), fresco(for Android) but some part(bottom) of the image is missing. I tried the property stretch with the values of aspectFit, aspectFill, and none but they are not working. 

Any suggestions?

Thanks.

**Comment by NickIliev** [comment]
@kamlekar consider posting the code involved in your project that is related to the issue.
It is not clear if the issue reproducible on iOS on Android or on both?  
If you are hitting an issue related to nativescript-fresco plugin (or another Fresco implementation) please move the issue in the related plugin's repository.

Follow the instructions for opening a new issue

## Please, provide the details below:

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

If you are hitting an issue related to nativescript-fresco plugin (or another Fresco implementation) please move the issue in the related plugin's repository.
