### ISSUE TITLE
Found peer TypeScript Error : CALL AND RETRY LAST ALLOCATION FAILED - JavaScript heap out of memory

### ISSUE THREAD

**Issue by jain1977** [NativeScript/NativeScript#5494]
Need Help with following

a) 32 Bit System
b) Created fresh template using tns create --ng (angular)
c) android add as platform
d) tns run command --- Android Emulator Starts ---but it gives this error
e) It is default code only. Not a single word has been written

![image 2018-03-06 at 11 14 21 am](https://user-images.githubusercontent.com/37097515/37015887-ae871458-212f-11e8-826c-0fa3c94a04d9.png)

Executing before prepare hook from nativescript-dev-typescript.js

Found peer TypeScript Error : CALL AND RETRY LAST ALLOCATION FAILED - JavaScript heap out of memory

Unable to apply changes on device : emulator-5554. Error is: TypeScript Compiler failed with exit code 3

Tried to dig on here & stack but no sucess

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3421
