### ISSUE TITLE
Cannot create uncancelable dialogs closable programmatically

### ISSUE THREAD

**Issue by fthuin** [NativeScript/NativeScript#5499]
Hello everyone,

My NativeScript App needs internet connectivity for any user action. So I would like to have an uncancelable dialog with the text 'Network connectivity lost' (user should not be able to use the app) that would appear when connectivity is lost, and disappear automatically when connectivity comes back.

My problem is:

* If I use dialogs.alert() or any other ui/dialogs functions, it will return a promise and not the dialog instance, so I'll never be able to close the dialog programmatically later.
* If I create a custom alert by myself, there is no option to make it uncancelable (at least in Android).

It seems to me that there is a missing feature. 

In this tns-core-modules page [https://github.com/NativeScript/NativeScript/tree/master/tns-core-modules/ui/dialogs]() it is said that there should be something like

```javascript
	require("globals");
	var dialogs = require("ui/dialogs");

	/// Splash 
	var d = new dialogs.Dialog("Loading...");
	d.show();
	setTimeout(function(){ d.hide(); }, 2000);

	//or cancelable loading dialog
	var d = new dialogs.Dialog("Loading...", 
		function(r){ dialogs.alert("You just canceled loading!"); }, { cancelButtonText: "Cancel" });
	d.show();
	setTimeout(function(){ d.hide(); }, 10000);
```

but it looks like it is not implemented.

**Comment by tsonevn** [comment]
Hi @fthuin,
In your case, I would suggest creating a modal page, which could be shown and close programmatically via code behind. For more info, you could review the[ sample code](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/modal-page) in nativescript-sdk-examples-ng.

**Comment by fthuin** [comment]
Hi @tsonevn ,

This was the second option 

> * If I create a custom alert by myself, there is no option to make it uncancelable (at least in Android).

I've seen no way to make the modal uncancelable as you pass it `ModalDialogOptions ` as option and it does not accept that kind of options.

Here is the code I wrote, I might be missing something.

```typescript
import { Component } from '@angular/core';
import { ModalDialogParams } from 'nativescript-angular/modal-dialog';

@Component({
    selector: 'connectivity-dialog',
    template: `
    <StackLayout margin="24" horizontalAlignment="center" verticalAlignment="center">
        <Label text="Network connectivity is unavailable."></Label>
    </StackLayout>
  `,
})
export class ConnectivityDialogComponent {
    static singleton: ConnectivityDialogComponent;

    prompt: string;
    constructor(private params: ModalDialogParams) {
        if (ConnectivityDialogComponent.singleton) {
            return ConnectivityDialogComponent.singleton;
        } else {
            this.prompt = params.context.promptMsg;
            ConnectivityDialogComponent.singleton = this;
        }
    }

    close() {
        this.params.closeCallback();
        ConnectivityDialogComponent.singleton = undefined;
    }
}
```

I wrote this code in `app.component.ts` 
```
        const options: ModalDialogOptions = {
            context: {
                promptMsg: 'Network connectivity is unavailable.',
            },
            fullscreen: false,
            viewContainerRef: this.viewContainerRef,
        };

        this.modalDialogService.showModal(ConnectivityDialogComponent, options);
```

I know I could make it fullscreen to avoid the user clicking outside but it really doesn't look good to have 1 sentence in a fullscreen modal.

**Comment by NickIliev** [comment]
@fthuin you can make certain dialogs uncancelable in Android using [`cancelable` boolean property](https://docs.nativescript.org/api-reference/interfaces/_ui_dialogs_.cancelableoptions#cancelable)

For example:
```

import { ActionOptions, CancelableOptions, action } from "tns-core-modules/ui/dialogs";

let options: ActionOptions = {
        title: "some title",
        message: "some message",
        cancelButtonText: "close",
        actions: ["yes", "no"],
        cancelable: false
}  

action(actionOptions);

```

Notice that the above will make the dialog to be uncancelable when user tries to interact outside its area - of course it will still be closed if the user chooses one of the actions or the close button

**Comment by victorblq** [comment]
I need to create an uncancelable dialog, using a component to handle some logical code, there is a way to achieve this? 
`var options = {
                viewContainerRef: this.viewContainerRef,
                context: {},
                fullscreen: false
            };

            this.modalService.showModal(ExecucaoAbertaComponent, options)
            .then((result: Funcionario) => {
                this.execucao.responsavel = result;
            });`
I tried put this in the dialog component:
`loaded(event) {
		if (isAndroid) {
			event.object._dialogFragment.getDialog().setCanceledOnTouchOutside(false);
		}
	}`
but sometimes I get a NullPointeException in the device console and the dialog does not show up.
