### ISSUE TITLE
Unknown Error: Execution failed for task ':app:transformClassesWithDexForF0F1Debug'.

### ISSUE THREAD

**Issue by Meyer-dev** [NativeScript/NativeScript#5501]
## Please, provide the details below:
When i build my code ,the project seems to build correctly but when running it on the android emulator the following error appears ;

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
 YES

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
* What went wrong:
Execution failed for task ':app:transformClassesWithDexForF0F1Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/telerik/widget/primitives/panels/RadScrollView$SavedState$1;

BUILD FAILED in 2m 18s
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.
Executing after-watch hook from C:\Users\meyer\pronto1\hooks\after-watch\nativescript-dev-sass.js
Executing after-watch hook from C:\Users\meyer\pronto1\hooks\after-watch\nativescript-dev-typescript.js

### Which platform(s) does your issue occur on?
iOS/Android/Both
ANDROID

### Please provide the following version numbers that your issue occurs with:
"dependencies": {
    "@angular/animations": "4.4.6",
    "@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/platform-browser": "4.4.6",
    "@angular/router": "4.4.6",
    "font-awesome": "^4.7.0",
    "nativescript-angular": "4.4.1",
    "nativescript-pro-ui": "3.2.0",
    "nativescript-theme-core": "1.0.4",
    "nativescript-ui-listview": "^3.5.0",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.5.2",
    "tns-core-modules": "^3.4.1",
    "zone.js": "0.8.18"

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Stacktrace:

**Comment by tsonevn** [comment]
Hi @Meyer-dev,
Thank you for contacting NativeScript team,
Regarding the problem, I would suggest removing the platform and adding it again. Then try to rebuild the project.
1. `tns platform remove android`
2. `tns platform add android`
3. `tns run android`

If this does not help, I would suggest reviewing [this thread](https://github.com/telerik/nativescript-ui-feedback/issues/417#issuecomment-346758056) where the similar issue is discussed.
If the problem persists, please send us the project, which will help us to debug it on our side.

**Comment by Meyer-dev** [comment]
Hi thanks for the help :) was about to close the issue. All I did was
update my plugins and rebuilt as you said.

Regards Meyer
