### ISSUE TITLE
Android real device problem

### ISSUE THREAD

**Issue by b4rtt** [NativeScript/NativeScript#5503]
Hi, I have strange problem with my app. On iOS is everything working good.

When I try my app launch on Android virtual device it's working good too.

But when I connect my real device and run it app gives me this error.

JS: ANGULAR BOOTSTRAP DONE. 5816
10:32:49 PM - Compilation complete. Watching for file changes.
I/dalvikvm(18332):   at com.tns.Runtime.callJSMethodNative(Native Method)
I/dalvikvm(18332):   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
I/dalvikvm(18332):   at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
I/dalvikvm(18332):   at com.tns.Runtime.callJSMethod(Runtime.java:957)
I/dalvikvm(18332):   at com.tns.Runtime.callJSMethod(Runtime.java:941)
I/dalvikvm(18332):   at com.tns.Runtime.callJSMethod(Runtime.java:933)
JS: ERROR Error: java.lang.OutOfMemoryError
JS:     android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
JS:     android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:709)
JS:     android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:685)
JS:     android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:447)
JS:     android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:486)
JS:     android.graphics.drawable.Drawable.createFromPath(Drawable.java:1005)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:957)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:941)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:933)
JS:     com.tns.gen.org.nativescript.widgets.Async_CompleteCallback.onComplete(Async_CompleteCallback.java:12)
JS:     org.nativescript.widgets.Async$Http$HttpRequestTask.onPostExecute(Async.java:585)
JS:     org.nativescript.widgets.Async$Http$1$1.run(Async.java:486)
JS:     android.os.Handler.handleCallback(Handler.java:733)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:146)
JS:     android.app.ActivityThread.main(ActivityThread.java:5602)
JS:     java.lang.reflect.Method.invokeNative(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:515)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
JS:     dalvik.system.NativeStart.main(Native Method)
JS: ERROR TypeError: Cannot read property 'id' of null

**Comment by b4rtt** [comment]
Here is my logcat https://pastebin.com/xqigucyG

**Comment by carlosdelfino** [comment]
ERROR Error: java.lang.OutOfMemoryError

**Comment by Plamen5kov** [comment]
Hi @b4rtt 
Could you fill out the issue template and repost or edit this issue so we're able to better help you?
Seeing the log, I can't know what the possible issue might be, so a small repo reproducing the problem would be very helpful.
