### ISSUE TITLE
RadSideDrawer, and dynamic actionBar Directive

### ISSUE THREAD

**Issue by sanchez182** [NativeScript/NativeScript#5505]
Hi. I have a question. Is it possible to do this?

I have a directive @Directive, which is responsible for creating my <ActionBar> dynamically to save code between screens, now I want to use that feature and implement RadSideDrawer in my application, I try to pass <RadSideDrawer #drawer from Html to my directive. and capture it with @ViewChild ("drawer") drawerComponent: RadSideDrawerComponent;
But it does not work, it gives an undefined error in my derective. All this so that when you press the NavigationButton button, open the drawerComponent component with
this.drawerComponent.sideDrawer.showDrawer ();
Sorry for my English.

My HTML
Search.component.html

<RadSideDrawer showOverNavigation="true" [drawerTransition]="sideDrawerTransition"
   appActionBar appToggleNavButton #drawer >
    <StackLayout tkDrawerContent>
        <MyDrawer [selectedPage]="'Search'"></MyDrawer>
    </StackLayout>

    <GridLayout class="page page-content" tkMainContent  >
        <Label class="page-icon fa" text="&#xf002;"></Label>
        <Label class="page-placeholder" text=""></Label>
    </GridLayout>
</RadSideDrawer>
------------------------------------------
My Directive appToggleNavButton 
ToggleNavButtonDirective.ts 
.....
@Directive({
  selector: "[appToggleNavButton]"
})
export class ToggleNavButtonDirective implements  AfterViewInit, OnInit {

@ViewChild("drawer")  drawerComponent: RadSideDrawerComponent;
private drawer: RadSideDrawer;

constructor(route: ActivatedRoute, private page: Page, private _changeDetectionRef: ChangeDetectorRef,
            private routerExtensions: RouterExtensions) {
    let navigationButton = this.createNavigationButton();
    page.actionBar.navigationButton = navigationButton;
}
ngAfterViewInit() {
  console.log("----" + this.drawerComponent); //here.....Undefined
//  this.drawer = this.drawerComponent.sideDrawer;
  this._changeDetectionRef.detectChanges();
}
createNavigationButton(): NavigationButton {
    let navigationButton = new NavigationButton();
    navigationButton.visibility = "visible";

    if (app.android) {
        navigationButton.icon = "res://menu";
        navigationButton.on("tap", (args: EventData) => {
     //     this.drawer.showDrawer(); Here I want to open my RadSideDrawer
        });
    } else if (app.ios) {
        navigationButton.text = "";
    }
    return navigationButton;
}
-------------

Thank you

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#564
