### ISSUE TITLE
Android Modal closeCallback does not close modal window.

### ISSUE THREAD

**Issue by glen-stephens** [NativeScript/NativeScript#5508]
The issue occurs when I am on a page that a modal will be launched from.  If while on that page I leave the app, then return to the app and then launch the modal, the closeCallback function fires in my code so that I can catch the data passed back in the closeCallback function, but the modal does not close and is not dismissed.  However, the hardware back button does dismiss the modal.  I have tried programmatically closing it from my closeCallback function and it does not work.  Have verified that this is an Android ONLY issue.  This is for vanilla NativeScript. Any work around or fix of the issue would be great!

"tns-android": {
      "version": "3.4.2"
    }

**Comment by tsonevn** [comment]
Hi @glen-stephens,
We have tested your case with the modal page, however, it was correctly closed on our side while opening the app from suspend mode. For your convenience, I am attaching a sample project. Please review it and make the needed changes, which will allow us to recreate your scenario.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/1793031/Archive.zip)
