### ISSUE TITLE
Implement an image picker

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#551]
Create a module that allows you to invoke the native utilities that would let your users select images from the phone.

 - [ ] For iOS research if [UIIMagePickerController](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIImagePickerController_Class/) will be sufficient
 - [ ] [For android you we can open image picker with an intent](http://stackoverflow.com/questions/2507898/how-to-pick-an-image-from-gallery-sd-card-for-my-app)
 - [ ] The implementation details seem close to the [camera](https://github.com/NativeScript/NativeScript/tree/master/camera) module, extend it if possible

**Comment by PanayotCankov** [comment]
This is moved to an external plugin.

**Comment by bradmartin** [comment]
Is this the right issue for the module or is it #249? They're both closed...

**Comment by valentinstoychev** [comment]
There is an image picker implemented already. It will be part of the next Telerik UI update. cc: @ginev 

@bradmartin - if you need it earlier, please send me an email valentin.stoychev@telerik.com, so we can give you the internal version.

**Comment by bradmartin** [comment]
Thanks @valentinstoychev - is the Telerik UI update planned with 1.4 of Nativescript? Where can I find the roadmap or planning for the UI suite? Will this be a free piece or paid plugin/module? Thanks again for letting me know.

**Comment by valentinstoychev** [comment]
Yes - Telerik UI update is planned with 1.4. The Image PIcker will be one of the free components there.

There is still not too much info about the roadmap as this is very early preview version, but we are planning a dedicated web page on this. 

What would you like to see there as part of the suite?

**Comment by bradmartin** [comment]
Well the more the better :) is this image picker going to have a
customizable UI? Is that why its in the UI suite? Because at first when I
read it was in the UI suite I thought that seemed odd because I was
thinking it was just a module to mirror the functionality of the Cordova
plugin for hybrid apps so can you give more info about it in the meantime.
I'm sure others will see this thread :)

**Comment by valentinstoychev** [comment]
Yes - there is UI. We needed it in order to enable the multi-selection, which is not supported by default in all the OS. cc: @PanayotCankov

**Comment by valentinstoychev** [comment]
The image picker plugin is already available here - https://plugins.telerik.com/nativescript/plugin/multi-select-image-picker

**Comment by chrillewoodz** [comment]
@valentinstoychev So.. For anything below IOS 8 what should we use?
