### ISSUE TITLE
NS goBack not working sometimes

### ISSUE THREAD

**Issue by markomiljkovic** [NativeScript/NativeScript#5510]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes

### Tell us about the problem
Hello guys I have a small problem it seems to me that this code:
```
const topmost = require("ui/frame").topmost;
topmost().goBack();
```
for navigating back wont work sometimes,
ISSUE is when I open app and a go to somepage
and then leave that page open for some time for example 5,10 min
and then I tap on button that executes code above,
method is called but it wont navigate me to previous page,
seems like after some time page is removed from stack.
but if I go directly for example:
```
const topmost = require("ui/frame").topmost;
topmost().navigate('./views/somepage');
```
then its working :)
### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.3.1

**Comment by tsonevn** [comment]
Hi @markomiljkovic,
We tested your case with latest CLI 3.4.2 modules and runtime, and the back navigation seems to work as expected. I am attaching sample application, please review it and provide the needed changes, which will allow us to recreate the case on our side.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1793154/Archive.zip)
