### ISSUE TITLE
ObservableArray add .clear() or .removeAll()

### ISSUE THREAD

**Issue by LorenDorez** [NativeScript/NativeScript#5515]
I was surprised to find ObservableArry doesnt have a clear or removeAll method. 

Here is my usage senario
I am using OA to build a list view and add search functionality to it. So i carry and originalValues array and a values array. I the the originalValues array upon search and then load this into the values array. If i override the values array like values = filteredItems then this breaks the data-binding and the listview isnt updated. If i do values.push(filteredItems) then the listview is updated but the old values are not removed.

For now i call
while(values.length){
            values.pop();
        }

But would be nice to have a clear or remove all method to handle this

**Comment by tsonevn** [comment]
Hi @LorenDorez,
Thank you for your suggestion. I logged this issue as a new feature request. For further info, please keep track on the issue.

**Comment by MartoYankov** [comment]
@LorenDorez
The ObservableArray is designed to follow the API of the JS Array. The specs do not include a clear() or removeAll() method. If you want to empty the array you should use  `arrayInstance.length = 0` or `arrayInstance.splice(0)`. They do the same thing. You should also be able to use `splice()` to replace all or some items of an array with new items. See the example at [MDN](https://developer.mozilla.org/enUS/docs/Web/JavaScript/Reference/Global_Objects/Array/splice).

**Comment by LorenDorez** [comment]
@MartoYankov 
Thanks the link is broken but i managed to find it. The splice(0) is much cleaner so I switched to that. I cant use it to replace items as they might not be in the same order. I understand with wanting to keep it to eh JS standard just thought of it as a suggestion,

**Comment by VladsGG** [comment]
I'm trying to use the OservableArray.clear(); but it puts out an error that it is not a function

**Comment by NickIliev** [comment]
@VladsGG there is no `clear` method for the reasons discussed above

**Comment by VladsGG** [comment]
Is there any alternative code to clear all items in array?

**Comment by NickIliev** [comment]
@VladsGG [the answer is posted in the very same thread two posts above your question...](https://github.com/NativeScript/NativeScript/issues/5515#issuecomment-372622094)
