### ISSUE TITLE
tns platform remove android freezing

### ISSUE THREAD

**Issue by dbay920** [NativeScript/NativeScript#5516]
### Tell us about the problem
**tns platform remove android is freezing after installing updated tns version, doesn't get past "Gradle build...". ios platform was successfully removed and added back**

### Which platform(s) does your issue occur on?
**NA (occurs in CLI)**

### Please provide the following version numbers that your issue occurs with:
- CLI: **3.4.3**
- Cross-platform modules: **3.4.1**
- Runtime(s): **Android: 3.4.2 IOS: 3.4.1**

### Please tell us how to recreate the issue in as much detail as possible.
**I'm using terminal on a mac, my repo is here: [github.com/dbay920/phn-app.git*](https://github.com/dbay920/phn-app.git)

**Comment by tsonevn** [comment]
Hi @dbay920,
We tested your scenario with tns remove command while using your project, however, was unable to recreate it.
Can you provide more info on the problem and if there is thrown an error after starting `tns platform remove android`?
You could also try deleting the platform folder manually with `rm -rf platform`.
If the problem persists, run in the console `tns platform remove android --log trace` and send us the full log from the console.

**Comment by dbay920** [comment]
Recloned and seems to be working ok
