### ISSUE TITLE
Use hook to enable/disable a plugin

### ISSUE THREAD

**Issue by jolafrite** [NativeScript/NativeScript#5518]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

Yes, forum
Created a topic but no answer

https://discourse.nativescript.org/t/use-hook-to-disable-a-plugin/4829

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

As explain on the forum, i would like to enable/disable a plugin at startup time and based on my environment prod/dev

### Which platform(s) does your issue occur on?
iOS/Android/Both

Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

Latest

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there.

**Comment by NickIliev** [comment]
@jolafrite from what I've understood you are using nativescript-dev-webpack you don't want to drag this plugin in production - if that is the case just make sure that you are installing it as a `devDependency`
```
npm i nativescrtipt-dev-webpack --save-dev
```

**Comment by jolafrite** [comment]
but put my plugin into devDependency won't ship file into to device, no ?
