### ISSUE TITLE
view size clipping issue on iOS

### ISSUE THREAD

**Issue by dbay920** [NativeScript/NativeScript#5519]
### Tell us about the problem
**See if you can help me figure this out:
On ios (device and emulator)
Open app -> tap on services or providers -> there is a gray bar at the bottom that is right above the tabview. When you navigate off then back it goes away…
My backend guy says: _that has something to do with the way the height of the listview is calculated i believe. on the first pass it thinks its a certain height but after actually rendering on the screen it figures out that its not high enough._ 
But I'm not sure how to fix this, see screenshot below**

![img950006](https://user-images.githubusercontent.com/4195311/37226514-2f1fb1c2-23a8-11e8-914c-e5ae378518cd.png)

### Which platform(s) does your issue occur on?
**iOS**

### Please provide the following version numbers that your issue occurs with:
- CLI: **3.4.3**
- Cross-platform modules: **3.4.1**
- Runtime(s): **Android: 3.4.2 IOS: 3.4.1**

### Please tell us how to recreate the issue in as much detail as possible.
**My repo is here: [github.com/dbay920/phn-app.git*](https://github.com/dbay920/phn-app.git)**

**Comment by tsonevn** [comment]
Hi @dbay920,
Thank you for the attached project,
I tested t on my side. However, the ListView in the Services component was rendered as expected without the grey space on the bottom page. I tested it on iPhone 7 (iOS 11.2). For your convenience I a, attaching ScreenShot from the simulator. 
![screen shot 2018-03-12 at 8 56 47 am](https://user-images.githubusercontent.com/17448734/37269641-23414e6e-25d4-11e8-9be5-90d3539a8448.png)

SOmething that you could try on your side is to replace the StackLayout with GridLayout as follow the example below and to check if you will have the same issue.
```
<GridLayout rows="auto *" width="100%" >
    <CardView row="0"
        elevation="40"
        radius="2"
        height="90pt"
        class=""
    >
        <StackLayout
            class="primary-background"
            height="90pt"
            orientation="horizontal"
        >
            <Image
                src="res://icon_service_home"
                height="30"
                class="col-2 m-4"
            >

            </Image>
            <Label
                text="Services"
                class="double-columbian white font-weight-bold col-10"
                style="padding-left: 5pt; vertical-align: middle;"
            >

            </Label>
        </StackLayout>
    </CardView>
    <ListView
    row="1"
        [items]="services"
        style="background-color: #cecece;"
    >
        <ng-template
            let-item="item"
            let-i="index"
            let-odd="odd"
            let-even="even"
        >
            <StackLayout
                orientation="horizontal"
                horizontalAlignment="center"
            >
                <CardView
                    elevation="40"
                    radius="2"
                    [class.hidden]="odd"
                    height="80pt"
                    class="m-4 col-6"
                    (tap)="listViewItemTap(i)"
                    horizontalAlignment="center"

                >
                    <Label
                        [text]="item.getName()"
                        textWrap="true"
                        class="svc-card great-primer font-weight-bold primary text-center white-background py-16"
                        verticalAlignment="center"
                    >

                    </Label>
                </CardView>
                <CardView
                    elevation="40"
                    radius="2"
                    [class.hidden]="odd || i + 1 >= services.length "
                    height="80pt"
                    class="m-4 col-6"
                    (tap)="listViewItemTap(i+1)"
                >
                    <Label
                        [class.hidden]="i + 1 >= services.length"
                        [text]="i + 1 < services.length ? services[i + 1].getName() : i"
                        textWrap="true"
                        class="svc-card great-primer font-weight-bold primary text-center white-background py-16"
                        verticalAlignment="center"
                    >

                    </Label>
                </CardView>
            </StackLayout>
        </ng-template>
    </ListView>
</GridLayout>

```

Let me know whether this helps.

**Comment by dbay920** [comment]
Thanks for the advice, I'll see if swapping in GridView fixes this issue on my end.

**Comment by dbay920** [comment]
That worked! Thank you so much! 😄

**Comment by dbay920** [comment]
Any idea why changing to GridLayout causes android to not display the view?
