### ISSUE TITLE
Detect NativeScript as the environment

### ISSUE THREAD

**Issue by TobiasHennig** [NativeScript/NativeScript#552]
I need to detect NativeScript as the environment to extend a script to use the NativeScript `file-system` module instead of the node `fs` module, but i don't know how to detect it.

Something like:
```js
if (typeof window === 'undefined') {
    // It is node
}

if (typeof global !== 'undefined' && ???) {
    // It is NativeScript
}
```

**Comment by valentinstoychev** [comment]
I think this is a good idea for implementation. For the moment you can define global.NativeScript = true; in your app.js file and check it later in your app.

**Comment by valentinstoychev** [comment]
For the moment if you are trying to use it in a module this will also work:
```if (global.android || global.NSObject)```

**Comment by TobiasHennig** [comment]
Thanks for the feedback, thats my current solution. :)

**Comment by TobiasHennig** [comment]
Should i close this issue know?

**Comment by atanasovg** [comment]
We discussed this internally and agreed that semantically the approach is the same as in other JavaScript worlds - in other words, you check whether something is available on the global context to detect your current execution environment. So, closing the issue.
