### ISSUE TITLE
The way to optimize the app developed by NativeScript 

### ISSUE THREAD

**Issue by zhangsuimi** [NativeScript/NativeScript#5520]
I developed an APP for Android using NativeScript ,and my computer OS is Windows.
I want to optimize its performance,can anyone give me some advice?
Thanks !!!!

**Comment by NickIliev** [comment]
Check [this blog post](https://www.nativescript.org/blog/deep-dive-into-nativescript-3.1-performance-improvements) but notice that you can improve your application performance in many ways de[pending on whether you are using Angular or NativeScript Core and also depending on your own business logic that stands behind the application.

@zhangsuimi keep in mind that the repository is for logging issues, bugs and features related to NativeScript.
For how-to related questions please use the community channels like [the NativeScript forum](https://discourse.nativescript.org/), [SO ](https://stackoverflow.com/questions/tagged/nativescript)or [NativeScript community slack](https://nativescriptcommunity.slack.com/messages/general)

**Comment by zhangsuimi** [comment]
Thank you !
