### ISSUE TITLE
System.err: Error running script /data/user/0/br.com.mobile.client/files/internal/livesync.js

### ISSUE THREAD

**Issue by Fatme** [NativeScript/NativeScript#5521]
_From @carlosdelfino on March 10, 2018 2:55_

# The problem

On livesync randomly throw: 
```
System.err: com.tns.NativeScriptException:
System.err: Error running script /data/user/0/br.com.mobile.client/files/internal/livesync.js
System.err: TypeError: Cannot read property 'entry' of undefined
System.err: File: "file:///data/data/br.com.mobile.client/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js, line: 36, column: 46
System.err: StackTrace:
System.err:     Frame: function:'reloadPage', file:'file:///data/data/br.com.mobile.client/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 36, column: 47
System.err:     Frame: function:'livesync', file:'file:///data/data/br.com.mobile.client/files/app/tns_modules/tns-core-modules/application/application-common.js', line: 58, column: 9
System.err:     Frame: function:'global.__onLiveSync', file:'file:///data/data/br.com.mobile.client/files/app/tns_modules/tns-core-modules/application/application.js', line: 137, column: 26
System.err:     Frame: function:'', file:'/data/user/0/br.com.mobile.client/files/internal/livesync.js', line: 2, column: 9
System.err:     at com.tns.Runtime.runScript(Native Method)
System.err:     at com.tns.Runtime.access$2200(Runtime.java:34)
System.err:     at com.tns.Runtime$2.run(Runtime.java:551)
System.err:     at android.os.Handler.handleCallback(Handler.java:815)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:104)
System.err:     at android.os.Looper.loop(Looper.java:207)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5683)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
```
### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- tns cli: 3.4.3
- tns-core-modules: 3.4.1
- Runtime(s): 3.4.2
- "nativescript-intl": "^3.0.0",
    "nativescript-ios-declarations": "^4.0.1",
    "nativescript-platform-css": "^1.6.5",
    "nativescript-statusbar": "^4.0.1",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-ui-autocomplete": "^3.5.0",
    "nativescript-ui-calendar": "^3.5.0",
    "nativescript-ui-chart": "^3.5.0",
    "nativescript-ui-dataform": "^3.5.0",
    "nativescript-ui-gauge": "^3.5.0",
    "nativescript-ui-listview": "^3.5.0",
    "nativescript-ui-sidedrawer": "^3.5.0",

### Please tell us how to recreate the issue in as much detail as possible.
I my application i only type tns run android and got to work on develop, save the code, and wait reload, ramomily throw the exception.

_Copied from original issue: NativeScript/nativescript-cli#3440_

**Comment by Fatme** [comment]
Seems to be related with this https://github.com/NativeScript/NativeScript/issues/5198

**Comment by NickIliev** [comment]
Closing as duplicate [to the linked issue](https://github.com/NativeScript/NativeScript/issues/5198)
