### ISSUE TITLE
TypeScript bindind for "ActionResult" doesn't exist

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/NativeScript#5523]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
**yes**

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
**YES**
### Which platform(s) does your issue occur on?
iOS/Android/Both
**Both**
### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)
**3.4.2**
### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

for dialogs there is typescript binding available for "LoginResult", "PromptResult" but not available for "ActionResult" and "ConfirmResult".

**Comment by tsonevn** [comment]
Hi, @bhavincb,
Can you provide more info about your case and about the functionality, which you are looking for?

**Comment by bhavincb** [comment]
hi @tsonevn,
`import { action, ActionOptions } from "ui/dialogs";`
what i'm saying is that there is no interface provided for the "ActionResult".
what i want is type checking for the result of the action dialog.
currently this is what we doing.
`action(options).then((result) => {})`

but there should be some interface provided for action result like
`action(options).then((result:ActionResult) => {})`

also there is no document available for information regarding what will be getting as a result on action dialog dissmiss.

**Comment by tsonevn** [comment]
Hi @bhavincb,
We reviewed your case, however, the return result from the action dialog will be a string value. The result will be the title of the Close button or some of the options set up in the array. Regarding that, there is no need to create custom `ActionResult`. To solve your case you could cast the result to a string.
```
import * as dialogs from "ui/dialogs";
dialogs.action("Your message", "Cancel button text", ["Option1", "Option2"]).then(result:string => {
    console.log("Dialog result: " + result);
    if(result == "Options1"){
        //Do action1
    }else if(result == "Option2"){
        //Do action2
    }
});
```

**Comment by bhavincb** [comment]
hii @tsonevn ,
thank you for your response, this will solve the problem for the time being.
but if there is some type checking class available for action results then it will be great to have it.
because there is already "LoginResult" and "PromptResult" interfaces available.

**Comment by tsonevn** [comment]
Hi, @bhavincb,
Indeed introducing such an interface will be useful if the returned arguments are more then a single string value. For now creating such an interface is not needed. In the future, if we change the type of the returned result, we will create an interface for this dialog type.
