### ISSUE TITLE
Image Src not accepting string object

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/NativeScript#5525]
i'm using telegram imagepicker library to select images which returns Array<string> as response.
here is code
```
openTelegramImagePicker(1).then((resp: TelegramPickerResponse) => {
        
          let fileUrl=resp.photos[0];
          // let src=new ImageSource();
          // src.fromFile(fileUrl).then(source=>{
          //   let image:any={};
          //   image.fileURL=fileUrl;
          //   image.imageSource=source;
          //   image.toURL=function(){
          //     return this.fileURL;
          //   }
          //   this.data.selectedGalleryImages.unshift(image);
            
          // });
          let image:any={};
          image.fileURL=fileUrl;
          image.toURL=function(){
            return this.fileURL;
          }
          // this.data.selectedGalleryImages.unshift(image);
          images.unshift(image);
          // resolve(image);
        
        resolve(image);
      }).catch((error)=>{
        reject(error);
      })
```
but when i use it in image like this `[src]="image.fileURL` gives error like below
```
JS: ERROR Error: java.lang.Exception: Failed resolving method setImageBitmap on
class org.nativescript.widgets.ImageView
JS:     com.tns.Runtime.resolveMethodOverload(Runtime.java:1049)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:957)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:941)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:933)
JS:     com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
JS:     android.os.Handler.handleCallback(Handler.java:739)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:148)
JS:     android.app.ActivityThread.main(ActivityThread.java:5441)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.ja
va:738)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
JS:     de.robv.android.xposed.XposedBridge.main(XposedBridge.java:163)
```

but when i use `let fileUrl=resp.photos[0].toString()`
and ten src binding `[src]="image.fileURL` it works as expected.

**Comment by bhavincb** [comment]
### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
3.4.2
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
3.4.0
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
3.4.2
- Plugin(s): (look for the version number in the `package.json` file of your
project)
"nativescript-telegram-image-picker": "^1.0.3",

### Please tell us how to recreate the issue in as much detail as possible.
i'm selecting images using Telegram image picker plugin and binding it's response to Image element's source attribute.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```
openTelegramImagePicker(1).then((resp: TelegramPickerResponse) => {
        
        let fileUrl=resp.photos[0];
        resolve(fileUrl);
      }).catch((error)=>{
        reject(error);
      })
```
```
export interface TelegramPickerResponse {
    photos: Array<string>,
    videos: Array<string>
}
```
<Image [src]="fileUrl"></Image>
```

Error i'm getting is described below
```
JS: ERROR Error: java.lang.Exception: Failed resolving method setImageBitmap on
class org.nativescript.widgets.ImageView
JS:     com.tns.Runtime.resolveMethodOverload(Runtime.java:1049)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:957)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:941)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:933)
JS:     com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
JS:     android.os.Handler.handleCallback(Handler.java:739)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:148)
JS:     android.app.ActivityThread.main(ActivityThread.java:5441)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.ja
va:738)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

**Comment by NickIliev** [comment]
@bhavincb the `src` accepts string - Playground demo [here](https://play.nativescript.org/?template=play-ng&id=Mmc6yI).

However, I've noticed that in your code the `fileUri` property is set in the callback and it seems that it is not initialized as observable property for your Angular component.

Try somethig like:
```
export class HomeComponent implements OnInit {
    fileUrl: string;

    openTelegramImagePicker(1).then((resp: TelegramPickerResponse) => {
        
        this.fileUrl = resp.photos[0];
        resolve(fileUrl);
      }).catch((error)=>{
        reject(error);
      })
}
```

**Comment by bhavincb** [comment]
hi @NickIliev ,
i will upload the sample project very soon.
