### ISSUE TITLE
Build android release apk without signing

### ISSUE THREAD

**Issue by ZuSe** [NativeScript/NativeScript#5526]
We are using Jenkins for building, signing and uploading our native android apps.
As the keyStore containing our signing key is saved within the jenkins credentials manager I would also like to use the same process for our NativeScript-App.
Unfortunately I am not able to build an unsigned release APK (as you can do for example in Android Studio) using the tns command.

**tns build android --release** requires the specification of the keystore (which might not be installed on the building machine)
I would therefore suggest to let it build an unsigned-release.apk file similar to **Android Studio / gradle assembleXXXRelease** command which can then be signed by whatever key signer is preferred.
In case the key-path parameter is specified it should use the existing process but not require it per se.

Best
Patrick

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3444
