### ISSUE TITLE
GridLayout spacing bug

### ISSUE THREAD

**Issue by waszqba** [NativeScript/NativeScript#5528]
## Please, provide the details below:
I have an issue with GridLayout using Angular on Android
I have a wide image as one of elements that has an unwanted kind of margin on top ('photo' one):
```
<GridLayout columns="*,*,*"
            rows="auto,auto,auto,auto,auto"
            width="100%">
    <Image row="0"
           col="0"
           colSpan="3"
           rowSpan="2"
           src="photo" ></Image>
    <Image rowSpan="2"
           row="1"
           col="1"
           src="otherPhoto}" ></Image>
//Some other stuff that doesn't change literally anything in the behavior...
```
but when I change it's `colSpan` to 1 or remove this property, it aligns perfectly with the upper border of the layout. If it helps, it's a component called in a `ListView`, but I don't think that would change anything
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.2
- Cross-platform modules: 3.4.1
- Runtime(s): 3.4.1 for both

### Please tell us how to recreate the issue in as much detail as possible.
Just try adding two overlapping images of `colSpan="2"`, one a row lower than the other.
this is the result with the grey bar being the border of an element above
![colspan 2](https://i.imgur.com/YS6IYKZ.jpg)
this is a desired result
![colspan 1](https://i.imgur.com/s3jrC7R.jpg)
I'm sorry but I can't really show any more of the app :/

**Comment by tsonevn** [comment]
Hi @waszqba,
The issue seems to be related to setting a different height for both images. 
Regarding that, I would suggest to set up specific height for the rows in the GridLayout or to replace the auto option with *(Star), which should allow the image to be appropriately measured.

option 1:
```
<GridLayout columns="*,*,*"
            rows="50,50,50,50,50"
            width="100%">
    <Image row="0"
           col="0"
           colSpan="3"
           rowSpan="2"
           src="photo" ></Image>
    <Image rowSpan="2"
           row="1"
           col="1"
           src="otherPhoto}" ></Image>
</GridLayout>
```
option 2:
```
<GridLayout columns="*,*,*"
            rows="*,*,*,*,*"
            width="100%">
    <Image row="0"
           col="0"
           colSpan="3"
           rowSpan="2"
           src="photo" ></Image>
    <Image rowSpan="2"
           row="1"
           col="1"
           src="otherPhoto}" ></Image>
</GridLayout>
```
However, if the issue persists, please send us sample project, which could be used for debugging.

**Comment by waszqba** [comment]
Well, setting a fixed height worked for portrait mode, landscape though is another story, but setting all rows to `*,*,*,*,*` didn't help much. I'll try to post a sample project that may show the problem I'm facing in the coming 48h, btw, is there any topic that could help me changing layout based on orientation dynamically?

**Comment by waszqba** [comment]
I am unable to create a playground project for now, however if you create a gridLayout object and make a wide image span across first two rows and across all the columns (the ratio is almost 27:9 I believe), you'll get the issue.

**Comment by tsonevn** [comment]
Hi @waszqba,
I rechecked the case, however, I am still unable to recreate the problem on my side. Regarding that, any sample project that could help us to reproduce the issue will be highly appreciated.

In the meantime, I would also suggest using the orientationChange event and to change the value of the rows and columns properties regarding the needs of the application. I am attaching sample project, which demonstrates this scenario.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1836616/Archive.zip)

**Comment by waszqba** [comment]
Thank you @tsonevn, I will surely try to handle rotation with provided sample, for now, we can consider this issue closed, but I'll post here if I manage to recreate the issue on playground
