### ISSUE TITLE
Refresh image with same src

### ISSUE THREAD

**Issue by bigradish** [NativeScript/NativeScript#5529]
If the src of an Image tag keep same, while the image file is replaced (for example., by a user's uploading his new avatar), Nativesript still diaplay the old image.
Is there a way to refresh the image without changing its src?
Thank you.

**Comment by NickIliev** [comment]
NativeScript will refresh the UI when working with observables, however, in your case your image is cached. As the developer is controlling the way the user will change its photo what you can do is to create a new image with new image name and pass its path as a source (e.g. [here](https://stackoverflow.com/a/47608209/4936697)) - instead of replacing the actual image file just create a new one and use it in your avatar photo binding.

Closing as a duplicate to [https://github.com/NativeScript/NativeScript/issues/5493](https://github.com/NativeScript/NativeScript/issues/5493)

**Comment by bigradish** [comment]
@NickIliev I know change the src can refresh the image, but my question is how to refresh the image without changing the src (i.e., refresh the image cache). Please answer my question!
The example you provide might work on Nativescript + Angular, but does not work on Nativesript + pure Javascript.
I think it might be better for you to provide a refresh method to clear the cache and show the new image.
Thank you.

**Comment by NickIliev** [comment]
@bigradish our developer's team is currently reworking some of the image implementation and the feature to reload the image when the file has changed should be included in our next official release (4.x.x) - stay tuned for updates regarding this matter.

**Comment by bigradish** [comment]
@NickIliev Good news. This is the right answer. Thank you very much. :)

**Comment by nmandyam** [comment]
Is this available now? I see a remove function, but that needs a "key" that there's no documentation about. Using the original image URL as the key (which is the logical thing to do, I would think) in the remove does nothing, nor does clear (tns V 4.2.4). What am I missing?

**Comment by JCFowler** [comment]
@NickIliev 
Hello, 
I'm also having this issue, I'm running 5.x.x now, but I still can't seem to solve this issue. 
And I can't seem to find anything online regarding this, other than this post. 
Thank you

**Comment by Eonfuzz** [comment]
Was this ever followed up on?

**Comment by CarissaHurt** [comment]
@JCFowler 
The useCache="false" worked really well for me. Thank you.

**Comment by michael-dots** [comment]
Having problem here as well. http headers says expiry 1 second, but never gets refreshed. tried useCache=false but that crashes in android emulator? No message or anything, app just closes.

**Comment by ziaKhan1995** [comment]
HTML:
<Image [useCache]="false" [src]="path" (tap)="pictureTap()"></Image>

TS:
showImage() { this.path = ''; setTimeout(() => { this.path = this.filePathHelper.getFilePath('profile-pic.jpeg'); }, 100); }

can someone explain this?
where is the function pictureTap() logic and what is this.filePathHelper ?
