### ISSUE TITLE
How to automatic sign in when app is launched(Question)

### ISSUE THREAD

**Issue by yclau** [NativeScript/NativeScript#5535]
## Please, provide the details below:
I trying to do auto login after success login and get token. Currently, i'm using plugin nativescript-localstorage to store the username and password then pass to server to validate when launched , isn't is a good practices or other way?

**Comment by tsonevn** [comment]
HI @yclau 
In your case, you could also use [Application setting](https://docs.nativescript.org/cookbook/application-settings) module for saving the values in the application.

For further questions please use our [forum ](https://discourse.nativescript.org/) or [StackOverflow thread](https://stackoverflow.com/questions/tagged/nativescript). This repository is used only for feature request and bug reporting.
