### ISSUE TITLE
css color and backkground clolor doesn't apply on NavigationButton.

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/NativeScript#5536]
i am trying to apply css color and background color to NavigationButton but it is not working.
here is playground link https://play.nativescript.org/?template=play-ng&id=FpaWzb&v=26
i had checked on Android.
i'm using nativescript with Angular

**Comment by NickIliev** [comment]
@bhavincb I can confirm that indeed, at this very moment we can not set styles to NavigationButton via CSS.

As a workaround, you can still set the color of Android navigation button by accessing the native API.

For example (Angular)

in your component
```
onActionBarLoadedLoaded(args) { 
    if (isAndroid) { 
        let androidToolbar = this.page.actionBar.nativeView;
        androidToolbar.getNavigationIcon().setColorFilter(android.graphics.Color.parseColor("#ed5d40"), (<any>android.graphics).PorterDuff.Mode.SRC_ATOP);
    }
}
```

HTML
```
<ActionBar class="action-bar" (loaded)="onLoaded($event)">
	<ActionItem>
		<Label (tap)="goToNext()" text="Next"></Label>
	</ActionItem>
	<NavigationButton android.systemIcon="ic_menu_back" text="Back" (tap)="goBack()"></NavigationButton>
</ActionBar>
```
Demo Playgroound demonstrating the abvove can be found [here](https://play.nativescript.org/?template=play-ng&id=FpaWzb&v=30)

**Comment by bhavincb** [comment]
hii @NickIliev 
what about using custom action bar with icon font to achieve that. i had searched entire nativescript angular documentation. but unable to find anything related to that.

**Comment by NickIliev** [comment]
@bhavincb while we can set icon fonts on our custom ActionItems this is still not possible for the NavigationButton.

**Comment by bhavincb** [comment]
hii @NickIliev ,
also there is document available in Nativescript core for custom ActionBar [https://docs.nativescript.org/ui/action-bar#using-a-custom-title-view](url) but there is no document available on custom action bar in Nativescript for angular.
example like above should be added to [https://docs.nativescript.org/angular/code-samples/ui/action-bar](url)

**Comment by NickIliev** [comment]
@bhavincb thanks for the notice about the missing Angular example.
We are currently working on improving JavaScript examples but will add missing examples in Angular as well. Meanwhile, if you want, you can contribute by adding the example yourself - the Angular examples are actually coming from [this demo application](https://github.com/NativeScript/nativescript-sdk-examples-ng) a-- all PRs are welcomed!

The basic contribute guide can be found [here](https://www.nativescript.org/contribute)
