### ISSUE TITLE
font-size attributes affect different icon fonts differently

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/NativeScript#5538]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes
### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
i'm using  font-awesome and ionic fonts in my projects, when applying same font size one icons seems bigger than other one.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
ionic fonts 2.0

### Please tell us how to recreate the issue in as much detail as possible.
here is playground link [https://play.nativescript.org/?template=play-ng&id=mItQD5&v=3](url)

**Comment by NickIliev** [comment]
@bhavincb the template link provided is not working. Please revise the template or send us archive (without node_modules/platforms folders) or GitHub link to the test project so we could investigate locally.

**Comment by bhavincb** [comment]
hii @NickIliev ,
i had updated link. [https://play.nativescript.org/?template=play-ng&id=mItQD5&v=3](url).
please check it.

**Comment by NickIliev** [comment]
@bhavincb this seems to be related to the specific `ionic fonts` font as all other icon fonts are rendered as expected and only the ionic one is smaller than expected. 
[Here is a Playground demo ](https://play.nativescript.org/?template=play-ng&id=mItQD5&v=4)showing Icomoon, Ionic fonts, and FontAwesome next to each other.
