### ISSUE TITLE
http service is not working in iOS when invoked from worker thread

### ISSUE THREAD

**Issue by slsumathi** [NativeScript/NativeScript#5540]
Hi,

   I iOS build the http service is not working, throwing the below error.

    **TypeError: global.moduleMerge is not a function. (In 'global.moduleMerge(httpRequest, exports)', 'global.moduleMerge' is undefined)**

   I noticed this problem when we invoke http service in a worker thread.
   I guess the problem exists even when we run in main thread.

   The fix I did for this problem is.. include the below line in 
   node_modules/tns-core-modules/http/http.js    at the beginning of the file

    require('globals');

**Comment by vakrilov** [comment]
The `global.moduleMerge` method is not needed any more. We prefer to use typescript `export` syntax instead. So instead of 
```
import * as httpRequest from "./http-request";
global.moduleMerge(httpRequest, exports);
```
You can do:
```
import * as httpRequest from "./http-request";
export * "./http-request";
```
The result should be the same. However, the code looks cleaner and there is no dependency in the `global` module.

**Comment by slsumathi** [comment]
Vakrilov,

   When we added tns-core-modules in node_modules we got http.js file not ts file.
   Thanks for the respective fix in typescript.
   BTW this fix needs to go into tns-core-modules.
   Who will be doing that ?

**Comment by vakrilov** [comment]
The `http.js` is generated from the `http.ts`. So the typescript file *is* the correct place for fix.
Once merged, the fix will come out in the `@next` builds and in the next official release
