### ISSUE TITLE
[Modal Page][iOS] modalpage showing in fullscreen.

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#5542]
_From @kamlekar on March 15, 2018 11:20_

Hi,

I am using the modal page to show a custom pop-up. In Android its working fine but in iOS, it's stretching (showing in fullscreen). As per the documentation, this is `by design in iPhone`. Is there any way to get rid of this behavior? or any alternative to show the pop-up?

Also, in iPad, this modal stretch abnormally. Please check the below screenshot.

![image](https://user-images.githubusercontent.com/2201186/37460315-e163d38c-2870-11e8-971b-82286de48ada.png)

Thanks.

_Copied from original issue: NativeScript/nativescript-cli#3462_

**Comment by NickIliev** [comment]
@alg `by design on iOS` means that this is the way the modal pages are working on native iOS. so you could not overcome the native limitations. 

As a possible workaround, you could replace the modal page with a custom layout which you can show/hide depending on some custom implementation (e.g. using `visibility`)

**Comment by kamlekar** [comment]
@NickIliev Ok thanks. Is there any possibility that without adding even a single line in xml file (only xml files related to the pages), I can create this custom modal layout?

**Comment by NickIliev** [comment]
@kamlekar yes you can create dynamically create a layout from the code-behind.
For example something like this
```
let label = new Label();
label.text = "some text";

let stack = new StackLayout();
stack.width = 200;
stack.height = 400;
// set styles here..

stack.addChild(label);
```

And then add the layout to some container element. You can also control its visibility through the code-behind file. For more complex scenarios, we can c[reate custom components](https://moduscreate.com/blog/custom-components-in-nativescript/) via code-behind and reuse them in multiple places using the builder for NativeScript Core applications or using their selectors for Angular based apps

**Comment by kamlekar** [comment]
Yay, I got that but I would like to create a component which will replicate exactly as showModal, means I won't place any code in XML, I don't want to control it through visibility. I directly want to add a component to 'page' itself. on pageLoaded

**Comment by NickIliev** [comment]
@kamlekar we can add/remove views entirely through the code-behind files via different layout methods.
For example, if we have [`StackLayout`](https://docs.nativescript.org/api-reference/classes/_ui_layouts_stack_layout_.stacklayout) as our layout container we can add views with [`addChild`](https://docs.nativescript.org/api-reference/classes/_ui_layouts_stack_layout_.stacklayout#addchild) or [`insertChild`](https://docs.nativescript.org/api-reference/classes/_ui_layouts_stack_layout_.stacklayout#insertchild) methods.
The `Page` itself has a [`content`](https://docs.nativescript.org/api-reference/classes/_ui_page_.page#content) property which allows changing the whole content of the current page.

Using the above methods you can entirely add and remove layouts in your current Page.

**Comment by kamlekar** [comment]
@NickIliev Thanks. Your suggestion helped a lot.
