### ISSUE TITLE
Resources$NotFoundException On Google Robo Test

### ISSUE THREAD

**Issue by rakeshgirase** [NativeScript/NativeScript#5549]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes
### Tell us about the problem
One out of 10 devices which were under test encountered following exception and I felt like not leaving it this time as I got a logs of the same. 
[logcat.txt](https://github.com/NativeScript/NativeScript/files/1817140/logcat.txt)
Though there is nothing specific, I have attached the video of the test which gave this exception:
Video: https://drive.google.com/open?id=1uiGHhPdT8LhQ83HMlczgrY-w5FRFkn5n 
Following is stacktrace:
```
03-14 23:11:59.425: I/Robo(14384): android.content.res.Resources$NotFoundException: Resource ID #0xffffffec
03-14 23:11:59.425: I/Robo(14384): 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:255)
03-14 23:11:59.425: I/Robo(14384): 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2187)
03-14 23:11:59.425: I/Robo(14384): 	at android.content.res.Resources.getAnimation(Resources.java:1202)
03-14 23:11:59.425: I/Robo(14384): 	at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:127)
03-14 23:11:59.425: I/Robo(14384): 	at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:108)
03-14 23:11:59.425: I/Robo(14384): 	at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:93)
03-14 23:11:59.425: I/Robo(14384): 	at android.app.FragmentManagerImpl.loadAnimator(FragmentManager.java:828)
03-14 23:11:59.425: I/Robo(14384): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1072)
03-14 23:11:59.425: I/Robo(14384): 	at android.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1283)
03-14 23:11:59.425: I/Robo(14384): 	at android.app.BackStackRecord.run(BackStackRecord.java:766)
03-14 23:11:59.425: I/Robo(14384): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1585)
03-14 23:11:59.425: I/Robo(14384): 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:484)
03-14 23:11:59.425: I/Robo(14384): 	at android.os.Handler.handleCallback(Handler.java:755)
03-14 23:11:59.425: I/Robo(14384): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-14 23:11:59.425: I/Robo(14384): 	at android.support.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:148)
03-14 23:11:59.425: I/Robo(14384): 	at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:465)
```
### Which platform(s) does your issue occur on?
Android
![image](https://user-images.githubusercontent.com/16098644/37492565-bb8e533e-2899-11e8-8653-3407a89c7065.png)

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)
The complete project can be found at https://github.com/rakeshgirase/QSB.

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
I understand that it is an issue which is difficult to pin point and fix.. Its strange that code works just fine on 9 out of 10 devices. However, if at all code is required then you can find it https://github.com/rakeshgirase/QSB

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#974
