### ISSUE TITLE
Radio button control

### ISSUE THREAD

**Issue by cime** [NativeScript/NativeScript#555]
Please add radio button widget.

Android
 - http://developer.android.com/guide/topics/ui/controls/radiobutton.html

iOS example
 - http://mobisoftinfotech.com/resources/blog/iphone/iphone-uibutton-tutorial-radio-buttons/
 - https://github.com/onegray/RadioButton-ios

**Comment by lscown** [comment]
It'd also be great to see a checkbox widget as well.  :+1:

**Comment by stonecourier** [comment]
Here is a post how I made my own. Hopefully it may help you.

http://stonecourier.blogspot.com.au/2015/08/making-replacement-checkboxradiobutton.html

**Comment by enchev** [comment]
You can use my example from here:
https://github.com/NativeScript/NativeScript/issues/1769#issuecomment-198268655

**Comment by mnahkies** [comment]
@enchev IMHO using switches seems like a workaround rather than a solution to the need for a radio buttons control. 

Yes they can be emulated / implemented relatively easily using labels and icons, but I would still have expected this to be a core UI control.

Is there any reason not to implement this as a core control? Same question for check boxes.

**Comment by enchev** [comment]
Usually we create cross-platform wrappers for standard UI components for both Android and iOS, however there is no such component for iOS. You can still create your own plugin using some of the [cocoapods available out there](https://cocoapods.org/?q=radio)

**Comment by markhatchell** [comment]
There is a radio button widget we have started that works for android right now. Tunaweza/nativescript-radiobutton

**Comment by taivna** [comment]
@markhatchell can you provide an example for your radio button plugin?

**Comment by romandragan** [comment]
https://market.nativescript.org/plugins/nativescript-checkbox
