### ISSUE TITLE
Insert child before and after

### ISSUE THREAD

**Issue by bigradish** [NativeScript/NativeScript#5550]
The addChild method appends a child view to the end of the container view. I think if methods for inserting a child view before and after another view can be provided, the manipulating should be much more convenient. Thank you.

**Comment by NickIliev** [comment]
@bigradish you can use [`insertChild](https://docs.nativescript.org/api-reference/classes/_ui_layouts_stack_layout_.stacklayout#insertchild)` method to provide the view and the specific index.

**Comment by bigradish** [comment]
@NickIliev Thank you so much. :)
