### ISSUE TITLE
ngIf alternative for vanilla JS

### ISSUE THREAD

**Issue by surdu** [NativeScript/NativeScript#5552]
My goal here is to have an custom component with a `loaded` event attached to it, and that loaded event should be triggered every time the component is shown.

I've written a [very simplified example](https://play.nativescript.org/?template=play-ng&id=nrac48&v=3) in the Playground, and it seems that `ngif` already does this.

The problem is that I didn't find anything similar for vanilla JS, and I was wondering if I'm missing something.

**Comment by NickIliev** [comment]
@surdu you can use `visibility` with ternary expression to hide/show the wanted layout.
```
visibility="{{ isItemVisible ? 'visible' : 'collapsed' }}" 
```
[Playground demo](https://play.nativescript.org/?template=play-js&id=RjmZSl)

**Comment by surdu** [comment]
For whomever needs something similar, I wrote a small component that does just this: https://gist.github.com/surdu/57ad41764c714c86497b92e1b4cde04e
