### ISSUE TITLE
If the value of a binding changes to -1, it is not displayed in a Label

### ISSUE THREAD

**Issue by shiv19** [NativeScript/NativeScript#5559]
https://github.com/NativeScript/NativeScript/blob/8248d8a8b93527cd81d3e0d3bc80eebecce6f1df/tns-core-modules/ui/text-base/text-base.android.ts#L104

`<Label text="{{ value }}" />`

If we have a label like this, and the value of the `value` variable changes to -1 then it doesn't display on the label. Unless it is stringified.

https://play.nativescript.org/?template=play-js&id=2XPVRh

(same on iOS)

**Comment by tsonevn** [comment]
Hi @shiv19,
Thank you for contacting us,
I reviewed your case and was able to recreate this issue. You could keep track on it for further info.
