### ISSUE TITLE
ActionBar - issues in styling and help required in re-creating a custom one.

### ISSUE THREAD

**Issue by venkateshsj** [NativeScript/NativeScript#5560]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

## Please, provide the details below:
The provision to style the ActionBar and its contents is a widely discussed issue with less flexibility, mainly due to OS limitations. Well, what I am trying to achieve is a workaround.

Please refer the following image,
![2018-03-18-20-41-00](https://user-images.githubusercontent.com/7588513/37567874-3d25b9c2-2af3-11e8-806b-5c7c66478783.jpg)

The image contains 2 ActionBars as viewed on OnePlus3 (Oxygen OS 5.0.2), Android 8.0:
1. Actual ActionBar
2. Recreated using WrapLayout and Labels.

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yeah.

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

#Issue with Actual ActionBar:
1. I cannot apply icon font in NavigationButton
2. If you see the image, the menu icon looks very small
3. ActionBar.TItleview does not consume remaining width, hence it appears only in the center
4. Icons cannot be displayed in the Popup menu

#Help required in re-creating the ActionBar:
1. How to re-create the popup menu as in ActionBar?
2. Is it possible to display this custom layout in ActionBar?

### Which platform(s) does your issue occur on?
Currently Android, not checked on iOS yet.

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

nativescript - 3.4.3 - Up to date
tns-core-modules - 3.4.1 - Up to date
tns-android - 3.4.2 - Up to date
tns-ios - 3.4.1 - Not installed

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

https://play.nativescript.org/?template=play-js&id=yYd9bV&v=8

I tried my best to reproduce the issue in the above URL, but somehow the menu.png uploaded doesn't display in the ActionBar, also the icon font for menu does not appear, hence displayed the 3-dot icon.

**Comment by tsonevn** [comment]
Hi @venkateshsj,
Thank you for the sample project,

Regarding "I cannot apply icon font in NavigationButton":

In Android, you cannot set text inside the navigation button. In this case, if you set up the text property with custom icon font in Android, nothing will be displayed.  You can only use the icon property to set an image in Android. This also is mentioned in the documentation here.


Regarding "If you see the image, the menu icon looks very small":
While displaying image from the resources in the ActionBar, the image will be measured based on the screen resolution. Currently, the image size in the ActionItem and NavigationButton, could not be changed.


Regarding "ActionBar.TItleview does not consume remaining width, hence it appears only in the center":

The ActionItems and the NavigationButton do not support setting up the width, and the ActionBar.titleView will take only the needed width to display the image and the title.

Regarding "Icons cannot be displayed in the Popup menu":

Using icons in the ActionBar items in the popup menu seems to not be supported in NativeScirpt application as well as in [native Android app](https://stackoverflow.com/a/39026923/6133327). To achieve this I would suggest using the below-described scenario for creating custom ActionBar and popup menu




In your case, I would suggest creating [custom ActionBar](https://docs.nativescript.org/ui/action-bar#using-a-custom-title-view) and to create the needed Layout structure with the required buttons and title view. For creating a custom popup menu, you could try using [nativescript-drop-down](https://www.npmjs.com/package/nativescript-drop-down) plugin.


Hope this helps.

**Comment by venkateshsj** [comment]
**@tsonevn**, thank you so much for your reply!

I had actually tried displaying the custom layout inside ActionBar.titleView, but the icon font simply does not display. Hence I eventually hid the actual ActionBar and displayed the custom layout as an ActionBar. 

Another reason for hiding actual ActionBar, the ActionBar.titleView is always center-aligned whereas I wanted it to be aligned next to the NavigationButton, tried setting horizontalAlignment and/or left, but nothing works.

As suggested, I will try the dropdown plugin to re-create the popup menu.

It would have been so great to customize the ActionBar as required instead of creating a custom ActionBar, any plans this might be possible in the near future?

**Comment by tsonevn** [comment]
Hi @venkateshsj,
I would suggest opening a new feature request and to describe, what you would like to add as further styling to the ActionBar component. We will review them and will check which of them could be added as a functionality.
