### ISSUE TITLE
How to insert image with pure javascript?

### ISSUE THREAD

**Issue by bigradish** [NativeScript/NativeScript#5561]
I try to insert local images to a StackLayout with **pure javascript**. My code is something like follows:

```
const { Image } = require('ui/image')
const imageSource = require('image-source')
insertImage(containerView) { // containerView is the StackLayout view
  let img = new Image()
  img.src = imageSource.fromFile(fileUri)
// fileUri is the file path of a local image. I also tried img.imageSource = imageSource.fromFile(fileUri) 
  containerView.insertChild(img, 0)
}
```

But above code does not work.
Please don't tell me this can be done via XML + data binding. I need a pure javascript solution.
Thank you very much.

**Comment by NickIliev** [comment]
@bigradish the snippet looks fine - look for the following possible issues:
- make sure your `fileUri` exists and that you are using a file located within the application. 
- make sure that 'containerView' exists and is referenced properly.

Playground demo using the above code can be found [here](https://play.nativescript.org/?template=play-js&id=RKTMHd&v=2).

**Comment by bigradish** [comment]
@NickIliev Thanks for your checking and answers.

- fileUri is correct in the XML + data binding mode, but I don't know if it can be used samely in imageSource.fromFile.

- containerView is correct, for I can insert a TextView into it.


I can't open your playground page. Could you paste those code to this page?
Thank you very much.

**Comment by bigradish** [comment]
@NickIliev I found the code works on a static page, but the image is not shown when the insertion happens in page navigating. For example, inserting an image in the page's onNavigatingTo callback function, or when going back from using the ImagePicker plugin.
Thank you.

**Comment by bigradish** [comment]
@NickIliev How to resolve this issue?
Thank you.

**Comment by NickIliev** [comment]
@bigradish please provide a sample project illustrating the described scenario - either via GitHub link or by directly posting an archive here (without `node_modules` and `platforms`) - this way I would be able to reproduce the issue and investigate further the causes behind it.
