### ISSUE TITLE
Broken emails

### ISSUE THREAD

**Issue by atilkan** [NativeScript/NativeScript#5565]
![img_3815](https://user-images.githubusercontent.com/1254613/37629707-5e904196-2bf1-11e8-9931-1f3ac76c6d6b.PNG)
I know this is not the place but where can be. Anyways. Please fix   emails for iphone 5 screens.

**Comment by tsonevn** [comment]
Hi @atilkan,
Could you provide more info about the issue and if this is the email related to the SideKick registration?

**Comment by pedromorgan** [comment]
I seen similar on android recent, there was no width, but hey..

**Comment by atilkan** [comment]
@tsonevn it is about nativescript emails. Including sidekick.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/sidekick-feedback#152
