### ISSUE TITLE
ListView mixing component data in angular

### ISSUE THREAD

**Issue by waszqba** [NativeScript/NativeScript#5567]
## Please, provide the details below:
When I put a component as a list item, the listView mixes data, when I change a piece of data influencing appearance of the component instance, the change is visible on further instances taking place of the one that has actually changed it's data.

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
yes

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.3
- Cross-platform modules: 3.4.1
- Runtime(s): 3.4.1 for both
- Angular: 5.2.0

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
home.component.html:
```
<ListView [items]="items" (itemTap)="onItemTap($event)">
    <ng-template let-item="item" let-i="index" let-odd="odd" let-even="even">
        <my-component [item]="item"></my-component>
    </ng-template>
</ListView>
```
the .ts file makes an API request onInit, ant that's all there's to it

`my-component` is in a separate module if it helps. The module imports NativescriptCommonModule and NativeScriptModule and declares its components, nothing more.

`my-component.conponent.ts` contains `moduleId: module.id` in its declaration has one input for the item and 3 public variables, one of which is boolean declared to `true` and it's broken by ListView, as if I set it to false on first few instances, it remains false on any further loaded instance.

`my-component.component.html` contains two sub-component calls with some data passed to it. Those sub-components have their own independent data and this data also gets copied from previous instance of my-component that had taken this place.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1245
