### ISSUE TITLE
Someone has managed to import the Web3Js library to a Navitvescript project (angular or Vue)

### ISSUE THREAD

**Issue by camilo5972** [NativeScript/NativeScript#5569]
Only with importing the library does the application stop working.

I tried to directly add the Javascript file, but tells me that it does not recognize the variable "self"

**Comment by NickIliev** [comment]
@camilo5972 I guess we are talking about [this](https://web3js.readthedocs.io/en/1.0/web3.html#version) - it seems the library is depending on some DOM specific code and is not compatible with NativeScript.
I guess one possible solution would be to create a plugin that wraps the needed code.
