### ISSUE TITLE
access dom bby class/selector/attribute

### ISSUE THREAD

**Issue by peppeg85** [NativeScript/NativeScript#5570]
hello, is there a way to select multiple objects with the same attribute? like col="0", or row="0" due the fact that in nativescript there isnt get object by class

thank you

**Comment by NickIliev** [comment]
@peppeg85 there is no out-of-the-box functionality that allows you to select multiple opbjects by attribute name. However, you can use the [nativescript-dom](https://github.com/NathanaelA/nativescript-dom) plugin to select elements by class name or tag name
