### ISSUE TITLE
ios publish error: invalid binary plist

### ISSUE THREAD

**Issue by dbay920** [NativeScript/NativeScript#5571]
### Tell us about the problem
- ran `tns build ios --release --for-device`
- ran `tns publish ios --ipa <path to my ipa file>`
- After I enter my Apple ID and PW I get folowing error: 
`Invalid binary plist. Expected 'bplist' at offset 0`

github repo [here](https://github.com/dbay920/phn-app)

### Which platform(s) does your issue occur on?
macOS Sierra

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.2.1
- Cross-platform modules: 3.4.1
- Runtime(s): 3.2.0

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3479
