### ISSUE TITLE
application.displayedEvent is broken on iOS

### ISSUE THREAD

**Issue by sserdyuk** [NativeScript/NativeScript#5572]
I had some initialization logic on `displayedEvent` and it stopped working after I upgraded NS to latest and greatest. The event doesn't fire anymore. The `resumeEvent` does fire, so I was able to move my logic there. It's just odd that this got broken somewhere between 3.4.0 and now.

```
application.on(application.displayedEvent, function (args: application.ApplicationEventData) {
    console.log("Display never fires: " + args.ios);
});

application.on(application.resumeEvent, function (args: application.ApplicationEventData) {
    console.log("Resume fired: " + args.ios);
});
```

You can test the bug and see the code in the app.ts in the example project: https://github.com/sserdyuk/ns-bug-displayevent-ios.git 

```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 3.4.3           │ 3.4.3          │ Up to date    │
│ tns-core-modules │ 3.4.1           │ 3.4.1          │ Up to date    │
│ tns-android      │                 │ 3.4.2          │ Not installed │
│ tns-ios          │ 3.4.1           │ 3.4.1          │ Up to date    │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```

**Comment by vakrilov** [comment]
It seems that the event is only fired when tracing is enbaled(). [Here](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/application/application.ios.ts#L123-L128) is the corresponding place in the code.

It is a bug, as you would not enable tracing in production. This means that you would not be able to use this event.
