### ISSUE TITLE
Using with Nativescript Javascript

### ISSUE THREAD

**Issue by WS20** [NativeScript/NativeScript#5574]
Dear all,

I hope someone is following up still.
I want to have this working in NS: JavaScript, I just get an error claim that materialripplelayout is not a constructor.

After I install the plug-in, I have this in XML file:
`xmlns:RL="nativescript-ripple"`

then;
`
<RL:Ripple rippleColor="#d50000">
<Label position="right" text="&#xf17b;" style="font-family: FontAwesome;font-size:22px; "/>
</RL:Ripple>`

what do I miss ...

Best

**Comment by tsonevn** [comment]
Hi @WS20,
You could review the sample application in the plugin's repository, where it is demonstrated how to use it in [non-Angular project](https://github.com/bradmartin/nativescript-ripple/blob/master/demo/app/main-page.xml#L1-L34). 
If you have a problem with its usage, please use our NativeScirpt [forum](https://discourse.nativescript.org/) or open new issue in the plugin's [repo](https://github.com/bradmartin/nativescript-ripple).

This repository is used only for bug reporting and feature requests related to tns-core-modules.
