### ISSUE TITLE
how to make a overlay screen in Nativescript

### ISSUE THREAD

**Issue by priyangamani** [NativeScript/NativeScript#5575]
I trying to design a overlay screen in nativescript. I need a half transparent screen with a full transparent that shows what the user [needs](url) to do.Is there any default plugin is available or layouts.

![6dd39aed5ed73e1b9754b7a05019be11](https://user-images.githubusercontent.com/6038069/37764689-49cf4a46-2dfd-11e8-9b72-01187233c42e.jpg)

Like this...Any idea?

**Comment by tsonevn** [comment]
Hi @priyangamani,
In your case you could use [nativescript-coachmarks](https://www.npmjs.com/package/nativescript-coachmarks), which seems to provide the functionality, you need.
Also for any further questions, please use our [forum](https://discourse.nativescript.org/) or StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript). This repository is used only for bug reports and feature requests.
