### ISSUE TITLE
TextView - pressing return/enter does not go to new line

### ISSUE THREAD

**Issue by venkateshsj** [NativeScript/NativeScript#5579]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
I think this issue is similar to what I am facing - 
https://github.com/NativeScript/NativeScript/issues/5121

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both - currently checking on Android only

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

nativescript - 3.4.3 - Up to date
tns-core-modules - 3.4.1 - Up to date
tns-android - 3.4.2 - Up to date
tns-ios - 3.4.1 - Not installed

"dependencies": {
"nativescript-animatecss": "1.0.0",
"nativescript-appversion": "1.4.1",
"nativescript-cardview": "2.0.5",
"nativescript-dom": "2.0.0",
"nativescript-exit": "1.0.1",
"nativescript-fancyalert": "1.2.0",
"nativescript-floatingactionbutton": "4.1.3",
"nativescript-globalevents": "1.2.1",
"nativescript-loading-indicator": "2.4.0",
"nativescript-pro-ui": "3.4.1",
"nativescript-snackbar": "2.0.1",
"nativescript-textinputlayout": "2.0.2",
"nativescript-theme-core": "~1.0.4",
"nativescript-toasts": "1.0.3",
"tns-core-modules": "~3.4.0"
},
"devDependencies": {
"babel-traverse": "6.4.5",
"babel-types": "6.4.5",
"babylon": "6.4.5",
"copy-webpack-plugin": "~4.3.0",
"css-loader": "~0.28.7",
"extract-text-webpack-plugin": "~3.0.2",
"lazy": "1.0.11",
"nativescript-dev-webpack": "~0.9.1",
"nativescript-worker-loader": "~0.8.1",
"raw-loader": "~0.5.1",
"resolve-url-loader": "~2.2.1",
"uglifyjs-webpack-plugin": "~1.1.6",
"webpack": "~3.10.0",
"webpack-bundle-analyzer": "^2.9.1",
"webpack-sources": "~1.1.0"
}
}

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

https://play.nativescript.org/?template=play-tsc&id=unGzmK

Add a TextView, enter some text and press the enter/return key on the soft keyboard, the cursor does not go to the next line, it remains where it was. I don't know if any plugin is causing this issue or not. I have English (UK) and 'SwiftKey' keyboard installed as default keyboard. Testing on an actual device -  OnePlus 3 with Android 8.0 (OxygenOS 5.0.2).

**Comment by NickIliev** [comment]
@venkateshsj the issue was a known bug reported [here](https://github.com/NativeScript/NativeScript/issues/5121).

The fix is already included in the `next` version of  `tns-core-modules` and will be part of the upcoming official release. Meanwhile, for testing purposes, you can test the fix with installing `tns-core-modules@next` (keep in mind that you would also need nativescript@next to work with the next modules)

**Comment by venkateshsj** [comment]
Wow! Didn't expect such a prompt reply! Thanks a lot!

Any idea when is the next release containing these fixes expected to take place? Also, is it advisable to publish an app to PlayStore using the `next` version of `tns-core-modules`?
