### ISSUE TITLE
Error: more than one library with package name 'com.google.android.gms.license

### ISSUE THREAD

**Issue by priyangamani** [NativeScript/NativeScript#5580]
How to resolve the google play service issues??

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0F1F2F3F4F5F6F7F8F9F10F11F12F13F14F15F16F17F18F19F20F21F22DebugResources'.
> Error: more than one library with package name 'com.google.android.gms.license'

**Comment by NickIliev** [comment]
@priyangamani please provide additional info required by [the open new issue template](https://github.com/NativeScript/NativeScript/issues/new) - including the required fields
```
Please provide the following version numbers that your issue occurs with:
CLI: (run tns --version to fetch it)
Cross-platform modules: (check the 'version' attribute in the
node_modules/tns-core-modules/package.json file in your project)
Runtime(s): (look for the "tns-android" and "tns-ios" properties in the
package.json file of your project)
Plugin(s): (look for the version number in the package.json file of your
project)
```

**Comment by priyangamani** [comment]
Required file  is as below
Package.json
 "dependencies": {
    "nativescript-appversion": "^1.3.3",
    "nativescript-audio": "^4.0.3",
    "nativescript-azure-mobile-apps": "^0.5.2",
    "nativescript-barcodescanner": "^2.6.0",
    "nativescript-camera": "^3.0.0",
    "nativescript-carousel": "^2.3.1",
    "nativescript-clipboard": "^1.1.5",
    "nativescript-collapsing-header": "^2.0.0",
    "nativescript-dialog": "0.1.0",
    "nativescript-drop-down": "^3.2.0",
    "nativescript-effects": "^0.3.0",
    "nativescript-eghl": "0.0.1",
    "nativescript-fancyalert": "^1.1.2",
    "nativescript-feedback": "^1.0.5",
    "nativescript-filterable-listpicker": "^1.0.5",
    "nativescript-floatingactionbutton": "^2.2.7",
    "nativescript-google-analytics": "^0.4.1",
    "nativescript-https": "^1.0.1",
    "nativescript-imagecropper": "0.0.7",
    "nativescript-imagepicker": "^3.0.0",
    "nativescript-intl": "0.0.6",
    "nativescript-iqkeyboardmanager": "^1.0.1",
    "nativescript-loading-indicator": "^2.3.2",
    "nativescript-numeric-keyboard": "^3.0.2",
    "nativescript-onesignal": "^1.0.7",
    "nativescript-permissions": "^1.2.3",
    "nativescript-pro-ui": "^3.2.0",
    "nativescript-pulltorefresh": "^1.1.9",
    "nativescript-push-notifications": "0.0.19",
    "nativescript-screen-orientation": "^2.0.0",
    "nativescript-secure-storage": "^2.2.0",
    "nativescript-slides": "^2.2.2",
    "nativescript-snackbar": "^1.1.7",
    "nativescript-social-share": "^1.3.1",
    "nativescript-sound": "^1.0.4",
    "nativescript-status-bar": "^1.1.1",
    "nativescript-theme-core": "^0.1.2",
    "nativescript-toast": "^1.4.6",
    "nativescript-toolbox": "^1.49.1",
    "nativescript-tooltip": "^2.1.2",
    "nativescript-urlhandler": "^1.1.1",
    "nativescript-vibrate": "^1.1.2",
    "tns-core-modules": "^3.3.0"
  },
  "devDependencies": {
    "babel-traverse": "6.16.0",
    "babel-types": "6.16.0",
    "babylon": "6.12.0",
    "lazy": "1.0.11",
    "shelljs": "^0.5.3"
  }
app.gradle File
![screen shot 2018-03-23 at 5 09 19 pm](https://user-images.githubusercontent.com/6038069/37821088-9d5c337a-2ebd-11e8-8f44-b88ebc4985ec.png)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#983
