### ISSUE TITLE
setAttribute in nativescript

### ISSUE THREAD

**Issue by peppeg85** [NativeScript/NativeScript#5582]
hello, sorry for the stupid question, but in the cdocumentation i can not find the answer, how i set the attribute/property isEnabled via javascript in nativescript?
i try with 

obj.getViewById('11').setAttribute('isEnabled',false)

but i have that setAttribute is not a function.....thank you

**Comment by peppeg85** [comment]
okm if someone need it....just ".attributename=value"
sorry

**Comment by pedromorgan** [comment]
What are u trying to `setAttribute()` upon,
in ns, there is no "DOM", instead u get an xml and it renders in js ??

What are u trying to achieve ?

**Comment by peppeg85** [comment]
i'm trying to set the checkbox attribute "isEnabled" to false or true by checking another checkbox, i achieved it by obj.getViewById('id').isEnabled=args.object.checked where args.object is the checkbox 'tapped'

**Comment by pedromorgan** [comment]
sorry am a newbie, like you before....
