### ISSUE TITLE
How to use different app id and build configuration for debug and release

### ISSUE THREAD

**Issue by smartsanja2013** [NativeScript/NativeScript#5585]
I have few questions about how to create multiple build configurations for debug(UAT) and release(PROD)

I could found only this http://docs.telerik.com/platform/appbuilder/nativescript/build-configurations/application-settings article for similar topic, but there it used AppBuilder which is currently I am not using.

These are the things I am currently struggling to do.

How to use different appId for UAT and PROD environment. Can I define it in package.json?

I want to use different web server urls for those environments. How can I define it?

Can I create two Xcode schemes as UAT and PROD and Android build flavors from nativescript project. (I know we can easily do this in native ios and android manulaly , But if I remove the platform, All the settings should be re-do)

**Comment by Plamen5kov** [comment]
Hi @smartsanja2013,
_For Android:_
With {N} 4.0 release, you'll be able to use flavors specified in `app/App_Resources/Android/app.gradle` just as you can do in native.
You can see an example [here](https://github.com/Plamen5kov/flavorsproject). Feel free to clone it, tinker with it and come back to us with any feedback. Note the [`app.gradle`](https://github.com/Plamen5kov/flavorsproject/blob/master/app/App_Resources/Android/app.gradle#L24-L41) which should look familiar.
The resulting `.apk` files from this build are as follows: 
```
app-arm64-demo-debug.apk
app-arm64-full-debug.apk
app-arm-demo-debug.apk
app-arm-full-debug.apk
app-x86-demo-debug.apk
app-x86-full-debug.apk
```

**Comment by smartsanja2013** [comment]
@tsonevn thanks for the quick answer.  [nativescript-hook-debug-production](https://www.npmjs.com/package/nativescript-hook-debug-production) plugin works well for me to define server urls for uat and prod.
I have read other two questions that you have pointed out. It seems, we only can modify the app name/ appID manually. Cannot be change at the runtime?

@Plamen5kov thanks for the answer. I'll try it. But currently I am using {N}3.3.1

**Comment by Plamen5kov** [comment]
@smartsanja2013  unfortunately, in 3.3.1 you can't use flavors or different build variants as is described in the repo. I'd recommend you update your project to 4.x.x if you need build variants.

**Comment by smartsanja2013** [comment]
@Plamen5kov noted and thanks. How about ios, can we create multiple xcode scheme in {N}4.x similar to android?

**Comment by tdermendjiev** [comment]
Hello @smartsanja2013,

At this point creating custom Xcode schemes and configurations is not supported. Regarding the app name you can still use *build.xcconfig* to define custom variables for different build configurations:

```
CUSTOM_NAME[config=Debug] = Custom;
CUSTOM_NAME[config=Release] = CustomRelease;
```

And then use them in *Info.plist* like:

```
<key>CFBundleDisplayName</key>
<string>${CUSTOM_NAME}</string>
```
