### ISSUE TITLE
how can i use multiple Workers

### ISSUE THREAD

**Issue by AsrarMemon** [NativeScript/NativeScript#5590]
i am create one worker from .ts and other from worker

I'm doing is pretty much this (inside a Button tap):

```
var worker = new Worker("./secound-worker");
    
global.onmessage = function (msg) {
    console.log('onmessage ..............')
    try {
        worker.postMessage('');
    
    } catch(e) {
        console.log(e);
    }
}
```

but it is not working can you please give me a help how can i use  multiple Workers ?

**Comment by NickIliev** [comment]
@AsrarMemon create different instances for each of your workers (e.g. like the `w` [here](https://github.com/NativeScript/demo-workers/blob/master/app/main-view-model.js#L79))

Please note that this repository is for logging issues, bugs and features related to NativeScript.
For how-to related questions please use the community channels like [the NativeScript forum](https://discourse.nativescript.org/), [SO ](https://stackoverflow.com/questions/tagged/nativescript)or [NativeScript community slack](https://nativescriptcommunity.slack.com/messages/general)

**Comment by AsrarMemon** [comment]
Hello Nicklliev
here i can understand how to use multiple workers but actually my question is about how one worker can communicate with another can you please help me on that 
i just need demo or code sample that will show communication between one worker to another 

thanks
