### ISSUE TITLE
isUserInteractionEnabled in scroll view doesnt have the same behaviour in both platforms

### ISSUE THREAD

**Issue by krisidmisso** [NativeScript/NativeScript#5592]
I have an issue where i set grammatically isUserInteractionEnabled= true/false. The false case disables scrolling in ANDROID but all other inputs, i.e: buttons are enabled and you can interact with those.

But in IOS it disables scrolling and every touch-related interaction (except back button in action bar).

I need this function to be the same as it is in android. Is this a bug or am i using it wrong?

**Comment by tsonevn** [comment]
Hi @krisidmisso,
Thank you for contacting us.
The different behaviour of the isUserInteractionEnabled functionality depends on the difference between both platforms. In iOS, this property will disable the interaction of the component, which you have just set it up and on its children as well. However, on Android, we can block only the interaction of the main component. More on the topic could be found in this issue. 

Regarding your case, you can review [this ](https://stackoverflow.com/questions/36773101/nativescript-how-to-programmatically-disable-enable-scrollview-scrolling/36842883) thread in StackOverflow, where it is demonstrated, How to disable the scroll in NativeScript.
