### ISSUE TITLE
404 error when trying to setup on OSX

### ISSUE THREAD

**Issue by gerchicov-bp** [NativeScript/NativeScript#5594]
Problem is independent from platform. Your tutorial:
https://docs.nativescript.org/start/quick-setup
```
npm install -g nativescript
```
result:
```
npm install -g native_script
npm ERR! code E404
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/native_script
...
```

**Comment by tsonevn** [comment]
Hi @gerchicov-bp,
Try to clean up the npm cache with `npm clean cache` and try again to install NativeScript CLI ->`npm install nativescript --g`.
You could also review the thread in [this issue](https://github.com/NativeScript/NativeScript/issues/2400#issuecomment-230282243) and the provided solution in it.

If the problem persists, please send us the full error log from the console.

**Comment by gerchicov-bp** [comment]
@tsonevn thanks it works but fix your answer:
`npm clean cache` -> `npm cache clean`
