### ISSUE TITLE
[Feature Request] Add on "Create" lifecycle callback for view

### ISSUE THREAD

**Issue by bigradish** [NativeScript/NativeScript#5595]
For example, Page's onNavigatingTo and loaded callbacks can be called many times whenever the related events happen, but sometimes I need a function only be called once when the page is created.
Can onCreate and other lifecycle hooks be added in Nativescript like React and Vue? Maybe you can do this by adding a "created" event name in event list of View's "on" method and adding related supports in the your XML mechanism. I think this may be important for Nativescript.
Thank you very much.

**Comment by tsonevn** [comment]
Hi @bigradish,
First of all, thank you for your interest in NativeScript.
Regarding your case, I will suggest using page loaded event and to set up a flag, which can be used for checking, whether this is the first execution of the event. This will help you to call the needed function only once. 
For example:
```
import {getBoolean, setBoolean} from "tns-core-modules/application-settings";
export function onLoaded(args){
    if(getBoolean("isFirstLoad")){
        alert("This will be shown only the first time");
        setBoolean("isFirstLoad", false);
    }
}
```
I am attaching sample project.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1858807/Archive.zip)

**Comment by jogboms** [comment]
@tsonevn There were times i wished this existed too instead of having to pollute application-settings

**Comment by bigradish** [comment]
@tsonevn Thanks for your answer. What I did is similar to yours:

exports.onNavigatingTo = args => {
  let page = args.object
  if (!page.isMyFuncCalled) {
    Myfunc()
    page.isMyFuncCalled = true
  }
}

Are there any issues in my code?
I still think if you can provide the onCreate-like hooks, these extra execution overhead and code can be eliminated.

**Comment by tsonevn** [comment]
Hi @bigradish @jogboms,

Could you provide more detailed info about the use cases of similar onCreate hook and what would be the benefit of introducing similar event?

**Comment by bigradish** [comment]
Hi @tsonevn  For example, in binding a view model to a page, the code is often as follows (just like the code in your HelloWorld template):

`exports.onNavigatingTo = args => {
  let page = args.object
  page.bindingContext = createViewModel(page)
}`

But if the page is frequently navigated to and from, the view model will be created again and again, which is normally not what developers want. To prevent this, the code should be changed to:

`exports.onNavigatingTo = args => {
  let page = args.object
  if (!page.bindingContext) {
    page.bindingContext = createViewModel(page)
  }
}`

If the onCreated hook can be provided, developers do not have to worry about this issue, and the "if" statement is unnecessary.
Thank you.

**Comment by NickIliev** [comment]
@bigradish the scenario you are describing is already handled in a way in NativeScript. For example, if you are navigating to/from (e.g. master-details scenario), you can pass the context via `context` and `bindingContext` properties of the navigation entry. The first can be obtained in the navigated page with `navigationContext` available in `navigatedTo` event and the second can automatically assign the context to the navigated page. More details [here](https://docs.nativescript.org/core-concepts/navigation#navigate-and-pass-context)

**Comment by bigradish** [comment]
@NickIliev Your answer does not meet my request.
What I said is: If the onCreated hook can be provided, developers do not have to worry about whether the onNavigatingTo hook may be call many times.
Thank you.
