### ISSUE TITLE
Nativescript datepicker - expected value

### ISSUE THREAD

**Issue by markomiljkovic** [NativeScript/NativeScript#5596]
### Tell us about the problem
Hello guys I have quick question, since there is no info, in the docs on the website ...
What does datepicker expect at initialization,
https://docs.nativescript.org/cookbook/ui/date-picker
 DateObject like new Date(), or ISO string- new Date().toIsoString(), or something else ???
also can I initialize Datepicker like 
<DatePicker date = "{{ date }}" />
### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.1

**Comment by tsonevn** [comment]
Hi @markomiljkovic,
You could define the DataPicker component directly in the XML as follows:
`<DatePicker></DatePicker>`
You could also set up the date, which should be shown on initial time by setting up `day` `month` and `year` properties.
`<DatePicker day="20" month="04" year="1980"></DatePicker>`
For further questions, please use our [forum ](https://discourse.nativescript.org/) or StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript).
