### ISSUE TITLE
UI/Dialogs: How to set different color,text Alignment for title,button

### ISSUE THREAD

**Issue by priyangamani** [NativeScript/NativeScript#5597]
I tried to set the color in css.But it doesn't show any changes in my alert dialog Text.
Dialog{
    color:red;
    font-size:24;
    }
.myDialog .button1, .myDialog .button3 {color:red};
.myDialog .title {text-align:left;color:red} ;

**Comment by NickIliev** [comment]
@priyangamani there are some styling limitations for the dialogs module discussed [here](https://github.com/NativeScript/NativeScript/issues/3830).
To create custom dialog page I would suggest using [**modal** pages](https://docs.nativescript.org/core-concepts/navigation#modal-pages) - however, keep in mind that the modal pages can only be fullscreen on iOS

At this very moment, you should be able to change the [color ](https://github.com/NativeScript/NativeScript/issues/3198#issuecomment-263568730)and the [background-color](https://github.com/NativeScript/NativeScript/issues/3220) of Dialog thought the `Button` CSS properties.

Closing as duplicate to [https://github.com/NativeScript/NativeScript/issues/3830](https://github.com/NativeScript/NativeScript/issues/3830)

**Comment by spencercap** [comment]
@NickIliev thanks for the `Button` CSS tip! 

hopefully more support / extensibility can be shared here. 
is it possible to color `okButtonText`, `cancelButtonText`, `neutralButtonText`, `title` and `message` individually for example?

**Comment by drewcovi** [comment]
@NickIliev @spencercap any updates on this? im accustomed to providing danger text for destructive actions in an actionsheet.

**Comment by zhitomir-oreshenski-mm** [comment]
Hello support Team, 

Is there any progress on this?

I see that currently last information was one year ago. Is there any possibility to customize Modal -> okButtonText, cancelButtonText, etc?

**Comment by wuilmerj24** [comment]
Hello.

**Comment by MateusSpadari** [comment]
Hello @NickIliev you commented above that now is possible to change the text color and the background color of the Dialog, but i tested right now with Nativescript 6.0 and the background color is not changing !

**Comment by zhitomir-oreshenski-mm** [comment]
Hello @MateusSpadari,

Background color of your modal is also depending on your default theme on your OS (dark/light). In this case, you can also check what value do you have in Info.plist (conf file for IOS) for following properties:

	<key>UIStatusBarStyle</key>
	<string>UIStatusBarStyleLightContent</string>
	<key>UIViewControllerBasedStatusBarAppearance</key>
  	<false/>

and if you have global style applied for all buttons. In that case you may need to change it only for your needs.
