### ISSUE TITLE
Mac access issues

### ISSUE THREAD

**Issue by peppeg85** [NativeScript/NativeScript#5599]
hello, I'm trying to install native script on high Sierra following the advanced guide I still can't install.
I'm new to the Mac world, I have the common issue eaccess with the command sudo npm i -g native script
EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nativescript/docs/html'

I tried also following the guide with nvm, but I still can't make it work. is there a newbie detailed guide to fix this?

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3507
