### ISSUE TITLE
Calendar control

### ISSUE THREAD

**Issue by MiroValchev** [NativeScript/NativeScript#560]
Hi guys,

I was the one asking about the calendar control since I need it ASAP. It would be great if I can play with whatever you have currently available. I know we are some 6 weeks away from official and stable version :)

Keep up the great work!

**Comment by N3ll** [comment]
Hi @MiroValchev! What you are requesting, will be available in the next version 1.5.0 as a Telerik UI component. Stay tuned!

**Comment by MiroValchev** [comment]
Thanks Neli :)

**Comment by vakrilov** [comment]
This control will be available in [nativescript-telerik-ui](https://www.npmjs.com/package/nativescript-telerik-ui).
