### ISSUE TITLE
Custom plugin link issue in Xcode

### ISSUE THREAD

**Issue by smartsanja2013** [NativeScript/NativeScript#5601]
I have created a native ios plugin and exported as .tgz
Now I have added the plugin using this command
`tns plugin add  ./mywork/third-party-package/nativescript-mylib-1.0.0.tgz`

But when building the Xcode project, I am getting following error
```
ld: library not found for -lMYLIB
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
But, In xcode project, I can see `mylib.a` already being added in to **Linked Frameworks and Binaries**

In order to build the Xcode project,
Every time I need to delete the `mylib.a` from Framworks folder in xcode and need to add again manually (with the "copy items if needed" option selected)

Is there any workaround to solve this problem?

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/ios-runtime#898
