### ISSUE TITLE
Build fails after updating to the latest NS.

### ISSUE THREAD

**Issue by mhmo91** [NativeScript/NativeScript#5602]
### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0-2018-03-27-11297
- Cross-platform modules:  ^4.0.0-2018-03-27-02
- Runtime(s): 4.0.0-2018.3.22.2
- Plugin(s): 
  "nativescript-background-http": "^3.2.2",
    "nativescript-camera": "^3.2.1",
    "nativescript-cardview": "^2.0.5",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-exit": "^1.0.1",
    "nativescript-feedback": "1.1.1",
    "nativescript-floatingactionbutton": "^4.1.3",
    "nativescript-geolocation": "^4.2.6",
    "nativescript-image-swipe": "^2.1.0",
    "nativescript-imagecropper": "^0.1.2",
    "nativescript-imagepicker": "^4.0.1",
    "nativescript-intl": "^3.0.0",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-pdf-view": "^2.0.1",
    "nativescript-permissions": "^1.2.3",
    "nativescript-pro-ui": "next",
    "nativescript-textinputlayout": "^2.0.3",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-toast": "^1.4.6",
    "ngx-order-pipe": "^2.0.1",
    "reflect-metadata": "^0.1.12",
    "rxjs": "^5.5.8",
    "tns-core-modules": "^4.0.0-2018-03-27-02",
    "zone.js": "^0.8.4"

### Please tell us how to recreate the issue in as much detail as possible.
the build fails when upgraded the android version n the core modules
![image](https://user-images.githubusercontent.com/3815200/38136284-be841f4e-341d-11e8-8950-6cd5c6f664fe.png)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#991
