### ISSUE TITLE
GitHub API - javax.net.ssl.SSLProtocolException Android 4.4.2

### ISSUE THREAD

**Issue by salomaosnff** [NativeScript/NativeScript#5605]
### Tell us about the problem
I'm trying to display information from a Github user in my application but on accessing the GitHub API I get the following error:
```
TypeError: Network request failed: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl = 0x592e87d8: Failure in SSL library, usually a protocol error
[Salomão Neto]: error: 14077410: SSL routines: SSL23_GET_SERVER_HELLO: sslv3 alert handshake failure (external / openssl / ssl / s23_clnt.c: 744 0x54eafd74: 0x00000000)
```
See my code in the Playground from line 44
https://play.nativescript.org/?template=play-js&id=9alJrl&v=2

### Which platform(s) does your issue occur on?
Android 4.4.2

**Comment by NickIliev** [comment]
@salomaosnff this issue appears to be related to a specifics in Android 4.4.2 and is not reproducible on other Android API levels.

It might be related to [this ](https://github.com/NativeScript/NativeScript/issues/5157)so can you please try [the following solution ](https://github.com/NativeScript/NativeScript/issues/5157#issuecomment-352721710)to force update your provider. The solution is in TypeScript and needs minor syntax changes to work in plain JavaScript.
