### ISSUE TITLE
queue multiple files download background

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/NativeScript#5606]
what is the correct way of downloading multiple files in queue one after another?
i want to download process keep running event if app is closed or killed.
there is nativescript-background-http for uploading files. but i'm unable to find anything for downloads.

**Comment by tsonevn** [comment]
Hi, @bhavincb,
For your case, you could use [getFile ](https://docs.nativescript.org/cookbook/http#get-content-as-file-from-url-you-can-specify-where-the-file-should-be-saved) method provided by HTTP module or [nativescript-downloadmanager](https://www.npmjs.com/package/nativescript-downloadmanager) plugin. Bear in mind that this plugin currently is available only for Android.  The plugin is using the Android DownloadManager, which might allow you to keep downloading the file even if the app is in suspend mode. I have not tested this scenario on my side.

Regarding iOS [documentation](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/TheAppLifeCycle/TheAppLifeCycle.html), it seems that the download will stop when the app went in suspend. In the `Execution States for Apps` section, it is mentioned that `app remains in memory but does not execute any code`. About iOS, you could also review [this thread](https://discussions.apple.com/thread/1782007).

For any further questions, please use our [forum ](https://discourse.nativescript.org/) or StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript).
