### ISSUE TITLE
Add a clearer example of java interface implementation in typescript in the doc

### ISSUE THREAD

**Issue by gdurand** [NativeScript/NativeScript#5611]
In the doc https://docs.nativescript.org/runtimes/android/generator/extend-class-interface#interfaces, the example with typescript is exactly the same as the one for javascript, i.e. with a non idiomatic syntax. So it looks like an error in the doc. This led me to try to implement with functionality by creating a class implementing my interface and trying to instanciate it, which fails.

I think you should provide an example using arrow functions, and also perhaps indicate clearly that trying to create a class is not the way to go (coming from java it's the first reflex).
Also an example of declaration file with the following pattern would be useful:
```
interface IMyInterface {
  doSomething()
}
class MyInterface implements IMyInterface {
  constructor(implementation: IMyInterface)

  doSomething()
}
```

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/docs#1110
