### ISSUE TITLE
[Feature] GridLayout's addChild method to take care of setting row and column

### ISSUE THREAD

**Issue by pedromorgan** [NativeScript/NativeScript#5620]
so here's some code to add a button to  grid

```js
var gridLayout = new GridLayout();
var btn = new Button();
gridLayout.addChild(btn);
gridLayout.setRow(btn, 1);
gridLayout.setColumn(btn, 2);
gridLayout.setColspan(btn, 2);
```

Qt has a neat api for adding a child - [addWidget](http://doc.qt.io/archives/qt-4.8/qgridlayout.html#addWidget)

Maybe something similar to
```
gridLayout.addChild(btn, row, col, rowspan, colspan);
```
above example would be
```js
var gridLayout = new GridLayout();
var btn = new Button();
gridLayout.addChild(btn, 1, 2, 1, 2);
```

**Comment by NickIliev** [comment]
@pedromorgan marking this as a feature and `good-first-issue`.If you (or anyone) have interest in implementing this one all PRs are welcomed - contributing guide can be found [here ](https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md)and [here](https://www.nativescript.org/contribute).

**Comment by rakeshgirase** [comment]
Shouldn't colSpan be an optional attribute?

**Comment by pedromorgan** [comment]
both colSpan and rowSpan

**Comment by rakeshgirase** [comment]
Created a PR https://github.com/NativeScript/NativeScript/pull/6411 for this feature.

**Comment by vchimev** [comment]
Hey Everyone,

I really like the collaboration here - let me reopen and use this issue in a demo. Please, disregard the following comments.

Thank you!

**Comment by vchimev** [comment]
test

**Comment by vchimev** [comment]
test

**Comment by vchimev** [comment]
test
