### ISSUE TITLE
Removing all items from ObservableArray

### ISSUE THREAD

**Issue by pedromorgan** [NativeScript/NativeScript#5622]
I've got an app where I need to remove all items in an ObservableArray<any>, but using the same object.

I was looking for a `.clear()` or `.removeAll()` methods, but can only see `.pop()`.

My workaround is 
```ts
while(myarr.length > 0){
       myarr.pop();
}
```
- What is the correct way ?
- Can a ```.clear()``` method be added, similar to dozens of other api's ?

**Comment by tsonevn** [comment]
Duplicate of #5515
