### ISSUE TITLE
typescript 2.6.2 cannot make async work (only on ios)

### ISSUE THREAD

**Issue by AshleyCao** [NativeScript/NativeScript#5632]
Hi, after reviewing the related questions, I am still unable to find solution to our issue. 

As suggested, async function is compile-able in es5. In tsconfig file, if I target to "es5", async works. But other functions such as "slice" would not work. 

When I target ts to "esnext" . everything performs as expected on Android system. 

So, I just wonder if this issue is something to do with ios setting? Or, is there a good way to target to es6. Tried tslib plugin, no luck.

- CLI: 3.4.3
- Cross-platform modules: 3.4.1
- Runtime(s): 3.4.1
- Sidekick: 1.8.2

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/ios-runtime#903
