### ISSUE TITLE
Rad-list-view issues with Webpack on Ios

### ISSUE THREAD

**Issue by Boud** [NativeScript/NativeScript#5633]
Since updating the Mac at work to High Sierra 10.13.3, we are experiencing issues with our application when bundling with webpack.

The rad-view-lists we use in some of our screens started behaving weirdly and having some kind of visual lag when the page is loaded. This behaviour only appears when using webpack on IOS (it works fine without webpack on IOS and works in both cases on Android)

Without webpack (original behaviour) :
![img_0112 trim](https://user-images.githubusercontent.com/3704952/38413958-7196493a-398d-11e8-975f-878cb016c618.gif)

With webpack (weird lag in loading) :

![img_0110 trim](https://user-images.githubusercontent.com/3704952/38413993-8d789e5a-398d-11e8-8c7e-bd5f81b28f6a.gif)

Did anybody experience something similar ?

tns-cli : 3.4.3
nativescript-angular : 5.0.0
tns-code-module version : 3.4.0
webpack version : 3.8.1
Xcode : 9.3 (Build version 9E145)
Apple Swift version 4.1 (swiftlang-902.0.48 clang-902.0.37.1)

**Comment by NickIliev** [comment]
@Boud what are the versions of [nativescript-ui-listview](https://www.npmjs.com/package/nativescript-ui-listview) and `nativescript-dev-webpack` - please post the content of the `package.json` file. If possible provide a sample project that can reproduce the issue.

Try updating to the latest version of both plugins (nativescript-ui-listview and nativescript-dev-webpack) and the related dependencies and then rebuild the project.
For example:
```
rm -rf node_modules platforms
npm i nativescript-ui-listview@latest --save
npm i nativescript-dev-webpack@latest--save-dev
npm i nativescript-angular@latest --save
 ./node_modules/.bin/update-ns-webpack --config --deps
npm i
 ./node_modules/.bin/update-app-ng-deps
npm i
tns build ios --bundle--env.uglify --env.aot
```

**Comment by NickIliev** [comment]
This issue was moved to telerik/nativescript-ui-feedback#611

**Comment by Boud** [comment]
@NickIliev Thank you for your reply.

For the versions :
 "nativescript-dev-webpack": "0.9.2"

As for the  **_nativescript-ui-listview_**  we are using the older version where it was not packaged separately : 
"nativescript-pro-ui": "3.3.0"

I will try updating both of those dependencies and see if it changes anything.

**Comment by Boud** [comment]
@NickIliev Thank you for your reply.

For the versions :
**"nativescript-dev-webpack": "0.9.2"**

As for the nativescript-ui-listview we are using the older version where it was not packaged separately :
**"nativescript-pro-ui": "3.3.0"**

I will try updating both of those dependencies and see if it changes anything.
