### ISSUE TITLE
How to disable emoji from being entered in TextField?

### ISSUE THREAD

**Issue by priyangamani** [NativeScript/NativeScript#5639]
1.How to disable emoji from being entered in TextField ?
                       or
2.Is there any other way to set keyboard pattern  allow only alphanumeric and symbols  ?

**Comment by NickIliev** [comment]
@priyangamani you can access the native control and apply native solution.
For example as behind TextField on Android stays [android.widget.EditText](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/text-field/text-field.android.ts#L6) you can [apply this solution](https://stackoverflow.com/a/23212485/4936697)

Closing as this repository is for logging issues, bugs and features related to NativeScript.
For how-to related questions please use the community channels like [the NativeScript forum](https://discourse.nativescript.org/), [SO ](https://stackoverflow.com/questions/tagged/nativescript)or [NativeScript community slack](https://nativescriptcommunity.slack.com/messages/general)
