### ISSUE TITLE
Error when submitting app to iTunes with Push Notification

### ISSUE THREAD

**Issue by duongnhatduy** [NativeScript/NativeScript#564]
I recently integrated push plugin to my nativescript app. It works fine when I run it on my phone but when I try submitting to Submit to App Store it gives me the following error

![snip20150807_1](https://cloud.githubusercontent.com/assets/6529267/9133054/0b9bfa8e-3d01-11e5-9fa1-a839245f6dfa.png)

**Comment by fealebenpae** [comment]
Hi @duongnhatduy, it seems that the build process fails to strip the simulator architectures when building the app. Please open `platforms/ios/<project-name>/strip-dynamic-framework-architectures.sh` and remove the text `-perm +111` on line 47. Build you project again and the extra architectures should be gone.

**Comment by duongnhatduy** [comment]
Hi @fealebenpae, it only solved the 2 top errors. I still get theses errors: 
![snip20150810_4](https://cloud.githubusercontent.com/assets/6529267/9160670/162975b2-3f45-11e5-86b0-cc1bcbe147f3.png)

**Comment by valentinstoychev** [comment]
We updated the push plugin with the required changes. Thanks @fealebenpae for the fix.

@duongnhatduy I'm closing this issue, if you experience other problems please let us know.
