### ISSUE TITLE
How to pass context in frame goBack method?

### ISSUE THREAD

**Issue by bigradish** [NativeScript/NativeScript#5641]
I tried code something like:

frameModule.topmost().goBack({
entry: {
context: {
data: 'testing data',
}
}
})

But the page didn't go back.
How to pass context in the frame goBack method?
Thank you very much.

**Comment by tsonevn** [comment]
Hi @bigradish,
Passing a context, while navigating back is not an available option. You can send a context only while using navigate method. This is also described in the [documentation](https://docs.nativescript.org/core-concepts/navigation#navigate-and-pass-context).

**Comment by suparnavg** [comment]
@tsonevn the documentation suggests using `const frame = getFrameById("firstFrame");` but it is not specified (and I couldn't find it on stackoverflow) - how to set the ID for a frame so that we can use the function above?

Would appreciate your help. Thanks!
