### ISSUE TITLE
I am using broadcast receivers, NotificationServiceStart.js file to run when app is killed or closed, but how can i navigate to particular component in this js

### ISSUE THREAD

**Issue by vijaykumar5050** [NativeScript/NativeScript#5643]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there.

**Comment by tsonevn** [comment]
Hi, @vijaykumar5050,
Please follow the template and provide the requested info in it. Also send us sample project, which could be used for debugging.

**Comment by vijaykumar5050** [comment]
Hi @tsonevn ,

I have verified this issue in Native script forum but no result,

tns --version
3.3.1
package.json
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.prel.test",
    "tns-ios": {
      "version": "3.0.0"
    },
    "tns-android": {
      "version": "3.3.1"
    }
  },
  "scripts": {
    "tslint": "tslint -p tsconfig.json",
    "ns-bundle": "ns-bundle",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  },
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/router": "~4.1.0",
    "nativescript-android-utils": "^1.0.2",
    "nativescript-angular": "~3.0.0",
    "nativescript-audio": "^4.3.1",
    "nativescript-camera": "^3.0.1",
    "nativescript-drop-down": "^3.1.0",
    "nativescript-google-maps-sdk": "^2.3.2",
    "nativescript-imagepicker": "^3.0.6",
    "nativescript-loading-indicator": "^2.3.2",
    "nativescript-master-technology": "^1.1.1",
    "nativescript-phone": "^1.3.1",
    "nativescript-photoviewer": "^1.2.0",
    "nativescript-pro-ui": "^3.2.0",
    "nativescript-ripple": "^2.0.0",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-twilio-video": "file:nativescript-twilio-video",
    "nativescript-xml2js": "^0.5.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "~3.0.0",
    "tns-platform-declarations": "^3.3.0",
    "twilio": "^2.1.1",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.1.0",
    "@ngtools/webpack": "^1.3.0",
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.1",
    "codelyzer": "^3.0.1",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~2.1.0",
    "filewalker": "^0.1.3",
    "jasmine-core": "^2.6.2",
    "karma": "^1.7.0",
    "karma-jasmine": "^1.0.2",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "~0.4.0",
    "nativescript-dev-webpack": "next",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.0.2",
    "tslint": "^5.4.2",
    "typescript": "~2.2.1",
    "webpack": "~2.6.1",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1",
    "nativescript-worker-loader": "~0.8.1",
    "clean-webpack-plugin": "~0.1.19",
    "css-loader": "~0.28.7",
    "uglifyjs-webpack-plugin": "~1.1.6"
  }
}
I have used Braod cast receivers to run android backgroud service there i need to open particular component

com.pip3r4o.android.app.IntentService.extend("com.tns.broadcastreceivers.NotificationIntentService", {
  onHandleIntent: function (intent) {

    /*let context = application.android.context;
    intent.setClassName("com.test", "com.test.MainActivity");
    intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
context.startActivity(intent);*/

    var frames = require("ui/frame");
    frames.topmost().navigate("app/components/videochat/videochat.module.");
    console.log(" CURRENNT ENTRY.............."+topmost.currentPage);    
    topmost.navigate("Page(60)");
    console.log("++++++++++++++++++++++NotificationIntentService++++++++++++++++++++++");

    android.support.v4.content.WakefulBroadcastReceiver.completeWakefulIntent(intent);
  }
});

**Comment by NickIliev** [comment]
@vijaykumar5050 use [this example ](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/0b0722025e83126efdf42433f25d1d4a676f9fc0/app/application/app-using-android-specifics/app-using-android-specifics.component.ts#L40-L47)as reference and notice that the this is a native callback and the meaning of `this` is different so use the this-that pattern to pass the context and the current frame instance.
