### ISSUE TITLE
Application is closed when press on back button when the stack of route is empty 

### ISSUE THREAD

**Issue by MuhammadTahir92** [NativeScript/NativeScript#5645]
hey , It's the default behaviour of application when i press on back button from the dashboard when the routes stack is empty application is closed and when i tap again on application icon to start the application then application is not resume to the dashboard but rather then this it start from scratch .

> What is want to to move the application to the background Or foreground state so when it runs again it must start from where it is but not from scratch . 
what can i do for this please guide

**Comment by NickIliev** [comment]
@MuhammadTahir92 indeed this is the default behavior.

To overcome this you could overwrite the backPressedEvent for Android. Details [here](https://stackoverflow.com/questions/40603588/nativescript-handling-back-button-event).

Please notice that the repository is for logging issues, bugs and features related to NativeScript.
For how-to related questions please use the community channels like [the NativeScript forum](https://discourse.nativescript.org/), [SO ](https://stackoverflow.com/questions/tagged/nativescript)or [NativeScript community slack](https://nativescriptcommunity.slack.com/messages/general)
