### ISSUE TITLE
Make SignalR Compatible with NativeScript

### ISSUE THREAD

**Issue by tuckerjt07** [NativeScript/NativeScript#5647]
I opened a feature request with the SignalR team to make it compatible with NativeScript. (https://github.com/aspnet/SignalR/issues/1926#issuecomment-379968069) I was directed here to make sure it wasn't an issue inside of NativeScript. Would someone be able to take a look?

**Comment by NathanaelA** [comment]
Just so you know I already have a commercial plugin that works with NativeScript and SignalR.   https://nativescript.tools - https://nativescript.tools/product/15

**Comment by NathanaelA** [comment]
I never said it wasn't Core compatible; not sure where you got that idea.   But if their is an issue with SignalR Core; I'll get it squared away.  :grinning:

**Comment by tuckerjt07** [comment]
Your latest commit date is too old for it to be Core compatible.

**Comment by NathanaelA** [comment]
You could be right -- depends on the changes needed (and when they occurred); and if you were looking at my private (for paid users) repo where I actually keep all the code.  :grinning:      

If you were looking at the public github repo; it is a empty placeholder that hasn't been updated for a while; as the paetron idea never really took off... 

---

Since it has been called into question; I'll be pulling the latest Core SignalR and seeing what (if anything) needs to be fixed.   So even if it is incompatible today; probably be working by the end of the week.  :grinning:

**Comment by tuckerjt07** [comment]
@tsonevn this isn't related to his plugin. I wish he would quit muddying up the issues that I've created to be honest. I have no desire to pay for a plugin that I can write myself. I'd rather contribute something back to the community as a result of my work.  The SignalR team has a free plugin that will work with NativeScript with a few minor changes in its code. They asked me to post over here just to confirm that these changes are necessary before making them in their repo. Just to reiterate since he has added confusion to both issues on this topic @NathanaelA and his repo have zero involvement or consideration in this work.

**Comment by NathanaelA** [comment]
@tsonevn - Tuckers problem is not with my plugin.  (When I first posted my plugin link; it was to help people find a solution, which is what I thought he needed, but it is unrelated to the issue).     

What, he actually wants NativeScript to be compatible as is using the standard SignalR code base (no extra plugin needed).  And for that to happen, there are a couple places in the HTTP module that are doing things different than a standard webbrowser does.    What tucker should probably do is list the things that are different; and create some test case code to show the issues...    Then the NS team can decide if any of them are something that can be fixed or to ingrained in how NS currently works...

**Comment by tuckerjt07** [comment]
@NathanaelA no, what I should do is what I was trying to do, before you hijacked my issues in both places, work with the SignalR team to either make the changes or allow for extensibility. I have no desire to see the NativeScript libraries changed and was just asking for confirmation that everything was working as expected on this side per the request of the SignalR team. I would kindly ask that you do not speak for me, stop using my issues to promote your plugin and to please quit muddying the issue.

**Comment by dudipsh** [comment]
@tuckerjt07  
i have create js file working  with signalr2(core signalr) if it's relevant i will open github with the file
its a vrey basic implementation on websocket using @NathanaelA nativescript-websocket plugin

**Comment by dudipsh** [comment]
@tuckerjt07 @tsonevn @tuckerjt07
you can use my plugin it's free 
https://github.com/dudipsh/nativescript-signalr-core

**Comment by NickIliev** [comment]
Closing the feature request as there is already a plugin that handles this issue.
