### ISSUE TITLE
RadSideDrawer.showDrawer() should hide keyboard

### ISSUE THREAD

**Issue by pedromorgan** [NativeScript/NativeScript#5651]
I have an app with a `RadSideDrawer`, and a simple `Page` with a `TextField` as filter for a `RadListView`
- focusing to the `TextField` shows the keyboard
- Clicking the button shows the sideDrawer, but the keyboard is still visible over the SideDrawer

What I expect to happen is the `showDrawer()` method to hide the keyboard, if it is showing.

![screenshot_1523389248](https://user-images.githubusercontent.com/123932/38579505-21dab014-3cff-11e8-9ac1-516bff708831.png)

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#614
