### ISSUE TITLE
[Feature Request] Passing context in frame goBack method

### ISSUE THREAD

**Issue by bigradish** [NativeScript/NativeScript#5653]
I think it should be very useful that the frame goBack method can pass context just like the navigate method.
A common use case is that to input a field in a page, another page is navigated, and after selecting a value, go back the previous page with the selected value.
Thank you very much.
Refer to #5641

**Comment by NickIliev** [comment]
@bigradish you can use[ this technique](https://discourse.nativescript.org/t/how-do-i-pass-data-when-navigating-back-using-the-back-button/3584/2?u=nickiliev) to send context when navigating back

**Comment by manoldonev** [comment]
@bigradish Have you considered using [modal pages](https://docs.nativescript.org/core-concepts/navigation#modal-pages)? They seem to suit what you are trying to achieve in your application scenario.

**Comment by bigradish** [comment]
@manoldonev Thanks for your information.
I've not tried modal page. The document shows that it uses callback.
I think with callback, getting value when go back can also be implemented without modal page. Suppose that we navigate from page1 to page2 to pick a value, the page1.js can include below code:

`frameModule.topmost().navigate({`
`moduleName: './page2',`
`context: {`
`callback: value => {`
`//do something with the value.`
`},`
`},`
`})`

and page2.js can include code:

`let callback`
`exports.onNavigatingTo = args => {`
`let page = args.object`
`callback = page.navigationContext.callback`
`}`
`exports.onSelectValue = args => {`
`callback(args.object.value)`
`frameModule.topmost().goBack()`
`}`

How do you think of this?

**Comment by manoldonev** [comment]
@bigradish It would probably work but personally I use the out-of-the-box modal page functionality in similar scenarios.

**Comment by pedromorgan** [comment]
So bumping into same issue as @bigradish .

I've got a callback working, but wish it was a simpler api with 
`frameMod.topmost().goBack({NavData})`

**Comment by suparnavg** [comment]
@pedromorgan did you manage to put a callback on the frameMod.topMost().goBack() function? Could you share some details if so? Thanks!

**Comment by NickIliev** [comment]
On many occasions, the users will navigate back through the hardware back button and not via a developer created frame.goBack() ... so you will again face the same issue. Using modals will allow you to handle the close callback no matter if the user has closed the callback via your programmatically created interface or via the back button.

SO the above said I would say that passing context on the back is not a must-have feature ()as it will work with limitations

**Comment by andrewm-mitchells** [comment]
Hello,

I know this is relatively old thread but hoping someone here can point me in the right direction.

I have parent and child pages. One is list of items, anther item details. I need to refresh (make new api call) data on the parent page when navigating back to it from the child page.

Using modal is not an option as child page has more nested pages/modals and it would be problematic to control all that stuff from the modal.

Any help would be highly appreciated.
