### ISSUE TITLE
IOS event bubbling issue

### ISSUE THREAD

**Issue by shabib3** [NativeScript/NativeScript#5659]
Hi,

the following happened only on IOS.

I have an issue with event passing through elements.
I know that there is a lots of already opened (actually closed) issues about this subject but I cannot find the solution for me.

So here is the [playground sample](https://play.nativescript.org/?template=play-ng&id=tbTlFk&v=2)

this issue is that I have a component that represent a floating menu (`floating-menu`) that get some parameters and invoke action by the chosen item - I simplified the use in the sample.
the problem in this is that the `floating-menu` component is catching the all screen (I got to catch the all screen for the blurred layout when pressing the opening the menu) and by that I cannot pass my tap event to the element in the under layout (the number in case of the sample - that should raise alert on tap).

What can I do in this case?

**Comment by NickIliev** [comment]
@shabib3 your issue can be resolved by combining two techniques - providing size and using the Angular `EventEmiiter`.Currently, the floating menu is spanned all over the whole screen (assign background-color for the main `GridLayout` to visualize what I mean)!  
The second thing is that you are using tap event to catch the user interaction but the tap is on the whole floating menu component. This would work if there is only a single action to catch, but in your case where there are two buttons, you should "know" which action was triggered. So here comes [`EventEmitter`](https://angular.io/api/core/EventEmitter)

For example, use [this "toolbar" as reference](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/apod/toolbar/toolbar.component.html). The five different buttons (actions) are outputted via EventEmitter [here](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/apod/toolbar/toolbar.component.ts#L12-L32) and passed [to the parent component via the notify event](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/apod/apod.component.html#L20) and the[ related callback](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/apod/apod.component.ts#L93-L127)

**Comment by shabib3** [comment]
Actually solved it by:
1. align the `StackLayout` the contains the `floating-menu` that in the `home.component.ts` to the right and the bottom 
2. set the most top `GridLayout` of the `floatingMenu.component.html` to be `rows="auto" columns="auto"` and then it is sets the occupying automatically

this is the fixed sample -> https://play.nativescript.org/?template=play-ng&id=tbTlFk&v=3
:slightly_smiling_face:
