### ISSUE TITLE
Ability to use GridLayout in Repeater

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#566]
It would be great if you could use the GridLayout in a Repeater. Each itemTemplate would be a new row. An example being:

```xml
    <Repeater items="{{ accounts }}">
      <Repeater.itemsLayout>
        <GridLayout columns="100, *, 100"/>
      </Repeater.itemsLayout>
      <Repeater.itemTemplate>
         <Image col="0" cssClass="first-image" horizontalAlignment="center"  src="{{ image_url }}"/>
         <Label col="1" cssClass="first-item" text="{{ item1 }}" />
         <Label col="2" cssClass="second-item" text="{{ item2 }}" />
      </Repeater.itemTemplate>
    </Repeater>
```

**Comment by enchev** [comment]
Hi @lscown,

There is no problem to use ```GridLayout``` as ```Repeater``` ```itemsLayout``` since we will create ```View``` from ```itemTemplate``` for each item and will add this ```View``` as ```GridLayout``` child. There is no logic however that will set rows/columns for these children. 

Can you post more info about your scenario? Why not use vertical ```StackLayout``` for ```Repeater``` ```itemsLayout```?

**Comment by lscown** [comment]
Hey @enchev,

So currently we are using a vertical `StackLayout` with each new row being a horizontal `StackLayout`. Like this:

```xml
<Repeater items="{{ accounts }}">
      <Repeater.itemTemplate>
        <StackLayout orientation="horizontal">
          <Image cssClass="first-image" horizontalAlignment="center"  src="{{ image_url }}"/>
          <Label cssClass="first-item" text="{{ item1 }}" />
          <Label cssClass="second-item" text="{{ item2 }}" />
        </StackLayout>
      </Repeater.itemTemplate>
    </Repeater>
```

However, our need for a GridLayout is that each column is a aligned nicely. Whether it's left, right or centre align. 

Currently it looks like:
![screen shot 2015-08-12 at 1 33 35 pm](https://cloud.githubusercontent.com/assets/5018471/9214924/e3765e00-40f7-11e5-8e34-6d2ea2f13f56.png)

We want the 3rd item on each row to be aligned in a column.

Cheers

**Comment by enchev** [comment]
Hi @lscown,

Here is an example how to achieve this:
```XML
<Repeater items="{{ accounts }}">
    <Repeater.itemTemplate>
          <GridLayout columns="100, *, 100" height="100">
                <Image cssClass="first-image" horizontalAlignment="center"  src="{{ image_url }}" />
                <Label cssClass="first-item" text="{{ item1 }}" col="1" />
                <Label cssClass="second-item" text="{{ item2 }}" col="2" />
          </GridLayout>
     </Repeater.itemTemplate>
</Repeater>
```

**Comment by enchev** [comment]
Just a quick update! If you want your rows to use auto-height you can define single row like this:
```XML
 <GridLayout columns="100, *, 100" rows="auto">
        <Image cssClass="first-image" horizontalAlignment="center"  src="{{ image_url }}" />
        <Label cssClass="first-item" text="{{ item1 }}" col="1" />
        <Label cssClass="second-item" text="{{ item2 }}" col="2" />
</GridLayout>
```

**Comment by lscown** [comment]
Awesome, that's a good point. I'll give this a go tomorrow, thanks!

**Comment by NathanaelA** [comment]
@enchev doesn't this still mean it is doing:
    <StackLayout><GridLayout/></StackLayout> for each item?

**Comment by enchev** [comment]
Yes. You have one main layout for all items and you can choose how these items will be arranged and you have one item layout where you can specify the arrangement of the item itself. Of course if your item is simply text you do not need any item layout and you can use simple Label.

**Comment by NathanaelA** [comment]
Ah, that makes more sense; I was thinking the \<StackLayout> was going to be repeated also; but so that is the parent container that basically replaces the repeater in the actual view.   So based on the above, each item is just a single <GridLayout> in side the repeater, correct?

**Comment by enchev** [comment]
Indeed the StackLayout is only one and will host all items as children.
