### ISSUE TITLE
Build Error: The sandbox is not in sync after install tns-plugin

### ISSUE THREAD

**Issue by miguelopezv** [NativeScript/NativeScript#5660]
## Please, provide the details below:
after installing any plugin, i.e. nativescript-imagepicker, the project will work if I use` tns run`, however after using `tns prepare ios` or `tns build ios`, opening the project on Xcode and trying to build it I get the error mentioned above. I've tried running `pod install`, and `pod update` without any difference.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.3
- Cross-platform modules: 3.4.1
- Runtime(s): tns-android: 3.4.2, tns-ios: 3.4.1
- Plugin(s): 
```
"dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "nativescript-angular": "~5.2.0",
    "nativescript-camera": "^4.0.2",
    "nativescript-drop-down": "^3.2.1",
    "nativescript-imagepicker": "^5.0.2",
    "nativescript-iqkeyboardmanager": "^1.2.0",
    "nativescript-ngx-fonticon": "^4.1.0",
    "nativescript-social-login": "^3.0.11",
    "nativescript-sqlite": "^2.0.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-listview": "^3.5.4",
    "nativescript-ui-sidedrawer": "^3.5.2",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~5.5.5",
    "tns-core-modules": "~3.4.0",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~5.2.0",
    "@ngtools/webpack": "~1.9.1",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "codelyzer": "~4.0.2",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.3.5",
    "nativescript-dev-typescript": "~0.6.0",
    "nativescript-dev-webpack": "^0.9.2",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "~6.0.6",
    "tns-platform-declarations": "^3.4.1",
    "tslint": "~5.8.0",
    "typescript": "~2.6.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  }
```

### Please tell us how to recreate the issue in as much detail as possible.
just create an empty project, install a plugin like nativescript-imagepicker, and then try to build from xcode.

**Comment by tsonevn** [comment]
Hi @miguelopezv 
I tested the case with the latest NativeScript(4.0.0) and was unable to recreate that issue. I would suggest updating the CLI while following:
`npm uninstall nativescript --g`
`npm install nativescript --g`

Than create a new project `tns create test --ng` add ` nativescript-imagepicker` plugin in the project.
Prepare the project `tns prepare ios` and build it the project with Xcode.

**Comment by miguelopezv** [comment]
Apparently updating `nativescript-cli` to version 4.0.0 and `tns-ios` version to 4.0.1 fixed the problem.
