### ISSUE TITLE
[Question] Isn't formattedstring span got tap event? 

### ISSUE THREAD

**Issue by yclau** [NativeScript/NativeScript#5664]
![30176912_1823891954298791_126538053_o](https://user-images.githubusercontent.com/4135524/38656710-ec600a32-3e4e-11e8-8a23-a3cabdf159bf.png)

### Tell us about the problem
I trying to do collapse word in description , how can I do show more beside the label when click will expand? I using formatted string to do this kind function but no have tap event under span.

### Which platform(s) does your issue occur on?
Both

**Comment by tsonevn** [comment]
Hi @yclau,
Currently, we could set up the tap event only on the component itself. For example:
```
<Label tap="onLabelTap" class="h3 p-15 m-15 text-left">
    <FormattedString>
        <Span text="Words " color="#006600" ></Span>
        <Span text="with " color="#990000" fontAttributes="Bold"></Span>
        <Span text="different " color="#ffcc00"></Span>
        <Span text="color."></Span>
    </FormattedString>
</Label>
```
We have a feature request logged [here](https://github.com/NativeScript/NativeScript/issues/3671) for ClickableSpan support. You could keep track on it for further info. 
For further questions, please use our [forum ](https://discourse.nativescript.org/) or StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript).
