### ISSUE TITLE
Root RadSideDrawer + ActionBar save area issue with  NativeScript 4.x.x on iOS 

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#5672]
Using nativescript-ui-sidedrawer@4.0.0 with tns-core-modules@4.0.0 is causing save area movement issue for the RadSideDrawer when used with pages with and without ActionBar.

Steps to reproduce:
- [use this applicaiton](https://github.com/NickIliev/nativescript-ng-cosmos) on iOS device/emulator.
- the RadSideDrawer is placed as root in[ app.component.html](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/app.component.html)
- the [first loaded page](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/login/login.component.html) is **without** ActionBar
- when **navigating to a page with ActionBar** [like this one](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/main/main.component.html) (tap "Home" or some login option) the RadSideDrawer is "jumping" and starts showing up behind the save area - best visualized on iPhoneX but reproducible on each iOS 11 device.

**Comment by chrisse27** [comment]
@NickIliev Would it be possible to have a look at the side drawer source code, so we could figure out what's going wrong in this case. This issue is currently blocking as from releasing a new version of an app for our customer.

**Comment by MartoYankov** [comment]
@chrisse27 We found a way to work around the issue and will release a patch version for the nativescript-ui-sidedrawer today.

**Comment by chrisse27** [comment]
Cool, thanks for the update.

**Comment by MartoYankov** [comment]
@chrisse27 We have released the patch version 4.1.1. Can you check it out?

**Comment by chrisse27** [comment]
@MartoYankov Behavior is now consistent for pages with and without ActionBars. So I would consider this fixed. To make the side drawer draw itself up to the very top on iPhoneX I added a negative margin to tkDrawerContent
```
  <StackLayout tkDrawerContent style="margin-top: -safeAreaInsetTop">
    ...
  </StackLayout>
```
where safeAreaInsetTop is set in our source code.

**Comment by MartoYankov** [comment]
@chrisse27 Yep, we are aware that this is problematic and providing ways to handle the safe area on iOS 11 is on our roadmap.
