### ISSUE TITLE
Slider component does not update on tap (iOS)

### ISSUE THREAD

**Issue by spierala** [NativeScript/NativeScript#5675]
The Slider component does not update its value on tap Event (on iOS). 
Dragging the Slider handle seems to be the only way to change the slider value.
The native iOS Slider does update on tap. Therefore I am wondering why the nativescript Slider does not behave the same way. 

tns version: 3.4.3

I tested on iOS v 9.3.5 and v 11.2.

I did not test Android. 

The issue can easily be reproduced in the "nativescript-sdk-examples-ng" repo: https://github.com/NativeScript/nativescript-sdk-examples-ng

**Comment by tsonevn** [comment]
HI @spierala,
This behaviour seems to expect in iOS. The NativeScript Slider is a common abstraction of UISlider. Regarding the iOS documentation:
> slider sends value-changed events continuously as the user moves the slider’s thumb control.

Based on that, the slider will not change the value, if you tap on a random place on the component different from the thumb. More about this could be found [here](https://developer.apple.com/documentation/uikit/uislider?language=objc).
