### ISSUE TITLE
emit in textChange cause focus issues on textfield

### ISSUE THREAD

**Issue by MuhammadTahir92** [NativeScript/NativeScript#5677]
I am using textfield in nativescript angular and it cause issues on delete the string or input new string in textfiled 

html 
`<TextField #textFieldColor [(ngModel)]='textFieldValue'  (textChange)="onTextChange($event)" width="80" row="0"  col="1"  returnKeyType="done"    (blur)="onBlur($event)"  keyboardType="number" class="{{ isSelectedIncrement ? 'fieldTypeTrue tl-small-text' : 'fieldTypeFalse tl-small-text' }}" ></TextField>
`

ts
` onTextChange(args)
  {    
    this.textFieldValue = Number(args.value);
    this.quantityChanged.emit(args.value);
  }
  `

>  this.quantityChanged.emit(args.value);  
As the emit function call in textfield the focus refresh in textfield

https://youtu.be/dieOJfuxpWU

**Comment by MuhammadTahir92** [comment]
video click is also added so you can easily understand

**Comment by NickIliev** [comment]
@MuhammadTahir92 you are using two-way-binding (`ngModel`) and a `textChange` at the same time, and this is causing both to trigger the textChange event.
Try the following instead (which just as using ngModel for `text` property).
```XML
<TextField [text]="textFieldValue" (textChange)="onTextChange($event)">
```

Also, the logic suggests that when the user changes the value in your text field, you will also change the binging via `this.textFieldValue = Number(args.value)` - this seems unnecessary - is there are a reason for the explicit `Number` casting of the bounded variable?

I might be missing the real issue here with the `emit` - if so please send me [a Playground demonstration](https://play.nativescript.org/) so I could investigate further.

**Comment by NickIliev** [comment]
@endymion00 this is an Angular concept. In NativeScript Core (plain javaScript or TypeScript projects) you can't create an XML change event handler. You could directly attach to the wanted event via code-behind

For example (TypeScript)
```TS
export function onTfLoaded(args: EventData) {
    let tf = <TextField>args.object;

    tf.on("textChange", (args) => {
        console.dir(args);
    })
}
```

XML
```XML
<TextField hint="my text" loaded="onTfLoaded" />
```

**Comment by endymion00** [comment]
hey @NickIliev ,
Ok, got it. Thank you very much for you help!

**Comment by toppa80** [comment]
Hi @NickIliev,
do you have an example for a JS-Version? I've tried:

JS
´´´
exports.onTfLoaded = function(args) {
    let tf = args.object;

    tf.on("textChange", (args) => {
        console.dir(args.text);
    })
}
´´´

XML
´´´
<TextField text="" hint="" keyboardType="number" loaded="onTfLoaded" />
´´´

But it is not working :(

Best regards,
Tobias

**Comment by toppa80** [comment]
Hi @NickIliev,
do you have an example for a JS-Version? I've tried:

JS
```
exports.onTfLoaded = function(args) {
let tf = args.object;

tf.on("textChange", (args) => {
    console.dir(args.text);
})
}
```

XML
```
<TextField text="" loaded="onTfLoaded" />
```

But it is not working :(

Best regards,
Tobias

**Comment by NickIliev** [comment]
@toppa80 here is a[ plain JavaScript example](https://play.nativescript.org/?template=play-js&id=diqYwn) demonstrating the above - overall the same with no changes I've just replaced the `console.dir` with `console.log`  and for demonstration purposes I am logging only the text value
