### ISSUE TITLE
Fetch API's statusText should not return status code

### ISSUE THREAD

**Issue by moll** [NativeScript/NativeScript#568]
Talking about the recently merged Fetch polyfill.
XMLHttpRequest's `statusText` includes the status code, but Fetch's, I believe, shouldn't.
https://fetch.spec.whatwg.org/#concept-response-status-message

Cheers

**Comment by ligaz** [comment]
Hey @moll,

Can you please elaborate more on this? The spec defines that there should be a `status` and `status message` fields. The polyfill implementation that we provide "borrows" from the one that GitHub has [implemented](https://github.com/github/fetch/). [Here](https://github.com/github/fetch/blob/master/fetch.js#L274-L276) is the relevant code that sets the `status` and `statusText` properties.

**Comment by moll** [comment]
Well, if the Fetch polyfill behaves incorrectly too, then that's the problem with copying code rather than depending on it — we've got two upstreams to fix. :-)
Anywho, when I did the following, I saw the status code prefixed with the status code in NativeScript (e.g. "200 OK"):
```
fetch("/").then((res) => console.log(res.statusText))
```
This shouldn't happen. It should just be `OK`.

**Comment by ligaz** [comment]
It turned out that this is a bug in our XMLHttpRequest polyfill. It should be fixed with this PR #591. 

Thanks for your help.

**Comment by moll** [comment]
Hehe, not so easy. Two APIs, two different behavior, I believe. ^_^
See https://github.com/NativeScript/NativeScript/pull/591#issuecomment-131187300.

**Comment by moll** [comment]
Noticed another bug there and made https://github.com/NativeScript/NativeScript/issues/592. ;-)

**Comment by enchev** [comment]
I've just replied to #592. Do you think we can close this?

**Comment by moll** [comment]
I suppose so. Let's continue in #592.
