### ISSUE TITLE
coverflow plugin

### ISSUE THREAD

**Issue by peppeg85** [NativeScript/NativeScript#5681]
hello, is there a coverflow plugin for nativescript? or some guides to create with css? thank you

**Comment by tsonevn** [comment]
Hi @peppeg85,
You could check [nativescript-carousel](https://www.npmjs.com/package/nativescript-carousel) plugin and to verify if it is applicable to your case. 
For any further questions, please use our [forum ](https://discourse.nativescript.org/) or StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript). This repository is used only for bug reporting and feature requests.
