### ISSUE TITLE
WebView execute javascript very slow on iOS. NativeScript 3.4 & 4.0

### ISSUE THREAD

**Issue by erikandershed** [NativeScript/NativeScript#5683]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes

### Tell us about the problem
NativeScript 3.4 & 4.0 performance JavaScript is slow. Much much slower then normal WKWebView when build in Xcode. Also tried the NativeScript playground and it has the same slow execute of javascript.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
NativeScript 3.4 & 4.0

### Please tell us how to recreate the issue in as much detail as possible.
The same slow execution of javascript appear in the [NativeScript Playground].

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

var createViewModel = require("./main-view-model").createViewModel;
var webViewModule = require("tns-core-modules/ui/web-view");
function onNavigatingTo(args) {
    var page = args.object;
    var webView = page.getViewById("webview");
    webView.on(webViewModule.WebView.loadFinishedEvent, function () {});
    webView.src = "<page with heavy is code>";
    page.bindingContext = createViewModel();
}
exports.onNavigatingTo = onNavigatingTo;

**Comment by tsonevn** [comment]
Hi @erikandershed,

Could you provide some more info about your project and what you are trying to achieve? It will help if you give us more info about the JavaScript code, which you want to execute while using the WebView. Also provide sample project, which could be used for debugging.

Thank you in advance for your cooperation.

**Comment by erikandershed** [comment]
Hi @tsonevn! 

Of course, here is a link to my project [(Download).](https://www.dropbox.com/s/063sn1vrvy1wbkc/app.zip?dl=0) Test clicking the radio or checkbox, it take an sec before it get selected. On desktop the click in instant. I am testing on an iPhone X.

![image-1](https://user-images.githubusercontent.com/260369/38798900-3ba82202-4163-11e8-9e32-3f42038c845e.jpg)

**Comment by tsonevn** [comment]
Hi @erikandershed,
Please attached the `package.json` and `tsconfig.json` files, which are required for building the project.

**Comment by erikandershed** [comment]
oj sorry.. here is the file [Download](https://www.dropbox.com/s/mgqy5gqnct282uz/app.zip?dl=0). Hope this is working. :D

**Comment by erikandershed** [comment]
@tsonevn did it work?

**Comment by tsonevn** [comment]
Hi @erikandershed,
I am checking it now.

**Comment by tsonevn** [comment]
Hi @erikandershed,
The issue might be related to the JavaScript which is set up to config the site's initial-scale.
Just for the test I would suggest opening `node_modules/tns-core-modules/ui/web-view/web-view-ios.js` and replace
`var jScript = "var meta = document.createElement('meta'); meta.setAttribute('name', 'viewport'); meta.setAttribute('content', 'initial-scale=1.0'); document.getElementsByTagName('head')[0].appendChild(meta);";` -> `var jScript = ""` then try to build the project again `tns run ios` and check if the javascript will be executed slowly again.

**Comment by erikandershed** [comment]
Hi @tsonevn,
I did change the row `87` to only `var jScript = ""; ` in the `/web-view-ios.js`. But sorry I can't see any speed improvement. Any other idea what it can be?

**Comment by erikandershed** [comment]
Hi @tsonevn,
Sorry mate, it did work! 
First I didn't remove the `ios` folder from `platforms/`. But after I did that it all worked super nice!!

Big thanks!!

**Comment by tsonevn** [comment]
Hi @erikandershed 
You could also keep track on [this feature request](https://github.com/NativeScript/NativeScript/issues/5443), about providing further control on the JavaScript, which is set up on the WebView init in iOS.

**Comment by erikandershed** [comment]
@tsonevn, thank I will
