### ISSUE TITLE
HTTPS response is different on iOS and Android

### ISSUE THREAD

**Issue by exAbstracto** [NativeScript/NativeScript#5684]
## Please, provide the details below:
We're implementing a rest server and a mobile client to call the various rest endpoints (via https, with nativescript-https).
On Android, the response is a plain JSON, ready to be used (accessing the fields can be done with response.field1, response.field2 etc.)
On iOS, the response is a NSDictionary object, getting the actual data from it has to be done with response.valueForKey("field1"), response.valueForKey("field2") etc. 
This is not optimal, it brings a platform dependency that we would like to avoid.
We have rest calls througout the application, thus a lot of potentially platform dependent points. 

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem
HTTPS response is different on iOS and Android

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) 3.4.0
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) 3.4.0
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project) 3.4.0 and 3.4.0
- Plugin(s): (look for the version number in the `package.json` file of your
project) 

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

var https = require("nativescript-https");

function someHttpsCall = function() {
        return https.request({
                url: "serverURL/restEndPoint",
                method: "GET",
                headers: {
                    "Content-type": "application/json",
                },
            }).then(handleErrors)   // implemented somewhere else
            .then(function(response) {
                return response.content.data;
            })
            .then(function(data) {
// ------> Here, data is a JSON in Android, and a NSDictionary in iOS 
           }
}

**Comment by tsonevn** [comment]
Hi @exAbstracto,
If I understand you correctly, you are using `nativescript-https` in your application, instead of the HTTP module provided by core modules.

One of our community members create the 'nativescript-https' and, the NativeScript team does not support it. Regarding that, if you are facing any issues with it please log an issue in the [plugin's repository](https://github.com/gethuman/nativescript-https).

**Comment by exAbstracto** [comment]
Hi Tsonevn, 
Thank you for the reply. 
Does the standard http module support SSL pinning?

**Comment by tsonevn** [comment]
Hi @exAbstracto,
The HTTP module does not support SSL pinning, because of that the `nativescript-https` was created.

**Comment by exAbstracto** [comment]
But is it even possible, @tsonevn, to do https calls with the http module? Thank you!
