### ISSUE TITLE
IOS - event bubbling

### ISSUE THREAD

**Issue by shabib3** [NativeScript/NativeScript#5685]
Hi,

I try to implement a button on top of a layout...the layout has an function on tap and also the button has one, every one has a different logic to invoke.

Seems like in Android it is working naturally - when I tap the layout the layout tap event function invokes
the issue is when it comes to IOS - it seem that when I press the button what happens is that both of the events function are invoke...it is important to say that the layout tap function is calling first.

[here is an playground sample to show my issue](https://play.nativescript.org/?template=play-ng&id=cm9ZGQ).

I see some suggested solution but non of them is worked for me.

thanks! :)

**Comment by tsonevn** [comment]
Hi @shabib3,

The event handling on both platforms have some differences, and this iOS behaviour seems to be expected. Based on the iOS docs, the `UIKit automatically directs that event to the most appropriate responder object, known as the first responder. ` 

In your case, you have set up the tap event for both `StackLayout` and its parent `GridLayout`, and the tap event will be handled by the `first responder`(In the project this is the GridLayout). More about the topic could be found in the iOS [documentation](https://developer.apple.com/documentation/uikit/touches_presses_and_gestures/understanding_event_handling_responders_and_the_responder_chain?language=objc).

To solve the case in the project, I can suggest setting up different events to the Layouts. For example to setup touch gesture to the StackLayout and tap for the GridLayout.
```
<ActionBar title="Home" class="action-bar">
</ActionBar>

<GridLayout width="100%" rows="auto" columns="*" (tap)="tapRed($event)">
	<StackLayout row="0" height="100" backgroundColor="red">
	</StackLayout>

	<StackLayout row="0" (touch)="tapGreen($event)" backgroundColor="green" verticalAlignment="top" horizontalAlignment="right" borderRadius="25" height="50" width="50" borderWidth="1" borderColor="#333333">
	</StackLayout>
</GridLayout>
```

**Comment by shabib3** [comment]
@tsonevn - this isn't solving it...both of the event raise on `tap`...It means that it still invoke the `tapRed()` function when I `touch` the  green button...

**Comment by tsonevn** [comment]
Hi @shabib3,
 I tested the suggestion with your [Playground ](https://play.nativescript.org/?template=play-ng&id=cm9ZGQ&v=2) project on iOS 11.3, and the tap and touch events are executed separately.
Please review the attached link and check if I am missing something.

**Comment by shabib3** [comment]
@tsonevn - Ok so two things:
1. I saw your example and I saw that it works great...but somehow I cannot figure it out why it didn't work for me - [here it a video of my project](https://www.youtube.com/watch?v=0n37FGXzdCE&feature=youtu.be)
2. I solved it by putting the event registration inside the container - [like here](https://play.nativescript.org/?template=play-ng&id=cm9ZGQ&v=3)
it seems like not the prettiest workaround, but I can accept it...if you have any idea to improve it I would love to hear! :)

Thanks!

**Comment by tsonevn** [comment]
Hi @shabib3,
I checked the video and, however, I can not find what the difference in your project and the suggestion that I have shown to you. Regarding that,  I would suggest making a sample project while using the same layout structure as it is used in your project and could be used for debugging.
