### ISSUE TITLE
Adding RadCalender plugin gives build error

### ISSUE THREAD

**Issue by pankajjjpr** [NativeScript/NativeScript#5688]
I amnew to Nativescript.

I tried to add a plugin named RadCalender "nativescript-ui-calendar". after adding this plugin into my app, i got below error:

Execution failed for task ':app:transformClassesWithDexForF0F1F2F3F4Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/telerik/android/common/BuildConfig;

Please give any suggestion and if you need any file info then please let me know.

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#621
