### ISSUE TITLE
invalid animation curve slideRight

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#5689]
_From @aaayushsingh on April 16, 2018 12:29_

### Did the error happen while the app was being constructed? (buildtime error)
NO

### Did the error happen while the app was executing? (runtime error)
Yes

[this is the error log.](https://pastebin.com/vc2KbrRb)

### Please tell us how to recreate the issue in as much detail as possible.

1. create a new application
2. add a page for navigation
3. in the exports.pageLoaded, add the following code
```
const navigationEntry = {
    moduleName: "main-page",
    animated: true,
    // Set up a transition property on page navigation.
    transition: {
      name: "slide",
      duration: 380,
      curve: "slideRight"
    }
  };
  const topmost = frame.topmost();
  topmost.navigate(navigationEntry);
```
4. run app

It crashes on android Oreo with error saying invalid animation curve slideRight.
Please note that the same code works fine on iOS, that is why I'm raising an issue in android runtime.

_Copied from original issue: NativeScript/android-runtime#1009_

**Comment by aaayushsingh** [comment]
NOTE: This is only reproducible on android devices. The same code produces no issues on iOS devices and emulators.

**Comment by NickIliev** [comment]
@aaayushsingh the thing is that you are passing `slideRight` as value for the `curve` argument and not for the `name`argument. The `curve` is of type [AnimationCurve](https://docs.nativescript.org/api-reference/modules/_ui_enums_.animationcurve) while the supported animation types are provided via `name` argument and are listed here (e.g, `slide` and `slideRight` are two different types).

The curve explained from [the documentation section](https://docs.nativescript.org/core-concepts/navigation#navigation-transitions)

> The curve property lets you specify the animation curve of the transition. Possible values are contained in the AnimationCurve enumeration...

For example (using TypeScript)
```TypeScript
import { topmost } from "ui/frame"
import { AnimationCurve } from "ui/enums";

export function navigateWithSlideRight() {
    const navigationEntry = {
        moduleName: "main-page",
        animated: true,
        // Set up a transition property on page navigation.
        transition: {
            name: "slideRight",
            duration: 380,
            curve: AnimationCurve.easeIn
        }
    };
    const frame = topmost();
    frame.navigate(navigationEntry);
}
```
