### ISSUE TITLE
Change Observable API to return Constructor

### ISSUE THREAD

**Issue by burkeholland** [NativeScript/NativeScript#569]
The current API for an observable feels a bit awkward. Right now, the constructor is exported as the `Observable` property resulting in...

    var observable = require('data/observable');

    var model = new observable.Observable({});

Typing (nearly) the exact same thing twice feels kinda nuts, so I generally default to `observableModule`, but then it looks out of place with all of the other tns_modules, and results in inconsistencies in the way tns modules are referenced.

    var http = require('http');
    var dialogs = require('ui/dialogs');
    var observableModule = require('data/observableModule');

Is it possible to return the constructor for an observable so that it can be used without reference to an inner creation function?

    var Observable = require('data/observable');
    var ObservableArray = require('data/observable-array');

    var model = new Observable({});
    var modelThings = new ObservableArray([]);

**Comment by enchev** [comment]
Hi Burke,

It is possible however we've decided to do this only for modules with no classes (like, http, fetch, etc. where we have just functions as exports) and for modules with classes to export every class separately. On the other hand with ES6 you can have to following syntax:

import {Observable} from "data/observable";
var model = new Observable({});

Let us know what you think!

Thanks

**Comment by ligaz** [comment]
If we export single values we might want to do this with [`default export`](https://github.com/Microsoft/TypeScript/issues/2242). Not sure what will be the benefit though.

**Comment by PanayotCankov** [comment]
I think in ES6 you can use both default and named exports to mix and match. Burk's case then can be covered by making the Observable a default export, but also keeping the PropertyChangedData present in this module as named export.

Currently you can also:
``` JavaScript
var Observable = require("data/observable").Observable;
var o = new Observable();
```

**Comment by atanasovg** [comment]
The `observable` module is not the only such case, quite the opposite - we have this same convention for all the modules which expose a class (constructor function). So, if we want to make some change on this matter, we need to do it across all modules. My opinion is the ES6 declaration (as @enchev pointed)

```javascript
import {Observable} from "data/observable";
var model = new Observable({});
```

provides an elegant way to mitigate this issue.

**Comment by burkeholland** [comment]
I like the ES6 solution and it sounds to me like that's the best option.

Thanks all!
