### ISSUE TITLE
Component tns-core-modules & tns-android & tns-ios is not installed

### ISSUE THREAD

**Issue by Juliusdz** [NativeScript/NativeScript#5690]
Node v9.11.1
macOS High Sierra
`tns-version - 4.0.0`
Package.json:
`"version": "4.0.0"`
And there are no `tns-android` nor `tns-ios`. Instead:
```
  "nativescript": {
    "platforms": {
      "ios": "3.0.0",
      "android": "3.0.0"
    }
  },
```
I have tried to install iOS and Android - `ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)"` and got bunch of errors that Android and Xcode are not installed correctly. Setting up Xcode's Preferences > Locations > Command Line Tools helped to finish installation on next try. Then `tns-doctor` shows that "No issues were detected", but you can see bellow that tns-core-modules, tns-android and tns-ios is not installed. 

> ✔ Your ANDROID_HOME environment variable is set and points to correct directory.
> ✔ Your adb from the Android SDK is correctly installed.
> ✔ The Android SDK is installed.
> ✔ A compatible Android SDK for compilation is found.
> ✔ Javac is installed and is configured properly.
> ✔ The Java Development Kit (JDK) is installed and is configured properly.
> ✔ Xcode is installed and is configured properly.
> ✔ xcodeproj is installed and is configured properly.
> ✔ CocoaPods are installed.
> ✔ CocoaPods update is not required.
> ✔ CocoaPods are configured properly.
> ✔ Your current CocoaPods version is newer than 1.0.0.
> ✔ Python installed and configured correctly.
> ✔ The Python 'six' package is found.
> No issues were detected.
> ✔ Getting NativeScript components versions information...
> ✔ Component nativescript has 4.0.0 version and is up to date.
> ✖ Component tns-core-modules is not installed.
> ✖ Component tns-android is not installed.
> ✖ Component tns-ios is not installed.

Running `tns info` showed:
`⚠ Update available for component tns-core-modules. Your current version is 3.4.1 and the latest available version is 4.0.0.` so `tns-update` fixed the "Component tns-core-modules is not installed." error  and `tns-info`:

> ✔ Getting NativeScript components versions information...
> ✔ Component nativescript has 4.0.0 version and is up to date.
> ✔ Component tns-core-modules has 4.0.0 version and is up to date.
> ✖ Component tns-android is not installed.
> ✖ Component tns-ios is not installed.

Now after app created if I run `tns run android` I get:

```
Cannot find connected devices.
Emulator start failed with: Cannot resolve the specified connected device by the provided index or identifier. To list currently connected devices and verify that the specified index or identifier exists, run 'tns device'.
To list currently connected devices and verify that the specified identifier exists, run 'tns device'.
To list available emulator images, run 'tns device <Platform> --available-devices'.
```

But `tns run ios` starts the emulator. and `tns info`:

> ✔ Getting NativeScript components versions information...
> ✔ Component nativescript has 4.0.0 version and is up to date.
> ✔ Component tns-core-modules has 4.0.0 version and is up to date.
> ✖ Component tns-android is not installed.
> ✔ Component tns-ios has 4.0.1 version and is up to date.

**Comment by Juliusdz** [comment]
Looks like now I get also Android emulator after I created it manually:

```
$ cd $ANDROID_HOME/tools/bin
$ ./sdkmanager "system-images;android-23;google_apis;x86"
$ ./sdkmanager --licenses
$ avdmanager create avd -n test -k "system-images;android-25;google_apis;x86"
```

Now I run `tns run android` and emulator appears. 

Not sure why it didn't worked - seems I need to download the emulator package even though `sdkmanager --list` gives a list of installed packages and one of them was:

`system-images;android-25;google_apis;x86              | 12          | Google APIs Intel x86 Atom System Image`

**Comment by tsonevn** [comment]
Hi @Juliusdz,
While following the provided info I am assuming that you were able to fix the issues, and now you can create and build NativeScript project.

Regarding `Component tns-android is not installed.` issue.
Make sure that the `platform/android` folder exists in your project. If it is missing run `tns platform add android` command and again `tns info`. Then the Warning should disappear.

**Comment by Juliusdz** [comment]
@tsonevn - yep, seems its all good, so I close this. Thanks!

**Comment by abdul-elah-js** [comment]
where is the $ANDROID_HOME folder located ? couldn't find it !

**Comment by tsonevn** [comment]
HI @abdul-elah-js,
`$ANDROID_HOME` is a global variable, which contains the path to Android SDK folder. You can check [this](https://docs.nativescript.org/start/ns-setup-os-x#advanced-setup-steps) section from docs, where it is described, how to setup this variable as well.

**Comment by Castor243** [comment]
Hi @Juliusdz .
That seems not work for me. can you help me please.

**Comment by tsonevn** [comment]
Hi @Castor243,
Please provide more info about the issue, you are facing.

**Comment by bruceherve** [comment]
I am having the same issue here despite tns doctor indicating that everything is fine: 
![tns-doctor](https://user-images.githubusercontent.com/35220130/56752783-5d990280-6789-11e9-8703-9ceb50783bf3.png)
Vtx is supported on my machine as well , here is the lscpu command:
![lscpu](https://user-images.githubusercontent.com/35220130/56752828-828d7580-6789-11e9-87ba-a07ed34ce13b.png)
And finally the grep --color vmx /proc/cpuinfo command: 
![vmx](https://user-images.githubusercontent.com/35220130/56752912-ad77c980-6789-11e9-98b5-78e909e044fb.png)

As you can see here I have a list of created devices using the avd manager
./avdmanager list 
![avdmanager](https://user-images.githubusercontent.com/35220130/56754726-05b0ca80-678e-11e9-9823-68fdf807ebc9.png)
However when I run tns device android  --available-devices I see none:
![nadroid-device](https://user-images.githubusercontent.com/35220130/56755117-0b5ae000-678f-11e9-9cc5-e68a1200644b.png)

Can someone help figure out whats wrong with my set up, I feel like every thing checks out yet I can't start an emulator at all. Thanks

**Comment by malyod4iki** [comment]
When i create a new avd, I have the below error: (Help me please)
Error: Package path is not valid. Valid system image paths are:ository...       
system-images;android-25;google_apis;x86_64
null
