### ISSUE TITLE
GPS location services time out issue

### ISSUE THREAD

**Issue by dbay920** [NativeScript/NativeScript#5691]
**GPS location services time out issue: Upon first run of app, location services are blocked until you allow app to use your location data. After you click allow, however, the service seems to be timed out and won't work until app is re-started. This seems to only be a problem on the home view.**

### Which platform(s) does your issue occur on?
**Both**

### Please provide the following version numbers that your issue occurs with:
- CLI: **3.4.3**
- Cross-platform modules: **3.4.1**
- Runtime(s): **Android: 3.4.2   iOS: 3.4.1**
- Plugin(s): "**nativescript-geolocation": "^3.0.0"    "nativescript-locate-address": "^1.0.2"**

### Please tell us how to recreate the issue in as much detail as possible.
**Occurs upon first launch after install, github repo here: https://github.com/dbay920/phn-app/tree/master/MyPHN**

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem. 
**I would imagine something to do with my app's [home.component.ts file](https://github.com/dbay920/phn-app/edit/master/MyPHN/app/home/home.component.ts)**

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-geolocation#126
