### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [NativeScript/NativeScript#5695]
Hello! I would like to collaborate with this project by providing a _free_ new logo that suits with the project! Let me know if interested so we can get in touch! Cheers.

**Comment by pedromorgan** [comment]
**{N}** is cool for me.. cos its native to markdown also

https://github.com/NativeScript/docs/issues/1131

**Comment by pedromorgan** [comment]
Needs to be in SVG
and new {n} has log creation etc

**Comment by EmilStoychev** [comment]
Thanks for the enthusiasm @LuigiBaute Changing logo and colors is always exciting. What is the reason behind this proposal? The NativeScript logo is part of our overall branding spread through the website, marketing materials, swag, etc so changing the logo involves many other changes across the board. 

If you want to contribute to NativeScript, there are multiple ways to do so, fixing one of the "[good first issue](https://github.com/NativeScript/NativeScript/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)"  labeled issues being the most straight forward one.

**Comment by LuigiBaute** [comment]
My intention is to collaborate freely with your project, you could not change {N} and if you want the same color, but you can present a new proposal with the same orientation and go with your website, only if you want to use it. @EmilStoychev  @pedromorgan

**Comment by pedromorgan** [comment]
So can u make a **{N}** logo ? in svg ?

The thing in my mind is that the **N** at the moment is just an N with dodgy legs and a { superimposed..

so **{N}** or **{Ns}** or **{ns}** even..
so current N logo is only a logo, a png fraphic
- but we could use in text and a logo..
- So yea, keep going for the logo

lets the creative juices flourish...

**Comment by NickIliev** [comment]
@LuigiBaute @pedromorgan changing the logo would require a big resource in branding and currently, we are relying on the existing NativeScript logo which in my opinion is pretty awesome :)

Closing this issue as it is not related to NativeScript modules and framework. Use the docs repository for similar threads.
