### ISSUE TITLE
[ANDROID] TabBarItem icon size

### ISSUE THREAD

**Issue by devlfm** [NativeScript/NativeScript#5698]
Hi,

I'm facing a problem with iconSource on TabView:
![image](https://user-images.githubusercontent.com/11923375/38923897-7d31651c-42f3-11e8-9b23-107244de5493.png)

I was able to use font-icon on 2nd tab and the size is ok.
I couldn't find any place to set the icon size or TabViewItem size.

Thank you

**Comment by tsonevn** [comment]
Hi @devlfm,
You can try setting up the font-size for the TabView component. For example:
CSS
```
TabView{
   font-size: 18;
}
```

**Comment by devlfm** [comment]
Hi @tsonevn, that just works for font icon and not iconSource.

I eventually found the right icon size:
mdpi = 48x48 pixels, then the multipliers for ldpi(0.75) hdpi(1.5) xdpi(2) xxdpi(3) xxxdpi(4). **BUT!!** for ActionBar/TabBar the mdpi should be 32x32 with a transparent padding of 8px so the inner icon gets the true size of 24x24 > +info here: http://www.gargasz.info/android/

This is a pain is the a** because there are no official tool for batch all icons on a folder, and I have to make manually one by one..

**Comment by hanglearning** [comment]
I'm facing the similar issue for iOS. I'm trying to find the solution.
![image](https://user-images.githubusercontent.com/13460425/39092603-3e907d44-4644-11e8-90d5-fbd345465ef7.png)

**Comment by RamyTalal** [comment]
Same issue here.
![afbeelding](https://user-images.githubusercontent.com/188874/40005229-b9527d48-5797-11e8-81ac-3c9c2e987e43.png)

**Comment by tsonevn** [comment]
Hi @hanglearning @RamyTalal,
Can you provide more info about your problem? Also, it will help if you send us sample project, which could be used for debugging.
In the meantime make sure that the image, which you are loading, are defined in the App_Resources folder and follows the iOS and Android guidelines. More info could be found [here](https://docs.nativescript.org/ui/images#load-images-from-a-resource).

**Comment by RamyTalal** [comment]
Hello @tsonevn,

I followed this guide to create a Tab View: https://docs.nativescript.org/angular/cookbook/tab-view-ng
And I've placed the images in `drawable-nodpi`, the images are converted from svg to png. 

The problem is that I can change the dimensions in the `<Image>` tag, but there is no such flexibility with tabs.

**Comment by tsonevn** [comment]
Hi @RamyTalal,
The TabView component follows the design guidelines required by both platforms Android and iOS. Regarding that, both platforms do not provide any straightforward functionality, which can allow setting up further styling options to the icons in the TabView component. Regarding that, if you need the images in the tab to be scaled properly on the screen, you should define the needed images in the [App_Resources](https://docs.nativescript.org/ui/images#load-images-from-a-resource) folder and use them in the component.

**Comment by RamyTalal** [comment]
@tsonevn so I also need to place the images in the other drawable directories? And the scaling happens automatically?

**Comment by NickIliev** [comment]
@RamyTalal yep on Android, you should provide differently scaled images via [the drawable resources](https://developer.android.com/guide/topics/resources/drawable-resource) and [on iOS you could use scale factor](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/image-size-and-resolution/) for your resources images

**Comment by patrikengborg** [comment]
Thanks @devlfm your info got me on the right track. Adobe XD lets you batch-export images to all different sizes required by both iOS and Android, so that takes away a bit of the pain in the assy-ness at least.
![screen shot 2019-02-28 at 17 45 47](https://user-images.githubusercontent.com/5710602/53582901-bf216400-3b80-11e9-92b3-a41a22d86534.jpg)

**Comment by geilix10** [comment]
@patrikengborg @devlfm 
Found a another simple way to convert a .png file to all android sizes. (For those who do not want to download Adobe XD). 
Just open Android Studio create an empty project and do a right click on the folder "res" and click "Add Image Asset". There you can choose an image and convert it to all sizes with some more options than in Adobe XD. 

<img width="1023" alt="Screenshot 2019-09-19 at 10 47 58" src="https://user-images.githubusercontent.com/16301998/65229072-e9f6e980-dacb-11e9-877a-bd07c1bdb408.png">
