### ISSUE TITLE
WARNING: The Python 'six' package not found. 

### ISSUE THREAD

**Issue by obiwankenoobi** [NativeScript/NativeScript#5699]
after installing NativeScript on my macos using 
`ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)"`
I ran into error while typing `tns doctor` which tells me 
`WARNING: The Python 'six' package not found. ` and when I trying to install six by `pip install six`
I get the message : `Requirement already satisfied: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (1.4.1)
` so there is `six` installed but yet it wont let me move on because of it

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3534
