### ISSUE TITLE
Binary data support for fetch and XMLHttpRequest

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#570]
https://fetch.spec.whatwg.org/#dom-body-arraybuffer
https://xhr.spec.whatwg.org/

**Comment by satish-pokala** [comment]
writesync is not working with binary data any update on this ?

**Comment by kumaran-dena** [comment]
Hey @enchev & @NickIliev  Any update on this feature request?

May i know when we all can expect this feature avail?

Issue i have faced and my personal need of this feature!
I need to download the byte array from the server through http post api call. The byte array will be hold different type of attachments files/documents which will sizes around 60 to 100 MB's. Once i download & decompress the byte array to local file system then only i can proceed further in my application.

Still i cannot get any proper solution/idea on this. I got stucked in this step. I got confused with this.

Can you people suggest me anything in this moment !!

**Comment by caiusCitiriga** [comment]
Any news on this?

**Comment by surdu** [comment]
This was fixed in #7707
