### ISSUE TITLE
Is there a way to use esnext for ios?

### ISSUE THREAD

**Issue by AshleyCao** [NativeScript/NativeScript#5701]
Hi, 
I am still trapped at async&wait function for ios. 
After searching and looking through all relative issues. Still cannot find proper solution. 
(tried suggestions in# #5199 #1611) 
So, back from the beginning. 
Here is my tsconfig.json 
`{
    "compilerOptions": {
        "module": "commonjs",
        "target": "esnext",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": false,
        "noEmitOnError": true,
        "sourceMap": false,
        "noImplicitReturns": true,
        "lib": [
            "es6",
            "dom"
        ],
        "baseUrl": ".",
        "paths": {
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
}`
I target it to esnext since I am using some functions in new version( such as =>, async and even sort. maybe more later)
But apparently, project stopped at async. 
**Above ts setting works for Android perfectly.**
So my questions are:
1. Is there a comprehensive solution to use async and function from es6 or above(or use es7 properly coz async is in es7) for ios?
2. Is there some tutorial document about typescript in NS?

Thank you

**Comment by NickIliev** [comment]
There is runtime limitation on iOS for using async/await in plain JavaScript so we are officially not supporting `esnext`. The solutions discussed are basically for downcompiling Typescript (with async/await) to JavaScript ES5. I haven't use async/await in a project recently but perhaps you could try the [tslib helper published ](https://github.com/NativeScript/NativeScript/issues/1611#issuecomment-352147673) by @m-abs


To create basic TypeScript project you could directly use one of [our TS tempaltes](https://github.com/NativeScript?utf8=%E2%9C%93&q=template+ts&type=&language=).
For example

```
tns create myApp --tsc

// or pass the specific temapte name with `--template` flag

tns create myApp --template template-drawer-navigation-ts
```

**Comment by AshleyCao** [comment]
@NickIliev Can I 'target' it es6? 
Is ES6 still not supported by both iOS and Android runtimes ? 
there are still some features I would like to use in es6 and if typescript ( mine is 2.7.2) can transpile to es5, does that means all features from es6 can be transpiled?
For example, array slice() function ca only be used in es6?

**Comment by NickIliev** [comment]
@AshleyCao yes, virtually anything from TypeScript can be transpiled - you [can safely use `slice` in TS](https://github.com/NativeScript/NativeScript/search?utf8=%E2%9C%93&q=slice&type=) or `async/await` or decorators or interfaces.  In my opinion, using TypeScript is the better choice as it  provides an extended language options and at the same time is more readable and more safer when used with typings.

**Comment by AshleyCao** [comment]
@NickIliev Good to know. Thank you, I will test it
