### ISSUE TITLE
using js file without xml to navigate crashes app on ios

### ISSUE THREAD

**Issue by aaayushsingh** [NativeScript/NativeScript#5702]
### Tell us about the problem
navigating using a js file not associated to any xml causes app crash on iOS

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0-2018-04-05-11381
- Cross-platform modules: 4.0.0
- Runtime(s): iOS : 4.0.1
- Plugin(s): NA

### Please tell us how to recreate the issue in as much detail as possible.
1. create an app and create a js file (let testing.js)
2. in the js file, paste the following
```
var frameModule_1 = require("ui/frame");
function navigante() {
  var topmost = frameModule_1.topmost();
  topmost.navigate("page/detail-page/detail-page");
}
navigante();
```
where page/detail-page/detail-page is some valid path to an xml file (detail.page.xml exists)
3. ```tns run android``` will work fine and load this page when the config file is loaded.
4. ```tns run ios``` crashes with the following error
```
JS ERROR TypeError: undefined is not an object (evaluating 'topmost.navigate')
```

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```
var frameModule_1 = require("ui/frame");
function navigante() {
  var topmost = frameModule_1.topmost();
  topmost.navigate("page/detail-page/detail-page");
}
navigante();
```

**Comment by aaayushsingh** [comment]
[link to app on NS playground](https://play.nativescript.org/?template=play-js&id=MKP2Y4&v=2). Also crashing on android on playground.

**Comment by NickIliev** [comment]
@aaayushsingh this is expected error as you are calling `topmost()` method of the `Frame` before the application has started. The method is explicitly called in `test.js` which is required before any frame logic is applied in your application (before application `start`.

Here you can find a [revised Playground demo](https://play.nativescript.org/?template=play-js&id=MKP2Y4&v=3) showing how the same method can be exported and used at will.

**Comment by NickIliev** [comment]
@aaayushsingh yes, you can use the `loaded` event on any `View` (e.g. `Page`, `StackLayout`, `GridLayout`, etc.)
```XML
<Page loaded="onPageLoaded">
    <StackLayout loaded="onStackLoaded" >
    </ StackLayout>
</Page>
```

```JavaScript
exports.onPageLoaded = function(args) {
    const page = args.object;
    // the page has loaded
};

exports.onStackLoaded = function(args) {
    const stack = args.object;
    // the stack has loaded
};
```
