### ISSUE TITLE
PlatformModule Cookbook Docs need updating

### ISSUE THREAD

**Issue by codethebeard** [NativeScript/NativeScript#5707]
The platform module cookbook documentation is missing a few other properties that are now available. https://docs.nativescript.org/cookbook/platform

I would like to update this documentation to include the following additional properties:

- `platformModule.device.language`
- `platformModule.device.manufacturer`
- `platformModule.device.region`
- `platformModule.device.uuid`
- `platformModule.screen.mainScreen.heightDIPs`
- `platformModule.screen.mainScreen.heightDIPs`

**Comment by NickIliev** [comment]
@codethebeard thank you for your suggestions - indeed we need to add examples for this properties.
We are currently re-working the whole Cookbook experience and the revised examples will be built from [this application](https://github.com/NativeScript/nativescript-sdk-examples-js). [The nex `platform` module example is already containing the newly introduced properties](https://github.com/NativeScript/nativescript-sdk-examples-js/blob/master/app/platform/basics/basics-page.js#L11-L23). Expect the new Cookbook examples to go live in a matter of few days.

Once again thank you for your interest and will to contribute! If you wish to add new info in the documentation you can use [this repo](https://github.com/NativeScript/docs/issues) as a reference for wanted features.
