### ISSUE TITLE
Time Picker Restrict Date to Current date

### ISSUE THREAD

**Issue by devsufyan** [NativeScript/NativeScript#5713]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
yes
### Tell us about the problem
I have used the time pciker in my agular native script app. when i select the time picker and print seleted time it give me below date object 
`JS: Sun Dec 31 1899 14:36:00 GMT+0000 (GMT)`
date is set to 1899 which is a wrong thing. i want it to be the current date

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
tns 3.3.1

just add time picker in app and print the time and date in console please see below code
```
import { TimePicker } from "ui/time-picker";
onPickerLoaded(args) {`
    let timePicker = <TimePicker>args.object;
      let today = new Date();
          let hour = today.getHours();
          let minute = today.getMinutes();
          
          timePicker.hour = hour;
          timePicker.minute = minute;
          console.log(timePicker.hour);
          console.log(timePicker.time);
  //}, this);
  }

```
html
`<TimePicker class="date-time-pickers" (loaded)="onPickerLoaded($event)"
                    verticalAlignment="center" #optionsStartTime ></TimePicker>`

**Comment by EddyVerbruggen** [comment]
Note that you can correct the date by doing this at after initializing the `today` variable in your `onPickerLoaded` function: `timePicker.time = today;`

**Comment by manoldonev** [comment]
@devsufyan I don't think the described behavior should be regarded as a bug within the TimePicker control. Generally it can be debated whether exposing a JavaScript Date value for a time picker was necessary in the first place but that's what we have now. The control is a **time** picker and the relevant data is correct with respect to the time component of the Date instance. Moreover, I am not sure why the current date should be treated in a more special way than the current base date (the epoch start date).
