### ISSUE TITLE
Game development

### ISSUE THREAD

**Issue by Alcadur** [NativeScript/NativeScript#5715]
I would like to start create game for android using NativeScript but I found only tutorial with PhysicsJS (https://www.nativescript.org/blog/first-steps-in-game-dev-with-nativescript) which is still in beta and last commit in repo was 3 years ago.  I was trying to use phaser.js or pixi.js but unfortunately I failed, even when using nativescript-nodeify.

For:
`import * as PIXI from 'pixi.js'`

Error:
`System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.theworldoflabyrinths/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to find module: "pixi.js", relative to: app/tns_modules/`

**Comment by tsonevn** [comment]
Hi @Alcadur,
First of all, thank you for your interest in NativeScript.
Currently, there is no plugin, which provides support for the phaser.js library. Regarding that, I can suggest creating a custom plugin, which provides support for phaser in NativeScript. For further info, you can review our this article in our [documentation ](https://docs.nativescript.org/plugins/building-plugins).
Also, you can contact the nativescript-nodeify author, which can help you in integrating the phaser while using the nativescript-nodeify.
