### ISSUE TITLE
setNativeSource possible breaking change in 4.0

### ISSUE THREAD

**Issue by bufke** [NativeScript/NativeScript#5717]
### Tell us about the problem

In <4.0 this code worked to get the package application icon

```
let nativeApp: android.app.Application = application.android.nativeApp;
let bundle = nativeApp.getPackageName();
let drawable = nativeApp.getPackageManager().getApplicationIcon(bundle);
fromNativeSource(drawable);
```

In 4.0 it fails because of this [commit](https://github.com/NativeScript/NativeScript/commit/58d61caf59ab340b9ab1762f3941d6bc3f8f744a) which adds a check

```
if (source && !(source instanceof android.graphics.Bitmap)) {
    throw new Error("The method setNativeSource() expects android.graphics.Bitmap instance.");
}
```

I didn't see a mention of this as a intended breaking change - so it may be an actual bug or just a lack of documented change. Or it's possible I'm abusing how images work and it just happened to work before by chance.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0
- Cross-platform modules: 4.0.0
- Runtime(s): Android 4.0.1

### Please tell us how to recreate the issue in as much detail as possible.

Add the code snippet to a project or see this plugin

https://gitlab.com/burke-software/nativescript-foss-sidedrawer

According to the typescript definitions `getApplicationIcon` returns a androidgraphicsdrawableDrawable. While fromNativeSource claims to accept `any` it actually only works with `android.graphics.Bitmap`.

Simply removing the `instanceof` check in the image-source.android.js file makes the app work again, successfully retrieving the app's package icon and displaying it.

**Comment by vchimev** [comment]
Hey @bufke,

This [check](https://github.com/NativeScript/NativeScript/blob/4.0.0/tns-core-modules/image-source/image-source.android.ts#L142) is intedned and its lack was a bug as, in fact, the `fromNativeSource` works only with `android.graphics.Bitmap`. This is mentioned in the [comment](https://github.com/NativeScript/NativeScript/blob/4.0.0/tns-core-modules/image-source/image-source.d.ts#L144) of its definition.

I took a look at the [nativescript-foss-sidedrawer](https://gitlab.com/burke-software/nativescript-foss-sidedrawer) plugin and noticed that actually for Android the `ImageSource` is never used in favour of its [native representation](https://gitlab.com/burke-software/nativescript-foss-sidedrawer/blob/master/src/nativescript-sidedrawer.android.ts#L27) which happend to be satisfied by the `android.graphics.drawable.Drawable` object.
