### ISSUE TITLE
Documentation autogen + future

### ISSUE THREAD

**Issue by pedromorgan** [NativeScript/NativeScript#5719]
So this is a big question, and future planning thought. Snag is that the 

- api docs (autogenerated) are in one place - https://docs.nativescript.org/api-reference/
- and the commentary supporting docs elsewhere https://docs.nativescript.org/api-reference/

eg a button
- api = https://docs.nativescript.org/api-reference/modules/_ui_button_
- cookbook = https://docs.nativescript.org/cookbook/ui/button
-- But cookbook docs are in sdk examples and not in the /docs repos ?

So would it not be better to put the examples code in the source instead eg button.ts ??

this would avoid replication, and also allow versioing..

The only snag is we would need to update the api serialiser frontend to do this... ??

I've been around all the docs format, from docbook, sphinx/rst, jekyll/md (doxygen is still best all rounder)

# file-system example
- cookbook = https://docs.nativescript.org/cookbook/file-system
- https://docs.nativescript.org/api-reference/modules/_file_system_
- https://docs.nativescript.org/api-reference/classes/_file_system_.file

The former bascically lists the method in the afters...

So modifying docs in the source would be the .d file as I understand(newbie to ts)
https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/file-system/file-system.d.ts

So basic question is....
- should the code examples + docs  be in the source files (maybe an .md alongside)
- or as currently seperate stuff, with one in markdown/jekyll and other done by ?

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/docs#1145
