### ISSUE TITLE
How to disable console.logs in release builds?

### ISSUE THREAD

**Issue by smartsanja2013** [NativeScript/NativeScript#5722]
I have to disable all the `console.logs` in release build. I used following commands to generate release builds

```
tns prepare release --ios
tns build ios --release

tns build android --release
```
But console.logs still can be seen in the ios and android consoles. I have tried `enableProdMode();` in the `main.ts` file as well. Still the logs can be seen.

How can I disable the logs for release/prod builds?

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/android-runtime#1024
