### ISSUE TITLE
How to prevent Tapjacking in Android app?

### ISSUE THREAD

**Issue by smartsanja2013** [NativeScript/NativeScript#5725]
We can set the `filterTouchesWhenObscured` to true. Or implement the method `onFilterTouchEventForSecurity()` in native android apps to prevent Tapjacking. How I can do it in nativescript? Please share if anyone has done that before

**Comment by tsonevn** [comment]
HI @smartsanja2013,
If I understand you correctly, you want to display window and prevent it's closing. If this is the case, you can review the provided solution in [this thread](https://stackoverflow.com/questions/45689520/nativescript-angular-preventing-modal-closing-on-background-tap), where it is described how it could be done for the modal page.
For any further questions, please use our [forum ](https://discourse.nativescript.org/) or [StackOverflow ](https://stackoverflow.com/questions/tagged/nativescript) thread.

**Comment by smartsanja2013** [comment]
@tsonevn Sorry for the lack of information in the question. My question is regarding nativescript-loading-indicator plugin. Our security team complains that the android loading indicator is vulnerable for [tapjacking](https://www.xda-developers.com/how-tapjacking-made-a-return-with-android-marshmallow-and-nobody-noticed/) 
What that means is, when the loading indicator display as an overlay, it still responds to tap events.
FYI: I have set the property `cancelable: true` in the loading indicator. But still it accepts tap events.
