### ISSUE TITLE
Set allowsInlineMediaPlayback for WebView

### ISSUE THREAD

**Issue by erikandershed** [NativeScript/NativeScript#5726]
### Did you verify this is a real problem by searching the [NativeScript Forum]
yes

### Tell us about the problem
Where do I set the property "allowsInlineMediaPlayback" in NativeScript for a WebView? Android has alos similar function, where do I set it?

### Which platform(s) does your issue occur on?
iOS/Android

### Please provide the following version numbers that your issue occurs with:
NativeScript 3.4

### Please tell us how to recreate the issue in as much detail as possible.
In Xcode you need set allowsInlineMediaPlayback for WebView to play a video inline. I can't find a way to set this settings to NativeScript WebView.

**Xcode**
`theConfiguration!.allowsInlineMediaPlayback = true;
 theConfiguration!.mediaPlaybackRequiresUserAction = false;
 self.wkWebView = WKWebView(frame: self.getFrame(), configuration: theConfiguration!)`

**NatieScripte**
`if (page.ios) {
    webView.ios.allowsInlineMediaPlayback = true;
    webView.ios.mediaPlaybackRequiresUserAction = false;
}`

**Comment by tsonevn** [comment]
Hi @erikandershed,
To enable the inline video in iOS you should set up `allowsPictureInPictureMediaPlayback` and `allowsPictureInPictureMediaPlayback` to `true` before initialising the WebView component. Currently, this could happen only if you add those properties directly in the `tns-core-modules/ui/web-view-ios.js` file. For example:
```
var WebView = (function (_super) {
    __extends(WebView, _super);
    function WebView() {
        var _this = _super.call(this) || this;
        var configuration = WKWebViewConfiguration.new();
        _this._delegate = WKNavigationDelegateImpl.initWithOwner(new WeakRef(_this));
        var jScript = "var meta = document.createElement('meta'); meta.setAttribute('name', 'viewport'); meta.setAttribute('content', 'initial-scale=1.0'); document.getElementsByTagName('head')[0].appendChild(meta);";
        var wkUScript = WKUserScript.alloc().initWithSourceInjectionTimeForMainFrameOnly(jScript, 1, true);
        var wkUController = WKUserContentController.new();
        wkUController.addUserScript(wkUScript);
        configuration.userContentController = wkUController;
        configuration.allowsInlineMediaPlayback = true;
        configuration.allowsPictureInPictureMediaPlayback = true;
        configuration.preferences.setValueForKey(true, 'allowFileAccessFromFileURLs');
        _this.nativeViewProtected = _this._ios = new WKWebView({
            frame: CGRectZero,
            configuration: configuration
        });
        return _this;
    }
....
}
```
Regarding that this seems to be a perfect candidate for creating a new property which allows this functionality. More about our contribution guidelines can be found [here](https://www.nativescript.org/contribute).

Regarding Android, you can review the provided solution in their [documentation](https://developer.android.com/reference/android/webkit/WebView.html).

**Comment by erikandershed** [comment]
Thanks it works!

**Comment by NickIliev** [comment]
Closing the feature as it is iOS-specific and the provided workaround (via accessing the native API) is resolving the issue.

**Comment by erikandershed** [comment]
Hey! I can find "tns-core-modules/ui/web-view-ios.js" to be able to change this. It seems like NativeScript have changed in the later versions.

**Comment by erikandershed** [comment]
I did fund this here:
node_modules/@nativescript/cure/ui/web-view/index.ios.js


`createNativeView() {
        const jScript = "var meta = document.createElement('meta'); meta.setAttribute('name', 'viewport'); meta.setAttribute('content', 'initial-scale=1.0'); document.getElementsByTagName('head')[0].appendChild(meta);";
        const wkUScript = WKUserScript.alloc().initWithSourceInjectionTimeForMainFrameOnly(jScript, 1 /* AtDocumentEnd */, true);
        const wkUController = WKUserContentController.new();
        wkUController.addUserScript(wkUScript);
        const configuration = WKWebViewConfiguration.new();
        configuration.userContentController = wkUController;
        **configuration.allowsInlineMediaPlayback = true;
        configuration.allowsPictureInPictureMediaPlayback = true**;
        configuration.preferences.setValueForKey(true, 'allowFileAccessFromFileURLs');
        return new WKWebView({
            frame: CGRectZero,
            configuration: configuration,
        });
    }`

**Comment by ngunner** [comment]
Thank you @davecoffin and all. Has there been any progress on exposing these configurations on WebView? Cheers!

**Comment by davecoffin** [comment]
Yea I believe this is in core now! Right @NathanWalker ?

**Comment by NathanWalker** [comment]
Correct it went in with 8.4.0
https://github.com/NativeScript/NativeScript/releases/tag/8.4.0-core
