### ISSUE TITLE
after minimize several times app event not work 

### ISSUE THREAD

**Issue by A1Gard** [NativeScript/NativeScript#5730]
I was compile a new app with native-vue-template by this code:
`
 tns create fireApp --template nativescript-vue-template`

and I try to compile and install in my phone.

but after after minimize several times app event not work.

Problem is detect on **andriod** platform, I don't check on ios app.

```
$ tns --version
4.0.0
```
My phone is Nexus p6 and andriod 7.1.1.
Sdk comile is latest sdk install with last andriod studio version.

an here is video attached:

![ezgif-3-8755d4642d](https://user-images.githubusercontent.com/9222481/39168377-da9f6a6e-47a8-11e8-9cec-ac790d9e0156.gif)

**Comment by tsonevn** [comment]
This issue was moved to nativescript-vue/nativescript-vue#196
