### ISSUE TITLE
Memory leaks with CSS animation 

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#5731]
_From @RoyiNamir on April 20, 2018 6:33_

I've created a simple new project via `tns create bbb --ng`

![image](https://user-images.githubusercontent.com/2842123/39033892-edd54baa-447c-11e8-9a69-024e90c17b5c.png)

Added a CSS animation class via `animate.css` library : 

**app.css**
```
@import '~nativescript-theme-core/css/core.light.css';
@import "~animate.css/animate.min.css";

.breath {
    animation-name: pulse;
    animation-duration: 2s;
    animation-iteration-count: infinite;
    animation-fill-mode: forwards;
}

```

And now I've created 7 images with that class. Some with manual images and some are via `*ngFor` : 

![image](https://user-images.githubusercontent.com/2842123/39033944-247af402-447d-11e8-8b7f-a08f27626357.png)

This is the code for **items.component.html**

```
<ActionBar title="My App" class="action-bar"></ActionBar>
<GridLayout columns="*,*,*,*,*,*,*" rows="*">

    <StackLayout row="0" col="1"  >
        <Image class="breath " [src]="'~/images/hat00001.png'" stretch="aspectFit"></Image>
    </StackLayout>

    <StackLayout row="0" col="2"  >
        <Image class="breath " [src]="'~/images/hat00001.png'" stretch="aspectFit"></Image>
    </StackLayout>

    <Image *ngFor="let o of [1,2,3,4,5];let i = index;"
           [col]="i+3"
           [class]="'breath'"
          verticalAlignment="top"
           [src]="'~/images/hat0000'+(i+2)+'.png'"
           stretch="aspectFit"></Image>
</GridLayout>

```

**There's nothing else. No TS code ,  no nothing. Just this html and css.**

However  , while writing down this issue ^  , look at the memory consumption : 

![image](https://user-images.githubusercontent.com/2842123/39034024-777f0526-447d-11e8-8276-2bc5568797fa.png)

Started at : 

![image](https://user-images.githubusercontent.com/2842123/39034039-83f6e68e-447d-11e8-8c35-ecff4c1fa17f.png)

And now it's (keeps growing) : 

![image](https://user-images.githubusercontent.com/2842123/39034051-92f5d3f2-447d-11e8-9057-48f1a772524d.png)

**Attached project** : https://ufile.io/spicc

Video showing the ease growing leak : 

![video_2018-04-20_093614](https://user-images.githubusercontent.com/2842123/39034403-f21ba52c-447e-11e8-8d8a-d0a7323adfc1.gif)

_Worth to mention: I'm not talking about the jumps. I'm talking about the easy growing memory consumption_

**Eventually the app is shutdown due to out of memory**

Additional info : 

![image](https://user-images.githubusercontent.com/2842123/39034546-6da88444-447f-11e8-8544-516f44ce889d.png)

Update:  after 51 min -  it's  0.2 GB : 

![image](https://user-images.githubusercontent.com/2842123/39035747-d2c3c858-4483-11e8-8412-2081dd782b68.png)

This bug hurts  the ability to use NS with  games/continuous animations  (said to be supported with css animations).  :-(
Any workaround ?
BTW  it also happens with Angular animations. ( i've created a test and still there's also a leak with Angular animations).

_Copied from original issue: NativeScript/nativescript-angular#1291_

**Comment by NickIliev** [comment]
@RoyiNamir thank you for reporting this issue and providing the detailed description and information.
I can confirm that indeed the issue is reproducible and the memory leak is also observed in NativeScript Core application (`--tsc`).

Steps to reproduce:
- use the above Angular application or[ this one (Core with TypeScript)](https://github.com/NickIliev/NS-Issues-2018/tree/master/NativeScript/issue_5731_tsc)

**Comment by NickIliev** [comment]
Update: it seems chaning the animation count from `infinity` to some large number is causing larger memory leak
```
.breath {
    animation-name: pulse;
    animation-duration: 2s;
    animation-iteration-count: 100000;
    animation-fill-mode: forwards;
}
```

**Comment by RoyiNamir** [comment]
@NickIliev  Hi.  Thanks for update. To my understanding  , the problem is that the animation code is not reset ( after each iteration) , or not GC'ed. it happened to me also with large number of animation count instead of infinite.

**Comment by RoyiNamir** [comment]
Any progress on this one ? it really puts NS out of game/animations world  ...

**Comment by NickIliev** [comment]
Tested on my side [via this application](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/NativeScript/issue-5731) and Android profiler and the memory leak is now fixed. 

@RoyiNamir  @jogboms can you guys test with your own applications and verify that the fix is resolving the issue for your scenarios as well.

**Comment by RoyiNamir** [comment]
Hey @NickIliev .

Created another sample demo ( same code as above ^ ) : 6 animated hats : 

![image](https://user-images.githubusercontent.com/2842123/43989366-3b0f8fe8-9d51-11e8-8784-999fd464fdc8.png)


Package.json is [here](https://gist.github.com/RoyiNamir/6e6c988e1bb4412ff50b39825a53063f)


The app is doing nothing but animating 6 hats.

However look at memory consumption : 

# 4.9 seconds

![image](https://user-images.githubusercontent.com/2842123/43989378-810597f4-9d51-11e8-9c5e-174217c50435.png)


# 2 min

![image](https://user-images.githubusercontent.com/2842123/43989380-8cc37ed0-9d51-11e8-80a9-495d00f34376.png)


# 6 min

![image](https://user-images.githubusercontent.com/2842123/43989382-95e5badc-9d51-11e8-8c97-ab33ae82236d.png)


The graph clearly shows that there is still a leak .

![image](https://user-images.githubusercontent.com/2842123/43989392-c717e670-9d51-11e8-8d07-31e2c3139624.png)


The empty sample project i've used : https://ufile.io/8k0az

**Comment by NickIliev** [comment]
The bug seems to have resurfaced so I am reopening the issue.

**Comment by weijyewang** [comment]
any update on this issue?

**Comment by tsonevn** [comment]
HI @weijyewang,
Can you check if you will have the same issue while using the next modules version? Check the steps below:
1. `tns plugin remove tns-core-modules`
2. `tns plugin add tns-core-modules@next`
3. remove `platforms` folder 
4. rebuild the app `tns run <platform_name>`

**Comment by weijyewang** [comment]
@tsonevn I did not do any profiling, just tested on Samsung Galaxy S7.  I can feel some improvement, but after iterating indefinitely for changing the background color from red to transparent for over 10 minutes, the entire app experience some serious lag. Restarting the app will makes things smooth again, so I guess the memory problem still persist.

**Comment by SkupeZZ** [comment]
To me it gets even worst if you place the animated element behind a 
`*ngif="something"` 
or
 ` <ng-template></ng-template>`

If I hide it at run time, the CPU continues to work as if the animated element was there, and RAM starts increasing fast.

**Comment by gogoout** [comment]
The current workaround is having a `animation-iteration-count: 10;` instead of `Infinity`

**Comment by RoyiNamir** [comment]
@adjenkov , i dont understand. Was this fixed ? If yes , in what version?

**Comment by ADjenkov** [comment]
@RoyiNamir this will be released officially as a patch version. It is also available in `tns-core-modules@rc` `and tns-core-modules@next`. You can take a look at the [fix](https://github.com/NativeScript/NativeScript/pull/6930) for more specific info related to the issue.

**Comment by mmeven** [comment]
Hello, 
I've observed this memory leak again. Using the same kind of app as the one mentioned earlier, I've witnessed a 10mb memory usage increase over 5 minutes using the Android profiler. Could someone confirm I'm not mistaken ?
