### ISSUE TITLE
java.lang.NullPointerException when closing app

### ISSUE THREAD

**Issue by b4rtt** [NativeScript/NativeScript#5733]
## Please, provide the details below:
Hi, I have problem with app crash when I am closing app by middle android button. I am getting this. It will be really hard to reproduce error because it's big application which is ready to publish to stores.
Problem is on Samsung Galaxy J3(2016) (j3xnlte), 1536MB RAM, Android 5.1. On other phones (other versions of Android it's without problem)

```
java.lang.NullPointerException: 
  at android.app.BackStackRecord$1.onPreDraw (BackStackRecord.java:1131)
  at android.view.ViewTreeObserver.dispatchOnPreDraw (ViewTreeObserver.java:1018)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2327)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1314)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:7057)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:829)
  at android.view.Choreographer.doCallbacks (Choreographer.java:606)
  at android.view.Choreographer.doFrame (Choreographer.java:576)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:815)
  at android.os.Handler.handleCallback (Handler.java:739)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:145)
  at android.app.ActivityThread.main (ActivityThread.java:6934)
  at java.lang.reflect.Method.invoke (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1404)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1199)
```

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
CLI: 4.0.1
Cross-platform modules: 4.0.1
Runtime(s): 4.0.1
Plugin(s): N/A

**Comment by tsonevn** [comment]
Hi @b4rtt,
Can you provide some more info about the problem and the project? The given information is not enough to investigate further the issue. You have mentioned that is is hard for reproduce, however it will help if you can isolate the problem in a sample project, which could be used for debugging.

**Comment by b4rtt** [comment]
@tsonevn It helps you if I send you project repository? As I said. My project is little bigger with multiple views, so I don't know how to reproduce problem and which part of code is wrong (If really is wrong?) Problem is only on some android versions.

**Comment by b4rtt** [comment]
@tsonevn I found that same problem on NS Discourse. 

https://discourse.nativescript.org/t/java-lang-nullpointerexception-attempt-to-read-from-field-int-android-app-fragment-mcontainerid-on-a-null-object-reference/5588

**Comment by tsonevn** [comment]
HI @b4rtt, 
Indeed it will help if you send us the project repository as well as the steps, which should be used for reproducing the issue.

**Comment by b4rtt** [comment]
@tsonevn Repository is here.

https://github.com/b4rtt/ns_android_bug

Problem is only on Android. Version 5.1.
Problem causing minimalizing app by center android button. (No closing)

**Comment by giorgi-abashidze** [comment]
I have same problem, also I have this error when i open image picker, on android.
I think it because when open image picker gallery page are showing and app goes to background like when you press middle android round button also app goes to background and then crashes

**Comment by b4rtt** [comment]
@giorgi-abashidze is it possible please?

**Comment by tsonevn** [comment]
Hi @b4rtt,
I reviewed the project and found that you have `"npm": "^5.7.1",` dependency in your project. Can you remove it from the project? Also, you are using the old `"nativescript-pro-ui": "3.4.1",` plugin, which is deprecated in favour of separate plugin for each of the components. You can review[ this article](https://docs.telerik.com/devtools/nativescript-ui/migration), where it is described, how to migrate to the new plugins.

**Comment by b4rtt** [comment]
Hi @tsonevn, 
thank you for your suggestions. Now it's updated in my repository. https://github.com/b4rtt/ns_android_bug


App still crashing when I minimalize it.

Here is my logcat.

I don't really understand it, but it looks that problem should be in Firebase plugin (@EddyVerbruggen). When I plugin removed, crashing stopped. Weird is that crashing is only on Android 5.1. Other versions working like a charm.

```
I/art     ( 9707): Not late-enabling -Xcheck:jni (already on)
D/FirebaseApp( 9707): com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
I/FirebaseInitProvider( 9707): FirebaseApp initialization successful
W/linker  ( 9707): libNativeScript.so: unused DT entry: type 0x6ffffffe arg 0x25d4
W/linker  ( 9707): libNativeScript.so: unused DT entry: type 0x6fffffff arg 0x3
I/TNS.Native( 9707): NativeScript Runtime Version 4.0.1, commit 5f6450733f6593cc634ed128ece466f87722c6ca
D/TNS.Native( 9707): JNI_ONLoad
D/TNS.Native( 9707): JNI_ONLoad END
I/FA      ( 9707): App measurement is starting up, version: 12211
I/FA      ( 9707): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
I/FA      ( 9707): To enable faster debug mode event logging run:
I/FA      ( 9707):   adb shell setprop debug.firebase.analytics.app cz.esports.skslovanbratislava
D/TNS.Native( 9707): Failed to load snapshot: dlopen failed: library "libsnapshot.so" not found
D/TNS.Native( 9707): V8 version 5.5.372.32
D/TNS.Native( 9707): lenNodes=94380, lenNames=869534, lenValues=1121245
D/TNS.Native( 9707): time=2
D/FirebasePluginCB( 9707): Unregistering the activity lifecycle callbacks...
D/FirebasePluginCB( 9707): Registering the activity lifecycle callbacks...
D/FirebasePlugin( 9707): onActivityResumed: Application has been started
I/FA      ( 9707): Tag Manager is not found and thus will not be used
D/OpenGLRenderer( 9707): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D/        ( 9707): HostConnection::get() New Host Connection established 0xa1b702e0, tid 9707
D/Atlas   ( 9707): Validating map...
I/JS      ( 9707): ANGULAR BOOTSTRAP DONE. 1490
D/skia    ( 9707): --- SkImageDecoder::Factory returned null
I/DynamiteModule( 9707): Considering local module com.google.android.gms.firebase_database:4 and remote module com.google.android.gms.firebase_database:6
I/DynamiteModule( 9707): Selected remote version of com.google.android.gms.firebase_database, version >= 6
W/ResourcesManager( 9707): Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
W/ResourcesManager( 9707): Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
D/        ( 9707): HostConnection::get() New Host Connection established 0xae85a100, tid 9734
I/OpenGLRenderer( 9707): Initialized EGL, version 1.4
W/OpenGLRenderer( 9707): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/EGL_emulation( 9707): eglCreateContext: 0xae967220: maj 2 min 0 rcv 2
D/EGL_emulation( 9707): eglMakeCurrent: 0xae967220: ver 2 0
D/OpenGLRenderer( 9707): Enabling debug mode 0
D/EGL_emulation( 9707): eglMakeCurrent: 0xae967220: ver 2 0
W/art     ( 9707): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
D/skia    ( 9707): --- SkImageDecoder::Factory returned null
D/skia    ( 9707): --- SkImageDecoder::Factory returned null
W/linker  ( 9707): libimagepipeline.so: unused DT entry: type 0x6ffffffe arg 0x2e4c
W/linker  ( 9707): libimagepipeline.so: unused DT entry: type 0x6fffffff arg 0x2
D/FirebasePlugin( 9707): onActivityPaused: Application has been stopped.
D/EGL_emulation( 9707): eglMakeCurrent: 0xae967220: ver 2 0
W/IInputConnectionWrapper( 9707): showStatusIcon on inactive InputConnection
D/AndroidRuntime( 9707): Shutting down VM
W/System.err( 9707): java.lang.NullPointerException: Attempt to read from field 'int android.app.Fragment.mContainerId' on a null object reference
W/System.err( 9707): 	at android.app.BackStackRecord$1.onPreDraw(BackStackRecord.java:1131)
W/System.err( 9707): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
W/System.err( 9707): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1970)
W/System.err( 9707): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
W/System.err( 9707): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
W/System.err( 9707): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
W/System.err( 9707): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
W/System.err( 9707): 	at android.view.Choreographer.doFrame(Choreographer.java:550)
W/System.err( 9707): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
W/System.err( 9707): 	at android.os.Handler.handleCallback(Handler.java:739)
W/System.err( 9707): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err( 9707): 	at android.os.Looper.loop(Looper.java:135)
W/System.err( 9707): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err( 9707): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 9707): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 9707): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
W/System.err( 9707): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
I/Process ( 9707): Sending signal. PID: 9707 SIG: 9
```

**Comment by shivgolani** [comment]
Getting Similar Error Guys Any update on this?


Exception java.lang.NullPointerException: Attempt to read from field 'int android.app.Fragment.mContainerId' on a null object reference
android.app.BackStackRecord$1.onPreDraw (BackStackRecord.java:1131)
android.view.ViewTreeObserver.dispatchOnPreDraw (ViewTreeObserver.java:944)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2000)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1084)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:5990)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:767)
android.view.Choreographer.doCallbacks (Choreographer.java:580)
android.view.Choreographer.doFrame (Choreographer.java:550)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:753)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:135)
android.app.ActivityThread.main (ActivityThread.java:5343)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:905)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:700)

**Comment by NickIliev** [comment]
@shivgolani  please provide the needed info in [your original issue](https://github.com/NativeScript/NativeScript/issues/5756)

**Comment by tsonevn** [comment]
Hi @b4rtt,
The problem, which you are facing might be related to the one reported in [issue #5674](https://github.com/NativeScript/NativeScript/issues/5674).
The fix for issue 5674 is already available in `@next` modules. Can you try on your side, whether you will have the same problem with next modules?

1. `tns plugin remove tns-core-modules`
2. `tns plugin add tns-core-modules@next`
3. `tns platform remove android`
4. `tns platform add android`
5. `tns run android`

**Comment by b4rtt** [comment]
@tsonevn It's working like a charm! Thank you so much.
