### ISSUE TITLE
WebView loadFinishedEvent isn't firing

### ISSUE THREAD

**Issue by cbruce11** [NativeScript/NativeScript#5738]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

Yes

### Tell us about the problem

I'm trying to open a WebView to a url that is from a site that I have built. The site can be hit from any external source and works on the emulators browser. The WebView works for displaying sites such as http://www.google.com and other simple examples, but fails for my site. 

The loadFinishedEvent never fires for my site as well. I don't know how to debug this issue any further.

### Which platform(s) does your issue occur on?

I have only tested it on iOS.

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.3
- Cross-platform modules: 3.4.1
- Runtime(s): tns-ios: 4.0.1

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

`<GridLayout>
    <WebView [src]="url" (loadedFinished)="loaded($event)"></WebView>
</GridLayout>`

`

    url;

    constructor(
        private routerExtensions: RouterExtensions,
        private route: ActivatedRoute){

            this.route.queryParams.subscribe(params => {
                if (params['url']) {

                    this.url = params['url'];

                    console.log(this.url);
                }
            })
    }

    loaded(ev) {
        console.log(ev)
    }`

**Comment by tsonevn** [comment]
HI @cbruce11,
You should set up `loadFinishedEvent ` listener via code behind. Check out [this ](https://docs.nativescript.org/angular/code-samples/ui/web-view#basic-web-view) example from the documentation, where this scenario is demonstrated.

**Comment by cbruce11** [comment]
I can try that, but how would that be any different from triggering the event on the WebView tag in the HTML?

**Comment by tsonevn** [comment]
Hi @cbruce11,
Some component-specific event listeners do not have exposed eventName, which could be used for setting up the event listener via the HTML. According to that the appropriate way, in this case, is to set up the listener via code behind on component loaded event.


More about our property system and how it is working could be found [here](https://docs.nativescript.org/core-concepts/properties#property-system).

**Comment by cbruce11** [comment]
Ok. But the loadFinished fires fine with certain sites, just not the one I'm hitting. So that solution hasn't provided any help.

**Comment by angularturk** [comment]
here is a sample site wont load with webview https://www.denizbank.com/3ds/default.aspx
