### ISSUE TITLE
Key Listener support for TextField

### ISSUE THREAD

**Issue by jkappel71** [NativeScript/NativeScript#574]
TextField should implement a method for listening for and responding to key presses.

**Comment by emiloberg** [comment]
Can't this be solved with [data bindings](https://docs.nativescript.org/bindings.html)?

E.g. creating a binding context:

```
var observableModule = require("data/observable");
var bindingContext = new observableModule.Observable({
	textFieldInput: ''
});
page.bindingContext = bindingContext;
```

...attaching it to the TextField:

```
<TextField text="{{ textFieldInput }}" />
```

And then reacting to when that that property is changed:
```
bindingContext.on(Observable.propertyChangeEvent, function (propertyChangeData) {
	console.log(propertyChangeData.propertyName + " has been changed and the new value is: " + propertyChangeData.value);
});
```

This is the way I do "search-as-you-type". See this [search.js](https://github.com/emiloberg/oppna-program-reklistan-app/blob/master/app/src/views/search.js) of a project of mine (and the corresponding [search.xml](https://github.com/emiloberg/oppna-program-reklistan-app/blob/master/app/src/views/search.xml)).

[Docs: propertyChangeEvent](https://docs.nativescript.org/events#propertychange-event)

**Comment by jkappel71** [comment]
Well, that's about what I ended up with also to solve the issue.  However, sometimes you need to see that actual key press value.  For example, I am working with a Bluetooth bar code scanner.  It sends all of its data into the keyboard buffer (it actually registers as a Bluetooth keyboard when you pair it).  When it's done sending data it sends the tab character.  The tab character doesn't cause the data bound value to change, rather it causes the focus to change to the next control.  There isn't a lost focus method or a key press listener for the TextField, so I had to hack it a bit by watching for my bound value to be a certain length.  It's not a good solution.

**Comment by hgenru** [comment]
Key listener may help implement "next button" handler 
![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f343738323837362f313236313531372f65313637336261612d326332652d313165332d396663392d6332336638646163393833372e6a7067](https://cloud.githubusercontent.com/assets/2411525/9564417/18f1c1ac-4ec0-11e5-987e-1c3282bfd320.jpeg)

**Comment by hamorphis** [comment]
I will investigate if this can be implemented and how.

**Comment by jkappel71** [comment]
Excellent, thanks.  One additional thought, most programming languages support key press listening, and also handling.  So, if you mark that the event has been handled, it stops it from bubbling up to other listeners.  Just a thought while you're looking into it.

**Comment by hamorphis** [comment]
On Android, we can fire an NativeScript event from EditText's OnEditorActionListener.onEditorAction. There is a KeyEvent argument there. How about iOS?

**Comment by hamorphis** [comment]
@jkappel71 Do you have ideas how to implement a key listener for iOS UITextField and UITextView? We need to have this feature for both platforms and it has to have the same public API.

**Comment by hamorphis** [comment]
@hgenru Do you have ideas how to implement a key listener for iOS UITextField and UITextView? We need to have this feature for both platforms and it has to have the same public API.

**Comment by hamorphis** [comment]
I can use this for Android: https://developer.android.com/reference/android/view/KeyEvent.Callback.html

**Comment by hamorphis** [comment]
More info on the subject: http://stackoverflow.com/questions/1967740/onkeylistener-not-working-with-soft-keyboard-android

**Comment by hamorphis** [comment]
Key events are not supported by the operating systems.

**Comment by jkappel71** [comment]
It's odd in deed that Android does not require onKeyListener to work with the soft keyboard, however, it is required to work with all physical keyboards.  Bluetooth scanners register themselves as keyboards.  Therefore, the onKeyListener is still a quite useful method to implement.

I don't develop for IOS natively, so I have no idea how to implement it there.

Here's the docs for how to do it on android: [http://developer.android.com/reference/android/view/View.OnKeyListener.html][1]

-Jay

  [1]: http://developer.android.com/reference/android/view/View.OnKeyListener.html

**Comment by atanasovg** [comment]
In iOS it is not that straight-forward to respond to a keyboard event and extract the key value. @jkappel71 The article you pointed to uses Apple's private APIs and an app using the approach would get rejected from the store. Generally, the suggested way is to handle the text change notifications of a UITextField instance and to an action like "A text will be inserted at position, do something". In iOS 7+ there is the [keyCommands](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIResponder_Class/index.html#//apple_ref/occ/instp/UIResponder/keyCommands) array which would *probably* help with some special keys but still, these are stated to be applicable to attached hardware keyboards only.

**Comment by manojdcoder** [comment]
@hamorphis I'm not a very good with native iOS, but still I found [UITextFieldTextDidChangeNotification](https://developer.apple.com/reference/uikit/uitextfieldtextdidchangenotification?language=objc) and it works with native apps. May I know, is there any particular reason for not using it on NS.

**Comment by hamorphis** [comment]
@manojdcoder Does the UITextFieldTextDidChangeNotification provide the **key** being pressed?

**Comment by manojdcoder** [comment]
@hamorphis As you mentioned already I too don't find the exact option for key being pressed, but still [textFieldShouldChangeCharactersInRangeReplacementString](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/text-field/text-field.ios.ts#L75) delegate method could be a work around. `range: NSRange` should give us the changed characters through which we assume the pressed keys, returning false will prevent inputs.

This may fail only if user plays with select all / clear / past menus, but in most cases it should behave as expected.

**Comment by rudii1410** [comment]
Is there any updates on these feature?
