### ISSUE TITLE
Stopping nativescript-dev-sass watcher Executing after-watch hook 

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/NativeScript#5741]
with nativescript 4.0.0 i'm unable to stop `tns run android` command using `ctrl + c`
doesn't matter how many times i press `ctrl+ c` it always give below msg.

```
Stopping nativescript-dev-sass watcher
Executing after-watch hook from E:\incpt\nativescript\mydrawer-ng\hooks\after-wa
tch\nativescript-dev-typescript.js
Executing after-watch hook from E:\incpt\nativescript\mydrawer-ng\hooks\after-wa
tch\nativescript-dev-webpack.js
```
below is screenshot 
![temp](https://user-images.githubusercontent.com/13558667/39245004-1e8cec1c-48b0-11e8-838b-340cd26bad89.PNG)

**Comment by manoldonev** [comment]
@bhavincb You can follow the issue for this specific problem in the nativescript-dev-sass repo here: https://github.com/NativeScript/nativescript-dev-sass/issues/76. Closing this as a duplicate
