### ISSUE TITLE
iOS: navigation-crash after closing modal page when 'animated' is set to false

### ISSUE THREAD

**Issue by felix-idf** [NativeScript/NativeScript#5743]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
_Yes_

### Tell us about the problem
It is hard to explain the issue, as we have only one scenario where the issue occurs, so please use the sample project and follow the steps from the end of this post. It only occurs when closing a modal page and navigate from the topmost-frame to another page while setting the animated-property to false.

### Which platform(s) does your issue occur on?
iOS (tested on iOS 10 and 11)

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0
- Cross-platform modules: next (4.0.0-2018-04-25-02)
- Runtime(s): 4.0.1

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the app
2. open the drawer (using the button or with pan event)
3. tap "open modal" option from drawer to open the sample modal page
4. close the modal page with the button to navigate to another page
5. use back button to navigate back to the first page (main-page)
6. repeat steps 1-4

While closing the modal page and attempting to navigate, the app crashes with the following log:

> 
> ***** Fatal JavaScript exception - application has been terminated. *****
> Native stack trace:
> 1   0x10aeac359 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
> 2   0x10aed31fb NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
> 3   0x10b7c849e ffi_closure_unix64_inner
> 4   0x10b7c8de2 ffi_closure_unix64
> 5   0x10c69962f -[UIViewController __viewWillAppear:]
> 6   0x10c663f55 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke
> 7   0x10c4fa513 _runAfterCACommitDeferredBlocks
> 8   0x10c4e977e _cleanUpAfterCAFlushAndRunDeferredBlocks
> 9   0x10c517f05 _afterCACommitHandler
> 10  0x1102e5607 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
> 11  0x1102e555e __CFRunLoopDoObservers
> 12  0x1102c9b81 __CFRunLoopRun
> 13  0x1102c930b CFRunLoopRunSpecific
> 14  0x111b40a73 GSEventRunModal
> 15  0x10c4ef0b7 UIApplicationMain
> 16  0x10b7c8c3d ffi_call_unix64
> 17  0x12f355d40
> JavaScript stack trace:
> 1   update@file:///app/tns_modules/tns-core-modules/ui/action-bar/action-bar.js:143:50
> 2   onLoaded@file:///app/tns_modules/tns-core-modules/ui/page/page.js:201:34
> 3   @file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:311:98
> 4   callFunctionWithSuper@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:304:13
> 5   callLoaded@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:311:35
> 6   loadView@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:439:28
> 7   @file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:233:27
> 8   eachChildView@file:///app/tns_modules/tns-core-modules/ui/frame/frame-common.js:340:21
> 9   eachChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:855:27
> 10  onLoaded@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:232:23
> 11  onLoaded@file:///app/tns_modules/tns-core-modules/ui/frame/frame-common.js:41:39
> 12  @file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:311:98
> 13  callFunctionWithSuper@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:304:13
> 14  callLoaded@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:311:35
> 15  loadView@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:439:28
> 16  @file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:233:27
> 17  eachChildView@file:///app/tns_modules/nativescript-ui-sidedrawer/ui-sidedrawer.js:186:21
> 18  eachChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:855:27
> 19  onLoaded@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:232:23
> 20  onLoaded@file:///app/tns_modules/nativescript-ui-sidedrawer/ui-sidedrawer.js:45:39
> 21  @file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:311:98
> 22  callFunctionWithSuper@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:304:13
> 23  callLoaded@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:311:35
> 24  viewWillAppear@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:639:33
> 25  UIApplicationMain@[native code]
> 26  start@file:///app/tns_modules/tns-core-modules/application/application.js:264:26
> 27  run@file:///app/tns_modules/tns-core-modules/application/application.js:284:10
> 28  anonymous@file:///app/app.js:2:16
> 29  evaluate@[native code]
> 30  moduleEvaluation@[native code]
> 31  @[native code]
> 32  promiseReactionJob@[native code]
> JavaScript error:
> file:///app/tns_modules/tns-core-modules/ui/action-bar/action-bar.js:143:50: JS ERROR TypeError: null is not an object (evaluating 'navController.viewControllers')

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
[NSIssues4.zip](https://github.com/NativeScript/NativeScript/files/1947640/NSIssues4.zip)

Thank you in advance.

**Comment by tsonevn** [comment]
The issue is no longer reproducible with NativeScript 4.2
