### ISSUE TITLE
TabView layout item problem NS 4.0 (ios)

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/NativeScript#5745]
I've got the following layout

```
       <TabView>
            <TabView.items>

                <TabViewItem>
                    <TabViewItem.view>
                        <ScrollView>
                            <StackLayout className="form m-10">

                                <GridLayout columns="*,auto" rows="auto">
                                    <Label text="Entry #1" row="0" col="0" class="app-form-label" />
                                </GridLayout>

                                <GridLayout columns="*,auto" rows="auto">
                                    <Label text="Entry #2" row="0" col="0" class="app-form-label" />
                                </GridLayout>
                            </StackLayout>
                        </ScrollView>
                    </TabViewItem.view>
                </TabViewItem>
            </TabView.items>
        </TabView>
```

With NS 4.0 - it doesn't display the GridLayout children (I removed some UI).

If I comment out the ScrollView - then it works.

**Comment by r0zar** [comment]
I'm also seeing this, and only for iOS.

For me its forcing my first element up and halfway tucking it under the actionbar.

**Comment by r0zar** [comment]
This is caused by tns-core-modules. Roll back to version 3.4.1 and you should be good until they find the fix.

**Comment by tsonevn** [comment]
HI all, 
I tested this case in a sample project while using latest NartiveScript 4.0, however, was unable to recreate the issue. For your convenience, I am attaching a sample project. You can review it and make the needed changes, which will help us to reproduce it.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/1949869/Archive.zip)

**Comment by erjdriver** [comment]
Looks like another user confirmed the problem also.

I'll try to strip the page down and and let know the conditions it occurs it.

The only difference seems to be (my page has more stuff) - but also could be the css definitions.

**Comment by tsonevn** [comment]
Hi @erjdriver,

I noticed that @r0zar has the same problem, however, I can not confirm that this is a real issue, without a stable way to reproduce it on my side.
It will help if you can recreate the issue with the sample project and to send it back.

**Comment by erjdriver** [comment]
I created a project with `tns create test --template tsc`

I'm using NS 4.0, core 4.0 and iOS 4.0.1

`
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo" class="page">
    
    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>

    <TabView>
            <TabView.items>

                <TabViewItem>
                    <TabViewItem.view>
                        <ScrollView>
                            <StackLayout>

                                <GridLayout columns="*,auto" rows="auto">
                                    <Label text="Entry #1" row="0" col="0" />
                                </GridLayout>

                                <GridLayout columns="*,auto" rows="auto">
                                    <Label text="Entry #2" row="0" col="0" />
                                </GridLayout>
                            </StackLayout>
                        </ScrollView>
                    </TabViewItem.view>
                </TabViewItem>
            </TabView.items>
        </TabView>

</Page>
`

The page file doesn't do anything and no model file.

I stripped out all the css references.

PROBLEM: 2 grid layouts not visible - but if the ScrollView is removed, works.

**Comment by tsonevn** [comment]
Hi @erjdriver,
In your scenario, you should setup the ScrollView or the whole TabView into some of the available Layouts(e.g GridLayout). This is needed for the ScrollView, while it is measured.
Option 1:
```
<GridLayout>
    <TabView>
            <TabView.items>

                <TabViewItem>
                    <TabViewItem.view>
                        <ScrollView>
                            <StackLayout className="form m-10">

                                <GridLayout columns="*,auto" rows="auto">
                                    <Label text="Entry #1" row="0" col="0" class="app-form-label" />
                                </GridLayout>

                                <GridLayout columns="*,auto" rows="auto">
                                    <Label text="Entry #2" row="0" col="0" class="app-form-label" />
                                </GridLayout>
                            </StackLayout>
                        </ScrollView>
                    </TabViewItem.view>
                </TabViewItem>
            </TabView.items>
        </TabView>
</GridLayout>
```

Option 2:
```
<TabView>
            <TabView.items>

                <TabViewItem>
                    <TabViewItem.view>
                     <GrindLayout>
                        <ScrollView>
                            <StackLayout className="form m-10">

                                <GridLayout columns="*,auto" rows="auto">
                                    <Label text="Entry #1" row="0" col="0" class="app-form-label" />
                                </GridLayout>

                                <GridLayout columns="*,auto" rows="auto">
                                    <Label text="Entry #2" row="0" col="0" class="app-form-label" />
                                </GridLayout>
                            </StackLayout>
                        </ScrollView>
                      </GrindLayout>
                    </TabViewItem.view>
                </TabViewItem>
            </TabView.items>
        </TabView>
```

**Comment by erjdriver** [comment]
That fixed it!

So it the issue that TabViewItems need a layout child or ScrollView needs a layout parent?
