### ISSUE TITLE
NativeScript Play sound simultaneously as ex Spotify is playing in background

### ISSUE THREAD

**Issue by erikandershed** [NativeScript/NativeScript#5749]
### Did you verify this is a real problem by searching the [NativeScript Forum]
yes
### Tell us about the problem
In NativeScript 3.4 where and how do I declare that my app should be able to play sound simultaneously as for exempel Spotify is playing in the background?

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
NativeScript 3.4

**Comment by NickIliev** [comment]
@erikandershed on iOS by default only one application can play a sound at a time. iOS will automatically stop the background music and play your application sound.

**Comment by erikandershed** [comment]
No, that not true. You can play a sound while an other background music is playing.

**Comment by erikandershed** [comment]
The Class [AVAssetReaderAudioMixOutput](https://developer.apple.com/documentation/avfoundation/avassetreaderaudiomixoutput) for iOS do just that. Mix in a sound with other apps that are playing music. 

Any ide how I add this for an app in NativeScript?

**Comment by NickIliev** [comment]
@erikandershed you can use the native API directly and implement it just as you would do it on iOS.
To have access to the native API and IntelliSense (tath will help you with the data conversion syntax from Objective-C to JavaScript) use [tns-platform-declarations](https://www.npmjs.com/package/tns-platform-declarations)

**Comment by erikandershed** [comment]
Sweet. I am new to this API, can you show me an example on how I would do this?

**Comment by NickIliev** [comment]
@erikandershed using [marshaling](https://docs.nativescript.org/runtimes/ios/marshalling/Marshalling-Overview) (data conversion from/to in this case Objective-C to JavaScript) it would look like something like

```TypeScript
let newReaderOutput = AVAssetReaderAudioMixOutput.alloc().initWithAudioTracksAudioSettings(myNSArray, myNSDictionary);
```

**Comment by erikandershed** [comment]
I have an old app that do just this. So I know it works. But I have tried my best to be able to add the code. But I can’t get it to work. If it’s not to much to ask, please show me little more what I need to write. Many thanks!!

**Comment by erikandershed** [comment]
Sorry, can you show me little more in detail how I can this conversion from c to js.

Best!
