### ISSUE TITLE
Add a file picker that works with any type of files stored in any folder in /storage/emulated

### ISSUE THREAD

**Issue by pierremacedo** [NativeScript/NativeScript#5753]
We only have two options to select files in Nativescript and both of them are third party plugins that don't quite offer many configuration options and allow to select only images and videos. There should be a native module for this.  I had to give up on the idea of allowing users to select pdf and doc files in the current app I'm building just because I couldn't find a solution for this. To use the FileSystem module you have to specify a folder and a file to open, and this is useless in my case.

Please consider adding this feature.

**Comment by tsonevn** [comment]
Hi @pierremacedo,
First of all, thank you for your interest in NativeScript.
Regarding the issue, the core modules provide an implementation for the basic functionalities for both platform iOS and Android, similar to the FileSystem or Platforms modules.
For any other functionality which extends the one in the core modules or implements a new one, while using a native library, you should create a custom plugin. 
As you have mentioned there are plugins similar to [nativescript-mediafilepicker](https://github.com/jibon57/nativescript-mediafilepicker) , which provides a way to select files from the device.
You can help authors to improve the existing ones by sending a pull request in their repositories. Another option is to create a new one from scratch. More info about creating a plugin could be found [here](https://docs.nativescript.org/plugins/building-plugins).

**Comment by aleksander351** [comment]
I am amazed by the limited community support for this framework, compared to others. Not even a file picker module. Every browser has this basic functionality.
