### ISSUE TITLE
 field 'int android.app.Fragment.mContainerId' Error

### ISSUE THREAD

**Issue by shivgolani** [NativeScript/NativeScript#5756]
Exception java.lang.NullPointerException: Attempt to read from field 'int android.app.Fragment.mContainerId' on a null object reference
android.app.BackStackRecord$1.onPreDraw (BackStackRecord.java:1131)
android.view.ViewTreeObserver.dispatchOnPreDraw (ViewTreeObserver.java:944)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2000)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1084)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:5990)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:767)
android.view.Choreographer.doCallbacks (Choreographer.java:580)
android.view.Choreographer.doFrame (Choreographer.java:550)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:753)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:135)
android.app.ActivityThread.main (ActivityThread.java:5343)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:905)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:700)

**Comment by NickIliev** [comment]
@shivgolani can you please provide as much information as possible on how t reproduce the issue. The best approach would be to isolate the case in a sample project (or code snippet or even [a Playground demo](https://play.nativescript.org/)) so we could investigate the case at our side.

FOllow the requirements for posting a new issue 
```
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

## Please, provide the details below:

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```

**Comment by shivgolani** [comment]
@NickIliev Thanks for quick response my package.json 

{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.ngasce.jforce",
    "tns-android": {
      "version": "4.0.1"
    }
  },
  "scripts": {
    "lint": "eslint \"app/**/*.js\""
  },
  "dependencies": {
    "moment": "^2.22.0",
    "nativescript-appavailability": "^1.3.1",
    "nativescript-appversion": "^1.4.1",
    "nativescript-calendar": "^2.0.0",
    "nativescript-cardview": "^3.0.0",
    "nativescript-cfalert-dialog": "^1.0.6",
    "nativescript-downloader": "^2.0.0",
    "nativescript-email": "^1.5.1",
    "nativescript-exoplayer": "^3.4.1",
    "nativescript-fancyalert": "^1.2.0",
    "nativescript-floatingactionbutton": "^4.1.3",
    "nativescript-fresco": "^3.0.7",
    "nativescript-google-maps-sdk": "^2.6.0",
    "nativescript-insomnia": "^1.2.1",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-onesignal": "^1.0.7",
    "nativescript-openfile": "0.0.11",
    "nativescript-pdf-view": "^2.0.1",
    "nativescript-permissions": "^1.2.3",
    "nativescript-phone": "^1.3.1",
    "nativescript-plugin-firebase": "^5.3.1",
    "nativescript-screen-orientation": "^2.0.0",
    "nativescript-sqlite": "^2.0.1",
    "nativescript-store-update": "^1.0.2",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-calendar": "^3.5.2",
    "nativescript-ui-dataform": "^3.5.2",
    "nativescript-ui-listview": "^3.5.4",
    "nativescript-ui-sidedrawer": "^4.0.0",
    "remote-file-size": "^3.0.4",
    "tns-core-modules": "^4.0.0"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "clean-webpack-plugin": "~0.1.19",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "eslint": "~4.9.0",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "~1.5.0",
    "nativescript-dev-typescript": "^0.7.1",
    "nativescript-dev-webpack": "^0.10.1",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "~6.0.6",
    "typescript": "^2.8.3",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  }
}

**Comment by shivgolani** [comment]
@NickIliev I'm unable the reproduce this error, I got this error via firebase crash analytics.

**Comment by NickIliev** [comment]
@shivgolani on what API Level is the error thrown and on what device (if the analytics is reporting this kind of info) - it might be related to a customized Android SDK (e.g. some RedMi devices0 or a specific API level.

**Comment by shivgolani** [comment]
Hi its on API level 21 and 22 have got more than 300 crash reports on this issue.

**Comment by NickIliev** [comment]
@shivgolani thanks for the information. It seems that your issue might be related [to this one](https://github.com/NativeScript/NativeScript/issues/5674). The fix for the linked issue is already in the `master` branch and will be included in our next official release. Meanwhile, you can test the issue by installing the `next` version of tns-core-modules
```
npm uninstall tns-core-modules
npm i tns-core-modules@next --save
```

Let me know if the fix is resolving your case.

**Comment by shivgolani** [comment]
@NickIliev thanks I've updated the app. Waiting for the analytics.
Will keep you posted.

**Comment by shivgolani** [comment]
@NickIliev Thank you. Issue Resolved.
