### ISSUE TITLE
Modal Issue: shownModally not firing from frame in {N} 4

### ISSUE THREAD

**Issue by 99hats** [NativeScript/NativeScript#5761]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

Yes

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

Modal Issue: shownModally not firing from frame in NS 4

### Which platform(s) does your issue occur on?
iOS/Android/Both

iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) 4.0.1 on default playground

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

[Run on playground ](https://play.nativescript.org/?template=play-tsc&id=Nlvzek&v=2)

Click on Show Modal Page With Frame.

"shown modally" should appear in device logs, but it doesn't

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```xml
<Page backgroundColor="green" shownModally="onShownModally">
	<ActionBar>
		<Label text="Modal"></Label>
	</ActionBar>
	<StackLayout backgroundColor="lightGreen">
		<Button text="Close" tap="onClose" />
	</StackLayout>
</Page>
```

``` typescript
import { Page } from "tns-core-modules/ui/page";
import { View, EventData } from "tns-core-modules/ui/core/view";

export function onShownModally(args) {
    console.log('shown modally ' + args.context)
}

export function onClose(args) {
    const view = args.object as View;
    const page = view.page as Page;

    page.frame.closeModal();
}
```

**Comment by tsonevn** [comment]
Hi @99hats,
The `shownModally` event should be set up on the first element in the view. In your case, this is the Frame component. Regarding that you can set up the event callback method via code behind on the newly created frame as follow:
home-page.ts
```
export function onModalFrame(args: EventData) {
    const view = args.object as View;
    const page = view.page;

    const frame = new Frame();
    frame.navigate("home/modal-page");
    frame.on("shownModally", (args) => { 
        console.log("shownModally event");
    })
    page.showModal(frame,
        "context",
        () => console.log("home-page modal frame closed"),
        true);
}
```

**Comment by 99hats** [comment]
Ah, thank you. 

So new question, how do I get the "context" in a page that is shown modally?

The args.object passed in the onLoaded event does not appear to have the "context"

**Comment by 99hats** [comment]
Here's what I ended up doing

```typescript
import { View, EventData, ShownModallyData} from "tns-core-modules/ui/core/view";
import { Frame } from "tns-core-modules/ui/frame";
import { Page } from "tns-core-modules/ui/page"


let mypage: View

export function onModalFrame(args: EventData) {
    const view = args.object as View;
    const page = view.page;

    const frame = new Frame();
    frame.navigate("home/modal-page");

    frame.on("shownModally", (args: ShownModallyData) => {
        console.log("shownModally event");
        this.mycontext = args.context
        mypage.bindingContext = this.mycontext
    })


    mypage = page.showModal(frame,
        {'foo':'bar'},
        () => console.log("home-page modal frame closed"),
        true);
}
```
```xml
<Page>
	<ActionBar>
		<Label text="Home"></Label>
	</ActionBar>
	<StackLayout>
		<Button text="Show Modal Page With Frame" tap="onModalFrame" />
	</StackLayout>
</Page>
```

**Comment by tsonevn** [comment]
Hi @99hats,
On `shownModally` you can set up the received context to the newly created frame used in the modal page. 
For example:
```

    frame.on("shownModally", (args:any) => {
        console.log("shownModally event");
        let mframe = args.object;
        
        let mycontext = args.context
        console.log(mycontext);
        mframe.bindingContext = mycontext
    })
```
You can also check the sample [here](https://play.nativescript.org/?template=play-tsc&id=Nlvzek&v=5).

**Comment by tsonevn** [comment]
Hi @surdu,
This use case is demonstrated in the first sample [here](https://docs.nativescript.org/ui/ns-ui-widgets/modal-page#basics).

**Comment by surdu** [comment]
@tsonevn By "this use case" I meant the case when you have to use a frame to navigate inside the modal. That was the root of this issue: not understanding how to pass the context down to the modal page from the frame.

Also, the exemple that I linked in my previous comment sends the context but never shows how to use it on the other side.
