### ISSUE TITLE
unable to create new native thread

### ISSUE THREAD

**Issue by luishdez87** [NativeScript/NativeScript#5764]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
**yes**
### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
 * What went wrong:
17:27:08.162 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':app:mergeDebugAssets'.
17:27:08.162 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > unable to create new native thread

### Which platform(s) does your issue occur on?
iOS/Android/Both
**Android
[log.txt](https://github.com/NativeScript/NativeScript/files/1958234/log.txt)
**

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

i create a new angular project with --ng and try to build and show this error
can you help me plis?

**Comment by ikhsan017** [comment]
It seems yours is similar to mine on #5729

**Comment by luishdez87** [comment]
@ikhsan017 i think you have an answer...

**Comment by luishdez87** [comment]
thanks for nothing to the community... I think the best choice gonna be xamarin...

**Comment by NickIliev** [comment]
@luishdez87 the issue would be resolved if you have shared as much as possible information that can help us and the community to investigate and reproduce your case. Please follow the guidelines for posting a new issue including providing the steps taken, the code involved and the environment details (OS, Node, NPM, tns versions).

The community channels like SO, the NativeScript forum and the community slack are also good places for seeking help. You will still need to provide a detailed info along with the error log.
