### ISSUE TITLE
[iOS] ListView does not span under home indicator of iPhone X

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#5765]
### Tell us about the problem

Here are ListView cases based on the [template-master-detail-ts](https://github.com/NativeScript/template-master-detail-ts).

### Which platform(s) does your issue occur on?

iOS

### Please tell us how to recreate the issue in as much detail as possible.

[Quick start](https://github.com/NativeScript/template-master-detail-ts#quick-start):
```
tns create my-master-detail-ts --template tns-template-master-detail-ts
```

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```cars-list-page.xml
<Page class="page" navigatingTo="onNavigatingTo" navigatingFrom="onNavigatingFrom"
    xmlns:lv="nativescript-ui-listview"
    xmlns="http://schemas.nativescript.org/tns.xsd">
    
    <!-- backgroundColor="green" -->
    <!-- scrollableContent="true" -->

```

### Screenshots

master-detail-list-view-landscape-current
![master-detail-list-view-landscape-current](https://user-images.githubusercontent.com/12251337/39428253-61bcd564-4c8f-11e8-8806-d9ae6c26870a.png)
Expected: ListView should span under the home indicator and ListView background should stretch.

---
master-detail-list-view-landscape-current-scrollable-content
![master-detail-list-view-landscape-scrollable-content](https://user-images.githubusercontent.com/12251337/39428254-61dbd662-4c8f-11e8-918a-1b7eb79f8858.png)
Expected: ListView should span under the home indicator, ListView background should stretch and ListView should have proper offset.

---
master-detail-list-view-portrait-current
![master-detail-list-view-portrait-current](https://user-images.githubusercontent.com/12251337/39428255-61f70c66-4c8f-11e8-8a4c-edadf1945100.png)
Expected: ListView should span under the home indicator.

---
master-detail-list-view-portrait-current-scrollable-content
![master-detail-list-view-portrait-scrollable-content](https://user-images.githubusercontent.com/12251337/39428256-621414e6-4c8f-11e8-90d8-28e71d50dc5a.png)
Expected: ListView should span under the home indicator and ListView should have proper offset.

#

**Comment by MartoYankov** [comment]
This issue is no longer reproducible with latest version of the template.
