### ISSUE TITLE
The colorFill parameter in the gauge plugin cannot be set by an observable for color

### ISSUE THREAD

**Issue by dwlayton** [NativeScript/NativeScript#5766]
I want to dynamically change the color of an indicator bar on a gauge as a function of the parameter that the gauge represents. The RadialBarIndicator length is successfully set by using an observable to represent the maximum value. However, when I tried using an observable to set the fillColor of the BarIndicatorStyle the bar color did not change, defaulting to blue. 
I searched forums for a solution, but found none.
I have included two nativescript playground links: the first link shows a gauge where an observable sets the bar length and its color is defined by a color hex code for red [(playground link)](https://play.nativescript.org/?template=play-js&id=U9ktp5&v=1) The second link shows the same gauge but with an observable to define the bar color, but the bar defaults to blue [(playground link)](https://play.nativescript.org/?template=play-js&id=LTQQnM&v=1)
I hope there is a simple javascript (or css?) solution to dynamically change the bar color, as I do not plan to use typescript, angular, etc.

Here is the xml markup with the uvColor observable

</gauge:RadialBarIndicator>
<gauge:RadialBarIndicator minimum="0" maximum="{{ uvIndex }}" location="0.97">
<gauge:RadialBarIndicator.indicatorStyle>
<gauge:BarIndicatorStyle cap="Round" fillColor= "{{ uvColor }}" barWidth="0.3" />
</gauge:RadialBarIndicator.indicatorStyle>
</gauge:RadialBarIndicator>	<!--

Here is the home-view-model.js with the uvColor observable set to the hex color for red.

var observableModule = require("data/observable");
function HomeViewModel() {
  var viewModel = observableModule.fromObject({
    uvIndex: 11,
    uvColor: "#d8001d",
  });
  return viewModel;
}
module.exports = HomeViewModel;

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#639
