### ISSUE TITLE
Chrome dev tools TypeError: Cannot read property ensureDomNode of undefined

### ISSUE THREAD

**Issue by altunyurt** [NativeScript/NativeScript#5767]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes

### Tell us about the problem

When I click on the elements tab on chrome dev tools, i get this error on  tns side

 JS: 'ERROR in getDocument(): TypeError: Cannot read property \'ensureDomNode\' of undefined'
05-01 17:00:15.246 27585 27585 D TNS.Native: JS Error: Error thrown while calling getDocument: Uncaught TypeError: Cannot read property 'domNode' of undefined

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0
- Cross-platform modules: 4.0.0
- Runtime(s): tns-android 4.0.1
- Google chrome: Version 57.0.2987.98 beta (64-bit) on linux mint 18.3
- Plugin(s): 
 "dependencies": {
    "nativescript": "^4.0.0",
    "nativescript-exoplayer": "^3.4.1",
    "nativescript-facebook": "^2.2.2",
    "nativescript-oauth": "^2.1.2",
    "nativescript-plugin-firebase": "^5.3.1",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-vue": "^1.3.2-rc.4",
    "tns-core-modules": "^4.0.0",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-async-to-generator": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "copy-webpack-plugin": "^4.5.1",
    "css-loader": "^0.28.11",
    "eslint": "^4.19.1",
    "eslint-plugin-vue": "^4.5.0",
    "extract-text-webpack-plugin": "^3.0.2",
    "fs-extra": "^5.0.0",
    "lazy": "1.0.11",
    "nativescript-vue-externals": "^0.1.2",
    "nativescript-vue-loader": "^0.1.5",
    "nativescript-vue-target": "^0.1.0",
    "nativescript-vue-template-compiler": "^1.3.2-rc.4",
    "node-sass": "^4.7.2",
    "ns-vue-loader": "^0.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "rimraf": "^2.6.2",
    "sass-loader": "^6.0.7",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^3.11.0",
   "webpack-synchronizable-shell-plugin": "0.0.7",
    "winston-color": "^1.0.0"

### Please tell us how to recreate the issue in as much detail as possible.
It is working with nativescript 3.4.1 . But I'm getting this error whenever i chose the elements tab on chrome dev-tools page with nativescript 4.0.0 Other tabs are working without any problems.

**Comment by tsonevn** [comment]
Hi @altunyurt,
I tested your case on my side, however, was unable to recreate it. Can you provide a sample project, which could be used for debugging?

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/android-runtime#1035
