### ISSUE TITLE
When Can I expect support for angular 6?

### ISSUE THREAD

**Issue by hamada147** [NativeScript/NativeScript#5769]
My team is going to start a new intensive project and we would like to know when can we expect support for angular 6 after getting out of the beta state?
I won't mind a rough estimation just need confirmation that it is a priority and a release date expectation

**Comment by EddyVerbruggen** [comment]
Looking at [this issue](https://github.com/NativeScript/template-master-detail-ng/pull/130) in `template-master-detail-ng`, and [this one](https://github.com/NativeScript/sample-Groceries/pull/303) in the Groceries sample, I'd say the team is right on top of Angular 6.

**Comment by vchimev** [comment]
Hey Guys,

In brief, yes, we are on top of Angular 6. Here is an issue to follow: https://github.com/NativeScript/nativescript-angular/issues/1282.

We already support Angular 6 RCs in our `master` branches, however, we are going to support it when it goes official.
