### ISSUE TITLE
How to write code for  below image attached

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#5770]
Want code for the highlighted picture in native script

![1](https://user-images.githubusercontent.com/10844041/39562224-1aa6537c-4ec8-11e8-901d-ab399f640087.PNG)

**Comment by tsonevn** [comment]
Hi @dhanalakshmitawwa,
For `How to` questions, please use our [forum ](https://discourse.nativescript.org/) or StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript). This repository is used only for bug reporting and feature requests.

**Comment by dhanalakshmitawwa** [comment]
ok,
Thank you for reply
