### ISSUE TITLE
iOS ActionBar Retains Color When Navigating Back

### ISSUE THREAD

**Issue by cfoulkes** [NativeScript/NativeScript#5773]
iOS Action Bar Issue

- CLI: 4.0.0
- Cross-platform modules: 4.0.0
- Runtime(s): 		"tns-ios": {
			"version": "4.0.1"
		},

tns create someapp --ng

in item-detail.component.html add color attribute to ActionBar
<ActionBar title="Details" class="action-bar" color="blue"></ActionBar>

tns run ios

select row
item detail displays action bar text in blue
click back
item list now has action bar text in blue

setting color in actionbar html in the list view has no effect

<ActionBar title="My App" class="action-bar" color="black"></ActionBar>

This appears to be a bug.
Is there a way to override this behavior?

Thanks

Colin

**Comment by MartoYankov** [comment]
@cfoulkes  Thank you for reporting this. I was able to reproduce the problem and marked it as a bug.\

As a workaround you can use a `Label` to specify the title and set the color on the `Label`. Here is an example:
```
<ActionBar>
    <Label text="Details" color="red"></Label>
</ActionBar>
```

**Comment by janoshrubos** [comment]
I tried to reproduce this issue, but it seems like it's resolved now.

If this error is still relevant, feel free to open a new issue!
