### ISSUE TITLE
[iOS] GridLayout background does not stretch on iPhone X

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#5774]
### Tell us about the problem

Here are cases based on the [template-tab-navigation-ts](https://github.com/NativeScript/template-tab-navigation-ts).

### Which platform(s) does your issue occur on?

iOS
### Please tell us how to recreate the issue in as much detail as possible.

[Quick start](https://github.com/NativeScript/template-tab-navigation-ts#quick-start):
```
tns create my-tab-ts --template https://github.com/NativeScript/template-tab-navigation-ts
```

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```app.ios.scss
.page {
    background-color: green;
}
```

### Screenshots

tab-navigation-list-view-landscape-current
![tab-navigation-list-view-landscape-current](https://user-images.githubusercontent.com/12251337/39585934-8c431e8a-4efe-11e8-952f-26948d8dadd3.png)
Expected: ListView background should stretch.

---
tab-navigation-portrait-current
![tab-navigation-portrait-current](https://user-images.githubusercontent.com/12251337/39586089-ecb7df80-4efe-11e8-8739-8c59af1621ef.png)
Expected: GridLayout background should stretch under the NabigationBar and TabView and its content stays in the Safe Area.

---
tab-navigation-landscape-current
![tab-navigation-landscape-current](https://user-images.githubusercontent.com/12251337/39586224-4639c690-4eff-11e8-8133-a088a4eadb1a.png)
Expected: GridLayout background should stretch and its content stays in the Safe Area.

**Comment by MartoYankov** [comment]
This is now implemented in NativeScript 5
