### ISSUE TITLE
NS 4.0 Android navigation Issue

### ISSUE THREAD

**Issue by markomiljkovic** [NativeScript/NativeScript#5780]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem
Hello guys Im having a problem with nativescript v4.0.0 and frameModule 
when I send my app or page to background and then bring app to the front 
and tapp on button 
that has code like this:
<Button tap="navigate"></Button>
const frame  = require('ui/frame');
function navigate() {
frame.topmost.navigate("details-page");
}

App will crash with folowing error:
https://ibb.co/h15Om7
### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0
- Runtime(s): tns-android :4.0.0

**Comment by tsonevn** [comment]
HI @markomiljkovic,
This issue might be related to #5674. Can you try on your side, whether you will have the same problem with next modules?

1. `tns plugin remove tns-core-modules`
2. `tns plugin add tns-core-modules@next`
3. `tns platform remove android`
4. `tns platform add android`
5. `tns run android`

If the problem persists, please provide sample project, which could be used for debugging.

**Comment by markomiljkovic** [comment]
Nope it is not working  with new tns-core-modules :(
here is my package.json
tns-android: {
"version": "4.0.1"
}
tns-core-modules: "^4.0.0-2018-05-04-01"

**Comment by markomiljkovic** [comment]
Here is a sample project:
https://play.nativescript.org/?template=play-js&id=R7nWar

**Comment by markomiljkovic** [comment]
Also I think it is not related to #5674.
This was working fine in v3 but now with 4 it is broken.

**Comment by manoldonev** [comment]
Probably related to https://github.com/NativeScript/NativeScript/issues/5759

**Comment by manoldonev** [comment]
@markomiljkovic Checked the playground project (fixed two syntax errors so my version is https://play.nativescript.org/?template=play-js&id=R7nWar&v=2) but still cannot reproduce the issue locally neither on physical device (Nexus 6P with Android 8.1.0), nor on emulators with API Levels 19, 21, 23, and 25.

What is your Android version -- do you reproduce it on emulator / device?

Basically I have enabled "Don't Keep Activities" in Developer Options, starting the app, minimizing it to background, then restoring it, and tapping the button.

**Comment by markomiljkovic** [comment]
I reproduced it on Emulator Nexus 5x Api 25 and on Smasung J7 2017 - mobile phone.

**Comment by manoldonev** [comment]
@markomiljkovic unfortunately still nothing. Tested on emulators and various physical devices that we have around the office (with different Android versions ranging from 5 to 8) but cannot reproduce this. What is your Android SDK Build-tools versions btw (in Android Studio)?

**Comment by manoldonev** [comment]
The fix is in the master branch and will be included in our next official release. Meanwhile, you can test the fix by installing the next version of tns-core-modules
```
npm uninstall tns-core-modules
npm i tns-core-modules@next --save
```
