### ISSUE TITLE
HTMLView with ngIf and <br/> tag renders blank

### ISSUE THREAD

**Issue by noumaans** [NativeScript/NativeScript#5783]
### Tell us about the problem
If an HTMLView component is used with an *ngIf, it renders blank / empty if the HTML starts with a `<br/>` tag.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0-2018-04-18-11407
- Cross-platform modules: 4.0.0-2018-05-03-03
- Runtime(s): `"tns-ios"` 4.1.0-2018-04-24-01
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
Playground Link:
https://play.nativescript.org/?template=play-ng&id=LUVNqq&v=2

NOTE: Remember to make sure the delay is present in ngAfterViewInit - if delay is reduced to 1s, the render starts working again.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1314
