### ISSUE TITLE
How to implement Smooth scroll for nativescript angular in ScrollView

### ISSUE THREAD

**Issue by MuhammadTahir92** [NativeScript/NativeScript#5786]

**Comment by tsonevn** [comment]
HI @MuhammadTahir92,
You can use [scrollToHorizontalOffset ](https://docs.nativescript.org/api-reference/classes/_ui_scroll_view_.scrollview#scrolltohorizontaloffset) or [scrollToVerticalOffset](https://docs.nativescript.org/api-reference/classes/_ui_scroll_view_.scrollview#scrolltoverticaloffset) methods. For example:
```
scrollviewloaded(args){
        let scrollview:ScrollView = <ScrollView>args.object;
        setTimeout(() => {
            // scrollview.scrollToHorizontalOffset(30,true);
            scrollview.scrollToVerticalOffset(130, true)
        }, 2000);
    }
```
For any further questions use our [forum ](https://discourse.nativescript.org/) or StackOverflow [thread ](https://stackoverflow.com/questions/tagged/nativescript) this repository is used only for bug reporting or feature requests.
