### ISSUE TITLE
iOS: ScrollView moves content under ActionBar

### ISSUE THREAD

**Issue by dbenninger** [NativeScript/NativeScript#5792]
### Tell us about the problem
ScrollView moves content under ActionBar.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0
- Cross-platform modules: ~4.0.0
- Runtime(s): 4.0.1

### Please tell us how to recreate the issue in as much detail as possible.
1. tns create Test --ng
2. cd Test/
3. Edit the file app/item/item-detail.component.html and add a ScrollView as the root component
4. tns run ios
5. Open the detail view of one of the items

Content is under the ActionBar:
![img_06f9f9dab7e8-1](https://user-images.githubusercontent.com/13940547/39694134-822c3522-51e6-11e8-8770-a7fc6a787515.jpeg)

**Comment by tsonevn** [comment]
Hi @dbenninger,
To avoid moving the ScrollView content under the ActionBar you should set up the ScrollView inside some of the available Layouts. For example:
```
<GridLayout>
     <ScrollView>
..........
     </ScrollView>
</GridLayout>
```
This is recommended way for resolving this case after the changes made with NativeScript 4.0.

**Comment by dbenninger** [comment]
@tsonevn Thanks

**Comment by chrisse27** [comment]
@tsonevn Could you add this to the list of breaking changes for NS 4 or ns-ng 5.3?

**Comment by Gamadril** [comment]
Please reopen the issue for fixing. Bug still exists in 5.2.0 . Adding the GridLayout around ScrollView has no effect. My workaround for the moment is adding marginTop = 1 (or in CSS margin-top: 1) to the ScrollView.

Check the playground example.
https://play.nativescript.org/?template=play-js&id=lBPIgK

**Comment by tsonevn** [comment]
Hi @Gamadril,
You can try setting up `iosOverflowSafeArea` to false on the root component.
```
    <ScrollView iosOverflowSafeArea="false" class="scroll_wrapper">
....
</ScrollView>
```

**Comment by Gamadril** [comment]
@tsonevn, thanks that helps.
