### ISSUE TITLE
BUG: Android Label not auto resizing after value change

### ISSUE THREAD

**Issue by btaluy** [NativeScript/NativeScript#5793]
**Tell us about the problem**
When using Label and changing the text in realtime on the same page, it doesn't resize/shrink the Label after the text goes from big to small.

**Which platform(s) does your issue occur on?**
Only on Android, IOS works fine since it uses the UILabel component.

**Please provide the following version numbers that your issue occurs with:**
CLI: 4.0.0
Cross-platform modules: 3.4.0
Runtime(s): 3.4.1

**Do note**: _**This issue is also on TNS 4.0**_

**Please tell us how to recreate the issue in as much detail as possible.**
By using the Label component inside a StackLayout/GridLayout and changing its value from big to a smaller text in realtime on the same page.

Some pictures to show what is happening. I've made the background of the label orange so that you can see what the effect is of not shrinking the label.

This is how it looks on page initialisation.

![whatsapp image 2018-05-07 at 11 30 14](https://user-images.githubusercontent.com/22479262/39695273-5486054a-51ea-11e8-985b-869555716e63.jpeg)

Now we change the value with the slider to make it bigger.

![whatsapp image 2018-05-07 at 11 30 32](https://user-images.githubusercontent.com/22479262/39695274-54a71dde-51ea-11e8-90d6-6f0e7850aa23.jpeg)

Now we resize the value to small again from 1000s to 100s.
![whatsapp image 2018-05-07 at 11 29 42](https://user-images.githubusercontent.com/22479262/39695272-546d1d32-51ea-11e8-955e-05c51c22671f.jpeg)

 As you can see the width of the label does not shrink back.

Looking forward to your messages.
Kind regards: btaluy

**Comment by m-abs** [comment]
Workaround for nativescript-angular:
https://gist.github.com/m-abs/7743a0aa41621a5a54a74ef9d357e41b

**Comment by NickIliev** [comment]
@btaluy can you provide a Playground demo or sample project that can reproduce the issue with the used code base. You could also try the solution provided [here](https://github.com/NativeScript/NativeScript/issues/5326#issuecomment-385880531) (using `textAlignment`) - let me know if that approach is resolving your case.

**Comment by NickIliev** [comment]
@btaluy confirming this one as unexpected behavour on Android and marking it as a bug (works as expected on iOS). The solution to manually call `requestLayout`can be used as temporaly workaround - [here is a Playground demo ](https://play.nativescript.org/?template=play-tsc&id=llLK2T&v=3)demonstraing the technique in NativeScript Core project (TS)

**Comment by btaluy** [comment]
Hey guys, thanks for replying.

Yea, I'm using nativescript angular and for now we are using this implementation m-abs provided.
Although I do hope this will be fixed soon for the android versions.

here is a playground where you can check it out and see what happends.

https://play.nativescript.org/?template=play-ng&id=3MLWIz&v=4

**Comment by fthuin** [comment]
I confirm this also affects ListView with multiple template in Android. I have multiple template and inside them some components with *ngIf directives, and sometimes they're resizing properly, sometimes not (scrolling inside the list view can even randomize which component is rendered properly and which is not).

The solution with calling `.requestLayout()` on the outer layout when accessing the variable that changes the value of *ngIf does the trick, thank you! 👍 Hope it will be fixed soon.
