### ISSUE TITLE
button with width:auto not working

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/NativeScript#5794]
i'm trying to style button to only consume minimum space required. something similar to android `wrap_content` . but unable to do so. button always takes full space when set t `width:auto`. also padding-right and padding-left aplied to button not working properly.

below is css i'm using
```
Button{
    color: white;
    background-color: blue;
    width: auto;
    height:auto;
    padding: 20;
    z-index:0;
}
```

**Comment by NickIliev** [comment]
@bhavincb the thing is that when the width of an element (`Button`) is set to `auto` it will span to the size of its parent layout in which the element is nested. So in your case to control the element width you should either control your parent layout size or use different sizing approach (e.g. percentages or fixed sizes)

For example, take a look at [this Playground demo](https://play.nativescript.org/?template=play-tsc&id=qVeQDG)

**Comment by bhavincb** [comment]
hii @NickIliev ,
what if i want `Button` size to be same as it's text size?  using layout for every button will cause serious performance issues.

**Comment by joshcomley** [comment]
Is it possible to have a button automatically fit to the text?

In this playground, no matter what I do (apart from hard coding widths), buttons have a minimum width. Is there any way around this?

https://play.nativescript.org/?template=play-ng&id=epk2HB

**Comment by tskweres** [comment]
@bhavincb @NickIliev agreed, looking for an 'inline-block' style button. Specifically for apps with translations, based on the language being used, I have no idea how big my button will be, but I don't want it to always be 100% block

**Comment by NickIliev** [comment]
@tskweres the `Button` comes with some native specifics like predefined padding and styles. If you need to create your own customized inline button, I would recommend using `label` with `tap` event.

**Comment by kambojaz** [comment]
@tskweres, possible solution:

```
<GridLayout rows="auto" columns="auto, *">
         <Button text="Some label"  />
</GridLayout>
```

**Comment by patrikengborg** [comment]
`<Button text="Some label" horizontalAlignment="center" />`

**Comment by alexhribsek** [comment]
@patrikengborg Makes so much sense 😂

But thanks 🙏
