### ISSUE TITLE
I can’t make my app work with Webpack (Page-specific CSS and JS not being applied)

### ISSUE THREAD

**Issue by pierremacedo** [NativeScript/NativeScript#5797]
### Tell us about the problem
First, I’m using vanilla JS. My app is finished and it’s fully working with tns run android, but it’s really slow so I had to consider using Webpack. So I followed the following steps:

npm install --save-dev nativescript-dev-webpack
npm install

I created a bundle-config.js file containing the following code and put it in the app folder:

```
if (global.TNS_WEBPACK) {
    // registers tns-core-modules UI framework modules
    require("bundle-entry-points");

    // register application modules
    // This will register each `page` postfixed xml, css, js, ts, scss etc. in the app/ folder
    const context = require.context("~/", true, /(page|fragment)\.(xml|css|js|ts|scss|less|sass)$/);
    global.registerWebpackModules(context);
}
```
Then I imported bundle-config on top of app.js using `require("./bundle-config");`

`tns run android --bundle`

The app is installed on the device and it loads without a problem but with no page-specfic css being applied and it seems there are problems with the JS files as well because when I click on the “login” button nothing happens, so I think it’s not calling any function at all.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0
- Runtime(s): tns-android 4.0.1
- Plugin(s): "crypto-js": "^3.1.9-1",
                "nativescript-sqlcipher": "^1.1.11",
                 "nativescript-theme-core": "~1.0.4",
                "tns-core-modules": "~4.0.0"

### Please tell us how to recreate the issue in as much detail as possible.
The minimum code to reproduce the problem is here https://play.nativescript.org/?template=play-js&id=pIsNu3 
The login.js, login.xml, and login.css are inside the components folder just like they are in my project. The app.js and app.css also contain the same code of my project.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-dev-webpack#517
