### ISSUE TITLE
Stop calling metadata generator and build twice for android platform.

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#58]
_From @teobugslayer on April 1, 2015 15:35_

_From @teobugslayer on April 1, 2015 15:0_

Instead, the project template will supply a custom ants hook to do the work

Also, cache the platformData
Also, starting ant through the user command interpreter falling back to cmd

See https://github.com/NativeScript/android-runtime/issues/47

_Copied from original issue: NativeScript/nativescript-cli/pull/405_

_Copied from original issue: NativeScript/cross-platform-modules#241_

**Comment by enchev** [comment]
_From @teobugslayer on April 1, 2015 15:35_

_From @ns-bot on April 1, 2015 15:1_

:white_check_mark:

**Comment by enchev** [comment]
_From @teobugslayer on April 1, 2015 15:35_

ping @plamen5kov, @atanasovg

**Comment by enchev** [comment]
_From @teobugslayer on April 1, 2015 15:35_

_From @rosen-vladimirov on April 1, 2015 15:5_

:+1:  awesomeeeeeee

**Comment by enchev** [comment]
_From @teobugslayer on April 1, 2015 15:35_

_From @ns-bot on April 1, 2015 15:10_

:white_check_mark:

**Comment by enchev** [comment]
_From @teobugslayer on April 1, 2015 15:35_

_From @ns-bot on April 1, 2015 15:18_

:white_check_mark:

**Comment by enchev** [comment]
_From @teobugslayer on April 1, 2015 15:35_

_From @Plamen5kov on April 1, 2015 15:18_

:+1:

**Comment by enchev** [comment]
_From @teobugslayer on April 1, 2015 15:35_

**Do not merge before the new project templates!**

**Comment by enchev** [comment]
_From @teobugslayer on April 1, 2015 15:35_

_From @ns-bot on April 1, 2015 15:22_

:white_check_mark:

**Comment by Plamen5kov** [comment]
The double build problem is fixed in the android runtime with a custom_rules.xml that builds metadata

The actual commit is:
https://github.com/NativeScript/android-runtime/commit/661bf997a88b67d67d2a7180050bd92d0435744c
