### ISSUE TITLE
Accessing Native Packages starting with 'in'

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/NativeScript#5801]
i was trying to use AwesomeImagePicker library inside nativescript app.

i had added below code to gradle file
```
dependencies {
    compile 'com.github.myinnos:AwesomeImagePicker:1.0.2'
}
```
now to access this library i have to use 
`const AlbumSelectActivity=in.myinnos.awesomeimagepicker.activities.AlbumSelectActivity` for which i have to declare `in` as any like `declare var in:any` . but that gives typescript compile error.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#1046
