### ISSUE TITLE
Build Failure 

### ISSUE THREAD

**Issue by devyaz** [NativeScript/NativeScript#5802]
### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

After updating Nativescript to 4  i cant build my project that used to build and run fine
### Which platform(s) does your issue occur on?
iOS/Android/Both
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)
here is my output
 `[18-05-09 15:15:50.402] (CLI) Successfully prepared plugin nativescript-webview-interface for android.
[18-05-09 15:15:50.563] (CLI) Successfully prepared plugin tns-core-modules for android.
[18-05-09 15:15:50.727] (CLI) Successfully prepared plugin tns-core-modules-widgets for android.
[18-05-09 15:16:35.927] Build failed. Failed to build plugin nativescript-socket.io : 
Error: Command failed: gradlew.bat -p C:\Users\Martin Mtawali\Desktop\nativescript\MalaChat\platforms\tempPlugin\nativescript_socket.io assembleRelease -PcompileSdk=android-27 -PbuildToolsVersion=27.0.3 -PsupportVersion=26.0.0-alpha1
FAILURE: Build failed with an exception.
* What went wrong:
The specified project directory 'C:\Users\Martin' does not exist.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 32s`

`$ tns doctor
Your ANDROID_HOME environment variable is set and points to correct directory.
Your adb from the Android SDK is correctly installed.
The Android SDK is installed.
A compatible Android SDK for compilation is found.
Javac is installed and is configured properly.
The Java Development Kit (JDK) is installed and is configured properly.
Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
No issues were detected.
Component nativescript has 4.0.0 version and is up to date.
Component tns-core-modules is not installed.
Component tns-android is not installed.
`
### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 
i even created a new project with Sidekick and try to build but Build still fails! :(

**Comment by NickIliev** [comment]
@devyaz  It seems that the path where your project is located has a blank space in the name. The gradle build seems to fail while trying to find `C:\Users\Martin` where it should be l;ooking for `C:\Users\Martin Mtawali`. Please try moving your project to a folder with a path that doesn't contain empty spaces (e.g. `C:\test`) and rebuilding your project with deleted `node_modules`, `platforms` folders

**Comment by devyaz** [comment]
Hi Nick,

Thank you it worked!! J J I don’t understand why since it worked fine before in the same directory before!!

**Comment by NickIliev** [comment]
The latest Android runtime is using update gradle version which seems to be having troubles parsing paths with an empty space,
