### ISSUE TITLE
isUserInteractionEnabled not preventing tapping twice

### ISSUE THREAD

**Issue by arcovoltaico** [NativeScript/NativeScript#5804]
**Issue :**
When tap an element, the isUserInteractionEnabled is not working as expected. If I tap twice fast
this.action() is called twice.

**View :**
` <AbsoluteLayout  (tap)="requestSong(item.id, playlist)" [isUserInteractionEnabled]="buttoninteraction">
             <Image src="res://button"></Image>
     </AbsoluteLayout>`

**Component :**

`  export class SearchComponent implements OnInit {
    buttoninteraction = true;

       requestSong(item: string, playlist: string) {
                  this.buttoninteraction = false; 
                  this.action();
                } 

**Version details :**

Issue happening on iOS, as long as I know Android is not working with isUserInteractionEnabled and a workaround is required.

CLI 4.0.0
  Cross-platform modules "version": "4.0.0"

    "tns-ios": {
      "version": "4.0.1"
    },
    "tns-android": {
      "version": "4.0.1"

- Plugin(s): 

           `   dependencies": {
                   "@angular/animations": "^5.2.10",
                 "@angular/common": "^5.2.10",
                 "@angular/compiler": "^5.2.10",
                "@angular/core": "^5.2.10",
                 "@angular/forms": "^5.2.10",
                 "@angular/http": "^5.2.10",
                 "@angular/platform-browser": "^5.2.10",
                 "@angular/platform-browser-dynamic": "^5.2.10",
                  "@angular/router": "^5.2.10",
                  "email-validator": "^1.2.3",
                  "gulp-typescript": "^4.0.2",
                  "is-valid-birthdate": "^0.1.0",
                   "moment": "^2.22.1",
                   "nativescript-angular": "~5.2.0",
                   "nativescript-appversion": "^1.4.1",
                   "nativescript-directions": "^1.2.0",
                    "nativescript-facebook": "^2.2.2",
                    "nativescript-iqkeyboardmanager": "^1.3.0",
                   "nativescript-localize": "^2.3.2",
                    "nativescript-modal-datetimepicker": "^1.1.2",
                    "nativescript-pro-ui": "~3.3.0",
                     "nativescript-pulltorefresh": "^2.1.0",
                    "nativescript-social-share": "^1.5.0",
                    "nativescript-theme-core": "^1.0.4",
                    "nativescript-unit-test-runner": "^0.3.4",
                    "reflect-metadata": "~0.1.10",
                   "remove-accents-diacritics": "^1.0.2",
                   "rxjs": "^5.5.10",
                   "tns-core-modules": "^4.0.0",
                   "zone.js": "^0.8.26"
           },

**Comment by NickIliev** [comment]
@arcovoltaico the described scenario is working as expected on my side. I've used [this Playground demo ](https://play.nativescript.org)to test the case(tested on both iOS and Android). Let me know if there is anything I should change to reproduce the issue.

**Comment by tsonevn** [comment]
HI @arcovoltaico,
Were you able to recreate the issue with the attached by @NickIliev sample project?
