### ISSUE TITLE
How to disable scroll view in RadListView

### ISSUE THREAD

**Issue by pekubu** [NativeScript/NativeScript#5806]
I want disable scrollview in radlistview, because i use RadListView in ScrollView, scroll in radListView is very slow. Plz help me

**Comment by NickIliev** [comment]
It is not good practice to nest scrollable elements inside other scrollable elements. If the scroll in RadListView is slow, consider simplifying the item templates and if this doesn't resolve the issue open an issue describing the slow scroll problem [here](https://github.com/telerik/nativescript-ui-feedback/issues)

This repository is for logging issues, bugs and features related to NativeScript.
For how-to related questions please use the community channels like [the NativeScript forum](https://discourse.nativescript.org/), [SO ](https://stackoverflow.com/questions/tagged/nativescript)or [NativeScript community slack](https://nativescriptcommunity.slack.com/messages/general)

**Comment by MuhammadTahir92** [comment]
hey @NickIliev  i am not using multiple scrolls but i need to disable the scroll for rad list

**Comment by MuhammadTahir92** [comment]
How to limit the scroll view to not to scroll after certain condition meet lets suppose 
i am to scroll the list view only when the scroll value is in between 100 to 200 and not to scroll away from these two boundaries What can i do ?

**Comment by NickIliev** [comment]
@MuhammadTahir92 for issues related to nativpescript-ui controls use [this repository](https://github.com/telerik/nativescript-ui-feedback/issues). However, disabling the native scroll to wrap in scroll view is **really bad practice** (even if possible) as this way you would lose the virtualization and recycling of the RadListView which are both great performance related optimizations. If you are having a slow scroll please consider opening an issue in the linked repository explaining how to reproduce the problem (by providing a code base or Playground demo)
