### ISSUE TITLE
Label does not recognize awesome icons after change

### ISSUE THREAD

**Issue by pekubu** [NativeScript/NativeScript#5808]
`<Label text="&#xf03e;" class="fa-icon"></Label>`
If I do like it then it works. But if I change it, use TypeScript
`label.text = '&#xf03e;';`
It will only display the plaintext `(&#xf03e;)`. How to fix it
Thank you

**Comment by tsonevn** [comment]
Hi @pekubu,
If you are changing the icon string via code-behind you should use `fromCharCode` method, which will convert the needed char code in a string. You can find an example [here](https://docs.nativescript.org/ui/icon-fonts#the-code).
