### ISSUE TITLE
HtmlView only for single line?

### ISSUE THREAD

**Issue by emiloberg** [NativeScript/NativeScript#581]
Is the idea behind the HtmlView that it enables us to create a single line of html-formated code?

When I'm giving a HtmlView the html: `hi<br>by` it only displays the first line: `hi`.

The View is the simplest possible:
```
<Page xmlns="http://www.nativescript.org/tns.xsd" navigatingTo="navigatingTo" loaded="loaded">
        <StackLayout>
        <HtmlView html="{{html}}" />
        </StackLayout>
</Page>
```

Or am I doing something wrong here?

**Comment by vchimev** [comment]
Fixed in master branch - it is going to be part of our upcoming 1.3 release.
