### ISSUE TITLE
Animate properties with relative values

### ISSUE THREAD

**Issue by koder12** [NativeScript/NativeScript#5810]
Is there any way to animate the properties of the element with relative values,  like as in anime.js
```
translate: {
    x: '+=150'
}
```
or
```
rotate: '+=15'
```

**Comment by tsonevn** [comment]
Hi @koder12,
You can do this while defining the animation via code behind. You can set up a property for example, which contains the rotate angle and to increase its value before starting the animation. For example:
```
let rotateValue = 15;
function animate(args) {
    rotateValue+=15;
        
    console.log("Rotate value");
    console.log(rotateValue);
    myView.animate({
        backgroundColor: "#414b7d",
        curve: AnimationCurveEnum.easeOut,
        delay: 1,
        duration: 100,
        iterations: 1,
        opacity: 0.8,
        rotate: rotateValue
    }).then(() => {
        console.log("Animation finished");
    }).catch((e) => {
        console.log(e.message);
    });
    
   
}
```
Also, you can check [this ](https://github.com/NativeScript/nativescript-sdk-examples-js/tree/master/app/ui-category/animations/animating-properties) sample project, where it is demonstrated, how to define animation via code-behind.

**Comment by koder12** [comment]
Does the above code add 15 deg to the present rotate value (like if the element is already rotated to 30 deg and after the animation, it is now 45deg)?
