### ISSUE TITLE
Checkbox Component by default

### ISSUE THREAD

**Issue by jonorozcoc** [NativeScript/NativeScript#5821]
Why Checkbox component is no available by default in NativeScript components?, even I couldn't see it in pro ui package. I know there is a plugin that can be installed but I think that checkbox is an essential component which can't be omited.

I would like to see it in official package. Thanks for all your work

**Comment by tsonevn** [comment]
Hi @jonorozcoc,
Thank you for contacting NativeScript team,
We will investigate what would be the best way to implement a similar component in the core modules, and similar Checkbox component could be available for some of the next NS versions. You can keep track on the issue for further info. 
In the meantime, I would suggest using the [nativescript-checkbox](https://www.npmjs.com/package/nativescript-checkbox) plugin.

**Comment by jonorozcoc** [comment]
Hi @tsonevn,
At the moment the most suitable component in the core package is Switch component, it has almost the same behavior than a Checkbox.

**Comment by NickIliev** [comment]
The overall opinion is that the core modules (`@nativescript/core`) should be as light as possible and if there are already plugins that are implementing a component then there should be no need to introduce the same in the core modules (and this way making them larger). CLosing the feature request for the reasons above.
