### ISSUE TITLE
textTransform ignored for Android TabView items

### ISSUE THREAD

**Issue by BeMor81** [NativeScript/NativeScript#5826]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

Android

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) 4.0.0
- Cross-platform modules: (check the 'version' attribute in the 
`node_modules/tns-core-modules/package.json` file in your project) 4.0.0
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project) 4.0.1
- Plugin(s): (look for the version number in the `package.json` file of your
project)N/A

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

Using angular NativeScript setting the textTransform to none has no effect on the tab's title text and still shows all uppercase as per default. 

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

All the below ways seem to not work

<ng-template tabItem title="Favourites" textTransform="none" class="tabItem">

<StackLayout *tabItem="{textTransform: 'none', title: 'Favourites', iconSource: ios ? 'res://heart' : '', cssClasses: ['tabItem']}">

TabViewItem, .tabItem, tabItem {
  text-transform: none;
}

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1328
