### ISSUE TITLE
NSLocalizedDescription=An App ID with Identifier '...' is not available.

### ISSUE THREAD

**Issue by house-md** [NativeScript/NativeScript#5830]
### Tell us about the problem
I created new project, autogenerated files for IOS (prov. profile and certificate). And when I try to build it to my phone for test it ends with error "NSLocalizedDescription=An App ID with Identifier 'org.nativescript.mindeetest' is not available. Please enter a different string." I tried atleast 10 different ids but every time the same error.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): tns-ios 4.0.1
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
I created new project, autogenerated files for IOS (prov. profile and certificate). And when I try to build it to my phone for test it ends with error "NSLocalizedDescription=An App ID with Identifier 'org.nativescript.mindeetest' is not available. Please enter a different string." I tried more than 10 different ids but every time the same error.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
NO code added. it occured with auto-generated project

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3601
