### ISSUE TITLE
IOS - custom component in ListView - ripple problem

### ISSUE THREAD

**Issue by shabib3** [NativeScript/NativeScript#5842]
Hi,

it seems like the ListView has a ripple effect issue when use custom component as an item only on IOS.

When you have a listview with component as an item when you press on the item content all the things go great but when the user hit the ListView item background it the ripple effect is showing all over the item and gets upon the component.

this is issue is happen only on IOS - the behavior that expect for me it what is happen on android.

here is a playground example - https://play.nativescript.org/?template=play-ng&id=lMpsGb

Thank you very much! :)

**Comment by LeCaoPhuc** [comment]
You can try add event ItemLoading with code : 
 onItemLoading(args) {
        if (app.ios) {
            args.ios.selectionStyle = UITableViewCellSelectionStyle.None;
        }
    }

**Comment by tsonevn** [comment]
HI all, 
This issue seems to be related to the missing feature. Regarding that, I will mark this one as a feature request. We will research the case and will provide the needed functionality for setting up the selectionStyle for the ListView items. This functionality will be available for some of the next NativeScript versions. You can keep track on it for further info.

**Comment by shabib3** [comment]
@LeCaoPhuc -
How can I import `UITableViewCellSelectionStyle` ? (the vccode doesn't like it :) )

**Comment by shabib3** [comment]
@LeCaoPhuc -
How can I import `UITableViewCellSelectionStyle` ? (the vccode doesn't like it :) )

**Comment by NickIliev** [comment]
@shabib3 either use [tns-platform-declarations](https://www.npmjs.com/package/tns-platform-declarations) or directly d3eclare the variable and cast it to `any`

```
declare let UITableViewCellSelectionStyle: any;
```

I am recommending using the plugin (as `devDependency`) as it will provide you with IntelliSense for the native API

**Comment by LeCaoPhuc** [comment]
@NickIliev  is true . add it before @Component will resolve.

**Comment by shabib3** [comment]
@NickIliev - Thanks!

**Comment by NickIliev** [comment]
Closing the feature request as[ the provided solution](https://github.com/NativeScript/NativeScript/issues/5842#issuecomment-390540601) is a one-liner that works as expected.
