### ISSUE TITLE
Error. UI periodically is frozen if I am using looped route

### ISSUE THREAD

**Issue by gladiussdv** [NativeScript/NativeScript#5843]
1. Environment:

tns --version: 4.0.0
npm packages tns module: "tns-core-modules": "~4.0.0",
android (7.1): emulator and real device (zte axon 7 with android 7.1.1).

2. Reproduce.

a. Create basic application with 2 components and routing between they.
b. Create Labels with tap action on the first and on the second component.
c. Don't use "this.routerExtensions.back();" this code for going back to the previous page.  Instead of it use following code for both Labels: "this.router.navigate(['/firstComponent']);" and "this.router.navigate(['/secondComponent']);"
d. Click a few times on labels and transit between components a few times.

3. The result:

I notice that UI has freeze after this steps. And the more you execute the call of looped routes then more you will see freezes.

4. Addition info:

I have tried the following solutions that I have find in the internet:
a. remove gc() in onActivityDestroyd method:

onActivityDestroyed: profiling_1.profile("onActivityDestroyed", function (activity) {
            if (activity === androidApp.foregroundActivity) {
                androidApp.foregroundActivity = undefined;
            }
            if (activity === androidApp.startActivity) {
                androidApp.startActivity = undefined;
            }
            androidApp.notify({ eventName: ActivityDestroyed, object: androidApp, activity: activity });
            // gc();  !!!
        }),

b. add following code to package.json
"android": {
		"markingMode": "none"
	}
they don't help. I should just avoid this looped routes somehow. But it is not comfortable.

Also in my project I have lists and ActionBar on both components. And one component has tabs.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1337
