### ISSUE TITLE
Is there a plugin for data caching that is actively maintained?

### ISSUE THREAD

**Issue by jannotabamo** [NativeScript/NativeScript#5844]

**Comment by tsonevn** [comment]
Hi @jannotabamo,
For questions, please use our [forum ](https://discourse.nativescript.org/) or StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript). 
Meanwhile, you can check the [ApplicationSettings ](https://docs.nativescript.org/cookbook/application-settings) module and its functionality
