### ISSUE TITLE
(Question) Datepicker - select only month and year.

### ISSUE THREAD

**Issue by csi-stasik** [NativeScript/NativeScript#5845]
Hi, What is the way to hide the day in Datepicker and allow to choose only month and year? (Android & IOS)

I suppose I need to access native components of each platform, but i can't succeed to do that.

I have a reference of datePicker doing this:

```
...

 @ViewChild('datePicker') datePicker: ElementRef;

...

 ngOnInit() {

        const datePicker: DatePicker = this.datePicker.nativeElement;
        datePicker.minDate = new Date(this.params.context.min);
        datePicker.maxDate = new Date(this.params.context.max);
        
        let dayId = app.android.context.getResources().getIdentifier("android:id/day", null, null);  // <- I get some id
}

...
```

But how to use this dayId to setVisibility(View.GONE)?

`console.log(datePicker.android) // -> is always undefined.`

Thanks

**Comment by NickIliev** [comment]
@csi-stasik use the `loaded` event for DatePicker to get the reference to the native object. The Angular hook `ngOnInit` is triggered way earlier.

For example
```HTML
<DatePicker (loaded)="onDatePickerLoaded($event)" ></DatePicker>
```

and in the component file
```TypeScript
    onDatePickerLoaded(args) {
        const datePicker = <DatePicker>args.object;
        const nativeDP = datePicker.nativeView;

        console.log(androidDP); 
        // on Andorid: android.widget.DatePicker
        // on iOS: UIDatePicker

    }
```

**Comment by csi-stasik** [comment]
Ohh... Haven't thought about it, so easy. Thanks
