### ISSUE TITLE
I have never been able to get the android version running despite having the below mentioned dependencies installed

### ISSUE THREAD

**Issue by gjonakin** [NativeScript/NativeScript#5847]
I think this might be a pathing issue but I could be wrong. If it is a path problem, can you direct me how to fix it, not overly experienced over here. Thanks!

Here's what I get when I run a TNS Doctor:

Cannot find a compatible Android SDK for compilation. To be able to build for Android, install Android SDK 22 or later.
Run $ $ANDROID_HOME/tools/bin/sdkmanager to manage your Android SDK versions.

You need to have the Android SDK Build-tools installed on your system. You can install any version in the following range: '>=23 <=27'.
Run $ $ANDROID_HOME/tools/bin/sdkmanager from your command-line to install required Android Build Tools.

You need to have Android SDK 22 or later and the latest Android Support Repository installed on your system.
Run $ $ANDROID_HOME/tools/bin/sdkmanager to manage the Android Support Repository.

**Comment by NickIliev** [comment]
@gjonakin there are few things you should check:
- Verify that you have installed a compatible **Android SDK version** (versions 22 or later) and a compatible **Android SDK Build Tools** (e.g. version 25.0.2 or anything above 23)
- If all of the above is installed you need to check your `ANDROID_HOME` environment variable.
type in your shell
```
echo $ANDROID_HOME
```
If the command prints a path, verify that the SDK files are existing in the path. Important: If you have Android Studio installed open it and in `Tools > SDK Manager` verify that the path in `Android SDKLocation` field is the same as in your `$ANDROID_HOME` If the path is different change it to the one set as `$ANDROID_HOME`

**Comment by gjonakin** [comment]
am trying to figure out how to change the path to usr/local/share/android-sdk using the GUI in android studio. It won't let me see the hidden folders of which usr is a hidden folder. Do you know a workaround?

**Comment by NickIliev** [comment]
@gjonakin it depends on Android Studio version but the GUI (for changing SDK path) is usually located in **_Tools > SDK Manager > Android SDK Location (field)_**

Also the path `/usr/local/share/android-sdk` looks like a [symlink](https://en.wikipedia.org/wiki/Symbolic_link) so if that is the case try reading and setting the real path behind it (wh8ile using something like `readlink symlinkName` on OSX)
