### ISSUE TITLE
Help Needed - IOS - install app to beta testers before in is on the market

### ISSUE THREAD

**Issue by shabib3** [NativeScript/NativeScript#5848]
Hi,

Lately I am installing my NS app to beta testers users.
I am uploading the apk/ipa to https://www.diawi.com/ (platform for beta testers - exactly what I need).
When it comes to Android everything is good! :)
But when it comes to IOS it says that it cannot be install...So I connect the iPhone and try to install the app from the terminal and this is what it throw up:
```
Unable to apply changes on device: ed42ca6f8e4ec94f26e2d240e5cf9dbfc357b511. Error is: Failed to install
 /Users/barzaruk/Documents/Projects/staccato_lean_client/platforms/ios/build/device/staccatoleanclient.ipa
on device with identifier ed42ca6f8e4ec94f26e2d240e5cf9dbfc357b511. Error is: Could not install application.
```

after google a bit I saw this issue -> https://github.com/NativeScript/nativescript-cli/issues/3325

as I understand I cannot install the app on IOS device unless it passed the provision process.
Note: With my iPhone device I did all the provision process and it works.

So just so I know:
1. Is it a problem that will happen also after the app will upload to App Store? or that should be work?
2. Is there any platform that will help me with this issue of send an installation to beta testers before the app going up on the market?

Thanks a lot! :)

**Comment by rmathias86** [comment]
Are you using the individual apple developer account (non-enterprise)?
If so, are you sure you have added the device UUID in your apple developer account registered devices?

Your question 1: Unless the app is in the app store, only registered devices will be able to run the app.  
Your question 2: I'm have been using Hockeyapp platform, excellent for CI/CD.
