### ISSUE TITLE
Navigation breaks after closing modal and navigating back

### ISSUE THREAD

**Issue by tbozhikov** [NativeScript/NativeScript#5853]
### Tell us about the problem
Navigation stops working after closing modal and navigating back a couple of times.

### Which platform(s) does your issue occur on?
Both, Angular

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): 4.0.1

### Please tell us how to recreate the issue in as much detail as possible.
In an Angular {N} app:
1. Start an app at component HOME
2. navigate to component A
3. navigate to component B
4. open modal dialog
5. close the dialog
6. navigate back to component A using
`this._routerExtensions.backToPreviousPage() `
7. navigate back to component HOME using
`this._routerExtensions.backToPreviousPage() `

This error is logged in the console:
CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:1682:24: ERROR Error: Calling startGoBack while going back.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1350
