### ISSUE TITLE
[iOS] ScrollView does not layout properly when NavigationBar is not translucent

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#5855]
### Tell us about the problem
When setting [`translucent`](https://developer.apple.com/documentation/uikit/uinavigationbar/1624928-translucent) property of NavigationBar to `false` and have `ScrollView` as direct child of `Page`, it is not layouted properly.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0
- Cross-platform modules: 4.0.0
- Runtime: 4.0.0

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" backgroundColor="green">
    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar" flat="true" />
    </Page.actionBar>
    <ScrollView>
        <TextView text="Lorem ipsum" />
    </ScrollView>
</Page>
```
### Actual Result
![scrollview](https://user-images.githubusercontent.com/12251337/40426273-4e83d094-5ea3-11e8-90bb-63ca394511cd.png)

### Expected Result
`ScrollView` should be layouted just below the NavigationBar without a gap.

### Workarounds
- set `page.scrollableContent = false;`
or
- wrap `ScrollView` in `GridLayout` for example

**Comment by victorevox** [comment]
Hi there, dont know if this issue I'm having is the same the one mentioned here but, after upgrading from NS4 to NS5 my flat action bar adds a gap.

Before, in NS 4
![screenshot from 2019-02-01 14-47-56](https://user-images.githubusercontent.com/17477657/52149402-3ae7c980-2632-11e9-8da5-1d0728b415ea.png)

After, in NS5
![screenshot from 2019-02-01 15-00-00](https://user-images.githubusercontent.com/17477657/52149419-49ce7c00-2632-11e9-8084-6872a7fa172f.png)


Do you know any workaround for this?

**Comment by victorevox** [comment]
> @victorevox Please, provide a code sample or a playground with your layout.

Hi @MartoYankov , thanks for checking, please see: https://play.nativescript.org/?template=play-ng&id=ZyeGeF&v=3
