### ISSUE TITLE
Binding trivial expressions

### ISSUE THREAD

**Issue by webleaf** [NativeScript/NativeScript#5858]
```
<!-- work -->       <Label text="Some text" visibility="{{ '', 'collapse' }}"/>
<!-- work -->       <Label text="Some text" visibility="{{ null, 'collapse' }}"/>
<!-- work -->       <Label text="Some text" visibility="{{ undefined, 'collapse' }}"/>
<!-- work -->       <Label text="Some text" visibility="{{ isCollapsed ? 'collapse' : 'visible'}}"/>
<!-- don't work --> <Label text="Some text" visibility="{{ 'collapse' }}"/>
```

Now with SideDrawer:
```
<!-- work -->       <nsDrawer:RadSideDrawer gesturesEnabled="{{ isGesturesEnabled }}" xmlns:nsDrawer="nativescript-ui-sidedrawer" loaded="onSideDrawerLoaded">
<!-- work -->       <nsDrawer:RadSideDrawer gesturesEnabled="{{ isGesturesEnabled ? true : false }}" xmlns:nsDrawer="nativescript-ui-sidedrawer" loaded="onSideDrawerLoaded">
<!-- work -->       <nsDrawer:RadSideDrawer gesturesEnabled="{{ '', false }}" xmlns:nsDrawer="nativescript-ui-sidedrawer" loaded="onSideDrawerLoaded">
<!-- work -->       <nsDrawer:RadSideDrawer gesturesEnabled="{{ null, false }}" xmlns:nsDrawer="nativescript-ui-sidedrawer" loaded="onSideDrawerLoaded">
<!-- work -->       <nsDrawer:RadSideDrawer gesturesEnabled="{{ undefined, false }}" xmlns:nsDrawer="nativescript-ui-sidedrawer" loaded="onSideDrawerLoaded">
<!-- work -->       <nsDrawer:RadSideDrawer gesturesEnabled="{{ true ? false : true }}" xmlns:nsDrawer="nativescript-ui-sidedrawer" loaded="onSideDrawerLoaded">
<!-- work -->       <nsDrawer:RadSideDrawer gesturesEnabled="{{ !true }}" xmlns:nsDrawer="nativescript-ui-sidedrawer" loaded="onSideDrawerLoaded">
<!-- don't work --> <nsDrawer:RadSideDrawer gesturesEnabled="{{ false }}" xmlns:nsDrawer="nativescript-ui-sidedrawer" loaded="onSideDrawerLoaded">
```
This cases don't make a lot of sense. But it's first what i try to do, to check that all works as expected, and then spend a lot of time, to find error, because i don't understand why trivial expressions should not work.

Tested for Android only.
My package.json is:
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.blankts",
    "tns-android": {
      "version": "4.0.1"
    }
  },
  "dependencies": {
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-sidedrawer": "^4.1.0",
    "tns-core-modules": "4.0.1"
  },
  "devDependencies": {
    "awesome-typescript-loader": "~3.1.3",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "~0.1.19",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.10.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "typescript": "~2.7.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  }
}
```

**Comment by NickIliev** [comment]
@webleaf can you clarify what is the issue here? 

 In your last Label example, it would make sense that the binding won't work with a string value as the visibility is expecting not any string but specific values of the `visibility; property. You are trying to pass the value directly but that would break any two-way binding (all XML created bindings are two-way by design). So you could create a binded string property like 
```XML
<Label text="Some text" visibility="{{ myCollapse }}"/>
```

where `myCollapse` is
```TypeScript
this.myCollapse = "collapse";
```

Or directly use the string value without any binding
```XML
<Label text="Some text" visibility="collapse"/>
```

**Comment by webleaf** [comment]
@NickIliev 
Is `!true` trivial expression? I think yes. Should `gesturesEnabled="{{ !true }}"` works? Yes. Does it works? Yes.
Is `false` trivial expression? I think yes. Should `gesturesEnabled="{{ false }}"` works? Yes. Does it works? **No**.
That's the issue.
Same with `visibility="{{ 'collapse' }}"`. It's just formal logic.

**Comment by NickIliev** [comment]
@webleaf if you need to provide a static text you could add it to your source property by using an expression (like you have done in the first 4 labels in your example).More details about expression can be found [here ](https://docs.nativescript.org/core-concepts/data-binding#using-expressions-for-bindings).  Trivial binding using a direct value is not supported out-of-the-box for strings. However the observation with different behaviour for setting true/false values might be related to [this known issue ](https://github.com/NativeScript/NativeScript/issues/5694#issuecomment-382006391)(fix in the upcoming release)

**Comment by webleaf** [comment]
I got situation where I need this. [RadListView multipleSelection](https://docs.telerik.com/devtools/nativescript-ui/api/classes/radlistview.html#multipleselection) property have type `boolean`. But via XML it sets as `string`
```
<lv:RadListView multipleSelection="true">
```
And I use it in my plugin. So in my XML I do:
```
<lv:RadListView multipleSelection="{{ isMultiSelectionEnabled }}">
```
Now I expect that I will work with boolean value, when I use my plugin/widget. I do something like this:
```
<MyWidget:MyWidget isMultiSelectionEnabled="true"/>
```
It works. And RadListView "correctly" convert this string to `boolean`. But in code side I have string value `"true"`
Then I try 
```
<MyWidget:MyWidget isMultiSelectionEnabled="{{ true }}"/>
```
...of course this don't works as mentioned in issue description
