### ISSUE TITLE
NativeScript plugin size is small but app get bigger

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/NativeScript#5859]
Hey all,
I use [nativescript-fresco](https://github.com/NativeScript/nativescript-fresco) plugin in my NativeScript app. After installing, I see nativescript-fresco folder in node_modules is about 150kb. But when I build my app, the app size grows more than to 1mg. Any idea?

**Comment by tsonevn** [comment]
Hi @vahidvdn,
`nativescript-fresco` depends on `com.facebook.fresco:fresco`  library. This native library is downloaded in the project folder while instaling the plugin and perhaps is the reason for this increase the app size with 1mb.
Bear in mind that some nativescript plugins depend on native libraries, which size cannot be control by nativescript. However, you can use [ABI splits](https://docs.nativescript.org/publishing/android-abi-split) to make the APK much smaller.

**Comment by vahidvdn** [comment]
@tsonevn Thanks. I had forgotten about native library.
