### ISSUE TITLE
Help. Device orientation (alpha, beta, gamma angles)

### ISSUE THREAD

**Issue by csi-stasik** [NativeScript/NativeScript#5860]
Hi.

How to access device orientation alpha, beta and gamma angles in nativescript? I was wondering because I did not found any information about this (only portrait and landscape are supported). This from my point of view should be the basic feature. Even in HTML5 is very easy to implement.

There is one library Core Motion only for IOS but why Android is not supported? What is the technical problem?

Thank you.

**Comment by tsonevn** [comment]
Hi @csi-stasik,
You can check [native-script-accelerometer](https://github.com/vakrilov/native-script-accelerometer) plugin and the functionality, which provides.

For further questions, please use our [forum](https://discourse.nativescript.org/) or StackOverflow [thread](https://stackoverflow.com/questions/11235370/android-emulator-doesnt-take-keyboard-input-sdk-tools-rev-20).

**Comment by csi-stasik** [comment]
Thanks @tsonevn (next time i will use the forum)

I come from phone gap world and Accelerometer was another thing (displays only the acceleration value) I will try.. hope i will get the desired result.
