### ISSUE TITLE
[iOS] Flat ActionBars, transition animations & ScrollView issue 

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#5870]
### Tell us about the problem
I define ActionBars with `flat="true"` to get the most correct color on the ActionBar.  When navigating to Pages and using transitions animation, the layout becomes messed up. There is a big gap between the actionbar and the first element of the page. Removing `flat` or the transition animation removes the issue, but is not a solution.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.2
- Cross-platform modules: 4.0.1
- Runtime(s): 4.0.1

**Comment by tsonevn** [comment]
Duplicate of [#5768](https://github.com/NativeScript/NativeScript/issues/5768)

**Comment by manijak** [comment]
@tsonevn Ok? how are the two cases related? The issue is very much present in 4.1.2

**Comment by tsonevn** [comment]
HI @manijak,
Excuse me. I misunderstood the problem, which you are facing. I tested further the issue with the latest NativeScirpt 4.1, however, was unable to recreate the problem. For your convenience, I am attaching the sample project and the screenshots from the simulator, which I used for testing. Can you review the project and check if I am missing something? It will help if you provide some more info about the case and the way it can be reproduced.
![screen shot 2018-06-27 at 9 38 19 am](https://user-images.githubusercontent.com/17448734/41957223-ed074834-79ee-11e8-9f4f-62a401c79737.png)
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2140040/Archive.zip)

**Comment by manijak** [comment]
No problem @tsonevn, should have provided you with a demo app from the start.
The issue is more delicate, it is a combination of several things:
- `flat="true"` on all ActionBars
- onTap navigation has a animationTransition (e.g. Slide or Fade)
- The first element of the `page2` is a `ScrollView`

Results in:
![flatdemo_issue](https://user-images.githubusercontent.com/3605066/41961241-394b55e8-79f2-11e8-9492-377449d8bb25.PNG)

Updated the demo app you provided with changes: 
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2140316/Archive.zip)

**Comment by MartoYankov** [comment]
This issue is fixed in 5.2 with https://github.com/NativeScript/NativeScript/pull/6862
