### ISSUE TITLE
A float[] array?

### ISSUE THREAD

**Issue by xeroxstar** [NativeScript/NativeScript#5874]
Hello, it's not a bug rather a question that i am struggling to answer, i am trying to pass a float[] from native script to java but i find no way to do it:

Here is a code:
```
 float[] colorTransform = {
            0, 1f, 0, 0, 0, 
            0, 0, 0f, 0, 0,
            0, 0, 0, 0f, 0, 
            0, 0, 0, 1f, 0
};

    ColorMatrix colorMatrix = new ColorMatrix();
    colorMatrix.setSaturation(0f); //Remove Colour 
    colorMatrix.set(colorTransform);
```

How can i create a float array for colorTransform  in nativescript? Thanks!

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#1071
