### ISSUE TITLE
iOS not being able to retrieve image from ASP.Net response (HTTP load failed)

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#5877]
Image sources retrieved via response from ASP.Net Web API are causing TCP error on some networks

Steps to reproduce:
```
<StackLayout class="p-20" height="500" backgroundColor="lightgray">
    <!-- working -->
    <Image src="http://23.97.179.10:8081/images/roundLogo.png" width="50" stretch="aspectFit" marginBottom="20"/>
    <!-- NOT working -->
    <Image src="http://23.97.179.10:8081/api/MobileCommon/GetUserImage?userName=Admin" width="50" stretch="aspectFit" />
</StackLayout>
```

Result: Works as expected on Android or on mobile networks but fails on some WiFi network with the following system log
```
tcp_timers tcp[1] retransmit SYN 3
XPC connection invalidated (daemon unloaded or disabled)
client.trigger:#N CCFG for cid 0x35 has # of profiles: 0
tcp_timers tcp[1] retransmit SYN 4
tcp_timers tcp[1] retransmit SYN 5
tcp_timers tcp[1] retransmit SYN 6
tcp_timers tcp[1] retransmit SYN 7
tcp_timers tcp[1] retransmit SYN 8
tcp_timers tcp[1] retransmit SYN 9
Task <38F44BB4-B42B-4F2D-A343-85FD73352F7E>.<1> finished with error - code: -1001
TIC TCP Conn Cancel [1:0x1c0177a00]
[1 <private> stream, pid: 823, url: http://23.97.179.10:8081/api/MobileCommon/GetUserImage?userName=Admin] cancelled. Events:
0.000s [1 49041294-2198-4274-ABBE-9EB2BD6E089B 192.168.90.44:63156-><private> channel-flow] path:start
0.000s [1 49041294-2198-4274-ABBE-9EB2BD6E089B 192.168.90.44:63156-><private> channel-flow] path:satisfied
CONSOLE LOG file:///app/main-page.js:37:20: err:  Error: The request timed out.
0.001s [1 49041294-2198-4274-ABBE-9EB2BD6E089B 192.168.90.44:63156-><private> channel-flow] flow:start_nexus
0.001s [1 49041294-2198-4274-ABBE-9EB2BD6E089B 192.168.90.44:63156-><private> channel-flow] flow:receive_nexus
0.003s [1 49041294-2198-4274-ABBE-9EB2BD6E089B 192.168.90.44:63156-><private> channel-flow] flow:start_connect
60.302s [1] path:cancel
Task <38F44BB4-B42B-4F2D-A343-85FD73352F7E>.<1> HTTP load failed (error code: -999 [1:89])
TIC TCP Conn Destroyed [1:0x1c0177a00]
```

Test application can be found [here](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/others/t1169433). Note that we need explicit permissions to load arbitrary loads as done [here](https://github.com/NickIliev/NS-Issues-2018-II/blob/master/others/t1169433/app/App_Resources/iOS/Info.plist#L46-L50)

**Comment by NickIliev** [comment]
Above example is using a custom port to make HTTP call. Might be related [to this](https://github.com/NativeScript/nativescript-angular/issues/927#issuecomment-393111981)

**Comment by NickIliev** [comment]
After additional investigation, it seems that the issue is reproducible only when working within a restricted newtwork with limited access for some ports. Explicitly allowing the use of that port from the network or [changing the default port on the ASP Net ](https://msdn.microsoft.com/en-us/library/ms178109.aspx) should resolve the case.

Removing the `bug` tag as the issue is not related n how NativeScript works abut is related to environment configuration for used network.

**Comment by NickIliev** [comment]
Using the latest NativeScript (modules and runtime) and [the base test project](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/others/t1169433) the issue seems not to be reproducible even when testing from a restricted WiFi network.

**Comment by slaven3kopic** [comment]
I am getting the same problem using the Node(express.js) server. It occurs on NativeScript version 5.1.0. It only happens for the iOS. Android is working fine. Problem appears only when using restricted network. After connecting to other network, app works normally. I've tried to change the server port, it doesn't help. @NickIliev do you maybe know what can be the solution?

`60.851s [3] path:cancel
Task <7841F9CE-F111-4898-982C-B43693BE9435>.<3> HTTP load failed (error code: -999 [1:89])
TIC TCP Conn Destroyed [3:0x1c4368d00]`
