### ISSUE TITLE
Gradient Not working

### ISSUE THREAD

**Issue by yeomann** [NativeScript/NativeScript#5880]
### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.2
- Runtime(s): 
"tns-ios": {
      "version": "4.0.1"
    },
    "tns-android": {
      "version": "4.0.1"
    }

### Please tell us how to recreate the issue in as much detail as possible.
Just added 
`.bottom-gradient {
    background: linear-gradient(to bottom, orangered, green, lightblue);
}`
in home.component.css and added that class in html. 
Play ground: https://play.nativescript.org/?template=play-ng&id=IIMjKm

also see screenshot from my mobile. 

![screenshot_20180529-143631](https://user-images.githubusercontent.com/5970751/40657371-4964cada-6350-11e8-87c8-01ae113bbb6a.png)

**Comment by NickIliev** [comment]
Hey @yeomann the gradient functionality will be officially included in the upcoming release and is not supported with tns-core-modules@4.0.0.

For testing purposes you could install the `next` version of tns-core-modules
```
npm i tns-core-modules@next
```

**Comment by NickIliev** [comment]
@yeomann the article containing the linear gradient examples was published ahead of the release for which I apologize. The official release is expected within few days.
