### ISSUE TITLE
How to collaborate on a NativeScript project?

### ISSUE THREAD

**Issue by msarsha** [NativeScript/NativeScript#5882]
Hey,

We are two devs trying to collaborate building a NS app but having issues.

We started with the tabs template on one machine (windows), pushed the code to GH and then pulling to the 2nd machine (mac) - everything worked.

Our issue happen after adding tns plugins on one machine - where everything works. but once pulled to the 2nd machine we having problems building for both ios and android.

What steps should be taken on both machines when adding tns plugins?

Should the platforms/ folder be pushed to remote?

**Comment by NathanaelA** [comment]
@msarsha - When you pull the repo from github;
- `npm i`
- `tns platform add android`  (if using android)
- `tns platform add ios` (if using ios)

Should get you back and running on the new machine.  Please note; in your repo you do NOT want to put `node_modules` or `platforms` under version control; they should both be ignored and not commited.

**Comment by msarsha** [comment]
Awesome, so there is no need for any ‘tns plugin add ...’ commands.

But we should communicate about changes on android manifest for example
because platforms is not under source control.
