### ISSUE TITLE
IllegalArgumentException when changing chart bounds

### ISSUE THREAD

**Issue by danbockapps** [NativeScript/NativeScript#5883]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes, there are no Google results for "minimum for an axis cannot be greater than its current maximum"(until now)

### Tell us about the problem
I should be able to change both axis mimimum and maximum at the same time, as long as I keep the maximum greater than the minimum. But I get this when I try to increase both bounds:

`java.lang.IllegalArgumentException: minimum for an axis cannot be greater than its current maximum`

I'm guessing it's because the _new_ minimum is being compared to the _old_ maximum.

I can _decrease_ both minimum and maximum without an error.

I suspect this is specific to Angular, but I don't know how to develop NativeScript apps any other way in order to test that.

### Which platform(s) does your issue occur on?
Android only. There's no error on iOS.

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.2
- Cross-platform modules: 4.0.1
- Runtime(s): 4.0.1
- nativescript-ui-chart 3.6.0

### Please tell us how to recreate the issue in as much detail as possible.
https://play.nativescript.org/?template=play-ng&id=3mcpYT&v=11
If you click on "Increase bounds", you get the error. Click "Decrease bounds" and you don't get an error.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```
	<RadCartesianChart tkExampleTitle tkToggleNavButton height=300>
		<DateTimeContinuousAxis tkCartesianHorizontalAxis majorStep="Week" dateFormat="MM-dd" labelFitMode="Rotate" labelRotationAngle="1.2">
		</DateTimeContinuousAxis>
		<LinearAxis tkCartesianVerticalAxis [minimum]="bounds.graphWeightMin" [maximum]="bounds.graphWeightMax" [ios.offset]="bounds.graphWeightMin"
		[ios.baseline]="bounds.graphWeightMin">
		</LinearAxis>
		<LineSeries tkCartesianSeries [items]="weightData" categoryProperty="date" valueProperty="weight">
		</LineSeries>
	</RadCartesianChart>

    ngOnInit(): void {
        this.bounds = new WeightGraphBounds(100, 95);
    }

    onIncreaseTap(): void {
        // This causes an error (Android only)
        this.bounds = new WeightGraphBounds(110, 105);
    }
```

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#681
