### ISSUE TITLE
Errors don't show in console when they're in an Observable's subscribe method

### ISSUE THREAD

**Issue by danbockapps** [NativeScript/NativeScript#5884]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
I didn't find anything. Got no answer [here](https://discourse.nativescript.org/t/errors-dont-show-in-console-when-theyre-in-an-observables-subscribe-method/6089).

### Tell us about the problem
Usually when there’s an error, the error is printed in the console. But it seems that if that error happens inside an Observable’s subscribe method, there’s no sign of it in the console. So my app doesn't work and I don't get any clue about why.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.2
- Cross-platform modules: 4.0.1
- Runtime(s): 4.0.1

### Please tell us how to recreate the issue in as much detail as possible.
https://play.nativescript.org/?template=play-ng&id=tCZ7sW&v=3

Line 19 of home.component.ts should print error details to the console, but it doesn't.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```
        this.homeService.getData().subscribe(
            (data) => {
                console.log("I'm about to throw an error...");
                throw new Error("I'm an error.");
                // ^^ Nothing shows in the console ^^
            },
            (error) => {
                console.log("Error getting data");
                console.log(error);
            }
        )
```

**Comment by tsonevn** [comment]
Hi @danbockapps,
Thank you for the provided sample project.
I tested this case on my side and was able to recreate the issue. 
We logged this as a bug, and we will investigate further the problem. You can keep track on the issue for more info.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1352

**Comment by ghuser** [comment]
The same happens with promises (both linux and windows), on a non-angular project.

tns create ExampleProject --template nativescript-template-tutorial

main-page.js

exports.pageLoaded = function() {  
    fetch("https://github.com").then(()=>{throw Error("should see this on the console")})
};
tns run android

Nothing shown on the console

**Comment by tsonevn** [comment]
HI @danbockapps,
In this scenario, you should add catch at the end of the request, which will handle the thrown error. For example:
```
fetch("https://httpbin.org/get")
    .then((response) => {
               throw Error("should see this on the console")
               return response.json();
     })
    .then((r) => {
        viewModel.set("host", r.headers.Host);
        viewModel.set("userAgent", r.headers["User-Agent"]);
        viewModel.set("origin", r.origin);
        viewModel.set("url", r.url);
    }).catch((err) => {
        console.log("Error: ");
        console.log(err);
    });
```

**Comment by ghuser** [comment]
Is the issue fixed?
Adding a catch is just a workaround for the bug.

See the differrence in the browser or in the [node-fetch](https://github.com/bitinn/node-fetch).

**Comment by NickIliev** [comment]
@ghuser the node-fetch library has their own way of handling errors see the[ ERROR-HANDLING.md](https://github.com/bitinn/node-fetch/blob/master/ERROR-HANDLING.md)

From that markdown notice the following:

> Because window.fetch isn't designed to be transparent about the cause of request errors, we have to come up with our own solutions.
> 
> The basics:
> 
> All operational errors are rejected with a FetchError. You can handle them all through the promise catch clause.
