### ISSUE TITLE
Page events are multiplied when application is refreshed on android

### ISSUE THREAD

**Issue by muntyan** [NativeScript/NativeScript#5886]
Steps to reproduce:
1) tns create hello
2) in the app\main-page.js, add console.log("navigatingTo") to onNavigatingTo() function
3) tns run android
4) once it's running in the emulator, resave app\main-page.js file to make it refresh the application in emulator. 
Result: it will print "JS: navigatingTo" twice. 
```
ActivityManager: Start proc 10756:org.nativescript.hello/u0a94 for activity org.nativescript.hello/com.tns.NativeScriptActivity
JS: navigatingTo
JS: navigatingTo
```
Save again, and it will print that three times, etc. Same thing happens with other page events - loaded, unloaded, navigatedTo.

This is a weird bug, and I don't really understand what's happening. In the actual app I got, I have a joystick control from a native java library (created with Placeholder), and this bug results in joystick events generated several times per actual mouse event. It's possible that the multiplied page events above have nothing to do with my joystick problem, but the number of times joystick events are triggered is the same as the number of page events, so it looks related. It's not easy to post the actual application, and it has 3rd-party dependencies so it may not be helpful.

CLI version: 4.0.2
modules version: 4.0.1
runtime version: 4.0.1

**Comment by tsonevn** [comment]
HI @muntyan,
I tested your case on my side while following the provided steps, however, was unable to recreate the issue.
Regarding that, Make sure that there is only one emulator started on your machine, and there are no other Android devices connected to it. If there is more then one emulator running or there is a device connected, `tns run android` command will deploy and run the app on both and the navigatinTo event will be executed two times.

If the issue is happening when there is only one emulator started, try removing the platform via `tns platform remove android`, delete node_modules and package-lock.json file and try again to rebuild the app. If the problem persists, please send us the project, where this problem happened.

**Comment by muntyan** [comment]
I can repro with hello world, just like in repro steps. You sure you resaved the js file and it refreshed the app while the app was running in the emulator? Here's sample output after I did this several times (I added prints to other events as well):

```
Successfully transferred main-page.js.
Refreshing application...
Successfully synced application org.nativescript.tnshellots on device emulator-5554.
ActivityManager: Start proc 13523:org.nativescript.tnshellots/u0a92 for activity org.nativescript.tnshellots/com.tns.NativeScriptActivity
JS: navigatingTo
JS: navigatingTo
JS: navigatingTo
JS: navigatingTo
JS: navigatingTo
JS: navigatingTo
JS: navigatingTo
JS: navigatingTo
JS: navigatingTo
JS: creatingView
JS: creatingView
JS: creatingView
JS: creatingView
JS: creatingView
JS: creatingView
JS: creatingView
JS: creatingView
JS: creatingView
JS: loaded
JS: loaded
JS: loaded
JS: loaded
JS: loaded
JS: loaded
JS: loaded
JS: loaded
JS: loaded
JS: navigatedTo
JS: navigatedTo
JS: navigatedTo
JS: navigatedTo
JS: navigatedTo
JS: navigatedTo
JS: navigatedTo
JS: navigatedTo
JS: navigatedTo
```

Sometimes the output is different and it prints first the following before printing the above. I am not doing anything differently, just hitting Ctrl-S in vs code.

```
Successfully transferred main-page.js.
Refreshing application...
JS: navigatingTo
JS: navigatingTo
JS: navigatingTo
JS: navigatingTo
JS: navigatingTo
JS: navigatingTo
JS: navigatingTo
JS: navigatingTo
JS: navigatingTo
JS: creatingView
JS: creatingView
JS: creatingView
JS: creatingView
JS: creatingView
JS: creatingView
JS: creatingView
JS: creatingView
JS: creatingView
JS: loaded
JS: loaded
JS: loaded
JS: loaded
JS: loaded
JS: loaded
JS: loaded
JS: loaded
JS: loaded
JS: unloaded
JS: unloaded
JS: unloaded
JS: unloaded
JS: unloaded
JS: unloaded
JS: unloaded
JS: unloaded
JS: unloaded
JS: navigatedTo
JS: navigatedTo
JS: navigatedTo
JS: navigatedTo
JS: navigatedTo
JS: navigatedTo
JS: navigatedTo
JS: navigatedTo
JS: navigatedTo
ActivityManager: Killing 13523:org.nativescript.tnshellots/u0a92 (adj 0): stop org.nativescript.tnshellots
ActivityManager: Killing 13523:org.nativescript.tnshellots/u0a92 (adj 0): stop org.nativescript.tnshellots
ActivityManager: Killing 13523:org.nativescript.tnshellots/u0a92 (adj 0): stop org.nativescript.tnshellots
ActivityManager: Killing 13523:org.nativescript.tnshellots/u0a92 (adj 0): stop org.nativescript.tnshellots
ActivityManager: Killing 13523:org.nativescript.tnshellots/u0a92 (adj 0): stop org.nativescript.tnshellots
ActivityManager: Killing 13523:org.nativescript.tnshellots/u0a92 (adj 0): stop org.nativescript.tnshellots
ActivityManager: Killing 13523:org.nativescript.tnshellots/u0a92 (adj 0): stop org.nativescript.tnshellots
ActivityManager: Killing 13523:org.nativescript.tnshellots/u0a92 (adj 0): stop org.nativescript.tnshellots
ActivityManager: Killing 13523:org.nativescript.tnshellots/u0a92 (adj 0): stop org.nativescript.tnshellots
ActivityManager: setHasOverlayUi called on unknown pid: 13523
ActivityManager: setHasOverlayUi called on unknown pid: 13523
ActivityManager: setHasOverlayUi called on unknown pid: 13523
ActivityManager: setHasOverlayUi called on unknown pid: 13523
ActivityManager: setHasOverlayUi called on unknown pid: 13523
ActivityManager: setHasOverlayUi called on unknown pid: 13523
ActivityManager: setHasOverlayUi called on unknown pid: 13523
ActivityManager: setHasOverlayUi called on unknown pid: 13523
ActivityManager: setHasOverlayUi called on unknown pid: 13523
```

**Comment by tsonevn** [comment]
Hi @muntyan,
Indeed I tested the case while resaving the JS file. The app was rebuild, and only one console.log was printed. For your convenience, I am attaching GIF file, where this is demonstrated. I tested the scenario on Windows PC and Mac and in both cases the behaviour is the same.
![screencast 2018-05-30 at 9 10 06 am](https://user-images.githubusercontent.com/17448734/40703413-b25a1552-63ed-11e8-884c-ec4d371b96a8.gif)

Can you provide more info about your emulator and its API level? In the meantime, You can create a new one and test whether the same issue will be reproduced after you build the app on it.

**Comment by NathanaelA** [comment]
@tsonevn - I've seen this issue many times.   Seems to be random to when it wants to hit; never bothered to trace it down as it only occurs because of livesync'ing not an issue that occurs on a release version.

**Comment by NathanaelA** [comment]
Of course when I want it to duplicate it won't duplicate.  I just tried a sample in Android 4.4 and 7.0 emulators and it is working properly for me right now.   Not sure what triggers it.   If I can come up with duplicatable steps I'll post them..

**Comment by muntyan** [comment]
Android tools here are installed by Android Studio.
Android Emulator: 27.2.9
Image: Google Play Intel Atom (x86), google_apis_playstore [Google Play] (API level 26)

I will check release build once I figure out what to pass to --key-store* options.

**Comment by muntyan** [comment]
Created a different emulator, API 24 this time, I see the same thing.

tns run android --release doesn't product the same result simply because it isn't watching file changes, so there is no refreshing the application.

**Comment by muntyan** [comment]
One interesting thing, sometimes events are interleaving. When I click the joystick control in my app, it's supposed to generate Down, Drag, Up (i.e. press, move, release), and I see the following. Super weird.
```
JS: onDown
JS: onDrag(178.9070281982422, 1)
JS: onDown
JS: onDrag(178.9070281982422, 1)
JS: onUp
JS: onUp
```

**Comment by tsonevn** [comment]
HI @muntyan,
Excuse me for the delay in reply.
I investigated further your case, however, I am still unable to recreate this case on my side.
Something that I can suggest is to review the[ active processes](https://www.digitalcitizen.life/command-prompt-advanced-commands-system-information-managing-active-tasks) in the machine when the problem appears and check how many live sync processes have been started.

**Comment by rlewis86** [comment]
Has anyone found a fix for this issue?

**Comment by tsonevn** [comment]
HI @rlewis86,
Can you check if you have only one [active live sync process ](https://github.com/NativeScript/NativeScript/issues/5886#issuecomment-397529667)on your machine? Also, you can try deleting platforms, node_modules folder and rebuild the project. It will help if you provide more info about your environment(node, NativeScript CLI, tns-core-modules, runtime versions.)

**Comment by rlewis86** [comment]
@tsonevn thank you for the response!

I deleted the platforms, node_modules, and hooks folders.  Then I ran npm install and rebuilt the project.  It has no problem running on my android emulator, but every time I have a livesync refresh, it duplicates all events.

This is happening on 2 different windows machines.  When I install Nativescript, I let the Powershell script run to configure my android environment.

First machine: 
Windows 10
node v10.0.0
Android API 25 on Pixel AVD
Project created with NativeScript Sidekick - Master-Detail (with Firebase)
package.json:
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.NewApp",
    "tns-android": {
      "version": "4.1.3"
    }
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "~6.0.6",
    "@angular/common": "~6.0.6",
    "@angular/compiler": "~6.0.6",
    "@angular/core": "~6.0.6",
    "@angular/forms": "~6.0.6",
    "@angular/http": "~6.0.6",
    "@angular/platform-browser": "~6.0.6",
    "@angular/platform-browser-dynamic": "~6.0.6",
    "@angular/router": "~6.0.6",
    "nativescript-angular": "~6.0.6",
    "nativescript-imagepicker": "~5.0.0",
    "nativescript-plugin-firebase": "~6.0.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-listview": "~3.5.0",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.1.0",
    "tns-core-modules": "4.1.0",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~6.1.0-beta.3",
    "@ngtools/webpack": "~6.1.0-rc.0",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "codelyzer": "~4.3.0",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "~1.6.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.14.0",
    "tslint": "~5.10.0",
    "typescript": "~2.7.2"
  }
}
```
This is what I get in the console one one livesync refresh: 
![duplicated events](https://user-images.githubusercontent.com/18204245/42449076-513a19f0-834d-11e8-9b50-ff7e10da3ab3.PNG)

After 2 livesync refreshes:
![duplicated events 2](https://user-images.githubusercontent.com/18204245/42449167-b1490c48-834d-11e8-928e-55b1dcb93c5c.PNG)

I'll leave another comment from my other machine with the environment setup.
