### ISSUE TITLE
Loading images from local file system: Image not showing up

### ISSUE THREAD

**Issue by alereisan** [NativeScript/NativeScript#5888]
### Did you verify this is a real problem
yes

### Tell us about the problem
Loading images from local file system is not working in newly generated app (images are not displayed):
```
<StackLayout width="33%" orientation="horizontal" padding="5" *ngFor="let navItem of navItems" (tap)="onNavItemTap(navItem)">
  <Image [src]="'~/images/' + navItem.img"  width="24" height="24"></Image>
  <Label text="{{navItem.name}}"></Label>
</StackLayout>
```
navItems Array in controller:
```
navItems = [
  {id: 1, name: "My Yooji's", targetUrl: "myyoojis", img: "myyoojis24.png"},
  {id: 2, name: "Order", targetUrl: "order", img: "order24.png"},
  {id: 3, name: "Locations", targetUrl: "locations", img: "locations24.png"}
];
```
File-Structure:
![image](https://user-images.githubusercontent.com/14333479/40724617-bb4fe05e-6421-11e8-977d-10a703199c4a.png)

Result:
![image](https://user-images.githubusercontent.com/14333479/40724758-1e098fd8-6422-11e8-86d6-858e235ac652.png)

### Which platform(s) does your issue occur on?
only tried it on Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.2
- Cross-platform modules: tns-core-modules@4.0.1
- Runtime(s): "tns-android": {
      "version": "4.0.1"
    }

In another Nativescript App, which I created a few months ago, I did the same and there the images show up.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1354
