### ISSUE TITLE
How to create a compass.

### ISSUE THREAD

**Issue by zuohuadong** [NativeScript/NativeScript#5889]
![image](https://user-images.githubusercontent.com/11203929/40730224-b9eabcea-6460-11e8-966e-e6d36ca713ae.png)

I did not find the corresponding interface or plug-in.
Or, what kind of algorithm should I use?
As a basic function, I think Nativscript should provide it.

**Comment by tsonevn** [comment]
Hi @zuohuadong,
In your case, you can use [nativescript-geolocation](https://github.com/NativeScript/nativescript-geolocation/blob/6dd3068bb9b8851a6acd4c966fa1b80f6cdebc69/src/location.d.ts#L39) plugin to get the direction and to implement the needed UI to display that information. If this is not applicable to you, you can create [a plugin](https://docs.nativescript.org/plugins/building-plugins), which provides the required functionality.

For further questions, please use our [forum](https://discourse.nativescript.org/) or StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript).

**Comment by zuohuadong** [comment]
@tsonevn  
now,   https://github.com/NativeScript/nativescript-geolocation     have no  direction.

I tried to create a plugin, but there was an error introducing AAR.

**Comment by tsonevn** [comment]
Hi @zuohuadong,
I review the plugin and found that there is still [direction property](https://github.com/NativeScript/nativescript-geolocation/blob/master/src/location.d.ts#L39) which can be used. You can also test it while using the plugin's [demo](https://github.com/NativeScript/nativescript-geolocation/tree/master/demo). 
Regarding the `aar`, make sure that you have set the file in the correct platform folder. You can review [this](https://docs.nativescript.org/plugins/plugin-reference#directory-structure) part of the article, where it is described the plugin structure.

**Comment by csi-stasik** [comment]
```
declare const android: any;
declare const CLLocationManager: any;

export class MyClass {
  private sensorUpdate: any;
  private sensorManager: any;

  constructor(private map: MapView, private location: geolocation.Location) {
    this.setPosition(this.location);
    this.create();
    this.startHeadingUpdates();
  }

 private startHeadingUpdates() {
    if (this.sensorManager || this.sensorUpdate) {
      return;
    }

    if (isIOS) {
      this.sensorManager = CLLocationManager.alloc().init();

      if (this.sensorManager.headingAvailable) {
        this.sensorManager.startUpdatingHeading();

        this.sensorUpdate = setInterval(() => {
          this.marker.rotation = this.sensorManager.heading.trueHeading;
        }, 100);
      } else {
        console.log("Heading not available.");
      }

      return;
    }

    if (isAndroid) {
      this.sensorManager = app.android.foregroundActivity.getSystemService(
        android.content.Context.SENSOR_SERVICE
      );

      this.sensorUpdate = new android.hardware.SensorEventListener({
        onAccuracyChanged: (sensor: any, accuracy: any) => {
          // console.log(accuracy)
        },
        onSensorChanged: (event: any) => {
          this.marker.rotation = event.values[0];
        }
      });

      const orientationSensor = this.sensorManager.getDefaultSensor(
        android.hardware.Sensor.TYPE_ORIENTATION
      );
      this.sensorManager.registerListener(
        this.sensorUpdate,
        orientationSensor,
        android.hardware.SensorManager.SENSOR_DELAY_UI
      );
    }
  }

  stopUpdatingHeading() {
    if (!this.sensorManager || !this.sensorUpdate) {
      return;
    }

    if (isIOS) {
      this.sensorManager.stopUpdatingHeading();
      clearInterval(this.sensorUpdate);
      this.sensorManager = null;
      return;
    }

    if (isAndroid) {
      this.sensorManager.unregisterListener(this.sensorUpdate);
      this.sensorManager = null;
    }
  }
}
```
