### ISSUE TITLE
How to build for release android

### ISSUE THREAD

**Issue by duongnhatduy** [NativeScript/NativeScript#589]
Hi,

Is there any command for generating the release apk for android. I can see there are < project name >-debug.apk, < project name >-debug-unaligned.apk and < project name >.ap_ in platforms/android/bin. But I'm not sure if one of those is the one to use for publishing

**Comment by Fatme** [comment]
Hi @duongnhatduy,

If you want to produce an unsigned release apk you need `tns build android --release` command. The produced .apk will be `platforms/android/bin/<project name>-release-unsigned.apk`.
If you want to produce a signed release apk you need `tns build android --release --keyStorePath <path to your keystore> --keyStorePassword  <your keystore password>  --keyStoreAlias <your key store alias>  --keyStoreAliasPassword <your key store alias password>`. The produced .apk will be `platforms/android/bin/<project name>-release.apk`.

Hope this will help you.

**Comment by jazzik** [comment]
Hi, I might be doing something wrong, but today I tried to build unsigned apk using `tns build android --release` with 1.6.0 version, but I am getting this

> When producing a release build, you need to specify all --key-store-* options.

also help is bit confusing. For --release option it says 'you **must** specify key options', for --key-store-* it says 'you **can** use key options along with --release to have signed release'

> * --release - If set, produces a release build. Otherwise, produces a debug build. When set, you must also specify the --key-store-* options.
> * --key-store-path - Specifies the file path to the keystore file (P12) which you want to use to code sign your APK. You can use the --key-store-* options along with --release to produce a signed release build.

**Comment by jjTudu** [comment]
`C:\A>tns build android --release --key-store-path C:\A\LIN.TXT --key-store-password YOURPASSWORD --key-store-alias NAME --key-store-alias-password YOURPASSWORD`

**Comment by samuelt1** [comment]
this does not answer the question of how to make an unsigned release apk. I have the make that, then give that to my boss.

**Comment by darijanrijan** [comment]
You can generate your own keystore locally:

keytool -genkey -v -keystore <my-release-key>.keystore -alias <alias_name> -keyalg RSA -keysize 2048 -validity 10000

**Comment by emmanuel128** [comment]
is the `key-store-alias-password` is same as `key-store-password `?

**Comment by byhba** [comment]
i try to producea signed release apk and it return:
'--key-store-path' n’est pas reconnu en tant que commande interne ou externe, un programme exécutable ou un fichier de commandes.
Can you help me?
