### ISSUE TITLE
How to handle navigation when a push notification is opened?

### ISSUE THREAD

**Issue by endymion00** [NativeScript/NativeScript#5891]
Hi,
I'm facing an issue using Nativescript core related to navigation when a push notification is opened.
I found a solution BUT it is neither efficient nor consistent because I had to place navigation sentences in different places in the application and also navigation is executed twice...
What is the recommended way to architect this situation? 

Thank you in advance

**Pages:**
**1. app.js** --> application page. 
**2.. splash.js** --> Is the "main page", performs some configurations, shows an animation and also acts a as "redirector page".  This page redirects automatically to home.js (in normal start up flow) or to conversation_detail.js (if a push notification is opened -read below-)

**User flow (in order) and desired navigation :**

**1. A push notification is received**
**2. A push notification is opened by the user.**
**3. The app must navigate to a internal page (in 3 scenarios: app is killed, app is in foreground and app is in background).**

**My solution (it works but it is not consistent and is navigating twice because there are 2 navigation sentences in different places):**

Push notifications are set to NOT show the modal dialog.
ios: 'kOSSettingsKeyInFocusDisplayOption'
android: OSInFocusDisplayOption.Notification

**Scenario foreground/background:**

What I do is to navigate in an "on opened push handler". **This works for iOS BUT NOT in some Androids**. 've seen that Nexus 5 (marshmallow 6.0.1) and Nox emulator (android 4.4.2) ignores it (I meant they execute the navigate command but without effect) but a Huawei using  6.0 and EMUI 4.1 is working.

**Scenario app killed:**
I had to add in the "on opened push handler" a sentence to store the push notification in appSettings. 
Also in splash.js I added code to recover the push notification so a navigation to conversation_detail.js is perform.
Note: while this code solves app killed scenario it also solves foreground/background for the tested androids that didn't navigate...

Pseudo code is:
```

//splash.js (inside onNavigatedTo)
if (get_stored_push_notification) {
navigate_to_conversation_detail; // Push notification opened flow.
}
else {
navigate_to_home_page; // Normal flow.
}
```

**Comment by NickIliev** [comment]
@endymion00 you could use the message received callback e.g. like discussed [here](https://discourse.nativescript.org/t/navigate-to-route-after-push-notification-is-received-in-main-ts/1340). Also as far as I understand the last scenario is practically solving your issue and navigation is working for all scenario (using `onNavigatedTo` to track fro stored notifications) - it also uses application-settings to store needed information to navigate to wanted page, so it seems legit. Are there any downsides to this approach (am I missing something..)?

Please note that the repository is for logging issues, bugs and features related to NativeScript.
For how-to related questions please use the community channels like [the NativeScript forum](https://discourse.nativescript.org/), [SO ](https://stackoverflow.com/questions/tagged/nativescript)or [NativeScript community slack](https://nativescriptcommunity.slack.com/messages/general)

**Comment by endymion00** [comment]
@NickIliev Ok, thank you very much for your time.

**Comment by endymion00** [comment]
@NickIliev I missed to to answer your question. The only drawback my code has is that 2 navigation events are triggered when the app starts (when it is killed).  The first navigation event in on the handler and the other on the navigatedTo of my splash.js. If the phone is not very fast a page double loading is noticed.
For executing only one navigation when in foreground/background I was being able to detect on the on push opened handler that the app was in this state.  Code is:
```
                const frameTopmost = frameModule.topmost();
                // navigate only if the app has not been launched (is in background or foreground)
                if (frameTopmost && frameTopmost.currentEntry) {
                    navigateToSplash(frameTopmost, message);
                }

```
By the way when used only frameTopmost.currentEntry as a condition it only I noticed that some Androids crashed because frameTopmost was also undefined while others had value in frameTopmost but not in its currentEntry property.
