### ISSUE TITLE
nativescript-imagecropper error

### ISSUE THREAD

**Issue by momoling** [NativeScript/NativeScript#5895]
Unable to apply changes on device: 79BMADR7QZD25. Error is: Failed to build plugin nativescript-imagecropper :
Error: Command gradlew.bat failed with exit code 1 Error output:
 C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\ucrop-2.2.2-native.aar\bfa85db65d82ba41411e23f89fa6657f\res\values\values.xml:72:5-77:13: AAPT: resource attr/selectableItemBackground (aka org.nativescript.nativescript_imagecropper:attr/selectableItemBackground) not found.

D:\HelloWorld\platforms\tempPlugin\nativescript_imagecropper\build\intermediates\res\merged\release\values\values.xml:75: AAPT: resource attr/selectableItemBackgroundBorderless (aka org.nativescript.nativescript_imagecropper:attr/selectableItemBackgroundBorderless) not found.

D:\HelloWorld\platforms\tempPlugin\nativescript_imagecropper\build\intermediates\res\merged\release\values\values.xml:69: error: resource attr/selectableItemBackground (aka org.nativescript.nativescript_imagecropper:attr/selectableItemBackground) not found.
D:\HelloWorld\platforms\tempPlugin\nativescript_imagecropper\build\intermediates\res\merged\release\values\values.xml:75: error: resource attr/selectableItemBackgroundBorderless (aka org.nativescript.nativescript_imagecropper:attr/selectableItemBackgroundBorderless) not found.
error: failed linking references.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

**Comment by tsonevn** [comment]
Hi @momoling,
Thank you for contacting us.
We reviewed the attached log and the problem seems to be related to the nativescript-imagecropper plugin.
Regarding that, I will suggest contacting the author of the plugin by logging a new issue in the [nativescript-imagecropper's repo](https://github.com/bthurlow/nativescript-imagecropper/issues).

**Comment by momoling** [comment]
@tsonevn 
Thank you.
