### ISSUE TITLE
Feature Request: Focus / Blur events for other/all ui elements

### ISSUE THREAD

**Issue by gms1** [NativeScript/NativeScript#5902]
quote: https://github.com/NativeScript/NativeScript/issues/2181
> It would be useful to have focus and blur events (to mirror the DOM terminology) that are raised for a
> textfield, searchbar, or any other controls that can gain or lose focus.
> Also would be good to have a way to determine if a view currently has focus or not, like a hasFocus property.

Please consider adding this feature to other ui controls, like buttons, ...

**Comment by tsonevn** [comment]
Hi @gms1,
Can you provide more info about your case and what you are trying to achieve in your project? Also, it will help if you give us info about the scenarios, where such events(Focus / Blur) can be used for the button.

**Comment by gms1** [comment]
hm, may I ask another question? what makes the textfield / textview so specific that these focus / blur events would justify for those two only?

The use-case for having these events for buttons, switch, slider, ...**or any other controls that can gain or lose focus**, is in no way different from that of textfields and textviews. It offers a way to tell if a control has the focus or not, which can then be used to programmatically apply stylings, perform validation and so on

coming from the web, I can not believe that these basic events are not available in NativeScript, so please forgive me if my answer sounds harsh

**Comment by NickIliev** [comment]
The `textfield` and `textview` (editable) is not only focusing on the element but allows the user to input data which triggers the mobile keyboard to appear (which is not the case for other UI elements).

Regarding focusing an element like button. - It is possible if it can be achieved for the native control in Android or iOS. So, for example, to focus a button on Android, you could use [this solution](https://stackoverflow.com/a/3234884/4936697)

For example, this is the NativeScript code
```JavaScript
const btn = page.getViewById("myBtn");
const androidBtn = btn.android;

androidBtn.setFocusableInTouchMode(true); 
androidBtn.requestFocus();
```

Keep in mind that the main purpose of NativeScript is to follow the native behavior embedded in the mobile frameworks (iOS and Android) and not the Web browsers. DOM related techniques can be applied but are not always the proper way to create a mobile application. Consider that a user in the browser can easily change the focus of different elements no matter their functionality. However when using smartphone one of the most common way to change focus is when the user is entering data via the keyboard and hitting the `next` button. Changing focus while not using the keyboard is rare and not common UI scenario for a mobile application. You could validate you controls/ apply styles while using application or view lifecycle events (e.g., loaded)
