### ISSUE TITLE
IOS - find developement team id 

### ISSUE THREAD

**Issue by peppeg85** [NativeScript/NativeScript#5903]
hello, maybe for someone it could be a stupid question, i'm trying to run an app on ios, when i run tns run ios it fails because it lokks for my development_team id. in xcode i've generated a team, but where can i find the id? inside xcode -> accounts ->team there is a certificate with my name and surname, but no ID.

thanks in advance and sorry for my question

**Comment by tsonevn** [comment]
Hi @peppeg85,
You can review [this](https://stackoverflow.com/questions/18727894/how-can-i-find-my-apple-developer-team-id-and-team-agent-apple-id) thread in StackOverflow, where it is described, how to find your team Id. Also, make sure that the certificate is set up [correctly](https://developer.apple.com/account/ios/certificate/create).

It will help if you provide more info about the issue, which you are facing while running `tns run ios` command and about the exact error, which is thrown?

**Comment by dtopuzov** [comment]
Hi @peppeg85 

{N} CLI has build in functionality to detect teams/provisioning profiles.

When run `tns build ios --path TestApp --release --for-device --provision` (or specify wrong provision) you will see a table with available provisioning profiles and teams.

**Comment by peppeg85** [comment]
thanks for the answers, here is the error:

Skipping prepare.
Building project...
Xcode 8 requires a team id to be specified when building for device.
You can specify the team id by setting the DEVELOPMENT_TEAM setting in build.xcconfig file located in App_Resources folder of your app, or by using the --teamId option when calling run, debug or livesync commands.
Xcode build...
2018-06-04 16:34:25.233 xcodebuild[2653:85829]  DTDeviceKit: deviceType from 25b6b3827db648aa6c5bdafbb622cac7c0f9efe6 was NULL
2018-06-04 16:34:25.288 xcodebuild[2653:85830]  DTDeviceKit: deviceType from 25b6b3827db648aa6c5bdafbb622cac7c0f9efe6 was NULL
2018-06-04 16:34:25.471 xcodebuild[2653:85828] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-14098/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/RuntimeSupport/MacroExpansion/XCMacroExpansionExtensions.mm:94
Details:  Assertion failed: [value isKindOfClass:[NSString class]] || [value isKindOfClass:[NSArray class]]
Object:   <DVTMacroDefinitionTable: 0x7f85afe8da60>
Method:   -_xc_setValue:forMacroName:conditionSet:errorHandler:
Thread:   <NSThread: 0x7f85ae501ec0>{number = 1, name = main}
Hints: 

Backtrace:
  0   -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1   _DVTAssertionHandler (in DVTFoundation)
  2   _DVTAssertionFailureHandler (in DVTFoundation)
  3   _DVTAssertionFailureHandler (in DVTFoundation)
  4   -[DVTMacroDefinitionTable(XCMacroExpansionExtensions) _xc_setValue:forMacroName:conditionSet:errorHandler:] (in DevToolsCore)
  5   -[DVTMacroDefinitionTable(XCMacroExpansionExtensions) _xc_setValue:forMacroName:errorHandler:] (in DevToolsCore)
  6   __108-[DVTMacroDefinitionTable(XCMacroExpansionExtensions) xc_setMacroNamesAndValuesFromDictionary:errorHandler:]_block_invoke (in DevToolsCore)
  7   -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] (in CoreFoundation)
  8   -[DVTMacroDefinitionTable(XCMacroExpansionExtensions) xc_setMacroNamesAndValuesFromDictionary:errorHandler:] (in DevToolsCore)
  9   +[DVTMacroDefinitionTable(XCProjectArchivingExtensions) xc_macroDefinitionTableFromDictionaryRepresentationForProjectArchiving:usingPropertyDefinitionsFromSpecificationDomain:] (in DevToolsCore)
 10   -[PBXBuildStyle _setBuildSettings:] (in DevToolsCore)
 11   -[PBXUnarchivingBinding readValueForObject:fromPListUnarchiver:] (in DevToolsCore)
 12   -[PBXObject _unarchiveValuesForArchiveMask:fromPListUnarchiver:] (in DevToolsCore)
 13   -[PBXObject readFromPListUnarchiver:] (in DevToolsCore)
 14   -[PBXBuildStyle readFromPListUnarchiver:] (in DevToolsCore)
 15   -[PBXPListUnarchiver _unarchiveObjectWithGlobalIDHexString:] (in DevToolsCore)
 16   -[PBXPListUnarchiver _decodeMutableObjectArrayFromPListArray:] (in DevToolsCore)
 17   -[PBXPListUnarchiver decodeMutableObjectArrayForKey:] (in DevToolsCore)
 18   -[PBXUnarchivingBinding readValueForObject:fromPListUnarchiver:] (in DevToolsCore)
 19   -[PBXObject _unarchiveValuesForArchiveMask:fromPListUnarchiver:] (in DevToolsCore)
 20   -[PBXObject readFromPListUnarchiver:] (in DevToolsCore)
 21   -[PBXPListUnarchiver _unarchiveObjectWithGlobalIDHexString:] (in DevToolsCore)
 22   -[PBXPListUnarchiver decodeObjectForKey:] (in DevToolsCore)
 23   -[PBXUnarchivingBinding readValueForObject:fromPListUnarchiver:] (in DevToolsCore)
 24   -[PBXObject _unarchiveValuesForArchiveMask:fromPListUnarchiver:] (in DevToolsCore)
 25   -[PBXObject readFromPListUnarchiver:] (in DevToolsCore)
 26   -[PBXPListUnarchiver _unarchiveObjectWithGlobalIDHexString:] (in DevToolsCore)
 27   -[PBXPListUnarchiver _decodeMutableObjectArrayFromPListArray:] (in DevToolsCore)
 28   -[PBXPListUnarchiver decodeMutableObjectArrayForKey:] (in DevToolsCore)
 29   -[PBXUnarchivingBinding readValueForObject:fromPListUnarchiver:] (in DevToolsCore)
 30   -[PBXObject _unarchiveValuesForArchiveMask:fromPListUnarchiver:] (in DevToolsCore)
 31   -[PBXObject readFromPListUnarchiver:] (in DevToolsCore)
 32   -[PBXProject readFromPListUnarchiver:] (in DevToolsCore)
 33   -[PBXPListUnarchiver _unarchiveObjectWithGlobalIDHexString:] (in DevToolsCore)
 34   -[PBXPListUnarchiver decodeRootObject] (in DevToolsCore)
 35   +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
 36   -[Xcode3Project initWithFilePath:extension:workspace:options:error:] (in DevToolsCore)
 37   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke_2 (in IDEFoundation)
 38   _dispatch_client_callout (in libdispatch.dylib)
 39   _dispatch_queue_barrier_sync_invoke_and_complete (in libdispatch.dylib)
 40   DVTDispatchBarrierSync (in DVTFoundation)
 41   -[DVTDispatchLock performLockedBlock:] (in DVTFoundation)
 42   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke (in IDEFoundation)
 43   __58-[DVTModelObjectGraph performBlockCoalescingModelChanges:]_block_invoke (in DVTFoundation)
 44   -[DVTModelGraphTransactionScope performTransaction:] (in DVTFoundation)
 45   -[DVTModelObjectGraph performBlockCoalescingModelChanges:] (in DVTFoundation)
 46   +[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:] (in IDEFoundation)
 47   +[IDEContainer retainedContainerAtFilePath:fileDataType:workspace:error:] (in IDEFoundation)
 48   -[IDEFileReference _recalculateReferencedContainer] (in IDEFoundation)
 49   -[IDEFileReference referencedContainer] (in IDEFoundation)
 50   -[IDEContainer _resolveFileReference:] (in IDEFoundation)
 51   -[_DVTTimeSlicedMainThreadUnorderedUniquingWorkQueue _processWorkItemsWithDeadline:] (in DVTFoundation)
 52   -[DVTTimeSlicedMainThreadWorkQueue _processWithDeadline:] (in DVTFoundation)
 53   -[_DVTTimeSlicedMainThreadActiveWorkQueues _processWorkQueuesOnDeadline] (in DVTFoundation)
 54   __NSFireDelayedPerform (in Foundation)
 55   __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ (in CoreFoundation)
 56   __CFRunLoopDoTimer (in CoreFoundation)
 57   __CFRunLoopDoTimers (in CoreFoundation)
 58   __CFRunLoopRun (in CoreFoundation)
 59   CFRunLoopRunSpecific (in CoreFoundation)
 60   +[DVTKVOConditionValidator waitForCondition:sourceObject:keyPathAffectingConditionBlock:timeout:] (in DVTFoundation)
 61   -[Xcode3CommandLineBuildTool _resolveInputOptionsWithTimingSection:] (in Xcode3Core)
 62   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
 63   main (in xcodebuild)
 64   start (in libdyld.dylib)
Unable to apply changes on device: 25b6b3827db648aa6c5bdafbb622cac7c0f9efe6. Error is: Command xcodebuild failed with exit code null.

in the apple account page I can't find the team id, here are the screenshots within the command tns build ios --path TestApp --release --for-device --provision:
![screen shot 2018-06-04 at 16 40 19](https://user-images.githubusercontent.com/25436763/40923944-59b91bf0-6816-11e8-8e81-baa6e1909289.png)
![screen shot 2018-06-04 at 16 41 58](https://user-images.githubusercontent.com/25436763/40923956-60a5dfca-6816-11e8-8b86-9f72a6365211.png)
 thank you again!

**Comment by peppeg85** [comment]
in xcode I've created a iOS developer certificate and pressed the download profile button, so I think it's configured

**Comment by NickIliev** [comment]
@peppeg85 you need to enroll in the Apple Developer program to create your certificates and provisioning profiles. You can use the [NativeScript Sidekick documentation for detailed  information about how to enroll the program and create your certificate](https://docs.nativescript.org/sidekick/user-guide/code-signing/code-signing-for-ios/ios-developer-program)s

**Comment by peppeg85** [comment]
is it free or must i pay the 99 $? they say it's free also develope on a real device
