### ISSUE TITLE
Css animations with iteration count set to "infinite" causes crash on Android

### ISSUE THREAD

**Issue by shiv19** [NativeScript/NativeScript#5910]
This issue occurs on Android.

- CLI: 4.1.0
- Cross-platform modules: 4.1.0
- Runtime(Android): 4.1.0

### How to recreate the issue
https://play.nativescript.org/?template=play-tsc&id=f9kFvA
If you wait on this playground app on Android for long enough (about 2-5 minutes), the animation stops working.
And the app becomes unresponsive.

I have also been able to recreate this issue in an app which is running from CLI.

A simple animation such as the following should be enough to recreate it.
```
.swing {
    animation-name: swingAnimation;
    animation-duration: 6s;
    animation-iteration-count: infinite;
    animation-timing-function: cubic-bezier(0.42,0,1,1);
}

@keyframes swingAnimation {
    0% { 
        transform: translate(0, 0); 
    }
    50% { 
        transform: translate(0, 300); 
    }
    100% {
        transform: translate(0, 0);
    }
}
```

**Comment by jogboms** [comment]
#5731 #3901

I remember this one. 
I had to switch to creating my animations iin JS then.
I still wish a lasting solution can be conceived.

**Comment by NickIliev** [comment]
@shiv19 @jogboms the issue os a known bug - closing a duplicate to [https://github.com/NativeScript/NativeScript/issues/5731](https://github.com/NativeScript/NativeScript/issues/5731)
