### ISSUE TITLE
XMLHttpRequest should return statusText from server, not overwrite it

### ISSUE THREAD

**Issue by moll** [NativeScript/NativeScript#592]
I took a brief look at the XHR compatibility object and I think there's another thing not exactly right: The server returned status text is replaced by a default status text. That shouldn't be done as it's perfectly okay to return custom ones from the server. In fact, I do so in my APIs to provide more user-friendly descriptions for otherwise ambiguous status codes.

**Comment by enchev** [comment]
Unfortunately we are not aware of any Android and/or iOS API that will return the Reason-Phrase. Please share what's your idea on how to get this!
