### ISSUE TITLE
[Android] Cannot open modal from modal

### ISSUE THREAD

**Issue by hosikiti** [NativeScript/NativeScript#5924]
### Did you verify this is a real problem by searching the [NativeScript Forum]
yes

### Tell us about the problem
After updated to 4.1, modal dialog cannot be opened from modal. It worked with NS 4.0 on both android and ios.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1
- Cross-platform modules: 4.1

### Please tell us how to recreate the issue in as much detail as possible.
Minimum example: 
https://play.nativescript.org/?template=play-ng&id=gYEcD1&v=2

1) Tap "open" button.
2) Opened successfully.
3) Tap "open 2nd modal" button.
4) 2nd modal cannot be opened.

**Comment by tsonevn** [comment]
Hi @hosikiti,
Please review our [documentation](https://docs.nativescript.org/angular/code-samples/modal-page#modal-page-navigation), where it is described how to navigate to a second modal page inside a modal page.  You can also review our example [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/modal-page/modal-page-navigation).
In general, you should create root modal component, where you should define a second page-router-outlet, which should be used while making the inner navigations inside the modal.

**Comment by RoyiNamir** [comment]
@hosikiti  did you find a solution to that ? 
From my testing , it doesn't work as expected : https://play.nativescript.org/?template=play-ng&id=XbV6U6
Can you share a playground ? ( if you've found a solution).

**Comment by souly1** [comment]
Hi @tsonevn , 

The solution you offer is different from what we require.
Instead of opening a single modal view with two pages we want to open one modal which will in turn open another. 
The scenario being a simple modal view opening a separate existing reusable component which is expecting to load as modal view (thus using the ModalDialogParams.context to retrieve parameters).

As @hosikiti mentioned, this used to work, as mentioned at https://www.nativescript.org/blog/nativescript-4.0-is-out:
> "We also removed the "only one modal at a time" limitation, so now you can show a modal dialog from inside another modal dialog!"

but now this is broken, which totally breaks our project's code in several places and would require a lot of code changes and testing to implement differently. 

Given your answer, what I'm trying to understand now is if this is considered a bug that Nativescript team plans to fix or should this be considered a breaking change.

Thanks.

P.S bug also in iOS

**Comment by hosikiti** [comment]
Hello @RoyiNamir @souly1 ,

Let me explain how I solved this issue and how I'm understanding this change.
Actually, as @tsonevn said, it is possible to open modal from another modal in the following way with NS4.1:

1. Create 2 modal components, say ModalFirstComponent and ModalSecondComponent.
2. Create ModalFirstContentComponent in which you include actual content of the ModalFirstComponent.
3. Defince page-router-outlet in ModalFirstComponent and declare route definition for the ModalFirstContentComponent in app-routing.module.ts.
4. In the ModalFirstComponent's ngOnInit, navigate to the ModalFirstContentComponent with the route path declared.
5. Open ModalFirstComponent by calling modalServices's showModal() from parent component.
6. Now you can open ModalSecondComponent by calling modalService's showModal() from ModalFirstContentComponent.

It is not clearly stated, but it seems the way to open modal from modal completely changed on NS4.1.
Like @souly1 said, it totally broke our app's code. By the solution I suggested above, we had to rewrite a lot of modal dialog related codes when updating to NS4.1. So for us, this was a breaking change.

Personally, I think NS4.1 was a great update because it supports flexible navigation inside modal dialog. But on the other hand, I also feel the way to open a single page modal from another single page modal  a little bit complicated, compared to the way on NS4.0 because it requires a lot of work ( such as adding routing ) to just open modal dialog.

@tsonevn 
Correct me if I'm wrong, but current my understanding of opening modal is:

The way to open modal which does not open another modal or not has navigation: same as  4.0.
The way to open modal which opens another modal or has own navigation inside it: CHANGED on 4.1.

Thanks.

**Comment by RoyiNamir** [comment]
IMO - This should be re-opened as a bug OR be documented as a Breaking Change.

@hosikiti  Do you have any playground for the solution of yours ? Just to be synchronized.

**Comment by hosikiti** [comment]
@RoyiNamir 
Here it is. https://play.nativescript.org/?template=play-ng&id=RbISYY&v=2

This example works both iOS and Android.

**Comment by RoyiNamir** [comment]
@hosikiti When you close the second modal , it closes also the first modal.
Also , in a regular modal , we used to have transparent layer.
Can that be done in your current solution ?

**Comment by hosikiti** [comment]
@RoyiNamir 

> When you close the second modal , it closes also the first modal.

If you remove following lines in `modal1.component.ts`, it does not close automatically.

```
            setTimeout(() => {
                this.params.closeCallback(res * 2);
            }, 1000);
```

> Also , in a regular modal , we used to have transparent layer.

As far as I know, trasparency of modal dialog is not supported officially.
To make dialogs transparent, you can try my workaround suggested here:
https://github.com/NativeScript/NativeScript/issues/5554

**Comment by souly1** [comment]
@tsonevn @NickIliev , can anyone on the Nativescript team please give a formal final reply on this issue?

Thanks.

@hosikiti you're braver than us, changing ones code from what was officially supported to a solution that might work but is not officially supported(?) is too brave for us.
In such case, as we see it, there is absolutely **no** commitment from the framework development team that it will continue working in the future.

**Comment by hosikiti** [comment]
@souly1 I totally agree with you. We really need official point of view on this issue. At least I would like to know if my solution suggested above is correct or not.

**Comment by NickIliev** [comment]
@hosikiti @souly1 @RoyiNamir we are currently investigating the issue and it seems that indeed the scenario was working with tns-core-modules@4.0.0 and nativescript-angular@5.3.0 but is currently throwing (both on Android and iOS). Marking as a bug and we will post any related information here

**Comment by nikym23** [comment]
> @RoyiNamir
> Here it is. https://play.nativescript.org/?template=play-ng&id=RbISYY&v=2
> 
> This example works both iOS and Android.

can this example with a modal inside tabview (any tabview item)?
