### ISSUE TITLE
Navigate from page with flat ActionBar to page with TabView - Tabs not displayed (iOS)

### ISSUE THREAD

**Issue by cfoulkes** [NativeScript/NativeScript#5925]
Problem occurs on iOS.

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0
- Cross-platform modules: 4.1.0
- Runtime(s): tns-ios - 4.1.0

Create angular app,
Create initial page with ActionBar flat="true"

import { Component } from "@angular/core";
import { Router } from '@angular/router';

@Component({
    moduleId: module.id,
    selector: 'page1',
    template: 
`
        <ActionBar flat="true" title="Page 1"></ActionBar>

        <StackLayout>
            <Label text="page1"></Label>
            <Button text="goto tabs page" (tap)="buttonTapped()"></Button> 
        </StackLayout>    
`
})

export class Page1Component {

    constructor(private router: Router) {}

    buttonTapped() {
        this.router.navigate(['tabs']);
    }
}

Create link or code to navigate to second page with TabView element.

import { Component } from "@angular/core";

@Component({
    moduleId: module.id,
    selector: 'tab-container',
    template: 
    `

    <ActionBar title="Tab Page"></ActionBar>
    <TabView>
        <StackLayout *tabItem="{title: 'Tab0'}">
            <Label text="tab0"></Label>
            <Label text="tab0"></Label>
            <Label text="tab0"></Label>
            <Label text="tab0"></Label>
            <Label text="tab0"></Label>
        </StackLayout>
        <StackLayout *tabItem="{title: 'Tab1'}">
            <Label text="tab1"></Label>
        </StackLayout>
    </TabView>

    `
})

export class TabContainerComponent {}

After navigation, the page displays the content of the first tab (partially hidden by the Action Bar), but not the TabView bar itself.

Thanks,
Colin

**Comment by tsonevn** [comment]
HI @cfoulkes,
We have a similar issue logged [here](https://github.com/NativeScript/NativeScript/issues/5901). You can keep track on it for further info. 
Meanwhile, as a temporary solution, you can nest the TabView inside a GridLayout. For example:
```
<GridLayout>
<TabView>
    <StackLayout *tabItem="{title: 'Tab0'}">
        <Label text="tab0"></Label>
        <Label text="tab0"></Label>
        <Label text="tab0"></Label>
        <Label text="tab0"></Label>
        <Label text="tab0"></Label>
    </StackLayout>
    <StackLayout *tabItem="{title: 'Tab1'}">
        <Label text="tab1"></Label>
    </StackLayout>
</TabView>
</GridLayout>
```

**Comment by cfoulkes** [comment]
Thanks a lot. 
I did a search but must have missed that one.

Colin
