### ISSUE TITLE
TNS XSD Page not found

### ISSUE THREAD

**Issue by kkganesan** [NativeScript/NativeScript#593]
The xsd reference in the following returns 404, 
targetNamespace="http://www.nativescript.org/tns.xsd"
xmlns="http://www.nativescript.org/tns.xsd"

**Comment by enchev** [comment]
Hey @kkganesan,

You are right, we use this URL just to provide unique namespace for the {N} XML elements however the URL is not something available publicly. Just a unique string.

Is this a problem?

HTH
