### ISSUE TITLE
css textTransform crashes the app if value not of type string

### ISSUE THREAD

**Issue by Burgov** [NativeScript/NativeScript#5932]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes 

### Tell us about the problem
When the text value of a Label is bound to a non string value (e.g. `undefined` or a numeric value), the app crashes, because toUpperCase() only exists on strings

### Which platform(s) does your issue occur on?
Somehow this only seems to affect Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.2
- Cross-platform modules: 4.0.0
- Runtime(s): 4.0.1 both
- Plugin(s): n/a

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there.

**Comment by tsonevn** [comment]
Hi @Burgov,
I tested your case on my side with NativeScript 4.1, however, I was unable to recreate the issue on my side. For your convenience, I am attaching sample project, please review it and check if you will be able to recreate the problem. 

If the problem persists, please provide some more info about your devises or simulators, which you used for testing.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2089643/Archive.zip)
