### ISSUE TITLE
TextView with left or right padding will crop the text

### ISSUE THREAD

**Issue by gogoout** [NativeScript/NativeScript#5933]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes
### Tell us about the problem

This is a weird one. TextView with the left or right padding doesn't show the full text when blurred. And the one with top or bottom padding is act normal.

### Which platform(s) does your issue occur on?
iOS(haven't tested on Android)

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
`tns --version` `4.0.0`

- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
`tns-core-modules@4.0.0` 

- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
`tns-ios` `4.0.1`

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

1. Start the application
2. Text in the TextView (either one, they are binding to the same ngModel)
3. Text at least 4~5 lines
4. Blur the TextView
5. The first TextView crop the text while the second is normal.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
https://play.nativescript.org/?template=play-ng&id=t1Ca6V

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1375
