### ISSUE TITLE
build different from run version

### ISSUE THREAD

**Issue by peppeg85** [NativeScript/NativeScript#5936]
hello, sometimes happens that tns build android builds an apk different from the current versions of files! with an app that i'm building i have two different results on tns run and tns build. the correct is the run version, but i need the correct also aon the build! i tried also removing the platform and build again, but without results. 
i fixed by cloning the same project inside a new folder and build again.....anyone has the same problem? is there a way to "clean" the project and build the real files? it's like it has a "cache", but also changing the files it builds old versions.

sorry and thank you

**Comment by tsonevn** [comment]
Hi @peppeg85,
Can you provide more info about the problem, which you are facing and the difference, which you see?
Keep in mind that the tns build <platform name> command will be executed, while the tns run command is executed as well.

**Comment by peppeg85** [comment]
hello, thanks for your answer. 
to try the app i run the tns build android command, go to take the app-debug.apk file inside ..\platforms\android\app\build\outputs\apk (that should be the same generated with the tns run command) and copy this file on drive to run it on the smartphone. 
is this right or am i wrong and should do in a different way?
i use 
"tns-android": { version": "3.4.3"}
"tns-core-modules": "~3.4.0"
thank you

**Comment by tsonevn** [comment]
Hi @peppeg85,
I tested your case while using latest NativeScript CLI 4.1.0, tns-core-modules 4.1.0 and tns-android 4.1.2. After executing the `tns build android`an app-debug.apk  file was generated in `<app-name>/platforms/android/app/build/outputs/apk/debug` folder. I also try instaling the apk file with `adb install` command and everything seems to work as expected. 
Can you [upgrade](https://docs.nativescript.org/releases/upgrade-instructions) to latest available NativeScript and try whether you will be able to recreate the problem.

**Comment by peppeg85** [comment]
ok, thank you.
is there a guide to migrate from one version to another of nativescript? i tried many times on different pc , but i have the flavour error, solved downgrading the ns version

**Comment by tsonevn** [comment]
Hi @peppeg85,
You can use the update command, which is described in the attached article in my previous comment. As it is mentioned there, the first steps are to update the CLI, while using the npm command -> `npm install -g nativescript` and then the update command will change the version of the dependencies to the latest available one.
