### ISSUE TITLE
Javascript causes fatal error evaluating this.parent._automaticallyAdjustsScrollViewInsets ios > 10

### ISSUE THREAD

**Issue by isaacfi** [NativeScript/NativeScript#5937]
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10a4f2749 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x10a51ad5b NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x10ae10561 ffi_closure_unix64_inner
4   0x10ae10ec2 ffi_closure_unix64
5   0x109b7a456 -[CALayer layoutSublayers]
6   0x109b7e667 CA::Layer::layout_if_needed(CA::Transaction*)
7   0x109b050fb CA::Context::commit_transaction(CA::Transaction*)
8   0x109b3279c CA::Transaction::commit()
9   0x10b2d5f2c _afterCACommitHandler
10  0x10eb19607 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
11  0x10eb1955e __CFRunLoopDoObservers
12  0x10eafdb81 __CFRunLoopRun
13  0x10eafd30b CFRunLoopRunSpecific
14  0x110ca7a73 GSEventRunModal
15  0x10b2ad057 UIApplicationMain
16  0x10ae10d1d ffi_call_unix64
17  0x135a11020
JavaScript stack trace:
1   onMeasure@file:///app/tns_modules/tns-core-modules/ui/scroll-view/scroll-view.js:122:46
2   measure@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:54:27
3   measureChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:815:26
4   layoutView@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:590:26
5   viewDidLayoutSubviews@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:632:27
6   UIApplicationMain@[native code]
7   start@file:///app/tns_modules/tns-core-modules/application/application.js:264:26
8   run@file:///app/tns_modules/tns-core-modules/application/application.js:284:10
9   bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:160:26
10  bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:94:38
11  bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:83:26
12  anonymous@file:///app/main.js:10:57
13  evaluate@[native code]
14  moduleEvaluation@[native code]
15  @[native code]
16  promiseReactionJob@[native code]
JavaScript error:
file:///app/tns_modules/tns-core-modules/ui/scroll-view/scroll-view.js:122:46: JS ERROR TypeError: undefined is not an object (evaluating 'this.parent._automaticallyAdjustsScrollViewInsets')

https://github.com/NativeScript/NativeScript/blob/0b9d4aea0ab76f01107de0b33c83a5c77e1c9559/tns-core-modules/ui/scroll-view/scroll-view.ios.ts#L130

It needs to validate **this.parent != undefined** as this:

```
if (majorVersion > 10 && this.parent != undefined && !this.parent._automaticallyAdjustsScrollViewInsets) {
            this.nativeViewProtected.contentInsetAdjustmentBehavior = 2;
        }
```

**Comment by tsonevn** [comment]
Hi @isaacfi,
I tested the ScrollView and its functionality on my side, however, I was unable to recreate any issue with the component. Concerning that, can you provide more info about your case and the problem? It will help if you send us sample project, which can be used for debugging.

**Comment by isaacfi** [comment]
I've seen the problem. When I use an ScroolView whitout a parent StackLayout in a Modal.

```
<ScrollView sdkExampleTitle sdkToggleNavButton class="alert-panel">
    <StackLayout>
        <Image width="80" height="80" src="res://{{icon}}"></Image>
    </StackLayout>
</ScrollView>
```

To avoid the error:
```
<StackLayout>
    <ScrollView sdkExampleTitle sdkToggleNavButton class="alert-panel">
        <StackLayout>
            <Image width="80" height="80" src="res://{{icon}}"></Image>
        </StackLayout>
    </ScrollView>
</StackLayout>
```

**Comment by tsonevn** [comment]
Hi @isaacfi,
I tested the case with our [nativescript-sdk-exmples-ng](https://github.com/NativeScript/nativescript-sdk-examples-ng), and was unable to recreate the issue. Make sure that you are using the latest available NativeScript version 4.1. It will help if you send us your project package.json  and sample project, which can be used for debugging. Also, do you reproduce the issue on a specific platform or on both (Android and iOS)?

**Comment by isaacfi** [comment]
You can reproduce it with a device or simulator with iOS 11.4

Regards

**Comment by JPM84** [comment]
Same issue here on iOS 11.4, {N} 4.1.0. Wrapping the scrollview in a StackLayout solved it for me.

**Comment by tsonevn** [comment]
Hi all,
I investigated further the case and was able to recreate the similar issue while using iOS 11.4.0 and displaying Image inside a ScrollView. I am attaching a sample project, which can be used for debugging. For further info, please keep track on the issue.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2126899/Archive.zip)

**Comment by Alessandro994** [comment]
I ran into the same error (also same context: only on iOS 11.4) while trying to display a modal after clicking on a listview's item inside a RadSideDrawer. I attach below the content of the drawer.
I get the error when I tap on the item having the bmi field.
`<StackLayout tkDrawerContent class="stack-bg">

    <Button class="btn btn-rounded-lg btn-primary" (tap)="onToggleScoreList()" text="Chiudi" marginTop="12"></Button>

    <ListView [items]="details" class="list-group list-score">
      <ng-template let-item="item">
        <GridLayout columns="*, auto, 72, 48" rows="*" class="list-group-item bg-primary">
          <Label col="0" row="0" class="list-score-label" [text]="item.label"></Label>
          <Label col="1" row="0" *ngIf="!item.bmi" class="list-score-label"></Label>
          <Label col="1" row="0" *ngIf="item.bmi" class="bmi-label icon-mdi" [text]="iconInfo" (tap)="onOpenBmiDialog(item)"></Label>
          <Label col="2" row="0" class="list-score-value-label m-r-24" [text]="item.points"></Label>
          <Image col="3" row="0" [src]="item?.state ? 'res://score_' + item?.state : 'res://icon'" class="score-state-img" loadMode="async">
          </Image>
        </GridLayout>
      </ng-template>
    </ListView>
  </StackLayout>`

Could you have any idea to solve this issue?
Thanks.

**Comment by manoldonev** [comment]
Reworked / fixed with the implementation of iOS safe area support: https://github.com/NativeScript/NativeScript/pull/6230
