### ISSUE TITLE
Nesting elements dynamically with js

### ISSUE THREAD

**Issue by printnoname** [NativeScript/NativeScript#5938]
Hello. Let's say I want add this construction to page layout via js:
`` 
        <ActionBar class="action-bar">
                <Label class="action-bar-title" text="Some Title"></Label>
        </ActionBar>
``
Can i nest Label inside ActionBar with js, is that possible?

**Comment by tsonevn** [comment]
Hi, @printnoname,
You can review our sample [here](https://github.com/NativeScript/nativescript-sdk-examples-js/blob/master/app/ui-category/action-bar/code-behind/code-behind-page.js), where it is demonstrated,
how to create ActionBar via code behind. Also, you can review our [API references](https://docs.nativescript.org/api-reference/classes/_ui_action_bar_.actionbar), where are described all available properties for the ActionBar. For further questions, please use our [forum](https://discourse.nativescript.org/) or StackOverflow [thread](https://stackoverflow.com/questions/11235370/android-emulator-doesnt-take-keyboard-input-sdk-tools-rev-20). This repository is used only for feature requests and bug reporting.
