### ISSUE TITLE
[Question] How to set CSS linear-gradient to background of slider?

### ISSUE THREAD

**Issue by felix-idf** [NativeScript/NativeScript#5939]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
_Yes_

### Tell us about the problem
I try to create our own color picker component and I want to create a slider with linear-gradient for the hue value like this:
![screen shot 2018-06-12 at 10 27 35](https://user-images.githubusercontent.com/6443021/41278935-7553fa90-6e2b-11e8-8da3-2431bf173936.png)

I try to set the linear-gradient this way:
```
Slider {
    background-image: linear-gradient(to right, #ff0000, #ffff00, #00ff00, #00ffff, #0000ff, #ff00ff, #ff0000);
}
```
... as the [docs](https://docs.nativescript.org/api-reference/classes/_ui_slider_.slider#backgroundimage) say that the Slider component has a background-image property which can be set to a LinearGradient. But what I get is just a slider with default background.

By the way, setting this linear-gradient works perfect for a layout container or a Button.

### Which platform(s) does your issue occur on?
_iOS & Android_

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0
- Cross-platform modules: 4.1.0
- Runtime(s): tns-android 4.1.2, tns-ios 4.1.0

I am thankful for any advice.

Thank you in advance and best regards.

**Comment by tsonevn** [comment]
Hi @felix-idf,
The linear-gradient seems not to be supported for the Slider component. Regarding that, I logged new feature request [here](https://github.com/NativeScript/NativeScript/issues/5940). You can keep track on it for further info.
