### ISSUE TITLE
ListView itemTap does not fire when there is a button in the ListView.item template

### ISSUE THREAD

**Issue by tsvetan-ganev** [NativeScript/NativeScript#594]
When a ```ListView.itemTemplate``` contains a button element, the ```itemTap``` event does not trigger anymore.

**test.xml**
```xml
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
    <ListView items="{{ items }}" itemTap="onTap">
      <ListView.itemTemplate>
        <StackLayout>
          <Label text="{{ $value }}" />
          <Button text="Button" />
        </StackLayout>
      </ListView.itemTemplate>
    </ListView>
</Page>
```

**test.js**
```js
var observable = require("data/observable");
var observableArray = require("data/observable-array");

var items = ['one', 'two', 'three', 'four'];
var viewModel = {
    items: items
};

exports.pageLoaded = function (args) {
    var page = args.object;
    page.bindingContext = viewModel;
};

exports.onTap = function (args) {
    var index = args.index;
    console.log('Clicked item with index ' + index);
};
```

I'm not sure if this is made on purpose, but for me it was very hard to figure out why the ```itemTap``` event doesn't fire.

If this behaviour is intended, it should be mentioned in the ```ListView``` documentation.

![list-view-with-buttons](https://cloud.githubusercontent.com/assets/10002284/9288601/2b9327c0-4357-11e5-841c-27e27f46e2d1.jpg)

**Comment by enchev** [comment]
Looks like this is known issue with [buttons inside ListView in Android](http://stackoverflow.com/questions/6275183/android-listview-with-buttons-onitemclick-do-nothing)

Here is an example how to do this in {N}:
```XML
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
  <ListView items="{{ items }}" itemTap="onTap">
    <ListView.itemTemplate>
      <StackLayout>
        <Label text="{{ $value }}" />
        <Button text="Button" loaded="btnLoaded" />
      </StackLayout>
    </ListView.itemTemplate>
  </ListView>
</Page>
```
```JavaScript
var observable = require("data/observable");
var observableArray = require("data/observable-array");

var items = ['one', 'two', 'three', 'four'];
var viewModel = {
    items: items
};

exports.pageLoaded = function (args) {
    var page = args.object;
    page.bindingContext = viewModel;
};

exports.btnLoaded = function (args) {
    var btn = args.object;
    btn.android.setFocusable(false);
};

exports.onTap = function (args) {
    var index = args.index;
    console.log('Clicked item with index ' + index);
};
```

**Comment by Jayuda** [comment]
Hello @enchev  and @tsvetan-ganev,
I have same problems, I have check your tutorial Mr. @enchev, but not works.
Do you have answer about this problem Mr. @tsvetan-ganev ???

**Comment by tsvetan-ganev** [comment]
@Jayuda, as far as I remember I haven't tried @enchev's workaround, because in the end I just used a label with on-tap event instead of a button.

**Comment by Najki** [comment]
I can confirm that the workaround by @enchev does work. Thanks! 😄

**Comment by Robophil** [comment]
i can't access the current index in my listview template with `{{ $value  }}` any solution?

**Comment by NickIliev** [comment]
@Robophil better create new issue with detailed information about the situation you are trying to solve and a sample code/project given (in order to reproduce your case and give the best advice possible)

**Comment by Robophil** [comment]
Thanks. Already solved this.

**Comment by roblav96** [comment]
@Robophil care to share how?

**Comment by Robophil** [comment]
Hi @roblav96, it was an passing an array of objects. when working with just an array of maybe(numbers or string) $value works fine. I just had to access the key of the object in my template view

**Comment by roblav96** [comment]
Ah, gotcha. Thanks for the enlightenment :D

**Comment by dameety** [comment]
The convo here just helped solve the issue i had. just one more thing, Is there something like an itemTemplateTap that gets the index of the list just live the itemTap.

**Comment by Robophil** [comment]
sure, you can get the index
```xml
<ListView items="{{ items }}" itemTap="onItemTapped">
```

```javascript
function onItemTapped(args){
   const index = args.index;//index of tapped item
}
```

**Comment by dameety** [comment]
thanks Robophil, but i get that. i need to get that same index with a button in the listview template. see: 

<ListView items="{{ courses }}" itemTap="navigateToSchedule">
    <ListView.itemTemplate>
        <StackLayout class="marksLabelStack">
            <DockLayout class="below" orientation="horizontal">
            	<Label text="{{ course_name }}" dock="left"/>
            	<StackLayout orientation="vertical">
                	<Button class="" dock="right" loaded="btnLoaded" text="button" horizontalAlignment="right" tap="REMOVE"/>
	            </StackLayout>
			</DockLayout>
        </StackLayout>
    </ListView.itemTemplate>
</ListView>

i wanna get the index with the tap="REMOVE"

**Comment by roblav96** [comment]
@dameety you can set the id of the button to the index:
```xml
            <StackLayout orientation="vertical">
                <Button id="{{ 'btn_' + $index }}" class="" dock="right" loaded="btnLoaded" text="button" horizontalAlignment="right" tap="REMOVE"/>
            </StackLayout>
```

**Comment by dameety** [comment]
Thanks @roblav96 i will try it out soonest.

**Comment by ullalaaron** [comment]
@roblav96 I tried your suggestion with the following 

```
    <ListView.itemTemplate>
     ...
                    <StackLayout >
                        <Image id="{{ 'btn_' + $value }}" tap="likeItem" class="width-50" />
                    </StackLayout> 
                </StackLayout>
        </StackLayout>
    </ListView.itemTemplate>
```
Only problem is that as args.object.id I get `btn_undefined`

**Comment by roblav96** [comment]
You're right this way does not work, nor does this use of `$index` like it does in `ng2`. So you'll need to manually insert an index number in your array of objects.

For the `likeItem` event, you need to add it to your `application.resources`:
```
import application = require('application')
application.resources['likeItem'] = function likeItem() {}
```

**Comment by Sakshamgupta20** [comment]
use this linke in ur button xml
 android:focusable="false"

**Comment by ycherniavskyi** [comment]
@Sakshamgupta20 could you please explain in more details how you configure your Nativescript  to `android:focusable="false"` construction works in XML?

If I add it to my button, it does not work 
``` XML
<Button android:focusable="false" text="Tap Me" tap="onButtonTap" />
```

But if I set it within `loaded` event (as was suggested in previous comments), then this workaround works. But for me, it is much cleaner to set this property with XML rather than with code.

**Comment by lonerzzz** [comment]
Rather than fight with buttons or inputs stealing focus and preventing the itemTap from being passed along, it is easier to style a label to look like a button or to look like an input if you purpose is only to view data.
