### ISSUE TITLE
Navigation broken with closing modal

### ISSUE THREAD

**Issue by cgebe** [NativeScript/NativeScript#5944]
### Tell us about the problem
I am navigating to a lazy loaded module and within the same call i am closing a modal. The navigation works after a delay but immediately navigates back to the originating page without any error message.

Maybe related to: https://github.com/NativeScript/NativeScript/issues/5853

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0
- Cross-platform modules: 4.1.0
- Runtime(s): 4.1.2
- Plugin(s): "nativescript-angular": "6.0.0",

### Please tell us how to recreate the issue in as much detail as possible.

Have a modal with a button on a page. In the the button click call navigate to a lazy loaded module and call the `closeCallback()` method. When not calling the `closeCallback()` the navigate happens immediately but it navigates back after the model is closed. If calling `closeCallback()` it navigates after 2 seconds but immediately navigates back. No errors shown.

As soon as the `closeCallback()` method is called the navigate back happens. Is there some hidden call happening in the back? How can i prevent this?

**Comment by cgebe** [comment]
As soon as i clear the history, the navigate back does not occur.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1380
