### ISSUE TITLE
Method post unidentified id

### ISSUE THREAD

**Issue by abinaj** [NativeScript/NativeScript#5954]
I'm new mobile developer. I'm working with Nativescript. Now I have a problems with my `post method`. I want to display some details in my product, for this I get in ws ID of product and ws return me details.

For this I tried to use this service code:

service.ts

    import { Injectable } from '@angular/core';
    import { Http, Headers, Response , URLSearchParams} from '@angular/http';
    import { Api } from '../state/Api';
    import { Product} from '~/model/product';
    import 'rxjs/operators';
    import { Observable } from 'rxjs';
    import { map } from 'rxjs/operators';
    
    @Injectable()
    export class ProductService {
    
        constructor(private http: Http,
        ) { }
    
        public Productgetbyid(id: string): Observable<Product> {
            let headers = new Headers();
            headers.append('Content-Type', 'application/x-www-form-urlencoded');
            let urlSearchParams = new URLSearchParams();
            urlSearchParams.append('id', id);
            urlSearchParams.append('id_unique', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9');
            let body = urlSearchParams.toString();
            console.log('body',urlSearchParams.toString())
            return this.http.post(Api.getUrl(Api.URLS.Productgetbyid), body, {
                headers: headers
            })
                .pipe(map((response: Response) => {
                    let res = response.json();
                    if (res.StatusCode === 0) {
                        return new Product(res.StatusDescription[0]);
                    } else if (res.StatusCode === 1) {
                    } else {
                        return new Product(null);
                    }
                }));
        }
    }

Model Product:

    export class Product{
        id: string;
        prodnumber: String;
        name: string;
    
        constructor(obj: any) {
            this.id= obj.id;
            this.prodnumber= obj.prodnumber;
            this.name= obj.name;
        }
    }

This code I call in my component with this code:

component.ts

        items: Product;
        public ngOnInit() {
         this.route.params.subscribe(
                params => {
                    console.log('params',params)
                    this.as.Productgetbyid(params['id']).subscribe(
                        items=> {
                            console.log('items',items)
                            this.items= items;
                        }
                    );
                }
            );
    }

component.html

    <StackLayout class="page">
        <ListView [items]="items" class="list-group">
            <ng-template let-item="item">
                <Label [nsRouterLink]="['/item', item.id]" [text]="item.name"
                    class="list-group-item"></Label>
            </ng-template>
        </ListView>
    </StackLayout>

My ID is undefined. 

From API I expects this JSON:

    {
        "StatusCode": 0,
        "StatusMessage": "OK",
        "StatusDescription": [
            {
                "id": 5,
                "prodnumber": 4,
                "name": "UpdateTest"
            }
        ]
    }

Package.json

    {
    	"description": "NativeScript Application",
    	"license": "SEE LICENSE IN <your-license-filename>",
    	"readme": "NativeScript Application",
    	"repository": "<fill-your-repository-here>",
    	"nativescript": {
    		"id": "org.nativescript.project",
    		"tns-android": {
    			"version": "4.1.2"
    		}
    	},
    	"dependencies": {
    		"@angular/animations": "~6.0.0",
    		"@angular/common": "~6.0.0",
    		"@angular/compiler": "~6.0.0",
    		"@angular/core": "~6.0.0",
    		"@angular/forms": "~6.0.0",
    		"@angular/http": "~6.0.0",
    		"@angular/platform-browser": "~6.0.0",
    		"@angular/platform-browser-dynamic": "~6.0.0",
    		"@angular/router": "~6.0.0",
    		"nativescript-angular": "~6.0.0",
    		"nativescript-barcodescanner": "^2.7.6",
    		"nativescript-theme-core": "~1.0.4",
    		"reflect-metadata": "~0.1.8",
    		"rxjs": "~6.1.0",
    		"tns-core-modules": "~4.1.0",
    		"zone.js": "^0.8.26"
    	},
    	"devDependencies": {
    		"babel-traverse": "6.4.5",
    		"babel-types": "6.4.5",
    		"babylon": "6.4.5",
    		"lazy": "1.0.11",
    		"nativescript-dev-typescript": "~0.7.0",
    		"typescript": "~2.7.2"
    	}
    }

Please can you ask me any idea, how to post my correctly id?

Thanx

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1383
