### ISSUE TITLE
router-outlet usage throws exception if not nested under a page-router-outlet

### ISSUE THREAD

**Issue by bytesoftly** [NativeScript/NativeScript#5955]
When using a `router-outlet` by itself in an app with Angular for Android causes the following exception:

`Error: java.lang.IllegalArgumentException: Cannot add a null child to a ViewGroup`

On reading router documentation I was not clear on why this happens, there is no mention that `router-outlet` components cannot be used in this way compared to `page-router-outlet` components.

I believe this [tutorial](https://www.nativescript.org/blog/using-nested-router-outlets-with-nativescript-and-angular#comments) on your site would not currently work with Nativescript 4.0.0 for this reason and that the breaking change happened at some point between that tutorial and now.

**Reproduction**

To reproduce this error, try the following:

- Create a new Angular project `tns create tester --ng`
- Open up app.component.html and replace `<page-router-outlet></page-router-outlet>` with `<router-outlet></router-outlet>` 
- Run `tns debug android` and an uncaught Java exception will be thrown

**Version**
Nativescript 4.0.0

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1384
