### ISSUE TITLE
Unmet peer dependency tns-core-modules@4.1.0

### ISSUE THREAD

**Issue by jaikarve** [NativeScript/NativeScript#5964]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

I found a similar issue at [installing latest version of tns-core-modules](https://github.com/NativeScript/NativeScript/issues/2659).  Removing tns-core-modules and reinstalling did not fix the issue.

### Tell us about the problem
I am attempting to update a {N} project, and receive the following error message:

npm WARN nativescript-statusbar@4.0.1 requires a peer of tns-core-modules@^3.0.0 || ^3.0.0-rc.1 but none was installed.
npm WARN nativescript-drop-down@4.0.0 requires a peer of tns-core-modules@^4 but none was installed.
npm WARN nativescript-telerik-ui@3.1.4 requires a peer of tns-core-modules@^3.1.0 || >3.2.0- but none was installed.
/Users/Jai/Kinvey/Demos/Test/SDE-Nativescript
└─┬ UNMET PEER DEPENDENCY tns-core-modules@4.1.0
  └── tns-core-modules-widgets@4.1.0 

npm WARN nativescript-statusbar@4.0.1 requires a peer of tns-core-modules@^3.0.0 || ^3.0.0-rc.1 but none was installed.

npm ERR! code 1
Could not update the project!

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0
- Cross-platform modules: 4.1.0
- Runtime(s): tns-ios version 4.1.0
- Plugin(s): "tns-core-modules": "^4.1.0",
    "progress-nativechat/nativescript-nativechat": "^1.0.5",
    "kinvey-nativescript-sdk": "3.8.0",
    "nativescript-camera": "^3.1.3",
    "nativescript-drop-down": "^4.0.0",
    "nativescript-fonticon": "^1.1.1",
    "nativescript-geolocation": "^3.0.1",
    "nativescript-mapbox": "^3.1.1",
    "nativescript-materialdropdownlist": "^1.0.15",
    "nativescript-pdf-view": "^2.0.1",
    "nativescript-push-notifications": "^0.1.3",
    "nativescript-sqlite": "^1.1.7",
    "nativescript-statusbar": "^4.0.1",
    "nativescript-telerik-ui": "3.1.4",
    "nativescript-theme-core": "^1.0.4"

### Please tell us how to recreate the issue in as much detail as possible.
The project is on Github: [SDE-NativeScript](https://github.com/KinveyClientServices/SDE-Nativescript.git)

The project runs fine, but tns update results in the error mentioned above.

Thanks for the support!

**Comment by vakrilov** [comment]
Hi,
It looks like the `nativescript-statusbar` has a peer-dependency pointing to `tns-core-modules^3.xxx` and you are using v4. The npm warning you are getting is expected. It looks like there is already an [issue in the `nativescript-statusbar` repo](https://github.com/burkeholland/nativescript-statusbar/issues/14) about that. You can give your feedback there.

As you said - there is a good chance that the code will work even if the status-bar plugin code is not tested with {N} 4 as most of the changes with the 4.0 release were back-compatible.
