### ISSUE TITLE
Arrays not converted automatically to Java

### ISSUE THREAD

**Issue by Tyg-g** [NativeScript/NativeScript#5965]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)? 

Yes.

### Tell us about the problem
In some cases JavaScript arrays are not converted to Java.

### Which platform(s) does your issue occur on?
Android (iOS not tested)

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0
- Cross-platform modules: 4.1.0
- Runtime(s): "tns-android": {"version": "4.1.2"}
- Plugin(s): 

        "dependencies": {
            "nativescript-nbmaterial-ripple": "^1.0.1",
            "nativescript-theme-core": "^1.0.4",
            "tns-core-modules": "^4.1.0"
        },
        "devDependencies": {
            "babel-traverse": "~6.26.0",
            "babel-types": "~6.26.0",
            "babylon": "~6.18.0",
            "lazy": "~1.0.11"
        }

### Please tell us how to recreate the issue in as much detail as possible.
In some cases JavaScript arrays are not converted to Java and give an `Error: Cannot marshal JavaScript argument 1,2,3 at index 0 to Java type.` I'm not sure this is a bug or a feature, I did not find  exact description. I think we need more clarification on this topic.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

    var a = Array.create("[I",2);
    a[0] = [1,2,3];

Gives: `Error: Cannot marshal JavaScript argument [...] at index 0 to Java type.` The array is of simple number so according to [JavaScript to Java: Array](https://docs.nativescript.org/runtimes/android/marshalling/js-to-java#array) I expected an automatic conversion. This happens also when calling Java functions/constructors.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#1089
