### ISSUE TITLE
Feature request: Compatibility with native SDK packages

### ISSUE THREAD

**Issue by jamesharvey2** [NativeScript/NativeScript#5971]
Hello NativeScript,

Is it possible for you guys to make us use SDK packages on NativeScript? 

Here are a few SDK packages which can be used on Java and Swfit apps.  I hope we can use them like using plugins. In general, SDK packages are more powerful than average user made plugins.

SendBird chat SDK for iOS and Android. (React Native is included but no Cordova)
https://sendbird.com/

AudioKit sound kit SDK for iOS
http://audiokit.io

Mapbox SDK for android and iOS
https://www.mapbox.com/maps/

JW Player SDK for android and iOS
https://developer.jwplayer.com/android-sdk/

VMware AirWatch SDK for android
https://code.vmware.com/web/sdk/16.4.1/airwatch-android

MapQuest android SDK
https://developer.mapquest.com/documentation/android-sdk/

Samsung Pro Audio SDK
https://developer.samsung.com/galaxy/professional-audio

Google VR SDK for android
https://developers.google.com/vr/develop/android/download

Smaato SDK
https://www.smaato.com/resources/sdks/

Wikitude augmented reality SDK
http://www.wikitude.com/external/doc/documentation/latest/android/

PubNub chat SDK
https://www.pubnub.com/products/chatengine/

Pepper SDK
https://android.aldebaran.com/sdk/doc/pepper-sdk/index.html

Adobe Creative SDK for android
https://www.adobe.io/apis/creativecloud/creativesdk/docs/androidsdk.html

AppsFlyer SDK
https://support.appsflyer.com/hc/en-us/articles/207032126-AppsFlyer-SDK-Integration-Android

PayPal android SDK
https://developer.paypal.com/docs/integration/mobile/android-integration-guide/

Mapfit SDK
https://mapfit.com/developers/android

Superpowered Audio SDK
http://www.superpowered.com

For example, let us register Java or Swift function and use it on Angular with TypeScript.  
Functionalities offered in SDK packages are much better than that of plugins.
These SDK packages should become a part of NativeScript.

**Comment by NickIliev** [comment]
@jamesharvey2 you can use native libraries (an AAR, a JAR for Android and CocoaPods for iOS) at this very moment. In fact, a quick search revealed that MapBox and Pubnunb are already having a NativeScript related plugin ([here ](https://github.com/EddyVerbruggen/nativescript-mapbox)and https://github.com/triniwiz/nativescript-pubnub). [Here is how the author of the Mapbox plugin has requested the dependency to the Mapbox SDK](https://github.com/EddyVerbruggen/nativescript-mapbox/blob/master/src/platforms/android/include.gradle#L8-L18).

If you don't want to rely on created plugin than you can directly access the SDK in your application and use it as per your requirements.

Making custom SDKs part of NativeScript has its downsides - the third-party SDK are often not supported as the Android SDK. Apart from that would bring larger packages and not everyone would need Mapbox or Pubnub. Closing this as we have good tools for creating plugins and accessing native SDKs + already created plugins for some of the related SDKs.

**Comment by NathanaelA** [comment]
@jamesharvey2 - You should check out the plugin sites; https://plugins.nativescript.rocks -- I know for sure that several of those SDK's are actual plugins in NativeScript (in fact I've worked on two of them in that list myself for clients.)
