### ISSUE TITLE
How to convert xml layout to native view?

### ISSUE THREAD

**Issue by brunoziie** [NativeScript/NativeScript#5972]
I'm trying to create dialog with a custom layout view and when I try do this:

```js
import app = require('application'); 
import { GridLayout } from 'ui/layouts/grid-layout';

const dialog = new android.app.AlertDialog.Builder(app.android.currentContext);
const layout = new GridLayout();

dialog.setView(layout);
```
So I got the following error:

**Uncaught Error: Cannot convert object to Landroid/view/View;**

I tried change to:

```js
dialog.setView(layout.android);
```
And

```js
dialog.setView(layout.nativeView);
```
And the dialog is displayed empty.

How I can convert a NativeScript UI Object to a native android View?

**tns 4.1.0**
**tns-android 4.1.3**

**Comment by NickIliev** [comment]
@brunoziie you could directly create the native input as done [here](https://github.com/NativeScript/NativeScript/blob/38e6f6688e47ebf13cb56a7a5a641721ff3d7ae5/tns-core-modules/ui/dialogs/dialogs.android.ts#L180-L192)

Apart from that, it is recommended to use either native views only or NativeScript's views only. More details on that can be found [in this comment](https://discourse.nativescript.org/t/appending-nativescript-views-to-a-native-ui-view/1412/7?u=nickiliev)
