### ISSUE TITLE
[MacOS 10.13.5]  WARNING: CocoaPods is not installed or is not configured properly.

### ISSUE THREAD

**Issue by turiguiliano88** [NativeScript/NativeScript#5973]
This message prompted out after installing nativescript on MacOS 10.13.5 and run "sudo tns doctor". Therefore I am not able to run "sudo tns run ios". I keep emphasizing sudo here because I just can not run without it. I did follow option "config with local build" but it doesn't solve the problem. My Xcodeproj version is 1.5.9, node v8.11.3.

**Comment by NickIliev** [comment]
@turiguiliano88 do you have CocoaPods installed on your Mac?
```
pod --version
```

If not, please install them with
```
sudo gem install cocoapods
```

**Comment by turiguiliano88** [comment]
@NickIliev Hi, I had already installed CocoaPods before. Version 1.5.3.
During "sudo tns doctor" there were also messages:
✔ CocoaPods update is not required.
✔ Your current CocoaPods version is newer than 1.0.0.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3695
