### ISSUE TITLE
Inconsistency between Android and iOS in label rendering (vertical center)

### ISSUE THREAD

**Issue by Burgov** [NativeScript/NativeScript#5977]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem
Labels render differently in iOS than in Android. In iOS, the text inside is vertically centered, in Android it's top aligned.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
See playground

### Please tell us how to recreate the issue in as much detail as possible.
https://play.nativescript.org/?template=play-ng&id=GXFhEd&v=2

The above Label has no logic applied to it. You can see that in iOS, the text is vertically centered, while in Android, it's top aligned.

The 2nd span has the following logic applied to force it to be vertically centered:

```
                el.android.setGravity(el.android.getGravity() & 0xffffffdf);
```

This should be standard behavior in android to make the behavior consistent between the two platforms.

**Comment by NickIliev** [comment]
@Burgov indeed there is an inconsistency but that is expected as iOS and Android have their own specifics and guidelines and default behaviors. On Android, we should explicitly align any content vertically when it is nested in another view (while quite the opposite on iOS). Setting `verticalAlignment` to `middle` would create the wanted effect and will work on both iOS and Android..

Example [here](https://play.nativescript.org/?template=play-ng&id=GXFhEd&v=3)

**Comment by Burgov** [comment]
Hi @NickIliev 

Setting `verticalAlignment` to `middle` works to center a Label within its parent, but not to center a Label's text within the Label. Without using android specific code, the only way to center text in a box, is by wrapping it in a (Grid)Layout, however, adding Layouts comes at a cost and I'm trying to minimize the use of them.

I wrote a directive which does the android specific trick on all labels, but I think it should be standard part of Nativescript - for consistency's sake. It makes it easier to develop apps that look the same on Android and on iOS
