### ISSUE TITLE
IOS receiving json with parentheses !!!

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#5978]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
YES
### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

I use socio.io Server and when i emit event from server i recive : 
```js
(
{
"auth_id" = 687019;
}
)
```
no problem with android i receive :
```js
{
"auth_id" = 687019;
}
```

### Which platform(s) does your issue occur on?
iOS
### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0
- Cross-platform modules: "tns-core-modules": "^4.1.0",
- Runtime(s): 
"tns-android": {
			"version": "4.1.3"
		},
		"tns-ios": {
			"version": "4.1.1"
		}
- Plugin(s): (look for the version number in the `package.json` file of your
project)

```js
//server.js
const http = require("http");
const server = http.createServer();
const io = require("socket.io")(server);

io.on("connect", (socket) => {
socket.emit("auth_id", {auth_id: 123});
});

//IOS
socketIO.on("auth_id", (data) => {
        console.log("AUTHORISATION ID :");
        console.log(data);
        //output
(
{
"auth_id" = 123;
}
)
```

Thnk you :)

**Comment by NickIliev** [comment]
@kefahB can you provide a sample application that can reproduce the issue (not being able to reproduce it with simple HTTP request on my side)

**Comment by kefahB** [comment]
Hello @NickIliev,

[https://gist.github.com/kefahB/35ee86cc985dbefbae73bf6affcbe3d1](here) a sample code represent my server.js and nativescript side (client) with nativescript-socketio dependencie

Thanks

**Comment by NickIliev** [comment]
@kefahB  the issue seems related to nativescript-socketio plugin so please open an issue in [the plugin's repository](https://github.com/triniwiz/nativescript-socketio/issues)

**Comment by kefahB** [comment]
HI @NickIliev,

I write console.log() in nodes-modules/nativescript-socketio/socketio.ios.d.ts 

```js
SocketIO.prototype.on = function (event, callback) {
        this.socket.onCallback(event, function (data, ack) {
            if (ack) {
                callback(data, ack);
            }
            else {
                callback(data);
                console.log(data) // THE RESOPONSE IS ALREADY MALFORMED ({"msg": "Hello"}) !!!
            }
        });
    };
```

when reciving the response from server, the response format was already malformed, this is the reason what i post my issue here.

Thank you.
