### ISSUE TITLE
Can't resolve scss files

### ISSUE THREAD

**Issue by waszqba** [NativeScript/NativeScript#5981]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
yes

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0
- Cross-platform modules: 4.0.0
- Runtime(s): 4.1.3
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

I have a problem with building and properly running the whole application. It was all fine on my device, it ran like a charm every time, but today there's some kind of a problem with imports. when I start `tns debug android` it builds the app and tries to launch it, but as soon as the splash screen passes, I get this:
```
JS: ns-renderer: ERROR BOOTSTRAPPING ANGULAR
JS: ns-renderer: Could not resolve /data/data/eu.neoteric.skillhunt/files/app/~nativescript-theme-core/scss/light. Looked for: /data/data/eu.neoteric.skillhunt/files/app/~nativescript-theme-core/scss/light.
JS: 
JS: Error: Could not resolve /data/data/eu.neoteric.skillhunt/files/app/~nativescript-theme-core/scss/light. Looked for: /data/data/eu.neoteric.skillhunt/files/app/~nativescript-theme-core/scss/light.
JS:     at FileSystemResourceLoader.resolve (file:///data/data/eu.neoteric.skillhunt/files/app/tns_modules/nativescript-angular/resource-loader.js:33:19) [<root>]
JS:     at FileSystemResourceLoader.get (file:///data/data/eu.neoteric.skillhunt/files/app/tns_modules/nativescript-angular/resource-loader.js:19:33) [<root>]
JS:     at DirectiveNormalizer._fetch (file:///data/data/eu.neoteric.skillhunt/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:3186:43) [<root>]
JS:     at file:///data/data/eu.neoteric.skillhunt/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:3382:41 [<root>]
JS:     at Array.map (<anony...
```
And this is after modifying `app-variables` imports to be `_app-variables.scss` everywhere, because that's what it couldn't find at first, but I can't modify bundle files.
Any help with that?

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3699
