### ISSUE TITLE
bar chart series all values starting from min value from data not from 0 (ios)

### ISSUE THREAD

**Issue by giorgi-abashidze** [NativeScript/NativeScript#5984]
in bar chart series all values starting from min value of data not from 0, on IOS only, on android it's ok.

it looks like this: [https://ibb.co/ksfVuo](https://ibb.co/ksfVuo)

I want to show data like this: [https://ibb.co/ii3NQT](https://ibb.co/ii3NQT)

maybe its not a bug and it have option for this, I don't know.

**Comment by NickIliev** [comment]
This issue was moved to telerik/nativescript-ui-feedback#709
