### ISSUE TITLE
androidOffscreenTabLimit is not working when the position is set to bottom

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/NativeScript#5987]
Hi. I see some issues with tab component in `nativescript-angular`. For managing loading and unloading views in tab items , `androidOffscreenTabLimit` is a good choice. I can scroll in first tab in a list view, go through the other tabs, come back to first tab, and I can see scroll position again (When tab is in top).

But when tab bar is in the bottom, no matter what the value of `androidOffscreenTabLimit` is, you can't see scroll position. [Here ](https://github.com/NativeScript/template-tab-navigation-ng/issues/78)we have had some discussion about it in  tab template repository.

Any idea?

**Comment by tsonevn** [comment]
Hi @vahidvdn,
I reviewed your case and found that setting up the tab bar at the bottom for Android will disable the preloaded functionality by design. You can check our [documentation](https://docs.nativescript.org/angular/ui/ng-ui-widgets/tab-view#tab-view), this has been mentioned at the beginning.

**Comment by vahidvdn** [comment]
Hi @tsonevn , thanks for the answer. I tested in multiple devices and found out something strange. It keeps scroll position based on different android versions. See these videos:

Huawei P9 (Android 6 with new update of Huawei gui)  **VS**  Huawei Honor6 (Android 4.4.2)
![giphy](https://user-images.githubusercontent.com/11078601/41838615-20246974-7876-11e8-93c2-1a8033b02d9c.gif) -------------- ![giphy 1](https://user-images.githubusercontent.com/11078601/41839697-2b51580e-7879-11e8-9261-126ecda71b5f.gif)

Logically, it must keep the history of scroll position. As well as all real world apps.

**Comment by tsonevn** [comment]
Hi @vahidvdn,
I tested this behaviour on my side on Android API level 22, 23 and 25, however on all of them the ListView position's state was saved and reset correctly. For your convenience, I am attaching a sample project. Can you review it and check if I am missing something. 
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2132652/Archive.zip)

**Comment by vahidvdn** [comment]
@tsonevn I tested your code, and it works fine in both devices. However I'm still wondering why the default template doesn't work fine in second device (or maybe in many devices). Would you please test it? (I attached the files or it's the same as you install from sidekick application)
[tnsTabBar.zip](https://github.com/NativeScript/NativeScript/files/2132922/tnsTabBar.zip)

And one question. Does iOS keep the scroll position as well?

**Comment by vahidvdn** [comment]
@tsonevn Also there is a difference between your example and the one is in sidekick. In the default app which is available in sidekick, when going through the tabs, it pushes the page. (see second video)

**Comment by tsonevn** [comment]
Hi @vahidvdn,
Thank you for the attached sample project. I reviewed it and found that the difference between both projects is that in tnsTabBar one, new page-router-outlet is created for every Tab in the TabView component. This will create new Frame for each tab, which seems to be related to the case with the ListView position reset on Android devices and simulators with lower API levels (e.g. 23, 22). We spent some time researching the case, and for now, it seems that this is something related to the OS and we can not control it. 

I can suggest removing the inner page-router outlets in the app.component.html and to define the Tabs as follow:
```
<TabView selectedIndex="1" selectedColor="#FF0000" androidTabsPosition="bottom">
    <StackLayout *tabItem="{title: 'Home', iconSource: getIconSource('home')}" >
        <GridLayout rows="" columns="">
                <home></home>
        </GridLayout>
       
    </StackLayout>
    <StackLayout *tabItem="{title: 'Browse', iconSource: getIconSource('browse')}">
        <GridLayout rows="" columns="">
                <browse></browse>
        </GridLayout>
        
    </StackLayout>
    <StackLayout *tabItem="{title: 'Search', iconSource: getIconSource('search')}">
        <GridLayout rows="" columns="">
                <search></search>
        </GridLayout>
    </StackLayout>
</TabView>
```

**Comment by vahidvdn** [comment]
Thanks @tsonevn 
I understand. Although it has lots of benefit when we separate the templates but as you mentioned it related to the OS and we can not control it. Btw, thanks for the support.
