### ISSUE TITLE
Bug very serious with navigation !

### ISSUE THREAD

**Issue by Fabiyo-90** [NativeScript/NativeScript#5992]
I use "NativeScript@4.1" with "nativescript-view@1.3.1" using the template designed with view / cli, "view-router@3.0.1", tns-core-modules@3.4.1 ".
When I use my router going from the "root page" to the third page with the method "$ route.push ('/ path')" everything goes well; while I'm on the second page and I press the return button of my android so I go back to the "root page" but when I'm on the third page and I press the back button of my android so to go back to the second page, I have an error

TypeError: can not read property '__ob__' of undefined

this error comes back to all "tns-android" versions including "tns-android@4.0.0", android@4.0.1 ", android@4.1.1", android@4.1.2 "and android@4.1.3 "

Bug very serious !

**Comment by NickIliev** [comment]
Closing as a duplicate to [https://github.com/nativescript-vue/nativescript-vue/issues/269](https://github.com/nativescript-vue/nativescript-vue/issues/269)

**Comment by jlooper** [comment]
This has to do with using the NativeScript Vue plugin with the Vue router. Moving to that repo
