### ISSUE TITLE
Adding android dependencies to NS

### ISSUE THREAD

**Issue by xeroxstar** [NativeScript/NativeScript#5993]
Hello, i have a small question (not a bug), i need to access to the scroll animation on android, i was referred to https://developer.android.com/guide/topics/graphics/fling-animation where i require to install  dependencie .

```
dependencies {
        implementation 'com.android.support:support-dynamic-animation:27.1.1'
}
```

 But where do i put this code in nativescript? I found a directory **(dist/platforms/android)** a build.gradle and added this line there:  

```
buildscript {
    
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        implementation 'com.android.support:support-dynamic-animation:27.1.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

but it won't work. Every time i start my app i get an error **Can not read property 'FlingAnimation' of undefined.**  I don't find any other build.gradle file in my app, is there a solution? I found a question same as mine here (https://github.com/NativeScript/NativeScript/issues/5230) but one of the links that @NickIliev provided won't work wich i guess explains how to install dependencies with nativescript. Thank you

**Comment by xeroxstar** [comment]
I found where i have to place my dependencies (dist/platforms/android/app/build.gradle) 

`compile "com.android.support:support-dynamic-animation:$supportVer"`

**Comment by tsonevn** [comment]
Hi @xeroxstar,
The dependency, which you need can be add in the `<project_name>/app/App_Resources/app.gradle` file. For example:
```
// Add your native dependencies here:

// Uncomment to add recyclerview-v7 dependency
dependencies {
	compile 'com.android.support:recyclerview-v7:+'
}

android {  
  defaultConfig {  
    generatedDensities = []
    applicationId = "org.nativescript.testFonts"  
  }  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }  
} 

```
In case the dependency is added in `platforms/android/app/build.gradle`, and you delete the platform folder, the dependency will not be added automatically. If you add it in the project folder as I suggested the dependency will be added whenever you decide to delete the platform and to create a new full build.
