### ISSUE TITLE
tabviewItem title sometimes showing with large font size sometimes a small font size (ios)

### ISSUE THREAD

**Issue by giorgi-abashidze** [NativeScript/NativeScript#5995]
tabviewItem title sometimes showing with large font size and text is not centered vertically, sometimes with a small font size on ios

**Comment by tsonevn** [comment]
Hi @giorgi-abashidze,
Can you provide more info about the problem and about your environment (CLI, tns-core-modules, tns-ios versions)? It will help if you send us sample project, which can be used for debugging.

**Comment by giorgi-abashidze** [comment]
core modules: 4.1.0
tns ios: 4.1.1
nativescript: 4.1.0

sorry I cant share the project.

on the page I have only tabview and listview in bots tabs

**Comment by giorgi-abashidze** [comment]
My bad, I had property row="4" on scrollview but the parent wasn't gridLayout, I removed it and everything is rendering well.

**Comment by giorgi-abashidze** [comment]
@tsonevn  well its very strange, I have 2 page, in second page I have some hidden view "collapsed" and I'm toggling its state on tap event, in this hidden view I have dropDown (I'm using drop down plugin).

in first page I have tabview.
case 1:
If I Go to first page first, tabview item titles are with small font size and centered well,
but when I go to second page after first and open drop down, the drop down text is also too small like tabview item title, which I dont like.

case 2:
if i go to second page first, make visible that hidden view and open dropdown, fontsize are normal "not too small" but, when i go to first page after this the tabview item title fons size is also normal "not too small like default on ios" which I dont like because if tabview item fontsize is not a small, text is not centered vertically and looks bad.

what I want is:
tabview item title to stay with small font size and drop down to stay with medium font size as default.

**Comment by tsonevn** [comment]
Hi @giorgi-abashidze,
Most probably you have defined some global font-size for the Page or some of the TabView parents, which also affects the TabView component. In this case, you can setup specific fontSize via CSS for the DropDown and the TabView 
```
.tabViewClass{
font-size:18;
}
.dropDownClass{
font-size:28;
}
```
