### ISSUE TITLE
[IOS] ListPicker property isEnabled not working

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#5996]
_From @manigorsh on June 26, 2018 12:42_

<ListPicker **isEnabled="false"** [items]="listPickerCountries" [(ngModel)]="selectedListPickerIndex"></ListPicker>

_Copied from original issue: NativeScript/nativescript-angular#1402_

**Comment by manigorsh** [comment]
@NickIliev isUserInteractionEnabled=false works on IOS, but on Android if you'll hold selector and try to switch it - it is possible. It switches slowly, but switches. I tried it on android emulator.
So workaround for me at this moment is to use two properties (isUserInteractionEnabled and isEnabled) together.

**Comment by NickIliev** [comment]
@manigorsh the thing is that the native implementation that stands behind `ListPicker` on iOS is not allowing to enable the property `isEnabled`. Closing this one as the behavior is expected due to the native control implementation.
