### ISSUE TITLE
iOS output verbosity

### ISSUE THREAD

**Issue by jnorkus** [NativeScript/NativeScript#5997]
### Tell us about the problem
`tns run ios` produces tons of verbose output that doesn't help when trying to debug or just see `console.log`. The output is very clean on Android but on iOS I get lost scrolling the console over and over again. Here is a sample of my output:
![image](https://user-images.githubusercontent.com/5137138/41919794-0a31a828-7968-11e8-9f04-b7b3033dab1f.png)

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.1
- Cross-platform modules: 3.4.1
- Runtime(s): 3.4.1
- Plugin(s): (not relevant)

**Comment by tsonevn** [comment]
HI @jnorkus,
I notice that you are using old modules and runtime. You can try upgrading to the latest available ones 4.1 and check if the issue persists on your side. For further help, you can review our [upgrade instructions](https://docs.nativescript.org/releases/upgrade-instructions).

**Comment by jnorkus** [comment]
I can confirm output is the same using the latest version of runtime and modules.

**Comment by tsonevn** [comment]
Hi @jnorkus,
Can you provide some sample project or at least some code snippets, which can be used for reproducing the issue? 
Thank you in advance for your cooperation.

**Comment by jnorkus** [comment]
I have isolated the issue to one device. Looks like it's not NS related. Not sure how to fix but will try resetting the device. Thanks for asking questions!

**Comment by GrEg00z** [comment]
Why the post is closed ?

The problem still persist, while using :
tns cli : 4.1.2
tns-ios 4.1.1

Problem only on iOS, where it's just impossible to debug (thousands logs lines in 10s)

**Comment by GrEg00z** [comment]
On simulator it's OK, the problem occurs only on real device (I use iphone 6)

**Comment by tsonevn** [comment]
Hi @GrEg00z, 
Which iOS version do you have on your device? Make sure that you are using the latest one. Also provide some info about the CLI, tns-core-modules, tns-ios versions, which you use.

**Comment by GrEg00z** [comment]
Im using iOS 11.2.6, it's not the last one so I will update my phone, and tell you if it was the problem.

My environnement :
 - nativescript 4.1.2
 - tns-core-module 4.1.0
 - tns-ios 4.1.1

**Comment by danbockapps** [comment]
I started a project with Nativescript 5.0 recently, and the console output from my iPhone 7 (with iOS 12) was pretty quiet until I added nativescript-plugin-firebase. Then there was a ton of verbose output, looking similar to the OP and not related to Firebase. Adding that plugin flipped some switch.
