### ISSUE TITLE
TS files do not get transpiled with NS Core and Typescript

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/NativeScript#5998]
Hello,

I am using NS version 4.1.0 Core with Typescript.  Recently, I started experiencing a problem with the TS files not getting transpiled on change.  

E.g. I run **tns run android,** then I make a change to a TS file, the app refreshes the TF file, but not the corresponding JS file.  If I run **tsc** separately, the app is refreshed again and the updated JS is transferred to the device.  This happens with iOS and Android and on Windows and Mac machines.  This also happens if I run the app through SideKick, the command prompt, or VS Code.  Bellow is mu package.json:

```
{
  "description": "...",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.company.project",
    "tns-android": {
      "version": "4.1.3"
    },
    "tns-ios": {
      "version": "4.1.1"
    }
  },
  "dependencies": {
    "@nstudio/nativescript-camera-plus": "1.0.6",
    "moment": "2.22.2",
    "nativescript-camera": "4.0.2",
    "nativescript-imagepicker": "6.0.2",
    "nativescript-loading-indicator": "2.4.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-sidedrawer": "4.1.1",
    "tns-core-modules": "4.1.0"
  },
  "devDependencies": {
    "awesome-typescript-loader": "~5.0.0",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "clean-webpack-plugin": "~0.1.19",
    "copy-webpack-plugin": "~4.5.1",
    "css-loader": "~0.28.11",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.12.0",
    "nativescript-worker-loader": "~0.9.0",
    "raw-loader": "~0.5.1",
    "typescript": "~2.7.2",
    "uglifyjs-webpack-plugin": "~1.2.5",
    "webpack": "~4.6.0",
    "webpack-bundle-analyzer": "~2.13.0",
    "webpack-cli": "~2.1.3",
    "webpack-sources": "~1.1.0"
  },
  "author": "..."
}
```

Perhaps you can also make a comment at: https://stackoverflow.com/questions/51027942/nativescript-documentation-for-ns-core-with-typescript.

Any suggestions?

**Comment by tsonevn** [comment]
Hi @dpdragnev,
I tested your case while using the same dependencies' versions in the sample project, however, I was unable to recreate the issue with the transpilation. For your convenience I am attaching the sample project, can you review it and try whether you will have the same issue with it.  Also, does this happen while building the project with `tns run <platform name>` command or only while building with webpack -> `tns run <platform name> --bundle`?
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2139904/Archive.zip)

**Comment by tsonevn** [comment]
Hi @dpdragnev,
We investigated further the case and found that if the `hooks` folder is missing or deleted for some reason, the typescript compiler will be killed, and the transpilation will stop.  To solve the case, you can try to remove `node_modules` and `platforms` folder and start the build again via `tns run <platform name>`. The `hooks` folder will be generated again and the `tsc` command should be executed on every ts file change.

**Comment by dpdragnev** [comment]
YES!  That did it.  Thank you @tsonevn
