### ISSUE TITLE
htmlview remove links

### ISSUE THREAD

**Issue by peppeg85** [NativeScript/NativeScript#5999]
hi, i have htmlview filled dynamically, it displays links in case of dot withiut space after, and sometimes also dot with space...is there a way to fix this?
i tried with webview, but the autozoom is useless for my application 
thank you

**Comment by tsonevn** [comment]
Hi @peppeg85,
Can you provide more info about your problem? It will help if you provide more info about the (CLI, tns-core-modules, runtime versions and send us sample project, which can be used for debugging.

**Comment by peppeg85** [comment]
hello, i solved with  webView.android.getSettings().setDisplayZoomControls(false); and binding the src text with <div style="xxx">
i must use 
tns-core-modules": "~3.4.0"
	"tns-android": {
			"version": "3.4.3"
		}
