### ISSUE TITLE
first loading is slow?

### ISSUE THREAD

**Issue by bitcard** [NativeScript/NativeScript#6]
I run the samples "Tasks" and "cuteness" on android device. first loading is almost 8-15s.

**Comment by phienkaka** [comment]
I also got the same issue. I use my phone LG Optimus G pro. F240K.

**Comment by ligaz** [comment]
Thanks for this feedback guys. The startup performance on Android has already been addressed and will be available in the next public update of the Android runtime. You can read more about this on Misho's blog [here](http://iobservable.net/blog/2015/03/09/on-nativescript-performance/).

**Comment by bitcard** [comment]
Thanks for your reply, I read the article, it's a great news. NativeScript is so coolest.

**Comment by phienkaka** [comment]
Thank you. That is very cool, waiting for the next version. :+1:

**Comment by Anilinfo2015** [comment]
It is very slow for me too.
