### ISSUE TITLE
build add --snapshot option  very very slow

### ISSUE THREAD

**Issue by momoling** [NativeScript/NativeScript#6003]
i try to generate a release apk
build without --snapshot to generate take 2 minute
but i add --snapshot togenerate 
the cmd do not move
it is always show 

generating snapshot for armeabi-v7a 
loading script for embedding: *******/platforms/android/app/src/main/assets/app/_embedded_script_.js
and so on

**Comment by tsonevn** [comment]
Hi @momoling,
Make sure that you are not using the old nativescript-dev-android-snapshot plugin, which is deprecated. The recommended way or using V8 Heap Snapshot feature in the context of NativeScript is via nativescript-dev-webpack plugin in combination with the --snapshot flag. For further help, you can review the article [here](https://docs.nativescript.org/performance-optimizations/bundling-with-webpack#v8-heap-snapshot).

**Comment by momoling** [comment]
@tsonevn thank you first.
i try to understand the article and try once.
through using {ns},i study a lot of knowledge.

**Comment by momoling** [comment]
i git https://github.com/NativeScript/sample-Groceries
and try to 
tns build android --bundle --env.uglify --env.aot --env.snapshot --release --keyStorePath /usr/local/src/example.jks --keyStorePassword 123456 --keyStoreAlias example --keyStoreAliasPassword 123456

ERROR in NativeScriptSnapshot. Snapshot generation failed!
Target architecture: x86
Segmentation fault

Loading script for embedding: /usr/local/src/sample-Groceries-master/platforms/android/app/src/main/assets/app/_embedded_script_.js
[Initializing context from scratch took 12.127 ms]
Executing custom snapshot script <embedded> took 634.801 ms
Deserialization will reserve:
   5078504 bytes per isolate
   2124784 bytes per context #0
Snapshot blob consists of:
   3861536 bytes for startup
   1142636 bytes for builtins
    804076 bytes for context #0
Creating snapshot took 1068.778 ms

**Comment by tsonevn** [comment]
Hi @momoling,
I investigated further the case. While testing this scenario on a windows

**Comment by tsonevn** [comment]
Hi @momoling,
I investigated further the issue, and I notice that you are trying to build the project with a snapshot on a windows machine.  Currently, the snapshot is not supported in Windows. If you start the build with `--env.snapshot` while using latest NativeScript 4.1, the following message should be displayed in the console `Stripping the snapshot flag. Bear in mind that snapshot is only available in release builds and is NOT available on Windows systems.`. Regarding that, you can build on release only using Webpack, which should also minimise the app size.
