### ISSUE TITLE
back button ios

### ISSUE THREAD

**Issue by peppeg85** [NativeScript/NativeScript#6009]
hello, i have a "stupid" problem, i have an app running fine on android, now i'm trying running on ios, i'm using the system emulator, following the official guide on actionbar:

https://docs.nativescript.org/ui/action-bar#navigation-button

on android i have the back button, but on ios i don't, i followed the instructions, i tried also changing the text with the name of the previous page, but with no result...how can i solve this? adding an actionitem right aligned?

thank you

**Comment by tsonevn** [comment]
Hi @peppeg85, 
The back button on iOS should be shown on the ActionBar, while you navigated to some of the inner pages in the app.
To investigate further your case and what is the issue, please provide some more info about the case. It will also help if you send us sample project, which can be used for debugging.

**Comment by peppeg85** [comment]
hello @tsonevn, here is the xml of the page:

 `
                       <Page loaded="loaded" class="page" actionBarHidden="false">
                                   <ActionBar class="action-bar" title="Invio stringa" horizontalAlignment="center">
                                   <NavigationButton text="Go Back" android.systemIcon="ic_menu_back"                                 tap="backHome"/>
    </ActionBar>

    <GridLayout columns="*,*,*,*" rows="auto,auto, 50, 50, 50, 70" class="grid-fonts">

        <Image id="logo" colSpan="4" row="1" src="res://logoblack" horizontalAlignment="center"/>

        <Label text="Data" textWrap="true" row="2" col="1" colSpan="2"></Label>
        <Switch checked="false" tap="date" id="0" row="2" col="3" class="m-15"></Switch>
        <Label text="Ora" textWrap="true" row="3" col="1" colSpan="2"></Label>
        <Switch checked="false" tap="hour" id="1" row="3" col="3" class="m-15"></Switch>
        <Label text="Temperatura" textWrap="true" row="4" col="1" colSpan="2"></Label>
        <Switch checked="false" tap="temp" id="2" row="4" col="3" class="m-15"></Switch>
        <Button row="5" col="1" colSpan="2" text="colore" tap="colorpicker" />

    </GridLayout>

</Page>

`

as you can see, nothing particular, I use a custom css file generated with native script theme builder, how can I send it?
thinking about that I see that on android I have blu action bar but not on iOS, maybe I need to add a specific app css file for iOS? could be this?

thank you again

**Comment by tsonevn** [comment]
Hi @peppeg85,
Thank you for the attached sample code. 
I tested it on my side in a sample project, however, was unable to recreate your case. For your convenience, I am attaching sample project and GIF file, which demonstrates the behaviour on my side. Please review the project and make the needed changes, which will allow us to recreate the case. 
Also provide some more info about your environment(CLI, tns-core-modules, tns-ios versions).
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2157803/Archive.zip)
![test](https://user-images.githubusercontent.com/17448734/42201026-c19bcc6a-7e9e-11e8-963b-2c50cef4411d.gif)

**Comment by peppeg85** [comment]
hello, thanks for your help, here is the package.json configuration:

{
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": {
		"id": "org.nativescript.xx",
		"tns-android": {
			"version": "4.0.1"
		},
		"tns-ios": {
			"version": "3.4.1"
		}
	},
	"dependencies": {
		"moment": "^2.22.2",
		"nativescript-bluetooth": "^1.3.0",
		"nativescript-checkbox": "^3.0.3",
		"nativescript-color-picker": "^1.3.2",
		"nativescript-gif": "^3.1.1",
		"nativescript-maskedinput": "0.0.3",
		"nativescript-modal-datetimepicker": "^1.1.0",
		"nativescript-theme-core": "~1.0.4",
		"npm": "^6.1.0",
		"tns-core-modules": "^4.1.0"
	},
	"devDependencies": {
		"babel-traverse": "6.4.5",
		"babel-types": "6.4.5",
		"babylon": "6.4.5",
		"lazy": "1.0.11"
	}
}

could it be the css file generated with nativescript themebuilder
[Nuovo Archivio WinRAR ZIP.zip](https://github.com/NativeScript/NativeScript/files/2158267/Nuovo.Archivio.WinRAR.ZIP.zip)

thank you again

**Comment by tsonevn** [comment]
HI @peppeg85,
I reviewed the attached CSS file, however, I was unable to find something that can cause this issue.
I also notice that you are using old iOS runtime. Regarding that I will suggest upgrading to latest available one while following the below-attached steps:
1. `tns platform remove ios`
2. `tns platform add ios`
3. `tns run ios`
If the problem persists, please provide a sample, which can be used for debugging.

**Comment by peppeg85** [comment]
ok, @tsonevn thank you for the support, i will try in the next days

**Comment by tsonevn** [comment]
Hi @peppeg85,
Were you able to resolve your case?
