### ISSUE TITLE
Translucent status/navigation bar support

### ISSUE THREAD

**Issue by toddwong** [NativeScript/NativeScript#601]

**Comment by lscown** [comment]
:+1: 

extends #516

**Comment by toddwong** [comment]
I just knew that Android (above 4.4) has translucent system bars support, too.  I change the issue title.

**Comment by enchev** [comment]
copied from https://github.com/NativeScript/NativeScript/issues/516
---------------------------------------------------------------------------------------
Right now the status bar inherits the colour from it's ActionBar/NavigationBar. This is not so great when you have a hidden ActionBar.

It would be great to be able to hide the status bar or add custom colours to it.

CSS property suggestions:

color
background-color

Would be great to have the status bar transparent as well. This goes for both iOS and Android (I believe the Android one overlays the background content.)

**Comment by toddanglin** [comment]
Is this still targeting the 1.6 milestone? Super common use case. I could use this support now for a simple demo app. :)

**Comment by burkeholland** [comment]
I got tired of doing this over and over again in `pageLoaded` because I do it virtually every time, so I created a plugin to make this as easy as a line of markup...

````
<x:StatusBar barStyle="light" />
````

![status-bar-light](https://github.com/burkeholland/nativescript-statusbar/blob/master/images/status-bar.png)

Looks like this is going to hit in 1.7, so hopefully we can deprecate this plugin then.

**Comment by burkeholland** [comment]
I'll note that I can only get `setBarStyle` to work when the ActionBar is present. When it is not, the StatusBar is **always** white. I thought that the StatusBar was transparent by default as of iOS 7. is there some setting I need to get the page all the same color besides just...

````
page {
    background-color: #336699;
}
````

![](https://www.evernote.com/shard/s149/sh/3be0a1c8-fee8-44a4-8e99-8bed6ce9c92d/5ae955f39aa81e9b/res/32ca94bc-0df3-4c7b-8d9f-67c230cd7929/skitch.png?resizeSmall&width=832)

**Comment by PanayotCankov** [comment]
@burkeholland The Page has a boolean `backgroundSpanUnderStatusBar` property that works for iOS and you can set it in XML (does not work in CSS yet). https://github.com/NativeScript/NativeScript/blob/master/ui/page/page.d.ts#L99

**Comment by burkeholland** [comment]
Thank you! Too easy.

Seems like this should be on by default to mimic the default iOS behavior?

**Comment by PanayotCankov** [comment]
We were discussing this internally today. It may very well become a default.

**Comment by sitefinitysteve** [comment]
I vote for a default open in {N}, this is a core app style thing, not really a plugin, should be a property off Page or something

**Comment by majorpaynegh** [comment]
@burkeholland and anyone what if I want an image to span under the status bar??

**Comment by NickIliev** [comment]
@majorpaynegh 

You can set background image for your Page via CSS and use the `backgroundSpanUnderStatusBar` property to span it under the status bar.

e.g.
page.css
```
Page {
    background-image: url("~/images/logo");
}
```
page.xml
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" backgroundSpanUnderStatusBar="true" >
</Page>
```

**Comment by majorpaynegh** [comment]
@NickIliev i tried this and it refuses to work ..status bar still remains the same..

**Comment by timricker** [comment]
Is it possible to allow the page content itself to be seen underneath the status bar on iOS?

Eg, lets say I have a StackLayout as the first element inside my base app component. I want this to be displayed at the very top of the screen with status bar displayed transparently on top of it.

I can't seem to achieve this using the `backgroundSpanUnderStatusBar` page property. The page content is always displayed underneath the status bar. I am able to change the background color, however this isn't giving the desired result of a truly translucent status bar.

Any help/feedback appreciated.

**Comment by timricker** [comment]
For anyone interested, I was able to achieve the desired effect using:
`this._page.style.marginTop = -20;`

**Comment by majorpaynegh** [comment]
@timricker this makes makes my app crash when i launch it.where did you put this line of code

**Comment by timricker** [comment]
@majorpaynegh try putting it inside `ngAfterViewInit` on your base app component, it should work. In my app I'm setting it after i make a $http request but this isn't likely required in your case.

**Comment by corebreaker** [comment]
The project of @burkeholland seems dead, someone can do a plugin for stylying the status bar and with Angular please. At now, not support for Angular.
