### ISSUE TITLE
ListView template have an inconsistent widths

### ISSUE THREAD

**Issue by fthuin** [NativeScript/NativeScript#6018]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
I discussed with @NickIliev on Slack, and he told me that this issue (for me, it's related to #5793 ) should have been resolved in tns-core-modules 4.2, but it doesn't. 

### Tell us about the problem

I have a ListView, different templates inside it (6 different templates) and 2 of them change their widths when I navigate. If I interact with them, they resize properly.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.2
- Cross-platform modules: 4.2.0-2018-06-29-01
- Runtime(s): tns-android 4.1.3
- Plugin(s): a lot, but none are necessary to reproduce the bug.

### Please tell us how to recreate the issue in as much detail as possible.

So the issue is shown here, if I'm scrolling from top to bottom, the elements are displayed correctly. But if I scroll back to top, some of the templates are taking 100% of the width... and if I interact with them, they go back to their expected width. Here is a Youtube video showing the problem and a Google Drive link with the code I run (`tns run android`) to produce the video.

https://www.youtube.com/watch?v=1zCRVfQpQ-k

https://drive.google.com/file/d/1zkpn9O8gocfoGQ6lWHIWNZAY9yfaSEVI/view?usp=sharing

**Comment by tsonevn** [comment]
Hi @fthuin,
Thank you for the attached project. I tested it on my side with `@next` tns-core-modules, and it seems that the problem persists. I will mark this as a bug, and you can keep track of the issue for further info.
