### ISSUE TITLE
[Modal] [Embedded ios] App crashes when opening a modal

### ISSUE THREAD

**Issue by jolafrite** [NativeScript/NativeScript#6019]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes (I also submitted https://github.com/telerik/nativescript-ui-feedback/issues/716)

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
When the app is embedded into a native iOS app, opening a modal, crashes the app with the error Thread 1: EXC_BAD_ACCESS (code=1, address=0x18)

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.2.0-2018-06-26-11829
- Cross-platform modules: 4.2.0-2018-06-29-01
- Runtime(s): IOS@4.1.1

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 
1- Clone the repo https://github.com/jolafrite/ns-embedded-test
2- Open a terminal and then navigate to where you downloaded this repo at
3- ```cd ns-embedded-ns```
4- ```tns install```
5- In the current version of tns-core-modules you must download manually the folder ```https://github.com/NativeScript/NativeScript/tree/master/tns-core-modules/platforms``` and copy it into ```node_modules/tns-core-modules```
6- ```tns build ios --bundle --env.aot```
7- ```cd ../ns-embedded-ios```
8- ```pod install```
9- Open ```ns-embedded-ios/ns-embedded-ios.xcworkspace``` in xcode
10- Press the ```play button```
11- Open the side navigation and press the nativesript menu item
12- When the car list is loaded, tap on a car
13- Tap the edit button
13- The app will crash with ```Thread 1: EXC_BAD_ACCESS (code=1, address=0x18)```

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

see previous answer

![screen shot 2018-07-03 at 3 31 12 pm](https://user-images.githubusercontent.com/579224/42206765-a918cc2e-7eda-11e8-8087-e969f3782da0.png)

**Comment by tsonevn** [comment]
Hi @jolafrite,
Thank you for the sample project and the provided steps to reproduce. 
I tested it on my side and was able to recreate the issue. We will investigate further the problem. For now, I will suggest keeping track of the issue, and we will provide more info on it.

**Comment by mbektchiev** [comment]
The fix is in the iOS runtime and has been released with version 4.2.0. Here's the PR which addresses it: https://github.com/NativeScript/ios-runtime/pull/954
