### ISSUE TITLE
Cannot create a new project (EACCES)

### ISSUE THREAD

**Issue by sturcpavel** [NativeScript/NativeScript#602]
After installing tns and other dependencies, I've tried to create a new project by a simply writing:

`tns create new-project`

but after a while, error occured:

`EACCES, open '/home/pavel/.local/share/.nativescript-cli/.lock'`

I fixed it by chown:

`sudo chown -R $(whoami) $HOME/.local/share/.nativescript-cli`

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#815
