### ISSUE TITLE
Android 7.0/8.0 Request permission is not prompted

### ISSUE THREAD

**Issue by liuchuancong** [NativeScript/NativeScript#6020]
``` <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

I don't have any tips on my phone （Android 8.0）

**Comment by liuchuancong** [comment]
i want use geolocation,
on 6.0 i do it, but on 8.0 it can't

**Comment by tsonevn** [comment]
HI @liuchuancong,
I tested your case with our nativescript-geolocation demo app, however, was unable to recreate an issue with permission requests, while using Android 8. You can check the demo app [here](https://github.com/NativeScript/nativescript-geolocation/tree/master/demo). It will help if you provide more info about your environment(CLI, tns-core-modules, tns-android versions). Also, send us sample project, which can be used for debugging.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-geolocation#144
