### ISSUE TITLE
howTo: update nativescript for a single project locally

### ISSUE THREAD

**Issue by peppeg85** [NativeScript/NativeScript#6024]
hello, like the topic says...is possible to upgrade the NS version for a single project? not globally?
from this guide:
https://docs.nativescript.org/releases/upgrade-instructions
i see that the command npm install -g nativescript should be global(-g), but if i remove the -g qhen i run tns android it execute the installed version of ns 3.4.3, not the updated version.

thank you

**Comment by NickIliev** [comment]
When you run 
```
npm i -g nativescript
```
You are installing the **NativeScript command line interface** (a.k.a. **CLI**). The CLI enables the commands [in this article section](https://docs.nativescript.org/tooling/docs-cli/start) and updating to latest CLI will provide you with the latest globally installed commands.

To update the porject dependencies (e.g. like `tns-core-modules`) and the platform runtime (`tns-android` and `tns-ios`) you can use `tns update` and/or manual npm commands (e.g. `npm i tns-core-modules@latest --save`).

The runtimes can also be updated via CLI command as follows
```
tns platform add android
```

Full upgrade instructions and descriptions of each command can be found in [this documentation article](https://docs.nativescript.org/releases/upgrade-instructions).
