### ISSUE TITLE
iOS - project doesn't build

### ISSUE THREAD

**Issue by miroslavaivanova** [NativeScript/NativeScript#6026]
### Tell us about the problem
If you create a project with space in the name and try to build ios , you will see exception

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: next: (4.2.0-2018-07-04-11903)
- Cross-platform modules: @4.2.0-2018-07-04-01
- Runtime(s): next

### Please tell us how to recreate the issue in as much detail as possible.
1. tns create "Test App"
2. tns platform add ios@next
3. tns build ios
you will see two folders in tns-core-modules: platform and platforms
the exception is: 
```Xcode build...
2018-07-04 13:56:33.530 xcodebuild[38841:990585] Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected character / at line 1" UserInfo={NSDebugDescription=Unexpected character / at line 1, kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Expected terminating ')' for array at line 375" UserInfo={NSDebugDescription=Expected terminating ')' for array at line 375}}
xcodebuild: error: Unable to read project 'TestApp.xcodeproj'.
	Reason: Project /Users/nsbuilduser/workspace/CLI-stable-tests-build-ios-common-osx/Test App/platforms/ios/TestApp.xcodeproj cannot be opened because the project file cannot be parsed.


?[31;1mCommand xcodebuild failed with exit code 74?
```

**Comment by dtopuzov** [comment]
Caused by https://github.com/NativeScript/NativeScript/pull/6007

**Comment by NickIliev** [comment]
@miroslavaivanova I am not sure if this clalifies as a bug as we are s[pecifying that white spaces are not allowed in the project name.

For example run
```
tns help create
```

And in the help section for <App Name> it will state

> <App Name> is the name of the project. The specified name must meet the requirements of all platforms that you want to target. For projects that target Android, you can use uppercase or lowercase letters, numbers, and underscores. The name must start with a letter. For projects that target iOS, you can use uppercase or lowercase letters, numbers, and hyphens.
