### ISSUE TITLE
Error when pressing Back to home screen, then opening app again

### ISSUE THREAD

**Issue by medozs** [NativeScript/NativeScript#6028]
> JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
> System.err: com.tns.NativeScriptException:
> System.err: Calling js method onCreateView failed
> System.err:
> System.err: TypeError: Cannot read property 'length' of undefined
> System.err: File: "file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/animation/keyframe-animation.js, line: 84, column: 61
> System.err:
> System.err: StackTrace:
> System.err:     Frame: function:'KeyframeAnimation.parseKeyframe', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/animation/keyframe-animation.js', line: 84, column: 62
> System.err:     Frame: function:'KeyframeAnimation.keyframeAnimationFromInfo', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/animation/keyframe-animation.js', line: 63, column: 51
> System.err:     Frame: function:'', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/styling/style-scope.js', line: 293, column: 79
> System.err:     Frame: function:'CssState.playKeyframeAnimations', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/styling/style-scope.js', line: 287, column: 27
> System.err:     Frame: function:'', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/styling/style-scope.js', line: 281, column: 19
> System.err:     Frame: function:'ViewBase._batchUpdate', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 278, column: 20
> System.err:     Frame: function:'CssState.updateDynamicState', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/styling/style-scope.js', line: 278, column: 19
> System.err:     Frame: function:'CssState.onLoaded', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/styling/style-scope.js', line: 266, column: 14
> System.err:     Frame: function:'ViewBase.onLoaded', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 230, column: 24
> System.err:     Frame: function:'View.onLoaded', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 194, column: 35
> System.err:     Frame: function:'', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 90
> System.err:     Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
> System.err:     Frame: function:'ViewBase.callLoaded', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 14
> System.err:     Frame: function:'ViewBase.loadView', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 439, column: 18
> System.err:     Frame: function:'', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 233, column: 19
> System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
> System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 855, column: 14
> System.err:     Frame: function:'ViewBase.onLoaded', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 232, column: 14
> System.err:     Frame: function:'View.onLoaded', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 194, column: 35
> System.err:     Frame: function:'', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 90
> System.err:     Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
> System.err:     Frame: function:'ViewBase.callLoaded', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 14
> System.err:     Frame: function:'ViewBase.loadView', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 439, column: 18
> System.err:     Frame: function:'', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 233, column: 19
> System.err:     Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
> System.err:     Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 120, column: 40
> System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 855, column: 14
> System.err:     Frame: function:'ViewBase.onLoaded', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 232, column: 14
> System.err:     Frame: function:'View.onLoaded', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 194, column: 35
> System.err:     Frame: function:'Page.onLoaded', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/page/page.js', line: 43, column: 35
> System.err:     Frame: function:'', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 90
> System.err:     Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
> System.err:     Frame: function:'ViewBase.callLoaded', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 14
> System.err:     Frame: function:'ViewBase.loadView', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 439, column: 18
> System.err:     Frame: function:'ViewBase._addViewCore', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 434, column: 18
> System.err:     Frame: function:'ViewBase._addView', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 420, column: 14
> System.err:     Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 576, column: 24
> System.err:     Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/org.mycompany.myapp/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38
> System.err:
> System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
> System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
> System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
> System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:970)
> System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:954)
> System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:946)
> System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:45)
> System.err:     at android.app.Fragment.performCreateView(Fragment.java:2353)
> System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
> System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
> System.err:     at android.app.BackStackRecord.run(BackStackRecord.java:816)
> System.err:     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
> System.err:     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
> 15:32:24 - File change detected. Starting incremental compilation...

tns Version 4.1

Details:

When I press back android button and there is no previous pages, it goes to home screen. When I try to navigate back to app, it throws that error. Splash screen is shown when I navigate back to app then app throws error. This also happens when I tap on app notification. 

Thank You,

**Comment by tsonevn** [comment]
HI @medozs,
I have tested your case in the sample project, however, I was unable to recreate the problem with the app crash on my side. Regarding that, can you provide some more info about your environment(tns-core-modules, tns-android, nativescript-angular versions)? I am also attaching sample project, please review it and make the needed changes, which will allow us to recreate the issue.

In the meantime you can try removing the platform with `tns platform remove android` and to rebuild the project `tns run android`.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2165029/Archive.zip)

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1414
