### ISSUE TITLE
Support for some vector graphics similar to HTML5's SVG

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#603]
For `.svg` files see: https://github.com/peoplewareDo/nativescript-svg

---

[A nice short overview.](http://www.w3schools.com/html/html5_svg.asp)
This will allow us to present some of the icons using vectors.

 - [The android implementation can make a good use of the ShapeDrawable](http://developer.android.com/reference/android/graphics/drawable/ShapeDrawable.html)
 - [For iOS a View superclass can be used by implementing the drawRect:](https://developer.apple.com/library/ios/documentation/2DDrawing/Conceptual/DrawingPrintingiOS/BezierPaths/BezierPaths.html)

I could see a sound synergy with the animation framework #255.

**Comment by lscown** [comment]
:+1:

**Comment by jlooper** [comment]
I'd also +1 the ability to use .svg

**Comment by divyan** [comment]
+1

**Comment by grimmjow** [comment]
+1

**Comment by rui-cruz** [comment]
+1

**Comment by PanayotCankov** [comment]
[You can vote for this feature here](https://nativescript.ideas.aha.io/ideas/NS-I-69).

**Comment by PanayotCankov** [comment]
@jlooper: .SVG support will probably best come with a plugin https://github.com/NativeScript/NativeScript/issues/944

**Comment by enchev** [comment]
Merged with https://github.com/NativeScript/NativeScript/issues/944

**Comment by PanayotCankov** [comment]
@enchev This is different than SVG files. Supporting SVG elements in our visual tree will allow us to target them with selectors and animate different pieces of them with CSS animations. While the SVG files behave more like an image, that you can target different parts in.

**Comment by victorsosa** [comment]
Hi, @PanayotCankov 

> 
Supporting SVG elements in our visual tree will allow us to target them with selectors and animate different pieces of them with CSS animations.

How this should work exactly? If you are ok, can you please post an propose animate api for it?, please.

**Comment by PanayotCankov** [comment]
For example HTML supports this:
```
<!DOCTYPE html>
<html>
<head>
<style> 
#grafic {
    background: gray;
}
#grafic path {
    stroke-width: 3;
    stroke: red;
    fill: green;
}
#grafic #tri1 {
    transform: translate(0px,0px);
    transition: transform 0.4s;
}
#grafic #tri2 {
    transform: translate(0px,0px);
    transition: transform 0.4s;
}
#grafic:hover #tri1 {
    transform: translate(0px,-10px);
    transition: transform 0.4s;
}
#grafic:hover #tri2 {
    transform: translate(0px,10px);
    transition: transform 0.4s;
}
</style>
</head>
<body>

<svg id="grafic" width="80" height="80">
  <path id="tri1" d="M 20 20 l 40 0 -20 20 Z" />
  <path id="tri2" d="M 20 60 l 40 0 -20 -20 Z" />
</svg>

</body>
</html>
```

In {N} we can for example add `:selected` pseudo selector for `ListViewItem` and then allow the selection state to be animated using some fancy checkbox SVG graphics and CSS similar to the one above.

I don't know how to propose animate API since its web standard anyway.

**Comment by victorsosa** [comment]
base on this [inline-css-style-sheets](http://tutorials.jenkov.com/svg/svg-and-css.html#inline-css-style-sheets) you can do it inside the svg and then it should work.

**Comment by PanayotCankov** [comment]
We have clip-path now

**Comment by jonnyroc** [comment]
just wondering there is currently no support for d3js right?

**Comment by victorsosa** [comment]
@jonnyroc no, but I don't think it need support because d3js can be used as it is. I don't see any limitation.

**Comment by yoat** [comment]
This [clip-path Playground demo](https://play.nativescript.org/?template=play-ng&id=9wkGbB) does not work and throws errors.  Even if clip-path works, it didn't provide support for loading SVG images as files. The alternative (https://github.com/peoplewareDo/nativescript-svg) also does not work and is not maintained.  

We do still need this feature but both the workarounds described here do not appear to cover it.  

Maybe I'm wrong about clip-path, but I can find no reference/example of it being used to load SVG graphics inline.
