### ISSUE TITLE
wrong constructor for android.content.ServiceConnection

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/NativeScript#6031]
In the android17.d.ts the constructor for ```android.content.ServiceConnection``` is wanting an ```implementation``` parameter which is wrong.
All ```implementation``` parameters for android constructor should be removed.
This is quite important as your tic won't work because of that and if you put a null parameter you app will crash.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#1107
