### ISSUE TITLE
webview openurl ios

### ISSUE THREAD

**Issue by peppeg85** [NativeScript/NativeScript#6032]
hi, i fount this code for android to open webview urls outside of the app:

```
        exports.webViewLoaded = function(args) {
            var webview = args.object;
            var TNSWebViewClient =
                android.webkit.WebViewClient.extend({
                    shouldOverrideUrlLoading: function(view, url) {
                        if (url != null && url.startsWith("https://")) {
                            console.log(url);
                            utilityModule.openUrl(url)
                            return true;
                        } else {
                            return false;
                        }
                    }
                });
            if (isAndroid) {
                  webview.android.getSettings().setDisplayZoomControls(false);
                  webview.android.getSettings().setBuiltInZoomControls(false);
                  webview.android.setWebViewClient(new TNSWebViewClient());
                   }  
             }
```

it works fine, is there a way to do the same for ios?

thank you

**Comment by tsonevn** [comment]
HI @peppeg85,
You can use [nativescript-webview-interface](https://www.npmjs.com/package/nativescript-webview-interface) plugin for bi-directional communication between WebView and Android/iOS. Also, you can use the `openUrl` method for opening the needed website on the default device browser on both(iOS and Android).

For further how-to questions, please use our [forum](https://discourse.nativescript.org/) or StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript). This repository is used for bug reporting and feature requests.

**Comment by peppeg85** [comment]
hello @tsonevn,
thank you for your answers and sorry if i write here, i'm trying the plugin, it works, renders the html i pass to, but how can i capture the tap on a link(both on ios and android)?
i've seen that there are the various events handler...but wich would be the event 'tap on link'?
sorry and thank you
