### ISSUE TITLE
Label nativeElement numberOfLines doesn't resize frame

### ISSUE THREAD

**Issue by JillevdW** [NativeScript/NativeScript#6037]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

Yes; I have not found any similar issues.

### Tell us about the problem

When trying to set a max number of lines with the following code: 
`
let label = <Label>ref.nativeElement;
if (platformModule.isIOS) {
    label.ios.numberOfLines = 3;
} else {
    label.android.setMaxLines(3);
}
`
the Label is correctly cut off after three labels. However, it looks like on iOS the frame of the label does not get smaller.

Expected behaviour (this is taken on Android): 

![image](https://user-images.githubusercontent.com/23138608/42379186-4598e9e8-812a-11e8-9424-ff83dde3a9bf.png)

Observed behaviour (this is taken on iOS):

![image](https://user-images.githubusercontent.com/23138608/42379240-5c8dee8c-812a-11e8-8787-f0479dabe04c.png)

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.2
- Cross-platform modules: 4.1.0
- Runtime(s): iOS: 4.1.1, android: 4.1.3

I hope this is enough to fix this problem. If there is anything else you need, please contact me.

**Comment by NickIliev** [comment]
Hey @JillevdW there is no support for `maxLines` in NativeScript - [the feature is logged here](https://github.com/NativeScript/NativeScript/issues/4315) and anyone interested in implementing this one is welcome to contribute.

Regarding your issue when accessing the native iOS property - you could change the height of your iOS label based on the number of lines and font-size (+ minimum padding for each eline).

e.g. something like the following:
```TypeScript
let fontSize = label.fontSize; // the font-size should be assigned via CSS or fontSize property (not the defaut global one)
let textPadding = 4; // padding for eahc line of text
let maxLines = 3;

label.ios.numberOfLines = maxLines;
label.height = ((fontSize + textPadding) * maxLines);
```

**Comment by JillevdW** [comment]
@NickIliev alright, this is a sufficient workaround for now. Is there a guide on implementing features into NativeScript? I could try to take a look into it.

**Comment by NickIliev** [comment]
@JillevdW you could look at[ the base contributing guide](https://www.nativescript.org/contribute) and also at [the detailed guide for contributing in the NativeScript modules ](https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md)repository

**Comment by anki247** [comment]
@JillevdW any progress here?

**Comment by JillevdW** [comment]
@anki247 I have fixed this by implementing Nick’s suggestion dor the time being. I’ve looked into using the ‘sizeToFit()’ function on iOS but hit a wall there.
