### ISSUE TITLE
AppSettings set/get changes value on Android

### ISSUE THREAD

**Issue by dlcole** [NativeScript/NativeScript#6039]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes, and I opened a thread on the NativeScript forum.  See https://discourse.nativescript.org/t/wtf-appsettings-getnumber-returns-different-value-then-set-by-setnumber/6705/4

### Tell us about the problem
I saved a date value via appSettings and later retrieved it.  On Android, the retrieved value differs from the original value. On iOS, they are identical, as expected. 

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.1
- Cross-platform modules: 4.1.0
- Runtime(s): Android: 4.1.3
- Plugin(s): n/a

### Please tell us how to recreate the issue in as much detail as possible.
See the playground at https://play.nativescript.org/?template=play-js&id=ZLB5UJ&v=8

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

This code is sufficient: 

```
var currentTime = new Date();  // create date object
console.log(currentTime.toISOString()); // display as formatted date
var currentTimeVal = currentTime.getTime(); // get date in milliseconds
console.log("currentTimeVal: " + currentTimeVal);
appSettings.setNumber("currentTimeVal", currentTimeVal); // save date in milliseconds

var newTimeVal = appSettings.getNumber("currentTimeVal", 0); // retrieve date in milliseconds
console.log("newTimeVal: " + newTimeVal);

var newTime = new Date(newTimeVal); // create date object from retrieved value
console.log(newTime.toISOString()); // display as formatted date]

```

**Comment by NathanaelA** [comment]
Well, if I had a guess -- On Android the  number is cast into a [Java Float](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/application-settings/application-settings.android.ts#L67) before it is saved and then retrieved as a [Java Float](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/application-settings/application-settings.android.ts#L41) and then cast into a JS number.   Unfortunately Floating point numbers are notoriously known for being just an number **approximation**.   

I bet if you changed the example to this, it would work:
```
var currentTime = new Date();  // create date object
console.log(currentTime.toISOString()); // display as formatted date
var currentTimeVal = currentTime.getTime(); // get date in milliseconds
console.log("currentTimeVal: " + currentTimeVal);
appSettings.setString("currentTimeVal", currentTimeVal); // save date in milliseconds

var newTimeVal = parseInt(appSettings.getString("currentTimeVal", 0),10); // retrieve date in milliseconds
console.log("newTimeVal: " + newTimeVal);

var newTime = new Date(newTimeVal); // create date object from retrieved value
console.log(newTime.toISOString()); // display as formatted date]

**Comment by dlcole** [comment]
@NathanaelA I expect you're right, and I modified my code to see if the time stamps are reasonably close rather than equal.  Saving and retrieving the integer time value as a string is also a viable alternative.  Thanks for the reply!

**Comment by tsonevn** [comment]
Hi @dlcole,
Does the suggestion provided by @NathanaelA solve the issue on your side?

**Comment by dlcole** [comment]
@tsonevn - yes, it does.  It might be good to mention in the docs that AppSettings numbers are stored as floats and that large numbers, such as getTime() values, may be approximate.

**Comment by dlcole** [comment]
Closing issue based on above discussion, but recommend doc update.
