### ISSUE TITLE
Z-index not working on views except of Button

### ISSUE THREAD

**Issue by Tyg-g** [NativeScript/NativeScript#6040]
Platform: Android

Setting the z-index CSS property has effect only on Button view, nothing else. There are no shadows. However, the [UI: Styling: Supported CSS Properties](https://docs.nativescript.org/ui/styling#supported-css-properties) article does not mention any support details.

I created a simple sample: https://play.nativescript.org/?template=play-js&id=VJs4JT&v=16

![screenshot_20180707-100219](https://user-images.githubusercontent.com/40174710/42408922-bee66ef8-81d2-11e8-916d-082db75f87d0.png)

**Comment by tsonevn** [comment]
Hi @Tyg-g,
I tested the Z-Index property on my side on Android, and everything seems to work as expected. I made a sample project. You can check it [here](https://play.nativescript.org/?template=play-js&id=VJs4JT&v=17). You will see that the object with higher z-index will be displayed on the top and the other element will be shown behind him while following the order.

Also if the case is different, please provide more info about the problem.

**Comment by Tyg-g** [comment]
The order is ok. But what about shadows? The button has shadow, the other elements does not.

**Comment by tsonevn** [comment]
Hi @Tyg-g,
Setting up the shadow for the component is a missing feature. You can keep track on [this](https://github.com/NativeScript/NativeScript/issues/550) issue, where this feature is already logged.
