### ISSUE TITLE
Using NGXLogger

### ISSUE THREAD

**Issue by iMarwan-k** [NativeScript/NativeScript#6045]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
I'm using NGXLogger for logging with web but it doesn't build for mobile

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
     4.0.0
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
    4.0.1
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
    4.0.1
- Plugin(s): (look for the version number in the `package.json` file of your
project)
"dependencies": {
    "@angular/animations": "6.0.5",
    "@angular/common": "6.0.5",
    "@angular/compiler": "6.0.5",
    "@angular/core": "6.0.5",
    "@angular/forms": "6.0.5",
    "@angular/http": "6.0.5",
    "@angular/platform-browser": "6.0.5",
    "@angular/platform-browser-dynamic": "6.0.5",
    "@angular/router": "6.0.5",
    "core-js": "2.5.7",
    "font-awesome": "4.7.0",
    "nativescript-angular": "6.0.0",
    "nativescript-grid-view": "^4.0.0",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-theme-core": "1.0.4",
    "primeng": "5.2.7",
    "reflect-metadata": "0.1.12",
    "rxjs": "6.2.1",
    "tns-core-modules": "4.0.1",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.7.0-beta.0",
    "@angular-devkit/core": "0.7.0-beta.0",
    "@angular/cli": "6.1.0-beta.0",
    "@angular/compiler-cli": "6.0.5",
    "@angular/language-service": "6.0.5",
    "@ngtools/webpack": "6.1.0-beta.0",
    "@types/jasmine": "2.8.8",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "8.9.5",
    "clean-webpack-plugin": "0.1.19",
    "codelyzer": "4.2.1",
    "copy-webpack-plugin": "4.5.1",
    "css-loader": "0.28.11",
    "extract-text-webpack-plugin": "3.0.2",
    "jasmine-core": "2.99.1",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage-istanbul-reporter": "2.0.1",
    "karma-jasmine": "1.1.2",
    "karma-jasmine-html-reporter": "0.2.2",
    "nativescript-dev-typescript": "0.7.1",
    "nativescript-dev-webpack": "0.13.0",
    "nativescript-worker-loader": "0.9.1",
    "tns-platform-declarations": "^4.0.0",
    "protractor": "5.3.2",
    "raw-loader": "0.5.1",
    "resolve-url-loader": "2.3.0",
    "ts-node": "5.0.1",
    "tslint": "5.9.1",
    "typescript": "2.7.2",
    "uglifyjs-webpack-plugin": "1.2.5",
    "webpack": "4.6.0",
    "webpack-bundle-analyzer": "2.13.1",
    "webpack-cli": "2.1.5",
    "webpack-sources": "1.1.0",
    "ngx-logger": "3.0.4"
  }

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

install the lib from https://github.com/dbfannin/ngx-logger#readme

import the library
import {NGXLogger} from "ngx-logger";

`constructor(private logger:NGXLogger) {
    }`

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

how can I use the lib with both platforms (mobile and web)?

Thanks

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1420
