### ISSUE TITLE
There is no logout capability

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#6050]
_From @alexziskind1 on January 20, 2018 2:36_

Logging out is pretty fundamental to an authenticated app. There should be a way to log out.
Thanks.

_Copied from original issue: NativeScript/template-patient-care-ng#15_

**Comment by tsonevn** [comment]
_From @manoldonev on January 22, 2018 12:18_

Kinvey SDK provides support for logging out the authenticated user:

``` ts
import { Kinvey } from "kinvey-nativescript-sdk";

// ...

Kinvey.User.logout();
```

We will also consider how to extend the app design to incorporate this functionality out-of-the-box for one of the future versions of the app template.

**Comment by NathanWalker** [comment]
n/a to core but if still desired can be transferred to https://github.com/rosen-vladimirov/template-enterprise-auth-ng with Rosen approval.
