### ISSUE TITLE
ActionBar color iOS - application terminated

### ISSUE THREAD

**Issue by fthuin** [NativeScript/NativeScript#6057]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

There is [this on stackoverflow](https://stackoverflow.com/questions/51099787/nativescript-ui-listview-throws-error-typeerror-undefined-is-not-an-object-eva) but no answer.

### Tell us about the problem

```
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10510f649 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x105137c5b NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x105a2d5c1 ffi_closure_unix64_inner
4   0x105a2df22 ffi_closure_unix64
5   0x1069005cf -[UIViewController __viewWillAppear:]
6   0x10692bcfc -[UINavigationController _startCustomTransition:]
7   0x106942582 -[UINavigationController _startDeferredTransitionIfNeeded:]
8   0x10694386c -[UINavigationController __viewWillLayoutSubviews]
9   0x106b9bd0b -[UILayoutContainerView layoutSubviews]
10  0x1068257a8 -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
11  0x10ab58456 -[CALayer layoutSublayers]
12  0x10ab5c667 CA::Layer::layout_if_needed(CA::Transaction*)
13  0x10aae30fb CA::Context::commit_transaction(CA::Transaction*)
14  0x10ab1079c CA::Transaction::commit()
15  0x10ab1151a CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
16  0x10a56c607 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
17  0x10a56c55e __CFRunLoopDoObservers
18  0x10a550b81 __CFRunLoopRun
19  0x10a55030b CFRunLoopRunSpecific
20  0x10d6fca73 GSEventRunModal
21  0x106756057 UIApplicationMain
22  0x105a2dd7d ffi_call_unix64
23  0x130db76b0
JavaScript stack trace:
1   @file:///app/tns_modules/tns-core-modules/ui/action-bar/action-bar.js:328:19
2   applyAllNativeSetters@file:///app/tns_modules/tns-core-modules/ui/core/properties/properties.js:977:37
3   initNativeView@file:///app/tns_modules/tns-core-modules/ui/core/properties/properties.js:904:30
4   onResumeNativeUpdates@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:627:36
5   _resumeNativeUpdates@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:272:39
6   onLoaded@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:231:34
7   @file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:311:98
8   callFunctionWithSuper@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:304:13
9   callLoaded@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:311:35
10  loadView@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:439:28
11  @file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:233:27
12  eachChildView@file:///app/tns_modules/tns-core-modules/ui/page/page-common.js:122:21
13  eachChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:868:27
14  onLoaded@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:232:23
15  onLoaded@file:///app/tns_modules/tns-core-modules/ui/page/page.js:198:39
16  @file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:311:98
17  callFunctionWithSuper@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:304:13
18  callLoaded@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:311:35
19  loadView@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:439:28
20  @file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:233:27
21  eachChildView@file:///app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:34
22  eachChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:868:27
23  onLoaded@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:232:23
24  @file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:311:98
25  callFunctionWithSuper@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:304:13
26  callLoaded@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:311:35
27  loadView@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:439:28
28  @file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:233:27
29  eachChildView@file:///app/tns_modules/tns-core-modules/ui/content-view/content-view.js:70:21
30  eachChildView@file:///app/tns_modules/tns-core-modules/ui/page/page-common.js:120:44
31  eachChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:868:27
32  onLoaded@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:232:23
33  onLoaded@file:///app/tns_modules/tns-core-modules/ui/page/page.js:198:39
34  @file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:311:98
35  callFunctionWithSuper@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:304:13
36  callLoaded@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:311:35
37  loadView@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:439:28
38  _addViewCore@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:434:26
39  _addView@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:420:26
40  viewWillAppear@file:///app/tns_modules/tns-core-modules/ui/page/page.js:69:31
41  UIApplicationMain@[native code]
42  start@file:///app/tns_modules/tns-core-modules/application/application.js:264:26
43  run@file:///app/tns_modules/tns-core-modules/application/application.js:284:10
44  bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:157:26
45  bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:91:38
46  bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:80:26
47  anonymous@file:///app/main.js:11:57
48  evaluate@[native code]
49  moduleEvaluation@[native code]
50  @[native code]
51  promiseReactionJob@[native code]
JavaScript error:
file:///app/tns_modules/tns-core-modules/ui/action-bar/action-bar.js:328:19: JS ERROR TypeError: undefined is not an object (evaluating 'navBar.tintColor = color.ios')
```

### Which platform(s) does your issue occur on?
iOS only

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.2
- Cross-platform modules: 4.1.0
- Runtime(s): 4.1.1

### Please tell us how to recreate the issue in as much detail as possible.

Put this in a sass file 
```
ActionBar {
    text-align: center;
    horizontal-align: center;
    color: white;
}
```

**Comment by tsonevn** [comment]
Hi @fthuin,
 I tested your case in a sample project while using `tns-template-tab-navigation-ts` template, however, I was unable to recreate this problem. I am attaching the sample. Can you review it and make the needed changes, which will help in recreating the issue.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/2187235/Archive.zip)

**Comment by fthuin** [comment]
It looks like there was an underlying problem in my code, I fixed it after removing the css color, and put back the css color property, everything is fine now.

I close this issue until I'm not even able to reproduce it anymore.

**Comment by fthuin** [comment]
@tsonevn So I had it again today. In Angular, if you put your component template inside a `<Page>...</Page>` and you have a color on your ActionBar, once you navigate to it you'll have the error shown in the issue instead of saying "Hey you can't put that inside a Page". Not really an issue from NativeScript in my point of view, it's just that the error is a bit misleading.

**Comment by weijyewang** [comment]
@fthuin i got the same error, i tried not to apply any css to the` <ActionBar></ActionBar>` but to no avail. How did you resolve it?

**Comment by tsonevn** [comment]
Hi all 
@fthuin You can open a new feature request, where you can describe your suggestions about improving the error logs.
@weijyewang make sure that you are using latest NativeScript 5.0 on your side. You can also check our upgrade instruction [here](https://docs.nativescript.org/releases/upgrade-instructions)

**Comment by weijyewang** [comment]
@tsonevn  I'm already on Nativescript 5 when facing this problem.

<img width="440" alt="screenshot 2018-11-27 at 12 45 01 pm" src="https://user-images.githubusercontent.com/8890603/49059128-573a4500-f242-11e8-94f1-b017e5f2e516.png">
![screenshot 2018-11-27 at 12 45 23 pm](https://user-images.githubusercontent.com/8890603/49059129-57d2db80-f242-11e8-92d3-beb6ccb8c5d9.png)

**Comment by tsonevn** [comment]
@weijyewang  Can you provide a sample project, which demonstrates the issue, you are facing?

**Comment by HughEdwards1** [comment]
I'm having this issue with nativescript angular.      
I've moved any ActionBar's out of <Page> elements, and even tried removing all CSS styles entirely.

`JavaScript stack trace:
setColor(file:///node_modules/tns-core-modules/ui/action-bar/action-bar.js:279:0)
at file:///node_modules/tns-core-modules/ui/action-bar/action-bar.js:367:0
at applyAllNativeSetters(file:///node_modules/tns-core-modules/ui/core/properties/properties.js:1063:0)
at initNativeView(file:///node_modules/tns-core-modules/ui/core/properties/properties.js:990:0)
at onResumeNativeUpdates(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:628:0)
at _resumeNativeUpdates(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:273:0)
at onLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:232:0)
at file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:75
at callFunctionWithSuper(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:305:0)
at callLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:0)
at loadView(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:440:0)
at file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:234:0
at eachChildView(file:///node_modules/tns-core-modules/ui/page/page-common.js:128:0)
at eachChild(file:///node_modules/tns-core-modules/ui/core/view/view-common.js:1010:0)
at onLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:233:0)
at onLoaded(file:///node_modules/tns-core-modules/ui/page/page.js:238:0)
at file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:75
at callFunctionWithSuper(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:305:0)
at callLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:0)
at loadView(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:440:0)
at file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:234:0
at eachChildView(file:///app/vendor.js:1469<…>
JavaScript error:
file:///node_modules/tns-core-modules/ui/action-bar/action-bar.js:279:0: JS ERROR TypeError: undefined is not an object (evaluating 'navBar.titleTextAttributes = (_a = {}, _a[NSForegroundColorAttributeName] = color.ios, _a)')`

App just crashes on launch and is completely unusable (on ios).

**Comment by lukkystunt** [comment]
can you share the section of the code that is causing the issue?

**Comment by HughEdwards1** [comment]
I'm not sure what's causing the issue - since I don't call that code anywhere

**Comment by HughEdwards1** [comment]
Maybe it's something to do with the title text and the colour is misleading me....
Will do a quick investigation

**Comment by HughEdwards1** [comment]
CSS which would alter ActionBar (I'm using {N} angular but this issue seemed relevant).    
```
ActionBar, Page, RadList {
    background-color: #3E556A;
    color: white;
}
```

I've tried removing this completely for the action bar style, no change.

All my action bars:   
```
<ActionBar title="{{ theTime| momentDateString }}" flat="true">
    <NavigationButton text="Go Back" icon="res://baseline_arrow_back_white_24" (tap)="goBack()"></NavigationButton> 
</ActionBar>
<Page>
```
```
<ActionBar title="Newly Added" flat="true">
    <ActionItem 
        (tap)="newlyAddedClicked()"
        icon="res://baseline_new_releases_white_24"
        ios.position="right"
        android.position="actionBar"
    >
    </ActionItem>
</ActionBar>
<Page>
```

Moved the action bar elements outside of pages from the above comments suggesting that was a poor hierarchy.

**Comment by lukkystunt** [comment]
does the application work when you comment out the actionbar

**Comment by HughEdwards1** [comment]
Same error with all action bars commented out.    
Commented css also, same error.

I'll be able to do some more debugging in the morning.

**Comment by lukkystunt** [comment]
You can delete your apps ios platform `tns platform clean ios`  then rebuild.

**Comment by HughEdwards1** [comment]
Same error unfortunately, even with every action bar related item commented out.

**Comment by HughEdwards1** [comment]
Managed to make some progress thanks to Eduardo over on slack.     
Noticed that the <Page> components were irrelevant under angular.    
Removing them caused a new error, which was relating to the icon `res://` I was using which either wasn't sent or isn't supported over the playground app. 

Got a bit more styling work to be done but it seems solved.

Cheers :)
