### ISSUE TITLE
ActionBar documentation confusing links

### ISSUE THREAD

**Issue by endymion00** [NativeScript/NativeScript#6058]
On nativescript website current ActionBar documentation for nativescript core is poorly detailed.
Path is NativeScript Core->USER INTERFACE->UI Widgets->ActionBar
(https://docs.nativescript.org/ui/ns-ui-widgets/action-bar)

But as I see by searching using google that there is a more complete page located at:
https://docs.nativescript.org/ui/action-bar which theorically is under "UI Widgets" but I'm not able to land there if coming from nativescript website and by following the sections.

Please update the documentation for ActionBar it is very confusing for users (and also time consuming).Official documentation website should be easier to use.
Thanks!

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/docs#1256
