### ISSUE TITLE
Android - Dynamic Link - After first installation

### ISSUE THREAD

**Issue by shabib3** [NativeScript/NativeScript#6060]
Hi guys,

Hi,

I am working on dynamic links with @EddyVerbruggen 's firebase plugin - I posted there but without any response so maybe you guys here can help me out :)

Everything works great until it comes to scenario where user doesn't have the app.
For iOS we get fully working solution, but on android when
the user clicks the dynamic link and get him on Play Store to install the app, there we have a problem.
The issue starts when it come to open the app after first installation. It looks like the app doesn't get the deep link after the installation.
The only way that I get the deep link after the first installation is if the user stays on the app page in the Play Store, wait there to the installation to end and then click 'Continue' (The 'Continue' button show that it knows that it came from a dynamic link rather it would put 'Open' instead of 'Continue'), also I can get it to work if the user clicks the 'App successfully installed, Press to Continue' Play Store notification at the notification tray.
But the thing is that cannot trust on the user to open the app from these sources (Play Store/Notification tray). Probably the average user clicks install and get out of the Play Store page and when the app finish the installation he opens it from the Application dashboard.

Any idea how can I pass the deep link after the first installation no matter from where the user open it?

Thinks I tried:

Use onResumed and onLaunched event to get the DataString from the intent...I was able to get the deep link there but not at the first launch after the installation when I opened it from the launcher.
Change for the various android:launchMode options.

it may help - I also wrote this issue to firebase support and this is the response that I got:
```
Hi there,

This is Patricia from Firebase Support and I'm glad to assist you with your issue in Firebase Dynamic Links.

The reason why your app wasn't able to retrieve the deep link after opening it via the launcher/application dashboard instead of the Play Store post-installation is because it breaks our installation flow mentioned in our flowchart. You'll need to make sure that your intent also includes a launcher intent in order to support your use-case. We'll work on including this information in our public documentation, however, as of now, we are yet to find out an estimated date for this.

Let me know if there's anything else that I can assist you with. 

Regards
Patricia
```

also saw (it may help):
- [Official Firebase Documentation About this subject](https://firebase.google.com/docs/dynamic-links/android/receive) - reach out to `Handling deep links` section - is there a way to get access to the following in nativescript:
<img width="861" alt="screen shot 2018-07-13 at 1 35 09" src="https://user-images.githubusercontent.com/27296296/42663153-12be64c2-863d-11e8-9c78-13ea97c59d7e.png">

- [this Medium post](https://medium.com/exploring-android/exploring-firebase-on-android-dynamic-links-7364def74808) about the subject...reach out to `Handling deep links` section.

I think the thing is to know I to extract the data and from which actual intent...I am not so much of an native android developer, so I am little lack of experience...

Will appreciate any help! :)

Thanks a lot! :)

**Comment by tsonevn** [comment]
This issue was moved to EddyVerbruggen/nativescript-plugin-firebase#819
