### ISSUE TITLE
Background color set doesn't works when also changing Button text in a ListView

### ISSUE THREAD

**Issue by drmistral** [NativeScript/NativeScript#6061]
I need a 2-states toggle Button: each tap changes the background color **and** its text label (color and text). It works correctly when the button belongs to a simple page.
Instead, when the button is put as element of a simple list (20 elements) it does not change its background color, and only its label text changes. **This problem arises in iOS** while it works on Android. Same problem with the border as well.

Here is the playground demo https://play.nativescript.org/?template=play-js&id=Hms4zb&v=2

**Comment by tsonevn** [comment]
HI @drmistral,
In iOS, you should [refresh](https://docs.nativescript.org/api-reference/classes/_ui_list_view_.listview#refresh) the whole listview component when making similar changes to the child elements. However the recommended way to achieve the needed functionality is to use the view model and to bind the needed properties in the XML(e.g. in your case those properties are `text`, `color`, `backgroundColor`). For your convenience, I am attaching a [sample](https://play.nativescript.org/?template=play-js&id=Hms4zb&v=3) project.

**Comment by drmistral** [comment]
Hi @tsonevn, thanks for your support.

About first point, I can see the refresh method defined in my ListView but a call to it produces un "undefined", can't understand why. Anyway even if it worked I don't want to reload the list because in the real case is infinite-scroll based feed of content and that would be disruptive for UX (see row 50 of [home-page.js](https://play.nativescript.org/?template=play-js&id=Hms4zb&v=6).

Second workaround: is difficult to apply in my real case, actually the button is a custom component with its logic that controls both function and style. This logic is completely unknown at the caller context where I wave a simple call like:

`<FollowButton:FollowButton entityId="{{ itemId }}" entityType="customer" value="{{ followed }}" />`

Moreover, actually the change of button style is controlled just applying different css classes, defined in the component, from the javascript (and the problem is the same).

**Comment by drmistral** [comment]
Hi @tsonevn, thanks for your support.

About first point, I can see the refresh method defined in my ListView but a call to it produces un "undefined", can't understand why. Anyway even if it worked I don't want to reload the list because in the real case is infinite-scroll based feed of content and that would be disruptive for UX (see row 50 of [home-page.js](https://play.nativescript.org/?template=play-js&id=Hms4zb&v=6).

Second workaround: in my real case, the button is present in many places (pages, list items etc.), actually it is a custom component (full-js, extending Button) embedding its own logic to control both its function and style. This logic is completely unknown at the caller context where I wave a simple call like:

`<FollowButton:FollowButton entityId="{{ itemId }}" entityType="customer" value="{{ followed }}" />`

So would avoid to expose parameters about its style. A the moment the changes of button style are controlled just applying different css classes, defined in the component, from javascript side (and the problem is the same).

**Comment by tsonevn** [comment]
HI @drmistral,
I am glad to hear that you were able to solve your problem.  I also notice that this issue is already logged [here](https://github.com/NativeScript/nativescript-angular/issues/377). I would suggest keeping the discussion in the other issue and to close this one in favour of the issue [#377].(https://github.com/NativeScript/nativescript-angular/issues/377).
