### ISSUE TITLE
IOS - Cannot Use <Span/>

### ISSUE THREAD

**Issue by George0112** [NativeScript/NativeScript#6062]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
**Yes**

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) 4.1.0
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) 4.1.0
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project) 
    - "tns-ios": {
                        "version": "4.1.0"
                },
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
I'm working on an app and I use <Span/> in one of my components. However, when I route to any page used that component. The app crash immediately with the following error.
```
JavaScript stack trace:
1   @file:///app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:134:31
2   eachChildView@file:///app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:34
3   eachLayoutChild@file:///app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:133:27
4   onMeasure@file:///app/tns_modules/tns-core-modules/ui/layouts/stack-layout/stack-layout.js:49:29
5   measure@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:54:27
6   measureChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:815:26
7   onMeasure@file:///app/tns_modules/tns-core-modules/ui/page/page.js:232:53
8   measure@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:54:27
9   measureChild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:815:26
10  layoutView@file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:590:26
11  viewDidLayoutSubviews@file:///app/tns_modules/tns-core-modules/ui/page/page.js:154:34
12  UIApplicationMain@[native code]
13  start@file:///app/tns_modules/tns-core-modules/application/application.js:264:26
14  @file:///app/tns_modules/nativescript-vue/dist/index.js:12826:22
15  initializePromise@[native code]
16  Promise@[native code]
17  $navigateTo@file:///app/tns_modules/nativescript-vue/dist/index.js:12795:25
18  $start@file:///app/tns_modules/nativescript-vue/dist/index.js:12990:29
19  anonymous@file:///app/main.js:65:10
20  evaluate@[native code]
21  moduleEvaluation@[native code]
22  @[native code]
23  promiseReactionJob@[native code]
JavaScript error:
file:///app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:134:31: JS ERROR TypeError: undefined is not a function (near '...cv._eachLayoutView...')
``` 
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 
[playground](https://play.nativescript.org/?template=play-vue&id=AL9iYD&v=2)

I have tried removing node-modules, update tns, update node.js, and nothing change.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

I can recreate this issue if I use something like. `<Span text="Category : \n"/>`

**Comment by tsonevn** [comment]
HI @George0112,
For using a `<Span>` in NativeSciprt, you should use `FormattedString` and set it up e.g. in a `Label` or `TextField`. Check [this](https://docs.nativescript.org/ui/ns-ui-widgets/formatted-string#formatted-string) example from docs.
