### ISSUE TITLE
[template-enterprise-auth-ng] Android: Configure keyboard to push the login fields up

### ISSUE THREAD

**Issue by zbranzov** [NativeScript/NativeScript#6065]
Currently when the login screen opens the keyboard goes over the fields and it's hard to fill them. Expected behaviour is the keyboard to push the fields up. If possible, provide a solution that affects only the mentioned screen and not the whole app.

**Comment by euller88** [comment]
Can't the developer just do this in their AndroidManifest.xml: 
``` xml
<activity
    ...
    android:windowSoftInputMode="adjustResize"
    ...

```
It's fast and easy.

**Comment by NathanWalker** [comment]
n/a

**Comment by euller88** [comment]
> Can't the developer just do this in their AndroidManifest.xml:
> 
> ```
> <activity
>     ...
>     android:windowSoftInputMode="adjustResize"
>     ...
> ```
> 
> It's fast and easy.

Wow reading back this comment made me realize that I was in a pretty bad state of mind that time. This rudeness was uncalled for, and I apologize to the development for doing it.
