### ISSUE TITLE
Cannot find module "tns-core-modules/application"

### ISSUE THREAD

**Issue by Kamieniu** [NativeScript/NativeScript#6068]
MacOS HighSierra 10.13.3
Node 9.6.1
NPM 6.1.0

### Tell us about the problem
I try to run `npm run ios` on my Angular + NativeScript project. Project is CLEAN! 
I used `ng new app` and `ng add @nativescript/schematics`

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) `4.1.2`
- Cross-platform modules: (check the 'version' attribute in the 
`node_modules/tns-core-modules/package.json` file in your project) `4.1.0`
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the 
`package.json` file of your project) tns-ios `4.1.1`
 
- Plugin(s): (look for the version number in the `package.json` file of your
project) `0.0.0`

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

`ng new angular-app`
`cd angular-app`
`ng add @nativescript/schematics`
`npm run ios`

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

There are plenty of errors.

This one occured at the end.

`JavaScript error:
file:///app/vendor.js:55195:167: JS ERROR Error: Cannot find module "tns-core-modules/application"`

.. but this kind of error occured multiple times with defferent 'Can't resolve' file.

`ERROR in ../node_modules/tns-core-modules/bundle-entry-points.js
Module not found: Error: Can't resolve 'ui/segmented-bar' in '/Users/franciszekstodulski/Develop/native-app/node_modules/tns-core-modules'
 @ ../node_modules/tns-core-modules/bundle-entry-points.js 29:67-94
 @ ./main.ns.ts`

**Comment by erkanarslan** [comment]
How do you try to import application package?

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-schematics#37
