### ISSUE TITLE
problem on reading an entity object value

### ISSUE THREAD

**Issue by vick16ach** [NativeScript/NativeScript#6070]
i know no one will answer this post but still i'm trying.....

for more details visit:
https://discourse.nativescript.org/t/simple-but-useful-problem-of-context/6854/5?u=vikasacharya

when i run this on loaded …

```
viewModel.selectedContactForEstimate = function(){

    console.log("inside select...");
    var context = page.navigationContext;
    console.log(context);
    viewModel.set("contactList",context);

};
```
i ll get these things in console

  inside select...
{
“_id”: “5b446166b80d61190432d879”,
“title”: "Mrs. ",
“selectedTitleIndex”: 1,
“firstname”: “Sakshi”,
“phone”: “8976755948”,
“lastname”: “Shivanand”,
“email”: “da jauajajb@gmail.com”,
“gstn”: “Dbsj46”,
“adl1”: "Bangalore ",
“state”: “Karnataka”,
“city”: “Bangalore”,
“adl2”: “Bangalore”,
“selectedStateIndex”: 10,
“pincode”: “569040”,
“imageRefId”: “”,
“_acl”: {
“creator”: “5b31c86a755ccb4b137a35be”
}
}

but when i try to print only one value like

              console.log(context.firstname); 
          or console.log(context['firstname']); 
          or console.log(context[1]);

im getting error “cannot read property firstname of undefined” why i dont know please clarify this simple issue

so context is not an array please tell me what is it. and how to access its elements.
no where in document or here i found a solution. if there is an existing thread please give link of that…

i have also recreated this problem and posted on above link. just copy paste the code it will work fine. do please give a solution for this problem

    viewModel.set("contactList",context);
}

**Comment by tsonevn** [comment]
Hi @vick16ach,
I tested your case, however, was unable to recreate an issue with the setting up the binding context of the project and with accessing the properties. For your convenience I am attaching sample project, you can review it [here](https://play.nativescript.org/?template=play-js&id=zXUCfi&v=2). While creating the sample project, I notice that the JavaScript marked the used quotation marks in your code as invalid characters. I will suggest replacing all the quotation marks with `"`.

Also regarding your case, you can also use our StackOverflow thread [here](https://stackoverflow.com/questions/tagged/nativescript), when you have a question.
