### ISSUE TITLE
Documentation Clarification

### ISSUE THREAD

**Issue by charsleysa** [NativeScript/NativeScript#6071]
### Tell us about the problem
Apologies if this has already been answered but I haven't been able to get a clear answer from searching GitHub issues / StackOverflow / NativeScript discourse / the entire internet.

I am using Typescript with NativeScript and have noticed that in many examples the `tsconfig.json` file has the lib option array set to `["es6" ,"dom"]`.

Is it correct to think that this is a mistake and that all the API's (e.g. `URL` class) usually available in a browser setting are _NOT_ available in NativeScript? (In essence, the lib option array should be set to `["es6"]`).

At first I thought the API's might be available but undocumented until I noticed that `XHR` and `Fetch` are shimmed in the `tns-core-modules` and registered globally on startup.

Any help would be much appreciated.

Cheers!

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/docs#1257
