### ISSUE TITLE
unhandledRejection

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/NativeScript#6073]
How do we catch unhandledRejection in Nativescript?
As there is no ```process``` we need a way to do that 

Thanks

**Comment by NickIliev** [comment]
@farfromrefug currently the `PromiseRejectionEvent` is not supported.

Here is [an actual example](https://github.com/NativeScript/NativeScript/blob/bcadcbe7b5761a0f6aea1b6252ea8af44bee1ca1/tns-core-modules/ui/animation/keyframe-animation.ts#L246-L253) of how you could process the unhandled rejection warnings
