### ISSUE TITLE
Navigation is blinking both in IOS and Android.

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/NativeScript#6081]
New empty project  `tns create aaa --ng` ( angular 6 , 4.1.2)

Let's set some dark colors to see the blinking : 

 **Items.component.html** 

 
 
![image](https://user-images.githubusercontent.com/2842123/42818512-c15e14ec-89d9-11e8-8155-be0018c92a3e.png)

**items-detail.component.html**

![image](https://user-images.githubusercontent.com/2842123/42818494-b755e650-89d9-11e8-9245-adea43678b91.png)

Now let's see this in action :  **Notice the blinking**.

 ![image](https://i.imgur.com/9PRhjfL.gif)
 

Currently we use a dark app and it's **very** problematic.

-------

No additional code was added.
It happens also in a real device ( tested galaxy s8).
Also happens in IOS.

Project attached ( it can be reproduce by `tns create aaa --ng`) but still  - I've attached.:  https://ufile.io/ht6yv

**Comment by NickIliev** [comment]
@RoyiNamir the initial page (`app.component.html` where page-router-outlet is created) has by default a white background color. In the same time, the default page transition for `nsRouterLink` is `fade`. Thus when navigation the fade effect is showing the "whiteness" for a split of a second.

I am thinking of two possible approaches to overcome this issue.
- Option 1: Remove the page transitions if they are not used. 
For example: in the place where the navigation is triggered
```HTML
<Label [nsRouterLink]="['/item', item.id]" pageTransition="none" [text]="item.name" ></Label>
```

- Option 2: Create a  background "scene" behind the `page-router-outlet` ('Frame' in NativeScript Core)
For example:
_app.component.html_
```HTML
<GridLayout backgroundColor="black">
    <page-router-outlet></page-router-outlet>
</GridLayout>
```

**Comment by RoyiNamir** [comment]
Oh. It wasn't  in prev versions .thought it's a bug.
Thanks Nick

**Comment by RoyiNamir** [comment]
@NickIliev But what about code navigation ? 
```
this.routerExtensions.navigate(routes, {
                    transition
                }); 
```

I've tried with 

```
 let transition = {
                  name: "none", duration: 0, curve: "linear"
            };
```

But it still blinks. 
Not all navigation in our app is nsRouterLink. some are via  `routerExtensions`
