### ISSUE TITLE
platform.device.language value caching

### ISSUE THREAD

**Issue by webleaf** [NativeScript/NativeScript#6082]
If user change system language, `platform.device.language`, value updates only after app restart.
But if I want check this value onResume event, I have to use `java.util.Locale.getDefault().getLanguage()`. And thus create own cross-platform wrapper for this purpose. So presence of `platform.device.language` loses its meaning.
I think whether to cache this value or not, should be taken at the application level (NS should not cache it).
Perhaps the same applies to `platform.device.region`.

**Comment by tsonevn** [comment]
Hi @webleaf,
Thank you for the provided suggestion. 
I tested your case and indeed the `platform.device.language` will return the initial value, while the app comes from the suspend mode and the language is changed.
Regarding that this behaviour seems to be related to a missing feature. Any PR that provides functionality for handling the language change will be highly appreciated. You can review our [contributing guidelines](https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md).

**Comment by StekloKRG999** [comment]
#6082
