### ISSUE TITLE
Listview tap event does not expose item index

### ISSUE THREAD

**Issue by endymion00** [NativeScript/NativeScript#6085]
I'm using vanilla Js and just wanted to get the index of a listitem when the tap event occur but its value is "index" instead of a number.ç

### Which platform(s) does your issue occur on?
Tested on Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.3
- Cross-platform modules: 3.4.1
- Runtime(s): 3.4.1

### Please tell us how to recreate the issue in as much detail as possible.

Use a listview with a array of objects as items and assign a function for handling the tap event.
Test it by taping on one of the list items and try to get the index value.
As a result index is null.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

page.xml
```
....
        <ListView id="inspectionItemsList" items="{{ inspection.inspection_items }}"  tap="testTap">
            <ListView.itemTemplate>
                <StackLayout>
                    <GridLayout id=columns="150, *, 100" rows="auto" >
                        <Label row="0" col="0" text="{{ code  }}" className="fa data-field-label" />
                    </GridLayout>
                </StackLayout>
            </ListView.itemTemplate>
        </ListView>

```
page.js

```
function onPageLoaded(args) {
  const page = args.object;
 const inspectionViewModel = createInspectionModel();
// inspectionViewModel is like this { inspection: { inspection_items = [ { code: 'a code1', status: a status1'}, { code: 'a code2', status: a status2'}] } }
 page.bindingContext = inspectionViewModel; 
}


function testTap(args){
  console.log('test tap');
  console.log('selected index', args.index); // ---> args.index is undefined   
}
exports.testTap = testTap;
exports.onPageLoaded = onPageLoaded;
```

**Comment by tsonevn** [comment]
Hi @endymion00,
In this scenario, you should use ListView's `itemTap` event instead of `tap`. For further help, you can check the [documentation](https://docs.nativescript.org/ui/ns-ui-widgets/list-view#basics).
