### ISSUE TITLE
Expose NativeScript runtime version to JavaScript

### ISSUE THREAD

**Issue by ligaz** [NativeScript/NativeScript#609]
It will be good (mainly for debugging purposes) to have a way to access the NativeScript runtime version from JavaScript.

**Comment by ligaz** [comment]
See [here](https://github.com/NativeScript/ios-runtime/issues/123) for iOS implementation.

**Comment by slavchev** [comment]
Do you need "NativeScript" version only or something more detailed like [`process.versions`] (https://nodejs.org/api/process.html#process_process_version) in `nodejs`?

**Comment by ligaz** [comment]
Let's start with `version` and expand later upon demand.

**Comment by NathanaelA** [comment]
Here is the Android request I did a month before you did.  :grinning: 
https://github.com/NativeScript/android-runtime/issues/93

**Comment by enchev** [comment]
`__runtimeVersion` can be used now with both ios and android runtimes.
