### ISSUE TITLE
Disable swipe back  using enableSwipeBackNavigation  doesn't work

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#6091]
_From @RoyiNamir on July 18, 2018 20:57_

I've created a new simple plain empty project : 

`tns create aaa --ng`

In the ctor of the items component , I did exactly what [this post suggests](https://discourse.nativescript.org/t/disabling-swipe-gestures-in-ios-preventing-navigation-back/3169/3)

```
constructor(private page: Page) {
        this.page.enableSwipeBackNavigation = false;
}
```

But the suggested code (also [in here](https://github.com/NativeScript/NativeScript/issues/3075) by @tsonevn ) - doesn't work in the latest version.

As you can see : I'm still able to drag the window : 

<img width="361" alt="screen shot 2018-07-18 at 23 31 56" src="https://user-images.githubusercontent.com/2842123/42907324-1e3ce118-8ae6-11e8-8747-de3f7996dad0.png">

It happens in emulator and also on a real device.
(nativescript 4.1)

Attached sample project : https://ufile.io/umni8

_Copied from original issue: NativeScript/ios-runtime#956_

**Comment by tsonevn** [comment]
HI @RoyiNamir,
In this scenario,  you should set up the `enableSwipeBackNavigation` property to `false ` in the detailed page(e.g. `item-detail.component.ts`). For your convenience, I am attaching a sample project. 
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2209392/Archive.zip)

**Comment by RoyiNamir** [comment]
@tsonevn Thank you for reply.
I thought that if I set this property on page A  , then it protects A from being "backed" to.
But apparently it should be set on page B. and not in page A.

**Comment by RoyiNamir** [comment]
@tsonevn Thank you for reply.
I thought that if I set this property on page A  , then it protects A from being "backed" to.
But apparently it should be set on page B. and not in page A.

BTW do you know about any GLOBAL way of doing it ? ( prevent back via swipe in ios)

**Comment by tsonevn** [comment]
HI @RoyiNamir,
In your case, you can try removing the gesture while using `removeGestureRecognizer`. For example:
items.component.ts
```
import { Component, OnInit } from "@angular/core";
import {Page} from "ui/page"
import { Item } from "./item";
import { ItemService } from "./item.service";
import {RouterExtensions} from "nativescript-angular/router"
@Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
})
export class ItemsComponent implements OnInit {
    items: Item[];

    constructor(private itemService: ItemService, private page:Page, private router:RouterExtensions) { 

    }

    ngOnInit(): void {
        this.items = this.itemService.getItems();
    }
    ngAfterViewInit(){
        setTimeout(() => {
            this.page.frame.viewController.view.removeGestureRecognizer(this.page.frame.viewController.interactivePopGestureRecognizer)
        }, 200);
       
    }
}
```
I also logged a new [feature request](https://github.com/NativeScript/NativeScript/issues/6098) for providing a new property which will allow disabling the swipe back navigation globally.

**Comment by hettiger** [comment]
Just for the record:

`this.page.ios.navigationController.interactivePopGestureRecognizer.enabled = false;`

Doing it like that allows to toggle the swipe back functionality dynamically.
