### ISSUE TITLE
Spelling on NativeScript landing page. No Code

### ISSUE THREAD

**Issue by endepointe** [NativeScript/NativeScript#6094]
Used 'V' instead of 'B' in "hybrid WebView-vased) apps"

Snapshot given

![ns](https://user-images.githubusercontent.com/30739491/42961021-67e39198-8b42-11e8-8262-f3ebcd294370.GIF)

Easy fix but it is nice to see correct spelling.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/docs#1267
