### ISSUE TITLE
Come on down to party town! Discord Server!

### ISSUE THREAD

**Issue by TheJaredWilcurt** [NativeScript/NativeScript#6103]
When are our NativeScript buddies going to join all the Vue kids on Discord?

![baman](https://user-images.githubusercontent.com/4629794/43037374-b700ae52-8cda-11e8-9102-088149924ab7.png)

![both](https://i.kym-cdn.com/photos/images/original/000/538/731/0fc.gif)

In conclusion:

![cat dj](https://media.giphy.com/media/swNCgflRTbWVi/giphy.gif)

![cat party](https://media.giphy.com/media/yoJC2qAXwxtoLpK7pm/giphy.gif)

![dog swag](http://i.imgur.com/Oxy0e6I.gif)

![dog rave dance](https://78.media.tumblr.com/e2b4f07b3ddc3df3914bdd2bcf21383e/tumblr_mwk6diXjGh1rq45r5o1_500.gif)

![cat and dog dance party baby](https://media.giphy.com/media/zypf2S3hCbf0s/giphy.gif)

**Comment by jlooper** [comment]
I'll hop on when I can! :)

**Comment by gustojs** [comment]
@TheJaredWilcurt what's your handle on Vuejs Discord?

**Comment by NickIliev** [comment]
Discord group can be found at the following link:

https://discordapp.com/invite/tWatGYj
