### ISSUE TITLE
myApp breaks after adding plugins that uses pods

### ISSUE THREAD

**Issue by andrewvmail** [NativeScript/NativeScript#6106]
Heads up guys, after plugin installation tns run ios breaks

```
2018-07-21 20:00:20.421 xcodebuild[81537:506460] [MT] IDEDistribution: Step failed: <IDEDistributionPackagingStep: 0x7fcb8990cb60>: Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value., NSFilePath=/var/folders/f3/1xjfp66x2f5gpkjv83q69q2h0000gn/T/ipatool-json-filepath-87gK7c}
error: exportArchive: The data couldn’t be read because it isn’t in the correct format.
```

```
tns create test-drive-nativescript --template angular
tns plugin add nativescript-websockets
tns run ios 
```

```
#tns doctor
✔ Getting environment information 

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 4.1.2 version and is up to date.
✔ Component tns-core-modules has 4.1.1 version and is up to date.
✖ Component tns-android is not installed.
✔ Component tns-ios has 4.1.1 version and is up to date.
```

```
tns --version
4.1.2
```

solution
----
```
npm install nativescript@next
```

**Comment by NathanaelA** [comment]
Hi @andrewvmail,

As the author of the websocket plugin, I am actually quite confused as to why you are having any issues.   First in the future it is better to drop a bug report on my [repo](https://github.com/NathanaelA/nativescript-websockets) ; I am more likely to see it.

Second I just grabbed the latest demo & version (1.5.0), made sure to upgrade to the very latest nativescript, core modules and runtimes.  (As the demo is set to 4.1 not 4.1.1) 
```
bash-3.2$ tns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 4.1.2 version and is up to date.
✔ Component tns-core-modules has 4.1.1 version and is up to date.
✔ Component tns-ios has 4.1.1 version and is up to date.
```
Did a simple `tns run ios` and the app built and ran fine on my iPhone 7.

**Comment by andrewvmail** [comment]
Hi @NathanaelA thanks your comment helped me isolate the issue. turns out its not the plugin. I had a feeling its not your plugin thats why i have it here.

But the Nativescript readme needs to be updated to use ``` npm install nativescript@next ``` or funny things can happen. 

@RoyiNamir since this is resolved, I'm closing this I think you should open a dialogue at his repo now...

**Comment by NathanaelA** [comment]
@RoyiNamir - NS-Signalr uses NS-Websockets.  ;-)

@andrewvmail - Using @next is NOT recommended unless you are testing something, see my blog post:
http://fluentreports.com/blog/?p=528 on @next and its uses.  ;-)

**Comment by andrewvmail** [comment]
This bug is fixed on next. Please close when its in latest.

**Comment by andrewvmail** [comment]
@NathanaelA thanks! im just getting my feet wet with the nativescript ecosystem.

**Comment by NathanaelA** [comment]
@andrewvmail - Not a problem; we all get our feet wet at some point.   :grinning:      I hope your future attempts with NativeScript go a lot more smoothly!

**Comment by NickIliev** [comment]
@andrewvmail glad to hear you have managed to resolve the issue. There is a known issue with POD regeneration logged [here](https://github.com/NativeScript/nativescript-cli/issues/3549) - we've released a fix which is currently in the master branch so perhaps this is what the issue was on your side.

Closing this as related to [https://github.com/NativeScript/nativescript-cli/issues/3549](https://github.com/NativeScript/nativescript-cli/issues/3549) but I will reopen the issue if ihe reasons are elsewhere.
