### ISSUE TITLE
Data binding access Array item via binded index does not work as mentioned in the docs

### ISSUE THREAD

**Issue by shiv19** [NativeScript/NativeScript#6107]
https://docs.nativescript.org/core-concepts/data-binding#supported-expressions
Referring to `array access`

Demonstration: https://play.nativescript.org/?template=play-js&id=YFnWeE

For some reason, this is not working as mentioned in the docs.

It works fine if I uses `list[0]` (if I pass actual number when I bind it)

**Comment by NickIliev** [comment]
@shiv in this case, the inner index binding should be accessed via the exposed `$parents` binding (iotherwise `this` inside the array does not refer to the global binding context).

For example:
```XML
Label text="{{ list[$parents['Page'].index] }}"  />
```
You could also use as parent freference the root layout (e.g. StackLayout) if no page exist in your applicaiton,.

However, if applicable you could directly pass the number value of the array item
```XML
<Label text="{{ list[0] }}" />
```

Playground demo [here](https://play.nativescript.org/?template=play-js&id=YFnWeE&v=3).

**Comment by shiv19** [comment]
@NickIliev 
Please take a closer look at the issue 
using `list[$parents['StackLayout'].index]` when index is set to 2,
is yielding `2` on the label, instead of the expected `case` text for the playground demo you sent.

$parents['StackLayout'].index => 2
list[2] => case
list[$parents['StackLayout'].index] => 2

**Comment by NickIliev** [comment]
@shiv19 indeed this seems to be the case - using binded index is not working as expected so I am marking this one as a bug

**Comment by shiv19** [comment]
Another option is to handle such cases from the code behind file
by manually updating the desired views when the index changes.

**Comment by shiv19** [comment]
@NickIliev 
Thanks to @PeterStaev, now I know to bind to variable index, of an array,
Demo: https://play.nativescript.org/?template=play-js&id=YFnWeE&v=4

We can use `{{ list index, list[index] }}` to bind it. i.e., specify the variables and then use it.

So this means that the documentation has to be updated,
Closing this issue.
