### ISSUE TITLE
App Store rejection

### ISSUE THREAD

**Issue by alibahjat** [NativeScript/NativeScript#6110]
hello 
the app store reject my app because of this

Your app appears to be a pre-release, test, or trial version with a limited feature set. Apps that are created for demonstration or trial purposes are not appropriate for the App Store.

how can solve this problem

**Comment by NickIliev** [comment]
@alibahjat take a look [at this comment](https://stackoverflow.com/a/36451915/4936697)

based on [this page](https://developer.apple.com/app-store/review/rejections/) your application might have advertisements that are rejected.

```
Advertisements
When submitting your app for review, you’ll be asked whether your app uses the Advertising Identifier (IDFA) to serve advertisements. If you indicate that your app uses the IDFA, but it does not have ad functionality or does not display ads properly, your app may be rejected. Make sure to test your app on an iOS device to verify that ads work correctly. Similarly, if you indicate that your app does not use the IDFA, but it does, your app will be put into the “Invalid Binary” status.
```
