### ISSUE TITLE
Memory Leak with ListView 

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#6111]
### Did you verify this is a real problem by searching the forum (no), issues (yes)

Long story short; trying to track down a memory leak; and based on the heap data I saw -- the issue was that lots of Labels and Label Properties were being created and not freed in a NAN app using a RadListView.  (and by a lot, I mean like a ~150 per each navigation.back) 

So first step is to create simple test case; I started with a very simple PAN app; and a stock ListView to see if I can duplicate the issue with minimal code, and got a different bug.  Memory leak; but not the one I was seeing in NAN.  :grinning:   

### Tell us about the problem
Using a ListView will leak _all_ templates worth of items each navigation return.  Please note by all templates; I mean that if your listview has 5 different templates; it will then create 5 new templates worth of items on each return on a navigate.goback...   So if you had 20 templates in memory; you would now have 25 templates in memory.   Each navigate away and then return by a "goback" will generate another 5 templates worth of items in memory.   Now if each template has say two labels; then you will get 10 labels generated each time.  As you can see; this can generate a pretty significant leak each master->detail; goback loop you do.

### Which platform(s) does your issue occur on?
Android  (untested on iOS)

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.2
- Modules: 4.1.1
- Android Runtime: 4.1.3

### Please tell us how to recreate the issue in as much detail as possible.
Well the first thing you need to do is modify the UI/Label.js code to add very simple tracking; 
Here is tracking code:
```
var _counter = 0, _disposed = 0;
Label.prototype.createNativeView = function () {
    	_counter++;
    	console.log("Label: create", _counter, ", disposed:", _disposed, "Left:", _counter-_disposed);
        if (!TextView) {
            TextView = android.widget.TextView;
        }
        return new TextView(this._context);
    };
Label.prototype.disposeNativeView = function () {
		_disposed++;
		console.log("Label: Disposing Labels left:", _counter-_disposed);
		_super.prototype.disposeNativeView.call(this);
	};
```

Please note; I added this same tracking to `Image`, and I have the same issue with leak with a Image.  So to keep things simple; we will just add the tracking to the Label.   Basically all items inside all the ListView templates is leaked.   

Attached is a sample project; can't really run this from Playground because it doesn't let you mess with the core modules to add the simple label tracking.  :grinning:

[testlist.zip](https://github.com/NativeScript/NativeScript/files/2226147/testlist.zip)

---

I should state; I suspect the leak in this specific case is caused by TNS creating a new copy of each of the Templates while parsing them for some reason.   I could be wrong but this seems like a logical reason for me to only get one template of each type created on each `goback`.

**Comment by NathanaelA** [comment]
@ADjenkov, interesting problem.  Not sure I fully understand how the elements are sticking around after navigating away and then back. 

Shouldn't the old "measuring" templates have been discarded when the new "measuring" templates are creates and assigned to the listview?     The issue I'm seeing is that it appears all these "measuring" templates are all staying around no matter how many forward/goback cycles I do.

**Comment by ADjenkov** [comment]
Navigating forward won't dispose any Labels since the views are kept alive, so that when you come back to them, their view state will be kept the same. Views are destroyed only when you back away from them. If you navigate to 'detail' back with clearHistory:true all the labels will be disposed and when go back they will be recreated again

**Comment by NathanaelA** [comment]
@Adjenkov - Yes I realize going forward doesn't eliminate the labels.   Guess I needed to be more clear in what I stated.  :Grinning:

Say I navigate to Main page; it creates say 110 labels for all the lines of data it shows.  Navigate forward, and  goback; it create another 10 labels (for sizing purposes).  Navigate forward and goback it creates another 10 labels (again for sizing).      So now I have 130 labels in memory.    

In all reality 20 of those labels should no longer in use (10 from the first time, 10 from the second time, the 10 in the third view should be valid even if not being used for display purposes).    

My question is why aren't the 10 from navigation 1 and the 10 from navigation 2 being cleared.  Shouldn't they have been disposed of when the 10 news ones were created on the 3rd goback.

Now assuming we only have one template with 10 labels causes 10 to leak.   If we have 5 templates with 10 labels each; we just got a 50 label leak each navigation sequence.   

I am not worried about extra labels being created for sizing reason -- what I am worried about is why these sizing labels then are retained _forever_ and then even more sizing labels are created on each navigation sequence.

**Comment by ADjenkov** [comment]
@NathanaelA I should have guessed that you are not talking about the navigation - my bad. The new labels when you go back is because of that measure mode/state the ListView is currently in (because of the StackLayout), since again getView method is called without convertView (_and new Label is created_). There is currently no custom logic inside getView that takes care of despossing these unnecessary components. Neither the native ListView knows when and how to destroy them I guess.

Is there any particular reason for you to wanna use ListView (with no specific _height_) inside StackLayout in your application, since it will behave badly visually as well?

**Comment by NathanaelA** [comment]
Oh, I think I understand what your saying.   So then the getView should then probably not retaining the items.  

So this code down here probably should be changed:
https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/list-view/list-view.android.ts#L325
So that it doesn't cache the items when convertview is not called; or that cache should be reset when the listview is reinitialzed on the goback.  ;-)
  
I believe the reason why was because they were using images; and the images could be different sizes so the size of the stacklayout would be taller and shorter per label change.

**Comment by ADjenkov** [comment]
Additional Labels creation won't happen if the ListView have specified height (or it is placed inside GridLayout)

Closing this issue in favor of these PRs https://github.com/NativeScript/tns-core-modules-widgets/pull/161 https://github.com/NativeScript/NativeScript/pull/6784. We've decided to add runtime warning when nesting ListView inside StackLayout (or ScrollView).

**Comment by webmeemba** [comment]
Out of memory - leak ui
Out of Memory Issue - 6000 items

Hi, I need to be able to show in a radlistview 7000 elements with cached images in an optimal way. Currently the url of the image is 400x300 / imagen.jpg. But when you go displaying products in the view it becomes corrupted. Someone could help me?

Thanks!
