### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by debpedrano** [NativeScript/NativeScript#6112]
Greetings there my friend, I am a student in a university here in the Philippines, I am a graphics designer. By any chance, can I update the current logo ? or made some a little bit of changes ?

**Comment by tsonevn** [comment]
Hi @debpedrano,

Thank you for the suggestion.

I discussed your proposal with our designers, however, currently there are no plans to change the NativeScript logo. 

Regards,
@tsonevn
