### ISSUE TITLE
Class binding text color issue in iOS only

### ISSUE THREAD

**Issue by marklanhamhc** [NativeScript/NativeScript#6115]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes, can't see anything similar to this issue.

### Tell us about the problem
There seems to be an issue with class binding and changing text color in iOS. I basically have a button group of 3 buttons. Each button has a default style of a white background and grey text color and when tapped, the class binding gives the tapped button an active class which then makes the background blue and the text white. This works fine in Android however in iOS the background changes to blue, as expected, but the text stays grey.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.2
- package.json file:
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.MyApp",
    "tns-android": {
      "version": "4.1.3"
    },
    "tns-ios": {
      "version": "4.1.1"
    }
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "@mdi/font": "^2.4.85",
    "angular-oauth2-oidc": "^4.0.2",
    "nativescript-angular": "~5.3.0",
    "nativescript-drop-down": "^4.0.1",
    "nativescript-material-icons": "^1.0.3",
    "nativescript-ngx-fonticon": "^4.2.0",
    "nativescript-svg": "^1.3.4",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-sidedrawer": "~4.0.0",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~5.5.5",
    "tns-core-modules": "^4.1.0",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~5.2.0",
    "@ngtools/webpack": "~1.9.4",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "~0.1.19",
    "codelyzer": "~4.0.2",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "~1.5.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.10.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "~6.0.6",
    "tslint": "~5.8.0",
    "typescript": "~2.7.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  }
}

### Please tell us how to recreate the issue in as much detail as possible.
See example: https://play.nativescript.org/?template=play-ng&id=A3975k&v=2

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1453
