### ISSUE TITLE
feature(iOS-property) know if a view property was changed

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/NativeScript#6117]
In my module I have a custom View which have its own  way of drawing background, borderRadius ....

I managed to get it to work by implementing ```backgroundInternalProperty.setNative```
However I have an issue with the borderRadius.
My native view already have a borderRadius(material button) but in ```backgroundInternalProperty.setNative``` there is no way to know the borderRadius was actually "set" because the default value of borderRadius is 0. So no difference between default value and actually setting the borderRadius to 0 through html or css.

Could we have a property in ```Background``` like  ```borderIsSet``` which would be put to true as soon as one of the 4 borders is set?

I am willing to make a PR if that will make it in the Framework.

Thanks

**Comment by NickIliev** [comment]
@farfromrefug all contributions are welcome if they make sense. Notice that as a cross-platform framework, in the base scenario most properties would be exposed for both platforms (there only a few very specific exceptions).

Apart from that, I was thinking about your implementation. If the default value is 0 why do you need a check if the border-radius is set in the first place (it is always set as it has a default value)? Perhaps, you could check if the border-radius value is greater than 0 (which would practically mean that we have a radius applied) and assume that it is not set if the value is 0.

You could also check how other UI plugins are handling similar cases. For example, nativescript-cardview has its own radius property ([here ](https://github.com/bradmartin/nativescript-cardview/blob/e6319e89855ccd9eced7bdc2417a423b3b4e5ca3/src/cardview.android.ts#L22-L24)and [here](https://github.com/bradmartin/nativescript-cardview/blob/0e102cc5c4c2ec470fe15839e409fadc881bf328/src/cardview-common.ts#L60-L64) and [here](https://github.com/bradmartin/nativescript-cardview/blob/e6319e89855ccd9eced7bdc2417a423b3b4e5ca3/src/cardview.ios.ts#L27-L33))

**Comment by farfromrefug** [comment]
@NickIliev Thanks for actually thinking about my implementation !!! 
My issue is this:
I am implementing material components. Let's say a button.
For this I need to override all background behaviours like borderRadius or backgroundColor.

The native component has a default borderRadius which I don't want to "hardCode" because it might change, depend on theme (android) ...

So my Button class constructor I have no way of knowing the default borderRadius without having access to the nativeView (which is not created yet).
So I can only set the "default" borderRadius in ```createNativeView```. But the ```style.borderRadius``` might already have changed. Especially the hard case is that the user might explicitly have put it to 0 which is also the default.
So I can't know about it ...
That's my all issue. In fact the main issue is that you can't set the default value for a ```CSSProperty``` on a Widget base. That would be awesome! But even then in my case I still would need to get the default value from the native side (maybe read the theme...)

Now about cardView yes I can define my own property but : 
* I am all about reusability. It's in the core, we should not re-implement it.
* I want a css property. I think if I do this I will face the same issue. Plus the "borderRadius" prop is already defined...

Finally about the PR. I need to ask first because It takes time to write a PR and I don't want to be refused once created ...

Thanks again

**Comment by vakrilov** [comment]
Hi, there is a mechanics in the property system that will allow you to get a default value form the native component (and not use one hardcoded in JS). You can use the `getDefault` symbol in the property to define a getter function. [Here is an example with the min/max dates in the `DatePicker`](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/date-picker/date-picker.android.ts#L112-L126). The callback will be called the first time you try to set the value of the property. The result is cached in case you want to reset the property later on.

Note: The `getDefault()` callback (if exists) will have higher priority when getting and caching the default value for the property. 

[Here](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/core/properties/properties.ts#L159-L161) is the relevant section in the property code if you are interested.

**Comment by farfromrefug** [comment]
@vakrilov @NickIliev This issue should be reopened. The getDefault does not for for borderRadius which is a ShortHandProperty. Consequently there is now way to define the default border radius for a view. This is a big issue for any components that want to 'override' the default border radius behavior.
One example is ```nativescript-material-components``` where the (textfield)[https://material.io/design/components/text-fields.html#usage] has its own border radius behavior, and especially has its own default values. Right now i am stuck and can't enable the borderRadius property
