### ISSUE TITLE
CSS Attribute Selectors Don't Respond to Changed State

### ISSUE THREAD

**Issue by mudlabs** [NativeScript/NativeScript#6122]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
- _Yes_. Couldn't find similar issue/discussion

### Tell us about the problem
I'd expect **CSS** attribute selector rules to kick in when there's a change and they become valid/true, however that is not the case.

For example the rule, `.label[occupied="true"] { background-color: red; }` will not produce a **red** label unless the condition is _true_ to begin with. 

Toggling between `.label` and `.label.occupied` will work as expected though.

- [Playground example](https://play.nativescript.org/?template=play-js&id=iyrT7x)

### Which platform(s) does your issue occur on?
iOS/Android/Both
- iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.1
- Modules: 4.1.0 
- iOS Runtime: 4.1.1

**Comment by pana-cc** [comment]
Angular? What is `occupied`? When you set `occupied` does it notify the `occupiedChange` event?

**Comment by mudlabs** [comment]
### I'm using {N} Core.
The Playground link I shared was not correct. Here's the correct version (just tested) [Playground example](https://play.nativescript.org/?template=play-js&id=uuTVCB)

`occupied` is just an attribute I've set to the `Label`.
```xml
<Label text="Blabla..." class="label" occupied="false" />
```
It doesn't matter how you change `occupied`. For Example in the Playground example I've attached a `tap` event that updates it to _"true"_ via `bindingContext`. But even if you don't use binding the result is the same.

Incase you can't access the Playground example;
```xml
<Label text="Blabla..." class="label" occupied="false" tap="makeLabelGreen"/>
```
```css
/* If we have this simple CSS */
.label {
   background-color: red;
}

.label[occupied="true"] {
    background-color: green;
}
```
```js
/*
  After execution the Labels' occupied attribute will be true. 
  We could expect the Label to now be green, but it will still be red.
*/
function makeLabelGreen(args) {
    const label = args.object;
    label.occupied = true;
}

exports.makeLabelGreen = makeLabelGreen;
```

**Comment by pana-cc** [comment]
occupied is a plain JavaScript property and the inderlying system has no idea you've set it.
You can try to:
```
label.occupied = true;
label.notify({ eventName: "occupiedChange", object: label }); // I am not sure about all the property changed event data fields
```
One would think {N} should have a weblike `setAttribute` to handle this under the hood.

**Comment by tsonevn** [comment]
Hi @mudlabs,
The latest suggestion provided by @pana-cc  should work in your case. For your convenience, I am attaching a [link to a Playground example](https://play.nativescript.org/?template=play-js&id=uuTVCB&v=2).

**Comment by mudlabs** [comment]
Yes thank you @pana-cc and @tsonevn. My head was in _HTML5_ land, thinking we could just set our own custom attributes.

It would be good if we could though. Or if there was a comparable `data-YOUR_CUSTOM_THING` attribute setup, as there is on the web 🤔 

Until now `notify()` as always gone over my head. I didn't get what to pass `eventName`. 
- Is it always _attributeName_**Change**?

I assume you can use it for something other than when you change a custom attribute. Otherwise `notify({ attibuteName: "the_attribute", object: the_object })` would be more semantic, right?

Anything beyond this NativeScript docs section [Creating a custom event](https://docs.nativescript.org/core-concepts/events#creating-a-custom-event), I should read?

Thanks.

**Comment by mudlabs** [comment]
So it wasn't really a bug I just didn't get `notify()`, closing.

**Comment by farfromrefug** [comment]
@tsonevn sorry to jump on that issue but seems like the right place. In your sample app you send "notify" manually. Is there a way to make a View automatically notify on attribute change?

I am trying to use the attribute selector within a ng-for/v-for, consequently it is not as easy to call "notifiy" on the object (except with ```eachChildView```). 
Would be much better if i could tell the View to automatically "notify" if the attribute change. I think it is already the case with "properties"
