### ISSUE TITLE
Feature(iOS): Fonts are not scaled for a11y in nativescript.

### ISSUE THREAD

**Issue by m-abs** [NativeScript/NativeScript#6125]
### Tell us about the problem
Platform font-size setting not respected by nativescript apps.

This is a huge problem for our target audience, which include the some who are only partially sighted.

### Which platform(s) does your issue occur on?
iOS only. It works as expected on Android.

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1x
- Cross-platform modules: 4.1.x, 4.0.x, 3.x.
- Runtime(s): 4.1.0
- Plugin(s): none

### Please tell us how to recreate the issue in as much detail as possible.
Create a nativescript app and run it on iOS.

1. Go to `Settings -> General -> Accessibility -> Larger text` and change the font-size.
2. Go back to the `nativescript` app, the text is rendered the same size as before.

On `iOS 10+` UILabel have the property `adjustsFontForContentSizeCategory`
https://developer.apple.com/documentation/uikit/uicontentsizecategoryadjusting/1771731-adjustsfontforcontentsizecategor?language=objc

But my experience from solving this with our `@nota/nativescript-accessibility-ext` is that it only works for the preferred fonts on `iOS` and those are not easily set from `NativeScript`.

The way we solve it in `@nota/nativescript-accessibility-ext` is by [listening](https://github.com/Notalib/nativescript-accessibility-ext/blob/master/src/utils/FontScaleObservable.ios.ts) for the platform setting and scaling the font-size, unfortunately this is slow and gives makes the UI jumpy.

**Comment by NickIliev** [comment]
@m-abs indeed there is no out-of-the-box support for dynamic types. I am marking this one as a feature as even in native iOS not all fonts can be used as dynamic and for many custom fonts [a different techniques](https://medium.com/livefront/practical-dynamic-type-d2b5774e8a8a) are used to scale them properly.

Resources:
- [Dynamic Types from iOS Human INterface Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/typography/)

- [Practical dynamic types for iOS 11 with `UIFontMetrics`](https://medium.com/livefront/practical-dynamic-type-d2b5774e8a8a)

- [Using `adjustFontsForContentSizeCategory`](https://useyourloaf.com/blog/auto-adjusting-fonts-for-dynamic-type/)

**Comment by PatrickLohan** [comment]
How is this progressing. Asking because we have a information rich and UI heavy app that is borked if the user selects a device accessibility font zoom on both Android and iOS.

If there's another way around this while #8909 ids worked out please let us know. App broken in this state.

**Comment by m-abs** [comment]
@PatrickLohan
You try use our (nota.dk) `@nota/nativescript-accessibility-ext` and the theme extensions, that's what we do in our own app.

**Comment by PatrickLohan** [comment]
It doesn't look like there's a way to stop the iOS/Android accessibility settings when opening our app. Am I missing something obvious? Our app has already been designed and written with sight impairment in mind so we need to not allow the operating system to control UI in that way.

**Comment by vickyATD** [comment]
> feat(core): a11y support #8909

can you help me here as how can i achieve this for my app?

**Comment by PatrickLohan** [comment]
We use Nativescript-Vue and create a custom boolean prop (default true) that can be used in any text elements (labels/buttons etc.) that need to not have a11y settings.
