### ISSUE TITLE
webview not working in ios

### ISSUE THREAD

**Issue by alibahjat** [NativeScript/NativeScript#6130]
hello
i got this problem the webview is not work in ios only it is shown white screen
 
it is only load firstWebViewSRC the code html

![simulator screen shot - iphone 6 - 2018-07-27 at 19 10 46](https://user-images.githubusercontent.com/29424884/43332367-e46e58c6-91d0-11e8-84b1-457175b97e03.png)

in android every thing working fine

<img width="309" alt="screen shot 2018-07-27 at 7 23 31 pm" src="https://user-images.githubusercontent.com/29424884/43333270-d4c7d7ce-91d2-11e8-892a-2fd922e96325.png">

my view is 

 ```
  <GridLayout row="1" rows="100 *" columns="*">
        <WebView row="0" col="0" [src]="firstWebViewSRC"></WebView>
        <WebView row="1" col="0" [src]="secondWebViewSRC"></WebView>
    </GridLayout


```
my code is 

```

import {Component, ViewChild, ElementRef} from "@angular/core";
import { RouterExtensions } from "nativescript-angular/router";
import { getString } from "tns-core-modules/application-settings/application-settings";
import { WebView, LoadEventData } from "ui/web-view";

@Component({
    selector: "map",
    templateUrl: "map.html",
    styleUrls: ["map.css"],
    moduleId: module.id 

})

export class MapComponent {

public firstWebViewSRC = '<!DOCTYPE html><html><head><title>MyTitle</title><meta charset="utf-8" /></head><body><span style="color:#0099CC; text-align: center;">First WebView</span></body></html>';

public secondWebViewSRC = 'https://www.youtube.com/';


    constructor(public routerExtensions:RouterExtensions) {

    }
  

}

```
please help me

**Comment by jibon57** [comment]
@alibahjat , in case of iOS if you want to add anything even `label` with `webview` then you will need to give `height` value of `webview`.

```
 <GridLayout row="1" rows="100 *" columns="*">
       <WebView height="300" row="0" col="0" [src]="firstWebViewSRC"></WebView>
       <WebView height="300" row="1" col="0" [src]="secondWebViewSRC"></WebView>
</GridLayout
```

**Comment by alibahjat** [comment]
still now working

**Comment by alibahjat** [comment]
please help me

**Comment by alibahjat** [comment]
i opened this issue in https://discourse.nativescript.org/t/webview-not-working-in-ios/7218
the problem still exsist
