### ISSUE TITLE
Issue with Angular Tab Navigation Template on Android

### ISSUE THREAD

**Issue by svzi** [NativeScript/NativeScript#6131]
### Tell us about the problem
The tabs are placed above the action-bar as shown in this screenshot:
https://ibb.co/jSkXUT

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.2
- Cross-platform modules: 4.1.2
- Runtime(s): 4.1.2
- Plugin(s): 
```
  "dependencies": {
    "@angular/animations": "~6.0.6",
    "@angular/common": "~6.0.6",
    "@angular/compiler": "~6.0.6",
    "@angular/core": "~6.0.6",
    "@angular/forms": "~6.0.6",
    "@angular/http": "~6.0.6",
    "@angular/platform-browser": "~6.0.6",
    "@angular/platform-browser-dynamic": "~6.0.6",
    "@angular/router": "~6.0.6",
    "nativescript-angular": "~6.0.6",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.1.0",
    "tns-core-modules": "4.1.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~6.1.0-beta.3",
    "@ngtools/webpack": "6.1.0-rc.0",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "codelyzer": "~4.3.0",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "~1.6.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.14.0",
    "tslint": "~5.10.0",
    "typescript": "~2.7.2"
  }

```

### Please tell us how to recreate the issue in as much detail as possible.
Just start a new NS project based on the tab view starter template.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Just remove `androidTabsPosition="bottom"` from line 1 in file `app.component.html`.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1463
