### ISSUE TITLE
custom ActionBar with GridLayout has a small gap on the left

### ISSUE THREAD

**Issue by racknoris** [NativeScript/NativeScript#6133]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes, there's issue #4843 

### Tell us about the problem
There's a gap in a custom ActionBar on the left (GridLayout inside ActionBar), which can't be closed, even when margin/padding is 0 

### Which platform(s) does your issue occur on?
Android
(Might be also iOS, haven't tested yet)

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0
- Cross-platform modules: 4.1.1
- Runtime(s): 4.0.0
- Plugin(s): version number of `tns-android` is 4.1.3

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

1. Create a new angular project using a blank template: `tns create myActionBarIssue --ng`
2. On the path `app/item/items.component.html`:

Replace the:

```
<ActionBar title="My App" class="action-bar">
</ActionBar>
```

With:

```
<ActionBar title="My App" class="action-bar">
    <GridLayout rows="*" columns="*" backgroundColor="green">
        <Label text="Test"></Label>        
    </GridLayout>
</ActionBar>
```

3. See that there's a small gap between the label and the edge on the left, even though there shouldn't be
4. Now add `marginLeft="-15"` to the `ActionBar` element like so:

```
<ActionBar title="My App" class="action-bar" marginLeft="-15">
    <GridLayout rows="*" columns="*" backgroundColor="green" >
        <Label text="Test"></Label>        
    </GridLayout>
</ActionBar>
```

5. See that the label is placed correctly more or less

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
No code is involved

**Comment by tsonevn** [comment]
Reported  with t.1346423
