### ISSUE TITLE
How to replace datepicker for keyboard in NativeScript?

### ISSUE THREAD

**Issue by McDonal11** [NativeScript/NativeScript#6144]
I am trying to replace DatePicker for Keyboard when user clicks Textfield in NativeScript.

**NativeScript + Angular:**

**.HTML:**

```
<DatePicker *ngIf="toShowDatePicker" (loaded)="onPickerLoaded($event)" (dateChange)="onDateChanged($event)" (dayChange)="onDayChanged($event)" (monthChange)="onMonthChanged($event)" 
(yearChange)="onYearChanged($event)" verticalAlignment="center"></DatePicker>
<TextField hint="Please enter your birthday" (tap)="showDatePicker()"></TextField>
```

**.TS:**

```
showDatePicker()
{
    this.toShowDatePicker = true;
}
```

1.How to add Done button above DatePicker ?

2.How to replace DatePicker for Keyboard [as inputView in iOS]?

My [SO Question](https://stackoverflow.com/questions/51647398/how-to-replace-datepicker-for-keyboard-in-nativescript). Can anyone help me on this?

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there.

**Comment by NickIliev** [comment]
@McDonal11 you can [modify the default keyboard ](https://www.nativescript.org/blog/nativescript-ios-numeric-keyboard)that shows when the text field is in focus, in some ways but I am not sure about replacing the whole keyboard view. 

I was also thinking about your layout structure.. wouldn't it be easier to ass for the birthday from a label and use the datepicker as modal page (where you could create a more complex layout with done button, etc.) and when the modal page is closed to simply output the selected birthday via binding. 
Why do you need to open the keyboard when you can pop-up a datepicker via modal.

Closing the issue as how-to related. Keep in mind tht apart from the SO you could seek help for how-to-related questions in our community slack or [in the NativeScript forum](https://discourse.nativescript.org/)

**Comment by McDonal11** [comment]
Thanks for your reply. "use the datepicker as modal page", how to use that? I am new to NativeScript, So I don't know. Can u give sample example? @NickIliev

**Comment by NickIliev** [comment]
@McDonal11  [here ](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/ng-ui-widgets-category/modal-page/sample-modal-page-module-example)you can find an example for opening a modal that contains a date picker inside.

**Comment by McDonal11** [comment]
Why do you need to open the keyboard?? For this I am answering.

I am having 5 textfields. Name, age, DOB, place, phone. If I am using, TextField for those 5, I can easily navigate in between each other with the help of DownArrow and UpArrow which appearing topleft side of the keyboard and Done button which is in topRight side to dismiss keyboard. 

Without any code from my end, the above logic is handled by IQKeyboardManager. 

Hope you understood this.

Suppose, If I can replace Keyboard with Picker as my wish, the above logic will work here. 

Now, u r saying that this is not possible. Do u know, is there any other way to do this logic?
