### ISSUE TITLE
TabView does not seem to work with angular dynamic routing

### ISSUE THREAD

**Issue by ventsislav-georgiev** [NativeScript/NativeScript#6145]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem
TabView does seem to work when using using dynamic routes in an angular app.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- `tns-android`: `4.1.3`
- `tns-ios`: `4.1.1`
- `@angular`: `6.0.6`
- `tns-core-modules`: `4.1.1`

### Please tell us how to recreate the issue in as much detail as possible.
[NativeScript Playground repro](https://play.nativescript.org/?template=play-ng&id=CGEM9u&v=2)

**Comment by manoldonev** [comment]
Closing this as it seems Angular does not support the combination of dynamic routes and named (auxiliary) outlets:
app.component.html
``` html
<div>
	<router-outlet></router-outlet>
	<router-outlet name="browseTab"></router-outlet>
</div>
```

app.component.ts
``` ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'my-app',
  styleUrls: ['./app.component.scss'],
  templateUrl: './app.component.html',
})
export class AppComponent {
    constructor(private _router: Router) {
        this._router.config.unshift(
          { path: '', redirectTo: '/home(browseTab:browse)', pathMatch: 'full' },
          { path: 'home', loadChildren: './home/home.module#HomeModule' },
          { path: 'browse', loadChildren: './browse/browse.module#BrowseModule', outlet: 'browseTab' }
        );
    }
}
```

See attached Angular sample app where browserTab outlet remains empty.
[angular-playground.zip](https://github.com/NativeScript/NativeScript/files/2278486/angular-playground.zip)
