### ISSUE TITLE
ActtionBar cannot be wrapped into its own component

### ISSUE THREAD

**Issue by IAMtheIAM** [NativeScript/NativeScript#6149]
If I want to create a reusable action bar component like so:
```
//home.component.ts
<header [title]="'My Course Plan'"></header>
```
where I pass a string which becomes the value for action:

```
//header.component.html
<ActionBar class="action-bar">
    <Label class="action-bar-title"
        [text]="title"
        (tap)="logout()"></Label>
</ActionBar>
```

```
//header.component.ts
import { Component, Input } from '@angular/core';
import { LogoutService } from "../../../services/logout.service";

// import './header.component.scss';
// app

@Component({
    moduleId: module.id,
    selector: 'header',
    templateUrl: './header.component.html',
    styleUrls: [ './header.component.scss' ]
})
export class HeaderComponent {
    @Input() title: string;

    constructor(private logoutService: LogoutService) {
    }

    logout() {
        this.logoutService.logout(false);
    }
}

```

It does not work. It renders the default action bar with the word `nativescript` left aligned, the same as if I did not put the custom component there at all.

Why does it not understand this component? I must be misunderstanding something because this setup works for most components in angular.

TNS 4.1.1
NativeScript angular 6.1.0-rc.0
Android API 26

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1472
