### ISSUE TITLE
View Component consistancy

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#615]
In the View component; we use **.observe** to connect our event handlers to any Gesture events.  Is their some reason why we can't make this be a lot more consistent with the Observable event handling system and use the **on**, **addEventListener**, **off**, and **removeEventListener** functions?   That way all events go through those functions.

This seems inconsistent to have some events connected via **on** and some events connected via **observe**

**Comment by NathanaelA** [comment]
One note, I should say.    I am proposing here that we override the **addEventListener** & **removeEventListener** code at the View component, it would in a nutshell check to see if the event passed in is a gesture, and then behind the scenes call the observe otherwise it would call its super method.     This would make the event api much more consistent as then all events would go through add/remove...

**Comment by vakrilov** [comment]
One more inconsistency worth fixing are the event args:
For gestures `args.view`(coming form [GestureEventData](http://docs.nativescript.org/ApiReference/ui/gestures/GestureEventData.html)) should be used to get the calling view. 
For other events (for example Button.tap) it is `args.object` (coming from [EventData](http://docs.nativescript.org/ApiReference/data/observable/EventData.html)).

**Comment by enchev** [comment]
In my opinion observe() for gestures cannot be replaced easily with on/addEventListener since in the first case (observe) you can listen for multiple gestures with single callback:
```TypeScript
    var lbl = new Label();
    lbl.observe(GestureTypes.tap | GestureTypes.doubleTap | GestureTypes.longPress, args => {
       //
    });
```
while with on/addEventListener you can listen for just one event:
```TypeScript
    var btn = new Button();
    btn.on(Button.tapEvent, args => {
        //
    });
```

**Comment by NathanaelA** [comment]
@enchev hmm, didn't know you could do that.with observe -- However, that would still work fine.   It won't break. Doing a **|** will add them up to a single number, so again it would work as the prototype wouldn't have to change.  ;-)

**Comment by enchev** [comment]
Hi @NathanaelA,

It will be hard to apply the same pattern for regular events since they are strings (the first argument of on/addEventListener while gesture types are numbers and you can in bitwise operations.

**Comment by NathanaelA** [comment]
@enchev which actually makes it easier to support.  :grinning:
if (!sNaN(parameter)) { 
// Do addEventHandler
} else { 
// do observe
}

**Comment by enchev** [comment]
Hi @NathanaelA,

Actually you are right - I've made pull request with on/off support for gestures. Please let me know if you have any questions!

Thanks

**Comment by NathanaelA** [comment]
Awesome!  :+1:
