### ISSUE TITLE
use node package 

### ISSUE THREAD

**Issue by peppeg85** [NativeScript/NativeScript#6153]
hello, is there a way to use a node package with nativescript? 
i explain: 
i'm trying to use the node package https://www.npmjs.com/package/ftp but when i require it i have the following error: " failed to find module "fs" relative to app/tns-modules/ at etc.."

how can i use a node package with nativescript

thank you

**Comment by tsonevn** [comment]
Hi @peppeg85,
Some of the node packages, which are not dom related, can be used in a NativeScript application. Also, you can check the [nativescript-nodeify](https://github.com/EddyVerbruggen/nativescript-nodeify) plugin, which makes most npm packages compatible with NativeScript. For further question, please use our [forum](https://discourse.nativescript.org/) or StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript). This repository is used only for bug reporting and feature requests.

**Comment by peppeg85** [comment]
ok, thank you
