### ISSUE TITLE
TitleView in ActionBar not taking full width in android 5.1

### ISSUE THREAD

**Issue by shripal04** [NativeScript/NativeScript#616]
I am using genymotion emulator with android 5.1 OS.

I have create a simple app with custom titleView in actionbar.

Code for the page is as shown below:

```
<Page xmlns="http://www.nativescript.org/tns.xsd" 
      navigatedTo="navigatedTo" >
 
	<Page.actionBar>
		<ActionBar>
      			<ActionBar.titleView>
           			<GridLayout columns="*" style="background-color: blue;">
            			</GridLayout>
      			</ActionBar.titleView>
		</ActionBar>
	</Page.actionBar>
  
        <Label text="Hello world" />
</Page>
```

Above code gives output as shown below:
![android_5 1_nativescript_customtitleview_bug](https://cloud.githubusercontent.com/assets/4411891/9428984/87be6d74-49de-11e5-97a9-b93a635940ae.png)

I tested this code on Android 4.2 and Android 4.4. It is working fine and taking full width of the actionbar.
But, in Android 5.1 it is not taking full width of the actionbar. 

Can you help me out with this.

**Comment by vakrilov** [comment]
Hi @shripal04,
The padding of the action bar is the default behavior in Android. Good news is that in the upcoming 1.3 release we have reworked the action bar implementation, There you will be able to set the background on the action bar itself like that: `  <ActionBar  style="background-color: blue;">`.
I hope that will work for you.

**Comment by shripal04** [comment]
That sounds good. It will work for me.

Thanks and :+1:  for such an awesome framework.
