### ISSUE TITLE
How to format a string? (amount numbers)

### ISSUE THREAD

**Issue by VeeK727** [NativeScript/NativeScript#6169]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
There is [this thread](https://discourse.nativescript.org/t/separator-commas-for-numbers/5947) on the forum but its unanswered.

### Tell us about the problem
How do I format a number with commas. E.g. 10000 -> 10,000
I tried `num.toLocaleString('en')` which works in javascript but it didn't work here.

**Comment by tsonevn** [comment]
Hi @VeeK727,
In your case, you can use [nativescript-masked-text-field](https://www.npmjs.com/package/nativescript-masked-text-field) or [nativescript-maskedinput](https://www.npmjs.com/package/nativescript-maskedinput) plugins. The both will allow you to display the text in the needed format.

Also, you can post your questions in the StackOverflow [here](https://stackoverflow.com/questions/tagged/nativescript).

**Comment by VeeK727** [comment]
Hi @tsonevn , these are for `TextField` but I need them for `TextVIew`. I have to display these numbers not take input from user. Also I don't know how big the number be so I don't think a mask can be defined to suit all cases like 
100
1,000
10,000
100,000

**Comment by mudlabs** [comment]
@VeeK727 see: [NativeScript Forum](https://discourse.nativescript.org/t/tolocalestring/7338/2?u=mudlabs)
