### ISSUE TITLE
Loading images from resources - old instruction?

### ISSUE THREAD

**Issue by lukasz-galka** [NativeScript/NativeScript#6178]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem
I was trying to load images from resources using https://docs.nativescript.org/ui/images#load-images-from-a-resource but it didn't work

### Which platform(s) does your issue occur on?
Android (I haven't checked on iOs)

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
4.1.2

- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
4.1.1

- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
4.1.3

- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
I've created a new project using `tns create HelloWorld --template tns-template-blank`. Next I wanted to create `ActionBar` with `menu` icon. I've found this tutorial https://docs.nativescript.org/ui/action-bar#setting-icons, and here I've found how to load images from resources https://docs.nativescript.org/ui/images#load-images-from-a-resource. 

I downloaded icon from https://material.io/tools/icons/?style=baseline and put it to `app\App_Resources\Android`, next I created following xml

```
<ActionBar title="XYZ">
    <NavigationButton icon="res://baseline_menu_white_24" />
</ActionBar>
```

Unfortunately it did't work and I've spent a few hours to find solution. At the end by accident I've found other icons in `app\App_Resources\Android\src\main\res` so I moved my icons there and now everything works fine.

Is this https://docs.nativescript.org/ui/images#load-images-from-a-resource out of date or I am doing something wrong?

**Comment by tsonevn** [comment]
Hi @lukasz-galka,
Thank you for contacting us. We will review the article and will update its content. 
Regards,
@tsonevn

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/docs#1307
