### ISSUE TITLE
nativescript-ui-chart - RadCartesianChart valueProperty doesn't display when datasource changes from code

### ISSUE THREAD

**Issue by janossuta** [NativeScript/NativeScript#6192]
Hi,

I have a problem with `RadCartesianChart` when I updating the datasource from code the `valueProperty` doesn't display at all only the `categoryProperty` shows. 

I'm using Andorid 8.0.0 for testing

I've set up a playgroud to reproduce the issue:
https://play.nativescript.org/?template=play-ng&id=P8WPCT

my code is in the `home.component.ts` file

Could somebody help me with this issue? Am I doing something wrong?

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#796
