### ISSUE TITLE
TextView text disappearing on lost focus

### ISSUE THREAD

**Issue by mrwrighty** [NativeScript/NativeScript#6193]
I have a TextView defined as:

`<TextView id="inttext" hint="Enter details of any issues/concerns" editable="true" row="1" col="0" colSpan="2"
        class="textview" width="100%" horizontalAlignment="center" borderWidth="1px" marginTop="20px"></TextView>`

CSS is

`.textview{
    font-size: 15em;
    font-weight: normal;
    word-wrap: true;
    color: black;
    height: 200;
}`

When the textview looses focus some of the text disappears.

![out](https://user-images.githubusercontent.com/6585298/44254488-dd360100-a1fa-11e8-9a3a-0f2bac5d6920.gif)

I have tested on iOS 11.4.1 on Physical device via play and iOS 11.4 on Emulators via TNS CLI. I cannot recreate the issue on Android 4.4.4 via Play.

tns --version (4.2.1)

Here is a play.nativescript.org link

https://play.nativescript.org/?template=play-js&id=Jw2QJI&v=11

**Comment by tsonevn** [comment]
Hi @mrwrighty,
Thank you for the provided sample project. 
I reviewed the case and was able to recreate the issue. I will mark this as a bug. In the meantime, I would suggest removing the ScrollView. This seems to resolve the problem.

**Comment by tsonevn** [comment]
Hi @mrwrighty,
We researched further the issue and found that the border caused the problem, that is set up to the component. As a workaround, you can set the TextView inside a Layout container(e.g. `StackLayout`) and set the border on it. For example:
```
<Page loaded="pageLoaded" class="page" xmlns="http://www.nativescript.org/tns.xsd">
	<StackLayout borderWidth="1px" verticalAlignment="center">
		<TextView id="inttext" hint="Enter details of any issues/concerns" editable="true" class="textview" width="100%" marginTop="20px"></TextView>
	</StackLayout>
</Page>
```

**Comment by manoldonev** [comment]
Seems to work with latest tns-core-modules@5.4.0

**Comment by KarthikMalaimegam** [comment]
Still this issue in tns-core-modules@6.0.1 version but not in below ios13.2. 
Any workaround for below ios13.2 version?
