### ISSUE TITLE
tns run android produces TypeScript compiler failed with exit code 3221225786

### ISSUE THREAD

**Issue by IRCraziestTaxi** [NativeScript/NativeScript#6195]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
I searched for a while and found no solutions that helped me.

### Tell us about the problem
After running `tns run android`, the build succeeds: `Found 0 errors. Watching for file changes.`. However, nothing happens on my device. Then, when I stop the process, I see:
```
Failed during hook execution.
TypeScript compiler failed with exit code 3221225786
Error: TypeScript compiler failed with exit code 3221225786
    at Errors.fail (C:\Users\IRCraziestTaxi\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:125:28)
    at Errors.failWithoutHelp (C:\Users\IRCraziestTaxi\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:135:21)
    at HooksService.<anonymous> (C:\Users\IRCraziestTaxi\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\hooks-service.js:83:30)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\IRCraziestTaxi\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\hooks-service.js:5:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
4.2.1
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
4.2.0
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
4.2.0

### Please tell us how to recreate the issue in as much detail as possible.
`tns run android` used to work; it would deploy the built apk to my device. This error happened after I upgraded node to 8.11.3 and nativescript to 4.2.1. I simply run `tns run android` and nothing happens after the build succeeds, then when I stop the process, I see the error above.

**Comment by tsonevn** [comment]
Hi @IRCraziestTaxi,
Try to delete `node_modules`, `platforms `, `hooks` folders and `package-lock.json` file. Then rebuild the project with `tns run android`. If the problem persists, please send us the project or at least its package.json file.

**Comment by IRCraziestTaxi** [comment]
I deleted node_modules, platforms, hooks, and package-lock.json. Then, I ran `npm install` followed by `tns run android`. I got the same result:

```
19:00:15 - Starting compilation in watch mode...



19:00:20 - Found 0 errors. Watching for file changes.

TypeScript compiler failed with exit code 3221225786
Terminate batch job (Y/N)? y
```

The only difference is that it did not show the stack trace this time. Not sure whether that's significant or not.

I can't share my entire project, but I can work on creating a minimal reproduction of it. In the meantime, here is my package.json:

```
{
  "description": "NativeScript Application",
  "private": true,
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.<Redacted>",
    "tns-android": {
      "version": "4.2.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "nativescript-angular": "~5.2.0",
    "nativescript-exit": "^1.0.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-sidedrawer": "^4.0.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.5.2",
    "tns-core-modules": "^4.2.0",
    "uikit": "^3.0.0-beta.37",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "del": "^3.0.0",
    "gulp": "^3.9.1",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.3.5",
    "nativescript-dev-typescript": "~0.6.0",
    "typescript": "^3.0.1",
    "vinyl-paths": "^2.1.0"
  }
}
```

**Comment by IRCraziestTaxi** [comment]
Update: Made some progress.

I used `npm-check-updates` to upgrade all of my packages to the latest major version. In doing so, I upgraded from Angular 5 and RxJs 5 to Angular 6 and RxJS 6.

That allowed the application to launch on my device, but now I am getting a ton of errors regarding RxJS errors due to the RxJS 6 changes, so I am in the process of going through my code and updating all of my RxJS code per [these guidelines](https://www.academind.com/learn/javascript/rxjs-6-what-changed/).

It is quite annoying that `rxjs-compat` doesn't work with nativescript, but I am just happy I am making progress.

Here is my new package.json:

```
{
  "description": "NativeScript Application",
  "private": true,
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.<Redacted>",
    "tns-android": {
      "version": "4.2.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~6.1.3",
    "@angular/common": "~6.1.3",
    "@angular/compiler": "~6.1.3",
    "@angular/core": "~6.1.3",
    "@angular/forms": "~6.1.3",
    "@angular/http": "~6.1.3",
    "@angular/platform-browser": "~6.1.3",
    "@angular/platform-browser-dynamic": "~6.1.3",
    "@angular/router": "~6.1.3",
    "nativescript-angular": "~6.1.0",
    "nativescript-exit": "^1.0.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-sidedrawer": "^4.0.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~6.2.2",
    "tns-core-modules": "^4.2.0",
    "uikit": "^3.0.0-rc.9-dev.bd39d353",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "del": "^3.0.0",
    "gulp": "^3.9.1",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.3.5",
    "nativescript-dev-typescript": "~0.7.2",
    "typescript": "^3.0.1",
    "vinyl-paths": "^2.1.0"
  }
}
```

In closing:
Updated from node ~6.10 and npm ~4 to node 8.11.3 and npm 5.6.0.
Updated from nativescript ~3 to nativescript 4.2.1.
Updated android platform to 4.2.0.
Used `npm-check-updates` to update Angular and RxJS from 5.x.x to 6.x.x.

I hope this helps somebody else out. I will close this issue for now. I am confident that fixing all of my code to fit RxJS's ridiculous breaking changes will allow my application to build and run properly.
