### ISSUE TITLE
NS 4: Using a root view will affect the status bar background

### ISSUE THREAD

**Issue by demetrio812** [NativeScript/NativeScript#6197]
Hello,
I'm using the standard ActionBar in iOS and so far the background naturally extended over the status bar, you can see an example here:

https://play.nativescript.org/?template=play-ng&id=6vLorx&v=3

But

As soon as I add a View in the root view, like this:

```
<GridLayout> 
	<page-router-outlet></page-router-outlet>
        ... other always visible components...
</GridLayout>
```

You can see a working example here: https://play.nativescript.org/?template=play-ng&id=y9Ra3K&v=2

What should I do to fix it? I've tried many things but didn't find a solution so far

Thanks,
Dem

**Comment by tsonevn** [comment]
Hi @demetrio812,
I tested both projects on my side, however, I was unable to recreate an issue with the StatusBar colour. I am attaching screenshots from the builds of the projects. The colour was set up properly in both.
`v=3`
![6vlorx v 3](https://user-images.githubusercontent.com/17448734/44334013-167ba480-a479-11e8-9d12-d959bc8dd5d9.png)

`v=2`
![y9ra3k v 2](https://user-images.githubusercontent.com/17448734/44334026-1f6c7600-a479-11e8-94bd-afb8bc02d9b1.png)

It will help if you provide some more info about the issue, you are facing and whether there are some specific steps required for reproducing the problem.

**Comment by demetrio812** [comment]
Hello @tsonevn , can you try to close the preview and playground app and reopen them using this link:

https://play.nativescript.org/?template=play-ng&id=y9Ra3K&v=3

This is how I see it (on my iPhone X): 
![img_37c6a67bb5d0-1](https://user-images.githubusercontent.com/385644/44343705-f9ea6700-a48e-11e8-899d-ddc346cca8a5.jpeg)

Please let me know

Thanks,
Dem

**Comment by tsonevn** [comment]
Hi @demetrio812,
I was able to recreate the issue. It seems that this problem is related to the issue https://github.com/NativeScript/NativeScript/issues/5746 . 
To solve this case, you should remove the GridLayout in the app.component.html. For example:
```
<!-- <GridLayout> <-remove this line -->
	<page-router-outlet></page-router-outlet>
<!-- </GridLayout> <-remove this line -->
```

**Comment by demetrio812** [comment]
@tsonevn I know that without the GridLayout it works (that was the other example), I need to add more components in the root view that's why I've added a gridlayout, also, I don't think it's related to the safe area as it does it also on iPhone 6/7/8

I don't think this issue should be closed
