### ISSUE TITLE
Application module's `onUncaughtError` function is not invoked

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#62]
_From @tjvantoll on March 25, 2015 13:29_

Hey all,

I'm trying to setup a global error handler of some sort, and it seems like the Application module's onUncaughtError is intended for just this sort of thing, but it doesn't seem to work. That is, if I use the following code in my `app.js`:

```
var application = require( "application" );
application.mainModule = "app/main-page";
application.onUncaughtError = function(error) {
	alert( "Hello world" );
	return false;
}
application.start();
```

I don't get the alert when a JavaScript error occurs on either Android or iOS. I dug a bit further into Application module's iOS implementation and I found that I don't get into this catch block either: https://github.com/NativeScript/cross-platform-modules/blob/fdf8937c5da38c2796b0728cd00453e0098801aa/application/application.ios.ts#L184-191.

Am I doing something wrong, or is this function just not being triggered?

Thanks.

_Copied from original issue: NativeScript/cross-platform-modules#224_

**Comment by enchev** [comment]
_From @ritcoder on April 5, 2015 11:21_

I just tried and it was triggerred. I'm using android. You can try updating to the latest version of the cross platform modules to see if it works. One thing though as it the alert is not shown though the function is called. I'm not sure if it is because the application has crashed.

This is the help on the method from the typescript definition file:
/**
     * A callback to be used when an uncaught error occurs while the application is running.
     * The application will be shut down after this method returns.
     * **Loading new UI at this point is erroneous** and may lead to unpredictable results.
     * The method is intended to be used for crash reports and/or application restart. 
     */

**Comment by slavchev** [comment]
Staring from the next NativeScript (1.4) release this functionality will be supported for iOS as well. It is important to note that there are scenarios when this callback is not guaranteed to be called (e.g. segmentation fault). We'll look further how to provide workarounds (if any) in most common scenarios.
