### ISSUE TITLE
New livesync: Socket closed from server before operation end

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/NativeScript#6200]
Hi there. Updating to NativeScript 4.2 leads to some errors in livesync. As livesync has been rewritten completely in new version, the speed is high but sometimes I get the following error and application suddenly crashes.

```
Successfully transferred item-detail.component.html.
Unable to apply changes for device: BUC4C16805014542. Error is: Socket closed from server before operation end..
Executing after-watch hook from C:\Users\vahidnajafi\NativeScript\tns423\hooks\after-watch\nativescript-dev-typescript.js
Stopping tsc watch
```

Then livesync stops working...

**Comment by tsonevn** [comment]
HI @vahidvdn,
Can you check if you will able to recreate the issue while using the latest CLI `4.2.2`? 
If the issue persists, please provide some info about the project and the steps, which you use while building the project.

**Comment by vahidvdn** [comment]
@tsonevn It's `4.2.2` . When I run `tns info` :

```
√ Getting NativeScript components versions information...
√ Component nativescript has 4.2.2 version and is up to date.
√ Component tns-core-modules has 4.2.0 version and is up to date.
√ Component tns-android has 4.2.0 version and is up to date.
√ Component tns-ios has 4.2.0 version and is up to date.
```

I simply create a blank ng project and run to my device. I'll test it more, maybe I lost my connection from my phone.

**Comment by vahidvdn** [comment]
@tsonevn [Here ](https://github.com/NativeScript/nativescript-cli/issues/3755#issuecomment-414406064)you can see more detail about the error.

And when app crashes:

![photo_2018-08-22_17-46-37](https://user-images.githubusercontent.com/11078601/44466243-08728300-a635-11e8-9959-62b6be67a84e.jpg)

**Comment by vahidvdn** [comment]
I reinstalled `nativescript` and now it works fine.

**Comment by Karolcz125** [comment]
In my case using run configuration provided with nativescript plugin in WebStorm was causing the problem. Running the app using console not only solved the error, but also made compiling and installing the app much faster.
