### ISSUE TITLE
Error while trying to start application ... on device 0034008422. Error is: Devices.NotFoundDeviceByIndexErrorMessage

### ISSUE THREAD

**Issue by felipebueno** [NativeScript/NativeScript#6205]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes.

### Tell us about the problem
Unable to debug after upgrading to TNS 4.2.2.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.2.2
- Cross-platform modules: 4.2.0
- Runtime(s): 4.2.0
- Plugin(s):
```
    "@nstudio/nativescript-camera-plus": "^1.0.5",
    "email-validator": "^2.0.4",
    "nativescript-camera": "4.0.2",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-couchbase": "^1.0.18",
    "nativescript-downloadmanager": "^0.1.0",
    "nativescript-drop-down": "^3.2.4",
    "nativescript-filterable-listpicker": "git+ssh://git@gitlab.com/innovareti/nativescript-filterable-listpicker.git",
    "nativescript-fresco": "^3.0.6",
    "nativescript-imagepicker": "^5.0.2",
    "nativescript-intl": "^3.0.0",
    "nativescript-pdf-view": "^2.0.1",
    "nativescript-phone": "^1.3.1",
    "nativescript-plugin-firebase": "5.2.0",
    "nativescript-pro-ui": "^3.4.1",
    "nativescript-radio": "^0.3.6",
    "nativescript-slides": "^2.2.14",
    "nativescript-social-share": "^1.5.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-youtubeplayer": "2.2.5",
    "rxjs": "^5.5.6",
    "tns-core-modules": "^4.2.0"
```

### Please tell us how to recreate the issue in as much detail as possible.
I don't know how to recreate the issue.

### Log
```
➜  emulzint-mobile git:(master) ✗ tns run --debug
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Executing before-watchPatterns hook from /home/felipe/devel/projects/innovare/emulzint/emulzint-mobile/hooks/before-watchPatterns/nativescript-dev-sass.js
Executing before-watchPatterns hook from /home/felipe/devel/projects/innovare/emulzint/emulzint-mobile/hooks/before-watchPatterns/nativescript-dev-typescript.js
Executing before-watchPatterns hook from /home/felipe/devel/projects/innovare/emulzint/emulzint-mobile/hooks/before-watchPatterns/nativescript-dev-webpack.js
Executing before-watch hook from /home/felipe/devel/projects/innovare/emulzint/emulzint-mobile/hooks/before-watch/nativescript-dev-sass.js
Found peer node-sass
Executing before-watch hook from /home/felipe/devel/projects/innovare/emulzint/emulzint-mobile/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 2.7.2
Executing before-watch hook from /home/felipe/devel/projects/innovare/emulzint/emulzint-mobile/hooks/before-watch/nativescript-dev-webpack.js
Executing before-shouldPrepare hook from /home/felipe/devel/projects/innovare/emulzint/emulzint-mobile/hooks/before-shouldPrepare/nativescript-dev-webpack.js
Skipping prepare.
Refreshing application...
Error while trying to start application br.com.innovareti.emulzintevoce on device 0034008422. Error is: Devices.NotFoundDeviceByIndexErrorMessage 34008421 tns
Unable to start application br.com.innovareti.emulzintevoce on device 0034008422. Try starting it manually.
```

**Comment by tsonevn** [comment]
Hi @felipebueno,
Try to clear up the project with the following steps:
1. delete `node_modules`, `platforms` and `hooks` folders
2. delete `package-lock.json` file
3. remove the project from the device
4. rebuild the project via `tns run android` or `tns debug android`

If the issue persists, please build the project with `tns run android --log trace > log.txt` and send us the `log.txt` file.


I also noticed from the provided log that the app is installed properly, however, the CLI was unable to start it. Regarding that, when the following message is printed on the console 
-> `Error while trying to start application br.com.innovareti.emulzintevoce on device 0034008422. Error is: Devices.NotFoundDeviceByIndexErrorMessage 34008421 tns
Unable to start application br.com.innovareti.emulzintevoce on device 0034008422. Try starting it manually.`
you can try starting the app manually.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-cli#3832
