### ISSUE TITLE
Issues with environment variables and Angular2+

### ISSUE THREAD

**Issue by rafaelcmrj** [NativeScript/NativeScript#6206]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem
I'm using Angular2+ and the environments file isn't loading the production file when using --release. I've tried --env.prod, --env prod, --env=prod and many other options. None of them worked.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.2
- Cross-platform modules: 4.1.1
- Runtime(s): ios 4.1.0 / android 4.1.3

### Please tell us how to recreate the issue in as much detail as possible.
Any app using Angular2+ and environment files.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
The environment files are located under /app/environments/enviroment.ts and /app/environments/enviroment.prod.ts

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1491
