### ISSUE TITLE
Function hooked to Webview's "loaded" function isn't being triggered when navigated within a Tab View application (coded in TypeScript)

### ISSUE THREAD

**Issue by SebanSunny** [NativeScript/NativeScript#6212]

**Comment by SebanSunny** [comment]
I'm adding an example code. Just replace the app folder after creating a new NativeScript app
[app.zip](https://github.com/NativeScript/NativeScript/files/2314986/app.zip)

You should see an alert pop-up when the Webview is loaded but the call isn't triggered. But when you switch tabs back and forth the "loaded" function is triggered.

**Comment by tsonevn** [comment]
Hi @SebanSunny,
I tested the described scenario, and the problem in the project seems to be related to the fact the HomeViewModel is set on page loaded event. The page's loaded event will be executed after WebView loaded, which means that the WebView loaded event listener still does not exist on the time when the WebView's loaded is executed.
To solve your case,  you can set up the bindingContext on `navigatingTo` event. For example:
home-page.xml
```
<Page navigatingTo="onNavigatingTo">

  <Page.actionBar>
    <ActionBar class="action-bar" title="Home" icon=""></ActionBar>
  </Page.actionBar>

  <GridLayout rows="*">
    <WebView row="0" loaded="{{ onWebViewLoaded }}" id="myWebView" src="{{ webViewSrc }}" />
  </GridLayout>
</Page>

```
home-page.ts
```
import { HomeViewModel } from './home-view-model'

export function onNavigatingTo(args) {

  let page = args.object;
  page.bindingContext = new HomeViewModel()
}

```
Also, keep in mind that while sending a sample project, you should send app folders as well as the main package.json file of the project.

**Comment by SebanSunny** [comment]
Hey Thanks a lot @tsonevn that helped out!!!
