### ISSUE TITLE
NgFor is not working in a subdirectory

### ISSUE THREAD

**Issue by ludo-f** [NativeScript/NativeScript#6215]
Hi,

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Please tell us how to recreate the issue in as much detail as possible.

The issue is visible here : https://play.nativescript.org/?template=play-ng&id=ep0OaC

I'm using a ngFor loop in "home" directory to display a list of fruit, it's working fine.
The same loop, in the subdirectory "level2" give me the next error : 

> Property binding ngForOf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations"

Thank you

**Comment by NickIliev** [comment]
@ludo-f declare the  `Level2Component` in `home.module.ts` so your binding and structural directives would work as expected.  

[https://play.nativescript.org/?template=play-ng&id=ep0OaC&v=2](https://play.nativescript.org/?template=play-ng&id=ep0OaC&v=2)
