### ISSUE TITLE
Not possible to build projects created by your schematics (rxjs-compact + zone.js errors)

### ISSUE THREAD

**Issue by montella1507** [NativeScript/NativeScript#6218]
TNS version:
√ Component nativescript has 4.2.2 version and is up to date.
√ Component tns-core-modules has 4.2.0 version and is up to date.
√ Component tns-android has 4.2.0 version and is up to date.

Source code created via:
ng new --collection=@nativescript/schematics project-name --shared
(https://docs.nativescript.org/code-sharing/intro)

tns run android - result:
`
platforms/android/app/build/intermediates/assets/debug/app/tns_modules/rxjs/src/operator/share.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/operator/share'.
platforms/android/app/build/intermediates/assets/debug/app/tns_modules/rxjs/src/operator/shareReplay.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/operator/shareReplay'.
platforms/android/app/build/intermediates/assets/debug/app/tns_modules/rxjs/src/operator/single.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/operator/single'.
platforms/android/app/build/intermediates/assets/debug/app/tns_modules/rxjs/src/operator/skip.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/operator/skip'.
platforms/android/app/build/intermediates/assets/debug/app/tns_modules/rxjs/src/operator/skipLast.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/operator/skipLast'.
platforms/android/app/build/intermediates/assets/debug/app/tns_modules/rxjs/src/operator/skipUntil.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/operator/skipUntil'.
platforms/android/app/build/intermediates/assets/debug/app/tns_modules/rxjs/src/operator/skipWhile.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/operator/skipWhile'.
platforms/android/app/build/intermediates/assets/debug/app/tns_modules/rxjs/src/operator/startWith.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/operator/startWith'.
platforms/android/app/build/intermediates/assets/debug/app/tns_modules/rxjs/src/operator/subscribeOn.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/operator/subscribeOn'.
platforms/android/app/build/intermediates/assets/debug/app/tns_modules/rxjs/src/operator/switch.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/operator/switch'.
platforms/android/app/src/main/assets/app/tns_modules/rxjs/operators/isEmpty.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/operators/isEmpty'.
platforms/android/app/src/main/assets/app/tns_modules/rxjs/operators/last.d.ts(1,15): error TS2307: e.bootstrapApp(Module.java:309)
..,..
`

I am able to fix errors with rxjs-compact by adding rxjs-compact to dependencies.. however there are other errors regarding zone.js like:

`
platforms/android/app/build/intermediates/assets/debug/app/tns_modules/zone.js/dist/zone.js.d.ts(134,11): error TS2451: Cannot redeclare block-scoped variable 'Zone'.
platforms/android/app/build/intermediates/assets/debug/app/tns_modules/zone.js/dist/zone.js.d.ts(423,14): error TS2300: Duplicate identifier 'HasTaskState'.
platforms/android/app/build/intermediates/assets/debug/app/tns_modules/zone.js/dist/zone.js.d.ts(432,14): error TS2300: Duplicate identifier 'TaskType'.
platforms/android/app/build/intermediates/assets/debug/app/tns_modules/zone.js/dist/zone.js.d.ts(436,14): error TS2300: Duplicate identifier 'TaskState'.
platforms/android/app/build/intermediates/assets/debug/app/tns_modules/zone.js/dist/zone.js.d.ts(535,15): error TS2451: Cannot redeclare block-scoped variable 'Zone'.
platforms/android/app/build/intermediates/assets/debug/app/tns_modules/zone.js/lib/common/promise.ts(203,13): error TS2322: Type 'ZoneAwarePromise<any>' is not assignable to type 'Promise<any>'.
`

you may update your schematics to fix this issue? 
Thank you.

**Comment by NickIliev** [comment]
@montella1507 I've tried to reproduce the issue to no avail (used[ this test project)](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/NativeScript/issue6218). Keep in mind that you should build/run your project by including the `--bundle` flag.

Try updating the required dependencies to the latest versions
```
npm i -g nativescript
npm i -g @angular/cli
npm i -g @nativescript/schematics
```

and then building with Webpack
```
tns run android --bundle
```

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-schematics#93
