### ISSUE TITLE
CSS Selector Issue/Question

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#622]
Does the CSS system currently support **Element.ClassName** or **Element#Id** or **Element Element** selectors?   Or does it only support each one of them totally basic or stand alone: **Element**, **.ClassName**, and **#id**.

 I'm running on NativeScript version 1.20 and the CSS selectors only seem to be extremely basic with no ability to chain selectors for specificity.   I've tried:
**Button#MyId**, **Button.MyClass**, and **StackLayout Button** as the rules; and none of them seem to be applied.   Is this a current limitation, or have I somehow messed up my environment...

**Comment by vakrilov** [comment]
Hi
The answer is no - there is still no support for more complex CSS selectors. The only supported ones are those listed [here](http://docs.nativescript.org/styling#supported-selectors).
There is already an issue for advanced CSS selectors #98. I'm going to close this one.

**Comment by NathanaelA** [comment]
Thanks for verifying what my findings were.   The docs you referenced which I studied before I put this question in does not state that you cannon combine the selectors.  It just says it supports those three selectors.   If you are coming from a html background; combining the selectors is a natural assumption when you say they are supported.   :grinning:        

Do you want me to make a bug report for the Docs; because the Docs really should say you cannot combine the selectors.

Awesome that their is a bug for this already.
