### ISSUE TITLE
Filter error Runtime in console - but it work !!

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#6220]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes 

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
I have create a filter with à `substr` function for make à short text when is long... the result is correctly binding but this error occurred on console `JS: Binding: Run-time error occured in file: undefined at line: undefined and column: undefined`

The problem comme from the filter `text={{ description | extrait }}` because when i remove `extrait` the errors disappears 

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
4.3.0-2018-08-07-12084
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
4.2.0
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
```json
"tns-android": {
"version": "4.3.0-2018-08-13-04"
},
"tns-ios": {
"version": "4.3.0-2018-08-17-02"
}
```
- Plugin(s): (look for the version number in the `package.json` file of your
project)
```json
"dependencies": {
		"base-64": "^0.1.0",
		"build-url": "^1.1.1",
		"email-validator": "^2.0.4",
		"moment": "^2.22.2",
		"nativescript-barcodescanner": "^2.7.7",
		"nativescript-fancyalert": "^1.2.0",
		"nativescript-fontawesome": "^1.0.0",
		"nativescript-i18n": "^0.2.4",
		"nativescript-intl": "^3.0.0",
		"nativescript-loading-indicator": "^2.4.0",
		"nativescript-socketio": "^3.0.2",
		"nativescript-statusbar": "^4.0.1",
		"nativescript-telephony": "^1.0.4",
		"nativescript-theme-core": "~1.0.4",
		"nativescript-toast": "^1.4.6",
		"nativescript-ui-listview": "^3.6.0",
		"tns-core-modules": "^4.2.0",
		"tslib": "^1.9.2",
		"utf8": "^3.0.0"
	},
	"devDependencies": {
		"babel-traverse": "6.26.0",
		"babel-types": "6.26.0",
		"babylon": "6.18.0",
		"lazy": "1.0.11",
		"nativescript-dev-sass": "^1.6.0",
		"nativescript-dev-typescript": "~0.7.0",
		"typescript": "~2.6.2"
	}
```

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

`shared/filters.ts`
```ts
export const extrait = (value, length = 40) => {
    if(value.length <= 40)
        return value;
    return value.substr(0, length) + "...";
};
```

`app.ts`
```ts
import * as application from 'tns-core-modules/application';
import * as applicationSettings from 'tns-core-modules/application-settings';
import { ago, currencyFormatter, deviceLanguage, extrait } from './shared/filters';

application.getResources().currencyFormatter = currencyFormatter;
application.getResources().ago = ago;
application.getResources().deviceLanguage = deviceLanguage;
application.getResources().extrait = extrait;
```

`main-page.ts`
```ts
var vm =  new Observable.Observable();
var items = new ObservableArray([]);
var page, lv: RadListView;
export async function onLoaded(args)
{
    page = args.object;
    var suggestionsList = await user.get('/requests/api/suggestions');
    items.push(suggestionsList);
    vm.set("dataItems", items);
    page.bindingContext = vm;   
}
```

`mai-page.xml`
```xml
<lv:RadListView.itemTemplate>
                    <StackLayout orientation="vertical" class="list-group-item suggestions-item-container" paddingLeft="5">
                        <GridLayout rows="auto, *" columns="*, 80" paddingTop="5" paddingBottom="5" paddingRight="5">
                            <Label row="0" col="0" text="{{ title }}" textWrap="true" marginBottom="5" class="list-group-item-heading suggestions-item-title"/>
                            <Label row="0" col="1" colSpan="2" text="{{ price | currencyFormatter }}" textWrap="false" class="suggestions-item-price" horizontalAlignment="right"/>
                            <Label row="1" col="0" text="{{ mainCourse | extrait }}" textWrap="true" class="text-muted suggestions-description"/>
                        </GridLayout>
                    </StackLayout>
</lv:RadListView.itemTemplate>
```

THANKS

**Comment by NickIliev** [comment]
@kefahB the issue is strictly related to the way NativeScript and the `RadListView` are working with data binding - the issue is not reproducible when using `ListView` for example. Still, the error happens due to a timing issue and won't crash or freeze your application. In fact, the binding with the filter is triggered right away and works as expected. as you have noticed so you can safely ignore this error.

To reduce the number of errors you could also use the  extended syntax for data boding

```
<Label text="{{ mainCourse, mainCourse | extrait }}" textWrap="true"/>
```
