### ISSUE TITLE
iOS New XCode release not allowing upload

### ISSUE THREAD

**Issue by Skintillion** [NativeScript/NativeScript#6221]
```
tns platform remove ios
tns platform add ios
cd platforms
cd ios
pod install
cd ..
cd ..
tns prepare ios --release
```

Open in XCode
Set Profiles
Archive

and when I try to upload to App Store I get the following.

```
ERROR ITMS-90680: "The binary you uploaded was invalid."
An unknown error occurred.

ERROR ITMS-90087: "Unsupported Architectures. The executable for myapp.app/app/tns_modules/nativescript-ui-listview/node_modules/nativescript-ui-core/platforms/ios/TNSCore.framework contains unsupported architectures '[x86_64, i386]'."
An unknown error occurred.

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'myapp.app/app/tns_modules/npm/node_modules/update-notifier/node_modules/boxen/node_modules/term-size/vendor/macos/term-size' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
An unknown error occurred.

ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'Telerik.TelerikUI.TNSCore' under the iOS application 'myapp.app'."
An unknown error occurred.

ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'myapp.app/app/tns_modules/nativescript-ui-listview/node_modules/nativescript-ui-core/platforms/ios/TNSCore.framework/TNSCore' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
An unknown error occurred.

ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'myapp.app/app/tns_modules/npm/node_modules/update-notifier/node_modules/boxen/node_modules/term-size/vendor/macos/term-size' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
An unknown error occurred.

ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."
An unknown error occurred.

WARNING ITMS-90080: "The executable 'Payload/myapp.app/app/tns_modules/nativescript-ui-listview/node_modules/nativescript-ui-core/platforms/ios/TNSCore.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library."
An unknown error occurred.
```

Any ideas? Thank you!

I did a successful upload last week of this

**Comment by Skintillion** [comment]
Problem is the nativescript-ui-listview is adding another nativescript-ui-core in its node_modules folder. Remove that and it works.

**Comment by rafaelcmrj** [comment]
I'm not using nativescript-ui-listview and I'm facing the same error

**Comment by NickIliev** [comment]
@rafaelcmrj post your `package.json` content

**Comment by rafaelcmrj** [comment]
@NickIliev 

`
{
  "description": "WeCancer",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "WeCancer",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.wecancer.wecancer",
    "tns-android": {
      "version": "4.2.0"
    },
    "tns-ios": {
      "version": "4.2.0"
    }
  },
  "scripts": {
    "start": "tns run android",
    "start:ios": "tns run ios",
    "clean": "rm -rf ./platforms && rm -rf ./hooks && rm -rf ./node_modules && chmod -R +x /usr/local/lib/node_modules/nativescript/",
    "lint": "tslint \"app/**/*.ts\"",
    "build:android:debug": "tns build android --debug",
    "build:android:release": "tns build android --bundle --env.aot --env.uglify --release --key-store-path ./wecancer_keystore.jks --key-store-password cura#2016 --key-store-alias wecancer --key-store-alias-password cura#2016"
  },
  "dependencies": {
    "@angular/animations": "~5.1.0",
    "@angular/common": "~5.1.0",
    "@angular/compiler": "~5.1.0",
    "@angular/core": "~5.1.0",
    "@angular/forms": "~5.1.0",
    "@angular/http": "~5.1.0",
    "@angular/platform-browser": "~5.1.0",
    "@angular/platform-browser-dynamic": "~5.1.0",
    "@angular/router": "~5.1.0",
    "moment": "^2.22.2",
    "nativescript-angular": "~5.1.0",
    "nativescript-camera": "^4.0.2",
    "nativescript-carousel": "~3.1.1",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-drop-down": "~3.2.2",
    "nativescript-fancyalert": "~1.1.2",
    "nativescript-fresco": "^3.0.7",
    "nativescript-gif": "^4.0.0",
    "nativescript-gradient": "~2.0.1",
    "nativescript-intercom-bridge": "^1.0.0",
    "nativescript-iqkeyboardmanager": "~1.0.1",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-local-notifications": "^2.0.5",
    "nativescript-localstorage": "~1.1.5",
    "nativescript-masked-text-field": "^2.0.2",
    "nativescript-modal-datetimepicker": "^1.1.3",
    "nativescript-ng-shadow": "^2.1.0",
    "nativescript-pdf-view": "^2.0.1",
    "nativescript-phone": "~1.3.1",
    "nativescript-plugin-firebase": "^5.0.5",
    "nativescript-social-share": "^1.5.0",
    "nativescript-status-bar": "^1.1.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-calendar": "^3.8.1",
    "nativescript-ui-sidedrawer": "3.5.1",
    "nativescript-urlhandler": "^1.2.2",
    "nearest-date": "^1.0.1",
    "node-sass": "~4.7.2",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~5.5.5",
    "tns-core-modules": "^4.2.0",
    "tns-platform-declarations": "^4.2.1",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~5.1.0",
    "@ngtools/webpack": "~1.9.1",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "codelyzer": "~4.0.2",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.3.5",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "^0.9.2",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "~6.0.6",
    "tslint": "~5.8.0",
    "typescript": "^2.7.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "^3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  },
  "author": "Wecancer inc."
}
`

**Comment by rafaelcmrj** [comment]
@NickIliev I'm guessing it's the nativescript-ui-calendar.. re-building now..

**Comment by NickIliev** [comment]
@rafaelcmrj  update `nativescript-ui-calendar` and `nativescript-ui-sidedrawer` to latest versions. I would also advise for updating all used plugins to latest.

As a side note remove tns-platform-declarations from the `dependencies` and install it as a `devDependency`
```
npm i tns-platform-declarations --save-dev
```

**Comment by Skintillion** [comment]
Open your app in xcode navigate to the calendar node_modules folder and remove the extra copy of core-ui there.

**Comment by rafaelcmrj** [comment]
@Skintillion it worked, thank you!!
