### ISSUE TITLE
How to set text of action bar on center or right side

### ISSUE THREAD

**Issue by mujibjan** [NativeScript/NativeScript#6223]
I need to set the app title on center whether ios or android in action bar and on the right side i need to put a slidedrawer button . please show me how to do it. 

<ActionBar title="Application" >

</ActionBar>

**Comment by NickIliev** [comment]
@mujibjan the repository is for logging issues, bugs and features related to NativeScript.
For how-to related questions please use the community channels like [NativeScript in StackOverflow ](https://stackoverflow.com/questions/tagged/nativescript) or [NativeScript community slack](https://nativescriptcommunity.slack.com/messages/general)

regarding your question - you could use a custom action bar view as demonstrated in the links below

 - Here is [a simple example on centered title ](https://gist.github.com/burkeholland/be0ce59306db9a51a5ba)

- Centered title and icons to the left (same for the right) -[ Angular example](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/main/main.component.html#L2-L6)
