### ISSUE TITLE
App size increased with --provision Distribution

### ISSUE THREAD

**Issue by tareknaj** [NativeScript/NativeScript#6224]
### Tell us about the problem
Application size (.IPA) is increasing dramatically when specifying a distribution provision profile while building

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.2.2
- Cross-platform modules: 4.2.0
- Runtime(s): 4.2.0

### Please tell us how to recreate the issue in as much detail as possible.
tns create nativescript-hello-world --template tns-template-blank-ts   
cd nativescript-hello-world
tns platform add ios
tns build ios --for-device --release --bundle --provision Development
tns build ios --for-device --release --bundle --provision Distribution 

you will notice size difference between the generated IPA, and this difference will be larger with bigger applications (30MB-> 80MB in my case)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3850
