### ISSUE TITLE
tns run output verbosity

### ISSUE THREAD

**Issue by erkanarslan** [NativeScript/NativeScript#6227]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes

### Tell us about the problem
When I run `tns run` console output contains lots of unrelated logs. I cannot see what my app outputs. I always get logs about network connectivity and other things. They never stop. One of the devices is an android emulator, other one is a real iPhone 7.

Here is a screenshot.

<img width="855" alt="ekran resmi 2018-08-29 18 02 56" src="https://user-images.githubusercontent.com/11949947/44796652-15075600-abb6-11e8-8e83-7d02c092360f.png">

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.1
- Cross-platform modules: 4.1.1
- Runtime(s): 4.1.3 for Android and 4.1.1 for iOS
- Plugin(s): Unrelated

### Please tell us how to recreate the issue in as much detail as possible.
Run `tns run` on a project. You will see the output.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3852
