### ISSUE TITLE
Accessing an iOS methods (same name different params) in an external iOS library

### ISSUE THREAD

**Issue by demetrio812** [NativeScript/NativeScript#6231]
Hello,
I'm writing a plugin to use a stomp library written in iOS (https://github.com/WrathChaos/StompClientLib).

Beside the initial compilation problems (solved forcing the swift version to 3) I have a problem accessing a specific method of the class `StompClientLib`: `openSocketWithURLRequest`

Debugging the app with VS Code and accessing the element in javascript, I can see all the other methods, the only one is missing is `openSocketWithURLRequest`.

Is it because there are 2 methods with the same name but different parameters?

```swift
    public func openSocketWithURLRequest(request: NSURLRequest, delegate: StompClientLibDelegate) {
        self.delegate = delegate
        self.urlRequest = request
        // Opening the socket
        openSocket()
    }
    
    public func openSocketWithURLRequest(request: NSURLRequest, delegate: StompClientLibDelegate, connectionHeaders: [String: String]?) {
        self.connectionHeaders = connectionHeaders
        openSocketWithURLRequest(request: request, delegate: delegate)
        self.connection = true
    }
```

How can I access them from Typescript?

I've checked the documentation and forums but didn't find anything...

Thanks,
Dem

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/ios-runtime#983
