### ISSUE TITLE
Ability to customize showModal() transitions

### ISSUE THREAD

**Issue by webleaf** [NativeScript/NativeScript#6232]
There are only `animated` argument of `showModal` method. Also animation on Android don't work (https://github.com/NativeScript/NativeScript/issues/5989).
In some cases I need overlap transition from bottom, in other cases I need overlap transition from right.
If you don't want to fix the bug https://github.com/NativeScript/NativeScript/issues/5989, may be it will be more common solution to add ability to implement custom transition for `showModal`, like it's done for page transitions.

**Comment by webleaf** [comment]
I think `showModal()` should have same interface as `navigate()` ([NavigationEntry](https://docs.nativescript.org/api-reference/interfaces/_ui_page_.navigateddata)). It's possible to set `context` and `bindingContext` when do `navigate()`, but it's not possible to set `bindingContext`, when do `showModal()`.

**Comment by mudlabs** [comment]
@webleaf not sure I understand?

Setting bindingContext from `navigate()`;
```js
 exports.onNavigatingTo = args => {
    const page = args.object;
    page.bindingContext = page.navigationContext
}
```
Setting bindingContext from `showModal()`;
```js
exports.onShowingModally = args => {
    const modal = args.object;
    modal.bindingContext = modal.context;
}
```

**Comment by webleaf** [comment]
@mudlabs setting `bindingContext` from `navigate()`:
```javascript
someFrame.navigate({
    moduleName: "path/to/your/page"
    bindingContext: myObservable,
    context: otherContext,
})
```
You can provide `NavigationEntry` interface to `navigate()` method. So If you use `onNavigatingTo` only for set `page.bindingContext`, you can avoid it.
Other use case is avoiding to use code-behind at all. That's what I do in my project.

**Comment by mudlabs** [comment]
@webleaf nice I hadn't realised you could do that.

**Comment by sserdyuk** [comment]
I second this request. We need eye candy to make real consumer facing apps. Not everybody's making corporate stuff.

**Comment by KhalifaGad** [comment]
I have kinda hacky stuff, wrapping my elements with AbsoluteLayout and give it a high top value like '800',
and in navigatedTo function make transition animation with the negative value of the top attribute.

**Comment by bradmartin** [comment]
```        // set the animations to use on showing and hiding the dialog
        window_1.setWindowAnimations(android.R.style.Animation_Dialog);``` putting this in the core-modules for view.android.js [here](https://github.com/NativeScript/NativeScript/blob/55dfe25938569edbec89255008e5ad9804901305/tns-core-modules/ui/core/view/view.android.ts#L198) will apply the current device/sdk default `Animation_Dialog` style to modals. Which will animate them as the default. 

@NickIliev @tsonevn - do you think this is suitable for now to at least fix the bug with no animations on the modals for android? If so, I'll be happy to provide a PR with this.

Ideally, long term, being able to customize the modal transition is ideal. I can probably help on android side of things there, but iOS would require some more thinking/work from myself.

**Comment by bbroereES** [comment]
This would be amazing!
