### ISSUE TITLE
listview inside a tabview doesn't strech out to fullscreen

### ISSUE THREAD

**Issue by janossuta** [NativeScript/NativeScript#6233]
Hi,

I have an issue with a listview inside a tabview it doesn't strech out to fullscreen.
I inserted a playground link below

### Which platform(s) does your issue occur on?
iOS

### Please tell us how to recreate the issue in as much detail as possible.
https://play.nativescript.org/?template=play-ng&id=FBvoVG

**Comment by janossuta** [comment]
Hi,

I tested on an Ipad mini 1 and an iPhone 6 emulator.
After you wrote I tested on an iPhone 6s and it worked so it must be version related issue.

**Comment by NickIliev** [comment]
@janossuta we are working on proper safe area support  - the issue is logged [here ](https://github.com/NativeScript/NativeScript/pull/6230)and is expected to become part of the next official release. Please keep an eye on the linked issue for additional details.
