### ISSUE TITLE
ENOENT: no such file or directory, lstat /nativescript/node_modules/fsevents/package.json'

### ISSUE THREAD

**Issue by IAMtheIAM** [NativeScript/NativeScript#6235]
Every single time I add, update, or remove any package.json dependency, nativescript fails to compile with this error

```
Executing before-prepareJSApp hook from /nativescript/hooks/before-prepareJSApp/nativescript-dev-webpack.js
Unable to apply changes on device: emulator-5554. Error is: ENOENT: no such file or directory, lstat /nativescript/node_modules/fsevents/package.json'.
```

I always have to delete node_modules and reinstall - why?

On Linux Mint 19

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) **4.2.3**
- Cross-platform modules: (check the 'version' attribute in the **4.2.0**
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project) **4.2.0**
- Plugin(s): (look for the version number in the `package.json` file of your
project)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3864
