### ISSUE TITLE
[Question] Check if --syncAllFiles flag was passed when running app

### ISSUE THREAD

**Issue by aaayushsingh** [NativeScript/NativeScript#6236]
I have a hook that needs to check if `tns run <platform> --syncAllFiles` was used or just `tns run <platform>`. Basically I need to check for `--syncAllFiles` flag. I couldn't find a resource for this.

or is there another way to execute a hook on full build and ignore otherwise?

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3865
