### ISSUE TITLE
Native Script vue Sidekick complie error : AAPT: error: resource drawable/icon

### ISSUE THREAD

**Issue by harshne** [NativeScript/NativeScript#6237]
### Which platform(s) does your issue occur on?
Android

I am using nativescript and vue to build a sample app. I've coded the app in nativescript playground.

When I preview it, it works just fine. I downloaded the app and used native script sidekick to build the android app. When creating the app it is showing an error:  AAPT: error: resource drawable/icon on researching it appears that the issue is a missing icon but I'm unable to find which directory it is that i need to place it. I would appreciate any help for it!

my app is at :
https://play.nativescript.org/?template=play-vue&id=11ouHV&v=15

here is the complete output of build :
#####
D:\projects\nativescript\rooms>tns build android
Skipping prepare.
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from D:\projects\nativescript\rooms\app\App_Resources\Android\app.gradle
         Applying settings from D:\projects\nativescript\rooms\app\App_Resources\Android\settings.json
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: D:\projects\nativescript\rooms\node_modules\nativescript-background-http\platforms\android\nativescript_background_http.aar
         + adding aar plugin dependency: D:\projects\nativescript\rooms\node_modules\nativescript-camera\platforms\android\nativescript_camera.aar
         + adding aar plugin dependency: D:\projects\nativescript\rooms\node_modules\nativescript-geolocation\platforms\android\nativescript_geolocation.aar
         + adding aar plugin dependency: D:\projects\nativescript\rooms\node_modules\nativescript-social-share\platforms\android\nativescript_social_share.aar
         + adding aar plugin dependency: D:\projects\nativescript\rooms\node_modules\nativescript-ui-autocomplete\platforms\android\TNSAutoComplete-release.aar
         + adding aar plugin dependency: D:\projects\nativescript\rooms\node_modules\nativescript-ui-calendar\platforms\android\TNSCalendar-release.aar
         + adding aar plugin dependency: D:\projects\nativescript\rooms\node_modules\nativescript-ui-chart\platforms\android\TNSChart-release.aar
         + adding aar plugin dependency: D:\projects\nativescript\rooms\node_modules\nativescript-ui-dataform\platforms\android\TNSDataForm-release.aar
         + adding aar plugin dependency: D:\projects\nativescript\rooms\node_modules\nativescript-ui-gauge\platforms\android\TNSGauge-release.aar
         + adding aar plugin dependency: D:\projects\nativescript\rooms\node_modules\nativescript-ui-listview\platforms\android\TNSListView-release.aar
         + adding aar plugin dependency: D:\projects\nativescript\rooms\node_modules\nativescript-ui-sidedrawer\platforms\android\TNSSideDrawer-release.aar
         + adding aar plugin dependency: D:\projects\nativescript\rooms\node_modules\nativescript-ui-core\platforms\android\TNSCore-release.aar
         + adding aar plugin dependency: D:\projects\nativescript\rooms\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
D:\projects\nativescript\rooms\platforms\android\app\build\intermediates\manifests\full\debug\AndroidManifest.xml:30: AAPT: error: resource drawable/icon (aka org.nativescript.playvue:drawable/icon) not found.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Command gradlew.bat failed with exit code 1

#######

**Comment by tsonevn** [comment]
Hi @harshne,
First of all, thank you for the provided sample project.
Currently, the NativeScript Vue project cannot be built with NativeScript SideKick. There is a new feature request logged [here](https://github.com/NativeScript/sidekick-feedback/issues/18) for enabling NativeScript Vue builds in SideKick. We are already working on this functionality, however, I can not commit to the exact time when the feature will be ready. For further info, I would suggest keeping track on the issue mentioned above.

**Comment by harshne** [comment]
thanks alot for your reply,

what is my alternative to build it with vue? as you can see a build from cli also fails. is there any way to make this playground app into apk?

**Comment by tsonevn** [comment]
Hi @harshne 
You can use vue cli to build your project. Check the vue documentation [here](https://nativescript-vue.org/en/docs/getting-started/quick-start/).
