### ISSUE TITLE
Numerical input type for dialogs and textfields

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#624]
Would be great to limit the keyboard to the phone number pad when only needing to enter digits in a text field or dialog.

For example, iOS would use `UIKeyboardTypeDecimalPad`.

**Comment by emiloberg** [comment]
According to the docs, the `TextField` inherits from `EditableTextBase` which has the `keyboardType` which you can set to `number`: http://docs.nativescript.org/ApiReference/ui/editable-text-base/EditableTextBase.html

**Comment by enchev** [comment]
Hey folks,

Indeed keyboardType is the right property, maybe however in this case you should use "phone" - more info here:
http://docs.nativescript.org/ApiReference/ui/enums/KeyboardType/README.html

HTH

**Comment by lscown** [comment]
Good to know :-)
