### ISSUE TITLE
Sidekick not starting under Windows 7 64 bit

### ISSUE THREAD

**Issue by WhiteTrashLord** [NativeScript/NativeScript#6244]
I hope it's okay to post this here.
I wanted to try out Sidekick. Sadly I really have big problems under Windows 7 64 bit.
It seems that Sidekick installed correctly.
My problem seems to be similar to this:
https://discourse.nativescript.org/t/cannot-accept-sidekick-terms-of-service-on-windows-10/4587

But I have the problem that I almost never see this Terms screen. I also cannot continue this dialog in case I can see it. Did you fix this problem or is there another problem?

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/sidekick-feedback#260
