### ISSUE TITLE
How to load icon fonts from a different directory than app/fonts?

### ISSUE THREAD

**Issue by kamok** [NativeScript/NativeScript#6247]
Currently, one loads fonts by adding the `.ttf` inside `app/fonts` directory.

And then declaring the corresponding css via:

```
.material-icon{
  font-family: 'MyFontFamily', myfontfamily; // iOS, Android
  font-size: 30;
}
```

I tried the method of declaring font family via src in CSS, as denoted here: https://stackoverflow.com/questions/21251760/font-face-use-absolute-path

But it seems like that doesn't work. Is there another way?

**Comment by tsonevn** [comment]
HI @kamok,
It seems that adding a custom fonts path is not supported at this time. You can check the feature request [here](https://github.com/NativeScript/NativeScript/issues/2609), where it is suggested to provide an option for using custom resource paths. You can provide more info if it is needed.
