### ISSUE TITLE
npm fails install of nativescript on btrfs

### ISSUE THREAD

**Issue by KatsuoRyuu** [NativeScript/NativeScript#6252]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes

### Tell us about the problem
My docker automated build server is failing to install NativeScript
```
npm install -g nativescript
```

### Which platform(s) does your issue occur on?
NPM 

### Please provide the following version numbers that your issue occurs with:
Fails on nativescript install through NPM

### Please tell us how to recreate the issue in as much detail as possible.
Create docker container
Install node using `curl -sL https://deb.nodesource.com/setup_10.x | bash -`
run `npm install -g nativescript`

Output:
```
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN nativescript No description
npm WARN nativescript No repository field.
npm WARN nativescript No README data
npm WARN nativescript No license field.

npm ERR! path /node_modules/.nativescript.DELETE/node_modules/sinon
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/node_modules/.nativescript.DELETE/node_modules/sinon' -> '/node_modules/nativescript/node_modules/sinon'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-10T11_06_17_384Z-debug.log
```

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Part of installation of nativescript so no code needed.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3880
