### ISSUE TITLE
Gradle Duplicate resources error with firebase dependency

### ISSUE THREAD

**Issue by jpierront** [NativeScript/NativeScript#6254]
### Tell us about the problem
When we add "firebase" to package.json, the Android gradle build fail.
```
Execution failed for task ':app:mergeDebugAssets'.
[app/tns_modules/bytebuffer/dist/bytebuffer.min.js] ... Error: Duplicate resources
[app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] ... Error: Duplicate resources
[app/tns_modules/long/dist/long.min.js]  ... Error: Duplicate resources
[app/tns_modules/protobufjs/dist/protobuf-light.min.js]  ... Error: Duplicate resources
[app/tns_modules/protobufjs/dist/protobuf.min.js]  ... Error: Duplicate resources
```
I try to migrate my Angular Web App to Nativescript+Web and I need web firebase version for my web version.

The problem occurs even on the "Angular & TypeScript Drawer navigation" demo.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.2.3
- Cross-platform modules: 4.2.0
- Runtime(s): 4.2.0
- Plugin(s):
```
"dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.1.0",
    "firebase": "^5.4.2",
    "nativescript-angular": "~6.1.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-sidedrawer": "~4.2.0",
    "tns-core-modules": "~4.2.0",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.2.0",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "codelyzer": "~4.3.0",
    "nativescript-dev-sass": "~1.6.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.15.0",
    "tslint": "~5.11.0",
    "typescript": "~2.7.2",
    "@angular/compiler-cli": "~6.1.0",
    "@ngtools/webpack": "~6.1.0"
  }
```
### Please tell us how to recreate the issue in as much detail as possible.
1) Add "firebase": "^5.4.2" to your package.json
2) Clear your platforms/android directory
3) Run tns run android --emulator

**Comment by NickIliev** [comment]
@jpierront use the NativeScript plugin that enables firebase. Its called [nativescript-plugin-firebase](https://github.com/EddyVerbruggen/nativescript-plugin-firebase) and is accessible via npm as well. The wrapper you are using is not supportinhg NativeScript and has only a limited set of fgeatures enabled (database and storage)

The plugin supports a lot more features compared to the wrapper you are using.
Here is the list of features which are supported by n**ativescript-plugin-firebase**

- Realtime Database
- Firestore
- Authentication
- Remote Config
- Cloud Messaging
- Storage
- Crash Reporting / Crashlytics
- Analytics
- Invites and Dynamic Links
- AdMob
- ML Kit

**Comment by jpierront** [comment]
@NickIliev Is it compatible with "ng serve" too ? (Web version)

**Comment by NickIliev** [comment]
@jpierront good question - the answer is no. I will try to reproduce the issue and provide a solution - can you please post a link to the Angular template you are using ("Angular & TypeScript Drawer navigation")

**Comment by NickIliev** [comment]
@jpierront indeed the `firebase` packet is not compatible with NativeScript - keep track on this issue for a possible solution to use firebase with web and mobile shared applications.

Are you using [code sharing via Angular schematics](https://docs.nativescript.org/angular/code-sharing/intro) to create your shared project?

**Comment by jpierront** [comment]
Yes I use it but there is only one package.json for both (App & Web)
Any way to create a white/back list for tns_modules ? (To not take all nodes_modules content)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-schematics#115
