### ISSUE TITLE
Save photo from url to image gallery(camera roll) - IOS

### ISSUE THREAD

**Issue by SugumarParthi** [NativeScript/NativeScript#6256]
I want save image from url(application) to iPhone image gallery(camera roll).
is it possible?
i tried but that's not working. 
can u please help me
- **Image not saving in the photo album.**

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0
- Cross-platform modules: 
        "tns-ios": {"version": "4.1.1"}
	"dependencies": {
		"moment": "^2.22.2",
		"nativescript-background-http": "^3.2.7",
		"nativescript-camera": "^4.0.2",
		"nativescript-grid-view": "^4.1.0",
		"nativescript-image-cache": "^1.1.6",
		"nativescript-imagecropper": "^1.0.4",
		"nativescript-imagepicker": "^6.0.2",
		"nativescript-iqkeyboardmanager": "^1.3.0",
		"nativescript-loading-indicator": "^2.4.0",
		"nativescript-social-login": "^4.0.1",
		"nativescript-theme-core": "^1.0.4",
		"nativescript-twitter": "^2.0.0",
		"tns-core-modules": "^4.1.0",
		"tns-platform-declarations": "2.2.0"
	}
}

### Here is my code:

imageSource.fromUrl(imageUrl).then(function (ImageSource) {
            let folder = fileSystemModule.knownFolders.documents().path;
            let path = fileSystemModule.path.join(folder, "Image"+new Date().getTime()+".jpeg");
            let saved = ImageSource.saveToFile(path, "jpeg");
            if (saved) {
                ImageSource.saveToAlbum(imageSource, false, false, function() {
                    alert('The photo was saved!');
                 });
            }
        }).catch(err => {
            loader.hide();
        });

**Comment by tsonevn** [comment]
Hi @SugumarParthi,
You can check the provided solution for iOS in [this](https://discourse.nativescript.org/t/how-to-save-an-imagesource-object-to-the-devices-photo-library-on-both-ios-and-android/1126) NativeScript forum thread. In the given sample is demonstrated how to access the native methods needed for saving the image in the Gallery. Keep in mind that before saving the image, you should request permission to access the photo gallery. To get the needed permission you should add the following two lines:
```
<key>NSPhotoLibraryUsageDescription</key>
	<string>Requires access to photo library.</string>
```
in the `App_Resources/iOS/Info.plist` file and to request user authorization with the following code:
```
PHPhotoLibrary.requestAuthorization((result)=> {
        if (result === PHAuthorizationStatus.Authorized) {
........
        } else {
            console.log("not authorized")
        }
    });
```


For your convenience, I am attaching sample project, where it is demonstrated how to request the permissions and to save the image.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/2373765/Archive.zip)

**Comment by SugumarParthi** [comment]
HI @tsonevn 
Thank you.
Its working perfectly.
