### ISSUE TITLE
Routing zone error with ngrx usage

### ISSUE THREAD

**Issue by pnahtanoj** [NativeScript/NativeScript#6257]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Indeed.  I did look for a dupe, as well.

### Tell us about the problem
When routing to a previously visited page (with and ngrx subscription), I'm getting a zone error

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)

$ tns --version
4.1.2

- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)

"tns-core-modules": "~4.2.0",

- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)

"tns-ios": {
       "version": "4.1.1"
}

- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
I had issues getting a ngrx integrated into playground, so I created a small application here:
https://github.com/pnahtanoj/routing-error-example

You'll see the error if you got to Page1, then click Add One!

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

See previous item

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1511
