### ISSUE TITLE
CONSOLE ERROR [native code]: ERROR TypeError: undefined is not an object (evaluating 'frame_1.topmost().ios')

### ISSUE THREAD

**Issue by felicks** [NativeScript/NativeScript#6259]
I've tried to update a nativescript project. I can successfully build the project but run into the following xCode error message:

2018-09-12 10:35:16.580715+0200 HelloWorld[3200:783878] CONSOLE ERROR [native code]: ERROR TypeError: undefined is not an object (evaluating 'frame_1.topmost().ios')

package.json:

{
  "nativescript": {
    "id": "org.nativescript.HelloWorld",
    "tns-android": {
      "version": "4.2.0"
    },
    "tns-ios": {
      "version": "4.2.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.1.0",
    "nativescript-angular": "~6.1.0",
    "nativescript-carousel": "^4.0.2",
    "nativescript-email": "^1.5.3",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-sidedrawer": "^4.3.0",
    "node-sass": "^4.9.3",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^6.3.2",
    "tns-core-modules": "~4.2.0",
    "webpack": "^4.17.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~6.1.0",
    "@ngtools/webpack": "~6.2.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "^0.16.0",
    "typescript": "~2.7.2"
  },
  "readme": "NativeScript Application"
}

**Comment by tsonevn** [comment]
Hi @felicks,
Can you provide more info about the steps, which you are using while building the app? How did you build it with `tns run ios` or `tns run ios --bundle` command? It will help if you give us sample project, which can be used for debugging or at least some code fragments, which you think that can be responsible for the error. 

In the meantime, try to clear up the project while following the below-attached steps and check if you will be able to recreate the problem.
1. delete `node_modules`, `platforms`, `hooks` folders and `package-lock.json` file. 
2. run `npm cache clear` command 
3. rebuild the project with `tns run ios`

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1513
