### ISSUE TITLE
Change APP Name under ALL APPS not working ?

### ISSUE THREAD

**Issue by MopheusDG** [NativeScript/NativeScript#6262]
Hi, I've created a STRINGS.XML under values to change my APP_NAME. It works fine under the application Icon but when I do SETTINGS/APPS in the Emulator to "remove/uninstall" the app, I can still see my old app name. I attached an image (I just see my old name there as "API Demos" for example).

This is my XML, does anyone know if there's an additional value I should change that I'm not aware ?

`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">My APP</string>
    <string name="title_activity_kimera">My APP</string>
</resources>
`

![where](https://user-images.githubusercontent.com/19177037/45491568-61b76900-b740-11e8-87d7-a76ce1db7d27.jpg)

**Comment by NickIliev** [comment]
@MopheusDG  Changing the app_name should be enough to change the name of your application in the settings.  Can you let me know on what API level you are experiencing this issue (what is the device/ emulator used for tests)

**Comment by MopheusDG** [comment]
Hi @NickIliev, I only tested on the Android Emulator so far (I could post an update tomorrow on a real phone too if needed). The emulator is running Android 7.1.1 / API Level 25.

I'm also running NS 4.2.2 with tns-modules 4.2.0 and tns-android 4.2.0 in case that helps.

Thanks.

**Comment by MopheusDG** [comment]
After removing platform, doing a full build/clean, etc... it seems the name is now correctly applied to the settings page too. Sorry, for some reason was not applying before but now it's fine. I close the issue and leave just for reference if someone get's stuck on this issue too.

Thanks.
