### ISSUE TITLE
tns-template-tab-navigation-ng, trying to use this template 

### ISSUE THREAD

**Issue by Toq97** [NativeScript/NativeScript#6263]
i'm new to nativesript and i need to use a welcome page without tab navigation and the next page will be the tabview. i tried to change the routing but how can i use redirectto in second page?

Please help me, thanks

**Comment by tsonevn** [comment]
HI @Toq97,
The `tns-template-tab-navigation-ng` template demonstrates, how to use the TabView component as a root in a NativeScript Angular project. If you need to define your custom initial page I would suggest creating a new project via our default Ns Angular template(`tns create appName --ng`). In the newly created project, you can define the welcome page and then navigate to the one with the TabView. Check out the attached sample.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2382051/Archive.zip)

For further question please use [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript). This repository is used only for bug reporting and feature request.
Thank you in advance for your cooperation.

**Comment by Toq97** [comment]
Thanks @tsonevn. you save my day
