### ISSUE TITLE
CSS Padding support - regression?

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#627]
Is their some reason why in the new version (v1.20) of NativeScript padding is only used on Layouts.   Shouldn't this actually be put back on the View component and control the internal padding of the component.   If I apply a border-radius to a button; their is no way to make the button look nice without manually messing with the height and width now.  In normal CSS you can apply padding to a element/component and it effects the internal dimensions..

**Comment by hshristov** [comment]
Padding was wrongly exposed on View class but was never working on anything other than Layout. It could be easily implemented for Android but not for iOS and Windows Universal.
For 1.3 we will expose padding on Button, Label, TextField, TextView.

**Comment by NathanaelA** [comment]
@hshristov your statement left me a little confused.  Is padding on the Button going to work on iOS/WU, or just Android?    
Are you planning on putting it only on Button(& the others you listed), or putting it back on view as a protected property, so that other third party components might also extend and use it)?

**Comment by hshristov** [comment]
@NathanaelA Prior 1.2 padding was exposed on View but was working only if your view was Layout. With 1.3.0 we are going to expose Padding only on the listed components and make it work on all supported platforms.

**Comment by rclai** [comment]
Uh.. how do we apply padding on a `Label`? It seems like it's not possible.
