### ISSUE TITLE
Event "pageLoaded" not firing

### ISSUE THREAD

**Issue by w3hr** [NativeScript/NativeScript#6273]
I will bind a viewModel (var viewModel = new Observable();) to a Page, in the Documentation its like:

`<Page class="page" loaded="pageLoaded" navigatingTo="onNavigatingTo" xmlns="http://schemas.nativescript.org/tns.xsd">`

and in script:

```
function pageLoaded(args) {
    var page = args.object;
    console.log(page);
    page.viewModel = viewModel;
    viewModel.set("LastGetNews", "test");
}
exports.pageLoaded = pageLoaded;
```

Also when i add a Function to Class of the Compontent like

```
    HomeComponent.prototype.pageLoaded = function (args) {
      var page = args.object;

      page.viewModel = viewModel;

  viewModel.set("LastGetNews", "test");

      console.log(page);
    };
```

its also not firing ..

what doing im wrong?

**Comment by w3hr** [comment]
thank u guys for answering me.

```
var frameModule = require("ui/frame");
var HomeViewModel = require("./home-view-model");

var viewModel = new HomeViewModel();

function pageLoaded(args) {
  var page = args.object;
  console.log(page);

  page.bindingContext = viewModel;

  viewModel.set("LastGetNews", "test");
}
exports.pageLoaded = pageLoaded;
```

yes this will work in the demo and on my smartphone, thank you for creating it.
in this case i get it to work also, before i create this issue.

my problem is, when im using routes or 

```
@Component({
    moduleId: module.id,
    selector: "home",
    templateUrl: './home.html'
})
export class HomeComponent {}
```
the `<Page loaded="pageLoaded">` will not trigger. (no matter that i use *.html or *.xml files)


in the evening i will create a sample app to demonstrate that

**Comment by NickIliev** [comment]
@w3hr the `Page` tag should not be used in an Angular based application nor the MVVM binding concept. Use the Angular approach for data binding as explained [in this documentation article (NativeScript docs)](https://docs.nativescript.org/angular/core-concepts/angular-data-binding).

Notice that NativeScript Core and NativeScript Angular are two different flavors that have their specifics. In the Angular based application use the Angular related documentation ([bottom left of the documentation](https://docs.nativescript.org/)).
