### ISSUE TITLE
data binding template selector in ListView fails

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#6280]
_From @jokro on September 19, 2018 7:13_

In [Playground Nativescript](https://play.nativescript.org/?template=play-js&id=h0dxyU&v=23) I have adapted the ListView example with multiple templates. Two buttons show the age of two persons. The age of each person selects a template, hence one button appears red the other green.

A tap of the button changes its age. The new age is correctly displayed. Hence databinding is working for text. The color is not changing accordingly, meaning that the changed age is not propagated to the itemselector key.

_Copied from original issue: NativeScript/nativescript-cli#3908_

**Comment by NickIliev** [comment]
@jokro the data binding works with the item template selector function. Here is [a simplified Playground app](https://play.nativescript.org/?template=play-js&id=h0dxyU&v=24) demonstrating the case.

However, there is a bug when trying to access the item at index 0 which is logged [here](https://github.com/NativeScript/nativescript-angular/issues/1479).

Closing as the main issue is resolved and the bug is logged in the linked issue.

**Comment by jokro** [comment]
Hi Nickliev, thx. One question. The teplate effect can be imitated by  using a layout containers and setting visibility to hide and and show alternative containers.  I am doing this now for the zero index item.  I wonder whether I should use this solution for the other items too. Is there any negative consequence (memory, speed) if I would do this ?
