### ISSUE TITLE
remove an item from navigation history without clearing the whole history

### ISSUE THREAD

**Issue by janossuta** [NativeScript/NativeScript#6285]
Hi,

I would like to remove an item from navigation history.

I have a route like this

`Homepage -> Comment list -> Add comment`

After you add a comment it navigates back to `Comment list`
So the navigation history is this:
`Homepage -> Comment list -> Add comment -> Comment list`

What I want is to prevent navigation back from `Comment list` to `Add comment` when pressing the back button and jump to `Homepage` instead

`Comment list  -> (back button) skip Add comment -> Homepage` 

Here is a simple example:
https://play.nativescript.org/?template=play-ng&id=zhyj9e

### Which platform(s) does your issue occur on?
Both

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1525
