### ISSUE TITLE
Sidekick is not starting on windows 10

### ISSUE THREAD

**Issue by yashwp** [NativeScript/NativeScript#6296]
I've freshly installed sidekick for the first time on my windows 10 laptop. It was installed successfully but when I double click on the application icon, splash screen loads for 4-5 seconds and disappears and nothing happens after that.

I've also install its latest CLI version `4.2.4`. Still, the problem is coming. What to do, to get it started?

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/sidekick-feedback#265
