### ISSUE TITLE
RSA Encryption

### ISSUE THREAD

**Issue by nisharamesh83** [NativeScript/NativeScript#6299]
### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there.

**Comment by nisharamesh83** [comment]
RSA encryption not possible in Nativescript.
Try to implement jsrasign method.But the encrypted data cannot be decrypted  in server side

**Comment by NickIliev** [comment]
@nisharamesh83 the RSA was requested as a feature but a solution was provided some time ago [in this thread](https://github.com/NativeScript/NativeScript/issues/4156).

Closing as duplicate and as not enough information provided to reproduce an issue.

**Comment by NathanaelA** [comment]
@nisharamesh83 - Actually RSA encryption on Android is easily done; I just finished a plugin for a client that did AES encryption and RSA was one of the other possibilities we were discussing and supported by the OS.
Haven't checked into iOS yet.    However, why not just use one of the JavaScript based Crypto libraries.
