### ISSUE TITLE
Video Recorder Component

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#63]
_From @ligaz on March 21, 2015 6:46_

Forum thread: https://groups.google.com/forum/#!topic/nativescript/7_qwzUsp578

_Copied from original issue: NativeScript/cross-platform-modules#212_

**Comment by N3ll** [comment]
You can vote for the idea here https://nativescript.ideas.aha.io/ideas/NS-I-66.

**Comment by mikeres0** [comment]
+1

Has anyone started writing a plugin for this yet?

**Comment by victorsosa** [comment]
Hi,

Actually there is one:
https://github.com/triniwiz/nativescript-videorecorder

*But right now only support Android.

**Comment by triniwiz** [comment]
Both platforms are now  supported :smile:

**Comment by enchev** [comment]
Great work @triniwiz! I'm closing this.

**Comment by tskweres** [comment]
Does it support IOS? are there any docs?
