### ISSUE TITLE
Android with java file

### ISSUE THREAD

**Issue by Fabiyo-90** [NativeScript/NativeScript#6301]
I use nativescript-vue@2.0.0 and I wanna know how can I add a .java file in my nativescript project.

I use nativescript@4.+

**Comment by NickIliev** [comment]
At this very moment, a viable option is to create an Android library from your java file.

The possibility to directly use java files in NativeScript is logged as a feature [here](https://github.com/NativeScript/android-runtime/issues/1172)

**Comment by Fabiyo-90** [comment]
I found the solution !
Just adding your java files in "your_project\app\App_Resources\Android\src\main\java" 
then call the class in your js or ts file and Nativescript will take care to send you back your object.
nativescript is the simplest, just understand the logic.
Nativescript is the best

**Comment by farfromrefug** [comment]
@Fabiyo-90 can you post an example app? This does not seem to work for me. Thanks
