### ISSUE TITLE
Second change of .css file in android results in blank screen

### ISSUE THREAD

**Issue by vtrifonov** [NativeScript/NativeScript#6302]
When running `tns run android` every second change in a **.css** file results in a blank screen. This happens only with tns-core-modules@next, it works with tns-core-modules@latest

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 5.0.0-2018-09-25-12302
- Cross-platform modules: 4.3.0-2018-09-20-01
- Runtime(s): 4.2.0

### Please tell us how to recreate the issue in as much detail as possible.
Follow the steps to reproduce it:
``` bash
tns create test
cd test
npm i tns-core-modules@next
tns run android
## change font-size value in app/app.css file once and wait for the changes to be synced
## changing the font-size second time will result in a blank screen
```

**Comment by vchimev** [comment]
Latest working versions:
```
tns-core-modules@4.3.0-2018-07-31-01
tns-core-modules-widgets@4.3.0-2018-07-25-01
```
