### ISSUE TITLE
ERROR MESSAGE css.lint.unknown property horizontal-alignment

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#6303]
Visual Studio with NativeScript on Windows 10, all most recent versions, building for android

If in css file I define:

.center {horizontal-alignment:center;}  
OR
 .center {horizontal-align:center;} 
  
then VisualStudio raises a non-fatal PROBLEM: **css.lint.unknown property horizontal-align(ment).**

The app does center as expected. In PlayGround the error flag is not raised. 
The error although not fatal is disturbing,

I tried to find the file css.lint but could not find it.

**Comment by tsonevn** [comment]
Hi @jokro,
Following the NativeScript [docs](https://docs.nativescript.org/ui/styling#supported-css-properties), you should use `horizontal-align` when you need to set up the property via CSS file. Regarding the mentioned issue with centring the elements in the app. Can you provide a sample project, which shows the problem? 
It will also help if you provide more info, what you are trying to achieve as a final result.

**Comment by NickIliev** [comment]
You Visual Studio is probably using CSSLint and if so you could create your own rule for the properties that are not included [https://github.com/CSSLint/csslint/wiki/Working-with-Rules](https://github.com/CSSLint/csslint/wiki/Working-with-Rules)

**Comment by jokro** [comment]
ThxOp 26 sep. 2018 13:32 schreef Nick Iliev <notifications@github.com>:You Visual Studio is probably using CSSLint and if so you could create your own rule for the properties that are not included https://github.com/CSSLint/csslint/wiki/Working-with-Rules

**Comment by jokro** [comment]
1. I do not think CSSLint is causing the problem. The standard NativeScript sample in [playground ](https://play.nativescript.org/?template=play-tsc&id=Y4fVGt&v=16) from market.nativescript.org also shows the error. In app/app.css  .center{horizontal-align:center;} shows a green line below horizontal-align. When the mousepointer is hovering above it, it shows [css] unknown property horizontal-align.

2. An additional question: does NativeScript follow css naming conventions ? In that case horizontal-align should be horizontal-alignment in stead. This also would be consitent with javascript horizontalAlignment (see NativeScript documentation). The situation now is disturbing at least.

3. As separate question, the abobe example playground  presented in [market.nativescript.org](https://market.nativescript.org/?tab=samples&framework=core&category=forms%20and%20data) as (vanilla) javascript example. I see *.ts files however. Does this mean it is Typescript, not javascript ? I have been searching the internet for an example of sidedrawer with vanilla javasript.

**Comment by NickIliev** [comment]
@jokro in CSS there are the [text-align`](https://www.w3schools.com/cssref/pr_text_text-align.asp) and [`vertical-align`](https://www.w3schools.com/cssref/pr_pos_vertical-align.asp) and we are following this naming convention for the custom CSS properties introduced in NativeScript like `horizontal-align` and `vertical-align`. In JavaScript / TypeScript the full naming is preserved which is indeed not consistent with the CSS naming but makes more sense as lexical meaning.

The Playground is checking the CSS using standard CSS parser and this is why as expected the custom properties that are not part of CSS specifications will be underlined. Naming the CSS variant of the NativeScript `textAlignment` with the standard CSS convention (`text-align`) is confirming that won't be marked as unrecognized property.

Regarding the JS version of the sidedrawer scenario - the easiest approach would be to download the TypeScript demo and transpile it to plain JavaScript with `tsc`. Then you can use the output JavaScript source.

**Comment by jokro** [comment]
ThxOp 28 sep. 2018 15:03 schreef Nick Iliev <notifications@github.com>:@jokro in CSS there are the [text-align](https://www.w3schools.com/cssref/pr_text_text-align.asp) and [vertical-align](https://www.w3schools.com/cssref/pr_pos_vertical-align.asp) and we are following this naming convention for the custom CSS properties introduced in NativeScript likehorizontal-alignandvertical-align`. In JavaScript / TypeScript the full naming is preserved which is indeed not consistent with the CSS naming but makes more sense as lexical meaning.
The Playground is checking the CSS using standard CSS parser and this is why as expected the custom properties that are not part of CSS specifications will be underlined. Naming the CSS variant of the NativeScript textAlignment with the standard CSS convention (text-align) is confirming that won't be marked as unrecognized property.
Regarding the JS version of the sidedrawer scenario - the easiest approach would be to download the TypeScript demo and transpile it to plain JavaScript with tsc. Then you can use the output JavaScript source.

**Comment by fstuparu** [comment]
In Visual Studio Code (at least in our version 1.35.1), we made the warning disappear by adding this property to the user settings (%Home%\AppData\Roaming\Code\User\settings.json) :

`{
    "scss.lint.validProperties": [ "horizontal-align" ]
}`
