### ISSUE TITLE
Nativescript-Vue: Cannot compile /data/data/org.nativescript.application/files/app/main.js

### ISSUE THREAD

**Issue by RaisinBread42** [NativeScript/NativeScript#6304]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
yes

### Tell us about the problem
App failed to compile for Android Emulator. The error message received is:
```

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Cannot compile /data/data/org.nativescript.application/files/app/main.js

SyntaxError: Unexpected identifier
File: "file:///data/data/org.nativescript.application/files/app/main.js, line: 1, column: 67

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266


SyntaxError: Unexpected identifier
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: com.tns.NativeScriptException: 

Cannot compile /data/data/org.nativescript.application/files/app/main.js

SyntaxError: Unexpected identifier
File: "file:///data/data/org.nativescript.application/files/app/main.js, line: 1, column: 67

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266


SyntaxError: Unexpected identifier
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266


	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:553)
	at com.tns.Runtime.run(Runtime.java:545)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
	... 8 more

```

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.2.4
- Cross-platform modules: ^4.2.0
- Runtime(s): tns-android 4.2.0
- Plugin(s): 
"dependencies": {
    "vuex": "^3.0.1",
    "@vue/devtools": "5.0.0-beta.3",
    "nativescript-socket.io": "^0.9.0",
    "nativescript-vue-devtools": "^1.0.0",
    "nativescript-toast": "^1.4.6",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-vue": "^2.0.0",
    "tns-core-modules": "^4.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.2",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.2",
    "css-hot-loader": "^1.4.2",
    "css-loader": "^1.0.0",
    "lazy": "1.0.11",
    "mini-css-extract-plugin": "^0.4.1",
    "nativescript-dev-webpack": "^0.17.0-2018-09-12-01",
    "nativescript-vue-template-compiler": "^2.0.0-alpha.3",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.1.0",
    "uglifyjs-webpack-plugin": "~1.2.7",
    "vue-loader": "^15.2.6",
    "webpack": "^4.16.4",
    "webpack-bundle-analyzer": "~2.13.1",
    "webpack-cli": "^3.1.0"
  }

### Please tell us how to recreate the issue in as much detail as possible.
Follow the documentation to create a simple project: https://nativescript-vue.org/en/docs/getting-started/quick-start/

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
The code that comes when running vue init command.

**Comment by tsonevn** [comment]
This issue was moved to nativescript-vue/nativescript-vue#335
