### ISSUE TITLE
ReferenceError: Can't find variable: __makeTemplateObject

### ISSUE THREAD

**Issue by fhackenb** [NativeScript/NativeScript#6306]
I'm attempting to use the graphql-tag library and am getting some issues that may be caused by some version compatibility issues. My package.json:

```
{
    "nativescript": {
        "id": "org.nativescript.nativescriptappsync3",
        "tns-android": {
            "version": "4.2.0"
        },
        "tns-ios": {
            "version": "4.2.0"
        }
    },
    "description": "NativeScript Application",
    "license": "SEE LICENSE IN <your-license-filename>",
    "repository": "<fill-your-repository-here>",
    "dependencies": {
        "@angular/animations": "~6.1.0",
        "@angular/common": "~6.1.0",
        "@angular/compiler": "~6.1.0",
        "@angular/core": "~6.1.0",
        "@angular/forms": "~6.1.0",
        "@angular/http": "~6.1.0",
        "@angular/platform-browser": "~6.1.0",
        "@angular/platform-browser-dynamic": "~6.1.0",
        "@angular/router": "~6.1.0",
        "aws-appsync": "^1.3.3",
        "graphql": "^0.11.7",
        "graphql-tag": "^2.5.0",
        "nativescript-angular": "~6.1.0",
        "nativescript-dev-typescript": "^0.7.0",
        "nativescript-nodeify": "^0.8.0",
        "nativescript-theme-core": "~1.0.4",
        "reflect-metadata": "~0.1.8",
        "rxjs": "^6.0.0",
        "tns-core-modules": "^4.2.1",
        "typed-graphql": "^1.0.2",
        "zone.js": "^0.8.26"
    },
    "devDependencies": {
        "typescript": "^2.7.2"
    },
    "readme": "NativeScript Application"
}
```

My error:

> ***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10428cc1f NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool, bool)
2   0x1042c1caf -[TNSRuntime executeModule:referredBy:]
3   0x103cf31e3 main
4   0x107c69551 start
JavaScript stack trace:
1   anonymous@file:///app/graphql/queries/getAllPosts.js:4:101
2   evaluate@[native code]
3   moduleEvaluation@[native code]
4   @[native code]
5   promiseReactionJob@[native code]
6   require@[native code]
7   anonymous@file:///app/item/items.component.js:14:28
8   evaluate@[native code]
9   moduleEvaluation@[native code]
10  @[native code]
11  promiseReactionJob@[native code]
12  require@[native code]
13  anonymous@file:///app/app.routing.js:5:32
14  evaluate@[native code]
15  moduleEvaluation@[native code]
16  @[native code]
17  promiseReactionJob@[native code]
18  require@[native code]
19  anonymous@file:///app/app.module.js:5:28
20  evaluate@[native code]
21  moduleEvaluation@[native code]
22  @[native code]
23  promiseReactionJob@[native code]
24  require@[native code]
25  anonymous@file:///app/main.js:5:27
26  evaluate@[native code]
27  moduleEvaluation@[native code]
28  @[native code]
29  promiseReactionJob@[native code]
JavaScript error:
file:///app/graphql/queries/getAllPosts.js:4:101: JS ERROR ReferenceError: Can't find variable: __makeTemplateObject

I can make a repo to demonstrate this issue if anyone would be interested in trying to reproduce it

**Comment by tsonevn** [comment]
Hi @fhackenb,
I have made a little research and found [this](https://medium.com/@iguissouma/using-graphql-inside-an-angular-native-nativescript-app-using-apollo-756a344cd486) article, which might help in setting up `graphql-tag` in your NativeScript project.
Keep in mind that currently `graphql ` is not supported officially in NativeScript and we can not confirm that the plugin and the related packages will work as expected. The problem also does not seem to be connected to the core framework. Regarding that, I would suggest moving the conversation in [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript). 

Let me know, if I am missing something or if you think that the problem is caused by an issue in the modules.

BR,
@tsonevn
