### ISSUE TITLE
[Angular] Repeater widget documentation missing

### ISSUE THREAD

**Issue by cmckni3** [NativeScript/NativeScript#6308]
I would expect https://docs.nativescript.org/angular/ui/ng-ui-widgets/repeater to have the documentation for repeater widget with Angular.

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

Yes

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

Missing UI widget documentation for `Repeater`

### Which platform(s) does your issue occur on?

Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.2.4
- Cross-platform modules: 4.2.1
- Runtime(s): 4.2.0

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

No

**Comment by tsonevn** [comment]
Hi @cmckni3,
In case you are using NativeScript Angular, you can use ngFor directive, which is the angular way to display the info in the app as the Repeater. Also, it is the recommended way to show a collection of items in NativeScript Angular app. An example can be found [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/ng-ui-widgets-category/ng-directives/ngfor-directive).

**Comment by tsonevn** [comment]
Hi @cmckni3,
Can you provide a sample project, which demonstrates the issue, which you are facing with `ngFor`?

**Comment by cmckni3** [comment]
This is resolved. Thanks @tsonevn.

**Comment by n0mer** [comment]
@tsonevn probably this one: https://github.com/NativeScript/NativeScript/issues/7125
