### ISSUE TITLE
On app launch: first page depends on fetch request

### ISSUE THREAD

**Issue by JackPoteYes** [NativeScript/NativeScript#6311]
On my app launch I want to send a fetch request and choose what first page to go to depending on the result.

But the problem is:
  -  Launching a fetch request before the app launchs creates an error, probably because the frame environment is not defined yet
  -  Performing the fetch on launch with app.on(application.launchEven, ...) works, but in the meantime the first default page is is displayed with app.stat({moduleName: <defaultFirstModuleName>}), and therefore the pb remains.

**Comment by NickIliev** [comment]
@JackPoteYes I would suggest creating a default landing page where the wanted http request can be made - this way your application will also work when there is no connection available. Or you could create the view model in your landing page to load dynamically the page content once the async response is received.

Some additional information on why your mobile application won't work when the async operation is made before the application bootstrapping can be found [here](https://github.com/NativeScript/nativescript-angular/issues/1487#issuecomment-413541011) - in the linked issue and ideas for extending the Angular logic is provided which might be considered for the Core logic as well.

**Comment by JackPoteYes** [comment]
Thanks @NickIliev, a temporary loading view is indeed the solution I am using for now.
Thank you for the extra knowledge and answer, appreciated.
