### ISSUE TITLE
Text color on SegmentedBar only affects first element

### ISSUE THREAD

**Issue by nicoeg** [NativeScript/NativeScript#6324]
### Tell us about the problem
When styling the color of a SegmentedBar the first element on the page is only affected by the styling.
It also seems to be an issue when applying the property to the element through html.
Other styling properties like background is working as expected.

I'm pretty certain this has been an issue for a while.

### Which platform(s) does your issue occur on?
Only tested on Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.2.0
- Cross-platform modules: 4.2.0
- Runtime(s): 4.2.0

### Please tell us how to recreate the issue in as much detail as possible.
https://play.nativescript.org/?template=play-ng&id=uVa4GK&v=4

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```css
SegmentedBar {
    color: #ffffff;
}
```

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1533

**Comment by nicoeg** [comment]
Hi sorry. This is also an issue with Nativescript-vue so it's not specific to Angular
