### ISSUE TITLE
Method `modalParams.closeCallback()` not closing modal modal

### ISSUE THREAD

**Issue by abhayastudios** [NativeScript/NativeScript#6328]
### Tell us about the problem
In `tns-core-modules@next` I am experiencing a problem with multiple pre-existing modals `modalParams.closeCallback()` where it doesn't close the modal, but it **does** reach the main view's close callback. Also it looks as if the modal is removed from an Array holding modal references or something because if I tap again, I am getting an error `ERROR TypeError: Cannot read property 'length' of undefined`. The problem is just that the modal does not close.

If I revert back to `tns-core-modules@4.2.0` then all modals involved work fine.

Note: my app is using the pre-4.1 modal setup, but even if I change it to the new format of `modal-page-actionbar` from the `nativescript-sdk-examples-ng` then I observe the same behavior.

### Which platform(s) does your issue occur on?
Android with `tns-core-modules@4.3.0-2018-09-28-182206-01`
(but same happened with previous `@next`)

### Please provide the following version numbers that your issue occurs with:
```
$ tns info
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 4.2.3 and the latest available version is 4.2.4.
✔ Component tns-core-modules has 4.3.0-2018-09-28-182206-01 version and is up to date.
✔ Component tns-android has 4.2.0 version and is up to date.
✔ Component tns-ios has 4.3.0-2018-09-19-01 version and is up to date.
```

### Please tell us how to recreate the issue in as much detail as possible.
I am still trying to reproduce in a fresh project. Will update when I have something.

**Comment by tsonevn** [comment]
HI @abhayastudios,
Indeed, It will help if you can provide a sample project, which can be used for debugging.

**Comment by abhayastudios** [comment]
@tsonevn never mind about this one. Using tracing I was able to narrow the problem down to the `nativescript-ngx-slides` plugin firing a double tap event when using `<slide (tap)="">` as of `tns-core-modules@next`, but setting the `(tap)` on a child `<StackLayout>` solves the issue for me.

Closing and thanks for your help!
