### ISSUE TITLE
Invalid maximum heap size: -Xmx16384M

### ISSUE THREAD

**Issue by pushqrdx** [NativeScript/NativeScript#6332]
### Tell us about the problem
The `gradpe.properties` file always contains wrong `jvmargs` resulting in `Invalid maximum heap size` error during build. Note that the error occurs with all types of NativeScript templates. 

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.2.4

### Please tell us how to recreate the issue in as much detail as possible.
Just create a new project from any of NativeScripts templates and the `org.gradle.jvmargs` in `gradle.properties` will be allocated ram than what the PC has. You'll then have to go and decrease that value so the build can run successfully.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#1182
