### ISSUE TITLE
Failed to build plugin nativescript-socket.io 

### ISSUE THREAD

**Issue by kibhub** [NativeScript/NativeScript#6346]
I am trying to setup a nativescript + vue development environment, but i am stuck with error when i try to build for android 

Unable to apply changes on device: emulator-5554. Error is: Failed to build plugin nativescript-socket.io : 
Error: Command ./gradlew failed with exit code 1 Error output: 
 Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:215)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:75)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
.

and Here is packgage.json files content

{
 ,
  "nativescript": {
    "id": "org.nativescript.application",
    "tns-ios": {
      "version": "4.2.0"
    },
    "tns-android": {
      "version": "4.2.0"
    }
  },
  "dependencies": {
    "@vue/devtools": "5.0.0-beta.3",
    "ajv": "^6.5.4",
    "nativescript-socket.io": "^0.9.0",
    "nativescript-socketio": "^3.2.1",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-vue": "^2.0.0",
    "nativescript-vue-devtools": "^1.0.0",
    "tns-core-modules": "^4.2.0",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.2",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "^1.0.0",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "next",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.1.0",
    "terser-webpack-plugin": "^1.1.0",
    "vue-loader": "^15.2.6",
    "webpack": "^4.20.2",
    "webpack-bundle-analyzer": "~2.13.1",
    "webpack-cli": "^3.1.0"
  },
  "main": "babel.config.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  }
}

**Comment by tsonevn** [comment]
HI @kibhub,
Can you send us some more info about your environment(`node`, `NativeScript CLI` version)? It will help if you send us the project or at least its `package.json` file.

Meanwhile, you can try deleting the `.gradle` and then try to rebuild the project.
> the path to the `.gradle` should be `~/.gradle` for Mac/Linux and `%USERPROFILE%\.gradle` for windows.

**Comment by gezn** [comment]
@kibhub  I have the same issue building socket.io so I opened a ticket on nativescript-socket.io project https://github.com/naderio/nativescript-socket.io/issues/49    since it seems to be related to them. because I can build for android if I take of socket.io out of the equation.

**Comment by tsonevn** [comment]
Hi @kibhub,
If the build problem is caused by `nativescript-socket.io`, the right place for discussing the problem is the plugins repository. I would suggest following the [issue](https://github.com/naderio/nativescript-socket.io/issues/49) opened by @gezn.
