### ISSUE TITLE
Making sense of ERROR CONTEXT / easier error debugging

### ISSUE THREAD

**Issue by suparnavg** [NativeScript/NativeScript#6349]
### Tell us about the problem
Feature request: An easier way to make sense of ERROR CONTEXT shown in the console

### Which platform(s) does your issue occur on?
Android

###Details:
E.g. if there is a `TypeError:  Cannot read property 'length' of undefined`, it is followed by a long ERROR CONTEXT, which does not show fully in the console, resulting in more trouble to find the actual error! E.g.

Would be a lot more helpful if the filename / line number where the error was thrown was displayed prominently. Many times, this is all that is required to debug, and the full ERROR CONTEXT is not even needed.

```
ERROR CONTEXT {
JS:   "view": {
JS:     "def": {
JS:       "nodeFlags": 50905089,
JS:       "rootNodeFlags": 1,
JS:       "nodeMatchedQueries": 0,
JS:       "flags": 0,
JS:       "nodes": [
JS:         {
JS:           "nodeIndex": 0,
JS:           "parent": null,
JS:           "renderParent": null,
JS:           "bindingIndex": 0,
JS:           "outputIndex": 0,
JS:           "checkIndex": 0,
JS:           "flags": 1,
JS:           "childFlags": 50905089,
JS:           "directChildFlags": 50331649,
JS:           "childMatchedQueries": 0,
JS:           "matchedQueries": {},
JS:           "matchedQueryIds": 0,
JS:           "references": {},
JS:           "ngContentIndex": null,
JS:           "childCount": 2,
JS:           "bindings": [],
JS:           "bindingFlags": 0,
JS:           "outputs": [],
JS:           "element": {
JS:             "ns": "",
JS:             "name": "StackLayout",
JS:             "attrs": [],
JS:             "template": null,
JS:             "componentProvider": null,
JS:             "componentView": null,
JS:             "componentRendererType": null,
JS:             "publicProviders": {},
JS:             "allProviders": "[Ci...
```

**Comment by NickIliev** [comment]
Related to [https://github.com/NativeScript/android-runtime/issues/1026](https://github.com/NativeScript/android-runtime/issues/1026)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#1541
