### ISSUE TITLE
Execution failed for task ':app:lintVitalRelease'. Could not resolve all artifacts for configuration ':app:debugAndroidTestRuntimeClasspath'.  Could not find com.android.support:multidex-instrumentation:27.1.1. during android release build

### ISSUE THREAD

**Issue by SwapnilRathore** [NativeScript/NativeScript#6352]
> Task :app:bundleReleaseJsAndAssets
 
Scanning folders for symlinks in /Users/jayantitripathi/Documents/trickster_frontend/node_modules (21ms)
Scanning folders for symlinks in /Users/jayantitripathi/Documents/trickster_frontend/node_modules (19ms)
warning: the transform cache was reset.
Loading dependency graph, done.
bundle: Writing bundle output to: /Users/jayantitripathi/Documents/trickster_frontend/android/app/build/intermediates/assets/release/index.android.bundle
bundle: Done writing bundle output
bundle: Copying 4 asset files
bundle: Done copying assets

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not find com.android.support:multidex-instrumentation:27.1.1.
     Searched in the following locations:
         file:/Users/jayantitripathi/Library/Android/sdk/extras/m2repository/com/android/support/multidex-instrumentation/27.1.1/multidex-instrumentation-27.1.1.pom
         file:/Users/jayantitripathi/Library/Android/sdk/extras/m2repository/com/android/support/multidex-instrumentation/27.1.1/multidex-instrumentation-27.1.1.jar
         file:/Users/jayantitripathi/Library/Android/sdk/extras/google/m2repository/com/android/support/multidex-instrumentation/27.1.1/multidex-instrumentation-27.1.1.pom
         file:/Users/jayantitripathi/Library/Android/sdk/extras/google/m2repository/com/android/support/multidex-instrumentation/27.1.1/multidex-instrumentation-27.1.1.jar
         file:/Users/jayantitripathi/Library/Android/sdk/extras/android/m2repository/com/android/support/multidex-instrumentation/27.1.1/multidex-instrumentation-27.1.1.pom
         file:/Users/jayantitripathi/Library/Android/sdk/extras/android/m2repository/com/android/support/multidex-instrumentation/27.1.1/multidex-instrumentation-27.1.1.jar
         https://dl.google.com/dl/android/maven2/com/android/support/multidex-instrumentation/27.1.1/multidex-instrumentation-27.1.1.pom
         https://dl.google.com/dl/android/maven2/com/android/support/multidex-instrumentation/27.1.1/multidex-instrumentation-27.1.1.jar
         file:/Users/jayantitripathi/.m2/repository/com/android/support/multidex-instrumentation/27.1.1/multidex-instrumentation-27.1.1.pom
         file:/Users/jayantitripathi/.m2/repository/com/android/support/multidex-instrumentation/27.1.1/multidex-instrumentation-27.1.1.jar
         https://jcenter.bintray.com/com/android/support/multidex-instrumentation/27.1.1/multidex-instrumentation-27.1.1.pom
         https://jcenter.bintray.com/com/android/support/multidex-instrumentation/27.1.1/multidex-instrumentation-27.1.1.jar
         https://repo.maven.apache.org/maven2/com/android/support/multidex-instrumentation/27.1.1/multidex-instrumentation-27.1.1.pom
         https://repo.maven.apache.org/maven2/com/android/support/multidex-instrumentation/27.1.1/multidex-instrumentation-27.1.1.jar
         file:/Users/jayantitripathi/Documents/trickster_frontend/node_modules/react-native/android/com/android/support/multidex-instrumentation/27.1.1/multidex-instrumentation-27.1.1.pom
         file:/Users/jayantitripathi/Documents/trickster_frontend/node_modules/react-native/android/com/android/support/multidex-instrumentation/27.1.1/multidex-instrumentation-27.1.1.jar
         https://jitpack.io/com/android/support/multidex-instrumentation/27.1.1/multidex-instrumentation-27.1.1.pom
         https://jitpack.io/com/android/support/multidex-instrumentation/27.1.1/multidex-instrumentation-27.1.1.jar
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by NickIliev** [comment]
@SwapnilRathore please provide more details on what the error actually means and how it is happening. Please follow the requirements when posting a new issue including providing the needed information so that the issue can be investigated

> 
> 
> 
> ### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
> 
> ### Tell us about the problem
> Please, ensure your title is less than 63 characters long and starts with a capital
> letter.
> 
> ### Which platform(s) does your issue occur on?
> iOS/Android/Both
> 
> ### Please provide the following version numbers that your issue occurs with:
> - CLI: (run `tns --version` to fetch it)
> - Cross-platform modules: (check the 'version' attribute in the
> `node_modules/tns-core-modules/package.json` file in your project)
> - Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
> `package.json` file of your project)
> - Plugin(s): (look for the version number in the `package.json` file of your
> project)
> 
> ### Please tell us how to recreate the issue in as much detail as possible.
> The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 
> 
> ### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

**Comment by SwapnilRathore** [comment]
@NickIliev kindly have a look at the issue here please 

https://github.com/SwapnilRathore/trickster_frontend/issues/1

**Comment by NickIliev** [comment]
@SwapnilRathore  looking at your `package.json` content it seems that the issue is that you are using `react-native` instead of `nativescript` ...

Are you sure you got the right repository to log the issue?

**Comment by SwapnilRathore** [comment]
yes i have the issue on this repo and i am using react native .. i want to know the cause of the issue

**Comment by SwapnilRathore** [comment]
My android repository is up to date .

**Comment by SwapnilRathore** [comment]
If you help please on how i can fix it , any idea

**Comment by bilaz** [comment]
try removing this line "

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support' && requested.name != 'multidex') {
            details.useVersion "${rootProject.ext.supportLibVersion}"
        }
    }
}"

You are using react native navigation
