### ISSUE TITLE
AWS AppSync Support [feature]

### ISSUE THREAD

**Issue by fhackenb** [NativeScript/NativeScript#6355]
It would be great if someone were to make a plugin to easily integrate AWS AppSync with NativeScript. AppSync is great for updating data in realtime and for its offline support. If we had a {N} plugin that supported it, I think a lot of people would use it. 

I've found (and spoken to) a couple people that have tried to use it with NativeScript and haven't been able to get the js sdk working. They've had to use alternative (hacky) approaches that don't include offline support (critical for many use cases). So there is definitely already a desire for this plugin beyond just me.

Here's the iOS sdk: [https://github.com/awslabs/aws-mobile-appsync-sdk-ios](url)

I started working on developing an iOS plugin for it, but haven't gotten very far (having some import issues when generating the typings).

**Comment by tsonevn** [comment]
Hi @fhackenb,
You can check the [nativescript-aws-sdk](https://github.com/triniwiz/nativescript-aws-sdk), which seems to provide AWS support for NativeScript. If there is a missing feature, you can log a new feature request in the plugin's repository and also to provide PR with its implementation.
As you already mentioned, the second option is to create your own [plugin](https://docs.nativescript.org/plugins/building-plugins), which provides support in NativeScript for the needed native library. If you are facing an issue, you can always open a new thread in StackOverflow or a new issue in NativeScript repository for bug-related problems.

BR,
@tsonevn
