### ISSUE TITLE
ERROR in Path "C:/../../Users/hansl/Sources/hansl/angular-cli/packages/angular_devkit/core/src/virtual-fs" is invalid.

### ISSUE THREAD

**Issue by pedrofp1993** [NativeScript/NativeScript#6356]
### Tell us about the problem
I can´t run my nativescript application with tns run android --bundle after i create the apk with the command tns build android --release

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.2.4
- Cross-platform modules: 4.2.1
- Runtime(s): 4.0.0

### Please tell us how to recreate the issue in as much detail as possible.
Make the apk with the command tns build android --release
--key-store-path ~/path/to/tj-vantoll.jks
--key-store-password my-very-secure-password
--key-store-alias PokemonTypes
--key-store-alias-password my-very-secure-password

run the application with tns run android --bundle

**Comment by tsonevn** [comment]
Hi @pedrofp1993,
Try to clear up the project by deleting `platforms`, `node_modules` and `hooks` folders and try to rebuild it again with `tns run android`. 
If the issue persists, send us the project or at least it's `package.json` file and the full Error log from the console.
