### ISSUE TITLE
Plugin for Elasticsearch in Nativescript 

### ISSUE THREAD

**Issue by rg777** [NativeScript/NativeScript#6360]
Has anyone been able to successfully integrate elasticsearch into nativescript client side application?

I tried to install it as NPM module
`npm install elasticsearch --save`

However I am receiving the following errors while running the following command
`tns run android`

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "fs", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:553)
    com.tns.Runtime.run(Runtime.java:545)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
    android.app.ActivityThread.-wrap1(Unknown Source:0)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
    android.os.Handler.dispatchMessage(Handler.java:106)
    android.os.Looper.loop(Looper.java:164)
    android.app.ActivityThread.main(ActivityThread.java:6494)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
File: "<unknown>, line: 1, column: 265

I tried installing the module 'fs' but the error still remains.
Does there already exist a plugin for elastcisearch in NativeScript?

**Comment by NickIliev** [comment]
@rg777 the plugin is not compatible with NativeScript as one or more of its dependencies are clashing with the mobile wrappers.
