### ISSUE TITLE
Save Html content in backend

### ISSUE THREAD

**Issue by kanchanagarwal3** [NativeScript/NativeScript#6361]
Nativescript-4.1.3
Ipad version - 12.0
Issue:
is it possible to save the entire html content as image file

**Comment by NickIliev** [comment]
@kanchanagarwal3  Not a NativeScript related question so consider looking for JavaScript/TypeScript solutions to your problem (e.g. [here](https://stackoverflow.com/questions/10721884/render-html-to-an-image))

The repository is for logging issues, bugs and features related to NativeScript.
For how-to related questions please use the community channels like  [NativeScript in StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) or [NativeScript community slack](https://nativescriptcommunity.slack.com/messages/general)
