### ISSUE TITLE
Feature: New Dialog Prompt Input Type for Phone / Numbers

### ISSUE THREAD

**Issue by shyamseshadri** [NativeScript/NativeScript#6363]
**Is your feature request related to a problem? Please describe.**

PromptOptions when creating a dialog.prompt currently takes inputType as an option.

It is only limited to text, password or email.

There are cases when it is nice to take a number as an input, where the keypad is restricted to numbers only, instead of taking any string, and then checking if it is a number, and if not, reshowing the prompt.

**Describe the solution you'd like**

Would like to add an option called number to inputType, and show the numeric keypad in case the inputType is set to number.

**Additional context**
I'm assuming this would be similar to #3118. If it will be similar, I can create a PR for the same and send it for review.

**Comment by NickIliev** [comment]
@shyamseshadri feel free to create the feature request and post your PR. Contributions details can be found [here](https://www.nativescript.org/contribute)

**Comment by shyamseshadri** [comment]
@NickIliev Created the PR. Thanks!
