### ISSUE TITLE
Google play app signing

### ISSUE THREAD

**Issue by suparnavg** [NativeScript/NativeScript#6368]
**Is your feature request related to a problem? Please describe.**
The current documentation on [publishing to android](https://docs.nativescript.org/angular/tooling/publishing/publishing-android-apps#release-certificate) does not have any guidance for using the [Google Play App signing](https://developer.android.com/studio/publish/app-signing#google-play-app-signing) flow. Requesting some clarity on this issue because google's app signing has many benefits over creating and managing your keys personally.

An issue was opened previously #4888  but has since been closed without enough clarity..

**Describe the solution you'd like**
Questions:
1. Is Google Play App Signing compatible with how NS apps are signed before release?
2. If so, what is the process to do it?

Thanks a lot!

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#1184
