### ISSUE TITLE
App name vs project name

### ISSUE THREAD

**Issue by delanick** [NativeScript/NativeScript#6378]
Hi,

I'm not sure if this is the right place, or if I should request this of the Sidekick team, but:

Please allow us to change the app's name during the project. Currently (with Sidekick anyway), you can only create a project name, which also doubles as the app name. I would like to be able to change the app's name (the name they see on their phone under the icon image) and Sidekick doesn't allow it. Or is there another way via package.json I can change it?

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/sidekick-feedback#279
