### ISSUE TITLE
Ad Control Request

### ISSUE THREAD

**Issue by paranoid-android** [NativeScript/NativeScript#638]
The more I experiment with NativeScript, the more excited I am about it. However, one of the requests I routinely get from customers is the need to include advertisements in their apps. I hope NativeScript will provide some sort of advertisement control that would allow me to:

1. Enter application and ad unit IDs by provider.
    a. Enter for Android Apps
    b. Enter for iOS Apps
    c. Enter an Application ID and Ad Unit ID for use in Windows Apps
2. Provide a way to prioritize advertisements
3. Provide a way to fall back.

In general, I'm thinking of something like this:
```
<ui:Advertisement UseCustomFirst="true" OnErrorLoadingAdvertisement="functionName" OnClick="functionName">
  <ui:Advertisement.Android>
    <ui:AdvertisementService ApplicationId="..." AdUnitId="..."  />
  </ui:Advertisement.Android>

  <ui:Advertisement.iOS>
    <ui:AdvertisementService ApplicationId="..." AdUnitId="..."  />
  </ui:Advertisement.iOS>

  <ui:Advertisement.Windows>
    <ui:AdvertisementService ApplicationId="..." AdUnitId="..."  />
  <ui:Advertisement.Windows>

  <ui.Advertisement.Custom>
  </ui.Advertisement.Custom>
</ui:Advertisement> 
```

The syntax is a little unique. Due to the nature of native advertisements, I'm not sure how to have OS specific advertisements and provide settings for each service. At the same time, sometimes, I need to show a custom advertisement first and fall back to the ad services. Other times, I need to do it the other way.

I hope this control will be considered. If nothing else, I hope it makes it into NativeScript UI. That would be a huge, valuable addition.

**Comment by NathanaelA** [comment]
I'm not with Telerik; but NativeScript can already do platform specific items with Declarative UI.
<Advertisement ...  ios:ApplicationId=".."  android:ApplicationId="..." .../>
or
<ios><Advertisement ....></ios><android><Advertisement ...></android>

Both of those ways will only use the platform specific version.

I don't believe we need to add any special additional declarative ui code.  

As for priority; you can control that fully via JS easily.      

Now as to advertisement services; that is a whole different ball of wax; each one does it differently; so I'm not sure how easy it would be wrap things up in a generic control...  But I wanted you to know that the Declarative UI syntax already support platform modifiers.

**Comment by N3ll** [comment]
You can vote on out ideas-voting site https://nativescript.ideas.aha.io/ideas/NS-I-6.

**Comment by enchev** [comment]
You can use https://github.com/EddyVerbruggen/nativescript-admob plugin
