### ISSUE TITLE
 Error is: Socket connection timeouted..

### ISSUE THREAD

**Issue by szgozcan** [NativeScript/NativeScript#6382]
**Environment**
Getting NativeScript components versions information...
✔ Component nativescript has 4.2.4 version and is up to date.
✔ Component tns-core-modules has 4.2.1 version and is up to date.
✔ Component tns-android has 4.2.0 version and is up to date.
✔ Component tns-ios has 4.2.0 version and is up to date.

**Describe the bug**
I have finished  my app and it was running perfectly but when I added the admob banner as it is described in nativescript documentation I get 

Project successfully built.
Installing...
Successfully installed on device with identifier '52002decb4371555'.
Unable to apply changes on device: 52002decb4371555. Error is: Socket connection timeouted..

I deleted all banner stuff from the codes and android manifest xml but the app even doesn't start.
I have working apps with banners and I went through the same exact steps. But this time I keep getting that error. 

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by tsonevn** [comment]
Hi @szgozcan,
Try to clean up the project by deleting the `platforms`, `node_modules`, `hooks` folders and `package-lock.json` file from the project. Then rebuild the app (`tns run <platform_name>`) and check if you are facing the same issue.

If the problem persists, please send us the full error log from the console. Also, any info, that can help us to recreate the problem on our side will be highly appreciated(sample project, any code fragment, which might be responsible for the crash ).

**Comment by szgozcan** [comment]
I  deleted the platforms, node modules, hooks and package.json file from the project. Then rebuilt it with tns run android. I ran it on emulator. I keep getting the same problem. And this is what I have on console

    sezgin-ozcans-MacBook-Pro:IngilizceBesinciSinif sezginozcan$ tns run android
    Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
    Searching for devices...

  > fsevents@1.2.4 install /Users/sezginozcan/IngilizceBesinciSinif/node_modules/fsevents
> node install

[fsevents] Success: "/Users/sezginozcan/IngilizceBesinciSinif/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> nativescript-dev-webpack@0.16.2 postinstall /Users/sezginozcan/IngilizceBesinciSinif/node_modules/nativescript-dev-webpack
> node postinstall.js


NativeScript Webpack plugin was successfully added.
You can now bundle your project by passing --bundle flag to NativeScript CLI commands:    - tns build android --bundle
    - tns build ios --bundle
    - tns run android --bundle
    - tns run ios --bundle
You can also pass the "--env.uglify" flag to use UglifyJS for minification.
For more information check out https://docs.nativescript.org/tooling/bundling-with-webpack#bundling.

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN awesome-typescript-loader@5.2.1 requires a peer of typescript@^2.7 || ^3 but none is installed. You must install peer dependencies yourself.

added 673 packages in 54.783s
Executing before-watchPatterns hook from /Users/sezginozcan/IngilizceBesinciSinif/hooks/before-watchPatterns/nativescript-dev-webpack.js
Executing before-watch hook from /Users/sezginozcan/IngilizceBesinciSinif/hooks/before-watch/nativescript-dev-webpack.js
Copying template files...
Platform android successfully added. v4.2.0
Executing before-shouldPrepare hook from /Users/sezginozcan/IngilizceBesinciSinif/hooks/before-shouldPrepare/nativescript-dev-webpack.js
Preparing project...
Executing before-prepareJSApp hook from /Users/sezginozcan/IngilizceBesinciSinif/hooks/before-prepareJSApp/nativescript-dev-webpack.js
Successfully prepared plugin nativescript-admob for android.
Successfully prepared plugin nativescript-audio-player for android.
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared (Android)
Executing after-prepare hook from /Users/sezginozcan/IngilizceBesinciSinif/hooks/after-prepare/nativescript-dev-webpack.js
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from /Users/sezginozcan/IngilizceBesinciSinif/app/App_Resources/Android/app.gradle
         Applying settings from /Users/sezginozcan/IngilizceBesinciSinif/app/App_Resources/Android/settings.json
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: /Users/sezginozcan/IngilizceBesinciSinif/node_modules/nativescript-admob/platforms/android/n
ativescript_admob.aar
         + adding aar plugin dependency: /Users/sezginozcan/IngilizceBesinciSinif/node_modules/tns-core-modules-widgets/platforms/and
roid/widgets-release.aar
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Project successfully built.
Installing...
Successfully installed on device with identifier '192.168.57.101:5555'.
Unable to apply changes on device: 192.168.57.101:5555. Error is: Socket connection timeouted..
Executing after-watch hook from /Users/sezginozcan/IngilizceBesinciSinif/hooks/after-watch/nativescript-dev-webpack.js
Executing after-watch hook from /Users/sezginozcan/IngilizceBesinciSinif/hooks/after-watch/nativescript-dev-webpack.js
sezgin-ozcans-MacBook-Pro:IngilizceBesinciSinif sezginozcan$

**Comment by tsonevn** [comment]
Hi @szgozcan,
The problem might be related the one logged [here](https://github.com/NativeScript/nativescript-cli/issues/3818). Please check the provided solution in [this](https://github.com/NativeScript/nativescript-cli/issues/3818#issuecomment-428644265) comment. Also, can you build the project with the `--log trace` flag -> `tns run android --log trace > log.txt` and send us the `log.txt` file. This will help us to verify if it is the same case.

**Comment by szgozcan** [comment]
hello again;
I still keep getting the same error. In order to understand the problem, I started a blank project. It was working fine until I added the banner part. I did the following parts in order to find the problem.
My js file with banner is as follows 
[js file.txt](https://github.com/NativeScript/NativeScript/files/2470346/js.file.txt)


1. I created a bannerview.js under app folder.

[bannerview .txt](https://github.com/NativeScript/NativeScript/files/2470357/bannerview.txt)



2. I added sample app id to manifest.xml 

[AndroidManifest copy.txt](https://github.com/NativeScript/NativeScript/files/2470363/AndroidManifest.copy.txt)



3.  I imported the following part to build-gradle 

     
[build copy.txt](https://github.com/NativeScript/NativeScript/files/2470372/build.copy.txt)


4. And lastly I added
     ` 
[app build  gradle copy.txt](https://github.com/NativeScript/NativeScript/files/2470379/app.build.gradle.copy.txt)


5.  I think the problem is caused something with admob. I use the instructions defined in admob site. I use sample ad units id. But unfortunately I get that crush. 

6. My log.txt is 
[log.txt](https://github.com/NativeScript/NativeScript/files/2470308/log.txt)

**Comment by tsonevn** [comment]
Hi @szgozcan,
Try the [nativescript-admob](https://github.com/EddyVerbruggen/nativescript-admob) plugin? The plugin seems to provide support for AdMob in NativeScript and should work as expected within NS project. Check if you will have a problem with the build.

**Comment by szgozcan** [comment]
Hi,
I already did it.

sezgin-ozcans-MacBook-Pro:ingilizce5 sezginozcan$ tns plugin add nativescript-admob
Plugin "nativescript-admob" is already installed.


I have apps needed to be updated. And I fear that if I run them. They will also crush also. I get the following output at console. 



     `Project successfully prepared (Android)

    Executing after-prepare hook from /Users/sezginozcan/ingilizce5/hooks/after-prepare/nativescript-     dev-webpack.js

    Building project...

    Gradle build...

	 + setting applicationId


	 + applying user-defined configuration from /Users/sezginozcan/ingilizce5/app/App_Resources/Android/app.gradle

	 + adding nativescript runtime package dependency: nativescript-optimized-with-inspector


	 + adding aar plugin dependency: /Users/sezginozcan/ingilizce5/node_modules/nativescript-admob/platforms/android/nativescript_admob.aar
	 + adding aar plugin dependency: /Users/sezginozcan/ingilizce5/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar

    Project successfully built.

    Installing...

    Successfully installed on device with identifier '192.168.57.101:5555'.

    Unable to apply changes on device: 192.168.57.101:5555. Error is: Socket connection timeouted..

    Executing after-watch hook from /Users/sezginozcan/ingilizce5/hooks/after-watch/nativescript-dev-webpack.js

    Executing after-watch hook from /Users/sezginozcan/ingilizce5/hooks/after-watch/nativescript-dev-webpack.js

    [NSDebugAdapter] The tns command finished its execution with code 0.`

**Comment by NickIliev** [comment]
@szgozcan we've increased the timeout via this PR - please check your run command via the `next` CLI.
Closing this issue as not related to NativeScript modules - if you are still encountering this issue with the `next` version of CLI please post an issue in the [nativescript-cli repository](https://github.com/NativeScript/nativescript-cli/issues).

**Comment by kodster** [comment]
> I had the exact same problem. It got fixed after I freed up some space from the phone storage.
Excat error - "Unable to apply changes on device: emulator. Error is: Socket connection timeouted.."
Freeing up phone storage worked for me too. Thanks.

**Comment by horia-alungulesei** [comment]
@NickIliev Seems like the error message is unrelated to the root problem. There should be a check to determine if the available storage is sufficient.
