### ISSUE TITLE
Whenever a modal-dialog is closed, the header-footer stops showing 

### ISSUE THREAD

**Issue by nikeshjain** [NativeScript/NativeScript#6383]
Hello,

We have recently upgraded our app to NativeScript v4.2 with Angular v6. Earlier we were using NativeScript v3.3 with Angular v4. The app has a common header and footer section for navigating through the app. The central area of the app loads different components as per the current menu selection.

We have used "RadSideDrawer" control of the "nativescript-ui-sidedrawer" module in the app.component.html.

The "DrawerContent" contains the UI elements for user preferences that we need to show in the drawer when the user swipes down from the header
The "Maincontent" contains the UI elements for header, footer and the central area. The central area is kept in the page-router-outlet.

The navigation from the header-footer and the slider swiping features are working fine until we open and close a modal-dialog. Whenever a modal-dialog is closed, the header-footer stops showing, only the elements inside page-router-outlet continue to show.

The above issue is faced only in iOS. In Android, everything is working fine. In iOS, the issues started to arise after we upgraded to NS 4.2.

I have attached the demo code for your reference.
https://play.nativescript.org/?template=play-ng&id=EcYrUw&v=2

An urgent help in solving this issue will be greatly appreciated!

Thanks in anticipation!
Regards,
Nikesh Jain

**Comment by NickIliev** [comment]
@nikeshjain I can confirm that indeed the issue exists marking this one as a bug. We will investigate the case and post any related information here.

**Comment by NickIliev** [comment]
Related to [https://github.com/NativeScript/nativescript-angular/issues/1532](https://github.com/NativeScript/nativescript-angular/issues/1532)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#1554
