### ISSUE TITLE
Release Plan 5.0

### ISSUE THREAD

**Issue by radeva** [NativeScript/NativeScript#6384]
## Release 5.0 -  Oct 2018
**DO till Oct 15**
- [x] Publish RC tns-android, @vtrifonov 
  - [x]  Create release branch
  - [x]  Tests are passing
  - [x]  Publish RC package to npm
- [x] Publish RC tns-ios, @vtrifonov 
  - [x]  Create release branch
  - [x]  Tests are passing
  - [x]  Publish RC package to npm
- [x] Publish RC tns-platform-declarations, @vakrilov
  - [x]  Create release branch
  - [x]  Tests are passing
  - [x]  Publish RC package to npm
- [x] Publish RC tns-core-modules, @vakrilov
  - [x]  Create release branch
  - [x]  Tests are passing
  - [x]  Publish RC package to npm
- [x] Publish RC nativescript, @rosen-vladimirov 
  - [x]  Create release branch
  - [x]  Tests are passing
  - [x] Ensure Sidekick tests and cloud builds work with RC version of CLI 
  - [x]  Publish RC package to npm
- [x] Publish RC NativeScript UI Plugins, @etabakov 
  - [x]  Create release branch
  - [x]  Tests are passing
  - [x]  Publish RC package to npm
- Announce RC on twitter, Slack

**DO Before Release**
- [x] Update roadmap on <https://www.nativescript.org/roadmap>, @radeva (PRE: Planning for next release is completed)
- [x] Publish documentation on UAT, @etabakov (PRE: All affected articles need to be added/updated and merged in master)
- [x] Write release blog post , @radeva

**DO on Release Date**
- [x] (optional) Publish migration guides, @sis0k0 
- [x] Publish tns-android, @vtrifonov 
  - [x]  Build package for release
  - [x]  Tests are passing
  - [x]  Prepare Changelog
  - [x]  Publish package to npm
  - [x] Tag the new release in GitHub 
  - [x]  Post in Slack #ns-releases
- [x] Publish tns-ios, @vtrifonov 
  - [x]  Build package for release
  - [x]  Tests are passing
  - [x]  Prepare Changelog
  - [x]  Publish package to npm
  - [x] Tag the new release in GitHub 
  - [ ] Upload dSYM in GitHub release
  - [x]  Post in Slack #ns-releases
- [x] (optional) Publish tns-ios-inspector, @vtrifonov 
- [x] Publish tns-platform-declarations, @vakrilov
  - [x]  Build package for release
  - [x] Publish package in npm 
  - [x] Tag the new release in GitHub 
  - [x] Post in Slack #ns-releases 
- [x] Publish tns-core-modules, @vakrilov
  - [x]  Build package for release
  - [x] Prepare Changelog
  - [x] Make sure tests pass
  - [x] Release tns-core-modules to npm
  - [x] Tag the new release in GitHub 
  - [x] Post in Slack #ns-releases 
- [x] Publish nativescript, @rosen-vladimirov 
  - [x]  Build package for release
  - [x] Prepare Changelog 
  - [ ] Ensure Sidekick tests and cloud builds work with RC version of CLI 
  - [x] Publish package in npm 
  - [ ] Tag the new release in GitHub 
  - [x] Post in Slack #ns-releases 
- [ ] (optional) Publish nativescript-dev-sass, @rosen-vladimirov - not required for this release
  - [ ]  Build package for release
  - [ ] Prepare Changelog 
  - [ ] Publish package in npm 
  - [ ] Tag the new release in GitHub 
  - [ ] Post in Slack #ns-releases 
- [ ] (optional) Publish nativescript-dev-typescript, @rosen-vladimirov - not required for this release
- [x] Publish nativescript-angular, @vakrilov
  - [x]  Build package for release
  - [x] Publish package in npm 
  - [ ] Tag the new release in GitHub 
  - [x] Post in Slack #ns-releases 
- [x] Publish nativescript-dev-webpack, @vakrilov
  - [x]  Build package for release
  - [x] Publish package in npm 
  - [x] Tag the new release in GitHub 
  - [x] Post in Slack #ns-releases 
- [ ] Publish @nativescript/schematics, @vakrilov 
  - [x]  Build package for release
  - [x] Publish package in npm 
  - [x] Tag the new release in GitHub 
  - [x] Post in Slack #ns-releases 
- [x] Publish all core templates, @vakrilov
- [x] Publish all business templates, @lini
- [x] (optional) Publish all plugins & plugin seed, @lini
- [x] Publish documentation on LIVE, @etabakov

**DO After Release**
- [x] (optional) Verify the migration steps by trying with a real app, @etabakov 
- [x] (optional) Update the breaking changes in the app, @etabakov 
- [ ] (optional) Update plugins demo apps, @lini
- [x] (optional) Update all Playground apps, @vtrifonov
- [x] (optional) Update all Playground templates, @vtrifonov
- [x] Publish release blog post, @rdlauer 
- [x] Announce release on Twitter, @sipacate 
- [x] (optional) Feature blog posts 

## Known issues in RC:
- [ ] [LiveSync is not working in Preview app when Angular's lazy loading is used](https://github.com/NativeScript/nativescript-cli/issues/4024)

**Comment by etabakov** [comment]
Upgrade instructions for the RC: https://github.com/NativeScript/NativeScript/wiki/Early-Testing-of-NativeScript-5.0-RC
