### ISSUE TITLE
ObservableArray.reduce from tns-core-modules doesn't handle initial value correctly

### ISSUE THREAD

**Issue by elonmallin** [NativeScript/NativeScript#6385]
**Environment**
From `tns info`:
✔ Component nativescript has 4.2.4 version and is up to date.
✔ Component tns-core-modules has 4.2.1 version and is up to date.
✔ Component tns-ios has 4.2.0 version and is up to date.

**The bug**
The `reduce` function form `ObservableArray` doesn't handle initial value correctly. The first value will always be the first item in the list and not the initial value provided as a parameter.

**To Reproduce**
```javascript
let products = new ObservableArray([{price:10},{price:20},{price:30}]);

const sum = products.reduce((sum, p, index) => {
  console.log('Iteration', index, 'Sum:', sum, 'Type of sum:', typeof(sum), 'Price:', p.price);
  return sum + p.price;
}, 0);

console.log('Final sum', sum, typeof(sum));

// Output
// Iteration 1 Sum: { "price": 10 } Type of sum: object Price: 20
// Iteration 2 Sum: "[object Object]20" Type of sum: string Price: 30
// Final sum "[object Object]2030" string
```
Run the code and see that  `sum` will be `{price:10}` on the first iteration. This is wrong. It should be `0`. However, if we didn't pass an initial value as a parameter this would be the expected behaviour.

**Expected behavior**
On the first iteration the `sum` should be `0` as it is provided as the initial value.

**Comment by NickIliev** [comment]
@elonmallin I think you are dealing with [this known problem](https://stackoverflow.com/a/5732087/4936697) of `reduce`.

Basically try the following:
```TS
let products = new ObservableArray([{ price: 10 }, { price: 20 }, { price: 30 }]);

const red1 =  (a, b) => ({ price: a.price + b.price });
let res = products.reduce(red1, 0);
console.log(res);
// or directly
console.log(res.price);
```

**Comment by elonmallin** [comment]
Hi @NickIliev, that link doesn't seem like a problem of reduce? It's just how it's supposed to work I think. The first parameter should always be what you return in the function from the previous iteration. The edge case is the first time when it will either be the first item in the array or the initial value provided as a parameter.

So I would say my code should still work. `sum` should be `0` the first time since it's the initial value. The problem is that in `ObservableArray.reduce` the initial value is ignored and the first argument (in this case `sum`) is just the first item in the array instead. So initial value is completely ignored, it does nothing.

Try the same thing in your console in your browser and see it work:
```javascript
[{price:10},{price:20},{price:30}].reduce((sum, p) => sum + p.price, 0);
// 60
```

So this still seems like a bug to me. Unless `ObservableArray` decided to implement `reduce` in another way than browsers and as defined on [mozilla docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce).

**Comment by NickIliev** [comment]
@elonmallin [use the Mozilla sire reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce) for reduce and change the snippet to use your array

```JS
// add change the runnable code with your code
const array1 = [{price:10},{price:20},{price:30}];
const reducer = (accumulator, currentValue) => accumulator + currentValue.price;
```

Result (in Chrome) is:
```JS
> "[object Object]2030"
> 65  // this is the value for the reduce with initial value
```

Which confirms that you need to destruct your object as shown in my previous comment.

**Comment by elonmallin** [comment]
@NickIliev What am I missing? What you wrote shows that `ObservableArray.reduce` is ignoring the last parameter (`0` in my example or `5` in the mozilla example).

As you wrote:
```
> "[object Object]2030"
> 65  // this is the value for the reduce with initial value
```
And I **am using** the **initial value** so it should work for me. I should be getting `60`.

My first example simplified shows the problem:
```javascript
const products = new ObservableArray([{price:10},{price:20},{price:30}]);
const reducer = (sum, p) => sum + p.price;
const sum = products.reduce(reducer);
const sum2 = products.reduce(reducer, 0); // Notice the initial value 0
console.log(sum, sum2);

// Actual output
> "[object Object]2030" // Without initial value
> "[object Object]2030" // With initial value

// Expected output
> "[object Object]2030" // Without initial value
> 60 // With initial value
```

The problem, as you can see is that the **initial value** (`0` in my example) is ignored completely by `ObservableArray.reduce`.

**Comment by NickIliev** [comment]
@elonmallin ok now I see what you mean - it seems that only when **the initial value is set to 0** it is not respected and only then the bug appears. Marking this one as a bug.

**Comment by elonmallin** [comment]
Okey 👍 

Didn't know it was only for `0`. But makes sense that could be the case if they're just checking that `initialValue` is truthy and not `initialValue === undefined` or something.

**Comment by NickIliev** [comment]
Resolved via [https://github.com/NativeScript/NativeScript/pull/6402](https://github.com/NativeScript/NativeScript/pull/6402) - thank you @surdu !

**Comment by surdu** [comment]
@NickIliev As always, my pleasure 😉
