### ISSUE TITLE
[iOS] providing an option to specify the modal view's UIModalPresentationStyle 

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#6387]
Providing a way to specify the modal view's UIModalPresentationStyle by choosing some of the available [optional values from iOS docs](https://developer.apple.com/documentation/uikit/uimodalpresentationstyle).
```
case fullScreen
A presentation style in which the presented view covers the screen.

case pageSheet
A presentation style that partially covers the underlying content.

case formSheet
A presentation style that displays the content centered in the screen.

case currentContext
A presentation style where the content is displayed over another view controller’s content.

case custom
A custom view presentation style that is managed by a custom presentation controller and one or more custom animator objects.

case overFullScreen
A view presentation style in which the presented view covers the screen.

case overCurrentContext
A presentation style where the content is displayed over another view controller’s content.

case blurOverFullScreen
A presentation style that blurs the underlying content before displaying new content in a full-screen presentation.

case popover
A presentation style where the content is displayed in a popover view.

case none
A presentation style that indicates no adaptations should be made.
```

**Comment by surdu** [comment]
I could take this one, if it's ok.

@tsonevn How do you envision this be implemented: pass an argument to showModal that will only be used on iOS ?

**Comment by demetrio812** [comment]
Hello guys, any news on this feature? Is there a workaround in the meantime that works across multiple iOS versions?

Cheers

**Comment by tsonevn** [comment]
HI @demetrio812,
Currently, the workaround is to change the UIModalPresentationStyle directly in the [tns-core-modules](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/core/view/view.ios.ts#L405).
Keep in mind that if you delete the **node_modules** folder, you have to make this change again.

**Comment by cerireyhan** [comment]
@tsonevn Can this also be used with nativescript-angular? Its not implemented in ModalDialogService.

**Comment by dottodot** [comment]
It seems to have been implemented but no way to use in Angular.
