### ISSUE TITLE
Nested repeaters

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#639]
Currently you aren't able to have nested repeaters. Nested repeaters is a requirement if we want to group objects together.

An example being:

```xml
<Repeater items="{{ bank }}">
  <Repeater.itemTemplate>
    <Label cssClass="bank-label"  text="{{ title }}"/>
    <Repeater items="{{ accounts }}">
      <Repeater.itemTemplate>
        <Label cssClass="accounts-label" text="{{ name }}"/>
      </Repeater.itemTemplate>
    </Repeater>
  </Repeater.itemTemplate>
</Repeater>
```

Using this object which is bound to `bank`:
```js
var test = [
   {
      "title":"Westpac",
      "accounts":[
         {
            "name":"Westpac Checking"
         },
         {
            "name":"Westpac Credit"
         }
      ]
   },
   {
      "title":"ASB",
      "accounts":[
         {
            "name":"ASB Checking"
         },
         {
            "name":"ASB Credit"
         }
      ]
   }
];
```

**Comment by lscown** [comment]
closing due to https://github.com/NativeScript/NativeScript/pull/563

**Comment by stevetayloruk** [comment]
Did this ever get completed- if so, what is the syntax to bind the inner array?

**Comment by lscown** [comment]
Hey @stevetayloruk, they added support for nested repeaters since then and the syntax is the same as I originally proposed above. However, nesting repeaters creates a lot of layouts in your app, and we found it slowed our page load times down largely. 

I suggest using a ListView with flattened data, where you check each item's nest level and a apply a style accordingly.

**Comment by stevetayloruk** [comment]
@lscown thanks for the feedback. I'll take your advice.

thanks

**Comment by FlashDark** [comment]
@lscown When using ListView, the click event effect (ripples on Android) appears in the wrong position, especially when the repeater is pretty big. Just tried having 10 items in a stacked repeater and clicking on the on at the bottom, but the effect appeared above the click position. It seems that ListView  Item is handling the click, therefore the ripples effect appears closed to the center of the ListView Item itself.
@stevetayloruk Have you solved this? What combination of views/repeaters did you use?

**Comment by lscown** [comment]
@FlashDark Have you tried without repeaters at all? My guess is that repeaters are causing you grief. I recommend what I suggested above: flatten your data and making sure to be able to identify the nest level, and then setting the visibility per level. For example, inside the ListView item template:

```xml
<StackLayout visibility="{{ level == 0 : 'visible' : 'collapsed' }}">
</StackLayout>
<StackLayout visibility="{{ level == 1 : 'visible' : 'collapsed' }}">
</StackLayout>
```

`level` being added to the data in the flattening process.

**Comment by FlashDark** [comment]
@lscown Thanks for your response! I see what you mean, but that means that "level==2" element will be created regarding if it's visible or not. Will that cause greater memory usage when having, say, 200 elements?

**Comment by lscown** [comment]
@FlashDark I *think* if the element is collapsed, it's not present in memory. Though, if it were 'hidden' it would be. Regardless, the memory usage will be much less compared to the repeater approach. 

Both iOS and Android native ListView components (ListView, UITableView) will manage the memory properly when the item is not on screen.

**Comment by FlashDark** [comment]
@lscown Well, I have actually tried 5M items running in Genymotion emulator, with 3 different templates in it. It does work and doesn't seem to have any lags at all.

```html
<ListView items="{{ data }}">
 <ListView.itemTemplate>
  <StackLayout>
   <GridLayout visibility="{{ type == 'template_1' ? 'visible' : 'collapsed' }}">
    ...
   </GridLayout>
   <GridLayout visibility="{{ type == 'template_2' ? 'visible' : 'collapsed' }}">
    ...
   </GridLayout>
   <GridLayout visibility="{{ type == 'template_3' ? 'visible' : 'collapsed' }}">
    ...
   </GridLayout>
  </StackLayout>
 </ListView.itemTemplate>
</ListView>
```
Having more records seems to be unstable and occasionally the app did not launch. I have no possibility to test this on a physical device, but I hope it will work, and 10K records with 20 different templates (200K variations) will not be a problem for device to handle (no one will probably have to deal with such a big numbers, but that just shows the potential of the platform).

Thanks for your help!

**Comment by stevetayloruk** [comment]
I agree with @lscown. I know the flattened data is not ideal though.

Has anyone looked at the this?: https://www.npmjs.com/package/nativescript-sectioned-list-view
