### ISSUE TITLE
Run on android takes too long (too slow)

### ISSUE THREAD

**Issue by phacic** [NativeScript/NativeScript#6400]
**Environment**
 - tns 4.2.3
 - tns-core-modules 4.2.1
 - tns-android 4.2.0
 - nativescript-imagepicker
 - angular 6.1

**Describe the bug**
`tns run android --emulator` takes too long
![screenshot 10](https://user-images.githubusercontent.com/29029376/46810588-ecec4480-cd68-11e8-9896-2a2f1f44e6e0.png)
it got to this point (app:mergeDebugAssests) after like a minute and after 27 minutes it was still there

![screenshot 12](https://user-images.githubusercontent.com/29029376/46810850-713ec780-cd69-11e8-9245-80dcc4283026.png)

I went searching for answers and i edited `gradel.properties` to
`org.gradle.parallel=true`

`org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8`

`org.gradle.daemon=true`

Actually these changes brought the build time from around `1hr` to `30mins`

here is my `package.json`

{
  "name": "MyContacts",
  "license": "SEE LICENSE IN <your-license-filename>",
  "version": "0.0.0",
  "nativescript": {
    "id": "org.nativescript.myContacts",
    "tns-android": {
      "version": "4.2.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.1.0",
    "nativescript-angular": "~6.1.0",
    "nativescript-imagepicker": "^6.0.4",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~6.2.0",
    "tns-core-modules": "~4.2.0",
    "webpack": "^4.20.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/core": "^0.8.0",
    "@angular/cli": "^6.2.0",
    "@angular/compiler-cli": "~6.1.0",
    "@nativescript/schematics": "~0.3.0",
    "@ngtools/webpack": "~6.2.0",
    "nativescript-dev-sass": "~1.6.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "^0.16.0",
    "typescript": "~2.7.2"
  }
}

I don't think i need to say how stressful this is. Any help to reduce the build time would be appreciated

**Comment by NickIliev** [comment]
@phacic verify that you are using 64-bit Java (and that the hardware you are working with is supporting 64-bit operations). Make sure that you have enough free memory before building a NativeScript app. On Windows OS I would recommend using 8 or more RAM - please do let me know what are the hardware specifications on your PC.

Closing this issue as it is not related to the NativeScript modules. Still, post the related information so we could continue our discussion.

**Comment by phacic** [comment]
Am using a 64bit Windows machine with 4GB ram. With Java I have both the 64 and 32 bit installed

**Comment by NickIliev** [comment]
@phacic make sure your `JAVA_HOME` is pointing to the 64-bit Java version.

**Comment by phacic** [comment]
@nick it is. I will upgrade the ram and see what happens
