### ISSUE TITLE
So what is the solution to check if "isDirectory"?

### ISSUE THREAD

**Issue by awebi** [NativeScript/NativeScript#6407]
_Originally posted by @awebi in https://github.com/NativeScript/NativeScript/issue_comments#issuecomment-429424982_

**Comment by tsonevn** [comment]
Hi @awebi,
Check out the provided solution in this forum thread [here](https://discourse.nativescript.org/t/file-system-getentity-how-do-i-check-if-entity-is-folder-or-file/7036)
