### ISSUE TITLE
Introducing Nativesctipt-Markdown

### ISSUE THREAD

**Issue by b02505048** [NativeScript/NativeScript#6412]
**Is your feature request related to a problem? Please describe.**
 
Since Nativescript mentioned 
> no WebViews, resulting in native-like performance and UX. 

but WebView is the only way to render markdown content so far...

**Describe the solution you'd like**

```
<Markdown :src="marked_content" />
// where marked_content = " **Hello** World! It could be *cool* ![Img](https://www.imgur.com) "
```
Inspired by [react-native-simple-markdown](https://github.com/CharlesMangwa/react-native-simple-markdown)

**Describe alternatives you've considered**

Hmm...well...404.

**Additional context**

The result is just smth like Medium App ![medium app](https://www.geeky-gadgets.com/wp-content/uploads/2015/03/medium.jpg)

**Comment by tsonevn** [comment]
Hi @b02505048,
Thank you for the provided suggestion. Indeed this seems to be a perfect candidate for a new plugin. You can check our [building-plugins](https://docs.nativescript.org/plugins/building-plugins) article in NativeScript docs and the [nativescript-plugin-seed](https://github.com/NativeScript/nativescript-plugin-seed), which is a good starting point for building a new plugin.
