### ISSUE TITLE
Runtime adding tab in TabView 

### ISSUE THREAD

**Issue by jvermirovsky** [NativeScript/NativeScript#6414]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 4.2.4
 - Cross-platform modules: 4.2.1
 - Android Runtime: 4.2.0
 - iOS Runtime: 4.2.0
 - Plugin(s): none

**Describe the bug**
When I dynamically initialize tabs in TabView eveything looks good, but when it is added new tab in runtime content of active tab dissapear. Content missing in neighbour of that tab too. But when I go to last tab and back, content is in correctly in all tabs. Content of newly added tab is correctly there. 

**To Reproduce**
1, Run application from sample project - you will see 3 tabs with listview.
2, Click on random item in listview.
3, New tab is added but content of active tab dissapear.
4, Click to new tab and back to tab 1 - content in tab1 is back.

**Expected behavior**
Added new tab but contents of active tab not dissapear.

**Sample project**
[Playground sample](https://play.nativescript.org/?template=play-ng&id=yrPidv&v=3)

**Comment by NickIliev** [comment]
@jvermirovsky adding/removing tab view items are not officially supported operations and is a known limitation for that widget. You could handle this problem by either rebuild the entire tab view when add/remove a tab item is triggered or by implementing a custom to view control using Angular UI - for example here is a[ great Playground](https://play.nativescript.org/?template=play-ng&id=WvQnzu&v=19) demonstrating Angular created custom tab bars (more similar demos in the [marketplace](https://market.nativescript.org/?tab=samples&framework=all_frameworks&category=all_samples))

**Comment by bjesus** [comment]
Can anyone share an example of how to rebuild the the entire tab view?
