### ISSUE TITLE
iOS Angular6: empty ActionBar visible while canActivate route guard hasn't resolved

### ISSUE THREAD

**Issue by jnorkus** [NativeScript/NativeScript#6419]
**Environment**
 - CLI: 4.2.4
 - Cross-platform modules: 4.2.1
 - Android Runtime: 4.2.0
 - iOS Runtime: 4.2.0
 - Plugin(s): none
 - Angular: 6.1.0

**Describe the bug**
On iOS only an empty ActionBar is visible while a route guard's `canActivate` is not resolved.

**To Reproduce**
The issue is very easily reproducable by creating a new NS Angular app using `tns new <app> --template=angular`, then adding a `canActivate` guard to the "items" route. Then running `tns run ios`.

app.routing.ts
```
@Injectable()
export class TheGuard implements CanActivate {
    canActivate(): Observable<boolean> {
        return timer(1000).pipe(
            map(_ => true)
        );
    }
}

const routes: Routes = [
    { path: "", redirectTo: "/items", pathMatch: "full" },
    { path: "items", component: ItemsComponent, canActivate: [TheGuard] },
    { path: "item/:id", component: ItemDetailComponent },
];
```

**Expected behavior**
A white blank page without any ActionBar.

**Additional context**
The issue was not seen with Angular 5.2.0.

Angular 6.1.0
![image](https://user-images.githubusercontent.com/5137138/47023950-6faa4080-d169-11e8-8ad6-75a71b2269ea.png)

Angular 5.2.0
![image](https://user-images.githubusercontent.com/5137138/47024028-92d4f000-d169-11e8-9065-33dee7347304.png)

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-angular #1558](https://github.com/NativeScript/nativescript-angular/issues/1558) via [**ZenHub**](https://www.zenhub.com/)
