### ISSUE TITLE
Support for HEVC encoded images in ImageSource and camera plugin

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/NativeScript#6420]
In the recent versions of iOS (11) and Android (9), there is built-in support for HEVC-encoded images. With this encoding, one can take very high quality pictures in small files.

Can you add support for this image codec?

**Comment by NickIliev** [comment]
Just as an additional info - the Android implementation wouldn't guarantee that the HECV encoded images will work on all Android phones - more [here](https://www.cnet.com/news/android-p-heic-photo-compression-feature-wont-work-on-lower-end-phones/)
