### ISSUE TITLE
How to get Audio From the Android MediaStore

### ISSUE THREAD

**Issue by awebi** [NativeScript/NativeScript#6424]
**Is your feature request related to a problem? Please describe.**
 
I tried fetching it this way
```
  let proj =[ android.provider.MediaStore.Audio.Media._ID,android.provider.MediaStore.Audio.Media.DISPLAY_NAME ];
  let audioCursor = new 
 android.content.Context().getContentResolver().query(android.provider.MediaStore.Audio.Media.EXTERNAL_CONTENT_URI, proj, null, null, null);
        console.log(audioCursor);
        let audioList: Array<String>;
        if(audioCursor != null){
            if(audioCursor.moveToFirst()){
                do{
                    let audioIndex = audioCursor.getColumnIndex(android.provider.MediaStore.Audio.Media.DISPLAY_NAME);
  
                    audioList.push(audioCursor.getString(audioIndex));
                    // console.log(audioCursor.getString(audioIndex));
                }while(audioCursor.moveToNext());
            }
        }
        audioCursor.close();
```
But i was getting 

`10-17 00:04:53.776  7857  7857 F art     : art/runtime/java_vm_ext.cc:470]     from java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[])
10-17 00:04:53.776  7857  7857 F art     : art/runtime/java_vm_ext.cc:470]   at com.tns.Runtime.callJSMethodNative(Native method)
10-17 00:04:53.776  7857  7857 F art     : art/runtime/java_vm_ext.cc:470]   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
10-17 00:04:53.776  7857  7857 F art     : art/runtime/java_vm_ext.cc:470]   at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
10-17 00:04:53.776  7857  7857 F art     : art/runtime/java_vm_ext.cc:470]   at com.tns.Runtime.callJSMethod(Runtime.java:983)
10-17 00:04:53.776  7857  7857 F art     : art/runtime/java_vm_ext.cc:470]   at com.tns.Runtime.callJSMethod(Runtime.java:967)
10-17 00:04:53.776  7857  7857 F art     : art/runtime/java_vm_ext.cc:470]   at com.tns.Runtime.callJSMethod(Runtime.java:959)
10-17 00:04:53.795  7857  7857 F art     : art/runtime/runtime.cc:403]   at com.tns.Runtime.callJSMethodNative(Native method)
10-17 00:04:53.795  7857  7857 F art     : art/runtime/runtime.cc:403]   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
10-17 00:04:53.795  7857  7857 F art     : art/runtime/runtime.cc:403]   at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
10-17 00:04:53.795  7857  7857 F art     : art/runtime/runtime.cc:403]   at com.tns.Runtime.callJSMethod(Runtime.java:983)
10-17 00:04:53.795  7857  7857 F art     : art/runtime/runtime.cc:403]   at com.tns.Runtime.callJSMethod(Runtime.java:967)
10-17 00:04:53.795  7857  7857 F art     : art/runtime/runtime.cc:403]   at com.tns.Runtime.callJSMethod(Runtime.java:959)
10-17 00:04:53.795  7857  7857 F art     : art/runtime/runtime.cc:403]   at com.tns.Runtime.callJSMethodNative(Native method)
10-17 00:04:53.795  7857  7857 F art     : art/runtime/runtime.cc:403]   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
10-17 00:04:53.795  7857  7857 F art     : art/runtime/runtime.cc:403]   at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
10-17 00:04:53.795  7857  7857 F art     : art/runtime/runtime.cc:403]   at com.tns.Runtime.callJSMethod(Runtime.java:983)
10-17 00:04:53.795  7857  7857 F art     : art/runtime/runtime.cc:403]   at com.tns.Runtime.callJSMethod(Runtime.java:967)
10-17 00:04:53.795  7857  7857 F art     : art/runtime/runtime.cc:403]   at com.tns.Runtime.callJSMethod(Runtime.java:959)`

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NickIliev** [comment]
@awebi please note that this repository is for logging bugs and issues related to NativeScript. Your issue seems related to the way of handling a specific native Android functionality (see [this thread](https://stackoverflow.com/a/6975971/4936697)). Post your question ins [SO](https://stackoverflow.com/questions/tagged/nativescript) or in the community slack channel.

Closing the issue as how-to related.

Note: possible sample for working with MediaStore can be found [here](https://github.com/NativeScript/NativeScript/issues/5838#issue-324591219).
