### ISSUE TITLE
TypeError: undefined is not an object (frame.topmost().currentPage) iOS

### ISSUE THREAD

**Issue by fhackenb** [NativeScript/NativeScript#6425]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.10
 - iOS Runtime: 4.2.0
 - Plugin(s): keyboard

**Describe the bug**
I recently updated from angular 4 to angular 6 and am now getting an error whenever I open the keyboard (i.e. Dialog.prompt() or click in a TextView or SearchBar).

My error is:

> JavaScript stack trace:
1   notifyKeyboard@file:///app/tns_modules/nativescript-keyboardshowing/index.js:61:38
2   @file:///app/tns_modules/nativescript-keyboardshowing/index.js:42:23
3   onReceive@file:///app/tns_modules/tns-core-modules/application/application.js:30:32
4   UIApplicationMain@[native code]
5   start@file:///app/tns_modules/tns-core-modules/application/application.js:272:26
6   run@file:///app/tns_modules/tns-core-modules/application/application.js:300:10
7   bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:153:26
8   bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:87:38
9   bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:76:26
10  anonymous@file:///app/main.js:7:57
11  evaluate@[native code]
12  moduleEvaluation@[native code]
13  @[native code]
14  promiseReactionJob@[native code]
JavaScript error:
file:///app/tns_modules/nativescript-keyboardshowing/index.js:61:38: JS ERROR TypeError: undefined is not an object (evaluating 'frame.topmost().currentPage')

**To Reproduce**

Some sample code that causes this error for me:
     `const Dialogs = require("ui/dialogs");
       Dialogs.prompt({
            title: "Test",
            message: "Test",
            okButtonText: "Ok",
            cancelButtonText: "Cancel",
            inputType: Dialogs.inputType.text
        });
`

And my package.json:

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.funfangle.pos",
    "tns-ios": {
      "version": "4.2.0"
    }
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.1.0",
    "nativescript-angular": "^6.1.0",
    "nativescript-appversion": "^1.4.1",
    "nativescript-bitmap-factory": "^1.7.1",
    "nativescript-bluetooth": "^1.3.1",
    "nativescript-couchbase": "^1.0.18",
    "nativescript-fontawesome": "^1.0.0",
    "nativescript-insomnia": "^1.2.1",
    "nativescript-keyboardshowing": "^1.0.0",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-material-icons": "^1.0.3",
    "nativescript-ng2-fonticon": "^1.3.4",
    "nativescript-orientation": "^2.2.0",
    "nativescript-print-star": "file:nativescript-print-star-0.1.6.tgz",
    "nativescript-screen-orientation": "^2.0.0",
    "nativescript-secure-storage": "^2.3.0",
    "nativescript-sentry": "^1.5.2",
    "nativescript-square-plugin": "^1.0.5",
    "nativescript-star-printer": "^1.2.1",
    "nativescript-tappy": "^1.0.6",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-ui-core": "^2.0.0",
    "nativescript-ui-listview": "^3.7.1",
    "nativescript-ui-sidedrawer": "^4.3.1",
    "nativescript-urlhandler": "^1.2.2",
    "nativescript-uuid": "0.0.1",
    "reflect-metadata": "~0.1.10",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.3.3",
    "tns-core-modules": "^4.2.1",
    "tns-platform-declarations": "^4.2.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^6.1.10",
    "@ngtools/webpack": "^6.2.5",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "~0.1.19",
    "codelyzer": "~4.0.2",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.7.4",
    "nativescript-dev-webpack": "^0.16.2",
    "nativescript-worker-loader": "^0.9.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "~6.0.6",
    "tslint": "~5.8.0",
    "typescript": "~2.7.2",
    "uglifyjs-webpack-plugin": "^2.0.1",
    "webpack": "^4.20.2",
    "webpack-bundle-analyzer": "^3.0.3",
    "webpack-sources": "^1.3.0"
  }
}
```

**Expected behavior**
Keyboard should open and allow me to type

**Comment by tsonevn** [comment]
Hi @fhackenb,
I reviewed the provided error log, and it seems that the crash in the ap is related to the [nativescript-keyboardshowing](https://github.com/NathanaelA/nativescript-keyboardshowing). I would suggest contacting the author of the plugin by opening a [new issue ](https://github.com/NathanaelA/nativescript-keyboardshowing/issues) in the plugins' repository.
