### ISSUE TITLE
TabView State not maintained while using HMR

### ISSUE THREAD

**Issue by shiv19** [NativeScript/NativeScript#6426]
**Environment**
 - CLI: 5.0.0-2018-10-16-12488
 - Cross-platform modules: 5.0.0-rc-2018-10-16-182917-07
 - Android Runtime: 5.0.0-rc-2018-10-15-143937-09
 - iOS Runtime: N/A
 - Plugin(s): N/A
 - Dev-webpack: 0.17.0-rc.0

**Description**
HMR is not maintaining the state of TabView.

**To Reproduce**
Open any tab other than the first tab of a TabView Layout, and make some changes to that file,
when you save the file, after HMR does its thing, the TabView always switches to the first tab.

**Expected behavior**
The TabView's state should be maintained as it is.

**Sample project**
[hmrDemo.zip](https://github.com/NativeScript/NativeScript/files/2489018/hmrDemo.zip)

**Comment by tsonevn** [comment]
HI @shiv19,
Thank you for the provided sample project. I was able to recreate the case. We will investigate further this issue and will provide more info.
Related to issue [#6398](https://github.com/NativeScript/NativeScript/issues/6398)

**Comment by patrikengborg** [comment]
Any progress on this? I'm experiencing even more problems after the NS 5.3 update. Prior to that, all I had to do when HMR was having problems was to restart the app. Now I need to cancel the terminal session and rerun `tns run ios --hmr`to even see my changes.

**Comment by vchimev** [comment]
Hey @shiv19 and @patrikengborg,

This has been implemented for NativeScript applications with JavaScript and TypeScript:
- related issue: https://github.com/NativeScript/NativeScript/issues/7145
- available with `tns-core-modules@next`
- official release with NativeScript 5.4.0

The improved behavior consists of handling updates on `View` level which allows:
- preserving application state when not only `Frame`, but also`TabView` and `SideDrawer` (any `View` successor) are application roots
- applying changes per module, without performing navigation
- detect updates on app root module and reset application content

**Comment by patrikengborg** [comment]
I'm still having quite extensive problems with TabView and HMR, as described in my comment above. The provided answer was promising, but sadly didn't make much of a difference after trying out tns-core-modules@next

Has this been tested in NativeScript Vue? I forgot to mention that's what I'm using.
