### ISSUE TITLE
Pairing to Mac for Windows-based iOS developers

### ISSUE THREAD

**Issue by beam-codegrind** [NativeScript/NativeScript#6427]
### Is your feature request related to a problem? Please describe.
Life is hard for Windows-based iOS developers who want to develop app using NativeScript, since we must rely on Sidekick or other Mac-based teammates to build it because building native iOS applications requires access to Apple's build tools, which only run on a Mac.

### Describe the solution you'd like
NativeScript should be able to discover, connect to, authenticate with, and remember Mac build hosts so that Windows-based iOS developers can work productively.
Based on [this Xamarin's feature](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/), NativeScript should have these similar workflows:

* Developers can write NativeScript iOS code in Windows.
* NativeScript opens a network connection to a Mac build host and uses the build tools on that machine to compile and sign the iOS app.
* There is no need to run a separate application on the Mac – NativeScript invokes Mac builds securely over SSH.
* Multiple instances of NativeScript can connect to the Mac simultaneously.
* It's possible to use the Windows command-line to build iOS applications.

### Describe alternatives you've considered
Not much of an alternative, but can we reuse Sidekick's code and application ? Just point it to other Mac in the network.

### Additional context
This feature request is based on [this Xamarin's feature](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/)

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #4041](https://github.com/NativeScript/nativescript-cli/issues/4041) via [**ZenHub**](https://www.zenhub.com/)
