### ISSUE TITLE
nativescript-ui-listview not being installed

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#6432]
I have a  vanilla ListView installed and working and now want to take advantage of advanced RadListView. I followed the instruction to install the plugin:

```
:\Users\Jokro\Software\NativeScript\mappi> tns plugin add nativescript-ui-listview
+ nativescript-ui-listview@3.7.2
added 2 packages from 1 contributor, removed 1 package and audited 25 packages in 2.602s
found 0 vulnerabilities
```

In Page I added: 
```
<Page xmlns:lv="nativescript-ui-listview" 
      xmlns="http://schemas.nativescript.org/tns.xsd"
      loaded="onLoaded">
```

And I adapted the other lv elements.

When running I get the error:

`System.err:    > Module '/data/data/org.nativescript.mappi/files/app/tns_modules/nativescript-ui-listview' not found for element 'nativescript-ui-listview:RadListView'.`

Wen I check, directory tns-modules, the module nativescript-ui-listview is missing

When I run tns plugin add nativescript-ui-listview a second time, it replies the module is already installed.

tns doctor replies:
`PS C:\Users\Jokro\Software\NativeScript\mappi> tns doctor
√ Getting environment information

No issues were detected.
√ Your ANDROID_HOME environment variable is set and points to correct directory.
√ Your adb from the Android SDK is correctly installed.
√ The Android SDK is installed.
√ A compatible Android SDK for compilation is found.
√ Javac is installed and is configured properly.
√ The Java Development Kit (JDK) is installed and is configured properly.
√ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
√ Getting NativeScript components versions information...
√ Component nativescript has 4.2.4 version and is up to date.
‼ Update available for component tns-core-modules. Your current version is 4.2.0 and the latest available version is 4.2.1.
√ Component tns-android has 4.2.0 version and is up to date.
√ Component tns-ios has 4.2.0 version and is up to date.
PS C:\Users\Jokro\Software\NativeScript\mappi>`

I run in  VS on windows 10, for android emulator, using TypeScript
`Version: 1.28.1 (user setup)
Commit: 3368db6750222d319c851f6d90eb619d886e08f5
Date: 2018-10-11T18:13:53.910Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64`

**Comment by NickIliev** [comment]
@jokro remove the `platforms` folder and rebuild the project with the `nativescript-ui-listview` added in your dependencies list

```
rm -rf platforms
npm i nativescript-ui-listview --save
tns platform add android
tns run android
```

**Comment by jokro** [comment]
Nickliev, thx for your prompt reply.
The sulutions is still simpler: restart Visual Studio. Only then the installed module becomes visible in the VS project. I Always do this when having a problem, but this time I forgot my standard reaction.
Thx again

**Comment by jokro** [comment]
Although app/tns_modules/nativescript-ui-listview' is present in the project, I still get the following error
S`ystem.err:    > Module '/data/data/org.nativescript.demo/files/app/tns_modules/nativescript-ui-listview' not found for element 'nativescript-ui-listview:RadListView'.`

I installed a new project and still got this error.


When going through the module, i find two files showing errors because three slashes have been used to comment. See screenshots:
![image](https://user-images.githubusercontent.com/6855225/47214438-39093b80-d39e-11e8-9260-2f7f3df357c4.png)
![image](https://user-images.githubusercontent.com/6855225/47214464-4aeade80-d39e-11e8-8ce5-666dae390c9c.png)

**Comment by NickIliev** [comment]
@jokro please post the `package.json` content and the XML page where the RadListView is used

**Comment by jokro** [comment]
```
{
    "nativescript": {
        "id": "org.nativescript.demo",
        "tns-android": {
            "version": "4.2.0"
        },
        "tns-ios": {
            "version": "4.2.0"
        }
    },
    "description": "NativeScript Application",
    "license": "SEE LICENSE IN <your-license-filename>",
    "repository": "<fill-your-repository-here>",
    "dependencies": {
        "nativescript-theme-core": "~1.0.4",
        "nativescript-ui-listview": "^3.7.2",
        "tns-core-modules": "~4.2.0"
    },
    "readme": "NativeScript Application",
    "devDependencies": {
        "nativescript-dev-typescript": "^0.7.4",
        "typescript": "^3.1.1"
    }
}
```


```
<!-- >> listview-first-look -->
<Page  loaded="onPageLoaded" xmlns:lv="nativescript-ui-listview" xmlns="http://www.nativescript.org/tns.xsd">
    <lv:RadListView items="{{ dataItems }}" >
        <lv:RadListView.itemTemplate>
            <StackLayout orientation="vertical">
                <Label fontSize="20" text="{{ itemName }}"/>
                <Label fontSize="14" text="{{ itemDescription }}"/>
            </StackLayout>
        </lv:RadListView.itemTemplate>
    </lv:RadListView>
</Page>
<!-- << listview-first-look -->

```

**Comment by jokro** [comment]
also tsconfig.json:

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "lib": [
            "es6",
            "dom"
        ],
        "baseUrl": ".",
        "paths": {
            "~/*": [
                "app/*"
            ],
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
}
```

**Comment by jokro** [comment]
Solved.

nativescript-ui-listview must be installed _before_ platform android is added.
I think this sounds logic...
