### ISSUE TITLE
Angular http observable not triggering

### ISSUE THREAD

**Issue by gonniegijsen** [NativeScript/NativeScript#6435]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  4.2.4
 - Cross-platform modules: 4.2.1
 - Android Runtime: 4.2.0
 - iOS Runtime: 4.2.0
 - Plugin(s):

**Describe the bug**

This is more a question;
I'm working on an application with nativescript-angular that needs to send information to the server each 10minutes (I need access to my angular services as well). When the phone is locked and charging everything works fine but when I remove the charger, the http requests take ages to complete and when I unlock it everything works again.

**To Reproduce**

```typescript
setInterval(() =>
{
// do stuff
}, 60000);
```
lock the phone without charger, after some time the interval will not trigger correctly (or not trigger at all)

**Expected behavior**

**Sample project**

**Additional context**

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1561
