### ISSUE TITLE
SearchBar .isEnabled and .isUserInteractionEnabled does not work

### ISSUE THREAD

**Issue by OsamaAbbas** [NativeScript/NativeScript#6437]
**Environment**
 - CLI: 4.2.4
 - Cross-platform modules: 4.2.1
 - Android Runtime: 4.2.0
 - iOS Runtime: 4.2.0
 - Plugin(s): None

**Describe the bug**
`SearchBar.isEnabled = false` does not work on iOS and Android devices. It has no effect.
and
`SearchBar.isUserInteractionEnabled = false` does not work on Android devices. It has no effect too.

**To Reproduce**
Just add these components and run the app, you will still be able to type inside the search box:
`<SearchBar isEnabled="false" />`
`<SearchBar isUserInteractionEnabled="false" />`

**Expected behavior**
Users should not be able to interact with search boxes, just like `<TextField />` and `<Button />`. However, Setting these properties to false has no effect.

**Sample project**
[Here in Plain Javascript](https://play.nativescript.org/?template=play-js&id=MWHqSQ&v=4)

**Additional context**
Same problem occurs in Vue. In fact, I discovered it there:
[Same project in Vue](https://play.nativescript.org/?template=play-vue&id=GjPBjF)

**Comment by tsonevn** [comment]
Hi @OsamaAbbas,
Thank you for the provided sample project and workaround.
I was able to recreate the described case on my side and will mark the issue as a bug. I would suggest keeping track of the issue for further info.

**Comment by tsonevn** [comment]
Hi @OsamaAbbas,
Thank you for the provided sample project and workaround.
I was able to recreate the described case on my side and will mark the issue as a bug. I would suggest keeping track of the issue for further info.

**Comment by tsonevn** [comment]
Hi @OsamaAbbas,
Thank you for the provided sample project and workaround.
I was able to recreate the described case on my side and will mark the issue as a bug. I would suggest keeping track of the issue for further info.

**Comment by tsonevn** [comment]
Hi @OsamaAbbas 
Thank you for the provided sample project and workaround.
I was able to recreate the reported case on my side and will mark the issue as a bug. I would suggest keeping track of the issue for further info.
