### ISSUE TITLE
RadListView item

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#6438]
1. I have a working example of Listview, with itemLongPress. When I convert ListView to RadListView,  my onItemLongPress function is not called anymore. Is this a bug ? 

2. I found a workaround by adding a longPress action on a StackLayout inside the itemtemplate. 

3. This workaround stops functioning if I set swipeActions = true. see the example in [playground](https://play.nativescript.org/?template=play-tsc&id=Y6GyQn&v=3)  I stripped the code until the bare minimum to show the problem. If swipeActions is set false, and a long press is being given, the longPress function is called, which shows in the console.log. If the longPress action is removed, the itemLongPress is never called, illustrating the above point 1.

How can I use longPress for items of a RadListView item ? I would like to use other gestures too, is this possible ? I only found how to use itemTap, which is working alright.

Thx

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#888

**Comment by NickIliev** [comment]
@jokro please post the issue in the UI repository [here](https://github.com/telerik/nativescript-ui-feedback/issues). Closing this one as it is not related to Nativesdcript and NativeScript nodules
