### ISSUE TITLE
Default iosOverflowSafeArea="false" is not working inside ScrollView

### ISSUE THREAD

**Issue by cerireyhan** [NativeScript/NativeScript#6439]
- CLI: 5.0.0-2018-10-16-12488
 - Cross-platform modules: 5.0.0-rc-2018-10-16-182917-07
 - Android Runtime: 5.0.0-rc-2018-10-18-172901-01
 - iOS Runtime: 5.0.0-rc-2018-10-17-161243-01

`iosOverflowSafeArea="false"` needs to be set explicitly on generated elements within a `ScrollView`, even though its default value is `false`. Which causes layout bugs if not set, even simple dividers `<StackLayout class='hr-light'></StackLayout>` would look like below.

![44530577_1029474757224854_1767420334119583744_n](https://user-images.githubusercontent.com/8045318/47285344-d8bb0980-d5ea-11e8-868e-7d3d2a98785c.jpg)

**Comment by tsonevn** [comment]
Hi @cerireyhan,
Can you provide a sample project, which can be used for recreating the problem?

**Comment by cerireyhan** [comment]
@tsonevn Here is a sample project.
[NSPlayground.zip](https://github.com/NativeScript/NativeScript/files/2506188/NSPlayground.zip)

**Comment by tsonevn** [comment]
Hi @cerireyhan,
 I researched further the issue and found that the problem seems to be caused by `vertical-align: center;`, which is defined in `home-panel` CSS class. Can you try removing the alignment from the CSS?

**Comment by cerireyhan** [comment]
Hi @tsonevn ,
Removing vertical-align fixed another layout issue but the original issue remains. As you can see below.
This happens when you add layouts with ngFor or hide/show them with ngIf (binding event to a button to hide them as user). And this can only be fixed with adding iosOverflowSafeArea="false". So, the real issue is that default value of iosOverflowSafeArea is not false for generated elements in ScrollView.

![img_1835](https://user-images.githubusercontent.com/8045318/47556110-d835b200-d90d-11e8-9774-5f4de757d1c1.jpg)

**Comment by cerireyhan** [comment]
You need to scroll down in real iOS device to observe this behavior, it happens on layouts rendered outside screen. Its not reproducible on simulator.

**Comment by sivsushruth** [comment]
Same issue here. This is very critical as it is blocking the upgrade process.
Nothing inside listview is generated fine once scrolling starts
