### ISSUE TITLE
Image widget src local not working just remote paths

### ISSUE THREAD

**Issue by felixlberg** [NativeScript/NativeScript#6442]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

✔ Component nativescript has 4.2.4 version and is up to date.
✔ Component tns-core-modules has 4.2.1 version and is up to date.
✔ Component tns-android has 4.2.0 version and is up to date.
✔ Component tns-ios has 4.2.0 version and is up to date.

**Describe the bug**

The src property for image are **not** working as described in: https://docs.nativescript.org/angular/ui/ng-ui-widgets/image

I have an image widget `src/app/home/home.component.ts`  100% like described in your documentation: `<Image src="~/images/concept.png" stretch="none" class="img-rounded p-l-15 p-r-15 p-t-15"></Image>`

which gives me the following error:

`java.io.FileNotFoundException: /data/data/org.nativescript.conceptapp/files/app/images/concept.png (No such file or directory)`

this is my image path: `src/app/images/concept.png`

If this istn a bug i would be really glad if you could give some little more information about this
"Load image from app/images folder" mechanic.

**Comment by felixlberg** [comment]
I was able to fix it by myself with correcting **wrong** path in documentation:

https://docs.nativescript.org/angular/ui/ng-ui-widgets/image

You say here: tilde loads image from app/images folder this is **not** correct if you start an empty project with: 

`tns create HelloWorld --template tns-template-blank-ng`

Because in tsconfig.json you define ~ path as `src/*` which is not `src/app/*` like described in documentation. Its ether necessary to modify tsconfig.json or put images folder under src/images not src/app/images like suggested.

If you follow 100% the documentation you are running in this described error.

Best Regards
Felix

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/docs#1404
