### ISSUE TITLE
have a magento2 plugin?

### ISSUE THREAD

**Issue by benyang2015** [NativeScript/NativeScript#6444]
**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tsonevn** [comment]
Hi @benyang2015, 
It seems that there is no plugin, which provides a support for Magento2 in NativeScript. Regarding that, you can create a new one, which provides support for this API. Check out the article [here](https://docs.nativescript.org/plugins/building-plugins).

For further questions please, use [this StackOverflow thread](https://stackoverflow.com/questions/tagged/nativescript). This repository is used only for feature request and bug reporting related to `tns-core-modules`.
