### ISSUE TITLE
Let RadListView args.data.x/y discriminate between real swipe and animated swipe

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#6447]
Swipe in RadListView animates moving the listitem from a set threshold to  the set swipeLimits.left/right.
Both the real user movement and the animated movement which follows are shown in args.data.x/y.
It would be useful if it could be known if the change in args.data.x/y is caused by real user swipe, or by the animation. In that way it is possible to program that a user swipe (1) generates an action if some thresold is passed, or (2) that the this action is held and the swiped field keeps open to disclose the tappable fields, so that the user can tap. I did not find this in the documetation, hence I would like to propose this as a feauture request.

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#894
