### ISSUE TITLE
TextField does not show keyboard if swipeActions=true

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#6456]
I want the user o edit texst of a RadListView item. With swipeActions=false this works.
With swipeActions=true the field does not appear editable, and tapping the field does not show the keyboard to enter tekst. 

I tried changing swipeActions by {{-binding. This works to change swipeActions from false to true. However, when changing back from true to false the TextField keeps not-editable.

What is the right way to implement an editable item, which survives swipeActions=true?

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#900
