### ISSUE TITLE
ScrollView Android not rendering after resize

### ISSUE THREAD

**Issue by alexandrmiee** [NativeScript/NativeScript#6461]
**Environment**
√ Component nativescript has 4.2.4 version and is up to date.
√ Component tns-core-modules has 4.2.1 version and is up to date.
√ Component tns-android has 4.2.0 version and is up to date.
√ Component tns-ios has 4.2.0 version and is up to date.

I use Vue

**Describe the bug**
Create simple chat

```
<Page
 actionBarHidden="true"
> 
 <GridLayout columns="*" rows="1*,8*,1*">
  <StackLayout row="0" class="form"  background="#FAE379" >
   <Label class="lbl-menu" fontSize="20" marginBottom="1%" @tap="$navigateBack">
    <FormattedString>
     <Span fontSize="15">{{'fa-chevron-left' | fonticon}}</Span>
     <Span fontSize="20" class="txt-btn">     Test</Span>
    </FormattedString>
   </Label>
  </StackLayout>
  
  
  
  <ScrollView  row ="1" id="myScroller">
   <StackLayout >
    <StackLayout v-for="(m,i) in messages" :key="i" marginTop="30">
     <StackLayout class="card-chat-msg-o" v-if="m.u">
      <StackLayout>
       <Label class="card-chat-text-o"  textWrap="true" :text="m.txt"/>
      </StackLayout>
     </StackLayout>
     <StackLayout class="card-chat-msg-u" v-else>
      <StackLayout>
       <Label class="card-chat-text-u"  textWrap="true" :text="m.txt"/>
      </StackLayout>
     </StackLayout>
    </StackLayout>
   </StackLayout >
  </ScrollView  >
     
  <GridLayout row ="2" columns="1*,8*,1*" rows="*" borderColor="#F1F1F1" borderWidth="2%">
   <Label col="0" class="fa" fontSize="30">{{'fa-paperclip' | fonticon}}</Label>
   <TextView col="1" editable="true" v-model="message" hint="Enter message" autocorrect="true"/>
   <Label col="2" class="fa" fontSize="30" @tap="sendMessage()">{{'fa-play' | fonticon}}</Label>
  </GridLayout>
  
 </GridLayout>
</Page>
```
when I focus TextView , android show keyboard, ScrollView  sheeft up and all items of messages not showing
after that I push new items in messages 
ScrollView  rennder only new messages in correct positions other items of messages not showing

[video](https://yadi.sk/i/R7F7sELLYZAREw)

**Comment by tsonevn** [comment]
Hi @alexandrmiee,
This issue seems to be Vue related. I was unable to recreate the same problem in vanilla JavaScript NativeScript project. Regarding that, I would suggest opening a new issue in the [nativescript-vue](https://github.com/nativescript-vue/nativescript-vue/issues) repository.

Meanwhile, I would suggest to try using the ListView for showing the messages' text. Check out the article [here](https://nativescript-vue.org/en/docs/elements/components/list-view/).
