### ISSUE TITLE
MagTek Bluetooth eDynamo multiple activities

### ISSUE THREAD

**Issue by thiagorezserve** [NativeScript/NativeScript#6465]
I might be wrong not sure so please someone enlighten me if what I'm expecting is possible or not.

I have one SDK from MagTek, for uDynamo, eDynamo, iDynamo etc. with has a demo where I can built into my phone to test if everything is ok with my devices etc and serves as documentation to where I need to go https://www.magtek.com/support/edynamo?tab=software

While dealing with the audio jack feature I could do it with Nativescript without a sweat, it is done and works perfectly. My problem started when I had to do with Bluetooth connection.

First I thought it could be because I was using someone else library to get the devices ([nativescript-bluetooth](https://github.com/EddyVerbruggen/nativescript-bluetooth)) but well... that wasn't the case.

I did my own functionalities to connect to the device and could even send messages to the device etc, it does respond.

So then I decided to question to check if I was right or wrong. Does for any instance bluetooth use more than one activity? And if the JAR file from the SDK request a new activity, will it replace the main activity and run normally?

Because what I can see until now is im doing exactly as their demo to connect to the device:
 ```
let m_connectionType = MTConnectionType.BLEEMV;
m_scra.setConnectionType(m_connectionType); 
m_scra.setConnectionRetry(true);
m_scra.setAddress(b_device.getAddress());
m_scra.openDevice();
 ```

But my application just starts... says connecting as it should and stop right after that and I never hear from it again. It stop totally all possible threads or activities...

The logcat says this:
 ```
10-26 17:06:37.934 27664-27664/org.nativescript.application I/BluetoothDevice: createBond() for device 4A:0 called by pid: 27664 tid: 27664
10-26 17:06:37.958 27664-27664/org.nativescript.application I/MTSCRA: openDevice:ConnectionType:BLEEMV
10-26 17:06:37.964 27664-27664/org.nativescript.application I/h: Device Is Disconnected
10-26 17:06:37.964 27664-27664/org.nativescript.application I/MTBLEService: setDisconnectRequest=false
10-26 17:06:37.964 27664-27664/org.nativescript.application I/MTBaseService: setState:Current:Disconnected,New:Connecting
10-26 17:06:37.964 27664-27664/org.nativescript.application I/MTSCRA: OnConnectionState
10-26 17:06:37.975 27664-27718/org.nativescript.application D/OpenGLRenderer: eglDestroySurface = 0xe6114ae8
10-26 17:06:37.975 27664-27664/org.nativescript.application D/ViewRootImpl@c14fdd9[NativeScriptActivity]: dispatchDetachedFromWindow
10-26 17:06:37.975 27664-27664/org.nativescript.application D/InputEventReceiver: channel 'c841afd org.nativescript.application/com.tns.NativeScriptActivity (client)' ~ Disposing input event receiver.
    channel 'c841afd org.nativescript.application/com.tns.NativeScriptActivity (client)' ~NativeInputEventReceiver.
10-26 17:06:37.998 27664-27664/org.nativescript.application I/JS: '*** Callback 0'
10-26 17:06:37.999 27664-27664/org.nativescript.application I/JS: 'State' 'Connecting'
10-26 17:06:37.999 27664-27664/org.nativescript.application D/ViewRootImpl@1bfd230[NativeScriptActivity]: MSG_WINDOW_FOCUS_CHANGED 1
10-26 17:06:38.002 27664-27664/org.nativescript.application E/ViewRootImpl: sendUserActionEvent() returned.
 ```

While if I test with their app same part when they try to connect here is what I get:

 ```
10-26 17:08:27.438 28292-28292/com.magtek.mobile.android.mtscrademo I/MTSCRA: openDevice:ConnectionType:BLEEMV
10-26 17:08:27.449 28292-28292/com.magtek.mobile.android.mtscrademo I/h: Device Is Disconnected
10-26 17:08:27.449 28292-28292/com.magtek.mobile.android.mtscrademo I/MTBLEService: setDisconnectRequest=false
10-26 17:08:27.449 28292-28292/com.magtek.mobile.android.mtscrademo I/MTBaseService: setState:Current:Disconnected,New:Connecting
10-26 17:08:27.450 28292-28292/com.magtek.mobile.android.mtscrademo I/MTSCRA: OnConnectionState
10-26 17:08:27.450 28292-28292/com.magtek.mobile.android.mtscrademo I/MTBLEService: Connect to Gatt...
10-26 17:08:27.455 28292-28292/com.magtek.mobile.android.mtscrademo D/BluetoothGatt: connect() - device: 34:03:DE:4A:06:08, auto: false
10-26 17:08:27.455 28292-28292/com.magtek.mobile.android.mtscrademo D/BluetoothAdapter: isSecureModeEnabled
10-26 17:08:27.456 28292-28292/com.magtek.mobile.android.mtscrademo D/BluetoothGatt: registerApp()
10-26 17:08:27.457 28292-28292/com.magtek.mobile.android.mtscrademo D/BluetoothGatt: registerApp() - UUID=4b6d339a-b228-426e-88e1-0113d660e6f1
10-26 17:08:27.463 28292-28900/com.magtek.mobile.android.mtscrademo D/BluetoothGatt: onClientRegistered() - status=0 clientIf=7
10-26 17:08:27.465 28292-28292/com.magtek.mobile.android.mtscrademo I/MagTekDemo: *** Callback 0
    *** Event MTSCRAEvent.OnDeviceConnectionStateChangedConnecting
10-26 17:08:27.691 28292-28900/com.magtek.mobile.android.mtscrademo D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=7 device=34:03:DE:4A:06:08
10-26 17:08:27.694 28292-28900/com.magtek.mobile.android.mtscrademo I/MTBLEService: BluetoothGattCallback::onConnectionStateChange:BluetoothProfile.STATE_CONNECTED
10-26 17:08:27.697 28292-28900/com.magtek.mobile.android.mtscrademo I/MTBLEService: GattCallback Bond State = 12
10-26 17:08:27.697 28292-28900/com.magtek.mobile.android.mtscrademo I/MTBaseService: setState:Current:Connecting,New:Connecting
10-26 17:08:27.898 28292-28292/com.magtek.mobile.android.mtscrademo I/MTBLEService: PendingCommandHandler
    Start Service Discovery...
 ```

And then it proceed to search for my device etc... to search my activities.

Than since my application goes numb... versus this one that actually continues and does something.
What am I doing wrong?

I really would appreciate some help on this one... very lost here.
Since my plugin is open source. If needed I can publish with the bluetooth version broken so you guys can view my code and tell me what im doing wrong.

**Comment by tsonevn** [comment]
Hi @thiagorezserve,
Thank you for contacting NativeScript team.
I would suggest reviewing the article [here](https://docs.nativescript.org/core-concepts/android-runtime/advanced-topics/extend-application-activity), where it is described how you can extend the existing activity and to implement the needed functionality. You can also check how the functionality for Bluetooth connection and scanning for a device is implemented in the [nativescript-bluetooth](https://github.com/EddyVerbruggen/nativescript-bluetooth/tree/master/src/android) plugin for Android. 
It is hard to provide any further info about what can cause the problem on your side, without having a sample project, which can be debugged locally.
 
Keep in mind that this repository is used mainly for bug reporting and feature request related to the `tns-core-modules`. Regarding that, I would suggest opening a new thread in [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript)(while providing a sample project or access to the plugin's repository), where you can find help from the other community members.
