### ISSUE TITLE
Frame content disappear on pause, reload on resume

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/NativeScript#6468]
**Describe the bug**
Kind of related to https://github.com/NativeScript/NativeScript/issues/6188
Happening with 4.1.2 and 5.0.0 (next)

**To Reproduce**
https://play.nativescript.org/?template=play-tsc&id=VNkHaw&v=4
Scroll a bit,
Open recent apps,
Resume,
The scroll goes back to 0
**Expected behavior**
It should not move

**Sample project**
https://play.nativescript.org/?template=play-tsc&id=VNkHaw&v=4

**Additional context**

First i discovered that bug with nativescript Mapbox and nativescript Cart (Carto Mobile SDK).
When using fragments, and pausing (recent apps) while seeing the map, you see the app activity getting black. It redraws while resuming the app.

Can't post a playground sample with mabpox though as it is native.

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#902

**Comment by farfromrefug** [comment]
@tsonevn you are wrong please see my comment on your new issue

**Comment by farfromrefug** [comment]
@tsonevn here is a very simple example project showing the issue with Mapbox. i know it is not a ```tns-core-modules``` But you need to have an OpenGL view to easily see the fragment issue.

That project as it is will show the issue:
* run the app on android
* open "recent apps"
* the app fragment goes black
* focus the app again
* the fragment is recreated

now in the demo project change the tns-core-modules version to ```4.2.0```
clean/run 
The bug is not there anymore.

I can reproduce that issue with all OpenGL plugins with an app using Frame thus fragments.
I think Mapbox users did not report that issue yet because it is a regression from ```4.2.0```
Could you please reopen this issue?

Thanks
[demo.zip](https://github.com/NativeScript/NativeScript/files/2528596/demo.zip)

**Comment by tsonevn** [comment]
HI @farfromrefug,
Thank you for the demo app with the Mapbox. We will review it and will comment on the issue.

**Comment by farfromrefug** [comment]
@tsonevn could you reopen that issue? Thanks

**Comment by farfromrefug** [comment]
@tsonevn @manoldonev i will continue the discussion here as we agreed this is not telerik related.
Now to follow on @manoldonev last comments here is a sample project using mapbox and showing the issue.

First i all cases we wont change the ```tns-android``` version. That way we are sure it comes from ```tns-core-modules```

We will switch 2 things in different cases : 
* ```tns-core-modules``` versions between 4.1.0 and 5.0.2
* application start between ```application.start``` and ```application.run```

for the application start, simply comment/uncomment in the ```app.ts```

WARNING: you might end up with crashes (i am) but looking at logcat this comes from Mapbox:
```
9 09:51:59.494 21706 21791 I chatty  : uid=10452(u0_a452) org.nativescript.mapbox identical 1 line
11-09 09:51:59.496 21706 21791 F libc    : /usr/local/google/buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating" failed
11-09 09:55:29.479 22411 22491 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 22491 (GLThread 833), pid 22411 (vescript.mapbox)
11-09 09:55:29.573 22495 22495 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
11-09 09:55:29.574  2779  2779 I /system/bin/tombstoned: received crash request for pid 22411
11-09 09:55:29.575 22495 22495 I crash_dump32: performing dump of process 22411 (target tid = 22491)
11-09 09:55:29.575 22495 22495 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-09 09:55:29.576 22495 22495 F DEBUG   : LineageOS Version: '15.1-20180826-UNOFFICIAL-a3y17lte'
11-09 09:55:29.576 22495 22495 F DEBUG   : Build fingerprint: 'samsung/a3y17ltexx/a3y17lte:7.0/NRD90M/A320FXXU3CRD4:user/release-keys'
11-09 09:55:29.576 22495 22495 F DEBUG   : Revision: '0'
11-09 09:55:29.576 22495 22495 F DEBUG   : ABI: 'arm'
11-09 09:55:29.576 22495 22495 F DEBUG   : pid: 22411, tid: 22491, name: GLThread 833  >>> org.nativescript.mapbox <<<
11-09 09:55:29.576 22495 22495 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
11-09 09:55:29.576 22495 22495 F DEBUG   : Cause: null pointer dereference
11-09 09:55:29.576 22495 22495 F DEBUG   :     r0 e3f6f3c0  r1 000035c2  r2 00000000  r3 40000000
11-09 09:55:29.576 22495 22495 F DEBUG   :     r4 dbf31100  r5 dbf16b18  r6 00000000  r7 c3779930
11-09 09:55:29.576 22495 22495 F DEBUG   :     r8 00000000  r9 e3f6fba0  sl c3779b00  fp c3779a8c
11-09 09:55:29.576 22495 22495 F DEBUG   :     ip e5392d58  sp c3779928  lr c2baf1f5  pc 00000000  cpsr a0000010
11-09 09:55:29.578 22495 22495 F DEBUG   :
11-09 09:55:29.578 22495 22495 F DEBUG   : backtrace:
11-09 09:55:29.578 22495 22495 F DEBUG   :     #00 pc 00000000  <unknown>
11-09 09:55:29.578 22495 22495 F DEBUG   :     #01 pc 000261f3  /data/app/org.nativescript.mapbox-0vaEF3BWe5KJjYvD6ODqSQ==/lib/arm/libmapbox-gl.so
11-09 09:55:29.578 22495 22495 F DEBUG   :     #02 pc 0002621d  /data/app/org.nativescript.mapbox-0vaEF3BWe5KJjYvD6ODqSQ==/lib/arm/libmapbox-gl.so
11-09 09:55:29.578 22495 22495 F DEBUG   :     #03 pc 000dd3d3  /data/app/org.nativescript.mapbox-0vaEF3BWe5KJjYvD6ODqSQ==/lib/arm/libmapbox-gl.so
11-09 09:55:29.578 22495 22495 F DEBUG   :     #04 pc 00076c01  /data/app/org.nativescript.mapbox-0vaEF3BWe5KJjYvD6ODqSQ==/lib/arm/libmapbox-gl.so
11-09 09:55:29.578 22495 22495 F DEBUG   :     #05 pc 00076c2d  /data/app/org.nativescript.mapbox-0vaEF3BWe5KJjYvD6ODqSQ==/lib/arm/libmapbox-gl.so
11-09 09:55:29.578 22495 22495 F DEBUG   :     #06 pc 00074571  /data/app/org.nativescript.mapbox-0vaEF3BWe5KJjYvD6ODqSQ==/lib/arm/libmapbox-gl.so
11-09 09:55:29.578 22495 22495 F DEBUG   :     #07 pc 0005e7d7  /data/app/org.nativescript.mapbox-0vaEF3BWe5KJjYvD6ODqSQ==/lib/arm/libmapbox-gl.so
11-09 09:55:29.578 22495 22495 F DEBUG   :     #08 pc 00022b0b  /data/app/org.nativescript.mapbox-0vaEF3BWe5KJjYvD6ODqSQ==/oat/arm/base.odex (offset 0x1b000)
```

As it is the project is using ```tns-core-modules``` 4.1.0:
* ```application.start``` : works perfecty! Nothing happening while pause/resume (recent apps or home)
* ```application.run``` : the map is reloaded upon pause/resume. However this is not actual issue. No black screen on pause/resume. You can actually see that behavior on the official Mapbox demo app.

Now change ```tns-core-modules``` to 5.0.2. Delete platforms !
* ```application.start``` : black screen on pause resume.
* ```application.run``` : black screen on pause resume.


[fragment_issue.zip](https://github.com/NativeScript/NativeScript/files/2565101/fragment_issue.zip)
