### ISSUE TITLE
Data binding does not work with Android progress bar

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#647]
When I bind data to `Progress` it will not show any progress on Android.

![screen shot 2015-09-01 at 11 40 35 am](https://cloud.githubusercontent.com/assets/5018471/9593068/4e818fd4-509e-11e5-9f46-58f4f8266388.png)

However, it works fine on iOS, and it works fine if I hard-code the data for Android as well.

In the below example, the Label text is showing the bindings on Android, but not the progress bar.
```xml
<Progress cssClass="progress-bar" value="{{ current_page }}" maxValue="{{ total_pages }}"/>
<Label text="{{ current_page + '/' + total_pages }}"/>
```

**Comment by nsndeck** [comment]
I've checked it out and everything works fine on my end. The only difference is `cssClass="progress-bar"`. Could you please remove it and let me know how it goes?

**Comment by lscown** [comment]
Hey! Yeah, so I tried removing the selector in the .css file, and that didn’t work. I then removed cssClass=“progress-bar” and that fixed it, thanks!
