### ISSUE TITLE
.notify not working

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#6470]
In [`playground`](https://play.nativescript.org/?template=play-tsc&id=tEnXFt&v=15) I used the following code to automatically run the tap function defined on tapObject.   
```
export function onNotify(args: EventData) {
    let page = <View>args.object
    let parent = page.parent
   let tapObject = parent.getViewById("toNotify")
   tapObject.notify({ eventName: "tap", object: tapObject }
}
```

I tested with Android. tapObject does contain the right object, as shown in console.log:
object to notify=Label@file:///app/home/home-page.xml:15:6; 

What is wrong ?

**Comment by tsonevn** [comment]
Hi @jokro,
Following the [documentation](https://docs.nativescript.org/core-concepts/events#creating-a-custom-event), the `.notify` can be used to raise a **custom** event on a particular action or to emit **propertyChange** manually. Emitting a `tap` event on a specific UI component using `notify` is not supported.
If you need to show the alert, you can call `onNotified`manually. For example:
```
export function onNotify(args: EventData) {
    console.log("onNotify...")
    let page = <View>args.object
    let parent = page.parent
    let tapObject = parent.getViewById("toNotify")
    console.log("object to notify=" + tapObject)
    console.log("expected: Alert window showing...")
    onNotified(undefined);
    
}
```

Let me know if I am missing something or if your case is different.

**Comment by jokro** [comment]
Hi @tsonevn ,
Of course this is possible. However, the reason for me to investigate  .notify is that I would like to make a program which animates user behaviour,  to visually show the user what he should do using a particular program. Being able to trigger gestures is a prerequisite as I did not program the app the instruction is about.

**Comment by tsonevn** [comment]
HI @jokro,
In this scenario, I would suggest using the [nativescript-coachmarks](https://market.nativescript.org/plugins/nativescript-coachmarks). The plugin allows you to display coach marks and to guide the user on the first start of the app.

**Comment by mudlabs** [comment]
@jokro @tsonevn 

I just released  [NativeScript Eventify](https://github.com/mudlabs/nativescript-eventify). You can use it to raise `UI` gesture events from code like so, `view.eventify({ eventName: "tap" object: view });`.

It's just `tap` event for now, but will try add others later.

**Comment by jokro** [comment]
Thx very muchOp 27 mrt. 2019 09:38 schreef Sam <notifications@github.com>:@jokro @tsonevn
I just released  NativeScript Eventify. You can use it to raise UI gesture events from code like so, view.eventify({ eventName: "tap" object: view });.
It's just tap event for now, but will try add others later.
