### ISSUE TITLE
loadMoreItems event triggered on child tap event in ListView for the first time in IOS

### ISSUE THREAD

**Issue by saikumar-madana** [NativeScript/NativeScript#6478]
Hi Everyone,

In my application I have a listview and a `loadMoreItems` event attached to it. When I initially launch the application, I try to do a tap event on an item of listview. When I trigger a tap event on an item of listview for the first time, `loadMoreItems` event getting triggered. I am not sure what makes it happen. For second and later tap events, it is not happening. Only for the first time the `loadMoreItems` is getting triggered. This issue is not there in `android`.

I am unable to move forward because of this issue. Please help me solve this.

Thanks...

**Comment by tsonevn** [comment]
Hi @saikumar-madana,
I have checked described case with our sample project [here](https://github.com/NativeScript/nativescript-sdk-examples-js/tree/master/app/ns-ui-widgets-category/list-view/events), however, was unable to recreate the described problem. I have tested ListView's itemTap event and the tap event inside the template. Keep in mind that if the ListView does not has enough items to fulfil the screen, the ListView will execute `loadMoreItems` ones on initial time in iOS.

**Comment by saikumar-madana** [comment]
Hi @tsonevn ,

Actually I am refreshing the `listview` using `.refresh()` in the `tap` event inorder to show some changes in UI. May this be the reason?  On debugging I came to know that not only for the first time I am getting this issue, but also for rest of the `tap`s too.

Thanks...

**Comment by tsonevn** [comment]
Hi @saikumar-madana,
Indeed,  refreshing the ListView on tap most likely is triggering the `loadMoreItems` event. Can you provide more info, what kind of UI changes you are making in the ListView, that require to call the `refresh()` method? It will also help if you can give us a sample project, which shows your case and what you are trying to achieve a final result.

**Comment by saikumar-madana** [comment]
Hi @tsonevn ,

As shown below, we are toggling the shipment-timeline overlay.

Before show:
![image](https://user-images.githubusercontent.com/17292167/47793663-cb1d2680-dd44-11e8-9ed4-d021180e9040.png)

After show:
![image](https://user-images.githubusercontent.com/17292167/47793768-0586c380-dd45-11e8-936a-effb32bdfc5c.png)


We are using something like

```
args.object.bindingContext.selectedCardData.moreMenuOptionVisibility = true;
page.getViewById('radListViewRef').refresh();
```

Let me know do I need to provide more info...

**Comment by tsonevn** [comment]
Hi @saikumar-madana,
To solve your case, I would suggest setting up a flag, which can be set up to false when there is a tap event. Then you will be able to disable to functionality, which loads the new items.   For example:
XML
```
<ListView row="0" items="{{ listArray }}" itemTap="onItemTap" loadMoreItems="onLoadMoreItems" class="list-group">
            <ListView.itemTemplate>
                <!-- -->
            </ListView.itemTemplate>
        </ListView>  
```
TypeScript
```
let loadMore = true;

export function onItemTap(args: ItemEventData) {
    const index = args.index;
    loadMore = false;
   //........
}
export function onLoadMoreItems(args: ItemEventData) {
    if (loadMore) {
        console.log("ListView -> LoadMoreItemsEvent");
        setTimeout(() => {
           // load the new items
        }, 3000);
        loadMore = false;
        
    }
    if(loadMore === false){
        console.log("in the if")
        loadMore = true;
    }
}
```
