### ISSUE TITLE
Android ActionBar icon and text left position does not align left

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#648]
Using the following:
```xml
<Page.actionBar>
  <ActionBar title="New transactions">
    <ActionBar.actionItems>
      <ActionItem  ios.position="left"  android.position="left" icon="res://ic_arrow_back" tap="navigateBack"/>
      <ActionItem  ios.position="right"  android.position="right" icon="res://ic_done" tap="nextItem"/>
    </ActionBar.actionItems>
  </ActionBar>
</Page.actionBar>
```

Will show up as (sorry about white on gray):
![screen shot 2015-09-01 at 1 15 22 pm](https://cloud.githubusercontent.com/assets/5018471/9594162/b96d5f32-50ab-11e5-9066-9e9a5efaad05.png)

Whereas it shows up correctly on iOS

**Comment by vakrilov** [comment]
Hi @lscown,
The position property supports different values for [iOS](http://docs.nativescript.org/ApiReference/ui/enums/IOSActionItemPosition/README) and [Android](http://docs.nativescript.org/ApiReference/ui/enums/AndroidActionItemPosition/README).
Basically for iOS the icons can be position to left or right and in Android you can specify if they are going to be in the actionbar(left aligned) or in the options menu.

**Comment by alexrainman** [comment]
What if i want to do this in Android?

ActionBar.SetDisplayHomeAsUpEnabled(true);
ActionBar.SetHomeButtonEnabled(true);

and use it to Toggle SideDrawer?
