### ISSUE TITLE
NativeScript - Back button not showing in iOS but works well for android

### ISSUE THREAD

**Issue by princy05** [NativeScript/NativeScript#6482]
I am trying to develop an app for both android and ios. I am using NavigationButton ui component in my code to return to home tab. The back button is shown for Android but it is not showing for the iOS app. 

Please see my attached code:
html code:
        <ActionBar class="action-bar" title="Create Show" horizontalAlignment="center">
                <NavigationButton text="SignIn" android.systemIcon="ic_menu_back" tap="goBack()" [nsRouterLink]="['../../home']" ></NavigationButton>
            </ActionBar>

    <ScrollView height="87%"  orientation="vertical" >
            <StackLayout class="form" >
                    <StackLayout>
                            <Button class="customButton" text="upload picture"></Button>
                    </StackLayout>
            </StackLayout>
        </ScrollView>

typescript coe: 
import { Component, OnInit } from "@angular/core";
    import { RouterExtensions } from "nativescript-angular/router";
    import { device, isAndroid, isIOS, screen } from "tns-core-modules/platform";
    import { ScrollView } from "tns-core-modules/ui/scroll-view";

    import { NativeScriptFormsModule } from "nativescript-angular/forms";
    import * as ModalPicker from "nativescript-modal-datetimepicker";

    @Component({
        selector: "Browse",
        moduleId: module.id,
        templateUrl: "./browse.component.html",
        styleUrls: ["./browse.component.css"]
    })
    export class BrowseComponent implements OnInit {
        constructor(private routerExtensions: RouterExtensions) {
            // Use the component constructor to inject providers.
            console.log("inside constructor");
        }

        ngOnInit(): void {
            // Use the "ngOnInit" handler to initialize data for the view.
        }
        goBack() {
            alert("alert");
            this.routerExtensions.backToPreviousPage();
        }
    }

**Comment by princy05** [comment]
<img width="400" alt="screen shot 2018-10-31 at 6 48 34 pm" src="https://user-images.githubusercontent.com/16576656/47826449-a40f2680-dd3d-11e8-8b35-fc0cf3ddee33.png">

**Comment by tsonevn** [comment]
Hi @princy05,
I have checked your case on our side, however, was unable to recreate an issue with the `NavigationButton` component. For your convenience, I am attaching a sample project. You can review it and make the needed changes, which will allow us to recreate the problem on our side.

Keep in mind that on iOS the NavigationButton will be shown after you made navigation in the app. If you have set up the component to the main page, nothing will be displayed.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2537825/Archive.zip)

**Comment by princy05** [comment]
Thank you.

**Comment by onurhanaytac** [comment]
Is there anyway to force ios to show back button?

**Comment by onurhanaytac** [comment]
Thank you @tsonevn ! I used <ActionItem> for ios. I guess we cannot force it to show up.
