### ISSUE TITLE
Listview orientation horizontal

### ISSUE THREAD

**Issue by rahultyagiji** [NativeScript/NativeScript#6486]
Hi, 

I am looking to create a ListView element which is required to be orientated horizontally and not vertically. Is it something that nativescript ListView still doesn't support out of the box?

Any help would be great. 

Cheers

Rahul

**Comment by tsonevn** [comment]
Hi @rahultyagiji,
The ListView provided by `tns-core-modules` does not provide similar functionality for changing the orientation. I would suggest using the RadListView component from `nativescript-ui-listview`, where you can specify the `scrollDirection`. Check out this [article](https://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/item-layouts#using-listviewlinearlayout).
