### ISSUE TITLE
List View fails rendering rows on iOS

### ISSUE THREAD

**Issue by sivsushruth** [NativeScript/NativeScript#6493]
**Environment**

 - CLI: 5.0.0-2018-10-03-12377
 - Cross-platform modules: 5.2.0-2018-10-30-142506-02
 - iOS Runtime: 4.2.0

**Describe the bug**
If the list view has rows with dynamic heights, it fails to render certain rows when the new height of the recycled cell is different from previous height. 
Weird thing is, when you tap on the cell, it does show the content that was supposed to be there. 
<img width="317" alt="screen shot 2018-11-02 at 3 03 28 pm" src="https://user-images.githubusercontent.com/5187494/47912910-2d4e6680-dec0-11e8-965a-03a30c99ed04.png">

<img width="329" alt="screen shot 2018-11-02 at 4 51 06 pm" src="https://user-images.githubusercontent.com/5187494/47912864-042dd600-dec0-11e8-9ce4-d154ba6798a7.png">

**Expected behavior**
As in previous versions, it used to work perfect. Currently upgrading my app from 3.4.0 to latest version and faced this issue.

Works perfect even with upgrade on Android

**Comment by tsonevn** [comment]
Hi @sivsushruth,
Please provide a sample project, which demonstrates the problem and can be used for debugging.

**Comment by abhayastudios** [comment]
I have the same issue. You can see the behaviour in this [test project](https://github.com/abhayastudios/ns5-listview).

Steps:
1. select an item from the listview
2. tap on the go back button
3. scroll around --> you will see that the height of the listview items has changed and sometimes all items will disappear

**Comment by james-criscuolo** [comment]
Anybody have a workaround for this? We've just seen the same issue, it's all that is preventing us from upgrading. Should we maybe move the issue to ios-runtime?

**Comment by james-criscuolo** [comment]
Looks like tns-core-modules@next fixes this, so next release will resolve this.

**Comment by abhayastudios** [comment]
@tsonevn please re-open, still happens with NS 5.1.

**Comment by tsonevn** [comment]
Hi @abhayastudios,
 I tested the project that you have attached in comment https://github.com/NativeScript/NativeScript/issues/6493#issuecomment-435615269 with NS 5.1, however, was unable to recreate the issue. For your convenience, I am attaching the project with updated dependencies.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2697990/Archive.zip)
