### ISSUE TITLE
Angular Custom Modal

### ISSUE THREAD

**Issue by xjpmauricio** [NativeScript/NativeScript#6496]
If using a page with an ActionBar, the overlay area starts bellow the action bar and does not fill the entire page. Is there a way to solve this?

Template: https://play.nativescript.org/?template=play-ng&id=BDujuH&v=3

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-angular #1587](https://github.com/NativeScript/nativescript-angular/issues/1587) via [**ZenHub**](https://www.zenhub.com/)
