### ISSUE TITLE
Nav issue in docs

### ISSUE THREAD

**Issue by cfjedimaster** [NativeScript/NativeScript#6497]
**Describe the bug**
When looking at the Layout Containers docs (https://docs.nativescript.org/ui/layouts/layout-containers), I noticed a small but annoying bug. In the right hand nav, you will notice many of the links, like for "Stack Layout", go to https://docs.nativescript.org/ui/layouts/layout-containers. But the link beneath it, "Stack Layout properties", goes to https://docs.nativescript.org/ui/layouts/layout-containers#stacklayout-properties. 

It's a minor thing, but as I've used this page a bit over the past few days, I keep clicking and wondering why the page reloads and doesn't go to the right place.

**To Reproduce**
Click the "bold" link to go to a topic.

**Expected behavior**
To go to the topic. ;)

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/docs #1419](https://github.com/NativeScript/docs/issues/1419) via [**ZenHub**](https://www.zenhub.com/)
