### ISSUE TITLE
Nav UI issue in docs

### ISSUE THREAD

**Issue by cfjedimaster** [NativeScript/NativeScript#6499]
I selected one of the sub nav items on the Layout page (https://docs.nativescript.org/ui/layouts/layout-containers#docklayout-properties) and ended up with this:

![image](https://user-images.githubusercontent.com/393660/47937823-00925300-deb0-11e8-8e8d-78d9a1c3adc0.png)

As I scroll, all the green highlights will turn off, and then show up again.

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/docs #1418](https://github.com/NativeScript/docs/issues/1418) via [**ZenHub**](https://www.zenhub.com/)
