### ISSUE TITLE
Get contacts from device

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#65]
_From @edimoldovan on March 17, 2015 15:58_

Hi everyone,

Is there any way of reaching the iOS contacts?

Thanks,
Eduárd

_Copied from original issue: NativeScript/cross-platform-modules#195_

**Comment by enchev** [comment]
Hi Eduárd,

You can try this code:
http://stackoverflow.com/questions/19027118/fetch-contacts-in-ios-7

This API is available in NativeScript as well!

Thanks,
Vlad

**Comment by enchev** [comment]
_From @edimoldovan on March 18, 2015 7:55_

I will, thanks.
Also, I am curious if this would be a possible approach for some more special future features, like this one. Do you plan to leave handle it like this, or have a higher level platform independent version of the feature in Nativescript?

**Comment by enchev** [comment]
We will have for sure - the community will add it even if we don't have it! :) @tjvantoll already added flashlight module: https://github.com/tjvantoll/nativescript-flashlight

**Comment by enchev** [comment]
Combined with https://github.com/NativeScript/NativeScript/issues/250

**Comment by pavel-blagodov** [comment]
@enchev, what do you mean by "This API is available in NativeScript as well!". I could't find any related to AddressBook API in the documentation, could you point me out where I can find it?

**Comment by NathanaelA** [comment]
@pavel-blagodov What @enchev means is that the native iOS & Android apis are available to be called directly from NativeScript.   Not that their is a plugin for these features.

**Comment by pavel-blagodov** [comment]
Ok, how can I call ABAddressBookCreateWithOptions directly from NativeScript?

**Comment by enchev** [comment]
Here is the function signature:
```TypeScript
declare function ABAddressBookCreateWithOptions(options: NSDictionary, error: any): any;
```

You can check [this definition](https://raw.githubusercontent.com/NativeScript/NativeScript/master/ios.d.ts) file for more info.

**Comment by pavel-blagodov** [comment]
Thanks a lot, I got it. I can do the following:

```javascript
(function () {
  "use strict";

  exports.loaded = loaded;

  function loaded() {
    console.log(ABAddressBookCreateWithOptions)
  }
})();
```
