### ISSUE TITLE
bug in css with gierarchical components

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#6500]
Tested with android.

 [Example 1](https://play.nativescript.org/?template=play-tsc&id=o87l19&v=43)  shows a very odd behaviour. I have defined three classes representing the colors red green and blue. One class in home-page.css, another in custom-1.css and the third in custom-2.css. I defined two components on different hierarchical levels:

```
    <Label text="home/home-page.css defines class green" class="color-green" />
    <Label text="home/custom-1.css defines class red" class="color-red" />
    <Label text="home/custom-1/custom-2.css defines class blue" class="color-blue" />
```

The above three lines are defined in home-page.xml, component-1.xml and component-2.xml.
The followig points need to be resolved:
1. The three lines of code defined in home-page,xml are NOT showing. This is a bug ?.
2. home-page.css (green) is not being applied. This is a bug ?
3. component-1.css is not being applied to component=1.xml. This is a bug ?
4, component-2.css is also applied to compent-1.xml. I would expect it the other way, that the class defined in component-1 would apply in component-2.xml ?

In [example2](https://play.nativescript.org/?template=play-tsc&id=o87l19&v=44) I removed component-2.css. The result for both component-1 and component-2  is as follows: the first line shows green and the second red. This means that now home-page.css is applied on both component-1 (sibling) and component-2 (child). This is what I would have expected in the first example too. Component-1.css is applied in component-2.xml, This als feels ok. The problem that home-page.xml is not showing its thee lines also exists in example 2.

Please explain.

**Comment by jokro** [comment]
Point 1 of example 1 is solved by adding a StackLayout, see [example 3](https://play.nativescript.org/?template=play-tsc&id=o87l19&v=45). In conclusion, the bug seems to be that if css components are nested more than 1 level, the css mechanism fails. If component-2.css is removed as in example 2, css works normal, see [xample 4](https://play.nativescript.org/?template=play-tsc&id=o87l19&v=45).


One of the great things about components is nesting. It makes your code much more readable and you have less chances of errors in handling with long xml files. Nesting css is part of this. I hope it can be solved soon as I am in the middle of converting a long xml file in manageable modules.

**Comment by NickIliev** [comment]
@jokro, as you have observed providing a root layout, is resolving the 1st point. In NativeScript it is mandatory to have a single root layout in your pages.

However, the second issue seems legit and looks lies the one reported by you [here](https://github.com/NativeScript/NativeScript/issues/6501) so closing this one as a duplicate to [https://github.com/NativeScript/NativeScript/issues/6501](https://github.com/NativeScript/NativeScript/issues/6501)
