### ISSUE TITLE
RE: SideDrawer - android.content.res.Resources$NotFoundException: Resource ID #0xfffffff6

### ISSUE THREAD

**Issue by samliaw** [NativeScript/NativeScript#6503]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):
C:\tns\ema2>tns info
√ Getting NativeScript components versions information...
√ Component nativescript has 5.0.0 version and is up to date.
√ Component tns-core-modules has 5.0.1 version and is up to date.
√ Component tns-android has 5.0.0 version and is up to date.
√ Component tns-ios has 5.0.0 version and is up to date.

**Describe the bug**

I am building a new app using the following command. Here is the package.json
{
  "nativescript": {
    "id": "org.nativescript.ema2",
    "tns-android": {
      "version": "5.0.0"
    },
    "tns-ios": {
      "version": "5.0.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "lint": "tslint \"src/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.1.0",
    "nativescript-angular": "~6.2.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-sidedrawer": "~5.0.0",
    "tns-core-modules": "~5.0.0",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.2.0",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "@nativescript/schematics": "~0.3.0",
    "codelyzer": "~4.5.0",
    "nativescript-dev-sass": "~1.6.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.17.0",
    "tslint": "~5.11.0",
    "typescript": "~2.7.2",
    "@angular/compiler-cli": "~6.1.0",
    "@ngtools/webpack": "~6.2.0"
  },
  "readme": "NativeScript Application"
}

I run the following command
"tns create ema2--template tns-template-drawer-navigation-ng",
"cd ema2",
"tns run android --emulator"
and the following error is produced. 
Refreshing application on device emulator-5554...
Successfully synced application org.nativescript.ema2 on device emulator-5554.
ActivityManager: Start proc 14174:org.nativescript.ema2/u0a69 for activity org.nativescript.ema2/com.tns.NativeScriptActivity
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
System.err: android.content.res.Resources$NotFoundException: Resource ID #0xfffffff6
System.err:     at android.content.res.Resources.getValue(Resources.java:1351)
System.err:     at android.content.res.Resources.loadXmlResourceParser(Resources.java:2774)
System.err:     at android.content.res.Resources.getAnimation(Resources.java:1189)
System.err:     at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:75)
System.err:     at android.support.v4.app.FragmentManagerImpl.loadAnimation(FragmentManager.java:1102)
System.err:     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1600)
System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1641)
System.err:     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:794)
System.err:     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
System.err:     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2200)
System.err:     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2153)
System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2063)
System.err:     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:725)
System.err:     at android.os.Handler.handleCallback(Handler.java:739)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:148)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
ActivityManager: Process org.nativescript.ema2 (pid 14174) has died

**To Reproduce**

run following commands
"tns create ema2--template tns-template-drawer-navigation-ng",
"cd ema2",
"tns run android --emulator"

**Expected behavior**
I should be able to see the main screen without any compiling errors. 

**Sample project**

**Additional context**

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#914
