### ISSUE TITLE
Outputting to console using colours

### ISSUE THREAD

**Issue by Eonfuzz** [NativeScript/NativeScript#6506]
Hey Crew,

As it stands is there any way to output to the console using colours? There's a lot of visual mess going on when trying to do logging (working on iOS has a LOT of output) and colours could really, really help readability.

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-cli #4094](https://github.com/NativeScript/nativescript-cli/issues/4094) via [**ZenHub**](https://www.zenhub.com/)
