### ISSUE TITLE
#ask- need plugin rich text editor on nativescript.!!!!!!

### ISSUE THREAD

**Issue by budineverend** [NativeScript/NativeScript#6507]
hallo, i was try to use this is one "https://github.com/aukris/nativescript-rich-text-example/issues/new" but isn't working anymore, is there have any new plugin of rich text?????

**Comment by tsonevn** [comment]
HI @budineverend,
You can follow the feature request logged [here](https://github.com/telerik/nativescript-ui-feedback/issues/297). Also, I would suggest opening a [new issue ](https://github.com/aukris/nativescript-rich-text-example/issues/new) in the plugins repository and to contact the plugin's author for further help.

**Comment by budineverend** [comment]
> HI @budineverend,
> You can follow the feature request logged [here](https://github.com/telerik/nativescript-ui-feedback/issues/297). Also, I would suggest opening a [new issue ](https://github.com/aukris/nativescript-rich-text-example/issues/new) in the plugins repository and to contact the plugin's author for further help.

oc, thank you for attention..
cause i really need this plugin rich text editor.
