### ISSUE TITLE
Getting the same iOS device UUID

### ISSUE THREAD

**Issue by jannotabamo** [NativeScript/NativeScript#6508]
Is this [plugin (NS-ios-uuid)](https://www.npmjs.com/package/nativescript-ios-uuid) still active? because it helps me a lot in getting the same iOS device UUID even you uninstalled the app. And was also suggested by the  [api-reference docs for Device](https://docs.nativescript.org/api-reference/interfaces/_platform_.device).

but there's a problem i've encountered when using the latest version of nativescript-webpack (0.17.*) together with this plugin. Is there any workaround for this issue? I can't proceed because of this problem with webpack.

I'm using the latest version of NS (5.0), NS-angular (6.2), NS-webpack (0.17) 

<img width="1434" alt="screen shot 2018-11-05 at 4 10 34 pm" src="https://user-images.githubusercontent.com/8262418/47985675-629fc200-e115-11e8-9e9a-808cc9e10f53.png">

**Comment by tsonevn** [comment]
Hi @jannotabamo,
I haven't tested if the plugin is compatible with the latest the latest NativeScript version, however, I would suggest using the `platform` module to access the device UUID. For example:
```
import * as platformModule from "tns-core-modules/platform";
platformModule.device.uuid
```

**Comment by jannotabamo** [comment]
@tsonevn the problem in iOS was that the device uuid changes everytime you uninstall & install the app.

**Comment by tsonevn** [comment]
Hi @jannotabamo,
Changing the uuid while reinstalling the app seems to be the expected behaviour on iOS. Check out [this thread](https://stackoverflow.com/a/49707846/6133327) in StackOverflow. 
Regarding your case, What is the purpose of making the uuid consistent?
