### ISSUE TITLE
NativeScript 5.0 WebView Specific config don't work

### ISSUE THREAD

**Issue by erikandershed** [NativeScript/NativeScript#6509]
**Environment**
✔ Component nativescript has 5.0.0 version and is up to date.
✔ Component tns-core-modules has 5.0.1 version and is up to date.
✔ Component tns-ios has 5.0.0 version and is up to date.

**Describe the bug**
I can't add device specific config to a WebView. Here for example I am trying to remove the iOS bounces effect, scrollbar and add a transparent background. But I get error:

**Error**
`JavaScript error:
file:///app/home/home-page.js:34:20: JS ERROR TypeError: undefined is not an object (evaluating 'webView.ios.scrollView')
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating 'webView.ios.scrollView')`

**To Reproduce**
```
const HomeViewModel             = require("./home-view-model");
const webViewModule             = require("tns-core-modules/ui/web-view");

function onNavigatingTo(args) {

    var page = args.object;
        page.bindingContext = HomeViewModel;
    var webView = page.getViewById('webview');

    if (page.ios) {
        webView.ios.scrollView.bounces = false;
        webView.ios.scrollView.showsHorizontalScrollIndicator = false;
        webView.ios.scrollView.showsVerticalScrollIndicator = false;
        webView.ios.backgroundColor = UIColor.clearColor;
    }

    webView.src = "https://www.google.com/";

}

exports.onNavigatingTo = onNavigatingTo;
```

**Comment by tsonevn** [comment]
Hi @erikandershed,
This error appears because you are trying to access the WebView native instance when it is still not created.  To solve the issue try to set up the needed settings on WebView loaded event. For example:
XML
```
<WebView loaded="wbloaded" id="webview" src="" />
```
TypeScript
```
import {isIOS} from "tns-core-modules/platform";
import {WebView} from "tns-core-modules/ui/web-view";
export function wbloaded(args){

    console.log("webView loaded");
    var webView:WebView = <WebView>args.object;
    if(isIOS){
        console.log(webView);
        console.log(webView.ios);
        // ..........
    }
}
```
