### ISSUE TITLE
Android: isUserInteractionEnabled stopped controlling the ScrollView's behaviour 

### ISSUE THREAD

**Issue by manojdcoder** [NativeScript/NativeScript#6511]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.0
 - Cross-platform modules: 5.0.1
 - Android Runtime: 5.0.0
 - iOS Runtime: 5.0.0
 - Plugin(s): N/A

**Describe the bug**
Until v4.2.0, setting `isUserInteractionEnabled` to `false` not only prevented click events but also the scrolling incase of ScrollView. Since 5.0.0, it's not the case anymore with Android, user is allowed to scroll anyways. 

**To Reproduce**
https://stackoverflow.com/questions/53158670/nativescript-scrollview-bug-on-android-with-runtime-version-5-0-0

**Expected behavior**
Setting `isUserInteractionEnabled` to `false` should prevent scroll on Android.

**Sample project**
https://play.nativescript.org/?template=play-js&id=hKrNlK

**Additional context**
If anyone looking for a workaround, here it is - https://play.nativescript.org/?template=play-js&id=hKrNlK&v=10

**Comment by tsonevn** [comment]
Hi @manojdcoder,
Thank you for the provided sample projects. 
I tested the problem on my side and was able to recreate the issue. I will mark this as a bug.
