### ISSUE TITLE
Image src not correct in ListView when setting from component asynchronously

### ISSUE THREAD

**Issue by kspearrin** [NativeScript/NativeScript#6518]
**Environment**
 - CLI: 4.2
 - Cross-platform modules: 4.2
 - Android Runtime: 4.2
 - iOS Runtime: 4.2
 - Plugin(s): n/a

**Describe the bug**
I have a `ListView` that references a component (`app-icon`) that displays an `Image` based on input parameters.

    <ListView [items]="items" class="list-group">
        <ng-template let-item="item">
            <GridLayout class="list-group-item" rows="auto" columns="auto, *">
                <app-icon [item]="item"></app-icon>
                <StackLayout row="0" col="1" >
                    <Label [nsRouterLink]="['/item', item.id]" [text]="item.name" class="list-group-heading"></Label>
                    <Label [text]="item.role" class="list-group-text" color="gray"></Label>
                </StackLayout>
            </GridLayout>
        </ng-template>
    </ListView>

```
@Component({
    selector: 'app-icon',
    template: '<Image [src]="image" class="thumb img-rounded"></Image>',
})
export class IconComponent implements OnChanges {
    @Input() item: Item;
    image: string;

    ngOnChanges() {
        // This works fine...
        // this.image = 'https://icons.bitwarden.net/' + this.item.name + '/icon.png';

        // This doesn't...
        this.doSomething().then(() => {
            this.image = 'https://icons.bitwarden.net/' + this.item.name + '/icon.png';
        });
    }

    private doSomething() {
        // Do some stuff...
        return Promise.resolve();
    }
}
```

As you can see above, this component's `image` property (the URL for the icon) is set during `ngOnChanges`. This works fine if `ngOnChanges` run synchronously, however, if I do any asynchronous work (i.e. with a promise) and then set the `image` URL property, the icon images displayed in the `ListView` are not correct. Images will show, however, they are not the correct icon for the corresponding item. Scrolling around in the `ListView` causes the icons to change when viewed again, however, they are usually not the correct icon for that item. The same problem happens if trying to use `ngOnInit` as well.

I am assuming this has something to do with how the ListView's cells are being recycled.

I have only tested this on Android so far, but I imagine something similar will probably happen in iOS as well.

**To Reproduce**
Run the sample project below (created from a basic `tns create --ng` command). Observe the starting page's ListView. Scroll around and observe the wrong icons for each item.

**Expected behavior**
Show correct icons.

**Sample project**
https://github.com/kspearrin/ns-imagetest

Relative parts (things that were changed from the generated template):
- https://github.com/kspearrin/ns-imagetest/blob/master/src/app/item/item.service.ts
- https://github.com/kspearrin/ns-imagetest/blob/master/src/app/item/items.component.html#L26
- https://github.com/kspearrin/ns-imagetest/blob/master/src/app/item/icon.component.ts

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1592
