### ISSUE TITLE
Nativescript-ui-listview layout error

### ISSUE THREAD

**Issue by jannotabamo** [NativeScript/NativeScript#6519]
When I used the staggered layout there's a weird spaces created when I'm scrolling down. It is also reproducible using the [nativescript-ui-samples-angular](https://github.com/telerik/nativescript-ui-samples-angular). 

![image from ios](https://user-images.githubusercontent.com/8262418/48114747-2eeea480-e29b-11e8-8b91-e44133cfe4ea.jpg)

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#919
