### ISSUE TITLE
Styling components like native spinner for android created using Placeholder not possible (http://developer.android.com/guide/topics/ui/controls/spinner.html)

### ISSUE THREAD

**Issue by bathejasumeet** [NativeScript/NativeScript#652]
Applying styles to native components like spinners for android created using Placeholder tags , does not work by assigning attributes, or creating appropriate layout files in App resources and instantiating appropriate adapters as specified in ( http://www.broculos.net/2013/09/how-to-change-spinner-text-size-color.html#.VeVclfaqpBc )

**Comment by enchev** [comment]
Hi @bathejasumeet,

There is no support in our XML for native Android XML attributes, etc. Have you tried to create desired component programmatic?

**Comment by bathejasumeet** [comment]
Hi @enchev ,

Some components in android cannot be styled programatically ( http://stackoverflow.com/questions/11723881/android-set-view-style-programatically ), the styles need to be pre specified in xml . Though NativeScript has some support for xml, I could implement the spinner using xml, placing it in App_Resources/Android /layout folder and referencing it using Resource IDs programatically. There is a work-around, however it is a kludge.
