### ISSUE TITLE
UI render misplacement in nativescript@5.0.0

### ISSUE THREAD

**Issue by xlcs0110** [NativeScript/NativeScript#6524]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.0
 - Cross-platform modules:5.0.1
 - Android Runtime:5.0.0
 - iOS Runtime:5.0.0

**Describe the bug**

I was just upgrade platform(tns-ios and tns-android) from 4.2 to 5.0.0,and upgrade tns-core-modules from 4.2 to 5.0.0.Then the ui render misplacement

**Comment by xlcs0110** [comment]
4.2
![11541646845_ pic](https://user-images.githubusercontent.com/13692131/48175560-8e09f300-e347-11e8-8542-e4455dc838fd.jpg)

5.0.0
![11541646862_ pic](https://user-images.githubusercontent.com/13692131/48175585-9d893c00-e347-11e8-9032-4bbdf02c28fa.jpg)

**Comment by tsonevn** [comment]
Hi @xlcs0110,
The given information is not enough to investigate the problem further. Please, provide a sample project, which can be used for debugging. 

Meanwhile, you can try set up `iosOverflowSafeArea` property to `true` on each item, which you are loading in the ListView and check if the problem persists. For example:
```
<StackLayout iosOverflowSafeArea="true">
				<Label textWrap="true" text="Play with NativeScript!" class="h2 description-label"></Label>
				<StackLayout class="hr-light"></StackLayout>
			</StackLayout>
```

**Comment by xlcs0110** [comment]
thanks,I will try it later.And I'll give you more code if necessary
