### ISSUE TITLE
Move Chart Documentation to NativeScript website

### ISSUE THREAD

**Issue by razorsyntax** [NativeScript/NativeScript#6530]
**Is your feature request related to a problem? Please describe.**
It's disconcerting that looking up information on the Nativescript charts directs you to the [Telerik documentation website](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/Chart/overview).  The look and feel of the of this site makes it appear the charts are "less supported" than those found on the main Nativescript website.  Finally, there's no explanation as to why the Progress Nativescript UI has its own website.

**Describe the solution you'd like**
Solution 1) Move the Nativescript Charts documentation to the [Nativescript](https://docs.nativescript.org/) website directly like any other Nativescript related widget.

Solution 2) Modify the Progress Nativescript UI website styling to look identical to that of the Nativescript docs website.

**Additional context**
Here's a screenshot of the Progress Nativescript UI website where you find documentation for the charts:
<img width="1109" alt="screen shot 2018-11-08 at 2 04 56 pm" src="https://user-images.githubusercontent.com/10995063/48224450-60c93f00-e35f-11e8-908b-569464cf1737.png">

Here's a screenshot of the Nativescript Docs website where you find documentation for everything else:
<img width="846" alt="screen shot 2018-11-08 at 2 05 18 pm" src="https://user-images.githubusercontent.com/10995063/48224470-6d4d9780-e35f-11e8-8736-e0a5878be495.png">

These are vastly different and should not diverge in style.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/docs#1430
