### ISSUE TITLE
Add more Image positioning modes

### ISSUE THREAD

**Issue by Gamadril** [NativeScript/NativeScript#6533]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to center an unscaled  small image inside a bigger Image view using API.

**Describe the solution you'd like**
Add more valid options to the _stretch_ property of the Image: 'center', 'top', 'bottom', 'left', 'right', 'topleft', 'topright', 'bottomleft', 'bottomright' . Default mode should be 'center'. (Well, looking at the possible values, the _stretch_ property might be the wrong name for all the modes...)

**Describe alternatives you've considered**
Since I currently need that option only for iOS, my workaround is to set the mode directly on the UIImageView:
`image.on('loaded', (event) => {
    event.object.nativeView.contentMode = UIViewContentMode.Center;
})`

**Additional context**
For iOS all possible modes are listed here:
https://developer.apple.com/documentation/uikit/uiviewcontentmode
Not sure about android:
https://developer.android.com/reference/android/widget/ImageView.html#attr_android:scaleType
Modes that are not defined as constants like for iOS, should be possible using transformation matrix.

**Comment by Gamadril** [comment]
Thanks, that works. Also with dynamically generated views where I have to set _backgroundImage_ property instead of _src_. However this feels like a hack than a solution. If this is the official way to load images, I see no sense for the _src_ property of the image view. There is also a restriction: _tintColor_ property has no effect - so for me still a hack and not a full equivalent...

**Comment by NickIliev** [comment]
@Gamadril you can still use the layout system and the alignment properties to position your image.. For example `horizontalAligment` + `verticalAlignment` for a image inside a layout.

Keep in mind that the stretch propery is no a positioning property but a property that "says" how an image should scale on a given fixed size layout. Using the actual size that is smaller then the parents size will allow you to effectivly position your image top/left/bottom/up or center just by using the alignment propetrties.
