### ISSUE TITLE
Livesync and debug mode stops after JS error

### ISSUE THREAD

**Issue by AhmedAzzabi** [NativeScript/NativeScript#6537]
So I was testing with version 5.0, I noticed that if I have small js error like undefined or null reference exception the debug mode stops, emulator shuts down and looks livesync, which slows my workflow as everytime I have to relaunch emulator and debug also adb.exe process stay hanged their and I need to kill it from task manager in order to reboot properly otherwise debug active but emulator gebynotion does not show like running in background.

**Comment by tsonevn** [comment]
Hi @AhmedAzzabi,
I tested the described case, however, was unable to recreate the problem.  The project was successfully synced after fixing the error which was causing the problem. Regarding that can you provide some more info about your environment(CLI, tns-android, tns-core-modules, node, versions) as well as some steps to reproduce? Also, does this problem happen only on emulator?

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-cli #4121](https://github.com/NativeScript/nativescript-cli/issues/4121) via [**ZenHub**](https://www.zenhub.com/)
