### ISSUE TITLE
How can i achieve a  vertically align label text like the attached image specially using StackLayout

### ISSUE THREAD

**Issue by sayem2015** [NativeScript/NativeScript#6539]
![vertical-text](https://user-images.githubusercontent.com/16286893/48302103-1c39d100-e522-11e8-8dd2-ffa04044a250.png)

**Comment by tsonevn** [comment]
Hi @sayem2015,
Try to set up the `textAlignment` to to `center ` and to rotate the Label using `rotate` property.
For further questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript), this repository is used for bug reporting and feature requests.

**Comment by sayem2015** [comment]
![screenshot_1542031688](https://user-images.githubusercontent.com/16286893/48352828-09590500-e6b8-11e8-9db4-f05044a96157.jpg)
 textAlignment to center hevent worked much.

Please check this code: 
.rotate {
transform: rotate(-90deg);
font-size: 16px;
color: #FFFFFF; 
}
    <StackLayout backgroundColor="#3C414B" width="12%" height="100%" horizontalAlignment="center" verticalAlignment="center" (tap)="openDrawer('Right')">
   <StackLayout class="rotate" orientation="horizontal">
      <Label class="fa" style="margin-right: 10px" text="&#xf067;"></Label>
      <Label width="100%" class="" text="New Category" textwrap="false"></Label>
   </StackLayout>
 </StackLayout>

Output:
![screenshot_1542031688](https://user-images.githubusercontent.com/16286893/48352999-7c627b80-e6b8-11e8-8c41-2a18ff6e3340.jpg)

But the width text is no way going vertical ...please share your thought

**Comment by tsonevn** [comment]
Hi @sayem2015,
Try to setup `textWrap="true"` to the Label.
