### ISSUE TITLE
@types/jasmine not compatible with tns-template-blank-ng on NS5

### ISSUE THREAD

**Issue by RobertGardner** [NativeScript/NativeScript#6540]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.0
 - Cross-platform modules: 5.0.0
 - Android Runtime: 
 - iOS Runtime: emulator 10.3.1
 - Plugin(s): none

**Describe the bug**
`@types/jasmine` requires TypeScript 2.8.4 but `tns-template-blank-ng` installs 2.7.2.

Following the unit testing instructions at `https://docs.nativescript.org/angular/tooling/testing`, create a new Angular project using `tns create HelloWorld --template tns-template-blank-ng`. This creates a project with TypeScript 2.7.2. Set up testing as instructed with `tns test init` and select Jasmine.

Now execute `npm i @types/jasmine --save-dev` as instructed.

The project doesn't compile since `@types/jasmine` latest version requires TypeScript 2.8.

**To Reproduce**
```
tns create HelloWorld --template tns-template-blank-ng
cd HelloWorld
tns test init
// Select Jasmine
npm i @types/jasmine --save-dev
tns test ios --emulator
```
This produces a bunch of compile errors.

Change `package.json` to use TypeScript 2.8.4. The project now compiles.

**Comment by tsonevn** [comment]
Hi @RobertGardner,
Following the error mentioned above, `The project doesn't compile since @types/jasmine latest version requires TypeScript 2.8.`, I would suggest updating the typescript version in the project's `package.json` file. For example:
```
{
  "nativescript": {
    "id": "org.nativescript.testNg",
    "tns-android": {
      "version": "5.0.0"
    },
    "tns-ios": {
      "version": "5.0.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    .........
  },
  "devDependencies": {
    "@nativescript/schematics": "~0.3.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.17.0",
    "typescript": "~2.8.0",
    "@angular/compiler-cli": "~6.1.0",
    "@ngtools/webpack": "~6.2.0"
  },
  "readme": "NativeScript Application"
}
```
Then clear up the project, by deleting `platforms`, `node_modules`,  `hooks` folders and `packege-lock.json` file and check if you will have the same issue with the debug command. 

Also before rebuilding the project make sure that you have installed globally the typescript `2.8.0` -> `tsc --version`

**Comment by RobertGardner** [comment]
Yes, as I mentioned in the last line of the bug report, your procedure works. I was hoping that the resolution of the bug would be to fix the template.

There are actually several problems with using `tns create HW --template tns-template-blank-ng` followed by `tns test init`. I've reported several bugs. It would have been nice if NativeScript had more thoroughly vetted the unit testing process before releasing.

**Comment by tsonevn** [comment]
Hi @RobertGardner,
Currently, we are updating the typescript version in the templates. We will soon publish the new templates.
