### ISSUE TITLE
NS5 + Angular unit testing doesn't work

### ISSUE THREAD

**Issue by RobertGardner** [NativeScript/NativeScript#6541]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.0
 - Cross-platform modules: 5.0.2
 - Android Runtime:
 - iOS Runtime: emulator 10.3.1
 - Plugin(s): none

**Describe the bug**
Creating a new Angular project using the `tns-template-blank-ng` template, then following the instructions at `https://docs.nativescript.org/angular/tooling/testing` fails to run the tests.

I can't figure out how to get tests to run successfully.

The last few lines of the log show:

```
CONSOLE ERROR DEPRECATION: Setting specFilter directly on Env is deprecated, please use the specFilter option in `configure`
CONSOLE LOG file:///app/tns_modules/nativescript-unit-test-runner/main-view-model.js:212:24: NSUTR: beginning test run
NativeScript / 10.3.1 (10.3.1; iPhone): Executed 0 of 0 SUCCESS (0 secs / 0 secs)
CONSOLE LOG file:///app/tns_modules/nativescript-unit-test-runner/main-view-model.js:254:20: NSUTR:NativeScript / 10.3.1 (10.3.1; iPhone): Executed 0 of 0 ERROR (0.008 secs / 0 secs)
```

which indicates that the tests never executed.

I tried renaming `example.js` to `example.spec.js`, I tried moving the generated `tests` folder from `src` to `src/apps`, I tried changing the `files` property in `karma.conf.js` to `src/**/*.js`. They all generate similar errors.

**To Reproduce**
```
tns create HelloWorld --template tns-template-blank-ng
cd HelloWorld
tns doctor // reports everything is OK
tns run ios --emulator // app runs successfully
tns test init // select Jasmine
tns test ios --emulator
```

This produces the above error.

**Comment by RobertGardner** [comment]
Interesting. That one never occurred to me since the glob rules should have picked up the test files. But for whatever reason, it works! Thank you! I wasted so much time on this!!!

I suggest that `tns test init` should be fixed to use that (or a similar) pattern. (I am now using `src/tests/**/*.spec.js`.)

**Comment by Fatme** [comment]
@RobertGardner,

I'm really happy your problem is resolved!

This glob rule `src/**/*.js` picks up the the test files but it picks up additional files that are not test files(the files from app folder for example). I assume some of these additional files breaks the karma runner for some reason.

Actually we're working on improving and fixing the issue. You can track the progress here https://github.com/NativeScript/nativescript-cli/issues/4071.

I'm closing this as a duplicate to https://github.com/NativeScript/nativescript-cli/issues/4071.
