### ISSUE TITLE
After update HMR not working on Angular - Error: "Module not found"

### ISSUE THREAD

**Issue by andresg747** [NativeScript/NativeScript#6544]
**Environment**
 - CLI: 5.0.0
 - Cross-platform modules: 5.0.2
 - Android Runtime: 5.0.0
 - iOS Runtime: 5.0.0
 - Plugin(s): 
    "nativescript-localstorage": "^1.1.5",
    "nativescript-pulltorefresh": "^2.1.1",
    "nativescript-snackbar": "^3.1.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-chart": "^3.6.1",
    "nativescript-ui-listview": "^3.5.11",
    "nativescript-ui-sidedrawer": "~4.1.0",

**Describe the bug**
When running `tns run [android | ios] --hmr` I get the following errors: [Full Log](https://pastebin.com/raw/shFvvQ1J).
The app (obviously), crashes on the device. 
When running the same command without the HMR flag, the app runs perfectly. 

**To Reproduce**
`tns run [android | ios] --hmr`

**Expected behavior**
Working Hot Module Replacement

I've added the [script](https://github.com/NativeScript/nativescript-angular/wiki/HMR#enable-hmr-in-nativescript-angular-project) on main.ts and have "nativescript-dev-webpack": "0.17.0" installed.

Any help would be very appreciated. Thanks in advance.

**Comment by Fatme** [comment]
@andresg747,

Maybe your `webpack.config,js` or your webpack's dependencies are not updated. Try to execute the following:
```
./node_modules/.bin/update-ns-webpack --deps
./node_modules/.bin/update-ns-webpack --configs
```

**Comment by Fatme** [comment]
@andresg747,

It seems it is still not updated correctly.

1. `rm -rf node_modules`
2. `rm -rf hooks`
3. `rm -rf platforms`
4. `rm -rf webpack.config.js`
5. Ensure `nativescript-dev-webpack: 0.17.0` is written in package.json
6. Ensure `nativescipt-angular: 6.2.0` is written in your package.json
7. Ensure the following code snippet https://github.com/NativeScript/nativescript-angular/wiki/HMR#enable-hmr-in-nativescript-angular-project is added
8. `npm i`
9. `tns run ios | android --hmr`

NOTE: `--hmr` mode does not work for projects containing lazy loading - https://github.com/NativeScript/nativescript-angular/issues/1564.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1603
