### ISSUE TITLE
How to disable Select & paste option in Textview?

### ISSUE THREAD

**Issue by priyakathiresan1** [NativeScript/NativeScript#6547]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by NickIliev** [comment]
These are the default iOS toolbar menu. To create a custom one you need to [overwrite the UIMenuControleer](https://medium.com/@sdrzn/how-to-use-the-ios-tooltip-menu-in-your-own-app-890a36faa1b2) while using [data conversion from Objective-C to JavaScript](https://docs.nativescript.org/core-concepts/ios-runtime/Marshalling-Overview).

Closing this one as how-to related - you can post a similar question in the community channels like [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) or the NativeScript slack.
