### ISSUE TITLE
suddenly: newly created android app gives errors

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#6549]
Please see [issues/323](https://github.com/NativeScript/sample-Groceries/issues/323l)

**Comment by jokro** [comment]
Error in ling. Onde more, please see [sample-Groceries/issues/323](https://github.com/NativeScript/sample-Groceries/issues/323)

**Comment by NickIliev** [comment]
@jokro make sure you are working with the latest version of `tns-android`, `tns-core-modules` and that you have installed Android SDK 28. If the issue persists please consider providing detailed information about your project's configuration files (package.json and local environment versions).

Closing as a duplicate to the linked issues above.
