### ISSUE TITLE
QWERTY Keyboard when 2 secure field 

### ISSUE THREAD

**Issue by acortino** [NativeScript/NativeScript#6555]
**Describe the bug**
I want to add a "Confirm password" on my register Page. But when I put a second Textfield with secure=true, the keyboard for these two fields are in QWERTY when all other Textfield in the form are in AZERTY

**To Reproduce**
```
<ActionBar title="Home" class="action-bar">
</ActionBar>

<GridLayout>
    <ScrollView class="page">
        <StackLayout class="form">
            <StackLayout class="input-field">
                <Label text="Prénom" class="label font-weight-bold m-b-5"></Label>
                <TextField class="input" autocorrect="false" name="firstname"></TextField>
                <StackLayout class="hr-light"></StackLayout>
            </StackLayout>
            <StackLayout class="input-field">
                <Label text="Nom" class="label font-weight-bold m-b-5"></Label>
                <TextField class="input" autocorrect="false" name="lastname"></TextField>
                <StackLayout class="hr-light"></StackLayout>
            </StackLayout>
            <StackLayout class="input-field">
                <Label text="Email" class="label font-weight-bold m-b-5"></Label>
                <TextField class="input" autocorrect="false"
                    autocapitalizationType="none" autocomplete='email' name="email"></TextField>
                <StackLayout class="hr-light"></StackLayout>
            </StackLayout>

            <StackLayout class="input-field">
                <Label text="Mot de passe" class="label font-weight-bold m-b-5"></Label>
                <TextField name="password" class="input" secure="true"></TextField>
                <StackLayout class="hr-light"></StackLayout>
            </StackLayout>
            <StackLayout class="input-field">
                <Label text="Confirmation mot de passe" class="label font-weight-bold m-b-5"></Label>
                <TextField name="passConf" class="input" secure="true"></TextField>
                <StackLayout class="hr-light"></StackLayout>
            </StackLayout>
        </StackLayout>
    </ScrollView>
</GridLayout>
```
**Expected behavior**

**Sample project**

https://play.nativescript.org/?template=play-ng&id=ODdaN7

**Additional context**

The mail field is in AZERTY
![2018-11-13 09 56 57](https://user-images.githubusercontent.com/3941710/48402001-ca17cc00-e72a-11e8-8c75-17459988b379.png)
The password field is in QWERTY
![2018-11-13 09 57 01](https://user-images.githubusercontent.com/3941710/48402002-ca17cc00-e72a-11e8-8f11-74bcddb896a6.png)
But when I remove the second secure field, the password is in AZERTY
![2018-11-13 09 57 42](https://user-images.githubusercontent.com/3941710/48402003-ca17cc00-e72a-11e8-8cc4-7f83e61f14d1.png)

**Comment by tsonevn** [comment]
Hi @acortino,
I tested the provided sample project on iPhone SE with iOS 12, however, was unable to recreate the problem. Can you give some more info about the device, you are using(device type, iOS version)? Are there any specific steps, that are needed for recreating the issue.

**Comment by tsonevn** [comment]
Hi @acortino,
I have tested this case in a native iOS application, and it seems that this issue is not related to NativeScript. The same behaviour can be seen in a native app. The keyboard for the TextField with enabled security will be QWERTY  and for the others -  AZERTY. For your convenience, I am attaching a sample native project and GIF, where it is demonstrated the native behaviour.
![screencast 2018-11-15 at 3 12 37 pm](https://user-images.githubusercontent.com/17448734/48555494-13fae080-e8ea-11e8-9939-663c77556087.gif)

[testfield.zip](https://github.com/NativeScript/NativeScript/files/2585434/testfield.zip)
