### ISSUE TITLE
Setting image color on TabView

### ISSUE THREAD

**Issue by yassern** [NativeScript/NativeScript#6557]
On styling a TabView we can set colors of text, background but not png images neither access to use the `tint-color` property, we can only set the iconSource path.

**Comment by NickIliev** [comment]
@yassern  [here you can find examples](https://docs.nativescript.org/ui/ns-ui-widgets/tab-view#styling) for the supported styling options for TabView (the Angular article [here](https://docs.nativescript.org/angular/ui/ng-ui-widgets/tab-view#styling)).

There is a property called `selectedTabTextColor` -  

> 
`selectedTabTextColor` -  (corresponding CSS property selected-tab-text-color ) -  used to change the color of the text while selecting some of the tabs.


There is also an Android specific property for the selected tab

> 
androidSelectedTabHighlightColorandroid specific property (corresponding CSS property android-selected-tab-highlight-color) - setup underline color of the Tabs in Android.
