### ISSUE TITLE
Nativescript preview crashing

### ISSUE THREAD

**Issue by AhmedAzzabi** [NativeScript/NativeScript#6559]
**Environment**
√ Getting NativeScript components versions information...
‼ Update available for component nativescript. Your current version is 5.0.0 and the latest available
version is 5.0.1.
‼ Update available for component tns-core-modules. Your current version is 5.0.1 and the latest available version is 5.0.2.
√ Component tns-android has 5.0.0 version and is up to date.
√ Component tns-ios has 5.0.0 version and is up to date.

**Describe the bug**
Looks that nativescript preview crashes when there is a node lib dependency in project, for example i have a project using node-html-parser, in emulator and real device no issue, but when tried tns preview, it crashes  with message failed to find module 'node-hml-parser'

**To Reproduce**
Add npm install --save node-html-parser to your app as dependecy, execute tns preview and scan QR code the app will crash with message failed to find module 'node-hml-parser'

**Expected behavior**
Work as emulator and real device
**Sample project**

**Comment by tsonevn** [comment]
Hi @AhmedAzzabi,
Currently, the preview app has a limitation and does not support using plugins, which are not included in the preview app. 
Regarding that, if you need to use the node-html-parser, you can test it at this time, using the local builds.

**Comment by AhmedAzzabi** [comment]
Ok thanks, i thought plugins refer to nativescript plugins but looks normal node libs are not supported too. Any plans to support these ? As it is hard to believe that apps dont use node lib or nativescript plugin. Many thanks you have great product though.

**Comment by tsonevn** [comment]
Hi @AhmedAzzabi,
  In the future, we might extend the list of the supported plugins from the preview app, however, there are no plans for providing similar functionality for adding external libs.

Regards,
@tsonevn
