### ISSUE TITLE
Debug not working with flag --hmr

### ISSUE THREAD

**Issue by AhmedAzzabi** [NativeScript/NativeScript#6560]
**Environment**
√ Getting NativeScript components versions information...
‼ Update available for component nativescript. Your current version is 5.0.0 and the latest available
version is 5.0.1.
‼ Update available for component tns-core-modules. Your current version is 5.0.1 and the latest available version is 5.0.2.
√ Component tns-android has 5.0.0 version and is up to date.
√ Component tns-ios has 5.0.0 version and is up to date.
**Describe the bug**
Im using VSCode for debugging, i added tnsArgs:["--hmr"] flag in launch.config from console i can see that debug is launch with --hmr, but what i noticed is when i update code or xml it gets updated and see webpack logs in terminal, but the app close and reopen again instead of staying open as it is the case with tns run. Also i noticed that the change takes effect before app close and starts again so hmr work but looks buggy.
**To Reproduce**
Take any sample app, in VSCode with nativescript, modify launch.config of visual studio to add tnsArgs["--hmr"] hit F5, change the code or xml files notice the app close after each file save instead of remaining open.

**Expected behavior**
HMR works correctly and not restart app.

**Comment by Fatme** [comment]
@AhmedAzzabi,

Currently debug command does not support `--hmr` mode but we're working on implementing it. You can track the progress of the feature in this thread https://github.com/NativeScript/nativescript-cli/issues/2992.
