### ISSUE TITLE
HMR crashes on topmost().navigate(...)

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/NativeScript#6562]
I am trying the new hmr feature and I am running into an issue.  I create a sample project using **tns create NativeLibrariesTest --template typescript**.  In the project I created a second page called page2.  I placed 2 buttons, one on main-page that navigates to page2 and one on page2 that navigates back to main-page.  Then I run the app on my physical test device with **tns run android --device 1 --hmr**

When I press the button to navigate to page2, I get the following error:
```
System.err: com.tns.NativeScriptException:
System.err: Calling js method onClick failed
System.err:
System.err: TypeError: Cannot read property 'onNavigatingTo' of undefined
System.err: File: "file:///data/data/org.nativescript.NativeLibrariesTest/files/app/vendor.js, line: 20112, column: 36
```

If I run the same app without the --hmr switch everything works as expected.

Here is my code:
main-page.ts
```
import { EventData } from "tns-core-modules/data/observable";
import { Page } from "tns-core-modules/ui/page";
import { HelloWorldModel } from "./main-view-model";
import { Frame, topmost } from "tns-core-modules/ui/frame";

var page;
export function navigatingTo(args: EventData) {
    page = <Page>args.object;
    page.bindingContext = new HelloWorldModel();
}

export function forward() {
    const navigationEntry = {
        moduleName: "page2",
        context: page.bindingContext.get('message'),
        animated: false
    };
    topmost().navigate(navigationEntry);
}
```

page2.ts
```
import { EventData } from "tns-core-modules/data/observable";
import { Page } from "tns-core-modules/ui/page";
import { Frame, topmost } from "tns-core-modules/ui/frame";
import { Observable } from "tns-core-modules/data/observable";

var model: Observable;

export function navigatingTo(args: EventData) {
    let page = <Page>args.object;

    model = new Observable();
    model.set('message', page.navigationContext);

    page.bindingContext = model;
}

export function back() {
    topmost().navigate('main-page');
}
```

package.json:
```
{
  "nativescript": {
    "id": "org.nativescript.NativeLibrariesTest",
    "tns-android": {
      "version": "5.0.0"
    },
    "tns-ios": {
      "version": "5.0.0"
    }
  },
  "main": "app.js",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "nativescript-theme-core": "~1.0.4",
    "tns-core-modules": "~5.0.2"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.18.0",
    "typescript": "^3.1.6"
  },
  "readme": "NativeScript Application"
}
```

Am I missing something or this is a bug in the hmr module?
Thanks

**Comment by tsonevn** [comment]
Hi @dpdragnev,
This seems to be a bug while building the project with `--hmr` flag. I am attaching a sample project, which can be used for debugging. 
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2588258/Archive.zip)

**Comment by vchimev** [comment]
Hey @dpdragnev,

The [Hot Module Replacement in NativeScript](https://www.nativescript.org/blog/nativescript-hot-module-replacement) is implemented with the [webpack](https://docs.nativescript.org/performance-optimizations/bundling-with-webpack) module bundler.

The issue you're experiencing is not related to the HMR itself, but the fact that `page2` you created is not included in the application bundle. The [`bundle-config-loader`](https://github.com/NativeScript/nativescript-dev-webpack/blob/0.18.0/bundle-config-loader.js#L3) registers app's XML, CSS and JavaScript pages with a regex and all pages' resources should be named as that they end with either `root` of `page`, so renaming `page2` to `page2-page` will work as expected.
