### ISSUE TITLE
Custom ActionBar not working ANDROID(ANGULAR) version 5.0.0

### ISSUE THREAD

**Issue by tebieto** [NativeScript/NativeScript#6566]
Everything is working fine on my new Nativescript-Angular project but my custom ActionBar <ActionBar></ActionBar> does not display. The App uses the default ActionBar with default app title... tns vesion is 5.0.0.

**Comment by tsonevn** [comment]
Hi @tebieto,
Can you provide a sample project or at least some sample code snippets, which can be used for recreating the problem?

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-angular #1613](https://github.com/NativeScript/nativescript-angular/issues/1613) via [**ZenHub**](https://www.zenhub.com/)
