### ISSUE TITLE
Nativescript 5 Angular animation problems

### ISSUE THREAD

**Issue by yonkoGH** [NativeScript/NativeScript#6570]
- CLI: 5.0.0
 - Cross-platform modules: 5.0.0
 - Android Runtime: 5
 - iOS Runtime: 5
 - Plugin(s):

**Describe the bug**
angular animation not working well with Nativescript 5   

**Sample project**
https://play.nativescript.org/?template=play-ng&id=Hqp5UQ&v=2576

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-angular #1617](https://github.com/NativeScript/nativescript-angular/issues/1617) via [**ZenHub**](https://www.zenhub.com/)
