### ISSUE TITLE
Extending Application and Activity

### ISSUE THREAD

**Issue by bagnos** [NativeScript/NativeScript#6571]
How Can I extend Application and Activity in a code-sharing project? There is no documentation about this kind of project, using the official documentation we get a ClassNotFoundException.

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-schematics #155](https://github.com/NativeScript/nativescript-schematics/issues/155) via [**ZenHub**](https://www.zenhub.com/)
