### ISSUE TITLE
Layout/style issue with NS 5.0

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/NativeScript#6575]
Using NS 5.0 on ios.

Have the following xml file definition

```
   <ScrollView>
        <StackLayout>
            <Label height="650" text="First Label"/>

            <GridLayout rows="100" columns="*" backgroundColor="red">        
                <Label text="Second Label" />
            </GridLayout>

            <Label text="Third Label" textWrap="true" />

        </StackLayout>
    </ScrollView>
```

The height of 650 for the first Label makes the 3rd  Label off screen.

But as you scroll down to it - the third Label has style attributes of the second child (i.e. GridLayout). It displays in red. Same if there's a CSS class definition.

This can be duplicated by copying the above into any page xml file. The key is to set the height for the first Label so that the third Label is initially off screen.

**Comment by tsonevn** [comment]
Hi @erjdriver,
Can you try adding `@next` modules in the project and check if you will face the same issue? (`tns plugin remove tns-core-modules` -> `tns plugin add tns-core-modules@next`)? After updating make sure to delete  `platforms` folder.

**Comment by erjdriver** [comment]
Unfortunately that did NOT work.

Here's the line from the package file `"tns-core-modules": "^5.0.2-rc-2018-11-07-211354-02"`

I note that if I replace the second child from a layout to just Label -works fine.

I tested with GridLayout and StackLayout and both had the same issue - the style gets propagated to the next child.

**Comment by tsonevn** [comment]
Hi @erjdriver 
`"^5.0.2-rc-2018-11-07-211354-02"` is an old version of the NativeScript modules. Did you try adding `@next` modules using the above, mentioned commands -> (`tns plugin remove tns-core-modules` -> `tns plugin add tns-core-modules@next`)?

**Comment by erjdriver** [comment]
Voila that worked - when will that be released?
