### ISSUE TITLE
[iOS] Inconsistency with isEnabled property on ListView

### ISSUE THREAD

**Issue by shiv19** [NativeScript/NativeScript#6576]
**Environment**
Reproducible on playground 

**Describe the bug**
When `isEnabled` is set to false, you can't scroll through the ListView on android,
but you can on iOS.

**To Reproduce**
Try to scroll through the list on Android in this playground sample,
Then try on iOS.
https://play.nativescript.org/?template=play-tsc&id=wlaieB

**Expected behavior**
You should not be able to scroll on iOS too.

**Comment by tsonevn** [comment]
Hi @shiv19,
Thank you for the provided sample project. We will investigate further what is causing the issue on iOS.

**Comment by manoldonev** [comment]
@shiv19 indeed the behavior is inconsistent but on the other hand that's the standard behavior for each platform. As far as I can see on iOS [UIControl.enabled](https://developer.apple.com/documentation/uikit/uicontrol/1618217-enabled?language=objc) property does nothing for container controls e.g. UIScrollView (NativeScript ScrollView), UITableView (NativeScript ListView) so I am not sure we should override this.

Could you elaborate what exactly are you trying to achieve as setting ListView.isEnabled will prevent you from tapping the buttons on Android as well?

**Comment by shiv19** [comment]
On Android, setting isEnabled to false would only prevent from scrolling. But still allow me to tap the buttons.

I'm working on a UI where there is a panel that you can slide up and interact with. 

When the panel is closed, you can see the currently active step in the list. And interact with it. 

When the panel opens you can scroll and interact with other steps on the list view. 

I'm able to do this on Android. 
But on iOS isEnabled doesn't disable scrolling on the listview. 

Please let me know if more context is needed

**Comment by manoldonev** [comment]
> On Android, setting isEnabled to false would only prevent from scrolling. But still allow me to tap the buttons.

Technically speaking I am not sure the current Android behavior for isEnabled=false is "correct". It is true that buttons in the item template are interactive and scrolling is disabled (listview.itemtap is not fired as well). But one could say it is logical that isEnabled=false should disable buttons in the item template as well. On the other hand iOS native container controls do not have an opinion for isEnabled concept at all and for the time being we will not be trying to provide consistent behavior across platforms for this property (nor modify the Android behavior).

As for your specific case -- isEnabled does not look like the property one would use to enable this kind of functionality but if the current Android isEnabled behavior works for you, you can use it.

For iOS I would suggest you to disable scrolling directly on the native UITableView like this:
``` xml
<ListView ios:loaded="onListViewLoaded" android:isEnabled="false" class="list-group" items="{{ countries }}" itemTap="{{ onItemTap }}">
    <ListView.itemTemplate>
        <FlexboxLayout flexDirection="row" class="list-group-item">
            <Image src="{{ imageSrc }}" class="thumb img-circle" />
            <Label text="{{ name }}" class="list-group-item-heading"
                verticalAlignment="center" style="width: 60%" />
        </FlexboxLayout>
    </ListView.itemTemplate>
</ListView>
```

```ts
import { EventData } from 'tns-core-modules/data/observable';
import { ListView } from "tns-core-modules/ui/list-view";

// ...

export function onListViewLoaded(args: EventData) {
    const listView = <ListView>args.object;
    // listView.ios is an UITableView instance
    listView.ios.scrollEnabled = false;
}
```

**Comment by shiv19** [comment]
@manoldonev thank you :)
I agree with your reasoning.
