### ISSUE TITLE
Back button in Action bar- not working for android

### ISSUE THREAD

**Issue by princy05** [NativeScript/NativeScript#6579]
I have an action bar with back button for both android and ios. 
On clicking the back button in the action, it is working for ios. But, in android clicking the back arrow is not navigating to previous page. 
<img width="333" alt="screen shot 2018-11-19 at 11 18 42 am" src="https://user-images.githubusercontent.com/16576656/48723695-f3ce6880-ebec-11e8-86d0-17083ab0f7b5.png">

**Comment by tsonevn** [comment]
Hi @princy05,
Please provide a sample project or at least the code fragment related to the issue, you are facing. 

Also, keep in mind that if you are using NavigationButton, for Android you need to set up the [tap event](https://docs.nativescript.org/ui/action-bar#navigation-button) and to provide the needed functionality for the back navigation. I this case you can use [goBack](https://docs.nativescript.org/api-reference/classes/_ui_frame_.frame#goback) method provided by frame module.

**Comment by princy05** [comment]
Thanks for your help. I added the tap event and it is working fine now.
So I am closing this
