### ISSUE TITLE
Receive images in iOS by share intent

### ISSUE THREAD

**Issue by agnoam** [NativeScript/NativeScript#6583]
There is any way to make my app shareable in IOS ?
That means to take any app like gallery and choose one image or more and share my app with those images.

Anyone know how to do it ?

**Comment by NickIliev** [comment]
@agnoam to achieve that you need to enable [ Share extensions](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Share.html) which in NativeScript needs some additional work (more information [here](https://github.com/NativeScript/nativescript-cli/issues/3965)). 

CLosing as how-to related and duplicate to [https://github.com/NativeScript/nativescript-cli/issues/3965](https://github.com/NativeScript/nativescript-cli/issues/3965)

**Comment by agnoam** [comment]
Is there any tutorial you can give me to follow (specific to NativeScript) ?

**Comment by agnoam** [comment]
Is there any tutorial you can give me to follow (specific to NativeScript) ?

**Comment by NickIliev** [comment]
@agnoam you can try the steps in [this blog post ](https://www.nativescript.org/blog/making-a-today-widget-in-ios-with-nativescript-and-ui-for-nativescript)to enable the share extension and then implement it in your application by converting a native iOS code to JS/TSC. (e.g. some of the tutorial listed [here](https://www.google.bg/search?rlz=1C1CHBF_enBG781BG781&ei=5AT0W9XsK4-ugQay-rP4Dg&q=ios+share+extension+tutorial+objective+c&oq=ios+share+extension+tutorial+obj&gs_l=psy-ab.3.0.0i203j0i22i30.6022.6539..8428...0.0..0.247.577.0j3j1......0....1..gws-wiz.......0i19j0i22i30i19.fPF9pI9YPt8))

**Comment by agnoam** [comment]
Sorry, not mac os tutorial.
