### ISSUE TITLE
Update wiki's Migration Steps to NativeScript 5.0

### ISSUE THREAD

**Issue by ggodlewski** [NativeScript/NativeScript#6587]
I think the migration guide should be divided into 2 steps:
* Upgrading system
* Upgrading app itself

So I'd move "Update Android SDK" before "Navigate to your app"

After that add one more step: run "tns doctor" to check the installation.
Yeah, I wasted an hour before I reminded myself about this command.

Also 
```
tns platform remove android 
tns platform remove ios
```
Should be before:

```
rm -rf node_modules
rm -rf platforms
rm -rf hooks
```

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/docs #1443](https://github.com/NativeScript/docs/issues/1443) via [**ZenHub**](https://www.zenhub.com/)
