### ISSUE TITLE
Problem with iOS resizing when there is an activity running in background (active call, hotspot, etc.)

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#659]
There seems to be a problem when there is an activity running in the background and when the statusbar is higher than usual (like when you have an active call):

Loading screen (with active call):
![img_1340](https://cloud.githubusercontent.com/assets/9464097/9625450/e7179d7c-515e-11e5-9659-60faab4a7c48.PNG)

Loading screen (without active call):
![img_1343](https://cloud.githubusercontent.com/assets/9464097/9625463/fec35b6e-515e-11e5-865f-bdbe7cf035a3.PNG)

Simple grid layout (with active call):
![img_1341](https://cloud.githubusercontent.com/assets/9464097/9625486/2f9b9c74-515f-11e5-9028-f26d18ec2d2b.jpeg)

Simple grid layout (without active call):
![img_1342](https://cloud.githubusercontent.com/assets/9464097/9625481/234ca6d4-515f-11e5-8207-da231c8e79ea.jpeg)

Here is the XML for the grid layout page:
```xml
<Page xmlns="http://www.nativescript.org/tns.xsd">
  <Page.actionBar>
    <ActionBar title="TEST"/>
  </Page.actionBar>
  
  <GridLayout rows="auto, *, 30">
    <Label row="0" text="TOP" fontSize="20"/>
    <ListView row="1"></ListView>
    <Label row="2" text="BOTTOM" fontSize="20"/>
  </GridLayout>
</Page>
```

**Comment by hamorphis** [comment]
I found a way to fix this when the in-call status bar shows or hides while in the NS app. But I can't find a way to fix this when the NS app is started while the in-call status bar is displayed. Seems like some sort of iOS issue: https://forums.developer.apple.com/thread/20632

**Comment by speigg** [comment]
> So I don't really know how to force the NavBar to move down when the app is started or resumed while the in-call status bar is visible. Suggestions are welcome.

@hamorphis 
This is the workaround that I have figured out. When the page loads, if I do this:
```
	setTimeout(()=>{
		page.requestLayout();
	}, 0)
```

Then the navigation bar is rendered at the correct location. Hopefully you can derive a proper solution from this workaround.

**Comment by agisboye** [comment]
Has there been any progress on this issue? With NativeScript 3, the navigation bar glitches when the in-call status bar is visible.
![img_0746](https://user-images.githubusercontent.com/4165670/27129820-f55a6de6-5103-11e7-899f-9336b41944ea.PNG)
![img_0747](https://user-images.githubusercontent.com/4165670/27129821-f55db79e-5103-11e7-9a5d-f51ef952511c.PNG)

**Comment by soodohkohd** [comment]
I'm having this same issue.  It started after I upgraded core-tns-modules from 2.5.2 to 3.0.0.

Here's the basics of my environment...
`"dependencies": {
		"@angular/animations": "~4.1.0",
		"@angular/common": "~4.1.0",
		"@angular/compiler": "~4.1.0",
		"@angular/core": "~4.1.0",
		"@angular/forms": "~4.1.0",
		"@angular/http": "~4.1.0",
		"@angular/platform-browser": "~4.1.0",
		"@angular/router": "~4.1.0",
		"nativescript-angular": "~3.0.0",
		"nativescript-appversion": "^1.4.1",
		"nativescript-dev-sass": "^1.1.1",
		"nativescript-email": "^1.4.0",
		"nativescript-fingerprint-auth": "^4.0.0",
		"nativescript-iqkeyboardmanager": "^1.0.1",
		"nativescript-loading-indicator": "^2.3.2",
		"nativescript-permissions": "^1.2.3",
		"nativescript-phone": "^1.3.0",
		"nativescript-telerik-ui": "^2.0.1",
		"nativescript-theme-core": "~1.0.2",
		"reflect-metadata": "~0.1.8",
		"rxjs": "~5.3.0",
		"tns-core-modules": "~3.0.0",
		"zone.js": "~0.8.11"
	},
	"devDependencies": {
		"nativescript-dev-typescript": "~0.4.0",
		"typescript": "~2.2.1"
	}`

**Comment by soodohkohd** [comment]
If this issue is closed, can it be re-opened?
