### ISSUE TITLE
Can anyone help me with this ??

### ISSUE THREAD

**Issue by bfmnigfh0608** [NativeScript/NativeScript#6591]
![46507303_583499698777806_9203905406823301120_n](https://user-images.githubusercontent.com/45221675/48818953-93742e00-ed88-11e8-9cc5-4a6fec28358a.png)

**Comment by tsonevn** [comment]
Hi @bfmnigfh0608,
Can you provide some more info about the problem you are facing? It will also help if you give us some info about the CLI, tns-core-modules, tns-android versions, which you are using and the steps that you are following.

**Comment by bfmnigfh0608** [comment]
Thank you for the information
