### ISSUE TITLE
Handling popup window inside the webview 

### ISSUE THREAD

**Issue by LSmint** [NativeScript/NativeScript#6592]
How to support popup window when we clicked some link inside the webview, currently it seems like nothing happen when try to click popup link.

**Comment by tsonevn** [comment]
Hi @LSmint,
Check out the [nativescript-webview-interface](https://www.npmjs.com/package/nativescript-webview-interface) plugin, which allows you to create bi-directional communication between WebView and the application.

**Comment by LSmint** [comment]
@tsonevn ,

Thanks for your response. Some of the website may contains javascript alert/confirm dialog and i may not know the actual event name used in the website. Can this plugin handle for auto open the dialog directly if popup window is triggered?

**Comment by LSmint** [comment]
I got the way for Android, but still stuck on iOS:
`class MyWebChromeClient extends android.webkit.WebChromeClient
                {
                    constructor()
                    {
                        super();
                        return global.__native(this);
                    }

                    init()
                    {
                        return global.__native(this);
                    }

                    onJsAlert( webview: android.webkit.WebView, url: string, msg: string, result: android.webkit.JsResult ) : boolean
                    {
                        // my function - but NS has one also
                        // console.log("MESSAGE:"+msg)
                        alert(msg);
                        // utils.errorDialog( msg, "MESSAGE" );
                        
                        result.confirm();
                        
                        return true;
                    }
                }
                webview.android.getSettings().setPluginsEnabled(true);
                webview.android.getSettings().setAllowFileAccess(true);
                webview.android.getSettings().setMixedContentMode(0);
                webview.android.getSettings().setJavaScriptEnabled(true);
                webview.android.getSettings().setJavaScriptCanOpenWindowsAutomatically(true);
                webview.android.setWebChromeClient( new MyWebChromeClient() );`

**Comment by tsonevn** [comment]
Hi @LSmint,
While using the plugin, you should create a custom event listener and emit an event with the same event name via Site's  JavaScript, when the site alert/confirm result is available. Check out the sample in the plugin's [readme](https://github.com/shripalsoni04/nativescript-webview-interface#inside-native-app).

Also, I found the article [here](https://mislavjavor.github.io/2016-03-08/WKWebView-advanced-tutorial/), which describes how you can define a similar listener using native code. Keep in mind that I have not tested this scenario and cannot guarantee that it will work in a NativeScript app.

**Comment by LSmint** [comment]
@tsonevn , Thank for your sharing, i will study it and find out the way to handle it.
