### ISSUE TITLE
tns create foobar results into a hello world exception

### ISSUE THREAD

**Issue by sombriks** [NativeScript/NativeScript#6596]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.1
 - Cross-platform modules: -
 - Android Runtime: - 
 - iOS Runtime: - 
 - Plugin(s): - 

**Describe the bug**

just tried to run the hello world project. it gave me an exception

**To Reproduce**

- fresh install nativescript from npm
- do "tns create foo"
- select vue when asked
- install nativescript playground and nativescript preview on android phone
- do tns preview
- scan qrcode using playground
- preview shows exception

**Expected behavior**

running from playground the vue hello world works correctly

**Sample project**

-
**Additional context**

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #4166](https://github.com/NativeScript/nativescript-cli/issues/4166) via [**ZenHub**](https://www.zenhub.com/)
