### ISSUE TITLE
RadDataForm and sources containing lists generates conflicting error

### ISSUE THREAD

**Issue by lonerzzz** [NativeScript/NativeScript#6597]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.01
 - Cross-platform modules: 
 - Android Runtime: 5.0.0
 - iOS Runtime:  5.0.0
 - Plugin(s): 

**Describe the bug**
Currently the RadDataForm does not seem to support source objects containing list entities, but the error message seems to contradict this. The error indicates both that an object of type JSONArray is not supported and that a value converter should be added. Even when a value converter is added, the following error occurs. The error should indicate only that a JSONArray is not supported rather than suggesting that a value converter might solve the problem. Alternatively, the code could support passing a JSONArray to a value converter to let it resolve the list to an appropriate value.

Error: java.lang.Error: DataFormTextEditor does not support properties of type JSONArray. Please specify a value converter for your property.  com.telerik.widget.dataform.visualization.core.EntityPropertyViewer.loadPropertyValue(EntityPropertyViewer.java:431)
com.telerik.widget.dataform.visualization.core.EntityPropertyEditor.loadPropertyValue(EntityPropertyEditor.java:201)
com.telerik.widget.dataform.visualization.core.EntityPropertyViewer.load(EntityPropertyViewer.java:409)
    com.telerik.widget.dataform.visualization.core.EntityPropertyEditor.load(EntityPropertyEditor.java:189)
    com.telerik.widget.dataform.visualization.RadDataForm.load(RadDataForm.java:806)
    com.telerik.widget.dataform.visualization.RadDataForm.reload(RadDataForm.java:485)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
    com.tns.Runtime.callJSMethod(Runtime.java:983)
    com.tns.Runtime.callJSMethod(Runtime.java:967)
    com.tns.Runtime.callJSMethod(Runtime.java:959)
    com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
    android.os.Handler.handleCallback(Handler.java:751)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6823)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1557)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
Caused by: java.lang.ClassCastException: org.json.JSONArray cannot be cast to java.lang.String
com.telerik.widget.dataform.visualization.editors.DataFormTextEditor.applyEntityValueToEditor(DataFormTextEditor.java:103)
com.telerik.widget.dataform.visualization.core.EntityPropertyViewer.loadPropertyValue(EntityPropertyViewer.java:429)
com.telerik.widget.dataform.visualization.core.EntityPropertyEditor.loadPropertyValue(EntityPropertyEditor.java:201)
com.telerik.widget.dataform.visualization.core.EntityPropertyViewer.load(EntityPropertyViewer.java:409)
    com.telerik.widget.dataform.visualization.core.EntityPropertyEditor.load(EntityPropertyEditor.java:189)
    com.telerik.widget.dataform.visualization.RadDataForm.load(RadDataForm.java:806)
    com.telerik.widget.dataform.visualization.RadDataForm.reload(RadDataForm.java:485)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
    com.tns.Runtime.callJSMethod(Runtime.java:983)
    com.tns.Runtime.callJSMethod(Runtime.java:967)
    com.tns.Runtime.callJSMethod(Runtime.java:959)
    com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
    android.os.Handler.handleCallback(Handler.java:751)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6823)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1557)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**To Reproduce**
Use a source object containing a property of type array. Then provide a converter for the property converter to handle that type. The converter will never be called and the error will occur beforehand.

**Expected behavior**
The error should indicate that arrays are not supported or should allow the converter to handle the array.

**Sample project**
Do not have a simple project for this at the moment.

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#941
