### ISSUE TITLE
'tns update' command hangs for a long period without stating that it is doing anything.

### ISSUE THREAD

**Issue by lonerzzz** [NativeScript/NativeScript#6598]
**Environment**
 - CLI: 5.0.1
 - Android Runtime: 5.0.0
 - iOS Runtime: 5.0.0

**Describe the bug**
When running command line 'tns update 5.0.3', the program hangs without any output for several minutes before printing out errors or problems. No status is printed to indicate that anything is happening.

**Expected behavior**
Commands with long run durations should provide status updates along the way to indicate what is happening.

**Comment by NickIliev** [comment]
Closing as duplicate to https://github.com/NativeScript/nativescript-cli/issues/4165
