### ISSUE TITLE
'tns update 5.0.3' fails with useless error

### ISSUE THREAD

**Issue by lonerzzz** [NativeScript/NativeScript#6599]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.1
 - Android Runtime: 5.0.0
 - iOS Runtime: 5.0.0

**Describe the bug**
Running 'tns update 5.0.3' fails with the error 'Could not update the project!'. The output should state the cause of the update failure or point to logs that can tell what is happening. As it is, there is no indication of the cause of the error.

**Expected behavior**
A useful error should be presented to allow user to investigate the cause of the error instead of having to guess.

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #4165](https://github.com/NativeScript/nativescript-cli/issues/4165) via [**ZenHub**](https://www.zenhub.com/)
