### ISSUE TITLE
NativeScript and plugins

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#66]
_From @calebeaires on March 17, 2015 13:15_

Will NativeScript have plugins like Admob and Sqlite?

_Copied from original issue: NativeScript/cross-platform-modules#191_

**Comment by enchev** [comment]
_From @jgamedev on March 28, 2015 0:28_

+1 for AdMob support!

**Comment by enchev** [comment]
_From @ujjawalmisra on April 17, 2015 7:54_

+1 fro Sqlite support!

**Comment by Nathanaela** [comment]
For those seeing this Bug Issue #73 is for Sqlite support.

**Comment by enchev** [comment]
https://github.com/NativeScript/docs/blob/master/plugins.md
