### ISSUE TITLE
RadDataForm Groups not Displaying in Angular

### ISSUE THREAD

**Issue by lonerzzz** [NativeScript/NativeScript#6602]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.01
 - Cross-platform modules: 5.0.0
 - Android Runtime: 5.0.0
 - iOS Runtime: NA
 - Plugin(s): NA

**Describe the bug**
When using a RadDataForm in NativeScript with Angular2, groups are not displayed. Using the linked playground example from the sample section below, the form simply displays the list of email addresses without any trace of grouping around the email addresses and without any errors. If this is a case of incorrect usage, then the problem comes down to a lack of examples or incomplete documentation.

As a follow on, the grid layout within the form also does not work but that may be a result of the issue with the grouping to begin with.

```
<RadDataForm #contactSettingsForm [source]="contactSettings" commitMode="Manual" validationMode="Immediate"
		(propertyValidate)="onContactSettingsValidate($event)" (propertyValidated)="onContactSettingsValidated($event)">
	<TKPropertyGroup name="Email Contact Addresses" collapsible="true" hidden=false>
		<TKPropertyGroupProperties>
			<TKEntityProperty tkDataFormProperty name="emailAddress1" displayName="Email Address 1" [emailAddress1]="emailAddress1" hintText="Enter an email contact address" index="9">
				<TKPropertyEditor tkEntityPropertyEditor type="Email"></TKPropertyEditor>
				<TKEmailValidator tkEntityPropertyValidators errorMessage="Please enter a valid email address"></TKEmailValidator>
			</TKEntityProperty>
			<TKEntityProperty tkDataFormProperty name="emailAddress2" displayName="Email Address 2" [emailAddress2]="emailAddress2" hintText="Enter an email contact address" [hidden]="isHidden(index)" index="10">
				<TKPropertyEditor tkEntityPropertyEditor type="Email"></TKPropertyEditor>
				<TKEmailValidator tkEntityPropertyValidators errorMessage="Please enter a valid email address"></TKEmailValidator>
			</TKEntityProperty>
			<TKEntityProperty tkDataFormProperty name="emailAddress3" displayName="Email Address 3" [emailAddress3]="emailAddress3" hintText="Enter an email contact address" [hidden]="isHidden(index)" index="11">
				<TKPropertyEditor tkEntityPropertyEditor type="Email"></TKPropertyEditor>
				<TKEmailValidator tkEntityPropertyValidators errorMessage="Please enter a valid email address"></TKEmailValidator>
			</TKEntityProperty>
		</TKPropertyGroupProperties>
	</TKPropertyGroup>
</RadDataForm>

```

**To Reproduce**
See playground link provided below. The page loads with a form.

**Expected behavior**
The grouping should work as indicated in the documentation.

**Sample project**
https://play.nativescript.org/?template=play-ng&id=GOwBOc

**Additional context**
None

**Comment by NickIliev** [comment]
This issue was moved to telerik/nativescript-ui-feedback#943
