### ISSUE TITLE
Mot playing base64 audio with WebView

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#6603]
I am trying to find out how to play base64 coded audio.
I found a [playground example](https://play.nativescript.org/?template=play-tsc&id=i6n8rT&v=9). It uses a webview. Unfortunately it does not play on my android device, although the maker seems to have posted it when it played for him. According to HTML 5 documentation it should play.

1. What can be wrong. Would it be necessary to ask permissions first ? If so, how must this be done?

2. I am using the nativescrit audio plugin. Would it be possible to play base64 data with this plugin ?
Thx

**Comment by NickIliev** [comment]
@jokro check if you have permissions to open the site hosting the audio file. At my side, the site is blocked due to piracy concerns and the audio file can't be loaded at all.

However, using an mp3 free sample from the non-blocked site is working as expected on my side (testing on XIaomi Android 8) - here is the [modified Playground demo ](https://play.nativescript.org/?template=play-tsc&id=i6n8rT&v=10)(note that you will still need to press play manually)

**Comment by jokro** [comment]
Thx for the demo. I understand you only changed src= "data:audio/mp3;base64,${base64String}" ? I tried this but because it was not working I got stuck. In your example I get the message that the file is blocked. thx.

I have a related question to make sure it works for ios too. In the example  I see android related code:
`const base64String = android.util.Base64.encodeToString(file.readSync(), android.util.Base64.NO_WRAP);`

Will this work for ios or can I use JSON.stringify to encode to base64 in stead?  What about android.util.Base64.NO_WRAP?
thx

**Comment by NickIliev** [comment]
@jokro yes I've changed only the URL.

the  `android.util.Base64` is accessing the native Android API so it won't work on iOS. You will need a similar wrapper for the iOS counterpart. Look[ at this thread ](https://discourse.nativescript.org/t/how-to-base64-encode-a-string-in-nativescript/345/6)for details on how to implement encode and decode for both platforms

**Comment by jokro** [comment]
The thread you sent contains a variable NSUTF8StringEncoding which is null and used as a parameter. This worries me. I googled triniwiz's snippets to check if this is an error. I can't find the source snippet however.

**Comment by jokro** [comment]
I found the triniwiz's source [here](https://discourse.nativescript.org/t/how-to-base64-encode-a-string-in-nativescript/345). It has the same problem/question I described above, the null parameter called NSUTF8StringEncoding.

**Comment by jokro** [comment]
The above thread also describes the following nativescript plugins. Would it be possible to use these instead to encode and decode the platform dependent data, or is it necessary to use the platform specific code  ?
```
import * as  base64 from "base-64";
import * as utf8 from "utf8";
Then in your code:
var str = "myfancystring";
var bytes = utf8.encode(str);
var encodedStr = base64.encode(bytes);
console.log(encodedStr);
```

**Comment by NickIliev** [comment]
@jokro I haven't tried the npm packages in the above sample but if they are building with a NativeScript app (thus they are not DOM dependent) then you can absolutely use those packages.

Regarding `NSUTF8StringEncoding`

This is [native iOS enumeration ](https://developer.apple.com/documentation/foundation/1497293-anonymous/nsutf8stringencoding?language=objc) and in order, to use it you should either include [tns-platform-declarations](https://www.npmjs.com/package/tns-platform-declarations) as a dev dependency

**Comment by jokro** [comment]
Thx. I managed to get it working with
 npm install utf8 --save  ; and 
 import {NSUTF8StringEncoding} from "utf8";
