### ISSUE TITLE
Nativescipt - Blurry effect for line chart using canvas

### ISSUE THREAD

**Issue by bijalmistry** [NativeScript/NativeScript#6605]
Hello Developer Team,

We have one application developed in Nativescript 4.2 with Angular v6. In our app we have to plot a line chart graph using canvas, but when we are trying to plot a graph then we have blurry effect.

Following is the demo code for your reference.
https://play.nativescript.org/?template=play-ng&id=zp7MGK&v=11

An urgent help in solving this issue will be greatly appreciated!

Thanks In Advance!
Bijal Mistry

**Comment by NickIliev** [comment]
@bijalmistry you could use [nativescript-ui-chart](https://www.npmjs.com/package/nativescript-ui-chart) and create your own custom looking chart - the plugin provides a lot of opportunities.

As far as I understand the question you are asking is related to canvas usage in WebView - which is a web concept. I would suggest posting this one in the community channels (e.g. NativeScript slack or StackOverflow) and also providing more detailed information on what you are meaning by "when we are trying to plot a graph then we have a blurry effect." I am not entirely sure that your question is related to NativeScript modules as I am seeing a WebView inlined code creating a canvas which seems to work as expected..

Keep in mind that this repository is for logins bugs, issues and feature requests related to NativeScript.
Closing this issue as a how-to related question.
