### ISSUE TITLE
How to solve android safe area like iphone x

### ISSUE THREAD

**Issue by ms-typescript** [NativeScript/NativeScript#6609]
**Environment**
- Android Runtime:

**Describe the bug**

How to solve android safe area like iphone x when android this.page.actionBarHidden = true;

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by NickIliev** [comment]
@ms-typescript so far there is no safe area property like the iOS `iosOverflowSafeArea`. The feature is currently neede only on several Android 9 devices so you could try to handle this case by implementing your own logic for Android P (e.g. by using [versions check](https://developer.android.com/reference/android/os/Build.VERSION) and then applying an additional space for the area).

**Comment by ms-typescript** [comment]
thank you
