### ISSUE TITLE
getViewById cannot find <audio>view inside WebView

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#6612]
In  [playground](https://play.nativescript.org/?template=play-tsc&id=cq2BTk&v=4) I tested if getViewById can find a LabelView with id='label' inside a WebView. I find that the following statement  returns undefined:
```
console.log(page.getViewById('label'))
```
Is this a bug ? Is there another way to find the Label's view ?

I have a WebView to play audio from base64. To play by js I need the audio view (audioView.play()). I do not know another way then WebView to play base64 audio. The standard controls are not enough, I need to play, pause and stop under program control.

.

**Comment by tsonevn** [comment]
Hi @jokro,
The `getViewById ` can be used only for getting an instance of an element inside the application page, however, It can not be used for accessing an element inside the WebView. You can check the example [here](https://docs.nativescript.org/ui/basics#execute-business-logic). In your case, you have set up the Label inside the WebView's src, and it is expected the page to not find an element with id `label ` while using `getViewById `. If you need to play audio inside the NativeScript app, you can use the [nativescript-audio](https://www.npmjs.com/package/nativescript-audio) plugin.

**Comment by tsonevn** [comment]
Hi @jokro,
You can use the [nativescript-webview-interface](https://www.npmjs.com/package/nativescript-webview-interface) plugin. The plugin allows you to create bi-directional communication between WebView and the app. You can create a custom event listener(for play/pause/stop of the audio) in the page source, which you will load in the WebView and to trigger this event via the app. You can find more info about the usage of the plugin inside in [its repository](https://github.com/shripalsoni04/nativescript-webview-interface).
