### ISSUE TITLE
How to replace keyboard an emoji's keyboard in textview  Nativescript?

### ISSUE THREAD

**Issue by yogapriyaK** [NativeScript/NativeScript#6614]

**Comment by tsonevn** [comment]
HI @yogapriyaK,
Check out the link [here](https://docs.nativescript.org/api-reference/modules/_ui_enums_.keyboardtype), where it is described which keyboard types can be set up to the TextView using NativeScript. Also, you can always enable the emoji keyboard using the device settings([iOS](https://support.apple.com/en-us/HT202332), [Android](https://www.lifewire.com/add-emojis-to-android-4149696))  For any other questions, please use our StackOverflow thread [here](https://www.lifewire.com/add-emojis-to-android-4149696).

**Comment by yogapriyaK** [comment]
Thank you
