### ISSUE TITLE
Scrollview Bug iOS. Layout Background merge

### ISSUE THREAD

**Issue by mrblade** [NativeScript/NativeScript#6615]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: none. using  playground
 - Cross-platform modules:
 - Android Runtime: 5.0.0
 - iOS Runtime:  5.0.0
-  iOS - 12.1.0 , Android - 7.0.0
-- | --

 - Plugin(s): none

**Describe the bug**
When a backgroundColor is applied to a layout(child layout) inside scrollview layout (parent), then if the child layout containing the background gets cut off at the edge(because of no more visible screen), it will merge with the next child Layout say another FlexBox. I applied margins & padding on the right to prevent it, but it doesn't take its values.

**To Reproduce**
Add a ScrollView Layout (horizontal) and let's call it as a Parent Layout. Add multiple flexbox layouts inside it. Add a background color to each of these Flex layout & add some margins on the right to separate these.  The last Flex Layout which is visible on the screen and is being cut off slightly will merge with the next Flex Layout(the one which will be visible when scrolled in). It's right margins don't work!

P.S It's not just FlexBox Layout, I've tried all the layouts inside the scrollview. Whenever I apply a background to child layouts and add margins to separate them, the element which is being cut off gets merged into the next one.

This happens only on iOS, Android works pretty fine.
I want to add padding or margins between these layouts to mimic a Google Material Card.

**Expected behavior**
Margins to work fine and all the layouts to get equal distance between them.

**Sample project**

https://play.nativescript.org/?template=play-js&id=tkeetd

**Additional context**
![img_2413](https://user-images.githubusercontent.com/9509855/49003664-68268000-f188-11e8-9c2d-71818263c331.PNG)

**Comment by tsonevn** [comment]
Hi @mrblade,
The issue, you are facing is fixed with the latest tns-core-modules version 5.0.5. You can update the modules using the below-attached steps:
1.  run `tns update`
2. delete `platforms` folder
3. rebuild the project again with `tns run ios`
