### ISSUE TITLE
Add IOS App store link to my app

### ISSUE THREAD

**Issue by janossuta** [NativeScript/NativeScript#6625]
Hi,

Is there a way to add a link to my app in App store?

I have created an about page and I would like to add a rate us button or link which is opens up the App store page (app store application) of my app.

**Comment by NickIliev** [comment]
@janossuta try the [nativescript-ratings ](https://www.npmjs.com/package/nativescript-ratings) plugin por directly use[ the iOS-related logic](https://github.com/nraboy/nativescript-ratings/blob/master/ratings.ts#L58-L61)
