### ISSUE TITLE
NativeScript angular navigation not working

### ISSUE THREAD

**Issue by agnoam** [NativeScript/NativeScript#6632]
Hi,
I have problem on navigation with my app.
I'm using the RouterExtensions class in the ngOnInit callback.

This line of code is the navigation, in the logs the router write the new route like it moved but in the UI not moved.

`this.ngZone.run(() => this.routerExtention.navigate(['upload'], additionalData))`

**Comment by NickIliev** [comment]
@agnoam is there are a reason to use `NgZone` ? The Angular navigation should work as expected so please consider posting a Playground demo that reproduces the issue. You can also enable the route tracing with `{ enableTracing : true }` and investigate your local setup (the option should be passed in `forRoot` method of `NativeScriptRouterModule`).

C

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-angular #1636](https://github.com/NativeScript/nativescript-angular/issues/1636) via [**ZenHub**](https://www.zenhub.com/)
