### ISSUE TITLE
Node packages without an index.js or <name>.js don't seem to load

### ISSUE THREAD

**Issue by maknz** [NativeScript/NativeScript#664]
Consider the `parse-link-header` npm package. It depends on `xtend`.

Most other NPM packages seem to work fine, such as `accounting` and `moment`, which seem to have files named either `index.js` or `packagename.js`. In the case of `xtend`, there is an `immutable.js` and `mutable.js`. The `package.json` identifies `immutable.js` as the main file.

To reproduce, try and install `parse-link-header` (along with `url` and `querystring` which are polyfills/ports of the built-in Node packages of the same name, which `parse-link-header` uses) and you will see that when requiring it, an error is thrown saying the `xtend` module is not found, despite it being in the `tns_modules` in the Android platform.

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#210
