### ISSUE TITLE
exiting tab item fragment disappears on navigating away from tab page

### ISSUE THREAD

**Issue by manoldonev** [NativeScript/NativeScript#6641]
**Environment**
 - CLI: 5.0.2
 - Cross-platform modules: 5.0.5
 - Android Runtime: 5.0.0

**Describe the bug**
Exiting tab item fragment disappears instead of executing exit transition while navigating from page containing tabview to a different page. Going back to the tab page works as expected -- tab item fragment executes its enter transition properly. The type of the navigation transition does not matter (slide, fade, flip)

**To Reproduce**
1. Tap "navigate to some page" -- notice how the "tab" part of the page disappears immediately instead of transitioning away

**Expected behavior**
"Tab" part of the page should transition away properly.

**Sample project**
https://play.nativescript.org/?template=play-tsc&id=BZfk8A&v=4 NOTE: use playground source files just for reference! (playground not updated to latest binares yet)

Use the attached zip to debug: [NSPlayground.zip](https://github.com/NativeScript/NativeScript/files/2634299/NSPlayground.zip)

**Comment by manoldonev** [comment]
Seems this is a known issue with nested fragments and support library apis: https://issuetracker.google.com/issues/36970570. Marked as won't fix, will try to work around it somehow.

**Comment by SkupeZZ** [comment]
Let us know if you find a work around in the meantime.
