### ISSUE TITLE
Broken Bluetooth API for Eddystone advertisement frames

### ISSUE THREAD

**Issue by allnash** [NativeScript/NativeScript#6642]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:   latest
 - Cross-platform modules:
 - Android Runtime: NA
 - iOS Runtime: 9.0 and above
 - Plugin(s): NA

**Describe the bug**
The following API is not providing data for Eddystone beacons:
 ```CBCentralManagerDelegateImpl.prototype.centralManagerDidDiscoverPeripheralAdvertisementDataRSSI = function (central, peripheral, advData, RSSI) { }```

**To Reproduce**
Eddystone beacon using a g Google beacon App.

**Expected behavior**
Should return `AdvData` in hex that can be used to figure out TLM/EID/URL type and its frame content.

**Comment by allnash** [comment]
I am on the latest version: Here is my package.json

```
  "@angular/animations": "~7.0.0",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "nativescript-angular": "~7.0.0",
    "nativescript-permissions": "^1.2.3",
    "nativescript-secure-storage": "^2.3.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-listview": "^5.0.0",
    "nativescript-ui-sidedrawer": "~5.0.0",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.3.0",
    "tns-core-modules": "~5.0.2",
    "tns-platform-declarations": "^5.0.5",
    "zone.js": "~0.8.18"
```

**Comment by tsonevn** [comment]
Hi @allnash,
I have checked the provided  package.json, however, the `nativescript-bluetooth` is missing from the dependencies list, and it is not clear which version of the plugin you are using. Regarding that, I would suggest checking if you are using the latest version` 1.3.1` and verify if you will be able to recreate the issue. 

Also if you are facing an issue with the Bluetooth plugin, please log a new issue in its repository [here](https://github.com/eddyverbruggen/nativescript-bluetooth/issues).
