### ISSUE TITLE
SSLsocket implementation in API >20 [android]

### ISSUE THREAD

**Issue by Momazo7u7** [NativeScript/NativeScript#6643]
In api <20 the fetch, and the https module, are still using  TLS v1 for SSL verification.

With that option , some websites that doesn't support TLS 1 or TLS 1.1 are throwing an SSL handshake exception.

Please Make the fetch and https module to use TLS1.2 by default 
according to https://developer.android.com/reference/javax/net/ssl/SSLSocket , since api 16 the TLS 1.2 protocol is available but it´s used by default on API >=20.

**Comment by NickIliev** [comment]
@Momazo7u7 based on the information [here](https://en.wikipedia.org/wiki/Transport_Layer_Security#Web_browsers) the TLS 1.2 is disabled by default on devices with Android 4.4 (API 19). and is not supported on lower API levels. That said some device manufacturers have enabled the TLS 1.2 on these lower API levels but not all of them.

There is a solution for enabling TLS 1.2 (only for devices with Google Play services).
Place the below code in the bootstaoping files - `main.ts` (Angular base aapp) or in `app.ts` (plain JS or TypeScript app)
```TypeScript
  androidApp.on(AndroidApplication.activityCreatedEvent, (args: AndroidActivityBundleEventData) => {
    
    com.google.android.gms.security.ProviderInstaller.installIfNeededAsync(
      context,
      new com.google.android.gms.security.ProviderInstaller.ProviderInstallListener(
        {
          onProviderInstalled: () => {
            console.log("Provider Installed!");
          },
          onProviderInstallFailed: (errorCode, intent) => {
            console.log("Error: " + errorCode);
          }
        }
      )
    );
  });
```

For example as done [here](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/main.ts#L28-L41).
The above will update the security protocols to latest version on the device (still it would require the device to have Google Play) - more details [here](https://medium.com/tech-quizlet/working-with-tls-1-2-on-android-4-4-and-lower-f4f5205629a)
