### ISSUE TITLE
Label is not catching all tap events.

### ISSUE THREAD

**Issue by xpete** [NativeScript/NativeScript#6644]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.2
 - Cross-platform modules: 5.0.5
 - Android Runtime: 5.0.0
 - iOS Runtime: NA
 - Plugin(s): NA

**Describe the bug**
A label is not catching all the tap events when a project is run with "tns run android"

**To Reproduce**
This examples writes TAP on the console everytime i tap with my finger on Label1 when I run it from the Playground or with the command "tns preview" but if I run it with "tns run android" the "TAP" is only written sometimes. Looks random.

**Expected behavior**
Writes TAP on the console every time i tap with my finger on Label1.

**Sample project**
https://play.nativescript.org/?template=play-js&id=bfMBFD&v=2

**Comment by manoldonev** [comment]
@xpete generally under-the-hood the Android widgets for most NativeScript views (except for Button) use OnTouchListener to detect user input while Button uses onClickListener.

You can find more information on the differences between OnTouch and OnClick in Android [here](https://stackoverflow.com/questions/9122679/difference-between-ontouch-and-onclick-android) but to summarize:

- OnTouchListener is used when you want to receive "motion events".
- OnClickListener is used when you want to detect clicks.

I would assume the behavior you are describing is the result of the Label (that is an Android TextView widget) detecting some of the quick taps as a motion gesture and that might look like skipping some of the taps.

If you would like to achieve the simple "click" behavior of a button, I would suggest you to use a NativeScript Button component and style it to look like a label.

As for the different behavior with Playgroung and tns run/preview commands -- this shouldn't be the case and I cannot reproduce this locally.

**Comment by xpete** [comment]
Nevermind. It was a USB cable problem. I was about to close this anyway.
