### ISSUE TITLE
this.super undefined in extended class instance

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#6647]
In this  [example](https://play.nativescript.org/?template=play-tsc&id=MReETr&v=10) I created a class animal and an extended class horse. In  horse I want to invoke a method of animal with this.super.head(). I get an error that  this.super is undefined. Is this a bug ? How can I deliberately invoke a method or property of a parent class (and bypassing the method with the same name in the child class)?

**Comment by NickIliev** [comment]
@jokro use the modified example (and the provided TSC documentation). Btw you are wrapping a method that calls `console.log` inside a `console.log` which would also cause troubles...

[https://play.nativescript.org/?template=play-tsc&id=MReETr&v=12](https://play.nativescript.org/?template=play-tsc&id=MReETr&v=12)

**Comment by jokro** [comment]
Hi, Nickliev,
Your solution does not handle my problem as this.head does not override the property with the same name as super does. In my example, using super in stead of this.super raised the error error `TS2340: Only public and protected methods of the base class are accessible via the 'super' keyword.` This is why I googled the internet and found this.super (see below).

After your reaction I solved my problem in [this modified example ](https://play.nativescript.org/?template=play-tsc&id=MReETr&v=15) by replacing head=function(){..} by head(){...}. I hope my reaction may help others.

By the way, I came to this.super in stead of super after  reading [this documentation](https://docs.nativescript.org/core-concepts/android-runtime/binding-generator/extend-class-interface). In the second inset it is written `this.super.setEnabled(enabled);`, not just super. I assume this a mistake in the documentation? 

Thx again for your help.

**Comment by NickIliev** [comment]
@jokro it is not a mistake in the docs:  in your case you are extending TypeScript Class and the TypeScript rules apply. In the documentation the example demonstrates how to extend a native Android class (Java) via the TypeScript syntax and here some special rules applies. 

Notice the following note in [the docs article](https://docs.nativescript.org/core-concepts/android-runtime/binding-generator/extend-class-interface#classes):

> Note: In the above setEnabled function the this keyword points to the JavaScript object that proxies the extended native instance. The this.super property provides access to the base class method implementation.


[Playground](https://play.nativescript.org/?template=play-tsc&id=MReETr&v=17)


**_Side note:_** However the example with `setEnabled` is having a minor mislead. As the native android.widget.Buttoin has a constructor that needs a mandatory parameter (context) the example needs a little modification to work.
```
class MyButton extends android.widget.Button {
    static constructorCalled: boolean = false;
    // constructor
    constructor(context: any) {
        super(context); // passing context from the super class
        MyButton.constructorCalled = true;

        // necessary when extending TypeScript constructors
        return global.__native(this);
    }

    setEnabled(enabled: boolean): void {
        this.super.setEnabled(enabled);
    }
}

let context = {}; // test only - this should be Android context
let btn = new MyButton(context);
```
