### ISSUE TITLE
Livesync process takes high cpu

### ISSUE THREAD

**Issue by agnoam** [NativeScript/NativeScript#6657]
Hello, 
I run the `tns run android` on my Windows 10 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz machine.

Why NativeScript livesync is very cpu wasteful. There is any way to decrease its  process, Because for comparison Flutter livesync work batter and not stuck my pc.

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #4199](https://github.com/NativeScript/nativescript-cli/issues/4199) via [**ZenHub**](https://www.zenhub.com/)
