### ISSUE TITLE
Images in ActionBar are oversized

### ISSUE THREAD

**Issue by mrmowji** [NativeScript/NativeScript#6663]
**Environment**
 - CLI: 5.0.1
 - Cross-platform modules: 5.0.3
 - Android Runtime: 5.0.0
 - iOS Runtime: 5.0.0
 - Plugin(s): -
 - OS: Windows 7 x64

**Describe the bug**
Images in ActionBar are oversized.

**To Reproduce**
I used the following example from [ActionBar's Custom Title View](https://docs.nativescript.org/ui/ns-ui-widgets/action-bar#custom-title-view):
```xml
<Page.actionBar>
    <ActionBar title="test">
        <StackLayout orientation="horizontal"
            ios:horizontalAlignment="center"
            android:horizontalAlignment="left">
            <Image src="res://icon" class="action-image"></Image>
            <Label text="ativeScript"  class="action-label"></Label>
        </StackLayout>
    </ActionBar>
</Page.actionBar>
```
![capture](https://user-images.githubusercontent.com/7012177/49477030-d1fdf400-f830-11e8-8bd4-8c30d19749ed.PNG)

There was a similar reported issue (#498) in which images are displayed downsized in devices with high DPI.

**Expected behavior**
That image should load with its natural dimensions, or dimensions forced by the native OS's ActionBar height.

**Comment by tsonevn** [comment]
Hi @mrmowji,
When you are using a custom view inside the ActionBar you should specify the width and height for the images. For example:
```
<StackLayout orientation="horizontal"
        ios:horizontalAlignment="center"
        android:horizontalAlignment="left">
        <Image width="90" height="90" src="res://icon" class="action-image"></Image>
        <Label text="ativeScript"  class="action-label"></Label>
    </StackLayout>
```
You can also check the example [here](https://docs.nativescript.org/ui/action-bar#using-a-custom-title-view) from NativeScript docs.

**Comment by mrmowji** [comment]
@tsonevn Thanks. I couldn't find [your link](https://docs.nativescript.org/ui/action-bar#using-a-custom-title-view) in the NativeScript-JS documentation. Are there 2 different pages for each UI Widget? From the left-side navigation menu, only [this link](https://docs.nativescript.org/ui/ns-ui-widgets/action-bar) is reachable for ActionBar.
