### ISSUE TITLE
debug is good but release release flash exit

### ISSUE THREAD

**Issue by ms-typescript** [NativeScript/NativeScript#6667]
**Environment**

 - Android Runtime:

**Describe the bug**
debug is ok
but when i build release, such as
tns build android --bundle --env.uglify --env.aot --env.snapshot --release --key-store-path /home/microsoft/nativescript/nativescript.keystore --key-store-password 123456 --key-store-alias nativescript --key-store-alias-password 123456

it is success and i get a release apk and install it successfully in my phone
flash exit

**Comment by ms-typescript** [comment]
The release version appears flashing back.

**Comment by tsonevn** [comment]
Hi @ms-typescript,
Can you provide some more info about the issue, you are facing? It will be great if you can give some more info about your environment(`CLI`, `tns-core-modules`, `tns-android` versions). It will also help if you send us a sample project, which can be used for debugging.

**Comment by ms-typescript** [comment]
I'm sorry, I'm not a native English speaker. I can only read English in general. My English grammar may be a little strange, please understand.

**Comment by dtopuzov** [comment]
Hi @ms-typescript,

As I understand your app crash on startup when it is build in release mode.

Following steps can help us to investigate the issue:
- Build your app and deploy it (do not start it)
- Run `$ANDROID_HOME/platform-tools/adb logcat -c` to clean old logs of your device
- Start your app
- Run `$ANDROID_HOME/platform-tools/adb logcat` to get crash logs and attache them to this issue.

**Comment by ms-typescript** [comment]
Thank you @dtopuzov for your free help and advice.

I will reconfigure the environment on the new laptop. According to your suggestion, I will try again. If it succeeds, I'll let you tell you. If it fails, I will submit a new error message.

**Comment by ms-typescript** [comment]
If it succeeds, I'll tell you. If it fails, I will submit a new error message.
