### ISSUE TITLE
Live reload extremely slow

### ISSUE THREAD

**Issue by amobarak** [NativeScript/NativeScript#6670]
My live reload is extremely slow and glitchy after running the following project:
https://github.com/telerik/nativescript-ui-samples-angular/tree/master/listview

Please help me out.

**Comment by tsonevn** [comment]
Hi @amobarak,
Try to clear up your project while deleting the `platforms`, `node_modules`, `hooks` folders and  `package-lock.json` file, restart the console and the simulator that you are using. Then rebuild the project - `tns run <platform name>`. 
You can also try using our new option hot module reload (`--hmr`). You can find more info [here](https://www.nativescript.org/blog/nativescript-hot-module-replacement). Keep in mind that this feature is still in beta.
