### ISSUE TITLE
tns devices doesn't list all connected devices if 2 devices and simulator are connected at the same time

### ISSUE THREAD

**Issue by Natalia-Hristova** [NativeScript/NativeScript#6672]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.0-2018-12-05-12712

**Describe the bug**
If you connect 2 devices and run `tns devices` - cli shows both of them listed. If you run one simulator and run again the same command - cli shows 1 device and 1 simulator instead of 2 devices and 1 simulator

**To Reproduce**
1. Connect 2 devices and 1 simulator
2. Run `tns devices`

**Expected behavior**
to be listed 2 devices and 1 simulator

**Sample project**

**Additional context**

**Comment by Fatme** [comment]
This issue was moved to NativeScript/nativescript-cli#4208
