### ISSUE TITLE
JS string to native String has wrong data 

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/NativeScript#6673]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.1-2018-11-08-12560
 - Cross-platform modules: None
 - Android Runtime: 5.0.0
 - iOS Runtime: 5.0.0
 - Plugin(s): None

**Describe the bug**
Trying to encode a JS string into a native one will get wrong data if JS string has utf8 characters like 'µ' 

This is mostly not shown by users as it is only happening when trying to transform JS string to native NSData or Android byte[].
I do see this issue while using my fork of the bluetooth module. I was trying to send JS strings with a 
'µ'  char and we were seeing wrong chars when using code from testEncoding1. I had to switch to the method used in testEncoding2.

I would really much prefer the method from testEncoding1 as it is completely native and thus faster.

**To Reproduce**
run the provided sample code.
Either look at the console of the UI

**Expected behavior**
So i implemented to 2 methods testEncoding1 and testEncoding2

testEncoding1 will show wrong native data length (1 byte is added) . The resulting encoded string is shown.

testEncoding2 will have good native data length.

**Sample project**
[NSPlayground 2.zip](https://github.com/NativeScript/NativeScript/files/2652631/NSPlayground.2.zip)

**Comment by NickIliev** [comment]
@farfromrefug as a disclosure I don't really have good knowledge about encoding formats but what I've noticed while playing with your code is that if I change the encoding from `UTF-8` to `ISO-8859-1` the data lenght is as expected (and so is the output)

```TypeScript
const result = new java.lang.String(str).getBytes("ISO-8859-1"); // here
const stringBack = new java.lang.String(result, "ISO-8859-1"); // here
const buffer = this.byteArrayToBuffer(result);
const bufView = new Uint8Array(buffer);
const encodedString = String.fromCharCode.apply(null, bufView);
this.testEncoding1Result = {
  nativeData: result,
  nativeDataLength: result.length,
  buffer: buffer,
  stringBack: stringBack,
  encodedString: encodedString,
  base64: java.util.Base64.getEncoder().encodeToString(result)
};
console.log(`testEncoding1 result:${JSON.stringify(this.testEncoding1Result)}`);
```

returns
```
JS: testEncoding1 result:{"nativeData":{"length":5},"nativeDataLength":5,"buffer":{},"stringBack":{},"encodedString":"testµ","base64":"dGVzdLU="}
```

**Comment by farfromrefug** [comment]
@NickIliev You saved my day. The isssue is indeed with the encoding. Thanks to your remark i ended up [here](https://stackoverflow.com/questions/7048745/what-is-the-difference-between-utf-8-and-iso-8859-1) which explains that with UTF-8  "code points 128 - 255 differ by becoming 2-byte sequence"!!!! And thus the length difference. 
I guess the nativescript-bluetooth module will need an encoding option while sending strings.

Thank you so much and sorry for taking some of your time (though you saved mine).
