### ISSUE TITLE
Failed HTTP connections resolve the promise instead of rejecting it

### ISSUE THREAD

**Issue by lsapan** [NativeScript/NativeScript#6678]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: Playground
 - Cross-platform modules: N/A
 - Android Runtime: 5.0.0
 - iOS Runtime: 5.0.0
 - Plugin(s): None (other than axios)

**Describe the bug**
It appears that if a request fails to connect to the server (or doesn't get a status code), it resolves the promise instead of rejecting it.

**To Reproduce**
I've created a minimal repro in the playground using the icanhazdadjoke API. Tap "The Button" to load a dad joke. You'll see that the message changes to "We loaded it!", the status code is 200, and the data gets filled in with the joke.

Now, put your phone into airplane mode and tap The Button again. Despite not having a connection, it calls the success handler again, so the message still becomes "We loaded it!". As you can see though, the status code is `null` and the data is empty.

**Expected behavior**
The failure handler should be called, displaying "Hmm, looks like it didn't load." on the screen instead.

**Sample project**
https://play.nativescript.org/?template=play-vue&id=cShoHR&v=2

**Additional context**
The sample project uses axios as that's how I uncovered the issue, but there must be some underlying issue with the way NS is handling these requests that's causing axios to treat it as a successful request.

**Comment by tsonevn** [comment]
Hi @lsapan,
The issue with the HTTP request seems to be related to the `axios` plugin that you are using. I have tested the same scenario with the [HTTP module](https://docs.nativescript.org/ns-framework-modules/http#post) provided by tns-core-modules and this scenario with `no network ` is appropriately handled. For your convenience, I am attaching a sample project. 
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2656324/Archive.zip)

I would suggest using the **module** provided by `tns-core-modules` in the project.
