### ISSUE TITLE
Add support for UITextContentTypeOneTimeCode

### ISSUE THREAD

**Issue by iwanbolzern** [NativeScript/NativeScript#6686]
I would like to use the OneTimeCode feature on ios plattform. 

https://developer.apple.com/documentation/uikit/uitextcontenttype/2980930-onetimecode

Possible solution:
```
function tfloaded(args) {
    var field:TextField = <TextField>args.object;   
    console.log("----------UITextContentTypeOneTimeCode-----------");
    console.log(UITextContentTypeOneTimeCode);
    field.ios.textContentType = UITextContentTypeOneTimeCode;
    console.log("----------textContentType-----------");
    console.log(field.ios.textContentType);
}
```

**Comment by eusend** [comment]
Hello, is there any update on this? My team wants to use this in production.

**Comment by tsonevn** [comment]
Hi @eusend,
This feature request is still under review. Currently, I can not commit to the exact time when it will be available. Have you tried the solution provided in the[ initial comment](https://github.com/NativeScript/NativeScript/issues/6686#issue-389024709)?

**Comment by NickIliev** [comment]
@iwanbolzern as there is no similar counter property on Android it would be hard to create a cross-platform property SO it would make sense that anyone that needs that iOS specific property could implement it by using the native API (as shown in [your solution](https://github.com/NativeScript/NativeScript/issues/6686#issue-389024709)).

Closing this feature request for the reasons above but if anyone is interested in creating an implementation - all PRs are welcomed!
