### ISSUE TITLE
NativeScript tns run android throw ENOSPC error

### ISSUE THREAD

**Issue by AbdullatifJamous891** [NativeScript/NativeScript#6688]
**Environment**
this is my environment information
 ✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.0.3 version and is up to date.
✔ Component tns-core-modules has 5.0.5 version and is up to date.
✔ Component tns-android has 5.0.0 version and is up to date.
✔ Component tns-ios has 5.0.0 version and is up to date.

**Describe the bug**
I am trying to run  a simple nativeScript app by this comman ( tns run android ) and I got this error  

`Error: watch /home/abdullatif/Documents/projects/nativescript/native/app ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/usr/local/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:37:15)`

I installed Genymotion, it has worked successfully at the first time but after that it did not work, I have not change any thing in my code or my setting

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #4212](https://github.com/NativeScript/nativescript-cli/issues/4212) via [**ZenHub**](https://www.zenhub.com/)
