### ISSUE TITLE
Add support for the UI for NativeScript markup in iOS today widgets

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#669]
[Here is a getting started article, for what is implemented in the ios-runtime.](https://github.com/NativeScript/ios-runtime-docs/blob/d548447067a87ba7ed9af0b91bd8dc2ee1f486bb/extensions/TodayExtension.md)

We have to implement an abstraction that will provide UIViewController principal class in the today extension and will allow our XML to be used to create the TodayWidget UI,

We should also research what is the state in android.

**Comment by adrian-niculescu** [comment]
> Is there a working link to this article?
https://www.nativescript.org/blog/making-a-today-widget-in-ios-with-nativescript-and-ui-for-nativescript
