### ISSUE TITLE
Quick question regarding release 5.1

### ISSUE THREAD

**Issue by larssn** [NativeScript/NativeScript#6697]
So this release has been out for about 6 days here on Github, but it's not been added to the NPM repo yet. Is this an oversight?

**Comment by NickIliev** [comment]
@larssn  currently we have release a RC (release candidate) with the **rc** tag. 
You can try the RC CLI with
```
npm i -g nativescript@rc
```

or you can try the RC modules with
```
npm i -g tns-core-modules@rc --save
```

Or the RC runtimes
```
tns platform add android@rc
```

The official release will go live in a matter of days (as planned mid-December)

**Comment by larssn** [comment]
Alright, but it's a bit confusing that it's not flagged as RC, when all the other releases in the list is actual releases. :-)
