### ISSUE TITLE
Map Component

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#67]
_From @ligaz on March 14, 2015 21:19_

...

_Copied from original issue: NativeScript/cross-platform-modules#177_

**Comment by N3ll** [comment]
You can vote on our voting site https://nativescript.ideas.aha.io/ideas/NS-I-65.

**Comment by N3ll** [comment]
The issue is closed in favor of https://github.com/NativeScript/NativeScript/issues/769.
