### ISSUE TITLE
Add a cross platform "openUrl"

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#670]
Something that wraps:
iOS:
```
var url = NSURL.URLWithString("http://www.facebook.com");  
UIApplication.sharedApplication().openURL(url);
```
Android:
``` JavaScript
var application = require("application");
var Intent = android.content.Intent;

var context = application.android.context;
var browserIntent = new Intent(Intent.ACTION_VIEW, Uri.parse("http://www.google.com"));
context.startActivity(browserIntent);
```

**Comment by NathanaelA** [comment]
I created a plugin for this...     **tns plugin add nativescript-openurl** will get you it.

If the NativeScript team does want to add it internally to NativeScript, I would recommend you just copy my plugins code; as it covers a couple corner cases your above code didn't and which will cause crashes.

**Comment by sitefinitysteve** [comment]
Thanks Nathanael, works awesome :)

**Comment by emiloberg** [comment]
![You're awesome](http://media.giphy.com/media/vCKC987OpQAco/giphy.gif)

**Comment by sitefinitysteve** [comment]
@NathanaelA Just encountered this...would be handy to throw in a .trim() or something internally.  A space will cause it to crash.

**Comment by NathanaelA** [comment]
@sitefinitysteve -- I just pushed a v1.01 which has a trim in it, and put the try/catch around everything as when I wrote it yesterday, I didn't expect you to be able to crash the routine in the url parsing.  ;-)

**Comment by sitefinitysteve** [comment]
@NathanaelA ...as I was not expecting an admin to preceed the Url with a space :) "<space>http://..."

**Comment by sitefinitysteve** [comment]
@enchev ...this merging into core at all?

**Comment by enchev** [comment]
Well, we don't mind to merge it, @NathanaelA what do you think? Should people use your plugin or this can be part of our master?

**Comment by ligaz** [comment]
IMO it should be part of the core (until we split it) ;).

**Comment by NathanaelA** [comment]
@enchev -- I am perfectly happy donating it to core.  Would you like a pull request or do you want to task one of your engineers to add the module to where you want it?

**Comment by NathanaelA** [comment]
I added some notes to the 700 patch.  I had to work around several issues; so you might want to grab my code...  :grinning:

**Comment by enchev** [comment]
Thanks @NathanaelA!

We've lost too much time on this, maybe next time we should proceed with a pull request directly! :)

Thanks again!
