### ISSUE TITLE
How to display font awesome 5 icons in the tabview 

### ISSUE THREAD

**Issue by alexisconsuegra** [NativeScript/NativeScript#6701]
I just started trying to use Font Awesome 5. I can use it in labels and buttons but not quite yet in the TabViewItem. Basically placing the unicode value on the title property displays the icon but it is too small. I have not figured out how to use the font-size property to display the correct size. Also I lost the ability to display a text underneath the icon. I tried using labels but it is not working. 
  <TabView androidTabsPosition="bottom" class="far">
   <TabViewItem title="&#xf002;">
      <Frame defaultPage="search/search-page"></Frame>
    </TabViewItem>
  </TabView>
</Page>

**Comment by tsonevn** [comment]
Hi @alexisconsuegra,
Make sure that you are specifying the correct font name. I have tested `Font Awesome`, and the icons have been appropriately applied. Check out the attached project.
For further questions, please use our StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript). This repository is used for bug reporting and feature requests.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2674715/Archive.zip)

**Comment by felix-idf** [comment]
When using FontAwesome within the TabViewItem, the font is also applied for all the contents within the tab. Actually I only want to use FontAwesome for the Tab-title.

**Comment by princy05** [comment]
@LiteKat : The hack you mentioned is working for android. But for iOS, only the font awesome icons are shown without text underneath
