### ISSUE TITLE
Crash on navigate on app resume: The specified child already has a parent

### ISSUE THREAD

**Issue by manoldonev** [NativeScript/NativeScript#6708]
**Environment**
 - CLI: 5.1.0
 - Cross-platform modules: 5.1.0
 - Android Runtime: 5.1.0

**Describe the bug**
Navigating to a page when app resumes from background causes the app to crash with the following exception:
```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to resume activity {org.nativescript.bl32/com.tns.NativeScriptActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**To Reproduce**
1. Create app from blank template
2. Add new Page second-page.xml
3. Add the following application.resumeEvent handler to app.ts:
``` ts
import * as application from "tns-core-modules/application";
import { topmost } from "tns-core-modules/ui/frame";

application.on(application.resumeEvent, (context) => {
    topmost().navigate("home/second-page");
});

application.run({ moduleName: "app-root" });
```
4. Start app
5. Suspend app
6. Resume app -- app crashes

Originally reported by @nudiref here: https://github.com/NativeScript/NativeScript/issues/6201

**Comment by manoldonev** [comment]
@nudiref as a workaround you can wrap the `navigate` action inside a setTimeout(...) call with 0ms delay and that should allow you to achieve the desired effect:
Instead of:
``` ts
application.on(application.resumeEvent, (context) => {
    topmost().navigate("home/second-page");
});
```

Use:
``` ts
application.on(application.resumeEvent, (context) => {
    setTimeout(() => topmost().navigate("home/second-page"), 0);
});
```

**Comment by manoldonev** [comment]
> when I navigate from login to home page, navigates back to login and then open another app. 

Usually when navigating from login screen you would set `clearHistory` to true as user should not be able to return to login screen unless he/she decides to log out?

Find attached a modified version of the [drawer navigation template](https://github.com/NativeScript/template-drawer-navigation-ts) that implements such login/logout functionality with observable `defaultPage` property binding.

[bl33.zip](https://github.com/NativeScript/NativeScript/files/2686130/bl33.zip)

**Comment by nudiref** [comment]
> 
> 
> @nudiref as a workaround you can wrap the `navigate` action inside a setTimeout(...) call with 0ms delay and that should allow you to achieve the desired effect:
> Instead of:
> 
> ```ts
> application.on(application.resumeEvent, (context) => {
>     topmost().navigate("home/second-page");
> });
> ```
> 
> Use:
> 
> ```ts
> application.on(application.resumeEvent, (context) => {
>     setTimeout(() => topmost().navigate("home/second-page"), 0);
> });
> ```

thanks for the info and workaround Manol. i hope there will be a fix soon

**Comment by vosonha89** [comment]
> @nudiref as a workaround you can wrap the `navigate` action inside a setTimeout(...) call with 0ms delay and that should allow you to achieve the desired effect:
> Instead of:
> 
> ```ts
> application.on(application.resumeEvent, (context) => {
>     topmost().navigate("home/second-page");
> });
> ```
> 
> Use:
> 
> ```ts
> application.on(application.resumeEvent, (context) => {
>     setTimeout(() => topmost().navigate("home/second-page"), 0);
> });
> ```

It's work for me :). Thank you so much
