### ISSUE TITLE
WebView Lifecycle

### ISSUE THREAD

**Issue by Dennis-kw-yiu** [NativeScript/NativeScript#6711]
Hi all i am newbie to nativescript and webview.

Is there any documentation about the event sequence of the nativescript webview and its supported events?

Thanks all in advance

**Comment by tsonevn** [comment]
Hi @Dennis-kw-yiu,
The supported WebView's events are described [here](https://docs.nativescript.org/ui/ns-ui-widgets/web-view#events). In the article, you will find also an example of their usage.
