### ISSUE TITLE
Weird white bar on routerExtension.back() (slideTop transition)

### ISSUE THREAD

**Issue by bearinld004** [NativeScript/NativeScript#6713]
Coming in from #6565 late replying the issue. I downloaded the archive zip and run it on iphone 6 plus runing ios 10 without modifing the project i see the bug see : https://www.youtube.com/watch?v=XMDsXAaXA7E 

Thanks

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-angular #1663](https://github.com/NativeScript/nativescript-angular/issues/1663) via [**ZenHub**](https://www.zenhub.com/)
