### ISSUE TITLE
Wrong behaviour on back default tab template 

### ISSUE THREAD

**Issue by gianemi2** [NativeScript/NativeScript#6714]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

- Getting NativeScript components versions information...
- Component nativescript has 5.1.0 version and is up to date.
- Component tns-core-modules has 5.1.0 version and is up to date.
- Component tns-android has 5.1.0 version and is up to date.
- Component tns-ios has 5.1.0 version and is up to date.

**Describe the bug**
The bug happens instantly after back navigation on item. 
I'm using default app template **tab view Angular**.

After open an item in a items list, pressing back icon bring back to home page but:

- just after land to homepage another homepage slide from right, as another item as been clicked.
- The new homepage has a back button on ActionBar
- Click back again brings finally to homepage but clicking an item will not work no more.

[Check this video for better explanation.](https://www.dropbox.com/s/4a420cm63h2hmxw/ScreenRecording_12-16-2018%2013-28-52.MP4?dl=0)

**To Reproduce**
Simply create the tabView sample project using [nativescript website](https://market.nativescript.org/plugins/tns-template-tab-navigation-ng) or using [github repo.](https://github.com/NativeScript/template-tab-navigation-ng).

Tap on a list item and go back.

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-angular #1666](https://github.com/NativeScript/nativescript-angular/issues/1666) via [**ZenHub**](https://www.zenhub.com/)
