### ISSUE TITLE
iOS: itemTap not being called when listening to parent tap

### ISSUE THREAD

**Issue by MukaSchultze** [NativeScript/NativeScript#6718]
**Environment**

 - CLI: 5.0.1
 - Cross-platform modules: 5.0.5
 - Android Runtime: Not relevant
 - iOS Runtime: 5.0.0
 - Plugin(s): Not relevant

**Describe the bug**

ListView's `itemTap` events not fired when listening to its parent `tap`

**To Reproduce**

Place a `ListView` inside a `StackLayout`, then listen to the StackLayout's `tap` and ListView's `itemTap`, the function binded to the `itemTap` won't be called.

In the example below, `taphandle()` is never called unless you remove the `(tap)="parentTap()"`
```html
    <StackLayout class="page home-panel" (tap)="parentTap()">
        <Label text="OUTSIDE" padding="30"></Label>
        <ListView (itemTap)="taphandle()" height="300" items="['a','b','c']">
            <ng-template let-item="item">
                <StackLayout>
                    <Label text="CLICK ME" padding="30"></Label>
                </StackLayout>
            </ng-template>
        </ListView> 
    </StackLayout>
```

**Expected behavior**

The `tap` event should no swallow the `itemTap` event.

**Sample project**

https://play.nativescript.org/?template=play-ng&id=Lrwg8A&v=4

**Comment by tsonevn** [comment]
Hi @MukaSchultze,
Similar case has been discussed in the issue https://github.com/NativeScript/NativeScript/issues/6376
