### ISSUE TITLE
Faint outline around image with border radius applied

### ISSUE THREAD

**Issue by froggman2k** [NativeScript/NativeScript#6724]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.1
 - Cross-platform modules: None
 - Android Runtime: 5.0.0
 - iOS Runtime: 5.0.0
 - Plugin(s): None

**Describe the bug**
When a border radius is applied to an image, there is a very faint outline of a second border (for lack of a better word) outside of the border I actually want.

![image](https://user-images.githubusercontent.com/45978987/50178877-de6b5d80-02c2-11e9-9cc9-1c24bc9a576e.png)

**To Reproduce**
1. Add an image to your XML file, like this: <Image src="{{ base64EncodedImageSrc }}" class="border-def" />
2. In CSS, add a border definition like this:
.border-def {
    border-width: 2;
    border-color: #ffffff;
    border-radius: 45;
}
In my case, my border-radius is 45 because my image height and width are 90, so it's an effective border radius of 50%.

**Expected behavior**
There should be a border with a width of 2, in the color white, that effectively turns the image into a circle. There should NOT be any other borders.

**Sample project**
https://play.nativescript.org/?template=play-tsc&id=ZQUQtk&v=2

**Additional context**
None.

**Comment by tsonevn** [comment]
Hi @froggman2k,
I reviewed the provided [sample project](https://play.nativescript.org/?template=play-tsc&id=ZQUQtk&v=3), however, was unable to recreate the issue with the border.
For your convenience, I am attaching a screenshot with the result on my side for both platforms iOS and Android
![polarisopr1 170623 032ntsonev12192018074825](https://user-images.githubusercontent.com/17448734/50201385-90a63200-0362-11e9-8b84-16f873607ea1.png)

iOS
![img_6906](https://user-images.githubusercontent.com/17448734/50201421-b29fb480-0362-11e9-9d73-56bde049ad2b.PNG)
I would suggest checking if you have defined some global styling in your app that can affect the image border. I also notice that you are using an old NativeScript version. I would suggest upgrading to the latest one. Check out the [upgrade instructions](https://docs.nativescript.org/releases/upgrade-instructions).
