### ISSUE TITLE
ios property in WebView gives undefined

### ISSUE THREAD

**Issue by dotnetdreamer** [NativeScript/NativeScript#6725]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.0
 - Cross-platform modules: 5.1.0
 - Android Runtime: 5.1.0
 - iOS Runtime: 5.1.0

**Describe the bug**
I had a code before which worked fine:
```
this.webview=new WebView();
this.webview.src=this.webViewSrc;
constwkwebview:WKWebView=this.webview.ios;
// console.log('----------------------------');
console.log(typeof this.webview.ios);
```
Now in NS 5.1. This stopped working. The ios property is coming undefined. 

**Expected behavior**
Webview should have ios property.

**Comment by tsonevn** [comment]
Hi @dotnetdreamer,
It seems that you are trying to access the `ios` property too early. You can try accessing the native view on WebView loaded event. For example:
```
 wv.on(WebView.loadedEvent, ()=>{
        if(isIOS){
            console.log("navite view")
            console.log(wv.ios);
        }
    })
```
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2694844/Archive.zip)

**Comment by dotnetdreamer** [comment]
@tsonevn yes i need to configure the delegate before the webview is loaded. This code did work. Now it isn't. Check [this](https://play.nativescript.org/?template=play-ng&id=Dh4mYQ) playground:

**Comment by tsonevn** [comment]
HI @dotnetdreamer,
If you need to overwrite the ScrollView's delegate method, you need to do it on the ScrollView's loaded event. I am not sure why you need to access the WebView ios property earlier. It will help if you give us some more info, what you are trying to achieve a final result. I am also attaching a sample project, which demonstrates how to extend the WebView's delegate. The same way the ScrollView's delegate can be extended.

> Note: I am not sure in which NS version the ios property will return an instance of the native view immediately after creating the WeView. However, in case you need to access the native view and to be sure that it will not return an undefined value, you should access it in the loaded event.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/2697725/Archive.zip)

**Comment by dotnetdreamer** [comment]
Hi @tsonevn, I have a delegate which blocks the zoom in webview as shown below:
```
export class WkWebViewUIScrollViewDelegate extends NSObject implements UIScrollViewDelegate {
public static ObjCProtocols = [UIScrollViewDelegate];
static new(): WkWebViewUIScrollViewDelegate {
       return <WkWebViewUIScrollViewDelegate>super.new();
}
 
scrollViewWillBeginZoomingWithView(scrollView: UIScrollView, view: UIView) {
     scrollView.pinchGestureRecognizer.enabled = false;
}
}
```
and i am attaching this delegate like so:
```
        const webView = new WebView();
        webView.src = "https://www.google.com";
webview.ios.scrollView.delegate = this._wkWebViewUIScrollViewDelegate;
webview.ios.scrollView.minimumZoomScale = 1.0;
webview.ios.scrollView.maximumZoomScale = 1.0;
```
This way i was able to disable the zooming with fingers. Without delegate i couldn't. Now in NS 5 i added this code in ngOnInit it is no longer working. What is the better place now to put this code so it can work ?

**Comment by tsonevn** [comment]
Hi @dotnetdreamer,
I can still overwrite the UIScrollView delegate on WebView loaded event and to disable the zoom. Check out the attached project.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2702039/Archive.zip)

I the project, I am overwriting the WebView's and ScrollView's delegates

**Comment by NickIliev** [comment]
@dotnetdreamer with NativeScript 5.x.x the properties `nativeView`, `ops` and `android` were aligned to all work the same. As on Android a reference to native view can only be accessed after the view is actually rendered (it needs application `context` to be created in the first place) our devs aligned the `ios` property to be accessible only **after** the view has been loaded.

So to get the reference to the native property use the loaded event

e.g.
````TypeScript
const webView = new WebView();
webView.on("loaded", (args) => {
    let webVIew = args.object as WebView;

    let nativeView = webView.nativeView // or webView.ios if you prefer
})
```
