### ISSUE TITLE
Method called can't access variables outside of its scope

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/NativeScript#6733]
See this Playground example: https://play.nativescript.org/?template=play-tsc&id=jl6CgE&v=2

When binding a function to a tap event using the [method described in the docs](https://docs.nativescript.org/core-concepts/data-binding#binding-to-a-parent-binding-context), that method cannot seem to access any variables outside of itself.

Bug or am I missing something?

**Comment by tsonevn** [comment]
Hi @rdlauer,
This seems like an issue with the binding. I will mark this as a bug, and we will investigate the case further. Might be related to issue https://github.com/NativeScript/NativeScript/issues/5054. As a temporary solution, you can try getting the ListView's bindingContext as follows:
```
doSomething(args: EventData) {
        const tappedLabel = <Label>args.object;
        let id = parseInt(tappedLabel.parent.bindingContext.id);

        console.log(id); // this works fine of course
        console.log(tappedLabel.parent.parent.bindingContext.people); 
        console.log(tappedLabel.parent.parent.bindingContext.someInteger); 
    }
```

**Comment by webleaf** [comment]
In such case `this` refer to item `bindingContext`.
It confuse me too.

**Comment by tsonevn** [comment]
Hi all,
The case with the `this` seems to be expected JavaScript behaviour. In the way, you have defined the binding of the tap event inside the ListView item,  the scope of `this` in your` doSomething` method will return the binded data for your tapped list view cell. You can also check the similar discussion in [this GitHub issue](https://github.com/NativeScript/NativeScript/issues/3777#issuecomment-286062210).

Also, another way to solve your scenario is to define the callback method inside the view model as follows. In this case, `this` will point to the global binding context and can access all of its properties.
```
  doSomething = (args) => {
            const tappedLabel = <Label>args.object;

            console.log(this.people); 
            console.log(this.someInteger); 
    }
```
