### ISSUE TITLE
Header Entry not clickable in RadListView grouping function

### ISSUE THREAD

**Issue by NL33** [NativeScript/NativeScript#6734]
**Environment**

 - CLI: 5.0.1
 - Cross-platform modules: 5.0.1
 - Android Runtime: N/A
 - iOS Runtime: 5.0.0
 - Plugin(s):  nativescript-ui-listview (downloaded Dec 10, 2018)

**Describe the bug**
In a basic two-level list, where there are category headers and entries below, there is not a way to catch a click on the category header (at least in iOS). 

There should not be a place on the screen (especially in a basic+common UI like a list) where there is no way to watch (and isolate) a user click event.

For example, take a basic list of countries and cities as follows:
```
US
--New York
--Los Angeles
--Chicago

Canada
--Calgary
--Toronto

England
--London
```
The headers (the countries) should be clickable.

The common way to create such a list in Nativescript is using RadListView's grouping function, described [here](https://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/data-operations). However, the grouping function "hides" the group header from html, so there is not a clear way to attach a tap event to it.

Other methods would include to create a two level loop using *ngFor, but *ngFor is reportedly not stable for larger lists. Another method would be to have a two level (ie, nested) listview, but that is also reported to be unstable/non-performant.

**To Reproduce**

Simple code would be:

html:

```
<GridLayout>
    <RadListView [items]="places"  [groupingFunction]="myGroupingFunc" (tap)="groupTapped()">  
        <ng-template tkListItemTemplate let-place="item" >
            <StackLayout>
                <Label [text]="place.city"></Label>
              </StackLayout>
          </ng-template>
      </RadListView>
  </GridLayout>
```

ts:

```
public places = [
         {country: 'US', city: 'New York'}, 
         {country: 'US', city: 'Los Angeles' },     
         {country: 'Canada', city: 'Toronto'},
         {country: 'England', city: 'London'},
         {country: 'US', city: 'Chicago'},
         {country: 'Canada', city: 'Calgary'}      
 ]
...
myGroupingFunc(value) {
      return value.country;
 }

groupTapped(){
/*will fire whenever anywhere in group is tapped*/
}
```

The groupTapped() function here will register a tap on anywhere in the group--it will not tell you if the user has clicked on a category header.

**Expected behavior**

With a basic list, like as follows:
```
US
--New York
--Los Angeles
--Chicago

Canada
--Calgary
--Toronto

England
--London
```
There should be a way to register if the user taps on a category header (here, a country).

**Sample project**
N/A

**Additional context**
There are questions about this issue on stackoverflow [here](https://stackoverflow.com/questions/53885975/how-to-catch-click-on-category-header-with-radlistview-grouping-function-nativ) and [here](https://stackoverflow.com/questions/53731449/how-to-make-an-accordion-list-with-radlistview-nativescript).

There is also an issue on github [here](https://github.com/telerik/nativescript-ui-feedback/issues/965), as well as the NS slack channel. 

There are no answers provided to these, so I'm assuming that currently Nativescript does not provide a method for this basic operation (though I would still be happy if this is incorrect and there is a way, and maybe a pretty simple one!).

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#973
