### ISSUE TITLE
android webview issues

### ISSUE THREAD

**Issue by Dennis-kw-yiu** [NativeScript/NativeScript#6735]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 4.2.4

**Describe the bug**
I am having 2 webviews: one is having a link to other page; one is to open a pdf file.
I want all links in the webview to open in external browser so i add the loadstarted event in the webviews to check if open link and then  open the external browser.

However, there are problems in my 2 webviews:
1. the webview to open a link can open the external browser first time but cannot open in the second time after i am back to the app
2. the webview to open the pdf does not work

**Expected behavior**
the webview can open the external browser in all scenario

**Sample project**
https://play.nativescript.org/?template=play-ng&id=Qv1kri&v=22

**Comment by tsonevn** [comment]
Hi @Dennis-kw-yiu,
In your specific case, you can overwrite the Android WebView's `shouldOverrideUrlLoadings` listener. This will allow you to handle every link's tap in the view. When the listener mentioned above is triggered, you can load the URL in the device's browser via `openUrl` method provided by `utils` module. More info can be found in [this ](https://discourse.nativescript.org/t/how-to-make-links-in-a-webview-to-open-in-the-default-browser/945) forum thread. For your convenience, I am attaching a [link to a playground demo.](https://play.nativescript.org/?template=play-ng&id=Qv1kri&v=23)

**Comment by Dennis-kw-yiu** [comment]
Hi @tsonevn ,

Thank you for your reply. However, it seems that the URL in the method is not the link I am targeting because I have the following in the device logs in the playground

vg@a587a0b
Error: Error in OpenURL

Would you please advise if anything I am getting wrong? Thank you.

**Comment by Dennis-kw-yiu** [comment]
After a few trials, I found that the link should be url.getUrl().toString(), so I change all url to url.getUrl().toString() and seems everything well.

Thank you @tsonevn again.
