### ISSUE TITLE
{N} + Ng - class added in TS w/ className not affecting styling

### ISSUE THREAD

**Issue by jamessouth** [NativeScript/NativeScript#6737]
**Describe the bug**
adding a CSS class with className updates the list of classes on the element, but the styles are not changing 

**To Reproduce**
programmatically create an element in TS and apply a class with element.className = 'myClass'

**Expected behavior**
per the docs [here](https://docs.nativescript.org/angular/ui/styling#class-selector) you should be able to simply create an element and add a class to it with className

**Sample project**
[playground demo](https://play.nativescript.org/?template=play-ng&id=mmmJ5Q&v=13) 
the newly added class is logged to the console, but the styling of the text doesn't change

**Additional context**
i'm using the playground/preview apps on my android phone

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-angular #1670](https://github.com/NativeScript/nativescript-angular/issues/1670) via [**ZenHub**](https://www.zenhub.com/)
