### ISSUE TITLE
The ability to set `isUserInteractionEnabled` from css.

### ISSUE THREAD

**Issue by abozanona** [NativeScript/NativeScript#6738]
I have this page  

XML:

	<FlexboxLayout id="lytForgotPassword" tap="{{lytForgotPassword_click}}" justifyContent="center" class="bg-overlay not-children-user-interaction">
		<StackLayout id="ltyContainer" orientation="vertical">
			<StackLayout id="lytEmail" orientation="vertical">
				<Label text="Enter your email" />
				<DockLayout stretchLastChild="true">
					<Image dock="left" width="40" height="40" src="res://icon_btn_go" />
					<TextField id="txtEmail" dock="left" />
				</DockLayout>
			</StackLayout>
			
		</StackLayout>
	</FlexboxLayout>

JS: 

	lytForgotPassword_click:function(data){
		lytForgotPassword.visibility = 'collapse';
	},

CSS

	.bg-overlay{
	    background-color: rgba(0,0,0,0.5);
	    background-image: url("res://blur");
	    background-size: cover;
	    background-repeat: no-repeat;
	    height: 100%;
	}

The page looks like this:
![Image of Tmasraf](https://i.imgur.com/8boSsNL.png)

The gray layout is `lytForgotPassword` & the yellow layout is `lytEmail`.  
What I need is to hide `lytForgotPassword` when I tap on the gray area only.  
The problem is when I click on any layout inside `lytEmail` it triggers `lytForgotPassword` tap event.

I tried to use `isUserInteractionEnabled` on `ltyContainer`, `lytEmail` and all other layouts inside `lytForgotPassword` separately, but the yellow doesn't trigger the tap event of `lytForgotPassword` only if `isUserInteractionEnabled` value of all layouts inside `lytForgotPassword` is `true`.

**Describe the solution you'd like**
I suggest adding a css property for setting `isUserInteractionEnabled` from css, so I can have something like this in css.

    .not-children-user-interaction Label, .not-children-user-interaction StackLayout, .not-children-user-interaction DockLayout{
        user-interaction: false;
    }

**Describe alternatives you've considered**

I considered the solution in #3006 

	stop_prop:function(data){
		lytForgotPassword.off("tap");
		timerModule.setTimeout(() => {
			lytForgotPassword.on("tap", function(data){
				lytForgotPassword.visibility = 'collapse';
			});
		}, 500);
	}

    <StackLayout orientation="vertical" class="lyt-forget-password" tap="{{stop_prop}}">

**Comment by tsonevn** [comment]
Hi @abozanona,
To solve your scenario, I would also suggest setting up the isUserInteractionEnabled property recursively for all child components. This will disable the tap event for the StackLayout with id `lytEmail` and the nested elements. Check out the comment in [this](https://github.com/NativeScript/NativeScript/issues/3215#issuecomment-265691428) GitHub issue. 
Regarding the suggestion for a new CSS property, I will mark this as a feature request and will consider what the best way to provide similar functionality, which can be set up via CSS property is. You can keep track of the issue for further info.

**Comment by manoldonev** [comment]
You should be able to set `isUserInteractionEnabled` property via CSS like `is-user-interaction-enabled: false;`
