### ISSUE TITLE
[Suggestion] @keyframes CSS

### ISSUE THREAD

**Issue by Positivism** [NativeScript/NativeScript#6739]
```
@keyframes slideOutUp {
    0% {
      transform: translateY(0%);
    }
  
    100% {
      transform: translateY(-100%);
      visibility: collapse;
    }
}
```

Basic exit animations are impossible without css styling being available in the keyframes such as visibility.

**Comment by Positivism** [comment]
Just a note, opacity 0 will make the target element invisible, however, the space occupied remains leaving a blank area within the application.

**Comment by tsonevn** [comment]
Hi @Positivism,
You can try setting up the animation via code behind. For example:
```
view.animate({
    translate: { x: 0, y: 100},    
    duration: 1000,
    curve: enums.AnimationCurve.easeIn
}) .then(function () {
view.visibility = "collapse"
    console.log("Animation finished");
})
    .catch(function (e) {
    console.log(e.message);
});
```
This will allow you to specify the visibility property.

**Comment by Positivism** [comment]
How do I gain access to the view? I created an ElementRef using ViewChild this.ref.nativeElement.animate but I get undefined when I try to modify visibility.

**Comment by tsonevn** [comment]
Hi @Positivism,
Check out [this](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/c1c74b7a5e159e01f3bb0e27d9216ababab3e79c/app/ng-ui-widgets-category/web-view/basic-web-view/basic-web-view.component.ts#L15-L36) example from our NativeScript Angular SDK sample app.
