### ISSUE TITLE
ListPicker Inside GridLayout does not display correctly

### ISSUE THREAD

**Issue by alexisconsuegra** [NativeScript/NativeScript#6742]
List Picker does not display correctly inside a grid view if there are two columns.
Here is a screenshot 
![img_6896](https://user-images.githubusercontent.com/45446335/50554450-9831d900-0c88-11e9-8ebd-ecd6c26e68a8.jpg)

The code.

```
<ScrollView orientation="vertical">
    <GridLayout rows="50,auto,50,auto,50,auto,50,auto,50,auto,50,auto" columns="auto,*">
      <Label row="0" col="0" text="Title: " />
      <TextField row="0" col="1" id="title" text="{{ title }}" class="input" hint="Title" autocorrect="false" returnKeyType="next"/>
      <StackLayout row="1" col="0" colSpan="2" class="hr-light" />
      <Label row="2" col="0" text="Street Address: " />
      <TextField row="2" col="1" id="streetAddress" text="{{ streetAddress }}" class="input" hint="Street Address" autocorrect="false" returnKeyType="next" returnPress="focusSuite"/>
      <StackLayout row="3" col="0" colSpan="2" class="hr-light" />
      <Label row="4" col="0" text="Suite: " />
      <TextField row="4" col="1" id="suite" text="{{ suite }}" class="input" hint="Suite" autocorrect="false" returnKeyType="next" returnPress="focusCity"/>
      <StackLayout row="5" col="0" colSpan="2" class="hr-light" />
      <Label row="6" col="0" text="City: " />
      <TextField row="6" col="1" id="city" text="{{ city }}" class="input" hint="City" autocorrect="false" returnKeyType="next"/>
      <StackLayout row="7" col="0" colSpan="2" class="hr-light" />
      <Label row="8" col="0" text="State: " />
      <StackLayout row="8" col="1" >
        <ListPicker id="state" items="{{ states }}" selectedIndex="{{ state }}" selectedValue="{{ state }}"/>
      </StackLayout>
      <StackLayout row="9" col="0" colSpan="2" class="hr-light" />
      <Label row="10" col="0" text="Zipcode: " />
      <TextField row="10" col="1" id="zipcode" text="{{ zipcode }}" class="input" hint="Zipcode" autocorrect="false" returnKeyType="next"/>
    </GridLayout>
  </ScrollView>
```

**Comment by tsonevn** [comment]
Hi @alexisconsuegra,
Thank you for the provided sample code. 
I tested the case on my side, however, was unable to recreate an issue with the ListPicker. For your convenience, I am attaching the demo project and GIF, that demonstrates, how the component is working with the demo. 
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2717753/Archive.zip)
![screencast 2018-12-31 at 7 30 15 am](https://user-images.githubusercontent.com/17448734/50555026-d4882800-0cce-11e9-9661-a0c358c8e2c1.gif)

Please, check out the attached sample project and make the needed changes, that will allow us to recreate the issue.

**Comment by alexisconsuegra** [comment]
Hi Nikolay,
Thank you very much. The results you show are not the native behavior
I got the same results you have, but that is not correct. The native behavior displays previous items on top and next items at the bottom of the selected item. Please compare the two images I am sending.
Also, the view model "state" property is set to "FL". The list picker does not display FL as the selected value. I most be missing something but I can't find what it is. Thanks again.
________________________________

**Comment by alexisconsuegra** [comment]
Hi Nikolay,
Thank you very much. The results you show are not the native behavior
I got the same results you have, but that is not correct. The native behavior displays previous items on top and next items at the bottom of the selected item. Please compare the two images I am sending.

![img_6947e](https://user-images.githubusercontent.com/45446335/50975819-7290a500-14bc-11e9-92bb-ef5c14c55607.jpg)
![img_6896](https://user-images.githubusercontent.com/45446335/50975820-7290a500-14bc-11e9-9fe8-da48ea82569e.jpg)

**Comment by tsonevn** [comment]
Hi @alexisconsuegra 
Thank you for the provided ScreenShots. I also tested the UIPickerView in a native iOS project, However, was unable to find a difference between the behaviour in the native and NativeScript project. I am attaching gif file.
![screencast 2019-01-11 at 10 40 21 am](https://user-images.githubusercontent.com/17448734/51023074-a3d9a580-158e-11e9-8411-494d00df57d3.gif)

On the left simulator is build the NativeScript project and on the right one the native. You can see that items in both simulators are displayed in the same way. Also, you can find the native project, that I've used for testing on the attached zip file.

Let me know if I am missing something.  
[testListPicker.zip](https://github.com/NativeScript/NativeScript/files/2748814/testListPicker.zip)

**Comment by alexisconsuegra** [comment]
Thanks once again. I am sorry I have not been able to ask my question correctly because you keep showing me the same thing I am able to get.
Basically the widget works fine if it is NOT inside a GridLayout. But it does not work as intended if it is inside the grid. It is a Bug. 
Please compare the behavior of this last sample you provided with the first one you sent which was inside the GridLayout.

**Comment by NickIliev** [comment]
@alexisconsuegra your **9th row** (**index 8**) is having a height of **50** hardcoded in your rows definition. So it would only give 50 DP space to render to StackLayout which contains the ListPicker.

Change it to auto if you want the native look and feel.
