### ISSUE TITLE
.nomedia file created an saved with file system does not do its job

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#6743]
In android an empty .nomedia file in a folder should prevent appearing the media files in the folder to appear in googles gallery. When I use file-system to save a .nomedia file, this file is not doing it's supposed job. [Here](https://www.journeybytes.com/2018/01/reason-why-some-apps-ignoring-nomedia-file-android.html) it is described why. The file should have some attribute set to N(ormal) or "no attributes". I did not find a way in nativescript file-system tho set this attribute. Can you please tell me how to solve this problem ?

**Comment by tsonevn** [comment]
Hi @jokro,
I checked your case, however, was unable to find further info about the attributes(`N(ormal)` `"no attributes"`) and how they are set up to the file. In my opinion, you need to set up  some permissions to the newly created file(`.nomedia`), which will allow its correct execution. For example:
```
import * as fileSystemModule from "tns-core-modules/file-system";
import {isAndroid} from "tns-core-modules/platform"


export function onTap(){
    const documents: fileSystemModule.Folder = <fileSystemModule.Folder>fileSystemModule.knownFolders.documents();
    const folder: fileSystemModule.Folder = <fileSystemModule.Folder>documents.getFolder("testFolder");
    const file: fileSystemModule.File = <fileSystemModule.File>folder.getFile(".nomedia");
   
    const exists = fileSystemModule.File.exists(file.path);
    if(exists && isAndroid){
        let androidFile = new java.io.File(file.path);
        console.log("file exists");
        console.log("android file");
        console.log(androidFile);
        let canRead = androidFile.canRead();
        console.log("android file -canRead");
        console.log(canRead);
        if(!canRead){
            androidFile.setReadable(true);
        }
        let canExecute = androidFile.canExecute();
        console.log("android file -canExecute");
        console.log(canExecute);
        if(!canExecute){
            androidFile.setExecutable(true);
        }
    }
}
```
More info about setting up file permission on Android can be found [here](https://www.dev2qa.com/how-to-use-java-code-to-set-file-permission/).

**Comment by jokro** [comment]
tsonev, thx for your reaction. The problem is how to set de Achive attribute off. That is,
how can I invoke the **android setArchive function** ? ( In your above example java.io.File doen't know this function.) The android function I want to use is defined [here](https://developer.android.com/reference/java/nio/file/attribute/DosFileAttributeView).
