### ISSUE TITLE
Release build generates apk with embeded (js) source files !

### ISSUE THREAD

**Issue by essadek** [NativeScript/NativeScript#6747]
This might be a beginner question but I can't find an option to not include the source files in the apk.
If the Javascript source files are required in the Android package to be deployed and run how can we secure them ?

{
  "android": {
    "v8Flags": "--expose_gc"
  },
  "main": "app.js",
  "name": "NAME",
  "version": "4.1.0"
}

**Comment by tsonevn** [comment]
Hi @essadek,
The JavaScript files are required in the package and should not be removed. In your case, you can uglify the files while using the **uglify** flag(more info about this option can be found [here](https://docs.nativescript.org/performance-optimizations/bundling-with-webpack#uglifyjs). Keep in mind that you should use webpack for enabling the uglify option).

**Comment by NathanaelA** [comment]
Hi @essadek,

On NativeScript, React Native, ionic/cordova/phonegap the source code has to be bundled with the application (all platforms).     However, you can use things like the uglify flag (in nativescript) or use third party tools to make it even hard to see your code (things like appprotection.net and jsscrambler).      

Please note; even if you wrote your app in Java on Android; I could get access to your source code fairly trivially...  Java is fully decompilable unless you are using third party tools; and even in those cases the code is still frequently easily recovered...
