### ISSUE TITLE
Allow CSS & JS files to be set in XML

### ISSUE THREAD

**Issue by hshristov** [NativeScript/NativeScript#675]
Allow CSS file as well as JS code-behind file to be specified in the XML. This will allow CSS & JS to be set in different folder from the XML.

**Comment by atanasovg** [comment]
+1, this is an easy-to-implement feature that is extremely useful when people need custom folder structure.

**Comment by Plamen5kov** [comment]
:+1:  it would give us a project structure, so bigger projects are easier to read.
