### ISSUE TITLE
FileSystem getEntities()

### ISSUE THREAD

**Issue by nnuvo** [NativeScript/NativeScript#6750]
Nativescript-Vue
TNS 5.2.0

Filesystem getEntities() is skipping or not picking up files with small file sizes (JSON files).

**Comment by tsonevn** [comment]
Hi @nnuvo,
While building the project with WebPack, the JSON file will not be copied in the project by default. To solve this, you need to include the JSON as a file type that can be copied in your webpack.config.js. For example: 
```
new CopyWebpackPlugin([
                { from: "fonts/**" },
                { from: "**/*.+(jpg|png)" },
                { from: "**/test/*.+(json)" },
                { from: "assets/**/*" },
            ], { ignore: [`${relative(appPath, appResourcesFullPath)}/**`] }),
```
For your convinience I am attaching sample project.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2723142/Archive.zip)
