### ISSUE TITLE
iOS delay push notification prompt

### ISSUE THREAD

**Issue by stevenspiel** [NativeScript/NativeScript#6751]
I'd like to be able to prompt the user to allow push notifications after a specific event in my app, but the prompt is appearing when the app loads for the first time. Is it possible to delay that prompt? I have in my Info.plist:

```
<key>UIBackgroundModes</key>
	<array>
	<string>remote-notification</string>
</array>
```

For my use case, I'd like to first show a soft prompt within the app before showing the system dialog.

**Comment by tsonevn** [comment]
Hi @stevenspiel,
You can try requesting access permissions for the `remote-notification` programmatically. For example:
```
 const authorizationOptions = UNAuthorizationOptions.Alert | UNAuthorizationOptions.Sound | UNAuthorizationOptions.Badge;
    const curNotCenter = utils.ios.getter(UNUserNotificationCenter, UNUserNotificationCenter.currentNotificationCenter);
    curNotCenter.requestAuthorizationWithOptionsCompletionHandler(authorizationOptions, (granted, error) => {
        if (!error) {
            let sharedApplication = utils.ios.getter(UIApplication, UIApplication.sharedApplication);
            sharedApplication.registerForRemoteNotifications();
        } else {
          console.log("Error requesting push notification auth: " + error);
        }
      });
```
This will show the prompt when the request authorisation method is called. To access the native API in an NS TypeScript project, you will need to add [tns-platform-declarations](https://www.npmjs.com/package/tns-platform-declarations) in the project.
For further question, please use our StackOverflow thread [here](https://stackoverflow.com/questions/tagged/nativescript).
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2723300/Archive.zip)

**Comment by stevenspiel** [comment]
Oh fantastic! Thank you!
