### ISSUE TITLE
Android: App crash when trying to access topmost frame while app is using in split-screen mode

### ISSUE THREAD

**Issue by felix-idf** [NativeScript/NativeScript#6753]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.0
 - Cross-platform modules: 5.1.0
 - Android Runtime: 5.1.0
 - iOS Runtime: 5.1.0

**Describe the bug**
When the app is in split-screen mode (Android API 24 or higher), the **frameModule.topmost()** method returns **undefined**. So whyn trying to navigate using the topmost-frame, the app crashes with the following error:

> System.err: com.tns.NativeScriptException:
System.err: Calling js method onClick failed
System.err:
System.err: TypeError: Cannot read property 'currentPage' of undefined
System.err: File: "file:///data/data/org.nativescript.examples/files/app/views/side-drawer-content/side-drawer-content.js, line: 29, column: 28
System.err:
System.err: StackTrace:
System.err:     Frame: function:'sideDrawer', file:'file:///data/data/org.nativescript.examples/files/app/views/side-drawer-content/side-drawer-content.js', line: 29, column: 29
System.err:     Frame: function:'closeDrawer', file:'file:///data/data/org.nativescript.examples/files/app/views/side-drawer-content/side-drawer-content.js', line: 32, column: 20
System.err:     Frame: function:'tapAbout', file:'file:///data/data/org.nativescript.examples/files/app/views/side-drawer-content/side-drawer-content.js', line: 60, column: 5
System.err:     Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.examples/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
System.err:     Frame: function:'Observable._emit', file:'file:///data/data/org.nativescript.examples/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 127, column: 18
System.err:     Frame: function:'ClickListenerImpl.onClick', file:'file:///data/data/org.nativescript.examples/files/app/tns_modules/tns-core-modules/ui/button/button.js', line: 26, column: 23
System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:987)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err:     at com.tns.gen.java.lang.Object_button_19_32_ClickListenerImpl.onClick(Object_button_19_32_ClickListenerImpl.java:17)
System.err:     at android.view.View.performClick(View.java:5640)
System.err:     at android.view.View$PerformClick.run(View.java:22455)
System.err:     at android.os.Handler.handleCallback(Handler.java:751)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6165)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**To Reproduce**
Clone the [NativeScript examples](https://github.com/NativeScript/nativescript-marketplace-demo) repository (or NativeScript UI Samples,...).
Open the app on Android device with API 24+, go to the split-screen mode with another app and then try to navigate within the NativeScript app while split-screen mode is active.

**Expected behavior**
The topmosu-method o the frame module should not return undefined if the app is in split-screen mode.
If the whole split-screen scenario is not allowed for NativeScript apps, it should be mentioned in the docs , as I could not find anything about it. Maybe this is a bug since NS 5, I have not tried that with previous versions.

**Comment by tsonevn** [comment]
Hi @felix-idf,
I was able to recreate the issue on my side, and I will mark this as a bug. For now, I would suggest keeping track on the issue for further info

**Comment by ADjenkov** [comment]
Hi @felix-idf,
You can try add "screenLayout" configuration to `android:configChanges` in _App_Resources/Android/AndroidManifest.xml_:
`<activity android:configChanges="keyboardHidden|orientation|screenSize|`__screenLayout__`">`

This will prevent destroy of the main application Activity which will remove the topmost() frame and make it undefined if no previous frame available.

**Comment by felix-idf** [comment]
@ADjenkov 
thanks for your help. Indeed , the screenLayout flag was missing.
Now it works.
