### ISSUE TITLE
Application terminated when navigate from and back to component has <RadListView> with load more feature.

### ISSUE THREAD

**Issue by mudasser** [NativeScript/NativeScript#6754]
**Environment**
 - CLI: 5.0.1
 - Cross-platform modules: 5.1.0
 - Android Runtime: 5.1.0
 - iOS Runtime: 5.1.0
 - Plugin(s):
nativescript-ui-listview

**Describe the bug**
When navigate (clearHistory=true) from a component which has <RadListView> with loadMore auto to another component which also has navigation back to home component (clearHistory=true). Application terminate with couple or more cycles back and forth. 

**To Reproduce**

Once application launched tap on  Go to Profile and then on profile component tap on 'Go to listView' link which will take back to home. Try to repeat this cycle for some time. Application will terminate.

**Expected behavior**
Application should not be terminated while navigating between home and profile screens.

**Sample project**
PlayGround project link https://play.nativescript.org/?template=play-ng&id=hBqpY5

**Additional context**
Tested on iPhone 6 and iOS version: 12.1.2

**Exception trace:**

2019-01-04 12:11:14.862 nsplaydev[294:7859] PlayLiveSync: Uncaught Exception
2019-01-04 12:11:14.863 nsplaydev[294:7859] PlayLiveSync: Sending crash report
2019-01-04 12:11:18.876 nsplaydev[294:7859] *** JavaScript call stack:
(
	0   didLoadDataOnDemand@[native code]
	1   notifyLoadOnDemandFinished@file:///app/tns_modules/nativescript-ui-listview/ui-listview.js:1453:57
	2   @file:///app/home/home.component.js:37:52
	3   invoke@file:///app/tns_modules/tns-core-modules/timer/timer.js:54:53
	4   onInvoke@file:///app/tns_modules/@angular/core/bundles/core.umd.js:16201:43
	5   runGuarded@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:151:53
	6   tick@file:///app/tns_modules/tns-core-modules/timer/timer.js:19:26
	7   UIApplicationMain@[native code]
	8   start@file:///app/tns_modules/tns-core-modules/application/application.js:273:26
	9   run@file:///app/tns_modules/tns-core-modules/application/application.js:301:10
	10  bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:187:26
	11  bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:105:38
	12  bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:89:26
	13  anonymous@file:///app/main.js:8:57
	14  evaluate@[native code]
	15  moduleEvaluation@:1:11
	16  promiseReactionJob@:1:11
)
2019-01-04 12:11:18.876 nsplaydev[294:7859] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UICollectionViewLayoutAttributes setOwnerListView:]
: unrecognized selector sent to instance 0x1083d88f0'
*** First throw call stack:
(0x19a24cec4 0x19941da40 0x19a165c24 0x19a2527dc 0x19a25448c 0x10209d860 0x1c6cae1dc 0x1c6cb251c 0x1c6cb75bc 0x1c788b73c 0x19e849b74 0x19e84eb2c 0x1c7876c28 0x10209a734 0x10209c658 0x101968044 0x1019658dc 0x1019653a0 0x100ea54e4 0x101964448 0x10196383c 0x10196383c 0x101963d08 0x10196383c 0x10196383c 0x1019638a4 0x10195c30c 0x10175c9ac 0x100f08318 0x100f07ef4 0x100f0850c 0x1019661c8 0x1019681b4 0x19ad01488 0x19a1dd828 0x19a1dd558 0x19a1dcd8c 0x19a1d7c68 0x19a1d71f0 0x19c450584 0x1c73e2bc0 0x101968044 0x1019658dc 0x1019653a0 0x100ea54e4 0x101964448 0x1019638a4 0x1019638a4 0x1019638a4 0x1019638a4 0x1019638a4 0x1019638a4 0x10195c30c 0x10175c9ac 0x1019163e0 0x100ebc558 0x100febd84 0x10196431c 0x1019638a4 0x1019638a4 0x10195c30c 0x10175c9ac 0x101916544 0x100fe7184 0x100eb3a78 0x100f1364c 0x100b57b78 0x1005df4f4 0x199c96bb4)
libc++abi.dylib: terminating with uncaught exception of type NSException
2019-01-04 12:11:18.879 nsplaydev[294:7859] PlayLiveSync: Uncaught Exception

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#978
