### ISSUE TITLE
[NS 5] - Plugin migration

### ISSUE THREAD

**Issue by mobilemindtec** [NativeScript/NativeScript#6759]
Hi!

I have a drawer plugin that I use in my projects, and when I upgrade it to NS 5 it broke (ios only). I override `_addViewToNativeVisualTree` to fix part of the code. Before I was initializing the native IOS code on the constructor. But now, the content of `_mainContentHost` is not showed. Can you help me fix it?

My js code is:

`
var SideDrawer = (function (_super) {

    __extends(SideDrawer, _super)
    function SideDrawer() {
        _super.call(this)
        this._mainContentHost = new contentView.ContentView()
        this._drawerContentHost = new contentView.ContentView()
        this._drawerContentHost.height = mainScreen.bounds.size.height

        this._drawerContentHost.backgroundColor = "#FFFFFF"        
        
        this._drawer = MMSideDrawer.alloc().initWithViewContentContentWidthMarginPositionHasActionBarOwner(
            this.drawerContentSize,
            this.drawerMargin,
            this.drawerPosition,
            this.drawerHasActionBar,
            this
        )

        this._addView(this._mainContentHost)
        this._addView(this._drawerContentHost)
    }

    SideDrawer.prototype._addViewToNativeVisualTree = function (child, atIndex) {
        _super.prototype._addViewToNativeVisualTree.call(this, child, atIndex);

        if(this._mainContentHost === child){
            
            this._ios = this._mainContentHost.nativeView

        }else if(this._drawerContentHost === child){
            
            this._drawer.addContentView(this._drawerContentHost.nativeView)
        }
        
        return true        
    }

    Object.defineProperty(SideDrawer.prototype, "drawer", {
        get: function () {
            return this._drawer
        },
        enumerable: true,
        configurable: true
    })

    SideDrawer.prototype._onDrawerContentSizeChanged = function (oldValue, newValue) {
      var data = {
        newValue: newValue,
        oldValue: oldValue
      }

      this.drawerContentSize = data.newValue
    }

    SideDrawer.prototype._onDrawerMarginChanged = function (oldValue, newValue) {
      var data = {
        newValue: newValue,
        oldValue: oldValue
      }

      this.drawerMargin = data.newValue
      if(this._ios)
        this._drawer.setMargin(this.drawerMargin)
    }

    SideDrawer.prototype._onDrawerPositionChanged = function (oldValue, newValue) {
      var data = {
        newValue: newValue,
        oldValue: oldValue
      }

      this.drawerPosition = data.newValue
      if(this._ios)
        this._drawer.setPosition(this.drawerPosition)
    }

    SideDrawer.prototype._onDrawerHasActionBarChanged = function (oldValue, newValue) {

      var data = {
        newValue: newValue,
        oldValue: oldValue
      }

      this.drawerHasActionBar = data.newValue
      if(this._ios)
        this._drawer.setHasActionBar(this.drawerHasActionBar)
    }

    SideDrawer.prototype._onMainContentChanged = function (oldValue, newValue) {

      var data = {
        newValue: newValue,
        oldValue: oldValue
      }

      var newContent = data.newValue

      if (newContent instanceof view.View){
        this._removeView(this._mainContentHost);
        this._mainContentHost.content = newContent
        this._addView(this._mainContentHost);        
      }

    }

    SideDrawer.prototype._onDrawerContentChanged = function (oldValue, newValue) {

      var data = {
        newValue: newValue,
        oldValue: oldValue
      }

      var newContent = data.newValue
      if (newContent instanceof view.View) {
        newContent.height = mainScreen.bounds.size.height        
        this._removeView(this._drawerContentHost);
        this._drawerContentHost.content = newContent
        this._addView(this._drawerContentHost);
      }
    }

    SideDrawer.prototype._onDrawerFixeOpenedPropertyChanged = function(oldValue, newValue) {
        
      var data = {
        newValue: newValue,
        oldValue: oldValue
      }

      this._fixedOpned = newValue
      
      if(this._ios)
        this._drawer.setFixedOpened(data.newValue)

    }

    Object.defineProperty(SideDrawer.prototype, "_nativeView", {
        get: function () {
            return this._ios
        },
        enumerable: true,
        configurable: true
    })

    SideDrawer.prototype.closeDrawer = function () {
        if (this._ios) {
            this._drawer.onCloseMenuClick()
        }
    }
    SideDrawer.prototype.showDrawer = function () {
        if (this._ios) {
            this._drawer.onSlideMenuButtonPressed()
        }
    }

    SideDrawer.prototype.eachChildView = function (callback) {
        if (this._mainContentHost) {
            callback(this._mainContentHost);
        }
        if (this._drawerContentHost) {
            callback(this._drawerContentHost);
        }
    }    

    SideDrawer.prototype.onLayout = function (left, top, right, bottom) {

    
        var controller = frameModule.topmost().ios.controller
        var statusBarHeight = sharedApplication.statusBarFrame.size.height
        var actionBarHeight = (this.drawerHasActionBar) ? controller.navigationBar.frame.size.height : 0        
        var navBarHeight = actionBarHeight  + statusBarHeight
        var size = this.drawer.getView().frame.size

        var width = right - left;
        var height = bottom - top;

        var w = (this.drawerContentSize > 0) ? this.drawerContentSize : size.width - this.drawerMargin
        var h = size.height - navBarHeight

        var drawerSizeW = utils.layout.toDevicePixels(w);
        var drawerSizeH = utils.layout.toDevicePixels(h);
        
        
        var wp = utils.layout.toDevicePixels(size.width)
        var hp = utils.layout.toDevicePixels(size.height)

        this._drawerContentHost.layout(0, 0, drawerSizeW, drawerSizeH);
        

        if(this._fixedOpned){
            this._mainContentHost.layout(0, 0,  wp, hp);       
        } else {
            this._mainContentHost.layout(0, 0, wp, hp);       
        }

        this._drawer.setPosition(this.drawerPosition)
        this._drawer.setMargin(this.drawerMargin)
        this._drawer.setHasActionBar(this.drawerHasActionBar)
        this._drawer.addDrawerView()
    }
    SideDrawer.prototype.onMeasure = function (widthMeasureSpec, heightMeasureSpec) {
                

        var controller = frameModule.topmost().ios.controller
        var statusBarHeight = sharedApplication.statusBarFrame.size.height
        var actionBarHeight = (this.drawerHasActionBar) ? controller.navigationBar.frame.size.height : 0
        var navBarHeight = actionBarHeight  + statusBarHeight
        var size = this.drawer.getView().frame.size
        
        var drawerWidth = widthMeasureSpec;
        var drawerHeight = heightMeasureSpec;
        var w = (this.drawerContentSize > 0) ? this.drawerContentSize : size.width - this.drawerMargin
        var h = size.height - navBarHeight
        var drawerSizeW = utils.layout.toDevicePixels(w);
        var drawerSizeH = utils.layout.toDevicePixels(h);
        
        view.View.measureChild(this, this._drawerContentHost, utils.layout.makeMeasureSpec(drawerSizeW, utils.layout.EXACTLY), utils.layout.makeMeasureSpec(drawerSizeH, utils.layout.EXACTLY));

        var result = view.View.measureChild(this, this._mainContentHost, widthMeasureSpec, heightMeasureSpec);
        var width = utils.layout.getMeasureSpecSize(widthMeasureSpec);
        var widthMode = utils.layout.getMeasureSpecMode(widthMeasureSpec);
        var height = utils.layout.getMeasureSpecSize(heightMeasureSpec);
        var heightMode = utils.layout.getMeasureSpecMode(heightMeasureSpec);
        var widthAndState = view.View.resolveSizeAndState(result.measuredWidth, width, widthMode, 0);
        var heightAndState = view.View.resolveSizeAndState(result.measuredHeight, height, heightMode, 0);
        this.setMeasuredDimension(widthAndState, heightAndState);

    }
    return SideDrawer
})(commonModule.SideDrawer)
`

Thanks!

**Comment by tsonevn** [comment]
Hi @mobilemindtec,
I would suggest checking out the [nativescript-ui-sidedrawer](https://www.npmjs.com/package/nativescript-ui-sidedrawer). The plugin is fully compatible with NativeScript 5.x and can be used for both platforms(iOS and Android).
