### ISSUE TITLE
Hot Module Replacement (HMR) not pushing style changes for Single File Vue Components

### ISSUE THREAD

**Issue by saibbyweb** [NativeScript/NativeScript#6760]
**Environment**
√ Component nativescript has 5.1.0 version.
√ Component tns-core-modules has 5.1.1 version.
√ Component tns-android has 5.1.0 version.
√ Component tns-ios has 5.1.0 version.

**Hot Replacement Module not pushing styles changes on a Vue component**
Changing simple class properties such as **font-size** does not reflect on the app instantly even though the terminal says: 
`Refreshing application on device emulator-5554...`
`Successfully synced application org.nativescript.PilotVueApp on device emulator-5554.`

However, any change in the **script** part instantly updates the app (including the backlog of the un-updated style changes)

**Expected behavior**
Style changes should be instantly updated like the script changes.

**Sample project to reproduce (contains 1 simple Vue component)**
Here's the link of a sample project on which I'm facing the problem: [https://github.com/saibbyweb/nativescript-vue-pilot]

**Additional context**
I tested on an Android Emulator and using **NS Preview App** on an iOS device. I am having the same issue on both Android and iOS. (Windows 10 Home)

**Comment by tsonevn** [comment]
Hi @saibbyweb,
I tested the case on my side and was able to recreate the problem. I will mark this as a bug, and we will investigate further the issue. For now, I would suggest keeping track on the issue for further info.

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-cli #4266](https://github.com/NativeScript/nativescript-cli/issues/4266) via [**ZenHub**](https://www.zenhub.com/)
