### ISSUE TITLE
nativescript helloworld

### ISSUE THREAD

**Issue by Gurucharan** [NativeScript/NativeScript#6764]
Hello,

I was new to nativescript and trying to run android app in my local emulator followed steps from the nativescipt website. got following error. please tell me a solution to solve this error.

C:\Windows\System32\HelloWorld>tns run android
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Executing before-watchPatterns hook from C:\Windows\System32\HelloWorld\hooks\before-watchPatterns\nativescript-dev-webpack.js
Executing before-watch hook from C:\Windows\System32\HelloWorld\hooks\before-watch\nativescript-dev-webpack.js
Executing before-shouldPrepare hook from C:\Windows\System32\HelloWorld\hooks\before-shouldPrepare\nativescript-dev-webpack.js
Skipping prepare.
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from C:\Windows\System32\HelloWorld\app\App_Resources\Android\app.gradle
Using support library version 28.0.0
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: C:\Windows\System32\HelloWorld\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  Output:  C:\Windows\System32\HelloWorld\platforms\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

  Command: C:\Users\BESPL-COMP1\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\833daae6ab7426f29bf50f02404424e1\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
          -o \
          C:\Windows\System32\HelloWorld\platforms\android\app\build\intermediates\res\merged\debug \
          C:\Windows\System32\HelloWorld\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.
Executing after-watch hook from C:\Windows\System32\HelloWorld\hooks\after-watch\nativescript-dev-webpack.js
Stopping webpack watch
Executing after-watch hook from C:\Windows\System32\HelloWorld\hooks\after-watch\nativescript-dev-webpack.js
Stopping webpack watch

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#4269
