### ISSUE TITLE
How to get font path in Android app?

### ISSUE THREAD

**Issue by haingdc** [NativeScript/NativeScript#6768]
I'm following this sample in [#3671](https://github.com/NativeScript/NativeScript/issues/3671) to make span-tapable. And get stuck in setting font face (font-family) for it. How do I make it work?

![capture2](https://user-images.githubusercontent.com/14939139/50811065-59161e80-133f-11e9-9e5c-197fb669287a.PNG)

````ts
let ClickableSpanClass2 = ClickableSpan.extend({
  onClick: function(view) {
    console.log("on span click2: Learn more");
  },
  updateDrawState: function(tp: android.text.TextPaint) {
    this.super.updateDrawState(tp);
    let typeface = android.graphics.Typeface.createFromFile(`file:///android_asset/app/fonts/FSElliotPro.ttf`);
    typeface = Typeface.create(typeface, Typeface.BOLD);
    tp.setTypeface(typeface);
  }
});
```

**Comment by tsonevn** [comment]
Hi @haingdc,
You can use the [file system](https://docs.nativescript.org/api-reference/modules/_file_system_) module to access the currentApp folder and to then the needed ttf folder. Check out the article [here](https://docs.nativescript.org/ns-framework-modules/file-system#paths) which shows, how to access the current app folder path. For further questions, please use our [StackOverflow thread](https://stackoverflow.com/questions/tagged/nativescript). This repository is used only for bug reporting and feature requests.
