### ISSUE TITLE
Provide option to create project with local tns-core-modules

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/NativeScript#677]
Currently tns create does not provide an option to install tns-core-modules from local tgz. 
It will be nice it there is such option.

**Comment by rosen-vladimirov** [comment]
As a workaround you can create the project and point the local tgz after that:
```
tns create app1;
cd app1;
npm i --save <path to .tgz>
```

**Comment by vchimev** [comment]
This issue was moved to NativeScript/nativescript-cli#872
