### ISSUE TITLE
[iOS] Multiple frame breaks UIBarStyle

### ISSUE THREAD

**Issue by maxorlovsky** [NativeScript/NativeScript#6771]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.0
 - Cross-platform modules: 5.1.1
 - Android Runtime: 5.1.0
 - iOS Runtime: 5.1.0
 - Plugin(s): n/a

**Describe the bug**

I've installed cleaned NativeScript project and tried to change barStyle with this code.
```
var navigationBar = frame.topmost().ios.controller.navigationBar;
navigationBar.barStyle = 1;
```
It works, when my app-root.xml looks like this
```
<Frame defaultPage="home/home-page" id="my-frame-id"></Frame>
```
As soon as I put it in the Grid Layout, barStyle breaks and is not changing text color, only background color. But I need to change actual text.

**To Reproduce**
Install clean project, wrap Frame in app-root.xml with grid-layout and try to run this script
```
var frame = require("tns-core-modules/ui/frame");
var navigationBar = frame.topmost().ios.controller.navigationBar;
navigationBar.barStyle = 1;
```

**Expected behavior**
Styling still can be changed when using multiple Frames

**Sample project**
This works https://play.nativescript.org/?template=play-js&id=Ejj7Jp&v=3
This **won't** work https://play.nativescript.org/?template=play-js&id=Ejj7Jp&v=4

**Comment by tsonevn** [comment]
Hi @maxorlovsky,
Thank you for the provided sample projects. 
I was able to reproduce the described behaviour with barStyle. I will mark this as a bug, and we will investigate further the case. Meanwhile, It will help if you provide some more info about your scenario and why you need to wrap the Frame in GridLayout.

**Comment by maxorlovsky** [comment]
I'm using grid to create a skeleton file with main frame, that is going to display pages and under it have navigation menu, that is going to persist when transitioning between screens.
I'm originally using nativescript-vue and not nativescript-js, so this is my root template file:
```
<template>
    <GridLayout rows="*, 50">
        <Frame ref="mainFrame"
            row="0"
        >
            <router-view />
        </Frame>

        <navigation row="1" />
    </GridLayout>
</template>
```

Where navigation is component, which is a FlexboxLayout with icons, texts and links.

For me modifying status bar is mandatory, because I use dynamic actions bar color / banner images on top of the mobile page and sometimes images can be too dark, that's why I a possibility to swap barStyle text color from black to white when necessary.

**Comment by shihkerimov** [comment]
Is there any progress in solving this bug? Or workaround?

**Comment by darrenkhouston** [comment]
I'm having the same issue. Working in Nativescript Vue specifically, when setting the info.plist `UIViewControllerBasedStatusBarAppearance` to `true` and the `UIStatusBarStyle` set to `UIStatusBarStyleLightContent`, I have no control over the statusbar text color, only the background.

**Comment by rigor789** [comment]
I managed to change the status bar color with
```js
UIApplication.sharedApplication.setStatusBarStyleAnimated(0, true)
// or 
UIApplication.sharedApplication.setStatusBarStyleAnimated(1, true)
```
Seems like `navigationBar.barStyle` is deprecated?

**Comment by darrenkhouston** [comment]
> I managed to change the status bar color with
> 
> ```js
> UIApplication.sharedApplication.setStatusBarStyleAnimated(0, true)
> // or 
> UIApplication.sharedApplication.setStatusBarStyleAnimated(1, true)
> ```
> 
> Seems like `navigationBar.barStyle` is deprecated?

Yep. Fixed the issue for me. Thanks @rigor789

**Comment by maxorlovsky** [comment]
Yes, that worked perfectly fine. Thank you @rigor789.
I'm closing this issue as solution was found.
