### ISSUE TITLE
Javascript files do not update when updating the typescript files

### ISSUE THREAD

**Issue by Sam-Davis** [NativeScript/NativeScript#6774]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.2
 - Cross-platform modules:
 - Android Runtime: na
 - iOS Runtime: na
 - Plugin(s):
  "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "nativescript-angular": "~5.3.0",
    "nativescript-background-http": "^3.3.1",
    "nativescript-camera": "^4.0.2",
    "nativescript-imagepicker": "^6.0.5",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-sidedrawer": "~4.0.0",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~5.5.5",
    "tns-core-modules": "^4.0.1",
    "zone.js": "~0.8.18"

**Describe the bug**
I make a change to a typescript file and the javascript file is not updated. There are no errors being reported in the typescript and the app continues to work, but changes that I have made do not appear. 

**To Reproduce**
It happened after I created a pipe and this had an error, so I removed the pipe and added the transform in the controller instead. 

**Expected behavior**
Javascript files should update when making changes to a typescript file. Furthermore, if there is an issue with the project which is stopping the javascript from being generated, then an error message should be displayed. 

**Sample project**

**Additional context**

**Comment by Sam-Davis** [comment]
I had a typo in a switch statment

 case 'a': {
        'b'
        break;
      }

should have been: 

 case 'a': {
        return 'b'
        break;
      }

Ideally it would be great if the compiler picked this up.

**Comment by tsonevn** [comment]
Hi @Sam-Davis,
From your last comment, I am assuming that the issue on your side is solved. Regarding  transpilation, if there is an error in the ts file, the typescript transpiler should throw an error in the console. Check out if you are using the latest typescript on your side.
