### ISSUE TITLE
Add OnDiscardedError handler

### ISSUE THREAD

**Issue by vtrifonov** [NativeScript/NativeScript#6776]
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/NativeScript/android-runtime/issues/1245 and https://github.com/NativeScript/ios-runtime/issues/1051
We need to have a way to receive information about discarded errors using the following flags: [discardUncaughtJsExceptions](https://docs.nativescript.org/core-concepts/android-runtime/advanced-topics/custom-flags#discarding-javascript-exceptions-when-called-from-native) and [suppressCallJSMethodExceptions](https://github.com/NativeScript/android-runtime/issues/1223)

**Describe the solution you'd like**
A new handler to be added to the global object and a new application event to be added to the application. The possible usages are:
```JavaScript
global.__onDiscardedError = function(error){
    console.log(error.message);
    console.log(error.stackTrace);
    console.log(error.nativeException);
    //report the exception in your analytics solution here
}
```
or 
```JavaScript
var application = require("application");

application.on(application.discardedErrorEvent, function (args) {
    console.log(error.message);
    console.log(error.stackTrace);
    console.log(error.nativeException);
    //report the exception in your analytics solution here
});
```

**Comment by nmandyam** [comment]
This is such a great feature, but unfortunately, it refuses to report the code file-name and code line-number. Although the exception does show those details on the console. Can those items be added to the args?
