### ISSUE TITLE
iOS cloud build runs for hours

### ISSUE THREAD

**Issue by theremon** [NativeScript/NativeScript#6778]
**Environment**
Windows 10 Pro build 1803 
 - CLI: 
Component nativescript has 5.1.0 version and is up to date.
 - Cross-platform modules:
Component tns-android has 5.1.0 version and is up to date.
Component tns-ios has 5.1.0 version and is up to date.
 - Plugin(s):

**Describe the bug**
Got an application that is building fine locally on Android. It has been installed on Android devices etc and everything is ok. When trying through Sidekick to use iOS Cloud Build in order to create and test the same application on an iPhone, after creating the certificates etc, the procedure runs for many hours, with no apparent result. In some attempts, timeout errors from amazon-aws were received, in others nothing - it's just extremely slow with no feedback. In the Windows Task Manager, during all this time there are Java processes, some VirtualBox processes, NodeJS processes that get spawned and killed by Sidekick along with the Sidekick ones.
Previous attempts worked ok and we have had successful tests with other apps or older versions of the app, completing in just a few minutes.

In the latest run, everything was uploaded in about 2 minutes. After that, it the Build Step started. After 1 hour and 50 minutes, the message 'Checking for updates...' appeared. It now has been another 2 hours and nothing has happened yet.

If you need any further information that can be publicly shown without exposing the project, please ask.

Any advice would be greatly appreciated.
Thanks everyone...

package.json contents:
{
  "nativescript": {
    "id": "org.nativescript.MyClient",
    "v8Flags": "--expose_gc",
    "tns-android": {
      "version": "5.1.0"
    },
    "tns-ios": {
      "version": "5.1.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~7.0.0",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "nativescript-angular": "~7.0.0",
    "nativescript-oauth2": "^1.1.2",
    "nativescript-permissions": "^1.2.3",
    "nativescript-snackbar": "^4.0.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-zxing": "^1.5.7",
    "reflect-metadata": "0.1.12",
    "rxjs": "6.3.3",
    "tns-core-modules": "^5.1.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~7.0.0",
    "@nativescript/schematics": "~0.4.0",
    "@ngtools/webpack": "7.1.3",
    "nativescript-dev-typescript": "0.7.8",
    "nativescript-dev-webpack": "0.18.4",
    "typescript": "^3.1.6"
  },
  "readme": "NativeScript Application"
}

**Comment by sepccom** [comment]
My Nativescript Typescript is also stalling during an IOS Cloud Build. Here is the VS Output Log if this helps. An urgent fix would be helpful. Thanks.

1>------ Build started: Project: PunchList, Configuration: Debug iOS Cloud ------
1>Please wait while we prepare your project. This might take some time.
1>Getting accounts information...
1>Using account 30281662-c5fb-4a4b-a9ce-7ea346d1609f.
1>Starting cloud build of 'C:\Users\awday\Source\Repos\PunchList\PunchList', platform: 'iOS', configuration: 'Debug', buildId: 541a9ffa-4dae-4a1c-8fb2-2e9f433c3058.
1>Prepare step started.
1>Executing before-shouldPrepare hook from C:\Users\awday\Source\Repos\PunchList\PunchList\hooks\before-shouldPrepare\nativescript-dev-webpack.js
1>Skipping prepare.
1>Prepare step completed.
1>Upload step started.
1>Upload step completed.
1>Build step started.
1>  ios Build Tooling revision 2018.12.11.1 origin/release-v2
1>  Build Tooling Hostname administrators-mac-177.local
1> App package not specified. Skipping unzip step.
1>  NativeScript CLI version 5.0.3
1> Add platform ios with runtime version 5.0.0
1>Copying template files...
1>Platform ios successfully added. v5.0.0
1> Prepare Project for Platform -  ios

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/sidekick-feedback #326](https://github.com/NativeScript/sidekick-feedback/issues/326) via [**ZenHub**](https://www.zenhub.com/)
