### ISSUE TITLE
Setting TabView androidTabsPosition to bottom does not disable slide animation

### ISSUE THREAD

**Issue by enwi** [NativeScript/NativeScript#6787]
**Environment**
 - CLI: 5.0.3
 - Cross-platform modules: 5.1.0
 - Android Runtime: 5.1.0
 - iOS Runtime: 5.1.0
 - Plugin(s):
│ nativescript-angular              │ ~7.0.0  │
│ nativescript-localstorage         │ ^2.0.0  │
│ nativescript-theme-core           │ ~1.0.4  │
│ nativescript-ui-listview          │ ^5.0.1  │
│ nativescript-ui-sidedrawer        │ ^5.1.0  │
│ nativescript-websockets           │ ^1.5.3  │

**Describe the bug**
After setting the `androidTabsPosition` to bottom and changing the tab index using the `selectedIndex` property the slide animation is still shown. If the tab is changed using the TabView itself,  the animation is not shown, which should be the expected behavior. This will only affect Android devices.

**To Reproduce**
Hit the `CHANGE TAB VIA NGMODEL` button in the demo below and the tab is switched with a slide animation.

**Expected behavior**
Hitting the `CHANGE TAB VIA NGMODEL` button should change the tab, but not show the slide animation.

**Sample project**
[Sample](https://play.nativescript.org/?template=play-ng&id=JcyWb3)

**Additional context**

**Comment by ycherniavskyi** [comment]
It seems that this issue already had fixed by me in #6942.
