### ISSUE TITLE
NON HTTPS Webview not loading

### ISSUE THREAD

**Issue by saibbyweb** [NativeScript/NativeScript#6793]
**Environment**

√ Getting NativeScript components versions information...
√ Component nativescript has 5.1.0 version and is up to date.
√ Component tns-core-modules has 5.1.1 version and is up to date.
√ Component tns-android has 5.1.0 version and is up to date.
‼ Update available for component tns-ios. Your current version is 5.0.0 and the latest available version is 5.1.0.

**Describe the bug**
I'm using `Nativescript-Vue` and `WebWiew` component is not loading NON HTTPS websites. 
Tested on emulator running Android 9.0 and a physical device running iOS 12.1  

On Android it throws the following error : 
`net::ERR_CLEARTEXT_NOT_PERMITTED` 

and on iOS, I couldn't see any error as the load never finished.

**To Reproduce**
Just add a simple `WebView` and provide a non-https URL as `src`
 `<WebView src="http://google.com/" />`

**Expected behavior**
Should load a NON HTTPS website.

**Comment by tsonevn** [comment]
Hi @saibbyweb,
Can you provide a sample project, which demonstrates, how you are loading the content in the WebView?
Also if you are loading the WebView content from a local file, make sure that you have included your custom file's path in the `CopyWebpackPlugin` in the `webpack.config.js`. For example:
```
new CopyWebpackPlugin([
    { from: { glob: "ng-ui-widgets-category/web-view/web-view-html/test.html"} },
  .......
]
```

**Comment by amirvenus** [comment]
As far as I know, you cannot load a non-HTTPS on iOS anyway unless you explicitly put that as an exception in a file but for android, I am struggling to understand why it's not loading.

**Comment by NickIliev** [comment]
@amirvenus on Android 8 and above the cleartext traffic is not permitted and if you try to load **http** you should receive an error like 
```
net: ERR_CLEARTEXT_NOT_PERMITTED
```

This is valid for API levels 27 and above. Details on why this is happening and how to overcome the issue can be found in[ this SO thread](https://stackoverflow.com/a/50834600/4936697)
