### ISSUE TITLE
Documentation error: Button Tap Event handler argument Type

### ISSUE THREAD

**Issue by lord-saumagen** [NativeScript/NativeScript#6794]
Dear Ladies and Gentlemen,

recently it came to my attention that there is a discrepancy between your documentation and the current implementation of the "tap" event of a "Button" object. The documentation states that the "args" parameter should be of type "GestureEventData". But the truth is, that the "args" parameter is of type "EventData".

https://docs.nativescript.org/core-concepts/events

![image](https://user-images.githubusercontent.com/9468599/51125965-347be400-1822-11e9-9791-aebe7e27ff1e.png)

As far as I can see, that problem was already discussed in 2016. Unfortunately the documentation doesn't show the result of that discussion. 

https://github.com/NativeScript/NativeScript/issues/2775

For some reason it's generally hard to find the type information of the event handler parameters. 
They are not part of the "api-reference" but somewhat buried in "docs.nativescript.org". 

Sometimes the "api-reference" is also wrong. Here an example for the "onLoaded" event handler of the 
"Page" object. 

(The onLoaded event handler of the Page object gets also called with an args parameter of type EventData)

https://docs.nativescript.org/api-reference/classes/_ui_page_.page#onloaded

![image](https://user-images.githubusercontent.com/9468599/51126754-38a90100-1824-11e9-9dea-6b7e54b276c2.png)

It would be nice if you could make that kind of information available in the "api-reference" in the future.

Kind regards, Lord Saumagen.

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/docs #1503](https://github.com/NativeScript/docs/issues/1503) via [**ZenHub**](https://www.zenhub.com/)
