### ISSUE TITLE
TypeScript compiler failed with exit code 3221225477

### ISSUE THREAD

**Issue by anfen** [NativeScript/NativeScript#6800]
After following the NativeScript full installation guide, and executing **"tns create TypeScriptTest --ts"**, when I try and build the app, it fails:
```
PS C:\Users\Adam\TypeScriptTest> **tns build android**
Copying template files...
Platform android successfully added. v5.1.0
Executing before-shouldPrepare hook from C:\Users\Adam\TypeScriptTest\hooks\before-shouldPrepare\nativescript-dev-webpack.js
Executing before-cleanApp hook from C:\Users\Adam\TypeScriptTest\hooks\before-cleanApp\nativescript-dev-webpack.js
Executing before-prepare hook from C:\Users\Adam\TypeScriptTest\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 3.1.6
TypeScript compiler failed with exit code 3221225477
```

I've attached the large console output below, for the command: **tns build android --log trace**
[build.txt](https://github.com/NativeScript/NativeScript/files/2764064/build.txt)

The following commands **did work**, and successfully built the app - suggesting there is an issue with TypeScript:
```
PS C:\Users\Adam> **tns create JavaScriptTest --js**
PS C:\Users\Adam\JavaScriptTest> **tns build android**
```
I found the following tickets, but neither addressed exactly the issue I am experiencing:

https://github.com/NativeScript/NativeScript/issues/5215 <--Identical issue, but abandoned ticket
https://github.com/NativeScript/NativeScript/issues/5382 <--Not exactly the same issue

I have included the output of the following commands:
```
PS C:\Users\Adam\TypeScriptTest> **tns info**
√ Getting NativeScript components versions information...
√ Component nativescript has 5.1.0 version and is up to date.
√ Component tns-core-modules has 5.1.1 version and is up to date.
√ Component tns-android has 5.1.0 version and is up to date.
√ Component tns-ios has 5.1.0 version and is up to date.

PS C:\Users\Adam\TypeScriptTest> **tns doctor**
√ Getting environment information

No issues were detected.
√ Your ANDROID_HOME environment variable is set and points to correct directory.
√ Your adb from the Android SDK is correctly installed.
√ The Android SDK is installed.
√ A compatible Android SDK for compilation is found.
√ Javac is installed and is configured properly.
√ The Java Development Kit (JDK) is installed and is configured properly.
√ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
√ Getting NativeScript components versions information...
√ Component nativescript has 5.1.0 version and is up to date.
√ Component tns-core-modules has 5.1.1 version and is up to date.
√ Component tns-android has 5.1.0 version and is up to date.
√ Component tns-ios has 5.1.0 version and is up to date.
```
I am using Windows 10, Node version v8.9.1 and 32bit JDK (not 64bit).

The local version of npm TypeScript module to the app's root folder is:

PS C:\Users\Adam\TypeScriptTest> **npm list typescript**
C:\Users\Adam\TypeScriptTest
`-- nativescript-dev-typescript@0.7.9
    `-- typescript@3.1.6

The global version of npm TypeScript module is:

PS C:\Users\Adam\TypeScriptTest> **npm list -g typescript**
C:\Users\Adam\AppData\Roaming\npm
`-- nativescript@5.1.0
    `-- typescript@2.4.1

Any help would be greatly appreciated.

**Comment by tsonevn** [comment]
Hi @anfen,
Which Windows 10 and NodeJS versions you are using on your side(32bit  or 64bit)? If you are using 64 bit Windows version, I would suggest installing NodeJS 64bit version as well.

**Comment by anfen** [comment]
> Hi @anfen,
> Which Windows 10 and NodeJS versions you are using on your side(32bit or 64bit)? If you are using 64 bit Windows version, I would suggest installing NodeJS 64bit version as well.

Hi @tsonevn,
I'm using Windows 10 64bit and NodeJS 32bit.
I'm also using Appcelerator, which is "very" sensitive when the NodeJS\Java environment is changed, so not poking that would be ideal - but if it must to get NatveScript working, then it must.

**Comment by tsonevn** [comment]
Hi @anfen,
Because of the needs of NativeScript we have set up `max_old_space_size` to `4096 `. This can lead to the above error while using NodeJS 32bit. Regarding that, can you try installing NodeJS 64bit and try to rebuild the project.
