### ISSUE TITLE
TypeError: Cannot read property 'navigate' of undefined

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#6801]
Hi,

Since today I had this error on `Android` and `IOS` : 

```sh
01-16 15:30:46.448  6921  6921 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethodNative(Native Method)
01-16 15:30:46.448  6921  6921 E MessageQueue-JNI: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
01-16 15:30:46.448  6921  6921 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
01-16 15:30:46.448  6921  6921 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)
01-16 15:30:46.448  6921  6921 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
01-16 15:30:46.448  6921  6921 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: com.tns.NativeScriptException: 
System.err: Calling js method onTouch failed
System.err: TypeError: Cannot read property 'navigate' of undefined
```

My code is simply : 

```ts
import * as frameModule from "tns-core-modules/ui/frame";

var activate = function(args) {
    const navigationEntry = {
        moduleName: "views/activate/activate",
        animated: true,
        transition: {
            name: "slide",
            duration: 380,
            curve: "easeIn"
        }
    };
    var topmost = frameModule.topmost();
    topmost.navigate(navigationEntry); 
};
exports.activate = activate;
```

The strangest thing is that navigation works for some pages and not for others.

I found that this error could be if the path is not correct, OR my paths are correct (I checked)

TNS -v : 5.0.1

**Comment by kefahB** [comment]
Here is a playground project [https://play.nativescript.org/?template=play-tsc&id=WJ9wEx](url)

**Comment by tsonevn** [comment]
Hi @kefahB,
Thank you for the provided demo. 
Indeed the issue in the attached project was the wrong path that was set in the navigation method. I rebuilt the project several times, and the following error was thrown every time the button is tapped: 
```
TypeError: Cannot read property 'onNavigatingTo' of undefined
File: "file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js, line: 276, column: 36
``` 

If we change the path to `"views/settings"` the navigation work as expected, also, if I understand the case correctly, you are receiving the above error message even if the Page's path is correct. Regarding that, It will help if you can send us your project, where this problem can be reproduced.

**Comment by kefahB** [comment]
Hi @tsonevn 

Thanks for reply.

There is problem .. it is work in playground like you propose to remove the last `settings` but in my app this example will work as expected : 

From home > wallet
```ts
const navigationEntry = {
            moduleName: "views/wallet/wallet",
            context: { 
            },
            animated: true,
            transition: {
                name: "slide",
                duration: 100,
                curve: "easeIn"
            },
            backstackVisible: true,
            clearHistory: true
        };
        topmost.navigate(navigationEntry); 
```

AND THIS FAILLE !!!

From login > register :
```ts
const navigationEntry = {
            moduleName: "views/register/register",
            context: { 
            },
            animated: true,
            transition: {
                name: "slide",
                duration: 100,
                curve: "easeIn"
            },
            backstackVisible: true,
            clearHistory: true
        };
        topmost.navigate(navigationEntry); 
```

I create new folder and add new pages but no way to navigate .. I work with this APP since one year and I tested on real device and I never had this problem !!

**Comment by kefahB** [comment]
Do you think is come from versions incompatibility between tns-core-modules and Nativescript ??

Nativescript version is : `5.0.1`
Tns-core-modules : `5.1.2`

**Comment by tsonevn** [comment]
Hi @kefahB,
I do not think that similar difference in the used CLI and modules versions can be related to the problem. I also tested the below-attached sample project with CLI (5.0) and tns-core-modules(5.1.2), however, the navigation was correctly executed.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2771845/Archive.zip)

**Comment by kefahB** [comment]
I will go crazy :-s !! in the same project some pages are navigate and other are not !!!

**Comment by kefahB** [comment]
@tsonevn Finally I found the source of error !!!

The problem com from `app.ts` file that when I migrate NS to version `5.0.0` I read that we must declare `run` method instead of `start`. 

In my project `tns --version` return `5.0.1` that for what I use `run` : 
app.ts
```ts
// This will throw ERROR : TypeError: Cannot read property 'navigate' of undefined
application.run({ moduleName: "main-page" });
```

And when i change to `start` : 
app.ts
```ts
// This work as expected !!
application.start({ moduleName: "main-page" });
```

**Comment by kefahB** [comment]
@tsonevn Do you want test this issue with `run` `start` NS 5.0.1 before I close it ?

**Comment by tsonevn** [comment]
Hi @kefahB,
With the latest NativeScript, it is recommended to use `run` instead of `start`. Keep in mind that when you are using the run method, you need to declare a root component with a Frame object. Check out our template [here](https://github.com/NativeScript/template-blank-ts/blob/master/app/app-root.xml). I would suggest to try declaring the Frame as it is shown in the template and check if you will still have a problem.

**Comment by kefahB** [comment]
Hi,

I have already a Frame in root of my project `app/app-root.xml` below : 

```xml
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="tabLoaded" actionBarHidden="true">
    <TabView class="root-tabView" iosIconRenderingMode="alwaysOriginal" androidTabsPosition="bottom" selectedIndex="1" >
        <TabView.items>

            <TabViewItem title="Carte">
                <TabViewItem.view>
                    <Frame defaultPage="views/Maps/Maps"></Frame>
                </TabViewItem.view>
            </TabViewItem>

            <TabViewItem title="Home" >
                <TabViewItem.view>
                    <Frame defaultPage="views/home/home"></Frame>
                </TabViewItem.view>
            </TabViewItem>

            <TabViewItem title="{{ L('bookings') }}">
                <TabViewItem.view>
                    <Frame defaultPage="views/bookings/bookings"></Frame>
                </TabViewItem.view>
            </TabViewItem>
        </TabView.items>
    </TabView>
</Page>
```

**Comment by tsonevn** [comment]
HI @kefahB,
If you will use the TabView as a root component, you should remove the Page. For example:
```
<TabView class="root-tabView" iosIconRenderingMode="alwaysOriginal" androidTabsPosition="bottom" selectedIndex="1" >
        <TabView.items>

            <TabViewItem title="Carte">
                <TabViewItem.view>
                    <Frame defaultPage="views/Maps/Maps"></Frame>
                </TabViewItem.view>
            </TabViewItem>

            <TabViewItem title="Home" >
                <TabViewItem.view>
                    <Frame defaultPage="views/home/home"></Frame>
                </TabViewItem.view>
            </TabViewItem>

            <TabViewItem title="{{ L('bookings') }}">
                <TabViewItem.view>
                    <Frame defaultPage="views/bookings/bookings"></Frame>
                </TabViewItem.view>
            </TabViewItem>
        </TabView.items>
    </TabView>
```

**Comment by kefahB** [comment]
@tsonevn 

I am Sorry, but I removed the `Page` tag and the problem still.

**Comment by tsonevn** [comment]
Hi @kefahB,
I am still unable to recreate the issue while using the sample project, that I have attached in comment https://github.com/NativeScript/NativeScript/issues/6801#issuecomment-455445686.
Can you check if you will have the issue with the latest NativeScript `5.1`?

**Comment by kefahB** [comment]
Hi @tsonevn,

Sorry about delay .. but i had a real problem to update NS with OSX.

I updated to 5.1.1 and the problem still, BUT I think I know what the problem, it is in my app.ts, when on the first run of the APP there is no registered user and it will run the app on register page, this I think it cause the problem because the concept oh app-root with `TabView` dose not work any more, what do you think ?

app.ts : 
```ts
        /**
         * isAutehtificated         = isRegistered + isActivated    => home
         * isActivatedAccount   = isRegistered                           => login
         * isRegistered               = isRegistered                           => activate
         */
        if(isAutehtificated)
        {
            application.start({ moduleName: "app-root" });
        }
        else if(isActivatedAccount)
        {
            application.start({ moduleName: "views/login/login" });
        }
        else if(isRegistered)
        {
            application.start({ moduleName: "views/activate/activate" });
        }
        else 
        {
            application.start({ moduleName: "views/register/register" });
        }

```

**Comment by kefahB** [comment]
@tsonevn  [here](https://play.nativescript.org/?template=play-tsc&id=FkiFOe&v=2) is edited project with little change on app.ts

**Comment by kefahB** [comment]
I do this verification into `HomeViemModel` but what I dont like in this configuration is that the App will navigate first to the `main-page` then the user will see navigation back to `login`.

That with my old code the App lunch on login directly

**Comment by sinandogan** [comment]
`TypeError: Cannot read property 'onNavigatingTo' of undefined`

Hi, I know why you got an error. Your problem is with your home-view-model.ts file.

**Run example 1:
home-view-model.ts**
private page:Page;
constructor(page) {
        super();
        this.page=page;
        
      //get parameter
       var gotData = page.navigationContext;
        console.log(gotData.param1);
}

**home-page.ts**
import { Page } from 'tns-core-modules/ui/page';
import { Observable } from "tns-core-modules/data/observable";
export function onNavigatingTo(args: EventData) {
    const page = <Page>args.object;
   page.bindingContext = new HomeViewModel(page);  
}

-------------
**Run example 2 :**
**home-page.ts**
import { Page } from 'tns-core-modules/ui/page';
import { Observable } from "tns-core-modules/data/observable";
export function onNavigatingTo(args: EventData) {
    const page = <Page>args.object;
   page.bindingContext = new HomeViewModel(page);  

  //get parameter   
  var gotData = page.navigationContext;
    console.log(gotData.param1);
}

I hope it helps.

**Comment by androidovshchik** [comment]
@tsonevn answer is correct
create `app-root.xml` file
```
<Frame defaultPage="views/main-page/main-page"></Frame>
```
And this is main entry file
```
import * as app from "tns-core-modules/application";

app.run({moduleName: "app-root"});
```
