### ISSUE TITLE
Android detect keyboard before / after closing

### ISSUE THREAD

**Issue by Dennis-kw-yiu** [NativeScript/NativeScript#6806]
Is it possible to detect the keyboard before / after closing ?

**Comment by tsonevn** [comment]
Hi @Dennis-kw-yiu,
Check out the [nativescript-keyboardshowing](https://www.npmjs.com/package/nativescript-keyboardshowing) plugin. The plugin allows you to detect if the keyboard is showing or hiding.  
Also, for further question, please use our StackOverflow thread [here](https://stackoverflow.com/questions/tagged/nativescript). This repository is used only for bug reporting and feature requests.
