### ISSUE TITLE
Error public fsevents iOS

### ISSUE THREAD

**Issue by srcarmi** [NativeScript/NativeScript#6808]
Error is time to make public in the store ios (app store) initial review, the only way I could solve the problem was removing the folder 'fsevents' tns_modules and in the file package-loak.json fsvents and chokidar queria saable as i for you permanent standing this situation

```
Invalid Bundle Structure - The binary file '..................app/app/tns_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide for information on the iOS app bundle structure.
```

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #4304](https://github.com/NativeScript/nativescript-cli/issues/4304) via [**ZenHub**](https://www.zenhub.com/)
