### ISSUE TITLE
background-repeat: "no-repeat"; Doesn't seem to work

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#681]
This is the background image css for my page

Page xmlns="http://www.nativescript.org/tns.xsd" xmlns:widgets="utils/widgets" loaded="pageLoaded" cssClass="city-image"

.city-image{
	background-image: url("~/images/layout-background-city.jpg");
	background-repeat: "no-repeat";
}

On my android device though the image is repeating, at least on the y axis.

**Comment by vchimev** [comment]
Hi @sitefinitysteve,

I don't think the quotes of "no-repeat" are needed. Could you please try like this:

```
.city-image{
background-image: url("~/images/layout-background-city.jpg");
background-repeat: no-repeat;
}
```

**Comment by sitefinitysteve** [comment]
Eugh yeah that was it
