### ISSUE TITLE
Android crashes on css text-transform if undefined

### ISSUE THREAD

**Issue by abhayastudios** [NativeScript/NativeScript#6814]
**Environment**
```
$ tns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.1.1 version and is up to date.
✔ Component tns-core-modules has 5.1.2 version and is up to date.
✔ Component tns-android has 5.1.0 version and is up to date.
✔ Component tns-ios has 5.1.1 version and is up to date.
```

**Describe the bug**
 Android apps crash if a css text-transform is performed if the string is still undefined. It seems not an unlikely scenario that for example a `<Label>` component may be bound to a variable that initially may be still `undefined`.

In my opinion NS should handle this scenario and avoid an app crash.

**Sample project**
See this [play](https://play.nativescript.org/?template=play-ng&id=qi1RGa) project

**Comment by tsonevn** [comment]
Hi @abhayastudios,
Thank you for the attached sample project.
I was able to recreate the issue and will mark it as a bug. Meanwhile, you can try setting up the initial value for the Label to an empty string. For example:
```
export class TextComponent implements OnInit {
    public text = "";

    constructor() { }

    ngOnInit(): void {
        setTimeout(() => this.text = 'uppercase', 3000);
    }
}
```

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-angular #1699](https://github.com/NativeScript/nativescript-angular/issues/1699) via [**ZenHub**](https://www.zenhub.com/)

**Comment by abhayastudios** [comment]
@tsonevn I just submitted PR #6815 which should fix this issue. Why did you move it to nativescript-angular? Looks to me like this issue is with `tns-core-modules`.
