### ISSUE TITLE
Calling Swift code from NativeScript

### ISSUE THREAD

**Issue by Triuman** [NativeScript/NativeScript#6816]
I have a Swift project that opens the camera and does some image processing. How do I import Swift project to my NativeScript project and use its methods?

**Comment by NickIliev** [comment]
Refer to the articles linked in this documentation section for information on how to use APIs written in Swift. There is also useful information related to the topic [here ](https://www.nativescript.org/blog/video-course-use-objective-c-swift-and-java-apis-in-nativescript-for-angular)and [here](https://stackoverflow.com/questions/31856174/how-to-use-swift-library-in-nativescript)

Closing the issue as how-to-related

**Comment by Triuman** [comment]
Sorry but I still do not understand. I know how to use iOS apis. But I do not know how to use my own Swift project. Where should I put the project in my NativeScript project folder and how to import it?

Thank you.

**Comment by Triuman** [comment]
Ok that is more clear now. Thank you.
