### ISSUE TITLE
Missing App Icon 

### ISSUE THREAD

**Issue by emiloberg** [NativeScript/NativeScript#682]
Hi,

When I'm trying to upload an app to iTunes Connect, it fails with the error message:
> ERROR ITMS-90022: "Missing required icon file. The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 7.0"

![skarmavbild 2015-09-04 kl 16 39 08](https://cloud.githubusercontent.com/assets/4673048/9686970/f4e874b6-5326-11e5-81ba-791346d86b05.png)

I've replaced all icons in App_Resources (gotten from the hello world project), and there's a 120x120 icon (named `icon-60@2x`)

![skarmavbild 2015-09-04 kl 17 00 24](https://cloud.githubusercontent.com/assets/4673048/9687034/540fa40a-5327-11e5-9e1b-3f0807f795ba.png)

And this is how it looks like in Xcode, all the icons under `Resources`
 
![skarmavbild 2015-09-04 kl 16 59 04](https://cloud.githubusercontent.com/assets/4673048/9687073/954f936c-5327-11e5-804d-0a642e0e9728.png)

That being said. Notice the blue {N} icon in the bottom of the Xcode window. How did that get there? All the blue default icons have been replaced. Could it be that {N} hasn't updated the images as it should?

**Comment by emiloberg** [comment]
Looking at Images.xcassets, it's all empty:

![skarmavbild 2015-09-04 kl 17 15 58](https://cloud.githubusercontent.com/assets/4673048/9687242/a2555a14-5328-11e5-8019-69d72d264888.png)

**Comment by emiloberg** [comment]
I manually solved this by drag 'n' dropping the icons to the placeholders in the screenshot above. However, this shouldn't really be the case, should it?

Anything I can do to debug this?

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#888
