### ISSUE TITLE
Camera takePicture and uploading with bghttp not working

### ISSUE THREAD

**Issue by ozimanik** [NativeScript/NativeScript#6821]
i have tried every single solution and reach the server but the server doesnt get the image...

```
`function openCam(args) {
    camera.takePicture()
        .then(imageAsset => {

            var savepath = fs.knownFolders.documents().path;
            var filename = 'img_' + new Date().getTime() + '.jpg';
            var filepath = fs.path.join(savepath, filename);

            var imageSource = imageSourceModule.ImageSource;

            imageSourceModule.fromAsset(imageAsset).then(res => {
                imageSource = res;
                var picsaved = imageSource.saveToFile(filepath, "jpg");

                console.log("filepath: " + filepath);

                if (picsaved) {

                    var session = bgHttpModule.session("file-upload");

                    http.request({
                        url: appSettings.getString("url") + "/Public/UploadImage" + "?path=" + filepath + "&username=" + appSettings.getString("username") + "&passwort=" + appSettings.getString("passwort") + "&kalender=" + appSettings.getString("kalender") + "&evid=2996",
                        method: "POST",
                        headers: {
                            "Content-Type": "application/octet-stream",
                            "File-Name": filename
                        },
                    }).then(function (response) {
                        result = response.content.toJSON();
                        dialogs.alert(JSON.stringify(result));
                    }, function (e) { });

                    var task = session.uploadFile(filepath, request);

                    task.on("progress", logEvent);
                    task.on("error", logEvent);
                    task.on("complete", logEvent);

                } else {
                    console.log("Failed To Save");
                }
            })
        });
}
```

**Comment by NickIliev** [comment]
@ozimanik in your code you are using the [background-http plugin](https://market.nativescript.org/plugins/nativescript-background-http) but at the same time, you are also using the NativeScript `http` module...  It is not clear where the `request` is coming from in `session.uploadFile(filepath, request);`. Either use the HTTP module or the background-http plugin but in either case, use the code as described in [the related documentation](https://market.nativescript.org/plugins/nativescript-background-http).


```JS
var request = {
        url: url,
        method: "POST",
        headers: {
            "Content-Type": "application/octet-stream",
            "File-Name": name
        },
        description: description
    };

    if (should_fail) {
        request.headers["Should-Fail"] = true;
    }

let task: bghttp.Task;
task = session.uploadFile(file, request);
```

Closing as how-to related question.

**Comment by ozimanik** [comment]
but it doesnt work like this too
`function openCam(args) {
    camera.takePicture()
        .then(imageAsset => {

            var savepath = fs.knownFolders.documents().path;
            var filename = 'img_' + new Date().getTime() + '.jpg';
            var filepath = fs.path.join(savepath, filename);

            var imageSource = imageSourceModule.ImageSource;

            imageSourceModule.fromAsset(imageAsset).then(res => {
                imageSource = res;
                var picsaved = imageSource.saveToFile(filepath, "jpg");

                console.log("filepath: " + filepath);

                if (picsaved) {

                    var session = bgHttpModule.session("image-upload");

                    var request = {
                        url: appSettings.getString("url") + "/Public/UploadImage" + "?username=" + appSettings.getString("username") + "&passwort=" + appSettings.getString("passwort") + "&kalender=" + appSettings.getString("kalender") + "&evid=2996",
                        method: "POST",
                        headers: {
                            "Content-Type": "application/octet-stream",
                            "File-Name": filename
                        },
                    };

                    var task = session.uploadFile(filepath, request);
                    task.on("progress", logEvent);
                    task.on("error", logEvent);
                    task.on("complete", logEvent);

                } else {
                    console.log("Failed To Save");
                }
            })
        });
}`
