### ISSUE TITLE
Im trying to take a picture and upload it with backgroundHttp but it doesnt work

### ISSUE THREAD

**Issue by ozimanik** [NativeScript/NativeScript#6823]
`function openCam(args) {
    camera.takePicture()
        .then(imageAsset => {

            var savepath = fs.knownFolders.documents().path;
            var filename = 'img_' + new Date().getTime() + '.jpg';
            var filepath = fs.path.join(savepath, filename);

            var imageSource = new imageSourceModule.ImageSource;

            imageSourceModule.fromAsset(imageAsset).then(res => {
                imageSource = res;
                var picsaved = imageSource.saveToFile(filepath, "jpg");

                console.log("filepath: " + filepath);

                if (picsaved) {

                    var session = bgHttpModule.session("file-upload");

                    var request = {
                        url: appSettings.getString("url") + "/Public/UploadImage" + "?username=" + appSettings.getString("username") + "&passwort=" + appSettings.getString("passwort") + "&kalender=" + appSettings.getString("kalender") + "&evid=2996",
                        method: "POST",
                        headers: {
                            "Content-Type": "application/octet-stream",
                            "File-Name": filename
                        }
                    };

                    var task = session.uploadFile(filepath, request);
                    task.on("progress", logEvent);
                    task.on("error", logEvent);
                    task.on("complete", logEvent);

                } else {
                    console.log("Failed To Save");
                }
            })
        });
}`

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-background-http #200](https://github.com/NativeScript/nativescript-background-http/issues/200) via [**ZenHub**](https://www.zenhub.com/)
