### ISSUE TITLE
Failed to find module: "ui/audio", relative to: app/tns_modules/

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#6825]
In [playground example ](https://play.nativescript.org/?template=play-tsc&id=i6n8rT&v=20) for android  I have:

` <WebView>
            <audio controls>
                <source src='~/components/media/audio/sound.mp3' type="audio/mpeg" />
            </audio>
        </WebView>`

This generates error: 

`Error: Building UI from XML. @file:///app/app-root.xml:1:1
> Building UI from XML. @file:///app/home/home-page.xml:8:13
> Module 'ui/audio' not found for element 'Audio'.
> com.tns.NativeScriptException: Failed to find module: "ui/audio", relative to: app/tns_modules/`

Is there a module missing ? I have the same problem in my local build.

**Comment by tsonevn** [comment]
Hi @jokro,
You need to load the needed WebView content via its `src` property. Setting up the HTML directly in the XML file is causing the error. When you remove it the project will be built correctly. Check out the example [here](https://play.nativescript.org/?template=play-tsc&id=i6n8rT&v=23).
