### ISSUE TITLE
webview  stopLoading() no longer works

### ISSUE THREAD

**Issue by mspusta78** [NativeScript/NativeScript#6826]
WebView stopLoading() no longer works on Android Oreo and Android Pie

tns android version 5.0.0

Using standard WebView 
<WebView loadStarted="webViewLoadStarted" id="webBrowser"/>   

Trying to intercept LoadStarted event and stop loading the webview for a specific URL
exports.webViewLoadStarted = function(args) {   
     /// check args.url and decide if we want to stop loading it
     args.object.stopLoading();    // <-- this no longer works on Android Oreo and Pie
}

 args.object.stopLoading();  works good on iOS but on Android this no longer works consistently

**Comment by tsonevn** [comment]
Hi @mspusta78,
I've checked the described scenario with the WebView's `stopLoading` method, however, was unable to recreate the problem on a device with Android 8. For your convenience, I am attaching a sample project. In the demo, we have two buttons(`Start` and `Stop`). The start button will load a web page on the WebView with around 10 seconds delay. The stop button will call `stopLoading` method. If you tap the stop button in the sample project before those 10 seconds, the loading will be interrupted, and nothing will be shown on the WebView. Check out the demo and let me know if I am missing something.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/2790709/Archive.zip)

**Comment by mspusta78** [comment]
Hello @tsonevn ,
Thank you so much for you r prompt response! It is always appreciated!!!

I ran your example and it does work; however, it works only if the url schema starts with http:// or https://

I was able to re-create the issue using your project. I should mention that I am trying to stop the webview loading inside of the webViewLoadStarted event.

Go ahead and make these modifications to your project:
1. in the main-page.xml please change your WebView to:

<WebView id="wvId" row="4" src="{{source}}" loadStarted="webViewLoadStarted" loadFinished="webViewLoadFinished" />

2. in the main-page.js  (change the navigate url to custom schema)

vm.set("source", "custom://test");

3. in the main-page.js  (add the following)

exports.webViewLoadStarted = function(args) {      
    console.log("Load Started fired and url = "+args.url);     
    if (args.url.indexOf('custom//')>=0){                        
         args.object.stopLoading();              
         console.log("Stopping webpage load");
    }
}
exports.webViewLoadFinished = function(args) {     
    console.log("Load Finished fired and url= "+args.url);
}


____

You will see that if the URL is set to "custom://test" the webview does not stop loading, but if you were to set it to "http://custom//test" the webview.stopLoading() does work.

We have a project where we use custom schema to invoke some native functionality from the website when using our app (webview). This used to work just fine and still work fine on iOS but Android no longer works

@tsonevn I have two requests for your team:
1. Any chance to make the .stopLoading() work for non http:// or non https:// requests?
2. Any chance to make the webViewLoadStarted and webViewLoadFinished not fire multiple times?


Thanks for all you guys do!!!

**Comment by mspusta78** [comment]
@tsonevn 
I can see that my use case might be unique, but in further testing using your sample project I did discover that the stopLoading() doesn't work even if you use http:// 

There is 1 difference between our approach. You are setting the source of the webview when the "Start" button is pressed.

We need to be able to stopLoading() when user presses links within the website after we examine the link.

Please use this example
1. Set the webview source to the test page I made
vm.set("source","https://lifeinfoapp.com/test.html");

2. in that test page is a link to the http://httpbin.org/get
Let's assume we do not wish to load any content from this domain httpbin so in our webviewLoadStarted we do:

exports.webViewLoadStarted = function(args) {      
    console.log("Load Started fired and url = "+args.url);     
    if (args.url.indexOf('httpbin')>=0){                        
         args.object.stopLoading();              
         console.log("Stopping webpage load");
    }
}

You will see that the stopLoading() does not stop loading of the page and http://httpbin.org/get will get delivered to the webview.

These are the exact steps to duplicate this issue on Android Oreo and Pie

**Comment by NickIliev** [comment]
@mspusta78 the described scenario is working as expected on Android 8 & 9 (tested on Xiaomi, Nexus, Huawei real devices) - here is [the Playground demo](https://play.nativescript.org/?template=play-js&id=NwMh55) I've used during the tests
