### ISSUE TITLE
[ListView] [Scrolling] Item template with Labels with FormattedString strange Exception

### ISSUE THREAD

**Issue by gcaseres** [NativeScript/NativeScript#6827]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.0
 - Cross-platform modules: 5.1.2
 - Android Runtime: 5.1.0
 - iOS Runtime: 5.0.0
 - Plugin(s):

**Describe the bug**
I have a ListView with a complex Item Template. 
Each item template is a StackLayout with some Labels with FormattedString.
This Labels are shown conditionally (v-if in Vue) depending of the datasource structure.

When trying to scroll the ListView, an exception occurs: ```TypeError: Cannot read property 'textTransform' of undefined```

**To Reproduce**
I couldn't find a minimal example for error reproduction, so I've created a Playground sample similar to my real app with a testing datasource.
I'm receiving the error in the Playground sample.

**Expected behavior**
The exception should not occur.

**Sample project**
https://play.nativescript.org/?template=play-vue&id=kVJka3&v=4

**Additional context**
I've tried it on Android 8 and Android 4.4

**Comment by tsonevn** [comment]
This issue was moved to nativescript-vue/nativescript-vue#419
