### ISSUE TITLE
scss changes do not propogate to playground preview

### ISSUE THREAD

**Issue by sday** [NativeScript/NativeScript#6831]
**Environment**
 Component nativescript has 5.1.1 version and is up to date.
✔ Component tns-core-modules has 5.1.2 version and is up to date.
✔ Component tns-android has 5.1.0 version and is up to date.

**Describe the bug**
scss file changes do not propagate to playground preview via "tns preview --hmr"
You can see the file change is detected but the change doesn't display unless you restart.

**To Reproduce**
create Vue project
```
tns create simpleApp
cd simpleApp
tns preview -hmr

```
In Home.vue add class to the following line
`<Span class="newcolor" :text="message"/>
`
in app.scss add
```
.newcolor {
    color:green;
}
```

**Expected behavior**
Expected black text "Blank {N}-Vue app" to change to the specified color in scss file.   If I stop the tns preview and restart, the changes take effect. 

**Sample project**
I was not able to duplicate this in web based playground using standard .css files.  The changes propagated as expected. 

**Additional context**
I am running Node v11.1.0 which does throw a warning that CLI may not install properly, but it doesn't seem like that would be the problem here.

**Comment by vchimev** [comment]
Hey @sday,

thank you for the report!

This issue has been addressed by https://github.com/NativeScript/nativescript-dev-webpack/pull/763.

The fix is available in `nativescript-dev-webpack@next` and will take part of `0.19.1` later this week.

> Please, make sure to update the `webpack.config.js` file in the project.

Steps to update:
```
npm i -D nativescript-dev-webpack@next
./node_modules/.bin/update-ns-webpack --configs
```
