### ISSUE TITLE
Datepicker cant change Months names and the order theyre showed 

### ISSUE THREAD

**Issue by razdahan** [NativeScript/NativeScript#6833]
Hi is there any option to change the month's names and change the order they showed I mean instead of M/D/Y I want D/M/Y
tnx

**Comment by tsonevn** [comment]
Hi @razdahan,
Similar topic has been discussed in [this](https://discourse.nativescript.org/t/how-modify-the-result-default-date-format-to-this-dd-month-year-format-in-datepicker-control/2065) forum thread. I would suggest reviewing the provided solution in it.
