### ISSUE TITLE
NavigationEntry.bindingContext of app.run() not bind to rootView

### ISSUE THREAD

**Issue by webleaf** [NativeScript/NativeScript#6835]
**Environment**
 - CLI: 5.1.1
 - Cross-platform modules: 5.1.2
 - Android Runtime: 5.1.0
 - iOS Runtime:
 - Plugin(s):

**Expected behavior**
`Root View Text` should appear. `onLoaded` method should be called.

**To Reproduce**

Just replace your `app.ts` with this:
```typescript
import * as app from "tns-core-modules/application";
import {parse} from "tns-core-modules/ui/builder";
import {StackLayout} from "tns-core-modules/ui/layouts/stack-layout";
import {Observable} from "tns-core-modules/data/observable";

class RootLayoutViewModel extends Observable {

    public rootViewText = "Root View Text";

    onLoaded() {
        console.log("RootLayoutViewModel.onLoaded()")
    }
}

const rootLayoutXml = `<StackLayout loaded="{{ onLoaded }}"><Label text="{{ rootViewText }}"/></StackLayout>`;
const rootLayoutView = <StackLayout>parse(rootLayoutXml);
const rootLayoutViewModel = new RootLayoutViewModel();

app.run({
    bindingContext: rootLayoutViewModel, // <--------------- this is NOT do what expected
    create: () => {
        // rootLayoutView.bindingContext = rootLayoutViewModel; // <---------- workaround
        return rootLayoutView;
    }
});
```

**Comment by tsonevn** [comment]
Hi @webleaf, 
Can you provide some more info about your use case(Why you need to set up the bindingContext on `run`) and what you are trying to achieve as a final result?  

Thank you in advance for your cooperation.

**Comment by webleaf** [comment]
@tsonevn use case same as with using `bindingContext` in `navigate()`
I use one `ViewModel` per page. It's not comfortable to me to have 3 files (`xml`, `code-behind` and `view-model`). Also it is not comfortable to me to store view in `xml` file. I need to store view as string.
So there is no sense for me to use code-behind, because all I do in it is set `bindindContext`. All other things I do in ViewModel.
By the way, same concerns modal windows, where it is generally not possible to specify `bindingContext` in` showModal()`
Finally, `app.run()` have `NavigationEntry` as attribute, so it should work.

**Comment by webleaf** [comment]
@tsonevn I gave you more info. What's next?

**Comment by NickIliev** [comment]
@webleaf the thing is that with `application.run` your root view should be `Frame` so the binding context is passed to the `Frame` and no to your initial page.

If you want to start the app directly from a page (that would mean SPA app) you can use the start `method`

Using the `start` method with binding context
```JS
const vm = new Observable();
vm.set("name", "John SMith");

app.start({
    bindingContext: vm,
    create: () => { 
        return pageView;
    }
})
```

Apart from that if you want to have a `Frame` and more complex navigation scenarios then use the `run` and create a frame as root. The pass the binding context when you are creating the pages.

**Comment by webleaf** [comment]
@NickIliev you don't right. With `application.run` your root view SHOULD NOT be `Frame`. Vice versa
`start` method  implicitly create `Frame`. I don't need such root `Frame`, because I use `RadSideDrawer` as root view.

> Note: Prior to version 4.0.0 all NativeScript application had single topmost Frame implicitly created by the application.start() method. With NativeScript 4.x.x and above the root Frame is no longer implicitly created. Instead you can specify any View to be the root of your application while using application.run({ moduleName: "app-root"}) where app-root is the file containing your root View.

Note from here: https://docs.nativescript.org/core-concepts/application-lifecycle#application-run
