### ISSUE TITLE
Android build failing - Request to https://authentication.nativescript.cloud/v3/api/token-state timed out..

### ISSUE THREAD

**Issue by delanick** [NativeScript/NativeScript#6842]
Hi,

My builds were working fine and now suddenly the last few days I'm getting this error when building for Android:

`Unable to apply changes on device: 52108bf447e0c3ad. Error is: Request to https://authentication.nativescript.cloud/v3/api/token-state timed out..`

Very frustrating as I have no idea how to sort it out - please help.

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/sidekick-feedback #334](https://github.com/NativeScript/sidekick-feedback/issues/334) via [**ZenHub**](https://www.zenhub.com/)
