### ISSUE TITLE
License Requirement

### ISSUE THREAD

**Issue by NL33** [NativeScript/NativeScript#6846]
@rdlauer provides a description of the Apache License that comes with Nativescript here: [link](https://www.nativescript.org/blog/nativescript-licensing-explained).

The license--included when NS creates new apps--says things like: "each Contributor hereby grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare Derivative Works of, publicly display, publicly perform, sublicense, and distribute the Work". The Work is just defined as the work made available in the license.

I want to be totally sure that this license does NOT apply to the app itself I am putting on the app store. Obviously, users of the app **do not have** any right to reproduce, sublicense, etc... the app itself.  The license should only apply to software tools (like Nativescript itself) used in creating the app. 

Do I still need to include the "License" file with the app when I bundle it for the app store? If so, how am I sure its clear that there is no license given regarding the app itself?

**Comment by rdlauer** [comment]
Correct, the license does NOT apply to the app itself. Apache is not a "copyleft" license, it is very permissive (similar to MIT in many ways).

**Comment by NL33** [comment]
Thanks for your reply. Here's is my issue: how is it clear that the license only applies to the software (not the app itself), if I have to include the license in the app iself?

Basically, it seems like the Nativescript team is saying I have to include the license in my app. Which means my app has a file with a license that says it grants a license to reproduce, sublicense, etc. It would be helpful if somewhere the license made it clear that the license applies only to the underlying software tools, and not the app itself.

**Comment by rdlauer** [comment]
Apache 2 is one of the most widely-used OSS licenses, it's not unique to NativeScript. If your issue is with the wording of license itself, that's outside of the scope of what the NativeScript team can answer.

You can read more about Apache 2 on this excellent site:

https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

**Comment by NL33** [comment]
Thanks. I'm not looking for you guys to revise the Apache license terms. Instead, it would be helpful to understand how you guys see it--why you have comfort on this issue. Right now I am looking at my source code that has a doc in it (from Nativescript) that mimics the Apache language, and says it grants a license for anyone to do what they want with the "work".  

This is a key issue for anyone producing apps. However, maybe I am not approaching the topic correctly. I am just looking for some assurance that its clear the license applies to the underlying software, not the app itself. Is the license doc (and licenses with plugins in node modules) NOT included in the bundle that goes to Apple? Maybe there is something else I am missing?

**Comment by rdlauer** [comment]
Yep, so again the Apache license pertains to the code we ship as part of the NativeScript framework. It is not a “viral” or "copyleft" license and does not impact in any way additional code in an application. Any Intellectual Property, or Source Code, created by an app developer will have whatever license they choose and is unaffected by our licensing.

The Apache license also gives freedom to the app developer to ensure there will be no issues in the future if they need to modify the source code in the NativeScript framework.

So the license does NOT have to be included in your app, you can use whatever license you want.

**Comment by NL33** [comment]
That is helpful. Thank you.
