### ISSUE TITLE
tns-core-modules.d.ts: Wrong signature of Array#filter

### ISSUE THREAD

**Issue by sczerniawski** [NativeScript/NativeScript#6854]
**Environment**
The issue is present in master.

**Describe the bug**
The following code
```typescript
const x = [1, 2, 3].filter((v, i) => true);
```
causes the compiler to complain that `v` and `i` implicitly have an `any` type.

This is because `tns-core-modules.d.ts` contains an incomplete declaration of `Array#filter`:
https://github.com/NativeScript/NativeScript/blob/ff476d983d40afe136bfb4461f8dd20cfc72b21f/tns-core-modules/tns-core-modules.d.ts#L156-L158
which shadows the correct declaration in TypeScript's [lib.es5.d.ts](https://github.com/Microsoft/TypeScript/blob/14fa6ac8eb5a8aed75865ee3a5a9f7caf6353aa2/lib/lib.es5.d.ts#L1211).

**Suggested fix**
The fix is to remove the offending code from `tns-core-modules.d.ts`.

The fix is not a breaking change since TypeScript's `lib.es5.d.ts` contains the correct declaration since at least version 2.4.0 (June 2017).

**Comment by NickIliev** [comment]
@sczerniawski thank you for the provided info - feel free to become a contributor in NativeScript by creating a PR. Marking the issue as  `good-first-issue` so that anyone interested could improve the TypeScript declaration.
