### ISSUE TITLE
[CLI] Manual watching the source changes

### ISSUE THREAD

**Issue by raffaeler** [NativeScript/NativeScript#6865]
**Is your feature request related to a problem? Please describe.**
When `tns run` is started, it takes a while before deploying the application. For this reason I prefer to run in `watch mode` (`tns run` or `tns debug`).
Anyway, when you are doing more than a trivial change, it would be useful to manually trigger the compilation/deploy without stopping and re-running `tns run` or `tns debug`.

**Describe the solution you'd like**
When the terminal is in `tns run` or `tns debug` it can accept keyboard commands. It would be useful to add support for three commands while the terminal is watching:
- 's' key: suspend watching
- 'r' key: resume watching
- 'd' key: deploy while in suspended mode

**Describe alternatives you've considered**
Stopping and restarting `tns run` or `tns debug` is way too slow.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#4360
