### ISSUE TITLE
ListView separatorColor="transparent" doesn't delete separator on Android

### ISSUE THREAD

**Issue by krgolovan** [NativeScript/NativeScript#6869]
**Environment**
 - CLI: 5.1.1
 - Cross-platform modules: 5.1.0
 - Android Runtime: 5.1.0
 - iOS Runtime: 5.1.0
 - Plugin(s): nativescript-ui-listview: 5.0.1

**Describe the bug**
ListView separatorColor="transparent" doesn't delete separator on Android (Pixel 2XL) but works fine on iOS (iPhone X)

**To Reproduce**
Just run the sample project

**Expected behavior**
No separator between ListView items

**Sample project**
[Playground](https://play.nativescript.org/?template=play-vue&id=KD7Qaf&v=2)

**Additional context**
Screenshot from iOS:
![img_bbe3fb7527bd-1](https://user-images.githubusercontent.com/26555680/52378826-998bb980-2a1d-11e9-8143-2e36a7306d91.jpeg)
Screenshot from Android:
![screenshot_20190206-142113](https://user-images.githubusercontent.com/26555680/52378886-c50ea400-2a1d-11e9-8c8f-d55a19a7629d.png)

**Comment by NickIliev** [comment]
The issue seems to be reproducible only in Vue based project.

**Comment by chrisbekas** [comment]
Still an issue in {N} core in iOS but its intermittent; have also tried forcing that with CSS `ListView { separator-color: white; }`but every so often the separator turns up (sorry I haven't been able to find a pattern).

CLI: 5.2.4
tns-core-modules: 5.2.2
iOS Runtime: 5.2.0
Plugin(s): nativescript-ui-listview: 6.0.0

**Comment by VeeK727** [comment]
Its not just in vue. I'm facing the same issue in my vanilla js project with {N}6

**Comment by lblase** [comment]
I've tried to apply `android:listSelector="@android:color/transparent"` and `separatorColor="transparent"` to my `ListView` but nothing changed.
Also tried programmatically add `this.yourListView.nativeElement.setDivider(null);` but it breaks the list.

nativescript-ui-listview: 8.2.0

**Comment by rigor789** [comment]
If you apply a background to the items, the separator shows even if it's set to transparent, because it's a gap between the items and not actually a colored line. To confirm this, move `style="background-color: red"` to the ListView, and the gaps will no longer be visible. https://play.nativescript.org/?template=play-vue&id=hj3162

**Comment by lblase** [comment]
Alright, I have figured out what my problem is. After I have installed `RadDataForm` component into my nativescript app, the separators lines are always visible on any `ListView`. If I remove `RadDataForm` any workaround on `ListView` works.

Really I don't understand what is going on. Seems `RadDataForm` rewrite `ListView` styles...

**Comment by amberyiyao** [comment]
> Alright, I have figured out what my problem is. After I have installed `RadDataForm` component into my nativescript app, the separators lines are always visible on any `ListView`. If I remove `RadDataForm` any workaround on `ListView` works.
> 
> Really I don't understand what is going on. Seems `RadDataForm` rewrite `ListView` styles...

But how to solve this problem?

**Comment by rigor789** [comment]
Cannot reproduce anymore.
