### ISSUE TITLE
Issue in creating custom plugin(MapQuest)

### ISSUE THREAD

**Issue by venkatpruthvi** [NativeScript/NativeScript#6871]
I tried creating MapQuest Plugin using the steps given in plugin seed. I have imported the library from iOS and android and able to call them.

When trying to create instance for MQMapView with initwithframe() but the execution pauses at the creation and no error is displayed 
```
let map = MQMapView.alloc();
console.log("map alloc" + map)
console.log("map init  " + map.initWithFrame );
var rect = CGRectMake(0, 0, 200,200);
let mapView =  map.initWithFrame(rect);
console.log("map object" + mapView);
```
Logs:
```
CONSOLE LOG file:///app/tns_modules/nativescript-mapquestplugin/mapquestplugin.js:5:20: called
CONSOLE LOG file:///app/tns_modules/nativescript-mapquestplugin/mapquestplugin.js:7:20: map alloc<MQMapView: 0x7ff39505e000; frame = (0 0; 0 0); transform = [0, 0, 0, 0, 0, 0]; alpha = 0; opaque = NO; layer = (null)>
CONSOLE LOG file:///app/tns_modules/nativescript-mapquestplugin/mapquestplugin.js:8:20: map init  function initWithFrame() {
[native code]
}
```

gitlink: https://github.com/venkatpruthvi/mapquestplugin.git

**Comment by NickIliev** [comment]
@venkatpruthvi in the source of the GitHub repo you are not using `initWithFrame` and the map view is not attached to any parent view.

try the following:

```JS
let mapView= MKMapView.alloc().initWithFrame( CGRectMake( 0, 0, 1000, 1000 ) );

yourNativeView.addSubview(mapView);
```

**Comment by venkatpruthvi** [comment]
@NickIliev Thanks for update, adding pod for navigation solved my issue.
