### ISSUE TITLE
Android TabView Bottom don't have animation and swipe gesture

### ISSUE THREAD

**Issue by syahnur197** [NativeScript/NativeScript#6876]
TabView androidTabsPosition="bottom" disabled the swipe gesture and the animation

![bug](https://user-images.githubusercontent.com/18722385/52467288-f32be980-2bbf-11e9-97df-0762c8577f77.gif)

**Comment by NickIliev** [comment]
@syahnur197 this is expected behavior described in [this documentation section](https://docs.nativescript.org/ui/ns-ui-widgets/tab-view#tab-view)

> The iOS and Android UX guidelines regarding the Tab controls differ greatly. The difference is described in the below points:
> 
> The iOS tabs have their tab bar, which will be displayed always on the bottom and does not allow swipe gesture for changing tabs.
> The Android tabs are on top and will enable the swipe navigation between the tabs.
> For Android we have androidTabsPosition property which has two options top(default value) and bottom. Setting up this property to bottom allows mimicking Bottom Tab Navigation control(provided by android support library v25 release). Setting the Tabs at the bottom will disable the swipe navigation and the items preloading functionality
