### ISSUE TITLE
Build failed after adding nativescript-ui-dataform plugin

### ISSUE THREAD

**Issue by AmitGurbani** [NativeScript/NativeScript#6883]
### Tell us about the problem
Build failed with an exception after adding nativescript-ui-dataform plugin to the project

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- **CLI:** 5.1.1
- **Cross-platform modules:** 5.1.0
- **Runtime(s):** 5.1.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Add plugin nativescript-ui-dataform to the project 
    `tns plugin add nativescript-ui-dataform`
2. Build project
    `tns build android`
3. Build failed with an exception

> Exception in thread "main" java.lang.ClassNotFoundException: Class:
> com.telerik.widget.autocomplete.ShowSuggestionListListener
>         at org.nativescript.staticbindinggenerator.Generator.getClass(Generator.java:776)
>         at org.nativescript.staticbindinggenerator.Generator.collectInterfaceMethods(Generator.java:703)
>         at org.nativescript.staticbindinggenerator.Generator.getPublicApi(Generator.java:227)
>         at org.nativescript.staticbindinggenerator.Generator.writeBinding(Generator.java:342)
>         at org.nativescript.staticbindinggenerator.Generator.generateBinding(Generator.java:133)
>         at org.nativescript.staticbindinggenerator.Generator.processRows(Generator.java:172)
>         at org.nativescript.staticbindinggenerator.Generator.generateBindings(Generator.java:90)
>         at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:66)
>         at org.nativescript.staticbindinggenerator.Main.main(Main.java:47)

**Comment by erjdriver** [comment]
Did you do a `tns platform clean android` before the build.

Or better yet delete the platforms folder and then do the build.

you can also do a `npm install` and then the build.

**Comment by AmitGurbani** [comment]
I tried the solution from @erjdriver , problem appears to be solved now.

`tns build android` runs without any problem.
