### ISSUE TITLE
Documentation and examples for unit testing using NativeScriptTestingModule and TestBed

### ISSUE THREAD

**Issue by lohiarahul** [NativeScript/NativeScript#6885]
I cannot seem to find documentation or a working example for unit testing NativeScript applications using TestBed for which I assume NativeScriptTestingModule was created.

I have tried to use TestBed to test my components but it doesn't seem to work. I have followed the issues raised or the same and understand that the PR to implement this was pending and has been completed for some time now. It would be highly appreciated if the starter templates with Angular CLI could create tests with testbed or at-least there is sufficient documentation on the official website or link to a working sample.

Also, some documentation on using the utilities provided would be very helpful. 

NativescriptTestingModule,
nsTestBedInit(),
nsTestBedBeforeEach(),
nsTestBedAfterEach(),
nsTestBedRender()

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/docs #1535](https://github.com/NativeScript/docs/issues/1535) via [**ZenHub**](https://www.zenhub.com/)
