### ISSUE TITLE
How to scroll particular position when i click a button in scrollview?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [NativeScript/NativeScript#6893]
Iam developing android and ios application using nativescript angular.I was showing list of items using scrollview.Used ngfor to iterate the array of elements.I want scrollview scroll to particular item when i click a button.How can achieve the functionality in scrollview?

**Comment by tsonevn** [comment]
Hi @ArigarasuthanRepo,
Check out [this](https://discourse.nativescript.org/t/scroll-down-programmatically/5025/2) forum thread, where the same topic has been discussed. Also, for further questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript).
