### ISSUE TITLE
nativescript plugin build behaviour changed, conflicting android support library version

### ISSUE THREAD

**Issue by alex-m-humai** [NativeScript/NativeScript#6894]
**Environment**
 - CLI: 5.1.1
 - Cross-platform modules: tns-core-modules has 5.2.0

**Describe the bug**
A nativescript plugin i build a few weeks ago is not able to be built any more. I did not change anything since then. it always says that there are conflicting android support libraries.

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':releaseCompileClasspath'.
> Could not resolve com.android.support:support-v4:27.0.1.
  Required by:
      project :
   > Cannot find a version of 'com.android.support:support-v4' that satisfies the version constraints: 
        Dependency path ':nativescript_pdfview_ng:unspecified' --> 'com.android.support:support-v4:27.0.1'
        Constraint path ':nativescript_pdfview_ng:unspecified' --> 'com.android.support:support-v4' strictly '25.3.1' because of the following reason: releaseRuntimeClasspath uses version 25.3.1
        Dependency path ':nativescript_pdfview_ng:unspecified' --> 'com.android.support:support-v4:27.0.1'
        Constraint path ':nativescript_pdfview_ng:unspecified' --> 'com.android.support:support-v4' strictly '25.3.1' because of the following reason: releaseRuntimeClasspath uses version 25.3.1
        Dependency path ':nativescript_pdfview_ng:unspecified' --> 'com.github.barteksc:android-pdf-viewer:2.8.1' --> 'com.github.barteksc:pdfium-android:1.7.1' --> 'com.android.support:support-v4:25.3.1'

> Could not resolve com.android.support:support-v4:25.3.1.
  Required by:
      project :
   > Cannot find a version of 'com.android.support:support-v4' that satisfies the version constraints: 
        Dependency path ':nativescript_pdfview_ng:unspecified' --> 'com.android.support:support-v4:27.0.1'
        Constraint path ':nativescript_pdfview_ng:unspecified' --> 'com.android.support:support-v4' strictly '25.3.1' because of the following reason: releaseRuntimeClasspath uses version 25.3.1
        Dependency path ':nativescript_pdfview_ng:unspecified' --> 'com.android.support:support-v4:27.0.1'
        Constraint path ':nativescript_pdfview_ng:unspecified' --> 'com.android.support:support-v4' strictly '25.3.1' because of the following reason: releaseRuntimeClasspath uses version 25.3.1
        Dependency path ':nativescript_pdfview_ng:unspecified' --> 'com.github.barteksc:android-pdf-viewer:2.8.1' --> 'com.github.barteksc:pdfium-android:1.7.1' --> 'com.android.support:support-v4:25.3.1'

> Could not resolve com.android.support:support-compat:25.3.1.
  Required by:
      project :
   > Cannot find a version of 'com.android.support:support-compat' that satisfies the version constraints: 
        Dependency path ':nativescript_pdfview_ng:unspecified' --> 'com.android.support:support-v4:27.0.1' --> 'com.android.support:support-compat:27.0.1'
        Dependency path ':nativescript_pdfview_ng:unspecified' --> 'com.android.support:support-v4:27.0.1' --> 'com.android.support:support-media-compat:27.0.1' --> 'com.android.support:support-compat:27.0.1'
        Dependency path ':nativescript_pdfview_ng:unspecified' --> 'com.android.support:support-v4:27.0.1' --> 'com.android.support:support-core-utils:27.0.1' --> 'com.android.support:support-compat:27.0.1'
        Dependency path ':nativescript_pdfview_ng:unspecified' --> 'com.android.support:support-v4:27.0.1' --> 'com.android.support:support-core-ui:27.0.1' --> 'com.android.support:support-compat:27.0.1'
        Dependency path ':nativescript_pdfview_ng:unspecified' --> 'com.android.support:support-v4:27.0.1' --> 'com.android.support:support-fragment:27.0.1' --> 'com.android.support:support-compat:27.0.1'
        Dependency path ':nativescript_pdfview_ng:unspecified' --> 'com.android.support:appcompat-v7:27.0.1' --> 'com.android.support:support-vector-drawable:27.0.1' --> 'com.android.support:support-compat:27.0.1'
        Dependency path ':nativescript_pdfview_ng:unspecified' --> 'com.github.barteksc:android-pdf-viewer:2.8.1' --> 'com.github.barteksc:pdfium-android:1.7.1' --> 'com.android.support:support-v4:27.0.1' --> 'com.android.support:support-compat:27.0.1'
        Constraint path ':nativescript_pdfview_ng:unspecified' --> 'com.android.support:support-compat' strictly '25.3.1' because of the following reason: releaseRuntimeClasspath uses version 25.3.1

**To Reproduce**
git clone https://github.com/humai-technologies-gmbh/nativescript-pdfview-ng
cd nativescript-pdfview-ng
cd publish
bash pack.sh

**Expected behavior**
It should build.

**Sample project**
https://github.com/humai-technologies-gmbh/nativescript-pdfview-ng

**Comment by jibon57** [comment]
@alex-m-humai , you can try to add following codes in your `app.gradle` file:

```
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '27.0.1'
            }
        }
    }
}
```

**Comment by jibon57** [comment]
I think better way you can try `include.gradle` like this:

```
dependencies {
    def supportVer = "27.0.1"
    if(project.hasProperty("supportVersion")) {
  	    supportVer = project.supportVersion
    }
    implementation 'com.github.barteksc:android-pdf-viewer:2.8.1'
    implementation "com.android.support:support-compat:$supportVer"
}
```

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#1277
