### ISSUE TITLE
blur event on TextField is not called when tapping on Button

### ISSUE THREAD

**Issue by jerbob92** [NativeScript/NativeScript#6905]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.0
 - Cross-platform modules: 5.1.1
 - Android Runtime: 5.1.0
 - iOS Runtime: 5.1.1
 - Plugin(s): A lot.

**Describe the bug**
Situation: you have a view that contains a TextField and a Button, the TextField has a blur event and the Button has a tap event.
When you focus on the TextField, and then click on the Button, the tap event on the Button gets called, but not the blur on the TextField. This is not expected/wanted behaviour. The TextField should lose focus and call blur before calling tap on the Button.

**To Reproduce**
 - Create a view with a TextField and a Button
 - Add a blur event on the TextField which executes `console.log('blur');`
 - Add a tap event on the Button which executes `console.log('tap');`
 - Place your cursor in the TextField
 - Click the back button to hide the keyboard
 - Click on the Button
 - The console will log tap, not blur

**Expected behavior**
The console should log blur, then tap

**Sample project**
https://play.nativescript.org/?template=play-ng&id=Aj5SwT

**Additional context**
The blur event does get called when moving away from the view with the RouterExtensions. But the the tap is first called, then blur (blur after the `navigate()`).

**Comment by tsonevn** [comment]
Hi @jerbob92,
Thank you for the attached demo project.
The blur event by design will be fired when the TextField lose focus. Check out the initial [feature request](https://github.com/NativeScript/NativeScript/issues/2181), where this event has been requested.

In your case, I would suggest setting the focus for the second TextField, when the Button is tapped(you can use [focus](https://docs.nativescript.org/api-reference/classes/_ui_text_field_.textfield#focus) method). This will trigger the blur event for the first one.

**Comment by jerbob92** [comment]
@tsonevn Thanks for looking into it!
Shouldn't the TextField lose focus when you click the button? In our case, we can't focus on a second field, because there is no second field. Maybe we can change this into a feature request?

**Comment by tsonevn** [comment]
Hi @jerbob92,
I am not sure that clearing the focus on button tap is the correct native behaviour. In your case, I would suggest clearing the focus for the field on the tap via `clearFocus` native method for Android and `endEditing`for iOS. Check out the demo [here](https://play.nativescript.org/?template=play-ng&id=Aj5SwT&v=3). On that matter, you can open a new feature request about providing a more general way to clear the focus from the fields programmatically, that will allows handling similar cases.
