### ISSUE TITLE
nameof  method to get string value of property-name for  notifyPropertyChange

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#6907]
In notifyPropertyChange the property must be given as a string value. There exisits an npm packakage for typescript which implements a  **nameof** function which at compile/build time converts a property-name to its string value, see [here](https://github.com/dsherret/ts-nameof/tree/master/packages/ts-nameof) and [here](https://github.com/dsherret/ts-nameof). I do not understand the steps to follow to get it working in nativescript with visual studio.

Could you provide a (beginner's) instruction, or preferably, prepare a nativescript plugin ?

**Comment by NickIliev** [comment]
@jokro TypeScript doesn't support custom transformers so[ the plugin](https://github.com/dsherret/ts-nameof/blob/master/packages/ts-nameof/setup/tsc.md#swapping-out-typescript-with-ttypescript) is using [TTYpeScript](https://github.com/cevek/ttypescript#ttypescript). That said I don't beleive you can use it with NativeScript which supports the official TypeScript.

**Comment by jokro** [comment]
ThxOp 20 feb. 2019 08:32 schreef Nick Iliev <notifications@github.com>:@jokro TypeScript doesn't support custom transformers so the plugin is using TTYpeScript. That said I don't beleive you can use it with NativeScript which supports the official TypeScript.
