### ISSUE TITLE
Visibility attribute on ActionItem element

### ISSUE THREAD

**Issue by Kamilius** [NativeScript/NativeScript#691]
Hi guys. I didn't found any documentation on how 'visibility' actually works and for which elements. Only related article I've found is http://tjvantoll.com/2015/06/05/nativescript-showing-and-hiding-elements/ . 

Now I'm struggling with following visibility manipulation:

```xml

  <Page.actionBar>
    <ActionBar title="SampleApp">
      <ActionBar.actionItems>
        <ActionItem text="Stop"
                    tap="stopTimer" ios.position="right"
                    visibility="{{ timerId === 0 ? 'collapse' : 'visible' }}"/>
        <ActionItem text="Resume"
                    tap="startTimer" ios.position="right"
                    visibility="{{ timerId === 0 ? 'visible' : 'collapse' }}"/>
        <ActionItem text="Save"
                    tap="saveEntryToEntriesFile" ios.position="right"
                    visibility="{{ timerId === 0 ? 'visible' : 'collapse' }}"/>
      </ActionBar.actionItems>
    </ActionBar>
  </Page.actionBar>
```

`timerId`, is a set property of `pageData` observable, which holds `page context`.
First `ActionItem` should be seen only when `timerId` is different from `0` and second+third buttons, when `timerId` is `0`.

But currently all `ActionItem` elements are always visible, no matter timerId is 0 or holds value different from it.

Would be awesome to have a separate documentation chapter describing how to show/hide elements from both xml markup and code, as well as which elements could be dynamically shown/hidden and which are not.

**Comment by hshristov** [comment]
Hi @Kamilius,

visibility is a property of View so all views have it. You can check View API from here:
https://docs.nativescript.org/ApiReference/ui/core/view/View.html

ActionItem is not a descendant of View so it does not have visibility property. You can control its position:
https://docs.nativescript.org/ApiReference/ui/action-bar/ActionItem.html
Currently there is no option to control ActionItem visibility but you could log it as issue and we will evaluate it. For the moment you could simply not add it in the collection.

**Comment by Kamilius** [comment]
Hi @hshristov, and thanks for an answer.
Could you, please, point me on guide on how to properly log this post as issue? Because I believe it would be really handy to be able to manipulate those action buttons dynamically.
