### ISSUE TITLE
How to get the data elements of the tapped item in a JavaScript function.

### ISSUE THREAD

**Issue by alexisconsuegra** [NativeScript/NativeScript#6910]
I have a master detail pages using a list view in the master page created in Nativescript 5.0. I need to get the data elements of the tapped item in a JavaScript function. So far I get [object object].
```
<ListView row="1" col="0" items="{{ listings }}" itemTap="onItemTap" class="list-group">
<ListView.itemTemplate>
    <GridLayout class="list-group-item" rows="auto" columns="*, auto">
        <Label row="0" col="0" text="{{ title }}" class="list-item-header" />
        <Label row="0" col="1" class="page-icon fa" text="&#xf054;" />
    </GridLayout>
</ListView.itemTemplate>
```
The view model:
```
const viewModel = new observableModule.fromObject({
    listings: info.listings || [],
    processing: info.processing || false
});

The tap event and navigation:
function onItemTap(args) {
const view = args.view;
const page = view.page;
const tappedItem = view.bindingContext;

try {
    page.frame.navigate({
            moduleName: "./mylistings/mylisting/mylisting",
            context: tappedItem,
            animated: true,
            transition: {
                name: "slide",
                duration: 200,
                curve: "ease"
            }
        });
}
catch (e) {
    console.error(e);
}
}
```
The NavigatingTo page:
```
function onNavigatingTo(args) {
page = args.object;

const myListing = observableModule.fromObject({
    listings: args.context
});
page.bindingContext = myListing.listings;

console.log(`myListing.listings: ${myListing.listings}`);
}
```
What I am missing?

**Comment by tsonevn** [comment]
Hi @alexisconsuegra,

To receive the context only for the currently selected  item you need to get the bindingContext of the item's view. For example:
```
function onItemTap(args) {
const view = args.view;
const context = view.bindingContext;
......
}
```
For further help, check out thew example [here](https://play.nativescript.org/?template=play-tsc&id=bd4NKh&v=2).

**Comment by alexisconsuegra** [comment]
Hi,
Thanks for the response, but it does not solve the problem. Your code is just like the code I provided. I wonder if the code is visible to you. Let me clarify. The problem is not getting the context and passing it to the child page. The problem is getting it in the Navigated to page.

**Comment by alexisconsuegra** [comment]
How Ca I reopen it. It is not solved.

**Comment by tsonevn** [comment]
Hi @alexisconsuegra,
Try using `fromObjectRecursive` instead of `fromObject` in the `onNavigatingTo` method.  I also try to recreate your case in a sample project, however, on my side sending the context to the child page and its loading seems to work as expected. Check out the demo [here](https://play.nativescript.org/?template=play-tsc&id=v7ZxEt). If `fromObjectRecursive` does not solve the issue on your side, please make the needed changes in the demo project, which will help us to recreate the issue.

**Comment by alexisconsuegra** [comment]
It worked. Thanks.
