### ISSUE TITLE
Is there a memory problem with the owner references on android?

### ISSUE THREAD

**Issue by m-abs** [NativeScript/NativeScript#6913]
I'm researching a memory leak we have with `nativescript-angular` (https://github.com/NativeScript/nativescript-angular/issues/1738) and I noticed a few things in `NativeScript Core`.

Why is the `owner` references on Android not a `WeakRef` like it is on `iOS`?

For instance if you look at the `TouchListener` added here:
https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/core/view/view.android.ts#L416
This `owner` reference is not cleared when the `View` is destroyed, so there is circular reference between the `touchListener` and `owner` view.
On iOS the owner property would have been a `WeakRef` and there wouldn't have been a problem.

In my test project (https://github.com/NativeScript/nativescript-angular/issues/1738#issuecomment-464471438) this results in many leftover `Label` objects: 
![image](https://user-images.githubusercontent.com/1348705/52920788-ec644b80-3310-11e9-92f4-c608341a8856.png)

The screenshot is after forcing 100 redraws of a `ListView` with ~22 items, resulting in ~2200 `Label` objects.

I could submit a PR fixing this for the `touchListener` so the owner reference is cleared, but before that I'd like to understand why android views don't use a `WeakRef` to the owner like the `iOS` views do?

**Comment by tsonevn** [comment]
Hi @m-abs,
We just tested your demo project and on our side, all items seem to be appropriately released (the destroyed native views are the same quantity as the created ones at the beginning). We have tested the scenario on Android device - API level 28. We checked, also, the touchListener's functionality and it seems that the listener is removed correctly from the objects. Regarding that, we can not ensure that if the Android views use WeakRef the issue on your side will be resolved. Can you provide some more info, whether this change (using WeakRef for the views) helps in solving the problem on your side and how you debugged this issue?

**Comment by m-abs** [comment]
Hi @tsonevn 

Thank you for getting back to me so quickly.

I created this project for my nativescript-angular issue:
https://github.com/m-abs/tns-ng-leak

My emulator is a `Pixel with API 28`.

I ran it with:
```bash
tns debug android --bundle --emulator
```

- Started the Chrome debugger.
- I let the app switch/flip between my two ListViews to force destroy and recreation of the Views.
- While the app was running I took some heap snapshots.

In these heap snapshots I see a lot of Labels and everyone I look at have an reference as "owner" on an `Object` and that `Object` has an reference as `touchListener` on the `Label`.

These Labels are all inside a `StackLayout` in a `ListView`.

I'm sure why but the `touchListener` is added to the Labels but not on the StackLayouts or the ListViews.
https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/core/view/view.android.ts#L409

**Comment by pana-cc** [comment]
> Quote: I'm sure why but the touchListener is added to the Labels...
```
        <Label
          [nsRouterLink]="['/item', item.id]"
          [text]="item.name"
        ></Label>
```
The nsRouterLink probably listens for tap on the label to initiate navigation.
