### ISSUE TITLE
setClipChildren messes up interaction with Android elements

### ISSUE THREAD

**Issue by zslusnys** [NativeScript/NativeScript#6914]
**Environment**
 - CLI: 5.1.0
 - Cross-platform modules:  5.1.2
 - Android Runtime: 5.1.0

**Describe the bug**
This happens on android
When tapping the fab item, it should call the tap even, but it's hidden due to setClipChildren property set to false on each element layout element through code. The whole context is hidden somewhere. I think it should be possible to have these elements z-index (in web) increased because now they're shown but not functioning. I would assume it happens to other elements as well if you were to use on with other components.

**To Reproduce**
You can visit https://play.nativescript.org/?template=play-vue&id=vtenPV and add @tap="fabTapped" to each FabItem and implement method with a console output. Try expanding the fab item group and clicking on them, theres no action nor event initiated.

**Expected behavior**
tap event works and its possible to click the button.

**Sample project**
https://play.nativescript.org/?template=play-vue&id=vtenPV

**Additional context**
I tried to create a gif of what I mean. At first when the gif starts, I remove setClipChildren from the context of layout elements, later I add them. You can see that when setClipChildren it set to false the FabItems are shown, but you can't click on them.

![cant click](https://user-images.githubusercontent.com/10806701/52949765-26673900-3375-11e9-8f24-4e7338d48b7c.gif)

**Comment by NickIliev** [comment]
This issue was moved to nativescript-vue/nativescript-vue#434
