### ISSUE TITLE
iOS ScrollView & ListView issue with dynamically resized content (ngIf, visibility, textWrap)

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#6915]
Result: The UI is misplaced when the size is changed dynamically (for a view that is no part of the initially visible content inside the Scrolling area)

In cases when the content of the children inside a ScrollView or ListView is changing its size dynamically, the top content of the ScrollView/ ListView is misplaced and the UI is broken.

Happens only on iOS (tested with IPhoineX).

[Test application](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/test/dyn-grid) demonstrating the above with **ngIf**, **visibility** and **textWrap**.

Steps to reproduce:
- Run the app on iPhoneX 
- Use the button to show/hide long multiline text content.
- Scroll outside of the initially loaded items and repeat the above step. The scroll to the top to observe the misplaced UI.

Reported via t.1388181

**Comment by EddyVerbruggen** [comment]
Hi @MartoYankov, is there any quick & dirty workaround you can think of? I don't mind patching node_modules locally.

**Comment by edusperoni** [comment]
Could you try manually setting `iosOverflowSafeArea` to false on each component? I currently don't have an iPhone to test, but this property is acting up sometimes on ListViews/ScrollViews

**Comment by Burgov** [comment]
Hi @edusperoni, that worked! In the end all I had to do was add `iosOverflowSafeAreaEnabled="false"` to the scrollview, and then it started functioning as intended again.

This gets us out of the woods, thanks!

**Comment by EddyVerbruggen** [comment]
@NickIliev @MartoYankov I can confirm adding `iosOverflowSafeAreaEnabled="false"` to the outer `ScrollView` in Nick's test app also fixes the issue there. @edusperoni thanks a million!

**Comment by edusperoni** [comment]
Glad to see it working!

Just to add, you can put `iosOverflowSafeArea` on the gridlayouts and textviews. In our case we had a stacklayout acting up inside a listview, so we just disabled it there.

This might be useful if you want to overflow the scrollview. (Haven't tested on iPhone X, so can't say for sure)

**Comment by MartoYankov** [comment]
Sorry, I was off a bit. I'm glad you were able to find a workaround. Indeed, disabling the safe area should fix such issues. I made a patch PR with a fix. You can check it out and test it with the scenarios in your apps.
