### ISSUE TITLE
With HMR changes in app.css file causing angular reload on windows

### ISSUE THREAD

**Issue by endarova** [NativeScript/NativeScript#6916]
CLI: 5.2.0
Reproducible on Windows

When running angular project with --hmr changes to app.css file seems to reload angular components also.
1. tns create NGApp --ng
2. In the items.components.ts  file in the ngOnInit() method add console log in my case: console.log("QA: items component on init");
3. tns run android --hmr
4. Make changes to app.css

Expected: only app.css is updated, no angular reload
Actual:  In the log you can see the angular messages and the console log from items.components.ts file

Webpack build done!
Successfully transferred bundle.af939dfa55f034fddab1.hot-update.js on device emulator-5554.
Successfully transferred af939dfa55f034fddab1.hot-update.json on device emulator-5554.
JS: HMR: Checking for updates to the bundle with hmr hash af939dfa55f034fddab1.
JS: HMR: The following modules were updated:
JS: HMR:          ↻ ./app.css
JS: HMR: Successfully applied update with hmr hash af939dfa55f034fddab1. App is up to date.
Refreshing application on device emulator-5554...
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: QA: items component on init

**Comment by vchimev** [comment]
This issue was moved to NativeScript/nativescript-dev-webpack#806
