### ISSUE TITLE
ListView blank when scroll down

### ISSUE THREAD

**Issue by danicomas** [NativeScript/NativeScript#692]
Look at this video:
https://www.dropbox.com/s/6v0lr5lrrwexjks/nativeScript_listview_blank.mp4?dl=0

Is it a render problem @enchev @vakrilov @hamorphis @ErjanGavalji @hshristov?

P.S.: iOS 7.1.2 / iPhone 4

**Comment by enchev** [comment]
Hey @danicomas,

I believe that this is known issue with iOS 7.x ListView which is fixed in iOS 8.x.

**Comment by danicomas** [comment]
@enchev and this https://github.com/NativeScript/NativeScript/issues/693 too?

**Comment by danicomas** [comment]
It is true @enchev. In iOS simulator not appears.

**Comment by danicomas** [comment]
Probably it won't be easy but could be fixed or is it in your roadmap @enchev? I think that is not a good way discard iOS 7 by now. Thanks

**Comment by N3ll** [comment]
The solution of this problem is related to https://github.com/NativeScript/NativeScript/issues/693.
