### ISSUE TITLE
Navigation in Angular app stops working in Android after going back

### ISSUE THREAD

**Issue by lini** [NativeScript/NativeScript#6928]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.2.0
 - Cross-platform modules:
 - Android Runtime: 5.2.0
 - Plugin(s): ALL

**Describe the bug**
In an Angular app on Android, navigating forwards and back sometimes causes navigation to stop working.

**To Reproduce**
Contact me @ADjenkov for reproduce. Open app, login, go to list view, select list view item, click button to navigate a second time, click back button in action bar. All navigation buttons stop working after that.

**Expected behavior**
Navigation works all the time.

**Sample project**
Available upon request.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#1744
