### ISSUE TITLE
ListView - the position of the item after scroll down is not correct

### ISSUE THREAD

**Issue by danicomas** [NativeScript/NativeScript#693]
Look at this video:
https://www.dropbox.com/s/6v0lr5lrrwexjks/nativeScript_listview_blank.mp4?dl=0

**Before scroll down**

All is ok.

![image](https://cloud.githubusercontent.com/assets/4038192/9734140/ff34f982-5630-11e5-8d15-ba7cc72fa7a8.png)

**After scroll down**

54 should be 59 isn't it @enchev @vakrilov @hamorphis @ErjanGavalji @hshristov?

![image](https://cloud.githubusercontent.com/assets/4038192/9734158/1d5f62c6-5631-11e5-8d1f-9c94632a9f98.png)

P.S.: iOS 7.1.2 / iPhone 4

**Comment by hamorphis** [comment]
We must introduce row-height property to fix this issue.

**Comment by nsndeck** [comment]
Closed with commit #1035.
