### ISSUE TITLE
After add plugin build release fail

### ISSUE THREAD

**Issue by yclau** [NativeScript/NativeScript#6932]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.2
 - Cross-platform modules: 5.2
 - Android Runtime: 5.2
 - iOS Runtime: 5.2
 - Plugin(s): nativescript-onesignal

**Describe the bug**
after i added plugin nativescript-onesignal , then I release android build and error show below.  

* What went wrong:
Could not resolve all files for configuration ':app:releaseCompileClasspath'.
> Could not find :fancywebview-release:.
  Required by:
      project :app
> Could not find :nativescript_camera:.
  Required by:
      project :app
> Could not find :nativescript_social_share:.
  Required by:
      project :app
> Could not find :TNSListView-release:.
  Required by:
      project :app
> Could not find :TNSCore-release:.
  Required by:
      project :app
> Could not find :widgets-release:.
  Required by:
      project :app

**Comment by NickIliev** [comment]
@yclau have you tried a clean rebuild? Reset the node_modules and platforms folder and give it a try.
```
rm -rf node_modules platforms hooks
npm i 
tns build android | ios
```

If you still experience the issue, then please post the content of your 'package.json'

**Comment by yclau** [comment]
Thanks @NickIliev , it works
