### ISSUE TITLE
Error: Invalid boolean when using switch component in angular reactive forms.

### ISSUE THREAD

**Issue by TomaNikolov** [NativeScript/NativeScript#6934]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.2.0
 - Cross-platform modules: 5.2.0
 - Android Runtime: 5.2.0
 - iOS Runtime: 5.2.0
 - Plugin(s):

**Describe the bug**
Using switch component in angular reactive forms causes `Invalid boolean` error.
This is only reproducible on iOS.

**To Reproduce**

```
    profileForm = new FormGroup({
        firstName: new FormControl(''),
        lastName: new FormControl(''),
        pass: new FormControl(''),
    });
```
```
<GridLayout>
    <StackLayout [formGroup]="profileForm" class="page">
        <Label text="pass" textWrap="false"></Label>
        <Switch checked="false" formControlName="pass"></Switch>
        <Label text="firstName" textWrap="false"></Label>
        <TextField text="" hint="" secure="false" autocorrect="false"
            formControlName="firstName"></TextField>
        <Label text="lastName" textWrap="false"></Label>
        <TextField text="" hint="" secure="false" autocorrect="false"
            keyboardType="number" formControlName="lastName"></TextField>
    </StackLayout>
</GridLayout>
```

**Sample project**

 [Playground](https://play.nativescript.org/?template=play-ng&id=pkNHQE&v=2)

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1745
