### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by mchallenger88** [NativeScript/NativeScript#6935]
Installing nativescript on a new windows computer. Getting this error on npm install:

npm ERR! Unexpected end of JSON input while parsing near '...1","moment":"2.10.6",'

**Comment by tsonevn** [comment]
Hi @mchallenger88,
Can you provide more info about the steps that you have followed while installing NativeScript as well as the full error log from the console?

**Comment by mchallenger88** [comment]
I ran this command: npm install -g nativescript.

[2019-02-20T09_38_57_958Z-debug.log](https://github.com/NativeScript/NativeScript/files/2884085/2019-02-20T09_38_57_958Z-debug.log)

**Comment by mchallenger88** [comment]
Any thoughts?

**Comment by mchallenger88** [comment]
So I thought I'd trick the system and install N by installing Sidekick. Same error. I'm guessing there's a problem with the last commit.

**Comment by mchallenger88** [comment]
npm cache clean --force worked to clear the error.
