### ISSUE TITLE
Disable Event pinch on Calendar

### ISSUE THREAD

**Issue by xavierburzig** [NativeScript/NativeScript#6936]
Hi everybody, 

The problem is simple, I can't deactivate or disable the GestureType pinch on the Calendar.
I found a workaround for the swipe one but I can't find one for the pinch.

Solution could be a simple boolean to add in the html balise to activate or not the different events

I tried to work around a bit with a possibility to disabled the zoom like this
`@ViewChild('myCalendar') calendar: RadCalendarComponent;
setTimeout(() => {
      this.calendar.nativeElement.on(GestureTypes.pinch, function (arg: PinchGestureEventData) {
        if (isAndroid) {
          this.calendar.nativeElement.android.getSettings().setBuiltInZoomControls(false);
          this.calendar.nativeElement.android.getSettings().setDisplayZoomControls(false);
        } else {
          this.calendar.nativeElement.ios.scrollView.minimumZoomScale = 1.0;
          this.calendar.nativeElement.ios.scrollView.maximumZoomScale = 1.0;
          this.calendar.nativeElement.ios.scalesPageToFit = false;
          this.calendar.nativeElement.ios.scrollView.bounces = false;
        }
      });
    }, 100);`
I also tried a lot of differents stuff like this and with the interception of the rotation event but nothing is actually working as I except it to.

`
 this.calendar.nativeElement.android.getSettings().allowPinchZoom.isEnabled = false;
 this.calendar.nativeElement.ios.getSettings().allowPinchZoom = false;
 this.calendar.nativeElement.off(GestureTypes.pinch, (arg: PinchGestureEventData) => {
 });
this.calendar.nativeElement.off(GestureTypes.pinch);
`
If you could help me or provide a feature could be very appreciable.

PS: I'm working with Angular 

I actually found a solution working on android but not not on ios platform 

``this.calendar.nativeElement.android.getGestureManager().setPinchCloseToChangeDisplayMode(false);
this.calendar.nativeElement.android.getGestureManager().setPinchOpenToChangeDisplayMode(false);``

ios says that he doesn't know the getGestureManager() method

In advance Cheers

Xavier

**Comment by NickIliev** [comment]
This issue was moved to telerik/nativescript-ui-feedback#1027
