### ISSUE TITLE
Alert dialog cannot be shown while modal dialog is being shown on iOS

### ISSUE THREAD

**Issue by erkanarslan** [NativeScript/NativeScript#6939]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.1
 - Cross-platform modules: 5.0.5
 - Android Runtime: 5.1.0
 - iOS Runtime: 5.1.1
 - Plugin(s): Unrelated

**Describe the bug**
Alert dialog cannot be shown while modal dialog is being shown on iOS.

**To Reproduce**
Open a modal. After modal is open, show an alert dialog inside that modal's component. It doesn't show an alert dialog even though it works in Android.

**Expected behavior**
It should show an alert box.

**Comment by slolam** [comment]
@NickIliev, 

I too have the same issue and I have a little more information. The alert works fine if it's the first modal dialog displayed on the page. If I open a subsequent modal dialog on top a modal dialog, it fails to open the alert() or confirm() on iOS. 

Here is the playground link https://play.nativescript.org/?template=play-ng&id=GeR8Q4&v=2

**Comment by erkanarslan** [comment]
I still have this problem. I cannot show an alert dialog on top of a modal view and it is the only modal in the screen at the moment.

**Comment by slolam** [comment]
@erkanarslan, it is fixed and the PR has been approved. Waiting to be merged and released.

**Comment by erkanarslan** [comment]
But it seems that this fixes the problem if a modal is opened on top of an another modal. I only open a single modal and cannot show an alert on that modal. I think this won't fix my problem.
