### ISSUE TITLE
<Button> backgroundImage breaks touchable effect

### ISSUE THREAD

**Issue by flddr** [NativeScript/NativeScript#6940]
Hi!

I want to have an `image button`: including optical effects when clicking an image.

As far as i can set those properties on a `Button`, the `backgroundImage` breaks it touchable effect. I have tried this some years ago, but it seems the same today. Is it a bug? I did not found anything related and i am not sure why this should not work; the touchable effect shouldn't be affected here?

How do i build an `image button` then? Especially: an circle image button with `borderRadius` set to be a `circle` (like typical user icon today)?

Thanks

**Comment by NickIliev** [comment]
The native ripple effect is, in fact, working with drawables. So when you introduce a new drawable background (through the background-image property) you will lose the native ripple effect. This is a known limitation. One way to overcome this is to use [nativescript-ripple](https://www.npmjs.com/package/nativescript-ripple) to apply custom ripple effect.

**Comment by flddr** [comment]
Thank you very much :+1:
