### ISSUE TITLE
resolve reduced module path

### ISSUE THREAD

**Issue by flddr** [NativeScript/NativeScript#6941]
Hi!

_NS_ has a great API / concept - i like it really much :1st_place_medal: 

But i feel, the following could be reduced in most cases:

Actually, _NS_ resolves

`views/home-page` automatically, to `views/home-page.xml` etc.

Now, in real development, the paths are more like:

`views/home-page/home-page`
`views/another-page/another-page`
... and so on.

Mostly, this can be reduced to `views/another-page` if in `views/another-page` is `/another-page.xml` - and so on.

This would reduce coding and typing a much and should only be problematic in very small cases. It could be handled automatically, if `views/another-page` is a folder and there is nothing else than `/another-page.xml|.css|.js` in there and wouldn't affect an full set module-path at all.

What do you think?

**Comment by NickIliev** [comment]
@flddr thank you for your interest in NativeScript and suggestion.

NativeScript provides different flavors like plain JS, TypeScript, Angular and Vue (and even code sharing). That said you must consider that the different flavors come with different architectures. While in the Core frameworks (plain JS and TypeScript) you can use MVVM and create view-models which can contain files like `main-view-model.ts` and they can be inside the folder `views/home-page`. On Angular, you have services which also can be part of the component folder (or even you could have a folder that contains a lazily loaded module). We also use models almost in every flavor (e.g. like``item.ts`) which again in some cases can be accessed from the folder. 

All that said it is not just the Layout and the code behind files that can be part of your subfolder. You could also have JSON files or something different. 

The above plus the fact that we should also support resolving module resolution and paths for the different optimizations (e.g. like Webpack) is the main reasons why we stick to the current module resolution. 

In fact, the **file** resolution is how most of the Node..js require is meant to work ([here ](https://medium.freecodecamp.org/requiring-modules-in-node-js-everything-you-need-to-know-e7fbd119be8)for details)

```
// Requiring a module in Node isn’t that complicated of a concept.

const config = require('/path/to/file');
```

**Comment by flddr** [comment]
Thanks for your great explanation :+1:
