### ISSUE TITLE
Please bring back support for Windows 10 

### ISSUE THREAD

**Issue by steskalja** [NativeScript/NativeScript#6943]
Please bring back the Windows 10 runtime for NativeScript. https://www.nativescript.org/blog/nativescript-runtime-preview-for-windows-10 This would be a huge opportunity for desktop/tablet app written in nativescript. Based on the latest stats Windows and Android are neck and in terms of overall OS marketshare mobile/tablet/desktop, and of the Windows of Windows 10 is over 50% of that usage. You have an opportunity to create native apps for another 1billion devices.

**Comment by NathanaelA** [comment]
@steskalja - With code sharing; using Angular or VueJS you can easily create shared application code bases.  In fact if you use our (nStudio's) [xplat](https://nstudio.io/xplat) platform; you can actually create web, electron (i.e. mac and windows), NativeScript and a couple other platforms all from the same code base.

**Comment by NickIliev** [comment]
As @NathanaelA you already have solutions for creating web + mobile application while using one code base (xplat and Code Sharing). Learn more about Code Sharing with Angular [here](https://docs.nativescript.org/code-sharing/intro).

Closing as a duplicate to [https://github.com/NativeScript/NativeScript/issues/254](https://github.com/NativeScript/NativeScript/issues/254) and [https://github.com/NativeScript/NativeScript/issues/27](https://github.com/NativeScript/NativeScript/issues/27)
