### ISSUE TITLE
RadCartesianChart and RadPieChart don't update when an item has changed.

### ISSUE THREAD

**Issue by Walon1998** [NativeScript/NativeScript#6957]
**Environment**
 - CLI: 5.2.0
 - Cross-platform modules: 5.3.0
 - Android Runtime: 5.3.0
 - iOS Runtime: 5.2.0
 - Plugin(s):
 nativescript-ui-chart:  3.11.1    
 nativescript-angular:  7.2.2

**Describe the bug**
On Nativescript with Angular the RadCartesianChart and RadPieChart don't update when an item has changed. I want the user to be able to change the properties dynamically. On other components like RadListView or ListView it works as expected.

**To Reproduce**
Build a component with a RadCartesianChart or a RadPieChart and change one property of an item.

**Expected behavior**
RadCartesianChart and RadPieChart should update dynamically if a property of an item has changed. A cool additional feature would be animations, for example to see the bars grow or shrink if valueProperty of an item has changed.

**Sample project**
https://play.nativescript.org/?template=play-ng&id=S5YtL2&v=2
Click on the change button and see how nothing changes!

**Additional context**
I could only test it with Angular and Android. I don't know if other platforms are affected as well.

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#1030
