### ISSUE TITLE
webview video event "onShowCustomView" is firing on fullscreen but when I go back to small screen no listner works

### ISSUE THREAD

**Issue by lettertoamit** [NativeScript/NativeScript#6960]
webview video event "onShowCustomView" is firing on fullscreen but when I go back to small screen no listner/event works.kindly help. I am stuck with this issue in nativescript.things working in android.

```
function onWebViewLoaded1(webargs, url) { 
    var page = webargs.object.page; 
    var webview = webargs.object;    
    var customViewContainer = view.getViewById(webview, 'singleimgpopup');
    var viewr = view;
 

var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var MyWebChromeClient = /** @class */ (function (_super) {
    __extends(MyWebChromeClient, _super);
    function MyWebChromeClient() {

        var _this = _super.call(this) || this;
        return global.__native(_this);
    }
    MyWebChromeClient.prototype.onShowCustomView = function (view, callback) { 
        
         // Store the view and its callback for later (to kill it properly)
        if(this.mCustomView != null){
            callback.onCustomViewHidden(); return
        }
       this.mCustomView = view;
       this.mCustomViewCallback = callback;
       console.log('fullscreen');
    };
    MyWebChromeClient.prototype.onHideCustomView = function () { 
         console.log("this2");
        _super.prototype.onHideCustomView.call(this);
        _super.prototype.mCustomView = null;
    };
    return MyWebChromeClient;
}(android.webkit.WebChromeClient));

    
   
    webview.android.getSettings().setJavaScriptEnabled(true);
    webview.android.getSettings().setAppCacheEnabled(true);
    webview.android.getSettings().setBuiltInZoomControls(true); 
    webview.android.getSettings().setSaveFormData(true);
     let myWebChromeClient = new MyWebChromeClient();
    webview.android.setWebChromeClient(myWebChromeClient); 
    
    // console.log("1=====================url",url);
    // webview.android.loadUrl(url); 
}
```

**Comment by lettertoamit** [comment]
onShowCustomView and onHideCustomView works togeather . whe i try to come back to small screen . nither of function is called .

**Comment by tsonevn** [comment]
Hi @lettertoamit,
I tested the described scenario, however, I was unable to recreate an issue with the `onShowCustomView` and `onHideCustomView`. For your convenience, I am attaching my test project. When I request fullscreen mode for the video the `onShowCustomView` listener is fired as expected, then when the `onCustomViewHidden` is called the `onHideCustomView` listener is fired as well. Check out the attached demo and make the needed changes, that will allow me to recreate the problem.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/2900315/Archive.zip)

**Comment by lettertoamit** [comment]
@tsonevn   ok let me check you code and ping you in few min

**Comment by lettertoamit** [comment]
Hi there it this code not working on my end my video url is https://player.vimeo.com/video/302826331?playsinline=1

**Comment by lettertoamit** [comment]
> 
> 
> Hi @lettertoamit,
> I tested the described scenario, however, I was unable to recreate an issue with the `onShowCustomView` and `onHideCustomView`. For your convenience, I am attaching my test project. When I request fullscreen mode for the video the `onShowCustomView` listener is fired as expected, then when the `onCustomViewHidden` is called the `onHideCustomView` listener is fired as well. Check out the attached demo and make the needed changes, that will allow me to recreate the problem.
> 
> [Archive.zip](https://github.com/NativeScript/NativeScript/files/2900315/Archive.zip)

Hi there it this code not working on my end my video url is https://player.vimeo.com/video/302826331?playsinline=1

**Comment by lettertoamit** [comment]
i have tried with youtube video too , its not working 

the output is  

![capture](https://user-images.githubusercontent.com/11607454/53337366-352a8e80-3927-11e9-948a-1e75c4686514.PNG)

**Comment by lettertoamit** [comment]
I am not able to catch instance/event/listner  on "EXIT FULLSCREEN"

**Comment by chintan-snv** [comment]
Ohh strage @lettertoamit , I am also facing the same issue since last 6 days. I guess you have tried all the solutions given by @tsonevn, but none was working for you.

@tsonevn Can you please help me on this.

**Comment by tsonevn** [comment]
Hi @lettertoamit,
The only changes that I have made are inside the `main-page.xml` and `main-page.js`. Regarding the icon, you can try adding a [tap event](https://docs.nativescript.org/core-concepts/events#adding-an-event-listener-using-javascripttypescript) listener.
@chintan-snv Can you send us a demo project, that demonstrates the issue on your side?

**Comment by lettertoamit** [comment]
onTap listner on webview?

**Comment by lettertoamit** [comment]
> 
> 
> Hi @lettertoamit,
> The only changes that I have made are inside the `main-page.xml` and `main-page.js`. Regarding the icon, you can try adding a [tap event](https://docs.nativescript.org/core-concepts/events#adding-an-event-listener-using-javascripttypescript) listener.
> @chintan-snv Can you send us a demo project, that demonstrates the issue on your side?

Can you please eloborate more i am not able to get

**Comment by chintan-snv** [comment]
Actually what my project doing is, it's making iframe itself using web view, so we simply don't have control on any button placed on iframe in manner to programming. so can you please guide me, if there is any way to control those events programmatically, say if I do volume up, I should able to trigger an event there, if I do full screen, I should able to trigger an event. and so on.

**Comment by tsonevn** [comment]
@lettertoamit,
Can you send me your project or sample one that can be used for debugging and shows the view that you are loading when the fullscreen mode is requested? 
@chintan-snv, I am not sure if you can control the iframe programmatically(e.g. to change the volume). I would suggest checking the https://github.com/nstudio/nativescript-videoplayer, that can help in your case.

**Comment by lettertoamit** [comment]
these are my three files i am working on you can try pasting on code 


[videosingle-model.zip](https://github.com/NativeScript/NativeScript/files/2900861/videosingle-model.zip)

**Comment by snvankit07** [comment]
> @lettertoamit,
> Can you send me your project or sample one that can be used for debugging and shows the view that you are loading when the fullscreen mode is requested?
> @chintan-snv, I am not sure if you can control the iframe programmatically(e.g. to change the volume). I would suggest checking the https://github.com/nstudio/nativescript-videoplayer, that can help in your case.

Same Kind Of Issue i am Also facing  WIth "Vimeo Player" Zoom in/Zoom Out

**Comment by lettertoamit** [comment]
@tsonevn  did you get a chance to view my code ?

**Comment by tsonevn** [comment]
Hi @lettertoamit, 
I reviewed the attached files. If I understand correctly, you are navigating to another page, when the onShowCustomView is fired. Perhaps, inside the second page, you are loading another WebView with a fullscreen view(due to the missing files for the second page, I can not verify if this is so). Regarding the icon tap, if we are talking about the zoom out icon of the `iframe`, shown in the WebView, I am not sure that you can handle the tap event inside the `iframe` at all. 
I would suggest using `nativescript-videoplayer`. You can create your own control bar to play, pause the video and for requesting the fullscreen mode(you can use Button component provided by tns-core-modules). When a fullscreen mode is requested, you can stretch the video on the screen by changing the height and width of the `Video` element provided by  `nativescript-videoplayer.`

**Comment by lettertoamit** [comment]
@tsonevn  :-- hi just ignore  config.Navigate("home/a",webargs,url); this line of code it was for running you archive code , temporarily , Then what result you can analyse

**Comment by tsonevn** [comment]
Hi @lettertoamit,
Please, send me a runnable sample project, that shows me the, what you are trying to achieve and will help me in the debugging.
Also, did you check the `nativescript-videoplayer` and whether it works in your case?

**Comment by lettertoamit** [comment]
hi there , 
although nativescript-videoplayer does not give full screen facility in android ,  i have fixed it and written code using  https://stackoverflow.com/questions/54864118/webview-video-event-onshowcustomview-is-firing-on-fullscreen-but-when-i-go-bac  for adding full screen button. 
you can use it when needed.

**Comment by tsonevn** [comment]
Hi @lettertoamit,
 I am glad to hear that you have solved your case. Considering that,  I think that we can close this issue.
