### ISSUE TITLE
iOS RadDataForm MultilineText UI Issues

### ISSUE THREAD

**Issue by CaptainDingle** [NativeScript/NativeScript#6964]
**Environment**
 - CLI: 5.2.0
 - Cross-platform modules: 5.2.1
 - Android Runtime: 5.2.1
 - iOS Runtime: 5.2.0

**Describe the bug**
On iOS only, the RadDataForm Multilinetext control is not usable. There are 2 distinct issues. 

Issue 1:  When the label is configured on the left position(default), the MultilineText control correctly grows for each new line. However, you cannot then tap back into the text to edit what you already typed. The tap action sometimes works at the very beginning of the first sentence but no where else.

Issue 2: When the label is configured at the top position, the MultilineText control does not grow at all for additional lines correctly so you cannot see what you typed.

On Android, neither of these issues exist.

**To Reproduce**
Add MutilineText control to page with label positioned either at left (default) or on top (via CSS). Type several lines of text.

**Expected behavior**
As on Android, text control should grow as lines are added. You should also be able to tap back into the control to edit text in any spot.

**Sample project**
Link to Playground that demonstrates both issues:
https://play.nativescript.org/?template=play-ng&id=JBoH3l&v=76

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#1033
