### ISSUE TITLE
WKWebview with custom navigation & ui delegate

### ISSUE THREAD

**Issue by tdhman** [NativeScript/NativeScript#6969]
**Is your feature request related to a problem?**

The problem is that I cannot find any method to:

- Prevent opening any external links in a webview.
- Prevent peek preview with 3D touch in webview.
- Use custom view controller to open custom scheme in webview.

using the current webview component.

**Describe the solution you'd like**

- Ability to create webview with custom delegates: `WKNavigationDelegate` && `WKUIDelegate`.
- Allow to create wkwebview with custom `WKWebViewConfiguration`

**Describe alternatives you've considered**

I take a look at the plugin `https://github.com/triniwiz/nativescript-webkit-webview` that make an alternative webview of the default WebView with custom delegate. However, it still not have the ability to add the delegates by app client. Every delegate must be set before webview created.

What I'm thinking of is a something like a callback listener protocol for each delegate method of webview which allow to detect if any delegate method has been invoked. Something like: 

```WebView
export interface TNSWebViewDelegate {
  shouldAllowNavigation(url: string, type: string): boolean;
  shouldDisplayPreviewFor(url: string): boolean;
  shouldCreateWebviewForExternalLink(url: string): any;
  
  didStartProvisionalNavigation?(url: string): void;
  didNavigationAction?(url: string, type: string, success: boolean): void;
  didFinishNavigation?(url: string): void;
  didFailNavigation?(url: string, error?: string): void;
  didCloseWebview?(url: string): void;
 ...
}

class WKUIDelegateImpl extends NSObject implements WKUIDelegate {
  public _listener: TNSWebViewDelegate;
  // for example, call the listener protocol that will be implemented in app
  public webViewDidClose(webView: WKWebView) {
    this._listener && this._listener.didCloseWebview(webView.URL.absoluteString);
  }
}

export class WebView extends WebViewBase {
...
 set delegateListener(listener: TNSWebViewDelegate) {
    this._delegate._listener = listener;
    this._uiDelegate._listener = listener;
  }

  get delegateListener(): TNSWebViewDelegate {
    return this._delegate._listener || this._uiDelegate._listener
  }
....
}
```

Then, use in app:

```
class TNSWebViewDelegateImpl implements TNSWebViewDelegate {
   // implement the protocol methods here
}
let webView = <WebView>page.getViewById('wv');
webView.delegateListener = new TNSWebViewDelegateImpl();
```

Any other idea to add the delegate to the current webview component? 
Thanks for any help!

**Comment by NickIliev** [comment]
@tdhman [in this thread](https://github.com/NativeScript/NativeScript/issues/6725#issuecomment-449306078) you can find a test app that demonstrates how to overwrite the delegate method. 
Closing the issue as how-to related but do let us know if you still need assistance.
