### ISSUE TITLE
app-root frame is new created on app resume with launcher icon

### ISSUE THREAD

**Issue by matecode** [NativeScript/NativeScript#6977]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.2.0
 - Cross-platform modules: frame, page
 - Android Runtime: 5.2.0
 - iOS Runtime (if applicable):
 - Plugin(s): none

**Describe the bug**
We found a problem on serveral getFrameById refrences, where nothing happened with our navigate calls. So i investigated the cause and i found the following problem:
- we have a frame as root with id='root-fame' where we want to navigate on in later states of the app
- if the user leaves the app via "home" of android and resume the app with launcher icon (not recent tabs) the root-frame is new instantiated (with new dom id)
- if we call getFrameById('root-frame') the old instance is given

**To Reproduce**
I created a playgound app to reproduce, but you cannot reproduce the bug there because you have to click on launcher icon of your app. therefore download and extract it, build and run on android
To show the behaviour the sample app logs the domId of frame via loaded-Event of the frame and also via the button.

**Expected behavior**
The app should behave exactly as resuming via "recent apps tab"

**Sample project**
https://play.nativescript.org/?template=play-js&id=nimXLJ&v=2

**Comment by NickIliev** [comment]
@matecode thank you for reporting this one - confirming the behavior when returning to the app via the launcher icon. We will discuss the scenario and I will post any related info here as soon as we have more insights. Likely related to [the specifics in Android relaunch](https://medium.com/@elye.project/three-important-yet-unbeknown-android-app-launcher-behaviors-part-2-139a4d88157)

**Comment by NickIliev** [comment]
@matecode it seems that the behavior is expected on Android -  try setting the `launchMode` in AndroidManifest to `singleTask` (see [here ](https://developer.android.com/guide/topics/manifest/activity-element)for details)
