### ISSUE TITLE
Button attribute backgroundSize, backgroudRepeat, backgroundPosition don't work

### ISSUE THREAD

**Issue by boggddan** [NativeScript/NativeScript#6978]
Hello, 
I use nativescript-vue.
Could help me. *Button*  attributes: **backgroundSize**, **backgroudRepeat**, **backgroundSize** don't work

```html
<Button
backgroundRepeat="no-repeat" 
backgroundSize="contain"
backgroundPosition="center" 
 />
```

[reproduce bug playground](https://play.nativescript.org/?template=play-vue&id=9rqSC3&v=26)

But if you set them through a class or style attribute, then it works.

Thank's

**Comment by tsonevn** [comment]
Hi @boggddan,
I was able to recreate the problem in a [non-Vue project](https://play.nativescript.org/?template=play-tsc&id=FvaX1m). I will mark the issue as a bug and we will investigate it further.
