### ISSUE TITLE
Excessive logs

### ISSUE THREAD

**Issue by jinusean** [NativeScript/NativeScript#6980]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  5.2.0
 - Cross-platform modules:
 - Android Runtime: 5.2.0
 - iOS Runtime: 5.2.0
 - Plugin(s):

How can I prevent application logs in the console output? 
```
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> CreateElement(NativePage)'
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> CreateElement(nativeflexboxlayout)'
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> CreateElement(nativegridlayout)'
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> CreateElement(nativelabel)'
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> AppendChild(ElementNode(nativegridlayout), ElementNode(nativelabel))'
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> CreateElement(nativestacklayout)'
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> CreateElement(nativebutton)'
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> AppendChild(ElementNode(nativestacklayout), ElementNode(nativebutton))'
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> CreateElement(nativebutton)'
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> AppendChild(ElementNode(nativestacklayout), ElementNode(nativebutton))'
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> CreateElement(nativebutton)'
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> AppendChild(ElementNode(nativestacklayout), ElementNode(nativebutton))'
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> CreateElement(nativebutton)'
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> AppendChild(ElementNode(nativestacklayout), ElementNode(nativebutton))'
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> CreateElement(nativebutton)'
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> AppendChild(ElementNode(nativestacklayout), ElementNode(nativebutton))'
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> AppendChild(ElementNode(nativegridlayout), ElementNode(nativestacklayout))'
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> AppendChild(ElementNode(nativeflexboxlayout), ElementNode(nativegridlayout))'
CONSOLE LOG file:///app/vendor.js:33228:14: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> AppendChild(ElementNode(nativepage), ElementNode(nativeflexboxlayout))'
```

**Comment by tsonevn** [comment]
Hi @jinusean,
Can you provide more info, why you want to remove the logs from the console? Keep in mind that the console logs will be disabled when the app is built in production.

**Comment by jinusean** [comment]
@tsonevn is it possible to disable the console logs for the sampled output?

**Comment by felipebueno** [comment]
Same problem here.

Is there an option to turn off NSVue logging? It makes if difficult to debug my app.

**Comment by jinusean** [comment]
@tsonevn I don't want to remove all logs, just the view related ones. The sample output is just noise imo. I can tell that the elements loaded simply by looking at the simulator, and it makes it difficult for me to track down any of my own log statements.

**Comment by ExcelNet-Public** [comment]
In total agreement here that this makes debugging much more difficult.  An option of some sort to disable the CreateElement / AppendChild messages would be welcomed.  Through some sort of flag of course to enable should they be needed but at this point they seem clutter looking for real console log messages.

Thanks!

**Comment by NickIliev** [comment]
@jinusean @ExcelNet-Public the better place for this issue would be the [nativescript-vue](https://github.com/nativescript-vue/nativescript-vue) repository where the Vue.js implementation is being handled (the excessive logs seem entirely Vue related).

**Comment by HugoAntares** [comment]
https://github.com/nativescript-vue/nativescript-vue/issues/479
