### ISSUE TITLE
Parents Conditional expression dont work under ListView and Repeater

### ISSUE THREAD

**Issue by rakeshgirase** [NativeScript/NativeScript#6981]
**Environment**
 - CLI: 5.2.0
 - Cross-platform modules: 5.2.1 
 - Android Runtime: 5.2.0
 - iOS Runtime: 5.2.0

**Describe the bug**
$parents['ListView'] or $parents['Repeater'] dont work as expected when used in conditional expression.

**To Reproduce**
Run following playground example:
https://play.nativescript.org/?template=play-tsc&id=phg6fV&v=314

**Expected behavior**
$parents['ListView'] or $parents['Repeater'] should work fine even when used as conditional operations:
**Sample project**
Following is a playground example to replicate this issue
https://play.nativescript.org/?template=play-tsc&id=phg6fV&v=314

**Comment by tsonevn** [comment]
Hi @rakeshgirase,
Thank you for the provided sample project.
I was able to recreate the problem and will mark the issue as a bug. At this time I would suggest keeping track on the issue for further info.
