### ISSUE TITLE
Remove Button text fade effect on Tap [iOS]

### ISSUE THREAD

**Issue by chrisalexqm** [NativeScript/NativeScript#6982]
**Environment**
 - CLI: NativeScript Sidekick Blank Template

**Describe the bug**
Hi, I'm new to NativeScript! I was looking for a problem similar to mine but I could not find it, so I decided to publish it.

I'm styling the native button with CSS to have the same design in iOS as in Android. But in iOS the button has a fade effect in the text when I press the button.

I want to remove that fading effect from the text, I tried with the highlighted selector but it does not work.

I will be very grateful if you help me.

**Comment by tsonevn** [comment]
Hi @chrisalexqm,
For disabling the highlight control state for iOS, you need to change the button's type to Custom. The type of the button can be changed only initial time, regarding that, you need to set the new type inside the `tns-core-modules/ui/button/button.ios.js` file. For example:
```
    Button.prototype.createNativeView = function () {
        return UIButton.buttonWithType(0);
    };
```
For more info, check out this thread in [StackOverflow](https://stackoverflow.com/a/2259919/6133327). Also, after you've changed the type to `custom`, you need to set up the component text color.
```
button{
    color:green;
}
button:pressed{
     color: green; 
}
```
