### ISSUE TITLE
Android: Crash with "markingMode: none" and "ngFor" with binding 

### ISSUE THREAD

**Issue by jpierront** [NativeScript/NativeScript#6983]
**Environment**
 - CLI: 5.2.0
 - Cross-platform modules: 5.2.2
 - Android Runtime: 5.2.1

**Describe the bug**
- With "markingMode: none", errors "Attempt to use cleared object reference" occur when I change the background color of an element in my app with a css class name. ([class.element-active]="...")
- It doesn't seems to happen when I change the color or the opacity, only the background-color.
- It doesn't seems to happen when I use "[style.background-color]=..."
- My app freeze too often without the "markingMode: none"

I don't know if it's related to NativeScript or NativeScript-Angular

**To Reproduce**
- I did not succeed in reproducing it on a blank app, but the garbage collector is probably less often triggered with an empty app.

Do you have any tips to help test this kind of case?

**Expected behavior**
No crash ;-)

**Sample project**
```
export class MyComponent {
    public activeElement: Element | null = null;
    public elements: Element[] = [...];
}
```
```
.element {
    background-color: white;
}
.element-active {
    background-color: red;
}
```
```
<Label
    [text]="element.title"
    (tap)="activeElement = element"
    class="element"
    [class.element-active]="element === activeElement"
    *ngFor="let element of elements"
></Label>
```
**Additional context**

```
ERROR Error: com.tns.NativeScriptException: Attempt to use cleared object reference id=4370
    com.tns.Runtime.getJavaObjectByID(Runtime.java:1006)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
    com.tns.Runtime.callJSMethod(Runtime.java:1070)
    com.tns.Runtime.callJSMethod(Runtime.java:1050)
    com.tns.Runtime.callJSMethod(Runtime.java:1042)
    com.tns.gen.java.lang.Object_vendor_177265_32_TouchListenerImpl.onTouch(Object_vendor_177265_32_TouchListenerImpl.java:18)
    android.view.View.dispatchTouchEvent(View.java:11772)
    android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
    android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
    android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
    android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
    android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.j...

ERROR CONTEXT {
  "view": {
    "def": {
      "nodeFlags": 9125889,
      "rootNodeFlags": 1,
      "nodeMatchedQueries": 0,
      "flags": 0,
      "nodes": [
        {
          "nodeIndex": 0,
          "parent": null,
          "renderParent": null,
          "bindingIndex": 0,
          "outputIndex": 0,
          "checkIndex": 0,
          "flags": 1,
          "childFlags": 9125888,
          "directChildFlags": 9125888,
          "childMatchedQueries": 0,
          "matchedQueries": {},
          "matchedQueryIds": 0,
          "references": {},
          "ngContentIndex": null,
          "childCount": 3,
          "bindings": [
            {
              "flags": 8,
              "ns": "",
              "name": "text",
              "nonMinifiedName": "text",
              "securityContext": 0
            },
            {
              "flags": 2,
              "ns": "",
              "name": "element-active",
              "nonMinifiedName": "element-active"
            }
          ],
          "b...
```

"element-active" is the added css class name containing a change of background-color.

**Comment by NickIliev** [comment]
@jpierront I've used your snippets [in this test app](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/NativeScript/issue-6983) (with[ `markingMode` set to `none`](https://github.com/NickIliev/NS-Issues-2019-I/blob/master/NativeScript/issue-6983/app/package.json#L4)) but I was also not being able to reproduce the issue with the blank app. 

Please try to isolate the issue in a sample app and if you are still hitting this one, share the source code for further investigation.

**Comment by jpierront** [comment]
I succeeded to reproduce it.
[MarkingModeNoneBackground.zip](https://github.com/NativeScript/NativeScript/files/2927122/MarkingModeNoneBackground.zip)

The second part (getContentParts) is only to generate heavy content.
`(<any>java).lang.System.gc();` is to try to force GC (I do not know if it's useful or not)
You can have to tap on links (0-9) a lot of time before crash. (sometimes 3, sometimes 50 ...)

**Comment by NickIliev** [comment]
@jpierront using your demo I am still not able to reproduce the issue  - I am testing on Nexus 5, Nexus 5x, Pixel and Pixel XL. Are you experiencing this one on a specific device, API level?

**Comment by jpierront** [comment]
Android Virtual Device
3.2'' QVGA (ADP2) 320x480
Oreo Android 8.1 x86 (API 27)
Emulated Performance: Automatic
512 RAM
32 VM heap
800 Internal Storage

**Comment by jpierront** [comment]
I succeed on Android 9 too with a similar config (API 28)

![image](https://user-images.githubusercontent.com/1228441/53816462-e488e600-3f63-11e9-8286-8022dee39698.png)

**Comment by jpierront** [comment]
I use `tns run android`

**Comment by jpierront** [comment]
- I succeeded to trigger the error on Android 8.1 and 9. (Demo App + My own App)
- I succeeded to trigger the error on Android 7.1 and 6.0. (But only on my own App for now and it took a while before triggering the error)
- I haven't succeeded yet to trigger the error on Android 4.4 and 5.1.

**Comment by jpierront** [comment]
I succeeded to trigger the error on Nexus 5 (Emulator, Android 8.1, 1536 Ram, 128 VM heap). (Demo App + My own App) (But I have to click 15 or 20 times on links with changing background)

**Comment by jpierront** [comment]
I have a new sample app that triggers the bug faster. (By changing a lot of background color every 100ms)

On Android 8.1, it take only 10 seconds on my computer. (Virtual Device: Nexus 5 or custom device)
On Android 9, it take less than 60 seconds on my computer.
On Android 4.4/5.1/6.0/7.1, no bug after 10 minutes of running (I can reproduce the bug only on my own app)

The delay will probably depend on the speed of your computer.

```
import {Component, OnInit} from '@angular/core';

@Component({
    selector: 'ns-app',
    moduleId: module.id,
    templateUrl: './app.component.html',
    styles: [`
        .mat-list-item {
            background-color: #ffffff;
        }

        .mat-list-item-active {
            background-color: #ffeeee;
        }
    `],
})
export class AppComponent implements OnInit {
    public static readonly MAX = 21;
    public elementsGrid: boolean[][] = [];
    public rows: string = '*,'.repeat(AppComponent.MAX);

    protected indexes = Array.from(Array(AppComponent.MAX).keys());

    public constructor() {
        let elementValue = true;
        for (let i in this.indexes) {
            const elementRow: boolean[] = [];
            for (let j in this.indexes) {
                elementRow.push(elementValue);
                elementValue = !elementValue;
            }
            this.elementsGrid.push(elementRow);
        }
    }

    public ngOnInit(): void {
        setInterval((): void => {
            this.update();
        }, 100);
    }

    protected update(): void {
        for (let i in this.indexes) {
            for (let j in this.indexes) {
                this.elementsGrid[i][j] = !this.elementsGrid[i][j];
            }
        }
    }
}
```
```
<StackLayout>
    <GridLayout [rows]="rows" [columns]="rows">
        <ng-container *ngFor="let elementsRow of elementsGrid; index as i">
            <ng-container *ngFor="let element of elementsRow; index as j">
                <Label [row]="i" [col]="j" text=" " class="mat-list-item" [class.mat-list-item-active]="element"></Label>
            </ng-container>
        </ng-container>
    </GridLayout>
</StackLayout>
```

**Comment by NickIliev** [comment]
@jpierront thank you for the dedicated time to isolate the case! I\ve embedded the above snippet in[ this test app](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/test/marking-mode-bgcolor) and can confirm that indeed there is a markingMode error manifestation on most Android devices (used Pixel and Nexus real devices for tests). Our Android developers will investigate the case further and we will post any related information as soon as we have more details to share.

**Comment by NickIliev** [comment]
@jpierront after some additional investigation I've managed to simplify the app and it seems that the issue is **not** related to CSS and setting background-color but to the Angular structural directive `ngFor`.


[Here is my [updated application](url)](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/test/marking-mode-bgcolor) which is hitting the very same issue without using any CSS but simply the `ngFor` directives. The same scenario is not reproducible if we substitute the `ngFor` directives with `Repeater`

Moving the issue (and updating the title) to the NativeScript Angular repository as it seems related to specific case where we are using binding with `ngFor` and `markingMode`

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#1756
