### ISSUE TITLE
Android: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentTransaction...

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/NativeScript#6984]
**Environment**

 - CLI: 5.2.1
 - Cross-platform modules: 5.2.1
 - Android Runtime: 5.2.0

**Describe the bug**

Randomly opening a modal will cause app to be unstable and subsequent modal opening will not work due to this stacktrace:

```
JS: ERROR Error: Uncaught (in promise): Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentTransaction android.support.v4.app.FragmentTransaction.add(android.support.v4.app.Fragment, java.lang.String)' on a null object reference
JS:     android.support.v4.app.DialogFragment.show(DialogFragment.java:159)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1070)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1050)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1042)
JS:     com.tns.gen.java.lang.Runnable.run(Runnable.java:16)
JS:     android.os.Handler.handleCallback(Handler.java:873)
JS:     android.os.Handler.dispatchMessage(Handler.java:99)
JS:     android.os.Looper.loop(Looper.java:193)
JS:     android.app.ActivityThread.main(ActivityThread.java:6669)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android....
```

**To Reproduce**

Just monkey test an Android app and open/close modals after navigating in/out of different sections/routes ... This is specifically related to Angular integration and may only happen more frequently with Angular integrations. I've seen this happen in every NativeScript Angular app at random.

**Expected behavior**

Modal's should never cause race condition issues with Android fragments and in the event they do, the framework should gracefully handle by doing what is necessary to not cause an error and allow app to proceed normally.

**Additional context**

I can demonstrate this issue via a screenshare in a project (which cannot be shared publicly).

**Comment by NickIliev** [comment]
@NathanWalker can you give us more details on what your exact scenario is? Are you using navigation inside your modals, or are you opening a single page modal with no navigation? Are these modals triggered from a TabView or from another specific layout? If using navigation are you having specific page transitions during the initial modal navigation? 

Isolating the case in a sample application with greatly help us to investigate the case as it seems that it is not happening in the common scenarios (e.g. using [this application](https://github.com/NativeScript/nativescript-angular/tree/master/e2e/modal-navigation-ng) as a test app I was unable to reproduce the issue). The test app is running nightly a number of tests against `latest` and `RC` modules so if you are experiencing the issue on every NativeScript Angular,  we are probably missing your specific case. in our tests

**Comment by NathanWalker** [comment]
Single page modal with no inner navigation (no router outlet or anything in it). 
Always encounter this at random and often eventually at anytime specifically when using a TabView based app but I’ve seen it at random with other non-tabview based apps as well.

More than likely this is often observed in more complex apps under some stress hence a playground app is not going to suffice or some simple app setup.

That being said I wish I could provide an exact repo however the fact this stack occurs at all should be problem enough. The framework should prevent this condition regardless of scenario in all cases.

**Comment by NickIliev** [comment]
Using[ this test app](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/NativeScript/issue-6984) (tabs with a modal being opened from the `browse` tab and about an hour long interactions on Nexus 5 and Pixel) I am not able to reproduce the issue. You can use it as a reference and let me know if there is something more specific that I need to implement/change in the related code (e.g.if the issue happens  with [specific modal dialog options](https://github.com/NickIliev/NS-Issues-2019-I/blob/master/NativeScript/issue-6984/src/app/browse/browse.component.ts#L20-L24) or on a specific API level). 
I absolutely agree that the stack occuring is an issue but without any proper steps to reproduce it would be hard for the developers team to investigate & resolve it so any related infromation is welcome.

**Comment by NathanWalker** [comment]
Thanks @NickIliev for creating that. I modified it locally to have all the tabs open the modal and declare the ModalComponent in the AppModule so it can be opened from any of the pages (which is more common case than they setup you provided) - in real world practice it's more rare that one page needs to open one modal and "only that one page" but rather many pages should be able to open that modal from anywhere - most common case is login/signup modal. Any tab page in that app would/could open that at anytime. If I'm able to repro in this isolated condition I will let you know.

/cc @DickSmith do you have any other details that would be pertinent here?

**Comment by NathanWalker** [comment]
Here's the sample you provided modified as mentioned: 
https://github.com/NickIliev/NS-Issues-2019-I/pull/1

**Comment by NathanWalker** [comment]
@NickIliev I have a lead on this. Looks like this is tied back to the `ViewContainerRef` issue here:
https://github.com/NativeScript/nativescript-angular/issues/1546

Long story short the requirement of a `ViewContainerRef` in Angular integration creates a troubling case of passing around the proper ViewContainerRef all the time which turns out in complex apps is quite a burden. My hope is that the `nativescript-angular` adapter could handle this better for the integration automatically to ease problems like this. Let's keep this open for a bit to see if certain repro could be provided eventually or if other details come to light but so far in my investigation seems to all point to cases where the `ViewContainerRef` is not correct leading to this troubling issue (similar problems can occur on iOS).

**Comment by AndreiGusa** [comment]
I get the same error when I'm switching from a second activity to main activity and try to open a modal. The View context becomes null for few seconds.

**Comment by randomCards** [comment]
same here.. but removing this two line in app.gradle 

renderscriptTargetApi 25
renderscriptSupportModeEnabled true

request by nativescript-blur, no more error and the modal works...

**Comment by NickIliev** [comment]
@NathanWalker @AndreiGusa  I've [tested the case with the latest modules](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/NativeScript/issue-6984) and the issue seems to have been resolved (at least it is not manifesting after numerous open/close tests of the modals). - can you please let me know if you are still experiencing this one?

**Comment by govi2010** [comment]
@NickIliev I am facing this issue in my app 

APP INFO: 
Nativescript: "6.5.0", 
tns-android: "6.5.3",
tns-ios: "6.5.2",
angular: "8.2.0"

```
Unhandled Promise rejection: java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.fragment.app.FragmentTransaction androidx.fragment.app.FragmentTransaction.add(androidx.fragment.app.Fragment, java.lang.String)' on a nul
l object reference ; Zone: <root> ; Task: Promise.then ; Value: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.fragment.app.FragmentTransaction androidx.fragment.app.FragmentTransaction.add(androidx.fragment.app
.Fragment, java.lang.String)' on a null object reference (file: node_modules\@nativescript\core\ui\core\view\view.android.js:492:0)
JS:     at (file: node_modules\@nativescript\core\ui\core\view\view-common.js:283:0)
JS:     at (file: node_modules\@nativescript\angular\directives\dialogs.js:99:0)
JS:     at (file: node_modules\@nativescript\angular\zone-js\dist\zone-nativescript.js:388:0)
JS:     at (file: node_modules\@nativescript\angular\zone-js\dist\zone-nativescript.js:138:0)
JS:     at (file:///data/data/com.consiliumsoft.beyondjustab...

```

this error occures when in the the app page navigated from A fream to B frame then again come to A frame then   
suspend and ressume it autometicaly navigate to B frame.

and the exception log is  generated in console.

**Comment by LouieTian0209** [comment]
I am facing this issue as well. For me this happens when I'm trying to open a modal page on app launch, the result would be this error message in console and modal page fails to open. If I, however, add a setTimeout for opening modal page on launch, everything is fine and this error won't show up.

**Comment by codealvarez** [comment]
> 

You're right. I had to set a timeout for one second and it worked as expected. Thanks!
