### ISSUE TITLE
Load a text file from a webview & nativescript code behind - it is not the same file which is loaded

### ISSUE THREAD

**Issue by MoorateeahTashil** [NativeScript/NativeScript#6989]
I am trying to read a file from a webview and push data into the file  through my nativescript app. But upon reading i found out that if i read from the webview , the file in the project (Desktop/Projects/Project_Name/path) is read whereas if i write in the file via the .ts code , it reads and update a file in file///data/data/0.nativescript........ 

Any help please?

**Comment by tsonevn** [comment]
Hi @MoorateeahTashil,
Can you send us a sample project, which demonstrates what you are trying to achieve and shows how you are reading a file from the WebView and how you are saving the data in an external file?

Thank you in advance for your cooperation.

**Comment by MoorateeahTashil** [comment]
from the indoor.ts file

   for (let beacon of beacons) {
            console.log("B: " + beacon.proximityUUID + " - " + beacon.major + " - " + beacon.minor + " - " + beacon.distance_proximity + " - " + beacon.rssi + " - " + beacon.txPower_accuracy );
            var d=Math.pow(10,((beacon.txPower_accuracy- beacon.rssi)/25));
            this.values.push(d);
            this.count++;
            if (this.count==5)
            {
                var sum=0;
                for(let i=0;i<this.values.length;i++)
                {
                    sum=sum+this.values[i];
                }
                //alert(sum/this.values.length+"\n");
                    var fs = require('file-system');

                  

                  fs.knownFolders.documents().getFile("app/app/indoor/distance.txt").remove()
                 .then((res) => {
                   }).catch((err) => {
                        console.log(err.stack);
                   });
               

                  fs.knownFolders.documents().getFile("app/app/indoor/distance.txt").writeText(5+"\n"+5)
                   .then(() => {
                       
                 }).catch((err) => {
                        console.log(err);
                });


                   
                sum=0;
                this.count=0;
            }
        }



from the html file

 
                function readTextFile()
                {
                     var req = new XMLHttpRequest();
                        req.onload = function(){

                                var allText = this.responseText;
                                var splittedtext=allText.split('\n');
                                   dn=splittedtext[0];
                                   de=splittedtext[1];
                                 
                                
                        };
                        req.open('GET', './distance.txt');
                        req.send();           
                }

**Comment by tsonevn** [comment]
Hi @MoorateeahTashil,
Thank you for the provided code snippets, however from the above-given code it is not clear, how the WebView component is involved in the case. It will be great if you can send us a sample project, which can be used for debugging and demonstrates the problem, you are facing.

**Comment by MoorateeahTashil** [comment]
@tsonevn  Thank you for your concern but i am using a .js file to read value .
