### ISSUE TITLE
Suggestion : Add image rotate left/right

### ISSUE THREAD

**Issue by stonecourier** [NativeScript/NativeScript#699]
Please add so functionality in the core code so users can rotate the images taken with the camera module.

I have posted code how to do it here, but it would be great if this was built in for others.

http://stonecourier.blogspot.com.au/2015/09/adding-image-rotate-with-nativescript.html

**Comment by bradmartin** [comment]
+1

**Comment by bradmartin** [comment]
Link to the idea: https://nativescript.ideas.aha.io/ideas/NS-I-62

I'd like to see the camera module support some of the options present in the Cordova plugin. I don't know the native aspects of achieving this but it would definitely improve the camera module to correct the orientation, allow cropping before using the image and so forth. Those two options would probably be the most beneficial and needed by those coming from a hybrid background.

**Comment by hshristov** [comment]
@stonecourier @bradmartin We have done this in the @next of widgets. So Image component now handles the rotation. Do you think this is enough?
