### ISSUE TITLE
mapViewDidFinishLoadingStyle missing from objc!MapKit.d.ts

### ISSUE THREAD

**Issue by Yermo** [NativeScript/NativeScript#6990]
(Is this the correct place to report issues with tns-platform-declarations?)

This method: https://mapbox.github.io/mapbox-gl-native/macos/0.3.0/Protocols/MGLMapViewDelegate.html#/c:objc(pl)MGLMapViewDelegate(im)mapView:didFinishLoadingStyle:

is not present in objc!MapKit.d.ts.

Is there some reason that it is not?

**Comment by tsonevn** [comment]
Hi @Yermo,
Following the provided info, I would guess that you are using the `nativescript-mapbox` plugin in your project and the following error (`mapViewDidFinishLoadingStyle missing from objc!MapKit.d.ts`) appears, when you try calling `mapViewDidFinishLoadingStyle`.

If this is the case, I would suggest opening a new issue in the https://github.com/EddyVerbruggen/nativescript-mapbox/issues repository.
Let me know if I am missing something or the issue you are facing is not related to the plugin mentioned above.

**Comment by Yermo** [comment]
my bad.
