### ISSUE TITLE
angular cli commands silently fails

### ISSUE THREAD

**Issue by MAXMASTER001** [NativeScript/NativeScript#6991]
**Environment**
os: Macos-Mojave;
node version: 10.15.2

Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.2.1
 - Cross-platform modules:
 - Android Runtime:5.2.0
 - iOS Runtime:5.2.2
 - Plugin(s): -

**Describe the bug**
I can't create components using angular cli ,
for example "ng g c home" command fails without giving any information.

**To Reproduce**

tns create secondapp
cd secondapp
ng g c home

**Expected behavior**
home component should be created.
**Sample project**

**Additional context**

a year ago i installed nativescript. played a bit. node version was 8.9.4. unistalling that version was hard. I switched to 8.9.4. 
 npm uninstall nativescript -g didnt completely remove nativescript. tns command was working.  ( maybe a cache issue)  ( I am using nvm as node version manger by the way). this might be the cause.

in the screenshot below i recognized this.. vscode complaning no" no such file or directory"
![image](https://user-images.githubusercontent.com/11816983/53871661-ba8bfe00-400d-11e9-948c-1668a977de21.png)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-schematics#199
