### ISSUE TITLE
Dialog and modal track state

### ISSUE THREAD

**Issue by vforv** [NativeScript/NativeScript#6995]
Is it possible currently to track state for dialogs and modals? 

For example when opens and close?

**Comment by tsonevn** [comment]
Hi @vforv,

In your case, you can create a flag which helps you detecting if the Modal view or dialog is opened/closed. For example:
```
    let isViewClosed = false;
    // ----------- Modal view -------------
    mainView.showModal(modalViewModulets, context, (username, password) => {
        isViewClosed = true;
    }, fullscreen);
    // ----------- Dialog -------------
    dialogs.alert("Test").then(()=>{
        isViewClosed = true;
    })


    if(isViewClosed){
        console.log("Modal view/ Alert - closed")
    }
```
For the modal view, you can also check if the private `_modal` property is initialised (if it is `undefined` or `null` - the modal view is closed, if not - it is opened). 
```
import {topmost} from "tns-core-modules/ui/frame";
console.log((<any>topmost().currentPage)._modal);
```

**Comment by vforv** [comment]
How to do that for promps?
