### ISSUE TITLE
android.view.WindowManager.LayoutParams.FLAG_SECURE not working on modal page

### ISSUE THREAD

**Issue by MetaiR** [NativeScript/NativeScript#7013]
I use this code to prevent user to make an screenshot from my app,
```
// prevent to take an screenshot
        app.android.startActivity.getWindow().setFlags(
            android.view.WindowManager.LayoutParams.FLAG_SECURE,
            android.view.WindowManager.LayoutParams.FLAG_SECURE
        );
```
it works perfectly for taking an screenshot and when I suspend the application (to see the list of opened application) it shows a black screen inside my app
this is what I talking about:
![photo_2019-03-09_20-24-18](https://user-images.githubusercontent.com/7807264/54074573-571dfc80-42a9-11e9-95ef-b7501ab75055.jpg)

the problem is: when I open a modal page it dosen't have the same behaviour and this is what happens:

![photo_2019-03-09_20-27-39](https://user-images.githubusercontent.com/7807264/54074608-d3b0db00-42a9-11e9-93ad-d5b2b3585302.jpg)

what goes wrong?

**Comment by tsonevn** [comment]
Hi @MetaiR,
I checked the case with our sample app - [nativescript-sdk-examples-js](https://github.com/NativeScript/nativescript-sdk-examples-js), however, was unable to recreate the issue. The only change that I've made is to set up the `FLAG_SECURE` flag inside the `main-page.js`.
**main-page.js**
```
....
var application = require("tns-core-modules/application"); 
function onNavigatingTo(args) {
    const page = args.object;
    const vm = new ListViewLinksModel({
        links: navigationLinks,
        actionBarTitle: "Cookbook"
    });
    application.android.startActivity.getWindow().setFlags(
        android.view.WindowManager.LayoutParams.FLAG_SECURE,
        android.view.WindowManager.LayoutParams.FLAG_SECURE
    );
    page.bindingContext = vm;
}
exports.onNavigatingTo = onNavigatingTo;
```

Regarding that, can you send us a sample project, that demonstrates the issue and can be used for debugging?

**Comment by MetaiR** [comment]
@tsonevn 
I use nativescript angular and put it on my app.component.ts -> ngOnInit().
sure I am going to put a sample for this issue

**Comment by tsonevn** [comment]
@MetaiR,
I rechecked the case with our [NativeScript Angular examples](https://github.com/NativeScript/nativescript-sdk-examples-ng), however I was unable recreate the issue with Angular as well. I am setting the flag in **app.component.ts** inside ngOnInit.
```
import { Component, AfterViewInit } from "@angular/core";
import { hasKey, getString, remove } from "tns-core-modules/application-settings";
import { RouterExtensions } from "nativescript-angular/router";
import * as app from "tns-core-modules/application";
import { DeepLinkData } from "./shared/deep-link-data";
declare var android:any;
....................

export class AppComponent implements AfterViewInit {
    constructor(private router: RouterExtensions) { }
    ngOnInit(){
        app.android.startActivity.getWindow().setFlags(
            android.view.WindowManager.LayoutParams.FLAG_SECURE,
            android.view.WindowManager.LayoutParams.FLAG_SECURE
        );
    }
    ........................
}

``` 
Can you send us a sample, where the issue can be recreated?
