### ISSUE TITLE
Animation speeds are inconsistent between Android and iOS

### ISSUE THREAD

**Issue by shiv19** [NativeScript/NativeScript#7014]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.2.2
 - Cross-platform modules: 5.2.2
 - Android Runtime: 5.2.1
 - iOS Runtime: 5.2.0
 - Plugin(s): N/A

**Describe the bug**
Animations on Android seem to finish faster than on iOS. With the same duration.

**To Reproduce**
https://play.nativescript.org/?template=play-js&id=ZFFAJB
Try on Android and iOS

**Expected behavior**
Animations should look the same on Android and iOS with a given duration.

**Sample project**
https://play.nativescript.org/?template=play-js&id=ZFFAJB

**Comment by NickIliev** [comment]
@shiv19 while testing on several Android and iOS devices the animation speed is consistent on all of them. Please check if you have a different settings for animation speed (e.g in the developer's option). If that is not the case, then let me know on what devices you are testing the scenario.

**Comment by shiv19** [comment]
@NickIliev
You are right. It had to do with the animation duration setting in developer options. On my android it was set to 0.5x

Thanks!
