### ISSUE TITLE
Closemodal navigate issue on ios

### ISSUE THREAD

**Issue by oncul** [NativeScript/NativeScript#7022]
I am using sidedrawer. When i open fullscreen modal and i trigger closecallback() or closemodal() parent page navigates its self. I am using typescript version.

I am using latest nativescript and tns core modules. i didnt tested on android.

**Comment by tsonevn** [comment]
Hi @oncul,
I tested the modal view with our [SDK examples](https://github.com/NativeScript/nativescript-sdk-examples-js/tree/master/app/ns-ui-category/modal-view), however, I was unable to recreate a similar issue. Can you send us a sample project, that can be used for reproducing the problem?

**Comment by oncul** [comment]
Thank you for testing. i think its my mistake.
