### ISSUE TITLE
Cant create new project (Angular Template)

### ISSUE THREAD

**Issue by anaszgh** [NativeScript/NativeScript#7023]
- CLI: 5.1.0

I'm trying to create a new project using the following command

`tns create [appname] --ng --appid [appid]`

but the following error message appears each time

`No matching version found for tns-template-hello-world-ng@5.1.3`

there is no other logs but the tns suggestion for the command.

I have other project that been initialized previously, building & running them working just fine.

**Comment by tsonevn** [comment]
Hi @anaszgh,
Try to [upgrade NativeScript CLI](https://docs.nativescript.org/releases/upgrade-instructions) to the latest available version  5.2.3 and check if the issue will appear again. I checked the case with the latest version and the project was created successfully while using `tns create [appname] --ng --appid [appid]` command.

**Comment by anaszgh** [comment]
Hello @tsonevn 

After taking a very long time executing the command, i have received the following message using the latest CLI Version.

`No matching version found for tns-template-hello-world-ng@5.2.2`

Please guide on how to provide you with more information, if there is a log file located somewhere in order to have a proper information regarding this issue.

**Comment by anaszgh** [comment]
@tsonevn It is working now, it was an issue with the proxy server blocking the requests to the server, but i think that error message should be more clear.
