### ISSUE TITLE
Add JSDoc comments to platform declarations

### ISSUE THREAD

**Issue by mudlabs** [NativeScript/NativeScript#7026]
Working with native APIs is improved with `tns-platform-declarations`. But would it be worth adding `JSDoc` comments to the declaration files?

Currently typing something like `AVPi` in **VSC** will see **intellisense** throw up `AVPictureInPictureController`, amongst others. But there's no detail given. If we added `JSDoc` comments **intellisense** could serve a lot more detail. Like to quick introduction the Apple developer docs uses etc...

**Comment by NickIliev** [comment]
@mudlabs the declaration files are generated [by automated tools that traverse the native APIs](https://github.com/NativeScript/NativeScript/tree/master/tns-platform-declarations#generate-android-dts-files). However, adding comments for each entry would be an enormously big task if done by hand. If you have ideas for adding the JSDoc comments automatically on-the-fly (during generation) we are open for suggestions and PRs.

**Comment by mudlabs** [comment]
Yes, I figured it would be a lot to do manually. Was thinking some kind of web scraper type deal.

**Comment by NickIliev** [comment]
@mudlabs, unfortunately, the native APIs are not open source and the documentation APIs are also under license restrictions so crawling the APIs is no viable option.

Closing this one as so far there is no other option apart from adding the comments manually (which is a no-go)
