### ISSUE TITLE
Can I add a view inside StackLayout dinamically?

### ISSUE THREAD

**Issue by danicomas** [NativeScript/NativeScript#703]
```js
	var v = view.getViewById(page, "kk");
	var myComponentInstance = builder.load({
			path: "~/views/page2",
			name: "page2"
	});
	console.log(myComponentInstance);
	console.log(v);
	v.addChild(myComponentInstance) //I have tried v.content = myComponentInstance but it doesn't work
```

```xml
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
  <Page.actionBar>
    <ActionBar title="Main"/>
  </Page.actionBar>
  <StackLayout id="kk">
  </StackLayout>
</Page>
```

The error is the following:
/app/tns_modules/ui/core/view-common.js:773:32: JS ERROR TypeError: view._inheritProperties is not a function. (In 'view._inheritProperties(this)', 'view._inheritProperties' is undefined)

**Comment by danicomas** [comment]
Related https://github.com/telerik/nativescript-ui-samples/issues/16#issuecomment-138865951

**Comment by enchev** [comment]
Please check our tests for more info:
https://github.com/NativeScript/NativeScript/blob/master/apps/tests/xml-declaration/xml-declaration-tests.ts#L95

https://github.com/NativeScript/NativeScript/blob/master/apps/tests/xml-declaration/mymodulewithxml/MyControl.xml

In this case "MyControl" is the XML file name.

**Comment by danicomas** [comment]
Oh well @enchev the path is without the file name.

**Comment by enchev** [comment]
Yep! Should we close this now?

**Comment by danicomas** [comment]
Solved

**Comment by emmanuel128** [comment]
@danicomas I'm changing the drawer contents successfully but the tap events doesn't work, any ideas?
