### ISSUE TITLE
Build for mobile breaks if imports in TS files are not relevant paths

### ISSUE THREAD

**Issue by vapits** [NativeScript/NativeScript#7030]
**Describe the bug**
When I try to build or run a mobile version of my web app which is builded with Angular via Nativescript I get multiple compiler errors like:

>src/app/search/search.module.ts(5,29): error TS2307: Cannot find module 'app/common/pipes/pipes.module'.

This doesn't happen when I import the files from a relative path. For example instead of: 
`app/common/pipes/pipes.module` if I do `../../../common/pipes/pipes.module` I will not get any errors.

Even that the fix seems easy this is something that I would prefer not to change as relative paths make our life more difficult if we want to refactor our app or move things around.

Does anyone has a solution with this? It happens only when I build the app with nativescript cli and not with angular cli.

**To Reproduce**
In any component import any other module or component you need with this way:
```
import { MyComponent } from 'app/path/my-component';
```
instead of:
```
import { MyComponent } from '../../path/my-component';
```

**Comment by NickIliev** [comment]
@vapits you have an alias in the `tsconfig` which you can use to pass the root application directory (not to be confused with the project's directory)

In the newer templates it looks like this:
```JSON
"paths": {
    "~/*": [
        "src/*"
    ]
}
```

That said you could do the following
```TypeScript
import { MyComponent } from '~/app/path/my-component'; // use tilde ~
```
