### ISSUE TITLE
Fixed height TextView inside ScrollView is not scrollable

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#7040]
_From @bhavincb on March 18, 2019 12:9_

**Environment**

 - Nativescript-Playgroud: 5.0.2
 
**Describe the bug**
when `TextView`  has fixed height and it is placed inside the ScrollView at the bottom of the content then when we type more line than the height it does scroll to bottom automatically. but to see the top content there is no way other than erasing the text. scrolling inside `TextView` doesn't work.

**To Reproduce**
[https://play.nativescript.org/?template=play-ng&id=kwJNyQ](https://play.nativescript.org/?template=play-ng&id=kwJNyQ)

**Expected behavior**
we should be able to scroll the typed text inside the TextView to see the top text.

**Sample project**
[https://play.nativescript.org/?template=play-ng&id=kwJNyQ](https://play.nativescript.org/?template=play-ng&id=kwJNyQ)

_Copied from original issue: NativeScript/nativescript-angular#1765_

**Comment by NickIliev** [comment]
It seems that the issue is reproducible with NativeScript Core project (not related to Angular) - here is [a Playground demo](https://play.nativescript.org/?template=play-tsc&id=TYU9En) with Core project. Moving the issue to the main modules repository.

**Comment by NickIliev** [comment]
@bhavinchb depending on your UI there is a possible workaround. 
Workaround
- Create the `TextView` with `minHeight` instead of `height` and in cases where the user enters more lines then the minimum height the text view will expand. ([example](https://play.nativescript.org/?template=play-tsc&id=TYU9En&v=3))

**Comment by bhavincb** [comment]
@NickIliev  yes, that is what i'm already doing. but what i really need is fixed height with scroll option. is there any workaround for that?

**Comment by NickIliev** [comment]
removing the bug as it seems this is the native behavior for `EditText` nested within `ScrollView`. See [this thread](https://stackoverflow.com/a/24428854/4936697) for a possible workaround (requires accessing the native Android API)
