### ISSUE TITLE
Android - require("tns-core-modules/platform").device.uuid | Cannot read property 'getContentResolver' of undefined

### ISSUE THREAD

**Issue by cpreston321** [NativeScript/NativeScript#7041]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.2.4
 - Cross-platform modules:5.2.2
 - Android Runtime:5.2.1
 - iOS Runtime:5.2.0
 - Plugin(s): NONE

**Describe the bug**
When you try to recieve the device uuid on Android the app crashes saying that Cannot read property 'getContentResolver' of undefined. But IOS works perfectly fine.

**To Reproduce**
Just add this to startup of the project 

`const platformModule = require("tns-core-modules/platform");`

`var test = {
    uuid: platformModule.device.uuid,
};
console.log("asdasdasd", JSON.stringify(test));`

**Expected behavior**
Supposed to return the uuid of the device.

**Sample project**
https://play.nativescript.org/?template=play-vue&id=v2zJSb&v=1

**Additional context**
I tried logging the platform.android.js file under "tns-core-modules/platform" and logged `var nativeApp = appModule.android.nativeApp;` came back as `undefined` so if that could help you debug it faster thanks.

**Comment by tsonevn** [comment]
Hi @cpreston321,
I tested the case on my side and this issue seems to recreate only in a NativeScript Vue project. The same problem is not reproducible with the core[ typescript template](https://play.nativescript.org/?template=play-tsc&id=DcNrMl). Regarding that, I will move this issue in `nativescript-vue` repository

**Comment by tsonevn** [comment]
This issue was moved to nativescript-vue/nativescript-vue#458
