### ISSUE TITLE
Out of memory - leak ui - items with image

### ISSUE THREAD

**Issue by webmeemba** [NativeScript/NativeScript#7056]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.2
 - Cross-platform modules: 5.2.1
 - Android Runtime: 5.2.1
 - iOS Runtime: 5.2.0
 - Plugin(s): nativescript-web-image-cache

**Describe the bug**
Out of memory - leak ui
Out of Memory Issue - 6000 items

**To Reproduce**
Hi, I need to be able to show in a radlistview 7000 elements with cached images in an optimal way. Currently the url of the image is 400x300 / imagen.jpg. But when you go displaying products in the view it becomes corrupted. Someone could help me?

Thanks!

**Comment by tsonevn** [comment]
Hi @webmeemba,
I reviewed your case, however, the provided info is not enough to investigate further the issue.  Can you send us a sample project, that can be used for recreating the problem with the memory?
