### ISSUE TITLE
Adding an event to a View does not mean it can be notified.

### ISSUE THREAD

**Issue by mudlabs** [NativeScript/NativeScript#7058]
**Environment**
 Android and iOS

**Describe the bug**
If a View _(i.e. Label or StackLayout)_ has the `tap` event added, either in `XML` or via `object.on("tap", ...)` the event can not be raised by the `notify(...)` method. I believe this is because they do not have the `tapEvent` static property.

**Expected behavior**
It's reasonable to expect that if you can add the event you should be able to raise the event from `notify`.

**Sample project**
[Playground](https://play.nativescript.org/?template=play-js&id=tout6v)

**Comment by tsonevn** [comment]
Hi @mudlabs,
A similar topic has been discussed in [this issue](https://github.com/NativeScript/NativeScript/issues/6470#issuecomment-433815996). In general, the `.notify` can be used only to raise a custom event. For more info check out the issue #6470.

**Comment by mudlabs** [comment]
[NativeScript Eventify](https://github.com/mudlabs/nativescript-eventify)  attempts to solve this.
