### ISSUE TITLE
White space below action bar on IOS

### ISSUE THREAD

**Issue by brandon-sigao** [NativeScript/NativeScript#7065]
**Environment**
 - CLI: 5.2.4
 - Cross-platform modules: 5.2.2
 - Android Runtime: 5.2.1
 - iOS Runtime: 5.2.0
 - Nativescript Angular

**Describe the bug**
On IOS, navigating to a page results in the page content not extending to the action bar and leaving a large gap of white space.  User input such as a tap event will cause the page the redraw into the correct format without the white space.

**To Reproduce**
I honestly don't have a clue what specifically makes this bug occur.  I suspect its related to recently upgrading to "tns-core-modules: 5.2.2" as we weren't having these issues a few weeks ago, but I could be wrong. The best I can give you is that it happens on initial page load and persists until you interact with the page, at which point the page will be formatted correctly.

If it helps, we are also using flat="true" on all of our action bars.

**Additional context**
An example can be found [here](https://imgur.com/2KjBov9).  

**EDIT 1**
I'm in the process of switching back to 5.2.1 to confirm my suspicions.  As a work around, adding "changeDetectorRef.detectChanges()" at the end of the ngOnInit function seems to fix the problem, but I'm hoping to find a solution that doesn't involve injecting that into every single page.

**EDIT 2**
We confirmed that the issue exists only on tns-core-modules v5.2.2, reverting back to 5.2.1 solves this.

**Comment by tsonevn** [comment]
Hi @brandon-sigao,
I was able to recreate the case with  `flat="true"` in a non-Angular project and will mark the issue as a bug that we will investigate further. I also checked the workaround with `detectChanges()` suggested in your comment in an NS Angular project, however, it does not seem to fix the issue on my side. 
Regarding that, as a temporary solution, I would suggest removing the `flat` property from the ActionBar.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/3001984/Archive.zip)

**Comment by brandon-sigao** [comment]
@tsonevn Thanks for the update.  We ended up sticking with 5.2.1 as there wasn't any real need to jump to 5.2.2 right now and 'flat="true"' is necessary for our app design to work.

**Comment by djmgh** [comment]
I'm seeing the same behavior in NS Vue and not using flat="true"

**Comment by lohiarahul** [comment]
> @tsonevn Thanks for the update. We ended up sticking with 5.2.1 as there wasn't any real need to jump to 5.2.2 right now and 'flat="true"' is necessary for our app design to work.

But if you check the app in IOS versions 10/11 the data goes behind the action bar

**Comment by brandon-sigao** [comment]
We just updated everything to current versions, and as far as i can tell nothing has been fixed.  We still get a giant white bar under the action bar until we interact with the page, and then it redraws properly.  It does this on all Iphone emulators we've tried.  It also seems to randomly choose to show a white bar at the bottom of the iPhone X instead of extending the top level element to the bottom.

I'm going to be exploring workarounds, but otherwise we're just going to drop back down to 5.2.1.  

This also means that we're probably going to have to go into alpha with Iphone X safe areas not getting drawn because we were banking on this stuff being resolved in the newest version.

**Comment by lohiarahul** [comment]
@brandon-sigao Did you try running your app on ios 10.* with 5.2.1? For me, after the downgrade,the white space is not seen on IOS 12.*, but the content in a ScrollView tucks behind the ActionBar for the older versions with 5.2.1.

**Comment by tsonevn** [comment]
HI all,
Currently, the fix for this issue is available in `tns-core-modules@rc`. You can add `rc` modules as follows:
1. `tns plugin remove tns-core-modules`
2. `tns plugin add tns-core-modules@rc`
3. delete `node_modules`, `platforms`, `hooks` folders and `package-lock.json` file
4. rebuild the project

We will soon release a new patch of the modules with the fix. I will write you back as soon as the patch is available

**Comment by lohiarahul** [comment]
> HI all,
> Currently, the fix for this issue is available in `tns-core-modules@rc`. You can add `rc` modules as follows:
> 
> 1. `tns plugin remove tns-core-modules`
> 2. `tns plugin add tns-core-modules@rc`
> 3. delete `node_modules`, `platforms`, `hooks` folders and `package-lock.json` file
> 4. rebuild the project
> 
> We will soon release a new patch of the modules with the fix. I will write you back as soon as the patch is available

![image](https://user-images.githubusercontent.com/2647136/57113424-db5f9e00-6d87-11e9-9966-61a8edc10e40.png)

Still the same issue with "tns-core-modules": "^5.3.1-rc-2019-04-15-173231-01"

**Comment by tsonevn** [comment]
@lohiarahul, Can you send us the project that you are using for testing?
