### ISSUE TITLE
Remove default xmlns on Page element in Vanilla app templates

### ISSUE THREAD

**Issue by shiv19** [NativeScript/NativeScript#7066]
https://github.com/NativeScript/nativescript-app-templates/blob/736662372ea5f976ce6e6041ecc0e93cca0c275f/packages/template-hello-world/app/main-page.xml#L7

The xmlns on the Page element that points to "http://schemas.nativescript.org/tns.xsd" is no longer required. As the link doesn't work. And removing it doesn't have any effect on the app.

**Comment by tsonevn** [comment]
Hi @shiv19,
We have just fixed the broken link for the XSD schema., because of that, I think that we can close this issue.
