### ISSUE TITLE
Feature request: PKAddPaymentPassRequest

### ISSUE THREAD

**Issue by Nurgunkalol** [NativeScript/NativeScript#7068]
Any implementation how to do PKAddPaymentPassRequest on nativescript?

**Comment by NickIliev** [comment]
@Nurgunkalol there is no Apple Pay plugin created so far but as Pass Kit is part of the native iOS API and overall you could apply the same approaches that are being used by the native iOS developers.  The first thing I've noticed that before you start coding your Obj-C code to JS/TSC yo need to have special entitlements for Pass Kit and Apple Pay. See [here ](https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/EntitlementKeyReference/ApplePayandPassKitEntitlements/ApplePayandPassKitEntitlements.html)for details on the entitlements needed and perhaps use [this plugin for adding custom entitlement files in NativeScript
](https://www.npmjs.com/package/nativescript-custom-entitlements)

Closing the issue as not related to NativeScript - please consider posting a how-to related question in the community channels so we could keep the repository clean for logging issues, bugs and features related to NativeScript.

**Comment by NickIliev** [comment]
@Nurgunkalol there is also an alternative plugin for making iOS purchases. The plugin is called [`nativescript-purchase`](https://github.com/PeterStaev/nativescript-purchase#readme) and there is a detailed blog post about [the implementation steps](https://www.tangrainc.com/blog/2017/03/implementing-app-purchases-nativescript-application-part-2/).
