### ISSUE TITLE
background-repeat:no-repeat; does not work properly on some iOS devices

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#707]
The following CSS
```
background-image: url('~/pages/test2.png');
background-repeat: no-repeat;
```
could look like
![no-repeat](https://cloud.githubusercontent.com/assets/12251337/9785791/90b26fec-57bd-11e5-86e0-6c6312bf9f62.png)
on some iOS devices.

Tested on iPhone 5s, iOS8.4.

Theory: this effect is actually the image shown due to problems with pixels rounding.

**Comment by jlooper** [comment]
I'm also encountering problems with background-position: bottom. I'm trying this in the css:

```
.hot-bg{
	background-image: url("res://sunbg");
	background-repeat: no-repeat;
	background-position: bottom;
}
```
and attaching right to the xml:
`<GridLayout columns="*,*,*,*" rows="auto, auto, auto, auto, auto, *" cssClass="{{bg || 'hot-bg'}}" style="background-position:bottom">`

But the result is:
<img width="321" alt="screenshot 2015-09-10 22 47 23" src="https://cloud.githubusercontent.com/assets/1450004/9806062/163ae810-580e-11e5-9950-603660c37d77.png">

The sidewalk in the background should be placed underneath the cat; it seems to float to the top.

**Comment by vchimev** [comment]
First issue described is fixed by this commit: https://github.com/NativeScript/NativeScript/commit/cf20de12e7423bb3f94601967ff7898cb530eea9. The fix is going to be released in version 1.4.0.

**Comment by vchimev** [comment]
Hi @jlooper,

could you please try to set `background-position: center bottom;` - it should solve your problem.

**Comment by vchimev** [comment]
Closing this issue for now.
