### ISSUE TITLE
tns_modules folder not livesynced. Using tns_modules from the already deployed bundle...

### ISSUE THREAD

**Issue by mrwrighty** [NativeScript/NativeScript#7070]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.2.3
 - Cross-platform modules: 
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

"kinvey-nativescript-sdk": "3.12.4",
    "nativescript-accelerometer": "^2.0.1",
    "nativescript-background-fetch": "1.2.0",
    "nativescript-background-geolocation-lt": "1.9.1",
    "nativescript-background-http": "3.3.0",
    "nativescript-camera": "^4.3.0",
    "nativescript-drop-down": "4.0.1",
    "nativescript-fresco": "4.0.0",
    "nativescript-geolocation": "4.2.6",
    "nativescript-google-maps-sdk": "2.7.0",
    "nativescript-intl": "^3.0.0",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-platform": "1.2.3",
    "nativescript-social-share": "^1.5.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-autocomplete": "^3.7.0",
    "nativescript-ui-calendar": "^3.6.0",
    "nativescript-ui-chart": "^3.6.0",
    "nativescript-ui-dataform": "^3.6.0",
    "nativescript-ui-gauge": "^3.6.0",
    "nativescript-ui-listview": "^3.5.5",
    "nativescript-ui-sidedrawer": "^4.1.0",
    "nativescript-videoplayer": "^3.1.0",
    "nativescript-videorecorder": "^3.0.0-beta.2",
    "tns-core-modules": "^5.2.2"

**Describe the bug**
When building for an iPhone 5C (iOS 10.3.3), physical device, whenever the project is installed I am told tns_modules folder not livesynced. Using tns_modules from the already deployed. If I build for iPhone X (iOS 12.1.4) I get no such warning.
**To Reproduce**

I have used: 

tns debug ios
tns build ios

I have removed hooks, node_modules and package.lock.json.

I have cleared the tns cache

I am getting an error on the 5C from the video recorder package 

Mar 25 13:44:07 iPhone-5c Workforce(NativeScript)[400] <Notice>: file:///app/tns_modules/nativescript-videorecorder/advanced/advanced-video-view.js:199:43: JS ERROR TypeError: ex.getMessage is not a function. (In 'ex.getMessage()', 'ex.getMessage' is undefined).

This error does not occur on the iPhone X

**Expected behavior**

**Sample project**

**Additional context**

**Comment by tsonevn** [comment]
Hi @mrwrighty,
Can you try deleting the `platforms` folder as well while rebuilding the app? If the problem persists, please send us the project or sample one, which can be used for debugging.
Also, following the provided error log, the issue can be related to the  `nativescript-videorecorder` plugin and its usage in lower iOS versions, however, to be sure that this is the case I need to review the project.
Thank you in advance for your cooperation.

**Comment by mrwrighty** [comment]
Thank you for your response. Deleting the Platforms folder allow me to run the project and the error shown above related to the video recorder disappeared. Having said that, the line tns_modules folder not livesynced. Using tns_modules from the already deployed bundle... still happens. I'm not sure of the impact of this and whether it can result in the app not being updated correctly.

**Comment by tsonevn** [comment]
Hi @mrwrighty,
Can you send us the project and the full log for the new error? If you do not want to share your project here, you can also send it via private message using the [nativescript community slack](nativescriptcommunity.slack.com/). My nickname is `nikts`.
