### ISSUE TITLE
Programmatically zoom and pinch chart

### ISSUE THREAD

**Issue by jinusean** [NativeScript/NativeScript#7074]
**Is your feature request related to a problem? Please describe.**
- Programmatically pinch/zoom the chart.
- Get current level of zoom / pinch.
- Get a list of currently displayed data points.
- Optimize labels displayed so they all fit at once. 

These features would enable developers to load the chart with a preset amount of zoom/pinch in order to display large amounts of data.

**Comment by NickIliev** [comment]
@jinusean I guess you are talking about nativescript-ui-chart and if that is the case please open the issue in the following repository:

[https://github.com/telerik/nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback)

Closing the issue as unrelated to NativeScript modules and related to a feature request for a plugin.
