### ISSUE TITLE
Android support for clip-path on Image

### ISSUE THREAD

**Issue by Buuhuu** [NativeScript/NativeScript#7086]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.1
 - Cross-platform modules: 5.2.1 
 - Android Runtime: 5.2.0
 - iOS Runtime: 5.2.0
 - Plugin(s): a couple of 

**Describe the bug**
When setting a clip-path (for example a hexagon) on an Image, with a background-color different to transparent (for example yellow) the image is not clipped on Android, on iOS though all works fine.

In our project we use a dedicated service that loads the images as we have to modify/intercept the http requests for the images to add authentication. Using the background-url is not an option as we don't have this capabilities there (additionally we use a more advanced bitmap pooling, but that doesn't matter much: we have to stick to the src being set on the image view)

**To Reproduce**
```
<Image src="https://picsum.photos/640/480" class="image" stretch="aspectFill"></Image>
```
```
.image {
    background-size: cover;
    background-color: yellow;
    clip-path: polygon(25% 5%, 75% 5%, 100% 50%, 75% 95%, 25% 95%, 0% 50%);
    height: 216;
    width: 216;
}
```

**Expected behavior**
Android should have the same behaviour as iOS, properly clipping as specified. 

**Sample project**
https://play.nativescript.org/?template=play-ng&id=gMzbOn&v=3

**Comment by NickIliev** [comment]
@Buuhuu thanks for reporting this one - confirming that clip-path is not working on Image in Android so marking this one as a bug.

Meanwhile, as a temporary workaround, you could apply the clip-path on a parent layout. For example [here is a Playground demo ](https://play.nativescript.org/?template=play-ng&id=gMzbOn&v=4) achieving the above by applying the clipping on the StackLayout

**Comment by Buuhuu** [comment]
Thanks @NickIliev but as stated above this doesn't work for us as we cannot use background-url (its limited to string url or base64 but we would need image source)

**Comment by NickIliev** [comment]
@Buuhuu it seems that the issue was already logged [here ](https://github.com/NativeScript/NativeScript/issues/3837)so closing this one as a duplicate.

**Comment by Buuhuu** [comment]
Thanks @NickIliev. I found a first working solution and commented on the other issue, its quite old though but maybe worth to push it up in the backlog ;)

**Comment by Ahsan444** [comment]
not giving the accurate result
