### ISSUE TITLE
Could not create service of type DefaultUserHomeScopedCompileCaches using UserHomeScopeServices.createCompileCaches().

### ISSUE THREAD

**Issue by JohnGalt1717** [NativeScript/NativeScript#7088]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

√ Component nativescript has 5.3.0 version and is up to date.
√ Component tns-core-modules has 5.3.1 version and is up to date.
√ Component tns-android has 5.3.0 version and is up to date.
√ Component tns-ios has 5.3.0 version and is up to date.

**Describe the bug**
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Could not create service of type DefaultUserHomeScopedCompileCaches using UserHomeScopeServices.createCompileCaches().

**To Reproduce**
Setup Nativescript and got a clean bill of health from tns doctor.

I created a new nativescript project per the documentation like this: tns create HelloWorld --template tns-template-blank-ng and then ran tns run android. It worked perfectly fine.

Then used the nsconfig.json useLegacyWorkflow: false to make sure hot reload was on all of the time per the docs for 5.3 and ran tns run android.

Switching back by removing the command from nsconfig.json doesn't fix this issue.

**Expected behavior**
Should just build and work right.

**Additional context**
I have Android studio and flutter installed and had to fix the android sdk stuff to point to the Android Studio version.  Not sure that this matters but would be pretty common.

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #4485](https://github.com/NativeScript/nativescript-cli/issues/4485) via [**ZenHub**](https://www.zenhub.com/)
