### ISSUE TITLE
Issues with leading dashes in css class names (e.g. --selected_item)

### ISSUE THREAD

**Issue by SephReed** [NativeScript/NativeScript#7089]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.3.0 version and is up to date.
✔ Component tns-core-modules has 5.3.1 version and is up to date.
✔ Component tns-android has 5.3.0 version and is up to date.
✔ Component tns-ios has 5.3.0 version and is up to date.

**Describe the bug**
If you add the css class "--some_flag_type_class_name" to a view, it will not get the styling updates.  This may be an issue with the sass interpreter, or something else.

**Expected behavior**
The classname should be valid

**Additional context**
This style of classname is really useful for state related styling.  For instance `<div class="--disabled">` or `--fading_in`.  I use it a lot in web dev.  Would be nice to continue using it.

**Comment by NickIliev** [comment]
@SephReed moving the issue to the SASS plugin as it seems it is [only reproducible when using SASS ](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/NativeScript/iisue-7089)([working as expected with plain CSS](https://play.nativescript.org/?template=play-ng&id=3wgCek))

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-dev-sass #106](https://github.com/NativeScript/nativescript-dev-sass/issues/106) via [**ZenHub**](https://www.zenhub.com/)
