### ISSUE TITLE
API Stability Index (Proposal)

### ISSUE THREAD

**Issue by hshristov** [NativeScript/NativeScript#709]
Hi all,

we are thinking of adding **API Stability Index** based on the node.js:
https://nodejs.org/docs/latest-v0.12.x/api/documentation.html#documentation_stability_index

This will allow as to add **Experimental** features which you can test and let us know if they work as you expected or not. We will mark the experimental APIs in the documentation.

For 1.5:
 - [ ] mark unstable APIs with @experimental attribute in code

Unplanned:
 - [ ] mark the unstable APIs in the typedoc API reference

What do you think about this?
Please share your feedback/ideas.

**Comment by vakrilov** [comment]
:+1:

**Comment by atanasovg** [comment]
:100: 
This would be quite useful to people and would raise our awareness on how we design/maintain/change our APIs.

**Comment by PanayotCankov** [comment]
:+1:

**Comment by ligaz** [comment]
:heart:

**Comment by lscown** [comment]
:+1:

**Comment by jaalbaya** [comment]
+1

**Comment by teobugslayer** [comment]
This would be awesome!

**Comment by valentinstoychev** [comment]
Lets add @experimental attributes that will throw warnings that the API used is not stable.
