### ISSUE TITLE
iOS deploy to physical device, app appears installed but can't be accessed

### ISSUE THREAD

**Issue by isawk** [NativeScript/NativeScript#7091]
Similar issue was reported some time back, issue however appears to have not be resolved. With multiple comments of some saying works now, never worked, not working e.t.c.

**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.3.0
 - Cross-platform modules: 5.3.1
 - Android Runtime: 5.3.0
 - iOS Runtime: 5.3.0
 - Plugin(s):

Dependencies:
┌───────────────────────────────────┬──────────┐
│ Plugin                            │ Version  │
│ @angular/animations               │ ~7.1.0   │
│ @angular/common                   │ ~7.1.0   │
│ @angular/compiler                 │ ~7.1.0   │
│ @angular/core                     │ ~7.1.0   │
│ @angular/forms                    │ ~7.1.0   │
│ @angular/http                     │ ~7.1.0   │
│ @angular/platform-browser         │ ~7.1.0   │
│ @angular/platform-browser-dynamic │ ~7.1.0   │
│ @angular/router                   │ ~7.1.0   │
│ @fortawesome/angular-fontawesome  │ ^0.3.0   │
│ @fortawesome/fontawesome-svg-core │ ^1.2.17  │
│ @fortawesome/free-solid-svg-icons │ ^5.8.1   │
│ lodash                            │ ^4.17.11 │
│ nativescript-3dtouch              │ ^1.2.2   │
│ nativescript-angular              │ ^7.2.3   │
│ nativescript-camera               │ ^4.4.0   │
│ nativescript-fingerprint-auth     │ ^6.2.0   │
│ nativescript-localstorage         │ ^2.0.0   │
│ nativescript-plugin-firebase      │ ^8.1.1   │
│ nativescript-theme-core           │ ^1.0.4   │
│ nativescript-vibrate              │ ^2.1.3   │
│ reflect-metadata                  │ ~0.1.12  │
│ rxjs                              │ ^6.3.3   │
│ tns-core-modules                  │ ^5.3.1   │
│ typescript                        │ ~3.1.1   │
│ zone.js                           │ ^0.8.4   │
└───────────────────────────────────┴──────────┘
Dev Dependencies:
┌─────────────────────────────┬───────────┐
│ Plugin                      │ Version   │
│ @angular/compiler-cli       │ ^7.2.11   │
│ @nativescript/schematics    │ ^0.5.2    │
│ @ngtools/webpack            │ ~7.1.0    │
│ @types/lodash               │ ^4.14.123 │
│ nativescript-dev-typescript │ ~0.7.0    │
│ nativescript-dev-webpack    │ ~0.19.0   │
└─────────────────────────────┴───────────┘

**Describe the bug**

running `tns deploy ios ` along with --device id is meant to install application on device. Though CLI completes with message "Successfully installed application ..." on device with id "xxx" the aforementioned application doesn't appear in launcher, a quick search shows application icon however it can't be launched. 

**To Reproduce**
tns deploy ios --device ${your_connected_device_id}, using sidekick produces the same issue above.

**Expected behavior**

Application installed on physical device icon must appear on home screen, not only in search and must work when clicked. Though it appears in search "Top Hit" click it produces no effects. 

**Sample project**
Proprietary project, can't share name or git repo

**Additional context**

Deploying to physical device from xcode works 100%, installs and application can be accessed/opened. All features work 100%. However deploying from Sidekick or cli tns deploy ios doesn't produce the same results as deploying from xcode.

team_id has been set, all necessary documented steps have been followed. However though "Successfully installed on device with identifier" is reported by CLI and Sidekick application can't be accessed.

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #4486](https://github.com/NativeScript/nativescript-cli/issues/4486) via [**ZenHub**](https://www.zenhub.com/)
