### ISSUE TITLE
Nativescript routing

### ISSUE THREAD

**Issue by jannomeister** [NativeScript/NativeScript#7097]
I’m having trouble navigating to a different lazy loaded route. Because when I hit the back button from the said route and navigate back to the different lazy loaded route I’m getting an error: `Cannot reattach ActivatedRouteSnapshot created from a different route`

How can I properly solve this issue without using hack? btw, I'm using Nativescript-angular template.

**Comment by NickIliev** [comment]
@jannomeister there is not enough information provided to investigate your case.  If you think this is bug related then consider creating [a Playground demo](https://play.nativescript.org/) and logging the issue while providing full details requested in the report a bug template in [the nativescript-angular repository](https://github.com/NativeScript/nativescript-angular/issues).
