### ISSUE TITLE
ScrollView.animate() resets ScrollView.verticalOffset to zero

### ISSUE THREAD

**Issue by SephReed** [NativeScript/NativeScript#7104]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.3.1 version and is up to date.
✔ Component tns-core-modules has 5.4.0-next-2019-04-03-175957-02 version and is up to date.
✔ Component tns-android has 5.4.0-2019-04-03-095324-01 version and is up to date.
✔ Component tns-ios has 5.4.0-2019-04-03-180044-02 version and is up to date.

**Describe the bug**

Calling the `animate()` function on a `ScrollView` class resets its `verticalOffset` member to zero.

**To Reproduce**

```
const scrolly = new ScrollView();
// append to root
scrolly.verticalOffset = 100;
await scrolly.animate({ translate: {x:100, y:0}, duration: 0});
console.log(scrolly.verticalOffset); // outputs 0;
```

**Expected behavior**
The scroll view should move 100 px horizontally, without changing scroll position

**Sample project**

N/A

**Additional context**

I'm trying to tween between to ScrollViews.  The one being pushed offscreen resets to top first, doesn't look great.

**Comment by tsonevn** [comment]
Hi @SephReed,
In your case, you should set the vertical offset via  `scrollToVerticalOffset` method. For example:

``` TypeScript
import { EventData } from "tns-core-modules/data/observable";
import {ScrollView} from "tns-core-modules/ui/scroll-view";
export function navigatingTo(args: EventData) {
}

export function svlayoutChanged(args){
    let sv = <ScrollView> args.object;
    console.log("sv");
    console.log(sv)

        sv.scrollToVerticalOffset(100, false);
        sv.animate({ translate: {x:100, y:0}, duration: 2000});
        console.log(sv.verticalOffset);
}
```
```XML
    <StackLayout class="p-20" id="testsv">
        <ScrollView layoutChanged="svlayoutChanged">
            
        
            <GridLayout class="m-15" rows="auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto">
                <Label class="h3 m-5" height="50" row="0" text="Title 1"/>
                <Label class="h3 m-5" height="50" row="1" text="Title 2"/>
                <Label class="h3 m-5" height="50" row="2" text="Title 3"/>
                <Label class="h3 m-5" height="50" row="3" text="Title 4"/>
                <Label class="h3 m-5" height="50" row="4" text="Title 5"/>
                <Label class="h3 m-5" height="50" row="5" text="Title 6"/>
                <Label class="h3 m-5" height="50" row="6" text="Title 7"/>
                <Label class="h3 m-5" height="50" row="7" text="Title 8"/>
                <Label class="h3 m-5" height="50" row="8" text="Title 9"/>
                <Label class="h3 m-5" height="50" row="9" text="Title 10"/>
                <Label class="h3 m-5" height="50" row="10" text="Title 10"/>
                <Label class="h3 m-5" height="50" row="11" text="Title 11"/>
                <Label class="h3 m-5" height="50" row="12" text="Title 12"/>
                <Label class="h3 m-5" height="50" row="13" text="Title 13"/>
                <Label class="h3 m-5" height="50" row="14" text="Title 14"/>
                <Label class="h3 m-5" height="50" row="15" text="Title 15"/>
            </GridLayout>
        </ScrollView>
    </StackLayout>
```
Keep in mind that the [verticalOffset](https://docs.nativescript.org/api-reference/classes/_ui_scroll_view_.scrollview#verticaloffset) is a read-only property.

**Comment by SephReed** [comment]
I'm not actually setting the vertical offset in my codebase, I'm scrolling to get there.  I don't know what function is called internally when scrolling happens, but I suppose it must be `scrollToVerticalOffset`.  This was a failure in my example, but the issue remains unfixed.  If you create a ScrollView(), scroll inside it, than animate translate, the scroll offset gets reset before the animation begins.

**Comment by tsonevn** [comment]
Hi @SephReed,
Can you provide a sample project, that can be used for recreating the issue?

**Comment by SephReed** [comment]
I can give you most of the code, but I'm not really familiar with the playground, vue, or xml.  I'm using core, but this should be close.

```
<ScrollView height="5000" onClick={clicked()}>
  <Label text="This is some random text which exists to make the glitch visible" />
</ScrollView>
```

```
function clicked() {
  const scrollView = getScrollViewHoweverItsNormallyDone();
  scrollView.animate({ translate: {x: 200, y: 0}}).then(() => scrollView.translateX = 0);
}
```

To test it, scroll the scroll view so the text is out of bounds, then click.  The scroll view will pop back to the top, you'll be able to see the text, then at the same time translate to x = 200.  It should not scroll to the top first.

**Comment by tsonevn** [comment]
Hi @SephReed,
Excuse me for the delay in reply.
I have just checked the provided code samples in a [sample project](https://play.nativescript.org/?template=play-js&id=ESz44n), however, I am still unable to recreate the problem. For your convenience, I am attaching video, which demonstrates the behaviour on my side. I have tested the scenario on Android device - API level 28. You can test the demo while using the [Preview app](https://docs.nativescript.org/start/introduction#step-1-nativescript-playground) or you can download it and build it locally via CLI.
[demo.mp4.zip](https://github.com/NativeScript/NativeScript/files/3089027/demo.mp4.zip)

**Comment by SephReed** [comment]
I've also recently seen shit issue go away.  I have no idea what changed, but thank you for looking into this issue.  If it comes up again, I'll try to do better to pinpoint exactly what the circumstances are.
