### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by ibnYusrat** [NativeScript/NativeScript#7108]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.3.1
 - Cross-platform modules: 5.3.1
 - Android Runtime: 8
 - iOS Runtime: 12

**Describe the bug**
Its not possible to follow this document because it seems to be outdated. https://docs.nativescript.org/ui/change-status-bar-style-ios
For example:
` navigationBar.barStyle = UIBarStyle.UIBarStyleBlack;`
Produces
`Property 'UIBarStyleBlack' does not exist on type 'typeof UIBarStyle'.`
And this seems to happen for quite sometime. 

**To Reproduce**
Follow the documentation

**Expected behavior**
Effect the statusbar on iOS

**Sample project**
You can generate a blank project from command-line and it will produce the same result. 

**Additional context**
It seems not a lot of people have read/used this page for at least two years because even if you search google for UIBarStyleBlack nativescript and set the time of search results to "1 years" you don't get anything. That is really strange.

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/docs #1615](https://github.com/NativeScript/docs/issues/1615) via [**ZenHub**](https://www.zenhub.com/)
