### ISSUE TITLE
Creating angular module after adding nativescript takes forever

### ISSUE THREAD

**Issue by itsmeneartou** [NativeScript/NativeScript#7109]
### Description
When I try to create a new module using `ng g m test`. It takes very long time and this waiting is most probably an error because creating 4-5 files should not take this long. The component created using `ng g c my-component` takes almost no time.

## 🔬 Minimal Reproduction
The reproduction steps are simple.

1) Create new angular app using `ng new moduleCreationBug`.
2) Optional: try creating a test module and check everything is fine ng g m test (In this step module gets created in no time.)

3) Now add nativescript to angular app as taught in this [blog](https://blog.angular.io/apps-that-work-natively-on-the-web-and-mobile-9b26852495e7) using `ng add @nativescript/schematics`

4) Now try creating module again using `ng g m test2` and now it takes forever to create the module, I have never been able to create module after adding nativescript. I have to manually create the files for a module

## 🌍 Your Environment
Windows 10 core i5 8th Gen 8GB ram, editor:visual studio code, terminal:Integrated terminal

## What I have done till now ?
I created this issue on angular-cli github page but the issue was closed there stating 

> @nativescript/schematics sets itself as the default and replaces all the generation schematics. This issue ideally should be raised on the NativeScript repository.

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-schematics #203](https://github.com/NativeScript/nativescript-schematics/issues/203) via [**ZenHub**](https://www.zenhub.com/)
