### ISSUE TITLE
How can I add route-me/route-me RMMapView

### ISSUE THREAD

**Issue by danicomas** [NativeScript/NativeScript#711]
I want to add this external library but I have seen that in cocoapods is wrong and I don't know how I can add the project and the correct recognition.

I have tried:
1) add the project in Xcode
2) add the module inside platforms/ios/module.modulemap:

module RMMapView {
  umbrella header "route-me-master/MapView/Map/RMMapView.h"
  export *
  module * { export * }
}

3) the app give me an undefined RMMapView

```xml
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
  <GridLayout rows="auto, auto, auto, *">
    <Placeholder row="3" creatingView="createMapView" />
  </GridLayout>
</Page>
```

```js
var mapView;

function pageLoaded(args) {
    var page = args.object;
}

function createMapView(args) {
    var rect = {
        origin: {
            x: 10,
            y: 20
        },
        size: {
            width: 200,
            height: 300
        }
    };
    
    var initialCenter = {
        latitude: 66.44,
        longitude: -178.0
    }
    
    mapView = RMMapView.alloc().initWithFrameWithLocation(rect, initialCenter);
    args.view = mapView;
}

exports.pageLoaded = pageLoaded;
exports.createMapView = createMapView;
```

One solution could be to do some video to other user too. What do you think?

References: 
https://docs.nativescript.org/runtimes/ios/marshalling/Marshalling-Overview.html
https://github.com/route-me/route-me/blob/f689eb2274d96438430ae9397f64547c1cfc9762/MapView/UnitTesting/RouteMeTests.m
https://docs.nativescript.org/runtimes/ios/native-libs/CocoaPods

**Comment by fealebenpae** [comment]
Hi @danicomas

Assuming you've followed [route-me's embedding guide](https://github.com/route-me/route-me/wiki/Embedding-Guide) and added `route-me-master/MapView/Map` to your project's `HEADER_SEARCH_PATHS` build setting, it should be enough to place the modulemap with the other headers in the `Map` folder. Also, it looks like `RouteMe.h` is the main header for this library, which you can use as an umbrella header.

**Comment by danicomas** [comment]
I will try it @fealebenpae but a good idea would be to do a some video or repository with an example. What do you think?

**Comment by fealebenpae** [comment]
I agree that some sort of guidance on how the metadata generation process works and how to diagnose any issues is essential, and we are working to stabilize the generator enough to be able to document it (recent changes in Objective-C introduced in Xcode 7 have caused much flux in the API metadata generator).

However, there will always be some exceptional cases like route-me that are harder to integrate. Good documentation and examples can only cover 80% of the library scenarios out there. Since NativeScript for iOS depends on modulemaps just as the Swift compiler does, a good rule of thumb for the suitability of a library is whether Swift can import it with `import MyAwesomeLibrary`. This is really a problem with how libraries are distributed on iOS - newer libraries can be built as Cocoa Frameworks which are self-contained bundles with modulemaps and everything, whereas some older libraries such as route-me come with a set of manual integration steps, which are specific to the library, and these are hard to document or automate.

**Comment by danicomas** [comment]
I have this error following the route-me guide:

tns run ios --emulator
Project successfully prepared
Build settings from command line:
    ARCHS = i386
    CONFIGURATION_BUILD_DIR = /Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/build/emulator
    SDKROOT = iphonesimulator8.4
    SHARED_PRECOMPS_DIR = /Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/build/sharedpch
    VALID_ARCHS = "i386"

=== BUILD TARGET Proj4 OF PROJECT Proj4 WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET MapView OF PROJECT MapView WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET NativeScriptApp OF PROJECT NativeScriptApp WITH CONFIGURATION Debug ===

Check dependencies

Ld build/emulator/NativeScriptApp.app/NativeScriptApp normal i386
    cd /Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -L/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/build/emulator -L/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/NativeScript/lib -F/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/build/emulator -F/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios -F/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/../../lib/iOS -filelist /Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/build/NativeScriptApp.build/Debug-iphonesimulator/NativeScriptApp.build/Objects-normal/i386/NativeScriptApp.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -objc_abi_version -Xlinker 2 -all_load -ObjC -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=7.0 -framework QuartzCore -framework CoreLocation -lsqlite3 /Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/build/emulator/libMapView.a -licucore -lz -lc++ -weak_framework Foundation -weak_framework UIKit -lNativeScript -Xlinker -dependency_info -Xlinker /Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/build/NativeScriptApp.build/Debug-iphonesimulator/NativeScriptApp.build/Objects-normal/i386/NativeScriptApp_dependency_info.dat -o /Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/build/emulator/NativeScriptApp.app/NativeScriptApp
ld: warning: directory not found for option '-F/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/../../lib/iOS'
ld: warning: could not create compact unwind for .LFB3: non-standard register 5 being saved in prolog
Undefined symbols for architecture i386:
  "_CGAffineTransformIdentity", referenced from:
      -[RMLayerCollection initForContents:] in libMapView.a(RMLayerCollection.o)
      -[RMMarkerManager initWithContents:] in libMapView.a(RMMarkerManager.o)
      -[RMLayerCollection initForContents:] in libMapView.a(RMLayerCollection.o)
      -[RMMarkerManager initWithContents:] in libMapView.a(RMMarkerManager.o)
  "_CGAffineTransformMakeRotation", referenced from:
      -[RMMapView setRotation:] in libMapView.a(RMMapView.o)
      -[RMLayerCollection setRotationOfAllSublayers:] in libMapView.a(RMLayerCollection.o)
      -[RMMarkerManager addMarker:atProjectedPoint:] in libMapView.a(RMMarkerManager.o)
      -[RMMarkerManager setRotation:] in libMapView.a(RMMarkerManager.o)
  "_CGContextAddPath", referenced from:
      -[RMPath drawInContext:] in libMapView.a(RMPath.o)
  "_CGContextBeginPath", referenced from:
      -[RMPath drawInContext:] in libMapView.a(RMPath.o)
  "_CGContextDrawPath", referenced from:
      -[RMPath drawInContext:] in libMapView.a(RMPath.o)
  "_CGContextScaleCTM", referenced from:
      -[RMPath drawInContext:] in libMapView.a(RMPath.o)
  "_CGContextSetFillColorWithColor", referenced from:
      -[RMPath drawInContext:] in libMapView.a(RMPath.o)
  "_CGContextSetLineCap", referenced from:
      -[RMPath drawInContext:] in libMapView.a(RMPath.o)
  "_CGContextSetLineDash", referenced from:
      -[RMPath drawInContext:] in libMapView.a(RMPath.o)
  "_CGContextSetLineJoin", referenced from:
      -[RMPath drawInContext:] in libMapView.a(RMPath.o)
  "_CGContextSetLineWidth", referenced from:
      -[RMPath drawInContext:] in libMapView.a(RMPath.o)
  "_CGContextSetShadowWithColor", referenced from:
      -[RMPath drawInContext:] in libMapView.a(RMPath.o)
  "_CGContextSetStrokeColorWithColor", referenced from:
      -[RMPath drawInContext:] in libMapView.a(RMPath.o)
  "_CGPathAddEllipseInRect", referenced from:
      -[RMCircle updateCirclePath] in libMapView.a(RMCircle.o)
  "_CGPathAddLineToPoint", referenced from:
      -[RMPath addPointToXY:withDrawing:] in libMapView.a(RMPath.o)
  "_CGPathCloseSubpath", referenced from:
      -[RMPath closePath] in libMapView.a(RMPath.o)
  "_CGPathCreateMutable", referenced from:
      -[RMPath initWithContents:] in libMapView.a(RMPath.o)
      -[RMCircle updateCirclePath] in libMapView.a(RMCircle.o)
  "_CGPathGetBoundingBox", referenced from:
      -[RMPath recalculateGeometry] in libMapView.a(RMPath.o)
      -[RMPath projectedBounds] in libMapView.a(RMPath.o)
  "_CGPathIsEmpty", referenced from:
      -[RMPath addPointToXY:withDrawing:] in libMapView.a(RMPath.o)
  "_CGPathMoveToPoint", referenced from:
      -[RMPath addPointToXY:withDrawing:] in libMapView.a(RMPath.o)
  "_CGPathRelease", referenced from:
      -[RMPath dealloc] in libMapView.a(RMPath.o)
      -[RMCircle dealloc] in libMapView.a(RMCircle.o)
      -[RMCircle updateCirclePath] in libMapView.a(RMCircle.o)
  "_CGPointZero", referenced from:
      -[RMCoreAnimationRenderer initWithContent:] in libMapView.a(RMCoreAnimationRenderer.o)
      -[RMTileImage makeLayer] in libMapView.a(RMTileImage.o)
      _RMTileRectRound in libMapView.a(RMTile.o)
      -[RMMapContents setMetersPerPixel:] in libMapView.a(RMMapContents.o)
      -[RMPath recalculateGeometry] in libMapView.a(RMPath.o)
      -[RMCoreAnimationRenderer initWithContent:] in libMapView.a(RMCoreAnimationRenderer.o)
      -[RMTileImage makeLayer] in libMapView.a(RMTileImage.o)
      _RMTileRectRound in libMapView.a(RMTile.o)
      -[RMMapContents setMetersPerPixel:] in libMapView.a(RMMapContents.o)
      -[RMPath recalculateGeometry] in libMapView.a(RMPath.o)
      -[RMCoreAnimationRenderer initWithContent:] in libMapView.a(RMCoreAnimationRenderer.o)
      -[RMTileImage makeLayer] in libMapView.a(RMTileImage.o)
      _RMTileRectRound in libMapView.a(RMTile.o)
      -[RMMapContents setMetersPerPixel:] in libMapView.a(RMMapContents.o)
      -[RMPath recalculateGeometry] in libMapView.a(RMPath.o)
      -[RMCoreAnimationRenderer initWithContent:] in libMapView.a(RMCoreAnimationRenderer.o)
      -[RMTileImage makeLayer] in libMapView.a(RMTileImage.o)
      _RMTileRectRound in libMapView.a(RMTile.o)
      -[RMMapContents setMetersPerPixel:] in libMapView.a(RMMapContents.o)
      -[RMPath recalculateGeometry] in libMapView.a(RMPath.o)
      -[RMCoreAnimationRenderer initWithContent:] in libMapView.a(RMCoreAnimationRenderer.o)
      -[RMTileImage makeLayer] in libMapView.a(RMTileImage.o)
      _RMTileRectRound in libMapView.a(RMTile.o)
      -[RMMapContents setMetersPerPixel:] in libMapView.a(RMMapContents.o)
      -[RMPath recalculateGeometry] in libMapView.a(RMPath.o)
  "_CGRectContainsRect", referenced from:
      -[RMTileLoader screenIsLoaded] in libMapView.a(RMTileLoader.o)
  "_CGRectEqualToRect", referenced from:
      -[RMMapView setFrame:] in libMapView.a(RMMapView.o)
      -[RMPath recalculateGeometry] in libMapView.a(RMPath.o)
  "_CGRectInset", referenced from:
      -[RMPath recalculateGeometry] in libMapView.a(RMPath.o)
      -[RMPath projectedBounds] in libMapView.a(RMPath.o)
      -[RMCircle updateCirclePath] in libMapView.a(RMCircle.o)
  "_CGRectIntersection", referenced from:
      -[RMPath recalculateGeometry] in libMapView.a(RMPath.o)
  "_CGRectZero", referenced from:
      -[RMTileImage initWithTile:] in libMapView.a(RMTileImage.o)
      -[RMTileLoader clearLoadedBounds] in libMapView.a(RMTileLoader.o)
      -[RMMapContents screenBounds] in libMapView.a(RMMapContents.o)
      -[RMTileImage initWithTile:] in libMapView.a(RMTileImage.o)
      -[RMTileLoader clearLoadedBounds] in libMapView.a(RMTileLoader.o)
      -[RMMapContents screenBounds] in libMapView.a(RMMapContents.o)
      -[RMTileImage initWithTile:] in libMapView.a(RMTileImage.o)
      -[RMTileLoader clearLoadedBounds] in libMapView.a(RMTileLoader.o)
      -[RMMapContents screenBounds] in libMapView.a(RMMapContents.o)
  "_CGSizeZero", referenced from:
      -[RMMapView stopDeceleration] in libMapView.a(RMMapView.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build/emulator/NativeScriptApp.app/NativeScriptApp normal i386
(1 failure)
Command xcodebuild failed with exit code 65
# run ios

**Comment by danicomas** [comment]
I think that I need RMMapView.h in the modulemap:

```
module RMMapView {
  umbrella header "vendor/route-me/MapView/Map/RMMapView.h"
  export *
  module * { export * }
}
```

because after I call that:

```
RMMapView.alloc().initWithFrameWithLocation(rect, initialCenter);
```

I have a question too. Don't I need to add require library inside the .js?

**Comment by fealebenpae** [comment]
It seems from the linker errors that you need to link to the CoreGraphics framework as well.

Re. the modulemap - `RouteMe.h` already includes a reference to `RMMapView.h`, as well as a few other headers which you might need.

**Comment by danicomas** [comment]
Really nice. Amazing. It works. The problem was CoreGraphics. Thanks @fealebenpae.

**Comment by danicomas** [comment]
iOS 7 is not supported? Probably coreGraphics? Before add the module worked well in Iphone 4.

**Comment by danicomas** [comment]
@fealebenpae iOS 7 is not supported? Probably coreGraphics? Before add the module worked well in Iphone 4.

**Comment by danicomas** [comment]
Deploying on iOS 7 iPhone 4.
Results at '/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/build/device/NativeScriptApp.ipa' 
Project successfully built
Using  /Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/build/device/NativeScriptApp.ipa
Status: CreatingStagingDirectory PercentComplete: 5
Status: ExtractingPackage PercentComplete: 15
Status: InspectingPackage PercentComplete: 20
Status: TakingInstallLock PercentComplete: 20
Status: PreflightingApplication PercentComplete: 30
Status: InstallingEmbeddedProfile PercentComplete: 30
Status: VerifyingApplication PercentComplete: 40
Status: CreatingContainer PercentComplete: 50
Status: InstallingApplication PercentComplete: 60
Status: PostflightingApplication PercentComplete: 70
Status: SandboxingApplication PercentComplete: 80
Status: GeneratingApplicationMap PercentComplete: 90
Status: Complete
Successfully deployed on device 5bcd2076eb3e7eb8fec7f38cb6abe401362309ea
Mounting /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/7.1/DeveloperDiskImage.dmg
[Mounting] LookingUpImage
[Mounting] StreamingImage
[Mounting] MountingImage
Successfully run application org.nativescript.NativeScriptApp on device with ID 5bcd2076eb3e7eb8fec7f38cb6abe401362309ea.
Sep 14 14:08:05  accountsd[8326] <Notice>: 2015-09-14 14:08:05.462 accountsd[8326:9059]: The credential for account ipad@ingens-networks.com is missing. It may have been withheld by its auth plugin.
Sep 14 14:10:24 iPhone-de-Carlos com.apple.debugserver-310.2[8930] <Warning>: debugserver-310.2 for armv7.
Sep 14 14:10:24 iPhone-de-Carlos com.apple.debugserver-310.2[8930] <Warning>: Connecting to com.apple.debugserver service...
Sep 14 14:10:24 iPhone-de-Carlos com.apple.debugserver-310.2[8930] <Warning>: Got a connection, waiting for process information for launching or attaching.
Sep 14 14:10:24 iPhone-de-Carlos com.apple.debugserver-310.2[8930] <Warning>: About to launch process for bundle ID: org.nativescript.NativeScriptApp
Sep 14 14:10:33 iPhone-de-Carlos com.apple.debugserver-310.2[8930] <Error>: error: timed out trying to send openApplication to org.nativescript.NativeScriptApp.
Sep 14 14:10:33 iPhone-de-Carlos com.apple.debugserver-310.2[8930] <Warning>: 1 +0.000000 sec [22e2/060b]: RNBRunLoopLaunchInferior DNBProcessLaunch() returned error: 'timed out trying to launch app'
Sep 14 14:10:33 iPhone-de-Carlos com.apple.debugserver-310.2[8930] <Warning>: 2 +0.004912 sec [22e2/1c0b]: error: ::read ( -1, 0x2c49ec, 18446744069414585344 ) => -1 err = Bad file descriptor (0x00000009)
Sep 14 14:10:33 iPhone-de-Carlos com.apple.debugserver-310.2[8930] <Warning>: Exiting.
Sep 14 14:10:43 iPhone-de-Carlos wifid[15] <Notice>: WiFi:[463925443.357252]: BG Application: Not Present, BG Daemon: Present. Daemons: networkd apsd 
Sep 14 14:10:43 iPhone-de-Carlos wifid[15] <Notice>: WiFi:[463925443.361976]: BG Application: Not Present, BG Daemon: Present. Daemons: networkd apsd 
Sep 14 14:10:50 iPhone-de-Carlos wifid[15] <Notice>: WiFi:[463925450.876631]: Async scan requested by "locationd" for 1 iterations with maxage=0 priority low on en0
Sep 14 14:10:50 iPhone-de-Carlos wifid[15] <Notice>: WiFi:[463925450.878104]: Enqueuing command type: "Scan" pending commands: 0
Sep 14 14:10:50 iPhone-de-Carlos wifid[15] <Notice>: WiFi:[463925450.879250]: Dequeuing command type: "Scan" pending commands: 0
Sep 14 14:10:50 iPhone-de-Carlos wifid[15] <Notice>: WiFi:[463925450.880265]: Attempting Apple80211ScanAsync on en0
Sep 14 14:10:50 iPhone-de-Carlos locationd[54] <Notice>: need a scan, count, 0, 0, lwatchdog, 0.0, interval, 60.0, needWatchdog, 1
Sep 14 14:10:51 iPhone-de-Carlos wifid[15] <Notice>: WiFi:[463925451.405889]: Completed Apple80211ScanAsync on en0 (0)
Sep 14 14:10:51 iPhone-de-Carlos wifid[15] <Notice>: WiFi:[463925451.409072]: Async scan request completed for "locationd" (0)
Sep 14 14:10:51 iPhone-de-Carlos wifid[15] <Notice>: WiFi:[463925451.448317]: Async scan requested by "locationd" for 1 iterations with maxage=0 priority low on en0
Sep 14 14:10:51 iPhone-de-Carlos wifid[15] <Notice>: WiFi:[463925451.450191]: Enqueuing command type: "Scan" pending commands: 0
Sep 14 14:10:51 iPhone-de-Carlos wifid[15] <Notice>: WiFi:[463925451.450995]: Dequeuing command type: "Scan" pending commands: 0
Sep 14 14:10:51 iPhone-de-Carlos wifid[15] <Notice>: WiFi:[463925451.451627]: Attempting Apple80211ScanAsync on en0
Sep 14 14:10:53 iPhone-de-Carlos wifid[15] <Notice>: WiFi:[463925453.311070]: Completed Apple80211ScanAsync on en0 (0)
Sep 14 14:10:53 iPhone-de-Carlos wifid[15] <Notice>: WiFi:[463925453.312847]: Async scan request completed for "locationd" (0)
Sep 14 14:10:53 iPhone-de-Carlos timed[8365] <Notice>: (Note ) CoreTime: Received timezone "Europe/Madrid" from "Location"
Sep 14 14:10:53 iPhone-de-Carlos timed[8365] <Notice>: (Note ) CoreTime: Current mcc: '0' simulated:'0'.
Sep 14 14:10:53 iPhone-de-Carlos timed[8365] <Notice>: (Note ) CoreTime: Not setting time zone to Europe/Madrid from Location
Sep 14 14:11:24 iPhone-de-Carlos kernel[0] <Debug>: ALS: AppleARMBacklight::setBacklightEnableGated 0 (set level to 0x1c8)
Sep 14 14:11:24 iPhone-de-Carlos kernel[0] <Debug>: AppleMultitouchN1SPI: updating power statistics
Sep 14 14:11:24 iPhone-de-Carlos backboardd[28] <Notice>: Posting 'com.apple.iokit.hid.displayStatus' notifyState=0
Sep 14 14:11:24 iPhone-de-Carlos backboardd[28] <Notice>: MultitouchHID: detection mode: 0->255
Sep 14 14:11:24 iPhone-de-Carlos wifid[15] <Notice>: WiFi:[463925484.412645]: Device display is OFF
Sep 14 14:11:24 iPhone-de-Carlos kernel[0] <Debug>: ALS: AppleARMBacklight::handleMessageGated - framebufferState -> 0
Sep 14 14:11:27 iPhone-de-Carlos wifid[15] <Notice>: WiFi:[463925487.758232]: WoW is Enabled, 1 WoW Clients

**Comment by danicomas** [comment]
I don't understand why after I do ```tns run ios``` if I open Xcode the MapView is selected instead the main app NativeScriptApp @fealebenpae

**Comment by danicomas** [comment]
I want to add the RMDBMapSource too:

```
module RouteMe {
  umbrella header "vendor/route-me/MapView/Map/RouteMe.h"
  export *
  module * { export * }
}

module RMDBMapSource {
  umbrella header "vendor/route-me/MapView/Map/RMDBMapSource.h"
  export *
  module * { export * }
}
```

but the app crashes if add the RMDBMAPSource module. This message appears @fealebenpae :

````
Generating metadata for i386:
Parsed header search paths:
"/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/build/emulator/include"
"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include"
"/Applications/Xcode6.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include"
"/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/NativeScript/include"
"/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/vendor/route-me/MapView/Map"
Parsed framework search paths:
"/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/build/emulator"
"/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios"
"/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/../../lib/iOS"
Clang parameters: -v -x objective-c -fno-objc-arc -fmodule-maps -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -arch i386 -target arm-apple-darwin -std=gnu99 -miphoneos-version-min=7.0 -Wno-unknown-pragmas -Wno-ignored-attributes -ferror-limit=0 -I/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/build/emulator/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode6.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/NativeScript/include -I/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/vendor/route-me/MapView/Map -F/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/build/emulator -F/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios -F/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/../../lib/iOS 
metadata-generation-build-step.sh: line 3: 19779 Abort trap: 6           ./objc-metadata-generator -isysroot "$SDKROOT" -arch $1 -iphoneos-version-min $IPHONEOS_DEPLOYMENT_TARGET -target arm-apple-darwin -std $GCC_C_LANGUAGE_STANDARD -header-search-paths "$HEADER_SEARCH_PATHS" -framework-search-paths "$FRAMEWORK_SEARCH_PATHS" -enable-header-preprocessing-if-needed=true -output-bin "$BUILT_PRODUCTS_DIR/$CONTENTS_FOLDER_PATH/metadata-$1.bin" -output-umbrella "$BUILT_PRODUCTS_DIR/umbrella-$1.h" 2> "$errorLog"
clang version 3.6.0 (tags/RELEASE_360/final)
Target: i386-apple-darwin
Thread model: posix
clang Invocation:
 "clang-tool" "-cc1" "-triple" "i386-apple-ios7.0.0" "-fsyntax-only" "-disable-free" "-main-file-name" "umbrella.h" "-mrelocation-model" "pic" "-pic-level" "2" "-mthread-model" "posix" "-mdisable-fp-elim" "-masm-verbose" "-target-cpu" "yonah" "-target-linker-version" "241.9" "-v" "-dwarf-column-info" "-resource-dir" "../lib/clang/3.6.0" "-isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk" "-I" "/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/build/emulator/include" "-I" "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include" "-I" "/Applications/Xcode6.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include" "-I" "/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/NativeScript/include" "-I" "/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/vendor/route-me/MapView/Map" "-F/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/build/emulator" "-F/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios" "-F/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/../../lib/iOS" "-Wno-unknown-pragmas" "-Wno-ignored-attributes" "-std=gnu99" "-fdebug-compilation-dir" "/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/metadataGenerator/bin" "-ferror-limit" "0" "-fmessage-length" "0" "-stack-protector" "1" "-mstackrealign" "-fblocks" "-fmodule-maps" "-fobjc-runtime=ios-7.0.0" "-fencode-extended-block-signature" "-fobjc-exceptions" "-fexceptions" "-fmax-type-align=16" "-fdiagnostics-show-option" "-x" "objective-c" "umbrella.h"

ignoring nonexistent directory "/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/build/emulator/include"
ignoring nonexistent directory "/Applications/Xcode6.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include"
ignoring nonexistent directory "/Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/../../lib/iOS"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/NativeScript/include
 /Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/vendor/route-me/MapView/Map
 /Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios/build/emulator (framework directory)
 /Users/sergio.reyes/Desktop/NativeScriptApp/platforms/ios (framework directory)
 /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/usr/local/include
 ../lib/clang/3.6.0/include
 /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/System/Library/Frameworks (framework directory)
End of search list.
Assertion failed: (TextDiag && "Unexpected diagnostic outside source file processing"), function HandleDiagnostic, file TextDiagnosticPrinter.cpp, line 153.
Command /bin/sh failed with exit code 1

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Generate\ Metadata build/NativeScriptApp.build/Debug-iphonesimulator/NativeScriptApp.build/Script-C97FD7AC1ADE5369004DB2A4.sh
(1 failure)
Command xcodebuild failed with exit code 65
```
