### ISSUE TITLE
(ios) Need help with setting delegate to multithreading model

### ISSUE THREAD

**Issue by Owchzzz** [NativeScript/NativeScript#7110]
Hi,

Okay so, i need to run a delegat in a separate thread on nativescript. This issue comes up because i am using the twilio voice sdk with callkit, and we have a call listener object there and for some unkown reason, whenever i invoke ngzone / router, the call stops emitting and listening to events, 

I have tested with and without invoking angular ngzone on call accept, and the problem persists only 100% of the time when i invoke angular view updates.

Just wanting to know if this is possible and how would one go about doing this?

**Comment by NickIliev** [comment]
Closing as how-to related and due to inactivity. Please consider posting and searching for a solution in the community channels (SO or the community slack)
