### ISSUE TITLE
Problem with nativescript-popup help me please.

### ISSUE THREAD

**Issue by SebastianCBA** [NativeScript/NativeScript#7111]
Hi! I get this message about error when I open a nativescript-popup from a RadListView:

[Error: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?

How I can stop all activities for priorize the popup?

Thanks in advance!

**Comment by tsonevn** [comment]
Hi @SebastianCBA,
For  `nativescript-popup` related problems, please, use the [plugin's repository](https://github.com/triniwiz/nativescript-popup/issues) and log a new issue there. This repository should be used only for feature requests and bug reports related to `tns-core-modules`.

Regards,
@tsonevn
