### ISSUE TITLE
SegmentedBar doesn't render properly on iOS

### ISSUE THREAD

**Issue by uvigii** [NativeScript/NativeScript#7113]
**Environment**
 - CLI: 5.2.3
 - latest Nativescript preview App

**Describe the bug**
When using html to describe items, SegmentedBar doesn't show any of the tabs and a runtime error is logged in console (iOS only):
_TypeError: undefined is not an object (evaluating 'parent.ios.setTitleForSegmentAtIndex')_

`<SegmentedBar selectedIndex="selectedIndex">
        <SegmentedBarItem title="A"></SegmentedBarItem>
        <SegmentedBarItem title="B"></SegmentedBarItem>
    </SegmentedBar>`

**To Reproduce**
Run the PG Demo.

**Expected behavior**
Same behavior under iOS and Android

**Sample project**
https://play.nativescript.org/?template=play-ng&id=BtPv6K&v=2

**Comment by tsonevn** [comment]
Hi @uvigii,
While using the SegmentedBar component in NativeScript Angular project, you must define the collection of `SegmentedBarItem` via code-behind. Check out the documentation [here](https://docs.nativescript.org/angular/ui/ng-ui-widgets/segmented-bar#basic-segmented-bar).

**Comment by uvigii** [comment]
Hi @tsonevn,
Thank you for clarification.
As a side note defining _SegmentedBarItem_ as _html_ under Android seems to work fine.
Thanks again.

**Comment by vakrilov** [comment]
This seems like a bug. The following should be a valid way to use `SegmentedBar` in Angular:
```
<SegmentedBar> 
  <SegmentedBarItem title="A"></SegmentedBarItem>
  <SegmentedBarItem title="B"></SegmentedBarItem>
</SegmentedBar>
```

**Comment by janoshrubos** [comment]
Tried to reproduce this issue, but it seems to be resolved now.
If this error is still relevant, feel free to open a new issue!
