### ISSUE TITLE
increment ++ not in parameter

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#7114]
In [playground ](https://play.nativescript.org/?template=play-tsc&id=2YgCy0) I have included the following code in the code behind file:

  ```
  let a = ['a', 'b']
    let i = 0
    console.log(a[i++])
```

I would expect in the log file: 'b', yet I get 'a'. This means the increment i++ is not executed if inside the rectangles []. The same is true if I use decrement as in [i--]. I would interpret this as a bug. If not, I would propose a feature request to support the intended behaviour.

**Comment by NathanaelA** [comment]
@jokro - This is proper JS behavior; it is like doing this:
```
let a = ['a', 'b'];
let i = 0;
let x = i;   
i++;
console.log(a[x]);
```
The `++` happens AFTER the value lookup.  

If you want the `++` to happen first you can do it one of these two ways:
`console.log(a[(i++)]);`  // By wrapping it in a parens `()` it is evaluated first.
OR
`console.log(a[++i]);` // By using `++` in front, it happen BEFORE the `i` is used as a index.

**Comment by tsonevn** [comment]
Hi @jokro,
Description of this JavaScript behaviour can also be found in [this StackOverflow thread](https://stackoverflow.com/questions/34797524/js-while-loop-arrayi-how-does-it-work). In my opinion, we can close this issue.

**Comment by jokro** [comment]
Right. ThxOp 8 apr. 2019 07:18 schreef Nikolay Tsonev <notifications@github.com>:Hi @jokro,
Description of this JavaScript behaviour can also be found in this StackOverflow thread. In my opinion, we can close this issue.

**Comment by jokro** [comment]
Thx very muchOp 7 apr. 2019 22:43 schreef Nathanael Anderson <notifications@github.com>:@jokro - This is proper JS behavior; it is like doing this:
let a = ['a', 'b'];
let i = 0;
let x = i;   
i++;
console.log(a[x]);

The ++ happens AFTER the value lookup.
If you want the ++ to happen first you can do it one of these two ways:
console.log(a[(i++)]);  // By wrapping it in a parens () it is evaluated first.
OR
console.log(a[++i]); // By using ++ in front, it happen BEFORE the i is used as a index.
