### ISSUE TITLE
Use Mac OS machine as a "local cloud"

### ISSUE THREAD

**Issue by l4cr0ss** [NativeScript/NativeScript#7115]
**Is your feature request related to a problem? Please describe.**

It frustrates me that there is no middle ground between building iOS apps in the cloud and on a local machine. There should be a way to configure a mac machine to run as a "local cloud".

**Describe the solution you'd like**

I would like a way to setup my Mac Mini as a cloud provider for Nativescript Sidekick cloud builds so that I can develop on my local linux machine and build for iOS without needing to do builds in the cloud proper.

**Comment by NathanaelA** [comment]
Not sure if this will work for you; but my current way I work is I do everything in phpStorm on Linux (used to use Windows, so it works from windows also).  phpStorm I have set to automatically sync to the same folder on the mac (via ssh).   On the mac I just do `tns run` when I first start; and then ignore the mac for the rest of the time.   phpStorm will keep everything in sync with the mac, and the mac will keep everything in sync with the phone/simulator on it.   

I don't know if vscode has a automatic sync on file change plugin; but you can probably whip something up with node and file watching to do the same thing...

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/sidekick-feedback #365](https://github.com/NativeScript/sidekick-feedback/issues/365) via [**ZenHub**](https://www.zenhub.com/)
