### ISSUE TITLE
Android HTTPClient Delete Method Error

### ISSUE THREAD

**Issue by sissingclay** [NativeScript/NativeScript#7116]
Hi,

This following method below works on iOS but not on android. On Android I get the following error back from our API:

Http failure response for URL: 422 OK Unprocessable Entity

```
removeUserSports(
        sport
    ): Observable<ISports> {
        const DATA = {
            data: [
                {
                    type: 'sports',
                    id: sport
                }
            ]
        };

        const httpOptions = {
            headers: this.headerService.addAuthHeaders()
                .headers,
            body: DATA
        };

        return this.http.request<
            ISports
        >(
            'DELETE',
            `${
                ENVIRONMENT.urls
                    .apiClientUri
            }${USER_URI}${FAVOURITE_SPORT_URI}`,
            httpOptions
        );
    }
```

**Comment by NickIliev** [comment]
@sissingclay saying HttpClient I am assuming you are using Angular's HttpCLient.

If that is the case,  you could directly use [the `delete` method](https://docs.nativescript.org/angular/ng-framework-modules/http#http-delete) - here is [a test app](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/NativeScript/issue-7116) demonstrating the usage and confirming that it is working as expected on Android.

**Comment by sissingclay** [comment]
Hi @NickIliev, I've updated my code and have used the `delete method`. Unfortunately in your example data is an empty string and not the object that was passed. Due to this, it's failing. Our server is returning `Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON`

```
{
"args": {},
"data": "",
"files": {},
"form": {},
"headers": {
     "Accept": "application/json, text/plain, */*",
     "Accept-Encoding": "gzip",
     "Content-Type": "application/json",
     "Host": "httpbin.org",
     "User-Agent": "Dalvik/2.1.0 (Linux; U; Android 9; Android SDK built for x86 Build/PSR1.180720.075)"
   },
"json": null,
"origin": "86.22.11.245, 86.22.11.245",
"url": "https://httpbin.org/delete"
}
```

**Comment by sissingclay** [comment]
Hi @NickIliev, this is the response from iOS.

```
{
"args": {},
"data": "{\"data\":[{\"type\":\"sports\",\"id\":1234}]}",
"files": {},
"form": {},
"headers": {
"Accept": "application/json, text/plain, */*",
"Accept-Encoding": "br, gzip, deflate",
"Accept-Language": "en-us",
"Content-Length": "38",
"Content-Type": "application/json",
"Host": "httpbin.org",
"User-Agent": "Mozilla/5.0 (iPhone; CPU OS 12_2 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/12.2 Mobile/10A5355d Safari/8536.25"
},
"json": {
"data": [
{
"id": 1234,
"type": "sports"
}
]
},
"origin": "86.22.11.245, 86.22.11.245",
"url": "https://httpbin.org/delete"
}
```

**Comment by NickIliev** [comment]
@sissingclay looking at[ the Angular example for using `DELETE` i](https://angular.io/tutorial/toh-pt6#delete-a-hero)t is explicitly said that there is no data that can be sent (quote: `you don't send data as you did with put and post.`). I've also looked at the [specification of the DELETE method](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE), and it seems that the response body is flagged with `MAY`.

Going further it seems that the entity body might be completely ignored as [discussed in this thread](https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request).

All of the above leads me to the conclusion that the DELETE method should be used without a body - pass the delete parameters in your delete URL.
