### ISSUE TITLE
Prevent tabview index change

### ISSUE THREAD

**Issue by jinusean** [NativeScript/NativeScript#7117]
Currently watching for tabViewIndex change in `selectedIndexChange` event, but there is no way to prevent the tabs from changing.

**Comment by tsonevn** [comment]
Hi @jinusean,
You can set `isUserInteractionEnabled` to `false` on the TabView component. This will disable tab change. 
```
 <TabView isUserInteractionEnabled="false" >
.......
</TabView>
```

**Comment by jinusean** [comment]
Hi @tsonevn,

That seems to prevent all interaction with the view, even scrolling is disabled. 

For clarification the exact use case is:
1. Current view has unsaved form.
2. User clicks on another tab.
3. Confirm dialog is presented.
4. Only switch to tab if user confirms ok.

**Comment by tsonevn** [comment]
Hi @jinusean,
Thank you for the description of your use case.  I found that there is a feature request(#6095) for introducing a [new event](https://github.com/NativeScript/NativeScript/issues/6095#issuecomment-427384917), which should be fired before `selectedIndexChanged ` and will allow the developers to implement their custom behaviour. I would suggest to keep track on the other issue and to comment it if you need to add some more info about the feature.
