### ISSUE TITLE
tns-core-modules/ui/animation/animation.js:276:74: JS ERROR TypeError: undefined is not an object (evaluating 'nativeView.layer')

### ISSUE THREAD

**Issue by SephReed** [NativeScript/NativeScript#7118]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.3.1 version and is up to date.
✔ Component tns-core-modules has 5.4.0-next-2019-04-03-175957-02 version and is up to date.
✔ Component tns-android has 5.4.0-2019-04-03-095324-01 version and is up to date.
✔ Component tns-ios has 5.4.0-2019-04-03-180044-02 version and is up to date.

**Describe the bug**

I have some code which switches out child views inside a layout base.  Only on iOS, and somewhat randomly, there will be an error :
```
CONSOLE WARN file:///app/tns_modules/tns-core-modules/application/application.js:276:26: Fatal JavaScript exception - application has been terminated.
file:///app/tns_modules/tns-core-modules/ui/animation/animation.js:276:74: JS ERROR TypeError: undefined is not an object (evaluating 'nativeView.layer')
```

This is the line of code at which it happens:
https://github.com/NativeScript/NativeScript/blob/9790b0e89110b5fea414690f09f41961ebd5bec7/tns-core-modules/ui/animation/animation.ios.ts#L280

**To Reproduce**

I am unable to consistently reproduce this issue.  I know it has something to do with removing child views and adding them.  It would appear to be an issue specific to ios perhaps removing native views (setting it to undefined) under different circumstances from android. 

 

**Expected behavior**
The ability to add and remove views should be fine.  If nativeview is undefined, perhaps an error should be thrown to help describe how/why?

**Sample project**

To give at least some insight in what my code sort of does, this example might help:

```
const stack = () => new StackLayout();
const root = stack();
const view1 = stack();
let currentView;
setInterval(() => {
  if (currentView && currentView.parentNode) {
    const removeMe = currentView;
    removeMe.animate({background: "red"})
    .then(() => removeMe.parentNode.removeChild(removeMe));
  }
  currentView = (currentView !== view1) ? view1 : stack();
  root.addChild(currentView);
  root.animate({background: "green"});
}, 150);
```

**Additional context**

My current speculation is that animate is trying to act on a native object before it has come into existence.  Seems like a race condition.  If that is the case, then perhaps there will be a good event to hook into to make sure animate is not called before native view exists.

**Comment by NickIliev** [comment]
@SephReed I think this is related to the usage of `setInterval` with 150ms and at the same time recreating a view each 300ms (as the default animation duration is 300ms). Either remove the `setInterval` or increase the interval time to be more than the recreation of the view (example [here](https://play.nativescript.org/?template=play-tsc&id=8uKGnS)).

**Comment by SephReed** [comment]
I think the second issue I posted gets closer to what is a shared root cause, so I'm going to close this one.

https://github.com/NativeScript/NativeScript/issues/7119
