### ISSUE TITLE
Multiple app breaking issues revolving around IOS and LayoutBase.addChild()

### ISSUE THREAD

**Issue by SephReed** [NativeScript/NativeScript#7119]
**Environment**
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.3.1 version and is up to date.
✔ Component tns-core-modules has 5.4.0-next-2019-04-03-175957-02 version and is up to date.
✔ Component tns-android has 5.4.0-2019-04-03-095324-01 version and is up to date.
✔ Component tns-ios has 5.4.0-2019-04-03-180044-02 version and is up to date.

**Describe the bug**
I'm finding a lot of app breaking bugs involved with IOS and use of the LayoutBase.addChild() and removeChild() functions.  These issues include:

- Broken Event Listening - native buttons which show response to taps (change color) but no longer call the event listeners applied to them
- Broken Styling - many views have completely broken styling.  Updating the sass file (with no real changes) will regenerate them in place correctly.  The sass is correct, but not being applied correctly.
- Undefined nativeView - This was the first of many issues I've run into with ios.  A link to the issue is here: https://github.com/NativeScript/NativeScript/issues/7118

**To Reproduce**

Basically, make liberal use of the LayoutBase.addChild() and removeChild() functions on iOS.  Eventually they start falling apart.

**Sample project**

I don't have much for a sample project, but this code kind of shows what type of stuff I'm doing.  The following code should be pretty close to functional, and should create a couple stack layout items which get flip between eachother on touch using the addChild() and removeChild() functions.  Eventually, at least for me, they start to lose styling, have non working buttons, or even crash the app due to missing nativeView.
```
const stack = () => new StackLayout();
const label = (text) => {
  const out = new StackLayout();
  out.text = text;
  return out;
}
const root = stack();

let currentView;
const flipView = () => {
  if (currentView && currentView.parent) {
    const removeMe = currentView;
    removeMe.animate({background: "red"})
    .then(() => removeMe.parent.removeChild(removeMe));
  }
  currentView = (currentView !== view1) ? view1 : view2;
  root.addChild(currentView);
  root.animate({background: "green"});
}


const view1 = stack();
view1.addChild(label("View 1"));
view1.addEventListener("touch", flipView);
const view2 = stack();
view2.addChild(label("View 2"));
view2.addEventListener("touch", flipView);
```

**Additional context**

The biggest clues I've found on this so far are that nativeView is undefined AND **sometimes view1 or view2 will have a non undefined parent value when addChild is called, and the parent value will *not* match root**.  To me, this indicates something about ios is messing with native views, likely failing to update them, and dropping event listeners as a result.

For example, this error...
```
file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:417:100: JS ERROR Error: View already has a parent. View: AbsoluteLayout(109) Parent: AbsoluteLayout(45)
```
... is very strange because the View in this circumstance only ever has one AbsoluteView it is a child of.  To get this error, I update sass, wait for the refreshed look, then do a flip view.

**Comment by SephReed** [comment]
More clues.

If instead of creating `view1` and `view2` once and reusing them, you create them new every time:
```
const view = (num) => {
  const out = new StackLayout();
  out.addEventListener("touch", flipView);
  out.addChild(label(`View ${num}`);
  return out;
}

...

// then replace
// currentView = (currentView !== view1) ? view1 : view2;
 currentView =  Math.random() > 0.5 ? view(1) : view(2);
```

If the view is recreated every time, the buttons will no longer break and the native view issue is fixed, but you'll end up with redundant event listeners.  Basically, the point at which my buttons would normally break, they now end up calling console.log multiple times.  The longer I switch back and forth, slowly there will become more and more responses per click.

Something funky is going on with the way nativescript manages ios views and event listeners.  I only ever add a single listener to any view, but they keep piling up.

**Comment by NickIliev** [comment]
@SephReed are we talking about NativeScript Core app or Angular (or Vue.js) based application. 
The methods `addCh8ld` & `removeChild` should be used only in Core apps (plain JS or TSC flavors) as Angular has a different way of rendering the UI. If using Angular you shouldn't use the add/remove methods but the Angular way meaning custom components, structural directives, etc..

If you are hitting this one in Core app then please try to provide a demo Playground. Recreating the added views each time is the way to go - you could **detach** the listeners before when you are removing the child to avoid pilling up attached listeners in the memory. Info about removing listeners [here](https://docs.nativescript.org/core-concepts/events#removing-an-event-listener) + adding/removing weak event listeners [here](https://docs.nativescript.org/core-concepts/events#working-with-weak-events-Adding) Still if you are hitting a different issue I will be happy to investigate your case by looking into the actual test app.

**Comment by SephReed** [comment]
> are we talking about NativeScript Core app or Angular (or Vue.js) based application?

Core app

> Recreating the added views each time is the way to go

I'm trying not to do this for my app.  So far, I've managed to solve most of my issues by never removing the views from components and setting "collapse" and "visible" instead.  I can't give much more direction on this than I have, but there's something buggy with ios and add/remove child.  In particular, when recycling children.

**Comment by SephReed** [comment]
I've managed to narrow this bug down more, so I'm closing this issue and opening a better one.
