### ISSUE TITLE
Ability to style EditableTextBase's hint property

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#712]
Right now there's either no clear way to style the placeholder hint text for EditableTextBase or that you can't. Particularly changing the colour. 

possible properties could be:

* `placeholder-color`

Unsure if these inherit from the normal font properties, but:
* `placeholder-font`
* `placeholder-font-size`
* `placeholder-font-weight`
* `placeholder-font-family`
* `placeholder-text-align`

**Comment by lscown** [comment]
The way I am currently doing it for iOS:

```js
textField.ios.attributedPlaceholder = NSAttributedString.alloc().initWithStringAttributes("placeholder text", new NSDictionary([UIColor.whiteColor()], [NSForegroundColorAttributeName]));
```

and Android (with the hint property set on the textfield object):

```js
textField.android.setHintTextColor(android.graphics.Color.parseColor("#FFFFFF"));
```

**Comment by rclai** [comment]
One thing I noticed is that the hints for secure text fields have more letter spacing than a regular textfield in Android.

**Comment by stevetayloruk** [comment]
+1

**Comment by gadonski** [comment]
+1

**Comment by tsjishan** [comment]
+1

**Comment by hekigan** [comment]
+1

**Comment by hekigan** [comment]
Something that might help others.
In the "app/App_Ressources/Android/values/styles.xml", with the following changes you can control the TextInput's hint color.

```
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:android="http://schemas.android.com/apk/res/android">
	<style name="AppThemeBase" parent="Theme.AppCompat.Light.NoActionBar">
           ....
            <item name="android:editTextStyle">@style/Application</item>
           ....
        </style>
    
	<style name="Application" parent="Widget.AppCompat.EditText">
             <item name="android:textColorHint">#777777</item>
        </style>
</resources> 
```

This will effectively change the text hint color for **Android platform only**

**Comment by musaaslan** [comment]
+1

**Comment by Gustavo47** [comment]
+1

**Comment by jvzanatta** [comment]
+1

**Comment by Southpaw17** [comment]
+1

**Comment by simonmclean** [comment]
+1

**Comment by nsndeck** [comment]
I've just added `placeholder-color` css property with #2644 which will work for TextField (Android and iOS) and TextView (Android). Unfortunately iOS also supports other style options like font, weight ..., but for Android we can change only color. Therefore we end up with a support for placeholder(hint) color only.

**Comment by joshcomley** [comment]
@nsndeck I am trying this on a Samsung S7 and it doesn't seem to be affecting the colour from blue.

In theory I should be able to write this:

    TextField {
      placeholder-color: #FFFFFF;
    }

And have it come out white, right?
