### ISSUE TITLE
Unicode characters on the initial page cause crashes on iOS

### ISSUE THREAD

**Issue by ludwiktrammer** [NativeScript/NativeScript#7120]
**Environment**
 - CLI:  5.3.1
 - Cross-platform modules: 5.3.0
 - Android Runtime: 5.3.1
 - iOS Runtime: 5.3.1
 - Plugin(s): nativescript-dev-typescript, nativescript-dev-webpack

**Describe the bug**
If the XML of the app's first page (the one defined in the frame's `defaultPage`) includes Unicode characters outside of the basic ASCII set (for example Polish `Ł`) then some of the properties defined in the XML get set to `undefined` instead of their actual values. So far I observed this behavior with `returnKeyType` and `autocapitalizationType` on `TextField`. If the properties are present in XML, NativeScript tries to set their values to `undefined` (instead of the actual values defined in XML), resulting in the app crashing. The problem doesn't occur if there is no extended Unicode character present in the same XML file and only occurs with the very first page, only on iOS.

**Error Messages**
When tested with `returnKeyType` on `TextField`:

```
JS ERROR TypeError: undefined is not an object (evaluating 'returnKeyType.toString')
```

When tested with `autocapitalizationType` on `TextField`:

```
JS ERROR Error: Invalid autocapitalizationType value:undefined
```

**To Reproduce**
1. Add `Ł`, `ą`, `ś`, `ć`, `❤️` or other extended Unicode character anywhere inside the XML of your app's initial page (for example inside `Label`'s `text` property).
2. Add `<TextField autocapitalizationType="none"/>` to the same page.
3. `tns run ios --emulator`

**Expected behavior**
It should behave the same with and without extended Unicode characters.

**Sample project**
A repository with a demo of the problem: https://github.com/ludwiktrammer/ns_unicode_start_bug

This demo is based on NativeScript Hello World template (NativeScript+TypeScript). The only file that was modified to demonstrate the problem is `app/main-page.xml`. I left all other files untouched. The app should immediately crash after launching. Removing the `Ł` should stop the crashing.

**Comment by ludwiktrammer** [comment]
I now also observed the same behavior on pages other than the initial one.

**Comment by manoldonev** [comment]
@ludwiktrammer as a temporary workaround you can try using the [html entities](https://graphemica.com/%C5%81) for such Unicode characters like this:
``` xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="onNavigatingTo">
<StackLayout>
    <Label text="Example of unicode character: &#321; &#322; &#323;" />
    <TextField returnKeyType="next" />
</StackLayout>
</Page>
```

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/ios-runtime #1130](https://github.com/NativeScript/ios-runtime/issues/1130) via [**ZenHub**](https://www.zenhub.com/)
