### ISSUE TITLE
Cannot find any registered applications for Apple ID in iTunes Connect.

### ISSUE THREAD

**Issue by Nurgunkalol** [NativeScript/NativeScript#7126]
"tns-ios": {
      "version": "4.2.0"
}

One week ago was uploaded last version to testflight it was ok,
but today it calls error:
"httpRequest: Done. code = 200
Cannot find any registered applications for Apple ID in iTunes Connect."

**Comment by tsonevn** [comment]
Hi @Nurgunkalol,
I checked your case, however, the given information is not enough to investigate further the issue. Can you provide more info about the problem: sample code snippets and steps, that can be used for recreating the issue, as well as full error log?
Meanwhile, make sure that your device is connected to the Internet and that you are logged in correctly with your Apple ID on it. More info about the suggested solutions can be found [here](https://support.apple.com/en-us/HT201400).

**Comment by chuckmitchell** [comment]
I have the same issue, my script was working 2 weeks ago and now the same error:

My publish command:
`tns publish ios $ITUNES_ACCT $ITUNES_PWD --team-id $ITUNES_TEAM_ID --bundle --env.uglify --release --for-device`

And the output:
`...
Xcode build...
2019-04-30 10:36:02.952 xcodebuild[3877:90189] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/p9/plxwrsls5ddbbvgbhbkbhkvc0000gn/T/mymobilenative_2019-04-30_10-36-02.950.xcdistributionlogs'.
Exported mymobilenative to: /Users/kanayo/mymobile-native-25-tunstall/mymobile-native/platforms/ios/build/archive
Export at: /Users/kanayo/mymobile-native-25-tunstall/mymobile-native/platforms/ios/build/archive/mymobilenative.ipa`

**Comment by chuckmitchell** [comment]
Wanted to add 2 more pieces of information:

1. My Apple ID use belongs to 2 organizations.
1. I can upload the generated .ipa manually with the Application Loader.

**Comment by chuckmitchell** [comment]
@Nurgunkalol @tsonevn 
Can we re-open this one? Please let me know if you need more information.

**Comment by tsonevn** [comment]
Hi @chuckmitchell,
This issue seems to be fixed with PR https://github.com/NativeScript/nativescript-cli/pull/4547. A new CLI with the fix will be released soon. For now, I would suggest to keep using `Application Loader`.

**Comment by hhanckes** [comment]
Hi @tsonevn , I am running with the same issue, do you know if the PR was accepted and how to upgrade the CLI ? thanks.-

**Comment by tsonevn** [comment]
Hi @hhanckes,
The PR was accepted and released. Regarding the problem, can you provide more info about the issue you are facing and your environment({N} CLI, tns-ios, tns-core-modules versions)?
