### ISSUE TITLE
ReturnKeyType Listener

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#713]
Currently you can set a ReturnKeyType on a EditableTextBase. This is great, however it's really only cosmetic at this point as you can't listen to when the element "Next" or "Done" is pressed.

Would be good to:
* When `Next` is pressed, listen and then be able to focus on another textField
* When `Done` is pressed, listen and then run some code

**Comment by NathanaelA** [comment]
:+1:  I just noticed the same thing.  Their is no re-published event for the existing listener.  The current listener takes the key and hides the soft keyboard.

**Comment by PeterStaev** [comment]
:+1:

**Comment by x4080** [comment]
Hi, and how to use this new feature ? there are no next previous button on iOS keyboard, and how to add the listener for moving to next textfield for example ?

Thanks

**Comment by x4080** [comment]
I did some trial, and maybe the best to remove owner.dismissSoftInput() in the onFocusChange and in the onEditorAction (editable-text-base.android.js) since it automatically go to the next textedit if there is any and dismiss the keyboard when it is the only textedit (on android 5, I don't know in other android version)

Havent dig in the iOS yet though

**Comment by PeterStaev** [comment]
Try this:
```XML
<Page xmlns="http://www.nativescript.org/tns.xsd">
  <StackLayout>
    <TextField id="user-name" returnKeyType="next"  returnPress="userNameReturnPress"/>
    <TextField id="password" returnKeyType="go"  returnPress="performLogin"/>
  </StackLayout>
</Page>
```
```TypeScript
import pages = require("ui/page");
import textField = require("ui/text-field");

var passwordTextField: textField.TextField

export function pageLoaded(args: observable.EventData)
{
    var page = <pages.Page>args.object;

    passwordTextField = page.getViewById<textField.TextField>("password");
}
export function userNameReturnPress(args: observable.EventData)
{
    passwordTextField.focus();
}
export function performLogin(args: observable.EventData)
{
    // Some Code
}
```

**Comment by x4080** [comment]
Thanks Peter

**Comment by orsag** [comment]
This @PeterStaev solution does not work anymore after upgrade to 1.7, userNameReturnPress is never fired. Tested on real device. Also just to focus() textfield does not show the keyboard, annoying.

**Comment by PeterStaev** [comment]
@orsag this is because there are problems with it i the 1.7 version see  #1721
