### ISSUE TITLE
Appstore Upload 

### ISSUE THREAD

**Issue by narusevic** [NativeScript/NativeScript#7131]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.3.1
 - Cross-platform modules: 5.4.0-next-2019-04-03-110627-01
 - Android Runtime: 5.4.0-2019-04-03-095324-01
 - iOS Runtime: 5.4.0-2019-04-02-034159-01
 - Plugin(s): -

**Describe the bug**
I am using nativescript way to submit application to Apple Store. This exact workflow worked, before, but suddenly it stopped working. I am getting error: **Cannot find any registered applications for Apple ID _appleID_ in iTunes Connect.**

**To Reproduce**
- tns build ios --bundle --release --forDevice --provision _privisionId_
- tns appstore upload --ipa _ipaUrl_
- entering my _Apple ID_ and _App Specific Password_
- getting described error

**Expected behavior**
Submit application to Apple Store

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-cli #4527](https://github.com/NativeScript/nativescript-cli/issues/4527) via [**ZenHub**](https://www.zenhub.com/)
