### ISSUE TITLE
Destroy component/page? Angular/N

### ISSUE THREAD

**Issue by mchallenger88** [NativeScript/NativeScript#7133]
I have an observable object on a page. After three successive route changes, I set this object to null, and it creates an error on the page that should have been long ago destroyed. 

Page 1 - Object added to an observable on this page
Routing to Page 2 - No changes to the object.
Routing to Page 3 - No changes to the object.
Routing to Page 4 - The object is set to null and an error is generated with the stack trace referencing Page 1.

This seems a little crazy. How can I destroy a page on navigatedFrom?

**Comment by tsonevn** [comment]
Hi @mchallenger88,
Can you provide more info about your use case and what you are trying to achieve as a final result? Sample project, which demonstrates your scenario will be highly appreciated.
I  am not sure that I understand the scenario correctly, however, if you need to load a Page without an option to navigate back to the previous one, you can use `clearHistory` property and set it to true.

**Comment by mchallenger88** [comment]
At the time of writing, I was confident that I had unsubscribed to all my observables (or used them only with async in the html), on double-checking my code I did find one instance where I subscribed to an observable and failed to unsubscribe. My mistake. Sorry.
