### ISSUE TITLE
ActionBar is not showing

### ISSUE THREAD

**Issue by limemloh** [NativeScript/NativeScript#7139]
**Environment**
Tested on NativeScript Playground
 - Android Runtime: 5.3.0

**Describe the bug**

ActionBar is not showing when added through JavaScript.

I have created a Page and added a label to verify that it actually loads the app, but I can't get the action bar to show.

**Sample project**

https://play.nativescript.org/?template=play-tsc&id=5vJO8P&v=2

**Additional context**

Only tested using an Android device.

**Comment by tsonevn** [comment]
Hi @limemloh,
For showing an ActionBar, you need to create a new Frame and navigate to the newly created page. Check out the sample project [here](https://play.nativescript.org/?template=play-tsc&id=5vJO8P&v=4).

**Comment by limemloh** [comment]
Thank you @tsonevn 
Sorry for the inconvenience.
