### ISSUE TITLE
Unicode issue with http module

### ISSUE THREAD

**Issue by burningTyger** [NativeScript/NativeScript#7143]
**Environment**
tns info
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 5.3.1 and the latest available version is 5.3.2.
✔ Component tns-core-modules has 5.3.1 version and is up to date.
✔ Component tns-android has 5.3.1 version and is up to date.
⚠ Update available for component tns-ios. Your current version is 5.2.0 and the latest available version is 5.3.1.
**Describe the bug**
I'm using the http module to hit my API. It works fine with ASCII characters but fails with Unicode characters such as Arabic. See the difference in requests between Android 5 and 7. Android 7 works just as expected in Android 5 it fails. See the logs of the request on my server:
```
213.... - - [13/Apr/2019:07:13:04 +0000] "GET /a/\xDA\xA9 HTTP/1.1" 200 2 "-" "Dalvik/2.1.0 (Linux; U; Android 5.0.2; Android SDK built for x86_64 Build/LSY66K)"
213.... - - [13/Apr/2019:07:13:06 +0000] "GET /a/\xDA\xA9 HTTP/1.1" 200 2 "-" "Dalvik/2.1.0 (Linux; U; Android 5.0.2; Android SDK built for x86_64 Build/LSY66K)"
213.... - - [13/Apr/2019:07:13:08 +0000] "GET /a/\xDA\xA9 HTTP/1.1" 200 2 "-" "Dalvik/2.1.0 (Linux; U; Android 5.0.2; Android SDK built for x86_64 Build/LSY66K)"
213.... - - [13/Apr/2019:07:13:10 +0000] "GET /a/\xDA\xA9\xD8\xA7 HTTP/1.1" 200 2 "-" "Dalvik/2.1.0 (Linux; U; Android 5.0.2; Android SDK built for x86_64 Build/LSY66K)"
213.... - - [13/Apr/2019:07:13:14 +0000] "GET /a/\xDA\xA9\xD8\xA7\xD8\xB1 HTTP/1.1" 200 2 "-" "Dalvik/2.1.0 (Linux; U; Android 5.0.2; Android SDK built for x86_64 Build/LSY66K)"
213.... - - [13/Apr/2019:07:13:23 +0000] "GET /a/%DA%A9%D8%A7 HTTP/1.1" 200 4156 "-" "Dalvik/2.1.0 (Linux; U; Android 7.0; Android SDK built for x86 Build/NYC)"
213.... - - [13/Apr/2019:07:13:26 +0000] "GET /a/%DA%A9%D8%A7%D8%B1 HTTP/1.1" 200 1488 "-" "Dalvik/2.1.0 (Linux; U; Android 7.0; Android SDK built for x86 Build/NYC)"
```
![Screenshot from 2019-04-13 09-13-48](https://user-images.githubusercontent.com/263378/56076128-55c28100-5dcd-11e9-929a-43281c27b93c.png)

**To Reproduce**

    http.getJSON(`https://api.farhang.im/a/کار`)

**Expected behavior**
I'd expect the http module to send the exact same request independent of the Android version

**Sample project**
I'm using a svelte-native app: https://github.com/burningTyger/farhang-ns

**Additional context**

A current workaround is to use this snippet here:

    const uri = encodeURI(`https://api.farhang.im/a/کار`)
    http.getJSON(uri)

**Comment by NickIliev** [comment]
@burningTyger that's somehow to be expected as non-Unicode characters are not to be used for constructing URLs  ([see RFC-1738 p.2.2](http://www.faqs.org/rfcs/rfc1738.html)). Although the newer versions of Android have better HTTP implementation we are using the native capabilities so the limitation of the older Android versions are to be handled manually in this case.


Here are some of the recommendations for using ASCII only with HTTP URLs:

>  URLs are written only with the graphic printable characters of the
>    US-ASCII coded character set.

and also

>  Thus, only alphanumerics, the special characters "$-_.+!*'(),", and
>    reserved characters used for their reserved purposes may be used
>    unencoded within a URL.
> 


Handling the encoding of nonconforming URLs (e.g. as you have done with encodeURI) is the way to go in similar cases.

**Comment by burningTyger** [comment]
Ok, thank you for the clarification.
