### ISSUE TITLE
How to disable and remove default NativeScript project splash screen on iOS platform

### ISSUE THREAD

**Issue by Izrab** [NativeScript/NativeScript#7144]
I searched on Internet to find how do I disable and remove the default splash screen that comes from create new project in NativeScript Sidekick, I found an answer for Android platform, but couldn't find an answer or solution for iOS platform.

How do I disable and remove the default splash screen that comes from new create project in Sidekick on iOS platform?

My project is Core XML/Vanilla JavaScript

**Comment by tsonevn** [comment]
Hi @Izrab,
Check out the article [here](https://docs.nativescript.org/tooling/publishing/creating-launch-screens-ios), where it is described, how to change the application's icons and launch screen. Following the instructions, you can replace the default splash screen with your custom one.

**Comment by Izrab** [comment]
@tsonevn , I did not asked how do I change the default splash screen, I asked how do I disable and remove it, i.e. not showing at all, ?

This issue should not be closed, because your answer is not related to my question at all.

**Comment by DickSmith** [comment]
@Izrab 
https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/launch-screen/
> A launch screen appears instantly when your app starts up. The launch screen is quickly replaced with the first screen of your app, giving the impression that your app is fast and responsive. The launch screen isn’t an opportunity for artistic expression. It’s solely intended to enhance the perception of your app as quick to launch and immediately ready for use. **Every app must supply a launch screen.**

*(emphasis added)*
