### ISSUE TITLE
WebPack: custom xml-component tap event does not work anymore when there is no code-behind file

### ISSUE THREAD

**Issue by felix-idf** [NativeScript/NativeScript#7150]
**Environment**
 - CLI: 5.3.2
 - Cross-platform modules: 5.3.1
 - Android Runtime: 5.3.1
 - iOS Runtime: -
 - Plugin(s): -

**Describe the bug**
In our app, we want to share some xml-snippets between several pages, but only the UI part.

```
//./shared/my-component.xml
<StackLayout backgroundColor="yellow" padding="10">
    <Button text="Button 1" tap="customTapEvent1"/>
    <Button text="Button 2" tap="customTapEvent2"/>
</StackLayout>
```

```
//./main-page.xml
<Page xmlns:shared="shared" navigatingTo="onNavigatingTo">
    <!--  ...  -->
    <StackLayout>
        <shared:my-component/>
    </StackLayout>
</Page>
```

```
//./main-page.js
exports.customTapEvent1 = function (args) {
    alert("customTapEvent1");
};


exports.customTapEvent2 = function (args) {
    alert("customTapEvent2");
};
```

So there is no code-behind file for the my-component.xml.
We only want to shre the UI part and the tap events of the buttons should differ from page to page.

When running the app with **tns run android**, everything works as expected.
But when running the app using **tns run android --bundle**, the tap event is not raised at all.

I know, that this would work by adding a my-component.js file and moving those tap events to that file, but we really want to share only the UI part, so this is no solution for us.

**Sample project**
For an unknown reason, I am not able to paste my zipped sample project here, I will try to do that in the comments.

**Comment by felix-idf** [comment]
Here is the complete sample project
[WebPackIssue.zip](https://github.com/NativeScript/NativeScript/files/3080886/WebPackIssue.zip)

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-dev-webpack #865](https://github.com/NativeScript/nativescript-dev-webpack/issues/865) via [**ZenHub**](https://www.zenhub.com/)
