### ISSUE TITLE
Flex rows/cols in GridLayout

### ISSUE THREAD

**Issue by SephReed** [NativeScript/NativeScript#7151]
**Is your feature request related to a problem? Please describe.**
 
I have a grid in which I would like to _disproportionately_ spread the excess area.  The docs show that `*` will spread it _evenly_ amongst all rows/cols which have a `*` value.  (https://docs.nativescript.org/ui/layouts/layout-containers#gridlayout-properties)

**Describe the solution you'd like**

I would like to be able to use `1fr`, `3fr`, etc as a row/col value, and have it be treated like flex grow values (ie 1:3 means 1/3 excess area consumption rate).

**Describe alternatives you've considered**

If I could use flexbox in this scenario, it would be nice, but there's a lot of overlap amongst components.  I've thought of padding my grid by adding 100 rows of `*`, distributed to different places I'd like to grow more/less, but it's a bit too hacky of a solution.

**Comment by tsonevn** [comment]
HI @SephReed,
You can set a number before Star(`*`) defined in the `rows` or `columns` options. This will tell the GridLayout, what part from the available space should be allocated for a specific component when we have multiple `*` defined for the rows or columns. For example:    
```
<GridLayout rows="*, 3*" columns="">
        <Label backgroundColor="green" text="Item 1" textWrap="true" />
        
        <Label backgroundColor="blue" row="1" text="Item2" textWrap="true" />
    
</GridLayout>
```
Let me know if I am missing something or if your case is different.

**Comment by SephReed** [comment]
No, this should do it!  I couldn't find this feature in the docs, btw. (https://docs.nativescript.org/ui/layouts/layout-containers#gridlayout-properties).  It might just be being blind though.

**Comment by tsonevn** [comment]
HI @SephReed,
The scenario described in my previous comment can be found in the second GridLayout's example in the [layout-containers article](https://docs.nativescript.org/ui/layouts/layout-containers#gridlayout). 
I think that we can close this issue.

**Comment by SephReed** [comment]
I really think it would be worth it to include this feature in the description section of the docs.  It's really never specified except by example.
