### ISSUE TITLE
Unable to send a custom message for LocalBroadcastReceiver in Android

### ISSUE THREAD

**Issue by NikolayBa** [NativeScript/NativeScript#7152]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  5.2.3
 - Cross-platform modules: 5.2.2
 - Android Runtime:   5.2.1
 - iOS Runtime: not applicable
 - Plugin(s):  angular, dev dependency tns-platform-declarations

**Describe the bug**

Hello guys,
I am unable to broadcast a message from one part of an application to another, more specifically from an Android background service to an angular component so one can work with it in the UI. I am not sure if the LocalBroadCastManager is not being instantiated properly or if the intent is even created.

I am trying to follow the approach, as described in the first answer in here:
https://stackoverflow.com/questions/30629071/sending-a-simple-message-from-service-to-activity

and this documentation 
https://docs.nativescript.org/ns-framework-modules/application#android-broadcast-receiver

In NS terms I am sending the message like this:
```
      let intent = new android.content.Intent("customservice");
        var broadcastManager = android.support.v4.content.LocalBroadcastManager.getInstance(utils.ad.getApplicationContext());
        broadcastManager.sendBroadcast(intent);
    }
```

But then I never receive it

        app.android.registerBroadcastReceiver("customservice",

           (androidContext, intent) => {
                console.log("________________________________________________Data Received");
                that.data = intent.getIntExtra("message",-1/*default value*/);
                console.log("Data + " + that.data);
        });

 Note: - The receiving end seems to be okay, since I can send the broadcast directly via adb and the component receives it. 
https://stackoverflow.com/questions/22634446/sending-intent-to-broadcastreceiver-from-adb

Additionally, it works when I subscribe to the system messages.

So the problematic part is in the sending of the messages.

**To Reproduce**

1. Create the a background service and send a custom message via broadcast
2. Register a local BroadcastReceiver to receive the message
3. The message is never received

**Sample project**

Here is an my example Repo :
https://github.com/NikolayBa/NativeScriptTestAndroidService

More specifically:
https://github.com/NikolayBa/NativeScriptTestAndroidService/blob/master/src/app/testAndroidService.ts#L74

**Additional context**

The reason for the service being initialized in main.ts is that when the service starts Sticky, angular cannot be initialized.  More info https://github.com/NativeScript/android-runtime/pull/1348
However, that shouldn't make much of a difference.  Let me know if you need more info

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/android-runtime #1351](https://github.com/NativeScript/android-runtime/issues/1351) via [**ZenHub**](https://www.zenhub.com/)
