### ISSUE TITLE
hooks folder isn't generated when node_modules are present

### ISSUE THREAD

**Issue by armpogart** [NativeScript/NativeScript#7155]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.3.1
 - Cross-platform modules: 5.3.1
 - Android Runtime: 5.3.1
 - iOS Runtime: 5.3.1
 - Plugin(s):

**Describe the bug**

When `node_modules` folder is present and `hooks` folder is not present, `tns install` doesn't generate it, it only generates `platforms` folder. That causes to build fail afterwards with not clear error message.

**To Reproduce**

After creating clear project remove `hooks` folder and run `tns install`.

**Expected behavior**
Hooks folder to be regenerated and on `tns build` or `tns run` clear message that `hooks` folder is not present.

**Sample project**

**Additional context**

It is usual practice to cache `node_modules` in CI environment which will prevent `hooks` folder to be generated on `tns install`. Also the lack of clear message and some other unrelated message caused me to debug issue for several hours.

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-cli #4544](https://github.com/NativeScript/nativescript-cli/issues/4544) via [**ZenHub**](https://www.zenhub.com/)
