### ISSUE TITLE
`setNumber` in application-settings inaccuracy on Android

### ISSUE THREAD

**Issue by Frederiks96** [NativeScript/NativeScript#7157]
**Environment**
-  ⚠ Update available for component nativescript. Your current version is 5.2.0 and the latest available version is 5.3.2.
 - Cross-platform modules (tns-core-modules): 5.3.1
 - Android Runtime: 5.2.1
 - iOS Runtime: 5.2.0

**Describe the bug**
Storing numbers in application-settings on Android using the `setNumber` method may result in lost precision, overflow, or underflow. This is due to the implementation storing the number as a float.

**To Reproduce**
Storing a timestamp from a date in application-settings using the `setNumber` method results in one of the above issues. The same is true for values where high precision.

**Expected behaviour**
The retrieved value matches the value passed to the `setNumber` method from application-settings.

**Additional context**
One solution would be to convert the value to and from a string, but this can be inefficient.

Another solution is to convert the value to a `java.lang.Double` and save the value as a long and doing the same type conversion on retrieval. I.e. like this SO response mentions: https://stackoverflow.com/a/18098090/7735859

**Comment by NickIliev** [comment]
@Frederiks96 regarding
```
Those suggesting a toString and parseString are not wrong, but it's an inefficient solution.
```

In my opinion, the solution would be inefficient only if you are dealing with an enormously large array of values that you need to iterate & convert. Still, in such case, that would mean that `application-settings` module is not the right approach to begin with.  There is also the fact, that the NativeScript developers will work with a JavaScript number ([see JS number max range here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)) which also has its limitations, to begin with. Using the string for timestamps and large number should be the right approach

As you noticed even the native Android developers are using additional logic  (like [this hack](https://stackoverflow.com/a/18098090/4936697)) so I think the best approach would be to preserve the original implementation that uses the native method `putLong`. For anyone interested in the additional implementation, you can always access the SharedPreferences, the access the editor and add your own solution

e.g. something like (TypeScript)
```TSC
let sharedPreferences = (<android.app.Application>getNativeApplication()).getApplicationContext().getSharedPreferences("prefs.db", 0);

const editor = sharedPreferences .edit();



// implement the logic to create the putDouble method
// e.g. https://stackoverflow.com/a/18098090/4936697

```

**Comment by Frederiks96** [comment]
@NickIliev You mention that the current implementation uses the native `putLong`. However, that is not what I can see from the current repo? Here you use `putFloat`: https://github.com/NativeScript/NativeScript/blob/4e56c89f7d63f69a8c8bd77a11314941851c1107/tns-core-modules/application-settings/application-settings.android.ts#L67

**Comment by NickIliev** [comment]
@Frederiks96 sorry a mistype ... `putFloat` is what I meant
