### ISSUE TITLE
http module - headers don't work

### ISSUE THREAD

**Issue by rrednoss** [NativeScript/NativeScript#7159]
**Environment**
 - CLI: 5.2.4
 - iOS Runtime: 5.2.0 (only tested in ios)
- plugins: nativescript-ui-sidedrawer

**Describe the bug**
I want to query an image via a RESTful API. The API requires authorization information inside the HTTP-Header (Authorization: key="<secret key>"). Since the nativescript-angular HttpClient [does not support the "blob" responseType](https://github.com/NativeScript/nativescript-angular/issues/1202), I need to use the nativescript [http module](https://docs.nativescript.org/api-reference/modules/_http_) instead.

The problem I'm encountering is the authorization. When I send a request to the API (see below) I get a 403 status code. The authorization code is correct since I'm using it in an other part of my app to request JSON data.

**My service**
```
import { request, HttpResponse } from "tns-core-modules/http";
...
getImage(imageUrl: string) {
    return request({
        headers: { "Authorization": "key='<secret key>'" },
        method: "GET",
        url: imageUrl
    }).then((data: HttpResponse) => {
        console.log(data.statusCode)
    });
}
```

**Expected behavior**
Status Code: 200

**Comment by NickIliev** [comment]
@rrednoss if you have a test API that can be used with test authorization please do let me know so I could test this case. Meanwhile, you could try [this solution](https://github.com/NativeScript/NativeScript/issues/6209#issuecomment-417320458)

**Comment by rrednoss** [comment]
@NickIliev thanks for quick reply. I've tested the solution you suggested, but the problem still exists. Unfortunately I can't provide the API, cause it's under license.

**Comment by NickIliev** [comment]
@rrednoss the [HTTP status 403 ](https://httpstatuses.com/403) is 

> The server understood the request but refuses to authorize it.

> A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).
> 
> If authentication credentials were provided in the request, the server considers them insufficient to grant access. The client SHOULD NOT automatically repeat the request with the same credentials. The client MAY repeat the request with new or different credentials. However, a request might be forbidden for reasons unrelated to the credentials.

That said, the reasons are a bit vague and it is hard to investigate the issue with access to your specific API - can you please let us know is the issue persist when testing with Android device and also post the response from the server.

**Comment by rrednoss** [comment]
@NickIliev As I mentioned above I use also nativescript-angular HttpClient in an other part of my code.

So I've installed wireshark to compare the http-headers using [HttpClient](https://docs.nativescript.org/angular/ng-framework-modules/http) and the [Http](https://docs.nativescript.org/ns-framework-modules/http) module. The difference is that I am using single quotes in the first and double quotes in the second situation.

When I am changing the header into this, it's working!
`headers: { 'Authorization': 'key="<secret key>"' }`

So this issue can be closed.
