### ISSUE TITLE
tns preview is throwing an error on android

### ISSUE THREAD

**Issue by GAGANsinghmsitece** [NativeScript/NativeScript#7167]
**Environment**
-npm: 6.9.0
 - CLI: 5.3.2

**Describe the bug**
I'm trying to develop native-script app using quick-start guide with vue.js. But after using `tns preview` , i'm getting following exception:-
`LOG from device Galaxy On7: com.tns.NativeScriptException:

Error calling module function

TypeError: Cannot read property 'forName' of undefined
File: "file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/application/application.js, line: 158, column: 40

StackTrace:
        Frame: function:'getNativeApplication', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/application/application.js', line: 158, column: 41
        Frame: function:'_start', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/application/application.js', line: 105, column: 25
        Frame: function:'run', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/application/application.js', line: 120, column: 5
        Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.js', line: 41, column: 5
        Frame: function:'require', file:'', line: 1, column: 266

TypeError: Cannot read property 'forName' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace:
        Frame: function:'getNativeApplication', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/application/application.js', line: 158, column: 41
            Frame: function:'_start', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/application/application.js', line: 105, column: 25
            Frame: function:'run', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/application/application.js', line: 120, column: 5
            Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.js', line: 41, column: 5
            Frame: function:'require', file:'', line: 1, column: 266

        at com.tns.Runtime.runModule(Native Method)
        at com.tns.Runtime.runModule(Runtime.java:624)
        at com.tns.Runtime.run(Runtime.java:616)
        at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1037)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6428)
        at android.app.ActivityThread.access$1800(ActivityThread.java:229)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7331)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Expected behavior**
What guess, it should start with default welcome screen since i didn't edit the files.

**Comment by tsonevn** [comment]
Hi @GAGANsinghmsitece,
Can you send us the project or sample one, which demonstrates the problem and can be used for debugging?

**Comment by GAGANsinghmsitece** [comment]
I haven't edited the project,so it will be same as the initialised one

**Comment by tsonevn** [comment]
@GAGANsinghmsitece,
I have just tested the preview command with newly created NativeScript JavaScript, NativeScript TypeScript, NativeScript Angular, NativeScript Vue project while using Hello World templates on Samsung S8 device. However, I was unable to recreate the issue you are reporting. Can you check if you are using the latest Preview app version on your device? Also, It will help if you can provide more info about the template, that you are using.

**Comment by GAGANsinghmsitece** [comment]
nativescript preview v1.20.0

**Comment by GAGANsinghmsitece** [comment]
i'm using the latest version of preview app

**Comment by GAGANsinghmsitece** [comment]
I just tried preview app with native-script playground but it is again throwing same error

**Comment by GAGANsinghmsitece** [comment]
![Capture](https://user-images.githubusercontent.com/37043052/56494479-063c2d80-6510-11e9-8acd-787a59c6f521.PNG)

**Comment by GAGANsinghmsitece** [comment]
I'm closing this issue. I need to reinstall the preview app and then clear cache of my android device.Now,it works fine
