### ISSUE TITLE
No JS stack on discardedError and unhandledError

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/NativeScript#7169]
If you look at your test app [here](https://github.com/NativeScript/NativeScript/blob/master/apps/app/ui-tests-app/app.ts#L77) we are supposed to get the JS error .
But the JS error is not filled correctly (at least on android, need to check ios).
the JS error object as the same value for message and stack:
```
The application crashed because of an uncaught exception. You can look at "stackTrace" or "nativeException" for more detailed information about the exception.\'
```

the ```error.stackTrace``` however contains something like this:
```
An uncaught Exception occurred on "main" thread.
 com.tns.NativeScriptException: 
Calling js method onClick failed

TypeError: this.thisShouldCrash is not a function
File: "file:///data/data/org.nativescript.demovuebugsnag/files/app/bundle.js, line: 1044, column: 11

StackTrace: 
   Frame: function:\'crashTest\', file:\'file:///data/data/org.nativescript.demovuebugsnag/files/app/bundle.js\', line: 1044, column: 12
...
```

We should get the correct error message and stacktrace for the JS error.
The data is here as it all in ```error.stackTrace```.
I could parse the  ```error.stackTrace``` and create a correct JS error message out of it.
But it would be better for it to be done inside {N}

**Comment by farfromrefug** [comment]
After running some tests, this is an Android-only issue. The error si filled correctly on IOS.
Should this issue be opened in the android-runtime?

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/android-runtime #1354](https://github.com/NativeScript/android-runtime/issues/1354) via [**ZenHub**](https://www.zenhub.com/)
