### ISSUE TITLE
fetch() does not invoke catch() handlers on 400 responses

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/NativeScript#717]
When upgrading the same to the 1.3 RC I ran into a little issue that took me a while to track down. It seems that the `fetch()` method does invoke `catch()` handlers when a backend returns a 400 response.

Here's my example. I'm calling Telerik Backend Services to register a new user with the following code:

```js
fetch(config.apiUrl + "Users", {
	method: "POST",
	body: JSON.stringify({
		Username: viewModel.get("email"),
		Email: viewModel.get("email"),
		Password: viewModel.get("password")
	}),
	headers: {
		"Content-Type": "application/json"
	}
}).then(function(data) {
	resolve();
}).catch(function(error) {
	console.log(error);
	reject();
});
```

If I try to register a user that already exists in the backend, Telerik Backend Services returns the following JSON response:

```
{"_bodyInit":"{\"message\":\"A user with the same username already exists.\",\"errorCode\":201}","_bodyText":"{\"message\":\"A user with the same username already exists.\",\"errorCode\":201}","type":"default","url":"","status":400,"ok":false,"statusText":"Bad Request","headers":{"map":{"server":["nginx"],"content-type":["application/json; charset=utf-8"],"x-powered-by":["Everlive"],"content-length":["75"],"connection":["keep-alive"],"date":["Fri, 11 Sep 2015 15:58:38 GMT"],"access-control-allow-credentials":["true"]}}}
```

However, despite the response including `"status": 400`, I end up in the `then()` handler rather than the `catch()` handler. In the case of Groceries this means I show a confirmation dialog when registration fails, rather than correctly showing an error message. If you'd like to see this behavior for yourself I have a [1.3 branch of Groceries up](https://github.com/NativeScript/sample-Groceries/tree/1.3).

Unless I'm missing something, which is quite possible, the current behavior seems wrong.

**Comment by ligaz** [comment]
Just tested this in Chrome and the behavior is the one that you are describing here. I have also checked the [spec](https://fetch.spec.whatwg.org/) and I think what we have right now is the correct one.

> Tip: There is an [`ok`](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok) property on the response that you can use instead.

**Comment by tjvantoll** [comment]
Interesting. You're right, and actually `then()` is called regardless of the response code. I might need to write something about this. Thanks!
