### ISSUE TITLE
How to increase thumb in Slider?

### ISSUE THREAD

**Issue by boggddan** [NativeScript/NativeScript#7170]
Could help me? How to increase thumb? Like this

I use 

```js
<Slider value="80" />

```

![Sample](https://i.imgur.com/8yQPrxM.png)

I found the answer for Android. Need to create file `app/App_Resources/Android/src/main/res/drawable-nodpi/custom_thumb.xml`

```
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval" >

    <gradient
        android:angle="270"
        android:endColor="@color/colorDekraOrange"
        android:startColor="@color/colorDekraOrange" />

    <size
        android:height="35dp"
        android:width="35dp" />

</shape>
```    

and add a property `android:thumb="@drawable/custom_thumb"`

But how does this property add a Slider to nativescrip?

Thank's

**Comment by tsonevn** [comment]
Hi @boggddan,
In your case, you can define your drawable in the `app/App_Resources/Android/src/main/res/drawable-nodpi` folder and via the native `setThumb` method to set it to the Slider component. For example:
```
export function slloaded(args){
    let slider:Slider = <Slider>args.object;
    if(isAndroid){
        let rec = 	applicationModule.android.context.getResources();
        let idt = rec.getIdentifier("thumb_image", "drawable",applicationModule.android.context.getPackageName());
        let drawable  = android.support.v4.content.res.ResourcesCompat.getDrawable(rec, idt, null);
        slider.android.setThumb(drawable);
    }
}

```
For further help, you can check the attached sample project. 
[Archive.zip](https://github.com/NativeScript/NativeScript/files/3106208/Archive.zip)

**Comment by boggddan** [comment]
Hi, @tsonevn. Thank's.

Может кому-то будет полезно, пример компонента для Vue

[Samples](https://gist.github.com/b0939261761/1b573f23c53bca37f3277ac67a42d2f3)

**Comment by Firetrip** [comment]
how would you do this for ios?
