### ISSUE TITLE
NSPhotoLibraryUsage is enabled

### ISSUE THREAD

**Issue by SephReed** [NativeScript/NativeScript#7172]
**Describe the bug**

My app got denied due to a missing description for why NSPhotoLibraryUsage was enabled.  It's easy enough to add a description, except that I don't really need access to photo library for any good reason.  

**To Reproduce**

Create a default project, upload to app store

**Expected behavior**
Should not require access to NSPhotoLibraryUsage

**Sample project**

Default project

**Additional context**

There are a few tns modules I've installed, though I don't think any of them should be able to modify the overall permissions requested by my app.  Otherwise, I have not touched the settings.

**Comment by NathanaelA** [comment]
@SephReed - can you still list what plugins you have installed...

**Comment by tsonevn** [comment]
Hi @SephReed
This issue seems to be related to some of the plugins that you are using in your app. As @NathanaelA, already suggested, can you share with us the list of the plugins, installed in the app?
