### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by steskalja** [NativeScript/NativeScript#7174]
When will Nativescript support Windows 10 again? It would be nice to compile to UWP

**Comment by tsonevn** [comment]
Hi @steskalja,
NativeScript is working on Windows 10. On that matter, can you provide more info about the issue you are facing? Is it something related to NativeScript installation or project builds? Also, please follow the template, while opening a new issue and provide the requested info. 
->
```
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
<!-- A clear and concise description of what the bug is. Please, explain whether it's a build time error or a runtime error. More detailed logs can be easily obtained by following the instructions in this guide: https://docs.nativescript.org/get-support#how-to-obtain-diagnostic-reports. -->

**To Reproduce**
<!-- Add commands used or steps taken to reproduce the behaviour. -->

**Expected behavior**

**Sample project**
<!-- If possible, provide a link from the [Playground](https://play.nativescript.org) with reproduction of the problem. If not, consider attaching a sample project or link to a repository with such project. -->

**Additional context**
<!-- Add any other context about the problem here. -->

```

**Comment by NickIliev** [comment]
Closing as a duplicate to https://github.com/NativeScript/NativeScript/issues/254

Currently, the support for UWP is not a priority for the core team due to the UWP platform having less than 1% market share. Still, you might track the linked issue for community-driven ideas. discussed in the thread
