### ISSUE TITLE
Can't get the emulator to work despite the tns doctor showing everything is fine

### ISSUE THREAD

**Issue by bruceherve** [NativeScript/NativeScript#7176]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

I am having the same issue here despite tns doctor indicating that everything is fine: 
![tns-doctor](https://user-images.githubusercontent.com/35220130/56752783-5d990280-6789-11e9-8703-9ceb50783bf3.png)
Vtx is supported on my machine as well , here is the lscpu command:
![lscpu](https://user-images.githubusercontent.com/35220130/56752828-828d7580-6789-11e9-87ba-a07ed34ce13b.png)
And finally the grep --color vmx /proc/cpuinfo command: 
![vmx](https://user-images.githubusercontent.com/35220130/56752912-ad77c980-6789-11e9-98b5-78e909e044fb.png)

As you can see here I have a list of created devices using the avd manager
./avdmanager list 
![avdmanager](https://user-images.githubusercontent.com/35220130/56754726-05b0ca80-678e-11e9-9823-68fdf807ebc9.png)
However when I run tns device android  --available-devices I see none:
![nadroid-device](https://user-images.githubusercontent.com/35220130/56755117-0b5ae000-678f-11e9-9cc5-e68a1200644b.png)

Can someone help figure out whats wrong with my set up, I feel like every thing checks out yet I can't start an emulator at all. Thanks

Also tns run aandroid returns this:
![tns-run-android](https://user-images.githubusercontent.com/35220130/56755878-c768da80-6790-11e9-98fb-80ed2f90cea8.png)

**Comment by NathanaelA** [comment]
Well a couple things, I noticed:
1. Have you attempted to manually start an emulator using "Android Studio" -> Tools -> AVD Manager.
2. If you type "adb devices" does it show anything (especially after you started an emulator manually)?
3. If you have an emulator running; and `adb devices` shows it; does `tns device android` now show it?
4. In your last picture; your `tns run android` seems to indicate you tried running this in a folder that didn't have a nativescript project.  Is that the case?   (This might be unrelated to your issue)

I had a similar issue a couple weeks back, it might be related but in my case the CLI was throwing an error:  https://github.com/NativeScript/nativescript-cli/issues/4508    You might consider setting the additional environmental variables; TNS doesn't use them (or detect if they are missing), but the android tooling does use them...  And in my case fixed my issue.

**Comment by bruceherve** [comment]
You are right I was running the command outside the project but even inside it fails:
![inside-project](https://user-images.githubusercontent.com/35220130/56759848-2ed75800-679a-11e9-901d-5f2620a9fda2.png)
I did however managed to use tns preview on the SideDrawer starter project that works..I am now wondering If I need to use genymotion. I did not install Android Studio Since I would be using VsCode that's why I am starting manualy the emulators.. I am now wondering If I should use genymotion instead

**Comment by NathanaelA** [comment]
Well it could be a couple things then, but installing Android Studio makes **everything** a lot easier...  :grinning:   I frequently use the SDK manager and AVD manager in Android studio to install/setup things.   Much, much easier than CLI...  (And I love CLI for 99% of the things, I have 7 terminal windows open right now...  :grinning:)

First, I don't see any reason to use Geny now (I used to use it; in fact I still have a license for it).  The Android emulator are considerably better than Geny now, in my humble opinion, especially on Linux, so I never bothered to even reinstall Geny on my Linux box when I re-bricked it a couple months ago.    The really nice thing about the Google emulators is that you can actually test on the latest images; I'm already testing apps on the upcoming Q.  Geny probably won't have it for a while still...

Now for the emulator to work you need a couple things:
On my linux box the Android sdk is located in: ~/Android/sdk  
 And inside the `emulator` directory I have:
![image](https://user-images.githubusercontent.com/850871/56764692-f1a7a180-676a-11e9-936f-bafbc8d0d735.png)
According to the source.properties; I'm currently running 28.0.25

So the first thing you need to verify is that you do have the emulator binaries installed.   Now, I also recall when I first installed the emulator; the Android Studio had an helpful message about the `/dev/kvm` (missing rights) I needed permission to access it.   So I added myself the needed groups to give my user rights to the /dev devices I needed access to.  This is required on Linux.

The second thing you need to do is actually create an emulator.  So in your `~/.android/avd` folder you should see 
![image](https://user-images.githubusercontent.com/850871/56765074-d8ebbb80-676b-11e9-9ef4-60061168566e.png)
something that has both a folder and a .ini file of the same name.   If you don't have any of them, then you don't have any emulators setup to run.   I'm not sure how to create any via the CLI, I always using Android Studio to create the emulators I use.    Once they are created; then NativeScript should be able to run them...

**Comment by tsonevn** [comment]
Hi @bruceherve,
Did you manage to solve the issues mentioned above, or you still can not build a project for an android emulator?

**Comment by bruceherve** [comment]
@NathanaelA Thanks, I have been struggling with using genymotion until now due to my stubbornness to refuse to use install Android studio but I think I will now..

@tsonevn  I have not managed to use genymotion at all.
I have the emulator setup and running as genyshell confirms
![geny-shell](https://user-images.githubusercontent.com/35220130/56929518-1f2d7b80-6ada-11e9-9aec-b2f81e13adad.png)
But still tns command shows I have no devices at all, I even tried to run by passing -- emulator -geny="device name"  but It still does not work
![tns-devices](https://user-images.githubusercontent.com/35220130/56929597-5865eb80-6ada-11e9-9563-4f4935417bdb.png)

**Comment by tsonevn** [comment]
Hi @bruceherve,
I would suggest setting up the path to the Android SDK tools, which is set in ANDROID_HOME variable, in the [Genymotion configuration](https://docs.genymotion.com/latest/Content/02_Application/Configuring_Genymotion/ADB.htm). Then restart the Genymotion, start an emulator and try to build your project with `tns run android`.

**Comment by bruceherve** [comment]
@NathanaelA This was definitely a path issue when setting the path I forgot $ and since I was sure I set the path right I went looking everywhere else, thanks @NathanaelA @tsonevn It's fixed a while back I just forgot this was open, I am going ahead and closing it.
