### ISSUE TITLE
ListPicker on Android emits selectedIndexChange events while scrolling

### ISSUE THREAD

**Issue by taras** [NativeScript/NativeScript#7178]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: N/A
 - Cross-platform modules:
 - Android Runtime: 7, 8 & 9
 - iOS Runtime: 12
 - Plugin(s): none

**Describe the bug**

On Android, the ListPicker continuously emits `selectedIndexChange` events as the user interacts with the list wheel. This results in UI jank when `selectedIndexChange` handler performs a heavy operation. 

The same problem does not happen on iOS because iOS only emits a `selectedIndexChange` event once the user releases the list wheel and takes the finger off the screen.

**To Reproduce**

1. [Open demo app](https://play.nativescript.org/?template=play-ng&id=ImoCcR) using NativeScript Preview on Android
2. Use the ListPicker to attempt to select element
3. As you select elements further down the list, you'll see increasing jank around 6th item in the list
4. By 10th item, it'll completely lockup the screen for a few seconds

Repeat this on iOS to see that it's not a problem on iOS. Also, note that the `selectedIndex` value on the screen does not change on iOS until you let go of the input field.

**Expected behavior**

I would expect the behaviour to be consistent between iOS and Android. The behaviour on iOS makes sense because there is no point updating the UI if the user is still selecting their item.

**Sample project**

https://play.nativescript.org/?template=play-ng&id=ImoCcR

**Additional context**

None

Thank you

**Comment by tsonevn** [comment]
Hi @taras,
Thank you for the provided sample project. 
Regarding the case, there are some differences in **ListPicker** implementation which are based on some specifics in both platforms(Android and iOS). On that matter,  there is some difference in the execution of `selectedIndexChange` event handler. However, I do not think that this is the cause of the performance issue. I notice that you are calling the **slow** method inside of it, which seems to make some loop that hangs the UI. If I remove the nested method call, the issue disappears on my side. For example:
```
slow(index) {
        // slow(index);
        this.selectedIndex = index;
    }
```  
https://play.nativescript.org/?template=play-ng&id=ImoCcR&v=2

**Comment by taras** [comment]
Hi @tsonevn,

> I notice that you are calling the slow method inside of it, which seems to make some loop that hangs the UI. If I remove the nested method call, the issue disappears on my side.

Yes, this is intentional. It's there to show the consequence on perceived performance between iOS and Android. 

In ideally world, every problem would be a simple as commenting out the `slow` function in code. In practice, finding the source of slowness can be difficult. I expect NativeScript, as much as possible, to normalize behaviour between iOS and Android. Sometimes that means picking a default that works well on one and implementing it for both.

Knowing which defaults to choose can be difficult. In this case it's easier because we can compare the impact on perceived performance of both implementations. On iOS, the ListPicker does not emit events while the user is interacting with the wheel allowing the wheel to work smoothly even when the ListPicker is connected to a slow event handler. On Android, ListPicker emits events continuously which results in UI locking when the event handler is slow. 

IMO, iOS has a better design here. Android should mirror the iOS implementation. The Android implementation will need to be more complicated but that's the complexity that I would expect NativeScript to take care of in the framework code so I don't have to deal with this in my application code.  

NativeScript/ListPicker uses [android.widget.NumberPicker](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/list-picker/list-picker.android.ts#L73) which supports [NumberPicker.OnScrollListener](https://developer.android.com/reference/android/widget/NumberPicker.OnScrollListener) event. This listener emits [SCROLL_STATE_TOUCH_SCROLL state](https://developer.android.com/reference/android/widget/NumberPicker.OnScrollListener.html#SCROLL_STATE_TOUCH_SCROLL) that can be used to detect when `the user is scrolling using touch, and his finger is still on the screen.`

I'd be happy to try implementing this change if you agree with this suggestion.

**Comment by taras** [comment]
ping 😄

**Comment by WebDaMa** [comment]
Same issue here.

I have a listpicker that loads other listpicker values with an API call. The app almost freezes when scrolling.
Any suggestion on using another component from a plugin or a fix?

**Comment by NathanaelA** [comment]
The simplest solution is to debounce it yourself.   :grinning:    This code is off the top of my head, might be some minor changes you need....

```
const lastTimer = {id: null, value: -1};
function selectedIndexChangeDebouncer(args) { 
    // If we are the same index as the last time, or the next time; we skip doing anything.
    if (args.selectedIndexChange === lastValue.value) return;

   // Grab our current value...
   lastTimer.value = args.selectedIndexChanges;

   // If the timer is already running, clear it...
   if (lastTimer.id != null) { clearTimeout(lastTimer.id); }

   // Start a new timer  (runs in 1/4 of a second)
   lastTimer.id = setTimeout( () => { 
       lastTimer.id = null; 
       selectedIndexChangeCallback(args);  
   }, 250);  
}

function selectedIndexChangeCallback(args) { 
    /* your real SelectIndexChange function that does your actual work */ 
}
```

**Comment by WebDaMa** [comment]
`selectedIndexChangeDebouncer(args) {
        const picker = <ListPicker>args.object;
        console.log("picker selection: " + picker.selectedIndex);
        // If we are the same index as the last time, or the next time; we skip doing anything.
        if (picker.selectedIndex === this.lastTimer.value) { return; }

        // Grab our current value...
        this.lastTimer.value = picker.selectedIndex;

        // If the timer is already running, clear it...
        if (this.lastTimer.id != null) { clearTimeout(this.lastTimer.id); }

        // Start a new timer  (runs in 1/4 of a second)
        this.lastTimer.id = setTimeout(() => {
            this.lastTimer.id = null;
            this.selectedGroupIndexChanged(args);
        }, 250);
    }`
Thx for the debounce hint! Works smooth now.
