### ISSUE TITLE
OpenModal crash bug : Android

### ISSUE THREAD

**Issue by stonecourier** [NativeScript/NativeScript#718]
If you open a page using showModal and the user accidently double taps it quickly, it opens two of the same page. When they try and close the page, the application crashes.

TypeError : cannot read property
dismissAllowingStateLoss of null
page.js line 64 column 28

I have been trying to figure out an easy way of disabling the button to prevent this from happening, but not much luck yet.

**Comment by NathanaelA** [comment]
This won't solve the underlying issues; but you should be able to get the button and disable it in the onclick handler; and then re-enable the button in the dialog callback.   The button I think is passed in the event args as either object or obj.     

Or you can just leave the button enabled; and just set a flag if you are in the dialog and if the flag is set then return out of the button tap handler. Reset the flag when the dialog callback is called.

**Comment by stonecourier** [comment]
Unfortunately the way the back button closes the dialog page makes this so you can't do it (ie back just closes the window, does not inform anything else that it has done it, does not do dialog callback).

**Comment by NathanaelA** [comment]
Interesting -- I didn't know that.   Well, that sucks.  

Looking briefly at the code it appears like it should be notifying you any time it is closed.

**Comment by NathanaelA** [comment]
I should add; you can try also using the page unLoaded event, the loaded & unloaded events are fired on Dialog pages -- So as far as I recall, this event should be fired every time also...

**Comment by stonecourier** [comment]
Tested this, and the unloaded event is not fired if you use the back button, so I can't figure out any way of disabling the button.

**Comment by NathanaelA** [comment]
I just added a pull request that fixes these issues #726 ...  Hopefully we can get it into v1.3...

**Comment by stonecourier** [comment]
Thanks a lot. Much appreciated.

**Comment by N3ll** [comment]
This should be fixed with this pull request https://github.com/NativeScript/NativeScript/pull/864, but you can still check if everything works fine, when 1.4.0 is released.
