### ISSUE TITLE
[iOS] ScrollView inside a nested RadSideDrawer incorrect layout

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/NativeScript#7185]
This is a repeat of issue #6674.

Aplogies - but I posted at the end of that issue and getting no response.

The issue is: With the following xml, sometimes it creates an extra margin at the top - the green part of the image  (ios only).

[main-page.xml.txt](https://github.com/NativeScript/NativeScript/files/3123947/main-page.xml.txt)

![51789202-652e1880-2154-11e9-826c-834cf6d63183](https://user-images.githubusercontent.com/1229041/56850812-99d97980-68d5-11e9-90cc-0dc30f5d5f0b.jpg)

Using the latest environment 5.3.x

**Comment by tsonevn** [comment]
Hi @erjdriver,
Try setting up the RadSideDrawer component as a root component and check if the issue will be still reproducible. For further help, you can review our [drawer-navigation](https://github.com/NativeScript/nativescript-app-templates/blob/master/packages/template-drawer-navigation-ts/app/app-root/app-root.xml) template.

**Comment by erjdriver** [comment]
You're saying no `Page` element??

Then where would I put the `ActionBar`?

**Comment by tsonevn** [comment]
Hi @erjdriver,
I tested the provided XML in a local project. However, I was unable to recreate the issue on my side. I will check again in the lower iOS versions.
Meanwhile, my suggestion was to set the RadSideDrawer in the app-root.xml and then set the Frame as `mainContent`. In this scenario, the ActionBar should be still defined in each page individually as it is done in the template, that I have mentioned in my previous comment. The idea of this check is to verify if layouting will be fixed. Also, keep in mind that RadSideDrawer will not be stretched while using it inside the pages on iPhone X and above. Check out [this feature request](https://github.com/telerik/nativescript-ui-feedback/issues/1058).


It will also help if you can send a project, which can be used for debugging.

**Comment by erjdriver** [comment]
Here's the project with the problem.

I just did `tns create layout-problem --template tsc`

Then added `nativescript-ui-sidedrawer` plugin.

The latest NS versions are installed - 5.3.x

The simulator is running iPhone 6 running ios 12.2.

[layout-problem.zip](https://github.com/NativeScript/NativeScript/files/3131591/layout-problem.zip)

**Comment by erjdriver** [comment]
I followed your suggestion - and attached is the app with RadSideDrawer in app-root.xml file.

In `main-page.xml' file, if I enable the `ActionBar` code - it works as expected.

But if the `ActionBar` is commented out, then there's a layout issue.

Please see attached screenshot - the layout goes all the way to the top of the device screen (shown in blue. Works fine on Android

![Screen-shot 2019-04-30 at 10 37 25 AM](https://user-images.githubusercontent.com/1229041/56970051-56c91180-6b34-11e9-8b49-d880c2afdfd2.png)

[layout-problem.zip](https://github.com/NativeScript/NativeScript/files/3131735/layout-problem.zip)

Again, there seems to be a layout bug in the ios version - proven by both this and the earlier submitted versions.

I would like the earlier project to work as is - as the second one would require quite a bit of changes in my code.

Thank you.

**Comment by DevPlus31** [comment]
I do have the same issue especially when I use RadListView or RadDataForm. 
I am using RadSideDrawer for the whole app with Vue template and slot. 
I will provide more codes when I will get my Mac.

**Comment by erjdriver** [comment]
@tsonevn - as requested I submitted a project with the issue - above with the attached layout-problem.zip file.

Did you get a chance to replicate it?

Thanks.

**Comment by tsonevn** [comment]
Hi @erjdriver,
I was able to recreate your case on my side. I also find this feature request for allowing [RadSideDrawer stretch ](https://github.com/telerik/nativescript-ui-feedback/issues/1058) while using it inside the Page component. I would suggest keeping track of it. You can also comment it if you want to add some additional info. 
Meanwhile, you can set the SideDrawer component as root and for those Pages without ActionBar to set up the StatusBar color via [nativescript-statusbar plugin](https://www.npmjs.com/package/nativescript-statusbar).

**Comment by erjdriver** [comment]
I don't understand how you can close this issue - it's a bug!

Ok - you're saying for pages with `ActionBar` have RadSideDrawer as root. This requires me moving quite a bit of re-arrangement of logic and code - but I can do it. This used to work and still works on Android - isn't this a bug on the ios side?

You're saying for pages with OUT `ActionBar` - style the status bar. The problem is that the page goes to the top of the device screen. If I had a label text at the top of my page - it would be displayed over the status bar. This is a bug - not a matter of styling the status-bar.

NS guys - too many times when I report a bug - it's not fixed. Usually the solution is a workaround or suggestions of code changes on my end.

I'm working on a production software and there are limits to how much changes I can make without causing unforeseen issues.

I appreciate the tool, doesn't matter if it's free or for purchase - bottom line is that - if you guys want this to be used in production app development - it has to be stable and reliable.

**Comment by DevPlus31** [comment]
Here's my code about the issue. just to precise I am not using ScrollView but I do get the same result (top space) 
https://play.nativescript.org/?template=play-vue&id=JJxeIs
![bugios](https://user-images.githubusercontent.com/16153522/57244479-58ad3c00-7030-11e9-8176-3797bde36f0b.png)

Thanks.

**Comment by erjdriver** [comment]
I've implemented my app with RadSideDrawer in the root file now. Unfortunately, the menu also appears on some pages where it shouldn't because of gestures - so I disabled gestures. Side-effect of this workaround.

Please tag this issue as a bug.

Thanks.

**Comment by NickIliev** [comment]
@erjdriver as of this moment the RadSideDrawer (adn with latest versions) is supported only as a root. [Here ](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/login/login.component.ts#L51-L52)is how to prevent the drawer from being opened.
