### ISSUE TITLE
ios build rejected

### ISSUE THREAD

**Issue by afaridanquah** [NativeScript/NativeScript#7191]
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 5.3.1 and the latest available version is 5.3.4.
✔ Component tns-core-modules has 5.3.1 version and is up to date.
✔ Component tns-android has 5.3.1 version and is up to date.
✔ Component tns-ios has 5.3.1 version and is up to date.

Apple is rejecting all by recent builds 

Guideline 4.2.6 - Design - Commercialized Templates and App Generation Services

We noticed that your app appears to be created from an app generation service or a commercialized template, but it was not directly submitted by the owner or provider of the business, brand, or service.

**Comment by tsonevn** [comment]
Hi @afaridanquah, 
Can you share with us the full iOS report after the review? Also, provide more info about the exact template, that you have used for your application and the exact steps that have been used while building and publishing the app. It will also help if you can share your project's package.json file.
