### ISSUE TITLE
Text Moves behind the action bar when using tns-core-modules: 5.2.1 on IOS 10.*

### ISSUE THREAD

**Issue by lohiarahul** [NativeScript/NativeScript#7192]
Whenever a ScrollView is set for a page, the ContentView slides behind the ActionBar. Explicit for the ScrollView is set to screen.mainScreen.heightDIPs. The page loads normally and the phenomenon described above occurs once any transition occurs other than the default transition and you come back to the page. Using 5.3.1 solves the problem on IOS 10.*, but adds an extra space in IOS 12.*

**Comment by tsonevn** [comment]
Hi @lohiarahul,
Can you provide a sample project, that can be used for recreating the issue?
