### ISSUE TITLE
Navigation issues with frames and pages with sideDrawer template

### ISSUE THREAD

**Issue by delanick** [NativeScript/NativeScript#7194]
Hi,

I'm using {N} 5+ and using app.run() to start my project. Since you guys introduced the <Frame> concept for sideDrawers, I can't seem to navigate to my login page without the sideDrawer being active. Can you please advise how I can render the the drawer unusable/inactive on my login page, or any page that shouldn't have it?

Or, how do I create a root frame, which navigates to an app-root (sideDrawer) frame if user logged in, or login page if not logged in, and the navigation between them? I'm currently reciving massive TypeErrors when trying to navigate between frames.

Or, please advise how I can navigate from one Frame to another if my sideDrawer has to be in app-root and my login page in another.

**Comment by tsonevn** [comment]
Hi @delanick,
In your case, you can define the RadSideDrawer as a root component and disable its gestures only for the needed pages(in your case your login page). Disabling the gesture will not allow the user to open the side drawer in the login page however, the navigation in the app will still work as expected. 
For your convenience, I created a sample project which demonstrates the above-given suggestion. In the home page, I have disabled the drawer gesture. When you tap on the login button, the app will navigate to the browser page, where the drawer will be enabled.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/3140796/Archive.zip)

**Comment by NathanaelA** [comment]
@delanick - if this is a NS-Core/PAN (Plain Awesome NativeScript) application -- I have an MUCH better way of doing this.    :grinning:

Created a blog post here http://fluentreports.com/blog/?p=732 to answer the question...

**Comment by delanick** [comment]
@tsonevn Thanks so much, really appreciate it, will check it out now!

@NathanaelA This is a PSAN (Please Super-Awesome Nativescript) app :) Yeah, it's NS Core :)

Will check your blog post too :) Thanks!!

**Comment by delanick** [comment]
@tsonevn Worked perfectly!
@NathanaelA So did yours. 

Now the question begs: which approach will be better for the longer term? What is Nativescript's approach to this going forward for future versions?

Thanks guys, both responses are crazily appreciated!! :) I was going crazy!

**Comment by tsonevn** [comment]
Hi @delanick,
I am glad to hear both suggestions(the one from @NathanaelA and mine) works for you. Regarding your question about the better one, In my opinion, it depends on the project and the structure, you are using in it. I would suggest checking, which approach will cost you less time to integrate the RadSideDrawer with the needed functionality if you are going to do that for an existing project or you can use our [navigation-drawer template](https://docs.nativescript.org/app-and-screen-templates/app-templates#navigation-drawer) if you start a new project from scratch. About the second question, NativeScript will keep the support for RadSideDrawer as root and the functionality for disabling the swipe gesture for the future versions for sure.
