### ISSUE TITLE
GridLayout percentage for rows/columns not working

### ISSUE THREAD

**Issue by PieterHartzer** [NativeScript/NativeScript#7195]
**Environment**
TNS Playground
Android 8.0.0

**Describe the bug**
When setting up a GridLayout with percentages for rows/columns they appear to be treated as pixels instead of percentages. 

**To Reproduce**
Browse to [this playground project](https://play.nativescript.org/?template=play-js&id=bq16UX) and preview it.

**Expected behavior**
The buttons should appear in two rows, each 50% tall

**Sample project**
[Playground](https://play.nativescript.org/?template=play-js&id=bq16UX)

**Additional context**
I also tried it on my local machine with the same result

**Comment by tsonevn** [comment]
HI @PieterHartzer,
Percentage values for the rows and columns properties of the GridLayout are not supported. The supported option can be found in [this link](https://docs.nativescript.org/angular/ui/layouts/layout-containers#gridlayout) from NS docs. In your specific case, I would suggest using Star (`*`) for the rows and columns. I am attaching [a link](https://play.nativescript.org/?template=play-js&id=bq16UX&v=2) to your sample project with few changes.

**Comment by PieterHartzer** [comment]
@tsonevn Thank you for taking the time to fix the project, but that was a very simple example to demonstrate the issue and I will make use of the `auto` with different icon sizes depending on the screen size.

[This page](https://docs.nativescript.org/ui/ns-ui-widgets/layouts#grid-layout) states the following which I guess must be incorrect and fixed - I have reported it.

> The width of a column and the height of a row can be specified as an absolute amount of device independent pixels (e.g. rows="100, 50"), as a percentage (e.g. rows="20%, 60%, 20%") of the available space or automatically (e.g. rows="*, *, auto).

**Comment by NathanaelA** [comment]
@PieterHartzer - GridLayouts are my favorite layout; they are awesome...

You can use "*" for percentage of remaining area. 
 For example:
`<GridLayout rows="2*,28*,20*"/>`   

// 2+28+20 = 50...  So: 
Row 0 to be 4%  of the area.   
Row 1 = 56% of the area. 
Row 2 = 40% of the area.   

If you wanted to keep your math even simpler; you could even do:
<GridLayout rows="4*,56*,40*"/> and by making sure it equals 100 and * will basically act like %.

The nice thing about GridLayouts is that you can do this:
<GridLayout rows="auto,100,2*,3*">
The row=0 will automatically take as much room as needed.   Row=1 will take 100dp units.  Then the remaining space 2/5's will go to row 3 and 3/5 will go to the last row.

**Comment by PieterHartzer** [comment]
@NathanaelA Thank you so much for the detailed explanation and it definitely made things so much clearer. 
I am looking at the GridLayout after attending the NS day in Amsterdam in April and seeing Shiv's great talk. I always steered clear of it because of HTML experience with Tables, but seeing as it's a performance gain I want to use it.

**Comment by farfromrefug** [comment]
Just stumbled upon that issue because i wanted to do this `rows="auto,auto,*,auto,60%"`
There is no way to do that now.  Why it bugs me is that because of that i need to add one view hierarchy. One reason why i think percentage would be really useful.
