### ISSUE TITLE
Support for SignalR and NGINX Pushstream

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#72]
_From @kdubious on March 7, 2015 7:0_

It would be great to have access to "websocket" style notifications from tools like SignalR and Pushstream.

_Copied from original issue: NativeScript/cross-platform-modules#145_

**Comment by enchev** [comment]
_From @hamorphis on March 11, 2015 9:41_

Can you provide an example technology or other JavaScript libraries that support these. Please, elaborate on what features and functionality you would expect from such a NativeScript module. Dummy sample code would also be very helpful. In other words, point us in the right direction.

**Comment by enchev** [comment]
_From @kdubious on March 12, 2015 19:16_

Hi. Pushstream is a small JS file provided by NGINX to work with their 2-way we socket based communication platform. SignalR is the Microsoft approach.

My suggestion would be to create modules to work with these 2 technologies.

Pushstream makes use of "window.", so it wont work out of the box.

We would like to write an app that controls a piece of hardware on the local network. An IoT device. This device uses an NGINX webserver. We need our NativeScript client app to be able to subscribe to the pushstream web socket to get real time updates from the server.

Perhaps Pushstream.js can be easily rewritten to do what we need, but I have not yet been able to remove the dependencies on "window."

Does NativeScript support "websockets"? Can you have a look at pushstream.js?

**Comment by enchev** [comment]
_From @kdubious on March 12, 2015 19:42_

Here are a few items from the pushstream.js file that would need to be addressed:

`window.WebSocket`
`window.JSON.parse()`
`window.XMLHttpRequest();`
`window.XDomainRequest();`
`window.setTimeout()`
`window.attachEvent()`
`window.addEventListener()`

Can these be converted for use in NativeScript?

**Comment by enchev** [comment]
_From @jopima on March 30, 2015 7:30_

Am also looking at the possibility of Using NativeScript with SignalR. There is a possibility of having this done with .net client apps (desktop) but around a non .net client and out of web context. am curious to know the hows.

**Comment by enchev** [comment]
_From @ligaz on March 30, 2015 19:19_

Here is Cordova plugin that implements the WebSockets API for Android. We can use it as a reference: https://github.com/knowledgecode/WebSocket-for-Android

**Comment by enchev** [comment]
_From @ligaz on March 30, 2015 19:34_

@kdubious Apart from mimicking the WebSocket API the [`pushstream.js`](https://github.com/wandenberg/nginx-push-stream-module/blob/master/misc/js/pushstream.js) is also using the `document` and some browser specific elements like `head` and `iframe` tags. This have to be abstracted in the `pushstream` code base in order to be able to run outside of the browser context.

**Comment by enchev** [comment]
_From @kdubious on March 31, 2015 2:42_

I can deal with re-writing Pushstream.js, if there is a means of accessing WebSockets. To be honest, I'm not far along the NativeScript learning curve, but I think a supported WebSocket client would get me started. Am I missing something obvious, ligaz?

**Comment by enchev** [comment]
_From @ligaz on March 31, 2015 12:52_

I can give you a pointer how I would have approached writing WebSocket support for NativeScript but you should be warn that this is not a walk in the park :warning: 

Here are the steps:
1. I would take the [Jetty code](https://github.com/knowledgecode/WebSocket-for-Android/tree/master/src/android/org/eclipse/jetty) that is used in the Cordova plugin and compile it as jar.
2. Having the jar I will use the `tns library add` to and it to a NativeScript project.
3. I will re-write the [Java code](https://github.com/knowledgecode/WebSocket-for-Android/tree/master/src/android/com/knowledgecode/cordova/websocket) in the Cordova plugin to JavaScript. I will constantly consult with [NativeScript Android runtime documentation](http://docs.nativescript.org/runtimes/android/overview).
4. I will adapt [the JavaScript part](https://github.com/knowledgecode/WebSocket-for-Android/blob/master/www/websocket.js) of the plugin so it does not use the Cordova bridge for communication but rather the JavaScript code I have previously written.
5. Test and debug until I make it work :sweat_smile:

Hope this helps get you started.

**Comment by enchev** [comment]
_From @broderix on April 21, 2015 12:13_

Hi, @ligaz, any updates? Thank you!

**Comment by enchev** [comment]
_From @ligaz on April 24, 2015 7:3_

Hey @broderix,

I was just giving a pointer how I would have approached the problem. If you are willing to jump on it I can help you along the way.

**Comment by RangerMauve** [comment]
@ligaz Rather than jetty, I would suggest using [java-websocket](https://github.com/TooTallNate/Java-WebSocket). I might actually take on this challenge if I can figure out how to interface with libraries bettter.

**Comment by bluebug** [comment]
there is one nodejs module for websocket, may be someone can integrate into nativescript

https://github.com/theturtle32/WebSocket-Node/blob/master/lib/WebSocketClient.js

**Comment by RangerMauve** [comment]
@bluebug The issue with that is that NativeScript is not compatible with Node.js's API.

**Comment by Nathanaela** [comment]
(On WebSockets) I already have a working Android version I will be releasing in a couple days; I'm currently looking at the IOS side.   I prefer to release for both platforms initially.

**Comment by Nathanaela** [comment]
I have finally release my [NativeScript WebSockets](https://github.com/NathanaelA/nativescript-websockets).  It fully supports both iOS and Android.  It has both the web browser socket support and an more advanced socket support.    The browser version should make things like this much easier to convert.  You should be able to use nativescript plugin command to install it.

**Comment by valentinstoychev** [comment]
@kdubious - have you tried using the plugin created by @NathanaelA?
