### ISSUE TITLE
Back Navigation icon has changed

### ISSUE THREAD

**Issue by ryanzaatari** [NativeScript/NativeScript#7202]
<img width="143" alt="Screen Shot 2019-05-03 at 11 24 17 AM" src="https://user-images.githubusercontent.com/19889931/57126705-90995280-6d96-11e9-8c88-0dc1d939265a.png">

Back button has changed from **<** to the **hamburger** icon, & can't figure out how to revert back.

**Comment by NathanaelA** [comment]
@ryanzaatari - What does your markup look like.

**Comment by ryanzaatari** [comment]
@NathanaelA no explicit nav icon setting, here's my ActionBar markup
<ActionBar class="action-bar">
    <ActionItem icon="res://menu" 
            android:visibility="collapsed" 
            tap="onDrawerButtonTap"
        ios.position="right">
    </ActionItem>
    <Label class="action-bar-title" text="دعوى قضائية"></Label>
    <ActionItem text="حفظ"
            android:visibility="collapsed" 
            tap="btnSave"

        ios.position="left">
    </ActionItem>
</ActionBar>

**Comment by NathanaelA** [comment]
What happens if you actually quit the application on the phone, and then start it back up.  Does the icon go back to what you expect?

If so, then the reason this is occurring is probably because of LiveSync, when it is syncing any of your update to the pages to the phone it navigates to the update.  Which causes you to be on a different page; meaning it thinks their is a page to go back to...  This "issue" would only be seen while you are in developing your app...

**Comment by ryanzaatari** [comment]
Thank you @NathanaelA I quit the app, uninstalled, & reinstalled it again & the icon is back to "<" again.

**Comment by NathanaelA** [comment]
You shouldn't have to uninstall/re-install.  Just force the app to quit; so that when you restart it -- it is a fresh session.  :grinning:  (i.e. go to the list of running apps; then swipe the app off the screen (or hit the X) depending on the OS version -- then restart the app.. )

**Comment by tsonevn** [comment]
HI @ryanzaatari,

I noticed that you were able to solve your case thanks to the @NathanaelA. In my opinion, we can close the issue. On that matter, I would also suggest testing [NativeScript HMR option](https://www.nativescript.org/blog/nativescript-5.3-hot-module-replacement-officially-supported-and-more). This option will restart more precisely the application state, and the above-described scenario should be resolved as well.
