### ISSUE TITLE
How can I restore Nativescript application code from android device?

### ISSUE THREAD

**Issue by abozanona** [NativeScript/NativeScript#7210]
When I create an APK while developing a Nativescript application, Nativescript stores all the application code in the generated APK file, and that helps me a lot in case something bad happened to the code[The code was deleted, Didn't commit changes I was working on for a long time,...]. When something bad happens to the code, I usually generate an APK from my android device using any *APK Extractor* tool and decompile it with JADX to obtain my original code and save my day.

Nativescript doesn't generate NEW APKs when I make changes to layout or js files[even though changes are applied on the android device]. Nativescript generates new APKs only when I build the project. and that doesn't help a lot when I need to restore my code after a lot of changes on it.

We're working on a nativescript application. We've been making changes on the application for about two days without generating new APK nor committing changes to git. The files where suddenly removed from pc and we don't know why.

We extracted an APK from the latest working version on the test android device, decompiled it and retrieved the code but the changes of the last two days weren't there.

**Is there a way to restore the code from a Nativescript application installed on android devices?** By restoring the code I mean even restore all the changes on the code after building the application.

**Where does nativescript store the instant changes on the code for my application on the android device?**

**Comment by NickIliev** [comment]
@abozanona as a main rule working on a larger project for a longer time would require using some kind of source control (e.g. GitHub or Bitbucket) - the livesync option is not to be relayed when there are uncommitted and unsaved changes. As for your question - to be sure that the changes are included in the APK you should stop the livesync (now known simply as the. `run` command) and rebuild the project to produce an APK with the latest files.
