### ISSUE TITLE
The tap area is shifted down on the icons of a font on iOS

### ISSUE THREAD

**Issue by elvticc** [NativeScript/NativeScript#7214]
**Environment**
 - CLI: 5.3.4
 - Cross-platform modules: 5.3.2
 - Android Runtime: 5.3.1
 - iOS Runtime/iOS version: 5.3.1/12.2
 - Plugin(s): Angular, Firebase, IQKeyboardManager, Secure Storage, Social Share, Dev Sass

**Describe the bug**
The tap area is shifted down on the icons of a font on iOS. By tapping directly on the icon does not trigger any action, you must tap below the icon to start the action.

**To Reproduce**
You have to add an icon font on a CSS class. Then you have to put an icon on the label's text property and add the action tap on this label.

**Expected behavior**
You can not perform the action by tapping the icon directly, just click below to start the action.

**Comment by tsonevn** [comment]
Hi @elvticc,
I tested the described scenario, however, was unable to recreate the problem. For your convenience, I am attaching [a link ](https://play.nativescript.org/?template=play-js&id=bDUkh9) to the project, that I used for testing. Please review it and make the needed changes that will allow me to reproduce the issue.

**Comment by elvticc** [comment]
Hi @tsonevn 

Your test project link is exactly what I do, but the problem persists on my iPhone SE. Is it because of the small size of the screen?

Thanks a lot for your tests.

**Comment by tsonevn** [comment]
Hi @elvticc,
I just tested the sample project with iPhone SE simulator (iOS 12.1), however, I am still unable to recreate a problem. For your convenience, I am attaching GIF file, which demonstrates the behaviour on my side.
![Screencast 2019-05-10 at 8 32 08 AM](https://user-images.githubusercontent.com/17448734/57504856-d73efd80-72fe-11e9-8f0c-ee281098cef4.gif)

Let me know if I am missing something or if there are some specific steps that should be followed.

**Comment by elvticc** [comment]
Hi @tsonevn 

Thank you for your help.

I will review my code.
