### ISSUE TITLE
Reversible ObservableArray

### ISSUE THREAD

**Issue by sotisoti** [NativeScript/NativeScript#7217]
**Environment**
 - CLI: 5.3.0
 - Cross-platform modules: 5.3.4
 - Android Runtime: 5.3.0

**Describe the bug**
Nativescript doesn't seem to be able to retrieve the key (getItem) from a reversed ObservableArray. 

**To Reproduce**
```
    var test = new ObservableArray([
      { name: "item1", value: "a" },
      { name: "item2", value: "b" },
      { name: "item3", value: "c" }
    ]);
    var final = test.reverse();
   // works fine without calling the reverse() method. 
   //var final = test;
    console.log("last item:::: " + JSON.stringify(final.getItem(2)));
```

**Expected behavior**
Print the property of index 2. Which is { name: 'item3', value: 'c' }

**Comment by tsonevn** [comment]
Hi @sotisoti,
The `reverse` will return a new pure JavaScript Array. You can check the NativeScript API ref [here](https://github.com/NativeScript/NativeScript/blob/b7abb3dd/tns-core-modules/data/observable-array/observable-array.d.ts#L127). You can access the needed item by using JavaScript syntax:`final[0]` If you want using an observable array again you can create a new one after reversing the `test` array. For example:
```
 var test = new ObservableArray([
        { name: "item1", value: "a" },
        { name: "item2", value: "b" },
        { name: "item3", value: "c" }
      ]);
      console.log("last item:::: " + JSON.stringify(test.getItem(2)));
      var final = new ObservableArray(test.reverse());
      console.log("last item:::: " + JSON.stringify(final.getItem(2)));
```
