### ISSUE TITLE
Is it possible to use Polymer WebComponents with NativeScript ?

### ISSUE THREAD

**Issue by joao-parana** [NativeScript/NativeScript#722]
Is it possible to use some feature of Polymer WebComponents with NativeScript ? 

If NO, I can use Vanilla JavaScript to create a WebComponent.

    var MegaButton = document.registerElement('mega-button', {
      prototype: Object.create(HTMLButtonElement.prototype),
      extends: 'button'
    });

And use the component this way:

    var megaButton = document.createElement('mega-button');
    document.body.appendChild(megaButton);

Is it supported ? 

Android Browser have native support to registerElement on Document object and there is a Polypill to Safari on iOS

**Comment by NathanaelA** [comment]
NativeScript does not have **web** components in that fashion.  It uses **components** but not in the traditional HTML Web component sense.   

  So for example; var Sqlite = require('nativescript-sqlite');  var db = new Sqlite();   And you would have a database component.   NativeScript has many components builtin, and if you check npm; you can see a growing number of plugins (i.e. components). That others have developed.

NativeScript does not have a DOM or html; so no document, and no need to do a "registerElement".   You just do a require() and you have a usable component.    

Just in case the above isn't clear; you can create your own plugins (or components) that you want.  But they different than the normal web based components.   And yes, they are all JavaScript based.

**Comment by joao-parana** [comment]
@NathanaelA I understood but I would like to reuse my NativeScript code on the web version of my application. I thought I could read the XML file with Layout and generate compliant Polymer code. 
Additional information I would put as a comment in the XML file and I could treat by the XML parser.
Such an approach would be possible?

**Comment by enchev** [comment]
The best option we can offer for code reuse between native and web is our Angular 2 support (Angular components) which is coming soon. You can check the progress here:
https://docs.google.com/document/d/1J6fZcVbVa6uONVCJIox2A3Jn5TWgspLufmryfA1OXGk/edit?pli=1#heading=h.trgonlvb0z3j
