### ISSUE TITLE
Disabled and Uneditable TextField can take focus

### ISSUE THREAD

**Issue by AdamAtri** [NativeScript/NativeScript#7233]
**Environment**

Playground Link: https://play.nativescript.org/?template=play-tsc&id=DwU7vz&v=3

Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - nativescript. Your current version is 5.2.3 
 - tns-core-modules. Your current version is 4.2.1
 - tns-android. Your current version is 4.2.0
- Android runtime: ( 6.0.1  |  8.1.0 ) 

**Describe the bug**
`TextField`s take focus even when they have `.isEnabled` and `.editable` set to `false`.
In some cases this will cause the soft input to rise to edit a field that is not editable at the time. 

**To Reproduce**
See playground app: https://play.nativescript.org/?template=play-tsc&id=DwU7vz&v=3

**Expected behavior**
That disabled textFields do not take focus.
??? May have something to do with being in a modal view

**Comment by tsonevn** [comment]
Hi @AdamAtri,
I tested the provided sample project on Android device with the latest `tns-core-modules` v.5.3.2 and `tns-android` v. 5.3.2, and I was unable to recreate the problem. Can you upgrade your project to the most recent `tns-core-modules` and `tns-android` and check if you will be able to recreate the issue?

**Comment by AdamAtri** [comment]
@tsonevn thanks for taking a look. Are you saying that the focus event didn't fire?

**Comment by tsonevn** [comment]
@AdamAtri 
Yes, the focus event has not been fired on my side, which seems to be expected when the field is disabled and can not be focused. Make sure that you are using the latest NativeScript Preview app version. Also, can you provide more info about the device that you are using for testing?
