### ISSUE TITLE
hello i can't load the camera from webview

### ISSUE THREAD

**Issue by enfraly** [NativeScript/NativeScript#7234]
i need load this page in webview https://playcanv.as/p/jH8nuvmK but dont pop up camera permissions

**Comment by tsonevn** [comment]
Hi @enfraly,
You can check this forum thread [here](https://discourse.nativescript.org/t/webview-how-to-allow-access-device-camera-from-a-webview-url-on-browsers-it-works/6695/10), where this topic has been discussed.

**Comment by enfralys** [comment]
hi, This topic dont work for me i can't charge the prompt

**Comment by tsonevn** [comment]
HI @enfralys,
Did you try extending the WebChromeClient as it was demonstrated in the sample [here](https://play.nativescript.org/?template=play-tsc&id=CndpgD&v=1&_ga=2.150229557.2077739449.1558931394-2022237003.1548063582)?

**Comment by enfralys** [comment]
Yes, but it does not work: C I think it's impossible to do this ... I use https://test.webrtc.org/ to try

**Comment by tsonevn** [comment]
HI @enfralys 
Can you send us the project that you are using for testing?

**Comment by enfralys** [comment]
> HI @enfralys
> Can you send us the project that you are using for testing?

Of course! How i send?

**Comment by tsonevn** [comment]
You can attach it here in the issue or send it as a private message via our [Slack channel](https://nativescriptcommunity.slack.com). My nickname is `nikts`.

**Comment by butaminas** [comment]
Has anyone found a solution for this? I have the same problem. Can't get camera to work from webview from both iOS and Android.

**Comment by sido420** [comment]
updates?
