### ISSUE TITLE
Pull-to-refresh in views without ListView control

### ISSUE THREAD

**Issue by danicomas** [NativeScript/NativeScript#724]
Sometimes we need to refresh a page with some details not only with a ListView.

**Comment by danicomas** [comment]
Related https://github.com/NativeScript/NativeScript/issues/51#issuecomment-139492097

**Comment by stevetayloruk** [comment]
+1

**Comment by bradmartin** [comment]
https://www.npmjs.com/package/nativescript-pulltorefresh - needs iOS. If willing contact me.

**Comment by enchev** [comment]
I'm closing this in favor of this plugin:
https://github.com/bradmartin/nativescript-pulltorefresh

**Comment by bradmartin** [comment]
Update to those who wanted the plugin. iOS native control UIRefreshControl support has been added and updated on npm. `npm i nativescript-pulltorefresh`
