### ISSUE TITLE
Builed Failed: Too few bytes to read ASN.1 value.

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/NativeScript#7240]
**Describe the bug**

when using `tns cloud` for ios release build it fails with error: `Builed Failed: Too few bytes to read ASN.1 value.`

**To Reproduce**

`tns cloud build ios --release --certificate="/Users/stiofan/Downloads/NSPlayground/.cert/U2M49JU375.p12" --provision="/Users/stiofan/Downloads/NSPlayground/.cert/AppStore_io.ayecode.mobileprovision" --certificatePassword=secret`

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #4620](https://github.com/NativeScript/nativescript-cli/issues/4620) via [**ZenHub**](https://www.zenhub.com/)
