### ISSUE TITLE
RadioButton not working with Angular

### ISSUE THREAD

**Issue by Geeta-Singh** [NativeScript/NativeScript#7243]
I'm getting issue when I added '  tns plugin add nativescript-radiobutton'
ERROR:
node_modules/nativescript-radiobutton/angular/radiogroup.component.ts(5,36): error TS2307: Cannot find module 'data/observable'.
node_modules/nativescript-radiobutton/index.d.ts(1,22): error TS2307: Cannot find module 'ui/core/view'.

**Environment**
TNS : 5.3.4

Angular:
Angular CLI: 7.3.8
Node: 10.15.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular-devkit/architect 
@angular-devkit/core 7.1.4
@angular-devkit/schematics 7.1.4
@ngtools/webpack 7.2.4
@schematics/angular 7.1.4
@schematics/update 
rxjs 6.3.3
typescript 3.1.6
webpack 4.27.1

**Comment by danielgek** [comment]
@Geeta-Singh this is a problem of the plugin that you are using not with the framework it self, try to contact the author, it seams the imports on the plugin are deprecated, instead of `'ui/core/view'.` it should be `'tns-core-modules/ui/core/view'.`

**Comment by tsonevn** [comment]
Hi @Geeta-Singh,
@danielgek is right. The reported problem seems to be related to the  `nativescript-radiobutton`. Please contact the plugin's author by opening a new issue in `nativescript-radiobutton`'s [repository](https://github.com/Tunaweza/nativescript-radiobutton#readme).

**Comment by Geeta-Singh** [comment]
Thnaku @danielgek and @tsonevn ..
