### ISSUE TITLE
Custom Page Transition Using snapshotView and Pan Gestures

### ISSUE THREAD

**Issue by drewcovi** [NativeScript/NativeScript#7245]
**Is your feature request related to a problem? Please describe.**
 
Modern app design and development leverages fluid inter-page transitions of certain UI elements. To accomplish this, we need access to previous view and next view, as well as access to nested view elements and methods to snapshot those elements.

**Describe the solution you'd like**

If this is already possible, it would be helpful to have some documentation on how one can set up a promise between page transitions that would allow someone to hook into the event and bind UI element snapshots to pan gesture coordinates (for instance when leveraging "back" pan navigation).

**Describe alternatives you've considered**

As far as I can tell there are no alternatives. This is accomplished in Swift using the methods described above. https://medium.com/rosberryapps/tricky-uiviewcontroller-transition-animations-59131b540b33

**Comment by NickIliev** [comment]
@drewcovi you can create your own custom page transition as described [in this documentation section](https://docs.nativescript.org/ui/ns-ui-widgets/frame#navigation-transitions) (scroll to **_Custom Transitions_** subsection)

e.g. (iOS example taken from the documentaiton)
```TypeScript
// import { Transition } from "tns-core-modules/ui/transition";
declare let UINavigationControllerOperation: any; // or use tns-platform-declarations

export class CustomTransitionIOS extends Transition {
    public animateIOSTransition(containerView: UIView,
                                fromView: UIView,
                                toView: UIView,
                                operation: UINavigationControllerOperation,
                                completion: (finished: boolean) => void): void {
        const originalToViewTransform = toView.transform;
        const originalFromViewTransform = fromView.transform;

        // http://stackoverflow.com/questions/216076/uiview-scale-to-0-using-cgaffinetransformmakescale
        const scaleTransform = CGAffineTransformMakeScale(0.0001, 0.0001);

        toView.transform = scaleTransform;
        fromView.transform = CGAffineTransformIdentity;

        switch (operation) {
            case UINavigationControllerOperation.UINavigationControllerOperationPush:
                containerView.insertSubviewAboveSubview(toView, fromView);
                break;
            case UINavigationControllerOperation.UINavigationControllerOperationPop:
                containerView.insertSubviewBelowSubview(toView, fromView);
                break;
            default:
                break;
        }

        const duration = this.getDuration();
        const curve = this.getCurve();
        UIView.animateWithDurationAnimationsCompletion(duration, () => {
            UIView.setAnimationCurve(curve);
            toView.transform = CGAffineTransformIdentity;
            fromView.transform = scaleTransform;
        }, (finished: boolean) => {
            toView.transform = originalToViewTransform;
            fromView.transform = originalFromViewTransform;
            completion(finished);
        });
    }
}
```
