### ISSUE TITLE
Can't remove/add platform after upgrading the cli to v5.4.0

### ISSUE THREAD

**Issue by jannomeister** [NativeScript/NativeScript#7247]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: **5.4.0**
 - Cross-platform modules: **5.4.0**
 - Android Runtime: 5.3.1 **(not the latest version because of the issue)**
 - iOS Runtime: 5.3.1 **(not the latest version because of the issue)**
 - Plugin(s):

**Describe the bug**
after upgrading the `nativescript` cli to 5.4.0 I can't execute the `tns platform add` command.

<img width="1029" alt="Screen Shot 2019-05-16 at 5 10 44 PM" src="https://user-images.githubusercontent.com/46916819/57841686-9b73ce80-77fd-11e9-882a-143b9d25194d.png">

**To Reproduce**
upgrade first your nativescript cli to v5.4.0 using `npm install -g nativescript` and remove a platform by executing `tns platform remove android/ios` and the error occurs

**Expected behavior**
should remove the specified platform

**Sample project**
none

**Additional context**
none

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-cli #4626](https://github.com/NativeScript/nativescript-cli/issues/4626) via [**ZenHub**](https://www.zenhub.com/)
