### ISSUE TITLE
Add Delete, Edit buttons on swipe left in ListView

### ISSUE THREAD

**Issue by danicomas** [NativeScript/NativeScript#725]
Can we do this now?

**Comment by ginev** [comment]
Hi @danicomas , this is currently being worked on and will be available in Telerik UI for NS. Stay tuned.

**Comment by danicomas** [comment]
Nice @ginev

**Comment by danicomas** [comment]
Is it done @enchev ?

**Comment by ginev** [comment]
Hello @danicomas ,

yes, this feature is already available. Take a look here: 
http://docs.telerik.com/devtools/nativescript-ui/Controls/ListView/listview-features-swipe-to-execute

and here:

https://github.com/telerik/nativescript-ui-samples/tree/release/sdk/app/listview/swipe-execute

And also the shiny AppStore demo:
https://github.com/NativeScript/nativescript-marketplace-demo/tree/production/app/examples/listview/reorder

Please, post any questions in the https://github.com/telerik/nativescript-ui-samples repo.

**Comment by prantikv** [comment]
Can the same be achieved using angular2?

**Comment by tbehunin** [comment]
@prantikv Could be wrong, but I think it's already available (see here: http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/ListView/overview). Haven't tried it yet though.
