### ISSUE TITLE
Could not get unknown property 'VersionNumber' for project ':app' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by SuperAssassinNinja** [NativeScript/NativeScript#7257]
After updating my nativescript to 5.4.0 and trying to run android with webpack this is happening

app.gradle
android {
  compileSdkVersion 28
  buildToolsVersion '28.0.3'

  defaultConfig {
    generatedDensities = []
    applicationId = "APP-KEY"
    versionCode 1
    versionName "1.0"
    VersionNumber 2

    ndk {
        abiFilters.clear()
        abiFilters "armeabi-v7a"
 	}

  }
    aaptOptions {
        additionalParameters "--no-version-vectors"
    }

    project.ext {
       googlePlayServicesVersion = "15.8.0"
    }
}

project.ext {
       firebaseMessagingVersion = "15.0.1" // OR the version you wish
}

def settingsGradlePath = "$rootDir/../../app/App_Resources/Android/settings.gradle";
def settingsGradleFile = new File(settingsGradlePath);

if(settingsGradleFile.exists())
{
    apply from: settingsGradleFile;
}

Time: 10577ms
         + setting applicationId

FAILURE: Build failed with an exception.

* Where:
Script '/Users/alexandre.melo/projetos/connect/node_modules/nativescript-plugin-firebase/platforms/android/include.gradle' line: 22

* What went wrong:
A problem occurred evaluating script.
> Could not get unknown property 'VersionNumber' for project ':app' of type org.gradle.api.Project.

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #4630](https://github.com/NativeScript/nativescript-cli/issues/4630) via [**ZenHub**](https://www.zenhub.com/)
