### ISSUE TITLE
Webpack migration in 5.4.0 breaks unit tests

### ISSUE THREAD

**Issue by JonLevy** [NativeScript/NativeScript#7261]
**Environment**
```
tns info:
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.4.0 version and is up to date.
✔ Component tns-core-modules has 5.4.0 version and is up to date.
✔ Component tns-android has 5.4.0 version and is up to date.
✔ Component tns-ios has 5.4.0 version and is up to date.
```

**Describe the bug**
Migrating to the WebPack workflow causes Unit Tests to not run.

**To Reproduce**
`tns test ios --justlaunch` (and 'n' to WebPack migration prompt) runs the tests successfully and returns.

(Manually remove useLegacyWorkflow from nsconfig.json.)

`tns test ios --justlaunch` (and 'Y' to WebPack migration prompt) migrates to WebPack, but does not run tests or return. Instead launches the app, similar to a run command.

**Expected behavior**
The unit tests should continue to run.

**Additional context**
Also posted at https://stackoverflow.com/questions/56188421/nativescript-angular-webpack-migration-causes-tests-to-not-run

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-dev-webpack #898](https://github.com/NativeScript/nativescript-dev-webpack/issues/898) via [**ZenHub**](https://www.zenhub.com/)
