### ISSUE TITLE
NS 5.4 HMR: state not persisted

### ISSUE THREAD

**Issue by demetrio812** [NativeScript/NativeScript#7262]
Hello,
I've just migrated my project to NS 5.4, everything so far with HMR except that on reload also the state persisted in some services gets lost, is there something specific I have to do to save the state, or should it works or perhaps the services shouldn't reload at all?

Thanks

**Comment by NickIliev** [comment]
@demetrio812 you should use a state manager and persist the state manually. We are planning to release a  blog post with details pretty soon.
