### ISSUE TITLE
Marketplace Demo "Basic Listview with Images" bad link

### ISSUE THREAD

**Issue by lonerzzz** [NativeScript/NativeScript#7263]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
current online state of Marketplace

**Describe the bug**
I have raised the bug here as I saw no other means of providing input.

In the marketplace, the demo "Basic Listview with Images" has a bad link. It links to a Hispanic restaurant viewing application instead of the stated listview demo. Additionally, the replacement application is broken. I have fixed it here:

https://play.nativescript.org/?template=play-ng&id=2OkUP6&v=29

**To Reproduce**
Look for the demo as titled above and follow the playground link to it.

**Expected behavior**
I was looking for the multicolumn listview demo, but it was unavailable and i had to fix the existing demo to confirm what I was getting instead.

**Sample project**
Not applicable.

**Additional context**

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/marketplace-feedback #161](https://github.com/NativeScript/marketplace-feedback/issues/161) via [**ZenHub**](https://www.zenhub.com/)
