### ISSUE TITLE
JS ERROR TypeError: undefined is not an object (evaluating 'length.unit')

### ISSUE THREAD

**Issue by guzz** [NativeScript/NativeScript#7267]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
Component nativescript has 5.4.0 version and is up to date.
Component tns-core-modules has 5.4.0 version and is up to date.
Component tns-android has 5.4.0 version and is up to date.
Component tns-ios has 5.4.0 version and is up to date.

**Describe the bug**
I'm having a strange problem using a simple TextField with nativescript-vue. I have other components that have the same structure in this app and don't show this problem, I am trying to understand why is it behaving differently in each component.

In IOS whem I focus this TextField and start to write, the first letter, it breaks the app with this stack of errors:

```
JavaScript stack trace:
1   toDevicePixelsCommon@file:///app/vendor.js:166452:17
2   _updateEffectiveLayoutValues@file:///app/vendor.js:149592:75
3   measureChild@file:///app/vendor.js:149392:41
4   layoutView@file:///app/vendor.js:150499:22
5   viewDidLayoutSubviews@file:///app/vendor.js:161612:28
6   UIApplicationMain@[native code]
7   _start@file:///app/vendor.js:129775:22
8   run@file:///app/vendor.js:129817:9
9   $start@file:///app/vendor.js:107226:18
10  $start@file:///app/bundle.js:36966:25
11  @file:///app/bundle.js:30284:10
12  ./app.js@file:///app/bundle.js:30288:34
13  __webpack_require__@file:///app/bundle.js:76:34
14  checkDeferredModules@file:///app/bundle.js:45:42
15  @file:///app/bundle.js:149:38
16  anonymous@file:///app/bundle.js:150:12
17  evaluate@[native code]
18  moduleEvaluation@[native code]
19  promiseReactionJob@[native code]
20  require@[native code]
21  anonymous@file:///app/starter.js:2:8
22  evaluate@[native code]
23  moduleEvaluation@[native code]
24  promiseReactionJob@[native code]
JavaScript error:
file:///app/vendor.js:166452:17: JS ERROR TypeError: undefined is not an object (evaluating 'length.unit')
```

For what i see is an update in the layout that is receiving undefined instead of an object, I'm not using typescript.

It is working fine in Android.

**Comment by NickIliev** [comment]
@guzz pleases provide a [vue Playground app ](https://play.nativescript.org/) with your implementation.
