### ISSUE TITLE
animation-direction: alternate;

### ISSUE THREAD

**Issue by bkwhite** [NativeScript/NativeScript#7268]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.4.0
 - Cross-platform modules: 5.4.0
 - Android Runtime: 5.4.0
 - iOS Runtime: 5.4.0
 - Plugin(s):

**Describe the bug**
```
animation-direction: alternate;
```` 
Has no effect on the css animation. The animation does not alternate as expected.
![2019-05-20 11 20 10](https://user-images.githubusercontent.com/1873332/58034428-9318dd80-7af4-11e9-9d35-82534ab650dd.gif)

**To Reproduce**
```
.error {
  animation-name: backgroundColor;
  animation-duration: 2s;
  animation-direction: alternate;
  animation-iteration-count: infinite;
}
@keyframes backgroundColor {
  0% {
    background-color: #ff0000;
  }
  100% {
    background-color: darken($color: #ff0000, $amount: 60%);
  }
}
```

**Expected behavior**
To alternate properly like the browser. 
![2019-05-20 11 36 38](https://user-images.githubusercontent.com/1873332/58034436-96ac6480-7af4-11e9-970d-a8e3f1dd11d2.gif)

**Sample project**
https://play.nativescript.org/?template=play-vue&id=NWSULR

**Comment by NickIliev** [comment]
@bkwhite the alternate option is not supported everywhere - see the support graph [here ](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-direction#Browser_compatibility)for details
