### ISSUE TITLE
Provide a way to get a reference to the currently showing modal page instance.

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#727]
There does not seem to be an equivalent way to get the current modal view that is running like you can get the current non-modal page from the frame.topmost().    With the frame.topmost() you can do view.getViewById(frame.topmost(), "id") and find an id somewhere on the running non-modal page.   

However, if a modal page is up; it is not included in the search.     Is their another technique other than capturing the modal page object on the loaded event?   (i.e. so if I have a library that auto-searches for something it can find it if it is a normal page or a modal page).

Did I miss something, or does the frame code need some addition code to allow the modal pages to be included in a modal stack so that the search can find it?

**Comment by N3ll** [comment]
Hey @NathanaelA , you will have to use the instance method https://github.com/NativeScript/NativeScript/blob/master/ui/core/view.d.ts#L393 instead of the static one.

**Comment by NathanaelA** [comment]
@N3ll I assume you are meaning having a global variable that is already pointing to the model; then using that to do a getViewById?    i.e. myModel.getViewById('id') right?  

However, my problem is unless their is a cool function that I've missed something like view.getModal() that returns me a reference to the modal dynamically; then I'm stuck adding a global variable that I have to clean up when the modal is closed.  I really **HATE** adding globals for no reason other than to work around a framework issue that should be fixed.  So that is why this issue is raised.  :grinning:

**Comment by N3ll** [comment]
Hey, @NathanaelA , we misunderstood you question - sorry about that! The modal page cannot be accessed like that and it has nothing to do with the frame.topmost(), because it is not part of the navigation stack. Can you give us some more information about you are trying to achieve, so we can be more of a help? :)

**Comment by NathanaelA** [comment]
@N3ll, Hmm, let me check this was several weeks ago...   I was attempting to find the button and entry fields on the modal so that I could change it after some data was entered into fields.   I worked around the issue exactly how you were describing; by capturing the **args.object** on the **load** event and using it as a global variable in the page.  Then when I need to find an object I use that global variable and do a getViewById off of it.  

But I shouldn't have to dirty my global scope just to have access to find things that are currently running, which is why I reported this issue.    I would NOT be opposed to a helper function like frame.getModal() or some other helper function that can give me the current MODAL view that is running, just like frame.topmost() gives me the current non-modal view that is running.

**Comment by hamorphis** [comment]
OK. I will try to implement a frame.getModal() method.

**Comment by hamorphis** [comment]
Since a modal page always has a parent page, I decided to add a new property to the Page class called "modal". Getting it will return the currently shown modal page if any. So you could get it like this:

`var modalPage = frame.topmost().currentPage.modal;`

**Comment by hamorphis** [comment]
`var label = frame.topmost().currentPage.modal.getViewById("label");`

**Comment by erkanarslan** [comment]
@hamorphis This seems to be not working anymore. currentPage has no modal on it.
