### ISSUE TITLE
WebView: add navigation request to the load events

### ISSUE THREAD

**Issue by jnorkus** [NativeScript/NativeScript#7270]
**Is your feature request related to a problem? Please describe.**
I am trying to intercept a navigation event and read its request data so I can make decisions based on it.

**Describe the solution you'd like**
A solution would be to extend the load events with a request object.

**Describe alternatives you've considered**
Currently the only workaround I see is accessing the native APIs directly to overwrite NS implementation.

**Comment by NickIliev** [comment]
@jnorkus check out [the nativescript-webview-interface](https://www.nativescript.org/blog/plugin-nativescript-webview-interface) which allows two-way communication between the webview and the nativescript app.

As there is already a plugin for bi-directional communication I think there is no need to extend the basic WebView element.

**Comment by jnorkus** [comment]
@NickIliev thanks for the link. This plugin will come in handy but I don't see how it can help for my current case.

In the WebView I'm hosting pages that I have no control of. I need to be able to intercept a request once a redirect happens.

However I also found out it is not possible to see the POST request body with `WKWebView` as it has this limitation. So I'm choosing a different implementation path.

It could still be useful to be able to inspect the headers or any other data in a request.

**Comment by NickIliev** [comment]
@jnorkus as you have found out, there is a limitation in the implementation of the native control. Closing the issue as resolved but if anyone has ideas about implementation of the feature (to inspect headers) we are open for[ pull request from the community](https://www.nativescript.org/contribute)
