### ISSUE TITLE
[TNS 5.4] No frame was loaded

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#7273]
Hi,

Sine I updated my NS project to use `bundling` I had severals problem  !

I have a `home-page.xml` who work s expected without the `--bundle` `"useLegacyWorkflow": true` .. when i switch to the bundled version I receive `> Failed to load component from module: ./views/Maps/Maps.xml or file: null`

home-page.xml :  
```xml
<Page xmlns="http://www.nativescript.org/tns.xsd" navigatingTo="onLoaded" actionBarHidden="true">
    <TabView class="root-tabView" 
        iosIconRenderingMode="alwaysOriginal" androidTabsPosition="bottom" selectedIndex="1">
        <TabView.items>
            <TabViewItem title="Carte">
                <TabViewItem.view>
                    <Frame defaultPage="views/Maps/Maps"></Frame>
                </TabViewItem.view>
            </TabViewItem>

            <TabViewItem title="Home" >
                <TabViewItem.view>
                    <Frame defaultPage="views/home/home"></Frame>
                </TabViewItem.view>
            </TabViewItem>

            <TabViewItem title="{{ L('bookings') }}" badgeValue="3">
                <TabViewItem.view>
                    <Frame defaultPage="views/bookings/bookings"></Frame>
                </TabViewItem.view>
            </TabViewItem>
        </TabView.items>
    </TabView>
</Page>
``` 
Another think : 
The `nativescript-ios-uuid` dose not exist for `android` although I import it sine we are on `IOS` but still crash .. I think it can be solved from `Webpack` config but I am new on webpack !

Thanks

**Comment by NickIliev** [comment]
@kefahB Webpack will automatically bundle only pages that are postfixed with `--page` or `--root`. All other custom resources should be manually added to the webpack.config. Or you might just rename the files to end with the postfixes pointed above.

Here[ is the detailed answer](https://github.com/NativeScript/nativescript-dev-webpack/issues/867#issuecomment-486681864) related to your case.
