### ISSUE TITLE
Best practices for adding local content in iOS and Android

### ISSUE THREAD

**Issue by ikoif** [NativeScript/NativeScript#7279]
Hello NativeScript team. Firstly - amazing framework, awesome docs and great community!

I am developing a mobile app for the first time using {N} and I am having trouble finding guidelines for a very fundamental part of any app - where to store local resources.

## The case
The app that I'm building lists recipes and workout videos, which contain *images* and *videos*. The data is something I've already sorted thanks to tutorials and explanations online using [`nativescript-sqlite`](https://www.npmjs.com/package/nativescript-sqlite). Where to add (or store, or bundle) the rest of the media resources is what I find difficult to understand. 

What is further important in my case is that the app has an *in-app purchase* which when purchased, will give access to premium resources for the user, not accessible before that. Since the size of these files is quite big and the app has to be able to work offline, I wanted to have an `update mechanism`. The first iteration of this was done with a `.zip` file which was then extracted, but once the size got big, I ran out of memory and the [`nativescript-zip`](https://www.npmjs.com/package/nativescript-zip) was constantly throwing errors about being in a "Busy State". So the second iteration of this will be to pull a meta file that lists what to download with urls and build an iterator that will download each file one after the other. Easy-peasy. The question that arises here though is where do I download these files so they work for both iOS and Android, are not backed up by the iCloud and are accessible in the app.

## The research
The [iOS Data Storage Guidelines](https://developer.apple.com/icloud/documentation/data-storage/index.html) state:

> Data that can be downloaded again or regenerated should be stored in the <Application_Home>/Library/Caches directory. Examples of files you should put in the Caches directory include database cache files and downloadable content, such as that used by magazine, newspaper, and map applications.

Which makes sense, but in my case I need to have persistent data that is an inseparable part of the app and that can be downloaded again. 

The [`knownFolders`](https://docs.nativescript.org/api-reference/modules/_file_system_.knownfolders) gives me access to:
- `currentApp()` - This I assume is the folder that is accessible via the `~/` url prefix, also what is defined in the `nsconfig.json` as `"appPath"`. For *iOS* this is read-only, which means I can not download files into it.
- `documents()` - which allows read and write for iOS and Android, but the iOS Data Storage Guidelines state that this folder is backed up by iCloud, that's a no go since the size of the offline local resources can be ~600MB.
- `temp()` - this is probably the `<Application_Home>/Library/Caches` that iOS is mentioning (and a `temp` dir for Android) but I fear this might get cleared on system restart or as part of some other OS process that cleans the temporary directories. 

## The question
So how do I achieve this?
1. Where do I store my initial resources - videos and images?
2. Where do I download the premium resources once the purchase happens - ideally should go into the same place where the initial resources are so they are basically combined in one resource place?

**Comment by NickIliev** [comment]
@ikoif using `documents()` will get you an accessible path but there is one important note: the path will be accessible on a real device while there is no guarantee that the path will be accessible via emulator. So to test the functionality use a real iOS device. 

 Regarding the issue with iCloud backup, there is an option to exclude a given file from cloud backup but for this, you will need to access the native API (example [here](https://developer.apple.com/library/archive/qa/qa1719/_index.html)). Another option seems to be to use `temp()` as the temp folder won't be backed up  The folder won't be cleaned by the OS but can be cleaned explicitly by the user or by a third party tool. SO I would go with the `documents()` but I am not sure that removing the explicit backup is a good practice - especially when the files are large that could eat the device space pretty quickly (this is mentioned in the [guidelines ](https://developer.apple.com/icloud/documentation/data-storage/index.html)as well).

You can use [this blog post](https://blog.jscrambler.com/create-a-file-storage-mobile-app-with-nativescript-5/) as a reference on how to download a file and get an accessible path on both iOS and Android. There are some conceptual differences and on Android, you might need to access the native API to work with the external storage folders.

**Comment by OriIdan** [comment]
How do I exclude the knownFolders.documents() from iCloud in iOS using NativeScript?
