### ISSUE TITLE
Broken styles after enabling webpack 

### ISSUE THREAD

**Issue by ryanzaatari** [NativeScript/NativeScript#7286]
in my js core 5.4 NS app, if I set the property `useLegacyWorkflow` inside `nsconfig.json` to **false**, my project wide styling is no longer applied.

I'm currently importing my **custom.scss** file inside `_app-common.scss` file, which works just file by enabling the above mentioned property.

I tried adding `{from: "custom.scss"},` inside`new CopyWebpackPlugin`  in file `webpack.config.js` but to no avail.

**Comment by tsonevn** [comment]
Hi @ryanzaatari,
I've checked your case in a newly created sample project, however, was unable to recreate the problem. In the project, I've created a new scss file and import it into `_app-common.scss`. Then build the project and the styling that I've added in the custom file was applied correctly. For your convenience, I am attaching my sample project. Please review it and make the needed changes, that will allow us to recreate the problem.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/3222127/Archive.zip)

**Comment by ryanzaatari** [comment]
Hello @tsonevn & thank you for your response, I have noticed that in my case, when switching to the new workflow (_leaving everything else intact_), the below errors are generated in the console. 

<img width="834" alt="CSS_Loader_Issue" src="https://user-images.githubusercontent.com/19889931/58402497-27d98900-8069-11e9-97dc-f05d4883469e.png">

<img width="835" alt="Sqlite_Issue" src="https://user-images.githubusercontent.com/19889931/58402644-856dd580-8069-11e9-983f-cf6fe3f1fdf5.png">

**Comment by ryanzaatari** [comment]
I've just updated the webpack config file `./node_modules/.bin/update-ns-webpack --configs` following @DimitarTachev 's solution for the [issue here](https://github.com/NativeScript/nativescript-dev-webpack/issues/855#issuecomment-481637814) which resolved the CSS loading issue.

Many thanks.
