### ISSUE TITLE
HMR works incorrect

### ISSUE THREAD

**Issue by yn-tadpole** [NativeScript/NativeScript#7289]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.4
 - Cross-platform modules:5.4

**Describe the bug**
The HMR works correct when modify the css or template, but when you modify the JS, it stop to work.

**Comment by yn-tadpole** [comment]
I found the reason. It's because i used a 'console.log(....)' in the JS. When use 'console.log', it stop to work.

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #4653](https://github.com/NativeScript/nativescript-cli/issues/4653) via [**ZenHub**](https://www.zenhub.com/)
