### ISSUE TITLE
NativeScript Circular Menu Plugin

### ISSUE THREAD

**Issue by sujitbulu** [NativeScript/NativeScript#7291]
NativeScript community group has already released a Circular Menu plugin i.e. nativescript-circle-menu, but when am adding this plugin it does not support for Android platform where as it supports for iOS. Could you please let me know if there any solution be available in near future that would work in both iOS as well as Android platform.

When am adding the plugin nativescript-circle-menu using command "tns plugin add nativescript-circle-menu" in my window system, it displays below message: "nativescript-circle-menu is not supported for android."

Actual result - The circular menu plugin should work in both iOS and Android platform.

**Comment by tsonevn** [comment]
Hi @sujitbulu,
Indeed the `nativescript-circle-menu` plugin currently is supported only for iOS(this also has been mentioned in the plugin's [README](https://github.com/DeviantJS/nativescript-circle-menu)) and providing support for Android depend on the plugin's author. This plugin is not supported by NativeScript team. On that matter, I would suggest contacting the plugin's author by opening a [new issue ](https://github.com/DeviantJS/nativescript-circle-menu/issues/new) or fallow the existing one [here](https://github.com/DeviantJS/nativescript-circle-menu/issues/3).

**Comment by sujitbulu** [comment]
Thanks for your reply! I'll post the comments in the given link.

**Comment by sujitbulu** [comment]
Hi Nikolay - While going through the NativeScript document reference I read that NativeScript provides 0 days support to all Android and iOS plugin release. It means if any plugin is officially released by Android or iOS in the next day NS will release it's wrapper plugin that targets to both Android and iOS.

**Comment by NathanaelA** [comment]
@sujitbulu - Actually a slight misunderstanding; what the docs state is that NativeScript supports things out of the box on day one.   So when Android 28 was released (or Android API 29 is in the future released); you can actually call the API from NativeScript right away.     You don't have to create any extra stuff to make it work...    This also works for most plugins on iOS and Android also; but their are exceptions...
