### ISSUE TITLE
Make `column` a synonym for `col` property re layout child properties

### ISSUE THREAD

**Issue by paxperscientiam** [NativeScript/NativeScript#7295]
**Is your feature request related to a problem? Please describe.**
I had been trying to use a "column" property on child elements of the `GridLayout` element before realizing that I was using the wrong property -- d'oh! "col", of course, is the correct property.

**Describe the solution you'd like**
Make "column" a synonym for "col"

**Describe alternatives you've considered**
Maybe throw an error?

**Comment by rakeshgirase** [comment]
shouldn't this be closed now?
