### ISSUE TITLE
Support for local database 

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#73]
_From @ChristopherTotty on March 5, 2015 19:57_

It would be great if there were a module that interfaces with the native classes for SQLite database access.  This would allow a user to write JS once to interact with local data on any supported platform.

_Copied from original issue: NativeScript/cross-platform-modules#141_

**Comment by enchev** [comment]
_From @MiroValchev on April 6, 2015 16:24_

I'd love to see this too. We use it in one of our apps and would need it if we are to redo it in NativeScript

**Comment by Nathanaela** [comment]
Just a fyi; I just pushed "nativescript-sqlite" -- it only has the Android side done currently and it is a early alpha.   But it is available for playing with.  My repo is github.com/nathanaela/nativescript-sqlite

**Comment by valentinstoychev** [comment]
Hey @NathanaelA  - any news on the iOS version?

**Comment by NathanaelA** [comment]
@valentinstoychev - My sqlite plugin has supported both ios & android for a really, really long time.  ;-)
Guess I missed this issue; to post the status.  But yeah, you can use it fine on ios & android right now.

**Comment by valentinstoychev** [comment]
Thanks @NathanaelA.
