### ISSUE TITLE
Add transform origin for animations.

### ISSUE THREAD

**Issue by hamorphis** [NativeScript/NativeScript#730]

**Comment by roblav96** [comment]
@hamorphis is this still not possible?

**Comment by hamorphis** [comment]
The View class now has originX and originY properties: https://docs.nativescript.org/api-reference/classes/_ui_core_view_.view.html#originx

**Comment by 404Assassin** [comment]
Works perfect. 

This should be added to the CSS documentation. This was the only place I could find any reference to transform origin.

**Comment by hamorphis** [comment]
@404Assassin I no longer work for NativeScript.
