### ISSUE TITLE
8 Enum values in objc!UIKit.d.ts are way too large

### ISSUE THREAD

**Issue by bguijt** [NativeScript/NativeScript#7300]
Please check this diff: https://github.com/NativeScript/NativeScript/commit/f54f71bc60df8ba0772fe82f2fc911c2c3494e9d#diff-a4508a7cbf4cc46900ecccb75a31c03d

and find all value changes from 4294967295 (which is 0xFFFFFFFF) to 18446744073709551615 (which is 0xFFFFFFFFFFFFFFFF) which is an overflow to the JS numerical system and therefore incorrect.

This is probably OK for regular JS projects, however we use a commercial code obfuscator which is unable to handle these literals.

Please change these literals back to what they were ;-)

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/ios-runtime #1150](https://github.com/NativeScript/ios-runtime/issues/1150) via [**ZenHub**](https://www.zenhub.com/)
