### ISSUE TITLE
API naming convention (misnamed member in utils)

### ISSUE THREAD

**Issue by mudlabs** [NativeScript/NativeScript#7302]
**Environment**
n/a

**Describe the bug**
The method for accessing the _Android_ specific module in `tns-core-modules/utils/utils` does not follow _NativeScripts'_ naming convention for accessing platform specific code.

To uphold the convention `utils.ad` should be renamed `utils.android`

**Comment by NathanWalker** [comment]
Available via `Utils.android` now with 7+
https://github.com/NativeScript/NativeScript/blob/master/packages/core/index.ts#L149-L151
