### ISSUE TITLE
[iOS 13] App crashes with ReferenceError: Can't find variable: UIDocumentInteractionControllerDelegate

### ISSUE THREAD

**Issue by adrian-niculescu** [NativeScript/NativeScript#7306]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.4.0
 - Cross-platform modules: 5.4.1
 - Android Runtime: 5.4.0
 - iOS Runtime: 5.4.0
 - Plugin(s): -
- **Xcode: 11.0 beta (11M336w)**
- **iOS 13.0 beta**

**Describe the bug**
Any NativeScript application crashes on iOS 13.0 with:
`NativeScript encountered a fatal error: ReferenceError: Can't find variable: UIDocumentInteractionControllerDelegate`

**Cause**: Apple added the NS_CLASS_AVAILABLE_IOS(13_0) attribute on the protocol UIDocumentInteractionControllerDelegate
on iOS 12.2 (as seen with Xcode 10):
![iOS 12 2](https://user-images.githubusercontent.com/15037449/58890981-59e78c80-86f4-11e9-9a7d-dfdc87737f9e.png)

on iOS 13.0 (as seen with Xcode 11):
![iOS 13](https://user-images.githubusercontent.com/15037449/58891004-64a22180-86f4-11e9-83b0-76e9a9791322.png)

This seems to be a bug in iOS. As of now, the only mention I could find was here: https://forums.developer.apple.com/thread/117198

**Comment by adrian-niculescu** [comment]
UIDocumentInteractionControllerDelegate is used [here](https://github.com/NativeScript/NativeScript/blob/b436ecde3605b695a0ffa1757e38cc094e2fe311/tns-core-modules/utils/utils.ios.ts#L162) in tns-core-modules/utils for a openFile method.

**Comment by guiroco** [comment]
I´m having the same problem, it happens to me only on IOS, on ANDROID it works. Did you find any solution?

**Comment by guiroco** [comment]
I found the solution for my problem.

The problem was I was using *ListViewGridLayout* inside a *RadListView* which template was not surrounded by a  *GridLayout*. Basically I changed from:

```html
<RadListView (loaded)="coverPanel.setScrollList($event)" height="100%" width="100%" [items]="movies$ | async">
            <ng-template tkListItemTemplate let-movie="item" let-i="index" let-odd="odd" let-even="even">
                    <Image borderRadius="2" height="300" decodeHeight="300"  [src]="movie.poster" loadMode="async" stretch="aspectFill"></Image>
            </ng-template>
            <ListViewGridLayout tkListViewLayout scrollDirection="Vertical" itemHeight="300" ios:itemHeight="300" spanCount="2"></ListViewGridLayout>
        </RadListView>
```

to

```html
<RadListView (loaded)="coverPanel.setScrollList($event)" height="100%" width="100%" [items]="movies$ | async">
            <ng-template tkListItemTemplate let-movie="item" let-i="index" let-odd="odd" let-even="even">
                <GridLayout margin="7">
                    <Image borderRadius="2" height="300" decodeHeight="300"  [src]="movie.poster" loadMode="async" stretch="aspectFill"></Image>
                </GridLayout>
            </ng-template>
            <ListViewGridLayout tkListViewLayout scrollDirection="Vertical" itemHeight="300" ios:itemHeight="300" spanCount="2"></ListViewGridLayout>
        </RadListView>
```

**Comment by MarkDoggen** [comment]
For me, this was related to building with Xcode 11.0 Beta. Switching back to the current version of Xcode I could run on iOS 13 just fine.

**Comment by adrian-niculescu** [comment]
Tested this on iOS 13 beta 3. Apple fixed the header, so this issue doesn't reproduce anymore.

**Comment by ankushmittal87** [comment]
Any solution to this problem?

I am also facing the same error while "tns debug ios". 

Thank you in advance.

**Comment by adrian-niculescu** [comment]
> Any solution to this problem?
> 
> I am also facing the same error while "tns debug ios".
> 
> ios version 12.3.1
> native script version 5..1.1
> 
> Thank you in advance.

Use the latest Xcode 11 beta version.
