### ISSUE TITLE
Leading dash css-classes do not work with new bundler (eg. "--disabled")

### ISSUE THREAD

**Issue by SephReed** [NativeScript/NativeScript#7308]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.4.0 version and is up to date.
✔ Component tns-core-modules has 6.0.0-next-2019-05-16-141945-01 version and is up to date.
✔ Component tns-android has 5.4.0 version and is up to date.
✔ Component tns-ios has 6.0.0-2019-05-16-165318-01 version and is up to date.

**Describe the bug**

Using a css class with leading dashes (e.g. "--disabled") in the new bundler does not work.

**To Reproduce**

Add a leading dashes classname to a view, and attempt to target it with css.

**Expected behavior**
Should act as normal css classes

**Additional context**

I had put this issue in a while ago for the non-bundler route.  It appears to have been fixed there, but not for the new bundling one.

**Comment by NickIliev** [comment]
The issue is related to using SASS and is not reproducible when using plain CSS.

Updated demo app to reproduce the issue with SCSS files can be found [here](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/NativeScript/iisue-7089).

**Comment by vakrilov** [comment]
The issue seems to be fixed using `next` versions + bundle workflow.
Note: With bundle-workflow the scss will be build by the webpack build. Also the dependency to `nativescript-dev-sass` is removed)
