### ISSUE TITLE
Webpack workflow permanently breaks android sockets

### ISSUE THREAD

**Issue by SephReed** [NativeScript/NativeScript#7309]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.4.0 version and is up to date.
✔ Component tns-core-modules has 6.0.0-next-2019-05-16-141945-01 version and is up to date.
✔ Component tns-android has 5.4.0 version and is up to date.
✔ Component tns-ios has 6.0.0-2019-05-16-165318-01 version and is up to date.

**Describe the bug**

Using the non-legacy workflow leads to a silent failure for my android project which just hangs at the splash screen.  After trying the new workflow (and having it fail), I tried going back to the legacy workflow but kept getting a "Error is: Socket connection timed out".  I tried restarting the android emulator, but the error persisted.  The only way I could fix it was by either changing the project name, or creating a brand new emulator image.

**To Reproduce**

Not reproducible.  I don't even know what caused the silent failure, and can't imagine what's making it so permanent.

**Additional context**

I know this is an impossible bug to fix, I'm mostly just sharing it to say please, please, please keep legacy support going.  Webpack does not work at all for my projects in so, so, so, so, so, so many ways.  I'm nauseous about what's going to happen when I have to tell my boss that "Nativescript no longer works" after really putting my neck out to use this instead of react-native.  I want this to work, I know this is a much more logical approach than doing everything the react way all the time forever, but what am I supposed to do if you push an update that permanently breaks my app?

Sorry for the rant, but this whole "wepback" thing is putting me in an impossible place.

**Comment by NathanaelA** [comment]
For anyone running into weirdness like this; nuke the `platforms` folder and then rebuild and you should be good again.
