### ISSUE TITLE
NavigationEntry.bindingContext property

### ISSUE THREAD

**Issue by hamorphis** [NativeScript/NativeScript#731]
When you navigate to a page and provide a **bindingContext**, it would be nice this context to become the bindingContext of the page. In this way, you would not have to subscribe to each page's **navigatedTo** event simply to set its bindingContext. Instead you can do it like this:

```
    frameModule.topmost().navigate({
        moduleName: "details-page",
        bindingContext: new DetailsViewModel(id),
        animated: true,
        transition: {name: "slide"}
    });
```

**Comment by hamorphis** [comment]
Sample App: https://github.com/hamorphis/issue-731

**Comment by hamorphis** [comment]
We will introduce a new property on the NavigationEntry class called `bindingContext` which should be used for this purpose.

**Comment by webleaf** [comment]
Don't work with `application.run()` #6835
