### ISSUE TITLE
ShowModal Error

### ISSUE THREAD

**Issue by PirateWildWill** [NativeScript/NativeScript#7312]
Hi 

I have suddenly started receiving an error on all my showmodal calls. This started when I moved to the new workflow.

the error is:
JS: showModal(moduleName: string, context: any, closeCallback: Function, fullscreen?: boolean, animated?: boolean, stretched?: boolean) is deprecated. Use showModal(moduleName: string, modalOptions: ShowModalOptions) instead.

Has anyone got an example of the new showmodal call including how to return results?

√ Getting NativeScript components versions information...
√ Component nativescript has 5.4.0 version and is up to date.
√ Component tns-core-modules has 5.4.1 version and is up to date.
√ Component tns-android has 5.4.0 version and is up to date.

Dependencies:
┌─────────────────────────────────┬─────────┐
│ Plugin                          │ Version │
│ nativescript-screen-orientation │ ^2.0.0  │
│ nativescript-sqlite             │ ^2.3.3  │
│ nativescript-theme-core         │ ~1.0.4  │
│ nativescript-ui-gauge           │ ^4.0.0  │
│ nativescript-ui-sidedrawer      │ ^6.0.0  │
│ tns-core-modules                │ ^5.4.1  │
└─────────────────────────────────┴─────────┘
Dev Dependencies:
┌──────────────────────────┬─────────┐
│ Plugin                   │ Version │
│ nativescript-dev-webpack │ ~0.21.0 │
└──────────────────────────┴─────────┘

**Comment by PirateWildWill** [comment]
JS: showModal(moduleName: string, context: any, closeCallback: Function, fullscreen?: boolean, animated?: boolean, stretched?: boolean) is deprecated. Use showModal(moduleName: string, modalOptions: ShowModalOptions) instead.

System.err: com.tns.NativeScriptException: 

System.err: Calling js method onClick failed

System.err: 

System.err: Error: Cannot marshal JavaScript argument [object Object] at index 1 to Java type.

System.err: File: "file:///data/data/com.willhogarth.RunPacer/files/app/vendor.js, line: 9217, column: 20

System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/file-system/file-system-access.js.FileSystemAccess.joinPath', file:'file:///data/data/com.willhogarth.RunPacer/files/app/vendor.js', line: 9217, column: 21
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/file-system/file-system-access.js.FileSystemAccess.joinPaths', file:'file:///data/data/com.willhogarth.RunPacer/files/app/vendor.js', line: 9229, column: 27
System.err: 	Frame: function:'join', file:'file:///data/data/com.willhogarth.RunPacer/files/app/vendor.js', line: 9859, column: 27

System.err: 	Frame: function:'', file:'file:///data/data/com.willhogarth.RunPacer/files/app/vendor.js', line: 16765, column: 49

System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.getModalOptions', file:'file:///data/data/com.willhogarth.RunPacer/files/app/vendor.js', line: 20487, column: 45
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.showModal', file:'file:///data/data/com.willhogarth.RunPacer/files/app/vendor.js', line: 20492, column: 23
System.err: 	Frame: function:'onSetTimeTap', file:'file:///data/data/com.willhogarth.RunPacer/files/app/bundle.js', line: 1445, column: 18

System.err: 	Frame: function:'push.../node_modules/tns-core-modules/data/observable/observable.js.Observable.notify', file:'file:///data/data/com.willhogarth.RunPacer/files/app/vendor.js', line: 7747, column: 32

System.err: 	Frame: function:'push.../node_modules/tns-core-modules/data/observable/observable.js.Observable._emit', file:'file:///data/data/com.willhogarth.RunPacer/files/app/vendor.js', line: 7767, column: 18

System.err: 	Frame: function:'ClickListenerImpl.onClick', file:'file:///data/data/com.willhogarth.RunPacer/files/app/vendor.js', line: 17577, column: 23

System.err: 

System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)

System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)

System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)

System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1070)

System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1050)

System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1042)

System.err: 	at com.tns.gen.java.lang.Object_vendor_17570_32_ClickListenerImpl.onClick(Object_vendor_17570_32_ClickListenerImpl.java:18)

System.err: 	at android.view.View.performClick(View.java:6294)
System.err: 	at android.view.View$PerformClick.run(View.java:24770)
System.err: 	at android.os.Handler.handleCallback(Handler.java:790)

System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)

System.err: 	at android.os.Looper.loop(Looper.java:164)

System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6494)

System.err: 	at java.lang.reflect.Method.invoke(Native Method)

System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)

System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by PirateWildWill** [comment]
I have sorted the **"System.err: Error: Cannot marshal JavaScript argument [object Object] at index 1 to Java type."** error

Turns out I NOW have to make sure all my modal forms have **-page** as part of the file name

**Comment by NathanaelA** [comment]
@PirateWildWill - Yes, the webpack system basically requires all pages (modal and not modal) to have `-page` as part of the file name, so it knows what is actually part of the app.   You can update your webpack config to have different rules; but your config file will then probably get overwritten the next webpack update, so trying to keep it as stock as possible makes like typically simpler...


By the way; this is just a warning, not a error -- 
`JS: showModal(moduleName: string, context: any, closeCallback: Function, fullscreen?: boolean, animated?: boolean, stretched?: boolean) is deprecated. Use showModal(moduleName: string, modalOptions: ShowModalOptions) instead.`
At some point in the future this code will no longer work -- so they are letting you know that; but it currently still works and just throws a warning...

**Comment by tsonevn** [comment]
HI @PirateWildWill,
You can also review [application-architecture](https://docs.nativescript.org/core-concepts/application-architecture#application-modules) article, where this naming convention has been described. Regarding the showModal, I would suggest to migrate your code and to start using the new `ShowModalOptions ` option, that provides some [extra settings](https://docs.nativescript.org/api-reference/interfaces/_ui_core_view_base_.showmodaloptions) for the modal view.
I've just made a new PR, that updates our sample to the new `ShowModalOptions ` functionality. You can find it [here](https://github.com/NativeScript/nativescript-sdk-examples-js/pull/136/files).
