### ISSUE TITLE
[ios] "Unable to apply changes on device: ######. Error is: Unable to find free local port.."

### ISSUE THREAD

**Issue by paxperscientiam** [NativeScript/NativeScript#7316]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

> ✔ Getting NativeScript components versions information...
> ✔ Component nativescript has 5.4.0 version and is up to date.
> ✔ Component tns-core-modules has 5.4.1 version and is up to date.
> ⚠ Update available for component tns-android. Your current version is 5.3.1 and the latest available version is 5.4.0.
> ✔ Component tns-ios has 5.4.0 version and is up to date.

Just doing ios, so android thing shouldn't matter.

**Describe the bug**
When I do a `tns build ios --log trace` it builds successfully. However, when I run `tns debug ios`, I run into this error: "Unable to apply changes on device: ######. Error is: Unable to find free local port.."

Now, I think it may be related to `fork-ts-checker`, only because it remains running when there is a fault.

**To Reproduce**
* use bundle mode
* `tns debug ios` / `tns run ios` (i'm using simulator)
* change scss
* wait ... until webpack stops with aforementioned error "Unable to apply changes on device: ######. Error is: Unable to find free local port.."
* check background processes: there are two instances of `fork-ts-checker` running. But maybe this means nothing. IDK!

**Additional context**

I'll try to come up with minimal working example soon.

Other anonomolous errors:

> Module build failed (from ../node_modules/sass-loader/lib/loader.js):
> Error: ENOENT: no such file or directory, scandir '<PROJECT_ROOT>/node_modules/node-sass/vendor'

##EDIT##
OK, some progress. I've narrowed part of the problem down to `nativescript-dev-sass`. Seems to a negative interaction between its post install scripts and how `pnpm` works. I've opened an issue there too: https://github.com/pnpm/pnpm/issues/1865

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-cli #4684](https://github.com/NativeScript/nativescript-cli/issues/4684) via [**ZenHub**](https://www.zenhub.com/)
