### ISSUE TITLE
Closing an alert on the iPad crashesh the whole app.

### ISSUE THREAD

**Issue by hamorphis** [NativeScript/NativeScript#732]

**Comment by emiloberg** [comment]
I've seen this on a iPhone as well.

**Comment by enchev** [comment]
I've tried to reproduce it on various simulators and on iPad 2 device however everything worked as expected. If you can post some stack trace it will be helpful!

**Comment by emiloberg** [comment]
Sorry, can't reproduce :/ This was in a previous project and I solved it by not using the alert.
