### ISSUE TITLE
Android Platform Tools 29

### ISSUE THREAD

**Issue by cryptodude2000** [NativeScript/NativeScript#7328]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.4
 - Cross-platform modules:  Yes

**Describe the bug**
Upgraded to android studio 3.4, Platform Tools 29. 
TNS could not connect to Platform Tools 29 ADB
Both Emulator and Connected Device Fail.

**To Reproduce**
Replaced Platform Tools 29 with Platform Tools 28. Works. 
Replaced Platform Tools 28 with Platform Tools 29. Does Not Work. 

**Expected behavior**
TNS Should Eventually work with Platform Tools 29.

**Additional context**
None.

This is just to report my experience could cause several bug reports.

**Comment by NathanaelA** [comment]
I'm using Android Studio 3.4.1 w/ Platform tools 29...  Adb version --
```
Android Debug Bridge version 1.0.41
Version 29.0.0-5611747
```
I even manually re-installed the nativescript android platform and changed this:
![image](https://user-images.githubusercontent.com/850871/59100267-23c02d80-88eb-11e9-8cb3-12d3219e6269.png)

To version 29 just to make sure it was using the 29 tools and had no issues on Linux.

However a couple weeks back I ran into this issue: https://github.com/NativeScript/nativescript-cli/issues/4508
And so my machine by default has the additional environmental variables...  You might check to see if they fix it...
