### ISSUE TITLE
Add API to open a file at a given path with the default application.

### ISSUE THREAD

**Issue by hamorphis** [NativeScript/NativeScript#733]

**Comment by enchev** [comment]
In iOS this is [already available](https://github.com/NativeScript/NativeScript/pull/1479) however in Android is a bit more complicated since you should use external app.

**Comment by NathanaelA** [comment]
Just a tidbit, I'm pretty sure the "openURL" function will open an arbitrary file with the default app in Android.  The URL does NOT have to be a http/https; it can be a path to a file name...

**Comment by elmissouri16** [comment]
@NathanaelA  no it doesn't  work

**Comment by NickIliev** [comment]
@elmissouri16 you can use the solution suggested [here](https://github.com/NativeScript/NativeScript/issues/5661)

**Comment by elmissouri16** [comment]
```
 try {
                var intent = new android.content.Intent(android.content.Intent.ACTION_VIEW);
                intent.setDataAndType(android.net.Uri.fromFile(new java.io.File(file_path)), "audio/*");
                application.android.currentContext.startActivity(android.content.Intent.createChooser(intent, "Open File..."));
            } catch (e) {
               console.log(e);
            }
```

**@NickIliev I tried this is work  the only downside is needing to specify file format but i can work with thats on my application**

**Comment by elmissouri16** [comment]
I create this [package](https://www.npmjs.com/package/nativescript-openfile) for this purpose only support android

**Comment by DavidAvilesBios** [comment]
> I create this [package](https://www.npmjs.com/package/nativescript-openfile) for this purpose only support android


i dont know how to call new java.io.File , i cannot find the lib
