### ISSUE TITLE
pullToRefresh does  not trigger event pullToRefreshInitiated

### ISSUE THREAD

**Issue by alexisconsuegra** [NativeScript/NativeScript#7336]
Pull down does not trigger event pullToRefreshInitiated. The console log statement never runs. What am I missing? Thanks.

    exports.pullToRefreshInitiated = function () {
    console.log("**** Never Runs ****");
    setTimeout(function () {
        page.bindingContext = new MyViewModel();
        page.getViewById("items").notifyPullToRefreshFinished();
    }, 2000);
};

    <ListView id="items" items="{{ items }}" itemTap="onItemTap" class="list-group" pullToRefresh="true" pullToRefreshInitiated="pullToRefreshInitiated">
    <ListView.itemTemplate>
      <GridLayout class="listGroupItem" rows="70, 300" columns="*, auto">
        <StackLayout row="0" col="0">
          <Label text="{{ title }}" class="list-item-header" />
        </StackLayout>
        <StackLayout row="0" col="1" visibility="{{ processing ? 'collapsed' : 'visible' }}">
          <Label text="{{ views }}" horizontalAlignment="right"/>
          <Label text="views" />
        </StackLayout>
        <StackLayout row="1" col="0" colSpan="2" visibility="{{ processing ? 'collapsed' : 'visible' }}">
          <Label text="{{ type }}" textWrap="true" />
        </StackLayout>
        <ActivityIndicator rowSpan="3" color="blue" busy="{{ processing }}" visibility="{{ processing ? 'visible' : 'collapsed' }}"></ActivityIndicator>
      </GridLayout>
    </ListView.itemTemplate>
  </ListView>

**Comment by tsonevn** [comment]
Hi @alexisconsuegra,
The ListView provided by tns-core-modules does not have similar functionality such as `pullToRefresh`. In your case, you need to use `RadListView` component, which comes with [nativescript-ui-listview plugin](https://www.npmjs.com/package/nativescript-ui-listview).

**Comment by alexisconsuegra** [comment]
Thanks.
