### ISSUE TITLE
tns device command fails to find hardware devices (Android Studio works fine)

### ISSUE THREAD

**Issue by planetchili** [NativeScript/NativeScript#7339]
**Environment**
Component nativescript has 5.4.0 version and is up to date.
Component tns-core-modules has 5.4.2 version and is up to date.
Component tns-android has 5.4.0 version and is up to date.
Component tns-ios has 5.4.1 version and is up to date.
Windows 7 SP1 x64

**Describe the bug**
`tns device android` responds with "cannot find connected devices" with my Galaxy S5 connected. `adb devices` lists the device, and I am able run apps on this hardware from android studio, so I am certain that all the necessary setup is complete (app debugging enabled, usb driver installed etc.)

`tns run android` also fails with "Cannot find connected devices. Emulator start failed with: Command failed: C:\Android\android-sdk\platform-tools\adb -s 8ae6d329 shell getprop ro.product.manufacturer". This is interesting because the device name listed in `adb devices` is "8ae6d329", so although `tns device` is saying there are no devices, `tns run android` seems to be trying to do something with my device regardless.

**Expected behavior**
`tns device android` should list my hardware device and `tns run android` should execute the app on my device.

**Comment by planetchili** [comment]
One thing I'd like to add to the above:
If I start an emulator from Android Studio > Tools > AVD Manager, I am able to see it via `tns device android` and `tns run android` works as expected. However, if I attach my hardware device at the same time, `tns device android` fails to find any devices, and `tns run android` fails to work. `adb devices` shows both the emulated and hardware devices at the same time, and Android Studio works equally well with both attached at the same time.

**Comment by tsonevn** [comment]
This issue seems to be duplicated of https://github.com/NativeScript/nativescript-cli/issues/4688
