### ISSUE TITLE
absolute rowHeight in GridLayout doesn't work on Android

### ISSUE THREAD

**Issue by boriswinner** [NativeScript/NativeScript#7341]
**Environment**
nativescript 5.4.0.
tns-core-modules 5.4.2.
tns-android 5.4.0.

**Describe the bug**
Real row height in pixels is muuuch bigger than set.

**Expected behavior**
row height has to be 60px. At real (1920x1080 res, Android) it is ~160-170px.

**Sample project**
```
          <ScrollView v-if="!isCreatingNewNote && calendarMode === 1" orientation="vertical" class="home__week-wrapper"> 
            <StackLayout>     
              <GridLayout backgroundColor="white" columns="*, *, *, *, *, *, *, *" rows="60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60">
              <Label v-for = "(item, index) in [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]" :key="index" :text="item" :row="index" col="0" backgroundColor="#ffd0c7"/>
              <Label v-for= "(item, index) in selectedWeekNotes" class="home__weekview_cell" :key="'event'+index" :col="item.column+1" :row="item.row" :text="item.title" backgroundColor="#dbc7ff" :style="{'margin-top': item.marginTop+'px'}"/>                    
              </GridLayout>
            </StackLayout>
          </ScrollView>
```

![Screenshot_2019-06-11-10-55-59-808_org boriswinner teendok](https://user-images.githubusercontent.com/22561712/59236944-9a3a9380-8c3b-11e9-9b37-5d603d0c3b27.png)

**Comment by boriswinner** [comment]
Also, without ScrollView situation is the same

**Comment by edusperoni** [comment]
60 in Nativescript isn't in px but dip (device independent pixels). That means 60 will be the same size on all screen densities. https://github.com/NativeScript/NativeScript/issues/2411#issuecomment-230261240

If you want to use a specific pixel size you could calculate it using `screen.mainScreen.scale`

**Comment by tsonevn** [comment]
HI @boriswinner,
@edusperoni is right, in NativeScript device independent pixels are used. The linked issue 2411 above and the provided example in it should help you in solving your case.
