### ISSUE TITLE
Neither PhpStrom or WebStorm will analise webpack.config.js

### ISSUE THREAD

**Issue by Cclown98** [NativeScript/NativeScript#7342]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.4.0
 - Cross-platform modules:5.4.0
 - Android Runtime:5.4.0
 - iOS Runtime:5.4.1
 - Plugin(s): NONE

![Captura de Pantalla 2019-06-11 a la(s) 10 57 17 a  m](https://user-images.githubusercontent.com/20803123/59288112-9e18e680-8c38-11e9-8011-ffd0523e8b8f.png)

**Describe the bug**

None of these IDEs is able to analise the webpack.config.js file content which makes harder using Alias and another configs which help developers to have a better autocompletions and error prevention, this bug causes "false positives" since the IDEs will show error that are really in there

**To Reproduce**

Just initialise a new project using any CLI (Vue, Angular, TNS) or Sidekick and open the project using WebStorm or PhpStorm. 

**Sample project**

[TuCargaTransportador.zip](https://github.com/NativeScript/NativeScript/files/3277466/TuCargaTransportador.zip)

**Additional context**

- OS X 10.14

**Comment by tsonevn** [comment]
HI @Cclown98,
Check out [this thread](https://github.com/NativeScript/NativeScript/issues/6459#issuecomment-433342266), where the same case has been discussed.
