### ISSUE TITLE
border-top TabView Wrong Position

### ISSUE THREAD

**Issue by ios-blackswan** [NativeScript/NativeScript#7345]
**Environment**

✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.4.0 version and is up to date.
✔ Component tns-core-modules has 5.4.2 version and is up to date.
✔ Component tns-android has 5.4.0 version and is up to date.
✔ Component tns-ios has 5.4.1 version and is up to date.

iOS SDK: 10.1 / iOS 12.1

**Describe the bug**

When using border-top on TabView the border is showing at the top of the screen above the ActionBar.

![](https://i.imgur.com/0BF19Mt.png)

**Expected behavior**

Top Border should be on top of TabView not at the top of the screen.

**Sample project**

Can be reproduced with this playground: 
https://play.nativescript.org/?template=play-ng&id=Zkmd8V&v=2

**Comment by tsonevn** [comment]
Hi @ios-blackswan,
I tested your case on my side, however, was unable to recreate the issue. For your convenience, I am attaching a screenshot. Can you try restarting the Preview app and build it again? 
![Screenshot 2019-06-12 at 16 36 05](https://user-images.githubusercontent.com/17448734/59355730-380f8a80-8d30-11e9-946a-009ec886419d.png)

Let me know if I am missing something.

**Comment by ios-blackswan** [comment]
@tsonevn I am wanting the border here (on top of TabView) not near ActionBar. 

See the green line below.

![](https://i.imgur.com/6Ld1vwi.png)

**Comment by vahidvdn** [comment]
@ios-blackswan 

> Expected behavior
Top Border should be on top of TabView not at the top of the screen.

As I know, you don't have access to tabview's bar element as you want. The new TabView re-design is on the way. See the tracking on #6967

**Comment by tsonevn** [comment]
HI @ios-blackswan,
@vahidvdn  is right, at this time, you can not set up TabVies's bar via the CSS. Currently, if you need to apply border just above the bar line, you can try setting bottom border for each of the TabView's containers. For example:
```
TabView StackLayout{
     border-bottom-width: 100;
    border-bottom-color: green;
}
```
You can also check the example [here](https://play.nativescript.org/?template=play-ng&id=Zkmd8V&v=2).
