### ISSUE TITLE
HTTP load failed using https on iOS

### ISSUE THREAD

**Issue by alexisconsuegra** [NativeScript/NativeScript#7351]
**Environment**
 - CLI: 5.3.2
 - Cross-platform modules:
 - Android Runtime: 5.2.1
 - iOS Runtime: 5.2.0
 - Plugin(s):
    "nativescript-background-http": "^3.4.0",
    "nativescript-camera": "^4.4.0",
    "nativescript-drop-down": "^5.0.0",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-google-maps-sdk": "^2.7.0",
    "nativescript-imagepicker": "^6.1.2",
    "nativescript-masked-text-field": "^4.0.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-listview": "^6.3.2",
    "tns-core-modules": "~5.2.0"

**Describe the bug**
Error: HTTP load failed (error code: -1200 [3:-9802])
Task <F203CE04-0BD1-4AB7-8F11-4BB96B9E4E26>.<1> HTTP load failed (error code: -1200 [3:-9802])
Task <F203CE04-0BD1-4AB7-8F11-4BB96B9E4E26>.<1> finished with error - code: -1200

background:
It was working fine until I installed "nativescript-ui-listview": "^6.3.2" that a new build was created. I started getting the error on all new builds. Here is the call using HTTPS protocol 
    module.fetch("https://xisapi.com/api/controllername/actionname?param=a&param2=b");

Note: I make the same request with ARC and get a OK (200) response back.
I also noticed the build in using Deployment Target 9.0 by default. 
What could it be? Any thing missing in the plist file?

Here is error log: (Thanks in advance)

Task <DAE8C18F-91A3-4DC2-B8E6-624425D59C77>.<2> resuming, QOS(0x21)
Task <DAE8C18F-91A3-4DC2-B8E6-624425D59C77>.<2> {strength 1, tls 8, ct 0, sub 0, sig 0, ciphers 1, bundle 0, builtin 0}
TIC Enabling TLS [2:0x28394f240]
TIC TCP Conn Start [2:0x28394f240]
[C2 Hostname#9ab4a4fb:443 tcp, url hash: 1232ae70, tls] start
nw_connection_report_state_with_handler_locked [C2] reporting state preparing
Task <DAE8C18F-91A3-4DC2-B8E6-624425D59C77>.<2> setting up Connection 2
nw_endpoint_flow_protocol_connected [C2.1 IPv4#bf8a3b2a:443 in_progress channel-flow (satisfied)] Transport protocol connected
TIC TLS Event [2:0x28394f240]: 1, Pending(0)
TIC TLS Event [2:0x28394f240]: 11, Pending(0)
TIC TLS Event [2:0x28394f240]: 14, Pending(0)
Trust evaluate failure: [leaf AnchorTrusted SSLHostname]
System Trust Evaluation yielded status(-9802)
ATS failed system trust
System Trust failed for [2:0x28394f240]
TIC TLS Trust Result [2:0x28394f240]: 4
TIC SSL Trust Error [2:0x28394f240]: 3:0
TIC TCP Conn Cancel [2:0x28394f240]
[C2 Hostname#9ab4a4fb:443 tcp, url hash: 1232ae70, tls] cancel
[C2 Hostname#9ab4a4fb:443 tcp, url hash: 1232ae70, tls] cancelled
0.000s [C2 <private> Hostname#9ab4a4fb:443 resolver] path:start
0.000s [C2 <private> Hostname#9ab4a4fb:443 resolver] path:satisfied
0.000s [C2 <private> Hostname#9ab4a4fb:443 resolver] resolver:start_dns
0.002s [C2 <private> Hostname#9ab4a4fb:443 resolver] resolver:receive_dns
0.002s [C2.1 <private> 192.168.155.79:54099<->IPv4#bf8a3b2a:443 channel-flow] path:start
0.003s [C2.1 <private> 192.168.155.79:54099<->IPv4#bf8a3b2a:443 channel-flow] path:satisfied
0.003s [C2.1 <private> 192.168.155.79:54099<->IPv4#bf8a3b2a:443 channel-flow] flow:start_nexus
0.004s [C2.1 <private> 192.168.155.79:54099<->IPv4#bf8a3b2a:443 channel-flow] flow:receive_nexus
0.004s [C2.1 <private> 192.168.155.79:54099<->IPv4#bf8a3b2a:443 channel-flow] flow:start_connect
0.048s [C2.1 <private> 192.168.155.79:54099<->IPv4#bf8a3b2a:443 channel-flow] flow:finish_transport
0.048s [C2 <private> Hostname#9ab4a4fb:443 resolver] flow:finish_transport
0.099s [C2] path:cancel
nw_protocol_tcp_log_summary [C2.1:3]
[<private> <private>:54099<-><private>:443]
Init: 1, Conn_Time: 43.241ms, Syn's: 1, WR_T: 0/0, RD_T: 0/0, TFO: 0/0/0, ECN: 0/1/1, TS: 1
RTT_Cache: process, rtt_upd: 2, rtt: 41.062ms, rtt_var: 5.125ms rtt_nc: 42.875ms, rtt_var_nc: 16.375ms
nw_endpoint_flow_protocol_disconnected [C2.1 IPv4#bf8a3b2a:443 cancelled channel-flow (null)] Output protocol disconnected
nw_connection_report_state_with_handler_locked [C2] reporting state cancelled
TIC TCP Conn Destroyed [2:0x28394f240]
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
Task <DAE8C18F-91A3-4DC2-B8E6-624425D59C77>.<2> HTTP load failed (error code: -1200 [3:-9802])
Task <DAE8C18F-91A3-4DC2-B8E6-624425D59C77>.<2> finished with error - code: -1200

**Expected behavior**
 HTTP 200 responce

**Sample project**

**Additional context**

**Comment by tsonevn** [comment]
Hi @alexisconsuegra,
I checked the described scenario on my side, however, in my opinion, the issue in your project is not related to the nativescript-ui-listview plugin. In my test app, where a simple fetch request is made with the provided link, the following error was printed:
```
Error:
CONSOLE LOG file:///app/bundle.js:204:20: TypeError: Network request failed: An SSL error has occurred and a secure connection to the server cannot be made.
```
I also tried to enable the HTTP requests for `xisapi.com`, but it seems that those request's type is not allowed by the server. In this scenario, the error in the console was:
```
Error:
CONSOLE LOG file:///app/bundle.js:204:20: TypeError: Network request failed: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “xisapi.com” which could put your confidential information at risk.
```
On that matter, the problem in the project seems to be caused by a problem with the server's certificate. For your convenience, I am also attaching my sample app.
  
[Archive.zip](https://github.com/NativeScript/NativeScript/files/3289227/Archive.zip)
