### ISSUE TITLE
[Consultation] possibility of limiting which components 

### ISSUE THREAD

**Issue by Ncatalogna** [NativeScript/NativeScript#7355]
**Environment**

 - CLI: 5.4.0
 - Cross-platform modules: 5.2.2
 - Android Runtime: 5.4.0
 - Project in NativeScript & Angular

**Context**

I have a component created to be used as a head in Angular, but it has no use in Nativescript.

When I run Angular, it works fine. But when I run Nativescript it ends up detecting that this component is part of the project, although in 'app.module.tns.ts' it is not found declared.

*Folder structure*

* App
	* home ==> NativeScript & Angular
	* shared
	  * header ==> Angular
	  * footer	==> Angular
	  * Login	==> NativeScript & Angular

*NativeScript & Angular - components for both platforms*
*Angular - component intended only for angular*

**Consultation**

Could Nativescript be taking all the components within a project as its own?

There is no possibility to limit which components are Angular and which are Nativescript.

**Comment by NickIliev** [comment]
@Ncatalogna are you sure that the component is used only within the web HTML files (and not in the ones that are named `*.tns.html`)
