### ISSUE TITLE
How to use Jquery for making API calls using application?

### ISSUE THREAD

**Issue by nitishsainani** [NativeScript/NativeScript#7357]
I am new to Nativescript, I want to make API calls what will be the easiest way to implement it?

**Comment by edusperoni** [comment]
You should use the native http library for requests: https://docs.nativescript.org/ns-framework-modules/http

**Comment by nitishsainani** [comment]
@edusperoni 
I have somethings implemented on JQuery,
someone mentioned on some issue that he is using JQuery in nativescript for api calls.
Can I use it?

**Comment by nitishsainani** [comment]
@edusperoni 
I am using JavaScript for my nativescript project.
I installed the nativescript-api plugin 
but when I build or preview: 
`Error: Module not found.`

Am I missing something on plugin?, I just installed and used:
`const { ApiClient } = require("nativescript-apiclient")`

**Comment by tsonevn** [comment]
HI @nitishsainani,
If you are facing an issue with the plugin, I would suggest contacting the plugin's author by opening a [new issue](https://github.com/mkloubert/nativescript-apiclient/issues) in its repository.
