### ISSUE TITLE
Remove element from DOM based on condition

### ISSUE THREAD

**Issue by surdu** [NativeScript/NativeScript#7358]
**Is your feature request related to a problem? Please describe.**
I would like a way that remove and element from the UI completely when a condition is met. The `visibility` attribute only hides the element. Basically, implement a `display: none` as opposed to `visibility: hidden`.

**Describe the solution you'd like**
Have an element (we used in a past project an element called `Render`) that has a `when` attribute and a `content` attribute. When the `when` condition is met, the contents of the `content` attribute will be added to the DOM, otherwise, the contents are removed.

For example:
```xml
<Render when="something===true">
  <Render.content>
    <Label text="Something is true" />
  </Render.content>
</Render>
```

**Describe alternatives you've considered**
`visibility` is the only solution to hide content conditionally in {N}, AFAK, but it is not removing the element from the DOM. 

**Additional context**
If this feature is desired as part of {N}, I could also implement it. I did it once before, just have to remember how :) (I don't have access to that project's code anymore)

**Comment by NathanaelA** [comment]
@surdu - As of NS 3 (I believe 3, might have been 4), it offers both `hidden` and `collapsed`.

`hidden` just hides it, but still takes up layout room, `collapsed` is like the `display: none` where the element does not take up any room in the dom...

**Comment by rahadur** [comment]
https://docs.nativescript.org/api-reference/modules/_ui_enums_.visibility

https://docs.nativescript.org/ui/styling#supported-css-properties

**Comment by surdu** [comment]
Somehow I missed that for so long 😮 

Thank you !
