### ISSUE TITLE
Short imports in the http-request library

### ISSUE THREAD

**Issue by msaelices** [NativeScript/NativeScript#7366]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.4.0
 - Cross-platform modules: 5.4.2
 - Android Runtime: 5.4.0
 - iOS Runtime: 5.4.2
 - Plugin(s):

**Describe the bug**
There are still some short imports in the http-request code, which may conflict with other libraries (i.e. `tns-core-modules/platform` with the NPM `platform` library)

**Expected behavior**
The NS code should follow its principles and not using short imports.

**Comment by NickIliev** [comment]
@msaelices can you post a link to the file that contains short imports?
