### ISSUE TITLE
Nativescript-ui-listview does not display images

### ISSUE THREAD

**Issue by alexisconsuegra** [NativeScript/NativeScript#7373]
I switched from native core list view to nativescript-ui-listview to use the pull to refresh feature and noticed the images from a url are not displayed initially. Only after multiple scrolling up and downs the images are shown. Tested on iPhone device. 
I was reading about the load on demand but I want the image to load initially (automatically).

Here is the app folder.
[app.zip](https://github.com/NativeScript/NativeScript/files/3303424/app.zip)

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-ui-feedback #1156](https://github.com/NativeScript/nativescript-ui-feedback/issues/1156) via [**ZenHub**](https://www.zenhub.com/)
