### ISSUE TITLE
Support requestAnimationFrame

### ISSUE THREAD

**Issue by edusperoni** [NativeScript/NativeScript#7374]
**Is your feature request related to a problem? Please describe.**
Currently, there isn't a way to call a function when a frame "ticks". This also makes using RxJS's `animationFrameScheduler` throw an error.

**Describe the solution you'd like**
Implement `requestAnimationFrame` and `cancelAnimationFrame`.

**Describe alternatives you've considered**
`setInterval(() => ..., 16);`

**Additional context**
I've already implemented it 😅 

https://play.nativescript.org/?template=play-ng&id=62Ge6S&v=3

I've tested on android, might need `zonedCallback`. Worked out of the box + using `animationFrameScheduler`.

I'd open a PR, but I'm not sure if this falls into `timer` or `fps-meter`, as I use `fps-meter/fps-native` and `timer` does not have a `common` implementation.

Edit: updated the demo for a case where a callback would be canceled by another callback and we'd end up with undefined in the for loop

**Comment by tsonevn** [comment]
Hi @edusperoni,
I reviewed the attached project, however, I am not sure that  I am understanding, where the issue is. On that matter, can you provide some more info about the problem and what you are trying to achieve as a final result?

Thank you in advance for your cooperation.

**Comment by edusperoni** [comment]
Hi @tsonevn, thanks for taking the time.

Say we're processing an event (like touch/drag) or manually animating some property. If we do processing every tick (setInterval with 0 or 1), we'd be wasting a lot of processing on properties that only change ever frame.

We could use setInterval 16 (60fps = 16-17ms per frame), but that could cause a weird issue where you animate twice in one frame or skip a frame.

That's why we use `requestAnimationFrame`, so the app will call the function on the next frame. RxJS has `animationFrameScheduler` so we can discard events that emit more than once a frame, for example.

My sample project didn't have any practical example for it, just the implementation and the output (it shows how long it took for the function to be called, 16 to 17ms each time, or more if there are frame skips)

Without the two functions I implemented, `animationFrameScheduler` will throw an error.

**Comment by edusperoni** [comment]
I've updated the example with a better comparison between a timeout and a animationframe:

at 60 fps, the animation frame will emit 59-60 events. setTimeout will emit around 120 events with a 0 delay and around 55-56 with a 16ms delay.

https://play.nativescript.org/?template=play-ng&id=62Ge6S&v=4

**Comment by alexziskind1** [comment]
Thanks for the awesome work on this @edusperoni . @tsonevn this is a great first step to be able to use some great javaScript animation libs out there. Any idea when this will be available?

**Comment by tsonevn** [comment]
HI @alexziskind1,
This issue is still under review and currently, I can not commit to the exact time, when this functionality will be available. On that matter, any PR, that provides support for this functionality will be highly appreciated.

**Comment by edusperoni** [comment]
@tsonevn I can write this PR right away. Just need someone from the team to answer this:

> I'd open a PR, but I'm not sure if this falls into `timer` or `fps-meter`, as I use `fps-meter/fps-native` and `timer` does not have a `common` implementation.

I'm importing `fps-meter/fps-native` and using the callbacks to implement it. Should I put it in the `timer` directory?

I could:
1- create a `timer-common.ts` and import on .android and .ios
2- create a `request-animation-frame.ts` and import .android and .ios

the implementation is pretty much done.

**Comment by tsonevn** [comment]
Hi @edusperoni,
I've discussed the case with the team and for now, the most appropriate place for adding this functionality seems to be `fps-meter` module. I would suggest making the PR. The dev team will review it and will comment it if some changes are required. 
Regarding the timer, there is no common file because there is no class(with some common functionality), which should be extended in the platform-specific files.

**Comment by sebj54** [comment]
@edusperoni Issue should be closed, I guess!

**Comment by edusperoni** [comment]
@sebj54 yes it should, thanks for reminding us!
