### ISSUE TITLE
204 rest api with content-type="application/json" throwing error

### ISSUE THREAD

**Issue by ppyoosuf** [NativeScript/NativeScript#7375]
**To Reproduce**

Try any 204 rest api with returning content-type="application/json".I am working with the loopback backend server.actually loopback returning the 204 rest api response with content-type="application/json". (https://github.com/strongloop/loopback/issues/621). so the response is going to the error block

**Expected behavior**
Should be call resolve method

**Comment by NickIliev** [comment]
@ppyoosuf can you share a REST API that can return status 204 with the "application/json" content type?

I've created [this playground](https://play.nativescript.org/?template=play-tsc&id=40hIXQ) for testing purposes but I am not able to find similar REST API.

**Comment by ppyoosuf** [comment]
Hi @NickIliev

thanks for your replay

I was worked with the native script-angular project. I could not reproduce it on your playground project. I think this issue only in nativescript-angular. so i have created a playground project (https://play.nativescript.org/?template=play-ng&id=mPM7oK&v=4) .please check it .I have created a mockable delete rest api (this will expiry after 24 hrs) .This api will return content-type as json.when i try your api i  found it returning text/html as content-type

**Comment by NickIliev** [comment]
@ppyoosuf confirming the issue and marking this one as a bug.

After some additional research, it seems that the issue might be related to [an issue with the Angular's HttpClient](https://github.com/angular/angular/issues/19413)

**Comment by lochstar** [comment]
I've encountered the same error. After some investigation I've determined it only happens on Android (Angular has nothing to do with it, I'm using Vue for my tests).

It is triggered if `'Content-Type': 'application/json'` OR `'Content-Encoding': 'gzip'` is set.
