### ISSUE TITLE
fix footer

### ISSUE THREAD

**Issue by nitishsainani** [NativeScript/NativeScript#7378]
I need to Implement a fix footer for custom advertisements (hardcoded) that is not refreshed by navigating through pages.

**Comment by NickIliev** [comment]
@nitishsainani please note that this repository is meant for logging issues, bugs and feature requests related to NativeScript framework and modules. For how-to related question please consider posting your questions in the community channels (e.g., like SO or the community slack channel).

The above said, there are different options to create "footer" - check the article and the example for nested navigation ([Angular ](https://docs.nativescript.org/angular/core-concepts/nested-navigation)or [Core NativeScript](https://docs.nativescript.org/core-concepts/nested-navigation)).

Or you could use Admob advertisements (nativescript-plugin-firebase) if you need to utilize Admob banners.
