### ISSUE TITLE
After add project and modulemap and do tns run ios, the project added is selected by default in Xcode

### ISSUE THREAD

**Issue by danicomas** [NativeScript/NativeScript#738]
See this comment: https://github.com/NativeScript/NativeScript/issues/711#issuecomment-140054149

P.S: It causes a problem because if I execute tns run ios the device doesn't load the app. I need to execute the command and then open Xcode and select the main project before run on the device.

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#917
