### ISSUE TITLE
Unable to apply changes on device: emulator-XXXX. Error is: Cannot read property 'env' of undefined

### ISSUE THREAD

**Issue by shineklbm** [NativeScript/NativeScript#7380]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.4.2
 - Cross-platform modules:5.4.2
 - Android Runtime:5.4.0
 - iOS Runtime:5.4.2
 - Plugin(s): "nativescript-ui-sidedrawer": "^4.3.0", "nativescript-plugin-firebase": "^7.7.0", "nativescript-downloader": "^2.1.4",

**Describe the bug**
After upgrading upgrading the project, when I run, `tns run android --bundle` or `tns run ios --bundle`, I am getting `Unable to apply changes on device: emulator-XXXX. Error is: Cannot read property 'env' of undefined.`

**To Reproduce**
`npm install -g nativescript`
`tns update`
`tns run android --bundle`
`tns run ios --bundle`

**Expected behavior**
It should run the app inside emulator.

**Comment by keithgulbro** [comment]
@shineklbm I had the same issue, here's an a vue reference I found https://github.com/vuejs/vue-cli/issues/4177 

If you're using Nativescript-Vue CLI like I am, it seems there's some major issues that arose over the last 24 hours.

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #4751](https://github.com/NativeScript/nativescript-cli/issues/4751) via [**ZenHub**](https://www.zenhub.com/)
