### ISSUE TITLE
node-sass not compiling after 5.4.2 upgrade

### ISSUE THREAD

**Issue by bradrice** [NativeScript/NativeScript#7392]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
```
{
  "description": "Tooling U Class Player",
  "license": "private",
  "readme": "NativeScript Application",
  "repository": "https://github.com/toolingudev/classappnativescript.git",
  "name": "class2tns",
  "version": "0.1.0",
  "scripts": {
    "test": "ng test"
  },
  "nativescript": {
    "id": "com.toolingu.class2tns",
    "tns-android": {
      "version": "5.4.0"
    },
    "tns-ios": {
      "version": "5.4.2"
    }
  },
  "dependencies": {
    "@angular/animations": "8.0.2",
    "@angular/common": "8.0.2",
    "@angular/compiler": "8.0.2",
    "@angular/core": "8.0.2",
    "@angular/forms": "8.0.2",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "8.0.2",
    "@angular/platform-browser-dynamic": "8.0.2",
    "@angular/router": "8.0.2",
    "async-await": "^0.1.40",
    "lodash": "4.17.11",
    "moment": "2.24.0",
    "nativescript-angular": "^8.0.0",
    "nativescript-audio": "5.0.1",
    "nativescript-drop-down": "^4.0.1",
    "nativescript-orientation": "2.2.1",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-ui-listview": "6.2.0",
    "nativescript-ui-sidedrawer": "6.0.0",
    "nativescript-videoplayer": "4.2.1",
    "nativescript-xmlobjects": "^1.1.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^6.3.3",
    "tns-core-modules": "^5.4.3",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.800.1",
    "@angular/cli": "^7.0.3",
    "@angular/compiler-cli": "~7.2.0",
    "@ngtools/webpack": "^6.2.7",
    "@types/lodash": "4.14.68",
    "@types/node": "~6.0.60",
    "css-loader": "^2.1.0",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.7.0",
    "nativescript-dev-typescript": "^0.10.0",
    "nativescript-dev-webpack": "^0.24.1",
    "node-sass": "^4.11.0",
    "sass-loader": "^7.1.0",
    "tns-platform-declarations": "^3.4.1",
    "ts-node": "~3.3.0",
    "tslint": "^5.8.0",
    "typescript": "^3.2.4",
    "uglifyjs-webpack-plugin": "^2.1.3",
    "webpack": "^4.29.5"
  },
  "author": "bradrice"
}
```

**Describe the bug**
After installing nativescript 5.4.2 I cannot compile scss to css files.
I use this command. the app compiles but not scss and is not livesynced

tns run ios --device 61560E27-9F8D-430F-81D9-437A2E329F52 --bundle

**To Reproduce**
run a bundle command

**Expected behavior**
tns run should compile and run the project and livesync scss to css files on a change to scss.

**Sample project**

**Additional context**
Everything was working until the most recent upgrade.

**Comment by NickIliev** [comment]
@bradrice tested with CLI 5.4.2 and[ this template project](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/NativeScript/issue-7392) and the SASS is working as expected (with bundle and HMR enabled by default).

- [here ](**url**)is the custom `scss` added after running `tns run ios` (note that the file is iOS specific so it will apply styles only on iOS).
- the change is applied to [the home page](https://github.com/NickIliev/NS-Issues-2019-I/blob/master/NativeScript/issue-7392/src/app/home/home.component.html#L8)

Try removing `node-sass` and `sass-loader` from your project - [here ](https://github.com/NickIliev/NS-Issues-2019-I/blob/master/NativeScript/issue-7392/package.json#L34-L41)is what at this very moment the template needs to work with sass (only 'nativescript-dev-sass')

**Comment by bradrice** [comment]
If I add or change my top level scss file, it does compile and work properly. However, if I have scss in a feature page in my angular app like this:

`@Component({
    selector: 'class-detail',
    moduleId: module.id,
    templateUrl: './classdetail.component.html',
    styleUrls: ['./classdetail.css']
})`

It is not compiling those files. It always worked prior to the 5.4.2 install. Do I have to reconfigure all my pages?

**Comment by edusperoni** [comment]
Change `styleUrls: ['./classdetail.css']` to `styleUrls: ['./classdetail.scss']

**Comment by bradrice** [comment]
That was it. Thanks for the help.
