### ISSUE TITLE
Anything after 5.1.0 crashes

### ISSUE THREAD

**Issue by ryanlangton** [NativeScript/NativeScript#7393]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime: 5.1.0
 - iOS Runtime: 5.1.0
 - Plugin(s):
    "nativescript-angular": "^8.0.0",
    "nativescript-camera": "4.5.0",
    "nativescript-geolocation": "5.1.0",
    "nativescript-google-maps-sdk": "2.7.0",
    "nativescript-google-places-autocomplete": "1.0.3",
    "nativescript-oauth2": "1.4.1",
    "nativescript-plugin-firebase": "9.0.1",
    "nativescript-theme-core": "1.0.4",
    "nativescript-urlhandler": "1.2.3",

**Describe the bug**
Everything works fine in my app if I'm on v5.1.0 of nativescript. If I upgrade to 5.4.0 (ios) and run the following commands the app crashes on the simulator and I get the following output.

CONSOLE INFO file:///app/vendor.js:88623:36: HMR: Hot Module Replacement Enabled. Waiting for signal.
CONSOLE LOG file:///app/bundle.js:136:20: Vegan beacon initialized!
CONSOLE LOG file:///app/vendor.js:59330:20: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
NativeScript caught signal 11.
Native Stack:
1   0x1033a21df sig_handler(int)
2   0x109e7db5d _sigtramp
3   0x30
4   0x109dc3b4d libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step()
5   0x109dc7e4c _Unwind_RaiseException
6   0x1099a14aa __cxa_throw
7   0x1083c2bfa _objc_exception_destructor(void*)
8   0x109565555 +[NSException raise:format:]
9   0x100dfc462 +[FIRApp configure]
10  0x103cbe51d ffi_call_unix64
11  0x12d62ee10
JS Stack:
1   configure@[native code]
2   @file:///app/vendor.js:91998:29
3   UIApplicationMain@[native code]
4   _start@file:///app/vendor.js:109688:26
5   run@file:///app/vendor.js:109720:11
6   bootstrapNativeScriptApp@file:///app/vendor.js:83343:26
7   bootstrapApp@file:///app/vendor.js:83244:38
8   bootstrapModule@file:///app/vendor.js:83228:26
9   @file:///app/bundle.js:1469:144
10  ./main.ts@file:///app/bundle.js:1474:34
11  __webpack_require__@file:///app/runtime.js:751:34
12  checkDeferredModules@file:///app/runtime.js:44:42
13  webpackJsonpCallback@file:///app/runtime.js:31:39
14  anonymous@file:///app/bundle.js:2:61
15  evaluate@[native code]
16  moduleEvaluation@:1:11
17  promiseReactionJob@:1:11
18  require@[native code]
19  anonymous@file:///app/starter.js:3:8
20  evaluate@[native code]
21  moduleEvaluation@:1:11
22  promiseReactionJob@:1:11

I upgrade by running the commands
tns platform remove ios
tns platform add ios
tns run ios --emulator

To downgrade to a working version I do the same but with
tns platform add ios@5.1.0

**Comment by tsonevn** [comment]
Hi @ryanlangton,
If I understand correctly, you are upgrading only iOS Runtime version in your project. If so, can you try upgrading your project, while following the [instructions here?](https://docs.nativescript.org/releases/upgrade-instructions)
If the above-given suggestion does not help or the case is different, please send us the project or sample one that will help us to recreate the problem locally.

**Comment by ryanlangton** [comment]
I have followed the instructions on that page for upgrading. The issue I'm having right now is that it's very unreliable, and a clean build takes 5+ minutes so changing anything takes awhile. Running through command line `tns run ios --emulator` always crashes with the exception shown above, every time. If I run through Nativescript sidekick it runs sometimes but I rarely get debug information because the chrome debugger loses connection quickly. I'm trying my best to narrow it down. It seems like it might be something to do with `nativescript-plugin-firebase`, I can remove references to that and things seem to work better. Just very difficult to gather more information or replicate.

**Comment by NickIliev** [comment]
@ryanlangton apart from debugging you can directly check the code that is causing the error in the line logged in your error log
```
CONSOLE LOG file:///app/vendor.js:59330:20:
```
The outputted `vendor.js` file is located in `platforms/android/app/src/vendor.js`

**Comment by ryanlangton** [comment]
Thanks for the info, but the console.log line is not causing the error, it's something after.

**Comment by ryanlangton** [comment]
I went through all the update process again and here is the code that's blowing up
```
firebase_common_1.firebase.addAppDelegateMethods = function (appDelegate) {
    if (typeof (FIRMessaging) !== "undefined" || useExternalPushProvider || typeof (FBSDKApplicationDelegate) !== "undefined") {
        appDelegate.prototype.applicationDidFinishLaunchingWithOptions = function (application, launchOptions) {
            if (launchOptions) {
                var remoteNotification = launchOptions.objectForKey(UIApplicationLaunchOptionsRemoteNotificationKey);
                if (remoteNotification) {
                    firebaseMessaging.handleRemoteNotification(application, remoteNotification);
                }
            }
            if (typeof (FBSDKApplicationDelegate) !== "undefined") {
                FBSDKApplicationDelegate.sharedInstance.applicationDidFinishLaunchingWithOptions(application, launchOptions);
            }
            return true;
        };
    }
```
```
JavaScript error:
file:///app/vendor.js:96014:97: JS ERROR TypeError: FBSDKApplicationDelegate.sharedInstance.applicationDidFinishLaunchingWithOptions is not a function. (In 'FBSDKApplicationDelegate.sharedInstance.applicationDidFinishLaunchingWithOptions(application, launchOptions)', 'FBSDKApplicationDelegate.sharedInstance.applicationDidFinishLaunchingWithOptions' is undefined)
NativeScript caught signal 11.
```
