### ISSUE TITLE
'tns create' hangs for half an hour and then fails

### ISSUE THREAD

**Issue by ezpzlmnsqzy1** [NativeScript/NativeScript#7416]
**Environment**
Result of `tns info`:
Component nativescript has 5.4.2 version and is up to date.

**Describe the bug**
 Running the command `tns create HelloWorld --template tns-template-blank` results in a hang with no output for roughly half an hour before failing with the message `request to https://registry.npmjs.org/tns-template-blank failed, reason: read ECONNRESET`

**Expected behavior**
A project is created

**Additional context**
I suspect this is related to me being behind a company proxy. However, I set my proxy info using `tns proxy set` with no change to the behavior. Setting the same proxy info in many other programs and tools works just fine, so I'm not entirely sure this is the cause of the issue here

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #4781](https://github.com/NativeScript/nativescript-cli/issues/4781) via [**ZenHub**](https://www.zenhub.com/)
