### ISSUE TITLE
error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by vivek-aecor** [NativeScript/NativeScript#7429]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:  NativeScript-Vue
 - Android Runtime: 5.4.2
 - iOS Runtime: 5.4.2
 
tns-info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.4.2 version and is up to date.
✔ Component tns-core-modules has 5.4.3 version and is up to date.
✔ Component tns-android has 5.4.0 version and is up to date.
✔ Component tns-ios has 5.4.2 version and is up to date.

![image](https://user-images.githubusercontent.com/50658820/60396027-04b76300-9b5a-11e9-9c63-8fcf5010a36b.png)

Which platform(s) does your issue occur on?
iOS

**Describe the bug**

**To Reproduce**

**Comment by tsonevn** [comment]
HI @vivek-aecor,
Make sure that you have set up correctly the [certificate](https://docs.nativescript.org/sidekick/user-guide/code-signing/code-signing-for-ios/create-development-certificate) and the [provisioning profile](https://docs.nativescript.org/sidekick/user-guide/code-signing/code-signing-for-ios/create-development-provisioning) while building the app for iOS device. Also, can you provide more info about the exact steps, that are used while building the app and the full error log from the console? On that matter, can you recreate the issue while building the app on a simulator?
