### ISSUE TITLE
Swipe back navigation overrides ActionBar styles (iOS)

### ISSUE THREAD

**Issue by mudlabs** [NativeScript/NativeScript#7430]
**Environment**
- NativeScript Playground
- iOS

**Describe the bug**
Navigating back on `iOS` via the default _swipe back navigation_ removes all `ActionBar` styles to the default `iOS` style.  And if the _swipe back navigation_ event is started but not completed the styles remain changed.

**To Reproduce / Sample project**
See [Playground](https://play.nativescript.org/?template=play-js&id=ZajS2B&v=2)

**Expected behavior**
`ActionBar` styles of the _navigating_ page are not overridden.

**Comment by mudlabs** [comment]
I believe this happens because the `iOS` ActionBar UI component is shared by both pages. 

Even though it's not being used by the first page, swiping back transitions the ActionBar styles to the default style _(since no style was specified)_.

I've updated the [Playground](https://play.nativescript.org/?template=play-js&id=ZajS2B&v=3) so you can test this behaviour. The `Home Page` now has an ActionBar _(hidden)_ with custom styles. Swiping back will change the ActionBar to these styles. So this is how you can overcome the first issue _(though its a hack and should not be needed)_. 

The second issue remains though. If you begin swiping back the ActionBar will take on the styles off the page you are navigating back to; the `navigatingFrom` event is also raised here.  If the swipe is canceled _(i.e you don't navigate from the page)_ the ActionBar does not return to the styles of the current page, as it was before swipe.

---

- Swipe back navigation triggers the `navigatingFrom` event.
- There should be a `swipeBackObserver` attached to the ActionBar, Page, or Frame in place to manage this behaviour.
- The minutiae of synchronising the ActionBar from _page-to-page_ is ___NOT___ something developers should have to manage. Beyond the use of `actionBarHidden` and `enableSwipeBackNavigation`.

**Comment by mudlabs** [comment]
Looks like we need to register [notifyWhenInteractionChanges](https://developer.apple.com/documentation/uikit/uiviewcontrollertransitioncoordinator/1829391-notifywheninteractionchanges) of [UIViewControllerTransitionCoordinator](https://developer.apple.com/documentation/uikit/uiviewcontrollertransitioncoordinator) inside the delegate of `NativeScript/tns-core-modules/ui/frame/frame.ios.ts`.

This would allow _{NS}_ to detect if the swipe event was cancelled and reset the ActionBar to the appropriate styles.

**Comment by NickIliev** [comment]
Reported via t.1448746 

Steps to reproduce:

1. Deploy this application
2. Navigate to item-details (red action-bar) and navigate back (the action bar has defaulted to blue )
