### ISSUE TITLE
Nativescript imagecropper not working inside a modal view

### ISSUE THREAD

**Issue by glober-trotter** [NativeScript/NativeScript#7432]
`nativescript-imagecropper` is not working inside a modal view on iOS, but when I try it on a page it is working as expected. Is there some workaround on this issue? I badly needed this feature with the app im working on. I can't also proceed because of this bug :(

here is a sample project. Btw, im using `nativescript-angular` and this issue occurs on iOS not in android.

[imageCropperIssue.zip](https://github.com/NativeScript/NativeScript/files/3344217/imageCropperIssue.zip)

**Comment by tsonevn** [comment]
Hi @glober-trotter,
This issue does not seem to be related to NativeScript core modules or nativescript-angular. On that matter, I would suggest contacting the author by opening a [new issue in the plugin's repository](https://github.com/bthurlow/nativescript-imagecropper/issues). It seems that the plugin does not take correctly the currently visible page when it is used a modal view without a frame. As a workaround, I would suggest setting up a modal view with page-router-outlet in your project as it is shown [here in the documentation](https://docs.nativescript.org/angular/ui/modal-view-ng#modal-view-actionbar). This should solve the issue.
