### ISSUE TITLE
All TabView tabs are loaded on app load

### ISSUE THREAD

**Issue by heyddi** [NativeScript/NativeScript#7438]
Hi there!

I am just starting with Nativescript and I really am impressed with all that work!

As part of a project to move a VueJS web app to mobile, I am trying to work with tabview and understand this. One element that I cannot seem to figure out is a behaviour that I have that seems to defer with the doc:

> The iOS implementation uses UITabBarController. This means that only one TabViewItem can be shown at a given time and only one needs to be loaded. When the user selects a new TabViewItem, we load the new item and unload the previous one.

My tabview looks like this:

```
<TabView selectedTabTextColor="#d94b3f"
     class="fas"
     fontSize="60"
     androidTabsPosition="bottom"
     androidOffscreenTabLimit="1">
    <TabViewItem title="T1" fontSize="60">
        <GridLayout columns="*" rows="*">
            <Comp1 />
        </GridLayout>
    </TabViewItem>
    <TabViewItem title="T2" fontSize="60">
        <GridLayout columns="*" rows="*">
            <Comp2 />
        </GridLayout>
    </TabViewItem>
    <TabViewItem title="T4" fontSize="60">
        <GridLayout columns="*" rows="*">
            <Comp3 />
        </GridLayout>
    </TabViewItem>
</TabView>
```

In each of the component `mounted()` I have added a console.log(‘tab_name’). When I load the app, each console.log are loaded. From what I get in the doc, I should be only mounted when navigating to the tab.
Am I missing something? For now, the only solution I have (which might not be that bad) is to add a v-if on tabs 2 and 3 content to generate only if selected index is matches the tab index.

Thanks a lot for your help!!

**Comment by NickIliev** [comment]
@heyddi you are talking about the Vue lifecycle while the documentation is talking about the native component that stands behind the NativeScript mobile implementation. nativescript-vue is an abstraction over NativeScript so its lifecycle events should and will work just as they would in pure vue project.
