### ISSUE TITLE
Cannot read property 'useHotModuleReload' of undefined

### ISSUE THREAD

**Issue by nartc** [NativeScript/NativeScript#7450]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**

**To Reproduce**

Brand new project using NativeScript CLI v6 (`npm install -g nativescript@rc`). Angular template and executing `tns run ios` produces this error

**Expected behavior**

**Sample project**

**Additional context**

**Comment by NickIliev** [comment]
@nartc if you want to test the release candidate for NativeScript 6 then install the `next` version of CLI
```
npm uninstall -g nativescript
npm i -g nativescript@next
```

And then run the migration command (migrates a project to 6.0.0)
```
tns migrate
```

NativeScript 6 comes with some breaking changes the `tc` might not be compatible with your current projects. This is the reason why migration is needed. Note that you should not use `rc` or `next` in production - stick to the latest official versions if you want a production build.

**Comment by nartc** [comment]
Thanks for the response. I overlooked the “migrate” command but the rc tag is from this official blog.

https://www.nativescript.org/blog/nativescript-6.0-release-candidate-is-here
