### ISSUE TITLE
Subclass UIApplication

### ISSUE THREAD

**Issue by Lelelo1** [NativeScript/NativeScript#7451]
Some of us would like to be able to subclass `UIApplication` so we can override the [`sendEvent`](https://developer.apple.com/documentation/uikit/uiapplication/1623043-sendevent?language=objc) method on ios. This is needed to detect user events that occur anywhere in the application like on the [keyboard](https://stackoverflow.com/questions/12361423/is-there-a-way-to-detect-a-touch-on-the-onscreen-keyboard) and without having to attach listeners [everywhere](https://discourse.nativescript.org/t/detect-user-inactivity-idle-subclass-uiapplication/7409) - to each and every one of the controls.

**Describe the solution you'd like**
Just like we can implement `UIApplicationDelegate`:

```
class MyDelegate extends UIResponder implements UIApplicationDelegate {
    public static ObjCProtocols = [UIApplicationDelegate];

    touchesBeganWithEvent(touches: NSSet<UITouch>, event: _UIEvent): void {
        console.log("touches began");
        // will not be invoken when touch is on keybaord or is on a control
    }
}
application.ios.delegate = MyDelegate;
```
...described [here](https://docs.nativescript.org/core-concepts/application-lifecycle?&_ga=2.112654156.919873201.1562060128-453634117.1561213572#ios-uiapplicationdelegate)

**It would be nice if we could:**

```
class MyApplication extends UIApplication {
    sendEvent(event: _UIEvent) {
        console.log("event was: " + event);
    }
}
application.ios.nativeApp = MyApplication; // <-- now throwing TypeError: Attempted to assign to readonly property.
```

before running app `application.run({ moduleName: "app-root"});`.

**Describe alternatives you've considered**
Add an additional property in application.ios that contains the `UIApplication` subclass to be used if given.

**Additional context**

From `application.ios.js` inside application module:
```
function _start(entry) {
    mainEntry = typeof entry === "string" ? { moduleName: entry } : entry;
    started = true;
    if (!iosApp.nativeApp) {
        UIApplicationMain(0, null, null, iosApp && iosApp.delegate ? NSStringFromClass(iosApp.delegate) : NSStringFromClass(Responder));
    }
```
The third argument should probably be `NSStringFromClass(iosApp.nativeApp)`, and the `if(!iosApp.nativeApp)` check has to redesigned.

![UIApplicationMain](https://user-images.githubusercontent.com/42244983/60585103-349b7c00-9d8f-11e9-8132-a21797048281.png)
where principalClassName should be the name of the `UIApplication` subclass if given.

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/ios-runtime #1170](https://github.com/NativeScript/ios-runtime/issues/1170) via [**ZenHub**](https://www.zenhub.com/)
