### ISSUE TITLE
"Could not migrate the project!" To NS6

### ISSUE THREAD

**Issue by jorugit** [NativeScript/NativeScript#7454]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
√ Component nativescript has 6.0.0-2019-07-02-133207-13547 version and is up to date.
√ Component tns-core-modules has 5.4.3 version and is up to date.
√ Component tns-android has 5.4.0 version and is up to date.
√ Component tns-ios has 5.4.2 version and is up to date.

**Describe the bug**
install the 6.0 RC with npm install -g nativescript@rc
and running "tns migrate": I got th following error:
Backup project configuration.
Backup project configuration complete.
Backup auto-generated files.
Backup auto-generated files complete.
Clean old project artefacts.
**Could not migrate the project!**

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #4800](https://github.com/NativeScript/nativescript-cli/issues/4800) via [**ZenHub**](https://www.zenhub.com/)
