### ISSUE TITLE
BottomNavigation and Tabs binding issues

### ISSUE THREAD

**Issue by ADjenkov** [NativeScript/NativeScript#7455]
[__BottomNavigation__] Using binding for`<TabStrip items>` creates empty TabStripBar (no tabs visible). Using ui-tests-app binding [examples](https://github.com/NativeScript/NativeScript/blob/release/e2e/ui-tests-app/app/bottom-navigation/binding-page.xml)

Developer Note1: We create TabStripItems, when iterating over tabStripContent items (`setViewControllers() method)` , while there is no tabStrip.items property set yet.

Developer Note2: BottomNavigation control should be somehow notified when its inner TabStrip.items has changed

_Question: missing `tabStripProperty` same as the adnroid bottomNavigation?_

[__Tabs__] Using binding for`<TabStrip items>` crashes the app with `file:///app/Users/djenkov/Work/NativeScriptTab/NativeScript/tns-core-modules/ui/tabs/tabs.ts:846:14 JS ERROR TypeError: undefined is not an object (evaluating 'items.forEach')` .Using ui-tests-app binding [examples](https://github.com/NativeScript/NativeScript/blob/release/e2e/ui-tests-app/app/tabs/tabs-binding-page.xml)

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
