### ISSUE TITLE
BottomNavigation and Tabs binding issues

### ISSUE THREAD

**Issue by ADjenkov** [NativeScript/NativeScript#7456]
- [ ] Resetting `bottomNavigation.items` or `bottomNavigation.tabStrip.items` to new Array does not update them. TabContentItem on the current selected tab index disappear and appear only if we switch tabs.

   _Developer Note1: BottomNavigation control should be somehow notified when its inner TabStrip.items has changed_ 

- [ ] Binding `<TabStripBar>.items` will only work with its parent `<BottomNavigation>`/`<Tabs>` binding context. Binding to some Page view model property won't work.

- [ ] _(optional feature)_ :  Introduce `tabStripItems` property to directly set TabStripBar items. 

Using ui-tests-app binding [bottom-navigation examples](https://github.com/NativeScript/NativeScript/blob/release/e2e/ui-tests-app/app/bottom-navigation/binding-page.xml) / [tabs examples](https://github.com/NativeScript/NativeScript/blob/release/e2e/ui-tests-app/app/tabs/tabs-binding-page.xml)

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
