### ISSUE TITLE
Global Objects don't seem to work in an Appetize.io emulator

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#746]
Here’s the app: https://appetize.io/app/z7ymyhj8te4jz32rw8wqd2mxdg

I basically added analytics per this post
https://www.nativescript.org/blog/adding-analytics-to-your-nativescript-app
the error messages I’m getting seem to indicate it can’t handle a global object set when the app starts (monitor.trackFeature is undefined)

Everything works great on the device itself...and I know NativeScript apps work fine in the emulator  (example: https://www.nativescript.org/blog/using-nativescript-animations-api).  There just seems to (maybe) be this global object issue.

Steve

**Comment by N3ll** [comment]
Hey @sitefinitysteve , maybe this could be a bug from Appetize.io side, since it is working fine on the device and in the emulator.

**Comment by sitefinitysteve** [comment]
Sorry I forgot to close this! :)

It all works after their last update, was on their end
