### ISSUE TITLE
Want to understand NS support for running iOS apps on MacOS

### ISSUE THREAD

**Issue by kamath-prasad** [NativeScript/NativeScript#7463]
As apple plans to build support for writing apps once and provide ability to run the generated app on both iOS and MacOS as part of [project catalyst](https://techcrunch.com/2019/06/03/ios-apps-will-run-on-macos-with-project-catalyst/ )  , I want to understand whether NativeScript also has similar plans to support this feature for iOS app's generated via NS. 

Based on some more [articles](https://appspector.com/blog/xcframeworks) we believe that Apple plans to support this via bundling the SDK's as XCFramework and I could see somewhat related work/commit's in some of branches in NS repo - https://github.com/NativeScript/NativeScript/compare/feat/uikit-for-mac .

It would be good if you can share any plan / timeline / documentation about the same.

**Comment by NickIliev** [comment]
@kamath-prasad the support for Catalyst is already considered and researched. You can track[ this issue ](https://github.com/NativeScript/ios-runtime/issues/1165)for more information on the matter.


Closing as duplicate to https://github.com/NativeScript/ios-runtime/issues/1165

**Comment by kamath-prasad** [comment]
Thanks @NickIliev !
