### ISSUE TITLE
Cannot access file since Webpack ?

### ISSUE THREAD

**Issue by MopheusDG** [NativeScript/NativeScript#7464]
Hi, I've started having a problem lately while trying to access a file that used to worked perfectly fine before and now for some reason, the file.size is comming in 0 as it's not able to see it. I'm not sure when it started as I made several changes but I'd think that started at same point between this 2 steps:

1) Updated to Nativescript 5.4.2 (Latests)
2) Added Webpack.

Below is the lines for my file import and the rest, it's quite simple, and I'd like to know if there's something else I should modify on the Webpack settings to be sure it's included, as you can see, that path below is not standard of any project.

`
var fs = require("tns-core-modules/file-system");
const initialFile = fs.knownFolders.currentApp().getFile('../shared/ibases/ini_agenda.json');
console.log(initialFile.size);
`

I tried remove platform, clean builds, almost all the typical steps but no luck. Any ideas ? I'm not sure how to provide more info so if someone have any ideas, all are welcome.

Thanks a lot.

**Comment by NathanaelA** [comment]
@MopheusDG - Using NS 5.4 and above; 

- You either just need to `require` the file like so:
`const initialFile = require('/shared/ibases/ini_agenda.json').toString();`   (Assuming /shared/ is the top level directory in the /app/ folder.   You need to pretend the "/" = "/app/" and then do the full path from App to where the file exists...

or

- change the webpack config file and add the `**/*json` to the copy resources section of the webpack config...

**Comment by NickIliev** [comment]
As @NathanaelA suggested, you need to add the JSON file to your webpack.config.json 
```
new CopyWebpackPlugin([
    { from: { glob: "<path-to-your-file.json>" } },

    // more code follows here ...
```

**Comment by MopheusDG** [comment]
Thanks both for your help, keep fighting with this, I added the following (Just to be sure all methods) in my webpack.config:

`            new CopyWebpackPlugin([
                { from: { glob: "fonts/**" } },
                { from: { glob: "**/*.jpg" } },
                { from: { glob: "**/*.png" } },
                { from: { glob: "**/*.json" } },
                { from: { glob: "**/*json" } },
                { from: { glob: "../shared/ibases/ini_agenda.json" } },
            ], { ignore: [`${relative(appPath, appResourcesFullPath)}/**`] }),
`

but my getfile is still failing, so my question is, after including this files in the webpack, should I search for my file on the original path ? Or on resources ?

`const initialFile = fs.knownFolders.currentApp().getFile('../shared/ibases/ini_agenda.json');`

Sorry, still trying to get confortable with my preparations for NS 6 so excuse my very poor skilll.

**Comment by MopheusDG** [comment]
Just as additional information, I can see while running the TNS RUN ANDROID --BUNDLE that the file is included:

`shared/ibases/ini_agenda.json   1.88 KiB           [emitted]`

But after the getFile I still see the file size in 0 for some reason.

`const initialFile = fs.knownFolders.currentApp().getFile('../shared/ibases/ini_agenda.json');`
`console.log(initialFile.size);`

**Comment by MopheusDG** [comment]
Never mind me... fixed with:

`const initialFile = fs.knownFolders.currentApp().getFile('shared/ibases/ini_agenda.json');`

Amateur mistake :)

Thanks both for the support.
