### ISSUE TITLE
[BottomNavigation] Icons in tab-strips items cannot be changed dynamically

### ISSUE THREAD

**Issue by SvetoslavTsenov** [NativeScript/NativeScript#7470]
Tested with **tns-core-modules modules@6.0.0-rc-2019-07-04-184211-04**  

Trying to change icon source on tab strip when changing the selected tab strip item is not working and cannot be changed.

Please take a look into this [bottom-navigation/icon-change-page.ts](https://github.com/NativeScript/NativeScript/blob/release/e2e/ui-tests-app/app/bottom-navigation/icon-change-page.ts) sample

**Comment by lhovee** [comment]
I have a use case where attempting to swap an active icon when tab strip item is selected that doesn't work. Hoping we can re-open this ticket.

**Comment by lhovee** [comment]
code is:

```
<template>
  <Page>
    <BottomNavigation
      :selectedIndex="activeIndex"
      @selectedIndexChanged="activeIndexChange"
    >
      <TabStrip>
        <TabStripItem
          v-for="(item, index) in tabStripItems"
          :key="item.key"
        >
          <Label :text="item.text" />
          <Image :src="index === activeIndex ? item.activeIcon : item.icon" />
        </TabStripItem>
      </TabStrip>

      <TabContentItem
        v-for="(itm, idx) in tabStripItems"
        :key="idx"
      >
        <component
          :is="itm.component"
          :key="`${itm.key}-${idx}`"
          :title="itm.text"
        />
      </TabContentItem>
    </BottomNavigation>
  </Page>
</template>

<script lang="ts">
import { Component } from 'vue-property-decorator';
import Vue from 'nativescript-vue';
import { SelectedIndexChangedEventData } from 'tns-core-modules/ui/bottom-navigation';
import PlaceholderComponent from '@/components/PlaceholderComponent.vue';

@Component({
  components: {
    PlaceholderComponent,
  },
})
export default class HomeRoot extends Vue {
  public activeIndex: number = 2;
  private tabStripItems = [
    {
      text: 'Account',
      key: 'account',
      icon: 'res://app/icon_account',
      activeIcon: 'res://app/icon_account_active',
      component: PlaceholderComponent,
    },
    {
      text: 'Rules',
      key: 'rules',
      icon: 'res://app/icon_rules',
      activeIcon: 'res://app/icon_rules_active',
      component: PlaceholderComponent,
    },
    {
      text: 'Home',
      key: 'home',
      icon: 'res://app/icon_home',
      activeIcon: 'res://app/icon_home_active',
      component: PlaceholderComponent,
    },
    {
      text: 'Activity',
      key: 'activity',
      icon: 'res://app/icon_activity',
      activeIcon: 'res://app/icon_activity_active',
      component: PlaceholderComponent,
    },
    {
      text: 'Devices',
      key: 'devices',
      icon: 'res://app/icon_devices',
      activeIcon: 'res://app/icon_devices_active',
      component: PlaceholderComponent,
    },
  ];

  public activeIndexChange(update: SelectedIndexChangedEventData): void {
    this.activeIndex = update.newIndex;
  }
}
</script>

<style lang="scss" scoped>
TabStripItem {
  color: grey;

  Label {
    text-transform: uppercase;
  }
}

TabStripItem:active {
  color: green;
}
</style>
```

**Comment by lhovee** [comment]
where PlaceholderComponent.vue looks like

```
<template>
  <GridLayout>
    <Label
      :text="`${title} Component`"
      class="h2 text-center"
    />
  </GridLayout>
</template>

<script lang="ts">
import Vue from 'nativescript-vue';
import { Component, Prop } from 'vue-property-decorator';

@Component
export default class PlaceHolderComponent extends Vue {
  @Prop({ default: 'Placeholder' }) title: string;
}
</script>
```

**Comment by lhovee** [comment]
tns-android: 6.0.2
tns-ios: 6.0.2
nativescript-vue: 2.4.0
tns-core-modules: 6.1.0

**Comment by rigor789** [comment]
@lhovee I just re-created your example in the playground (using js) and seems to be working fine: https://play.nativescript.org/?template=play-vue&id=RPxTCx

I had to change `grey` to `gray` as it was erroring about `grey` not being a valid color.

**Comment by MartoYankov** [comment]
@lhovee We've tried to reproduce this in the playground, but it seems it's working fine - https://play.nativescript.org/?template=play-vue&id=RPxTCx . There are two differences to your code - the runtimes in the playground are updated to 6.1.0 and we're using local images instead of resources although I don't think these affect the scenario.

**Comment by lhovee** [comment]
@rigor789 @MartoYankov 

Tested your playground on an Android 7.0 LG K20 PLUS (I know I need to upgrade) and it works as expected. The active icon is black.

Unfortunately,
iPhone XR (and other iOS devices) the playground has a blue icon instead of the black. Can you confirm this is what you're seeing and whether or not that's an issue?

**Comment by lhovee** [comment]
UPDATE:
<TabStrip iosIconRenderingMode="alwaysOriginal">

This resolves the issue I was seeing on iOS.

**Comment by MartoYankov** [comment]
@lhovee Yes, this is the expected default behavior with 6.1 on iOS when you use resource images. There are specific iOS guidelines for these as far as I know. The `iosIconRenderingMode` property disables this behavior. The property was missed/forgotten in 6.0 See also https://github.com/NativeScript/NativeScript/issues/6967

**Comment by lhovee** [comment]
Appreciate the help!
