### ISSUE TITLE
[BottomNavigation] Renders bottom empty space if tabstrip is not defined

### ISSUE THREAD

**Issue by manoldonev** [NativeScript/NativeScript#7471]
**Environment**
 - CLI: rc
 - Cross-platform modules: rc
 - Android Runtime: rc
 - iOS Runtime: rc

**Describe the bug**
BottomNavigation component renders empty space at the bottom (where tabstrip would be) when no tabstrip is defined.

**To Reproduce**
Use the following xml declaration:
``` xml
<BottomNavigation backgroundColor="yellow">
    <!-- <TabStrip>
        <TabStripItem title="First"></TabStripItem>
        <TabStripItem title="Second"></TabStripItem>
        <TabStripItem title="Third"></TabStripItem>
        <TabStripItem title="Fourth"></TabStripItem>
    </TabStrip> -->

    <TabContentItem>
        <GridLayout>
            <!-- <Label text="First View" /> -->
            <Button text="Go to fifth (no tabstrip item)" tap="onTap" />
        </GridLayout>
    </TabContentItem>

    <TabContentItem>
        <GridLayout>
            <Label text="Second View" />
        </GridLayout>
    </TabContentItem>

        <TabContentItem>
        <GridLayout>
            <Label text="Third View" />
        </GridLayout>
    </TabContentItem>

        <TabContentItem>
        <GridLayout>
            <Label text="Fourth View" />
        </GridLayout>
    </TabContentItem>

        <TabContentItem>
        <GridLayout>
            <Label text="Fifth View" />
        </GridLayout>
    </TabContentItem>
</BottomNavigation>
```

**Expected behavior**
BottomNavigation should not render any empty space for missing TabStrip.

**Additional context**
Android screenshot:
![Screenshot_1562341333](https://user-images.githubusercontent.com/2650247/60733104-a244d500-9f54-11e9-958e-a52059715428.png)

iOS screenshot:
![Simulator Screen Shot - iPhone X - 2019-07-05 at 18 42 38](https://user-images.githubusercontent.com/2650247/60733122-abce3d00-9f54-11e9-9338-61ecf8e2a9ac.png)

**Comment by manoldonev** [comment]
Most probably fixed with https://github.com/NativeScript/NativeScript/pull/7580

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
