### ISSUE TITLE
error TS2339: Property 'getter' does not exist on type 'typeof ios'. in Nativescript 6 with angular

### ISSUE THREAD

**Issue by acharyaks90** [NativeScript/NativeScript#7473]
**Environment**
  "tns-android": {
      "version": "6.0.0-rc-2019-06-27-172817-03"
    },
    "tns-ios": {
      "version": "6.0.0-rc-2019-06-28-105002-01"
    }
 - CLI: "@angular/compiler-cli": "~8.0.0",
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

Property 'getter' does not exist on type 'typeof ios'. in Nativescript 6
```javascript
 utils.ios.getter(UIApplication, UIApplication.sharedApplication)
        .keyWindow
        .endEditing(true);
```

Earlier with nativescript 5 it was working but after upgrade showing error

**Comment by acharyaks90** [comment]
Also getting error after run by Object property access
utils.ios.getter() is deprecated; use the respective native property instead
 utils.ios['getter'](UIApplication, UIApplication.sharedApplication)

**Comment by charsleysa** [comment]
Hi @acharyaks90 

Starting with NativeScript 6.0 the ios getter and setter util has been removed.

You should access the properties directly, e.g.
```ts
UIApplication
        .sharedApplication
        .keyWindow
        .endEditing(true);
```

**Comment by NickIliev** [comment]
[The list of deprecated APIs for the upcoming NativeScript 6](https://github.com/NativeScript/NativeScript/pull/7382).

We will add those to the CHANGELOG.md once the release is live.
