### ISSUE TITLE
Set size to icon in NavigationButton on Android

### ISSUE THREAD

**Issue by panagulis72** [NativeScript/NativeScript#7476]
In a Nativescript/Angular app I have the avatar of the user on the left in the header. For Android, I have to use NavigationButton:
`<NavigationButton #navigationButton *ngIf="isAndroid" [loaded]="navigationButtonLoaded()" [icon]="customImage" (tap)="toggleSideDrawer()">
</NavigationButton>`

The customImage is a https resource; NavigationButton wants a local resource, so when the user signin I download the image, using the local resource. It works, but the image is big so it fills the whole header. I tried to simply ad a class con NavigationButton setting width and height but it doesn't work. So I added the loaded function, where I tried to set it manually, it doesn't give any error but it doesn't work:
`....

@ViewChild('navigationButton') navigationButton: NavigationButton;
 ....

navigationButtonLoaded() {
    if (this.navigationButton) {
        this.navigationButton.effectiveWidth = 45;
        this.navigationButton.effectiveMinWidth = 45;
        this.navigationButton.effectiveHeight = 45;
        this.navigationButton.effectiveMinHeight = 45;
    }
}`

**Comment by NickIliev** [comment]
`this.navigationButton` is the Angular element reference while you need the nativeElement.

Try this
```JavaScript
this.navigationButton.nativeElement.effectiveWidth = 45;
```

Or even better - using the NativeScript **loaded** event to get the NativeScript component
```HTML
<NavigationButton *ngIf="isAndroid" 
[loaded]="navigationButtonLoaded($event)"
[icon]="customImage" (tap)="toggleSideDrawer()"> </NavigationButton>
```

and the code-behind file
```TypeScript
navigationButtonLoaded(args: EventData) {
    let navButton = args.object as NavigationButton;
    navButton.effectiveWidth = 45;
}
```

**Comment by panagulis72** [comment]
With the second solution, it gives me the following error:
`ERROR ReferenceError: $event is not defined`

with the first solution, it provides no error but it doesn't work

**Comment by NickIliev** [comment]
@panagulis72 there was a minor syntax error - the `loaded` is an event and not property so in Angular you need an ordinary bracket to bind to an event.

```
(loaded)="navigationButtonLoaded($event)"
```

**Comment by panagulis72** [comment]
> ```
> (loaded)="navigationButtonLoaded($event)"
> ```

No more errors, but as the first solution it doesn't work, the image still takes the width of the ActionBar

**Comment by NickIliev** [comment]
@panagulis72 the NavigationButton should be used for navigation and not for custom user photos - that said when using static resources they should be set in the resource folders (`drawable`) as discussed here: https://stackoverflow.com/a/30874595/4936697

SO if you want to have an image that will change based on the user, then I would recommend to create your own custom ActionItem and use `Image` to set custom resources.

**Comment by panagulis72** [comment]
Yes at the beginning I tried to use the Image, but in the Action bar on android it is not possible to assign it on the left

**Comment by surdu** [comment]
@NickIliev [This](https://github.com/NativeScript/NativeScript/issues/7476#issuecomment-509183130) doesn't seem to work on vanilla JavaScript. Looking at the `args.object` in the `loaded` function with the debugger I see no `.effectiveWidth` property. Obviously, setting it has no effect.

Am I missing something ?

I could provide a playground example is this should work also in Vanilla JS.
