### ISSUE TITLE
ShowModal in v1.3

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#748]
I just upgraded to the  newest masters this morning; and I notice my dialog is opening length wise full screen.   As a test you can create the simple xml page: \<Page>\<StackLayout orientation="horizontal">\<Button/>\<Button/>\</StackLayout>\</Page>

An you will see the two buttons going the full length of the screen.   Something in the measurements are off and we might want to get this fixed before pushing 1.3.

**Comment by NathanaelA** [comment]
Ok, I traced it down: https://github.com/NativeScript/NativeScript/blob/master/ui/page/page.android.ts#L59
The .star tells it to use the whole screen height.    If you change it to .auto then the dialog works properly again; however since this is for the page; switching it to auto breaks the normal page.   

Is their a call into the this._grid we can do to switch this to .auto when it is a dialog.

**Comment by NathanaelA** [comment]
Please note this is still an issue with the final release of v1.30

**Comment by NathanaelA** [comment]
I was able to work around this easily by using the callback variable in my pull request #726 to detect if it is a callback or not.   The _createUI gets called way past the showModal call.    So I can either modifiy patch #726 to include the fix for this issue.  Or I can make a dependant patch on #726.   I don't see any reason to create another variable (& waste memory) to denote this is a showmodal dialog rather than a normal page view.

**Comment by NathanaelA** [comment]
The above mentioned patch will only fix Android; however while testing this on iOS; it has the same issue it goes fullscreen no matter what the  **fullScreen** variable is set too.  Somehow the measuring pass thinks it is full screen unless you manually set a height on the parent container.

**Comment by NathanaelA** [comment]
I added a Android fix for this dialog issue also in the pull request #726.

**Comment by N3ll** [comment]
This issue is fixed in pull request https://github.com/NativeScript/NativeScript/pull/726.

**Comment by hvadotnarola** [comment]
@N3ll where can i find documentation for modal ?

**Comment by N3ll** [comment]
@hvadotnarola - I hope this could be helpful https://docs.nativescript.org/angular/ui/ui-dialogs.html.

**Comment by hvadotnarola** [comment]
Thanks for Doc. link but seems like its for angular only, i am looking for javascript.

**Comment by NickIliev** [comment]
Hey @hvadotnarola  
Here is the link for modal pages in nativeScript Core:
 [https://docs.nativescript.org/core-concepts/navigation#modal-pages](https://docs.nativescript.org/core-concepts/navigation#modal-pages)

**Comment by hvadotnarola** [comment]
Thanks @NickIliev was looking for something similar.
