### ISSUE TITLE
Issue in android:pathPrefix on AndroidManifest.xml with special character #

### ISSUE THREAD

**Issue by panagulis72** [NativeScript/NativeScript#7485]
I want that this link is captured and opened with my app. So, I added these lines on AndroidManifest file:
    
```
    <intent-filter>
           <action android:name="android.intent.action.VIEW" />
           <category android:name="android.intent.category.DEFAULT" />
           <category android:name="android.intent.category.BROWSABLE" />
           <data android:scheme="https" android:host="thus.customapp.it" android:pathPrefix="/#/app/customapp/itemDetail"/>
    </intent-filter>
```

I also tried with: 
    
`    <data android:scheme="https" android:host="thus.customapp.it" android:pathPrefix="/#/app/customapp/itemDetail/.*"/>`

and this:
    
`     <data android:scheme="https" android:host="thus.customapp.it" android:pathPattern="/.*/.*/.*/.*/..*"/>`

and this:
    
`      <data android:scheme="https" android:host="thus.customapp.it" android:android:pathPrefix="/#"/>`

and this:

`    <data android:scheme="https" android:host="thus.customapp.it" android:pathPattern="/#/.*" />`

but it doesn't work.

P.S. with the following code:

`    <data android:scheme="https" android:host="thus.customapp.it" android:pathPattern="/.*"/>`

it works, but I need to intercept just a url which contains "itemDetail", and not, for example, https://thus.customapp.it/#/app/customapp/editItem/45289348293423

And I tried to hanlde the path with %23, so I generated the url with '%23' instad of '#' and it works! But if I choose to open it with Chrome, it doesn't work because it doesn't decode %23 into #

**Comment by tsonevn** [comment]
Hi @panagulis72,
I found [ this StackOverflow thread](https://stackoverflow.com/a/12050917), where a similar problem for native Android project has been discussed. In the referred comment above, it is suggested using in your case `android:path` instead of `android:pathPrefix` or `android:pathPattern`. For more info, check out the attached comment.

**Comment by panagulis72** [comment]
@tsonevn  thank you for you answer, but I doesn't work because I guess that android path is going to ignore the '#' character. So I guess the path /#/ of my url is going to be ignored and it will not match.
Anyway, if I generate the url writing '/%23/......' and I write /%23/ in the path, it works but I have the opposite problem, if I choose to open the url with Chrome or another browser on my phone it doesn't work because it doesnt convert %23 into #

**Comment by tsonevn** [comment]
Hi @panagulis72,
Excuse me for the delay in reply,
Can you try to register two schemas(one with `%23` and the other with `#`)? Check out [this thread](https://stackoverflow.com/questions/27321242/android-deeplinking-not-working-with-multiple-schemes) where it is demonstrated how to register multiple schemas.

**Comment by pcsantana** [comment]
Hi @panagulis72 !
Did you find a solution?
Thanks!
