### ISSUE TITLE
Change event on Switch for NativeScript Core

### ISSUE THREAD

**Issue by surdu** [NativeScript/NativeScript#7487]
**Is your feature request related to a problem? Please describe.**
I have a RadListView and each row has a `Switch` on it. Not considering the difficulty of binding to a bunch of switches from code, there is the problem that not all rows of the RadListView are created at list's `loaded` event (only as many as to fill the screen plus some few extra for buffer). So, if you try to search for all switches in the page in order to bind to the change event, you will miss a lot of the switches at the end of the list.

**Describe the solution you'd like**
The `Switch` element could have an `onChange` attribute.

**Describe alternatives you've considered**
Binding from code, which works for simple, non-list scenarios. For lists, you could re-bind on list scroll finish event, but that sounds overkill.

[This](https://github.com/NativeScript/NativeScript/issues/1353#issuecomment-170849408) also doesn't seem to work (anymore?) 

Also found [this](https://github.com/NativeScript/NativeScript/issues/5279#issuecomment-358217997) which seems to work pretty fine, but it looks slightly more complicated than it should. Also, this also seems to fire when the view is loaded if the model that is bound to the `checked` attribute has a value other than `true`.

**Comment by NathanaelA** [comment]
@surdu  - https://github.com/NativeScript/NativeScript/pull/7403
Should hopefully show up in 6.0 -- I haven't verified, but I am under the impression it will be in 6.0

**Comment by surdu** [comment]
![](https://media.giphy.com/media/IgEQeDbey5YYg/giphy.gif)
