### ISSUE TITLE
Make it possible to color the icons when using window.setNavigationBarColor()

### ISSUE THREAD

**Issue by Reached** [NativeScript/NativeScript#7492]
**Is your feature request related to a problem? Please describe.**
I think it would be an awesome addition if we made it possible to change the color of the icons of the Android navigation when using `window.setNavigationBarColor()`. Currently they seem to be always white.

**Describe the solution you'd like**
Some kind of similar api as the above, like `window.setNavigationBarIconColor()`

This is not possible AFAIK, but I think it would make a great addition to NativeScript.

**Comment by NickIliev** [comment]
@Reached you should be able to use the native API access to do that.

e.g., something like (TypeScript)
```TypeScript

declare let android: any; // or use tns-platform-declarations for Android SDK typings and intellisense;
import { getNativeApplication, android as androidApp } from "../application";

const window = androidApp.foregroundActivity.getWindow();
const resources = androidApp.context.getResources();

window.setNavigationBarColor(resources .getColor(android.R.color.Theme_color));
```

**Comment by NickIliev** [comment]
On second thought , are you trying to change the color of the ActionBar? If so that could be done by directly using the background-color property

```
<ActionBar title="Home" backgroundColor="orangered">
</ActionBar>
```

**Comment by Reached** [comment]
No you are absolutely right, it's the nav-bar in the very bottom of the Android phone.

Oh, thats cool! So `context.getResources()` is actually the content of the navigationBar?

Thank you!
