### ISSUE TITLE
Reduce the size of worker chunks

### ISSUE THREAD

**Issue by vakrilov** [NativeScript/NativeScript#7503]
Related to this: conversation https://github.com/NativeScript/worker-loader/pull/39#issuecomment-510081707

### Is your feature request related to a problem? Please describe.
When you import/require the `tns-core-modules\globals` package in a worker file you get a huge worker chunk (~2.5MB). The reason for that is that in [`globals` module we require a bunch of polifills](https://github.com/NativeScript/NativeScript/blob/release/tns-core-modules/globals/globals.ts#L30-L33). The one causing biggest impact is `ui/dialogs` as it drags dependencies to many ui modules with it (ironically it exactly the one you will probably won't need in a worker).

###  Describe the solution you'd like
Split the `xhr`, `timers`, `fetch`, `dialogs` etc. polyfills into separate modules so that you can require only the ones you want in a worker. All of them should be included by default in `globals`. Optionally create `workers-globals` that will include only non-ui polifills.

CC @edusperoni

**Comment by edusperoni** [comment]
Really awesome work @vakrilov!

I imagine `workers-globals` is probably a must for a more friendly dev experience. I'm thinking mostly when the dev wants to use non-ui plugins, is not sure what polyfills are required for it and just wants everything non-ui included.

Plugin developers must also take care to not import `globals` if they want to support workers.

**Comment by vakrilov** [comment]
With he current state of the PR you can do the following in the worker:
```
import "tns-core-modules/globals/core";
import "tns-core-modules/globals/polyfills/timers";
import "tns-core-modules/globals/polyfills/xhr";

// Use setTimeout() or xhr
``` 
So you would have to import `globals/core` + `[polyfills]`. 

I'm considered adding a `workers-globals` file that will import `core + timers + xhr + fetch`, but I think there is a risk of making things even more confusing as you would have to know what is it in `workers-globals` and what is not. And still if you want to optimize the worker code - handpicking which polyfills to include is the better approach.

@edusperoni What do you think?

**Comment by edusperoni** [comment]
That's the approach I'm probably using in my apps. `core + timers + xhr + fetch` are not particularly big, so many devs would prefer to just import a hassle free `worker-globals` (especially people that are starting).

The best approach is probably importing specific polyfills. I just get worried about seeing weekly stackoverflow threads titled "help! Can't use setTimeout on worker!" hahaha. So either way is fine.
