### ISSUE TITLE
Regexp bug

### ISSUE THREAD

**Issue by Isahara86** [NativeScript/NativeScript#7511]
**Environment**
packages versions:
    "@angular/core": "^8.1.0",
    "tns-core-modules": "^6.1.0-next-2019-07-03-144356-02",

    OS: ios 

**Describe the bug**
Unable create regular expression on ios
For android everything works fine

**To Reproduce**
"12345".replace(/(?<=.).(?=.)/g, '*');
ERROR SyntaxError: Invalid regular expression: invalid group specifier name

**Expected behavior**
"12345".replace(/(?<=.).(?=.)/g, '*');   // expected to be 1***5

**Comment by NickIliev** [comment]
It seems your issue is related to what regex functionalities are being supported no iOS (WebKit) - see[ this thread for a similar issue](https://stackoverflow.com/a/51568859/4936697).

CLosing as unrelated to NativeScript

**Comment by NathanaelA** [comment]
@Isahara86 - https://nativescript.rocks/compat/es2016plus/#test-RegExp_Lookbehind_Assertions
Also this site has this documented, as this shows what each JS engine supports and where you might run into differences.

**Comment by Isahara86** [comment]
Thanks for the explanation
