### ISSUE TITLE
RadCalendar - stacked months scrolling overlapping date range

### ISSUE THREAD

**Issue by dudipsh** [NativeScript/NativeScript#7512]
**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**
I was hoping that someone could help create a solution to the rad calendar similar to the attached image. the months are stacked and you can view the months by vertical scrolling

to be more specific you will be able to view two months on screen simultaneously and pick a date range that overlaps both months

![alt text](https://androidexample365.com/content/images/2018/06/Date-Range-Picker.jpg)

**Describe alternatives you've considered**

**Additional context**

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-ui-feedback #1174](https://github.com/NativeScript/nativescript-ui-feedback/issues/1174) via [**ZenHub**](https://www.zenhub.com/)
