### ISSUE TITLE
can't npm install nativescript

### ISSUE THREAD

**Issue by pushkin-** [NativeScript/NativeScript#7515]
**Environment**
Windows 10
Node 10.11.0
npm 6.4.1

I ran the powershell script mentioned [here](https://docs.nativescript.org/angular/start/quick-setup#full-setup) to install dependencies and restarted my computer.

`npm i -g nativescript` results in:

>npm ERR! Unexpected end of JSON input while parsing near '...tivescript-2.5.0-2016'

Here's the full log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'nativescript' ]
2 info using npm@6.4.1
3 info using node@v10.11.0
4 verbose npm-session 69257132e718408d
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/nativescript 23ms (from cache)
8 silly fetchPackageMetaData error for nativescript@latest Unexpected end of JSON input while parsing near '...tivescript-2.5.0-2016'
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 359ms
11 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...tivescript-2.5.0-2016'
11 verbose stack     at JSON.parse (<anonymous>)
11 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
11 verbose stack     at consumeBody.call.then.buffer (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
12 verbose cwd C:\Users\User
13 verbose Windows_NT 10.0.17134
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "nativescript"
15 verbose node v10.11.0
16 verbose npm  v6.4.1
17 error Unexpected end of JSON input while parsing near '...tivescript-2.5.0-2016'
18 verbose exit [ 1, true ]
```

Any ideas? I think I saw a link to Node 8 in the docs. Is my Node too new?

**Comment by NathanaelA** [comment]
Try doing `npm i -g nativescript@latest`  or `npm i -g nativescript@5.4.2`   Based on your error; it appears you are getting v2.5.0 and a test version of 2.5.0 at that.   v2.5 is NOT Node 10 compatible.   NativeScript 5.4 is the current version, and NS 6 is supposed to be released in the next two weeks.  :)

**Comment by pushkin-** [comment]
@NathanaelA  Huh - even when doing that, it's trying to pull in 2.5.0. Very strange...

**Comment by NathanaelA** [comment]
@pushkin- You might need to clear or check your npm cache; occasionally it can get corrupt.

**Comment by pushkin-** [comment]
@NathanaelA I've already tried that, and it says:

> As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. `npm cache verify` checks out.

**Comment by NathanaelA** [comment]
You might have to look at the full npm log to see what it is failing on.  Or add a `--verbose` to the install.  One of those might give you a better clue at what exactly is failing...

It is possible it is failing to deinstall 2.5.x if you had that installed.  If that is the case;  you can manually delete the folder out of the global node_modules folder...

**Comment by tsonevn** [comment]
HI @pushkin-,
Were you able to install the latest {N} version or you are still facing an issue?

**Comment by pushkin-** [comment]
@tsonevn I am still facing the issue. adding `--verbose` to the `npm install` didn't provide any useful information, and I didn't have `2.5.x` already installed. Still not sure why `npm` is trying to install 2.5.0 even though, 5.4.2 is clearly the latest version.

**Comment by tsonevn** [comment]
Hi @pushkin-,
This issue can happen if you have a local folder which contains a copy of a {N} CLI old package in the directory where you've executed the npm install command. In this case, perhaps npm takes the local package instead of downloading the latest version from npm. On that matter, can you try the steps below and check if they will solve the problem.
1. create a new directory
`mkdir test`
2. open the directory
`cd test`
3. run 
`npm i -g nativescript`

**Comment by pushkin-** [comment]
@tsonevn Brilliant, that did it - thanks!
