### ISSUE TITLE
RadSideDrawer needs slow finger moving from side to open (Angular & Android)

### ISSUE THREAD

**Issue by DarioDomiDE** [NativeScript/NativeScript#7517]
**Environment**
- all NS versions
 - Android only (iOS is working)
 - Angular only (via RadSideDrawer defined in .xml instead of Angular is working, tested with Angular v7 & v8)

**Describe the bug**
Hello, I noticed that RadSideDrawer is having a "lag" or some kind of delay on Angular & Android. It's currently not possible to open the SideDrawer via moving your fingers from the side to center of the device in a "normal speed" (like expected from other apps). You have to slide your fingers very slowly to let the RadSideDrawer appear.

**To Reproduce**
The same problem happens on every ng+angular project running on Android. Create project with template `tns-template-drawer-navigation-ng` and move/slide your fingers from (left) side to middle of the screen.

**Expected behavior**
You can move your fingers in all speeds and the RadSideDrawer will open independently how fast you slide. For example try the "Examples NativeScript" Demo from Play Store (or github)

**Sample projecty**
- [Examples NativeScript](https://github.com/NativeScript/nativescript-marketplace-demo) App (will work)
- Newly created template ng+angular+sidedrawer (won't work)

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-ui-feedback #1175](https://github.com/NativeScript/nativescript-ui-feedback/issues/1175) via [**ZenHub**](https://www.zenhub.com/)
