### ISSUE TITLE
Ux  disturbs on  different devices 

### ISSUE THREAD

**Issue by abhi95353** [NativeScript/NativeScript#7518]
ux is disturbed on different devices. kindly help out so that user experience is not disturbed in different screen sizes .

**Comment by tsonevn** [comment]
HI @abhi95353,
If you need to make some additional UI setup based on the screen size, you can use[ Screen Size Qualifiers](https://docs.nativescript.org/ui/supporting-multiple-screens#screen-size-qualifiers) option.

**Comment by abhi95353** [comment]
NIkolay,

I am working on Qualifiers.I will respond you after using them .
I beliver this suggestion of yous will work.

Thanks,
Abhimanyu
