### ISSUE TITLE
dynamic import support

### ISSUE THREAD

**Issue by Serge-SDL** [NativeScript/NativeScript#7524]
Hi,

I need to use some dynamic import in my app (importing js module from http or local device file), but it doesn't work.

I tried :
`import(/* webpackIgnore: true */ file.path)` -> got the error "Not supported"

and
`System.import(file.path)` -> got the error "Cannot find module '/path/to/file'" even if the file exists.

Is this situation expected? Is there an other way?
thanks for your help!

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-dev-webpack #990](https://github.com/NativeScript/nativescript-dev-webpack/issues/990) via [**ZenHub**](https://www.zenhub.com/)
