### ISSUE TITLE
Feature request: sound!

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/NativeScript#753]
NativeScript apps are currently silent. @jlooper and I would love to be able to do something like this:

```xml
<Button tap="tap" text="LET THERE BE MUSIC" />
```
```js
var sound = require("sound");
exports.tap = function() {
    sound.play("~/click.mp3");
};
```

Just a request, obviously not high priority. This would be a fun plugin to write for someone in the community too—just in case someone's looking for a fun side project :)

**Comment by jlooper** [comment]
+1 I think this would be a nice feature and hopefully not too hard to implement. It's a nice Usability bonus if, when you click a button, you hear a little 'ping'. Also it would enhance notifications. :)

**Comment by jbristowe** [comment]
The following should work for iOS:

```javascript
var url = NSURL.fileURLWithPath(fileName);
var audioPlayer = AVAudioPlayer.alloc();
audioPlayer.initWithContentsOfURLError(url);
audioPlayer.play();
```

I haven't looked into Android yet but I don't think it would be too hard.

Thinking about this - and, I apologise for making this tangent - I believe there's a good case to be made for refactoring the **image-source**; specifically, to make it more generic (i.e. **media-source**) for any non-streaming media type (i.e. audio, video). This change would include the `http` module, which has a method, `http.getImage` which should be `http.getMedia`.

**Comment by burkeholland** [comment]
I don't think that's a good logical step for web developers. We have Img, Audio and Video tags, so we would expect to find the same in the {N} markup.

**Comment by jbristowe** [comment]
The **image-source** is responsible for loading an image from a file, resource, or remote location. It's used under-the-covers by `<Image>`. I'm proposing to make it more generic to load any non-streaming content so it could be used not only by `<Image>` for elements like `<Audio>` and `<Video>` (if created).

**Comment by tjvantoll** [comment]
Closing this as @jbristowe built a really nice plugin https://www.npmjs.com/package/nativescript-sound.
