### ISSUE TITLE
Can we change DatePicker country from RadDataForm ?

### ISSUE THREAD

**Issue by Loown** [NativeScript/NativeScript#7530]
Hi,

I'm trying to find out a solution to output french translation of the chosen date of a user.

When someone selects a date he gets this output : 

> Tue, 17.06

Actually I'm french and I would have something like this : 

> Mardi 16 Juillet

Is there a feature to change that behavior?

I'm new and still learning so be kind !

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-ui-feedback #1180](https://github.com/NativeScript/nativescript-ui-feedback/issues/1180) via [**ZenHub**](https://www.zenhub.com/)
