### ISSUE TITLE
crypto and crypto-browserify not working

### ISSUE THREAD

**Issue by ineiti** [NativeScript/NativeScript#7533]
**Environment**
 - CLI: 5.4.2
 - Cross-platform modules: 5.4.3
 - Android Runtime: 5.4.0
 - iOS Runtime: 5.4.2
 - Plugin(s): none

**Describe the bug**

When using `crypto-browserify`, I get the following error:

```
JavaScript error:
file:///app/vendor.js:32286:56: JS ERROR Error: Parsing XML at 1:1
> undefined is not an object (evaluating 'undefined.browser')
```

**To Reproduce**

I use a fresh install from `tns create mobile --ts` and only add the following two lines to `app/main-page.ts`:

```
import { randomBytes } from "crypto-browserify";
// The following doesn't work neither:
// import { randomBytes } from "crypto";
...
    let rb = randomBytes(32);
```

Then I run:

```
rm -rf node_modules hooks platforms
tns run ios
```

**Expected behavior**

1. Get 32 bytes of randomness.
2. Future hope: getting node-modules to run that use `crypto`.

**Sample project**

https://play.nativescript.org doesn't allow importing `crypto` or `crypto-browserify`.

** What I tried **

- I tried installing `nativescript-nodeify`, which didn't work, even after applying patches to make it pass in webpack.
- I tried `"useLegacyWorkflow": true` in `nsconfig.js`, which didn't work, neither.

**Comment by tsonevn** [comment]
Hi @ineiti,
The `crypto-browserify` is not officially supported by NativeScript. By using `nativescript-nodeify`, indeed, you can use most of the non-compatible npm plugins in {N}. However, there might be an issue with a `nativescript-nodeify` plugin or some additional changes might be needed to make `crypto-browserify` compatible. On that matter, I would suggest contacting the author of `nativescript-nodeify` by opening a [new issue in the plugins repository](https://github.com/EddyVerbruggen/nativescript-nodeify/issues).

**Comment by ineiti** [comment]
Hi @tsonevn,

Thanks - I'm using `crypto-browserify` because `crypto` wasn't even recognized as module. I didn't find any example that uses something like `import {randomBytes} from "crypto";` - does that exist?

**Comment by tsonevn** [comment]
Hi @ineiti,
I've just noticed that `crypto` is marked as a deprecated package in  NPM. Regarding the `crypto-browserify`, there are no type definitions in the package, which means that you should use `require` instead of `import`. However, keep in mind that I haven't tested  `crypto-browserify` and can not guarantee that it will work as expected in {N} project while using `nativescript-nodeify`.
