### ISSUE TITLE
Feature Request: Dynamic form generator by json, like Alpaca

### ISSUE THREAD

**Issue by kokizzu** [NativeScript/NativeScript#7545]
**Is your feature request related to a problem? Please describe.**
the hassle when creating a lot of forms in NativeScript, especially something like [this](http://www.alpacajs.org/docs/cookbook/nested-tables.html)

**Describe the solution you'd like**
a dynamic form generator like [Alpaca](http://www.alpacajs.org) or [JsonForm](https://github.com/jsonform/jsonform/)

**Comment by tsonevn** [comment]
Hi @kokizzu,
In your case, you can use the RadDataForm component provided by nativescript-ui-dataform. This component allows you to display forms in a {N} app, where the provided JSON object is used for the generation of the field. For more info, you can review [the documentation here](https://docs.nativescript.org/ui/professional-ui-components/DataForm/GettingStarted/dataform-start-source) and the [demo app in this repository](https://github.com/NativeScript/nativescript-ui-samples/tree/master/dataform/app/examples/getting-started-json).
