### ISSUE TITLE
[xhr] Empty response headers when doing a request with content type json and an empty body

### ISSUE THREAD

**Issue by Cacodaimon** [NativeScript/NativeScript#7549]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.4.0

**Describe the bug**
Doing a XMLHttpRequest (using Axios for example) where the server responses with a HTTP 201 for created, an **empty body** and a proper location header with the content type "application/json" the response headers gets ommited.

This is because `getAllResponseHeaders()` returns an empty string if the `_errorFlag` is true. The flag gets sets to **true** because of an "SyntaxError: Unexpected end of JSON input" error catched in the `send()` method.

Suggested fix is here: https://github.com/Cacodaimon/NativeScript/commit/e57fd1e96e6fa2ed95e2d76aa6723394c44768ef

**To Reproduce**
Do an request to an server which responses with a "application/json" as content type and an empty response body.

**Expected behavior**

Firefox and Chrome do not ommit the headers when doing the same XMLHttpRequest.

**Comment by tsonevn** [comment]
Hi @Cacodaimon,
I tested your case with {N} 5.4 and 6.0, however, was unable to recreate an issue with the XMLHttpRequest. Can you send us a sample project, that can be used for recreating the issue?

**Comment by Cacodaimon** [comment]
Sure, do you need an complete sample project or just some lines of code which does the request and shows that the header are missing and one file for the HTTP server stub? In which language/what platfrom do you prefer the server stub, node.js, PHP…?

**Comment by tsonevn** [comment]
Hi @Cacodaimon,
Excuse me for the delayed reply.
It would be better if you can send us a complete sample project. About the second question, you can send us node.js based server stub.
