### ISSUE TITLE
Enable -skipLibCheck by default on all templates

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/NativeScript#7552]
**Is your feature request related to a problem? Please describe.**
https://github.com/nstudio/nativescript-loading-indicator/issues/1#issuecomment-512881780

**Describe the solution you'd like**
Add `skipLibCheck: true` to all templates from the CLI. No idea why that's not already done, large majority of users have no clue why their projects would want to analyze node_modules.

**Describe alternatives you've considered**
None.

**Additional context**
I'm tired of issues because people's projects analyze node_modules. So I guess, why doesn't the CLI default to this in the tsconfigs for all templates? By skipping libs, you also improve the performance during `tsc` for projects with a lot of deps and files to process. So there are multiple benefits.

**Comment by DickSmith** [comment]
There is absolutely no benefit to doing a lib check on an app project. If the libs are incorrect or have conflicting types it may cause an irrelevant build failure.
