### ISSUE TITLE
Pixel 2 API 29 httpClient not working correctly

### ISSUE THREAD

**Issue by bradrice** [NativeScript/NativeScript#7555]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: NativeScript CLI version: 5.4.2
 - Cross-platform modules:
https://gist.github.com/bradrice/c47407d8559802d0e44d5f0e31e72a0c
 - Android Runtime: 5.4.0
 - Plugin(s):
@angular-devkit/build-angular │ ^0.800.1 │
│ @angular/cli                  │ ^7.0.3   │
│ @angular/compiler-cli         │ ~7.2.0   │
│ @ngtools/webpack              │ ^6.2.7   │
│ @types/lodash                 │ 4.14.68  │
│ @types/node                   │ ~6.0.60  │
│ css-loader                    │ ^2.1.0   │
│ lazy                          │ 1.0.11   │
│ nativescript-dev-sass         │ ^1.7.0   │
│ nativescript-dev-typescript   │ ^0.10.0  │
│ nativescript-dev-webpack      │ ^0.24.1  │
│ tns-platform-declarations     │ ^3.4.1   │
│ ts-node                       │ ~3.3.0   │
│ tslint                        │ ^5.8.0   │
│ typescript                    │ ^3.2.4   │
│ uglifyjs-webpack-plugin       │ ^2.1.3   │
│ webpack                       │ ^4.29.5

**Describe the bug**
I have finally released a nativescript app to the store. iOS is good, almost all versions of Android are good. However, someone downloaded onto a Pixel 2 with API 29 and told me they couldn't login. I downloaded an emulator and sure enough, the http request never goes through.

This is my login code in my service:

```
getLogin(args): RxObservable<Object> {
    var params = this.buildQueryParams(args);
    let headers = this.createRequestHeader();
    return this.http.get(`${this.serverUrl}AuthenticateUser${params}`);
}
```
This is my login component using it:

```
login() {
  this.isLoggingIn = true;
  Object.assign(this.user, this.loginForm.value);
  this.httpSub = this.httpget.getLogin(this.user)
  .pipe(
    map(res=>res),
    catchError((err: string) => {
      const errMsg = "There was a network error, please check your connection or try again later";
      return of(errMsg)
  })
)
  .subscribe((result) => {
    if(result['Status'] === "SUCCESS"){
      this.onGetDataSuccess(result);
    }
    else if(typeof(result) === 'string'){
      this.errorMessage = "There is a connection error.";
      this.isLoggingIn = false;
    }
    else {
      this.errorMessage = "user name or password incorrect";
      this.isLoggingIn = false;
    }
}, (error) => {
  console.log("got an error");
    this.errorMessage = "Verify your username and password.  If you have an account, but are having trouble, call 1-866-706-8665.";
    this.isLoggingIn = false;
});
```
I'm getting this on the Pixel:

There is a connection error.

In the debugger this is what I see in the Headers on the pixel:

```
Request URL: http://toolingu.com/ToolingU.WCF.TuAppService/ToolingU.WCF.TuAppService.svc/AuthenticateUser?username=<user>&password=<pw>
Referrer Policy: no-referrer-when-downgrade
Provisional headers are shown
Accept: application/json, text/plain, */*
username: <user>
password: <pw>
```
This is what I see on the emulators that are working correctly:

```
Request URL: http://toolingu.com/ToolingU.WCF.TuAppService/ToolingU.WCF.TuAppService.svc/AuthenticateUser?username=<user>&password=<pw>
Request Method: GET
Status Code: 200 OK
Referrer Policy: no-referrer-when-downgrade
Provisional headers are shown
Accept: application/json, text/plain, */*
username: <user>
password: <pw>
```
It appears the error happens instantly, as if it isn't waiting for a response to come back. Why would one device not use the http get call?

**To Reproduce**
Open Pixel 2 emulator
Make an http.get request using Nativescript httpClient

**Expected behavior**
Call the url and return SUCCESS.

**Sample project**

**Additional context**

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-angular #1913](https://github.com/NativeScript/nativescript-angular/issues/1913) via [**ZenHub**](https://www.zenhub.com/)
