### ISSUE TITLE
ListView Render Problem

### ISSUE THREAD

**Issue by nitishsainani** [NativeScript/NativeScript#7558]
**Environment**
 - Android Runtime: ListView render while runtime android

**Describe the bug**

**Expected behavior**

** MY LOGIC **

`if (image != null) src = base64StringImage;`
`else src="~/shared/images/default-icon.png"`

![Screenshot_1563610760](https://user-images.githubusercontent.com/37032957/61576245-3b4b2280-aaf5-11e9-90b5-cd37d212fe7e.png)
![Screenshot_1563610748](https://user-images.githubusercontent.com/37032957/61576246-3b4b2280-aaf5-11e9-8737-8ae33fa853d9.png)
![Screenshot_1563610744](https://user-images.githubusercontent.com/37032957/61576247-3b4b2280-aaf5-11e9-9d70-107b489e8040.png)

These screenshots are taken after scrolling down some 20 items in list and scrolling up.

**Comment by tsonevn** [comment]
HI @nitishsainani,
The given information is not enough to investigate further your problem.
Can you provide more info about the issue and environment(CLI, `tns-core-modules`, `tns-androida versions)? Also, send us the project or sample one, where the issue can be recreated.

**Comment by nitishsainani** [comment]
@tsonevn 
The issue is occuring on latest android versions.

I tested on some android versions

Working fine on:
android 6

Render Issues on:
android 8
android 9

I will share a sample project soon.

**Comment by alexZaicev** [comment]
The same issue I was experiencing with the latest TNS versions (Android only) when I was changing the background color of the ListView.itemTemplate child (StackLayout in my case) on user tap. One highlighted item was rendered several times in the list... Possibly issue comes from RecycleView widget on in Android

**Comment by edusperoni** [comment]
You should probably provide a demo project. Listview recycles the view, so what's most likely happening is:

1. view1 appears
2. you change view1 (set the image/background color)
3. view1 is recycled and you don't reset the image/background color when the view changes context


The reason scrolling fast/slow changes the behavior is that ListView is probably fetching some additional views, so you have more views in your pool, meaning you're less likely to see the same recycled view

**Comment by nitishsainani** [comment]
I cannot recreate the same issue. Maybe because I am not using base 64 strings.

`if (image != null) src = base64StringImage;`
`else src="~/shared/images/default-icon.png"`
