### ISSUE TITLE
Nordic characters: "æøå"

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#756]
Add support for Nordic characters: "æøå".
These should work when used both in XML and JavaScript.
Prior 1.3.0 they used to appear correctly, but in 1.3.0 we've degraded and they can't be used in JavaScript now in iOS.

The problem is easily reproduced with the hello world app and the following setup:

``` XML
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
  <StackLayout>
    <Label text="Tap the button" cssClass="title"/>
    <Button text="æøå" tap="{{ tapAction }}" />
    <Label id="l" text="{{ message }}" cssClass="message" textWrap="true"/>
  </StackLayout>
</Page>
```

``` JavaScript
var vmModule = require("./main-view-model");
function pageLoaded(args) {
    var page = args.object;
    page.bindingContext = vmModule.mainViewModel;
    page.getViewById("l").text = "æøå";
}
exports.pageLoaded = pageLoaded;
```

Be sure to add automation tests with image verification for usage in XML and JS.

**Comment by emiloberg** [comment]
Any updates on this? This is quite a deal breaker for us Swedes. It's like designing a user interface where you can't use one third of the english vowels ;)

**Comment by fealebenpae** [comment]
Fixed in https://github.com/NativeScript/ios-runtime/pull/334.
