### ISSUE TITLE
Poor workflow - Only one platform at a time

### ISSUE THREAD

**Issue by delanick** [NativeScript/NativeScript#7565]
Prior to CLI 5.4.2 (or when not using Web Pack) I was able to run on both iOS and Android devices all at the same time, made development easy as I was able to debug and test on both platforms as soon as I changed something.

With Web Pack enabled I can only run on one device at a time. Why is this? Painfully frustrating as I now need to do all the tests in two separate actions - first on Android, then restart it all on iOS. WHY?

Please advise.

**Comment by tsonevn** [comment]
HI @delanick,
We've tested the described case, however, was unable to recreate an issue with run command and starting the app on both platforms at the same time. On that matter, please provide more info about your environment({N} CLI, tns-core-modules, tns-android, tns-ios versions) as well as the exact steps that you are using while building the app. Also, can you recreate the issue with a project, created from scratch or only with a specific one? If so, can you send us the project?

**Comment by delanick** [comment]
@tsonevn Apologies, it's in Sidekick that it has changed, not sure if CLI was changed too. Sidekick stops me from running on both platforms when WebPack is enabled - meaning it would probably be the case going forward once they align with CLI 6. Please can you tag someone from the Sidekick team to look at this issue? Apologies if CLI 6 still allows running on multiple devices and platforms at once.

**Comment by delanick** [comment]
@delanick Since upgrading to CLI 6 (and with Sidekick not having caught up yet), I set up my environment for local builds using CLI, but am getting errors. Once I'm home later can I please include those errors here so someone can help me correct my environment? Builds aren't working.

**Comment by tsonevn** [comment]
HI @delanick,
Can you send us the full error log from the console and info about the exact steps that you are using while building the project?

**Comment by delanick** [comment]
@tsonevn apologies, was away for a while.

It was on Sidekick that I experienced it. Is that a Sidekick limitation then? On Sidekick as soon as I try to run it on both platforms' devices then it gives me that warning.

**Comment by delanick** [comment]
@tsonevn it's working since I updated Sidekick, thanks a ton! :)
