### ISSUE TITLE
Not able to update multiple frames

### ISSUE THREAD

**Issue by delanick** [NativeScript/NativeScript#7566]
I am using a tab root-view with a frame in each tab, but the data in one tab depends on what changes in the other. In the old versions, I'd just code a page into each tab. How do I send data from one frame to another? :)

**Comment by tsonevn** [comment]
HI @delanick,
Can you provide more info about your project and the issue you are facing? It will help, if you provide more info about your environment(CLI, tns-core-modules, tns-android, tns-ios), as well as a sample project that can be used for debugging. Meanwhile, you can try transferring data between the Frames, while using [application settings module](https://docs.nativescript.org/api-reference/modules/_application_settings_)

**Comment by delanick** [comment]
Hi @tsonevn Just a standard CLI 5.4.2 project, using Tabview as the app-root. Application Settings works great for persisting the data, but real-time changes don't update the frames.

Example: 

Tab 1 uses frame, T2 ->FB and Tab3 ->FC.

Once all tabs are loaded, all 3 frames are loaded. Simply swiping between tabs does not update the page/frame I'm swiping to. So let's say frame T1 is fixtures, and T2 is results. If I click on a fixture in T1, update it and save it, it is removed from fixtures and added to results array (currently saved in Application Settings. When swiping to Realts in T2, even though onLoad calls Applications Settings for the results array, it only does in on load, not on show. So swiping to T2 doesn't 'update' the list on screen. Is there an onDisplay or onSwipeTo event for tabs?
