### ISSUE TITLE
Reload app on save appears broken on version 6

### ISSUE THREAD

**Issue by subhaze** [NativeScript/NativeScript#7568]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: macOS (zsh)
 - Cross-platform modules:
 - Android Runtime: 28
 - iOS Runtime: 10.0
 - Plugin(s): Vue/Vuex/vuex-class-modules/vue-property-decorator

**Describe the bug**

When running `tns run android --bundle` in Nativescript 5.x after each save the Android emulator would do an incremental webpack build and reload the app but after updating to Nativescript 6 this appears to no longer work, the incremental builds happen but the app is no auto-reloaded. This leads to having to stop the build and re-run `tns run android --bundle`

**To Reproduce**

`tns run android --bundle` with Vue as the base, save any .vue/.ts source file and you'll see it rebuild in the CLI properly, however, the app will not reload with the new code.

**Expected behavior**

When saving a .vue/.ts file the app auto-reloads to gain the perf of webpacks incremental builds instead of having to stop and rebuild on every save.

**Sample project**

Unfortunately one is not available.

**Additional context**

**Comment by darkyelox** [comment]
Same problem occurs with an Angular project with NativeScript 6, but the issue have appeared only today, back days there wasn't any problem.

**Comment by tsonevn** [comment]
Hi all,
I tested the described case on my side with {N} Vue and {N} angular projects created from scratch, however, was unable to recreate a similar problem. On that matter, Can you provide more info about the project configuration and more info about your environment(`tns-core-modules`, `tns-android`, `tns-ios versions`)? It will also help if you can send us the project or sample one, where the problem can be recreated. For your convenience, I am attaching a GIF file, where it is demonstrated, that the sync of {N} Vue works as expected on my side.
![Screencast 2019-07-23 at 9 30 38 AM](https://user-images.githubusercontent.com/17448734/61688528-eba36b80-ad2d-11e9-8932-3f3d766d85d4.gif)

**Comment by nikoTM** [comment]
@tsonevn happens for me in Angular project as well. I will try to make a minimal project that reproduces this when I have time, but I think it has to do with lazy loaded modules.

**Comment by jbarnabe** [comment]
Would not it be related to HMR and [995](https://github.com/NativeScript/nativescript-dev-webpack/issues/995) ?
Have you tested the `--no-hmr` flag ?

**Comment by nikoTM** [comment]
@jbarnabe seems like exactly what it is for me. At least the end result (the bug itself) is identical.

**Comment by subhaze** [comment]
@jbarnabe that might be it! I felt as if hmr may now be the default in 6 but didn't notice mention of it now being on by default. When I get to work a bit later today I'll try that new flag out to disable it, thanks!

**Comment by jbarnabe** [comment]
@subhaze yes, since {N} 6 HMR is default ! This flag allowed me to return to a functional environment but slower than the HMR.
I hope that the issue that I opened will allow a rapid resolution of this problem.

**Comment by subhaze** [comment]
@jbarnabe that was it! And here I thought I searched well enough through existing issues, thanks jbarnabe!

**Comment by roxart** [comment]
> @jbarnabe that was it! And here I thought I searched well enough through existing issues, thanks jbarnabe!

Hi is it somehow possible to shut this off also in playground?

**Comment by Sunhat** [comment]
Amazing that this has existed for almost 2 years and they still don't care

**Comment by PiyushHM** [comment]
issue is closed without resolution. 
I see the issue of "Reload app on save not working" on NS7 as well for real device. The build get stuck at "Webpack build done!"

**Comment by triniwiz** [comment]
@PiyushHM are you using core or another flavour ?

**Comment by PiyushHM** [comment]
Not using core I guess. How to check that ?

**Comment by triniwiz** [comment]
is it angular, vue, react or svelte ?

**Comment by PiyushHM** [comment]
it is Nativescript-vue. 
Below is dependencies from package.json. if this helps to get more info ...

"dependencies": {
    "@nativescript/core": "^7.1.0",
    "@nativescript/firebase": "^11.1.3",
    "@nativescript/social-share": "^2.0.1",
    "@nota/nativescript-webview-ext": "^7.0.3",
    "@nstudio/nativescript-cardview": "^2.0.1",
    "@triniwiz/nativescript-couchbase": "^1.1.0",
    "@vue/devtools": "^5.3.3",
    "axios": "^0.20.0",
    "lodash": "^4.17.20",
    "moment": "^2.29.1",
    "nan": "^2.14.1",
    "nativescript": "^7.1.1",
    "nativescript-custom-bottomsheet": "^1.0.6",
    "nativescript-exit": "^1.0.1",
    "nativescript-gif": "^5.0.0",
    "nativescript-socketio": "^3.3.1",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-ui-listview": "^9.0.4",
    "nativescript-vue": "^2.8.1",
    "nativescript-vue-devtools": "^1.4.0",
    "urlencode": "^1.1.0",
    "vuex": "^3.5.1"
  },
  "devDependencies": {
    "@babel/core": "^7.11.6",
    "@babel/preset-env": "^7.11.5",
    "@nativescript/android": "7.0.1",
    "@nativescript/ios": "7.1.0",
    "@nativescript/types": "^7.0.0",
    "@nativescript/webpack": "^3.0.4",
    "@types/node": "^14.6.2",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.1.0",
    "eslint": "^7.12.1",
    "eslint-config-airbnb-base": "^14.2.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-vue": "^7.1.0",
    "nativescript-vue-template-compiler": "^2.8.1",
    "nativescript-worker-loader": "~0.12.1",
    "prettier": "^2.1.2",
    "sass": "^1.26.10",
    "typescript": "^3.9.7",
    "vue": "^2.6.12",
    "vue-loader": "^15.9.3"
  }
