### ISSUE TITLE
update Nativescript 6.0

### ISSUE THREAD

**Issue by jagues6** [NativeScript/NativeScript#7571]
This is error and I can't find the solution.

Unable to instantiate activity ComponentInfo{com.alex.bubaloo/com.tns.NativeScriptActivity}: java.lang.ClassNotFoundException: Didn't find class "com.tns.NativeScriptActivity" on path: DexPathList[[zip file "/data/app/com.alex.bubaloo--DJI2qeunZzd20YJSFcyIA==/base.apk"],nativeLibraryDirectories=[/data/app/com.alex.bubaloo--DJI2qeunZzd20YJSFcyIA==/lib/arm64, /data/app/com.alex.bubaloo--DJI2qeunZzd20YJSFcyIA==/base.apk!/lib/arm64-v8a, /system/lib64]]

**Comment by tsonevn** [comment]
Hi @jagues6,
This can be caused by an issue with a plugin, that extends the activity in the application. However, due to the limited information, I can not tell for sure that this is the exact problem on your side. Regarding that, can you provide more info about your problem(send us the full error log) and your environment(CLI, `tns-core-modules`, `tns-android` versions)? Also, it will help if you can send us the project or at least its `package.json`. 
Meanwhile, you can check if this issue is caused by a plugin used in the project.

**Comment by jagues6** [comment]
Package.json
![image](https://user-images.githubusercontent.com/30126746/61766570-ed5d4580-ada6-11e9-972e-a7686074dfe6.png)

**Comment by jagues6** [comment]
Full error

nativescript-plugin-firebase: building for same environment, not forcing prepare.
Project successfully prepared (android)
Configure firebase
Copy D:\ns+vue\buba2\app\App_Resources\Android\google-services.json to D:\ns+vue\buba2\platforms\android\app\google-services.json.
Successfully transferred runtime.js on device 102bdb3.
Restarting application on device 102bdb3...
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to instantiate activity ComponentInfo{com.alex.bubaloo/com.tns.NativeScriptActivity}: java.lang.ClassNotFoundException: Didn't find class "com.tns.NativeScriptActivity" on path: DexPathList[[zip file "/data/app/com.alex.bubaloo-cof5a_osaZLTnKvHlfz6bQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.alex.bubaloo-cof5a_osaZLTnKvHlfz6bQ==/lib/arm64, /data/app/com.alex.bubaloo-cof5a_osaZLTnKvHlfz6bQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.alex.bubaloo/com.tns.NativeScriptActivity}: java.lang.ClassNotFoundException: Didn't find class "com.tns.NativeScriptActivity" on path: DexPathList[[zip file "/data/app/com.alex.bubaloo-cof5a_osaZLTnKvHlfz6bQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.alex.bubaloo-cof5a_osaZLTnKvHlfz6bQ==/lib/arm64, /data/app/com.alex.bubaloo-cof5a_osaZLTnKvHlfz6bQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2844)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6692)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tns.NativeScriptActivity" on path: DexPathList[[zip file "/data/app/com.alex.bubaloo-cof5a_osaZLTnKvHlfz6bQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.alex.bubaloo-cof5a_osaZLTnKvHlfz6bQ==/lib/arm64, /data/app/com.alex.bubaloo-cof5a_osaZLTnKvHlfz6bQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
System.err:     at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
System.err:     at android.app.Instrumentation.newActivity(Instrumentation.java:1216)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2832)
System.err:     ... 11 more

**Comment by tsonevn** [comment]
@jagues6,
Can you send us the {N} CLI(`tns --version`) version?

**Comment by jagues6** [comment]
tns --version of {N} is ### **6.0.2**

**Comment by tsonevn** [comment]
HI @jagues6,
I've tested your case in a sample project with the same configuration, however, I am still unable to recreate the problem. On that matter, try to build the project on your side with ` --log trace` flag (run `tns run android --log trace > out.txt`) and send us the `out.txt` file.

**Comment by jagues6** [comment]
Result **out.txt** file

**Comment by jagues6** [comment]
Result **out.txt** file

[out.zip](https://github.com/NativeScript/NativeScript/files/3432478/out.zip)

**Comment by tsonevn** [comment]
Hi @jagues6,
We reviewed the provided log and found out that this error is caused by the fact that you have special symbols in the path to the project. In your case, this is  Plus(`+`). To solve the problem, remove `+` from the folder's name, that contains this symbol. Also, we have [an issue here](https://github.com/NativeScript/nativescript-dev-webpack/issues/998), where this problem is logged and you can keep track on the issue for further info.

**Comment by ParthMaisheri** [comment]
even i am facing the same issue i dont even have '+' in path.
