### ISSUE TITLE
in my {N} project add printers functionality , which android versions supports in printer ? please suggest me any documents or links, any advice is welcome.

### ISSUE THREAD

**Issue by saravanacs** [NativeScript/NativeScript#7573]
**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NathanaelA** [comment]
@saravanacs - There are several plugins that support printing.   You should always search https://plugins.nativescript.rocks or the marketplace for any plugins...

The entire printer list can be found here: https://plugins.nativescript.rocks/search/printer

I wrote the three of them (Epson, Star, and Zebra) - which are commercial and you can purchase at https://nativescript.tools

The three of them that I wrote, all have custom background network and bluetooth drivers (I don't use the manufacturers driver, as it tend to be very very buggy and bloated.).   In addition my drivers can print any image, barcode and use any font, and all three share the same fluent api to make creating print outs easy and usable against all three.   

I cannot tell you anything about the other printer drivers, as I have never used them...

**Comment by saravanacs** [comment]
@NathanaelA Thanks for your information. one more doubts below android 5.1 version support printer ?

**Comment by NathanaelA** [comment]
@saravanacs - I can't say anything about the other print plugins, but my drivers support both iOS (all versions so far) & Android 4.4+

**Comment by saravanacs** [comment]
@NathanaelA  Okay sir. i want to contact you . Please send me any communication
