### ISSUE TITLE
I used nativescript-videorecorder to record video but it shows denied when I try to trigger my recording method.

### ISSUE THREAD

**Issue by ashhadaimviz** [NativeScript/NativeScript#7586]
Here is my playground link so you can test I try to give permission in android manifest but still it shows denied. Need help 
https://play.nativescript.org/

**Comment by NickIliev** [comment]
@ashhadaimviz there is no Playground demo in the link you've provided (I guess you forgot to press **"Save"**). 

Make sure that you have requested the necessary permissions. If you are still experiencing troubles then the best place to open an issue about it is in the plugin's repository ([here](https://github.com/triniwiz/nativescript-videorecorder/issues))

**Comment by ashhadaimviz** [comment]
> @ashhadaimviz there is no Playground demo in the link you've provided (I guess you forgot to press **"Save"**).
> 
> Make sure that you have requested the necessary permissions. If you are still experiencing troubles then the best place to open an issue about it is in the plugin's repository ([here](https://github.com/triniwiz/nativescript-videorecorder/issues))

sorry for that link. 
Here is the correct one https://play.nativescript.org/?template=play-ng&id=rhYjr2
