### ISSUE TITLE
Event listener for webview logs

### ISSUE THREAD

**Issue by SephReed** [NativeScript/NativeScript#7587]
**Is your feature request related to a problem? Please describe.**
I'm working with webviews.  Something is going wrong in one of them, and without logging it's hard to tell what.

**Describe the solution you'd like**
webView.addEventListener(WebView.ConsoleLogEvent, (data) => console.log(data));

**Describe alternatives you've considered**
Can't imagine anything simpler

**Additional context**
If the feature already exists, it might just need to be added to the docs: 
https://docs.nativescript.org/ui/ns-ui-widgets/web-view

**Comment by lukesUbuntu** [comment]
I currently use nativescript-webview-interface plugin provides bi-directional between webView & 
 platform, its a big help in getting the webview console logs.

https://github.com/shripalsoni04/nativescript-webview-interface

**Comment by tsonevn** [comment]
Hi @SephReed 
In your case, if you need to debug the WebView inside the app, you can use `Chrome Developer Tools` for Android and `Safari` for iOS. Check out the below attached links, where it is described, how to enable WebView debugging for Android and iOS.
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews
https://stackoverflow.com/questions/2767902/what-are-some-methods-to-debug-javascript-inside-of-a-uiwebview

**Comment by SephReed** [comment]
Hmmm.  It appears that even in a fully native app, there is no way to hook into a webview and consume its logs.  That's too bad.  It would help with not only debugging, but also passing out arbitrary string data.

Thank you for links to the current best solution.
