### ISSUE TITLE
Vertical text orientation

### ISSUE THREAD

**Issue by maximus1010101** [NativeScript/NativeScript#7604]
Hello,

How I can do <Label> with orientation text like rotate 90° in css?

**Comment by tsonevn** [comment]
HI @maximus1010101,
You can use the [rotate](https://docs.nativescript.org/api-reference/classes/_ui_label_.label#rotate) property. For further "How to" related question, please use the [SO thread here](https://stackoverflow.com/questions/tagged/nativescript). This repository is used only for bug reporting and feature requests.
