### ISSUE TITLE
[BottomNav] Changing tabs crashes app

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#7608]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0
 - Cross-platform modules: 6.0.2
 - Android Runtime: 6.0.0
 - iOS Runtime: 6.0.0
 - Plugin(s):

**Describe the bug**
Have one tab structure defined in XML. On click I want to change the tabs to something else. Doing so cause the app to crash. 

**To Reproduce**
https://play.nativescript.org/?template=play-tsc&id=qn90jL&v=2
Tap on the `Change` button

**Expected behavior**
To work 😀 

Related to #6967

**Comment by PeterStaev** [comment]
**Workaround**: clear the items of both the bottom nav and the tabstrip before setting the new ones:
```ts
    bottomNav.items = [];
    bottomNav.tabStrip.items = [];
```

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
