### ISSUE TITLE
[BottomNav] Changing tabs does not render the new tab items

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#7609]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.0
 - Cross-platform modules: 6.0.2
 - Android Runtime: 6.0.0
 - iOS Runtime: 6.0.0
 - Plugin(s):

**Describe the bug**
Having some tabs defined in the XML and then changing them from code does not generate new tabs. The tab bar appears to be empty. This is after applying the workaround to overcome #7608 

**To Reproduce**
https://play.nativescript.org/?template=play-tsc&id=BYivzi&v=2
Tap on the `Change` button

**Expected behavior**
To work 😀 

Related to #6967

**Comment by halfnelson** [comment]
Ran into this when adding tests for tabs/bottomnavigation in svelte native. The code calls _addView() for the new tabstripitem's, but the change isn't represented on the screen. backgrounding and then foregrounding the view seems to fix it.

**Comment by dosomder** [comment]
@halfnelson How do you "backgrounding and then foregrounding the view" ? Is there a workaround for this problem?

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
