### ISSUE TITLE
Enable NativeScript to work inside existing native application

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#761]
Lets enable developers to extend their existing native iOS and Android applications and to allow them to create Views inside their existing apps using NativeScript.

This can be a great transition path for them to start using NativeScript without the need to start from scratch.

For 1.6
- [ ] Research how to make NativeScript as a library that can be consumed from native app (for the runtimes and the modules)

After 1.6
- [ ] Research how the communication with the native app will be done.

[Please vote for this feature in our ideas portal.](https://nativescript.ideas.aha.io/ideas/NS-I-59)

**Comment by valentinstoychev** [comment]
Also make sure the steps here will make it available to extend existing PhoneGap app.

**Comment by rodenp** [comment]
This is a really great idea.
Will this enable ionic apps especially ionic 2 & angular2 to be extended?

**Comment by enchev** [comment]
Merged with https://github.com/NativeScript/NativeScript/issues/1746

**Comment by ernadeem** [comment]
Lets enable developers to extend their existing native iOS and Android applications and to allow them to create Views inside their existing apps using NativeScript? Please let me know if it is already available.
