### ISSUE TITLE
[BottomNav] Dynamically generating tabs when the BottomNav has a class applied crashes

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#7611]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.0
 - Cross-platform modules: 6.0.2
 - Android Runtime: 6.0.0
 - iOS Runtime: 6.0.0
 - Plugin(s):

**Describe the bug**
If you dynamically generate tabs when the `BottomNavigation` control has a class applied to it, the applications crashes. 

**To Reproduce**
https://play.nativescript.org/?template=play-tsc&id=GDzvl9&v=2
Tap on `Change` button

**Expected behavior**
To work 😀 

Related to #6967.

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
