### ISSUE TITLE
Application Check for Updates

### ISSUE THREAD

**Issue by seveneye** [NativeScript/NativeScript#7615]
Is there an official way on how to check for updates from playstore or applestore. The should not run unless it is updated.

**Comment by NickIliev** [comment]
@seveneye there is no official way to check for updates programmatically and as far, as I know up to this moment there is no native API that can be used for a similar task. 

Check the threads below for details and possible solutions
- [Android](https://stackoverflow.com/a/25201516/4936697)

- [iOS](https://stackoverflow.com/questions/22329266/can-i-check-app-store-for-updates-programmatically)

**Comment by seveneye** [comment]
thanks!
