### ISSUE TITLE
 Unable to instantiate activity ComponentInfo

### ISSUE THREAD

**Issue by ParthMaisheri** [NativeScript/NativeScript#7625]
after update to 6 

I am getting the following error:
` Unable to instantiate activity ComponentInfo{org.nativescript.Unite/com.tns.NativeScriptActivity}: java.lang.ClassNotFoundException: Didn't find class "com.tns.NativeScriptActivity" on path: DexPathList[[zip file "/data/app/org.nativescript.Unite-N8LvQmyn0YOtygBLHss0Mw==/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.Unite-N8LvQmyn0YOtygBLHss0Mw==/lib/arm, /data/app/org.nativescript.Unite-N8LvQmyn0YOtygBLHss0Mw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]`

**Comment by tsonevn** [comment]
Hi @ParthMaisheri,
Can you provide more info about the problem(send us the full error log) and more info about your environment(CLI, `tns-core-modules`, `tns-android`, `tns-ios` versions)? Also, it will help if you can send us the project or sample one, where the issue can be recreated.

**Comment by ParthMaisheri** [comment]
@tsonevn 
```
tns-core-modules 6.0.4 
tns-android 6.0.1  
```

**Comment by NickIliev** [comment]
@ParthMaisheri check the following threads for possible reasons and solutions:

- https://github.com/NativeScript/NativeScript/issues/7571
- https://github.com/NativeScript/nativescript-dev-webpack/issues/998

As there is not full information provided, we can't say what is causing the issue at your side. Please consider posting the requested information as per "Report a Bug" template:
```
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
<!-- A clear and concise description of what the bug is. Please, explain whether it's a build time error or a runtime error. More detailed logs can be easily obtained by following the instructions in this guide: https://docs.nativescript.org/get-support#how-to-obtain-diagnostic-reports. -->

**To Reproduce**
<!-- Add commands used or steps taken to reproduce the behaviour. -->

**Expected behavior**

**Sample project**
<!-- If possible, provide a link from the [Playground](https://play.nativescript.org) with reproduction of the problem. If not, consider attaching a sample project or link to a repository with such project. -->

**Additional context**
<!-- Add any other context about the problem here. -->

```

**Comment by NickIliev** [comment]
@ParthMaisheri can you try using the `rc` of tns-core-modules

```
rm -rf platforms
npm i tns-core-modules@rc --save
tns run android
```

**Comment by ParthMaisheri** [comment]
@NickIliev this did not work for me

**Comment by NickIliev** [comment]
@ParthMaisheri than please provide [the additional information requested here](https://github.com/NativeScript/ios-runtime/issues/1187) so that we can investigate further.

**Comment by ParthMaisheri** [comment]
Started working after path change.
