### ISSUE TITLE
tns_modules/readable-stream/lib/_stream_writable.js JS ERROR ReferenceError: Can't find variable: process

### ISSUE THREAD

**Issue by Oguzhan1942** [NativeScript/NativeScript#7630]
I am glad for any clue. 

**Getting runtime error:** 
Native stack trace:
1   0x1049b391f NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x1049f9d1f -[TNSRuntime executeModule:referredBy:]
3   0x1043dace3 main
4   0x1087c8541 start
5   0x1
JavaScript stack trace:
1   anonymous@file:///app/tns_modules/readable-stream/lib/_stream_writable.js:57:26
2   evaluate@[native code]
3   moduleEvaluation@[native code]
4   promiseReactionJob@[native code]
5   require@[native code]
6   anonymous@file:///app/tns_modules/readable-stream/writable.js:2:23
7   evaluate@[native code]
8   moduleEvaluation@[native code]
9   promiseReactionJob@[native code]
10  require@[native code]
11  anonymous@file:///app/tns_modules/stream-browserify/index.js:29:26
12  evaluate@[native code]
13  moduleEvaluation@[native code]
14  promiseReactionJob@[native code]
15  require@[native code]
16  anonymous@file:///app/tns_modules/readable-stream/readable.js:1:91
17  evaluate@[native code]
18  moduleEvaluation@[native code]
19  promiseReactionJob@[native code]
20  require@[native code]
21  anonymous@file:///app/tns_modules/stream-http/lib/response.js:3:21
22  evaluate@[native code]
23  moduleEvaluation@[native code]
24  promiseReactionJob@[native code]
25  require@[native code]
26  anonymous@file:///<…>
JavaScript error:
file:///app/tns_modules/readable-stream/lib/_stream_writable.js:57:26: JS ERROR ReferenceError: Can't find variable: process
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: process
at
1   anonymous@file:///app/tns_modules/readable-stream/lib/_stream_writable.js:57:26
2   evaluate@[native code]
3   moduleEvaluation@[native code]
4   promiseReactionJob@[native code]
5   require@[native code]
6   anonymous@file:///app/tns_modules/readable-stream/writable.js:2:23
7   evaluate@[native code]
8   moduleEvaluation@[native code]
9   promiseReactionJob@[native code]
10  require@[native code]
11  anonymous@file:///app/tns_modules/stream-browserify/index.js:29:26
12  evaluate@[native code]
13  moduleEvaluation@[native code]
14  promiseReactionJob@[native code]
15  require@[native code]
16  anonymous@file:///app/tns_modules/readable-stream/readable.js:1:91
17  evaluate@[native code]
18  moduleEvaluation@[native code]
19  promiseReactionJob@[native code]
20  require@[native code]
21  anonymous@file:///app/tns_modules/stream-http/lib/response.js:3:21
22  evalua<…>
NativeScript caught signal 6.
Native Stack:
1   0x1049f884f sig_handler(int)
2   0x108b2bb5d _sigtramp
3   0x1048f4d40
4   0x1088ae01d abort
5   0x1086459d1 __cxa_bad_cast
6   0x108645b6f default_unexpected_handler()
7   0x10706ae2d _objc_terminate()
8   0x108651a2e std::__terminate(void (*)())
9   0x1086514eb __cxa_get_exception_ptr
10  0x1086514b2 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
11  0x10706abfa _objc_exception_destructor(void*)
12  0x1049b3d58 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
13  0x1049f9d1f -[TNSRuntime executeModule:referredBy:]
14  0x1043dace3 main
15  0x1087c8541 start
16  0x1
JS Stack:

**Which platform(s) does your issue occur on?**
IOS

**Extract from package.json:** 
   "nativescript": {
        "id": "org.nativescript.swapcon",
        "tns-android": {
            "version": "5.2.0"
        },
        "tns-ios": {
            "version": "6.0.0"
        }
    },
    "dependencies": {
        "@angular/animations": "~8.1.0",
        "@angular/common": "~8.1.0",
        "@angular/compiler": "~8.1.0",
        "@angular/core": "~8.1.0",
        "@angular/forms": "~8.1.0",
        "@angular/http": "~8.0.0-beta.10",
        "@angular/platform-browser": "~8.1.0",
        "@angular/platform-browser-dynamic": "~8.1.0",
        "@angular/router": "~8.1.0",
        "@mdi/font": "^3.8.95",
        "@types/node": "^12.6.9",
        "@types/parse": "^2.2.7",
        "kinvey-nativescript-sdk": "^4.2.3",
        "moment": "^2.24.0",
        "nativescript-angular": "^8.1.0",
        "nativescript-cardview": "^3.2.0",
        "nativescript-iqkeyboardmanager": "^1.5.1",
        "nativescript-ng-shadow": "^2.1.0",
        "nativescript-nodeify": "^0.8.0",
        "nativescript-plugin-firebase": "~8.2.0",
        "nativescript-sqlite": "^2.3.3",
        "nativescript-swipe-layout": "^1.0.5",
        "nativescript-theme-core": "~1.0.6",
        "nativescript-ui-listview": "^7.0.2",
        "node-sass": "^4.12.0",
        "parse": "^2.6.0",
        "reflect-metadata": "~0.1.13",
        "rxjs": "~6.5.2",
        "tns-core-modules": "^6.0.0",
        "typescript": "~3.4.5",
        "uglifyjs-webpack-plugin": "^2.2.0",
        "zone.js": "~0.9.1"
    },
    "devDependencies": {
        "@angular/compiler-cli": "~8.1.0",
        "@nativescript/schematics": "~0.6.0",
        "@ngtools/webpack": "8.2.0",
        "nativescript-dev-sass": "^1.7.0",
        "nativescript-dev-typescript": "^0.10.0",
        "nativescript-dev-webpack": "^1.0.2"
    },

**ts.config:**
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "types": ["node"],
        "lib": ["es6", "dom", "es2015.iterable"],
        "baseUrl": ".",
        "paths": {
            "~/*": ["src/*"]
        }
    },
    "exclude": ["node_modules", "platforms"]
}

**Comment by NickIliev** [comment]
@Oguzhan1942 it seems that nativescript-nodeify might not be compatible with NativeScript 6. Can you try to remove the plugin and observe if the issue persists? If so, then please try to provide a sample project that can be used for reproduction of your specific case.

**Comment by Oguzhan1942** [comment]
Thanks @NickIliev ! I confirm that after removing the plugin `nativescript-nodify` the error message above disappeared.

**Comment by Oguzhan1942** [comment]
I've reinstalled `nativescript-nodify` (because I need it) and unfortunately I get the same error with `"tns-ios.version": "5.4.2"` and `"tns-core-modules": "^5.4.3"`.

**Comment by NickIliev** [comment]
I think that the issue is not related to the runtime versions (`tns-ios` and `tns-android`) but to the used version of CLI. There was a breaking change related to the hooks which mean that old hooks will fail with a new CLI version. [Here are more details about the issue](https://www.nativescript.org/blog/migrating-cli-hooks-to-nativescript-6.0) and [here](https://github.com/EddyVerbruggen/nativescript-nodeify/issues/62) the issue is logged as a bug in nativescript-nodify.  

@EddyVerbruggen ^^^
