### ISSUE TITLE
TabView can't navigate from item detail

### ISSUE THREAD

**Issue by russk4** [NativeScript/NativeScript#7633]
**Environment**
 - CLI: 5.4.2
 - Cross-platform modules: 5.4.3
 - Android Runtime: 5.4.0
 - iOS Runtime: 5.4.2
 - Plugin(s):

**Describe the bug**
I have extended the NativeScript template for TabView navigation: template-tab-navigation-ng (https://github.com/NativeScript/nativescript-app-templates/tree/master/packages/template-tab-navigation-ng) for use in my own app. Everything works as expected when navigating to the Home tab and then to the item detail view, but I'm unable to navigate any further from that detail view.

I've tried myriad approaches with no luck. When clicking to navigate from the detail view, there is no error; yet there's also no navigation to another page, a further detail view so to speak, with its own corresponding ActionBar and back navigation.

The desired navigation would be from the Home Tab -> Item with ListView -> Item Detail which is a corresponding ListView -> Item Detail Detail which is the in depth item detail view. Or Home Tab -> Item ListView -> Item ListView w/summary detail -> Item Detail

Is this a limitation or am I missing some step?

**To Reproduce**
Use template-tab-navigation-ng and put a ListView as the current item-detail and then try to navigate forward to an item-detail with corresponding ActionBar.

**Expected behavior**

Home Tab -> Item ListView -> Item ListView w/summary detail -> Item Detail -> and perhaps even further navigation with corresponding ActionBar.

**Comment by NickIliev** [comment]
@russk4 please provide a sample app or [demo Playground](https://play.nativescript.org/) that fully reproduces the issue so that we could investigate further.

**Comment by russk4** [comment]
I have updated to NativeScript 6 and started with a fresh template from Sidekick and have been able to achieve the desired navigation forward from an "item detail." Thanks for the timely response.
