### ISSUE TITLE
Can'r run from Xcode framework not found

### ISSUE THREAD

**Issue by cherimo** [NativeScript/NativeScript#7638]
**Environment**
```
  "nativescript": {
    "id": "org.nativescript.myApp",
    "tns-ios": {
      "version": "6.0.1"
    },
    "tns-android": {
      "version": "6.0.1"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "nativescript-angular": "~8.0.0",
    "nativescript-plugin-firebase": "^9.0.4",
    "nativescript-theme-core": "~1.0.6",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.5.0",
    "tns-core-modules": "~6.0.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.0.0",
    "@ngtools/webpack": "~8.0.0",
    "nativescript-dev-webpack": "~1.0.0",
    "typescript": "~3.4.0"
  },
```

**Describe the bug**
When I tried to run the app via xCode I get following error: "framework not found MDFInternationalization".
I have tested the app with the "Preview App" which works all fine on both platforms Android and iOS.

**To Reproduce**
tns create myApp --ng
> create platform
> prepare ios
> run it with xcode

**Expected behavior**
Run the app on device

**Sample project**
tns create myApp --ng
> create platform
> prepare ios
Run on device

**Additional context**

**Comment by NickIliev** [comment]
@cherimo The `tns prepare` command is not building the project but only preparing a base native project.

To build the NativeScript project run either `tns build` or `tns run` and then you can start the produced xcworkspace via XCode

e.g.,
```
tns create <my-project-name> --ng
cd base-ng-app
tns build ios

 // open platforms/ios/<my-project-name>.xcworkspace in XCode and deploy
```

**Comment by PetroSuch** [comment]
I run my project by tns run ios and i get error lb:framework not found AmPopTip
i see the framework in my folder Pods
