### ISSUE TITLE
CSS Animation won't trigger by Android back-button Event using Angular

### ISSUE THREAD

**Issue by DarioDomiDE** [NativeScript/NativeScript#7639]
**Environment**
 - Nativescript 6.0.2
- Android Runtime: latest
- Angular 8

**Describe the bug**
When I execute a css animation by set a class for example "active" via a tap-event, the css animation is triggered like excepted, so everything works fine. But when I set this class by an Android an back-button event, no animation is triggered. Even though the css class is set. When doing an animation via code (for example `this.someElement.nativeElement.animate({ translate: { x: 0, y: posY}, duration: 300 });`), it works fine.

**To Reproduce**

app.component.ts
```
    application.android.on(application.AndroidApplication.activityBackPressedEvent, (args: any) => {
      this.ngZone.run(() => {
        args.cancel = true;
        this.userService.onAndroidBackTriggered(path);
      });
    };
```

home.component.ts
```
ngOnInit() {
  this.userService.androidBackTriggered.subscribe((path: string) => this.onAndroidBackTriggered(path));
}

public clickHistory(): void {
  this.isHistoryOpen = !this.isHistoryOpen;
}

private onAndroidBackTriggered(path: string): void {
  this.isHistoryOpen = true;
}
```

home.component.html
```
    <GridLayout id="history" [class.active]="isHistoryOpen" [class.inactive]="!isHistoryOpen">
         <Image src="..." id="history_shadow"></Image>
         <some-element (tap)="clickHistory()"></some-element>
    </GridLayout>
```

home.component.scss
```
#history {
  &.active #history_shadow {
     animation-name: hideShadow;
     animation-duration: 0.6s;
     animation-fill-mode: forwards;
  }
  .inactive #history_shadow {
     animation-name: showShadow;
     animation-duration: 0.6s;
     animation-fill-mode: forwards;
  }

  @keyframes showShadow {
    from { opacity: 0; }
    to { opacity: 1; }
  }
  @keyframes hideShadow {
    from { opacity: 1; }
    to { opacity: 0; }
  }
}

```

**Expected behavior**
CSS Animation should work.

**Sample project**
Not setup'ed yet. Needed?

**Comment by NickIliev** [comment]
I think you are dealing with a race condition where the native lifecycle is faster than the CSS change. This is kinda expected as the back button event is immediately taking action leaving no time for the above UI abstraction to re-render and re-apply the CSS changes.
