### ISSUE TITLE
Create installation package for NativeScript on Mac and Windows

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#764]
One of the biggest getting started hurdles for new developers is the installation of the NativeScript dependencies. The list of libraries to install required by the mobile vendors is big and many things can go wrong.

Lets create an installer that will install all the needed dependencies and will make all the needed changes in order NativeScript to run on a Windows or Mac machine.

[Please vote for this features in our ideas portal.](https://nativescript.ideas.aha.io/ideas/NS-I-60)

**Comment by jlooper** [comment]
I think this is the best idea so far!! It will just have to be maintained by someone as the bits and pieces change quickly.

**Comment by atul221282** [comment]
Please create the installer as I have nearly spent two days and cannot get native new release 1.3.0 to work at all this is getting really annoying now

**Comment by emiloberg** [comment]
> I think this is the best idea so far!! 

Agree! Setting up (android) environment is a burden.

Be careful though. Many developers most probably have some of the tools installed needed to do {N} development, and they may have them installed in unorthodox ways, like actually having the Android SDK installed, but not in the regular place, different Java versions, installing NPM with or without the need for `sudo`, etc. And the last thing we want to do is to screw up the user's environment for developing other stuff.

**Comment by atul221282** [comment]
Agree..I have got so much love for this framework but amazed that such a nice thing doesn't have a basic packages...well any ways I am going to open an issue with nativescript installation coz i think something is definitely wrong with the new version. I think it expect user to have files at certain location and folder

**Comment by burkeholland** [comment]
:+1:

**Comment by ligaz** [comment]
Here is one line installation for Mac OS X:
```sh
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/NativeScript/nativescript-cli/master/setup/native-script.rb)"
```
Please give it a try and share any feedback.

**Comment by atul221282** [comment]
well Let say if I format my pc and run that command ( I am going to format it anyways), will that install it? Is there any prerequisite before running this command?

**Comment by valentinstoychev** [comment]
No, there is no prerequisite. Please give it a try.

**Comment by atul221282** [comment]
I wish I could but I have windows 8 :(

**Comment by ligaz** [comment]
[Here](http://boxstarter.org/package/nr/url?https://raw.githubusercontent.com/NativeScript/nativescript-cli/totev/setup-win/setup/native-script.txt) is the installation for Windows:
```
http://boxstarter.org/package/nr/url?https://raw.githubusercontent.com/NativeScript/nativescript-cli/totev/setup-win/setup/native-script.txt
```
Any feedback is more than welcome.

**Comment by atul221282** [comment]
I tried the Boxstarter.WebLaunch exe but getting the error attached in link below
http://pastebin.com/Gc2Xym89

**Comment by camilleeyries** [comment]
@ligaz your one command line installation is good :-D

**Comment by teobugslayer** [comment]
@atul221282, I am trying to reproduce the issue. What OS are you using? Which browser are you using?

**Comment by teobugslayer** [comment]
@atul221282,

I am still researching the issue. It seems that when you download the ClickOnce setup using Internet Explorer (I know, I know) or Edge (for Windows 10), it works well. Downloading using Chrome does not work.

**Comment by atul221282** [comment]
it's all good @teobugslayer . I will check nd see if it works in IE for me. Will update you ASAP.

Regards

**Comment by burkeholland** [comment]
@ligaz This is perfect! I had no issues whatsoever and the install process was clear. Can we put this in the docs yesterday at least for Mac?

**Comment by ligaz** [comment]
We are doing some final testing on those scripts. Once verified we will feature them on the site (@valentinstoychev) and the docs as well. I guess @tjvantoll can point to them in the getting started tutorial as well.

**Comment by enchev** [comment]
Closing in favor of https://github.com/NativeScript/NativeScript/issues/1556
