### ISSUE TITLE
Different behaviour of navigatingTo in a frame in ios and android

### ISSUE THREAD

**Issue by ineiti** [NativeScript/NativeScript#7642]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.0.2 version and is up to date.
✔ Component tns-core-modules has 6.0.5 version and is up to date.
⚠ Update available for component tns-android. Your current version is 6.0.0 and the latest available version is 6.0.1.
✔ Component tns-ios has 6.0.1 version and is up to date.

**Describe the bug**
The behaviour of the `navigatingTo` event is not the same for Android and iOS in the case of a `visibility="collapse"` frame-element.

For Android, a frame that is hidden using `visibility="collapse"` will not have its `navigatingTo` called, while the same frame on iOS will have a call to `navigatingTo`

**To Reproduce**

```bash
tns create collapse --template tns-template-tab-navigation-ts
cd collapse
perl -pi -e "s/^\}$/    console.log(\"home-items-page\");\n}\n/" app/home/home-items-page.ts 
cat <<'EOF' > app/app-root.xml
<StackLayout>
<TabView androidTabsPosition="bottom">
    <TabViewItem title="Search" ios:iconSource="res://tabIcons/search" android:iconSource="res://search">
        <Frame defaultPage="search/search-page"></Frame>
    </TabViewItem>
</TabView>
<TabView androidTabsPosition="bottom"
         visibility="collapse">
    <TabViewItem title="Home" ios:iconSource="res://tabIcons/home" android:iconSource="res://home">
        <Frame defaultPage="home/home-items-page"></Frame>
    </TabViewItem>
</TabView>
</StackLayout>
EOF

tns run android &
tns run ios
```

**Expected behavior**
Neither of them shows the `console.log` output.

**Sample project**
https://github.com/c4dt/collapse

**Comment by NickIliev** [comment]
@ineiti you can use `visibility="hidden"` (instaed of `collapse`) and the navigation events will be triggered on both platforms.

The difference is coming from what collapse is doing vs what hidden is doing and what stands behind `Frame` on iOS

```
Const collapse
collapse: BaseVisibility
Defined in ui/enums/enums.d.ts:260
The view is not visible and won't take place in the layout.

Const hidden
hidden: BaseVisibility
Defined in ui/enums/enums.d.ts:265
The view is not visible but will take place in the layout.
```

On iOS behind `Frame`, we have an iOS `NavigaitonController` and even if you set `collpase` this is an element that can't be removed. So that said, there is a difference in what `collpase` will do with the `Frame` element on iOS but the difference is expected due to the core iOS implementation of the NavigationController. To align both use `hidden` instead of `collpase`

**Comment by ineiti** [comment]
@NickIliev - thanks for the answer. I would still file this as a bug, because it is not expected behaviour to do different things on iOS and Android. If I use a cross-platform framework, I don't want it to do this...

But anyway, I'll use `visibility="hidden"` now...

**Comment by NickIliev** [comment]
@ineiti it is more of limitation than a bug as there is the native element is behaving differently depending on where it is removed from the visual tree or just hidden.
