### ISSUE TITLE
HMR doesn't starts app

### ISSUE THREAD

**Issue by ishaqueahmed-mev** [NativeScript/NativeScript#7645]
Hello,

After updating the app to NS v6, the app is not starting, it only starts till the splash screen nd then crashes without any error.

Also the cone just shows this for HMR : 
Hot Module Replacement Enable. Waiting for signal.

Please someone guide me as to what do I need to do further to make the app working again...

Thanks.

**Comment by NickIliev** [comment]
@ishaqueahmed-mev try to reset the connection to the device (physically plug/unplug the device or restart the simulator) and then do the following:

```
tns devices
```

It should output the connected device. If the device is successfully connected try the following:
```
rm -rf platforms
tns run android --log trace
```

You can also try to run the app without HMR
```
tns run android --no-hmr  --log trace
```

The `--log trace` flag will provide verbose information which you can use to investigate what is causing the issues.

**Comment by ishaqueahmed-mev** [comment]
@NickIliev the issue is still there, when I run the app for the first time, it shows the splash screen and then stops, and if I make any changes in code , it reloads and works proper.

Also this issue is only in iOS, and I haven't checked in android yet.

**Comment by NickIliev** [comment]
@ishaqueahmed-mev post the content of your `package.json` and the version of NativeScript CLI .. if possible please send us a demo project that is causing the issue on your side

**Comment by ishaqueahmed-mev** [comment]
Hello,

it seems to work fine now, after I ran with --no-hmr command.
but then after the system got restarted, it works fine now.

Thanks for the help.
