### ISSUE TITLE
Modules that have names ending in `.page` are not found

### ISSUE THREAD

**Issue by surdu** [NativeScript/NativeScript#7646]
**Describe the bug**
If a module name ends in `.page` (I'm guessing `.<anything>`) you'll not be able to use it, at least not as a Frame's `defaultPage`.

Please see this [Playground example](https://play.nativescript.org/?template=play-js&id=lfBxe9&v=1).

**To Reproduce**
Run the Playground example.

**Expected behavior**
The app starts without crash, showing the `home/home.page` page.

**Additional context**
I have a {N} 5.0 project and I preferred the `.page` suffix instead of the `-page` suffix for my pages.

**Comment by vakrilov** [comment]
Confirmed. The [`sanitizeModuleName`](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/builder/module-name-sanitizer.ts#L10-L15) method removes the part after the last dot. So `main.page` is "sanitized" to `main`. 

Probably the best approach will be to have a list of known extensions and remove the part after the dot only if it matches any of the known extensions.

**Comment by surdu** [comment]
That looks pretty straight forward to fix. I could give it a try if nobody already started working on it.

**Comment by surdu** [comment]
Fixed it 😃

**Comment by surdu** [comment]
@vakrilov Was this not published yet? I recall testing the published version 6 and this was working. Now it's not working again.
