### ISSUE TITLE
Nativescript 6 - page.showModal does not work anymore

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/NativeScript#7647]
After migrating my app to NS 6, the page.showModal does not work anymore.

I am calling it like: 
``page.showModal('/components/login/login', {
                context: null, 
                closeCallback: (res: boolean) => {
                ... some code
            }, 
            fullScreen: true});``

I am getting the following error:
**Argument of type '"components/login/login"' is not assignable to parameter of type 'ViewBase'**

I looked through the documentation and I can't see what I am doing differently.  

What is the proper way of making this call?

Thanks.

**Comment by rahadur** [comment]
it's working properly follow the document. i just work with it.  After use `ShowModalOptions` option my modal are working properly. one more thing just close the terminal and restar your app. 

```javascript
export function openModal(args) {
    const mainView: Button = <Button>args.object;
    const option: ShowModalOptions = {
        context: { username: "test_username", password: "test" },
        closeCallback: (username, password) => {
            // Receive data from the modal view. e.g. username & password
            alert(`Username: ${username} : Password: ${password}`);
        },
        fullscreen: true
    };
    mainView.showModal(modalViewModulets, option);
}
````

**Comment by NickIliev** [comment]
@dpdragnev are you still experiencing this issue? If so, can you please provide [a Playground demo](https://play.nativescript.org/) that uses your app structure

**Comment by dpdragnev** [comment]
Thank you @NickIliev .  It is working now.
