### ISSUE TITLE
Can't build project after update

### ISSUE THREAD

**Issue by kelvinharleyy** [NativeScript/NativeScript#7648]
**Environment**
 - CLI: 6.0.2
 - Cross-platform modules: 6.0.5
 - Android Runtime: 6.0.0

**Describe the bug**
After i update NativeScript to 6.0, when build the app in Android Platform it keep always show error mesage :

`
[19-08-07 00:10:15.053] Build failed. cp: no such file or directory: F:\Project\VSID\app\App_Resources\Android\src\*
`

I already tried clean Project, remove node_modules+hook+platform then `npm install` but the problem still the same

Here is my package.json :

```
{
  "nativescript": {
    "id": "org.nativescript.VSID",
    "tns-ios": {
      "version": "6.0.1"
    },
    "tns-android": {
      "version": "6.0.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "axios": "0.19.0",
    "nativescript-background-http": "4.0.0",
    "nativescript-carousel": "6.1.0",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-vue": "~2.4.0",
    "tns-core-modules": "~6.0.0"
  },
  "devDependencies": {
    "@babel/core": "~7.1.0",
    "@babel/preset-env": "~7.1.0",
    "babel-loader": "~8.0.0",
    "nativescript-dev-webpack": "~1.0.0",
    "nativescript-vue-template-compiler": "~2.4.0",
    "node-sass": "^4.7.1",
    "vue-loader": "~15.4.0"
  },
  "gitHead": "acc336cdf930533cd11ba8c8e4dcf350f2c5d818",
  "readme": "NativeScript Application",
  "author": "Harley"
}
```

I am using NativeScript-Vue to develop the App

**Comment by ashhadaimviz** [comment]
I had same issue earlier when I migrated my project to cli 6.0.2. In my case I addese these in main.ts

import { enableProdMode } from '@angular/core';
enableProdMode();

as well as remove platform
tns platform remove android
tns platform add android 

It helped me give it a try and let me know the result

**Comment by NickIliev** [comment]
@kelvinharleyy try to migrate the project resource directory by running the following command:

```
rm -rf platforms
tns resources update
tns migrate
tns run android
```

**Comment by kelvinharleyy** [comment]
thanks for the advice @NickIliev @ashhadaimviz
