### ISSUE TITLE
Execution failed for task ':app:runSbg'. > Process 'command 'C:\Program Files\Java\jdk1.8.0_211\bin\java.exe'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by ashhadaimviz** [NativeScript/NativeScript#7650]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.2
 - Cross-platform modules: 6.0.1
 - Android Runtime:6.0.0

**Describe the bug**
After migrating my project to cli 6.0.2 I cant build or run my project in android although it works perfectly when I preview it using tns preview --bundle or using Native-script Sidekick 

**To Reproduce**
I exactly don't know what will reproduce it but I migrated my project is all that I think may cause this problem

When I run 
tns run android (to preview it on my emulator) it works fine till 70% and then shows this error -> below in picture 
![image](https://user-images.githubusercontent.com/52818140/62619110-69bb6100-b92f-11e9-9e0b-77a4dc6bc778.png)

**Comment by NickIliev** [comment]
@ashhadaimviz I've noticed that you are using `nativescript-pro-ui` suite which was deprecated a while ago. [Migrate to the split UI plugins](https://docs.nativescript.org/ui/professional-ui-components/migration) (e.g. `nativescript-ui-listview`, 'nativescript-ui-sidedrawer') and also make sure you have updated all of your dependencies to ones that are compatible with NativeScript

**Comment by ashhadaimviz** [comment]
Thank you @NickIliev  it is working now
