### ISSUE TITLE
two versions of App version

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#7657]
At  [Market place](https://market.nativescript.org/plugins/nativescript-app-version)
There are two versions app version next to each other:
1. tns plugin add nativescript-app-version
and 
2.tns plugin add nativescript-appversion

It is not clear if this is a mistake, what is the difference.

**Comment by elena-p** [comment]
Hi @jokro,
It seems that there are two plugins published to npm:

1.  nativescript-appversion:
     - https://market.nativescript.org/plugins/nativescript-appversion
     - https://www.npmjs.com/package/nativescript-appversion
     - https://github.com/eddyverbruggen/nativescript-appversion

2. nativescript-app-version
     - https://market.nativescript.org/plugins/nativescript-app-version
     - https://www.npmjs.com/package/nativescript-app-version
     - https://github.com/code0wl/nativescript-appversion (this is a fork of the first one and has no commits for the last 2 years)

I would suggest you to use the first one, as it is widely used and was updated 2 months ago.

**Comment by jokro** [comment]
Thx. It would be nice to have this info on the marketplace...Op 8 aug. 2019 09:15 schreef Elena Hristova <notifications@github.com>:Hi @jokro,
It seems that there are two plugins published to npm:

nativescript-appversion:
https://market.nativescript.org/plugins/nativescript-appversionhttps://www.npmjs.com/package/nativescript-appversionhttps://github.com/eddyverbruggen/nativescript-appversion

nativescript-app-version
https://market.nativescript.org/plugins/nativescript-app-versionhttps://www.npmjs.com/package/nativescript-app-versionhttps://github.com/code0wl/nativescript-appversion (this is a fork of the first one and has no commits for the last 2 years)

I would suggest you to use the first one, as it is widely used and was updated 2 months ago.
