### ISSUE TITLE
Rename cssClass property to just class

### ISSUE THREAD

**Issue by ligaz** [NativeScript/NativeScript#766]
Let's consider renaming `cssClass` property to just `class` to better align with existing standards.

<img width="476" alt="screen shot 2015-09-17 at 21 24 00" src="https://cloud.githubusercontent.com/assets/19437/9942211/896f1fd0-5d82-11e5-82c4-bac08351982b.png">

**Comment by tjvantoll** [comment]
:+1:

I've always thought `cssClass` was an odd name. I should've asked for this myself a while ago.

**Comment by ligaz** [comment]
We should note that on the JavaScript side it is called `className`.

**Comment by manijak** [comment]
Reminds me of .net WebForms :)  But ```class```is better.
```xml
<asp:TextBox id="TextBox1" ForeColor="Red" CssClass="class1" />

**Comment by enchev** [comment]
I've made it just because the new picture of @akorchev! :)

**Comment by akorchev** [comment]
Now rename the JavaScript `cssClass` property to `className` (or deprecate cssClass in favor of className).

**Comment by enchev** [comment]
@akorchev Done!

**Comment by akorchev** [comment]
!!

**Comment by akorchev** [comment]
I know that I am pushing this bug what about `tap=""` vs `ontap=""`? The `on` prefix is something web developers understand well.

**Comment by enchev** [comment]
@akorchev Here you go:https://github.com/NativeScript/NativeScript/commit/36036c55b1ad7085d612d98251b03b4dafbcf9bf :)

**Comment by tjvantoll** [comment]
Wow, this is awesome! @akorchev You should keep asking for things :)

**Comment by hshristov** [comment]
@enchev Now we need to do the hard work to describe this change in the documentation & in help articles (cssClass rename, tap -> onTap). I'm marking this as a breaking change because if someone have by any chance exposed his event as 'onEvent' in 1.3 from 1.4 he will need to use 'ononEvent' in the XML.

**Comment by enchev** [comment]
Just to clear what I've done in my pull request to avoid further confusion:
- `cssClass` property is not removed and you can still use it from both XML and JavaScript
- I've added new custom attribute `class` for all view that can be used only from XML
- event names are not removed or renamed and you can still use `tap`, `doubleTap`, etc.:
```XML
  <Button tap="myTap" />
```
Now you can also use more familiar to web devs syntax with `on` prefix:

```XML
  <Button ontap="myTap" />
```
Both are valid!

**Comment by enchev** [comment]
I've updated the docs to use `class` instead `cssClass` and I've added [special section](https://github.com/NativeScript/docs/blob/production/ui-with-xml.md#html-like-syntax) to our declarative UI with XML article.
