### ISSUE TITLE
Error Attempted to assign to readonly property when updating the view model.

### ISSUE THREAD

**Issue by alexisconsuegra** [NativeScript/NativeScript#7663]
**Describe the bug**
I get error Attempted to assign to readonly property when updating the view model. viewProducts[i].selected = true;

Here is the UI

    <Page  class="page"  navigatingTo="onNavigatingTo"   xmlns="http://schemas.nativescript.org/tns.xsd">

      <ActionBar class="action-bar">
    <NavigationButton tap="onBackButtonTap" android.systemIcon="ic_menu_back" text="Back"/>
    <Label class="action-bar-title" text="Selection"></Label>
    <ActionItem tap="onSave" visibility="{{ processing ? 'collapse' : 'visible' }}"
      ios.systemIcon="3" ios.position="right"
      android.systemIcon="ic_menu_save" android.position="actionBar"></ActionItem>
  </ActionBar>

      <GridLayout class="list-group-item" rows="auto,250,auto" columns="*">
    <StackLayout row="0" col="0" class="section">
      <Label class="m-10 h2" text="Selections" verticalAlignment="top" ></Label>
    </StackLayout>
    <ListView row="1" col="0" id="listView" items="{{ products }}" itemTap="onProductTap" class="list-group">
      <ListView.itemTemplate>
        <StackLayout class="{{ selected ? 'selectedProduct' : '' }}" >
          <GridLayout class="list-group-item" rows="auto" columns="40,*">
            <Label id="active" row="0" col="0" class="page-icon fa" text="&#xf05d;" visibility="{{ selected ? 'visible' : 'collapsed' }}" />
            <Label id="expired" row="0" col="0" class="page-icon fa" text="&#xf10c;" visibility="{{ selected ? 'collapsed' : 'visible' }}" />
            <StackLayout row="0" col="1">
              <Label text="{{ title }}" class="{{ selected ? 'selectedheader' : 'header' }}" />
              <Label class="boldtext" text="{{ description }}" />
            </StackLayout>
          </GridLayout>
        </StackLayout>
      </ListView.itemTemplate>
    </ListView>
    <StackLayout row="2" col="0">
      <Button text="Select" class="btn btn-primary" tap="onSave" />
    </StackLayout>
  </GridLayout>
</Page>

The View Model
 
    const observableModule = require("tns-core-modules/data/observable");

    module.exports = function MyViewModel() {
    const viewModel = new observableModule.fromObject({
        products: [
            {
                selected: false,
                id: 1,
                title: "Title 1",
                description: "Description 1",
                length: 12,
                active: true
            },
            {
                selected: true,
                id: 2,
                title: "Title 2",
                description: "Description 2",
                length: 3,
                active: true
            },
            {
                selected: false,
                id: 3,
                title: "Title 3",
                description: "Description 3",
                length: 1,
                active: true
            }
        ]
    });

    return viewModel;

    };
    // End MyViewModel

The JS Controller

    const MyViewModel = require("./myviewmodel");
    let listingId;
    let viewModel;

    exports.onNavigatingTo = function onNavigatingTo(args) {
    const page = args.object;
    const context = args.context;

    listingId = context.listingId;
    viewModel = new MyViewModel();

    page.bindingContext = viewModel;
    };

    exports.onProductTap = function onProductTap(args) {
    const view = args.view;

    const tapProduct = view.bindingContext;

    console.log(`Product ${tapProduct.id} is selected. For Listing ${listingId}`);

    const viewProducts = viewModel.get("products");

    console.log(viewProducts);

    for (const i = 0; i < viewProducts.length; i++) {
        if (viewProducts[i].id == tapProduct.id) {
            console.log(`Product ${viewProducts[i].id} is selected.`);
            viewProducts[i].selected = true; // Error Attempted to assign to readonly property.
        }
        else {
            console.log(`Product ${viewProducts[i].id} is NOT selected.`);
            viewProducts[i].selected = false; // // Error Attempted to assign to readonly property.
        }
    }

    viewModel.set("products", viewProducts);

    };

**Comment by NickIliev** [comment]
@alexisconsuegra change
```JavaScript
for (const i = 0; i < viewProducts.length; i++) { 
    // more code follows here
}
```

to

```JavaScript
for (let i = 0; i < viewProducts.length; i++) { 
    // more code follows here
}
```

**Comment by alexisconsuegra** [comment]
Thanks.
