### ISSUE TITLE
[BottomNav][iOS] Changing tabs programatically messes up styles

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#7667]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.0
 - Cross-platform modules: 6.0.0
 - Android Runtime: 6.0.0
 - iOS Runtime: 6.0.0
 - Plugin(s):

**Describe the bug**
When you change the `selectedIndex` programatically the tab actually changes but the styles are not applied, so visually the old tab remains selected and the new one looks like unselected. Works as expected on android. 

**To Reproduce**
https://play.nativescript.org/?template=play-tsc&id=ill2KK 
tap on button in the action bar

**Expected behavior**
Styles to be applied correctly. 

**Sample project**

**Additional context**

Related to #6967

**Comment by ycherniavskyi** [comment]
The same happens when `Label` and `Image` elements used inside `TabStripItem` - https://play.nativescript.org/?template=play-tsc&id=kI4O0n&v=2

And unfortunately, it is reproduced under the last NS 6.2 release.
