### ISSUE TITLE
Using HMR with a modal view breaks livesync

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/NativeScript#7668]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.3
 - Cross-platform modules: 6.0.6
 - Android Runtime: 6.0.1
 - iOS Runtime: 6.0.2

**Describe the bug**
Similar to [this](https://github.com/NativeScript/nativescript-angular/issues/1854) issue but calling the close callback still works. The issue is that the modal's content is not changed accordingly to the changes and is not closed.

**To Reproduce**

- Open any modal view
- Make changes to that modal views xml
- Save the changes and wait for hmr to livesync the changes

**Expected behavior**
The modal view is closed during hmr

**Comment by zbranzov** [comment]
The fix is released in nativescript-angular@8.2.1
