### ISSUE TITLE
Change Android navigation and tabs title color

### ISSUE THREAD

**Issue by calebeaires** [NativeScript/NativeScript#767]
On this exemple, NativeScript dont change the text color from title bar, and title tabs bar.
```
    <Page.actionBar>
        <ActionBar title="Temas" style="background-color:blue;color:#fff">
        </ActionBar>
    </Page.actionBar>
```
Or

```
    <TabView>
        <TabView.items>
            <TabViewItem title="Questions" style="background-color:blue;color:#fff">
                <TabViewItem.view>
                    <GridLayout>
                        <ListView items="{{ items }}">
                            <ListView.itemTemplate>
                                <Label cssClass="cat" text="{{ question }}" textWrap="true" />
                            </ListView.itemTemplate>
                        </ListView>
                    </GridLayout>
                </TabViewItem.view>
            </TabViewItem>
   </TabView>
```

**Comment by bradmartin** [comment]
@N3ll - do you think this will make it in the 1.5 release? If not, what is the native code to setBackgroundColor for the tabview? I'm a web dev and I have no idea how to figure out the abstraction to do this as someone pointed out it was possible via the native options on another the forums related to this.

**Comment by sitefinitysteve** [comment]
This is pretty important for us as well... we can't match the app to the designers mockup, so we can't complete it to deploy at all.

**Comment by calebeaires** [comment]
All app samples on NativeScript shows how to change navigation style, but only on iOS.

**Comment by bradmartin** [comment]
Until there is an API or support for CSS to apply to the tabs, you can create a styles.xml file in your App_Resources/Android/values folder with the following and it should at least change the background of your TabView.

            
    <item name="windowNoTitle">true</item>
    
    <item name="windowActionBar">false</item>
    
    
    <item name="colorPrimary">@color/primaryColor</item>
    
    <item name="colorPrimaryDark">@color/primaryColorDark</item>
    
    <item name="colorAccent">@color/accentColor</item>
    


    <item name="actionBarTabStyle">@color/primaryColor</item>
    <item name="actionBarTabBarStyle">@color/primaryColor</item>

Also make sure you have those colors defined in a colors.xml file in the same folder. It's working for my app, I can't get the ActionBar to style but the TabView should work. Maybe someone more familiar with Android styling can help out.

**Comment by sitefinitysteve** [comment]
@N3ll These things are just so key right now...can you guys maybe throw us a bone and do like a 1.4.4 or 1.4.5 that exposes\fixes actionbar\tab styling?

**Comment by vakrilov** [comment]
@sitefinitysteve @calebeaires 
Styling the ActionBar and TabBar colors is something we are currently working on for the 1.5 milestone. Currently - you should be able to set only the background-color of the action bar for Android.

That said you can set some of the colors by accessing the native Android views and working on them directly. Check out [this gist](https://gist.github.com/vakrilov/3a6d293984c2c00c7256) to see how to do that.

Hope that helps for now.

**Comment by vakrilov** [comment]
After the #999 PR here are the styling options:
**ActionBar**
* `color` (CSS) - the title font color.
* `background-color` (CSS) - background color of the ActionBar/NavigationBar.

**TabView**
* `color` (CSS) - the text color used for the tab items and the content(as color is inherited).
* `background-color`(CSS) - background color of the **content** of the TavView.
*  `tabsBackgroundColor` (property of the TabView) - background color of the **tab items**.
* `selectedColor` (property of the TabView) - accent color for the selected tab-item. This is the text color in iOS and the color of the selection indicator in Android.

**Comment by calebeaires** [comment]
Amazing!

**Comment by alexrainman** [comment]
Yes :)

**Comment by bradmartin** [comment]
What @calebeaires said. :) can't wait to try this.

**Comment by sitefinitysteve** [comment]
Can't wait for 1.5 now!

**Comment by rclai** [comment]
Also how do you change the color of the ellipses when you have these:

```xml
<ActionBar.actionItems>
        <ActionItem text="Edit Room" android.position="popup" />
        <ActionItem text="Add Device" android.position="popup" />
        <ActionItem text="Add Room" android.position="popup" />
        <ActionItem text="Log Out" tap="logOut" android.position="popup" />
      </ActionBar.actionItems>
```

**Comment by vakrilov** [comment]
@rclai 
You can change the color of the action items by modifying the `styles.xml` file with the android themes (located at `[project]\App_Resource\Android\values`).
I have updated the [gist](https://gist.github.com/vakrilov/3a6d293984c2c00c7256#file-app_resources-android-values-styles-xml-L5) to include that.

**Comment by rclai** [comment]
Thanks @vakrilov.

**Comment by dianikol** [comment]
Is it possible to change the background color per tab?
