### ISSUE TITLE
After upgrading to NativeScript CLI 6.0.3 tab-based navigation page is blank  

### ISSUE THREAD

**Issue by Oguzhan1942** [NativeScript/NativeScript#7674]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.3
 - Cross-platform modules: 6.0.6
 - iOS Runtime: 6.0.2
 - Plugin(s): package.json
   "nativescript": {
        "id": "org.nativescript.swapcon",
        "tns-ios": {
            "version": "6.0.2"
        }
    },
    "dependencies": {
        "@angular/animations": "~8.1.0",
        "@angular/common": "~8.1.0",
        "@angular/compiler": "~8.1.0",
        "@angular/core": "~8.1.0",
        "@angular/forms": "~8.1.0",
        "@angular/http": "8.0.0-beta.10",
        "@angular/platform-browser": "~8.1.0",
        "@angular/platform-browser-dynamic": "~8.1.0",
        "@angular/router": "~8.1.0",
        "@mdi/font": "^3.8.95",
        "@nstudio/nativescript-cardview": "^1.0.0",
        "kinvey-nativescript-sdk": "^4.2.3",
        "moment": "^2.24.0",
        "nativescript-angular": "^8.1.0",
        "nativescript-iqkeyboardmanager": "^1.5.1",
        "nativescript-ng-shadow": "^2.1.0",
        "nativescript-plugin-firebase": "9.0.2",
        "nativescript-sqlite": "^2.3.3",
        "nativescript-swipe-layout": "^1.0.5",
        "nativescript-theme-core": "~1.0.6",
        "nativescript-ui-listview": "7.0.0",
        "reflect-metadata": "~0.1.13",
        "rxjs": "^6.3.3",
        "tns-core-modules": "~6.0.0",
        "uglifyjs-webpack-plugin": "^2.2.0",
        "zone.js": "^0.9.1"
    },
    "devDependencies": {
        "@angular/compiler-cli": "8.0.0",
        "@nativescript/schematics": "~0.6.0",
        "@ngtools/webpack": "8.0.0",
        "@types/node": "^12.6.9",
        "nativescript-dev-webpack": "^1.0.3",
        "node-sass": "4.12.0",
        "typescript": "3.4.5"
    }

**Describe the bug**
In my project I have created a login with a tab-base navigation according to the [instruction](https://www.nativescript.org/blog/implementing-a-login-for-nativescript-apps-with-tab-based-navigation). After I was upgrading and migrating my app to 6.0, the tab-base page after logging in is now fully blank, even without the tabview displayed. Unfortunately the log with option `--log trace` doesn't provide any useful message as error or likewise.

**Expected behavior**
Tab-based navigation page  should be displayed as it was working with cli version 5.

I am glad about any help. 

Thanks.

**Comment by tsonevn** [comment]
Hi @Oguzhan1942,
I tested the described scenario with the [sample project](https://github.com/NativeScript/login-tab-navigation-ng) attached at the end of the article, however, I was unable to recreate the issue with the latest {N}. On that matter can you send us a sample project, that can be used for recreating the problem? Also, let us know if there are some specific steps, that must be followed.

**Comment by Oguzhan1942** [comment]
Hi @tsonevn,
I compared the sample project with my code and to be honest I couldn't see a big difference from the routing and tabview logic. That's super weird. 
So can you please check my repository [here](https://gitlab.com/oatmaca/swap) . 
There are no specific steps, so far I know. Simply navigating from a start page to the tab-based page. The only thing I've just noticed now, when clicking on the blank page, I get the following error: 
`**** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10457991f NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x1045b1b60 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x104f52dd6 ffi_closure_unix64_inner
4   0x104f537fa ffi_closure_unix64
5   0x108ba6c10 -[UIPageViewController _queuingScrollView:viewBefore:view:]
6   0x108ba6d45 -[UIPageViewController queuingScrollView:viewAfterView:]
7   0x108baf68c -[_UIQueuingScrollView _viewBefore:view:]
8   0x108bafd6c -[_UIQueuingScrollView _requestViewForIndex:]
9   0x108bb0115 -[_UIQueuingScrollView _viewAtIndex:loadingIfNecessary:updatingContents:animated:]
10  0x108bb343a __54-[_UIQueuingScrollView _didScrollWithAnimation:force:]_block_invoke
11  0x108bb30af -[_UIQueuingScrollView _didScrollWithAnimation:force:]
12  0x108baec32 -[_UIQueuingScrollView layoutSubviews]
13  0x1096ed9c1 -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
14  0x10689feae -[CALayer layoutSublayers]
15  0x1068a4b88 CA::Layer::layout_if_needed(CA::Transaction*)
16  0x1068b0ee4 CA::Layer::layout_and_display_if_needed(CA::Transaction*)
17  0x1068203aa CA::Context::commit_transaction(CA::Transaction*)
18  0x106857584 CA::Transaction::commit()
19  0x106857ede CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
20  0x107d420f7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
21  0x107d3c5be __CFRunLoopDoObservers
22  0x107d3c326 CFRunLoopRunSpecific
23  0x10eaf32fe GSEventRunModal
24  0x10921fba2 UIApplicationMain
25  0x104f5363d ffi_call_unix64
26  0x1236d0950
JavaScript stack trace:
1   pageViewControllerViewControllerAfterViewController@file:///node_modules/tns-core-modules/ui/tabs/tabs.js:150:0
2   UIApplicationMain@[native code]
3   _start@file:///node_modules/tns-core-modules/application/application.js:277:0
4   run@file:///node_modules/tns-core-modules/application/application.js:305:0
5   bootstrapNativeScriptApp@file:///node_modules/nativescript-angular/platform-common.js:205:0
6   bootstrapApp@file:///node_modules/nativescript-angular/platform-common.js:106:0
7   bootstrapModule@file:///node_modules/nativescript-angular/platform-common.js:90:0
8   @file:///app/bundle.js:1248:144
9   ./main.ts@file:///app/bundle.js:1253:34
10  __webpack_require__@file:///src/webpack/bootstrap:750:0
11  checkDeferredModules@file:///src/webpack/bootstrap:43:0
12  webpackJsonpCallback@file:///src/webpack/bootstrap:30:0
13  anonymous@file:///app/bundle.js:2:61
14  evaluate@[native code]
15  moduleEvaluation@[native code]
16  promiseReactionJob@[native code]
JavaScript error:
file:///node_modules/tns-core-modules/ui/tabs/tabs.js:150:0 JS ERROR TypeError: undefined is not an object (evaluating 'owner.items.length')
NativeScript caught signal 11.
Native Stack:
1   0x1045be84f sig_handler(int)
2   0x1086f1b5d _sigtramp
3   0x6c851f
4   0x108637b4d libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step()
5   0x10863be4c _Unwind_RaiseException
6   0x1082174aa __cxa_throw
7   0x106c30bfa _objc_exception_destructor(void*)
8   0x104579d58 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
9   0x1045b1b60 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
10  0x104f52dd6 ffi_closure_unix64_inner
11  0x104f537fa ffi_closure_unix64
12  0x108ba6c10 -[UIPageViewController _queuingScrollView:viewBefore:view:]
13  0x108ba6d45 -[UIPageViewController queuingScrollView:viewAfterView:]
14  0x108baf68c -[_UIQueuingScrollView _viewBefore:view:]
15  0x108bafd6c -[_UIQueuingScrollView _requestViewForIndex:]
16  0x108bb0115 -[_UIQueuingScrollView _viewAtIndex:loadingIfNecessary:updatingContents:animated:]
17  0x108bb343a __54-[_UIQueuingScrollView _didScrollWithAnimation:force:]_block_invoke
18  0x108bb30af -[_UIQueuingScrollView _didScrollWithAnimation:force:]
19  0x108baec32 -[_UIQueuingScrollView layoutSubviews]
20  0x1096ed9c1 -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
21  0x10689feae -[CALayer layoutSublayers]
22  0x1068a4b88 CA::Layer::layout_if_needed(CA::Transaction*)
23  0x1068b0ee4 CA::Layer::layout_and_display_if_needed(CA::Transaction*)
24  0x1068203aa CA::Context::commit_transaction(CA::Transaction*)
25  0x106857584 CA::Transaction::commit()
26  0x106857ede CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
27  0x107d420f7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
28  0x107d3c5be __CFRunLoopDoObservers
29  0x107d3c326 CFRunLoopRunSpecific
30  0x10eaf32fe GSEventRunModal
31  0x10921fba2 UIApplicationMain
JS Stack:
1   UIApplicationMain@[native code]
2   _start@file:///node_modules/tns-core-modules/application/application.js:277:0
3   run@file:///node_modules/tns-core-modules/application/application.js:305:0
4   bootstrapNativeScriptApp@file:///node_modules/nativescript-angular/platform-common.js:205:0
5   bootstrapApp@file:///node_modules/nativescript-angular/platform-common.js:106:0
6   bootstrapModule@file:///node_modules/nativescript-angular/platform-common.js:90:0
7   @file:///app/bundle.js:1248:144
8   ./main.ts@file:///app/bundle.js:1253:34
9   __webpack_require__@file:///src/webpack/bootstrap:750:0
10  checkDeferredModules@file:///src/webpack/bootstrap:43:0
11  webpackJsonpCallback@file:///src/webpack/bootstrap:30:0
12  anonymous@file:///app/bundle.js:2:61
13  evaluate@[native code]
14  moduleEvaluation@:1:11
15  promiseReactionJob@:1:11`

Sorry for the log format. I couldn't format it better readable.

**Comment by Oguzhan1942** [comment]
I had to grant visibility to the source code. Now it's accessible. Let me know please @tsonevn , when you have checked the code, so I can make it private again.

**Comment by tsonevn** [comment]
Hi @Oguzhan1942,
I've just tried to clone the project, however, it seems that you've made the repository private again. Can you add me as a project's member in GitLab? My username is `tsonevn`.

**Comment by Oguzhan1942** [comment]
Hi @tsonevn,
for any reasons it works now. Upon on the sample project above I have created each components step for step. I cannot distinguish the logic from my previous version and the sample project. Pretty weird. If you notice any difference or mistake, please let me know. 
Thanks!

**Comment by tsonevn** [comment]
Hi @Oguzhan1942,
I am glad to hear that you were able to solve your case. In my opinion, we can close this issue.

**Comment by fpaaske** [comment]
I had this seemingly exact issue, and found that if you use the `selector: "tabs"` for the `TabsComponent`, it will fail with blank screen and when click/dragging on the screen you get this error. You can test with the code in the example repo: https://github.com/NativeScript/login-tab-navigation-ng

It took me much longer than I like to admit to figure this out.
