### ISSUE TITLE
Build fails on Win 8.1 x64, 64bit node.js

### ISSUE THREAD

**Issue by zahirdhada** [NativeScript/NativeScript#768]
npm i -g nativescript fails on my Win 8.1 x64 with 64bit node.js installed.

Here's a link to the log produced by npm: https://www.zerobin.net/?c9490666c24a738a#EpR/qKK9+EsD+Qzgut0Xlmw9FN4owaGx+cV88Tj+pzs=

**Comment by NathanaelA** [comment]
NativeScript can't be installed with Node 4 yet.  You need to downgrade to 0.12. to install it.

**Comment by zahirdhada** [comment]
Thanks. Worked perfectly after downgrading to 0.12.
