### ISSUE TITLE
Custom splash screen with data

### ISSUE THREAD

**Issue by ishaqueahmed-mev** [NativeScript/NativeScript#7687]
Hello,

I want to create a splash screen which loads an image and some data from API is shown over the image. I could create the layout, but I don't know how do I need to proceed further for using it in place of the default splash screens that we normally use as different sized images in iOS and android.

Can someone please guide me through it or is it even possible to do or not.

Thanks.

**Comment by tsonevn** [comment]
Hi @ishaqueahmed-mev,
I am not sure that I understand correctly, what you are trying to achieve as a final result. On that matter, can you provide some more info about your case?
Meanwhile, I would suggest reviewing our articles for [iOS](https://docs.nativescript.org/tooling/publishing/creating-launch-screens-ios) and [Android](https://docs.nativescript.org/tooling/publishing/creating-launch-screens-android), where it is described how to set up the splash screen for both platforms. Also, you can check our [generate splashes](https://docs.nativescript.org/tooling/docs-cli/project/configuration/resources/resources-generate-splashes) command that can help in the splash screen setup.

**Comment by ishaqueahmed-mev** [comment]
Hello, thanks for the response,

what I actually want to do is that I want to load a component in place of splash screen images. There's a particular design in component html and I want to load it as the starting screen and not the default splashes. Hope you understand what I'm trying to achieve.

Thanks.

**Comment by ashhadaimviz** [comment]
What I understand is you want to show  a loading component as a startup screen till you are receiving data from API is that so?

**Comment by ishaqueahmed-mev** [comment]
yes kind of, but I don't want the splash screen to loading first, directly the component.

**Comment by ashhadaimviz** [comment]
@ishaqueahmed-mev bro then you want to show data without loading? directly in component? It is confusing :/

**Comment by ishaqueahmed-mev** [comment]
Yeah, right now lets forget about the API, I can work with static data also, but the design that are created in the component, has to be loaded first instead of the default splashes.

**Comment by ashhadaimviz** [comment]
okay share details here or somewhere else you want!

**Comment by ishaqueahmed-mev** [comment]
there are some images in the html files which I need to show from the component, and that's it...

**Comment by ashhadaimviz** [comment]
have you started working on it? can we make it to any private communication and then we will share the result here if we succeed?

**Comment by ishaqueahmed-mev** [comment]
no, right now I have just created the component, and I'm not getting any idea about about replacing the default splash screens with custom components.

**Comment by ashhadaimviz** [comment]
Brother I am willing to help you but unfortunately without any clear image I can't do anything. Direct Communication will help like messenger or any other where you can share or tell each and every thing. 
It will be helpful

**Comment by NickIliev** [comment]
Just as a side note - the splash screen is not the place to have interactive UI with data - it is supposed to be just a splash.  Not to mention that loading an image from an online source for the splash screen is a really bad idea - this might cause bad UX especially when the connection is lost or slow - the splash screen shouldn't rely on any async APIs - oit should provide an immediate experience for the users.
Perhaps the landing page is the better place to have data.
