### ISSUE TITLE
Cross Platform Google Maps SDK

### ISSUE THREAD

**Issue by rodenp** [NativeScript/NativeScript#769]
I would really be keen to see the gap plugged in the nativescript google sdk plugin to allow both iOS and Android usage. (https://www.npmjs.com/package/nativescript-google-sdk)

I am very new to nativescript and have been struggling to come to terms with anything larger than a simple project. Having a solid and robust mapping system would give me confidence in the nativescript platform and also allow me to see how things fit together.

I believe there is fundamental functionality that should work out of the box and act as a template for others to model against.

There is massive rapid development happening with nativescript and this is totally awesome. I can really see the commitment that you guys have towards creating a platform of the future. And i can see that over time with contribution from others that developing new applications is going to get easier and quicker.

However  as I have seen with cordova plugins, the quality can vary significantly and resolving issues can be painful requiring a deep knowledge of iOS and Android.

I would like to see Telerik core nativescript plugins released that work right from the start on iOS and Android.

regards
Peter

**Comment by dapriett** [comment]
+1 For cross-platform Google Maps!

**Comment by N3ll** [comment]
You can vote on our voting site https://nativescript.ideas.aha.io/ideas/NS-I-65.

**Comment by N3ll** [comment]
Thanks to @dapriett now there is a cross-platform npm plugin for Google maps. You can download it [here] (https://www.npmjs.com/package/nativescript-google-maps-sdk) and participate in the [discussion](https://groups.google.com/forum/#!topic/nativescript/HWEEprMY8P0) about it in the Google group of {N} :)
