### ISSUE TITLE
Detailed rounded corners (Border radius for top-right-bottom-left)

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#77]
_From @ErjanGavalji on February 2, 2015 8:31_

Implement detailed corner radius specification. See [the respective forum post](http://www.telerik.com/forums/styling-labels-with-borders) for a detailed request.

The following [ios](http://stackoverflow.com/questions/10167266/how-to-set-cornerradius-for-only-top-left-and-top-right-corner-of-a-uiview) and [android](http://stackoverflow.com/questions/6054562/how-to-make-the-corners-of-a-button-round) hints might help with the implementation.

_Copied from original issue: NativeScript/cross-platform-modules#36_

**Comment by sharesoft** [comment]
I'm not clear from the above if the suggestion to allow the radius of all four corners of a border item (eg. <Border cornerRadius="0 0 5 5" ... /> or via CSS rules) is going to be implemented. Can the {N} dev team comment?

**Comment by sharesoft** [comment]
My hopes were raised eaerlier when I saw this had been added to the 2.4.0 features list. And then I saw it had been removed. : -( Are you still planning to implement this much-needed CSS feature?

**Comment by erkanarslan** [comment]
This feature works correctly on Android but not on iOS. On iOS sometimes it is correct, sometimes not. It looks like a random decision on Nativescript's side.

In this image all received messages should be formatted like the last one but some of them are incorrectly applies border radius. I checked if styles are correctly defined and there is no error. It already works correctly on android.

![img_641976712206-1](https://user-images.githubusercontent.com/11949947/34101401-b2f78f7a-e3f6-11e7-9f0c-b2cfbb36ed17.jpeg)

**Comment by NickIliev** [comment]
This feature is implemented with the standard CSS syntax:
```
border-radius: 10 5 10 5;
```
Where corners are in the standard CSS order - top-left, top-right, bottom-right, bottom-left.

Demo application demonstrating the above can be found [here](https://github.com/NickIliev/NS-Issues-2018/tree/master/NativeScript/issue_77)

Result:


![borders](https://user-images.githubusercontent.com/18008302/37702539-8c0a3afe-2cfb-11e8-8b70-9199d07b864b.png)

**Comment by NickIliev** [comment]
@erkanarslan let me know if you have a sample application demonstrating your issue as it is not reproducible on my side.
