### ISSUE TITLE
Decimal separator not available for keyboardType="number" in non-US regions (Android)

### ISSUE THREAD

**Issue by diegobelfiore** [NativeScript/NativeScript#7701]
**Environment**

Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.4.1-2019-05-16-13284
 - Cross-platform modules: 5.4.3
 - Android Runtime: 5.4.0 
 - iOS Runtime: 5.4.0
 - Plugin(s): (none)

**Describe the bug**

I have a TextField with keyboardType="number" that I need to use to input currency values. The problem is that the comma button is not available on Android as a decimal separator, even if I change the device locale to a region that uses ',' as the decimal separator (e.g., it-IT).

The comma button appears on the Android numerical keyboard, but does nothing when you press it. 

**To Reproduce**

Add a TextField with keyboardType="number". The comma button is not usable, even when you set your Android device/simulator region to something that uses ',' as the decimal separator. Only '.' is allowed as the decimal input, which is wrong in most regions outside of en-US. 

**Expected behavior**

The comma button should enter ',' as the decimal separator when you have your device/simulator region set to a locale that uses a comma as the decimal separator.

**Sample project**

I have a [sample repo available here](https://github.com/diegobelfiore/nskeyboarddemo). Ignore the web portion and run using 'npm run serve:android' or 'tns run android'. 

**Additional context**

I need to use the numeric keyboard for currency input in a point-of-sale application. I'm parsing numeric input according to the selected region and I need to be able to have my users enter the correct decimal separator for currency values.

Everything works if I use the default keyboard type, but it's not appropriate for a production app.

**Comment by NickIliev** [comment]
@diegobelfiore NativeScript is using the native APIs to create different keyboard types. So that said, it is expected to miss a decimal pint from a number keyboard as this is meant to be a phone-dial like a keyboard.  You can use either different keyboard or create an entirely custom one

**Comment by felixelgato92** [comment]
How can this be expected behavior? Why is the comma there then?
