### ISSUE TITLE
Worker freeze when device locked or application minimized

### ISSUE THREAD

**Issue by JMente** [NativeScript/NativeScript#7721]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.4.2
 - Cross-platform modules: 5.4.2
 - Android Runtime: 5.4.0
 - iOS Runtime: 5.4.2
 - Plugin(s): 

```
"nativescript-animated-circle": "^1.2.0",
    "nativescript-audio": "5.0.1",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-facebook": "^4.1.0",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-gif": "^4.0.2",
    "nativescript-google-maps-sdk": "^2.7.0",
    "nativescript-health-data": "^1.1.0",
    "nativescript-imagepicker": "^6.2.0",
    "nativescript-insomnia": "^1.2.3",
    "nativescript-local-notifications": "3.2.2",
    "nativescript-modal-datetimepicker": "^1.2.0",
    "nativescript-pedometer": "^2.1.0",
    "nativescript-permissions": "^1.2.3",
    "nativescript-plugin-firebase": "^8.3.2",
    "nativescript-screen-orientation": "^2.0.0",
    "nativescript-screenshot": "0.0.2",
    "nativescript-social-share": "^1.5.2",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-calendar": "^4.1.0",
    "nativescript-ui-listview": "^6.4.2",
```

**Describe the bug**
My application use a worker to make a counter, when application is minimized or the device is locked works around 30 seconds and after freeze around 10 seconds and continue, try to use the minimal resources as possible but the issue persist

Note: the freeze only happens when the application is minimized or the device is locked don't crash and don't happen when the application is open.

**To Reproduce**

my worker.js  code

```
require("tns-core-modules/globals");

let counter = 0;
let time_str = "";

// Convert counter to time formar 00:00:00
let counter_to_time_str = value => {
  let sec_num = parseInt(value, 10),
    hours = Math.floor(sec_num / 3600),
    minutes = Math.floor((sec_num - hours * 3600) / 60),
    seconds = sec_num - hours * 3600 - minutes * 60;

  hours = hours < 10 ? "0" + hours : hours;
  minutes = minutes < 10 ? "0" + minutes : minutes;
  seconds = seconds < 10 ? "0" + seconds : seconds;
  return hours + ":" + minutes + ":" + seconds;
};

global.onmessage = data => {
  if (data.data.stop) {
    global.close();
  }
  if (counter < data.data.counter) {
    counter = data.data.counter;
  }
  setInterval(() => {
    counter += 1;
    time_str = counter_to_time_str(counter);
    
    // Update the main theath with the counter and the time string
    global.postMessage({
      counter: counter,
      time_str: time_str
    });
    console.log("time: " + time_str);
    console.log("seconds: " + counter);
  }, 1000);
};

global.onerror = error => {
  global.close();
};
```

**Expected behavior**

A basic cronometer working in background

**Comment by NickIliev** [comment]
@JMente is it possible to provide the demo app where the above worker is implemented?

Also, let us know if the free is happening on Android or on iOS and if it is happening once you update to version 6.x.x of runtimes.

**Comment by JMente** [comment]
At this moment provide a demos it's complicated because it's a private repository and i only have acces as a team member, also for now this issue it's happen on android 7 to 9 I'm not try older versions, I'm not update to NS6 because some plugins failes after migrate the core.

I'm suspected android sleep the background process but not sure because when lock the screen stop after 30 seconds and resume when click on unlock the screen without unlock or resume the application.

**Comment by JMente** [comment]
Here a screen video of the issue.

https://drive.google.com/file/d/115OEdauJW7NYN0WQZFi_nBoQEl5nTlpl/view?usp=drivesdk

**Comment by JMente** [comment]
Thank you for nothing

**Comment by NathanaelA** [comment]
@JMente - Josue --  

1. If you got it fixed, you might want to document what you did for other users...
2. If you don't have it fixed; then whip up a quick demo app so that the NS team can easily check into the issue and see why.   Failing demos are gold when you are dealing with a busy team...

However, as a simple note as a user who has used NS for a long time -- since you aren't willing to upgrade to NS6; that makes things more difficult for you to actually get a fix...  The problem might actually be fixed already -- or if their is a problem and they do fix it -- the fix will always be going into the latest release -- since they don't actually do any work on older versions...
