### ISSUE TITLE
Tutorial or feature to set the language(s) of the app in the App Store and Play Store

### ISSUE THREAD

**Issue by elvticc** [NativeScript/NativeScript#7728]
**Is your feature request related to a problem? Please describe.**
 
It is currently difficult to define the language or languages of a NativeScript application on the App Store and the Play Store. In addition, the existing tutorials are not up to date and no longer work.

**Describe the solution you'd like**

Create a tutorial or feature to simply define the language(s) of a NativeScript application in the App Store and Play Store.

**Describe alternatives you've considered**

- https://discourse.nativescript.org/t/set-another-development-region-language/1176
- https://www.telerik.com/forums/localizations-in-app-store-incorrect

**Additional context**

**Comment by tsonevn** [comment]
Hi @elvticc, 
Have you checked the [nativescript-localize](https://github.com/EddyVerbruggen/nativescript-localize). The plugin allows you to set up support for different languages in the app. For more info, you can check the [readme file ](https://github.com/EddyVerbruggen/nativescript-localize#table-of-contents)of the plugin.

**Comment by elvticc** [comment]
Hi @tsonevn,

Thank you for your answer.

My problem is not related to defining multiple languages in the application. But rather to make it clear to the App Store that my application is not in English, but in French.
