### ISSUE TITLE
Move the API reference to typedoc

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#773]
Currently we have an in-house tool that generates an [API reference page](https://docs.nativescript.org/ApiReference/data/observable/Observable) for us. There is a public open-source state-of-the-art tool [typedoc](http://typedoc.io/) that generates much more extensive and feature rich API reference we can adopt.

**Comment by PanayotCankov** [comment]
[The grunt has been updated to generate api reference for the NativeScript modules](https://github.com/NativeScript/NativeScript/pull/1070).

We will have to find a proper place on [docs.nativescript.org](docs.nativescript.org) for the API reference, and integrate the site specific elements such as headers and footers in the typedoc.
According to the [typedoc documentation about theming](http://typedoc.io/guides/themes.html) we can override small parts of the default theme ([e.g. header](https://github.com/sebastian-lenz/typedoc-default-themes/blob/master/src/default/partials/header.hbs)) and inject our CSS-es.

**Comment by enchev** [comment]
This issue was moved to NativeScript/docs#239

**Comment by NathanaelA** [comment]
@enchev, this somehow got tagged as a new feature in v1.6 changelog; but according to NativeScript/docs#239 it is still an open issue.   Might want to fix...

**Comment by enchev** [comment]
Will be fixed immediately! Thanks for the report @NathanaelA!
