### ISSUE TITLE
Error: You are trying to set "Companion" which is a final field! Final fields can only be read.

### ISSUE THREAD

**Issue by dotnetdreamer** [NativeScript/NativeScript#7731]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.2
 - Cross-platform modules: 6
 - Android Runtime: 6.0.0
 - iOS Runtime: 6.0.1

**Describe the bug**
I am trying to test my plugin on NS 6. I have upgrade everything but when i try to run i get following error:
`Error: You are trying to set "Companion" which is a final field! Final fields can only be read.`

**To Reproduce**
Go to [this](https://github.com/dotnetdreamer/nativescript-http-formdata/tree/6.0) repository and v6.0 branch. Try to run the following command:
`npm run demo.android`. 

**Expected behavior**
In previous version of NS, it was working fine. 

**Sample project**
You can find it in [this](https://github.com/dotnetdreamer/nativescript-http-formdata/tree/6.0) repository demo folder.

**Comment by tsonevn** [comment]
HI @dotnetdreamer,
I checked the provided project, however, I was unable to recreate such an issue, while building the demo project on Android device with `npm run demo.android`. Is there anything specific that should be done to recreate the problem.

**Comment by dotnetdreamer** [comment]
Yes, Try to click on the Browse button and select any image to upload from gallery. After that, it will show error in the console.

**Comment by dotnetdreamer** [comment]
Please check the following gif:
![OZZlwpxdHq](https://user-images.githubusercontent.com/10280821/63672768-c0f87700-c7f3-11e9-8212-d7c24dcdeca2.gif)

**Comment by tsonevn** [comment]
Hi @dotnetdreamer,
I was able to recreate the problem on my side. I also find out that a similar issue is logged [here](https://github.com/NativeScript/android-runtime/issues/1178). You can keep track on it for further info.
