### ISSUE TITLE
[Tabs][BottomNavigation] TabStrip.iosIconRenderingMode property value not respected

### ISSUE THREAD

**Issue by manoldonev** [NativeScript/NativeScript#7733]
**Environment**
 - CLI: 6.0.1
 - Cross-platform modules: 6.0.7
 - iOS Runtime: 6.0.2

**Describe the bug**
BottomNavigation and Tabs components do not respect TabStrip.iosIconRenderingMode property value but use `UIImageRenderingMode.AlwaysOriginal` instead.

**Expected behavior**
BottomNavigation and Tabs components should respect TabStrip.iosIconRenderingMode property value.

**Comment by MartoYankov** [comment]
It's not such a simple issue. There are a couple of caveats:
1. The `alwaysTemplate` rendering mode will invalidate/override the `color` property and get the colors from the iOS theme. Currently, there is no easy way provided by NS to change the theme.
2. The `alwaysTemplate` rendering mode doesn't work with the MDCTabBar widget as it doesn't have a notion of changing colors/assets based on active state. Maybe MDCTabBarView will have this.
