### ISSUE TITLE
[BottomNavigation] Binding the iconSource dinamically with "font://" result in just text

### ISSUE THREAD

**Issue by rondey** [NativeScript/NativeScript#7736]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.3
 - Cross-platform modules: 6.0.7
 - Android Runtime: 6.0.2
 - iOS Runtime: 6.0.2

**Describe the bug**
In the TabStripItem, if I set the iconSource parameter to a TypeScript variable the icon will not appear, instead will appear the hexadecimal code

**To Reproduce**
In the template:
`<TabStripItem title="Account" [iconSource]="fontDynamic"></TabStripItem>`

In the TypeScript component:
`fontDynamic = "font://&#xf015;"`

**Expected behavior**
Appears the icon font

**Sample project**
https://play.nativescript.org/?template=play-ng&id=CcuY1G

**Comment by NickIliev** [comment]
@rondey NativeScript is automatically creating a string from a char code when the code is proved in the XML/HTML. But you will need to manually convert this code to a string when this is happening from the code-behind (see [this section](https://docs.nativescript.org/ui/icon-fonts#code-behind))

```JavaScript
String.fromCharCode(0xf015);
```

Here is [the modified Playground app](https://play.nativescript.org/?template=play-ng&id=CcuY1G&v=3) demonstrating the above
