### ISSUE TITLE
Can no longer use Axios

### ISSUE THREAD

**Issue by rynop** [NativeScript/NativeScript#7739]
**Environment**
✔ Component nativescript has 6.0.3 version and is up to date.
✔ Component tns-core-modules has 6.0.7 version and is up to date.
✔ Component tns-android has 6.0.2 version and is up to date.
✔ Component tns-ios has 6.0.2 version and is up to date.

running on iOS emulator

**Describe the bug**

Axios thinks NS is a NodeJs environment, which causes this call stack and error:

```
Module not found: Error: Can't resolve 'net' in '/Users/ryan/projects/ns-binary-test/node_modules/debug/src'
 @ ../node_modules/debug/src/node.js 193:16-30
 @ ../node_modules/debug/src/index.js
 @ ../node_modules/follow-redirects/index.js
 @ ../node_modules/axios/lib/adapters/http.js
 @ ../node_modules/axios/lib/defaults.js
 @ ../node_modules/axios/lib/axios.js
 @ ../node_modules/axios/index.js
```
Obviously NS does not implement the `net` module.  I know I've used Axios in NS in the past.  After debugging I can't figure out what changed.

**To Reproduce**

1.  `tns create ns-axios-test --ng`
1.  Add `import Axios from 'axios';` to `item.service.ts`
1.  Add `const axios = Axios.create();` to `getItems()`
1.  `tns run ios`

**Expected behavior**

Axios should [load and use](https://github.com/axios/axios/blob/b4c5d35d2875191dfa8c3919d4227dce8e2ad23f/lib/defaults.js#L24) XHR (`XMLHttpRequest`) adapter

**Additional context**

The Axios code that determines XHR (browser) vs http (NodeJS) module load can be found [here](https://github.com/axios/axios/blob/b4c5d35d2875191dfa8c3919d4227dce8e2ad23f/lib/defaults.js#L16)

**Comment by NickIliev** [comment]
@rynop with NativeScript 6 we are using WebPack by default and with Webpack we have a process variable (see [here](https://github.com/NativeScript/nativescript-dev-webpack/blob/87f5ca75a264dda1509f2ddeab8bb57b9b0072b6/templates/webpack.javascript.js#L209))

I guess you could modify the posted Axios if/else check for the `process` so you could end up with XHR instead of entering the other condition.

**Comment by belvederef** [comment]
Shoutout to everybody. I could not correctly use axios until I imported the package via 
```js 
import axios from 'axios/dist/axios'
```
when importing the package normally my requests failed returning the error
```
Error in v-on handler (Promise/async): "Error: Request failed with status code null"
```

**Comment by belvederef** [comment]
Shoutout to everybody. I could not correctly use axios until I imported the package via 
```js 
import axios from 'axios/dist/axios'
```
this also solves the `Module not found: Error: Can't resolve 'net' in...` error. 

When importing the package normally my requests failed returning the error
```
Error in v-on handler (Promise/async): "Error: Request failed with status code null"
```

**Comment by tuliodiaz** [comment]
Since @rynop comment about the right require will be executed at runtime. This solve my problem

`npm install net --save-dev`
