### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by ineiti** [NativeScript/NativeScript#7749]
I just got off a 4h debugging session of the following code, which works perfectly in Android, but in iOS has the following properties:
- doesn't show anything with 1 element
- gives a long stack-trace about too many stack-levels when `orgList` has 2 or more elements

page.scss
```
.grid-list {
  color: white;
  background-color: blue;
  text-align: center;
  vertical-align: center;
  horizontal-align: center;
}
```
page.xml
```
<Page
        class="page"
        navigatingTo="onNavigatingTo"
        xmlns:nsListView="nativescript-ui-listview">
    <StackLayout>
              <nsListView:RadListView items="{{ orgList }}">
                    <nsListView:RadListView.listViewLayout>
                        <nsListView:ListViewGridLayout scrollDirection="vertical" spanCount="3"/>
                    </nsListView:RadListView.listViewLayout>

                    <nsListView:RadListView.itemTemplate>
                        <StackLayout class="grid-list">
                            <Label text="{{ alias }}"/>
                        </StackLayout>
                    </nsListView:RadListView.itemTemplate>
                </nsListView:RadListView>
    </StackLayout>
</Page>
```

**Describe the solution you'd like**
For the above code, I did get _one_ warning:
- ListView should have `height`
But I needed to change three others:
- css has invalid fields (see also #1080): `vertical-align` and `horizontal-align`
- `scrollDirection` of `vertical` does not exist (must be `Vertical`)
- `ListViewGridLayout` needs `itemHeight` for iOS

Every single one of these three makes the listview crash with more than 1 element in `orgList`.

**Describe alternatives you've considered**
Switching to another development framework - but every one has its own quirks...

**Comment by shiv19** [comment]
@ineiti 
I suggest never to place ListView inside a StackLayout. Please consider placing it in a GridLayout instead.

**Comment by ineiti** [comment]
@shiv19 - thanks for the tip. In the actual code it _is_ in a `GridLayout`, but for simplicity's sake I put it in a `StackLayout` for the issue. The result is the same - only 1 out of 4 errors is reported.

**Comment by shiv19** [comment]
@ineiti is this something that you're able to recreate on Nativescript playground?

**Comment by ineiti** [comment]
@shiv19 hmm - I tested it here

https://play.nativescript.org/?template=play-tsc&id=LAGUeO

and tried all the elements of my list, but it didn't crash - which is nice. So probably the crashes were due to my version 5.1 of nativescript. I did not update, because I didn't get to work libraries depending on `crypto` with the new nativescript 6.x...

So I'm closing this, sorry for the noise.
