### ISSUE TITLE
Severe Vulnerabilities

### ISSUE THREAD

**Issue by Gardens18** [NativeScript/NativeScript#7752]
Greetings,

From nativescript.org sample apps page , downloaded one of the apps , and generated apk file and tested for vulnerabilities using MobSF , there are lot of vulnerabilities. the details with pdf report are as follows,

<img width="388" alt="Screen Shot 2019-08-29 at 3 27 46 PM" src="https://user-images.githubusercontent.com/41816775/63940475-36717b00-ca72-11e9-973a-f217fe874d3b.png">

[PDF_Nativescript.pdf](https://github.com/NativeScript/NativeScript/files/3555522/PDF_Nativescript.pdf)

Can this be resolved ?
Can you suggest best way to start with a template which does not have vulnerabilities ?

**Comment by NickIliev** [comment]
@Gardens18 the generated report is pretty much informative and suggest what action should be taken to resolve some of the reports. However, I am not seeing any real vulnerabilities so can you please point what exactly you want to resolve?

You could start by using a release Keystore to create a **release** build (this would eliminate some of the reports related to the tested **debug** build).. You could also sign with SHA256.

The reports related to "App logs information - sensitive information should not be logged" are pretty much not valid reports as the logged files are from the native Android SDK and they are not containing any sensitive information.

Overall I am not seeing any real threads being reported - please do let me know if you see something that you are considering a real threat.

**Comment by Gardens18** [comment]
I tried release build, only the "bad" status with certificate has gone. other vulnerabilities still persist. I have attached the report.

For example, one of the high risk vulnerability "Files may contain hardcoded sensitive informations like usernames, passwords, keys etc." 

How to solve this ? Any documentation in native script ?

We are not coding in java or objC, we are just using nativescript framework , so there should be a way to handle these issues in native script itself. Otherwise, it is not Enterprise ready.

Keep in my mind , in our organization , we are already using Sitefinity CMS , we need a strong justification to use native script for cross platform mobile development.


[download.pdf](https://github.com/NativeScript/NativeScript/files/3563468/download.pdf)

**Comment by Gardens18** [comment]
<img width="1032" alt="Screen Shot 2019-09-01 at 4 44 57 PM" src="https://user-images.githubusercontent.com/41816775/64077313-f4e20980-ccd7-11e9-9b9c-aa3724847f60.png">

<img width="1032" alt="Screen Shot 2019-09-01 at 4 46 14 PM" src="https://user-images.githubusercontent.com/41816775/64077318-09260680-ccd8-11e9-8ca8-1650e3f75150.png">


I tried commenting those permissions, but still the problem persists.

**Comment by NickIliev** [comment]
@Gardens18 the thing is that the reports are not conclusive and says

"Files **may** contain hardcoded sensitive information like usernames, passwords, keys, etc"

The keyword is **may** which is warning and not a statement - obviously, in a template project you are not including any sensitive data of this type. The reporting tool is probably not made with NativeScript apps in mind, where the SDK API is used to via VM and the native classes are used in the core modules by converting them to TypeScript/JavaScript code. Obviously those native classes are not using any clients information and are not holding any sensitive information - they are just the native API is used to create the JavaScript abstraction. For example, the reporting tool is classing [this native API](https://developer.android.com/reference/kotlin/androidx/core/content/ContextCompat) as high risk - but API is used in NativeScript just as it would be used in a native project - to build the core structure of your android Activity. 

NativeScript also uses TypeScript definition files (for IntelliSense and TypeScript typing) which are just listing the native API as TypeScript. Those files will never hold any sensitive information as those are just the native SDK being "translated". 

I am not familiar with the tool used for reporting, but it seems that the tool is meant to be runned agains a native Android app. With NativeScript, you have a runtime which is using the native API and core modules which are also using the native API -  just to build the abstraction. These files won't have anything to do with the business part of your application.  To solve an issue like "Files may contain hardcoded sensitive information like usernames, passwords, keys, etc." you should run **against the files in your business part** as the `tns-core-modules` or `tns-ios` will never have any sensitive information from your business logic. That said I think the tool is making the wrong suggestion that the whole app is the business part where in fact you are traversing the files mentioned above that are part from the NativeScript module sand runtimes.


As for the default permissions - are you creating an application that won't need an internet connection? Removing the INTERNET permission will disable the connectivity of your application. Apart from that, after removing permission from the `AndroidManifest.xml`, you should make a clean rebuild (delete **platforms** folder and rebuild) to make sure the native changes are respected.
