### ISSUE TITLE
Background downloading for iOS plugin

### ISSUE THREAD

**Issue by 7ammer** [NativeScript/NativeScript#7753]
Hello 👋 

**Is your feature request related to a problem? Please describe.**
I've worked on two projects that require some form of background downloading and I haven't come across a solution that works well for both Android and iOS.

**Describe the solution you'd like**
My hope is that some official background downloading support would be available that enables proper background downloading especially on iOS.

**Describe alternatives you've considered**
I've tried using https://github.com/triniwiz/nativescript-downloader which is a promising plugin! However, unfortunately there are a few issues with it that make it un-useable in my case.

- iOS download stops when the app is in the background.
- You cannot resume the download if the app has closed as the ID no longer exists even though the partially downloaded file still exists on the phone.

I have also tried to install https://github.com/sgrebnov/cordova-plugin-background-download in conjunction with https://github.com/NativeScript/nativescript-cordova-support but this failed to work due to a missing file ('framework.json??') when running `tns run ios --bundle`.

I've also tried https://github.com/mobilemindtec/nativescript-background-task but this doesn't have progress updates so is not ideal for large downloads.

Thank you for considering this request.

**Comment by NickIliev** [comment]
@7ammer you could implement this by using UIBackgorundModes of type fetch which will allow you to create long-running tasks. More info on how to achieve that in NativeScript can be found in [this documentation article](https://docs.nativescript.org/core-concepts/ios-runtime/how-to/BackgroundExecution). Also, refer to[ this blog post f](https://blog.newrelic.com/engineering/ios9-background-execution/)or more information about downloading in the background for iOS.

Keep in mind, that iOS is having some strict rules related to the background execution  Enabling this mode is not a guarantee that the system will give your app any time to perform background fetches. The system must balance your app’s need to fetch content with the needs of other apps and the system itself. After assessing that information, the system gives time to apps when there are good opportunities to do so.

**Comment by 7ammer** [comment]
@NickIliev Thanks for the info and great links! Looks like I'll be doing a bit of research today!
