### ISSUE TITLE
Badge for TapStrip icon on BottomNavigation, Tabs, Tabview

### ISSUE THREAD

**Issue by fvdung** [NativeScript/NativeScript#7758]
I want to add a badge to the icon in Bottom Navigation.
The content can be any number or any character.
Can an inline xml tag solution not?

**Comment by NickIliev** [comment]
@fvdung there is no out-of-the-box support for a badge but you can achieve that by changing the existing icon with a badged one. (e.g. by using binding which changes the badged icons on given criteria)

**Comment by pap5508** [comment]
@fvdung : Are you able to fix this ? I am trying similar implementation so far there is no success. Could you please help me out if you have Implemented.
