### ISSUE TITLE
Nativescript 1.3.0 intsllation issue

### ISSUE THREAD

**Issue by atul221282** [NativeScript/NativeScript#776]
I will try my best to explain what I did and where I am right now. I am using window7

What I did for installation.
 1. Installed jdk and updated the environment path variable and created new one JAVA_HOME
 2. Downloaded Gradle and updated the environment path pointing to bin directory of gradle
 3. Installed android sdk with all the specified version, sdk tool, and platform tools.
 4. Created ANDROID_HOME variable.
 5. Remove and Reinstalled Nativescript
 6. Ran tns doctor command and result can be found here http://pastebin.com/8EGzLmuV
 7. Launched the app via tns run android --emulator and tried on device as well error received was "Unfortunately mysir has stopped" and log can be found here http://pastebin.com/RcicsSFX.

Now Can anyone please tell me what I am missing?

Update "Unfortunately mysir has stopped" the reason why I was getting this is because I forgot to run "npm install tns-core-modules --save"  before launching my app.

**Comment by NathanaelA** [comment]
Actually it looks like a issue possibly with your phone or emulator.   I could be wrong; but the error:
09-19 10:17:49.688  1414  1414 W ContextImpl: Failed to ensure /sdcard/Android/data/org.nativescript.mysir/files: java.lang.SecurityException: Invalid mkdirs path: /storage/self/primary/Android/data/org.nativescript.mysir/files
appears to have failed to create the extraction folder for all your nativescript code.  So it is seg faulting when it starts and attempts to load the source code.

**Comment by atul221282** [comment]
Good to see you back. I have tried it on actual android device and getting the same error. I have just reinstalled everything again and i will show u what i get when I install native script. I have followed these guidelines https://github.com/NativeScript/nativescript-cli.

And this is my output when I installed nativescript http://pastebin.com/eFTCXx3S

**Comment by atul221282** [comment]
C is my drive on computer.
Please not when I run tns doctor command inside C:\Windows directory i get different output from when i run it inside C directory.

tns doctor output when inside C:Windows
http://pastebin.com/jN5ch7XK

tns doctor inside C
http://pastebin.com/uWtzDJX6

Can you tell me what and where we need to put ANDROID_HOME variable. I have got ANDROID_HOME set to C:\Program Files (x86)\Android;\android-sdk under System Environment variable.
Environment variable are of two types one for user and one for system
My Sytem path variable are http://pastebin.com/r5QUzDUY
My User Path is http://pastebin.com/3JBa1HHa

**Comment by atul221282** [comment]
I just created new project and was trying to add android platform and got the error of ANDROID_HOME not set properly but I think I am pointing to right directory installed by choclatey.

Error details are here http://pastebin.com/y5MvqvrE

**Comment by atul221282** [comment]
Project build error details about Could not create the java virtual machine.
Details are here http://pastebin.com/ETK3jQpK

**Comment by NathanaelA** [comment]
Ok, lets do some diagnostic work:
Type 
**node --version**
**npm --version**
**tns --version**
**java -version**   (only one dash in this one)
**android list**
**gradle --version**

Specifically do this from any of your project directories.

And report back what you get.

**Comment by atul221282** [comment]
ai ai sir and here it is my output for all versions command without any erro under my app folder
http://pastebin.com/ThRCZ5Hi
One thing more i tried with genymotion emulator and it throws the error of "INSTALL_FAILDER_OLDER_SDK"

**Comment by NathanaelA** [comment]
I may have idea; according to your **android list** you only have no abi's available for android-17 (which I believe NativeScript CLI targets).   
```
id: 1 or "android-17"
     Name: Android 4.2.2
     Type: Platform
     API level: 17
     Revision: 3
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, W
XGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.
```

I'm almost positive you need both the arm (armeabi-v7a) & x86 abi's installed to be able to build a app properly for NativeScript.    And just for safety sake, I would add both those abi's to the three sdk versions you have installed 17, 22 & 23.

As for Geny, you need to download a Geny emulator images of at least 4.2.2 for the Android 17.  However, if you don't have any abi's installed; Geny would also have issues.

**Comment by atul221282** [comment]
Hi NathanaelA please find the enclosed attachment and let me know all the checked one are that I am going to install.

![goingtoinstall](https://cloud.githubusercontent.com/assets/4570393/9975023/74288b5c-5eea-11e5-9787-aef01d7323a2.PNG)

**Comment by NathanaelA** [comment]
I don't think you need the the sources; nor do you need "Wear" (unless you are planning on targeting the android wearables)  -- Also make sure in your "Extras" that you have "Android Support Repository" and "Android Support Library" and in your "Tools" that you have "Android SDK Platform-tools" and "Android SDK Tools" and "Android SDK Build tools (22.0.1)" installed.

**Comment by atul221282** [comment]
I have got everything installed now but my sdk manager showing one update available for android sdk tools from 24.0.2 to 24.3.4. Should i do that or keep the existing one?

**Comment by NathanaelA** [comment]
I don't think that will matter; your choice.

**Comment by atul221282** [comment]
Hi Mate I finally got it working on my mobile but cannot get it to work on my android emulator. I just need to check the emu installation and i will also try it on genymotion and will update you asap

**Comment by NathanaelA** [comment]
You might need to de-install the app on the emulator; then try re-installing it.

**Comment by atul221282** [comment]
it is not getting installed at all

**Comment by NathanaelA** [comment]
Well, you could try resetting the emulator totally.   You can also try the **tns deploy android** and then try running it manually on the emulator...

**Comment by atul221282** [comment]
Yes that's what exactly I am going to do tonight get the emulator up and running and thanks for ur help atleast I got it working on actual device. Ur support is really appreciated and thanks for having patience. I think the best guide to follow the installation is https://github.com/NativeScript/nativescript-cli.
This is really well explained.

**Comment by atul221282** [comment]
Well finally got it working but not within default android emulator but with genymotion emulator and actual deevice. I think android latest sdk forced by native script is not compatible with windows 7 as they don't support Hyper V
