### ISSUE TITLE
Typo: "Andorid"

### ISSUE THREAD

**Issue by NanoDano** [NativeScript/NativeScript#7761]
In this file on line 44:

https://github.com/NativeScript/NativeScript/blob/e2c3c8c0845949efc8a4b1f13f88e27f209bb42d/tests/app/application/application-tests.android.ts#L44

there is a typo with the word "Andorid" instead of Android.

I also noticed a similar typo when building, but couldn't find this reference in the code:

```
+ using andorid X library androidx.legacy:legacy-support-v4:1.0.0
```

**Comment by milindsoorya** [comment]
can i work on this issue?
