### ISSUE TITLE
Add comment to locked threads

### ISSUE THREAD

**Issue by TheJaredWilcurt** [NativeScript/NativeScript#7771]
If you google nativescript discord, these two pop up:

* https://github.com/NativeScript/NativeScript/issues/6103
* https://github.com/NativeScript/NativeScript/issues/5417

They were both closed by an evil robot.

They should have this link added to the bottom of them so that googling gives useful results

* https://discord.gg/tWatGYj

**Comment by NickIliev** [comment]
@TheJaredWilcurt thanks for the suggestion - I've added the links to the locked threads.
