### ISSUE TITLE
add custom native view get error : Cannot read property '__extended' of undefined

### ISSUE THREAD

**Issue by YouYII** [NativeScript/NativeScript#7774]
**Environment**
 - CLI:  zsh
 - Cross-platform modules:
 - Android Runtime:6.0.2
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**

		System.err: Calling js method onCreateView failed
		System.err: TypeError: Cannot read property '__extended' of undefined
		System.err: StackTrace:
		System.err:     Frame: function:'extend', file:'/data/data/com.zheby.safa/files/internal/ts_helpers.js', line: 62, column: 15
		System.err:     Frame: function:'Parent.call', file:'/data/data/com.zheby.safa/files/internal/ts_helpers.js', line: 79, column: 19
		System.err:     Frame: function:'ClickListenerImpl', file:'file:///app/libs/my-button/my-button.ts:27:12
		System.err:     Frame: function:'module.exports.push../libs/my-button/my-button.ts.MyButton.initNativeView', file:'file:///app/libs/my-button/my-button.ts:71:30
		System.err:     Frame: function:'ViewBase.setNativeView', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:547:17
		System.err:     Frame: function:'ViewBase._setupUI', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:526:13
		System.err:     Frame: function:'', file:'file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:533:18

**To Reproduce**
copy https://github.com/NativeScript/nativescript-ui-plugin-custom/src/my-button.* to my code base , import and use my-botton view 

**Expected behavior**
show my-button view

**Additional context**

generated code on bundle.js

		"use strict";
		/* WEBPACK VAR INJECTION */(function(global) {
		Object.defineProperty(exports, "__esModule", { value: true });
		var tslib_1 = __webpack_require__("../node_modules/tslib/tslib.es6.js");
		var my_button_common_1 = __webpack_require__("./libs/my-button/my-button.common.ts");
		var ClickListener;
		// NOTE: ClickListenerImpl is in function instead of directly in the module because we
		// want this file to be compatible with V8 snapshot. When V8 snapshot is created
		// JS is loaded into memory, compiled & saved as binary file which is later loaded by
		// android runtime. Thus when snapshot is created we don't have android runtime and
		// we don't have access to native types.
		function initializeClickListener() {
		    // Define ClickListener class only once.
		    if (ClickListener) {
		        return;
		    }
		    // Interfaces decorator with implemented interfaces on this class
		    var ClickListenerImpl = /** @class */ (function (_super) {
		        tslib_1.__extends(ClickListenerImpl, _super);
		        function ClickListenerImpl(owner) {
		            var _this = this;
		            _this.owner = owner;
		            console.log('here1');
		            _this = _super.call(this) || this;
		            console.log('here2');
		            // Required by android runtime when native class is extended through TypeScript.
		            return global.__native(_this);
		        }
		        ClickListenerImpl.prototype.onClick = function (v) {
		            // When native button is clicked we raise 'tap' event.
		            var owner = this.owner;
		            if (owner) {
		                owner.notify({ eventName: my_button_common_1.MyButtonBase.tapEvent, object: owner });
		            }
		        };
		        ClickListenerImpl = tslib_1.__decorate([
		            Interfaces([android.view.View.OnClickListener]),
		            tslib_1.__metadata("design:paramtypes", [MyButton])
		        ], ClickListenerImpl);
		        return ClickListenerImpl;
		    }(java.lang.Object));
		    ClickListener = ClickListenerImpl;
		}

**Comment by YouYII** [comment]
typescript code 

			// NOTE: ClickListenerImpl is in function instead of directly in the module because we
			// want this file to be compatible with V8 snapshot. When V8 snapshot is created
			// JS is loaded into memory, compiled & saved as binary file which is later loaded by
			// android runtime. Thus when snapshot is created we don't have android runtime and
			// we don't have access to native types.
			function initializeClickListener(): void {
			    // Define ClickListener class only once.
			    if (clickListener) {
			        return;
			    }

			    // Interfaces decorator with implemented interfaces on this class
			    @Interfaces([android.view.View.OnClickListener])
			    class ClickListener extends java.lang.Object implements android.view.View.OnClickListener {
			        public owner: MyButton;

			        constructor() {
			            super(); #========== throw this error   ============
			            // Required by android runtime when native class is extended through TypeScript.
			            return global.__native(this);
			        }

			        public onClick(v: android.view.View): void {
			            // When native button is clicked we raise 'tap' event.
			            const owner = (<any>v).owner;
			            if (owner) {
			                owner.notify({ eventName: MyButtonBase.tapEvent, object: owner });
			            }
			        }
			    }

			    clickListener = new ClickListener();
			}

**Comment by YouYII** [comment]
Can i create native view without use plugin mode , It's much more efficient

**Comment by NickIliev** [comment]
@YouYII if you are using NativeScript Core (plain JS or TypeScript) than you could use [Placeholder ](https://docs.nativescript.org/ui/placeholder)and create the view while using the native SDK. 

**XML page**
```XML
<Page xmlns="http://schemas.nativescript.org/tns.xsd">
  <StackLayout>
    <Placeholder creatingView="creatingView"/>
  </StackLayout>
</Page>
```

**TypeScript** 
```TyperScript
mport { CreateViewEventData } from "tns-core-modules/ui/placeholder";

export function creatingView(args: CreateViewEventData) {
    let nativeView = new android.widget.TextView(args.context);
    nativeView.setSingleLine(true);
    nativeView.setEllipsize(android.text.TextUtils.TruncateAt.END);
    nativeView.setText("Native");
    args.view = nativeView;
}
```


However, if you are using Angular then creating a plugin would be much easier as you won't be able to use Placeholder and you will need to register the view in Angular. I would suggest sticking with the plugin approach as it would simplify improving the code base and reusing the component .. not to mention the community glory ;)

**Comment by YouYII** [comment]
> @YouYII if you are using NativeScript Core (plain JS or TypeScript) than you could use [Placeholder ](https://docs.nativescript.org/ui/placeholder)and create the view while using the native SDK.
> 
> **XML page**
> 
> ```
> <Page xmlns="http://schemas.nativescript.org/tns.xsd">
>   <StackLayout>
>     <Placeholder creatingView="creatingView"/>
>   </StackLayout>
> </Page>
> ```
> 
> **TypeScript**
> 
> ```
> mport { CreateViewEventData } from "tns-core-modules/ui/placeholder";
> 
> export function creatingView(args: CreateViewEventData) {
>     let nativeView = new android.widget.TextView(args.context);
>     nativeView.setSingleLine(true);
>     nativeView.setEllipsize(android.text.TextUtils.TruncateAt.END);
>     nativeView.setText("Native");
>     args.view = nativeView;
> }
> ```
> 
> However, if you are using Angular then creating a plugin would be much easier as you won't be able to use Placeholder and you will need to register the view in Angular. I would suggest sticking with the plugin approach as it would simplify improving the code base and reusing the component .. not to mention the community glory ;)

Thank you for your prompt reply. 
Using a local plugin is the best way. If you change the plugin code, the application will restart automatically. It’s amazing.
