### ISSUE TITLE
StaticInjectorError(AppModule)[NSLocationStrategy->FrameService]

### ISSUE THREAD

**Issue by sabrineayadi** [NativeScript/NativeScript#7775]
**### I have always the same problem.I can't advance....**
![Capture (2)](https://user-images.githubusercontent.com/44321003/64158096-338ed580-ce38-11e9-84e5-9765abfaa3c3.PNG)
![Capture2](https://user-images.githubusercontent.com/44321003/64158097-34276c00-ce38-11e9-813b-2bf870f6ad7a.JPG)
**### thank you for helping me**

**Comment by NickIliev** [comment]
@sabrineayadi this is not a NativeScript related error but Angular one and it is indicating that you have missed registering your service in the NgModule (where it is used) in the `providers` section. See this [SO thread for details](https://stackoverflow.com/a/32298993/4936697)
