### ISSUE TITLE
How to filter observable array in nativescript-vue

### ISSUE THREAD

**Issue by nulele** [NativeScript/NativeScript#7777]
Sorry for opening again [this issue](https://github.com/NativeScript/NativeScript/issues/1720) but it's already been closed... and the solution doesn't work for me.

My project uses **nativescript-vue** with **vuex**.

I'm trying to filter a RadListView based on the term typed in a SearchBar.

```
<SearchBar ref="searchBar" @textChange="onSearch" ></SearchBar>

...

<RadListView pullToRefresh="true" @pullToRefreshInitiated="refreshTodos" for="todo in todos" class="list-group">
	<v-template>
		<GridLayout rows="auto, auto" columns="85, *, auto" class="list-group-item" @tap="showTodo(todo)">
			...
		</GridLayout>
	</v-template>
</RadListView>
```

Here is the vuex state variable initially empty.

```
todos: new ObservableArray([]),
```

And the vuex mutation function feeded by an action that executes an axios call on the server.

```
getTodos: function (store, todos) {
	store.todos = new ObservableArray(todos);
},
```

In my component I have a computed function where I get and filter vuex state variable for the RadListView element based on the local variable "term".

```
todos() {
	let todos = this.$store.state.todo.todos;
	const term = this.term;
	return todos.filter(function (item) {
		if(term && term.length >= 2) {
			return item.name.toLowerCase().indexOf(term) !== -1;
		}
		return true;
	});
},
```

Everything works but I always get a warning log

```
[Vue warn]: Invalid prop: type check failed for prop "items". Expected Object, got Array 

found in

---> <RadListView>
       <Todos> at components/Todos.vue
         <TabViewItem>
           <TabView>
             <Page>
               <Home> at components/Home.vue
                 <NavigationEntry>
```
If I remove the filter part from the *todos()* computed function the error doesn't show.
I've done several attempts to transform the filtered array in an observable array but I always get 

```
range error: maximum call stack size exceeded
```

I'd really like to solve this annoying problem... any idea?

Thanks!

**Comment by tanc** [comment]
@nulele you closed the issue, did you find a solution? Can you post it?

**Comment by nulele** [comment]
Well... ehm... actually I moved over to Quasar  :P

**Comment by tanc** [comment]
My particular issue, which looked a lot like this one, was caused by an infinite loop of references which ends up in the call stack size exceeded message. I refactored my code and approached the problem in a different way.
