### ISSUE TITLE
Trouble running app after updating to v6.0

### ISSUE THREAD

**Issue by ishaqueahmed-mev** [NativeScript/NativeScript#7779]
after updating my current NS app from v5 to v6 using tns migrate command, and after running with tns run ios, I'm getting the following error

**Unknown argument: preserve-symlinks
Executing webpack failed with exit code 1.**

Versions::
✔ Component nativescript has 6.1.0 version and is up to date.
✔ Component tns-core-modules has 6.1.0 version and is up to date.
⚠ Update available for component tns-android. Your current version is 6.0.0 and the latest available version is 6.1.0.
✔ Component tns-ios has 6.1.0 version and is up to date.

I have been stuck in it for almost 4 hours, I have only checked on iOS, not on android. Also when I created a new app, it works fine.

Please help me to find the issue.

Thanks/.

**Comment by tsonevn** [comment]
Hi @ishaqueahmed-mev,
Can you provide more info about your project and your environment(`npm`, `NodeJS` versions)? It will help if you can send us the full error log as well as the project, which you are trying to migrate or at least its `package.json`.

**Comment by ishaqueahmed-mev** [comment]
Hey @tsonevn,
thanks for your response,
here are my configurations ::

**Node - v10.15.1
NPM - v6.11.3

"nativescript": {
    "tns-ios": {
      "version": "6.0.1"
    }
  },
  "dependencies": {
    "nativescript-advanced-webview": "^3.0.1",
    "nativescript-awesome-webview": "^0.1.1",
    "nativescript-calendar": "^2.0.2",
    "nativescript-dom": "^2.0.0",
    "nativescript-drop-down": "^3.2.4",
    "nativescript-effects": "^1.0.0",
    "nativescript-filterable-listpicker": "^2.0.2",
    "nativescript-google-maps-sdk": "^2.7.0",
    "nativescript-grid-view": "^5.0.0",
    "nativescript-https": "^1.0.3",
    "nativescript-ios-uuid": "^1.0.0",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-numeric-keyboard": "4.2.1",
    "nativescript-phone": "^1.3.1",
    "nativescript-platform-css": "^1.6.5",
    "nativescript-plugin-firebase": "9.0.2",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-sidedrawer": "7.0.0",
    "nativescript-zxing": "^1.5.6",
    "tns-core-modules": "6.0.1"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "~0.1.19",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "1.0.1",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "~6.0.6",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0",
    "node-sass": "4.12.0"
  }**

Thanks.

**Comment by tsonevn** [comment]
Hi @ishaqueahmed-mev,
Thank you for the provided additional information. After reviewing the `package.json` file, we found that this problem might be caused by the old `"webpack"` version (v. "~3.10.0"); To fix the issue, you can try executing the webpack deps  update script via
`./node_modules/.bin/update-ns-webpack --deps`
Then delete `node_modules`, `platforms` folders and `package-lock.json` file, run `npm i ` and try to rebuild the project.

**Comment by ishaqueahmed-mev** [comment]
hey @tsonevn,
thanks for the reply, I'll try it and get back to you with the output.

**Comment by ishaqueahmed-mev** [comment]
its working now, thanks for the help @tsonevn.
