### ISSUE TITLE
[BottomNavigation] State and scroll position is lost in android

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/NativeScript#7781]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1
 - Cross-platform modules: 6.1
 - Android Runtime: 6.1
 - iOS Runtime: -
 - Plugin(s): -

**Describe the bug**
This bug occurs in Android lower APIs (Android 7 and above works fine). When you scroll in listview within the first tab and then go to the second tab, and when you come back to the first tab, the scroll position is lost.

**To Reproduce**
This happens in a tab template. See issue #6859 for more info.

**Expected behavior**
To keep the scroll position when navigating between the tabs.

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
