### ISSUE TITLE
[iOS]: frame.topmost().currentPage is not the same instance as the page being loaded in page.loaded event handler.

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#779]
During page.loaded event, frame.topmost() does not have the proper information for getViewById to work.  In fact currentPage = null.   However on Android this does work during the page.loaded event.  

This also causes a Page.showModal(x) to fail during the page.loaded event.

**Comment by N3ll** [comment]
Hey, @NathanaelA , the recommended way to access the current page is by taking the object of the args parameter of page.loaded.
```
 exports.load = function(args){
	var currentPage = args.object;
};
```

**Comment by NathanaelA** [comment]
@N3ll -- Yeah, I know that should work. But that is what is NOT working.   :grinning:   That is what I am reporting.  Guess I should have put in a code example; sorry about that.

If you continue and do either of these:
```
exports.load = function(args){
    var currentPage = args.object;

    // Problem #1: 
    currentPage.getViewById("someValidId"); // -- This will be NULL on iOS

    // Problem #2:
    currentPage.showModal('SomeModalPage'); // This will CRASH on iOS with the following error:
    // JS ERROR Error: Parent page is not part of the window hierarchy. Close the current modal page before showing another one!
}
```

Please note these DO work as expected on Android.  

@N3ll does that help clarify the issues?

**Comment by N3ll** [comment]
@NathanaelA  - that clarified the issue :)

We reproduced the problem with v1.3.0 and it is working fine.

main-page.xml
```
<Page loaded="pageLoaded" >
    <Label id="label" text="Text"/>
</Page>
````

main-page.js
```
var page;
var label;
exports.pageLoaded = function(args) {
    page = args.object;
    label = page.getViewById("label");
    console.log("id" + label);
}
```

Can you send us some code and tell which version you are using, so we can reproduce it exactly?

**Comment by NathanaelA** [comment]
@N3ll -- Sorry about that, that is what happens when I haven't messed with a issued for several weeks, I forget things.  :grinning:    I sent you down a false trail on the first issue, because I couldn't remember the exact sequence.   currentPage.getViewById() does work fine in the loaded event. 

The two things that DON'T work on iOS are 
```
function getInfo() {
   var currentPage = frame.topmost();  // This will be NULL on iOS
   // Do something with currentPage
}

exports.load = function(args){
     var currentPage = args.object;
    // Problem #1: 
    getInfo();

    // Problem #2:
    currentPage.showModal('SomeModalPage'); // This will CRASH on iOS with the following error:
    // JS ERROR Error: Parent page is not part of the window hierarchy. Close the current modal page before showing another one!
}
```

The objective is to use the getInfo function in several places; so it has to lookup the current topmost page to be able to do its work.   In page.loaded on iOS this is null on Android it is fine.

The second issue is still the same.

**Comment by NathanaelA** [comment]
After a tad more testing I should say the frame.topmost() isn't really null; but you can't use it to get results.  Both frame.topmost().getViewById('label'); and view.getViewById(frame.topmost(),"label") will return null.

**Comment by N3ll** [comment]
@NathanaelA - first, I would like to point out something in the getInfo(). The method topmost() returns a Frame, so it is a bit misleading to name your variable thePage. If you would like to get the page, you can access the instance property currentPage (https://docs.nativescript.org/ApiReference/ui/frame/Frame.html). 

About the other problems - there is a difference how the pages are loaded in iOS and Android and that is why it crashes in iOS. What you can do is use the navigatedTo instead of loaded.

**Comment by NathanaelA** [comment]
@N3ll -    I am also aware I can use navigatedTo -- that was my workaround also.  ;-)

In my personal opinion this should be **fixed on iOS** or **broken on Android**.   No developer wants to code an app using his favorite platform to switch it to the other platform and have it start crashing.  

The two platforms need to be consistent, I shouldn't be able to write code that works on one platform that will crash the other.  It is extremely discouraging to have an app that runs perfectly on Android totally crash and burn in multiple places on iOS because of small inconsistencies like this.

**Comment by N3ll** [comment]
@NathanaelA - you are totally right! We will surely discuss it in the team and work towards improving it.

**Comment by hamorphis** [comment]
I will investigate this.

**Comment by hamorphis** [comment]
With the new page transitions that I am about to introduce, I will have to revert this change. On both platforms the page will first be loaded and then will become the current page, since there might be a transition involved. Even if there is not transition involved the order should remain the same.

**Comment by NathanaelA** [comment]
@hamorphis as long as it is consistent on all platforms; I'm fine.  :grinning:

**Comment by hamorphis** [comment]
@NathanaelA Yes. It turns out that the natural order of things will be the following on both platforms: navigatingTo, loaded, the page becomes frame.currentPage, navigatedTo

Also, in case you need to show modals in iOS, you should be doing it from the navigatedTo event handler from now on, since I am going to revert the ugly hack that I introduced several months ago in order to make the iOS order the same as the Android order. Since I will change the Android order once I push the Transitions Feature, the iOS order of things will no longer need to be hacked to align it with the Android version.

**Comment by NathanaelA** [comment]
I'm fine with that.   Consistency is what I want (Well world peace, couple million dollars would be nice too :grinning:).  I really hate developing on Android, and having the app crash on iOS because of some inconsistency.      In this case; my code is already using the navigatedTo, since that was what was working when I reported the issue.

**Comment by hamorphis** [comment]
After merging the Page Navigation Transitions(#1473) pull request into the master branch, the page lifecycle is now the following on both platforms.

    navigatingTo event is raised
    loaded event is raised
    the page becomes frame.currentPage
    navigatedTo event is raised

Also, in case you need to show modals in iOS, you should be doing it from the navigatedTo event.

**Comment by davecoffin** [comment]
@hamorphis @N3ll  My problem with this is there is no good way to get the top level Page on iOS. In my app, I have 4 different tabs, which are loaded into their own files like this:

```
<TabView selectedIndexChanged="onSelectedIndexChanged" selectedColor="#30A9FF">
    <TabView.items>
        <TabViewItem title="''" iconSource="{{ selectedIndex == 0 ? 'res://shiftsicon_selected' : 'res://shiftsicon' }}" xmlns:ShiftsView="views/nanny/home/shifts">
            <TabViewItem.view>
                <ShiftsView:shifts />
            </TabViewItem.view>
        </TabViewItem>
        <TabViewItem title="''" iconSource="{{ selectedIndex == 1 ? 'res://photosicon_selected' : 'res://photosicon' }}" xmlns:PhotosView="views/photothumbs">
            <TabViewItem.view>
                <PhotosView:photothumbs />
            </TabViewItem.view>
        </TabViewItem>
        <TabViewItem title="''" iconSource="{{ selectedIndex == 2 ? 'res://messagesicon_selected' : 'res://messagesicon' }}" xmlns:MessagesView="views/messages">
            <TabViewItem.view>
                <MessagesView:messages />
            </TabViewItem.view>
        </TabViewItem>
        <TabViewItem title="''" iconSource="{{ selectedIndex == 3 ? 'res://kidicon_selected' : 'res://kidicon' }}" xmlns:MyKidsView="views/nanny/home/mykids">
            <TabViewItem.view>
                
                <MyKidsView:mykids />
            </TabViewItem.view>
        </TabViewItem>
    </TabView.items>
</TabView>
```

Within the js files for each tab, I have no good way of performing some operation that requires the context of the parent page. For example, if I want to do showModal from within a tab's file, I need to do something like this:

```
parent = page.parent.parent.parent.parent.parent;
if (page.android) parent = page.parent.parent.parent.parent;

parent.showModal...
```

That is hacky, and creates problems when the layout changes. if I console.log currentPage, i get something like `Page<2>`, and if i console log args.parent.parent.parent etc until I find the page, I get my actual page that has an ID of home_page like this `Page<home_page>`

Is there still no cross platform way of getting the displayed page?

**Comment by manijak** [comment]
Is this still valid? I keep getting the `Parent page is not part of the window hierarchy. Close the current modal page before showing another one` error when trying to show a modal in my main view. 

My page instance is from the `navigatedTo` event.

**Comment by giorgi-abashidze** [comment]
**same error to me:**

Parent page is not part of the window hierarchy. Close the current modal page before showing another one
