### ISSUE TITLE
Disable component from build

### ISSUE THREAD

**Issue by ivanff** [NativeScript/NativeScript#7791]
**Environment**
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:

**Describe the bug**
You cannot exclude one component from the bundle. I read the man'ula in the webpack tried to modify webpack.config.js (rules), but I don't like it didn't help(

I'm using the latest version of native script and the standard build environment.please help to completely exclude app / results component and all its files.

[./app.scss] 20.8 KiB {bundle} [built]
[./app/app-routing.module.ts] 1.1 KiB {bundle} [built]
[./app/app.component.ts] 6.34 KiB {bundle} [built]
[./app/app.module.ts] 3.51 KiB {bundle} [built]
[./app/base/base.component.ts] 1.41 KiB {bundle} [built]
[./app/home/home.component.ts] 5.33 KiB {bundle} [built]
[./app/inventory/inventory.component.ts] 7.27 KiB {bundle} [built]
[./app/manual/manual.component.ts] 3.15 KiB {bundle} [built]
**[./app/results/results.component.ts] 5.81 KiB {bundle} [built] NEED EXCLUDLE**
[./app/service/service.component.ts] 6.52 KiB {bundle} [built]
[./app/service/service.modal.component.ts] 2.14 KiB {bundle} [built]
[./app/settings/settings.component.ts] 2.51 KiB {bundle} [built]
[./app/sporttrack-scan/sporttrack-scan.component.ts] 5.17 KiB {bundle} [built]
[./app/sporttrack-settings/sporttrack-settings.component.ts] 3.91 KiB {bundle} [built]
[./main.ts] 2.35 KiB {bundle} [built]

I think it should have a pretty simple solution (((

**Comment by tsonevn** [comment]
Hi @ivanff,
Can you provide some more info about your use case and what you are trying to achieve as a final result? In general, in NativeScript Angular, if a component is not referred inside the code, it will not be included in the bundle.

**Comment by ivanff** [comment]
Sorry.
Pleas close, my IDE add component to import in main app
