### ISSUE TITLE
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState androidx.fragment.app.FragmentManagerImpl.checkStateLoss

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/NativeScript#7793]
**Environment**

 - CLI: rc
 - Android Runtime: 6.1.0

**Describe the bug**
We see that error on some devices (HUAWEI)

**To Reproduce**
The error happens [here](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/core/view/view.android.ts#L657)
No easy way to reproduce it as it iseems to be dependent on the device.

**Additional context**
It seems to be a known issue on a lot of device with calling fragment methods without the ```AllowingStateLoss``` suffix.
https://stackoverflow.com/questions/7575921/illegalstateexception-can-not-perform-this-action-after-onsaveinstancestate-wit
https://stackoverflow.com/questions/12105064/actions-in-onactivityresult-and-error-can-not-perform-this-action-after-onsavei

It seems a solution is to use something like this:
```
//dialog.show(getSupportFragmentManager(), null);
FragmentTransaction ft = getSupportFragmentManager().beginTransaction();
ft.add(dialog, null);
ft.commitAllowingStateLoss();
```

Would you agree on changing it? I can create a PR. It seems it does not change the behavior, only prevent the crash on some devices.

**Comment by farfromrefug** [comment]
@manoldonev indeed it has been removed! too bad. 
Will try and see if the check solves the issue. Wll report here

**Comment by farfromrefug** [comment]
@manoldonev After looking at this i might have found the issue and it is not what we thought.
The issue seems actually to come from the fact that the modal view that i am showing is a ```Frame```. If i remove the ```Frame``` the issue seems to be gone (or i simply did not see it as it does not always happen).

And i found a bug when using a ```Frame``` as i did.  https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/core/view/view.android.ts#L657 here you use the parent ```FragmentManager``` because the view does not have a context yet.
But when dismissing the ```DialogFragment``` https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/core/view/view.android.ts#L227 you use the modally shown ```FragmentManager```. And i think in the case of a ```Frame``` it is not the same one. So i get an error saying the ```FragmentManager``` is not the one handling that ```DialogFragment```

**Comment by manoldonev** [comment]
@farfromrefug yup, opening another issue would be best -- I tried to reproduce the problem with the modal Frame locally but was not successful so far. As for https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/core/view/view.android.ts#L227 -- while the manager here might not be correct I don't think this is causing the error you are experiencing as this if-statement actually does not manipulate fragments (in fact I am not sure whether we need the condition at all or we can just execute its contents always).
