### ISSUE TITLE
WebView cannot open this web page

### ISSUE THREAD

**Issue by Izrab** [NativeScript/NativeScript#7797]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.0
 - Cross-platform modules: 6.1.0
 - Android Runtime: 6.1.0
 - iOS Runtime: 6.1.0
 - Plugin(s):
```
    "nativescript-dev-webpack": "1.2.0",
    "typescript": "3.6.2"
    "nativescript-theme-core": "2.0.17",

```

**Describe the bug**

I created a new core TypeScript project (not Angular or Vue), I added a simple WebView to a simple home page, but I am not able to open this page 
http://aram-village.com/client/login.php 
But I can open http://aram-village.com/ or  http://aram-village.com/about-us/ in the WebView in the NativeScript app.

Note that I am building the app for Android 9 64-bit and have latest version of 
https://play.google.com/store/apps/details?id=com.google.android.webview 

**Expected behavior**
To load the page

**Sample project**
```
<Page class="page"
    navigatingTo="onNavigatingTo" 
    actionBarHidden="true"
    xmlns="http://schemas.nativescript.org/tns.xsd">
    
    <StackLayout>
        <!-- Add your page content here -->
            <WebView  
                loaded="onWebViewLoaded" 
                id="myWebView" 
                src="http://aram-village.com/client/login.php" 
            />

    </StackLayout>
</Page>

```

Note:
I'm aware of new Android and iOS versions not load HTTP connections, I've read this issue https://github.com/NativeScript/NativeScript/issues/6793 
I also tried the each solution with a new clean nuked build, 
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted/50834600#50834600

But did still did not work. Remember that WebView still does open http://aram-village.com/ which is a complete non HTTPS website.

**Comment by nuochong** [comment]
> **Environment**
> Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
> 
> * CLI: 6.1.0
> * Cross-platform modules: 6.1.0
> * Android Runtime: 6.1.0
> * iOS Runtime: 6.1.0
> * Plugin(s):
> 
> ```
>     "nativescript-dev-webpack": "1.2.0",
>     "typescript": "3.6.2"
>     "nativescript-theme-core": "2.0.17",
> ```
> 
> **Describe the bug**
> 
> I created a new core TypeScript project (not Angular or Vue), I added a simple WebView to a simple home page, but I am not able to open this page
> http://aram-village.com/client/login.php
> But I can open http://aram-village.com/ or http://aram-village.com/about-us/ in the WebView in the NativeScript app.
> 
> Note that I am building the app for Android 9 64-bit and have latest version of
> https://play.google.com/store/apps/details?id=com.google.android.webview
> 
> **Expected behavior**
> To load the page
> 
> **Sample project**
> 
> ```
> <Page class="page"
>     navigatingTo="onNavigatingTo" 
>     actionBarHidden="true"
>     xmlns="http://schemas.nativescript.org/tns.xsd">
>     
>     <StackLayout>
>         
>             <WebView  
>                 loaded="onWebViewLoaded" 
>                 id="myWebView" 
>                 src="http://aram-village.com/client/login.php" 
>             />
> 
>     </StackLayout>
> </Page>
> ```
> 
> Note:
> I'm aware of new Android and iOS versions not load HTTP connections, I've read this issue #6793
> I also tried the each solution with a new clean nuked build,
> https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted/50834600#50834600
> 
> But did still did not work. Remember that WebView still does open http://aram-village.com/ which is a complete non HTTPS website.

You may only see the preview in ios, which should be normal in android.

In ios, you need to add an outer layer of containers to wrap the webview for normal display.

```
    <StackLayout>
            <WebView  
                src="http://aram-village.com/client/login.php" 
            />
    </StackLayout>
```

Modified to

```
    <StackLayout>
         <GridLayout>
            <WebView  
                src="http://aram-village.com/client/login.php" 
            />
         <GridLayout>
    </StackLayout>
```

That should solve your problem.

Both HTTP and HTTPS are available.

**Comment by tsonevn** [comment]
HI @Izrab,
Enabling the HTTP connection for [iOS](https://stackoverflow.com/a/30732693/6133327) and [Android](https://stackoverflow.com/a/51902630/6133327) and nesting the WebView in GridLayout, as @nuochong suggested, should solve the issue in your project. If you have a further issue with your local project configuration of WebView component, please use this [StackOverflow thread](https://stackoverflow.com/questions/tagged/nativescript).

**Comment by Izrab** [comment]
This worked for me. Thank you all.
```
    <StackLayout>
         <GridLayout>
            <WebView  src="http://aram-village.com/client/login.php" />
         <GridLayout>
    </StackLayout>

```
