### ISSUE TITLE
Pages appear from Right to Left when device language is set to Arabic or Hebrew

### ISSUE THREAD

**Issue by ashishjain14** [NativeScript/NativeScript#7798]
For a Right to Left language the pages should appear from Left to Right however currently the pages appear from RtoL in RtoL or LtoR languages. This impacts the user experience for users of RtoL language.

**Comment by tsonevn** [comment]
HI @ashishjain14,
Thank you for the provided info. A feature request about {N} RTL support already exists. You can find it [here](https://github.com/NativeScript/NativeScript/issues/7094). If you have some additional info, you can add it as a comment in the existing issue.
Thank you in advance for your cooperation.
