### ISSUE TITLE
Research Font Awesome support

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#78]
_From @ErjanGavalji on January 29, 2015 15:45_

Research if it is possible to have a Font-Awesome module. Check [the respective forum thread](http://www.telerik.com/forums/font-awesome) for more information as well as `ios` and `android` samples!

_Copied from original issue: NativeScript/cross-platform-modules#33_

**Comment by enchev** [comment]
_From @edimoldovan on March 17, 2015 9:23_

There are also these which look interesting:
iOS: https://github.com/alexdrone/ios-fontawesome
Android: https://github.com/JoanZapata/android-iconify

**Comment by sharesoft** [comment]
There's a useful article by Alex Ziskind on using custom fonts with NS in iOS mode...
http://nuvious.com/Blog/2015/5/11/fonts-in-nativescript--yes-you-can#ListingAvailableFonts

I was able to use this approach to get Font Awesome symbols working in an iOS NS app. I don't know enough about Android to say whether something similar could be done there.
