### ISSUE TITLE
can i use nativescript with ionic framework both in one project

### ISSUE THREAD

**Issue by bhandaribhumin** [NativeScript/NativeScript#7802]
i'm using ionic 4 angular project with ngxs so can i used nativescript component in my existing ionic 4 project????

**Comment by dmytro-gokun** [comment]
No. NativScript & Ionic are completely different platforms which are not interoperable. So, you cannot use a NativeScript component in an Ionic project and vice versa.

**Comment by NathanaelA** [comment]
@bhandaribhumin -- If you used The Xplat framework you can make the Angular app work in NS, Web, AND Ionic -- however, Dmytro is correct a NS component  won't work in ionic, and a ionic component won't work in NS.
