### ISSUE TITLE
Not able to run android app after migrated to Nativescript 6 // .  Unable to start activity ComponentInfo{com.dev.totmaster.driver/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.

### ISSUE THREAD

**Issue by shivasaicharan** [NativeScript/NativeScript#7807]
After Migrated to nativescript 6. not able to run android app. i am getting error like blow

System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{com.dev.totmaster.driver/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dev.totmaster.driver/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2932)
System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3010)
System.err: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1707)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loop(Looper.java:192)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6758)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:445)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1083)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1063)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1055)
System.err: 	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
System.err: 	at android.app.Activity.performCreate(Activity.java:7147)
System.err: 	at android.app.Activity.performCreate(Activity.java:7138)
System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2885)
System.err: 	... 9 more

**Comment by tsonevn** [comment]
HI @shivasaicharan,
The given information is not enough to investigate your case. While opening an issue, please follow up the template and provide the requested info:
```
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
<!-- A clear and concise description of what the bug is. Please, explain whether it's a build time error or a runtime error. More detailed logs can be easily obtained by following the instructions in this guide: https://docs.nativescript.org/get-support#how-to-obtain-diagnostic-reports. -->

**To Reproduce**
<!-- Add commands used or steps taken to reproduce the behaviour. -->

**Expected behavior**

**Sample project**
<!-- If possible, provide a link from the [Playground](https://play.nativescript.org) with reproduction of the problem. If not, consider attaching a sample project or link to a repository with such project. -->

**Additional context**
<!-- Add any other context about the problem here. -->

```
