### ISSUE TITLE
Soft Keyboard controller issue on iOS

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#782]
Unless I'm totally messing up all my projects on iOS somehow; when the Android Keyboard comes up the screen shrinks or scrolls to show the field in the visible area, then I can see what I type easily and I know for sure which field I'm in.   

On ios; it just covers over your text fields, this is just plain **ABSOLUTELY HORRIBLE** for the end user.  To me this is a HUGE, HUGE, MAJOR flaw currently; I can't ship any application with the user never being able to see what they type on iOS.

**Comment by emiloberg** [comment]
As I understand it, this has been a major pain for a long time, when it comes to iOS development. I've stumbled across a couple of libraries which tries to mitigate this flaw. E.g. [https://github.com/hackiftekhar/IQKeyboardManager](https://github.com/hackiftekhar/IQKeyboardManager). Could a solution like this be cocoapod'd in?

**Comment by NathanaelA** [comment]
Maybe, I also saw a couple posts on Xamarian forums that dealt with this; I believe the code code be adapted to NativeScript; but at this point I have plenty of other things going on on my plate and already several pull requests that are still pending.    https://forums.xamarin.com/discussion/30336/popup-keyboard-hides-parts-of-the-ui-rather-than-resizing

**Comment by tjvantoll** [comment]
I'll just add a +1 that this is a major problem. IQKeyBoardManager is [available via CocoaPods](https://cocoapods.org/?q=IQKeyboardManager), so now that {N} supports CocoaPods directly I'm going to add giving this a shot to my list.

**Comment by tjvantoll** [comment]
I made a plugin and it *seems* to solve this problem pretty elegantly: https://github.com/tjvantoll/nativescript-IQKeyboardManager. Let me know what you think.

**Comment by N3ll** [comment]
You can also check the IQKeyBoardManager here :https://www.npmjs.com/package/nativescript-iqkeyboardmanager.

**Comment by leocaseiro** [comment]
Thank you so much @tjvantoll. This is one of the best nativescript-plugins I've used so far.
Works so good. It's beautiful! I loved it!

Don't need setup, just install and built it. It's all done!
Awesome!

**Comment by vance** [comment]
TJ strikes again!

**Comment by bhavincb** [comment]
i have getting same problem on android. any idea?
