### ISSUE TITLE
Android release build crashes on opening

### ISSUE THREAD

**Issue by cerealexx** [NativeScript/NativeScript#7820]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.3
 - Cross-platform modules:
 - Android Runtime: 6.0.2
 - iOS Runtime: 6.0.2
 - Plugin(s):
"nativescript-angular": "8.0.2",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-facebook": "^4.1.0",
    "nativescript-fcuuid": "^1.0.2",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-mixpanel": "^2.0.1",
    "nativescript-ngx-shadow": "^6.1.0",
    "nativescript-ngx-slides": "^6.1.0",
    "nativescript-orientation": "^2.2.1",
    "nativescript-pedometer": "^2.0.2",
    "nativescript-plugin-firebase": "9.0.2",
    "nativescript-speech-recognition": "^1.4.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toasty": "^2.0.1",
    "nativescript-ui-gauge": "^5.0.0",
    "nativescript-ui-sidedrawer": "7.0.0",
    "@jnorkus/nativescript-svg": "^1.1.2",
    "@localization/l10n": "^2.1.7",
    "@nstudio/nativescript-camera-plus": "^2.2.0",

**Describe the bug**
`Tns run android` works fine.
`tns build android --key-store-path --key-store-password --key-store-alias --key-store-alias-password --release` builds fine. Then on opening shows during half a second the splash screen and then crashes.

**To Reproduce**
Build release apk with `tns build android --key-store-path --key-store-password --key-store-alias --key-store-alias-password --release`.
Install and open the app.

**Expected behavior**
Not crashing.

**Additional context**
I guess this wont help to know what's happening, but crashing version is available in Play Store: https://play.google.com/store/apps/details?id=com.aboueats.meyo

**Comment by mrpaaske** [comment]
Try to connect your device to the computer and run `adb -d logcat` in the command line, then start  start the app on the device. Maybe it gives some hint to what's wrong.

**Comment by cerealexx** [comment]
@mrpaaske no hint... just:
```
09-16 11:01:35.496  5739  7900 W ActivityManager: crash : com.aboueats.meyo,0
09-16 11:01:35.496  5739  7900 W ActivityManager:   Force finishing activity com.aboueats.meyo/com.tns.NativeScriptActivity
09-16 11:01:35.551  5739  9392 I ActivityManager: Process com.aboueats.meyo (pid 11537) has died: vis  TOP (557,2659)
```

**Comment by cerealexx** [comment]
I found the problem in a dependency... weird that NS didn't throw any errors though...

**Comment by iMarwan-k** [comment]
> I found the problem in a dependency... weird that NS didn't throw any errors though...

Hi there, what dependency that cause this, I'm having the same issue right now

**Comment by cerealexx** [comment]
In my case it was `nativescript-ngx-slides`
