### ISSUE TITLE
Is there any way to position say button on the right of the label as the text from label ends?

### ISSUE THREAD

**Issue by sansphp** [NativeScript/NativeScript#7823]
I am supposed to be positioning the Button alongside the Label but the issue here is that as soon as the text from Label crosses the width of the screen then button positions itself to next line because the Label has taken up the whole width already. In other words, I want a solution which works something like HTML style float:left which allows any other element to position itself on the right if space is available. 

Here is the screen shot of how it looks at the moment:-
[http://digportfolio.com/screenshot.png](url)

Thanks

**Comment by tsonevn** [comment]
HI @sansphp,
In your scenario, you can use a [GridLayout](https://docs.nativescript.org/ui/layouts/layout-containers#gridlayout) container, where you can set two columns. On the first one, you can display the Label and on the second one, you can set the Button. For further questions, please open a [new question ](https://stackoverflow.com/questions/tagged/nativescript )on StackOverflow.
