### ISSUE TITLE
[Tabs][iOS] Tabs get stuck when selecting one by one from tabstrip

### ISSUE THREAD

**Issue by MartoYankov** [NativeScript/NativeScript#7827]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.0
 - Cross-platform modules: 6.1.0
 - iOS Runtime: 6.1.0

**Describe the bug**
When tapping on the tab strip tabs one by one, they get stuck at the second.

**To Reproduce**
Playground example:
https://play.nativescript.org/?template=play-tsc&id=prISaT

1. Tap on second tab.
2. Tap on third tab.
Result: the highlight is stuck on second tab and the page tab isn't slided.

**Expected behavior**
Should move to third tab.

**Comment by felixelgato92** [comment]
Any idea as of when will this be fixed? We really like this component, but we don't want to have a bug like this in our app. Is there any time frame?

**Comment by NickIliev** [comment]
Reported via t. 1453725

**Comment by NickIliev** [comment]
Also reproducible via [this documentation example](https://play.nativescript.org/?template=play-tsc&id=G1eEcU) (coming from [the nested navigation article](https://docs.nativescript.org/core-concepts/nested-navigation#nesting-forward-in-lateral-navigation))
