### ISSUE TITLE
[Tabs][iOS] safe area issue when action bar is below tab bar on iPhone 6

### ISSUE THREAD

**Issue by MartoYankov** [NativeScript/NativeScript#7828]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.0
 - Cross-platform modules: 6.1.0
 - iOS Runtime: 6.1.0

**Describe the bug**
When tapping on the tab strip tabs one by one, they get stuck at the second.

**To Reproduce**
Playground example:
https://play.nativescript.org/?template=play-tsc&id=prISaT

1. Run on iPhone 6.
Result: The Action Bar is half visible

**Expected behavior**
Should either move below tab bar or be hidden by it.

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
