### ISSUE TITLE
How to access component method inside my ios delegate class

### ISSUE THREAD

**Issue by monicaarepo** [NativeScript/NativeScript#7830]
How to access a method from the app component to main.ts file??

I am developing android and ios mobile application using Nativescript angular. I have created a ios delegate class for application onResume. I want to call the native script class component method inside of my ios delegate class. Help me achieve the functionality
`My ios delegate class:
import { android, ios, AndroidApplication, AndroidActivityBundleEventData } from "tns-core-modules/application";

    class MyDelegate1 extends UIResponder implements UIApplicationDelegate{

        constructor(private sharedClass:sharedClass) {
            super();
        }

        public static ObjCProtocols =[UIApplicationDelegate];

        applicationWillEnterForeground(application:UIApplication):void{
            console.log("applicationWillEnterForeground"+application); 
             //how to access here appcomponent SampleFunction()            

        }

        applicationDidEnterBackground(application:UIApplication):void{
            console.log("applicationDidEnterBackground"+application);
        }
    }
`
My nativescript component class

```
` import { Component, OnInit } from "@angular/core";

    export class AppComponent implements OnInit {

      constructor(){}

      ngOnInit(){
    }
       SampleFunction(){
         console.log("Will call from ios delegate class");
        }

}`
```
Help me to fix this issue.

**Comment by Nurgunkalol** [comment]
same, any methods ?

**Comment by tsonevn** [comment]
Hi all, you can send an instance of the owner of the delegate in the delegate's constructor and to save it as a private variable in your delegate class implementation. Check out how it is done for the [TextField](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/text-field/text-field.ios.ts#L17) in the `tns-core-modules`
