### ISSUE TITLE
[Tabs][BottomNav][iOS] Crash when ProxyViewContainer first child of TabContentItem

### ISSUE THREAD

**Issue by MartoYankov** [NativeScript/NativeScript#7834]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.0
 - Cross-platform modules: 6.1.0
 - iOS Runtime: 6.1.0

**Describe the bug**
When having a ProxyViewContainer as first child of TabContentItem, the app crashes. This is very important for Angular. See playground.

**To Reproduce**
Playground example:
https://play.nativescript.org/?template=play-ng&id=Aa11Ia

1. Run on iOS.
Result: There is a crash
```
ERROR:  uncaughtError Error: onMeasure() did not set the measured dimension by calling setMeasuredDimension() ProxyViewContainer(60)
```

**Expected behavior**
Should work

**Comment by diegovincent** [comment]
As a workaround we simply put a `StackLayout` on top of our Angular Component. Since, as you said, it only happens with the first child.

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
