### ISSUE TITLE
Setting color css property on ListPicker causes app to crash

### ISSUE THREAD

**Issue by michalMajkel** [NativeScript/NativeScript#7844]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.2
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
When I set "color" css property on list picker it crashes the app:
i.e.
<ListPicker style="color:#fff" [...]

the exception occurs:

System.err: Calling js method onCreateView failed
System.err: TypeError: this.nativeView.getTextColor is not a function

**To Reproduce**
Set color through css

**Expected behavior**
Text color is changed and the app doesn't crash

**Comment by tsonevn** [comment]
Hi @michalMajkel,
I tested the described case in a sample project with the latest {N} 6.1.1, however, was unable to recreate an issue on my side. For your convenience,  I am attaching the project that I used for testing. You can review it and make the needed changes, that will help us to recreate the issue.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/3630754/Archive.zip)

**Comment by michalMajkel** [comment]
@tsonevn my app is written in Angular rather than Core {N} - didn't mention that before - sorry !

**Comment by tsonevn** [comment]
@michalMajkel, I tested the case in a sample {N} Angular project, however, I am still unable to recreate the issue.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/3631275/Archive.zip)

**Comment by bradmartin** [comment]
related to #7860 @tsonevn and is a build tools fix on android side.
