### ISSUE TITLE
iOS 13: New modal view style doesnt clean up when swiped to close

### ISSUE THREAD

**Issue by davecoffin** [NativeScript/NativeScript#7846]
All latest, xcode 11 and official iOS 13:

When you swipe to close a modal (new native control), frame.topmost().currentPage.modal is not cleared out.

One side effect is this:
Open a modal, swipe to dismiss it, then try to open a dialog. 

This line in dialogs fails:
```
var currentView = dialogs_common_1.getCurrentPage() || application_1.getRootView();
    if (currentView) {
        currentView = currentView.modal || currentView;
```

currentView becomes currentView.modal, which is gone, so the dialog is not presented.

**Comment by davecoffin** [comment]
If anybody finds this and needs a quick workaround:
setting `fullscreen` to `true` on the modal presents the old style, which is not draggable, so doing that fixes the problem, you just lose the nice draggable modal.

**Comment by tsonevn** [comment]
HI @davecoffin,
I was able to recreate the problem with [nativescript-sdk-examples-js](https://github.com/NativeScript/nativescript-sdk-examples-js/tree/master/app/ns-ui-category/modal-view/basics). I will mark the issue as a bug and we will investigate it further.

**Comment by vchimev** [comment]
I'm not sure how to reproduce this ...

**Comment by davecoffin** [comment]
@ADjenkov 
Does #8024  actually fix this? Or just provide an API to not let the user close the modal with a gesture?

**Comment by ADjenkov** [comment]
@davecoffin yes it fixes the problem you've reported and also provides new API to enable/disable it

**Comment by davecoffin** [comment]
Awesome you guys rock!!
