### ISSUE TITLE
Make actionbar consistant (Consistency)

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#785]
Actionbar has a ios.position and android.position.   It really should be just "position" and if you want to override or set it for a specific platform you use ios: or android: in front.   But by using "." you are making this parameter totally inconsistent with the framework and different then pretty much all other control...

**Comment by hamorphis** [comment]
@NathanaelA, do you have an idea about how to determine the cartesian product of these two sets:
```
    /**
     * Represents Android specific options of the action item.
     */
    export interface AndroidActionItemSettings {
        /**
         * Gets or sets the position of the action item in the action bar.
         *  1. actionBar - item is shown in the action bar.
         *  2. actionBarIfRoom - item is shown in the action bar if there is room for it. Otherwise it is put in the popup menu.
         *  3. popup - item is shown in the popup menu.
         */
        position: string;
    }
    
    /**
     * Represents iOS specific options of the action item.
     */
    export interface IOSActionItemSettings {
        /**
         * Gets or sets the position of the action item in the action bar.
         *  1. left - items is shown at the left part of the navigation bar. This is the default value.
         *  2. right - items is shown at the right part of the navigation bar.
         */
        position: string;
    }
```

So we have `actionBar`, `actionBarIfRoom`, and `popup` for Android and `left` and `right` for iOS. If we were to expose a single `position` property directly on the `ActionItem` class what value would you use to write platform-agnostic code?

**Comment by NathanaelA** [comment]
Why not postiion = "left|Actionbar" or "left,ActionBar" use a pipe symbol or "," symbol.  

I'm believe you can use pipe or comma somewhere else is in the Declarative UI (Events maybe???)
