### ISSUE TITLE
TranslateX and TranslateY does not update left and top properties properly

### ISSUE THREAD

**Issue by Lelelo1** [NativeScript/NativeScript#7851]
**Environment**

 - CLI: 6.1.2
 - Cross-platform modules: 6.0.7
 - Android Runtime: 6.0.2
 - iOS Runtime: 6.0.2
 - Plugin(s):

... there is a playground sample though.

**Describe the bug**
The `translateX` and `translateY` does not sync with `left` and `top` property of the view. Which leads to strange behaviour when implementing drag and drop like feature inside AbsoluteLayout and GridLayout.

During the first drag - `left` and `top` of properties are not updated - so that the view jumps back to it's original position at the start of the second drag.

**To Reproduce**
Put a view inside a layout and take `pan: PanGestureEventData` deltaX and deltaY to translate the view with.

**Expected behavior**
The `left` and `top` properties of the view should update and correspond to the translateX and translateY changes.

**Sample project**
https://play.nativescript.org/?template=play-tsc&id=epEkEW

**Additional context**
Potentially related: https://github.com/NativeScript/NativeScript/issues/2161

**Comment by Lelelo1** [comment]
I have tried to manually set `left` and `top`:

```
image.left += pan.deltaX;
image.top += pan.deltaY;
```
but it can't set like that due to `PercentLength`. And I have been struggling with it's conversions.

**Comment by lukesUbuntu** [comment]
Try checking the state add this

` if (pan.state == 2) {
            image.translateX = pan.deltaX;
            image.translateY = pan.deltaY;
      }
`

**Comment by tsonevn** [comment]
HI @Lelelo1,
Check out the `Dragging an Image (Practical Usage)` section of the blog post [**here**](https://www.nativescript.org/blog/drag-and-drop-ui-elements-with-basic-collision-detection), where it is described how to achieve the needed dragging functionality while using  `translateX` and `translateY` properties. For your convenience, I am attaching [**the project**](https://play.nativescript.org/?template=play-tsc&id=epEkEW&v=3) with some edits.
