### ISSUE TITLE
NSData to byte array

### ISSUE THREAD

**Issue by Nurgunkalol** [NativeScript/NativeScript#7852]
Im implemented PKAddPaymentPassViewControllerDelegate.
```
addPaymentPassViewControllerGenerateRequestWithCertificateChainNonceNonceSignatureCompletionHandler(controller: PKAddPaymentPassViewController, certificates: NSArray<NSData>, nonce: NSData, nonceSignature: NSData, handler: (p1: PKAddPaymentPassRequest) => void): void 
```
how to convert NSData to byte array ? 
im tryed: 
```
var len = nonce.length;
var byteData = malloc(len);
memcpy(byteData, nonce.bytes, len);
free(byteData)
var bytearray = NSMutableArray.array();
 for (var i = 0; i < len; i++) {
            console.log("byteData = ", byteData[i]);
            bytearray.addObject(NSNumber.numberWithUnsignedChar(byteData[i]));
  }
```

byteData is undefined, but nonce is not null

**Comment by tsonevn** [comment]
Hi @Nurgunkalol,
I noticed that you are releasing the memory of the pointer with the **free** method, before using it. This might be the issue in your code. Also, following the discussions in [this SO thread](https://stackoverflow.com/a/724365/6133327), It seems that with the first three lines of your code, you have already converted the NSData to a byte array.  I am not sure what you are trying to achieve as a final result. On that matter, I would suggest opening [a new question in StackOverflow](https://stackoverflow.com/questions/tagged/nativescript), where the other {N} community member can help you.
