### ISSUE TITLE
Build failed in android due to google services

### ISSUE THREAD

**Issue by ishaqueahmed-mev** [NativeScript/NativeScript#7854]
Hello,

I am using nativescript-plugin-firebase v10.0.0, and receiving the following error during android build.

```
Gradle build...
         + setting applicationId

FAILURE: Build failed with an exception.

* Where:
Script '/Users/iflair/Documents/Ishaque/menkehorst-mobile-client/node_modules/nativescript-plugin-firebase/platforms/android/include.gradle' line: 93

* What went wrong:
A problem occurred evaluating script.
> Plugin with id 'com.google.gms.google-services' not found.
```

My configs are :
Nativescript : v5.4.2
tns-android : v5.4.0

Also when building and running the app for the first time, it works fine, but then from next onwards, it gives the error. I tried adding various keys and configs in various .gradle files, but to no avail.

Any help would be appreciated.

**Comment by tsonevn** [comment]
Hi @ishaqueahmed-mev,
Try to clear up the project by deleting `platforms`, `node_modules`, `hooks` folders and `package-lock.json` file. Then rebuild the app and check if the issue will appear again. Also, From the provided info it seems that you are using an old {N}. If the problem persists, I would suggest [upgrading](https://docs.nativescript.org/releases/upgrade-instructions) to the newest {N} version and verify if the problem happens again.

**Comment by ishaqueahmed-mev** [comment]
Hello @tsonevn, thanks for the response, I tried the steps which you mentioned above and its working fine now. Also I had to make some changes in the build.gradle file to as sometimes it was throwing AndroidX compatibility issues.

Thanks for the help.
