### ISSUE TITLE
'systemBackgroundColor' not found on object of type 'UIColor'

### ISSUE THREAD

**Issue by samliaw** [NativeScript/NativeScript#7856]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  6.1.2
 - Cross-platform modules:
 - Android Runtime:6.1.1
 - iOS Runtime:6.1.1
 - Plugin(s):
Here is a partial of the package.json
{
  "android": {
    "markingMode": "none"
  },
  "nativescript": {
    "id": "com.softwaremanufacture.ema",
    "tns-android": {
      "version": "6.1.1"
    },
    "tns-ios": {
      "version": "6.1.1"
    }
  },
  "scripts": {
    "lint": "tslint \"src/**/*.ts\"",
    "clean": "rm -rf node_modules platforms hooks platforms",
    "e2e": "node ./node_modules/nativescript-dev-appium/check-dev-deps.js &&  tsc -p e2e  &&  mocha --opts ./e2e/config/mocha.opts ",
    "e2e-watch": "tsc -p e2e --watch"
  },
  "name": "ema",
  "description": "Employer Maid Agency",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~8.1.0",
    "@angular/common": "~8.1.0",
    "@angular/compiler": "~8.1.0",
    "@angular/core": "~8.1.0",
    "@angular/forms": "~8.1.0",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "~8.1.0",
    "@angular/platform-browser-dynamic": "~8.1.0",
    "@angular/router": "~8.1.0",
    "@essent/nativescript-loading-indicator": "^2.3.4-2",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^7.4.0",
    "@ngrx/store": "^7.4.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "moment": "^2.24.0",
    "nativescript": "^5.4.2",
    "nativescript-angular": "^8.1.0",
    "nativescript-background-http": "^3.4.0",
    "nativescript-camera": "^4.5.0",
    "nativescript-cfalert-dialog": "^1.0.14",
    "nativescript-download-progress": "^1.1.0",
    "nativescript-drawingpad": "^3.0.4",
    "nativescript-email": "^1.5.5",
    "nativescript-fancyalert": "^3.0.9",
    "nativescript-feedback": "^1.3.11",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-mediafilepicker": "^1.0.7",
    "nativescript-ngx-fonticon": "^4.2.0",
    "nativescript-permissions": "^1.2.3",
    "nativescript-social-login": "^4.0.1",
    "nativescript-social-share": "^1.5.2",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-listview": "7.0.0",
    "nativescript-ui-sidedrawer": "7.0.0",
    "nativescript-videoplayer": "^4.2.1",
    "nativescript-websockets": "^1.5.3",
    "ramda": "^0.26.1",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.3.3",
    "tns-core-modules": "^6.1.1",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "8.0.0",
    "@nativescript/schematics": "~0.5.0",
    "@ngtools/webpack": "8.0.0",
    "@types/chai": "~4.1.7",
    "@types/mocha": "^5.2.6",
    "@types/mongodb": "^3.1.25",
    "@types/node": "~10.12.18",
    "chai": "4.2.0",
    "eslint": "^5.15.1",
    "eslint-config-google": "^0.12.0",
    "eslint-plugin-angular": "^4.0.0",
    "karma": "4.0.1",
    "karma-chai": "0.1.0",
    "karma-mocha": "1.3.0",
    "karma-nativescript-launcher": "0.4.0",
    "mocha": "^6.1.4",
    "mocha-junit-reporter": "~1.18.0",
    "mocha-multi": "~1.0.1",
    "nativescript-dev-appium": "^5.3.0",
    "nativescript-dev-webpack": "^1.0.3",
    "node-sass": "4.12.0",
    "typescript": "3.4.5"
  },
  "readme": "NativeScript Application"
}

**Describe the bug**

The project runs successfully in Android environment. When I try to run in IOS environment by issuing "tns run ios", i have the following errors: 
/Users/samliaw/tns/samema/platforms/ios/Pods/GMImagePicker/GMImagePicker/GMImagePickerController.m:73:40: error: property 'secondaryLabelColor'
      not found on object of type 'UIColor'
            _pickerTextColor = UIColor.secondaryLabelColor;

I have tried to remove everything by issuing this command "rm -rf nooks platforms node_modules". Then i install again using the following command "npm i", "npm audit fix", "tns platform add ios" and "tns run ios". I still see the same error 
/Users/samliaw/tns/samema/platforms/ios/Pods/GMImagePicker/GMImagePicker/GMImagePickerController.m:73:40: error: property 'secondaryLabelColor'
      not found on object of type 'UIColor'
            _pickerTextColor = UIColor.secondaryLabelColor;

**To Reproduce**

Just run the command "tns run ios". 

**Expected behavior**

**Sample project**

Please give me your address email so I can send you the whole project. 

**Additional context**

**Comment by tsonevn** [comment]
HI @samliaw,
You can send me the project as a private message in [the {N} community slack](https://nativescriptcommunity.slack.com). My nickname is `nikts`.

**Comment by samliaw** [comment]
I uninstall all nativescript and reinstall again. It solves the problem. Therefore, I will close it now.
