### ISSUE TITLE
[BottomNav][iOS]Incorrect color applied to icon/text

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#7862]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1
- Cross-platform modules: 6.1
 - Android Runtime:6.1
 - iOS Runtime:6.1

**Describe the bug**
Have an image that is white. when placed in the bottom nav it becomes colored blue when the tab is active and grey when the tab is inactive. 
For the color of the label it is applied only when the tab is active. When the tab is inactive it becomes the same grey color as the icon. 

**To Reproduce**
https://play.nativescript.org/?template=play-tsc&id=khpHyT

Note the color of the label happens **ONLY** locally when you run the app. On the playground app it works as expected. 

**Expected behavior**
The icon should either remain the color it is, or there should be options to be colored with a specific color. 
The text should get its color from the class/style applied. 

**Additional context**
This is a **regression** from 6.0. 
Related to #6967

**Comment by PeterStaev** [comment]
Seems this relates to update to XCode11. I've just rolled back the project to the previous runtime versions and the problem is still present.

**Comment by PeterStaev** [comment]
Title says iOS :)

After further testing seems the icon coloring a regression in 6.1. But the text coloring seems iOS13/Xcode11 related.

**Comment by bundyo** [comment]
It does also say Android runtime: 6.1 below. :)

**Comment by tsonevn** [comment]
Hi @PeterStaev,
I've rechecked the case and it seems that in your case, you should set [`iosIconRenderingMode`](https://docs.nativescript.org/api-reference/classes/_ui_tab_navigation_tab_strip_.tabstrip#iosiconrenderingmode) to `alwaysOriginal` for the `TabStrip` component. Then the right color will be applied for the images. For your convenience, I am attaching [the project](https://play.nativescript.org/?template=play-tsc&id=khpHyT&v=2) with some changes.

**Comment by PeterStaev** [comment]
Hey @tsonevn , thanks for the provided fix! I can confirm that setting the rendering mode fixes the issue with the icon coloring (so seems there is some default behavior change since 6.0 as it was not needed then). 

But the XCode11/iOS13 problem with the text coloring is still present, even in your provided project. Simply download it locally `tns run ios` on a machine with XCode11 and you will see the problem.

**Comment by MartoYankov** [comment]
It seems that in iOS13, there is a new API for styling the TabBar (https://developer.apple.com/documentation/uikit/uitabbaritem/3198079-standardappearance?language=objc) and weirdly the old way with `setTitleTextAttributesForState` doesn't work as expected. We should try the new API for iOS >= 13.

**Comment by armpogart** [comment]
Any workaround before fixes? How can I set to build the project using old API?

**Comment by PeterStaev** [comment]
When can we expect a fix for this? I was hoping that all iOS13 issues would be fixed for 6.2, but seems that is not the case 😞

**Comment by manijak** [comment]
When using images as Tab icons with `allwaysTemplate` render-mode enabled, it would be preferable if the selected-icon-color was the same as selected-label-color. As it is now, my selected tab icons get a weird blue color that I have no control over, and cannot change. This breaks the design in my case. 

The original `TabView` gets this right and the non-selected/selected image-icons get correct color based on the style settings.

**Comment by NickIliev** [comment]
The issue with the color not being applied for a non-active state is reported [here ](https://github.com/NativeScript/NativeScript/issues/7862)- we are currently working on a solution.

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
