### ISSUE TITLE
[BottomNav][iOS] Styling is completely messed up on device rotation

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#7864]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1
 - Cross-platform modules: 6.1
 - Android Runtime: 6.1
 - iOS Runtime: 6.1
 - Plugin(s):

**Describe the bug**
When you rotate from portrait to landscape mode the styling of tabs/selection is completely messed up. In the example below the second tab becomes unstyled when the rectangles that were previously styling the tabs are moved and split the first tab:
![Screenshot 2019-09-25 at 0 42 29](https://user-images.githubusercontent.com/9464097/65552631-94886580-df2d-11e9-8a9b-27dbb9cb182c.png)

**To Reproduce**
https://play.nativescript.org/?template=play-tsc&id=ug5VWz
rotate device to landscape, tested on iPhoneX

**Expected behavior**
Styling to be applied correctly on device rotation. 

**Additional context**
Related to #6967

**Comment by vchimev** [comment]
Just for the record, this is an issue not only on iOS 13 but on lower versions as well.
