### ISSUE TITLE
Binding to function using $parent and $parents context

### ISSUE THREAD

**Issue by Pandishpan** [NativeScript/NativeScript#7865]
NativeScript core JavaScript & TypeScript

Inside the itemТemplate from the RadListView, using the special keywords $parent or $parents you are not able to bind to a function. 

The returned result for the function is always [object object]

**To Reproduce**
```
<lv:RadListView.itemTemplate>
	<StackLayout>
		<TextField text="{{ $parents['RadListView'].getLabel('dynamic'), $parents['RadListView'].getLabel('dynamic') }}"/>
		<TextField text="{{ $parent.getLabel('dynamic'), $parent.getLabel('dynamic') }}"/>
	</StackLayout>
</lv:RadListView.itemTemplate>
```

**Expected behavior**
Call the function and get the returned data.

**Sample project**
https://stackoverflow.com/questions/58017408/nativescript-data-binding-function-calls-not-working/58094194

**Additional context**
https://docs.nativescript.org/core-concepts/data-binding#binding-to-a-parent-binding-context

**Comment by NickIliev** [comment]
@Pandishpan the binding is supporting passing functions but not alongside with parameters. However,  you could create your own TextField property and pass the parameters through the arguments. Each function called from NativeScript element receives arguments of type **EventData**.

Here is an example:

XML
```XML
<TextField text="{{ $parent.getLabel }} type="dynamic" />
```

and then in the code-behind (e.g., TypeScript)
```TypeScript
import { EventData } from "tns-core-modules/data/observable"
export function getLabel(args: EventData) {
    let textField = args.object as TextField;
    let type = args.object["type"]; // "dynamic"

    // do whatever you want with the type argument
}
```
