### ISSUE TITLE
Create and Save file failing on Android 10

### ISSUE THREAD

**Issue by AmithRamesh** [NativeScript/NativeScript#7866]
**Environment**
Component nativescript has 6.1.2 version.
Component tns-core-modules has 6.1.1
Component tns-android has 6.1.1 
Component tns-ios has 6.1.1 

**BUG**
The issue is only with **Android 10**.
Trying to create a folder or trying to save a file to DIRECTORY_DOWNLOADS fails.
```

     createFolderForFiles() {
        try {
            /** Getting the Android Download directory */
            this.androidDownloadsPath =android.os.Environment.getExternalStoragePublicDirectory(android.os.Environment.DIRECTORY_DOWNLOADS).toString();
            /**  Creating or getting a folder in Android Download directory */
            this.path = fs.path.join(this.androidDownloadsPath, "myFolder");
            this.folder = fs.Folder.fromPath(this.path);
        } catch (error) {
            console.log("ERROR: Creating folder: " + error);
        } 
    }

```

RESULT: ERROR: Creating folder: Failed to create new java File for path **/storage/emulated/0/Download/myFolder**

Similarly, trying to download and open a file with Intent Chooser fails with the following error.

```

       try {
                    let intent = new android.content.Intent(android.content.Intent.ACTION_VIEW);
                    // let context = application.android.currentContext;
                    let context = application.android.context;
                    let mimeType = this.findExtension(extension);
                    /*
                    mimeType = mimeType.getMimeTypeFromExtension(extension.replace(".", 
                    "").toLowerCase());
                   */
                    /** Grant permission for third party apps to read the content of this file */
                    intent.addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK);
                    intent.addFlags(android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION);
                    
                    let chooserIntent = android.content.Intent.createChooser(intent, title);
                    chooserIntent.addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK);
              chooserIntent.addFlags(android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION);
                    /** Set the file content URI using Android native APIs */
                    intent.setDataAndType(androidx.core.content.FileProvider.getUriForFile(context, context.getApplicationContext().getPackageName() + ".fileprovider", new java.io.File(file.path)), mimeType);
                    context.startActivity(chooserIntent);
                } catch (e) {
                    console.log("ERROR: Cannot open file " + e);
                    return false;
                }
```
ERROR: Cannot open file Error: Cannot save file with path: **/storage/emulated/0/Download/myFolder/MyFile.pdf.**
Note: Observe the '.' after the extension(.pdf.)

Are there any new additional changes on Android? Or am I missing something?
Please help. Thank you.

**Comment by tsonevn** [comment]
Hi @AmithRamesh,
Make sure that you have added the needed [permissions](https://developer.android.com/training/data-storage/files/external-scoped) to write and read from the storage.

**Comment by AmithRamesh** [comment]
Hi @tsonevn,
Thank you. 
I have added the following permissions to my manifest file:
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

```
Able to save and open the file in Android 9 and below. Issue only with Android 10.
And also now, added the following as specified in the Android doc you shared:
```
<manifest ... >
  <!-- This attribute is "false" by default on apps targeting
       Android 10 or higher. -->
  <application android:requestLegacyExternalStorage="true" ... >
    ...
  </application>
</manifest>
```

Basically I am not an Android developer, so thought I will opt out of scoped storage concept until I figure out what it is. But facing the same errors even after making this change.

So does that mean I need to add this permission -  ACCESS_MEDIA_LOCATION ??
If I use the above permission, should I use the android:requestLegacyExternalStorage as well?

I am confused!!

**Comment by NathakornJ** [comment]
I am now facing a similar issue that <Image src="path to image media file" /> does not show up. This is only an issue on Android API Level 29

When I add <application android:requestLegacyExternalStorage="true" ... > then the issue is resolved.

So my question: does Nativescript 6.1.2 already support Android 10 scoped storage?

**Comment by AmithRamesh** [comment]
Hi @tsonevn,

Yes this works with <application android:requestLegacyExternalStorage="true" ... >
Just had to clean platform and re run.

**Comment by SaifulZiko** [comment]
@AmithRamesh Have you solved the issue by adding <application android:requestLegacyExternalStorage="true" ... > in your AndroidMainfest.xml file? I have the similiar problem to open and share odf files :(

**Comment by TemaSM** [comment]
@SaifulZiko setting `android:requestLegacyExternalStorage="true"` worked just fine for me

**Comment by bingocode** [comment]
setting android:requestLegacyExternalStorage="true" worked , thanks

**Comment by sunil-singh-chaudhary** [comment]
now after adding android:requestLegacyExternalStorage="true" also not create file or mkdir , dont know but working inside picture folder but not on the root folder dnt know ??

**Comment by dev071089** [comment]
Getting 'IllegalStateException: not one of standard directory'  while downloading a file on Android 10. 
Also added android:requestLegacyExternalStorage="true"

**Comment by ganesanNT51** [comment]
I am to get select multiple contact .That is working fine andorid 9.0 till. But Android version 10 not working 
android:requestLegacyExternalStorage="true"   -- This also not working

**Comment by arturikoX** [comment]
Hi,
I have
`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>`
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
As well as
`android:requestLegacyExternalStorage="true"`

But can't download files to Download folder, any help will be apricated ..
Android 10 + 11..

thanks

**Comment by erKaranjeet** [comment]
I also added android:requestLegacyExternalStorage="true" in manifest file. But the problem is same in android 10 phones. If i tried with emulator it works but in real phone it doesn't work.

**Comment by Renphil** [comment]
After adding android:requestLegacyExternalStorage="true", I've also changed the knowFolders.documents() path for it to work.
`fs.knownFolders.documents()._path = folderPath;`

**Comment by triniwiz** [comment]
Currently on the next version you can use the [new android file api](https://github.com/NativeScript/NativeScript/commit/ab32aeaaa3715e5178f349646f14a632c771ce61) to create files


```ts
let lastDownload: File;
export function createFileInDownloads() {
	if (!global.isAndroid) {
		return;
	}
	const width = Screen.mainScreen.widthPixels;
	const height = Screen.mainScreen.heightPixels;
	const randomImageUrl = `https://picsum.photos/${width}/${height}.jpg?random=${Date.now()}`;

	Http.getFile(randomImageUrl).then((result: File) => {
		let file = File.android.createFile({
			directory: AndroidDirectory.DOWNLOADS,
			name: `${Date.now()}.jpg`,
			mime: 'image/jpeg',
			relativePath: `NativeScript`,
		});
		result
			.copy(file.path)
			.then((done) => {
				lastDownload = file;
				console.log('done: ' + done + '\n' + 'Original path: ' + result.path + '\n' + 'Copied to: ' + file.path + '\n' + 'Original size: ' + result.size + '\n' + 'Copy size: ' + file.size + '\n');
				alert(`File saved in ${AndroidDirectory.DOWNLOADS}/NativeScript`);
			})
			.catch((error) => {
				console.error(error);
			});
	});
}
```
