### ISSUE TITLE
Windows - Genymotion error

### ISSUE THREAD

**Issue by maku** [NativeScript/NativeScript#787]
I would like to work with tns and genymotion on windows 7. 
e.g.
```
tns run android --emulator --geny "device-name"
```
So I have to set the genymotion dir to the PATH (e.g. set PATH=C:\Program Files\Genymobile\Genymotion;%PATH%)
When I have genymotion on the path tns commands don't work anymore (e.g tns run, tns doctor). I get the following error:
```
TypeError: Cannot read property 'value' of null
    at C:\Users\k1708\AppData\Roaming\npm\node_modules\nativescript\lib\common\sysinfo.js:110:36
    at ChildProcess.<anonymous> (C:\Users\k1708\AppData\Roaming\npm\node_modules\nativescript\node_modules\winreg\lib\registry.js:374:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```
When I remove from genymotion from the path tns commands works....

**Comment by NathanaelA** [comment]
I would recommend you put Geny at the end of your path.  It has its own "adb" program which in the past caused me issues.   If you type "SystemPropertiesAdvanced" then click the "Environment Variables" button at the bottom of the screen, then you can edit your user or system variable **Path** and then append **;C:\Program Files\Genymobile\Genymotion** to it.   After that close it and close the command window.  Then re-open a command window and type echo %PATH% and see if it is now in the path.  If it isn't you will need to reboot.
Once it shows up in your path; then you can try typing **genyshell** from the command line and see if it works.   Then finally go back to tns and see if it still works.

**Comment by maku** [comment]
O.k. yeah the trick is to append genymotion to the end of the path. 
Thank you!!

**Comment by teobugslayer** [comment]
@maku, @NathanaelA,

I think this is a bug / mis-feature in Genymotion itself. It comes with an executable named "reg.exe", which collides with the Windows system executable. The end result is, if the genymotion comes first in the PATH, random administrative scripts and, incidentally, {N} are broken.
