### ISSUE TITLE
Apk crashes in release mode, works in debug. Snapshot also fails

### ISSUE THREAD

**Issue by wpatter6** [NativeScript/NativeScript#7873]
**Environment**
✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.1.2 version and is up to date.
✔ Component tns-core-modules has 6.1.1 version and is up to date.
✔ Component tns-android has 6.1.1 version and is up to date.
✔ Component tns-ios has 6.1.1 version and is up to date.

Package.json:

https://gist.github.com/wpatter6/8de105db2282fe0e935866c2f7007c02

My webpack.config.js is the default produced by nativescript-dev-webpack@1.2.0

**Describe the bug**
My app runs well in debug mode, but when I try to build it for release on android, the app crashes immediately after starting.  The same version runs properly on iOS in testflight.

Here is the logcat message that is produced when this happens:

https://gist.github.com/wpatter6/ae4c44429bc6e8757c45d8706bde4d56

Here is the [out.txt](https://github.com/NativeScript/NativeScript/files/3660757/out.txt) produced by adding the `--log trace > out.txt` flag to the run command.

The second part which is possibly related, when I try to build in release mode with the `--env.snapshot` flag, it fails with the following message:
`Error: Could not load CSS from app.css: TypeError: e is not a function`

Followed by a longer error message which can be seen here:

https://gist.github.com/wpatter6/fd13c32e38a0f1361c033dcc46b60c53

**To Reproduce**
I am running the following bash script to run the app (including `--env.snapshot` for the second issue):

```
rm -rf platforms/android
rm -rf node_modules
rm -rf hooks

npm install

tns run android --log trace > out.txt --env.sourceMap --bundle --clean --release --key-store-*
```

**Additional context**
I recently migrated NS from 5x to 6.1.2.  Unfortunately though, rolling NS version back does not seem to make it work again.

I have tried the solutions listed in this issue: https://github.com/NativeScript/NativeScript/issues/3257

It also seems similar to this issue, but I cannot do the same workaround because my project is not in Angular: https://github.com/NativeScript/NativeScript/issues/7863

Please help! I have been trying to figure out this issue for several days now and I am at a loss for how to troubleshoot this.

**Comment by NickIliev** [comment]
@wpatter6 can you please post the content of your project's `package.json` - your dependencies, `nativescript-dev-webpack` and the configs file (webpack.config.js) should be updated to the latest version.

**Comment by wpatter6** [comment]
Hi, my package main can be found here: https://gist.githubusercontent.com/wpatter6/8de105db2282fe0e935866c2f7007c02/raw/6d898e119f33d61714ca4fefa61ce26bf2f01d7f/package.json

And my webpack config is indeed up to date and unmodified.  I'll post it if needed as well once I'm off mobile. Thanks

**Comment by wpatter6** [comment]
@NickIliev Here is a link to the full webpack.config.js:

https://gist.github.com/wpatter6/1d80b1232ed0c2b8b65690ca93e62786

Please let me know what other info you need or any other paths I can take to troubleshoot this, thanks

**Comment by wpatter6** [comment]
Adding more files that might help give a direction.  I believe the APK should have all optimization/uglifying disabled so hopefully it will give some detail (though logcat didn't seem to change...)

APK: [app-release.apk.zip](https://github.com/NativeScript/NativeScript/files/3687293/app-release.apk.zip)
Full logcat dump: [logcat.txt](https://github.com/NativeScript/NativeScript/files/3687296/logcat.txt)

Let me know if any other info is needed to remove the 'needs more info' tag on this issue.

**Comment by wpatter6** [comment]
So I believe I've narrowed down the issue here.  It is in the minification/obfuscation that I was doing which is detailed for Android [here](https://developer.android.com/studio/build/shrink-code).

Here is the current version of piece in my `app.gradle` with the 
buildTypes property that is apparently causing the issue commented out:

```gradle
// Add your native dependencies here:

android {
  defaultConfig {
    minSdkVersion 21
    generatedDensities = []
    applicationId = "com.willweb.clicker"
  }
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }  
  /* buildTypes { // THIS CAUSES RELEASE MODE ERROR ON APP LAUNCH
    release {
      // Enables code shrinking, obfuscation, and optimization for only
      // your project's release build type.
      minifyEnabled true

      // Enables resource shrinking, which is performed by the
      // Android Gradle plugin.
      shrinkResources true

      // Includes the default ProGuard rules files that are packaged with
      // the Android Gradle plugin. To learn more, go to the section about
      // R8 configuration files.
      proguardFiles getDefaultProguardFile(
        'proguard-android-optimize.txt'),
        'proguard-rules.pro'
    }
  } */
}
```

Fortunately, removing this does allow me to build for release mode, but unfortunately with a much larger file size!  So my question here becomes, how do I enable those features within a Nativescript app?  

I see [this question](https://github.com/NativeScript/android-runtime/issues/440) regarding proguard from a couple of years ago, is there any update on that? I'm also not seeing much with regards to the `minifyEnabled` and `shrinkResources` when I search google, is there a way to enable those without crashing the app?

**Comment by NickIliev** [comment]
@wpatter6 NativeScript provides tools to optimize the app size and code like Uglifing, AOT (for Angular), Snapshots (only for release Android build on MAC) and Webpack (enabled by default)

```
tns run android --env.uglify --env.aot --env.snapshot --releae <release-params-follows-here>
```

Apart from that, you could[ build the app with Android App Bundle](https://docs.nativescript.org/angular/tooling/publishing/android-app-bundle) which will create a bundle file with lower file size on the client's side.

**Comment by gustavost26** [comment]
Do you already have a definitive answer to this situation?

I'm using the R8 evolution of (ProGuard) but the APK is crashing.
