### ISSUE TITLE
iOS13 - Webview throws error on startup

### ISSUE THREAD

**Issue by moebiusmania** [NativeScript/NativeScript#7876]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: **6.1.2**
 - Cross-platform modules:
 - Android Runtime: **6.0.0**
 - iOS Runtime: **6.1.1**
 - Plugin(s):

**Describe the bug**
Hi, after updating to iOS13 (also 13.1) when our application uses a Webview it doesn't get initialised and throws the following error:
```
CONSOLE LOG file:///node_modules/tns-core-modules/utils/utils.js:48:0: utils.ios.getter() is deprecated; use the respective native property instead
CONSOLE ERROR file:///node_modules/@angular/core/fesm5/core.js:5847:0: ERROR TypeError: undefined is not an object (evaluating 'this.webView.ios.constructor')
```
on iOS 12 and Android it still works as expected. 

**To Reproduce**

**Expected behavior**
To work as on iOS 12 and Android

**Additional context**
We are also using `"tns-core-modules": "6.0.1"`, I've tried to update to a more recent version but beside not solving the webview issue I got some changes on various UI elements that needs to be refined so I've sticked with 6.0.1 .

Any help or suggestions are appreciated, thanks!

**Comment by tsonevn** [comment]
Hi @moebiusmania,
Can you send us a sample project, where the issue can be reproduced?

**Comment by moebiusmania** [comment]
@tsonevn unfortunately I can't share the source code of the related project since it's our company main mobile app. 

I've tried by creating a new TNS + Angular project from scratch and the webview on the iOS13 simulator it's working, so the issue seems to be related only on existing project migrated from previous TNS & Angular versions to latest ones.
