### ISSUE TITLE
Routing is not working on NavigationButton 

### ISSUE THREAD

**Issue by jasoniem9246** [NativeScript/NativeScript#7879]
**Environment**
 - CLI: 6.0.2
 - iOS Runtime: 6.0.2

**Describe the bug**
I want to use NavigationButton to navigate to certain page, but it always returns to the previous page. 
I have tried 

1. <NavigationButton text="Back" [nsRouterLink]="['/home]"></NavigationButton>
2. <NavigationButton text="Back" (tap)="goBack()"></NavigationButton>

Both ways are not working. 

**Expected behavior**
can navigate to certain page not previous page only.

**Comment by lukesUbuntu** [comment]
can you provide a test sample of your app on playground or git repo, also in your first example you are missing  `'`

Should be eg :
`
<a [nsRouterLink]="["/user"]">link to user component</a>
`

**Comment by NickIliev** [comment]
The `NavigationButton` on iOS will always navigate back - this functionality can not be overwritten (see [here](https://docs.nativescript.org/angular/ui/ng-components/action-bar#navigationbutton)). The limitation comes from the native iOS API not from NativeScript. If you want another navigation you need to create different ActionItem or your own custom button.
