### ISSUE TITLE
GridLayout OverLap in TabView

### ISSUE THREAD

**Issue by nitishsainani** [NativeScript/NativeScript#7882]
I am working in Tab View with GridLayout with a dialer which requires a 3*3 Layout but the gridLayout is overlapping with the following code.
```
<GridLayout height="100%" width="100%" backgroundColor="red" rows="*,*,*" colums="*,*,*>
            <Label text="0, 0" row="0" col="0" />
            <Label text="0, 1" row="0" col="1" />
            <Label text="0, 2" row="0" col="2" />
            <Label text="1, 0" row="1" col="0" />
            <Label text="1, 1" row="1" col="1" />
            <Label text="1, 2" row="1" col="2" />
            <Label text="2, 0" row="2" col="0" />
            <Label text="2, 1" row="2" col="1" />
            <Label text="2, 2" row="2" col="2" />
</GridLayout>
```

Here is the playground link:
https://play.nativescript.org/?template=play-js&id=khYelO

![Screenshot 2019-09-30 at 11 37 53 PM](https://user-images.githubusercontent.com/37032957/65904108-5f6f8d80-e3db-11e9-8ffa-de00801e1b8d.png)

**Comment by tsonevn** [comment]
HI @nitishsainani,
There is a mistake in the XML inside the attached project. Replace `colums` with `columns` in the opening `GridLayout` tag and the `Labels` will be ordered correctly.
