### ISSUE TITLE
App crash in android

### ISSUE THREAD

**Issue by ishaqueahmed-mev** [NativeScript/NativeScript#7885]
Hello,

I am trying to build my {N} app in android, but for some reason it just keeps on crashing, after adding firebase plugin.

My configurations are:
Nativescript : 5.4.2
android : 5.4.0
tns-core-modules : 5.2.2
firebase-plugin: 10.0.0

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:23:2-50:16 to override.`

I tried adding the following lines in the manifest files as it says in error:
`
tools:replace="android:appComponentFactory"
android:appComponentFactory="@string/app_name"
` 
but the error still persists.

Any help would be appreciated.
Thanks.

**Comment by NickIliev** [comment]
Try using previous version of nativescript-plugin-firebase - I think version 10.0.0 is compatible with NativeScript 6. Then make a clean rebuild

```
rm -rf node_modules platforms hooks webpack.config.js
npm i nativescript-plugin-firebase@9.1.1 --save
npm i
tns platform add android@5.4.0
tns run android
```

Closing the issue as related yo tour specific configuration but if you are still experiencing this one you can ping me in the community slack channel (nickname: **_niliev_**)
