### ISSUE TITLE
1.30 Error in Page Navigating Events order!

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#789]
Man, v1.3 is just causing me all sorts of issues.  As a work around to #779, I had to move the ShowModal code into the NavigatedTo event from the loaded event on iOS.   So that the page would be setup properly before I called the ShowModal on the page.   Well, guess what; on Android the  **onNavigatingTo** actually fires BEFORE the pageLoaded event during startup.   So now my code that does the initialization on my main screen so that the showModal can work properly isn't ran before it tries calling the showModal.  Argh!

We need to get this fixed; in no cases should the onNavigatedTo event fire before the pageLoaded event.   Please note this as far as I can tell ONLY occurs on the initial application bootup of the main screen.   The events are in the correct order during the normal usage of the application.

**Comment by hamorphis** [comment]
After merging the Page Navigation Transitions(https://github.com/NativeScript/NativeScript/pull/1473) pull request into the master branch, the page lifecycle is now the following on both platforms.

 - **navigatingTo** event is raised
 - **loaded** event is raised
 - the page becomes frame.**currentPage**
 - **navigatedTo** event is raised

Also, in case you need to show modals in iOS, you should be doing it from the **navigatedTo** event.
