### ISSUE TITLE
[Feature] ability to style the border-bottom of new Tabs component via CSS (equivalent to android-selected-tab-highlight-color for the old TabView)

### ISSUE THREAD

**Issue by felix-idf** [NativeScript/NativeScript#7897]
**Is your feature request related to a problem? Please describe.**
Right now, you can style only the color of the Label and the Image within the TabStripItem, but there seems to be no equivalent to _android-selected-tab-highlight-color_ from the old TabView component.

See the following image:
![TabsIssue_Android](https://user-images.githubusercontent.com/6443021/66049429-ac627980-e52b-11e9-904d-285e658cb904.PNG)

At the top you see the old TabView and you see that selected items not only have a custom text-color, but also an orange 'strip' at the bottom, that is styled through:
android-selected-tab-highlight-color: #d69a46;

At the bottom you see the new Tabs component and you see that there is also a 'strip' at the bottom of a selected item, but it has the default blue color.

Sample project:
[NSTabsIssue.zip](https://github.com/NativeScript/NativeScript/files/3681421/NSTabsIssue.zip)

**Describe the solution you'd like**
It would be nice, if we could set the color of the strip in CSS for Android and iOS (as a selected item in the new Tabs component on iOS also has the strip at the bottom).

**Comment by tsonevn** [comment]
Hi @felix-idf,
This feature is already available. I've just published a new version of {N} docs, where the usage of TabStrip's`highlight-color` property via CSS is described. Check out the article [here](https://docs.nativescript.org/ui/components/tabs#styling).

Hope this helps.

**Comment by felix-idf** [comment]
@tsonevn thats exactly what I wanted to achieve.
Thanks for adding this to the docs.
