### ISSUE TITLE
Android 9 ( v-for not working ) ( watch child component not not working )

### ISSUE THREAD

**Issue by monstrikus** [NativeScript/NativeScript#7898]
"V-for" does not work in android 9! When rendering the "page". "v-for" once draws all the elements of the list. When changing the array, does not draw! as if nothing had happened!

Android 9! when changing the "props" of the child component "watch" does not work. No reaction. The console is silent.

**Comment by monstrikus** [comment]
Android 9, GEN_RU_A5_2019_V1.0, 
model: ZTE Blade A5 2019

**Comment by tsonevn** [comment]
Hi @monstrikus,
For {N} Vue problems please use [nativescript-vue](https://github.com/nativescript-vue/nativescript-vue/issues) repository
