### ISSUE TITLE
Enable comments in JavaScript sample applications

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#79]
_From @valentinstoychev on January 22, 2015 13:3_

Now the cuteness sample app lack comments inside the source code.

_Copied from original issue: NativeScript/cross-platform-modules#23_

**Comment by mikebranski** [comment]
Comments would have gone a long way to helping understanding a lot of what is going on. I converrted the cuteness sample app to work with the NativeScript CLI and heavily commented things as I figured out what they did. Maybe I can help here and add some documentation for folks like me who are completely new to NativeScript.

**Comment by valentinstoychev** [comment]
Merged comment in #216.
