### ISSUE TITLE
Error: CALayer position contains NaN: [19.5 nan]

### ISSUE THREAD

**Issue by aranmohyeddin** [NativeScript/NativeScript#7908]
**Environment**
```
    "tns-android": {
      "version": "6.1.2"
    },
    "tns-ios": {
      "version": "6.1.2"
    }
  },
  "dependencies": {
    "@nstudio/nativescript-cardview": "^1.0.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "@vue/devtools": "^5.1.1",
    "axios": "^0.19.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-plugin-firebase": "^10.0.1",
    "nativescript-social-share": "^1.5.2",
    "nativescript-socketio": "^3.3.1",
    "nativescript-theme-core": "^2.0.23",
    "nativescript-toasty": "^2.0.1",
    "nativescript-ui-autocomplete": "^5.1.1",
    "nativescript-videoplayer": "^4.2.1",
    "nativescript-vue": "^2.4.0",
    "nativescript-vue-devtools": "^1.2.0",
    "tns-core-modules": "^6.1.0",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/preset-env": "^7.6.2",
    "babel-loader": "^8.0.2",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "^1.0.0",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "^1.2.1",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.1.0",
    "terser-webpack-plugin": "^1.1.0",
    "vue-loader": "^15.2.6",
    "webpack": "^4.41.0",
    "webpack-bundle-analyzer": "~2.13.1",
    "webpack-cli": "^3.3.8"
  }
```
Everything is latest version afaik.
```
$ tns --version
6.1.2
```

**Describe the bug**
> *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Error: CALayer position contains NaN: [19.5 nan] at setFrame(file:///node_modules/tns-core-modules/ui/core/view/view.js:129:27) at _setNativeViewFrame(file:///node_modules/tns-core-modules/ui/core/view/view.js:129:27) at layoutNativeView(file:///node_modules/tns-core-modules/ui/core/view/view.js:165:33) at layout(file:///node_modules/tns-core-modules/ui/core/view/view.js:66:34) at layoutChild(file:///node_modules/tns-core-modules/ui/core/view/view-common.js:936:21) at file:///node_modules/tns-core-modules/ui/layouts/stack-layout/stack-layout.js:112:51 at file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:136:29 at _eachLayoutView(file:///node_modules/tns-core-modules/ui/core/view/view-common.js:1018:24) at file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:134:31 at eachChildView(file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:34) at eachLayoutChild(file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:133:27) at layoutVertical(file:///node_modules/tns-core-modules/ui/layouts/stack-layout/stack-layout.js:110:29) at onLayout(file:///node_modules/tns-core-modules/ui/layouts/stack-layout/stack-layout.js:82:32) at layout(file:///node_modules/tns-core-modules/ui/core/view/view.js:74:26) at layoutChild(file:///node_modules/tns-core-modules/ui/core/view/view-common.js:936:21) at file:///node_modules/tns-core-modules/ui/layouts/stack-layout/stack-layout.js:140:51 at eachLayoutChild(file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:143:21) at layoutHorizontal(file:///node_modules/tns-core-modules/ui/layouts/stack-layout/stack-layout.js:138:29) at onLayout(file:///node_modules/tns-core-modules/ui/layouts/stack-layout/stack-layout.js:85:34) at layout(file:///ap<\M-b\M^@\M-&>

Can you just give me some hints on what can this error possibly mean? I'm totally clueless, if you describe the meaning and some possible causes of it I will be able to solve it. But right now my app just crashes out of nowhere and I literally have no clue for where to look for the problem. It works perfectly fine on android, I only have this issue on ios.

**Comment by NickIliev** [comment]
@aranmohyeddin if possible please share a demo app that can demonstrate the issue so we could investigate further.

**Comment by slolam** [comment]
@NickIliev,

I too am getting the same error leading to crash however not happening consistently. 

After digging into it further I learnt that the error is coming from one of my custom layout component. The cause was that the _onLayout_ method is being called out of order without calling the _onMeasure_ method first. Hence the component does not have proper measured height which lead to this error and crash. 

I am not sure why it is called out of order, but will keep you guys posted.

**Comment by ejlocop** [comment]
@rnmhdn Hi, I'm getting the same error as yours. did you manage to fix this issue? may I know what you did to resolve this? 

Thanks

**Comment by rnmhdn** [comment]
I'm sorry. I do not remember.
