### ISSUE TITLE
iOS Tap Event Propagation Is Inverted Between iOS12 and iOS13

### ISSUE THREAD

**Issue by Logikgate** [NativeScript/NativeScript#7912]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.2
 - Cross-platform modules: 6.1.1
 - Android Runtime: 6.1.2
 - iOS Runtime: 6.1.1
 - Plugin(s): None

**Describe the bug**
The order of execution of Tap event handlers is inverted between iOS12 and iOS13 using NS6. 

**To Reproduce**
Place a tap event handler on a TextField (or TextView) and on its parent layout container. Click on the TextField on a device running iOS12 and then again on a device running iOS13. On iOS12 the order of execution is TextField and then Parent. On iOS13 the order of execution is Parent and then TextField. See playground below.

**Expected behavior**
The order of execution should be TextField then Parent

**Sample project**
[Playground](https://play.nativescript.org/?template=play-tsc&id=BqnvGh)

**Comment by tsonevn** [comment]
HI @Logikgate,
I tested the provided project on my side while using {N} CLI and build it locally. However, I was unable to recreate a problem with event propagations on different iOS versions. For your convenience, I am attaching GIF file, that demonstrates the behaviour on my side. 
![Screen Recording 2019-10-08 at 8 06 28 AM](https://user-images.githubusercontent.com/17448734/66369131-d1c80b00-e9a3-11e9-8243-0849298a1190.gif)

Keep in mind that [Playground uses PubNub](https://www.nativescript.org/blog/architecture-of-the-nativescript-playground) as a service, which transfers the data between the devices. This service may return the callback results in a different order. On that matter, this is something which does not depend on NativeScript.

Hope this helps.
