### ISSUE TITLE
TextField focus freezes the app on iOS 13 

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#7919]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: latest
 - Cross-platform modules: 6.1.1
 - Android Runtime: n/a
 - iOS Runtime: 6.1.0

**Describe the bug**
When a TextField is focused the app is freezing - happening on iOS 13 emulator (iPhone 11 Max Pro).

**To Reproduce**
start the project and focus the text field.
https://github.com/NickIliev/NS-Issues-2019-I/tree/master/NativeScript/test-tf-ios

**Expected behavior**
Not to crash/freeze

**Sample project**
https://github.com/NickIliev/NS-Issues-2019-I/tree/master/NativeScript/test-tf-ios

**Comment by manoldonev** [comment]
@NickIliev cannot reproduce the issue on iOS 13.1 simulator now.

**Comment by NickIliev** [comment]
Issue resolved after using the latest 13.1 emulators

**Comment by jscti** [comment]
@NickIliev  Reproduced on a 13.3 simulator

**Comment by FengLin96** [comment]
@jscti re-open the simulator solved my problem.
