### ISSUE TITLE
Webpack Module not found: Error  Can't resolve '~/App-vd/page' 

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#7920]
What does the following error mean, which module is wrong ?:

ERROR in ./App-vd/page/pageTitleEdit.xml
Module not found: Error: Can't resolve '~/App-vd/page' in 'C:\Users\Jokro\Software\NativeScript\MemoTalks0.0.1\app\App-vd\page'
 @ ./App-vd/page/pageTitleEdit.xml 1:59-83 1:163-187 1:251-275 1:355-379
 @ . sync (?<!\bApp_Resources\b.*)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$
 @ ./app.ts

pageTextEdit.XML contains (starting at line 1 with comment):
`

<Page xmlns="http://www.nativescript.org/tns.xsd" navigatingTo="onNavigatingTo" class="page" xmlns:kt="nativescript-keyboard-toolbar">
 <Page.actionBar>  <ActionBar class="action-label" title="{{appName}}"/>  </Page.actionBar>

<GridLayout>   

            <GridLayout columns="*,*,*,*"   rows="300,*,*,*,*"  class="memo_background"  width="100%" height="100%"    >

             
              <StackLayout 
                     tap="{{onTapEditField}}" 
                     row="0" col="0" colSpan="4" 
                     class="{{options.themeDark,options.themeDark ? 'memo_content_dark': 'memo_content'}}" 
                     >
                      <Label id="ID_UNFOCUS"/> 
                      <Label  text="{{action}}"
                              class="page_action"
                              />
                      <Label  text="{{map.nr, map.nr+' '}}"
                              class="memo_nr"
                              />
                       
                        <TextView 
                                id="pageCommonInput.editField.text"
                                text="{{editField.text}}"
                                editable="{{isEditable}}"
                                class="memo_text"  
                                height="100%"
                                 tap="{{onTapEditField}}" 
                                />
                       
                </StackLayout>

        
                <Button id="pageCommonInput.onCut"      
                    text="{{onCut_text}}" 
                    longPress="{{onLongPressHelp}}"
                    tap="{{onCut}}"
                    class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}"      
                    visibility="{{isText, isText ? 'visible':'collapse' }}"     
                    row="1" col="0" 
                    />
        <Button id="pageCommonInput.onCopy"      
                    text="{{onCopy_text}}"  
                    longPress="{{onLongPressHelp}}"
                    tap="{{onCopy}}"
                    class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}"          
                    row="1" col="1" 
                    visibility="{{isText, isText ? 'visible':'collapse' }}"
                    />
        <Button id="pageCommonInput.onPaste"      
                    text="{{onPaste_text}}" 
                    longPress="{{onLongPressHelp}}"
                    tap="{{onPaste}}"
                    class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}"        
                    row="1" col="2" 
                    visibility="{{isClipboard_text, isClipboard_text ? 'visible':'collapse' }}"
                    />
        <Button id="pageCommon.onSpeak"      
                    text="{{onSpeak_text}}"  
                    longPress="{{onLongPressHelp}}"
                    tap="{{onSpeak}}"
                    class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}"          
                    row="1" col="3" 
                   />

        
        <Button id="pageCommonInput.onFirst"         
                text="{{onFirst_text}}"         
                longPress="{{onLongPressHelp}}"  
                tap="{{onFirst}}"
                class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}"  
                row="2" col="0"
                visibility="{{isText, isText ? 'visible':'collapse' }}"
                /> 
         <Button id="pageCommonInput.onSelection"         
                text="{{onSelection_text}}"         
                longPress="{{onLongPressHelp}}"  
                tap="{{onSelection}}"
                class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}"  
                row="2" col="1"
                visibility="{{isText, isText ? 'visible':'collapse' }}"
                /> 
         <Button id="pageCommonInput.onBack"         
                text="{{onBack_text}}"         
                longPress="{{onLongPressHelp}}"  
                tap="{{onBack}}"
                class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}"  
                row="2" col="2"
                visibility="{{isText, isText ? 'visible':'collapse' }}"
                /> 
         <Button id="pageCommonInput.onRest"         
                text="{{onRest_text}}"         
                longPress="{{onLongPressHelp}}"  
                tap="{{onRest}}"
                class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}"  
                row="2" col="3"
                visibility="{{isText, isText ? 'visible':'collapse' }}"
                /> 
        
         <Button id="pageCommonInput.onLast"         
                text="{{onLast_text}}"         
                longPress="{{onLongPressHelp}}"  
                tap="{{onLast}}"
                class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}"  
                row="3" col="0"
                visibility="{{isText, isText ? 'visible':'collapse' }}"
                /> 
         <Button id="pageCommonInput.onChar"         
                text="{{onChar_text}}"         
                longPress="{{onLongPressHelp}}"  
                tap="{{onChar}}"
                class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}" 
                visibility="{{isText, isText ? 'visible':'collapse' }}" 
                row="3" col="1"
                />
         <Button id="pageCommonInput.onWord"         
                text="{{onWord_text}}"         
                longPress="{{onLongPressHelp}}"  
                tap="{{onWord}}"
                class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}" 
                visibility="{{isText, isText ? 'visible':'collapse' }}" 
                row="3" col="2"
                />
       <Button id="pageCommonInput.onLine"         
                text="{{onLine_text}}"         
                longPress="{{onLongPressHelp}}"  
                tap="{{onLine}}"
                class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}" 
                visibility="{{isText, isText ? 'visible':'collapse' }}" 
                row="3" col="3"
                />      
 
       

                <Button id="pageCommonInput.onHelp"         
                        text="{{onHelp_text}}"         
                        longPress="{{onLongPressHelp}}"  
                        tap="{{onHelp}}"
                        class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}"  
                        row="4" col="0"
                        />
                     <Button row="4" col="1" 
                        id="pageCommonInput.onDictate"
                        text="{{onDictateButton_text}}" 
                        tap= "{{onDictate}}"
                        longPress="{{onLongPressHelp}}" 
                        class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}"  
                        />
                
               
                <Button id="pageCommonInput.onInput"      
                        text="{{onInput_text}}"  
                        longPress="{{onLongPressHelp}}"
                        tap="{{onInput}}"
                        class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}"          
                        row="4" col="2" 
                        />

                
                <Button id="pageCommon.onFinish"          
                        text="{{onFinish_text}}" 
                        tap= "{{onFinish}}"
                        longPress="{{onLongPressHelp}}"     
                        class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}"        
                        row="4" col="3"  
                        /> 

          </GridLayout>

 
        <kt:Toolbar forId="pageCommonInput.editField.text" height="60">
            <GridLayout columns="*, *, *,*" class="toolbar">
               
                <Button col="0" 
                        id="pageCommonInput.onInputMore"
                        text="{{onInputMore_text}}" 
                        tap="{{ onInputMore }}"
                        longPress="{{onLongPressHelp}}" 
                         class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}"  
                        />
                 <Button col="1" 
                        id="pageCommonInput.onDictate"
                        text="{{onDictateButton_text}}" 
                        tap= "{{onDictate}}"
                        longPress="{{onLongPressHelp}}" 
                        class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}"  
                        />
                 <Button col="2"
                        id="pageCommonInput.onCancel"
                        text="{{onCancel_text}}"
                        tap="{{onClear}}"
                        longPress="{{onLongPressHelp}}" 
                        class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}"  
                        visibility="{{isVisible_onCut, isVisible_onCut ? 'visible':'collapse' }}"
                        />
                
                <Button col="3" 
                        id="pageCommon.onFinish"
                        text="{{onFinish_text}}" 
                        tap="{{ onFinish }}"
                        longPress="{{onLongPressHelp}}" 
                        class="{{options.themeDark,options.themeDark ? 'button_dark': 'button'}}"  
                        />
            </GridLayout>
        </kt:Toolbar>

<AbsoluteLayout witdth="100%" height="100%" class="private"
visibility="{{isVisible_privacy, isVisible_privacy ? 'visible':'collapse' }}">
</AbsoluteLayout>
</GridLayout> 
</Page>`

app.ts contains:
`/*
In NativeScript, the app.ts file is the entry point to your application.
You can use this file to perform app-level initialization, but the primary
purpose of the file is to pass control to the app’s first module.
*/
import * as application from "tns-core-modules/application";

//DISABLE or set back key 
import {backEvent} from "~/App-vm/core/backButton"
if (application.android) {
    application.android.on(application.AndroidApplication.activityBackPressedEvent, backEvent);
  }

application.run({ moduleName: "app-root" });
`

N.B. ~/App-vm/core/backButton does exist

Running on android 9
tns doctor reports:
`No issues were detected.
√ Your ANDROID_HOME environment variable is set and points to correct directory.
√ Your adb from the Android SDK is correctly installed.
√ The Android SDK is installed.
√ A compatible Android SDK for compilation is found.
√ Javac is installed and is configured properly.
√ The Java Development Kit (JDK) is installed and is configured properly.
√ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
√ Getting NativeScript components versions information...
√ Component nativescript has 6.1.2 version and is up to date.
√ Component tns-core-modules has 6.1.1 version and is up to date.
√ Component tns-android has 6.1.2 version and is up to date.
‼ Update available for component tns-ios. Your current version is 6.0.2 and the latest available version is 6.1.1.`

**Comment by NickIliev** [comment]
@jokro try to remove the **~** from the path.

replace 
```
import {backEvent} from "~/App-vm/core/backButton"
```

with
```
import {backEvent} from "./App-vm/core/backButton" // or whatever the actual path is within your app
```

**Comment by jokro** [comment]
@Nickliev,

I did log if ~/App-vm/core/backButton was compiled. It it is both using ~/App-vm/core/backButton and ./App-vm/core/backButton. So that is not the problem.

I think pageTitleEdit.xml in cache was corrupted. Making a fully fresh start solved the problem.
Thx.
