### ISSUE TITLE
Android: FontAwesome icons inside TabStrip not crisp on some devices compared to icons used outside of Tabs component

### ISSUE THREAD

**Issue by felix-idf** [NativeScript/NativeScript#7921]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.2
 - Cross-platform modules: 6.1.1
 - Android Runtime: 6.1.2
 - iOS Runtime: -
 - Plugin(s): -

**Describe the bug**
FontAwesome Icons used in TabStrip do look blurred/unsharp on some devices, while the same icons have a normal quality used outside of TabStrip component.

Our test device:
[Acer Iconia Tab 10 A3-A30](https://www.acer.com/ac/en/GB/content/model/NT.LCFEE.002)

![Screenshot_20191008-141517](https://user-images.githubusercontent.com/6443021/66395384-99422480-e9d7-11e9-9ed3-a9ba012a1917.png)

**To Reproduce**
Start the sample app provided below

**Expected behavior**
FontAwesome icons within TabStrip should have the same quality as icons used outside of TabStrip for all devices.

**Sample project**
[TabsIssue.zip](https://github.com/NativeScript/NativeScript/files/3702288/TabsIssue.zip)

**Comment by felix-idf** [comment]
By the way, when setting `isIconSizeFixed` to false and the font-size of Images within TabStrip to 40, then the icons inside TabStrip look as excpected:

![Clipboard01](https://user-images.githubusercontent.com/6443021/66398440-0c4e9980-e9de-11e9-9aee-0c92e09775b0.jpg)

But unfortunately we cannot use this because of issue [https://github.com/NativeScript/NativeScript/issues/7922](https://github.com/NativeScript/NativeScript/issues/7922)

**Comment by NickIliev** [comment]
@felix-idf the thing is that the native Android element that is standing behind `Tabs` has some own rules for setting the TabStripItem **icon**.  The strip bar icons are not actually labels that we can control via `font-size` but images that are generated with width and height. These widths and heights are dependent on the device API level and screen density. So basically, if you are setting `isIconSizeFixed` to `false` then you will need to take care and assign custom styles for each API level - and that (in my opinion) would be very hard and a possible overkill.

We are still thinking of improving the API but so far I would say that sticking to the default **true** value of `isIconSizeFixed` is the way to go when using `TabStrip`.

Another option (which is currently not documented but is available [in the blog post](https://www.nativescript.org/blog/tabs-and-bottomnavigation-nativescripts-two-new-components)) is to entirely **remove** the `TabStrip` and this way create your own pager with your own entirely custom tab strip.

For example, something like:
```XML
<!-- Create your own custom strip here -->

<Tabs selectedIndex="0">
    <!-- <TabStrip iosIconRenderingMode="alwaysOriginal" isIconSizeFixed="false">
        <TabStripItem>
            <Label text="Tab 1"/>
            <Image src="font://&#xf007;" class="fa-solid"/>
        </TabStripItem>
        <TabStripItem>
            <Label text="Tab 2"/>
            <Image src="font://&#xf02d;" class="fa-solid"/>
        </TabStripItem>
        <TabStripItem>
            <Label text="Tab 3"/>
            <Image src="font://&#xf075;" class="fa-solid"/>
        </TabStripItem>
        <TabStripItem>
            <Label text="Tab 4"/>
            <Image src="font://&#xf086;" class="fa-solid"/>
        </TabStripItem>
    </TabStrip> -->

    <TabContentItem>
        <GridLayout rows="*">
            <Label text="&#xf007;" fontSize="18" className="fa-solid center"/>
        </GridLayout>
    </TabContentItem>

    <TabContentItem>
        <GridLayout rows="*">
            <Label text="&#xf02d;" fontSize="18" className="fa-solid center"/>
        </GridLayout>
    </TabContentItem>

    <TabContentItem>
        <GridLayout rows="*">
            <Label text="&#xf075;" fontSize="18" className="fa-solid center"/>
        </GridLayout>
    </TabContentItem>

    <TabContentItem>
        <GridLayout rows="*">
            <Label text="&#xf086;" fontSize="18" className="fa-solid center"/>
        </GridLayout>
    </TabContentItem>
</Tabs>
```

With this approach, you have the freedom to create your own TabStrip while using `Label` for your icon fonts or whatever component you want. See [this Playground app](https://play.nativescript.org/?template=play-ng&id=YfZPr1&_ga=2.129328649.462020354.1570542900-1456678682.1516707790) for a better demonstration of the above.
