### ISSUE TITLE
Android: FontAwesome icons size differences between devices when setting isIconSizeFixd to false

### ISSUE THREAD

**Issue by felix-idf** [NativeScript/NativeScript#7922]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.2
 - Cross-platform modules: 6.1.1
 - Android Runtime: 6.1.2
 - iOS Runtime: -
 - Plugin(s): -

**Describe the bug**
The default icon size in TabStrip compont is a big zu large for our use case so we try to define a custom size like this:

```
TabStripItem Image {
    font-size: 15;
}
```

The result: on some devices the icons still look very big, while they are too small on other devices.

Google Pixel 3:
![Tabs_Google_Pixel_3](https://user-images.githubusercontent.com/6443021/66397263-b7aa1f00-e9db-11e9-9bb8-be0f2148af3b.PNG)

Acer Iconia One 10 B3-A30:
![Screenshot_20191008-144539](https://user-images.githubusercontent.com/6443021/66397244-ad882080-e9db-11e9-995c-27c561b67075.png)

The Tab-icon with font-size 15 looks very different between different devices, while the same icon with sthe same size looks the same on every device when used outside the TabStrip component.

On iOS it works as expected: when defining this:

```
TabStrip {
    font-size: 15;
}


TabStrip Image {
    color: #3C3C3C;
    font-size: 15;
}
```

... then the icons have the same height as the usual text Labels and the icons look consistent through different devices and iOS versions.

**To Reproduce**
Start the sample app provided below.

**Expected behavior**
When setting isIconSizeFixed to false to define a custom font-size for the icons, then the icons in TabStrip should look consistent through different devices and Android versions, like font icons outside the TabStrip do. And ideally, the font-size of TabStrip icons should have the same relation to usual Labels, as it already works on iOS.

**Sample project**
[TabsIssue.zip](https://github.com/NativeScript/NativeScript/files/3702414/TabsIssue.zip)

**Comment by NickIliev** [comment]
@felix-idf [the comment made here](https://github.com/NativeScript/NativeScript/issues/7921#issuecomment-539540199) is valid for both occasions (I  actually meant to post it in this thread but somehow answered in the other)
