### ISSUE TITLE
How to install a specific version of NativeScript? 

### ISSUE THREAD

**Issue by sputn1k** [NativeScript/NativeScript#7926]
I tried - 

```
npm remove -g nativescript
npm install -g nativescript@version --- 5.4.0
```

Doesnt seem to work?

**No valid versions available for 5.4.0**

Also tried - 
`tns update 5.4.0` once latest NativeScript is installed. But says; 

`This project is not compatible with the current NativeScript version and cannot be updated. Use "tns migrate" to make your project compatible.`

I can't compile/run my app anymore after migrating/installing v6.

**Comment by NickIliev** [comment]
@sputn1k the command `npm i -g nativescript` will install the NativeScript CLI. It won't update/migrate your existing project. However, once you have installed a specific version of the CLI, you can use it to create new projects with the related versions.

For example
```
npm uninstall -g nativescript
npm i -g nativescript@5.4.0
tns --version // will output 5.4.0
```

One, you have the wanted version of the CLI you can create a project that uses the core dependencies (e.g., runtime, modules) that were compatible with that CLI version

```
tns create my-app --tsc
```

and the generated pckage.json will look like this
```JSON
{
  "nativescript": {
    "id": "org.nativescript.myapp",
    "tns-android": {
      "version": "5.4.0"
    },
    "tns-ios": {
      "version": "5.4.2"
    }
  },
  "main": "app.js",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "nativescript-theme-core": "~1.0.4",
    "tns-core-modules": "~5.4.0"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "~0.10.0",
    "nativescript-dev-webpack": "~0.24.0"
  },
  "gitHead": "8c1a4866a66daab09bf5ef8e5a96472687192373",
  "readme": "NativeScript Application"
}
```

**Comment by sputn1k** [comment]
@NickIliev Thanks I'll try that out cheers
