### ISSUE TITLE
node_module errors after migrating to NS6

### ISSUE THREAD

**Issue by Efrenray** [NativeScript/NativeScript#7932]
I've migrated my app to NS6 though the app still uses some deprecated plugins such that I encountered these errors.

**Dependencies versions: NodeJS: 10.16.0, npm: 6.9.0, NativeScript CLI: 6.1.2.**

> WARNING in ../node_modules/encoding/lib/iconv-loader.js 9:12-34
> Critical dependency: the request of a dependency is an expression
>  @ ../node_modules/encoding/lib/encoding.js
>  @ ../node_modules/node-fetch/lib/body.js
>  @ ../node_modules/node-fetch/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> WARNING in ./login/login-page.css
> Module build failed (from ../node_modules/css-loader/dist/cjs.js):
> CssSyntaxError
> 
> (74:1) Unexpected }
> 
>   72 |
>   73 |  }
> > 74 | }
>      | ^
> 
>  @ \b_[\w-]*\.)scss)$ (. sync (?<!\bApp_Resources\b.*)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$) ./login/login-page.css
>  @ ./app.js
> 
> WARNING in ../node_modules/ws/lib/BufferUtil.js
> Module not found: Error: Can't resolve '../build/Release/bufferutil' in 'F:\NativeScript\simpleapp\node_modules\ws\lib'
>  @ ../node_modules/ws/lib/BufferUtil.js
>  @ ../node_modules/ws/lib/Sender.js
>  @ ../node_modules/ws/index.js
>  @ ../node_modules/node-xmpp-client/lib/websockets.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> WARNING in ../node_modules/ws/lib/Validation.js
> Module not found: Error: Can't resolve '../build/Release/validation' in 'F:\NativeScript\simpleapp\node_modules\ws\lib'
>  @ ../node_modules/ws/lib/Validation.js
>  @ ../node_modules/ws/lib/Receiver.js
>  @ ../node_modules/ws/index.js
>  @ ../node_modules/node-xmpp-client/lib/websockets.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> WARNING in ../node_modules/ws/lib/BufferUtil.js
> Module not found: Error: Can't resolve '../build/default/bufferutil' in 'F:\NativeScript\simpleapp\node_modules\ws\lib'
>  @ ../node_modules/ws/lib/BufferUtil.js
>  @ ../node_modules/ws/lib/Sender.js
>  @ ../node_modules/ws/index.js
>  @ ../node_modules/node-xmpp-client/lib/websockets.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> WARNING in ../node_modules/ws/lib/Validation.js
> Module not found: Error: Can't resolve '../build/default/validation' in 'F:\NativeScript\simpleapp\node_modules\ws\lib'
>  @ ../node_modules/ws/lib/Validation.js
>  @ ../node_modules/ws/lib/Receiver.js
>  @ ../node_modules/ws/index.js
>  @ ../node_modules/node-xmpp-client/lib/websockets.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> WARNING in ../node_modules/nativescript-sqlite/sqlite.js
> Module not found: Error: Can't resolve 'nativescript-sqlite-commercial' in 'F:\NativeScript\simpleapp\node_modules\nativescript-sqlite'
>  @ ../node_modules/nativescript-sqlite/sqlite.js
>  @ ./home/home-page.js
>  @ . sync (?<!\bApp_Resources\b.*)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$
>  @ ./app.js
> 
> WARNING in ../node_modules/nativescript-sqlite/sqlite.js
> Module not found: Error: Can't resolve 'nativescript-sqlite-encrypted' in 'F:\NativeScript\simpleapp\node_modules\nativescript-sqlite'
>  @ ../node_modules/nativescript-sqlite/sqlite.js
>  @ ./home/home-page.js
>  @ . sync (?<!\bApp_Resources\b.*)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$
>  @ ./app.js
> 
> ERROR in ../node_modules/nativescript-xmpp-client/lib/deps/buffer.js
> Module not found: Error: Can't resolve './buffer_ieee754' in 'F:\NativeScript\simpleapp\node_modules\nativescript-xmpp-client\lib\deps'
>  @ ../node_modules/nativescript-xmpp-client/lib/deps/buffer.js 808:11-38 829:11-38 1113:4-31 1142:4-31
>  @ ../node_modules/nativescript-xmpp-client/lib/Client.js
>  @ ../node_modules/nativescript-xmpp-client/xmpp-client.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/node-xmpp-client/lib/Client.js
> Module not found: Error: Can't resolve 'child_process' in 'F:\NativeScript\simpleapp\node_modules\node-xmpp-client\lib'
>  @ ../node_modules/node-xmpp-client/lib/Client.js 15:11-35
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/node-xmpp-core/lib/SRV.js
> Module not found: Error: Can't resolve 'dns' in 'F:\NativeScript\simpleapp\node_modules\node-xmpp-core\lib'
>  @ ../node_modules/node-xmpp-core/lib/SRV.js 3:10-24
>  @ ../node_modules/node-xmpp-core/index.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/debug/src/node.js
> Module not found: Error: Can't resolve 'net' in 'F:\NativeScript\simpleapp\node_modules\debug\src'
>  @ ../node_modules/debug/src/node.js 193:16-30
>  @ ../node_modules/debug/src/index.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/forever-agent/index.js
> Module not found: Error: Can't resolve 'net' in 'F:\NativeScript\simpleapp\node_modules\forever-agent'
>  @ ../node_modules/forever-agent/index.js 6:10-24
>  @ ../node_modules/request/request.js
>  @ ../node_modules/request/index.js
>  @ ../node_modules/node-xmpp-client/lib/bosh.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/node-xmpp-core/lib/Connection.js
> Module not found: Error: Can't resolve 'net' in 'F:\NativeScript\simpleapp\node_modules\node-xmpp-core\lib'
>  @ ../node_modules/node-xmpp-core/lib/Connection.js 3:10-24
>  @ ../node_modules/node-xmpp-core/index.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/node-xmpp-tls-connect/starttls.js
> Module not found: Error: Can't resolve 'net' in 'F:\NativeScript\simpleapp\node_modules\node-xmpp-tls-connect'
>  @ ../node_modules/node-xmpp-tls-connect/starttls.js 27:10-24
>  @ ../node_modules/node-xmpp-core/lib/Connection.js
>  @ ../node_modules/node-xmpp-core/index.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/tough-cookie/lib/cookie.js
> Module not found: Error: Can't resolve 'net' in 'F:\NativeScript\simpleapp\node_modules\tough-cookie\lib'
>  @ ../node_modules/tough-cookie/lib/cookie.js 32:10-24
>  @ ../node_modules/request/lib/cookies.js
>  @ ../node_modules/request/index.js
>  @ ../node_modules/node-xmpp-client/lib/bosh.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/tunnel-agent/index.js
> Module not found: Error: Can't resolve 'net' in 'F:\NativeScript\simpleapp\node_modules\tunnel-agent'
>  @ ../node_modules/tunnel-agent/index.js 3:10-24
>  @ ../node_modules/request/lib/tunnel.js
>  @ ../node_modules/request/request.js
>  @ ../node_modules/request/index.js
>  @ ../node_modules/node-xmpp-client/lib/bosh.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/forever-agent/index.js
> Module not found: Error: Can't resolve 'tls' in 'F:\NativeScript\simpleapp\node_modules\forever-agent'
>  @ ../node_modules/forever-agent/index.js 7:10-24
>  @ ../node_modules/request/request.js
>  @ ../node_modules/request/index.js
>  @ ../node_modules/node-xmpp-client/lib/bosh.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/node-xmpp-client/lib/session.js
> Module not found: Error: Can't resolve 'tls' in 'F:\NativeScript\simpleapp\node_modules\node-xmpp-client\lib'
>  @ ../node_modules/node-xmpp-client/lib/session.js 3:10-24
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/node-xmpp-tls-connect/starttls.js
> Module not found: Error: Can't resolve 'tls' in 'F:\NativeScript\simpleapp\node_modules\node-xmpp-tls-connect'
>  @ ../node_modules/node-xmpp-tls-connect/starttls.js 28:10-24
>  @ ../node_modules/node-xmpp-core/lib/Connection.js
>  @ ../node_modules/node-xmpp-core/index.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/tunnel-agent/index.js
> Module not found: Error: Can't resolve 'tls' in 'F:\NativeScript\simpleapp\node_modules\tunnel-agent'
>  @ ../node_modules/tunnel-agent/index.js 4:10-24
>  @ ../node_modules/request/lib/tunnel.js
>  @ ../node_modules/request/request.js
>  @ ../node_modules/request/index.js
>  @ ../node_modules/node-xmpp-client/lib/bosh.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> 
> ERROR in ../node_modules/ws/lib/WebSocketServer.js
> Module not found: Error: Can't resolve 'tls' in 'F:\NativeScript\simpleapp\node_modules\ws\lib'
>  @ ../node_modules/ws/lib/WebSocketServer.js 13:10-24
>  @ ../node_modules/ws/index.js
>  @ ../node_modules/node-xmpp-client/lib/websockets.js
>  @ ../node_modules/node-xmpp-client/lib/session.js
>  @ ../node_modules/node-xmpp-client/lib/Client.js
>  @ ../node_modules/node-xmpp-client/index.js
>  @ ../node_modules/connectycube/src/cubeDependencies.js
>  @ ../node_modules/connectycube/src/videocalling/cubeRTCPeerConnection.js
>  @ ../node_modules/connectycube/src/videocalling/cubeWebRTCClient.js
>  @ ../node_modules/connectycube/src/cubeMain.js
>  @ ./app.js
> Webpack compilation complete.
> Executing webpack failed with exit code 2.

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #5065](https://github.com/NativeScript/nativescript-cli/issues/5065) via [**ZenHub**](https://www.zenhub.com/)
