### ISSUE TITLE
Existing style overwritten by dark mode (iOS)

### ISSUE THREAD

**Issue by Mixelated** [NativeScript/NativeScript#7939]
Any non defined styles are overwritten when dark style is enabled in iOS. 
Example: if a text input does not have the color set it will be overwritten to white color text when dark mode is enabled.

Device: iPhone XS Max iOS 11
Nativescript 6.1.2

**Comment by andreacappadona17** [comment]
You can add this to your Info.plist file to force the app to the Light Mode.

> <key>UIUserInterfaceStyle</key>
> <string>Light</string>

**Comment by manoldonev** [comment]
@Mixelated iOS dark mode support will be added with NativeScript 6.2 -- you can follow this tracking issue [here](https://github.com/NativeScript/NativeScript/issues/7800).

**Comment by Mixelated** [comment]
great! Thanks for the quick response!

**Comment by mr-simonski** [comment]
Is it possible to force light mode in Playground?
