### ISSUE TITLE
Force emulator to run with specific iOS version?

### ISSUE THREAD

**Issue by emiloberg** [NativeScript/NativeScript#794]
Hi,

All of a sudden (might be connected with me updating to 1.3.0), when I run `tns emulate ios --device iPhone-5`, my iOS simulator gives me: 

> The iOS 7.1 simulator runtime is not available.
> Unable to open liblaunch_sim.dylib. Try reinstalling Xcode or the simulator runtime. 

![skarmavbild 2015-09-21 kl 14 52 01](https://cloud.githubusercontent.com/assets/4673048/9992163/68b88358-6070-11e5-8a21-b5151dce3c27.png)

This is most probably because Xcode 7 (7A220 in my case)/Yosemite dropped support for simulating iOS 7.x. However, how can I make `tns emulate ios --device iPhone-5` use iOS 8.x instead of 7.x?

Running `tns emulate ios --device iPhone-6` (n.b iPhone __6__) works as it opens the emulator with iOS 8.1.

**Comment by emiloberg** [comment]
Looking at Xcode, there's no such thing as a 7.1 simulator (as Xcode 7 doesn't support it):

<img width="218" alt="skarmavbild 2015-09-22 kl 09 08 41" src="https://cloud.githubusercontent.com/assets/4673048/10012590/9f2a1534-6109-11e5-8361-60e48b3fd497.png">

**Comment by manijak** [comment]
I haven't installed Xcode7 yet. I've heard that {N} modules are not supported in iOS 9?

Does this mean that iOS7 apps are no more? And users of iPhone3 & 4 are out? We can focus on developing apps that are 8.x > ?

**Comment by emiloberg** [comment]
This doesn't mean that you can't build iOS7 apps (as far as I understand it), it just means that you can't use the emulator iOS 7 emulator.

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#952
