### ISSUE TITLE
Way to get original content height when container height is 0

### ISSUE THREAD

**Issue by mannok** [NativeScript/NativeScript#7949]
**Is your feature request related to a problem? Please describe.**
I am going to make a collapsable component. In order to make it collapse and expand in between. I should know its content size.

**Describe the solution you'd like**
A way to get container's content height even if the container is with height 0 (collapsed)

**Describe alternatives you've considered**

**Additional context**
I have try different method from nativeView but no luck. Provided with a fiddle URL. I tried to animate a `StackLayout` from `height: 0` to `height: auto` by `view.animation({ height: 'auto': duration: 2000 })`. However, seems it is not working as expected... The animation extended way too far.
[https://play.nativescript.org/?template=play-vue&id=2U8Hgj&v=3](https://play.nativescript.org/?template=play-vue&id=2U8Hgj&v=3)

**Comment by tsonevn** [comment]
Hi @mannok,
In your case, while animating the height, you should specify the exact value for this property instead of using `auto`. For example:
```
view.animation({ height: 200, duration: 2000 })
```
Regarding the original content height, I've checked the attached project and `getActualSize()` method seems to return the correct height for the components.
Let me know if I am missing something.

**Comment by mannok** [comment]
@tsonevn thank you for providing help.
What I mean is that you may press `get home-panel content height` immediately once you launched the attached project. and the console will show you all `0` since the `Label` container (StackLayout) has `height: 0`. But what I want to know is the size of the `Label` regardless `StackLayout`'s `height` is '0' or `'auto'`.

**Comment by NickIliev** [comment]
@mannok you can change the approach and move the "collapsing" of your StackLayout (_**height = 0**_) to the **loaded** even. The idea is to get the actual height (via **_getActualSize().height_**) before the height is collapsed to 0. This way you won't have to rely on the "auto" property to expand the view (it seems that the auto property is taking the measured values without taking into account the density scale factor).

[See this modified demo ](https://play.nativescript.org/?template=play-vue&id=2U8Hgj&v=5) where I am using the StackLayout loaded event to store the initial heigh and then reusing this value to collapse/expand the view.

```Vue
<template>
    <Page class="page">
        <ActionBar title="Home" class="action-bar" />
        <StackLayout>
            <StackLayout>
                <Button @tap="getParentHeight">get home-panel height</Button>
                <Button @tap="getContentElementHeight">get home-panel content
                    height</Button>
                <Button @tap="animateSL">animate SL</Button>
            </StackLayout>

            <StackLayout ref="sl" backgroundColor="red" color="white"
                @loaded="onContainerLoaded">
                <Label ref="lbl" textWrap="true" text="aaa" />
                <Label textWrap="true" text="aaa" />
                <Label textWrap="true" text="aaa" />
                <Label textWrap="true" text="aaa" />
                <Label textWrap="true" text="aaa" />
                <Label textWrap="true" text="aaa" />
                <Label textWrap="true" text="aaa" />
            </StackLayout>

            <Label textWrap="true" text="bbb" />
        </StackLayout>
    </Page>
</template>

<script>
    export default {
        data() {
            return {
                ht: 0 // initialization of our own height prop
            };
        },
        methods: {
            onContainerLoaded() {
                setTimeout(() => {
                    this.ht = this.$refs["sl"].nativeView
                        .getActualSize()
                        .height; // take the initial height of our Stack before it is collapsed. Use getActualSise().height

                    this.$refs["sl"].nativeView.height =
                    0; // "collapse" the stack by setting 0 height
                }, 1);
            },
            getParentHeight() {
                console.log(this.$refs["sl"].nativeView.getActualSize());
            },
            getContentElementHeight() {
                console.log(this.$refs["lbl"].nativeView.getActualSize());
            },
            animateSL() {
                if ((this.$refs["lbl"].nativeView.getActualSize().height === 0)) {
                    this.$refs["sl"].nativeView.animate({
                        height: this.ht, // use the stored height value (something like 151.66666)
                        duration: 2000
                    });
                } else {
                    this.$refs["sl"].nativeView.animate({
                        height: 0,
                        duration: 2000
                    });
                }
            }
        }
    };
</script>

<style scoped>
    .home-panel {

    }
</style>
```

**Comment by mannok** [comment]
> @mannok you can change the approach and move the "collapsing" of your StackLayout (_**height = 0**_) to the **loaded** event. The idea is to get the actual height (via **_getActualSize().height_**) before the height is collapsed to 0. This way you won't have to rely on the "auto" property to expand the view (it seems that the auto property is taking the measured values without taking into account the density scale factor).
> 
> [See this modified demo ](https://play.nativescript.org/?template=play-vue&id=2U8Hgj&v=5) where I am using the StackLayout loaded event to store the initial heigh and then reusing this value to collapse/expand the view.
> 
> ```
> <template>
>     <Page class="page">
>         <ActionBar title="Home" class="action-bar" />
>         <StackLayout>
>             <StackLayout>
>                 <Button @tap="getParentHeight">get home-panel height</Button>
>                 <Button @tap="getContentElementHeight">get home-panel content
>                     height</Button>
>                 <Button @tap="animateSL">animate SL</Button>
>             </StackLayout>
> 
>             <StackLayout ref="sl" backgroundColor="red" color="white"
>                 @loaded="onContainerLoaded">
>                 <Label ref="lbl" textWrap="true" text="aaa" />
>                 <Label textWrap="true" text="aaa" />
>                 <Label textWrap="true" text="aaa" />
>                 <Label textWrap="true" text="aaa" />
>                 <Label textWrap="true" text="aaa" />
>                 <Label textWrap="true" text="aaa" />
>                 <Label textWrap="true" text="aaa" />
>             </StackLayout>
> 
>             <Label textWrap="true" text="bbb" />
>         </StackLayout>
>     </Page>
> </template>
> 
> <script>
>     export default {
>         data() {
>             return {
>                 ht: 0 // initialization of our own height prop
>             };
>         },
>         methods: {
>             onContainerLoaded() {
>                 setTimeout(() => {
>                     this.ht = this.$refs["sl"].nativeView
>                         .getActualSize()
>                         .height; // take the initial height of our Stack before it is collapsed. Use getActualSise().height
> 
>                     this.$refs["sl"].nativeView.height =
>                     0; // "collapse" the stack by setting 0 height
>                 }, 1);
>             },
>             getParentHeight() {
>                 console.log(this.$refs["sl"].nativeView.getActualSize());
>             },
>             getContentElementHeight() {
>                 console.log(this.$refs["lbl"].nativeView.getActualSize());
>             },
>             animateSL() {
>                 if ((this.$refs["lbl"].nativeView.getActualSize().height === 0)) {
>                     this.$refs["sl"].nativeView.animate({
>                         height: this.ht, // use the stored height value (something like 151.66666)
>                         duration: 2000
>                     });
>                 } else {
>                     this.$refs["sl"].nativeView.animate({
>                         height: 0,
>                         duration: 2000
>                     });
>                 }
>             }
>         }
>     };
> </script>
> 
> <style scoped>
>     .home-panel {
> 
>     }
> </style>
> ```

@NickIliev Thanks for providing the idea. Nice trick! However, since the content of my project may be changed constantly (vary every 10 seconds by HTTPrequest). Therefore, this approach is not appropriate in my case. Any other workaround for me? :(

This make me mad for 4 days...    sad............................

**Comment by mannok** [comment]
Can't I do such easy animation dynamically?
