### ISSUE TITLE
How to require  name and version of nativescript in runtime.

### ISSUE THREAD

**Issue by Joy1024** [NativeScript/NativeScript#7950]
Hi. NS.
      I want get name and version  of nativescript in my App.
It's similar  using `const {name, version } = require("react-native/package.json");` in RN.

**Comment by OriIdan** [comment]
Use appversion

`import * as appversion from "nativescript-appversion";`
```
appversion.getVersionName().then((v: string) => {
	console.log("Your app's version is: " + v);
	this.verstr = localize("Version") + ': ' + v;
})
```

**Comment by Joy1024** [comment]
> Use appversion
> 
> `import * as appversion from "nativescript-appversion";`
> 
> ```
> appversion.getVersionName().then((v: string) => {
> 	console.log("Your app's version is: " + v);
> 	this.verstr = localize("Version") + ': ' + v;
> })
> ```

I try the code above.
I want get name and version of NativeScript not myApp.
It expect is `name:NativeScript version:6.1.2`.
