### ISSUE TITLE
Weird behavior of nested ListView (cannot tap 1st level item and 2nd level listview got wrong height)

### ISSUE THREAD

**Issue by mannok** [NativeScript/NativeScript#7951]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.2
 - Cross-platform modules:
 - Android Runtime: Android 9.0
 - iOS Runtime: -
 - Plugin(s): -

**Describe the bug**
1. All 1st level item (cyan) cannot be tapped.
2. All 2nd level item (pink) having a wrong height. (only 1 row is shown)

**To Reproduce**
Run the playground fiddle.

**Expected behavior**
1. All 1st level item (cyan) should be tappable.
2. All 2nd level item (pink) should contain 3 rows.

**Sample project**
[https://play.nativescript.org/?template=play-vue&id=A9hwkj&v=3](https://play.nativescript.org/?template=play-vue&id=A9hwkj&v=3)

**Additional context**

**Comment by NickIliev** [comment]
@mannok nesting ListView inside a ListView is not supported and can cause a performance issue (apart from the issue you are dealing with). The `ListView` is using virtualization and recycling to optimize the creation and usage of its cells. So when a cell is containing another `ListView` that would break the proper recycling and virtualization.

That said, we are not testing scenarios where a ListView is nested within another ListView. Based on the Playground it appears that you are trying to create something like a grouping of your inner lists which can be achieved either by using separate lists (but not nested) or by using [RadListView](https://docs.nativescript.org/ui/components/RadListView/data-operations)
