### ISSUE TITLE
Is there a simple way to check iOS permissions (in particular Push Notifications)?

### ISSUE THREAD

**Issue by Mixelated** [NativeScript/NativeScript#7952]
Is there a simple way to check iOS permissions (in particular Push Notifications)?

**Comment by OriIdan** [comment]
What do you mean check permissions? For push notification you have to enable it in profiles in developer.apple.com and enable it in xcode project settings.
That's what I remember about Push notifications.
What other permissions do you mean?

**Comment by Mixelated** [comment]
Yes I enabled the permissions (for push notifications) I just wondered if there is a way to check if the user has allowed push notifications. (Usecase here is that I can send them to settings to enable notifications  if they haven’t allowed them)

**Comment by tsonevn** [comment]
Hi @Mixelated,
In your case, you can use the `getNotificationSettingsWithCompletionHandler` native method, which will return the status of this permission. For example:
```
 let center = UNUserNotificationCenter.currentNotificationCenter()
    center.getNotificationSettingsWithCompletionHandler((settings: UNNotificationSettings)=>{
        switch (settings.authorizationStatus) {
            case  UNAuthorizationStatus.Authorized:
                console.log("Status Authorized");
                break;
            case UNAuthorizationStatus.Denied:
                console.log("Status Denied");
                break;
            case UNAuthorizationStatus.NotDetermined:
                console.log("Undetermined");
                break;
            default:
                break;
            }
    })
``` 

If you are using NativeScript Angular or TypeScript project, you will also need to install  [tns-platform-declarations](https://www.npmjs.com/package/tns-platform-declarations).
