### ISSUE TITLE
Verticaly centralize if fit, scroll otherwise.

### ISSUE THREAD

**Issue by aranmohyeddin** [NativeScript/NativeScript#7956]
**Describe the solution you'd like**
The contents of a certain page fit withing a box. What I would like is to have the box centralized vertically if it fully fits in the display, and otherwise I want it to take all the available space and be scrollable.

**Describe alternatives you've considered**
Here is what I've tried so far(I use nativescript-vue):
```
<template>
  <GridLayout rows="*,auto,*" height="100%">
    <StackLayout row="0" />
    <ScrollView row="1" orientation="vertical">
      <StackLayout>
        <slot />
      </StackLayout>
    </ScrollView>
    <StackLayout row="2" />
  </GridLayout>
</template>
```
It works fine on Android if the content fits in the window, but otherwise the scrolling doesn't work. I have some issues on IOS but I'm not yet sure if it's because of this, I'm still looking into it.

**Comment by aranmohyeddin** [comment]
I've also asked my question on [stackoverflow](https://stackoverflow.com/q/58334922/5120089) two days ago but didn't get any answer.

**Comment by tsonevn** [comment]
Hi @aranmohyeddin,
You can try nesting the ScrollView in GridLayout and replacing the `auto` option with a star(`*`). For example:
```
<GridLayout rows="* * *" columns="">
		<StackLayout row="0" backgroundColor="red">
		</StackLayout>
		<GridLayout row="1">
			<ScrollView>
				<GridLayout class="m-15" rows="auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto">
					........
				</GridLayout>
			</ScrollView>
		</GridLayout>
		<StackLayout row="2" backgroundColor="green">
		</StackLayout>
	</GridLayout>
```

**Comment by aranmohyeddin** [comment]
That is not what I want. your solution splits the screen into three equal rows! I don't want that. basically what I want is to have auto be there but assign a maximum height to it.

**Comment by aranmohyeddin** [comment]
I created a new [stackoverflow](https://stackoverflow.com/questions/58371204/how-to-set-max-height-in-nativescript) question.

**Comment by aranmohyeddin** [comment]
I was wondering if [such a hack](https://github.com/NativeScript/NativeScript/issues/4315) is possible for this.

**Comment by aranmohyeddin** [comment]
[This feature](https://github.com/NativeScript/NativeScript/issues/6441) would possibly solve my issue.
