### ISSUE TITLE
Beep

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#7959]
Is there a way to generate a beep without using an audio file ?
If not, could it be added ?

 [For android I found the following code.](https://stackoverflow.com/questions/29509010/how-to-play-a-short-beep-to-android-phones-loudspeaker-programmatically) Did somone convert it to use it with nativescript ?

`import android.media.AudioManager
import android.media.ToneGenerator
import android.os.Handler
import android.os.Looper

class BeepHelper
{
val toneG = ToneGenerator(AudioManager.STREAM_ALARM, 100)

fun beep(duration: Int)
{
    toneG.startTone(ToneGenerator.TONE_DTMF_S, duration)
    val handler = Handler(Looper.getMainLooper())
    handler.postDelayed({
        toneG.release()
    }, (duration + 50).toLong())
}
}`

**Comment by jokro** [comment]
I need it for an app for blind peeple…
thx

**Comment by luizbills** [comment]
@jokro the code for your solution: 

```js
const AudioManager = android.media.AudioManager
const ToneGenerator = android.media.ToneGenerator
const Handler = android.os.Handler
const Looper = android.os.Looper

function beep (duration) {
    const toneG = new ToneGenerator(AudioManager.STREAM_ALARM, 100)
    toneG.startTone(ToneGenerator.TONE_DTMF_S, duration)
    setTimeout(() => toneG.release(), duration + 50)
}
```

But the github is not a support channel, come to our slack https://www.nativescript.org/slack-invitation-form

**Comment by tsonevn** [comment]
HI @jokro,
I was unable to find a plugin that provides similar functionality. On that matter, you can use the native solution that you have found. Also, for further questions, please use Slack, as @luizbills suggested, or [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript).
