### ISSUE TITLE
Being able to specify the WebView client (specifically WebChromeClient)

### ISSUE THREAD

**Issue by ligaz** [NativeScript/NativeScript#796]
_From @svalchinov on September 19, 2015 13:34_

I'm currently trying to get a WebView to work on a 4.2 HTC One.

The WebView is loading a MJPG stream that works perfectly in Chrome and Firefox but not the stock browser.

It'd great if we can force/specify the engine the WebView needs to use.

[WebChromeClient](http://developer.android.com/reference/android/webkit/WebChromeClient.html)

_Copied from original issue: NativeScript/nativescript-cli#948_

**Comment by enchev** [comment]
He @svalchinov,

I believe that you can do that even now:

var webView = new WebView();
webView.on("loaded", function(args){
   webView.android.setWebChromeClient(new android.webkit.WebChromeClient());
});

**Comment by svalchinov** [comment]
@enchev 

Good to know! I will give that a go in the next few days. Thanks a lot.
