### ISSUE TITLE
"tns run android" is enormously slow with active internet connection

### ISSUE THREAD

**Issue by Jay-Vo** [NativeScript/NativeScript#7962]
**Environment**
 - CLI: 6.1.2
 - Cross-platform modules 6.1.1:
 - Android Runtime 6.1.2:
 - Plugin(s):

>  "dependencies": {
>     "@angular/animations": "~8.0.1",
>     "@angular/common": "~8.0.1",
>     "@angular/compiler": "~8.0.1",
>     "@angular/core": "~8.0.1",
>     "@angular/forms": "~8.0.1",
>     "@angular/http": "~8.0.0-beta.10",
>     "@angular/platform-browser": "~8.0.1",
>     "@angular/platform-browser-dynamic": "~8.0.1",
>     "@angular/router": "~8.0.1",
>     "core-js": "^2.5.4",
>     "nativescript-angular": "~8.0.1",
>     "nativescript-theme-core": "~1.0.4",
>     "reflect-metadata": "~0.1.12",
>     "rxjs": "~6.5.0",
>     "tns-core-modules": "~6.0.0",
>     "zone.js": "~0.9.1"
>   },
>   "devDependencies": {
>     "@angular/cli": "~8.0.3",
>     "@angular/compiler-cli": "~8.0.1",
>     "@angular-devkit/build-angular": "~0.800.0",
>     "@nativescript/schematics": "~0.7.0",
>     "@nativescript/tslint-rules": "~0.0.2",
>     "@types/jasmine": "~3.3.8",
>     "@types/jasminewd2": "~2.0.3",
>     "@types/node": "~8.9.4",
>     "codelyzer": "^5.0.0",
>     "jasmine-core": "~3.4.0",
>     "jasmine-spec-reporter": "~4.2.1",
>     "karma": "~4.1.0",
>     "karma-chrome-launcher": "~2.2.0",
>     "karma-coverage-istanbul-reporter": "~2.0.1",
>     "karma-jasmine": "~2.0.1",
>     "karma-jasmine-html-reporter": "^1.4.0",
>     "nativescript-dev-webpack": "~1.0.0",
>     "protractor": "~5.4.0",
>     "ts-node": "~7.0.0",
>     "tslint": "~5.15.0",
>     "typescript": "~3.4.3"
>   }

**Describe the bug**
Every time I work with Nativescript, it takes about 15 minuet to start my project via „tns run android“.
It only gets faster when I deactivate my internet connection. (about 10 sec)
Afterwards, changes in the code are quickly captured and the app is restarted at the usual speed.

**To Reproduce**
I really don't know how to reproduce it.

**Expected behavior**
It shoud start the app much faster. Like it does without internet connection.

**Sample project**
This problem is not linked to any specific project.
(For the log trace I've just created a new project)

**Additional context**
It seems as if nativescript is looking for the available versions for each package.
At the same time, it tries to download something.

The Problem first occued after I migrated my projects to NS6.
I work with Windows. My colleague who works with Mac does not have the problem.
Since then I've tried different solutions, some seemed to work at first, but the problem came back every time I rebooted my computer.

Things that seemed to have an effect.
- Changing the proxy setting.
- Using another version of tns-core-modules / tns-android.

Things that does’nt change anything.
- The „delete node-modules/hooks etc. and do npm install again“ loop.
- Reinstallation
- Changing the versions of npm/node

[logtrace_with_internet.txt](https://github.com/NativeScript/NativeScript/files/3729659/logtrace_with_internet.txt)
[logtrace_without_internet.txt](https://github.com/NativeScript/NativeScript/files/3729660/logtrace_without_internet.txt)

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #5087](https://github.com/NativeScript/nativescript-cli/issues/5087) via [**ZenHub**](https://www.zenhub.com/)
