### ISSUE TITLE
Error when trying to run on ios

### ISSUE THREAD

**Issue by tobydeh** [NativeScript/NativeScript#7963]
**Environment**

iOS 13.1.2
XCode 11.1
OS X 10.14.6
tns-core-modules 6.1.2
tns-platform-declarations 6.1.2

**Describe the bug**

We're getting the following error when trying to run / debug on ios.
The application installs but doesn't launch automatically.

Error while executing ios device operation: Could not start service com.apple.mobile.house_arrest with code: -402653057
Unable to apply changes on device: 8a3447df5498f9ccbf6bc4059e56dcd83eaefd43. Error is: Could not start service com.apple.mobile.house_arrest.
Will emit event runOnDeviceError with data { projectDir: '/Volumes/HD2/Development/Repos/wollit/mobile',
  deviceIdentifier: '8a3447df5498f9ccbf6bc4059e56dcd83eaefd43',
  applicationIdentifier: 'com.wollit.mobile',
  error:
   { code: -402653057,
     deviceId: '8a3447df5498f9ccbf6bc4059e56dcd83eaefd43',
     message: 'Could not start service com.apple.mobile.house_arrest' } }
Stopping webpack watch for platform ios.
Project dir from hooksArgs is: /Volumes/HD2/Development/Repos/wollit/mobile.
Hooks directories: [ '/Volumes/HD2/Development/Repos/wollit/mobile/hooks' ]
AfterHookName for command watch is after-watch
Will emit event runOnDeviceStopped with data { projectDir: '/Volumes/HD2/Development/Repos/wollit/mobile',
  deviceIdentifier: '8a3447df5498f9ccbf6bc4059e56dcd83eaefd43' }
Webpack process exited with code null when we expected it to be long living with watch.

**Comment by tsonevn** [comment]
Hi @tobydeh,
This problem can happen if you are using an old {N} CLI version. Regarding that, I would suggest upgrading to the latest  CLI - version `6.1.2`. If you are already using it, restart the device and try to rebuild the app. If the issue still persists, please send us the full log.

**Comment by tobydeh** [comment]
Doh! Fixed, thank you.
