### ISSUE TITLE
iOS 13 listviews don't work in the "Examples NativeScript" app

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/NativeScript#7967]
**Environment**
I just tested "Exampes NativeScript" app which is available in the app store.

**Describe the bug**
I just installed the app in an iphoneX (iOS 13) and found out some pages don't work. Actually I saw empty pages (with no errors or anything). Pages: Item layouts, Item reorder and Reorder with handle. It seems lisview doesn't work in iOS 13.

**To Reproduce**
Get the app from App Store and test it.

**Expected behavior**
To work fine all the pages.

**Comment by tsonevn** [comment]
Hi @vahidvdn,
I tested our as well [SDK examples ](https://github.com/NativeScript/nativescript-sdk-examples-js) and the ListView seems to work as expected on iOS 13. Can you provide more info about the problem and how to reproduce it?

**Comment by vahidvdn** [comment]
Hi @tsonevn 

Just download the app from "App Store" and test it in iOS 13.1.2
Here is some screenshots from these pages.

![01](https://user-images.githubusercontent.com/11078601/66988619-b8277180-f0cf-11e9-984c-86e1876b48f3.jpg)    ![02](https://user-images.githubusercontent.com/11078601/66988707-d7be9a00-f0cf-11e9-95a6-3a2097bb5dae.jpg)

**Comment by tsonevn** [comment]
Hi @vahidvdn,
I was able to recreate the issue with the [app](https://github.com/NativeScript/nativescript-marketplace-demo). This issue with iOS 13 and the RadListView is [already fixing](https://github.com/NativeScript/nativescript-ui-feedback/issues/1160) and this problem should not be reproducible with the latest `nativescript-ui-listview`. On that matter, the app still uses an old version of the plugin. We will update it and will publish a new version.

**Comment by tsonevn** [comment]
Fixed with https://github.com/NativeScript/nativescript-marketplace-demo/pull/325#event-2729167044
