### ISSUE TITLE
Is the nativescript/facebook project dead?

### ISSUE THREAD

**Issue by aranmohyeddin** [NativeScript/NativeScript#7969]
It's been almost one month since I've posted an issue being unable to even run the demo application from the repo and I have gotten no response. [reference](https://github.com/NativeScript/nativescript-facebook/issues/213#issue-496886323)

**Comment by NickIliev** [comment]
@aranmohyeddin thank you for bringing that into our attention. The project is not dead - I will check the issue and report back in the logged issue.
