### ISSUE TITLE
Semantic versioning in {N}?

### ISSUE THREAD

**Issue by emiloberg** [NativeScript/NativeScript#797]
Hi,

What is NativeScript's take on semantic versioning? 

Searching the issues and looking at the code gives that NativeScript tries to do semver. However, the latest 1.3.0 release included #473 which is a breaking change and should, according to so semver standards, have bumped the version number to 2.0. Same thing with 1.2.0 which contained the breaking change #304 and 1.1.0 which contained breaking change #242.

Now, when {N} is becoming more and more modularized (yay!), a more rigid adherence to semver would probably make our developing lives a tiny bit easier.

It would also mean that we could safely change the tns-core-modules dependency from a fixed version:
```
"dependencies": {
   "tns-core-modules": "1.3.0",
}
```
...into a 'no breaking changes' version (n.b. the caret):
```
   "tns-core-modules": "^1.3.0",
```

One downside to this is that one might hold back on releasing new functionality/fixes if it bumps a major number. However, that is - as I see it - a mental block, which could be overcome.

**Comment by NathanaelA** [comment]
I'm almost wondering if you should skip semvar until you get to 2.0.  The framework seems to currently be in a state of heavy flux.  A lot more than what you pointed out above has changed between those versions.  I've had to fix a number of things that worked in v1.2 that broke or changed in v1.3.    And to v1.4 you already have a stack of breaking changes. (like cssClass -> class).   At this point, I'd rather be willing to break things to improve the overall framework and get several rough areas hammered out then start to lock things down.

**Comment by enchev** [comment]
Hi @NathanaelA 
Actually cssClass -> class is not a breaking change - just a new custom attribute support in the XML. :)

Our cssClass property is untouched!

**Comment by NathanaelA** [comment]
@enchev -- Ah, that should teach me to open my mouth before actually looking at the cssClass->Class commit.   :grinning:

**Comment by hamorphis** [comment]
I’m closing this issue because it has been inactive for almost an year.
