### ISSUE TITLE
Aspect padding in percentage width

### ISSUE THREAD

**Issue by wendt88** [NativeScript/NativeScript#7971]
**Environment**
Android and iOS

**Describe the bug**
The percentage width should be calculated by the inner-width (subtract the padding) of its parent and not by the outer-width

**To Reproduce**
Add padding to a container containing child elements with percentage width

**Expected behavior**
Two elements with 50% width should be side by side, also if the parent has a pagging

**Sample project**
https://play.nativescript.org/?template=play-vue&id=0tZJ07

**Additional context**
So it would be possible to use a grid system for example with space between without 2 containers (1 with width, the 2nd with padding)

**Comment by NickIliev** [comment]
The issue seems closely related to [https://github.com/NativeScript/NativeScript/issues/7968](https://github.com/NativeScript/NativeScript/issues/7968) so closing this one as a duplicate. Please track the linked issue for information and updates.

**Comment by NickIliev** [comment]
@wendt88 in fact, [the Playground seems to work as expected](https://play.nativescript.org/?template=play-vue&id=0tZJ07&v=2) - I've increased the padding value and applied some additional colors for better illustration.

**Comment by wendt88** [comment]
On my device it looks like:

![Screenshot_2019-10-18-15-49-41](https://user-images.githubusercontent.com/13959976/67100011-3c0c5700-f1bf-11e9-9d69-1c1a7ca5007c.png)
