### ISSUE TITLE
webview window.location = 'about:blank' on physical device but simulator = '....app/'?

### ISSUE THREAD

**Issue by 7ammer** [NativeScript/NativeScript#7978]
## Environment

 - CLI:  6.1.0
 - tns-core-modules:  6.1.1
 - iOS Runtime: 6.0.1

 - Plugin(s):
  "dependencies": {
    "nativescript-advanced-webview": "^3.0.2",
    "nativescript-animated-circle": "^1.2.0",
    "nativescript-datetimepicker": "^1.2.1",
    "nativescript-downloader": "^2.1.5",
    "nativescript-fonticon": "^2.0.0",
    "nativescript-local-notifications": "^4.0.1",
    "nativescript-localstorage": "^2.0.0",
    "nativescript-permissions": "^1.2.3",
    "nativescript-statusbar": "^5.0.0",
    "nativescript-vue": "^2.4.0",
    "nativescript-webview-interface": "^1.4.3",
    "tns-core-modules": "^6.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.2",
    "nativescript-dev-webpack": "^1.0.0",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "tns-platform-declarations": "^6.0.0",
    "typescript": "^3.2.4",
    "vue": "^2.5.22",
    "vue-loader": "^15.4.0"
  }

## Describe the bug
I can't access any internal files from inside the webview on a physical device (ios 13.0 iphoneXs). However I can on an ios simulator.

Printing out the javascript value `window.location` shows:
**Simulator:** `file:////Users/{username}/Library/Developer/CoreSimulator/Devices/6A4E03A1-89D7-4E41-AAD5-DA1FF1058ED0/data/Containers/Bundle/Application/551770B5-D274-4AB7-BBD2-AE8D62EA97D1/{appname.app}/app/`

**Physical device:** `about:blank`

## To Reproduce
Add the below to webview's src: `<WebView :src="html"></WebView>`

```
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="HandheldFriendly" content="True">
	<link href="./assets/webview/basic.css" rel="stylesheet" media="all" />
    </head>
    <body class="generic-page-theme">
        hello world

        ${`<script>`}
            setTimeout(function() {
                var div = document.createElement("div");
                div.textContent = window.location;
                document.body.appendChild(div);
             }, 0);
        ${'</' + 'script>'}
    </body>
</html>

```

**Comment by NickIliev** [comment]
It sounds like you are hitting [this issue](https://stackoverflow.com/a/46153286/4936697).
Try using the `file-system` module as described in the SO thread.

```TypeScript
import * as fs from "tns-core-modules/file-system";
public webViewSRC: string = encodeURI(`${fs.knownFolders.currentApp().path}/www/index.html`);
```

**Comment by 7ammer** [comment]
Hello @NickIliev ,

Thanks for replying :)

Your suggestion makes sense however after implementing it am still not able to see the results when I run `tns run ios` on a real device.

Here is the updated test code that gets applied to the src attribute of webview:


```

processHTML(html) {
    const fileSystemModule = require("tns-core-modules/file-system");
    const currentAppFolder = fileSystemModule.knownFolders.currentApp();
    const cssPath = encodeURI('file:///'+currentAppFolder.getFile(fileSystemModule.path.join("/", 'assets/webview/basic.css')).path);

    return `
    <html>
        <head>
            <meta charset="UTF-8">
            <meta http-equiv="X-UA-Compatible" content="ie=edge">
            <meta name="HandheldFriendly" content="True">
            <link href="${cssPath}" rel="stylesheet">
        </head>
        <body class="generic-page-theme">
            ${cssPath}

            <h1>Testing</h1>

        </body>
    </html>`;
}

```

Interestingly I created an .ipa build via xcode and installed it on the iPhone and all the styles worked!?

Here are the locations that get output:
**Real device via 'tns run ios':** **FAILS**
`file:////var/mobile/Containers/Data/Application/{randomLetters}/Library/Application%20Support/LiveSync/app/assets/webview/basic.css`

**Real device 'tns build ios --release' + xcode archive + install via https://www.diawi.com/** **WORKS**
`file:////var/containers/Bundle/Application/{randomLetters}/lectio365appts.app/app/assets/webview/basic.css`

**iOS Simulator:** **WORKS**
`file:////Users/jamesisbell/Library/Developer/CoreSimulator/Devices/6A4E03A1-89D7-4E41-AAD5-DA1FF1058ED0/data/Containers/Bundle/Application/38EA4F11-5B4C-47B6-AD5C-3BDD21132945/lectio365appts.app/app/assets/webview/basic.css`

**Comment by 7ammer** [comment]
Can anyone help?

**Comment by 7ammer** [comment]
This is definitely a debug vs release issue.
`tns run ios --release` : works fine.
`tns run ios` : does not work.

**Comment by 7ammer** [comment]
Closing in favour of: https://github.com/NativeScript/NativeScript/issues/8165 as it should the issue more directly with a better example.
