### ISSUE TITLE
Modal broken in 1.3.0

### ISSUE THREAD

**Issue by bathejasumeet** [NativeScript/NativeScript#798]
Modal occupies whole height in 1.3.0 , and 95% of width, irrespective of specified dimensions. It also has a titlebar at top indicating the name of the application. This was not an issue in 1.2.4, and is introduced in 1.3.0

**Comment by NathanaelA** [comment]
I reported this in #748 and a couple more issues in #781.  This is a duplicate.

**Comment by toddanglin** [comment]
Should modal dialog dimensions be configurable at this point?

Been banging my head against the wall trying to change dimensions of a modal page in iOS (not fullscreen). No matter what I do, the dimensions of the modal window itself do not seem to change.

My assumption was that setting width/height of the `Page` that will be loaded in the modal should set the frame/view size for the modal pop-up. Should the dimensions be set somewhere else?
