### ISSUE TITLE
iOS TextField doesn't resize if horizontalAlignment is center

### ISSUE THREAD

**Issue by BumbiSit** [NativeScript/NativeScript#7980]
I have a case where I have to center a textfield inside a parent container, but the size has to be according to how much text is in the field. So in a gridLayout I put TextField with `horizontalAlignment="center"`, on Android it resizes fine, I can do a custom padding and make it resize smoothly while staying centered, on iOS the resize completely breaks. Tested it with other values and at the end it comes to if I set `horizontalAlignment` to center, only then the field gets stuck to a small size, even if I do it outside of containers etc.

**Comment by NickIliev** [comment]
@BumbiSit consider providing [a sample Playground ](https://play.nativescript.org/)or demo project depicting what you are trying to achieve.

**Comment by BumbiSit** [comment]
https://play.nativescript.org/?template=play-vue&id=Ryvpv0

Here you can easily see the different behaviour between two platforms. This is a simple example, but my project design requires a properly designed page with an auto-growing text field in the middle of the screen.

I was trying to manually change the width of the field by calculating the characters, but then it was a bit glitchy as the caret wasn't following the new width properly.

**Comment by NickIliev** [comment]
@BumbiSit you could use **TextView** instead of **TextField** and it will auto-resize on both iOS and Android.
