### ISSUE TITLE
[IOS] unecessary layout steps on subview size change

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/NativeScript#7988]
{N} 6.1.2

Playground: 
https://play.nativescript.org/?template=play-vue&id=yQTS5W&v=3

In {N} if we change the width of a View a ```requestLayout``` is called. In the view-base implementation a ```requestLayout``` is made on the parent. So whenever you change a view, whatever the level, the whole page(if not frame) is always re-layout. Which means re-measure / re-draw.
This is very expensive, especially on complex layouts(even though it is not so complex) like this one.
![image](https://user-images.githubusercontent.com/655344/67204395-af0b0d00-f40d-11e9-8e9e-b12eb0ca9a6d.png)
In my case this makes the animation stutter without real need for it

You wont see that issue using Nativescript animation module because the animation is made natively and not through the property, so a ```requestLayout``` is not made on every step of the animation.
However you will see in the playground that i linked before. Simply enable ```Layout``` trace to see the layout called on the whole page on button size change.

So 2 things:
- why do need to animate the size and not simply a transformation? Because i want the buttons to always remain center during the whole animation
- how can we fix this?

Well the fix is actually straight forward. You only need to call the parent ```requestLayout``` if the parent has it's size depending on the child size. If not there is no need to to "propagate" the event.
I have not yet started to write the test for "fixed" size but it should be straight forward

**Comment by farfromrefug** [comment]
Actually it is not as easy as. i thought it was. If i try to stop propagating the ```requestLayout``` then there is no update of layout at all!
And i think it is because ```setNeedsLayout``` is used which can only be "heard" from a viewController https://github.com/NativeScript/NativeScript/blob/cc97a1680009f1bf6dbf97c421f6e8dc535295b5/nativescript-core/ui/core/view/view.ios.ts#L748
I need to find a way to make any view request a layout and redo the measure/layout

**Comment by farfromrefug** [comment]
So i got something partially working. The idea is this:
- create a custom ```UICustomLayoutView``` to be able to override ```layoutSubViews```
- in ```layoutSubViews``` call a ```forceReLayout``` on the attached {N} ```View```. The ```forceReLayout``` will measure and layout children
- use ```UICustomLayoutView``` as the nativeView of ```CustomLayoutView```
- improve ```requestLayout``` in ```ViewBase```. For now i only check if width or height are auto. If not i dont call ```requestLayout``` on the parent view ( i also check if i am actually ran from another chilld ```requestLayout```. That way i try not to propagate the layout request too high in the visual tree
- in the ```View``` class dont call ```setNeedsLayout``` on the nativeView if you know you are going to call it on its parent. There is no need as the parent will redraw its children

The basic is here and working. But i already found an edge case

Should i create a PR even if this might not be the right implementation?

**Comment by farfromrefug** [comment]
Here are gifs showing the first result of the PR  https://github.com/NativeScript/NativeScript/pull/7996
![Original 2019-10-22 11_51_01](https://user-images.githubusercontent.com/655344/67275150-46319c80-f4c2-11e9-8b28-7e4a30368cda.gif)
![WithPR 2019-10-22 11_51_55](https://user-images.githubusercontent.com/655344/67275203-62353e00-f4c2-11e9-8d4e-ed520cfa9948.gif)

it is is not that easy to see the improvements on the GIFs (taken on an iPhone 5s) but the improvement is huge. The animation is really smooth without any hickup.

**Comment by MartoYankov** [comment]
@farfromrefug You might be onto something here with the layout improvements, because there certainly are layout scenarios that won't be affected by certain layout parameter changes. There might be a good optimization here.

However, I'd like to return to your first post and ask as you have - why are you animating the width instead of using a transform? Is there a good reason to do this? The usual way to do this is to use transform for the animation and once it's over you assign the element the final layout params. In this way the re-layout is done only once.

**Comment by farfromrefug** [comment]
@MartoYankov I knew you were going to ask me this :D 
If you look at the result in the gif you will see that the horizontal layout containing the pause and the stop buttons is always centered.
This is the behavior you cant achieve with transform. Transform is not taken into account while measuring so you cant get something "centered" while scaling.
You mean then scaling the stop button and translating the play/pause button? That could work and i did not thing about this! That could work. I will try this! 
But it works for this animation. Would not work if you were to animate a label width on which you want to truncate the text ( I am thinking of Material Extended FAB). Just to say transforms wont always work.

One little note in case it could be useful in the future
While working on the PR associated to this i discovered  that ```CaTransaction.commit()``` (which is called when updating a transform) actually calls a ```layoutSubviews```.

I should mention BTW that {N} animation system used for width/height actually is not updating the layout of the parent view. You know about this? 

Now as you said the main thing is that it points out an issue with the layout system in {N}. The issue actually happens on both iOS and Android. But i had no stuttering effect on Android.
I hope we can work on that

**Comment by MartoYankov** [comment]
@farfromrefug Yep, I know not everything is possible with transform - that's why we added the width/height animations in the end. The thing is, animating layout params will always be slower than transforms. They should be used as a last resort for cases like the Label with text.

There should be some optimization in place already - for example, yes, `requestLayout` is called, but then if an element is measured the same, it's not actually laid out again. I haven't looked at these things in a while, so I can't really go into specifics now (we're in the middle of a release). These might not be enough.

As I said, it sounds like a good idea in general, but has to be thought through and the possible scenarios identified. Even if we do this optimization, the animation can still be slow if you use the "wrong" layout, right?

Btw, I'm not sure I understand you correctly, but isn't the default transform origin center? In this way the element will be always centered while transforming.

**Comment by farfromrefug** [comment]
@MartoYankov about your point on measure not calling layout. I read differently in the code.
- ```requestLayout``` sets  ```_isLayoutValid = false``` [here](https://github.com/Akylas/NativeScript/blob/1134621314f172d38483489fad8e45f6ab0d8f1d/nativescript-core/ui/core/view/view-common.ts#L800) and ```PFLAG_FORCE_LAYOUT``` [here](https://github.com/NativeScript/NativeScript/blob/904590ee7d06fabc30df50e421109bcd248b5815/nativescript-core/ui/core/view/view.ios.ts#L57)
- measure is forced because of ```PFLAG_FORCE_LAYOUT```  [here](https://github.com/NativeScript/NativeScript/blob/904590ee7d06fabc30df50e421109bcd248b5815/nativescript-core/ui/core/view/view.ios.ts#L72)
- ```PFLAG_LAYOUT_REQUIRED``` is set [here](https://github.com/NativeScript/NativeScript/blob/904590ee7d06fabc30df50e421109bcd248b5815/nativescript-core/ui/core/view/view.ios.ts#L78)
- layout is then forced by ```PFLAG_LAYOUT_REQUIRED``` [here](https://github.com/NativeScript/NativeScript/blob/904590ee7d06fabc30df50e421109bcd248b5815/nativescript-core/ui/core/view/view.ios.ts#L95)
- bounds Changed is actually ignored

That might the reason for the stuttering in my case!

Now about the centering thing. look at this playground
https://play.nativescript.org/?template=play-vue&id=yQTS5W&v=3
What i want is for the StackLayout containing the 2 buttons to always be centered. Even during the animation
