### ISSUE TITLE
[iOS][BottomNavigation] Images are not vertically centered

### ISSUE THREAD

**Issue by flodaniel** [NativeScript/NativeScript#7991]
**Environment**

 - CLI: 6.1.2
 - Android Runtime: 6.1.1
 - iOS Runtime: 6.1.1

**Describe the bug**
On iOS the Images within the TabStrip are not vertically centered within a BottomNavigation. On Android they are perfectly centered. 
Here is a screenshot from two running iphone Simulators, where you should be able to see the issue. 

![image](https://user-images.githubusercontent.com/6661557/67211415-fea40580-f41a-11e9-98fb-8c2f90763fe5.png)

**To Reproduce**
```
<TabStrip #mainNavigationStrip isIconSizeFixed="false" iosIconRenderingMode="alwaysOriginal">
        <TabStripItem class="nav-icon" [class.ios]="isIOS()" [class.selected]="selectedTab === 0">
            <Image src="font://&#xf25d;" class="fas"></Image>
        </TabStripItem>
        <TabStripItem class="nav-icon" [class.ios]="isIOS()" [class.selected]="selectedTab === 1">
            <Image src="font://&#xf375;" class="fas"></Image>
        </TabStripItem>
        <TabStripItem class="nav-icon" [class.ios]="isIOS()" [class.selected]="selectedTab === 2">
            <Image src="font://&#xf100;" class="fas"></Image>
        </TabStripItem>
        <TabStripItem class="nav-icon" [class.ios]="isIOS()" [class.selected]="selectedTab === 3">
            <Image src="font://&#xf153;" class="fas"></Image>
        </TabStripItem>
        <TabStripItem class="nav-icon" [class.ios]="isIOS()" [class.selected]="selectedTab === 4">
            <Image src="font://&#xf345;" class="fas"></Image>
        </TabStripItem>
        
    </TabStrip>
````

**Expected behavior**

The Images (using Ionicons) should be centered vertically. Styling on Image, TabStripItem or Tabstrip is not working (not applied at all).

**Comment by tsonevn** [comment]
HI @Firetrip,
I was able to recreate the case on iPhone 8 simulator. As a reference, I am attaching [the project](https://play.nativescript.org/?template=play-tsc&id=pSYI2Z&v=2), which I used for debugging. On that matter, I will mark this as a bug and we will investigate it further. Regarding the styling of BottomNavigation on iOS, keep in mind that you can’t style individual TabStripItem components on the iOS Tabs component. You can style them on the TabStrip component together. For more info, check out the blog post [here](https://www.nativescript.org/blog/tabs-and-bottomnavigation-nativescripts-two-new-components).

**Comment by NickIliev** [comment]
Happening also with `TabView`.

+1 Reported from t.1432041

**Comment by Ayushpatel71106** [comment]
Hii i am working on nativescript ,but i using the tabitem horizontal is working but vertical is not working.

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
