### ISSUE TITLE
install nativescript on mac error.

### ISSUE THREAD

**Issue by bitcard** [NativeScript/NativeScript#8]
when I install the nativescript, the final step appear the follow errors, and stop this step forever:
ws@0.4.32 install /usr/local/lib/node_modules/nativescript/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

I try node.js 0.10.33 and 0.10.28(my windows all is ok), also install node-gyp and upgrade npm to 2.7. 

thanks for your reply.

**Comment by bitcard** [comment]
I solved it, sudo npm install node-gyp, and sudo chmod 777 /User/your usename/.node-gyp, it need rebuild node-gyp.

**Comment by rafaband** [comment]
I got this error on install nativescript cli on my macbook:

sudo npm install nativescript -g --unsafe-perm
/usr/local/bin/tns -> /usr/local/lib/node_modules/nativescript/bin/tns
/usr/local/bin/nativescript -> /usr/local/lib/node_modules/nativescript/bin/tns

> fsevents@1.2.7 install /usr/local/lib/node_modules/nativescript/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/usr/local/lib/node_modules/nativescript/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> nativescript@5.4.2 postinstall /usr/local/lib/node_modules/nativescript
> node postinstall.js

unable to resolve processService
Failed to display command help { Error: Unknown command 'post-install-cli'. Try '$ tns help' for a full list of supported commands.
    at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:126:28)
    at Errors.failWithoutHelp (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:136:21)
    at HelpService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/services/help-service.js:178:26)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/nativescript/lib/common/services/help-service.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'Exception',
  message:
   'Unknown command \'post-install-cli\'. Try \'$ tns help\' for a full list of supported commands.',
  stack:
   'Error: Unknown command \'post-install-cli\'. Try \'$ tns help\' for a full list of supported commands.\n    at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:126:28)\n    at Errors.failWithoutHelp (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:136:21)\n    at HelpService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/services/help-service.js:178:26)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/local/lib/node_modules/nativescript/lib/common/services/help-service.js:4:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
  errorCode: 127,
  suppressCommandHelp: true,
  proxyAuthenticationRequired: false,
  printOnStdout: undefined }
+ nativescript@5.4.2
added 1018 packages from 1367 contributors and updated 1 package in 21.037s


![image](https://user-images.githubusercontent.com/829282/60770076-8b65c600-a0ad-11e9-9b6b-0dcc5298f458.png)
