### ISSUE TITLE
NativeScript RadSideDrawer template get crashed after some back and forth navigation

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/NativeScript#8007]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.0
 - Cross-platform modules: 6.1.2
 - Android Runtime: 6.1.2
 - Plugin(s):

**Describe the bug**
After about 1 minute of back and forth in nativescript-angular RadSideDrawer template, it gets crashed. Here is a video for a demonstration:

[crash.zip](https://github.com/NativeScript/NativeScript/files/3763285/crash.zip)

**To Reproduce**
Just get the nativescript-angular RadSideDrawer template via cli `tns create` command.

**Expected behavior**
Navigate without crashing.

**Comment by vahidvdn** [comment]
This also happens in core (js) template.

**Comment by vahidvdn** [comment]
After more investigating it turns out the RadSideDrawer crash relates to issue #7867 
When I remove background color in menu, it works without crash.

But still, it crashes when I use mapbox plugin. This seems it relates to the plugin itself.

**Comment by tsonevn** [comment]
Closing this issue in favour of https://github.com/NativeScript/NativeScript/issues/7867

**Comment by vahidvdn** [comment]
@tsonevn Thanks. Is there any plan when it will get fixed?
