### ISSUE TITLE
Chained animations lose state on iOS

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/NativeScript#801]
The code below chains two animations—one that rotates an image 90 degrees, and a second that scales it to twice its size.

``` xml
<Page loaded="loaded">
    <AbsoluteLayout>
        <Image src="~/logo.png" id="logo" />
    </AbsoluteLayout>
</Page>
```
```js
exports.loaded = function(args) {
    var page = args.object;
    var message = page.getViewById("logo");
    message.animate({
        rotate: 90,
        duration: 1000
    }).then(function() {
        return message.animate({
            scale: { x: 2, y: 2 },
            duration: 1000
        });
    });
};
```

This works as intended on Android, but on iOS the second animation incorrectly rotates the image during the scaling, and then reverts to the appropriate value when the animation completes. You can see this behavior in the gif below:

![ios-bug](https://cloud.githubusercontent.com/assets/544280/10029220/c876f8fa-613e-11e5-9750-44d7b1c36118.gif)

**Comment by hamorphis** [comment]
I will investigate this. Without looking at it, what comes to my mind is that the rotate and scale transform use the same spots in the affine transform matrix, i.e. UIView.transform property.
