### ISSUE TITLE
Nativescript videoplayer not showing on tns build (ios)

### ISSUE THREAD

**Issue by hetd54** [NativeScript/NativeScript#8018]
**Environment**

CLI: 6.1.2
Xcode: 11.1.0
tns-ios: 6.1.0

**Describe the bug**

When building for ios 13, videos do not show up in the view (but they _are_ there, and they do play, because you can hear the sound of the video). You can get the videos to show up temporarily the following way:

"tns run ios"
When the app opens, and the video isn't displaying, change anything in the file (like on the xml page)
When the app updates and re-opens, the video will be there. 

However, any time you close the app manually and reopen it, the video is no longer there (but it plays in the background again).

**To Reproduce**
build a plain typescript app
add nativescript-videoplayer plugin
add to your xml file:
`<StackLayout class="home-panel">
			<VideoPlayer:Video id="nativeVideoPlayer" controls="false" autoplay="true" height="300" src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" />
		</StackLayout>`
tns run ios
You will see that the video is not there, but you can hear it playing.
Change anything in the file (like on the xml page)
When the app updates and re-opens, the video will be there. 
Close the app manually, and reopen
The video (again) is not there, but you can hear it playing.

**Comment by tsonevn** [comment]
Hi @hetd54,
This problem seems to be related to the `nativescript-videoplayer`. On that matter, please contact the plugin's author by opening a new issue in the repository [here](https://github.com/nstudio/nativescript-videoplayer).

**Comment by hetd54** [comment]
Thanks for directing me to the right place. 

Everything was working with NativeScript 6.0, though. Now even when I go back to 6.0, it is not working. I also rolled back to 5.4 but I saw that the NativeScript team is not fixing a major issue with ios 13 for previous versions of NativeScript (https://github.com/NativeScript/nativescript-cli/issues/4741), so I was forced to update to 6.1

**Comment by hetd54** [comment]
Hello,

I confirmed that this behavior is identical when using nativescript-exoplayer. This suggests that it is not specifically a nativescript-videoplayer issue but rather something to do with nativescript and ios 13, correct? Would love to hear others' thoughts because I am not sure how to solve this issue!

**Comment by NathanaelA** [comment]
@hetd54 - FYI: We are shipping several apps using the NS-ExoPlayer on NS 6.x and iOS 13 and aren't having any major issues with it.
