### ISSUE TITLE
Ability to modify font size on SegmentedBar/SegmentedBarItem

### ISSUE THREAD

**Issue by ligaz** [NativeScript/NativeScript#802]
_From @nguyenbn on September 22, 2015 15:39_

Is there the ability to modify font size on SegmentedBar/SegmentedBarItem?  If so, how do I do that?  I tried font-size through CSS.  If not, I'd like to suggest that as a feature request.

Thanks

_Copied from original issue: NativeScript/nativescript-cli#950_

**Comment by nsndeck** [comment]
Closed with commit #995.
