### ISSUE TITLE
Modal in IOS does not respond to transparency.

### ISSUE THREAD

**Issue by vicmasa** [NativeScript/NativeScript#8028]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: {N} 6.1.2  in  Mac OS Hight Sierra 10.13.6
 - Cross-platform modules:  Javascript plane
 - Android Runtime: 
 - iOS Runtime: 
 - Plugin(s): SideDrawer

**Describe the bug**
Hi, I'm working on {N} 6.1.2. and I have a problem:
* I cannot place transparency in my modal (backgroundColor = "transparent" does not work in IOS).

**To Reproduce**
Clone https://github.com/vicmasa/test.git
Select button open modal

**Expected behavior**
Background transparent in IOS.

**Sample project**
https://github.com/vicmasa/test.git

**Additional context**

**Comment by tsonevn** [comment]
HI @vicmasa,
I've checked the attached repository, however, there is no project. In your case, you might need to set up `presentationStyle` property to `UIModalPresentationStyle.OverFullScreen`. For example:
page.showModal("ui-tests-app/modal-view/login-page", {
        context,
        closeCallback: createCloseCallback(label, context),
        fullscreen: false,
            ios: {
                presentationStyle: UIModalPresentationStyle.OverFullScreen
            }
    });

**Comment by vicmasa** [comment]
Funcionó.
Muchas gracias.
