### ISSUE TITLE
ObjCExposedMethods: how to return enum 

### ISSUE THREAD

**Issue by demetrio812** [NativeScript/NativeScript#8029]
Hello,
from this document: https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/creating_a_basic_video_player_ios_and_tvos/controlling_background_audio

In order to control the background audio, the latest iOS 13 version requires that the target methods for the controls returns MPRemoteCommandHandlerStatus.

Before iOS 13 I was using a CommandCenterHandler with the following code:

    public static ObjCExposedMethods = {
        'cmdPause': { returns: interop.types.void, params: [interop.types.id] },
        'cmdPlay': { returns: interop.types.void, params: [interop.types.id] },
        'cmdStop': { returns: interop.types.void, params: [interop.types.id] },
        'cmdTogglePlay': { returns: interop.types.void, params: [interop.types.id] },
        'cmdNext': { returns: interop.types.void, params: [interop.types.id] },
        'cmdPrev': { returns: interop.types.void, params: [interop.types.id] },
        'cmdSkipFwd': { returns: interop.types.void, params: [interop.types.id] },
        'cmdSkipBack': { returns: interop.types.void, params: [interop.types.id] },
        'cmdSeekFwd': { returns: interop.types.void, params: [interop.types.id] },
        'cmdSeekBack': { returns: interop.types.void, params: [interop.types.id] },
        'cmdLike': { returns: interop.types.void, params: [interop.types.id] },
        'cmdDislike': { returns: interop.types.void, params: [interop.types.id] },
        'cmdBookmark': { returns: interop.types.void, params: [interop.types.id] },
        'cmdRating': { returns: interop.types.void, params: [interop.types.id] },
        'cmdChangePlaybackRate': { returns: interop.types.void, params: [interop.types.id] }
    };

Then I was initialising the handler:

    this._cmdCenterHandler = (<any>CommandCenterHandler).initWithOwner(new WeakRef(<any>this));

And connecting its methods to the different remote commands in this way:

    MPRemoteCommandCenter.sharedCommandCenter()
    .togglePlayPauseCommand.addTargetAction(this._cmdCenterHandler, 'cmdTogglePlay');

And it was working, now it's required to return that enum (MPRemoteCommandHandlerStatus), is it possible to do it in Nativescript? What should I use instead of interop.types.void? I've tried many things but they aren't working

Thanks,
Dem

**Comment by tsonevn** [comment]
Hi @demetrio812,
In your case, you may need to install the [tns-platform-declarations](https://www.npmjs.com/package/tns-platform-declarations) in your project. Then you should be able to use this enum in your custom code. For example:
```
MPRemoteCommandHandlerStatus.DeviceNotFound
```
Let me know if I am missing something or if your case is different.

**Comment by demetrio812** [comment]
@tsonevn the issue is that if I try to add this:

MPRemoteCommandCenter.sharedCommandCenter().togglePlayPauseCommand.addTargetAction(this._cmdCenterHandler, 'cmdTogglePlay');

It crashes now (before iOS 13 it was working) with this error:

```
NativeScript caught signal 11.
Native Stack:
1   0x10b2bccb1 sig_handler(int)
2   0x10ee6641b MPSignalHandler
3   0x110755b1d _sigtramp
4   0x28
5   0x11067cb85 libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step()
6   0x110680e58 _Unwind_RaiseException
7   0x1101bc8bd __cxa_throw
8   0x10f72cc44 _objc_exception_destructor(void*)
9   0x10fd3af68 +[NSException raise:format:arguments:]
10  0x10c45fde9 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
11  0x12fa81230 -[MPRemoteCommand addTarget:action:]
12  0x10bc5afbd ffi_call_unix64
13  0x13997b560
JS Stack:
addTargetAction([native code])
at AudioService(file:///src/app/shared/services/audio.service.ts:35:93)
at AudioService([native code])
at file:///node_modules/@angular/core/fesm5/core.js:1091:71
at _createProviderInstance(file:///node_modules/@angular/core/fesm5/core.js:18480:0)
at resolveNgModuleDep(file:///node_modules/@angular/core/fesm5/core.js:18455:0)
at injectArgs(file:///node_modules/@angular/core/fesm5/core.js:589:0)
at file:///node_modules/@angular/core/fesm5/core.js:1091:71
at _createProviderInstance(file:///node_modules/@angular/core/fesm5/core.js:18480:0)
at resolveNgModuleDep(file:///node_modules/@angular/core/fesm5/core.js:18455:0)
at createClass(file:///node_modules/@angular/core/fesm5/core.js:19400:0)
at createDirectiveInstance(file:///node_modules/@angular/core/fesm5/core.js:19271:0)
at createViewNodes(file:///node_modules/@angular/core/fesm5/core.js:27489:0)
at createRootView(file:///node_modules/@angular/core/fesm5/core.js:27403:0)
at callWithDebugContext(file:///node_modules/@angular/core/fesm5/core.js:28411:0)
at create(file:///node_modules/@angular/core/fesm5/core.js:18750:0)
at bootstrap(file:///node_modules/@angular/core/fesm5/core.js:25162:0)
at forEach
at _moduleDoBootstrap(file:///node_modules/@angular/core/fesm5/core.js:24884:0)
at file:///node_modules/@angular/core/fesm5/core.js:24852:0
at onInvoke(file:///node_modules/@angular/core/fesm5/core.js:24349:0)
at run(file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:138:0)
at file:///app/vendor.js:11992<…>
```

And I think the reason is the declaration in `ObjCExposedMethods`, I've got tns-platform-declarations but I don't know how to specify that it returns the MPRemoteCommandHandlerStatus enum here:

```
public static ObjCExposedMethods = {
        'cmdPause': { returns: interop.types.void, params: [interop.types.id] },
...
};
```

I've tried: 
* `returns: interop.types."class"` 
* `returns: interop.types.class` 
* `returns: interop.types.id` 
* `returns: interop.types.protocol` 
* `returns: any` 
* `returns: interop.Type<any>` 
* `interop.Type<MPRemoteCommandHandlerStatus>`

I've also searched github code to find a similar case but didn't find anything helpful

How can I point addTarget action to a method that returns the specific enum? Is it possible?

Thanks

**Comment by tsonevn** [comment]
Hi @demetrio812,
We reviewed the latest log, however, because of [this known issue](https://github.com/NativeScript/ios-runtime/issues/1044) with the iOS simulator, the log does not show the exact problem. On that matter, I would suggest building the app on the device, which might help you in finding the problem. Meanwhile, you can change the `cmdTogglePlay` definition as follows:

`'cmdTogglePlay': { returns: interop.types.void, params: [interop.types.id] },` -> 
`'cmdTogglePlay': { returns: MPRemoteCommandHandlerStatus, params: [MPRemoteCommandEvent] },`

You should use types that are defined in the [iOS documentation](https://developer.apple.com/documentation/mediaplayer/mpremotecommand/1622895-addtarget?language=objc).

**Comment by demetrio812** [comment]
Hello @tsonevn ,
sorry for the delay but I had some issue with XCode and my iOS 13.2 I had on the phone.

I've done the change you suggested but it's still crashing, on the phone I get his log:

```NativeScript caught signal 11.
Native Stack:
1   0x1060f3150 sig_handler(int)
2   0x105e0d048 MPSignalHandler
3   0x19b3e4894 <redacted>
4   0x1a7b4f6ec <redacted>
5   0x106bfc044 ffi_call_SYSV
6   0x106bf8ae4 ffi_call_int
7   0x106bf85e0 ffi_call
8   0x106070f90 NativeScript::FunctionWrapper::call(JSC::ExecState*)
9   0x106bf77e8 llint_entry
10  0x106bf5b64 llint_entry
11  0x106be160c vmEntryToJavaScript
12  0x106869a88 JSC::Interpreter::executeConstruct(JSC::ExecState*, JSC::JSObject*, JSC::ConstructType, JSC::ConstructData const&, JSC::ArgList const&, JSC::JSValue)
13  0x10618d5bc JSC::boundThisNoArgsFunctionConstruct(JSC::ExecState*)
14  0x106bf769c llint_entry
15  0x106bf6558 llint_entry
16  0x106bf5ac4 llint_entry
17  0x106bf5ac4 llint_entry
18  0x106bf5ac4 llint_entry
19  0x106bf5ac4 llint_entry
20  0x106bf5ac4 llint_entry
21  0x106bf5ac4 llint_entry
22  0x106bf5ac4 llint_entry
23  0x106bf5b64 llint_entry
24  0x106bf5b64 llint_entry
25  0x106bf5b64 llint_entry
26  0x106bf6804 llint_entry
27  0x106bf5b64 llint_entry
28  0x106bf5b64 llint_entry
29  0x106bf5b64 llint_entry
30  0x106bf5b64 llint_entry
31  0x106bf5b64 llint_entry
JS Stack:
addTargetAction([native code])
at AudioService(file:///src/app/shared/services/audio.service.ts:35:94)
at AudioService([native code])
at file:///node_modules/@angular/core/fesm5/core.js:1091:71
at _createProviderInstance(file:///node_modules/@angular/core/fesm5/core.js:18480:0)
at resolveNgModuleDep(file:///node_modules/@angular/core/fesm5/core.js:18455:0)
at injectArgs(file:///node_modules/@angular/core/fesm5/core.js:589:0)
at file:///node_modules/@angular/core/fesm5/core.js:1091:71
at _createProviderInstance(file:///node_modules/@angular/core/fesm5/core.js:18480:0)
at resolveNgModuleDep(file:///node_modules/@angular/core/fesm5/core.js:18455:0)
at createClass(file:///node_modules/@angular/core/fesm5/core.js:19400:0)
at createDirectiveInstance(file:///node_modules/@angular/core/fesm5/core.js:19271:0)
at createViewNodes(file:///node_modules/@angular/core/fesm5/core.js:27489:0)
at createRootView(file:///node_modules/@angular/core/fesm5/core.js:27403:0)
at callWithDebugContext(file:///node_modules/@angular/core/fesm5/core.js:28411:0)
at create(file:///node_modules/@angular/core/fesm5/core.js:18750:0)
at bootstrap(file:///node_modules/@angular/core/fesm5/core.js:25162:0)
at forEach
at _moduleDoBootstrap(file:///node_modules/@angular/core/fesm5/core.js:24884:0)
at file:///node_modules/@angular/core/fesm5/core.js:24852:0
at onInvoke(file:///node_modules/@angular/core/fesm5/core.js:24349:0)
at run(file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:138:0)
at file:///app/vendor.js:13703<\M-b\M^@\M-&>
```

Not sure it helps, basically the issue is that I can't use the audio command center controls anymore, so I'm stuck with publishing the new release of the app, do you have any other hints?

Thanks,
Dem

**Comment by mbektchiev** [comment]
@demetrio812 I managed to reproduce and fix the error. In Xcode I saw that actually the crash is caused by a failed assertion inside the MediaPlayer SDK:
```
*** Assertion failure in -[MPRemoteCommand addTarget:action:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/MediaPlayer_Sim/MobileMusicPlayer-4017.200.33/SDK/MPRemoteCommand.m:134
```
Actuall,  you cannot use an `enum` type as a type reference because it is a plain JS object and you have to specify its underlying type. For [MPRemoteCommandHandlerStatus
](https://developer.apple.com/documentation/mediaplayer/mpremotecommandhandlerstatus?language=objc) it is actually [NSInteger](https://developer.apple.com/documentation/objectivec/nsinteger?language=objc), which is depending on the bitness of the CPU is either an `int32` or an `int64`. That's why the following signature should be used:
```
public static nativeIntType = interop.sizeof(interop.types.id) == 4 ? interop.types.int32 : interop.types.int64;

public static ObjCExposedMethods = {
        'cmdPause': { returns: nativeIntType, params: [MPRemoteCommandEvent] },
...
};
```

I hope this helps.

**Comment by mbektchiev** [comment]
When I ran it on a device I managed to see the log of the native exception being thrown. It's strange that in your case it was the signal handler that kicked in ...
```
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x104d45178 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x104dd2220 -[TNSRuntime executeModule:referredBy:]
3   0x104dd1dd8 -[TNSRuntime executeModule:]
4   0x104217704 main
5   0x199143460 <redacted>
JavaScript stack trace:
addTargetAction(file:///app/index.js:18:83)
at anonymous(file:///app/index.js:18:83)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
JavaScript error:
file:///app/index.js:18:83: JS ERROR Error: Unsupported action method signature. Must return MPRemoteCommandHandlerStatus or take a completion handler as the second argument.
```

**Comment by demetrio812** [comment]
Hello @mbektchiev 
Thanks a lot for your help, it works now!

Dem
