### ISSUE TITLE
[Android] Bottomsheet: app crashes when there is active button in the bottomsheet and being dismissed

### ISSUE THREAD

**Issue by hamidbsd** [NativeScript/NativeScript#8038]
**Environment**
 - CLI: 6.1.2 
 - Cross-platform modules: Angular 8.2.11
 - Android Runtime: 6.1.2
 - Plugin(s): nativescript-material-components (BottomSheet) 2.5.2

**Describe the bug**
App crashes when touch event is being captured on the BottomSheet and the BottomSheet is being dismissed.
Has been reported on nativescript-material-components repo earlier:
https://github.com/Akylas/nativescript-material-components/issues/71

**To Reproduce**
To reproduce, simply capture (touch) event instead of (tap) on the component being shown on the bottomsheet and it will crash when it is dismissed.

**Expected behavior**
Not to crash

**Sample project**
nativescript-material-components (BottomSheet) demo-ng

**Crash Log**

> 
> An uncaught Exception occurred on "main" thread.
> Calling js method onDismiss failed
> TypeError: Cannot read property 'setOnTouchListener' of null
> 
> StackTrace:
> 	push.../node_modules/tns-core-modules/ui/core/view/view.js.View.onUnloaded(file:///data/data/app.name/files/app/vendor.js:102970:38)
> 	at (file:///data/data/app.name/files/app/vendor.js:101093:92)
> 	at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///data/data/app.name/files/app/vendor.js:101082:9)
> 	at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callUnloaded(file:///data/data/app.name/files/app/vendor.js:101093:14)
> 	at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.unloadView(file:///data/data/app.name/files/app/vendor.js:101222:18)
> 	at (file:///data/data/app.name/files/app/vendor.js:101024:19)
> 	at push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///data/data/app.name/files/app/vendor.js:110064:26)
> 	at push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild(file:///data/data/app.name/files/app/vendor.js:102584:14)

**Comment by hamidbsd** [comment]
@farfromrefug suggested I report it here.
https://github.com/Akylas/nativescript-material-components/issues/71

**Comment by tsonevn** [comment]
Hi @hamidbsd,
Can you send us a sample project, where the issue, you are facing, can be reproduced?

**Comment by farfromrefug** [comment]
@tsonevn i asked @hamidbsd to add it here cause i already see an issue in the code:
https://github.com/NativeScript/NativeScript/blob/cc97a1680009f1bf6dbf97c421f6e8dc535295b5/nativescript-core/ui/core/view/view.android.ts#L382
There you don't check for ```nativeViewProtected```. And it might be null un unloaded.
I think it is an edge case

Also should i mention that it should be done in ```disposeNativeView``` and not ```onUnloaded```

**Comment by hamidbsd** [comment]
Here is a simple project to reproduce the crash.
I needs {N} 6.2.1 + latest Angular + nativescript-material-bottomsheet@3.0.0
https://www.dropbox.com/s/m1weedpegpo0rlv/Bottomsheet%20crashing.zip?dl=0

**Comment by hamidbsd** [comment]
@tsonevn I did what @farfromrefug suggested and it worked!
I changed this:
https://github.com/NativeScript/NativeScript/blob/cc97a1680009f1bf6dbf97c421f6e8dc535295b5/nativescript-core/ui/core/view/view.android.ts#L381-L385

to this:
```
        if (this.touchListenerIsSet) {
            this.touchListenerIsSet = false;
            if (this.nativeViewProtected) {
                this.nativeViewProtected.setOnTouchListener(null);
                this.nativeViewProtected.setClickable(this._isClickable);
            }
        }

```
And no crashes anymore!

**Comment by hamidbsd** [comment]
The bug has been fixed as of nativescript-material-bottomsheet@3.0.2
