### ISSUE TITLE
 I have 2 Css Files App.css and App-night.css, how can i change them programmatically??  

### ISSUE THREAD

**Issue by sunpasup** [NativeScript/NativeScript#8039]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by tsonevn** [comment]
HI @sunpasup,
Check out this StackOverflow [thread](https://stackoverflow.com/questions/36307884/change-nativescript-application-wide-css-file-dynamically).
