### ISSUE TITLE
 I have 2 Css Files App.css and App-night.css, how can i change them programmatically?

### ISSUE THREAD

**Issue by sunpasup** [NativeScript/NativeScript#8040]
was using nativescript-themes plugin till now, now its not working with {N} 5.0 and above.

any other alternatives?? 

TIA

**Comment by NathanaelA** [comment]
If you have a ProPlugins subscription; then `tns plugin add @proplugins/nativeScript-themes`  for sure works with NS6.  All ProPlugins are NS6 compatible.

**Comment by tsonevn** [comment]
HI @sunpasup,
This plugin not supported by the NativeScript team and we can not guarantee that the latest version, that is uploaded in npm will work with {N} 6. Regarding that, if you want to keep using this plugin, you may review the suggestion of @NathanaelA. Another option is to create your [own plugin](https://docs.nativescript.org/plugins/building-plugins), that provides the needed functionality for your app.

**Comment by sunpasup** [comment]
> If you have a ProPlugins subscription; then `tns plugin add @proplugins/nativeScript-themes` for sure works with NS6. All ProPlugins are NS6 compatible.

i have bought this Subscription recently.. and tried with this plugin also, but no Luck.  

this is what i kept in app.component.ts 

`var themes = require('@proplugins/nativescript-themes');
 if (this.themeValue == 'off') {
                themes.applyTheme(themes.getAppliedTheme('app.css'));

            }
            if (this.themeValue == 'on') {
                themes.applyTheme(themes.getAppliedTheme('app-night.css'));

            }`

still no luck.

**Comment by sunpasup** [comment]
@NathanaelA 

> > If you have a ProPlugins subscription; then `tns plugin add @proplugins/nativeScript-themes` for sure works with NS6. All ProPlugins are NS6 compatible.
> 
> i have bought this Subscription recently.. and tried with this plugin also, but no Luck.
> 
> this is what i kept in app.component.ts
> 
> `var themes = require('@proplugins/nativescript-themes');`
> ` if (this.themeValue == 'off') {`
> `themes.applyTheme(themes.getAppliedTheme('app.css'));`
> 
> ```
>         }`
>        ` if (this.themeValue == 'on') {`
>             themes.applyTheme(themes.getAppliedTheme('app-night.css'));
> 
>         }`
> ```
> 
> still no luck.

@NathanaelA  Any Suggestions on this... TIA
