### ISSUE TITLE
[iOS] App crashes on iOS 13 when setting day of NSDateComponents object

### ISSUE THREAD

**Issue by AlessandroFBK** [NativeScript/NativeScript#8045]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.2
 - Cross-platform modules:
 - iOS Runtime: 6.1.1 and 6.2.0
 - Xcode 11
 - iOS 13

**Describe the bug**
App crashes at runtime when trying to set the day value of a NSDateComponents object.

**To Reproduce**
I need a NSDateComponent as it is a parameter required by the function `HKStatisticsCollectionQuery.alloc().initWithQuantityTypeQuantitySamplePredicateOptionsAnchorDateIntervalComponents` used to retrive data from HealthKit. 
```
    const intervalComponent = NSDateComponents.alloc();
    intervalComponent.day = 1;
```
What I get in the console is the following:
```
NativeScript caught signal 6.
Native Stack:
1   0x105764b18 sig_handler(int)
2   0x19741f884 <redacted>
3   0x197428c1c <redacted>
4   0x197378824 abort
5   0x197377c44 err
6   0x19776974c <redacted>
7   0x1976e88c4 CFDateComponentsIsValidDate
8   0x106248044 ffi_call_SYSV
9   0x106245780 ffi_call_int
10  0x10624527c ffi_call
11  0x1056e8f54 NativeScript::FunctionWrapper::call(JSC::ExecState*)
12  0x10622e454 vmEntryToNative
13  0x105ebbf34 JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&)
14  0x1060dbe1c JSC::callSetter(JSC::ExecState*, JSC::JSValue, JSC::JSValue, JSC::JSValue, JSC::ECMAMode)
15  0x10586d6a8 JSC::JSObject::putInlineSlow(JSC::ExecState*, JSC::PropertyName, JSC::JSValue, JSC::PutPropertySlot&)
16  0x105f6a49c llint_slow_path_put_by_id
17  0x10623621c llint_entry
18  0x106242804 llint_entry
19  0x106242804 llint_entry
20  0x106242804 llint_entry
21  0x106242764 llint_entry
22  0x106242764 llint_entry
23  0x106242764 llint_entry
24  0x106242764 llint_entry
25  0x106242804 llint_entry
26  0x106242764 llint_entry
27  0x106242764 llint_entry
28  0x106242804 llint_entry
29  0x106242764 llint_entry
30  0x106242804 llint_entry
31  0x106242764 llint_entry
JS Stack:
```
which I don't know how to interpret.
I'm not sure if [this commit](https://github.com/NativeScript/NativeScript/commit/3e8d6350b901243ae4aba45009815282d06e4fcd#diff-e8c0842f4507ef1a9dfd9e4a49801037) can be somehow related to my issue.

**Expected behavior**
Set the interval of one single day.

**Additional context**
It happens only on iOS 13.*. On iOS 12.2 it works without any error.

**Comment by tsonevn** [comment]
Hi @AlessandroFBK,
Following the [iOS documentation](https://developer.apple.com/documentation/foundation/nsdatecomponents?language=objc), you should define the NSDateComponents as follows:
```
const intervalComponent = NSDateComponents.alloc().init();
intervalComponent.day = 1;
```
This should work as expected on both (iOS 12 and iOS 13).

**Comment by AlessandroFBK** [comment]
Great, it works!
Thank you for your precious help!
