### ISSUE TITLE
Topmost() returns undefined and cause application to crash, on activity resumed [Android]

### ISSUE THREAD

**Issue by bryanliujh** [NativeScript/NativeScript#8048]
**Environment**
 - Android: API level 28
 - Plugin(s): Nativescript 6.1.2

**Describe the bug**
1) Create an app with frameModule.topmost() onActivityResumed
2) Suspend App
3) Go to settings -> Display -> Advanced -> font size -> change the font size
4) Resume App, app display blank page, press home button, app crashed 

Error log: 
An uncaught Exception occurred on "main" thread.
Unable to stop activity 
Calling js method onStop failed
TypeError: Cannot read property 'backStack' of undefined

**Comment by tsonevn** [comment]
HI @bryanliujh,
I was able to recreate the issue, I will mark this as a bug and we will investigate it further.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/3798356/Archive.zip)
