### ISSUE TITLE
Missing console.dump on ios...

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#805]
_From @enchev on September 23, 2015 6:36_

_From @NathanaelA on September 19, 2015 8:6_

I copied some code over from Android to ios; and found out the console.dump doesn't work.   Shouldn't we take the same dump routine that is available on the ios and patch the console prototype to use it?   

_Copied from original issue: NativeScript/NativeScript#778_

_Copied from original issue: NativeScript/ios-runtime#326_

**Comment by enchev** [comment]
_From @jasssonpet on September 23, 2015 7:53_

`console.dump()` isn't implemented in any of the following popular APIs:

* [Node.js console](https://nodejs.org/api/console.html)
* [Chrome console](https://developer.chrome.com/devtools/docs/console-api)
* [Firefox console](https://developer.mozilla.org/en-US/docs/Web/API/Console)
* [IE console](https://msdn.microsoft.com/en-us/library/gg589530(v=vs.85).aspx)
* [Safari console](https://developer.apple.com/library/mac/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/Console/Console.html)
* [Opera console](http://www.opera.com/dragonfly/documentation/console/)

IMO, if we want to support it on iOS, the same as we do on Android, we have to add the same [implementation from the modules](https://github.com/NativeScript/NativeScript/blob/v1.3.0/console/console.ts#L335-L384) in the runtime, which is a suboptimal and error-prone. I think, that the `dump` method (and any other custom one) should be added in the NativeScript modules, so that it can work the same on iOS *and* Android.

IMO, we should also replace the `console.dump(obj)` method with `console.log(f(obj))`, where `f` is something like [util.inspect()](https://nodejs.org/api/util.html#util_util_inspect_object_options) in node.

Related to: https://github.com/NativeScript/ios-runtime/issues/261

**Comment by NathanaelA** [comment]
To be honest, the biggest issue is consistency for me.  

 If you don't want to support dump on ios; then please remove it from android and the docs.  It is **extreamly** annoying to have code that works on one platform blow up when you move it to the other platform.    My personal thought would be just to monkey patch console.prototype.dump on ios to add it in the common modules.   But I won't disagree with @jasssonpet  about using a helper function in console.log, that would work just as well.  But most of all I just want consistency.  :grinning:

**Comment by valentinstoychev** [comment]
@NathanaelA - consistency is a major concern here and it is with biggest priority for us, so we will make sure to fix this. cc: @atanasovg

**Comment by emiloberg** [comment]
One of the first thing I do, no matter if it's a {N} project or a Node project, is that I add [eyes.js](https://www.npmjs.com/package/eyes) for outputing stuff. Colorized and nice formatted. I could definitely see this being a core part of {N}.

Footnote: 
Unfortunately eyes asks for `process.stdout`. To make it work in a {N} context you've to change [Line 34](https://github.com/cloudhead/eyes.js/blob/master/lib/eyes.js#L34) from `stream: process.stdout,` to `stream: null`.

**Comment by enchev** [comment]
I've just merged to master `console.dump` for iOS and I'm closing this.
