### ISSUE TITLE
hmr doesn't apply changes in pages other than main page

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/NativeScript#8050]
**Environment**

 - CLI: 6.1
 - Cross-platform modules: 6.1.2
 - Android Runtime: 6.1.2

**Describe the bug**
I installed sidedrawer template (angular project)  and when I apply some changes in other pages like search (other than the home page), the changes are not going to be applied.

**To Reproduce**
Install the angular sidedrawer template and try to change some code in other pages. (approximately 50% of the time, it doesn't refresh the app. But cannot find when it doesn't work) 

**Expected behavior**
To update changes.

**Additional context**
Sometimes it just works fine, I don't know when it happens.

**Comment by vahidvdn** [comment]
After some more investigation, I found out when you are on the home page and make a change on another page, it doesn't refresh the app. You have to be on the page, in which you are going to make some changes.

**Comment by tsonevn** [comment]
Hi @vahidvdn,
I tested the case with newly created {N} Angular project using the SideDrawer template. However, I was unable to recreate the issue. Here are the steps that I follow:
1. create new NativeScript Angular project using the SideDrawer
2. build the app with `tns run android` command
3. make a change in SearchComponent in the XML or Code Behind.
4. Navigate to SearchComponent.
I've rebuilt the app around ten times and the changes have always been appropriately applied while following the above steps. On that matter, is there something specific, that should be made to recreate more regularly the problem you are facing(something specific on the project structure or the way it is built)?

**Comment by vahidvdn** [comment]
Hi @tsonevn 
On my side, it happens. I'm in windows.

Let me explain more. I'm on the home page, then I make some changes to the setting page. In cli it rebuilds but it doesn't refresh the app. Then when I navigate to the setting page, I can't see the changes which I made in html file.

**Comment by vahidvdn** [comment]
Hi @tsonevn 

Is there any update on this? I really get a lot of problems. I save something in home.component.ts, it saves and refreshes, then I change something in home.service.ts, it doesn't refresh and from this point, If I even make any changes in home.component.ts, it doesn't refresh anymore.

**Comment by szgozcan** [comment]
Hi, I would say that I have the similar problem after updating to Nativescript 6.3. HMR stopped to make changes when I work with my pages, but when I make changes in AndroidManifest.xml HMR responds. 
After making changes in pages and pressing save in console the following lines appear and nothing next happens.
       `Webpack compilation complete. Watching for file changes.` 
       `Webpack build done!` 
I don't know if it is related but I have begun to get 
 `JS: topmost() is deprecated. Use Frame.topmost() instead.`
After that complaining I deleted all topmost() from my codes for navigation. I deleted platforms, hooks and node modules and made a new run. But I still get the topmost() warning and HMR does not work either.  But navigation works.
   

    `{
       "nativescript": {
        "id": "org.nativescript........",
        "tns-ios": {
         "version": "6.1.0"
       },
       "tns-android": {
         "version": "6.3.0"
       }
      },
      "description": "NativeScript Application",
      "license": "SEE LICENSE IN <your-license-filename>",
      "repository": "<fill-your-repository-here>",
      "dependencies": {
        "nativescript-admob": "^4.0.1",
        "nativescript-audio-player": "^1.0.3",
       "nativescript-image": "^2.2.5",
       "nativescript-rater": "^2.1.1",
        "nativescript-theme-core": "~1.0.6",
       "tns-core-modules": "^6.3.2"
     },
      "devDependencies": {
       "nativescript-dev-webpack": "~1.2.0"
      },`



Thx

**Comment by vahidvdn** [comment]
For me, I had to disable the `hmr`, since it's really unstable and doesn't refresh the app in many cases.

**Comment by szgozcan** [comment]
Hi @vahidvdn,
I do not know how to disable HMR, how it is handled? 
Thx

**Comment by Fatme** [comment]
@szgozcan,

The HMR can be disabled using `--no-hmr` flag but it is not the recommended solution as it doesn't fix the root cause of the problem.

**Comment by vahidvdn** [comment]
@Fatme `hmr` shouldn't have been on by default since it's completely unstable.

**Comment by DimitarTachev** [comment]
@vahidvdn, @szgozcan,

We've tried to reproduce such behavior on our side but everything is working as expected even if we try in an Angular app with lazy routes like the steps below.
1) `tns create ngTabs --template tns-template-tab-navigation-ng` (nativescript@6.3.0)
2) `cd ngTabs`
3) `tns run android`
4) Edit something in the Search page (e.g. `src/app/search/search.component.html`)
5) Navigate to the Search tab
6) The change is applied as expected

Could you provide us with the exact steps to reproduce the issue in some of our templates or a sample application demonstrating the problematic behavior?
