### ISSUE TITLE
Cannot observe/watch UI component's array property

### ISSUE THREAD

**Issue by mannok** [NativeScript/NativeScript#8055]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1
 - Cross-platform modules:6.1.2
 - Android Runtime:6.1.2

**Describe the bug**
Take `Frame` as an example, I want to watch its `backStack` in order to know if the `backStack` changed, and:

- If I apply `frame.on('propertyChange', () => { console.log('changed'); })`, `propertyChange` event will not be fired when the property is an array.
- If I apply `frame.backStack.on('propertyChange', () => { console.log('changed'); })` , it will throw me an exception as the `frame.backStack` is a plain array.

How can I observe UI component's property like this?

**Comment by tsonevn** [comment]
Hi @mannok,
Can you provide more info about, about your use case and what you are trying to achieve as a final result? Following your example, currently, you cannot set a similar global event listener, which can show the changes in the backStack. In your case, you can create custom logic in the app, while using page [navigation events](https://docs.nativescript.org/ui/components/page#page-events) and save globally which pages have been loaded or unloaded and which is the current page, shown on the screen.

**Comment by mannok** [comment]
@tsonevn Thank you for your promptly reply. I am trying to highlight the button in drawer which has activated the current page's stack. 

In my scenario, all buttons in drawer are bound to a certain starting page. For every frame navigation event (if there is any), I would check if the current frame's back stack contain any of those buttons' bound first page. If yes, I will highlight that button.

I have thought about your solution like... handle it by pages' loaded/unloaded/navigation events. However, I think this maybe not a good solution as I may need to do it for all pages if I adoption this solution. Also, I cannot guarantee all pages will be created by me or all of them are already implemented with those events.

Please advice. Thank you

**Comment by NickIliev** [comment]
@mannok 

Regarding 

> In my scenario, all buttons in a drawer are bound to a certain starting page. For every frame navigation event (if there is any), I would check if the current frame's back stack contain any of those buttons' bound first page. If yes, I will highlight that button.

Tracking the `backStack` is a bit overkill - you could create custom flags for each starting page and while using `application-settings` you could remember when a page is being visited. As you have access to the drawer (via `getRootView` from `"tns-core-modules/application"`) you could then access the drawer content and apply any UI changes you want.

Apart from that - indeed the `backStack` is a plain JS array and when adding entries they won't trigger propertyChange.
