### ISSUE TITLE
Importing _app-variables.scss in a component breaks fontawesome

### ISSUE THREAD

**Issue by elonmallin** [NativeScript/NativeScript#8059]
**Environment**
 - CLI: 6.1.2
 - Android Runtime: 6.1.2
 - iOS Runtime: 6.1.0
 - nativescript-theme-core: 2.0.24
 - Using Nativescript with Angular

**Describe the bug**
Importing the `_app-variables.scss` file in a component breaks fontawesome for that component.

**To Reproduce**
1. Get fontawesome to work like you normally would.
2. Create a new component and add a fontawesome icon in a `<Label>`.
3. Do `@import '~/_app-variables';` in your new components scss file.
4. See that the icon stopped working (it shows the little rectangle with the x for symbol not found).

**Expected behavior**
The fontawesome icon should still work even though I imported `_app-variables.scss` into the component.

**Additional context**
My *_app-variables.scss*:
```scss
@import '~nativescript-theme-core/core';
@import '~nativescript-theme-core/core.compat';
... just color declarations below here ...
```

**Comment by bundyo** [comment]
What do you have in the _app-variables file?

**Comment by elonmallin** [comment]
I have just the two imports and some color variable declarations like I wrote in the **Additional context** section in the issue.

*_app-variables.scss*:
```scss
@import '~nativescript-theme-core/core';
@import '~nativescript-theme-core/core.compat';

// Custom colors
$primary-black: #333;
// more custom colors...
```

Trying it now without the imports it works. So it's definitely `@import '~nativescript-theme-core/core';` that breaks fontawesome.

So I guess the real issue then is, `@import '~nativescript-theme-core/core';` breaks fontawesome.

**Comment by elonmallin** [comment]
After more investigation, putting the `@imports` in the `_app-common` file makes both the theme and fontawesome work. But the angular template I started from put the `@imports` in the `_app-variables` file.

**Comment by bundyo** [comment]
The .fa class was indeed removed from the Theme, but this happened in 2.1.1, and it was also left in `compat` files, so this shouldn't break you.

This might have something to do with Angular component scoping - not sure, but Angular might traverse all `@imports` and add their component scope to each selector. The imports indeed should be in `_app.common`. In `_app-variables` you may want to load only the variables file for core or the skin, like this:

```scss
// Core variables
@import '~@nativescript/theme/scss/variables';

// Skin variables
@import '~@nativescript/theme/scss/variables/blue';
```

In latest templates, `_app-variables` was removed, as most colors are now derived from the skin itself.

**Comment by elonmallin** [comment]
Ah nice so that's what I have to do to access the variables. For me however I need to use this path: `@import '~nativescript-theme-core/scss/variables';`

**Comment by elonmallin** [comment]
Seems like this is fixed then if the structure in the latest template is already fine so this wouldn't happen. Closing this. Thanks =)
