### ISSUE TITLE
White screen on preview with Vue Typescript class components

### ISSUE THREAD

**Issue by DenisNP** [NativeScript/NativeScript#8065]
**Environment**
 - nativescript: 6.1.2
 - tns-core-modules: 6.2.0
 - Android Runtime: 9 PKQ1.190302.001
 - Phone model: Xiaomi Mi9T

**Describe the bug**
White screen on `tns preview` if you use class-component style.

**To Reproduce**
`npm install -g @vue/cli @vue/cli-init`
`vue init nativescript-vue/vue-cli-template my-app`

 select **typescript**, **vuex**, **no devtools**, **any theme**, then

`cd my-app`
`npm install`
`npm install vue-class-component vue-property-decorator --save-dev`

fix template bug with:
`npm install @types/node --save-dev`

Then rewrite `App.vue` in class-component style, e.g.: [App.vue](https://gist.github.com/DenisNP/65cb4554746b50157822329de1c29bcb)

`tns preview`

**Expected behavior**
Normal UI with label.

**Sample project**
Playground doesnt support `vue + typescript` (why?).  [Here is the repo with sample project](https://github.com/DenisNP/Nativescript-Vue-TS-sample)

**Comment by NickIliev** [comment]
@DenisNP I've recreated the case using your steps and on my side, everything works as expected - here is [the demo app](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/NativeScript/issue-8065).

**Comment by DenisNP** [comment]
@NickIliev you run it with `tns preview` (not `tns run`), and it worked? Maybe there is some platform specific case. I'll try to test it on another Android phone. For now here is my video with your repo (don't work): https://www.youtube.com/watch?v=kERvxpeo71g

**Comment by chumlee007** [comment]
I'm also experience the same issue, it does not work with tns preview. I get no errors, the component is mounted but the preview app displays a white screen. I have tested with your demo app as well

**Comment by NickIliev** [comment]
@DenisNP on it would work only with `tns build` or `tns run` . The `tns preview` is the same as running the project in PLaayground - and again you are probably missing the developer dependencies in the prebuild Preview app (which is to be expected).

**Comment by grreeenn** [comment]
@NickIliev which means that Vue+TS won't work in Preview?

I'm facing the same blank screen problem in preview on iOS. There are no errors in console, I see all of the elements creation output in terminal as expected, CSS works - but no elements are actually rendered on the screen. Is there any direction to look to?

**Comment by NathanWalker** [comment]
@grreeenn we’re working on preview app update in App Store which has iOS 14 support - what you’re seeing is expected right now - if possible to just run locally is suggested right now until we give clearance that preview app update is posted.

**Comment by grreeenn** [comment]
@NathanWalker I'm on iOS 13.7 - is it expected there too?

**Comment by NathanWalker** [comment]
Yes should have mentioned if you're using {N} 7 it's expected as the dep's of project and what's supported in preview must match.

**Comment by grreeenn** [comment]
@NathanWalker {N} 6, actually. tns-core-modules 6.3.2

**Comment by NathanWalker** [comment]
I should have read the whole issue above instead of just your comment 🙃 - it totally depends on your project deps. Some plugins are not supported in preview.
In general preview is meant for sample demos largely and not recommended for project development per say. Always have a good local dev environment.

**Comment by grreeenn** [comment]
I've just tried to run a clean install from vue-cli-plugin-nativescript-vue. But I get what you're saying, I'll explore more durable options to build the app. Thank you for your help! :)

**Comment by AntoKr** [comment]
same problem. has anyone found the solution?
