### ISSUE TITLE
z-index breaks the application on android 5.0

### ISSUE THREAD

**Issue by Nurgunkalol** [NativeScript/NativeScript#8069]
Hello!
After update nativescript, my transparent buttons on the android have broken, to find the answer I added the z-index and it worked, but after the release we noticed that the users of android 5 started to crash the application, problem was in the z-index of button

nativescript-angular
```
"nativescript": {
    "id": "",
    "tns-ios": {
      "version": "6.0.1"
    },
    "tns-android": {
      "version": "6.1.2"
    }
  }
```

**Comment by tsonevn** [comment]
Hi @Nurgunkalol 
I tested the case with the z-index with the latest NativeScirpt (v 6.2) on Android 5.0 emulator, however, was unable to recreate the problem. Can you send us the project or sample one, where the issue can be reproduced?
