### ISSUE TITLE
Status Bar

### ISSUE THREAD

**Issue by wellyson21** [NativeScript/NativeScript#8083]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
When ActionBar is hidden on android the content is overlaying the status bar.
The content does not respect the status bar.

**To Reproduce**
Set page.actionBarHidden=true

**Expected behavior**

**Sample project**

**Additional context**

**Comment by NickIliev** [comment]
@wellyson21 I am using[ the Playground demo](https://play.nativescript.org/?template=play-ng&id=ipIwj1) (Angular based) where I am setting actionBarHidden to true in home.component.ts, but I am unable to reproduce the issue. If possible, please provide a demo depicting the issue.
