### ISSUE TITLE
[BottomNavigation] iOS "More" tab

### ISSUE THREAD

**Issue by jeroendk** [NativeScript/NativeScript#8085]
**Is your feature request related to a problem? Please describe.**
The iOS more tab seems to be lacking in the new BottomNavigation or it's unclear to me how to make this work. Not sure if this is an open feature or known issue for https://github.com/NativeScript/NativeScript/issues/6967?

**Describe the solution you'd like**
Automatically add the "more" tab when there are 6 or more tabs for iOS.

**Comment by NickIliev** [comment]
@jeroendk so far we are not planning of exposing the "More" functionality for the BottomNavigaiton.

The reason for that decision is that we are looking for a cross-platform solution that would have identical features for both Android and iOS. On Android, there is no "More" option for tab-based navigation. Another limitation which is hard-to-resolve with the "More" options is that it wouldn't work with the Angular router (as you won't be able to create working navigation from the "More" options) - this is also strictly NativeScript related and one of the reasons, the team decided to strip off this functionality.

Some of the design guidelines are suggesting that UI with 5 or more options (links, tabs) should be created via a side drawer while UI with 2-5 options should use the equivalents of Tabs and BottomNavigaiton.
