### ISSUE TITLE
ScrollView with ListView

### ISSUE THREAD

**Issue by cheungcl** [NativeScript/NativeScript#8086]
Nativescript 6.2.0

My ListView contains very long items items. I would like to enclose the ListVew with ScrollView so user can scroll horizontally.  The following code works well with Android, but empty items are displayed on iOS

<GridLayout>
    <ScrollView  orientation="horizontal" >
    <ListView [items]="items">
        <ng-template let-item="item">
            <StackLayout>
                <Label [nsRouterLink]="['../item', item.id]" [text]="item.name + 'make it very long qqqqqqqqqqqqqqqqqqqqqqqq qqqqqqqqqqqqqqqqq'"></Label>
            </StackLayout>
        </ng-template>
    </ListView>
    </ScrollView>
</GridLayout>

**Comment by NickIliev** [comment]
@cheungcl on iOS the item templates should have some pre-defined size and you are using a StackLayout which is automatically resized. The same goes for the `ScrollView` size and the nested `ListVIew` height. Try giving them a pre-defined size so that it can be rendered properly on iOS.

Another thing is that you could make the item template horizontally scrollable instead of nesting the whole list view inside a `ScrollView`.

**Comment by cheungcl** [comment]
Thanks Nicklliev. What is the recommended pattern if I don't want to hard code the size of the listview ?

>>  make the item template horizontally scrollable  
Can you show me an example ?

**Comment by NickIliev** [comment]
@cheungcl I meant to move the scrollview inside the template (instead of being a parent of the ListView).

```HTML
<GridLayout>

    <ListView [items]="items">
        <ng-template let-item="item">
            <ScrollView orientation="horizontal">
                <GridLayout columns="*">
                    <Label col="0" class="description-label"
                        [text]="item.name + 'make it very long qqqqqqqqqqqqqqqqqqqqqqqq qqqqqqqqqqqqqqqqq'">
                    </Label>
                </GridLayout>
            </ScrollView>
        </ng-template>
    </ListView>

</GridLayout>
```

Notice that I am using `columns="*"` to create a column that spans to the whole available space.

[a Playground demo](https://play.nativescript.org/?template=play-ng&id=CHBV4Q&v=2)

**Comment by cheungcl** [comment]
Thank you Nicklliev, I would need all the list items scrolling together so this solution not suitable for my case.

I'd developed something like this:

```
<GridLayout #layout>
<ScrollView orientation="horizontal">
    <ListView [style.width]="width">
    </ListView>
</ScrollView>    
<GridLayout>

```
After View inited, get the #layout width, and set to the listview width.
