### ISSUE TITLE
Modal transitions

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#809]
It would be great to be able to apply transitions to when a modal is opening and closing. I am thinking transitions such as slide-up which would slide-down when closed.

Custom transitions would be nice too.

**Comment by hamorphis** [comment]
Here is how we do it on Android:
```
        this._dialogFragment = new DialogFragmentClass(this, fullscreen, function() {
            that.closeModal();
        });
        this._dialogFragment.show(parent.frame.android.activity.getFragmentManager(), "dialog");        
```
And here is how we do it on iOS:
```
        if (fullscreen) {
            this._ios.modalPresentationStyle = UIModalPresentationStyle.UIModalPresentationFullScreen;
        }
        else {
            this._ios.modalPresentationStyle = UIModalPresentationStyle.UIModalPresentationFormSheet;
            this._UIModalPresentationFormSheet = true;
        }

        var that = this;
        parent.ios.presentViewControllerAnimatedCompletion(this._ios, false, function completion() {
            that._raiseShownModallyEvent(parent, context, closeCallback);
        });
```

Having the above code in mind, do you have some ideas on how to implement consistent cross-platform transitions?

**Comment by hamorphis** [comment]
Resources:
 - https://groups.google.com/forum/#!topic/android-developers/0oCWqQC4Pww
 - http://stackoverflow.com/questions/6129567/is-it-possible-to-animate-a-dialogfragment
 - https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIViewController_Class/index.html#//apple_ref/occ/instm/UIViewController/presentViewController:animated:completion:

**Comment by hamorphis** [comment]
Another alternative -- do some animations when the modal page is loaded using our [Animation API](http://docs.nativescript.org/animation)

**Comment by bradmartin** [comment]
I think being able to define the animation with the {N} animation API is a solid option. Since {N} devs should be familiar with it the learning curve is lessened on creating a custom animation for a modal.

**Comment by rclai** [comment]
@hamorphis, what is your code bound to?
