### ISSUE TITLE
Navigation Bug "Frame.navigate" with transition specified

### ISSUE THREAD

**Issue by glen-stephens** [NativeScript/NativeScript#8090]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.2.0
 - Cross-platform modules:
 - Android Runtime: 6.2.0
 - iOS Runtime: 6.2.0
 - Plugin(s):

**Describe the bug**
In version 6.1 and 6.2 there is a bug that if a TextField has focus (cursor active in the field) when you navigate to a new page AND there is a transition specified in the params object, the animation occurs incorrectly and turns the page that you are leaving all white, then when going back one page in the stack, the page that was navigated from is blank.

**To Reproduce**
1.  Add a TextField to a page.
2. Tap in the text field so the cursor is in it (has focus).
3.  Add a button to the page that calls the navigate code below.
4. Navigate to a new page using the below code by tapping the button:
`let transition = {name:"slideLeft",curve: "easeIn"};
let params = {transition:transition};
Frame.topmost().navigate(params);`

The bug is present when a TextField has focus AND a transition is specified.  If the TextField does not have focus OR the transition is not defined it behaves properly.

**Additional context**
This is existing code that is in the app store that has been working all the way up to version 6 of NativeScript.

**Comment by NickIliev** [comment]
@glen-stephens I am using [this test app ](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/NativeScript/issue-8090) but I am unable to reproduce the issue. Can you take a look at the test app and let me know if the code needs to be updated. You can also post [a Playground demo ](https://play.nativescript.org/)that illustrates your case.

**Comment by NickIliev** [comment]
Possibly related to [this issue](https://github.com/NativeScript/NativeScript/issues/8094)

**Comment by glen-stephens** [comment]
@NickIliev I did more testing and found that it is an issue only when iqkeyboard is installed and referenced on the page. Thanks for the quick response and sorry for the hassle.
