### ISSUE TITLE
Allow modal to partially cover screen on iOS

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#810]
Right now the fullscreen parameter for `showModal `only works on Android. iOS does allow partial modals:

https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Alerts.html#//apple_ref/doc/uid/TP40006556-CH14-SW3

**Comment by hamorphis** [comment]
We use form-sheet modal on iOS. iPads respect that and do not show it on the entire screen, while iPhones show it on the entire screen since their screens are smaller.

```
        if (fullscreen) {
            this._ios.modalPresentationStyle = UIModalPresentationStyle.UIModalPresentationFullScreen;
        }
        else {
            this._ios.modalPresentationStyle = UIModalPresentationStyle.UIModalPresentationFormSheet;
            this._UIModalPresentationFormSheet = true;
        }

        var that = this;
        parent.ios.presentViewControllerAnimatedCompletion(this._ios, false, function completion() {
            that._raiseShownModallyEvent(parent, context, closeCallback);
        });
```

**Comment by hamorphis** [comment]
I will have to investigate whether I can override iPhone's default behavior and make it smaller than full-screen.

**Comment by enchev** [comment]
Hey @lscown,

Maybe my recently released [custom dialog module](https://www.npmjs.com/package/nativescript-dialog) can help you in your scenario.
