### ISSUE TITLE
Page navigation not working w/ flipLeft & flipRight transitions (Android)

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/NativeScript#8100]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.2
 - Cross-platform modules: 6.2
 - Android Runtime: 6.2
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
The following page navigation is not working.

It works once...you can see I'm toggling the flip - but second and subsequently - not working.

If I comment out the transition - then the navigation takes place.

```
       let page_def =
        {
            moduleName: "test-page",
            animated: true,
            clearHistory: true,
            transition:
            {
                name: bSwitch2List ? "flipRight" : "flipLeft",
                duration: 350,
                curve: "easeOut"
            }
        };

        frameModule.Frame.topmost().navigate( page_def );
```

**Comment by NickIliev** [comment]
@erjdriver confirming the issue as a bug. It is happening only when using `flipLeft` and `flipRight` as transition type.  Steps to reproduce - use [this Playground demo](https://play.nativescript.org/?template=play-tsc&id=DAsGgD&v=2) to navigate forward and backward.

As a workaround, you could use `flip` as your transition type. Here is [a Playground demo demonstrating the workaround](https://play.nativescript.org/?template=play-tsc&id=DAsGgD)

**Comment by NickIliev** [comment]
The issue is resolved [via this PR](https://github.com/NativeScript/NativeScript/pull/8306/files)
