### ISSUE TITLE
TabStripItem in iOS not taking up available spaces

### ISSUE THREAD

**Issue by cheungcl** [NativeScript/NativeScript#8101]
Nativescript 6.2

The TabStripItem in Android taking up available spaces and placed evenly.

While in iOS it looks like this:
[https://upload.cc/i1/2019/11/15/kot6sF.png](https://upload.cc/i1/2019/11/15/kot6sF.png)

Is it a bug ?  How to make the appearance same as Android ?

**Comment by NickIliev** [comment]
This is actually by design and expected as there is a conceptual difference in the native elements for iOS and Android that are standing behind TabStripItem.

**Comment by cheungcl** [comment]
Is it possible to make it look similar to Android version ?
