### ISSUE TITLE
setting selectedIndex  for Tabs Layout , highlight is incorrect in iOS

### ISSUE THREAD

**Issue by cheungcl** [NativeScript/NativeScript#8103]
Nativescript 6.2.0

In iOS, if selectedIndex is set by program, the highlight underline is remained at first tab, but the tab page is correctly set.
```
<Tabs tabsPosition="bottom" (selectedIndexChanged)="onTabIndexChange($event)"
    [selectedIndex]="tabSelectedIndex"
>
```

In the program, 
`tabSelectedIndex:number = 2;`

while the above is working correctly in Android.

The second issue is, my application saved the last active tab page and saved to storage. When my app start, it try restoring the application tab page index.  Once in a while, the application crashed at line 403 in nativescript/core/ui/tabs/tabs.ios.js :

`items[index].canBeLoaded=true;`

I have to patch it by:
```
if (items[index])
    items[index].canBeLoaded=true;

```

**Comment by cheungcl** [comment]
Forget to report the case that after the application route to a new activity and return back, the tab page highlight will be incorrectly restored to the first page.

**Comment by NickIliev** [comment]
@cheungcl thank you for reporting the issues - those were already reported [here](https://github.com/NativeScript/NativeScript/issues/7667) and linked to [the tracking issue](https://github.com/NativeScript/NativeScript/issues/6967). Closing this one as a duplicate.

**Comment by cheungcl** [comment]
How about the second issue:
The second issue is, my application saved the last active tab page and saved to storage. When my app start, it try restoring the application tab page index. Once in a while, the application crashed at line 403 in nativescript/core/ui/tabs/tabs.ios.js
