### ISSUE TITLE
How to stop tap event propagation

### ISSUE THREAD

**Issue by mannok** [NativeScript/NativeScript#8105]
**Environment**
 Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 
 * CLI: 6.2
 * Cross-platform modules: 6.2
 * Android Runtime: 6.2
 * iOS Runtime:
 * Plugin(s):
 
 **Describe the bug**
Actually this is not a bug. I have search through all the threads and issues and still no solution was found. What I want to achieve is tap event propagation capturing. I have a `StackLayout` with a `tap` event as a container. It contains a `Label` with a `tap` event as well. When user press on the `Label`, only tap event handler of the `Label` will be triggered but not the one of the `StackLayout`.

Code Provided as follow.
 
 ```
	<StackLayout width="100" height="100" (tap)="console.log('triggered only when user press outside the label but inside StackLayout')">
		<Label width="50" height="50" (tap)="console.log('triggered only when user press inside the label')">presss</Label>
	</StackLayout>

 ```

Thanks in advance.

**Comment by Pandishpan** [comment]
Follow this thread [https://github.com/NativeScript/NativeScript/issues/4883](https://github.com/NativeScript/NativeScript/issues/4883) 

You have some explanations and solutions for event propagation. I hope it helps you.

**Comment by mannok** [comment]
> Follow this thread #4883
> 
> You have some explanations and solutions for event propagation. I hope it helps you.

@Pandishpan Thank you for answering. Unfortunately the issue you refered to have not solved my problem and even that OP problem. Any other approach suggested for me?   Thank you

**Comment by mannok** [comment]
Can anyone help me out?   Thank you

**Comment by Pandishpan** [comment]
@mannok take a look on this  new video by Alexander Ziskind
https://www.youtube.com/watch?v=Fuu_Onv7buY

and this article by @NickIliev 
https://medium.com/@NativeNick/nativescript-event-bubbling-a-short-story-of-propagating-tap-f0c1ccec2752

On short, you'll have an elegant solution with isPassThroughParentEnabled property if you convert the label in a button.

**Comment by sp42** [comment]
This code is okay for me:


```ts
import { type TapGestureEventData } from "@nativescript/core";

function stopPropagation(args: TapGestureEventData): void {
  if (args.android)
    args.android.setAction(android.view.MotionEvent.ACTION_CANCEL); // Android 平台：直接消费 MotionEvent
  else if (args.ios)
    args.ios.cancelsTouchesInView = true;// iOS 平台：标记事件已处理
}
```
