### ISSUE TITLE
Issue with DataForm and Modal view

### ISSUE THREAD

**Issue by ngocnt1** [NativeScript/NativeScript#8106]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.2
 - Cross-platform modules: 
 "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
 - Android Runtime: 6.1.2
 - iOS Runtime: 6.1.1
 - Plugin(s):
    "@ngx-translate/core": "^11.0.1",
    "nativescript-angular": "~8.2.0",  
    "nativescript-geolocation": "^5.1.0",
    "nativescript-oauth2": "^1.5.3",
    "nativescript-plugin-firebase": "^10.1.0",
    "nativescript-social-share": "^1.5.2",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-ui-autocomplete": "~6.0.0",
    "nativescript-ui-calendar": "~6.0.0",
    "nativescript-ui-chart": "~7.0.0",
    "nativescript-ui-dataform": "~6.0.0",
    "nativescript-ui-gauge": "~6.0.0",
    "nativescript-ui-listview": "~8.0.1",
    "nativescript-ui-sidedrawer": "~8.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.5.0",
    "tns-core-modules": "~6.2.1",
    "zone.js": "~0.9.1"
**Describe the bug**

**To Reproduce**

XML:

```
<RadDataForm tkExampleTitle  [source]="LedgerNameField" col="0" row="0" colSpan="3"
                     class="pane">
            <TKEntityProperty tkDataFormProperty name="name"
                              displayName="&#xe905;">
                <TKPropertyEditor tkEntityPropertyEditor type="Text">
                    <TKPropertyEditorStyle tkPropertyEditorStyle labelHidden="false"
                                           strokeColor="white"
                                           labelFontName="IcoMoon-Free"></TKPropertyEditorStyle>
                </TKPropertyEditor>
            </TKEntityProperty>
        </RadDataForm>
```
TS:
```
LedgerNameField: {
        _: string
    } = {
            _: null
        };
```
Display name & TKPropertyEditorStyle does not work if i put DataForm into a modal view but it works well for normal page view.

**Expected behavior**
TKPropertyEditorStyle  should work on modal view

**Sample project**

**Additional context**

**Comment by ejlocop** [comment]
@ngocnt1 were you able to solve this? I'm having the same issue as well.

**Comment by ngocnt1** [comment]
i removed Rad form & TKPropertyEditorStyle as well, and replaced by TextField, i'm not sure if it still happens to the latest NS core 7.0+
@ejlocop
