### ISSUE TITLE
Modal view not opening properly on IOS

### ISSUE THREAD

**Issue by EnMar32** [NativeScript/NativeScript#8108]
**Environment**
Nativescript playground:
https://play.nativescript.org/?template=play-ng&id=iC2pnQ&v=143
Device: Iphone 7
Os version: IOS 13.1.3
Preview app version: 1.26.0
Runtime version: 6.2.0 

**Describe the bug**
I am trying to create a simple modal in my app, but it opens weird. It looks like it takes over the entire screen (can't see the mobile carrier or the clock on top of the screen). Then I opened the playground view (Creating a modal page), and the modal view behaviour is the same. Even if ModalDialogOptions property, fullscreen is set to false or true, the modal view opens fullscreen. I presume this is a bug.

![image](https://user-images.githubusercontent.com/57832451/68992761-6e6daa80-0878-11ea-83c2-f693ccae3545.png)

**To Reproduce**
1. Open the link in the environment section.
2. Scan the QR on your phone.
3. Click on "Open Modal"

**Expected behavior**
Modal view should be shown in front of the content.
![image](https://user-images.githubusercontent.com/57832451/68993408-952fdf00-0880-11ea-989f-b00241edd85c.png)

**Sample project**
https://play.nativescript.org/?template=play-ng&id=iC2pnQ&v=143

**Comment by tylerablake** [comment]
Hi @EnMar32,

That is the default behavior for iOS modals in iOS 13. Previously modals in iOS were full screen but now they do an "overlapping card" view.

If you'd like to read more here is a write up on the new behavior: https://medium.com/@hacknicity/view-controller-presentation-changes-in-ios-13-ac8c901ebc4e


If you need the modals to look similar on iOS and Android you might want to try a plugin that will have similar styling and behavior across platforms.

**Comment by EnMar32** [comment]
Thank you @tylerablake. This clears up my concerns.
