### ISSUE TITLE
GridLayout problem on iOS

### ISSUE THREAD

**Issue by cheungcl** [NativeScript/NativeScript#8110]
Nativescript 6.2

I need two components in a gridlayout, with the first row occupy remain spaces, the second row is a fixed size (or various size) label.

```
<GridLayout rows="*,auto" columns="*">
    <ListView [items]="items" row="0" col="0">
        <ng-template let-item="item">
            <StackLayout>
                <Label [nsRouterLink]="['../item', item.id]" [text]="item.name"></Label>
            </StackLayout>
        </ng-template>
    </ListView>
    <StackLayout row="1" col="0" orientation="horizontal">
        <Label text="label1" style="height:40"></Label>
        <Label text="label2"></Label>
    </StackLayout>
</GridLayout>
```

on Android, works perfectly.
on iOS, becomes:
https://upload.cc/i1/2019/11/17/uqTzpt.png
the listview take up all the spaces. The second row disappeared.

===
If listview is in second row, everything works fine:

```
<GridLayout rows="auto,*" columns="*">
    <ListView [items]="items" row="1" col="0">
        <ng-template let-item="item">
            <StackLayout>
                <Label [nsRouterLink]="['../item', item.id]" [text]="item.name"></Label>
            </StackLayout>
        </ng-template>
    </ListView>
    <StackLayout row="0" col="0" orientation="horizontal">
        <Label text="label1" style="height:40"></Label>
        <Label text="label2"></Label>
    </StackLayout>
</GridLayout>
```
https://upload.cc/i1/2019/11/17/7qWCrI.png

**Comment by tsonevn** [comment]
Hi @cheungcl,
I tested your case on my side while reusing the provided code fragments. However, I was unable to recreate such a problem. For your convenience, I am attaching screenshots, that shows the behaviour on my side(tested on iPhone 8 and iPhone Xr simulator with iOS 13).
Snippet 1:
![Screenshot 2019-11-18 at 7 51 15](https://user-images.githubusercontent.com/17448734/69027820-cfac8f80-09d8-11ea-82e6-50bb59160f0e.png)

Snippet 2:
![Screenshot 2019-11-18 at 7 50 17](https://user-images.githubusercontent.com/17448734/69027847-e357f600-09d8-11ea-9e4e-fa6e57c8f92c.png)

On that matter, it will help if you provide some more info about the device or simulator that you are using for testing. Meanwhile, you can try replacing the `StackLayot` with `GridLayout` and check if there will be any difference.

**Comment by cheungcl** [comment]
I just create a hello world example and apply my code, yes, it is working,

My application and example is in Tabs layout, I think it can be only reproduced with a Tabs layout.
I tried it in both https://appetize.io and Xcode simulator.

**Comment by tsonevn** [comment]
@cheungcl I tested the application case with the NativeScript Angular Tabs template, however, I am still unable to recreate the issue. Here is the result on my side:
![Screenshot 2019-11-18 at 10 07 01](https://user-images.githubusercontent.com/17448734/69035005-39ce3000-09eb-11ea-8862-9fec2a3bbb70.png)

As a reference, I am attaching my test app. Please review it and make the needed changes, that will allow me to reproduce the problem.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/3857414/Archive.zip)

**Comment by cheungcl** [comment]
Yes, you are right. It is not the problem of Tabs + GridLayout.
I had misunderstood that <BottomNavigation> is the same as <Tabs tabsPosition="bottom">
and made a change to app.component.html

I changed it back to <BottomNavigation> and everything works fine.
Thanks a lot.

**Comment by tsonevn** [comment]
Hi @cheungcl,
I think that we can close this issue for now. We can reopen it when we have a sample app that shows that this is a bug in the `tns-core-modules`.
