### ISSUE TITLE
[Feature request] Ability to set Height for the TabStrip

### ISSUE THREAD

**Issue by DanielRitvas** [NativeScript/NativeScript#8118]
How can I change height of `TabStrip` in `ButtomNavigation` on iOS? Straightforward set of `height` doesn't seem to work.

**Comment by tsonevn** [comment]
HI @DanielRitvas,
This is a new feature for the `Tabs` and `BottomNavigations` component. Currently, for those components, we haven't added any specific functionality that enables setting the height for the `TabStrip`. However, for android, it seems that it is working out of the box. On that matter, I will mark this one as a feature request. For now, I would suggest keeping track on the issue for further info.

**Comment by DanielRitvas** [comment]
@tsonevn hi, thanks for your response, looking forward to seeing this feature. I tried to get reference of UITabBarController to change height. Bottom-navigation docs states that `ios` property should return the reference, but it's not (returns undefined in fact). Any ideas how could I get the reference?

**Comment by tsonevn** [comment]
HI @DanielRitvas,
Make sure that, you are getting the native instance on `BottomNavigation` loaded event. For example:
```XML
<BottomNavigation selectedIndex="1" loaded="bottomnavLoaded">
.......
</BottomNavigation>
```
```JavaScript
function bottomnavLoaded(args){
    let bottom = args.object;
    let controller  = bottom.ios;
}

exports.bottomnavLoaded = bottomnavLoaded;
```

**Comment by tsonevn** [comment]
Hi @DanielRitvas,
Regarding your case, you can also consider creating a custom `TabView` component. For further help, you can check the below-attached articles.  
https://nativescripting.com/posts/cradle-tab-bar-animation-in-nativescript
https://nativescripting.com/posts/sliding-colors-tab-bar-animation-in-nativescript

**Comment by dosomder** [comment]
Bump

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
