### ISSUE TITLE
Use of external libraries with Nativescript

### ISSUE THREAD

**Issue by prijindal** [NativeScript/NativeScript#812]
Right now there is no end point for using any kind of external libraries.
For exampe use of MaterialDesignLibrary (https://github.com/navasmdc/MaterialDesignLibrary).

there are a lot of libraries available out there and it will be a great feature to include its usage in nativescript

**Comment by enchev** [comment]
Please check this article to know more how to use external libraries as plugins:
http://docs.nativescript.org/plugins

**Comment by dtopuzov** [comment]
{N} 1.3+ also supports CocoaPods:
https://github.com/NativeScript/nativescript-cli/blob/master/CocoaPods.md

**Comment by manijak** [comment]
Would be nice to have a full tutorial on how to use CocoaPods in 1.3. Especially for those who have no background in iOS development. 

From what I could understand. You need to create a new project in order to create a {N} plugin that wraps the coca library? But then what? How do we use it in an exsisting app project?

**Comment by anshulguleria** [comment]
+1 @manijak It would also be nice to have full code tutorial(sample app) for including android library also.

**Comment by prijindal** [comment]
+1 @anshulguleria There should be some tutorials for using external libraries

**Comment by valentinstoychev** [comment]
Please check this post about how to use cocoapods  - https://www.nativescript.org/blog/using-cocoapods-is-a-piece-of-cake-with-nativescript-1.3.0

**Comment by enchev** [comment]
Hi folks,

Please check also these article for Android:
http://docs.nativescript.org/runtimes/android/external-libs/jars
http://docs.nativescript.org/runtimes/android/external-libs/resource-libs

**Comment by lasuax** [comment]
Links are not working any more. I'm trying to import Wowza SDK for NativeScript but I couldn't find how to import the files after compiling with gradle.

**Comment by meSmashsta** [comment]
It's been 2018 and still no answer

**Comment by NickIliev** [comment]
@meSmashsta you could create a plugin to use an external Android library ('aar' or 'jar') - details about the plugin structure [here](https://docs.nativescript.org/plugins/Android-Plugins-Infrastructure).
