### ISSUE TITLE
nativescript-vue 我喜欢nativescript-vue 

### ISSUE THREAD

**Issue by djroad** [NativeScript/NativeScript#8122]
**Is your feature request related to a problem? Please describe.**
                       NO

**Describe the solution you'd like**
       1).希望, nativescript-vue, 可以支持安卓4.4版 
       2).希望, nativescript-vue,可以支持调用通讯录
       3).希望, nativescript-vue UI,可以和 Vux UI 一样 ( Url: "https://doc.vux.li/zh- 
                  CN/components/cell.html"    )
       4).希望, nativescript-vue UI 可以和 Element UI 一样( Url: "https://element.eleme.io/#/en-US"    )
       

**Describe alternatives you've considered**
     考虑过   DCloud - HBuilder ( Url: "https://uniapp.dcloud.io/component/view"    )  

**Additional context**
     Byte beat 公司

**Comment by tsonevn** [comment]
HI @djroad,
Thank you for contacting us.
For {N} vue related problem, please use https://github.com/nativescript-vue/nativescript-vue/issues repository. It will also help if you can describe the problem you are facing in English.

Thanks,
@tsonevn

**Comment by djroad** [comment]
let  希望=  hope
      一样 = same 
      考虑过 = Considered
