### ISSUE TITLE
Animating css border-color causes exception or build error (Android?)

### ISSUE THREAD

**Issue by tomcatmwi** [NativeScript/NativeScript#8133]
**Environment**
 - CLI: 6.1.2
 - Cross-platform modules: N/A
 - Android Runtime: 29
 - iOS Runtime: N/A
 - Plugin(s): N/A

**Describe the bug**
An attempt to use CSS animation on `border-color` seems to crash the build or throw the following exception:

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method run failed
System.err: Error: No known animation properties specified
```

I've not tried it on iOS, only Android. The error occurs on Android 9 on a Google Pixel 2 XL and emulators.

**To Reproduce**
CSS:

```
@keyframes example {
    from { border-color: red; }
    to { border-color: green; }
}

.view {
    animation-name: example;
    animation-duration: 4s;
    animation-fill-mode: forwards;
    border-width: 5;
    padding: 5;
    background-color: white;
}
```

Template:
```
<Label text="CSS test" class="view"></Label>
```

The result is either a plain black border around the label or the app won't even build. However if I change `border-color` to `background-color`, it works perfectly.

**Expected behavior**
The border color should animate or at least not throw an exception.

**Comment by NickIliev** [comment]
@tomcatmwi indeed the `border-color` is not supporting CSS animations - [here is the list of properties ](https://docs.nativescript.org/ui/animation-css#animatable-properties)that are supported by declarative animations in NativeScript.
