### ISSUE TITLE
viewContainerRef createComponent does not work in Modal views [Angular]

### ISSUE THREAD

**Issue by jalbatross** [NativeScript/NativeScript#8137]
Playground URL: 
https://play.nativescript.org/?template=play-ng&id=iC2pnQ&v=155

**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.2.0
 - Cross-platform modules:
 - Android Runtime: Android10
 - iOS Runtime: iOS13
 - NativeScript-Angular: yes
 
**Describe the bug**
For regular components, using viewContainerRef.createComponent renders a component over the current component. When this is used in the views loaded modally, nothing happens.

**To Reproduce**
See the playground link. When the create component button is tapped on the HomeComponent, the view is changed to render the TestComponent. When the create component button is tapped in the modal view, nothing happens.

**Expected behavior**
When I tap the create component button in the modal view, it should render the TestComponent in the modal view.

**Sample project**
https://play.nativescript.org/?template=play-ng&id=iC2pnQ&v=155

**Comment by NickIliev** [comment]
Closing as duplicate to https://github.com/NativeScript/nativescript-angular/issues/2089
