### ISSUE TITLE
Webpack does not support GIF files as standard.

### ISSUE THREAD

**Issue by mrwrighty** [NativeScript/NativeScript#8142]
Why hasn't Webpack been updated to include GIF files as standard. Required to edit the web pack.config.js file and add { from: { glob: "**/*.gif" } }, to get GIF's included with app.

**Comment by NickIliev** [comment]
@mrwrighty GIF is not a commonly used standard in the context of mobile development. The mobile APIs are having more or less limited supported for things like animated GIFs and are recommending using PNG files. This is just a difference with web development where there are no such rules and everyone is using whatever the browser is supporting.
