### ISSUE TITLE
Webview stopLoading() does not work on android

### ISSUE THREAD

**Issue by 7ammer** [NativeScript/NativeScript#8145]
**Environment**
*Note this is my environment but obviously the playground will be different :)*
nativescript:  6.1.0
tns-core-modules: 6.1.2
tns-android: 6.0.0
device: Oneplus 6

**Describe the bug**
Please see sample project.
When I click on a link in a webview in android `stopLoading()` does not do anything.

**Expected behavior**
I would expect `stopLoading()` to work the same as iOS where it prevents the webview from loading the new url.

**Sample project**
https://play.nativescript.org/?template=play-vue&id=QFn1uy&v=1

Thanks for your time

**Comment by NickIliev** [comment]
@7ammer actually the method works - it's just that you are using utils.openUrl to explicitly open the address from **args.url** parameter.

See[ this playground ](https://play.nativescript.org/?template=play-vue&id=QFn1uy&v=2)as a demo that **_stopLoading_** is indeed preventing the content to load.

**Comment by 7ammer** [comment]
Hi @NickIliev,

The idea I was hoping to achieve is to prevent the WebView from loading the new url completely and instead open the link in an external browser using `utils.openUrl` or https://www.npmjs.com/package/nativescript-advanced-webview.

**Comment by 7ammer** [comment]
If anyone is stuck on this I resorted to using: https://www.npmjs.com/package/nativescript-webview-interface, set event.preventDefault() to run on click in the webview and then sent a message to nativescript-webview-interface to handle `utils.openUrl`.

I've recently discovered this repo `https://www.npmjs.com/package/@nota/nativescript-webview-ext` which might be a good alternative as it exposes this event which looks useful: `shouldOverrideUrlLoading`.

**Comment by Zefling** [comment]
`shouldOverrideUrlLoading` is not good for me. Specifically for links like mailto: tel: sms: etc.
It is possible to overload the method:

```typescript
webView.nativeView.client.shouldOverrideUrlLoading =
    (view: android.webkit.WebView, data: String | android.webkit.WebResourceRequest) => {
        let url = '';
        if (typeof data === 'string') {
            url = data.toString();
        } else {
            // Added in API level 24
            url = (<android.webkit.WebResourceRequest>data).getUrl().toString();
        }
        // override if the url not start with http:, https: or file:
        const shouldOverrideUrlLoading = !url.match(/^(https?|file):.*/);
        if (shouldOverrideUrlLoading) {
            // call this URL outside de webview
            this.androidService.contentIntent(url);
        }
        return shouldOverrideUrlLoading;
    };
```

Android documentation : https://developer.android.com/reference/android/webkit/WebViewClient#shouldOverrideUrlLoading(android.webkit.WebView,%20android.webkit.WebResourceRequest)
