### ISSUE TITLE
[Question] How to specify which emulator run on iOS?

### ISSUE THREAD

**Issue by ebellumat** [NativeScript/NativeScript#8147]
In React Native we have this command to specify emulator model to run, for example:

```react-native run-ios --simulator='iPhone 8'```

In Native Script we have ```tns run ios --emulator``` but no option to choose which emulator.

This option exists or no? Please help.

**Comment by DimitarTachev** [comment]
@ebellumat 

For running simulator:
1) `tns devices`
2) Copy the `Device Identifier`
3) `tns run ios --device {deviceId}`

For not running simulators:
1) `tns devices --available-devices`
2) Copy the `Device Identifier`
3) `tns run ios --device {deviceId}`

Feel free to open another issue if you have additional issues or questions.
