### ISSUE TITLE
Vue.js HTML view working in IOS Device

### ISSUE THREAD

**Issue by sbhol2008** [NativeScript/NativeScript#8152]
Hi,
Trying to show the editor data in IOS app the data is coming. But not in formated I have added in the back end. 
For getting the data I am using vue.js
Also, I am trying to write the CSS for the HTML view and that is not working.

Please help!

Thanks

**Comment by NickIliev** [comment]
@sbhol2008 please consider reposting the issue in [the nativescript-vue repository](https://github.com/nativescript-vue/nativescript-vue/issues). and providing enough information for reproduction (e.g. [ a  Playground demo](https://play.nativescript.org/))  

Closing the issue as it is related to Vue project
