### ISSUE TITLE
Null reference exception in view.android.onUnloaded

### ISSUE THREAD

**Issue by hamidbsd** [NativeScript/NativeScript#8153]
https://github.com/NativeScript/NativeScript/blob/3199a392b45635606e06119845099965246395c3/nativescript-core/ui/core/view/view.android.ts#L381-L386

`this.nativeViewProtected.setOnTouchListener(null);` would throw if `nativeViewProtected` is null.
`this.nativeViewProtected.setClickable(this._isClickable);` would throw if `nativeViewProtected` is null.

**Comment by NickIliev** [comment]
@hamidbsd  Are you using a specific component/layout or something from the core modules? Please consider creating a demo project or [Playground ](https://play.nativescript.org/)that demonstrates your scenario.

**Comment by hamidbsd** [comment]
@NickIliev I am using nativescript-material-bottomsheet plugin and this is where @farfromrefug thinks the bug is.
Please see this: https://github.com/NativeScript/NativeScript/issues/8038
I happens when there are active button(s) on the bottomsheet and it is is dismissed.
Simple project to reproduce:
https://www.dropbox.com/s/m1weedpegpo0rlv/Bottomsheet%20crashing.zip?dl=0

**Comment by NickIliev** [comment]
@hamidbsd I saw the discussion that you had with @farfromrefug and it sounds legit. Marking the issue with `good-first-issue` as the fix sounds like a one-liner (adding a null check).
