### ISSUE TITLE
Navigation between parent and child frames

### ISSUE THREAD

**Issue by bornes** [NativeScript/NativeScript#8156]
Reproduction link
https://play.nativescript.org/?template=play-tsc&id=x1CC7e&v=17

Platform and OS info
Nativescript 6.2.0

Steps to reproduce
Navigate from first page to the end of the pages
Come back to the first page

What is expected?
A nice and clean navigation

What is actually happening?
The content flash for a brief moment when navigating the menu frame. 

So, when we come back to the first page and navigate, again, to the next ones, we can see that the last screen of the child frame (page3) is always in the background. 

I don't know if this is a bug or some kind of bad navigation design.

**Comment by NickIliev** [comment]
@bornes I've updated the Playground to use the `Frame.getFrameById` and the 1-2 navigation is no longer showing the 3rd page underneath. See the modified demo [here](https://play.nativescript.org/?template=play-tsc&id=x1CC7e&v=18).

**Comment by bornes** [comment]
@NickIliev thanks for your example. I tested it on the most recent version and all works fine!
Thanks
