### ISSUE TITLE
Does nativescript support android instant apps?

### ISSUE THREAD

**Issue by amobarak** [NativeScript/NativeScript#8159]
Does it support android instant apps?

**Comment by NickIliev** [comment]
Hello @amobarak 
The short answer is no - NativeScript is not supporting instant apps. 

The thing is that one of the requirements for an instant app is the smaller app size. NativeScript us using VMs to create a native app from JS code (or Angular, Vue, etc.,). That said the app size of the NativeScript created an app is a bit larger. There are also other limitations but this is one of the crucial ones.
