### ISSUE TITLE
Keyboard overlapping TextField in modal when using ScrollView and fullscreen mode

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/NativeScript#8169]
**Environment**
 - CLI: 6.1
 - Cross-platform modules: 6.1.2
 - Android Runtime: 6.1.2

**Describe the bug**
I have a layout that contains `ScrollView`   and some `TextFields` and works fine in all pages. But when I use the same layout in a modal page (using nativescript-angular) it doesn't work fine, which means the Keyboard overlapping TextField (TextField will be under the keyboard If I use the layout into the modal page). Then if I remove `ScrollView` it works fine. But without `ScrollView` I can't scroll to other elements.

Note: If I set the `fullscreen` to false in the modal page, it works fine.

**To Reproduce**
First, download the sidedrawer template in an angular project. Then create a modal page. And check this layout:

```
<ScrollView>

    <StackLayout>
        <TextField verticalAlignment="center" hint="09121234567" autocorrect="false" class="saz-input login-input"></TextField>
        <TextField verticalAlignment="center" hint="09121234567" autocorrect="false" class="saz-input login-input"></TextField>
        <TextField verticalAlignment="center" hint="09121234567" autocorrect="false" class="saz-input login-input"></TextField>
        <TextField verticalAlignment="center" hint="09121234567" autocorrect="false" class="saz-input login-input"></TextField>
        <TextField verticalAlignment="center" hint="09121234567" autocorrect="false" class="saz-input login-input"></TextField>
        <TextField verticalAlignment="center" hint="09121234567" autocorrect="false" class="saz-input login-input"></TextField>
        <Button class="saz-btn login-button" (tap)="login()" text="Login"></Button>
    </StackLayout>
</ScrollView>
```

**Expected behavior**
Not overlapping the keyboard

**Additional context**
The issue was even in main pages. Then as mentioned [here ](https://discourse.nativescript.org/t/keyboard-overlapping-textview/3213/13)I added the following to the AndroidManifest.xml in `activity` tag:

```
android:windowSoftInputMode="adjustPan"
```

**Comment by NickIliev** [comment]
@vahidvdn try making the `StackLayout` to span for 100% of the height. If that is not working than please provide a testable [Playground](https://play.nativescript.org/).

**Comment by vahidvdn** [comment]
Hi @NickIliev 
I tried adding `height="100%"` to the `StackLayout` but it didn't work. I will make a demo in playground asap.

**Comment by vahidvdn** [comment]
@NickIliev 
I couldn't be able to reproduce the issue in Playground. For now, I'm going to close this issue. If I have time, I try to create a repo for a demonstration and reopen it.
