### ISSUE TITLE
Wrong ActionBar position in modal

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/NativeScript#8179]
**Environment**

 - CLI: 6.1
 - Cross-platform modules: 6.1.2
 - Android Runtime: 6.1.2

**Describe the bug**
When I use `ActionBar` within the modal page, it doesn't show the ActionBar in the modal, but instead, it shows the ActionBar on the page itself.

**To Reproduce**
Create a modal in the nativescript-angular template. Then put the ActionBar within the modal. (See Playground link)

**Expected behavior**
Show ActionBar within the modal.

**Sample project**
https://play.nativescript.org/?template=play-ng&id=MGCa54

**Comment by NickIliev** [comment]
@vahidvdn create a modal with PRO (page-router-outlet) so that your modal has Page instances and can have their own action bars - use [this article and the example from the snippets](https://docs.nativescript.org/angular/core-concepts/angular-navigation#modal-view-navigation).
