### ISSUE TITLE
How to play hls videos in a nativescript project?

### ISSUE THREAD

**Issue by aranmohyeddin** [NativeScript/NativeScript#8180]
Is it possible to play hls links with adaptive streaming in a nativescript app?
I don't even need any video controls. I just need to be informed when the video is done. I saw some people with similar problems abandoning nativescript and using react native because the couldn't make it work. eg, [this SO question](https://stackoverflow.com/a/31390956/5120089) I really would prefer to stick with nativescript. How can I play an hls link in my nativescript app and be informed when the video ends? I'm using nativescript-vue by the way.

**Comment by NickIliev** [comment]
@aranmohyeddin you could try the exoplayer plugin (not sure if the NativeScript implementation is supporting **_hls_** videos). Or create your own plugin while using a native library.

Closing as how-to related.

**Comment by ralyodio** [comment]
@rnmhdn did you ever find a way?

**Comment by triniwiz** [comment]
@ralyodio iirc the exoplayer should work
