### ISSUE TITLE
How to think about the fact that H5 released by Apple store is not allowed to be put on the market, does it have an impact on native script?

### ISSUE THREAD

**Issue by djroad** [NativeScript/NativeScript#8187]
**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**
How to think about the fact that H5 released by Apple store is not allowed to be put on the market, does it have an impact on native script?

**Comment by NathanaelA** [comment]
Not part of the team, but what exactly is "H5"  -- I tried googling for it and couldn't seem to find anything relevant.
