### ISSUE TITLE
After migration to Nativescript 6, REST calls aren't made in release mode

### ISSUE THREAD

**Issue by gsarme** [NativeScript/NativeScript#8188]
I created the app with Nativescritp + Angular but when I try to make a REST call it does nothing.
I already create a [question on StackOverflow](https://stackoverflow.com/questions/59263998/after-tns-buid-android-release-app-doesnt-make-rest-calls) but no one aswered. 

The code of the release versione is the same of the development version.

Runnign `tns info` I get:

> √ Getting NativeScript components versions information...
> √ Component nativescript has 6.2.2 version and is up to date.
> √ Component tns-core-modules has 6.2.3 version and is up to date.
> ‼ Update available for component tns-android. Your current version is 6.0.0 and the latest available version is 6.2.0.
> ‼ Update available for component tns-ios. Your current version is 6.0.1 and the latest available version is 6.2.0.

Here is my package.json
```JSON
{
  "nativescript": {
    "id": "com.xxx.xxx",
    "tns-ios": {
      "version": "6.0.1"
    },
    "tns-android": {
      "version": "6.0.0"
    }
  },
  "description": "xxx Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "8.0.0",
    "@angular/common": "8.0.0",
    "@angular/compiler": "8.0.0",
    "@angular/core": "8.0.0",
    "@angular/forms": "8.0.0",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "8.0.0",
    "@angular/platform-browser-dynamic": "8.0.0",
    "@angular/router": "8.0.0",
    "nativescript-angular": "8.0.2",
    "nativescript-background-http": "^3.4.0",
    "nativescript-camera": "^4.4.0",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-drop-down": "^5.0.0",
    "nativescript-fancyalert": "^3.0.6",
    "nativescript-fontawesome": "^1.0.0",
    "nativescript-fonticon": "^2.0.0",
    "nativescript-imagepicker": "^6.2.0",
    "nativescript-localstorage": "^2.0.0",
    "nativescript-modal-datetimepicker": "^1.2.0",
    "nativescript-ng-ripple": "^2.0.1",
    "nativescript-ngx-fonticon": "^4.2.1",
    "nativescript-pulltorefresh": "^2.2.2",
    "nativescript-ripple": "^2.2.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-chart": "5.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.0.0",
    "tns-core-modules": "~6.2.0",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "8.0.0",
    "@nativescript/schematics": "~0.5.0",
    "@ngtools/webpack": "8.0.0",
    "nativescript-dev-webpack": "^1.3.0",
    "tns-platform-declarations": "6.0.1",
    "typescript": "3.4.5"
  },
  "gitHead": "f548ec926e75201ab1b7c4a3a7ceefe7a4db15af",
  "readme": "NativeScript Application"
}
```

***login.component.ts***

```JavaScript
public login() {
      if(!this.user.email || !this.user.password){
        let options = {
            title: 'ATTENZIONE!',
            message: 'Inserire tutte le credenziali',
            okButtonText: 'OK'
        };

        alert(options);            //first
      } else {
         alert("HELLO WORLD!");    //second
         this.userService.login(this.user).subscribe((res) => {
           alert(res);             //third
           localStorage.setItem("authenticated", true);
           localStorage.setItem("access_token", "bearer " + res.access_token);
           localStorage.setItem("username", this.user.email);
         },
         (err)=>{
           console.log("Something went wrong "+err);
           alert("Credenziali errate");
           return;
         }
         );
       }
      return;
    }
```

***login.service.ts***

```JavaScript
login(user: User) {
      let urlSearchParams = new URLSearchParams();

      urlSearchParams.append('username', user.email);
      urlSearchParams.append('password', user.password);
      urlSearchParams.append('grant_type','password');

      let body = urlSearchParams.toString();

      var url = Config.apiUrl + "/token";
      
     alert(url);
     
      return this.http.post(url, body , { headers : this.getCommonHeaders() })
      .map(res => res.json())
      .catch( (error: any) => {Observable.throw(error.json().error)} );
}
```

The problem is that the http.post doesn't work. The alert right before that return is raised, so the execution arrives at that point but if I put an alert inside the .map like this `.map(res => {alert res.json(); return res.json()})` is never raised. So the http.post doesn't work. The http variable is Http from `@angular/http` and map is from `rxjs/operators` 

I read that `@angular/http` is deprecated, could it be the problem?

I think the problem is with the `rxjs package` but I don't know how to resolve.
Any idea?

**Comment by NickIliev** [comment]
@gsarme is the same code working in development? In any case, consider providing a demo project which can be used for investigation. Here is what you need to provide when logging a bug report issue:

**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**


**To Reproduce**


**Expected behavior**

**Sample project**


**Additional context**

**Comment by gsarme** [comment]
@NickIliev I update the issue with more info.

**Comment by NickIliev** [comment]
> I read that `@angular/http` is deprecated, could it be the problem?

Most likely - use the NativeScriptHttpModule along with the `@angular/common/http` as shown [here](https://docs.nativescript.org/angular/ng-framework-modules/http)

**Comment by gsarme** [comment]
But why in development mode works and in release mode doesn't?

**Comment by NickIliev** [comment]
@gsarme 

> But why in development mode works and in release mode doesn't?

I can't really say without having a real-life demo that reproduces the issue. For example, it is not clear what is the IP address (secure-,non-secure - do you need any additional permission to open a non-secure IP). It is not clear if your HTTP request is triggered at all or returning any kind of error message (timeout? bad connection?). In any case, I would strongly recommend updating the codebase so your services are no longer using the deprecated API.

**Comment by gsarme** [comment]
@NickIliev the IP address is secure (my API are at https://...). 
The http request gives nothing.

Now I'm migrating the code to NativeScriptHttpModule like you said and seems that is working.

Thank for the help!
