### ISSUE TITLE
ios app  when back zoom out home the app icon change between nativescript default icon and my icon.why?

### ISSUE THREAD

**Issue by gxsjtu** [NativeScript/NativeScript#8195]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.2.2
 - iOS Runtime: 13

**Describe the bug**
  build and install ios app on real device,  when click iphone home button back zoom out home the app icon change between nativescript default icon and my icon. why?

**Comment by NickIliev** [comment]
@gxsjtu you probably need to change & provide all icons needed in `App_Resources` - check that you are not missing a specific resolution/type.

Closing as no test app/codebase is provided to continue the investigation.
