### ISSUE TITLE
Button tap not working when using Button element inside StackLayout  

### ISSUE THREAD

**Issue by satyam-dev** [NativeScript/NativeScript#8199]
**Environment**
 - nativescript : `5.4.0`
 - tns-core-modules : `5.4.2`
 -  tns-android : `5.4.0`
 -  tns-ios : `5.4.2` 

**Bug**
 When using `Button` inside `StackLayout` for iOS build, the button's `tap` event is not working. 
 Example - 
```
<StackLayout>
      <Button
        text="Some button"
        (tap)="onTap()"
      ></Button>
    </StackLayout>
```

**Comment by NickIliev** [comment]
@satyam-dev [this PLaygrond demo](https://play.nativescript.org/?template=play-ng&id=1L7KcX) is working as expected - check your code and if the issue still exists then modify the demo so it can reproduce your case.
