### ISSUE TITLE
The x and y components of an Android translate or scale animation are not animated together when delay is specified.

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/NativeScript#820]
Suppose I want to make an image huge with the following animation:

```js
imageReference.animate({
    scale: { x: 5, y: 5 },
    duration: 1000,
    delay: 1000
});
```

This works on iOS, but on Android the x and y scaling happen independently (see gif below). If I remove the `delay` the problem goes away.

![android-bug](https://cloud.githubusercontent.com/assets/544280/10076755/0da57a88-62ab-11e5-94e0-5305cbda91b2.gif)

**Comment by shripal04** [comment]
I am also facing the same issue in android, the width is getting scaled first and then height is getting scaled when delay is used in animation.
