### ISSUE TITLE
File.read fails on Android 10

### ISSUE THREAD

**Issue by xuhcc** [NativeScript/NativeScript#8203]
**Environment**

Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.2.1
 - Cross-platform modules: 6.2.1
 - Android Runtime: 6.2.0
 - iOS Runtime: N/A
 - Plugin(s): nativescript-imagepicker

**Describe the bug**

```js
const file = File.fromPath(path);
const data = file.readSync((error) => {
    console.log(error);
});
```

This code worked on Android 9, but on Android 10 it fails with the following error:

```
JS: Error: java.io.FileNotFoundException: /storage/emulated/0/Download/myfile: open failed: EACCES (Permission denied)
```

**Additional context**

It seems that a very similar problem described here: 

https://github.com/NativeScript/nativescript-imagepicker/issues/309

The solution mentioned in the thread (adding `android:requestLegacyExternalStorage="true"` to manifest file) worked for me too.

**Comment by NickIliev** [comment]
Marking the issue as feature request to support `MediaStore`. As a workaround, at this very moment, the devs should use the legacy storage on Android 10 by setting the key shown above in their `AndroidManifest.xml`.

**Comment by vytautas-pranskunas-** [comment]
Watching

**Comment by sublime392** [comment]
It looks like the requestLegacyExternalStorage option is going away on May 5th: We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of 1 or more of your app bundles or APKs.

Developers with apps on devices running Android 11+ must use Scoped Storage to give users better access control over their device storage.
