### ISSUE TITLE
missing device language fails to open android app

### ISSUE THREAD

**Issue by jokro** [NativeScript/NativeScript#8210]
I have an app for the blind with English spoken system messages. This app does not open on Italian phones with Italian as the current device language. When in the phone's settings English is set as a second language, then the app does open. I know how to get the current device language, but not how to get the second set language. Is there a way to know in advance if English is set as a (second) device language ? I do not want to change the device language itself, as this is used for STT purposes. Or possibly to set the second language programmatically?

**Comment by NickIliev** [comment]
@jokro does your app have localization files (does it have translations to other languages?).

NOt sure what you mean by `how to get the second set language` -can you elaborate more on the second language part?
