### ISSUE TITLE
Not working after upgrading to last MAC OS - Catalina

### ISSUE THREAD

**Issue by vforv** [NativeScript/NativeScript#8215]
After I upgraded to last MAC sistem I get this error when try to run ios with comand

>  tns debug ios --bundle --provision 4a6905a8-b946 --no-hmr

> Command failed: ruby -e "require 'xcodeproj'; Xcodeproj::Config.new('mobile/platforms/ios/plugins-debug.xcconfig').merge(Xcodeproj::Config.new('mobile/node_modules/nativescript-ng-ripple/platforms/ios/build.xcconfig')).save_as(Pathname.new('mobile/platforms/ios/plugins-debug.xcconfig'))"
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- xcodeproj (LoadError)
>         from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
>         from -e:1:in `<main>'

Anyone know what is an issue?

**Comment by fibric** [comment]
In the [docs](https://docs.nativescript.org/angular/start/ns-setup-os-x) it's written to install `xcodeproj` via `sudo gem install xcodeproj`.

I installed `ruby` via `brew` and put `ruby` in my `path` variable to omit to install anything with `sudo`.
