### ISSUE TITLE
Error receiving broadCast Intent on Android in connectivity module

### ISSUE THREAD

**Issue by tdhman** [NativeScript/NativeScript#8223]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.3.0
 - Cross-platform modules:
 - Android Runtime: 6.1.2
 - iOS Runtime: 6.1.1
 - Plugin(s): None

**Describe the bug**
When using the connectivity module in my application on android, if the application is running on background, everything is working ok. But if I put the device on sleep (device locked after inactivity) while the application is still open, then when I unlock the device, my application is crashed due to error with the connectivity module:

```
Android Runtime: java.lang.RuntimeException: Error 
receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010   
(has extras) } in com.tns.gen.android.content.BroadcastReceiver_vender_...
```

**To Reproduce**
- Create an Android application with Nativescript
- Import the connectivity module, then use the startMonitoring() function
- Run the application on android device
- While the application is open, lock the device
- Wait some time then unlock the device --> app crashed

**Expected behavior**
- Application is not crashed

**Comment by NickIliev** [comment]
@tdhman add the `<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>` in your **_AndroidManifest.xml_** and retry the above case -the permissions resolved the issue on my side.

**Comment by tdhman** [comment]
@NickIliev I have already set that permission in the manifest file but still got this error.

**Comment by NickIliev** [comment]
@tdhman can you share a demo app [or modify this one](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/NativeScript/issue-8223) so it could reproduce the issue. I am testing on API28 w/Samsun s9 and on APi21 (emulator) but I am unable to reproduce the issue when the permission is present.
