### ISSUE TITLE
Incompatibility between topmost and BottomNavigation

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#8227]
Hi,

I use `BottomNavigation` as a root .. I have reported several issues with the BottomNavigation concept.

I have a frame on each `Tabs` and for navigation no problem since I can use `const view: View = agrs.object as View` then `const frame: Frame = view.page.frame as Frame` to get the current frame.

The problem is too many plugins use the `topmost()` concept to get the current frame, I had more then issue with `nativescript-barcodescanner` and `nativescript-toasty` that use `topmost()` to get the view especially on `IOS` .. but if I navigate to page other tabs, the topmost will change and if you goback to the pervious page that you have a Qr-code scanner it will not appear because the last frame is not the same one !

I have create a [sample](https://play.nativescript.org/?template=play-tsc&id=PpozvL) here to better explanation .. I have installed both plugin but unfortunately there is problem with Playground .. the app crash with `Can't find variable...` and this related with those plugins.

For `nativescript-toasty` I swith to `Frame.topmost()` but this dose not resolve the issue .. to work correctly I had edited the source code to : `Frame.topmost().page.frame` and for barcodescanner I think I must do same think but is not a solutions...

Hop that I misunderstand some think about the navigation concept and there is a solution.

**Comment by NickIliev** [comment]
@kefahB  in the provided Playground the `BottomNavigaiton` is not placed as root (**app-root.xml**) - can you clarify more on the example.

**Comment by kefahB** [comment]
@NickIliev I placed It as a root and the result is same think !

**Comment by NickIliev** [comment]
@kefahB it looks like an issue with the plugin's codebase - for example, there are at least [two different issues opened in nativescript-toasty](https://github.com/triniwiz/nativescript-toasty/issues) related to the topmost usage (including using a deprecated method).

Still not sure what your exact issue is - I've recreated the Playground with BottomNavigaitonas root and the toast from nativescript-toasty are working as expected - here is [the modified demo project.](https://play.nativescript.org/?template=play-tsc&id=ilfBLM&v=2)

**Comment by kefahB** [comment]
@NickIliev .. I am sorry, the issue come from my side !! I made a big mistake in my App side .. I have copy/past the code to testing the BottomNavigation concept from your Doc .. in `TabContentItem` there is a `GridLayout` and by error I have the `Frame` inside the Grirdlayout !! and for that causing 5 day debugging.....

Removing Gridlayout resolve the issue.

Sorry about that

```xml
<TabContentItem>
        <GridLayout>
            <Frame default="some-page" />
        </GridLayout>
</TabContentItem>
```
