### ISSUE TITLE
Nativescript app size is growing each time when a new screen is added

### ISSUE THREAD

**Issue by vick16ach** [NativeScript/NativeScript#8228]
I have `10 xml files`, and `23 js files`, and `1 css file` 

`4 font styles`, `25 10kb images`. Thats all

my `app` folder size is `2.77 mb`

these are the dependencies

```
{
  "nativescript": {
    "id": "org.nativescript.higherstudy",
    "tns-android": {
      "version": "6.3.0"
    },
    "tns-ios": {
      "version": "6.3.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@nativescript/theme": "~2.2.1",
    "@nstudio/nativescript-floatingactionbutton": "^1.1.0",
    "@nstudio/nativescript-loading-indicator": "^2.0.0",
    "nativescript-carousel": "^6.1.1",
    "nativescript-pdf-view": "^2.1.0",
    "nativescript-permissions": "^1.3.8",
    "nativescript-phone": "^1.4.1",
    "nativescript-toast": "^2.0.0",
    "nativescript-ui-listview": "^8.0.1",
    "tns-core-modules": "~6.3.0"
  },
  "devDependencies": {
    "nativescript-dev-webpack": "~1.4.0"
  },
  "gitHead": "94f487c5279f7abc2cc61cb48e357d1756865a40",
  "readme": "NativeScript Application"
}
```

when i build the app on `Sidekick` the size of apk file is `43,873kb` which is `43mb`

each time when i add xml js file the size was growing with a range of `5 to 8 mb` in size.

`is it time to stop using nativescript` who will download my simple app with big size.

the problem video link https://youtu.be/FtcbagvDqR8  where i create hello world app and simply build an apk which sized `28 mb`. which is `14mb` before webpack update.

**Comment by NickIliev** [comment]
@vick16ach you are creating a **debug** build which is (as expected) larger in size than a **release** build. There are a number of optimizations that can (and should) be executed to produce an optimized (in size and in-app speed) APK for production. 

[The CLI provides the options](https://docs.nativescript.org/performance-optimizations/bundling-with-webpack#optimizations) to run Uglify.js, snapshots, AOT compilation and Webpack (by default) but apart from those optimizations, the Android builds are also to be optimized with [Android App Bundle](https://docs.nativescript.org/tooling/publishing/android-app-bundle) or [ABI Splits](https://docs.nativescript.org/tooling/publishing/android-abi-split).

For example, [see this app](https://github.com/NickIliev/nativescript-ng-cosmos) (significantly larger than a Hello World template) which [is 11mb on Google Play Store](https://play.google.com/store/apps/details?id=org.nativescript.curiosity&hl=en_US)

**Comment by vick16ach** [comment]
My bad, I though native-script members gave a very bad update. but Once ill build release version and convinced with the size. I'll for sure update this thread with a brief explanation to help others. Thank you
