### ISSUE TITLE
Android - How to identify that they keyboard is open or closed

### ISSUE THREAD

**Issue by shreenailink** [NativeScript/NativeScript#8230]
*Current behavior*
In our application, we are having a chat detail screen. We would like to show a bottom bar under the chat, when the keyboard is not shown, but would like to hide the bottom bar,  when the keyboard is open.

We tried to solve this with keyboard events like when the keyboard will open we will hide the bottom bar and when the keyboard will close we will show the Bottom Bar, but we are not able to find events, that inform us correctly.

*Expected behavior*
We would like to show a bottom bar under the chat, when the keyboard is not shown, but would like to hide the bottom bar, when the keyboard is opened.

*Configuration*
We are using the below configuration for our application:

Angular CLI: 7.3.8
Node: 8.9.0
OS: Linux x64
typescript: 3.2.4

*Already Tried*
To hide the bottom bar when the keyboard is open we already tried below solutions:

1. To change in AndroidManifest.xml, `android:windowSoftInputMode="adjustPan".`
We had some success by this method, but it caused trouble elsewhere, like hiding half of the text input area behind the keyboard.

2. To get the Keyboard's current state and according it hide or show bottom bar. But here we are not able to find the correct events that can be called when keyboard will close and we can hide it.

Are there any events that exist, to identify that the keyboard is closed/open? 
Is there any other / best practice approach to achieve the hiding of an element based on the keyboard open / closed status?

**Comment by NickIliev** [comment]
@shreenailink there is a plugin [nativescript-keyboardshowing ](https://www.npmjs.com/package/nativescript-keyboardshowing) that provides this functionality
