### ISSUE TITLE
Detect if app runs in Debug mode ?

### ISSUE THREAD

**Issue by jscti** [NativeScript/NativeScript#8231]
Is there a boolean somewhere available to know (JS Side), if the currenttly running app is in Debug Mode or not ?
Like the boolean `isAndroid` from 'tns-core-modules/platform'

Seems like a very basic need so I might be missing it.

Need it to console.log OR not and to display a visual "debug" warning when running app.

Thanks

**Comment by NickIliev** [comment]
@jscti you could create your own production variable in `webpack.config.js` and then access it runtime. 

For example, open `webpack.config.js` and add the following key-value in DefinePlugin section
```JavaScript
// ...

plugins: [
            // Define useful constants like TNS_WEBPACK
            new webpack.DefinePlugin({
                "global.TNS_WEBPACK": "true",
                "global.production": !!production, // here
                "process": "global.process",
            }),

// .. more code follows here
```

And then access runtime as follows:
```JavaScript
    if (global["production"]) {
        alert(`global["production"]: ${global["production"]}`);
    }
```


Note that the `console.log` is disabled by default when running a release build. If you want to explicitly allow logs in a release then you need to add the **forceLog** in the **internal** package.json

**app/package.json**
```JavaScript
{
  "main": "app.js",
  "android": {
    "v8Flags": "--expose_gc",
    "markingMode": "none",
    "forceLog": true 
  }
}
```

**Comment by jscti** [comment]
Thanks

> Note that the console.log is disabled by default when running a release build

Is that true also for android ?

The docs (https://docs.nativescript.org/ns-framework-modules/console) tell it only for IOS :

> iOS Specifics: On iOS the logging is enabled only in debug and will not work in release.

**Comment by NickIliev** [comment]
@jscti 

> Is that true also for Android?

Yes the latest version of the CLI will strip logs for both Android and iOS (when building in release without the `forceLog` flag)
