### ISSUE TITLE
Delegate methods not triggering

### ISSUE THREAD

**Issue by dotnetdreamer** [NativeScript/NativeScript#8234]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.3.0
 - Cross-platform modules: 6.3.0
 - Android Runtime: 6.3.0
 - iOS Runtime: 6.3.0
 - Plugin(s):
Dependencies:
┌───────────────────────────────────┬──────────┐
│ Plugin                            │ Version  │
│ @angular/animations               │ ~8.2.0   │
│ @angular/common                   │ ~8.2.0   │
│ @angular/compiler                 │ ~8.2.0   │
│ @angular/core                     │ ~8.2.0   │
│ @angular/forms                    │ ~8.2.0   │
│ @angular/platform-browser         │ ~8.2.0   │
│ @angular/platform-browser-dynamic │ ~8.2.0   │
│ @angular/router                   │ ~8.2.0   │
│ lodash                            │ ^4.17.15 │
│ moment                            │ ^2.24.0  │
│ nativescript-angular              │ ^8.2.1   │
│ nativescript-animate-sass         │ 0.0.2    │
│ nativescript-audio                │ ^5.0.5   │
│ nativescript-background-http      │ ^4.2.0   │
│ nativescript-calendar             │ ^2.1.0   │
│ nativescript-camera               │ ^4.5.0   │
│ nativescript-directions           │ ^1.3.1   │
│ nativescript-email                │ ^1.5.5   │
│ nativescript-fingerprint-auth     │ ^7.0.2   │
│ nativescript-gif                  │ ^4.0.2   │
│ nativescript-imagepicker          │ ^7.1.0   │
│ nativescript-iqkeyboardmanager    │ ^1.5.1   │
│ nativescript-mediafilepicker      │ ^2.0.18  │
│ nativescript-pager                │ ^11.0.11 │
│ nativescript-pdf-view             │ ^2.1.0   │
│ nativescript-permissions          │ ^1.3.8   │
│ nativescript-phone                │ ^1.4.1   │
│ nativescript-secure-storage       │ ^2.6.0   │
│ nativescript-speech-recognition   │ ^1.5.0   │
│ nativescript-sqlite               │ ^2.3.3   │
│ nativescript-theme-core           │ ~1.0.6   │
│ nativescript-ui-calendar          │ ^5.0.0   │
│ nativescript-ui-listview          │ ^7.1.0   │
│ nativescript-videoplayer          │ ^4.2.1   │
│ nativescript-web-image-cache      │ ^5.0.0   │
│ reflect-metadata                  │ ~0.1.12  │
│ rxjs                              │ ^6.4.0   │
│ string                            │ ^3.3.3   │
│ tns-core-modules                  │ ~6.3.0   │
│ zone.js                           │ ~0.9.1   │
└───────────────────────────────────┴──────────┘
Dev Dependencies:
┌───────────────────────────┬─────────┐
│ Plugin                    │ Version │
│ @angular/compiler-cli     │ ~8.2.0  │
│ @ngtools/webpack          │ ~8.2.0  │
│ codelyzer                 │ ~4.5.0  │
│ nativescript-dev-webpack  │ ~1.4.0  │
│ node-sass                 │ ^4.12.0 │
│ tns-platform-declarations │ ^6.1.1  │
│ tslint                    │ ~5.19.0 │
│ typescript                │ ~3.5.3  │
└───────────────────────────┴─────────┘

**Describe the bug**
I have used the following code. However, whenever i call the picker, the picker does show up but when i select a document e.g any PDF file the closer simply closes without any errors or triggering the delegate method.
I have tested on iPhone 8 Plus which has iOS 13.3 installed. **It works in simulator as expected.**

**To Reproduce**

```
import * as utils from "tns-core-modules/utils/utils";

export class FilePicker {
    _documentPickerViewController: UIDocumentPickerViewController;
    // _documentPickerDelegate: UIDocumentPickerDelegateImp;

    constructor() {
        // this._documentPickerDelegate = new UIDocumentPickerDelegateImp();

        const utis = [kUTTypePDF as string];
        let nsUtis: NSArray<string> = utils.ios.collections.jsArrayToNSArray(utis);
        let documentPicker = UIDocumentPickerViewController.alloc().initWithDocumentTypesInMode(nsUtis, 
            UIDocumentPickerMode.Import);
        documentPicker.modalPresentationStyle = UIModalPresentationStyle.FormSheet;
        // documentPicker.delegate = this._documentPickerDelegate;

        this._documentPickerViewController = documentPicker;
    }

    isAvailable() {
        let supported = NSClassFromString("UIDocumentPickerViewController");
        return supported;
    }

    present() {
        return new Promise((resolve, reject) => {
            if (!this.isAvailable()) {
                reject("your device can't show the file picker");
                return;
            }
            const documentPickerDelegate = UIDocumentPickerDelegateImp.new();
            documentPickerDelegate._resolve = resolve;
            documentPickerDelegate._reject = reject;
            this._documentPickerViewController.delegate = documentPickerDelegate;

            let app = UIApplication.sharedApplication;
            app.keyWindow.rootViewController.presentViewControllerAnimatedCompletion(
                this._documentPickerViewController, true, null);
        });

    }

    release() {
        // this._documentPickerDelegate = null;
        this._documentPickerViewController = null;
    }
}

export class UIDocumentPickerDelegateImp extends NSObject implements UIDocumentPickerDelegate {
    public static ObjCProtocols = [UIDocumentPickerDelegate];

    _resolve: any;
    _reject: any;

    static new(): UIDocumentPickerDelegateImp {
        const instance = <UIDocumentPickerDelegateImp>super.new(); // calls new() on the NSObject

        // instance.registerToGlobal();
        return instance;
    }
    
	documentPickerDidPickDocumentsAtURLs?(
        controller: UIDocumentPickerViewController, urls: NSArray<NSURL> | NSURL[]): void {
        alert('documentPickerDidPickDocumentsAtURLs');
    }

	documentPickerDidPickDocumentAtURL(controller: UIDocumentPickerViewController, url: NSURL): void {
        alert('documentPickerDidPickDocumentAtURL');
        if (controller.documentPickerMode == UIDocumentPickerMode.Import) {
            const name = url.lastPathComponent;
            const path = url.path;

            this._resolve({ name: name, path: path });
        } else {
            this._resolve();
        }
    }

	documentPickerWasCancelled?(controller: UIDocumentPickerViewController): void {
        this._resolve();
    }
}
```

**Expected behavior**
Calling picker should trigger documentPickerDidPickDocumentAtURL method in delegate.

**Sample project**

I have tried to use playground but its taking too long. The sample code is above. Simply call it using following code:
```
const filePicker = new FilePicker();                    
const response: any = await filePicker.present();
```

**Comment by NickIliev** [comment]
@dotnetdreamer you could create a demo project via the CLI and share it via archive or source control link.

**Comment by dotnetdreamer** [comment]
Hi thanks for the info. I resolved the issue using globals. It seems that the delegate reference was destroying... 
```
declare const global: any;
const setDocumentPickerDelegate = (value: any) =>  (<any>global).documentPickerDelegate = value;
const getDocumentPickerDelegate = () =>  (<any>global).documentPickerDelegate;
```
