### ISSUE TITLE
ld: framework not found TNSCrashlyticsLogger

### ISSUE THREAD

**Issue by curtiscarlson** [NativeScript/NativeScript#8242]
After Xcode automatically updated itself to 11.3 my project won't build.  I am getting an xcode build failed with exit code 65, trying to build for ios emulator.  Before that, I am getting this error: ld: framework not found TNSCrashlyticsLogger 
I'm not sure what crashlytics is.  it appears in Xcode in the user defined area of the target project.  I don't know if nativescript or nativescript-vue may have added it.  If not, then who else?  I can't seem to find anything on this online.  I upgraded nativescript and Xcode to the latest versions.  Any thing else I should be looking at?  I am not really good at Xcode and the build settings, I'm more of a javascript developer, hence using this framework.  Thank you.

**Comment by NickIliev** [comment]
@curtiscarlson update the version of your NativeScript CLI to latest
```
npm uninstall -g nativescript
npm i -g nativescript
```

And then make a clean rebuild with latest runtimes
```
rm -rf platforms
tns platform add ios
```

**Comment by curtiscarlson** [comment]
@NickIliev Thank you!!  That seems to have done the trick.
