### ISSUE TITLE
TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by aaronliangj88** [NativeScript/NativeScript#8243]
There is a error when launch after update the version to 6.3.2 .The error is 
```
TypeError: Cannot read property 'join' of undefined.
```

The stackTrace is  
```
loadFontFromFile(file:///node_modules/@nativescript/core/ui/styling/font.js:52:0).
```
Then i analyze the source code of the font.js.I found the reason is the code of "var fs = require("../../file-system");" is wrong. The solution is replace the code with "var fs = require("tns-core-modules/file-system");"

**Comment by NickIliev** [comment]
@aaronliangj88 could you post the content of your **package.json** file and even better a sample project that reproduces the issue?

**Comment by aaronliangj88** [comment]
[package.json.zip](https://github.com/NativeScript/NativeScript/files/4058078/package.json.zip)

**Comment by NickIliev** [comment]
@aaronliangj88 the issue is not reproducible on my side - the import should work with the relative path just as good as with the absolute path.
