### ISSUE TITLE
HtmlView not rendering correctly on android

### ISSUE THREAD

**Issue by connor-sleight** [NativeScript/NativeScript#8246]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  6.1.2
 - Cross-platform modules: 6.0.3
 - Android Runtime: 6.1.2
 - iOS Runtime: N/A
 - Plugin(s): None relating to this

**Describe the bug**
I have a HtmlView that doesn't completely render the styles if I have 2 nested spans.

**To Reproduce**
If the value of the HtmlView is set to the following, only the first sentence is shown in red and the second is default colour:

`<p><span style="color:#ff6666"><span style="font-family:helvetica neue,helvetica,arial,sans-serif; font-size:14px">Span 1 Text.</span> <span style="font-family:helvetica neue,helvetica,arial,sans-serif; font-size:14px">Span 2 Text.</span></span></p>`

If the following value is used, all the text renders as red:

`<p><span style="color:#ff6666"><span style="font-family:helvetica neue,helvetica,arial,sans-serif; font-size:14px">Span 1 Text.  Span 2 Text.</span></span></p>`

**Expected behavior**
I expected that the first sample of code would render the whole text red, rather than the first nested span.

**Additional context**
This html comes from a backend service, generated from a cms admin panel. Meaning it cant easily be changed

**Comment by NickIliev** [comment]
@connor-sleight the HtmlView implementation provides limited support of HTML and CSS.

If you need to render more complex HTML views then use the `WebView` - refer to [this Playground demo](https://play.nativescript.org/?template=play-tsc&id=C6NqiB) that uses your first snippet

**Comment by connor-sleight** [comment]
@NickIliev I dont see how this is complex. I'm just trying to apply a colour to 2 nested spans which is simple html.

Using WebView will heavily impact our app as we currently use the HtmlView within a listview, which can have 1-500+ entries, including then also the same in multiple subviews

**Comment by NickIliev** [comment]
@connor-sleight see the documentation article [here](https://docs.nativescript.org/ui/components/html-view#html-view)

> Note: The HtmlView component has limited styling capabilities. For more complex scenarios use the WebView component.

If you want to extend the functionalities supported by HtmlView then you could become a contributor and post a PR - [the HtmlView related code is here](https://github.com/NativeScript/NativeScript/tree/master/nativescript-core/ui/html-view).

**Comment by connor-sleight** [comment]
@NickIliev I still dont see how this is complex? Surely this should be basic functionality? ie apply a style to all nested tags?

**Comment by NickIliev** [comment]
@connor-sleight the HtmlView is using the native [android.text.Html](https://developer.android.com/reference/android/text/Html) which has its own limitations. 

> This class processes HTML strings into displayable styled text. Not all HTML tags are supported.


See also this thread: 

https://stackoverflow.com/questions/13972940/android-html-fromhtml-does-not-work-correctly-on-nested-text-style

It might be possible to implement nested styling - if so, then we will be more than happy to accept the PR that does it.
