### ISSUE TITLE
Support for base64 and url() for Image in BottomNavigaiton, Tabs

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#8253]
**Is your feature request related to a problem? Please describe.**

The `Image` placeholder in BottomNavigation is currently supporting resources (`res://`), local images or font icons (`font://`).

**Describe the solution you'd like**

Extend the image support by providing options to pass **base64** string or image with **url()**

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
