### ISSUE TITLE
File.exists always give false

### ISSUE THREAD

**Issue by hgc2002** [NativeScript/NativeScript#8254]
Good morning,

I'm trying to find out if a file exists prior to (example) delete it or rename it, and of course, I'm using the exists function of File class, but it always return false, so this is causing a big problem for me. Here there are my examples:

try 1:
```JavaScript
const fileSystemModule = require("tns-core-modules/file-system");
const documents = fileSystemModule.knownFolders.documents();
const path = fileSystemModule.join(documents.path, "my_sqlite_database_db.db");
const exists = fileSystemModule.File.exists(path);
console.log(\`Does my_sqlite_database_db.db exists: ${exists}\`);
```
try 2:
```JavaScript
const fileSystemModule = require("tns-core-modules/file-system");
const documents = fileSystemModule.knownFolders.documents();
const path = fileSystemModule.join(documents.path, "my_sqlite_database_db.db");
const path2 = fileSystemModule.path.normalize(path); // <--- here is the change
const exists = fileSystemModule.File.exists(path2);
console.log(\`Does my_sqlite_database_db.db exists: ${exists}\`);

```
I've already verified that my file (my_sqlite_database_db.db, that is actually a sqlite database) is there and can be opened without any issue.

Here is my version info:

iOS: 13.3 (simulator iPhone 8) (Android not tested yet)
tns: 6.2.2
tns-core-modules@6.3.1
tns-ios: 6.2.0

**Comment by NickIliev** [comment]
@hgc2002 the *.db extension is not automatically handled by Webpack (in `webpack.config.js`) - can you make sure that you have provided the file in **CopyWebpackPlugin** section of the config file (e.g. here add  from: { glob: "<databasepath>/my_sqlite_database_db.db" } },).

**Comment by hgc2002** [comment]
Hi, 
Yes, my Webpack has been modified:

            new CopyWebpackPlugin([
                { from: { glob: "fonts/**" } },
                { from: { glob: "**/*.+(jpg|png)" } },
                { from: { glob: "assets/**/*" } },
                { from: { glob: "**/*.db" } },
            ], { ignore: [`${relative(appPath, appResourcesFullPath)}/**`] }),

But, here is the deal: the database can be opened without any problem so I know it is transferred with the application and copied properly to the folder the nativescript-sqlite plugin use for it (documents in iOS and databases in Android). That is not the issue. The db file is there and works.

The question is: why File.exists(path) always gives false ???

Is there any way to debug this ??

By the way, I found a workaround asking for Folder.contains(file or folder) entities. I don't know how File.exists is implemented actually but is not this way.

**Comment by NickIliev** [comment]
@hgc2002 the file-system is just a high-level abstraction of the native implementation. Here is what is [the code behind `File.exists`](https://github.com/NativeScript/NativeScript/blob/master/nativescript-core/file-system/file-system-access.android.ts#L92-L96). However, there are known cases where the Java method `exists` is not working properly (see [here](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=5003595))

**Comment by NickIliev** [comment]
@hgc2002 the method is working on my side -[ tested via this app](https://github.com/NickIliev/NS-Issues-2019-I/blob/master/issue-8254/app/main-page.ts#L13-L16).

Note that in your snippet there was an error while accessing the **join** method


```TypeScript
import { knownFolders, File, path } from "tns-core-modules/file-system";

    const documents = knownFolders.currentApp();
    const mypath = path.join(documents.path, "db/my_sqlite_database_db.db");
    const exists = File.exists(mypath);
    console.log(`Does my_sqlite_database_db.db exists: ${exists}`);
```

**Comment by hgc2002** [comment]
Yes, the join call was wrong, because it's part of path class.

Actually I found my mistake, maybe the examples didn't the best I could: my issue came becaise I was using File.exists for everything, including folders, and this is wrong because there is actually another method in Folder for this: Folder.exists

I have fixed everything and all is working fine now.
Thanks for your heplp. 
Closing.
