### ISSUE TITLE
Vue Tabview component in playground

### ISSUE THREAD

**Issue by pat-flew** [NativeScript/NativeScript#8259]
Running through the Vue tutorial in the playground, lesson 3 step 7 says drag a TabView from the component selector on the left. But there's no TabView component in the selector. I can only find a Tabs navigation component. Has something changed here, or am I missing something obvious..?

**Comment by NickIliev** [comment]
@pat-flew thanks for bringing this one into our attention. Indeed, we've removed the TabView from the Playground and we need to update the tutorial to use the recently introduced[ **Tabs** component](https://docs.nativescript.org/ui/components/tabs).

Marking this issue as a bug -[ the tutorial ](https://github.com/NativeScript/playground-tutorials)needs to be migrated to use Tabs

**Comment by NickIliev** [comment]
Will be resolved via https://github.com/NativeScript/playground-tutorials/pull/55
