### ISSUE TITLE
Activating elements using TalkBack (Android accessibility feature) is not working

### ISSUE THREAD

**Issue by alexborbely** [NativeScript/NativeScript#8262]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - Android: 8.1 & 9
 - CLI: 6.1.2
 - Cross-platform modules: 6.1.2
 - Android Runtime: 6.1.1
 - iOS Runtime: 6.1.1

**Describe the bug**
Trying to navigate though Examples NativeScript application (4.3) using the TalkBack feature. Activating the elements from the first page (Layouts, User profile, Conference agenda ...) is not working. I've got the same behaviour when trying to activate Label components from the Examples NativeScript application or my application.

**To Reproduce**
To reproduce the issue activate the TalkBack feature from the Settings > Accessibility menu (if the TalkBack is not shown, the Android Accessibility Suite (4.3) from Google needs to be installed), install the Examples NativeScript application (4.3) and try to navigate through the first page items (or create a simple application with a clickable Label).

**Comment by NickIliev** [comment]
@alexborbely thank you for your detailed explanation of the problem. Indeed the accessibility has a number of functionalities that would need additional implementation - logged as a feature request [here ](https://github.com/NativeScript/NativeScript/issues/6993)so closing this one as a duplicate.
