### ISSUE TITLE
DatePicker dateChange event not triggered on iOS

### ISSUE THREAD

**Issue by bernica** [NativeScript/NativeScript#8264]
**Describe the bug**
When opening the date picker with a selected Date different than today, changing the selected date to today doesn't update the date picker's date nor it triggers a date change event.

Draft PR open at https://github.com/NativeScript/NativeScript/pull/8263

**Comment by NickIliev** [comment]
@bernica you need [to sign the CLA so we could merge the PR](https://github.com/NativeScript/NativeScript/pull/8263)

**Comment by vtrifonov** [comment]
@bernica can you, please, provide a playground example for that as I cannot reproduce it?

**Comment by bernica** [comment]
@vtrifonov I'm initializing the date picker like:

```
onPickerLoaded(args: any) {
  this.datePicker = <DatePicker>args.object;
  this.datePicker.date = someDate;
```

and within the view:

```
<DatePicker (loaded)="onPickerLoaded($event)" (dateChange)="onDateChanged($event)"></DatePicker>
```

**Comment by vtrifonov** [comment]
I still cannot reproduce it: https://play.nativescript.org/?template=play-ng&id=jto0xk . Can you create a playground sample to show that? I'm setting the date to a date in the past, then either programmatically or manually changing the date to today always trigger the onDateChanged event.

**Comment by vtrifonov** [comment]
@bernica could you, please, provide a playground demo or a sample app with the issue, as I cannot reproduce it?

**Comment by bernica** [comment]
@vtrifonov https://play.nativescript.org/?template=play-ng&id=hNo33P&v=2 when loaded the selected date is tomorrow, and changing it to today's date doesn't trigger the dateChange event (in which I log to the console).

**Comment by vtrifonov** [comment]
I see now! Thanks, it makes sense now! Are you going to add something else to the PR as it is in Draft.

**Comment by bernica** [comment]
I won't be able to add anything more as I lack time
