### ISSUE TITLE
Android Immersive mode

### ISSUE THREAD

**Issue by dimitriospafos** [NativeScript/NativeScript#8265]
**Is your feature request related to a problem? Please describe.**
I'm trying to use Android's immersive mode at all times. Seems like the sticky immersive mode get's disabled when soft keyboard is shown, such as when trying to type in, in a TextField. I know this functionality it's not supported even in native Android out of the box at this time, but there are workarounds.

**Describe the solution you'd like**
I would like to find a way to keep the immersive mode whenever I'm typing in a TextField.

**Describe alternatives you've considered**
I tried to implement a solution which extends the "AppCompatActivity" from here: :https://stackoverflow.com/questions/24187728/sticky-immersive-mode-disabled-after-soft-keyboard-shown following the docs from here: https://docs.nativescript.org/core-concepts/android-runtime/advanced-topics/extend-application-activity but seems like "onWindowFocusChanged" does not get invoked when I start/stop typing in a TextField, It only get's invoked when the app starts.

**Additional context**
Code of extended AppCompatActivity class:

`import {setActivityCallbacks, AndroidActivityCallbacks} from "tns-core-modules/ui/frame";

@JavaProxy("com.MyApp.MainActivity")
class Activity extends androidx.appcompat.app.AppCompatActivity {
    public isNativeScriptActivity;
    private mHideHandler :HideHandler;

    private _callbacks: AndroidActivityCallbacks;

    public onCreate(savedInstanceState: android.os.Bundle): void {
        // Set the isNativeScriptActivity in onCreate (as done in the original NativeScript activity code)
        // The JS constructor might not be called because the activity is created from Android.
        this.isNativeScriptActivity = true;
        if (!this._callbacks) {
            setActivityCallbacks(this);
        }

        this.mHideHandler = new HideHandler(this);

        this._callbacks.onCreate(this, savedInstanceState, this.getIntent(), super.onCreate);
    }

    public onSaveInstanceState(outState: android.os.Bundle): void {
        this._callbacks.onSaveInstanceState(this, outState, super.onSaveInstanceState);
    }

    public onStart(): void {
        this._callbacks.onStart(this, super.onStart);
    }

    public onStop(): void {
        this._callbacks.onStop(this, super.onStop);
    }

    public onDestroy(): void {
        this._callbacks.onDestroy(this, super.onDestroy);
    }

    public onBackPressed(): void {
        this._callbacks.onBackPressed(this, super.onBackPressed);
    }

    public onResume(): void {
        this.setToImmersiveMode();
    }

    public onRequestPermissionsResult(requestCode: number, permissions: Array<string>, grantResults: Array<number>): void {
        this._callbacks.onRequestPermissionsResult(this, requestCode, permissions, grantResults, undefined /*TODO: Enable if needed*/);
    }

    public onActivityResult(requestCode: number, resultCode: number, data: android.content.Intent): void {
        this._callbacks.onActivityResult(this, requestCode, resultCode, data, super.onActivityResult);
    }

    public onWindowFocusChanged(hasFocus: boolean) {
        super.onWindowFocusChanged(hasFocus);
        if(hasFocus) {
            this.mHideHandler.removeMessages(0);
            this.mHideHandler.sendEmptyMessageDelayed(0, 300);
        }
        else this.mHideHandler.removeMessages(0);
    }

    private setToImmersiveMode() {
        // set to immersive

        const androidViewPkg = android.view;
        var View = androidViewPkg.View;

        this.getWindow().getDecorView().setSystemUiVisibility(
                View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                        | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                        | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                        | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
                        | View.SYSTEM_UI_FLAG_FULLSCREEN
                        | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);
    }
}

class HideHandler extends android.os.Handler {
    private static mActivity: java.lang.ref.WeakReference<Activity>;

    constructor (activity: Activity) {
        super();
        HideHandler.mActivity = new java.lang.ref.WeakReference(activity);
    }

    public handleMessage(msg: any) {
        var activity = HideHandler.mActivity.get();
        if(activity != null) activity.setToImmersiveMode();
    }
}`

**Comment by NathanaelA** [comment]
I can't answer to the above question directly, however my plugin ns-keyboard-showing will allow you to do whatever on both the keyboard showing and hiding.   You might be able to work around the issue using my plugin when the keyboard hides to call you `setToImmersiveMode()`

**Comment by dimitriospafos** [comment]
@NathanaelA are you referring to this https://github.com/NathanaelA/nativescript-keyboardshowing plugin ? Seems like there is no Typescript/Angular support for it.

**Comment by NathanaelA** [comment]
Two things:
- Because TypeScript is a subset of JavaScript; you can use any JS plugin (even if it doesn't have typings) inside your TS apps.     However that link is for the older community supported version -- it may not work in NS 6, it was designed and tested in NS <= 5.

- The professionally supported ProPlugins version (https://npm.proplugins.org/-/web/detail/@proplugins/nativescript-keyboardshowing) actually does have typings and I know it has several fixes for NS 6.x.  :-D

**Comment by dimitriospafos** [comment]
Thank you, will try it tonight.

**Comment by dimitriospafos** [comment]
Seems like this actually works. Even though it's a workaround and you need to get the Pro plugin subscription it does the job for now. I used :

	```
	keyboard.on(keyboard.ALL, () => { 
			setTimeout( () => setImmersiveScreen(), 50);
			

		}, [this]);
```
