### ISSUE TITLE
iOS project generated with Development Code Signing Identities for Release build

### ISSUE THREAD

**Issue by tralves** [NativeScript/NativeScript#8266]
**Environment**
 - CLI:  6.3.3
 - Cross-platform modules:  ~6.3.0
 - Android Runtime:  6.3.1
 - iOS Runtime: 6.3.0
 - Plugin(s): irrelevant

**Describe the bug**
When creating the iOS Xcode workspace, the project has the Development code signing identities for the Release build, as you can see here:

<img width="504" alt="Screen Shot 2020-01-22 at 01 09 03" src="https://user-images.githubusercontent.com/2600867/72856973-2756c800-3cb4-11ea-8085-c2b89d856561.png">

This is a problem in my setup, where I am using GH actions and fastlane for CI/CD.

**To Reproduce**
```
rm -rf platforms
tns prepare ios
```

**Expected behavior**

When the project is created, the Release build should be set to the Distribution identities, like this:

<img width="581" alt="Screen Shot 2020-01-22 at 01 13 54" src="https://user-images.githubusercontent.com/2600867/72857107-93393080-3cb4-11ea-8fb8-944c258b0459.png">

**Additional context**
I was able to fix this issue in my setup by adding to `build.xconfig`:

```
CODE_SIGN_IDENTITY[config=Debug] = iPhone Developer
CODE_SIGN_IDENTITY[config=Release] = iPhone Distribution
```

This produced the result:

<img width="561" alt="Screen Shot 2020-01-22 at 01 21 09" src="https://user-images.githubusercontent.com/2600867/72857499-b2848d80-3cb5-11ea-9f8b-dcda967e0ce0.png">

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #5223](https://github.com/NativeScript/nativescript-cli/issues/5223) via [**ZenHub**](https://www.zenhub.com/)
