### ISSUE TITLE
Copying App to new folder will not compile with all assets

### ISSUE THREAD

**Issue by mrwrighty** [NativeScript/NativeScript#8268]
I need to create a variation on an existing app. I created a new folder using SideKick, then copied the various app folders I require over to the new project folder. This include the usual page.js and xml files as well as assets of images and video. I updated the settings.json file and the package.json file to reflect the new app name com.xxxx.myapp2.

When running tns debug android, the mp4 video files are not included in the build. The original source build fine with all the assets.

I've checked all the files I know of, but cannot find why these assets and not included in the build. The file structure and paths are exactly as the original project. I have numerous times removed platform, node_modules and hooks but unable to fix it. I've tried tns clean android, tns update etc etc, but still they are missing. This is the second variation of the project. The first variation doing exactly as I have done above compiled correctly and included all assets.

**Comment by NathanaelA** [comment]
@mrwrighty - Check your webpack.config.js file; towards the bottom is a section that says what type of extra resources to include.   
I would guess your App1 has a glob with  **/*.mp4 and your App2 is missing the same glob.

**Comment by NickIliev** [comment]
@mrwrighty [this is the section](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/webpack.config.js#L302-L306) @NathanaelA is talking about.

```JavaScript
            new CopyWebpackPlugin([
                { from: { glob: "fonts/**" } },
                { from: { glob: "**/*.jpg" } },
                { from: { glob: "**/*.png" } },
            ], { ignore: [`${relative(appPath, appResourcesFullPath)}/**`] }),
```

**Comment by mrwrighty** [comment]
I’m pretty sure I copied over the web.config.js file but will check later this morning.

**Comment by mrwrighty** [comment]
OK I had missed these settings on two of the variations of the app. But variation 1 had it and compiled correctly. Variation 2 did not have the glob values and still compiled correctly. Variation 3 also did not have the glob values and failed to build all the assets. I have now added the following and this has fixed Variation 3, but do not understand how Variation 2 was working without the code below.`{ from: { glob: "**/*.mp3" } },
                { from: { glob: "**/*.mp4" } },
                { from: { glob: "audio/**" } },`

**Comment by NickIliev** [comment]
@mrwrighty hard to say without actually having the codebase of version 2 - for example, we can speculate that you were using webpack config that was adding a specific folder (which was containing all the needed files). 

Closing the issue as resolved.
