### ISSUE TITLE
ImageAsset returns empty object for geo location (ios) (vue)

### ISSUE THREAD

**Issue by andrevvm** [NativeScript/NativeScript#8270]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.3.3
 - Cross-platform modules: 6.3.2
 - Android Runtime: 6.3.1
 - iOS Runtime: 6.3.0
 - Plugin(s): tns-core-modules

**Describe the bug**
```ImageAsset``` is returning an empty ```location``` when it exists on the asset.

**To Reproduce**
Check the ```asset.ios.location``` object on a returned ImageAsset in nativescript-vue

**Expected behavior**
Location returned

**Additional context**
See output of asset object from 
```
CONSOLE LOG file:///node_modules/@nativescript/core/image-asset/image-asset.js:13:24: 'asset' 'burstIdentifier' null
CONSOLE LOG file:///node_modules/@nativescript/core/image-asset/image-asset.js:13:24: 'asset' 'burstSelectionTypes' 0
CONSOLE LOG file:///node_modules/@nativescript/core/image-asset/image-asset.js:13:24: 'asset' 'creationDate' Mon Jan 13 2020 11:38:44 GMT+0100 (CET)
CONSOLE LOG file:///node_modules/@nativescript/core/image-asset/image-asset.js:13:24: 'asset' 'duration' 0
CONSOLE LOG file:///node_modules/@nativescript/core/image-asset/image-asset.js:13:24: 'asset' 'favorite' false
CONSOLE LOG file:///node_modules/@nativescript/core/image-asset/image-asset.js:13:24: 'asset' 'hidden' false
CONSOLE LOG file:///node_modules/@nativescript/core/image-asset/image-asset.js:13:24: 'asset' 'location' {}
CONSOLE LOG file:///node_modules/@nativescript/core/image-asset/image-asset.js:13:24: 'asset' 'mediaSubtypes' 0
CONSOLE LOG file:///node_modules/@nativescript/core/image-asset/image-asset.js:13:24: 'asset' 'mediaType' 1
```
You can see the location is indeed flagged as true
```
CONSOLE LOG file:///node_modules/@nativescript/core/image-asset/image-asset.js:13:24: 'asset' 'debugDescription' '<PHAsset: 0x10213fd40> 2A79B45E-7F94-4364-B0A9-AF6E3FBC2117/L0/001 mediaType=1/0, sourceType=1, (2448x3264), creationDate=2020-01-13 10:38:44 +0000, location=1, hidden=0, favorite=0 '
```

This is confirmed an issue with Vue, as see output from same image with core NativeScript:
```
CONSOLE LOG file:///node_modules/nativescript-imagepicker/imagepicker.js:107:0: location <+52.48697167,+13.42997000> +/- 0.00m (speed 0.00 mps / course 4.61) @ 1/1/01, 1:00:00 AM Central European Standard Time```

**Comment by NickIliev** [comment]
@andrevvm it is strange that you are seeing the GPS location at all - I think that Apple is stripping the location metadata by default. NativeScript is not overwriting or messing with the EXIF data in any way so if you are not seeing in via the native object then it must be how the metadata is passed.

See [this thread](https://stackoverflow.com/a/21169901/4936697) for a detailed discussion on the topic and for a solution that suggests that you could still parse the metadata from the asset. extracting the metadata is also discussed [here](https://stackoverflow.com/questions/12478502/how-to-get-image-metadata-in-ios)

**Comment by andrevvm** [comment]
Thanks @NickIliev. It is not strange, but a core property of [PHAssets](https://developer.apple.com/documentation/photokit/phasset/1624788-location). So, not talking about the EXIF or metadeta here, but the native location saved when taking a photo with the iOS camera. 

Somehow the property IS lost in Nativescript-Vue, but not Nativescript Core. Is there a better place to report this issue?
