### ISSUE TITLE
iOS 13: Button text gets truncated in the middle when using FormattedString with FontAwesome

### ISSUE THREAD

**Issue by felixkrautschuk** [NativeScript/NativeScript#8272]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.3.3
 - @nativescript/core 6.3.2
 - Android Runtime: -
 - iOS Runtime: 6.3.0
 - Plugin(s): -

**Describe the bug**
in iOS 13, a Button's text gets truncated in the middle when using a FormattedString with FontAwesome. This also happens if the text is short and if there is enough space to show the whole text.
For us, it is only reproducable on iOS 13 Simulator (we have no iOS 13 physical device, but we cannot reproduce it on our iPhone 6 with iOS 12 and the iOS 12 simulator).

![Bildschirmfoto 2020-01-23 um 15 32 34](https://user-images.githubusercontent.com/6443021/72993919-7ad12f00-3df6-11ea-9a21-39d36d6ac6b2.png)

In addition, yo can see on iOS 13 Simulator, that the bottom part of the button's text is cutt off a bit. There is no padding or anything else that could cause this issue.
![Bildschirmfoto 2020-01-23 um 15 42 14](https://user-images.githubusercontent.com/6443021/72994296-25e1e880-3df7-11ea-89cf-a08908321496.png)

Compared to the correct look on iOS 12:
![Bildschirmfoto 2020-01-23 um 15 44 27](https://user-images.githubusercontent.com/6443021/72994424-5f1a5880-3df7-11ea-9ee5-6ebc6ed51c81.png)

**To Reproduce**
Just see the sample app provided below.

**Expected behavior**
The button's text should only be truncated if the content is too long.
The button's text should not be cut off at the bottom.

**Sample project**
[NSButtonFontAwesomeIssueIOS.zip](https://github.com/NativeScript/NativeScript/files/4103584/NSButtonFontAwesomeIssueIOS.zip)

**Additional context**
There is a workaround for truncation in the middle of the text:
Just add a white space to the last Span's text or add a new Span with text=" " at the end of the FormattedString.

But I came to this workaround only by a happy accident, so if there is no prompt fix on this, it should be added to the documentation anywhere at least.

**Comment by NickIliev** [comment]
@felixkrautschuk marking this one as a bug. During my test, it seems that the workaround is not working (if you add a letter like **g** it will be truncated even with the workaround)

**Comment by felixkrautschuk** [comment]
Both issues described in this thread (truncation in the middle and on the bottom) do not occur on my side anymore after upgrading to the latest @nativescript/core@6.5.12 version.
This seems to be fixed by the new default behaviour of vertical-alignment of Spans added by https://github.com/NativeScript/NativeScript/pull/8257
