### ISSUE TITLE
Incorrect calculation of grid coordinates on Android when @longPress event is added

### ISSUE THREAD

**Issue by nodermann** [NativeScript/NativeScript#8278]
**Environment**
 - CLI: Preview 1.28.0
 - Android 8.1.0 (Redmi 5 Plus), Android 5.0 (Samsung Galaxy Note 3)

**Describe the bug**
Incorrect calculation of grid coordinates on **Android** when @longPress event is added.

**Expected behavior**
Remove @longPress="longPress" from label.

**To Reproduce**
Add @longPress="longPress" to label. (Line 10)

**Sample project**
https://play.nativescript.org/?template=play-vue&id=YVklCb

**Additional context**
iPhone 6 and iPhone 11 (simulator) works fine.

**Comment by NickIliev** [comment]
@nodermann not sure what should happen on longPress - I've tested your demo but I am not seeing any difference with or without the long press gesture.

**Comment by nodermann** [comment]
@NickIliev Sorry, try not to lift your finger and move on the grid, the behavior will be different.

**Comment by NickIliev** [comment]
@nodermann again not seeing any difference? Is this happening on a specific API level (Android version)?
