### ISSUE TITLE
Upgrading plugin to 6.3.0 is throwing Parameter specified as non-null is null error

### ISSUE THREAD

**Issue by dotnetdreamer** [NativeScript/NativeScript#8279]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  6.3.0
 - Cross-platform modules: 6.3.0
 - Android Runtime:  6.3.0
 - iOS Runtime: 6.3.0

**Describe the bug**
The plugin was working fine in 6.2.0. Upgrading the project to 6.3.0 started causing issue. 

**To Reproduce**
Clone the repository. Switch to **6.3.0 branch** and run it. After that select a file to upload and you will see the error.

**Expected behavior**
The application should work fine. 

**Sample project**
Clone [this](https://github.com/dotnetdreamer/nativescript-http-formdata) repo.

**Comment by NickIliev** [comment]
@dotnetdreamer the demo project is failing with **permission denied** related error

logcat
```
2020-01-28 13:00:15.012 11033-11033/org.nativescript.demoangular E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/DCIM/Camera/MVIMG_20191206_112259.jpg: open failed: EACCES (Permission denied)
```

And from that point I guess the image parameters is null - which is why the Kotlin compiler is outputting the error you are receiving.

**Comment by dotnetdreamer** [comment]
@NickIliev  the permission error was due to [this](https://github.com/NativeScript/nativescript-imagepicker/issues/309) issue in image-picker plugin. I update my code in 6.3.0 branch and i am still getting same error. Here is the output:

```
submitting [{
JS:   "data": {
JS:     "length": 9187061        
JS:   },
JS:   "contentType": "image/png",
JS:   "fileName": "test.png",    
JS:   "parameterName": "file1"   
JS: }, {
JS:   "data": "John Doe",        
JS:   "parameterName": "firstName"
JS: }]
JS: ---------------home.component.ts---------------
JS: Error: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter type
```

**Comment by NickIliev** [comment]
@dotnetdreamer check if your plugin is making a native call from withing the JavaScript/TypeScript files to a Kotlin method and if so make sure that none of the parameters are not passed as **null**. Kotlin is not allowing a null parameter so if you are calling the method from JS/TS with null parameter the next thing that will happen is the above error where the Kotlin compiler is throwing the IllegalArgumentException

**Comment by NickIliev** [comment]
@dotnetdreamer it seems that you are using a recently migrated to Kotlin version of the OKHttp library and after looking closely in their repository it seems that there are some tests that are failing on Android due to an illegal argument exception of type null - see [here](https://github.com/square/okhttp/issues/4535).

**Comment by dotnetdreamer** [comment]
@NickIliev  the error is in following line. After that it doesn't execute. I event pointed to old version i.e 4.0.1.
`builder.setType(okhttp3.MultipartBody.FORM);`

**Comment by dotnetdreamer** [comment]
@NickIliev it seems that it is comming as null. i have to use parse method. I am not sure if it is an issue with NS runtime. Following way i resolved it:

```
 let builder = new okhttp3.MultipartBody.Builder();
//its null here
                console.log(okhttp3.MultipartBody.FORM)
                // builder.setType(okhttp3.MultipartBody.FORM);
                const FORM_MEDIA_TYPE = okhttp3.MediaType.parse("multipart/form-data");
                builder.setType(FORM_MEDIA_TYPE);
```
