### ISSUE TITLE
How to use DELETE method in http.request or fetch?

### ISSUE THREAD

**Issue by koraykupe** [NativeScript/NativeScript#8284]
I have a Nativescript Vue project, and trying to do a delete request using http module, but it seems like it still does the call as a get method. On the documentation page, it mentions just get and post methods too: https://docs.nativescript.org/ns-framework-modules/http

Also tried fetch, but it was the same.

```JavaScript
http.request({
            url: process.env.API_URL + 'api/v1/bookings/1',
            method: 'DELETE',
            headers: {
              'Content-Type': 'application/x-www-form-urlencoded',
              Accept: 'application/json',
              'Access-Control-Allow-Origin': '*',
              Authorization: 'Bearer *******'
            }
          })
```

Also tried to add `'X-HTTP-Method-Override': 'DELETE'`, but it also didn't work. It's still handled as a GET method request on the API.

For Angular there is a [documentation](https://docs.nativescript.org/ns-framework-modules/http), but what if I am using Vue? How can I do a delete call?

Best Regards

**Comment by NickIliev** [comment]
@koraykupe here is [a TypeScript demo ](https://play.nativescript.org/?template=play-tsc&id=DELJ2u&v=2)(using httpbin.org) but the same should work in Vue based project.

**Comment by koraykupe** [comment]
Thanks @NickIliev it works. It was actually my bad.
