### ISSUE TITLE
[Feature] Support side-by-side title & icon for TabStripItem in landscape (Android)

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#8288]
**Is your feature request related to a problem? Please describe.**
Android guidelines are providing an option to create a bottom navigation bar with tabs where the title and icon for each tab can be **stacked** (supported by NativeScript) or **side-by-side** (supported only for iOS where this is the default option when in Tablet in landscape mode).

**Describe the solution you'd like**
See the material guidelines in [the **_Landscape View_** section ](https://material.io/components/bottom-navigation/#placement)- provide the functionality to support the second doable option.

**Comment by NickIliev** [comment]
Requested via t.1451293

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
