### ISSUE TITLE
Detecting page changes 

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#829]
problem : loaded event is called everytime when navigating to a page, if this is by design, I propose a change in the navigatingTo event (with extra isback:boolean)

The changes : 
		@frame-common.js
    Frame.prototype.performGoBack = function (navigationContext) {
        var navContext = navigationContext.entry;
        this._onNavigatingTo(navContext,true); // mod
        this._goBackCore(navContext);
        this._onNavigatedTo(navContext, true);
    };
    Frame.prototype._goBackCore = function (backstackEntry) {
    };
    Frame.prototype._navigateCore = function (backstackEntry) {
    };
    Frame.prototype._onNavigatingTo = function (backstackEntry,isBack) { // mod
        if (this.currentPage) {
            this.currentPage.onNavigatingFrom();
        }
        backstackEntry.resolvedPage.onNavigatingTo(backstackEntry.entry.context,isBack); // mod
    };

		@page-common.js
    Page.prototype.onNavigatingTo = function (context,isBack) { // mod
        this._navigationContext = context;
        this.notify({
            eventName: Page.navigatingToEvent,
            object: this,
            context: this.navigationContext,
            isback:isBack, // mod
        });
    };

Hope it will help

**Comment by enchev** [comment]
Loaded event comes from View base class and indeed will be called on pages as well when loaded. You can use navigation events in your case if loaded/unloaded are not suitable for you.

**Comment by x4080** [comment]
What navigation event that have back navigation information from hardware button back or soft button back? I look at the doc and cannot find it
