### ISSUE TITLE
App not working on iOS 13.3.1

### ISSUE THREAD

**Issue by dammynex** [NativeScript/NativeScript#8294]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.3.3
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime: 6.3.0
 - Plugin(s):

**Describe the bug**
App not starting on iPhones with latest iOS 13.3.1

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

Here is the log from XCode
[
<img width="615" alt="Screenshot 2020-01-30 at 15 39 23" src="https://user-images.githubusercontent.com/30000286/73459214-bf207a00-4376-11ea-9444-2dfadd0a0d19.png">
](url)

**Comment by NickIliev** [comment]
@dammynex please follow the requirements listed in the open a new issue template. Without the requested information is not very likely that you will receive good or any guidance. Avoid posting images instead of the real log (which can be provided as an external link to a file or as an archive)


> **Environment**
> Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
>  - CLI: 
>  - Cross-platform modules:
>  - Android Runtime:
>  - iOS Runtime:
>  - Plugin(s):
> 
> **Describe the bug**
> 
> 
> **To Reproduce**
> 
> 
> **Expected behavior**
> 
> **Sample project**
> 
> 
> **Additional context**
> 
>

**Comment by NickIliev** [comment]
@dammynex [check this SO thread ](https://stackoverflow.com/questions/32730312/reason-no-suitable-image-found/32730393#32730393)where it is suggested that the issue is related to a recently revoked certificate

**Comment by ronalson** [comment]
Hi @NickIliev, I reported this issue on the slack channel a couple days ago and so far what I found is that iOS `13.3.1` introduced an issue with free Apple IDs.

> Are you using a non-developer Apple ID to install the app to your phone? It looks like iOS 13.3.1 has broken apps installed with free Apple IDs, but only if they contain embedded frameworks. If it's possible to link all your dependencies as static libraries rather than frameworks (for example, if you're using Cocoapods you can remove use_frameworks! from your Podfile), that should fix the issue for now.

Similar errors have been reported on multiple projects:

https://github.com/Alamofire/Alamofire/issues/3051

https://github.com/ionic-team/capacitor/issues/2383

https://github.com/evgenyneu/Cosmos/issues/157#issuecomment-579969983

https://github.com/flutter/flutter/issues/49693 

I've run my own project on another machine, with a friend's paid Developer Account and I had no issues.

So, right now I'm waiting for Apple to approve my enrollment, which has been on pending status for almost a month (I'm from Brazil).

I've tried performnthe workaround that uses `use_frameworks!` and `use_modular_headers!` on the Podfile, but I couldn't make it work with Nativescript (I not sure how to do it actually). 

If anyone has any idea perform this changes, I would appreciate the help.

**Comment by dammynex** [comment]
> @dammynex [check this SO thread ](https://stackoverflow.com/questions/32730312/reason-no-suitable-image-found/32730393#32730393)where it is suggested that the issue is related to a recently revoked certificate

Doesn't seem to be the issue.  The problem is with iOS 13.3.1

**Comment by xuhcc** [comment]
Has anyone found a workaround for this?

**Comment by NathanaelA** [comment]
Looking into this issue -- two possible solutions:
1. You need a paid developer account (i.e. not using a free apple id)
2- update the device to 13.4 beta 3.  

 This is an issue in 13.3.1 and nothing anyone outside of Apple can do anything about.
