### ISSUE TITLE
Update the default version of the AppCompat library to the latest official (1.1.0)

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#8298]
**Is your feature request related to a problem? Please describe.**

Currently, the default version that is brought by NativeScript (and the Android runtime) of the **AppCompat** library is **1.0.2.**  However, [recently Android released AppCompat **version 1.1.0**](https://developer.android.com/jetpack/androidx/releases/appcompat#1.1.0).

**Describe the solution you'd like**

Test the `tns-core-modules` against 1.1.0 and implement the new version as the default one.  This would solve issues where some plugins are using an unstable RC version (1.1.0-rc01) that is crashing NativeScript apps on navigation. As the official version is newer then the RC the Gradle build will ignore cases where a plugin requires the RC version and will use the stable 1.1.0.

Related to https://github.com/NativeScript/NativeScript/issues/7901

**Comment by erodriguezh** [comment]
Hi @NickIliev 

Any updates on when the update is going to take place?

From the [Maven repository](https://mvnrepository.com/artifact/androidx.appcompat/appcompat?repo=google) you can already see that usage of version 1.1.0 is way higher than 1.0.2
 
<img width="710" alt="Screenshot 2020-05-31 at 13 08 20" src="https://user-images.githubusercontent.com/710174/83350950-23ad0f00-a340-11ea-9327-7a9862c374f9.png">
