### ISSUE TITLE
Installation problem OSX

### ISSUE THREAD

**Issue by PoluosmakAndrew** [NativeScript/NativeScript#831]
There are a lot of errors during installation

Yosemite 10.10.5 (14F27)
Mac: 12-inch, Early 2015 (1.1 GHz Intel Core M)

Installation log file
https://drive.google.com/a/digicode.net/file/d/0B8PdNW5GOHwSdXhpRE9Zemt6M1k/view?usp=sharing

Can you help me?

**Comment by vchimev** [comment]
This issue was moved to NativeScript/nativescript-cli#970
