### ISSUE TITLE
 Failed resolving method queryRenderedFeatures on class com.mapbox.mapboxsdk.maps.MapboxMap

### ISSUE THREAD

**Issue by csimpi** [NativeScript/NativeScript#8314]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

√ Getting NativeScript components versions information...
√ Component nativescript has 6.3.3 version and is up to date.
√ Component tns-core-modules has 6.3.2 version and is up to date.
√ Component tns-android has 6.3.1 version and is up to date.
× Component tns-ios is not installed.

package.json
```
    "@nativescript/schematics": "^1.0.0",
    "@nativescript/theme": "~2.2.1",
    "nativescript-angular": "~8.20.0",
    "nativescript-mapbox-bitmads": "file:nativescript-plugins/nativescript-mapbox-bitmads/src",

    "@nativescript/schematics": "~1.0.0",
    "@nativescript/tslint-rules": "~0.0.5",
    "nativescript-dev-webpack": "~1.4.0",
```

`include.gradle` of `nativescript-mapbox-bitmads` plugin:
```
repositories {
    mavenCentral()
}

android {
}

dependencies {
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.6.2'
}
```
**Describe the bug**

I would like to use queryRenderedFeatures() method for the list of the clicked features on the mapbox map.

For this I have to Initialize the map, get the instance, set a style, add a source and a layer. Everything works well.
Then I have to add a onMapClickListener which catches the click event and returns the coordinates `LatLng`.
I have to convert these coordinates to pixels (the pixel corrdinate on the visible map):

```
    const point = event.point;
    let pixel = event.map.getProjection().toScreenLocation(point);
```

This works well, I'm getting the right pixel coordinates of the MapView.
This point I'd like to query the map based on the pixel coordinates to get the list of the clicked features:

```
event.map.queryRenderedFeatures(pixel)
```

This throws an error:
```
ERROR Error: java.lang.Exception: Failed resolving method queryRenderedFeatures on class com.mapbox.mapboxsdk.maps.MapboxMap
```

This should work here're the docs:

https://docs.mapbox.com/android/api/map-sdk/8.6.2/com/mapbox/mapboxsdk/maps/MapboxMap.html#queryRenderedFeatures-android.graphics.PointF-java.lang.String...-

https://docs.mapbox.com/android/maps/overview/query/

**To Reproduce**

```
                this.mapView.getMapAsync(new com.mapbox.mapboxsdk.maps.OnMapReadyCallback({
                    onMapReady: mbMap => {
                        console.log('onMapReady()');
                        this.map = mbMap;
                        this.notify({
                            eventName: 'mapReady',
                            object: this,
                            mapView: this.mapView,
                            map: this.map,
                        });

                        this.map.addOnMapClickListener(
                            new com.mapbox.mapboxsdk.maps.MapboxMap.OnMapClickListener({
                                onMapClick: (point) => {
                                  console.log('onMapClick',point);
                                  this.notify({
                                    eventName: 'mapClick',
                                    object: point,
                                    point: point,
                                    map: this.map,
                                  });
                                  return false;
                                }
                            })
                        );
                    }
                }));
```

`<Mapbox accessToken="{{accessToken}}" (mapReady)="mapReady($event)" (mapClick)="mapClick($event)" [camera]="{zoom:2, center:{lng:0, lat:0}}"></Mapbox>`

```
  mapClick(event){
    const point = event.point;
    let pixel = event.map.getProjection().toScreenLocation(point);
    console.log('mapClick',event.point,pixel,event.map.queryRenderedFeatures);
    console.log('FEATURES',event.map.queryRenderedFeatures(pixel));



  }
```

**Expected behavior**

**Sample project**

**Additional context**

**Comment by csimpi** [comment]
UPDATE:
In the meantime, I've got some help and figured out the workaround is:
`event.map.queryRenderedFeatures(pixel,[])`

Nativescript can't resolve (find) the method because it waits for at least two parameters.
What is interesting based on the documentation the second parameter is `Nullable` so I think NativeScript should be able to handle these situations better and resolve the corresponding method when a parameter is nullable and the user doesn't provide anything in the place of the nullable parameter.

**Comment by NickIliev** [comment]
@csimpi there are no optional parameters in Java - if the user does not provide a second parameter, you will still need to pass some value (null or empty array) to this parameter.
