### ISSUE TITLE
RadDataForm back navigation destroys iOS source binding

### ISSUE THREAD

**Issue by Noppey** [NativeScript/NativeScript#8316]
**Environment**
Update available for component nativescript. Your current version is 6.3.0.
Update available for component tns-core-modules. Your current version is 6.3.0-next-2020-02-05-134007-01
Update available for component tns-android. Your current version is 6.3.0
Component tns-ios has 6.3.0 version and is up to date.

**Describe the bug**
RadDataForm does not bind properly on iOS when navigating back to the component with the form. After navigating back, you can change values in the form fields, but these values aren't propagated into the source object.

**To Reproduce**
Open the playground project: Fill a value on "test" and click "Test" to verify. Then click "Next" to navigate away. Then click "back" and try to update the value on "test", the binding is now gone and "Test" (or anything else) won't update the value of the source variable anymore.

**Expected behavior**
Source variable should be updated after navigating back to the form and changing values.

**Sample project**
https://play.nativescript.org/?template=play-ng&id=vwLAH9&v=3

**Additional context**
iOS issue only

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-ui-feedback #1350](https://github.com/NativeScript/nativescript-ui-feedback/issues/1350) via [**ZenHub**](https://www.zenhub.com/)
