### ISSUE TITLE
iOS 1024x1024 icon not being auto generated

### ISSUE THREAD

**Issue by erwindemoel** [NativeScript/NativeScript#8318]
I've generated the icons for the App store using `tns resources generate icons`

https://docs.nativescript.org/tooling/docs-cli/project/configuration/resources/resources-generate-icons

However when I try to deploy to the App store using Xcode, I get the error saying that the required 1024x1024 icon is missing.

I would expect that it would also generate this icon and place it in `App_Resources/iOS/Assets.xcassets/AppIcon.appiconset`

I've manually added a 1024x1024 icon in that folder and also tried updating the Contents.json file with:
`{
      "size" : "1024x1024",
      "idiom" : "ios-marketing",
      "filename" : "icon-1024.jpg",
      "scale" : "1x"
    }`

This works.

Why doesn't this get generated automatically?

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #5245](https://github.com/NativeScript/nativescript-cli/issues/5245) via [**ZenHub**](https://www.zenhub.com/)
