### ISSUE TITLE
TabStripItem not respecting selectedIndex set on Tabs

### ISSUE THREAD

**Issue by tonyhogben** [NativeScript/NativeScript#8327]
**Environment**
 - CLI: 6.3.3
 - Cross-platform modules: 6.3.0
 - Android Runtime: 6.3.1
 - iOS Runtime: 6.3.0
 - Plugin(s): None

**Describe the bug**
When setting a `selectedIndex` on the `Tabs` tag as per [https://docs.nativescript.org/ui/components/tabs](https://docs.nativescript.org/ui/components/tabs), it is only respected by the `TabContentItem` and not the `TabStrip` and `TabStripItem` - these default to the first item.

Also, when returning to the page containing the `Tabs` using goBack, the `TabContentItem` is correct, but again the `TabStripItem` is not set - this would appear to be related.

**To Reproduce**
Run a simple tabs example and set the selectedIndex

**Expected behavior**
The `TabStripItem` and `TabContentItem` should respect the `selectedIndex`

**Comment by NickIliev** [comment]
Reproducible on iOS - working as expected on Android.

Steps to reproduce - use the following Playground and observe the **selectedIndex** not being set.
https://play.nativescript.org/?template=play-tsc&id=G1eEcU

**Comment by NickIliev** [comment]
Reported via t.1453726

**Comment by vmutafov** [comment]
Issue seems to be due to a missing check for `selectedIndex` and setting a given item as selected somewhere in this block of code: https://github.com/NativeScript/NativeScript/blob/master/nativescript-core/ui/tabs/tabs.ios.ts#L870

Something like this could be the fix:

``` JS
if (this.selectedIndex) {
    this.viewController.tabBar.selectedItem = tabBarItems[this.selectedIndex];
}
```

**Comment by NickIliev** [comment]
We should also verify that the fix is working in a scenario when the users **navigate back** to a page with Tabs.

Reported via t.1454990

@vmutafov ping me for a demo project that tests the above.
