### ISSUE TITLE
Sequential Animation separating animations that should be played together

### ISSUE THREAD

**Issue by Fatme** [NativeScript/NativeScript#833]
_From @sebawita on September 28, 2015 12:22_

There is a problem with sequence animations, which should be bundled up together.
Where instructions that are meant to be played together are played one by one.

The below animation sequence is executed in 4 steps instead of 2.
1)Change width to: 0.8
2) Change height to: 0.8
3) Change width to: 1.2
4) Change height to: 1.2

Instead of:
1) Change width to: 0.8 and height to: 0.8
2) Change width to: 1.2 and height to: 1.2

```
var animationModule = require("ui/animation");
var animationChain = [
                        { target: view1, scale: { x: 0.8, y: 0.8 } },
                        { target: view1, scale: { x: 1.2, y: 1.2 } }
                    ];
var animation = new animationModule.Animation(animationChain, true);
animation.play();
```

The same applies when the animation chain is based on translate.
First the component will move right and then after that it will move down.
Instead of moving across right-down.
```
animationChain = [
                        { target: view1, translate: { x: 100, y: 100 } }
                    ];
var animation = new animationModule.Animation(animationChain, true);
animation.play();
````

And finally combining multiple animations in one step doesn't seem to work either.
The below animation executes in 3 steps instead of one.
```
animationChain = [
                        { target: view1, translate: { x: 100, y: 100 } , rotate: 270}
                    ];
var animation = new animationModule.Animation(animationChain, true);
animation.play();
````

_Copied from original issue: NativeScript/nativescript-cli#973_

**Comment by hamorphis** [comment]
@sebawita In Android a separate ObjectAnimator is created for each property, i.e. setScaleX and setScaleY. Then those animators are inserted in an AnimatorSet. When you pass in **true** for playSequentially, this is the default behavior of the Android animator set -- it plays each Animator sequentially. If you want to execute these two separate animation in two steps you should do it like this:

``` TypeScript
    label.animate({ scale: { x: 0.8, y: 0.8 } })
        .then(() => label.animate({ scale: { x: 1.2, y: 1.2 } }))
        .then(() => {
            console.log("Animations finished");
        })
        .catch((e) => {
            console.log(e.message);
        });
```
If you prefer to work with the animationModule.Animation class, you will need to create two separate instances of this class -- one for each animation -- and then chain them together using the Promise that is returned from the play method of the first Animation object. Something along the lines of
``` TypeScript
var animation1 = new animationModule.Animation([{ target: view1, scale: { x: 0.8, y: 0.8 } }]);
var animation2 = new animationModule.Animation([{ target: view1, scale: { x: 1.2, y: 1.2 } }]); 
animation1.play().then(()=>animation2.play());
```
I hope this helps.
