### ISSUE TITLE
ListView itemTap animation is graphically hidden by backgroundColor

### ISSUE THREAD

**Issue by oslc15** [NativeScript/NativeScript#8332]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.3.3
 - Cross-platform modules: 6.3.2
 - Android Runtime: 6.3.1
 - iOS Runtime: 6.3.0

**Describe the bug**
Using the ListView component and setting a backgroundColor of the layout inside template causes the default selection effect to disappear on both ios and Android. I have tested with a backgroundColor with opacity and the effect seems to go behind the backgroundcolor.

**To Reproduce**

```            
<ListView.itemTemplate>
    <FlexboxLayout flexDirection="row" backgroundColor="green">
        <Image src=" {{ imageSrc }}" class="thumb img-circle" />
        <Label text="{{ name }}" class="t-12" verticalAlignment="center" style="width: 60%" /> 
    </FlexboxLayout>
</ListView.itemTemplate>
```

**Expected behavior**
Setting a backgroundColor of a view inside a listview should not ovverride the default itemTap animation.

**Sample project**
https://play.nativescript.org/?template=play-js&id=VGOPEa&v=3

**Comment by oslc15** [comment]
Maybe there is a native work arround to directly set the background to the native UITableViewCell for example?

**Comment by NickIliev** [comment]
@oslc15 check [this thread](https://github.com/NativeScript/NativeScript/issues/5842#issuecomment-390540601)- perhaps you could use the `itemLoading` to get the native iOS cell and apply a custom solution via native code.

**Comment by oslc15** [comment]
@NickIliev 
Thanks!

I got this working for ios with this code snippet. However, the setBackgroundColor of the androidCell does not seem to work as expected. Not sure that setBackgroundColor is the correct way in Android?

```
    private onItemLoading(itemEventData: ItemEventData): void {
        if (this.$isIOS) {
            const iosCell = itemEventData.ios as UITableViewCell;
            iosCell.backgroundColor = UIColor.whiteColor;
        } else {
            const androidCell = itemEventData.android as android.view.View;
            androidCell.setBackgroundColor(android.R.color.white);
        }
    }
```

**Comment by NickIliev** [comment]
@oslc15 instead of `android.R.color.white` try passing the color as follows:
```TypeScript
import { Color } from "tns-core-modules/ui/color";

let redColor = new Color("red");

androidCell.setBackgroundColor(redColor.android); // note that I am passing the native Android color
```

**Comment by oslc15** [comment]
Works as expected. Thanks for the help!

```
    private onItemLoading(itemEventData: ItemEventData): void {
        const whiteColor: Color = new Color('white');

        if (this.$isIOS) {
            const iosCell = itemEventData.ios as UITableViewCell;
            iosCell.backgroundColor = whiteColor.ios;
        } else {
            const androidCell = itemEventData.android as android.view.ViewGroup;
            androidCell.setBackgroundColor(whiteColor.android);
        }
    }
```

**Comment by NickIliev** [comment]
@oslc15 you could change the approach and apply a background color for the whole list view. Then set the opacity of the cells to 100% (`opacity = 1`) and use the inner nested element if you need further styling.

For example, see[ this modified Playground](https://play.nativescript.org/?template=play-js&id=VGOPEa&v=5). The demo has preserved the ripple effect for the list view cells while in the same time I am able to apply custom styles for the nested labels.

**Comment by oslc15** [comment]
@NickIliev the issue with that approach is that the lightblue backgroundColor of the label is overriding the ripple-effect, so if the label would have been 100% width and height of the cell you would not be able to see the Ripple effect any longer.

**Comment by NickIliev** [comment]
@oslc15 well that is to be expected as the ripple effect in Android is created via drawable resources. Using a background-color is practically overwriting these resources. 

You could create your own ripple effect using[ this plugin](https://www.npmjs.com/package/nativescript-ripple)

**Comment by oslc15** [comment]
@NickIliev Alright i understand. I managed to solve my specific issue like this:
https://play.nativescript.org/?template=play-vue&id=parC1G&v=8

The original goal was to have a grey color underneath the list in both ios and android if the elements does not fill the screen, but still keep the native animation of a selection.

**Comment by pianocomposer321** [comment]
@oslc15 How did you solve this? The link you pasted just takes me to the main play.nativescript.org page, not your example :/

**Comment by vallemar** [comment]
@pianocomposer321 use ripple plugin to create the effect on tap https://github.com/nativescript-community/ui-material-components

**Comment by CatchABus** [comment]
@pianocomposer321 @vallemar I think there's a native setter to achieve this. https://developer.android.com/reference/android/widget/AbsListView#setDrawSelectorOnTop(boolean)

By setting this to true, ripple effect should be drawn on top of background color.

**Comment by pianocomposer321** [comment]
Thanks @CatchABus! I was able to achieve what I wanted by changing the color through the theme scss variables instead of the css property directly. But I'll look into this if I need to as well.

On a related note, does anyone know how to change the color of the ripple effect? I couldn't find a theme variable for that, and I don't really know what terms to use to search for it.

I can open a second issue if that's better too.

**Comment by pianocomposer321** [comment]
> @pianocomposer321 @vallemar I think there's a native setter to achieve this on android. https://developer.android.com/reference/android/widget/AbsListView#setDrawSelectorOnTop(boolean)
> 
> By setting this to true, ripple effect should be drawn on top of background color.
> Other than that, creating the effect on tap is also a good approach.

Also how would I use this method? How do I call it from native script, specifically using svelte?
