### ISSUE TITLE
I cannot open Modal page after update 6.4.0

### ISSUE THREAD

**Issue by sanghyunj5958** [NativeScript/NativeScript#8333]
**Environment**
Provide version numbers for the following components (information can be retrieved by running tns info in your project folder or by inspecting the package.json of the project):

CLI: 6.3.3
Cross-platform modules:  6.4.0
Android Runtime:  6.4.1
iOS Runtime:  6.4.0

**Describe the bug**
I've got the errors below after update 6.4.0 when I click one of the listviews to open modal page.

> CONSOLE ERROR file:///node_modules/@nativescript/core/trace/trace.js:174:0: Error: Css styling failed: Error: Unknown node type Raw
> CONSOLE ERROR file:///node_modules/@angular/core/fesm5/core.js:4002:0: ERROR Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'inlineRuleSet[0].declarations')
> applyInlineStyle(file:///node_modules/@nativescript/core/ui/styling/style-scope.js:757:0)
> at file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:617:0
> at set(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:162:0)
> at file:///node_modules/@nativescript/angular/view-util.js:279:0
> at file:///node_modules/@nativescript/angular/view-util.js:263:0
> at file:///node_modules/@nativescript/angular/renderer.js:170:0
> at file:///node_modules/@angular/platform-browser/fesm5/animations.js:234:0
> at file:///node_modules/@angular/core/fesm5/core.js:30441:0
> at createElement(file:///node_modules/@angular/core/fesm5/core.js:28428:0)
> at createViewNodes(file:///node_modules/@angular/core/fesm5/core.js:29348:0)
> at callViewAction(file:///node_modules/@angular/core/fesm5/core.js:29703:0)
> at execComponentViewsAction(file:///node_modules/@angular/core/fesm5/core.js:29622:0)
> at createViewNodes(file:///node_modules/@angular/core/fesm5/core.js:29415:0)
> at createRootView(file:///node_modules/@angular/core/fesm5/core.js:29301:0)
> at callWithDebugContext(file:///node_modules/@angular/core/fesm5/core.js:30309:0)
> at file:///node_modules/@angular/core/fesm5/core.js:20506:0
> at file:///node_modules/@angular/core/fesm5/core.js:20617:0
> at file:///node_modules/@nativescript/angular/common/detached-loader.js:21:0
> at file:///node_modules/@nativescript/angular/common/detached-loader.js:35:0
> at file:///node_modules/@nativescript/angular/directives/dialogs.js:89:0
> at file:///app/ven<…>

**To Reproduce**
```JavaScript
   onItemTap(args: ListViewEventData, type: string): void {
         this._isLoading = true;
         this._mainService.loadQueryByID(args.view.bindingContext.id, type).subscribe((girls: Girl) => {
             if (girls[0]) {
                 girls[0].type = type;
                 const options: ModalDialogOptions = {
                     viewContainerRef: this._vcRef,
                     context: girls[0],
                     fullscreen: true
                 };
 
                 this._modalService.showModal(MainDetailComponent, options).then((result: any) => {
                     this.onRefreshTapped();
                 });
             }
         });
     }
```
Expected behavior
Open Modal page

**Comment by NickIliev** [comment]
@sanghyunj5958 works as expected on my side - here is [a Playground test app](https://play.nativescript.org/?template=play-ng&id=VRHVdj) for reference.

**Comment by NickIliev** [comment]
Working on my side with 6.4.0 - here is [a Playground demo ](https://play.nativescript.org/?template=play-ng&id=VRHVdj)for reference (make sure to update the **Preview** app to work with 6.4.0).

**Comment by sanghyunj5958** [comment]
@NickIliev Thank you for your reply. it was my fault. one of my lines was

>   <Label row="0" rowSpan="2" col="1" text="" borderRadius="100%" height="50" width="50" style="border-width: 2; border-color: #ff4b60;;"></Label>
like this.. so I change ;; to ; and work fine!
