### ISSUE TITLE
[Tabs] Not able to change title for TabStripItem on iOS

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#8340]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.4.0
 - Cross-platform modules: 6.4.0
 - Android Runtime:6.4
 - iOS Runtime:6.4

**Describe the bug**

When accessing TabStripItem we can't change the title value on iOS (works as expected on Android)
```JavaScript
    tabs.tabStrip.items[0].title = "ITEM 1";
    tabs.tabStrip.items[1].title = "ITEM 22";
    tabs.tabStrip.items[2].title = "ITEM 333";
```

**To Reproduce**
[Use this Playground](https://play.nativescript.org/?template=play-tsc&id=XR9KDy&v=2) and press the button to trigger the title change. Works on Android - not working on iOS.

Reported via t. 1453730

**Comment by NickIliev** [comment]
Possibly related to https://github.com/NativeScript/NativeScript/issues/7455

**Comment by NickIliev** [comment]
The issue is also happening when trying to set the **src** property of **image** (works on Android - doesn't work on iOS)

For example:
```JavaScript
parentComponent.tabStrip.items[1].image.src = 'res://map_icon';
```

**Comment by vtrifonov** [comment]
> ```js
> parentComponent.tabStrip.items[1].image.src = 'res://map_icon';
> ```

you should use the following instead:
```js
parentComponent.tabStrip.items[1].imageSrc = 'res://map_icon';
```
