### ISSUE TITLE
Tabs with swipeEnabled="false" is crashing the app on iOS

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#8344]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.4.0
 - Cross-platform modules:6.4.0
 - Android Runtime:6.4
 - iOS Runtime:6.4

**Describe the bug**

App crashes when using `Tabs` with `swipeEnabled="false"`

**To Reproduce**
Run this test https://github.com/NativeScript/NativeScript/blob/dfcbe6c319485b87c0d619b075f661f769316c8d/e2e/ui-tests-app/app/tabs/swipe-disabled-page.xml

**Expected behavior**
To work

**Sample project**
The e2e test app https://github.com/NativeScript/NativeScript/blob/dfcbe6c319485b87c0d619b075f661f769316c8d/e2e/ui-tests-app/app/tabs/swipe-disabled-page.xml

**Additional context**
Works on Android

reported via t. 1453727

**Comment by lambourn** [comment]
@NickIliev do you happen to know which PR includes this fix?
