### ISSUE TITLE
Tabs/listview navigation troubles on IOS

### ISSUE THREAD

**Issue by qwixilver** [NativeScript/NativeScript#8349]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.4.0
 - Cross-platform modules: N/A
 - iOS Runtime: 6.4.0
 - Android Runtime (if applicable):6.4.1
 - Plugin(s):N/A

**Describe the bug**
When using tabs to navigate to a page that has a listview by tapping on the tab (as opposed to using a gesture, or swipe), navigation occurs but you cannot subsequently navigate to other tabs by tapping. 

**To Reproduce**
Once the app loads, immediately tap on the 'archives' tab at the top of the app.  **Please ensure you tap and do not use gestures to swipe to the tab or you will not reproduce the bug.** Once on the 'archives' tab, try tapping to navigate to any other tab, and you will see that you cannot. However swiping navigation does work, and after successfully navigating by gestures, tap navigation also begins to work as expected.

<img width="375" alt="IMG_0001" src="https://user-images.githubusercontent.com/7517933/74565674-c4b5bc80-4f3f-11ea-8f66-7b8f5463e385.PNG">

<img width="375" alt="IMG_0002" src="https://user-images.githubusercontent.com/7517933/74565672-c41d2600-4f3f-11ea-9f53-5c1d1bb783f7.PNG">

**Expected behavior**
Navigation works regardless of input method. Tapping vs swiping should not make any difference at any stage of app development.

**Sample project**
https://play.nativescript.org/?template=play-js&id=ggNCqV&v=7

**Additional context**
This does not happen on Android. It occurs only on IOS

**Comment by NickIliev** [comment]
@qwixilver [the issue is logged here](https://github.com/NativeScript/NativeScript/issues/7827) (duplicate.

The fix is upcoming via [this PR](https://github.com/NativeScript/NativeScript/pull/8353)
