### ISSUE TITLE
takePicture does not generate event

### ISSUE THREAD

**Issue by vicmasa** [NativeScript/NativeScript#8351]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: "~6.3.0"
 - Cross-platform modules: 
 - Android Runtime: "6.3.1"
 - iOS Runtime: "6.3.0"
 - Plugin(s): "@nstudio/nativescript-camera-plus": "^3.0.5"

**Describe the bug**
Hello everyone, when invoking "take Picture", the event is not detected and images and videos cannot be captured.
I enclose an isolated project where you can see the error.
Greetings.
https://github.com/nstudio/nativescript-camera-plus/issues/113

**To Reproduce**
Clic in botton "Get Image"
https://github.com/vicmasa/testbg

**Comment by NickIliev** [comment]
@vicmasa you are actually [creating the events](https://github.com/vicmasa/testbg/blob/master/app/main-page.js#L15-L25) when[ the tap is triggered](https://github.com/vicmasa/testbg/blob/master/app/main-page.js#L11). You can't expect to trigger an event that had already happened.

Just move the events outside the tap callback (e.g. in some of the application lifecycle events.)

**Comment by vicmasa** [comment]
Thanks for your help, I made the corrections, but the event does not always take place on the device, in some cases it works and in others it does not. It works perfect with the secondary camera, but not the main one.

**Note:** I used a Huawei p20 PRO device (40MP main camera)

https://github.com/vicmasa/ns-camera-plus-vanilla.git
