### ISSUE TITLE
XMLHttpRequest throws "Event not supported: readystatechange"

### ISSUE THREAD

**Issue by m-abs** [NativeScript/NativeScript#8357]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.4.0
 - Cross-platform modules: 6.4.0
 - Android Runtime: 6.4.1
 - iOS Runtime: 6.4.0
 - Plugin(s):

**Describe the bug**

We're using sentry to track errors in our app and a recent update to their packages adds an event listener for `readystatechange`.
Nativescript implementation of `XMLHttpRequest` throw an Error "Event not supported: readystatechange" on every request we make.
Caused by:
https://github.com/NativeScript/NativeScript/blob/master/nativescript-core/xhr/xhr.ts#L179-L187

Even though the event is emitted by `XMLHttpRequest`:
https://github.com/NativeScript/NativeScript/blob/master/nativescript-core/xhr/xhr.ts#L158
https://github.com/NativeScript/NativeScript/blob/master/nativescript-core/xhr/xhr.ts#L172

**To Reproduce**

Create an instance of `XHRHttpRequest` and add an event listener for `readystatechange`.

```javascript
function reqListener () {
  console.log(this.responseText);
}

function reqReadyState() {
   /// DO STUFF
}

var oReq = new XMLHttpRequest();
oReq.addEventListener("load", reqListener);
oReq.addEventListener("readystatechange", reqReadyState); // <<--- this throws an error
oReq.open("GET", "http://www.example.org/example.txt");
oReq.send();
```

**Expected behavior**
I'd expect add `addEventListener` to allow listening for `readystatechange` without throwing an error.

**Sample project**

**Additional context**

**Comment by NickIliev** [comment]
Resolved via https://github.com/NativeScript/NativeScript/pull/8362/

**Comment by m-abs** [comment]
Since the PR have been merged, I'll close the issue.
Thank you for responding so quickly.
