### ISSUE TITLE
TabView crashes with "Changing the view of an already loaded TabViewItem is not currently supported"

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#836]
All I want to do is put a different listview in each tab, but the subject shows the error I get.

Heck I can't even have 2 tabs with a search bar in each without the error being thrown (like the Slack app).  If I remove the search bar from Tab 1 it renders, and I see the search bar in Tab 2....??? 
```
 <TabView>
   <TabView.items>
     <TabViewItem title="Resources">
       <TabViewItem.view>
            <SearchBar text="Search" hint="Search" cssClass="search" textFieldBackgroundColor="white" id="searchAll"/>
            <ActivityIndicator horizontalAlignment="center" busy="{{ isLoading }}"/>
       </TabViewItem.view>
     </TabViewItem>
     <TabViewItem title="Favourites">
       <TabViewItem.view>
          <SearchBar text="Search" hint="Search" cssClass="search" textFieldBackgroundColor="white" id="searchFavs"/>
       </TabViewItem.view>
     </TabViewItem>
   </TabView.items>
 </TabView>
```
Screenshot
https://goo.gl/photos/7DSj5Vu8uEZizZzg8

**Comment by sitefinitysteve** [comment]
Okay, so I don't know what the deal is...this has been crashing all day, suddenly it works with zero code changed... ??

**Comment by nsndeck** [comment]
The problem goes away if you remove the ActivityIndicator control or at least wrap SearchBar and ActivityIndicator of the first TabViewItem in any layout e.g. `StackLayout`.

**Comment by gordonpro** [comment]
The problem is the `TabViewItem.view` could only have one child. the child could be a layout.

**Comment by RusEu** [comment]
thanks gordonpro .. you saved my day
