### ISSUE TITLE
[Only problem in iOS 13] Connection problem with httpclient post with common angular

### ISSUE THREAD

**Issue by juan-rodriguez-dev-shareppy** [NativeScript/NativeScript#8360]
Good, there is a connection problem in **iOS 13** using angular common _httpclient_, this is only presented in this version of iOS.

This is the part of the code that is responsible for using httpclient to consume a service.
```
public doRequest(serviceName: String, data: any): any {
        let headers: HttpHeaders;
        let dataQs: any;
        headers = this.createHeader();
        dataQs = this.toQueryString(data);
        if (serviceName.indexOf("geo") != -1){
            this.serverUrl = "https://mydomain.com/api";
        }else{
            this.serverUrl = "https://mydomain.com/api/fc";
        }
        return this.http.post(`${this.serverUrl}${serviceName}`, dataQs, {
            headers: headers
        });
    }
```

- nativescript has 6.4.0
- tns-core-modules has 6.4.1
- tns-android has 6.4.1
- tns-ios has 6.4.2
- iOS 13 version problem
- iOS 12 version "ok"

Plugin                                  │ Version        │
│ @angular/animations                     │ ~8.2.0         │
│ @angular/common                         │ ~8.2.0         │
│ @angular/compiler                       │ ~8.2.0         │
│ @angular/core                           │ ~8.2.0         │
│ @angular/forms                          │ ~8.2.0         │
│ @angular/http                           │ ~8.0.0-beta.10 │
│ @angular/platform-browser               │ ~8.2.0         │
│ @angular/platform-browser-dynamic       │ ~8.2.0         │
│ @angular/router                         │ ~8.2.0         │
│ @nativescript/schematics                │ ^0.7.1         │
│ @nstudio/nativescript-checkbox          │ ^1.0.0         │
│ @nstudio/nativescript-loading-indicator │ ^2.0.0         │
│ @schematics/angular                     │ ^8.3.14        │
│ nativescript-advanced-permissions       │ ^1.2.0         │
│ nativescript-angular                    │ ^8.21.0        │
│ nativescript-bitmap-factory             │ ^1.8.1         │
│ nativescript-crossplatform-aes          │ ^1.0.3         │
│ nativescript-cscreenshot                │ ^1.0.2         │
│ nativescript-datetimepicker             │ ^1.2.1         │
│ nativescript-drop-down                  │ ^5.0.4         │
│ nativescript-exit                       │ ^1.0.1         │
│ nativescript-fancyalert                 │ ^3.0.9         │
│ nativescript-fingerprint-auth           │ ^7.0.2         │
│ nativescript-geolocation                │ ^5.1.0         │
│ nativescript-google-maps-sdk            │ ^2.8.1         │
│ nativescript-modal-datetimepicker       │ ^1.2.0         │
│ nativescript-permissions                │ ^1.3.8         │
│ nativescript-phone                      │ ^1.4.0         │
│ nativescript-social-share               │ ^1.5.2         │
│ nativescript-status-bar                 │ ^1.2.0         │
│ nativescript-theme-core                 │ ~1.0.6         │
│ nativescript-ui-sidedrawer              │ ~7.0.0         │
│ npm                                     │ ^6.13.6        │
│ reflect-metadata                        │ ~0.1.12        │
│ rxjs                                    │ ^6.4.0         │
│ tns-core-modules                        │ ^6.4.1         │
│ zone.js                                 │ ^0.9.1 

Dev Dependencies:
┌──────────────────────────┬─────────┐
│ Plugin                   │ Version │
│ @angular/compiler-cli    │ ~8.2.0  │
│ @ngtools/webpack         │ ~8.2.0  │
│ codelyzer                │ ~4.5.0  │
│ nativescript-dev-webpack │ ^1.5.0  │
│ node-sass                │ ^4.13.1 │
│ tslint                   │ ~5.11.0 │
│ typescript               │ ~3.5.3  │
└──────────────────────────┴─────────┘
I would like to know if someone else has been presented the same with this version using httpcliente of common angular. Thanks for the help.

**Comment by NickIliev** [comment]
@juan-rodriguez-dev-shareppy are you receiving a connection error or some kind of runtime crash?  Are there any logs related to that error? Currently, the information is not enough to say what might be causing your issue. The best approach would be to try to isolate the case in a sample application that you can share for further investigation.

**Comment by juan-rodriguez-dev-shareppy** [comment]
I receiving a connection error, The problem occurs precisely at these points respectively, one is the loading of points on a map and the other is the login to the application:
load points service:
![image](https://user-images.githubusercontent.com/57687238/75041629-f7edd380-548a-11ea-93bd-9a2f974cec6d.png)

login service:
![image](https://user-images.githubusercontent.com/57687238/75041554-c70d9e80-548a-11ea-9678-5ab52a43d798.png)

at both points the flow stops and does not continue, does not throw any console errors, nor does it stop.
