### ISSUE TITLE
Multiple activities created on 6.4.0 resulting in crash 

### ISSUE THREAD

**Issue by edusperoni** [NativeScript/NativeScript#8364]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.4.0
 - Cross-platform modules: 6.4.1
 - Android Runtime: 6.4.1

**Describe the bug**
https://github.com/NativeScript/nativescript-angular/issues/2125
6.4.0 (notice second activityCreated):
```
JS: Event: activityCreated, Activity: com.tns.NativeScriptActivity@eedd28e, Bundle: null
JS: calling constructor for DummyService!
JS: calling constructor for LoggerService!
JS: calling constructor for HomeComponent!
JS: Event: activityStarted, Activity: com.tns.NativeScriptActivity@eedd28e
JS: Event: activityResumed, Activity: com.tns.NativeScriptActivity@eedd28e
JS: Event: activityPaused, Activity: com.tns.NativeScriptActivity@eedd28e
JS: Event: activityStopped, Activity: com.tns.NativeScriptActivity@eedd28e
JS: Event: saveActivityState, Activity: com.tns.NativeScriptActivity@eedd28e, Bundle: Bundle[{android:viewHierarchyState=Bundle[{android:views={1=android.view.AbsSavedState$1@1d1f671, 16908290=android.view.AbsSavedState$1@1d1f671, 2131230764=android.view.AbsSavedState$1@1d1f671, 2131230775=android.view.AbsSavedState$1@1d1f671}}], android:lastAutofillId=1073741823, android:fragments=android.app.FragmentManagerState@be28c56}]
JS: running instance with id: 422
JS: Event: activityCreated, Activity: com.tns.NativeScriptActivity@5d4b706, Bundle: null
JS: calling constructor for DummyService!
JS: calling constructor for LoggerService!
JS: calling constructor for HomeComponent!
JS: Event: activityStarted, Activity: com.tns.NativeScriptActivity@5d4b706
JS: Event: activityResumed, Activity: com.tns.NativeScriptActivity@5d4b706
```

6.3.1 (activity is resumed instead of created):
```
JS: Event: activityCreated, Activity: com.tns.NativeScriptActivity@610d7cf, Bundle: null
JS: calling constructor for DummyService!
JS: calling constructor for LoggerService!
JS: calling constructor for HomeComponent!
JS: Event: activityStarted, Activity: com.tns.NativeScriptActivity@610d7cf
JS: Event: activityResumed, Activity: com.tns.NativeScriptActivity@610d7cf
JS: Event: activityPaused, Activity: com.tns.NativeScriptActivity@610d7cf
JS: Event: activityStopped, Activity: com.tns.NativeScriptActivity@610d7cf
JS: Event: saveActivityState, Activity: com.tns.NativeScriptActivity@610d7cf, Bundle: Bundle[{android:viewHierarchyState=Bundle[{android:views={3=android.view.AbsSavedState$1@8bd8399, 16908290=android.view.AbsSavedState$1@8bd8399, 2131230764=android.view.AbsSavedState$1@8bd8399, 2131230775=android.view.AbsSavedState$1@8bd8399}}], android:lastAutofillId=1073741823, android:fragments=android.app.FragmentManagerState@81fd65e}]
JS: Event: activityStarted, Activity: com.tns.NativeScriptActivity@610d7cf
JS: Event: activityResumed, Activity: com.tns.NativeScriptActivity@610d7cf
```

Additionally, the app will crash when the back button is pressed.

**To Reproduce**
Open app
press home
Open app again (via home screen, not recent screen)
check that a new activity is created
press back and see it crash

**Expected behavior**
Activity reused and app does not crash

**Sample project**
DOES NOT WORK ON PLAYGROUND!
https://play.nativescript.org/?template=play-ng&id=49IDvC&v=9

**Comment by NickIliev** [comment]
@edusperoni the thing is the app (once downloaded) lack a `launchMode` flag in the AndroidManifest.xml (the Playground uses different **AndroidManifest.xml** from the Preview app). So when this flag is missing it is actually being set to **standard**.

Using any of the other options for launchMode will reoslve your issue:

For example:
```
android:launchMode="singleTask"
```

`singleTask` or `singleTop` or `singleInstance` (more [here](https://android.jlelse.eu/android-activity-launch-mode-e0df1aa72242)).

Not sure if NativeScript is expected to work with the **standard** option.

**Comment by edusperoni** [comment]
@NickIliev indeed that fixes the problem. I tried that, but on the wrong section of the manifest, oops. For some reason it worked by downgrading @nativescript/core for me, leading me to believe it was a bug, but I can't reproduce that anymore.

Thanks!

**Comment by jessorlisa** [comment]
@NickIliev 

> Not sure if NativeScript is expected to work with the standard option which is creating new activity each time you start the app. (it is obviously not working now).

If it is necessary to set the launchMode to anything but the default, would it then not be a good idea to incorporate that into the start templates? I tried any combination of options available via `tns create` and none seems to be adding the launchMode flag.
