### ISSUE TITLE
Tabs missalign with two tabStripItem

### ISSUE THREAD

**Issue by dyane91** [NativeScript/NativeScript#8369]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.4.0
 - Cross-platform modules: 6.3.2
 - Android Runtime: 6.4.1
 - iOS Runtime: 6.4.2
 - Plugin(s):
```
    "nativescript-angular": "^8.21.0",
    "nativescript-camera": "^4.5.0",
    "nativescript-carousel": "^6.1.1",
    "nativescript-plugin-firebase": "^10.3.3",
    "nativescript-theme-core": "^2.0.24",
    "nativescript-ui-autocomplete": "^6.0.0",
    "nativescript-ui-listview": "^8.0.1",
```

**Describe the bug**
new Tabs component doesn't resize properly when there are only 2 `TabStripItem`.

**To Reproduce**
I have created a playground demo [here](https://play.nativescript.org/?template=play-ng&id=bM2SFv).
As you can see, the tabs displays as this:

![Screenshot 2020-02-23 at 1 48 18 AM](https://user-images.githubusercontent.com/48399922/75105077-d43ba200-55de-11ea-870a-ab3bd1c095f4.jpg)

**Expected behavior**
It should align the only two tabs in the middle. 

**Sample project**
[here](https://play.nativescript.org/?template=play-ng&id=bM2SFv).

**Comment by NickIliev** [comment]
@dyane91 we are currently working on some major improvements related to the **Tabs** component and one of them is providing an iOS-specific property that will allow you to **_justify_** the tab strip items. There will also be an option to preserve the current behavior (both are natively supported by MDCTabBar)

**Comment by dyane91** [comment]
Thanks @NickIliev . 
Based on your PR, I noticed that it should be ready soon. Do you know if this is going to be for tns 6.5.0?

Thanks!

**Comment by abdullahkhalidmahmood** [comment]
I am still facing this issue. Any way to fix it now ?

**Comment by farfromrefug** [comment]
@abdullahkhalidmahmood can you try with `@nativescript-community/ui-material-tabs` ? It is a port of the N component with updated native libs

**Comment by abdullahkhalidmahmood** [comment]
@farfromrefug I installed the plugin `tns plugin add @nativescript-community/ui-material-tabs`, however i received an error  
`CocoaPods could not find compatible versions for pod "MaterialComponents/Tabs+TabBarViewTheming":
  In Podfile:
    MaterialComponents/Tabs+TabBarViewTheming
`
I did `pod repo update` as well but i am unable to use this plugin

**Comment by abdullahkhalidmahmood** [comment]
I am still facing this issue, i have empty white space on the left. I tried using `OSTabBarItemsAlignment` but still no change!
