### ISSUE TITLE
[iOS] Newly generated NativeScript Vue project crashing

### ISSUE THREAD

**Issue by bbc91** [NativeScript/NativeScript#8373]
**Environment**
 - CLI: 6.4.0
 - Cross-platform modules: 6.4.1
 - Android Runtime:
 - iOS Runtime: 6.4.2
 - Plugin(s): It's a clean SideDrawer project. Also tried with a "Simple" project.

**Describe the bug**
I'm creating a NativeScript Vue project with `vue init nativescript-vue/vue-cli-template <project-name>` with "Simple" template and also tried with SideDrawer template, but after installing it on my iPad device with iOS 13.3.1 version the app just flashes the launch screen and then closes. 
No errors in the terminal. 

**To Reproduce**
1. Run vue init nativescript-vue/vue-cli-template <project-name>`
2. `cd <project-name>` npm install
3. `tns run ios --bundle`
4. The app prepares successfully, xcode builds successfully.
5. Installs successfully on the iPad device.
6. Refreshing the application and closing on the launch screen.

**Expected behavior**
To open the newly created clean app.

**Additional context**
I opened the prepared project in Xcode and also built it from there, and installed on the tabled, and the same crash is happening, but got an error this time.

`dyld`__abort_with_payload:
    0x100b4f5dc <+0>:  mov    x16, #0x209
    0x100b4f5e0 <+4>:  svc    #0x80
->  0x100b4f5e4 <+8>:  b.lo   0x100b4f600               ; <+36>
    0x100b4f5e8 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x100b4f5ec <+16>: mov    x29, sp
    0x100b4f5f0 <+20>: bl     0x100b4dbe8               ; cerror_nocancel
    0x100b4f5f4 <+24>: mov    sp, x29
    0x100b4f5f8 <+28>: ldp    x29, x30, [sp], #0x10
    0x100b4f5fc <+32>: ret    
    0x100b4f600 <+36>: ret   `

**Comment by NickIliev** [comment]
@bbc91 please report and track this issue in [the nativescript-vue repository](https://github.com/nativescript-vue/nativescript-vue).

You could also open the built project via XCode and obtain more verbose error log from XCOde.

**Comment by vpiskunov** [comment]
Same issue here, but using the Tab-navigation type for project, this makes xcode build fail in `tns run ios` but also, if I open the project inside XCode, it fully crashes (XCode as a whole, UI & everything) - it just quits it! then a minute later I get "XCode quit unexpectedly"

Log is here:
https://gist.github.com/vpiskunov/2966ace8e253d3eb93ddaffce079be0b

Any ideas? I can go back to old versions (1-2 years old) and take base code from there (those build well), but starting a new project, needed new codebase...
