### ISSUE TITLE
[modal] ns-dark not applied to top element

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/NativeScript#8374]
I am using latest of everything

If you run the attached example:
* click the button => opened page is not themed but child label is
* change the code to open modal `modalFrame/modalFrame` 
* click the button => opened page is themed but child label is
[NSPlayground 2.zip](https://github.com/NativeScript/NativeScript/files/4244537/NSPlayground.2.zip)

I think the issue is that the top/root view opened in modal is not applied ns-dark.

I also see that behavior in my `nativescript-material-bottomsheet` and `nativescript-material-dialogs` when i show custom view inside dialog or bottom sheet.
https://github.com/Akylas/nativescript-material-components/blob/2ed3d870bdce10e66fa2bcda4d936da499690f39/src/bottomsheet/bottomsheet-common.ts#L134
BTW it happens on both platforms

**Comment by NavruzbekNoraliev** [comment]
same issue, bottom sheet doesn't read ns dark styles

**Comment by Bezlepkin** [comment]
Same issue in modalDialog....
