### ISSUE TITLE
Lable  Text  are not populating in IOS real device in Iphone XS 13.3.1

### ISSUE THREAD

**Issue by kranthi-kiki** [NativeScript/NativeScript#8376]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules: 6.1.1
 - Android Runtime: 6.2.0
 - iOS Runtime: 6.2.0
 - Plugin(s):
@nstudio/nativescript-cardview": "^1.0.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "@nstudio/nativescript-loading-indicator": "^1.0.0",
    "@nstudio/nativescript-pulltorefresh": "^1.0.1",
    "@nstudio/nativescript-snackbar": "^1.0.0",
    "nativescript-appversion": "^1.4.4",
    "nativescript-fancyalert": "^3.0.8",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-mediafilepicker": "^2.0.17",
    "nativescript-plugin-firebase": "^10.3.3",
    "nativescript-sqlite": "^2.3.3",

**Describe the bug**
**we are developing Mobile apps  in nativescript angular 6.2.0
as shown in below images text in lable not visible in ios real device , working perfectly in xcode ios simuator** 

IOS  simulator
![image](https://user-images.githubusercontent.com/46471488/75249837-0b879a00-57fd-11ea-8892-0aff1414fd37.png)

Real device
![image](https://user-images.githubusercontent.com/46471488/75249879-20642d80-57fd-11ea-844b-d20f891cc1b7.png)

**To Reproduce**

**Expected behavior**

**Sample project**
**Additional context**

**Comment by mattkenefick** [comment]
What was the solution here?

**Comment by kranthi-kiki** [comment]
By default label text will take black color  if not declared any color. but for IOS it's taking white color. so for my problem i assigned black color using CSS
