### ISSUE TITLE
Difference between multiple devices in font icon size

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/NativeScript#8391]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.3.3
 - Cross-platform modules: 6.2.3 
 - Android Runtime: 6.2.0
 - Plugin(s):

**Describe the bug**
There is a difference between multiple devices in font icon size (in actionbar). As following:

![font-size](https://user-images.githubusercontent.com/11078601/75456348-a9ab6980-598f-11ea-9d90-5c59702920ed.jpg)

**To Reproduce**

```XML
<ActionBar class="saz-action-bar">
    <NavigationButton icon="font://&#xf013;" class="fa actionbar-setting" ios:visibility="collapsed"></NavigationButton>
</ActionBar>
```

**Expected behavior**
To have a same icon size.

**Comment by NickIliev** [comment]
@vahidvdn there is not enough information provided to investigate the issue.

Consider providing a sample project that uses the fonts behind the shown CSS classes and also clarify what are the API levels on the pictures.
