### ISSUE TITLE
Nativescript nested RadListView does not render on iOS 13

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/NativeScript#8392]
In my NS Core 6.3 app, I have nested RadListViews to display related items. The outer RadListView displays properly, but the nested one does not display at all. Here is my code:

```
<GridLayout row="1" rows="*" columns="*">
    <lv:RadListView items="{{ asks }}">
        <lv:RadListView.itemTemplate>
            <StackLayout>
                ...

                <GridLayout rows="*" columns="auto" marginTop="10">

                    <lv:RadListView items="{{ recs }}">
                        <lv:RadListView.listViewLayout>
                            <lv:ListViewLinearLayout scrollDirection="Horizontal" />
                        </lv:RadListView.listViewLayout>
                        <lv:RadListView.itemTemplate>
                            ...
                        </lv:RadListView.itemTemplate>
                    </lv:RadListView>
                </GridLayout>
            </StackLayout>
        </lv:RadListView.itemTemplate>
    </lv:RadListView>
</GridLayout>
```

If I replace the inner RadListView with a Repeater, the items render, but I cannot scroll through them horizontally.

Note that this code works as expected on Android.

Am I missing a setting or something?

Thank you.

**Comment by NickIliev** [comment]
@dpdragnev there could be multiple reasons for your issue to appear but without a sample project it is hard to tell what is causing this one. Check the following:

- On iOS, the item template should have a predefined height. Try to give the outer StackLayout some height. Or give some height for the outer layout that creates the template.

- What is the height for the whole row that contains the Grid that contains the RadListView (make sure it is not set with some auto height) `<GridLayout row="1" rows="*" columns="*">`

**Comment by NickIliev** [comment]
Btw you are not supposed to nest on RLV inside another RLV (or even LV)
