### ISSUE TITLE
Text label not getting displayed in IOS device with OS version 13.3.1

### ISSUE THREAD

**Issue by kranthi-kiki** [NativeScript/NativeScript#8394]
Cross-platform modules: 6.1.1
Android Runtime: 6.2.0
iOS Runtime: 6.2.0
Plugin(s):
@nstudio/nativescript-cardview": "^1.0.0",
"@nstudio/nativescript-checkbox": "^1.0.0",
"@nstudio/nativescript-loading-indicator": "^1.0.0",
"@nstudio/nativescript-pulltorefresh": "^1.0.1",
"@nstudio/nativescript-snackbar": "^1.0.0",
"nativescript-appversion": "^1.4.4",
"nativescript-fancyalert": "^3.0.8",
"nativescript-iqkeyboardmanager": "^1.5.1",
"nativescript-mediafilepicker": "^2.0.17",
"nativescript-plugin-firebase": "^10.3.3",
"nativescript-sqlite": "^2.3.3",

**Describe the bug**
Text label is not getting displayed in  ios latest model mobiles [real device ]. working good in xcode ios simulator.

 In Simulator::::
---------------------
![image](https://user-images.githubusercontent.com/46471488/75546637-f99d3580-5a4e-11ea-8896-270084827a2f.png)

In IOS XS 13.3.1 
----------------------------
![image](https://user-images.githubusercontent.com/46471488/75546667-12a5e680-5a4f-11ea-90ca-a8735173b2c4.png)

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by jerbob92** [comment]
@kranthi-kiki can you explain what the issue was here?

**Comment by kranthi-kiki** [comment]
In IOS[iphone] new device [XR, 11, 11 pro with version 13.3.1 ] if you not give css colour [in my case Black]  white colour is taking as default colour. actually in older version of IOS and in Simulator it's taking as black. so for new versions of IOS we have to specify css colour

**Comment by jerbob92** [comment]
@kranthi-kiki thanks! I thought it might have been the same problem that I have currently, but that doesn't seem to be the case.
