### ISSUE TITLE
Nativescript RadSideDrawer. I don't need back button.

### ISSUE THREAD

**Issue by lapodelapis** [NativeScript/NativeScript#8398]
I'm trying to make a simple app with Playground (https://play.nativescript.org/). I'm using "RadSideDrawer" as a side menu. I'm satisfied. BUT ... every time I use "RadSideDrawer" and I move from one page to another, inside the "ActionBar" a button appears whose function is to bring back to the left page (please have a look at this page https://www.attivitacollaterali.it/appdata/services/apps/RadSideDrawer.html). I don't need and want this button. How can I make it not appear? Thank you.

**Comment by lapodelapis** [comment]
Or, if not, at least update "RadSideDrawer". I mean that if the button goes back, for example to the "Search" page from the "Home" page, it should highlight/select "Search" in the "RadSideDrawer" menu and not leave "Home". Thanks again.

**Comment by NickIliev** [comment]
@lapodelapis I can only suspect that you are talking about iOS where the UINavigaitonBar will show a back button anytime forward navigation is made. You could entirely remove the ActionBar but you can't remove the navigation back button that comes from the native iOS.
