### ISSUE TITLE
White flash before app load

### ISSUE THREAD

**Issue by msteini82** [NativeScript/NativeScript#8399]
**Environment**
 - CLI: 6.4.1
 - Cross-platform modules: 6.4.2
 - Android Runtime: 6.4.1
 - iOS Runtime: 6.4.2

**Describe the bug**
On Launch there is a white flash between LaunchScreen and app start. The bug happens on NS+Angular on iOS and on Android. Setting the Page Background in app.css don't work (as described in close issue https://github.com/NativeScript/NativeScript/issues/3414#issue-198926126). The bug appears especially if external plugins are used, which cause a longer loading time.

**To Reproduce**
Create a new project with `tns create project --ng` change background color of home page and set `Page { background-color: blue;}` in app.css. Optionally use some plugins for longer load time.

**Expected behavior**
There should be a smooth transition between LaunchScreen and first app page. If that's not possible, there should be the possibility to declare the main background Color.

**Sample project**
https://play.nativescript.org/?_ga=2.79038225.408070477.1582939149-2005108081.1577734019&template=play-ng&id=5dWzOB

**Comment by NickIliev** [comment]
@msteini82 I am not reproducing the issue - can you let me know what are the testing devices used on you side?

**Comment by tralves** [comment]
I fixed the issue on Android by changing `App_Resources/Android/src/main/res/values/styles.xml`:

```
    <style name="AppThemeBase" parent="Theme.AppCompat.Light.NoActionBar">
       <!-- added this line here -->
        <item name="android:windowBackground">@color/ns_primaryDark</item>
        ...
```
