### ISSUE TITLE
About androidx.biometric classes declarations

### ISSUE THREAD

**Issue by alonstar** [NativeScript/NativeScript#8404]
I tried to use biometric authentication dialog in library :  androidx.biometric:biometric:1.0.1 .
But I can't find the classes declarations.

Could you please add they in androidx?

**Comment by NathanaelA** [comment]
@alonstar - You should be able to just reference it in your gradle file; and the meta data should then become available...

**Comment by alonstar** [comment]
> @alonstar - You should be able to just reference it in your gradle file; and the meta data should then become available...

Yes, I added it in gradle file then I tried to generate new TypeScript declaration files using android-dts-generator but got errors :(

**Comment by NickIliev** [comment]
@alonstar this is a standalone library that is not coming with the Android SDK and the platform declarations are including the core Android SDK only. You could, of course, generate your own typing while using the Android DTS generator. See [the documentation article](https://docs.nativescript.org/core-concepts/android-runtime/metadata/generating-typescript-declarations) and[ this repository](https://github.com/NativeScript/android-dts-generator).
