### ISSUE TITLE
Tap event data should include touch location

### ISSUE THREAD

**Issue by mudlabs** [NativeScript/NativeScript#8407]
**Is your feature request related to a problem? Please describe.**
 
As it stands getting the _x/y_ location of a tap event requires diving into native code. But touch events are already supplying this utility. This should be extended to tap events.

**Describe the solution you'd like**

The `touch` gesture event data methods of `getX`, and `getY` should be included in tap event data.

Also a TapGestureEventData interface should be available for type assignment.

```ts
export function tapped(args: TapGestureEventData): void {
    const tapped_x = args.getX(); // The X axis tap location in DIP
    const tapped_y = args.getY(); // The Y axis tap location in DIP
}
```

**Describe alternatives you've considered**

Currently you have to dive into platform specific native code to get the tap location. But they are also not in DIP, so that conversion must be done.
```ts
import { screen } from "tns-core-modules/platform";

export function tapped(args: GestureEventData): void {
    if (args.ios) {
        const location = args.ios.locationInView(args.object.ios); //CGPoint in DP.
        const x = location.x / screen.mainScreen.scale; // The X axis tap location in DIP
        const y = location.y / screen.mainScreen.scale; // The Y axis tap location in DIP
    } else {
        const x = args.android.getX() / screen.mainScreen.scale; // The X axis tap location in DIP
        const y = args.android.getY() / screen.mainScreen.scale; // The Y axis tap location in DIP
    }
}
```

**Additional context**

Could also extend the `getPointerCount`, and `getAllPointers` methods available to `touch` events. This would give a simple way to handle single or multiple pointer events when you don't require the longer lived event cycle of `touch` events.

**Comment by NathanaelA** [comment]
This is a good idea --  However it probably should be a helper function/getter; like something like:
`const tapLocation = args.getLocation()` which returns it.   We probably don't want to run the conversion code on every tap event, but only when the developer actually needs the tap location..

**Comment by mudlabs** [comment]
Yeah, that's how `touch` does it.

Looks like there's some inconsistency with how `getX` and `getY` work too.
- The `getX` and `getY` methods of the `touch` event data are in **DP**, on both platforms.
- But if you get a `touch` event Pointer _(i.e. args.getActivePointers()[0])_, its `getX` and `getY` methods return **DP** on _iOS_, and **DIP** on _Android_.

**Comment by NickIliev** [comment]
Marking this issue as an enhancement (for the tap event data) and also as a good-first-issue as most of the code is already implemented in the touch event data and can be used as a reference.
