### ISSUE TITLE
 java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:

### ISSUE THREAD

**Issue by bhavanigattikoppula** [NativeScript/NativeScript#8408]
declaration in app.module.ts file--->
declare const com: any, android: any;
const LocationService = com.obf.LocationService;

System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: TypeError: Cannot read property 'LocationService' of undefined
System.err: File: "file:///data/data/com.onebigfamily.android/files/app/app.module.js, line: 72, column: 30
System.err: 
System.err: StackTrace: 
System.err:     Frame: function:'', file:'file:///data/data/com.onebigfamily.android/files/app/app.module.js', line: 72, column: 31
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/com.onebigfamily.android/files/app/main.js', line: 5, column: 20
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'LocationService' of undefined
System.err: File: "<unknown>, line: 1, column: 265
System.err: 
System.err: StackTrace: 
System.err:     Frame: function:'', file:'file:///data/data/com.onebigfamily.android/files/app/app.module.js', line: 72, column: 31
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/com.onebigfamily.android/files/app/main.js', line: 5, column: 20
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'LocationService' of undefined
System.err: File: "<unknown>, line: 1, column: 265
System.err: 
System.err: StackTrace: 
System.err:     Frame: function:'', file:'file:///data/data/com.onebigfamily.android/files/app/app.module.js', line: 72, column: 31
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/com.onebigfamily.android/files/app/main.js', line: 5, column: 20
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5593)
System.err:     at android.app.ActivityThread.-wrap2(ActivityThread.java)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
System.err:     at android.os.Looper.loop(Looper.java:203)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6338)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1066)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: TypeError: Cannot read property 'LocationService' of undefined
System.err: File: "file:///data/data/com.onebigfamily.android/files/app/app.module.js, line: 72, column: 30
System.err: 
System.err: StackTrace: 
System.err:     Frame: function:'', file:'file:///data/data/com.onebigfamily.android/files/app/app.module.js', line: 72, column: 31
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/com.onebigfamily.android/files/app/main.js', line: 5, column: 20
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'LocationService' of undefined
System.err: File: "<unknown>, line: 1, column: 265
System.err: 
System.err: StackTrace: 
System.err:     Frame: function:'', file:'file:///data/data/com.onebigfamily.android/files/app/app.module.js', line: 72, column: 31
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/com.onebigfamily.android/files/app/main.js', line: 5, column: 20
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'LocationService' of undefined
System.err: File: "<unknown>, line: 1, column: 265
System.err: 
System.err: StackTrace: 
System.err:     Frame: function:'', file:'file:///data/data/com.onebigfamily.android/files/app/app.module.js', line: 72, column: 31
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/com.onebigfamily.android/files/app/main.js', line: 5, column: 20
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:624)
System.err:     at com.tns.Runtime.run(Runtime.java:616)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5590)
System.err:     ... 8 more
Skipping prepare.

**Comment by NickIliev** [comment]
@bhavanigattikoppula :

1. The error indicates that you are missing the metadata for `com.obf.LocationService`. Is this package (that holds the above namespace) available in your project?
2. How are you declaring a CONST without a value in the first place? (`declare const com: any, android: any;`). I think you should use **let** here

Closing the issue as it lacks the information needed to reproduce the case (see the bug report template for requested information and sample project)

**Comment by wjgvm** [comment]
read the code and verify package, template, import correctly in app.js
