### ISSUE TITLE
Distribute the .d.ts-es

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#841]
For good TS experience within the {N} we have to ship .d.ts-es for modules (and optionally to generate .d.ts-es for native APIs). This is a feature that needs shipping since most of the tooling is there for us already.

**Comment by ligaz** [comment]
Consider adding `typings` key in the `package.json` or `index.d.ts`. More info [here](https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages).

**Comment by PanayotCankov** [comment]
@ligaz :+1:

**Comment by ErjanGavalji** [comment]
With TypeScript 1.6 using the Typings folder out of the box, it would be good to have the TypeScript declarations in a separate package. Thus, d.ts files won't be embedded in the tns-core-modules package, which is pure executable javascript code only.

Separation of concerns FTW!

**Comment by guillaume-roy** [comment]
In the meantime, how and where can we get d.ts files ?

**Comment by ligaz** [comment]
You can find them in the release pages of this repo. Look at the downloads section: https://github.com/NativeScript/NativeScript/releases/tag/v1.4.0

**Comment by guillaume-roy** [comment]
Thanks

**Comment by vchimev** [comment]
Starting with {N} 1.5, `.d.ts` files will be included in the **tns-core-modules** package.
