### ISSUE TITLE
Unable to trace cause of crash | com.tns.Runtime.callJSMethodNative | AUDIO_BECOMING_NOISY

### ISSUE THREAD

**Issue by 7ammer** [NativeScript/NativeScript#8416]
Hello,

Apologies if this is not directly related to this repo. I can't quite pinpoint if the below error is coming from Nativescript, a package or my code...

I'm receiving a large number of Android crash reports related to `com.tns.Runtime.callJSMethodNative`. About 624 crashes in the last 7 days. Google searches for `AUDIO_BECOMING_NOISY`, `ZygoteInit` and `ACTION_MY_PACKAGE_SUSPENDED` etc seem to be a bit too generic for me to pinpoint what the issue could be.

These are the highlights regarding the report:
```
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.media.AUDIO_BECOMING_NOISY flg=0x14000010 } in com.tns.gen.android.content.BroadcastReceiver_vendor_1_27888_BroadcastReceiver@8d705fa
```

```
Caused by com.tns.NativeScriptException: Calling js method onReceive failed
Error: java.lang.NoSuchFieldError: no "Ljava/lang/String;" field "ACTION_MY_PACKAGE_SUSPENDED" in class "Landroid/content/Intent;" or its superclasses
```

I have also seen:
`ACTION_INSTALL_FAILURE`
`ACTION_APPLICATION_PREFERENCES`
`ACTION_CARRIER_SETUP`
in place of `ACTION_MY_PACKAGE_SUSPENDED `

It looks like this does not appear on all devices and it happens around the time the app is opened.

Here is the full error stack trace:
https://pastebin.com/raw/mkheZEdK

Package versions are:
```
"tns-android": {
  "version": "6.0.0"
},
"dependencies": {
    "nativescript-advanced-webview": "^3.0.2",
    "nativescript-animated-circle": "^1.2.0",
    "nativescript-datetimepicker": "^1.2.1",
    "nativescript-dev-appium": "^6.1.3",
    "nativescript-downloader": "^2.1.5",
    "nativescript-local-notifications": "^4.1.5",
    "nativescript-localstorage": "^2.0.0",
    "nativescript-permissions": "^1.2.3",
    "nativescript-plugin-firebase": "^10.3.0",
    "nativescript-social-share": "^1.5.2",
    "nativescript-statusbar": "^5.0.0",
    "nativescript-vue": "^2.4.0",
    "nativescript-webview-interface": "^1.4.3",
    "tns-core-modules": "^6.0.0",
    "url-parse": "^1.4.7"
},
"devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.2",
    "nativescript-dev-webpack": "^1.0.0",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "tns-platform-declarations": "^6.0.0",
    "typescript": "^3.2.4",
    "vue": "^2.5.22",
    "vue-loader": "^15.4.0",
    "mocha": "~5.2.0",
    "mochawesome": "~3.1.2",
    "chai": "~4.1.2",
    "@types/mocha": "~5.2.5",
    "@types/chai": "~4.1.7",
    "@types/node": "~10.12.18",
    "mocha-junit-reporter": "~1.18.0",
    "mocha-multi": "~1.0.1"
}
```

Please let me know if any other info might be helpful. Any help would be much appreciated.

Thanks

**Comment by 7ammer** [comment]
Hello @NickIliev, thanks for reading. I note the "needs more info" tag. Can you let me know what I can add?

Cheers

**Comment by NickIliev** [comment]
@7ammer a sample demo project that reproduces the issue so that anyone interested in helping can have a starting point.
