### ISSUE TITLE
Tabs iOS transition between frames

### ISSUE THREAD

**Issue by henrikdahl** [NativeScript/NativeScript#8422]
Instead of using the `BottomNavigation` I've used the `Tabs` component. I want to use it as a `BottomNavigation` which sort of works. The issue is that I don't want swipe gestures to be enabled, that was possible to disable. The remaining issue is that switching between pages using the selectedIndex adds a transition and also a history (back button). Hiding the action bar solved the back button but the transition between pages remain. How do you remove it? I've tried everything.

As for the reason going with Tabs instead of BottomNavigation, it's because I wanted to be able to style it more freely. Borders on the BottomNavigation wasn't possible.

Any help is welcome. Thanks!

```
<template>
	<Page actionBarHidden="true">
		<FlexboxLayout flexDirection="column">
			<FlexboxLayout>
				<Tabs :selectedIndex="activeTab" swipeEnabled="false">
					<TabContentItem>
						<Frame>
							<Dream />
						</Frame>
					</TabContentItem>
					<TabContentItem>
						<Frame>
							<Home />
						</Frame>
					</TabContentItem>
					<TabContentItem>
						<Frame>
							<Inbox />
						</Frame>
					</TabContentItem>
					<TabContentItem>
						<Frame>
							<Profile />
						</Frame>
					</TabContentItem>
				</Tabs>
			</FlexboxLayout>
			<FlexboxLayout class="navigation">
				<Image v-for="(tab, index) in tabs" key="index" :src="`res://icon-${tab.icon}`" stretch="none" @tap="onTap(index)" />
			</FlexboxLayout>
		</FlexboxLayout>
	</Page>
</template>
```

**Comment by NickIliev** [comment]
@henrikdahl are you using @nativescript/core@6.4.2 - there is [this fix ](https://github.com/NativeScript/NativeScript/issues/8344)for **swipeEnabled** included in this version

**Comment by henrikdahl** [comment]
@NickIliev where can I see that? is it the same as `tns-core-modules`? If so, I'm running 6.0.0

**Comment by NickIliev** [comment]
@henrikdahl yes try to update `tns-core-modules` to the latest version. I will try to reproduce this one later.

**Comment by henrikdahl** [comment]
@NickIliev updated to `tns-core-modules` version `6.4.2`. Doesn't seem to change anything, still has the swipe animation with `swipeEnabled="false"`. Although as before, the swipe gesture is indeed disabled, just the animation remains.

**Comment by henrikdahl** [comment]
Basically trying to use the tabs as none tabs in the end, so switched to simple navigation instead with a `Frame`.
