### ISSUE TITLE
How to console object (nativescript vue)

### ISSUE THREAD

**Issue by thamibn** [NativeScript/NativeScript#8433]
Hi,

I am using nativescript-vue and i have a simple object that i want to console on the terminal

when i run ```console.log(this.simpleObject)```
I get this results
```
JS: { age: [Getter/Setter],
JS:   gender: [Getter/Setter],
JS:   [__ob__]: 
JS:    { value: [Circular],
JS:      dep: { id: 135, subs: [Object] },
JS:      vmCount: 0 } }
```

instead of

``` 
simpleObject {
 age:10,
gender: 'male'
}

**Comment by NickIliev** [comment]
@thamibn you could use `JSON.Parse` & `JSON.Stringify`

Here is [a basic example](https://play.nativescript.org/?template=play-vue&id=tWqnV6)

**Comment by thamibn** [comment]
Thanks @NickIliev for the advice i am currently using console.dir(object); i find it easy, it does show me the object content.

thank you very much again.
