### ISSUE TITLE
Add selectedItemColor and unSelectedItemColor to TabStrip

### ISSUE THREAD

**Issue by vtrifonov** [NativeScript/NativeScript#8435]
As there are some cases in which it is too complex to support all the different ways of setting text and icon color to the TabStrip items on Bottom Navigation and Tabs components in Android in iOS we need to introduce **selectedItemColor** and **unSelectedItemColor** properties in TabStrip. If you set them the color set through CSS won't be respected and you won't be able to set different colors to icon and text in a single TabStrip item. However as it seems in Material Design Guidelines they should have the same color, so we recommend using these properties. You can set the properties like this:
```XML
  <Tabs>
    <TabStrip selectedItemColor="red" unSelectedItemColor="green">
  ...
```

**Comment by NickIliev** [comment]
Related to t.1456350

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
