### ISSUE TITLE
Border radius not working on GridLayout

### ISSUE THREAD

**Issue by vforv** [NativeScript/NativeScript#8437]
Here is simple xml to reproduce issue:
```
<GridLayout rows="*,300">
    <StackLayout row="0" backgroundColor="yellow" opacity="0.4" >
    </StackLayout>
    <StackLayout row="1" style="border-radius: 30;border-width: 30;">
    </StackLayout>
</GridLayout>
```
After border-radius is added there are still white corners. There is also a white background which I even didn't specify

**Comment by NickIliev** [comment]
The white corners you are seeing are actually the white GridLayout underneath. [Here is a modified dem](https://play.nativescript.org/?template=play-tsc&id=4gNjuW)o where the Grid is blue and the stack is green so you could visualize what is happening. The border-radius **is applied on the nested StackLayout** and not on the GridLayout so everything is working as expected. If you want the Grid to have a border-radius - apply it on the GridLayout
