### ISSUE TITLE
Geolocation / desiredAccuracy = 1 doesnt work ?

### ISSUE THREAD

**Issue by baermathias** [NativeScript/NativeScript#8438]
**Environment**
I am using an Samsung S8 + play.nativescript without the CLI

**Describe the bug**
On https://play.nativescript.org/ is a component called Location, when using it inside HelloWorld.vue the location doesn't change / update when moving around my house and waiting or pressing the Show location button again. I set both `desiredAccuracy` and `updateDistance` to `1` (1m?), but also tried it with the value Accuracy.high after importing the module. What could be the issue?

What is the highest accuracy I can set? 1m?

**To Reproduce**
Add the below code to play.nativescript.org:

**Expected behavior**
Changed location

**Sample project**
```
<template>
    <Page>
        <ActionBar title="Home" />
        <ScrollView>

            <StackLayout>
                <Button text="Show location" @tap="enableLocationServices" />
                <StackLayout>
                    <Label
                        :text="'Latitude: ' + currentGeoLocation.latitude" />
                    <Label
                        :text="'Longitude: ' + currentGeoLocation.longitude" />
                    <Label
                        :text="'Altitude: ' + currentGeoLocation.altitude" />
                    <Label
                        :text="'Direction: ' + currentGeoLocation.direction" />
                </StackLayout>
            </StackLayout>

        </ScrollView>
    </Page>
</template>

<script>
    const geoLocation = require("nativescript-geolocation");

    export default {
        methods: {
            enableLocationServices: function() {
                geoLocation.isEnabled().then(enabled => {
                    if (!enabled) {
                        geoLocation
                            .enableLocationRequest()
                            .then(() => this.showLocation());
                    } else {
                        this.showLocation();
                    }
                });
            },

            showLocation: function() {
                geoLocation.watchLocation(
                    location => {
                        this.currentGeoLocation = location;
                    },
                    error => {
                        alert(error);
                    }, {
                        desiredAccuracy: 1,
                        updateDistance: 1,
                        minimumUpdateTime: 1000 * 1
                    }
                );
            }
        },

        data() {
            return {
                currentGeoLocation: {
                    latitude: null,
                    longitude: null,
                    altitude: null,
                    direction: null
                }
            };
        }
    };
</script>
```

**Comment by NickIliev** [comment]
@baermathias this is related to how the native API works. See details [here](https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest#setInterval(long))



> This interval is inexact. You may not receive updates at all (if no location sources are available), or you may receive them slower than requested. You may also receive them faster than requested (if other applications are requesting location at a faster interval). 


I've also tested your code around the house and it works as described above - form time-to-time but not on every call.
