### ISSUE TITLE
Progress View `value` property change does not trigger Observable.propertyChangeEvent

### ISSUE THREAD

**Issue by swlemp** [NativeScript/NativeScript#8444]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.4.1
 - Runtime: Android 6.0.0

**Describe the bug**
Progress View `value` property change does not trigger Observable.propertyChangeEvent.

**Comment by NickIliev** [comment]
@swlemp you could use the **_valueChange_** event (most properties in NativeScript Core can be observed by using the name of the property + the **_Change_** word).

For example(TypeScript):
```TypeScript
export function onProgressLoaded(args: EventData) {
    let pr = args.object as Progress;

    pr.on("valueChange", (args: any) => {
        console.log(`old value: ${args.oldValue}; new value: ${args.value}`);
    })
}
```

Full demo [here](https://play.nativescript.org/?template=play-tsc&id=IpcWqp)

Note that the **valueChange** event can not be used from the XML (inline) but only form the code-behind (Thas related to NativeScript Core).
In Angular, you can use the Angular Change event on each property including from the HTML or via code-behind.
