### ISSUE TITLE
feat(angular): v9 with ivy support

### ISSUE THREAD

**Issue by abcfoundry** [NativeScript/NativeScript#8448]
Angular 9 has been out for almost 2 months and there is still no support for this critical update.  Furthermore the NativeScript Angular repository is dead!  There has not been any updates since Feb 15 2020.  

I'm guessing that the NativeScript community has moved on from Angular to a new shiny object, leaving any current invested projects in the cold.  Correct me if I'm wrong, but actions are stonger than words.

Rather disappointing

**Comment by NickIliev** [comment]
Please post any comment related to Angular 9 support in the Angular repository - there is an ongoing initiative to support Angular 9 ([see this feature request thread](https://github.com/NativeScript/nativescript-angular/issues/2060)) but at this very moment the officially supported version of Angular is still version 8
