### ISSUE TITLE
Can't open modal within modal due to ViewHierarchy error on IOS.

### ISSUE THREAD

**Issue by aranmohyeddin** [NativeScript/NativeScript#8451]
I've raised this issue before(#8447) but it was closed without being resolved so I'm raising a new issue to explain more. 

* **Please note that this is a bug** because this issue only occurs on IOS simulator/real device. Not in android or playground(neither ios nor android) and nowhere in IOS docs or nativescript docs it is mentioned that we are not able to open a modal from within another modal.

* Furthermore, please note that **navigation is not a proper workaround** for this because in case of complex navigation in both outer and inner modals, it will be very difficult to get the same behavior using navigations. Modals are a real thing for a reason. Modals serve their own use cases, otherwise they would have not existed. We really need to be able to use modals inside modals. 

* Finally, it is important to mention that **this issue did not exist before**. I could always open a modal in another modal before and It's since one of the recent updates that this is not possible anymore. Existing applications are breaking because of this.

* This issue had occurred before(#5924) and it was considered as a bug and was fixed, how come it is dismissed now?

**Environment**
```
$ tns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.5.0 version and is up to date.
✔ Component tns-core-modules has 6.5.0 version and is up to date.
✔ Component tns-android has 6.5.0 version and is up to date.
✔ Component tns-ios has 6.5.0 version and is up to date.
```

**Describe the bug**
When I try to open a modal while I'm already in another modal. I get an error saying:
> ViewHierarchy: parent is already presenting view controller close the current modal page before showing another one!

How can I have one modal within another?

**To Reproduce**

 * Click on Button (A modal should pop up)
 * Click on Button (Nothing will happen and you will get an error)

**Expected behavior**
You should see a new popup open.

**Sample project**
Here is a [playground sample](https://play.nativescript.org/?template=play-vue&id=mQF8k3&v=3)

**Additional context**
I believe the exact same code used to work a few weeks ago. It seems like the issue is causes by an update but I do not know what and when. It works perfectly fine on android but I get this error in IOS.

**Comment by AbtinAghagolian** [comment]
We also have this issue.

**Comment by AbtinAghagolian** [comment]
@aranmohyeddin I this U should wait for your existing issue to be reopened instead of creating a new one.
