### ISSUE TITLE
Rich CSS support

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [NativeScript/NativeScript#8452]
Hello, 
with version 6.4 release i see you are working on many cool feature like 3d transformations etc... however all these features will not e used if we cannot build nice, upto date applications. 
There are many missing css features missing like box-shadow, form elements focus state styling etc.
I am working as an solution architect in my company with 50k employees and I was aksed what should we go with NativeScript or ReactNative and no matter how i like NS but i had to admit that NS is not mattre enough to fit our design customization needs... We are still in early stage of development and I can turn things around if only see the progress in that field. And this is not about me or my case.. i see many developers sufereing from same issues and making same choices.

Guys, can you please focus on rich css improvement tasks because having nice UX / UI is most important today.

https://github.com/NativeScript/NativeScript/issues/550

giving simple example:
need to add texfield with nice shadow, without border with custom focus state - NOT POSSIBLE now or we have to do some hacky things that you would like to drop using NS instead...

**Comment by NickIliev** [comment]
@vytautas-pranskunas-thank you for your interest in NativeScript. Note that some of the CSS features that are widely used on the Web are having their counter features in the mobile world. This is one of the main reasons to be hard to provide full CSS support for some concepts. For example there is athe material design where you could create elevated layouts via elevation which is pretty similar to box-shadow but not it is different in how it is implemented.

We have multiple CSS feature request issues (like the one linked by you) and as NativeScript is an open-source we are open to any PRs and contributors. Closing this one as a duplicate issue.

**Comment by vytautas-pranskunas-** [comment]
Hi, i understand, but look if you look at react native box shadows and most other CSS support is mplemented.
If you look at the elevation try to add border to texbox and add elevation - then look what will happen... Textbox will be shrinked, shadow will be around and border will be around shadow....  so it useless because shadow should be after border and should not effect input size...
