### ISSUE TITLE
Targeting ES2017 on android 6.4.1+ fails with custom activity

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/NativeScript#8455]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.4.1
 - Cross-platform modules: 6.4.1
 - Android Runtime: 6.4.1

**Describe the bug**

```bash
Restarting application on device emulator-5554...
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: Error: com.tns.system.classes.loading.LookedUpClassNotFound: Class "org.myApp.MainActivity" not found.
System.err: File: (/data/data/org.nativescript.test2017/files/internal/ts_helpers.js:154:25)
System.err: 
System.err: StackTrace: 
System.err: (/data/data/org.nativescript.test2017/files/internal/ts_helpers.js:154:26)
System.err:     at __decorate(/data/data/org.nativescript.test2017/files/internal/ts_helpers.js:13:19)
System.err:     at ./activity.ts(file: app/activity.ts:6:14)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:74:0)
System.err:     at (file: app/app.ts:7:0)
System.err:     at ./app.ts(file:///data/data/org.nativescript.test2017/files/app/bundle.js:205:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:74:0)
System.err:     at checkDeferredModules(file: app/webpack/bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: app/webpack/bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.test2017/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err: 
System.err: 
System.err: Error: com.tns.system.classes.loading.LookedUpClassNotFound: Class "org.myApp.MainActivity" not found.
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: Error: com.tns.system.classes.loading.LookedUpClassNotFound: Class "org.myApp.MainActivity" not found.
System.err: File: (/data/data/org.nativescript.test2017/files/internal/ts_helpers.js:154:25)
System.err: 
System.err: StackTrace: 
System.err: (/data/data/org.nativescript.test2017/files/internal/ts_helpers.js:154:26)
System.err:     at __decorate(/data/data/org.nativescript.test2017/files/internal/ts_helpers.js:13:19)
System.err:     at ./activity.ts(file: app/activity.ts:6:14)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:74:0)
System.err:     at (file: app/app.ts:7:0)
System.err:     at ./app.ts(file:///data/data/org.nativescript.test2017/files/app/bundle.js:205:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:74:0)
System.err:     at checkDeferredModules(file: app/webpack/bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: app/webpack/bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.test2017/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err: 
System.err: 
System.err: Error: com.tns.system.classes.loading.LookedUpClassNotFound: Class "org.myApp.MainActivity" not found.
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
System.err:     at android.app.ActivityThread.access$1100(ActivityThread.java:199)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function 
System.err: Error: com.tns.system.classes.loading.LookedUpClassNotFound: Class "org.myApp.MainActivity" not found.
System.err: File: (/data/data/org.nativescript.test2017/files/internal/ts_helpers.js:154:25)
System.err: 
System.err: StackTrace: 
System.err: (/data/data/org.nativescript.test2017/files/internal/ts_helpers.js:154:26)
System.err:     at __decorate(/data/data/org.nativescript.test2017/files/internal/ts_helpers.js:13:19)
System.err:     at ./activity.ts(file: app/activity.ts:6:14)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:74:0)
System.err:     at (file: app/app.ts:7:0)
System.err:     at ./app.ts(file:///data/data/org.nativescript.test2017/files/app/bundle.js:205:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:74:0)
System.err:     at checkDeferredModules(file: app/webpack/bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: app/webpack/bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.test2017/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err: 
System.err: 
System.err: Error: com.tns.system.classes.loading.LookedUpClassNotFound: Class "org.myApp.MainActivity" not found.
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:674)
System.err:     at com.tns.Runtime.run(Runtime.java:666)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
System.err:     ... 8 more
```

 With 6.4.1 introducing latest V8, android can basically target ES2017 and be feature complete as far as I can tell. Which produces smaller bundles and less transpiling with a TS project to write modern TS/JS.

I've put a sample app up displaying the issue [here](https://github.com/bradmartin/ns-es2017-test).

The tsconfig is targeting: `ES2017`
The app has a custom activity for android as the main activity, declared in the manifest, webpack.config and copied from the documentation.

If the app does not have a custom activity it will run as expected on Android 6.4.1.

**To Reproduce**
Run this demo app https://github.com/bradmartin/ns-es2017-test

**Expected behavior**

Run without error.

**Additional context**
I thought this was just not possible to run ES2017, because I got this error in a production app I was upgrading. So I created the template app and tested and it worked without the custom activity. Added the custom activity and same error.

I'm assuming this is an SBG or runtime issue.

**Comment by vmutafov** [comment]
Hey @bradmartin ! I looked into the case and it seems the problem is due to the way how your TS code is transpiled. The `activity.ts` class is transpiled to:
```JS
let Activity = class Activity extends androidx.appcompat.app.AppCompatActivity
```
This way of extending native classes is currently unsupported due to the JS parser in the Static Binding Generator. Currently, we have no plans to support this as it may need significant effort in reimplementing the JS parser. 

The options you have is to use the documented JS approach of extending native classes in your TS code.

**Comment by bradmartin** [comment]
Thanks @vmutafov - I poked around in that transpiled file to see if I could spot something but I wasn't sure since I've always used the TS approach :) thanks for the help. I'll prob roll it back into the es5 transpiled file for the activity and leave it at that and see if it works... Or possibly exclude that file from the `tsconfig` rules and leave the TS file with the ES5 version in the project also, with some docs so the team is aware of why/what 👍

**Comment by bradmartin** [comment]
@vmutafov  - I was unsuccessful in that attempt :) Do you think that should work? I've transpiled the custom activity with ES5 target, excluded the ts file (double checked a `tsc` run and it didn't change from the ES5 version) and it failed.

I guess when I think about it, it makes sense it fails bc the rest of the code is ES2017. I was just hopeful that worked as a quick work around.

I could extend the activity just fine using plain JS, but the callback class I'm using has me a bit confused on how to do that, not finding anything in the docs. Any help/guidance appreciated and will keep trying to see if I can get it working.

Trying to measure bundle differences and any performance gains, specifically around async/await since it's supported by the newest engines vs. having the older `generators/yield` plain js approach for those calls. Since the app makes use of a lot of async/await I was hoping it might give a slight perf boost. These are WearOS apps, so every perf piece I can gain, is what I'm trying to squeeze out 🏎

**Comment by NathanaelA** [comment]
@bradmartin - This is the thread that I was thinking of: https://github.com/NativeScript/android-runtime/issues/1135

 Basically I think if you downgrade your class to a standard POD that you uses .extends on you should be good.   But I haven't actually tried it myself...

**Comment by bradmartin** [comment]
Yeah I don't want to jump through all those hoops right now 🙃 I'll wait to see what future holds there
