### ISSUE TITLE
SCSS compiles but error occurs in bundle.js

### ISSUE THREAD

**Issue by wellyson21** [NativeScript/NativeScript#8463]
**Describe the bug**
I have installed all the dependencies for SCSS processing, however it returns the following runtime error when executed on the device: ERROR SyntaxError: Unexpected identifier 'defined undefined undefi' in file bundle.js

-- Package.json
 "devDependencies": {
    "nativescript-dev-webpack": "~1.5.1",
    "node-sass": "^4.13.1",
    "sass-loader": "^8.0.2",
    "typescript": "~3.5.3",
    "webpack": "^4.42.1"
  },

![Captura de Tela 2020-03-27 às 10 50 02](https://user-images.githubusercontent.com/26719586/77762768-c8496280-7018-11ea-88ed-1ee9632ad9b4.png)

* when you run the app

![Captura de Tela 2020-03-27 às 10 59 15](https://user-images.githubusercontent.com/26719586/77763624-20349900-701a-11ea-8a5c-7ef6df6723cd.png)

**Comment by NickIliev** [comment]
Closing as a duplicate to https://github.com/NativeScript/nativescript-cli/issues/5288
