### ISSUE TITLE
ListView combined with Theme Core V2 breaks scroll

### ISSUE THREAD

**Issue by SuperdanTX** [NativeScript/NativeScript#8465]
**Environment**
 - CLI: 6.3.3
 - Cross-platform modules:
 - Android Runtime: 6.5.0-2020-03-12-133513-01
 - iOS Runtime: 6.5.0-2020-03-12-110223-01
 - Plugin(s): "nativescript-filterable-listpicker": "^2.2.6"

**Describe the bug**
All I'm about to describe still works fine on iOS. This only affects Android.
We have a main screen made up of several individual components.
One of these components contains a ListView, which prior to upgrading to Material (Theme Cor 2 v2), worked fine on both iOS and Android.
After we upgraded the project to use "nativescript-theme-core": "^2.0.24", this component will no longer scroll on Android.
We also make extensive use of the filterable list picker, noted above in plugins, and it is now broken, but again only on Android. It still works fine on iOS. I assume since it is inheriting from the ListView class, that perhaps this may be in the nativescript/android list element?

**To Reproduce**
A scrollview with an added component that has a listview, using Theme Core v2 will reproduce this.

**Expected behavior**
The listview should be scrollable on both iOS and Android.

**Additional context**
We have deployed this app to the app since December 2019, and it has been fine until we did the Theme Core v2 upgrade. Not sure if this belongs in a different github, but we will start here.

Thanks for any thoughts or ideas on the subect!

**Comment by NickIliev** [comment]
@SuperdanTX the description of the issue itself is not enough to investigate the issue. Try to isolate the case in a demo project (e.g. by removing parts of your application until you are left with the minimum code needed to reproduce the case)
