### ISSUE TITLE
Cannot make tab image smaller

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [NativeScript/NativeScript#8466]
I have tabs

```
<TabStripItem class="navigation__item">
       <Label text="Search" class="tab"></Label>
       <Image src="font://&#xe986;" class="icon icon-small"></Image>
</TabStripItem>
```

and no matter what i do i cannot make image smaller. I have tired different font sizes set in css, i tried to add sizing on image it self through width and height

Icon just is not getting smaller.
however i can easily change color so styling iteslf is good.

**Comment by NickIliev** [comment]
@vytautas-pranskunas- by default the icon size of the `tabStripItem` is fixed (the size is fixed accordingly the specific platform design guidelines).

If you still want to disregard the recommended size of the tab icon you could use the property and change the default **true** value to **false**.
```XML
<TabStripItem isIconSizeFixed="false">
```
See the `isIconSizeFixed` property in[ this documentation section](https://uatdocs.nativescript.org/ui/components/tabs#properties-TabStrip).

**Comment by vytautas-pranskunas-** [comment]
Hi, 
i cannot get it working
I have applied all different sizes i new however there should be enought font-size but it is not getting smaller

my code:

```
<TabStripItem class="navigation__item" isIconSizeFixed="false">
       <Label text="Search" class="tab"></Label>
       <Image src="font://&#xe986;" class="icon icon-small"></Image>
</TabStripItem>


.icon-small {
        font-size: 4px;
        size: 4px;
        width: 4px;
        height: 4px;
    }
```

**Comment by NickIliev** [comment]
@vytautas-pranskunas- my bad the proeprty should be set on the `Tabs` component.

Here is [a demo Playground](https://play.nativescript.org/?template=play-ng&id=rg4K03)
