### ISSUE TITLE
Event propagation in NS 6.5

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/NativeScript#8467]
I'm using NS core 6.5.

I've got a layout with a buttons inside it - both have tap events registered.

The problem is that when I click on a button, the event also propagates to the layout.

This issue seems to be well discussed - it's an expected behavior.

The workaround seems to be to set a flag in the button event and interrogate that in the layout event.

But it seems like the layout callback is called before the button callback.

This is on Android - and pretty sure wasn't the case 5.x.

Any help?

**Comment by erjdriver** [comment]
Why is the bot closing issues and pointing me to SO?

This is a framework issue.

Create a ListView with items having tap event and a Button inside a listitem with tap event also.

Press the Button and the event will be sent to the ListItem tap event and then to the Button event.

@NickIliev I think you wrote that this was not a good UI design. Respectfully - this UI is used everywhere. e.g. Youtube app which is essentially a ListView and most of the list items have a small buttons (e.g. thumbs up).

In NS 6.x it looks like the event gets sent to the outside container first and then to the inside.

In NS 5.x Android this wasn't and issue - the Button and only the button got the callback.

**Comment by rbudnar** [comment]
@NickIliev I noticed the same issue as well in NS 6.5. Perhaps I'm misunderstanding, but from reading your post here: https://medium.com/@NativeNick/nativescript-event-bubbling-a-short-story-of-propagating-tap-f0c1ccec2752 it seems that a taps on a `<Button>` should not propagate (`So if you tap on our button, you will notice that no event will be propagated to its parents.`)

If you run the playground (https://play.nativescript.org/?template=play-tsc&id=iixpoJ&v=2) from the documentation https://docs.nativescript.org/ui/gestures (added [here](https://github.com/NativeScript/docs/pull/1500)), at least on android, a single tap of the button will  show the following output in the console: 
![image](https://user-images.githubusercontent.com/1072625/81063943-5e856980-8e9e-11ea-95ce-deeef7f491dc.png)

Side note, and perhaps this is worth a separate issue: simply changing the wrapping stacklayout in the playground to a FlexboxLayout immediately causes the app to crash (when `isPassThroughParentEnabled="true"` is on the FlexboxLayout). 

![image](https://user-images.githubusercontent.com/1072625/81064148-c5a31e00-8e9e-11ea-9ab4-bf87ea015520.png)
