### ISSUE TITLE
BottomNavigation with a shared bindingContext

### ISSUE THREAD

**Issue by DimitrisRK** [NativeScript/NativeScript#8474]
I'm not sure if it's is a good practice but I thought of this.
Since BottomNavigation extends ViewBase, consists of multiple Frames and therefore developers have the ability to create lazy-loaded pages, I thought that a main binding context would be useful.

What I mean: BottomNavigation will have its own view model as bindingContext set by developer inside 'loaded' event callback, and all tab pages will have access to it while each one will still have a view model as context on its own. If a child context has a property name that is identical to one of parent's, then the parent property will be overridden.

Just imagine an app retrieving data from an API once and share it among all tabs, instead of performing a request on every page navigation. This is especially good when using a lazy pattern into all pages.

**Comment by DimitrisRK** [comment]
Just noticed that the following method works.
Assigning a binding context to 'BottomNavigation' and nesting view models inside it for each page might do the work. But in every xml page, every property will have to get called like 'homeViewModel.title'.
Also, since this is a new component and this approach is not documented, I'm not sure if I should use it.

**Comment by NickIliev** [comment]
> Just noticed that the following method works.
Assigning a binding context to 'BottomNavigation' and nesting view models inside it for each page might do the work. But in every xml page, every property will have to get called like 'homeViewModel.title'.

I see no issue with the above technique - it would help you to reuse specific model logic which is the idea of MVVM/MVC like patterns.

**Comment by DimitrisRK** [comment]
@NickIliev Thanks a lot for answering, that sounds reassuring. Do you think it's right that page binding context fails to initialize if I set root view's (BottomNavigation) context first?
