### ISSUE TITLE
POST request without body content

### ISSUE THREAD

**Issue by MichalWojtczak** [NativeScript/NativeScript#8477]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
Nativescript with Angular
 - CLI: 6.2.0
 - Cross-platform modules: 6.2.0
 - Android Runtime: 6.2.0
 - iOS Runtime: 6.2.0
 - Plugin(s):
 "dependencies": {
    "@angular/animations": "^8.2.12",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "8.2.12",
    "@angular/compiler": "8.2.12",
    "@angular/core": "8.2.12",
    "@angular/forms": "8.2.12",
    "@angular/http": "^7.2.15",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "8.2.12",
    "@angular/platform-browser-dynamic": "8.2.12",
    "@angular/router": "8.2.12",
    "@ckeditor/ckeditor5-angular": "^1.1.0",
    "@ckeditor/ckeditor5-build-classic": "^12.4.0",
    "@ckeditor/ckeditor5-upload": "^11.1.1",
    "@nativescript/schematics": "~0.7.0",
    "@ng-bootstrap/ng-bootstrap": "^4.2.2",
    "@sentry/browser": "^5.7.1",
    "@swimlane/ngx-datatable": "^16.0.2",
    "angular-calendar": "0.26.4",
    "angular-in-memory-web-api": "0.6.1",
    "angular2-ladda": "^2.0.2",
    "angular2-text-mask": "^9.0.0",
    "apolloai-nativescript-status-bar": "^1.1.0",
    "bootstrap": "^4.3.1",
    "ckeditor4-angular": "^1.0.0-beta.2",
    "ckeditor5-simple-upload": "^1.0.7",
    "classlist.js": "1.1.20150312",
    "core-js": "2.5.4",
    "date-fns": "1.29.0",
    "echarts": "4.2.0-rc.1",
    "feather-icons": "4.7.3",
    "highlight.js": "9.13.1",
    "lodash": "latest",
    "mockserver": "^3.1.1",
    "moment": "^2.24.0",
    "nativescript-angular": "^8.21.0",
    "nativescript-grid-view": "^5.1.0",
    "nativescript-ng-shadow": "^2.1.0",
    "nativescript-oauth2": "^2.2.2",
    "nativescript-plugin-firebase": "^10.5.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-listview": "^7.1.0",
    "ng-multiselect-dropdown": "^0.2.6",
    "ng-pick-datetime": "^7.0.0",
    "ng-recaptcha": "^4.3.0",
    "ng2-validation": "4.2.0",
    "ng5-slider": "^1.2.4",
    "ngx-chips": "1.9.8",
    "ngx-clipboard": "^12.2.1",
    "ngx-color-picker": "7.0.1",
    "ngx-dropzone-wrapper": "^8.0.0",
    "ngx-echarts": "4.0.0",
    "ngx-facebook": "^2.4.0",
    "ngx-img-cropper": "0.10.4",
    "ngx-pagination": "3.2.1",
    "ngx-perfect-scrollbar": "6.3.1",
    "ngx-quill": "4.0.0",
    "ngx-spinner": "^7.2.0",
    "ngx-toastr": "9.1.0",
    "popper.js": "1.14.4",
    "qs": "latest",
    "quill": "^1.3.7",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.5.3",
    "tns-core-modules": "~6.2.0",
    "tns-core-modules-widgets": "^6.3.0",
    "tslib": "^1.10.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.9.1"
  },

**Describe the bug**
When I sends POST request with body content then server receives empty body.
I tried Angular HttpClient (1) and standard request post (2) from here https://docs.nativescript.org/ns-framework-modules/http

I called a few different API's, also by Postman. All is fine there.
The weird things are:
1. Aplication builded about 4 months ago using Angular HttpClient. There was no problems (app is even in AppStore)
2. Now I wanted to add some updated and I got this error
3. In a preview mode Angular HttpClient is not working. Standard request IS WORKING
4. After build (checked directly on device) both ways are not working

![image](https://user-images.githubusercontent.com/23667690/77968112-ce746300-72e6-11ea-9a30-8b8092ce76ce.png)
```
 httpModule.request({
            url: "https://dummy.restapiexample.com/api/v1/create",
            method: "POST",
            headers: { "Content-Type": "application/json" },
            content: JSON.stringify({"name":"test123","salary":"123","age":"233"})
        }).then(function(result) {
            console.log('then-------')
            console.log(result.content.toJSON());
        }, function(error) {
            console.log('error-------')
            console.error(JSON.stringify(error));
        });
```

![image](https://user-images.githubusercontent.com/23667690/77968139-db915200-72e6-11ea-95b6-2140ef6d9d48.png)

```
this.http.post(environment.url + RoutesGlobal.SHOP_LIST, {
                page: filters.page,
                pageSize: filters.pageSize,
                search: filters.search,
                categories: categoryIds
              });
```
**To Reproduce**

**Expected behavior**
POST request should work correct with body content

I tried change content type to 'application/x-www-form-urlencoded'
I tried send FormData

**Additional context**

**Comment by NickIliev** [comment]
@MichalWojtczak 

1. Posting code-snippets as a screenshot is not very good practice as anyone interested in reproducing your issue won't be able to copy/paste the code.

2. `Now I wanted to add some updated and I got this error` - where is the error?

Overall the HttpClient should work [as documented in the official Angular documentation](https://angular.io/guide/http) (with small exceptions).

**Comment by MichalWojtczak** [comment]
@NickIliev Thanks for reply. Yeah, my bad. I forgot to paste code. I added it to main description.

> Now I wanted to add some updated and I got this error - where is the error?

I meant that 4 months ago I created this app. All was fine. App was builded correctly. Even I added it to the PlayStore. 
After 4 months (so now) I wanted to add some extensions and new functionalities but I discovered this issue.

> Overall the HttpClient should work as documented in the official Angular documentation (with small exceptions).
I know it. I have a experience in Angular (I developed 2 web aplication already). I implemeneted a lot of HttpClient functions :) 
The thing is I don't know what is causing this kind of problem. I thought that some new special permissions was added to the Android (and this is removing body content). I was searching info about it but I failed.

**Comment by NickIliev** [comment]
@MichalWojtczak the following works fine on my side:

```TypeScript
getHttp() {
    this.httpClient.post(
        "https://dummy.restapiexample.com/api/v1/create",
        {
            "name": "test123",
            "salary": "123",
            "age": "233"
        })
        .subscribe((result) => {
            console.dir(JSON.stringify(result));
        });
}

// returns the following:
// [Pixel 3 XL]: {"status":"success","data":{"name":"test123","salary":"123","age":"233","id":49}}
```

Here is [the test Playground](https://play.nativescript.org/?template=play-ng&id=BpEgU9)

**Comment by MichalWojtczak** [comment]
Hello
I was debugging it for a lot of hours. Without results. As a last idea I upgraded all of NS modules and dependencies. I migrated from 6.2 to 6.5 
Now all is working :) 
Topic to close
