### ISSUE TITLE
Text-Transform not working on TabStripItem

### ISSUE THREAD

**Issue by cavalos0086** [NativeScript/NativeScript#8478]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.5.0
 - Cross-platform modules: 6.5.1
 - Android Runtime: none
 - iOS Runtime: 6.5.0
 - Plugin(s):
```
"@ngx-translate/http-loader": "^4.0.0",
    "@nstudio/nativescript-loading-indicator": "^3.0.4",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "nativescript-camera": "^4.5.0",
    "nativescript-carousel": "^6.1.1",
    "nativescript-gif": "^4.0.2",
    "nativescript-plugin-firebase": "^10.5.0",
    "nativescript-ui-autocomplete": "^6.0.1",
    "nativescript-ui-listview": "^8.1.0",
```
**Describe the bug**
TextTransform in <Label> inside <TabStripItem> doesn't  work. In the docs it says:
```
Currently, we can set only the backgroundColor, color, fontFamily, fontSize, fontStyle, fontWeight and textTransform styling properties to the Label and Image components inside the TabStripItem.
```
so it should work.

**To Reproduce**
See attached playground link

**Expected behavior**
I should be able to use text transform values and use "capitalize" or "lowercase" 

**Sample project**
https://play.nativescript.org/?template=play-ng&id=RTOmJA

Thank you Nativescript team for looking into this!

**Comment by NickIliev** [comment]
Behind `Tabs` on iOS, the native component is `MDCTabBar` which does not allow styling of individual tab strip items ()noted as a limitation in the documentation). So that said there is no option to use text=transform on iOS.

> iOS Limitation!! You can’t style individual TabStripItem components on the iOS Tabs component. You can style them on the TabStrip component together.

This is a Tabs specific issue for iOS (not present for `BottomNavigation`).


For `Tabs` now the styling is controlled entirely through the `TabStrip` component.

```CSS
TabStrip {
   backgorund-color: orangered;
   selected-item-color: blue;
   un-selected-item-color: green;
}
````

**Comment by cavalos0086** [comment]
Thanks for your fast reply @NickIliev .
