### ISSUE TITLE
Composite Components: Not apply style of files .SCSS

### ISSUE THREAD

**Issue by wellyson21** [NativeScript/NativeScript#8483]
TNS: 6.5.0

"devDependencies": {
    "css-loader": "^3.4.2",
    "nativescript-dev-webpack": "~1.5.1",
    "node-sass": "^4.13.1",
    "sass-loader": "^8.0.2",
    "typescript": "~3.5.3",
    "webpack": "^4.42.1"
  },

**Describe the bug**
I created a component with .SCSS style but it does not apply the style. need to be specifically .css the style file?

**Expected behavior**
Load component with style.

**Sample project**
[sample.zip](https://github.com/NativeScript/NativeScript/files/4411629/sample.zip)

**Comment by NickIliev** [comment]
@wellyson21 the provided project is not very useful as it uses Firebase configs that are missing and prevent the build. Also, it is not clear which SCSS file is not applied. I've also noticed that you are having SCSS and CSS files under the same name - is that on purpose?

Closing the issue as not enough information is provided but we can continue the discussion here

**Comment by wellyson21** [comment]
In the case here I'm only managing to apply style to the components only with .css files so these were still there in the example, I forgot to remove them. I already cleaned the project and removed all dependencies including the firebase and here it is.

[sample.zip](https://github.com/NativeScript/NativeScript/files/4414604/sample.zip)

this sample is executable.

![Captura de Tela 2020-04-01 às 07 58 25](https://user-images.githubusercontent.com/26719586/78129854-9ce6bf00-73ee-11ea-98ee-1987cae248e8.png)

**Comment by wellyson21** [comment]
I edited the issue and await your response. Thanks.
