### ISSUE TITLE
[android]last changes in text-base breaks plugins

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/NativeScript#8486]
i am using latest version 6.5.1
And the latest change in the framework in 6.5.0 broke my plugin `nativescript-material-textfield`
in this line https://github.com/NativeScript/NativeScript/blob/master/nativescript-core/ui/text-base/text-base.android.ts#L107 you access `this.nativeView` instead of `nativeView`

This is a very easy fix but a pretty important bug in my case and for all people using my plugin.

Thanks

**Comment by vtrifonov** [comment]
But this is not in the release branch yet https://github.com/NativeScript/NativeScript/blob/release/nativescript-core/ui/text-base/text-base.android.ts#L68

**Comment by farfromrefug** [comment]
@vtrifonov damn you are right i was using link version to the master branch ;)
Sorry so i change it to "it will be an issue"
Sorry i thought it was released with 6.5.1...
