### ISSUE TITLE
Unable to install app

### ISSUE THREAD

**Issue by vforv** [NativeScript/NativeScript#8490]
I created .ipa file with:

`tns build ios --bundle --env.environment="prod" --env.uglify --env.aot --release --for-device --provision ...`

Used distribution provisioning profile

After I shared file with my iPhone and tried to install icon become black and when I click on it get: 

Unable To install popup

Any idea what is problem?
I want to be able to share my build with others for testing

**Comment by NickIliev** [comment]
@vforv try to directly deploy & and run the build on the physical device with `tns run ios <additional-params-here>`
