### ISSUE TITLE
TextField event, (textChange). Not working on device keyboard.

### ISSUE THREAD

**Issue by ElecTreeFrying** [NativeScript/NativeScript#8494]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: `6.5`
 - Android Runtime: `6.5`
 - Plugin(s): `nativescript-ui-sidedrawer`, `nativescript-material-ripple`
 - Angular + Nativescript

**Describe the bug**

`TextField`'s event `(textChange)` works only at keyboard input but not on device keyboard. See below.

![ns](https://user-images.githubusercontent.com/19801459/78251221-9e65d380-7523-11ea-9425-1a6fbe4be249.gif)

**To Reproduce**

```html
<TextField
  ...
  returnKeyType="go"
  hint="Search pokémon"
  textAlignment="left"
  (textChange)="onTextChange($event)">
</TextField>
...
<MDRipple
  ...
  *ngFor="let item of pokemon">
  <FlexboxLayout>
    <Label
      ...
      [text]="'#' + item?.entry_number + ' '"></Label>
    <Label
      ...
      [text]="item?.name"></Label>
    <Image
      ...
      [src]="item?.image">
    </Image>
  </FlexboxLayout>
</MDRipple>
```

```ts
onTextChange(event: EventData) {
  const object = <TextField>event.object;
  const text = object.text;

  this.pokemon = this._pokemon.filter((e: any) => e['name'].includes(text));

  if (text.length > 0) {
    this.textFieldActive = true;
  } else {
    this.textFieldActive = false;
    this.pokemon = this._pokemon;
  }
}
```

**Expected behavior**

From the example below. I want the same behavior on input in laptop keyboard and device keyboard input.

![ns](https://user-images.githubusercontent.com/19801459/78251221-9e65d380-7523-11ea-9425-1a6fbe4be249.gif)

**Sample project**

n/a

**Additional context**

n/a

**Comment by ElecTreeFrying** [comment]
solved the problem

**Comment by matteonatale** [comment]
Hi @ElecTreeFrying,
I'm working on a Nativescript-Vue app with Nativescript 8. I made a custom Vue component for all textfields of my app, but on Android the textChange event doesn't work. How did you solve it?

**Comment by sercanozen** [comment]
+1 same problem

**Comment by matteonatale** [comment]
Thank you @sercanozen, now it works! 😉
