### ISSUE TITLE
Image blinks out on forward/backward navigation

### ISSUE THREAD

**Issue by ElecTreeFrying** [NativeScript/NativeScript#8497]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: `6.5`
 - Android Runtime: `6.5`
 - Plugin(s): `nativescript-ui-sidedrawer`, `nativescript-material-ripple`
 - Nativescript + Angular app

**Describe the bug**

The image is blinking out on forward/backward navigation.

![saaa](https://user-images.githubusercontent.com/19801459/78347660-6a49eb80-75d3-11ea-8cd1-6993c603a239.gif)

**To Reproduce**

```html
<Image
  class="image"
  horizontalAlignment="right"
  decodeHeight="70"
  decodeWidth="70"
  width="70"
  height="70"
  isLoaded="true"
  isLoading="true"
  loadMode="async"
  [src]="item?.image">
</Image>
```

```ts
toPokemon(pokemon: any) {
  ...
  this.router.navigate(['/', 'pokemon-data'], {
    ...
  });
}
```

**Expected behavior**

The image should stay and should not blink out on forward/backward navigation.

**Sample project**

n/a

**Additional context**

n/a

**Comment by NickIliev** [comment]
@ElecTreeFrying providing a sample project is a must so we could investigate the case.

FOr example, it is now clear what is happening behind `[src]=" item?.image"` - is this an async call to an online API? Is the URL present during the page loading or are you running an async call and fetching the data? In the second case, I would say that your behavior is expected.

Note: The properties **isLoading** and **isLoaded** are not to be set - they are meant to be used as getters (in the **loaded** callback).

**Comment by ElecTreeFrying** [comment]
thanks for the reply @NickIliev. I created a temporary repo. Here's the project. the image is still blinking on forward/backward navigate.

Yes this is is an async call to an online api.

I'm not sure about this. *"...Is the URL present during the page loading or are you running an async call and fetching the data ."*. From my sample project this is how I call the image from an online api.

``` html
<Image
  loadMode="async"
  src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png">
</Image>
```

I see. Thanks for the additional information about `isLoading` and `isLoaded`.

https://github.com/ElecTreeFrying/async-image

![issue](https://user-images.githubusercontent.com/19801459/78547742-299bdd80-7832-11ea-8700-7793f622926a.gif)

**Comment by ElecTreeFrying** [comment]
any temporary fix for this issue ?

**Comment by NickIliev** [comment]
@ElecTreeFrying I've tested n several emulators but I am not able to reproduce the issue - can you let me know on what API level () is the above happening?

**Comment by ElecTreeFrying** [comment]
I don't know what happened. I just randomly updated my genymotion emulator from 3.0.1 to the latest version 3.1.0 after reading your comment. And is now working well. Ill close this issue now. thanks thanks !
