### ISSUE TITLE
Cannot set "isUserInteractionEnabled" programatically in TextField

### ISSUE THREAD

**Issue by Rahul1d** [NativeScript/NativeScript#8498]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.5
 - Cross-platform modules: 6.5
 - Android Runtime: 6.5
 - iOS Runtime: 6.5
 - Plugin(s): no plugins

**Describe the bug**
Initially, TextField is set isUserInteractionEnabled=false.
I am trying to set TextField to editable on click of button. But, i am not able to enable it.

**To Reproduce**
https://play.nativescript.org/?template=play-ng&id=gSZUmD&v=3

**Expected behavior**
TextField should be enabled is isUserInteractionEnabled = true

**Sample project**
https://play.nativescript.org/?template=play-ng&id=gSZUmD&v=3

**Additional context**

**Comment by NickIliev** [comment]
You could use `editable` instead https://play.nativescript.org/?template=play-ng&id=gSZUmD&v=5

**Comment by Rahul1d** [comment]
Hi @NickIliev ,
I tried editable instead of isUserInteractionEnabled. 
But secure has issue if used along with editable.


This video describes the issue.
https://imgur.com/a/jOYKNl2
