### ISSUE TITLE
TextField "secure" and "editable" issue

### ISSUE THREAD

**Issue by Rahul1d** [NativeScript/NativeScript#8499]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.2
 - Cross-platform modules:
 - Android Runtime: 6.5.0
 - iOS Runtime: 6.5.0
 - Plugin(s): No

**Describe the bug**
 I am using TextField to show password . Intially, it is not editable also hidden.
for this , i have set secure = true and editable = false;

Now, TextField is set to editable on click of button. Also, I have secure = true;
But , even after that , it appears hidden. One can refer to playground link here: https://play.nativescript.org/?template=play-ng&id=kL8k2i

**To Reproduce**
https://play.nativescript.org/?template=play-ng&id=kL8k2i

**Sample project**
https://play.nativescript.org/?template=play-ng&id=kL8k2i

**Comment by NickIliev** [comment]
@Rahul1d in your original code you've used a single property for both and both were set to false and then to true. I've modified the e[PLayground demo](https://play.nativescript.org/?template=play-ng&id=kL8k2i)

```HTML
<GridLayout>
    <ScrollView>
        <StackLayout class="home-panel">
            <!--Add your page content here-->
            <TextField text="Data" [secure]="secure" [editable]="editable"
                backgroundColor="green" color="black"></TextField>

            <Button text="Button" (tap)="onButtonTap()" backgroundColor="red"
                color="black"></Button>

        </StackLayout>
    </ScrollView>
</GridLayout>
```

and the component code-behind
```TypeScript
export class HomeComponent implements OnInit {

    secure: boolean = false;
    editable: boolean = false;

    onButtonTap(): void {
        console.log("Button was pressed");

        this.secure = true;
        this.editable = true;
    }

    constructor() {
    }

    ngOnInit(): void {
    }
}

```

**Comment by Rahul1d** [comment]
Hi @NickIliev ,
 I think there is some issue. 
I want to set secure to false and editable to true on click of button. 
But, even after when i set secure to false, the text appears as hidden.

I have modified the https://play.nativescript.org/?template=play-ng&id=kL8k2i according to my requirement.

Here, is the link of video, which describes the issue.
https://imgur.com/a/jOYKNl2
