### ISSUE TITLE
Missing constants from TS definitions and runtime for android

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#850]
I'm writing some code to save a new contact and noticed that the following constants seems to be missing from the .d.ts:
```Java
android.provider.ContactsContract.RawContacts.ACCOUNT_TYPE
android.provider.ContactsContract.RawContacts.ACCOUNT_NAME
android.provider.ContactsContract.Data.RAW_CONTACT_ID
android.provider.ContactsContract.Data.MIMETYPE
android.provider.ContactsContract.CommonDataKinds.Phone.TYPE
android.provider.ContactsContract.CommonDataKinds.Email.DATA
android.provider.ContactsContract.CommonDataKinds.Email.TYPE
android.provider.ContactsContract.CommonDataKinds.StructuredPostal.TYPE
```

**Comment by PeterStaev** [comment]
Seems not only the definitions are missing but also the android runtime is missing support for those constants. Learned it the hard way, spending couple of hours trying to make a simple contact add code to work... Ended up adding local constants with the correct string values for each of those

**Comment by enchev** [comment]
This issue was moved to NativeScript/android-runtime#235
