### ISSUE TITLE
Example App crashes on tab click

### ISSUE THREAD

**Issue by baermathias** [NativeScript/NativeScript#8500]
**Environment**
Galaxy S8 + Android 

**Describe the bug**
The official NativeScript Examples app crahes.

**To Reproduce**
Download the NativeScript example app (https://www.nativescript.org/nativescript-example-application), open it, navigate to charts and then click between the different tabs a few times.

**Expected behavior**
Stay stable

**Comment by srghma** [comment]
it didn't crash for me on galaxy s8

could you post `adb logs`, please https://stackoverflow.com/a/46932133/3574379

**Comment by ElecTreeFrying** [comment]
tried reproducing. didn't crashed on me also.
