### ISSUE TITLE
App crash whe using useCache="true" Image tag property on tns run android with Android 6+ 

### ISSUE THREAD

**Issue by ofe2358** [NativeScript/NativeScript#8505]
**Environment**
 - CLI:  "6.3.1"
 - Android Runtime: from Android 6 and any higher versions
 - NativeScript-Angular: "~8.20.0",
 - Angular:"~8.2.0",

**Describe the bug**
Using useCache property on Image tag like this (only on Android v6++)

` <Image useCache="true"  src="~/image.png"></Image>`

and runing for development (tns run android) app crash with this trace log:

> System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: JNI Exception occurred (SIGABRT).
System.err: =======
System.err: Check the 'adb logcat' for additional information about the error.
System.err: =======
System.err: StackTrace:
System.err: push.../node_modules/@nativescript/core/ui/image/image.js.Image._createImageSourceFromSrc(file:///node_modules/@nativescript/core/ui/image/image.js:103:0)
System.err:     at push.../node_modules/@nativescript/core/ui/image/image.js.Image.<computed>(file:///node_modules/@nativescript/core/ui/image/image.js:167:0)
System.err:     at applyAllNativeSetters(file:///node_modules/@nativescript/core/ui/core/properties/properties.js:1046:0)
System.err:     at initNativeView(file:///node_modules/@nativescript/core/ui/core/properties/properties.js:990:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onResumeNativeUpdates(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:628:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._resumeNativeUpdates(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:273:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:232:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file:///node_modules/@nativescript/core/ui/core/view/view.js:247:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:440:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0)
System.err:     at push.../node_modules/@nativescript/core/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///node_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules/@nativescript/core/ui/core/view/view-common.js:1010:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:233:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file:///node_modules/@nativescript/core/ui/core/view/view.js:247:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:440:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0)
System.err:     at push.../node_modules/@nativescript/core/ui/content-view/content-view.js.ContentView.eachChildView(file:///node_modules/@nativescript/core/ui/content-view/content-view.js:70:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules/@nativescript/core/ui/core/view/view-common.js:1010:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:233:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file:///node_modules/@nativescript/core/ui/core/view/view.js:247:0)
System.err:     at push.../node_modules/@nativescript/core/ui/scroll-view/scroll-view-common.js.ScrollViewBase.onLoaded(file:///node_modules/@nativescript/core/ui/scroll-view/scroll-view-common.js:31:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:440:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0)
System.err:     at push.../node_modules/@nativescript/core/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///node_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules/@nativescript/core/ui/core/view/view-common.js:1010:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:233:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file:///node_modules/@nativescript/core/ui/core/view/view.js:247:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:440:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0)
System.err:     at push.../node_modules/@nativescript/core/ui/content-view/content-view.js.ContentView.eachChildView(file:///node_modules/@nativescript/core/ui/content-view/content-view.js:70:0)
System.err:     at push.../node_modules/@nativescript/core/ui/page/page-common.js.PageBase.eachChildView(file:///node_modules/@nativescript/core/ui/page/page-common.js:126:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules/@nativescript/core/ui/core/view/view-common.js:1010:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:233:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file:///node_modules/@nativescript/core/ui/core/view/view.js:247:0)
System.err:     at push.../node_modules/@nativescript/core/ui/page/page.js.Page.onLoaded(file:///node_modules/@nativescript/core/ui/page/page.js:43:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:440:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._addViewCore(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:435:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._addView(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:421:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame.js.FragmentCallbacksImplementation.onCreateView(file:///node_modules/@nativescript/core/ui/frame/frame.js:700:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/fragment.js.FragmentClass.onCreateView(file:///node_modules/@nativescript/core/ui/frame/fragment.js:29:0)

**It does not happen on lower Android versions, or when realease build APK**

**To Reproduce**
With an app with any html like this
` <Image useCache="true"  src="~/image.png"></Image>`
on Android 6+ when tns run android

**Comment by NickIliev** [comment]
Closing as a duplicate to https://github.com/NativeScript/NativeScript/issues/8217
