### ISSUE TITLE
List Picker not working on Android API 29 / Android 10

### ISSUE THREAD

**Issue by matty0005** [NativeScript/NativeScript#8508]
- Android Runtime: "6.4.1"

While the ListPicker UI component works on older API versions of Android, it crashes my app when I go to view it on API 29.

I noticed an issue was raised a while ago #7785, but it seems as though the bug still exists, at least for me. I have updated my Android runtime, removed/reinstalled node_modules, but this also didn't solve the problem.

Here is the error
```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: java.lang.NoSuchFieldException: No field mSelectorWheelPaint in class Landroid/widget/NumberPicker; (declaration of 'android.widget.NumberPicker' appears in /system/framework/framework.jar!classes3.dex)
```

**Comment by NickIliev** [comment]
@matty0005 tried to reproduce the issue but to no avail. I've used[ this demo app](https://github.com/NickIliev/NS-Issues-2020/tree/master/NativeScript/issue-8508) and deployed on an Android 10 (API 29) emulator.

**Comment by matty0005** [comment]
@NickIliev I tried the sample app you provided, and it works just fine for me.
I forgot to mention i am using NS + Vue - I don't know if that makes any difference at all.

As for the question, I don't recall ever setting a specific compileSdk value.
If it helps, here is my AndroidManifest.xml file.
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="__PACKAGE__" android:versionCode="10002" android:versionName="1.0.0">
    <supports-screens android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true" />
    <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="__APILEVEL__" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <application android:name="com.company.app" android:allowBackup="true" android:icon="@drawable/icon" android:label="@string/app_name" android:theme="@style/AppTheme">
        <activity android:name="com.tns.NativeScriptActivity" android:label="@string/title_activity_kimera" android:configChanges="keyboardHidden|orientation|screenSize" android:theme="@style/LaunchScreenTheme">
            <meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name="com.tns.ErrorReportActivity" />
    </application>
</manifest>
```

**Comment by NickIliev** [comment]
@matty0005 check your `app.gradle` file (for the **compileSdkVersion** property)

**Comment by matty0005** [comment]
@NickIliev My `app.gradle` file located in `App_Resources/Android` doesn't contain the compileSdkVersion - as seen below. Is it supposed to specify it?
```
dependencies {
    implementation(name:'brother_label_printer', ext:'aar')
}

android {
  defaultConfig {  
    generatedDensities = []
    applicationId = "com.company.app"
  }
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }  
} 
```

**Comment by NickIliev** [comment]
No, no need to explicitly set the property - I was just wondering if an explicit value might be causing the issue. Could you check what is the version of the installed android SDKs (SDK Manager) and build tools  (SDK Manager > SDK Tools > Android SDK Build tools). - try to update it to the latest if you are using an older version.

**Comment by matty0005** [comment]
I had Android 10 (API 29), Android 9 (API 28) and Android 8.0 (API 26) for the SDK Platforms. As for the SDK Build tools, I just downloaded all of them to make sure it wasn't it, but now it works. 
Cheers.
