### ISSUE TITLE
iOS. HtmlView mixing styling with other HtmlView inside ListView

### ISSUE THREAD

**Issue by RustamAkimov** [NativeScript/NativeScript#8512]
### Environment
 - CLI: 6.4

### Describe the bug
HtmlViews start to mix styling (b, font, small etc..) inside ListView after **multiple scrolling up and down** in iOS version

### To Reproduce
Populate a few HtmlView contents inside ListView with styled content: 
` this.items.push('<b>Bold text</b>');`

And other contents without any styling:
```
 for (var i = 0; i < 100; i++)
            this.items.push('simple text<br/>text<br/>text<br/>');
```

After multiple scrolling up and down some simple contents start having styled content styling 
![File (1)](https://user-images.githubusercontent.com/1545864/78818679-a77af880-799a-11ea-9493-e13dd4ad385e.jpg)

## Sample project
https://play.nativescript.org/?template=play-ng&id=eHVx9W&v=3

**Comment by NickIliev** [comment]
The ListView recycles each cell which is causing the issue. You should change the styles through the bonded data model and not through the UI (as the UI within the list view cell will be recycled and re-used which would lead to the above behavior).

See[ this thread for details](https://github.com/NativeScript/NativeScript/issues/1265#issuecomment-165468381)

**Comment by RustamAkimov** [comment]
@NickIliev thank you.

In my case, i could not move styling on htmlview level as content itself contains **multiple** styling tags like `b, u, font size`

issue fixed when content was wrapped with `<html><body><span style='defStyles'> `tags
where defStyles are default styles for color, font family, font size etc
