### ISSUE TITLE
Which percentage Do Nativescript-Vue cover  Nativescript API engine?

### ISSUE THREAD

**Issue by biapar** [NativeScript/NativeScript#8513]
Which percentage Do Nativescript-Vue cover  Nativescript API engine?

**Comment by NickIliev** [comment]
@biapar you can use 100% of the UI components (like Label, GridLayout, SerarchBar, etc.,) and the framework modules (like application, platform, application-settings). You are also able to access 100% from the native APIs (Android and iOS).

There are, of course, some differences in the way the navigation works when using different abstractions (like Vue or Angular) on which you should consult with [the NativeScript Vue documentation.](https://nativescript-vue.org/en/docs/elements/components/list-view/)
