### ISSUE TITLE
support #rrggbbaa instead of #aarrggbb

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/NativeScript#8517]
in the web the standard is `#rrggbbaa` but {N} supports `#aarrggbb`
Right now i am facing an issue with webpack which is wrongly translated colors in production
https://github.com/NativeScript/nativescript-dev-webpack/issues/1133

It also have bad side effects like in VSCode which wrongly shows those colors. 

Now i know it is a breaking change for user. So what i am thinking about is a flag in the app package.json to use the new format.

Would you agree with that? (i could make a simple PR)

**Comment by NathanaelA** [comment]
@farfromrefug - Make a PR for this.   No need for a flag -- I think it would best to match the web as much as possible.    We should be able to put this into NS 7 as NS 7 will have other breaking changes...   :-)

**Comment by farfromrefug** [comment]
@NathanaelA here is the PR https://github.com/NativeScript/NativeScript/pull/8519
