### ISSUE TITLE
how to use third part library whitch has a special function

### ISSUE THREAD

**Issue by cartmanchen** [NativeScript/NativeScript#852]
>
@interface RCObject: NSObject
-(void)connectWithToken:(NSString *)token
                            success:(void (^)(NSString *userId))successBlock
                                 error:(void (^)())errorBlock
@end
  

i use it like this
>  var obj = RCObject.alloc().init();
   obj.connectWithToken(MY TOKEN, function(userId){}, function(){});

but it throw a exception:
obj.connectWithToken is undifned

**Comment by fealebenpae** [comment]
Hi @cartmanchen,

When translating Objective-C method names to JavaScript, the NativeScript runtime takes the selector for a method, in this case `connectWithToken:success:error:`, and converts it in a JavaScript identifier like so: `connectWithTokenSuccessError`.

**Comment by cartmanchen** [comment]
Thank you.
It's ok.
