### ISSUE TITLE
(Bug Bounty $15) iOS Bug: Tab View, on indexChange back to first page does mot load the viewModel 2-Way Binding

### ISSUE THREAD

**Issue by gnubyte** [NativeScript/NativeScript#8522]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.5.0 TNS version
 - Cross-platform modules: iOS, Android
 - Android Runtime:
 - iOS Runtime: 13.4
 - Plugin(s):

**Describe the bug**
Tab View, on indexChange back to first page does mot load the viewModel 2-Way Binding. When navigating to the first tab, then back to the second tab, the first tab's view model doesn't load.

**To Reproduce**
Create a tab view page, that contains tabViewItems in it. Each tabViewItem has its own page, and content that is managed like a normal page.

Navigate to the config page. This page, with static content, shows. When navigating back the first tab's listView shows, and the actionbar of the page loads, but NOT the 2 way binding itself. The onload event fires off, and the viewmodel when console logged shows data. 
```
<Page actionBarHidden="true" loaded="loaded" >
    <TabView androidTabsPosition="bottom" >
    <TabViewItem title="FooPage">
        <Frame defaultPage="views/foo/first-page"></Frame>
    </TabViewItem>
    <TabViewItem title="Config">
        <Frame defaultPage="views/config/config-page"></Frame>
    </TabViewItem>
    </TabView>
</Page>
```

**Expected behavior**

2 way binding data should show ;-)

**Comment by NickIliev** [comment]
@gnubyte how is your view model loaded (are you using a specific event? is it by chance lazily loaded in the JS file?).

As a side note, the `TabView` component is deprecated in favor of two new components `Tabs` and `BottomNavigation`.

**Comment by gnubyte** [comment]
@NickIliev greatly appreciate you taking a look at this!

> how is your view model loaded
> is it lazy loaded

I'm fairly new to javascript's nomenclature and the typescript multiverse...so bear with me here. From what I've read lazy loading is not initializing an object, until it is needed by the DOM. I'd imagine I'd have to indicate that to Nativescript somehow, to lazily load the view object here. I believe I am initializing the view model object in the global namespace for that page once, then changing pages, and then on selectIndex in the tab view, navigating back to that frame & its page. At that point, I can see the `console.log` get events but the page's view model two way binding isn't seeing them. Codes below, I don't think I am lazy loading here.



**page in question**
```
// --------------------------------
// Imports
var frameModule = require("tns-core-modules/ui/frame");
var observableModule = require("tns-core-modules/data/observable")
var ObservableArray = require("tns-core-modules/data/observable-array").ObservableArray;
var fooViewModel = require("../shared/view-models/foo-view-model");

// --------------------------------
// Global Initializations
var page;
var foo = new fooViewModel();

exports.loaded = function(args) {
    console.log(Data);
    console.log(Data.someAttribute.length);
    page.actionBarHidden = true;
    console.log('Loaded page full of foo');
    page = args.object;
    page.bindingContext = Notes;
    fetchFoo()
    
};



function fetchFoo(){
    Data.fetchFoo(); //view model method invoked here
    console.log('Fetched foo');
}
```



**view model:**

```
var couchbaseModule = require("nativescript-couchbase");
var observableModule = require("tns-core-modules/data/observable");
var config = require("../../shared/config");
var applicationSettings = require("tns-core-modules/application-settings");

function foo(data) {
    //Param cleansing
    data = data || {};

    // Database config
    var database = new couchbaseModule.Couchbase(config.database);

    // Live Page Binding
    var viewModel = new observableModule.fromObject({
        foo: data.foo || []
    });

    // Event emitter
    database.createView("foo", "1", function(document, emitter) {
        emitter.emit(document._id, document);
    });

     // Function
    viewModel.fetchFoo = function (){
        console.log('resetting view model foo list to zero so we dont populate duplicates');
        viewModel.foo = [];
        var rows = database.executeQuery("foo", {descending : true, limit : 20});
        for(var i = 0; i < rows.length; i++) {
            viewModel.foo.push(rows[i])
            console.log('pushing new updated foo listing: '+rows[i]);
        }
        // Good testing mechanism:
        //console.log("Viewmodel Foo:"+viewModel.foo[0]._id)
    } // end fetchFoo
    
    
    
    return viewModel;

}//end Foo

module.exports = Foo;
```

I can go ahead and try the Tabs and BottomNavigation as well.

**Comment by gnubyte** [comment]
Hey Bug bounty starting at $15 USD is live. 

Come in, solve the issue, and get paid for your work. I appreciate anyones time on this issue and need it solved.

https://www.bountysource.com/issues/91061397-ios-bug-tab-view-on-indexchange-back-to-first-page-does-mot-load-the-viewmodel-2-way-binding

**Comment by gnubyte** [comment]
So thank you @NickIliev for your inquiry into how my view model was loading. It got me to evaluate how I was loading my model. 

Specifically using basic javascript to directly access child objects of the parent(view model) object was what was breaking the code:

```
// Does NOT work since we are directly accessing the view model
viewModel.foo = []; //reset my model back to nothing for a refresh of the data contained in the 2 way binding
var rows = obj.executeQuery('select foos where foo.bar = *');
for(var i = 0; i < rows.length; i++) {
            viewModel.notes.push(rows[i]);
        }
```


Below solution does work. I would assume because it uses the view Models builtin methods - which probably support lazy loading. I haven't tried using promises, but my understanding is that whatever I would have tried, needs to have nativescript support/leverage: my point being that promises conceptually should offer the same functionality of run operation, run + load in background while foreground page loads. Promises, like me directly accessing a child object, seems to suggest that maybe promises are not guaranteed to work either.

```
// This solution does work, and loads on page every time
viewMode.set('foo', []);
var rows = db.executeQuery('some SQL');
viewModel.set('foo', rows);
```

As general feedback to Nativescript team &/ || Progress from the perspective of a new trail-blazing Nativescript dev:

 - an example outside of angular, in plain JS would be killer here: https://docs.nativescript.org/angular/performance-optimizations/lazy-loading
 - audience using nativescript can be varied in experience, a concept like lazy loading/explained would be nice to see touched on in nativescript playground
 - Slack/Github/Stackoverflow in 2020 seems to lack a large support audience that you might get with React Native or python. Would be nice to see some "get an hour of consulting/support" on the Nativescript site, and I would be willing to pay for that if reasonably priced or if some minimal amount of hours were in a subscription "solo developer" subscription tier --- in addition to the Slack/Github audience seeing some boost in nativescript subject matter experts


Thank you again for the help/support @NickIliev for your comment.

Cheers.
