### ISSUE TITLE
TextField : setting secure to false has not effect if editable set to false

### ISSUE THREAD

**Issue by Rahul1d** [NativeScript/NativeScript#8523]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.5
 - Cross-platform modules:6.5
 - Android Runtime:6.5
 - iOS Runtime:6.5
 - Plugin(s):

**Describe the bug**
Hi,
In TextField, editable is set to false. I am trying to toggle between secure and not secure. But Unfortunately, text is hidden and not visible even if secure is set to false.

**To Reproduce**
https://play.nativescript.org/?template=play-ng&id=qGgSQQ&v=4

**Comment by NickIliev** [comment]
Confirming the issue as a bug - once **editable** is set to **false** there is no toggling the **secure** option (in fact, the value is changed but the UI is not updated and the TextField stays secure)
