### ISSUE TITLE
Frame & BottomNavigation (as root) + 'visibility' binding problem

### ISSUE THREAD

**Issue by DimitrisRK** [NativeScript/NativeScript#8528]
**Environment**
 - CLI: 6.4
 - Cross-platform modules:
 - Android Runtime: 6.4.1
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
'visibility' attribute binding does not work if trying to perform a binding expression using an observable parent or child.

**To Reproduce**
This is an example where parent of current page has its own binding context:
```
<StackLayout backgroundColor="#fff" visibility="{{ $parents['Frame'].isBusy ? 'visible' : 'hidden' }}"/>
<ActivityIndicator busy="{{ $parents['Frame'].isBusy }}" backgroundColor="red" width="50" height="50"></ActivityIndicator>
```
Works perfectly fine for ActivityIndicator.

**Expected behavior**
'visibility' attribute value should change when parent property value changes.

**Comment by NickIliev** [comment]
Is your view model attached to the Frame? You could try to set the view-model on the root for the Page and not the Frame. 

Anyway - providing a sample project or Playground that demonstrates your case will be much appreciated.

**Comment by DimitrisRK** [comment]
> Is your view model attached to the Frame? You could try to set the view-model on the root for the Page and not the Frame.
> 
> Anyway - providing a sample project or Playground that demonstrates your case will be much appreciated.

View model is attached to a 'BottomNavigation' root. Same issue with $parents['BottomNavigation']. I used $parents['Frame'] as an example here since 'Frame' can also be a root view depending on the application structure. Thing is I have such issues only when meddling with 'visibility'. Every other binding seems to work.

I'll also try to provide a sample when I get more free time. Thanks.

**Comment by DimitrisRK** [comment]
@NickIliev Here is a sample to replicate the issue using a timer: https://play.nativescript.org/?_ga=2.83013270.1403707195.1586719014-124534118.1582156580&template=play-js&id=LfG2yx&v=14

**Comment by DimitrisRK** [comment]
Here is another playground that confirms the problem is expression-related: https://play.nativescript.org/?_ga=2.83013270.1403707195.1586719014-124534118.1582156580&template=play-js&id=LfG2yx&v=28

However, expression binding will still work with page binding.
