### ISSUE TITLE
Button focus is essential

### ISSUE THREAD

**Issue by DimitrisRK** [NativeScript/NativeScript#8534]
**Environment**
 - CLI: 6.4
 - Cross-platform modules:
 - Android Runtime: 6.4.1
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
1) TextField won't lose focus if click on another elements like Button. **Cursor remains there**.
I believe it's essential that at least Buttons should become focusable if possible.
If automatic isn't an option, manual focus would be as helpful. I mean one could call 'focus()' method during 'tap' event.
Also, after searching, I noticed that both platforms have native support for button focus.

2) In a scrolled form, if I have a focused text field at the top, and go down to submit button and tap "back" to close softkeyboard while scrolled down, **page will automatically scroll to the height of focused text field**. This issue also applies to 'RadDataForm' plugin editors.
Playground: https://play.nativescript.org/?template=play-js&id=Lyo9AU&v=5

**To Reproduce**
1) Click inside a text field. Then click on a button.
2) Click inside a text field. Scroll down to button (it's important to keep soft keyboard open). When you are done scrolling, tap "back" to close keyboard and **page will automatically scroll back to text field**. You can tap button, but it will make no difference since it's not focusable. If it was, there would be the ability to close soft keyboard on button tap.

**Expected behavior**
TextField should lose focus, removing cursor and focusing Button.

**Sample project**
1) https://play.nativescript.org/?template=play-js&id=Lyo9AU&v=3
2) https://play.nativescript.org/?template=play-js&id=Lyo9AU&v=5

**Additional context**
About no. 2, I think TextField cursor staying there is the root of the problem.

There is an old bug report here #6905 where it's suggested that one can focus another text field to call blur event for previous text field but then we have another focused text field.

Issue 2 is quite serious as it also causes problems among RadDataForm editors.

**Comment by NickIliev** [comment]
@DimitrisRK there is a **_focus_** method that could be called on each component that extends the NativeScript's **View**. However, by default, the Android Button is not focusable and if you want to enable focus you need to add some modifications for its native component (_android.widget.Button_).

XML (use the loaded event to make the button focusable)
```XML
<Button text="My Button" loaded="onButtonLoaded" tap="onButtonTap" />
```

and in the code-behind (TypeScript example)
```TypeScript
export function onButtonLoaded(args) {
    let btn = args.object as Button;
    let androidButton = btn.android;
    console.log(`loaded native Android button ${androidButton}`)
    androidButton.setFocusableInTouchMode(true);
}

export function onButtonTap(args) {
    console.log(`onButtonTap`);
    
    let btn = args.object as Button;
    let isFocused = btn.focus();

    console.log(`isFocused: ${isFocused}`);
}
```

Here is the above demonstrated in[ a Playground demo](https://play.nativescript.org/?template=play-tsc&id=bzUxyu&v=3) for Android.

**Comment by DimitrisRK** [comment]
@NickIliev Alright, but what about case 2? Scroll position would reset to last focused item if for example I tap a button at the bottom to submit my form. This causes UX issues in general, and also affects most of 'RadDataForm' plugin fields too. I think there should be a solution for this at least.
