### ISSUE TITLE
iOS. Keyboard overlaps bottom texfield once layout changes

### ISSUE THREAD

**Issue by RustamAkimov** [NativeScript/NativeScript#8536]
### Environment
 - CLI: 6.5
 - iOS Runtime: 12 & 13

### Describe the bug
In iOS, If `Textfield/Textview ` is placed at the bottom of the page when keyboard is invoked by tapping to this control, `Textfield` correctly goes above keyboard with layout shrinked as expected. 
However, any change in layout makes layout go to initial size which makes `Textfield` overlapped by keyboard

![keyboard issue](https://user-images.githubusercontent.com/1545864/79390676-c565d180-7f35-11ea-9699-e7e13e221331.gif)

### Sample project
`TextField `placed under `ListView`.
`ListView `  **populated every second by new item** which replicates the problem 

https://play.nativescript.org/?template=play-ng&id=D6i0Mw&v=2

### Additional Info
Could not solve this problem with trying  multiple layouts to bind textview to the bottom (GridLayout, FlexboxLayout, AbsoluteLayout)

**Comment by NickIliev** [comment]
@RustamAkimov  while testing on iPhone 11 with iOS 13.3 I am not able to reproduce the issue. Can you please let me know if the issue is appearing on specific simulators or on a specific iPhone model (and what is the exact version of iOS)?

**Comment by RustamAkimov** [comment]
@NickIliev 

I was able to replicate a problem on Simulator iPhone 11 (13.4.1) and real iPhone 11 (13.3.1)
For simulator, please **uncheck** IO->Keyboard->Connect Hardware Keyboard. With checked problem is not replicated

![iphone11](https://user-images.githubusercontent.com/1545864/79455343-55496100-7fb2-11ea-8027-eb1ec95c6bba.gif)

**Comment by RustamAkimov** [comment]
@NickIliev 
Similar issue was recorded previously #2907 
A workaround from that issue was used to fix my problem
