### ISSUE TITLE
issue in multiselect dropdown in nativescript for ios only

### ISSUE THREAD

**Issue by khirender** [NativeScript/NativeScript#8542]
well i have used a plugins for multiselect dropdown. it`s working fine for android but giving issue in iOS. i have used three dropdown of same type
exception says

Error: An instance 0x17386200 of class AAMultiSelectViewController was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x16d39cb0> (
<NSKeyValueObservance 0x16d5f150: Observer: 0x17386200, Key path: self.dataArray, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x16d8a5f0>
<NSKeyValueObservance 0x16dcea20: Observer: 0x16d5f150, Key path: dataArray, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x16dd8630>
)

i have such requirement to implement three multiselect dropdown. when i select one dropdown and again i open the dropdown it got crashed suddenly.

bellow i am attaching trace of sidekick :
  
one thing : it`s working fine on android

CONSOLE LOG file: node_modules\@angular\core\fesm5\core.js:25638:0: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
Faulting in NSHTTPCookieStorage singleton
Faulting in CFHTTPCookieStorage singleton
Creating default cookie storage with default identifier
TIC TCP Conn Start [1:0x16eb6600]
TIC TCP Conn Event [1:0x16eb6600]: 1 Err(0)
TIC TCP Conn Connected [1:0x16eb6600]: Err(0)
TIC Enabling TLS [1:0x16eb6600]
TIC TLS Event [1:0x16eb6600]: 2, Pending(0)
TIC TLS Event [1:0x16eb6600]: 11, Pending(0)
TIC TLS Event [1:0x16eb6600]: 12, Pending(0)
TIC TLS Event [1:0x16eb6600]: 14, Pending(0)
TIC TLS Trust Result [1:0x16eb6600]: 0
TIC TLS Event [1:0x16eb6600]: 20, Pending(0)
TIC TCP Conn Event [1:0x16eb6600]: 8 Err(0)
TIC TLS Handshake Complete [1:0x16eb6600]
TIC TCP Conn Start [2:0x16dcb1e0]
TIC TCP Conn Event [2:0x16dcb1e0]: 1 Err(0)
TIC TCP Conn Connected [2:0x16dcb1e0]: Err(0)
TIC TCP Conn Start [3:0x16ed63a0]
TIC TCP Conn Start [4:0x16ed7ae0]
TIC TCP Conn Start [5:0x16ed8dd0]
TIC TCP Conn Event [4:0x16ed7ae0]: 1 Err(0)
TIC TCP Conn Connected [4:0x16ed7ae0]: Err(0)
TIC TCP Conn Event [3:0x16ed63a0]: 1 Err(0)
TIC TCP Conn Connected [3:0x16ed63a0]: Err(0)
TIC TCP Conn Event [5:0x16ed8dd0]: 1 Err(0)
TIC TCP Conn Connected [5:0x16ed8dd0]: Err(0)
CONSOLE LOG file: node_modules\tns-core-modules\utils\utils.ios.js:49:0: utils.ios.getter() is deprecated; use the respective native property instead
CONSOLE LOG file: node_modules\tns-core-modules\utils\utils.ios.js:49:0: utils.ios.getter() is deprecated; use the respective native property instead
NativeScript debugger has opened inspector socket on port 18183 for org.nativescript.LIRMA.
CONSOLE LOG file: node_modules\tns-core-modules\inspector_modules.ios.js:1:0: Loading inspector modules...
CONSOLE LOG file: node_modules\tns-core-modules\inspector_modules.ios.js:6:0: Finished loading inspector modules.
NativeScript debugger attached.
TIC TCP Conn Cancel [1:0x16eb6600]
TIC TCP Conn Cancel [2:0x16dcb1e0]
TIC TCP Conn Cancel [4:0x16ed7ae0]
TIC TCP Conn Cancel [3:0x16ed63a0]
TIC TCP Conn Cancel [5:0x16ed8dd0]
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x7b719b NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x7f59d5 -[TNSRuntime executeModule:referredBy:]
3   0xace0d
4   0x1baaa4eb <redacted>
JavaScript stack trace:
UIApplicationMain(file: node_modules\tns-core-modules\application\application.ios.js:295:0)
at _start(file: node_modules\tns-core-modules\application\application.ios.js:295:0)
at run(file: node_modules\tns-core-modules\application\application.ios.js:323:0)
at bootstrapNativeScriptApp(file: node_modules\nativescript-angular\platform-common.js:210:0)
at bootstrapApp(file: node_modules\nativescript-angular\platform-common.js:111:0)
at bootstrapModule(file: node_modules\nativescript-angular\platform-common.js:91:0)
at ./main.ts(file:///app/bundle.js:837:116)
at __webpack_require__(file: src\webpack\bootstrap:74:0)
at checkDeferredModules(file: src\webpack\bootstrap:43:0)
at webpackJsonpCallback(file: src\webpack\bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at promiseReactionJob([native code])
JavaScript error:
file: node_modules\tns-core-modules\application\application.ios.js:295:0: JS ERROR Error: An instance 0x17386200 of class AAMultiSelectViewController was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x16d39cb0> (
<NSKeyValueObservance 0x16d5f150: Observer: 0x17386200, Key path: self.dataArray, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x16d8a5f0>
<NSKeyValueObservance 0x16dcea20: Observer: 0x16d5f150, Key path: dataArray, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x16dd8630>
)
CONSOLE WARN Fatal JavaScript exception - application has been terminated.
CONSOLE WARN Active debugger session detected. Blocking app to keep the session alive.

**Comment by NickIliev** [comment]
@khirender this looks like an issue related to the specific plugin you are using - please contact the plugin author and/or post an issue in the plugin's repository.
