### ISSUE TITLE
Tab label is not changing its color when swipe isdisabled

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [NativeScript/NativeScript#8543]
When swiping to another tab label is highlighted. When swipe is disabled label is NOT highlighted

https://play.nativescript.org/?template=play-ng&id=WxSW9I

this is very annoying issue because i cannot use tabs with RadViewList swipe actions :(
Can you fix it or provide workaround. I have tried to add selectedIndexChange event and assign it to property but this does not help either.

**Comment by vytautas-pranskunas-** [comment]
Why this need more info?
I have created playground and if you try to click on tab you would see that bottom blue line swithces but label stays grey not blue.

**Comment by liuy97** [comment]
I also have this bug in Android, not in iOS.
