### ISSUE TITLE
Tab Navigation Template has Navigation Issues

### ISSUE THREAD

**Issue by Banksy93** [NativeScript/NativeScript#8549]
Apologies if this has already been raised, I had a look for this issue but couldn't see it.

**Environment**
Using NS 6.5 and testing on Samsung Galaxy S8.

Fairly new to NS so I opted to use a template for a mobile app to help get to grips with it. 

This template to be specific: https://github.com/NativeScript/nativescript-app-templates/tree/master/packages/template-tab-navigation-vue

**Description of bug**
I haven't done any code changes to the above template, I just created a new project using it and spun it up.

I notice that when you're on the Home page and tap an item from the list, it is supposed to take you to that item's page.

However tapping an item does nothing until you hit the Search tab button when it will then load the Search tab before immediately loading the Item Component you initially wanted to see.  Also tapping the back button in the action bar or back button on the device, you're then taken back to the search tab.

**Comment by jp-sauve** [comment]
Yes, I just ran into this bug today, same circumstances. Default vue with tabs project, running on the playground on Sony Xperia XA2, not that I think it's a phone issue. Looking at the [docs](https://nativescript-vue.org/en/docs/routing/manual-routing/), the templates used for switching to another page are vue configuration objects, not components in SFC form.

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
