### ISSUE TITLE
Tabs highlight/selected color not applied when using gestures

### ISSUE THREAD

**Issue by cdmistman** [NativeScript/NativeScript#8551]
**Environment**
 - CLI: 6.5.0
 - Cross-platform modules: 6.5.1
 - Android Runtime: 6.5.0
 - iOS Runtime: N/A (not using right now)
 - Plugin(s): `nativescript-angular` ("^8.21.0"), `@angular/core` ("^8.2.14")

**Describe the bug**
When using custom highlight colors for `TabStrip`, the specified color is only used for tapping to select the tab. When using the swipe gesture to navigate between tabs, the default blue color is used for the tab strip item highlight color.

**To Reproduce**
1. Have a `Tabs` component with at least 2 tabs
2. Assign a CSS class to the `TabStrip`
3. In the CSS class, assign the `unselected-item-color`, `highlight-color`, and `selected-item-color` values to easy-to-differentiate colors
4. In the app, try switching between the tabs, both by tapping on the tab to navigate to, as well as swiping.

**Expected behavior**
There should be no coloring difference between tapping and selecting tabs for navigation

**Sample project**
[Playground](https://play.nativescript.org/?template=play-ng&id=mpAVJ6)

**Additional context**
So far, every `@nativescript/core` version I've tried is affected by this bug, including `6.6.0-next-2020-04-20-155205-01`
I also haven't been able to test on iOS, so I can only confirm this bug affects Android

**Comment by NickIliev** [comment]
@cdmistman you have a syntax error in the CSS -  the JavaScript property is `unSelectedItemColor` which means that it translates to the following CSS property`un-selected-item-color` (note the first dash)


[Here is the modified demo](https://play.nativescript.org/?template=play-ng&id=mpAVJ6&v=3) (I've used some more "lively" colors) that demonstrates that everything is working as expected with taps and with gestures. I've tested on Android 10 and on iOS 13 and both are working as expected - do let me know if you have an issue with a specific API level.

**Comment by cdmistman** [comment]
Interesting... I believe your code actually raises a different issue.

When tapping between the 2 tabs, the colors change appropriate (tapping on "TAB TWO" turns tab 2's highlight color to blue and tab 1's to red, etc). However, when swiping, the colors are switched: swiping to tab 2 from tab 1 results in tab 2's highlight color being red and tab 1's being blue. Note that everything else seems to be working as expected - the blue underline bar switches to tab 2 and I see "tab two content". Switching back to tab 1 results in the same thing: tab 1 is highlighted red, and tab 2 is highlighted blue.

I'm testing on my Pixel 4 running Android 10

**Comment by cdmistman** [comment]
If you can verify this bug then I can file a new bug report, otherwise I can try to collect more info

**Comment by felixkrautschuk** [comment]
@cdmistman what you describe in your last comment sounds similar to the issue I posted in https://github.com/NativeScript/NativeScript/issues/8552

**Comment by houssam98** [comment]
Why is it closed? It's clearly not working for me, and not working in the demo provided above.

The swipe gestures apply the opposite color...

https://play.nativescript.org/?template=play-ng&id=mpAVJ6&v=3

Swipe right and the second tab strip color is red instead of blue.

**Comment by cdmistman** [comment]
@houssam98 it's redundant to #8552 so this issue hasn't been reopened

**Comment by giulianimartini** [comment]
Hey,

same here.

Is there a workaround for this?

Thanks.
