### ISSUE TITLE
iOS Tabs component issue when changing selectedIndex by tapping the desired Tab + TabContent is RadListView

### ISSUE THREAD

**Issue by felixkrautschuk** [NativeScript/NativeScript#8553]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.5.0
 - Cross-platform modules: 6.51
 - Android Runtime: 6.5.0
 - iOS Runtime: 6.5.0
 - Plugin(s): nativescript-ui-listview 8.1.2 (also tested 7.1.0)

**Describe the bug**
When changing the Tab selectedIndex bei tapping on the desired Tab within the TabStrip, the component is not always snapping to the right content (sometimes only 95% of the desired tab-content visible).
![ios_tabs_issue_selectedindex](https://user-images.githubusercontent.com/6443021/82458214-b3d49400-9ab6-11ea-9ba8-aa0eb8a3c645.gif)

In this case, you have to swipe the content a little bit and tap again, then it works.
The following GIF shows our real app, where you can see this effect easier than in the sample app.
![ios_tabs_snapping_fanfiktion](https://user-images.githubusercontent.com/6443021/80241722-62c2b300-8664-11ea-92c6-7b0ceb5ab28e.gif)

Note: it is only reproducable to us, when using RadlistViews within the Tabs content. We can not reproduce it ourselves when using ListVews instead (but we need RadListView in our real app).
![ios_tabs_correct_listview](https://user-images.githubusercontent.com/6443021/80241750-7110cf00-8664-11ea-9ec3-d9c894a29843.gif)

When swiping through the Tabs (without tapping the TabStripItem), everything seems to work as expected on iOS (even if the Tabs contain RadListViews).

**To Reproduce**
1.) Open the sample app
2.) navigate to the RadListView page 
3.) Tap on a TabStripItem -> the content is changing correctly
4.) Tap on another TabStripItem -> nothing happens

**Expected behavior**
Tabs component should behave correctly when tapping the TabStripItems.

**Sample project**
[ns-tabs-issues.zip](https://github.com/NativeScript/NativeScript/files/4657451/ns-tabs-issues.zip)

**Comment by AnthonyLenglet** [comment]
We had this issue for a long time, after trying random things we eventually found something that fixes it

```
<Tabs
  [iosOverflowSafeArea]="true"
  [iosOverflowSafeAreaEnabled]="false"
>
```
We have no idea why, but setting those 2 settings fixed the issue for us, really confusing

**Comment by felixkrautschuk** [comment]
@AnthonyLenglet thanks for your suggestion, but unfortunately it does not change anything on our side.

Did you also use RadListViews as your TabContents ?

**Comment by AnthonyLenglet** [comment]
> Did you also use RadListViews as your TabContents ?

We used router outlets inside stacklayouts on our end !

**Comment by felixkrautschuk** [comment]
@NickIliev I just noticed that this issue does not occur when setting **tabsPosition="bottom"** to the Tabs component. Maybe that helps in any way to find out what is causing this issue.

![ios_tabs_correct_bottom](https://user-images.githubusercontent.com/6443021/82459673-81c43180-9ab8-11ea-95c8-77f28f7db328.gif)

**Comment by houssam98** [comment]
![2020-06-02 12 35 20](https://user-images.githubusercontent.com/22226728/83510644-a2838280-a4cd-11ea-9e9e-ede080176083.gif)

Having same issue, using RadListView and Tabs. 

Were you able to find a solution other than putting it in the bottom? @felixkrautschuk

**Comment by felixkrautschuk** [comment]
@houssam98 no, unfortunately I have no idea what to do. Even when putting the TabStrip to the bottom, there are still other side effects... it is just frustrating.

**Comment by houssam98** [comment]
> @houssam98 no, unfortunately I have no idea what to do. Even when putting the TabStrip to the bottom, there are still other side effects... it is just frustrating.

I actually did some adjustments and used ListView instead. It works perfectly. RadListView caused so many side effects while switching.

**Comment by felixkrautschuk** [comment]
Yes I also noticed that, but unfortunately we need RadListViews in many cases (scrolling header and footer, item selection, etc)

**Comment by felixkrautschuk** [comment]
I just noticed that this issue can be fixed by disabling animations in the following lines of the ios tabs component:
- https://github.com/NativeScript/NativeScript/blob/master/nativescript-core/ui/tabs/tabs.ios.ts#L1105
- https://github.com/NativeScript/NativeScript/blob/master/nativescript-core/ui/tabs/tabs.ios.ts#L1109
and
- https://github.com/NativeScript/NativeScript/blob/master/nativescript-core/ui/tabs/tabs.ios.ts#L1118

When setting the animated flag for those method calls to "false", the issue does not appear on my side in both cases, when the tabsPosition is set to top and when it is set to bottom.

In addition, we notice an annoying crash when tapping the Tabs and swiping through the Tabs randomly. The error message was:

>  NativeScript encountered a fatal error: Error: Invalid parameter not satisfying: [views count] == 3

I made a little research and came to this comment on StackOverflow:
[https://stackoverflow.com/a/48955006](https://stackoverflow.com/a/48955006)

This made me trying to disable the animations temporary in the tns-core-modules and it works.

Maybe we can introduce another property `isIOSAnimationEnabled`? It seems to be the only way making the Tabs component and the RadListView working together on iOS...

**Comment by HugeJackChen** [comment]
> I just noticed that this issue can be fixed by disabling animations in the following lines of the ios tabs component:


Thank you very much , it works for me ,solves tabs problem that has troubled me for a long time...

It not only solves RadListView on Tabs crash problem , and aslo solves  Loading dynamic UI object with  code behind on Tabs.

**Comment by scottypipz** [comment]
is this working? there is no docs regarding iOSAnimationEnabled

**Comment by scottypipz** [comment]
Man, you should have included it in the nativescript docs. I was having this problem for 3 days lol
