### ISSUE TITLE
Totorial how to run emulator and device side by side

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [NativeScript/NativeScript#8554]
I am working on angular NS app. I want to test 2 users behaviour by launching independent app on emulator and independent one on device. Currently i cannot find way (except duplicating project phisically) how to do this.
I was trying to launch app on emulator and then via sidekick launch on device. It launches but device gets emualtors build and emulator stops syncing.

So is there a way how to do this?

**Comment by NickIliev** [comment]
The CLI `run` command supports multiple devices to run simultaneously the same app (and the app can be live synced on all of them) - I was able to run an app on 4 different Android devices + 2 iOS simulators. All you need is to have the CLI installed and configured properly (for local builds), then to start/attach the devices and finally to execute the following command:

```
tns run android
```

And you are good to go.
