### ISSUE TITLE
How to add a ios view into layout

### ISSUE THREAD

**Issue by kobehjk** [NativeScript/NativeScript#8555]
**<StackLayout #calendarview  class="calendar" dock="top" id="aaa"></StackLayout>**
**i creat a ios native custom view which is inherited from UIView，How can i put the custom view into thelayout**

**Comment by NickIliev** [comment]
@kobehjk if you are using NativeScript Core you could use a `Placeholder` element to create a custom view (based on a native view).

The same is not applicable to Angular based apps. The best approach there is to create your custom NativeScript layout (preferably through a plugin - see [here](https://docs.nativescript.org/angular/plugins/ui-plugin-custom#platform-specific-code) and [here ](https://docs.nativescript.org/angular/plugins/angular-third-party)and basically the whole section) which implements the native one.
