### ISSUE TITLE
Android 6 support

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#856]
We have Android 6 support in the runtimes, but we should check if there is new functionality to be supported in the JS abstractions.

**Comment by dtopuzov** [comment]
List of known issues:
https://github.com/NativeScript/NativeScript/issues/990

**Comment by vchimev** [comment]
https://gist.github.com/vchimev/bb7f652177a95a0e0d35

**Comment by vchimev** [comment]
Fixed by https://github.com/NativeScript/NativeScript/pull/1073.
