### ISSUE TITLE
Can't load local file in WebView

### ISSUE THREAD

**Issue by laurnicolae** [NativeScript/NativeScript#8568]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.4.1
 - Cross-platform modules: 6.4.2
 - Android Runtime: 6.4.1
 - iOS Runtime:6.4.0
 - Plugin(s):

**Describe the bug**
I am trying to include a html file in a local folder into a webview but it doesn't work. I found a solution online but it doesn't work either.

My code is below:
`import Vue from "nativescript-vue";
import * as fs from "tns-core-modules/file-system";

new Vue({

    template: `
        <WebView :src="source" />`,

    components: {
    },
    data() {
      return {
        source: encodeURI(`${fs.knownFolders.currentApp().path}/html/index.html`)
      }
    },
    mounted() {
    	this.source = encodeURI(`${fs.knownFolders.currentApp().path}/html/index.html`)
    }
}).$start();`

I also tried to include it like in the official example: <WebView src="~/html" /> or <WebView src="~/html/index.html" /> 
with no luck.
Any idea how I can include the local HTML file in the webview?

I am trying on iOS on an emulator.

**Comment by NickIliev** [comment]
@laurnicolae your local file should be added in the `webpack.config.js` in the `CopyWebpackPlugin` section (as done [here](https://github.com/NativeScript/nativescript-sdk-examples-js/blob/master/webpack.config.js#L258))

**Comment by laurnicolae** [comment]
> @laurnicolae your local file should be added in the `webpack.config.js` in the `CopyWebpackPlugin` section (as done [here](https://github.com/NativeScript/nativescript-sdk-examples-js/blob/master/webpack.config.js#L258))

Thank you for your answer.  It works perfectly!

I have another problem, in the webview I load a vuejs app which does some http requests using axios. The requests are not working, I don't see any error and I don't see any request in the devtools inspector. Any idea why?
