### ISSUE TITLE
Creating NS-Vue project using nativescript-vue/vue-cli-template adds imports  from vue instead of nativescript-vue

### ISSUE THREAD

**Issue by Dobermensch** [NativeScript/NativeScript#8570]
I used this command to create my project: `vue init nativescript-vue/vue-cli-template <project-name>` by following the steps here: https://nativescript-vue.org/en/docs/getting-started/quick-start/ and I opted in for TS support and VueX.

Now I noticed that in the store.ts file that is created, the import on the first line is `import Vue from "vue"`. Here is the file store.ts:
```
import Vue from 'vue';
import Vuex from 'vuex';

Vue.use(Vuex);

export default new Vuex.Store({
  state: {

  },
  mutations: {

  },
  actions: {

  }
});
```

Yet when I visited NS playground, their examples import Vue from nativescript-vue for their VueX store file. I believe this led me to face the following issue https://stackoverflow.com/questions/61710809/nativescript-vue-cannot-read-property-getters-of-undefined/ because when I changed the import to nativescript-vue in store.ts, the issue was resolved.

Anyways this I'm creating this issue for others who may happen to search for the same problem.

**Comment by kabaluyot** [comment]
yep. To leverage vue in a nativescript project, you must use the `nativescript-vue` package instead of `vue`

**Comment by rigor789** [comment]
In the cli-template this shouldn't be a problem, there is an alias defined in the webpack config that points vue to nativescript-vue.
