### ISSUE TITLE
TypeError: Network request failed

### ISSUE THREAD

**Issue by alexisconsuegra** [NativeScript/NativeScript#8572]
**Environment**
Version: 1.19.2-v.2019.11.18.2 (latest)
NativeScript CLI version: 6.5.0
CLI extension nativescript-cloud version: 1.19.3
CLI extension nativescript-starter-kits version: 0.3.5
 - Android Runtime: 6.5.0
 - iOS Runtime: 6.5.0
- tns-core-modules: 6.5.1

**Describe the bug**
Any and all fetch now produce TypeError: Network request failed.
It just started happening 2-4 days ago. I have the app already published for both iOS and Android. Both working fine and suddenly it stopped working.
Does anyone has a hint of what has changed in the last few days?

Thanks a lot.

**Comment by NickIliev** [comment]
@alexisconsuegra the last change in the `fetch` module [was introduced about four months ago](https://github.com/NativeScript/NativeScript/tree/master/nativescript-core/fetch). Also, if your app is published, no changes in an NPM library will make any difference up until you rebuild and release a new version of your app (with the latest version of the NPM library, which in that case is `@nativescript/core`).

That said, it is most likely related to a real network issue you might want to check the visibility of the endpoint from different mobile networks and CDNs (e.g., is your host still reachable from where your users are located? Are there any connection limitations, are there any latency requirements... etc.)
