### ISSUE TITLE
Unitless line-height values interpreted wrong

### ISSUE THREAD

**Issue by RedHatter** [NativeScript/NativeScript#8576]
Unitless values for the line-height property are currently interpreted as dp. They should be a scaling factor based on the font size. For example `line-height: 2;` is currently interpreted as `2dp` but is should actually be `font-size * 2`.

**Comment by NickIliev** [comment]
@RedHatter the unitless values are actually DIPs (device-independent pixels) where the scale is based on the scale of the used device. If the device screen density is 1 then no scaling will be applied which should be expected. Same goes for a font that is set with unitless values (e.g.: `font-size: 14` is using DIP while `font-size:14px` will always use the hardware pixels without taking the screen density into account)

**Comment by RedHatter** [comment]
@NickIliev I understand that. As I said in my post `line-height: 2;` is currently interpreted as `2dp`. But this is not correct. For line height a unitless value should define the size based on *font size* not device scale. See https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#Values under unitless.

**Comment by NickIliev** [comment]
@RedHatter I don't think, in this case, we could compare Web to Mobile.. there is no concept of screen density in Web so there is no need to scale any unit based on that factor. In mobile on the other hand, if you want to create a responsive UI on devices with different screen density you should rely on DIP units. 

In NativeScript all unitless values are DIPs (including the ones set for  **font-size** and **line-height**) and in the context of deploying on multiple differently scaled devices, I think this is the only right approach.
