### ISSUE TITLE
getActiveNetworkInfo() and NetworkInfo were deprecated in API level 29

### ISSUE THREAD

**Issue by edurenye** [NativeScript/NativeScript#8580]
**Describe the bug**
`connectivityManager.getActiveNetworkInfo()` (https://developer.android.com/reference/android/net/ConnectivityManager#getActiveNetworkInfo()) and `NetworkInfo` (https://developer.android.com/reference/android/net/NetworkInfo) were deprecated in API level 29, and we use it in: https://github.com/NativeScript/NativeScript/blob/master/nativescript-core/connectivity/connectivity.android.ts

**Expected behavior**
I'm not sure how to get the network type but to get the SSID we should use https://developer.android.com/reference/android/net/wifi/WifiManager `wifiManager.getConnectionInfo().getSSID()`

**Comment by NickIliev** [comment]
@edurenye confirming this one as a bug that prevents proper detecting of active connections on newer Android API levels.

With the current implementation, devices with newer API levels won't detect that there is active internet connection when the connection type is WIFI.

For example:
- Turn WIFI on the device,
- Turn of Mobile Data

as a result:
`getConnectionType` and `startMonitoring` will both return **connectionType = 0** (no Internet connection) while it should be of type 1 (WIFI connection active).

**Comment by jarmani** [comment]
@triniwiz @NathanWalker I think the issue can be closed
