### ISSUE TITLE
Allow borders to be applied on a per-side basis in CSS

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/NativeScript#859]
I'm finding that I frequently need to put a border on one side of a UI component, but NativeScript currently does not support this. I'm requesting that the following CSS properties be added:

* `border-top-width`
* `border-top-color`
* `border-right-width`
* `border-right-color`
* `border-bottom-width`
* `border-bottom-color`
* `border-left-width`
* `border-left-color`

To be consistent with CSS, I would also like the `border-width` and `border-color` shorthands to work like they do in CSS.

![screen shot 2015-09-30 at 8 17 47 am](https://cloud.githubusercontent.com/assets/544280/10192639/c4dd109a-674b-11e5-9fd8-65cae2b3b72f.png)

> Update: You can vote for this feature at https://nativescript.ideas.aha.io/ideas/NS-I-110.

Thanks.

**Comment by lscown** [comment]
Yes please :+1:

**Comment by PeterStaev** [comment]
:+1:

**Comment by tsvetan-ganev** [comment]
:+1:

**Comment by kishmiryan-karlen** [comment]
:+1:

**Comment by kishmiryan-karlen** [comment]
@tjvantoll do you have any workaround now?

**Comment by kvelikov** [comment]
:+1:

**Comment by rclai** [comment]
So how do we set a border to a specific side right now?

**Comment by tjvantoll** [comment]
What I’ve been doing is something like `<stack-layout style="height: 2; border-color: red; border-width: 2;"></stack-layout>`, which is definitely hacky, but it works until per-side borders are truly supported.

**Comment by rclai** [comment]
Oh haha okay, thanks.

**Comment by tenorok** [comment]
:+1:

**Comment by stevetayloruk** [comment]
+1

**Comment by sitefinitysteve** [comment]
+1

**Comment by karlix** [comment]
+1

**Comment by firescript** [comment]
+1

**Comment by RusEu** [comment]
So how do we set a border to a specific side right now? Like the TabView does for the border-bottom?

**Comment by tiagordc** [comment]
+1

**Comment by mayke5421** [comment]
+1

**Comment by vbresults** [comment]
+5

**Comment by vbresults** [comment]
+5

@tjvantoll The hack only works well visually on certain devices -- depending on the device's width.  For example, a grid layout with *,1,*,1,* will sometimes not display those 1-height borders.

So we'd also need the option to make the borders inset.

**Comment by lelong37** [comment]
+1

**Comment by dragGH102** [comment]
+1

**Comment by nripendra** [comment]
+1

**Comment by Premitium** [comment]
+1

**Comment by gadonski** [comment]
+1

**Comment by treio** [comment]
+1

**Comment by sitefinitysteve** [comment]
Common, lets tag this with "high" we all need it, height:1 StackLayout is suuuuper bloaty and hacky

**Comment by PanayotCankov** [comment]
:+1:

**Comment by erkanarslan** [comment]
+1

**Comment by paveldk** [comment]
+1

**Comment by runningBuffalo** [comment]
+1

**Comment by vdende** [comment]
+1

**Comment by mariocosme** [comment]
+1

**Comment by k3yb0ardn1nja** [comment]
+1

**Comment by TheOriginalJosh** [comment]
+1

**Comment by yezarela** [comment]
+1

**Comment by Daxito** [comment]
+1

**Comment by leocaseiro** [comment]
+1

**Comment by leocaseiro** [comment]
Guys, vote here, please: https://nativescript.ideas.aha.io/ideas/NS-I-110

**Comment by dragGH102** [comment]
great idea @Leo.
done!

**Comment by tjvantoll** [comment]
> @leocaseiro: @tjvantoll would you mind add this link to your description?

Done!

And just an fyi to everyone watching here, per-side borders are pretty easy to do on Android, but a complete pain on iOS—which is why this hasn’t been implemented in the modules yet. Getting per-side borders right on iOS is a big engineering challenge, and it’s not as simple as adding a few properties into a list. (Side note: I [took a stab at implementing border-bottom on an iOS `UITextField` and failed horribly](http://stackoverflow.com/questions/35949934/nativescript-textfield-with-only-a-bottom-border-on-ios) myself.) That being said, we realize there’s a lot of demand here so we do want to tackle this. If you want to see this implemented [add your vote](https://nativescript.ideas.aha.io/ideas/NS-I-110) to help us prioritize.

**Comment by luigi7up** [comment]
+1

**Comment by kenhowardpdx** [comment]
👍

**Comment by jmak** [comment]
👍

**Comment by kwong93** [comment]
+1

**Comment by valentinstoychev** [comment]
probably a dependency to #1763

**Comment by PanayotCankov** [comment]
Will it require :first-child and :last-child pseudo class selectors after it?

**Comment by jorendemaeyer1996** [comment]
+1

**Comment by carakan** [comment]
+1

**Comment by PanayotCankov** [comment]
@tjvantoll iOS has sufficient APIs to draw it.

**Comment by philpalmieri** [comment]
FWIW, I just use a background image for what i've needed so far ( a single line underneath an element)

**Comment by ahmedelgendy** [comment]
+1

**Comment by mragwa** [comment]
+1

**Comment by hamorphis** [comment]
https://github.com/NativeScript/NativeScript/pull/2743 adds basic support for non-uniform borders.

Current limitations are:

 - Different border radii on the four corners are not yet supported
 - Border radius is supported only when the border width and color is uniform on all four sides.
 - Images on iOS will still render behind the border as they always have, until a fix is provided.

**Comment by hamorphis** [comment]
![screenshot_20160917-161341](https://cloud.githubusercontent.com/assets/1201857/18608443/0090a388-7cf2-11e6-8b57-88062e34b767.png)
![simulator screen shot sep 17 2016 4 14 45 pm](https://cloud.githubusercontent.com/assets/1201857/18608444/020e0570-7cf2-11e6-8203-d01f090d8a77.png)

**Comment by sitefinitysteve** [comment]
... So happy right now

**Comment by hamorphis** [comment]
@sitefinitysteve :)

**Comment by TheOriginalJosh** [comment]
Awesome!!!

**Comment by hamorphis** [comment]
Outstanding issues:
[ ] Support border radius when border width or color are non-uniform [Complex]
[ ] Borders currently hide the content of some iOS components such as Image, ListView and ScrollView. Quick workaround is to place the component inside a Layout and set the borders on the Layout instead.
[ ] Android ScrollView does not show any borders at all.

**Comment by hamorphis** [comment]
[ ] Support uniform and non-uniform border radii on non-uniform border colors and/or widths.
[ ] Some iOS components such as Image, ScrollView and ListView will render behind the borders. Quick workaround is to place the component inside one of our Layouts and set the borders on the Layout instead.
[ ] Android ScrollView draws no borders at all.
