### ISSUE TITLE
Getting error installing and uninstalling 6.5.1

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/NativeScript#8602]
Was getting an error installing 6.5.1.

So I decided to uninstall it.

`sudo npm uninstall -g nativescript`
Getting error

```
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> nativescript@6.5.1 preuninstall /usr/local/lib/node_modules/nativescript
> node preuninstall.js

EACCES: permission denied, open '/Users/mini/.local/share/.nativescript-cli/a05e966313d1a8e32b13c35910ae824e'
Error while reporting exception: Error: EACCES: permission denied, open '/Users/mini/.local/share/.nativescript-cli/a05e966313d1a8e32b13c35910ae824e'

```

I was also getting permissions problems during the install.

**Comment by rigor789** [comment]
You shouldn't need to run `npm install` with `sudo` - that will completely mess up file permissions, as files created by a sudo user won't be readable by your user.

Double check you have installed node/npm correctly.
