### ISSUE TITLE
iOS Tabs safe area not used of TabStrip position is "bottom"

### ISSUE THREAD

**Issue by felixkrautschuk** [NativeScript/NativeScript#8603]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.5.1
 - Cross-platform modules: 6.5.2
 - Android Runtime: -
 - iOS Runtime: 6.5.0
 - Plugin(s): -

**Describe the bug**
When using the old TabView, the safe area on ios devices was filled correctly like this:
<img width="427" alt="Bildschirmfoto 2020-05-29 um 12 13 39" src="https://user-images.githubusercontent.com/6443021/83249465-e7927680-a1a6-11ea-8d4c-b955e1777fbf.png">

But when using the Tabs component with TabStrip position="bottom", the TabStrip looks like this:
<img width="427" alt="Bildschirmfoto 2020-05-29 um 12 15 54" src="https://user-images.githubusercontent.com/6443021/83249564-0db81680-a1a7-11ea-9b2a-d8086f515484.png">

This os our CSS:
```
Tabs {
    tabs-position: bottom;
}

TabStrip {
    background-color: lightblue;
    selected-item-color: darkblue;
    un-selected-item-color: #3c3c3c;
    highlight-color: orange;
}

TabContentItem {
    background-color: aliceblue;
}
```

If the TabStrip position is set to "top", the TabContentItem will will the safe area as expected. But when setting the position to "bottom", the TabStrip does not fill the safe area (like the old TabView does).

**To Reproduce**
-

**Expected behavior**
The TabStrip should fill the safe area at the bottom, like the TabView does.

**Sample project**
[ns-tabs-issues.zip](https://github.com/NativeScript/NativeScript/files/4701268/ns-tabs-issues.zip)

**Additional context**
Maybe BottomNavigation brings the desired behaviour at this point, but we really want to have the Tabs behaviour (swipe gesture etc) so I hope this can be fixed by the NS core team.

I tried to set iosOverflowSafeArea="true" on TabStrip and Tabs, but that did not change anything.

**Comment by Ross-Olivares** [comment]
Hi @felixkrautschuk 
Thank you for reporting this issue.
We are going to try replicate this case on our end and will confirm, we will research what is causing this issue and will provide the needed fix. For further info, you could keep track the issue.

**Comment by felixkrautschuk** [comment]
Are there any updates for this? I tried to set iosOverflowSafeArea="true" to Tabs component and to TabStrip, but it has no effect.

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
