### ISSUE TITLE
Nativescript BottomNavigation full screen issue on specific page

### ISSUE THREAD

**Issue by simple-access** [NativeScript/NativeScript#8604]
Able to hide both Bottom navigation Tabs  ios and android. Expected functionality such way that we can hide and show bottom navigation.
Environment
{
"nativescript": {
"id": "org.nativescript.mytest",
"tns-android": {
"version": "6.5.0"
},
"tns-ios": {
"version": "6.5.0"
}
},
"description": "NativeScript Application",
"license": "SEE LICENSE IN ",
"repository": "",
"scripts": {
"lint": "tslint "src/**/*.ts""
},
"dependencies": {
"@angular/animations": "~8.2.0",
"@angular/common": "~8.2.0",
"@angular/compiler": "~8.2.0",
"@angular/core": "~8.2.0",
"@angular/forms": "~8.2.0",
"@angular/platform-browser": "~8.2.0",
"@angular/platform-browser-dynamic": "~8.2.0",
"@angular/router": "~8.2.0",
"@nativescript/theme": "~2.3.3",
"nativescript-angular": "~8.21.0",
"reflect-metadata": "~0.1.12",
"rxjs": "^6.4.0",
"tns-core-modules": "~6.5.0",
"zone.js": "~0.9.1"
},
"devDependencies": {
"@angular/compiler-cli": "~8.2.0",
"@ngtools/webpack": "~8.2.0",
"codelyzer": "~4.5.0",
"nativescript-dev-webpack": "~1.5.1",
"node-sass": "^4.7.1",
"tslint": "~5.19.0",
"typescript": "~3.5.3"
},
"gitHead": "2250137db8c1e0bd0eb543e8e4563cb71480c00d",
"readme": "NativeScript Application"
}

Describe the bug
When navigated to a page unable to hide bottom navigation tab bar or show full screen page view.

To Reproduce
Create a basic native script angular tabs app by tns create

Home tab with items
2)Select an item navigates to next page.
Issue: Show Bottom navigation Tabs on item detail page (Unable to hide)
Expected behavior
Able to hide both Bottom navigation Tabs ios and android. Expected functionality such way that we can hide and show bottom navigation.

Attached just source code
[src.zip](https://github.com/NativeScript/NativeScript/files/4703214/src.zip)

**Comment by Ross-Olivares** [comment]
Hi @simple-access 
Thank you for reporting this issue.
We are going to try replicate this case on our end and will confirm. We will research what is causing this issue and will provide the needed fix. For further info, you could keep track the issue.

**Comment by jakoguta** [comment]
@simple-access did you ever get a solution to this NativeScript BottomNavigation hide issue?

**Comment by jakoguta** [comment]
@Ross-Olivares did you find a fix for this issue?

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
