### ISSUE TITLE
unable to attach to debugger

### ISSUE THREAD

**Issue by tahir-jamil** [NativeScript/NativeScript#8605]
chrome-devtools://devtools/bundled/inspector.html?experiments=true&ws=localhost:40000
this is the url which i get after tns debug android but it will not attached to debugger
![Screenshot 2020-05-30 at 3 30 42 PM](https://user-images.githubusercontent.com/40952630/83326468-bfca0e00-a28d-11ea-8f31-0c93698404cd.png)
![Screenshot 2020-05-30 at 3 30 14 PM](https://user-images.githubusercontent.com/40952630/83326470-c3f62b80-a28d-11ea-8b5a-ca6956556bbc.png)
![Screenshot 2020-05-30 at 3 28 10 PM](https://user-images.githubusercontent.com/40952630/83326471-c5bfef00-a28d-11ea-8c86-649c2a4facf4.png)

**Comment by tahir-jamil** [comment]
Fixed need to use like that

**Comment by tahir-jamil** [comment]
Fixed need to use like that
**devtools://devtools/bundled/inspector.html?experiments=true&ws=localhost:40000**

**Comment by NathanaelA** [comment]
We need to fix the URL so that others don't run into this issue, Chrome in the most recent versions of the browser no longer support the "chrome-" in front of the URL.

**Comment by NathanWalker** [comment]
Correct debug url is now printed to console with `nativescript` cli **v6.7.4**
