### ISSUE TITLE
ListView loadmore items being called too many times

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#861]
g+ Post on it, not the only user seeing this

https://plus.google.com/105924849940590264025/posts/UuvX5Ysucs3

**Comment by bradmartin** [comment]
+1 - This makes this event unusable on a ListView with images on Android. Crashes everytime with 'OutOfMemory' exception.

**Comment by sitefinitysteve** [comment]
I'm also seeing it on Android :/

**Comment by x4080** [comment]
I experience it too,right now my workaround is using timeout

**Comment by bradmartin** [comment]
@x4080 - when using timeout are you setting the delay to any specific time or just wrapping the event in a timeout and does that seem to resolve the issue?

**Comment by x4080** [comment]
Just simple canceltimeout if it called again. It works as workaround

**Comment by bradmartin** [comment]
@x4080 okay yea I didn't think about cancelling it. Thanks.

**Comment by x4080** [comment]
Another good trick is using simple variable to toggle if loading is finished or not. I think the android community get the same problem. It just the way it is not really ns specific issue

**Comment by enchev** [comment]
Hey folks,

I've just checked this problem and indeed this seems to be common issue with Android ListView. We currently raise the event [here](https://github.com/NativeScript/NativeScript/blob/master/ui/list-view/list-view.android.ts#L74) and if you think that there is better time/place please let us know!

Thanks

**Comment by sitefinitysteve** [comment]
Works for me, it's an easy fix I just thought I was hacking around a bug!

**Comment by bradmartin** [comment]
Can someone help out by posting the work around code using the timeout and the variable approach. I've tried both but I'm not having any luck preventing it from calling multiple times. Below is what I have currently which DOES NOT WORK so if someone wants to expand on the correct way to do that for future users I think it would be helpful.

//// Infinite Scrolling - when list gets to bottom this is called.
exports.loadMoreUsers = function (data) {

    var timeout = setTimeout(loadMoreUsersTimeout(), 500);

    clearTimeout(timeout);
};

function loadMoreUsersTimeout() {
    pageData.set("isLoading", true);
    userList.load().then(function () {
        pageData.set("isLoading", false);
    });
};

**Comment by sitefinitysteve** [comment]
@bradmartin for me I just set isLoading to true before my http call, then in it's callback I set it back to false...

So in my loadMore event I do 
if(model.get("isLoading") === false){
  //Load more data
}
