### ISSUE TITLE
When it touched the push notifications and the application is in the background, it deletes the data from ApplicationSettings and local storage

### ISSUE THREAD

**Issue by ferleysilva** [NativeScript/NativeScript#8611]
Hello @EddyVerbruggen, I am implementing push notifications and using versions: NativeScript v6.4. * And nativescript-plugin-firebase 10.5.2 but I have a problem, when the application is in the background and a notification arrives and I touch the notification opens the application but it is deleting the user data that I have saved with ApplicationSettings and / or local storage, for this reason it sends me to the login and it does not redirect me in the desired view

I need help, thanks

**Comment by Ross-Olivares** [comment]
Hi @ferleysilva 
Thank you for reporting this issue.
This issue seems to be plugin specific that @EddyVerbruggen authored. Let us know if there is something else we can help to fix.
