### ISSUE TITLE
Angular Ivy failing to start

### ISSUE THREAD

**Issue by alexhribsek** [NativeScript/NativeScript#8615]
I tried to upgrade to Angular Ivy. Upon running, I get the following error:

    ERROR in The target entry-point "@nativescript/angular" has missing dependencies:
    - @nativescript/core/ui/layouts/layout-base

**Comment by NathanWalker** [comment]
Hi @alexhribsek You can add an `ngcc.config.js` file to root of your project to solve. This is mentioned in the [Ivy update guide here](https://github.com/NativeScript/nativescript-angular/wiki/Updating-and-developing-for-@nativescript-angular-v9-with-Ivy-or-without#problem-2)

You can use the example provided there as is 👍

**Comment by alexhribsek** [comment]
Hi @NathanWalker 👋

Thank you very much for you quick response. I have already tried this, however I got a similar issue, with the ListView dependency. Will try again tomorrow morning and get back to you with the details.

**Comment by NathanWalker** [comment]
If it’s nativescript-ui-listview try to copy and paste this entire example into your ngcc.config.js which covers that plugin:
```
module.exports = {
  "packages": {
    "@nativescript/angular": {
      entryPoints: {
        ".": {
          override: {
            main: "./index.js",
            typings: "./index.d.ts",
          },
          ignoreMissingDependencies: true,
        }
      },
      ignorableDeepImportMatchers: [
        /tns-core-modules\//,
        /@nativescript\/core\//
      ]
    },
    "nativescript-datetimepicker": {
      entryPoints: {
        ".": {
          override: {
            main: "./index.js",
            typings: "./index.d.ts",
          },
          ignoreMissingDependencies: true,
        },
        "angular": {
          override: {
            main: "./index.js",
            typings: "./index.d.ts",
          },
          ignoreMissingDependencies: true,
        }
      },
      ignorableDeepImportMatchers: [
        /tns-core-modules\//,
        /@nativescript\/core\//,
        /@nativescript\/angular\//
      ]
    },
    "nativescript-ui-sidedrawer": {
      entryPoints: {
        "angular": {
          override: {
            main: "./side-drawer-directives.js",
            typings: "./side-drawer-directives.d.ts",
          },
          ignoreMissingDependencies: true,
        }
      },
      ignorableDeepImportMatchers: [
        /tns-core-modules\//,
        /@nativescript\/core\//,
        /@nativescript\/angular\//
      ]
    },
    "nativescript-ui-listview": {
      entryPoints: {
        "angular": {
          override: {
            main: "./listview-directives.js",
            typings: "./listview-directives.d.ts",
          },
          ignoreMissingDependencies: true,
        }
      },
      ignorableDeepImportMatchers: [
        /tns-core-modules\//,
        /@nativescript\/core\//,
        /@nativescript\/angular\//
      ]
    }
  }
}
```

**Comment by alexhribsek** [comment]
I get this:

```
ERROR in Symbol ListViewComponent declared in /Users/alex/Desktop/work/private/todo/client-v8-ivy/node_modules/@nativescript/angular/directives/list-view-comp.d.ts is not exported from nativescript-angular/nativescript.module
```

**Comment by NathanWalker** [comment]
@alexhribsek possible to share your project on github? If private you can invite `NathanWalker`. I'd be happy to take a look. Most likely it could be an import in the project that may be using a deep import possible but can also be result of various other subtle things.

**Comment by alexhribsek** [comment]
I can only share the configuration. Here's my `package.json`. Let me know if any other file would help to clarify things.

```
{
    "name": "client-app",
    "version": "0.0.0",
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e",
        "android": "tns run android",
        "ios": "tns run ios",
        "mobile": "tns run",
        "preview": "tns preview",
        "ngcc": "ngcc --properties es2015 module main --first-only",
        "postinstall": "npm run ngcc"
    },
    "nativescript": {
        "id": "com.client.app",
        "tns-ios": {
            "version": "7.0.0-beta.3-v8-2020-05-05-103807-01"
        },
        "tns-android": {
            "version": "6.5.0"
        }
    },
    "dependencies": {
        "@angular/animations": "~9.1.0",
        "@angular/common": "~9.1.0",
        "@angular/compiler": "~9.1.0",
        "@angular/core": "~9.1.0",
        "@angular/forms": "~9.1.0",
        "@angular/http": "~8.0.0-beta.10",
        "@angular/platform-browser": "~9.1.0",
        "@angular/platform-browser-dynamic": "~9.1.0",
        "@angular/router": "~9.1.0",
        "@nativescript/angular": "^9.0.0",
        "@ngxs/store": "^3.6.2",
        "core-js": "^2.6.9",
        "lodash": "^4.17.15",
        "nativescript-angular": "~8.20.0",
        "nativescript-ui-listview": "^8.2.0",
        "reflect-metadata": "~0.1.12",
        "rxjs": "~6.5.5",
        "tns-core-modules": "~6.3.0",
        "tslib": "1.10.0",
        "zone.js": "^0.10.3"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "~0.803.0",
        "@angular/cli": "~8.3.0",
        "@angular/compiler-cli": "~9.1.0",
        "@nativescript/schematics": "~1.0.0",
        "@nativescript/tslint-rules": "~0.0.5",
        "@types/jasmine": "~3.3.8",
        "@types/jasminewd2": "~2.0.3",
        "@types/node": "~8.9.4",
        "codelyzer": "^5.0.0",
        "jasmine-core": "~3.4.0",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~4.1.0",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.1",
        "karma-jasmine": "~2.0.1",
        "karma-jasmine-html-reporter": "^1.4.0",
        "nativescript-dev-webpack": "~1.4.0",
        "protractor": "~5.4.0",
        "ts-node": "~7.0.0",
        "tslint": "~5.15.0",
        "typescript": "~3.8.3"
    }
}
```

**Comment by NathanWalker** [comment]
@alexhribsek thanks - that's pretty helpful actually.
```
"@nativescript/angular": "^9.0.0",
...
"nativescript-angular": "~8.20.0",
```
2 different version of {N} angular - that might be causing your issue. Remove `nativescript-angular`. You should be using only `@nativescript/angular` at this point. Then clean and rebuild and let's see what ya got.

**Comment by alexhribsek** [comment]
I get the same issue:

```
ERROR in Symbol ListViewComponent declared in node_modules/@nativescript/angular/directives/list-view-comp.d.ts is not exported from nativescript-angular/nativescript.module
```

The thing is, I'm not importing it anywhere, just using the `RadListView` component in two views.

**Comment by NathanWalker** [comment]
Do you have an import in your project like this by chance?
```
import { NativeScriptModule } from '@nativescript/angular/nativescript.module';
```
If so, remove the `nativescript.module` on the end.
Are there other deep imports into @nativescript/angular ?

The only deep import should be this in `main.ts`:
```
import { platformNativeScriptDynamic } from "@nativescript/angular/platform";
```
All others should be imported from `@nativescript/angular` only.

**Comment by alexhribsek** [comment]
Yup, this seems to do the trick. Thank you very much! 👍

There is a strange side effect of reactive forms not working on only some views (on some they do), so I think that might be a different problem.

**Comment by NathanWalker** [comment]
@alexhribsek awesome good to hear! On reactive forms, do you have a repo you could share which exhibits that issue? I'll look into it.

**Comment by alexhribsek** [comment]
Sadly I cannot share the project. I will dive into it and share my findings.

**Comment by compishe** [comment]
After update I have a error:
```
ERROR in ../node_modules/nativescript-ui-gauge/__ivy_ngcc__/angular/gauges-directives.js
Module not found: Error: Can't resolve './../' in '*****/node_modules/nativescript-ui-gauge/__ivy_ngcc__/angular'
 @ ../node_modules/nativescript-ui-gauge/__ivy_ngcc__/angular/gauges-directives.js 4:10-26
 @ ./app/shared/atoms/atoms.module.ts
 @ ./app/feed/feed.module.ts
 @ ./app/core/tabs/tabs-routing.module.ts
 @ ./app/core/tabs/tabs.module.ts
 @ ./app/app-routing.module.ts
 @ ./app/app.module.ts
 @ ./main.ts
```

in my ngcc.config.js:
```
"nativescript-ui-gauge": {
      entryPoints: {
        angular: {
          override: {
            main: "./gauges-directives.js",
            typings: "./gauges-directives.d.ts",
          },
          ignoreMissingDependencies: true,
        },
      },
      ignorableDeepImportMatchers: [
        /tns-core-modules\//,
        /@nativescript\/core\//,
        /@nativescript\/angular\//,
      ],
    },
```

What is wrong?

**Comment by funder7** [comment]
> If so, remove the `nativescript.module` on the end.
> Are there other deep imports into @NativeScript/angular ?

Thanks @NathanWalker it helped me too to fix the problem!

**Comment by sampetroda** [comment]
Hi ,
I have got similar error when **tns run andriod.....** command  but while run tns preview command , I have don't get any error.

**Comment by sampetroda** [comment]
I have got following error
ERROR in ../node_modules/nativescript-ui-sidedrawer/__ivy_ngcc__/angular/side-drawer-directives.js
Module not found: Error: Can't resolve './..' in 'E:\2020doc\rect\native\chitti-pata-app\node_modules\nativescript-ui-sidedrawer\__ivy_ngcc__\angular'
 @ ../node_modules/nativescript-ui-sidedrawer/__ivy_ngcc__/angular/side-drawer-directives.js 3:10-25 6:23-38
 @ ./app/superadminhome/superadminhome.component.ts
 @ ./app/app-routing.module.ts
 @ ./app/app.module.ts
 @ ./main.ts
Executing webpack failed with exit code 2.

**Comment by StefanAleksik** [comment]
> I have got following error
> ERROR in ../node_modules/nativescript-ui-sidedrawer/**ivy_ngcc**/angular/side-drawer-directives.js
> Module not found: Error: Can't resolve './..' in 'E:\2020doc\rect\native\aa\node_modules\nativescript-ui-sidedrawer__ivy_ngcc__\angular'
> @ ../node_modules/nativescript-ui-sidedrawer/**ivy_ngcc**/angular/side-drawer-directives.js 3:10-25 6:23-38
> @ ./app/superadminhome/superadminhome.component.ts
> @ ./app/app-routing.module.ts
> @ ./app/app.module.ts
> @ ./main.ts
> Executing webpack failed with exit code 2.

I have the same issue. Any progress so far?

**Comment by Muhanady** [comment]
I had the exception below 
`ERROR in ../node_modules/nativescript-ui-sidedrawer/__ivy_ngcc__/angular/side-drawer-directives.js
Module not found: Error: Can't resolve '../angular' in 'D:\Native\new-native\MyApp\node_modules\nativescript-ui-sidedrawer\__ivy_ngcc__\angular'
 @ ../node_modules/nativescript-ui-sidedrawer/__ivy_ngcc__/angular/side-drawer-directives.js 3:10-31 6:23-44
 @ ./app/app.module.ts
 @ ./main.ts`

and I ware able to solve it by changing node_modules/nativescript-ui-sidedrawer/__ivy_ngcc__/angular/side-drawer-directives.js file to 
var __1 = require("./../../"); <================= was ./..
var page_1 = require("tns-core-modules/ui/page");
var element_registry_1 = require("nativescript-angular/element-registry");
var sideDrawerModule = require("./../../");<=============== was ./..
this solution might be not the perfect one and in any update it will get lost but until team update the solution this can be used.

**Comment by HendricksonTyler** [comment]
For anybody experiencing some of the issues mentioned above, in my case it was:
```ERROR in ../node_modules/nativescript-ui-sidedrawer/__ivy_ngcc__/angular/side-drawer-directives.js
Module not found: Error: Can't resolve './..' in '/Users/tylerhendrickson/Repositories/SomeApp/node_modules/nativescript-ui-sidedrawer/__ivy_ngcc__/angular'
 @ ../node_modules/nativescript-ui-sidedrawer/__ivy_ngcc__/angular/side-drawer-directives.js 3:10-25 6:23-38
 @ ./app/app.module.tns.ts
 @ ./main.tns.ts
```
Try clearing your `node_modules` and `platforms` and run another `npm i`. Seems to have fixed the issue in my case.

**Comment by NathanWalker** [comment]
Closing this now since Ivy issues are about to be thing of past entirely with 10.1.2 of @nativescript/angular in moment.
