### ISSUE TITLE
Local build for iOS step by step

### ISSUE THREAD

**Issue by alexisconsuegra** [NativeScript/NativeScript#8621]
Where can I find a step by step guide to do local build for iOS?
I used to work on a windows system using SideKick with cloud builds, but since Sidekick was discontinue I turned to local build. I have never worked with xcode nor mac os before.

My first attempt to build failed.
ld; symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
note: Using new build systemnote: Planning buildnote: Construction build description
** BUILD FAILED 88
Command xcodebuild failed with exit code 65

Help!

**Comment by NathanWalker** [comment]
@alexisconsuegra Hi! Have you tried this guide: https://docs.nativescript.org/start/ns-setup-os-x
However I would skip Step 2 and instead use `nvm` to install node.
You can of course use latest node (guide mention 10 but you can use anything node 12 or 14).
This is a good guide for `nvm` if you haven't used it before: https://itnext.io/nvm-the-easiest-way-to-switch-node-js-environments-on-your-machine-in-a-flash-17babb7d5f1b

**Comment by alexisconsuegra** [comment]
Hello @NathanWalker Thanks for the response.
Yes, I used the guide "NativeScript Advanced Setup: macOS" to setup. That is done!
But what is next? How to build after the setup is done? 
I tried to follow:
"Publishing a NativeScript iOS App in the App Store" (https://docs.nativescript.org/tooling/publishing/publishing-ios-apps). But this guide is not clear to me.
Basically I did:
tns prepare ios --release
and next
tns build ios 
in that order. But build failed. What am I missing? (Most likely a lot, but what are the steps)
Note: The same app used to build fine in the cloud with Sidekick.

**Comment by alexisconsuegra** [comment]
@NathanWalker just want to add that I used to work on a Windows system and relied on Sidekick for builds and publishing.

**Comment by NathanWalker** [comment]
Are you build {N} with Angular? If so, try building with this command:
```
tns build ios --env.aot --env.uglify --env.production --release
```

That single command is how we build everything. (If not angular based app, no need to add `--env.aot`). Then just open the .xcworkspace file in XCode, and Archive to upload to store.

**Comment by alexisconsuegra** [comment]
Hi, not Angular. it is plain JavaScript.
I would need to configure the p12 and mobile provision, first right? Where is it done?
Thanks again

**Comment by NathanWalker** [comment]
XCode makes that much easier these days. Assuming you have a developer account with apple just login to it in XCode and open the `platforms/ios/projectname.xcworkspace` and choose project in top left file window and in the middle there's an area of tabs, one of which is Signing related where you can choose your development team from the dropdown. Always best to leave 'Automatically manage signing' enabled 👍 
<img width="754" alt="Screen Shot 2020-06-08 at 3 08 28 PM" src="https://user-images.githubusercontent.com/457187/84085196-ea0c8180-a999-11ea-8f44-4d592c21eeed.png">

**Comment by alexisconsuegra** [comment]
@NathanWalker thanks a lot. I was able to add my developer account to Team. But no much progress. Then I went product -> build. But build still fails.
Keep in mind. Most or all of us now struggling by the sun-setting of Sidekick are not a mac-os developers. I have never worked on mac before and just forced by the recent events got myself a mac PC. The latest OS it supports is High Sierra and therefore xcode is not the latest and greatest. Any how I need to publish this app.

Here is my Xcode version 

![thumbnail_Screen Shot 2020-06-08 at 9 49 30 PM](https://user-images.githubusercontent.com/45446335/84098770-1ba33e00-a9d6-11ea-84a7-70cd3e5035ca.png)

The Error:

![thumbnail_Screen Shot 2020-06-08 at 10 05 25 PM](https://user-images.githubusercontent.com/45446335/84098787-26f66980-a9d6-11ea-8b23-cd28c61ed708.png)

Once again. I appreciate all your help.

**Comment by NathanWalker** [comment]
@alexisconsuegra if you’re in a bind and open to this, just shoot an email to support@nativescript.org and someone can share an email to invite to your Apple developer team to help you publish the app and then we can look further into your setup. It’s likely you could install an older version of nativescript like version 5 which supported that older xcode version.
