### ISSUE TITLE
Slow Rendering UI

### ISSUE THREAD

**Issue by ukik** [NativeScript/NativeScript#8625]
I am NS fanboy, I have bad experience on UI rendering in NS is slower (too slower) comparing with React Native or Flutter.

For example 
first: I have UI that larger than screen height viewport, the apps slow to render them.
two: When I navigate from 1 page to anathor page, the new page has to rerendering again n again, this  is bad user experience (repeatation resource cost), this is mobile not website so user think rerendering visited page make my user complain
third: App should wait for few second to display new page with enough complex component

Any idea what NS plan to solve above problems?

**Comment by NathanWalker** [comment]
@ukik Thanks for posting. Is it possible to share the project on github? Like a lot of things performance can be affected by subtle approaches to layout handling and numerous other things so a peek at your project would help answer with more clarity.

**Comment by DimitrisRK** [comment]
> two: When I navigate from 1 page to anathor page, the new page has to rerendering again n again, this is bad user experience (repeatation resource cost), this is mobile not website so user think rerendering visited page make my user complain
> third: App should wait for few second to display new page with enough complex component

Regarding tab navigation, if your tabs consist of frames and pages, you can always implement lazy-loading yourself. Inside each page's 'loaded' callback, you can check if page has already a binding context from a previous loading. If it does, just avoid setting context anew.

That also demands putting all stuff like http requests inside your view-model's constructor.
I already have an app that uses BottomNavigation and the behaviour above.

About third, I'm not sure what you are talking about.

**Comment by NathanWalker** [comment]
@DimitrisRK Sounds like you have a good handle on your issue. Would you like to submit a PR to solve your case? Additionally a project to share on github with the setup you mention would help us collaborate on any aspects of it to more clear identify what you experience.

**Comment by DimitrisRK** [comment]
@NathanWalker I personally don't have any loading issue. :) I'm trying to explain that BottomNavigation tab system works really good on NS if proper patterns are used.

**Comment by NathanWalker** [comment]
Excellent @DimitrisRK 🎉 thanks for sharing. Please let us know if you encounter any other issue.

**Comment by DimitrisRK** [comment]
@NathanWalker I think there's been a mistake here. I'm not the starter of this issue, but merely somebody who shared his own experience. My first comment was an answer to @ukik .

**Comment by ukik** [comment]
> @ukik Thanks for posting. Is it possible to share the project on github? Like a lot of things performance related, very subtle approaches to layout handling and numerous other things can have an effect - a peek at your project would help answer with more clarity.

This is my example project that I can share the codebase for investigation
https://github.com/ukik/az-zahra

**Comment by ukik** [comment]
while I currently making start-up using Nativescript as my technology... hope NS going faster n better
