### ISSUE TITLE
typescript error: Subsequent variable declarations must have the same type.  Variable 'global' must be of type 'Global & typeof globalThis', but here has type 'Global'.

### ISSUE THREAD

**Issue by ReyPena** [NativeScript/NativeScript#8628]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.7.4
 - Cross-platform modules: 
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
TypeScript returns type error subsequent variable declarations must have the same type.  Variable 'global' must be of type 'Global & typeof globalThis', but here has type 'Global'.

**To Reproduce**
build

**Expected behavior**
TypesScript should return no error

**Additional context**
This is been reported in other projects like the main angular project  many others

**Comment by NathanWalker** [comment]
Thank you @ReyPena  - I believe this may be related to the core modules version. I notice in your package there you have:
```
"@nativescript/core": "~6.2.0",
```
however based on all other version in your package you should be using this instead:
```
"@nativescript/core": "~6.5.0",
```

**Comment by ReyPena** [comment]
I made the change and upgrade the package, and I'm still getting the same error.
To verify that the package was not cached I removed the node_modules folder and the global cache for the packages.

**Comment by NathanWalker** [comment]
@ReyPena are you using a code sharing project generated with @nativescript/schematics?
Those have not been updated for angular 9 yet.

**Comment by NathanWalker** [comment]
Also possible to share this project? I'd like to poke around given the error you reported which I've never seen before.

**Comment by NathanWalker** [comment]
Keep in mind `6.6.0-next-2020-05-08-112112-01` is not latest - that's actually old from May 8 --- latest is 6.5.5.

**Comment by ReyPena** [comment]
I can not share the project since is for the place I work for but it is really easy to recreate you just need to run `ng new ${Project name}` using the angular cli version 9.1.0, once that is generated you can just follow the instructions in the nativescript webside `ng add @nativescript/schematics`, this is enough to replicate the bug in fact a version higher than that will show another bug with the new interface from angular.
I was wondering if there is somewhere a table of compatibility or something that will show what angular verions are compatible with the different versions of nativescript? I think this will be really helpful!

Again thank you very much!

**Comment by NathanWalker** [comment]
@ReyPena Thanks for the extra info. That makes sense now, @nativescript/schematics Angular 9 ivy official support is in progress here: https://github.com/NativeScript/nativescript-schematics/pull/276/files
We expect that to be available early next week and will ping you back here to try it 👍

**Comment by NathanWalker** [comment]
@ReyPena We have published a beta of @nativescript/schematics which you can try.
```
npm i @nativescript/schematics@9.0.0-beta.0
```
You should follow similar instructions here with updating your codebase for Angular 9:
https://github.com/NativeScript/nativescript-angular/wiki/Updating-and-developing-for-@nativescript-angular-v9-with-Ivy-or-without

Let us know if you see better results after using the schematics beta. We're looking to publish it official by end of week with confirmation from other projects that it works as expected.

**Comment by NathanWalker** [comment]
@ReyPena I'm going to close this as @nativescript/schematics ~9.0.0 has been released and should not exhibit this issue but please post back if you still see something here.
