### ISSUE TITLE
Nativescript full setup installation problem

### ISSUE THREAD

**Issue by hanimatary147** [NativeScript/NativeScript#8633]
whenever i type the @powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((new-object net.webclient).DownloadString('https://www.nativescript.org/setup/win'))" to cmd i get:

Exception calling "DownloadString" with "1" argument(s): "The underlying connec
tion was closed: An unexpected error occurred on a send."
At line:1 char:47
+ iex ((new-object net.webclient).DownloadString <<<< ('https://www.nativescrip
t.org/setup/win'))
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

please help

**Comment by rigor789** [comment]
@hanimatary147 can you try opening https://www.nativescript.org/setup/win in your browser - does it download `native-script.ps1`? I just tested the following command, and the setup script ran without any errors:
```cmd
@PowerShell -NoProfile -ExecutionPolicy Bypass -Command "iex ((new-object net.webclient).DownloadString('https://www.nativescript.org/setup/win'))"
```

**Comment by hanimatary147** [comment]
yes it downloads it

**Comment by hanimatary147** [comment]
but still the same problem

**Comment by Ross-Olivares** [comment]
Hey @hanimatary147 This usually happen when the link is not accessible by your network. Although, you said you are able to access by your web browser but is there a chance you can turn off your firewall and try it. Also Ensure that you are not going through a gateway or proxy that is preventing specific ports.
Hope it helps!!!

**Comment by hanimatary147** [comment]
I'm still facing the same problem, turned off firewall and made sure gateway or proxy is not preventing ports

**Comment by hanimatary147** [comment]
i updated my powershell and .net framework to 4.5 then downloaded chocolety
