### ISSUE TITLE
iOS large title doesn't work properly

### ISSUE THREAD

**Issue by cybaj** [NativeScript/NativeScript#8636]
**Environment**
- CLI: 6.5.0
- Cross-platform modules: 6.5.5
- Android Runtime: 6.5.0
- iOS Runtime: 6.5.0
- Plugin(s): -
- Node.js: v12.16.1

**Describe the bug**
I followed the [nativescripting tutorial](https://nativescripting.com/posts/how-to-use-ios-large-titles)
for animating the navigion bar in iOS, I set like below.
```
page.frame.ios.controller.navigationBar.prefersLargeTitles = true;
```
but it doesn't animating. The navigation title just stands largely, not animating.
I don't know that [largeTitleDisplayMode](https://developer.apple.com/documentation/uikit/uinavigationitem/2909056-largetitledisplaymode) affects, I switched that property but, doesn't works.
```
const auto = UINavigationItemLargeTitleDisplayMode.Automatic;
const never_ = UINavigationItemLargeTitleDisplayMode.Never;
const always = UINavigationItemLargeTitleDisplayMode.Always;
page.frame.ios.controller.navigationBar.items[0].largeTitleDisplayMode = auto;
```
- only works with `Never`, just like what it should that large navigation title doesn't show up.
- `Auto` and `Always` shows like below. It overwrapped. It didn't animate. 
![issue](https://i.ibb.co/j9NqV2T/issue.jpg)

**To Reproduce**
`tns preview`

**Expected behavior**
![gif](https://nativescripting.com/d4984352eb5bf6df77880175fd4c1a5d/collapsible_large_title.gif)

**Sample project**
[repo](https://github.com/cybaj/ios_large_title)

**Additional context**
iOS version : 13.3

**Comment by NathanWalker** [comment]
Thank you for the sample project @cybaj 👍

**Comment by cybaj** [comment]
I recently got Mac machine, and I tried to `build` it with local machine.
It works with local `build`. 
This issue only occurs with `preview`. Personally it is hard to know, which works on `preview` or not, even with [this explanation](https://docs.nativescript.org/start/quick-setup#quick-setup-limitations).
Anyway, I think it is good to closing this issue.
