### ISSUE TITLE
Hi @3rror404

### ISSUE THREAD

**Issue by vinothpnl** [NativeScript/NativeScript#8656]
Hi Team,

I followed the instructions but still no the issue exists. please help me. 

Deleted thhe hooks, node_modules, platforms and matched the versions with tns-core-modules and tns-core-widgets

 "tns-core-modules": {
      "version": "6.3.2",
      "resolved": "https://registry.npmjs.org/tns-core-modules/-/tns-core-modules-6.3.2.tgz",
      "integrity": "sha512-WoMslVNu8OSSjNA83xU2DIcvsXeM4zDzgMwD5JRpiw4zrCO9CylM1TZOcat9tw3zkourA/ZK7p8r4efbW9rt6A==",
      "requires": {
        "@nativescript/core": "6.3.2"
      }
    },
    "tns-core-modules-widgets": {
      "version": "6.3.2",
      "resolved": "https://registry.npmjs.org/tns-core-modules-widgets/-/tns-core-modules-widgets-6.3.2.tgz",
      "integrity": "sha512-qnpPFUMvty31BoaD7lMur0BvA2yFemr2JJw/wT4fJwKT2nBlhlNnKv9oeDNQAhawZvTBR5hfkBDNVEPzErxObg=="
    },

![image](https://user-images.githubusercontent.com/49946598/85033158-ed192600-b180-11ea-8aa8-a1b010550166.png)

**Comment by rigor789** [comment]
6.3.2 is a fairly old version - are you locked into using it for any reason? 

Please also share the runtime version (or your whole `package.json`)

**Comment by vinothpnl** [comment]
Hi rigor789, Thank you for the response. There's no other reason than matching with tns-core-modules and tns-core-modules-widgets. Please find below for the software versions that I use and also package.json
tns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.7.4 version and is up to date.
⚠ Update available for component tns-core-modules. Your current version is 6.3.2 and the latest available version is 6.5.7.
⚠ Update available for component tns-android. Your current version is 6.4.1 and the latest available version is 6.5.1.
⚠ Update available for component tns-ios. Your current version is 6.4.0-2020-01-13-121401-01 and the latest available version is 6.5.1.

nativescript --version
6.7.4

package.json

{
  "nativescript": {
    "id": "org.nativescript.testapp",
    "tns-ios": {
      "version": "6.4.0-2020-01-13-121401-01"
    },
    "tns-android": {
      "version": "6.4.1"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/theme": "~2.2.0",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "@nstudio/nativescript-cardview": "^1.0.0",
    "@sunify/lerp-color": "^2.0.0",
    "d3-interpolate": "^1.4.0",
    "dotenv": "^8.2.0",
    "nativescript-angular": "~8.20.0",
    "nativescript-app-environment": "^1.0.0",
    "nativescript-dna-deviceinfo": "^2.4.3",
    "nativescript-local-notifications": "^4.2.0",
    "nativescript-material-bottomnavigationbar": "^3.1.10",
    "nativescript-material-ripple": "^3.1.6",
    "nativescript-modal-datetimepicker": "^1.2.1",
    "nativescript-ng-ripple": "^2.0.1",
    "nativescript-platform-css-free": "^1.6.16",
    "nativescript-ripple": "^2.2.1",
    "nativescript-secure-storage": "^2.6.0",
    "nativescript-statusbar": "^5.0.0",
    "nativescript-ui-chart": "^7.1.1",
    "polate-js": "^1.0.5",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.3.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/cli": "^8.3.20",
    "@angular/compiler-cli": "~8.2.0",
    "@nativescript/schematics": "^0.7.3",
    "@ngtools/webpack": "~8.2.0",
    "@types/dotenv": "^8.2.0",
    "nativescript-dev-webpack": "~1.4.0",
    "node-sass": "4.12.0",
    "tslint": "^5.20.1",
    "typescript": "~3.5.3"
  },
  "gitHead": "a6fec076a20f898feabb4466a2c411158c18a100",
  "readme": "NativeScript Application"
}

**Comment by vinothpnl** [comment]
And also I tried with the latest version as well. Please help me

tns doctor
✔ Getting environment information 

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.7.4 version and is up to date.
✔ Component tns-core-modules has 6.5.7 version and is up to date.
✔ Component tns-android has 6.5.1 version and is up to date.
✔ Component tns-ios has 6.5.1 version and is up to date.

**Comment by MrSnoozles** [comment]
According to the error message it could be a problem in nativescript-ui-chart (https://github.com/ProgressNS/nativescript-ui-feedback) in combination with dark mode. Specifically the problem appears to occur in RadCartesianChart. Do you have the possibility to disable or remove that chart and see if the app starts?

**Comment by vinothpnl** [comment]
@MrSnoozles, I have updated sdk tools from 28 to 29 and everything works fine. :) Thank you for the support
