### ISSUE TITLE
Failed to apply property x with value y

### ISSUE THREAD

**Issue by stefanoScalzo** [NativeScript/NativeScript#8661]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.7.4
 - Cross-platform modules:6.6.0
 - Android Runtime:6.5.1
 - iOS Runtime:6.5.1
 - Plugin(s):

**Describe the bug**
While trying to apply a css property for a button when its disabled i get this
Error: Failed to apply property [background-color] with value [grey] to Button(105). ZoneAwareError(file: node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:1298:0)
at Color(file: node_modules/@nativescript/core/color/color-common.js:28:0)
at Color(file: node_modules/@nativescript/core/color/color.ios.js:6:0)
at valueConverter(file: node_modules/@nativescript/core/ui/styling/style-properties.js:613:81)
at set(file: node_modules/@nativescript/core/ui/core/properties/properties.js:670:0)
at file: node_modules/@nativescript/core/ui/styling/style-scope.js:499:0
at file: node_modules/@nativescript/core/ui/styling/style-scope.js:393:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:284:0
at file: node_modules/@nativescript/core/ui/styling/style-scope.js:391:0
at file: node_modules/@nativescript/core/ui/styling/style-scope.js:340:57
at file: node_modules/@nativescript/core/data/observable/observable.js:110:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:324:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:341:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:616:0
at valueChanged(file: node_modules/@nativescript/core/ui/core/view/view-common.js:1044:0)
at file: node_modules/@nativescript/core/ui/core/properties/properties.js:166:0
at file: node_modules/@nativescript/angular/view-util.js:290:0
at file: node_modules/@nativescript/angular/view-util.js:263:0
at file: node_modules/@nativescript/angular/renderer.js:181:0
at file: node_modules/@angular/core/fesm5/core.js:30484:0
at setElementProperty(file: node_modules/@angular/core/fesm5/core.js:28555:0)
at checkAndUpdateElementValue(file: node_modules/@angular/core/fesm5/core.js:28506:0)
at checkAndU<…>

**To Reproduce**
Add a styling for a disabled property and then load that disabled property
**Expected behavior**
No errors
`Button:disabled {
    background: lightgray;
    background-color: grey;
    border-color: white;
}`

**Comment by Ross-Olivares** [comment]
Hi @stefanoScalzo 
Thank you for reporting this issue.
We are going to try replicate this case on our end and will confirm. We will research what is causing this issue and will provide the needed fix. For further info, you could keep track the issue.

**Comment by janoshrubos** [comment]
I've tried to reproduce this issue, but it looks like it had been fixed.

If this error is still relevant, feel free to open a new issue!
