### ISSUE TITLE
Typescript Does Not Seem To Have Javasvript Array.create(...) Function

### ISSUE THREAD

**Issue by goduware** [NativeScript/NativeScript#8664]
View details in this link: https://stackoverflow.com/questions/62533429/typescript-does-not-seem-to-have-javasvript-array-create-function

**Comment by Ross-Olivares** [comment]
Hi @goduware 
Thank you for reporting this issue.
We are going to research this case on our end and will confirm. For further info, you could keep track the issue.

**Comment by NathanWalker** [comment]
@goduware are you hitting that in a code sharing project when you run your web app which may have had {N} code in it?

**Comment by goduware** [comment]
Hello Nathan,
Thanks for the response. There are 2 native projects, vanilla JS &
typescript created with the tns create command-line syntax:

I need to call an Android API package class function in the .js and .ts
files of the respective project (both .js & .ts files) are having similar
come de

**Comment by triniwiz** [comment]
In TS try updating to the latest version since the typings were recently (not sure which version) added so you can try `(Array as any).create(‘byte’, 10);` in the older versions

**Comment by goduware** [comment]
Hello Nathan,
Thanks for the response. There are 2 {N} projects, vanilla JS & typescript
created with the tns create command-line syntax:

I need to call an Android API package class function in the .js and .ts
files of the respective project (both .js & .ts files are having similar
codes).  The Android API function requires a primitive byte array as a
parameter.

I could create the primitive byte array in the Vanilla JS thus:
var arry = Array.create("byte", 10);
and it was acceptable to the Android API function.

However, Typescript doesn't seem to recognize the Array.create(...)
function and an attempt to create the byte array with Uint8Array or
int8Array wasn't accepted by the Android API requiring a primitive byte
array as a parameter.

How do I use Array.create(...) function in Typescript.

**Comment by goduware** [comment]
OK noted. Typescript version in package.json is 3.8.3.

**Comment by goduware** [comment]
Yes, using (Array as any).create(...) solved the issue with Typescript.
Thanks a lot.

**Comment by triniwiz** [comment]
Happy to help
