### ISSUE TITLE
Syntax error in @nativescript/core/ui/core/view/view.d.ts

### ISSUE THREAD

**Issue by chadzxrex** [NativeScript/NativeScript#8668]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.7.4
 - Cross-platform modules: 6.3.2
 - Android Runtime: 6.3.0
 - iOS Runtime: 6.3.0
 - Plugin(s):

**Describe the bug**

![image](https://user-images.githubusercontent.com/67261230/85526597-bb023b00-b63c-11ea-959e-f6bf772a9c51.png)

The comments which explain how to use the properties, `originX` and `originY`, include syntax errors. The wording '**deafault**' should be '**default**' instead.

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by chadzxrex** [comment]
If the issue is confirmed, I can work on this one!

**Comment by rigor789** [comment]
@chadzxrex Absolutely! All fixes are welcome 💯

**Comment by changda0616** [comment]
Just submit the PR using my personal account. :) Lemme know if any can be improved! Thanks!
