### ISSUE TITLE
utils.ad.async method is not implemented

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#867]
Seems the `utils.ad.async` method is not implemented...

**Comment by enchev** [comment]
Hi @PeterStaev,

My mistake! I've played a bit in the past however the code didn't played well and I've forgot to remove this declaration. I'll remove it right away!

Thanks

**Comment by PeterStaev** [comment]
Hi @enchev , 

Remember to remove it from the NS Docs as well :) https://docs.nativescript.org/ApiReference/utils/utils/ad/README
