### ISSUE TITLE
@tap events not being recognized on Android (Nativescript-Vue)

### ISSUE THREAD

**Issue by satyak450** [NativeScript/NativeScript#8671]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.7.4
 - TNS Core Modules: 6.5.8
 - Android Runtime: 6.5.1
 - iOS Runtime: 6.5.1
 - Nativescript Vue: 2.6.4

**Describe the bug**
Tap events are not recognized by any elements other than `<Button>` on Android. I'm trying to add `@tap` event handlers to an `<Image>` and `<GridLayout>`. It works fine on iOS.

**To Reproduce**
```html
<GridLayout columns="100, *" class="settings-box" @touch="hello" backgroundColor="blue">
    <Label col="1" text="Log Out" class="settings-text"  style="color: red"/>
</GridLayout>
```

The method:
```js
hello: function() {
    console.log('Testing that tap function works');
},
```
**Expected behavior**
"Testing that tap function works" is printed in the console.

**Comment by rigor789** [comment]
@satyak450 Can you share a project where this is happening? I just tested your layout/code and I am getting console logs.

In your code you had `@touch` - I tried both `@touch` and `@tap` and both printed the logs.

**Comment by satyak450** [comment]
The @touch was a typo, sorry. If it helps the GridLayout is in a TabViewItem. Here is the code for the TabViewItem if that helps.
`<TabViewItem iconSource="~/components/pictures/Settings.png" isPassThroughParentEnabled="true">
                <ScrollView isPassThroughParentEnabled="true" backgroundColor="orange">
                    <StackLayout id="outer-container" isPassThroughParentEnabled="true">
                        <GridLayout columns="100, *" class="settings-box" @tap="sendReport">
                            <Image col="0" src="~/components/pictures/GreyReport.png" class="settings-pic" />
                            <Label col="1" text="Report a Problem" class="settings-text"/>
                        </GridLayout>
                        <GridLayout columns="100, *" class="settings-box" @tap="handleLogout">
                            <Image col="0" src="~/components/pictures/GreyLogout.png" class="settings-pic"/>
                            <Label col="1" text="Log Out" class="settings-text"  style="color: red"/>
                        </GridLayout>
                    </StackLayout>
                </ScrollView>
            </TabViewItem>`

**Comment by satyak450** [comment]
Somehow it resolved itself and `@tap` works now. Thank you @rigor789 for the help.

**Comment by liamcharmer** [comment]
> tap

Do you know what sorted the issue or was it just randomly sorted
