### ISSUE TITLE
LongPress Event : NS iOS

### ISSUE THREAD

**Issue by phoenix503** [NativeScript/NativeScript#8681]
**Environment**
I am running app in iOS 13 with NS-ng code

**Describe the bug**
Whenever i clicked button with long press event , it is fired twice instead of once

**To Reproduce**
https://play.nativescript.org/?template=play-ng&id=0HkoIB

**Expected behavior**
It should occur only once as it is in android. It is working fine

**Sample project**
https://play.nativescript.org/?template=play-ng&id=0HkoIB

**Comment by Ross-Olivares** [comment]
Hi @phoenix503 
Thank you for reporting this issue.
We are going to try replicate this case on our end and will confirm. We will research what is causing this issue and will provide the needed fix. For further info, you could keep track the issue.

**Comment by phoenix503** [comment]
Okay @Ross-Olivares  👍

**Comment by dosomder** [comment]
Duplicate: https://github.com/NativeScript/NativeScript/issues/3573

**Comment by phoenix503** [comment]
Okay
