### ISSUE TITLE
ScrollEvent not Working iOS

### ISSUE THREAD

**Issue by phoenix503** [NativeScript/NativeScript#8682]
**Environment**
Angular project NS

**Describe the bug**
As you can see , this is function in ngOnInit to scroll to bottom , but its not happening in iOS neither in Android

**To Reproduce**
https://play.nativescript.org/?template=play-ng&id=BzyRcR

**Expected behavior**
It should auto scroll to the end after a time interval

**Sample project**
https://play.nativescript.org/?template=play-ng&id=BzyRcR

**Comment by triniwiz** [comment]
Try calling the method after the view has been measured and laid out you can try binding to `layoutChanged` event there you know the nativeView has been loaded and laid out also a chance where the nativeView will be null onInit so your method will not do anything

**Comment by phoenix503** [comment]
@triniwiz  it is working now :)
