### ISSUE TITLE
@nativescript/core >= 6.5.3 requires tns-core-modules-widgets 6.6.0-next-2020-05-08-...

### ISSUE THREAD

**Issue by felixkrautschuk** [NativeScript/NativeScript#8689]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.7.8
 - Cross-platform modules: 6.5.2
 - Android Runtime: -
 - iOS Runtime: -
 - Plugin(s): -

**Describe the bug**
Not sure if it is a bug or the desired behavior, but I think when upgrading @nativescript/core via `tns plugin add @nativescript/core@latest`, do dependency should point to a @next release that might be unstable.

Right now this happens:
<img width="1294" alt="Bildschirmfoto 2020-07-03 um 11 07 40" src="https://user-images.githubusercontent.com/6443021/86454260-45bef600-bd1f-11ea-8199-ef49cde81165.png">

**To Reproduce**
See description

**Expected behavior**
Upgrading a component to @latest should upgrade its dependencies to @latest as well, not to @next.

**Sample project**
-

**Additional context**
-

**Comment by rigor789** [comment]
Hey @felixkrautschuk - thanks for the heads up, we are looking into why this was done this way - and we'll be fixing the versions in an upcoming release!

**Comment by madmas** [comment]
seems to be fixed with the recent release:

<img width="891" alt="grafik" src="https://user-images.githubusercontent.com/37251/87419626-1e481300-c5d4-11ea-873e-3ef5e2711c42.png">

**Comment by felixkrautschuk** [comment]
@madmas @rigor789 I can confirm that this does not occur anymore updating to the latest @nativescript/core version.
Thanks
