### ISSUE TITLE
Is nativescript-facebook plugin actively maintained?

### ISSUE THREAD

**Issue by zhivkohinkov** [NativeScript/NativeScript#8696]
I posted an issue 7 days ago without any response, also saw there's no commit activity since early November last year. Demos haven't been updated, Is the plugin still being actively maintained?

Here's a [link](https://github.com/NativeScript/nativescript-facebook/issues/226) to the issue, if someone has stumbled upon this, a possible solution will be greatly appriciated.

**Comment by zhivkohinkov** [comment]
The issue was solved, will leave an explanation on the plugin repository.

**Comment by NathanWalker** [comment]
Thanks for the update here @zhivkohinkov and posting on that plugin repo where it can be addressed 👍
