### ISSUE TITLE
Android: on phone back button, modal does not close, but the page behind modal navigates back

### ISSUE THREAD

**Issue by vasudevpareek07** [NativeScript/NativeScript#8697]
I am using 'nativescript-angular/modal-dialog'

**Current Behavior:**
Bug 1: When user taps on the phone back button in Android, modal does not close, but the page behind the modal navigates back.
Bug 2: After opening the modal and tapping on phone back button, if user tries to close the modal by tapping on the close button which is inside the modal, then application freezes

**Expected Behavior:**
Expected Solution For Bug 1: When modal is open, on pressing phone back button, it should close the modal and page behind the modal should not navigate.
Expected Solution for Bug 2: Mostly if Bug 1 is solved, then Bug 2 ideally will be solved, but the expected solution is tapping on the close button after pressing the phone back button should not freeze the application.

Angular version: 8.2.0
Nativescript version: 6.4.1
Note: It is happening in Android. Any quick help would be appreciated. Thanks

**Comment by Ross-Olivares** [comment]
Hi @vasudevpareek07 
Thank you for reporting this issue.
We are going to try replicate this case on our end. Let me know if you can send us a sample project that can reproduce the issue.

**Comment by wontroba666** [comment]
hello any progress with this bug ?

**Comment by rigor789** [comment]
> hello any progress with this bug ?

Unless there is a repro to see this behavior and make a fix, we can't really do anything with it.
