### ISSUE TITLE
Cannot create an ImageSource from an icon code.

### ISSUE THREAD

**Issue by ClementDreptin** [NativeScript/NativeScript#8699]
Hello,

I've been trying to create an `ImageSource` instance from an icon code and I can't figure it out. I'm using NativeScript-Vue with JavaScript.

Here's the example component I made:
```JS
<template>
    <Page @loaded="onLoad">
        <Image ref="image" />
    </Page>
</template>

<script>
    import { Color } from "tns-core-modules/color";
    import { Font } from "@nativescript/core/ui/styling/font";
    import { ImageSource } from "tns-core-modules/image-source";

    export default {
        methods: {
            onLoad() {
                let imageTag = this.$refs.image.nativeView;
                let fontHex = "#xf013";
                let color = new Color(255, 201, 33, 66);
                let font = new Font("fa-solid-900", 18, "normal", "900");
                imageTag.imageSource = ImageSource.fromFontIconCodeSync(fontHex, font, color);
            }
        }
    };
</script>
```

The expected result is a red [fa-cog icon](https://fontawesome.com/icons/cog) and all I get is a giant `#xf013` red string.

I think I'm either using the `Font` constructor wrong (especially the first parameter) or giving the wrong format to my `fontHex` string (I tried multiple other formats like `#&xf013`, `#f013` or even `font://#&xf013` and none of them worked).

You can see my issue in [this playground](https://play.nativescript.org/?template=play-vue&id=vki6PJ).

Thanks in advance.

**Comment by Ross-Olivares** [comment]
Hi @ClementDreptin 
Thank you for reporting this issue.
We are going to try replicate this case on our end and will confirm. We will research what is causing this issue and will provide the needed fix. For further info, you could keep track the issue.

**Comment by NathanaelA** [comment]
@ClementDreptin - You had two things wrong with your sample:
- First the `fonts/` folder must always be in the root app folder, not the components folder...
- Second this is expecting a normal JAVASCRIPT string of characters, not html based.  So the easiest way to make a JS string with unicode characters is to do either use String.fromCodePoint or use the unicode string prefix "\uXXXX"
So:
`imageTag.imageSource = ImageSource.fromFontIconCodeSync(String.fromCodePoint(0xf013), font, color);`
or 
imageTag.imageSource = ImageSource.fromFontIconCodeSync("\uf013", font, color);
