### ISSUE TITLE
ReferenceError: internalBinding is not defined

### ISSUE THREAD

**Issue by brendanalexdr** [NativeScript/NativeScript#8701]
This is the same as [#7285](https://github.com/NativeScript/NativeScript/issues/7285), but I can't find a solution, despite fastidious googling.  

**Node**:  v10.21.0
**Operating System**:  Windows 10

I am trying to install the nativescript cli.  
`npm install -g nativescript` gives me the following: 
> ReferenceError: internalBinding is not defined
>    at internal/util/inspect.js:31:15
>    at req_ (C:\Users\brend\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:140:5)
>    at require (C:\Users\brend\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:113:12)
>    at util.js:25:21
>    at req_ (C:\Users\brend\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:140:5)
>    at require (C:\Users\brend\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:113:12)
>    at fs.js:42:21
>    at req_ (C:\Users\brend\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:140:5)
>    at Object.req [as require] 
>  (C:\Users\brend\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:54:10)
    at Object.<anonymous> 
> (C:\Users\brend\AppData\Roaming\npm\node_modules\nativescript\node_modules\fstream\node_modules\graceful-fs\fs.js:1:37)
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\nativescript\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> + nativescript@5.0.0
> added 947 packages from 1340 contributors in 19.631s

`tns -v`  gives me the following
> ReferenceError: internalBinding is not defined
>    at internal/util/inspect.js:31:15
>    at req_ (C:\Users\brend\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:140:5)
>    at require (C:\Users\brend\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:113:12)
>    at util.js:25:21
>    at req_ (C:\Users\brend\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:140:5)
>    at require (C:\Users\brend\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:113:12)
>    at fs.js:42:21
>    at req_ (C:\Users\brend\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:140:5)
>   at Object.req [as require] (C:\Users\brend\AppData\Roaming\npm\node_modules\nativescript\node_modules\natives\index.js:54:10)
    at Object.<anonymous> >(C:\Users\brend\AppData\Roaming\npm\node_modules\nativescript\node_modules\fstream\node_modules\graceful-fs\fs.js:1:37)

I have tried restarting.  Uninstalling/reinstalling.  Npm cache verify/re-installing.  No luck.

**Comment by brendanalexdr** [comment]
Ok I figured this out myself.  It appears there was an old version of the cli on my system at the following location that was, like a zombie, not responding to uninstall requests :
> C:\Users\brend\AppData\Roaming\npm\node_modules\nativescript

So I manually deleted this directory then ran the following: 
`npm cache verify`  and then
`npm install -g nativescript --force`
And that worked.

**Comment by NathanWalker** [comment]
Awesome thanks for letting us know @brendanalexdr 🤗
