### ISSUE TITLE
TabStrip Switch Item Issue

### ISSUE THREAD

**Issue by phoenix503** [NativeScript/NativeScript#8712]
**Environment**
I am using it in Android v10.0 

**Describe the bug**
Try switching between the tabs by sliding on the screen not on the tabs and see the color it is not as specified which is given. The colors are not changing for selectedtab.

**To Reproduce**
https://play.nativescript.org/?template=play-ng&id=TStMfT

**Expected behavior**
The unselected Tab color should change accordingly 

**Sample project**
https://play.nativescript.org/?template=play-ng&id=TStMfT

**Comment by felixkrautschuk** [comment]
@phoenix503 seems to be a duplictate of the issue I created some months ago:

https://github.com/NativeScript/NativeScript/issues/8552

**Comment by phoenix503** [comment]
@felixkrautschuk  it is still Open , no solution is given or solved by NS

**Comment by felixkrautschuk** [comment]
@phoenix503 that's right, but it is not useful to open a new discussion about an already existing issue.

**Comment by phoenix503** [comment]
okay @felixkrautschuk

**Comment by CL-Guzman-Alejandro** [comment]
This bug still present with no way to solve this.

**Comment by DimitrisRK** [comment]
@CL-Guzman-Alejandro Seems it's a rule priority issue as it works pretty good if you do it with CSS rules that override theme rules (using a stronger rule).
Example:
```
.my-parent-layout TabStrip {
    selected-item-color: red;
}
```
