### ISSUE TITLE
(Android) textfield loses focus when another textfield gets removed

### ISSUE THREAD

**Issue by jerbob92** [NativeScript/NativeScript#8713]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.7.8
 - Cross-platform modules: 6.5.9
 - Android Runtime: 6.5.2
 - iOS Runtime: 6.5.1
 - Plugin(s): (unrelated)

**Describe the bug**

When you are editing a text in a TextField, and another TextField get's removed (for us it's because it's in an ngFor and on the background the array is being recreated so the views in the ngFor are being rebuilt, this is intended behaviour. But I could also reproduce it with an ngIf) the focus is being removed from the TextField that you have focus on. This is due to the fact that the keyboard gets hidden when a TextFields [gets unloaded](https://github.com/NativeScript/NativeScript/blob/eac179cd3f60b3e85b97d34b040edc42c94e62bc/nativescript-core/ui/editable-text-base/editable-text-base.android.ts#L188), this logic [does not check](https://github.com/NativeScript/NativeScript/blob/eac179cd3f60b3e85b97d34b040edc42c94e62bc/nativescript-core/utils/native-helper.android.ts#L60) whether that TextField actually has focus on that moment.

**To Reproduce**

- Create a view with 2 textfields, in your controller create code that adds/removes the second textfield every couple of seconds.
- Start the app
- Focus the first field, the keyboard should appear
- After a few seconds the second field disappears and the keyboard gets hidden

**Expected behavior**
The keyboard should stay visible because the field that you are editing is still there

**Sample project**

https://play.nativescript.org/?template=play-ng&id=lw0Few

**Additional context**

I created a fix in my fork: https://github.com/jerbob92/NativeScript/commit/bbbfa814050f0114fda486e183ae5ee074f8fe9b
It checks whether the view that you are trying to hide is actually has focus right now when you pass it as parameter for the method, for me this fix worked, but I'm not sure if it will affect any other code/logic in NS.

**Comment by farfromrefug** [comment]
Actually not that easy. The native way would work either on both iOS and Android seeing what you do. 
So I don't think this is something we should handle in N.
Instead the right way to do this is to use visibility to hide (or collapse) the tf you don't want depending on your logic

**Comment by jerbob92** [comment]
What do you mean by "The native way would work either on both iOS and Android seeing what you do."? I know what I'm doing might be uncommon, but it's not an impossible use-case. In my case its not possible to do this with visibility. However, I do think N is doing something here that it shouldnt: changing keyboard behaviour based on a field that isn't even focussed /in the viewport. I get that working with visibility is a valid workaround for most, but it's not a fix. Can you explain to me why my proposal isn't correct? Also, this behaviour isn't on iOS.

**Comment by farfromrefug** [comment]
Sorry I meant would not work natively. But maybe I did not understand what you meant. Can you create a very simple project reproducing your issue ?

**Comment by jerbob92** [comment]
On both iOS and Android you can dynamically create and add text field to a view, so it is possible to recreate this natively.

And I did create a sample project, it's in the post: https://play.nativescript.org/?template=play-ng&id=lw0Few
