### ISSUE TITLE
[Angular 10] shared project after create nsc run android --emulator  Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function System.err: TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by maticbezjak** [NativeScript/NativeScript#8714]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  6.8.0-rc.4
 - Cross-platform modules:  6.5.10
 - Android Runtime: 6.5.3
 - iOS Runtime: none
 - Plugin(s): none 

**Describe the bug**
When i run this command ng new -c=@nativescript/schematics sass-project-angular10 --shared --style=scss to create a shared project it creates it with no issues. But when i run tns run android it build it okay but when app is luchend i get this error:

Successfully synced application org.nativescript.sassprojectangular10 on device emulator-5556.
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: Object(...) is not a function
System.err: File: (file: node_modules\@nativescript\angular\fesm2015\nativescript-angular.js:2976:29)
System.err:
System.err: StackTrace:
System.err: (file: node_modules\@nativescript\angular\fesm2015\nativescript-angular.js:2976:29)
System.err:     at ../node_modules/@nativescript/angular/fesm2015/nativescript-angular.js(file:///data/data/org.nativescript.sassprojectangular10/files/ap
p/vendor.js:95242:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:816:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at (file:///data/data/org.nativescript.sassprojectangular10/files/app/bundle.js:215:125)
System.err:     at ./main.tns.ts(file:///data/data/org.nativescript.sassprojectangular10/files/app/bundle.js:281:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:816:0)
System.err:     at checkDeferredModules(file: src\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: src\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.sassprojectangular10/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err:
System.err:
System.err: TypeError: Object(...) is not a function
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module
function
System.err: TypeError: Object(...) is not a function
System.err: File: (file: node_modules\@nativescript\angular\fesm2015\nativescript-angular.js:2976:29)
System.err:
System.err: StackTrace:
System.err: (file: node_modules\@nativescript\angular\fesm2015\nativescript-angular.js:2976:29)
System.err:     at ../node_modules/@nativescript/angular/fesm2015/nativescript-angular.js(file:///data/data/org.nativescript.sassprojectangular10/files/ap
p/vendor.js:95242:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:816:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at (file:///data/data/org.nativescript.sassprojectangular10/files/app/bundle.js:215:125)
System.err:     at ./main.tns.ts(file:///data/data/org.nativescript.sassprojectangular10/files/app/bundle.js:281:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:816:0)
System.err:     at checkDeferredModules(file: src\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: src\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.sassprojectangular10/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err:
System.err:
System.err: TypeError: Object(...) is not a function
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
System.err:     at android.app.ActivityThread.access$1300(ActivityThread.java:219)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
System.err:     at android.os.Looper.loop(Looper.java:214)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: Object(...) is not a function
System.err: File: (file: node_modules\@nativescript\angular\fesm2015\nativescript-angular.js:2976:29)
System.err:
System.err: StackTrace:
System.err: (file: node_modules\@nativescript\angular\fesm2015\nativescript-angular.js:2976:29)
System.err:     at ../node_modules/@nativescript/angular/fesm2015/nativescript-angular.js(file:///data/data/org.nativescript.sassprojectangular10/files/ap
p/vendor.js:95242:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:816:0)
System.err:     at fn(file: src\webpack\bootstrap:120:0)
System.err:     at (file:///data/data/org.nativescript.sassprojectangular10/files/app/bundle.js:215:125)
System.err:     at ./main.tns.ts(file:///data/data/org.nativescript.sassprojectangular10/files/app/bundle.js:281:30)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:816:0)
System.err:     at checkDeferredModules(file: src\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: src\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.sassprojectangular10/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err:
System.err:
System.err: TypeError: Object(...) is not a function
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:674)
System.err:     at com.tns.Runtime.run(Runtime.java:666)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
System.err:     ... 8 more

**To Reproduce**

ng new -c=@nativescript/schematics sass-project-angular10 --shared --style=scss
tns run android

**Sample project**
[sass-project-angular10.zip](https://github.com/NativeScript/NativeScript/files/4936481/sass-project-angular10.zip)

**Comment by NathanWalker** [comment]
@maticbezjak `@nativescript/schematics` **~10.0.0** has now been published alongside `@nativescript/angular` **~10.0.0**

Here's a couple examples if starting fresh (which are already documented) but here for quick reference:

A. Starting a new Angular web project and adding {N} to it afterwards:

```
ng new workspace
cd workspace
ng add @nativescript/schematics --skipAutoGeneratedComponent

// start apps:
npm run ios
npm run android 
```

B. Starting a new Angular NativeScript shared codebase from the start:

```
npm i -g @nativescript/schematics
ng new -c=@nativescript/schematics workspace --shared --style=scss
cd workspace

// start apps:
npm run ios
npm run android 

```

C. If updating existing @nativescript/schematics projects:

1. Delete webpack.config.js (the updated @nativesript/webpack dependency will regenerate a new correct one using latest webpack plugins). If you had customizations, use git change sets to compare the diff.
2. Update package.json as follows (at least in part - can use as a guide):

```
"scripts": {
  "clean": "npx rimraf hooks node_modules package-lock.json platforms",
  "ng": "ng",
  "start": "ng serve",
  "build": "ng build",
  "test": "ng test",
  "lint": "ng lint",
  "e2e": "ng e2e",
  "android": "tns run android --no-hmr",
  "ios": "tns run ios --no-hmr",
  "mobile": "tns run",
  "preview": "tns preview",
  "ngcc": "ngcc --properties es2015 module main --first-only",
  "postinstall": "npm run ngcc"
},
"dependencies": {
  "@angular/animations": "~10.0.0",
  "@angular/common": "~10.0.0",
  "@angular/compiler": "~10.0.0",
  "@angular/core": "~10.0.0",
  "@angular/forms": "~10.0.0",
  "@angular/platform-browser": "~10.0.0",
  "@angular/platform-browser-dynamic": "~10.0.0",
  "@angular/router": "~10.0.0",
  "core-js": "^2.6.9",
  "@nativescript/angular": "~10.0.0",
  "@nativescript/core": "rc",
  "@nativescript/theme": "~2.2.1",
  "reflect-metadata": "~0.1.12",
  "rxjs": "~6.5.5",
  "tslib": "1.10.0",
  "zone.js": "~0.10.2"
},
"devDependencies": {
  "@angular/cli": "~10.0.0",
  "@angular/compiler-cli": "~10.0.0",
  "@angular-devkit/build-angular": "~0.1000.2",
  "@nativescript/tslint-rules": "~0.0.5",
  "@types/jasmine": "~3.5.0",
  "@types/jasminewd2": "~2.0.3",
  "@types/node": "^12.11.1",
  "codelyzer": "^5.1.2",
  "jasmine-core": "~3.5.0",
  "jasmine-spec-reporter": "~4.2.1",
  "karma": "~4.4.1",
  "karma-chrome-launcher": "~3.1.0",
  "karma-coverage-istanbul-reporter": "~2.1.0",
  "karma-jasmine": "~3.0.1",
  "karma-jasmine-html-reporter": "^1.4.2",
  "@nativescript/webpack": "~2.0.0",
  "protractor": "~5.4.3",
  "ts-node": "~8.3.0",
  "tslint": "~6.1.0",
  "typescript": "~3.9.0",
  "node-sass": "^4.7.1"
}
```

3. Clean your projects with `npm run clean` if using the clean scripts from the example scripts above.
