### ISSUE TITLE
Error when updating nativescript-angular/modal-dialog module to @nativescript/angular prefix

### ISSUE THREAD

**Issue by Meyer-dev** [NativeScript/NativeScript#8715]
ERROR in src/app/datemodal.component.ts:2:35 - error TS2307: Cannot find module '@nativescript/angular/modal-dialog' or its corresponding type declarations.

2 import { ModalDialogParams } from "@nativescript/angular/modal-dialog";
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/profile_details/profile_details.component.ts:11:56 - error TS2307: Cannot find module '@nativescript/angular/modal-dialog' or its corresponding type declarations.

11 import { ModalDialogOptions, ModalDialogService } from "@nativescript/angular/modal-dialog";
                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/datacol1/datacol1.component.ts:8:56 - error TS2307: Cannot find module '@nativescript/angular/modal-dialog' or its corresponding type declarations.

**Comment by NathanWalker** [comment]
@Meyer-dev hi! you can flatten the import - `import { ModalDialogOptions, ModalDialogService } from "@nativescript/angular";`

That's the way with Angular 9 and 10 with {N} and will be forever now 👍

**Comment by Meyer-dev** [comment]
@NathanWalker  Thanks for the help. I flattened the import and got it to work with @Nativescript/angular _rc_

**Comment by NathanWalker** [comment]
Excellent thanks for letting me know.
