### ISSUE TITLE
Video conferencing plugin

### ISSUE THREAD

**Issue by JamesPJ** [NativeScript/NativeScript#8716]
I'm using NativeScript 5.3, I'd like to know any video conferencing tool integration available for nativescript. Such as Zoom or Google Meet etc.

**Comment by NathanaelA** [comment]
@JamesPJ - Your best bet for finding plugins is to use https://plugins.nativescript.rocks or https://market.nativescript.org and do a search.   If their isn't a plugin, you can either create it or you can have another company (like us, nStudio, LLC) create you one.
