### ISSUE TITLE
[Angular 10] export declare type ViewResolver = () => ViewClass;

### ISSUE THREAD

**Issue by alexgritton** [NativeScript/NativeScript#8717]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.8.0-rc.4
 - Cross-platform modules: 7.0.0-rc.20 
 - Android Runtime: 6.5.3
 - iOS Runtime: 6.5.2
 - Plugin(s): "@nstudio/nativescript-cardview": "^1.0.0",

**Describe the bug**
I've followed the blog post upgrading to Angular 10 and ran into this issue with CardView

```
ERROR in src/app/app.module.tns.ts:80:35 - error TS2322: Type 'typeof CardView' is not assignable to type 'ViewClass'.
  Type 'CardView' is missing the following properties from type 'View': bindingContext, borderColor, borderTopColor, borderRightColor, and 224 more.

80 registerElement("CardView", () => CardView);
                                     ~~~~~~~~

  node_modules/@nativescript/angular/element-registry.d.ts:46:36
    46 export declare type ViewResolver = () => ViewClass;
                                          ~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.
```

**Additional context**
The imports in app.module.tns.ts looks like this

```
import { registerElement } from "@nativescript/angular";
import { CardView } from "@nstudio/nativescript-cardview";
registerElement("CardView", () => CardView);
```

CardView extends ContentView from tns-core-modules/ui/content-view... Do I need to install tns-core-modules along with @nativescript/core?
EDIT: ^^^ this makes things worse

**Comment by NathanWalker** [comment]
@alexgritton You can actually just drop a cast on there for now, ie:
```
registerElement("CardView", () => <any>CardView);
```
as it's just a typings warning, we'll check the typings but that'll let your build proceed,

**Comment by NathanWalker** [comment]
@nativescript/angular **~10.0.0** is now officially released which fixes the typings issue mentioned here.
