### ISSUE TITLE
[angular-10] adding nativescript-ui-sidedrawer to angular-10 project is crashing

### ISSUE THREAD

**Issue by lonemanotzi** [NativeScript/NativeScript#8723]
First of all, THANK YOU Nathan for making Angular 9 and 10 available in nativescript. We are in the process of converting an old nativescript app to Angular 10 and facing issues with ui-sidedrawer.

Steps:
1,npm i -g nativescript@rc
2.nsc create sampleapp --template @nativescript/template-hello-world-ng@rc
3. nsc run android

App is up and running on Emulator.

now add nativescript-ui-sidedrawer 
4. nsc plugin add nativescript-ui-sidedrawer
5. add NativeScriptUISideDrawerModule to AppModule (import { NativeScriptUISideDrawerModule } from "nativescript-ui-sidedrawer/angular";)
6. Add <RadSideDrawer> to  AppComponent.html
7. nsc run android

Error:
ERROR in ../node_modules/nativescript-ui-sidedrawer/angular/side-drawer-directives.js
Module not found: Error: Can't resolve 'nativescript-angular/element-registry' in 'c:\temp\sampleapp\node_modules\nativescript-ui-sidedrawer\angular'
 @ ../node_modules/nativescript-ui-sidedrawer/angular/side-drawer-directives.js 5:25-73
 @ ./app/app.module.ts
 @ ./main.ts

************
No changes where made to the ngcc.config file, it has an entry for sidedrawer as  shown below
module.exports = {
  packages: {
    "nativescript-ui-sidedrawer": {
      entryPoints: {
          angular: {
              override: {
                  main: "./side-drawer-directives.js",
                  typings: "./side-drawer-directives.d.ts"
              },
              ignoreMissingDependencies: true
          }
      },
      ignorableDeepImportMatchers: [
        /tns-core-modules\//,
        /@nativescript\/core\//,
        /@nativescript\/angular\//,
        /nativescript-angular\//,
      ]
    },......

**Comment by lonemanotzi** [comment]
Disabling Ivy by adding to tnsconfig.json results in Router error
ERROR in Error during template compile of 'AppRoutingModule'
  Function calls are not supported in decorators but 'NativeScriptRouterModule' was called.

****
{
  "compilerOptions": {
      "module": "ESNext",
      "target": "es2015",
      "experimentalDecorators": true,
      "emitDecoratorMetadata": true,
      "noEmitHelpers": true,
      "noEmitOnError": true,
      "skipLibCheck": true,
      "lib": [
        "es2018", "es2017", "dom", "es6"
      ],
      "baseUrl": ".",
      "paths": {
          "~/*": [
              "app/*"
          ]
      }
  },
  "include": [
    "references.d.ts",
    "src/tests/**/*.ts"
  ],
  "files": [
    "./src/main.ts"
  ],
  "exclude": [
      "node_modules",
      "platforms",
      "e2e"
  ],
 "angularCompilerOptions": {
	"enableIvy": false
}
}

**Comment by NathanWalker** [comment]
@lonemanotzi You can use nativescript-ui-sidedrawer `rc` version which solves the mentioned issue and keep Ivy on.

**Comment by PhilippS93** [comment]
> Function calls are not supported in decorators but 'NativeScriptRouterModule' was called.

Did you fixed the error `Function calls are not supported in decorators but 'NativeScriptRouterModule' was called.`? Having the same problem currently..
