### ISSUE TITLE
iOS build fail: Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by alexisconsuegra** [NativeScript/NativeScript#8725]
**Environment**
 - CLI: 6.5.0
 - Cross-platform modules: 6.5.10
 - Android Runtime: 6.5.0
 - iOS Runtime: 6.5.0
 - Plugin(s): nativescript-google-maps-sdk

**Describe the bug**
Unable to build locally for iOS using Xcode 10.1.0 (I can not upgrade Xcode, Mac will not support it)
Error:
Undefined symbols for architecture i386:
"___isPlatformVersionAtLeast", referenced from:
-[GMSCellularInfo SIMCountryCode] in GoogleMaps
-[GMSScreenInfo initWithUIScreen:] in GoogleMaps
-[GMSx_QTMCollectionViewController viewDidLoad] in GoogleMaps
-[GMSx_QTMCollectionViewController viewDidLayoutSubviews] in GoogleMaps
-[GMSx_QTMCollectionViewStyleController contentViewInsetsForCellWithAttribute:] in GoogleMaps
-[GMSx_QTMCollectionViewStyleController setInsetsContentViewsToSafeArea:] in GoogleMaps
-[GMSx_QTMCollectionViewStyleController insetsAtSectionIndex:] in GoogleMaps
...
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
note: Using new build systemnote: Planning buildnote: Constructing build description
** BUILD FAILED **

Command xcodebuild failed with exit code 65

**To Reproduce**
Create an app.
Add plugin nativescript-google-maps-sdk
Try to build locally Xcode 10.1.0

**Expected behavior**
Been able to build locally.

**Additional context**
Is this plugin been maintained? Can I get an older version of the plugin working with Xcode 10? Any better option?
Thanks a lot.

**Comment by NathanWalker** [comment]
@alexisconsuegra you most likely will need to drop your runtime version down - so instead of 6.5.0 you could try going down to 6.2.0 perhaps? To use an Xcode version that old will need to use older runtime.

**Comment by alexisconsuegra** [comment]
@NathanWalker Thanks for the response. Where can I find instructions to downgrade nativescript version?
