### ISSUE TITLE
[Angular 10] Can not add AppDelegate

### ISSUE THREAD

**Issue by james-criscuolo** [NativeScript/NativeScript#8727]
**Environment**
Ran `nsc create sampleapp --template @nativescript/template-hello-world-ng@rc` this morning, so should be all the latest rc versions.
```
✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.8.0-rc.4 version and is up to date.
✔ Component @nativescript/core has 7.0.0-rc.24 version and is up to date.
✔ Component tns-android has 6.5.3 version and is up to date.
✔ Component tns-ios has 6.5.2 version and is up to date.
```

**Describe the bug**

Making your own app delegate crashes while trying to use NSStringFromClass. For some reason, extending UIResponder does not return a function, but UIResponder itself is a function, so the one place where this occurs blows up:
https://github.com/NativeScript/NativeScript/blob/feat/monorepo/packages/core/application/index.ios.ts#L385
```
JavaScript error:
file: node_modules/@nativescript/core/application/index.ios.js:364:0: JS ERROR TypeError: function is not a class. (evaluating 'NSStringFromClass(iosApp.delegate)')
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: function is not a class. (evaluating 'NSStringFromClass(iosApp.delegate)')
at
NSStringFromClass(file: node_modules/@nativescript/core/application/index.ios.js:364:0)
```

**To Reproduce**

I've made a sample project here: https://github.com/james-criscuolo/nativescript7-sample
I wish I had cleanly separated my changes from the base sample, but the only code changes are in main.ts and a new file, src/app/delegate.ios.ts.
Once you pull down the repo, `npm i && tns prepare ios && tns build ios && tns run ios` (sorry, haven't flipped to nsc yet) and you should see the error.
I have a more detailed delegate for my project, but I believe the file I made should be a minimal version that works. Either way, it produces the same error.

**Sample project**
https://github.com/james-criscuolo/nativescript7-sample

**Additional context**

**Comment by NathanWalker** [comment]
Same issue as mentioned in your other ticket https://github.com/NativeScript/NativeScript/issues/8728 but we'll keep both open until we have the new decorator out as well as @nativescript/core published using higher than es5 target.

**Comment by NathanWalker** [comment]
@james-criscuolo PR'd you the goods here which serves as good example of how to work with all the latest - see description here:
https://github.com/james-criscuolo/nativescript7-sample/pull/1

**Comment by james-criscuolo** [comment]
Looks good, thanks. I'll take a look tomorrow.
