### ISSUE TITLE
[Angular 10] Issue with SBG and target: es2015

### ISSUE THREAD

**Issue by james-criscuolo** [NativeScript/NativeScript#8728]
Sorry for the unorganized bug report and no sample, but it would take a bit more work to create a demo app and I think I have some information that would be helpful. Here is my code:

```
@JavaProxy("com.onsip.OnSIP.ForegroundService")
class ForegroundService extends android.app.Service {
```

Both the old working version and new version output this code transpiled into vendor.js before the SBG comes in. The old version in vendor.js looks like:

```
var ForegroundService = /** @class */ (function (_super) {
    __extends(ForegroundService, _super);
    function ForegroundService() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
.
.
.
 ForegroundService = __decorate([
        JavaProxy("com.onsip.OnSIP.ForegroundService")
    ], ForegroundService);
    return ForegroundService;
}(android.app.Service));
```

The new code in vendor.js looks like:

```
let ForegroundService = class ForegroundService extends android.app.Service {
.
.
.
};
ForegroundService = __decorate([
    JavaProxy("com.onsip.OnSIP.ForegroundService")
], ForegroundService);
```

The new version does not find the foreground.service, so my output java folder has no com/onsip folder. Once I saw the vendor.js, I decided to shift back to target: es5, and the code now compiles and runs with the new version.

This could come down to being not a bug and more of a configuration issue, but the new blog post has a tsconfig switched to es2015, and I don't think that is currently possible for those with custom activities.

**Comment by NathanWalker** [comment]
@james-criscuolo thanks for the report, yes you're correct on your findings. During the community chat today we mentioned we're introducing a `@NativeClass` decorator which will help solve this type of issue for projects that target es2015 and higher - we'll leave this issue open until we have a blog post out with the details 👍

**Comment by james-criscuolo** [comment]
Sounds great, glad it's getting worked on. I'm happy to test once the new decorator is available or core is republished with the higher target.

**Comment by NathanWalker** [comment]
@james-criscuolo just as seen in this pr: https://github.com/james-criscuolo/nativescript7-sample/pull/1 you can decorate in same way:
```
@JavaProxy("com.onsip.OnSIP.ForegroundService")
@NativeClass
class ForegroundService extends android.app.Service {
```

Feel free to reopen if you encounter any further issue.
