### ISSUE TITLE
Nativescript image builder website is offline

### ISSUE THREAD

**Issue by derschnee68** [NativeScript/NativeScript#8737]
As mentionned in the docs,
https://docs.nativescript.org/ui/image-resources

the website that generates images for android and ios app seems down and the link expired.

http://nsimage.brosteins.com/

It would be very helpful to see it up again.
Thank you for your work

**Comment by NathanaelA** [comment]
Thanks, I have fixed the docs with: https://github.com/NativeScript/docs/pull/1905
