### ISSUE TITLE
[iOS] Layout events

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/NativeScript#8742]
**Environment**
 - CLI: 6.8.0
 - Cross-platform modules: 6.1.2
 - iOS Runtime: 6.1.0
 - Plugin(s): -

**Describe the bug**
Not sure to have the best title, but let me describe it. First of all, this happens only in iOS (works fine in android). I have multiple `AbsoluteLayout` within a `GridLayout`. But only the last one's `tap` events work (this is not just about tap event, but the other ones like the Mapbox touch events). I can see the others but can not tap on them or do anything (move the map, etc).

**To Reproduce**
```xml
<GridLayout>

  <!-- Map don't move and is not touchable when I have more layouts -->
  <Mapbox></Mapbox>

  <!-- this doesn't work either -->
  <AbsoluteLayout>
    <some-child-component></...>
  </AbsoluteLayout>

  <!-- only this one's tap events work in iOS, if I put more layout, this won't work anymore -->
  <AbsoluteLayout>
    <some-child-component></...>
  </AbsoluteLayout>

</GridLayout>
```

**Expected behavior**
Work the same way as android.

**Additional context**
The goal is to have some layouts on the map.

**Comment by mohammadrafigh** [comment]
I don't know if these are related but there is another problem like this on Android when using Mapbox. If you use `"@nativescript/core": "rc"` and `"@nativescript/angular": "10.0.0"` Mapbox just captures touch events but won't pan/scroll.

**Comment by NathanaelA** [comment]
1. Can you provide a sample application; NS-Core if possible.
2. Not sure what you mean by **Priority issue** in the title, so I removed it since it is confusing to the issue.

**Comment by vahidvdn** [comment]
Here is the demo: https://play.nativescript.org/?template=play-ng&id=1z5PND

I think I should use `DockLayout` instead of `AbsoluteLayout`. (Since there is no such thing in AbsoluteLayout: `top="100%"`. For now going to close this.
