### ISSUE TITLE
[RC] Tabs component causes app to crash

### ISSUE THREAD

**Issue by mohammadrafigh** [NativeScript/NativeScript#8747]
**Environment**
 - CLI: 6.8.0-rc.4
 - Cross-platform modules: "@nativescript/core": "7.0.0-rc.43", "@nativescript/angular": "~10.0.0", "@nativescript/webpack": "^2.1.3"
 - Android Runtime: 6.5.3
 - iOS Runtime: 6.5.1
 - Plugin(s):

**Describe the bug**
 App crashes when using Tabs component.

**To Reproduce**
Here is an example in Angular but the problem is not related to `@nativescript/angular`
```
<StackLayout>
    <FlexboxLayout>
        <Tabs class="tabs">
            <TabStrip>
                <TabStripItem title="tab 1"></TabStripItem>
                <TabStripItem title="tab 2"></TabStripItem>
            </TabStrip>

            <TabContentItem>
                <StackLayout>
                    <Label text="tab 1"></Label>
                </StackLayout>
            </TabContentItem>
            <TabContentItem>
                <StackLayout>
                    <Label text="tab 2"></Label>
                </StackLayout>
            </TabContentItem>
        </Tabs>
    </FlexboxLayout>
</StackLayout>
```
**Additional context**
I have traced the issue and found that here in [tabs.android.ts](https://github.com/NativeScript/NativeScript/blob/36aa181185cc097f5281cb113cd87aca183ee659/nativescript-core/ui/tabs/tabs.android.ts#L146) the `super()` constructor is called but the app is not able to generate native object for some reason and throws `JNI DETECTED ERROR IN APPLICATION: can't make objects of type androidx.viewpager.widget.PagerAdapter`.

As an extra suggestion ViewPager seems to be deprecated and Android docs suggest to switch to ViewPager2 at some point.

**Comment by farfromrefug** [comment]
You need to migrate to @nativescript-community/ui-material-tabs I will release a fix tomorrow

**Comment by farfromrefug** [comment]
@mohammadrafigh released `@nativescript-community/ui-material-tabs` which fixes everything

**Comment by mohammadrafigh** [comment]
@farfromrefug thanks for your suggestion I will try that. Just for more clarification, the `Tabs` component is going to be dropped in main core package?

**Comment by farfromrefug** [comment]
Not dropped but moved out into an external comp. It makes more sense and will fix issues we are having because of it being in the core.

**Comment by mohammadrafigh** [comment]
Cool thanks for clarification :+1: So I close this.
