### ISSUE TITLE
utils/utils openUrl is duplicated. Use open.

### ISSUE THREAD

**Issue by tarunama** [NativeScript/NativeScript#8749]
**Is your feature request related to a problem? Please describe.**
https://github.com/NativeScript/NativeScript/blob/bd9828a0367b30bd332070c92a5f2f921461c5a8/nativescript-core/utils/utils.ios.ts#L38
This is duplicated method.

**Describe the solution you'd like**

use this.
https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl

**Describe alternatives you've considered**

- Add testcase
- Impact to plugins

**Comment by Ross-Olivares** [comment]
Hi @tarunama 
Thank you for reporting this issue.
We are going to try replicate this case on our end. Let me know if you can send us a sample project that can reproduce the issue.

**Comment by tarunama** [comment]
So I cannot remember to this issue...
Does not share reproduction env, so close this issue.
