### ISSUE TITLE
@nativescript/core  latest rc version -  old plugins like nativescript-iqkeyboardmanager Class constructor ContentView cannot be invoked without 'new'

### ISSUE THREAD

**Issue by milansar** [NativeScript/NativeScript#8757]
**Not sure whether it is bug or question** 

**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  6.8.1-rc.1
 - Cross-platform modules: 
  "@nativescript/core": "7.0.0-rc.49",
 - Android Runtime: "6.5.3"
 - iOS Runtime:
 - Plugin(s):
"nativescript-iqkeyboardmanager": "^1.5.1",

**Describe the bug**
Trying upgrading our project on rc version of nativescript after following [ instruction](https://nativescript.org/blog/angular-10-support/)

after changing imports paths able to compile project but started hitting roadblock with plugins, for example below error with 
nativescript-iqkeyboardmanager

```
ERROR Error: Uncaught (in promise): **TypeError: Class constructor ContentView cannot be invoked without 'new'**
JS: TypeError: Class constructor ContentView cannot be invoked without 'new'
JS:     at new PreviousNextView (file: projects\trivia\src\E:\projects\rwa-trivia\node_modules\nativescript-iqkeyboardmanager\iqkeyboardmanager.js:8:0)
JS:     at ViewUtil.createView (file: projects\trivia\src\E:\projects\rwa-trivia\node_modules\@nativescript\angular\fesm2015\nativescript-angular.js:2543:0)
JS:     at EmulatedRenderer.createElement (file: projects\trivia\src\E:\projects\rwa-trivia\node_modules\@nativescript\angular\fesm2015\nativescript-angular.js:2745:0)
JS:     at EmulatedRenderer.createElement (file: projects\trivia\src\E:\projects\rwa-trivia\node_modules\@nativescript\angular\fesm2015\nativescript-angular.js:2962:0)
JS:     at elementCreate (file: projects\trivia\src\E:\projects\rwa-trivia\node_modules\@angular\core\fesm2015\core.js:7126:0)
JS:     at Module.ɵɵelementStart (file: projects\trivia\src\E:\projects\rwa-trivia\node_modules\@angular\core\fesm2015\core.js:13975:0)
JS:     at LoginComponent_Template (file: projects\trivia\src\E:\projects\rwa-trivia\projects\shared-library\src\lib\core\components\login\login.component.html:9:10)
JS:     at executeTemplate (file: projects\trivia\src\E:\projects\rwa-trivia\node_modules\@angular\core\fesm2015\core.js:7447:0)
JS:     at renderView (file:///dat...
```

upon inspecting a code , found that @nativescript/core has generated code  as es6/2015 target where nativescript-iqkeyboardmanager has generated code as es5 as shown below

**node_modules\nativescript-iqkeyboardmanager\iqkeyboardmanager.android.js**
```
Object.defineProperty(exports, "__esModule", { value: true });
var content_view_1 = require("tns-core-modules/ui/content-view");
var text_view_1 = require("tns-core-modules/ui/text-view");
var PreviousNextView = (function (_super) {
    __extends(PreviousNextView, _super);
    function PreviousNextView() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return PreviousNextView;
}(content_view_1.ContentView));
```
**node_modules\@nativescript\core\ui\content-view\index.js**

```
import { View, CustomLayoutView } from '../core/view';
import { layout } from '../../utils';
/**
 * Represents a View that has a single child - content.
 * The View itself does not have visual representation and serves as a placeholder for its content in the logical tree.
 */
export class ContentView extends CustomLayoutView {
```

**changing target to es5 in tsconfig did not help nor adding nativescript-iqkeyboardmanager into ngcc.config.js** 

**Expected behavior**
**is there any way to work with old plugins or we need to wait  for those plugin to be published and complied with new @nativescript/core and es6 as target ?**

PS:
we have similar issue with nativescript-plugin-firebase where even we had to modify few lines in plugin file as makeValidator, makeParser is no longer available ui/core/view-base and only available in ui/core/properties. i guess for that we need to file issue with  nativescript-plugin-firebase

**Comment by farfromrefug** [comment]
This is a known conséquence of N 7.0. All plugins have to be updated to be built using es2017

**Comment by NathanWalker** [comment]
Well publish an update to this plugin tonight and post back when ready for you 👍

**Comment by NathanWalker** [comment]
@milansar You can now update to this version:
```
"@nativescript/iqkeyboardmanager": "~2.0.0"
```
👍  Lemme know if any others come up you need help with.

**Comment by milansar** [comment]
@NathanWalker , Thanks a lot . Will get back if i run into issue with other plugins

**Comment by jwrascoe** [comment]
@NathanWalker 
Here are a few more... Is there a way that I can manually fix them? Or is it better to just wait till they are re-published?
nativescript-mapbox
@nstudio/nativescript-pulltorefresh
nativescript-image-zoom
nativescript-exoplayer

**Comment by jitendraashutec** [comment]
@NathanWalker  

I am also getting an error in @nstudio/nativescript-checkbox plugin. have you any plan to update this plugin ?

**Comment by Klunk75** [comment]
> @NathanWalker
> Here are a few more... Is there a way that I can manually fix them? Or is it better to just wait till they are re-published?
> nativescript-mapbox
> @nstudio/nativescript-pulltorefresh
> nativescript-image-zoom
> nativescript-exoplayer

Following...
Thanx!

**Comment by gregersen79** [comment]
I have the same issue with Nativescript-background-http and Nativescript-google-maps-sdk
