### ISSUE TITLE
absolutelayout top and left position of a view cannot be set using css

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#876]
if we set position in the xml works ok, but not with css, is this by design ?
```
<AbsoluteLayout>
    <AbsoluteLayout id="someid" top="100" width="100" height="100" backgroundColor="yellow">
    </AbsoluteLayout>
</AbsoluteLayout>
```
above works perfectly, but if we use css

```
<AbsoluteLayout>
    <AbsoluteLayout id="someid" backgroundColor="yellow">
    </AbsoluteLayout>
</AbsoluteLayout>

#someid{
  top:100;
  width:100;
  height:100;
}
```
not working

**Comment by nsndeck** [comment]
Unfortunately with the current version (1.3) and upcoming version (1.4) `top` is not a `css` definable property, therefore you cannot set it with `css`. We will consider adding properties like `top` and `left` to NativeScript css properties.

**Comment by enchev** [comment]
Implemented with https://github.com/NativeScript/NativeScript/issues/1660
