### ISSUE TITLE
Site requests feedback on pages, very annoying.

### ISSUE THREAD

**Issue by room101b** [NativeScript/NativeScript#8761]
NativeScript is great but using the website is awful. Every new page I visit asks me for feedback, and not just on the first visit. Even if I've been on a page 20 times before it asks me again for feedback. This is annoying. I've asked for you stop doing this in the feedback but ironically it appears that no one is actually reading the feedback since you still keep doing it. Popups are bad.

**Comment by NathanaelA** [comment]
@room101b - Can you provide a screen shot of what you are talking about, I just opened up a browser I never used and perused several different pages and I am not sure what you are talking about...    Also if you have a link to a page that does it, that would be helpful...

**Comment by room101b** [comment]
Hi, if you go on to any of the below pages you will get a pop up at the bottom of the page asking "Is this article helpful? Yes/No"
I have timed it and it waits exactly 30 seconds from when you load the page to pop up.

https://docs.nativescript.org/angular/start/quick-setup
https://docs.nativescript.org/angular/start/general-requirements
https://docs.nativescript.org/angular/start/cli-basics

I think this happens for every page in the contents menu on the left, and maybe others. I've included an image; the pop up is the blue strip along the bottom.

![image](https://user-images.githubusercontent.com/40149909/90379757-09e3b400-e073-11ea-8971-aabf20288a5c.png)

**Comment by NathanaelA** [comment]
Thanks for the link -- I was able to see what you are talking about...    Guess I had never noticed it before...   
I'll discuss it with the rest of the team, however getting feedback from people about the documentation quality is important, so I don't think we want to remove it, but anything is possible...  

A couple thoughts:
1.  maybe put the link on he side bar next to improve the article, instead of the popup?
2. Would a kill switch (i.e. don't ask again) that sets a cookie that makes it no longer pop up make you happy?

**Comment by room101b** [comment]
I agree that feedback is important. But, with the popup as it is if I visit a page 20 times I'm asked for feedback on that page 20 times. If over a year I make 500 visits I get asked for feedback 500 times. It is also set on a timer which prompts a user after 30 seconds, barely enough time to read anything let alone arrive at a thoughtful conclusion as to how the page could be improved. So, that would mean someone would either dismiss the popup immediately and be left with no way to provide feedback if they then had any after 1 or 2 minutes, or leave the popup in place, in a position which obscures some of the page, in expectation that they may want to offer feedback which they have not yet thought of, a lot to ask a user to do if they make several visits a day. For the above reasons, I don't thing popup even serves the function for which it is intended and simultaneously acts as an annoying, persistent prodding for something I may not even have each time a go and look for assistance.

My preference would be a passive option to provide feedback, as you suggest in point 1 above. The kill switch would rely on cookies not being wiped and if someone hit the kill switch on visit 10 but had feedback on visit 50 then they would be unable to provide it.

Please note that I am providing feedback to you and it would be the height of irony to ignore feedback because you value feedback. The fact that you did not know that this was happening on your site for over a year and were unaware of what your own site is like to use should be probably be more of a concern to you then losing feedback your not even reading (I actually put feedback in the feedback popup to say that it is annoying and it was ignored).

**Comment by rigor789** [comment]
> The fact that you did not know that this was happening on your site for over a year and were unaware of what your own site is like to use should be probably be more of a concern

@room101b we've been in charge of the site for the past 2-3 months, but have taken it over as-is, some annoying things have already been removed/improved but this feedback popup hasn't - as frankly I've never seen it pop up before... I guess my visits are less than 30 seconds :D We do value the feedback, and will address the issue. The popup is part of the page initially if you scroll down, and only pops up/sticks to the bottom after 30 seconds. I'd be happy to just remove the sticking part, and keep it at the end of the page - that way it's out of the way, but still usable when needed.

**Comment by room101b** [comment]
@rigor789 - thanks very much for listening and responding, it is much appreciated.

**Comment by rigor789** [comment]
@room101b decided to hide it for now - we'll figure out a better way and perhaps bring it back at some point (without it popping up).
