### ISSUE TITLE
iOS TextView text-color becomes black when keyboard is dismissed

### ISSUE THREAD

**Issue by felixkrautschuk** [NativeScript/NativeScript#8764]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.7.8
 - Cross-platform modules: @nativescript/core 6.5.15
 - Android Runtime: -
 - iOS Runtime: 6.5.2
 - Plugin(s): tested without plugins and with nativescript-iqkeyboardmanager 1.5.1

**Describe the bug**
When typing within the TextView component and hiding the keyboard, the TextView loses its text color (it becomes black).

I tested this without any plugins, just using the TextView and calling its _dismissSoftInput_ method:

![ios_textview_color_issue](https://user-images.githubusercontent.com/6443021/90234817-95193b80-de20-11ea-8f25-fc86832bfc14.gif)

I also tested using the iqkeyboardmanager plugin by tapping the done-button in thr keyboard (left side) and tapping outside the view using _iqKeyboard.shouldResignOnTouchOutside = true_ (right side)

![ios_textview_color_issue_iq](https://user-images.githubusercontent.com/6443021/90235005-e1647b80-de20-11ea-8bbe-81b43776c05d.gif)

But the issue occurs the same way.

It happens the same way on iOS 12 and 13 (Simulator and device).

**To Reproduce**
Just open the sample app provided below and follow the steps from the GIFs. (the uploaded sample app does not use iqkeyboardmanager plugin to keep it clean)

**Expected behavior**
Dismissing the keyboard after typing within the TextView component should not affect the text color at all.

**Sample project**
[ns-textview-color-issue.zip](https://github.com/NativeScript/NativeScript/files/5073772/ns-textview-color-issue.zip)

**Additional context**
-

**Comment by 7ammer** [comment]
Same here. This makes white on black themes or dark mode apps impossible! :(

Can anyone advise?

**Comment by 7ammer** [comment]
It seems to happen when the TextView blurs or goes out of focus.

**Comment by 7ammer** [comment]
I resorted to this work around. After blur a setTimeout will re-apply the textColor on iOS only.

```
<template>
    <TextView style="color:white" v-model="form.message" @blur="onBlur" />
</template>

<script>
export default {
    ....
    methods: {
        onBlur(args) {
            setTimeout(()=>{
                if(isIOS) args.object.ios.textColor = UIColor.whiteColor;
            }, 0);
        },
    }
}
</script>

```

**Comment by alexander-mai** [comment]
Could this also be backported to Version 6.5.x?
https://github.com/NativeScript/NativeScript/blob/tns-core-modules/nativescript-core/ui/text-view/text-view.ios.ts#L239

**Comment by louisyeoh** [comment]
Having the same issue here, is this fix?
