### ISSUE TITLE
tns preview doesn't work doe to unexpected token

### ISSUE THREAD

**Issue by cebepok13** [NativeScript/NativeScript#8765]
Webpack compilation complete. Watching for file changes.
Webpack build done!
Project successfully prepared (ios)
Start sending initial files for device iPhone.
Successfully sent initial files for device iPhone.
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at PreviewSdkService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/livesync/playground/preview-sdk-service.js:100:43)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/nativescript/lib/services/livesync/playground/preview-sdk-service.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by baldsteve** [comment]
I have the same issue. Seems to be related to the playground endpoint not being JSON. Web version of playground also experiencing issues.

**Comment by BockHornJS** [comment]
Yep same problem here and a few people on stackoverflow say the same. same position in same js file.  Hopefully they can fix the issue fast.

**Comment by BockHornJS** [comment]
I got answer from the support team. The error is known and they are working on it. Should be done by monday.

**Comment by HashirGJ8842** [comment]
Yeah i was facing the same problem. Thanks @BockHornJS for letting us know.

**Comment by beeman** [comment]
@cebepok13 thanks for creating this issue - Could you give it another try?

**Comment by cebepok13** [comment]
Works! Well done, thx.

> @cebepok13 thanks for creating this issue - Could you give it another try?

Works! Well done, thx.
