### ISSUE TITLE
I can't start the preview, I get an error and it never loads

### ISSUE THREAD

**Issue by taksumaki** [NativeScript/NativeScript#8767]
**Environment**

 - CLI: 4.27.1
 - Cross-platform modules: any
 - Android Runtime: any
 - iOS Runtime: any
 - Plugin(s): any

**Describe the bug**
I just created a project and when I use the command **"tns preview"** I get this error and it won't let me have a preview of the application.

**To Reproduce**
Use the command **"tns preview"** to show the preview of the application.

**Expected behavior**
Have a preview in the NativeScript Preview application.

**Sample project**
In all empty templates or projects

**Additional context**
Please fix it, I can't use NativeScript as I can't see the application preview.

**Image**
![1](https://user-images.githubusercontent.com/56084970/90315893-31ecdf00-dedc-11ea-9756-afe1fd8aa42f.JPG)

**Error**
```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at PreviewSdkService.<anonymous> (C:\Users\Sawako\AppData\Local\Yarn\Data\global\node_modules\nativescript\lib\services\livesync\playground\preview-sdk-service.js:100:43)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Sawako\AppData\Local\Yarn\Data\global\node_modules\nativescript\lib\services\livesync\playground\preview-sdk-service.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by rigor789** [comment]
A migration is in progress - we expect everything to be back in working order by Monday

https://github.com/NativeScript/NativeScript/issues/8765

**Comment by beeman** [comment]
@taksumaki thanks for creating this issue - Could you give it another try?

**Comment by taksumaki** [comment]
> @taksumaki thanks for creating this issue - Could you give it another try?

Now it works perfect, thanks for repairing it. Time to use NativeScript like never before!
