### ISSUE TITLE
Android navigation go back randomly go slow

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#877]
Maybe there is a leak after a while ? Or maybe the javascript or java garbage collector working in the background? Already use navigation cache it helps but still somehow random lag when go back

**Comment by x4080** [comment]
I think it related to animation somehow. After doing some animation, navigation go back is getting slower

**Comment by N3ll** [comment]
@x4080 - can you please give some more information about your project, so we can look more deeply into the problem.

**Comment by x4080** [comment]
Sure. I was using pan event to listen for movement and when panning i move the rectangle which is an absolutelayout using animation (changing x coordinate) if i move around. Then i goto another page using frame topview. And go back. The go back eventually getting slower the more i pan the box

And i don't find it happening if i move the box using native set location in android 

I don't know if this is android thing or ns thing. Maybe it could help

**Comment by vchimev** [comment]
Hi @x4080,

thanks for the informatino.

I gave a try to your scenario and did not have any issues going back to the page with animations. I tested it with NativeScript version 1.4 on Nexus 5 device running Android version 5.1.

Could you please send us a sample test app/page if you are able to reproduce the issue in a stable manner along with details about your device/emulator type and Android version?

**Comment by x4080** [comment]
Ill try it again using 1.4 and let you know thanks

**Comment by vchimev** [comment]
Looking forward to hearing from you.

Closing this one for now - to be opened if needed.
