### ISSUE TITLE
Collapsed should collapse and not occupy space

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#878]
Example... lets say the layout is like this

StackLayout
  ActivityIndicator
  ListView

So you'd set the activity indicator to show when the listview is pulling remote data right

However when it's state is *not* visible\collapsed there's a gap from top to listview where the invisible indicator is.

CSS equivalent is like visibility hidden, rather than the desired display none.

**Comment by nsndeck** [comment]
Generally `visibility="collapse"` should do the job. It should not take place in layout.
For more info you check this [help topic](http://docs.nativescript.org/ApiReference/ui/enums/Visibility/README).

I've just prepared an example:

```XML
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
    <StackLayout>
        <ActivityIndicator visibility="{{ isVisible ? 'visible' : 'collapse'}}" />
        <Button text="Click" tap="toggleVisibility" />
    </StackLayout>
</Page>
```
```JavaScript
var observable_1 = require("data/observable");
var model;
function pageLoaded(args) {
    var page = args.object;
    model = new observable_1.Observable();
    model.set("isVisible", true);
    page.bindingContext = model;
}
exports.pageLoaded = pageLoaded;
function toggleVisibility(args) {
    var isVisible = !model.get("isVisible");
    model.set("isVisible", isVisible);
}
exports.toggleVisibility = toggleVisibility;
```

And everything works like a charm. Could you please try it, and if it is not working provide me with a little bit more info about `tns` versions?

**Comment by sitefinitysteve** [comment]
OH!  No I'm sure that would work just fine...I assumed when busy="false" (and the thing hides) it would not occupy physical space.  IMO it shouldn't, that's what the "busy" flag is for right?

**Comment by enchev** [comment]
We intentionally made busy to work like this otherwise the UI will flicker
