### ISSUE TITLE
Build error :  `building for iOS Simulator, but linking in dylib built for iOS`

### ISSUE THREAD

**Issue by RilRil** [NativeScript/NativeScript#8782]
**Environment**
 - @nativescript/core:  6.5.12
 - iOS Runtime: tns-ios 6.5.2
 - xcode 12 beta 5
 - iOS 14

**Describe the bug**
I tried to build my app for simulator AND real device using `tns debug ios` with xcode beta 5 out of the box and I got this first error : 
`error: The linked framework 'Pods_<myapp>.framework' is missing one or more architectures required by this target: i386.`

then to avoid having this error I added the following to app/App_Reources/iOS/build.xcconfig:
`EXCLUDED_ARCHS = i386 armv7`

and now I am getting this error:
```
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/myapp/app/platforms/ios/internal//NativeScript.framework/NativeScript' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If i add `arm64` to the list of excluded architectures, it builds for simulator but it wont build for real device.
and in the other way if I add `x86_64` to the list of excluded archs, it will build for device but not for sim...

Can't find any config to be able to build for both simulator and real device. like it was with previous version of Xcode.

**Comment by Ross-Olivares** [comment]
Hi @RilRil 
Thank you for reporting this issue.
We are going to try replicate this case on our end. Let me know if you can send us a sample project that can reproduce the issue. Or if you can send us the generated log file:
tns run ios --log trace --justlaunch >out.txt

**Comment by Ross-Olivares** [comment]
Hi @RilRil  
Thanks for the log file, unfortunately it doesn't to provide much help. We are going to try replicating this case on our end and will confirm, let me know if you can send us a sample project or a playground link that can reproduce the issue.

**Comment by alexgritton** [comment]
@RilRil Have you found a solution for this yet? I've run into the same error today after upgrading to Xcode 12 and iOS 14.

**Comment by triniwiz** [comment]
@RilRil previously I would of used something like `VALID_ARCHS = arm64 arm64e x86_64` (`x86_64` for testing) but this was deprecated for a temp solution you can open the project in xcode after the build fails then set the min platform version to 11 (It should not complain again since from 11 the 32bit arch was dropped)

**Comment by timoschlueter** [comment]
We are also running into this problem. We updated Xcode to version 12 in order to support iOS 14. 
Building for devices seems to work, but running in the simulator (tns run ios --emulator) crashes with the same error @RilRil posted.

Running our app on an iOS 14 simulator directly through Xcode does work. Unfortunately, that does not work in our build pipeline.

Any suggestions would be highly appreciated.

**Comment by timoschlueter** [comment]
This seems to work for us for now:

We added this to the end of our App_Resources/iOS/build.xcconfig

```
EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64=arm64 arm64e armv7 armv7s armv6 armv8
EXCLUDED_ARCHS=$(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT))
```

This excludes the arm64 architecture for the simulator. Since we are developing on Intel only right now we are fine with this.
I did not come up with this myself. Found the solution over here: https://github.com/Carthage/Carthage/issues/3019#issuecomment-664099506

**Comment by RilRil** [comment]
@timoschlueter what we did was creating a .xconfig for the simulator and one for real device. That added some complexity so I will try your solution. thanks

**Comment by RilRil** [comment]
@timoschlueter it helped ! thank you !
though I had to add `EXCLUDED_ARCHS = i386 armv7` to fix my first issue

**Comment by JimLynchCodes** [comment]
Sadly, none of these worked and I am still getting the error:
```
error: Building for iOS Simulator, but the linked and embedded framework 'TNSSideDrawer.framework' was built for iOS + iOS Simulator.
```

**Comment by timoschlueter** [comment]
@JimLynchCodes this is actually a problem we also ran into a few weeks ago.

Just add _VALIDATE_WORKSPACE = YES;_ to your _App_Resources/iOS/build.xcconfig_.

Also remove the _platform_ folder and try running the app again. It should work now.

**Comment by Jogendra1234** [comment]
I have added  to VALIDATE_WORKSPACE = YES;
After this I am getting below error :
building for Mac Catalyst, but linking in dylib built for iOS Simulator, file '/Users/ACRO/Downloads/MobileApp/XRM/node_modules/@nativescript/core/platforms/ios/TNSWidgets.framework/TNSWidgets' for architecture x86_64

I'm using XCode12 . Any suggestions would be highly appreciated.

**Comment by ferleysilva** [comment]
@RilRil Thank you!!  You saved my life, I had 5 hours with this issue! and your answer was the solution 💯

**Comment by MarkKewley** [comment]
I'm receiving the same issues as @Jogendra1234

**Comment by sudiptosen** [comment]
Facing this issue on M1 - Should I really exclude `arm64` and expect it to work on M1. Please help. Many thanks

**Comment by llanoajm** [comment]
For those who encountered this error using the MapBox iOS SDK, switching to Swift Package Managers will do the trick. Installation guidelines here: [https://docs.mapbox.com/ios/maps/guides/install/](https://docs.mapbox.com/ios/maps/guides/install/)
