### ISSUE TITLE
Nativescript CLI 6.8.0 create new Angular project can't build.

### ISSUE THREAD

**Issue by alonstar** [NativeScript/NativeScript#8802]
CLI 6.8.0
macOS 10.15.5
nodeJS v12.18.2

I installed the cli @ 6.8.0 and create a new project using Angular Default Template (default is 9.1.0)
And just run "tns run ios" got errors.

How do I fix it?

> ERROR in ../node_modules/@nativescript/angular/http-client/http-utils.js
> Module not found: Error: Can't resolve '@nativescript/core/file-system/file-system' in '/Users/shelly.chen/SecurityApp/node_modules/@nativescript/angular/http-client'
>  @ ../node_modules/@nativescript/angular/http-client/http-utils.js 3:20-73
>  @ ../node_modules/@nativescript/angular/http-client/ns-http-backend.js
>  @ ../node_modules/@nativescript/angular/http-client/index.js
>  @ ../node_modules/@nativescript/angular/index.js
>  @ ./app/app.module.ts
>  @ ./main.ts
> 
> ERROR in ../node_modules/@nativescript/angular/element-registry.js
> Module not found: Error: Can't resolve '@nativescript/core/ui/border' in '/Users/shelly.chen/SecurityApp/node_modules/@nativescript/angular'
>  @ ../node_modules/@nativescript/angular/element-registry.js 141:47-86
>  @ ../node_modules/@nativescript/angular/index.js
>  @ ./app/app.module.ts
>  @ ./main.ts

the package.json file
```

{
  "nativescript": {
    "id": "org.nativescript.MyApp",
    "tns-android": {
      "version": "6.5.0"
    },
    "tns-ios": {
      "version": "6.5.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "ngcc": "ngcc --properties es2015 module main --first-only",
    "postinstall": "npm run ngcc"
  },
  "dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/forms": "~9.1.0",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
    "@nativescript/angular": "~9.0.0",
    "@nativescript/theme": "~2.3.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.5.0",
    "tns-core-modules": "~6.5.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~9.1.0",
    "@ngtools/webpack": "~9.1.0",
    "nativescript-dev-webpack": "~1.5.0",
    "tns-platform-declarations": "~6.5.0",
    "typescript": "~3.8.3"
  },
  "readme": "NativeScript Application"
}

```

**Comment by nevardreik** [comment]
There's  no `@nativescript/core` dependency in your package.json.

**Comment by pboulch** [comment]
Hi ! 
Same problem. I have been using Nativescript for two years, today my application is based on nativescript 6.5. Since the release of NativeScript 7.0 on August 31, I can no longer build the application. When I look at the package-lock.json, I realize that we forced the installation of @ nativescript / core 7.0.0 when I wanted to avoid it for the moment. I use a lot of plugins that don't support the upgrade to Nativescript 7.0.

**Comment by JeanneBertrand** [comment]
Same here, hope they fix it soon :(

**Comment by alonstar** [comment]
> There's no `@nativescript/core` dependency in your package.json.

I tried to add @nativescript/core 7.0 but still got the same error.
```

{
  "nativescript": {
    "id": "org.nativescript.SecurityToken",
    "tns-android": {
      "version": "6.5.0"
    },
    "tns-ios": {
      "version": "6.5.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "ngcc": "ngcc --properties es2015 module main --first-only",
    "postinstall": "npm run ngcc"
  },
  "dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/forms": "~9.1.0",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
    "@nativescript/angular": "~9.0.0",
    "@nativescript/core": "^7.0.0",
    "@nativescript/theme": "~2.3.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.5.0",
    "tns-core-modules": "~6.5.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~9.1.0",
    "@ngtools/webpack": "~9.1.0",
    "nativescript-dev-webpack": "~1.5.0",
    "tns-platform-declarations": "~6.5.0",
    "typescript": "~3.8.3"
  },
  "readme": "NativeScript Application"
}

```

**Comment by alonstar** [comment]
I think the path is wrong.

file-system is in @nativescript/core/file-system, not @nativescript/core/file-system/file-system

And there is no border module in @nativescript/core/ui, but I found one in tns-core-modules/ui.

**Comment by nevardreik** [comment]
> > There's no `@nativescript/core` dependency in your package.json.
> 
> I tried to add @nativescript/core 7.0 but still got the same error.

What's in your `ngcc.config.js` file? You could try adding this:

```
module.exports = {
  packages: {
    "@nativescript/angular": {
      entryPoints: {
        ".": {
          override: {
            main: "./index.js",
            typings: "./index.d.ts",
          },
          ignoreMissingDependencies: true,
        }
      },
      ignorableDeepImportMatchers: [
        /zone.js\//,
        /tns-core-modules\//,
        /@nativescript\/core\//,
      ]
    }
  }
}
```

**Comment by alonstar** [comment]
> > > There's no `@nativescript/core` dependency in your package.json.
> > 
> > 
> > I tried to add @nativescript/core 7.0 but still got the same error.
> 
> What's in your `ngcc.config.js` file? You could try adding this:
> 
> ```
> module.exports = {
>   packages: {
>     "@nativescript/angular": {
>       entryPoints: {
>         ".": {
>           override: {
>             main: "./index.js",
>             typings: "./index.d.ts",
>           },
>           ignoreMissingDependencies: true,
>         }
>       },
>       ignorableDeepImportMatchers: [
>         /zone.js\//,
>         /tns-core-modules\//,
>         /@nativescript\/core\//,
>       ]
>     }
>   }
> }
> ```

It looks like the same.  I don't change it.

```
module.exports = {
  packages: {
    "@nativescript/angular": {
      entryPoints: {
        ".": {
          override: {
            main: "./index.js",
            typings: "./index.d.ts",
          },
          ignoreMissingDependencies: true,
        }
      },
      ignorableDeepImportMatchers: [
        /tns-core-modules\//,
        /@nativescript\/core\//,
      ]
    }
  }
};
```

**Comment by rigor789** [comment]
For older projects, just make sure you have `@nativescript/core` installed, with the same version as your `tns-core-modules` dependency. In your case, add `"@nativescript/core": "~6.5.0",`

**Comment by alonstar** [comment]
> For older projects, just make sure you have `@nativescript/core` installed, with the same version as your `tns-core-modules` dependency. In your case, add `"@nativescript/core": "~6.5.0",`

Thank you. It's working. So the template project lacks @nativescript/core dependency.
