### ISSUE TITLE
UIDevice.currentDevice.name returns the device model!!

### ISSUE THREAD

**Issue by LafallaMohamed** [NativeScript/NativeScript#8805]
**Environment**

NativeScript components : 6.3.3
tns-core-modules : 6.5.15
component tns-android : 6.3.1
tns-ios : 6.5.2

**Describe the bug**
`UIDevice.currentDevice.name` is returning the device model instead of returning the device name, see below screen shots

![image](https://user-images.githubusercontent.com/17175868/91968854-da59ca80-ed47-11ea-9cb2-fab2729a1d41.png)

![image](https://user-images.githubusercontent.com/17175868/91971733-42121480-ed4c-11ea-9ef6-07a24f78635d.png)

**To Reproduce**
Just run the VS Code in debug mode and watch the below two expressions 

`UIDevice.currentDevice.name`
`UIDevice.currentDevice.model`

**Expected behavior**

`UIDevice.currentDevice.name` ----------> should return the device name instead of the model
`UIDevice.currentDevice.model` ----------> should return the device model instead of the name

**Comment by Ross-Olivares** [comment]
Hi @LafallaMohamed 
Thank you for reporting this issue.
We are going to try replicating this case on our end and will provide the needed fix. For further info, you could keep track of the issue.

**Comment by interrobrian** [comment]
I don't think this should change, if it is even able to be changed. [UIDevice](https://developer.apple.com/documentation/uikit/uidevice)  is a native iOS SDK class not controlled by NativeScript. The return values you are getting are the same you would get if you were using Swift directly against the iOS SDK. Note that Apple's documentation for [model](https://developer.apple.com/documentation/uikit/uidevice/1620044-model) gives you example results similar to what you got.

**Comment by LafallaMohamed** [comment]
@interrobrian I agree with you, problem found only in the Simulator. Physical device working well.

Issue can be closed, thanks
