### ISSUE TITLE
ActionBar->ActionItem doesn't respond to visibility binding

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#881]
This doesn't appear to do anything
```
<ActionItem icon="res://ic_star_border_white_24dp" tap="onAddFavorite" ios.position="right" android.position="right"  visibility="{{ isFavorite ? 'collapsed' : 'visible' }}" />
                <ActionItem icon="res://ic_star_white_24dp" tap="onRemoveFavorite" ios.position="right" android.position="right" visibility="{{ isFavorite ? 'visible' : 'collapsed' }}" />
```
I wanted to have a toggle for favs...2 buttons to do 1 task each and just hide\show the appropriate button.

**Comment by nsndeck** [comment]
Unfortunately for the time being there is no property `visibility` on ActionItem (it does not derive from View class).
You could try another approach use one ActionItem instead of two:

<ActionItem icon="{{ isFavorite ? 'res://ic_star_border_white_24dp' : 'res://ic_star_white_24dp' }}" tap="toggleFavorite" ...../>

Could you please give it a try and let me know how it works on your end.

**Comment by sitefinitysteve** [comment]
Okay thats fine, I can do it on one element, thanks!

**Comment by sitefinitysteve** [comment]
Hangon sorry... if it doesn't derive from view, how am I to find the element and change it's icon?  getViewById doesn't work...?

**Comment by nsndeck** [comment]
Sorry there is a problem with my comment (sample code is not visible):

```XML
<ActionItem icon="{{ isFavorite ? 'res://fav_icon' : 'res://no_fav_icon' }}" tap="toggleFavorite" />
```

**Comment by sitefinitysteve** [comment]
OH SLICK!

**Comment by mprokopowicz** [comment]
Can i use expressions with ios.systemIcon and android.systemIcon?
```
<ActionItem ios.systemIcon="{{ isScanning ? '17' : '18' }}" />
```

**Comment by KingAndroid** [comment]
Please check this this.
https://docs.nativescript.org/ui/action-bar#defining-the-actionbar
Does actionitem still not working with visibility binding?
