### ISSUE TITLE
Padding on orientation="horizontal" StackLayout clips children

### ISSUE THREAD

**Issue by delaneyb** [NativeScript/NativeScript#8810]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.7.4
 - Cross-platform modules: 6.5.15
 - Android Runtime: 6.5.3
 - iOS Runtime: 6.5.2
 - Plugin(s): NativeScript-Vue, Playground

**Describe the bug**
Children of a StackLayout with orientation="horizontal" are not moved to account for padding. The area of the children that lies inside the padding area on the left side gets clipped on android. On iOS the content is not clipped but the padding has no effect on the horizontal position of children.

**To Reproduce**
Create a StackLayout with orientation="horizontal", padding > 0 and a child Label and observe the label does not move horizontally away from the left edge of the parent as the padding increases.

**Expected behavior**
Children should be moved to fit into the padded area.

**Sample project**
https://play.nativescript.org/?template=play-vue&id=QEl2dh&v=2

**Additional context**

**Comment by Ross-Olivares** [comment]
Hi @delaneyb 
Thank you for reporting this issue.
We are going to try replicate this case on our end and will confirm. We will research what is causing this issue and will provide the needed fix. For further info, you could keep track the issue.
