### ISSUE TITLE
ns migrate deletes tsconfig.tns.json file

### ISSUE THREAD

**Issue by alexgritton** [NativeScript/NativeScript#8812]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.4

**Describe the bug**
Running ns migrate deletes the tsconfig.tns.json file. This is a problem for apps that have app.module.ts and app.module.tns.ts files. Trying to build results in errors stating "The Component 'name' is declared by more than one NgModule."

**Additional context**
Restoring the tsconfig.tns.json file resolved these issues.

**Comment by jalberto-ghub** [comment]
This is a major issue for people using shared angular projects.

**Comment by rigor789** [comment]
@jalberto-ghub the migration scripts are being worked on, but nothing prevents you from restoring the file after the migration. 

It should be in the `.migration_backup` folder.

**Comment by jalberto-ghub** [comment]
Hi @rigor789 , I understand but I was just mentioning it here. There is an additional problem that it is not clear what should be the correct content of the tsconfig files. For example, the different bits on the blogs say I should use es2017 but when I created a new project with `ns create project-name --ng` the tsconfig.json had es2015. (I was on 7.0.2 at the time).

**Comment by alexgritton** [comment]
This seems to be fixed with the latest CLI 7.0.7 release.

**Comment by Arystosedes** [comment]
@alexgritton not working in 7.0.11. https://github.com/NativeScript/NativeScript/issues/8987

**Comment by Heena-Vora** [comment]
not working with CLI 7.0.11, same error
