### ISSUE TITLE
NativeScript 7 Incompatibility

### ISSUE THREAD

**Issue by RFBennet** [NativeScript/NativeScript#8819]
I've got the tns-platform-declarations plugin as part of my typescript-based NativeScript application - so I can get intellisense within VS Code (which is extremely helpful!). I'm working on migrating my project to NativeScript 7, and the process seems to strip this plugin out of package.json. Is this plugin not compatible with NativeScript 7.0.6?

1. I migrate my project to 7.x, and do some touch up here and there
2. I execute: `npm i tns-platform-declarations --save-dev` (previous test had stripped it out; so I specifically make sure it's added **after** doing the NativeScript migration stuff)
3. I execute: `tns run ios --emulator`
4. I get this error: The current application is not compatible with NativeScript CLI 7.0.
5. I execute: `tns migrate`
6. I see that the plug-in got removed from package.json. However if I execute `tns run ios --emulator` again, I no longer get the error about the application not being compatible (I get other errors now of course)

Am I missing a step, or is there something that needs to be adjusted somewhere for compatibility with 7.x?

**Comment by rigor789** [comment]
`tns-platform-declarations` has been replaced/renamed to `@nativescript/types`

---

With the new `@nativescript/types` you can actually simplify your references.d.ts to this if you want both iOS and Android type declarations:

```ts
/// <reference path="./node_modules/@nativescript/types/index.d.ts" />
```

You can also include specific platform types as needed if you desire; for example, say you wanted different Android sdk types alongside the iOS types:
```ts
/// <reference path="./node_modules/@nativescript/types-ios/index.d.ts" />
/// <reference path="./node_modules/@nativescript/types-android/lib/android-29.d.ts" 
```
_Info from the release blog post: https://nativescript.org/blog/nativescript-7-announcement/_

**Comment by RFBennet** [comment]
Thanks for that reminder rigor789! After a fresh start today, I noticed the message when upgrading, and should have paid more attention the first time!
