### ISSUE TITLE
NativeScript nativescript-ui-dataform Module Issue 

### ISSUE THREAD

**Issue by digifost** [NativeScript/NativeScript#8820]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.2.0
 - Cross-platform modules:
 - Android Runtime: 6.5
 - iOS Runtime:
 - Plugin(s):
- nativescript-ui-dataform : 7.0.2

**Describe the bug**
I wanted to use nativescript-ui-dataform module in my angular nativescript project. But as soon as i import and run the application i am getting error as shown below:

![image](https://user-images.githubusercontent.com/69108520/92319330-61eb5600-f034-11ea-9a04-215afb4c0869.png)

and following is the snapshot of my app.module.ts
![image](https://user-images.githubusercontent.com/69108520/92319341-92cb8b00-f034-11ea-9ac7-8202e533fd10.png)

Please let me know in case i am missing anything here

**Comment by rigor789** [comment]
Please share your `package.json` contents!

**Comment by digifost** [comment]
> Please share your `package.json` contents!

{
  "nativescript": {
    "id": "org.com.nativeapplication",
    "tns-ios": {
      "version": "6.5.0"
    },
    "tns-android": {
      "version": "6.5.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/theme": "~2.3.0",
    "@nstudio/nativescript-paytm": "^1.0.0",
    "add": "^2.0.6",
    "nativescript-angular": "~8.21.0",
    "nativescript-drop-down": "^5.0.6",
    "nativescript-oauth2": "^2.4.3",
    "nativescript-ui-dataform": "^7.0.2",
    "nativescript-ui-listview": "^8.1.2",
    "nativescript-ui-sidedrawer": "^8.0.1",
    "plugin": "^0.3.3",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns": "^0.2.0",
    "tns-core-modules": "^6.5.16",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "~8.2.0",
    "nativescript-dev-webpack": "~1.5.0",
    "tns-android": "6.5.0",
    "typescript": "~3.5.3"
  },
  "gitHead": "20a65d338ae8f8911087ab6615b89363f864b07b",
  "readme": "NativeScript Application"
}

**Comment by digifost** [comment]
@rigor789 ..any update on this issue. Appreciate your help in advance.

**Comment by rigor789** [comment]
I don't see anything obviously wrong, can you share the project with me? (Can email the zip to igor@nstudio.io)

**Comment by digifost** [comment]
Hi @rigor789 , I have mailed you my source code. Thanks!

**Comment by rigor789** [comment]
@digifost the issue is that `"nativescript-ui-dataform": "^7.0.2",` is for NativeScript 7.0 that uses es2017 modules. Setting that to `"nativescript-ui-dataform": "^6.1.0",` builds the app just fine - as that is the last release before the ns7.

**Comment by digifost** [comment]
Thanks @rigor789 , now it is working fine!!...

**Comment by Salahudeen** [comment]
@rigor789 could you help me with the below issue? Please let me know if you need any additional details...

https://github.com/ProgressNS/nativescript-ui-feedback/issues/1464
