### ISSUE TITLE
[Question / Feature] Create Nativescript View from android service / native api

### ISSUE THREAD

**Issue by cheuksing** [NativeScript/NativeScript#8824]
#### Environment
tns --version 7.0.3
@nativescript/webpack ~3.0.0

#### Describe purpose
I am trying to create a cross-platform keyboard app.
The goal is to reuse all styles / gestures / input method logic.

#### Describe issue
In Android, its related to andoird.InputMethodService.onCreateInputView.
[https://developer.android.com/reference/android/inputmethodservice/InputMethodService#onCreateInputView()](url)
An android View object should be returned within the function.

If I tried to create an Nativescript View (e.g. Flexboxlayout),

```js
export const IMService = android.inputmethodservice.InputMethodService.extend(
  'org.nativescript.keyboard',
  {
    onCreateInputView: function () {
       const view = new Flexboxlayout()
       return view.android // it is undefined, on('loaded') will never be triggered
    }
  }
)
```

The problem is its nativeView can not be access until loaded.
Also, the Nativescript UI component in above example is not within the UI Tree, it will never be loaded.

#### Failed Workaround 1:
If I add it to the main activity, and then map it in onCreateInputView, the keyboard layout is shown, but
1. the Nativescript on tap events doesn't work
2. the activity can be killed, and the view will be gone
```js
  onCreateInputView: function () {
    const keyboard = app.getRootView().getViewById(keyboardID)
    const view = keyboard.android
    view.getParent().removeView(view)
    return view
  }
```

**Comment by triniwiz** [comment]
the `onloaded` will not be triggered because it was not added to the visual-tree usually if I wanted the add something to the tree I would do something like `Frame.topmost()._addView()` then you can get the native instance from `.nativeView`
