### ISSUE TITLE
[NS 7, Vue] Preview / build ignores <style> in .vue files

### ISSUE THREAD

**Issue by piter75git** [NativeScript/NativeScript#8829]
**Environment**
 - OS: MacOS 10.15.5
 - npm: 6.2.0
 - node: 10.8.0
 - CLI: 7.0.6
 - iOS Runtime: 7.0.0

"dependencies": {
    "@nativescript/core": "7.0.0",
    "@nativescript/webpack": "3.0.0",
    "@vue/devtools": "^5.3.3",
    "abortcontroller-polyfill": "^1.5.0",
    "moment": "^2.27.0",
    "nativescript-socketio": "^3.3.1",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-ui-sidedrawer": "^9.0.3",
    "nativescript-vue": "^2.6.1",
    "nativescript-vue-devtools": "^1.4.0",
    "vuex": "^3.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@nativescript/ios": "7.0.0",
    "babel-loader": "^8.1.0",
    "nativescript-dev-sass": "^1.7.0",
    "nativescript-vue-template-compiler": "^2.6.0",
    "node-sass": "^4.13.1",
    "vue-loader": "^15.9.1"
  },

**Describe the bug**
tns preview / build ignores classes in `<style lang='scss'>` in .vue files.

**To Reproduce**
`npm install -g @vue/cli @vue/cli-init`
`vue init nativescript-vue/vue-cli-template test`
`cd test`
`tns migrate --force`
`npm install`
`tns install sass`
add some styles to .vue file
`tns preview`

**Expected behavior**
Adding styles (classes) form `<style lang='scss'>` in .vue files to the application CSS.

**Comment by rigor789** [comment]
https://github.com/nativescript-vue/nativescript-vue/issues/715

**Comment by piter75git** [comment]
Thank you, @rigor789. Your solution fixed that problem.
