### ISSUE TITLE
Error on apply background-image

### ISSUE THREAD

**Issue by PabloPG** [NativeScript/NativeScript#8832]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.4.1
 - Cross-platform modules:
 - Android Runtime: 6.4.1

**Describe the bug**
After installing the android emulator for API 23, the background-image style started triggering a css error, removing the line the code works perfectly

**To Reproduce**
```
.page {
	background-image: url("~/assets/images/login-background.png");
	background-repeat: no-repeat;
	background-position: center;
	background-size: cover;
	padding: 0 25;
	color: #fff;
}
```

**Additional context**
```
JS: TypeError: css_value_1.parse is not a function
JS:  LOG  createNativeCSSValueArray(file: node_modules\@nativescript\core\ui\styling\background.android.js:158:0)
JS:     at refreshBorderDrawable(file: node_modules\@nativescript\core\ui\styling\background.android.js:119:0)
JS:     at onBackgroundOrBorderPropertyChanged(file: node_modules\@nativescript\core\ui\styling\background.android.js:62:0)
JS:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View._redrawNativeBackground(file: node_modules\@nativescript\core\ui\core\view\view.android.js:777:0)
JS:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.<computed>(file: node_modules\@nativescript\core\ui\core\view\view.android.js:757:0)
JS:     at applyAllNativeSetters(file: node_modules\@nativescript\core\ui\core\properties\properties.js:1065:0)
JS:     at initNativeView(file: node_modules\@nativescript\core\ui\core\properties\properties.js:992:0)
JS:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onResumeNativeUpdates(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:647:0)
JS:     at push.../node_mo...
JS:  LOG  com.tns.NativeScriptException: Calling js method onCreateView failed
JS: TypeError: css_value_1.parse is not a function
```

**Comment by Ross-Olivares** [comment]
Hi @PabloPG 
Thank you for reporting this issue.
We are going to try replicate this case on our end and will confirm. However, sometimes setting up background-image for some of the available Layouts do come up with error. Meanwhile can you try using the inline css and let us know how it goes.
<StackLayout backgroundImage="~/images/myImage.jpeg" >
    -------
    -------
 </StackLayout>

Let me know if you can send us a sample project or playground link so we can dig this further.

**Comment by PabloPG** [comment]
Hello @Ross-Olivares, 
after using the command `npm rebuild node-sass` the error stopped

Thankz
