### ISSUE TITLE
NativeScript 7 cannot import platform module

### ISSUE THREAD

**Issue by nicmanzini** [NativeScript/NativeScript#8850]
**Environment**
✔ Component nativescript has 7.0.8 version and is up to date.
✔ Component @nativescript/core has 7.0.3 version and is up to date.
✔ Component @nativescript/ios has 7.0.0 version and is up to date.

**Describe the bug**
in nativeScript 6.x.x I could do in my vue based project

**import {screen} from "platform"**

in NativeScript 7 I tried without success to import the same library. I also tried to import it as per the doc

const platformModule = require("tns-core-modules/platform")

and also those ways

import platform from '@nativescript/core'

import screen from '@nativescript/core/platform'
import platform from '@nativescript/plateform'
import {screen] from '@nativescript/platform'
import {screen}  from "@nativescript/core/platform"

and in the code:
const width = screen.mainScreen.widthDIPs

**none works. I get
Uncaught TypeError: Cannot read property 'mainScreen' of undefined**

**To Reproduce**
just try to import and use the lib.
**Expected behavior**
I expect to not have undefined imported element.

`<script>

 import {screen}  from "@nativescript/core/platform"
 import moment from 'moment'

    export default {
        name: "NewsBigCell",
        components: {
        },
        props: {
            item: Object,
            onTap: Function,
        },
        data() {
            return {
            }
        },
        computed: {
            date() {
                let m = moment(this.item.date)
                return m.format('Do MMMM YYYY')
            },
            image() {
                const image = this.item.images[0]
                if (image) {
                    return image.uri.list
                }
            },
            imageHeight() {
                const width = screen.mainScreen.widthDIPs
                console.log('width has been calculated to: '+ width);
                return  width*0.5625
            },
        },
        methods: {
        },
    }
</script>`

**Comment by nicmanzini** [comment]
I found out. notice **Screen** with a capital Letter.

**import {Screen}  from "@nativescript/core/platform"**

then in the code:

const width = Screen.mainScreen.widthDIPs

**Comment by rigor789** [comment]
@nicmanzini you can also do `import {Screen} from "@nativescript/core"`.

In fact, it's recommended to import everything from `@nativescript/core` since we may want to move things around in the future (unlikely in this case, just in general).
