### ISSUE TITLE
NS 708 iOS Apps might quit unexpectedly on launch

### ISSUE THREAD

**Issue by ngocnt1** [NativeScript/NativeScript#8854]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.8
 - Cross-platform modules:7.0.3
 - Android Runtime:7.0.0
 - iOS Runtime:7.0.0
 - Plugin(s):
    "@angular/animations": "~10.1.0",
    "@angular/common": "~10.1.0",
    "@angular/compiler": "~10.1.0",
    "@angular/core": "~10.1.0",
    "@angular/forms": "~10.1.0",
    "@angular/platform-browser": "~10.1.0",
    "@angular/platform-browser-dynamic": "~10.1.0",
    "@angular/router": "~10.1.0",
    "@nativescript/angular": "~10.1.0",
    "@nativescript/core": "~7.0.3",
    "@nativescript/fingerprint-auth": "^7.0.0",
    "@nativescript/firebase": "^11.0.0-rc.7",
    "@nativescript/theme": "^2.5.0",
    "@ngx-translate/core": "^13.0.0",
    "moment": "^2.27.0",
    "nativescript-ui-calendar": "^7.0.2",
    "nativescript-ui-chart": "^8.0.2",
    "nativescript-ui-dataform": "^7.0.2",
    "nativescript-ui-sidedrawer": "^9.0.3",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.6.0",
    "zone.js": "~0.11.1"

**Describe the bug**
Due to known issue with ios 14 sdk: https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-release-notes/
"Apps using the NativeScript framework might quit unexpectedly on launch. NativeScript performs an unsafe operation to determine if an arbitrary pointer is an Objective-C object pointer. You can temporarily resolve this issue by using object_getClass(_:) instead of reading the isa directly; however, update this code to avoid checking whether arbitrary pointers are Objective-C object pointers. (62913064)"

**To Reproduce**
Build app with **ns build ios --release** 
Note: It works if without --release

**Expected behavior**
App should not quit unexpectedly on launch

**Comment by alexgritton** [comment]
This issue was only a problem for the JSC and it was solved already in tns-ios@6.5.2. The 7.0 release uses the v8 engine which didn't have these issues so you should be fine.
