### ISSUE TITLE
Java Bindings not working

### ISSUE THREAD

**Issue by ragu89** [NativeScript/NativeScript#8855]
We are using a native Android library developed by img.ly, [PhotoEditorSDK](https://github.com/imgly/pesdk-android-demo).

This native library allow us to open an image editor. The SDK provides a static property `ALLOW_SYSTEM_EMOJI` in the class `ly.img.android.pesdk.backend.layer.TextGlLayer`. This is a flag to enable a feature, the usage of emojis when writing a text.

The feature has been tested natively (Kotlin and Java), it's working as expected.

Apparently, there is an issue with the Java Binings, because there is no impacts when we set this flag to `true` in NativeScript.

[Expected behaviour](https://drive.google.com/file/d/1nIfRUGf4aWwp8VktrB0HbARnBfDAY7OU/view?usp=sharing).
[Current behaviour](https://drive.google.com/file/d/10VipDA4pxIehhqUIwrCJ_Hc-37DFFxoU/view?usp=sharing).

You can reproduce the issue with [the demo app](https://github.com/NativeScript/NativeScript/files/5233138/ns7-pesdk-emoji.zip), the logic is in the class `items.component.ts`.

To ensure the native SDK is working as expected, you can remove the generated directory `platforms/android/app/build `and update manually the file `platforms/android/app/src/main/java/com/tns/NativeScriptApplication.java` by adding at the top of the class :
```
    static {
        ly.img.android.pesdk.backend.layer.TextGlLayer.ALLOW_SYSTEM_EMOJI = true;
    }
```
This will make the app working as expected and this is how the [Expected behaviour](https://drive.google.com/file/d/1nIfRUGf4aWwp8VktrB0HbARnBfDAY7OU/view?usp=sharing) has been recorded. 

That's why we think about a binding issue.
To consolidate this intuition, the initial value of the flag is 'undefined'. It should be 'false'.

The procedure to run the example:
- [Download the archive](https://github.com/NativeScript/NativeScript/files/5233138/ns7-pesdk-emoji.zip) and unzip
- $ npm i
- $ ns run android
N.B.1: The first execution of the app doesn't work, you have to accept the usage of the medias and start the app again.

The procedure to create the demo app is also simple in case you need:
- $ npm i -g nativescript@latest
- $ ns create ns7-pesdk-emoji (-> Angular -> Hello World)
- Add LICENSE file in App_Resources/Android/src/main/assets
- Update files items.component.ts, items.component.html
- Update/create files App_Resources/Android/app.gradle and App_Resources/Android/buildscript.gradle
- Add file typings/imgly-androidlib.d.ts and update references.d.ts
- $ ns run android
N.B.2: The license is a trial license (30 days), you can generate a new one from the img.ly website https://docs.photoeditorsdk.com/guides/android/v7_6/introduction/getting_started

The demo app attached has been created with NativeScript 7.0.8.
The issue is also there with NativeScript 6.

**Comment by NathanaelA** [comment]
I can't say anything about this issue and why it is occurring yet --  however just to let you know if you have a plugin you can drop a java file into the platforms/android/src folder and it will be compiled and built into the app so that you don't have to modify any files in your app.    

One question, is it possible that you are initializing the photo framework  before the static value is being set; because if the static value is set after their framework reads it -- it might be too late...

**Comment by ragu89** [comment]
Good question, but I tried to put at several places without any effects. In native android, it's working at this place.

I tried to put Java files in platforms/android/src of my plugins but it doesn't work. I can't even find them in the platforms/ directory of my demo app.

![custom-java-files](https://user-images.githubusercontent.com/1267845/93472842-86c5b000-f8f5-11ea-9073-e3d1aec17316.png)

Am I doing something wrong?

**Comment by NathanaelA** [comment]
Yeah, that won't work.    There are two places this can be depending on if it is a plugin or your app:

1. If it is a plugin then: `src/platforms/android/java/` assuming src is the root of your plugin code.
2. If it is a APP, then `App_Resources/Android/src/main/java/` 

If you still all your .java files into that directory they will be automatically merged into your app.

**Comment by ragu89** [comment]
it's a plugin. When I put a simple Java class in `src/platforms/android/java/` I get the error message:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/XXX/my-workspace/myplugin/demo-angular/platforms/tempPlugin/myplugin/build.gradle' line: 104

* What went wrong:
Could not compile build file '/Users/XXX/my-workspace/myplugin/demo-angular/platforms/tempPlugin/myplugin/build.gradle'.
> startup failed:
  build file '/Users/XXX/my-workspace/myplugin/demo-angular/platforms/tempPlugin/myplugin/build.gradle': 104: expecting EOF, found ':' @ line 104, column 13.
     apply plugin: 'com.android.application'
                 ^
  
  1 error
```

Something is missing?

**Comment by NathanaelA** [comment]
So the primary issue is that the the `ALLOW_SYSTEM_EMOJI` is not be exposed to the metadata correctly from the PESDK library.   NativeScript has no knowledge of it -- so when you assign it; it just assigned a local JS variable, not any underlying java object value.    

So their are a couple ways to solve this; the easiest is this method
- Create a file inside your `App_Resources/Android/src/main/java` folder (you probably will have to create the java folder) called `pesdk.java`.   
![image](https://user-images.githubusercontent.com/850871/94866683-6a516980-0405-11eb-8982-ea26919681c2.png)

This file contains this:
```
package io.nstudio;

public class pesdk {
    public static void setEmoji(boolean value) {
        ly.img.android.pesdk.backend.layer.TextGlLayer.ALLOW_SYSTEM_EMOJI = value;
    }
 }
```

Then in your code here:
Add this code before you call the `startActivityForResult()`
`io.nstudio.pesdk.setEmoji(true);`

![image](https://user-images.githubusercontent.com/850871/94866991-f5cafa80-0405-11eb-9e2f-9228a54e0f65.png)
