### ISSUE TITLE
Some plugins I was using doesnt compatible with version 7 cuz they have dependences on tns-core-modules.

### ISSUE THREAD

**Issue by huyaxiong** [NativeScript/NativeScript#8857]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  7.0.8
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime: 7.0.0
 - Plugin(s): nativescript-carousel & nativescript-htmllabel

**Describe the bug**

**To Reproduce**
After I migrated to version 7.0 and installed all the dependencies and try to run the project with the command `tns debug ios --force`, some plugins threw errors. (I have installed tns-core-modules again after I migrated to v 7.0)

![image](https://user-images.githubusercontent.com/6245250/93472035-b7720d80-f926-11ea-91b4-a4a4abc03fa6.png)
![image](https://user-images.githubusercontent.com/6245250/93472070-c789ed00-f926-11ea-9813-0830bdd43320.png)
![image](https://user-images.githubusercontent.com/6245250/93472114-d2448200-f926-11ea-9898-0f1403cdd239.png)

**In my main.js**

![image](https://user-images.githubusercontent.com/6245250/93472169-e25c6180-f926-11ea-944e-2f395009e0d9.png)

**Expected behavior**
run it normally without any errors like old version 6

**Sample project**

**Additional context**
I just want my old plugins could still work in version 7, and I dont think I could find any replacement for the plugins I am using, but also I have to upgrate to version 7 cuz old version 6 seems doesnt support ios 14, so is there any solutions or workaround pls let me know, thanks a lot!

**Comment by ineiti** [comment]
you can try to use the `alias` variable in `webpack.config.js` and direct to the new definitions.

**Comment by farfromrefug** [comment]
@huyaxiong `nativescript-label` has been moved to `@nativescript-community/ui-label` for N 7

**Comment by NathanaelA** [comment]
Multiple plugins have been updated for NS7, You can check @nativescript/* , @nativescript-community/* and @proplugins/* if you see any plugin in those three namespaces they should work with NativeScript 7 (You can use https://plugins.nativescript.rocks to see recently updated plugins and do searches for plugins)

In addition the tns-ios 6.5.2 engine has the iOS 14 fixes and works with iOS 14, so if you want to stay on NS6, you can use the 6.5.2 engine for iOS 14 compatibility.

**Comment by huyaxiong** [comment]
> Multiple plugins have been updated for NS7, You can check @nativescript/* , @nativescript-community/* and @proplugins/* if you see any plugin in those three namespaces they should work with NativeScript 7 (You can use https://plugins.nativescript.rocks to see recently updated plugins and do searches for plugins)
> 
> In addition the tns-ios 6.5.2 engine has the iOS 14 fixes and works with iOS 14, so if you want to stay on NS6, you can use the 6.5.2 engine for iOS 14 compatibility.

https://github.com/NativeScript/NativeScript/issues/8866 I am facing this issue when I use the 6.5.2 engine.
