### ISSUE TITLE
nativescript-inappbrowser plugin crashes app after NS7 & Angular 10 upgrade System.err: TypeError: Class constructor Observable cannot be invoked without 'new'

### ISSUE THREAD

**Issue by aquinn637** [NativeScript/NativeScript#8865]
I have an app written with NS7 and Angular 10. Here is the sample code: https://github.com/aquinn637/NS7InAppBrowser

I am using this plugin to open a browser.

When I run the command `ns run android` I get this error:

```
Gradle build...
         + setting applicationId
         + applying user-defined configuration from /Users/aubrey/Documents/GitHub/NS7InAppBrowser/App_Resources/Android/app.gradle
         + using android X library androidx.legacy:legacy-support-v4:1.0.0
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: /Users/aubrey/Documents/GitHub/NS7InAppBrowser/node_modules/@nativescript/core/platforms/android/widgets-release.aar
         + adding aar plugin dependency: /Users/aubrey/Documents/GitHub/NS7InAppBrowser/node_modules/nativescript-inappbrowser/platforms/android/nativescript_inappbrowser.aar
Project successfully built.
The build result is located at: /Users/aubrey/Documents/GitHub/NS7InAppBrowser/platforms/android/app/build/outputs/apk/debug/app-debug.apk
Installing on device 2cccaac838017ece...
Successfully installed on device with identifier '2cccaac838017ece'.
Restarting application on device 2cccaac838017ece...
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Class constructor Observable cannot be invoked without 'new'
System.err: File: (file: node_modules/nativescript-inappbrowser/ChromeTabsManagerActivity.js:8:0)
System.err: 
System.err: StackTrace: 
System.err: ChromeTabsEvent(file: node_modules/nativescript-inappbrowser/ChromeTabsManagerActivity.js:8:0)
System.err: 	at (file: node_modules/nativescript-inappbrowser/ChromeTabsManagerActivity.js:13:0)
System.err: 	at ../node_modules/nativescript-inappbrowser/ChromeTabsManagerActivity.js(file:///data/data/org.nativescript.NS7InAppBrowser/files/app/vendor.js:152874:30)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:816:0)
System.err: 	at fn(file: src/webpack/bootstrap:120:0)
System.err: 	at (file: node_modules/nativescript-inappbrowser/InAppBrowser.android.js:12:34)
System.err: 	at ../node_modules/nativescript-inappbrowser/InAppBrowser.js(file:///data/data/org.nativescript.NS7InAppBrowser/files/app/vendor.js:153115:30)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:816:0)
System.err: 	at fn(file: src/webpack/bootstrap:120:0)
System.err: 	at ./app/item/items.component.ts(file: src/app/item/items.component.ts:1:0)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:816:0)
System.err: 	at fn(file: src/webpack/bootstrap:120:0)
System.err: 	at ./app/app-routing.module.ts(file: src/app/app-routing.module.ts:1:0)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:816:0)
System.err: 	at fn(file: src/webpack/bootstrap:120:0)
System.err: 	at ./app/app.module.ts(file: src/app/app.module.ts:1:0)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:816:0)
System.err: 	at fn(file: src/webpack/bootstrap:120:0)
System.err: 	at (file:///data/data/org.nativescript.NS7InAppBrowser/files/app/bundle.js:305:73)
System.err: 	at ./main.ts(file:///data/data/org.nativescript.NS7InAppBrowser/files/app/bundle.js:371:30)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:816:0)
System.err: 	at checkDeferredModules(file: src/webpack/bootstrap:43:0)
System.err: 	at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
System.err: 	at (file:///data/data/org.nativescript.NS7InAppBrowser/files/app/bundle.js:2:57)
System.err: 	at require(:1:266)
System.err: 
System.err: 
System.err: TypeError: Class constructor Observable cannot be invoked without 'new'
```

**Comment by Ross-Olivares** [comment]
Hi @aquinn637 ,
Thank you for reporting this issue. We will try to replicate the case on our end locally.
Meanwhile, could try to follow the below-attached steps and to verify, whether the problem will exist after the changes.

1) delete node_modules, platforms, hooks folders from the project.
2) clean npm cache with npm cache clean
3) delete the project from the simulator
4) build it again with tns run android

**Comment by ray007** [comment]
Have there been any substantial changes to `Observable`?
I'm having the same problem, and the `nativescript-inappbrowser` plugin is not the only one with this error.

**Comment by NathanaelA** [comment]
Yeah, this is a bug in the InAppBrowser; the author has already fixed it in v3.0

**Comment by bugMaker-237** [comment]
> Yeah, this is a bug in the InAppBrowser; the author has already fixed it in v3.0
> 
> I should probably mention, because we are using ES6 output some things that the JS engines let slide in the past don't work as the engines are now running by default in strict mode.
> So trying to create a class without a "new" now fails... `Class constructor Observable cannot be invoked without 'new'`

Hello ran into the same issue, but unfortunately v3.0 is not published on npm

> Yeah, this is a bug in the InAppBrowser; the author has already fixed it in v3.0
> 
> I should probably mention, because we are using ES6 output some things that the JS engines let slide in the past don't work as the engines are now running by default in strict mode.
> So trying to create a class without a "new" now fails... `Class constructor Observable cannot be invoked without 'new'`

But v3.0 is not availabe!?

**Comment by rgill02** [comment]
I'm running into this problem on other plugins. Can someone point me to an example of old code that is making this fail (producing the "cannot be invoked without new" error) and the updated code that fixes it?

**Comment by ray007** [comment]
@rgill02 afaics the transpile target needs to be `es6` or better, otherwise things fail.
I think nativescript is using `es2017`, so best go with that.

**Comment by codealvarez** [comment]
Install the new version: 
`npm i n7-google-places-autocomplete`

And make the import like this:
`import { GooglePlacesAutocomplete } from "n7-google-places-autocomplete";`
