### ISSUE TITLE
[(ngModel)] not working after page navigation

### ISSUE THREAD

**Issue by Nerdsofsweden** [NativeScript/NativeScript#8870]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.2
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime: 14.0
 - Plugin(s):

**Describe the bug**
After page navigation two way binding stops working on TextField.

**To Reproduce**
1. ns create test --ng
2. import { NativeScriptFormsModule } from "@nativescript/angular"; in app.module.ts
3. Remove contet of items.component.html and add <TextField hint="write here" [(ngModel)]="name"></Textfield><Label [text]="name"></Label>
5. Add custom link <Label [nsRouterLink]="['/item', 1]" text="link"><Label>
4. Add name: string = ""; to items.component.ts
5. Do step 3 and 4 in item-detail.component.html and item-detail.ts. 
6. Add custom link <Label [nsRouterLink]="['/items']" text="link"><Label>

**Expected behavior**
Label text should match users input. This works on first page but not on second detail page. If I change start route to detail page it works there but not navigating to items page.

**Sample project**
--ng list/detail app

**Additional context**
iOs 14 and Xcode 12-beta, iphone 7 plus

**Comment by NathanWalker** [comment]
Thanks for tracking @Nerdsofsweden , we anticipate a fix on this early this week. This was a change with Ivy and the way the lifecycle and node handling was done which affected iOS since it resulted in delegates being lost (thus bindings not working).

**Comment by NathanWalker** [comment]
@Nerdsofsweden Fixed with @nativescript/angular 10.1.4 published now 👍
