### ISSUE TITLE
[iOs] White gap between two frames on the same page

### ISSUE THREAD

**Issue by piter75git** [NativeScript/NativeScript#8873]
**Environment**
CLI: 7.0.8
node: 10.8
simulator (iOs): iPhone 11 (13.6)
"@nativescript/core": "7.0.0",
"nativescript-vue": "^2.6.1",
"@nativescript/webpack": "^3.0.1-rc.0",
"node-sass": "^4.13.1",

**Describe the bug**
Based on the:
https://nativescripting.com/posts/multiple-frames-in-nativescript

When I create two frames on the same page, I can see a white gap between them on iOs.

**To Reproduce**
https://play.nativescript.org/?template=play-vue&id=aNeGcj&v=11

**Expected behavior**
No gap between frames on iOs.

**Sample project**
https://play.nativescript.org/?template=play-vue&id=aNeGcj&v=11

**Additional context**
 It can be related to the iPhone safe area.

**Comment by akhlthmz** [comment]
I am also having the same problem. Any solution ?

**Comment by rigor789** [comment]
@akhlthmz post your code, and a screenshot of the issue, can't help without any context.
