### ISSUE TITLE
[NS7] Snapshot flag is not working in Android production build of initial project

### ISSUE THREAD

**Issue by mohammadrafigh** [NativeScript/NativeScript#8875]
**Environment**
 - CLI: 7.0.8
 - Android Runtime: 7.0.0

**Describe the bug**
When trying to build with compiled snapshot using `ns build android --release --env.snapshot --env.compileSnapshot --env.uglify --keyStorePath <KEYSTORE> --keyStorePassword <PASSWORD> --keyStoreAlias <ALIAS> --keyStoreAliasPassword <PASSWORD> --aab`

This exception happens: 

```
ERROR in snapshot-entry.js from Terser
Unexpected token string «"); e.code = », expected punc «)» [snapshot-entry.js:156,96]
    at ee (/test-project/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:19541)
    at c (/test-project/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:28244)
    at l (/test-project/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:28335)
    at p (/test-project/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:28475)
    at _ (/test-project/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:28587)
    at D (/test-project/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:28913)
    at /test-project/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:32314
    at /test-project/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:32430
    at /test-project/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:28976
    at N (/test-project/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1:38503)

```

**To Reproduce**
- Initialize a new project
- Run the command mentioned above

**Comment by vforv** [comment]
Try --env.snapshotInDocker

**Comment by farfromrefug** [comment]
I can confirm I have the same issue. And actually it is not N 7 related but CLI related.
On a 6.x project with CLI 7.x you get this error
Now rollback to CLI 6.x and the project builds normally.

**Comment by NathanaelA** [comment]
Please note Snapshots have been depreciated for a while; and not even tested (to my knowledge) under NS7...     Second, the error is occurring from terser, so it **might** work if you don't pass the `--env.uglify` variable.

**Comment by farfromrefug** [comment]
What if he you want to uglify? Where has it been said it is deprecated? What is it replaced with? Code caching does not replace it. Snapshot is about cold runtime and makes a huge difference in user experience.

**Comment by farfromrefug** [comment]
@rigor789 managed to make it work. There are a lot of issues making snaphsot not work.
Now the issue related to this terser issue come from a change in the cli
https://github.com/NativeScript/nativescript-cli/commit/9641bea992e05978dbb64d28dc7d60bf14ea2f76
`~/package.json` was added as external. This is what creates that error.
Maybe it could be added only if `env.snapshot` is false?

To finish on the snapshot building on N 7 there are 2 more issues
https://github.com/NativeScript/NativeScript/pull/8889
https://github.com/NativeScript/NativeScript/pull/8890

**Comment by bufke** [comment]
The notice here is not clear to me https://docs.nativescript.org/core-concepts/android-runtime/advanced-topics/v8-heap-snapshots

> The recommended approach for using V8 Heap Snapshot feature in the context of NativeScript is via nativescript-dev-webpack 

It's also mentioned [in the building with webpack docs](https://docs.nativescript.org/performance-optimizations/bundling-with-webpack) and mentions using --env.snapshot

Should we no longer be using `--env.snapshot`? Or is it just broken at this time?

**Comment by NathanaelA** [comment]
@bufke - Snapshots were supposed to be gone as of NS 7.0; but we totally forgot to put that in the release notes.   Code-Cache is the way forward.       See https://github.com/NativeScript/NativeScript/issues/8926

**Comment by mohammadrafigh** [comment]
Ok so with code-cache as a replacement I think we can close this issue, thank you @NathanaelA for clarification.
