### ISSUE TITLE
*ngFor on Android renders first item as last item (the rest are in proper order)

### ISSUE THREAD

**Issue by crowmagnumb** [NativeScript/NativeScript#8878]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

```
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.0.8 version and is up to date.
✔ Component @nativescript/core has 7.0.3 version and is up to date.
✔ Component @nativescript/ios has 7.0.0 version and is up to date.
✔ Component @nativescript/android has 7.0.0 version and is up to date.
```

**Describe the bug**

When rendering for example ...
```
items = ["1", "2", "3", "4"];
<Label *ngFor="let item of items" [text]="item"></Label>
```
It will render 2, then 3, then 4, then 1. But on Android only. Works fine on iOS.

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by NathanWalker** [comment]
@crowmagnumb what nativescript/angular version?

**Comment by crowmagnumb** [comment]
Ah, yes, didn't notice that `tns info` did not give that. Sorry. `@nativescript/angular@10.1.4`

**Comment by NathanWalker** [comment]
Ok nice thanks - this pr may fix that https://github.com/NativeScript/nativescript-angular/pull/2262 - bout to be merged and released.

**Comment by NathanWalker** [comment]
@crowmagnumb 10.1.5 was just published, could you clean project and try with that when get a chance?

**Comment by crowmagnumb** [comment]
That did it!

**Comment by NathanWalker** [comment]
Hooray! Thanks for confirming 🤗
