### ISSUE TITLE
Back button on Android doesn't work since 1.3

### ISSUE THREAD

**Issue by maknz** [NativeScript/NativeScript#888]
We specify a `<NavigationButton />` in our action bars so that we can have a back button in the top bar on Android, but also so we can modify its style cross platform, which works really well:

```
  if (page.actionBar.navigationButton) {
    page.actionBar.navigationButton.text = "";
    page.actionBar.navigationButton.icon = "res://ic_arrow_back";
  }
```

This worked great on iOS and Android on 1.2, but broke for Android in 1.3.

On Android, the button appears at the right times and is styled correctly, but it doesn't work. Tapping it does the right "pressed" state animation and stuff, but it doesn't go back. It works fine on iOS on 1.3 as it did on 1.2, this is just an Android problem.

**Comment by bradmartin** [comment]
I've noticed when declaring in the .xml that text doesn't work on some Android devices, the icon does work fine though.

**Comment by hamorphis** [comment]
In previous versions we did not have a navigation button on Android. If there was a button on the screen, it was not ours -- it was coming from somewhere else. In 1.3 we introduced the actionBar abstraction and now the button is ours. You will need to attach to its tap event do the thing you need to do. Here is some sample code:
```
  <Page.actionBar>
    <ActionBar title="{{ title }}" icon="{{ mainIcon }}">
      <NavigationButton text="{{ navText }}" icon="{{ navIcon }}" tap="{{ navTap }}"/>
      <ActionBar.actionItems>
        <ActionItem text="{{ firstItemText }}" tap="{{ firstItemTap }}"  ios.position="left"/>
        <ActionItem icon="{{ secondItemIcon }}" tap="{{ secondItemTap }}" ios.position="right"/>
      </ActionBar.actionItems>
    </ActionBar>
  </Page.actionBar>
```

**Comment by hamorphis** [comment]
And some examples: https://docs.nativescript.org/ApiReference/ui/action-bar/HOW-TO

**Comment by bradmartin** [comment]
@hamorphis - is it a bug or by design that the "text" for <NavigationButton> is not visible on Android? I know the default Android navigation button is an icon/image and not text. So in your sample code above is that why you declare the text and icon so it works on both platforms?

If that is the design then it might be worth adding something in the docs to explain that to prevent others from filing issues.

**Comment by hamorphis** [comment]
From the docs: *The icon can only be set in Android platform. Following the design guides it is automatically hidden in Lollipop versions (API level >= 20). You explicitly control its visibility with the `android.iconVisibility' property.*
