### ISSUE TITLE
Upgrading to NS7 gives errors while building on Android

### ISSUE THREAD

**Issue by ubaidazad** [NativeScript/NativeScript#8883]
**Environment**
 ```ns info```
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.0.8 version and is up to date.
✔ Component @nativescript/core has 7.0.3 version and is up to date.
✖ Component @nativescript/ios is not installed.
✔ Component @nativescript/android has 7.0.0 version and is up to date.

**Describe the bug**
While building the app on android ```ns run android``` gives error
```
ERROR in ./main.ts 40:9
Module parse failed: Identifier 'isAndroid' has already been declared (40:9)
File was processed with these loaders:
 * ../node_modules/@nativescript/webpack/helpers/android-app-components-loader.js
 * ../node_modules/@nativescript/webpack/bundle-config-loader.js
 * ../node_modules/@nativescript/webpack/helpers/moduleid-compat-loader.js
 * ../node_modules/@nativescript/webpack/helpers/lazy-ngmodule-hot-loader.js
 * ../node_modules/@ngtools/webpack/src/index.js
You may need an additional loader to handle the result of these loaders.
| import { registerElement } from "@nativescript/angular";
| import { MapView } from 'nativescript-google-maps-sdk';
> import { isAndroid } from "@nativescript/core";
| var options_Generated = {};
| 
```

**To Reproduce**
add these imports and run the app using NS7
```
 import { isAndroid } from "@nativescript/core";
```

**Expected behavior**
app should run successfully on android as it is using NS6

**Sample project**

**Additional context**
Upgrading project to NS6 TO NS7

**Comment by rigor789** [comment]
You can remove the import - it's now globally available. I don't know why it throws an error though, either way should work.

**Comment by farfromrefug** [comment]
@rigor789 this is why it gets the error then? Because it is defined globally. But I thought it only worked as `global.isAndroid`, does simple use of  `isAndroid` should work too?

**Comment by ubaidazad** [comment]
Thanks working as `global.isAndroid` defined in webpack config.

**Comment by tomtastico** [comment]
Visual Studio complains if it's not imported, seems it doesn't know it's a global? If imported, VS is happy but the build fails as explained in this issue. 

![image](https://user-images.githubusercontent.com/690217/97030181-bbfd9780-155e-11eb-8668-bb4f2995659e.png)


Any tips on how to solve it so VS is happy too?

I tried `declare var isAndroid: boolean;` in `main.ts` but it makes the build fail for iOS.

**Comment by tomtastico** [comment]
@farfromrefug it works for me when imported except in `main.ts`. In any other file it works, in `main.ts` I have to use `global.isAndroid`.
