### ISSUE TITLE
iOS 14: DatePicker does not set dates

### ISSUE THREAD

**Issue by grey280** [NativeScript/NativeScript#8885]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.8
 - Cross-platform modules: 7.0.4
 - Android Runtime: N/A
 - iOS Runtime: 7.0.0
 - Plugin(s): @nativescript/angular@10.1.5

**Describe the bug**
At runtime, attempting to either two-way bind to `date` or bind to `dateChanged` does not work. Instead of emitting a `Date`, the result emits `undefined`, and prints `ERROR TypeError: value.getFullYear is not a function` to the debugger.

**To Reproduce**
1. Create a component with a DatePicker in it.
2. Create a two-way binding to a `Date` variable (i.e., in .component.ts, have `public myDate: Date = new Date();`, and in .component.html. `<DatePicker [(date)]="myDate"></DatePicker>`)
3. Run the app, and edit the date.

Alternately, manually bind to it:
2. Create a manual binding to the `Date` variable (i.e. `<DatePicker [date]="myDate" (dateChange)="myDate = $event"></DatePicker>`)
3. Run the app, and edit the date.

**Expected behavior**
The `myDate` property should be updated with the new date the user selected.

**Sample project**
I've created [a playground](https://play.nativescript.org/?template=play-ng&id=es4lhG&v=2), but haven't tested it, as the companion iOS app hasn't been updated to NativeScript 7 and crashes on launch on iOS 14.

**Comment by asharghi** [comment]
It's working for me. Instead of 

`<DatePicker [date]="myDate" (dateChange)="myDate = $event"></DatePicker>`

you have to do:

`<DatePicker [date]="myDate" (dateChange)="myDate = $event.value"></DatePicker>`
