### ISSUE TITLE
npm install runs again first time while building app, even when packages are already installed using yarn

### ISSUE THREAD

**Issue by ubaidazad** [NativeScript/NativeScript#8891]
**Environment**
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.0.8 version and is up to date.
⚠ Update available for component @nativescript/core. Your current version is 7.0.3 and the latest available version is 7.0.5.
✖ Component @nativescript/ios is not installed.
✔ Component @nativescript/android has 7.0.0 version and is up to date.

**Describe the bug**
`npm install` runs again first time even packages are already installed using yarn.

**To Reproduce**

- `yarn install`
- `ns run android`
npm install runs automatically first time after this the build is started.

**Expected behavior**
App should start building without running `npm install` again.

**Comment by NathanaelA** [comment]
This is normal behavior to make sure that all dependencies are correct.
