### ISSUE TITLE
Bug in nativescript-webview-interface for ns 7

### ISSUE THREAD

**Issue by janivargundersen** [NativeScript/NativeScript#8894]
The bug is inside the file index.android.js and is at line 78.
The platformModule,device,sdkVersion is wrong.

After new statndard in ns 7 the inlcude must be changed:
const platformModule = require("platform");
to somthing likst
import { Device } from "@nativescript/core";
And change the code accoringly. The line with the error is in bold.

/**
     * Executes event/command/jsFunction in webView.
     */
    WebViewInterface.prototype._executeJS = function(strJSFunction){
      **if (platformModule.device.sdkVersion >= 19) {**
        this.webView.android.evaluateJavascript(strJSFunction, null);
      }
      else {
        this.webView.android.loadUrl('javascript:'+strJSFunction);
      }
    };

**Comment by rigor789** [comment]
Please open the issue in the plugin's repo: https://github.com/shripalsoni04/nativescript-webview-interface
