### ISSUE TITLE
IOS 14 Crash issue

### ISSUE THREAD

**Issue by avesaravanan** [NativeScript/NativeScript#8897]
The App is crashing in IOS 14
running
 "tns-ios": {
 "version": "6.5.1"
 }
does not work with iOS 14.
Running it in XCode 12 showed the error in main.m
[runtime executeModule:@"./"];
 Thread 1: EXC_BAD_ACCESS

**Comment by NathanaelA** [comment]
You need to use the 6.5.2 iOS engine.

**Comment by avesaravanan** [comment]
Thank you, your advise resolve the issue
