### ISSUE TITLE
Badge property for TabStripItem in BottomNavigation

### ISSUE THREAD

**Issue by tdhman** [NativeScript/NativeScript#8901]
**Is your feature request related to a problem? Please describe.**
Hello,

I recently use the component `BottomNavigation` for my application and try to add a badge icon to the tabbar items but this component only allows to add 1 Label + 1 Image in `TabStripItem` component. When I try to add a custom layout, e.g. StackLayout, in order to add another Label to create a badge icon, the custom layout is not displayed. There is no way to add a 3rd component inside the tabstripitem?

```
<TabStripItem class="navigation__item">
   <StackLayout>
       <Label text="Home" />
       <Label text="10" class="badge-icon" />
   </StackLayout>
    <Image src.decode="font://&#xe021;" class="fas t-36"></Image>
</TabStripItem>
```

For iOS, this component uses UITabController which has a `badge` property in order to show a badge count. So I think it's possible to support this feature in the component `BottomNavigation` itself.
I have tried the following code to show the badge with the `BottomNavigation` component and it works.

```
<BottomNavigation id="bottomTabNav">
<!-- TODO  -->
</BottomNavigation>

bottomTabNav.ios.tabBar.items[0].badgeValue = '10 '; // show the badge on tab item
```

However, for Android, I don't found anyway to add a badge count.

**Describe the solution you'd like**
For example, we can add a `badge` property directly to the component the `TabStripItem`:

```
<TabStripItem class="navigation__item" badge="10">
    <Label text="Home"></Label>
    <Image src.decode="font://&#xe021;" class="fas t-36"></Image>
</TabStripItem>
```
Is there any plan to add the `badge` feature for the component `BottomNavigation`?

**Describe alternatives you've considered**
For iOS, we can badge value directly with the code:
```
bottomTabNav.ios.tabBar.items[0].badgeValue = '10 '; // show the badge on tab item
```
For android, is it possible to add badge with code?

![IMG_0263](https://user-images.githubusercontent.com/420003/94259305-8bf6b080-ff2e-11ea-9b75-983cc1cf3a2c.PNG)

Thank you for any help.

**Comment by Ross-Olivares** [comment]
Hi @tdhman  
Thank you for reporting this issue.
We are going to try replicate this case on our end and will provide the needed fix. For further info, you could keep track the issue.

**Comment by Ross-Olivares** [comment]
Hi @tdhman 
Can you try using Nativescript-plugin-badge 
https://market.nativescript.org/plugins/nativescript-plugin-badge/
It uses ShortcutBadger control for android and it should work fine.
Let me know how it goes.

**Comment by tdhman** [comment]
@Ross-Olivares Thanks a lot for the suggestion Ross. However, I want to add badge on the NativeScript BottomTabNavigation component, not the notification badge on the application icon.

**Comment by DimitrisRK** [comment]
@tdhman It seems that it won't be easy to do this on BottomNavigation, even natively.
Since you need this feature, I suggest that you try a plugin like this one:
https://www.npmjs.com/package/@nativescript-community/ui-material-bottomnavigationbar

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
