### ISSUE TITLE
[iOS] NS7 Error in openFile

### ISSUE THREAD

**Issue by BlueHunter99** [NativeScript/NativeScript#8913]
**Environment**
 - CLI: 7.0.9-rc.1
 - @nativescript/core: 7.0.7
 - iOS Runtime: 7.0.0
 - Plugin(s): none

**Describe the bug**
When trying to open a file using `openFile` on iOS the error `Error in openFile` is thrown. When I add additional logging to `@nativescript/core/utils/index.ios.js` that gives the following error: `TypeError: _native_helper__WEBPACK_IMPORTED_MODULE_0__.iOSNativeHelper.UIDocumentInteractionControllerDelegateImpl is not a constructor`. 

This did work previously, and as far as I can see there have been no changes between NS6.5 and NS7 in this code. Could this be related to the switch from ES5 to ES2017+?

**To Reproduce**
1. `git clone https://github.com/BlueHunter99/barebones-getfile-bug`
2. `ns run ios`
3. Press 'Download file' button

**Expected behavior**
File should download and show the preview.

**Comment by rigor789** [comment]
@NathanWalker isn't this something you and @bradmartin encountered in one of the plugins? Exporting the `@NativeClass` directly? https://github.com/NativeScript/NativeScript/blob/020ad4da37f551e934cd6054ca983ab5083a4042/packages/core/utils/native-helper.ios.ts#L130-L151

**Comment by bradmartin** [comment]
Yes. I don't know if @NathanWalker had time to document it on the plugin update stuff or not but this being in core, looks like we'll need to init it before it's used or export it out of the file for use (several ways to solve it).

**Comment by NathanWalker** [comment]
@BlueHunter99 Thank you for reporting this, greatly appreciated. Fix is published under @NativeScript/core "rc" tag now if you want to use right now (specifically under 7.0.8-rc.0).
We'll probably publish in a patch on Tuesday or Wednesday along with some others.

**Comment by BlueHunter99** [comment]
@NathanWalker I might be blind, but 7.0.8-rc.0 does not seem to be published yet. The only recently published version is 7.0.9-unit.0 and that doesn't contain the changes.

**Comment by NathanWalker** [comment]
@BlueHunter99 it's published official in `7.0.8` now. Let us know if you have any further trouble.

**Comment by BlueHunter99** [comment]
Can confirm it is fixed now, thanks a lot guys.
