### ISSUE TITLE
androidx.fragment.app.SuperNotCalledException in playstore

### ISSUE THREAD

**Issue by karsie** [NativeScript/NativeScript#8918]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.5.3
 - Cross-platform modules: 6.5.13
 - Android Runtime: 6.5.3
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
In the playstore we see a crash with the following (obfuscated) stacktrace:
androidx.fragment.app.SuperNotCalledException: 
  at androidx.fragment.app.Fragment.Hxj (Fragment.java:11702784)
  at androidx.fragment.app.Fragment.performPause (Fragment.java)
...
This could very well be caused due to the incorrect callback method in frament.android.ts (onStop instead of onPause)

**To Reproduce**
No idea

**Expected behavior**
No stacktrace

**Sample project**

**Additional context**

**Comment by farfromrefug** [comment]
@karsie created https://github.com/NativeScript/NativeScript/pull/8919
THanks
