### ISSUE TITLE
iOS 12 iPhone 6 crashes after migrate project to nativescript 7, terminated due to taking too long to start up

### ISSUE THREAD

**Issue by syahnur197** [NativeScript/NativeScript#8924]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

dependencies
```json
"dependencies": {
    "@nativescript/background-http": "^5.0.0",
    "@nativescript/camera": "^5.0.0",
    "@nativescript/core": "~7.0.0",
    // this was taken from Nathanwalker repo
    "@nativescript/datetimepicker": "file:nativescript-datetimepicker-2.0.2.tgz", 
    "@nativescript/firebase": "^11.0.0",
    "@nativescript/imagepicker": "^1.0.0",
    "@nativescript/theme": "^3.0.0",
    "@nstudio/nativescript-cardview": "^2.0.0",
    "@nstudio/nativescript-checkbox": "^2.0.0",
    "font-awesome": "^4.7.0",
    "intl": "^1.2.5",
    "js-base64": "^3.5.2",
    "nativescript-barcodescanner": "^4.0.1",
    "nativescript-clipboard": "^2.0.0",
    "nativescript-downloader": "^2.1.4",
    // this was taken from Nathanwalker repo
    "nativescript-inappbrowser": "file:nativescript-inappbrowser-3.0.0.tgz",  
    "nativescript-iqkeyboardmanager": "^1.4.0",
    "nativescript-openfile": "0.0.12",
    "nativescript-permissions": "^1.3.6",
    "nativescript-phone": "^2.0.0",
    "nativescript-rater": "^2.1.1",
    "nativescript-socket.io": "^0.11.1",
    "nativescript-statusbar": "^5.0.0",
    "nativescript-theme-core": "^2.0.24",
    "nativescript-ui-autocomplete": "7.0.2",
    "nativescript-vue": "^2.8.1",
    // this was taken from PhilippS93 repo
    "nativescript-windowed-modal": "file:nativescript-windowed-modal-6.2.8.tgz", 
    "vue-moment": "^4.0.0",
    "vuex": "^3.1.3"
},
"devDependencies": {
    "@babel/core": "^7.9.6",
    "@babel/preset-env": "^7.11.5",
    "@nativescript/android": "7.0.0",
    "@nativescript/ios": "7.0.0",
    "@nativescript/webpack": "~3.0.0",
    "babel-loader": "^8.1.0",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-vue-template-compiler": "^2.8.1",
    "node-sass": "^4.9.2",
    "vue-loader": "^15.9.1"
},
```
```
ns version: 7.0.9-rc.2
npm version: 6.14.4
node version: 13.12.0
xcode version: 12
```

**Describe the bug**
I migrated my app from NS 6 to NS 7 a week ago. The problem that I am having right now is that my app got terminated when I am using iOS 12 on iPhone 6 since the app launches more than 20 second. I have no issue here when I am using iOS14 on iPhone X, the app launches in 8 seconds on average. Previously, before I upgrade the app, it took less than 20 second and the app is running fine. 

To give you a detail about my production app:-
- Developed using nativescript-vie
- Has like 200 vue files 
- Has around 150 pages
- Has 30 JS files for mixins and some classes
- Navigation is done using this.$navigateTo
- Has route files with 150 pages imports, while exporting two route objects. The objects will then be used for navigation purposes, which I will explain more in detail later.

Steps I have taken and still not resolve my issue
- run `ns run ios --env.uglify`
- Tried to use profiler, but the timeline is not showing

Some context, I cannot use --env.snapshot and --env.aot since I am using nativescript-vue and the issue is in iOS

What I also have done:
- `ns create` new project
- bringing some files from the original project to the new project bit by bit
- I noticed that as the files in the new project grows, the time taken for the app to startup also increases, when I have like 30 vue files or so, it takes around 7 second to startup, as I gradually bring my files from previous project to the new project, the app takes more time to startup

Now to explain the route file, in the file, I have two objects holding the pages for the app to navigate to

route.js
``` javascript
import Home from '@/components/home/Home';
import Home2 from '@/components/home/Home2';
import Home3 from '@/components/home/Home3';
import Home4 from '@/components/home/Home4';
import Home5 from '@/components/home/Home5';

export const routes = {
    Home: Home,
    Home2: Home2,
    Home3: Home3,
    Home4: Home4,
    Home5: Home5,
}
```

Then I import this file in my main.js file and also other vue files when I need to navigate to other page

main.js
``` javascript
import { navRoutes } from "@/routes";

new Vue({
    render: h => h(
        'frame',
        [h(navRoutes.Home)]
    )
})
.$start();

```

**To Reproduce**
You need a ns7 project with a lot of vue files, with tons of lines of codes in the vue file, to the point the app size is 100 MB in the app store.

**Expected behavior**
App to launch less than 20 second and not terminated. I also need some suggestions and recommendations on how can I fix this issue temporarily and able to support iOS 14, iOS 13, and iOS 12

**Additional context**
In my previous issue, I though the reason why it was taking too long to launch the app is because the app is looking for Sensor.Kit in older iOS version. But since I removed barcode scanner, the warning message is no longer showing so I think SensorKit is not the issue here.

**Comment by NathanaelA** [comment]
Closing because we are already discussing this is #8920
