### ISSUE TITLE
[NativeScript 7 - Angular 10] nativescript-ui-sidedrawer crashes with files not found and reference path error

### ISSUE THREAD

**Issue by phenric** [NativeScript/NativeScript#8932]
Hello everyone!

I really enjoy and appreciate all the works you do to develop and maintain a technology like NativeScript and how you integrate Angular.
During the upgrade to NS7 & NG10, I encounter some issues. I would be grateful if you could have a look and explain me what's wrong with my config. :-)

**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.10
 - Cross-platform modules: 7.0.10
 - Android Runtime: 7.0.0
 - iOS Runtime: 7.0.1
 - nativescript-ui-sidedrawer: 9.0.0-rc.3

**Describe the bug**

After upgrading to Angular 10 and Nativescript 7, I have multiple errors as this one:

```
node_modules/nativescript-ui-sidedrawer/references.d.ts:5:22 - error TS6053: File '/Users/Documents/Project/Applications/node_modules/nativescript-ui-sidedrawer/node_modules/nativescript-ui-core/android.d.ts' not found.

5 /// <reference path="./node_modules/nativescript-ui-core/android.d.ts" />
```

**To Reproduce**

Migrate Nativescript to 7 and Angular to 10.

**Additional context**

I saw many solution such as @NathanWalker from here -> https://github.com/aquinn637/Angular9SideDrawer/pull/1#issue-489052106

I also tried with IVY and with ngcc.config.js as described here -> 
https://github.com/NativeScript/nativescript-angular/wiki/Updating-and-developing-for-@nativescript-angular-v9-with-Ivy-or-without#solution-1

**Comment by NathanWalker** [comment]
Hi @phenric update to the latest version:
nativescript-ui-sidedrawer: ~9.0.3

Then ‘ns clean’ and run again.

If you have further trouble please share your tsconfig and package.

**Comment by phenric** [comment]
Hi @NathanWalker,

Thank you for the reply.

I still have the issues even with nativescript-ui-sidedrawer: ~9.0.3.
You will find my package and my tsconfig below as asked:

**package**
```
{
  "scripts": {
    "clean": "npx rimraf hooks node_modules package-lock.json platforms",
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "android": "tns run android --no-hmr",
    "ios": "tns run ios --no-hmr",
    "mobile": "tns run",
    "preview": "tns preview",
    "ngcc": "ngcc --properties es2015 module main --first-only",
    "postinstall": "npm run ngcc"
  },
  "dependencies": {
    "@angular/animations": "~10.1.4",
    "@angular/common": "~10.1.4",
    "@angular/compiler": "~10.1.4",
    "@angular/core": "~10.1.4",
    "@angular/forms": "~10.1.4",
    "@angular/platform-browser": "~10.1.4",
    "@angular/platform-browser-dynamic": "~10.1.4",
    "@angular/router": "~10.1.4",
    "@types/node": "~14.11.2",
    "lodash": "~4.17.11",
    "nativescript-geolocation": "5.1.0",
    "nativescript-localize": "4.2.2",
    "nativescript-phone": "^2.0.0",
    "@nstudio/nativescript-snackbar": "^2.0.2",
    "nativescript-socket.io": "^0.11.1",
    "nativescript-theme-core": "~2.0.24",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-tslib": "~1.9.1-r1",
    "nativescript-ui-listview": "9.0.2",
    "nativescript-ui-sidedrawer": "~9.0.3",
    "reflect-metadata": "~0.1.13",
    "reinstall": "^2.0.0",
    "rxjs": "~6.6.3",
    "rxjs-compat": "^6.6.3",
    "zone.js": "~0.11.1",
    "core-js": "^3.6.5",
    "@nativescript/angular": "10.0.0",
    "@nativescript/core": "7.0.10",
    "@nativescript/theme": "3.0.0",
    "tslib": "2.0.1",
    "@nativescript/webpack": "3.0.5"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1001.3",
    "@angular/cli": "~10.1.4",
    "@angular/compiler-cli": "~10.1.4",
    "@nativescript/android": "7.0.0",
    "@nativescript/ios": "7.0.1",
    "@nativescript/schematics": "~10.1.0",
    "@nativescript/tslint-rules": "~0.0.5",
    "@nativescript/types": "~7.0.0",
    "@ngtools/webpack": "^10.1.4",
    "@types/jasmine": "~3.5.14",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "^14.11.2",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~6.0.0",
    "karma": "~5.2.3",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.3",
    "karma-jasmine": "~3.0.3",
    "karma-jasmine-html-reporter": "^1.5.4",
    "node-sass": "^4.14.1",
    "protractor": "~7.0.0",
    "ts-node": "~9.0.0",
    "tslint": "~6.1.3",
    "typescript": "~3.9.0"
  },
  "main": "main.js"
}
```

**tsconfig**

```
{
    "compilerOptions": {
        "module": "esnext",
        "target": "es2017",
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "lib": [
            "es6",
            "dom",
            "es2015.iterable",
            "es2017"
        ],
        "baseUrl": ".",
        "paths": {
            "~/*": [
                "src/*"
            ],
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        },
        "removeComments": false
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
}
```

**Comment by NathanWalker** [comment]
You’re using a bunch of legacy plugins (non {N} 7). See this and update to proper scoped name and version:
https://nativescript.org/blog/nativescript-7-compatible-plugins/

Also update @nativescript/angular to latest ~10.1.0

After doing that give another ns clean. If still trouble I can post package you’d want tomorrow.

**Comment by phenric** [comment]
I'll finish the update of the nativescript-ui-sidedrawer module tomorrow.
Thank you for your time :-)

**Comment by phenric** [comment]
The issue is quite obvious at the end. Inside the references.d.ts within the nativescript-ui-sidedrawer's module I had to manually correct the paths to that ones.

```
/// <reference path="./../@nativescript/core/global-types.d.ts" />
/// <reference path="./../@nativescript/types/index.d.ts" />
/// <reference path="./../nativescript-ui-core/ios.d.ts" />
/// <reference path="./../nativescript-ui-core/android.d.ts" />
/// <reference path="./android.d.ts" />
/// <reference path="./ios.d.ts" />
```
Is there a better way? For each clean and modules reinstallation I have to change those paths.

I've also realized I used the localize module (nativescript-localize) for {N}6 and lower. I changed it to @nativescript/localize.
However, I still have issues when running the app on simulator:

> /App_Resources/iOS/Info.plist' doesn't exists: unable to set default language

> An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
> Failed to install the requested application
> The application's Info.plist does not contain CFBundleVersion.
> Ensure your bundle contains a CFBundleVersion.

Based on the Localize's documentation, I tried to add this line "ios.info.plist.CFBundleVersion": "1.0.0" inside a local.json which didn't work.

Any idea where I misconfigured my app?

**Comment by valera1401** [comment]
Try to add "skipLibCheck": true to the "compilerOptions" of the tsconfig.json

**Comment by etelvinacunha** [comment]
Hi @phenric , 

we are having the same problem, can you describe what you did to overcome the issue?

thanks in advance
Etelvina

**Comment by phenric** [comment]
Hi @etelvinacunha,

I'm sorry for the delay.
Do you still have the mistake? What's the exact message?

After changing the paths as I described above, I realized my App_Ressources was misconfigured. I just reloaded an old one.
