### ISSUE TITLE
Nativescript 7 clearTimeout issue [ios only]

### ISSUE THREAD

**Issue by kryptus36** [NativeScript/NativeScript#8933]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 

7.0.8

 - Cross-platform modules:

7.0.10

 - Android Runtime:

N/A

 - iOS Runtime:

7.0.1

 - Plugin(s):

nativescript-mqtt: 1.2.0

**Describe the bug**

I'm filing this as a supplement to edusperoni/nativescript-mqtt#14 as it seems like the proper fix  may be in core.

The use of clearTimeout in this plugin is causing a crash which says "clearTimeout is not a function".

setTimeout does not have the same issue. It also works fine on Android in NS7 and worked in both in NS6.

**To Reproduce**
Use this plugin as you normally would.

**Expected behavior**
mqtt goodness & no crash

**Comment by eltharynd** [comment]
First I'd suggesti updating your cli to 7.0.10 as well with `npm install -g nativescript`
And let us know if that fixes it

**Comment by kryptus36** [comment]
Thanks for the reply. I just tried it now, same result. I've been digging to try to get more info, but no luck yet.

**Comment by eltharynd** [comment]
I remember having a similar weird issue that was ultimately due to a scope error after typescript compiled to js in my case.. 
Maybe this can help you..
Unfortunately without looking at the code I can't be too sure..
I'll try creating a sample project tomorrow and see if I can help

**Comment by NathanaelA** [comment]
@kryptus36 - I tested `setTimeout`/`clearTimeout` in a NS Core app on NS 7 and it is working properly.   

However, a issue we did have with a earlier version of TS & NS was that the globals was being registered after some other things were being registered.  (i.e. setTimeout/clearTimeout are a global).     Can you try upgrading to the latest NS CLI and replacing your webpack.config file with the latest version here: https://github.com/NativeScript/NativeScript/tree/master/packages/webpack/templates   (Grab whatever flavor you are using and rename it to the `webpack.config.js`

**Comment by kryptus36** [comment]
I am going to close this issue. At some point it seems to have resolved itself. Unfortunately I don't know exactly what caused it to stop.

The plugin in question still isn't working for me in ns7, but I am no longer able to reproduce this specific error. Baby steps.

Thanks everyone for your ideas and feedback.
