### ISSUE TITLE
Application crashing after splash screen on iOS 14 

### ISSUE THREAD

**Issue by HakikatGPCoders** [NativeScript/NativeScript#8935]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.8
 - Cross-platform modules: 6.5.8
 - Android Runtime: 6.5.1
 - iOS Runtime: 6.5.1

**Describe the bug**
I am using RadSideDrawer in my application and its working fine in previous iOS versions. But after recent update of iOS 14 my application started to crash after splash screen.

**Crash  Report from XCode:**
nativeapp[3742:118699] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Error
 at 
UIApplicationMain(file:///app/vendor.js:93058:30)
at run(file:///app/vendor.js:93058:30)
at file:///app/vendor.js:87304:26
at file:///app/vendor.js:87205:38
at file:///app/vendor.js:87185:26
at file:///app/bundle.js:2661:144
at ./main.ts(file:///app/bundle.js:2666:34)
at __webpack_require__(file:///app/runtime.js:817:34)
at checkDeferredModules(file:///app/runtime.js:44:42)
at webpackJsonpCallback(file:///app/runtime.js:31:39)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
', reason: '(null)'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3de6e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff512a19b2 objc_exception_throw + 48
	2   NativeScript                        0x000000010934856f _ZN12NativeScript30reportFatalErrorBeforeShutdownEPN3JSC9ExecStateEPNS0_9ExceptionEb + 1631
	3   NativeScript                        0x0000000109399f94 -[TNSRuntime executeModule:referredBy:] + 660
	4   nativeapp                           0x0000000107bffe73 main + 179
	5   libdyld.dylib                       0x00007fff5211c1fd start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Crash at line :**
UIApplicationMain(0, null, null, iosApp && iosApp.delegate ? NSStringFromClass(iosApp.delegate) : NSStringFromClass(Responder));

**Comment by rigor789** [comment]
Please use the search functionality and look for existing issues before opening a new one, this particular issue has been solved months ago, and there are a few different issues where the fix is posted:
https://github.com/NativeScript/NativeScript/issues/8916#issuecomment-700635542
https://github.com/NativeScript/NativeScript/issues/8665#issuecomment-696372407
... (and a few more)

**Comment by HakikatGPCoders** [comment]
I have tried all the possible solutions and still same crash.

**Comment by rigor789** [comment]
> all the possible solutions

Perhaps list the things you tried to avoid us suggesting the same steps!

**Comment by boldham31** [comment]
This is a known issue that the NativeScript team is currently working on. For now, here is the best workaround that I have seen. I am currently in the process of working through it - I will update with my progress in putting together a temporary solution.

https://stackoverflow.com/questions/64136571/nativescript-playground-app-on-ios-14-0-18a373-crash-directly-after-start

**Comment by kranthi-kiki** [comment]
can you try by updating nativescript to  7.0.9-rc.2 version

**Comment by eltharynd** [comment]
You can update to 7.0.10 and that should fix that (and you will have to update further to actually publish on the app store as soon as next update is available or follow #8937)

**Comment by NathanWalker** [comment]
Playground and Preview Updates are now available:
https://twitter.com/NativeScript/status/1325994280003891200
