### ISSUE TITLE
Not able to load the local images after updating to NS7

### ISSUE THREAD

**Issue by shivasaicharan** [NativeScript/NativeScript#8936]
Not able to load the images from the local folder after updating to NS7.
```
<StackLayout row="0" class="nt-drawer__header">
            <Image class="nt-drawer__header-image fas t-36" src="~/images/logo.png"></Image>
            <Label class="nt-drawer__header-brand" text="User Name"></Label>
            <Label class="nt-drawer__header-footnote" text="username@mail.com"></Label>
</StackLayout>
```
<img width="258" alt="Screenshot 2020-10-05 at 5 46 39 PM" src="https://user-images.githubusercontent.com/46471584/95078787-507c9300-0733-11eb-9069-0faebfecd51d.png">

**Comment by ozgursel** [comment]
i have same problem after upgrading.. also on IOS "loadSync" attribute not working with <Image/> tags

**Comment by kranthi-kiki** [comment]
need to include image folder in copyTargets in webpack 

{ from: 'images/**', noErrorOnMissing: true, globOptions: { dot: false, ...copyIgnore } }
