### ISSUE TITLE
TimePicker: Selecting 12am time doesn't work

### ISSUE THREAD

**Issue by nevendyulgerov** [NativeScript/NativeScript#8941]
**Environment**
 - CLI: 6.5.1
 - Android Runtime: 29
 - Plugin(s): None

**Describe the bug**
When setting time like `12:07 AM` (equal to `00:07` in 24h format) the timepicker displays an incorrect time. Also it displays `PM` instead of `AM`.

**To Reproduce**
Just test the following in `yyyy-MM-dd hh:mm aa` format:

```javascript
<TimePicker :time="new Date('2020-10-06 12:07 AM')" />
```
or using format `yyyy-MM-dd HH:mm`

```javascript
<TimePicker :time="new Date('2020-10-06 00:07')" />
```

**Expected behavior**
The timepicker should be set to `12:07 AM`:
![timepicker-expected-result](https://user-images.githubusercontent.com/6005179/95189970-48762f00-07d7-11eb-9300-9d98cded9421.PNG)

**Actual behavior**
The timepicker is set to `01:07 PM`:
![timepicker-actual-result](https://user-images.githubusercontent.com/6005179/95189785-fe8d4900-07d6-11eb-82eb-1d2b7d08e07d.PNG)

**Comment by eltharynd** [comment]
Pretty sure 12:07 AM is 00:07 (24h)

But regardless NOW do americans realize how silly am/pm is?

**Comment by lonerzzz** [comment]
I reported this issue (https://github.com/NativeScript/nativescript-angular/issues/1813) sometime back. It is still not fixed and no ETA available.

**Comment by MrSnoozles** [comment]
Jupp, this seems to be a bug in the TimePicker component in NativeScript core.

Weirdly enough it seems to be working if you set the hour to `new Number('0')`. Discovered this afters hours of trial and error.

**Comment by NathanWalker** [comment]
Closed via https://github.com/NativeScript/NativeScript/pull/10460
