### ISSUE TITLE
'backStack' is defined as an accessor in class 'FrameBase', but is overridden here in 'Frame' as an instance property.

### ISSUE THREAD

**Issue by rleongmt** [NativeScript/NativeScript#8945]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.10
 - Cross-platform modules: "@nativescript/core": "7.0.10"
 - Android Runtime: "@nativescript/android": "7.0.0"
 - iOS Runtime: "@nativescript/ios": "7.0.1"
 - Plugin(s): @nativescript/core/ui

**Describe the bug**
I am in the process of migrating from NS 5.4.2 to NS 7. I have fixed up a lot of error, and this is one of the last few errors that appear in my terminal when I type in the command 'ns prepare android'.

**To Reproduce**
I run the following command in order:
`ns clean`
`ns install`
`ns prepare android`

The error I get afterward is the following:
```
ERROR in node_modules/@nativescript/core/ui/frame/index.d.ts:84:2 - error TS2610: 'backStack' is defined as an accessor in class 'FrameBase', but is overridden here in 'Frame' as an instance property.

84  backStack: Array<BackstackEntry>;
    ~~~~~~~~~
node_modules/@nativescript/core/ui/frame/index.d.ts:89:2 - error TS2610: 'currentPage' is defined as an accessor in class 'FrameBase', but is overridden here in 'Frame' as an instance property.

89  currentPage: Page;
    ~~~~~~~~~~~
node_modules/@nativescript/core/ui/frame/index.d.ts:94:2 - error TS2610: 'currentEntry' is defined as an accessor in class 'FrameBase', but is overridden here in 'Frame' as an instance property.

94  currentEntry: NavigationEntry;
    ~~~~~~~~~~~~
node_modules/@nativescript/core/ui/frame/index.d.ts:99:2 - error TS2610: 'animated' is defined as an accessor in class 'FrameBase', but is overridden here in 'Frame' as an instance property.

99  animated: boolean;
    ~~~~~~~~
node_modules/@nativescript/core/ui/frame/index.d.ts:104:2 - error TS2610: 'transition' is defined as an accessor in class 'FrameBase', but is overridden here in 'Frame' as an instance property.

104  transition: NavigationTransition;
     ~~~~~~~~~~
node_modules/@nativescript/core/ui/frame/index.d.ts:146:2 - error TS2610: 'navigationBarHeight' is defined as an accessor in class 'FrameBase', but is overridden here in 'Frame' as an instance property.

146  navigationBarHeight: number;
     ~~~~~~~~~~~~~~~~~~~
node_modules/@nativescript/core/ui/proxy-view-container/index.d.ts:11:9 - error TS2611: 'ios' is defined as a property in class 'LayoutBase', but is overridden here in 'ProxyViewContainer' as an accessor.

11     get ios(): any;
           ~~~
node_modules/@nativescript/core/ui/proxy-view-container/index.d.ts:12:9 - error TS2611: 'android' is defined as a property in class 'LayoutBase', but is overridden here in 'ProxyViewContainer' as an accessor.

12     get android(): any;
```

**Expected behavior**
The terminal shouldn't throw the error and that the app should build properly.

**Additional context**
Just incase my tsconfig is incorrect, here's my settings.
```
{
  "compilerOptions": {
    "module": "commonJs",
    "target": "ES2017",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "importHelpers": true,
    "noEmitHelpers": true,
    "noEmitOnError": true,
    "lib": [
      "es6",
      "dom",
      "es2015.iterable",
      "es2015.promise",
      "es5",
      "es2017"
    ],
    "baseUrl": ".",
    "paths": {
      "*": [
        "./node_modules/@nativescript/core/*",
        "./node_modules/*"
      ]
    },
    "moduleResolution": "node",
    "removeComments": false
  },
  "exclude": [
    "node_modules",
    "platforms",
    "**/*.aot.ts"
  ]
}
```

**Comment by Kristoffer-Axelsson** [comment]
I have been testing an upgrade to NS7 to accomodate support on iOS14, I'm getting the exact same error when running tns build android, any ideas are appreciated!

**Comment by rleongmt** [comment]
I've solved it.

I was using TypeScript v4.0.3, however @nativescript/core/ui is using TypeScript v3.9.7. After downgrading my typecript, it now works.

**Comment by jpcarnes** [comment]
@rleongmt I am running into the same isues with my ns7 and ng10 app. What specific steps did you take to fix this issue?

**Comment by rleongmt** [comment]
@jpcarnes Try doing it without the caret sign.

**Comment by jpcarnes** [comment]
@rleongmt I removed the caret, deleted node modules, saved all then ran a fresh npm install. Any thoughts on what else I could do to try and fix this?

Thanks for the help!

**Comment by rleongmt** [comment]
@jpcarnes package-lock.json should be deleted, along with node_modules folder before doing npm install.

Make sure all your version are as exact without any caret or squiggles.
Cross-platform modules: "@nativescript/core": "7.0.10"
Android Runtime: "@nativescript/android": "7.0.0"
iOS Runtime: "@nativescript/ios": "7.0.1"
"typescript": "3.9.7"

If it doesn't work, maybe it is a different problem, and consider asking around on NativeScript slack? https://nativescriptcommunity.slack.com

**Comment by matejhrazdira** [comment]
In my case I had to set ` "skipLibCheck": true` in tsconfig.json. 

They do the same thing in NativeScript template: https://github.com/NativeScript/nativescript-app-templates/blob/%40nativescript/template-blank-ng%407.0.7/packages/template-hello-world-ng/tsconfig.json
