### ISSUE TITLE
Plugin Upgraded To NS7 Missing Exports

### ISSUE THREAD

**Issue by Logikgate** [NativeScript/NativeScript#8948]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.10
 - Cross-platform modules: 7.0.10
 - Android Runtime:
 - iOS Runtime: 7.0.1
 - Plugin(s): nativescript-webview-utils

**Describe the bug**
I am currently attempting to modify nativescript-webview-utils so that it is compatible with NS7.  I have followed the plugin upgrade guide to update the plugin and have used ns migrate to upgrade the demo in the plugin.  

When running the plugin demo the below warning is shown.  When the app boots up the imported WebViewUtils is indeed undefined. This is odd because the compiled code does include an export for WebViewUtils.  This import did work prior to me adding the @NativeClass decorator but that decorator is required since it is extending native classes.

```
WARNING in ./main-page.ts 19:4-16
"export 'WebViewUtils' was not found in 'nativescript-webview-utils'
 @ \b_[\w-]*\.)scss)$ (. sync (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$)
 @ ./app.ts
```

**To Reproduce**
The repo can be found [here](https://github.com/flypapertech/nativescript-webview-utils/tree/upgrade-to-ns7).  

From the src directory run `npm run demo.ios`

**Expected behavior**
The demo app should run and the imported WebViewUtils should be defined.

**Sample project**
https://github.com/flypapertech/nativescript-webview-utils/tree/upgrade-to-ns7

**Comment by NathanWalker** [comment]
Thanks @Logikgate I'll take a look at the plugin.

**Comment by NathanWalker** [comment]
@Logikgate I posted PR https://github.com/flypapertech/nativescript-webview-utils/pull/1
This reworks the util class setup to work with NativeClass esm handling for {N} 7 👍 
I've verified iOS works and Android looks like is working but lemme know if anything else is missing.

**Comment by Logikgate** [comment]
@NathanWalker Thank you so much!
