### ISSUE TITLE
[ios] prompt dialog not working

### ISSUE THREAD

**Issue by toams69** [NativeScript/NativeScript#8951]
**Environment**
"tns-android": {
      "version": "6.0.0"
    },
    "tns-ios": {
      "version": "6.5.2"
    }
 "@nativescript/core": "^7.0.10",
ios 14

**Describe the bug**
Prompt dialog are not working. No error in the device console.

It is ok with alert dialog btw.
I have use the sample to test.

```
prompt({
  title: "Your dialog title",
  message: "Your message",
  okButtonText: "Your OK button text",
  cancelButtonText: "Your Cancel button text",
  defaultText: "Suggested user input",
}).then(result => {
  console.log(`Dialog result: ${result.result}, text: ${result.text}`)
});
```

it was working well on previous version of ios and ns 6.

**Comment by NathanWalker** [comment]
@toams69 hey thanks - could you try using the rollup barrel like this?
```
import { Dialogs } from '@nativescript/core';

Dialogs.prompt({...
```

**Comment by toams69** [comment]
@NathanWalker I have the same issue :( .

**Comment by toams69** [comment]
For information


"dependencies": {     "@nativescript/core": "^7.0.10",     "@nativescript/datetimepicker": "^2.0.3",     "@nativescript/theme": "~2.3.0",     "@nstudio/nativescript-checkbox": "^2.0.0",     "@nstudio/nativescript-snackbar": "^2.0.2",     "moment": "^2.24.0",     "nativescript-bluetooth": "^1.3.1",     "nativescript-carousel": "^7.0.1",     "nativescript-fonticon": "^2.0.0",     "nativescript-localize": "4.2.2",     "nativescript-modal-datetimepicker": "^1.2.3",     "nativescript-ui-chart": "^8.0.2",     "nativescript-ui-gauge": "^7.0.2",     "nativescript-vue": "^2.8.1",     "vue-class-component": "^6.3.2",     "vue-moment": "^4.0.0",     "vue-property-decorator": "^7.3.0",     "vuex": "^3.0.1"   },   "devDependencies": {     "@babel/core": "^7.1.0",     "@babel/preset-env": "^7.1.0",     "@types/node": "^12.12.16",     "babel-loader": "^8.0.0",     "clean-webpack-plugin": "^0.1.19",     "copy-webpack-plugin": "^4.5.2",     "css-loader": "^1.0.0",     "lazy": "1.0.11",     "nativescript-dev-webpack": "1.5.0",     "nativescript-vue-template-compiler": "2.4.0",     "nativescript-worker-loader": "0.11.0",     "node-sass": "^4.9.2",     "sass-loader": "^7.1.0",     "terser-webpack-plugin": "^1.1.0",     "tns-platform-declarations": "6.5.15",     "typescript": "^3.2.4",     "vue": "^2.5.22",     "vue-loader": "^15.4.0",     "vuex-class": "^0.3.2",     "webpack": "^4.27.0",     "webpack-bundle-analyzer": "~2.13.1",     "webpack-cli": "^3.1.0"   } }
--

**Comment by toams69** [comment]
The prompt function is called in a tap handler function

**Comment by NathanWalker** [comment]
Here's a sample project - works fine: https://github.com/NathanWalker/ios-14-prompt-working

Feel free to post a sample project if you find different sample which causes what you're seeing.

![prompt-working](https://user-images.githubusercontent.com/457187/95629067-144b7a00-0a34-11eb-9c26-8c4cc3eb2fad.gif)
