### ISSUE TITLE
RadListView has a broken indices on Android after NS7 upgrade, this leads to the app crashing on cell recycling

### ISSUE THREAD

**Issue by cjohn001** [NativeScript/NativeScript#8955]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.10
 - Cross-platform modules:
 - Android Runtime: "@nativescript/android": "7.0.0"

 - Plugin(s): "nativescript-ui-listview": "^9.0.2"

**Describe the bug**
When using RadListView together with sorting and/or grouping functionality, the lists internal indexes are messed up. It is most easy to see when using the list view together with swipe gesture, than the onItemSwiping() event handler gets called with wrong indexes in its argument. I also get app crashes once the listview starts recycling it cells. I assume this is due to the same bug where the wrong indices are breaking the recycling.

**To Reproduce**
I provided a demo showing the bug which you can download from here:

https://github.com/cjohn001/listviewbug

Explanation is in the demo. Simply swipe a cell to the left to open it and compare console output. On IOS everything is working as expected, i.e. console output shows text displayed within cell. On iOS, du to the obtained wrong index the wrong source items are accessed.

**Expected behavior**
onItemSwiping() event handler should be called with the correct indices and the app should not crash. Same behaviour as with NS6

**Sample project**
https://github.com/cjohn001/listviewbug

**Additional context**
@NathanWalker : This is the bug for the issue we were discussing recently.

**Comment by NathanWalker** [comment]
@cjohn001 `9.0.3` was just published now which improves index handling and adds some resiliency on null/undefined hooks. Could you try `ns clean` and try this version and lemme know?

**Comment by cjohn001** [comment]
Hello @NathanWalker ,
thanks for looking into it. Unfortunately, the bug still persists and is exactly the same. Have you tried to get my example running? In my example, if you set a breakpoint into the onItemSwiping function you can see that the index in the event is the index of the item view in the swipe list, but it rather should be the index of the source item in the underlaying array which is displayed by the item view. As I mentioned, this requires grouping and sorting being enabled because then the indexes in the underlaying source list are not equal to the list item view index in the list.

**Comment by NathanWalker** [comment]
@cjohn001 hmm okay lemme give it another shot, thanks for extra detail.

**Comment by NathanWalker** [comment]
@cjohn001 alright `9.0.4` published now with the fix confirmed against your sample. Feel free to reopen if have further issue.

**Comment by cjohn001** [comment]
@NathanWalker , thanks a lot! One step closer now :) I can confirm, it works with demo and my app as well.
