### ISSUE TITLE
Native declarations cause app to not be compatible with NS7

### ISSUE THREAD

**Issue by bradrice** [NativeScript/NativeScript#8972]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ Component nativescript has 7.0.10 version and is up to date.
⚠ Update available for component @nativescript/core. Your current version is 7.0.10 and the latest available version is 7.0.11.
⚠ Update available for component @nativescript/ios. Your current version is 7.0.1 and the latest available version is 7.0.3.
✖ Component @nativescript/android is not installed.
 - XCode Version: 12.01
 - Plugin(s): 
Dependencies:
┌───────────────────────────────────┬──────────┐
│ Plugin                            │ Version  │
│ @angular/animations               │ ~10.1.0  │
│ @angular/common                   │ ~10.1.0  │
│ @angular/compiler                 │ ~10.1.0  │
│ @angular/core                     │ ~10.1.0  │
│ @angular/forms                    │ ~10.1.0  │
│ @angular/platform-browser         │ ~10.1.0  │
│ @angular/platform-browser-dynamic │ ~10.1.0  │
│ @angular/router                   │ ~10.1.0  │
│ @nativescript/angular             │ ~10.1.0  │
│ @nativescript/core                │ ~7.0.0   │
│ async-await                       │ ^0.1.40  │
│ lodash                            │ ^4.17.15 │
│ moment                            │ 2.24.0   │
│ nativescript-audio                │ ^6.1.0   │
│ nativescript-theme-core           │ ^1.0.4   │
│ nativescript-ui-listview          │ ^9.0.2   │
│ nativescript-ui-sidedrawer        │ ^9.0.3   │
│ nativescript-videoplayer          │ ^5.0.1   │
│ nativescript-xml2js               │ ^0.5.2   │
│ nativescript-xmlobjects           │ ^1.1.4   │
│ reflect-metadata                  │ ~0.1.8   │
│ rxjs                              │ ^6.4.0   │
│ zone.js                           │ ^0.9.1   │
└───────────────────────────────────┴──────────┘
Dev Dependencies:
┌─────────────────────────┬──────────┐
│ Plugin                  │ Version  │
│ @angular/compiler-cli   │ ~10.1.0  │
│ @nativescript/ios       │ 7.0.1    │
│ @nativescript/types     │ 7.0.0    │
│ @nativescript/webpack   │ ~3.0.0   │
│ @ngtools/webpack        │ ^8.2.2   │
│ @types/lodash           │ 4.14.108 │
│ @types/node             │ 10.0.3   │
│ lazy                    │ 1.0.11   │
│ node-sass               │ 4.12.0   │
│ ts-node                 │ 8.3.0    │
│ tslint                  │ 5.18.0   │
│ typescript              │ ^3.5.3   │
│ uglifyjs-webpack-plugin │ 2.2.0    │

**Describe the bug**
I need native platform declarations but if I use tns-platform-declarations I get a message my app is not compatible with NS7.

If I compile my app without it, I get typescript errors even though I have this:

/// <reference path="./node_modules/@nativescript/types/index.d.ts" />
/// <reference path="./node_modules/@nativescript/types-ios/index.d.ts" />

in my references.d.ts file

**To Reproduce**

npm i tns-platform-declarations

run app and you should get the error.

**Expected behavior**

**Sample project**

**Additional context**
I am using the nativescript-audio plugin which uses native declarations. I get errors when compiling for missing declarations.

**Comment by NathanWalker** [comment]
@bradrice use strictly only `@nativescript/types` - they are same as tns-platform-declarations actually. Just make sure `references.d.ts` is updated as follows:
```
/// <reference path="./node_modules/@nativescript/types/index.d.ts" />
```
Works the same. Feel free to comment further is any additional confusion.

**Comment by bradrice** [comment]
I have a references.d.ts file with this in it

/// <reference path="./node_modules/@nativescript/types/index.d.ts" />
/// <reference path="./node_modules/@nativescript/types-ios/index.d.ts" />

I have 

"@nativescript/types": "7.0.0",

in my devDependencies, but it still is not finding them. Do I need a tsconfig pointer?

**Comment by bradrice** [comment]
I figured it out. My references.d.ts file was not being found.
