### ISSUE TITLE
NativeScript Image Picker error for Android 10

### ISSUE THREAD

**Issue by avesaravanan** [NativeScript/NativeScript#8990]
**Environment**
The Image picker is error in Android 10 version.
 
**Version**
"tns-android": {
 "version": "6.5.1"
 },
 "tns-ios": {
 "version": "6.5.2"
 }

The above is used.

**Describe the Bug:** 
ERROR Error: uncaught (in promise): Asset '/storage/emulated/0/WA0010.jpeg' cannot be found.

**Expected behavior**

The Image has to be display in Android 10 version Mobiles. The same is working in Android 9 versions.

**Comment by avesaravanan** [comment]
Any help please

**Comment by nikoTM** [comment]
@avesaravanan could you please provide a minimal project to reproduce this?

**Comment by ARKEOLOGIST** [comment]
Any update on this @avesaravanan?

**Comment by rigor789** [comment]
Android 10 had significant file related changes, locking them down for security: https://developer.android.com/about/versions/10/privacy/changes

See: https://github.com/NativeScript/NativeScript/issues/8596#issuecomment-633134458
```
<manifest ... >
  <!-- This attribute is "false" by default on apps targeting
       Android 10 or higher. -->
  <application android:requestLegacyExternalStorage="true" ... >
    ...
  </application>
</manifest>
```
