### ISSUE TITLE
Work with Maps

### ISSUE THREAD

**Issue by vit1251** [NativeScript/NativeScript#9]
Hello,

How to create Maps widget on platform and set Mark and etc?

Thanx.

**Comment by ligaz** [comment]
Hi @vit1251,

Currently we did not have a cross platform Map Compoment but we plan to have one in a future version of the framework. Please follow [this](https://github.com/NativeScript/cross-platform-modules/issues/177) issue in our cross-platform-modules repo for updates.

Meanwhile you can also check [this](https://github.com/tjvantoll/maps) app by @tjvantoll that illustrates basic usage of the native map for iOS - MKMapView.

**Comment by vit1251** [comment]
Thanx for answer.
