### ISSUE TITLE
Support background-color and color for ActionBar

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/NativeScript#900]
I've found that this is a common requirement, and changing these colors yourself using the native approach is a bit of a pain.

Ideally I'd be able to do this in CSS—e.g. `ActionBar { color: white; background-color: black; }`—but an API to handle this in JavaScript would be sufficient as well. Anything that keeps me from ever touching `styles.xml` or `colors.xml` again is a win for me :)

**Comment by bradmartin** [comment]
+1 - coming from a web/hybrid app background I'm having to spend a lot of time in the Android dev docs for styling different components. Specifically I've been working to customize the TabView on Android and I've finally figured it out using AppCompat and styles.xml. I believe this is potentially a turn off for many web devs trying to pick up NativeScript. Adding more CSS support for common Views would help with developer adoption for sure.

Adding to what @tjvantoll  is suggesting, I'm not opposed to NativeScript not adding a common API to handle this if they would add a very thorough blog/doc section about common iOS styling and Android styling with themes, colors, styles.xml.

**Comment by sitefinitysteve** [comment]
+2 I find the android xml files frustrating to use with {N} ....changes do one of two things
1) Don't work
2) Break the build

I vote for the css idea from @tjvantoll and have it all handled internally...

**Comment by nedium** [comment]
Am i missing something or is this already working?
I read the action-bar-demo source code, applied them to my project and it worked instantly.
[action-bar-demo/main-page.xml](https://github.com/NativeScript/NativeScript/blob/6b9a476a7cb68802273b92f4f067f94fe9ace518/apps/action-bar-demo/main-page.xml)
[action-bar-demo/app.css](https://github.com/NativeScript/NativeScript/blob/6b9a476a7cb68802273b92f4f067f94fe9ace518/apps/action-bar-demo/app.css)

**Comment by sitefinitysteve** [comment]
color works? (foreground text color)

**Comment by nedium** [comment]
just tested color, it is the partypooper.

**Comment by sitefinitysteve** [comment]
Yeah thats the problem...ugly android apps :\

**Comment by nedium** [comment]
This way both foreground and background colors are working, but it is an hack anyway...
```xml
  <Page.actionBar>
    <ActionBar title="{{ message }}" cssClass="custom-action-bar">
      <ActionBar.titleView>
        <Button text="{{ message }}" cssClass="custom-action-bar"/>
      </ActionBar.titleView>
      <NavigationButton text="go back" icon="res://backlight" tap="navTap"/>
      <ActionBar.actionItems>
        <ActionItem icon="res://save"/>
        <ActionItem icon="res://delete"/>
      </ActionBar.actionItems>
    </ActionBar>
  </Page.actionBar>
```
```css
.custom-action-bar {
    background-color: navy;
	color: white;
}
```

**Comment by N3ll** [comment]
Closing the issue in favor of https://github.com/NativeScript/NativeScript/issues/499.

**Comment by RusEu** [comment]
But how to add style to ActionItem?
```html
  <Page.actionBar>
    <ActionBar class="menu-color" style="background-color:#000;">
      <ActionBar.titleView>
        <Label text="Droupy"/>
      </ActionBar.titleView>
      <ActionBar.actionItems class="menu-color">
        <ActionItem text="BACK"  ios.position="left"/>
        <ActionItem text="SETTINGS" ios.position="right"/>
      </ActionBar.actionItems>
    </ActionBar>
  </Page.actionBar>
```

**Comment by alg** [comment]
@RusEu You can do that by adding this piece to `App_Resources/Android/values-v21/styles.xml`:

```xml
<resources>

  <!-- Application theme -->
  <style name="AppTheme" parent="Theme.AppCompat.Light">
    <!-- .... -->
    <item name="actionMenuTextColor">@color/white</item>
    <item name="android:actionMenuTextColor">@color/white</item>
  </style>

</resources>
```

As a bonus, you can also change the color of the status bar with this:

```xml
    <item name="colorPrimary">@color/color_primary</item>
    <item name="colorPrimaryDark">@color/color_primary</item>
    <item name="colorAccent">@color/ns_accent</item>
    <item name="android:statusBarColor">@color/color_primary</item>
```

**Comment by bradmartin** [comment]
You can also programmatically change the statusbar background at least on API >= 21. I use this to change the status bar on different pages, similar to how the Google Messenger app behaves.

          window.setStatusBarColor(new color.Color("#3489db").android);

**Comment by andreyluiz** [comment]
@RusEu Your tip does not work for me.
```
:processDebugResourcesUnknown source file : [...] styles.xml:8:38-50 : No resource found that matches the given name (at 'actionMenuTextColor' with value '@color/white').
```

It says.

**Comment by ralphpig** [comment]
This may be a bit late, but you can set the color of the actionBar programmatically from the views controller..

Tested on Android, API 23

Typescript
```typescript
import {EventData} from "data/observable";
import {Page} from "ui/page";
import {Color} from "color";

class Main{
   public loaded(args: EventData) {
      var page = <Page>args.object;
      page.actionBar.backgroundColor = new Color("#3523ff"); // This works
   }
}
```

Javascript
```javascript
var Color = require("color"); // Maybe?

function loaded(args) {
   var page = args.object;
   page.actionBar.backgroundColor = new Color("#3523ff"); // This probably works,
   page.actionBar.backgroundColor = "#3523ff"; // but maybe this is it instead. I haven't tried it.
}
```

**Comment by Saadoosh8** [comment]
simply add the following line to your app/App_Resources/Android/values/styles.xml  file:

<item name="android:textColorSecondary">#fff</item>

or by refrencing a color in your colors.xml file as following:

<item name="android:textColorSecondary">@color/{YOUR_COLOR_NAME}</item>

-------------------------------------------------------------

 NOTE: add it inside the AppThemeBase, it will look like the code below:

   <style name="AppThemeBase" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="toolbarStyle">@style/NativeScriptToolbarStyle</item>
        <item name="colorPrimary">@color/ns_primary</item>
        <item name="colorPrimaryDark">@color/ns_primaryDark</item>
        <item name="colorAccent">@color/ns_accent</item>
        **<item name="android:textColorSecondary">@color/{YOUR_COLOR_NAME}</item>**
    </style>

**Comment by Saadoosh8** [comment]
```
simply add the following line to your app/App_Resources/Android/values/styles.xml  file:

<item name="android:textColorSecondary">#fff</item>

or by refrencing a color in your colors.xml file as following:

<item name="android:textColorSecondary">@color/{YOUR_COLOR_NAME}</item>

-------------------------------------------------------------

 NOTE: add it inside the AppThemeBase, it will look like the code below:

   <style name="AppThemeBase" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="toolbarStyle">@style/NativeScriptToolbarStyle</item>
        <item name="colorPrimary">@color/ns_primary</item>
        <item name="colorPrimaryDark">@color/ns_primaryDark</item>
        <item name="colorAccent">@color/ns_accent</item>
   <item name="android:textColorSecondary">@color/{YOUR_COLOR_NAME}</item>

    </style>
```

**Comment by venkateshsj** [comment]
**To change color of ActionBar overflow button color, add the following in styles.xml:-**
`<item name="colorControlNormal">#fff</item>`
OR
`<item name="android:textColorSecondary">@color/ns_white</item>`

When you apply any of the above, it also changes the color of the bottom border of TextField, seemingly making it look borderless on a white background.

My environment is:
```
nativescript - 3.4.3 - Up to date
tns-core-modules - 3.4.1 - Up to date
tns-android - 3.4.2 - Up to date
tns-ios - 3.4.1 - Not installed
```

Is it not possible to only set a color for the overflow button from ActionBar without affecting anything else?

**Comment by spencercap** [comment]
@venkateshsj thanks for this! your solution works great in a global scope. any idea how I can change the color of the overflow button (the more actionItems three vertical dots) differently for various pages of my app? cheers
