### ISSUE TITLE
Cannot read property 'useHotModuleReload' of undefined

### ISSUE THREAD

**Issue by devcodedao** [NativeScript/NativeScript#9004]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - XCode Version:
 - Plugin(s):

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by dodongphure** [comment]
My solution is removing folder `hooks`.

**Comment by devcodedao** [comment]
Thanks. This resolve
