### ISSUE TITLE
Manifest merger failed : Package name 'false'

### ISSUE THREAD

**Issue by VeeK727** [NativeScript/NativeScript#9006]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ Component nativescript has 7.0.11 version and is up to date.
✔ Component @nativescript/core has 7.0.13 version and is up to date.
✖ Component @nativescript/ios is not installed.
✔ Component @nativescript/android has 7.0.1 version and is up to date.

**Problem**
I've migrated my NS6 project to NS7. I've also moved a plugin (dropdown) to the proplugins version and since then I'm unable to run the app. This error appears right at the end of the build when its almost ready to install on the device. The error is

```
Execution failed for task ':app:processDebugManifest'.
Manifest merger failed : Package name 'false' at position AndroidManifest.xml:3:64-89 should contain at least one '.' (dot) character
```
My manifest file looks like this
```
<?xml version="1.0" encoding="utf-8"?>
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android" package="__PACKAGE__" android:versionCode="10200" android:versionName="1.2">
    <supports-screens android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <application android:name="com.tns.NativeScriptApplication" android:allowBackup="true" android:icon="@drawable/icon" android:label="@string/app_name" android:theme="@style/AppTheme">
        <activity android:name="com.tns.NativeScriptActivity" android:label="@string/title_activity_kimera" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|smallestScreenSize|screenLayout|locale|uiMode" android:theme="@style/LaunchScreenTheme" android:windowSoftInputMode="adjustPan">
            <meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name="com.tns.ErrorReportActivity" />
    </application>
</manifest>
```
and package.json
```
{
  "description": "redacted",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@nativescript/core": "~7.0.0",
    "@nativescript/theme": "3.0.0",
    "@nstudio/nativescript-cardview": "^1.0.0",
    "@nstudio/nativescript-floatingactionbutton": "3.0.3",
    "@nstudio/nativescript-loading-indicator": "4.0.0",
    "@nstudio/nativescript-pulltorefresh": "^1.0.1",
    "@proplugins/nativescript-drop-down": "^9.0.2",
    "nativescript": "7.0.11",
    "nativescript-datetimepicker": "1.2.2",
    "nativescript-google-places-autocomplete": "1.0.3",
    "nativescript-image-cache-it": "6.0.0",
    "nativescript-material-icons": "1.0.3",
    "nativescript-toasty": "3.0.0-alpha.2",
    "nativescript-ui-autocomplete": "7.0.2"
  },
  "devDependencies": {
    "@nativescript/android": "7.0.1",
    "@nativescript/webpack": "~3.0.0",
    "sass": "1.27.0"
  },
  "gitHead": "d8bdf0799a219051f28f8abd7c258d2bf2fce6e1",
  "readme": "NativeScript Application",
  "author": "redacted",
  "main": "app.js"
}
```

I assume the variable `_PACKAGE_` is not getting loaded in there. How to fix this?

**Comment by rigor789** [comment]
You are missing a `name` field in your `package.json` - I believe adding that should resolve the issue after cleaning the project with `ns clean`

**Comment by VeeK727** [comment]
No didn't work. Same error. I've used `ns migrate` on this project and it seems it didn't work properly. I read that NS7 uses a single config file _nativescript.config.ts_ so is _package.json_ even being used?

nativescript.config.ts
```
import { NativeScriptConfig } from '@nativescript/core'

export default {
  id: 'redacted package id',
  appResourcesPath: 'app/App_Resources',
  android: {
    v8Flags: '--expose_gc',
    markingMode: 'none',
  },
  appPath: 'app',
} as NativeScriptConfig
```

**Comment by rigor789** [comment]
The config handles most of it yes, but the root level `package.json` is still required as that's where dependencies are managed etc. 

Could you share the project with us so we can look further into this?

**Comment by VeeK727** [comment]
Any way of sharing it privately?

**Comment by rigor789** [comment]
Sure, if it's on GitHub invite me (rigor789@gmail.com) or you can send the project zipped up to igor@nstudio.io

**Comment by VeeK727** [comment]
I've sent you on mail.

**Comment by rigor789** [comment]
@VeeK727 looks like your App_Resources has very old legacy gradle configs and it was overriding `applicationId` with `false` as in the `settings.json` it was set to `null`. 

Deleting `settings.gradle` and `settings.json` from `app/App_Resources/Android` and updating `app.gradle` to be the default restores the build:
```gradle
// Add your native dependencies here:

// Uncomment to add recyclerview-v7 dependency
//dependencies {
//	implementation 'com.android.support:recyclerview-v7:+'
//}

// If you want to add something to be applied before applying plugins' include.gradle files
// e.g. project.ext.googlePlayServicesVersion = "15.0.1"
// create a file named before-plugins.gradle in the current directory and place it there

android {
  defaultConfig {
    minSdkVersion 17
    generatedDensities = []
  }
  aaptOptions {
    additionalParameters "--no-version-vectors"
  }
}
```

**Comment by VeeK727** [comment]
That worked. Thanks for looking into it mate.

**Comment by mesuttalebi** [comment]
I has the same error, deletting settings.gradle and settings.json and updating app.gradle as what is in @rigor789  answer, but build failing with error as below:

FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleDebug' not found in root project 'myApp'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Command gradlew.bat failed with exit code 1
