### ISSUE TITLE
TypeError: using <Placeholder> example from docs

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/NativeScript#901]
Samsung Tab (4.4.2) - 

Error: TypeError: android.widget.LabelView is not a function... 

     var placeholder = require("ui/placeholder");
       function creatingView(args) {
    var nativeView = new android.widget.LabelView(args.context);
    nativeView.setText("Native");
    args.view = nativeView;
     }
    exports.creatingView = creatingView;

With the sample XML inside a <TabView>

       <StackLayout>
                    <Placeholder creatingView="creatingView"/>
                  </StackLayout>

**Comment by enchev** [comment]
Hey @bradmartin,

Thanks for reporting the issue!

This is [already fixed in our tests](https://github.com/NativeScript/NativeScript/blob/master/apps/tests/ui/placeholder/placeholder-tests.ts) and the docs will be regenerated for the release.

Please use TextView instead LabelView.

HTH
