### ISSUE TITLE
ERROR in Unexpected value 'NativeScriptRouterModule in /Users/projects/mobile-app/node_modules/@nativescript/angular/nativescript-angular.d.ts' imported by the module 'AppModule in /Users/projects/mobile-app/src/app/app.module.ts'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by Heena-Vora** [NativeScript/NativeScript#9010]
**Environment**

 - CLI: NativeScript - 7.0.11
 - Cross-platform modules: - 
 - Android Runtime: -
 - iOS Runtime: Nativescript/ios - 7.0.4
 - XCode Version: Version 12.1 (12A7403)
 - Plugin(s):

**Describe the bug**
I migrated the project to NS7 and Angular 10 to make it run with XCODE 12. and when I run _ns build ios_ it fails with exit code 2.

**Comment by NathanWalker** [comment]
Hi @Heena-Vora have you updated all import paths to:
```
import { Something } from '@nativescript/angular';
```
Make sure no imports like the following exist *anywhere* in your app:
```
import { Something } from '@nativescript/angular/something';
// or...
import { Something } from 'nativescript-angular/anything';
```

**Comment by Heena-Vora** [comment]
@NathanWalker Yes, I have updated all the imports following the same.

**Comment by NathanWalker** [comment]
@Heena-Vora if you could invite ‘NathanWalker’ username to repo I’d be happy to take a look Monday.

**Comment by Heena-Vora** [comment]
Added you @NathanWalker to our repo.

**Comment by choang10** [comment]
Having the same issue -- please post updates/info here when you can.

**Comment by Heena-Vora** [comment]
Not able to figure out yet what's causing this issue.

@NathanWalker if you can have a look, would really appreciate your kind gesture. :)

**Comment by etelvinacunha** [comment]
Having the same issue -- please post updates/info here when you can.

**Comment by NathanWalker** [comment]
@Heena-Vora when get a chance you may can share the package we got working for you here but we’ll close this now that it’s resolved for you.
