### ISSUE TITLE
HMR not working on iOS 14.2

### ISSUE THREAD

**Issue by basil-wolf** [NativeScript/NativeScript#9011]
**Environment**
 - CLI: 7.0.13
 - Cross-platform modules: @nativescript/ios - 7.0.4
 - Android Runtime: N/A
 - iOS version: 14.2
 - XCode Version: 12.1

**Describe the bug**
Seems there have been some changes in iOS 14.2 as when I run **ns run ios** the app is not starting on iOS device and HMR isn't working event when I try to start the app manually.

**To Reproduce**
Connect iOS device and run **ns run ios**

**Expected behavior**
HMR should work and restart the app automatically as it was working before.

**Comment by Log3n** [comment]
@vasilyzakharov You need to install XCode 14.2 Beta/RC to work with iOS 14.2 devices.
