### ISSUE TITLE
NativeScript Playground app not working in iOS 14

### ISSUE THREAD

**Issue by donmb1** [NativeScript/NativeScript#9012]
**Describe the bug**
`tns preview` produces a QR code and prompts to download the playground app via App Store. However, the app does not work. It immediately crashes once opened. This also seems to be a common issue. I am helpless now and don't know how to properly develop an app in nativescript if there is no way to test it?
Thanks for any advice.

**To Reproduce**
Download NativeScript Playground app from Appstore. Open in iOs 14.

**Expected behavior**
Expecting to preview my app in some way.

**Sample project**

**Additional context**

**Comment by NathanWalker** [comment]
Current Preview app in app store was built with 6.5.0 of tns-ios runtime and just needs republishing with 6.5.3. The delay in posting another update is related to AFNetworking update. We're working on posting an update 👍

**Comment by NathanWalker** [comment]
Updates are now available:
https://twitter.com/NativeScript/status/1325994280003891200
