### ISSUE TITLE
Cannot read property 'concat' of undefined

### ISSUE THREAD

**Issue by devcodedao** [NativeScript/NativeScript#9022]
Hi everbody.
I building app mobile by nativescript but when tns run android appear err 
 Cannot read property 'concat' of undefined
![image](https://user-images.githubusercontent.com/44493646/98783179-b98ab100-242b-11eb-8b97-3c717ab55886.png)
if  have any idea please comment below
Thank so much!

**Comment by rigor789** [comment]
Hey @devcodedao - please share the following information:
* CLI version (run `ns -v` or `tns --version`)
* Contents of your `package.json`
* perhaps the whole project if possible.

**Comment by devcodedao** [comment]
Info my package.json
  "@angular/compiler-cli": "^7.2.11",
    "@nativescript/schematics": "~0.3.0",
    "@nativescript/types": "7.0.0",
     tns --version 7.0.11
    "@angular/core": "~6.1.0",
    "@nativescript/angular": "10.0.0",
    "@nativescript/core": "7.0.0",
    "@nativescript/webpack": "3.0.0"

**Comment by rigor789** [comment]
Ok yeah, old project need to be migrated/updated manually to work with 7.x
