### ISSUE TITLE
How or when 'disposeNativeView' is called

### ISSUE THREAD

**Issue by luiguild** [NativeScript/NativeScript#9029]
**Environment**
 - CLI: 7.0.11

**Describe the bug**
I create this plugin [@yoonit/nativescript-camera](https://github.com/Yoonit-Labs/nativescript-yoonit-camera) from scratch and we figure out that 'disposeNativeView' it's never called. How to proceed?

**Expected behavior**
Fire `super.disposeNativeView()` when view are destroyed but's nothing happens

Sorry to not offer everything it's required to open a issue, I searched a lot about it before to decide come here and do that and I don't know what to do anymore

**Comment by DimitrisRK** [comment]
@luiguild How do you test whether this method is called or not?
Also, I think you get more chances to discuss or get answers regarding questions in Slack channel.
