### ISSUE TITLE
android: 'ui' and 'automated' apps run issues

### ISSUE THREAD

**Issue by DimitrisRK** [NativeScript/NativeScript#9039]
**Environment**
 - CLI: 7.0.11
 - Cross-platform modules: 7.0.13
 - Android Runtime: 7.0.0
 - iOS Runtime:
 - XCode Version:
 - Plugin(s):

**Describe the bug**
Every time I try to run automated or ui apps via `ns run` inside each app's root directory, I get the following message after app successful installation:
`Unable to apply changes on device: 7pizbqwkhexkw85h. Error is: Invalid Version: null.`

This gets fixed if I include `@nativescript/android` inside apps `package.json` like this:
```
"devDependencies": {
     "@nativescript/ios": "7.0.0",
+    "@nativescript/android": "7.0.0",
     "@nativescript/webpack": "file:../../dist/packages/nativescript-webpack.tgz",
     "typescript": "file:../../node_modules/typescript"
   },
```
I attempted to add this in a previous PR but was asked to remove it for some kind of reason.

I know that NativeScript development environment is setup in such a way that one runs everything from `npm run start` menu, but apps failed to locate my devices this way (probably has something to do with my environment being dockerized). Therefore, `ns run` could still be of primary importance.

**Comment by NathanaelA** [comment]
1. I've see the `Unable to apply changes on device: 7pizbqwkhexkw85h. Error is: Invalid Version: null.` error before; what happens when you nuke the platforms and node_modules folder.   Does it fix itself.    

2. As an aside; can you explain exactly what is docker-ized.

**Comment by DimitrisRK** [comment]
> 1. I've see the `Unable to apply changes on device: 7pizbqwkhexkw85h. Error is: Invalid Version: null.` error before; what happens when you nuke the platforms and node_modules folder.   Does it fix itself.
> 2. As an aside; can you explain exactly what is docker-ized.

About 1, yes getting rid of old platforms and node_modules folders fixed this issue. I'm not sure how this occured in the first place.
About 2, I have a docker container with Ubuntu OS that contains NativeScript CLI, Android SDK, and OpenJDK.
When running my container, I mount my workspace folder and work within it.
Even though my device is recognized when using ns build or run commands, npm run start menu will fail to locate my connected device resulting in the following error:
```
22:36  $ npm run start                                                                                                                               
                                                                                                                                                     
> nativescript@7.0.13 start /home/dimitrisrafail/workdir/NativeScript                                                                                
> nps                                                                                                                                                
                                                                                                                                                     
nps is executing `default` : nps-i                                                                                                                   
? NativeScript ~ made with ❤ apps.ui.android                         ⚆  Run Android  🤖                                                              
nps is executing `apps.ui.android` : nx run apps-ui:android                                                                                          

> nx run apps-ui:android                                                                                                                             
Searching for devices...                                                                                                                             
Cannot find connected devices.                                                                                                                       
Emulator start failed with: No emulator image available for device identifier 'undefined'.                                                           
To list currently connected devices and verify that the specified identifier exists, run 'tns device'.                                               
To list available emulator images, run 'tns device <Platform> --available-devices'.                                                                  
The script called "apps.ui.android" which runs "nx run apps-ui:android" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
```

Hitting `ns device android --available-devices` confirms my devices is in available devices list but `nx run apps-ui:android` will still fail to find it.

**Comment by DimitrisRK** [comment]
It seems that the issue in my case was that my environment had no emulators available.
