### ISSUE TITLE
FontAwesome icons not showing on OxygenOS 11

### ISSUE THREAD

**Issue by asharghi** [NativeScript/NativeScript#9041]
**Environment**
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 7.0.10 and the latest available version is 7.0.11.
⚠ Update available for component tns-core-modules. Your current version is 6.5.20 and the latest available version is 6.5.21.
✔ Component tns-ios has 6.5.3 version and is up to date.
✔ Component tns-android has 6.5.3 version and is up to date.

**Describe the bug**
I'm experiencing an issue with FontAwesome on version 11 of OxygenOS. It works great on OxygenOS 10 and iOS. 

Icons from the "fas" class isn't shown correctly anywhere in my apps. In the example image below, the one icon that is showing has class "far", and the rest "fas" My setup is:

![font](https://user-images.githubusercontent.com/9407896/99190251-cb3ec200-2765-11eb-851f-156338738a38.jpg)

Example of how it looks:
<table>
<tr>
<td> OxygenOS 11 (wrong)</td>
<td>iOS 14 (correct)</td>
<td> OxygenOS 10 (correct)</td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/9407896/99190408-b878bd00-2766-11eb-9649-1e02562a22bc.jpg" width="200"></td>
<td><img src="https://user-images.githubusercontent.com/9407896/99190441-d514f500-2766-11eb-95db-a80cfccd167c.jpg" width="200"></td>
<td><img src="https://user-images.githubusercontent.com/9407896/99190451-e0682080-2766-11eb-8ea7-260eda377737.jpg" width="200"></td>
</tr>
</table>

**To Reproduce**
Try running these examples on OxygenOS 11:
```
<Label text.decode="&#xf543;" class="nt-icon fas" />
<Label text.decode="&#xf02a;" class="nt-icon fas" />
```

**Expected behavior**
Icons to be shown

**Sample project**
I can give access to my project if needed

**Comment by jessorlisa** [comment]
We had two user reports so far with missing icons, both Huawei devices with OxygenOS. I assumed it has to do with OxygenOS because all other tested devices are fine (real devices and simulator).

**Comment by asharghi** [comment]
Great to hear that it's not all Android 11 devices. I tested with OnePlus 8T on OxygenOS 11.

**Comment by felixkrautschuk** [comment]
@asharghi I tested our app (using FontAwesome 5.14.0) on some Android 11 Emulators and on my Google Pixel 3a with Android 11 and all icons (regular and solid) are working as expected.
So I guess @jessorlisa is right, it might be related to OxygenOS users... at least it does not seem to be a general Android 11 problem.

**Comment by asharghi** [comment]
Thanks for confirming. I have updated the title of this issue

**Comment by farfromrefug** [comment]
Seems to be a known issue nothing to do with N https://forums.oneplus.com/threads/font-issue-in-oxygenos-10-3-0.1161212/

**Comment by asharghi** [comment]
Hi @farfromrefug. I don't think this is the same issue because it works on OxygenOS 10. Any suggestions on what I can do next?

**Comment by farfromrefug** [comment]
@asharghi do you have one of those phone? The best thing to do would be to test a very simple native android app testing the font there. That way we could say for sure if it is a N issue or an OS issue. 
In both case it would also be good to test with another custom font, especially a smaller one. I know big icons use characters that could fail on some system.

**Comment by asharghi** [comment]
It was actually my friends phone, but I can test that this weekend. When you say "smaller" do you mean in filesize? In my example above that is true. The only icon showing is from "fa-regular-400.ttf" (40kb), where the others that's not showing are from "fa-solid-900.ttf" (209kb).

**Comment by farfromrefug** [comment]
@asharghi Yes i mean smaller in size(less icons)

**Comment by anmaitrannguyen** [comment]
Recently we got report from our user about this problem too. Vivo vivo device and Asus device mostly. On Android 9.0, Android 8.1 and Android 10. So we should optimize the size of the icon files?

**Comment by farfromrefug** [comment]
@anmaitrannguyen not yet. First we need to make sure:
* devices it happens on
* font used
* know if any other icon font is working on those devices

**Comment by anmaitrannguyen** [comment]
List of device reported so far:
Vivo vivo 1920 (Android 10)
Vivo vivo 1906 (Android 9)
Vivo vivo 1804 (Android 10)
Vivo vivo 1806 (Android 10)
Asus ZenFone 4 Max (Android 8.1)

I'm trying to get these device.

**Comment by jessorlisa** [comment]
Has anybody figured out the culprit here?

**Comment by asharghi** [comment]
I haven't been able to get hold of a phone with this os and version yet. Anyone else?

**Comment by asharghi** [comment]
I got to test this out some more today. Found out it has to do with selected font in the OS. It only happens on "OnePlus Sans". Works with "Roboto", even on OxygenOS 11.

<table>
<tr>
<td>OxygenOS 11 with Roboto (works)</td>
<td>OxygenOS 11 with OnePlus Sans (not working)</td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/9407896/101994689-7ccd0680-3cc4-11eb-873d-0f53aea140dd.jpg" width="200"></td>
<td><img src="https://user-images.githubusercontent.com/9407896/101994731-d7666280-3cc4-11eb-9194-7c4e8c65e1e3.jpg" width="200"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/9407896/101994718-b4d44980-3cc4-11eb-8e33-a2c1e04c6afc.png" width="200"></td>
<td><img src="https://user-images.githubusercontent.com/9407896/101994721-b867d080-3cc4-11eb-9737-4f49268b4b28.png" width="200"></td>
</tr>
</table>

**Comment by saschaarthur** [comment]
+1 can confirm that its related to the selected font

**Comment by NathanaelA** [comment]
Have you tried copying the "OnePlusSans" font to another device and seeing it the same issue occurs?    If we can duplicate the issue we might be able to find a work around...

**Comment by saschaarthur** [comment]
if you tell me where to find this font, im willing to share it

**Comment by asharghi** [comment]
Hi @NathanaelA. These are preinstalled fonts in OxygenOS, with the possiblity to switch between them in the OS settings. To reproduce the bug, you could just create a new NS project with a Label showing a FontAwesome icon: 

<Label text.decode="&#xf543;" class="nt-icon fas" />

Then go to the phone settings and change from Roboto to OnePlus Sans

**Comment by NathanaelA** [comment]
@asharghi - Hi Andre, I don't have a device with OxygenOS, so my thought was if it could be duplicated on a different device (or even better yet, emulator) using the OnePlusSans's font as the default font on it, then perhaps a fix could be figured out how to work around it...

**Comment by NathanaelA** [comment]
@asharghi - Hi Andre, I don't have a device with OxygenOS, so my thought was if it could be duplicated on a different device (or even better yet, emulator) using the OnePlusSans's font as the default font on it, then perhaps a fix could be figured out how to work around it...

**Comment by farfromrefug** [comment]
@NathanaelA just tried OnePlusSans on my samsung device. No issue, icon fonts works perfectly. 
I think it is an OxygenOS issue. You can easily find forums posts about this on the web.

**Comment by rigor789** [comment]
I suspect they "force override" the font system wide - causing icon fonts to be overridden to OnePlusSans.

**Comment by asharghi** [comment]
Thanks for the response guys. So I guess there isn't a workaround or anything else we can do?

**Comment by farfromrefug** [comment]
@asharghi you could try to set a font llike roboto or all labels buttons....

**Comment by jessorlisa** [comment]
> @asharghi you could try to set a font llike roboto or all labels buttons....

Are we not doing exactly that by setting up our FontAwesome css classes and applying them to labels/buttons?

**Comment by farfromrefug** [comment]
I dont think you are using font awesome for all labels/buttons. Would have only icons. It is those others I am talking about. Though I really doubt it would work

**Comment by felixkrautschuk** [comment]
On my Pixel 3a with Android 11 it is working as expected, but we got some reports that the FontAwesome Icons are not shown anymore after upgrading to Android 11 on some devices. 

In our case, some Samsung devices are affected, as one example the _Samsung S20 Ultra_. The user mentioned that he switched from the default font to one of the other pre-installed fonts like "SamsungOne", "Gothic Bold" or "Cool Jazz" and they were working fine with all the FontAwesome icons we use. After upgrading Android 11, some of the icons are shown the wrong way or are not shown at all anymore. When switching back to the default system font, it is working fine again.

**Comment by jessorlisa** [comment]
We have another (non OxygenOS) report as well:

- Samsung Galaxy S20+ with Android 11
- Custom font: "SamsungOne"

**Comment by farfromrefug** [comment]
@jessorlisa @felixkrautschuk could you try then to reproduce it in an android 11 emulator? If you do then you can share a repro example and we can take a look at finding a solution/workaround

**Comment by felixkrautschuk** [comment]
I downloaded the ttf file [here](https://github.com/putrairvaan/Font-TTF/blob/master/SamsungOne-400.ttf) but now I do not know how to install the font in the emulator. I found some old instructions but they do not work.

**Comment by felixkrautschuk** [comment]
@asharghi do you see the same effect using another font like Material design icons or is this only related to FontAwesome?

I am still not able to install the SamsungOne font on emulator, actually I have not that much time to try it again.

**Comment by asharghi** [comment]
@felixkrautschuk I have only tried with FontAwesome. Wasn't able to find out how to install fonts on Android emulators when I googled either sadly.

**Comment by saschaarthur** [comment]
Invested some hours on this issue.. 

Successfully replaced the fonts with following steps:

What i did:

1. create emulator:
   - create avd emulator device android-9 no playstore (important!), used x86 as arch
    dont start the device
    
2.  start emulator with correct parameters:
  -  start it via cli with "emulator -show-kernel -verbose -writable-system -avd [name]" (leave it running in a terminal)
  
3. make /system writeable:
  - open a new terminal and put "adb root && adb remount", should work without issues 
  | this part is the most tricky, it get /system writable on the emulator 
  | if you get errors on this commands, you prob. selected an image with google play support.

4. replace fonts:
  - download font: https://www.dropbox.com/s/gei2xdiu58x8wq0/OpFont-Regular.ttf?dl=1
  - adb push "OpFonts-Regular.ttf /system/fonts"
  - adb shell
  - (running inside of the emulator): cd /system/fonts; for i in $(ls | grep Roboto); do cp OpFonts-Regular.ttf $i; done
  - exit
  
 5. Install affected app
  - adb install *.apk
  
 6. reboot system:
  - adb reboot 
  
   
Now your system should be bootet with the OP Font (you will surely see a difference).

So far so good, the font replace is working perfectly fine on android-9 devices (even if i see little issues on android-9 with it).

As we all know android 10/11 is affected. Sadly i struggle currently to get step 3 running on android-10/11, this step just fails when executing.. 

Anyone able to get /system writable on android-10/11 ?

**Comment by saschaarthur** [comment]
looks like getting /system rw, for the replacement is going to be hard.. https://mobile.twitter.com/topjohnwu/status/1170404631865778177

**Comment by jessorlisa** [comment]
@felixkrautschuk 
I did a quick test with Material Design Icons, as it seems there is no issue. But this might be related to the font weight.

Compare the following:
```
.material-icons {
  font-family: "Material Icons", "MaterialIcons-Regular";
  font-weight: 400;
}
```

vs.
```
.far {
  font-family: "Font Awesome 5 Free", fa-regular-400, monospace;
  font-weight: 400; // working!
}

.fas {
  font-family: "Font Awesome 5 Free", fa-solid-900, monospace;
  font-weight: 900; // not working!
}
```

@all Just a guess, but maybe the issue lies with the font-weight and not specificially with FontAwesome?

_Anyway, for now we will be switching to Material Design Icons because now more and more Android 11 updates are rolled out and we are sadly getting more and more bad reviews due to this bug. It would be wonderful if this would be addressed nevertheless._

**Comment by asharghi** [comment]
@jessorlisa I think I have to do the same. Any tips or examples on using MDI?

**Comment by jessorlisa** [comment]
@asharghi Short version: The setup steps are the same as for FontAwesome.

More details:

**Setup Steps**
- Get the latest MaterialIcons-Regular.ttf from the GitHub Repo and copy it to `src/fonts`, 
  e.g. [v4.0.0](https://github.com/google/material-design-icons/blob/4.0.0/font/MaterialIcons-Regular.ttf) (or [v3.0.1](https://github.com/google/material-design-icons/blob/3.0.1/iconfont/MaterialIcons-Regular.ttf))

- Add the following to your css:
```
.m-icon { // or any other class name you prefer
  font-family: "Material Icons", "MaterialIcons-Regular";
  font-weight: 400;
}
```

- Example Usage:
```
<FlexboxLayout justifyContent="space-between">
    <Image src="font://&#xe8e5;" class="m-icon" width="22"></Image>
    <Button text="&#xe8e5;" class="m-icon -primary" fontSize="22"></Button>
    <Label text="&#xe8e5;" class="m-icon m-t-15" fontSize="22"></Label>
</FlexboxLayout>
```

**Appearance compared to FontAwesome**

![Screenshot_20210112-140810](https://user-images.githubusercontent.com/55237/104319217-dbaeb700-54e0-11eb-81f8-f96da7a75613.png)


**Resources**
- Available Icons: https://material.io/resources/icons/
- Codepoints: https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.codepoints

Make sure to run `ns clean` after adding new font files.

**Comment by rigor789** [comment]
@jessorlisa @asharghi just a heads up, in latest CLI you can run `ns fonts` to figure out the correct `font-family` and `font-weight` values for your custom fonts!
