### ISSUE TITLE
TextField: clicking on email suggestion returns pretyped + suggested value (iOS 14)

### ISSUE THREAD

**Issue by kanclalg** [NativeScript/NativeScript#9043]
**Environment**
 - CLI: 7.0.10
 - iOS Runtime: 7.0.5
 - XCode Version: 12.2

**Describe the bug**
Clicking on email suggestion on iOS 14 returns pretyped + suggested email, e.g.: type `tes`, click on `test@test.com `suggestion, nativescript value becomes `testest@gmail.com` though textField's text which is seen is `test@test.com`

**To Reproduce**
1.1 On Simulator: Login to your iCloud if you're on simulator, merge your contacts and add your email so that you'd get suggestions;
1.2 On device: I'm not fully sure but I think it's enough to add new contact to `My Info` on `Settings -> Contacts` with a configured email;
2. Open app;
3. Start typing email;
4. Click on suggestion.

**Expected behavior**

Value is the same as shown in the textfield - without additional text.

**Sample project**
[TestTextField.zip](https://github.com/NativeScript/NativeScript/files/5548318/TestTextField.zip)

**Additional context**

Bug video:
[Screen Recording 2020-11-16 at 18.20.59.zip](https://github.com/NativeScript/NativeScript/files/5548375/Screen.Recording.2020-11-16.at.18.20.59.zip)

**Comment by luke-hawk** [comment]
+1

**Comment by janoshrubos** [comment]
Related to https://github.com/NativeScript/NativeScript/issues/9486, fixed in https://github.com/NativeScript/NativeScript/pull/9555

Closing this issue since the implementation is merged to master. 
If this error is still relevant, feel free to open a new issue!
