### ISSUE TITLE
BottomNavigation -> goBack on one tab breaks page opening

### ISSUE THREAD

**Issue by danyadanch** [NativeScript/NativeScript#9047]
**Environment**:
 - CLI:  6.8.0
 - Cross-platform modules: 6.5.20
 - Android Runtime: 6.5.3
 - iOS Runtime: 6.5.2

**Describe the bug**
I have page called "Fund". I have bottom navigation with 5 tabs - "Home" / "Portfolio" and 3 others. In default behaviour all tabs has it's own navigation stack and if opened "Fund" in Home and then opened Portfolio when i return to Home "Fund" still be opened. 
My goal is open default page for opened bottom navigation tab on every touch. Now it opened default page only on double tap like this
```

    handleTapIcon(args, index) {
        console.log('---> onItemTap', args.eventName);
        console.log('---> onItemTap', index);
        console.log('---> onItemTap', args.object);

        const tabStrip = args.object;
        const page = tabStrip.page;
        const frame = Frame.topmost();
        const bottomNav = page.getViewById('bottomNav');

        console.log('---> onItemTap selectedIndex', bottomNav.selectedIndex);
        if (bottomNav.selectedIndex === index && frame.canGoBack()) {
          this.selectedIndex = index;
          frame.goBack();
        }
    },
```
So i changed it to
```
    handleTapIcon(args, index) {
        console.log('---> onItemTap', args.eventName);
        console.log('---> onItemTap', index);
        console.log('---> onItemTap', args.object);

        const tabStrip = args.object;
        const page = tabStrip.page;
        const frame = Frame.topmost();
        const bottomNav = page.getViewById('bottomNav');

        console.log('---> onItemTap selectedIndex', bottomNav.selectedIndex);
        if (frame.canGoBack()) {
          this.selectedIndex = index;
          frame.goBack();
        }
    },
```
 and when i open Fund on Home tab and opened Portfolio tab and return to Home tab -> Fund is closed, but i can't opened it one more time.

**To Reproduce**
1. Create at mininum 2 bottom tabs.
2. Create common page for this tabs.
3. On first tab open page
4. Click second tab
5. Return to first tab
6. Click to open page!

**Expected behavior**
"Fund" page closes on bottom tab changing and opens correctly.

**Comment by DimitrisRK** [comment]
@danyadanch Since you use NativeScript 6, you can create a small sample in playground and post it here.
This would be very helpful.

**Comment by danyadanch** [comment]
@DimitrisRK Sure! [Link to playground](https://play.nativescript.org/?template=play-tsc&id=4Ij5yz&v=2)

**Comment by DimitrisRK** [comment]
@danyadanch It's quite possible Frame.topmost() gets confused during tab transition.
However, you can access a certain tab frame and call goBack() for it.
Check this playground and let me know if it solves your problem: https://play.nativescript.org/?template=play-tsc&id=4Ij5yz&v=6

**Comment by danyadanch** [comment]
@DimitrisRK I came to this decision just before you. Thank you so much!
