### ISSUE TITLE
ns run/debug ios stuck on "restarting application...."

### ISSUE THREAD

**Issue by delanick** [NativeScript/NativeScript#9059]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.11
 - Cross-platform modules:  "@nativescript/core": "~7.0.0",
 - Android Runtime: Not relevant
 - iOS Runtime: "@nativescript/ios": "7.0.6",
 - XCode Version: 11.6
 - Plugin(s):
    "@nstudio/nativescript-exoplayer": "^5.0.4",
    "nativescript-appversion": "^1.4.4",
    "nativescript-barcodescanner": "^4.0.1",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-pushy": "^2.1.0"

**Describe the bug**
When running `ns run ios` or `ns debug ios` the app installs on the device but the CLI gets stuck on `restarting application on....` without actually restarting it. When I manually then open the app, it never outputs anything into the console, so I can't check device outputs. And when making file changes, the CLI doesn't update the app debug/run session.

**To Reproduce**
Not sure, duplicate my environment...

**Expected behavior**
App should start on iOS device (iOS 14.1)

Please help, this is hell of annoying.

**Comment by jamescodesthings** [comment]
I know it sucks but as a workaround deleting the app from the device before the first cli run seems to work.

i.e. If you're installing the app fresh it doesn't get stuck there, then you get output as normal.

Same issue for me on `packages@latest` (ns-angular) with iOS 14.2 on an iPhone 11 Pro Max.

This is what I see in a trace log during the failure, not sure it alludes to the problem at all:
```
Uploading files:
[
  {
    source: '/var/folders/n5/p60rxvsd4rv1sq71vsctg5m80000gn/T/sync20201023-6726-19wafo4.jztr.zip',
    destination: 'Library/Application Support/LiveSync/sync.zip'
  }
]
For application com.engineius.app.driver on device with identifier: [MY-DEVICE-ID].
Received multiple results:
{
  '[MY-DEVICE-ID]': [
    {
      deviceId: '[MY-DEVICE-ID]',
      response: 'Successfully uploaded files'
    }
  ]
}
Restarting application on device [MY-DEVICE-ID]...
Printing device log for device with identifier: [MY-DEVICE-ID].
Stopping application com.engineius.app.driver on device with identifier: [MY-DEVICE-ID].
Received multiple results:
{
  '[MY-DEVICE-ID]': [
    {
      deviceId: '[MY-DEVICE-ID]',
      response: 'Successfully stopped application'
    }
  ]
}
Starting application com.engineius.app.driver on device with identifier: [MY-DEVICE-ID].
```

**Comment by delanick** [comment]
@jamescodesthings  sadly thatr also doesn't work. It fresh installs each time, but same result as above: gets stuck on `Restarting...` and then I need to man ually open the app, with no console outputs....

**Comment by jamescodesthings** [comment]
Sorry to hear it, I've had intermittent issues with the same problem and the workaround I've been using may just be a red herring.

**Comment by delanick** [comment]
@jamescodesthings Okay so I missed a crucial blog post earlier in the year around the NS7 compatibility with Xcode 12. Installed Xcode 12 and it seems to be working. Oof, feel really dumb now.

**Comment by brysem** [comment]
I ran into this same issue recently with the 12.2 update of Xcode. Updating from 12.1 to 12.2 fixed the issue. Updating to the latest version seems to be the remedy.

**Comment by jessorlisa** [comment]
I am still having the issue with Xcode 12.2. I sadly do not know when it started. Current test device is an iPhone SE (1st gen).

{N} 7 with JSC runtime:
```
├── nativescript@7.0.11
├── @nativescript/core@7.0.13
├── @nativescript/ios@6.5.3
```

**Comment by Upd4ting** [comment]
Still having this issues as well, any workaround?
It really sucks to need to rebuild each time we make a change

**Comment by Upd4ting** [comment]
Got the same issue on Xcode 12.4 (latest) any workaround please?

**Comment by jamescodesthings** [comment]
What sim version are you using?

There's various issues with iOS 14 and the cli tools: https://github.com/NativeScript/nativescript-cli/issues/5454

_tldr:_ try download the iOS 13 simulator runtime and test on an iOS 13 device until these issues are fixed.

- Xcode -> Preferences -> Components -> install 13.x
- Xcode -> Window -> Devices & Simulators -> Create a 13.x simulator of the device you're testing on.
- `ns run ios --device "iPhone 11 Pro Max 13"` or whatever you called the sim.

**Comment by Upd4ting** [comment]
I'm using a real device with ios 13.5.1

**Comment by justintoth** [comment]
Same issue here, both on iOS 14 and iOS 13 sims. I have the latest version of Xcode installed. Very frustrating... Anyone else still running into this issue?

```
Installing on device 00008020-00191D681E92002E...
Successfully installed on device with identifier '00008020-00191D681E92002E'.
Restarting application on device 00008020-00191D681E92002E...
```

**Comment by cjohn001** [comment]
+1

**Comment by LiamMcCallum** [comment]
+1

**Comment by Bezlepkin** [comment]
NS 8.1, XCode 12.4, iPhone SE (1) 14.7.1
Everything worked fine. Since yesterday, it also gets stuck...

**Comment by Bezlepkin** [comment]
I solved it!

It was necessary to download support for the device of the desired version https://github.com/JinjunHan/iOSDeviceSupport

and put in: Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform

**Comment by 7ammer** [comment]
@Bezlepkin's solution works!

**Comment by dlcole** [comment]
I just hit this same problem (again) after updating my devices to iOS 15.6. @Bezlepkin's solution does work.  Add the extracted folder downloaded from [https://github.com/JinjunHan/iOSDeviceSupport](https://github.com/JinjunHan/iOSDeviceSupport) (in this case, 15.6) to `Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport`.  You should see other supported versions in this same folder; you'll just be adding to it.

**Comment by SmailHammour** [comment]
@Bezlepkin can that be trusted since it's not official?

**Comment by rigor789** [comment]
I've used these sources in the past:
- https://github.com/filsv/iOSDeviceSupport
- https://github.com/iGhibli/iOS-DeviceSupport

But all 3 seem fine to me, they are extracted from official XCode. Perhaps less reputable repos should be avoided, but these are pretty widely used, so just based on that I'd say are ok.

**Comment by laupas** [comment]
hi all

I have the following tools installed:
Xcode version 14.2.0 
ns: 8.4.0
IOS Device with 16.3.1

I downloaded the DeviceSupport package 16.3 and stored under
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/16.3  

When I start ns run ios it is installing the application successfully but hangs on stopping the application on the device:

zipstream: 1896327 bytes written
Uploading files:
[
  {
    source: '/tmp/sync2023226-68013-c19wel.va5zr.zip',
    destination: 'Library/Application Support/LiveSync/sync.zip'
  }
]
For application common.lauener.demoapp on device with identifier: XXXXXX-XXXXXX.
Received multiple results:
{
  'XXXXXX-XXXXXX': [
    {
      deviceId: 'XXXXXX-XXXXXX',
      response: 'Successfully uploaded files'
    }
  ]
}
Restarting application on device XXXXXX-XXXXXX...
Printing device log for device with identifier: XXXXXX-XXXXXX.
Stopping application common.lauener.demoapp on device with identifier: XXXXXX-XXXXXX.

What do I miss?

**Comment by utkarsh-ust** [comment]
The issue still persists with iOS 17.5.1 with xCode 15.4.
Please suggest what needs to be done
