### ISSUE TITLE
Scss files do not generate css when in a subfolder in Nativescript 7

### ISSUE THREAD

**Issue by leocrawf** [NativeScript/NativeScript#9073]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

```json
{
  "name": "@nativescript/template-tab-navigation",
  "main": "app.js",
  "displayName": "Tabs",
  "templateType": "App template",
  "version": "7.0.3",
  "description": "NativeScript Application",
  "author": "NativeScript Team <oss@nativescript.org>",
  "license": "SEE LICENSE IN <your-license-filename>",
  "publishConfig": {
    "access": "public"
  },
  "keywords": [
    "nstudio",
    "nativescript",
    "mobile",
    "{N}",
    "tns",
    "template",
    "tab",
    "navigation",
    "category-general"
  ],
  "repository": "<fill-your-repository-here>",
  "homepage": "https://github.com/NativeScript/nativescript-app-templates",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "scripts": {
    "lint": "eslint \"app/**/*.js\""
  },
  "dependencies": {
    "@nativescript-community/ui-pager": "^13.0.0-alpha.14",
    "@nativescript/core": "~7.0.0",
    "@nativescript/firebase": "^11.1.3",
    "@nativescript/theme": "~2.3.0",
    "nativescript-carousel": "^7.0.1",
    "nativescript-ui-dataform": "^7.0.4",
    "nativescript-ui-listview": "^9.0.4"
  },
  "devDependencies": {
    "@nativescript/android": "7.0.1",
    "@nativescript/webpack": "~3.0.0",
    "copy-webpack-plugin": "^4.6.0",
    "eslint": "~7.7.0",
    "node-sass": "^4.14.1"
  },
  "private": "true",
  "readme": "NativeScript Application"
}
```

**Describe the bug**
If you create a component and place it in a subfolder structure similar to this: shared/components/searchbar/ and then import it in your parent page, the file is imported but it is not styled. If a css file is manually placed in the folder, the app is styled as expected.

**To Reproduce**
create nativescript 7 project then create file structure similar to this:
```
shared/components/searchbar/
  --searchbar.scss
  --searchbar.xml
```

Then import it on home page:

```
     // pages/home/home-page.xml

     <Page
         navigatingTo="onNavigatingTo"  
         xmlns:searchbar="shared/components/searchbar/"
         xmlns="http://schemas.nativescript.org/tns.xsd">

        <ActionBar flat="true">
           <searchbar:searchbar />
        </ActionBar>

    </Page>
```

**Expected behavior**
The expected  behavior is that the searchbar component should be imported and should be styled

**Sample project**
I created a sample project but the default project version is NS 6.5 not 7.x so it worked as expected.

**Additional context**
I modified `webpack.config.js` to fix NS 7 HMR issue where is restarts app on every change:
https://github.com/nativescript-vue/nativescript-vue/issues/747
```js
            // Copy assets
            // new CopyWebpackPlugin({
            //   patterns: [
            //     { from: 'assets/**', noErrorOnMissing: true, globOptions: { dot: false, ...copyIgnore } },
            //     { from: 'fonts/**', noErrorOnMissing: true, globOptions: { dot: false, ...copyIgnore } },
            //     { from: '**/*.jpg', noErrorOnMissing: true, globOptions: { dot: false, ...copyIgnore } },
            //     { from: '**/*.png', noErrorOnMissing: true, globOptions: { dot: false, ...copyIgnore } },
            //   ],
            // }),

            new CopyWebpackPlugin([
                { from: { glob: 'assets/**', dot: false } },
                { from: { glob: 'fonts/**', dot: false } },
                { from: { glob: '**/*.jpg', dot: false } },
                { from: { glob: '**/*.png', dot: false } },
              ], copyIgnore),
```
it is really difficult to write all my SCSS code in `_app-common.scss`. Any help is appreciated.

**Comment by rigor789** [comment]
I just tried this in a brand new project (`ns create issue9073 --js`), and seems to be working as expected:



![image](https://user-images.githubusercontent.com/879060/100526930-f1d11400-31cd-11eb-841d-4f74ded56682.png)

![image](https://user-images.githubusercontent.com/879060/100526935-f85f8b80-31cd-11eb-8dff-975785c75a61.png)

Attached my test project - perhaps it can help you compare configuration/structure
[issue9073.zip](https://github.com/NativeScript/NativeScript/files/5611294/issue9073.zip)

**Comment by rigor789** [comment]
Also tested with deeper nesting and it works in that test project.
![image](https://user-images.githubusercontent.com/879060/100527064-432dd300-31cf-11eb-8274-ccc49740b4bd.png)

**Comment by leocrawf** [comment]
Thank you. I will examin it.

**Comment by leocrawf** [comment]
After examining your project I realized I had made an error in how I was calling the file in XML:

         <Page
         navigatingTo="onNavigatingTo"  
         xmlns:searchbar="shared/components/searchbar/" --- this is wrong
         xmlns="http://schemas.nativescript.org/tns.xsd">

that really should

         <Page
         navigatingTo="onNavigatingTo"  
         xmlns:searchbar="shared/components/searchbar" -- no trailing slash
         xmlns="http://schemas.nativescript.org/tns.xsd">

thank you for your help.
