### ISSUE TITLE
Live reload can not reload page with BottomNavigation after change in code

### ISSUE THREAD

**Issue by PetroSuch** [NativeScript/NativeScript#9091]
**Environment**
{
  "nativescript": {
    "id": "com.application.app",
    "tns-android": {
      "version": "6.5.0"
    },
    "tns-ios": {
      "version": "6.5.0"
    }
  },

  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/schematics": "^0.6.0",
    "@nativescript/theme": "^2.3.3",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "@nstudio/nativescript-pulltorefresh": "^1.0.1",
    "@tweenjs/tween.js": "^17.4.0",
    "base-64": "^0.1.0",
    "lodash": "^4.17.15",
    "lodash.round": "^4.0.4",
    "moment": "^2.24.0",
    "nativescript-angular": "^8.21.0",
    "nativescript-background-http": "^4.2.1",
    "nativescript-barcodescanner": "^3.3.2",
    "nativescript-bcryptjs": "^1.0.1",
    "nativescript-camera": "^4.5.0",
    "nativescript-carousel": "^6.1.1",
    "nativescript-clipboard": "^1.2.0",
    "nativescript-datetimepicker": "^1.2.2",
    "nativescript-dom": "^2.0.5",
    "nativescript-fingerprint-auth": "^7.0.1",
    "nativescript-google-maps-sdk": "^2.9.0",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-keyboard-toolbar": "^1.1.0",
    "nativescript-local-notifications": "^4.1.5",
    "nativescript-localstorage": "^2.0.1",
    "nativescript-masked-text-field": "^4.0.3",
    "nativescript-md5": "^1.0.1",
    "nativescript-numeric-keyboard": "^4.3.1",
    "nativescript-openurl": "^1.0.2",
    "nativescript-permissions": "^1.3.9",
    "nativescript-plugin-badge": "^1.0.0",
    "nativescript-plugin-firebase": "^10.3.3",
    "nativescript-pulltorefresh": "^2.3.0",
    "nativescript-screenshot": "0.0.2",
    "nativescript-secure-storage": "^2.6.0",
    "nativescript-social-share": "^1.5.2",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-toast": "^2.0.0",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-ui-dataform": "^6.1.0",
    "nativescript-ui-listview": "^8.0.2-next-2019-12-18-091654-01",
    "nativescript-urlhandler": "^1.3.0",
    "nativescript-uuid": "0.0.1",
    "nativescript-zxing": "^1.5.9",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-android": "^6.1.2",
    "tns-core-modules": "^6.5.1",
    "tns-ios": "^6.1.1",
    "tns-urihandler": "^1.0.1",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "~8.2.0",
    "@types/lodash": "^4.14.136",
    "nativescript-dev-webpack": "^1.5.1",
    "tns-platform-declarations": "^6.1.2",
    "typescript": "~3.5.3"
  },
  "gitHead": "f28dbc60d74dd2cef4b645afd8fdd63bbb12c73e",
  "readme": "NativeScript Application"
}

I added BottomNavigation to my application, and when i change something in code and save it, LiveReload can not update application on my android emulator

Application  frozen and when i click on application i get message alert "Application isn't responding, Close app or Waiting"
What do i do wrong ?

**tabs-component.ts**

`<TabStrip iosIconRenderingMode="alwaysOriginal">

        <TabStripItem>
            <Image src="font://&#xf007;" class="fas t-36"></Image>
        </TabStripItem>
        <TabStripItem>
            <Image src="font://&#xf0c0;" class="fas t-36"></Image>
        </TabStripItem>

    </TabStrip>

    <TabContentItem>
        <page-router-outlet name="homeTab" actionBarVisibility="never"></page-router-outlet>
    </TabContentItem>

    <TabContentItem>
        <page-router-outlet name="teamTab" actionBarVisibility="never"></page-router-outlet>
    </TabContentItem>`

I have big home page, it contain many carousels, and other elements

**Comment by iamabs2001** [comment]
Not the issue with nativescript
