### ISSUE TITLE
Nativescript Playground QR code not doing anything on iOS 14.3

### ISSUE THREAD

**Issue by bjornharvold** [NativeScript/NativeScript#9106]
**Environment**
Have not yet installed an environment. I am trying to view the samples you have online at play.nativescript.org
iPhone 12
iOS: 14.3

**Describe the bug**
Nothing happens

**To Reproduce**
- Install Nativescript Playground from the iOS Appstore
- Open the application
- Tell it to scan a QR code
- The app beeps..... and nothing else happens

**Expected behavior**
- I should be seeing the samples as outlined on your website.
- 
**Sample project**
https://play.nativescript.org/?template=groceries-ng&tutorial=groceries-ng&autoStart=true

Please advise,
Bjorn

**Comment by scal0u** [comment]
I encounter the same issue 8 days later. Thanks

**Comment by FounderCasey** [comment]
I am also encountering this same issue

iOS 14.4

![](https://i.imgur.com/pRWPZN4.mp4)

**Comment by loki-gpu** [comment]
Hey guys ! Just found the solution, you have to install this app : https://apps.apple.com/us/app/nativescript-preview/id1264484702
Once you have installed NativeScrpit Previaw and Nativescript Playground, try to scan your qr code again !

**Comment by cor** [comment]
Thank you @loki-gpu, this solves the problem. the _Playground_ app should probably have a popup warning users that they should also have the _Preview_ app

**Comment by vikash20186** [comment]
thank you @loki-gpu. this should be in the docs.
