### ISSUE TITLE
Brew cask BROKEN for local build install

### ISSUE THREAD

**Issue by Sunhat** [NativeScript/NativeScript#9107]
I'm using nativescript 6, with nativescript-vue.

Hi - when running

```
tns run android
```

and choosing `Configure for local builds`

homebrew no longer works

``` brew cask ``` has been deprecated as of Dec 1st, and was removed in v2.7 released in the past few days.

I believe this has broken all installations

**Comment by brokyo** [comment]
This has been driving me crazy for an hour and I'm so relieved to see this post! 

This appears to be the case for me as well as I am receiving `Error: caskroom/versions was moved. Tap homebrew/cask-versions instead.` at the end of the first step and everything continues to fail from there on. Screenshot attached if useful :)

![Screen Shot 2020-12-28 at 9 50 59 PM](https://user-images.githubusercontent.com/1268510/103255327-e735a600-4956-11eb-894a-7a6b27feb133.png)

**Comment by Sunhat** [comment]
Hi @brokyo. Homebrew maintainers said they maintain their project based on their own interests not the community's. They will not patch this, so for now you'll have to install manually!

**Comment by rogersmj** [comment]
Just wanted to say I ran into this as well, and after digging around a little bit, here's the discussion in the Homebrew community:

https://github.com/Homebrew/discussions/discussions/340

They gave all of _20 days_ notice before fundamentally changing the install command behavior.

Is the best workaround to figure out how to downgrade to Homebrew 2.6 (which thus far I haven't been able to figure out how to do), or install the NS dependencies manually?
