### ISSUE TITLE
ns create vue project does not work

### ISSUE THREAD

**Issue by 7ammer** [NativeScript/NativeScript#9128]
**Environment**
ns cli: 7.1.1

**Describe the bug**
I get an error when trying to create a vue project :(

**To Reproduce**
`ns create`
...
> Next, which style of NativeScript project would you like to use: › Vue.js
> **Cannot read property 'value' of undefined**

**Expected behavior**
It doesn't brake

**Additional context**
I'm currently updating from ns cli 6.7.8

**Comment by rigor789** [comment]
Fixed in https://github.com/NativeScript/nativescript-cli/releases/tag/v7.1.2
