### ISSUE TITLE
tns create --template tns-template-hello-world-ng is broken (or has problems)

### ISSUE THREAD

**Issue by frunjik** [NativeScript/NativeScript#9134]
**Environment**
package.json
{
  "name": "tns-template-hello-world-ng",
  "version": "6.6.5",
  "author": "NativeScript Team <nativescript@nstudio.io>",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "keywords": [
    "nstudio",
    "nativescript",
    "mobile",
    "angular",
    "{N}",
    "tns",
    "template"
  ],
  "repository": "<fill-your-repository-here>",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "scripts": {
    "ngcc": "ngcc --properties es2015 module main --first-only",
    "postinstall": "npm run ngcc"
  },
  "dependencies": {
    "@angular/animations": "10.0.0",
    "@angular/common": "10.0.0",
    "@angular/compiler": "10.0.0",
    "@angular/core": "10.0.0",
    "@angular/forms": "10.0.0",
    "@angular/platform-browser": "10.0.0",
    "@angular/platform-browser-dynamic": "10.0.0",
    "@angular/router": "10.0.0",
    "@nativescript/angular": "10.0.0",
    "@nativescript/theme": "~2.3.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.5.0",
    "zone.js": "0.11.1",
    "@nativescript/core": "7.0.0",
    "@nativescript/webpack": "3.0.0"
  },
  "devDependencies": {
    "@angular/compiler-cli": "10.0.0",
    "@nativescript/types": "7.0.0",
    "@ngtools/webpack": "10.0.0",
    "tns-android": "6.5.3",
    "typescript": "3.9.7"
  },
  "private": "true",
  "readme": "NativeScript Application",
  "main": "main.js"
}

ns --version
7.0.11

ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.0.4
Node: 12.18.1
OS: win32 x64

Angular: 10.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1100.4 (cli-only)
@angular-devkit/core         10.0.8
@angular-devkit/schematics   11.0.4 (cli-only)
@ngtools/webpack             10.0.0
@schematics/angular          11.0.4 (cli-only)
@schematics/update           0.1100.4 (cli-only)
rxjs                         6.6.3
typescript                   3.9.7

ns info
√ Getting NativeScript components versions information...
‼ Update available for component nativescript. Your current version is 7.0.11 and the latest available version is 7.1.2.
‼ Update available for component @nativescript/core. Your current version is 7.0.0 and the latest available version is 7.1.0.
× Component @nativescript/ios is not installed.
√ Component tns-android has 6.5.3 version and is up to date.

**Describe the bug**
I want to generate an empty Nativescript app using angular.
I get all kinds of errors - and fixing them is confusing and does not seem to help

**To Reproduce**
>ns create --template tns-template-hello-world-ng hello-world

>cd hello-world

>ns run android --bundle

--SNIP--

Project successfully built.
The build result is located at: c:\Projects\web\tns\hello-world\platforms\android\app\build\outputs\apk\debug\app-debug.apk
Installing on device 19129522504543...
Successfully installed on device with identifier '19129522504543'.
Application org.nativescript.helloworld is not running on device 19129522504543.
This issue may be caused by:
        * crash at startup (try `tns debug android --debug-brk` to check why it crashes)
        * different application identifier in your package.json and in your gradle files (check your identifier in `package.json` and in all *.gradle files in your App_Resources directory)
        * device is locked
        * manual closing of the application
Unable to apply changes on device: 19129522504543. Error is: Application org.nativescript.helloworld is not running.

>tns debug android --debug-brk
The current application is not compatible with NativeScript CLI 7.0.

Run 'ns migrate' to migrate your project to NativeScript 7.

Alternatively you may try running it with '--force' to skip this check.

> ns migrate
Running ns migrate in a non-git project is not recommended. If you want to skip this check run ns migrate --force.

> git init

> git add *

> git commit -a -m "initial"

> ns migrate

ns run android --bundle

ERROR in ./main.ts
Module not found: Error: Can't resolve '@nativescript/angular/platform' in 'c:\Projects\web\tns\hello-world\src'
 @ ./main.ts 34:8-98 59:0-67
Error from chokidar (c:\): Error: EBUSY: resource busy or locked, lstat 'c:\hiberfil.sys'
Error from chokidar (c:\): Error: EBUSY: resource busy or locked, lstat 'c:\pagefile.sys'
Error from chokidar (c:\): Error: EBUSY: resource busy or locked, lstat 'c:\swapfile.sys'

**Expected behavior**
A working example app

**Sample project**
https://github.com/frunjik/ns-hello-world

**Additional context**

**Comment by rigor789** [comment]
Can you try with the updated templates:
```shell
ns create hello-world --ng 

# or 

ns create hello-world --template @nativescript/template-hello-world-ng
```

**Comment by frunjik** [comment]
> ns create hello-world --ng
> cd hello-world
> ns run android

Searching for devices...
Copying template files...
| [..................] - rollbackFailedOptional: WARN install Usage of the
`--dev` option is deprecated. U/ [..................] -
rollbackFailedOptional: WARN install Usage of the `--dev` option is
deprecated. U- [..................] - rollbackFailedOptional: WARN install
Usage of the `--dev` option is deprecated. U\ [..................] -
rollbackFailedOptional: WARN install Usage of the `--dev` option is
deprecated. U| [..................] - rollbackFailedOptional: WARN install
Usage of the `--dev` option is deprecated. U/ [..................] -
rollbackFailedOptional: WARN install Usage of the `--dev` option is
deprecated. U- [..................] - rollbackFailedOptional: WARN install
Usage of the `--dev` option is deprecated. U\ [..................] -
rollbackFailedOptional: WARN install Usage of the `--dev` option is
deprecated. U/ [   ...............] | loadDep:source-map: sill
resolveWithNewModule @nativescript/android@7.0.1 checkin- [
 ............] | loadExtraneous: sill resolveWithNewModule
@nativescript/android@7.0.1 checking in\ [      ............] |
loadExtraneous: sill resolveWithNewModule @nativescript/android@7.0.1
checking in| [      ............] | loadExtraneous: sill
resolveWithNewModule @nativescript/android@7.0.1 checking in/ [
 ........] / extract:fsevents: sill extract fsevents@1.2.13 extracted to
c:\Projects\web\tns\h- [          ........] / extract:fsevents: sill
extract fsevents@1.2.13 extracted to c:\Projects\web\tns\h\ [
 ........] | extract:fsevents: sill extract fsevents@1.2.13 extracted to
c:\Projects\web\tns\h| [          ........] | extract:fsevents: sill
extract fsevents@1.2.13 extracted to c:\Projects\web\tns\h/ [
 ........] | extract:fsevents: sill extract fsevents@1.2.13 extracted to
c:\Projects\web\tns\h- [            ......] -
refresh-package-json:@nativescript/android: timing action:finalize
Completed in 8\ [            ......] | postinstall: info lifecycle
@nativescript/android@7.0.1~postinstall: @nativescrip| [            ......]
\ postinstall: info lifecycle @nativescript/android@7.0.1~postinstall:
@nativescrip+ @nativescript/android@7.0.1
added 1 package and audited 806 packages in 3.684s
-
33 packages are looking for funding
  run `npm fund` for details

found 2 vulnerabilities (1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Platform android successfully added. v7.0.1
Preparing project...
Compiling @angular/core : module as esm2015
Compiling @angular/animations : module as esm2015
Compiling @angular/animations/browser : module as esm2015
Compiling @angular/common : module as esm2015
Compiling @angular/platform-browser : module as esm2015
Compiling @angular/router : module as esm2015
Compiling @angular/forms : module as esm2015
Compiling @angular/platform-browser/animations : module as esm2015
Compiling @angular/common/http : module as esm2015
Compiling @nativescript/angular : module as esm2015
File change detected. Starting incremental webpack compilation...

webpack is watching the files…

Hash: c79a733a2289cfd2e13e
Version: webpack 4.44.2
Time: 23661ms
Built at: 2021-01-05 21:24:33
              Asset      Size   Chunks             Chunk Names
          bundle.js  43.9 KiB   bundle  [emitted]  bundle
       package.json  1.46 KiB           [emitted]
         runtime.js  77.1 KiB  runtime  [emitted]  runtime
tns-java-classes.js   0 bytes           [emitted]
          vendor.js  17.1 MiB   vendor  [emitted]  vendor
Entrypoint bundle = runtime.js vendor.js bundle.js
[../$$_lazy_route_resource lazy recursive] ../$$_lazy_route_resource lazy
namespace object 160 bytes {bundle} [built]
[./app.css] 2.03 KiB {bundle} [built]
[./app/app-routing.module.ts] 1.27 KiB {bundle} [built]
[./app/app.component.ts] 853 bytes {bundle} [built]
[./app/app.module.ts] 1.56 KiB {bundle} [built]
[./app/item/item-detail.component.ts] 2.02 KiB {bundle} [built]
[./app/item/item.service.ts] 1.74 KiB {bundle} [built]
[./app/item/items.component.ts] 1.91 KiB {bundle} [built]
[./main.ts] 2.3 KiB {bundle} [built]
[~/package.json] external "~/package.json" 42 bytes {bundle} [optional]
[built]
    + 548 hidden modules

WARNING in Zone.js does not support native async/await in ES2017+.
These blocks are not intercepted by zone.js and will not triggering change
detection.
See: https://github.com/angular/zone.js/pull/1140 for more information.
Webpack compilation complete. Watching for file changes.
Webpack build done!
Updating runtime package.json with configuration values...
Project successfully prepared (android)
Building project...
Gradle build...
File change detected. Starting incremental webpack compilation...
Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."

> Starting Daemon
Hash: 3bdbe28eb2df471c41ac
Version: webpack 4.44.2
Time: 1722ms
Built at: 2021-01-05 21:24:36
                               Asset      Size   Chunks
          Chunk Names
c79a733a2289cfd2e13e.hot-update.json  35 bytes           [emitted]
[immutable] [hmr]
                          runtime.js  77.1 KiB  runtime  [emitted]
           runtime
 + 2 hidden assets
Entrypoint bundle = runtime.js vendor.js bundle.js
[../$$_lazy_route_resource lazy recursive] ../$$_lazy_route_resource lazy
namespace object 160 bytes {bundle} [built]
    + 557 hidden modules
         + setting applicationId
         + applying user-defined configuration from
c:\Projects\web\tns\hello-world-2\App_Resources\Android\app.gradle
         + using android X library androidx.legacy:legacy-support-v4:1.0.0
         + adding nativescript runtime package dependency:
nativescript-optimized-with-inspector
         + adding aar plugin dependency:
C:\Projects\web\tns\hello-world-2\node_modules\@nativescript\core\platforms\android\widgets-release.aar

Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."
Detailed log here:
C:\Projects\web\tns\hello-world-2\platforms\android\build-tools\runSbg.log

<========-----> 61% EXECUTING [38s]

Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."
Detailed log here:
C:\Projects\web\tns\hello-world-2\platforms\android\build-tools\buildMetadata.log

Project successfully built.
The build result is located at:
c:\Projects\web\tns\hello-world-2\platforms\android\app\build\outputs\apk\debug\app-debug.apk
Installing on device 19129522504543...
Successfully installed on device with identifier '19129522504543'.
Restarting application on device 19129522504543...
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication:
com.tns.NativeScriptException: Application entry point file not found.
Please specify the file in package.json otherwise make sure the file
index.js or bootstrap.js exists.\nIf using typescript make sure your entry
point file is transpiled to javascript.
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application
com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application
entry point file not found. Please specify the file in package.json
otherwise make sure the file index.js or bootstrap.js exists.\nIf using
typescript make sure your entry point file is transpiled to javascript.
System.err:     at
android.app.ActivityThread.handleBindApplication(ActivityThread.java:5768)
System.err:     at android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1669)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6528)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err:     at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
System.err: Caused by: com.tns.NativeScriptException: Application entry
point file not found. Please specify the file in package.json otherwise
make sure the file index.js or bootstrap.js exists.\nIf using typescript
make sure your entry point file is transpiled to javascript.
System.err:     at com.tns.Module.bootstrapApp(Module.java:316)
System.err:     at com.tns.Runtime.run(Runtime.java:680)
System.err:     at
com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
System.err:     at
android.app.ActivityThread.handleBindApplication(ActivityThread.java:5765)
System.err:     ... 8 more
System.err: Caused by: com.tns.NativeScriptException: Failed to find
module: "./", relative to: app//
System.err:     at com.tns.Module.resolvePathHelper(Module.java:151)
System.err:     at com.tns.Module.bootstrapApp(Module.java:314)
System.err:     ... 12 more
Successfully synced application org.nativescript.helloworld2 on device
19129522504543.
Successfully transferred bundle.js on device 19129522504543.
Successfully transferred runtime.js on device 19129522504543.
Successfully transferred vendor.js on device 19129522504543.
Successfully transferred runtime.js on device 19129522504543.
Restarting application on device 19129522504543...
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication:
com.tns.NativeScriptException: Application entry point file not found.
Please specify the file in package.json otherwise make sure the file
index.js or bootstrap.js exists.\nIf using typescript make sure your entry
point file is transpiled to javascript.
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application
com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application
entry point file not found. Please specify the file in package.json
otherwise make sure the file index.js or bootstrap.js exists.\nIf using
typescript make sure your entry point file is transpiled to javascript.
System.err:     at
android.app.ActivityThread.handleBindApplication(ActivityThread.java:5768)
System.err:     at android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1669)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6528)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err:     at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
System.err: Caused by: com.tns.NativeScriptException: Application entry
point file not found. Please specify the file in package.json otherwise
make sure the file index.js or bootstrap.js exists.\nIf using typescript
make sure your entry point file is transpiled to javascript.
System.err:     at com.tns.Module.bootstrapApp(Module.java:316)
System.err:     at com.tns.Runtime.run(Runtime.java:680)
System.err:     at
com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
System.err:     at
android.app.ActivityThread.handleBindApplication(ActivityThread.java:5765)
System.err:     ... 8 more
System.err: Caused by: com.tns.NativeScriptException: Failed to find
module: "./", relative to: app//
System.err:     at com.tns.Module.resolvePathHelper(Module.java:151)
System.err:     at com.tns.Module.bootstrapApp(Module.java:314)
System.err:     ... 12 more
Successfully synced application org.nativescript.helloworld2 on device
19129522504543.

Op di 5 jan. 2021 om 13:15 schreef Igor Randjelovic <
notifications@github.com>:

**Comment by mapo80** [comment]
I've the same problem, how to solve?

**Comment by mapo80** [comment]
Solved installing latest nativescript cli!

**Comment by frunjik** [comment]
- what cli version are you using ?
- and what template are you generating ?

Op vr 8 jan. 2021 om 13:49 schreef mapo80 <notifications@github.com>:

**Comment by frunjik** [comment]
I solved this (with help)
By updating both angular and nativescript to latest versions
