### ISSUE TITLE
App Crash EXC_CRASH when being tested on App Store on iPad

### ISSUE THREAD

**Issue by aaayushsingh** [NativeScript/NativeScript#9137]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.1.1
 - Cross-platform modules: "@nativescript/core": "~7.0.0",
 - Android Runtime: NA
 - iOS Runtime: 7.1.0
 - XCode Version: 12.3 (12C33)
 - Plugin(s):
 ```
    "@nativescript/core": "~7.0.0",
    "@nativescript/geolocation": "^7.0.0",
    "@nativescript/localize": "^5.0.2",
    "@nativescript/nativescript-downloader": "git+https://github.com/aaayushsingh/nativescript-download.git",
    "@nativescript/theme": "~2.3.0",
    "@nstudio/nativescript-checkbox": "^2.0.4",
    "@nstudio/nativescript-loading-indicator": "^4.0.0",
    "crypto-js": "^4.0.0",
    "moment": "^2.29.1",
    "nativescript-audio": "git+https://github.com/aaayushsingh/nativescript-audio.git",
    "nativescript-headset-detection": "^1.0.0",
    "nativescript-insomnia": "^1.2.1",
    "nativescript-iqkeyboardmanager": "^1.2.0",
    "nativescript-permissions": "^1.3.7",
    "nativescript-ripple": "^4.0.1",
    "nativescript-screen-orientation": "^2.0.0",
    "nativescript-sound-kak": "^1.1.1",
    "nativescript-sqlite": "^2.6.6",
    "nativescript-ui-listview": "^9.0.4",
    "nativescript-zip": "^3.0.2"
```

**Describe the bug**

App works well locally, and on TestFlight. Even tried an AdHoc distribution of the binary and everything works fine. 
Tried on multiple iPads on our side and works fine.

However, when submitted to App Store for approval, the app crashes multiple times on their side

(3 crash logs attached)

**To Reproduce**
1. Submit app to app store, they somehow crash it for you

(checked backed logs for API calls, no calls at the time of the crash mentioned in the crash logs)

**Expected behavior**
No crash

**Sample project**
NA
**Additional context**
[attachment.crashlog-1.txt](https://github.com/NativeScript/NativeScript/files/5774755/attachment.crashlog-1.txt)
[attachment.crashlog-2.txt](https://github.com/NativeScript/NativeScript/files/5774756/attachment.crashlog-2.txt)
[attachment.crashlog-3.txt](https://github.com/NativeScript/NativeScript/files/5774757/attachment.crashlog-3.txt)

**Comment by janoshrubos** [comment]
did this release solve your crash issue? https://github.com/NativeScript/ns-v8ios-runtime/issues/98

**Comment by aaayushsingh** [comment]
@janoshrubos  couldn't get much help from that release. However when I enabled bitcode when building the app, it somehow didn't crash in App Store review. 

NativeScript/ns-v8ios-runtime/issues/104#issuecomment-776510680

**Comment by janoshrubos** [comment]
@aaayushsingh thank you for your response! i'm glad you found a solution
