### ISSUE TITLE
Nativescript could not load bundle .... SensorKit.framework

### ISSUE THREAD

**Issue by 7ammer** [NativeScript/NativeScript#9139]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.1.2
 - Cross-platform modules: "@nativescript/core": "~7.1.0",
 - iOS Runtime: "@nativescript/ios": "7.1.0",
 - XCode Version: Version 12.2 (12B45b)
 - Plugin(s): no extra plugins

**Describe the bug**
```
NativeScript could not load bundle file:///Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%2011.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/SensorKit.framework
```
```
NativeScript could not load bundle  file:///Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%2013.3.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/SensorKit.framework
```

**To Reproduce**
This comes up in the console when running `ns run ios`.
Create a new project `ns create`. I've tried vue and typescript projects
`ns run ios` on a iOS simulator running 11.4 or 13.3. Those are the versions I have tested so far.

**Expected behavior**
Does not appear in console.

**Comment by 7ammer** [comment]
After uninstalling xcode12.2 and command tools and reinstalling xcode12.3 and command tools. I get the same error in iOS13.3

**However**, I do not get the error in iOS14.3.

**Comment by jessorlisa** [comment]
Same here: https://github.com/NativeScript/ios-runtime/issues/1281

**Comment by hypery2k** [comment]
any ideas? @NathanaelA maybe?

**Comment by hypery2k** [comment]
Try to get the stack trace, just make sure in your src/package.json that discardUncaughtJsExceptions: false and you should see a more concrete error
see also #8865

**Comment by NathanaelA** [comment]
To my knowledge it is a bogus error because the SensorKit metadata is included in the application and iOS tries to load the dylib and fails.  However, it has no effect unless you are actually using the SensorKit API (which I believe is only available on real devices and then it should work...)

**Comment by hypery2k** [comment]
correct. With the discard discardUncaughtJsExceptions I found the real error in my app. In my case it's the googlemaps plugin
