### ISSUE TITLE
Feature: IntelliJ/Webstorm IDE support

### ISSUE THREAD

**Issue by dapriett** [NativeScript/NativeScript#914]
IntelliJ (and Webstorm) support would be great with Nativescript since it's a very popular Javascript IDE.  Specifically being able to debug directly from the IDE.  You can currently debug NodeJS apps, so maybe there is a way to hook the Nativescript debugging as well with a plugin.

**Comment by N3ll** [comment]
You can vote for this idea here https://nativescript.ideas.aha.io/ideas/NS-I-70.

**Comment by valentinstoychev** [comment]
Please add your votes on the WebStorm ideas portal to increase the priority of this feature - https://youtrack.jetbrains.com/issueMobile/IDEA-140751

**Comment by enchev** [comment]
Hey folks,

I'm closing this since we cannot do much from our side. Please use our Visual Studio Code extension to debug your NativeScript applications and/or vote for this feature on JetBrains portal.

Thanks

**Comment by enchev** [comment]
There is a plugin already! More info:
https://twitter.com/iguissouma/status/770725676508909569
https://twitter.com/iguissouma/status/770954567546789889
