### ISSUE TITLE
Why tns doctor is showing different results in different directories?

### ISSUE THREAD

**Issue by GAGANsinghmsitece** [NativeScript/NativeScript#9143]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.4
 - Cross-platform modules: No Such Modules
 - Plugin(s):No Plugin

**Describe the bug**

I setup nativescript on ubuntu. On running tns doctor in root directory I get

    ubuntu@ubuntu-ck0xxx:~$ tns doctor
    ⠦ Getting environment information ✔ Getting environment information 

    No issues were detected.
    ✔ Your ANDROID_HOME environment variable is set and points to correct directory.
    ✔ Your adb from the Android SDK is correctly installed.
    ✔ The Android SDK is installed.
    ✔ A compatible Android SDK for compilation is found.
    ✔ Javac is installed and is configured properly.
    ✔ The Java Development Kit (JDK) is installed and is configured properly.
    ✔ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
    ✔ Getting NativeScript components versions information...

but when I run this command in /Projects/nativescript/test/ i get following output

    ubuntu@ubuntu-ck0xxx:~/Projects/nativescript/test$ tns doctor
    ✔ Getting environment information 

    There seem to be issues with your configuration.
    ✔ Getting NativeScript components versions information...
    ✔ Javac is installed and is configured properly.
    ✔ The Java Development Kit (JDK) is installed and is configured properly.
    ✔ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
    ✖ The ANDROID_HOME environment variable is not set or it points to a non-existent directory.  You will not be able to perform any build-related operations for Android. 
     To be able to perform Android build-related operations, set the `ANDROID_HOME` variable to point to the root of your Android SDK installation directory. 

    ✖ WARNING: adb from the Android SDK is not installed or is not configured properly.  
    For Android-related operations, the NativeScript CLI will use a built-in version of adb.
    To avoid possible issues with the native Android emulator, Genymotion or connected
    Android devices, verify that you have installed the latest Android SDK and
    its dependencies as described in http://developer.android.com/sdk/index.html#Requirements 

    ✖ WARNING: The Android SDK is not installed or is not configured properly. 
     You will not be able to run your apps in the native emulator. To be able to run apps
    in the native Android emulator, verify that you have installed the latest Android SDK 
    and its dependencies as described in http://developer.android.com /sdk/index.html#Requirements 

    ✖ Cannot find a compatible Android SDK for compilation. To be able to build for Android, install Android SDK 28 or later. 
     Run `$ sdkmanager` to manage your Android SDK versions. 

    ✖ You need to have the Android SDK Build-tools installed on your system. You can install any  version in the following range: '>=23 <=30'. 
     Run `$ sdkmanager` from your command-line to install required `Android Build Tools`. In case you already have them installed, make sure `ANDROID_HOME` environment variable is set correctly. 

    Your environment is not configured properly and you will not be able to execute local  builds.

**To Reproduce**
I setup nativescript on ubuntu 20.04 using [this link](https://docs.nativescript.org/start/ns-setup-linux).Then I create nativescript project using 
    tns create test

**Expected behavior**
In project folder, `tns doctor` should show that all configuration are correct

**Comment by rigor789** [comment]
What does `echo $ANDROID_HOME` print? You may have a relative path in there - which works from your home directory, but not the project directory (ie. points to a non-existent directory).

**Comment by GAGANsinghmsitece** [comment]
I changed 

     export ANDROID_HOME="local/android/sdk/"
to

    export ANDROID_HOME="/local/android/sdk/"
but now it's failing in home directory too

**Comment by rigor789** [comment]
@GAGANsinghmsitece change it to the actual path, find where it is - probably `/usr/local/android/sdk/` (just like in the doc you linked). If `/local/android/sdk/` is not an existing path - then there's no way for any tool to find the android sdk there.

**Comment by GAGANsinghmsitece** [comment]
I changed it to 

    /home/usr/local/android/sdk

now it works
