### ISSUE TITLE
Android has broken styles on different devices

### ISSUE THREAD

**Issue by georgemark0v** [NativeScript/NativeScript#9146]
"@nativescript/android": "7.0.1"
"@nativescript/types": "7.0.0"

Android 8.0.0
https://yadi.sk/i/LenDLxmQLN1xkg

Android 9.0.0
https://yadi.sk/i/fsAEHlsoUN1Y0w

1. NavigationBack icon set as image and has different sizes on devices
2. Manually setting separator via css property border-bottom-width: 0.1 - looks different

On first screenshot (android 8) its looks as expected but on android 9 its all broken.

Also when trying to set system Icons (drawable with prefix ic) it's rendered outlined, how i can make them filled?
https://yadi.sk/i/k3F4vs3EELrXMA

**Comment by rigor789** [comment]
Share your code for the layout - and keep in mind that different devices have different pixel densities, so if you used `px` values in your app, things may look different across devices.
