### ISSUE TITLE
HMR does not work in NS Angular

### ISSUE THREAD

**Issue by Bezlepkin** [NativeScript/NativeScript#9149]
HRM does not work in NS Angular. After saving the code, I get a white screen.
Fresh app.

- CLI: 7.1.2

**Comment by nignucial** [comment]
Got the same issue with fresh app from template `@nativescript/template-blank-ng` @ `7.0.8` 😢

**Comment by mapo80** [comment]
Same here!

**Comment by AgustinV08** [comment]
With version 11.0.1 of @nativescript/angular, hmr should work now

**Comment by Bezlepkin** [comment]
Thanks!

I'm trying to do audio control from the lock screen.
[image: 2021-01-25_10-00-06.png]
.addTargetAction() // Accepts two parameters, target: any, action: string
[image: 2021-01-25_10-02-09.png]

I don't understand what is meant by target and action params.

сб, 23 янв. 2021 г. в 02:11, Agustin Villanueva <notifications@github.com>:

**Comment by Bezlepkin** [comment]
Yes, it works!
