### ISSUE TITLE
Pass data to webview

### ISSUE THREAD

**Issue by paulocarvalhodesign** [NativeScript/NativeScript#915]
Guys thanks for the awesome platform.
As I have not found a library for charting for Nativescript I when ahead and implemented my charts on an app I'm building with webview.
Works fine but a couple of things I can't quite achieve yet:
Pass Json object to webview, render webview transparent.
I solved the transparency by using same background as the page but I would like to know how to get Json into that webview.

Many thanks for any help in advance.
Paulo

**Comment by x4080** [comment]
In native mode there is javsscript call that can pass parameter, maybe you can check out the native code. I ve been thinking about using svg for displaying chart but the data is from the server. You run html locally?

**Comment by enchev** [comment]
Hey @paulocarvalhodesign,

You can access native WebView via [```android```](https://github.com/NativeScript/NativeScript/blob/master/ui/web-view/web-view.d.ts#L31) and [```ios```](https://github.com/NativeScript/NativeScript/blob/master/ui/web-view/web-view.d.ts#L36) properties and call directly methods like [```stringByEvaluatingJavaScriptFromString```](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIWebView_Class/) for iOS and [```loadUrl``` for Android with "javascript:" urls](http://stackoverflow.com/questions/12490789/how-to-pass-a-string-value-to-webview-from-an-activity). 

HTH
