### ISSUE TITLE
`tns create` keeps failing

### ISSUE THREAD

**Issue by FeezyHendrix** [NativeScript/NativeScript#9152]
**Describe the bug**
# Let’s create a NativeScript app!

Answer the following questions to help us build the right app for you. (Note: you
can skip this prompt next time using the --template option, or the --ng, --react, --vue, --svelte, --ts, or --js flags.)

✔ First, what will be the name of your app? … newboss

✔ Next, which style of NativeScript project would you like to use: › Angular

✔ Finally, which template would you like to start from: › SideDrawer
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @nativescript/template-drawer-navigation-ng@7.0.6
npm ERR! Found: zone.js@0.11.3
npm ERR! node_modules/zone.js
npm ERR!   zone.js@"~0.11.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer zone.js@"~0.10.3" from @angular/core@11.0.9
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"~11.0.0" from the root project
npm ERR!   peer @angular/core@"11.0.9" from @angular/animations@11.0.9
npm ERR!   node_modules/@angular/animations
npm ERR!     @angular/animations@"~11.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/mac/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2021-01-18T16_27_14_082Z-debug.log
Command npm failed with exit code 1

**To Reproduce**
tns create

**Expected behavior**
Create a nativescript angulat side drawer project

**Comment by rigor789** [comment]
What's your `npm -v` & `node -v` versions? 

I believe this may be related to latest npm changes - making installs a bit more strict around peer dependencies.

**Comment by FeezyHendrix** [comment]
Npm: 7.0.15
Node: v15.4.0

**Comment by rigor789** [comment]
Can you try with npm 6.x in the meantime? 

We need to figure out the deal with npm 7.x - I've seen many issues around many tools due to it introducing stricter checks.

**Comment by FeezyHendrix** [comment]
Worked like a charm
