### ISSUE TITLE
ObservableArray splice not clearing array as expected

### ISSUE THREAD

**Issue by matthewianmorgan** [NativeScript/NativeScript#9157]
**Environment**
 - CLI: 7.1.2

**Describe the bug**
Attempting to clear an ObservableArray with splice(0) does nothing.

**To Reproduce**
```
const _array = new ObservableArray();
_array.push(1);
_array.splice(0);
// _array.length !== 0
```

**Expected behavior**
Array length should be zero.

**Additional context**
It seems that calling Array.splice(0, undefined) does nothing.

**Comment by NathanWalker** [comment]
closed via https://github.com/NativeScript/NativeScript/pull/9159
On `next` tag shortly and will be released with a patch including number of core feat/fix this upcoming week.
