### ISSUE TITLE
building a tvOs app

### ISSUE THREAD

**Issue by mrjeremy28** [NativeScript/NativeScript#917]
I'm pretty new to NativeScript, but noticed the power it has to deploy to multiple platforms using a single code base. I've used JavaScript before and am looking in creating a quiz like app that uses mobile devices as controllers.
I'll be using a nodejs backend for all of the APIs, but trying to get the main TV app up and running and am looking for any guidance.

**Comment by fealebenpae** [comment]
Hi @mrjeremy28 

Right now we don't support tvOS like we do iOS and Android, but there is a sample project with the NativeScript runtime for tvOS [here](https://github.com/nativescript/sample-tvos) that you can play with.

**Comment by enchev** [comment]
This issue was moved to NativeScript/ios-runtime#365
