### ISSUE TITLE
Cannot use copy-to file after Nativescript compile

### ISSUE THREAD

**Issue by mrwrighty** [NativeScript/NativeScript#9181]
When running ns build ios --release --for-device --provision PhoneGap —-copy-to myfile.ipa

I'm getting an error: -

The arguments '—-copy-to myfile.ipa' are not valid for the current command.

Help shows the option is still valid.

**Comment by rigor789** [comment]
`--copy-to myFile.ipa` should work fine - I'm using it with latest everything. In your message, you have a long dash, perhaps that's an issue? 

```
—-copy-to
vs
--copy-to
```

**Comment by mrwrighty** [comment]
Ha thanks for that, but very odd from my end. I had copy and pasted the ns build line which clearly shows double -, but pasting seems to have screwed it. Cheers
