### ISSUE TITLE
[iOS] Orientation change issue Tabs

### ISSUE THREAD

**Issue by jessorlisa** [NativeScript/NativeScript#9185]
**Environment**
 - CLI: `├── nativescript@7.1.2`
 - Cross-platform modules: `@nativescript/core@7.1.4`
 - Android Runtime: -
 - iOS Runtime: `├── @nativescript/ios@6.5.4` (JSC)
 - XCode Version: `Xcode 12.2 (12B45b)`
 - Plugin(s):
   `├── @nativescript/angular@11.0.1`
   `├── @nativescript/theme@2.3.4`
   `├── @nativescript/webpack@4.0.1`
   `├── nativescript-ui-sidedrawer@9.0.3`

**Describe the bug**
Changing the device orientation with simple `Tabs` setup causes the UI and app to be unresponsive. Sadly there are no logs. Only reproducible when using the `Angular Drawer Navigation Template` as app template.

**To Reproduce**
- Setup sample project (see below)
- `ns clean && ns run ios --no-hmr`
- Change the screen orientation on Home > everything is fine
- Navigate to "Browse" (via the side drawer) > Tabs layout
- Change the orientation again > Voilà (should it work first, change the orientation a few times).

**Expected behavior**
Working.

**Sample project**
https://github.com/jessorlisa/issue-drawer-tabs-orientation

**Additional context**
Sadly I have absolutely no clue what is causing this and how to fix or debug it. Any help is appreciated.
Let me know if you need anything else from me.

**Comment by jessorlisa** [comment]
I narrowed it down to the wrapping GridLayout. 

Changing from

```
<ActionBar>
    <!-- inner content removed for clarity -->
</ActionBar>

<GridLayout class="page__content">
    <Tabs selectedIndex="1">
        <!-- inner content removed for clarity -->
    </Tabs>
</GridLayout>
```

to


```
<ActionBar>
    <!-- inner content removed for clarity -->
</ActionBar>

<Tabs selectedIndex="1">
    <!-- inner content removed for clarity -->
</Tabs>
```
seems to solve the issue.

Not sure if it should be working when wrapped inside another layout container. If not, let me know and I will close the ticket.

**Comment by shirakaba** [comment]
> Not sure if it should be working when wrapped inside another layout container. If not, let me know and I will close the ticket.

I can't comment on expected behaviour when changing device orientation or when using Android, but the docs do show use of BottomNavigation as a direct child of GridLayout, so I'd expect Tabs (a close cousin of BottomNavigation) to work fully as a child of GridLayout, too:

https://docs.nativescript.org/core-concepts/nested-navigation

![image](https://user-images.githubusercontent.com/14055146/106597919-f0fe8a80-654e-11eb-896b-9dd82094a73b.png)

**Comment by jessorlisa** [comment]
@shirakaba Thanks. As Tabs/BottomNavigation are removed from the core with {N}8 I will close this ticket.
