### ISSUE TITLE
Tappable Span on IOS are not working

### ISSUE THREAD

**Issue by alexist** [NativeScript/NativeScript#9189]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ CLI: 7.1.2
✔ Xcode version 12.4.0 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.1.2 version and is up to date.
⚠ Update available for component @nativescript/core. Your current version is 7.0.13 and the latest available version is 7.1.4.
✔ Component @nativescript/ios has 7.1.1 version and is up to date.
✔ Component @nativescript/android has 7.0.1 version and is up to date.

**Describe the bug**
Tappable link are not working correctly on IOS when there is several span.

The "link" doesn't work  on Ios, but work on android. 

```
    <Label>
        <FormattedString>
            <Span
                    text="This is a"></Span>
            <Span (linkTap)="openLink()"
                  color="red"
                  text=" link"></Span>
       </FormattedString>
   </Label>
```

The method openLink is not executed 

```
 openLink() {
        console.log('openlink');
  }
```

Without the first Span, "link" is tappable : 
```
    <Label>
        <FormattedString>
            <Span (linkTap)="openLink()"
                  color="red"
                  text=" link"></Span>
        </FormattedString>
    </Label>
```

**Comment by alexziskind1** [comment]
Just adding to this issue, which I also experienced. 
When I have two Span elements with linkTap in the FormattedString, the first one works, but the second doesn't.

**Comment by farfromrefug** [comment]
@alexziskind1 @alexist I know it works on my @nativescript-community/ui-label. I don't use N Label. 
I am not saying use my comp. but you can compare the code to see why it works there

**Comment by NathanaelA** [comment]
Verified this is a core issue; not a Angular issue.
The link calculation code is not working on ios and returning the wrong character index, which then calls the wrong linktap handler.

The broken function is in text-base/index.ios.ts - The source code links to this stackoverflow article:
https://stackoverflow.com/questions/1256887/create-tap-able-links-in-the-nsattributedstring-of-a-uilabel/35789589#35789589

I don't see anything obviously wrong, not sure if it is a iOS 14 change, or something else we changed on the label component...   Did test both NS 6 & 7 runtimes, no change...

**Comment by alexziskind1** [comment]
@farfromrefug trying your @nativescript-community/ui-label. Does it support multiple urls in one label? Seems like there is only one link handler per label.
Also, it doesn't seem to be able to handle different fonts, even though there is a fontFamily property. Even the example with OpenSans doesn't actually show OpenSans. Is this incorrect?

**Comment by farfromrefug** [comment]
@alexziskind1 yes it does either through span or HTML.
only one listener is enough.
yes it supports fonts. though it has a highly optimize font loader which might be failing in your case. I need to know your font filenames and family you use in the app.
we can chat on slack.

BTW I think my plugin might be working differently than N one because it does not use UILabel but UITextView instead
