### ISSUE TITLE
The file “app” couldn’t be opened because you don’t have permission to view it.

### ISSUE THREAD

**Issue by alexisconsuegra** [NativeScript/NativeScript#9192]
Details

The file “My.app” couldn’t be opened because you don’t have permission to view it.
Domain: NSCocoaErrorDomain
Code: 257
Failure Reason: You don’t have permission.
Recovery Suggestion: To view or change permissions, select the item in the Finder and choose File > Get Info.
User Info: {
    NSFilePath = "/Users/alexis/Library/Developer/Xcode/DerivedData/My-bngsswacwmraecgrvizldrhmbyid/Build/Products/Debug-iphonesimulator/My.app";
}
--
The operation couldn’t be completed. Permission denied
Domain: NSPOSIXErrorDomain
Code: 13
Failure Reason: Permission denied
--

System Information

macOS Version 10.15.6 (Build 19G2021)
Xcode 11.6 (16141)

**Comment by kantan-florian** [comment]
Hi Alexis,

did you do something special to resolve this issue? I have the same problem...

Thanks,
Florian

**Comment by alexisconsuegra** [comment]
Hi @kantan-florian 
No, I did not find the way to solve it and gave up trying the simulator. I am using a real device.

**Comment by kantan-florian** [comment]
I solved it for my case, but since it worked for you on a real device, we probably don't have the same issue. I reset the CFBundleExecutable value to ${EXECUTABLE_NAME} in my info.plist file. I changed that accidentally and that leaded to lot of issues.
