### ISSUE TITLE
Nested ListView

### ISSUE THREAD

**Issue by truongsinh** [NativeScript/NativeScript#92]
I am trying to have nested list view, like this
```xml
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
    <StackLayout>
        <ListView
            items="{{ postList }}"
            >
            <ListView.itemTemplate>
                <!-- Binding in template property of an component will use the bindingContext provided by the component. -->
                <StackLayout orientation="vertical">
                    <Image src="{{ imageCache }}" cssClass="post-image" stretch="aspectFill"/>
                    <Label text="{{ title || 'Untitled' }}" textWrap="true" cssClass="title"/>
                    <Label text="{{ body }}" cssClass="author" /> 
                    <!-- empty array for demonstration purpose -->   
                    <ListView items="{{ [] ]}}">
                        <ListView.itemTemplate>
                            <StackLayout orientation="vertical">
                                <Label text="abc" />
                        </StackLayout>
                        </ListView.itemTemplate>
                    </ListView>
                    </StackLayout>
                <!-- End of tempplate. -->
            </ListView.itemTemplate>
        </ListView>
    </StackLayout>
</Page>
```
but i have fatal error:
```
/app/tns_modules/ui/list-view/list-view.js:205:17: JS ERROR TypeError: undefined is not a function (evaluating 'value.replace('xmlns="http://www.nativescript.org/tns.xsd"', "")')
```

**Comment by enchev** [comment]
Please get the latest modules from master branch and let us know how it goes!

**Comment by truongsinh** [comment]
will do

**Comment by truongsinh** [comment]
Too bad, the same error even with 1.0-rc

**Comment by enchev** [comment]
This code is [improved in our latest commits](https://github.com/NativeScript/NativeScript/blob/master/ui/builder/builder.ts#L163). Can you check with the latest modules from master branch?

**Comment by froyke** [comment]
The code is not crashing now - but no items in the list view are displayed. When commenting out the inner ListView - everything works back again.

**Comment by truongsinh** [comment]
@duongnhatduy can you confirm with https://github.com/NativeScript/NativeScript/blob/master/ui/builder/builder.ts#L163

**Comment by dtopuzov** [comment]
Hi,

Unfortunately nested ListView currently is not supported scenario due to some limitations in native platforms. You can try to achieve such scenario with [Repeater](https://docs.nativescript.org/layouts#repeating-layout-children) component.

**Comment by duongnhatduy** [comment]
I already tried with Repeater, it doesn't work either. But thanks for the heads up
