### ISSUE TITLE
Background color not updating properly

### ISSUE THREAD

**Issue by cityinspain** [NativeScript/NativeScript#9207]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.11
 - Android Runtime: 7.0.1
 - iOS Runtime: N/A
 - XCode Version: N/A
 - Plugin(s): nativescript-ui-sidedrawer

**Describe the bug**

Background color of sidedrawer items is not removed when -selected class is removed.
 
**To Reproduce**

Generate a new app from a template with `nativescript-ui-sidedrawer`, and update `@nativescript/core` package to 7.2.1

**Expected behavior**

When an item loses the -selected class, the background color is reset. 

**Sample project**

https://github.com/cityinspain/ns-test-space

**Additional context**
Screenshot of the behavior
<img src="https://user-images.githubusercontent.com/21955158/107582724-ef286d00-6bc7-11eb-8f6b-2ed7da3ce14e.png" width="400"></img>

I've fixed the underlying issue, and will submit a PR.

**Comment by farfromrefug** [comment]
@cityinspain just saw your issue after my comment. will try to reproduce.

**Comment by jwrascoe** [comment]
@farfromrefug thanks for looking into this, we noticed this in the latest release of {N}... @cityinspain tracked it down and we both were trying to understand the true intention of the code change that went in.

**Comment by farfromrefug** [comment]
@jwrascoe so you understand before that change every single view was using a `BorderDrawable`  even when simply using a backgroundColor. But sometimes `BorderDrawable` is slow to create and unecessary. That PR made it so that it is used only when necessary.

**Comment by cityinspain** [comment]
This issue is actually fixed in master, at [this commit](https://github.com/NativeScript/NativeScript/commit/4b96d4baa03d23b0488ec724f123caf2cb81a5f5), where the change in `style-scope.ts` stopping the batch update if there are no matching selectors is reverted. However, that fix isn't in the latest 7.2.1 release. So, this issue is already fixed, it's just waiting to be released.

**Comment by farfromrefug** [comment]
@cityinspain damn so that issue again! damn I created side effects with this :s
I am adding tests to prevent this from happening again in the featuee
