### ISSUE TITLE
ns debug iOS failing, but ns build iOS and Xcode build working

### ISSUE THREAD

**Issue by mrwrighty** [NativeScript/NativeScript#9213]
Running Nativescript on MacOS 10.15.7

Just upgraded app from Nativescript 7.1.2 to 7.2
Core from 7.1.4 to 7.2.1
iOS from 7.1.1 to 7.2.0

Did ns migrate, ns update.

Tried ns clean

ns debug iOS now fails where previously it compiled. 
ns build ios --release --for-device works and I can build the project in Xcode from the workspace file.

Debug build fails with error ld: framework not found IQKeyboardManager
clang: error: linker command failed with exit code 1 (use -v to see invocation)
NSLD: Swift bridging header '*-Swift.h' not found under ... /Objects-normal/x86_64

Getting really annoyed that every update at the moment seems to break something. Its a very frustrating platform to work with.

**Comment by flipperlite** [comment]
First, cudos, thanks, and appreciation for the NativeScript team. I'm fairly new to the community but LOVE NativeScript. I hope I can begin contributing to this team and community. Unfortunately, I too agree that updates seem to break often. I backup often using Time Machine and manual backups since even Git commands/branches cannot restore back to a previously working state. I've seen Xcode error 65 too many times. Here is what I use when I experience ANY iOS or Xcode issue:

Confirm these command run:
```
xcodebuild -version
c++ --version
```

After any change to the environment (Xcode update, ns migrate, ns update, etc.), I run the following commands:
```
rm -rf ~/Library/Developer/Xcode/DerivedData/
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

**Comment by mrwrighty** [comment]
Thanks for the response. 

xcodebuild -version:-
Xcode 12.4
Build version 12D4e

c++ --version:-
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Applied the changes you suggested, but same error on debug.

**Comment by flipperlite** [comment]
First, make a full local backup of your repo. Next, I hope I don't further break your code and am just throwing out tips I've discovered. I've also had some luck with these commands and Cocoapods:
```
cd platforms/ios
# I believe reinstalls pods with current versions and assumes a Podfile exists. May need "pod init" to create Podfile.
pod install
# I believe will update the versions, but I've also broken it further
pod update
```
I've also tried complete uninstall and reinstall of Cocoapods, but this may have hurt my environment even more so I'm not recommending it unless it's a last ditch attempt.

**Comment by mrwrighty** [comment]
Thanks for posting, still same error I'm afraid.

**Comment by rigor789** [comment]
@mrwrighty possible to share the project? Everything working fine with all of our projects, so hard to tell what's going on with yours without looking!

**Comment by mrwrighty** [comment]
The code only exists on my laptop, not a git repository. How do I share otherwise.

**Comment by rigor789** [comment]
@mrwrighty if you zip up the project (excluding `node_modules`, `platforms`) you can send it to `igor (at) nstudio.io` referencing this issue, and I'd be happy to take a look.

**Comment by mrwrighty** [comment]
Thanks @rigor789 I've emailed the project.

**Comment by mrwrighty** [comment]
Have you had chance to look at the issues on this project and why it will not build for debug. Thanks

**Comment by rigor789** [comment]
Hey @mrwrighty - sorry, I got real busy last week - I'll try and take a look later today and get back to you!

**Comment by mrwrighty** [comment]
OK Many thanks, not a problem.

**Comment by minhnhut** [comment]
I used to have same problem.
How about:

```
ns platform remove ios && ns platform add ios
```

Btw, are you doing `ns debug ios` against Simulator or real device?

**Comment by rigor789** [comment]
The issue was an outdated plugin (drawer) in @mrwrighty's project

**Comment by minhnhut** [comment]
Great, thanks for let me know!
Btw, I think we should close resolved issues.
