### ISSUE TITLE
Nativescript 7 styling not resolving: Scss styles are compiling to bundle.js as css but no styles are displaying when running ns debug ios

### ISSUE THREAD

**Issue by pandabuilt** [NativeScript/NativeScript#9216]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  7.1.2
 - Cross-platform modules:
 - 
    "@nativescript/angular": "^10.0.0",
    "@nativescript/core": "^7.2.0",
    "@nativescript/schematics": "~1.0.0",
    "@nativescript/theme": "^3.0.1",
    "@nativescript/webpack": "~4.0.1",
 - Android Runtime:
    "@nativescript/android": "7.0.1",
 - iOS Runtime:
    "@nativescript/ios": "7.2.0",
 - XCode Version:12.1
 - Plugin(s):

**Describe the bug**
No css is displaying at all, however, bundle.js are displaying the css that gets compiled.  I am lazy loading routes. 

When I run --env.uglify css is there and not displaying when I don't include --env.uglify it errors:

CONSOLE ERROR: Error: Css styling failed: Error: undefined:1:16: Parse error: LeftCurlyBracket is expected
But I cannot find a single place where I'm missing a brack :( 

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by pandabuilt** [comment]
sass-resource-loader compiles mat-core weird.

**Comment by jonsabogal** [comment]
@pandabuilt I have an issue where my styles entered in component.ios.scss or component.ios.css are being ignored when running either "ns debug ios" or "ns run ios" The respective android scss or css files are being applied just fine (and I am importing a component-common.css into each one as shown in nativescript tutorial). Inline styling works fine for either platform. Any ideas?

Environment (package.json)
{
  "name": "@nativescript/template-tab-navigation-ng",
  "main": "main.js",
  "displayName": "Tabs",
  "templateType": "App template",
  "version": "7.0.6",
  "description": "NativeScript Application",
  "author": "NativeScript Team <oss@nativescript.org>",
  "license": "SEE LICENSE IN <your-license-filename>",
  "publishConfig": {
    "access": "public"
  },
  "keywords": [
    "nstudio",
    "nativescript",
    "mobile",
    "angular",
    "{N}",
    "tns",
    "template",
    "tab",
    "navigation",
    "category-general"
  ],
  "repository": "<fill-your-repository-here>",
  "homepage": "https://github.com/NativeScript/nativescript-app-templates",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "scripts": {
    "lint": "tslint \"src/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "~11.0.0",
    "@angular/common": "~11.0.0",
    "@angular/compiler": "~11.0.0",
    "@angular/core": "~11.0.0",
    "@angular/forms": "~11.0.0",
    "@angular/platform-browser": "~11.0.0",
    "@angular/platform-browser-dynamic": "~11.0.0",
    "@angular/router": "~11.0.0",
    "@nativescript/angular": "~11.0.0",
    "@nativescript/camera": "^5.0.8",
    "@nativescript/core": "~7.1.0",
    "@nativescript/firebase": "^11.1.3",
    "@nativescript/theme": "~2.3.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.6.0",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~11.0.0",
    "@nativescript/android": "7.0.1",
    "@nativescript/ios": "7.1.1",
    "@nativescript/webpack": "~4.0.0",
    "@ngtools/webpack": "~11.0.0",
    "codelyzer": "~6.0.0",
    "node-sass": "^4.14.1",
    "tslint": "~6.1.3",
    "typescript": "~4.0.0"
  },
  "private": "true",
  "readme": "NativeScript Application"
}

**Comment by dlcole** [comment]
@pandabuilt - did you ever resolve this?  I see you closed the issue, but I'm hitting the same problem as I try and migrate a large project from {N} 6.8 to 8.1.
