### ISSUE TITLE
NS 7 upgrade error -- ERROR in ../node_modules/debug/src/node.js

### ISSUE THREAD

**Issue by sido420** [NativeScript/NativeScript#9218]
I am getting an error switching from NS 6 to NS7. There are multiple issues but this is the first one I encountered.

**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.2.0
 - Cross-platform modules:
 - Android Runtime:
$ ns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.2.0 version and is up to date.
✔ Component @nativescript/core has 7.2.1 version and is up to date.
✖ Component @nativescript/ios is not installed.
✔ Component @nativescript/android has 7.0.1 version and is up to date.

 - Plugin(s):
```
  "dependencies": {
    "@bradmartin/nativescript-urlhandler": "^2.0.1",
    "@nativescript/background-http": "^5.0.1",
    "@nativescript/core": "^7.2.1",
    "@nativescript/geolocation": "^7.0.0",
    "@nativescript/iqkeyboardmanager": "^2.0.0",
    "@nativescript/secure-storage": "^3.0.0",
    "@nativescript/theme": "^2.5.0",
    "@nativescript/webpack": "3.0.0",
    "@nstudio/nativescript-exoplayer": "^5.0.5",
    "@nstudio/nativescript-https": "^3.0.1",
    "@nstudio/nativescript-loading-indicator": "^4.0.0",
    "@triniwiz/nativescript-toasty": "^4.1.3",
    "async": "^3.2.0",
    "dotenv": "^8.2.0",
    "emoji-js": "^3.5.0",
    "linkifyjs": "^2.1.9",
    "localforage": "^1.9.0",
    "localforage-memoryStorageDriver": "^0.9.2",
    "nativescript-contacts": "^1.6.2",
    "nativescript-downloader": "^2.1.5",
    "nativescript-feedback": "^2.0.0",
    "nativescript-mediafilepicker": "^4.0.2",
    "nativescript-oauth2": "^3.0.3",
    "nativescript-perms": "^2.0.11",
    "nativescript-theme-core": "^2.0.24",
    "nativescript-ui-autocomplete": "^7.0.2",
    "nativescript-vibrate": "^4.0.1",
    "nativescript-websockets": "^1.5.6",
    "svelte-native": "~0.9.5",
    "svelte-native-nativescript-ui": "^0.9.0"
  },
  "devDependencies": {
    "@nativescript/android": "7.0.1",
    "@nativescript/types": "^7.2.0",
    "@types/async": "^3.2.5",
    "@types/backbone": "^1.4.10",
    "@types/lodash": "^4.14.168",
    "node-sass": "^5.0.0",
    "svelte": "~3.32.3",
    "svelte-loader-hot": "~0.3.1",
    "svelte-native-preprocessor": "^0.2.0",
    "svelte-preprocess": "^4.6.9",
    "typescript": "^4.1.5"
  },
```

**Describe the bug**
I'm getting the following error:
```
ERROR in ../node_modules/debug/src/node.js
Module not found: Error: Can't resolve 'net' in '/nativescript/Test/node_modules/debug/src'
 @ ../node_modules/debug/src/node.js 193:16-30
 @ ../node_modules/debug/src/index.js
```
Looks like my code was dependent on 'net' module of node.js. However, that appears to have been removed from NS 7. Why?
Also, looking at the error line in code:
```
    case 'PIPE':
    case 'TCP':
      var net = require('net');        // <-- line 193
      stream = new net.Socket({
        fd: fd,
        readable: false,
        writable: true
      });
```

**To Reproduce**
See above

**Expected behavior**
I was expecting my code to work after changing plugin and module names at least. I did make some other changes to adjust the code.

**Sample project**
I will try to reproduce on a new project

**Additional context**
I am upgrading from 6.7.8 to 7.2.0

**Comment by rigor789** [comment]
`net` was never part of core, so not sure how this worked before?

It may be related to some other change you've done during the upgrade.

Looking at the error message, it appears to be coming from `node_modules` and not your code, so perhaps see what dependency that you updated pulls in the `debug` package?
