### ISSUE TITLE
Feature request: Add loading wheel to Dialogs module

### ISSUE THREAD

**Issue by alexrainman** [NativeScript/NativeScript#922]
I will love that {N} add a loading wheel dialog to block UI when long background task are executed.

**Comment by nsndeck** [comment]
{N} already have such functionality via `ActivityIndicator` control. For more information you can refer to [this help article](http://docs.nativescript.org/ApiReference/ui/activity-indicator/HOW-TO).

**Comment by nsndeck** [comment]
A little follow up: You can place `ActivityIndicator` in a [modal page](http://docs.nativescript.org/navigation#modal-pages). If your scenario is to block UI for user input.

**Comment by enchev** [comment]
Hi @alexrainman,

We've simplified our [showModal()](https://github.com/NativeScript/NativeScript/pull/954) - let us know if this can help in your case!

Thanks

**Comment by alexrainman** [comment]
I still thinking this need to be added to Dialogs module including some parameters to set the overlay mode opacity. Anyway, i wish you make it work this way :)

**Comment by enchev** [comment]
Hey @alexrainman,

I've just published custom dialog for {N}:
https://www.npmjs.com/package/nativescript-dialog

HTH

**Comment by enchev** [comment]
Here is also our verified plugin:
http://plugins.telerik.com/nativescript/plugin/custom-ui-dialog

**Comment by afortaleza** [comment]
@enchev Thank you very much, solved my problem very elegantly :+1:
