### ISSUE TITLE
missing fonts in ios

### ISSUE THREAD

**Issue by liuy97** [NativeScript/NativeScript#9221]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.2.0
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime: 7.2.0
 - XCode Version: 12.4
 - Plugin(s):

**Describe the bug**

font icons are missing

**To Reproduce**

ns create demo --template @nativescript/template-tab-navigation-ng
ns run ios
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-02-17 at 09 26 59](https://user-images.githubusercontent.com/2961144/108177079-0e148b00-7103-11eb-99e8-d73ece1cea63.png)

**Expected behavior**
font icons shows correctly

**Sample project**

**Additional context**

**Comment by bradmartin** [comment]
Could you try using `ns fonts` from your terminal to get the correct CSS for the fonts you have in your application? This was added to the CLI with NS 7.1 (https://nativescript.org/blog/nativescript-7-1-hmr-reenabled-and-xcode-12-3-support/)

If you have the CSS configured correctly it should render the fonts.

**Comment by liuy97** [comment]
Hi, the demo project is created from Tabs template. It seems font css is same as result of "ns fonts".
[.fab](https://github.com/NativeScript/nativescript-app-templates/blob/a81a737f4d7627d0d75772aba775b0505941210e/packages/template-tab-navigation-ng/src/_app-common.scss#L8)
`
.fab {
    font-family: "Font Awesome 5 Brands", "fa-brands-400";
    font-weight: 400;
}
`
This bug is that font files are not copied when "ns run ios" at the first time.

**Comment by bradmartin** [comment]
If the webpack config is using the latest and the fonts are in the correct directory then it should copy them over, that is handled with webpack bundling.

The issue of the template might be that the fonts are not in the correct directory for the copyTargets portion of the webpack config.

**Comment by bradmartin** [comment]
It seems that a second run of the app does copy the files over correctly. Could be a webpack issue or a IO issue. Hard to say, hopefully you can get past it though with a second run of the app and move forward.

**Comment by liuy97** [comment]
ns-cli 8.0.1 has fixed this.
