### ISSUE TITLE
Some Android devices not firing resume event when back from lock PIN -> destroys entire lifecycle after that

### ISSUE THREAD

**Issue by xtronoid** [NativeScript/NativeScript#9224]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `ns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules: 7.x
 - Android Runtime: 7.x
 - iOS Runtime:
 - XCode Version:
 - Plugin(s):

**Describe the bug**

if you do screen lock, no other lifecycle event will trigger resulting in total incompatibility (loaded events, hmr, plugins that even don´t rely on loaded but on lifecycle)

**To Reproduce**
### create a project, listen to application suspend resume... and just see the logs

**Expected behavior**
**Lock do suspend, unlock do resume**

**Additional context**

android 10 / xiaomi redmi note 7

Thanks, I really love this team!!!! You´re the best._

UPDATE/EDIT   _______________________________   READ BEFORE SCROLL THE THREAD)  _________________________________________

**After further research in this topic, the issue was summed into:**

**1. Some Android devices (e.g.: Xiaomi Redmi Note 7, probably related to MIUI), simply don´t trigger ResumeEvent event**

**2. Although this can look relatively inoffensive if you don´t directly rely on lifecycle (page loaded, release camera, camera mlkit, mapbox, to name  few), this goes further and breaks even hmr, in truth it breaks the entire lifecycle**

**3. to clarify better the point 2, minimize/switch works fine (suspend/resume), but, if you press lock, you will get 1 suspend, then no resume, and worse... NO MORE ANY LIFECYCLES AFTER IT. even from switch/minimize, or hmr, everything breaks after lock press...**

4. @NathanaelA **proposed a dedup retrig... i dunno, why not just abstract the event itself to be always based on lock detect via:**

```
KeyguardManager myKM = (KeyguardManager) context.getSystemService(Context.KEYGUARD_SERVICE);
if( myKM.inKeyguardRestrictedInputMode()) {
//it is locked
} else {
//it is not locked

}
```

**this would solve de-dup, and also it feels more secure, since resume will be really connected with lock being unlocked or no ( via pin, face, finger, whatever)... because, if you disable PIN, etc, this such devices works flawless.**

**Also i would like to reinforce that (im not low level coder), but in my imagination this should be fixed at the very ROOT of NativeScript, and not some poor attempt to fix plugin avoiding life cycle at all / then calling that java KeyguardManager API to try to ressucrrect the app, what i think it would be very strange, impossible, wrong or clunky... (because it would also breaks page loaded and HMR)....  and just be used at a last resort if no one comes with a PR.**

**Thanks in advance to all involved.**

**Comment by xtronoid** [comment]
FOR THOSE WHO WANNA TO VERIFY:

import { Application } from '@nativescript/core'

Application.on(Application.resumeEvent, event => {
    console.log('resume: lock/unlock never fires me, but switch/minimize always')
    console.log('resume: i will also not fire anymore if lock was used')
})

Application.on(Application.suspendEvent, event => {
    console.log('suspend: switch/minimize always suspend')
    console.log('suspend: since u never locked also')   
    console.log('suspend: if u start with lock, I NEVER FIRE')
    
    // AND YES, BREAK ALL PLUGINS THAT WAIT FOR THAT EVENTS INTERNALLY
})

**Comment by NathanaelA** [comment]
I created a test app using similar code earlier today; and it fired every time I locked or minimized and unlocked or restored the app.   

But my understanding is that some android phones don't actually trigger the system wide events properly (which then means NativeScript then won't see the event, since it didn't trigger it), and the `redmi` phones have some other weird android incompatibilities/issues, so it wouldn't surprise me if the redmi phone is the culprit here...

**Comment by xtronoid** [comment]
wow this is was my afraid!

but i just can´t believe that there´s no workaround?

**Comment by farfromrefug** [comment]
the first thing I would do is create a very simple android native app to check if you get the life cycle events

**Comment by xtronoid** [comment]
@farfromrefug is that example... i was thinking in test in ns6, but i can´t do ns platform add android@6, gives me error

**Comment by xtronoid** [comment]
@NathanaelA 

I found something now, researching

https://dontkillmyapp.com/xiaomi

**Comment by xtronoid** [comment]
this affects also the LOADED events stuff... so it breaks everything

**Comment by xtronoid** [comment]
in the last 3 months, thousand of hundreds of ppl in india and here in brazil are buying a lot of xiaomi´s, as huawei declines from the samsung war

**Comment by xtronoid** [comment]
it´s possible to adb log whatsapp to understand how they do?

**Comment by xtronoid** [comment]
@NathanaelA I found a clue now...

as i said, if i start using lock, it makes switch/minimize stops working also... as if it lost communication

now i did a further investigation and i found that, if i listen to this:


Application.android.on(AndroidApplication.activityPausedEvent, (event) => {
    console.log('interesting')
})

i see it fire once, when using lock, and just before everythings stops to listen...
seems like its needed to ressurrect app after pause, how i can try to do that?

**Comment by NathanaelA** [comment]
Pause/Suspend and Resume are the two standard android events, but if the device doesn't send them (which does happen with some devices).  

You can also on at least Android check for user activity to see if the Lock screen is active.   There is a API that allows you to get device state and if someone is using it or if the lock screen is locked.

**Comment by xtronoid** [comment]
I need to do that so, because i know that i will have many users using xiaomi including myself developing!
And I will never release IOS version, it´s part of our very big strategy

**Comment by xtronoid** [comment]
I found this now, on web:

KeyguardManager myKM = (KeyguardManager) context.getSystemService(Context.KEYGUARD_SERVICE);
if( myKM.inKeyguardRestrictedInputMode()) {
 //it is locked
} else {
 //it is not locked

}

if that works, how in the else it would can be ressurrected? app full restart? lol

**Comment by jerbob92** [comment]
> @farfromrefug is that example... i was thinking in test in ns6, but i can´t do ns platform add android@6, gives me error
> 
> tried 6.5 version, same problem

He's saying you might want to create a native app to see whether it's related to your device (if you don't get them on a native app either, then the problem isn't inside NS) or related to something in NS.

I'm also failing to understand what exactly kind of problems this causes? Can you explain that a little more and give some examples of plugins that break because of this? Xiaomi isn't new, and I didn't really hear about there problems before?

**Comment by xtronoid** [comment]
@jerbob92 hey bro, you really are gettin a very hard time understanding this, but im here to help...

I´ve just tested now in my old device (SAMSUNG J5), the lock works fine

but in xiaomi LOCK/UNLOCK only does 1 suspend, then nothing (all stops), even the switch/minimize suspend resume events that works fine if you don´t press LOCK BUTTON (power)

well, this disrputs hmr, loaded events of pages, and all plugins that relies in lifecycle, i dunno why you asking so hard for a redundant list of plugins if it´s nothing to do with plugins

Thanks

**Comment by jerbob92** [comment]
> @jerbob92 hey bro, you really are gettin a very hard time understanding this, but im here to help...
> 
> I´ve just tested now in my old device (SAMSUNG J5), the lock works fine
> 
> but in xiaomi LOCK/UNLOCK only does 1 suspend, then nothing (all stops), even the switch/minimize suspend resume events that works fine if you don´t press LOCK BUTTON (power)
> 
> well, this disrputs hmr, loaded events of pages, and all plugins that relies in lifecycle, i dunno why you asking so hard for a redundant list of plugins if it´s nothing to do with plugins
> 
> Thanks

If you're going to be condescending to me this will be my last reply to this issue. You do realize that I'm replying here because I want to help you to get this fixed? There's no need to write your messages like that.

I'm asking for more information to validate the implications of this issue, and to check whether I can find more information about this issue in these plugins that you are talking about to check if more people are having issues because of this. You should not assume that everyone here has the same information that's in your head. Reason I'm asking about plugins is because you said:

```
// AND YES, BREAK ALL PLUGINS THAT WAIT FOR THAT EVENTS INTERNALLY
```

That statements made me think that you know of plugins that are actively breaking because of this.

**Comment by xtronoid** [comment]
Sorry, bro :( was not my intention, we are trying to help each other, i´ve just got nervous thinkin you r not trusting my test, but i 
know that this things can be complicated.

For example, the new nativescript camera plus that relies in new fancy camera that have detection listeners, they are connected with lifecycle for stopping resuming activities

but independent of plugins, i need to listen resume and suspend to do stuff (which real app doesn´t)? and hmr stop working also, because hmr also have some connection with this...
this also even (as i said a million of times), loaded events...
for example when you rely in a loaded event to do something... the event is never more fired refreshed (even we programmers usually sometimes puts a lock on this with some kind of if( !booted ) stuff, but haha with this bug it´s not even needed, lol

**Comment by NathanaelA** [comment]
First @jerbob92 - I can tell you @xtronoid wasn't trying to be a problem, not everyone has a solid grasp of the intricacies of English.   Can't tell you how many times me and the Bulgaria Nativescript team would actually be in agreement but it would look like we were disagreeing because of word usage...

Now as to this issue:
It can break several plugins, as things like Exoplayer, mabbox use these events to detach the video view  when the screen is locked.  Unfortunately if the actual underlying platform is not actually sending the event properly, "we" probably can't really do anything about it, unless we can find another way to reliably detect the same.  

@xtronoid  - You might want to do some searches for `xiaomi` and `exoplayer` or `mapbox` and the pause & resume events and see how developers are handling these devices with 100% android java/kotlin apps.

**Comment by xtronoid** [comment]
and if NS abstract this? like always using lockdetect in parallel to switch minimize? then trigger "events" up above

**Comment by xtronoid** [comment]
Hey @NathanaelA in a flash of intuition i nailed the problem... what you guess i did?

i went to settings, and disabled xiaomi face detection, screen lock, pin, everything... is something related to security maybe... was the first thing i went after meditating about it

do you think you have an elegant way for we manage this common edge case? if you want i can try to isolate if it´s specific finger or face or pin, etc

**Comment by farfromrefug** [comment]
@xtronoid again I really think N community can't really help.you unless you pinpoint what is happening (or most probably what event is not fired). 
you should create an android native app. there you can log lifecyle events to see if you get them all.
once you be done that you can run The N app with lifecycle trace category and compare.

**Comment by xtronoid** [comment]
@farfromrefug i think you don´t read my last post

**Comment by xtronoid** [comment]
https://stackoverflow.com/questions/16771319/android-activity-ondestroy-called-on-screen-lock

i dunno if it´s related

**Comment by xtronoid** [comment]
I know that it´s hard to test on all devices, but i think it´s fundamental for us testing in devices, and i know that most of ppl don´t do  fullscreen/webgl/mlkit stuff that really depends on lifecycle things... but for common ppl and past ppl i understand that´s easy to don´t bother with messy and dirty retrigger of this kind of page loaded etc events... but for me, it´s impossible to even start an app without a robust clean lifecycle control monitoring

**Comment by xtronoid** [comment]
Yesterday i also tested battery optimization off for the ns app, but isn´t the case...

now i´ve found on Signal messenger forum, a lot of ppl complaining about this probably related problem, i think they don´t know... i think this is a kind of new bug to some app developers... but whatsapp knows how to deal... (but there´s no source code to sneak)

https://github.com/signalapp/Signal-Android/issues/9225

**Comment by xtronoid** [comment]
i dont wanna sound superticious here, but signal issue is 9225, and mine nativescript issue is 9224

**Comment by NathanaelA** [comment]
> I know that it´s hard to test on all devices, but i think it´s fundamental for us testing in devices, and i know that most of ppl don´t do fullscreen/webgl/mlkit stuff that really depends on lifecycle things... but for common ppl and past ppl i understand that´s easy to don´t bother with messy and dirty retrigger of this kind of page loaded etc events... but for me, it´s impossible to even start an app without a robust clean lifecycle control monitoring

Unfortunately if the device DOES not give us the notification, it is hard for us to really know.   The only way off the top of my head to really know in this case would be to run a notifier of some sort using something from https://stackoverflow.com/questions/8317331/detecting-when-screen-is-locked and then have it fire the pause/resume notification -- however we would have to make sure to de-dupe the notification so that you don't get two pauses and two resumes on the rest of the devices...

We would love to see a PR to add a listener like this to the framework @xtronoid as you have a phone to actually test this on.

**Comment by xtronoid** [comment]
Thanks Nathanael, i´m ready to do anything to help... even offer my machine as remote, with camera streaming my device, and me being controlled by your voice commands :D

**Comment by xtronoid** [comment]
i dont wanna sound superticious here, but signal issue is 9225, and mine nativescript issue is 9224

i think SIGNAL just don´t know, one day they will find by us, that isn´t battery but PIN, because I found this, and we nativescript solved signal and the rest of the world

IMHO

9224 < 9225, we found first even later in human time
prove us we are wrong
the first test i did yesterdey was disable bat sav, and the test i did today was disable security
i think it´s a nice security feature, and all androids developers DONT SHOULD RELY ANYMORE on resume, in my not so humble opinion as a high-level developer
but only using KeyManager JAVA API
maybe it´s the right way, abstracting pin, finger , face
maybe miui is better
maybe we are wrong
maybe everyone is wrong
maybe miui is more correct even by accident, or not, i dunno the intricacies of low level java android C++ ASSEMBLER

**Comment by xtronoid** [comment]
at the moment we will compare a empty native app, to check adb logs between PIN / no PIN, for trying to isolate more

**Comment by xtronoid** [comment]
https://imgur.com/a/okuO52L

even in native, PIN don´t fire anything
don´t fire suspend, neither resume
resume.. but as it first fire one, it´s the same strange behaviour that nativescript mimics
this is strange, because it breaks communication also
no more life even from switch minimize during the session that lock was pressed one time, because it suspends one time
then all native lifecycle halts

**Comment by VanderSP** [comment]
google lens resumes fine, but i cant make a native lifecycle works... some kind of whitelist or special technique???

**Comment by xtronoid** [comment]
After haunted nights thinkin about this issue, i´ve opened android studio again and found a little of hope:

1. logcat can listen to start resume always
2. adb can´t... is some issue related to adb losing connection when LOCK is pressed

this adb EOF is enough to make NS stop sending the lifecycle events after that...

there´s some special xiaomi option, or adb that doesn´t break the entire system? I´m pretty sure that other ppl will suffer the same thing... at least now things are getting nailed a bit

**Comment by xtronoid** [comment]
Sorry to all involved, @NathanaelA @farfromrefug @jerbob92 @triniwiz 

Finally, I found that with cable it works... somehow adb via wifi loses connection with some mobiles... i would like to confirm if it´s on windows in normal mode, or only in wsl2 im using... but probably it can be some related to mobile wifi battery optimization? i dunno... but i think this should be an alert to us avoiding future issues somehow...

and a tip: in wsl2 there´s a lot of issues with networking, and they are solving... but i was able to use via wifi

and i found in SO a workaround to cable, that wsl forum ppl probably don´t know

1. adb tcpip 5555 on windows side
2. adb kill-server / adb connect MOBILEIP:5555

it worked!
