### ISSUE TITLE
IOS App Crashing Soon After Splash (tried all possible Solutions)

### ISSUE THREAD

**Issue by Rmadhuprasanth** [NativeScript/NativeScript#9226]
App freezing  soon after launch screen .running on IOS 14 with platform IOS 6.5.0 (**thinking made  wrong decision choosing Nativescript** )
tried all possible solutions
 "tns-ios": {
      "version": "6.5.0"
    }

**Comment by bradmartin** [comment]
Could you possibly provide a sample repo where this occurs? If you could also provide the full `package.json` for the project that would help, if you cannot provide a sample repo to reproduce the crash you are experiencing.

**Comment by Rmadhuprasanth** [comment]
> Could you possibly provide a sample repo where this occurs? If you could also provide the full `package.json` for the project that would help, if you cannot provide a sample repo to reproduce the crash you are experiencing.

### `Package.json file`
{
  "nativescript": {
    "id": "xxxxxxxxx",
    "tns-android": {
      "version": "6.5.0"
    },
    "tns-ios": {
      "version": "6.5.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "lint": "tslint \"src/**/*.ts\""
  },
  "dependencies": {
    "@agm/core": "^1.1.0",
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript-rtl/ui": "^0.1.4",
    "@nativescript/theme": "~2.3.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "@types/jest": "^26.0.0",
    "guid-typescript": "^1.0.9",
    "jest": "^26.0.1",
    "nativescript-angular": "~8.21.0",
    "nativescript-autocomplete": "^1.0.0",
    "nativescript-background-http": "^4.2.1",
    "nativescript-camera": "^4.5.0",
    "nativescript-cardview": "^3.2.0",
    "nativescript-carousel": "^6.1.1",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-dna-deviceinfo": "^2.4.3",
    "nativescript-downloader": "^2.1.5",
    "nativescript-downloadmanager": "^0.1.0",
    "nativescript-drop-down": "^5.0.5",
    "nativescript-geocoding": "^2.0.1",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-gif": "^4.0.6",
    "nativescript-google-maps-sdk": "^2.9.1",
    "nativescript-google-places-autocomplete": "^1.0.3",
    "nativescript-here": "0.0.1",
    "nativescript-http-formdata": "^2.1.0",
    "nativescript-image-zoom": "^3.0.3",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-localstorage": "^2.0.1",
    "nativescript-mapbox": "^5.0.1",
    "nativescript-ng-shadow": "^2.1.0",
    "nativescript-pager": "^12.0.0-alpha.9",
    "nativescript-pdf-view": "^2.4.3",
    "nativescript-permissions": "^1.3.9",
    "nativescript-plugin-firebase": "^10.5.2",
    "nativescript-push-notifications": "^1.1.6",
    "nativescript-radial-gradient": "^0.8.0",
    "nativescript-range-seek-bar": "^1.0.3",
    "nativescript-share-file": "^1.0.6",
    "nativescript-sms-inbox": "^2.1.0",
    "nativescript-sms-receiver": "^1.0.1",
    "nativescript-social-share": "^1.6.0",
    "nativescript-star-ratings": "^1.0.0",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-ui-autocomplete": "^6.0.1",
    "nativescript-ui-chart": "^6.0.0",
    "nativescript-ui-gauge": "^6.0.0",
    "nativescript-ui-listview": "^8.2.0",
    "nativescript-ui-sidedrawer": "~8.0.0",
    "ng-otp-input": "^1.7.1",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.5.0",
    "tns-ng-gif": "^1.3.1",
    "ts-jest": "^26.1.0",
    "uuid": "^8.3.0",
    "uuid-generator-ts": "^1.0.4",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@nativescript/schematics": "^9.0.0",
    "@ngtools/webpack": "~8.2.0",
    "@schematics/angular": "^9.1.9",
    "codelyzer": "~4.5.0",
    "nativescript-dev-webpack": "~1.5.0",
    "node-sass": "^4.7.1",
    "tns-android": "6.5.0",
    "tns-ios": "6.5.0",
    "tns-platform-declarations": "^6.5.12",
    "tslint": "~5.19.0",
    "typescript": "~3.5.3"
  },
  "gitHead": "20a65d338ae8f8911087ab6615b89363f864b07b",
  "readme": "NativeScript Application"
}

**Comment by bradmartin** [comment]
Any reason you haven't bumped the `"tns-ios": "6.5.0",` to `6.5.4`? Possibly a bug fix was introduced that could correct this. Just first thoughts. Hopefully it's that simple :)

**Comment by Rmadhuprasanth** [comment]
> Any reason you haven't bumped the `"tns-ios": "6.5.0",` to `6.5.4`? Possibly a bug fix was introduced that could correct this. Just first thoughts. Hopefully it's that simple :)

![Screenshot 2021-02-20 at 2 21 59 AM](https://user-images.githubusercontent.com/46020760/108561032-94a7b300-7323-11eb-9a67-403c38156c76.png)

Thanks @bradmartin for quick response.
Getting same error after upgrading to "tns-ios": "6.5.4"

**Comment by bradmartin** [comment]
I think at this point we need to know what type of code you are executing on app start, then I can try to reproduce it.

**Comment by NathanWalker** [comment]
@Rmadhuprasanth that error is typical of an unfound dependency import or incorrect path to an imported file.

The most likely causes are:
1. A dependency you added which ended up in devDependencies but should be in `dependencies` section. Rule of thumb: If you are importing a plugin in your code, then that plugin should be in `dependencies` - not `devDependencies`.
2. You are using a *lot* of carrots in your versioning, `^`.. It's advisable to usually use `~`. It's quite possible that one of your dep's is pulling in a {N} 7 compatible plugin but your projects is still {N} 6. Try switching most carrots `^` to `~`
3. You can comment out various plugin usages in your project (comment out imports from plugins and their usage) to try and isolate down the culprit.

**Comment by Rmadhuprasanth** [comment]
> @Rmadhuprasanth that error is typical of an unfound dependency import or incorrect path to an imported file.
> 
> The most likely causes are:
> 
> 1. A dependency you added which ended up in devDependencies but should be in `dependencies` section. Rule of thumb: If you are importing a plugin in your code, then that plugin should be in `dependencies` - not `devDependencies`.
> 2. You are using a _lot_ of carrots in your versioning, `^`.. It's advisable to usually use `~`. It's quite possible that one of your dep's is pulling in a {N} 7 compatible plugin but your projects is still {N} 6. Try switching most carrots `^` to `~`
> 3. You can comment out various plugin usages in your project (comment out imports from plugins and their usage) to try and isolate down the culprit.

Thanks @NathanWalker let me Try with your instructions

**Comment by Rmadhuprasanth** [comment]
> I think at this point we need to know what code you are executing on app start, then I can try to reproduce it.

@bradmartin  find my complete repo here
https://github.com/Rmadhuprasanth/mzn
Pls have a look into it. hoping for the possible solution
Thanks

**Comment by Rmadhuprasanth** [comment]
Thanks @bradmartin  @NathanWalker  for the response. Found the issue. For now am closing the bug
