### ISSUE TITLE
Request: Tool to live preview generated native code

### ISSUE THREAD

**Issue by avif** [NativeScript/NativeScript#9227]
I find myself often wanting to see the generated native code for my js/ts files, I found the .dex files but that's unreadable.

**Describe the solution you'd like**
 It got me thinking about https://www.typescriptlang.org/play and how it demistifies the compilation process, NativeScript could do the same!
So in short, I suggest a website with a realtime side by side view of input js/ts and output java/objective-c.

**Describe alternatives you've considered**
- More documentation
- Output readable native code to output folder

**Comment by dotnetdreamer** [comment]
This will be cool...

**Comment by rigor789** [comment]
The files are usually generated in the `platforms` folder as `.java` files and can be inspected: 

```ts
@NativeClass
@JavaProxy('com.rigor789.MyTestClass')
class MyTestClass extends java.lang.String { /* just an example */
}
```
![image](https://user-images.githubusercontent.com/879060/108497315-8fa71d00-72ab-11eb-9099-251ed1a15133.png)

**Comment by avif** [comment]
> The files are usually generated in the `platforms` folder as `.java` files and can be inspected:
> 
> ```ts
> @NativeClass
> @JavaProxy('com.rigor789.MyTestClass')
> class MyTestClass extends java.lang.String { /* just an example */
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/879060/108497315-8fa71d00-72ab-11eb-9099-251ed1a15133.png)

Thanks!, I did eventually find these files and it was a great help, still think the tool would be awsome for people evaluating NativeScript.
