### ISSUE TITLE
TimePicker: Can not set to 24HourView on Android

### ISSUE THREAD

**Issue by MrSnoozles** [NativeScript/NativeScript#9239]
**Environment**
 - CLI:  7.2.0
 - Cross-platform modules: 7.2.1
 - Android Runtime: 7.0.1
 - iOS Runtime: 7.2.0

**Describe the bug**
On Android, the TimePicker always shows in 12 hour format (with am/pm), even if we call `setIs24HourView` to true on the native TimePicker widget as described here: https://docs.nativescript.org/ui/components/time-picker#time-format

**To Reproduce**
Use the TimePicker component and use the onLoad event to call the native `setIs24HourView` to true. It won't throw an error but it doesn't change the appearance of the TimePicker.

**Expected behavior**
Show a time picker in 24 hour mode. (without am/pm)

**Sample project**
https://play.nativescript.org/?template=play-vue&id=xbk6I4&v=2

![timepicker_bug](https://user-images.githubusercontent.com/17496592/108863736-cd7cac00-75f1-11eb-83d6-38baa504242e.jpg)

**Comment by asharghi** [comment]
I'm on `"tns-core-modules": "^6.5.21"`

and for me it works with:

```
onPickerLoaded(args) {
   if (!isIOS) args.object.android.setIs24HourView(java.lang.Boolean.TRUE);
}
```

**Comment by MrSnoozles** [comment]
Thanks for the reply. So the playground demo works for you too? And if you set it to `java.lang.Boolean.FALSE` it  goes back to am/pm selection?

**Comment by asharghi** [comment]
If you change your playground from `Boolean.true` to `Boolean.TRUE` it works there too

**Comment by MrSnoozles** [comment]
Seriously? I would have never come to that solution and I already spent hours trying to figure it out.
Thank you so so so much for the help here.
