### ISSUE TITLE
Nativescript Angular 11 CONSOLE ERROR: ERROR Error: Event not supported: timeout

### ISSUE THREAD

**Issue by invaderb** [NativeScript/NativeScript#9245]
**Environment**
 - CLI: 7.2.0
 - Cross-platform modules:
 - Android Runtime: N/A
 - iOS Runtime: 7.2.0
 - XCode Version:12.4
 - Plugin(s): N?A
 - Mac OS 11.1
 - nodeJS 12.18

**Describe the bug**
Here is the repo I'm playing with https://github.com/invaderb/ns-angular-dex/tree/main
I have updated to Nativescript 7 and Angular 11, on angular 10 HTTP calls were working fine however angular 11 HTTP calls just hang and I get the following runtime error in the terminal:

Successfully synced application org.nativescript.nativescriptpokedex on device 4391A347-F047-4518-892D-F72455E12A1E.
Will emit event runOnDeviceStarted with data {
  projectDir: '/Users/braydonharris/dev/nativescript-pokedex',
  deviceIdentifier: '4391A347-F047-4518-892D-F72455E12A1E',
  applicationIdentifier: 'org.nativescript.nativescriptpokedex'
}
Socket sent data: x{"method":"Log.entryAdded","params":{"entry":{"source":"javascript","level":"error","text":"ERROR Error: Event not supported: timeout","timestamp":1614208542324,"url":"","lineNumber":-1}}}x{"method":"Log.entryAdded","params":{"entry":{"source":"javascript","level":"error","text":"ERROR Error: Event not supported: timeout","timestamp":1614208542325,"url":"","lineNumber":-1}}}
CONSOLE ERROR: ERROR Error: Event not supported: timeout
CONSOLE ERROR: ERROR Error: Event not supported: timeout

**To Reproduce**
Use Nativescript 7 and angular 11 or check out the repo above and try and run the IOS build
tns run ios --bundle --log trace

**Expected behavior**
HTTP calls to return data

**Sample project**
https://github.com/invaderb/ns-angular-dex/tree/main

**Comment by invaderb** [comment]
I Just tested on IOS and android and they are both doing giving the same error.

**Comment by 13dante04** [comment]
Having the same issue on iOS only, everything worked fine up until one moment yesterday when I did cleaned my project and rebuilt it (did not change any dependencies).

**Comment by 13dante04** [comment]
Also I can confirm this didn't affect my build on Windows for android. Did not try building android on mac though.

**Comment by NathanWalker** [comment]
Interesting thanks for this report @invaderb - looks like could be related to this angular change:
https://github.com/angular/angular/pull/40771/files

Will investigate and look for another patch update to our angular package in the coming days.

**Comment by invaderb** [comment]
I am actually using Angular 11.1.1 with this issue

**Comment by NathanWalker** [comment]
I don't see the issue when I pin to `11.2.0` or when using `11.1.0`. Only when using `11.2.3` specifically.

**Comment by NathanWalker** [comment]
@invaderb share your package.json when get a chance so we can confirm.

**Comment by invaderb** [comment]
Here is my package.json
`{
  "name": "nativescript-pokedex",
  "version": "0.1.0",
  "scripts": {
    "clean": "npx rimraf hooks node_modules package-lock.json platforms",
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "android": "tns run android --no-hmr",
    "ios": "tns run ios --no-hmr",
    "mobile": "tns run",
    "preview": "tns preview",
    "ngcc": "ngcc --properties es2015 module main --first-only",
    "postinstall": "npm run ngcc"
  },
  "dependencies": {
    "@angular/animations": "~11.2.3",
    "@angular/common": "~11.2.3",
    "@angular/compiler": "~11.2.3",
    "@angular/core": "~11.2.3",
    "@angular/forms": "~11.2.3",
    "@angular/localize": "^11.2.3",
    "@angular/platform-browser": "~11.2.3",
    "@angular/platform-browser-dynamic": "~11.2.3",
    "@angular/router": "~11.2.3",
    "@nativescript/angular": "11.0.1",
    "@nativescript/core": "7.2.1",
    "@nativescript/theme": "~2.2.1",
    "@nativescript/webpack": "3.0.0",
    "@ng-bootstrap/ng-bootstrap": "7.0.0",
    "core-js": "^2.6.9",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.6.3",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.1",
    "@angular/cli": "~11.2.1",
    "@angular/compiler-cli": "~11.2.3",
    "@nativescript/ios": "7.2.0",
    "@nativescript/tslint-rules": "~0.0.5",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.1.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "node-sass": "^4.7.1",
    "protractor": "~7.0.0",
    "tns-android": "6.5.3",
    "tns-ios": "6.5.4",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.5"
  },
  "main": "main.tns.js"
}
`

**Comment by NathanWalker** [comment]
Ok good to know yeah you can pin that for all angular dep's to `11.2.0` and I don't see the issue here with that. But we'll have this resolve early next week so can just do that for now.

**Comment by edusperoni** [comment]
as a workaround, you can do the following in your main.ts (or some other file that you import in main.ts):

```
const oldAEL = XMLHttpRequest.prototype.addEventListener;
XMLHttpRequest.prototype.addEventListener = function () {
	if (arguments.length > 0 && arguments[0] === 'timeout') {
		return;
	}
	return oldAEL.apply(this, arguments);
};
```

We'll work on supporting 'timeout' the event (or at least not erroring out when you request it)

**Comment by NathanWalker** [comment]
This is published in @nativescript/core `next` at moment but will go out with patch version after awhile.

**Comment by NathanWalker** [comment]
Published with 7.2.2.

**Comment by codealvarez** [comment]
> I don't see the issue when I pin to `11.2.0` or when using `11.1.0`. Only when using `11.2.3` specifically.

I confirm. Version 11.2.0 works properly

**Comment by lostation** [comment]
Hi guys, 

This message seems coming back???

With latest ns packages -> I get also "Debug: XHR Event not supported: timeout" for each request I'm doing... Is this a regression compare to 11.2.0 ?

Should I modify some of these ?

`
  "dependencies": {
    "@angular/animations": "14.0.6",
    "@angular/cdk": "14.0.4",
    "@angular/common": "14.0.6",
    "@angular/compiler": "14.0.6",
    "@angular/core": "14.0.6",
    "@angular/forms": "14.0.6",
    "@angular/google-maps": "14.1.0",
    "@angular/material": "14.0.4",
    "@angular/platform-browser": "14.0.6",
    "@angular/platform-browser-dynamic": "14.0.6",
    "@angular/router": "14.0.6",
    "@brfrontend/xplat-scss": "file:libs/xplat/scss/src",
    "@googlemaps/markerclusterer": "2.0.10",
    "@googlemaps/markerwithlabel": "2.0.14",
    "@master.technology/websockets": "2.0.5",
    "@nativescript-community/ui-drawer": "0.1.1",
    "@nativescript-community/ui-material-bottomsheet": "7.0.25",
    "@nativescript-community/ui-material-button": "7.0.25",
    "@nativescript-community/ui-material-cardview": "7.0.25",
    "@nativescript-community/ui-material-ripple": "7.0.25",
    "@nativescript-community/ui-material-textfield": "7.0.25",
    "@nativescript-community/ui-material-textview": "7.0.25",
    "@nativescript/angular": "14.0.4",
    "@nativescript/appversion": "2.0.0",
    "@nativescript/core": "8.3.2",
    "@nativescript/firebase-core": "2.2.8",
    "@nativescript/firebase-messaging": "2.2.8",
    "@nativescript/iqkeyboardmanager": "2.0.0",
    "@nativescript/localize": "5.0.4",
    "@nativescript/secure-storage": "3.0.0",
    "@nativescript/theme": "3.0.2",
    "@ngx-translate/core": "14.0.0",
    "@ngx-translate/http-loader": "7.0.0",
    "@nstudio/nativescript-loading-indicator": "4.1.2",
    "@nstudio/nativescript-snackbar": "2.1.0",
    "@nstudio/nativescript-tracking-transparency": "1.0.0",
    "@triniwiz/nativescript-accelerometer": "4.0.3",
    "nativescript-dna-deviceinfo": "3.7.3",
    "nativescript-exit": "1.0.1",
    "nativescript-google-maps-sdk": "file:apps/nativescript-app/ns-custom-plugins/nativescript-google-maps-sdk",
    "nativescript-menu": "1.1.7",
    "nativescript-ngx-fonticon": "7.0.0",
    "nativescript-sentry": "2.0.1",
    "nativescript-ui-chart": "9.0.2",
    "nativescript-ui-gauge": "8.0.1",
    "nativescript-ui-listview": "10.2.2",
    "rxjs": "7.5.6",
    "zone.js": "0.11.6"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "14.0.5",
    "@angular-eslint/eslint-plugin": "14.0.2",
    "@angular-eslint/eslint-plugin-template": "14.0.2",
    "@angular-eslint/template-parser": "14.0.2",
    "@angular/cli": "14.0.0",
    "@angular/compiler-cli": "14.0.6",
    "@angular/language-service": "14.0.6",
    "@nativescript/android": "8.3.1",
    "@nativescript/ios": "8.3.2",
    "@nativescript/eslint-plugin": "0.0.4",
    "@nativescript/types": "8.2.0",
    "@nativescript/webpack": "5.0.7",
    "@ngtools/webpack": "14.0.5",
    "@nrwl/angular": "14.4.2",
    "@nrwl/cli": "14.4.2",
    "@nrwl/cypress": "14.4.2",
    "@nrwl/eslint-plugin-nx": "14.4.2",
    "@nrwl/jest": "14.4.2",
    "@nrwl/linter": "14.4.2",
    "@nrwl/workspace": "14.4.2",
    "@nstudio/angular": "14.3.0",
    "@nstudio/nativescript": "14.3.0",
    "@nstudio/nativescript-angular": "14.3.0",
    "@nstudio/web": "14.3.0",
    "@nstudio/web-angular": "14.3.0",
    "@nstudio/xplat": "14.3.0",
    "@types/google.maps": "3.49.2",
    "@types/he": "1.1.2",
    "@types/jest": "28.1.5",
    "@types/node": "16.11.7",
    "@typescript-eslint/eslint-plugin": "5.30.6",
    "@typescript-eslint/parser": "5.30.6",
    "cypress": "10.3.0",
    "eslint": "8.19.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-plugin-cypress": "2.12.1",
    "jest": "28.1.3",
    "jest-preset-angular": "12.1.0",
    "nativescript": "8.2.3",
    "nx": "14.4.2",
    "plist": "3.0.6",
    "prettier": "2.7.1",
    "sass": "1.53.0",
    "ts-jest": "28.0.5",
    "typescript": "4.7.4"
  },
`
