### ISSUE TITLE
Feature request: Azure Mobile Services module

### ISSUE THREAD

**Issue by alexrainman** [NativeScript/NativeScript#925]
These days Backend as a Service (BaaS) solutions are pretty popular to simplify development time. Azure Mobile Services is such a BaaS. Are you planning to release your own module or validate something like this one? 

https://github.com/alexziskind1/NativeScript-Azure-Mobile-Services-Module-Basic

**Comment by enchev** [comment]
Hey @alexrainman,

We plan to release soon [our market place with verified plugins for {N}](http://plugins.telerik.com/) and we will do our best to include as many as possible.

Thanks

**Comment by alexrainman** [comment]
Awesome!

**Comment by dtopuzov** [comment]
Hi @alexrainman, 

Please update your [demo app](https://github.com/alexziskind1/NativeScript-Azure-Mobile-Services-Module-Basic/tree/master/demo/azuremobiledemo) to {N} 1.4+ and we will verify it.

Thanks

**Comment by alexrainman** [comment]
Actually, the plugin is not mine. It's someone else :)

**Comment by alexrainman** [comment]
I just want you guys to validate it so i can use it :)

**Comment by LostBalloon1** [comment]
I see that your marketplace also points to cordova plugsins. Microsoft has some (very small) instructions https://azure.microsoft.com/en-us/documentation/articles/mobile-services-html-get-started-users/ on how to get azure working with cordova projects. Now I'm very new to NativeScript and I was wondering if it would work or not (how does your mapping to native apis affect this if it does?)

**Comment by enchev** [comment]
https://www.npmjs.com/package/nativescript-azure-mobile-basic
