### ISSUE TITLE
Svelte Template is broken when using CLI

### ISSUE THREAD

**Issue by MrAmericanMike** [NativeScript/NativeScript#9250]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.2.0
 - Cross-platform modules: (no idea)
 - Android Runtime:  (no idea)
 - iOS Runtime: (no idea)
 - XCode Version: (no idea)
 - Plugin(s): (no idea)

**Describe the bug**
Installation fails

**To Reproduce**
tns create nsapp
Select Svelte when prompted style of NativeScript

`tns create nsapp`

**Expected behavior**
Installation to proceed without errors

```
√ First, which style of NativeScript project would you like to use: » Svelte
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @nativescript/template-blank-svelte@7.0.2
npm ERR! Found: @nativescript/core@7.1.4
npm ERR! node_modules/@nativescript/core
npm ERR!   @nativescript/core@"~7.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @nativescript/core@"~7.0.0" from svelte-native@0.9.5
npm ERR! node_modules/svelte-native
npm ERR!   svelte-native@"~0.9.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See ___ for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     ___
Command npm.cmd failed with exit code 1
```

**Comment by rigor789** [comment]
If you are using npm 7, downgrade to 6. npm@7 introduced some strict changes around peer dependencies that can cause issues like yours.

**Comment by MrAmericanMike** [comment]
Confirmed. Using NPM version 6.14.11 worked.

Thanks.
