### ISSUE TITLE
Context as to whether a navigation was back or not

### ISSUE THREAD

**Issue by maknz** [NativeScript/NativeScript#926]
It would be useful to be able to find out if a navigation was back or just a regular forward navigate, something like `isBackNavigation: true`.

It would also be useful to provide context for the back navigation, separate from the navigation context. The navigation context must persist when using goBack, as the page you're going back to has to know how it was navigated to in the first place. However, it would be useful to be able to pass some separate context for the back navigation -- say, a child view that was responsible for editing a record from a parent view, passing back that record to the parent when saved (it would get back to the parent via goBack).

**Comment by nsndeck** [comment]
Issue fixed with commit #975.

**Comment by maknz** [comment]
@nsndeck does this fix allow for us to pass navigation context with `goBack()`?
