### ISSUE TITLE
iOS 14.5 beta

### ISSUE THREAD

**Issue by jdmeer** [NativeScript/NativeScript#9260]
We have two NativeScript 6.5.2 apps that fail to start on the iOS 14.5 beta.   Is this a known issue or is it possible that we're using an incompatible plugin?

NativeScript 6.5.2
NativeScript-CLI 6.5.0
Xcode 11.4.1
iOS Runtime 6.5.2

We're in the process of creating an empty hello world app on the same version to see if we can reproduce the crash.  If not, we'll try to narrow it down to a specific plugin.

**Comment by rigor789** [comment]
Runtime version? (`tns-ios`)

**Comment by anmaitrannguyen** [comment]
There are an issues with nativescript-phone:
https://github.com/msywensky/nativescript-phone/issues/51

**Comment by jdmeer** [comment]
> Runtime version? (`tns-ios`)

```json
"tns-ios": {
  "version": "6.5.2"
}
```

**Comment by iMarwan-k** [comment]
> We've confirmed that this was the issue. We intend to drop our dependency on nativescript-phone and implement the dial functionality ourselves.

Do you mind sharing how you developed your own?


Thanks

**Comment by lilac16** [comment]
Not sure if this is the right way to do it but workaround for now is to use back the openUrl(tel: ).. Would love to know if there s better option

**Comment by lilac16** [comment]
> > We've confirmed that this was the issue. We intend to drop our dependency on nativescript-phone and implement the dial functionality ourselves.
> 
> Do you mind sharing how you developed your own?
> 
> Thanks


Not sure if this is the right way to do it but workaround for now is to use back the openUrl(tel: ).. Would love to know if there s better option
