### ISSUE TITLE
IOS App Submission Failed

### ISSUE THREAD

**Issue by Rmadhuprasanth** [NativeScript/NativeScript#9274]
Dear Developer, We identified one or more issues with a recent delivery for your app. Your delivery was successful, but you may wish to correct the following issues in your next delivery:ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs. See https://developer.apple.com/documentation/uikit/uiwebview for more information. After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect. Best regards, The App Store Team

**Note:I have searched API references for UIWebView but not found any in workspace**

Any possible solution Much appreciated thanks

**Please Find My plugins List Below**

"dependencies": {
    "@agm/core": "^1.1.0",
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript-rtl/ui": "^0.1.4",
    "@nativescript/theme": "~2.3.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "@types/jest": "^26.0.0",
    "guid-typescript": "^1.0.9",
    "jest": "^26.0.1",
    "nativescript-angular": "~8.21.0",
    "nativescript-autocomplete": "^1.0.0",
    "nativescript-background-http": "^4.2.1",
    "nativescript-camera": "^4.5.0",
    "nativescript-cardview": "^3.2.0",
    "nativescript-carousel": "^6.1.1",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-dna-deviceinfo": "^2.4.3",
    "nativescript-downloadmanager": "^0.1.0",
    "nativescript-drop-down": "^5.0.5",
    "nativescript-geocoding": "^2.0.1",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-gif": "^4.0.6",
    "nativescript-google-maps-sdk": "^2.9.1",
    "nativescript-google-places-autocomplete": "^1.0.3",
    "nativescript-here": "0.0.1",
    "nativescript-http-formdata": "^2.1.0",
    "nativescript-image-zoom": "^3.0.3",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-localstorage": "^2.0.1",
    "nativescript-mapbox": "^5.0.1",
    "nativescript-ng-shadow": "^2.1.0",
    "nativescript-pager": "^12.0.0-alpha.9",
    "nativescript-pdf-view": "^2.4.3",
    "nativescript-permissions": "^1.3.9",
    "nativescript-plugin-firebase": "^10.5.2",
    "nativescript-push-notifications": "^1.1.6",
    "nativescript-radial-gradient": "^0.8.0",
    "nativescript-range-seek-bar": "^1.0.3",
    "nativescript-share-file": "^1.0.6",
    "nativescript-sms-inbox": "^2.1.0",
    "nativescript-sms-receiver": "^1.0.1",
    "nativescript-social-share": "^1.6.0",
    "nativescript-star-ratings": "^1.0.0",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-ui-autocomplete": "^6.0.1",
    "nativescript-ui-chart": "^6.0.0",
    "nativescript-ui-gauge": "^6.0.0",
    "nativescript-ui-listview": "^8.2.0",
    "nativescript-ui-sidedrawer": "~8.0.0",
    "ng-otp-input": "^1.7.1",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.5.0",
    "tns-ng-gif": "^1.3.1",
    "ts-jest": "^26.1.0",
    "uuid": "^8.3.0",
    "uuid-generator-ts": "^1.0.4",
    "zone.js": "~0.9.1"
  }

**Comment by NathanaelA** [comment]
Do a grep/search in the `node_modules` folder to find which plugin is using UIWebView.        If you don't find it this way, then the next way is to build the ios app; then search the platforms/ios/ to try and find out which native module (i.e. typically a podfile included resource) is bringing it in.  As a native resource can also reference it...

**Comment by Rmadhuprasanth** [comment]
> Do a grep/search in the `node_modules` folder to find which plugin is using UIWebView. If you don't find it this way, then the next way is to build the ios app; then search the platforms/ios/ to try and find out which native module (i.e. typically a podfile included resource) is bringing it in. As a native resource can also reference it...

@NathanaelA Thanks for Your quick response 
  Earlier i found that AFNetworking Plugin used UIWebView and then i removed it from the project..

Again I have searched API references for UIWebView but not found any in workspace.Eventhough i am getting same issue

**Comment by Rmadhuprasanth** [comment]
> Do a grep/search in the `node_modules` folder to find which plugin is using UIWebView. If you don't find it this way, then the next way is to build the ios app; then search the platforms/ios/ to try and find out which native module (i.e. typically a podfile included resource) is bringing it in. As a native resource can also reference it...

**@NathanaelA i did grep.found plugins which are using UIWebView**

**grep -r -F "UIWebView" .** 


Any idea regarding this..

Binary file ./platforms/ios/Pods/HEREMapsStarter/framework/NMAKit.framework/NMAKit matches
Binary file ./platforms/ios/Pods/Mapbox-iOS-SDK/dynamic/Mapbox.framework.dSYM/Contents/Resources/DWARF/Mapbox matches
Binary file ./platforms/ios/build/Release-iphonesimulator/OMGHTTPURLRQ/OMGHTTPURLRQ.framework.dSYM/Contents/Resources/DWARF/OMGHTTPURLRQ matches
Binary file ./platforms/ios/build/Release-iphonesimulator/DKCarouselView/DKCarouselView.framework.dSYM/Contents/Resources/DWARF/DKCarouselView matches
Binary file ./platforms/ios/build/Release-iphonesimulator/FLAnimatedImage/FLAnimatedImage.framework.dSYM/Contents/Resources/DWARF/FLAnimatedImage matches
Binary file ./platforms/ios/build/Release-iphonesimulator/TTRangeSlider/TTRangeSlider.framework.dSYM/Contents/Resources/DWARF/TTRangeSlider matches
./node_modules/nativescript-dna-deviceinfo/deviceinfo.ios.js:        var webView = UIWebView.alloc().initWithFrame(CGRectZero);
./node_modules/tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts:declare class UIWebView extends UIView implements NSCoding, UIScrollViewDelegate {
./node_modules/tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts:	static alloc(): UIWebView; // inherited from NSObject
./node_modules/tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts:	static appearance(): UIWebView; // inherited from UIAppearance
./node_modules/tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts:	static appearanceForTraitCollection(trait: UITraitCollection): UIWebView; // inherited from UIAppearance
./node_modules/tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts:	static appearanceForTraitCollectionWhenContainedIn(trait: UITraitCollection, ContainerClass: typeof NSObject): UIWebView; // inherited from UIAppearance
./node_modules/tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts:	static appearanceForTraitCollectionWhenContainedInInstancesOfClasses(trait: UITraitCollection, containerTypes: NSArray<typeof NSObject> | typeof NSObject[]): UIWebView; // inherited from UIAppearance
./node_modules/tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts:	static appearanceWhenContainedIn(ContainerClass: typeof NSObject): UIWebView; // inherited from UIAppearance
./node_modules/tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts:	static appearanceWhenContainedInInstancesOfClasses(containerTypes: NSArray<typeof NSObject> | typeof NSObject[]): UIWebView; // inherited from UIAppearance
./node_modules/tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts:	static new(): UIWebView; // inherited from NSObject
./node_modules/tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts:	delegate: UIWebViewDelegate;
./node_modules/tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts:interface UIWebViewDelegate extends NSObjectProtocol {
./node_modules/tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts:	webViewDidFailLoadWithError?(webView: UIWebView, error: NSError): void;
./node_modules/tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts:	webViewDidFinishLoad?(webView: UIWebView): void;
./node_modules/tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts:	webViewDidStartLoad?(webView: UIWebView): void;
./node_modules/tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts:	webViewShouldStartLoadWithRequestNavigationType?(webView: UIWebView, request: NSURLRequest, navigationType: UIWebViewNavigationType): boolean;
./node_modules/tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts:declare var UIWebViewDelegate: {
./node_modules/tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts:	prototype: UIWebViewDelegate;
./node_modules/tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts:declare const enum UIWebViewNavigationType {

**Comment by NathanaelA** [comment]
The `.d.ts` files don't matter, they are just the typings but aren't used by the final program.

So based on your list you have:
- Binary file `HEREMapsStarter`/framework/NMAKit.framework/NMAKit matches
- Binary file `Mapbox`.framework.dSYM/Contents/Resources/DWARF/Mapbox matches
- Binary file `OMGHTTPURLRQ`.framework.dSYM/Contents/Resources/DWARF/OMGHTTPURLRQ matches
- Binary file `DKCarouselView`/DKCarouselView.framework.dSYM/Contents/Resources/DWARF/DKCarouselView matches
- Binary file `FLAnimatedImage`/FLAnimatedImage.framework.dSYM/Contents/Resources/DWARF/FLAnimatedImage matches
- Binary file `TTRangeSlider`.framework.dSYM/Contents/Resources/DWARF/TTRangeSlider matches
- `nativescript-dna-deviceinfo`/deviceinfo.ios.js: var webView = UIWebView.alloc().initWithFrame(CGRectZero);

Are all items that appear to be using the `UIWebView` based on your grep search -- You probably need to upgrade each of those plugins to use a later version, or replace them with a different plugin.
