### ISSUE TITLE
Throwing Error when resize image retrieved via fromURL method of ImageSource

### ISSUE THREAD

**Issue by videouser** [NativeScript/NativeScript#9275]
I am building Nativescript App with Angular. 
App will retrieve image from internet and resize on the fly before it is showing in app.

Below is the code:-

**image.html**

```
<Image (loaded)="onImageLoaded($event)" class="img-home-event" stretch="aspectFill">
 </Image> 
```

**image.ts**

```
onImageLoaded(args)
{        
        let image = <Image>args.object;
        
        ImageSource.fromUrl("https://homepages.cae.wisc.edu/~ece533/images/airplane.png")
        .then((imageSource) =>{
            image.imageSource = imageSource.resize(100);
            image.height = 150;
            image.width = 150;
        });        
}
```

While doing so I ma receiving below error:-

> ERROR Error: Uncaught (in promise): TypeError: imageSource.resize is not a function. (In 'imageSource.resize(100)', 'imageSource.resize' is undefined)

Please help me to resolve the error.

**Comment by NathanWalker** [comment]
@videouser when you can, drop your package.json here so we can see the core and angular versions in use.

**Comment by videouser** [comment]
Thanks Nathan for replying. Here is package.json attached.

[package.zip](https://github.com/NativeScript/NativeScript/files/6252606/package.zip)

**Comment by NathanWalker** [comment]
@videouser looking at the changelog shows resize was added in `6.5.9`:
https://github.com/NativeScript/NativeScript/releases/tag/6.5.9
You might want to see if your project has a `package-lock.json` file which may be preventing you from getting that patch since your project is set to 6.5.0.... try doing this:
```
npx rimraf node_modules package-lock.json hooks platforms
```
And then try running again.

**Comment by videouser** [comment]
I upgraded my NS project to 7+ and error is gone. Thanks Nathan for your help. 
However my issue is now that resize function is not resizing images to desired value. I was testing with various size of images and found that edges are getting cut while resizing to desired value. 
@NathanWalker - Can you please suggest of any plugin or alternative that could resize image perfectly in Nativescript?

**Comment by NathanWalker** [comment]
Great to hear! - it will always depend on the original source image - edges getting cut is expected depending on the aspect you are resizing to from original source. Let's close this issue however you could also checkout using the imagecropper as an additional UX point for handling with more user control:
https://github.com/bthurlow/nativescript-imagecropper
or programmatically can find additional tips on StackOverflow around cropping for example:
https://stackoverflow.com/questions/32041420/cropping-image-with-swift-and-put-it-on-center-position
