### ISSUE TITLE
New webpage not search

### ISSUE THREAD

**Issue by vallemar** [NativeScript/NativeScript#9291]
In the new page of nativescript when you search for something, it does not find anything, it keeps searching. By the way, great job!

**Comment by rigor789** [comment]
The search will be working soon, we are waiting for the Algolia DocSearch setup process to finish & index the docs.

**Comment by xeroxstar** [comment]
> The search will be working soon, we are waiting for the Algolia DocSearch setup process to finish & index the docs.

The website links are not working when you are doing a search in Google. The results i am getting from google redirects me to 404 page:

```
Page Not Found
Looks like you've followed a broken link or entered a URL that doesn't exist on this site.

 Back to our site

If this is your site, and you weren't expecting a 404 for this path, please visit Netlify's "page not found" support guide for troubleshooting tips.
```

**Comment by rigor789** [comment]
Search is up!

**Comment by rigor789** [comment]
Re: 404s, tracking here https://github.com/NativeScript/docs/issues/1952
