### ISSUE TITLE
Documents do not search well

### ISSUE THREAD

**Issue by vallemar** [NativeScript/NativeScript#9302]
When you search in the documents: for example label, if you click on the first option it first takes you to https://docs.nativescript.org/ui-and-styling.html#label and then changes to https://docs.nativescript.org/ui-and-styling.html#frame in my case. Does the same with everything. It's a bit random, sometimes it leads to the section and sometimes it doesn't. (for me most do not)

**Comment by janoshrubos** [comment]
Closing this issue and move it to the [NativeScript/docs-new](https://github.com/NativeScript/docs-new) repo: https://github.com/NativeScript/docs-new/issues/34
