### ISSUE TITLE
Cannot open camera within a webview on Android

### ISSUE THREAD

**Issue by bliulin** [NativeScript/NativeScript#9304]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.0 (Nativescript with Angular)
 - Cross-platform modules:
 - Android Runtime: 8, 9, 10, 11
 - iOS Runtime: N/A
 - XCode Version: N/A
 - Plugin(s): N/A

**Describe the bug**
On Android I cannot get the camera to open within a WebView control.

I am not getting any errors, just a white screen instead of the camera permission prompt from the chromium browser. There has been another issue opened on this (https://github.com/NativeScript/NativeScript/issues/7234), but it is closed without anybody providing a solution for it.

I have followed the indications provided on most resources, so that:

I have the webview instance declared in the markup:

`<WebView #webView [src]="url" (loaded)="onWebViewLoaded()" marginTop="10"></WebView>`

I initialize the webview when the loaded handler is called:

```
private setupWebViewInterface(url: string): void {
        const webView: WebView = this.myWebView.nativeElement;
        if (isAndroid) {
            const settings = webView.android.getSettings();
            settings.setDomStorageEnabled(true);
            settings.setJavaScriptEnabled(true);
            settings.setSupportZoom(false);
            settings.allowFileAccess = true;
            settings.allowContentAccess = true;
            settings.setAllowFileAccessFromFileURLs(true);
            settings.setAllowUniversalAccessFromFileURLs(true);

            webView.android.setWebViewClient(new android.webkit.WebViewClient());

            permissions.requestPermissions([android.Manifest.permission.CAMERA], "").then(() => {
                console.log('Permissions granted');
                webView.android.setWebChromeClient(new KycExecutionPermissions());
                webView.reload();
            })
            .catch(() => {
                console.log('No permissions granted');
            });
        }
        this.oLangWebViewInterface = new WebViewInterface(webView, url);
        this.listenToActions();
    }
```

The `KycExecutionPermissions ` extends the WebChromeClient in order to grant permissions:

```
export class KycExecutionPermissions extends android.webkit.WebChromeClient {
    onPermissionRequest(permissionRequest: android.webkit.PermissionRequest): void {
        console.log('onPermissionRequest: ' + permissionRequest);
        var resources = permissionRequest.getResources();

        console.log('Resources requested below...');
        for (let i = 0; i < resources.length; i++) {
            console.log(resources[i]);
        }

        try {
            //permissionRequest.grant([android.webkit.PermissionRequest.RESOURCE_VIDEO_CAPTURE]);
            permissionRequest.grant(resources);
            console.log('permission granted in web chrome client.')
        } catch (e) {
            console.log('ERROR: ' + e);
        }
    }

    //@ts-ignore
    onConsoleMessage(consoleMessage: android.webkit.ConsoleMessage): boolean {
        console.log('CONSOLE message: ' + consoleMessage.message);
        return true;
    }
}
```

Uses-permissions elements are added in the AndroidManifest.xml file:

```
<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.CAMERA2" />
    <uses-permission android:name="android.permission.CAPTURE_SECURE_VIDEO_OUTPUT" />
    <uses-permission android:name="android.permission.CAPTURE_VIDEO_OUTPUT" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />

    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.CAPTURE_AUDIO_OUTPUT" />
	<uses-permission android:name="android.permission.VIDEO_CAPTURE" />
	<uses-permission android:name="android.permission.AUDIO_CAPTURE" />

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_USER_DICTIONARY" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    
	<uses-feature android:name="android.hardware.camera.autofocus" android:required="true" />
    <uses-feature android:name="android.hardware.camera.front" android:required="true" />
    <uses-feature android:name="android.hardware.camera" android:required="true" />
    <uses-feature android:name="android.hardware.camera.level.full" android:required="true" />
    <uses-feature android:name="android.hardware.camera.capability.raw" android:required="true" />
    <uses-feature android:name="android.hardware.camera.any" android:required="true" />
    <uses-feature android:name="android.hardware.microphone" android:required="true" />
    <uses-feature android:name="android.hardware.camera2" android:required="true" />
```

Does anybody know what is the issue here?

**To Reproduce**
I have created the following repo for testing this behavior with a sample app: https://github.com/bliulin/ns-webview-camera

This app opens a page which contains a webview. Within this webview, the following URL is loaded: 'https://bliulinstorage.z6.web.core.windows.net/'. This URL shows the webcam image, as it can be seen when testing it on a normal Google Chrome instance (not webview).

This web app has the following JS file running on the page:

```
// Set constraints for the video stream
var constraints = { video: { facingMode: "user" }, audio: false };
var track = null;

var oWebViewInterface = window.nsWebViewInterface;

// Define constants
const cameraView = document.querySelector("#camera--view"),
    cameraOutput = document.querySelector("#camera--output"),
    cameraSensor = document.querySelector("#camera--sensor"),
    cameraTrigger = document.querySelector("#camera--trigger");

// Access the device camera and stream to cameraView
function cameraStart() {
    oWebViewInterface.emit('action', 'window loaded');

    navigator.mediaDevices
        .getUserMedia(constraints)
        .then(function(stream) {
            track = stream.getTracks()[0];
            cameraView.srcObject = stream;
            oWebViewInterface.emit('action', 'getUserMedia success!');
        }, function(reason) {
            oWebViewInterface.emit('action', 'getUserMedia rejected! Reason: ' + reason);
        })
        .catch(function(error) {
            console.error("Oops. Something is broken. Message: " + error, error);
            oWebViewInterface.emit('action', error);
        });
}

// Take a picture when cameraTrigger is tapped
cameraTrigger.onclick = function() {
    cameraSensor.width = cameraView.videoWidth;
    cameraSensor.height = cameraView.videoHeight;
    cameraSensor.getContext("2d").drawImage(cameraView, 0, 0);
    cameraOutput.src = cameraSensor.toDataURL("image/webp");
    cameraOutput.classList.add("taken");
    // track.stop();
};

// Start the video stream when the window loads
window.addEventListener("load", cameraStart, false);
```

So it uses the getUserMedia method on the navigator to open the device camera. It uses a an interface to send debug messages back to the NS component, where we can see in the console the _getUserMedia success!_ message. So I don't know why the webcam is not showing anything.

It does _seem_ to work on an emulator for Android 9 and lower. But not on the actual device I have tested on, which also has Android 9.

**Expected behavior**

The webview should display the webcam image, possibly by showing a permission prompt first.

**Sample project**
https://bliulinstorage.z6.web.core.windows.net/

**Additional context**

**Comment by farfromrefug** [comment]
@bliulin this a N issue. you should search the web on how to use camera in android webview.
this could help https://stackoverflow.com/questions/40659198/how-to-access-the-camera-from-within-a-webview

**Comment by bliulin** [comment]
@NathanWalker , thanks, I will check that post in more detail. According to many other posts, granting the resources on the PermissionRequest instance is enough to make it work. But it appears it is not so.

**Comment by bliulin** [comment]
@NathanWalker , could you perhaps indicate towards a direction for change? As far as I understand, all the posts from the Stackoverflow thread above point towards the same idea, granting resources on the permission request, which I am already doing:

request.grant(request.resources)

Thank you!

**Comment by farfromrefug** [comment]
@bliulin i would suggest to test this on a native Android app. If you get it to work we can see if something is wrong with the N side.

**Comment by bliulin** [comment]
Hi @farfromrefug , I was able to get it to work in a native Android app. The code is here: https://github.com/bliulin/android-webview-webcam

Could it be that I am not applying the settings properly on the webview instance in the setupWebinterface method? In Kotlin one would do it like so:

```
web_view.settings.apply {
//            allowContentAccess = true
            javaScriptEnabled = true
            mediaPlaybackRequiresUserGesture = false
        }
```

But how can we do it in NS?

**Comment by bliulin** [comment]
It appears that in NS you have to call the method, like so:

`settings.setMediaPlaybackRequiresUserGesture(false);`

By doing this, the problem is solved.

**Comment by ebiscardi** [comment]
Hi @bliulin, I need to use the device camera in a WebView, so I came across your post.
Do you solve using the code posted here? I tried to replicate in my project (with some variant to make it build with Nativescript core), using your page for testing, but after asking (and confirm) for camera permission, I read this in my console: JS: Received event: "getUserMedia rejected! Reason: NotAllowedError: Permission denied".
Besides this, I can't see any log from KycExecutionPermissions class.

**Comment by bliulin** [comment]
Hi @ebiscardi , indeed the demo code on git should be working. I just pushed the latest changes, with the setMediaPlaybackRequiresUserGesture call. I didn't test with NS core though, only with NS with Angular.

**Comment by Abhi-bluesurf** [comment]
Webview in android/react native is not allowing the web cam to zoom. Even though the zoom value for the camera is set statically in javascript, webview loads the website with the default zoom. Please suggest how to zoom the camera access through webview.
