### ISSUE TITLE
Templates error ActionBar (Only pixel 4)

### ISSUE THREAD

**Issue by vallemar** [NativeScript/NativeScript#9307]
tr**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  8.0.01
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - XCode Version:
 - Plugin(s):

**Describe the bug**
I have tried to create projects: js, vue and vue + ts (I imagine it would happen in all). All 3 have the same error in the ActionBar. They have that effect cut in half

![image](https://user-images.githubusercontent.com/15719383/113826217-31ae9600-9782-11eb-9ea2-dcf07fff61fa.png)

**Comment by LouieTian0209** [comment]
Not completely sure but I think it's also related to which device your emulator is mirroring. I was having this status bar overlapping issue when using an emulator that simulates Pixel 4XL, but when I use Pixel 2 XL or 3, I don't get this issue. Still would like to know how to get this fixed once and for all.

**Comment by vallemar** [comment]
@LouieTian0209 It's true, together I was testing it. Checked on my real mobile and other pixels and it works fine. I have been trying to correct it for a while but I have not been able to

**Comment by vallemar** [comment]
I have found a solution but it makes the bar look somewhat larger on other devices.

```
<style name="LaunchScreenThemeBase" parent="Theme.AppCompat.Light.NoActionBar">    
 <item name="toolbarStyle">@style/NativeScriptToolbarStyle</item>     
 <item name="colorPrimary">@color/ns_primary</item>    
 <item name="colorPrimaryDark">@color/ns_primaryDark</item>    
 <item name="colorAccent">@color/ns_accent</item>    
 <item name="android:windowBackground">@drawable/splash_screen</item>    
 <item name="colorControlActivated">@color/ns_primary</item>      
<item name="android:windowActionBarOverlay">false</item>     
<item name="android:windowTranslucentStatus">false</item>     
add --->  <item name="android:fitsSystemWindows">true</item>
  </style>

```

**Comment by LouieTian0209** [comment]
> I have found a solution but it makes the bar look somewhat larger on other devices.
> 
> ```
> <style name="LaunchScreenThemeBase" parent="Theme.AppCompat.Light.NoActionBar">    
>  <item name="toolbarStyle">@style/NativeScriptToolbarStyle</item>     
>  <item name="colorPrimary">@color/ns_primary</item>    
>  <item name="colorPrimaryDark">@color/ns_primaryDark</item>    
>  <item name="colorAccent">@color/ns_accent</item>    
>  <item name="android:windowBackground">@drawable/splash_screen</item>    
>  <item name="colorControlActivated">@color/ns_primary</item>      
> <item name="android:windowActionBarOverlay">false</item>     
> <item name="android:windowTranslucentStatus">false</item>     
> add --->  <item name="android:fitsSystemWindows">true</item>
>   </style>
> ```

@vallemar If you set padding of the ActionBar to 0 it should look normal.
