### ISSUE TITLE
N8 self is undefined in worker

### ISSUE THREAD

**Issue by jamescodesthings** [NativeScript/NativeScript#9308]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8
 - Cross-platform modules: 8.0.0
 - iOS Runtime: 8.0.0
 - XCode Version: Version 12.4 (12D4e)
 - Angular: 11.2.8

**Describe the bug**
I've been poking at updating to NS 8. When I migrate and update the build to run I get the following error from a worker:

`Uncaught ReferenceError: self is not defined`

**To Reproduce**
1. Update final webpack config to resemble the webpack config from https://github.com/NativeScript/worker-loader

Relevant parts of final webpack config:
```js
{ //...
  rules: [
      // Exclude from ng rule
      {
        test: /(?:\.ngfactory.js|\.ngstyle\.js|\.ts)$/,
        use: [ { loader: '@ngtools/webpack' } ],
        exclude: /.worker.ts$/
      },
      // Transpile workers with ts-loader
      { test: /.worker.ts$/, use: [ { loader: 'ts-loader' } ] },
  ],
  plugins: [
    // Add angular compiler to worker plugin instantiation
    // Note: here angular plugin is a ref to the AngularCompilerPlugin
    new NativeScriptWorkerPlugin(angularPlugin),
  ],
```

2. Write a worker
3. Import and use the worker with `nativescript-worker-loader` inlined:
```
const WorkerScript = require("nativescript-worker-loader!./worker-script.js");
const worker = new WorkerScript();
```

**Expected behavior**
The worker should work & not cause crash on app init.

**Sample project**
Can produce upon request.

**Additional context**
Previously this config worked with ns 7.2.0, before the webpack change. After the webpack change I've attempted to reproduce the same webpack config with webpack-chain and the output from the above config is the final configuration.

Guessing there's some change that I've not seen documented that would make this work?

Have also tried with the default webpack config and no changes to my code. Throws a module build error with missing from typescript compilation. When I manually add the file to the files: array in tsconfig.json I then get the same error as above.

Have not tried removing nativescript-worker-loader from the import of my worker. But have also noted there's another definition in the default angular config that uses this loader?

Any help would be appreciated.

**Comment by jamescodesthings** [comment]
Producing demo project now.

**Comment by farfromrefug** [comment]
@jamescodesthings this is not the way to use Worker anymore. Now we can do it the web way.
* remove `nativescript-worker-loader`
* instantiate your worker this way `new Worker('./worker-script')`

**Comment by jamescodesthings** [comment]
Cheers! Appreciate it.
