### ISSUE TITLE
[Webpack5] Adding wbepack plugins messes up HMR

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#9309]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.1
 - Cross-platform modules: 8.0.1
 - Android Runtime: 8.0
 - iOS Runtime: 8.0
 - XCode Version: 12.4
 - Plugin(s): `@nativescript/webpack: 5.0.0-beta.5`

**Describe the bug**
Seems that adding any custom plugin to the webpack config messes up the HMR and it stops working at all - it recompiles the files says it syncs, but nothing changes on device (tested for iOS). Below is a sample changed config file
```js
const webpack = require("@nativescript/webpack");
const { DefinePlugin } = require("webpack");

module.exports = (env) => {
    webpack.init(env);

    // Learn how to customize:
    // https://docs.nativescript.org/webpack

    webpack.chainWebpack((config) => {
        config.plugin("DefinePlugin").use(
            DefinePlugin,
            [
                {
                    "global.isIOS": `${!!env.ios}`,
                    "global.isAndroid": `${!!env.android}`,
                    "global.isProductionModeIn": `${!!env.production}`,
                },
            ]
        )
    });
    // END config customization

    return webpack.resolveConfig()
}
```

**To Reproduce**
Create a HelloWorld Plain TS app and change the `webpack.config.js` to the above

**Expected behavior**
HMR to continue to work. 

**Sample project**

**Additional context**

**Comment by joshmossas** [comment]
I can confirm that this is also happening with the android emulator. I'm using Nativescript-Vue + Typescript.

My webpack config
```js
const webpack = require('@nativescript/webpack');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

module.exports = (env) => {
    webpack.init(env);

    // if I comment this out HMR works
    webpack.chainWebpack((config) => {
        config.resolve.plugin().use(new TsconfigPathsPlugin());
    });

    // Learn how to customize:
    // https://docs.nativescript.org/webpack

    return webpack.resolveConfig();
};
```

**My Environment**

Windows 10
Nativescript v8.0.1
@nativescript/core v8.0.1
@nativescript/android v8.0.0
@nativescript/ios v8.0.0

**Comment by rigor789** [comment]
```js
webpack.chainWebpack((config) => {
  config.plugin("DefinePlugin").use(
    DefinePlugin,
    [
      {
        "global.isIOS": `${!!env.ios}`,
        "global.isAndroid": `${!!env.android}`,
        "global.isProductionModeIn": `${!!env.production}`,
      },
    ]
  )
});
```

completely overrides the internal DefinePlugin, which already defines `global.isAndroid` and `global.isIOS` - you can either give it a different name, or extend the built-in defines with your own:

```js
webpack.chainWebpack(config => {
  config.plugin("DefinePlugin").tap(args => {
    Object.assign(args[0], {
      "global.isProductionModeIn": !!env.production,
    })

    return args;
  });
});
```

To inspect them, run `ns prepare android/ios --env.verbose` and look in console: 
![image](https://user-images.githubusercontent.com/879060/113943711-82b29e80-9803-11eb-829e-2ac4ab9f4d86.png)

@joshmossas this seems to work for me:
```js
config.resolve.plugin('TsconfigPathsPlugin').use(TsconfigPathsPlugin);
```

Note that you shouldn't instantiate the plugin - just pass it to `use` as a constructor.

Another note with Vue & HMR, if you are trying to change template/script, it only works if you are not updating a page component, or a direct child of it (I plan to look into that next week).

**Comment by joshmossas** [comment]
Nice that's working thanks.

**Comment by PeterStaev** [comment]
Thanks @rigor789 ! I missed that there is already a plugin with the same name defined. Changing the name solved the problem!
