### ISSUE TITLE
Android build fails with - duplicate of com.tns.FragmentClass

### ISSUE THREAD

**Issue by basil-wolf** [NativeScript/NativeScript#9310]
**Environment**
 - CLI: 8.0.1
 - Core: 8.0.1
 - Android Runtime: 8.0.0

**Describe the bug**
Cannot build my android app which was developed with NS7 - always get the error:

Warning: there already is an extend called com.tns.FragmentClass.
Warning: The static binding generator will generate extend from:vendor.js implementation
java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
File:/Users/ns/app/platforms/android/app/src/main/java/com/tns/FragmentClass.java Class: com.tns.FragmentClass
	at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:112)
	at org.nativescript.staticbindinggenerator.Main.main(Main.java:55)

**To Reproduce**
ns run android

Also I have attached the [vendor.js.zip](https://github.com/NativeScript/NativeScript/files/6277959/vendor.js.zip) file.
Please search for **com.tns.FragmentClass**

**Plugins**
None of the installed plugins are requesting com.tns.FragmentClass as I can see.

@bradmartin/nativescript-urlhandler
@nativescript/appversion
@nativescript/firebase
@nativescript/geolocation
@nativescript/secure-storage
@owen-it/nativescript-uuid
moment
moment-timezone
nativescript-getters
nativescript-sqlite

**Comment by rsun-thoughtworks** [comment]
Did you fix it? Can you share your solution? Big Thank you!

**Comment by basil-wolf** [comment]
If you are using @owen-it/nativescript-uuid it may cause the problem. Some plugins haven’t been update to NS8. Also nativescript-getters have been update recently and works with NS8.
