### ISSUE TITLE
[TabView] Linear gradient for background color

### ISSUE THREAD

**Issue by LouieTian0209** [NativeScript/NativeScript#9312]
**Is your feature request related to a problem? Please describe.**
In my project I have an ActionBar and a TabView. Both of which should have linear gradient color as background for consistency reason required from my client. I am able to set ActionBar background color with linear gradient value but the same thing cannot be done with TabView.

**Describe the solution you'd like**
Expose an attribute for users on TabView to let user set `background` to linear gradient value.

**Describe alternatives you've considered**
I have considered switching to BottomNavigation or Tabs provided in `nativescript-community` but they don't support such feature either.

**Comment by farfromrefug** [comment]
@LouieTian0209 this could only come in `nativescript-community`. N dropped those components, they are now fully maintained in `nativescript-community`

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
