### ISSUE TITLE
Use of VoiceOver causes crash

### ISSUE THREAD

**Issue by groenroos** [NativeScript/NativeScript#9317]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.1
 - Cross-platform modules:
 - Android Runtime: n/a
 - iOS Runtime: 8.0.0
 - XCode Version: 12.4 (12D4e)
 - Plugin(s): `nativescript-dark-mode 1.0.0`

**Describe the bug**

When running the app on a physical device and using the VoiceOver assistive technology, VoiceOver will read the first label in the app automatically; however touching the screen causes the app to crash with the following log;

```
***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught TypeError: Cannot read property 'tag' of null
at
(file: src/packages/core/accessibility/index.ios.ts:77:14)
at NotificationObserver.onReceive(file:///app/vendor.js:1807:10)
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught TypeError: Cannot read property 'tag' of null
at
(file: src/packages/core/accessibility/index.ios.ts:77:14)
at NotificationObserver.onReceive(file:///app/vendor.js:1807:10)
', reason: '(null)'
*** First throw call stack:
(0x19d28186c 0x1b229dc50 0x1031ec064 0x1035c40e8 0x1035c3f40 0x1034c8b70 0x1033eebd4 0x1033ee2ac 0x10325ecdc 0x10312d8ac 0x1032234fc 0x1032241b4 0x19d1de9a0 0x19d1de948 0x19d1ddeb0 0x19d1dd870 0x19e4a44bc 0x1b15c9040 0x1b15ce14c 0x1b15ba75c 0x1b158e004 0x1bcc07024 0x1bcc065d4 0x1bcc06f2c 0x1bcc54874 0x1bcc161f0 0x19d1fdfe8 0x19d1fd378 0x19d1f708c 0x19d1f621c 0x1b4dc3784 0x19fc36ee8 0x19fc3c75c 0x103224044 0x103222d60 0x1031c375c 0x103186090 0x1031e6e24 0x1031e0ee8 0x102607758 0x19ceb66b0)
```

**To Reproduce**

- Turn on VoiceOver
- Switch to the NS app
- Touch the screen

**Expected behavior**

App shouldn't crash

**Sample project**

**Additional context**

I'm using NativeScript Vue if that makes a difference, but the error message seems to point towards an NS core lib

**Comment by NathanWalker** [comment]
Thank you for the report 👍 
When you get a chance could you download this .tgz which includes the patch fix:
https://drive.google.com/file/d/1zmScaad05dNkqTlnIU6u_OcHCDWTmx5w/view?usp=sharing
Place in root of your project and modify you package.json as follows:
```
"@nativescript/core": "file:nativescript-core-8.0.1-fix-9317.tgz",
```
And then `ns clean` and run the app to confirm the fix, thank you.

**Comment by groenroos** [comment]
Thanks @NathanWalker, I can confirm that this patch has fixed the issue! 👍

**Comment by NathanWalker** [comment]
@groenroos You can use the `next` tag for now which includes that fix:
```
"@nativescript/core": "next"
```
It will go into 8.0.2 patch sometime next week along with few others. thanks again.
