### ISSUE TITLE
CLA Links Are Broken

### ISSUE THREAD

**Issue by joshmossas** [NativeScript/NativeScript#9321]
**Environment**
Github.com

**Describe the bug**
Pull requests want to you to affirm that you have signed the Nativescript CLA, but the [CLA link](https://nativescript.org/cla) leads to a 404.

Additionally in the https://github.com/NativeScript/nativescript-app-templates repo. (Which is where I created a PR) The links for "Nativescript Guidelines" and "Running Tests" are also broken

**To Reproduce**
Go to any of the links specified above.

**Expected behavior**
Links should be up to date so potentially new developers can create PRs without additional friction.

**Comment by rigor789** [comment]
Fixed CLA link now!

**Comment by joshmossas** [comment]
Nice thanks.
