### ISSUE TITLE
Tabs/TabContentItem rendering error (first 2 indices 0 and 1 specifically) on iOS NativeScript Angular

### ISSUE THREAD

**Issue by kenzend** [NativeScript/NativeScript#9322]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - NativeScript Angular: tns-core-modules 6.5.0

Screen shots:
![IMG-3968](https://user-images.githubusercontent.com/17608491/114238288-9f54f080-9941-11eb-8ff8-27f79aaf6bfd.PNG)
![IMG-3969](https://user-images.githubusercontent.com/17608491/114238289-9fed8700-9941-11eb-976d-06a56074303f.PNG)
![IMG-3970](https://user-images.githubusercontent.com/17608491/114238290-9fed8700-9941-11eb-9079-13da0a8bb1a4.PNG)
![IMG-3971](https://user-images.githubusercontent.com/17608491/114238292-a0861d80-9941-11eb-8d3d-2a1c7fadcbd1.PNG)
![IMG-3972](https://user-images.githubusercontent.com/17608491/114238293-a0861d80-9941-11eb-9f11-4db0ed2a9c77.PNG)
![IMG-3973](https://user-images.githubusercontent.com/17608491/114238295-a0861d80-9941-11eb-9e78-42d724f4ce89.PNG)
![IMG-3974](https://user-images.githubusercontent.com/17608491/114238298-a11eb400-9941-11eb-9476-8bf23f90c339.PNG)
![IMG-3975](https://user-images.githubusercontent.com/17608491/114238299-a11eb400-9941-11eb-839c-419d3261b0f7.PNG)

**Describe the bug**

This happens on iOS (iPhone X specifically), whereas in Android, everything is correct and renders as expected.
Weird rendering behavior on first few indices of tabs (0 and 1):
- Layout is not centered.
- GridLayout is messed up.
- View disappearing on re-loaded (sometimes).
I came up with the above hypothesis error when I switched TabContentItem's order and it renders the contents correctly on latter indices. 

**To Reproduce**

On iOS device (I tested with an iPhone X):
There are 2 TabContentItem-s that I have implemented (TasksToday and BudgetWallet on indices 0 and 4 respectively). TasksToday's view is really messed up, whereas BudgetWallet's view is as expected. If you make both of them on 0 and 1 indices, they are both messed up. On the other hand, if you swap them with TabContentItem on 3 and 4 indices, they work as expected. Hence, I came up with the hypothesis error above.

**Sample project**

https://play.nativescript.org/?template=play-ng&id=PhTkb8&v=7

**Comment by kenzend** [comment]
Update: Change the currentTabIndex and defaultSelected variables from 2 to 0 in home.component.ts seems to fix the error but I would like to keep the same bottom nav order and the starting selected index as 2 (the home icon).

**Comment by valera1401** [comment]
Also have the same issue.


> Change the currentTabIndex and defaultSelected variables from 2 to 0 in home.component.ts seems to fix the error

It doesnt fix the error. Try go on tab 2 from tab 0 with tap, but not with swipe. Then go to tab 1. Layout on tab 1 will be broken.

**Comment by kenzend** [comment]
Yes, confirmed! For some context: I use the featured cradle tab bottom navigation from https://blog.nativescript.org/tabs-and-bottomnavigation-nativescripts-two-new-components/ 
The tabs behavior is not consistent.

**Comment by farfromrefug** [comment]
@rigor789 @NathanWalker after looking into this i found out it is a  safearea issue.
For some reason the applying of safe area to the gridlayout inside the scrollview is breaking the layout.
Using `iOSIgnoreSafearea` on that gidlayout is a workaround but we should definitely investigate why the safe area is breaking the layout (and it happens only when the  tab viewcontroller of the scrollview is not the one "seen" on start).

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
