### ISSUE TITLE
Upgraded project to v. 8 remove webpack.config.js

### ISSUE THREAD

**Issue by ignacio68** [NativeScript/NativeScript#9327]
I've tried to migrate a nativescript-vue v.7 project to the new version 8.0. All are ok but the old webpack.config.js file is remove and the new file isn't generated.

**Comment by NathanWalker** [comment]
Try running:
npx nativescript-webpack init

**Comment by ignacio68** [comment]
Thank you. Now I have to customize the config file, ok.

**Comment by rigor789** [comment]
@ignacio68 see docs on the new config format: https://docs.nativescript.org/webpack.html

And fee free to ask here/discord if you need help figuring out the right syntax for your customizations!
