### ISSUE TITLE
Please provide an API reference for core v8

### ISSUE THREAD

**Issue by marcelklehr** [NativeScript/NativeScript#9331]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I don't have a comprehensive API reference for a library or framework. 

**Describe the solution you'd like**
I'd like to have an API reference available for nativescript/core v8.x

**Describe alternatives you've considered**
Using the API reference for v7 and potentially failing hard.

**Additional context**
None.

**Comment by NathanWalker** [comment]
Published here: https://docs.nativescript.org/api-reference/
