### ISSUE TITLE
JavaProxy does not work

### ISSUE THREAD

**Issue by mrh1997** [NativeScript/NativeScript#9337]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.1
 - Cross-platform modules: 8.0.1 (also tested 7.0.0)
 - Android Runtime: 8.0.0 (also tested 7.0.0)

**Describe the bug**
When extending a Java class via ``@JavaProxy(...)`` I always get the following runtimeerror:
```
Error: com.tns.system.classes.loading.LookedUpClassNotFound: Class "com.tns.notifications.NotificationIntentService" not found.
```

When using the pure-javascript way (extend method of the base class) everything works fine.

**To Reproduce**
Add the following piece of code to your project:

```typescript
@JavaProxy("com.tns.notifications.NotificationIntentService")
class Bf3UpdateService extends android.app.IntentService {
}
```

When adding the following (theoreticially identical) code everything works fine:
```javascript
android.app.IntentService.extend("com.tns.notifications.NotificationIntentService", {})
```

**Comment by triniwiz** [comment]
```ts
@NativeClass()
@JavaProxy("com.tns.notifications.NotificationIntentService")
class Bf3UpdateService extends android.app.IntentService {
}
```
