### ISSUE TITLE
[webpack-cli] Error: Unknown option '--env.hmr'

### ISSUE THREAD

**Issue by tbhaxor** [NativeScript/NativeScript#9341]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.2.1
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - XCode Version:
 - Plugin(s):

**Describe the bug**

_Title is self explainatory_

**To Reproduce**

1. Setup new native script `tns create --vue HelloWorld`
2. Create a new genymotion motion
3. Run the app `tns run android --geny NativeScript`

**Expected behavior**

Well it should run in genymotion file

**Sample project**

_create a new project_

**Additional context**

![image](https://user-images.githubusercontent.com/28386721/115116731-dae26100-9fb8-11eb-87f7-dd7cb0f5aaca.png)

**Comment by rigor789** [comment]
Update your CLI to `8.0.1`

**Comment by tbhaxor** [comment]
@rigor789 I am getting new error. 

![image](https://user-images.githubusercontent.com/28386721/115121244-2dc71300-9fcf-11eb-82f4-b29f4ad78695.png)

I setup the anndroid from [here](https://wiki.archlinux.org/index.php/Android)

**Comment by rigor789** [comment]
@tbhaxor make sure you install a JDK (Java Development Kit) and not just a JRE (Java Runtime Environment). OpenJDK 8 should be fine.

**Comment by tbhaxor** [comment]
@rigor789  It is working but HMR ain't working. I have to close and reopen the app in genymotion

**Comment by rsun-thoughtworks** [comment]
I cannot believe that as a release version 7.2.1 cli cannot create a project that actually works.

Maybe it is not a good idea to let version to be "beta".

**Comment by dstar22** [comment]
> I cannot believe that as a release version 7.2.1 cli cannot create a project that actually works.
> 
> Maybe it is not a good idea to let version to be "beta".

SOO true it literally took my 2months to find this we cant even create project for angular

**Comment by sylwesterdigital** [comment]
it's called sabotage. RIP nativescript.

**Comment by NathanWalker** [comment]
@sylwesterdigital 
https://github.com/adobe/brackets/issues/15330

your comments are unhelpful and remembered in all of open source. Thanks for sharing who you are and who we should steer away from.

**Comment by tbhaxor** [comment]
@NathanWalker Cool down bro. I cant see the comments made by him/her/it

**Comment by NathanWalker** [comment]
Sounds good - he deleted his comment so at least he gained some sense.
We'll close this since `--env.hmr` is no longer used since hmr is on by default (and has been for quite long time now) - You can disable with `--no-hmr` flag.
