### ISSUE TITLE
Nativescript Web page contributions.

### ISSUE THREAD

**Issue by LaKing** [NativeScript/NativeScript#9342]
Please provide a way to contribute to the NS documentation.

There are a couple of hints, fixes, and corrections that would make working with NS more straight forward.
Examples: 

Environment Setup... 
- A side note that installing Xcode requires about 50G disk space would have saved me a day.
- MacOs section: The zsh profile file is `.zprofile`
- `gem install ...` may/does require sudo
- `gem env` will give a hint where to look for missing binaries. 
- An entry in PATH is required to the bin directory, eg: `/usr/local/lib/ruby/gems/2.7.0/bin` 

- `ns preview` does not work currently with all components, eg read-write text field causes crash ...

And so on ...

**Comment by NathanaelA** [comment]
Hi @LaKing - Thanks for wanting to contribute -- the docs repo is located here: https://github.com/NativeScript/docs-new, please feel free to clone them and create a PR for any changes you think make the docs easier to read and onboard people.

One minor note; `ns-preview` should work with any components that is built into the core NativeScript.  If the external plugin  us pure JS/TS then it should also work fine.   If it requires a compiled modules (i.e. a aar/jar or cocoapod/lib) then yes, this is a unfortunate limitation in that we can't actually recompile the preview app on the phone adding new native Java/ObjC code...

**Comment by LaKing** [comment]
Thank you, @NathanaelA .. I'll make a couple of documentation contributions.

Please check https://github.com/NativeScript/NativeScript/issues/9330
