### ISSUE TITLE
Can tns-core-modules co-exists with @nativescript/core

### ISSUE THREAD

**Issue by rsun-thoughtworks** [NativeScript/NativeScript#9350]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.1
 - Cross-platform modules:
 - Android Runtime: 8.0.0
 - iOS Runtime:
 - XCode Version:
 - Plugin(s):

**Describe the bug**
I start from 8.0.1 cli, and create a new project with this command
```
ns create angular-demo --angular
```
Until now, everything works. I can build, debug this fresh new project.
Because I need `nativescript-facebook` to track installations, and this plugin requires `tns-core-modules`, to make it happy, I introduce tns-core-modules alone with @nativescript/core.

Now, I am not happy, because when I run 
```
ns debug android --emulator
```

I got this **ERROR MESSAGE**

> Error executing Static Binding Generator: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
File:/Users/xxx/code/private/opensource/nativescript-projects/angular-demo/platforms/android/app/src/main/java/com/tns/FragmentClass.java Class: com.tns.FragmentClass

![image](https://user-images.githubusercontent.com/44775081/115677893-860d6480-a383-11eb-8886-1cda9d5f1503.png)

**To Reproduce**

Described above.

**Expected behavior**

App can be debugged.

**Additional context**

I digged a little to the source code and found that both `tns-core-modules` and `@nativescript/core` extends `com.tns.FragmentClass` to the same `FragmentClass` classname.
I guess they cannot co-exists, but still need confirm from you people.

**Comment by vallemar** [comment]
@rsun-thoughtworks  I think this shouldn't do it, you are adding an old module, it does overload.  Why don't you fork the plugin, update it to the new @ nativescript / core and do a PR?  I would help the community and solve the problem.  (I haven't gone into the code but if it's just updating routes it shouldn't be a lot of work)

**Comment by triniwiz** [comment]
They cannot coexist in the later versions the plugin will need to be updated

**Comment by rsun-thoughtworks** [comment]
> They cannot coexist in the later versions the plugin will need to be updated

Thanks for confirming this.

**Comment by rsun-thoughtworks** [comment]
> @rsun-thoughtworks I think this shouldn't do it, you are adding an old module, it does overload. Why don't you fork the plugin, update it to the new @nativescript/core and do a PR? I would help the community and solve the problem. (I haven't gone into the code but if it's just updating routes it shouldn't be a lot of work)

Of cause, this is the best way, hope I can have more time to do it.
