### ISSUE TITLE
NS8 box-shadow and border-radius, z-index issues

### ISSUE THREAD

**Issue by kanclalg** [NativeScript/NativeScript#9353]
Hi, I was excited about NS8 box-shadow implementation, but looks like there are still few issues with it :(

1. Box-shadow does not work with border-radius.
 - on iOS it doesn't show shadow at all.
 - on Android it shows shadow with border-radius, but element itself is not rounded.
2. Strange behaviour when box-shadow is used with z-index. See screenshot

box-shadow + border-radius:
iOS:
![box-shadow-with-border-radius](https://user-images.githubusercontent.com/11705645/115871751-a142a780-a449-11eb-9bf2-23dc89088b9d.png)
Android:
![box-shadow-with-border-radius-android](https://user-images.githubusercontent.com/11705645/115872177-2ded6580-a44a-11eb-9080-1f46819c9e7c.png)

box-shadow + z-index:
iOS:
![box-shadow-with-z-index](https://user-images.githubusercontent.com/11705645/115871758-a30c6b00-a449-11eb-8af4-9782aa8e66a4.png)
Android:
![box-shadow-with-z-index-android](https://user-images.githubusercontent.com/11705645/115872193-3180ec80-a44a-11eb-98a1-9c8b6a08bb8a.png)

**Comment by maxaqquepucho** [comment]
I have the same issue, is there a temporary solution for this?

**Comment by AndreasKarlzzon** [comment]
+1
