### ISSUE TITLE
JS->Java Bridge fails to return Array to Java Service

### ISSUE THREAD

**Issue by mrh1997** [NativeScript/NativeScript#9355]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.1
 - Cross-platform modules: 8.0.2
 - Android Runtime: 8.0.0

**Describe the bug**
I created a backgroundservice with a JS method that has to return an array of byte to the Java VM.

**To Reproduce**
The following piece of code should return a byte array {0x90, 0x00} when calling ``MyHostApduService`` from java:
```typescript
@NativeClass()
@JavaProxy("com.tns.Bf3UpdateServiceJS")
class MyHostApduService extends android.nfc.cardemulation.HostApduService {
    processCommandApdu(commandApdu: number[], extras?: any): number[] {
        return [0x90,0x00]
    }
}
```
But when debugging into the java code I see, that ``callJsMethod(...)`` (which is called by processCommandApdu of the java proxy) always returns *null*.

**Expected behavior**
I would expect callJsMethod / the java proxy to return an array of bytes (with the values 0x90 and 0x00)

**Comment by triniwiz** [comment]
Another way you can ensure it’s the type of java array you need is to create a slice of that type there are a couple other ways to do that if the rt doesn’t handle the marshaling automatically 

```ts
const byteArray = Array.create(‘byte’,2);
byteArray[0] = 0x90;
byteArray[1] =0x00;
```

or 

```ts
const array = java.nio.ByteBuffer.wrap([0x90,0x00]).array();
```

**Comment by mrh1997** [comment]
Thanks for this hint. This actually solves my Problem.

But nevertheless I will keep the ticket open, as this behaviour contradicts the [chapter "Array" in the marshalling documentation](https://docs.nativescript.org/advanced-concepts.html#array-2). It claims that Javascript arrays are converted to java arrays automaticially...

**Comment by triniwiz** [comment]
@mrh1997 something came to mind can you try `[byte(0x90),byte(0x00)]` as the array if ts complains feel free to declare or ignore it

**Comment by triniwiz** [comment]
There is some more info here https://docs.nativescript.org/advanced-concepts.html#android-marshalling

**Comment by mrh1997** [comment]
@triniwiz : Why did you close the issue? As I mentioned in my [comment from Apr 25th](https://github.com/NativeScript/NativeScript/issues/9355#issuecomment-826166017) the link about marshalling contains **wrong** information! 

In the meantime I also tested ``[byte(0x90),byte(0x00)]`` as you asked me: it doesn't work either. 

The only working solution is your [comment from Apr 24th](https://github.com/NativeScript/NativeScript/issues/9355#issuecomment-826148970).

**Comment by mrh1997** [comment]
Ahh. According to the chapter "Array of primitive types" arrays of **primitive types are not marshalled** automaticially. 

Regarding your proposal (adding a constructor that returns ``global.__native(this)``): This didn't work, too. Neither did I find a documentation about the __native() function...

**Comment by triniwiz** [comment]
Take a look at [this](https://v7.docs.nativescript.org/core-concepts/android-runtime/binding-generator/extend-class-interface) it mentions the .native
