### ISSUE TITLE
Doesn't anyone noticed that the favicon of https://nativescript.org/ is missing?

### ISSUE THREAD

**Issue by georgebawesome** [NativeScript/NativeScript#9361]
Doesn't anyone noticed that the favicon of https://nativescript.org/ is missing?

**Comment by shirakaba** [comment]
It's present on Safari:

<img width="112" alt="image" src="https://user-images.githubusercontent.com/14055146/116269910-8c7e5080-a776-11eb-9a77-d5654aeaf086.png">


(Though it is the old colour scheme)

**Comment by georgebawesome** [comment]
Buy I think it is not on Chrome Windows 10

**Comment by shirakaba** [comment]
True, Chrome for macOS also doesn't show a favicon.

**Comment by georgebawesome** [comment]
And chrome in Android also shows up any favicon

**Comment by shirakaba** [comment]
Doesn't display on Firefox for macOS, either.

**Comment by shirakaba** [comment]
I get this message on Firefox:

<img width="599" alt="image" src="https://user-images.githubusercontent.com/14055146/116275371-79ba4a80-a77b-11eb-9243-07febb48e51a.png">

I guess maybe on Safari I might even just have a cached favicon from a previous visit.

**Comment by georgebawesome** [comment]
Have we got something to do with that?

**Comment by georgebawesome** [comment]
Just add it ☺️

**Comment by shirakaba** [comment]
> Just add it ☺️

PRs welcome!

**Comment by rigor789** [comment]
Fixed for docs & blog now.
