### ISSUE TITLE
Cannot run Test directly from the HelloWorld template without one single line of code change

### ISSUE THREAD

**Issue by cupidchan** [NativeScript/NativeScript#9362]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ Component nativescript has 8.0.1 version and is up to date.
 - Android Runtime: 4.1.3
 - iOS Runtime: 12.4
 - XCode Version: 12.4
 - Plugin(s):

**Describe the bug**
Cannot run `ns test ios` or `ns test android` even it's just the HelloWord template directly from NativeScript WITHOUT one line of code added.

**To Reproduce**
- create a project call HelloWorld `ns create HelloWorld`
- 'cd HelloWorld'
- `ns test init` and pick Jasmine
- 'ns test ios' or `ns test android` => FAILED

**Expected behavior**
Test should run

**Sample project**
https://github.com/cupidchan/HelloWorld

**Additional context**
Searching for devices...
27 04 2021 18:44:17.749:WARN [karma-server]: Passing raw CLI options to `new Server(config, done)` is deprecated. Use `parseConfig(configFilePath, cliOptions, {promiseConfig: true, throwErrors: true})` to prepare a processed `Config` instance and pass that as the `config` argument instead.
[@nativescript/webpack] Warn: 
 Cannot find NativeScript CLI path. Make sure --env.nativescriptLibPath is passed
27 04 2021 18:44:19.305:ERROR [plugin]: Cannot find plugin "/Users/cupidchan/Documents/temp/HelloWorld/node_modules/karma-webpack".
  Did you forget to install it?
  npm install /Users/cupidchan/Documents/temp/HelloWorld/node_modules/karma-webpack --save-dev
27 04 2021 18:44:19.309:ERROR [plugin]: Cannot load "webpack", it is not registered!
  Perhaps you are missing some plugin?
27 04 2021 18:44:19.325:ERROR [karma-server]: Error during file loading or preprocessing
TypeError: process is not a function
    at executeProcessor (/Users/cupidchan/Documents/temp/HelloWorld/node_modules/karma/lib/preprocessor.js:47:11)
    at runProcessors (/Users/cupidchan/Documents/temp/HelloWorld/node_modules/karma/lib/preprocessor.js:60:23)
    at FileList.preprocess [as _preprocess] (/Users/cupidchan/Documents/temp/HelloWorld/node_modules/karma/lib/preprocessor.js:106:11)
    at async Promise.all (index 0)
    at async /Users/cupidchan/Documents/temp/HelloWorld/node_modules/karma/lib/file-list.js:90:11
    at async Promise.all (index 3)
27 04 2021 18:44:19.328:INFO [karma-server]: Karma v6.3.2 server started at http://localhost:9876/
27 04 2021 18:44:19.328:INFO [launcher]: Launching browsers ios with concurrency unlimited
27 04 2021 18:44:19.329:ERROR [karma-server]: Error: Found 2 load errors
    at Server.<anonymous> (/Users/cupidchan/Documents/temp/HelloWorld/node_modules/karma/lib/server.js:239:26)
    at Object.onceWrapper (events.js:420:28)
    at Server.emit (events.js:326:22)
    at emitListeningNT (net.js:1350:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
Test run failed.

**Comment by alexist** [comment]
Same issue

**Comment by cupidchan** [comment]
I found a way to make it work:

- `npm install karma-webpack@next --save-dev`
- In karma.conf.js, add webpack to frameworks section `frameworks: ['jasmine', 'webpack']`
- In tsconfig.json, add `src/tests/**/*.ts` in include section `"include": ["src/tests/**/*.ts", "src/**/*.ios.ts", "src/**/*.android.ts"],`
