### ISSUE TITLE
Nativescript Docs - fixing template command

### ISSUE THREAD

**Issue by markosole** [NativeScript/NativeScript#9364]
I've noticed some minor errors in NS Docs page which can be misleading for many beginners. 

Template with Drawer (Side Drawer):

    ns create myCoolApp --template @nativescript/template-blank

Should be changed to:

    ns create myCoolApp --template @nativescript/template-drawer-navigation

You should add url for "Recommend or report errors in Docs". Thank I will help more with this. 

Regards.

**Comment by janoshrubos** [comment]
Thank you for you issue!

The command for drawer navigation should appear well now. 
The issue handling on the new docs is in work in progress also!
