### ISSUE TITLE
Regarding Apple's forcing to us to use XCode 12

### ISSUE THREAD

**Issue by mrunals1994** [NativeScript/NativeScript#9366]
Getting error: Unable to apply changes on device. Error is: Command xcodebuild failed with exit code 65.

Old environment setup that works:

Nativescript-Vue 6
Nativescript CLI 6.8.0
TNS 6.8.0
XCode 11
Package:
    "tns-android": {
      "version": "6.5.3"
    },
    "tns-ios": {
      "version": "6.5.2"
    }

New environment that doesn't work:

Nativescript-Vue 6
Nativescript CLI 7.2.0
TNS 7.2.0
XCode 12
Package:
    "tns-android": {
      "version": "6.5.3"
    },
    "tns-ios": {
      "version": "6.5.3"
    }

**What we have tried:**

Adding Podfile in app/App_Resources/ios:

First Podfile attempt
`post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
			config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
			config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
		end
	end
end`

Second Podfile attempt
`post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end`

Error in Console: 
![image(2)](https://user-images.githubusercontent.com/83418749/116585496-19bbd380-a936-11eb-9089-b1d78493316c.png)

**Comment by NathanWalker** [comment]
@mrunals1994 change to use `6.5.4` of tns-ios specifically, ie:
```
"tns-ios": {
"version": "6.5.4"
}
```
Add this to your Podfile:

```
platform :ios, '13.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
```

Then add this to your build.xcconfig:

```
IPHONEOS_DEPLOYMENT_TARGET = 13.0;
```

Make sure you have latest cli installed `npm i -g nativescript@latest` (should be 8.0.1) then `ns clean` and run.

**Comment by mrunals1994** [comment]
@NathanWalker Thank you for your response but this solution doesn't work for me. It is throwing same error as above.

**Comment by NathanWalker** [comment]
Please share your pacalage.json, build.xcconfig, Podfile and the results of ‘ns doctor’

**Comment by keithoys** [comment]
Hi @NathanWalker we're working on the same project.

**package.json**

```
"nativescript": {
    "templateVersion": "v2",
    "tns-android": {
      "version": "6.5.3"
    },
    "tns-ios": {
      "version": "6.5.4"
    }
  },
  "scripts": {
    "start": "tns debug ios --env.development --env.uglify",
    "serve:ios": "npm start",
    "serve:ios-dev": "tns debug ios --env.development --env.uglify",
    "serve:ios-qa": "tns debug ios --env.qa --env.uglify --force",
    "serve:ios-staging": "tns debug ios --env.staging --env.uglify",
    "serve:ios-prod": "tns debug ios --env.production --env.uglify",
    "serve:android": "tns debug android --env.development --env.uglify --env.snapshot",
    "serve:android-dev": "npm run serve:android --env.development --env.uglify --env.snapshot",
    "serve:android-qa": "tns debug android --env.qa --env.uglify --env.snapshot",
    "serve:android-staging": "tns debug android --env.staging --env.uglify --env.snapshot",
    "serve:android-prod": "tns debug android --env.production --env.uglify --env.snapshot",
    "build:ios": "tns build ios --env.setup --release --for-device",
    "build:ios-dev": "tns build ios --env.development --release --for-device",
    "build:ios-qa": "tns build ios --env.qa --release --for-device",
    "build:ios-staging": "tns build ios --env.staging --release --for-device",
    "build:ios-beta": "tns build ios --env.staging --release --for-device",
    "build:android": "tns build android --env.setup --bundle",
    "build:android-dev": "tns build android --env.dev --bundle",
    "build:android-staging": "tns build android --env.staging --bundle",
    "build:android-qa": "tns build android --env.qa --bundle",
    "build:android-prod": "tns build android --env.production --bundle"
  },
  "dependencies": {
    "@nstudio/nativescript-pulltorefresh": "^2.0.0",
    "base-64": "^0.1.0",
    "chalk": "^3.0.0",
    "edit-json-file": "^1.4.0",
    "figlet": "^1.2.4",
    "inquirer": "^7.0.0",
    "moment": "^2.24.0",
    "nativescript-app-tour": "^2.0.2",
    "nativescript-appversion": "^1.4.4",
    "nativescript-couchbase-plugin": "^0.9.6",
    "nativescript-fingerprint-auth": "^7.0.2",
    "nativescript-image-cache-it": "^6.0.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-localize": "^4.2.0",
    "nativescript-lottie": "^4.0.1",
    "nativescript-pdf-view": "^2.4.3",
    "nativescript-permissions": "^1.3.8",
    "nativescript-plugin-firebase": "^10.4.0",
    "nativescript-range-seek-bar": "^1.0.3",
    "nativescript-ui-autocomplete": "^6.0.0",
    "nativescript-ui-listview": "^8.0.1",
    "nativescript-vue": "~2.7.1",
    "nativescript-vue-navigator": "^1.2.0",
    "nativescript-windowed-modal": "^6.2.1",
    "tns-core-modules": "^6.5.8",
    "vue-class-component": "^7.1.0",
    "vue-property-decorator": "^8.3.0",
    "vuex": "^3.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@types/node": "^12.12.6",
    "babel-loader": "^8.0.2",
    "nativescript-dev-webpack": "^1.5.1",
    "nativescript-vue-template-compiler": "~2.7.1",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "shelljs": "^0.8.4",
    "tns-ios": "6.5.3",
    "tns-platform-declarations": "^6.3.2",
    "typescript": "^3.2.4",
    "vue": "^2.5.22",
    "vue-loader": "^15.4.0",
    "vuex-class": "^0.3.2",
    "vuex-module-decorators": "^0.16.1",
    "webpack-bundle-analyzer": "^3.9.0"
  }
}
```

**build.xcconfig**

```
ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME = LaunchImage;
IPHONEOS_DEPLOYMENT_TARGET = 13.0;
```

**Podfile**

```
platform :ios, '13.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
```

**ns doctor**

![image](https://user-images.githubusercontent.com/7553961/116848705-bd9bcc80-ac1f-11eb-8561-75a1e68325a2.png)

**node -v**

`v14.15.0`

**npm -v**

`6.14.8`

Appreciate your kind assistance.

**Comment by NathanWalker** [comment]
@keithoys is there anyway to share the project privately? You can send email to support@nativescript.org - would be helpful to be able to run it to provide further insight. We have same versions/setup here working against similar dependencies.

**Comment by NathanWalker** [comment]
@keithoys @mrunals1994 something else you can also try, remove this entire section from your package.json:
```
"nativescript": {
    "templateVersion": "v2",
    "tns-android": {
      "version": "6.5.3"
    },
    "tns-ios": {
      "version": "6.5.4"
    }
  },
```
Remove entire section, yes. Then add these 2 dep's to your `devDependencies` and then do a `ns clean` and try to run again:
```
"devDependencies": {
  ...,
  "@nativescript/android": "8.0.0",
  "@nativescript/ios": "8.0.0",
  ...
}
```

Take particular note that your devDependencies above are *incorrect* and contain something conflicting that you need to remove manually:
```
"tns-ios": "6.5.3",
```
is in your devDependencies and likely causing you all the trouble.

**Comment by keithoys** [comment]
Hello @NathanWalker just tried with the above changes you suggested to no avail as well:

![image](https://user-images.githubusercontent.com/7553961/116953618-4c602600-acc0-11eb-9dca-951ac644b422.png)

![image](https://user-images.githubusercontent.com/7553961/116953638-597d1500-acc0-11eb-8de9-c6317d1761f8.png)

**Comment by keithoys** [comment]
I think I finally solved it by moving `IPHONEOS_DEPLOYMENT_TARGET = 13.0;` to the top of **build.xcconfig**.

The original file actually contained the following:

```
// You can add custom settings here
// for example you can uncomment the following line to force distribution code signing
// CODE_SIGN_IDENTITY = iOS Developer
// To build for device with Xcode 8 you need to specify your development team. More info: https://developer.apple.com/library/prerelease/content/releasenotes/DeveloperTools/RN-Xcode/Introduction.html
IPHONEOS_DEPLOYMENT_TARGET = 13.0;
DEVELOPMENT_TEAM = XXX;
ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME = LaunchImage;
```

**Comment by keithoys** [comment]
Finally managed to run our application with the configurations above. Thank you so much for your kind assistance @NathanWalker!!

**Comment by NathanWalker** [comment]
Great to hear thanks for letting us know!
