### ISSUE TITLE
After upgrading to V8, the ActionBar became smaller in height on the real device

### ISSUE THREAD

**Issue by Bezlepkin** [NativeScript/NativeScript#9375]
**Environment**
- NS 8.0.1
- Device ZTE Blade A5 2020 (Android 9)
 - CLI: 11.1.3
 - Cross-platform modules: 
 - Android Runtime: 8.0.0
 - iOS Runtime: 8.0.0
 - XCode Version:
 - Plugin(s): 

After the update to NS8, the ActionBar has become smaller in height and the content in it is not horizontal. In NS7. Everything was fine. The ActionBar was the same on both the emulator and the real device.

The screenshot shows that the Native Script Playground ActionBar app looks correct.

![IMG_5089](https://user-images.githubusercontent.com/10475699/117118028-e8f5f700-ad98-11eb-8718-2ba29494f79e.JPG)
![IMG_5088](https://user-images.githubusercontent.com/10475699/117118041-ee534180-ad98-11eb-9be8-d532df9e54e2.JPG)
![photo_2021-05-05_11-48-48](https://user-images.githubusercontent.com/10475699/117118049-f14e3200-ad98-11eb-9830-e3ba2a9cd78b.jpg)

**Comment by cjohn001** [comment]
+1

**Comment by farfromrefug** [comment]
Actually it looks to me like rhe new one is the right one following the material specs. Especially the text being left aligned. ( i dont use N actionbar).
I am not sure about the height though. Any chance you can compare it to native material same app ?

**Comment by cjohn001** [comment]
@Bezlepkin : Have you found a solution to bring back the old behavior?

**Comment by Bezlepkin** [comment]
> Have you found a solution to bring back the old behavior?

yes. App_Resources/Android/src/main/res/values-v21/styles.xml
![2021-09-01_09-28-50](https://user-images.githubusercontent.com/10475699/131622744-47830e6a-7b75-4cb0-bbbc-21beb80b6fcf.png)

**Comment by Bezlepkin** [comment]
> @Belepkin: Thank you for the update. Unfortunately it does not work for me, than the statusbar is completely overlaying my actionbar. Have you set a different flag to also configure the statusbar?

hhhmmmmm... maybe it?!

<item name="android:windowTranslucentStatus">false</item>
