### ISSUE TITLE
ImageSource .resize() on iOS with transparent background images turns to black

### ISSUE THREAD

**Issue by liamcharmer** [NativeScript/NativeScript#9385]
nativescript has 8.0.1 version and is up to date.
@nativescript/core has 8.0.4 version and is up to date.
@nativescript/ios has 8.0.0 version and is up to date.
@nativescript/android has 8.0.0 version and is up to date.

**Bug**
Retrieve an image using ImageSource.fromUrl(), which then needs to be resized down. The image is a .png with a transparent background. Once resized, on Android works fine, on iOS however the transparency becomes black. You can see see the PNG image on top of the black background. No errors occur however expected outcome not achieved. 

**To Reproduce**
Resize a png image with a transparent background.

**Comment by liamcharmer** [comment]
For now used the following code to resize exclusively for iOS

(theImage being original image that i've retrieved, and then the newImage replaces .ios of the original image)

```UIGraphicsBeginImageContextWithOptions(
                  { width: 75, height: 75 },
                  false,
                  0.0
                );
                theImage.ios.drawInRect(CGRectMake(0, 0, 75, 75));
                let newImage = UIGraphicsGetImageFromCurrentImageContext();
                UIGraphicsEndImageContext();
                theImage.ios = newImage;```

**Comment by NathanWalker** [comment]
@liamcharmer when you get a chance this fix is now published with “next” tag if could confirm. It will be published along with others in patch this week.
