### ISSUE TITLE
CSS not applied with NativeScript 1.4.1

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#939]
_From @sebawita on October 14, 2015 11:23_

When I create a project from scratch using NativeScript 1.4.1 and run it on Samsung Edge+ (Android 5.1.1) app.css doesn't seem to be applied.

I have not tested it on any other device.

However when I build and run my older projects that were created with {N} 1.3 the css seems to be working fine.

_Copied from original issue: NativeScript/nativescript-cli#1062_

**Comment by vchimev** [comment]
Hi @sebawita,

I am not able to reproduce such an issue. Could you please try to run your project on any other device or emulators?

**Comment by enchev** [comment]
Not enough info to reproduce.
