### ISSUE TITLE
[NS8] NativeScript 7 (Angular, Schematics) project hitting "JavaScript heap out of memory" when upgraded to NS8

### ISSUE THREAD

**Issue by mahmoudajawad** [NativeScript/NativeScript#9407]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: v8.0.2
 - Cross-platform modules: 
 - Android Runtime: N/A
 - iOS Runtime: v8.0.0
 - XCode Version: v12.4 on macOS 10.15.7
 - Node: v15.14.0
 - npm: v7.7.6
 - Plugin(s): package.json:
```json
  {
    "@angular/animations": "~11.2.7",
    "@angular/common": "~11.2.7",
    "@angular/compiler": "~11.2.7",
    "@angular/core": "~11.2.7",
    "@angular/forms": "~11.2.7",
    "@angular/platform-browser": "~11.2.7",
    "@angular/platform-browser-dynamic": "~11.2.7",
    "@angular/router": "~11.2.7",
    "@nativescript-community/ui-material-bottomsheet": "^5.3.0",
    "@nativescript/angular": "~11.8.0",
    "@nativescript/background-http": "^5.0.2",
    "@nativescript/core": "~8.0.0",
    "@nativescript/firebase": "^11.1.3",
    "@nativescript/imagepicker": "^1.0.4",
    "@nativescript/theme": "~3.0.1",
    "angular-l10n": "^11.1.0",
    "jsrsasign": "^10.2.0",
    "nativescript-carousel": "^7.0.1",
    "nativescript-modal-datetimepicker": "^2.1.5",
    "nativescript-urlhandler": "^1.3.0",
    "nativescript-websockets": "^1.5.6",
    "reflect-metadata": "~0.1.13",
    "rxjs": "~6.6.7",
    "zone.js": "~0.11.4"
  }
```

**Describe the bug**
I have a project that is created using angular schematics lib to generate a shared web and mobile project. I wanted to migrate the project to NS8 using `ns migrate` but found it fails for schematics projects, and had to do manually. For that, I created a new project, and manually began to migrate difference pieces into the new project. The process worked fine, until I hit the last patch of files when it seems webpack is hitting a memory limit with the current error in console:
```
<--- Last few GCs --->

[23151:0x104a0f000]  1162148 ms: Scavenge (reduce) 4069.4 (4133.2) -> 4068.6 (4133.2) MB, 3.1 / 0.0 ms  (average mu = 0.241, current mu = 0.238) allocation failure 
[23151:0x104a0f000]  1162160 ms: Scavenge (reduce) 4070.5 (4134.2) -> 4069.6 (4134.2) MB, 3.8 / 0.0 ms  (average mu = 0.241, current mu = 0.238) allocation failure 
[23151:0x104a0f000]  1162170 ms: Scavenge (reduce) 4071.5 (4135.2) -> 4070.7 (4135.2) MB, 3.9 / 0.0 ms  (average mu = 0.241, current mu = 0.238) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x101397115 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000c6979 node::Abort() [/usr/local/bin/node]
 3: 0x1000c6adf node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1002461f7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x100246193 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 6: 0x100401305 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 7: 0x100402ec3 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 8: 0x1003fef2f v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x1003fc8bd v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
10: 0x10040a51a v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x10040a5a1 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
12: 0x1003d224e v8::internal::FactoryBase<v8::internal::Factory>::NewRawTwoByteString(int, v8::internal::AllocationType) [/usr/local/bin/node]
13: 0x10066dc08 v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::AllocationType) [/usr/local/bin/node]
14: 0x100671a82 v8::internal::String::SlowEquals(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::String>) [/usr/local/bin/node]
15: 0x1007a1c61 v8::internal::Runtime_StringEqual(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
16: 0x100adab39 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
17: 0x100ab9b97 Builtins_StrictEqual_WithFeedback [/usr/local/bin/node]
18: 0x3ca85bb06e26 
```

**To Reproduce**

I repeated the process in different order to make sure it is not one of the files that is causing the issue, but I ended up with the same results when I reached near-end to finish the migration process. The project is private, I can't provide it for inspection.

**Additional context**
In the second attempt, I kept NS CLI running and continued to to migrate piece by piece (I installed all the plugins before the migration starts, and asserted all are working fine by importing angular modules before migrating the project) and the issue still came up.

**Comment by mahmoudajawad** [comment]
Yes, I do confirm the issue is the naming scheme we follow for this project. Once all style files were changed to `NAME.component.css`, the app has worked. Current project is using `beta` version of `@nativescript/webpack` which tags `5.0.0-beta.10`

**Comment by robertcbit** [comment]
THANK YOU!!! you literally just saved my sanity! - pretty sure I was headed toward a melt-down trying to figure out why some of my components styling would not render.  I recently converted my old NS6 to NS8, had to create a new project and migrate everything in manually, it's been 3 weeks or so now and I HOPE this is the last issue remaining.  Exactly the same, I had a few css files named like files.css, imagehandler.css, etc. once I renamed to files.component.css... instantly rendered.  Additionally, when I had the files named wrong navigating to the component would take up to 20, 30 seconds, fyi... wish I found this post a few days ago!

**Comment by mahmoudajawad** [comment]
Glad this helped you, @robertcbi, and I'm looking forward to seeing this issue resolved by the great nativescript team.

**Comment by mahmoudajawad** [comment]
@cjohn001, should I close this issue as you mentioned it is already fixed in v5 of `@nativescript/webpack` package?

**Comment by cjohn001** [comment]
@mahmoudajawad . Yes I think the issue can be closed. Was solved for me as well.
