### ISSUE TITLE
[Request] ListView getFirstVisiblePosition() API 

### ISSUE THREAD

**Issue by HakobiDev** [NativeScript/NativeScript#9409]
**Is your feature request related to a problem? Please describe.**
Listview getting current first visible index for appending new data after first visible similar to FB's AI content suggestion to attract more user using app.  This will help my app or other developers to customize ListView, I check some community alternatives it seems {N} Core Listview is best suitable for my use-case and its speed and smoothness. I hope it give a chance to expose it.

**Describe the solution you'd like**
It is possible to use getFirstVisiblePosition API at isItemAtIndexVisible method to get first visible args.Index without trigger of itemTap. 

[ https://developer.android.com/reference/android/widget/AdapterView.html#getFirstVisiblePosition()]( https://developer.android.com/reference/android/widget/AdapterView.html#getFirstVisiblePosition())

**Other Context**
Limitation of isItemAtIndexVisible is causing bottleneck for pulling the index via itemLoading and calling isItemAtIndexVisible that affecting in scrolling performance.

**Comment by nikoTM** [comment]
```
listView.android.setOnScrollListener(
  new android.widget.AbsListView.OnScrollListener({
    onScroll(
      view: View,
      firstVisibleItem: number,
      visibleItemCount: number,
      totalItemCount: number
    ) {
      // firstVisibleItem is what you are looking for?
    },
    onScrollStateChanged(view: View, scrollState: any) {
      // Can wait here for scroll state to get idle (android.widget.AbsListView.OnScrollListener.SCROLL_STATE_IDLE)
    },
  })
);
```

You can just set a listener to your ListView and listen to changes of firstVisibleItem, or did I misunderstand what you needed?

**Comment by HakobiDev** [comment]
@nikoTM Thanks for this, I already tried to hook up on scroll event it seems that hooking gives me a GC Hit or UI freeze, the requested direct method is same as RLV current firstVisible.

**Comment by nikoTM** [comment]
@HakobiDev okay, thanks for the clarification, but. I still don't understand why it's a feature request, you can just do something like:

```typescript
const list = this.page.getViewById("myList");

    if (list) {
      console.log(list.nativeView.getFirstVisiblePosition());
    }
```

Why do you want a proxy method that calls the same for you?

**Comment by HakobiDev** [comment]
@nikoTM Thanks, I already removed in my project.
