### ISSUE TITLE
global.ios missing (consistancy)

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#941]
global.android is defined when the app is running on a Android.  However global.ios is never defined.  Either add global.ios or remove global.android to keep platform consistancy as when anyone sees a global.android they will assume the other global.PLATFORMS exists also.

**Comment by enchev** [comment]
Hey @NathanaelA, 

I believe that *android* comes from the namespaces exposed while in the other hand there are no namespaces in iTS platform and that is why there is no global ios object defined.

If you want to check in your code what is the current platform you can use our *platform* module.

Thanks

**Comment by NathanaelA** [comment]
@enchev - I'm not actually sure where global.android gets defined, but it is defined and it is used in several places in the NativeScript code base, so anyone digging into the code will see it.  Any sane developer who sees global.android, is going to assume global.ios and global.windows will be defined on their respective platforms.  In fact I almost wrote some verbiage about it in C6 because I made the assumption that if global.android worked on Androids, then global.ios would be defined on iOS devices.  Of course it didn't...  

Missing consistency drives me nuts.   Even if we need to add it to the global.js file so that it check and sets it global.ios = true or global.windows = true on their respective platforms, that would be totally acceptable.   But having these always be evaluated to false; is not good for consistency...

**Comment by atanasovg** [comment]
@NathanaelA: @enchev is correct - the Android Runtime injects these [top-level packages](http://developer.android.com/reference/packages.html) directly into the global context. Consider for example the `android.widget.Button` expression - `android` here is actually `global.android`. In iOS there are no such top-level packages, the entire API is available at the global context and the equivalent of the previous expression is `UIButton`. So, `global.android` is **not** something that we do explicitly to mark the current execution context. It is just the way the native Android APIs work. With that said, adding an artificial `global.ios` property, be it at Runtime or at JS level, simply does not make sense to me.

**Comment by NathanaelA** [comment]
@atanasovg  -- Ok, I understand what you are saying, this is a side effect of injecting the api's into the namespace.  I don't have an issue with that.

However, then I would highly recommend everywhere you are currently using global.android as a platform flag, that it be totally removed.  You should not be using a global "feature" flag in the NativeScript you don't intend to be cross platform.   The implication when you are using code in the common NativeScript:   **if (global.android) { do x  }**
Makes other developers assume that since global.android is SUPPORTED and used by the NativeScript team; is that global.ios and global.windows would also be supported to check to see if you are on those platforms.    

By just having global.android **used** in the common code to detect if you are on Android; you set up the implied expectation that this is a valid way to check android, ios and windows platforms.  Does that make sense?
