### ISSUE TITLE
can i build ios without mac

### ISSUE THREAD

**Issue by CyrusLiu158** [NativeScript/NativeScript#9410]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.2
 - XCode Version: 12.5
 - Plugin(s):  

**Describe the bug**
I run successfully in iphone ,but when i am ready to publish , build error:
@nativescript/core/platforms/ios/TNSWidgets.xcframework:1:1: While building for Mac Catalyst, no library for this platform was found in '.../node_modules/@nativescript/core/platforms/ios/TNSWidgets.xcframework'.

**Expected behavior**
I just want to publish in ios without macOs, how can i do that?

**Comment by mrwrighty** [comment]
You cannot, you require Xcode which runs on Mac to be able to publish.
