### ISSUE TITLE
@nativescript/webpack forces monorepos to use it's version of webpack

### ISSUE THREAD

**Issue by Logikgate** [NativeScript/NativeScript#9415]
When using the new webpack 5 version of @nativescript/webpack the webpack version is tied to an exact version:
https://github.com/NativeScript/NativeScript/blob/a9eed7e4c6d8184a936d71c76921e3c606028537/packages/webpack5/package.json#L49

We use nativescript in a monorepo which has a few different webpack configs.  It also includes webpack as its own dependency.  If that webpack dep is a different version than the one required by @nativescript/webpack strange errors like this show up:

<img width="1523" alt="Screen Shot 2021-05-24 at 4 30 38 PM" src="https://user-images.githubusercontent.com/2379994/119404140-654f6c00-bcad-11eb-96c7-1e2e00002d71.png">

This appears to be a similar issue to the one closed here: https://github.com/jantimon/html-webpack-plugin/issues/1451#issuecomment-637751352

That comment suggests that if you only have one version of webpack in your dependency tree then the error will go away. This is true in our case. If we match the version in our monorepo with that of the version required by @nativescript/webpack then this issue resolves itself.  However, this makes it so we are unable to upgrade webpack to stay up-to-date with the latest bug fixes and improvements.

In the webpack 4 version of this package the webpack dependency was an approximate one:
https://github.com/NativeScript/NativeScript/blob/4ef49f28aaa293e83e2604e9d268713620551c3b/packages/webpack/package.json#L78

Could this be changed in the webpack 5 version as well? I'm thinking a `^5.31.2` would be ok since minor versions shouldn't have breaking api changes that would affect this package.  If acceptable I'm happy to open a pull request to make the change.

**Comment by NathanWalker** [comment]
Thanks for tracking this @Logikgate we've had this on our radar for some time now and have been exploring some options as well as modifications to cli to help circumvent - the monorepo case is one we are particularly dialing with improvements.

**Comment by NathanWalker** [comment]
If you custom pack @nativescript/webpack@beta you can remove the 'webpack' dependency in it's package, repack it and used the .tgz in your monorepo and then manage the webpack dependency at root of monorepo (is one way temporarily).

**Comment by NathanWalker** [comment]
Fixed in 8.1
