### ISSUE TITLE
Feature request: Enable home button in Android ActionBar (plus tap event)

### ISSUE THREAD

**Issue by alexrainman** [NativeScript/NativeScript#942]
It can be really useful if you implement same API to add a button at the left to be used as SideDrawer toggle or just to add an icon to the left.

Now is possible on iOS adding ActionItem with icon and binding a function to toggle the SideDrawer but in Android i can only play with the ActionBar icon visibility but i cannot do something equivalent to this:

ActionBar.SetDisplayHomeAsUpEnabled(true);
ActionBar.SetHomeButtonEnabled(true);

And the use it to toggle SideDrawer.

**Comment by N3ll** [comment]
The discussion moves to https://github.com/NativeScript/NativeScript/issues/943.
