### ISSUE TITLE
JS issue on documentation user not able to access right side #navigation

### ISSUE THREAD

**Issue by akash-dew** [NativeScript/NativeScript#9424]
I am facing the attached issue on my mac book chrome. Please check. https://twitter.com/akashne07863433/status/1398099659743129602/photo/1

**Comment by HakobiDev** [comment]
Even Chrome at Windows same issue.

**Comment by pjabang1** [comment]
Same here. It throws :
Uncaught TypeError: Cannot read property 'offsetHeight' of null
    at $o (app.b17562fb.js:1)
    at window.addEventListener.capture (app.b17562fb.js:3)

**Comment by rigor789** [comment]
Fixed.
