### ISSUE TITLE
IOS Marshalling Error for boolean valued NSNumber, appears since NS7 and usage of new V8 IOS runtime

### ISSUE THREAD

**Issue by cjohn001** [NativeScript/NativeScript#9429]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.2
 
Please see demo-angular from here:
https://github.com/NativeScript/nativescript-ui-charts/tree/master/demo-angular

**Describe the bug**
I am trying to fix a bug in a plugin which uses a cocoapods library since a while. In the meantime I am sure that there must be something wrong with the marshalling of NSNumber objects (with boolean values) starting from NS7 onwards.

I have to set a property of type 
@property (nonatomic, readwrite) NSNumber *enabled 

to call a native function in a cocoapod

In objective c code the following ways are working with the library
 @NO
[[NSNumber alloc] initWithBool:NO]
[NSNumber numberWithBool:NO]

as far as I understood in the Nativescript docs, setting a boolean NSNumber is as simple as using a number type with 0 or 1. However, this does not seem to work.

**To Reproduce**
I upgraded the plugin demo sources to show the error. For reference, see links given in bug report section sample project

**Expected behavior**
Using  const value:number = 0 should be marshalled to an NSNumber with boolean value= NO

**Sample project**
https://github.com/NativeScript/nativescript-ui-charts/tree/master/demo-angular
The description on how to observe the bug can be found here
https://github.com/NativeScript/nativescript-ui-charts/issues/17#issuecomment-850885818

**Comment by triniwiz** [comment]
If you want to test it try installing the latest rc version of the runtime

**Comment by cjohn001** [comment]
@triniwiz: I just tried with v8.0.1-rc.0 and I can confirm that the bug is resolved. Thanks a lot! I hope I can now upgrade from NS 6 to 8 :) Is there already a release schedule available for the next official release of the runtime?

**Comment by rigor789** [comment]
@cjohn001 no schedule, but we can release that rc as a patch soon (though nothing wrong with using an rc version in the meantime).

**Comment by cjohn001** [comment]
@rigor789, thanks. I was only a little worrying to put a rc into a production release. However, as soon as I find time I will now try to upgrade my project from NS6 :)

**Comment by janoshrubos** [comment]
Closing this issue since the solution is merged to master.

If this error is still relevant, feel free to open a new issue!
