### ISSUE TITLE
Website Spelling error

### ISSUE THREAD

**Issue by francoiscx** [NativeScript/NativeScript#9433]
[https://docs.nativescript.org/plugins/email.html](https://docs.nativescript.org/plugins/email.html) has a spelling error in the heading.

#@nativescriot/email     ->       #@nativescript/email

**Comment by vallemar** [comment]
hi @francoiscx, now anyone can change the documents and do a PR!  the repo is [here](https://github.com/NativeScript/docs-new) .  Thanks!

**Comment by NathanWalker** [comment]
Thanks for heads up @francoiscx - let us know if you wanna try submitting a PR for it or we can handle here, either way 🤗

**Comment by francoiscx** [comment]
I'd love to submit a PR, try to get involved as I start learning Nativescipt. I'm just not sure how one goes about submitting the PR.
When pushing, I get an error, no permission to push, would I like to create a branch instead. - Please advise.

**Comment by vallemar** [comment]
Hi @NathanWalker, like @francoiscx  there will be many more people. The fork and PR process seems very simple but there are many people who have never done this and do not know how to approach it. A section in the readme of the documents would be good for this. I would dare to do it but it sure would be a disaster

**Comment by vallemar** [comment]
@francoiscx  This problem is already resulting, right?

**Comment by vallemar** [comment]
@francoiscx Can you close the issue? Thanksss
