### ISSUE TITLE
Error executing command 'javac'

### ISSUE THREAD

**Issue by Cluster2a** [NativeScript/NativeScript#9437]
My Environment
Ubuntu 21.04
NS: 8.0.2
Android Studio 4.2.1
Java:
openjdk 17-ea 2021-09-14
OpenJDK Runtime Environment (build 17-ea+19-Ubuntu-1ubuntu1)
OpenJDK 64-Bit Server VM (build 17-ea+19-Ubuntu-1ubuntu1, mixed mode, sharing)

Environment Paths:
```
export JAVA_HOME=/usr/bin/javac /usr/lib/jvm/java-17-openjdk-amd64
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$JAVA_HOME/bin
```
Javac is accessible via vhe variable:
![image](https://user-images.githubusercontent.com/84905165/121102928-0afef100-c7ff-11eb-8004-15b72475a9bb.png)

Everything seems to be set up correctly, but ns doctor keeps returning this error:
![image](https://user-images.githubusercontent.com/84905165/121103003-2d910a00-c7ff-11eb-92a1-124b681db668.png)

```Error executing command 'javac'. Make sure you have installed The Java Development Kit (JDK) and set JAVA_HOME environment variable.```

Is there any problem with java-17-openjdk?

Also tried the update-alternatives commands without any success.

Is there anything else I should check?

Thanks in advance - Alex

**Comment by Cluster2a** [comment]
The following steps resolved the problem:

- download JDK-16 `sudo apt-get install -y openjdk-16-jdk`
- set JAVA_HOME to JAVA_HOME=/usr/lib/jvm/java-16-openjdk-amd6

**Comment by reddigriz** [comment]
Tested on a debain 12 with openjdk-17-jdk and it works
