### ISSUE TITLE
nativescript-camera-plus 3.4.0 dont work in {N} 8.0

### ISSUE THREAD

**Issue by vicmasa** [NativeScript/NativeScript#9439]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.2
 - Cross-platform modules: 
 - Android Runtime: 8.0.0
 - iOS Runtime: 8.0.0
 - XCode Version: 12.4
 - Plugin(s): @nstudio/nativescript-camera-plus 3.4.0

**Describe the bug**

**Android:**
Error executing Static Binding Generator: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
File: .../myapp/platforms/android/app/src/main/java/com/tns/FragmentClass.java Class: com.tns.FragmentClass

**IOS:**
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'QBImagePickerController' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'QBImagePickerController-QBImagePicker' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'MDFInternationalization' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'SwiftyCam' from project 'Pods')
** BUILD FAILED **

Unable to apply changes on device: C23C67A6-028D-45C7-92D6-C24840D39E1B. Error is: Command xcodebuild failed with exit code 65.

**To Reproduce**
Add plugin @nstudio/nativescript-camera-plus 3.4.0
CLI: 8.0.2

**Comment by janoshrubos** [comment]
this is a different error message, but it looks like the plugin doesn't support {N} 7+ yet.  https://github.com/nstudio/nativescript-camera-plus/issues/164

**Comment by edusperoni** [comment]
It is updated here: https://github.com/nstudio/nativescript-plugins

I suggest opening an issue there
