### ISSUE TITLE
Error during creating nativescript project

### ISSUE THREAD

**Issue by harshal-khot08** [NativeScript/NativeScript#9448]
E:\Android_app>ns create

 Let’s create a NativeScript app!

Answer the following questions to help us build the right app for you. (Note: you
can skip this prompt next time using the --template option, or the --ng, --react, --vue, --svelte, --ts, or --js flags.)

√ First, what will be the name of your app? ... digital-card

√ Next, which style of NativeScript project would you like to use: » Angular

√ Finally, which template would you like to start from: » Hello World
Invalid URL: http:
![Capture](https://user-images.githubusercontent.com/73331799/122360891-62762d00-cf74-11eb-8dd7-6c864dc978bf.PNG)

**Comment by harshal-khot08** [comment]
[trace.txt](https://github.com/NativeScript/NativeScript/files/6669360/trace.txt)
Hi, Sorry for trouble
I am totally new to this. The CLI version is latest. I have attached trace. could you please tell where I am going wrong?

**Comment by rigor789** [comment]
@harshal-khot08 seems like you have an invalid npm config setting somewhere, from the log it says: 
```
npm WARN invalid config registry="http:"
```

You can try `npm config ls` to see all values you have set in your npm config, and then remove the invalid one with 
```bash
npm config rm <NAME OF THE INVALID SETTING HERE>
```

**Comment by harshal-khot08** [comment]
@rigor789  Thank You for your valuable time. It Worked!!
npm config rm proxy
npm config rm https-proxy
ran this two commands
