### ISSUE TITLE
Android Build fails com.android.builder.errors.EvalIssueException

### ISSUE THREAD

**Issue by mrwrighty** [NativeScript/NativeScript#9449]
NS 8
Android Studio 4.2.1

When building Android for release I get the following error:

Caused by: com.android.builder.errors.EvalIssueException: Failed to parse XML in /Users/nick/Documents/NativeScript/Projects/WFSL/platforms/android/app/src/main/AndroidManifest.xml
The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.

I have edited the AndroidManifest.xml file to remove the minSdk reference and put it in the build.gradle file as suggested on previous posts. But when I run the build again, the minSdk values re-appear in the AndroidManifest.xml file.

These are the lines I remove from AndroidManifest.xml: -

	<uses-sdk
		android:minSdkVersion="17"
		android:targetSdkVersion="__APILEVEL__"/>

My Build.gradle file has this

defaultConfig {
        def manifest = new XmlSlurper().parse(file(android.sourceSets.main.manifest.srcFile))
        def minSdkVer = manifest."uses-sdk"."@android:minSdkVersion".text() ?: 17
        minSdkVersion minSdkVer
        targetSdkVersion computeTargetSdkVersion()
        ndk {
            if (onlyX86) {
                abiFilters 'x86'
            } else {
                abiFilters 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'
            }
        }
        dexOptions {
            jumboMode = true
        }
    }

Which when I replace with this: -

compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.name.app"
        minSdkVersion 19    // This over here
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }

But as mentioned above the values re-appear in AndroidManifest.xml

**Comment by rigor789** [comment]
Make sure you edit the one inside App_Resources - the one inside platforms/android is wiped on every build.

**Comment by mrwrighty** [comment]
Thanks Igor, that fixed it.
