### ISSUE TITLE
Page content scrolls upwards when keyboard is opened

### ISSUE THREAD

**Issue by namikarif** [NativeScript/NativeScript#9457]
NS version **8.0.2**
Angular version **11.2.7**

**My question**
Why does the screen slide up when the keyboard is opened?
How do I solve this problem?

**Android Emulator SS**
![Ekran Resmi 2021-06-30 10 12 00](https://user-images.githubusercontent.com/45629136/123919042-2c31a800-d98d-11eb-8cc9-78e5125941d2.png)

**HTML Content**

`<ActionBar class="action-bar">
    <NavigationButton visibility="hidden"></NavigationButton>
    <GridLayout columns="50, *">
        <Label class="action-bar-title" text="Home" colSpan="2"></Label>
        <Label class="fas" text="&#xf0c9;" (tap)="onOpenDrawerTap()"></Label>
    </GridLayout>
</ActionBar>
<GridLayout rows="*, auto">
    <StackLayout>
        <TabView selectedIndex="0"
                 selectedTabTextColor="#5f6368"
                 tabBackgroundColor="#F0F0F0"
                 tabTextFontSize="12"
                 tabTextColor="#5f6368"
                 androidSelectedTabHighlightColor="green">
            <StackLayout *tabItem="{title: 'header_info' | translate, textColor: 'red'}">
                <ScrollView [height]="scrollViewHeight">
                    <GridLayout rows="auto, auto,auto,auto,auto,auto,auto, auto, auto">
                        <kl-floating-input [(ngModel)]="entity.document_num"
                                           [required]="true"
                                           (tapIcon)="generateNumber()"
                                           icon="&#xf084;"
                                           row="0"
                                           label="document_num"
                                           maxLength="20"
                                           name="document_num"
                                           id="document_num">
                        </kl-floating-input>
                        <GridLayout rows="50" columns="*, 140" row="1" style="margin: 0 15 0 5;">
                            <DatePickerField row="1"
                                             col="0"
                                             [(ngModel)]="document_date"
                                             name="document_date"
                                             [hint]="'document_date' | translate"
                                             locale="tr_TR" timeFormat="dd.mm.yyyy"
                                             style="padding-right: 0; margin-right: 0">
                            </DatePickerField>
                            <TimePickerField row="1"
                                             col="1"
                                             [(ngModel)]="document_time"
                                             name="document_time"
                                             [hint]="'document_time' | translate"
                                             locale="tr_TR"
                                             timeFormat="HH:MM:ss"
                                             style="padding-left: 5; margin-left: 5">
                            </TimePickerField>
                        </GridLayout>
                        <kl-floating-input [(ngModel)]="branchDescription"
                                           (tapInput)="branchPickerOpen()"
                                           (ngModelChange)="changeBranch(entity.branch)"
                                           [required]="true"
                                           row="2"
                                           icon="&#xf0dd;"
                                           editable="false"
                                           label="branches"
                                           name="branch"
                                           id="branch">
                        </kl-floating-input>
                        <kl-floating-input [(ngModel)]="warehouseDescription"
                                           (tapInput)="wareHousePickerOpen()"
                                           [required]="true"
                                           icon="&#xf0dd;"
                                           row="3"
                                           editable="false"
                                           label="warehouses"
                                           name="warehouse"
                                           id="warehouse">
                        </kl-floating-input>
                        <kl-floating-input [(ngModel)]="destBranchDescription"
                                           (tapInput)="destBranchPickerOpen()"
                                           (ngModelChange)="changeDestBranch(entity.dest_branch)"
                                           *ngIf="entity.document_type === DocumentTypesEnum.MATERIAL_WAREHOUSE_TRANSFER_RECEIPT"
                                           [required]="true"
                                           icon="&#xf0dd;"
                                           row="4"
                                           editable="false"
                                           label="dest_branch"
                                           name="dest_branch"
                                           id="dest_branch">
                        </kl-floating-input>
                        <kl-floating-input [(ngModel)]="destWarehouseDescription"
                                           (tapInput)="destWareHousePickerOpen()"
                                           *ngIf="entity.document_type === DocumentTypesEnum.MATERIAL_WAREHOUSE_TRANSFER_RECEIPT"
                                           [required]="true"
                                           icon="&#xf0dd;"
                                           row="5"
                                           editable="false"
                                           label="dest_warehouse"
                                           name="dest_warehouse"
                                           id="dest_warehouse">
                        </kl-floating-input>
                        <kl-floating-input [(ngModel)]="entity.external_document_num"
                                           label="external_document_num"
                                           maxLength="20"
                                           row="6"
                                           name="external_document_num"
                                           id="external_document_num">
                        </kl-floating-input>
                        <kl-floating-input [(ngModel)]="currencyCode"
                                           (tapInput)="currencyPickerOpen()"
                                           (ngModelChange)="changeCurrency(entity.currency)"
                                           [required]="true"
                                           icon="&#xf0dd;"
                                           row="7"
                                           editable="false"
                                           label="currency"
                                           name="currency"
                                           id="currency">
                        </kl-floating-input>
                        <kl-floating-input [(ngModel)]="entity.exchange_rate"
                                           [required]="true"
                                           row="8"
                                           keyboardType="number"
                                           label="exchange_rate"
                                           name="exchange_rate"
                                           id="exchange_rate">
                        </kl-floating-input>
                    </GridLayout>
                </ScrollView>
            </StackLayout>
            <StackLayout *tabItem="{title: 'product_line' | translate, iconSource: 'res://icon'}">
                <StackLayout>
                    <Label text="Second Tab" textWrap="true" class="m-15 h2 text-left" color="blue"></Label>
                </StackLayout>
            </StackLayout>
            <StackLayout *tabItem="{title: 'details' | translate, iconSource: 'res://icon'}">
                <StackLayout>
                    <Label text="Second Tab" textWrap="true" class="m-15 h2 text-left" color="blue"></Label>
                </StackLayout>
            </StackLayout>
        </TabView>
    </StackLayout>
    <AbsoluteLayout row="1" class="bottom-container">
        <GridLayout rows="*" columns="*" class="bottom-layout">
            <Button [text]="'save' | translate" class="fas save-button"></Button>
        </GridLayout>
    </AbsoluteLayout>
</GridLayout>
<kl-menu></kl-menu>
`

**Comment by namikarif** [comment]
?

**Comment by farfromrefug** [comment]
@namikarif this is a normal android behavior. See this https://developer.android.com/guide/topics/manifest/activity-element#wsoft. You can change the setting in your android manifest file.
