### ISSUE TITLE
Angular 12 code splitting don't work anymore

### ISSUE THREAD

**Issue by teha-at** [NativeScript/NativeScript#9458]
**Environment**
 - CLI: 8.0.2
 - Cross-platform modules: 8.0.8
 - Android Runtime: 8.0.0
 - iOS Runtime: 8.0.0
 - XCode Version: 12.5.1

**Describe the bug**
With Angular 12 the file based code splitting (xxx.component.ios.html / xxx.component.android.html) don't work anymore. Instead of using the platfrom specific file the app use the dummy `xxx.component.html` file or create an error if this dummy file don't exist.

**To Reproduce**
Create a new project with Angular 11
```bash
ns create hello-ng11 --template @nativescript/template-hello-world-ng@8.0.6
cd hello-ng11
# create iOS specific file
cat src/app/item/item-detail.component.html | sed -e 's/Details/iOS Details/g' > src/app/item/item-detail.component.ios.html
# create Android specific file
cat src/app/item/item-detail.component.html | sed -e 's/Details/Android Details/g' > src/app/item/item-detail.component.android.html
ns run android --emulator # or ios
```
In the app you can tap a list entry and the action bar will contain the platform "android" or "ios".

Create Angular 12 project which don't work
```bash
ns create hello-ng12 --template @nativescript/template-hello-world-ng@8.0.7
cd hello-ng12
# create iOS specific file
cat src/app/item/item-detail.component.html | sed -e 's/Details/iOS Details/g' > src/app/item/item-detail.component.ios.html
# create Android specific file
cat src/app/item/item-detail.component.html | sed -e 's/Details/Android Details/g' > src/app/item/item-detail.component.android.html
ns run android --emulator # or ios
```
In the app you can tap a list entry and the action bar will contain only "Details" from the `src/app/item/item-detail.component.html`file. The iOS or Android file will be ignored.

**Expected behavior**
As in Angular 11 the platform specific files should be used.

**Comment by rigor789** [comment]
Published `@nativescript/webpack@5.0.0-beta.15` with the merged fix, this should work as expected now.
