### ISSUE TITLE
Wrong Dialog colors on android in dark mode and no way to handle dark/light mode

### ISSUE THREAD

**Issue by wendt88** [NativeScript/NativeScript#9462]
**Environment**
 - nativescript: 8.0.2
 - @nativescript/core: 8.0.8
 - @nativescript/android: 8.0.0
 - @nativescript/ios: 8.0.0

**Describe the bug**
Could not set label and button colors for `Dialogs` via `css` (to handle dark mode colors)

**To Reproduce**
- run: `ns create ...`
- add somewhere a `Dialog.alert('Hi')`
- replace the scss as followed:
```scss
Page {
  Label,
  Button {
    color: gray;
  }

  &.ns-dark {
    Label,
    Button {
      color: white;
    }
  }
  &.ns-light {
    Label,
    Button {
      color: black;
    }
  }
}

Label,
Button {
  color: blue;

  &.ns-dark {
    color: yellow;
  }
  &.ns-light {
    color: green;
  }
}
```

***Result on Android***
![android](https://user-images.githubusercontent.com/13959976/124453432-a5fbd400-dd87-11eb-8d90-416b01b6742b.png)

***Result on iOS***
![ios](https://user-images.githubusercontent.com/13959976/124452458-b2cbf800-dd86-11eb-98a7-aed5b8b2b493.png)

**Expected behavior**
- in light mode, the `Dialogs` text and button colors should be `black` or `green` in light mode and `white` or `yellow` in dark mode
- without dark/light mode support they shloud be `gray` or `blue`;

**Sample project**
Playground is useless, because it it's last version runs on NS 6.5 (released a year ago).

**Additional context**
- the [`lbl`](https://github.com/NativeScript/NativeScript/blob/master/packages/core/ui/dialogs/dialogs-common.ts#L299) and [`btn`](https://github.com/NativeScript/NativeScript/blob/master/packages/core/ui/dialogs/dialogs-common.ts#L281) have no `page` or `parentNode`, so the css selectors `Page Label` and `Page Button` fail (described here: https://github.com/NativeScript/NativeScript/issues/3830#issuecomment-547349025)
- the [`lbl`](https://github.com/NativeScript/NativeScript/blob/master/packages/core/ui/dialogs/dialogs-common.ts#L299) and [`btn`](https://github.com/NativeScript/NativeScript/blob/master/packages/core/ui/dialogs/dialogs-common.ts#L281) have no `ns-light` or `ns-dark` css-class, so there is no possibility to set different colors via css.
- on android and ios the color property of [`lbl`](https://github.com/NativeScript/NativeScript/blob/master/packages/core/ui/dialogs/dialogs-common.ts#L299) and [`btn`](https://github.com/NativeScript/NativeScript/blob/master/packages/core/ui/dialogs/dialogs-common.ts#L281) is:
```js
color: {
  _argb: 4278190335
  _name: "blue"
  a: 255
  android: -16776961
  argb: 4278190335
  b: 255
  g: 0
  hex: "#0000FF"
  ios: undefined
  name: "blue"
  r: 0
}
```
there are a some existing issues about this problem, wich are opend over moths, like:
https://github.com/NativeScript/NativeScript/issues/8484
https://github.com/NativeScript/theme/issues/184

**Summarized:**
- no chance to apply custom colors for dark mode on both platforms (this is realy bad -> dialogs are not usable in dark mode)
- on android in dark mode gets generated "magically" a custom color (but at least is a bit lighter and could be used in dark mode)
- If I'm not wrong, this issue could not be solved, by css (and `@nativescript/theme`)

**Comment by michael-dots** [comment]
Having the same problem with action type dialog with options. Also can't find any way to solve by css, even using .ns-dark styles . Not even sure the options in action mode are buttons, or how to style them?

**Comment by micahlt** [comment]
Same issue here!
