### ISSUE TITLE
WebView local html file wont load

### ISSUE THREAD

**Issue by philipgyllhamn** [NativeScript/NativeScript#9463]
✔ Component nativescript has 8.0.2 version and is up to date.
✔ Component @nativescript/core has 8.0.8 version and is up to date.
✔ Component tns-ios has 6.5.4 version and is up to date.
✖ Component @nativescript/android is not installed.

this app is also being tested and run on an IOS device with 'ns debug ios --chrome'

So im trying to display a local html file in a WebView. But it only displays white and does not display the html file.
Ive read this issue https://github.com/NativeScript/NativeScript/issues/8568 and clicked every link on google regarding this issue. And from my understanding it should work the way i have done it.

In **webpack.config.js**
`new CopyWebpackPlugin([...copyTargets, { from: { glob: '**/*.jpg', dot: false } },{ from: { glob: "swedbank-pay-view/assets/*.html"} } ,{ from: { glob: '**/*.png', dot: false } }], copyIgnore),
			new nsWebpack.GenerateNativeScriptEntryPointsPlugin('bundle')`

**File structure where the html file is**
- App
- - Swedbank-pay-view
- - - assets
- - - - swedbank.html

**in the component typescript file**
`  public webViewSrc: string = encodeURI(`${fs.knownFolders.currentApp().path}/swedbank-pay-view/assets/swedbank.html`);
`

**In the component html file**
`<webview row="2" col="1"  (loadFinished)="onLoadFinished($event)" (loadStarted)="onLoadStarted($event)" [src]="webViewSrc"></webview>`

So what may be the problem?

**Comment by triniwiz** [comment]
To verify your config works you can check `platforms/ios/app_name/app/`

**Comment by cjohn001** [comment]
Hello together, I am also seeing the issue. It is important to note, that it seems to appear with API Level 30. For older Android versions the WebView did work. I am also unable to load local files anymore. I get a net::ERR_ACCESS_DENIED
And on console
chromium: [ERROR:filesystem_posix.cc(62)] mkdir /data/user/0/org.nativescript.nativescriptsdkexamplesng/cache/WebView/Crashpad: No such file or directory (2)

**Comment by cjohn001** [comment]
It looks like the issue is related to loading of the local html file. If I read the html file into a local buffer and bind it to the WebView, it works. Might be related to scoped storage which seems to be enforced now with API Level 30

```
const file: File = File.fromPath(filePath);
file.readText()
			.then(result => {
				this._htmlContent = result;
			})
			.catch(err => {
				console.log(err.stack);
			});
```
