### ISSUE TITLE
[NS8] view files with certain names not working correctly

### ISSUE THREAD

**Issue by gecklund** [NativeScript/NativeScript#9471]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.2
 - iOS Runtime: 14.5
 - XCode Version: 12.5.1

**Describe the bug**
Files with "password" in the file name are displaying but won't function properly. (loaded, navigatedTo events aren't fired). I also noticed that it doesn't happen if using @nativescript/webpack 5.0.0-beta.3 or below. This happens in both android and iOS.

**To Reproduce**
Run the hello world typescript template and change the name of main-view.xml to password.xml as well as the corresponding .ts file and notice the usual hello world behavior doesn't work.

I've renamed the file in my project to work around it but it took me longer than I'd like to admit to track down.

**Comment by gecklund** [comment]
Ran into this again with some views I had named "dashboard.xml" and renaming them fixed them. Tried the file name in a fresh hello world app and got the same issue.

**Comment by rigor789** [comment]
I believe it should be fixed in the next patch with this change: https://github.com/NativeScript/NativeScript/commit/0fd53e3abbbb035dd11914663c0f92de97717c95

**Comment by gecklund** [comment]
Ah, thanks! A regex issue makes sense here.
