### ISSUE TITLE
fetch doesn't work

### ISSUE THREAD

**Issue by ReazerDev** [NativeScript/NativeScript#9475]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.2
 - Cross-platform modules:
 - Android Runtime: 8.0.0
 - iOS Runtime:
 - XCode Version:
 - Plugin(s):

**Describe the bug**
Using fetch in nativescript throws an error.
![image](https://user-images.githubusercontent.com/36013882/126051229-e4df26bc-d01b-4429-882d-89c486670961.png)

**To Reproduce**
`fetch("https://mirror.reazer.net/api/corona").then(res => res.text()).then(res => {
      console.log(res);
    });`

**Expected behavior**
It successfully completes the http request.

**Sample project**
https://github.com/ReazerDev/nativescript-fetch-bug
(Click on the TV Button and to execute the fetch, click on TV again)

**Additional context**
I'm using @nativescript/angular@12.0.5. (I'm not sure if this is supposed to be in Cross-platform modules, or not). It does work in another project using @nativescript/angular@11.8.1.

**Comment by ReazerDev** [comment]
It seems to be an issue with the angular zone stuff.
This works:
`reader.__zone_symbol__originalInstance.readAsText();`

**Comment by ReazerDev** [comment]
So in fetch's index.js file changing the readBlobAsText function to this:
`var reader = new FileReader().__zone_symbol__originalInstance;
        var promise = fileReaderReady(reader);
        reader.readAsText(blob);
        return promise;`

(I know this isn't a possible solution, I'm just trying to give information^^)

**Comment by edusperoni** [comment]
Hey! There's an issue for this and a workaround on the angular repo. https://github.com/NativeScript/angular/issues/14

Closing as we should keep the discussion there.
