### ISSUE TITLE
Can't open local HTML file in Android

### ISSUE THREAD

**Issue by OriIdan** [NativeScript/NativeScript#9479]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.1.2

We are loading a local HTML file using:
this.webViewInterface = new WebViewInterface(this.epubWebView, htmlUrl);

This works in iOS and Android with chrome versions below 91.
In devices with Chrome 92 and above it stopped working.
htmlUrl is a local HTML file is the Documents folder.

**To Reproduce**
Open a webview and load a local HTML file using: WebViewInterface(this.epubWebView, htmlUrl)

**Expected behavior**
It used to work and for some reason stopped working when chrome (or Android webview) where updated.

**Comment by OriIdan** [comment]
It seems to be a bug in Android WebView we are monitoring it now.

**Comment by OriIdan** [comment]
We are now sure it was a bug in Chrome.
New version of chrome solved it.

**Comment by jessorlisa** [comment]
@OriIdan We are experiencing similiar issues and identified it being an issue with the "Android System WebView" app (not necessarily Chrome).

According to our research issues only occur with the dev/beta version:

Current: 91.0.4472.164 -> no issues
Beta: 92.0.4515.105 -> issues
Dev: 93.0.4577.8 -> issues
Canary: 94.0.4585.0 -> no issues

Can you confirm this?

**Comment by OriIdan** [comment]
I can confirm the problem exists with 92.0.4515.105
I don't have access to Dev or Canary.
I hope that google will not release to customer version 93 as you say it
has the same issue.

**Comment by cjohn001** [comment]
@OriIdan : May I ask how you have worked around the issue? I see the issue on Android API Level 30 when I try to load a local file into a webview. I thought it might be related to my app configuration, wrong permissions in Manifest, searching for a solution since hours already but all permission related workarounds I could find with google did not point me to a valid solution

**Comment by OriIdan** [comment]
Hi cjohn001,
I did not work around it, it seems to fixed by google, this is a bug in few
webview versions.
Version 93 and above, solve it. It took about 3 days and google updated
webview in all our users devices and the problem disappeared.

**Comment by cjohn001** [comment]
@Orildan, thanks for the info. I am seeing it with the current nativescript WebView version as well on my Samsung phone, so this means I have to wait till Samsung decides to do provide an Android update. Bad situation.

**Comment by OriIdan** [comment]
@cjohn001 Try to update chrome or WebView.
This is strange as many of our users have Samsung phones. Webview is
updated regularly not related to Android releases.
