### ISSUE TITLE
Error reading or writing files in Download folder in Android 11

### ISSUE THREAD

**Issue by kandangit** [NativeScript/NativeScript#9480]
**Environment**
NativeScript version: 8.0.2
Android version 11
(Not tested in iOS)

**Describe the bug**

The app cannot read/write file from the Download folder in Android 11
The same code works fine in Android 8/9 (have not tested 10) but fails in Android 11

When reading a file: 
- If the file does NOT exist, getFile returns the following error "Failed to create new Java File for path /storage/emulated/0/Download/accounts.json"
- If the file exist, call to readTextSync returns "undefined"

When writing to a file 
- If the file does NOT exist, getFile returns the following error "Failed to create new Java File for path /storage/emulated/0/Download/accounts.json"
- If the file exist, call to writeTextSync wil write nothing

**IMPORTANT**

1) The app requests permissions before: READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE
2) AndroidManifest.xml has the following flag:
`android:requestLegacyExternalStorage="true"`
3) AndroidManifest.xml requires targetSdkVersion 29 although it also fails without it
`<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="29" />`

Why is this happening? I am testing in Xiaomi with Android 11 and Android 9 worked fine. In the emulator works in Android 11 fine but i have not touched any settings on the device.

**To Reproduce**

**Sample Code with function to read file from Downloads folder**
```
declare var android: any;
export const downloadsPath: string = android.os.Environment.getExternalStoragePublicDirectory(
    android.os.Environment.DIRECTORY_DOWNLOADS
).toString();
const downloadsFolder: Folder = fileSystem.Folder.fromPath(downloadsPath);
const documentsFolder: Folder = fileSystem.knownFolders.documents();

export function getDownloadsFile(name: string) {
    return downloadsFolder.getFile(name);
}
```

**Sample Code with function to read file from Downloads folder**

```
let accountsFile = getDownloadsFile("accounts.json"); // Here call to getFile errors if the file does NOT exist 
let contentFileAccounts = accountsFile.readTextSync(); // If the files exists it returns undefined instead of the content
```

**package.json**
```
{
  "name": "@nativescript/template-blank-ng",
  "main": "src/main.ts",
  "displayName": "Blank",
  "templateType": "App template",
  "version": "8.0.6",
  "description": "NativeScript Application",
  "author": "NativeScript Team <oss@nativescript.org>",
  "license": "SEE LICENSE IN <your-license-filename>",
  "publishConfig": {
    "access": "public"
  },
  "files": [
    "App_Resources",
    "hooks",
    "src",
    "tools",
    "!tools/assets",
    ".editorconfig",
    "references.d.ts",
    "tsconfig.json"
  ],
  "keywords": [
    "nstudio",
    "nativescript",
    "mobile",
    "angular",
    "{N}",
    "tns",
    "template",
    "category-general"
  ],
  "repository": "<fill-your-repository-here>",
  "homepage": "https://github.com/NativeScript/nativescript-app-templates",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "dependencies": {
    "@angular/animations": "~12.0.0",
    "@angular/common": "~12.0.0",
    "@angular/compiler": "~12.0.0",
    "@angular/core": "~12.0.0",
    "@angular/forms": "~12.0.0",
    "@angular/platform-browser": "~12.0.0",
    "@angular/platform-browser-dynamic": "~12.0.0",
    "@angular/router": "~12.0.0",
    "@nativescript/angular": "~12.0.0",
    "@nativescript/core": "~8.0.0",
    "@nativescript/email": "^2.0.5",
    "@nativescript/theme": "~3.0.1",
    "@nstudio/nativescript-checkbox": "^2.0.4",
    "moment": "^2.29.1",
    "nativescript-modal-datetimepicker": "^2.1.5",
    "nativescript-permissions": "^1.3.11",
    "nativescript-ui-autocomplete": "^7.0.2",
    "nativescript-ui-dataform": "^7.0.6",
    "rxjs": "^6.6.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~12.0.0",
    "@nativescript/android": "8.0.0",
    "@nativescript/types": "~8.0.0",
    "@nativescript/webpack": "beta",
    "@ngtools/webpack": "~12.0.0",
    "typescript": "~4.2.0"
  },
  "private": "true",
  "readme": "NativeScript Application"
}
```

**Comment by kandangit** [comment]
Is this same issue as https://github.com/NativeScript/NativeScript/issues/7866 ?

Though that issue is quite old and for Android 10

**Comment by ray007** [comment]
I have the same problem with a json file with custom extension.
Anybody else also having troubles with accessing files in the Downloads dir?
