### ISSUE TITLE
Is there a showcases?

### ISSUE THREAD

**Issue by biapar** [NativeScript/NativeScript#9482]
Is there a showcases?

**Comment by farfromrefug** [comment]
@biapar not really, not a website. Though people started to share their apps on discord inside the `#showcase` channel. 
Also a few of us shared their apps [here](https://github.com/NativeScript/NativeScript/discussions/9473)

**Comment by pekevski** [comment]
As og today they have brought them back and you can see them here: [https://nativescript.org/showcase/](https://nativescript.org/showcase/)
