### ISSUE TITLE
nativescript.org homepage links

### ISSUE THREAD

**Issue by jbeckton** [NativeScript/NativeScript#9491]
The links on your homepage https://nativescript.org do not work. How can I access the Angular docs?

On your homepage under the "Choose the flavor you love" the only links that work are the two capacitor options.

**Comment by janoshrubos** [comment]
Thank you for your issue!

The flavor icons will link to flavor specific pages, which are currently in progress.

You can access to the Angular related docs by choosing the Angular in the tabs above codes.
(e.g. https://docs.nativescript.org/ui-and-styling.html#actionbar)
