### ISSUE TITLE
Error: Cannot find module 'webpack/lib/rules/DescriptionDataMatcherRulePlugin'

### ISSUE THREAD

**Issue by rajdeodas89** [NativeScript/NativeScript#9493]
I started getting this error after `ns clean` and then `ns run ios`

Copying template files...
Platform ios successfully added. v8.0.0
Preparing project...
Error: Cannot find module 'webpack/lib/rules/DescriptionDataMatcherRulePlugin'
Require stack:
- /Users/rajdeo/Work/IPT/Mobile-App/limelight360-mobile/node_modules/vue-loader/lib/plugin-webpack5.js
- /Users/rajdeo/Work/IPT/Mobile-App/limelight360-mobile/node_modules/vue-loader/lib/plugin.js
- /Users/rajdeo/Work/IPT/Mobile-App/limelight360-mobile/node_modules/vue-loader/lib/index.js
- /Users/rajdeo/Work/IPT/Mobile-App/limelight360-mobile/node_modules/@nativescript/webpack/dist/configuration/vue.js
- /Users/rajdeo/Work/IPT/Mobile-App/limelight360-mobile/node_modules/@nativescript/webpack/dist/configuration/index.js
- /Users/rajdeo/Work/IPT/Mobile-App/limelight360-mobile/node_modules/@nativescript/webpack/dist/index.js
- /Users/rajdeo/Work/IPT/Mobile-App/limelight360-mobile/webpack.config.js
- /Users/rajdeo/Work/IPT/Mobile-App/limelight360-mobile/node_modules/@nativescript/webpack/dist/bin/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/rajdeo/Work/IPT/Mobile-App/limelight360-mobile/node_modules/vue-loader/lib/plugin-webpack5.js:6:42)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/rajdeo/Work/IPT/Mobile-App/limelight360-mobile/node_modules/vue-loader/lib/plugin-webpack5.js',
    '/Users/rajdeo/Work/IPT/Mobile-App/limelight360-mobile/node_modules/vue-loader/lib/plugin.js',
    '/Users/rajdeo/Work/IPT/Mobile-App/limelight360-mobile/node_modules/vue-loader/lib/index.js',
    '/Users/rajdeo/Work/IPT/Mobile-App/limelight360-mobile/node_modules/@nativescript/webpack/dist/configuration/vue.js',
    '/Users/rajdeo/Work/IPT/Mobile-App/limelight360-mobile/node_modules/@nativescript/webpack/dist/configuration/index.js',
    '/Users/rajdeo/Work/IPT/Mobile-App/limelight360-mobile/node_modules/@nativescript/webpack/dist/index.js',
    '/Users/rajdeo/Work/IPT/Mobile-App/limelight360-mobile/webpack.config.js',
    '/Users/rajdeo/Work/IPT/Mobile-App/limelight360-mobile/node_modules/@nativescript/webpack/dist/bin/index.js'
  ]
}
No configuration!
Executing webpack failed with exit code 0.

_____________________________________________________

{
  "name": "@nativescript/template-drawer-navigation-ng",
  "main": "src/main.ts",
  "displayName": "Navigation Drawer",
  "templateType": "App template",
  "version": "8.0.4",
  "description": "NativeScript Application",
  "author": "NativeScript Team <oss@nativescript.org>",
  "license": "SEE LICENSE IN <your-license-filename>",
  "publishConfig": {
    "access": "public"
  },
  "files": [
    "App_Resources",
    "hooks",
    "src",
    "tools",
    "!tools/assets",
    ".editorconfig",
    "references.d.ts",
    "tsconfig.json"
  ],
  "keywords": [
    "nstudio",
    "nativescript",
    "mobile",
    "angular",
    "{N}",
    "tns",
    "template",
    "drawer",
    "navigation",
    "category-general"
  ],
  "repository": "<fill-your-repository-here>",
  "homepage": "https://github.com/NativeScript/nativescript-app-templates",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "dependencies": {
    "@angular/animations": "~11.2.7",
    "@angular/common": "~11.2.7",
    "@angular/compiler": "~11.2.7",
    "@angular/core": "~11.2.7",
    "@angular/forms": "~11.2.7",
    "@angular/platform-browser": "~11.2.7",
    "@angular/platform-browser-dynamic": "~11.2.7",
    "@angular/router": "~11.2.7",
    "@nativescript-community/ui-canvas": "^4.0.49",
    "@nativescript-community/ui-material-bottom-navigation": "^5.2.30",
    "@nativescript-community/ui-material-tabs": "^5.2.30",
    "@nativescript-community/universal-links": "^2.0.3",
    "@nativescript/angular": "~11.8.0",
    "@nativescript/appversion": "^2.0.0",
    "@nativescript/background-http": "^5.0.2",
    "@nativescript/core": "~8.0.0",
    "@nativescript/datetimepicker": "^2.1.3",
    "@nativescript/fingerprint-auth": "^7.0.0",
    "@nativescript/firebase": "^11.1.3",
    "@nativescript/imagepicker": "^1.0.3",
    "@nativescript/iqkeyboardmanager": "^2.0.0",
    "@nativescript/secure-storage": "^3.0.0",
    "@nativescript/theme": "~3.0.1",
    "@nota/nativescript-webview-ext": "^8.0.0",
    "@nstudio/nativescript-checkbox": "^2.0.4",
    "@nstudio/nativescript-floatingactionbutton": "^3.0.4",
    "@nstudio/nativescript-pulltorefresh": "^3.0.1",
    "@triniwiz/nativescript-toasty": "^4.1.3",
    "iso8601-duration": "^1.3.0",
    "nativescript-advanced-webview": "^6.1.1",
    "nativescript-carousel": "^7.0.1",
    "nativescript-feedback": "^2.0.0",
    "nativescript-http-formdata": "^2.1.0",
    "nativescript-mediafilepicker": "^4.0.2",
    "nativescript-ui-calendar": "^7.0.2",
    "nativescript-ui-listview": "^9.1.0",
    "nativescript-ui-sidedrawer": "~9.0.3",
    "nativescript-windowed-modal": "7.0.0",
    "reflect-metadata": "~0.1.13",
    "rxjs": "~6.6.7",
    "rxjs-compat": "^6.6.7",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~11.2.7",
    "@nativescript/android": "8.0.0",
    "@nativescript/ios": "8.0.0",
    "@nativescript/types": "~8.0.0",
    "@nativescript/webpack": "beta",
    "@ngtools/webpack": "~11.2.6",
    "typescript": "~4.0.0"
  },
  "private": "true",
  "readme": "NativeScript Application"
}

**Comment by pjmagtubo** [comment]
Hi @rigor789 

I encountered the same issue, 

I have a working solution that does not have an error when executing "npm run dev". You may use the zip file attached and copy the file DescriptionDataMatcherRulePlugin.js to "<Your Laravel Project>\node_modules\webpack\lib\rules\".

[DescriptionDataMatcherRulePlugin.zip](https://github.com/NativeScript/NativeScript/files/6939226/DescriptionDataMatcherRulePlugin.zip)

**Comment by farfromrefug** [comment]
@pjmagtubo i had this this morning. Upgrading `vue-loader` fixed it

**Comment by naufalakhyar46** [comment]
@farfromrefug worked. thank you

> @pjmagtubo i had this this morning. Upgrading `vue-loader` fixed it

**Comment by 4samitim** [comment]
> webpack

thxxxxxxx

**Comment by MrBhola** [comment]
Thanks a lot @pjmagtubo

**Comment by tejasambalia** [comment]
> @farfromrefug worked. thank you
> 
> > @pjmagtubo i had this this morning. Upgrading `vue-loader` fixed it

It worked for me @pjmagtubo thanks

**Comment by farfromrefug** [comment]
@rajdeodas89 can you confirm it works for you so we can close this issue?

**Comment by Rajdeo-Das** [comment]
> @rajdeodas89 can you confirm it works for you so we can close this issue?

Yes, It got resolved, and it's working.
Thanks, Cheers.

**Comment by ismailcaakir** [comment]
> @pjmagtubo i had this this morning. Upgrading `vue-loader` fixed it

thank you 🙏

**Comment by shoutershub** [comment]
Thanks running  `npm i vue-loader` solved my problem

**Comment by ThecodingOG** [comment]
@shoutershub Thanks so much. It worked

**Comment by GhostMech** [comment]
> @pjmagtubo i had this this morning. Upgrading `vue-loader` fixed it

Also solved MY problem with Laravel Mix!!

**Comment by pvanhooren** [comment]
@farfromrefug upgrading vue-loader worked for me multiple times over the last week, but it doesn't work anymore today. Upgrading vue-loader leads to another error:

>Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'webpackbar'.

**Comment by farfromrefug** [comment]
@pvanhooren that is something else. Do you have a special webpack config? Search for `webpackbar` in your project folder.

**Comment by pvanhooren** [comment]
> @pvanhooren that is something else. Do you have a special webpack config? Search for `webpackbar` in your project folder.

I do have a webpackbar folder and a webpackbar files, yes. What should I do with it?

**Comment by farfromrefug** [comment]
@pvanhooren for some reason that folder name seems to be "passed" as argument of the webpack config. Cant help much more without seeing your project

**Comment by pvanhooren** [comment]
> @pvanhooren for some reason that folder name seems to be "passed" as argument of the webpack config. Cant help much more without seeing your project

Which files do you need to see? I can post them

**Comment by farfromrefug** [comment]
@pvanhooren well all your project config files, including webpack.config.js

**Comment by pvanhooren** [comment]
> @pvanhooren well all your project config files, including webpack.config.js
I am new to the framework, Where can I find these files?

**Comment by farfromrefug** [comment]
@pvanhooren can you share the whole project? that would be faster. You can find me on discord if you want to share privately

**Comment by pvanhooren** [comment]
> @pvanhooren can you share the whole project? that would be faster. You can find me on discord if you want to share privately

Where can I find your Discord? I don't see it on your profile

**Comment by farfromrefug** [comment]
@pvanhooren not on my computer right now but you should maybe see me on the N server under "farfromrefug"?

**Comment by pvanhooren** [comment]
> @pvanhooren not on my computer right now but you should maybe see me on the N server under "farfromrefug"?

Sorry if this sounds dumb but what is the N server :joy:

**Comment by farfromrefug** [comment]
@pvanhooren https://blog.nativescript.org/nativescript-8-announcement/#join-our-discord-community ;)

**Comment by talharain707** [comment]
zindabaaad
npm i vue-loader

**Comment by shhtaheri** [comment]
npm i vue-loader@latest

**Comment by darkyelox** [comment]
I'm in a NativeScript 8.1 migrated project using Angular and I have this error with vue-loader

**Comment by SahanRashmika97** [comment]
@pjmagtubo Thank you so much.

**Comment by sksmsWKd** [comment]
thank you

**Comment by deulizealand** [comment]
> @pjmagtubo i had this this morning. Upgrading `vue-loader` fixed it

can you tell me 'vue-loader' version ? i got same issues

**Comment by Zach-Mose** [comment]
Thanks, @shoutershub was the end of all my problems

**Comment by DanendraWM** [comment]
it works thanks bro

**Comment by Oladayo-Ahmod** [comment]
This solves my problem with laravel mix as well

**Comment by RenaudKieffer** [comment]
THX !! But 1 year without fix ?? why ?
