### ISSUE TITLE
Support dynamically generated XML

### ISSUE THREAD

**Issue by RangerMauve** [NativeScript/NativeScript#95]
It'd be nice if there was a way to just dynamically generate XML and have that used to update the view. Something a la React virtual dom patching.

Are there facilities for this already?

Are there maybe docs on how the XML is being parsed and turned into the UI itself that hint as to how this can be made more dynamic?

**Comment by enchev** [comment]
You can create and parse XML dynamically even now using our [ui/builder](https://github.com/NativeScript/NativeScript/blob/master/ui/builder/builder.d.ts#L6)

**Comment by RangerMauve** [comment]
Oh, that's perfect. There wouldn't happen to be an example of how to set the current view from that, would there?

**Comment by enchev** [comment]
You can add the view to desired [Layout](http://docs.nativescript.org/layouts) using [addChild() method](http://docs.nativescript.org/ApiReference/ui/layouts/layout/Layout.html) or [assign some Page content](http://docs.nativescript.org/ApiReference/ui/page/HOW-TO.html).

**Comment by RangerMauve** [comment]
Perfect. Thank you!
