### ISSUE TITLE
Playground (preview) Error

### ISSUE THREAD

**Issue by futuremaster777** [NativeScript/NativeScript#9512]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.2
 - Cross-platform modules:
 - Android Runtime: 8.0.0
 - iOS Runtime:
 - XCode Version:
 - Plugin(s):

**Describe the bug**
 ns doctor android
✔ Getting environment information

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.0.2 version and is up to date.
✔ Component @nativescript/core has 8.0.8 version and is up to date.
✔ Component @nativescript/android has 8.0.0 version and is up to date.

ns create HelloWorld --template @nativescript/template-hello-world-ts

When I try to preview using the Playground app, the following error occurs. ( See the below log )
How to fix it?
Thanks.

**Error: Failed to load component from module: app-root**

---------------------------------------------------------------------------------------------------------------------------------------------
Local plugin @nativescript/core differs in major version from plugin in preview app. The local plugin has version ~8.0.0 and the plugin in preview app has version 6.5.0. Some features might not work as expected.

-  In the app are used one or more NativeScript plugins with native dependencies.                                                   *
-  Those plugins will not work while building the project via `$ tns preview`. Please, use `$ tns run <platform>` command instead.  

Copying template files...
Platform android successfully added. v8.0.0
Preparing project...
webpack is watching the files...
asset vendor.js 5.66 MiB [emitted] (name: vendor) (id hint: defaultVendor)
asset bundle.js 347 KiB [emitted] (name: bundle)
asset runtime.js 86.8 KiB [emitted] (name: runtime)
Entrypoint bundle 6.08 MiB = runtime.js 86.8 KiB vendor.js 5.66 MiB bundle.js 347 KiB
runtime modules 24.8 KiB 12 modules
orphan modules 356 bytes [orphan] 6 modules
modules by path ./node_modules/@nativescript/core/ 1.41 MiB 164 modules
modules by path ./node_modules/css-tree/ 317 KiB 113 modules
modules by path ./app/ 126 KiB 8 modules
modules by path ./node_modules/source-map/lib/*.js 36.3 KiB 6 modules
modules by path ./node_modules/reduce-css-calc/dist/ 131 KiB
  modules by path ./node_modules/reduce-css-calc/dist/lib/*.js 11.1 KiB 3 modules
  modules by path ./node_modules/reduce-css-calc/dist/*.js 120 KiB 2 modules
modules by path ./node_modules/postcss-value-parser/lib/*.js 11.8 KiB 5 modules
modules by path ./node_modules/mdn-data/css/*.json 242 KiB 3 modules
./node_modules/tslib/tslib.es6.js 10.5 KiB [built] [code generated]
external "~/package.json" 42 bytes [optional] [built] [code generated]
./node_modules/css-unit-converter/index.js 2.57 KiB [built] [code generated]
webpack 5.50.0 compiled successfully in 4036 ms
Webpack compilation complete. Watching for file changes.
Updating runtime package.json with configuration values...
Project successfully prepared (android)
Start sending initial files for device Galaxy A70 (9f0d4295-7be2-4533-a73c-d761dd43cf4b).
Successfully sent initial files for device Galaxy A70 (9f0d4295-7be2-4533-a73c-d761dd43cf4b).
Issues checking in progress...
File change detected. Starting incremental webpack compilation...
assets by status 6.08 MiB [cached] 3 assets
Entrypoint bundle 6.08 MiB = runtime.js 86.8 KiB vendor.js 5.66 MiB bundle.js 347 KiB
cached modules 2.26 MiB (javascript) 24.8 KiB (runtime) [cached] 346 modules
javascript modules 506 bytes
  ./app/__@nativescript_webpack_virtual_entry_typescript__ 236 bytes [built]
  ./app/ sync \.(xml|js|(?<%21d\.)ts|s?css)$ 270 bytes [built]
webpack 5.50.0 compiled successfully in 194 ms
Webpack compilation complete. Watching for file changes.
Issues checking in progress...
No issues found.
LOG from device Galaxy A70: An uncaught Exception occurred on "main" thread.
Unable to start activity ComponentInfo{org.nativescript.preview/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
Error: Failed to load component from module: app-root

StackTrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.preview/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
Error: Failed to load component from module: app-root
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
Error: Failed to load component from module: app-root
        at com.tns.Runtime.callJSMethodNative(Native Method)
        at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
        at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
        at com.tns.Runtime.callJSMethod(Runtime.java:1160)
        at com.tns.Runtime.callJSMethod(Runtime.java:1138)
        at com.tns.Runtime.callJSMethod(Runtime.java:1134)
        at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:20)
        at android.app.Activity.performCreate(Activity.java:8198)
        at android.app.Activity.performCreate(Activity.java:8182)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
        ... 11 more

**Comment by janoshrubos** [comment]
Thank you for your issue!

  The Playground and the Preview app don’t support NativeScript 8 yet, the implementation is in progress.

**Comment by BunnyTheLifeguard** [comment]
> Thank you for your issue!
> 
>   The Playground and the Preview app don’t support NativeScript 8 yet, the implementation is in progress.

Where can we expect to get the info when it is ready?

**Comment by rigor789** [comment]
@BunnyTheLifeguard we'll announce anything as usual on Twitter & a blog post, as well as post about it on Discord/Slack.
