### ISSUE TITLE
Doesn't ApplicationSettings will be deleted even when the app is updated?

### ISSUE THREAD

**Issue by HeyKJ** [NativeScript/NativeScript#9521]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime: 8.0.0
 - iOS Runtime:
 - XCode Version:
 - Plugin(s):

**Describe the bug**

When I tested using FakeAppUpdateManager, the data was not erased.
Can I expect the same result as the actual app update?

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by edusperoni** [comment]
Application settings doesn't get deleted on app update
