### ISSUE TITLE
pod install fails M1 Macbook

### ISSUE THREAD

**Issue by angryloner** [NativeScript/NativeScript#9535]
I can't seem to get ios to run, natively or using rosetta

When I run with ns prepare ios --log trace I see it failing here:

`Installing pods...
Running on arm64 - running pod through rosetta2.
spawn: arch "-x86_64" "pod" "install"
arch: posix_spawnp: pod: Bad CPU type in executable
Result when throw error is false:
{ stdout: '', stderr: '', exitCode: 1 }
'arch install' command failed.

Error: 'arch install' command failed.

    at Errors.failWithOptions (/Users/alas/.nvm/versions/node/v15.14.0/lib/node_modules/nativescript/lib/common/errors.js:157:27)
    at Errors.fail (/Users/alas/.nvm/versions/node/v15.14.0/lib/node_modules/nativescript/lib/common/errors.js:130:21)
    at CocoaPodsService.<anonymous> (/Users/alas/.nvm/versions/node/v15.14.0/lib/node_modules/nativescript/lib/services/cocoapods-service.js:55:30)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/alas/.nvm/versions/node/v15.14.0/lib/node_modules/nativescript/lib/services/cocoapods-service.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)`

Config:
`Exec system_profiler SPSoftwareDataType -detailLevel mini
 stdout: Software:

    System Software Overview:

      System Version: macOS 11.5.2 (20G95)
      Kernel Version: Darwin 20.6.0
      Time since boot: 22:58

 stderr:
macOS version based on system_profiler is 11.5.
Looking for project in '/Users/alas/Apps/mycoolapp'
Project directory is '/Users/alas/Apps/mycoolapp'.
Initializing project identifiers. Config:  {
  id: 'org.nativescript.mycoolapp',
  appPath: 'src',
  appResourcesPath: 'App_Resources',
  android: { v8Flags: '--expose_gc', markingMode: 'none' }
}
Loading extensions.
Collecting system information...
System information:
{
  "platform": "darwin",
  "shell": "/bin/zsh",
  "os": "Darwin Alass-MBP.lan 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64\n",
  "procArch": "arm64",
  "nodeVer": "15.14.0",
  "npmVer": "7.7.6",
  "nodeGypVer": null,
  "nativeScriptCliVersion": "8.0.2",
  "gitVer": "2.30.1 (Apple Git-130)",
  "dotNetVer": null,
  "javacVersion": "15.0.2",
  "javaVersion": "15.0.2",
  "javaPath": "java",
  "adbVer": "1.0.41",
  "androidInstalled": true,
  "monoVer": null,
  "gradleVer": null,
  "isAndroidSdkConfiguredCorrectly": true,
  "xcodeVer": "12.5.1",
  "xcodeprojLocation": "/opt/homebrew/lib/ruby/gems/3.0.0/bin/xcodeproj",
  "itunesInstalled": false,
  "cocoaPodsVer": "1.11.0",
  "isCocoaPodsWorkingCorrectly": true,
  "isCocoaPodsUpdateRequired": false,
  "pythonInfo": {
    "isInstalled": true,
    "isSixPackageInstalled": true
  }
}
Current CLI version:  8.0.2`

Happy to provide the full log if it helps. Any clues?

**Comment by rigor789** [comment]
I'm not sure how you installed CocoaPods, I would uninstall it, and then install it inside rosetta2 (or just `sudo arch -x86_64 gem install cocoapods`). The end goal is to have cocoapods as an x86_64 executable rather than an arm64 one - because so far it's had trouble running natively. 

The nativescript stack is fully working on arm64 - with the exception of cocoapods - which the CLI spawns with `arch -x86_64 pod install` to make sure it runs under rosetta...

You may need to install the ffi gem - users report it helps on M1: `sudo arch -x86_64 gem install ffi`

**Comment by LaKing** [comment]
I installed cocoapods by the docs on my M1, it works. Yes, those command line arguments are essential, ...

**Comment by angryloner** [comment]
I got it working!

I installed homebrew in my Rosetta terminal and followed the instructions in there, after first uninstalling cocoapods. 

Suspect I messed everything up by following the instructions in the M1 terminal first time around.

Thanks folks.
