### ISSUE TITLE
[ @nativescript/core ] [ NS 8 ] -- isIOS & isAndroid both return false

### ISSUE THREAD

**Issue by Ed-Simmons** [NativeScript/NativeScript#9537]
**Environment**
 - CLI: v8.0.2
 - @nativescript/core: v8.0.10
 - Android Runtime: v8.0.0
 - iOS Runtime:  v8.0.0

**Describe the bug**
Both the `isIOS` & `isAndroid` constants exported from @nativescript/core return false, regardless of platform.

**To Reproduce**
```ts
import { isIOS, isAndroid } from '@nativescript/core';

console.log('isIOS: ', isIOS)
console.log('isAndroid: ', isAndroid);
```
on both iOS and Android, the following is printed to the console:
```
isIOS: false
isAndroid: false
```

**Expected behavior**
The booleans should reflect the current platform, as is the case in NS 7.

**Additional context**
The following can be used as a workaround:

```ts
import { Application } from '@nativescript/core';

const _isAndroid = !! Application.android;
const _isIOS = !! Application.ios;
```

**Comment by rigor789** [comment]
@Ed-Simmons what is your `@nativescript/webpack` version? And what's in your `webpack.config.js`?

**Comment by Ed-Simmons** [comment]
Hi @rigor789,

```json
"@nativescript/webpack": "5.0.0-rc.6"
```

```js
const webpack = require("@nativescript/webpack");
const dotenv = require("dotenv");
module.exports = (env) => {
	webpack.init(env);
	const mode = !! env.production ? 'production' : 'development';

	dotenv.config()
    const isUppercase = key => key.toUpperCase() === key;
    const envKeys = Object.keys(env);
    let dotEnvValues = envKeys
        .filter(isUppercase)
        .reduce((memo, key) => {
            return {...memo, [key]: JSON.stringify(env[key])};
        }, {})

    const dotEnvkeys = Object.keys(process.env);
    dotEnvValues = dotEnvkeys
        .filter(isUppercase)
        .reduce((memo, key) => {
            if (memo[key]) {
                return memo;
            }

            return {...memo, [key]: dotEnvValues[key] || JSON.stringify(process.env[key])};
        }, {...dotEnvValues})

		// console.log(dotEnvValues);
		const definitiveEnv = {
			"global.TNS_WEBPACK": "true",
			"global.isAndroid": webpack.platform === 'android',
			"global.isIOS": webpack.platform === 'ios',
			"TNS_ENV": JSON.stringify(mode),
			"process": "global.process",
			...dotEnvValues
		}

		webpack.chainWebpack(config => {
			config.plugin('DefinePlugin').tap(args => {
			  Object.assign(args[0], definitiveEnv)
		
			  return args
			})
		})

	return webpack.resolveConfig();
};
```

**Comment by rigor789** [comment]
Yep, `webpack.platform` is always `undefined`.

These are the default defines: https://github.com/NativeScript/NativeScript/blob/3e2e5dfe9d8e33a0e76dc5cb15aad82caee682c3/packages/webpack5/src/configuration/base.ts#L347-L364

You should only extend them with:
```js
config.plugin('DefinePlugin').tap((args) => {
  args[0] = merge(args[0], {
    // add anything here
  });

  return args;
});
```

But note: webpack5 has built-in DotEnv support, just add a `.env` file & access with `process.env.VAR_NAME`.

**Comment by Ed-Simmons** [comment]
Oh wow, built-in dotenv! That's a game changer indeed.

I've run a little test this morning, and sure enough, I can reduce my webpack config down to the bare minumum which is lovely:

**Comment by felixkrautschuk** [comment]
@Ed-Simmons I think `isAndroid` & `isIOS` is working fine, except when used within `app.ts`. I also use the workaround in app.ts, but in other files `isAndroid` & `isIOS` are working as expected.

**Comment by rigor789** [comment]
@Ed-Simmons isn't it nice and clean? 🎉 

And yep those declares are fine - we're going to add them somewhere, just haven't found the right spot for them yet (should it be in core globals? or should it be in `@nativescript/webpack` somewhere since it's being added from there...?).

The ones from `@nativescript/core` are set to `global.isAndroid` which is also defined in the webpack config and should be correct even in `app.ts` - I wasn't able to reproduce the issue.

Speaking of which, you can use `global.isAndroid` and `global.isIOS` too...

But generally, I think we should perhaps hard-code these in core because we know them ahead of time, in `.ios.ts` we set `isIOS=true; isAndroid=false` and in `.android.ts` we set the opposite.
