### ISSUE TITLE
Basic hello world app errors out on tns preview

### ISSUE THREAD

**Issue by harshne** [NativeScript/NativeScript#9540]
Hello,

I opened up nativescript playground and wanted to develop locally using it.

upon going into my project folder and typing : tns preview i get the following error messages:

this is without any modification and base example app that is created by playground.

*****************************

$ tns preview
You are using the deprecated nsconfig.json file. Just be aware that NativeScript now has an improved nativescript.config.(js|ts) file for when you're ready to upgrade this project.
npm WARN deprecated @progress-nativechat/nativescript-nativechat@3.0.0: @progress-nativechat/nativescript-nativechat is now deprecated. See the README for the current instructions on how to add a NativeChat widget in a NativeScript app
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://github.com/thomasconner/javascript/tarball/67b7944366453a87226389d483ac1ad861e0e129
npm ERR! 404 
npm ERR! 404  'pubnub@https://github.com/thomasconner/javascript/tarball/67b7944366453a87226389d483ac1ad861e0e129' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'kinvey-nativescript-sdk'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/harry/.npm/_logs/2021-09-08T15_59_36_427Z-debug.log

********************************************

Any help is appreciated.

**Comment by janoshrubos** [comment]
Thank you for your issue!

  The Playground and the Preview app don’t support NativeScript 7,8 yet, the implementation is in progress. 
  We'll announce anything as usual on Twitter & a blog post, as well as post about it on Discord/Slack.

  By the time you can run your project on your device connected via USB with `ns run ios` or `ns run android`.

Closing this issue since there are a few about the playground/preview app.
