### ISSUE TITLE
runSbg fails silently on error

### ISSUE THREAD

**Issue by mrh1997** [NativeScript/NativeScript#9545]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.1 
 - Cross-platform modules: 8.0.3
 - Android Runtime: 8.0.0
 - iOS Runtime: - 
 - XCode Version: - 
 - Plugin(s): svelte-native-preprocessor, typescript

**Describe the bug**
When passing an invalid javascript file to runSbg it does neither generate output nor throw an error.

**To Reproduce**
Create a svelte native script with a ?. operator in the ``<page>`` area (see https://github.com/halfnelson/svelte-native/issues/234).
This is valid javascript code but runSbg will not produce any output

**Expected behavior**
Either produce a output file or throw an error.

**Sample project**
```python
<script lang="typescript">
  class Obj {
    header?: number = 9;
  }
  let obj: Obj;
</script>

<page>
  <stack-layout>
    <label text="TEST" />
    <label text={obj?.header} />
  </stack-layout>
</page>
```

If a project with this svelte-native component contains a JavaProxy it will not be updated by runSbg any more until ``{obj?.header}`` is replaced by ``obj ? obj.header : null}``

**Comment by rigor789** [comment]
Try the 8.1.0 android runtime, jsparser has been updated & I believe it should process the `?.` operator correctly now.

**Comment by mrh1997** [comment]
Correct. I tested 8.1.1 and it worked without problems.
