### ISSUE TITLE
Using Http.getFile with POST - body is always `undefined`

### ISSUE THREAD

**Issue by sudiptosen** [NativeScript/NativeScript#9553]
**Environment**
NativeScript: 7.2.1
@nativescript/core: 7.0.0
@nativescript/ios: 7.2.0
@nativescript/android:8.0.0

*Issue Description*
The goal is to do a POST request with a json body. The returned Response will be a File

----------------------------
Sample NS Code part
----------------------------

`Http.getFile(

 {
  url: testUrl, 
  method: 'POST',   
  content: JSON.stringify({data: 3000})
 })
.then((file: File) => {
        console.log(`Got the file from url: `, file);
 })
.catch(err => {
        console.log(`ERROR: `, err);
 });`

----------------------------
Sample Server Side (Express) Code
----------------------------
app.post('/file', (req, res) => {

  console.log('Received Body!', req.body);
  res.send({"data": 100}); 
  res.end();
})

Please note that for the sake of testing the server is not really sending back any File. We are just checking if we receive any body

**Expected behavior**
getFile will work with 'POST' and a valid Body received on the server side

**Comment by janoshrubos** [comment]
I checked your sample, but i think the problem is related to express.

With your example the request body is `undefined` on the server log, but you could try `body-parser` on the server side:

```
const bodyParser = require('body-parser');

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
```

I've got the expected result with this package. I hope it helps

**Comment by sudiptosen** [comment]
@janoshrubos Thanks for directing me to the right spot.  It is an Express Issue.

I was only using `app.use(express.json())` but was missing express.urlencoded({extended: true}).

Really appreciate the help.

PS: My apologies for bringing in an Express issue in this forum.

**Comment by janoshrubos** [comment]
@sudiptosen That's fine! I'm glad it is working for you!
