### ISSUE TITLE
Get error when use transparent for color and background-color. Error: Expected 1 or 4 constructor parameters.

### ISSUE THREAD

**Issue by anmaitrannguyen** [NativeScript/NativeScript#9559]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.1.1
 - Cross-platform modules: 8.1.3
 - Android Runtime: 8.1.0
 - iOS Runtime: 8.1.0
 - XCode Version:
 - Plugin(s):

**Describe the bug**
In new version, when I set the color or background-color with css or by attributewith the value "transparent", I will get this error:
Error: Failed to apply property [background] with value [transparent] to GridLayout(69). Error: Expected 1 or 4 constructor parameters.
For css, if I change from transparent to rgba(0,0,0,0), it will working. But for the inline attribute, like this:
<StackLayout
    background="rgba(0,0,0,0)"
  >
I will still get the above error:
Failed to apply property [background] with value [rgba(0, 0, 0, 0)] to GridLayout(69). Error: Expected 1 or 4 constructor parameters.
**To Reproduce**
<StackLayout
    background="rgba(0,0,0,0)"
  >
For css:
background: transparent;

**Expected behavior**
It should be working like before.
**Sample project**

**Additional context**

**Comment by rigor789** [comment]
I believe this was fixed by #9560 - since the merge, this was auto-released in version `8.1.3-next-09-22-2021-1260380904`, and will eventually land in a release soon.
