### ISSUE TITLE
[NS8.1] [IOS] App crashing with "unkown opcode" error

### ISSUE THREAD

**Issue by mahmoudajawad** [NativeScript/NativeScript#9564]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.1.2
 - Cross-platform modules: 8.1.1
 - Android Runtime: N/A
 - iOS Runtime: 8.1.0
 - XCode Version: 12.5.1
 - Plugin(s): N/A

**Describe the bug**
I'm working with a payment gateway that is available as a pod with name `NISdk`, and hitting a `unknown opcode` error, upon using its method `showCardPaymentViewWith` (method name is `showCardPaymentViewWithCardPaymentDelegateOverParentFor` after conversion to NS) with the following output in xcode:
```
->  0x105c04720: .long  0x00676e69                ; unknown opcode      Thread 1: EXC_BAD_INSTRUCTION (code=1, subcode=0x676e69)
    0x105c04724: fcmla.8h v5, v19, v18[1], #270
    0x105c04728: fmla   z18.h, p0/m, z3.h, z4.h
    0x105c0472c: .long  0x00677562                ; unknown opcode
    0x105c04730: .long  0x6f666e69                ; unknown opcode
    0x105c04734: ldnp   d0, d24, [x24, #-0x110]
    0x105c04738: .long  0x006e6d75                ; unknown opcode
    0x105c0473c: fnmls  z12.h, p1/m, z11.h, z22.h

```
 A quick search got me on this issue: https://github.com/mono/mono/issues/20533, which sounds like the problem as I'm currently using imac with m1 processor. The issue links to a PR (https://github.com/mono/mono/pull/20548) which resolves the issue, and now I'm wondering how can I test the same for NS.

**To Reproduce**
1. Create new project.
2. Install pod `NISdk` (Avoid using Nx workspace alas #9554)
3. Bind the following snippet to an action.
4. Build application with nativescript.
5. Run application in xcode, as ns would crash silently.
6. Hit the issue.
```
    const delegate: CardPaymentDelegate = {
      paymentDidCompleteWith: status => {
        console.log("paymentDidCompleteWith", status);
      },
      authorizationDidBegin: () => {},
      authorizationWillBegin: () => {},
      paymentDidBegin: () => {},
      threeDSChallengeDidBegin: () => {},
      threeDSChallengeDidCompleteWith: () => {}
    };
    NISdk.sharedInstance.showCardPaymentViewWithCardPaymentDelegateOverParentFor(
      delegate,
      Frame.topmost().viewController,
      order
    );
```

**Comment by mahmoudajawad** [comment]
@janoshrubos, this issue is causing a lot of hassle to me as I'm unable to get around it for my current work. Any chance you could guide me (or mention a person who could) on where these opcodes are located? I might try to add it myself, but a search on my own took me nowhere. Thanks.

**Comment by rigor789** [comment]
@mahmoudajawad I don't think the mono/mini issue is the same - NS does not do anything like that with opcodes. I think the more plausible issue is that the `NISdk` pod has not been compiled for arm64 iOS Simulators, which is required to m1 machines.

**Comment by mahmoudajawad** [comment]
@rigor789, that makes sense about why I couldn't find anything in ns classes about it. I need to dedicate more time understanding the internals of ns to avoid opening such issues. Thanks for answering.
