### ISSUE TITLE
pod install doesn't work on M1 processor

### ISSUE THREAD

**Issue by sebolio** [NativeScript/NativeScript#9569]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.1.2
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - XCode Version:
 - Plugin(s):

**Describe the bug**

I followed all [instructions](https://docs.nativescript.org/environment-setup.html#macos-ios) about macOS M1 + iOS, but two commands don't work:
```
> sudo arch -x86_64 gem install ffi
arch: posix_spawnp: gem: Bad CPU type in executable
```
and
```
> arch -x86_64 pod install
arch: posix_spawnp: pod: Bad CPU type in executable
```

And even tho I was able to create a project and install iOS emulator, when i run `tns run ios` it starts the emulator (an iPad, not and iPhone, i don't know why) but the app doesn't run, then I get the following message:
```
Installing pods...
arch: posix_spawnp: pod: Bad CPU type in executable
'arch install' command failed.
```

**To Reproduce**

Create an app following the instructions and try to launch it

**Expected behavior**
To work

**Sample project**

**Additional context**

**Comment by rigor789** [comment]
The main issue here is cocoapods, what usually works on M1 is to install cocoapods under rosetta2. I don't have an M1 currently to give you precise steps, but I went through the setup process on one before, and it did work.

The issue here seems to be that cocoapods has been installed as an arm64 binary - but a few months ago that did not work at all, so the cli invokes it with `arch -x86_64 pod install` - but that requires `cocoapods` to be installed as an x86_64 binary.

**Comment by cjohn001** [comment]
@tr4g : I just migrated my project to apple Silicon. I reinstalled my homebrew, ruby and cocoapods with ARM64 packages and I can say that those run (also against ios simulators). 
However, I had to update an old plugin which was not on @nativescript/core 8.1 yet. Not sure where the magic version boundary for core is. Seems like older plugin versions pull in non-universal binaries. I also found that the JSC runtime is currently not ARM64 compatible. I just opened in issue in this regards and hope that we will see a working version soon. Try to go with the latest runtime if you can.

**Comment by sudiptosen** [comment]
@cjohn001 can you please post the reinstall steps with `ARM64`. Really appreciate it. I have been struggling for days with this `@nativescript/firebase` plugin. Really appreciate it

**Comment by cjohn001** [comment]
@sudiptosen : firebase plugin is also not running for me on ARM64. I use the old version which does not have ARM64 binaries included. I also cannot run on ios simulator if ns app includes this package. regarding installing native binaries see rigor789 comment.
