### ISSUE TITLE
WrapLayout issue on Android device with API 21

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#957]
The following page:

``` xml
<Page loaded="onLoaded">
  <WrapLayout>
    <Button id="app" text="app" />
    <Button id="inline" text="inline" style="background-color: lightgreen;" />
    <Button id="page" text="page" />
    <Button id="property" text="property" />
    <Button id="import" text="import" />
  </WrapLayout>
</Page>
```

looks as expected on API 19.
![api_19](https://cloud.githubusercontent.com/assets/12251337/10578876/87bdf526-767d-11e5-92b7-772e7a146f2b.png)

But on API 21 seems like the wrap layout expands to the whole screen width with no need because the "APP" button has the same size as the "IMPORT" button:
![api_21](https://cloud.githubusercontent.com/assets/12251337/10578893/b856f39a-767d-11e5-945e-82c379ee63a4.png)

**Comment by vakrilov** [comment]
@vchimev 
I don't think it's bug. In Android Lollipop there is a default minWdith value for buttons. That's why the APP button is the same length as IMPORT.
The default style also makes all text upper-case.
