### ISSUE TITLE
Nativescript app doesn't show top bar in iOS emulator

### ISSUE THREAD

**Issue by erwindemoel** [NativeScript/NativeScript#9578]
I want to run our Nativescript app in the iOS emulator so I can make screenshots of different sizes. However, the top bar that shows the title and the back button isn't shown in the emulator. If I click on it, the button does work, but it's not visible.

How can we get the top bar to be visible in the emulator?

See here the difference:

Screenshot from iPhone:
![Screen 2](https://user-images.githubusercontent.com/40738900/134934078-84f025ef-ba1b-48e2-a795-d5684ec3f5e2.png)

Screenshot from emulator:
![Screen 2](https://user-images.githubusercontent.com/40738900/134934034-9543cb22-ccf3-48f0-aad8-c7c52e995a17.png)
:

**Comment by rigor789** [comment]
What is the iOS version on the phone/simulator? 

And what version of `@nativescript/core`? We've recently released some changes required for ios15 ActionBars here:
- https://github.com/NativeScript/NativeScript/pull/9530
- https://github.com/NativeScript/NativeScript/pull/9534
- https://github.com/NativeScript/NativeScript/commit/7e35fdf143894f473a5140ceec4f26326164f393

**Comment by erwindemoel** [comment]
I'm running the iPhone 11 Pro Max emulator. iOS 15.0.

"@nativescript/core": "~8.0.0",

**Comment by rigor789** [comment]
Ok, try `"@nativescript/core": "~8.1.0",` instead - it contains those ios15 changes, and should work as expected.

**Comment by kfw9257** [comment]
Is there a workaround for this issue for Nativescript 7? I can't upgrade to Nativescript 8 right now.

**Comment by rigor789** [comment]
> 
> 
> Is there a workaround for this issue for Nativescript 7? I can't upgrade to Nativescript 8 right now.

You can use something like patch-package and apply the fixes to `node_modules` directly. `patch-package` is to ensure to keep the changes/re-apply them after wiping node_modules.

Other option is to open a PR backporting the fixes - will require us to create a new branch to target for 7.x - let us know if you are interested.

**Comment by kfw9257** [comment]
@rigor789 Can we look into backporting the fixes?

**Comment by rigor789** [comment]
@kfw9257 sure, I created a new branch here: https://github.com/NativeScript/NativeScript/tree/release/7.x - this contains the latest 7.3.0 version of core, you can create a new PR targeting this branch with the fixes backported.

**Comment by erwindemoel** [comment]
I just updated the version to "@nativescript/core": "~8.1.0" but the top bar is still white in my simulator, instead of the intended color blue.
Do you have something else that can fix my issue?

**Comment by rigor789** [comment]
@erwindemoel can't think of anything else, perhaps if you can share a project where the issue happens we can investigate further.

**Comment by erwindemoel** [comment]
@rigor789 my apologies, I did something wrong with npm install. It works perfectly now, thanks!  👍  :-) I'll close the ticket.
