### ISSUE TITLE
list view IOS indexPathForSelectedRow() null and crashed

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#959]
Hi, I'm trying to use  indexPathForSelectedRow() but it crashed, the console log :

JS ERROR TypeError: listview.ios.indexPathForSelectedRow is not a function. (In 'listview.ios.indexPathForSelectedRow()', 

listview is already correct :
listview = page.getViewById('listview');

since I can access other functions

What I'm trying to do is return the changed background color to unselected after a tap

I did something wrong somewhere ? Thanks

**Comment by N3ll** [comment]
@x4080  - I tried to reproduce the error, but 'listview.ios.indexPathForSelectedRow()' is working fine. Can you please give some more information about what version of {N} you are using and maybe post more code.

**Comment by x4080** [comment]
Ill try again meanwhile the quick info is xcode 7.iphone 4s simulator on ios 9. If i cannot make it work ill try create simple source code to reproduce it

**Comment by x4080** [comment]
here is the simple source code i promise

main-page.xml
```
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageloaded">
  <GridLayout rows="20,50,*" columns="*" backgroundColor="red">
    <StackLayout row="1">
        <Button text="Cool app" tap="tap" color="White"/>        
    </StackLayout>
    <ListView items="{{myItems}}" row="2" left="0" top="0" id="content" itemTap="listViewItemTap">
        <ListView.itemTemplate>
          <StackLayout>
            <Label text="{{title}}"/>
          </StackLayout>
        </ListView.itemTemplate>
    </ListView>  
  </GridLayout>
</Page>
```

main-page.js
```
var dapplication = require('application');
var dlistview = require("ui/list-view");
var dgridlayout = require("ui/layouts/grid-layout");
var dlabel = require("ui/label");
var frameModule = require("ui/frame");
var page, firstload = false, listview;
var Observable = require('data/observable');
var ObservableArray = require('data/observable-array');
var bindingContext = new Observable.Observable({
    myItems: new ObservableArray.ObservableArray([]),
});
for (var i = 1; i <= 45; i++) {
    bindingContext.myItems.push({ title: "Title" + i });
}
function pageloaded(args) {
    if (!firstload) {
        firstload = true;
        page = args.object.page;
        page.bindingContext = bindingContext;
        listview = page.getViewById('content');
    }
}
exports.pageloaded = pageloaded;
function tap() {
    var a = listview.ios.indexPathForSelectedRow();
}
exports.tap = tap;
function listViewItemTap(args) {
    console.log(args.index); // minus the fake top margin
    console.log(listview.ios.indexPathForSelectedRow());
}
exports.listViewItemTap = listViewItemTap;

```

**Comment by N3ll** [comment]
Hi @x4080 , the reason it was working for me was that I used xcode 6. If you are using xcode 7 - you will have to use indexPathForSelectedRow as a property, due to some changes in Apple [documentation](https://developer.apple.com/library/prerelease/tvos/documentation/UIKit/Reference/UITableView_Class/index.html#//apple_ref/occ/instp/UITableView/indexPathForSelectedRow), and that's why you got JS ERROR TypeError: listview.ios.indexPathForSelectedRow is not a function.

If you are building your projects with lower version of xcode, the indexPathForSelectedRow() should be used as a function.

**Comment by x4080** [comment]
Oh i missed that, thanks for the tip. Ill try again

**Comment by enchev** [comment]
Hey folks,

Indeed in iOS 9 some methods are now properties and the best way to avoid problems is to check first if something is Function:
https://github.com/NativeScript/NativeScript/blob/master/ui/tab-view/tab-view.ios.ts#L86

Thanks

**Comment by x4080** [comment]
in relation with this issue, how can we generate the header file for iOS or android like the one you have for type script? Thanks

**Comment by N3ll** [comment]
Hey @x4080  - can you give some more information about what do you need to generate header files for? There are already generated .d.ts files for [iO](https://github.com/NativeScript/NativeScript/blob/master/ios.d.ts) and [Andorid](https://github.com/NativeScript/NativeScript/blob/master/android17.d.ts), which you can use.

**Comment by x4080** [comment]
Yes I mean when new ios or Android api change we can always just lookup at the .d.ts for the api much more easier than waiting for crash (joking aside) 

The d.ts are a great value for development. So I just reference to it and scratching my head why it won't work since already the right function

Thanks Nell
