### ISSUE TITLE
M1 issue with nativescript ios build

### ISSUE THREAD

**Issue by daydreamer95** [NativeScript/NativeScript#9591]
**Environment**
 - CLI:  tns
 - XCode Version: 12.5.1

{
  "nativescript": {
    "id": "com.writemedia.snookerquotients",
    "tns-android": {
      "version": "6.5.0"
    },
    "tns-ios": {
      "version": "6.5.3"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript-community/ui-share-file": "^1.2.2",
    "@nativescript/theme": "~2.3.0",
    "@nstudio/nativescript-camera-plus": "^3.0.7",
    "nativescript-angular": "~8.21.0",
    "nativescript-app-version": "^1.4.1",
    "nativescript-aws-sdk": "0.0.4",
    "nativescript-carousel": "^6.1.1",
    "nativescript-cscreenshot": "^1.0.2",
    "nativescript-downloader": "^2.1.5",
    "nativescript-image-cache-it": "^5.0.0-beta.20",
    "nativescript-insomnia": "^1.2.3",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-multiple-screen-css": "^1.0.1",
    "nativescript-ng-shadow": "^2.1.0",
    "nativescript-numeric-keyboard": "^4.3.1",
    "nativescript-orientation": "^2.2.5",
    "nativescript-secure-storage": "^2.6.1",
    "nativescript-share-file": "^1.0.6",
    "nativescript-videoplayer": "^4.2.1",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.5.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "~8.2.0",
    "nativescript-dev-webpack": "~1.5.0",
    "node-sass": "4.12.0",
    "tns-android": "6.5.0",
    "tns-ios": "6.5.3",
    "tns-platform-declarations": "^6.5.8",
    "typescript": "~3.5.3"
  }
}

**Describe the bug**

<img width="1440" alt="Screen Shot 2021-10-03 at 19 50 12" src="https://user-images.githubusercontent.com/38958256/135754414-65021100-06b2-4131-9ee4-fe90e3387095.png">

I got a problem while running and debugging a nativescript on Mac M1. The project running fine on my Mac 2013 Pro but got this error while running Xcode on M1  right after splash screen . Already try solution on internet but cant help. Im running Xcode using Rosseta mode.
If Im running "tns run ios" by CLI through visual studio code. The application shown the splash screen and suddenly shutdown.

**Comment by janoshrubos** [comment]
I believe `"tns-core-modules": "~6.5.0"` is outdated for Xcode 12. 

You can find more info on [NativeScript 6 & 7, Xcode 11 & 12, and IOS 14 Compatibility](https://blog.nativescript.org/nativescript-6-7-xcode-compatibility/)

**Comment by daydreamer95** [comment]
> I believe `"tns-core-modules": "~6.5.0"` is outdated for Xcode 12.
> 
> You can find more info on [NativeScript 6 & 7, Xcode 11 & 12, and IOS 14 Compatibility](https://blog.nativescript.org/nativescript-6-7-xcode-compatibility/)

At the time, I can't install Xcode 11 on M1 ( Its shown that not supported, please update to ver 12++). Is there a way to fix it so I can develop on my new macbook?

**Comment by rigor789** [comment]
@daydreamer95 I don't think you can run 6.x projects on M1 simulators without updating your project, unless you run on a connected device - that part should still work I believe.
