### ISSUE TITLE
Cant call function of object class in android native gradle library

### ISSUE THREAD

**Issue by Pauk1989** [NativeScript/NativeScript#9592]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.1
 - Android Runtime: 6.5.3

**Describe the bug**
Im trying to use native library included via gradle: 
compile "cloud.mindbox:mobile-sdk:1.1.0" 

But object-like class not working:

native library code:
```
package cloud.mindbox.mobile_sdk

import ...

object Mindbox {
    ...
    fun init(
        context: Context,
        configuration: MindboxConfiguration
    ) {
        ...
    }
    ...
}
```

my code: 
`cloud.mindbox.mobile_sdk.Mindbox.init(application.android.context, configuration);`

error:
```
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.demo/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: cloud.mindbox.mobile_sdk.Mindbox.init is not a function
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
System.err:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6944)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by triniwiz** [comment]
You can pass the lib through the[ dts-generator](https://github.com/NativeScript/android-dts-generator) to get the typings for the lib , another thing you can try is logging the methods/props available on the instance `console.dir(cloud.mindbox.mobile_sdk.Mindbox)`. Since Mindbox is an object try `cloud.mindbox.mobile_sdk.Mindbox.INSTANCE.init(application.android.context, configuration); `

**Comment by Pauk1989** [comment]
@triniwiz thank you very much,  it works! =)
