### ISSUE TITLE
Observable "subscribe" convenience function for named properties

### ISSUE THREAD

**Issue by alexziskind1** [NativeScript/NativeScript#96]
As of version 0.10, if I want to react to a change in an observable, I have to use "addEventListener" (or "on"). A more convenient way to react specifically to a property change event for a passed in property would be to have a "subscribe" function on observable.
It would look like this:
<pre>
Observable.prototype.subscribe = function(propName, callback) {
        this.addEventListener(knownEvents.propertyChange, function(changeObj){
            if (changeObj.propertyName == propName) {
                callback(changeObj);
            }
        });
    };
</pre>

All a client will have to do is just pass in the property name to watch and a callback like this:

<pre>
this.subscribe('message', function(changeObj){
            alert('message change triggered by subscribe');
        });
</pre>

I can create the pull request if this looks OK.

**Comment by N3ll** [comment]
So far there is not enough demand for this convenience function, so we are not planning on implementing it for now.

**Comment by dreambo8563** [comment]
+1 to use subscribe as rxjs
