### ISSUE TITLE
Upgrading from NativeScript Core from v5 - Cannot Navigate to page

### ISSUE THREAD

**Issue by SaadmanChowdhury** [NativeScript/NativeScript#9608]
Good evening,

I'm trying to upgrade a version 5 NativeScript project to version 8.
I began by first upgrading the project to 6, 
and then testing if all of the functionalities work before moving on to upgrading it further.
After TNS migrate, and resolving a few minor issues, I hit a snag.

After the login screen, when trying to navigate to another screen, the **topmost()** returns **undefined**.

I've used the debugger and realized that the **frame_stack_1** in **frame-common.js** is empty.
I think the reason is that the frames are not being pushed into frame_stack_1 when the app loads.

I checked out this guide 
https://nativescripting.com/posts/missing-frame-and-page
`platformNativeScriptDynamic({ createFrameOnBootstrap: true }).bootstrapModule(
  AppModule
);`
but it is for angular.

Is there was a similar method of making it work for NativeScript Core?

- I'm a new comer to NativeScript, and I would appreciate and help at all. ^_^

**Comment by OPADA-Eng** [comment]
The breaking changes between 5 and 8 are the key to upgrade successfully.
I suggest you clone a fresh project with the new dependencies and try to add your plugins one by one.
finally, move your code and try to modify the breaking changes.
