### ISSUE TITLE
iOS App crashes after force closing the app in version 8.1.1

### ISSUE THREAD

**Issue by DarkRanger66666** [NativeScript/NativeScript#9638]
### Issue Description

When I close the app forcefully, the I receive the Test flight pop up saying the app has crashed and send report. Even if I don't close the app forcefully. I randomly see the pop (probably when OS tries to kill the inactive app in background).

Here is the crash report:

Incident Identifier: D86E6CB9-9125-47CC-BCAA-D9E8C58D6F0A
Hardware Model:      iPhone9,3
Process:             pestiugyvedapp [77162]
Path:                /private/var/containers/Bundle/Application/408A1206-1F2E-40B2-8E0C-052D5B329377/pestiugyvedapp.app/pestiugyvedapp
Identifier:          com.bpbar.pestiugyved
Version:             1.0 (1.0.8)
AppStoreTools:       13A1030d
AppVariant:          1:iPhone9,3:15
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Non UI
Parent Process:      launchd [1]
Coalition:           com.bpbar.pestiugyved [5564]

Date/Time:           2021-11-03 04:40:03.3418 +0100
Launch Time:         2021-11-03 04:39:44.4713 +0100
OS Version:          iPhone OS 15.0.2 (19A404)
Release Type:        User
Baseband Version:    6.00.00
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Kernel Triage:
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get

Thread 0 name:
Thread 0 Crashed:
0   NativeScript                  	0x0000000103070968 0x102b84000 + 5163368
1   NativeScript                  	0x000000010306e778 0x102b84000 + 5154680
2   NativeScript                  	0x000000010307a4b8 0x102b84000 + 5203128
3   NativeScript                  	0x00000001030985ec 0x102b84000 + 5326316
4   NativeScript                  	0x0000000103097e08 0x102b84000 + 5324296
5   NativeScript                  	0x0000000103097538 0x102b84000 + 5322040
6   NativeScript                  	0x0000000103097878 0x102b84000 + 5322872
7   NativeScript                  	0x00000001030ef6c8 0x102b84000 + 5682888
8   NativeScript                  	0x000000010340628c 0x102b84000 + 8921740
9   NativeScript                  	0x00000001034540c8 0x102b84000 + 9240776
10  NativeScript                  	0x000000010339f598 0x102b84000 + 8500632
11  NativeScript                  	0x0000000103420fc8 0x102b84000 + 9031624
12  NativeScript                  	0x000000010339f598 0x102b84000 + 8500632
13  NativeScript                  	0x0000000103420fc8 0x102b84000 + 9031624
14  NativeScript                  	0x000000010339f598 0x102b84000 + 8500632
15  NativeScript                  	0x000000010339c578 0x102b84000 + 8488312
16  NativeScript                  	0x000000010348f848 0x102b84000 + 9484360
17  NativeScript                  	0x000000010339f598 0x102b84000 + 8500632
18  NativeScript                  	0x000000010339d36c 0x102b84000 + 8491884
19  NativeScript                  	0x000000010339d004 0x102b84000 + 8491012
20  NativeScript                  	0x0000000102e77a70 0x102b84000 + 3095152
21  NativeScript                  	0x0000000102e77058 0x102b84000 + 3092568
22  NativeScript                  	0x0000000102cca50c 0x102b84000 + 1336588
23  NativeScript                  	0x0000000102c2ded0 tns::ModuleInternal::LoadModule(v8::Isolate*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>,... + 1008 (ModuleInternal.mm:218)
24  NativeScript                  	0x0000000102c2d480 tns::ModuleInternal::LoadImpl(v8::Isolate*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, s... + 684 (ModuleInternal.mm:167)
25  NativeScript                  	0x0000000102c2cab8 tns::ModuleInternal::RequireCallback(v8::FunctionCallbackInfo<v8::Value> const&) + 484 (ModuleInternal.mm:118)
26  NativeScript                  	0x0000000102d2be60 0x102b84000 + 1736288
27  NativeScript                  	0x0000000102d2b360 0x102b84000 + 1733472
28  NativeScript                  	0x0000000102d2aaf8 0x102b84000 + 1731320
29  NativeScript                  	0x00000001034063cc 0x102b84000 + 8922060
30  NativeScript                  	0x000000010339f598 0x102b84000 + 8500632
31  NativeScript                  	0x000000010339d36c 0x102b84000 + 8491884
32  NativeScript                  	0x000000010339d004 0x102b84000 + 8491012
33  NativeScript                  	0x0000000102e77a70 0x102b84000 + 3095152
34  NativeScript                  	0x0000000102e77058 0x102b84000 + 3092568
35  NativeScript                  	0x0000000102cca50c 0x102b84000 + 1336588
36  NativeScript                  	0x0000000102c2d0d4 tns::ModuleInternal::RunModule(v8::Isolate*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 244 (ModuleInternal.mm:62)
37  NativeScript                  	0x0000000102c28234 tns::Runtime::RunMainScript() + 92 (Runtime.mm:135)
38  NativeScript                  	0x0000000102c5706c +[NativeScript start:] + 544 (NativeScript.mm:50)
39  pestiugyvedapp                	0x000000010210e9c4 0x102108000 + 27076
40  dyld                          	0x0000000102a00190 start + 444 (dyldMain.cpp:876)

Thread 1 name:
Thread 1:
0   libsystem_kernel.dylib        	0x00000001bd7c9550 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x00000001ddc06cb0 _pthread_cond_wait$VARIANT$mp + 1216 (pthread_cond.c:636)
2   NativeScript                  	0x00000001034d0790 0x102b84000 + 9750416
3   NativeScript                  	0x00000001034d03dc 0x102b84000 + 9749468
4   NativeScript                  	0x00000001034c864c 0x102b84000 + 9717324
5   libsystem_pthread.dylib       	0x00000001ddc00458 _pthread_start + 116 (pthread.c:890)
6   libsystem_pthread.dylib       	0x00000001ddbfeab0 thread_start + 8

Thread 2:
0   libsystem_pthread.dylib       	0x00000001ddbfea9c start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	0x00000001ddbfea9c start_wqthread + 0

No thread state (register information) available

Binary Images:
0x102108000 - 0x10222bfff pestiugyvedapp arm64  <ba00c739b0fb3ae983c79ebf7a28ebb0> /private/var/containers/Bundle/Application/408A1206-1F2E-40B2-8E0C-052D5B329377/pestiugyvedapp.app/pestiugyvedapp
0x1029e8000 - 0x102a3bfff dyld arm64  <d7a0282e93de3a1e981327e84517cc96> /usr/lib/dyld
0x102b84000 - 0x1035a3fff NativeScript arm64  <45d9e17873383e9299a00511ec219706> /private/var/containers/Bundle/Application/408A1206-1F2E-40B2-8E0C-052D5B329377/pestiugyvedapp.app/Frameworks/NativeScript.framework/NativeScript
0x1bd7c8000 - 0x1bd7f9fff libsystem_kernel.dylib arm64  <83a7e9554c943d9d9c1163fe9c36fbd7> /usr/lib/system/libsystem_kernel.dylib
0x1ddbfe000 - 0x1ddc0dfff libsystem_pthread.dylib arm64  <c685b49359ff3f13a9b33d3bb868ccd5> /usr/lib/system/libsystem_pthread.dylib

EOF

### Reproduction

Force close the app or wait for the system to kill it. Only happens on my iPhone 7 OS 15.0.2. Works fine on other iPhones

### Relevant log output (if applicable)

```shell
Incident Identifier: D86E6CB9-9125-47CC-BCAA-D9E8C58D6F0A
Hardware Model:      iPhone9,3
Process:             pestiugyvedapp [77162]
Path:                /private/var/containers/Bundle/Application/408A1206-1F2E-40B2-8E0C-052D5B329377/pestiugyvedapp.app/pestiugyvedapp
Identifier:          com.bpbar.pestiugyved
Version:             1.0 (1.0.8)
AppStoreTools:       13A1030d
AppVariant:          1:iPhone9,3:15
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Non UI
Parent Process:      launchd [1]
Coalition:           com.bpbar.pestiugyved [5564]

Date/Time:           2021-11-03 04:40:03.3418 +0100
Launch Time:         2021-11-03 04:39:44.4713 +0100
OS Version:          iPhone OS 15.0.2 (19A404)
Release Type:        User
Baseband Version:    6.00.00
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0


Kernel Triage:
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get


Thread 0 name:
Thread 0 Crashed:
0   NativeScript                  	0x0000000103070968 0x102b84000 + 5163368
1   NativeScript                  	0x000000010306e778 0x102b84000 + 5154680
2   NativeScript                  	0x000000010307a4b8 0x102b84000 + 5203128
3   NativeScript                  	0x00000001030985ec 0x102b84000 + 5326316
4   NativeScript                  	0x0000000103097e08 0x102b84000 + 5324296
5   NativeScript                  	0x0000000103097538 0x102b84000 + 5322040
6   NativeScript                  	0x0000000103097878 0x102b84000 + 5322872
7   NativeScript                  	0x00000001030ef6c8 0x102b84000 + 5682888
8   NativeScript                  	0x000000010340628c 0x102b84000 + 8921740
9   NativeScript                  	0x00000001034540c8 0x102b84000 + 9240776
10  NativeScript                  	0x000000010339f598 0x102b84000 + 8500632
11  NativeScript                  	0x0000000103420fc8 0x102b84000 + 9031624
12  NativeScript                  	0x000000010339f598 0x102b84000 + 8500632
13  NativeScript                  	0x0000000103420fc8 0x102b84000 + 9031624
14  NativeScript                  	0x000000010339f598 0x102b84000 + 8500632
15  NativeScript                  	0x000000010339c578 0x102b84000 + 8488312
16  NativeScript                  	0x000000010348f848 0x102b84000 + 9484360
17  NativeScript                  	0x000000010339f598 0x102b84000 + 8500632
18  NativeScript                  	0x000000010339d36c 0x102b84000 + 8491884
19  NativeScript                  	0x000000010339d004 0x102b84000 + 8491012
20  NativeScript                  	0x0000000102e77a70 0x102b84000 + 3095152
21  NativeScript                  	0x0000000102e77058 0x102b84000 + 3092568
22  NativeScript                  	0x0000000102cca50c 0x102b84000 + 1336588
23  NativeScript                  	0x0000000102c2ded0 tns::ModuleInternal::LoadModule(v8::Isolate*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>,... + 1008 (ModuleInternal.mm:218)
24  NativeScript                  	0x0000000102c2d480 tns::ModuleInternal::LoadImpl(v8::Isolate*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, s... + 684 (ModuleInternal.mm:167)
25  NativeScript                  	0x0000000102c2cab8 tns::ModuleInternal::RequireCallback(v8::FunctionCallbackInfo<v8::Value> const&) + 484 (ModuleInternal.mm:118)
26  NativeScript                  	0x0000000102d2be60 0x102b84000 + 1736288
27  NativeScript                  	0x0000000102d2b360 0x102b84000 + 1733472
28  NativeScript                  	0x0000000102d2aaf8 0x102b84000 + 1731320
29  NativeScript                  	0x00000001034063cc 0x102b84000 + 8922060
30  NativeScript                  	0x000000010339f598 0x102b84000 + 8500632
31  NativeScript                  	0x000000010339d36c 0x102b84000 + 8491884
32  NativeScript                  	0x000000010339d004 0x102b84000 + 8491012
33  NativeScript                  	0x0000000102e77a70 0x102b84000 + 3095152
34  NativeScript                  	0x0000000102e77058 0x102b84000 + 3092568
35  NativeScript                  	0x0000000102cca50c 0x102b84000 + 1336588
36  NativeScript                  	0x0000000102c2d0d4 tns::ModuleInternal::RunModule(v8::Isolate*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 244 (ModuleInternal.mm:62)
37  NativeScript                  	0x0000000102c28234 tns::Runtime::RunMainScript() + 92 (Runtime.mm:135)
38  NativeScript                  	0x0000000102c5706c +[NativeScript start:] + 544 (NativeScript.mm:50)
39  pestiugyvedapp                	0x000000010210e9c4 0x102108000 + 27076
40  dyld                          	0x0000000102a00190 start + 444 (dyldMain.cpp:876)

Thread 1 name:
Thread 1:
0   libsystem_kernel.dylib        	0x00000001bd7c9550 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x00000001ddc06cb0 _pthread_cond_wait$VARIANT$mp + 1216 (pthread_cond.c:636)
2   NativeScript                  	0x00000001034d0790 0x102b84000 + 9750416
3   NativeScript                  	0x00000001034d03dc 0x102b84000 + 9749468
4   NativeScript                  	0x00000001034c864c 0x102b84000 + 9717324
5   libsystem_pthread.dylib       	0x00000001ddc00458 _pthread_start + 116 (pthread.c:890)
6   libsystem_pthread.dylib       	0x00000001ddbfeab0 thread_start + 8

Thread 2:
0   libsystem_pthread.dylib       	0x00000001ddbfea9c start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	0x00000001ddbfea9c start_wqthread + 0


No thread state (register information) available

Binary Images:
0x102108000 - 0x10222bfff pestiugyvedapp arm64  <ba00c739b0fb3ae983c79ebf7a28ebb0> /private/var/containers/Bundle/Application/408A1206-1F2E-40B2-8E0C-052D5B329377/pestiugyvedapp.app/pestiugyvedapp
0x1029e8000 - 0x102a3bfff dyld arm64  <d7a0282e93de3a1e981327e84517cc96> /usr/lib/dyld
0x102b84000 - 0x1035a3fff NativeScript arm64  <45d9e17873383e9299a00511ec219706> /private/var/containers/Bundle/Application/408A1206-1F2E-40B2-8E0C-052D5B329377/pestiugyvedapp.app/Frameworks/NativeScript.framework/NativeScript
0x1bd7c8000 - 0x1bd7f9fff libsystem_kernel.dylib arm64  <83a7e9554c943d9d9c1163fe9c36fbd7> /usr/lib/system/libsystem_kernel.dylib
0x1ddbfe000 - 0x1ddc0dfff libsystem_pthread.dylib arm64  <c685b49359ff3f13a9b33d3bb868ccd5> /usr/lib/system/libsystem_pthread.dylib

EOF
```

### 

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
I believe this has been fixed in the ios runtime https://github.com/NativeScript/ns-v8ios-runtime/commit/57ec2ec012f5c9b5322be1e330cc3e747926bc0d

Closing, but if the issue still happens, feel free to let us know and we'll reopen it.
