### ISSUE TITLE
Support of Node.js Version 4.2.1

### ISSUE THREAD

**Issue by sittingbool** [NativeScript/NativeScript#972]
Since you just released a new version of nativescript I was very much hoping to be able to use it this time. Node.js version 4.2.1 is the first stable LTS version. I need it for node-server implementation on the same machine I want to use nativescript with. Its a MacOSX since I want to use iOS. But so far a lot of things like no support for Xcode 7 and therefore the iOS 9 Simulators and not being able to switch the simulators prevented me from even getting it running for a test. 
I appreciate the work you do. Nevertheless I can not use it in a stable environment so far. I can not use it for projects with real customers behind it. And you should really try to get to that point where people can use it for real to not waste your possible impact on the world of app development.
Starting with a stable installation on MacOSX because it is the only way to develop iOS apps. And despite it seams to work somehow under version 0.12.7 there are many error outputs ( e.g gyp WARN EACCES user "root" does not have permission to access the dev dir ). I think you should drop fibers. A better solution for synchronous code would be the deasync module. After that you should be able to go to node.js 4.2.1 support. Because this old 0.12 has so many bugs... it can cost you all your effort.

**Comment by alexrainman** [comment]
+1 for Node.js 4.x

**Comment by valentinstoychev** [comment]
Thanks @sittingbool - we recognize the importance of this and there is already a fix waiting for tetst in the master branch of the CLI. Please follow the progress here - https://github.com/NativeScript/nativescript-cli/issues/958. It is scheduled for 1.5 release, we will see if we can release it earlier.

**Comment by teobugslayer** [comment]
We decided to fast-track the change to support node 4.2.1 and include it in the next bug-fixing release - 1.4.3.

Our support for Xcode 7 iOS Simulator depends on another project. The required fixes are currently on a PR and once we test them, we will use them in the NativeScript CLI. This currently is scheduled for 1.5. You can track the progress [here](https://github.com/telerik/ios-sim-portable/pull/33).

**Comment by dtopuzov** [comment]
Node 4.2.1 support already release with 1.4.3. Xcode 7 iOS simulators will be shipped with 1.5.0 in few weeks.
