### ISSUE TITLE
Tap not working on elements in custom component

### ISSUE THREAD

**Issue by Whip** [NativeScript/NativeScript#9730]
### Issue Description

I have a custom component to share the action bar across the screens. Until a few days ago, everything worked fine but now `tap` is not working on elements in the custom component. Absolutely nothing happens when tapping the component. Everything works fine if I copy and paste the contents of the component directly on the page. 

I haven't changed anything since last time it was running. I've tried `ns clean` but it didn't help.

Here's my code

home/home-page.xml
```
<Page navigatingTo="onNavigatingTo" loaded="onLoaded" unloaded="onUnloaded" xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:customControls="shared">

	<ActionBar title="My App" class="action-bar">
		<customControls:actionbar />
	</ActionBar>
</Page>
```

home/home-page.js
```
export { toggleDrawer, toSearch, toCart } from '../functions.js';
```

shared/actionbar.xml
```
<android>
	<GridLayout columns="*,auto">
		<StackLayout orientation="horizontal" col="0">
			<Label class="mdi" text="&#xe5d2;" tap="toggleDrawer" />
			<Label text="My App" fontSize="20" />
		</StackLayout>
		<StackLayout orientation="horizontal" horizontalAlignment="right">
			<Label class="mdi" text="&#xe8b6;" tap="toSearch" fontSize="20" marginRight="5" />
			<AbsoluteLayout width="30" height="30" tap="toCart">
				<Label class="mdi" text="&#xe8cc;" left="0" top="5" fontSize="20" padding="0" />
				<Label text="{{ cartNumProducts }}" left="10" top="0" class="cartCounter" color="#000" visibility="{{ cartNumProducts > 0 ? 'visible' : 'collapsed' }}" />
			</AbsoluteLayout>
		</StackLayout>
	</GridLayout>
</android>
<ios>
	...
</ios>
```

/functions.js
```
import { Application, ApplicationSettings, Frame } from '@nativescript/core';

export function toggleDrawer() {
  const sideDrawer = Application.getRootView();
  sideDrawer.showDrawer();
}
export function toCart() {
  console.log('to cart');
  const sideDrawer = Application.getRootView(),
    rootFrame = Frame.getFrameById('root');
  rootFrame.navigate({
    moduleName: "cart/cart-page"
  });
  sideDrawer.closeDrawer();
}
export function toSearch() {
  const sideDrawer = Application.getRootView(),
    rootFrame = Frame.getFrameById('root');
  rootFrame.navigate({
    moduleName: "search/search-page"
  });
  sideDrawer.closeDrawer();
}
```

### Environment

```yaml
OS: macOS 11.6
CPU: (4) x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
Shell: /bin/zsh
node: 14.15.1
npm: 8.3.0
nativescript: 8.1.5

# android
java: 11.0.9.1
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 12.4/12D4e
cocoapods: 1.10.1
python: 2.7.16
python3: 3.8.2
ruby: 2.6.3
platforms: 
  - iOS 14.4
  - DriverKit 20.2
  - macOS 11.1
  - tvOS 14.3
  - watchOS 7.2
```

### Dependencies

```json
"dependencies": {
  "@nativescript-community/ui-collectionview": "^4.0.32",
  "@nativescript-community/ui-material-cardview": "^6.2.5",
  "@nativescript-community/ui-material-textfield": "^6.2.1",
  "@nativescript-community/ui-material-textview": "^6.2.5",
  "@nativescript-community/ui-pager": "^13.0.33",
  "@nativescript/core": "^8.1.5",
  "@nativescript/firebase": "^11.1.3",
  "@nativescript/theme": "^3.0.2",
  "@nstudio/nativescript-checkbox": "^2.0.4",
  "@nstudio/nativescript-loading-indicator": "^4.0.0",
  "@triniwiz/nativescript-image-cache-it": "^7.0.8",
  "@triniwiz/nativescript-image-zoom": "^4.1.1",
  "@triniwiz/nativescript-toasty": "^4.1.1",
  "@triniwiz/nativescript-youtubeplayer": "^4.1.4",
  "nativescript-exit": "1.0.1",
  "nativescript-gif": "^5.0.0",
  "nativescript-material-icons": "^1.0.3",
  "nativescript-permissions": "^1.3.11",
  "nativescript-phone": "^2.0.0",
  "nativescript-ui-autocomplete": "^7.0.2",
  "nativescript-ui-sidedrawer": "^9.0.3"
},
"devDependencies": {
  "@nativescript/android": "~8.1.1",
  "@nativescript/ios": "~8.1.0",
  "@nativescript/webpack": "~5.0.0-beta.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by Whip** [comment]
Just to be sure, I've created a test app with `ns create` using Sidenav template. Moved the actionbar into custom component and this behaviour can be replicated.

**Comment by rigor789** [comment]
> Just to be sure, I've created a test app with `ns create` using Sidenav template. Moved the actionbar into custom component and this behaviour can be replicated.

Can you attach a zip file of this test project? (`ns clean` then zip up and drop in issue).

**Comment by keerl** [comment]
@Whip does this happen on Android only? I may have encountered a similar thing recently. I didn't know what to do to fix the issue and ended up creating a new Android emulator and that seemed to get rid of the issue. That's not the only time it has happened though.

https://discord.com/channels/603595811204366337/828973479343947787/927025603201339432

**Comment by Whip** [comment]
Zip file attached.

@keerl Same behaviour on iOS as well. BTW I'm using real devices for both platforms.

[Test.zip](https://github.com/NativeScript/NativeScript/files/7836940/Test.zip)

**Comment by felixkrautschuk** [comment]
For me a similar issue exists since **@nativescript/webpack 5.0.3**.

When having an xml snippet like this:

snippets/snippet.xml
```
<GridLayout height="200" width="200" tap="myTestFunc">
    <Label text="TAP ME!"/>
</GridLayout>
```


And I use this snippet in a page:
main-page.xml
```
<Page xmlns:snippets="snippets"
      ...
    <StackLayout padding="20">
        <snippets:snippet/>
    </StackLayout>
</Page>
```


And that page defines the tap method of the snippet "myTestFunc"

main-page.ts
```
export function myTestFunc() {
  alert("Congrats!");
}
```

The tap event is not called since 5.0.3.

It was working until 5.0.2. This way we were able to share some xml snippets on several pages and those snippets could have different implementations of the tap event depending on where the snippet is used.

demo app:
[ns-webpack-tap-issue.zip](https://github.com/NativeScript/NativeScript/files/7846060/ns-webpack-tap-issue.zip)

**Comment by Whip** [comment]
But I'm using 5.0.0-beta.0 version of webpack

**Comment by DimitrisRK** [comment]
@Whip What if you create a `shared/actionbar.js` file and export functions from there?

**Comment by Whip** [comment]
I don't understand. I need to have XML in it, not javascript.

**Comment by manijak** [comment]
I can confirm this issue as well, on iOS. The `tap` events al of a sudden stopped working on all of partial views. Partial views are .xml only files containing layout that is then injected into a parent xml view that holds all logic as well. 

Moving the partial view code directly into the parent view, makes the event fire again.

This used to work for years, now suddenly it has stopped working. I do remember updating `@nativescript/webpack` the other day, so that could be the issue.

**Comment by chrisalexqm** [comment]
I have the same issue with layouts tap event on Android, i try with StackLayout, GridLayout, FlexboxLayout.

**Comment by Whip** [comment]
Awesome. I'll try it out. Can someone tell me how to update webpack? I've asked this [question](https://stackoverflow.com/questions/70389499/how-to-update-dev-plugin-in-nativescript) in several places but didn't get an answer.

**Comment by rigor789** [comment]
@Whip I'll be publishing an `rc` version shortly
