### ISSUE TITLE
Misspelled "platfrom" causes "Cannot read property 'toLowerCase' of undefined" error

### ISSUE THREAD

**Issue by Erudition** [NativeScript/NativeScript#9733]
### Issue Description

There is a misspelling in the code.

https://github.com/NativeScript/NativeScript/blob/c6bfc05bb766f2fca386b694a2cb464a13c99319/packages/core/cli-hooks/before-checkForChanges.js#L11

platfrom should be platform.

same with the lines above:

https://github.com/NativeScript/NativeScript/blob/c6bfc05bb766f2fca386b694a2cb464a13c99319/packages/core/cli-hooks/before-checkForChanges.js#L7

### Reproduction

with nativescript core it adds this hook automatically.

### Relevant log output (if applicable)

```shell
$ ns deploy
Cannot read property 'toLowerCase' of undefined
```

### Environment

```
$ npx -y nativescript-envinfo

ERROR: You must supply a command.
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by DimitrisRK** [comment]
This isn't the reason that this error is thrown. Variable names can be anything.
The problem must be deeper.

**Comment by rigor789** [comment]
Perhaps fixed by this commit: https://github.com/NativeScript/nativescript-cli/commit/0be52e914540898fa0cdc679edfa303192c812f7

Try `npm i -g nativescript@next`

**Comment by Erudition** [comment]
I agree, the fact that the misspelling is in the original assignment means it can't be the reason. Will have to dig deeper.
