### ISSUE TITLE
knownFolders at top level broken in alpha

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/NativeScript#9737]
with that change https://github.com/NativeScript/NativeScript/commit/88e355d8144cff4d13c59ac83cdbc2c00fd2fe35 all plugins accessing`knownFolders` at script top level are broken.
i understand the need for some framework to not initialize native apps at top level though it should still be the default for Nativescript.
it is totally fine to want to access knownFolders at top level.

i see multiple ways of fixing this: 
* use a webpack variable which defines wether native app is init at top level or in run. top level being the default. though this would work for N might still break plugins in capacitor or others.
* define nativeApp as a getter so that it gets defined when necessarry

**Comment by NathanWalker** [comment]
fixed via https://github.com/NativeScript/NativeScript/commit/7cf2653a2636b87cf03ef1ec914579a049cbb0f3
in 8.2.0-alpha.4
