### ISSUE TITLE
Android action bar hides behind status bar

### ISSUE THREAD

**Issue by gyan-nsf** [NativeScript/NativeScript#9741]
![ezgif-5-e40dba71c5](https://user-images.githubusercontent.com/56147171/149766181-0ed2aabe-9726-408e-83de-02c3a1cbc52b.gif)
### Issue Description

The action-bar hides behind status bar when TextView gets focus. but not in IOS

### Reproduction

ro reproduce clone this repo

https://github.com/gyan-nsf/ns-android-actionbar-issue

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by gyan-nsf** [comment]
Hi guys,
Any update on this ?

Thanks

**Comment by hitesh-nsf** [comment]
Facing the same issue... eagerly waiting for the solution...

**Comment by gyan-nsf** [comment]
Hi team,
Any update on this ?

Thanks

**Comment by gyan-nsf** [comment]
Hi There,
Any update on this please... ?

Thanks

**Comment by gyan-nsf** [comment]
Hi There,
Any update on this please... ?

Thanks

**Comment by CatchABus** [comment]
This is an issue that may occur even in native android apps that use a similar concept.
You can get rid of this problem by editing your `AndroidManifest.xml` file, and append this configuration to your activity:
```
android:windowSoftInputMode="adjustResize"
```
