### ISSUE TITLE
IOS Textfield height issue 

### ISSUE THREAD

**Issue by gyan-nsf** [NativeScript/NativeScript#9746]
### Issue Description

In IOS if text content is very large. The height of the textField get decreased on keyboard hide. This is very weird behaviour of textfield  in IOS.

see screen recording : https://1drv.ms/v/s!ArkRgzpSRrygg-1ZIiQHScM08rGXPw?e=hHehfj

note : adding NativeScript IQKeyboardManager Plugin does not ha any effect.

### Reproduction

git repo to reproduce 
https://github.com/gyan-nsf/ns-ios-textviewfield-issue

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by gyan-nsf** [comment]
Hi There,
 an update on this ?

Thanks

**Comment by gyan-nsf** [comment]
Hi There,
Any update on this please... ?

Thanks

**Comment by gyan-nsf** [comment]
Hi There,
Any update on this please... ?

Thanks

**Comment by gyan-nsf** [comment]
Hi There,
Any update on this please... ?

Thanks

**Comment by shirakaba** [comment]
The height of a child element in a vertical StackLayout is determined by its intrinsic height. TextField, though, because it involves text and scrolling, will have relatively complicated rules for determining intrinsic height that I'm not really familiar with.

It feels conceptually like the virtual keyboard is updating the TextField's height and NativeScript needs to refresh the layout to sync up its constraints with the new value (but isn't doing so). But if that were the case, then it doesn't explain why the TextField visually disappears yet tapping into it shows that there's still text. So I'm really unsure what's going on.

All I can suggest is to try migrating from StackLayout to GridLayout; does that happen to fix things?

**Comment by gyan-nsf** [comment]
Hi @shirakaba thanks for you reply. But  already tried with GridLayout. But its not working. Also i tried to find a native method  to redraw or repaint the TextView, but found nothing.

**Comment by shirakaba** [comment]
@gyan-nsf here's the method I call as a workaround to force a text reflow in one of my React NativeScript apps. I don't know whether it'll force a layout refresh (which is more what we need), but it might be worth a try anyway as there's not much to it:

https://github.com/shirakaba/nside/blob/8235d64020a439915dfc8c3c1581db4d27483279/app/console/ConsolePage.tsx#L95-L103

**Comment by farfromrefug** [comment]
@gyan-nsf i tested your sample and i see absolutely no issue when the keyboard is hiding or showing.
I tested on iOS 15 and iOS 12.
We will need to more details to be able to reproduce your issue

PS: please next time dont spam the issue thread. Doing what you did does not help your case. We wont look at it faster. Please keep in mind that this is  community driven project and that we cant answer you right away

**Comment by hitesh-nsf** [comment]
Hi @gyan-nsf,

I have partially fixed this issue and it's working fine with a tiny limitation. The solution is:

We need to write the request layout code in the constructor and it will fix the height hide-related issue.

TextView.prototype.requestLayout = function() {
      if (!arguments[0] && this.nativeViewProtected && this.nativeViewProtected.isFirstResponder) {
        this.nativeViewProtected.setNeedsLayout();
        IQKeyboardManager.sharedManager().reloadLayoutIfNeeded();
      } else {
         #View.prototype.requestLayout.call(this);
      }
    };

Also, the text-view will work under the scroll-view element and programmatically we need to adjust and control the double scroll in ios and android.

focus() {
    if (isIOS) {
      this.scrollViewElem.nativeElement.scrollToVerticalOffset(0, true);
      this.scrollViewElem.nativeElement.isScrollEnabled = false;
    }
  }

blur() {
    this.scrollViewElem.nativeElement.isScrollEnabled = true;
  }

PS: @farfromrefug I understand about his fast thread reply but kindly show some respect and ask him politely.

Thanks

**Comment by gyan-nsf** [comment]
@hitesh-nsf  thanks for your workaround. This works.
@farfromrefug my apologies if this issue thread disturbing you. But this is a real issue not a spam. Please see the screen recording in description box.

**Comment by farfromrefug** [comment]
@gyan-nsf i never said it was a spam. I just said trying to write everyday to 'bump' the issue wont help. And you will see this i all OSS issue threads.
@hitesh-nsf where was i not polite?

Now about your issue i dont see why you closed this. I never said your issue was not valid. I just said we need more details. Now seeing @hitesh-nsf comment i have to ask, is your issue only happening with `IQKeyboardManager` ?

**Comment by hitesh-nsf** [comment]
Hi @farfromrefug,

I didn't tryed it with any third-party keyboard manager and yes we are facing this issue with `IQKeyboardManager` right now.

For above statement maybe your intention was not that, but your selection of words telling your point in a different way or may be I get it wrong.

Sorry if I felt it wrong ...  Happy Coding.

Thanks

**Comment by hitesh-nsf** [comment]
As per my understanding till now, this same workaround is working perfectly fine with the text field element and creating issues with the text view element.

 So most probably issue should transfer to the native-script team.

**Comment by farfromrefug** [comment]
@hitesh-nsf `with the text field element and creating issues with the text view element` what do you mean? you mean your workaround does not work with `TextView` ? Do you mean you see the issue happens with `TextView` and without `IQKeyboardManager` ?
Please help us understand this better.
