### ISSUE TITLE
Modals appearing with white background in dark mode

### ISSUE THREAD

**Issue by monishakhapali** [NativeScript/NativeScript#9750]
### Issue Description

Hello everyone, Has anyone faced issues with Android dark mode, all the modals in the app have a white background in dark mode. Any one who knows the solution for this issue ?

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by farfromrefug** [comment]
i confirm the issue. i already mentioned it in another issue https://github.com/NativeScript/NativeScript/issues/8354
did not find the root cause yet

**Comment by CatchABus** [comment]
@monishakhapali Is your problem related to dialogs? https://v7.docs.nativescript.org/ui/dialogs

**Comment by farfromrefug** [comment]
@CatchABus The issue is happening with modals. Needs to check if it is still happening, but i would say it is.

**Comment by CatchABus** [comment]
> @CatchABus The issue is happening with modals. Needs to check if it is still happening, but i would say it is.

I'm asking because I can't reproduce this on modals, at least now.
Dialogs on the other hand are missing theme in styles.xml so they always turn light.

**Comment by farfromrefug** [comment]
@CatchABus actually i cant reproduce myself anymore :D So this issue is fixed for me

**Comment by rigor789** [comment]
I believe this is fixed and should work as expected on latest core `@nativescript/core@8.5.7` (at the time).
