### ISSUE TITLE
Build error- Error executing Static Binding Generator: File already exists. This may lead to undesired behavior

### ISSUE THREAD

**Issue by naveenkumarrepo** [NativeScript/NativeScript#9755]
### Issue Description

I'm Migrating my nativescript application to the current version. I'm getting this error "Error executing Static Binding Generator: File already exists. This may lead to undesired behavior.Please change the name of one of the extended classes."

my package.json

```json
{
  "name": "abcd",
  "main": "./src/main.ts",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.1.1",
    "@angular/common": "~13.1.1",
    "@angular/compiler": "~13.1.1",
    "@angular/core": "~13.1.1",
    "@angular/forms": "~13.1.1",
    "@angular/platform-browser": "~13.1.1",
    "@angular/platform-browser-dynamic": "~13.1.1",
    "@angular/router": "~13.1.1",
    "@mashdog/nativescript-accordion": "^7.0.6",
    "@nativescript/android": "^8.1.1",
    "@nativescript/angular": "^13.0.1",
    "@nativescript/core": "~8.1.1",
    "@nativescript/geolocation": "^8.0.2",
    "@nativescript/theme": "~3.0.1",
    "@ngtools/webpack": "^13.2.1",
    "@nstudio/nativescript-checkbox": "^2.0.4",
    "@nstudio/nativescript-loading-indicator": "^4.1.2",
    "nativescript-angular": "8.0.1",
    "nativescript-dev-webpack": "^1.5.1",
    "nativescript-drop-down": "^6.0.0",
    "nativescript-feedback": "^2.0.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-phone": "^3.0.2",
    "nativescript-plugin-firebase": "^10.6.3",
    "nativescript-ratings": "^1.0.1",
    "nativescript-ripple": "^4.0.1",
    "nativescript-ui-listview": "^10.0.2",
    "nativescript-youtubeplayer": "^3.0.1",
    "rxjs": "~7.4.0",
    "tns-core-modules": "^6.5.27",
    "tns-platform-declarations": "^6.5.15",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.1.1",
    "@angular/compiler-cli": "~13.1.1",
    "@nativescript/types": "~8.1.1",
    "@nativescript/webpack": "~5.0.0",
    "typescript": "~4.4.4"
  }
}
```

![Image20220201173458](https://user-images.githubusercontent.com/78412389/151974476-73075991-a286-456a-991a-96dbbba8c297.jpg)

when I run this command "ns build android --log trace" getting error as

<img width="931" alt="Image20220201173454" src="https://user-images.githubusercontent.com/78412389/151974680-6aed41df-e93b-40bf-a7d2-e0a91b7bf37b.png">

when I run this command "ns run android --log trace" getting error as

![Image20220201173443](https://user-images.githubusercontent.com/78412389/151974748-f876b4eb-8712-49b4-93dc-c089e92c8e91.jpg)

Also referred some solution but not getting possible solution. Please help me with the solution, where I'm getting the error and how to solve the error.

### Environment

Error executing Static Binding Generator: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
File:G:\abcd\platforms\android\app\src\main\java\com\tns\FragmentClass.java Class: com.tns.FragmentClass

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
Remove `"tns-core-modules": "^6.5.27",` from your package json, then `ns clean` and try running/building again.

If one of the plugins is still referencing `tns-core-modules` you will get an error, but that one is simpler to fix:
- either the plugin has an updated version that references `@nativescript/core` instead (the package name might have changed, some plugins have been moved to a scope)
- you can configure a webpack alias to resolve `tns-core-modules` as `@nativescript/core` which will often fix the errors - this is not configured by default because `tns-core-modules` have been deprecated for a few years, and are no longer supported in webpack5 officially...
  ```js
  const webpack = require('@nativescript/webpack')
  const { resolve } = require('path')
  
  module.exports = env => {
    webpack.init(env)
  
    // alias tns-core-modules -> @nativescript/core
    webpack.chainWebpack(config => {
      config.resolve.alias.set('tns-core-modules', '@nativescript/core')
    })
  
    return webpack.resolveConfig()
  }
  ```

**Comment by faisalansari20** [comment]
Thanks a lot @rigor789 , I ran into same issue and fortunately found this ticket with the solution
