### ISSUE TITLE
After upgrading to nativescript 1.4, ios build failed

### ISSUE THREAD

**Issue by eforth** [NativeScript/NativeScript#978]
cocoapods (0.39.0)
nativescript@1.4.2

Steps

1. tns create testapp
2. cd testapp
3. tns platform add ios
4. tns build ios

Output from tns buid ios
========================

Project successfully prepared
Build settings from command line:
    ARCHS = i386
    CONFIGURATION_BUILD_DIR = /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/emulator
    SDKROOT = iphonesimulator9.0
    SHARED_PRECOMPS_DIR = /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/sharedpch
    VALID_ARCHS = "i386"

=== BUILD TARGET testapp2 OF PROJECT testapp2 WITH CONFIGURATION Debug ===

Check dependencies
build-debug.xcconfig line 2: Unable to find included file "Pods/Target Support Files/Pods/Pods.debug.xcconfig"

PhaseScriptExecution NativeScript\ PreBuild build/testapp2.build/Debug-iphonesimulator/testapp2.build/Script-C97FD7AC1ADE5369004DB2A4.sh
    cd /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios
    /bin/sh -c /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/testapp2.build/Debug-iphonesimulator/testapp2.build/Script-C97FD7AC1ADE5369004DB2A4.sh
~/Projects/nativescript-apps/testapp2/platforms/ios/internal/metadata-generator/bin ~/Projects/nativescript-apps/testapp2/platforms/ios
Generating metadata for i386

~/Projects/nativescript-apps/testapp2/platforms/ios

Ld build/emulator/testapp2.app/testapp2 normal i386
    cd /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ervinforth/ApacheAnt/bin:/Users/ervinforth/android-sdk/tools:/Users/ervinforth/android-sdk/platform-tools:/Users/ervinforth/android-sdk/build-tools:/Applications/Genymotion\\ Shell.app/Contents/MacOS/:/Applications/Genymotion.app/Contents/MacOS/"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -L/Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/emulator -F/Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/emulator -F/Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/../../lib/iOS -filelist /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/testapp2.build/Debug-iphonesimulator/testapp2.build/Objects-normal/i386/testapp2.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=7.0 -Xlinker -objc_abi_version -Xlinker 2 -ObjC -sectcreate __DATA __TNSMetadata /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/emulator/metadata-i386.bin -lNativeScript -L/Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/internal/NativeScript/lib -licucore -lz -lc++ -framework Foundation -framework UIKit -framework CoreGraphics -framework MobileCoreServices -fobjc-arc -fobjc-link-runtime -Xlinker -dependency_info -Xlinker /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/testapp2.build/Debug-iphonesimulator/testapp2.build/Objects-normal/i386/testapp2_dependency_info.dat -o /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/emulator/testapp2.app/testapp2
ld: warning: directory not found for option '-F/Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/../../lib/iOS'
ld: can't open -sectcreate file: /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/emulator/metadata-i386.bin
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld build/emulator/testapp2.app/testapp2 normal i386
(1 failure)
Command xcodebuild failed with exit code 65

I noticed this all happened when I upgraded to version 1.4 of nativescript.

build-debug.xcconfig line 2: Unable to find included file "Pods/Target Support Files/Pods/Pods.debug.xcconfig"

Anybody have a similar issue?

**Comment by fealebenpae** [comment]
Hi @eforth,

The `Unable to find included file "Pods/Target Support Files/Pods/Pods.debug.xcconfig"` warning is benign and you can safely ignore it. The real issue here is that for some reason the metadata generation has failed: `ld: can't open -sectcreate file: /Users/ervinforth/Projects/nativescript-apps/testapp2/platforms/ios/build/emulator/metadata-i386.bin`.

I just performed these steps on my machine, running OS X 10.11.1, Xcode 7.1 from the App Store, nativescript@1.4.2 and CocoaPods 0.39.0, and it built fine. What's your environment like?

**Comment by eforth** [comment]
Xcode 7.0.1
Build version 7A1001

OS X El Captain
Version 10.11.1

**Comment by manijak** [comment]
I had the similar (if not the same) error right after I moved to El Capitan and XCode 7. 
Try giving your user more permissions to the platforms and/or ios folder (and sub-content). I gave my user read & write permission, plus added myself as the 'owner'. 
Then rebuild.

**Comment by eforth** [comment]
That didn't work but I'm going to upgrade my Xcode.

**Comment by x4080** [comment]
Hello, i also can confirm that i don't have this issue, im using nvm for node versioning

**Comment by TobiasHennig** [comment]
I have exactly the same problem with the last Xcode.

**Comment by ivanbuhov** [comment]
Hi @eforth, try building your project with the CLI and the standart error stream of metadata generator will be dumped in `{YourAppFolder}/platforms/ios/build/emulator/metadata-generation-stderr-i386.txt` (if you build the app from Xcode you can find the dumped output in you `DeriveData` folder). Can you share the contents of the file?

**Comment by x4080** [comment]
Oh maybe I should add I don't have cocoapod installed .maybe that is the issue ?

**Comment by TobiasHennig** [comment]
I have the problem with and without cocoapod installed. (I install it to solve the problem.)

**Comment by eforth** [comment]
Hi @ivanbuhov, the {YourAppFolder}/platforms/ios/build/emulator/metadata-generation-stderr-i386.txt file is empty.

**Comment by eforth** [comment]
Upgraded to Xcode 7.1 and also completely removed node, npm and all node modules (I know it's a bit drastic but I wanted to see if node or node modules might have caused the error).

##### system config:

OS X El Captain (version 10.11.1)
Xcode 7.1 (Build version 7B91b)
nvm (version 0.29.0)
node (version v0.12.7)
npm (version 2.11.3)
nativescript (version 1.4.3)```

I didn't install cocoapods however I will install later once the issue is fixed

The same error still occurs:

```ld: can't open -sectcreate file: /Users/ervinforth/Desktop/doula/platforms/ios/build/emulator/metadata-i386.bin```

**Comment by TobiasHennig** [comment]
I've made a clean OSX install, but i'm still unable to build an ios project.

My system:
* OSX El Capitan 10.11
* Xcode 7.0.1
* node 0.12.7
* npm 2.11.3
* nativescript 1.4.3

And after ...
```
tns run ios --emulator
```
... i get these errors:
```
...
ld: warning: directory not found for option '-F/Users/tobiashennig/Sites/tns-example/platforms/ios/../../lib/iOS'
ld: can't open -sectcreate file: /Users/tobiashennig/Sites/tns-example/platforms/ios/build/emulator/metadata-i386.bin
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld build/emulator/tnsexample.app/tnsexample normal i386
(1 failure)
Command xcodebuild failed with exit code 65
```

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#1103

**Comment by hvadotnarola** [comment]
@TobiasHennig can you try `tns emulate ios` ? I am able to run application with this.
