### ISSUE TITLE
core 8.2.0-alpha.1+ :  Binding: Run-time error occured in file: undefined at line: undefined and column: undefined

### ISSUE THREAD

**Issue by felixkrautschuk** [NativeScript/NativeScript#9785]
### Issue Description

When installing @nativescript/core 8.2.0-alpha.1 and newer (also latest 8.2.0-alpha.9), I see many binding errors in the console in Android and iOS.

`CONSOLE ERROR: Binding: Run-time error occured in file: undefined at line: undefined and column: undefined`

Mostly it happens when using nested bindings. Some of the occurencies of this error I am not able to explain or to reproduce, but at least I can reproduce it in one scenari with RadListView.

Let's assume this layout in XML:
```
<lv:RadListView items="{{ items }}">
        <lv:RadListView.itemTemplate>
            <StackLayout padding="15">
                <Label text="{{ 'id: ' + id }}"/>
                <Label text="{{ 'name: ' + name }}"/>
                <Label text="{{ authorInfo.name, 'author name: ' + authorInfo.name }}"/>     <!-- is causing the error message -->
            </StackLayout>
        </lv:RadListView.itemTemplate>
</lv:RadListView>
```

And I have this binding context of the page:
(just some dummy data...)
```
export const vm = fromObject({
  items: new ObservableArray([
    { id: 1, name: "Item 1", authorInfo: { id: 999, name: "Firstname Lastname"} },
    { id: 2, name: "Item 2", authorInfo: { id: 999, name: "Firstname Lastname"} },
    { id: 3, name: "Item 3", authorInfo: { id: 999, name: "Firstname Lastname"} },
    ...
  ])
});
```
then I see this error message when initially loading the page and when scrolling the list.

The error message is caused by this:
`<Label text="{{ authorInfo.name, 'author name: ' + authorInfo.name }}"/>` 

When removing the static string in that Label's text and do something like this: 
`<Label text="{{ authorInfo.name }}"/>` 
then the error message does not appear.

Note that this issue does NOT happen at all with @nativescript/core 8.2.0-alpha.0, only on newer versions.

### Reproduction

Get the demo app:
[ns-binding-issue.zip](https://github.com/NativeScript/NativeScript/files/8098272/ns-binding-issue.zip)

Run it -> you will see the error messages in the console.

### Relevant log output (if applicable)

```shell
CONSOLE ERROR: Binding: Run-time error occured in file: undefined at line: undefined and column: undefined
```

### Environment

not able to run that command for an unknown reason, so here is my package.json content instead:

{
  "name": "ns-binding-issue",
  "main": "app/app.ts",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@nativescript/core": "^8.2.0-alpha.9",
    "nativescript-ui-listview": "^10.0.2"
  },
  "devDependencies": {
    "@nativescript/android": "^8.2.0-alpha.11",
    "@nativescript/ios": "^8.2.0-alpha.6",
    "@nativescript/types": "~8.1.1",
    "@nativescript/webpack": "~5.0.0",
    "typescript": "~4.3.5"
  }
}

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
Likely related to the expression parser change here: https://github.com/NativeScript/NativeScript/pull/9734

Not sure if that syntax is supposed to work in the new parser, or an alternative should be used? /cc @DimitrisRK 

What's the difference between:
```js
{{ authorInfo.name, 'author name: ' + authorInfo.name }}
```
and
```js
{{ 'author name: ' + authorInfo.name }}
```
?

**Comment by DimitrisRK** [comment]
@felixkrautschuk @rigor789 It's not supposed to remove old features like this one.
This seems like a case I missed myself during testing, but I'll take a look at it as soon as possible.

**Comment by felixkrautschuk** [comment]
Thanks for your quick responses.

There are other situations where this error occurs as well, but those pages have some more complex layouts and I was not able to detemrine which part is causing the error log. Will need some time to find out, I am away from the computer for a few days.

**Comment by felixkrautschuk** [comment]
Thanks again for your pull request. I do not get the binding error on RadListView anymore.

I still get some binding errors in different scenarios, but the improved error logs help a lot, so I am closing this issue for now.

**Comment by DimitrisRK** [comment]
@felixkrautschuk Has the new version gotten rid of your view issues?
If anything comes up, we can check it.

**Comment by felixkrautschuk** [comment]
@DimitrisRK yes I see binding errors in the log in our apps, I still need to investigate why. At least I am now able to see which components are affected.
As soon as I am able to make the scenarios reproducable in a sample app, I will come back here.

**Comment by felixkrautschuk** [comment]
Let's assume we have a viewmodel that contains a field that may be an object or even null

```
export const vm = fromObject({
  customObject: null
});
```
and we have the following binding in XML:

```
<StackLayout visibility="{{ customObject ? 'visible' : 'collapse' }}">
    <Label text="{{ customObject.title }}"/>        <!--no binding error-->
    <Label text="{{ 'Title: ' + customObject.title }}"/>         <!--binding-error-->
    <Label text="{{ 'Description: ' + customObject.description }}"/>    <!--binding-error-->
</StackLayout>
```

I modified the sample app: 
[ns-binding-issue.zip](https://github.com/NativeScript/NativeScript/files/8179267/ns-binding-issue.zip)


If the object is null, I want to show nothing. If the object is defined, I want to show some fields from it.

It is actually working, but I get a binding error for the 2nd Label and the 3rd Label, but not for the 1st Label.
> JS: Binding: TypeError: Cannot read properties of null (reading 'title') at Label(7)@main-page.xml:20:13;
> JS: Binding: TypeError: Cannot read properties of null (reading 'description') at Label(8)@main-page.xml:21:13;

NativeScript 8.1.5 did not show a binding error at all.

When I remove that visibility binding from the StackLayout containing those Labels, I get a different result as well between 8.1.5 and alpha:

NS 8.1.5:
<img width="358" alt="Bildschirmfoto 2022-03-03 um 15 25 52" src="https://user-images.githubusercontent.com/6443021/156603363-06d501ff-bd5f-49a0-8a86-5c84d2b1ae56.png">

NS 8.2.0-alpha.12:
<img width="350" alt="Bildschirmfoto 2022-03-03 um 15 28 36" src="https://user-images.githubusercontent.com/6443021/156603459-4abf09db-b561-48e9-8e59-77c6d9c54c60.png">

(But not sure if that is really important... just a side note).


In our real apps there are some certain situations where the app is crashing due to a binding error using alpha (tested 10-12). This crash did not happen with NS 8.1.5.
But again, I need to make some further investigations to make that situation reproducable in a sample app.

**Comment by DimitrisRK** [comment]
@felixkrautschuk Your problem is related to expressions. Old expression parser was null-safe according to README here: https://www.npmjs.com/package/polymer-expressions, therefore it was completely silent in such cases.

In my latest patch, I added an `undefined-safe` mechanism in cases where the XML caller is `undefined` (caller could be `customObject` in your case) and perhaps I'll add a check for `null` values as well.

So how could this be taken care of using new parser?
The meaning of this rework was to fix old issues, add missing ECMA features, have better error reporting, and stop relying on an abandoned package source altogether.

You can solve such issues using optional chaining. Something like this could take care of warnings.
I'm planning to add a check for `null` callers but optional chaining will also be useful for sub-properties.
```xml
<StackLayout visibility="{{ customObject ? 'visible' : 'collapse' }}">
    <Label text="{{ customObject.title }}"/>        <!--no binding error-->
    <Label text="{{ 'Title: ' + customObject?.title }}"/>         <!--binding-error-->
    <Label text="{{ 'Description: ' + customObject?.description }}"/>    <!--binding-error-->
</StackLayout>
```
Automated null-safety is good but I believe it deprives one of control inside code.

**Comment by felixkrautschuk** [comment]
@DimitrisRK the "?" operator seems to do the trick in the sample project, thanks.

But in one of our projects, I get a strange binding error message as soon as I use the "?" operator.

```
<StackLayout>
        <Label text="{{ customObject?.test }}"/>
        <Label text="{{ 'Test ' + customObject?.test }}"/>
</StackLayout>
```

> CONSOLE ERROR: Binding: SyntaxError: Unexpected token (1:13) at Label(13)@pages/home/home-page.xml:22:9;

Event when I initially set customObject to a valid object like 
```
export const vm = fromObject({
    customObject: {
        test: "Test 1234"
    }
});
```

Not sure why it is working in the sample app from this then (and even in one production project).

Main differences in that project compared to the sample project here:
- still using NS Webpack 4.1.0 instead of 5.x.y
- Vanilla JS project instead of typescript

But even when downgrading NS webpack in the sample project (from this thread here) from 5.0.0 to 4.1.0, this error message does not come up there.
When creating a new JS project the error message also does not come up...

So unfortunately I am not able to provide a demo app for reproduction as I am not allowed to share that project where I get this error.

Do you have any idea what could cause this?

**Comment by DimitrisRK** [comment]
@felixkrautschuk Not really. Either way, I have worked on a patch here #9805 that includes a null-safe check which may get rid of your issue.
