### ISSUE TITLE
builder.load don't use css

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#981]
Hi, i'm using builder to dynamically load a view (page1.xml) the css in the page1.css is not updating the view, but if I move the css class into app.css, it display correctly, is this by design ?

Thanks

**Comment by N3ll** [comment]
Hey @x4080 - the method [load](https://docs.nativescript.org/ApiReference/ui/builder/README.html) of the builder takes as a a parameter LoadOptions. One of the optional parameters in the LoadOptions is [page](https://docs.nativescript.org/ApiReference/ui/builder/LoadOptions.html). By setting this parameter to the page, where you are loading the custom component in, will set tge page to which the CSS will be connected. 
Here is a [gist](https://gist.github.com/N3ll/959d25bced3db9b38182) of how the problem could be solved.

**Comment by x4080** [comment]
Oh i see, i was trying to load a layout instead of page. Can we still use css then? I solved it by setting css on the page i addchild to and works good

**Comment by enchev** [comment]
With the current implementation of our CSS support you need to have page since this is where we will load the CSS text/file.

**Comment by x4080** [comment]
Thanks for the explanation
