### ISSUE TITLE
Error while getting gradle data for android runtime from view command: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by lambourn** [NativeScript/NativeScript#9814]
### Issue Description

NS CLI 8.1.4 is installed, now our Android builds after @nativescript/android@8.2.0 was introduced. 

Obviously the `gradle` node is not existing in the published `package.json` but the ns build process does an `npm view @nativescript/android@8.2.0 gradle --json` which yields an empty string/JSON

### Reproduction

- install NS CLI 8.1.4 (Android Runtime android@8.1.1)
- create the most simplistic ns project
- build for Android

```
ns --version
8.1.4
ℹ New version of NativeScript CLI is available (8.1.5), run 'npm i -g nativescript' to update.

...
ns build android --log trace
...

Got gradle versions null from runtime v8.1.1
Exec npm view @nativescript/android  dist-tags --json 
 stdout: {
  "rc": "8.2.0-rc.0",
  "latest": "8.2.0",
  "alpha": "8.2.0-alpha.11"
}
 
 stderr: 
Exec npm view @nativescript/android@8.2.0  gradle --json 
 stdout:  
 stderr: 
Error while getting gradle data for android runtime from view command: SyntaxError: Unexpected end of JSON input
Exec npm config get registry 
```

or most specifically:
```
npm view @nativescript/android@8.2.0  gradle --json 
// no output!
```

```
npm view @nativescript/android@8.1.1  gradle --json 
{
  "version": "6.4",
  "android": "3.6.4"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by lambourn** [comment]
Due to this change, obviously (removal of the `gradle` object)
https://github.com/NativeScript/android-runtime/pull/1705/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by rigor789** [comment]
Please install `nativescript@next` (it's due to be published later today)

**Comment by rigor789** [comment]
@lambourn you could pin `@nativescript/android` version to 8.1.5 I guess - and bump to 8.2.0 once you have your CI setup updated?

**Comment by lambourn** [comment]
@rigor789 I would - but there is no published `@nativescript/android` version 8.1.5

**Comment by rigor789** [comment]
Sorry, I meant 8.1.1 - the previous stable version

**Comment by lambourn** [comment]
@rigor789 well, this is what we actually use as a pinned version, `@nativescript/android`@8.1.1

I just locally patched the `nativescript/lib/services/android-plugin-build-service.js` of the 8.1.4 CLI and added the missing bit and am able to build now.
```
// this was missing after line 433 in https://github.com/NativeScript/nativescript-cli/blob/1fc3893e5bff66816d195d28aeafa01f2649ba5d/lib/services/android-plugin-build-service.ts
runtimeGradleVersions = await this.getGradleVersions(projectRuntimeVersion);
```

**Comment by rigor789** [comment]
Added the `gradle` key back in `8.2.1` - It's not actually being used as far as I can tell - but we'll need to look around and phase it out in a future release.

https://github.com/NativeScript/android-runtime/commit/af925d50990820c9ca92a9a1a869518dbfd43fad

**Comment by lambourn** [comment]
@rigor789 thanks for the prompt resolution. I'll give it a try.

**Comment by rigor789** [comment]
Just looked a bit more into this - cli 8.2 should definitely fix this for older projects too (it's backwards compatible, so should be safe to upgrade the CLI whenever you can). I also just prepared a PR that changes the behavior slightly - to always try reading from the local runtime package.json before going to `npm view` - this should be hit 99.9% of the time (I guess?) and save some time by not going out to the npm registry. https://github.com/NativeScript/nativescript-cli/pull/5646

**Comment by lambourn** [comment]
Hey @rigor789 - nice, sounds great 🤘
