### ISSUE TITLE
shouldReplaceString on TextField breaks emoji keyboard input

### ISSUE THREAD

**Issue by JJVetter** [NativeScript/NativeScript#9816]
### Issue Description

[https://github.com/NativeScript/NativeScript/pull/9555](url)

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by serrg1994** [comment]
It's not only breaks emojis. The are problems with Url keyboard type. Please check this issue https://github.com/NativeScript/NativeScript/issues/10108

I also see this issue is closed but I face this error on 8.3.6, or these fixes will be published with next 8.3.7 release ?

**Comment by serrg1994** [comment]
BTW did somebody try if native UIKit textfield has the same issue with autofill ?

**Comment by rigor789** [comment]
Let's track this in https://github.com/NativeScript/NativeScript/issues/10108 so we don't have multiple issues about it.
