### ISSUE TITLE
After updating from nativescript 7 to latest version 8 preparing project fails

### ISSUE THREAD

**Issue by faisalansari20** [NativeScript/NativeScript#9817]
### Issue Description

After updating from nativescript 7 to latest version 8 preparing project fails for IOS & Android. I am not sure but it seems to be some webpack version issue. 

Below is how my package.json looks like

{
  "name": "@nativescript/template-hello-world-ng",
  "main": "./src/main.ts",
  "version": "7.0.2",
  "author": "NativeScript Team <oss@nativescript.org>",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "publishConfig": {
    "access": "public"
  },
  "keywords": [
    "nativescript",
    "mobile",
    "angular",
    "{N}",
    "template"
  ],
  "repository": "<fill-your-repository-here>",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "scripts": {
    "ngcc": "ngcc --properties es2015 module main --first-only",
    "postinstall": "./src/scripts/nativescript-camera/nativescriptCamera.sh",
    "android-build": "tns clean && tns prepare android && tns run android",
    "ios-build": "tns clean && tns prepare ios && tns run ios"
  },
  "nativescript": {
    "id": "com.atd.atdmobileapp",
    "tns-android": {
      "version": "6.5.3"
    }
  },
  "dependencies": {
    "@angular/animations": "~13.2.0",
    "@angular/common": "~13.2.0",
    "@angular/compiler": "~13.2.0",
    "@angular/core": "~13.2.0",
    "@angular/forms": "~13.2.0",
    "@angular/platform-browser": "~13.2.0",
    "@angular/platform-browser-dynamic": "~13.2.0",
    "@angular/router": "~13.2.0",
    "@dmi/camera": "file:./src/thirdPartyLibraries/camera",
    "@nativescript-community/ui-material-bottom-navigation": "^7.0.0",
    "@nativescript-community/ui-material-tabs": "^7.0.0",
    "@nativescript/angular": "^13.0.0",
    "@nativescript/auto-fit-text": "^1.0.1",
    "@nativescript/background-http": "^5.0.1",
    "@nativescript/core": "~8.2.0",
    "@nativescript/email": "^2.0.0",
    "@nativescript/firebase": "11.1.3",
    "@nativescript/iqkeyboardmanager": "^2.0.0",
    "@nativescript/local-notifications": "^5.1.0",
    "@nativescript/localize": "^5.0.2",
    "@nativescript/theme": "~2.3.0",
    "@nota/nativescript-accessibility-ext": "^7.0.3",
    "@nstudio/nativescript-cardview": "^2.0.0",
    "@nstudio/nativescript-pulltorefresh": "^3.0.1",
    "axios": "^0.23.0",
    "file-base64": "^1.0.0",
    "follow-redirects": "^1.13.2",
    "jspdf": "^2.1.1",
    "nativescript-appversion": "^1.4.4",
    "nativescript-barcodescanner": "^4.0.1",
    "nativescript-camera": "^4.5.0",
    "nativescript-clipboard": "^2.0.0",
    "nativescript-fingerprint-auth": "^7.0.2",
    "nativescript-gif": "^5.0.0",
    "nativescript-numeric-keyboard": "^5.0.0",
    "nativescript-orientation": "file:./src/thirdPartyLibraries/nativescript-orientation",
    "nativescript-permissions": "1.3.11",
    "nativescript-phone": "^2.0.0",
    "nativescript-secure-storage": "^2.6.2",
    "nativescript-speech-recognition": "^2.0.0",
    "nativescript-ui-calendar": "^7.0.2",
    "nativescript-ui-listview": "^9.0.2",
    "nativescript-videoplayer": "^5.0.1",
    "nativescript-xml2js": "^0.5.2",
    "pdfmake": "^0.1.68",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~7.5.0",
    "util": "^0.10.3",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.2.5",
    "@angular/cli": "~12.0.0",
    "@angular/compiler-cli": "~12.0.0",
    "@nativescript/android": "~8.2.1",
    "@nativescript/ios": "8.2.1",
    "@nativescript/schematics": "^11.2.0",
    "@nativescript/types": "~8.2.0",
    "@nativescript/webpack": "^5.0.6",
    "@ngtools/webpack": "13.0.0",
    "@schematics/angular": "^13.2.5",
    "tns-android": "6.5.3",
    "typescript": "~4.5.5"
  },
  "private": "true",
  "readme": "NativeScript Application"
}

### Relevant log output (if applicable)

```shell
Copying template files...
Platform ios successfully added. v8.2.1
Preparing project...
webpack is watching the files...
Error: Not supported
    at eval (eval at initializeCompilerCli (/Users/pragiti/Desktop/ATD/atd-mobile-apps/ATD/node_modules/@ngtools/webpack/src/ivy/plugin.js:527:41), <anonymous>:3:1)
    at AngularWebpackPlugin.initializeCompilerCli (/Users/pragiti/Desktop/ATD/atd-mobile-apps/ATD/node_modules/@ngtools/webpack/src/ivy/plugin.js:527:96)
    at /Users/pragiti/Desktop/ATD/atd-mobile-apps/ATD/node_modules/@ngtools/webpack/src/ivy/plugin.js:126:73
    at Hook.eval [as callAsync] (eval at create (/Users/pragiti/Desktop/ATD/atd-mobile-apps/ATD/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:17)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/pragiti/Desktop/ATD/atd-mobile-apps/ATD/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Users/pragiti/Desktop/ATD/atd-mobile-apps/ATD/node_modules/webpack/lib/Compiler.js:1148:28)
    at /Users/pragiti/Desktop/ATD/atd-mobile-apps/ATD/node_modules/webpack/lib/Watching.js:214:19
    at eval (eval at create (/Users/pragiti/Desktop/ATD/atd-mobile-apps/ATD/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /Users/pragiti/Desktop/ATD/atd-mobile-apps/ATD/node_modules/@nativescript/webpack/dist/plugins/WatchStatePlugin.js:22:13
    at Hook.eval [as callAsync] (eval at create (/Users/pragiti/Desktop/ATD/atd-mobile-apps/ATD/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/pragiti/Desktop/ATD/atd-mobile-apps/ATD/node_modules/tapable/lib/Hook.js:18:14)
    at run (/Users/pragiti/Desktop/ATD/atd-mobile-apps/ATD/node_modules/webpack/lib/Watching.js:168:33)
    at /Users/pragiti/Desktop/ATD/atd-mobile-apps/ATD/node_modules/webpack/lib/Watching.js:163:6
    at Compiler.readRecords (/Users/pragiti/Desktop/ATD/atd-mobile-apps/ATD/node_modules/webpack/lib/Compiler.js:973:5)
    at run (/Users/pragiti/Desktop/ATD/atd-mobile-apps/ATD/node_modules/webpack/lib/Watching.js:159:26)
    at Watching._go (/Users/pragiti/Desktop/ATD/atd-mobile-apps/ATD/node_modules/webpack/lib/Watching.js:218:3)
Executing webpack failed with exit code 1.
kunalishwe@kunals-MacBook-Pro ATD %
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
Make sure your angular dependencies match in versions, for reference here are the default versions in the updated templates:

```json
 "dependencies": {
    "@angular/animations": "~13.2.0",
    "@angular/common": "~13.2.0",
    "@angular/compiler": "~13.2.0",
    "@angular/core": "~13.2.0",
    "@angular/forms": "~13.2.0",
    "@angular/platform-browser": "~13.2.0",
    "@angular/platform-browser-dynamic": "~13.2.0",
    "@angular/router": "~13.2.0",
    "@nativescript/angular": "^13.0.0",
    "@nativescript/core": "~8.2.0",
    "@nativescript/theme": "~3.0.2",
    "rxjs": "~7.5.0",
    "zone.js": "~0.11.5"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.2.0",
    "@angular/compiler-cli": "~13.2.0",
    "@nativescript/types": "~8.2.0",
    "@nativescript/webpack": "~5.0.6",
    "@ngtools/webpack": "~13.2.0",
    "typescript": "~4.5.5"
  }
```
