### ISSUE TITLE
Xcode 13 support

### ISSUE THREAD

**Issue by adrian-niculescu** [NativeScript/NativeScript#9818]
### Issue Description

The first stable release of Xcode 13 was on 20 Sep 2021.
The NativeScript v8 iOS runtime is not yet compatible with it.
Please see the details here: https://github.com/NativeScript/ns-v8ios-runtime/issues/147 

### Environment

{ N } runtime: 8.1
OS: macOS Big Sur 11.6.1
Xcode: 13.2.1 (AppleClang 13.0.0.13000029)
Target: iOS 15.0.1 (physical device)

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
Hopefully it works as expected, definitely let us know if you run into issues!

**Comment by NathanWalker** [comment]
@adrian-niculescu Please let us know when you've had a chance to try it with latest RC as we will be curious to hear.

**Comment by jack-ayoka** [comment]
@NathanWalker @rigor789 our build system was upgraded to 13.3 today, and is now running into the following error:
```Generating metadata...~/connect-monorepo/packages/connect-app/platforms/ios/internal/metadata-generator/bin ~/connect-monorepo/packages/connect-app/platforms/ios
Python version: 2.7.18 (default, Jan  4 2022, 17:47:56)
[GCC Apple LLVM 13.0.0 (clang-1300.0.29.10) [+internal-os, ptrauth-isa=deployme
Traceback (most recent call last):
  File "./build-step-metadata-generator.py", line 41, in <module>
    deployment_target_flag_name = env("DEPLOYMENT_TARGET_CLANG_FLAG_NAME")
  File "./build-step-metadata-generator.py", line 14, in env
    return os.environ[env_name]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'DEPLOYMENT_TARGET_CLANG_FLAG_NAME'
Command Ld failed with a nonzero exit code
```
It seems that Xcode 13.3 changes the default linker if the app is targeting >= iOS 13.4, >= macOS 11, >= watchOS 7, or >= tvOS 14

**Comment by rigor789** [comment]
@jack-ayoka update `@nativescript/ios` to 8.2.1 - it should fix that.

**Comment by AntoineBouquet** [comment]
> @jack-ayoka update `@nativescript/ios` to 8.2.1 - it should fix that.

This solution fix the issue for me

**Comment by jack-ayoka** [comment]
Ah my apologies, I was getting nativescript runtime confused with the CLI version. Is there by chance a patch for the NS7 runtime? Attempting to migrate to NS8 seems to fail due to some webpack error that I could likely make a separate issue about, but i'd like to look into it more before wasting anyone's time.

**Comment by dnepromell** [comment]
I have the same issue on XCode 13.3 with Nativescript 7.2.0.
"@nativescript/ios": "7.2.0"

For now, I can't upgrade to 8 because some plugins are still incompatible.
Any suggestions?

Thanks.

**Comment by rigor789** [comment]
You can update the runtime only - you don't have to update the rest to NS8.

**Comment by dnepromell** [comment]
@rigor789 thank you very much!!! It works!

Upgraded to
"@nativescript/ios": "8.2.1"

**Comment by richardman1** [comment]
How about NS6? I have the same error as @jack-ayoka but am clueless on how to fix this?

**Comment by rigor789** [comment]
@richardman1 here's the changeset that added XCode 13.3 support: https://github.com/NativeScript/ns-v8ios-runtime/pull/150/files

You can likely apply the same(ish) using [patch-package](https://www.npmjs.com/patch-package) in your project.

**Comment by adrian-niculescu** [comment]
Please see https://github.com/NativeScript/ns-v8ios-runtime/issues/147#issuecomment-1101491591
