### ISSUE TITLE
View tag

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#985]
Hi it would be nice if we can add tag to views via xml (Property).it can be used for many things and Android ios have one built in

Or is it already there ?

**Comment by enchev** [comment]
Hey @x4080,

You can have expando on any of our components no matter if the component is declared in XML or in JavaScript. For example:

<Switch myCustomProp="someValue" />

HTH

**Comment by x4080** [comment]
Sorry i dont understand. I cant see the example?

**Comment by enchev** [comment]
```XML
<Page>
   <Label someCustomProperty="someValue" loaded="labelLoaded" />
</Page>
```
```JavaScript
exports.labelLoaded = function(args) {
   console.log("CUSTOM PROPERTY VALUE: " + args.object["someCustomProperty"])
}
```

**Comment by x4080** [comment]
Oh i didnt know we can do that. Very cool

**Comment by ligaz** [comment]
Can those expando properties be set from the XML? 

Regarding the `tag` property on iOS [it is recommended](https://developer.apple.com/library/ios/documentation/WindowsViews/Conceptual/ViewPG_iPhoneOS/CreatingViews/CreatingViews.html) as a faster way for searching for a given view. So it might be a good idea to introduce a `tag:number` property on our `View` class.

**Comment by enchev** [comment]
@ligaz my example is using XML actually :)

**Comment by ligaz** [comment]
Indeed, my bad ;)
