### ISSUE TITLE
Vue3 support?

### ISSUE THREAD

**Issue by AbrahamBrookes** [NativeScript/NativeScript#9864]
### Is your feature request related to a problem? Please describe.

I wish I could use vue3 with Nativescript. Is that on the roadmap?

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by shirakaba** [comment]
It's under development [here](https://github.com/rigor789/nativescript-vue-next). The last status update seems to be [this](https://github.com/rigor789/nativescript-vue-next/issues/384).

**Comment by rigor789** [comment]
It's now available in **beta**!

https://twitter.com/igor_randj/status/1599830172143788032
