### ISSUE TITLE
NativeScript 8.2 - Android 11+ file handle 'content://'

### ISSUE THREAD

**Issue by Siergiej29** [NativeScript/NativeScript#9871]
### Issue Description

I am in the process of creating dynamic forms with the possibility of sending files of various types, recognized by their extension.

I use the ui-document-picker plugin for this (or whatever else plugin may be).
Unable to read content from `content: //`

According to the information at [Nativescript Blog](https://blog.nativescript.org/nativescript-8-2-announcement/index.html#android-11%2B-file-handling)

> Android 11+ file handling
> If you had been targeting newer Android SDK's or devices you may have run into trouble with content: // uri's. 8.2 now properly handles those under the hood with the same existing file APIs. 

It should be possible to read the contents of the file from `content: //`, but it is not possible because it returns an error:

```JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'readSync' of null
JS: TypeError: Cannot read property 'readSync' of null
JS: at FileSystemAccess29.readSync (file: src \ webpack: \ ns-file-android11 ​​\ node_modules \ @nativescript \ core \ file-system \ file-system-access.android.js: 692: 0)
JS: at file: src \ webpack: \ ns-file-android11 ​​\ src \ app \ app.component.ts: 16:46
JS: at Array.forEach (<anonymous>)
JS: at file: src \ webpack: \ ns-file-android11 ​​\ src \ app \ app.component.ts: 15: 0
JS: at _ZoneDelegate.invoke (file: src \ webpack: \ ns-file-android11 ​​\ node_modules \ zone.js \ fesm2015 \ zone.js: 372: 0)
JS: at Object.onInvoke (file: src \ webpack: \ ns-file-android11 ​​\ node_modules \ @angular \ core \ fesm2015 \ core.mjs: 25548: 0)
JS: at _ZoneDelegate.invoke (file: src \ webpack: \ ns-file-android11 ​​\ node_modules \ zone.js \ fesm2015 \ zone.js: 371: 0)
JS: at Zone.run (file: src \ webpack: \ ns-file-android11 ​​\ node_modules \ zone.js \ fesm2015 \ zone.js: 134: 0)
JS: at file: ///data/data/org.nativescript.nsfileandroid11/files/app/vendor.js: ...
```
error:

```at FileSystemAccess29.readSync (file: src \ webpack: \ ns-file-android11 ​​\ node_modules \ @nativescript \ core \ file-system \ file-system-access.android.js: 692: 0)```

points to [file-system-access.android - 815](https://github.com/NativeScript/NativeScript/blob/c2503e3693b0a8b88b3f0414ec7fea62ddc6f89b/packages/core/file-system/file-system-access.android.ts#L815)

where `getOrSetHelper` returns `null` and therefore we cannot read the contents of the file.

Does Nativescirpt 8.2 really have the correct file handling for android 11?
This is probably not a plug-in problem, just core NS itself. 

### Reproduction

I have created a sample repository with the problem already in place

https://gitlab.com/NiepozornyJanusz/ns-file-android11

1. clone repo
2. npm i
3. tns/ns run android (11)
4. click on button and select file

example selected file uri: `content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2Fdom-opole.jpg`

### Environment

√ Component nativescript has 8.2.3 version and is up to date.
√ Component @nativescript/core has 8.2.2 version and is up to date.
× Component @nativescript/ios is not installed.
√ Component @nativescript/android has 8.2.2 version and is up to date.

```
Angular CLI:    13.2.7
Node            14.15.0
Java JDK        11.0.14.1
Gradle          7.4.1
Windows         11
Android API 30  11
```

```json
"dependencies": {
  "@angular/animations": "~13.2.0",
  "@angular/cli": "^13.2.0",
  "@angular/common": "~13.2.0",
  "@angular/compiler": "~13.2.0",
  "@angular/core": "~13.2.0",
  "@angular/forms": "~13.2.0",
  "@angular/platform-browser": "~13.2.0",
  "@angular/platform-browser-dynamic": "~13.2.0",
  "@angular/router": "~13.2.0",
  "@nativescript-community/ui-document-picker": "^1.1.12",
  "@nativescript/angular": "^13.0.0",
  "@nativescript/core": "8.2.2",
  "@nativescript/theme": "~3.0.2",
  "nativescript-envinfo": "^1.0.9",
  "rxjs": "~7.5.0",
  "zone.js": "~0.11.5"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~13.2.0",
  "@angular/compiler-cli": "~13.2.0",
  "@nativescript/android": "8.2.2",
  "@nativescript/types": "~8.2.0",
  "@nativescript/webpack": "~5.0.6",
  "@ngtools/webpack": "~13.2.0",
  "typescript": "~4.5.5"
}
```

### Please accept these terms

- [x] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by NathanWalker** [comment]
@Siergiej29 you can try this fix by setting your package.json to this:
```
"@nativescript/core": "8.2.3-alpha.0"
```
Please let us know if it works for you and upon confirmation we will publish the patch.

**Comment by Siergiej29** [comment]
Thank you for your time.

After updating `@nativescript/core` to version `8.2.3-alpha.0`, it seems that `getOrSetHelper` no longer returns `null` for `png` and `jpg` extensions, but for the others it does, and the following information also appears for different file extensions.
Any attempt to read the file returns `null`.

Ofc project was cleaned.

Updated in reproduction: https://gitlab.com/NiepozornyJanusz/ns-file-android11

Example code:

```Javascript
 data.files.forEach(selected => {
            let applicationContext = getNativeApplication().getApplicationContext();
            const getOrSetHelper: org.nativescript.widgets.FileHelper = org.nativescript.widgets.FileHelper.fromString(applicationContext, selected);
            console.log('##################');
            console.log('applicationContext', applicationContext);
            console.log('selected: ', selected);
            console.log('getOrSetHelper: ', getOrSetHelper);
            console.log('##################');

            const fileRead = getFileAccess().read(selected)
            console.log('### fileRead: ', fileRead);

            const readSync = getFileAccess().readSync(selected)
            console.log('### fileSync: ', readSync);

            const readText = getFileAccess().readText(selected);
            console.log('### fileReadText: ', readText);

            getFileAccess().readAsync(selected).then(
              readAsyncResolve => {
                console.log('### fileAsyncResolve: ', readAsyncResolve)},
              readAsyncRejected => {
                console.log('### fileAsyncRejected: ', readAsyncRejected)}
            );
          });
```

### PNG, JPG:
```
JS: ##################
JS: applicationContext com.tns.NativeScriptApplication@ac31395
JS: selected:  content://com.android.providers.downloads.documents/document/msf%3A45
JS: getOrSetHelper:  org.nativescript.widgets.FileHelper@319fc1a
JS: ##################
JS: ### fileRead:  null
JS: ### fileSync:  null
JS: ### fileReadText:  null
JS: ### fileAsyncRejected:  java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadStorageProvider uri content:
//com.android.providers.downloads.documents/document/msf:45 from pid=7539, uid=10195 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
```

### PDF, DOCX
```
JS: ##################
JS: applicationContext com.tns.NativeScriptApplication@ac31395
JS: selected:  content://com.android.providers.downloads.documents/document/msf%3A41
JS: getOrSetHelper:  null
JS: ##################
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'readSync' of null
JS: TypeError: Cannot read property 'readSync' of null
JS:     at FileSystemAccess29.readSync (file: src\webpack:\ns-file-android11\node_modules\@nativescript\core\file-system\file-system-access.android.js:693:0)
JS:     at file: src\webpack:\ns-file-android11\src\app\app.component.ts:24:46
JS:     at Array.forEach (<anonymous>)
JS:     at file: src\webpack:\ns-file-android11\src\app\app.component.ts:16:0
JS:     at _ZoneDelegate.invoke (file: src\webpack:\ns-file-android11...
```

### JPEG, XLSX, CSV
```
JS: ##################
JS: applicationContext com.tns.NativeScriptApplication@ac31395
JS: selected:  content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2F13598.jpeg
JS: getOrSetHelper:  null
JS: ##################
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'readSync' of null
JS: TypeError: Cannot read property 'readSync' of null
JS:     at FileSystemAccess29.readSync (file: src\webpack:\ns-file-android11\node_modules\@nativescript\core\file-system\file-system-access.android.js:693:0)
JS:     at file: src\webpack:\ns-file-android11\src\app\app.component.ts:24:46
JS:     at Array.forEach (<anonymous>)
JS:     at file: src\webpack:\ns-file-android11\src\app\app.component.ts:16:0
JS:     at _ZoneDelegate.invoke (file: src\webpack:\ns-file-android11\...
```



I wonder why there is a content to the file (PNG, JPG, PDF, DOCX) `content://com.android.providers.downloads.documents/document/msf%3A41`  once, and already with another extension (JPEG, XLSX, CSV) eg. `content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2F13598.jpeg`

**Comment by matteo6b** [comment]
In this pull request    return the path of the file that is necessary for openFile()  and the background-http plugin   and it works with android 11

https://github.com/palikollar/ns-device-import-activity/pull/1/commits/334453fd3d97b1ed4fde92549c02149c0a71fcf4

**Comment by Siergiej29** [comment]
## @nativescript/core: 8.2.6-alpha.0
### Downloads Folder
#### Can read all files (jpg, jpeg, png, pdf, doc, docx, xls, xlsx, csv, zip, txt, etc.), but has the wrong extension and name. eg. (msf:34)
 ```
JS: ==== CONTEXT START =========
JS: applicationContext com.tns.NativeScriptApplication@306289a
JS: selected:  content://com.android.providers.downloads.documents/document/msf:34
JS: getOrSetHelper:  org.nativescript.widgets.FileHelper@eb8652
JS: ==== CONTEXT END =========
JS:
JS: ==== READ START =========
JS: # read:  [B@a3857d9
JS: # readSync:  [B@652a04c
JS: # readText:  ����
JS: ==== READ END =========
JS:
JS: ==== SAVE START =========
JS: # saved file:  {
JS:   "_path": "/data/user/0/org.nativescript.nsfileandroid11/files/msf:34",
JS:   "_name": "msf:34",
JS:   "_extension": ".nsfileandroid11/files/msf:34"
JS: }
JS: # save size:  13120
JS: ==== SAVE END =========
```
### Documents Folder
#### Can read all document files (doc, docx, xls, xlsx, csv, etc.), but has the wrong extension and name. eg. (document:118)
 ```
JS: ==== CONTEXT START =========
JS: applicationContext com.tns.NativeScriptApplication@306289a
JS: selected:  content://com.android.providers.media.documents/document/document:118
JS: getOrSetHelper:  org.nativescript.widgets.FileHelper@6cb48bc
JS: ==== CONTEXT END =========
JS:
JS: ==== READ START =========
JS: # read:  [B@1f4a4cb
JS: # readSync:  [B@920bf66
JS: # readText:  PK♥♦
JS: # readAsynccResolve:  [B@5e4444b
JS: ==== READ END =========
JS:
JS: ==== SAVE START =========
JS: # saved file:  {
JS:   "_path": "/data/user/0/org.nativescript.nsfileandroid11/files/document:118",
JS:   "_name": "document:118",
JS:   "_extension": ".nsfileandroid11/files/document:118"
JS: }
JS: # save size:  25337
JS: ==== SAVE END =========
```
### SD-Card (External Storage) Folder
#### Can read image files (jpg, jpeg, png) correctly
 ```
JS: ==== CONTEXT START =========
JS: applicationContext com.tns.NativeScriptApplication@306289a
JS: selected:  content://com.android.externalstorage.documents/document/100D-3803:TestFolder/a75e8217491.jpg
JS: getOrSetHelper:  org.nativescript.widgets.FileHelper@482bd4c
JS: ==== CONTEXT END =========
JS:
JS: ==== READ START =========
JS: # read:  [B@893ce9b
JS: # readSync:  [B@4ee0f76
JS: # readText:  ����
JS: # readAsynccResolve:  [B@e45435f
JS: ==== READ END =========
JS:
JS: ==== SAVE START =========
JS: # saved file:  {
JS:   "_path": "/data/user/0/org.nativescript.nsfileandroid11/files/a75e8217491.jpg",
JS:   "_name": "a75e8217491.jpg",
JS:   "_extension": ".jpg"
JS: }
JS: # save size:  50826
JS: ==== SAVE END =========
```

#### Can not read other files (pdf, doc, docx, xls, xlsx, csv, zip, txt, etc.)
 ```
JS: ==== CONTEXT START =========
JS: applicationContext com.tns.NativeScriptApplication@306289a
JS: selected:  content://com.android.externalstorage.documents/document/100D-3803:TestFolder/liczniki.csv
JS: getOrSetHelper:  org.nativescript.widgets.FileHelper@dcc01cd
JS: ==== CONTEXT END =========
JS:
JS: ==== READ START =========
JS: # read:  null
JS: # readSync:  null
JS: # readText:  null
JS: # readAsyncRejected:  java.io.FileNotFoundException: /storage/100D-3803/TestFolder/liczniki.csv: open failed: EACCES (Permission denied)
JS: ==== READ END =========
JS:
JS: ==== SAVE START =========
JS: TypeError: Cannot read property 'length' of null
JS: # saved file:  {
JS:   "_path": "/data/user/0/org.nativescript.nsfileandroid11/files/liczniki.csv",
JS:   "_name": "liczniki.csv",
JS:   "_extension": ".csv"
JS: }
JS: # save size:  0
JS: ==== SAVE END =========
```

**Comment by triniwiz** [comment]
@Siergiej29 your save file method is using the name from the content uri passed, something like the following should correct that. Another patch will be out soon so you can test reading all types from the sd-card

```ts
function getFileNameFromContent(content: string) {
	const file = getFileAccess().getFile(content);
	return decodeURIComponent(file.name).split('/').pop().toLowerCase();
}
```

**Comment by NathanWalker** [comment]
@Siergiej29 thank you for your feedback. We have published another alpha which we believe will solve the last of the cases you mentioned, please try:
```
 @nativescript/core@8.2.6-alpha.1
```
then `ns clean`.

**Comment by adam2303** [comment]
@Siergiej29 I was also trying to do similar thing and I come up with this solution:
```ts
import {
        isAndroid,
	Application,
	AndroidApplication,
} from '@nativescript/core';
import { getNativeApplication } from '@nativescript/core/application';

// In openFileFunction
await requestPermission(PERMISSIONS.READ_EXTERNAL_STORAGE);
if (isAndroid) {
    const Intent = android.content.Intent;
    const picker = new Intent(Intent.ACTION_GET_CONTENT);
    picker.addCategory(Intent.CATEGORY_OPENABLE);
    picker.setType('*/*');
    const chooser = Intent.createChooser(picker, 'File Chooser');
    const activity =
	    Application.android.foregroundActivity ||
	    Application.android.startActivity;
    activity.startActivityForResult(chooser, 1);
    AndroidApplication.once('activityResult', async (ev: any) => {
	    const data = ev.intent.getData();
	    const context = getNativeApplication().getApplicationContext();
	    const documentData =
		    androidx.documentfile.provider.DocumentFile.fromSingleUri(
			    context,
			    data,
		    );
	    const fileName = documentData.getName();
	    const mimeType = documentData.getType();
	    const inputStream = context
		    .getContentResolver()
		    .openInputStream(data);
	    const fileBytes = inputStream.readBytes();
    });
}
```
It works for all types of storage on device and also for Google Drive.
Tested in on @nativescript/core@8.2.5.

**Comment by sitterrus** [comment]
> # Edit
> ## Problem solved on @nativescript/core: 8.2.6-alpha.2 !!!
> Thanks for help: @triniwiz && @NathanWalker
> 
> ## @nativescript/core: 8.2.6-alpha.2
> ### Downloads, Documents, External Storage Folder
> #### Can read and save all files (jpg, jpeg, png, pdf, doc, docx, xls, xlsx, csv, zip, txt, etc.)
> ```
> JS: ==== CONTEXT START =========
> JS: applicationContext com.tns.NativeScriptApplication@b340d87
> JS: selected:  content://com.android.externalstorage.documents/document/100D-3803:Moje Pliki/commit convention.docx
> JS: getOrSetHelper:  org.nativescript.widgets.FileHelper@79023ef
> JS: ==== CONTEXT END =========
> JS:
> JS: ==== READ START =========
> JS: # read:  [B@60413da
> JS: # readSync:  [B@7ec4901
> JS: # readText:  PK♥♦
> JS: # readAsynccResolve:  [B@2f71fc7
> JS: ==== READ END =========
> JS:
> JS: ==== SAVE START =========
> JS: # saved file:  {
> JS:   "_path": "/data/user/0/org.nativescript.nsfileandroid11/files/commit convention.docx",
> JS:   "_name": "commit convention.docx",
> JS:   "_extension": ".docx"
> JS: }
> JS: # save size:  32768
> JS: # orginal size:  16668
> JS: ==== SAVE END =========
> ```
> 
> I will ask another question.
> 
> What is the reason for such a large difference in the size of the original file and the saved one?
> 
> ```
> JS: # save size:  32768
> JS: # orginal size:  16668
> ```

Just opened up this project fresh on on Galaxy XCover 4s on Android 11 to test it and it doesnt seem to work on Documents folder, just Downloads. Did i miss something?

```
JS: ==== CONTEXT START =========
JS: applicationContext com.tns.NativeScriptApplication@f9910e4
JS: selected:  content://com.android.providers.media.documents/document/document:112
JS: getOrSetHelper:  null
JS: ==== CONTEXT END =========
JS: ==== READ START =========
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'readSync' of null
JS: TypeError: Cannot read property 'readSync' of null
JS:     at FileSystemAccess29.readSync (file: src/webpack:/ns-file-android11/node_modules/@nativescript/core/file-system/file-system-access.android.js:693:0)
JS:     at file: src/webpack:/ns-file-android11/src/app/app.component.ts:31:46
JS:     at Array.forEach (<anonymous>)
JS:     at file: src/webpack:/ns-file-android11/src/app/app.component.ts:22:0
JS:     at _ZoneDelegate.invoke (file: src/webpack:/ns-file-android11/node_modules/zone.js/fesm2015/zone.js:372:0)
JS:     at Object.onInvoke (file: src/webpack:/ns-file-android11/node_modules/@angular/core/fesm2015/core.mjs:25548:0)
JS:     at _ZoneDelegate.invoke (file: src/webpack:/ns-file-android11/node_modules/zone.js/fesm2015/zone.js:371:0)
JS:     at Zone.run (file: src/webpack:/ns-file-android11/node_modules/zone.js/fesm2015/zone.js:134:0)
JS:     at file: src/webpack:/ns-file-android11/node_modules/zone.js/fesm2015/zone.js:1275:0
JS:     at _ZoneDelegate.invokeTask (file:///data/data/or...
```

**Comment by Siergiej29** [comment]
thanks, known that 
I need the content of the file to be able to save it again in the application and then send it to the server

**Comment by adam2303** [comment]
@Siergiej29
If you need to save files in application directory then you can replace
```ts
const fileBytes = inputStream.readBytes();
```
with
```ts
const folder = knownFolders.temp().path;
const fileCopy = File.fromPath(path.join(folder, fileName));
const inChannel = inputStream.getChannel();
const outputStream = new java.io.FileOutputStream(fileCopy.path);
const outChannel = outputStream.getChannel();
inChannel.transferTo(0, inChannel.size(), outChannel);
```
in my solution. After that your can use `read` functions on `fileCopy`.

**Comment by mobifly-dev** [comment]
> ```ts
> const folder = knownFolders.temp().path;
> const fileCopy = File.fromPath(path.join(folder, fileName));
> const inChannel = inputStream.getChannel();
> const outputStream = new java.io.FileOutputStream(fileCopy.path);
> const outChannel = outputStream.getChannel();
> inChannel.transferTo(0, inChannel.size(), outChannel);
> ```

Only Adam solution works 100% at the moment in the latest NS code (~8.3.1) and Android platform (^8.3.0).  Latest version of @nativescript-community/ui-document-picker plugin does not work as expected due to core issues with media store feature unfortunately.

**Comment by pap5508** [comment]
@mobifly-dev :  i am facing the same issue on `@nativescript/core": "~8.3.4", @nativescript-community/ui-document-picker": "1.1.12", `

Could you please suggest which version works UI document picker?

**Comment by mobifly-dev** [comment]
> @mobifly-dev : i am facing the same issue on `@nativescript/core": "~8.3.4", @nativescript-community/ui-document-picker": "1.1.12", `
> 
> Could you please suggest which version works UI document picker?

For me the ui-document-picker does not work as expected on Android SDK 31+ and NS core 8.3.4, so used my own function based on Intents to pick document files on Android. I'm still using this on iOS.

**Comment by pap5508** [comment]
> > @mobifly-dev : i am facing the same issue on `@nativescript/core": "~8.3.4", @nativescript-community/ui-document-picker": "1.1.12", `
> > Could you please suggest which version works UI document picker?
> 
> For me the ui-document-picker does not work as expected on Android SDK 31+ and NS core 8.3.4, so used my own function based on Intents to pick document files on Android. I'm still using this on iOS.

Could please share it here? so that I can implement a similar way 
that would be great help!

**Comment by mobifly-dev** [comment]
@pap

> > > @mobifly-dev : i am facing the same issue on `@nativescript/core": "~8.3.4", @nativescript-community/ui-document-picker": "1.1.12", `
> > > Could you please suggest which version works UI document picker?
> > 
> > 
> > For me the ui-document-picker does not work as expected on Android SDK 31+ and NS core 8.3.4, so used my own function based on Intents to pick document files on Android. I'm still using this on iOS.
> 
> Could please share it here? so that I can implement a similar way that would be great help!

No problem. Here you are.
```
/**
 * Pick files compatible with Android SDK 31+
 *
 * @param multipleSelection
 * @param excludePaths
 */
export function pickFiles(multipleSelection: boolean = true, excludePaths: string[] = [], extensions?: string[]): Promise<Array<{ path: string, name: string, file: string, tmp: string }>> {
    return new Promise<Array<{ path: string; name: string; file: string; tmp: string }>>(async (resolve, reject) => {
        /**
         * Due to issues with Media Store and permissions on Android (11+).
         * See https://github.com/NativeScript/NativeScript/issues/9871
         * Custom native code works as expected at the moment. iOS can still
         * use document picker.
         */
        if (isAndroid) {
            await requestPermission(PERMISSIONS.READ_EXTERNAL_STORAGE);
            const
                Intent = android.content.Intent,
                picker = new Intent(Intent.ACTION_GET_CONTENT),
                chooser = Intent.createChooser(picker, "File Chooser"),
                activity = Application.android.foregroundActivity || Application.android.startActivity;

            picker.addCategory(Intent.CATEGORY_OPENABLE);
            if (typeof extensions === "undefined") {
                picker.setType('*/*');
            } else {
                picker.setType(extensions.map((ext) => android.webkit.MimeTypeMap.getSingleton().getMimeTypeFromExtension(ext)).join("|"));
            }
            if (multipleSelection) {
                // @ts-ignore
                picker.putExtra(android.content.Intent.EXTRA_ALLOW_MULTIPLE, true);
            }
            activity.startActivityForResult(chooser, 1);
            AndroidApplication.once(AndroidApplication.activityResultEvent, async (ev: any) => {
                try {

                    const
                        context = getNativeApplication().getApplicationContext(),
                        folder = knownFolders.temp().path,
                        files = [],
                        data = ev.intent.getData(),
                        clipData = ev.intent.getClipData();

                    if (clipData != null) {
                        for (let index = 0; index < clipData.getItemCount(); index++) {
                            let
                                uri = clipData.getItemAt(index).getUri(),
                                documentData = androidx.documentfile.provider.DocumentFile.fromSingleUri(context, uri),
                                fileName = documentData.getName(),
                                mimeType = documentData.getType(),
                                inputStream = context.getContentResolver().openInputStream(uri),
                                fileBytes = inputStream.readBytes(),
                                fileCopy = FileSystem.File.fromPath(FileSystem.path.join(folder, fileName)),
                                inChannel = inputStream.getChannel(),
                                outputStream = new java.io.FileOutputStream(fileCopy.path),
                                outChannel = outputStream.getChannel();

                            inChannel.transferTo(0, inChannel.size(), outChannel);

                            if (excludePaths.indexOf(fileCopy.path) !== -1) {
                                return;
                            }

                            let extension = FileSystem.File.fromPath(fileCopy.path).extension;

                            files.push({
                                path: fileCopy.path,
                                name: fileName,
                                file: fileName,
                                tmp: Utils.uid("") + extension
                            });
                        }
                    } else {
                        const
                            documentData = androidx.documentfile.provider.DocumentFile.fromSingleUri(context, data),
                            fileName = documentData.getName(),
                            mimeType = documentData.getType(),
                            inputStream = context.getContentResolver().openInputStream(data),
                            fileBytes = inputStream.readBytes(),
                            fileCopy = FileSystem.File.fromPath(FileSystem.path.join(folder, fileName)),
                            inChannel = inputStream.getChannel(),
                            outputStream = new java.io.FileOutputStream(fileCopy.path),
                            outChannel = outputStream.getChannel();

                        inChannel.transferTo(0, inChannel.size(), outChannel);

                        if (excludePaths.indexOf(fileCopy.path) !== -1) {
                            return;
                        }

                        const extension = FileSystem.File.fromPath(fileCopy.path).extension;

                        files.push({
                            path: fileCopy.path,
                            name: fileName,
                            file: fileName,
                            tmp: Utils.uid("") + extension
                        });
                    }

                    resolve(files);
                } catch (e) {
                    console.log(e);
                }
            });

        } else {
            FilePicker.openFilePicker({
                permissions: {
                    read: true,
                    persistable: true,
                    recursive: true,
                    write: true
                },
                cloud: true,
                multipleSelection,
                extensions
            }).then((selection) => {
                if (!selection.files.length) {
                    resolve([]);
                    return;
                }

                requestPermission(android.Manifest.permission.READ_EXTERNAL_STORAGE).then(() => {
                    const files = [];
                    selection.files.forEach(async (path) => {

                        const mediaStoreObject = await MediaStore.toFilePath(path);
                        if (!mediaStoreObject || excludePaths.indexOf(mediaStoreObject.filePath) !== -1) {
                            return;
                        }
                        const file = FileSystem.File.fromPath(mediaStoreObject.filePath);
                        files.push({
                            path: mediaStoreObject.filePath,
                            name: file.name,
                            file: file.name,
                            tmp: Utils.uid("") + file.extension
                        });
                    });

                    resolve(files);
                }).catch(() => {
                    reject("Required Android permission has been denied!");
                });
            }).catch((e) => {
                reject(e);
            });
        }
    });
}
```

**Comment by AkaeyesWanabe** [comment]
> @pap5508
> 
> > > > @mobifly-dev : i am facing the same issue on `@nativescript/core": "~8.3.4", @nativescript-community/ui-document-picker": "1.1.12", `
> > > > Could you please suggest which version works UI document picker?
> > > 
> > > 
> > > For me the ui-document-picker does not work as expected on Android SDK 31+ and NS core 8.3.4, so used my own function based on Intents to pick document files on Android. I'm still using this on iOS.
> > 
> > 
> > Could please share it here? so that I can implement a similar way that would be great help!
> 
> No problem. Here you are.
> 
> ```
> /**
>  * Pick files compatible with Android SDK 31+
>  *
>  * @param multipleSelection
>  * @param excludePaths
>  */
> export function pickFiles(multipleSelection: boolean = true, excludePaths: string[] = [], extensions?: string[]): Promise<Array<{ path: string, name: string, file: string, tmp: string }>> {
>     return new Promise<Array<{ path: string; name: string; file: string; tmp: string }>>(async (resolve, reject) => {
>         /**
>          * Due to issues with Media Store and permissions on Android (11+).
>          * See https://github.com/NativeScript/NativeScript/issues/9871
>          * Custom native code works as expected at the moment. iOS can still
>          * use document picker.
>          */
>         if (isAndroid) {
>             await requestPermission(PERMISSIONS.READ_EXTERNAL_STORAGE);
>             const
>                 Intent = android.content.Intent,
>                 picker = new Intent(Intent.ACTION_GET_CONTENT),
>                 chooser = Intent.createChooser(picker, "File Chooser"),
>                 activity = Application.android.foregroundActivity || Application.android.startActivity;
> 
>             picker.addCategory(Intent.CATEGORY_OPENABLE);
>             if (typeof extensions === "undefined") {
>                 picker.setType('*/*');
>             } else {
>                 picker.setType(extensions.map((ext) => android.webkit.MimeTypeMap.getSingleton().getMimeTypeFromExtension(ext)).join("|"));
>             }
>             if (multipleSelection) {
>                 // @ts-ignore
>                 picker.putExtra(android.content.Intent.EXTRA_ALLOW_MULTIPLE, true);
>             }
>             activity.startActivityForResult(chooser, 1);
>             AndroidApplication.once(AndroidApplication.activityResultEvent, async (ev: any) => {
>                 try {
> 
>                     const
>                         context = getNativeApplication().getApplicationContext(),
>                         folder = knownFolders.temp().path,
>                         files = [],
>                         data = ev.intent.getData(),
>                         clipData = ev.intent.getClipData();
> 
>                     if (clipData != null) {
>                         for (let index = 0; index < clipData.getItemCount(); index++) {
>                             let
>                                 uri = clipData.getItemAt(index).getUri(),
>                                 documentData = androidx.documentfile.provider.DocumentFile.fromSingleUri(context, uri),
>                                 fileName = documentData.getName(),
>                                 mimeType = documentData.getType(),
>                                 inputStream = context.getContentResolver().openInputStream(uri),
>                                 fileBytes = inputStream.readBytes(),
>                                 fileCopy = FileSystem.File.fromPath(FileSystem.path.join(folder, fileName)),
>                                 inChannel = inputStream.getChannel(),
>                                 outputStream = new java.io.FileOutputStream(fileCopy.path),
>                                 outChannel = outputStream.getChannel();
> 
>                             inChannel.transferTo(0, inChannel.size(), outChannel);
> 
>                             if (excludePaths.indexOf(fileCopy.path) !== -1) {
>                                 return;
>                             }
> 
>                             let extension = FileSystem.File.fromPath(fileCopy.path).extension;
> 
>                             files.push({
>                                 path: fileCopy.path,
>                                 name: fileName,
>                                 file: fileName,
>                                 tmp: Utils.uid("") + extension
>                             });
>                         }
>                     } else {
>                         const
>                             documentData = androidx.documentfile.provider.DocumentFile.fromSingleUri(context, data),
>                             fileName = documentData.getName(),
>                             mimeType = documentData.getType(),
>                             inputStream = context.getContentResolver().openInputStream(data),
>                             fileBytes = inputStream.readBytes(),
>                             fileCopy = FileSystem.File.fromPath(FileSystem.path.join(folder, fileName)),
>                             inChannel = inputStream.getChannel(),
>                             outputStream = new java.io.FileOutputStream(fileCopy.path),
>                             outChannel = outputStream.getChannel();
> 
>                         inChannel.transferTo(0, inChannel.size(), outChannel);
> 
>                         if (excludePaths.indexOf(fileCopy.path) !== -1) {
>                             return;
>                         }
> 
>                         const extension = FileSystem.File.fromPath(fileCopy.path).extension;
> 
>                         files.push({
>                             path: fileCopy.path,
>                             name: fileName,
>                             file: fileName,
>                             tmp: Utils.uid("") + extension
>                         });
>                     }
> 
>                     resolve(files);
>                 } catch (e) {
>                     console.log(e);
>                 }
>             });
> 
>         } else {
>             FilePicker.openFilePicker({
>                 permissions: {
>                     read: true,
>                     persistable: true,
>                     recursive: true,
>                     write: true
>                 },
>                 cloud: true,
>                 multipleSelection,
>                 extensions
>             }).then((selection) => {
>                 if (!selection.files.length) {
>                     resolve([]);
>                     return;
>                 }
> 
>                 requestPermission(android.Manifest.permission.READ_EXTERNAL_STORAGE).then(() => {
>                     const files = [];
>                     selection.files.forEach(async (path) => {
> 
>                         const mediaStoreObject = await MediaStore.toFilePath(path);
>                         if (!mediaStoreObject || excludePaths.indexOf(mediaStoreObject.filePath) !== -1) {
>                             return;
>                         }
>                         const file = FileSystem.File.fromPath(mediaStoreObject.filePath);
>                         files.push({
>                             path: mediaStoreObject.filePath,
>                             name: file.name,
>                             file: file.name,
>                             tmp: Utils.uid("") + file.extension
>                         });
>                     });
> 
>                     resolve(files);
>                 }).catch(() => {
>                     reject("Required Android permission has been denied!");
>                 });
>             }).catch((e) => {
>                 reject(e);
>             });
>         }
>     });
> }
> ```

your typescript file has no importation please could you give us the import header of this files, else it doesn't work.
