### ISSUE TITLE
Named methods for adding an event listerner

### ISSUE THREAD

**Issue by nsndeck** [NativeScript/NativeScript#99]
The problem:

Currently we have some shorthand methods that is used to add an event listener. These methods are named `on`. For example button has two such methods general `on(eventNames: string, callback, thisArgs?)` and `on(event: "tap", callback, thisArgs?)` - the second one is added only for intellisense support. Same is the situation with the View class which has two methods for intellisense (`loaded` and `unloaded`). Unfortunately these methods are overriden and when the user has an instance of button and write `button.on` he is able to see only button methods (general on and "tap"). In order to hook for the `loaded` event user should write (from version 1.0) `button.on(buttonModule.Button.loadedEvent, callback ....)`. This `loadedEvent` is a static string field defined in View class (which is OK), but it has a suffix `Event` and suffix does not work great with intellisense.

The solution (possible one):

Add named shorthand methods for adding an event listener. By convention these methods will start with `on` and `event name` after. For example to hook for the `tap` event of the button we will add method similar to `button.onTap(callback, thisArgs?)`. In that case when user write `button.on` will have all inherited events (loaded, unloaded, propertyChange) in the intellisense pop-up.

**Comment by hamorphis** [comment]
:100:

**Comment by atanasovg** [comment]
This sounds like a good solution to the described problem.
:100:

**Comment by nsndeck** [comment]
After a closer look I've found a show-stopper for this to be implemented right now. The problem is that our "View" class already has methods "onLoaded" and "onUnloaded". These methods should be protected, but anyway there is no way to add another public methods which will be a short-hands for adding event listeners for "loaded" and "unloaded" events. 

One option to solve this is to rename current `onLoaded` and `onUnloaded` methods to `onViewLoaded` and `onViewUnloaded` respectively.

Another options is to have a different name convention for shorthand methods that add an event listener. For example `addLoaded`.

Personally I prefer the first options, because our current code uses "on" as prefix for adding event handlers.

**Comment by hdeshev** [comment]
`onLoaded` sounds OK to me, even though it sounds like a handler name rather than an attaching method name. `addLoaded` looks like a collection method. Maybe we can consider something like `attachLoaded`?

**Comment by hshristov** [comment]
or setLoaded?

**Comment by vakrilov** [comment]
Page events - navigatedTo/From would also be problematic as there are onNavigatedTo/From methods.
