### ISSUE TITLE
HTTP DELETE requests do not send a body with the request

### ISSUE THREAD

**Issue by rob4226** [NativeScript/NativeScript#9903]
### Issue Description

It seems that HTTP DELETE requests do not send a body with the request. I ran into this issue in a shared Angular mobile/web project where the Angular web app sent the body with the HTTP DELETE request (like a POST would), but the NativeScript mobile app just ignored sending the body of the request. This is especially problematic for feature parity with Angular web because Angular added support for sending a body with a DELETE request last year [see issue/pr](https://github.com/angular/angular/issues/19438).  If you read this issue you will see that sending a body with a delete request is not required, nor is it disallowed per web specs, but seeing that Angular does send a body, it would be a good idea for NativeScript to also send an optional body.

So basically the following sends the body in Angular web, but not NativeScript Angular:
```typescript
this.httpClient.delete(
  `https://example.com/api/v1/user/delete-me/`,
  {
    body: {
      current_password: currentPassword,
    },
  }
)
.subscribe();
```
I tried a non-Angular `fetch` delete request with the same results, the body is ignored, so I guess it's not really Angular specific but NativeScript core that would need some work.

I'd be willing to work on it if someone could point me in the right direction on where to start.  Thank you!

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by Archez** [comment]
@rob4226 There was a recent PR to address this #9887. Expect the fix to be available in a future build.

**Comment by rob4226** [comment]
@Archez O ok that's great!  I'll close this issue then. Thank you.
