### ISSUE TITLE
Orientation Handling

### ISSUE THREAD

**Issue by jarrodwhitley** [NativeScript/NativeScript#9925]
### Is your feature request related to a problem? Please describe.

I want NativeScript to be able to force a specific orientation. Most apps are meant to only work in portrait mode so being able to force portrait mode is very important.

### Describe the solution you'd like

Add the setting and locking of a specific orientation.

### Describe alternatives you've considered

There is a paid plugin which supposedly offers this function, but this is such an essential function to mobile development that it needs to be something that NS can do on its own.

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
You can set `android:screenOrientation="portrait"` on the activity in App_Resources/Android/../AndroidManifest.xml to force the app to a portrait mode.

And I believe the equivalent on ios would be in the Info.plist:

```xml
<key>UISupportedInterfaceOrientations</key>
<array>
    <string>UIInterfaceOrientationPortrait</string>
</array>
<key>UISupportedInterfaceOrientations~iphone</key>
<array>
    <string>UIInterfaceOrientationPortrait</string>
</array>
<key>UISupportedInterfaceOrientations~ipad</key>
<array>
    <string>UIInterfaceOrientationPortrait</string>
</array>
```

**Comment by jarrodwhitley** [comment]
Awesome, thank you!
