### ISSUE TITLE
ApplicationSettings loses setting despite using flush()

### ISSUE THREAD

**Issue by cdroege** [NativeScript/NativeScript#9928]
### Description

We use `ApplicationSettings.setString('login-token', loginToken)` to save a login token after login and after this, we use `ApplicationSettings.flush()` to ensure that this setting is persisted. The latter call returns `true`, so the changes should be persisted.

This works correctly on iOS, but on Android there seems to be a problem:

### Expectation

The login token does not get lost even if the app crashes (or is terminated) shortly after using the above functions.

### Observation

If the app crashes or is terminated, the above setting is lost.

### Cause (IMHO)

I looked at the implementation of the [`ApplicationSettings.setString()`](https://github.com/NativeScript/NativeScript/blob/81f57dc0c249ea257985f349448ed7dd329ab933/packages/core/application-settings/index.android.ts#L59) and [`ApplicationSettings.flush()`](https://github.com/NativeScript/NativeScript/blob/81f57dc0c249ea257985f349448ed7dd329ab933/packages/core/application-settings/index.android.ts#L90) functions and I believe the following happens:

In the `ApplicationSettings.setString()` function, the [`apply()`](editor.apply();) function is used to asynchronously save the setting. This saves the setting to memory and in the background the setting will by persisted after a while. That seems correct.

But, if there is now a `ApplicationSettings.flush()` call the following code will be executed:

```
return sharedPreferences.edit().commit();
```

From the [documentation about `commit()`](https://developer.android.com/reference/android/content/SharedPreferences.Editor.html#commit()):

> Commit your preferences changes back from this Editor to the [SharedPreferences](https://developer.android.com/reference/android/content/SharedPreferences) object it is editing. This atomically performs the requested modifications, replacing whatever is currently in the SharedPreferences.

Without any changes to the Editor instance, I believe the Android implementation of `commit()` will do nothing (see line [554](https://github.com/aosp-mirror/platform_frameworks_base/blob/c5d02da0f6553a00da6b0d833b67d3bbe87341e0/core/java/android/app/SharedPreferencesImpl.java#L554), line [587](https://github.com/aosp-mirror/platform_frameworks_base/blob/c5d02da0f6553a00da6b0d833b67d3bbe87341e0/core/java/android/app/SharedPreferencesImpl.java#L587) and line [752](https://github.com/aosp-mirror/platform_frameworks_base/blob/c5d02da0f6553a00da6b0d833b67d3bbe87341e0/core/java/android/app/SharedPreferencesImpl.java#L752) of the Android implementation) and I believe even changing a dummy value would be enough to trigger a write of all outstanding changes from previous `apply()` calls. So to make the implementation easier, the Nativescript implementation of the `flush()` function for Android could be something like:

```js

const FLUSH_DUMMY_KEY = "NS_DUMMY_KEY_FOR_ENFORCED_COMMIT1234"

export function flush(): boolean {
	ensureSharedPreferences();

	const editor = sharedPreferences.edit();
        // Without any changes, a commit() will do nothing, so we need to set
        // a dummy value to enforce a complete commit()
        editor.putInt(FLUSH_DUMMY_KEY, Date.now());
        return editor.commit();
}
```

But that might break some applications, if they do not expect any unknown keys (so it might be a good idea to remove this key from `getAllKeys()`). Other ideas:

2. Add a dummy key like above, call `apply()` then remove that key and then call `commit()`
3. Add a parameter to the `ApplicationSettings.set*` functions to switch between `apply()` and `commit()`, but that change would be a little bit larger and would change the API.

If you want, I can create a PR to fix this issue, but I am unsure what the best solution would be

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by CatchABus** [comment]
I don't really understand the problem here. Does your app terminate or crash couple of milliseconds after storing your token?
I also store an API token during login and never came across such an issue. How realistic is that scenario you describe?

Also, according to Android docs for method `apply` and its asynchronous execution:
```
You don't need to worry about Android component lifecycles and their interaction with apply() writing to disk. The framework makes sure in-flight disk writes from apply() complete before switching states.
```
