### ISSUE TITLE
CSS does not support new lowercase element names

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/NativeScript#993]
Since {N} 1.4 I can now use `<text-field>` instead of `TextField`, but if I try to style `text-field` the CSS rules are not applied; I have to use `TextField`.

Can the CSS implementation be updated to support the new lowercase, hyphen-separator element names?

Thanks.

**Comment by priyangamani** [comment]
Is there any solution???

**Comment by priyangamani** [comment]
lowercase class file is not supported in nativescript

**Comment by priyangamani** [comment]
CSS does not support new lowercase element names
