### ISSUE TITLE
Unable to compile while using in svelte native

### ISSUE THREAD

**Issue by krishnaTORQUE** [NativeScript/NativeScript#9957]
### Issue Description

I just make new ns project (svelte native) then installed this plugin & its not compiling.

### Reproduction

I just make new ns project (svelte native) then installed this plugin & its not compiling.

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
I was unable to reproduce with a fresh app:

![Screenshot 2022-07-27 at 11 07 04 AM](https://user-images.githubusercontent.com/879060/181208579-d946fbf5-33c5-4c73-b9ed-f537e5b0ef2f.png)

Please include your error messages if you are still having them.
